### ISSUE TITLE
Error after selecting dropdownmenu - data from sqflite

### ISSUE THREAD

**Issue by stahlie** [flutter/flutter#32174]
1. ...You can view my code at https://github.com/stahlie/pilotvoice       I'm having trouble with selecting item from dropdownmenu.   As you can see in CustomScreen.dart, there's futurebuilder.   so whenever I select the item from Airport name listing (this dropdownmenu is the only one retrieving datas from Sqflite database)...   

This is what it originally looks like....

![Screenshot_20190506-193248](https://user-images.githubusercontent.com/36582972/57261648-b47ac380-7036-11e9-8739-458be090a8f1.jpg)

I pressed the Airport dropdown menu and got the listing of Airport Name (It was retrieved from database)

![Screenshot_20190506-193253](https://user-images.githubusercontent.com/36582972/57261646-b2b10000-7036-11e9-844b-f6c7c09d7e77.jpg)

After selecting an item from the list...it produced this error..

![Screenshot_20190506-193303](https://user-images.githubusercontent.com/36582972/57261644-ae84e280-7036-11e9-8ddf-3503a67ec24c.jpg)

Here's the error log:

I/flutter (27661): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (27661): The following assertion was thrown building FutureBuilder<List<AirportModel>>(dirty, state:
I/flutter (27661): _FutureBuilderState<List<AirportModel>>#f9fc2):
I/flutter (27661): 'package:flutter/src/material/dropdown.dart': Failed assertion: line 560 pos 15: 'items == null ||
I/flutter (27661): items.isEmpty || value == null || items.where((DropdownMenuItem<T> item) => item.value ==
I/flutter (27661): value).length == 1': is not true.
I/flutter (27661): 
I/flutter (27661): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (27661): more information in this error message to help you determine and fix the underlying cause.
I/flutter (27661): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (27661):   https://github.com/flutter/flutter/issues/new?template=BUG.md
2. ...
3. ...

## Logs

```
```

```
```

```
C:\Users\Matt\AndroidStudioProjects\pilotvoice>flutter doctor -v
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.706], locale en-US)
    • Flutter version 1.2.1 at C:\src\flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Matt\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code (version 1.30.2)
    • VS Code at C:\Users\Matt\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • SM G950U • 9887e048383342515a • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

**Comment by BaderEddineOuaich** [comment]
Hmm.. looks like the dropdown doesn't accept null value items. cleaning the list could be a solution.  in line <strong>69</strong> add the <pre>.where((eachItem)=>eachItem != null).toList()</pre> as the following
<pre>
                      FutureBuilder<List<AirportModel>>(
                        future: db.getAllAirports(),
                        builder: (BuildContext context, AsyncSnapshot<List<AirportModel>> snapshot) {
                          if (!snapshot.hasData) return CircularProgressIndicator();
                           return DropdownButton<AirportModel>(items: snapshot.data.map((airportItem) =>
                                DropdownMenuItem<AirportModel>(
                                  child: Text(airportItem.airportName),
                                  value: airportItem,
                                ))
                                .where((eachItem)=>eachItem != null).toList(),// will clean list from null values.
                            onChanged: (AirportModel value) {
                              setState(() {
                                if (snapshot.hasData) debugPrint(
                                    "--------- snapshot is ${snapshot.data}");
                                _currentAirport = value;
                                selectedAirport = _currentAirport.airportName;
                              });
                            },
                            value: _currentAirport,
                            hint: Text("Airport"),
                          );
}),
</pre>

**Comment by stahlie** [comment]
Thanks.  I added it and it still give me the same error.  The first time dropdownmenu populated the list with the data from db.getAllAirports() without any problem as you can see the 2nd screenshot above.  What's interesting is that whenever I select the item in that airport, it refired the db.getAllAirports() .

Anyway... the error is actually coming from dropdown.dart in line 560 (here's the code):
 assert(items == null || items.isEmpty || value == null || items.where((DropdownMenuItem<T> item) => item.value == value).length == 1),
       assert(elevation != null),
       assert(iconSize != null),
       assert(isDense != null),
       assert(isExpanded != null),
       super(key: key);

I can't figure out what is creating the null.  This is where I've been stuck and couldn't figure out what I'm doing wrong.

**Comment by BaderEddineOuaich** [comment]
Aha! i noticed that in the dropdown.dart line <strong>629</strong> says the hint displays if the value is null. so if you show the hint only when the selected value is null could be the solution. check out this
<pre>
                 FutureBuilder>(
                        future: db.getAllAirports(),
                        builder: (BuildContext context, AsyncSnapshot> snapshot) {
                          if (!snapshot.hasData) return CircularProgressIndicator();
                           return DropdownButton(items: snapshot.data.map((airportItem) =>
                                DropdownMenuItem(
                                  child: Text(airportItem.airportName),
                                  value: airportItem,
                                )).toList()
                            onChanged: (AirportModel value) {
                              setState(() {
                                if (snapshot.hasData) debugPrint(
                                    "--------- snapshot is ${snapshot.data}");
                                _currentAirport = value;
                                selectedAirport = _currentAirport.airportName;
                              });
                            },
                            value: _currentAirport,
                            hint: _currentAirport == null ? Text("Airport") : null, // show hint only when there is no selected vlaue
                          );
}),
</pre>

**Comment by stahlie** [comment]
Thanks again.  It didn't solve the problem .  What I did was commented out the 'value:' line just above the 'hint:' line and the error didn't happen.  However it won't show the Selected Airport in the "hint" part.    Hmm...I suspected that it has to do with Model variable in the value: line .  I'm used to String value when it come to dropdownmenu but this is Model value.   Not sure how to resolve that.  Make sense?

**Comment by janmoppel** [comment]
Hello @stahlie !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
