### ISSUE TITLE
does webview_flutter have  loadHTMLString ?

### ISSUE THREAD

**Issue by guduge** [flutter/flutter#32184]
i don't find  such api as  "loadHTMLString" 
eg : [_webView loadHTMLString:@"<p class="package-count"><span>43</span> results for</p>" baseURL:nil];

**Comment by calvinmuller** [comment]
hi @guduge you can use the dart Uri class for this. please see ‘https://api.dartlang.org/stable/2.3.0/dart-core/Uri/Uri.dataFromString.html’

**Comment by janmoppel** [comment]
Hello @guduge !

Did you manage to find the solution for your problem?

**Comment by hillelcoren** [comment]
This approach works:

    final str = 'Some HTML string...';
    final String contentBase64 = base64Encode(const Utf8Encoder().convert(str));
    final url = 'data:text/html;base64,$contentBase64';
    _webViewController.loadUrl(url);

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
