### ISSUE TITLE
This release is not compliant with the Google Play 64-bit requirement ?

### ISSUE THREAD

**Issue by ShubhamHande99** [flutter/flutter#32191]
![Screenshot (5)](https://user-images.githubusercontent.com/45396085/57288493-2e628980-70d7-11e9-8f1c-3ffdb8e51e60.png)

How to fix this ?

**Comment by lgArlequin** [comment]
Read this #31922

**Comment by Laxman007** [comment]
add following line app level build.gradle
ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'

run flutter build apk --release --target-platform=android-arm
upload 32bit version to play store
increment versionCode in pubspec.yaml
run flutter build apk --release --target-platform=android-arm64
upload 64bit version to play store

**Comment by realvorl** [comment]
> add following line app level build.gradle
> ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
> 
> run flutter build apk --release --target-platform=android-arm
> upload 32bit version to play store
> increment versionCode in pubspec.yaml
> run flutter build apk --release --target-platform=android-arm64
> upload 64bit version to play store

Eurika: This works:
![image](https://user-images.githubusercontent.com/6973263/59568086-20107180-9076-11e9-95f9-ac2078f95c67.png)

 but it is not `pubspec.yaml `where you need to update the version, it is `build.gradle`

![image](https://user-images.githubusercontent.com/6973263/59568030-6e714080-9075-11e9-9b90-76cae11841e0.png)

I allso built using the `appbundle` switch not `apk` :

`flutter build appbundle --release --target-platform=android-arm64`

**Comment by Laxman007** [comment]
Yes, its in build.gradle. I have mentioned build.gradle only. And it depends on your need you can generate either one apk or appbundle.

**Comment by kgoofori** [comment]
This solution worked for me https://github.com/flutter/flutter/issues/31922#issuecomment-507247328

**Comment by shah2002** [comment]
Hello I have this problem in unity 2017.4.20 or 2019.1.2 , How can I resolve it? you can see  this problem 
 in blow link : https://stackoverflow.com/questions/56687339/what-is-this-error-in-build-adroid-and-build-app-bundle-in-unity-2017-4-17            
please Help me Because I am in this problem for 2 month thanks

**Comment by georgehamiltone** [comment]
@Laxman007 how to run flutter build apk --release --target-platform=android-arm  ??

**Comment by georgehamiltone** [comment]
@realvorl how to run flutter build apk --release --target-platform=android-arm ?? it dosen't work for me

**Comment by Laxman-Kumar** [comment]
@georgehamiltone
For 32 bit app. 
Step 1: In build.gradle
         Write this  -> ndk.abiFilters 'armeabi-v7a'

Step 2: flutter build apk --release --target-platform=android-arm

For 64 bit app
Step 1: In build.gradle
         Write this  -> ndk.abiFilters 'arm64-v8a'

Step 2: flutter build apk --release --target-platform=android-arm64

If still not working then please share the error.

**Comment by Laxman-Kumar** [comment]
@shah2002
Try my above solution by adding it into deafult config -> abifilter -> ndkfilter 
And try releasing.

**Comment by georgehamiltone** [comment]
@Laxman-Kumar thanks for your help. When i run this command on Terminal "flutter build apk --release --target-platform=android-arm". i got this error message:
"No pubspec.yaml file found. This command should be run from the root of your Flutter project. Do not run this command from the root of your git clone of Flutter".

**Comment by Laxman-Kumar** [comment]
@georgehamiltone 
Hy buddy you should run this from the root the project on the same level as pubspec.yaml.

**Comment by mtt2011pony** [comment]
> add following line app level build.gradle
> ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
> 
> run flutter build apk --release --target-platform=android-arm
> upload 32bit version to play store
> increment versionCode in pubspec.yaml
> run flutter build apk --release --target-platform=android-arm64
> upload 64bit version to play store

But how do I specify a signature file？

**Comment by Laxman-Kumar** [comment]
> @laxman Kumar
> 
> > add following line app level build.gradle
> > ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
> > run flutter build apk --release --target-platform=android-arm
> > upload 32bit version to play store
> > increment versionCode in pubspec.yaml
> > run flutter build apk --release --target-platform=android-arm64
> > upload 64bit version to play store
> 
> But how do I specify a signature file？


I didn't get the question can you please elaborate.

**Comment by holoc285** [comment]
> add following line app level build.gradle
> ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
> 
> run flutter build apk --release --target-platform=android-arm
> upload 32bit version to play store
> increment versionCode in pubspec.yaml
> run flutter build apk --release --target-platform=android-arm64
> upload 64bit version to play store

What is the versionCode in pubspec.yaml ?

**Comment by georgehamiltone** [comment]
@Laxman-Kumar  thanks for the reply .please i didn't understand what you meant by "run this from the root the project on the same level as pubspec.yaml." because i didn't found such a file"pubspec.yaml" in my project.

**Comment by eleguni** [comment]
I have added this line ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64' in gradle but it still has this error while upload


Error

This release is not compliant with the Google Play 64-bit requirement

The following APKs or App Bundles are available to 64-bit devices, but they only have 32-bit native code: 6.

Include 64-bit and 32-bit native code in your app. Use the Android App Bundle publishing format to automatically ensure that each device architecture receives only the native code it needs. This avoids increasing the overall size of your app.

**Comment by Laxman-Kumar** [comment]
@holoc285 version code varies based on how many version you have put on the play store.
If you having problem with the version code then follow this. To change the version automatically, you have two options —-build-name and --build-number. These two options are options of the flutter build command:
flutter build apk --build-name=1.0.3
flutter build apk --build-number=3
flutter build apk --build-name=1.0.3 --build-number=3

**Comment by Laxman-Kumar** [comment]
@georgehamiltone 
![Annotation 2019-09-07 194730](https://user-images.githubusercontent.com/23344957/64481345-750ce100-d1a8-11e9-9093-34782d13d82d.jpg)

Hy, I am attaching the project structure and highlighted the file.

**Comment by Laxman-Kumar** [comment]
@eleguni 
Hy there, you have to generate two apks. One with 'armeabi-v7a' for 32-bit build and one with 'arm64-v8a' for 64-bit build. You have upload two apks in the play store while releasing a build. You can upload two at once and it will automatically detect the versions while downloading. 
Just build the two separate apks.

**Comment by Ikxyz** [comment]
This was my solution:

in app gradle
splits {
        // Configures multiple APKs based on ABI.
        abi {
            // Enables building multiple APKs per ABI.
            enable true
            // By default all ABIs are included, so use reset() and include to specify that we only
            // want APKs for armeabi-v7a and arm64-v8a.

            // Resets the list of ABIs that Gradle should create APKs for to none.
            reset()

            // Specifies a list of ABIs that Gradle should create APKs for.
            include "armeabi-v7a", "arm64-v8a"

            // Specifies that we do not want to also generate a universal APK that includes all ABIs.
            universalApk false
        }
    }
run flutter build apk --release --target-platform=android-arm

upload app-armeabi-v7a-release.apk to the play store

increment versionCode

run flutter build apk --release --target-platform=android-arm64

upload app-arm64-v8a-release.apk to the play store

Google play store will serve App according to device architecture. 32bit devices are happy, 64bit devices are happy and I'm happy knowing that my APK size remains relatively small while still serving both architectures.

If we include support for both architectures in the same APK, expect the size of your app to be 10MB+

**Comment by Maikhaa** [comment]
You can also generate the two required apks without changing your build.gradle with:

>flutter build apk --target-platform android-arm,android-arm64 --split-per-abi

**Comment by BondarenkoStas** [comment]
@ ShubhamHande99 did you manage to fix it?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by ahmedaniss25** [comment]
i solve porblem here : https://www.youtube.com/watch?v=1F2Xb-ckOxE you can follow my steps step by step to fix enable 64 bit through unity and android studio
