### ISSUE TITLE
Firestore offline mode not working with cloud_firestore: 0.11.0

### ISSUE THREAD

**Issue by frankps** [flutter/flutter#32193]
We want to use the Firestore offline-mode.

We tried different versions, all giving other behaviors.

The latest version of this library (0.11.0) is giving the error (while device is in Aeroplane mode) :
     ### **UNAVAILABLE: Unable to resolve host firestore.googleapis.com**

Apparently, the library is not aware that we're in offline mode.

I installed the dependency:
     cloud_firestore: ^0.11.0

In order to create new objects, I'm re-using a generic method that I developed 1 year ago:
```

  _Future<dynamic> createObject(T obj) async {
    final TransactionHandler createTransaction = (Transaction tx) async {
      final DocumentSnapshot ds = await tx.get(_objectCollection.document());

      obj.id = ds.documentID;

      final Map<String, dynamic> data = obj.toMap();

      await tx.set(ds.reference, data);

      return data;
    };

    return Firestore.instance.runTransaction(createTransaction).then((mapData) {
      var objNew = obj.createNew();   

      return objNew.fromMap(mapData);
    }).catchError((error) {
      print('error: $error');
      return null;
    });
  }_
```

**Comment by collinjackson** [comment]
Is this a regression in 0.11.0? Can you show how you're enabling offline mode? Which platform are you seeing this on?

Thanks.

**Comment by collinjackson** [comment]
Also I'm curious why you're using a transaction in this case; it doesn't seem necessary for just setting the values of a new document.

**Comment by kroikie** [comment]
@frankps

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/381. Any further collaboration will be done there.
