### ISSUE TITLE
Consider removing intrinsic sizes of images.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#3219]
I had an AssetImage as a child of a stack and ImageFit.cover.  In the end it didn't cover because it picked it's own intrinsic aspect ratio which wasn't what I expected.

A workaround is to place that Asset/NetworkImage as a child of a Positioned with 0.0 top, left, right, and bottoms but seems hacky.

@Hixie @abarth

**Comment by Hixie** [comment]
What size should an image be if you put it in a large "Center" widget?

**Comment by abarth** [comment]
One answer is that it would expand to fill its container, both in width and height.  You'd then have to use something like ImageFit.scaleDown to center the image.

**Comment by Hixie** [comment]
This would be an API breaking change which makes it unlikely that we'd want to do it...

**Comment by Hixie** [comment]
There are lots of ways to render images in Flutter, e.g. the `fit` property, FittedBox, as a background, etc. The default behaviour seems intuitive, though, so I'm closing this.
