### ISSUE TITLE
Could not find a file named "pubspec.yaml" in "C:\Users\iftek\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\quiver-2.0.1".

### ISSUE THREAD

**Issue by iftee939** [flutter/flutter#32197]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by BondarenkoStas** [comment]
@iftee939 did you manage to solve it? Can you provide more details about the project, why is it it asking for that path?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
