### ISSUE TITLE
[documentation] add gdpr consent for adds

### ISSUE THREAD

**Issue by affdev73** [flutter/flutter#32194]
Hello , 
Is any documentation and/or exemple of flutter app where is implemented : GDPR for EU consent 
com.google.android.ads.consent ? I could not find anything, my test add units work fine, but no actual adds from admob ( firebase_admob)
Thanks

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
