### ISSUE TITLE
ios compile error for cloud_firestore

### ISSUE THREAD

**Issue by nagik23** [flutter/flutter#32195]
Hi 

I am getting the following errors on compiling cloud_firestore on ios:

 === BUILD TARGET cloud_firestore OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.10.1/ios/Classes/CloudFirestorePlugin.m:275:29:
    error: no known class method for selector 'fieldValueForDoubleIncrement:'
          return [FIRFieldValue fieldValueForDoubleIncrement:value.doubleValue];
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.10.1/ios/Classes/CloudFirestorePlugin.m:279:29:
    error: no known class method for selector 'fieldValueForIntegerIncrement:'
          return [FIRFieldValue fieldValueForIntegerIncrement:value.intValue];
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 errors generated.

This issue was closed earlier but I am using the latest cloud firestore - 0.10.1 and I am still getting these compile errors. Please help.

**Comment by collinjackson** [comment]
It looks like you need to update your CocoaPods. Does running "pod update" in the iOS folder help?

**Comment by nagik23** [comment]
Hi

Yes it works after updating the pods. Thank you.

-- 

Thanks and with regards,
- Nagi

Nagaraj Kanniah

Creative Micro Systems
No. 300-B, 5th Main, 4th Phase
Peenya Industrial Area
Bengaluru - 560 058
Karnataka, India

Ph:  +91-80-2837-7812 / 14
Fax: +91-80-2837-7812

Cell: +91-98451-65949
Email: nagik@cmsgp.com

**Comment by kroikie** [comment]
@nagik23

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/380. Any further collaboration will be done there.
