### ISSUE TITLE
Slider change divisions and value error

### ISSUE THREAD

**Issue by lpongetti** [flutter/flutter#32199]
## Steps to Reproduce

1. Put a Slider  inside a statefull widget
2. set a value , max and divisions (eg myvalue = 8; Slider(value: 8, max:8, divisions: 8) )
3. change my value with setState(() { myvalue = 9; });
4. the thumb does not positioned in the right place.

## Logs

Analyzing amico...                                                      

   info • Equality operator `==` invocation with references of unrelated types • lib/components/timeline.dart:12:31 • unrelated_type_equality_checks
   info • Equality operator `==` invocation with references of unrelated types • lib/components/timeline.dart:12:55 • unrelated_type_equality_checks

[✓] Flutter (Channel unknown, v1.2.1-pre.130, on Linux, locale it_IT.UTF-8)
    • Flutter version 1.2.1-pre.130 at /usr/share/flutter
    • Framework revision eae1b08b4b (7 days ago), 2019-04-30 17:42:50 -0400
    • Engine revision 59b91392e2
    • Dart version 2.3.0 (build 2.3.0-dev.0.3 c46deebfb6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/lorenzo/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/lorenzo/Android/Sdk
    • Java binary at: /usr/share/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /usr/share/android-studio
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[!] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /usr/share/ideaIC
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.33.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.26.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.

**Comment by clocksmith** [comment]
Hi, this is working as intended.

There are asserts that specifiy the value must be between the min and the max:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/slider.dart#L132

So if you set the max to 8, you cannot pass 9. Besides not passing values outside of this range, one recommendation would be to use something like `value.clamp(0, 8)` on the value you are passing in.

Hope this helps!

**Comment by lpongetti** [comment]
@clocksmith  Sorry, i write very bad.

i have something like this:

myvalue = 8; 
return Slider(value: myvalue, max:myvalue, divisions: myvalue)

and when i do

setState(() { myvalue = 9; });

before it updates value and after divisions i think.

Actually I tried using you RangeSlider in my project
this is my code

`
import 'package:flutter/material.dart';

class TimelineRange {
  final String start;
  final String end;

  const TimelineRange({this.start, this.end});

  @override
  bool operator ==(Object other) =>
      other is RangeValues && other.start == start && other.end == end;

  @override
  int get hashCode => hashValues(start, end);

  @override
  String toString() {
    return '[$start, $end]';
  }
}

class Timeline extends StatefulWidget {
  final Function(TimelineRange) onChanged;

  Timeline({
    Key key,
    @required this.onChanged,
  })  : assert(onChanged != null),
        super(key: key);

  @override
  _TimelineState createState() => _TimelineState();
}

class _TimelineState extends State<Timeline> {
  List<List<String>> steps;
  int stepIndex;
  RangeValues value;

  @override
  void initState() {
    steps = [
      [
        "2 y",
        "1 y",
        "6 m",
        "90 d",
        "60 d",
        "30 d",
        "7 d",
        "24 h",
        "12 h",
        "6 h",
        "3 h",
        "now"
      ],
      ["90 d", "60 d", "30 d", "7 d", "24 h", "12 h", "6 h", "3 h", "now"],
      ["7 d", "72 h", "48 h", "24 h", "12 h", "6 h", "3 h", "now"],
    ];
    stepIndex = 2;
    value = RangeValues(steps[stepIndex].indexOf("24 h").toDouble(),
        steps[stepIndex].indexOf("now").toDouble());

    super.initState();
  }

  bool get zoomInDisabled => stepIndex == steps.length - 1;

  bool get zoomOutDisabled => stepIndex == 0;

  onTapZoomIn() {
    var step = steps[stepIndex];
    var start = step[value.start.toInt()];
    var end = step[value.end.toInt()];

    setState(() {
      stepIndex++;

      step = steps[stepIndex];
      value = RangeValues(
        step.contains(start) ? step.indexOf(start).toDouble() : 0,
        step.contains(end) ? step.indexOf(end).toDouble() : step.length - 1,
      );
    });

    // Future.delayed(const Duration(milliseconds: 100)).then((_) {
    //   setState(() {
    //     return true;
    //   });
    // });
  }

  onTapZoomOut() {
    var step = steps[stepIndex];
    var start = step[value.start.toInt()];
    var end = step[value.end.toInt()];

    setState(() {
      stepIndex--;
      // });

      // Future.delayed(const Duration(milliseconds: 100)).then((_) {
      step = steps[stepIndex];

      // setState(() {
      value = RangeValues(
        step.contains(start) ? step.indexOf(start).toDouble() : 0,
        step.contains(end) ? step.indexOf(end).toDouble() : step.length - 1,
      );
      // });
    });

    // setState(() {
    //   stepIndex--;

    //   step = steps[stepIndex];
    //   value = RangeValues(
    //     step.contains(start) ? step.indexOf(start).toDouble() : 0,
    //     step.contains(end) ? step.indexOf(end).toDouble() : step.length - 1,
    //   );

    //   forceBuild = true;
    // });
  }

  buildText() {
    List<Widget> pos = [];

    for (var step in steps[stepIndex]) {
      pos.add(SizedBox(
        width: 30,
        child: Text(step),
      ));
      if (step != "now") {
        pos.add(Expanded(
          flex: 1,
          child: Container(),
        ));
      }
    }
    return pos;
  }

  @override
  Widget build(BuildContext context) {
    print("build");
    var length = steps[stepIndex].length - 1;

    return Column(
      children: <Widget>[
        Row(
          mainAxisAlignment: MainAxisAlignment.end,
          children: <Widget>[
            TimelineIcon(
              disabled: zoomInDisabled,
              icon: Icons.remove,
              onTap: onTapZoomIn,
            ),
            SizedBox(width: 5),
            TimelineIcon(
              disabled: zoomOutDisabled,
              icon: Icons.add,
              onTap: onTapZoomOut,
            ),
          ],
        ),
        Stack(
          children: <Widget>[
            Padding(
              padding: EdgeInsets.only(left: 20, right: 10),
              child: Row(
                children: buildText(),
              ),
            ),
            RangeSlider(
              min: 0,
              max: length.toDouble(),
              divisions: length,
              values: value,
              thumbSelector:
                  (textDirection, values, tapValue, thumbSize, trackSize, dx) {
                var alpha = 1 / length;
                var startAlpha = alpha * value.start;
                var endAlpha = alpha * value.end;

                if (startAlpha > tapValue) return Thumb.start;
                if (endAlpha < tapValue) return Thumb.end;
                if (tapValue - startAlpha < endAlpha - tapValue)
                  return Thumb.start;
                return Thumb.end;
              },
              minThumbSeparation: 1,
              onChanged: (newValue) {
                if (newValue.end - newValue.start >= 1 && value != newValue) {
                  setState(() => value = newValue);
                  widget.onChanged(TimelineRange(
                      start: steps[stepIndex][value.start.toInt()],
                      end: steps[stepIndex][value.end.toInt()]));
                }
              },
              onChangeEnd: (newValue) {
                // widget.onChanged(TimelineRange(
                //     start: steps[stepIndex][value.start.toInt()],
                //     end: steps[stepIndex][value.end.toInt()]));
              },
            ),
          ],
        ),
      ],
    );
  }
}

class TimelineIcon extends StatelessWidget {
  final IconData icon;
  final Function() onTap;
  final bool disabled;

  TimelineIcon(
      {@required this.icon, @required this.onTap, this.disabled = false})
      : assert(icon != null),
        assert(onTap != null);

  get color => disabled ? Colors.grey[300] : Colors.grey[400];

  get onTapFunction => disabled ? () {} : onTap;

  @override
  Widget build(BuildContext context) {
    return CircleButton(
      radius: 15,
      color: color,
      child: Icon(icon),
      onTap: onTapFunction,
    );
  }
}

class CircleButton extends StatelessWidget {
  final double radius;
  final Color color;
  final Widget child;
  final GestureTapCallback onTap;

  const CircleButton(
      {Key key,
      @required this.radius,
      @required this.color,
      this.child,
      this.onTap})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return new InkResponse(
      onTap: onTap,
      child: new Container(
        width: radius * 2,
        height: radius * 2,
        decoration: new BoxDecoration(
          color: color,
          shape: BoxShape.circle,
        ),
        child: Center(
          child: child,
        ),
      ),
    );
  }
}
`
my theme

`
theme: ThemeData(
        primarySwatch: Colors.blue,
        sliderTheme: SliderThemeData(
          disabledActiveTickMarkColor: Colors.black26,
          disabledInactiveTickMarkColor: Colors.black26,
          activeTickMarkColor: Colors.blue,
          inactiveTickMarkColor: Colors.lightBlueAccent,
          rangeTickMarkShape: RoundRangeSliderTickMarkShape(tickMarkRadius: 5),
          thumbColor: Colors.redAccent,
        ),
      )
`
if you tap on button with + or -, values change


Another error is that onChangEnd doen't works
You can try uncomment the code in "onChangeEnd" and remove this
`widget.onChanged(TimelineRange(
                      start: steps[stepIndex][value.start.toInt()],
                      end: steps[stepIndex][value.end.toInt()]));`
from onChanged.

Thanks

**Comment by clocksmith** [comment]
Thanks for the early feedback on the Range Slider! Once it is checked in, if you can still reproduce the issue, then please file a separate issue.

As far as this max value issue, what is `myvalue` in the example above. if `value` is greater than `max`, then the warning is expected.

**Comment by lpongetti** [comment]
@clocksmith 

in attachment my widget that use rangeslider.
when i press button "+" or "-" the value doen't align well with divisions.
also onchangeend dosn't work

[timeline.dart.txt](https://github.com/flutter/flutter/files/3187951/timeline.dart.txt)

**Comment by steve28100** [comment]
Is there any updates for this issue?

@lpongetti have you solved this problem or have any workaround?
