### ISSUE TITLE
Log file from user Flutter.

### ISSUE THREAD

**Issue by RogerPhilippe** [flutter/flutter#32206]
How can i save log files that the user has access to in Flutter?
I looked for something like Apache log4j or Timber, without success.

**Comment by BondarenkoStas** [comment]
@RogerPhilippe Just wonder if that https://medium.com/flutter-community/logging-in-flutter-a583b3668228 will help. Or did you find any other solution?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
