### ISSUE TITLE
[google_maps_flutter] Google Maps projection

### ISSUE THREAD

**Issue by aarocorp** [flutter/flutter#32203]
Hi there,

First of all, I wanna thanks you for all the work you are doing with Flutter and the Google Maps Plugin particulary. Have been using it for around three weeks now and really love it.

Still I would like to know, is there anyway to make the Google Maps projection available through the plugin ?

I have done some digging and looks like Projection are already available in the android `.java` file and the ios `.m` file too.

Thanks for your feedbacks,

PS : I checked before posting and (except if I am wrong) didn't find a duplicate to this request

**Comment by RevanScript** [comment]
Any updates on this?

**Comment by aarocorp** [comment]
Nope but found a workaround to fix this.
Basically used this solution found on StackOverflow and Google Documentation :
https://developers.google.com/maps/documentation/javascript/examples/map-coordinates 

https://stackoverflow.com/questions/23457916/how-to-get-latitude-and-longitude-bounds-from-google-maps-x-y-and-zoom-parameter

Hope it will help

**Comment by SDRuiz** [comment]
Sorry for me question but, can Projections solve my problem?
![polyline_error](https://user-images.githubusercontent.com/48831559/61395629-46574600-a89c-11e9-9061-0ccce637d04c.jpg)

**Comment by aarocorp** [comment]
@SDRuiz: Nope. Projection will just help you to get the equivalent of your GPS coordinates into pixel coordinates (or vice versa).
In your case, looks like you are trying to display an route retrieve from Google Service Right ? 
If show, the encoded_polyline retrieved is the reason why you have it displayed this way.
For each sub route of the route, you have a more precise encoded_polyline you should use instead if you wanna have a better render of the route.
If you aren't user Google Service, you can subscrible to the snap to road service which works as explained (follow the link ...) It is a paid service.
Snap to Road description :  https://developers.google.com/maps/documentation/roads/snap
Snap to Road pricing : https://developers.google.com/maps/documentation/roads/usage-and-billing

Hope it helps

**Comment by SDRuiz** [comment]
@aarocorp you are my very best friend rigth now...I really appretiate your response. I hit the Google Directions API and get the Response, extract the legs of the route and generate the polyline. Maybe the google_maps_flutter polyline's is not finish or something like that, because in Android work better or resolve the route better. I will review the API response to see if I been missed some info. Thanks again!

**Comment by aarocorp** [comment]
my please. 

Example taken from : https://developers.google.com/maps/documentation/directions/intro#sample-response
``` JSON
routes": [ {
    "summary": "I-40 W",
    "legs": [ {
      "steps": [ {
        "travel_mode": "DRIVING",
        "start_location": {
          "lat": 41.8507300,
          "lng": -87.6512600
        },
        "end_location": {
          "lat": 41.8525800,
          "lng": -87.6514100
        },
        "polyline": {
          "points": "a~l~Fjk~uOwHJy@P"
        },
        "duration": {
          "value": 19,
          "text": "1 min"
        },
        "html_instructions": "Head \u003cb\u003enorth\u003c/b\u003e on \u003cb\u003eS
        Morgan St\u003c/b\u003e toward \u003cb\u003eW Cermak Rd\u003c/b\u003e",
        "distance": {
          "value": 207,
          "text": "0.1 mi"
        }
      },
      ...
      ... additional steps of this leg
    ...
    ... additional legs of this route
      "duration": {
        "value": 74384,
        "text": "20 hours 40 mins"
      },
      "distance": {
        "value": 2137146,
        "text": "1,328 mi"
      },
      "start_location": {
        "lat": 35.4675602,
        "lng": -97.5164276
      },
      "end_location": {
        "lat": 34.0522342,
        "lng": -118.2436849
      },
      "start_address": "Oklahoma City, OK, USA",
      "end_address": "Los Angeles, CA, USA"
    } ],
    "copyrights": "Map data ©2010 Google, Sanborn",
    "overview_polyline": {
      "points": "a~l~Fjk~uOnzh@vlbBtc~@tsE`vnApw{A`dw@~w\\|tNtqf@l{Yd_Fblh@rxo@b}@xxSfytA
      blk@xxaBeJxlcBb~t@zbh@jc|Bx}C`rv@rw|@rlhA~dVzeo@vrSnc}Axf]fjz@xfFbw~@dz{A~d{A|zOxbrBbdUvpo@`
      cFp~xBc`Hk@nurDznmFfwMbwz@bbl@lq~@loPpxq@bw_@v|{CbtY~jGqeMb{iF|n\\~mbDzeVh_Wr|Efc\\x`Ij{kE}mAb
      ~uF{cNd}xBjp]fulBiwJpgg@|kHntyArpb@bijCk_Kv~eGyqTj_|@`uV`k|DcsNdwxAott@r}q@_gc@nu`CnvHx`k@dse
      @j|p@zpiAp|gEicy@`omFvaErfo@igQxnlApqGze~AsyRzrjAb__@ftyB}pIlo_BflmA~yQftNboWzoAlzp@mz`@|}_
      @fda@jakEitAn{fB_a]lexClshBtmqAdmY_hLxiZd~XtaBndgC"
    },
    "warnings": [ ],
    "waypoint_order": [ 0, 1 ],
    "bounds": {
      "southwest": {
        "lat": 34.0523600,
        "lng": -118.2435600
      },
      "northeast": {
        "lat": 41.8781100,
        "lng": -87.6297900
      }
    }
  } ]
```

Don't use `overview_polyline`, 
use instead the points within each `step > polyline`
```
{
      "steps": [ {
        "travel_mode": "DRIVING",
        "start_location": {
          "lat": 41.8507300,
          "lng": -87.6512600
        },
        "end_location": {
          "lat": 41.8525800,
          "lng": -87.6514100
        },
        "polyline": {
          "points": "a~l~Fjk~uOwHJy@P"
        },
        "duration": {
          "value": 19,
          "text": "1 min"
        },
        "html_instructions": "Head \u003cb\u003enorth\u003c/b\u003e on \u003cb\u003eS
        Morgan St\u003c/b\u003e toward \u003cb\u003eW Cermak Rd\u003c/b\u003e",
        "distance": {
          "value": 207,
          "text": "0.1 mi"
        }
      },
```

**Comment by SDRuiz** [comment]
@aarocorp yea, i'd tried that, but is the same as the lat, long start and end.
I checked that you told me about snap to roud, it's really great in near points :)
I post a feedback to google told them my problem, and especting what API can help me to solve this issue.

Thanks again, I really appreciate your help!

**Comment by aarocorp** [comment]
@SDRuiz I am really surprised by the result on your size. So lets me sum it up again : 
- You are using Google Direction API which give you the route from a point A to a point B. Correct ? 
- For the route retrieved, you loop into the steps and get the `polyline > points` within each. Correct ? 
If so it is supposed to work. Have anything against the `Snap Road` API but depending on the calls you will be making it might end up costly (especially because you are already using the `direction API` which already have the information you need) 
Can you share the part of code you made ?

**Comment by aarocorp** [comment]
@SDRuiz even simplier. Below my code. Have a look and adapt it to yours : 
`Decoding of polyline`
```dart
gmdir.Route route =
          directions.routes.length > 0 ? directions.routes[0] : null;

      if (route == null) return null;

      var legs = directions.routes[0].legs;
      for (int i = 0; i < legs.length; i++) {
        var steps = legs[i].steps;
          points.addAll(
              _decodePolyline(legs[i].steps[j].polyline.points));
        }
      }
```
`_decodePolyline`
```dart
List<gmf.LatLng> _decodePolyline(String encoded) {
    List<gmf.LatLng> points = new List<gmf.LatLng>();
    int index = 0, len = encoded.length;
    int lat = 0, lng = 0;
    while (index < len) {
      int b, shift = 0, result = 0;
      do {
        b = encoded.codeUnitAt(index++) - 63;
        result |= (b & 0x1f) << shift;
        shift += 5;
      } while (b >= 0x20);
      int dlat = ((result & 1) != 0 ? ~(result >> 1) : (result >> 1));
      lat += dlat;
      shift = 0;
      result = 0;
      do {
        b = encoded.codeUnitAt(index++) - 63;
        result |= (b & 0x1f) << shift;
        shift += 5;
      } while (b >= 0x20);
      int dlng = ((result & 1) != 0 ? ~(result >> 1) : (result >> 1));
      lng += dlng;
      gmf.LatLng p = new gmf.LatLng(lat / 1E5, lng / 1E5);
      points.add(p);
    }
    return points;
  }
```
` Legend`
```dart
import 'package:google_maps_flutter/google_maps_flutter.dart' as gmf;
import 'package:google_maps_webservice/directions.dart' as gmdir;
```

**Comment by SDRuiz** [comment]
> * You are using Google Direction API which give you the route from a point A to a point B. Correct ?

Yes, I am doing that.

> * For the route retrieved, you loop into the steps and get the `polyline > points` within each. Correct ?

I'm working whit LatLng, to draw the polyline, so I get the start and end coordinates for every step and added to the set<LatLng> like this: 

```
import 'package:google_maps_flutter/google_maps_flutter.dart' as flutter;
import 'package:google_maps_webservice/directions.dart' as google;

_mapsApiProvider
	.getDirections(origin, destination, points)
	.then((google.DirectionsResponse response) {
		List<google.Leg> legs = response.routes[0].legs;
		List<flutter.LatLng> ccc = List();
		for (var leg in legs) {
			List<google.Step> steps = leg.steps;
			print(steps.toString());
			for (final i in steps) {
				distance += i.distance.value;
				duration += i.duration.value;
				ccc.add(flutter.LatLng(i.startLocation.lat, i.startLocation.lng));
				ccc.add(flutter.LatLng(i.endLocation.lat, i.endLocation.lng));
			}
		}
		getSnapToRoad(ccc).then((pointList) {
		setState(
			() {
				_markers.clear();
				for (var point in itinerary) {
					_markers.add(
						flutter.Marker(
							markerId: flutter.MarkerId("parada ${point.latitude}"),
							position: flutter.LatLng(point.latitude, point.longitude),
							infoWindow: flutter.InfoWindow(
							title: point.address, snippet: point.province),
						),
					);
				}
				_polyline.clear();
				_polyline.add(
					flutter.Polyline(
						polylineId: flutter.PolylineId("route"),
						points: pointList,
						width: 2,
						color: Colors.red,
						geodesic: true,
						jointType: flutter.JointType.round,
					),
				);
			});
		}
```
```
Future<List<flutter.LatLng>> getSnapToRoad(List<flutter.LatLng> ccc) async {
    List<flutter.LatLng> points = new List();
    String coordinates = "";
    for (flutter.LatLng latlng in ccc) {
      coordinates += "${latlng.latitude},${latlng.longitude}|";
    }
    var snapResponse = await _mapsApiProvider
        .getSnapToRoads(coordinates.substring(0, coordinates.length - 2));
    for (var snap in snapResponse.snappedPoints) {
      flutter.LatLng location =
          new flutter.LatLng(snap.location.latitude, snap.location.longitude);
      points.add(location);
    }
    return points;
  }
```
>   If so it is supposed to work. Have anything against the `Snap Road` API but depending on the calls you will be making it might end up costly (especially because you are already using the `direction API` which already have the information you need)
>   Can you share the part of code you made ?

Sorry for this mess, I'm not using any StateManagment or Pattern to probe this!

**Comment by aarocorp** [comment]
@SDRuiz : Hey. Sorry for the silence. Been busy lately. Take time to have a look and let you know if I find something 👍

**Comment by SDRuiz** [comment]
@aarocorp NP man, thanks a lot for your help.
Do you know or integrate Geofence for flutter?
can I add you to Slack, Skype, Hangout or some other chat? :)

**Comment by aarocorp** [comment]
@SDRuiz sure thing.
My Skype account : aaro188 
Will we talk about your geofence question there if you don't mind 👍

**Comment by joknjokn** [comment]
I think projection has been added a few days ago.

Not entirely the same issue, but does someone know if I can use some projection function to check if a given gps-coordinate is within the boundaries of a polygon (also gps-coordinates)?

**Comment by BondarenkoStas** [comment]
yes, projections are supposed to be in 0.5.21+4 (September 25). I think it's safe to close the issue.
If you disagree or the feature doesn't solve the problem, please comment, I will re-open it right away.

**Comment by Juan-JDGroup** [comment]
@SDRuiz you can solved the problem with the lines? i try but not found the solution.
