### ISSUE TITLE
Support canvas.drawAtlas

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#32217]
The docs for `Canvas.drawImageRect` say:

> Multiple calls to this method with different arguments (from the same image) can be batched into a single call to drawAtlas to improve performance.

I'm working on a [Tiled](https://www.mapeditor.org/) map renderer, and it results in *lots* of calls to `drawImageRect` for drawing from the same tileset. I haven't done any measuring yet, but assume that drawAtlas would provide performance gains.

Even if it's not supported for web, having the API work (for example by just calling `drawImageRect`) would at least allow the performance benefits when running the same code on other platforms.

**Comment by kchnr** [comment]
I'm also trying to draw a bunch of sprites into my app, but my drawAtlas function actually renders the entire spreadsheet at once as far I can tell given what happens.

This is what I expect (in windows desktop and android emulator draws like this):
![working_windows_desktop](https://user-images.githubusercontent.com/576918/82377808-9cd06c00-99fa-11ea-973d-e82b3041fd5a.PNG)

This is the chrome/web version, it doesn`t work:
> flutter run --release --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome
![chrome_cavaskit_release_mode](https://user-images.githubusercontent.com/576918/82377929-c25d7580-99fa-11ea-90dd-300557981d37.PNG)

**Comment by iapicca** [comment]
Hi @kchnr 
your specific case should be addressed as `skia` /  `canvas-kit` specific
could you please open a separate issue for that
provideingyour `flutter doctor -v`
and a minimal complete reproducible code sample.
Thank you

**Comment by yjbanov** [comment]
Other than this bug - https://github.com/flutter/flutter/issues/88220 - `drawAtlas` is supported. It only works in CanvasKit, but since it cannot be supported in HTML mode with the same performance expectations, this is the best we can do until browsers provide new API. So let's consider this implemented.
