### ISSUE TITLE
Add web support for canvas.drawPoints

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#32218]
Currently `canvas.drawPoints` throws `UnimplementedError`, but it's useful for drawing points/lines/polygons on a Canvas. For now my use is mostly for debugging - I'm creating a renderer for [Tiled](https://www.mapeditor.org/) maps and it allows poionts/polylines/polygons to defined as areas on the map (eg. for triggering things, or making NPC paths) and it's very useful to turn on rendering of them. (I'm sure there a non-debug uses, but that's all I have right now :-))

**Comment by ferhatb** [comment]
@DanTup , update: starting implementation.

**Comment by ferhatb** [comment]
In master, closing issue.
