### ISSUE TITLE
flutter_web_ui contains a clone of some vector_math code

### ISSUE THREAD

**Issue by rakudrama** [flutter/flutter#32216]
It is a bad idea to have two copies of Matrix4, Vector3 etc.

The app will be bigger and slower because of this. Why it is bigger is obvious. It is slower because V8 and other JavaScript engines only JIT code after it is used for a while. Having two copies in use means that 'used for a while' is longer for both copies.

The copy is going to be a maintenance nightmare

- The copied code makes no attempt to maintain the structure of where it came from. The copied code is all in one file instead of files that can be compared to the original. It is 'part' of 'engine' instead of being library with similar structure to the original.

- The copy is a copy of _generated code_ (vector_math_64) which is generated from the 32-bit version. (This is the correct direction due to intermediate value truncation concerns.)

- I have some ideas how to make vector_math faster, but they are tricky and it will be a pain to make them in two places.

I'm not sure what the right thing is but it might look a bit like this:

- Move the core types  (Matrix4, Vector3) to a `dart:` library
- Make package:vector_math re-export the code

or

- Implement a low-level `dart:` library for use by both vector_math libraries.

I think I like the second idea - a 4x4 matrix copy (B=A) or multiply (C=A*B) of Float64List(16) could be intrinsified on the VM to use SIMD instructions.

**Comment by dnfield** [comment]
Why is Flutter for web ending up with two copies of vector math?

**Comment by ferhatb** [comment]
@dnfield, engine is dart: library. It can't import a package.

**Comment by markusaksli-nc** [comment]
Hi @rakudrama 
Since flutter_web has been archived it's hard to find what you mean by "two_copies" in the current code. Could you maybe provide some examples?
Thank you

**Comment by pedromassangocode** [comment]
Is this still valid today?

**Comment by yjbanov** [comment]
I don't think it's relevant any more. We have significantly customized the vector_math code, removing all the parts we don't use (which is _most_ parts) and altered API in breaking ways. I don't think we can call it a copy any more. If our version works better than that original, they should feel free to copy it (it's open-source!), but there are no plans to share code.
