### ISSUE TITLE
Text widget will occasionally overflow its containing widget

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#32214]
**Describe the bug**
Occasionally a Text widget will overflow its containing widget and draw outside its bounds.

**To Reproduce**
Use this code and resize the screen slowly until you see the text overflow as in the screenshot below.  A LayoutBuilder was reporting a screen width of 516.
```
// Copyright 2018 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter_web/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Padding(
        padding: EdgeInsets.all(24.0),
        child: Center(
          child: Container(
            child: Material(
              color: Colors.lightBlueAccent,
              child: Text(
                'Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper that we should do this.',
                style: TextStyle().copyWith(fontSize: 32.0),
              ),
            ),
          ),
        ),
      ),
    ),
  );
}
```

**Expected behavior**
Text should not overflow the Container, and instead the Container should be equal or larger all the time.

**Screenshots**
<img width="517" alt="Screen Shot 2019-05-02 at 3 03 37 PM" src="https://user-images.githubusercontent.com/9346834/57100348-ba963a80-6cec-11e9-9b99-744268de8506.png">

**Desktop:**
OS: macOS 10.14.4 (18E226)
Browser: Chrome Version 73.0.3683.103 (Official Build) (64-bit)
Dart Version: 2.2.1 (build 2.2.1-dev.4.0 None)
Flutter Web commit SHA:ecbdadf118b497f41c4ed4599baa0cc1c1c0fc08

**Comment by ferhatb** [comment]
Working on latest master. No overflow.
