### ISSUE TITLE
Full support for multi-line text editing on web

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#32213]
- [x] Use `<textarea>` as a backing DOM element when editing a multi-line text field.
- [x] Draw cursor in the correct location.
- [x] Draw selection boxes in the correct location.
- [ ] On tap, place the cursor in the correct position.

Depends on https://github.com/flutter/flutter/issues/33523

**Comment by AppleEducate** [comment]
Definitely needed. The cursor is not in the right place on the web. works great on ios though

**Comment by rpk98c** [comment]
+1 for placing cursor in correct position

**Comment by michaelchiowong** [comment]
hi, modebbar,

When will this avaiable in the beta channel?

**Comment by mdebbar** [comment]
@michaelchiowong the beta release process is explained [here](https://github.com/flutter/flutter/wiki/Release-process#rolling-the-beta-channel).

You don't have to wait for beta though. There's a flag available that you can use today. To enable the flag, follow instructions in this issue: https://github.com/flutter/flutter/issues/33523.
