### ISSUE TITLE
Add new gallery studies

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#32224]
There's some nice examples here we should include in the Flutter Web gallery:
![image](https://user-images.githubusercontent.com/2319867/56611829-a1dca500-65c7-11e9-8774-03bd6e16431a.png)

For example, Pesto, Fortnightly, 2D Transformations. I also notice Shrine is updated compared to the current one. 

@kevmoo arguably we should hoist the ones that are completed to the demo catalog page and deep-link into them.

**Comment by ferhatb** [comment]
Using same code base now.
