### ISSUE TITLE
flutter_web should be resilient to missing web/ subfolder

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#32222]
We need a web/ folder containing an HTML and Dart stub to launch Flutter apps for the web. These files are not necessary on mobile, and it's not obvious to a casual user that they need to be added. If the web folder is missing, pub serve fails in ways that are not obvious to a novice user. We should provide a better error message in this scenario.

**Comment by jonahwilliams** [comment]
This bug, and several others, are essentially covered by a single upstream web tooling into flutter

**Comment by yjbanov** [comment]
@jonahwilliams Do you have a link to the 'upstream web tooling into flutter' issue?

**Comment by yjbanov** [comment]
@jonahwilliams This works, no?

**Comment by yjbanov** [comment]
Yeah, this works ([example](https://github.com/flutter/flutter/tree/master/examples/flutter_gallery/web)). Closing.
