### ISSUE TITLE
Gallery uses Android styling in iOS Chrome

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#32220]
I guess the code to detect iOS styling and display with cupertino is either broken or disabled? (Maybe cupertino isn't implemented?)

73.0.3683.68, stable.
ios 12.2

Note the back arrow (and lack of back swipe gesture) by default:

![image](https://user-images.githubusercontent.com/11857803/56710253-fd975300-66d9-11e9-9db9-08e3067ec4b3.png)

**Comment by jonahwilliams** [comment]
We can implement this with a config import in the framework to define this in terms of dart:html APIs

**Comment by mariamhas** [comment]
This is for the old gallery, need to check if this issue exists for new gallery before closing

**Comment by ferhatb** [comment]
New gallery now detects both ios and macos.
