### ISSUE TITLE
[firefox] Selection changes in aren't reflected in text fields

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#32225]
While editing a text field in the gallery app, use the keyboard arrow keys to move the cursor. Notice that the cursor doesn't move in the text field.

**Comment by nturgut** [comment]
The PR is in.

**Comment by AresVampire** [comment]
This is not working. `TextField` is working at the beginning, but once it loses focus, like tapping on button, then textfield doesn't work anymore.

**Comment by nturgut** [comment]
@AresVampire I tested now with flutter, it worked for me on Firefox and Chrome:

[✓] Flutter (Channel unknown, 1.21.0-10.0.pre.176, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.21.0-10.0.pre.176 at /Users/nurhan/development/flutter
    • Framework revision 4954a46ff0 (5 days ago), 2020-08-19 14:44:56 -0700
    • Engine revision 8177937133
    • Dart version 2.10.0 (build 2.10.0-45.0.dev)

Can you please open another issue, share flutter doctor output and sample code? Also please note down the browsers (or platforms) you observe the issue.
