### ISSUE TITLE
Implement RTL support for text editing

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#32239]
Our current implementation ignores the RTL vs LTR distinction.

**Comment by alibt** [comment]
any updates? problem still persists.

**Comment by AliAyasrah** [comment]
any update please ?

**Comment by nilva-co** [comment]
when will this be fixed?

**Comment by Plegizplegiz** [comment]
su 6.12.2020 klo 2.20 Nilva.co <notifications@github.com> kirjoitti:

**Comment by terryakt** [comment]
Hello, 
Has this issue been resolved? Does anyone have a workaround. 

Have 3 screens, only the one encounters this problem. The others are doing quite fine.

**Comment by mo-ah-dawood** [comment]
this not fixed in flutter 2

**Comment by ahmadod** [comment]
Hello
Now that flutter web is stable I think you should consider prioritizing this issue.

**Comment by terryakt** [comment]
> Hello
> Now that flutter web is stable I think you should consider prioritizing this issue.

Will do, thanks man

**Comment by ronytesler** [comment]
What is this issue about?
