### ISSUE TITLE
What's the right value for kMaxUnsignedSMI in bitfield.dart for flutter web?

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#32234]
In JS we can't go as high as the Dart VM can.

**Comment by mdebbar** [comment]
I think @jonahwilliams already fixed this in https://github.com/flutter/flutter/pull/33828?

**Comment by jonahwilliams** [comment]
I think there is an open question whether you want it to be the largest 32bit int supported in JavaScript or `-1`.

**Comment by mdebbar** [comment]
Ok, I'll update the issue's title since this isn't about upstreaming anymore. It's about what value should be used for web.

**Comment by yjbanov** [comment]
-1, which we use today, seems to work. Can we update the value to -1 and close this?
