### ISSUE TITLE
UX changes for text selection

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#32236]
When the user initiates the interaction with a text field via mouse, we should hide the handles and the tooltip (which are designed for touch screens only).

Related to: https://github.com/flutter/flutter_web/issues/19

PR: https://github.com/flutter/flutter/pull/29683

**Comment by gspencergoog** [comment]
This is true for all platforms that support mouse. We should also hide the cut/copy/paste context menu.

**Comment by gspencergoog** [comment]
This appears to be fixed.
