### ISSUE TITLE
Create a benchmarking design and plan

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#32237]
We need to come up with a plan for benchmarking Flutter Web. This issue requests that we do that.

**Comment by amreniouinnovent** [comment]
@ferhatb I was following this issue so I could know the benchmark and performance of Flutter web
I just wonder if there is a benchmark or it will not be planned?

**Comment by ferhatb** [comment]
Yes benchmarks are now up and running on flutter dashboard and we've started adding more benchmarks as we work on scrolling performance and other areas.
