### ISSUE TITLE
Text is not selectable by default on the web

### ISSUE THREAD

**Issue by martinrybak** [flutter/flutter#32246]
**Describe the bug**
Text cannot be selected for copying. This affects all text elements other than text fields.

**To Reproduce**
1. Run the /examples/gallery app
2. Navigate to http://localhost:8080/#/material/text
3. Attempt to highlight and select text.

**Expected behavior**
Text should be selectable and can be copied to the clipboard.

**Screenshots**
![Screen Shot 2019-03-13 at 4 56 32 PM](https://user-images.githubusercontent.com/2292792/54314242-86867f00-45b1-11e9-9d25-57485a18b124.png)

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome 72.0.3626.121, safari 12.0.3
 - Dart Version 2.2.1
 - Flutter Web commit SHA f2006dd26c71fe7e9e7e144abbd3add40b4915f9

**Comment by dnfield** [comment]
See also #5422 - would the framework fix in progress for this be a fix for web?  Or is the expectation in web that all text be selectable?

**Comment by MaxBittker** [comment]
the expectation in web is strongly that all text is selectable, unless the property `user-select: none; ` has been set

**Comment by lubritto** [comment]
Any update here? We have 7 months since the last post, just an update can help us.

**Comment by dnfield** [comment]
@yjbanov @mdebbar - is this something that should behave differently for web?  This has a fix on the framework side but there `Text` is not selectable by default.

/cc @ferhatb

**Comment by mdebbar** [comment]
@dnfield @lubritto In Flutter, text isn't selectable by default. Try using [`SelectableText`](https://api.flutter.dev/flutter/material/SelectableText-class.html) to enable selection of text. Please let us know if you face any issues.

**Comment by ferhatb** [comment]
Hi Dan, are you suggesting adding an api (maybe theme level) that will allow changing the default ?I'm fine with the consistency (default off everywhere). I think web's default makes sense on content heavy sites/docs rather than apps.

**Comment by prujohn** [comment]
> @dnfield @lubritto In Flutter, text isn't selectable by default. Try using [`SelectableText`](https://api.flutter.dev/flutter/material/SelectableText-class.html) to enable selection of text. Please let us know if you face any issues.

With respect @mdebbar, this answer isn't satisfactory.  SelectableText doesn't behave as expected in a Web context.  Users expect to be able to use ctrl+c or right click on the selected text with their mouse and see "copy" in the context menu.  None of this appears to be the case with SelectableText, at least on the beta channel.

**Comment by azol** [comment]
No way to copy text using SelectableText on dev channel. As for me the issue should be reopened. Web without ability to select/copy is... not what I expect from the web :)

**Comment by dnfield** [comment]
@azol that sounds like a seperate issue - please file one for that (`SelectableText` can't be copied on web).

**Comment by mdebbar** [comment]
@azol @prujohn the issue you are describing is valid, and I can confirm that it isn't fixed on web. Like @dnfield said, it's a separate issue from the closed one.

I created a separate issue for the inability to copy selected text: https://github.com/flutter/flutter/issues/47234

**Comment by searchy2** [comment]
Inadvertent content and web scraping protection is the best :D
Only copyright infringers and criminals need to copy text! /s

**Comment by MaxBittker** [comment]
I understand and respect why keeping behavior consistent with other parts of flutter is desirable, but I also think there might be a better compromise to be struck here - 

If you go to twitter.com, nytimes.com, github.com, etc, 95+% of text is selectable. 

Breaking this assumption will cause some negative emotional reactions towards flutter web apps from users and developers, and that it's worth reconsidering the intended behavior here. Text behavior is a common smell test for "is this a native web experience"? 

Even if this behavior stands for the time being, do you think another solution, such as using the Theme to store whether text is selectable by default, could be considered in the future?

**Comment by polina-c** [comment]
> @dnfield @lubritto In Flutter, text isn't selectable by default. Try using [`SelectableText`](https://api.flutter.dev/flutter/material/SelectableText-class.html) to enable selection of text. Please let us know if you face any issues.

SelectableText does not help, because it makes the text selectable only within one widget. 
Web users expect the text to be selectable across many elements, for example, i selected and copied this text from the previous post:

------------
 Nash0x7E2 mentioned this issue on Jan 18
Copy support on web #49117
 Closed
7 of 11 tasks complete 
--------

**Comment by TheChileanKink** [comment]
Any updates on this?
