### ISSUE TITLE
Text input selection should use platform standards

### ISSUE THREAD

**Issue by martinrybak** [flutter/flutter#32247]
**Describe the bug**
Text input selection shows cut/copy/paste menu with handles. This is not consistent with the desktop experience. Also right-clicking does not display standard platform options.

**To Reproduce**
1. Run the /examples/gallery app
1. Navigate to http://localhost:8080/#/material/text-form-field
1. Enter text into a form field.
1. Select text. Handles and cut/copy/paste menu will appear.
1. Right-click on text. Standard platform options do not appear.

**Expected behavior**
A cut/copy/paste should not appear.
Right-clicking on text should display standard platform options.

**Screenshots**
# Actual
![flutter](https://user-images.githubusercontent.com/2292792/54316408-09f69f00-45b7-11e9-8080-5c21e34755f0.png)

# Expected
![google](https://user-images.githubusercontent.com/2292792/54316415-0b27cc00-45b7-11e9-9bfc-5ec20a2395d5.png)

**Desktop (please complete the following information):**
- OS: Mac
- Browser chrome 72.0.3626.121
- Dart Version 2.2.1
- Flutter Web commit SHA f2006dd

**Comment by mdebbar** [comment]
This has been fixed (cc @nturgut).
