### ISSUE TITLE
VSCode Improve logs

### ISSUE THREAD

**Issue by atilkan** [flutter/flutter#32258]
Error logs on Vscode are not as reliable as Android Studio. 
While i am getting some path location error on Android studio, Vscode doesn't say anything and doesn't launch app on simulator. Just stares me with blank eyes.

Mac OS

**Comment by DanTup** [comment]
Can you give a concrete example or screenshot of what you're seeing in each editor?

**Comment by atilkan** [comment]
Here is a video that shows "Nothing happens part". I can record more if you want.
https://youtu.be/NPKEk6IxoYo

**Comment by atilkan** [comment]
I just saw my mistake. I had to start the app from debug panel. But the way i do it in video should be supported.

**Comment by DanTup** [comment]
@atilkan thanks for the video! It's now clear what's going on. You're running the `launch emulator` command. This is intended only to launch the emulator (which in the case it's already running, won't do anything).

To start your app, you want to use `F5`, `Debug: Start Debugging`, `Debug: Start without Debugging` or the green Run button on the debug side bar.

If you don't already have a device connected, trying to launch will run the `Launch Emulator` command for you, so you can select an emulator (or connect a device) and then it will continue.

Hope this makes sense!

**Comment by atilkan** [comment]
@DanTup I figured that part as i noted. If Launch Emulator would open with HMR or if the command to do this listed on commands pallet, that would be just **convenient**. 
It is frustrating to open one thing from somewhere another thing from whole another panel.

**Comment by DanTup** [comment]
@atilkan The command you're running is specifically to launch the emulator. It doesn't make sense for it to launch the app. As mentioned above, there are other commands that do exactly what you want - they start a debug session, and if there is no active device they will automatically run Launch Emulator for you. You don't need to go to a whole other panel, only use the debugging commands:

<img width="337" alt="Screenshot 2019-05-09 at 10 04 30 am" src="https://user-images.githubusercontent.com/1078012/57441446-e449e700-7241-11e9-8850-ef468d931b7d.png">

If this does not work for you (or doesn't do as you expect), please open an issue in the [Dart-Code repo](https://github.com/Dart-Code/Dart-Code) and I can take a look. Thanks!

**Comment by atilkan** [comment]
Thanks. That is working. The problem is stupid of me trying to search the command by typing **flutter** first.

**Comment by DanTup** [comment]
Ah yes, that is unfortunate. There's a lot of functionality that's common to all languages and therefore the commands in VS Code are not specific.

Launching apps is covered a little on the website at https://flutter.dev/docs/development/tools/vs-code#running-and-debugging along with some extra tips like refactors and assists - it's worth scanning through if you haven't seen it before :-)
