### ISSUE TITLE
Expose pubspec.yaml plugin version to plugins for analytics

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#32267]
The latest Firebase release included a `registerLibrary` API on `FIRApp` that can be used to register plugins for version analytics.

Exposing the plugin version to plugins will enable Flutterfire plugins to register as versioned third-party libraries with an automatically updated version number.

```
/**
 * Registers a given third-party library with the given version number to be reported for
 * analytics.
 *
 * @param name Name of the library.
 * @param version Version of the library.
 */
+ (void)registerLibrary:(nonnull NSString *)name withVersion:(nonnull NSString *)version;
```

See https://github.com/firebase/firebase-ios-sdk/blob/55814996a1a0d1bc5efdb666ec88278fea57229e/Firebase/Core/Private/FIRAppInternal.h#L142

### Work required

  * [ ] Update Flutter [engine](https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm#L559) to make `FlutterEngineRegistrar` have a public `pluginVersion` String getter and accept plugin version as an argument to `registrarForPlugin`. Plugins will be able to read their version off of the registrar as they register themselves.
  * [ ] Update [flutter_tools](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/plugins.dart) to pass the version string from the pubspec.yaml to `registrarForPlugin` in the `GeneratedPluginRegistrant`.
  * [ ] Decide on a canonical platform name convention, probably something like 'fire-flutter-core' for firebase_core, to match what the other Firebase platforms are doing.
  * [ ] Once the engine and framework changes are widely available, update all Flutterfire plugins to call `registerLibrary` with the provided version.

### Alternative approach

We could hard code the version numbers of plugins into the source code and just update it whenever the plugin version changes. We could write a test script running on Cirrus that ensures this hard coded version stays up to date with what's in pubspec.yaml.

@kroikie

**Comment by amirh** [comment]
As the alternative approach sounds simpler I'd suggest starting with it as a first incremental step which can be later reverted(vs. adding a public engine API which we won't be able to revert without a breaking change).

I wonder if this is something that might be useful for any Dart package in which case maybe solution belongs somewhere in pub / dart build? (another reason I'd be hesitant to add public Flutter engine API for this right away)

**Comment by collinjackson** [comment]
It does seem like something that could be useful on the Dart side as well. I'm fine with going with hard coding values in source for the time being as we're exploring the possibility space.

**Comment by collinjackson** [comment]
It occurred to me that we should probably make the Flutter version available at runtime as well.

**Comment by jonasfj** [comment]
Have you seen [build_version](https://pub.dev/packages/build_version), other packages which need to know their own version number uses this. Often coupled with `build_verify` to test that `build_runner` was invoked.

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/378. Any further collaboration will be done there.
