### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by BombeyR** [flutter/flutter#32264]
Hello. I am new to flutter. I will like to add a new screen(Route) to my app and I don't want the code of the screens to reside within the same dart file. I will like to know what I could do

**Comment by MichaelMarner** [comment]
This kind of question is probably better suited to StackOverflow, rather than Flutter's issue tracker.

You can break widgets out into separate files and import them as needed. For example:

```dart
// page_a.dart
import 'package:flutter/material.dart';

class PageA extends StatelessWidget {
   ...
}
```

```dart
import './page_a.dart';
import 'package:flutter/material.dart;

class MyApp extends StatelessWidget {
  build(context) {
    return MaterialApp (
      home: PageA()
    }
  }
}
```

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
