### ISSUE TITLE
Monitor api.flutter.dev for version mismatches against the stable channel.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#32268]
When we pushed Flutter 1.5.4,, the CI script pushed contents to a Firebase container not wired to serve to api.flutter.dev, so although the docs were correctly generated, they were not being served by the web site.

Although it's unlikely this is a regular occurrence, other problems (such as a problem in documentation generation or an actual push failure) could cause a green push with no corresponding update to the web site, as this did. 

We should have some monitoring for the cocoon dashboard so that in the event that the current stable channel version does not match the version served by api.flutter.dev we know about it.

**Comment by christopherfujino** [comment]
Fixed in https://github.com/flutter/flutter/pull/86723 and https://github.com/flutter/flutter/pull/86501
