### ISSUE TITLE
docs.flutter.io/objcdoc 'Install in Dash' doesn't work

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32270]
![Screen Shot 2019-05-07 at 5 22 05 PM](https://user-images.githubusercontent.com/156888/57340872-aa1b0100-70ec-11e9-9f5b-6a23352702ee.png)

Dash version 4.6.2

**Comment by kf6gpe** [comment]
I'm not convinced this is something we actually want/need to support. I'm closing this at present, subject to feedback from others.
