### ISSUE TITLE
d:\src\sdk1\sdk\runtime\vm\kernel_binary.cc: 605: error: unreachable code

### ISSUE THREAD

**Issue by QoLTech** [flutter/flutter#32275]
## Steps to Reproduce

I followed the steps exactly to setup flutter for web using the hello_world example from this [page,](https://github.com/flutter/flutter_web) but I'm running into this issue when I call "webdev serve", or anything with webdev. I just get "d:\src\sdk1\sdk\runtime\vm\kernel_binary.cc: 605: error: unreachable code". My C drive is where my flutter stuff is and my D drive is my Recovery drive. I've never pointed anything at D.

The project builds and runs just fine if I just hit F5 in VS Code, but not when I run it via command line.

## Logs

[√] Flutter (Channel master, v1.5.9-pre.174, on Microsoft Windows [Version 10.0.17134.706], locale en-US)
    • Flutter version 1.5.9-pre.174 at C:\flutter
    • Framework revision fbe11671a4 (4 hours ago), 2019-05-07 18:13:39 -0400
    • Engine revision 149b7b8981
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a8b6e18b62)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Program Files (x86)\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.33.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.0.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by kvisscher** [comment]
This was fixed for me after upgrading my Dart SDK version to the latest version at this time: `2.3.0.0-dev-5` and refetching the webdev package as stated in the docs.

**Comment by QoLTech** [comment]
> This was fixed for me after upgrading my Dart SDK version to the latest version at this time: `2.3.0.0-dev-5` and refetching the webdev package as stated in the docs.

How can I upgrade my Dart SDK version? Isn't it tied to the Flutter SDK?

**Comment by SoneWinstone** [comment]
> This was fixed for me after upgrading my Dart SDK version to the latest version at this time: `2.3.0.0-dev-5` and refetching the webdev package as stated in the docs.

my dart version is `2.3.0.0-dev-5`, but still this problem

**Comment by kvisscher** [comment]
@QoLTech No it isn't. Flutter is build upon the Dart SDK. @SoneWinstone have you also re-installed the webdev package via the following command?

```bash
flutter packages pub global activate webdev
```

**Comment by QoLTech** [comment]
> @QoLTech No it isn't. Flutter is build upon the Dart SDK. @SoneWinstone have you also re-installed the webdev package via the following command?
> 
> ```shell
> flutter packages pub global activate webdev
> ```

https://github.com/flutter/flutter/issues/21001#issue-353895274

**Comment by SoneWinstone** [comment]
> @QoLTech No it isn't. Flutter is build upon the Dart SDK. @SoneWinstone have you also re-installed the webdev package via the following command?
> 
> ```shell
> flutter packages pub global activate webdev
> ```

yes, i re-installed th webdev package, but not useful

**Comment by yjbanov** [comment]
@kmillikin @a-siva Does this look like a CFE issue?

**Comment by kmillikin** [comment]
It's hard to tell.  The file `sdk\runtime\vm\kernel_binary.cc` only has about 160 lines so line 605 is misleading (perhaps a line in the file after preprocessing, and UNREACHABLE doesn't report line numbers correctly on Windows?).

@QoLTech it would help somewhat to know what was in `d:\src\sdk1\sdk\runtime\vm\kernel_binary.cc` from about line 595 to 615 or so.

**Comment by Dana-Ferguson** [comment]
To add a data point. I got the same error as is in the title of the issue with a similar setup.

I upgraded Dart (not Flutter's local Dart, just Dart) and then the error changed to run `pub get`. I ran `pub get` after `flutter pub upgrade`. Then `webdev serve` worked.

**Comment by csells** [comment]
@QoLTech do you have this same issue when using the web support built into Flutter 1.9+?

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
Thank you
