### ISSUE TITLE
Enable writing reference tests

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#3227]
It's difficult to verify that complex trees widgets have been rendered correctly.  For example we need to verify that complex app bars - like the gallery's home page - render correctly as the app is scrolled. One way to approach this is with a "reference test".  Per a recent discussion:

[from @abarth] In other projects, I've had some success with "reference tests," which work by having the test author provide two ways of drawing the same content.  Generally, one that is simple and reliable and another that uses the code being tested.  The test framework then checks that you get exactly the same pixels out of both code paths.  That approach tends to be a bit easier to maintain as the underlying implementation of how the pixels are drawn evolves.

[from @Hixie] Reference tests would be ok if we're good about building them, but there's definitely an art to making sure you're not testing the same thing twice (and thus not testing it at all). We do definitely need to test paint behaviour, we have nothing testing that today.

**Comment by eseidelGoogle** [comment]
We have on our quarterly goals to provide a solution for verifying visual correctness with flutter testing.  Is this the correct bug for that?

**Comment by Hixie** [comment]
yes

**Comment by eseidelGoogle** [comment]
We've had trouble with visual regressions not being caught until we release into Google recently. I think we should consider wiring up something like this in May to start enforcing visual stability in a similar way to how we are starting to have api stability.

**Comment by zoechi** [comment]
Is this about what golden tests provide now?

**Comment by Hixie** [comment]
Reference tests are a different kind of test than golden tests, but golden tests are filling a similar need and I don't think we're planning on doing reference tests any time soon so I'll close this.
