### ISSUE TITLE
WebView crashes when placed in Column

### ISSUE THREAD

**Issue by nsmith1024** [flutter/flutter#32271]
## Steps to Reproduce

I just want to have a button below the WebView

Put webview_flutter into a column and it crashes (same crash if i put it in a ListView), here is the code::

      Widget webView= WebView(javascriptMode: JavascriptMode.unrestricted,
                                          onWebViewCreated: (WebViewController wvc) {
                                                webViewController=wvc;
                                                _controller.complete(wvc);
                                                loadHTML(wvc,context,disp);
                                          },
                      );

      Widget button =  RaisedButton( child: Text("assign"), onPressed: () => showUsers(context));

      Widget body = new Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              mainAxisSize: MainAxisSize.min,
              children: <Widget>[
                webView,   // <<<<<<<<<<<<<<<--------- THIS 
                button,
              ],
            );

      return Scaffold(
        appBar: AppBar(title: Text(name)),
           body: new Padding(
                padding: new EdgeInsets.symmetric(vertical: 0.0, horizontal: 0.0),
               child: body, //<<<<<<<<<<<<<<<<<<<------------- THIS
              ),
        );

Place WebView_flutter into a Column

## Logs

I/flutter (28942): Another exception was thrown: RenderAndroidView object was given an infinite size during layout.
I/flutter (28942): Another exception was thrown: RenderAndroidView object was given an infinite size during layout.
I/flutter (28942): Another exception was thrown: RenderPointerListener object was given an infinite size during layout.
I/flutter (28942): Another exception was thrown: A RenderFlex overflowed by Infinity pixels on the bottom.

```
```

   info - Name non-constant identifiers using lowerCamelCase - lib\common_widgets\placeholder_widget.dart:11:10 - non_constant_identifier_names
   info - Unused import: './users.dart' - lib\globals.dart:3:8 - unused_import
   info - Unused import: './room.dart' - lib\globals.dart:4:8 - unused_import
   info - Unused import: './hotel.dart' - lib\globals.dart:5:8 - unused_import
   info - Unused import: './user.dart' - lib\globals.dart:7:8 - unused_import
   info - Unused import: 'package:flutter_firebase_auth_example/ui/widgets/loading.dart' - lib\home_page.dart:17:8 - unused_import
   info - The value of the field '_loadingVisible' isn't used - lib\home_page.dart:47:8 - unused_field
   info - Avoid using braces in interpolation when not needed - lib\home_page.dart:179:40 - unnecessary_brace_in_string_interps
   info - The value of the local variable 'userId' isn't used - lib\home_page.dart:204:11 - unused_local_variable
   info - 'GmailSmtpOptions' is deprecated and shouldn't be used - lib\home_page.dart:208:23 - deprecated_member_use
   info - 'SmtpTransport' is deprecated and shouldn't be used - lib\home_page.dart:212:25 - deprecated_member_use
   info - 'Envelope' is deprecated and shouldn't be used - lib\home_page.dart:214:26 - deprecated_member_use
   info - 'Envelope' is deprecated and shouldn't be used - lib\home_page.dart:229:26 - deprecated_member_use
   info - The value of the local variable 'logo' isn't used - lib\home_page.dart:275:13 - unused_local_variable
   info - The value of the local variable 'service' isn't used - lib\home_page.dart:525:22 - unused_local_variable
   info - The method '_readCharacteristic' isn't used - lib\home_page.dart:583:3 - unused_element
   info - The method '_writeCharacteristic' isn't used - lib\home_page.dart:588:3 - unused_element
   info - The method '_readDescriptor' isn't used - lib\home_page.dart:594:3 - unused_element
   info - The method '_writeDescriptor' isn't used - lib\home_page.dart:599:3 - unused_element
   info - The method '_refreshDeviceState' isn't used - lib\home_page.dart:634:3 - unused_element

   info - Unused import: 'package:cloud_firestore/cloud_firestore.dart' - lib\hotel_info.dart:1:8 - unused_import
   info - Name non-constant identifiers using lowerCamelCase - lib\room.dart:23:8 - non_constant_identifier_names
   info - Unused import: 'package:flutter_local_notifications/flutter_local_notifications.dart' - lib\settings_page.dart:6:8 - unused_import
   info - Unused import: 'package:flutter_firebase_auth_example/ui/screens/sign_in.dart' - lib\settings_page.dart:8:8 - unused_import
   info - Unused import: 'tab_monitoring.dart' - lib\settings_page.dart:9:8 - unused_import
   info - Unused import: 'tab_ranging.dart' - lib\settings_page.dart:10:8 - unused_import
   info - Use `;` instead of `{}` for empty constructor bodies - lib\settings_page.dart:14:18 - empty_constructor_bodies
   info - Name non-constant identifiers using lowerCamelCase - lib\settings_page.dart:21:10 - non_constant_identifier_names
   info - The value of the field '_sos_email' isn't used - lib\settings_page.dart:21:10 - unused_field
   info - Name non-constant identifiers using lowerCamelCase - lib\settings_page.dart:22:10 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\settings_page.dart:23:30 - non_constant_identifier_names
   info - Unused import: 'package:cloud_firestore/cloud_firestore.dart' - lib\show_task.dart:1:8 - unused_import
   info - The value of the local variable 'webView' isn't used - lib\show_task.dart:69:14 - unused_local_variable
   info - Unused import: 'user.dart' - lib\task.dart:5:8 - unused_import
   info - Use `;` instead of `{}` for empty constructor bodies - lib\task.dart:26:18 - empty_constructor_bodies
   info - Name non-constant identifiers using lowerCamelCase - lib\user.dart:20:8 - non_constant_identifier_names
   info - Unused import: 'user.dart' - lib\user_store.dart:3:8 - unused_import
   info - Name non-constant identifiers using lowerCamelCase - lib\user_store.dart:14:8 - non_constant_identifier_names

```
```

[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.2.1 at D:\HotelDev\flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: D:\Android\android-studio-3.0-preview\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[!] Android Studio (version 2.1)
    • Android Studio at D:\Android\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 3.0)
    • Android Studio at D:\Android\android-studio-3.0-preview\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Connected device (1 available)
    • LGL84VL • LGL84VLc12e6a75 • android-arm • Android 7.0 (API 24)

! Doctor found issues in 2 categories.
```
```

**Comment by dnfield** [comment]
Try wrapping your `webView` in an `Expanded`.

**Comment by maltub9** [comment]
> Try wrapping your `webView` in an `Expanded`.

I tried this but dosn't work

**Comment by VladyslavBondarenko** [comment]
The complete log

```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: RenderConstrainedBox object was given an infinite size during layout.
flutter: This probably means that it is a render object that tries to be as big as possible, but it was put
flutter: inside another render object that allows its children to pick their own size.
flutter: The nearest ancestor providing an unbounded height constraint is: RenderFlex#dc4b2 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   creator: Column ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
flutter:     CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
flutter:     _InkFeatures-[GlobalKey#513ed ink renderer] ← NotificationListener<LayoutChangedNotification> ←
flutter:     PhysicalModel ← AnimatedPhysicalModel ← ⋯
flutter:   parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
flutter:   constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=818.0)
flutter:   size: MISSING
flutter:   direction: vertical
flutter:   mainAxisAlignment: start
flutter:   mainAxisSize: max
flutter:   crossAxisAlignment: center
flutter:   verticalDirection: down
flutter: The constraints that applied to the RenderConstrainedBox were:
flutter:   BoxConstraints(0.0<=w<=414.0, 0.0<=h<=Infinity)
flutter: The exact size it was given was:
flutter:   Size(414.0, Infinity)
flutter: See https://flutter.dev/docs/development/ui/layout/box-constraints for more information.
flutter:
flutter: The relevant error-causing widget was:
flutter:   UiKitView
flutter:   file:///Users/nevercode/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.22+1/lib/src/webview_cupertino.dart:29:12
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1988:9)
flutter: #1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2056:6)
flutter: #2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1774:7)
flutter: #3      RenderBox.size= (package:flutter/src/rendering/box.dart:1776:6)
flutter: #4      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:273:7)
flutter: #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #6      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:771:15)
flutter: #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #8      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:11)
flutter: #9      _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:497:7)
flutter: #10     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:242:7)
flutter: #11     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:401:14)
flutter: #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #16     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1304:11)
flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #18     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:209:11)
flutter: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #26     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:562:15)
flutter: #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #39     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3263:13)
flutter: #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #43     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:702:15)
flutter: #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1775:7)
flutter: #57     RenderView.performLayout (package:flutter/src/rendering/view.dart:171:13)
flutter: #58     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1638:7)
flutter: #59     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:896:18)
flutter: #60     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:403:19)
flutter: #61     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:881:13)
flutter: #62     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #63     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1114:15)
flutter: #64     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1053:9)
flutter: #65     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:862:7)
flutter: (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: RenderConstrainedBox#71857 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT:
flutter:   creator: SizedBox.expand ← UiKitView ← WebView ← Column ← _BodyBuilder ← MediaQuery ←
flutter:     LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ←
flutter:     AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#513ed ink renderer] ← ⋯
flutter:   parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
flutter:   constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=Infinity)
flutter:   size: Size(414.0, Infinity)
flutter:   additionalConstraints: BoxConstraints(biggest)
flutter: This RenderObject has no descendants.
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: A RenderFlex overflowed by Infinity pixels on the bottom.
flutter: Another exception was thrown: RenderUiKitView object was given an infinite size during layout.
flutter: Another exception was thrown: RenderUiKitView object was given an infinite size during layout.
Lost connection to device.
```

@nsmith1024 You need to limit your WebView height when placing it in Column. For example

```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Column(
          children: [
            Container(
              height: MediaQuery.of(context).size.height - MediaQuery.of(context).padding.vertical,
              child: WebView(
                initialUrl: 'https://flutter.dev',
              ),
            ),
          ],
        )
      ),
    );
  }
}
```

Closing since this is not an issue with flutter

**Comment by iamjithinjohnson** [comment]
> Column. For ex

I changed in my code @VladyslavBondarenko but i cant scroll completely web page

```
import 'dart:async';

import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:share/share.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:get/get.dart';

class WebVieww extends StatelessWidget {
  final String title;
  final String image;
  final String url;
  final String desc;

  WebVieww({
    @required this.title,
    @required this.image,
    @required this.url,
    @required this.desc,
  });
  @override
  Widget build(BuildContext context) {
    Completer<WebViewController> _controller = Completer<WebViewController>();
    return Scaffold(
      backgroundColor: context.theme.backgroundColor,
      floatingActionButton: FloatingActionButton(
        child: Icon(
          Icons.share,
          color: Colors.white,
        ),
        onPressed: () async {
          await Share.share(url);
        },
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          child: Column(
            children: [
              Padding(
                padding: const EdgeInsets.all(12),
                child: Material(
                  elevation: 1,
                  color: context.theme.dividerColor,
                  clipBehavior: Clip.antiAlias,
                  borderRadius: BorderRadius.circular(12),
                  child: Column(
                    children: [
                      CachedNetworkImage(
                        height: MediaQuery.of(context).size.height * 0.55,
                        imageUrl: image,
                        width: MediaQuery.of(context).size.width,
                        fit: BoxFit.cover,
                      ),
                      Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: Text(
                          title,
                          style: TextStyle(
                            fontSize: 22,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ),
                      Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: Text(
                          title,
                          style: TextStyle(fontSize: 18),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Container(
                height: MediaQuery.of(context).size.height -
                    MediaQuery.of(context).padding.vertical,
                child: WebView(
                  initialUrl: url,
                  javascriptMode: JavascriptMode.unrestricted,
                  onWebViewCreated: (WebViewController webViewController) {
                    _controller.complete(webViewController);
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

**Comment by hammyofmha** [comment]
> 
> 
> 
> 
> ## Steps to Reproduce
> 
> 
> 
> I just want to have a button below the WebView
> 
> 
> 
> Put webview_flutter into a column and it crashes (same crash if i put it in a ListView), here is the code::
> 
> 
> 
>       Widget webView= WebView(javascriptMode: JavascriptMode.unrestricted,
> 
>                                           onWebViewCreated: (WebViewController wvc) {
> 
>                                                 webViewController=wvc;
> 
>                                                 _controller.complete(wvc);
> 
>                                                 loadHTML(wvc,context,disp);
> 
>                                           },
> 
>                       );
> 
> 
> 
>       Widget button =  RaisedButton( child: Text("assign"), onPressed: () => showUsers(context));
> 
> 
> 
>       Widget body = new Column(
> 
>               crossAxisAlignment: CrossAxisAlignment.stretch,
> 
>               mainAxisSize: MainAxisSize.min,
> 
>               children: <Widget>[
> 
>                 webView,   // <<<<<<<<<<<<<<<--------- THIS 
> 
>                 button,
> 
>               ],
> 
>             );
> 
> 
> 
>       return Scaffold(
> 
>         appBar: AppBar(title: Text(name)),
> 
>            body: new Padding(
> 
>                 padding: new EdgeInsets.symmetric(vertical: 0.0, horizontal: 0.0),
> 
>                child: body, //<<<<<<<<<<<<<<<<<<<------------- THIS
> 
>               ),
> 
>         );
> 
> 
> 
> 
> 
> 
> 
> Place WebView_flutter into a Column
> 
> 
> 
> ## Logs
> 
> 
> 
> I/flutter (28942): Another exception was thrown: RenderAndroidView object was given an infinite size during layout.
> 
> I/flutter (28942): Another exception was thrown: RenderAndroidView object was given an infinite size during layout.
> 
> I/flutter (28942): Another exception was thrown: RenderPointerListener object was given an infinite size during layout.
> 
> I/flutter (28942): Another exception was thrown: A RenderFlex overflowed by Infinity pixels on the bottom.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ```
> 
> ```
> 
> 
> 
> 
> 
>    info - Name non-constant identifiers using lowerCamelCase - lib\common_widgets\placeholder_widget.dart:11:10 - non_constant_identifier_names
> 
>    info - Unused import: './users.dart' - lib\globals.dart:3:8 - unused_import
> 
>    info - Unused import: './room.dart' - lib\globals.dart:4:8 - unused_import
> 
>    info - Unused import: './hotel.dart' - lib\globals.dart:5:8 - unused_import
> 
>    info - Unused import: './user.dart' - lib\globals.dart:7:8 - unused_import
> 
>    info - Unused import: 'package:flutter_firebase_auth_example/ui/widgets/loading.dart' - lib\home_page.dart:17:8 - unused_import
> 
>    info - The value of the field '_loadingVisible' isn't used - lib\home_page.dart:47:8 - unused_field
> 
>    info - Avoid using braces in interpolation when not needed - lib\home_page.dart:179:40 - unnecessary_brace_in_string_interps
> 
>    info - The value of the local variable 'userId' isn't used - lib\home_page.dart:204:11 - unused_local_variable
> 
>    info - 'GmailSmtpOptions' is deprecated and shouldn't be used - lib\home_page.dart:208:23 - deprecated_member_use
> 
>    info - 'SmtpTransport' is deprecated and shouldn't be used - lib\home_page.dart:212:25 - deprecated_member_use
> 
>    info - 'Envelope' is deprecated and shouldn't be used - lib\home_page.dart:214:26 - deprecated_member_use
> 
>    info - 'Envelope' is deprecated and shouldn't be used - lib\home_page.dart:229:26 - deprecated_member_use
> 
>    info - The value of the local variable 'logo' isn't used - lib\home_page.dart:275:13 - unused_local_variable
> 
>    info - The value of the local variable 'service' isn't used - lib\home_page.dart:525:22 - unused_local_variable
> 
>    info - The method '_readCharacteristic' isn't used - lib\home_page.dart:583:3 - unused_element
> 
>    info - The method '_writeCharacteristic' isn't used - lib\home_page.dart:588:3 - unused_element
> 
>    info - The method '_readDescriptor' isn't used - lib\home_page.dart:594:3 - unused_element
> 
>    info - The method '_writeDescriptor' isn't used - lib\home_page.dart:599:3 - unused_element
> 
>    info - The method '_refreshDeviceState' isn't used - lib\home_page.dart:634:3 - unused_element
> 
> 
> 
>    info - Unused import: 'package:cloud_firestore/cloud_firestore.dart' - lib\hotel_info.dart:1:8 - unused_import
> 
>    info - Name non-constant identifiers using lowerCamelCase - lib\room.dart:23:8 - non_constant_identifier_names
> 
>    info - Unused import: 'package:flutter_local_notifications/flutter_local_notifications.dart' - lib\settings_page.dart:6:8 - unused_import
> 
>    info - Unused import: 'package:flutter_firebase_auth_example/ui/screens/sign_in.dart' - lib\settings_page.dart:8:8 - unused_import
> 
>    info - Unused import: 'tab_monitoring.dart' - lib\settings_page.dart:9:8 - unused_import
> 
>    info - Unused import: 'tab_ranging.dart' - lib\settings_page.dart:10:8 - unused_import
> 
>    info - Use `;` instead of `{}` for empty constructor bodies - lib\settings_page.dart:14:18 - empty_constructor_bodies
> 
>    info - Name non-constant identifiers using lowerCamelCase - lib\settings_page.dart:21:10 - non_constant_identifier_names
> 
>    info - The value of the field '_sos_email' isn't used - lib\settings_page.dart:21:10 - unused_field
> 
>    info - Name non-constant identifiers using lowerCamelCase - lib\settings_page.dart:22:10 - non_constant_identifier_names
> 
>    info - Name non-constant identifiers using lowerCamelCase - lib\settings_page.dart:23:30 - non_constant_identifier_names
> 
>    info - Unused import: 'package:cloud_firestore/cloud_firestore.dart' - lib\show_task.dart:1:8 - unused_import
> 
>    info - The value of the local variable 'webView' isn't used - lib\show_task.dart:69:14 - unused_local_variable
> 
>    info - Unused import: 'user.dart' - lib\task.dart:5:8 - unused_import
> 
>    info - Use `;` instead of `{}` for empty constructor bodies - lib\task.dart:26:18 - empty_constructor_bodies
> 
>    info - Name non-constant identifiers using lowerCamelCase - lib\user.dart:20:8 - non_constant_identifier_names
> 
>    info - Unused import: 'user.dart' - lib\user_store.dart:3:8 - unused_import
> 
>    info - Name non-constant identifiers using lowerCamelCase - lib\user_store.dart:14:8 - non_constant_identifier_names
> 
> 
> 
> 
> 
> ```
> 
> ```
> 
> 
> 
> 
> 
> [√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 6.3.9600], locale en-US)
> 
>     • Flutter version 1.2.1 at D:\HotelDev\flutter
> 
>     • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
> 
>     • Engine revision 3757390fa4
> 
>     • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
> 
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> 
>     • Android SDK at D:\Android\sdk
> 
>     • Android NDK location not configured (optional; useful for native profiling support)
> 
>     • Platform android-28, build-tools 28.0.3
> 
>     • ANDROID_HOME = D:\Android\sdk
> 
>     • Java binary at: D:\Android\android-studio-3.0-preview\android-studio\jre\bin\java
> 
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
> 
>     • All Android licenses accepted.
> 
> 
> 
> [!] Android Studio (version 2.1)
> 
>     • Android Studio at D:\Android\android-studio
> 
>     X Flutter plugin not installed; this adds Flutter specific functionality.
> 
>     X Dart plugin not installed; this adds Dart specific functionality.
> 
>     X Unable to find bundled Java version.
> 
>     • Try updating or re-installing Android Studio.
> 
> 
> 
> [!] Android Studio (version 3.0)
> 
>     • Android Studio at D:\Android\android-studio-3.0-preview\android-studio
> 
>     X Flutter plugin not installed; this adds Flutter specific functionality.
> 
>     X Dart plugin not installed; this adds Dart specific functionality.
> 
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
> 
> 
> 
> [√] Connected device (1 available)
> 
>     • LGL84VL • LGL84VLc12e6a75 • android-arm • Android 7.0 (API 24)
> 
> 
> 
> ! Doctor found issues in 2 categories.
> 
> ```
> 
> ```
> 
>

**Comment by ktw1318** [comment]
me too,  I tried to change My code to "height: MediaQuery.of(context).size.height - MediaQuery.of(context).padding.vertical"  but it does not scroll completely web page!

is way to fix it ? 

please help us ~ 

add . 

some questions
1) How can I know URL's height size ? 

2) if I fixed height , How can i work the scroll ?

**Comment by adrianvintu** [comment]
I also cannot scroll if using provided _solution_

`height: MediaQuery.of(context).size.height - MediaQuery.of(context).padding.vertical,`
