### ISSUE TITLE
Improve documentation WRT webdev on your path

### ISSUE THREAD

**Issue by wmwgithub** [flutter/flutter#32276]
![image](https://user-images.githubusercontent.com/34740295/57347736-ecdce780-7185-11e9-8cf7-8f609252b6f4.png)

**Comment by dnfield** [comment]
Looks like you don't have dart on your `$PATH`... if it is there, maybe restart your terminal session.

**Comment by wmwgithub** [comment]
Thanks ,It need dart on `$PATH` 
- this is my setting for flutter_web
```
FLUTTER_PATH=/usr/local/src/flutter/bin
PUB_CACHE_BIN=$ULS/flutter/.pub-cache/bin
DART_PATH=/usr/local/src/flutter/bin/cache/dart-sdk/bin
export PATH=$PATH:$FLUTTER_PATH:$PUB_CACHE_BIN:$DART_PATH
```
- [offical link](https://github.com/flutter/flutter_web)

**Comment by kevmoo** [comment]
@wmwgithub – did you resolve your issue?

**Comment by wmwgithub** [comment]
yes,I resolve the problem and run the official example successful

**Comment by jonathanagosto** [comment]
In my opinion, it should be part of the *Getting Started* section. I encountered the same problem because I was under the assumption that just by installing the Flutter SDK would be enough.

**Comment by kevmoo** [comment]
Reopening – the docs should be better here!

**Comment by yousifk** [comment]
Problems 
```
> webdev build
Unhandled exception:
ProcessException: ***OUT***

***ERR***
The Flutter SDK is not available.

***
  Command: C:\SDK\flutter\bin\cache\dart-sdk\bin\pub.bat deps
#0      _runPubDeps (package:webdev/src/pubspec.dart:70:5)
<asynchronous suspension>
#1      PubspecLock.read (package:webdev/src/pubspec.dart:84:11)
<asynchronous suspension>
#2      readPubspecLock (package:webdev/src/command/shared.dart:62:39)
<asynchronous suspension>
#3      BuildCommand.run (package:webdev/src/command/build_command.dart:50:29)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#5      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CommandRunner.run (package:args/command_runner.dart:111:11)
#9      run (package:webdev/src/webdev_command_runner.dart:19:56)
#10     main (file:///C:/Users/yk/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/webdev-2.0.4/bin/webdev.dart:17:22)
<asynchronous suspension>
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by kevmoo** [comment]
@yousifk do you have both the Flutter **and** Dart SDKs installed?

**Comment by jonathanagosto** [comment]
@kevmoo I've yet to test on a clean environment, but I suspect that debugging with an IDEs plugin (VS Code, IntelliJ, etc.) works right out-of-the-box without installing Dart SDK. However, running the command in a Terminal fails (as noted in this thread).

Ultimately, the problem lies with the documentation, in my opinion. 😅

**Comment by ml-milkmidi** [comment]
> Thanks ,It need dart on `$PATH`
> 
> * this is my setting for flutter_web
> 
> ```
> FLUTTER_PATH=/usr/local/src/flutter/bin
> PUB_CACHE_BIN=$ULS/flutter/.pub-cache/bin
> DART_PATH=/usr/local/src/flutter/bin/cache/dart-sdk/bin
> export PATH=$PATH:$FLUTTER_PATH:$PUB_CACHE_BIN:$DART_PATH
> ```
> 
> * [offical link](https://github.com/flutter/flutter_web)

Thanks. I't work for me.

**Comment by phanirithvij** [comment]
Added all of them to path
