### ISSUE TITLE
"-bash: webdev: command not found"

### ISSUE THREAD

**Issue by indigothm** [flutter/flutter#32279]
I am trying to get the web flutter running. Updated the bash_profile with export PATH="~/.pub-cache/bin:$PATH". Still doesn't let me run webdev returning "webdev: command not found". Any ideas how to address that?

**Comment by ayush221b** [comment]
Facing the same issue. Really wanted to try it out. Any input would be appreciated.

**Comment by Immortalin** [comment]
instead of `~` try `<your flutter installation folder>/.pub-cache/bin`

**Comment by indigothm** [comment]
> instead of `~` try `<your flutter installation folder>/.pub-cache/bin`

gives:
pub-cache/bin/webdev: line 7: dart: command not found

**Comment by loolooii** [comment]
I have the same problem and error. This does not work.

**Comment by indigothm** [comment]
This worked for me:

```
FLUTTER_PATH=/Users/tikhomirovi/flutter/bin
PUB_CACHE_BIN=/Users/tikhomirovi/flutter/.pub-cache/bin
DART_PATH=/Users/tikhomirovi/flutter/bin/cache/dart-sdk/bin
export PATH=$PATH:$FLUTTER_PATH:$PUB_CACHE_BIN:$DART_PATH
```

**Comment by AmbujaAK** [comment]
Is there any solution for window user, I am getting the error after setting the path too.

**Comment by loolooii** [comment]
Also, you'll need to install dev version of dart. Follow this link:
https://medium.com/@sagarsuri56/getting-started-with-flutter-web-e187829c9dd3

**Comment by bayardkalyan** [comment]
@AmbujaAK  Try adding `C:\Users\<Username>\AppData\Roaming\Pub\Cache\bin` and `C:\flutter\.pub-cache\bin` and `C:\flutter\bin\cache\dart-sdk\bin` to your Path variable and it will solve the problem. If you are using VSCode use cmd or powershell terminal instead of git.

**Comment by androidovshchik** [comment]
Run this command in project folder
```
flutter packages pub global activate webdev
```

**Comment by chkkassd** [comment]
> This worked for me:
> 
> ```
> FLUTTER_PATH=/Users/tikhomirovi/flutter/bin
> PUB_CACHE_BIN=/Users/tikhomirovi/flutter/.pub-cache/bin
> DART_PATH=/Users/tikhomirovi/flutter/bin/cache/dart-sdk/bin
> export PATH=$PATH:$FLUTTER_PATH:$PUB_CACHE_BIN:$DART_PATH
> ```

Thanks,this worked for me, too.

**Comment by foxsofter** [comment]
> Run this command in project folder
> 
> ```
> flutter packages pub global activate webdev
> ```

flutter pub global activate webdev

**Comment by papalardo** [comment]
This resolve with me.
```bash
export PATH="$PATH:$HOME/flutter/bin:$HOME/flutter/.pub-cache/bin:$HOME/flutter/bin/cache/dart-sdk/bin"
```

**Comment by Bikeman868** [comment]
For Windows users this worked for me:

pub global activate webdev

**Comment by ashilfree** [comment]
> This worked for me:
> 
> ```
> FLUTTER_PATH=/Users/tikhomirovi/flutter/bin
> PUB_CACHE_BIN=/Users/tikhomirovi/flutter/.pub-cache/bin
> DART_PATH=/Users/tikhomirovi/flutter/bin/cache/dart-sdk/bin
> export PATH=$PATH:$FLUTTER_PATH:$PUB_CACHE_BIN:$DART_PATH
> ```

Thx my  friend

**Comment by Mathias-Godwin** [comment]
> This resolve with me.
> 
> ```shell
> export PATH="$PATH:$HOME/flutter/bin:$HOME/flutter/.pub-cache/bin:$HOME/flutter/bin/cache/dart-sdk/bin"
> ```

This works like magic... try it out fellas

**Comment by PeachBlack-Alba** [comment]
> > This resolve with me.
> > ```shell
> > export PATH="$PATH:$HOME/flutter/bin:$HOME/flutter/.pub-cache/bin:$HOME/flutter/bin/cache/dart-sdk/bin"
> > ```
> 
> This works like magic... try it out fellas

Where did you run this?

**Comment by Mathias-Godwin** [comment]
> > > This resolve with me.
> > > ```shell
> > > export PATH="$PATH:$HOME/flutter/bin:$HOME/flutter/.pub-cache/bin:$HOME/flutter/bin/cache/dart-sdk/bin"
> > > ```
> > 
> > 
> > This works like magic... try it out, fellas
> 
> Where did you run this?

just add it to a new line in your ".bashrc", are you using an operating system other than Linux? 

does this help?
