### ISSUE TITLE
[web]: link to samples in the repo

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#32283]
Add links to https://flutter.github.io/samples/ to...

- [ ] Root readme of https://github.com/flutter/flutter_web
- [ ] Add a readme to  https://github.com/flutter/flutter_web - `/examples`

**Comment by ayush221b** [comment]
@kevmoo Can I get this done?

**Comment by kevmoo** [comment]
> @kevmoo Can I get this done?

Sadly, no. We sync from an internal Google code base (in the short term). I'm fixing this now!
