### ISSUE TITLE
iPhone 6 memory consumption

### ISSUE THREAD

**Issue by ened** [flutter/flutter#32286]
iPhone 6 Plus shows severe performance issues on long-running Apps. Memory will be allocated but not released.

<img width="846" alt="Screen Shot 2019-05-08 at 06 37 57" src="https://user-images.githubusercontent.com/269860/57352502-79bf7b00-715d-11e9-8e2a-fc8c0ffe21b4.png">
<img width="846" alt="Screen Shot 2019-05-08 at 06 46 46" src="https://user-images.githubusercontent.com/269860/57352503-79bf7b00-715d-11e9-9177-93931cb6e4a9.png">

In  my sample project, the memory consumption will simply keep growing - others have reported issues here #19754 - I can observe the same issue in our main app with a lot more views, images etc.

https://www.gsmarena.com/apple_iphone_6_plus-6665.php - there's only 1GB of RAM, and Apps may allocate up to 650MB. This is easily reached if you extend the sample App with a few images. @cxq1221 invite you to add a sample image loader to the example app below to showcase the problem.

## Steps to Reproduce

1. Clone sample project from here: https://github.com/ened/flutter_iphone6_memory
2. Run it on the iPhone 6
3. Keep running, observe the memory consumption in xcode

## Logs

```
[✓] Flutter (Channel dev, v1.5.8, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.5.8 at /Users/ened/dev/flutter
    • Framework revision 0ba67226ee (13 days ago), 2019-04-24 17:18:28 -0700
    • Engine revision c63d1cf9c9
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.0

[✓] Connected device (2 available)
    • iPhone    • 8abb0e857d6f964b7cb479db5f40cb70da7954b9 • ios • iOS 12.1
```

**Comment by ened** [comment]
Probably the same issue like #32143.

**Comment by rsaf** [comment]
I'm having a similar issue #32820

**Comment by joaquinperaza** [comment]
Same here, flutter is reducing our possibilities with this. :worried:

**Comment by ened** [comment]
Closing for now as latest Flutter dev version plus issue #36935 seem to have a huge impact on my local performance.

Future issues should contain a lot more detail in terms of reproducing the error.

**Comment by DyaryRaoof** [comment]
I have the same issue , can't find a solution.

**Comment by f-martinez11-loro** [comment]
Any solution for this?

**Comment by satishsoni777** [comment]
Same issue , any solution ?
