### ISSUE TITLE
flutter fire firebase_ml_vision object detections 

### ISSUE THREAD

**Issue by startupgurukul** [flutter/flutter#32291]
Hello folks, 
This issue is regarding mlkit object detection annouced recently. Creating an issue to track its implementation in flutter.

Thank you

**Comment by ericklhe** [comment]
Any updates regarding this implementation?

**Comment by kroikie** [comment]
@startupgurukul

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1161. Any further collaboration will be done there.
