### ISSUE TITLE
ReorderableListView items disappear on reorder

### ISSUE THREAD

**Issue by DimitarPetrov** [flutter/flutter#32294]
`ReorderableListView` widget seems to have problems when children widgets are `Column` widgets. My use case is to have a reorderable list of columns consisting of a tile and a divider. When trying to drag an item it is correctly reordered but unfortunately other items disappear although they seems to be there when reordering finishes.

## Steps to Reproduce
Here is a small example app to reproduce the problem. In this example there is one more issue when dragging an item up, it crashes with 

> Multiple widgets used the same GlobalKey.
> The key [GlobalObjectKey ValueKey<String>#4c18a] was used by multiple widgets. 

it is possible to be for this example app only since there is no such a problem in my production code, but items of the list keeps disappearing.

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return MyAppState();
  }
}

class MyAppState extends State<MyApp> {
  List<Widget> items = <Widget>[
    Column(key: Key("1"), children: <Widget>[ListTile(title: Text("a")), Divider()]),
    Column(key: Key("2"), children: <Widget>[ListTile(title: Text("b")), Divider()]),
    Column(key: Key("3"), children: <Widget>[ListTile(title: Text("c")), Divider()]),
    Column(key: Key("4"), children: <Widget>[ListTile(title: Text("d")), Divider()]),
  ];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Title",
      home: Scaffold(
        appBar: AppBar(),
        body: ReorderableListView(
          children: items,
          onReorder: _onReorder,
        ),
      ),
    );
  }

  void _onReorder(int oldIndex, int newIndex) {
    if (newIndex > oldIndex) {
      newIndex -= 1;
    }
    setState(() {
      final Widget item = items.removeAt(oldIndex);
      items.insert(newIndex, item);
    });
  }
}
```

## Logs

```

flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-BG)
    • Flutter version 1.2.1 at /Users/i356426/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/i356426/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

**Comment by xuzhongpeng** [comment]
i have the same problem,how did you solve it

**Comment by DimitarPetrov** [comment]
@xuzhongpeng
Sadly i didn't, just removed the columns and used it with tiles only.

**Comment by xuzhongpeng** [comment]
> @xuzhongpeng
> Sadly i didn't, just removed the columns and used it with tiles only.

I don't know what's wrong with you, but I solved my problem.
copy ReorderableListView class from the file *reorderable_list.dart* to anyplace  Because we need to modify a source code
then modify the line 184
```
static const double _defaultDropAreaExtent = 100.0;
```
to
```
static const double _defaultDropAreaExtent = 5.0;
```
at last modify the line 368 to
```
 void onDragEnded() {
      reorder(_dragStartIndex, _currentIndex);
+      _scrollController.animateTo(
+        0,
+        duration: _scrollAnimationDuration,
+        curve: Curves.easeInOut,
+     );
    }
```
my problem is like this
![](	https://blog-1253495453.cos.ap-chongqing.myqcloud.com/flutter%E6%BB%91%E5%8A%A8%E9%97%AE%E9%A2%98.gif)

**Comment by atul161** [comment]
i had also a same problem ...Make your list item unique ..i think this will solve your problem

**Comment by moritzmorgenroth** [comment]
https://github.com/flutter/flutter/issues/21829#issuecomment-424412362 is the solution that worked for me

**Comment by Furtim** [comment]
This is caused by the column trying to take the max space, which while it's dragging is the entire screen size - the other elements are there, just behind.

`                    mainAxisSize: MainAxisSize.min,
`
in your column fixes it.

**Comment by DimitarPetrov** [comment]
> This is caused by the column trying to take the max space, which while it's dragging is the entire screen size - the other elements are there, just behind.
> 
> Adding:
> ` mainAxisSize: MainAxisSize.min,`
> in your column fixes it.

@Furtim This actually solved the issue! Thank you very much!
