### ISSUE TITLE
raw_keyboard.mojom.dart only gets generated into sky_services on Android builds

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#323]
...and not Linux builds. Shouldn't they be identical?

Since we tend to ship the output from Linux builds (right?) this seems like it might cause problems down the road, too.

**Comment by abarth** [comment]
We ship the packages from an Android build.  However, we should build the mojoms on all platforms for consistency.

**Comment by Hixie** [comment]
raw_keyboard.mojom.dart is now included in all builds.
