### ISSUE TITLE
Issue from website page 起步:安装Flutter

### ISSUE THREAD

**Issue by DarranFan** [flutter/flutter#32303]
From URL: https://www.flutterchina.club/get-started/install.md
![image](https://user-images.githubusercontent.com/23433152/57368978-0ea69080-71bf-11e9-875b-7fedec212a7a.png)

对这个问题我已经安装两次环境了 第二次好了，然后我运行一小会之后又出现这个问题了，不知道该怎么解决了

**Comment by stuartmorgan** [comment]
Duplicate of #36789
