### ISSUE TITLE
How to get context globally?

### ISSUE THREAD

**Issue by HannibalKcc** [flutter/flutter#32304]
## Scenes
I am using [dio](https://github.com/flutterchina/dio) help me with network requests.

I want to set a loading dialog (maybe need toast ,too)when the request is not completed. But i hope is that the interceptor is globally set, rather than a separate request.

At this point, consider using an interceptor to accomplish this task.
```
dio.interceptors.add(
    InterceptorsWrapper(
      onRequest: (RequestOptions options) {
        // showdialog ps: how can i get a context?
      },
      onResponse: (Response response) {
        // closedialog
      }，
   )
}
```

## question
How can I get the context? Or what other methods are used to achieve the desired scenario?

btw: when i store the `top widget's` context in a global variable in the build i will get error.
part of console:
```
E/flutter (26120): MyApp widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
E/flutter (26120): Localizations are used to generate many different messages, labels,and abbreviations which are used by the material library. 
E/flutter (26120): To introduce a MaterialLocalizations, either use a  MaterialApp at the root of your application to include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
E/flutter (26120): The specific widget that could not find a MaterialLocalizations ancestor was:
```

It looks like i can't use `top widget's` context.
thanks for any help. :)

**Comment by HannibalKcc** [comment]
(example)[https://github.com/OpenFlutter/flutter_oktoast]

**Comment by jiyarong** [comment]
How would you resolve this problem? I can not understand above example

**Comment by lyseiha** [comment]
i wonder how does it work too.

**Comment by HannibalKcc** [comment]
@jiyarong @lyseiha 

According to the beginning of my problems，i need a `dialog` without `context`.
the [example flutterOktoast](https://github.com/OpenFlutter/flutter_oktoast) can create a `dialog`(not `showDialog()`) without `context`.It solves my problem, If you review its source code, You will find that it actually uses `Overlay`.

But, sometimes we still need `context`, like `Navigator.push(context, route)`.

so here is the example:

main.dart
```
@override
Widget build(BuildContext context) {
  return MaterialApp(
    navigatorKey: Application.navKey, // GlobalKey()
  )
}
```

PageA.dart
```
Application.navKey.currentState.push(
  MaterialPageRoute(builder: (context) => PageB()),
);
```

I hope I expressed clearly  ：）

**Comment by hbshun** [comment]
But what is the Application? How to get it?

**Comment by anticafe** [comment]
https://medium.com/flutter-community/navigate-without-a-buildcontext-in-flutter-code-guide-2d344ee0e4d6
This is really helpful article to guide how to use GetIt to create a NavigationService without needing BuildContext.

**Comment by HannibalKcc** [comment]
> But what is the Application? How to get it?

Application is a Global Class witch has some static property.
You can delacre it in a file(e.g. Application.dart),then import and use it where you need.
