### ISSUE TITLE
Cannot target Intel processors since v1.5.4-hotfix.2

### ISSUE THREAD

**Issue by ndusart** [flutter/flutter#32305]
## Steps to Reproduce

1. Update Flutter to v1.5.4-hotfix.2 (latest stable)
2. Run `flutter build apk --target-platform android-x86` or `flutter build apk --target-platform android-x64` on any project
3. This fails with this error message: "android-x64" is not an allowed value for option "target-platform". 

It was working on the previous stable version (v1.2.1)

**Comment by blasten** [comment]
I just hit this problem. Thanks for reporting!

**Comment by jason-simmons** [comment]
Flutter does not support AOT compiled modes (`--profile` and `--release`) on `android-x86` and `android-x64` target platforms.

For x86/x64 you'll need to use `--debug` mode.

**Comment by ndusart** [comment]
@jason-simmons , yes, actually this was not working with v1.2.1 either. I maybe tried in `--debug` mode at the time. Thanks for the information.

Any plan to add support for release mode ?
