### ISSUE TITLE
SocketException: Socket has been closed

### ISSUE THREAD

**Issue by ThitSarNyanLynn** [flutter/flutter#32306]
I got the following error when I run these simple codes. 

```
import 'dart:async';
import 'package:mysql1/mysql1.dart';

Future main() async {
  final conn = await MySqlConnection.connect(new ConnectionSettings(
      host: '192.168.1.3', port: 3306, user: 'root', db: 'ppms'));

  var results = await conn
      .query('select * from user');

  for (var row in results) {
    print('UserName: ${row[0]}, Password: ${row[1]}');
  }
  await conn.close();
}
```

E/flutter ( 6312): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: Socket has been closed
E/flutter ( 6312): #0      MySqlConnection.connect (package:mysql1/src/single_connection.dart:142:5)
E/flutter ( 6312): <asynchronous suspension>
E/flutter ( 6312): #1      main (package:f_sqljocky_test/main.dart:8:38)
E/flutter ( 6312): <asynchronous suspension>
E/flutter ( 6312): #2      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:189:25)
E/flutter ( 6312): #3      _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 6312): #4      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 6312): #5      _runZoned (dart:async/zone.dart:1516:10)
E/flutter ( 6312): #6      runZoned (dart:async/zone.dart:1500:12)
E/flutter ( 6312): #7      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:180:5)
E/flutter ( 6312): #8      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
E/flutter ( 6312): #9      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
E/flutter ( 6312): 
Syncing files to device Android SDK built for x86...

**Comment by ItsNotMyFault** [comment]
I've got a similar problem trying to run similar line of code.
E/flutter ( 7524): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 159.203.13.220, port = 53786
E/flutter ( 7524): #0      MySqlConnection.connect
package:mysql1/src/single_connection.dart:142
E/flutter ( 7524): <asynchronous suspension>
E/flutter ( 7524): #1      GameDatabase.GetLastMove
package:flutter_tic_tac_toe/…/tic-tac-toe10_1v1_database/game_database.dart:54
E/flutter ( 7524): <asynchronous suspension>
E/flutter ( 7524): #2      GamePageState._movePlayed
package:flutter_tic_tac_toe/…/tic-tac-toe10_1v1_database/game_page_database.dart:127
E/flutter ( 7524): <asynchronous suspension>
E/flutter ( 7524): #3      GamePresenter_Database.onHumanPlayed
package:flutter_tic_tac_toe/…/tic-tac-toe10_1v1_database/game_presenter_database.dart:21
E/flutter ( 7524): <asynchronous suspension>
E/flutter ( 7524): #4      GamePageState._movePlayed.<anonymous closure>
package:flutter_tic_tac_toe/…/tic-tac-toe10_1v1_database/game_page_database.dart:150
E/flutter ( 7524): #5      State.setState 
package:flutter/…/widgets/framework.dart:1122
E/flutter ( 7524): #6      GamePageState._movePlayed
package:flutter_tic_tac_toe/…/tic-tac-toe10_1v1_database/game_page_database.dart:140
E/flutter ( 7524): #7      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
E/flutter ( 7524): #8      GamePageState._movePlayed
package:flutter_tic_tac_toe/…/tic-tac-toe10_1v1_database/game_page_database.dart:121

**Comment by itzmeanjan** [comment]
@ItsNotMyFault , may be you're closing your connection to database before it fetches all data.

Need to see code, for further investigation.

**Comment by AmSn6** [comment]
@ThitSarNyanLynn did you solve the error?

**Comment by ItsNotMyFault** [comment]
I didn't solve it, I simply gave up on MySQL1 and used PHP to create the connection to the database. Just used http request  to access web services.

**Comment by BondarenkoStas** [comment]
@ThitSarNyanLynn is the issue still relevant?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by gui-garcia87** [comment]
Is privilege issue, check your privilege for root user and grant all privileges for 'root'@'%' like :
grant all privileges on *.* to 'root'@'%';
check into your database using:
show grants for 'root'@'%';

**Comment by ahmed9378** [comment]
> Is privilege issue, check your privilege for root user and grant all privileges for 'root'@'%' like :
> grant all privileges on _._ to 'root'@'%';
> check into your database using:
> show grants for 'root'@'%';

Thanks. this one solves the problem for me. I change "localhost" to "%" and it works now.
