### ISSUE TITLE
[web]: Can't load Kernel binary: Invalid kernel binary format version. No active package webdev.

### ISSUE THREAD

**Issue by jkmpariab** [flutter/flutter#32319]
cant start building for web when running "webdev serve" or even "webdev"
error: 
Can't load Kernel binary: Invalid kernel binary format version.
No active package webdev.

**Comment by Botanium** [comment]
this happens due to the mismatch of Dart-Sdk. make sure to have Dart 2.2 and above. It is better only to depend on the Dart-Sdk from Flutter instead of the standalone Dart-Sdk.

**Comment by jkmpariab** [comment]
great. yea that's right. thank you

**Comment by Botanium** [comment]
You are welcome.

**Comment by proud2008** [comment]
webdev serv
Can't load Kernel binary: Invalid kernel binary format version.
webdev 2.5.0 doesn't support Dart 2.3.0.

**Comment by lutang123** [comment]
> this happens due to the mismatch of Dart-Sdk. make sure to have Dart 2.2 and above. It is better only to depend on the Dart-Sdk from Flutter instead of the standalone Dart-Sdk.

Hi, thank you, but how exactly I can do to fix it?

**Comment by yasinarik** [comment]
> this happens due to the mismatch of Dart-Sdk. make sure to have Dart 2.2 and above. It is better only to depend on the Dart-Sdk from Flutter instead of the standalone Dart-Sdk.

Thanks for the reply but can you please describe how its done?
