### ISSUE TITLE
image_picker with Flutter 1.5.9

### ISSUE THREAD

**Issue by Tomucha** [flutter/flutter#32315]
I upgraded Flutter:

    [✓] Flutter (Channel master, v1.5.9-pre.177, on Mac OS X 10.13.6 17G3025, locale cs-CZ)

... and `image_picker: 0.6.0+2` is not working anymore.

    var image = await ImagePicker.pickImage(source: ImageSource.camera);

It allows me to take and confirm a photo, but the Future in the statement above is never resolved and in the `flutter run` output I can see:

```

W/Binder  ( 8963): Caught a RuntimeException from the binder stub implementation.
W/Binder  ( 8963): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Binder:8963_1
W/Binder  ( 8963): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
W/Binder  ( 8963): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:556)
W/Binder  ( 8963): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:129)
W/Binder  ( 8963): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:215)
W/Binder  ( 8963): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.finishWithSuccess(ImagePickerDelegate.java:540)
W/Binder  ( 8963): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:505)
W/Binder  ( 8963): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.access$000(ImagePickerDelegate.java:66)
W/Binder  ( 8963): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate$4.onPathReady(ImagePickerDelegate.java:470)
W/Binder  ( 8963): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate$3$1.onScanCompleted(ImagePickerDelegate.java:160)
W/Binder  ( 8963): 	at android.media.MediaScannerConnection$ClientProxy.onScanCompleted(MediaScannerConnection.java:204)
W/Binder  ( 8963): 	at android.media.MediaScannerConnection$1.scanCompleted(MediaScannerConnection.java:53)
W/Binder  ( 8963): 	at android.media.IMediaScannerListener$Stub.onTransact(IMediaScannerListener.java:61)
W/Binder  ( 8963): 	at android.os.Binder.execTransact(Binder.java:731)


```

If it helps: It happened with image_picker 0.4 too, so I decided that it's time to upgrade to AndroidX and upgrade image_picker along the way, but no luck. After upgrade - same exception.

I tried to harvest "retrieveLostData()" but nothing there.

When I try to take another photo, it ends with a different error:

```
E/flutter ( 8963): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null)
E/flutter ( 8963): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter ( 8963): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter ( 8963): <asynchronous suspension>
E/flutter ( 8963): #2      ImagePicker.pickImage (package:image_picker/image_picker.dart:56:40)
E/flutter ( 8963): <asynchronous suspension>
E/flutter ( 8963): #3      _ImagesSlideshowState.loadOverlayPhoto (package:app/screens/images_slideshow.dart:405:37)
E/flutter ( 8963): <asynchronous suspension>
E/flutter ( 8963): #4      _ImagesSlideshowState.uiActionCallBack (package:app/screens/images_slideshow.dart:276:9)
E/flutter ( 8963): #5      TopBar.build.<anonymous closure> (package:app/ui/widgets/top_bar.dart:95:34)
```

... and I have to restart the whole app (hot restart is not enough).

**Comment by LucazzP** [comment]
I'm with the same error, I need a solution too!!
I tried on iOS and works fine, but in Android, I have the same error with image_picker, that accuses the Binder.

**Flutter doctor -v:**
`Microsoft Windows [versão 10.0.18362.86]
(c) 2019 Microsoft Corporation. Todos os direitos reservados.

C:\WINDOWS\system32>flutter doctor -v
[√] Flutter (Channel master, v1.5.9-pre.178, on Microsoft Windows [versÃ£o 10.0.18362.86], locale pt-BR)
    • Flutter version 1.5.9-pre.178 at C:\flutter
    • Framework revision 45d2b15d97 (10 hours ago), 2019-05-08 05:29:39 -0400
    • Engine revision ac4f3c9945
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 8143450941)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Lucas-Not\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code, 64-bit edition (version 1.33.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.25.1

[√] Connected device (1 available)
    • ONEPLUS A5010 • a9402cf8 • android-arm64 • Android 9 (API 28)

• No issues found!

C:\Windows\System32>`

**Error:**
`Launching lib\main.dart on ONEPLUS A5010 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-3.0.4\android\src\main\java\io\github\ponnamkarthik\toast\fluttertoast\FluttertoastPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\tflite-1.0.3\android\src\main\java\sq\flutter\tflite\TflitePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device ONEPLUS A5010...
I/flutter (21363): success
D/DecorView(21363): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@7fe555e[MainActivity]
E/Choreographer(21363): skip doframe for com.dodvision.face_recognition
E/Choreographer(21363): skip doframe for com.dodvision.face_recognition
D/DecorView(21363): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@7fe555e[MainActivity]
W/Binder  (21363): Caught a RuntimeException from the binder stub implementation.
W/Binder  (21363): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Binder:21363_4
W/Binder  (21363): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
W/Binder  (21363): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:556)
W/Binder  (21363): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:129)
W/Binder  (21363): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:215)
W/Binder  (21363): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.finishWithSuccess(ImagePickerDelegate.java:540)
W/Binder  (21363): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:505)
W/Binder  (21363): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.access$000(ImagePickerDelegate.java:66)
W/Binder  (21363): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate$4.onPathReady(ImagePickerDelegate.java:470)
W/Binder  (21363): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate$3$1.onScanCompleted(ImagePickerDelegate.java:160)
W/Binder  (21363): 	at android.media.MediaScannerConnection$ClientProxy.onScanCompleted(MediaScannerConnection.java:239)
W/Binder  (21363): 	at android.media.MediaScannerConnection$1.scanCompleted(MediaScannerConnection.java:64)
W/Binder  (21363): 	at android.media.IMediaScannerListener$Stub.onTransact(IMediaScannerListener.java:61)
W/Binder  (21363): 	at android.os.Binder.execTransact(Binder.java:752)
W/System  (21363): A resource failed to call close. `

**Comment by jason-simmons** [comment]
The Android embedder is now checking that platform->Dart messages are sent from the platform thread.

The image_picker plugin had been sending a method call reply from an Android media scanner callback that runs on a background thread.

**Comment by Tomucha** [comment]
Confirmed, it's working again in 0.6.0+3. Thanks!!!

**Comment by lhcdims** [comment]
> The Android embedder is now checking that platform->Dart messages are sent from the platform thread.

May I ask when did this "CHECKING" begins?  I believe it might affect either the adhara_socket_io package, and/or the fluttertoast package, because I'm receiving the 'Methods marked with @UiThread must be executed on the main thread. Current thread: EventThread' error, after running 'flutter upgrade' for the master channel an hour ago.  And this error disappears when I roll back to the beta channel.

**Comment by jason-simmons** [comment]
See https://github.com/flutter/engine/commit/2c9e37c34e79475bbde7c8163eb5e56cdb9662a1

**Comment by lhcdims** [comment]
> See [flutter/engine@2c9e37c](https://github.com/flutter/engine/commit/2c9e37c34e79475bbde7c8163eb5e56cdb9662a1)

I checked the source code of flutter/engine@2c9e37c

Ok, correct me if I’m wrong, if the current master channel becomes the beta channel, and some flutter packages are still using other threads to send messages (instead of the main thread), using those packages would cause the app to crash.

May I ask do I need to check each package myself?  or the flutter team will have someone take care of this?  I think I can help, at least to check all packages I’m using and report issues if there is any.

Anyway, your information provided is really helpful, at least I know why my app crashes without any code changes, but just a flutter upgrade.  thank you.

**Comment by rignaneseleo** [comment]
I get the same issue with the same plugin:
```
E/AndroidRuntime( 6350): FATAL EXCEPTION: pool-2-thread-1
E/AndroidRuntime( 6350): Process: boydpearce.my_grand_kids, PID: 6350
E/AndroidRuntime( 6350): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-2-thread-1
E/AndroidRuntime( 6350): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/AndroidRuntime( 6350): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:556)
E/AndroidRuntime( 6350): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:131)
E/AndroidRuntime( 6350): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime( 6350): 	at top.kikt.imagescanner.ImageScanner$getImagePathIdList$1.run(ImageScanner.kt:553)
E/AndroidRuntime( 6350): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 6350): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 6350): 	at java.lang.Thread.run(Thread.java:764)
I/Process ( 6350): Sending signal. PID: 6350 SIG: 9
Lost connection to device.
```

I'm using:
- image_picker: ^0.6.0+3
- Dart 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)
- Flutter 1.6.0
- Android Studio (version 3.4.1)

How can I fix it?

**Comment by jigarpatel17** [comment]
Getting same error in ```^0.6.0+3``` version as well.

Error: ```Caught error: PlatformException(already_active, Image picker is already active, null)```

**Comment by kw2019ltd** [comment]
getting the smae issue with latest plugin 

Non-fatal Exception: java.lang.Exception: PlatformException(already_active, Image picker is already active, null)


![image](https://user-images.githubusercontent.com/47334522/86585663-7dcc7000-bf8f-11ea-8b3d-a26f685826bc.png)

**Comment by zihong00** [comment]
Getting same error with latest plugin.

**Comment by zhangwei911** [comment]
Version:image_picker: ^0.6.7+7
Reason:the image picker plugin did not receive onActivityResult
Solution:
when add flutter module to Native App, use FlutterFragment,we should add the follow to the Activity
```
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        fragment.onActivityResult(requestCode, resultCode, data)
    }
````

**Comment by YoSalcido** [comment]
> Version:image_picker: ^0.6.7+7
> Reason:the image picker plugin did not receive onActivityResult
> Solution:
> when add flutter module to Native App, use FlutterFragment,we should add the follow to the Activity
> 
> ```
> override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
>         super.onActivityResult(requestCode, resultCode, data)
>         fragment.onActivityResult(requestCode, resultCode, data)
>     }
> ```

@zhangwei911 can you show which file I have to add this code? And the full code for that file.?

**Comment by YoSalcido** [comment]
> Version:image_picker: ^0.6.7+7
> Reason:the image picker plugin did not receive onActivityResult
> Solution:
> when add flutter module to Native App, use FlutterFragment,we should add the follow to the Activity
> 
> ```
> override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
>         super.onActivityResult(requestCode, resultCode, data)
>         fragment.onActivityResult(requestCode, resultCode, data)
>     }
> ```

@zhangwei911 can you show which file I have to add this code?
