### ISSUE TITLE
re-baseline flutter analyze benchmarks

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#32320]
Once https://github.com/dart-lang/sdk/issues/36881 has been fixed (a ~12% performance regression in the flutter analyze benchmarks), we should rebaseline the benchmarks.

Previously these were;
- 71.5s, 74.4s
- 71.6s, 74.8s
- 24.1s, 25.2s
- 18.3s, 19.2s

**Comment by Hixie** [comment]
This bug is mentioned on the Bad Builds page.

**Comment by Hixie** [comment]
Done!
