### ISSUE TITLE
firebase_auth onAuthStateChanged doesn't refresh from Firebase

### ISSUE THREAD

**Issue by newtonmunene99** [flutter/flutter#32324]
I know that the whole point of onAuthStateChanged is to get when a user logs in and out. From my understanding, the FirebaseUser is cached in the device. 
I'm however facing an issue. When I'm using onAuthStateChanged with the Js/Web SDK it catches all changes even those in Firebase. For example deleting/disabling a user, verifying email etc. 
But in Flutter when I delete a user from firebase console or when a user verifies their email it doesn't seem to update. The user has to completely log out and then try to log back in. or use ` reload()` method

**Comment by collinjackson** [comment]
How does this compare to the native iOS/Android behavior?

**Comment by newtonmunene99** [comment]
I haven't used firebase_auth in native IOS/Android before. After posting the issue I researched around the internet and realized that the JS SDK has a different implementation for that and why it wouldn't be ideal to use that for Flutter and native Android/Ios. For now the `reload()` method on the `FirebaseUser ` object will do. The only problem is that I have to call `currentUser()` twice, before reload and after reload, for the `FirebaseUser `object to actually update.

**Comment by collinjackson** [comment]
Sounds like a bug, I think that `reload()` should probably mutate the current user object to have the correct data. 

Filed #32431

**Comment by kroikie** [comment]
@newtonmunene99

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/376. Any further collaboration will be done there.

**Comment by feinstein** [comment]
I made a package to fix this, grab it here: [firebase_user_stream](https://pub.dev/packages/firebase_user_stream) 

In the Readme I explain the issues and how the package fixes them, there are examples and etc, enjoy!
