### ISSUE TITLE
Render app inside custom html element

### ISSUE THREAD

**Issue by lejard-h** [flutter/flutter#32329]
Have not found anything like that (yet).
Is it possible to render an app inside a custom html element, not on the body ?

Something similar to react

```html
<div id="root"></div>
```

```dart
runApp(App(), root: '#root");
```

It could help integrating flutter widget into existing Angular Dart app

**Comment by yjbanov** [comment]
This should also enable developers publishing apps as web components.

**Comment by bratyslav** [comment]
If this is easier to do, than #32326 I would go for it
Like, you can have half of screen covered with <video> tag and another one with flutter
Or put <video> as background, and make flutter view transparent

**Comment by Ephenodrom** [comment]
This would be really nice, for example if you use bootstrap for your website and want to add a flutter app under the boostrap navbar, so it will fit seamlessly inside your page. In this case the flutter app has to be rendered under the <div class="container">...</div>.

**Comment by kleinpetr** [comment]
Is there some news about this feature?? How can I set root html element of app?

**Comment by yjbanov** [comment]
No progress yet. The only workaround we're aware of is to put the Flutter app in an iframe and communicate with the hosting page via [Window.postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage).

**Comment by maszhin** [comment]
@yjbanov Is anyone working on right now? A few weeks ago I implemented this for integration with Angular components and it worked quite well. 

As this would be breaking change (I guess we can't use body anymore) - all examples would need to apply the change

**Comment by yjbanov** [comment]
@maszhin Nobody on the team is actively working on this.

**Comment by maszhin** [comment]
@yjbanov Thanks. I will send PR next week

**Comment by oantajames** [comment]
@maszhin any news in regards to the PR ?  😄

**Comment by yjbanov** [comment]
While we welcome pull requests, I'd like to give a heads-up that this may not be a small project. To implement this correctly we need to make sure all of the following work correctly between the non-Flutter host content and the hosted Flutter app:

- Gesture detection
- Accessibility
- Layout: we will likely have to measure the host page before rendering a Flutter frame because Flutter uses an open layout system. This needs to be done carefully to avoid performance issues.
- App lifecycle: how to properly control the launch and shut-down of a Flutter app.
- CSS encapsulation
- `<meta name="viewport">` configuration that works across Flutter and non-Flutter content.

These are just first things that came to my mind.

**Comment by sudip4036** [comment]
Any update on this feature ? This will enable flutter web to integrate with other product effectively.

**Comment by meold** [comment]
Any update on this feature ?

**Comment by Kishan-Kalburgi** [comment]
Hey team, we'll be happy to know if you have any estimated deadline to roll this feature out? 

Thank you
Kishan

**Comment by yjbanov** [comment]
As of today there has been no progress on this.

@sudip4036 @meold @Kishan-Kalburgi Is there anything you'd like to be able to do by hosting on the same page that you are unable to do using an iframe?

**Comment by Deeplightened** [comment]
As for today is there any documented workaround for using an iframe inside a js framework (Vuejs for example) ?
It's kind of hard to make the iframe work just by putting it inside some html template or component. Mainly because it seems the framework do some internal operations with other local js file (like the main.dart.js provided with the Flutter web build that cannot be loaded it seems).

Having an example of how to integrate this iframe with theses framework would greatly help.

**Comment by Y0geshsharma** [comment]
I tried with iframe but while you build the flutter web it creates a web socket so you which makes you build the project and use the web in some web server like express.. from there only I was able to access the iframe.
Now can anyone suggest the flutter equivalent for receiving data in iframe

**Comment by filiph** [comment]
I'd like to note that this scenario is one of the three noted on https://flutter.dev/web. 

> In this early stage of development, we envision the web version of Flutter being valuable in many scenarios. For example:
>
> * [...]
> * **Embedded interactive content** - Flutter provides a powerful environment for creating rich, data-centric components that can be easily hosted within an existing web page. Whether for data visualization, an online tool like a car configurator, or an embedded chart, Flutter can provide a productive development approach for embedded web content.
> * [...]

I know the site says "envision", but still -- we might be setting expectations too high over there. Should we update it? cc @sfshaza2

**Comment by rodydavis** [comment]
For anyone that is curious here is how you can render a flutter app inside of a webpage.

https://github.com/rodydavis/flutter_web_component

<img width="754" alt="flutter-web-component" src="https://user-images.githubusercontent.com/31253215/78304381-7494b880-74f3-11ea-9589-714fc47f0a26.png">

**Comment by rbluethl** [comment]
Hey @rodydavis, could you please explain in more detail how this is supposed to work? I don't really get it. 😄

**Comment by JonasJW** [comment]
> For anyone that is curious here is how you can render a flutter app inside of a webpage.
> 
> https://github.com/rodydavis/flutter_web_component
> 
> <img alt="flutter-web-component" width="754" src="https://user-images.githubusercontent.com/31253215/78304381-7494b880-74f3-11ea-9589-714fc47f0a26.png">

Is it possible to communicate between the two applications? Like passing in data to the Flutter App?

**Comment by beevelop** [comment]
@rodydavis' example is also using an iFrame to embed the Flutter app (see https://github.com/rodydavis/flutter_web_component/blob/master/web/flutter-app.js#L16). It's actually using a custom HTML element, but it does not mount the Flutter app into the existing DOM.

@yjbanov For existing applications it might be interesting to embed Flutter apps natively. E.g. speaking of React application where parts of the application are meant to be replaced by Flutter in the future. If the communication between Flutter Web and the (legacy) React application would be seamless, you could trigger Toast notifications or similar UI behavior. This could simplify the gradual switch to Flutter Web 😉 

Is there a good resource about the Flutter Web internals and how it currently "mounts itself into the DOM"?

**Comment by JonasJW** [comment]
Are there any updates on this topic?

**Comment by shalva97** [comment]
any news? I want this for some of my projects...

**Comment by yjbanov** [comment]
No progress has been made yet, unfortunately. However, as an initial step, we do plan to try wrapping the Flutter app into a web-component soon. Our immediate motivation is to switch to `<slot>` for embedding platform views. It should (:crossed_fingers:) fix a lot of platform view issues (arbitrarily reloading iframes, blinking video tags, lost DOM state), but it's also a more idiomatic approach on the web these days. Even though by itself it does not provide support for custom host element, it will get us closer architecturally. The next step after that would be to remove our dependency on the `<body>` tag.

**Comment by fzyzcjy** [comment]
hi any updates? flutter 2.0 has released for weeks and web is stable now!

**Comment by CaoGiaHieu-dev** [comment]
hi , can someone expand how to add 2 widget in 1 html ?

**Comment by alexshikov** [comment]
Hi there, we are also interested in this topic. Any plans to support this in the nearest months?

**Comment by casp4** [comment]
Maybe a flutter app can be packaged into an npm package? Anyone tried that? Would love example code.

**Comment by Gene-Dana** [comment]
Hi there everyone ! 

Before Vue became very popular, I remember that this capability of injecting Vue into any webpage really convinced me to invest the time and energy to learn and understand Vue. 

With it's popularity now, it seems like I was not the only one !

Anything I can do to help, please let me know. I would love to extend our value proposition of flexibility into this domain !

**Comment by sfmskywalker** [comment]
Hi everyone! I'm new to Flutter. I'm looking for a good alternative to StencilJS which I primarily use to build web components. It would be awesome if I could create web components using Flutter instead.

**Comment by joshmossas** [comment]
Hey @sfmskywalker Flutter does not use or create web components. So you'll need to look elsewhere for this feature. I would not consider Flutter an alternative to StencilJS.

Also please be aware that this issue page is not the place to ask questions like this. People who are subscribed to updates on the status of this issue get emails for every comment posted here. There are dedicated community forums where you can ask questions about Flutter vs X framework and things of that nature. I'll link them below. Cheers!

- [Flutter Discord Server](https://discord.com/invite/N7Yshp4)
- [FlutterDev Subreddit](https://www.reddit.com/r/FlutterDev/)
- [Flutter Gitter Community](https://gitter.im/flutter/flutter)
- [Flutter Google Group](https://groups.google.com/g/flutter-dev)

**Comment by laurensdewaele** [comment]
I've managed to specify where Flutter needs to attach itself onto.

> dartMainRunner(main, args):
> if this function is defined, the Dart [main] method will not be invoked
> directly. Instead, a closure that will invoke [main], and its arguments
> [args] is passed to [dartMainRunner].

This lets us hijack the execution, and by monkey patching the appendChild function, we can specify the output instead of the default html `body`.

script on index.html or somewhere global.
```
      let mainDartRunner;

      function makeApp(el) {
        const originalAppendChild = document.body.appendChild;
        let shadow = el.attachShadow({mode: 'open'});

        document.body.appendChild = function appendChild(...args) {
          el.appendChild.apply(shadow, args);
        };

        mainDartRunner();

        document.body.appendChild = originalAppendChild;
      }

      function dartMainRunner(main) {
        mainDartRunner = main;
      }
   ```
   
   Then in React (or JS) we can do:
   ```
function App() {
  const ref = useCallback(node => {
    if (node !== null) {
      const editor = window.makeEditor(node);
    }
  }, []);

  return <Main ref={ref} id={"flutter-target"} />
}
```

The flutter element is positioned absolute, so we do need to specify our parent div to be `position: relative`.

Haven't tested it fully, but seems to work.

**Comment by Kiruel** [comment]
Hi, @laurensdewaele. Do you have some code example (repo) somewhere?

**Comment by wangying3426** [comment]
hi any updates?  we have the same problem~

**Comment by MoacirSchmidt** [comment]
@laurensdewaele 's solution is perfect!

**Comment by YoussefRaafatNasry** [comment]
I have built a [working website](https://youssefraafatnasry.github.io/lo_form/) using solutions by @yjbanov & @rodydavis. It uses the following:

 - [Jekyll](https://jekyllrb.com/): to generate the static pages
 - [Web component](https://developer.mozilla.org/en-US/docs/Web/Web_Components): to render Flutter app inside a custom element 
 - [`window.postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage): to communicate between Flutter and JS.
 
 See the [source code](https://github.com/YoussefRaafatNasry/lo_form/tree/master/website) for more info.

**Comment by PaulDFPV** [comment]
I had a little success with the method described by @laurensdewaele.

Run ```flutter build web``` then add the following below the opening body tag of ```index.html```:

```
<h1>Html content</h1>
<div id="flutter" style="position: relative"></div>

<script>
  let mainDartRunner;

  function makeApp(el) {
    const originalAppendChild = document.body.appendChild;
    let shadow = el.attachShadow({ mode: "open" });

    document.body.appendChild = function appendChild(...args) {
      el.appendChild.apply(shadow, args);
    };

    mainDartRunner();

    document.body.appendChild = originalAppendChild;
  }

  function dartMainRunner(main) {
    mainDartRunner = main;
  }

  setTimeout(() => window.makeApp(document.getElementById("flutter")), 1000);
</script>
```

However, it throws the cursor position out on the Flutter app.

**Comment by rpk98c** [comment]
Has there been any progress on this issue or suggested workarounds? 

It would be a huge help in using Flutter in more places. We have the issue of being forced to use iFrames and this is fair from ideal as the iFrame then consumes all scroll events blocking the parent page scroll if the cursor is over the iFrame. See this issue here:

https://github.com/flutter/flutter/issues/78216

The combination of this issue and the iFrame issue make embedding Flutter in web pages unnatural.

**Comment by wangying3426** [comment]
Is there any update? Our business has also encountered this problem, we hope it can be supported by flutter team as soon as possible.

**Comment by ditman** [comment]
I'm working on this feature. It is not trivial because we need to undo the assumption that flutter can take over the whole page to going to just a single element. This has implications for:

* What can flutter/can't flutter do in the containing DOM. We go from having full control of the `body` tag to "don't touch anything outside of your container"
* Event handling. Right now we subscribe to any events we want anywhere we need on the document. We won't be able to do that anymore. Events like window "resize" will need to be synthesized using MutationObservers in the container, and there's probably many many many edge cases that I haven't thought of.
* Routing. How can we "change pages" in the embedded flutter app, if it can't take control of the URL. Do we need a new programmatic Router app that injects navigation events into Flutter from JS? (unknown!)
* Others?

I wrote a "design" document about this a while back, but it probably still contains more questions than actual answers at this point:

* [Astral Projections for Flutter Web: Enabling "out-of-`body`" experiences for Flutter Web apps](https://flutter.dev/go/web-astral-projections)

The first step for this (embedding flutter through a JS API) is already release and somewhat stable. It is the default code when doing `flutter create` a Flutter Web app.

The next step of the work to **isolate the code that decides where to modify the DOM, and where to attach events** and make it configurable (we need to fall-back to the old behavior, unless users want to opt-in to the new target). Currently it's [scattered anywhere it was needed on the engine](https://github.com/search?q=%22body%22+repo%3Aflutter%2Fengine+path%3Alib%2Fweb_ui&type=code). For a more or less comprehensive (albeit probably outdated) list of the places where we subscribe to HTML events, check the appendix of the above doc :)

As usual, suggestions are welcome!

**Comment by terryl1900** [comment]
@ditman Thanks for sharing the info.

One thing I don't see mentioned in the doc is the dynamic height of the element. I want to have a webpage with `html header`, `flutter app with SingleChildScrollView with a column` and `html footer`. I'm hoping the height of the flutter element could be adjusted dynamically so the page looks cohesive to the user.

Is that something in scope?

**Comment by rpk98c** [comment]
@ditman Thanks for the update.. great to hear work is progressing on this.

As this still sounds a way off from being implemented is there a parallel project that we can help with to improve the experience of using Flutter in an iFrame? This issue makes iFrames far from ideal with Flutter:

https://github.com/flutter/flutter/issues/78216

Thanks

**Comment by ditman** [comment]
> I'm hoping the height of the flutter element could be adjusted dynamically so the page looks cohesive to the user.
> 
> Is that something in scope?

@terryl1900 yes, the flutter app will completely fill whatever container it is rendered in (even when said container resizes, because it is resizing with the window or something).

It is **unclear** if we'll be able to do the opposite: resizing an element to fit a flutter app that is wider/taller than the allocated space from the webapp (like an image expanding a DIV, for example). That needs more investigation!

**Comment by diegomors** [comment]
I would love to know a solution to do this.

**Comment by statop** [comment]
@ditman Any updates? :-)

**Comment by ditman** [comment]
I'll get on a first prototype of this right after I get a first version of this out:

https://github.com/flutter/flutter/issues/88084

(The Google Identity Services has a hard deprecation deadline, and people will need time to migrate)

**Comment by ditman** [comment]
I've written a quick **draft** design doc, check it out here:

* [HTMLElement Add-to-App](https://docs.google.com/document/d/1rFM0qmYds1JkntTruBh8eO72xbT2KoP9JdbizucAAwQ/edit), still WIP, at some point will be integrated with the flutter.dev design docs page.

**Comment by ditman** [comment]
The 🦅 has landed. Soon in a Flutter `master` channel near you! (Please, do report issues!)

**Comment by statop** [comment]
@ditman This seems to fail when a plugin uses the engine in its itializer
```
 Error: LateInitializationError: Field '_dimensionsProvider' has not been initialized.
``` 

For example, https://github.com/fluttercommunity/flutter_sms/blob/fb17e22c47e3538ffd0ace48bac81a6c78cf31d6/lib/flutter_sms_web.dart#L10

**Comment by statop** [comment]
also, is there a way to render to multiple elements? or just one

**Comment by ditman** [comment]
@statop why does the plugin need to do that? The bindings will be initialized by the engine at the right time. I've only seen that explicitly called in tests.

For now, only one element. Multiple elements is next in the [roadmap](https://github.com/flutter/flutter/issues/118481).

**Comment by statop** [comment]
I agree, it's not ideal, it seems that plugin commented it out and never released a version with that change.

Thanks for the update on the roadmap.

**Comment by ditman** [comment]
@statop thanks for giving this a shot! Indeed it's for now only in the `master` channel, but it'll eventually roll to the new stages.

**Comment by bryanrideshark** [comment]
We maintain a very (very) large Angular application with 1400+ libraries of components.

We would like to make the migration to Flutter.

If Flutter could work natively with web-components, where individual widgets (not entire apps) could be exported as different Web Components, the migration to flutter would be seamless. 

We'd need:

 - Loading the flutter engine as an ES Module
 - Ability to lazy-load the web-components exported by Flutter one at a time (as single ES Modules ideally)

If this was possible, we'd probably eventually migrating our entire application to Flutter.

**Comment by treeder** [comment]
@bryanrideshark might not want to use flutter if web components is your goal. Or if a web app is your goal in general. I'd check out https://lit.dev instead.

**Comment by louisifn** [comment]
Does anyone have a working example of this as a Flutter web project, please? I am trying to deploy but am slightly confused by the design doc. I'd just love to see what a finished index.html looks like following this change and would love to understand how it can be deployed without utilising an iframe. Many thanks

**Comment by ditman** [comment]
@louisifn here's the source code of the Demo that was shown on stage in Flutter Forward:

https://github.com/flutter/samples/tree/main/experimental/element_embedding_demo

**Comment by sammy4gh** [comment]
@ditman please do you know when this feature will be stable?

**Comment by Gene-Dana** [comment]
@louisifn check out these ! 

Flutter Web Example Landing Page
https://flutter-web-example.netlify.app/#/
https://github.com/Team-Crushing-It/seamless

Custom-Embedded Flutter Rive Animation
https://continualcare.org/
https://github.com/Team-Crushing-It/animated_logo_continual_care

Web Admin Page for Hello Wine
https://hello-wine-admin.netlify.app/#/
https://github.com/Hello-Wine-Games/hello_wine_admin

**Comment by ditman** [comment]
@sammy4gh the feature as is now will show up in the next stable release. Stable releases happen once a quarter more or less.

**Comment by rpk98c** [comment]
Hey Gene,

I notice it still steals all scroll events, just like when in an iFrame.

Is that fixable now? The stealing of scroll is probably the biggest issue
we have with Flutter in iFrames.

Thanks,

**Comment by Gene-Dana** [comment]
> @louisifn here's the source code of the Demo that was shown on stage in Flutter Forward:
> 
> https://github.com/flutter/samples/tree/main/experimental/element_embedding_demo

@rpk98c check out this !

**Comment by Gene-Dana** [comment]
> Does anyone have a working example of this as a Flutter web project, please? I am trying to deploy but am slightly confused by the design doc. I'd just love to see what a finished index.html looks like following this change and would love to understand how it can be deployed without utilising an iframe. Many thanks

Check out this: https://geneyllanes.super.site/tutorials/hosting-flutter-web-on-netlify-correctly

**Comment by louisifn** [comment]
> @louisifn here's the source code of the Demo that was shown on stage in Flutter Forward:
> 
> https://github.com/flutter/samples/tree/main/experimental/element_embedding_demo

@ditman @Gene-Dana   These are brilliant, thank you both for all your input. Fully brought my understanding into operation.


I did also attempt to stop Flutter from absorbing scroll events mentioned by @rpk98c and noticed how the element_embedding_demo does still absorb all scroll events. The only way I have been able to negate this problem so far is by catching all scroll events within the flutter embed and passing them back up to the parent. This works fine for mouse scroll events with a Listener listening to onPointerSignal. I was unable however to do this with mobile scroll events as onVerticalDragUpdates operates on all devices and interrupts other touch events - even with delta strength restrictions.

My other question is, have any of you been able to disable scroll events from an embedded flutter component or do you have any better workaround to this, as this particular solution is pretty hacky?

Many thanks.

**Comment by ditman** [comment]
@Gene-Dana yes, the way that you embed flutter doesn't change how it handles mouse events (other than attaching the listeners to slightly different parts of the DOM).

For now, we aren't handling well the case where flutter needs to scroll internally AND the external page needs to scroll.

It's a very similar problem to what an IFrameElement would have (except the browser can know when an iframe element has stopped scrolling, and can continue scrolling *outside* of it).

**Comment by rpk98c** [comment]
@ditman Without fixing the scroll issues what are the benefits of this over an iframe? I appreciate it's a little nicer but I was of the belief this would be addressing the long running complaints for Flutter absorbing scroll events when in an iFrame

https://github.com/flutter/flutter/issues/78216

**Comment by rpk98c** [comment]
> For now, we aren't handling well the case where flutter needs to scroll internally AND the external page needs to scroll.

I would argue it's a bug even if the Flutter app doesn't need to scroll and only the web page needs to scroll. As soon as the mouse goes over the Flutter element you can no longer scroll the web page, making the whole site feel broken. For example, hover your mouse over a Flutter element (which needs on scrolling) and then use your scroll wheel to scroll the web page. The page doesn't scroll making the whole site feel broken as soon as a Flutter element exists on the page.

**Comment by ditman** [comment]
> I would argue it's a bug even if the Flutter app doesn't need to scroll and only the web page needs to scroll.

@rpk98c No need to argue, it's a bug. It's also not trivial to fix.

My hunch is that we'll need the framework to tell the engine that the user is hovering over something that may/may not be scrollable of an app, and then use that on the engine to turn on/off the scroll event handler, but I don't even know how feasible my solution is (or how performant).

While I was experimenting with the new embedding, I tried letting 30% of the scroll events unhandled [around here](https://github.com/flutter/engine/blob/main/lib/web_ui/lib/src/engine/pointer_binding.dart#L487-L506), I think, and scroll would "work" (only at 30% of the normal rate, of course), so I guess that's a clue.

I'm not an expert in mouse bindings, so take my opinion with a bunch of grains of salt.

**Comment by bryanrideshark** [comment]
The whole point of using web components in flutter, is to allow the strangler vine refactoring pattern to be used.

You can't shift a project with 1000 components to Flutter all at once. But if you could convert a single web component at a time, then you could do it.

We'd love to adopt flutter - but we're not going to take our product offline for two years to do a complete rewrite. Nor is any other sensible SAAS platform.

**Comment by Gene-Dana** [comment]
> but we're not going to take our product offline for two years to do a complete rewrite.

I'm not sure I understand your problem right now. How are embeddable widgets not a valid solution?

**Comment by Gene-Dana** [comment]
> Without fixing the scroll issues what are the benefits of this over an iframe? I appreciate it's a little nicer but I was of the belief this would be addressing the long running complaints for Flutter absorbing scroll events when in an iFrame

Check out this !

https://github.com/flutter/packages/tree/main/packages/pointer_interceptor

From this comment
https://github.com/flutter/flutter/issues/72273#issuecomment-747728199

**Comment by ditman** [comment]
> _(Replying to [this comment](https://github.com/flutter/flutter/issues/32329#issuecomment-1434787951))_

@bryanrideshark you're not the first person to ask for those features, (at least another person asked for the same in our Discord.)

I have written a small doc on how I see Flutter realistically inter-operating with ES Modules:

* https://flutter.dev/go/web-declarative-bootstrap

I think that where our communication breaks down is on the definition of "Widget" or component.

If you're suggesting that all Flutter widgets are exposed as individual ES Modules; for example, the: [`Scaffold` widget](https://api.flutter.dev/flutter/material/Scaffold-class.html) in a way that you can mix-and-match with your app (for example: make a Flutter `Scaffold` that has a `body` made of Angular stuff: I don't think this is doable! Flutter widgets do *not* map to HTML elements/Web components in the same way other html-based frameworks do.

If you want to replace some part of your app by a Flutter re-implementation of a widget that you have running in mobile (and you want to look and feel the same in the web), you should be able to. In this case I'm imagining a web component that has some complex behavior within it.

Anyway, let me /cc @kevmoo so he's aware of your use case, as I said, you're not the one to request this!

**Comment by ditman** [comment]
@Gene-Dana I don't think the pointer interceptor is going to be enough (I'm assuming that @rpk98c wants their Flutter app to be somewhat interactive :))

My current thinking is that the framework needs to tell the engine "the user is hovering over something: scrollable to top/scrollable to bottom/scrollable to both/not scrollable", and then the engine use that information to handle/ignore scroll events coming from the browser.

It's not going to feel **100% native** but at least, we wouldn't be trapping people attempting to scroll OUT of a Flutter app in a tall page :)

**Comment by rpk98c** [comment]
@ditman You're spot on. Something so we can interact with the Flutter app but inside flutter decide when we're handing vertical scroll events and if we're not let the page handle them. It would be amazing to just have Flutter apps where we said no to vertical scrolling and allowed all other interaction, that would be a big win. At least then we could use Flutter to embed say a calculator widget and not block all page scrolling if hovered over it. 

@Gene-Dana Thanks - we do use the pointer-interceptor extensively. It's very useful when embedding an iFrame in a native app and you want to have Flutter widgets over the top. E.g. a FAB. Great package.

**Comment by bb-renittojose** [comment]
**Making a Dart function callable from JavaScript**

I'm new to the web platform. I'm trying to integrate a flutter module into a PWA application. I would like to access one Dart function from PWA using JS. Used the following official package to call JavaScript APIs from Dart code, or vice versa.

[flutter package](https://lnkd.in/g4_cSTTn)

following is the sample JS used for accessing a sample dart function

```
<script src="./main.dart.js"></script>
<script type="text/javascript">
function callMethodFromFlutter() {
window.functionName();
}
</script>
```

but getting the following errors with window and without window object

_window.functionName is not a function
functionName is not defined_

Any idea what’s wrong here? or any other alternative way for communication between a flutter module and PWA just like platform channels used for android/iOS.

@ditman @Gene-Dana
