### ISSUE TITLE
error on pod install with Vibration plugin

### ISSUE THREAD

**Issue by AndreaMiotto** [flutter/flutter#32327]
Installing the application with the Vibration plugin gives me this error:

 Downloading dependencies
    -> Installing Flutter (1.0.0)
    -> Installing vibrate (0.0.1)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:
    - `vibrate` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/xcode/target_validator.rb:115:in `verify_swift_pods_swift_version'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:459:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:138:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command/install.rb:48:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'
Error running pod install
Exited (sigterm)

**Comment by AndreaMiotto** [comment]
It was a project configuration problem. 
It was not supporting swift. 
I've delete android and ios folder, than i've used the command:

`flutter create -i swift -a kotlin projectName`

And now it works.

**Comment by YAPPDEF** [comment]
Having the same issue and `pod update` didn't help.
Creating a new project should not be the way to solve this issue. I have an existing (large) project.

@Flutter team, any suggestions how to solve this properly? Maybe to apply changed configurations to an existing projects?

**Comment by willvlad** [comment]
Any solutions? Having the same problem...
