### ISSUE TITLE
[web] Embedding non-flutter view (for example <video>) 

### ISSUE THREAD

**Issue by rostopira** [flutter/flutter#32326]
## Use case

Currently there is no way to embed html video or canvas in flutter_web

## Proposal

This feature should the same logic as `UiKitView` and `PlatformView`, as well as support for creating and managing it in dart directly (via `dart:html` package)

**Comment by lejard-h** [comment]
Something like an `HtmlContainer` would be great with the same properties of the existing `Container` but wrapping an html element

```dart
HtmlContainer(
  child: html.DivElement(), 
  padding: padding: EdgeInsets.all(8),
)
```

**Comment by sgong-pdftron** [comment]
May I ask if there is any timeline? Thanks!

**Comment by rostopira** [comment]
Looks like, it's coming soon ( #37791 #37794 #37795 )

**Comment by ferhatb** [comment]
Please see PlatformView sample at https://github.com/flutter/flutter_web/tree/master/examples/html_platform_view
