### ISSUE TITLE
The behavior of Canvas.skew does not match the documentation

### ISSUE THREAD

**Issue by pents90** [flutter/flutter#32323]
The documentation for [Canvas.skew](https://docs.flutter.io/flutter/dart-ui/Canvas/skew.html) states that the units for the `sx` and `sy` parameters are in radians. However, that is incorrect, they are actually in raw "rise over run" ratio units. To see this, try a vertical skew of π/4 radians (45°). This should turn a horizontal line into a 45° diagonal line. You will see that it doesn't. However, if you instead try a vertical skew of tan(π/4), then you see the desired result.

**Comment by dnfield** [comment]
This is unfortunate.  I believe the goal here was to consistently do things in terms of radians, but it's probably too late now to change the behavior.  We'll have to update the docs.
