### ISSUE TITLE
Include flutter.jar in pre-built engine artifacts

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#3233]
We'll need it for the gradle-based workflow.

**Comment by eseidelGoogle** [comment]
https://codereview.chromium.org/1870043004/

**Comment by eseidelGoogle** [comment]
Now we just need to add an entry to flutters cache to have it pulled down
and update the gradle plugin to only need a flutter.src and not a
flutter.jar and to just find the jar in the cache.

**Comment by abarth** [comment]
Jason did this.
