### ISSUE TITLE
iOS create archive broken in new projects

### ISSUE THREAD

**Issue by pzahc** [flutter/flutter#32336]
Following: https://flutter.dev/docs/deployment/ios

The flow for deploying an app to testFlight/App Store is **broken "right out the box"** when creating an archive if you import a plugin. 

Steps to Reproduce Errors:
1) Flutter create _"app name"_
2) cd _"app name"_; flutter run
(Result: app build fine)
3) open pubspec.yaml
4) Under dependencies add line: "camera ^0.5.0" 
5) flutter packages get; flutter run
(Result: app build fine)
6) open ios/Runner.xcodeproj
7) Set your "Team" and "Bundle Identifier" under the general setting for Runner Target
8) flutter build ios
(Result: build succeeds)
9) (in Xcode ) Select Product > Scheme > Runner.
10) (in Xcode ) Select Product > Destination > Generic iOS Device.

11) Create Archive

**Result: Failure 1** 
Multiple commands produce '_"local path bla bla"_Flutter.framework':
1) Target 'Runner' has copy command from '<repo path>/ios/Flutter/Flutter.framework' to '_"os user directory"_/Library/Developer/Xcode/DerivedData/Runner-djddhrjsjqzwpvfgxkxuuxhdsntj/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Runner.app/Frameworks/Flutter.framework'
2) That command depends on command in Target 'Runner': script phase “[CP] Embed Pods Frameworks”

**Fix**
https://github.com/flutter/flutter/issues/20685

Try again: 
12)Create Archive

**Result: Failure 2** 
ld: warning: directory not found for option '-L/_"os user directory"_/Library/Developer/Xcode/DerivedData/Runner-djddhrjsjqzwpvfgxkxuuxhdsntj/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/camera'
ld: library not found for -lcamera
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**If you skip adding the plugin (Steps 3-5) the Archive build just fine.**

Solution: via https://github.com/flutter/flutter/issues/19149
Add Pods/Pods.xcodeproj into Runner/Pods in Xcode.
Should be happening automatically when flutter generates the profile?

**Comment by jmagman** [comment]
It should be in the Runner.xcworkspace, but it looks like you opened Runner.xcodeproj.

**Comment by jmagman** [comment]
Can you confirm with this all works out of the box (on top of the https://github.com/flutter/flutter/issues/20685 fix, as you already figured out)?

**Comment by pzahc** [comment]
Confirmed: Working fine
Runner.xcodeproj. -> Runner.xcworkspace was my issue. Regular old user error... 
Thanks for looking into it @jmagman.
