### ISSUE TITLE
[web]: Web Project Create Problem

### ISSUE THREAD

**Issue by samrat19** [flutter/flutter#32333]
I am using Flutter from September 2018. I have all set up ready in environment variable and path also. but when I am writing    

Flutter: New Web Project

it is giving this error:

Flutter: : The term 'Flutter:' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of
 the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Flutter: New Web Project
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Flutter::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

help me to solve the problem

**Comment by kevmoo** [comment]
You need to be running the latest Flutter SDK – 1.5!

**Comment by samrat19** [comment]
I am running latest flutter version. May be  1.5.4 hotfix 2

**Comment by kevmoo** [comment]
Okay! What tool are you running where you seen `Flutter: New Web Project`

**Comment by natebosch** [comment]
Looks like you're trying to run that in powershell - the "Flutter: New Web Project" referenced here is a vscode thing.

Currently the `flutter` command line tool does not have support for creating a web project - you'll want to look at either using that command through vscode or starting a Dart project (not flutter project) with intelliJ.

https://github.com/flutter/flutter_web#tools-support-for-flutter-web-development

**Comment by samrat19** [comment]
well, I was using VS Code and that command in the terminal was making a
problem then I followed the latest video from r_flutterdev in twitter and
my issue gone. pressed 'f1' and I got the option to make a Flutter Web
Project.

Thank you for your kind response
