### ISSUE TITLE
how can get marker icon from the internet in flutter google map

### ISSUE THREAD

**Issue by Seven7up** [flutter/flutter#32334]
I have some icon on the internet, and I want to set those icons for flutter google marker, how can I do that?

One way is that get the image from the internet and convert it to byte data and Uint8List finally set it on the marker with BitmapDescriptor.fromBytes

I do that but not work

someone can help?

**Comment by KirolousNashaat** [comment]
That question should be on stackoverflow not here.. and why would you put performance tag on it anyway!

**Comment by TahaTesser** [comment]
Hi @Seven7up 
Please take a look [this](https://medium.com/coletiv-stories/use-network-images-as-marker-icons-on-flutter-google-maps-d40638f1bd76)
Thank you
