### ISSUE TITLE
TextField's Text Selection Buttons are Disappeared when text starts with Chinese char

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#32332]
## Flutter version:

Flutter (Channel dev, v1.5.8, on Mac OS X 10.13.6 17G4015, locale en-CN)

## Code

Just any simple textfield will do:

```dart
       TextField(
          decoration: InputDecoration(filled: true, fillColor: Colors.white, border: InputBorder.none),
          maxLines: 5,
        ),
```

### The Unexpected Screenshot With Chinese Chars

![flutter_04](https://user-images.githubusercontent.com/1555508/57394690-b3918f80-71f8-11e9-821f-0cbf9c28b8d5.png)

### The Working Screenshot With En Chars

![flutter_03](https://user-images.githubusercontent.com/1555508/57394659-9d83cf00-71f8-11e9-8a36-2a6ce35bc72f.png)

### The Screencast (Gif file)

![video](https://user-images.githubusercontent.com/1555508/57398623-0e7bb480-7202-11e9-936b-1d6473213d93.gif)

## Issue Description

From what you can see from the above screenshot and screencast, TextField's text selection start and end buttons are disappeared when text starts with Chinese characters, but working fine when text start with English characters. 

Thank you very much for your help.

**Comment by jason-simmons** [comment]
This started with https://github.com/flutter/flutter/commit/88a477cacead093d18be0dcb4ea72e9976aeb0a7

The Chinese font has a higher ascent than the default font, and that causes the Chinese character's bounds to extend beyond the top of the viewport rectangle.  As a result, the framework thinks that the text is partially offscreen and hides the selection handle.

@GaryQian

**Comment by sgon00** [comment]
@jason-simmons Thank you very much for the quick reply and fix. 
(Btw, I am not sure if it's proper to say thank you in a comment. But really thank you very much for taking care of this issue.)

**Comment by justinmc** [comment]
I fixed a similar problem here by adding some fuzziness to the check: https://github.com/flutter/flutter/pull/31332

That doesn't fix this problem, though.  The "slop" fuzziness factor used in that PR is 0.5, but for me I see Chinese characters extending to -1.8.  That sounds like it's beyond a fuzzy check and we need to rethink this.

Should text extend above the input?

Maybe related: https://github.com/flutter/flutter/issues/32158

**Comment by TahaTesser** [comment]
Hi @sgon00 
This issue isn't reproducible on latest `dev` channel

![flutter_03](https://user-images.githubusercontent.com/48603081/83873080-bd195e00-a750-11ea-9be2-703c3b970def.png)


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.19.0-3.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 6135091de9 (3 days ago), 2020-06-01 17:17:03 -0700
    • Engine revision e39301f23f
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.97

• No issues found!
``` 

</details> 


Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
