### ISSUE TITLE
Mac desktop build 

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#32341]
I'm trying to build my app for Mac OSX but it doesn't work :( 

first there is an error in script `macos_build_flutter_assets.sh` that give `framework_name command not found` because line 43 need to be `framework_name="FlutterMacOS.framework"` without space between equal

After that I'm getting weird error on package flutter_hook or flare_flutter:

```
[        ] file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.3.0/lib/src/framework.dart:328:71: Error: The argument type 'String'
can't be assigned to the parameter type 'DiagnosticsNode'.
[        ]  - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart'
('file:///Users/jaumard/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
[        ] Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
[        ]             context: 'while calling `didBuild` on ${hook.runtimeType}',
[        ]                                                                       ^
[   +1 ms] file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.3.0/lib/src/framework.dart:348:59: Error: The argument type 'String'
can't be assigned to the parameter type 'DiagnosticsNode'.
[        ]  - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart'
('file:///Users/jaumard/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
[        ] Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
[        ]             context: 'while disposing ${hook.runtimeType}',
[        ]                                                           ^
[  +41 ms] file:///Users/jaumard/.pub-cache/hosted/pub.dartlang.org/flare_flutter-1.5.0/lib/flare.dart:1023:18: Error: The argument type 'Int32List' can't
be assigned to the parameter type 'Uint16List'.
[        ]  - 'Int32List' is from 'dart:typed_data'.
[        ]  - 'Uint16List' is from 'dart:typed_data'.
[        ] Try changing the type of the parameter, or casting the argument to 'Uint16List'.
[        ]         indices: _indices, textureCoordinates: _uvBuffer);
[        ]                  ^

```
And those once I don't know how to get rid of them.

**Comment by stuartmorgan** [comment]
> first there is an error in script macos_build_flutter_assets.sh

This script no longer exists, which suggests you are not using the latest Flutter master. Please provide details about your configuration and the commands you used, including:
- Your flutter version
- How exactly you set up your project to build for macOS (including repository and hash if you copied a `macos` folder from somewhere)
- What directions you were following to build

**Comment by jaumard** [comment]
Hello @stuartmorgan 

Here is my setup:
```
[✓] Flutter (Channel master, v1.5.9-pre.182, on Mac OS X 10.14.4 18E226, locale fr-FR)
    • Flutter version 1.5.9-pre.182 at /Users/jaumard/flutter
    • Framework revision 41d26b96e3 (12 hours ago), 2019-05-08 14:08:39 -0400
    • Engine revision 0a2d18da95
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 f80f0bfcfd)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jaumard/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 35.2.3
    • Dart plugin version 191.7019

[✓] Connected device (1 available)
    • macOS • macOS • darwin-x64 • Mac OS X 10.14.4 18E226

• No issues found!
```
I just did `flutter channel master && flutter upgrade` so I'm expecting to have the latest master right ?

To setup the project I was using the https://github.com/google/flutter-desktop-embedding (commit 763c4609c87a729afbff5c2517208763d354ddad) steps, so I copy the "macOS" folder from the example project to mine, and run `flutter run` 

Then I so the sh script failing so I dig into it and found the reported errors above.

**Comment by stuartmorgan** [comment]
My mistake; I though that was old name of the script and was looking in the wrong place to check. I'm not sure why we hadn't hit that issue with the variable assignment, but I'll send a PR for that now.

As for the rest, given that they are Dart-level errors in third-party packages it seems very unlikely that they are desktop-related. Are those versions of those packages compatible with Flutter master? Have you successfully built your project on master for iOS or Android?

**Comment by jaumard** [comment]
You're right @stuartmorgan I was focus on desktop that I forget to try to run it for mobile on master first ^^ those packages are not compatible yet with master, I removed them to try and the app is now launching but doesn't show anything because of this error ` macos was not recognized as a target platform. Consider updating the list of TargetPlatforms to` is there still something I forget to do ?

**Comment by jaumard** [comment]
Ok by adding `debugDefaultTargetPlatformOverride = TargetPlatform.fuchsia;` at the beginning of my main function it's all good ^^
