### ISSUE TITLE
Hello_Android Apk is too large(19M)

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#3234]
I found the Hello_Android apk(19M), and the flutter.jar(22M)  are too large

**Comment by sethladd** [comment]
Thanks for the feedback! Curious, did you enable `uses-material-design: true` in your flutter.yaml ? IIR, that brings in a lot of fonts.

**Comment by abarth** [comment]
I suspect we're including two copies of the engine or something silly like that.

**Comment by eseidelGoogle** [comment]
FYI @jason-simmons.  I have it on my todo list to set up tracking of binary sizes for @yjbanov's new graphs.  This is another binary size we should track.  I suspect as @abarth says we're just doing something silly.

**Comment by jason-simmons** [comment]
The issue is that the files in flutter.jar and the large files (libsky_shell.so, icuctl.dat) in the Gradle-built APK are being stored without compression.

**Comment by eseidelGoogle** [comment]
flutter.jar is now 9M (9,180k) built android_Release on Linux using 9cb0aa1ac9aedcca80c1c4d5d4ed8a271a632b30
