### ISSUE TITLE
No clear direction on how to order final fields in a class

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#32348]
I'm currently building out a new widget and could not find much from the style guide on how to order `final` fields relative to each other. The style guide mentions that `the methods, properties, and other members of a class should be in an order that will help readers understand how the class works.` 

Does this mean that we arbitrarily decide what is considered logical? I've noticed certain patterns like keys always being the first parameter, properties of the same type being clustered together, and that fields are typically ordered the same as parameter lists. Maybe there could be certain recommendations in the style guide to get people started on how to think about ordering them.

**Comment by goderbauer** [comment]
> the methods, properties, and other members of a class should be in an order that will help readers understand how the class works.

This is the guidance. Beyond that, you're free to do whatever makes sense.
