### ISSUE TITLE
Implement edge scrolling for text selection in Text/TextField

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#32344]
In the gif I attempted to extend the text selection beyond the word "wondering" (the first visible word) but wasn't able to. The text field should scroll upwards to allow me to further expand the selected area.

![edgescrolling](https://user-images.githubusercontent.com/31859944/57407819-f3288f00-7198-11e9-872e-d4265e1f605e.gif)

**Comment by truthmast** [comment]
Any plans for a fix on this? We have some users requesting this feature.

**Comment by LongCatIsLooong** [comment]
@truthmast unfortunately this doesn't have a very high priority at the moment. See https://github.com/flutter/flutter/wiki/Issue-hygiene#prioritization.

**Comment by LongCatIsLooong** [comment]
Looks like this has already been implemented on master. Closing.

**Comment by Piinks** [comment]
I am re-opening this as it is currently supported on mobile, but lacks support on web and desktop.
