### ISSUE TITLE
[web]: The term 'webdev' is not recognized

### ISSUE THREAD

**Issue by kavin014** [flutter/flutter#32349]
Couldn't run **webdev** serve command,

Error displays in terminal,
webdev : The term 'webdev' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path 
was included, verify that the path is correct and try again.
At line:1 char:1
+ webdev serve
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (webdev:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by grouma** [comment]
Looks like you need to install `webdev`. Instructions are here:
https://github.com/flutter/flutter_web#install-the-flutter_web-build-tools

If you run into further issues please reopen.

**Comment by kavin014** [comment]
@grouma Tried with that still having an issue,

'dart' is not recognized as an internal or external command,
operable program or batch file.
'pub' is not recognized as an internal or external command,
operable program or batch file.

**Comment by grouma** [comment]
Do you have the flutter SDK installed?

Instructions are located here:
https://flutter.dev/docs/get-started/install

Looks like you are running windows so more specifically here:
https://flutter.dev/docs/get-started/install/windows

Make sure you update your path. You'll likely need to relaunch your instance of cmd / powershell.

**Comment by kavin014** [comment]
@grouma I found the issue **dart** Path is not set in environment variables

**Comment by chanon-hongthong** [comment]
i have issue same you, would you show how to set your environment please.

**Comment by chanon-hongthong** [comment]
> i have issue same you, would you show how to set your environment please.

**Comment by grouma** [comment]
What is the value of your `path` environment variable?

Instructions on how to update here:
https://flutter.dev/docs/get-started/install/windows#update-your-path

**Comment by chanon-hongthong** [comment]
Thank you @grouma It's wrong myself (i add environment not restart window command but i restart window command it to work)

Thank you so much.
Chanon Hongthong

**Comment by grouma** [comment]
No troubles. I've done the same in the past. Enjoy the preview!

**Comment by UtkarshChandel** [comment]
> i have issue same you, would you show how to set your environment please.
> 
> **below is my set environment.**
> D:\Project\flutter\bin
> D:\Project\flutter.pub-cache\bin
> D:\Project\flutter\bin\cache\dart-sdk\bin

Set your environment path variables for both the user level and system level path variable
