### ISSUE TITLE
[web] Support embedding Flutter in an existing Web page

### ISSUE THREAD

**Issue by curiouscod3** [flutter/flutter#32351]
I am using Angular(not Angular Dart) as a main Web-dev framework.
I've researched new Flutter Web library and examples(samples) codes today.

To convert flutter Dart to the web bundle version, It is required to put the main.dart.js. Looks like this is a main runtime component to render compiled Flutter/Dart Javascript version.
` <script defer src="main.dart.js" type="application/javascript"></script>`

**Why do We Need Flutter Web version as a webComponent?**
This is Because Flutter cannot solve all web-based problems and It should take advantage of a huge Javascript ecosystem & Web components.

**I think the best way is to utilize the converted javascript bundle as a Web-component.** 
Desktop Web  apps need much more sophisticated and complex design and lots of plugins and javascript components.
Flutter even doesn't offer 3D like WebGL/WebGPU. Flutter has a limited WYSIWYG design support as CSS/SASS does for the Web as well.

However, Flutter has a great mobile Widget UI system. It can be gracefully utilized as a webcomponent widget for both Web and MobileWeb as I mentioned that Web is by far sophisticated and complex to design. 

Thus, I think it would be great that it can be embedded as a web-component to work within the other web framework like this. `<my-flutter-widget></my-flutter-widget>`

**Comment by startupgurukul** [comment]
Being able to leverage existing JS libraries would be huge and make flutter, the holy grail of development

**Comment by curiouscod3** [comment]
> Being able to leverage existing JS libraries would be huge and make flutter, the holy grail of development
> 
> It would also be nice to see being able to invoke js from with dart/flutter project

Well,, I am not sure..  It would not be so difficult that Dart2JS/Flutter teams  allow to be invoked the compiled javascript bundle as a webcomponent within other giant webframework like Angular.

**Comment by yjbanov** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/32329

**Comment by startupgurukul** [comment]
creeated https://github.com/flutter/flutter/issues/32443 for jsinterop
