### ISSUE TITLE
[webview_flutter] Video keeps playing on new route / app inactive

### ISSUE THREAD

**Issue by daohoangson** [flutter/flutter#32363]
## Steps to Reproduce (scenario 1 of 2)

(Demo app code at the bottom)

1. From Screen0, open Screen1
2. In Screen1, press play on the video
3. Still in Screen1, open Screen2

Expect: audio from video stops
Actual: it kept playing

This only happens in Android because iOS plays the video fullscreen and user can't navigate around while playing something. I think this is an issue with `PlatformView` in general, not just limited to WebView. 

## Steps to Reproduce (scenario 2 of 2)

1. From Screen0, open Screen1
2. In Screen1, press play on the video
3. Switch app

Expect: audio from video stops
Actual: it kept playing

## Logs

```
[✓] Flutter (Channel master, v1.5.9-pre.168, on Mac OS X 10.14.4 18E226, locale
    en-VN)
    • Flutter version 1.5.9-pre.168 at /Users/xxx/repos/flutter
    • Framework revision 2f1e7cf662 (2 days ago), 2019-05-07 08:33:22 -0700
    • Engine revision ee6412a74d
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 dbe80f3397)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Users/xxx/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/xxx/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android
      Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

• No issues found!
```

## Demo code

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: Screen0());
}

class Screen0 extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('Screen 0')),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              RaisedButton(
                child: Text('Screen 1'),
                onPressed: () => Navigator.of(context).push(
                      MaterialPageRoute(builder: (_) => Screen1()),
                    ),
              ),
            ],
          ),
        ),
      );
}

class Screen1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('Screen 1')),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              AspectRatio(
                aspectRatio: 560 / 315,
                child: WebView(
                  initialUrl: 'https://www.youtube.com/embed/fq4N0hgOWzU',
                  javascriptMode: JavascriptMode.unrestricted,
                ),
              ),
              RaisedButton(
                child: Text('Screen 2'),
                onPressed: () => Navigator.of(context).push(
                      MaterialPageRoute(builder: (_) => Screen2()),
                    ),
              ),
            ],
          ),
        ),
      );
}

class Screen2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('Screen 2')),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[Text('This is screen 2')],
          ),
        ),
      );
}
```

**Comment by daohoangson** [comment]
As a workaround, I have to reload the WebView on widget `deactivate` and `AppLifecycleState.paused`. This stops the annoying background audio issue but not the best user experience.

```dart

class Screen1 extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _Screen1State();
}

class _Screen1State extends State<Screen1> with WidgetsBindingObserver {
  WebViewController _controller;

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('Screen 1 (workaround)')),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              AspectRatio(
                aspectRatio: 560 / 315,
                child: WebView(
                  initialUrl: 'https://www.youtube.com/embed/fq4N0hgOWzU',
                  javascriptMode: JavascriptMode.unrestricted,
                  onWebViewCreated: (controller) => _controller = controller,
                ),
              ),
              RaisedButton(
                child: Text('Screen 2'),
                onPressed: () => Navigator.of(context).push(
                      MaterialPageRoute(builder: (_) => Screen2()),
                    ),
              ),
            ],
          ),
        ),
      );

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void deactivate() {
    super.deactivate();
    _controller?.reload();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.paused) {
      _controller?.reload();
    }
  }
}
```

**Comment by daohoangson** [comment]
Please @amirh and @iskakaushik, any input regarding this issue?

**Comment by woutervanwijk** [comment]
I see the same behaviour. As a workaround, I did this (Stateful widget): 

  @override
  void dispose() {
    //These two steps are needed to stop audio and video
    _webViewController.loadUrl('about:blank');
    setState(() {});
    // TODO: implement dispose
    super.dispose();
  }

This works. But I get an exception which tells me to report a bug for this:


════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4138 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      Element.markNeedsBuild 
package:flutter/…/widgets/framework.dart:4138
#3      State.setState 
package:flutter/…/widgets/framework.dart:1253
#4      _ArticleDetailPageState.dispose 
package:fiper/…/article/article_page.dart:36
#5      StatefulElement.unmount 
package:flutter/…/widgets/framework.dart:4729
#6      _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1922
...

**Comment by vlowe85** [comment]
I have also had to use the workaround posted by @woutervanwijk as my webview contains a vimeo video which auto plays. If i close the webview the video audio continues to play with no way of stopping it. 

The reload workaround posted by @dacaiguoguogmail will not work if the media in the webview will autoplay.

**Comment by woutervanwijk** [comment]
Btw, the sound continues to play, even while I completely reload the whole app. So the webview stays hidden and active in the background in a way

**Comment by marcinOz** [comment]
For me reload or anything that will interrupt Vimeo player in WebView is not working so only workaround I found for that (besides going deep in bridges) is adding this in Activity 
`@Override
protected void onPause() {
    super.onPause();
    ((AudioManager)getSystemService(
            Context.AUDIO_SERVICE)).requestAudioFocus(
                    new OnAudioFocusChangeListener() {
                        @Override
                        public void onAudioFocusChange(int focusChange) {}
                    }, AudioManager.STREAM_MUSIC, 
                    AudioManager.AUDIOFOCUS_GAIN_TRANSIENT);
}`
Here is fix (without depricated) https://stackoverflow.com/questions/56968138/how-to-pause-a-webview-in-flutter

**Comment by darshankawar** [comment]
The issue is reproducible on latest `dev channel (1.20.0-0.0.pre)` and with latest version of `webview_flutter`.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.20.0-0.0.pre at /Users/deeptibelsare/Documents/Fluttersdk/flutter
    • Framework revision d9653445f4 (8 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by marcjulian** [comment]
I also noticed on iOS that the WKWebView instances are still active and accessible via Safari using `webview_flutter: 0.3.22+1`.

To reproduce follow the steps

1. Use the code example below and make sure `debuggingEnabled` is enabled for the webview and run the app on iOS
2. Launch Safari and verify that you can see your device in the developer tab.
3. Navigate to Screen 1 and back to Screen 0, repeat this a few times 
4. Verify that the unmounted WKWebView instances are still active and accessible via Safari, see screenshot

![Screenshot 2020-06-26 at 15 37 44](https://user-images.githubusercontent.com/8985933/85864513-e9ab1d80-b7c4-11ea-98df-c62aac9a3c31.png)

How can the WKWebView correctly be unmounted when the page of the webview is disposed?

<details>
  <summary>Code Example</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: Screen0());
}

class Screen0 extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('Screen 0')),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              RaisedButton(
                child: Text('Screen 1'),
                onPressed: () => Navigator.of(context).push(
                  MaterialPageRoute(builder: (_) => Screen1()),
                ),
              ),
            ],
          ),
        ),
      );
}

class Screen1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('Screen 1')),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              AspectRatio(
                aspectRatio: 560 / 315,
                child: WebView(
                  debuggingEnabled: true,
                  initialUrl: 'https://www.youtube.com/embed/fq4N0hgOWzU',
                  javascriptMode: JavascriptMode.unrestricted,
                ),
              ),
              RaisedButton(
                child: Text('Screen 2'),
                onPressed: () => Navigator.of(context).push(
                  MaterialPageRoute(builder: (_) => Screen2()),
                ),
              ),
            ],
          ),
        ),
      );
}

class Screen2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: Text('Screen 2')),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[Text('This is screen 2')],
          ),
        ),
      );
}
```

</details>

**Comment by robbysoerya** [comment]
You can use javascript code to pause video

```
@override
  void didChangeAppLifecycleState(AppLifecycleState state) async {
    if (state == AppLifecycleState.paused && Platform.isAndroid) {
      _controller.future.then(
        (controller) => controller.evaluateJavascript(
            'var video = document.querySelector("video");video.pause();'),
        onError: (error) => debugPrint(error.toString()),
      );
    }
  }
```

**Comment by stuartmorgan** [comment]
@marcjulian Could you file a new issue for your case? The steps there are somewhat different, and it's on iOS, so it may not be exactly the same issue.

**Comment by stuartmorgan** [comment]
@daohoangson Can you elaborate for the initial descriptions why you expect the video to stop? If the web view is still active in the route, or in the app, why would it stop playing?

**Comment by daohoangson** [comment]
> @daohoangson Can you elaborate for the initial descriptions why you expect the video to stop? If the web view is still active in the route, or in the app, why would it stop playing?

It's expected that way I think. It's quite a surprise to receive a Google Play review regarding YouTube playing in background.

**Comment by stuartmorgan** [comment]
@daohoangson Sorry, I wasn't clear in my question. I understand why you might want your app to stop playing something when pushing a new route or switching apps; I'm asking why you expect this behavior to be fundamental to the web view itself. If the widget containing the web view still exists, why would the web view automatically stop playing without the developer doing so deliberately?

**Comment by daohoangson** [comment]
Your question made me wonder so I tried with a native Android app and the webview is indeed kept playing there. If there is no objection then I guess this issue can be closed now.
