### ISSUE TITLE
Is there a socket.io client library written using flutter's websocket? 

### ISSUE THREAD

**Issue by 2015-lizaiyang** [flutter/flutter#32378]
Is there a socket. IO client library written using flutter's websocket? I tried using the flutter_socket_io plug-in and had a number of problems that were caused by platform environment configuration issues.

**Comment by calvinmuller** [comment]
Have you tried? 
https://pub.dev/packages/socket_io_client I use it with no problems at all.

**Comment by 2015-lizaiyang** [comment]
To me is invalid.
My back-end USES nodejs+eggjs+socket.io, socket.io-client-dart can't connect

**Comment by alby97** [comment]
> Have you tried?
> https://pub.dev/packages/socket_io_client I use it with no problems at all.

The docs didn't give enough explainations to me, can you tell me how do you use that? Thanks.

**Comment by theochampion** [comment]
Do you guys know if any of those library support socket io extraHeaders?

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.

**Comment by OussamaCeltica** [comment]
> Have you tried?
> https://pub.dev/packages/socket_io_client I use it with no problems at all.

i tried but no error and no success , i dont know why !!
