### ISSUE TITLE
Dropdown menu constructor asserts unexpectedly (?)

### ISSUE THREAD

**Issue by nazi147** [flutter/flutter#32371]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

## Original issue title:
```
Failed assertion: line 560 pos 15: 'items == null || I/flutter ( 4941): items.isEmpty || value == null || items.where((DropdownMenuItem<T> item) => item.value == I/flutter ( 4941): value).length == 1': is not true.
```

**Comment by HansMuller** [comment]
Please fill in the issue's description (there are many fields to fill out if you edit it).

It looks like a DropdownButton was created with an invalid list of items.
