### ISSUE TITLE
Keyboard opens and shuts itself on focusing Textformfield.

### ISSUE THREAD

**Issue by shikha1992** [flutter/flutter#32375]
Hi, I am facing this strange issue. I have 2 different forms and they are almost same(functionality is same). One works fine but in other form, if any of TextformField is focused, keyboard opens and shuts itself. Both forms are called from different screen.
I am calling form(in which i am facing issue) using below method -
SingleChildScrollView(
child: GestureDetector(
onTap: (){
Navigator.push(
context,
MaterialPageRoute(builder: (context) => FormEnvRegularToilet()),
);
},
child: Container(
height: 70.0,
color: Color(0xffff7C10),
child: ListTile(
trailing: Image.asset('assets/forward.png'),
title: Text('Drop Regular Portable Toilet',style: TextStyle(color: Colors.white
, fontSize: 20.0,),textAlign: TextAlign.start,),
),
),
),
),

I tried to call the other form(in which keyboard is okay) from same function, then again this issue arises. I do not understand is whether issue is inside the form or is it in function that is calling form function. I tries to add static in "key" value too. It did not work. All controllers are different for each field.

**Comment by HansMuller** [comment]
If you could provide the output from `flutter doctor` and a small complete app that demos the problem (many developers use https://gist.github.com to share code like this), we'll be happy to look into it.

This sounds like a problem that was fixed by https://github.com/flutter/flutter/pull/27365; the fix has only recently landed in a stable release.

**Comment by shikha1992** [comment]
Thanks for reference. I found out the issue. The class which i used to call form had following code - 

final page = ModalRoute.of(context);
    page.didPush().then((x) {
      SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
        systemNavigationBarColor: Colors.red,
        statusBarColor: Colors.red,
      ));
    });
This caused issue. I removed this from my class.
