### ISSUE TITLE
[firebase_messaging] regression on Android: messages not delivered when app is terminated on a known good device (e.g. Pixel); this works on a normal Android app so am trying to figure out why Flutter has an issue in getting it to work

### ISSUE THREAD

**Issue by gerryhigh** [flutter/flutter#32372]
I have a "normal" Android app written in Kotlin that uses FCM. If the app is killed off it will still receive data messages. I have been working on porting the app to Flutter. However, on flutter the app does not receive messages unless it is in a running or background state.

So what is the reason for this? It would seem like it is doable. I've talked to a few people at IO 2019 from both the Flutter & Firebase teams and they suggested I open an issue. Tagging @amirh and @kroikie 

Thanks,
Gerry

**Comment by kroikie** [comment]
@gerryhigh At first investigation I am able to reproduce this issue. Looks like the message is getting to the device on the Android side but the broadcast does not work if the app is swiped away from recents. I'll investigate further and report back here.

**Comment by gerryhigh** [comment]
@kroikie I'm glad to hear that you were able to reproduce it. After IO I have spent some time confirming that the issue exists not just on Android Q but also on Android O (Nexus 5X).  I have also done other testing to see if it was anything I was doing but finally yesterday tried the example program and found that it was not working either.

I'm CCing @eseidelGoogle as he asked me to include him on this issue.

**Comment by kroikie** [comment]
After looking at this further, this will require some significant changes to the existing plugin to support data messages when the app process is ended. I will leave issue open and update here with any changes. Thanks for reporting this!

**Comment by gerryhigh** [comment]
I do hope this can get resolved soon as it is a serious regression from native Android apps. In my case I'll have to evaluate and decide if this loss of functionality is worth moving forward or not with this particular app.

**Comment by kroikie** [comment]
@gerryhigh There are some Flutter Engine changes that are required for this to be fixed. These changes are already in review so once those engine PRs land I will be able to address this issue. I'll leave it open and provide more updates here.

**Comment by gerryhigh** [comment]
Thanks for the update. I was actually going to start comparing my Kotlin app vs the Android plugin and see if I could hack something up but given there are engine changes I will wait for your changes. I may end up releasing the iOS version first if it comes to that. Thanks again.

**Comment by aleaforny** [comment]
I'm facing the same issue with firebase_messaging, as per the table "Receiving Messages" states on https://pub.dev/packages/firebase_messaging : **Receiving data messages while App is terminated on Android is not supported by the plugin.**

I join @gerryhigh as it's a severe regression and I hope this can be fixed. If you ever find something @gerryhigh , I'll be more than pleased to know how you managed to trick it 😊 

Thanks

**Comment by Henry-Keys** [comment]
+1 for this issue to be solved.

**Comment by kroikie** [comment]
Hi All, just an update here.

The firebase_messaging plugin uses a Local Broadcast to invoke Dart side code when a message is received. This works fine when the App's process is running. However when the process is not running the app cannot listen for and receive broadcasts, this prevents the Dart side from being invoked. We are currently looking alternative ways of invoking the Dart side when a message is received.

I will continue to update here with our progress.

**Comment by Henry-Keys** [comment]
@kroikie, are you planning to use Background Execution with Dart to solve this?
There's someone that managed to do this, see this [discussion](https://www.reddit.com/r/FlutterDev/comments/bnpzta/firebase_and_offline_push_notifications/en8evrt/).

Cheers

**Comment by kroikie** [comment]
Got a [PR](https://github.com/flutter/plugins/pull/1900) to provide some level of functionality while the app is in the background.

**Comment by athornz** [comment]
I'm not ready yet to create a PR for this but I've got a branch with background execution working in both iOS and Android: https://github.com/athornz/plugins/tree/messaging-background-execution.

- onMessage must be a top-level or static function
- `FirebaseMessagingPlugin.setPluginRegistrant(this)` must be called on the Android side:
```
class MyApplication : FlutterApplication(), PluginRegistry.PluginRegistrantCallback {

    override fun onCreate() {
        super.onCreate()

        FirebaseMessagingPlugin.setPluginRegistrant(this)
    }

    override fun registerWith(registry: PluginRegistry) {
        GeneratedPluginRegistrant.registerWith(registry)
    }
}
```

And on the iOS side:

```
func callback(registry: FlutterPluginRegistry) {
    GeneratedPluginRegistrant.register(with: registry)
}
FLTFirebaseMessagingPlugin.setPluginRegistrantCallback(callback)

```

I've only tested remote messages so far.

**Comment by kroikie** [comment]
@athornz Our approach on Android is similar to what you suggest. We will look into iOS next.

**Comment by subhash279** [comment]
@kroikie May I please know if the iOS version would be updated soon?

**Comment by kroikie** [comment]
@subhash279 we are currently working on this and updates to FCM support on iOS are coming soon.

**Comment by lordfrank** [comment]
> @subhash279 we are currently working on this and updates to FCM support on iOS are coming soon.

hello, news about the ios update? thanks

**Comment by subhash279** [comment]
@kroikie Just checking if there is any update on it pls.

**Comment by mubashirbashir** [comment]
i tried many things but was not not able to make push notification work on ios 13.5.1. I followed the official documentation and uploaded the build on test flight. Strangely i start receiving push notification on resume, on launch as well as on message. Also working fine with local notification plugin.

**Comment by pokkeerr** [comment]
hello, @kroikie any update about this issue?

**Comment by stuartmorgan** [comment]
`firebase_messaging` is no longer part of this project; if this is still an issue it should be filed in [the FlutterFire repository](https://github.com/FirebaseExtended/flutterfire/issues).
