### ISSUE TITLE
Physical Keyboard support on obscure text fields in Android

### ISSUE THREAD

**Issue by Jemshi101** [flutter/flutter#32373]
This is related to https://github.com/flutter/flutter/issues/11177 issue.

> https://github.com/flutter/flutter/issues/11177#issuecomment-388621784
> 
> Found a really weird case of the physical keyboard not working for emulated Pixel 2XL (API 27) when the TextFormField has `obsecureText: true`.
> 
> For anyone wanting to run an example: https://gist.github.com/MarkOSullivan94/bb3f0ea1eb158503f3235339bc23dae0

This is happening still. I could not enter anything using a physical keyboard in a textfield with `obscureText: true` is used.

##Steps to Reproduce

1.   Fire up an AVD in Android Studio
2.   Run the Flutter gallery in the AVD
3.   Navigate to the "Text fields" demo
4.   Select the first text input and begin typing on your physical keyboard

##Expected Behavior

You expect the text input to respond to physical key events, as they do in the iOS simulator.
##Actual Behavior

The text input does not respond to physical key events.
##Additional information

Some AVDs (such as the default used within Google) disable the virtual keyboard by default and rely on physical keyboard input. For these emulators, there's no way to enter text in flutter apps.

**Comment by BondarenkoStas** [comment]
@Jemshi101 is it the same while using current flutter stable v1.9.1+hotfix.4?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
