### ISSUE TITLE
[web]: TextField with Input Decoration has top part invisible

### ISSUE THREAD

**Issue by Vanethos** [flutter/flutter#32381]
In Chrome, MacOs Version 74.0.3729.131 (Official Build) (64-bit):

```
import 'package:flutter_web/material.dart';

void main() {
  runApp(ShowMeAroundApp());
}

class ShowMeAroundApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  State<HomePage> createState() {
    return _HomePageState();
  }
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white70,
      body: Center(
        child: SizedBox(
          width: MediaQuery.of(context).size.width * 0.4,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text("Test", style: TextStyle(fontSize: 20, fontStyle: FontStyle.italic),),
              SizedBox(height: 50,),
              TextField(

                decoration: InputDecoration(
                    disabledBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.all(Radius.circular(5.0)),
                        borderSide: BorderSide(color: Colors.black)),
                    border: OutlineInputBorder(
                        borderRadius: BorderRadius.all(Radius.circular(5.0)),
                        borderSide: BorderSide(color: Colors.black)),
                    labelText: "Test..."

                ),
              )
            ],
          ),
        ),
      )
    );
  }
}
```

Produces the following:

<img width="1198" alt="imagem" src="https://user-images.githubusercontent.com/10728633/57437073-53730b80-7241-11e9-900c-76f7344af64d.png">

When clicking on the field, it shows the correct outline

<img width="1181" alt="imagem" src="https://user-images.githubusercontent.com/10728633/57437108-62f25480-7241-11e9-8fee-e3e91d644d84.png">

I also tried to remove the elements above the TextFormField (the SizedBox and Text), but the outcome was the same

**Comment by caztial** [comment]
Im also having this issue :) 

I tried putting a Container and BoxDecoration to wrap it for some radius values the container boarder also gets invisible  
`  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Center(
          child: Container(
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(8.0),
              border: Border.all(color: Color(0xFF103F54), width: 1.0),
            ),
            width: 447.0,
            child: TextField(
              decoration: InputDecoration(
                hintText: "enter your new password",
              ),
            ),
          ),
        ),
      ),
    );
  }`

**Comment by rvowles** [comment]
@yjbanov this issue was added to the June milestone but appears to have missed it, has it been reprioritised by chance?

**Comment by venkimurthy07** [comment]
Still i am facing same issue, any fixes available

**Comment by yjbanov** [comment]
@rvowles 

> has it been reprioritised by chance?

No, I just wasn't using the labels correctly (had to re-learn https://github.com/flutter/flutter/wiki/Issue-hygiene#milestones)

@venkimurthy07 

> Still i am facing same issue, any fixes available

We fixed a separate border issue and thought that might fix this too, but apparently it didn't. There's also https://github.com/flutter/flutter/issues/34511 which may be caused by the same bug. @ferhatb do you recall any more details about this?

**Comment by ferhatb** [comment]
Issue fixed, will land in github shortly.

**Comment by venkimurthy07** [comment]
Thanks, please let me know once deployed :)

**Comment by kangajos** [comment]
jbbj
