### ISSUE TITLE
CocoaPods could not find compatible versions for pod “Firebase/CoreOnly”

### ISSUE THREAD

**Issue by panthe** [flutter/flutter#32389]
I've update my flutter package to the last versions and now IOS doesn't work anymore.

When I try to update the pods it's shows this error:
```
    [!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
    In Podfile:
    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.0.1, which depends on
    Firebase/Firestore (~> 6.0) was resolved to 6.0.0, which depends on
    Firebase/CoreOnly (= 6.0.0)

    cloud_functions (from `.symlinks/plugins/cloud_functions/ios`) was resolved to 0.0.1, which depends on
    Firebase/Functions (~> 5.18) was resolved to 5.18.0, which depends on
    Firebase/CoreOnly (= 5.18.0)
```
Here my pubspec.yaml (Firebase related):
```
firebase_core: "^0.4.0"
firebase_auth: "^0.11.0"
firebase_analytics: "^3.0.0"  
cloud_firestore: "^0.11.0+1"
cloud_functions: "^0.3.0"
firebase_storage: "^3.0.0"
firebase_messaging: "^5.0.1"
```
I've made various steps to try to fix:
```
flutter clean
flutter build ios

pod install
pod update
pod repo update
pod install --repo-update
```
I've set platform :ios, '12.1' in Podfile and in Xcode as build target but nothing come back to works.

Here my podfile:
```
# Uncomment this line to define a global platform for your project
platform :ios, '12.1'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  use_frameworks!

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by rogiervandenberg** [comment]
I have the same thing after upgrading Flutter, but with a slightly different error where it stops.

- Create shiny new project to test: `flutter create appletest`
- Drop in the latest firebase plugins:

```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0
  firebase_analytics: ^3.0.0
  firebase_auth: ^0.11.0
  cloud_firestore: ^0.11.0+1
  cloud_functions: ^0.3.0
```

- and build iOS: `flutter build ios`

results in:

```
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios-release`
    -> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
    -> Fetching podspec for `cloud_functions` from `.symlinks/plugins/cloud_functions/ios`
    -> Fetching podspec for `firebase_analytics` from `.symlinks/plugins/firebase_analytics/ios`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "Firebase/Functions":
      In Podfile:
        cloud_functions (from `.symlinks/plugins/cloud_functions/ios`) was resolved to 0.0.1, which depends on
          Firebase/Functions (~> 5.18)

    Specs satisfying the `Firebase/Functions (~> 5.18)` dependency were found, but they required a higher minimum
    deployment target.
```

My Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-NL)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.33.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by dvird** [comment]
+1

**Comment by FuNnaji** [comment]
+1

**Comment by panthe** [comment]
The problem is in cloud_functions plugins.
They have 5.18 version of Firebase.
For fix it you must change manually the file cloud_functions.podspec in the ios folder of the plugin while their doesn't finally fix.

Change it

> s.dependency 'Firebase/Firestore', '~> 5.18'

to

> s.dependency 'Firebase/Firestore', '~> 6.0'

After that still remaing an error regarding some missed dependencies of Firebase functions files.

I add directly in the pod this line:
> pod 'Firebase/Functions'

I know that all this is an workaround but works in this way for me.

**Comment by lambasoft** [comment]
+1

**Comment by rwozniak** [comment]
In my case running `pod repo update` from the `ios` directory helped to fix the issue.

**Comment by adriancmurray** [comment]
Neither of the suggest workarounds fixed it for me but this one did: https://stackoverflow.com/a/56080232/9910719

**Comment by colatusso** [comment]
`pod update`  did the trick for me.

**Comment by panthe** [comment]
I have try now and I think that the workaround is not relevant anymore.

**Comment by mliitfall** [comment]
Just delete podfile.lock work for me

**Comment by jspkm** [comment]
> `pod update` did the trick for me.

This worked for me. Thanks @colatusso!

**Comment by aaronsamkennedy** [comment]
> `pod update` did the trick for me.

This worked for me after adding the highest ios version dependency from the symlinks/plugins in the Podfile `platform :ios, '11.0'`

**Comment by eyale** [comment]
> `pod update` did the trick for me.

....for me too, thanks mate!
Update updating existing pods, removing unnecessary pods, so you don't need to run pod install again.

**Comment by emptyopen** [comment]
(1) delete podfile.lock (if you are getting complaints about conflicting package versions, especially)
(2) `pod update`

**Comment by MeshkaniMohammad** [comment]
If you got the following error:
`[!] CocoaPods could not find compatible versions for pod "cloud_firestore":
  In Podfile:
    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`)

Specs satisfying the `cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`)` dependency were found, but they required a higher minimum deployment target.
`

Just go to Podfile and update the minimum deployment target (in my case it was 9.0 and i changed it to 10.0).

**Comment by erf** [comment]
I had a similar problem and fixed it by updating the min ios version in the `Podfile`:
```
platform :ios, '10.0'
```

**Comment by eademir** [comment]
i had similar problem and i couldn't fix it for a while. i deleted firebase_analytics from pubspec.yaml and it's working.

**Comment by lane-faison** [comment]
`platform :ios, '10.0'`
then
`pod update`

**Comment by yuchar** [comment]
> 1. `platform :ios, '10.0'`
> 2. `pod update`
> 3. `flutter clean`
> 4. `flutter build ios`

Thanks @lane-faison

**Comment by Sukendh** [comment]
# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

do this in your pod file. It worked for me.

**Comment by flutterq** [comment]
[All Possible Working Solution Added Here [Solved] CocoaPods could not find compatible versions for pod “Firebase/CoreOnly”](https://fluttercorner.com/cocoapods-could-not-find-compatible-versions-for-pod-firebase-coreonly/)
