### ISSUE TITLE
[firebase_messaging] [IOS]Token invalid when I restart my App

### ISSUE THREAD

**Issue by falll2000** [flutter/flutter#32388]
I meet a problem when I use firebase_messaging plugin in iPhone 6 plus.

I can get valid token when I first open my App. 
But when I kill my app and reopen it, token invalid.
This situation only happen in iPhone 6 and iPhone 6 plus
 I try to mark all  firebase_messaging code, and reopen my app, token still invalid.
Does anyone meet this situation? How to solve it?  

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale
    zh-Hant-TW)
    • Flutter version 1.2.1 at /Library/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jerry/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5429.25

**Comment by sbJonas** [comment]
Hi,
i got this issue on an iPad 3 (iOS 9.3.5) and want to share some observations. On first install everything works fine. After restarting the app (via Android Studio, XCode or directly on the device) the token gets invalidated. In XCode (with -FIRDebugEnabled set) i get following logs on the second launch (not complete, just logs i think are relevant):

May 10 11:04:45  Runner[428] <Debug>: 5.20.0 - [Firebase/InstanceID][I-IID013006] App reset detected. Will delete server registrations.
May 10 11:04:45  Runner[428] <Debug>: 5.20.0 - [Firebase/InstanceID][I-IID021000] Unregister request to ...
May 10 11:04:46  Runner[428] <Debug>: 5.20.0 - [Firebase/InstanceID][I-IID014007] Successfully deleted GCM server registrations on app reset

After the token is invalidated i always get "NotRegistered" errors when sending push notifications to this device. But the fcm token always stays the same so the only way to get a new fcm token is to deinstall the app and do a fresh install to trigger the fcm token recreation.

So it looks like APNs is invalidating the APNs token for some reason.
@falll2000 Do you get logs like this too? Just to get an indicator if we really got the same issue.

(Just for completeness: I thought i got another issue and commented here #30486  but now i think this is my real issue)

Thanks for any help
Jonas

**Comment by sbJonas** [comment]
So..., i hope i solved my issue. For me it looks like it was a CamelCased iOS bundle id. I am not completely certain but after changing the bundle id to just lower characters the issue disappeared.

**Comment by falll2000** [comment]
No, I don't get "App reset detected. Will delete server registrations." message.

I update firebase_messaging's version to 5.0.1+1 and clean project build, the issue not show again. Maybe you can try to update your firebase_messaging version.

I am android engineer, so about apn server setting, I can't support you. 
Hope you can solve this issue. :)

**Comment by BondarenkoStas** [comment]
I think it's safe to close the issue.
