### ISSUE TITLE
[in_app_purchase] Support subscription upgrade/downgrade

### ISSUE THREAD

**Issue by rahulraj64** [flutter/flutter#32395]
Glad to see the beta release of official InApp purchase plugin. Please add support for upgrading/downgrading subscription plans. Currently, the plugin does not support this. In Android, this can be achieved by passing an old SkuId while purchasing a new plan. 
Reference: https://developer.android.com/google/play/billing/billing_subscriptions#Allow-upgrade
Version: **in_app_purchase: ^0.1.0**
@mklim

**Comment by rahulraj64** [comment]
Hi @mklim,
 Any ETA for this feature? 
Currently, we provide 2 subscription plans for Android, a low-cost base plan and high-cost premium plan and provide access to the customers according to the plan. Any time the customers should be able to upgrade or downgrade the plans. 
In the current implementation of the plugin, the customers can purchase the base plan, as well as the premium plan at the same time and both of the subscriptions will be active, which blocks me from publishing the app. I think most of the apps do this kind of approach to charge customers by subscription.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/plugins/tree/master/packages/in_app_purchase is the code.

https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/android/src/main/java/io/flutter/plugins/inapppurchase/InAppPurchasePlugin.java#L205 looks like a relevant part.

I'd recommend forking the in_app_purchases plugin, making the necessary modifications for your needs and using that for the time being. @mklim is currently off working on another project at this moment and I don't know when he'll be back working on this plugin.

Pull requests are of course always welcome to the flutter/plugins repository itself.  FYI @amirh

**Comment by andrewpmoore** [comment]
Just came here to raise the same issue. I'll see if I can add it myself.

**Comment by amirh** [comment]
@andrewpmoore thumb up the issue (first comment) in order to bump it up the priority order.

**Comment by rahulraj64** [comment]
I customized the plugin and implemented the Android side. I always would love to make a pull request, but not sure about the iOS part. How the current implementation would on iOS or is there any changes to be done to make it work on iOS. I don't have an Apple developer account and not familiar with the ecosystem. It takes more time for me to implement the changes for iOS. Since this is a plugin, I am afraid to make an Android-only modification as a pull request. 

Official support is critically needed since this is the most common use case and incorrect implementation of this plugin causes losing the real money.

https://github.com/flutter/plugins/compare/master...rahulraj64:feature/iap-change-subscription

CC @mklim @cyanglaz

**Comment by rahulraj64** [comment]
Since it has been many months, may I ask is there any updates on this? Released Android app on play store and waiting for this to release iOS.  Any ETA ?

**Comment by Hixie** [comment]
I think the reality is that this isn't a priority for Google's engineering team currently but we are very welcome to the idea in general, and your Android implementation seems fine at first glance (aside from needing tests). If this is a feature that it makes sense to support on iOS then my recommendation would be to see if you can find someone who can work with you to implement it there, and then together submit PRs to add this feature.

Sorry that we don't have better news; the reality is that we are currently focused on higher-priority issues on the plugins side such as making the infrastructure support multiple platforms more cleanly, and improving the message channel API so that writing plugins involves less boilerplate.

**Comment by pmrajani** [comment]
When plugin will support subscription upgrade/downgrade any idea? @H3r3zy @rahulraj64  @mklim @Hixie

**Comment by Adeering** [comment]
Is there any update on this? Getting ready to launch my app and this is the last thing holding it back

**Comment by rahulraj64** [comment]
Finally, I verified that this does not require any code changes on iOS since iTunesConnect provides a way to create a 'subscription group' to group logical subscriptions together. This is an Android-only change and happy to make this pull request
https://github.com/flutter/plugins/pull/2822

**Comment by vishnukvmd** [comment]
@Hixie the pull request raised by @rahulraj64 (https://github.com/flutter/plugins/pull/2822), LGTM. How can we get someone from Google to review this?

**Comment by Hixie** [comment]
You don't need a Googler to review it, you need someone on the "Flutter Hackers" team ("team member" role on our Discord). I would recommend asking in the #hackers-ecosystem Discord channel, as it says in the contributing documentation (https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md).

**Comment by cyanglaz** [comment]
@vishnukvmd  FYI: I just reviewed the PR :)

**Comment by cyanglaz** [comment]
Closing as fixed with https://github.com/flutter/plugins/pull/2822. Upgrade the plugin to 0.4.1 to get the feature :)
