### ISSUE TITLE
Build issue with flutter + IOS Xcode firebase_auth

### ISSUE THREAD

**Issue by nagik23** [flutter/flutter#32398]
Hi,

I am getting the following errors when building my flutter app on Xcode. I have tried everything (flutter clean, flutter packages get, deleting Pods folder, running pods install, pod update, etc) but whatever I do, I am getting the same following error:

                                                                                                                                  Xcode build done.                                            5.1s                                                                 Failed to build iOS app                                                                             
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.m:80:42: error:
    incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type
    'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                  completion:^(FIRUser *user, NSError *error) {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.m:5:
    In file included from
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.h:7:
    In file included from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/Firebase/Firebase.h:12:
    In file included from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FirebaseAuth.h:21:
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FIRAuth.h:500:66: note:
    passing argument to parameter 'completion' here
                      completion:(nullable FIRAuthDataResultCallback)completion;
                                                                     ^
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.m:87:42: error:
    incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type
    'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                  completion:^(FIRUser *user, NSError *error) {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.m:5:
    In file included from
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.h:7:
    In file included from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/Firebase/Firebase.h:12:
    In file included from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FirebaseAuth.h:21:
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FIRAuth.h:500:66: note:
    passing argument to parameter 'completion' here
                      completion:(nullable FIRAuthDataResultCallback)completion;
                                                                     ^
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.m:96:42: error:
    incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type
    'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                  completion:^(FIRUser *user, NSError *error) {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.m:5:
    In file included from
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.h:7:
    In file included from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/Firebase/Firebase.h:12:
    In file included from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FirebaseAuth.h:21:
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FIRAuth.h:500:66: note:
    passing argument to parameter 'completion' here
                      completion:(nullable FIRAuthDataResultCallback)completion;
                                                                     ^
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.m:109:21: warning:
    'fetchProvidersForEmail:completion:' is deprecated: Please use fetchSignInMethodsForEmail:completion: for Objective-C or
    fetchSignInMethods(forEmail:completion:) for Swift instead. [-Wdeprecated-declarations]
        [[FIRAuth auth] fetchProvidersForEmail:email
                        ^
    In file included from
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.m:5:
    In file included from
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.h:7:
    In file included from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/Firebase/Firebase.h:12:
    In file included from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FirebaseAuth.h:21:
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FIRAuth.h:334:1: note:
    'fetchProvidersForEmail:completion:' has been explicitly marked deprecated here
    DEPRECATED_MSG_ATTRIBUTE("Please use fetchSignInMethodsForEmail:completion: for Objective-C or "
    ^
    In module 'Darwin' imported from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FIRAuth.h:17:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/usr/inclu
    de/AvailabilityMacros.h:179:64: note: expanded from macro 'DEPRECATED_MSG_ATTRIBUTE'
                #define DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                                   ^
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.m:156:52: error:
    incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type
    'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                            completion:^(FIRUser *user, NSError *error) {
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.m:5:
    In file included from
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.h:7:
    In file included from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/Firebase/Firebase.h:12:
    In file included from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FirebaseAuth.h:36:
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FIRUser.h:360:64: note:
    passing argument to parameter 'completion' here
                    completion:(nullable FIRAuthDataResultCallback)completion;
                                                                   ^
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.m:165:52: error:
    incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type
    'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                            completion:^(FIRUser *user, NSError *error) {
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.m:5:
    In file included from
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.h:7:
    In file included from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/Firebase/Firebase.h:12:
    In file included from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FirebaseAuth.h:36:
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FIRUser.h:360:64: note:
    passing argument to parameter 'completion' here
                    completion:(nullable FIRAuthDataResultCallback)completion;
                                                                   ^
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.m:172:52: error:
    incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type
    'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                            completion:^(FIRUser *user, NSError *error) {
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.m:5:
    In file included from
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.h:7:
    In file included from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/Firebase/Firebase.h:12:
    In file included from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FirebaseAuth.h:36:
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FIRUser.h:360:64: note:
    passing argument to parameter 'completion' here
                    completion:(nullable FIRAuthDataResultCallback)completion;
                                                                   ^
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.m:250:42: error:
    incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type
    'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                  completion:^(FIRUser *user, NSError *error) {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.m:5:
    In file included from
    /Users/nagik/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.15/ios/Classes/FirebaseAuthPlugin.h:7:
    In file included from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/Firebase/Firebase.h:12:
    In file included from
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FirebaseAuth.h:21:
    /Users/nagik/Dropbox/Projects/Dev/flutter/bharat_thakur_art/ios/Pods/Headers/Private/FirebaseAuth/FIRAuth.h:500:66: note:
    passing argument to parameter 'completion' here
                      completion:(nullable FIRAuthDataResultCallback)completion;
                                                                     ^
    1 warning and 7 errors generated.

Could not build the application for the simulator.

I am using the following modules: 

Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Fetching podspec for `audioplayer` from `.symlinks/plugins/audioplayer/ios`
Fetching podspec for `audioplayers` from `.symlinks/plugins/audioplayers/ios`
Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
Fetching podspec for `connectivity` from `.symlinks/plugins/connectivity/ios`
Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
Fetching podspec for `flutter_sound` from `.symlinks/plugins/flutter_sound/ios`
Fetching podspec for `image_cropper` from `.symlinks/plugins/image_cropper/ios`
Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
Fetching podspec for `screen` from `.symlinks/plugins/screen/ios`
Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`
Downloading dependencies
Using BoringSSL-GRPC (0.0.3)
Using FMDB (2.7.5)
Using Firebase (6.0.0)
Using FirebaseAnalytics (6.0.0)
Using FirebaseAuth (6.0.0)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (6.0.0)
Using FirebaseDatabase (6.0.0)
Using FirebaseFirestore (1.3.0)
Using FirebaseInstanceID (4.0.0)
Using Flutter (1.0.0)
Using GTMSessionFetcher (1.2.1)
Using GoogleAppMeasurement (6.0.0)
Using GoogleUtilities (6.0.0)
Using Protobuf (3.7.0)
Using Reachability (3.2)
Using TOCropViewController (2.3.8)
Using audioplayer (0.0.1)
Using audioplayers (0.0.1)
Using cloud_firestore (0.0.1)
Using connectivity (0.0.1)
Using firebase_auth (0.0.1)
Using firebase_core (0.0.1)
Using flutter_sound (0.0.1)
Using gRPC-C++ (0.0.8)
Using gRPC-Core (1.19.0)
Using image_cropper (0.0.1)
Using image_picker (0.0.1)
Using leveldb-library (1.20)
Using nanopb (0.3.901)
Using path_provider (0.0.1)
Using screen (0.0.1)
Using shared_preferences (0.0.1)
Using sqflite (0.0.1)
Using video_player (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 15 dependencies from the Podfile and 35 total pods installed.

Pls help! I went through many messages here and tried everything - still the problem persists.

**Comment by jmillions** [comment]
+1

**Comment by jmagman** [comment]
Looks similar to https://github.com/flutter/flutter/issues/18340 but it's a different block pointer type.  Do any of the suggested solutions in that issue work?

**Comment by collinjackson** [comment]
It looks to me like CocoaPods is selecting an incompatible version of the Firebase/Auth pod. We might need to make the dependency more specific. Does running `pod update --repo-update` in the ios folder help?

**Comment by kroikie** [comment]
@nagik23

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1110. Any further collaboration will be done there.
