### ISSUE TITLE
Can app use the text "Flutter" in the app description?

### ISSUE THREAD

**Issue by raptorck** [flutter/flutter#32392]
According the Flutter's license or other rules, can we say our app used Flutter, in the app description? 
And if we used the text "Flutter", do we need to mention "Flutter and the related logo are trademarks of Google LLC"  in the app stores' description?

**Comment by stuartmorgan** [comment]
https://flutter.dev/brand covers usage of the Flutter name.

**Comment by raptorck** [comment]
It said about website, blog... but what about app stores' description?  If it is not in the title, then we can use it ?
