### ISSUE TITLE
new file opening issue

### ISSUE THREAD

**Issue by arunachaleshwaran** [flutter/flutter#32407]
when I open the flutter application file like `flutter-master` from the GitHub but it not working while opening. it shows the errors like the flutter is not connected to flutter SDK. like `runApp()` not defined.
> resolved by
I comment out every dependency in the `.yaml` file. then it didn't show any error. then one by one I remove the comments and run `futter package get` then it shows no error and runs perfectly.

**Comment by tvolkert** [comment]
It's not clear from the description what the issue is or whether you've since resolved it, so I'm going to close this issue.  Please feel free to re-open and add more info if this is still an issue for you!

**Comment by arunachaleshwaran** [comment]
i fell that is like a bug i will reach out to you when i download new flutter files
