### ISSUE TITLE
Firebase CocoaPods dependency-error after upgrade to Flutter 1.5.4

### ISSUE THREAD

**Issue by rogiervandenberg** [flutter/flutter#32400]
I had a fully working app, after upgrading to v1.5.4-hotfix.2 (stable) my project cannot build iOS anymore, using the latest plugins for Firebase.

- Create shiny new project to test: `flutter create appletest`
- Drop in the latest firebase plugins:

```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0
  firebase_analytics: ^3.0.0
  firebase_auth: ^0.11.0
  cloud_firestore: ^0.11.0+1
  cloud_functions: ^0.3.0
```

- and build iOS: `flutter build ios`

results in:

```
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios-release`
    -> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
    -> Fetching podspec for `cloud_functions` from `.symlinks/plugins/cloud_functions/ios`
    -> Fetching podspec for `firebase_analytics` from `.symlinks/plugins/firebase_analytics/ios`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "Firebase/Functions":
      In Podfile:
        cloud_functions (from `.symlinks/plugins/cloud_functions/ios`) was resolved to 0.0.1, which depends on
          Firebase/Functions (~> 5.18)

    Specs satisfying the `Firebase/Functions (~> 5.18)` dependency were found, but they required a higher minimum
    deployment target.
```

My Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-NL)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.33.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Somehow it seems that the combination of the latest FlutterFire plugins with the latest Flutter don't work anymore 🙁

**Comment by lukef** [comment]
Have you tried running `pod repo update`? It's possible your cocopods repo is out of date.

**Comment by PandaGeek1024** [comment]
Having exactly the same issue, I have tried pod repo update. But still no luck.

**Comment by rogiervandenberg** [comment]
I have a solution! Some Google/FlutterFire plugins have CocoaPod dependencies changed to `'~> 6.0'` in their latest release (like [cloud_firestore](https://pub.dev/packages/cloud_firestore#01101) (_click for details_)), but not all (like [firebase_core](https://pub.dev/packages/firebase_core#040)).

So, if you try to mix-use these plugins, the one is complaining about a too old vs. too new dependency.

The **fix** is to set the required plugins to versions not using ~> 6.0 yet, like so:
```
  firebase_core: ^0.4.0
  firebase_analytics: 3.0.0
  firebase_auth: 0.10.0
  cloud_firestore: 0.11.0
  cloud_functions: ^0.3.0
```

PS: I was also not running the latest (1.6.1) version of cocoapods, that's what I fixed first (no result), then `pod repo update` (no result), then the above (different versions).

**Comment by TedAce** [comment]
same problem here, @rogiervandenberg fix not helping.
Versions:
`firebase_core: ^0.4.0`
`firebase_analytics: 3.0.0`
`firebase_auth: 0.10.0`
`cloud_firestore: 0.11.0`
`cloud_functions: ^0.3.0`




`CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A cloud_functions
      A firebase_analytics
      - Flutter
      - cloud_firestore
      - firebase_auth
      - firebase_core

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
    -> Fetching podspec for `cloud_functions` from `.symlinks/plugins/cloud_functions/ios`
    -> Fetching podspec for `firebase_analytics` from `.symlinks/plugins/firebase_analytics/ios`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "Firebase/Auth":
      In snapshot (Podfile.lock):
        Firebase/Auth (= 6.0.0, ~> 6.0)

      In Podfile:
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.0.1, which depends on
          Firebase/Auth

        firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 0.0.1, which depends on
          Firebase/Auth (~> 5.19)

    It seems like you've changed the constraints of dependency `Firebase/Auth` inside your development pod `firebase_auth`.
    You should run `pod update Firebase/Auth` to apply changes you've made.

    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/resolver.rb:88:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer/analyzer.rb:938:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer/analyzer.rb:936:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer.rb:398:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/command/install.rb:51:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform
    for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone Xʀ.`

**Comment by KevinTheGray** [comment]
@TedAce I was having some similar problems, not sure what combination of this was necessary but this is what got it working for me

- I used the dependency versions listed by @rogiervandenberg
- `flutter clean`
- `pod repo update`
- deleted `/ios/Pods/` and `/ios/Podfile.lock`

then it worked

**Comment by hariprasadiit** [comment]
@rogiervandenberg  `cloud_functions: ^0.3.0` is the culprit here. Recent `cloud_functions` update tries to load `Firebase/functions` `5.18` version which doesn't exists. Most recent version of [`Firebase/functions`](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseFunctions.podspec) pod is `2.5.0`.

for quick fix, just remove version from `s.dependency 'Firebase/Functions', '~> 5.18'` of `cloud_functions` package in plugin cache.

**Comment by hariprasadiit** [comment]
@rogiervandenberg please reopen this and change issue title relevant to what is really happening with this issue, so that plugins team can release fix for this.

**Comment by collinjackson** [comment]
It seems like

**Comment by hariprasadiit** [comment]
@collinjackson Deleting `Podfile.lock` fixes the issue. Please close the issue. Thank you

**Comment by samariotorres** [comment]
> @collinjackson Deleting `Podfile.lock` fixes the issue. Please close the issue. Thank you

Worst advice for Flutter app ever.

**Comment by Bforsyth1234** [comment]
> @TedAce I was having some similar problems, not sure what combination of this was necessary but this is what got it working for me
> 
> * I used the dependency versions listed by @rogiervandenberg
> * `flutter clean`
> * `pod repo update`
> * deleted `/ios/Pods/` and `/ios/Podfile.lock`
> 
> then it worked

Worked for me thanks!

**Comment by ollydixon** [comment]
Happening again now. This library is the bane of my existence. The iOS SDK for Firebase has been awful for over 6 years now.

**Comment by exeptionerror** [comment]
Here is all possible solution added [[Solved] Flutter: CocoaPods’s specs repository is too out-of-date to satisfy dependencies](https://fluttercorner.com/flutter-cocoapodss-specs-repository-is-too-out-of-date-to-satisfy-dependencies/)
