### ISSUE TITLE
flutter_web: not getting statefull state less snippet by tuping stl or stf

### ISSUE THREAD

**Issue by samrat19** [flutter/flutter#32405]
while in Flutter mobile application we only type stl or stf it produces a snippet of stateless and statefull widget. But in web part I am not getting this.

![Screenshot (248)](https://user-images.githubusercontent.com/30453784/57453344-d0bf7000-7283-11e9-9535-f3c3bb445465.png)
![Screenshot (249)](https://user-images.githubusercontent.com/30453784/57453351-d61cba80-7283-11e9-9093-0f59d67e909d.png)

when I press enter on statelesswidget and statefullwidget it is not giving me the snippet part

**Comment by yjbanov** [comment]
This will be fixed by fixing https://github.com/flutter/flutter/issues/32415 (you will be able to use `package:flutter` with all existing IDE snippets).
