### ISSUE TITLE
Support for links in flutter_web

### ISSUE THREAD

**Issue by stemuk** [flutter/flutter#32414]
Support for opening links would allow developers to open links to any web page from their current app. 
This is most likely going to be a flutter_web only feature since both Android and iOS already have implementations that support opening links in a webview window. This however is not necessary for flutter_web since we are already in a browser environment.

**Comment by gazialankus** [comment]
Does anyone know a hacky way to do this at the moment?

**Comment by GregorySech** [comment]
Shouldn't the url_launcher plugin handle this instead of flutter itself?

**Comment by ferhatb** [comment]
Handled by url_launcher plugin. Closing issue.
