### ISSUE TITLE
Does flutter_web support any networking?

### ISSUE THREAD

**Issue by QoLTech** [flutter/flutter#32412]
I am trying to make a web request for data, but the http package isn't supported. Is there a way to perform a network request? Image.Network seems to work just fine, but looking at the source for that, I couldn't discern how to replicate what it was doing for network calls.

Any help is appreciated!

**Comment by yjbanov** [comment]
`package:http` should work. You can also use [HttpRequest](https://api.dartlang.org/stable/2.3.0/dart-html/HttpRequest-class.html) from the `dart:html` library. Please reopen if it doesn't work.

**Comment by QoLTech** [comment]
I get this error when building anything that uses `package:http`
`Heartbeat: 14.1s elapsed, 895/898 actions completed.
build_web_compilers:entrypoint on web/main.dart: Skipping compiling flutter_web.examples.hello_world|web/main.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

http|lib/src/multipart_file.dart
http|lib/src/io_client.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings
Heartbeat: 15.7s elapsed, 2833/2833 actions completed.`

**Comment by yjbanov** [comment]
@QoLTech what version of `package:http` is `pub` picking up for you? (You can check in `pubspec.lock`)

@grouma @jakemac53 @natebosch this comes up a lot. Is there a way to improve the error message to something more actionable?

**Comment by yjbanov** [comment]
Actually, nvm. This discussion moved to https://github.com/flutter/flutter/issues/32430.
