### ISSUE TITLE
Allow Flutter for Web to be a build target for existing projects 

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [flutter/flutter#32415]
I understand the use of a different option for creating flutter for web projects using Stagehand, but won't that require having two separate projects and code duplication? Can web be added as a third build target within the existing folder structure next to Android and iOS?

**Comment by GroovinChip** [comment]
Yes please!

**Comment by kevmoo** [comment]
See https://github.com/flutter/flutter_web/blob/master/docs/faq.md#when-will-flutter-for-web-be-ready-for-production

We want to get there, but we need to merge back into the core Flutter SDK first
