### ISSUE TITLE
[web]: The Flutter SDK is not available

### ISSUE THREAD

**Issue by lamikam100** [flutter/flutter#32424]
I am able to run the hello_world web example app with no problem.   When I follow the same steps for my test project (works on flutter mobile), getting the error below.

C:\temp\recipes-master-web>webdev serve
Unhandled exception:
ProcessException: ***OUT***

***ERR***
The Flutter SDK is not available.

***
  Command: C:\Program Files\dart\dart-sdk\bin\pub.bat deps
#0      _runPubDeps (package:webdev/src/pubspec.dart:55:5)
<asynchronous suspension>
#1      PubspecLock.read (package:webdev/src/pubspec.dart:70:11)
<asynchronous suspension>
#2      CommandBase.runCore (package:webdev/src/command/command_base.dart:77:41)
<asynchronous suspension>
#3      ServeCommand.run (package:webdev/src/command/serve_command.dart:98:24)
#4      CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#5      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:36:24)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CommandRunner.run (package:args/command_runner.dart:111:11)
#9      run (package:webdev/src/webdev_command_runner.dart:18:56)
#10     main (file:///C:/Users/amikaml/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/webdev-1.0.1/bin/webdev.dart:16:22)
<asynchronous suspension>
#11     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
Unhandled exception:
ProcessException: ***OUT***

***ERR***
The Flutter SDK is not available.

***
  Command: C:\Program Files\dart\dart-sdk\bin\pub.bat deps
#0      _runPubDeps (package:webdev/src/pubspec.dart:55:5)
<asynchronous suspension>
#1      PubspecLock.read (package:webdev/src/pubspec.dart:70:11)
<asynchronous suspension>
#2      CommandBase.runCore (package:webdev/src/command/command_base.dart:77:41)
<asynchronous suspension>
#3      ServeCommand.run (package:webdev/src/command/serve_command.dart:98:24)
#4      CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#5      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:36:24)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CommandRunner.run (package:args/command_runner.dart:111:11)
#9      run (package:webdev/src/webdev_command_runner.dart:18:56)
#10     main (file:///C:/Users/amikaml/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/webdev-1.0.1/bin/webdev.dart:16:22)
<asynchronous suspension>
#11     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

C:\temp\recipes-master-web>nptepad
'nptepad' is not recognized as an internal or external command,
operable program or batch file.

C:\temp\recipes-master-web>notepad

C:\temp\recipes-master-web>webdev serve
Unhandled exception:
ProcessException: ***OUT***

***ERR***
The Flutter SDK is not available.

***
  Command: C:\Program Files\dart\dart-sdk\bin\pub.bat deps
#0      _runPubDeps (package:webdev/src/pubspec.dart:55:5)
<asynchronous suspension>
#1      PubspecLock.read (package:webdev/src/pubspec.dart:70:11)
<asynchronous suspension>
#2      CommandBase.runCore (package:webdev/src/command/command_base.dart:77:41)
<asynchronous suspension>
#3      ServeCommand.run (package:webdev/src/command/serve_command.dart:98:24)
#4      CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#5      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:36:24)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CommandRunner.run (package:args/command_runner.dart:111:11)
#9      run (package:webdev/src/webdev_command_runner.dart:18:56)
#10     main (file:///C:/Users/amikaml/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/webdev-1.0.1/bin/webdev.dart:16:22)
<asynchronous suspension>
#11     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
Unhandled exception:
ProcessException: ***OUT***

***ERR***
The Flutter SDK is not available.

***
  Command: C:\Program Files\dart\dart-sdk\bin\pub.bat deps
#0      _runPubDeps (package:webdev/src/pubspec.dart:55:5)
<asynchronous suspension>
#1      PubspecLock.read (package:webdev/src/pubspec.dart:70:11)
<asynchronous suspension>
#2      CommandBase.runCore (package:webdev/src/command/command_base.dart:77:41)
<asynchronous suspension>
#3      ServeCommand.run (package:webdev/src/command/serve_command.dart:98:24)
#4      CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#5      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:36:24)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CommandRunner.run (package:args/command_runner.dart:111:11)
#9      run (package:webdev/src/webdev_command_runner.dart:18:56)
#10     main (file:///C:/Users/amikaml/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/webdev-1.0.1/bin/webdev.dart:16:22)
<asynchronous suspension>
#11     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by QoLTech** [comment]
You cannot use the flutter package in your pubspec.yaml file. Take a look at the pubspec.yaml file for the example flutter_web project and yours.

You will also need to replace your import statements throughout your project from to use flutter_web and not flutter. For instance import `'package:flutter/material.dart';` should now look like import `'package:flutter_web/material.dart';`.

**Comment by lamikam100** [comment]
That makes total sense.  Thanks!!

**Comment by yjbanov** [comment]
If you would like to get an existing Flutter app running on the Web, check out the migration guide for that: https://github.com/flutter/flutter_web/blob/master/docs/migration_guide.md

Please file an issue if that guide is not clear or something doesn't work.

**Comment by lamikam100** [comment]
Thank you!
