### ISSUE TITLE
Remove clover from LicensePage

### ISSUE THREAD

**Issue by jtmcdole** [flutter/flutter#32435]
The problem: "Something looks wrong".
What: The license page is generated with clovers between the sections.
What could be better: re-use the `applicationIcon` that was passed into the `showLicensePage()` and promptly ignored. Bonus: its a widget, so it could be anything I specify.

**Comment by csells** [comment]
@jtmcdole can you post a repro sample that demonstrates this issue?

**Comment by jtmcdole** [comment]
The repro case: just use the widget with more than one license. There is nothing more than that as the LicensePage widget's state uses it!

```
        _licenses.add(const Padding(
          padding: EdgeInsets.symmetric(vertical: 18.0),
          child: Text(
            '🍀‬', // That's U+1F340. Could also use U+2766 (❦) if U+1F340 doesn't work everywhere.
            textAlign: TextAlign.center,
          ),
        ));
```

**Comment by gspencergoog** [comment]
Closed via https://github.com/flutter/flutter/pull/66409
