### ISSUE TITLE
Test that web_ui implementation has no dartdocs

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#32439]
So that these do not get out of sync with the real implementation.

**Comment by cbracken** [comment]
@yjbanov @ferhatb thoughts on this?

**Comment by ferhatb** [comment]
@jonahwilliams @cbracken : "Implementation" is probably too broad, is this public classes such as Color or Gradient? How does this effect IDE/Analyzer today?

**Comment by jonahwilliams** [comment]
IIRC the analyzer will only see the "regular" dart:ui, hence the absence of webOnly members. It should be safe to delete from the dartdocs perspective, and any important documentation should be merged into dart:ui

**Comment by ferhatb** [comment]
SGTM. As an edge case, if there is a platform specific comment, it makes sense to have it in "regular" ui.

**Comment by jonahwilliams** [comment]
I'm not currently working on this
