### ISSUE TITLE
FirebaseUser.reload() should update the user with the correct info

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#32431]
To match the behavior of native SDKs, calling `reload()` on a `FirebaseUser` should update its info -- you shouldn't have to call `currentUser()` again.

See flutter/flutter#32324

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/374. Any further collaboration will be done there.
