### ISSUE TITLE
Exception when touching the screen with multiple fingers

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#32432]
* Open any flutter_web app.
* Tap the screen with two fingers simultaneously.
* Notice exception being thrown in the console.

**Comment by justinmc** [comment]
Potentially related to these?
https://github.com/flutter/flutter/issues/20517
https://github.com/flutter/flutter/issues/32132

**Comment by mdebbar** [comment]
@justinmc it appears that the issues you linked are for Flutter native (Android specifically). This issue is specific to the web.
