### ISSUE TITLE
[web] invoke js (on button clicks etc) from dart/flutter code

### ISSUE THREAD

**Issue by startupgurukul** [flutter/flutter#32443]
Platform channels can be a great way of invoking libraries like tf.js from within a flutter/dart  codebase

**Comment by rostopira** [comment]
As a workaround, you can use `dart:js` library: https://api.dartlang.org/stable/2.4.0/dart-js/dart-js-library.html

**Comment by mtallenca** [comment]
Thank you!

**Comment by startupgurukul** [comment]
Thank you for closing. Sorry for not doing due diligence myself
