### ISSUE TITLE
Resuming Flutter app can fail

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#3244]
[I'm sure I've typed this issue in already but I'm unable to find it. Perhaps I failed to press the submit button last time.]

This problem is intermittent and its symptoms are somewhat unpredictable.  Sorry.

If you back out of the Gallery app, wait a moment (I guess to make it more likely that it has been swapped out) and then tap on the paused app, sometimes nothing happens. Although the app's paused title bar changes from the gallery's color to gray (see below).

Sometimes the app can be resumed after a second tap on the paused app. In this case the app restarts, but its state is lost. Sometimes the screen just goes dark and stays that way. The phone may appear to be hung although usually hammering on the system buttons will eventually bring it around.

The problem occur in `--checked` and `--no-checked` modes.
- before attempting to resume the app

![screenshot](https://cloud.githubusercontent.com/assets/1377460/14437340/9e9ba0d6-ffd5-11e5-91df-b7d60604d242.png)
- afterwards the app hasn't resumed, but the title color has changed:

![screenshot](https://cloud.githubusercontent.com/assets/1377460/14437113/98e29ab0-ffd4-11e5-80aa-8aa1aef41682.png)

**Comment by eseidelGoogle** [comment]
I would recommend demoing this for @jason-simmons or @abarth, they might have ideas as to what our graphics code could be doing wrong on resume here.

**Comment by eseidelGoogle** [comment]
@jason-simmons and I discussed this today.  He was not sure if it was still reproducable.  If it is, I believe he's willing to own fixing.  @HansMuller have you seen this recently?

**Comment by HansMuller** [comment]
Yes, it's happening now. I backed out of the app and it did not restart. This (perhaps unrelated) message appeared on the log:
```
W/ActivityManager: Launch timeout has expired, giving up wake lock!
```
On the second attempt to restart the screen went dark, as if the app was restarting from scratch. Sadly it just hung that way.

I reviewed the failure more with  @jason-simmons. Usually the app does restart on the second attempt.

**Comment by jimbeveridge** [comment]
I can reproduce this fairly consistently on latest builds.

**Comment by HansMuller** [comment]
I'm no longer able to reproduce the problem with a current build.

**Comment by sethladd** [comment]
Thanks for checking. We can reopen if we see this again.

**Comment by HansMuller** [comment]
This problem has cropped up again. I'm able to reproduce it on Android in debug and release builds.

**Comment by eseidelGoogle** [comment]
@HansMuller were we able to get a repro into @jason-simmons's hands?

**Comment by eseidelGoogle** [comment]
I'm going to assume this is no longer happening or we would hear about it from our customers.  Please feel encouraged to re-open if that's not true!
