### ISSUE TITLE
i cannot run at ios

### ISSUE THREAD

**Issue by Ahmedesayed** [flutter/flutter#32449]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by Ahmedesayed** [comment]
[flutter_04.log](https://github.com/flutter/flutter/files/3164523/flutter_04.log)

**Comment by ffey** [comment]
```
[31m✗[39m libimobiledevice and ideviceinstaller are not installed. To install
      with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    [32m•[39m ios-deploy 1.9.2
    [31m✗[39m ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
```
is this problem cause it ?

**Comment by justinmc** [comment]
I think you should be able to fix this by following the steps given by `flutter_doctor` pasted above by @ffey.  I'll close this for now, but if you can't fix it and think there might be a bug in Flutter, feel free to reopen.
