### ISSUE TITLE
Attempt to invoke virtual method failure

### ISSUE THREAD

**Issue by CatEatFishs** [flutter/flutter#32458]
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (3 months ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
video_player 0.10.0+5 

Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference, null)
 i think this methods not find
final Map<dynamic, dynamic> response = await _channel.invokeMethod(
      'create',
      dataSourceDescription,
    );

## Logs

Another exception was thrown: SocketException: Failed host lookup: 'filedev.hongkazhijia.come68852332941f800b1e774f31fcb3610a59b400f82667f0da95d821cd112f30c' (OS Error: No address associated with hostname, errno = 7)
I/flutter (21630): PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference, null)
I/flutter (21630): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
I/flutter (21630): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
I/flutter (21630): <asynchronous suspension>
I/flutter (21630): #2      VideoPlayerController.initialize (package:video_player/video_player.dart:214:59)
I/flutter (21630): #3      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
I/flutter (21630): #4      VideoPlayerController.initialize (package:video_player/video_player.dart:193:26)

```
```

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.2)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ Brew can be used to install tools for iOS device development.
      Download brew at https://brew.sh/.
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

**Comment by BondarenkoStas** [comment]
@CatEatFishs did you manage to solve it? Is it the same while using current flutter stable?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
