### ISSUE TITLE
Does google_sigin_in plugin requires registration with Firebase?

### ISSUE THREAD

**Issue by aarjan** [flutter/flutter#32450]
In the documentation, https://github.com/flutter/plugins/tree/master/packages/google_sign_in#android-integration

> To access Google Sign-In, you'll need to make sure to register your application.  

Click on the **register** link https://developers.google.com/mobile/add?platform=android
redirects to Firebase platform. Does that means, i have to no other options than using Firebase?

**Comment by thehitechpanky** [comment]
I don't want to use firebase, is there a workaround?

**Comment by aarjan** [comment]
Looks, like there is no workaround. Actually, using firebase to register your app, doesn't cost you a bit, and it includes lots of free features, which i hope would not cost when you scale.
