### ISSUE TITLE
"Debugging Flutter applications" doesn't mention trace-startup

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3246]
Seems like the Debugging Flutter Applications doc (https://flutter.io/debugging/) has a scope of "things a developer can do/use to debug performance and correctness aspects of their app". If so, we might want to mention `flutter run --trace-startup` [1] and then how to get that info and view it.

Use case: I'd like to attach a trace file of my app's startup to a bug, and I was looking for docs on how to get this info for our engineers.

[1] and, what this does :)

Thanks!

**Comment by eseidelGoogle** [comment]
There are a bunch of other performance debugging tips/tricks like this which are on the list of things we should document this quarter. FYI @qchong and @yjbanov

**Comment by qchong** [comment]
@jason-simmons Jason, did you work on adding the '--trace-startup' option? If so, can you please provide some details about how this option works:

* Does the trace output get dumped somewhere by default, and is there a way to configure the output path? 
* What kind of information is included in the trace? Can this be configured by the user?
* Is this command only meant to be used internally by the Atom?
