### ISSUE TITLE
Separate Dart packages from Plugin packages in pubspec.yaml ?

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#32463]
## Proposal
is there a way to separate Dart packages from Plugin packages in pubspec.yaml dependencies ??

kind of categories like:
dart_dependencies
plugin_dependencies

## Example
so i wanted to make sure my project can be build for web/desktop so i check for plugins (which should fail to work on mentioned platforms )

i have project which use 'flutter_cached_network_image' which if i open its github repo , it doesn't have android/ios folder , so it appears to be a dart package, but in its pubspec.yaml it has another dependency : 'flutter_cache_manager' which is a plugin package because it needs ios/android specific code
so it's confusing to know which dependency is dart package or plugin package

Maybe i am missing something that's really obvious ?? , i don't know :/

**Comment by kangwang1988** [comment]
AFAIK, the short answer is NO now.

**Comment by KirolousNashaat** [comment]
> AFAIK, the short answer is NO now.

no to the proposal ? or just there is no way in pubspec ??
pubspec is the most important file in a project and this way of maintaining dependencies will make it really hard for platforms beyond mobile , plugins for all platforms don't exist , and some of them won't anytime soon .. right ??

btw the only viable solution i found now is in intellij project view > External libraries > Flutter plugins
it shows every plugin u have in the app even if it's a children of package
still u have to search for which package use that plugin in its pubspec but it's a start :)

**Comment by stuartmorgan** [comment]
Closing as "plugin" vs "not plugin" isn't a crisp line (e.g., FFI), and there are non-plugin packages that have OS constraints, so the proposed solution here wouldn't really address the use case.
