### ISSUE TITLE
Terminology: "slow mode" banner in app, and --debug in tools

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3247]
To turn off "slow mode" in my app, I need to use "--no-checked" on the CLI for my tools. It's not obvious that "checked mode" == "slow mode". When I do a `flutter run --help`, I don't see the words "slow" or "slow mode".

Could we have a --help option that clearly means "turn on/off slow mode", to better help our users toggle that mode?

Suggestion: change --[no-]checked to --[no-]slow-mode

Thanks!

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by sethladd** [comment]
cc @Hixie

**Comment by Hixie** [comment]
It's --debug now.

**Comment by Hixie** [comment]
The term "slow mode" was picked over "debug" intentionally, because it was trying to stop people asking "why is it slow".

**Comment by Hixie** [comment]
This will become moot once we have https://github.com/flutter/flutter/issues/9324.

**Comment by yathit** [comment]
Is there any workaround to remove SLOW MODE. I need to take 12" ipad screenshot for App Store. I do not have iPad and could not get a screen shot from simulator.

**Comment by Hixie** [comment]
https://flutter.io/faq/#my-app-has-a-slow-mode-bannerribbon-in-the-upper-right-why-am-i-seeing-that

**Comment by Hixie** [comment]
Oh and on simulator if you want to turn it off you can either take your screenshot from the `flutter` tool (when you press `s` it briefly turns off the ribbon to take the screenshot) or you can explicitly set [debugShowCheckedModeBanner](https://docs.flutter.io/flutter/material/MaterialApp/debugShowCheckedModeBanner.html) to false on your MaterialApp widget.
