### ISSUE TITLE
Finished with error: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by BugLai** [flutter/flutter#32478]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build bundle --suppress-analytics --target /Users/buglai/company/flutter/app-readmi-flutter/lib/main.dart --track-widget-creation --compilation-trace-file compilation.txt --extra-gen-snapshot-options --obfuscate --target-platform android-arm64 --depfile /Users/buglai/company/flutter/app-readmi-flutter/build/app/intermediates/flutter/debug/snapshot_blob.bin.d --asset-dir /Users/buglai/company/flutter/app-readmi-flutter/build/app/intermediates/flutter/debug/flutter_assets --debug

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _Uri._uriEncode (dart:core-patch/uri_patch.dart:44:23)
#2      Uri.encodeFull (dart:core/uri.dart:1145:17)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:40)
#5      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#6      FlutterManifest.assets (package:flutter_tools/src/flutter_manifest.dart:182:11)
#7      _parseAssets (package:flutter_tools/src/asset.dart:558:40)
#8      _ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:142:53)
<asynchronous suspension>
#9      buildAssets (package:flutter_tools/src/bundle.dart:178:40)
<asynchronous suspension>
#10     build (package:flutter_tools/src/bundle.dart:147:36)
<asynchronous suspension>
#11     BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:75:11)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#29     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#30     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#31     new Future.sync (dart:async/future.dart:224:31)
#32     CommandRunner.run (package:args/command_runner.dart:111:11)
#33     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#34     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#41     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#42     run (package:flutter_tools/runner.dart:51:10)
#43     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#44     main (file:///Users/buglai/Library/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/buglai/Library/Flutter/flutter
    • Framework revision 7a4c33425d (11 days ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/buglai/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/buglai/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.26.1

[✓] Connected device (2 available)
    • Pixel 2    • HT82V1A00897                             • android-arm64 • Android 9 (API 28)
    • iPhone (3) • 682a44c988b05477e50bf8115640ebf83fd5b3a2 • ios           • iOS 12.2

• No issues found!
```

**Comment by kangwang1988** [comment]
@BugLai 
Try steps below:
1. Using flutter clean to clean the old build
2. Check your pubspec.yaml and make sure that all items under `assets:` is valid
3. Run `flutter run --verbose` and paste the result below if this issue remains.

**Comment by superkelvint** [comment]
I am experiencing the exact same issue, albeit with a slightly different stacktrace.

<pre>
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _Uri._uriEncode (dart:core-patch/uri_patch.dart:44:23)
#2      Uri.encodeQueryComponent (dart:core/uri.dart:1100:17)
#3      mapToQuery.<anonymous closure> (package:http/src/utils.dart:19:13)
#4      CastMap.forEach.<anonymous closure> (dart:_internal/cast.dart:286:8)
#5      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#6      CastMap.forEach (dart:_internal/cast.dart:285:13)
#7      mapToQuery (package:http/src/utils.dart:17:7)
#8      Request.bodyFields= (package:http/src/request.dart:128:17)
#9      BaseClient._sendUnstreamed (package:http/src/base_client.dart:163:17)
<asynchronous suspension>
#10     BaseClient.post (package:http/src/base_client.dart:54:7)
#11     post.<anonymous closure> (package:http/http.dart:70:16)
#12     _withClient (package:http/http.dart:166:20)
<asynchronous suspension>
#13     post (package:http/http.dart:69:5)
#14     IO.httpPostMapJson (package:edge/io/io.dart:50:26)
<asynchronous suspension>
#15     API.viewTextObject (package:edge/vt/api.dart:47:15)
<asynchronous suspension>
#16     API.viewLibraryPage (package:edge/vt/api.dart:39:12)
<asynchronous suspension>
#17     _LibraryState.initState (package:edge/module/library.dart:23:19)
#18     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
#19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
#24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
#25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
#29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
#33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
#34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
#38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#40     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
#41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
#44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#46     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
#47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
#51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
#52     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
#53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
#54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
#58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
#59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
#60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
#64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
#65     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
#66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#69     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
#70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
#74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
#75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
#76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#78     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
#79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
#83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
#84     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
#85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
#86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
#90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
#91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
#92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#94     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
#95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
#99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
#100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
#101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
#104    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
#105    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
#106    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
#107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
#108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
#111    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
#112    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
#113    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
#114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
#115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#117    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4659:32)
#118    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
#120    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:607:16)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
#122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
#124    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
#126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
#127    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
#128    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
#130    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
#132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
#133    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
#134    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
#135    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
#136    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
#137    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
#138    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
#140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
#141    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
#142    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
#143    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
#144    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#145    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
#146    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
#147    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
#148    _rootRun (dart:async/zone.dart:1124:13)
#149    _CustomZone.run (dart:async/zone.dart:1021:19)
#150    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#151    _invoke (dart:ui/hooks.dart:219:10)
#152    _drawFrame (dart:ui/hooks.dart:178:3)
</pre>

Flutter Doctor
============
<pre>
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.3)
</pre>

**Comment by hsy1992** [comment]
@kangwang1988 You are right!!
