### ISSUE TITLE
Observatory Http Exception stops Flutter execution

### ISSUE THREAD

**Issue by ricardobrg** [flutter/flutter#32488]
I have faced the "Error connecting to the service protocol: HttpException: Connection closed before full header was received..." for some different reasons over the time and searching in the issues I have found lots of different errors like this.

It is generally not a Flutter error but a network configuration error or an OS bug. But when I get this error, the app is launched in the device or emulator but Flutter stops working and outputing messages to the terminal or IDE console.

I'd like to know if there is an option to disable observatory's url and just keep flutter running and outputing messages to the console. I rarely use observatory's url but use the console outputs to debug all the time.

**Comment by DanTup** [comment]
The connection to the VM service is required for Flutter to function (it's how many things work, such as reloading sources and all debugging functionality).

Did you happen to create an Android emulator using Q level API? If so, you might be seeing https://github.com/flutter/flutter/issues/33050 and should try creating one using API level 28 to see if that solves the issue until there's a fix.
