### ISSUE TITLE
plugin firebase_auth throws error on _onAuthStageChangedHandler

### ISSUE THREAD

**Issue by herkulano** [flutter/flutter#32482]
`_onAuthStageChangedHandler()` throws an exception when the `currentUser` is `null` in:

```dart
_authStateChangedControllers[id].add(currentUser);
```

Exception:
```
NoSuchMethodError: The method 'add' was called on null.
Receiver: null
Tried calling: add(null)
```

<img width="1114" alt="Screen Shot 2019-05-10 at 13 51 07" src="https://user-images.githubusercontent.com/125300/57522185-ae346200-732a-11e9-9396-44c1856fa395.png">

**Comment by collinjackson** [comment]
Thanks for the report! What are the steps that you followed to get this error? Is there sample code?

**Comment by herkulano** [comment]
With a clean `flutter create` project change this code:

```dart
class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  @override
  void initState() {
    super.initState();
    _auth.onAuthStateChanged.distinct().listen((firebaseUser) {
      if (firebaseUser == null) {
        _auth.signOut();
      }
    });
  }
```

I realize I probably don't need to sign out because if `firebaseUser == null` it should be signed out already, but I was also doing other things on the sign out and thought it shouldn't be a problem to make sure the user was "fully" signed out.

**Comment by kroikie** [comment]
@herkulano

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/373. Any further collaboration will be done there.
