### ISSUE TITLE
[web]: When scrolling anywhere on the page, console keeps reporting "Uncaught Error: Assertion failed: is not true"

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#32481]
Flutter version

```
[✓] Flutter (Channel dev, v1.5.8, on Mac OS X 10.13.6 17G4015, locale en-CN)
```

Workflow, use stagehand:

```
$ mkdir foo && cd foo
$ stagehand flutter-web-preview
$ flutter packages pub global activate webdev
$ flutter packages pub upgrade
$ flutter packages pub global run webdev serve
```

And then open chrome debug console and trying to scroll anywhere on the page (I am on MacBook, so basically using two fingers on the touchpad and then move Up and Down)

The error:

```
dart_sdk.js:5844 Uncaught Error: Assertion failed: is not true
    at Object.dart.throw (dart_sdk.js:4556)
    at Object.dart.assertFailed (dart_sdk.js:4495)
    at SyncIterable.new.expand (converter.dart:432)
    at expand.next (<anonymous>)
    at ListQueue.new.addAll (dart_sdk.js:31511)
    at src__widgets__binding.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (binding.dart:85)
    at src__engine.PointerBinding.new.[_onPointerData] (pointer_binding.dart:80)
    at pointer_binding.dart:205
    at HTMLElement.<anonymous> (pointer_binding.dart:449)
```

Gif Video:

![output](https://user-images.githubusercontent.com/1555508/57520394-1f3a4080-7350-11e9-8a71-4fcd75d0deba.gif)

**Comment by yjbanov** [comment]
This might have been fixed by https://github.com/flutter/flutter_web/commit/c4cfaecebc5ef97500db2be0bd99e52d1e5e16c2. Please reopen if you see this again.

**Comment by jegathispandian** [comment]
Still i am facing this issue

**Comment by yjbanov** [comment]
I think I saw this too recently. Reopening.

/cc @ferhatb

**Comment by kechankrisna** [comment]
I just got the same issue now,

**Comment by Shafran123** [comment]
I am also facing this issue!

**Comment by kynrai** [comment]
same, happy to help how I can to resolve this

**Comment by miketheman** [comment]
Seen on recent beta channel, and current error message:

doctor:
```
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.14.6 18G2022, locale en-US)
```
devices:
```
Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
Web Server • web-server • web-javascript • Flutter Tools
```

```
errors.dart:147 Uncaught Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:271:18
!state.down
is not true
    at Object.throw_ [as throw] (errors.dart:196)
    at Object.assertFailed (errors.dart:26)
    at _engine.PointerDataConverter.new.convert (pointer_converter.dart:271)
    at _engine.PointerAdapter.new.[_convertEventToPointerData] (pointer_binding.dart:366)
    at pointer_binding.dart:317
    at HTMLElement.<anonymous> (pointer_binding.dart:183)
```

Possibly the same as #46852 ?

**Comment by dkwingsmt** [comment]
https://github.com/flutter/flutter/pull/47492 might be a fix if your problem is an assertion error when scrolling (especially considering the change that this PR tries to fix was merged in May).

**Comment by mdebbar** [comment]
There are multiple errors reported in this issue.

* The original error reported in this issue was fixed by https://github.com/flutter/flutter_web/commit/c4cfaecebc5ef97500db2be0bd99e52d1e5e16c2, https://github.com/flutter/engine/pull/14082 and https://github.com/flutter/engine/pull/14378.
* Scrolling errors were fixed by https://github.com/flutter/flutter/pull/48149 and https://github.com/flutter/flutter/pull/47492.
* Right-click and `state.down` errors were fixed by https://github.com/flutter/engine/pull/15103.

If you are still seeing similar errors, please file an issue for the specific error so we can investigate.
