### ISSUE TITLE
Push notification

### ISSUE THREAD

**Issue by nagaraj95** [flutter/flutter#32486]
## Steps to Reproduce

1. ... I am using fire-store to store my data. I have retried all my data and update the data in UI using list-view builder.
2. ... Then I need to update my UI list-view when push notification comes. I have searched in google but I got no solution.
3. ... Please post any solution regarding my question. Thanks in advance.

## Logs

```
```

```
```

```
```

**Comment by BaderEddineOuaich** [comment]
Let's suppose you are saving notifications data inside a node.
So listening to that node and updating the UI whenever a child is changed/added/removed  will be the solution.
To listen to a node:
<pre>
var listener = FirebaseDatabase.instance
        .reference()
        .child("NotificationsNode")
          ..onChildAdded
              .listen((event) => OnAddedAction(event))) //  create method OnAddedAction to handle the event & manipulate the data.
          ..onChildChanged
              .listen((event) => OnChangedAction(event)))
          ..onChildRemoved
              .listen((event) => OnRemovedAction(event))))); 
</pre>

One more thing make sure to cancel the listeners when the app is on dispose
<pre>
@override
dispose() {
  listener.cancel();
  super.dispose();
}
</per>

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
