### ISSUE TITLE
Assertion failures missing key information

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#32507]
Assume a simple build method like the following:

```dart
Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      color: const Color(0x303030), // this line will fail for non-obvious reasons
      home: Container(/* ... */),
    );
  }
```

Here's what Flutter gives:
![image](https://user-images.githubusercontent.com/2319867/57552346-7a543f00-7320-11e9-83c9-a80ee3b628f5.png)

Here's what Flutter_Web gives:
![image](https://user-images.githubusercontent.com/2319867/57552358-804a2000-7320-11e9-911b-eb61ba6df4b7.png)

We need an improved message here to avoid friction to users. For some reason, the assert fields aren't getting properly propagated.

**Comment by vsmenon** [comment]
This is a DDC issue.

@nshahan - can you file accordingly on DDC?

**Comment by vsmenon** [comment]
@nshahan - can we close this now?  Should be fixed on the next roll of Dart into Flutter, right?

**Comment by nshahan** [comment]
It's landed into the SDK, but I don't know when that commit will actually make it into Flutter but users of flutter_web with the bleeding edge SDK could try it out now.
