### ISSUE TITLE
Obscured CupertinoTextField content is copy-able

### ISSUE THREAD

**Issue by blucell** [flutter/flutter#32504]
# Steps to Reproduce

Create a CupertinoTextField widget with obscureText set to true
Write some text in there and long-press it
Press copy and paste it anywhere else

# What Was Expected

Copy option not to even appear, and not to reveal any of the data

# What Happened

I could copy the obscured text

This was an issue with Material's TextField #24100, and it was temporarily fixed by disabling controls for the time being, but it appears to still exist for CupertinoTextField, too.

**Comment by justinmc** [comment]
Thanks for catching this.  I totally should have added this to CupertinoTextField when I did the Material one.  PR is open and should be in soon.
