### ISSUE TITLE
How to link Firebase Email Sign with Phone number sign in

### ISSUE THREAD

**Issue by harshapulikollu** [flutter/flutter#32500]
Hi, I'm using `firebase_auth` package to sign in user into app via email and password. Now I want to incorporate phone number authentication(only sign in) to the users who already registered into my app through email and password. I have the phone numbers of users. 
From documentation, I came to know using `linkWithCredential(AuthCredential credential)` method we can link third party identity providers. Inorder to achieve my desire what I have to sent as `credential `to `linkWithCredential(AuthCredential credential)` method, after I verified phone number through `verifyPhoneNumber()` method?

**Comment by john-ravi** [comment]
```
  // Example code of how to sign in with phone.
  void _signInWithPhoneNumber() async {
    final AuthCredential credential = PhoneAuthProvider.getCredential(
      verificationId: _verificationId,
      smsCode: _smsController.text,
    );
```
You can use `linkWithCredential(credential)` on the FirebaseUser object you have from email login.

This is not possible other way round, if you have user logged in with phone and you want to link user signing with email/password.
I see we do not get any AuthCredential while signing using Email/Password.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.

**Comment by Aakash-shero** [comment]
Did you find a solution to this @harshapulikollu
