### ISSUE TITLE
flutter run --trace-startup doesn't seem to do much?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3251]
Not sure what to expect, but I'm not sure I'm getting actionable info from `flutter run --trace-startup`.

![screen shot 2016-04-11 at 1 09 15 pm](https://cloud.githubusercontent.com/assets/5479/14441302/111138e8-ffe9-11e5-9a49-44f2820f0a4f.png)

I was hoping I could learn things like:
- how long did it take the engine to initialize?
- how long did it take the VM to initialize?
- how long did it take to read the app/snapshot/etc
- how long, and what were the steps, between tapping the icon and getting to first frame

You can find the full trace here: https://dl.dropboxusercontent.com/u/316685/for-github-issues/dart-timeline-2016-3-11%20%281%29.json

Definitely interested in a repeatable way to get a trace of cold app startup.

Thanks!

**Comment by xster** [comment]
How did you get the actual chrome trace? I ran --trace-startup and only got a summary back, not the actual entire timeline.

**Comment by Hixie** [comment]
I'm closing this on the basis that this works fine today. Please reopen if I misunderstood. There are other bugs open on documenting the UI for this better and improving the experience.
