### ISSUE TITLE
Can't run app after Flutter Upgrade

### ISSUE THREAD

**Issue by guit4eva** [flutter/flutter#32510]
## Problem:

After running `Flutter Upgrade`, I'm getting the following error:

`* Error running Gradle:`
`ProcessException: Process "C:\src\Apps\example\android\gradlew.bat" exited abnormally:`

 `Command: C:\src\Apps\example\android\gradlew.bat app:properties`
`Please review your Gradle project setup in the android/ folder.`

The app was running correctly before the upgrade.

## Logs

`Flutter doctor -v`:

[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.475], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at C:\src\flutter
    • Framework revision 7a4c33425d (11 days ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Rudeboy\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.33.1)
    • VS Code at C:\Users\Rudeboy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.1

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by guit4eva** [comment]
Ended up creating a new project, running the upgrade and importing the edited files from the previous project.

**Comment by pb03** [comment]
Did you try `flutter clean`?
