### ISSUE TITLE
Google io '19 - ML Kit x Material Design Demo

### ISSUE THREAD

**Issue by KirolousNashaat** [flutter/flutter#32526]
https://youtu.be/bEsncYGeMF8?t=1966
at the session the speaker mentioned that demo is open sourced on the flutter repo , but it'snot ! can u upload to the shrine repo in examples in flutter/flutter
or in the samples repo ?

**Comment by willlarche** [comment]
This has moved to https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_ml_vision/example
