### ISSUE TITLE
[web] Some buttons not working when compiling with dart2js

### ISSUE THREAD

**Issue by bgetsug** [flutter/flutter#32523]
Piggybacking off troubleshooting/discussion in #32347, I'm experiencing the following issues with buttons when I compile with `dart2js` / `webdev serve -r` (with or without minify), and not seeing any errors in Chrome Dev Tools console:
* `CheckboxListTile` won't check
* Can click (InkWell appears) but nothing happens
  * `IconButton`s in `CheckboxListTile.secondary` or `ListTile.trailing`
  * `CloseButton` in `AppBar.leading`

**Comment by bgetsug** [comment]
Well, I think I know why `CloseButton` isn't working, since it's not working when I compile with DDC either:

```dart
class CloseButton extends StatelessWidget {
  /// Creates a Material Design close button.
  const CloseButton({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return IconButton(
      icon: const Icon(Icons.close),
      tooltip: MaterialLocalizations.of(context).closeButtonTooltip,
      onPressed: () {
        // TODO(ferhat): wire up once Navigator is moved in
        // Navigator.maybePop(context);
      },
    );
  }
}
```

I think `Navigator.maybePop(context);` can be uncommented now, yes?

**Comment by yjbanov** [comment]
Should be fixed now.
