### ISSUE TITLE
[i hope fiex]about flutter function showDialog can't create Real full screen

### ISSUE THREAD

**Issue by 0-php** [flutter/flutter#32537]
about flutter function showDialog can't create Real full screen
example:
i wan't use showDialog  create real full screen
in iphone6-iphone8 and android phone is full screen but in iphoneX - iphone xs Max have empty space i don't know why
help help help

![image](https://user-images.githubusercontent.com/11140711/57564702-535a4380-73da-11e9-88be-4380a49e0e0f.png)

this is iphone8:
![image](https://user-images.githubusercontent.com/11140711/57564728-e7c4a600-73da-11e9-97ef-a4ea58da7e29.png)

demo:
```C
  showDialog(
    context: context,
    builder: (ctx) => IjkPlayer(
      mediaController: controller,
      controllerWidgetBuilder: (ctl) =>
          _buildFullScreenMediaController(ctl, true),
    ),
  ).then((_) {
    IjkManager.unlockOrientation();
    IjkManager.setCurrentOrientation(DeviceOrientation.portraitUp);
  });
```

**Comment by pedromassangocode** [comment]
Hi @0-php 
Are you still facing this issue? If yes please provide your `flutter doctor -v` and minimal reproducible code sample.
Thank you

**Comment by 0-php** [comment]
> Hi @0-php
> Are you still facing this issue? If yes please provide your `flutter doctor -v` and minimal reproducible code sample.
> Thank you

this long time ago now i use showGeneralDialog to create

**Comment by pedromassangocode** [comment]
Hi @0-php 
Can you confirm that this issue can be closed?
Thank you

**Comment by 0-php** [comment]
> > Hi @0-php
> > Are you still facing this issue? If yes please provide your `flutter doctor -v` and minimal reproducible code sample.
> > Thank you
> 
> this long time ago now i use showGeneralDialog to create

i am not sure if you have time you can check

**Comment by berrylawchingman** [comment]
👍

**Comment by pedromassangocode** [comment]
Please check when you have time. 
Thank you

**Comment by berrylawchingman** [comment]
❤️

**Comment by berrylawchingman** [comment]
Don't try to b silly

**Comment by pedromassangocode** [comment]
Without code sample and steps to reproduce I don't have enough information to verify this and I'm going to close this.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
