### ISSUE TITLE
Flutter create t module do not exist include_flutter.groovy in .android dir since 1.5.4-hotfix

### ISSUE THREAD

**Issue by YellowDoing** [flutter/flutter#32534]
Enviroment: Window10

1. I terminal 'flutter upgrade' to 1.5.4-hotfix02
2. I terminal `flutter create t module flutetr_module`,

But there is no  include_flutter.groovy file in .android fold.

Then I copy the include_flutter.groovy file from  other module  that before I upgrade(1.2.1-release) into the  .android fold, a error happened : `Unable to find a matching configuration of project :flutter: None of the consumable configurations have attributes.
`

How can I add Flutter module into old project since edition upgrade to 1.5.4-hotfix02.
Thanks.

**Comment by kangwang1988** [comment]
@YellowDoing 
I don't think this issue occurs in 1.5.4-hotfix02
<img width="1353" alt="Screen Shot 2019-05-12 at 11 11 22 PM" src="https://user-images.githubusercontent.com/817851/57584250-7f291680-750b-11e9-824e-f5ce57c968e6.png">

The include_flutter.groovy file is generated based on 'flutter1.5.4/packages/flutter_tools/templates/module/android/library/include_flutter.groovy.copy.tmpl'
You can check if that file exists in your flutter repo.
