### ISSUE TITLE
[tools] flutter devices should also print the observatory port #

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#3253]
Currently `flutter devices` only prints attached device names, device ids, and CPU architecture. What would be more relevant to a developer is the observatory # to connect to to debug an app running on a specific device.

Before

```
Nexus 9 • HT4A1JT02786                  • android-arm
iPhone  • a789dsf79d7sf98ds7f98sd7f98ds • ios
```

After:

```
Nexus 9 • HT4A1JT02786                  • android-arm • debug port: 8181
iPhone  • a789dsf79d7sf98ds7f98sd7f98ds • ios         • debug port: 8182
```

@devoncarew

**Comment by devoncarew** [comment]
Yeah, that would be useful. We don't track that info currently but we could. We probably also want to show the skia diagnostic port as well (and have commands, like `flutter observe`, to open pages to those ports).

**Comment by sethladd** [comment]
Yeah, even better is a `flutter -d Nexus observe` :)

**Comment by Hixie** [comment]
The specific request made here doesn't really make sense because there could be multiple apps, it would require some sort of broadcast message handled by running apps, it's not clear we could do that on iOS... Closing this for now. Please reopen if you have a specific need.
