### ISSUE TITLE
[web]: main.dart.js:443 Uncaught TypeError: Instance of 'minified:dZ': type 'minified:dZ' is not a subtype of type 'minified:y<String, dynamic>'

### ISSUE THREAD

**Issue by arrowoliver** [flutter/flutter#32539]
I tried to run a sample flutter web app and it works in the local machine but then i tried to prepare a build using the command "webdev build -r" and uploaded everything on a sample hosting service for testing only. But give the following error and it does not load any images i have added in the project

main.dart.js:443 Uncaught TypeError: Instance of 'minified:dZ': type 'minified:dZ' is not a subtype of type 'minified:y<String, dynamic>'
    at Object.i (main.dart.js:443)
    at Object.e (main.dart.js:794)
    at Ci.OE (main.dart.js:4729)
    at Gj.ow (main.dart.js:12915)
    at F7.$0 (main.dart.js:12506)
    at Object.jo (main.dart.js:1453)
    at a5.iQ (main.dart.js:12411)
    at jx.b_ (main.dart.js:12335)
    at q5.b_ (main.dart.js:12192)
    at Object.at (main.dart.js:1311)

**Comment by kevmoo** [comment]
Which sample app? Can you still reproduce this?

**Comment by arrowoliver** [comment]
@kevmoo  Thanks for checking up on this issue.
I will check and let you know.

**Comment by arrowoliver** [comment]
It looks fine.
You can close this task.

**Comment by yjbanov** [comment]
Cool. Thanks!

**Comment by dazza5000** [comment]
How did you resolve this?

**Comment by insinfo** [comment]
How did you resolve this?

**Comment by kevmoo** [comment]
@insinfo – what's your flutter version?

**Comment by insinfo** [comment]
@kevmoo 
thanks, already resolved on 2.8.0-20.11.beta

**Comment by arualana** [comment]
How did you resolve this?

**Comment by insinfo** [comment]
already resolved update dart SDK to ^ 2.8.0-20.11.beta
