### ISSUE TITLE
didChangeAppLifecycleState / AppLifecycleState.inactive

### ISSUE THREAD

**Issue by MrYunusOZ** [flutter/flutter#32547]
When I get back to the application, AppLifecycleState.inactive is triggered again after the build method. The code that needs to work while inactive is running at startup again :(

**Comment by kangwang1988** [comment]
@MrYunusOZ 
Can you provide a demo project and paste the result for `flutter doctor -v`?

**Comment by kangwang1988** [comment]
I'm closing this issue as it lacks of information to diagnose further.
@MrYunusOZ 
If you can provide more information, I will reopen it.
