### ISSUE TITLE
[web]: Document Integration Testing

### ISSUE THREAD

**Issue by eiswind** [flutter/flutter#32548]
Is flutter_driver working with the web version?
Please add some docs on that.

**Comment by chonghorizons** [comment]
I think flutter driver does not work with web version based on my try today.  I followed the instructions on 
https://flutter.dev/docs/cookbook/testing/integration/introduction

and tried to run it on Chrome as the device target. Did not work.

I made a video (2-3 minutes) just in case I did something dumb. Didn't work.
Video link is: (pending)

NOTE: Running flutter_driver with android target worked fine.

**Comment by angjieli** [comment]
Sure. I think that one is good enough to start with.

**Comment by angjieli** [comment]
Fixed in https://github.com/flutter/website/pull/3885.

**Comment by nturgut** [comment]
For anyone interested in more details, we prepared this wiki page: https://github.com/flutter/flutter/wiki/Running-Flutter-Driver-tests-with-Web
