### ISSUE TITLE
Icons are not getting rendered in Flutter Web

### ISSUE THREAD

**Issue by AyushBherwani1998** [flutter/flutter#32540]
I migrated my existing flutter application to flutter web. Everything is working fine but the icons are not getting rendered.
![Screenshot (5)](https://user-images.githubusercontent.com/34301187/57565647-f7de8480-73de-11e9-84e0-4b20f4ea5586.png)

**Comment by recvec** [comment]
If you mean that images are not displayed from assets, you can try to create **AssetManifest.json**.
I took the example from here 
https://github.com/GeekyAnts/FlatApp-Flutter/blob/master/ios/Flutter/flutter_assets/AssetManifest.json
The steps that I did:
1) move all my images from **./image** folder to **./web/assets/images.**
2) create AssetManifest.json in **./web/assets/** folder using this style:
`{
  "assets\/images\/googlephotos.png":[
    "assets\/images\/googlephotos.png"
  ],
  "assets\/images\/pinterest.png":[
    "assets\/images\/pinterest.png"
  ]

}`
3) load images using  **Image(image: AssetImage(path))** where path was like this **"images/googlephotos.png"**

**Comment by AyushBherwani1998** [comment]
No, I meant Material Icons are not getting rendered.

**Comment by ciokan** [comment]
Make sure to add 

```flutter:
  uses-material-design: true``` to your `pubspec.yaml` and also create a file `FontManifest.json` inside `web/assets` directory containing `[{"fonts":[{"asset":"fonts/MaterialIcons-Regular.ttf"}],"family":"MaterialIcons"}]`. Restart the server and it should work, it did for me after searching 3 hours yesterday.

**Comment by AyushBherwani1998** [comment]
Thank you. It worked.

**Comment by compiledcode** [comment]
Thank you Ciokan

Your solution worked for me too.

**Comment by RajeshKrSahoo** [comment]
Hi @ciokan I don't see any assets folder inside web folder.
 can you guide me to get the necessary list u mentioned to be present inside pls ?

**Comment by compiledcode** [comment]
You have to create the folder(s); I followed the original answer and used the manifest file to hook in the Material icons and it worked for me.

**Comment by abbadabbatech** [comment]
This works for material icon fonts, is there a way to get material icon images?  Like calendar_today, etc...

**Comment by Gene-Dana** [comment]
> MaterialIcons-Regular.ttf

Hey there ! where do I download this file??

**Comment by Gene-Dana** [comment]
Found it here ! 
https://www.cdnpkg.com/mdui/file/MaterialIcons-Regular.ttf/#

**Comment by jeffaknine** [comment]
> FontManifest

This doesn't work for me with Flutter 1.22.0-12.1.pre when releasing on NGINX

**Comment by puertojose** [comment]
> This doesn't work for me with Flutter 1.22.0-12.1.pre when releasing on NGINX


For anyone who is still having this problem. I finally found a solution that worked for me 😊.

In newer versions of Flutter were the original problem is already fix, your previous fix broke the Icons in the updated version, _let me explain:_

If you have tried a previous solution of adding MaterialIcons-Extended.ttf to assets/fonts/, and creating and/or updating FontManifest.json.

**Erase the font from assets/fonts/ and erase the FontManifest.json file you previously created.**
And of course be sure to have **uses-material-design: true** in the pubspec.yaml

Then `flutter clean` and you are good to go

It took me an incredible amount of time to fix this, hopefully this would help someone :)

**Comment by puertojose** [comment]
> Make sure to add
> 
> ```
> flutter:
>   uses-material-design: true
> ```
> 
> to your `pubspec.yaml` and also create a file `FontManifest.json` inside `web/assets` directory containing `[{"fonts":[{"asset":"fonts/MaterialIcons-Regular.ttf"}],"family":"MaterialIcons"}]`. Restart the server and it should work, it did for me after searching 3 hours yesterday.
> 
> Make sure to also download the `MaterialIcons-Regular.tff` font inside `web/assets/fonts` dir as well.

In newer versions you have to undo all these changes to make your Icons work in Flutter web again.

**Comment by andreagr** [comment]
I have an issue here, I am using FontManifest.json to also render my app's font.

If I remove it, as per @puertojose's suggestion, icons start working again but I lose my font styles. I'm in a deadlock here, any suggestion?

**Comment by WolveIT** [comment]
> > This doesn't work for me with Flutter 1.22.0-12.1.pre when releasing on NGINX
> 
> For anyone who is still having this problem. I finally found a solution that worked for me 😊.
> 
> In newer versions of Flutter where the original problem is already fix, your previous fix brakes the Icons in the updated version, _let me explain:_
> 
> If you have tried a previous solution of adding MaterialIcons-Extended.ttf to assets/fonts/, and creating and/or updating FontManifest.json.
> 
> **Erase the font from assets/fonts/ and erase the FontManifest.json file you previously created.**
> And of course be sure to have **uses-material-design: true** in the pubspec.yaml
> 
> Then `flutter clean` and you are good to go
> 
> It took me an incredible amount of time to fix this, hopefully this would help someone :)

Thank you so much!

**Comment by agavrel** [comment]
Be careful, the most upvoted solution is now obsolete as of 2021.
In my case I had forgotten to change the line:
```
static const _kFontFam = {your icon family name};
```
of the dart file.
