### ISSUE TITLE
[web]: Unnecessary auto restart

### ISSUE THREAD

**Issue by lucifer1004** [flutter/flutter#32544]
## Issue description

 `webdev` restarts when I clicked Cmd+S, even if there is no code change at all.

## Command used 

`webdev serve --auto restart`

## System information

- Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
- Framework • revision 7a4c33425d (12 days ago) • 2019-04-29 11:05:24 -0700
- Engine • revision 52c7a1e849
- Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
- Webdev • 2.0.5

**Comment by BondarenkoStas** [comment]
It think it's safe to close the issue, as webdev is not supported anymore after merging web to flutter/flutter repo.
