### ISSUE TITLE
☂️ Switch to Metal for macOS shell

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#32569]
Embedder and macOS embedding widely support metal (though its behind a gn flag). This issue tracks the remaining work items to make Metal the default rendering backend where supported on macOS.

- [x] https://github.com/flutter/flutter/issues/74056
- [x] https://github.com/flutter/flutter/issues/73826
- [x] https://github.com/flutter/flutter/issues/74058

### Prior to making an umbrella issue on 1/15/2020

Filing to track separately from #18208 since work will be needed to expose this though the embedding API. @chinmaygarde assigning to you since it seems like you're the best person to do this, having just done the Metal work for iOS and being very familiar with the embedding API, but let me know if that will be an issue.

I'm fine with turning Metal on by default for macOS immediately, which would be a way of getting a little bit more live testing of the Skia Metal backend before flipping the switch for iOS.

**Comment by chinmaygarde** [comment]
Depends on the [Embedder API exposing the Metal renderer config](https://github.com/flutter/flutter/issues/41811) before the Mac shell can use the same.

**Comment by MichelDiz** [comment]
Hey guys, (Quick question)

Context:
I'm using Flame Engine https://github.com/flame-engine/flame and I notice that above 3000 particles the FPS starts to fall. In 50k particles it drops to 6 FPS. In Chrome it can handle +50k okay. I believed as Flutter tries to perform natively, it would be better in cases like the Chrome (V8) engine itself.

The point is, would metal support be a deciding factor in Darwin's performance? The code I did the particle test uses almost nothing from the external video card (RX 580). It seemed to use more CPU than GPU. GPU processing under 10%.

The Flame Engine was by far the best engine that I tested these days using particles. No other engine or flutter code performed better than Flame. Even it using 10% of the GPU. That means there is a huge window to improvement.

I would like to have millions of particles dangling around with at least 30 FPS. I would ask that question in Flame repo, but as I researched it I realized that it is not an engine scope precisely.

Cheers.

**Comment by stuartmorgan** [comment]
If it's CPU-bound I would suspect the task queue thread sharing before this. Please file a new bug for your performance issue, since at this point there's no evidence that it's related to this issue.

**Comment by chinmaygarde** [comment]
Please provide a reduced test case (using Flame if necessary) for the performance issue. Drawing 3000 particles shouldn't be an issue using instanced rendering but I am not sure what Flame is doing. I'd be good to just get the traces to find out for sure.

**Comment by iskakaushik** [comment]
I have a prototype for this at: https://github.com/flutter/engine/pull/22606.

**Comment by stuartmorgan** [comment]
@iskakaushik Could you turn this into an umbrella bug with a checklist for issues tracking the follow-up work that's necessary to turn it on? (texture, smooth resize, etc.)

**Comment by iskakaushik** [comment]
@stuartmorgan done! I've edited the description of the issue to reflect the status.

**Comment by iskakaushik** [comment]
Metal is now the default rendering backend for macOS.

**Comment by iskakaushik** [comment]
See: https://github.com/flutter/flutter/issues/76710.
