### ISSUE TITLE
Expose the application messaging APIs on iOS

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#3256]
The Android implementation of FlutterView provides APIs for exchanging messages between the host application and the Flutter application.  These should also be supported on iOS.

Take a look at the sendToFlutter() and addOnMessagesListener() methods in Android FlutterView.  The messages are sent through a Mojo interface implemented by the host and the framework (sky/services/platform/app_messages.mojom)

**Comment by jason-simmons** [comment]
@chinmaygarde @eseidelGoogle

**Comment by abarth** [comment]
@chinmaygarde Are you actively working on this?  If not, I can give it a try.

**Comment by chinmaygarde** [comment]
No, I wasn't actively working on this.
