### ISSUE TITLE
[cloud_firestore] snapshots() are always returning all documents

### ISSUE THREAD

**Issue by RollyPeres** [flutter/flutter#32567]
Correct me if I'm wrong but doing 
```
someFirestoreQuery.snapshots()
    .map((snap) => snap.documentChanges)
```

or

```
someFirestoreQuery.snapshots()
    .map((snap) => snap.documents)
```

will end up in receiving both a `List<DocumentChange>` and a `List<DocumentSnapshot>`.

Shouldn't the two be available though separate listeners? Say for example `stateChanges` and `snapshotChanges` in Angular.

From the no. of document reads standpoint it would make a difference.
If anyone could clarify this would be cool. Thanks.

**Comment by larssn** [comment]
I'm pretty sure this is normal behavior in the core API's (Android/iOS), f.ex. check out the iOS documentation for `documentChanges` and `documents`: https://firebase.google.com/docs/reference/ios/firebasefirestore/api/reference/Classes/FIRQuerySnapshot

They are both present on the QuerySnapshot object.

AngularFire simply wraps this core logic in separate Rx functions to make it more reactive.

**Comment by RollyPeres** [comment]
Thanks for clarifying this @larssn
