### ISSUE TITLE
error while creating a web flutter project on VScode 

### ISSUE THREAD

**Issue by thierrylouppe** [flutter/flutter#32560]
> hello i have a problem when creating my project flutter web on VS code

- first mistake
every time I still have this prompt that asks me to download

'' Stagehand needs to be updated with 'Global Activate Stagehand' to use this feature. ''

- second mistake
see the catch
![erreur flutter](https://user-images.githubusercontent.com/29181160/57573315-c0db9380-741d-11e9-85e0-a871192995a0.png)
``

**Comment by MrMagloire** [comment]
If this can help you : https://www.didierboelens.com/2019/05/flutter-for-the-web/

**Comment by DanTup** [comment]
Could you run the **Dart: capture Logs** command (leave everything ticked), then reproduce this issue and then click **Stop Logging** in the notification and attach the log?

**Comment by pwlimaverde** [comment]
I had the same problem and could only solve it by activating the previous version of staghad - use the command: pub global activate stagehand 3.3.0
