### ISSUE TITLE
firebase phone authentication on dual sim phone

### ISSUE THREAD

**Issue by deepaksinghdangi** [flutter/flutter#32562]
On dual sim phone i am using firebase_auth 0.11.0 version, where i am doing otp verification and finding below problems,

1. I found that on one of the sim which is primary on phone is sending otp only once and subsequent verification is happening instantaneously without waiting for user entering the OTP.
Now I want that OTP should be sent always without instantaneous verification.

2. On the secondary Sim, I am getting OTP along with the instant verification happening both at the same time. Now interesting part is when I enter the OTP sent then it gave platform exception saying: OTP expired and resend is required.

Any help is appreciated.

Thanks in Advance.

**Comment by prabhuk56** [comment]
I am also facing the same in Phone Authentication. After entering OTP, throws a platform exception. @zoechi Any inputs will be helpful for us.

**Comment by BondarenkoStas** [comment]
@deepaksinghdangi can you confirm it's the same with current flutter stable and firebase_auth 0.14.0+5?

**Comment by kroikie** [comment]
@deepaksinghdangi

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1109. Any further collaboration will be done there.
