### ISSUE TITLE
CustomPainter inside Stack goes to zero

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3257]
Imagine you have a Stack inside a Container with a fixed height such that the Stacks incoming constraints are tight height, but bounded loose width. The stack will give its non-positioned children the same constraints.

If you then put a CustomPainter inside the stack, it'll go to zero width, which is weird and there's no obvious way to debug it.

Should we maybe make all the objects that go to smallest size (constrain size.zero) instead go to biggest size unless the incoming constraint is unbounded?

We could have BoxConstraints have a computeDefaultSize function that returns a Size that tends to zero for unbounded axes and tends to infinity for bounded axes. If we make every render box use it, it would be something you would come to expect throughout the platform. (It's what we already do for Flex.)

**Comment by abarth** [comment]
Looks like RenderCustomPaint inherits this behavior from RenderProxyBox, which inherits it from RenderBox's default performResize.

**Comment by Hixie** [comment]
This is probably too late to change. Closing.
