### ISSUE TITLE
intel x86 Emulator Accelerator 7.3.2 not compatible  

### ISSUE THREAD

**Issue by ashishKumarAgarwal** [flutter/flutter#32589]
I am not able to downgrade the emulator version, tried everything on the net. Please help me get started.
![haxm](https://user-images.githubusercontent.com/23659924/57586188-a58e8800-74f2-11e9-85c7-e54ef66d49af.PNG)

**Comment by ashishKumarAgarwal** [comment]
This is not letting me to use any virtual devices :(

**Comment by BondarenkoStas** [comment]
@ashishKumarAgarwal did you find a solution?

**Comment by ashishKumarAgarwal** [comment]
@BondarenkoStas Hey ! for me it turned out to be something related to the network and may be a restart, I was using my office laptop but was not in my organization's network . The very next day I stated looking in this issue but all was working fine ! Seems there were some network restrictions..I am not sure
