### ISSUE TITLE
please add PathEffect to the ui package

### ISSUE THREAD

**Issue by imaNNeoFighT** [flutter/flutter#32586]
Hi, as I migrated from Android native (Java / Kotlin), I familiar with some PathEffects, 
on Android, while drawing a path on the canvas, you can change the geometry of drawing a path with PathEffect.
like DashPathEffect (that draw our path as a dashed line) or CornerPathEffect (that round the sharp corners of our path).
I think we should have it in the flutter to implement fantastic UI.

**Comment by ethanblake4** [comment]
#4858

**Comment by imaNNeoFighT** [comment]
Okay Thanks, I will close it,

**Comment by joshliebe** [comment]
From what I can see, the linked issue only addresses support for `DashPathEffect` (Using `dashPath()` in the [path_drawing](https://pub.dev/packages/path_drawing) package). What is the equivalent to `CornerPathEffect`?
