### ISSUE TITLE
flutter 'share' plugin data sharing issue via whatsapp

### ISSUE THREAD

**Issue by pkmarathe** [flutter/flutter#32580]
I am using flutter 'Share' plugin in my app to share the content via platform like whats app , gmail etc.
When I am trying to send the more data to via gmail, it's working properly but via whats app, only some portion  of the data gets send.

If anybody have idea on this issue, please assist me.
Below is my code snippet.

StringBuffer strBuffer = StringBuffer();
for (int i = 0; i < shareNoteList.length; i++) 
 {
strBuffer.write('Title: ' +shareNoteList[i].title +'\n\nDescription: ' +shareNoteList[i].description +'\n\n\n');
}
Share.share('$strBuffer');

**Comment by kangwang1988** [comment]
@pkmarathe 
You want to share some pure text content, right?
What's exactly the content of `strBuffer` when this problem occurs?

**Comment by pkmarathe** [comment]
Yes. Content is like text notes.

**Comment by kangwang1988** [comment]
@pkmarathe 
I think it could be resulted from that other applications you want to share like Facebook may limit the text length.
I would recommend you to resolve this issue using other channels like Stackoverflow as it seems not a flutter issue.
