### ISSUE TITLE
[web]: canvas drawRRect does not stroke the top line

### ISSUE THREAD

**Issue by tnantoka** [flutter/flutter#32585]
I think that is caused by [this beginPath](https://github.com/flutter/flutter_web/blob/b3057c5b000e7a1ccc3588084fb24243f08966d6/packages/flutter_web_ui/lib/src/engine/bitmap_canvas.dart#L502).

### Code

```
class _MyPainter extends CustomPainter {
  @override
  bool shouldRepaint(_MyPainter oldDelegate) {
    return false;
  }

  @override
  void paint(Canvas canvas, Size size) {
    final Paint stroke = Paint()
      ..color = Colors.black
      ..style = PaintingStyle.stroke
      ..strokeWidth = 2;
    Rect rect = Rect.fromLTWH(0, 0, 100, 100);
    Radius radius = Radius.circular(10);
    RRect rrect = RRect.fromRectAndRadius(rect, radius);
    canvas.drawRRect(rrect, stroke);
  }
}
```

### Result

<img width="640" alt="Screen Shot 2019-05-12 at 23 20 04" src="https://user-images.githubusercontent.com/213169/57583564-856bc280-750c-11e9-8e65-4afe7934353a.png">

### flutter version

```
$ flutter --version
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (13 days ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```

### flutter_web version

Checked out [this commit](https://github.com/flutter/flutter_web/commit/b3057c5b000e7a1ccc3588084fb24243f08966d6).

**Comment by BondarenkoStas** [comment]
@tnantoka is it the same with current flutter master?

**Comment by tnantoka** [comment]
@BondarenkoStas 
It's fixed on current master 👍 

<img width="235" alt="Screen Shot 2019-10-12 at 22 03 13" src="https://user-images.githubusercontent.com/213169/66701884-1c4ade00-ed3c-11e9-9e3b-22e0dae750d2.png">
