### ISSUE TITLE
Create Skia colors in srgb

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3259]
https://github.com/flutter/engine/blob/master/sky/engine/core/painting/CanvasColor.cpp#L21
is the line to change.

Mike asked us to change to using sRGB, I don't know which exact API he had in mind without looking more.  cc @abarth

**Comment by abarth** [comment]
He said it was in the SkImageInfo struct we use when defining the surface that we draw into.

**Comment by eseidelGoogle** [comment]
OK, so presumably Mike wants this line changed:
https://github.com/flutter/engine/blob/f7909035f11b1347814ea2c2942426ef3cf7f44d/sky/shell/gpu/direct/ganesh_canvas.cc#L62
To pass an SkSurfaceProps which specifies we're OK with sRGB inputs?

**Comment by abarth** [comment]
Yeah, something like that.

**Comment by mikerreed** [comment]
Generically, Skia needs to be told that the buffer (surface or image) is to be treated as SRGB. If you are creating the buffer w/ SkImageInfo, just set fProfileType to kSRGB_SkColorProfileType. (in the future this will be SkColorSpace* we think).

For ganesh, there may be other specifics, so I defer to brian for those.

**Comment by bsalomon** [comment]
Nope, that's it.

You may need to communicate to the OS that the content you're producing is sRGB. Brian Osman found this WRT sRGB on iOS:  http://stackoverflow.com/questions/20769620/srgb-on-ios-opengl-es-2-0

"""
iOS 7.0 adds the new color format kEAGLColorFormatSRGBA8, which you can set instead of kEAGLColorFormatRGBA8 (the default value) for the kEAGLDrawablePropertyColorFormat key in the drawableProperties dictionary of a CAEAGLLayer.
"""

**Comment by eseidelGoogle** [comment]
@chinmaygarde @jason-simmons has this change already happened as part of our recent re-working in our Skia usage?  This was a long-ago ask from the Skia team.  No rush, just curious if we can already close this.

**Comment by chinmaygarde** [comment]
No. This hasn't happened yet. Will take a closer look this week.

**Comment by chinmaygarde** [comment]
I attempted this recently and kept running into https://bugs.chromium.org/p/skia/issues/detail?id=4148 on all iOS devices I could get my hands on. For now, I am postponing work on this till the linked issue is addressed.

**Comment by brianosman** [comment]
I just landed https://skia.googlesource.com/skia/+/9db12d2341f3f8722c8b90b11dd4cce138a8a64e, which should allow sRGB to work on most iOS devices. You will need to set a flag when creating the GrContext, though:

GrContextOptions options;
options.fRequireDecodeDisableForSRGB = false;
... = GrContext::Create(..., options);

**Comment by chinmaygarde** [comment]
That change was reverted in https://skia.googlesource.com/skia/+/0a2782c98c45127a10d6392c539e7bce72dc5513. I will patch that in locally and check on iOS.

**Comment by brianosman** [comment]
Yes - sorry. Let me know how the testing goes, though.

**Comment by brianosman** [comment]
FYI: This re-landed (twice), but finally stuck:
https://skia.googlesource.com/skia/+/20471894eaa441193d5ae8f2395e8244c91c55af

**Comment by eseidelGoogle** [comment]
Does this affect API stability?

**Comment by chinmaygarde** [comment]
> Does this affect API stability?

No.

Also, that reminds me to land the patch I had stashed waiting for the Skia patch to stick.

**Comment by Hixie** [comment]
@chinmaygarde Did this ever land?
