### ISSUE TITLE
sms plugin, permission denied by Play Store

### ISSUE THREAD

**Issue by DjivaCanessane** [flutter/flutter#32594]
Hello, 
I am trying to publish my app, which is using SMS: ^0.2.4, on the Play Store.
In my androidManifest.xml file I have declared that my app requires three permissions:

```
<uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
```

When I upload it on the play console, it tells me that I have to declare 3 other sensitive permission:

android.permission.READ_SMS
android.permission.SEND_SMS
android.permission.RECEIVE_SMS

I think it's due to the SMS plugin, and I need it to invite other users to join my app.
I receive this mail from Google: 
<img width="836" alt="Capture d’écran 2019-05-12 à 02 09 02" src="https://user-images.githubusercontent.com/50156885/57576241-0cf8f900-745b-11e9-82dc-b7567719b577.png">
Could someone help me with this issue please ?

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.5.8, on Mac OS X 10.14.5 18F131a, locale fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.33.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.`

**Comment by MichaelMarner** [comment]
The Play Store has some fairly restrictive policies over SMS and call permissions:

https://play.google.com/about/privacy-security-deception/permissions/

my guess is this has something to do with the `RECEIVE_SMS` permission - do you really need it?

If what you're trying to do is invite users to your app, you may be better off with the share plugin, which will launch the platform's share functionality:

https://pub.dev/packages/share

**Comment by ericel** [comment]
Did you ever solve this? I removed the permission from my app but unfortunately, I keep getting app reject cause of permissions sms.
