### ISSUE TITLE
[web]: HttpClient is almost fake

### ISSUE THREAD

**Issue by zhangruiyu** [flutter/flutter#32599]
Please implement HttpClient. The network request cannot be sent now! 0-0

**Comment by kevmoo** [comment]
Use `pkg:http` – `HttpClient` is from `dart:io` which doesn't work on the web.

**Comment by zhangruiyu** [comment]
pkg:http is not available

**Comment by zhangruiyu** [comment]
pkg:http is not available

**Comment by skreborn** [comment]
@zhangruiyu What do you mean "not available"? It's right [here](https://pub.dev/packages/http).
