### ISSUE TITLE
Cannot Build Release APK, Execution failed for task ':firebase_analytics:verifyReleaseResources'.

### ISSUE THREAD

**Issue by smholsen** [flutter/flutter#32595]
## My Problem
I have a flutter app which uses Firebase and Firebase analytics libraries. The specific implementation can be found below in "Steps to Reproduce".

When I try to run "flutter build apk", I get the following output:

```
>flutter build apk
Initializing gradle...                                              0.5s
Resolving dependencies...                                           2.2s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_analytics:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  C:\***\build\firebase_analytics\intermediates\res\merged\release\values\values.xml:276: error: resource android:attr/fontVar
iationSettings not found.
  C:\***\build\firebase_analytics\intermediates\res\merged\release\values\values.xml:277: error: resource android:attr/ttcInde
x not found.
  error: failed linking references.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                       2.6s
Gradle task assembleRelease failed with exit code 1
```
I assume the problem has to do with AndroidX migration, but it runs without problem with "flutter run". 

If I try to click in Android Studio on: Refactor -> Migrate to AndroidX, I get the following error message:

`You need to have compileSdk set to at least 28 in your module build.gradle to migrate to AndroidX`

My android/app/build.gradle looks like this, where the compileSdk is already set to 28:

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "**.***.***"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
apply plugin: 'com.google.gms.google-services'  // Google Play services Gradle plugin
```

Any tips on how to further debug and resolve this issue would be immensely appreciated.

## Steps to Reproduce

I am unable to reproduce the issue in a new flutter project, but I am unable to understand where my issue might lie. Below is the relevant changes I have done in my project. 

1. Create a new Flutter App
2. Edit pubspec.yaml to include 

```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.2.5  # add dependency for Firebase Core
  firebase_analytics: ^1.0.4  # add dependency for Google Analytics for Firebase
```
3. Edit android/gradle/wrapper/gradle-wrapper.properties to have:
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip`

4. Edit android/build.gradle to include 

```
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath 'com.google.gms:google-services:3.2.1'  // Google Services plugin
    }
}

allprojects {
    repositories {
        google()
        jcenter()

    }
}
```

5. edit android/app/build.gradle to include at the bottom

`apply plugin: 'com.google.gms.google-services'  // Google Play services Gradle plugin`

6. edit android/app/build.gradle and change the bottom dependencies to :

```
dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
```

7. Create a Firebase test project, link it to the app, and include the google-services.json file

8. Run flutter build apk

```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.475], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at C:\src\flutter
    • Framework revision 7a4c33425d (13 days ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\***\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    <removed>

! Doctor found issues in 1 category.
```

**Comment by smholsen** [comment]
Upon further inspections I can see that the file that the error is complaining about in the error
(` C:\***\build\firebase_analytics\intermediates\res\merged\release\values\values.xml`)
is different in my app, than the one in the new app I made where the build succeeded, even with the same version no, in pubspec.yaml (
`firebase_analytics: ^1.0.4  # add dependency for Google Analytics for Firebase`
)

In pubspec.lock however, the libraries seem to be the similar version, where both show this;
```
  firebase_analytics:
    dependency: "direct main"
    description:
      name: firebase_analytics
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0+1"
```

How can it be that the two files are then different?
I have tried running 'flutter clean', I have tried deleting the .gradle folder, and I have also tried invalidating caches and restarted Android Studio.

**Comment by smholsen** [comment]
So, I found out that the cause was the 
`android.useAndroidX=true` flag in project gradle.properties.

Does this mean that I cannot use Firebase Analytics in Flutter with AndroidX, so that I can use libraries that require AndroidX?

**Comment by smholsen** [comment]
I need to use AndroidX, as my app depends on sqflite (https://pub.dev/packages/sqflite), which breaks the build if AndroidX is not enabled. 

I did find a work-around for the issue, but I worry that it may not be a good solution. The work-around is simply to modify the gradle script of firebase_core and firebase_analytics, and change the compileSdkVersion from 27 to 28. 
Can any of you give me some input on whether this workaround is viable or not?

Workaround Steps:

1. In Android Studio (with your project open) right click the android folder, and click "Flutter"->"Open Android Module in Android Studio". Select "Open in New Window"

2. In the new window, expand "Gradle Scripts"

3. Locate "build.gradle (Module: firebase_core)" and "build.gradle (Module: firebase_analytics)"

4. In each of the two gradle scripts, modify the compileSdkVersion from 27->28.

5. Save the changes and build the signed apk (release version). 


Are there any drawbacks to using this method?

**Comment by JoseGeorges8** [comment]
Hey I just got the same issue you're facing with the exact same use case. I need sqflite in my project and I got both firebase_core and firebase_analytics. Error message is the same.

I used your steps and effectively the build got completed so I thank you for that. However I'm not sure if this is a viable workaround. I would assume the two packages need to be updated to have compile sdk version to 28 and it is okay until this change happens. 

I'll leave it as this for now

**Comment by sabdelhay** [comment]
Hey,
Try this solution, it worked for me
https://github.com/flutter/flutter/issues/29879#issuecomment-504657507

**Comment by devibrahimkarahan** [comment]
i was getting same error, i fixed it with `firebase_analytics: ^5.0.2`

**Comment by BondarenkoStas** [comment]
Good, I think it's safe to close the issue.

**Comment by Basher7** [comment]
I have a different task when i run flutter build apk
This error raise after I upgrade flutter stable version 1.9.1+hotfix.6 to 1.12.13+hotfix.5

**Error Description**

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':keyboard_visibility:verifyReleaseResources'.
> > java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
>   D:\Development\Node JS\XpertMemos\XpertMemo_flutter\build\keyboard_visibility\intermediates\res\merged\release\values\values.xml:236: error: resource android:attr/fontVariationSettings not found.
>   D:\Development\Node JS\XpertMemos\XpertMemo_flutter\build\keyboard_visibility\intermediates\res\merged\release\values\values.xml:237: error: resource android:attr/ttcIndex not found.
>   error: failed linking references.
> 
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4m 14s
> Running Gradle task 'assembleRelease'...
> Running Gradle task 'assembleRelease'... Done                     255.3s (!)
> Gradle task assembleRelease failed with exit code 1

**Comment by sayhicoelho** [comment]
here facing with the same issue with the lib adaha_socket_io:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':adhara_socket_io:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  D:\***\build\adhara_socket_io\intermediates\res\merged\release\values\values.xml:236: 
error: resource android:attr/fontVariationSettings not found.
  D:\***\build\adhara_socket_io\intermediates\res\merged\release\values\values.xml:237: 
error: resource android:attr/ttcIndex not found.
  error: failed linking references.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                       4,9s
Gradle task assembleRelease failed with exit code 1
```

**Comment by sayhicoelho** [comment]
I've fixed by changing the compileSdkVersion from adaha_socket_io using the @adrianvintu approach: https://github.com/adee42/flutter_keyboard_visibility/issues/42#issuecomment-566656630

**Comment by bmabir17** [comment]
I was facing the following error
```
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':socket_flutter_plugin:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed                                    
     /home/bmabir/.gradle/caches/transforms-2/files-2.1/8f7c2c55dc7bcef81fffc05ed3dfa051/support-compat-28.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
                                                                        
     /home/bmabir/.gradle/caches/transforms-2/files-2.1/8f7c2c55dc7bcef81fffc05ed3dfa051/support-compat-28.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
```

> I've fixed by changing the compileSdkVersion from adaha_socket_io using the @adrianvintu approach: adee42/flutter_keyboard_visibility#42 (comment)
@sayhicoelho Thaks for the solution. it worked.

**Comment by elsanal** [comment]
Wow , smholsen's approach is working perfectly . Thank you very much

**Comment by szepetry** [comment]
> I need to use AndroidX, as my app depends on sqflite (https://pub.dev/packages/sqflite), which breaks the build if AndroidX is not enabled.
> 
> I did find a work-around for the issue, but I worry that it may not be a good solution. The work-around is simply to modify the gradle script of firebase_core and firebase_analytics, and change the compileSdkVersion from 27 to 28.
> Can any of you give me some input on whether this workaround is viable or not?
> 
> Workaround Steps:
> 
> 1. In Android Studio (with your project open) right click the android folder, and click "Flutter"->"Open Android Module in Android Studio". Select "Open in New Window"
> 2. In the new window, expand "Gradle Scripts"
> 3. Locate "build.gradle (Module: firebase_core)" and "build.gradle (Module: firebase_analytics)"
> 4. In each of the two gradle scripts, modify the compileSdkVersion from 27->28.
> 5. Save the changes and build the signed apk (release version).
> 
> Are there any drawbacks to using this method?

Was having the same issue with YouTube API package. This fixed it. Thanks a tonn. :D
