### ISSUE TITLE
Widget tests fails with 'Unable to load asset' in 1.5.4-hotfix.2

### ISSUE THREAD

**Issue by svprdga** [flutter/flutter#32609]
I have a flutter plugin project in which I have screens in which I load some assets, like this:

```
Image.asset('res/icon/ic_arrow_back.png',
                width: 54,
                height: 54,
                fit: BoxFit.none,
                package: 'common_library')
```

When I run the application normally everything works fine, but when I try to execute some widget tests it outputs the following error:

> The following assertion was thrown resolving an image codec:
> Unable to load asset: packages/common_library/res/icon/ic_arrow_back.png

This tests were working ok in version 1.2.1 but now they seem to fail.

My pubspec.yaml:

```
flutter:
  uses-material-design: true
  plugin:
    androidPackage: com.xxx.commonlibrary
    pluginClass: CommonLibraryPlugin
  assets:
    - res/image/
    - res/icon/
```

My doctor:

> [✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
>     • Flutter version 1.5.4-hotfix.2 at /home/dserrano/opt/flutter
>     • Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
>     • Engine revision 52c7a1e849
>     • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /home/dserrano/Android/Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • ANDROID_HOME = /home/dserrano/Android/Sdk
>     • Java binary at: /opt/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
>     • All Android licenses accepted.
> 
> [✓] Android Studio (version 3.4)
>     • Android Studio at /opt/android-studio
>     • Flutter plugin version 35.3.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
> 
> [✓] IntelliJ IDEA Community Edition (version 2019.1)
>     • IntelliJ at /opt/idea
>     • Flutter plugin version 35.2.3
>     • Dart plugin version 191.7019
> 
> [✓] VS Code (version 1.33.1)
>     • VS Code at /usr/share/code
>     • Flutter extension version 3.0.0
> 
> [✓] Connected device (1 available)
>     • SM G930F • ad051602392a4a8260 • android-arm64 • Android 7.0 (API 24)
> 
> • No issues found!

**Comment by mo-fu** [comment]
My tests work again, when using `flutter test --no-test-assets` from the CLI.

**Comment by svprdga** [comment]
Thanks @mo-fu , I can run the tests with the above command without issues.

**Comment by mo-fu** [comment]
@svprdga Maybe you can reopen the issue because I still can not run tests from Android Studio.

**Comment by svprdga** [comment]
But the tests can be run from the CLI, maybe this is more an Android Studio configuration issue than a Flutter issue ?

**Comment by chunhtai** [comment]
This sounds like a valid bug, we should fix this.

**Comment by chunhtai** [comment]
@svprdga I cannot reproduce it locally, Do you mind share a reproducible example?

**Comment by svprdga** [comment]
Sure @chunhtai https://github.com/svprdga/flutter-issue-32609

Just run the tests in test/flutter_issue_32609.dart with **flutter test** and **flutter --no-test-assets** to see the diference.

**Comment by chunhtai** [comment]
Thanks @svprdga  I will look into it

**Comment by chunhtai** [comment]
After some investigation, I found out two issues.
The first issue is when running test within the plugin that has a widget that depends on assets in the plugin, the assets loader do not know how to look up the key with its packages name append to it. All it knows is the relative path to its asset. It you run the test in the app that use the plugin, it should pass. This is something we should fix.

The second issue is not related to this bug, it is rather a regression of the fix https://github.com/flutter/flutter/pull/31804. When you do not declared assets in pubspec.yaml, it will not build any test assets during unit test. This would cause some issue when you actually need assets from other package that declare in other package.
