### ISSUE TITLE
iOS app dont wipe data after reinstall

### ISSUE THREAD

**Issue by Arkuda** [flutter/flutter#32604]
App using firebase auth. After reinstall, user still authorized.

## Steps to Reproduce

1. Install app from TestFlight/Direct
2. Authorize from firebase auth (using email)
3. Close and delete app
4. Install app from TestFlight/Direct
5. User still authorized

```
```
`[✓] Flutter (Channel beta, v1.5.4, on Mac OS X 10.14.4 18E226, locale ru-RU)
    • Flutter version 1.5.4 at /Users/kiryantsev.a/Documents/FlutterSdk/flutter
    • Framework revision b593f5167b (3 weeks ago), 2019-04-22 07:51:33 -0700
    • Engine revision ca31a7c57b
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 cf4444b803)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kiryantsev.a/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/kiryantsev.a/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ ideviceinstaller is not installed; this is used to discover connected iOS devices.
      To install with Brew, run:
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] Android Studio (version 3.4)
    • Android Studio at /Users/kiryantsev.a/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    • IntelliJ at /Users/kiryantsev.a/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 35.0.3
    • Dart plugin version 191.7019

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.26.1
`

```
```

**Comment by StefanLobbenmeier** [comment]
I think this is a feature:

I found this in a forum:

> If your credentials are stored in the shared keychain then it will stay on the device even when you delete the app.
> 
> I’m guessing they store the oAuth token on the device and unless the token expires you’re able to be logged in with the same token. There’s nothing sketchy about it.

https://forums.macrumors.com/threads/deleting-app-doesnt-delete-data.2166184/#post-27019019
