### ISSUE TITLE
flutter state constructor not fired

### ISSUE THREAD

**Issue by Liashui** [flutter/flutter#32606]
1.Open flutter from iOS,AboutPageState() not called,"hello" does not show in xcode console,_getAppVersion is not called,but the flutter page presents.

2.Open flutter directly using AndroidStudio,everything is right.

## iOS code
```
FlutterEngine *flutterEngine = [[WMUtils getApplicationDelegate] flutterEngine];
FlutterViewController *flutterViewController = [[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil];
[self.navigationController pushViewController:flutterViewController animated:YES];
self.navigationController.navigationBar.hidden = YES;
FlutterMethodChannel* batteryChannel = [FlutterMethodChannel
                                                    methodChannelWithName:@"samples.flutter.io/appInfo"
                                                    binaryMessenger:flutterViewController];
[batteryChannel setMethodCallHandler:^(FlutterMethodCall* call, FlutterResult result) {
      if ([@"getAppVersion" isEqualToString:call.method]) {
          result([WMUtils getAppVersion]);
      } else if ([@"hiddenNavigationBar" isEqualToString:call.method]) {
          self.navigationController.navigationBar.hidden = YES;
      } else if ([@"navigatorPop" isEqualToString:call.method]) {
          self.navigationController.navigationBar.hidden = NO;
          [self.navigationController popViewControllerAnimated:YES];
      } else {
           result(FlutterMethodNotImplemented);
      }
}];
```

## flutter code
```
const platform = const MethodChannel('samples.flutter.io/appInfo');
class AboutPage extends StatefulWidget {
  AboutPageState createState() => AboutPageState();
}

class AboutPageState extends State<AboutPage> {
  AboutPageState() {
   print("hello");
    _getAppVersion();
  }

  String _appVersion = '';
  Future<Null> _getAppVersion() async {
    String appVersion;
    try {
      appVersion = await platform.invokeMethod('getAppVersion');
    } on PlatformException catch (e) {
    }
    setState(() {
      _appVersion = 'Version $appVersion';
    });
  }
  Widget build(BuildContext context) {
     ...
  }
}
```

## Logs
flutter doctor -v

[✓] Flutter (Channel dev, v1.5.8, on Mac OS X 10.14.1 18B75, locale zh-Hans-CN)
    • Flutter version 1.5.8 at /Users/MoMo/flutter
    • Framework revision 0ba67226ee (3 weeks ago), 2019-04-24 17:18:28 -0700
    • Engine revision c63d1cf9c9
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/MoMo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/MoMo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
```

**Comment by kangwang1988** [comment]
@Liashui 
A minimal demo project which can reproduce this issue could be better than this code snippets.
