### ISSUE TITLE
Dependency file generated by sky_snapshot is broken

### ISSUE THREAD

**Issue by alhaad** [flutter/flutter#3260]
The dependency file generated by sky_snapshot is producing incorrect filepaths for pub dependencies. 
For example, dependency file of a 'color displayer' flx that we generate looks like `/path/to/color/displayer/package:newton/newton.dart` instead of `/path/to/color/displayer/packages/newton/newton.dart`.

https://github.com/flutter/engine/commit/ff9af06e26a25ea96a4812becfbc9f313952d651 might have broken it.

**Comment by abarth** [comment]
Looks like this broke as part of the package URI cannonicalization change.

@johnmccutchan
