### ISSUE TITLE
Support for In-app update api for android 

### ISSUE THREAD

**Issue by harshapulikollu** [flutter/flutter#32619]
As google released In-app update API, add support or plugin in order to support that API.

**Comment by 0-php** [comment]
i thik flutter can't support this

**Comment by audkar** [comment]
> i thik flutter can't support this

I thik it can...

Can you elaborate more with details why Flutter couldn't do this? 
`flexible` mode is just API callbacks + onActivityResult 
`immediate` is onActivityResult + new Activity

**Comment by stuartmorgan** [comment]
Based on the updated guidance in https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues, I'm going to close this issue, better reflecting the expectation that this is not something that the Flutter team plans to implement.
