### ISSUE TITLE
How to draw path from my location to another using Google map in flutter?  

### ISSUE THREAD

**Issue by shrutiramnandan** [flutter/flutter#32615]
I wanna draw route  from  my location to another in flutter.

here the piece of code

  @override
  Widget build(BuildContext context) {
     markers.addAll([
     Marker(
      markerId: MarkerId('value'),
      position: LatLng(30.698930 , 76.691713),
      infoWindow: InfoWindow(title: "Vista Tower")
      ),
   ]);
    return new Scaffold(
      appBar: AppBar(
        title:  new Text("GoogleMap"),
      ),
      body:Container(
        child: GoogleMap(
          myLocationEnabled: true,
          mapType: MapType.hybrid,
          onMapCreated: onMapCreated, 
          initialCameraPosition: CameraPosition(
           target: center,
           zoom: 11.0 
         ),
         markers:  markers
        ),
      ),
    );
  }

**Comment by shivarajnaidu** [comment]
How to draw the line to my live moving path ?

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
