### ISSUE TITLE
open an app with flutter alarm manager

### ISSUE THREAD

**Issue by MortezaHatamiKia** [flutter/flutter#32617]
is flutter android alarm manager plugin can open an app ?

i'm try to create a reminder app but android alarm manager plugin just can print some things not any more !

### Main Code :

```
void main() async {
  final int helloAlarmID = 0;
  await AndroidAlarmManager.initialize();
  runApp(new MaterialApp(home: MyApp()));
  await AndroidAlarmManager.periodic(const Duration(minutes: 1), helloAlarmID,appRunner);
}
appRunner() {
  return runApp(new MaterialApp(home: new AlarmShow()));
}
```
### Alarm Show Class :
```
class AlarmShow extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      backgroundColor: Colors.red,
      body: new Center(
        child: new Column(
          children: <Widget>[
            new Text('alarm'),
            new Icon(Icons.alarm)
          ])));
  }
}
```
I expect this show AlarmShow class but it not

Does anyone know how to solve this problem ?

**Comment by miDeb** [comment]
Maybe show a notification (your app will launch when the user taps on it)?

**Comment by MortezaHatamiKia** [comment]
> Maybe show a notification (your app will launch when the user taps on it)?

It's a good idea thank you , but I want to show a screen not a notification, I want to show a screen and start music then repeat music until the user stop that with a button, unfortunately, apparently still does not support
and I have to use the notification

**Comment by miDeb** [comment]
Since your code runs in the background I don't think there is a way to do this from flutter directly. However, you could try to start your app from the native side when an alarm is fired. https://stackoverflow.com/questions/7050027/how-do-you-start-an-activity-with-alarmmanager-in-android (I haven't tried that)

**Comment by MortezaHatamiKia** [comment]
**thanks a ton**

**Comment by AmanNegi** [comment]
Well that does solve the problem but what about going to the flutter code back with data afterwards is that possible??

**Comment by IvanKaloyanov** [comment]
Are there any plans to put this into the plugin so that there is no need to mess with the native code or there are some restrictions for doing it?

**Comment by shinewanna** [comment]
how can i pass inputData to appRunner function?
