### ISSUE TITLE
Blank screen when adding a FlutterView for the second time to ViewGroup on Android

### ISSUE THREAD

**Issue by chip2n** [flutter/flutter#32624]
It seems that `FlutterView` does not render properly when it is added for the second time to a `ViewGroup` (in our case when Conductor controllers are detached and later attached again). This also happens when the parent container is removed from the hierarchy and later added again. We can work around this by recreating the `FlutterView` each time this happens, but that doesn't seem like a good permanent solution.

## Steps to reproduce

1. Create a `FlutterView` and attach it to the `FlutterEngine`
2. Add the `FlutterView` to a container
3. Remove the `FlutterView` from the container
4. Add the `FlutterView` to the container again
   
The second time the `FlutterView` is added, there's nothing rendered. In some cases we've also seen a black screen.
   
Here's some Android code to reproduce this issue - in this case an activity containing a FrameLayout and a button. Pressing the button adds the `FlutterView` to the container if it isn't there already, otherwise it removes the view from the container.

```kotlin
import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import io.flutter.embedding.android.FlutterView
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.embedding.engine.FlutterShellArgs
import io.flutter.embedding.engine.dart.DartExecutor
import io.flutter.facade.Flutter
import io.flutter.view.FlutterMain
import kotlinx.android.synthetic.main.activity_main.*

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        Flutter.startInitialization(applicationContext)
        val shellArgs = FlutterShellArgs(arrayOf<String>())
        FlutterMain.ensureInitializationComplete(applicationContext, shellArgs.toArray())

        val engine = FlutterEngine(this).apply {
            navigationChannel.setInitialRoute("/")
            val appBundlePath = FlutterMain.findAppBundlePath(applicationContext)
            val entrypoint = DartExecutor.DartEntrypoint(resources.assets, appBundlePath, "main")
            dartExecutor.executeDartEntrypoint(entrypoint)
        }

        val flutterView = FlutterView(this, FlutterView.RenderMode.texture).apply {
            attachToFlutterEngine(engine)
        }

        button.setOnClickListener {
            if (flutterContainer.childCount == 0) {
                flutterContainer.addView(flutterView)
            } else {
                flutterContainer.removeView(flutterView)
            }
        }
    }
}
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <Button
        android:id="@+id/button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Press me"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <FrameLayout
        android:id="@+id/flutterContainer"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

## Logs

Here's the flutter doctor output:
```
[✓] Flutter (Channel master, v1.5.9-pre.223, on Linux, locale en_US.UTF-8)
    • Flutter version 1.5.9-pre.223 at /home/chip/flutter
    • Framework revision b76a1e8312 (6 hours ago), 2019-05-13 09:06:30 +0100
    • Engine revision 816d3fc586
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/chip/android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.3)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] Android Studio
    • Android Studio at /home/chip/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (1 available)
    • SM G930F • ce081718cde4393e01 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 2 categories.
```

**Comment by jason-simmons** [comment]
This is happening because the engine thinks that it's in a paused state when the FlutterView is added back to the container.

The animator is stopped when the `FlutterView` is removed from the container and loses its rendering surface.  When the `FlutterView` is added back, it gets a new rendering surface and notifies the engine.  But the engine's `activity_running_` flag is false - it was set to false during construction and never updated by the embedder.  Thus, `Engine::StartAnimatorIfPossible` does not restart the animator, and no more frames are rendered.

This app works if I patch the `Engine` constructor to set `activity_running_` to true by default.

`FlutterView` does render frames when it is initially constructed because the `paused_` flag in `Animator` defaults to false.  The asymmetry between `Engine::activity_running_` and `Animator::paused_` at startup seems wrong - `Engine::activity_running_` says the activity is paused but `Animator::paued_` says that the animator is running.

@matthew-carroll @chinmaygarde What do you think would be the best solution here?

Potential options:
  * default `Engine::activity_running_` to true
  * default `Animator::paused_` to false and wait for the embedder to send a lifecycle message that starts the animator

**Comment by matthew-carroll** [comment]
@jason-simmons isn't this just a situation where the required contract is not being fulfilled?

The reason we have `FlutterFragment` and `FlutterActivity` is to forward calls at the right time. The following are all required lifecycle calls:

https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterFragment.java#L556

https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterFragment.java#L576

https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterFragment.java#L583

Without those calls, one should not expect correct behavior.

**Comment by chip2n** [comment]
Yep, calling those results in the correct behavior.

```kotlin
activity.lifecycle.addObserver(object: LifecycleObserver {
    @OnLifecycleEvent(Lifecycle.Event.ON_RESUME)
    fun onResume() {
        lifecycleChannel.appIsResumed()
    }

    @OnLifecycleEvent(Lifecycle.Event.ON_PAUSE)
    fun onPause() {
        lifecycleChannel.appIsInactive()
    }

    @OnLifecycleEvent(Lifecycle.Event.ON_STOP)
    fun onStop() {
        lifecycleChannel.appIsPaused()
    }
})
```

I suggest noting this in the documentation (when the new API is stabilized of course). Perhaps also adding an optional `Lifecycle` parameter in the constructor of `FlutterEngine` that calls the code above, or a method on the `LifecycleChannel` that hooks things up properly given a `Lifecycle`?

Anyways, I think it's safe to close this. Thanks, and keep up the awesome work!

**Comment by matthew-carroll** [comment]
Thanks for verifying.

**Comment by jason-simmons** [comment]
The concern is the inconsistency between the engine's default state and the animator's default state.

If you construct a `FlutterEngine` and never send a lifecycle message, then what app lifecycle state is the `FlutterEngine` in?

Right now, on the native code side the `Engine` object acts like it is in the `AppLifecycleState.paused` state, but the `Animator` object acts like it is in the `AppLifecycleState.resumed` state.  This can lead to counterintuitive behavior until you send a lifecycle message that brings the two sides into matching states.

Or is the policy that `FlutterEngine` is in an undefined state until you explicitly send a lifecycle message?

**Comment by matthew-carroll** [comment]
@jason-simmons I think that at this moment the `FlutterEngine` would probably be considered in an undefined state. However, I'm happy to reconsider that and make appropriate changes.

I'm not educated on the internal impact and relevance of the lifecycles within the engine, e.g., `Engine` object vs `Animator` object. Can you think of any reasons with regard to edge cases like testing, etc. where having a different `Animator` state might be important?

If the `Engine` and `Animator` can be synced WRT to lifecycle without hurting other expected behaviors then I would think that's a good change to make. Would that require any embedding changes or just engine changes?

Also, I'm not sure if it's relevant, but I think even if the Flutter rendering pipeline is running, a developer should be able to execute arbitrary Dart code without sending lifecycle events into the engine. Do you know if that's the case today? I assumed it was, but I never verified.
