### ISSUE TITLE
Slider Label is cutted in ExpansionPanel

### ISSUE THREAD

**Issue by kay4ik** [flutter/flutter#32621]
When I using a Slider in a Expansion Panel the Label is cutted at the Top so i cant see it.

The Workaround would be to wrap the slider in a Container or SizedBox and give it a Height but then the expanded Panel shows to much whitespace.

# Example:
You can See this Error in the [Flutter Gallery](https://github.com/flutter/flutter/tree/master/examples/flutter_gallery) at ExpansionPanelDemo

**Comment by shihaohong** [comment]
Sharing a screenshot to clarify hidden Slider label.

<img width="379" alt="Screen Shot 2019-05-13 at 8 14 56 AM" src="https://user-images.githubusercontent.com/27032613/57632794-38f9a480-7557-11e9-8216-a077b87e8f7e.png">

**Comment by shihaohong** [comment]
Also, this seems to be a duplicate of https://github.com/flutter/flutter/issues/31042
