### ISSUE TITLE
Annotate MethodChannel on Android with @UiThread

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#32623]
Today the methods on `MethodChannel` are the public API often used by plugin developers and advanced users. There is no indication that these methods are supposed to be called from the UI thread even though the mechanisms they rely on in `FlutterJNI.java` are marked as such.

Let's mark them as @UiThread such that this is less of a surprise for developers.

Tracked internally at: b/132204137

**Comment by matthew-carroll** [comment]
Closed via https://github.com/flutter/engine/pull/8947
