### ISSUE TITLE
[web]: <Unable to access flutter PWA over network>

### ISSUE THREAD

**Issue by aHalyk** [flutter/flutter#32629]
Currently using the web release of flutter with the hello world sample but I am unable to connect to the computer running the PWA with another device on the same network.

Changed the url from localhost to the IP of the device but that did no good. I am sure it is possible to do just it is not clear anywhere as how to go about this

**Comment by aHalyk** [comment]
![Capture](https://user-images.githubusercontent.com/44567845/57637121-95b98700-7578-11e9-8595-8212bad7508e.PNG)
Above image works
Below image does not
![Capture](https://user-images.githubusercontent.com/44567845/57637156-af5ace80-7578-11e9-9abe-d3f8692c03a2.PNG)

**Comment by skreborn** [comment]
Have you tried using `webdev serve --host=0.0.0.0` so that the server wouldn't be bound to `localhost`?

**Comment by aHalyk** [comment]
@skreborn Sorry where exactly do I add that to my flutter code, currently using VScode on a windows device. I tried finding info on where to add that like I would if I was using angular but I couldn't find anything on it. I would greatly appreciate the help

**Comment by skreborn** [comment]
In VSCode, you should be able to use the dart-lang plugin to start the web server. To set the host, edit your `.vscode/launch.json` and add `[ '--hostname', '0.0.0.0' ]` to your `args`.

```text
{
    ...
    "configurations": [
        {
            ...
            "args": [ "--host", "0.0.0.0" ],
        }
    ]
}
```

_This is entirely untested, so I can't tell if it will actually work, but I scoured through the code that calls `webdev` and this seems to be the way to go.

**Comment by aHalyk** [comment]
There wasn't a launch.json file so I added it under the .vscode directory but no luck.

I feel like its something u would have to call by using webdev serve --hostname 0.0.0.0 on the terminal but each time I do that it just says web dev is not a recognized command. Even though I added the bin folder and directory to the environment variables

**Comment by aHalyk** [comment]
Update: I managed to get it to work by using this command on the terminal: "pub global run webdev serve --hostname 0.0.0.0" 
This isn't going to create a build that can be deployed to a sever but it will allow for devices connected to the same network to access the PWA

**Comment by SebTardif** [comment]
In Visual Studio Code launch --host was not accepted but --web-hostname working fine. I used that to get a Docker container talk to host having flutter web running in debug mode.
