### ISSUE TITLE
Add stub Artifact handling for Deploy vs. Develop

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3262]
Continuation of #3249 @devoncarew agreed to add a stub "Deploy" variant of Android, which points to the same bucket as Develop for now, this will give @jason-simmons or @chinmaygarde a place to wire in separate deploy bits.

**Comment by devoncarew** [comment]
Fixed here: https://github.com/flutter/flutter/pull/3374. Likely a lot of follow-on work to tease apart develop and deploy.
