### ISSUE TITLE
Need help in parsing JSON

### ISSUE THREAD

**Issue by viratshukla** [flutter/flutter#32627]
What if I try to use classes in hierarchy. Lets say I got a response from server. Now the response model is based on parent, child model. Hence there would a BaseResponse class. And one feature specific response class which would be extending BaseResponse class. Now I would like to parse this json manually. Like toJson () and fromJson() pattern. (like this - https://flutter.dev/docs/cookbook/networking/background-parsing#convert-the-response-into-a-list-of-photos). Can some one help me with that

**Comment by stuartmorgan** [comment]
See https://flutter.dev/community for general help resources; the issue tracker is specifically for bug reports and feature requests.
