### ISSUE TITLE
Unable to build or run my Flutter app for iOS

### ISSUE THREAD

**Issue by mulderpf** [flutter/flutter#32634]
## Steps to Reproduce

I am having issues running or building my Flutter app on iOS.  I had a message saying I should update cocoa pods and I think it started from there, but unable to tell.  Until about a month ago, I was always able to run and build my Flutter app on iOS (I mainly develop on a PC and only use iOS to build for iOS).

I have searched for all the similar issues on here, but I am going around in circles with no real answers (this seems like an issue which many are experiencing, but none of the suggestions seem to work, although, due to the number of times this has been raised, I am unsure which is the correct solution.

I am just going in circles here and suspect that I might be making things worse rather than better.  I have also completed deleted flutter and started again, but no success (I also noted as in one of the previous issues raised that the .h files were all links rather than files, the reinstall seems to have changed it to files, but didn't resolve my issue).

1. flutter create new app
2. flutter run

## Logs

```
Launching lib/main.dart on iPhone Xʀ in debug mode...
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                           3.6s
 └─Compiling, linking and signing...                         0.4s
Xcode build done.                                            6.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    In file included from
    /Users/mulder/code/cleanapp/ios/Runner/GeneratedPluginRegistrant.m:5:
    /Users/mulder/code/cleanapp/ios/Runner/GeneratedPluginRegistrant.h:8:9
    : fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone Xʀ. 
```
## Flutter doctor

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale
    en-GB)
    • Flutter version 1.5.4-hotfix.2 at /users/mulder/downloads/flutter
    • Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mulder/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).

[✓] Connected device (1 available)
    • iPhone Xʀ • 887B96CB-B9DF-426A-ADDE-FA70A68A45C5 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by ewgcat** [comment]
can you help me install ios-toolchain,I am android developer，I can help you solve your issus

**Comment by ewgcat** [comment]
> ## Steps to Reproduce
> I am having issues running or building my Flutter app on iOS. I had a message saying I should update cocoa pods and I think it started from there, but unable to tell. Until about a month ago, I was always able to run and build my Flutter app on iOS (I mainly develop on a PC and only use iOS to build for iOS).
> 
> I have searched for all the similar issues on here, but I am going around in circles with no real answers (this seems like an issue which many are experiencing, but none of the suggestions seem to work, although, due to the number of times this has been raised, I am unsure which is the correct solution.
> 
> I am just going in circles here and suspect that I might be making things worse rather than better. I have also completed deleted flutter and started again, but no success (I also noted as in one of the previous issues raised that the .h files were all links rather than files, the reinstall seems to have changed it to files, but didn't resolve my issue).
> 
> 1. flutter create new app
> 2. flutter run
> 
> ## Logs
> ```
> Launching lib/main.dart on iPhone Xʀ in debug mode...
> Running Xcode build...                                                  
>                                                    
>  ├─Assembling Flutter resources...                           3.6s
>  └─Compiling, linking and signing...                         0.4s
> Xcode build done.                                            6.9s
> Failed to build iOS app
> Error output from Xcode build:
> ↳
>     ** BUILD FAILED **
> 
> 
> Xcode's output:
> ↳
>     In file included from
>     /Users/mulder/code/cleanapp/ios/Runner/GeneratedPluginRegistrant.m:5:
>     /Users/mulder/code/cleanapp/ios/Runner/GeneratedPluginRegistrant.h:8:9
>     : fatal error: 'Flutter/Flutter.h' file not found
>     #import <Flutter/Flutter.h>
>             ^~~~~~~~~~~~~~~~~~~
>     1 error generated.
> 
> Could not build the application for the simulator.
> Error launching application on iPhone Xʀ. 
> ```
> 
> ## Flutter doctor
> ```
> [✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale
>     en-GB)
>     • Flutter version 1.5.4-hotfix.2 at /users/mulder/downloads/flutter
>     • Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
>     • Engine revision 52c7a1e849
>     • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/mulder/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling
>       support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at:
>       /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/bin/java
>     • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
>     ✗ Android license status unknown.
>       Try re-installing or updating your Android SDK Manager.
>       See https://developer.android.com/studio/#downloads or visit
>       https://flutter.dev/setup/#android-setup for detailed instructions.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.2.1, Build version 10E1001
>     • ios-deploy 1.9.4
>     • CocoaPods version 1.6.1
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from
>       https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/setup/#android-setup for detailed
>       instructions).
> 
> [✓] Connected device (1 available)
>     • iPhone Xʀ • 887B96CB-B9DF-426A-ADDE-FA70A68A45C5 • ios •
>       com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
> 
> ! Doctor found issues in 2 categories.
> ```

can you help me install ios-toolchain,I am android developer，I can help you solve your issus

**Comment by mulderpf** [comment]
I just followed the guide on the flutter.io website step by step.  That worked for me.  This only started breaking now (around 5 months later).

**Comment by ewgcat** [comment]
I also followed the guide but failed.  Could you help me to solve it? 


 
---Original---

**Comment by mulderpf** [comment]
I didn't do anything other than follow the guide, so not sure how much help I would be.  Clearly I am doing something wrong, not right.

**Comment by mulderpf** [comment]
Reinstalled Flutter and cocoa pods eventually resolved the issue.
