### ISSUE TITLE
32 bit Linux support?

### ISSUE THREAD

**Issue by gsbhasin123** [flutter/flutter#32631]
I know that this issue may be considered a duplicate of #865, but it is not. Apparently, flutter on 32 bit linux gets stuck when running the 64-bit version of Dart. But on https://dart.dev/tools/sdk/archive, there is a 32-bit Linux version of Dart.

**Comment by gsbhasin123** [comment]
I can confirm that the Dart SDK works on 32-bit Linux

**Comment by Drac5079** [comment]
Could you give me the link to the download you did? Both Flutter and Dart. Thanks

**Comment by gsbhasin123** [comment]
I never did haha.
Turns out my PC did support 64 bit - didn't know it. Wasn't powerful enough for the stuff I wanted anyways, so got a new PC.

/cc @Drac5079
