### ISSUE TITLE
Conflict between newest version of Firebase package.

### ISSUE THREAD

**Issue by clovers1254** [flutter/flutter#32632]
I have some problems when update Firebase to newest version, maybe it have a confliction between package of firebase. I'm trying to build app for iOS but it have an error.
I'm just update all package of firebase family to newest version some day ago.
Package I'm using: 

  font_awesome_flutter: ^8.4.0
  firebase_core: ^0.4.0  # add dependency for Firebase Core
  firebase_database:
  firebase_admob: ^0.9.0
  firebase_auth: ^0.9.0
  google_sign_in: ^4.0.1+3
  flutter_facebook_login: ^2.0.0
  flutter_auth_buttons: ^0.3.1
  sprintf: ^4.0.0
  cloud_functions: 0.3.0
  auto_size_text: 1.1.0
  rflutter_alert: ^1.0.2
  audioplayers: ^0.10.1
  url_launcher: ^5.0.2
  video_player: ^0.10.0+8
  firebase_messaging: ^5.0.1
  package_info: ^0.4.0+3
  udid: ^0.0.2
 
## Logs

```
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    cloud_functions (from `.symlinks/plugins/cloud_functions/ios`) was resolved to 0.0.1, which depends on
      Firebase/Functions (~> 5.18) was resolved to 5.18.0, which depends on
        Firebase/CoreOnly (= 5.18.0)

    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 0.0.1, which depends on
      Firebase/Auth (~> 6.0) was resolved to 6.0.0, which depends on
        Firebase/CoreOnly (= 6.0.0)

```

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-VN)
    • Flutter version 1.2.1 at /Users/minhnguyen/development/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/minhnguyen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)


```

Sorry about my bad English :(

**Comment by jorg1piano** [comment]
Have the same issue, had to downgrade :/ 

`  firebase_core: ^0.3.4
  firebase_storage: ^2.1.1+2
  firebase_auth: ^0.9.0
  firebase_database: ^2.0.3`

**Comment by Asoseil** [comment]
seems related to cloudfunction that depends on Firebase/CoreOnly 5.18.0 instead of 6.0.0

**Comment by Smagold** [comment]
This is a blocker. Can't build my app with 5.0.0+1 version.
@collinjackson @jaumard mentioning you as recent contributors to Firebase Messaging plugin in PR flutter/plugins#1318

**Comment by jaumard** [comment]
@Smagold with newer version of firebase I sometime need to run `pod udpate` manually, after that it generally found everything it needs to build.

**Comment by Smagold** [comment]
@jaumard that worked, thank you for a quick response!

Quick instruction for the OP & others: do `cd ios` in your project directory and run `pod update`.

**Comment by clovers1254** [comment]
> @Smagold with newer version of firebase I sometime need to run `pod udpate` manually, after that it generally found everything it needs to build.



> @jaumard that worked, thank you for a quick response!
> 
> Quick instruction for the OP & others: do `cd ios` in your project directory and run `pod update`.

I have deleted Pods directory, Podfile.lock, and run "pod update" in ios, but still have error return:
``
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    cloud_functions (from `.symlinks/plugins/cloud_functions/ios`) was resolved to 0.0.1, which depends on
      Firebase/Functions (~> 5.18) was resolved to 5.18.0, which depends on
        Firebase/CoreOnly (= 5.18.0)

    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 0.0.1, which depends on
      Firebase/Auth (~> 6.0) was resolved to 6.0.0, which depends on
        Firebase/CoreOnly (= 6.0.0)
``
In pubspec.yanml:
``
firebase_core: ^0.4.0
firebase_auth: ^0.11.1
cloud_functions: 0.3.0
``

I think it have nothing changed?

**Comment by jaumard** [comment]
Yes it doesn't apply to you @clovers1254 because you have dependency conflicts, like @jorg1piano said you need to downgrade some dependencies (find the right combination) to resolve that conflict

**Comment by collinjackson** [comment]
I think the issue here is firebase_core needs to be upgraded. I'll do that.
