### ISSUE TITLE
Teach engine/src/sky/tools/gn and BUILD.gn files about --deploy mode

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3263]
Let's start with Android.  @johnmccutchan tells me that there is a PRODUCTION flag for Dart we could turn on as a simple first step.  In later iterations we can add AOTC, etc.

@devoncarew will wire in the tool bits with https://github.com/flutter/flutter/issues/3262, hopefully @jason-simmons or @chinmaygarde are willing to do the script and GN changes.

**Comment by johnmccutchan** [comment]
I will be landing a CL shortly which adds a gn arg `dart_product` set it to true.

**Comment by Hixie** [comment]
How does this differ from "release"?

**Comment by jason-simmons** [comment]
The debug/profile/release runtime modes are now available in the engine and in flutter_tools
