### ISSUE TITLE
dart2aot does not exist on the Dart SDK 

### ISSUE THREAD

**Issue by SaeedMasoumi** [flutter/flutter#32633]
I want to create a command line application, but `dart2aot` does not exist in the Flutter bundle. Should I install and keep separate versions of Dart?

**Comment by passsy** [comment]
Related to https://github.com/dart-lang/sdk/issues/36892

**Comment by mit-mit** [comment]
For general Dart development, you should install the Dart SDK from https://dart.dev/get-dart

**Comment by SaeedMasoumi** [comment]
@mit-mit If I have two separated versions of Dart SDK, Does Flutter get confused? I mean Flutter choose the SDK from its bundle or not?

**Comment by mit-mit** [comment]
Flutter uses the Dart SDK it has embedded inside `bin/cache/dart-sdk`. You can install one or more Dart SDKs as you like outside of your Flutter installation.
