### ISSUE TITLE
Add tools measurements for add-to-app

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32649]
- [x] Add a secondary dimension to the flutter run GA screen to see if it's being invoked in an app type project or a module type project
- [x] Track flavours of flutter create as a dimension app/plugin/module, java/kotlin/objc/swift, any sample template
- [x] Track flutter packages get context as a dimension. Is it in an app or module. Success or failure. Would be nice to add it both as a screen and as an app event (with timing). 
- [x] In flutter packages, would be nice to break out the number of plugins as another dimension. 
- [x] Track invocations of include_flutter.groovy, podhelper.rb and xcode_backend.sh build and embed. Success/failure dimensions. Dart snapshot cache hit as a dimension. Add timing as well in GA. 
- [x] Track flutter attach success/failure. 

Generally, avoid PII such as project names etc. 

Feel free to add additional information you think is valuable for future analysis.

**Comment by xster** [comment]
Worth also running through an add-to-app test run one time to make sure that all the reportings' mutual overlap/exclusion is sensible.

**Comment by xster** [comment]
Was the PR reverted?

**Comment by blasten** [comment]
It was merged back: https://github.com/flutter/flutter/pull/33458

**Comment by xster** [comment]
Small note: related to https://github.com/flutter/flutter/issues/32992 that we talked a bit about on Thursday, I think cd18 isn't right. It checks for people running `flutter run` in the wrapper projects though most likely developers won't do that. They'll be running include_flutter.groovy, flutter.gradle, podhelper.rb and xcode_backend.sh build and embed etc.

**Comment by xster** [comment]
Actually I think we'll need that part. Otherwise we won't have any middle-of-the-funnel level engagement signals from add-to-app'ers which at the moment is the pull-up mechanisms from the various gradle/xcode scripts.

**Comment by blasten** [comment]
@xster the ` include_flutter.groovy` flow only talks to the tool to generate the aot snapshots, and the bundle. What about we register when `flutter build aot` is called on a module project?

**Comment by xster** [comment]
ha, I was just thinking about how we would concretely implement this and wad going to recommend the same thing. SGTM!

We'd anticipate wanting to call flutter build aot for our future flutter build aar/framework too so we should plan ahead on annotating the pull-up experienced ahead of time.

**Comment by blasten** [comment]
Closing, since this is fully implemented now!
