### ISSUE TITLE
Make out/Target/dist directory match artifacts.zip layout

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3264]
In order to make it easier for those iterating with a custom engine with the flutter tool we need to make the layout of artifacts.zip and out/Target/dist match.  @chinmaygarde agreed to take a stab at what this layout should look like with possible help from @jason-simmons for specifying the Android bits.  Once that's done @devoncarew is willing to help with any flutter_tools changes.

**Comment by chinmaygarde** [comment]
This was fixed.
