### ISSUE TITLE
Can I build  apps with Flutter a similar app for this Life360

### ISSUE THREAD

**Issue by techpoints** [flutter/flutter#32650]
Hello
I'm creating an app with Flutter 
But I am worried
You can really create a powerful app that is similar to this Life360!

using:
Trace on the map
Others share my place on the map
Chat in real time

I hope to find a convincing answer .

thank you..

**Comment by stuartmorgan** [comment]
This seems like a very general question, rather than a feature request or a bug report; one of the more general forums listed at https://flutter.dev/community would be a much better forum for that.
