### ISSUE TITLE
Flutter doctor exception

### ISSUE THREAD

**Issue by LDKFighter** [flutter/flutter#32668]
Downloading Dart SDK from Flutter engine 52c7a1e849a170be4b2b2fe34142ca2c0a6fea1f...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  120M    0 97012    0     0  61899      0  0:34:03  0:00:01  0:34:02 61869
  0  120M    0  856k    0     0   333k      0  0:06:10  0:00:02  0:06:08  333k
  2  120M    2 3486k    0     0   978k      0  0:02:06  0:00:03  0:02:03  978k
  5  120M    5 7406k    0     0  1621k      0  0:01:16  0:00:04  0:01:12 1621k
 10  120M   10 12.2M    0     0  2260k      0  0:00:54  0:00:05  0:00:49 2612k
 12  120M   12 15.6M    0     0  2440k      0  0:00:50  0:00:06  0:00:44 3187k
 15  120M   15 18.3M    0     0  2471k      0  0:00:49  0:00:07  0:00:42 3560k
 18  120M   18 22.1M    0     0  2605k      0  0:00:47  0:00:08  0:00:39 3735k
 21  120M   21 25.6M    0     0  2666k      0  0:00:46  0:00:09  0:00:37 3572k
 24  120M   24 29.4M    0     0  2780k      0  0:00:44  0:00:10  0:00:34 3326k
 27  120M   27 33.5M    0     0  2969k      0  0:00:41  0:00:11  0:00:30 3663k
 29  120M   29 35.2M    0     0  2874k      0  0:00:42  0:00:12  0:00:30 3493k
 32  120M   32 38.8M    0     0  2934k      0  0:00:42  0:00:13  0:00:29 3519k
 35  120M   35 42.2M    0     0  2971k      0  0:00:41  0:00:14  0:00:27 3606k
 38  120M   38 45.9M    0     0  2970k      0  0:00:41  0:00:15  0:00:26 3385k
 39  120M   39 47.4M    0     0  2932k      0  0:00:42  0:00:16  0:00:26 2846k
 42  120M   42 50.8M    0     0  2963k      0  0:00:41  0:00:17  0:00:24 3187k
 44  120M   44 53.1M    0     0  2905k      0  0:00:42  0:00:18  0:00:24 2830k
 47  120M   47 57.1M    0     0  2990k      0  0:00:41  0:00:19  0:00:22 3046k
 50  120M   50 60.5M    0     0  3014k      0  0:00:40  0:00:20  0:00:20 3162k
 52  120M   52 63.9M    0     0  3036k      0  0:00:40  0:00:21  0:00:19 3380k
 55  120M   55 67.3M    0     0  3056k      0  0:00:40  0:00:22  0:00:18 3383k
 58  120M   58 70.7M    0     0  3074k      0  0:00:40  0:00:23  0:00:17 3732k
 61  120M   61 74.1M    0     0  3091k      0  0:00:39  0:00:24  0:00:15 3488k
 64  120M   64 77.7M    0     0  3112k      0  0:00:39  0:00:25  0:00:14 3515k
 67  120M   67 81.8M    0     0  3121k      0  0:00:39  0:00:26  0:00:13 3469k
 69  120M   69 84.1M    0     0  3125k      0  0:00:39  0:00:27  0:00:12 3436k
 74  120M   74 90.1M    0     0  3229k      0  0:00:38  0:00:28  0:00:10 3958k
 75  120M   75 91.4M    0     0  3167k      0  0:00:39  0:00:29  0:00:10 3539k
 79  120M   79 96.2M    0     0  3194k      0  0:00:38  0:00:30  0:00:08 3594k
 83  120M   83  100M    0     0  3199k      0  0:00:38  0:00:32  0:00:06 3596k
 85  120M   85  102M    0     0  3233k      0  0:00:38  0:00:32  0:00:06 3826k
 86  120M   86  104M    0     0  3195k      0  0:00:38  0:00:33  0:00:05 3003k
 91  120M   91  110M    0     0  3227k      0  0:00:38  0:00:34  0:00:04 3559k
 94  120M   94  113M    0     0  3273k      0  0:00:37  0:00:35  0:00:02 3786k
 96  120M   96  116M    0     0  3253k      0  0:00:37  0:00:36  0:00:01 3636k
 98  120M   98  118M    0     0  3228k      0  0:00:38  0:00:37  0:00:01 3194k
100  120M  100  120M    0     0  3261k      0  0:00:37  0:00:37 --:--:-- 3773k
find: invalid mode '+100'
Exited (1)

**Comment by rowild** [comment]
Are you on a Mac? If so, do you have brew installed with "findutils"?
https://stackoverflow.com/questions/55663577/flutter-cannot-switch-channel
