### ISSUE TITLE
How do I move the listview to the specified position or how to dynamically calculate the height of the position line?

### ISSUE THREAD

**Issue by FOnlyJack** [flutter/flutter#32669]

**Comment by juggist** [comment]
I think this can help you :)https://github.com/debuggerx01/rect_getter;
this lib can dynamically calculate the height of the listview item.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
