### ISSUE TITLE
Update readme in examples, remove widgets, add gallery

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3266]
The README for the examples directory (https://github.com/flutter/flutter/blob/master/examples/README.md) is a bit out of date. At quick glance, we should add a link to the gallery. Also, remove a mention of widgets. Also, we probably want to update the instructions on how to get and build the examples.

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/3434

**Comment by abarth** [comment]
Fixed in #3434
