### ISSUE TITLE
Flutter UI is broken first screen

### ISSUE THREAD

**Issue by durduman** [flutter/flutter#32675]
I have this UI issue when opening the build (on a device) made from a flutter project and I don't event know where to begin.

![IMG_2693](https://user-images.githubusercontent.com/1089865/57676781-040c5100-762e-11e9-9f2c-c38be754019e.PNG)

I observe this issue every time I reopen the app on the screen that starts.
If a UI render comes along (push/flip to landscape-portrait/popup), 
it comes back to normal.

    > flutter doctor 
    > Doctor summary (to see all details, run flutter doctor
    > -v): [✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-RO)   [✓] Android toolchain - develop for Android
    > devices (Android SDK version 28.0.3) [✓] iOS toolchain - develop for
    > iOS devices (Xcode 10.2) [✓] Android Studio (version 3.3) [✓] VS Code
    > (version 1.33.1) [✓] Connected device (1 available)
    > 
    > • No issues found!

 
(I am not doing anything fancy in the code... just a normal Login screen)

**Comment by daniilguit** [comment]
This is bug from 1.2, upgrade to 1.5

**Comment by durduman** [comment]
Thank you for your response, it resolved my issue.
