### ISSUE TITLE
Sample flutter webapp not detecting http://localhost:8080/

### ISSUE THREAD

**Issue by vijay14887** [flutter/flutter#32678]
I have created my first Flutter web app using "Flutter > New Web Project". Pub get ran fine with exit code 0. But localhost URL- http://localhost:8080/ is not showing the webpage or web server.

Debug Console giving an error as "Not allowed to load local resource: chrome-error://chromewebdata/#buttons [chrome-error://chromewebdata/]"

**Comment by jun-hak** [comment]
The debug console error has to do with "FontManifest.json".
See https://www.didierboelens.com/2019/05/flutter-for-the-web/

**Comment by BondarenkoStas** [comment]
@vijay14887 do you still experience the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
