### ISSUE TITLE
Scaffold is swallowing ScrollNotification 

### ISSUE THREAD

**Issue by tp** [flutter/flutter#32679]
I want to use `NotificationListener<ScrollNotification>` to listen to scroll changes in a scroll view that is about 5 levels deeply nested (hence I wanted to try this first rather than threading a controller through the whole hierarchy).

But when I use a `Scaffold` within the hierarchy, I don't receive any notifications anymore. Without the `Scaffold` it works just as expected.

Hierarchy sample:

```dart
NotificationListener<ScrollNotification>(
  Scaffold(
    appBar: appBar,
    body: SingleChildScrollView(),
  ),
);
```

Is this by design? Can you think of any workaround?

**Comment by HansMuller** [comment]
I was surprised by the very same thing just yesterday. Looking into it.
