### ISSUE TITLE
TabView is always rebuilt when using CupertinoTabScaffold

### ISSUE THREAD

**Issue by huoshulei** [flutter/flutter#32670]
Hello there  
I am having trouble using Flutter CupertinoTabScaffold.
The page is rebuilt when using tabBuilder.
View source The 342-line if statement found in the fullter/lib/src/cupertino/tab_scaffold.dart file, as long as the tab has been loaded, there is a problem of rebuilding.
I don't know if this place is designed like this, or there is a bug.

The source code is as follows:
```
Widget build(BuildContext context) {
  return Stack(
    fit: StackFit.expand,
    children: List<Widget>.generate(widget.tabNumber, (int index) {
      final bool active = index == widget.currentTabIndex;
      if (active || tabs[index] != null) {  //Just in this position
        tabs[index] = widget.tabBuilder(context, index);
      }
      return Offstage(
        offstage: !active,
        child: TickerMode(
          enabled: active,
          child: FocusScope(
            node: tabFocusNodes[index],
            child: tabs[index] ?? Container(),
          ),
        ),
      );
    }),
  );
}
```

**Comment by huoshulei** [comment]
I made the following changes:
```

//        if (active || tabs[index] != null) {
//          tabs[index] = widget.tabBuilder(context, index);
//        }
        if(active && tabs[index]==null){
          tabs[index] = widget.tabBuilder(context, index);
        }
```

The problem is solved

**Comment by LongCatIsLooong** [comment]
@huoshulei from what I understand the rebuilds are not redundant. The offstage tabs need to be rebuilt in order to maintain their state (the `Element`s that hold on to their state objects need to be in the tree). Closing the issue. Feel free to reopen if this behavior breaks anything.

**Comment by huoshulei** [comment]
Is the widget.tabBuilder(context, index) method

Not offstage

widget.tabBuilder(context, index) causes the data to be refreshed all the time

**Comment by huoshulei** [comment]
According to the log output，
All tab pages that have been loaded will be rebuilt as long as the tab is switched
