### ISSUE TITLE
packageInfo.version return null

### ISSUE THREAD

**Issue by haol666** [flutter/flutter#32674]
```
CFBundleDisplayName not set，packageInfo.version return null
code：
PackageInfo.
    fromPlatform().then((PackageInfo packageInfo) {
      String appName = packageInfo.appName;
      String packageName = packageInfo.packageName;
      String version = packageInfo.version;
      String buildNumber = packageInfo.buildNumber;
      print("appName:$appName\tpackageName:$packageName\tversion:$version\tbuildNumber:$buildNumber");
    });
```

**Comment by BondarenkoStas** [comment]
@haol666 did you find a solution? 
If not, can you share steps and example how to reproduce the issue? and please paster your flutter doctor -v output.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
