### ISSUE TITLE
i dont understand the issue

### ISSUE THREAD

**Issue by sarthak1singhal** [flutter/flutter#32676]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by hunomina** [comment]
Sorry mate, I wasn't able to reproduce those errors >_<

**Comment by c0h1b4** [comment]
What device were you using when this happened?
 😃

**Comment by SBNTT** [comment]
I've succesfully reproduced this error on my NoPhone!
