### ISSUE TITLE
Transform.scale doesn't affect disabled widgets

### ISSUE THREAD

**Issue by Kounex** [flutter/flutter#32681]
After recent updates of the flutter framework, `Transform.scale` did stop to affect disabled widgets. A small snippet to illustrate the case:

    Transform.scale(
        scale: 0.75,
        alignment: Alignment.center,
        child: GestureDetector(
            onTap: _active ? () { ... } : null,
            child: ...

if `null` is provided for the `onTap` property, the scaling won't effect its child anymore, which worked in the past and should be the way to go.

Flutter doctor output:

    [✓] Flutter (Channel master, v1.5.9-pre.236, on Mac OS X 10.14.4 18E226, locale de-DE)
    [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    [✓] Android Studio (version 3.2)
    [✓] VS Code (version 1.33.1)
    [✓] Connected device (2 available)

    • No issues found!

**Comment by jason-simmons** [comment]
Can you provide a full example that reproduces this?

I tried creating an application and adding a widget like the one in the bug report:

```
Transform.scale(
  scale: 0.75,
  alignment: Alignment.center,
  child: GestureDetector(
    onTap: () { print('onTap'); },
    child: Text('Hello'),
  ),
),
```

I ran this on the current master branch on Android.  The text is rendered with the scale transform as expected, and the text looks identical if I change `onTap` to `null`.

**Comment by Kounex** [comment]
Fixed meanwhile
