### ISSUE TITLE
run widget_test get Error: Not found: 'dart:ui'

### ISSUE THREAD

**Issue by pingshui3** [flutter/flutter#32680]
**here is the error message:**
```dart
Failed to load "/Users/lpp/Documents/大前端/flutter/xxxxx/test/widget_test.dart":
Unable to spawn isolate: file:///Users/lpp/Documents/Flutter/flutter1.0.0/packages/flutter_test/lib/src/accessibility.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
file:///Users/lpp/Documents/Flutter/flutter1.0.0/packages/flutter_test/lib/src/binding.dart:9:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
file:///Users/lpp/Documents/Flutter/flutter1.0.0/packages/flutter_test/lib/src/matchers.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
file:///Users/lpp/Documents/Flutter/flutter1.0.0/packages/flutter_test/lib/src/matchers.dart:9:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
file:///Users/lpp/Documents/Flutter/flutter1.0.0/packages/flutter_test/lib/src/test_pointer.dart:12:1: Error: Not found: 'dart:ui'
export 'dart:ui' show Offset;
^
file:///Users/lpp/Documents/Flutter/flutter1.0.0/packages/flutter_test/lib/src/window.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' hide window;
       ^
file:///Users/lpp/Documents/Flutter/flutter1.0.0/packages/flutter/lib/src/cupertino/action_sheet.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show ImageFilter;
       ^
file:///Users/lpp/Documents/Flutter/flutter1.0.0/packages/flutter/lib/src/cupertino/bottom_tab_bar.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show ImageFilter;
       ^
file:///Users/lpp/Documents/Flutter/flutter1.0.0/packages/flutter/lib/src/cupertino/colors.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show Color;
       ^
file:///Users/lpp/Documents/Flutter/flutter1.0.0/packages/flutter/lib/src/cupertino/dialog.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' show ImageFilter;
       ^

dart:isolate-patch/isolate_patch.dart 487:14          Isolate.spawnUri
===== asynchronous gap ===========================
dart:async/future_impl.dart 22:43                     _Completer.completeError
dart:async-patch/async_patch.dart 40:18               _AsyncAwaitCompleter.completeError
dart:isolate-patch/isolate_patch.dart                 Isolate.spawnUri
===== asynchronous gap ===========================
dart:async/zone.dart 1062:19                          _CustomZone.registerBinaryCallback
dart:async-patch/async_patch.dart 86:23               _asyncErrorWrapperHelper
dart:isolate-patch/isolate_patch.dart                 Isolate.spawnUri
package:test_core/src/util/dart.dart 28:24            runInIsolate
===== asynchronous gap ===========================
dart:async/zone.dart 1053:19                          _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 77:23               _asyncThenWrapperHelper
package:test_core/src/util/dart.dart                  runInIsolate
package:test_core/src/runner/vm/platform.dart 113:16  _spawnDataIsolate
===== asynchronous gap ===========================
dart:async/zone.dart 1053:19                          _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 77:23               _asyncThenWrapperHelper
package:test_core/src/runner/loader.dart              Loader.loadFile.<fn>
package:test_core/src/runner/load_suite.dart 98:31    new LoadSuite.<fn>.<fn>
===== asynchronous gap ===========================
dart:async/zone.dart 1045:19                          _CustomZone.registerCallback
dart:async/zone.dart 962:22                           _CustomZone.bindCallbackGuarded
dart:async/timer.dart 52:45                           new Timer
dart:async/timer.dart 87:9                            Timer.run
dart:async/future.dart 174:11                         new Future
package:test_api/src/backend/invoker.dart 399:21      Invoker._onRun.<fn>.<fn>.<fn>
Process finished with exit code 1


**here is the test content:**
import 'package:xxxxx/widgets/title_bar.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  // with Widgets in the test environment.
  testWidgets('MyWidget has a title and message', (WidgetTester tester) async {
    // Create the Widget tell the tester to build it
    await tester.pumpWidget(TitleBar('T'));

    // Create our Finders
    final titleFinder = find.text('T');

    // Use the `findsOneWidget` matcher provided by flutter_test to verify our
    // Text Widgets appear exactly once in the Widget tree
    expect(titleFinder, findsOneWidget);
  });
}
```

**Comment by kangwang1988** [comment]
@pingshui3 
Paste result for `flutter doctor -v` please.

**Comment by pingshui3** [comment]
flutter doctor -v
`[✓] Flutter (Channel master, v1.5.9-pre.236, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 1.5.9-pre.236 at /Users/lpp/Documents/Flutter/flutter1.0.0
    • Framework revision 894dca77b6 (2 hours ago), 2019-05-14 02:35:39 -0400
    • Engine revision 49bc9c86c9
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/lpp/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/lpp/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.4892.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
`

**Comment by 0-php** [comment]
是不是没有配置环境变量，如果环境没问题试着用 flutter packages get

**Comment by pingshui3** [comment]
> 是不是没有配置环境变量，如果环境没问题试着用 flutter packages get

已经配置了
/Users/lpp/Documents/Flutter/flutter1.0.0/bin:/Users/lpp/Documents/Flutter/flutter1.0.0/bin/cache/dart-sdk/bin

**Comment by kangwang1988** [comment]
I've solved the problem occured on @pingshui3 's mac via RemoteDesktop. It's a environment issue which can be fixed by reinstalling Intellij Idea and Flutter(Dart) plugin.

**Comment by pingshui3** [comment]
> I've solved the problem occured on @pingshui3 's mac via RemoteDesktop. It's a environment issue which can be fixed by reinstalling Intellij Idea and Flutter(Dart) plugin.

thanks you very much @kangwang1988

**Comment by feiyang1235** [comment]
have you solved this problem. same question occured~

**Comment by jaysephjw** [comment]
@feiyang1235 I was getting a similar problem, only in Android Studio. The problem was my run configuration:: it was running as a 'Dart Command Line App', instead of a Flutter Test.  Open run configurations and remove the Dart one to fix.

###### bad
![image](https://user-images.githubusercontent.com/3268245/65452981-403b9380-de10-11e9-889e-0428a30ef598.png)
runs like `/Users/me/tools/flutter/bin/cache/dart-sdk/bin/dart --enable-asserts --enable-vm-service:58029 /Users/jwarrick/projects/ecom_module/test/my_test.dart
`

###### good
![image](https://user-images.githubusercontent.com/3268245/65453197-b3dda080-de10-11e9-9956-7141dcf469d0.png)
runs like `/Users/me/tools/flutter/bin/flutter --no-color test --machine test/my_test.dart`

###### pick the flutter one!
![image](https://user-images.githubusercontent.com/3268245/65453088-7ed14e00-de10-11e9-9c38-af5f435d03df.png)

related SO solution here: 
https://stackoverflow.com/questions/52483773/dartui1-error-not-found-dartui-flutter-dart

**Comment by zahidr** [comment]
dart:ui , runner not found , 
resolved :  Android Studio go to tools menu  and install flutter sdk.
then flutter option. Can't remember the option after that , but it will say no sdk found in RED.
The option no longer appears as I have now installed flutter sdk.    
After that you will not have any issues when down loading or cloning git hub projects.
You may think  you have flutter sdk installed , 
but you if you are using git hub and cloning  a project but not creating a git hub project ,
you must installed flutter sdk  via tools menu . Then all is well.
