### ISSUE TITLE
Confusing CloudFunctions.getHttpsCallable parameters

### ISSUE THREAD

**Issue by bereal** [flutter/flutter#32691]
Since the version 0.2.0 cloud_functions for Flutter use `.getHttpsCallable()` instead of `.call()`. The new method is defined as:

```
/// @param functionName The name of the callable function being triggered.
/// @param parameters Parameters to be passed to the callable function.
HttpsCallable getHttpsCallable(
    {@required String functionName, Map<String, dynamic> parameters}) {
  return HttpsCallable._(this, functionName);
}
```

As we can see, the argument parameters is not used though declared and documented. I spent quite some time debugging before checked the code and realised that the argument is not used. So, one is expected to pass the parameters to the subsequent `.call()` on the callable object. Would it make sense to remove the confusing argument?

**Comment by jul1u5** [comment]
This is no longer the case and can be closed.
