### ISSUE TITLE
JPG image not displayed via Image.file()

### ISSUE THREAD

**Issue by MartinNiederl** [flutter/flutter#32692]
## Steps to Reproduce

The code leading to errors was taken from https://github.com/flutter/plugins/blob/master/packages/image_picker/example/lib/main.dart.

I tried the example to figure out how to take images in Flutter, and I soon realized that JPG pictures are not displayed on my older phone Samsung Galaxy A5 (2015) (listed in the `flutter doctor -v` output). There are no problems on the new phone or with the PNG image format.
So when I select JPG images, the screen stays white, but PNG images are displayed as desired.

Basically it comes down to these two lines:

```
_imageFile = await ImagePicker.pickImage(source: source);
Image.file(_imageFile)
```

1. Execute code from https://github.com/flutter/plugins/blob/master/packages/image_picker/example/lib/main.dart.

## Logs

`flutter run --verbose`

https://pastebin.com/ubMhG1U0

`flutter analyze`

```
Analyzing test_project...                                       
No issues found! (ran in 3.7s)
```

`flutter doctor -v`

```
[✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /home/martinniederl/development/flutter
    • Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/martinniederl/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/martinniederl/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /home/martinniederl/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.0.2

[✓] Connected device (2 available)
    • POCOPHONE F1 • 7fa18afc • android-arm64 • Android 9 (API 28)
    • SM A500FU    • 951ad3cd • android-arm   • Android 5.0.2 (API 21)

• No issues found!
```

**Comment by thevzurd** [comment]
I am facing the same issue with old moto phone.  Is there a work around ?

**Comment by thevzurd** [comment]
Incase you havent found a work around, I converted the image to PNG using Image package and it started working.

**Comment by stefandevai** [comment]
I was facing the same issue with a Motorola E5. In my case the problem was related with the image's size, I wasn't able to display any large size pictures.

If you don't want to convert the image to PNG as it can increase file's size, you can compress the image with the [flutter_image_compress](https://pub.dev/packages/flutter_image_compress) package and then display it.

**Comment by thevzurd** [comment]
Actually, I realized that the issue is with the file size. There is an option for maximum width and height in the image_picker methods. That kinda compress the file to manageable size. I can now see the image load immediately on the UI.

**Comment by MartinNiederl** [comment]
Then I will probably need 2 versions of the picture: A compressed one for displaying in the app and the original one for sending to the backend.

But I am sure that this is **not the intended behavior** and I will not close the issue yet.

**Comment by mponkin** [comment]
Having the same problem with big jpg images. Image source does not matter, both assets and network image displayed as white rectangle with proper aspect ratio.
Reproduces only on android, works fine on ios.

**Comment by VigneshPasupathy** [comment]
Hey just wanted to add this thread in case it might provide some insight.

I was experimenting with using https://pub.dev/packages/image_cropper plugin .
After taking the photo if I increase the scale while cropping ever so slightly (increased from 75% to 78%) and the image starts to display normally.

**Comment by TahaTesser** [comment]
Hi @MartinNiederl 
This seems to be fixed, running the code sample  on API 22 (Android 5.0)
JPG Image is loaded just fine.

If you're still experiencing this issue, please can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
I will reopen the issue
Thank you
