### ISSUE TITLE
How to implement custom color theme to google maps?  

### ISSUE THREAD

**Issue by navaneeth7067** [flutter/flutter#32695]
**

**Comment by rubensdemelo** [comment]
Hi @navaneeth7067 . Use StackOverflow, it isnt a bug.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
