### ISSUE TITLE
build and upload gen_snapshot to darwin-x64

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#3269]
As part of work for enabling AOT builds, we'll need to build `gen_snapshot` for mac and upload it to `darwin-x64` (which currently just holds `sky_snapshot`).

**Comment by eseidelGoogle** [comment]
AOTC builds for Android, I presume?  FYI @chinmaygarde

**Comment by sethladd** [comment]
This should allow for building `--release` on a Mac, yes?

**Comment by chinmaygarde** [comment]
This is complete. We upload a gen_snapshot capable of create EABI snapshots from the Mac host for Android targets. Mac ABI specific snapshotters are uploaded in the specific bucket for each variant (that is consumed by the Xcode scripts). Closing.
