### ISSUE TITLE
build and upload gen_snapshot to linux-x64

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#3270]
As part of work for enabling AOT builds, we'll need to build `gen_snapshot` for linux and upload it to `linux-x64`.

**Comment by eseidelGoogle** [comment]
I suspect it's already built and we just need to change this function:
https://chromium.googlesource.com/chromium/tools/build.git/+/master/scripts/slave/recipes/flutter/engine.py#141

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/blob/master/infra/README.md attempts to document instructions for changing engine.py.  Happy to help if it's unclear.

**Comment by eseidelGoogle** [comment]
I'm pretty sure this is already done?  In fact, I think @goderbauer even removed these from being downloaded twice yesterday? :D

**Comment by chinmaygarde** [comment]
This is definitely done. We can close the issue.
