### ISSUE TITLE
CupertinoButton in CupertinoNavigationBar as trailing gets cut

### ISSUE THREAD

**Issue by bierbaumtim** [flutter/flutter#32701]
Adding a CupertinoButton with Text to CupertinoNavigationBar as trailing cuts of the Text on its half height.

## Steps to Reproduce

https://gist.github.com/tb2761/567623b671e5d15cfadfb1a27248fcf4

## Logs

```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.475], locale de-DE)
    • Flutter version 1.5.4-hotfix.2 at C:\Users\Tim\Flutter\src\flutter
    • Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Tim\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Tim\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.33.1)
    • VS Code at C:\Users\Tim\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.2

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by alphatroya** [comment]
Yes, it is cutting by half like on screenshot
<img width="549" alt="Снимок экрана 2019-05-29 в 17 10 02" src="https://user-images.githubusercontent.com/4927633/58563912-a898b080-8234-11e9-9f13-c544c9308517.png">

Leading position have simular issue.

**Comment by ykorzikowski** [comment]
still an issue. 

Workaround: 

Add     padding: EdgeInsets.all(10), to CUpertinoButton

**Comment by tb2761** [comment]
okay, thanks for the workaround

**Comment by AllanStepps** [comment]
Still actual ?

**Comment by ameyer117** [comment]
Yes this is still a problem.

**Comment by glockhart8** [comment]
CupertinoButton(
    padding: EdgeInsets.all(0.0), 
    ...
)

If you surround the button in padding, i think that it somehow moves where the touch point is on the button, but if you change the padding inside the button to zero, works well.

**Comment by tiklup11** [comment]
Still this is not fixed

**Comment by casvanluijtelaar** [comment]
still an issue in 1.22.6

**Comment by quickdashapp** [comment]
Still an Issue!! haha

**Comment by Akhu** [comment]
Still an issue here with the latest version of Flutter 
```
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (3 days ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2
```

**Comment by Piinks** [comment]
I think this is expected, please refer to the documentation for `CupertinoButton`:

> The [padding] defaults to 16.0 pixels. When using a [CupertinoButton] within
 a fixed height parent, like a [CupertinoNavigationBar], a smaller, or even
 [EdgeInsets.zero], should be used to prevent clipping larger [child]
 widgets.

If there is a bug around this, please file a new issue with a reproducible code sample and the output of flutter doctor.

**Comment by lvyandev** [comment]
So what kind of widget is supposed to be in the trailing?

**Comment by haashem** [comment]
@Ivyandev mostly buttons that user can interact with like submitting a form.
<img width="368" alt="Screen Shot 2021-04-20 at 11 40 29" src="https://user-images.githubusercontent.com/3206748/115357150-60d6f580-a1cd-11eb-9e27-dc8acb7532ee.png">

**Comment by talamaska** [comment]
No, just documenting the behavior doesn't solve the issue itself. 
Changing the padding to zero is a workaround, not a fix. If we can't use CupertinoButton as is in the navigation bar, then there should be a separate widget just for that. I don't get how can I put a simple IconButton or TextButton or any other button in AppBar and don't have any problems, but for Cupertino I have to deal with this? I think there should be CupertinoNavigationBarButton or something alike. Should we just do that as a wrapper of CupertinoButton and submit a PR?
