### ISSUE TITLE
MaterialPageRoute adaptive page transition on iOS is too fast on stable channel v1.5

### ISSUE THREAD

**Issue by ghunter99** [flutter/flutter#32712]
On iOS, MaterialPageRoute, which adapts by sliding pages in from the right, is sliding the page much too fast.

I only noticed it on the latest stable build, v1.5.4-hotfix.2 so not sure when it started happening.

The transition is too fast when running:
- in debug and release mode 
- on slow devices (iPhone 6) and fast devices (iPhone XR)

CupertinoPageRoute slides at the right speed (according to my eyes)

You can see it when you run flutter_gallery on an iOS device.

Maybe I'm doing something silly?

Hope this is helpful.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] Connected device (2 available)

**Comment by TahaTesser** [comment]
Hi @ghunter99 
Are you still experiencing this issue with latest stable?
If yes,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
