### ISSUE TITLE
flutter has exited unexpectedly

### ISSUE THREAD

**Issue by saswatsaubhagya** [flutter/flutter#32729]
Working fine before upgrade 

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 477fefb0c3cdaecf)
 
Crash report written to /Users/saswatsaubhagyarout/flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by wenjiangit** [comment]
open  /Users/saswatsaubhagyarout/flutter_03.log，you may find some useful information

**Comment by saswatsaubhagya** [comment]
yes i myself resolved the issue by again updating the new  flutter zip file
