### ISSUE TITLE
FirebaseAuth: verificationCompleted never triggered for test (whitelisted) phone numbers

### ISSUE THREAD

**Issue by votagus** [flutter/flutter#32732]
Steps to reproduce:
1- Added my own phone number to the whitelist, events fired: codeSent, codeAutoRetrievalTimeout.
2- Removed my phone number from the whitelist, events fired were: codeSent, verificationCompleted, (I did receive the sms).
3- Added the number suggested by the docs., +16505551234, events fired were: same as in step 1.

```
    await _auth.verifyPhoneNumber(
        phoneNumber: phone,
        timeout: const Duration(seconds: 5),
        verificationCompleted: (r) {
          print("Verification completed ");
        },
        verificationFailed: (r) {
          print("Verification failed " + r.message);
        },
        codeSent: (r, [v]) {
          print("Code sent." + r + v.toString());
          return null;
        },
        codeAutoRetrievalTimeout: (r) {
          print("Timeout " + r.toString());
        });
```

**Comment by BondarenkoStas** [comment]
@votagus did you manage to solve the issue?

**Comment by kroikie** [comment]
@votagus

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1108. Any further collaboration will be done there.
