### ISSUE TITLE
 Class 'MethodChannel' has no instance method 'invokeMethod' with matching arguments

### ISSUE THREAD

**Issue by mrutyunjayagiri** [flutter/flutter#32739]
[ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 5924): NoSuchMethodError: Class 'MethodChannel' has no instance method 'invokeMethod' with matching arguments.
E/flutter ( 5924): Receiver: Instance of 'MethodChannel'
E/flutter ( 5924): Tried calling: invokeMethod<String>("getApplicationDocumentsDirectory")
E/flutter ( 5924): Found: invokeMethod(String, [dynamic]) => Future<dynamic>
E/flutter ( 5924): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter ( 5924): #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:65:22)
E/flutter ( 5924): <asynchronous suspension>

**Comment by boxsters1423** [comment]
same error

**Comment by Rimjhim28** [comment]
Any updates on this?

**Comment by boxsters1423** [comment]
After a flutter upgrade it solves my problem

**Comment by boxsters1423** [comment]
> Any updates on this?

After a flutter upgrade it solves my problem

**Comment by BondarenkoStas** [comment]
@mrutyunjayagiri do you experience it with current flutter stable?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
