### ISSUE TITLE
[web]:  FAQ Migration Guide link not working

### ISSUE THREAD

**Issue by ganeshsp1** [flutter/flutter#32737]
In Flutter for web Tech Preview FAQ, for the question Why are fonts not working?, the link provided at the end "including the fonts in the migration guide."(https://github.com/flutter/flutter_web/blob/master/oss/docs/faq.md) page says 404 Page not found.

**Comment by degroote22** [comment]
The correct one: https://github.com/flutter/flutter_web/blob/master/docs/migration_guide.md
