### ISSUE TITLE
App Crashes in Android using Firebase Auth 

### ISSUE THREAD

**Issue by SandyAra** [flutter/flutter#32731]
/android/app/src/main/AndroidManifest.xml:24:9-31:50 Warning:
	activity#com.google.firebase.auth.internal.FederatedSignInActivity@android:launchMode was tagged at AndroidManifest.xml:24 to replace other declarations but no other declaration present

Please help asap.

**Comment by JosePlaya** [comment]
Hi, do you have solved that problem?

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by megadrazz** [comment]
> /android/app/src/main/AndroidManifest.xml:24:9-31:50 Aviso:
> activity#com.google.firebase.auth.internal.FederatedSignInActivity@android: launchMode foi etiquetado em AndroidManifest.xml: 24 para substituir outros declarações, mas nenhuma outra declaração presente
> 
> Por favor, ajude o mais cedo possível.

AAPT: error: elements require a sdk version of at least 26+. ","tool":"AAPT"

Try Updating SDK version.

Settings->System Settings->Android SDK->SDK Tools

Check Android SDK Tools 26+

At least v26+ is to be installed or higher.
