### ISSUE TITLE
Android app crash on lunch :  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/platforminfo/LibraryVersionComponent;         at io.flutter.plugins.firebase.core.FlutterFirebaseAppRegistrar.getComponents(FlutterFirebaseAppRegistrar.java:16)

### ISSUE THREAD

**Issue by Abgaryan** [flutter/flutter#32749]
## Steps to Reproduce

After migration to AndroidX the project builds successfully but the app crashes on lunch 

## Logs

 ```
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/platforminfo/LibraryVersionComponent;
        at io.flutter.plugins.firebase.core.FlutterFirebaseAppRegistrar.getComponents(FlutterFirebaseAppRegistrar.java:16)
        at com.google.firebase.components.zzg.<init>(Unknown Source:31)
        at com.google.firebase.FirebaseApp.<init>(Unknown Source:114)
        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source:109)
        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source:2)
        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source:28)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source:4)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1964)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1933)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:15)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6655)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6189)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6110)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1715)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:180)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
```

 plugins  
```
  firebase_analytics: 2.0.1
  firebase_auth: 0.11.1

  firebase_messaging: 3.0.1
  firebase_database: 3.0.0

  firebase_performance: ^0.1.0+2
  firebase_remote_config: ^0.1.0+1

  firebase_dynamic_links:  0.4.0
  firebase_storage: ^3.0.0

  flutter_crashlytics: ^1.0.0
  cloud_firestore: ^0.11.0+2
```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):

[✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Mac OS X 10.13.6 17G5019, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

```

**Comment by osamagamal65** [comment]
is there's any fixes yet?

**Comment by BondarenkoStas** [comment]
please provide your build.gradle

**Comment by osamagamal65** [comment]
`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new FileNotFoundException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.") //GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

apply plugin: 'io.fabric'

repositories {
    mavenCentral()
    maven { url 'https://maven.fabric.io/public' }
}
android {
    signingConfigs {
        defaultConfig {
            keyAlias 'key0'
            keyPassword 'Berlin2018'
            storeFile file('keystores/ddkeystore')
            storePassword 'Berlin2018'
        }
        defaultConfigLearner {
            keyAlias 'key0'
            keyPassword 'ourPassword'
            storeFile file('keystores/ddkeystore')
            storePassword 'ourPassword'
        }
        prodactionConfigInstructor {
            keyAlias 'ourKeyAlias'
            keyPassword 'ourKeyPassword'
            storeFile file('keystores/instructorKeystore')
            storePassword 'ourKeyPassword'
        }
        prodactionConfigLearner {
            keyAlias 'ourKeyAlias'
            keyPassword 'ourKeyPassword'
            storeFile file('keystores/learnerKeystore')
            storePassword 'ourKeyPassword
        }
    }
    packagingOptions {
        exclude 'META-INF/NOTICE.txt'
    }
}
android {
    flavorDimensions "default"
    compileSdkVersion 28
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    defaultConfig {
        applicationId "com.driveddy.instructor.and.live"
        minSdkVersion 23
        targetSdkVersion 28
        versionName "1.4.0"
        versionCode 3445
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        manifestPlaceholders = [
                appLabel : "Instructor default",
                appIcon  : "@mipmap/ic_launcher",
                roundIcon: "@mipmap/ic_launcher_round",
                fabricKey: "ourFavricKey",
        ]
        ext.betaDistributionGroupAliases = "beta-android"
        ext.betaDistributionReleaseNotesFilePath = "keystores/beta_release_notes.txt"
        multiDexEnabled true
    }
    buildTypes {
        release {
        }
    }
    productFlavors {
        flavorDimensions "default"
        learner_live {
            signingConfig signingConfigs.prodactionConfigLearner
            applicationId "com.driveddy.learner.and.live"
            minSdkVersion 23
            targetSdkVersion 28
            versionCode 3445
            versionName "1.6.0"
            testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
            manifestPlaceholders = [
                    appLabel : "drivEddy",
                    appIcon  : "@mipmap/ic_launcher_student",
                    roundIcon: "@mipmap/ic_launcher_student_round",
                    fabricKey: "ourFavricKey",
            ]
        }
        learner {
            signingConfig signingConfigs.defaultConfig
            applicationId "com.driveddy.learner.and.beta"
            minSdkVersion 23
            targetSdkVersion 28
            versionCode 4059
            versionName "2.0.6"
            testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
            
            manifestPlaceholders = [
                    appLabel : "Learner-β",
                    appIcon  : "@mipmap/ic_launcher_student",
                    roundIcon: "@mipmap/ic_launcher_student_round",
                    fabricKey: "ourFavricKey",
            ]
            versionNameSuffix '-β'
        }
        instructor_live {
            signingConfig signingConfigs.prodactionConfigInstructor
            applicationId "com.driveddy.instructor.and.live"
            minSdkVersion 18
            targetSdkVersion 28
            versionCode 3445
            versionName "1.6.0"
            testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
            manifestPlaceholders = [
                    appLabel : "Fahrlehrer",
                    appIcon  : "@mipmap/ic_launcher",
                    roundIcon: "@mipmap/ic_launcher_round",
                    fabricKey: "ourFavricKey",
            ]
        }
        instructor {
            signingConfig signingConfigs.defaultConfig
            applicationId "com.driveddy.instructor.and.beta"
            minSdkVersion 18
            targetSdkVersion 28
            versionCode 3445
            versionName "1.5.1"
            testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
            manifestPlaceholders = [
                    appLabel : "Instructor-β",
                    appIcon  : "@mipmap/ic_launcher",
                    roundIcon: "@mipmap/ic_launcher_round",
                    fabricKey: "ourFavricKey",
            ]
            versionNameSuffix '-β'
        }
    }
}


flutter {
    source '../..'
}


dependencies {
    configurations.all {
        resolutionStrategy {
            eachDependency { details ->
                if (details.requested.group == 'com.google.android.gms' ||
                        details.requested.group == 'com.google.firebase') {
                    details.useVersion "15.0.0"
                }
            }
        }
    }

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation('com.crashlytics.sdk.android:crashlytics:2.10.1@aar') {
        transitive = true
    }
    implementation 'com.google.firebase:firebase-core:17.2.0'
    implementation 'com.google.firebase:firebase-messaging:20.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.facebook.android:facebook-android-sdk:5.5.1'

}`

**Comment by osamagamal65** [comment]
@BondarenkoStas

**Comment by blasten** [comment]
To migrate to AndroidX, follow the steps on https://flutter.dev/docs/development/androidx-migration.

Also, you might want to remove the code below from build.gradle:
```
configurations.all {
        resolutionStrategy {
            eachDependency { details ->
                if (details.requested.group == 'com.google.android.gms' ||
                        details.requested.group == 'com.google.firebase') {
                    details.useVersion "15.0.0"
                }
            }
        }
    }
```
