### ISSUE TITLE
Windows release engine build failed with unresolved external symbols

### ISSUE THREAD

**Issue by boyen747** [flutter/flutter#32746]
C:\steven\engine\src>ninja -C .\out\host_release
ninja: Entering directory `.\out\host_release'
[1/134] LINK(DLL) flutter_engine.dll flutter_engine.dll.lib
FAILED: flutter_engine.dll flutter_engine.dll.lib
C:/steven/depot_tools/win_tools-2_7_13_chromium7_bin/python/bin/python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /IMPLIB:./flutter_engine.dll.lib /DLL /OUT:./flutter_engine.
dll /PDB:./flutter_engine.dll.pdb @./flutter_engine.dll.rsp
  正在创建库 ./flutter_engine.dll.lib 和对象 ./flutter_engine.dll.exp
runtime.dart_snapshot.obj : error LNK2001: 无法解析的外部符号 kDartVmSnapshotData
runtime.dart_snapshot.obj : error LNK2001: 无法解析的外部符号 kDartVmSnapshotInstructions
runtime.dart_snapshot.obj : error LNK2001: 无法解析的外部符号 kDartIsolateSnapshotData
runtime.dart_snapshot.obj : error LNK2001: 无法解析的外部符号 kDartIsolateSnapshotInstructions
./flutter_engine.dll : fatal error LNK1120: 4 个无法解析的外部命令
[3/134] LINK ./flow_unittests.exe
ninja: build stopped: subcommand failed.

**Comment by boyen747** [comment]
same problem from others:
Trying to build flutter engine on Windows running this:
ninja -C out\host_release
It seems to be working until i hit this error:
[6/7] LINK(DLL) flutter_engine.dll flutter_engine.dll.lib
FAILED: flutter_engine.dll flutter_engine.dll.lib
C:/Python27/python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /IMPLIB:./flutter_engine.dll.lib /DLL /OUT:./flutter_engine.dll /PDB:./flutter_engine.dll.pdb @./flutter_engine.dll.rsp
runtime.dart_snapshot.obj : error LNK2001: unresolved external symbol kDartVmSnapshotData
runtime.dart_snapshot.obj : error LNK2001: unresolved external symbol kDartVmSnapshotInstructions
runtime.dart_snapshot.obj : error LNK2001: unresolved external symbol kDartIsolateSnapshotData
runtime.dart_snapshot.obj : error LNK2001: unresolved external symbol kDartIsolateSnapshotInstructions
./flutter_engine.dll : fatal error LNK1120: 4 unresolved externals
ninja: build stopped: subcommand failed.

**Comment by boyen747** [comment]
change to debug mode, it can work. Why? Is release mode not support?

**Comment by stuartmorgan** [comment]
> Is release mode not support?

In general, there has been no attempt to support release mode for desktop, no. That's tracked in #30672

**Comment by stuartmorgan** [comment]
I'm able to repo this. I've updated the engine build instructions for now to discourage trying to build release for Windows for anything other than `gen_snapshot`.

**Comment by shoryukenn** [comment]
This is very interesting, I started to try to solve it.

**Comment by shoryukenn** [comment]
@stuartmorgan , The reason is that the Windows platform does not link k_vn_snapshot_data.bin.o isolate_snapshot_instructions.bin.o vm_snapshot_instructions.bin.o vm_snapshot_data.bin.o generated by bin_to_coff. How do we add them in the shell/windows link deps?

**Comment by shoryukenn** [comment]
@stuartmorgan , I initiated a pull request: https://github.com/flutter/engine/pull/11475
