### ISSUE TITLE
Allow FlutterActivity to be configured with a transparent/translucent background.

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#32740]
Allow FlutterActivity to be configured with a transparent/translucent background.

The use-case is to display a FlutterApp that operates like an overlay, e.g., dialog, above the previous Activity.

**Comment by matthew-carroll** [comment]
@dnfield do you know if this use-case is already supported by the iOS embedding?

CC @xster because you're looking through embedding add-to-app capabilities right now.

**Comment by dnfield** [comment]
You can set a `FlutterViewController` to be opaque or not.  It then passed that down to the `FlutterView`.  https://github.com/flutter/flutter/issues/21808 has more details

**Comment by matthew-carroll** [comment]
Implemented here: https://github.com/flutter/engine/pull/9115
