### ISSUE TITLE
Discrete slider indicator should slide then show its indicator

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#3274]
You can see this in the gallery sliders demo.

Tapping on the discrete slider causes the indicator to leap from its current position to the place you've tapped.

The indicator circle should probably slide to the tap's location and before inflating the value bubble.

**Comment by eseidelGoogle** [comment]
I think the leaping is kinda cute.  Given how infrequent sliders are in the wild, we should probably punt this from the first release and re-visit slider behavior as a whole at a later time to make sure it matches spec.

**Comment by Hixie** [comment]
I'm going to close this. We can revisit if the material team point it out.
