### ISSUE TITLE
Account for Android Q Gestural Navigation

### ISSUE THREAD

**Issue by PieterAelse** [flutter/flutter#32748]
The new Gestural Navigation of Android Q interferes with touch/swipe regions inside any Flutter app. SafeArea doesn't take it into account.

Steps to reproduce:
- Get a Pixel or any other supported device
- Enrol to the Q beta program
- Download/install latest Q beta
- Go to settings => system => gestures and turn on "Fully Gestural Navigation"
- Open a Flutter app with a swipeable widget on the left/right and prepare to navigate back 🙃 ...

Example widgets which will be impacted:
- Pagers
- Sliders
- Drawer
- etc..
- ...

Google info video which also explains how to get insets natively: https://www.youtube.com/watch?v=Ljtz7T8R_Hk 

Screenshot from the video showing the regions:
![Screenshot 2019-05-15 at 09 55 13](https://user-images.githubusercontent.com/6347879/57759466-456a3280-76fa-11e9-8234-4bff60451d72.png)

**Comment by miguelcmedeiros** [comment]
@filiph, can you please label this issue with customer:solaris?

**Comment by Zazo032** [comment]
Maybe `SafeArea()` should take this into account and only draw widgets within the safe area of the device (i.e. not placing widgets in both sides for safer back gesture).

**Comment by audkar** [comment]
> Example widgets which will be impacted

also Drawer

Would be very good if this could be addressed before Android Q stable is released and users start using gesture navigation

**Comment by audkar** [comment]
@filiph IMHO customer also is a crowd :) 

I am not sure if Flutter team is even aware what is going to happen when next android stable version going to be released in a few months (~3 months)... Users with new android version will not be able to open Drawers, BottomSheets, change slider values from the edge of screen. So partially Flutter apps will be broken.

I hope that I am mistaken and Flutter team is already working on adapting Material widgets to work with Gesture Navigation. Because not much time left and from my understanding this is not trivial task to implement this correctly.

**Comment by eseidelGoogle** [comment]
@HansMuller is probably the best to comment here.  Thanks!

**Comment by HansMuller** [comment]
@audkar We're aware of the changes and will link to PRs that address them here.

Apps need to be informed about Q's gesture navigation insets (as well as the "mandatory" vertical ones), they need to be able to disable the left/right back gesture support, and extend apps full-screen. We've asked for some feedback from the Material Design team about how to handle a scaffold's drawer when back gesture is in effect.

**Comment by Zazo032** [comment]
This is going to be tweaked a bit in the upcoming Android Q beta 5: https://twitter.com/chrisbanes/status/1146050918892412928

**Comment by HansMuller** [comment]
@Zazo032 - right, opening the drawer upon long-press-then-swipe is consistent with the "new features" item here: https://developer.android.com/jetpack/androidx/releases/drawerlayout

**Comment by PieterAelse** [comment]
https://www.androidpolice.com/2019/07/03/android-q-beta-5-gesture-nav-side-menu/

**Comment by willlarche** [comment]
We're in touch with the Android team on final guidance and expectations and will hopefully have a new update on our support for this next week. Our priority is making sure this is resolved by Q release.

**Comment by audkar** [comment]
Super duper awesomely amazing news :smile:  :+1: 

As per [Gestural navigation docs](https://developer.android.com/preview/features/gesturalnav#back-gestures)
> The DrawerLayout and SeekBar components support automatic opt-out behavior out of the box

I really hope that behavior of components (SeekBar, etc) will be aligned at time AndroidQ is release in the wild :)

**Comment by PieterAelse** [comment]
Please also check and support proper drawing behind the statusbar! Like explained in Chris Banes [talk at Droidcon (slides)](https://chris.banes.dev/talks/2019/going-edge-to-edge-berlin/ ) the small part at the bottom can be accounted for using windowInsets.

Hoping this result on the right will be possible with Flutter soon: 
<img width="259" alt="Q-bottom-window-insets" src="https://user-images.githubusercontent.com/6347879/61292255-06775c80-a7d1-11e9-949b-340c4036ae69.png">

**Comment by shihaohong** [comment]
Hi all, I'm currently working on getting Flutter to handle Android Q Gestural Navigation. I'm going to list out the different tasks that need to be completed to help myself keep track of progress and what else needs to be done. This will also help if I missed anything:
- [ ] **Expose insets.systemGestureInsets on MediaQuery.of(context).systemGestureInsets**
This allows developers to place draggable widgets outside of the system gesture insets
- [ ] **Expose insets.systemWindowInsets.bottom**
There is some tricky logic in the engine that sets `MediaQueryData.viewInsets` and `MediaQueryData.padding` to be zero to handle keyboards/hidden nav bar(https://github.com/flutter/engine/pull/6288). We will need to provide the unchanged systemWindowInset values Android provides.
- [ ] **Expose setSystemGestureExclusionRects API**
This allows developers to change remove gestures from non-mandatory insets. After exposing the API to the framework, the next step would be to create a convenience widget that sends wraps itself in the exclusion rect.
- [ ] **Expose getSystemGestureExclusionRects API**
Conversely, it would be good to have a way to query what system gesture exclusion rects have been set.
- [ ] **Expose insets.mandatorySystemGestureInsets on MediaQuery.of(context).mandatorySystemGestureInsets**
This provides information regarding gesture insets that cannot be removed to the framework, if it is needed.

**Comment by danwulff** [comment]
Android 10 is now released: https://twitter.com/Android/status/1168935724655218691

I'm really hoping the above changes can be completed relatively soon.

**Comment by audkar** [comment]
@HansMuller so Android 10 stable is officially released. What would be flutter team recommendations for Flutter apps which navigation is based on NavigationDrawer? My app is unusable now...

**Comment by HansMuller** [comment]
@audkar The app drawer should still open with a long-press swipe and with its appbar button. Why is your app unusable?

**Comment by audkar** [comment]
Yes, sorry. Was trying on old emulator which didn't had long-press.

**Comment by shihaohong** [comment]
I've moved the items in my [original comment](https://github.com/flutter/flutter/issues/32748#issuecomment-521048122) over to its own issue (see https://github.com/flutter/flutter/issues/39858) to help others easily find the work that needs to be done. I will close this in favor of the other issue.

**Comment by Zee2** [comment]
What is the status on this? As of November 2020, there is still no way to do proper draw-behind-the-navbar Android Q-style rendering with Flutter. This is really important!

**Comment by carldressler** [comment]
The issue with the Drawer is still not resolved. There is a workaround though:

`
Scaffold(
  drawer: Drawer(),
  drawerEdgeDragWidth: MediaQuery.of(context).size.width,
  // ...
)
`

This allows swiping from the entire screen width.
