### ISSUE TITLE
Support AOT .so (--build-shared-library) compilation for Android arm64

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#32743]
It works for 32 but not 64 right now.

/cc @mkustermann @blasten @jonahwilliams

**Comment by blasten** [comment]
It would be great to also extend the support to x86 and x64.

**Comment by mkustermann** [comment]
Doing so for x64 should be easy. The Dart VM doesn't have AOT for ia32, so that will not be possible.

**Comment by dnfield** [comment]
From other discussion, but related to this: it would be nice if the tool supported writing an ELF binary directly without requiring users to have the NDK toolchain.

/cc @chinmaygarde @rmacnak-google

**Comment by chinmaygarde** [comment]
xref https://dart-review.googlesource.com/c/sdk/+/81323

**Comment by mkustermann** [comment]
Nowadays we emit ELF directly, so I think this issue is obsolete.

Closing, please re-open if this is not the case.
