### ISSUE TITLE
 windows,v1.5.4-hotfix.2,can't use timeline/ flutter screenshot --type=skia --verbose --observatory-port=

### ISSUE THREAD

**Issue by yongwn** [flutter/flutter#32750]
version：[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 6.1.7601], locale zh-CN)

when I use this version，I can't use timeline in chrome, 
when I use flutter screenshot --type=skia --verbose --observatory-port=xxxx , terminal show as follow:

PS D:\> flutter screenshot --type=skia --verbose --observatory-port=55555
[  +14 ms] executing: [D:\Program Files\flutter\] git log -n 1 --pretty=format:%H
[ +120 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 7a4c33425ddd78c54aba07d86f3f9a4a0051769b
[        ] executing: [D:\Program Files\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +112 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.5.4-hotfix.2-0-g7a4c33425
[   +8 ms] executing: [D:\Program Files\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +103 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [D:\Program Files\flutter\] git ls-remote --get-url origin
[  +99 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +131 ms] executing: [D:\Program Files\flutter\] git rev-parse --abbrev-ref HEAD
[ +101 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +274 ms] executing: E:\AndroidSdk\Sdk\platform-tools\adb.exe devices -l
[  +57 ms] Exit code 0 from: E:\AndroidSdk\Sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           UYT0117727000225       device product:ALP-AL00 model:ALP_AL00 device:HWALP transport_id:4
[  +25 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FuchsiaCacheArtifacts' is not required, skipping update.
[  +61 ms] Exception attempting to connect to Observatory: WebSocketException: Connection to
'http://127.0.0.1:55555/ws#' was not upgraded to websocket
[   +4 ms] This was attempt #1. Will retry in 0:00:00.100000.
[ +123 ms] Exception attempting to connect to Observatory: WebSocketException: Connection to
'http://127.0.0.1:55555/ws#' was not upgraded to websocket
[   +5 ms] This was attempt #2. Will retry in 0:00:00.200000.
[ +224 ms] Exception attempting to connect to Observatory: WebSocketException: Connection to
'http://127.0.0.1:55555/ws#' was not upgraded to websocket
[   +5 ms] This was attempt #3. Will retry in 0:00:00.400000.
[ +414 ms] Exception attempting to connect to Observatory: WebSocketException: Connection to
'http://127.0.0.1:55555/ws#' was not upgraded to websocket
[   +1 ms] This was attempt #4. Will retry in 0:00:00.800000.
[ +822 ms] Exception attempting to connect to Observatory: WebSocketException: Connection to

at last, I found para  “disable-service-auth-codes” in https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/engine/FlutterShellArgs.java

there is no problem with cmd “flutter run --profile --trace-skia -v --observatory-port=55555 --disable-service-auth-codes
” ,so I think should update docoument and also infomation of "flutter  run -h", I can't find any information of disable-service-auth-codes , and it is default on

**Comment by stuartmorgan** [comment]
I would imagine that the right fix is to have the tool provide something like `--observatory-uri` instead of `--observatory-port`, rather than encouraging `--disable-service-auth-codes`
