### ISSUE TITLE
Will the official Firebase Cloud Messaging plugin ever support receiving data messages on Android when the app is terminated?

### ISSUE THREAD

**Issue by dshukertjr** [flutter/flutter#32751]
I would like to show images in my notification, which is only supported in data messages, which will not be received on Android when the app in terminated, and therefore I am forced to use notification message, which I cannot show images within the notification.

**Comment by superciccio** [comment]
have you seen this one, 
[](https://pub.dev/packages/flutter_local_notifications
)should also handle when app is closed

**Comment by marianoarga** [comment]
Related to #22072

**Comment by kroikie** [comment]
flutter/plugins#1900 should allow you to handle background messages in your Dart code on Android.

**Comment by BondarenkoStas** [comment]
the PR was merged on September 6, @dshukertjr please try if it works for you. I'm going to close the issue, if you have any new input please comment and I will re-open it.
