### ISSUE TITLE
How can I change TextFormField widget cursor color?

### ISSUE THREAD

**Issue by qbszxy** [flutter/flutter#32754]
I can change the TextField widget cursor color with attribute "cursorColor".   And I have been told that TextFormField widget  contain TextField widget 's attribute,but I can't use "cursorColor" to change TextFormField widget's cursor color.
So I am confused,How can I change TextFormField widget cursor color?

**Comment by daniilguit** [comment]
As a workaround you can use `FormField` and build any TextField you want inside it:
```
FormField(builder: (field) => TextField(...))
```

**Comment by shihaohong** [comment]
Seems to be working on master and stable branches. Attempted the following: 
```
TextFormField(
  cursorColor: Colors.orange,
),
```

<img width="264" alt="Screen Shot 2019-05-20 at 2 58 46 PM" src="https://user-images.githubusercontent.com/27032613/58054565-ce74d580-7b0f-11e9-9dcd-577b9a88b3cb.png">

Is there a particular set of circumstances that is causing your issue?
