### ISSUE TITLE
flutter build error

### ISSUE THREAD

**Issue by riyouxi** [flutter/flutter#32752]
I/flutter (31628): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (31628): The following assertion was thrown building
I/flutter (31628): RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#c4eb7](state:
I/flutter (31628): RawGestureDetectorState#56612(gestures: <none>, behavior: opaque)):
I/flutter (31628): 'package:flutter/src/painting/basic_types.dart': Failed assertion: line 222 pos 10: 'textDirection
I/flutter (31628): != null': is not true.
I/flutter (31628): 
I/flutter (31628): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (31628): more information in this error message to help you determine and fix the underlying cause.
I/flutter (31628): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (31628):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (31628): 
I/flutter (31628): When the exception was thrown, this was the stack:
I/flutter (31628): #2      textDirectionToAxisDirection (package:flutter/src/painting/basic_types.dart:222:10)
I/flutter (31628): #3      Viewport.getDefaultCrossAxisDirection (package:flutter/src/widgets/viewport.dart:128:16)
I/flutter (31628): #4      Viewport.createRenderObject (package:flutter/src/widgets/viewport.dart:139:58)
I/flutter (31628): #5      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4586:28)
I/flutter (31628): #6      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5066:11)
I/flutter (31628): #7      _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:186:11)
I/flutter (31628): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4964:14)
I/flutter (31628): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4964:14)
I/flutter (31628): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4964:14)
I/flutter (31628): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4964:14)
I/flutter (31628): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3838:16)
I/flutter (31628): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3648:5)
I/flutter (31628): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3810:5)
I/flutter (31628): #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3952:11)
I/flutter (31628): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3805:5)
I/flutter (31628): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4964:14)
I/flutter (31628): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3838:16)
I/flutter (31628): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3648:5)
I/flutter (31628): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3810:5)
I/flutter (31628): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3805:5)
I/flutter (31628): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4964:14)
I/flutter (31628): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4964:14)
I/flutter (31628): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4964:14)
I/flutter (31628): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #47     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4964:14)
I/flutter (31628): #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3838:16)
I/flutter (31628): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3648:5)
I/flutter (31628): #52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3810:5)
I/flutter (31628): #53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3805:5)
I/flutter (31628): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3838:16)
I/flutter (31628): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3648:5)
I/flutter (31628): #58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3810:5)
I/flutter (31628): #59     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3952:11)
I/flutter (31628): #60     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3805:5)
I/flutter (31628): #61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3838:16)
I/flutter (31628): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3648:5)
I/flutter (31628): #65     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3810:5)
I/flutter (31628): #66     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3952:11)
I/flutter (31628): #67     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3805:5)
I/flutter (31628): #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3838:16)
I/flutter (31628): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3648:5)
I/flutter (31628): #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3810:5)
I/flutter (31628): #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3805:5)
I/flutter (31628): #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3838:16)
I/flutter (31628): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3648:5)
I/flutter (31628): #78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3810:5)
I/flutter (31628): #79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3805:5)
I/flutter (31628): #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3838:16)
I/flutter (31628): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3648:5)
I/flutter (31628): #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3810:5)
I/flutter (31628): #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3805:5)
I/flutter (31628): #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3044:14)
I/flutter (31628): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2847:12)
I/flutter (31628): #88     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:933:16)
I/flutter (31628): #89     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:904:5)
I/flutter (31628): #90     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:850:17)
I/flutter (31628): #91     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:19)
I/flutter (31628): #92     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:849:13)
I/flutter (31628): #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
I/flutter (31628): #94     runApp (package:flutter/src/widgets/binding.dart:780:7)
I/flutter (31628): #95     main (package:flutterpro/main.dart:4:16)
I/flutter (31628): #96     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:200:25)
I/flutter (31628): #101    _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:192:5)
I/flutter (31628): #102    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
I/flutter (31628): #103    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
I/flutter (31628): (elided 6 frames from class _AssertionError and package dart:async)
I/flutter (31628): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/art     (31628): Ignoring second debugger -- accepting and dropping

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
