### ISSUE TITLE
./flutter/tools/gn --ios --unoptimized

### ISSUE THREAD

**Issue by softwarefaith** [flutter/flutter#32753]
```bash
n gen --check in out/ibashos_debug_unopt
Traceback (most recent call last):
  File "./flutter/tools/gn", line 373, in <module>
    sys.exit(main(sys.argv))
  File "./flutter/tools/gn", line 348, in main
    gn_call_result = subprocess.call(command, cwd=SRC_ROOT)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by stuartmorgan** [comment]
Did your `gclient sync` step complete successfully?

**Comment by softwarefaith** [comment]
> Did your `gclient sync` step complete successfully?
already show:   Syncing projects: 100% (91/91), done.

**Comment by Kila2** [comment]
have same issue. you can exec ./src/buildtools/update.sh but will get another error.
eg.
`ERROR at //third_party/dart/build/dart/dart_action.gni:101:3: Assertion failed.
  assert(_is_fuchsia || prebuilt_dart_exe_works,
  ^-----
A pre built dart executable needs to be present
See //third_party/dart/build/dart/dart_action.gni:180:3: whence it was called.
  _prebuilt_tool_action(target_name) {
  ^-----------------------------------
See //third_party/dart/utils/compile_platform.gni:42:3: whence it was called.
  prebuilt_dart_action(target_name) {
  ^----------------------------------
See //flutter/lib/snapshot/BUILD.gn:234:1: whence it was called.
compile_platform("strong_platform") {
^------------------------------------
See //flutter/BUILD.gn:17:5: which caused the file to be included.
    "$flutter_root/lib/snapshot:generate_snapshot_bin",
    ^-------------------------------------------------
`

**Comment by Kila2** [comment]
I found that the cause of this problem may be that the src/third_party/dart/tools/sdks/dart-sdk/bin directory is empty.

**Comment by huangchuqiang** [comment]
> have same issue. you can exec ./src/buildtools/update.sh solve it .but will get another error.
> eg.
> `ERROR at //third_party/dart/build/dart/dart_action.gni:101:3: Assertion failed. assert(_is_fuchsia || prebuilt_dart_exe_works, ^----- A pre built dart executable needs to be present See //third_party/dart/build/dart/dart_action.gni:180:3: whence it was called. _prebuilt_tool_action(target_name) { ^----------------------------------- See //third_party/dart/utils/compile_platform.gni:42:3: whence it was called. prebuilt_dart_action(target_name) { ^---------------------------------- See //flutter/lib/snapshot/BUILD.gn:234:1: whence it was called. compile_platform("strong_platform") { ^------------------------------------ See //flutter/BUILD.gn:17:5: which caused the file to be included. "$flutter_root/lib/snapshot:generate_snapshot_bin", ^------------------------------------------------- `
I have the same problem too. Did you have solved  it ?

**Comment by Kila2** [comment]
用一个好点的网，gclient sync 100%后不要中断命令让它自己自己停止。可以在流量监视器中查看.cipd的进程有没有工作。

**Comment by huangchuqiang** [comment]
> 用一个好点的网，gclient sync 100%后不要中断命令让它自己自己停止。可以在流量监视器中查看.cipd的进程有没有工作。

已解决。原来 gclient sync 100% 后还会下载一大波文件，下完脚本自己结束就可以。

**Comment by waruqi** [comment]
> > 用一个好点的网，gclient sync 100%后不要中断命令让它自己自己停止。可以在流量监视器中查看.cipd的进程有没有工作。
> 
> 已解决。原来 gclient sync 100% 后还会下载一大波文件，下完脚本自己结束就可以。

cipd需要多久，我执行到 gclient sync 100%，然后cipd卡了一个多小时 也没动静，也不见各种提示。。网ok

**Comment by Kila2** [comment]
> > > 用一个好点的网，gclient sync 100%后不要中断命令让它自己自己停止。可以在流量监视器中查看.cipd的进程有没有工作。
> > 
> > 
> > 已解决。原来 gclient sync 100% 后还会下载一大波文件，下完脚本自己结束就可以。
> 
> cipd需要多久，我执行到 gclient sync 100%，然后cipd卡了一个多小时 也没动静，也不见各种提示。。网ok

取决于DEPS中dep_type为cipd的数量

**Comment by waruqi** [comment]
> > > > 用一个好点的网，gclient sync 100%后不要中断命令让它自己自己停止。可以在流量监视器中查看.cipd的进程有没有工作。
> > > 
> > > 
> > > 已解决。原来 gclient sync 100% 后还会下载一大波文件，下完脚本自己结束就可以。
> > 
> > 
> > cipd需要多久，我执行到 gclient sync 100%，然后cipd卡了一个多小时 也没动静，也不见各种提示。。网ok
> 
> 取决于DEPS中dep_type为cipd的数量

已经可以了，谢谢，是因为这边磁盘空间不够，所以卡住了，这货极度耗磁盘空间哈，下了一坨的toolchains。。我清理腾出15个G，才勉强跑过。。

**Comment by rockingdice** [comment]
meet the same issue. Indeed to wait for the script ended by itself. 

```
Syncing projects: 100% (103/103), done.                                         
Running hooks: 100% (6/6), done.    
```

After the second line is shown, the script ends by itself.
I can successfully run the command now.

@stuartmorgan I think this issue could be closed now.

**Comment by javanli** [comment]
1. check network, `gclient sync` output like:
```
Syncing projects: 100% (102/102), done.                                                                                        
Hook 'vpython src/flutter/tools/android_support/download_android_support.py' took 10.67 secs
Running hooks: 100% (6/6), done. 
```

2. check **ninja** installed, if not, install it.
```
brew install ninja
```

**Comment by Wi1ls** [comment]
> have same issue. you can exec ./src/buildtools/update.sh solve it .but will get another error.
> eg.
> `ERROR at //third_party/dart/build/dart/dart_action.gni:101:3: Assertion failed. assert(_is_fuchsia || prebuilt_dart_exe_works, ^----- A pre built dart executable needs to be present See //third_party/dart/build/dart/dart_action.gni:180:3: whence it was called. _prebuilt_tool_action(target_name) { ^----------------------------------- See //third_party/dart/utils/compile_platform.gni:42:3: whence it was called. prebuilt_dart_action(target_name) { ^---------------------------------- See //flutter/lib/snapshot/BUILD.gn:234:1: whence it was called. compile_platform("strong_platform") { ^------------------------------------ See //flutter/BUILD.gn:17:5: which caused the file to be included. "$flutter_root/lib/snapshot:generate_snapshot_bin", ^-------------------------------------------------`

请问你解决了吗？我也碰到同样的问题了

**Comment by TahaTesser** [comment]
Hi @softwarefaith  
Did fresh engine local setup from latest `master` branch from engine repository, no issues when following official docs
https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment
https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-ios-from-macos
Run the application generating simulator unopt
`flutter run --local-engine=ios_debug_sim_unopt`

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
