### ISSUE TITLE
Connectivity package problem

### ISSUE THREAD

**Issue by dmvvilela** [flutter/flutter#32758]
Tried getting WiFi SSID on iOS and it justs returns null.. Am i missing something here?

**Comment by thanhqquan** [comment]
I found in the file "connectivity.dart" that missing source code of function getWifiBSSID().
I add the source code of function getWifiBSSID()(https://github.com/flutter/plugins/blob/master/packages/connectivity/lib/connectivity.dart#L52) and after that get another error
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method wifiBSSID on channel plugins.flutter.io/connectivity)
Anyone has a solution for this? Please help!

**Comment by dmvvilela** [comment]
I got it to work. You have to get a developer account and make a provision profile to accept wifi..This sucks but is needed.. thanks apple.. I just think this should be communicated on the package..
