### ISSUE TITLE
Touch up/down status for slider.dart

### ISSUE THREAD

**Issue by jdeltoft** [flutter/flutter#32768]
I'm using Flutter's Material slider.dart and the official widget supports callbacks for **onChanged**, **onChangeEnd**, and **onChangeStart**.  These start and end callbacks are a bit odd though in that they trigger on a quick tap of the slider, as well as a touch and slide of the slider that's still being held, and then they fire again when the slider thumb is released.  What I really need to know is when the slider is FULLY released (from either a quick tap OR a touch and slide).  

So I have found a way to edit .../flutter/packages/flutter/lib/src/Material/slider.dart in a way that prints out to the console the status I need.  I look at all handleEvent calls and added the following to know when touch was up or down (**see the change using event.runtimeType**):

      @override
      void handleEvent(PointerEvent event, BoxHitTestEntry entry) {
        if (event.runtimeType == PointerDownEvent) {
          _touchActive = true;
          print("---------Down!---------");
        } else if (event.runtimeType == PointerUpEvent) {
          _touchActive = false;
          print("---------Up!---------");
        }
        assert(debugHandleEvent(event, entry));
        if (event is PointerDownEvent && isInteractive) {
          // We need to add the drag first so that it has priority.
          _drag.addPointer(event);
          _tap.addPointer(event);
        }
      }

But now I need to somehow get that data back out of the widget through a callback.  The callback can be similar to any of the three mentioned earlier such as onChangeStart or onChangeEnd, but I'm not sure where all I need to update to create this.  Can anyone help point me to how to add this?

**Comment by TahaTesser** [comment]
Hi 

This seems to be no longer reproducible, `onChangeStart` and `onChangeEnd` are firing as expected, tried on mobile and desktop with tap and drag.

Given there is no odd behavior and lack of activity on this issue, I feel safe to close this.
