### ISSUE TITLE
Cannot build app while offline, fails with "Could not resolve all task dependencies for configuration"

### ISSUE THREAD

**Issue by apaolino** [flutter/flutter#32765]
In situation of scarcity of reliable internet connection android building process produces the following error:
`Could not resolve all task dependencies for configuration`

There is no way to build an android app offine?

**Comment by jonahwilliams** [comment]
You can build an android app offline, but you need to have downloaded the correct Gradle resources first. For more information, see: https://stackoverflow.com/questions/32171524/how-to-configure-gradle-to-work-offline-using-cached-dependencies
