### ISSUE TITLE
Flutter Web webdev internal server error

### ISSUE THREAD

**Issue by stemuk** [flutter/flutter#32762]
The webdev serve command suddenly stopped working after I initialized a git respository in the project folder (this might be unrelated though). The website on `localhost:8080` now displays 'Internal server error'.

Update: As it turns out, this issue is git related. Removing the hidden .git file manually resolves this issue and `webdev serve` executes as expected.

1) Command line output:
```
stefan@thinkpad:~/projects/studilabs$ webdev serve
[INFO] Please file an issue with reproduction steps at https://github.com/dart-l[INFO] Failed to watch path, path = '/home/stefan/projects/studilabs/.git/object[INFO] Serving `web` on http://localhost:8080
WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 33416
ERROR - 2019-05-15 16:33:37.908420
GET /
Error thrown by handler.
SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 40918
dart:isolate  _RawReceivePortImpl._handleMessage

```

2) flutter doctor output:

```
stefan@thinkpad:~/projects/studilabs$ flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /home/stefan/flutter
    • Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/stefan/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/stefan/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /home/stefan/android-studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • IntelliJ at /home/stefan/idea-IC-172.4343.14
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[✓] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at /home/stefan/idea-IC-183.4588.61
    • Flutter plugin version 31.1.4
    • Dart plugin version 183.4588.61

[✓] VS Code (version 1.33.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.0.1

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)

• No issues found!

```

**Comment by stemuk** [comment]
The issue appeared frequently since yesterday, so much that it is now impossible to even use webdev serve on a brandnew flutter web project. It would help tremendously if someone could look into this issue and assess wether it is caused by me or flutter itself.

**Comment by vsmenon** [comment]
fyi - @grouma @jakemac53 - do we have corresponding issue on webdev / build?

**Comment by stemuk** [comment]
@grouma @jakemac53 @vsmenon This issue https://github.com/dart-lang/webdev/issues/375 seems to report a similar problem. However, even though the issue is marked as solved, the proposed solution (upgrade everything to its latest version) isn't solving the problem for me. 

A restart of the entire system does fix the issue only for the first time the `webdev serve` command is entered. If it is used a second time after the restart, the issue is still prevalent.

**Comment by grouma** [comment]
I have reopened https://github.com/dart-lang/webdev/issues/375. Let's move discussion over there for now. We'll keep this one open for now.

**Comment by grouma** [comment]
Closing this one for now.

We have done a number of releases of `webdev` to address server start up issues. We have also updated our error logging so more detailed messages are provided to the user.

Please upgrade your version of `webdev` and reopen if you continue to experience problems.
