### ISSUE TITLE
Destroying webviews

### ISSUE THREAD

**Issue by wickedman1976** [flutter/flutter#32766]
Using the latest version 0.3.7+1 there doesn't seem to be a way of destroying either the controller or webview.  Would expect a dispose method to be called on destroying the widget that the webview sits in.  

1) Run any flutter project with webviews in on iOS simulator
2) Use a pageview widget
3) as you swipe through the pages they call the dispose method but that does not remove webview from safari developer tools.

Thanks

Nathan

**Comment by Dronaldo17** [comment]
some question

**Comment by iapicca** [comment]
Hi @wickedman1976 
are you still experiencing this issue with the latest stable version of flutter?
If so could you please provide your updated `flutter doctor -v` 
and your `flutter run --verbose` and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by TahaTesser** [comment]
Hi @wickedman1976 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
