### ISSUE TITLE
Google Maps rendered outside bounds of scroll

### ISSUE THREAD

**Issue by benmeemo** [flutter/flutter#32774]
I'm making an application with a scrollview underneath another widget. When a google maps widget is in the scrollview, and the scrollview scrolls up such that the google maps widget is past the bounds of the scrollview, the google map widget is rendered outside of its scrollview. 

## Sample code to reproduce

```Dart
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children: <Widget>[
          Container(
            height: 100,
            color: Colors.red,
          ),
          Expanded(
            child: SingleChildScrollView(
              child: Column(
                children: <Widget>[
                  Container(
                    height: 100,
                    color: Colors.yellow,
                  ),
                  Container(
                    height: 300,
                    child: GoogleMap(
                      initialCameraPosition: CameraPosition(
                        target: LatLng(37.42796133580664, -122.085749655962),
                        zoom: 14.4746,
                      ),
                    ),
                  ),
                  Container(
                    height: 2000,
                    color: Colors.blue,
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

```
 ## Flutter Doctor

[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/benulmer/development/flutter
    • Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/benulmer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • iPhone Xʀ • 8DD3F68E-E58F-43E7-A221-BD6DDBAF73D5 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2
      (simulator)

• No issues found!

## Logs

Didn't want to attach logs as they were incredibly long, but there weren't any errors. Happy to provide them though if they might be helpful.

**Comment by VladyslavBondarenko** [comment]
I checked, can't see any issue with this.
Closing since probably fixed.

This is what I see with flutter master v1.15.19-pre.17, google_maps_flutter 0.5.24+1 and iOS 13.3 (simulator).

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17024977/76228196-12fd6900-6229-11ea-98dc-d8eb9c172439.gif)

Please file a new issue if you are still experiencing this
