### ISSUE TITLE
[web]: Printing does not work

### ISSUE THREAD

**Issue by goodmansasha** [flutter/flutter#32777]
Describe your issue and include the command you're running, flutter_web version, browser version.

Printing from a printer does not work. The print preview on 'Slide puzzle' is completely blank, and there is only 1 out of 1 pages to print.

This applies to almost every example at https://flutter.github.io/samples/ . 

Given that flutter can make use of the browser in a standards compliant way, I suspect this can be addressed eventually. I now see that https://github.com/flutter/flutter/issues/32249 also deals with this.

**Comment by elibwhittle** [comment]
Also looking for a solution to this problem

**Comment by BondarenkoStas** [comment]
@goodmansasha I will close the issue to avoid duplication, as #32249 contains the details, please continue to follow it there.

**Comment by RahulNode** [comment]
The print function is not working on web flutter.


Future createWidget() async{
  final jsonResponse = json.decode(_element);
  debugPrint(jsonResponse.topWidget);
  for(var i in jsonResponse.topWidget){
    debugPrint(i);
  }


`}`

**Comment by edex96** [comment]
print works one time and doesnt work another time its the same exact code nothing changed except time 😕 

:D frankly last night I have discovered that the current version of master channel for web has isssues with dart

for loops, list operations assignments and await doesnt work as excpected all the time
