### ISSUE TITLE
[cloud_firestore] metadata is missing for QuerySnapshot class

### ISSUE THREAD

**Issue by shasaf1986** [flutter/flutter#32789]
## Use case
I have disabled the persistent mode in my app and I am looking for solution to identify unsuccessful firestore read. 
Seems like firestore always returns successful result (via Future / Stream) in query case.
The metadata should contain isFromCache property which can indicate if the read was failed or not.
The metadata is already implemented in other sdks such as js,dart (html) and more (see references)

https://pub.dev/documentation/firebase/latest/firebase_firestore/QuerySnapshot-class.html
https://firebase.google.com/docs/reference/js/firebase.firestore.QuerySnapshot

## Proposal
Please implement it, Thanks a lot

**Comment by kroikie** [comment]
@shasaf1986

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1228. Any further collaboration will be done there.
