### ISSUE TITLE
[Camera Plugin] Autofocus doesn't work on older Samsung Galaxy devices

### ISSUE THREAD

**Issue by andrewmcdnz** [flutter/flutter#32785]
Raising an issue as I can't see one that already exists for this, and it likely impacts a large number of devices.

In testing the Camera plugin with one of my test devices, a Samsung Galaxy S5, I found the autofocus would not work despite it working fine on my other phones.

After investigating, it seems this is a well known issue with Samsung's implementation of Camera2 API that impacts older devices (Galaxy S4, S5 and S6 and similar). It seems it's best  avoided by using the legacy 'Camera1' API with these phones. The determination to switch between camera APIs could be made by looking at the INFO_SUPPORTED_HARDWARE_LEVEL from Camera2.CameraCharacteristics, falling back to Camera1 if LEGACY is returned, as seems to be the case on the S5.

May be worth considering this current limitation when making a priority call for adding the Camera1 support to the plugin. This was a total showstopper for my application, which involves a form of close-range document capture but thankfully I have managed to work around it by instead launching the native camera using a platform channel call on Android devices.

Tested with Camera Plugin v0.5.0

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.13.6 17G6030,
    locale en-NZ)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.4)

## Steps to Reproduce

On a Samsung Galaxy S5 or similar...
1. Build and launch the Camera plugin's example application (v0.5.0)
2. Enable the back (main) camera
3. Observe that autofocus does not work

**Comment by Afsalpp** [comment]
How can I add auto focus in flutter camera?

**Comment by Thetyne** [comment]
same on Galaxy A70

**Comment by andrewmcdnz** [comment]
> same on Galaxy A70

That's really interesting. The A70 is not an old phone at all. Maybe try run OpenCamera (best to run from source with verbose logging) and see if it does any better. On my S5, it falls back to Camera1 and AF works okay. If I force Camera2 then I get no autofocus, same as Flutter's plugin.

**Comment by Thetyne** [comment]
It's work if i disable multiple samsung option in camera application.

**Comment by Thetyne** [comment]
It works with a new version of camera plugin :)
Thanks

**Comment by jargalbat** [comment]
Autofocus doesn't work on Samsung Galaxy J5.
camera: ^0.5.7+3

**Comment by andrewmcdnz** [comment]
> It works with a new version of camera plugin :)
> Thanks

Perhaps you can explain a little bit more about how you got this to work on the A70, but based on what you've said it would seem that the issue you encountered is different to this one. After all, the A70 is a very new phone and really should have mature support for the Camera2 API. 

Using 0.5.7+3, I can confirm that autofocus still does not work on my tester Galaxy S5.

**Comment by Thetyne** [comment]
sorry i can't explain it. I have just change camera: 0.5.4+2 to 0.5.7+3.
the problem may be elsewhere...

**Comment by JDDV** [comment]
I tried to reproduce the same problem with multiple Samsung devices, but I cannot reproduce the same problem

Camera plugin version:
 - 0.8.0-nullsafety

Devices:
 - Samsung S9 (Android 10)
 - Samsung S6 (Android 7)
 - Samsung A20 (Android 10)

Steps I took to reproduce:
 - Build and launch the Camera plugin's example application (v0.5.0)
 - Enable the back (main) camera
 - Observe autofocus behaviour

<details>
     <summary>Flutter doctor -v</summary>

```
[√] Flutter (Channel beta, 1.26.0-17.6.pre, on Microsoft Windows [Version 10.0.19041.804], locale nl-NL)
    • Flutter version 1.26.0-17.6.pre at C:\Baseflow\flutter
    • Framework revision a29104a69b (3 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Jan-Derk\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Users\Jan-Derk\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Jan-Derk\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Users\Jan-Derk\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\202.7660.26
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

</details>

Can you confirm if the problem still exsists in the newest version of the camera plugin?

**Comment by andrewmcdnz** [comment]
I have re-tested on my Galaxy S5 with the latest stable release ^0.7.0+2 and auto focus still does not work.

This phone is now very old, and in all honesty the issue is Samsung's more than the author's. They did a lousy job at supporting Camera2 API on this phone. From my testing, the camera plugin would have to add support for the legacy Camera1 API in order to address this and at this stage I do not see this ever happening.

If anyone stumbles across this issue and lands here, the solution I went with in the end was to launch the native phone camera and avoid this plugin. Image picker plugin makes this very easy.

In light of the above, I am closing this issue.
