### ISSUE TITLE
Hi,how to add hint after this mark ")" ?

### ISSUE THREAD

**Issue by bladeofgod** [flutter/flutter#32798]
## Steps to Reproduce

1. i got a hint problem: my hint that the after ")", is disappeared, and i checked the setting of AS,cant restore it . so plz tell me how to fix this problem. 
thanks  a lot.  :)

## Logs

```
```

```
```

**Comment by KirolousNashaat** [comment]
u mean hint like 
Container(
child: widget(),
), **//Container** 
if yes then u should file the issue in https://github.com/flutter/flutter-intellij/issues
if not can u explain the problem ?

**Comment by bladeofgod** [comment]
yes,that's it; thanks a lot ,i will remove my problem to that  zone .

**Comment by bladeofgod** [comment]
im gonna close this issuse.
