### ISSUE TITLE
How to get the rotation direction？

### ISSUE THREAD

**Issue by guodf** [flutter/flutter#32808]
This rotation value is sometimes positive, sometimes negative, I don't understand, I want to get the direction of rotation.

```dart
onScaleUpdate(details){
  //Whether to consider adding a rotation direction:
  print(details.direction);
   print(details.rotation);
}
````

**Comment by BondarenkoStas** [comment]
https://api.flutter.dev/flutter/dart-ui/Offset/direction.html
