### ISSUE TITLE
about the products of aar

### ISSUE THREAD

**Issue by moonljt521** [flutter/flutter#32800]
The problem about the package of aar: I opened the flutter module with android studio, and build in local, it will generate an aar , the aar file has no problem, and it will contain intermediate products. Then I packaged it and uploaded it to the  maven by ourselves ,using of the commanding of upload Archives , but the generated aar would not contain” isolate snapshot instr”、“isolate snapshot data”and other products.At the same time,it did not contain the resource of assets also. It should be the process of gradle in the flutter project including the process of “flutter.gradle”(copy products and other operations). I have used a stupid way to write the script--local packaging firstly, and then decompressed the products and resources in the local aar, copied these to the project path and then packaged、 uploaded.I have knowen that it was not elegant at all, but I did not know how to do it better. Can you give any official advice? Greatfully.

------ flutter doctor
[✓] Flutter (Channel master, v1.5.9-pre.235, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)

**Comment by jinyulei0710** [comment]
![1559345813770](https://user-images.githubusercontent.com/3348074/58740310-372e4d00-8442-11e9-88ad-206d5ad1e12e.jpg)
use the task under the app. it works. @moonljt521

**Comment by moonljt521** [comment]
谢谢，我自己暂时总结了个脚本
