### ISSUE TITLE
Tap target size too small for upper-left button

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3280]
Some feedback from a reviewer today: "The tap targets for the upper-left button in the app bar menus feel too small."

Some subjective testing seems to confirm this.

**Comment by abarth** [comment]
The IconButton doesn't fill the toolbar vertically (or horizontally).  We probably need to adjust the layout so that the hittable region for the icon button fills the toolbar.

**Comment by vlidholt** [comment]
It would be useful if the tappable area could be made larger than the component itself. Perhaps by setting a property on the GestureRecognizer.

**Comment by Hixie** [comment]
That would have significant perf implications, unfortunately.

**Comment by abarth** [comment]
Let's expand the hit target to fill the toolbar height (and corresponding width) and see how far that gets us.  Oversized hit testing has a bunch of negatives (including performance).

**Comment by Timmmm** [comment]
I've tested recent builds of the Gallery ("2016 Q3 Preview" apparently) and this still isn't very good to be honest. The hit area of the hamburger / back button in the top left doesn't really get close to the left edge of the screen which is where you are most likely to tap it.

What exactly are the performance implications of having hit areas larger than components? It seems like an essential feature in a touch-based UI.

Also in the Pesto app, you can't tap the top half of the heart FAB. I think hit areas need some work.

**Comment by eseidelGoogle** [comment]
Thanks for the report.  @Timmmm would you be willing to file a fresh issue?  https://github.com/flutter/flutter/issues/new  @HansMuller indicated this morning that he's interested in doing a bit more work here, and any information you could provide would be helpful!

**Comment by HansMuller** [comment]
Making the tappable area of the hamburger/back appbar button should be doable, and I agree that doing so would improve usability.

I think Pesto's tiny heart is just a bug :-). Will fix that as well.

**Comment by xster** [comment]
Duping into #5201
