### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchFieldError: FN_AAPT2

### ISSUE THREAD

**Issue by HelloJack0** [flutter/flutter#32810]
## Steps to Reproduce

1. ...flutter doctor
2. ...flutter doctor --android-licenses
3. ...sdkmanager --update
![`XN@BR2PI 3W9W@ICRZOCK3](https://user-images.githubusercontent.com/47816656/57851518-59558780-7813-11e9-9dfd-6ecb22b6774a.png)

```
```

`F:\Develop Work\flutter>flutter doctor -v
[âˆš] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    â€¢ Flutter version 1.5.4-hotfix.2 at F:\Develop Work\flutter
    â€¢ Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    â€¢ Engine revision 52c7a1e849
    â€¢ Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    â€¢ Android SDK at D:\eclipse
    â€¢ Android NDK location not configured (optional; useful for native profiling support)
    â€¢ Platform android-Q, build-tools 28.0.3
    â€¢ ANDROID_HOME = D:\eclipse
    â€¢ Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[âˆš] Android Studio (version 3.0)
    â€¢ Android Studio at D:\Program Files\Android\Android Studio
    â€¢ Flutter plugin version 23.2.1
    â€¢ Dart plugin version 171.4424
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    â€¢ IntelliJ at F:\ä¸‹è½½ç›®å½•\ideaIU-2018.1.win
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    â€¢ For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by HelloJack0** [comment]
I reinstall sdkmanager

**Comment by Vedant-Dev** [comment]
Did you upgarade or installed same version
