### ISSUE TITLE
CallBack action from ANDROID to FLUTTER

### ISSUE THREAD

**Issue by JavaThirumalG** [flutter/flutter#32812]
In Flutter,
I have started an android activity from the flutter.
After that when we do some action on android activity screen need to send action back to the flutter.

Please let me know the simple and better solution for this situation.

**Comment by vintage** [comment]
Github issues are not a good place for asking this type of questions - you should have more luck asking it on stackoverflow/slack/discord.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
