### ISSUE TITLE
EventChannel.StreamHandler onCancel method is not called on Activity destroy

### ISSUE THREAD

**Issue by audkar** [flutter/flutter#32818]
## Steps to Reproduce

I have created simple application to reproduce this problem https://gist.github.com/audkar/abe61f4d32a0db479ddcd2dcb11a9fd3

1. Start application on Android platform
2. Press *back* button. [Expecting here to receive call to `EventChannel.StreamHandler.onCancel(args)`]
3. Open application again
4. Counter shows `2`.

This sequence can be repeated indefinitely. Each time plugin receives `onListen` call. But no `onCancel`.

In real world example we have long running ForegroundService which keeps Android Application alive. However `Activity` is often destroyed by system or closed by user. Such behavior leaks resources and leaves running tasks.

## flutter doctor

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /home/audrius/Documents/flutter
    • Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```

**Comment by pedromassangocode** [comment]
Hi @audkar 
Are you still facing this issue?

**Comment by audkar** [comment]
Don't know. We stopped using Flutter.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
