### ISSUE TITLE
flutter attach stays alive

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32824]
The ergonomics of flutter attach for add-to-app scenarios are poor. 
Development is often an interweaved mix of tweaking native code and tweaking flutter code.

Tweaking flutter code should be hot reloaded. Tweaking native code breaks existing resident runners and need another manual attach after each native code rerun. 

I should be able to run `flutter attach monitor` where it doesn't stop after disconnecting and always looks for a new connection when un-attached.

**Comment by jonahwilliams** [comment]
This sounds like a really great improvement to the tool UX.  cc @DanTup and @devoncarew for thoughts on IDE integration

**Comment by DanTup** [comment]
Sounds like a good idea to me. Right now the IDEs (or at least VS Code) assumes we'll only ever attach to a single app and when it quits, we disconnect. We'd probably need some daemon protocol changes to support an `app.stop` that signals the daemon will wait and try to reconnect. We'd also need to make the IDEs support disconnecting from the VM, clearing any state and then reconnecting (potentially on another URI) with the same session (currently when the VM connection dies, we terminate the session).

It sounds like this is a similar problem to pressing Refresh in the browser for web - the app is basically killed and starts again. I think for that it's all handled in the proxy (transparent to the IDE) - is there value in trying to align how these work?

**Comment by xster** [comment]
@InMatrix in case you have input on the UX. 

In terms of IDE UX, I think it should be fairly straightforward. It's a checkable button, press it, it attaches to the currently advertising VM or waits for the next one. Uncheck it and it either detaches from the attached daemon or stops trying to wait. 

The various combinations of attach once with the attach monitor button checked state should be fairly straight forward.

**Comment by xster** [comment]
@stevemessick @DanTup: by the current trend that @blasten is going towards, I think instead of a separate CLI command, we're just going to make the existing `flutter attach` long living until the user exits. In other words, instead of the `flutter attach` process dying when the first attached process dies, it'll just go back to waiting for another connection. 

The good news is that we don't have to add new buttons to the IDE. Just a heads up in case this long living nature needs any non-trivial tweaks in the IDEs.

**Comment by DanTup** [comment]
Sounds good. Whether any IDE work is required may depend on how it's implemented. There's a bunch of stuff we do at startup that would be skipped, but some of it happens when new isolates spawn, so assuming the old isolate exits and a new one starts when it connects to a new app, that might mostly handle it (though we may need to make sure we handle a period with 0 isolates, and than we track the new isolate as the "main isolate" to send things like hot reload to).

Where is the best place to follow updates so I can do some testing when it's far enough? (here?)

**Comment by devoncarew** [comment]
> we're just going to make the existing flutter attach long living until the user exits. In other words, instead of the flutter attach process dying when the first attached process dies, it'll just go back to waiting for another connection

How much of a burden is it to require that user to re-run and re-attach to a Flutter app when there are changes to the native side? I'd guess that even in an add2app scenario, many of the changes would be happening on the Flutter side.

IDEs would need to be changed to accommodate this. We currently use the termination of the `flutter attach` process as a signal that the app has finished. Instead, we'd need to do something like expect a series of `app.start` (https://github.com/flutter/flutter/blob/master/packages/flutter_tools/doc/daemon.md#appstart) and `app.stop` events from the daemon protocol from the flutter attach process:

```
<process start> app.start (app.stop app.start)* app.stop <process termination>
```

**Comment by xster** [comment]
There will likely be a period with no VM and VM with 0 isolates in between when the new app process starts. The user is likely to not start the VM or run a FlutterEngine early on in their app. 

You should be able to follow progress on this issue thread.

**Comment by DanTup** [comment]
> There will likely be a period with no VM and VM with 0 isolates in between when the new app process starts.

Some of this is similar to web - I think when a user hits Refresh in the browser there will be 0 isolates during the reload - however the proxy remains alive and doesn't change (we don't need to reinitialise all that) so we don't need to connect to a new server and reinitialise.

> How much of a burden is it to require that user to re-run and re-attach to a Flutter app when there are changes to the native side?

If we made the process of reattaching to the same app on the same device easy in the editors (eg. just a simple button press) then maybe we could get away without changing anything in the debuggers? You hit rebuild for the native code, the debugger disconnects from the old session (when the app terminates), you click this one button and it sits with a progress indicator waiting for the app to finish launching and attaches?

**Comment by xster** [comment]
> How much of a burden is it to require that user to re-run and re-attach to a Flutter app when there are changes to the native side?

I think not too much like @DanTup suggested if the 'workaround' is smoothly done. Though I don't think there's ever a reason to intentionally make it so. I think it just adds a bit of friction (as small as we can make it) with no clear up-side.

**Comment by xster** [comment]
This is done. The CLI `flutter attach` is now long living. IntelliJ has an equivalent solution now in https://github.com/flutter/flutter-intellij/pull/4200.

A branch-off issue exists in vscode with https://github.com/Dart-Code/Dart-Code/issues/2115.
