### ISSUE TITLE
Microsoft Azure Active Directory authentication flow for mobile app Update flutter (firebase_auth)

### ISSUE THREAD

**Issue by yugandh** [flutter/flutter#32829]
Recently firebase released microsoft azure authentication to login in to the mobile app.
Currently there is native ios and android plugin.

**There is no  flutter plugin** 

Reference:
https://firebase.google.com/docs/auth/ios/microsoft-oauth

**Comment by stickycitrus** [comment]
Yes Please. Need this one.

**Comment by lukelima** [comment]
Need it too ! =D

**Comment by RakhimyanTim** [comment]
Me too

**Comment by Eddydpyl** [comment]
Same here!

**Comment by buddhishan** [comment]
Me too

**Comment by kroikie** [comment]
@yugandh

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1107. Any further collaboration will be done there.
