### ISSUE TITLE
Provide JavaDoc config in Intellij metadata templates

### ISSUE THREAD

**Issue by audkar** [flutter/flutter#32822]
## Use case

Would be very useful to see JavaDocs for Flutter SDK in AndroidStudio/Intellij IDE. Currently `Dart_sdk.xml` is created with empty `<JAVADOC />`

## Proposal

Distribute JavaDoc with flutter sdk libraries and add paths in Intellij config template.

**Comment by gspencergoog** [comment]
Flutter doesn't use javadoc for our document generation (we use dartdoc), so I don't think this would be all that helpful: it would only show a few Android files from the engine.
