### ISSUE TITLE
Allow loading data to webviews

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#32827]
## Use case

Developers sometimes wants a webview to render a page from a string.
For example this is done in the webview_flutter example app for the [navigation delegate example](https://github.com/flutter/plugins/blob/e4cab7a56f43b9ff63b787adc04a7ebaf364256a/packages/webview_flutter/example/lib/main.dart#L12).
While this can currently be done using [data URIs](https://github.com/flutter/plugins/blob/e4cab7a56f43b9ff63b787adc04a7ebaf364256a/packages/webview_flutter/example/lib/main.dart#L253) that approach has a few drawbacks:

- A base url cannot be specified which means scripts are unable to access content loaded using any scheme other than 'data'.
- Converting the data to base64 is required even if the backing webview doesn't require it.
- It requires some boilerplate.

## Proposal

Add a `loadData` method to `WebViewController`:
```dart
Future<void> loadData({@required String data, @required String mimeType, String baseUrl});
```

This will use [[loadHtmlString:baseUrl]](https://developer.apple.com/documentation/webkit/wkwebview/1415004-loadhtmlstring?language=objc) on iOS and [loadWithBaseUrl](https://developer.android.com/reference/android/webkit/WebView#loadDataWithBaseURL(java.lang.String,%2520java.lang.String,%2520java.lang.String,%2520java.lang.String,%2520java.lang.String)) on Android.

Note that https://github.com/flutter/plugins/pull/1312 and https://github.com/flutter/plugins/pull/1137 are both trying to solve the same problem but need some more work (we can resolve this issue either with a new PR or by iterating on one of those PRs)

**Comment by stuartmorgan** [comment]
This was fixed in 2.4.0
