### ISSUE TITLE
CircularProgressIndicator draws outside of its bounds

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#3282]
It appears that the stroked outline is just outside of its constraint rect. This makes it difficult to precisely control CircularProgressIndicator's size. I think it would be easier to manage this widget if enclosing it in a SizedBox assured that nothing would be drawn outside the box.

**Comment by HansMuller** [comment]
When drawing wide lines with Canvas x,y correspond to the center of the line. Perhaps CircularProgressIndicator isn't taking this into account.

**Comment by Hari-07** [comment]
Any clues as to how this could be fixed? I can try to contribute, if anyone has any ideas about what could potentially be causing this could help

**Comment by Hixie** [comment]
The fix is probably to pad the widget with half the stroke width on each side, if we want to do it. However, it would likely be quite breaking since by now lots of apps depend on the exact behavior. Is it worth making this optional, or should we just not do it?

**Comment by AlexV525** [comment]
> However, it would likely be quite breaking since by now lots of apps depend on the exact behavior. Is it worth making this optional, or should we just not do it?

Can we identify if any internal tests or Golden tests rely on this?

**Comment by AlexV525** [comment]
With #125945, supporting this will not be a breaking change. It takes the same design of `BorderSide.strokeAlign` which defaults to `.center` same as the current situation.
