### ISSUE TITLE
Add support for `--tags` for flutter test command line flags

### ISSUE THREAD

**Issue by daniel-v** [flutter/flutter#32836]
## Use case

I have some expensive integration tests that require special setup before being ran (env setup). I do not wish to always run these during development, therefore I tag them with `slow` or `integration`. Something along those lines.

I'd like to be able to:
`flutter test --tags "integration || slow" ` 
or quite the opposite
`flutter test --tags "!integration && !slow"`

## Proposal

For my use-case to work, I'd need `flutter test` command to consider `dart_test.yaml` and have support for `--tags` and `--preset` flags.

**Comment by maxlapides** [comment]
It is also important for my workflow for `flutter test` to recognize `dart_test.yaml`.

**Comment by daniel-v** [comment]
Indeed, that'd be awesome.

**Comment by porn** [comment]
I'd love to see this feature too!

The interface can be the same as in dart test:
https://pub.dev/packages/test#tagging-tests

**Comment by jonahwilliams** [comment]
This would also include `flutter drive`, https://github.com/flutter/flutter/issues/25141

**Comment by jonahwilliams** [comment]
This is supported now from #55152

**Comment by daniel-v** [comment]
Oiohhh, yeaah! Thank you!
