### ISSUE TITLE
Enable hover by default for desktop platforms

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#32835]
We should enable mouse hover by default for desktop platforms. If we want to support disabling hover, that should probably be handled by a separate API in the embedder. If the framework and embedder disagree on whether hover should be enabled, we get some odd graphical artifacts.

Related to https://github.com/flutter/flutter/issues/32529

cc @stuartmorgan

**Comment by jonahwilliams** [comment]
cc @dkwingsmt

**Comment by stuartmorgan** [comment]
> We should enable mouse hover by default for desktop platforms.

I've been thinking about flipping that default. The reason I had it off by default is that that's what at least macOS does, for performance reasons, but having a shell-level switch that's off by default is I think pretty clearly the wrong choice. I do wonder though if we could enable and disable it automatically based on whether any widgets are using hover (@gspencergoog, thoughts?). If not/until then, we should default it to on. It's a trivial change in the desktop shells.

> If the framework and embedder disagree on whether hover should be enabled, we get some odd graphical artifacts.

Could you elaborate on this? I would expect that having hover support off would be the same as never hovering over the window; if that's not true, or buggy, we should fix that.

**Comment by gspencergoog** [comment]
If no widgets are using hover, then no widgets will be drawn with hover highlights, or be listening to hover events, so by definition this is already happening.

However, I've just added hover support for pretty much all Material widgets, so you'd have to not be using Material to avoid having any `Listener`s by default.

**Comment by gspencergoog** [comment]
If it's a performance hit to send mouse events from the engine, you could hook something up to  `MouseTracker` that would tell the engine to stop sending them if there were no annotations registered.

**Comment by dkwingsmt** [comment]
> Could you elaborate on this? I would expect that having hover support off would be the same as never hovering over the window; if that's not true, or buggy, we should fix that.

Currently when hover is disabled:
- Hover effect on: Click inside widget
- Hover effect off: Click out of widget

**Comment by stuartmorgan** [comment]
> If it's a performance hit to send mouse events from the engine

Right, that's the potential issue. But if pretty much everything has hover, let's just turn it on by default and see if it's actually an issue in practice. Given the ubiquity of using hover effects on desktop in general, it seems unlikely.

**Comment by stuartmorgan** [comment]
> Currently when hover is disabled [...]

Ah, that does seem problematic (since it essentially forces embedders to implement hover support, which I don't think we want—especially from an embedder-API-compat standpoint). Can you file a new bug for that specifically so we can think about whether we can figure out whether we have any viable options here? (Maybe a heuristic for not doing hover effects if hover has *never* been sent, for instance.)
