### ISSUE TITLE
[cloud_firestore] Add support for Collection group queries

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [flutter/flutter#32831]

**Comment by ThinkDigitalRepair** [comment]
Dupe of https://github.com/FirebaseExtended/firebase-dart/issues/223

**Comment by awazgyawali** [comment]
https://github.com/flutter/plugins/pull/1619

**Comment by creativecreatorormaybenot** [comment]
@ThinkDigitalRepair What you linked has nothing to do with Flutter.

**Comment by ThinkDigitalRepair** [comment]
@creativecreatorormaybenot. Oh

**Comment by ThinkDigitalRepair** [comment]
@awazgyawali thank you so much!
