### ISSUE TITLE
Flutter crashed, Unexpected character (at character 1)

### ISSUE THREAD

**Issue by XiLiuRoy** [flutter/flutter#32841]
## Steps to Reproduce

1. Run flutter doctor
2. It crashed directly

## Logs
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

FormatException: FormatException: Unexpected character (at character 1)
                                                                           ...
^

```
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1392:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1259:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:924:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:29:10)
#4      JsonDecoder.convert (dart:convert/json.dart:493:36)
#5      JsonCodec.decode (dart:convert/json.dart:151:41)
#6      VsCode._getVersionFromPackageJson (package:flutter_tools/src/vscode/vscode.dart:222:50)
#7      new VsCode.fromDirectory (package:flutter_tools/src/vscode/vscode.dart:67:34)
#8      VsCode._findInstalled (package:flutter_tools/src/vscode/vscode.dart:207:28)
#9      VsCode._installedWindows (package:flutter_tools/src/vscode/vscode.dart:179:12)
#10     VsCode.allInstalled (package:flutter_tools/src/vscode/vscode.dart:92:14)
#11     VsCodeValidator.installedValidators (package:flutter_tools/src/vscode/vscode_validator.dart:19:10)
#12     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:67:44)
#13     Doctor.validators (package:flutter_tools/src/doctor.dart:121:46)
#14     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:128:39)
#15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:200:41)
<asynchronous suspension>
#16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
<asynchronous suspension>
#17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#24     Future._complete (dart:async/future_impl.dart:473:7)
#25     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#26     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[âœ“][39m Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.16299.967], locale en-AU)
    [32mâ€¢[39m Flutter version 1.5.4-hotfix.2 at C:\IDE\flutter
    [32mâ€¢[39m Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    [32mâ€¢[39m Engine revision 52c7a1e849
    [32mâ€¢[39m Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[31m[âœ—][39m Android toolchain - develop for Android devices
    [31mâœ—[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[33m![39m Doctor found issues in 1 category.
```

C:\Users\roy.liu>flutter doctor -v

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: e483f8ebbe83eabe)
Crash report written to C:\Users\roy.liu\flutter_13.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by BaderEddineOuaich** [comment]
Run command <pre>pub cache repair</pre> And try again.

**Comment by XiLiuRoy** [comment]
Hi @BaderEddineOuaich , I tried to run pub cache repair, but it shows "No packages in cache, so nothing to repair.", and Flutter still crashes.

**Comment by BaderEddineOuaich** [comment]
@XiLiuRoy  Hmm, can i see what's in C:\Users\roy.liu\flutter_13.log

**Comment by XiLiuRoy** [comment]
@BaderEddineOuaich sure, the following is flutter_13.log
`Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

FormatException: FormatException: Unexpected character (at character 1)
                                                                           ...
^


```
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1392:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1259:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:924:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:29:10)
#4      JsonDecoder.convert (dart:convert/json.dart:493:36)
#5      JsonCodec.decode (dart:convert/json.dart:151:41)
#6      VsCode._getVersionFromPackageJson (package:flutter_tools/src/vscode/vscode.dart:222:50)
#7      new VsCode.fromDirectory (package:flutter_tools/src/vscode/vscode.dart:67:34)
#8      VsCode._findInstalled (package:flutter_tools/src/vscode/vscode.dart:207:28)
#9      VsCode._installedWindows (package:flutter_tools/src/vscode/vscode.dart:179:12)
#10     VsCode.allInstalled (package:flutter_tools/src/vscode/vscode.dart:92:14)
#11     VsCodeValidator.installedValidators (package:flutter_tools/src/vscode/vscode_validator.dart:19:10)
#12     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:67:44)
#13     Doctor.validators (package:flutter_tools/src/doctor.dart:121:46)
#14     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:128:39)
#15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:200:41)
<asynchronous suspension>
#16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
<asynchronous suspension>
#17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#24     Future._complete (dart:async/future_impl.dart:473:7)
#25     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#26     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[âœ“][39m Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.16299.967], locale en-AU)
    [32mâ€¢[39m Flutter version 1.5.4-hotfix.2 at C:\IDE\flutter
    [32mâ€¢[39m Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    [32mâ€¢[39m Engine revision 52c7a1e849
    [32mâ€¢[39m Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[31m[âœ—][39m Android toolchain - develop for Android devices
    [31mâœ—[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[33m![39m Doctor found issues in 1 category.
```
`

**Comment by XiLiuRoy** [comment]
For anyone who has the same problem, the issue is relating VS code's package.json file, re-install VS code fixed it, therefore, I'm closing this issue.

**Comment by JoseGeorges8** [comment]
I'm using android studio and have the same problem

**Comment by BrendanLester** [comment]
I've got this as well on Visual Studio Code.
Uninstalling does not fix,  
neither does flutter clean/build
nor pub cache repair

**Comment by BrendanLester** [comment]
uninstalling Dart/Flutter does not help (removing my c:\flutter folder)
webdev serve from the command line and terminal (inside VS) works fine - so there's nothing wrong with the Flutter install or the application.
As uninstalling VS keeps settings and extensions, I have also remove those folders and reinstalled the extension.
I keep looking....

**Comment by dukezhao** [comment]
I met same problem ,you can try below code , I tried  & it work for my data
var data=json.decode(json.encode(snapshot.data));
good luck!

**Comment by QOFOL** [comment]
Same problem here !
I tried     all above , but it does not work

**Comment by gpapadas** [comment]
> 
> 
> I met same problem ,you can try below code , I tried & it work for my data
> var data=json.decode(json.encode(snapshot.data));
> good luck!

Where is this code? By searching in all files in VS Code it doesn't give me this line :/

**Comment by gpapadas** [comment]
I also have this issue on Windows. Is current sdk's issue?

**Comment by BrendanLester** [comment]
I think it's an issue with the Browser communicating back to one ports in VS Code. As mentioned earlier, the application itself works fine for just 'webdev serve'

Wireshark is showing 'RST ACK' faults.


And there's a strong correlation with these messages in Event Viewer:
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user XXXX-XXXX\userid SID (S-1-5-21-234234234-1427681694-234234234-1002) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.

Info how to fix this is here https://helpdeskgeek.com/how-to/fix-error-10016-windows-event-viewer/ - though I've followed this and still have both the Event viewer error and the VS Code/Flutter error (Note, I did remove those unrecognised values accidentally that it said not to).

I would be interested in continuing to hear of experiences in this space....

**Comment by moodstubos** [comment]
Same issue here, 

@XiLiuRoy 
please reopen this issue

**Comment by XiLiuRoy** [comment]
Hi Guys,

It seems lots of people still having the same issue, I just checked my last comment and it seems it's not quite clear. When re-install flutter, make sure everything relating to flutter is deleted, for example, I noticed that there were some json files in C:\Your User\Roaming folder when I had this issue.

Hope this helps.

Cheers,
Roy

**Comment by mkwsra** [comment]
For me, I had this because I was trying to output error of FutureBuilder as **string interpolation** and simply as soon as changed this `Text("${snapshot.error}")`  widget things were fine

**Comment by MungaraJay** [comment]
If anyone can help me with the similar issue i am facing please take a look at the github issue.
https://github.com/dart-lang/pub-dev/issues/3060

**Comment by ConstantinTuca** [comment]
Had the same problem. I was trying to get data form the baseurl, not from the baseurl/products.json. Verify yours if this is correct.

**Comment by zingwena** [comment]
i had the same issue , did the issue resolved

**Comment by up4154** [comment]
I am also getting the same issue I tried flutter doctor also but there are no issues.

**Comment by shubiour** [comment]
i had the same issue , did the issue resolved

**Comment by Qaroev** [comment]
remove latest comma in the file .arb

**Comment by farshig** [comment]
hi.
I have this problem, what can I do? I tried different ways and I did not get any results.

**Comment by alaminsheikh01** [comment]
same issue

**Comment by MToheed** [comment]
var request = http.MultipartRequest('POST', Uri.parse('https://kfcapi.ufone.com/Complaint/UploadDocument'));
request.files.add(await http.MultipartFile.fromPath('', 'file_path.jpg'));

http.StreamedResponse response = await request.send();

if (response.statusCode == 200) {
  print(await response.stream.bytesToString());
}
else {
  print(response.reasonPhrase);
}

Response:
FormatException: Unexpected character (at character 1) flutter
