### ISSUE TITLE
Selection is disabled by default in password fields

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#32845]
It seems weird that you can't select in a password field.

**Comment by justinmc** [comment]
There was an issue complaining about the opposite of this, that selection wasn't disabled by default: https://github.com/flutter/flutter/issues/24100

So I "fixed" it.  You can still set `enableSelectionInteraction: true` if you want to allow selection in a password field, but I think it is bad that you can't paste into it by default.

Maybe the full solution is to allow more fine grained control of the selection menu items?  So a password field should show "Paste" but not "Copy".

**Comment by Hixie** [comment]
I could see not exposing "copy", but stopping selection and paste as well seems like overkill.

**Comment by chunhtai** [comment]
Disable/Enable individual action would require breaking change in my pending pr https://github.com/flutter/flutter/pull/32059

**Comment by chunhtai** [comment]
To sum up, we want to hide copy and cut, but keep paste, selectAll and basic selection when obscureText is set to true
Sounds good @Hixie @justinmc ?
This will have to wait for #32059, I will appreciate the if more people can review that pr :)

**Comment by justinmc** [comment]
Yes, so in full my best guess of how this should work is this:

When `obscureText` is true, selection works, and the selection menu shows, but cut and copy are not shown.

When `obscureText` is false, selection works and the full selection menu is available.

`enableInteractiveSelection` always defaults to true (breaking change due to https://github.com/flutter/flutter/pull/24527).  When it is false, regardless of the value of `obscureText`, selection doesn't work at all and the selection menu can't be shown.

The main assumption in this is that people don't want to copy from password fields, because that will no longer be possible at all with the above changes.

**Comment by mdebbar** [comment]
One thing to keep in mind here is during selection, the whole content of the field should be considered one piece of text (word boundaries should be ignored).

So if the field contains `foo bar`, it's displayed as `*******`. When the user double taps somewhere within "bar" for example, the whole input field should be selected, not just "bar" like a normal text field would do.

**Comment by justinmc** [comment]
Good point!  It looks like right now we only select one obscured character at a time on double tap or long press.  Native iOS and Android both select all the obscured text.

**Comment by Hixie** [comment]
Personally I wish I could copy out of password fields, but I could live with not having copy.

**Comment by justinmc** [comment]
We could do that too, but I think it would require involving more state than just `obscureText` and `enableInteractiveSelection`.  Do we have any plans to allow users to modify the contents selection menu?  Something like that might be a nice way to show/hide certain buttons like copy.

**Comment by chunhtai** [comment]
allowing user to disable/enable certain button should be trivial.

**Comment by HansMuller** [comment]
This issue was also reported (January 2019) here: https://github.com/flutter/flutter/issues/27353

**Comment by chunhtai** [comment]
reverted due to bad merge

**Comment by chunhtai** [comment]
relanded

**Comment by chunhtai** [comment]
reverted another time :(
