### ISSUE TITLE
Unused Import

### ISSUE THREAD

**Issue by herbstdr** [flutter/flutter#32858]
I have updated flutter to the latest and when i try to import and use packages they become 'unused' and greyed out. So that makes my makeHttpClient() and JSON methods be underlined in red.

Copied and Pasted code from this http example https://flutter.dev/docs/cookbook/networking/fetch-data

![image](https://user-images.githubusercontent.com/50723318/57895739-7df93180-780a-11e9-9dc1-1746847da1af.png)

Compiler Error

Compiler message:
lib/main.dart:33:22: Error: Method not found: 'createHttpClient'.
    var httpClient = createHttpClient();
                     ^^^^^^^^^^^^^^^^
lib/main.dart:36:16: Error: Getter not found: 'JSON'.
    Map data = JSON.decode(response);
               ^^^^
lib/main.dart:33:22: Error: The method 'createHttpClient' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:my_flutter_test/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'createHttpClient'.
    var httpClient = createHttpClient();
                     ^^^^^^^^^^^^^^^^
lib/main.dart:36:16: Error: The getter 'JSON' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'package:my_flutter_test/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'JSON'.
    Map data = JSON.decode(response);
               ^^^^
Compiler failed on C:\Users\herbs\AndroidStudioProjects\my_flutter_test\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by jaysephjw** [comment]
@herbstdr 
Hmm not seeing this exact code at that link `getIPAddress`, or `createHttpClient`.

Your editor might be hung up on the first error, can't find createHttpClient().  Do you have that method defined yourself? Sometimes I see unused imports when I'm missing a brace somewhere too. 

 Include a complete and minimal example of the problem (smallest program that doesn't work) so people can help more.

**Comment by herbstdr** [comment]
Ok this makes sense - my mistake i think i was just confused. closed issue.

**Comment by teokok** [comment]
what is the solution ?
