### ISSUE TITLE
In integration test, we need to access attributes like disabled flag as shown in the FlutterInspector

### ISSUE THREAD

**Issue by snickersv2** [flutter/flutter#32852]
Hello,

Are the attributes in widgets not accessible to flutter_driver? For example, we have a disabled button in our screen and we want to check that disabled flag through integration tests, how do we do that? 

Thank you.

**Comment by Hixie** [comment]
This is available now.

**Comment by dukhanov** [comment]
> This is available now.

**Comment by pacozaa-paloit** [comment]
@dukhanov Did you get the answer?

**Comment by dukhanov** [comment]
> @dukhanov Did you get the answer?

No
