### ISSUE TITLE
flutter ancillary library names

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#3285]
From here: http://docs.flutter.io/flutter/, we have some inconsistency in the package names. `cassowary`, `newton` and `playfair` all use un-prefixed names. `flutter_sprites` and `flutter_markdown` use a flutter prefix. They're all optional libraries, built on top of flutter, and provided by us - they should probably have a consistent naming scheme.

`flutter_driver` and `flutter_test` also use a prefix. These seem like different types of libraries though - a different naming scheme doesn't feel as out of place.

**Comment by Hixie** [comment]
This problem will solve itself:
* cassowary: https://github.com/flutter/flutter/issues/2442
* newton: https://github.com/flutter/flutter/issues/2441
* playfair: https://github.com/flutter/flutter/issues/2205

**Comment by devoncarew** [comment]
Generally though, do we want the library names to be prefixed? We're using two different strategies here.

**Comment by Hixie** [comment]
We use a prefix for everything except the three that were originally outside Flutter but which we are slowly importing more and more. Well, and "flx", I guess.

I think it's more of a case-by-case basis, though for consistency right now I would tend to prefixing new libraries if we add more.

**Comment by devoncarew** [comment]
OK, sounds like the other issues cover this one.
