### ISSUE TITLE
Proxy for Webview, Desktop/Mobile mode

### ISSUE THREAD

**Issue by AresVampire** [flutter/flutter#32869]
How to integrate proxy to webview_flutter?
And I think, if userAgent is added to webview, it will be helpful for users who want to use desktop mode as well.

**Comment by albydarned** [comment]
I'm also looking to use a proxy in webview_flutter.

**Comment by purplecandy** [comment]
Any solutions yet? I figured out how to proxy dart http request but don't know how to proxy the webview

**Comment by stuartmorgan** [comment]
At least on iOS, AFAIK this is impossible; WKWebView does network requests in a separate process.

Beyond that, building proxies into each component that does network access isn't really scalable; proxying is really something best done at a device level.
