### ISSUE TITLE
Crash when scanning certain QR codes

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#32867]
I'm using the `firebase_ml_vision` plugin to scan QR codes. I noticed that some QR codes are causing the app to crash without leaving any stack traces when I run it from VS Code. I'm not an iOS developer, but I tried to debug using XCode and found that the crash is coming from this line: https://github.com/flutter/plugins/blob/3ddc2fe2ad97d5574d082b9b5f35f4d06c82a925/packages/firebase_ml_vision/ios/Classes/BarcodeDetector.m#L127

This is all I got in the logs:
```
2019-05-16 19:59:38.216318-0700 Runner[8630:2477904] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
(0x1bb42c518 0x1ba6079f8 0x1bb3a5f8c 0x1bb32e168 0x1bb31ed44 0x1017b09bc 0x1bb315b2c 0x1017af2f4 0x1017addb8 0x1017acd28 0x10595b6f0 0x10595cc74 0x10596a6fc 0x1bb3bdec0 0x1bb3b8df8 0x1bb3b8354 0x1bd5b879c 0x1e7861b68 0x100ff3e60 0x1bae7e8e0)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

For repro, here's a QR code that triggers this crash:

![image](https://user-images.githubusercontent.com/1278212/57900479-d1bd4800-7815-11e9-9d54-53c97d975a63.png)

**Comment by mdebbar** [comment]
cc @azihsoyn @bparrishMines

**Comment by kroikie** [comment]
@mdebbar

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/370. Any further collaboration will be done there.
