### ISSUE TITLE
Google Maps not working on KitKat

### ISSUE THREAD

**Issue by felangga** [flutter/flutter#32865]
I wonder why my apps using google maps not working on kitkat phone, just showing blank map.
I'm using [google_maps_flutter](https://pub.dev/packages/google_maps_flutter) plugin. It works on Lolipop and above. Anyone having this same issue?

**Comment by sarbagyastha** [comment]
**google_maps_flutter** works using [AndroidView](https://docs.flutter.io/flutter/widgets/AndroidView-class.html) and it requires Android API level 20 or greater.

**Comment by felangga** [comment]
Oh I see, and no working around on this ?

**Comment by yuridiniz** [comment]
There is a discussion about this, but it seems the team has not given priority to this, perhaps because of the low number of people with this problem:

[https://github.com/flutter/flutter/issues/23728](https://github.com/flutter/flutter/issues/23728)

**Comment by rymesaint** [comment]
Any update on this problem?

**Comment by BondarenkoStas** [comment]
Thank you @yuridiniz ! I will close the issue to avoid duplication, please follow if in #23728.
