### ISSUE TITLE
Let add-to-app FlutterViewControllers be back swipable in a UINavigationController

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32866]

**Comment by xster** [comment]
For instance, we can we can use the gesture fallback mechanism @amirh created to let the framework try to handle the gesture, if the framework doesn't then pass it to the parent view controller. 

Let the whole thing be bypassed when the FlutterViewController is used in a full screen app case.

**Comment by gaaclarke** [comment]
This already works for me:
![backswipe](https://user-images.githubusercontent.com/30870216/59311031-feba1a80-8c5c-11e9-98c0-a2f4c84ecaad.gif)

Engine version: 064910eb3ba266b2da35a794428f1f14d9b735a4

**Comment by gaaclarke** [comment]
I just tried this same case with the nav bar hidden and the back swipe doesn't function.  I also tried it with a different ViewController and the back swipe doesn't work either when the nav bar is hidden.  That means the FlutterViewController is working as expected and there is no issue to fix here from my perspective.

**Comment by blasten** [comment]
This appears to be working. Please reopen otherwise.
