### ISSUE TITLE
Review iOS add-to-app usage page

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32863]
Add a usage section under https://flutter.dev/docs/development/platform-integration. 

Cover various integration scenarios listed in https://github.com/flutter/flutter/projects/28#column-3245156. 

- [ ] Split what I need to add if I'm not using plugins vs what needs to be added with plugins
- [x] Make sure every instruction has both languages per platform
- [x] Document how to make an engine, how to inject the engine into views. Then separately document how to launch view directly and make engine at the same time.
- [x] We probably don't want to recommend our users to make a custom activity with LaunchTheme style
- [x] Describe bundle, library, entrypoint 
- [x] Document vm:entry-point
- [x] Have a section describing how to produce different behaviors from one embeddable, either by passing loose arguments, by sending in an initial route or by going into different vm entry points.
- [ ] Point out FlutterViewController can be embedded in other VCs
- [x] Talk about pushing messages to Flutter before showing the view vs launching Activity/VC with a route
- [x] Talk about what @style/LaunchTheme does when declaring a FlutterActivity in the manifest
- [ ] Talk about how to build out debug/profile/release modes from the outer project
- [ ] Make sure to change https://flutter.dev/docs/development/platform-integration/platform-channels to document using a FlutterEngine as a binary messenger instead of a flutter view controller.
- [x] Document the implications of FlutterEngine ownership/lifecycle and onSaveInstanceState etc.
- [x] Describe the caveat of needing to pass on all the lifecycle messages and copy those implementations from FlutterFragment when using FlutterView.
- [x] Point existing add-to-app users to flutter.dev/go/android-project-migration for Android embedding migration. 
- [ ] Remember to mention that if you don't keep your own FlutterEngine, you lose the VM service connection from `flutter attach` after you kill your activity/VC https://github.com/flutter/flutter/issues/24813
- [x] Make sure to specify why to create a FlutterEngine earlier
- [x] For Android, review all classes with redundant names and make sure the full import path is specified

**Comment by matthew-carroll** [comment]
I would recommend that we split these checkmarks per platform because the guides will be split per platform, and there will be some differences in the types of things documented.

Also, this list includes items at the View level. Since View level integration is an anti-goal of Phase 1, I would recommend removing those items from the list.

**Comment by xster** [comment]
Sure, I can split this and https://github.com/flutter/flutter/issues/32862 per platform

**Comment by xster** [comment]
Splitting Android out to https://github.com/flutter/flutter/issues/45220

**Comment by xster** [comment]
@gaaclarke, can you take a look at https://github.com/flutter/website/blob/staging-add-to-app-do-not-delete-until-2020/src/docs/development/add-to-app/ios/add-flutter-screen.md too to make sure I covered all the bases?

**Comment by gaaclarke** [comment]
Where is all the info on cocoapods and what is "App.framework"?

**Comment by xster** [comment]
For posterity, the cocoapods stuff is in https://flutter.dev/docs/development/add-to-app/ios/project-setup. Sorry, we removed the sidenav for now until launch.

**Comment by xster** [comment]
All the points are now covered or are in https://github.com/flutter/flutter/issues/45224. Closing.
