### ISSUE TITLE
Add add-to-app flow analytics dashboard

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32864]
Add a tab under go/flutter-dash (similar to API docs satisfaction) showing various steps of the conversion pipeline

- [x] Visits to https://github.com/flutter/flutter/issues/32862
- [x] Runs of flutter create -t module
- [x] Visits to https://github.com/flutter/flutter/issues/32863
- [ ] Visits to https://docs.flutter.io/javadoc/ and https://docs.flutter.io/objcdoc/
- [x] Visits to https://flutter.dev/docs/development/platform-integration/platform-channels
- [x] Runs of include_flutter.groovy, podhelper.rb and xcode_backend.sh build and embed
- [x] Runs of flutter build aar/framework https://github.com/flutter/flutter/issues/26099
- [x] Runs of flutter attach / flutter attach monitor https://github.com/flutter/flutter/issues/32824

Tooling measurements in #32649

**Comment by xster** [comment]
cc @jayoung-lee, most of these stats don't exist yet but once they're created, we'd like to ask you to create a dashboard for us :)

**Comment by jayoung-lee** [comment]
Sounds good :) Please ping me again when you're ready!

**Comment by xster** [comment]
@blasten added a bunch of tool analytics. @jayoung-lee could you guys connect? I think we can start building some parts of this now.

**Comment by jayoung-lee** [comment]
Sure, @blasten let's setup a meeting to talk about this.

**Comment by blasten** [comment]
awesome!

**Comment by jayoung-lee** [comment]
**Meeting from Jun 12**

Analytics from flutter.dev is straightforward.

Some details for Flutter Tool Analytics:
- [ ] flutter create -t module: "create" screen & cd "command_create_project_type"
- [ ] include_flutter.groovy, podhelper.rb and xcode_backend.sh: "bulid/bundle" screen & cd "command_build_bundle_is_module" (T/F)
- [ ] flutter build aar/framework: TBD
- [ ] flutter attach / flutter attach monitor: "attach" is available, but not "attach monitor" yet (TBD)

**Comment by jayoung-lee** [comment]
@blasten @xster Do you know where you can find the "Visits to https://api.flutter.dev/javadoc/ and https://api.flutter.dev/objcdoc/" from the Analytics 360 UI? 

To my knowledge, all visits to flutter.dev and api.flutter.dev are supposed to be captured with UA-67589403-1, but I could not find javadoc or objcdoc under Behavior > Site Content > All Pages.

**Comment by xster** [comment]
Looks like the files are https://github.com/flutter/engine/blob/master/tools/gen_objcdoc.sh and https://github.com/flutter/engine/blob/master/tools/gen_javadoc.py. Maybe we're missing the analytics connection such as done in https://github.com/flutter/flutter/commit/9a4c2c681f165cc1f7afd2c677943f43894915cb#diff-489bc35564c2afa711fa83f3e0d5c2c3 with the java/obj-c docs. 

cc @devoncarew in case you know of a connection made somewhere I didn't find browsing through the code.

**Comment by xster** [comment]
I was looking at the dashboard since stable was out. 

The project create module type definitely looks believable. 

The flutter build bundle is a bit suspiciously low. I did a quick test and builds by both include_flutter.groovy and podhelper.rb have suppress analytics set somewhere. I didn't dig deep enough to find where yet. 

Flutter attach is low too. I suspect the problem is because the attach command is long running so sending analytics when the entire session returns is probably too late. We should send as soon as these long running commands connect.

**Comment by xster** [comment]
Oh, the flutter build bundles not showing up is from https://github.com/flutter/flutter/pull/34179/files#diff-4a8e85e670fc26e239c20a777adf4061R37. 

We probably need some integration test on this too since it's hard to get the data back once we cut stable.

**Comment by xster** [comment]
Note to self:

- [ ] Let there be a global filter for channel
- [ ] Let the flutter create graph just show all types like app, plugin etc for reference

**Comment by xster** [comment]
This is now done
