### ISSUE TITLE
I have a problem Add-Flutter-to-existing-apps  running the  APP to the real machine and virtual machine with black screen

### ISSUE THREAD

**Issue by yxwandroid** [flutter/flutter#32876]
I have a problem running the project to the real machine and virtual machine with black screen

my step
1, My steps are as follows
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

 2, attach a small application 
https://github.com/yxwandroid/integratedFlutter.git

3, flutter doctor -v` here. 
![image](https://user-images.githubusercontent.com/9635493/57904456-5dca8080-78a5-11e9-82e0-c47a8ae5d236.png)

4  Check out my video
https://github.com/yxwandroid/integratedFlutter/blob/master/video.mp4

**Comment by janmoppel** [comment]
Hello @yxwandroid !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
