### ISSUE TITLE
[Bug] Crashlytics plugin - keys don't work 

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#32873]
<img width="663" alt="Screen Shot 2019-05-17 at 11 38 12 AM" src="https://user-images.githubusercontent.com/13853/57901575-581a6e00-7898-11e9-922c-9e65dd037539.png">

I am using the latest version firebase_crashlytics: 0.0.4+3, but there is a issue in the _prepareKeys() function , could you please confirm and fix it ? thank you.

 @Hixie @kroikie

**Comment by spockfish** [comment]
I've created a PR (https://github.com/flutter/plugins/pull/1799) that fixes this problem.

**Comment by collinjackson** [comment]
FYI @kroikie 

I've added some tests for this feature to your PR.

**Comment by behnam-lum** [comment]
Although this was closed and there has been a change for fixing the problem, still something is wrong as keys still are not reported!
There is a related open issue here: https://github.com/flutter/flutter/issues/31371
Please upvote this to make sure it gets fixed sooner. I don't want to use other unofficial plugins!

**Comment by kroikie** [comment]
@realcarlos

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1144. Any further collaboration will be done there.
