### ISSUE TITLE
Define a pattern for runApp when the window may have no size 

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32871]
With add to app, we should propose a best practice for what to do with the widget tree if, by default, users are going to run the engine ahead of time. They would need to put some widget into runApp so something rebuilds eventually but some widget want actual window sizes too so it shouldn’t be the final widget tree. 

Do we need a WhenWindowAttached widget? Or just read MediaQuery.of(context).size?

**Comment by matthew-carroll** [comment]
This issue needs to also account for the fact that lifecycle events are sent across a platform channel and they have an impact on Flutter's running state. The platform developer would have to make a choice to send or not send those events, and that decision would impact what Flutter runs or doesn't run.

**Comment by xster** [comment]
Agreed. Perhaps one exploration might be to consider adding new parallel or enum value lifecycle signals to distinguish app not in foreground vs app in foreground but Flutter isn't

**Comment by chunhtai** [comment]
I wrote up a document to conclude our off line discussion https://docs.google.com/document/d/1FNuq5-3rEB1n1fChdEde6gzZG9QOiw7HtM2jb12Ecv4/

**Comment by xster** [comment]
@chunhtai you had some PRs on this right? Can we attach some links?

**Comment by chunhtai** [comment]
The life cycle pr is tracked in this https://github.com/flutter/flutter/issues/39832

**Comment by blasten** [comment]
Hi @chunhtai. Are you still working on this issue?

**Comment by chunhtai** [comment]
@blasten , I am still working on this one https://github.com/flutter/flutter/issues/39832

**Comment by timsneath** [comment]
Touching this issue for triage purposes.

**Comment by xster** [comment]
The last bit in the chain is https://github.com/flutter/engine/pull/14002
