### ISSUE TITLE
Images doesn't fade in when loaded

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3287]
Images should fade in (using opacity and saturation) when they finish loading.

Test case in Grid List demo in the gallery.

**Comment by abarth** [comment]
It's unclear whether we want to do this by default for all images, but we should definitely have a widget that does this and `NetworkImage` should probably recommend using it.

**Comment by vlidholt** [comment]
The asset images tend to load slowly too, so I think it should at least be an option there too.

**Comment by Hixie** [comment]
We have a widget that does this now: FadeInImage.
