### ISSUE TITLE
Icon Widget Isn't working correctly in flutter web

### ISSUE THREAD

**Issue by rkishan516** [flutter/flutter#32882]
## Steps to Reproduce

1. Create a flutter web app
2. Make a Iconbutton or use Icon widget.
3. Run and Check the widget in Browser

## Problem

Icon Widget isn't working correctly in flutter web

## Output

![Screenshot from 2019-05-17 14-42-49](https://user-images.githubusercontent.com/34465683/57917353-1e566100-78b2-11e9-825f-5e3a1b67e730.png)

**Comment by anondev32** [comment]
This issue was resolved multiple times here. Try search before you open a new one. You just making peoples life harder like this. Thank you for your cooperation and have a nice day. :)
