### ISSUE TITLE
Provide an option to NOT show last typed character briefly in TextField when obscureText is true

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#32889]
Flutter version

```
[✓] Flutter (Channel master, v1.5.9-pre.260, on Mac OS X 10.13.6 17G4015, locale en-CN)
```

How to hide last typed character briefly in TextField when obscureText is true?
Especially, this becomes a critical problem with flutter_web.
Thanks.

**Comment by justinmc** [comment]
The behavior I see on Android in a TextField is that the last character hides after a short delay.  Are you asking for something that never shows the character at all?

```dart
TextField(
  obscureText: true,
)
```

<img width="300" src="https://user-images.githubusercontent.com/389558/57943626-5bf2c400-7889-11e9-8c80-504e446d778f.gif" />

**Comment by sgon00** [comment]
@justinmc yeah, for security reasons, I think it should never show at all. Especially for web apps (flutter_web). I don't see any existing webpage will show the last character. In general, I will configure my mobile privacy setting to "Show passwords: off" too. Only flutter apps will not honor system's setting and always show the last character. I feel this is very unsafe.

**Comment by creativecreatorormaybenot** [comment]
@sgon00 The title seems slightly misleading. It should be something more along the lines of "Do not show last typed character briefly ..." and I know that one could think that the statements are the same, however, the "**no**" does not negate the "show" alone but it negates the "*show briefly*" as a whole. That said, "hide briefly" is different from "not show briefly" and if you really want to use "hide", it should be "hide permanently". I would still go with "not show".

Also, I feel like it is important to stress that your issue is **not only** related to Flutter web. I am not sure if the labels assigned by @HansMuller properly show this.

**Comment by HansMuller** [comment]
@creativecreatorormaybenot The labels are OK

**Comment by sgon00** [comment]
@creativecreatorormaybenot Thanks for the suggestion. I just changed the title to `Provide an option to NOT show last typed character briefly in TextField when obscureText is true`.  I was lazy before and just changed one word from the original issue https://github.com/flutter/flutter/issues/11817. 
And yeah, I also want this option on mobile platform too, since I think the last char should never be shown.

**Comment by yjbanov** [comment]
@HansMuller Are you sure this is a Web-only issue? It seems Flutter does this at the framework level. It seems like a general desktop issue.

**Comment by luigi-rosso** [comment]
I worked around this by creating a custom TextEditingController that just replaces the entire text span with an obscured version. Note that ```obscureText``` must be false for this code to work. 

This lets you still get the original value in the onChanged callback, but display something different. Let me know if someone has a cleaner way to work around this :) 

```dart
class ObscuringTextEditingController extends TextEditingController {
  @override
  TextSpan buildTextSpan({TextStyle style, bool withComposing}) {
    var displayValue = '•' * value.text.length;
    if (!value.composing.isValid || !withComposing) {
      return TextSpan(style: style, text: displayValue);
    }
    final TextStyle composingStyle = style.merge(
      const TextStyle(decoration: TextDecoration.underline),
    );
    return TextSpan(
      style: style,
      children: <TextSpan>[
        TextSpan(text: value.composing.textBefore(displayValue)),
        TextSpan(
          style: composingStyle,
          text: value.composing.textInside(displayValue),
        ),
        TextSpan(text: value.composing.textAfter(displayValue)),
      ],
    );
  }
}

// ...

// in your build somewhere
TextField(
  controller: passwordController,
  decoration: const InputDecoration(hintText: 'Password'),
  onChanged: (value) {
    print('Actual Value: $value');
  },
),
```

**Comment by SowellM** [comment]
@luigi-rosso I couldn't get the workaround to obscure the text on Flutter (Channel master, v1.15.4-pre.75, on Mac OS X 10.14.6 18G103, locale en-US) or [DartPad](https://dartpad.dev/8c131b2540e33b73eb29defcf4f3ad84). Maybe I missed something.

**Comment by TahaTesser** [comment]
duplicate of https://github.com/flutter/flutter/issues/51218
