### ISSUE TITLE
TextField NoSuchMethodError: The getter 'pasteButtonLabel' was called on null. for RU locale

### ISSUE THREAD

**Issue by gevork** [flutter/flutter#32881]
If i use localization for Russian language ""ru"
and in the TextField I try to call the context menu on IOS devices  "copy / paste / cut", then I get the following error (this error is repeated on my version 1.2.1 and 1.5.4-hotfix.2):
`flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: NoSuchMethodError: The getter 'pasteButtonLabel' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'pasteButtonLabel' was called on null.
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building _TextSelectionToolbar(dirty, dependencies:
flutter: [_LocalizationsScope-[GlobalKey#56a01], MediaQuery]):
flutter: The getter 'pasteButtonLabel' was called on null.
flutter: Receiver: null
flutter: Tried calling: pasteButtonLabel
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
flutter: #1      _TextSelectionToolbar.build (package:flutter/src/cupertino/text_selection.dart:97:51)
flutter: #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
flutter: #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
flutter: #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #5      StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #7      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #17     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #19     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
flutter: #20     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #22     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:607:16)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #26     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #30     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #44     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #48     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #52     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #60     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #64     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #68     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #72     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #76     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #80     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #84     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #88     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #92     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #96     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #100    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #102    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #106    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #109    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #110    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #114    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #117    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #118    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #122    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #126    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #129    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #130    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #132    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #135    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #136    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #140    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
flutter: #141    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
flutter: #142    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #143    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
flutter: #144    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
flutter: #145    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
flutter: #147    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
flutter: #148    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
flutter: #149    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
flutter: (elided one frame from package dart:async-patch)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════`

my code:
`class MyApp extends StatelessWidget {
  final Iterable<LocalizationsDelegate<dynamic>> localDelegates =
      <LocalizationsDelegate<dynamic>>[
    AppLocalizationsDelegate(),
    DefaultCupertinoLocalizations.delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate
  ];

  MyApp();

  @override
  Widget build(BuildContext context) {
    return Localizations(
        delegates: localDelegates,
        locale: const Locale('ru'),
        child: MaterialApp(
          navigatorKey: navigatorKey,
          localizationsDelegates: localDelegates,
          supportedLocales: [Locale("ru")],
          title: '',
          debugShowCheckedModeBanner: false,
          theme: ThemeData(
            backgroundColor: Colors.white,
            brightness: Brightness.light,
            primarySwatch: AppColors.greenMaterial,
            primaryTextTheme: TextTheme(title: TextStyle(color: Colors.black)),
            primaryIconTheme: IconThemeData(color: Colors.black),
          ),
          builder: (context, child) {
            return ScrollConfiguration(
              behavior: ScrollBehavior(),
              child: child,
            );
          },
          home: FirstStub(),
        ));
  }`

flutter doctor:
`
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.3 18D109, locale ru)
    • Flutter version 1.5.4-hotfix.2 at /Users/gevork/Documents/dev/flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/gevork/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 7.0 (API 24) (emulator)
    • iPhone Xʀ                 • E37B882E-6BF5-4204-B180-2744AE78766F • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!`

**Comment by Goolpe** [comment]
You can create your own delegate:
```
import 'package:flutter/foundation.dart' show SynchronousFuture;
import 'package:flutter/cupertino.dart';

class CupertinoLocalizationsDelegate extends LocalizationsDelegate<CupertinoLocalizations> {
  const CupertinoLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => <String>['en', 'ru'].contains(locale.languageCode);

  @override
  SynchronousFuture<_DefaultCupertinoLocalizations> load(Locale locale) {
    return SynchronousFuture<_DefaultCupertinoLocalizations>(
      _DefaultCupertinoLocalizations(locale.languageCode)
    );
  }

  @override
  bool shouldReload(CupertinoLocalizationsDelegate old) => false;
}

class _DefaultCupertinoLocalizations extends CupertinoLocalizations {
  _DefaultCupertinoLocalizations(this._languageCode):
    assert(_languageCode != null);

  final DefaultCupertinoLocalizations _en = const DefaultCupertinoLocalizations();
  final String _languageCode;

  final Map<String, Map<String, String>> _dict = <String, Map<String, String>>{
    'en': <String, String>{
      'alert': 'Alert',
      'copy': 'Copy',
      'paste': 'Paste',
      'cut': 'Cut',
      'selectAll': 'Select all'
    },
    'ru': <String, String>{
      'alert': 'Внимание',
      'copy': 'Копировать',
      'paste': 'Вставить',
      'cut': 'Вырезать',
      'selectAll': 'Выбрать всё'
    }
  };

  @override
  String get alertDialogLabel => _get('alert');

  @override
  String get anteMeridiemAbbreviation => _en.anteMeridiemAbbreviation;

  @override
  String get postMeridiemAbbreviation => _en.postMeridiemAbbreviation;

  @override
  String get copyButtonLabel => _get('copy');

  @override
  String get cutButtonLabel => _get('cut');

  @override
  String get pasteButtonLabel => _get('paste');

  @override
  String get selectAllButtonLabel => _get('selectAll');

  @override
  DatePickerDateOrder get datePickerDateOrder => _en.datePickerDateOrder;

  @override
  DatePickerDateTimeOrder get datePickerDateTimeOrder => _en.datePickerDateTimeOrder;

  @override
  String datePickerDayOfMonth(int dayIndex) => _en.datePickerDayOfMonth(dayIndex);

  @override
  String datePickerHour(int hour) => _en.datePickerHour(hour);

  @override
  String datePickerHourSemanticsLabel(int hour) => _en.datePickerHourSemanticsLabel(hour);

  @override
  String datePickerMediumDate(DateTime date) => _en.datePickerMediumDate(date);

  @override
  String datePickerMinute(int minute) => _en.datePickerMinute(minute);

  @override
  String datePickerMinuteSemanticsLabel(int minute) => _en.datePickerMinuteSemanticsLabel(minute);

  @override
  String datePickerMonth(int monthIndex) => _en.datePickerMonth(monthIndex);

  @override
  String datePickerYear(int yearIndex) => _en.datePickerYear(yearIndex);

  @override
  String timerPickerHour(int hour) => _en.timerPickerHour(hour);

  @override
  String timerPickerHourLabel(int hour) => _en.timerPickerHourLabel(hour);

  @override
  String timerPickerMinute(int minute) => _en.timerPickerMinute(minute);

  @override
  String timerPickerMinuteLabel(int minute) => _en.timerPickerMinuteLabel(minute);

  @override
  String timerPickerSecond(int second) => _en.timerPickerSecond(second);

  @override
  String timerPickerSecondLabel(int second) => _en.timerPickerSecondLabel(second);

  String _get(String key) {
    return _dict[_languageCode][key];
  }
}
```
in main.dart
```
localizationsDelegates: const <LocalizationsDelegate<dynamic>>[
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            CupertinoLocalizationsDelegate()
          ],
```

**Comment by gevork** [comment]
Ths Goolpe!!! It's work well!
