### ISSUE TITLE
[web]: Container does not draw border

### ISSUE THREAD

**Issue by a-marenkov** [flutter/flutter#32893]
border isn't drawn for decoration nor for foregroundDecoration

Container(
          height: 100.0,
          width: 100.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.all(radiusCard),
            border:
                Border.all(width: 1.0, color: Colors.red),
          ),
          foregroundDecoration: BoxDecoration(
              borderRadius: BorderRadius.all(radiusCard),
              border: Border.all(
                  width: 1.0, color: Colors.red)));

**Comment by ditman** [comment]
I'm closing this one as fixed, here: https://github.com/flutter/engine/commit/851f4606f19541376b6e8915e7b8677b31853223
