### ISSUE TITLE
Support FlutterEngine in FlutterPluginRegistry

### ISSUE THREAD

**Issue by chip2n** [flutter/flutter#32894]
`FlutterPluginRegistry` cannot be used properly with FlutterEngine at the moment, since `FlutterRegistrar.messenger()` returns an uninitialized `FlutterNativeView` instead of `FlutterEngine.dartExecutor`. This makes it hard to use some flutter plugins in embedding scenarios (NPE when attempting to access `BinaryMessenger`).

https://github.com/flutter/engine/blob/865cb1c986cf5abf93023f9b0bcbafd36a68eca2/shell/platform/android/io/flutter/app/FlutterPluginRegistry.java#L55-L57

https://github.com/flutter/engine/blob/865cb1c986cf5abf93023f9b0bcbafd36a68eca2/shell/platform/android/io/flutter/app/FlutterPluginRegistry.java#L125

Seems like this issue is known since there's a TODO by @matthew-carroll in the code, but didn't find an issue associated with it so I'm creating this one. Has there been any progress on this?

**Comment by matthew-carroll** [comment]
@chip2n the new Android embedding will come with a new plugin API, too. It was not designed to work with the old plugin registry. I am actively merging experimental code to bring plugins to the new embedding, e.g., https://github.com/flutter/engine/pull/8962

Based on the new work, can we close this, or did I misunderstand the issue?

**Comment by chip2n** [comment]
Thanks for the response. Yeah, I somehow missed that one. Go ahead and close this :)
