### ISSUE TITLE
[web]: Http requests throw XMLHttpRequest error

### ISSUE THREAD

**Issue by a-marenkov** [flutter/flutter#32892]
Here is the stack trace:
XMLHttpRequest error.
dart:sdk_internal 41198:30                                                           get current
package:http/src/packages/http/src/browser_client.dart 84:22     <fn>
dart:sdk_internal 98027:96                                                           <fn>

It happens due to Chrome sending an OPTIONS request first.
As a temporary solution for development, I launch Chrome with CORS turned off.

How can i fix this problem? There has to be a way to disable sending the OPTIONS request or ignore it.

**Comment by a-marenkov** [comment]
> @a-marenkov Sorry for such a long delay, do you still encounter the issue?

To solve the issue we had to set CORS on our backend, so I'm not sure if there's still the issue. 
When i look at network logs, i don't see OPTIONS request. So it seems ok now. 
I've switched to flutter branch from flutter_web since then.
Thanks for reply.

**Comment by BondarenkoStas** [comment]
Hmm, then I think it's safe to close it since there were no similar issues, though 18 thumb ups is quite a lot.

**Comment by AlexandreRoba** [comment]
Any update on this. Trying to access the google map places API and I'm getting a CORS error :(

**Comment by jonahwilliams** [comment]
Flutter has no control over browser CORS behavior

**Comment by AlexandreRoba** [comment]
Can this be a firebase hosting issue then?

**Comment by amreniouinnovent** [comment]
@jonahwilliams How could we test Flutter locally if AWS apis and images URLs did not work because of CORS?

**Comment by jonahwilliams** [comment]
@amreniouinnovent I recommend starting by reading https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by willvlad** [comment]
Facing similar issue on flutter web only, works fine on flutter mobile

**Comment by krunaldarji** [comment]
Facing similar issue on flutter web only, works fine on flutter mobile

**Comment by VickySalunkhe** [comment]
I was facing the same issue I solved it and have answered it on StackOverflow

Do give it a look [here](https://stackoverflow.com/a/59552060/9236994)

https://stackoverflow.com/a/59552060/9236994

**Comment by yasinarik** [comment]
I have a backend service written with Nodejs. So I simply added the CORS package to my server-side application.

1. `npm install cors`

2. 
```
var express = require('express');
var cors = require('cors');
var app = express();

app.use(cors());

```

[https://expressjs.com/en/resources/middleware/cors.html](url)

So now, Flutter Web works normally.

**Comment by Mohammad-Jaafar** [comment]
SOLVED !!!

try this ..
https://stackoverflow.com/a/14469443/13059465
