### ISSUE TITLE
[Connectivity] Closing Connectivity stream responsibility

### ISSUE THREAD

**Issue by freitzzz** [flutter/flutter#32897]
Good afternoon @flutter team.

Came across a concern while disposing one of my blocs that uses Connectivity broadcast stream. Since Connectivity is a singleton which provides a broadcast stream, who has the responsibility to close the stream? Is it the application or the framework?

Best regards,
freitzzz

**Comment by TahaTesser** [comment]
Hi @freitzzz 
if you're still experiencing this problem with latest stable, please create a new issue and provide the information required in the template.
Thank you
