### ISSUE TITLE
[image_picker][iOS] Camera controller throws touch event into parent flutter controller

### ISSUE THREAD

**Issue by arok** [flutter/flutter#32896]
## Steps to Reproduce

Pls see the example project https://github.com/arok/test_image_picker

Prerequisites
Launch camera controller from secondary screen (route)
1. Launch the app and click on FAB in main screen, new PageRoute will push
2. Click on the button "Click me" and select "Camera" option in opened action sheet
3. In camera controller click on any place to get camera focus works
4. click cancel or make a photo

Actual result: the user navigates to the main screen
Expected result: the user should stay on the second page

As I understand the issue is that touch events throw down from CameraController to FlutterController when the user clicks in CameraController, after that action sheet hides and call of Navigator.pop() method pops secondary route. 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.4.9-hotfix.1, on Mac OS X 10.14.4 18E226, locale en-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
[✓] Connected device (2 available)
```

**Comment by arok** [comment]
Here is recording of the issue https://take.ms/Lctbt

**Comment by Goolpe** [comment]
Try to change name of BuildContext
```
onPressed: () async {
                var path = await showCupertinoModalPopup(
                    context: context,
                    builder: (context2) {
                      return CupertinoActionSheet(
                        cancelButton: CupertinoActionSheetAction(
                          isDefaultAction: true,
                          onPressed: () => Navigator.pop(context2, null),
                          child: Text('Cancel'),
                        ),
                        actions: [
                          CupertinoActionSheetAction(
                            onPressed: () async {
                              var result = await ImagePicker.pickImage(source: ImageSource.camera,);
                              Navigator.pop(context2, result);
                            },
                            child: Text('Camera'),
                          ),
                          CupertinoActionSheetAction(
                            onPressed: () async {
                              var result = await ImagePicker.pickImage(source: ImageSource.gallery,);
                              Navigator.pop(context2, result);
                            },
                            child: Text('Gallery'),
                          )
                        ],
                      );
                    }
                );
                setState(() {
                  this.path = 'hello';
                });
              }),
```

**Comment by arok** [comment]
@Goolpe It doesn't change anything, in each variants used write context. I have a workaround for the issue (just change return value that I pass to Navigator.pop() from path to ImageSource) but it not fixes the root of the issue.

**Comment by MrLiuYS** [comment]
i also met. how did you solve it?

**Comment by helang1991** [comment]
i also met it.

**Comment by bcwjnq** [comment]
+ 1

**Comment by iapicca** [comment]
Hi all
if you are experiencing the issue with the latest stable version of flutter
and the latest version of image_picker 

please provide your updated `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by zzzs123** [comment]
inherit UIImagePickerController and override touchesBegan method
then use  YourImagePickerViewController instead of UIImagePickerController
may solve the problem
```
class YourImagePickerViewController: UIImagePickerController {

    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
    }
    
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        // DLog("\(self) \(#function)")
    }
}
```
