### ISSUE TITLE
Document how to update flutter

### ISSUE THREAD

**Issue by IvBaranov** [flutter/flutter#329]
In `/sky_engine-0.0.49/sdk_ext/Customwindow.dart`:
```
...
9: typedef void _EventCallback(Event event);
...
```
In `/flutter/packages/flutter/lib/src/rendering/binding.dart`:
```
...
146: ui.window.onEvent = _handleEvent;
...
207: void _handleEvent(String eventType, double timeStamp) {...}
...
```
Commit: c94e4c4

So I get on app start:
```
org.domokit.sky.shell E/chromium: [ERROR:dart_error.cc(16)] Unhandled exception:
                                                                 type '(String, double) => void' is not a subtype of type '_EventCallback' of 'value'.
                                                                 #0      Window.onEvent= (file:///src/flutter/engine/src/out/android_Release/gen/sky/bindings/Customwindow.dart:33)
                                                                 #1      FlutterBinding.FlutterBinding (packages/flutter/src/rendering/binding.dart:146)
                                                                 #2      WidgetFlutterBinding.WidgetFlutterBinding (packages/flutter/src/widgets/binding.dart:12)
                                                                 #3      WidgetFlutterBinding.ensureInitialized (packages/flutter/src/widgets/binding.dart:19)
                                                                 #4      runApp (packages/flutter/src/widgets/binding.dart:82)
                                                                 #5      main (/Users/ivbaranov/Projects/flutter/flutter/examples/fitness/lib/main.dart:165)

```

**Comment by IvBaranov** [comment]
Sorry, that is kind of obvious that I should update sky_engine package first:
`pub get sky_engine`

**Comment by IvBaranov** [comment]
However there should be the same kind of error when one followed _Getting Started with Flutter_:
```
Clone the alpha branch from the Flutter repository:

$ git clone https://github.com/flutter/flutter.git -b alpha
```
while alpha is far behind the c94e4c4, where `sky_engine` method parameters change took place.

**Comment by abarth** [comment]
Each git revision of flutter.git specifies exactly which revision of the engine it is compatible with.  If you clone the alpha branch and then `pub upgrade` your app, you'll get a version of the engine that is compatible with that version of `package:flutter`.

If you build the engine from source yourself, then you need to worry about whether the engine you've built locally is compatible with the version of `package:flutter` that you're working with.  However, most people shouldn't need to build the engine from source.

**Comment by abarth** [comment]
Maybe the bug here is to better document how to update flutter once you've got it?

**Comment by abarth** [comment]
First step in https://github.com/flutter/flutter/pull/331

**Comment by IvBaranov** [comment]
It's clear now, thanks!

**Comment by abarth** [comment]
Docs are in https://github.com/flutter/flutter.github.io/pull/84

Upgrade command pushed to `alpha`.
