### ISSUE TITLE
Provide method to view webview console logs

### ISSUE THREAD

**Issue by tonyclickspace** [flutter/flutter#32908]
## Use case
Trying to debug issues with the WebView, but Flutter has no way of displaying / logging any logs or errors that the WebView is throwing. So debugging blind.

## Proposal
Add an argument for the WebView it tell it how to handle / where to send console messages (a stream and/or print to the dev message window in debug mode)

**Comment by fzyzcjy** [comment]
One year has passed... Is there any progress?

**Comment by Nico04** [comment]
Some third-parties web widget that I use throws errors in the web console, it would be nice to be able to read/parse the console to handle thoses events.

**Comment by stuartmorgan** [comment]
For Android this is potentially implementable; for iOS I don't think there's any way to do this other than to inject JS into the page (which isn't something we would want to do in general). Note that on iOS at least you can remotely debug WKWebView via Safari tools.

**Comment by art926** [comment]
We'd really like to have it on iOS. In our case, we create a WebView that loads a script that fails right after, so there is no time to connect it and debug in an external browser. Maybe the WebView constructor could support an argument, that tells it that we're in a dbg mode and it would do some JS onerror injection to catch the error details.
