### ISSUE TITLE
[web]: Problem with flutter web and domain name

### ISSUE THREAD

**Issue by hyperpanthera** [flutter/flutter#32900]
I try to deploy my web app written in Flutter on Firebase.

The problem:

It does not show up after deployment if I do not add a subdomain.

For example:

www.website.com test.website.com xyz.website.com anything.website.com

... works greatly!

While only 'website.com' fails to work.

Any ideas?

**Comment by hyperpanthera** [comment]
This happened to a colleague too.

**Comment by yjbanov** [comment]
Can you please ask this question on StackOverflow to help others? Please include the output in the browser console.
