### ISSUE TITLE
Hover effects are incorrectly shown for all widgets under cursor.

### ISSUE THREAD

**Issue by KirolousNashaat** [flutter/flutter#32915]
## Screenshot:
![vvvvv](https://user-images.githubusercontent.com/23477886/57951690-149d1f80-78eb-11e9-93b6-750089b9724d.png)

## Steps to Reproduce
1. create a button in a scaffold
2. show a modal bottom sheet / open a side drawer / put two widgets on each other
3. hover the button even if it's not visible at all ( behind the drawer for example )
so the button get the hover effect too ,, but it shouldn't
and if you click , only the first one will receive the click (which is right ofc) 

```
```

[ظê?] Flutter (Channel master, v1.6.1-pre.36, on Microsoft Windows [Version 6.3.9600], locale en-US)

    ظت Flutter version 1.6.1-pre.36 at E:\Setups\FLUTTER\flutter
    ظت Framework revision 1f2972c7b6 (2 hours ago), 2019-05-17 10:44:08 -0700
    ظت Engine revision 065fe5b210
    ظت Dart version 2.3.1 (build 2.3.1-dev.0.0 5ffff98440)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ظت Android SDK at E:\Setups\Android
    ظت Android NDK location not configured (optional; useful for native profiling support)
    ظت Platform android-28, build-tools 28.0.3
    ظت ANDROID_HOME = E:\Setups\Android
    X Android SDK file not found: adb.
    ظت Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Android Studio (not installed)
    ظت Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[ظê?] IntelliJ IDEA Community Edition (version 2019.1)
    ظت IntelliJ at E:\Setups\JetBrains\IntelliJ IDEA Community Edition 2019.1.1
    ظت Flutter plugin version 35.3.3
    ظت Dart plugin version 191.7141.49

[ظê?] Connected device (2 available)
    ظت Windows ظت Windows ظت windows-x64 ظت Microsoft Windows [Version 6.3.9600]
    ظت web     ظت web     ظت web         ظت web

! Doctor found issues in 2 categories.

```
```

btw fixing this strange characters in the flutter doctor -v would be helpful too :)

**Comment by KirolousNashaat** [comment]
btw about the log , i am building for android fine , so it must be a mistake about 'Android SDK file not found: adb.' !?

**Comment by jonahwilliams** [comment]
cc @gspencergoog

**Comment by dkwingsmt** [comment]
Thanks for the issue. I'm currently working on a change that should fix this. 

Related: https://github.com/flutter/flutter/issues/33679
