### ISSUE TITLE
rendering/debug.dart should namespace its globals in a class

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3292]
It's very strange to have a bunch of public debug flags in the global namespace.

Better IMO would be to have `RenderingDebug.paintSizeEnabled = true` which could be done using a class and static variables.

Thoughts @Hixie, @abarth?

**Comment by Hixie** [comment]
Yeah, probably.

**Comment by abarth** [comment]
Strange in that its not idiomatic for Dart?

**Comment by Hixie** [comment]
It's pretty confusing in the docs, at least.

**Comment by abarth** [comment]
Yeah, it would be nice to have one doc location for all these flags.

**Comment by abarth** [comment]
The tricky thing is we have several of these debug.dart files at different layers of the system.  They can't all put the flags in the same namespace because Dart, which means we'll need to give the flags at different layers different names.

**Comment by eseidelGoogle** [comment]
Presumably that's OK since it keeps the layers separate?  WidgetsDebug, RenderingDebug, etc.  We can link them to each other in dartdoc?  Donno.

**Comment by abarth** [comment]
Generally we try to avoid developers having to worry too much about what's in the widgets layer versus the material layer.  I'm not sure renaming the flags is much of a net positive.

> It's very strange to have a bunch of public debug flags in the global namespace.

I'm not sure this statement from the issue description is accurate.  Do you have evidence that this pattern is not idiomatic for Dart?

**Comment by eseidelGoogle** [comment]
I don't have any evidence that it is not idiomatic Dart. I feel well too far removed from the code at this point to trust my judgement.  I suspect what triggered this bug was the confusion in my head about the scoping of these variables (are the globals, locals, some part of flutter, my widgets, etc.) when reading the code.

I see no reference to globals in Effective Dart.  It's possible the dart style is to have library globals and to just import the library with `as` for scoping.

Feel free to close this if it doesn't seem useful.

**Comment by abarth** [comment]
> just import the library with as for scoping

That's definitely a pattern that some libraries (e.g., `package:http`) use.  We generally expect people to import without `as` and we grab a bunch of really good names (e.g., `Card`).

I think the ideal thing would be to group them all into a single namespace, the way you can do with C++ and the `namespace` keyword.  If Dart supported "export as", we might be able to do something like that.  I'll explore a bit to see if we can get something like that working.

**Comment by Hixie** [comment]
To some extent they are at least namespaced in that they all start with "debug". :-)

IMHO we coud resolve the bulk of this with improvements to how we present this in the docs, e.g. by having a way to categorise stuff beyond what the code has (which is basically simple stuff like properties vs methods, by library). Having `debugPrint` next to `debugPrintBuildScope` isn't optimal. Ideally `debugPrint` and `debugPrintStack` would be in a group, and `debugPrintBuildScope` would be with `debugDumpApp`, for instance.

**Comment by abarth** [comment]
I'm going to close this issue.  It's possible we should file another issue against dartdoc with some ideas about how to improve the presentation of these functions.
