### ISSUE TITLE
Rationalize plugins in flutter assemble

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#32924]
Plugins require generating some flutter specific code as well as some native code. We might be able to handle the former and let gradle and cocoapods handle the later

**Comment by blasten** [comment]
oh cool. You have this issue already :)

**Comment by jonahwilliams** [comment]
Rationalization: these do not affect flutter assemble, since the dependency information is output by `flutter packages/pub get` and processed by the native build system.

The interaction between plugins is between the project structure and the native build system, not the dart build
