### ISSUE TITLE
Need to detect platform of target device of integration test

### ISSUE THREAD

**Issue by snickersv2** [flutter/flutter#32927]
Hello,

We are planning to run an adb command during our integration tests so we like to check the platform of the target device if it's Android or not. However, when we call Platform.operatingSystem, it returns the OS of the host machine of the test (macos in my case). Is there a way to detect the platform of the target device of the integration test?

Thank you.

**Comment by BassamxMednini** [comment]
According to my research there are currently no ways to detect the platform while integration tests.

**Comment by amorenew** [comment]
@jmagman @snickersv2 
I solved it by creating class called driver_commads.dart with
`const String getPlatformCommand = 'getPlatform';
`
and in app.dart
  ```
enableFlutterDriverExtension(handler: (command) {
    var result = '';
    switch (command) {
      case getPlatformCommand:
        result = Platform.operatingSystem;
        break;
    }

    return Future.value(result);
  });
```
then I check it by 
`final operatingSystem = await driver.requestData(getPlatformCommand);`

**Comment by seonadf** [comment]
@amorenew do you have a sample project where you have used this? As i am not able to get it working.

**Comment by felix-barz-brickmakers** [comment]
How can we get a reference to the current driver when using the newer integration_test package?

**Comment by rogeriodeandradepires** [comment]
> 

Thank you so much. This really worked.

**Comment by rogeriodeandradepires** [comment]
THank you so much. This really worked. I only had to handle on web.
> @jmagman @snickersv2 I solved it by creating class called driver_commads.dart with `const String getPlatformCommand = 'getPlatform'; ` and in app.dart
> 
> ```
> enableFlutterDriverExtension(handler: (command) {
>   var result = '';
>   switch (command) {
>     case getPlatformCommand:
>       result = Platform.operatingSystem;
>       break;
>   }
> 
>   return Future.value(result);
> });
> ```
> 
> then I check it by `final operatingSystem = await driver.requestData(getPlatformCommand);`

**Comment by ycherniavskyi** [comment]
It seems that this problem is resolved within [integration_test](https://github.com/flutter/flutter/tree/main/packages/integration_test#integration_test) package ([new way of integration testing](https://docs.flutter.dev/testing/integration-tests/migration)).

**Comment by matanlurey** [comment]
This is not something we will be doing, folks are able to add their own extensions to driver as necessary (as seen above).
