### ISSUE TITLE
Steps to enable precompilation on Android

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#3293]
- [ ] Step 0: If building to target armv7, compile the host snapshotter using the clang_i386 toolchain since we need a 32 bit snapshotter on the host for a 32-bit target. By default, we use clang_x64 on the host that is suitable for aarch64 targets. (Set dart_host_toolchain in https://github.com/flutter/engine/blob/c3504b519fcd95179ea832460758712ecd0e433d/sky/engine/bindings/bindings.gni#L9)
- [ ] Step 1: See SnapshotterInvoke to see how to prepare the instructions snapshot and link it into the dylib or executable.
- [ ] Step 2: Patch to include precompiled runtime on Android https://github.com/flutter/engine/blob/c3504b519fcd95179ea832460758712ecd0e433d/sky/shell/BUILD.gn#L48
- [ ] Step 3: Enable dynamic symbol resoultion in https://github.com/flutter/engine/blob/c3504b519fcd95179ea832460758712ecd0e433d/sky/engine/core/script/dart_init.h#L16. You might need to patch how the symbols are resolved on Android (where that symbol is present and how to find that library.)
- [ ] Step 4: Ensure these two methods return valid pointers https://github.com/flutter/engine/blob/c3504b519fcd95179ea832460758712ecd0e433d/sky/engine/core/script/dart_init.cc#L443

**Comment by jason-simmons** [comment]
This has landed
