### ISSUE TITLE
Focus handling affected tiles_scroll_perf performance

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#32932]
https://github.com/flutter/flutter/pull/31438 caused the following benchmarks to regress:

* tiles_scroll_perf__timeline_summary 90th_percentile_frame_build_time_millis
* tiles_scroll_perf__timeline_summary average_frame_build_time_millis

cc @gspencergoog

**Comment by franciscojma86** [comment]
Closing since metrics are green and have been for a while
