### ISSUE TITLE
cull benchmarks regressed

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#32931]
* `cull_opacity_perf__timeline_summary 90th_percentile_frame_build_time_millis`
* `cull_opacity_perf__timeline_summary average_frame_build_time_millis`

regressed slightly on https://github.com/flutter/flutter/commit/a967bc35f34dcaf0fcb451b60e6553e3f28bd7ec which rolled https://github.com/flutter/engine/pull/8964.

**Comment by Hixie** [comment]
May also be caused by https://github.com/flutter/flutter/pull/32717.

cc @jason-simmons @gspencergoog

**Comment by jason-simmons** [comment]
This started with a Skia change - removal of SkMiniPicture (https://github.com/google/skia/commit/046ecb1b5e0133bde915ffbd0f727224169f39b7)

**Comment by chinmaygarde** [comment]
The revert for the removal of SkMiniPicture has landed in https://github.com/flutter/engine/pull/9015.

**Comment by franciscojma86** [comment]
This benchmark still seems pretty flaky on 90th_percentile_frame_rasterizer_time_millis, and it currently shows a regression. Should this be re-baselined?

**Comment by franciscojma86** [comment]
They seem to have gone back to normal. Closing this issue.
