### ISSUE TITLE
IPC schema/codegen system for platform↔flutter and isolate↔isolate interop

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32930]
Using the current platform channel mechanism manually is fine for 'primitive' types and a small number of methods, but for complex data heavy plugins (firebase?) and add-to-app where we need to pass complex business logic data through potentially dozens of IPC APIs, the boilerplate can be very unsafe (untyped) and unergonomic. 

Explore making this process schemafiable via an IDL and send/receive APIs + data classes code-generated on Dart/Kotlin/Swift etc. 

First thoughts: 

- The gRPC schema .protos seems like a great format. But it's not clear whether the gRPC implementation libraries are modular enough to replace parts other than the serialization mechanism. e.g. we don't want any HTTP2, timeout propagation logic. Is it valuable enough still if we only want the gRPC specs and not its implementation?
- FlatBuffers might not be enough. We want both a data-class codegen mechanism and an IPC API codegen mechanism. Half of the pain comes from writing channel methods, spelling out the method names in strings, handling non-existent method names etc etc.
- FIDL could be promising. Not clear enough from reading the docs. 

Edit: 

This IDL should support bidirectional channels and ideally support streams so users can easily implement observables across plugins/modules. 

For instance, if I have a Profile class instance that I dependency inject into native screens and also sent to Flutter, I should ideally be able to call a setter on the Profile.isLoggedIn property and trigger observers in both native screens and Flutter without calling any other imperative functions. 

Related https://github.com/flutter/flutter/issues/24080

**Comment by jonahwilliams** [comment]
Another requirement: There should be no runtime dependencies. For example, if plugin A uses proto version X.1 and plugin B uses proto version X.2 now they are incompatible in ways they weren't before.

**Comment by xster** [comment]
I'm not sure I understood the example. Plugins only have codegened APIs and data classes that talk between Dart and native right? 2 plugins' APIs and data classes should never affect each other right? 

Or did you just mean general schema backward compatibility? A native app using APIs+data classes based on schema v1 should still work with a Flutter module using APIs+data classes based on schema v2 (except using new functions/fields brought in from v2 obviously). 

We should get that mostly for free if we followed .proto best practices such as never removing/reusing proto field numbers etc.

**Comment by jonahwilliams** [comment]
Specifically on the dart side, if the generate code has dependencies they need to compatible. There might be other ramifications for compatibility on the platform side.

**Comment by jonahwilliams** [comment]
For example, the dart protobuf plugin requires runtime support from a dart protobuf package: https://pub.dev/packages/protobuf

FIDL depends on libraries and tools vended by a particular version of the fuchsia sdk

**Comment by xster** [comment]
Ah I see. By runtime, you meant runtime as in build time :P

In other words,

1. Everyone needs to pull in gRPC Dart package v123 in their pubspec and/or codegen using a flutter_tools that depends gRPC Dart package v123
2. Everyone needs to use protobuf v3

We should definitely make sure 1 never becomes true. I think 2 is ok since that's the schema of the schema.

**Comment by jonahwilliams** [comment]
Well both, dart protobuf has a runtime support library

**Comment by jonahwilliams** [comment]
The build time dependencies are actually much easier, because we can force a specific version by handling the build logic ourselves.

**Comment by yjbanov** [comment]
@jonahwilliams would it satisfy the requirements if the runtime parts lived in `dart:ui` or `package:flutter`?

**Comment by mklim** [comment]
I prototyped a rough solution for this basic problem a few weeks ago, but for the plugins ecosystem. The rough working prototype I have is [here](https://github.com/mklim/plugins/tree/auto_channel_builder/packages/auto_channel_builder). The API in that prototype needs work, I was just focused on getting something up and running at the time.

#28348 and #15995 are the two tracking issues for the ecosystem. I have an unfortunately private RFC that predates our OSS template going into my research into this in detail.

To summarize it really briefly, my basic conclusions were:

1. There's two problems here: the schema API and non-primitive data types. They're related but  orthogonal.
2. Dart is too strongly typed to use a function registry at runtime, we do need codegen for this.
3. Existing IDL solutions have a learning curve and require manual set up from devs. If the goal here is to improve developer happiness there's a problem with requiring devs to install an IDL compiler  and then learn the ins and outs of the IDL in addition to Flutter. In addition, no one existing IDL that I analyzed was a perfect fit for us, and most had blockers that we'd need to invest significant work into to adopt.
4. Dart and Flutter have great codegen support, though it doesn't really expect to be ran in a project containing non-Dart files. We can leverage that to generate an API schema in multiple langauges from an abstract interface defined in Dart and annotated with some basic metadata. 

My basic design idea and the thing I demonstrated in the above prototype was to define a Dart interface for the API, then generate all of the boilerplate needing for making calls along that API using Dart. This is a simplified code example for an API that calls into Java from Dart, but the basic principles would work with arbitrary language combinations:

```dart
// "IDL", written by the user. Represents the API for a single MethodChannel.
@MethodChannelApi(channelName: 'com.example.Foo/FooChannel')
abstract class FooChannel {
  bool foo(int bar, int baz);
}
```

```dart
// Dart auto-generated class that invokes the API calls across the method channel.
// The user needs to instantiate and call this from within the plugin.
class FooChannelInvoker implements FooChannel {
  MethodChannel _methodChannel = MethodChannel('com.example.Foo/FooChannel');
  Future<bool> foo(int bar, int baz) async {
    Map<String, dynamic> args = {'bar': bar, 'baz': baz};
    return await _methodChannel.invokeMethod<bool>('foo', args);
  }
}
```

```java
// Java auto-generated interface mirroring the Dart FooChannel.
public interface FooChannel {
  boolean foo(int bar, int baz);
}
```

```java
// Java auto-generated MethodCallHandler for this interface that listens for matching calls.
// Requires the plugin author to implement the interface, and then instantiate this with an impl and Registrar.
// This would probably normally be constructed from within the plugin's registerWith method.
public class FooChannelHandler implements MethodCallHandler {
  public FooChannelHandler(FooChannel impl, Registrar registrar) {
    this.impl = impl;
    MethodChannel channel =
        new MethodChannel(registrar.messenger(), "com.example.Foo/FooChannel");
    channel.setMethodCallHandler(this);
  }

  @Override
  public void onMethodCall(MethodCall call, final Result result) {
    switch (call.method) {
      case "foo":
        result.success(impl.foo(call.argument("bar"), call.argument("baz")));
        break;
      default:
        result.notImplemented();
        break;
    }
  }
}
```

This solution could be extended for more complex data types but only addresses the IPC definition problem on its own. I also needed to creatively work around some of builder's assumptions about living in a dart-only package to get this to work nicely in my prototype.

In addition to that @BugsBunnyBR also mentioned working on something that [also addresses this problem](https://github.com/BugsBunnyBR/plugin_gen.flutter/) when I linked my initial prototype in chat. @bparrishMines was working on something similar to this as well.

Also /cc @amirh and @Hixie, who gave a lot of feedback on the initial design.

**Comment by xster** [comment]
For posterity, there's a design doc for this mechanism that's open for public comment in https://docs.google.com/document/d/1Ei0ZIqdqNjxTHoGB3Ay6SWQg3DMSsKKWl70XoBUCFTA. The first part of the implementation (which will be a pub package) is at https://github.com/flutter/packages/pull/77.

**Comment by xster** [comment]
This is now available for iOS at https://pub.dev/packages/pigeon

**Comment by xster** [comment]
oh look, I found something similar 
http://fluttify.com 
https://github.com/fluttify-project/fluttify-core-example

doc:
https://translate.google.com/translate?sl=zh-CN&tl=en&u=https%3A%2F%2Fjuejin.im%2Fpost%2F5e19306c6fb9a02ff67d3780

cc @amirh @blasten

**Comment by xster** [comment]
A sample project demonstrating pigeon in https://github.com/flutter/samples/pull/465

**Comment by xster** [comment]
Remaining task after filling in the swift part of the demo in samples is to add documentations in https://flutter.dev/docs/development/platform-integration/platform-channels and references in https://flutter.dev/docs/development/packages-and-plugins/developing-packages.

**Comment by xster** [comment]
Closing. We announced it in https://medium.com/flutter/announcing-flutter-1-20-2aaf68c89c75. 

Usage is described in https://flutter.dev/docs/development/platform-integration/platform-channels#pigeon and on pub https://pub.dev/packages/pigeon. 

Example plugin usage https://github.com/flutter/plugins/tree/master/packages/video_player/video_player. 
Example add-to-app usage https://github.com/flutter/samples/tree/master/add_to_app/flutter_module_books.
