### ISSUE TITLE
PointerEvent requires mouse to be held down

### ISSUE THREAD

**Issue by Dibitybopty** [flutter/flutter#32939]
I'm using a Listener widget on a RaisedButton (tried other widgets too) and the Pointer events are only being triggered while the mouse is held down.

**Comment by mps2209** [comment]
I am having the same Issue

**Comment by BondarenkoStas** [comment]
@Dibitybopty is it the same while using current flutter stable? please provide a code example to reproduce it exactly.

**Comment by mps2209** [comment]
> @Dibitybopty is it the same while using current flutter stable? please provide a code example to reproduce it exactly.

I tried this again recently and it seemed to be resolved

**Comment by BondarenkoStas** [comment]
Good, then I think it's safe to close it. If you encounter it again, please comment and I will re-open the issue.
