### ISSUE TITLE
Performance audit embedding Flutter view initialization time

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32945]
It may be unavoidable for users to need to embed a flutter view in their application's home screen. 

Trace the various cold initialization steps, see if any low hanging fruits can be targeted.

If not, document how users can sync up their native view appearance with the first frame listener.

**Comment by gaaclarke** [comment]
We've done a few things that make this better:
1) ShaderWarmUp works in add to app now: https://github.com/flutter/engine/pull/9813
2) Added synchronization with main thread: https://github.com/flutter/engine/pull/9506
3) Fixed the first frame callback for add to app case: https://github.com/flutter/engine/pull/9952
4) Made ShaderWarmUp faster: https://github.com/flutter/flutter/pull/36482

Here is a recent sample from app startup time (tested against PR 36482)
![Screen Shot 2019-07-19 at 2 32 00 PM](https://user-images.githubusercontent.com/30870216/61566916-95cf7a80-aa32-11e9-9ec6-54dea25d44f8.png)
[little.json.gz](https://github.com/flutter/flutter/files/3412787/little.json.gz)

~80ms is spent in FontCollection::FindFontFamilyInManagers.  That seems to be the place currently with a lot of opportunity outside of Skia.  We should use a more complete profiler to introspect into Skia as well.

**Comment by xster** [comment]
This is all in profile mode right? 300ms of pure dart code for one frame does seem a bit intense. Though given a prewarm'ed engine (on which we called runWithEntrypoint ahead of time), this cost is hidden right?

**Comment by gaaclarke** [comment]
An instruments profile confirms there is a lot of work being done with fonts:
![Screen Shot 2019-07-19 at 3 08 34 PM](https://user-images.githubusercontent.com/30870216/61568182-198b6600-aa37-11e9-89e1-9c5f3b6b761b.png)
[flutterstartup.trace.zip](https://github.com/flutter/flutter/files/3412853/flutterstartup.trace.zip)

**Comment by gaaclarke** [comment]
> This is all in profile mode right? 300ms of pure dart code for one frame does seem a bit intense. Though given a prewarm'ed engine (on which we called runWithEntrypoint ahead of time), this cost is hidden right?

Yep, both samples are in profile mode.

**Comment by xster** [comment]
Also cc @GaryQian @jason-simmons for any potential optimizations on the font manager (potentially doing things before the first Dart frame)

**Comment by jonahwilliams** [comment]
Seems like we did do the audit. Hopefully any follow up tasks were filled and or completed
