### ISSUE TITLE
Textfield context menu is not positioned correctly if it has more than two line.

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#32943]
## Steps to Reproduce

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(

        title: Text(widget.title),
      ),
      body: Center(

        child: Column(

          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField( controller: TextEditingController(text: 'asdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasd', maxLines: null),
            ),

          ],
        ),
      ),
    );
  }
}
```

In the screen if you long press the word to bring up context menu, the context menu will show up above the text with a big gap.

It should show up right above the selection.

**Comment by chunhtai** [comment]
@justinmc

**Comment by Shahzainali** [comment]
It would be great if you add screenshot, if possible, Thanks

**Comment by justinmc** [comment]
I was able to reproduce this by adding `maxLines` to the TextField in the code above.  Here's a screenshot:

<img width="200" src="https://user-images.githubusercontent.com/389558/58036815-d5382400-7ae0-11e9-87fc-b78271a14d3d.png" />

Without `maxLines` it renders on a single line and the context menu is the correct distance away:

<img width="200" src="https://user-images.githubusercontent.com/389558/58036950-1fb9a080-7ae1-11e9-8aef-6947356cedf6.png" />

**Comment by chunhtai** [comment]
updated example code to include maxLines

**Comment by OPY-bbt** [comment]
same problem

**Comment by justinmc** [comment]
This seems fixed to me now.  I believe it was recently fixed in https://github.com/flutter/flutter/pull/36974.  @OPY-bbt You'll have to be using the master [channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels) to get the fix for now, otherwise it will be in the next release (>1.8.4).  If you try it out on master and it's still not fixed, please let me know!

<img width="200" src="https://user-images.githubusercontent.com/389558/62875568-1b63e480-bcd8-11e9-806c-fa07b7eaeb1e.png" />
