### ISSUE TITLE
[cloud_firestore] Flutter App working in development but not production, CloudFirestorePlugin.java uses or overrides a deprecated API, uses unchecked or unsafe operations

### ISSUE THREAD

**Issue by ericel** [flutter/flutter#32957]
## My app works well when I do development debug. However, when I do flutter build and flutter install the apk to device,  clicking on app, just says stopped working!

# dependencies
```

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
 
 flutter:
    sdk: flutter
  firebase_auth: ^0.11.1
  google_sign_in: ^4.0.1+3
  flutter_facebook_login: ^2.0.0
  firebase_core: ^0.4.0+1
  cloud_firestore: ^0.11.0+2
  cloud_functions: ^0.3.0+1
  scoped_model: ^1.0.1
  rxdart: ^0.22.0
  intl: ^0.15.8
  moment: ^0.0.1
  http: ^0.12.0+2
  flutter_launcher_icons: "^0.7.0"
  braintree: ^0.1.2
  dio: ^2.1.3
```
# Error or warning I get during the build:
```
Note: C:\dev\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.11.0+2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\dev\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.11.0+2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\dev\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.0+1\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```
Beside that, no other real error logs.

What can be the solution to this?

**Comment by munjata** [comment]
I experienced a similar issue last night when I uploaded a released version.
The debug version was working fine, but not the release one.
When I attached the physical device, and run in release mode from Android Studio, I noticed that it fails when trying to write a downloading file from firestore.		

# Faulty code
Directory tempDir = Directory.systemTemp;
    final File file = File("${tempDir.path}/$fileName");

    final StorageReference strRef =
        FirebaseStorage.instance.ref().child("$COLLECTIONS/$fileName");

    print("++++++++++++++ STARTING DOWNLOAD++++++++++++++++");
    final StorageFileDownloadTask downloadTask =
        strRef.writeToFile(file);

//  ==========================================================================
# Add path_provider: ^0.4.1
import 'package:path_provider/path_provider.dart';


    Directory tempDir = await getTemporaryDirectory();
    final File file = File("${tempDir.path}/$fileName");

    final StorageReference strRef =
        FirebaseStorage.instance.ref().child("$COLLECTIONS/$fileName");

    print("++++++++++++++ STARTING DOWNLOAD++++++++++++++++");
    final StorageFileDownloadTask downloadTask =
        strRef.writeToFile(file);

**Comment by artashsanoyan** [comment]
So this is the flutter sdk and plugins compatibility issue. If you are using the latest version of firebase plugins also make sure that you are using the last version of flutter sdk which is 1.6.0 at this moment.

**Comment by harshapulikollu** [comment]
I also had this same issue, suddenly my app  started crashing in release build. From the logcat in android studio I came to know `firebase_auth` plugin causing and I updated it and it resolved the issue and nothing crashes further on.

**Comment by mulenatni** [comment]
please save my life.....same error
