### ISSUE TITLE
flutter canvas Add rounded corners to irregular graphics

### ISSUE THREAD

**Issue by hetian9288** [flutter/flutter#32955]
![矩形](https://user-images.githubusercontent.com/5409513/57965042-17425800-7971-11e9-8add-7d4f01f5a89e.png)
How can I create such graphics in canvas

**Comment by justinmc** [comment]
You can draw this shape by using canvas's [drawPath](https://api.flutter.dev/flutter/dart-ui/Canvas/drawPath.html).  You'll need to carefully build a Path that matches what you're showing in your image.  Path's `lineTo` and `arcTo` or `cubicTo` should be what you need.  Look at the [docs for Path](https://api.flutter.dev/flutter/dart-ui/Path-class.html) for how to use those.

Then you'll need to provide a Paint that produces the gradient effect.  Create the gradient with [Gradient](https://api.flutter.dev/flutter/dart-ui/Gradient-class.html).linear and assign it to the Paint's `shader` property.

Or you can always import your image as an image if you don't need to do anything too dynamic with it :)

Let me know if you can't get it or anything seems wrong and I'm happy to reopen.

**Comment by fluttercorner** [comment]
[How To Create Rounded Corners Image in Flutter](https://fluttercorner.com/how-to-create-rounded-corners-image-in-flutter/)
