### ISSUE TITLE
'Flutter: New Web Project' resulted in an error.

### ISSUE THREAD

**Issue by johnnylyimo** [flutter/flutter#32965]
I am trying flutter for web, 
I did  all initial setup i did like creating path and run flutter pub global activate webdev, everything has been setup up correctly and flutter doctor gave green ticks

But VS Code failed to open flutter new web project. give me error says "Command 'Flutter: New Web Project' resulted in an error."﻿
Please assist me

**Comment by TahaTesser** [comment]
I'm facing the same issue

**Comment by johnnylyimo** [comment]
The recently update has solved the problem, now in VS code i can open Flutter new web project. 
flutter doctor -v
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.503], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at C:\src\flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

i have done all procedures and last one was to run webdev serve, this give an error that say 
Could not find a file named "pubspec.yaml" in "C:\Users\john\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\protobuf-0.13.11".

Now am looking for solution........ if you know how to fix this please help.

**Comment by jeisux92** [comment]
run vs code as  admin
