### ISSUE TITLE
Problem when setting an image as wallpaper using Java

### ISSUE THREAD

**Issue by headspy** [flutter/flutter#32964]
I am developing a wallpaper app.

I am not getting any problem when setting the wallpaper in Oneplus phone but when I use the same code to set the wallpaper in Honor Play the image is getting distorted.

    WallpaperManager wallpaperManager = WallpaperManager.getInstance(activity);
      DisplayMetrics displayMetrics = new DisplayMetrics();
      (activity).getWindowManager().getDefaultDisplay().getMetrics(displayMetrics);

      // Display
      int display_width = displayMetrics.widthPixels;
      int display_height = displayMetrics.heightPixels;
      System.out.println(display_width+" "+display_height);

      // Image
      int image_width = bitmap.getWidth();
      int imgae_height = bitmap.getHeight();
      System.out.println(image_width+" "+imgae_height);
      
      // starting point wrt Image
      int starting_point_x = (Math.abs(display_width - image_width))/2;
      int starting_point_y = (Math.abs(display_height - imgae_height))/2;
      System.out.println(starting_point_x+" "+starting_point_y);

   

      //Matrix width and height scale
      float matrix_width = display_width/image_width;
      float matrix_height = display_height/imgae_height;

     

      // Matrix
      Matrix matrix = new Matrix();
      matrix.postScale(matrix_width, matrix_height);

      Bitmap bitmap_final = Bitmap.createBitmap(bitmap, starting_point_x, starting_point_y, display_width, display_height, matrix, false);
       try {
          // wallpaperManager.setBitmap(Bitmap.createBitmap(bitmap, desired_stating_width,desired_stating_height,width_main, height_main));
          wallpaperManager.setBitmap(bitmap_final);
          // wallpaperManager.setBitmap(Bitmap.createBitmap(bitmap, 0,0,width_main, height_main));
          System.out.println("Wallpaper is set");
        }
Oneplus 3
![Oneplus 3](https://user-images.githubusercontent.com/23632601/57970456-13c5c580-799f-11e9-9252-905bc4161db8.jpeg)

Honor Play
![Honor Play](https://user-images.githubusercontent.com/23632601/57970469-2a6c1c80-799f-11e9-9236-a978c9b63dfe.jpeg)

**Comment by stuartmorgan** [comment]
Since your issue is with the native Android API, not with Flutter, you should post this on a forum related to Android development in general.
