### ISSUE TITLE
Execution failed for task ':app:packageDebug'.

### ISSUE THREAD

**Issue by rohankumar997** [flutter/flutter#32962]
C:\Users\ag16000\Desktop\P_PRACTISE\FLUTTER\flutter_app_1>flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              1.1s
Resolving dependencies...                                           3.0s

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> C:\Users\ag16000\AppData\Local\Temp\1\tempdir_1559409151955361796: failed to delete one or more files; see suppressed exceptions for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        16.3s
Gradle task assembleDebug failed with exit code 1

**Comment by DMCDavi** [comment]
Facing the same problem

**Comment by jonahwilliams** [comment]
> C:\Users\ag16000\AppData\Local\Temp\1\tempdir_1559409151955361796: failed to delete one or more files; see suppressed exceptions for details

Without the full stack trace or more information we're unlikely to be able to help with this. I'm closing since this issue is likely stale, but feel free to re-open with more information including steps on how to reproduce the issue and the full stack trace from a --verbose run.

**Comment by numbernain** [comment]
1. Run 'flutter clean' in the project directory.
2. 'Flutter run' to build the project again.

**Comment by sandeshrajpoudel** [comment]
Parameter format not correct -                                          

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> Several variant outputs are configured to use the same file name "resources-debug.ap_", filters : MAIN:MAIN

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
