### ISSUE TITLE
Flutter Google-Maps Killing the App with No Errors!

### ISSUE THREAD

**Issue by azamsharp** [flutter/flutter#32975]
I have been facing number of issues with Flutter. Several times a day, Flutter apps just stops responding. This also results in memory leaks, performance issues and the CPU churning. It maybe related to VS Code but happens 2-3 a day sometimes even more. 

Flutter integration with Google Maps dart plugin is also broken. The app simply kills itself silently without any output messages.

**Comment by azamsharp** [comment]
Here is the error: 

Error output from CocoaPods:
↳
    [!] `<PBXGroup UUID=`97C146E51CF9000F007C117D`>` attempted to initialize an object with an unknown UUID. `CF3B75C9A7D2FA2A4C99F110` for attribute: `children`. This can be the result of a merge and  the unknown UUID is being discarded.
    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Error running pod install
Error launching application on iPhone Xʀ.

**Comment by manmetplok** [comment]
Could the issue with the google maps plugin maybe be related to this one?  #31152

**Comment by TahaTesser** [comment]
Hi @azamsharp 
if you're still experiencing this problem with latest stable, please create a new issue and provide the information required in the template.
Thank you
