### ISSUE TITLE
 Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.

### ISSUE THREAD

**Issue by prasant10050** [flutter/flutter#32973]
When i capture image from camera it will thow error. I am using image_picker plugin. This issue is generating from any version of image_picker. I have also use Camera plugin but i have face same issue.
W/Adreno-EGL(28446): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
D/vndksupport(28446): Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
W/Adreno-EGL(28446): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
W/Adreno-EGL(28446): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
D/vndksupport(28446): Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.

please resolve it anyone because it's urgent on my production app.

**Comment by TahaTesser** [comment]
Hi @prasant10050 
if you're still experiencing this problem with latest stable, please create a new issue and provide the information required in the template.
Thank you
