### ISSUE TITLE
Text() widget should have a padding argument

### ISSUE THREAD

**Issue by biancashouse** [flutter/flutter#32978]
Is it just me, or is this a common occurrence: very often wanting to enclose your Text() with a Padding() ?

It would be convenient and save a nesting level if we could optionally pass a padding arg to Text.

**Comment by lkaihua** [comment]
We can easily extend a MyText widget class by customizing a Container class. 

Text as a basic unit, itself should be as simple as possible. 

In HTML compare this:


Maybe the underlying philosophy is: flutter aims to paint elements in a efficiant way, so the parent widget should provide all information about layout, narrowing the canvas space for descends.

**Comment by marcelgarus** [comment]
Flutter relies on the "Composition over Inheritance" principle, which this proposal wouldn't align with.
For more information, you might check out [this StackOverflow answer] (https://stackoverflow.com/questions/54193724/is-it-bad-to-have-a-lot-of-nested-widgets-with-flutter/54196721#54196721).

**Comment by goderbauer** [comment]
https://github.com/flutter/flutter/issues/32978#issuecomment-493810790 is very accurate.
