### ISSUE TITLE
Flutter version solving Failed 

### ISSUE THREAD

**Issue by gk611995** [flutter/flutter#32979]
## Steps to Reproduce

1. Run flutter Upgrade on older flutter version

## Logs

The current Dart SDK version is 2.1.2-dev.0.0.flutter-0a7dcf17eb.

Because flutter_tools depends on build_test >=0.10.7 which requires SDK version >=2.2.0 <3.0.0, version solving failed.
exit code 1

##What i found

I understand this is due to flutter_tools requiring dart sdk version >2.2.0.
But my internal dart sdk version is 2.1.2.
How do i get arround this.Can i upgrade the dart sdk in flutter?

**Comment by christopherfujino** [comment]
@gk611995 are you still in this state? if so, can you share the output of `flutter doctor -v`?

**Comment by VladyslavBondarenko** [comment]
The issue is already long time not active and without answer.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
