### ISSUE TITLE
Once a progress indicator is shown, we never stop repainting

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3298]
Add showPerformanceOverlay: true to the MaterialApp in app.dart to see.

This is a really bad bug.  Open Components > Progress Indicators in the Gallery app.  Once you've done so, we constantly post frames for the rest of the lifetime of the app!

Typically the indicator line in the PerformanceOverlay should stop moving when we have a static scene.  It doesn't on the home page of Gallery due to https://github.com/flutter/flutter/issues/3297, but any of the demos other than Progress Indicators (assuming you've never opened Progress Indicators and triggered this bug) will have static scenes and won't move the indicator.

**Comment by Hixie** [comment]
Do we have any tests for the progress indicators? In theory, any test that triggers whatever it is that results in the leak should get caught by our testing framework now.

**Comment by HansMuller** [comment]
Fixed in https://github.com/flutter/flutter/pull/3367
