### ISSUE TITLE
Make sure flutter attach can work on android/ios device/simulator debug/profile without parameters

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32999]
Internal: b/117557861

@dnfield, I opened an issue for tracking

**Comment by xster** [comment]
Related https://github.com/flutter/flutter/issues/31872

**Comment by xster** [comment]
@dnfield, you were looking at Android mDNS but I forgot where that conversation ended.

**Comment by jonahwilliams** [comment]
For this to work entirely without parameters we'd need to add the capability to broadcast whether we're in debug/profile mode too

**Comment by xster** [comment]
Can you elaborate? Is this just for us to be able to provide a nicer message than can't connect on release mode?

**Comment by jonahwilliams** [comment]
The service protocols for hot reload/restart don't exist in profile mode since it is AOT, but we don't know how to fallback gracefully so we rely on the user to suggest with `--profile`. We could add that capability, but then we run the risk of not exiting if we fail to connect to a debug build

**Comment by dnfield** [comment]
I don't think Android mDNS will work.  Unlike on iOS, there's no networking bridge set up to use - except on the emulator, where multicast packets are documented as not being supported.  We'd need a different solution for Android.

**Comment by jonahwilliams** [comment]
We could create a secondary daemon which is always scanning logs and tracking open/closed dart observatories. Then attach talks to this daemon instead of log scanning.

**Comment by jonahwilliams** [comment]
This is similar to the attach monitor idea from @xster

**Comment by xster** [comment]
@jmagman: perhaps a 'starter project' to consider once you're done with explorations

**Comment by xster** [comment]
Might be related to the profile points above. Customer's reporting:

```
Waiting for a connection from Flutter on SM G9600...
Done.
Error -32603 received from application: Internal error
Error initializing DevFS: JSON-RPC error -32603 (internal error): Internal error
```
on Android

**Comment by xster** [comment]
Putting down another idea from yesterday's offline discussion: 

We can alleviate the need for the whole random port / token dance if we used a preshared key mechanism where the debug port is fixed and discoverable but a service connection can only be made if the host machine has the right key. This way we're not intertwining discovery and authentication.

cc @rmacnak-google @gamebox

**Comment by jonahwilliams** [comment]
That's part of the issue -  we also need to handle debug/profile mode via feature detection, which is only a tool change (and mostly a refactor)

**Comment by xster** [comment]
sg, is there a bug that specifically describes the nature of the feature detection issue? Or you can describe it here as well (so someone picking up this bug will know the full context of what needs to be done).

**Comment by jonahwilliams** [comment]
Yes, I outlined the rough approach here: https://github.com/flutter/flutter/issues/34552

**Comment by xster** [comment]
Ah, that's a lot clearer now. Thanks!

**Comment by blasten** [comment]
This is related to https://github.com/flutter/flutter/issues/41106 now that it's possible to dump the VM service URI to a file, we can just watch this file.
