### ISSUE TITLE
Asking users to always send AppDelegate callbacks to FlutterPluginAppLifeCycleDelegate is non-ideal

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32995]
For super large integrators such as banks, asking them to always forward all application events to a FlutterPluginAppLifeCycleDelegate when they change one of their 100 screens to Flutter because one of the Flutter screen's plugin may potentially need it may be infeasible. 

If the user doesn't send them, we should make it easier to understand what part of which plugin would stop working. 

We should try to make all plugins resilient to not receiving all platform lifecycle events.

cc @dnfield @amirh

**Comment by xster** [comment]
Actually this is only an issue on the iOS plugins API #33071

**Comment by gaaclarke** [comment]
https://github.com/flutter/engine/pull/9893

I've address this a bit in that PR.  This took away certain responsibilities from the FlutterAppDelegate and put them into the FlutterPluginAppLifeCycleDelegate.

**Comment by xster** [comment]
Meeting notes: I think the minimal work remaining here is for the add-to-app integrator to be aware that they control when they register plugins is when the plugins will start receiving lifecycle events
