### ISSUE TITLE
add-to-app should not contain machine- or user-specific artifacts (paths, etc)

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32994]
Since each developer in a team will have a different absolute path to the outer project's corresponding inner flutter module project.

**Comment by xster** [comment]
Should solve https://github.com/flutter/flutter/issues/28725

**Comment by xster** [comment]
Related https://github.com/flutter/flutter/issues/9502

**Comment by xster** [comment]
the title is a bit specific. Though the end goal is that multiple devs should be able to source control their code. Build it on one machine, check in everything in the repo, check out the repo on another machine with another user, build, and everything in git should be clean.

**Comment by xster** [comment]
@jmagman @blasten I think all of our source controlled project configurations only include relative paths now. But want to double check.

**Comment by jmagman** [comment]
There are still some non-source controlled/generated files that should be made relative like https://github.com/flutter/flutter/issues/34294.

But yes, source-controlled files should use relative paths now on the iOS side.

**Comment by jmagman** [comment]
@xster Feel free to reopen if there's more to do here.

**Comment by xster** [comment]
I think we're good here. Thanks!
