### ISSUE TITLE
Better document the module project's platform host project purpose

### ISSUE THREAD

**Issue by xster** [flutter/flutter#32992]
Currently, the module project's platform host projects .android and .ios serve 2 purposes. 

It allows the user to flutter build apk/ios in that folder (with a standard Runner.xcworkspace etc).

It also supplies podhelper.rb, include_flutter.groovy etc as well as the means to power them. 

These 2 mechanisms are almost unrelated. 

Explain this more clearly in documentations.

**Comment by jmagman** [comment]
The .ios one is documented at https://flutter.dev/docs/development/add-to-app/ios/project-setup#module-organization
