### ISSUE TITLE
Tutorial is missing flutter.yaml leading to missing assets

### ISSUE THREAD

**Issue by josephburnett** [flutter/flutter#330]
While doing the Tutorial I was unable to start the first code snippet (https://github.com/flutter/flutter.github.io/blob/master/tutorial.md#basic-widgets)

    $ flutter start
    $ flutter logs
    
    android: I/chromium: [INFO:SkFontMgr_android_parser.cpp(595)] [SkFontMgr Android Parser] '/system/etc/fonts.xml' could not be opened
    android: I/chromium: 
    android: I/chromium: [INFO:SkFontMgr_android_parser.cpp(595)] [SkFontMgr Android Parser] '/vendor/etc/fallback_fonts.xml' could not be opened
    android: I/chromium: 
    android: W/chromium: [WARNING:asset_bundle_impl.cc(45)] Requested asset 'action/drawable-xxhdpi/ic_search_black_24dp.png' does not exist.
    android: W/chromium: [WARNING:asset_bundle_impl.cc(45)] Requested asset 'navigation/drawable-xxhdpi/ic_menu_black_24dp.png' does not exist.
    android: F/libc    : Fatal signal 11 (SIGSEGV) at 0x00000028 (code=1), thread 4269 (io_thread)
    android: W/ActivityManager:   Force finishing activity org.domokit.sky.shell/.SkyActivity

Running Android 4.4.2 and Flutter at commit 778289f on Ubuntu 14.04.

**Comment by josephburnett** [comment]
Phone is a Samsung Galaxy SIII

**Comment by IvBaranov** [comment]
Didn't you try to update Flutter and dependencies?

**Comment by abarth** [comment]
Yes, the tutorial is missing information about `flutter.yaml`.  We recently started requiring a `flutter.yaml` to list the assets used by your app but we haven't updated the tutorial.

If you take a look at https://github.com/flutter/flutter/blob/master/examples/stocks/flutter.yaml you can see an example of such a file.  We need to add it to the tutorial.

Thanks!

**Comment by josephburnett** [comment]
Fixed by https://github.com/flutter/flutter.github.io/pull/88
