### ISSUE TITLE
Update the SystemNavigator.pop doc for add-to-app

### ISSUE THREAD

**Issue by xster** [flutter/flutter#33000]
For instance, 

“On iOS, calls to this method are ignored because Apple's human interface guidelines state that applications should not exit themselves.”

is wrong since pop doesn't imply exist on a2a

**Comment by gaaclarke** [comment]
> is wrong since pop doesn't imply exist on a2a

Can you clarify this?  SystemNavigator.pop should be ignored in full or a2a apps on iOS, no?

**Comment by xster** [comment]
The existing doc says it should be ignored on iOS, though that's only true for full-apps. Calling it in add-to-app is valid if the FlutterViewController isn't the root view controller.

**Comment by gaaclarke** [comment]
> The existing doc says it should be ignored on iOS, though that's only true for full-apps. Calling it in add-to-app is valid if the FlutterViewController isn't the root view controller.

What do you think it should do?  Look to see if the top view controller is a UINavigationController and pop the top view controller if it is?

**Comment by xster** [comment]
Right. Otherwise, check if it itself is the root view controller, if not, pop itself too.

**Comment by gaaclarke** [comment]
https://github.com/flutter/engine/blob/0995d2a86e36525b91f4ce4cf37d10c0ea7eaa96/shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm#L197

Here is the current logic for iOS.

**Comment by xster** [comment]
I think this can be closed now right?
