### ISSUE TITLE
Explain why we're asking our users to use Java 8

### ISSUE THREAD

**Issue by xster** [flutter/flutter#33003]
<img width="760" alt="Screen Shot 2019-05-19 at 5 20 49 AM" src="https://user-images.githubusercontent.com/156888/57982123-e22c1900-79f5-11e9-93f1-82e851fe3bdf.png">

Is part of our onboarding instructions

**Comment by jmagman** [comment]
"The Flutter Android engine uses Java 8 features."  🤷‍♀ 
https://flutter.dev/docs/development/add-to-app/android/project-setup#java-8-requirement

**Comment by xster** [comment]
Ya, let's close this.
