### ISSUE TITLE
Clickable area for png image

### ISSUE THREAD

**Issue by teshlya** [flutter/flutter#33009]
![Screenshot_1558283216](https://user-images.githubusercontent.com/5208267/57985522-1c69da80-7a37-11e9-91ac-f1df2d0c5f08.png)
How can I specify a clickable area for the GestureDetector widget that contains the png image. Because if I click on the blue circle, then is called onTap widget in the red square

**Comment by gilescm** [comment]
Hi has there been any progress on this item or another solution? It would be really useful.

**Comment by goderbauer** [comment]
This can be achieved with a Stack for example. This question would probably be better suited for stackoverflow.
