### ISSUE TITLE
Cross platform project problem

### ISSUE THREAD

**Issue by pkkballer** [flutter/flutter#33008]
I have problem with my project window to mac
1 I create counting example flutter project with Android Studio on window 10 test on real device work fine no error.  (flutter doctor no error)
2 open same project on Latest version of Mac Mojave 10.14.5 with Android Studio (flutter doctor no error) opened Iphone  simulator run flutter get packages (no error) then run build with iphone  simulator then error happen
error log:
Launching lib/main.dart on iPhone 5s in debug mode...
Running Xcode build...
Xcode build done. 3.1s
xcodebuild: error: The workspace named "Runner" does not contain a scheme named "Runner". The "-list" option can be used to find the names of the schemes in the workspace.
Finished with error: Exit code 65 from: /usr/bin/env xcrun xcodebuild -configuration Debug -quiet -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/phansaphongsaisuwan/Desktop/flutter_app_a/build/ios -sdk iphonesimulator -arch x86_64 -showBuildSettings

**Comment by pkkballer** [comment]
when I create counting flutter project with mac then open on window no error

**Comment by xesun** [comment]
Before run 

>  flutter clean 
command

**Comment by justinmc** [comment]
Another thing to try is opening Runner.xcodeproj instead of Runner.xcworkspace with Xcode.

**Comment by VladyslavBondarenko** [comment]
Hi @pkkballer 
I hope  you've solved your problem
Closing this issue
If you disagree please write in the comments and I will reopen it.
Thank you
