### ISSUE TITLE
F/flutter (19404): [FATAL:flutter/runtime/dart_vm.cc(416)] Error while initializing the Dart VM: Wrong full snapshot version, expected '0c73eb70aa4d30f450273cb424be8c62' found 'eed485c757fba5d731e4054412c99f2e'

### ISSUE THREAD

**Issue by AzarouAmine** [flutter/flutter#33007]
## Steps to Reproduce

This happened exactly after I did the following:
1- Flutter upgrade from 1.2.7 to 15.4
2- Installed Dart SDK for Flutter web.

I also upgraded to AndroidX before, but the above steps triggered this error.

## Logs

[ +415 ms] F/flutter (19841): [FATAL:flutter/runtime/dart_vm.cc(416)] Error while initializing the Dart VM: Wrong
full snapshot version, expected '0c73eb70aa4d30f450273cb424be8c62' found 'eed485c757fba5d731e4054412c99f2e'

##  Flutter analysis

This only produces warnings in the code such values not used ... etc.

## Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.765], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.2)
[√] VS Code (version 1.33.1)
[√] Connected device (1 available)

• No issues found!

**Comment by AzarouAmine** [comment]
Fixed the issue by 

- removing the content of `flutter/bin/cache`

- then running `flutter upgrade` again

- then running `flutter clean` prior to `flutter run`

**Comment by moonljt521** [comment]
@AzarouAmine    fix my issue,thanks
