### ISSUE TITLE
[web]: Failed to load resource: the server responded with a status of 500 ()

### ISSUE THREAD

**Issue by kavin014** [flutter/flutter#33010]
When I host the build, getting this error in console,
**Uncaught Unable to load asset: AssetManifest.json**

**AssetManifest.json** file is missing in **assets** folder

How could I sort this out?

**Comment by BondarenkoStas** [comment]
@kavin014 did you solve it? Did you have assets without the AssetManifest.json? Please check the example https://github.com/flutter/flutter/issues/33402#issuecomment-515495930.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
