### ISSUE TITLE
Layer.replaceWith not used, not tested; probably broken?

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#33015]
## Use case

Flutter provides the [Layer.replaceWith](https://api.flutter.dev/flutter/rendering/Layer/replaceWith.html) method. However, this method is neither used by Flutter itself, nor is it covered by any of Flutter's tests. I wouldn't be surprised if it's broken altogether and we just don't know about it.

## Proposal

Some options:

- Remove this method.
- Add tests to make sure this method actually works.

/cc @Hixie

**Comment by Hixie** [comment]
Remove it. I'm sure it's just something we were going to use one day but never got around to. Maybe check the git blame to see why we added it.
