### ISSUE TITLE
Dismissible onDismissed and confirmDismiss not working according to docs

### ISSUE THREAD

**Issue by kriswuollett** [flutter/flutter#33016]
According to the documentation, the `confirmDismiss` callback:

    Gives the app an opportunity to confirm or veto a pending dismissal.

    If the returned Future completes true, then this widget will be dismissed, otherwise it will be 
    moved back to its original location.

    If the returned Future completes to false or null the onResize and onDismissed callbacks will 
    not run.

The type of `confirmDismiss` is:

```dart
typedef ConfirmDismissCallback = Future<bool> Function(DismissDirection direction);
```

The two combined made me assume that if the returned `Future` returns `true`, then the `onResize` and `onDismissed` callbacks _will run_.  So I expected that if one is building an app with a synchronous data store, then `confirmDismiss` should be `null` or `true`. Or if using an asynchronous data store, then `confirmDismiss` should be the `Future` from an invocation on a service mapped to a `bool` depending on the service call success. Then `onDismissed` could be the single place to store logic like displaying snack bars when the action is confirmed done.

_However if I provide a `confirmDismiss` that returns a `Future<bool>` (and currently always results in true at the moment), then `onDismissed` is never called._

The next thing I noticed was that gallery's `leave_behind_demo` [is not returning a `bool`](https://github.com/flutter/flutter/blob/51799d31907fc86fd8c52faac4dec82013a3a520/examples/flutter_gallery/lib/demo/material/leave_behind_demo.dart#L230). From a user's perspective the demo works, but I really don't know what to make of the type checking situation. I'd expect it to not compile since that anonymous function doesn't appear to be returning a bool.

## Steps to Reproduce

Update `leave_behind_demo.dart`'s `Dismissable` construction with these updated parameters to add print statements and `bool` returns:

```dart
Dismissible(
        onDismissed: (DismissDirection direction) {
          print('onDismissed');
          if (direction == DismissDirection.endToStart)
            _handleArchive();
          else
            _handleDelete();
        },
        confirmDismiss: !confirmDismiss ? null : (DismissDirection dismissDirection) async {
          print('confirmDismiss running');
          switch(dismissDirection) {
            case DismissDirection.endToStart:
              if (await _showConfirmationDialog(context, 'archive')) {
                _handleArchive();
                print('confirmDismiss returning true');
                return true;
              }
              break;
            case DismissDirection.startToEnd:
              if (await _showConfirmationDialog(context, 'delete')) {
                _handleDelete();
                print('confirmDismiss returning true');
                return true;
              }
              break;
            case DismissDirection.horizontal:
            case DismissDirection.vertical:
            case DismissDirection.up:
            case DismissDirection.down:
              assert(false);
          }
//          print('confirmDismiss returning Void');
          print('confirmDismiss returning false');
          return false;
        }
),
```

Then also add some print statements to `_handleDismissStatusChanged`, `_confirmStartResizeAnimation`, `_startResizeAnimation`, and `_handleResizeProgressChanged` to track all state and decision points.

When returning false from the Future you'll get output like:

```
flutter: KW: _handleDismissStatusChanged status: AnimationStatus.forward
flutter: KW: _handleDismissStatusChanged status: AnimationStatus.completed
flutter: KW: _confirmStartResizeAnimation returning Future<bool>
flutter: confirmDismiss running
flutter: confirmDismiss returning false
flutter: KW: _handleDismissStatusChanged awaited confirm did not return true
flutter: KW: _handleDismissStatusChanged status: AnimationStatus.reverse
flutter: KW: _handleDismissStatusChanged status: AnimationStatus.dismissed
```

When returning true from the Future you'll get output like (notice `onDismissed` not called):

```
flutter: KW: _handleDismissStatusChanged status: AnimationStatus.forward
flutter: KW: _handleDismissStatusChanged status: AnimationStatus.completed
flutter: KW: _confirmStartResizeAnimation returning Future<bool>
flutter: confirmDismiss running
flutter: confirmDismiss returning true
flutter: KW: _handleDismissStatusChanged awaited confirm returned true
flutter: KW: _startResizeAnimation
flutter: KW: _handleResizeProgressChanged: AnimationController#3e6fa(▶ 0.000)}
```

Now revert the demo code so that the Future callback returns void, and then output whether confirming or not will be:

```
flutter: KW: _handleDismissStatusChanged status: AnimationStatus.forward
flutter: KW: _handleDismissStatusChanged status: AnimationStatus.completed
flutter: KW: _confirmStartResizeAnimation returning Future<bool>
flutter: confirmDismiss running
flutter: confirmDismiss returning Void
flutter: KW: _handleDismissStatusChanged awaited confirm did not return true
flutter: KW: _handleDismissStatusChanged status: AnimationStatus.reverse
```

However if you delete the `confirmDismiss` attribute (turn off confirmations in the demo), you'll get output:

```
flutter: KW: _handleDismissStatusChanged status: AnimationStatus.forward
flutter: KW: _handleDismissStatusChanged status: AnimationStatus.completed
flutter: KW: _confirmStartResizeAnimation returning true because confirmDismiss is null
flutter: KW: _handleDismissStatusChanged awaited confirm returned true
flutter: KW: _startResizeAnimation
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.059)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.112)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.167)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.220)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.280)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.328)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.391)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.449)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.496)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.555)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.609)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.662)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.726)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.776)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.831)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.883)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.943)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(▶ 0.996)}
flutter: KW: _handleResizeProgressChanged: AnimationController#324fe(⏭ 1.000; paused)}
flutter: onDismissed
```

Therefore the Dismissable implementation and the demo (with the modification in #30497) seem inconsistent with the docs.

Successful resolution to the issue to me seems like:

1.  `onDismissed` is called when `confirmDismiss` returns a `Future<bool>` that results in `true` (implementation to match the docs).
2.  `Dismissable` throws an `Error` (or use an `assert`) if it detects that the the future it used did not return a `bool` (catch incorrect usage).

## Logs

`flutter run --verbose` didn't seem interesting compared to custom logs above.
`flutter analyze` had no issues found.

```
Kristophers-MacBook-Pro:flutter_gallery kris$ flutter doctor -v
Warning: the 'flutter' tool you are currently running is not the one from the current directory:
  running Flutter  : /Users/kris/.local/opt/flutter
  current directory: /Users/kris/workspace/flutter
This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you're running the expected version (run 'flutter --version' to see which flutter is on your path).


[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/kris/.local/opt/flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kris/.local/opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/kris/.local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7141.49

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (1 available)
    • iPhone Xʀ • [*** REDACTED ***] • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by kriswuollett** [comment]
Also related to this when running the demo with confirmation on, there is no nice sliding up animation to make the row disappear, the table looks like it just cross-fades into its new state after the confirmation dialog is dismissed.

**Comment by kriswuollett** [comment]
Maybe it is possible to change the return type of `ConfirmDismissCallback` to `FutureOr<bool>` (default value is just `true`) and disallow `void` or returning `null`. That could allow some flexibility.  With that I'd almost think the `onDismisssed` should be replaced with an animation progress callback that gives direction and completion towards being dismissed or reverted (not familiar enough with Flutter's animation on how I'd do some animation in sync with dismissing an item -- but not trying for that at this time).

But... on the other hand, maybe I'm trying to do something unexpected?

**Comment by darrenaustin** [comment]
Thanks for pointing this out. There are several issues with the demo code:

- The `confirmDismiss` callback was not always returning a valid `true` or `false` value. In the case where the user dismisses the dialog (by tapping on the background barrier, or hitting the back button on an Android device), the value coming back from `_showConfirmationDialog` will be `null`. This causes an exception at runtime. To fix this we need to change:

```dart
if (await _showConfirmationDialog(context, 'archive')) {
```

to

```dart
if (await _showConfirmationDialog(context, 'archive') == true) {
```

and the equivalent for the 'delete' clause, and add a `return false;` to the end of the callback to ensure it always has a valid return value.

- The other issue is the the `confirmDismiss` callback is actually implementing the item dismissal itself by calling `_handleArchive` and `_handleDelete` directly. These both remove the item immediately and don't allow the usual dismissal code to handle it. The `confirmDismiss` callback should only return whether the dismiss is allowed or not, and let the rest of the system deal with dismissing the item:

```dart
switch(dismissDirection) {
  case DismissDirection.endToStart:
    return await _showConfirmationDialog(context, 'archive') == true;
  case DismissDirection.startToEnd:
    return await _showConfirmationDialog(context, 'delete') == true;
  case DismissDirection.horizontal:
  case DismissDirection.vertical:
  case DismissDirection.up:
  case DismissDirection.down:
    assert(false);
}
return false;
```

I just submitted a PR that does just this: #33080

With this two changes, I think it will work as you would expect with the onDismiss getting called properly.

As for the analyzer not catching the case where the callback is not always returning a value it looks like the Dart folks have tried to fix this before, but it hasn't landed yet. See https://github.com/dart-lang/sdk/issues/28233.

**Comment by kriswuollett** [comment]
Cool! Thanks for the updates, and the link to the Dart issue re the analyzer. I updated the code in my app to only do the delete in the `onDismissed` similarly and more or less happy with the setup for now. Still may eventually revisit with a question on the API itself assuming delete will work, but it's no longer a top issue for me at the moment.
