### ISSUE TITLE
Shader compilation error (Skia)

### ISSUE THREAD

**Issue by SvenSchoene** [flutter/flutter#33019]
## Steps to Reproduce

- Here is a minimal reproduction: https://github.com/SvenSchoene/bug_reproduction-_shader_compilation_error
- There is also a screenshot there: https://github.com/SvenSchoene/bug_reproduction-_shader_compilation_error/raw/master/shader_compilation_error.PNG
- I happened to use the `image_picker`-library to reliably reproduce the bug. However, in my real application it happens at many different points. I believe, it is mostly related to rendering operations triggered by navigation events, but that is just a gut feeling and I don't want to send anyone searching in the wrong direction.
- I also want to note that this "bug" is not causing me any other issues. However, I'd rather be safe than sorry and know a bit more about this before we ship our application. 
- I finally want to note that while there seem to be no other issues related to this "bug", I do notice some heavy jank in animations when this happens.

## Logs

Logs are long, so here's a gist https://gist.github.com/SvenSchoene/712b1f80a9074c717ac91567efeabce3

**Comment by creativecreatorormaybenot** [comment]
@SvenSchoene Could you move the log to a GitHub gist? Could make the thread more readable.

**Comment by SvenSchoene** [comment]
Good point. Done.

**Comment by erfanasg** [comment]
i also have this problem. i use flutter 1.7 stable version and this is the first time i see this..

**Comment by chinmaygarde** [comment]
The logs seem to indicate EGL emulation. Was this on an emulator? If so, can you provide details on how it was created and some information about host configuration?

**Comment by iapicca** [comment]
Hi @SvenSchoene 
I see there's an open [issue](https://github.com/flutter/flutter/issues/33018) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
