### ISSUE TITLE
High Memory Usage When Using Flutter

### ISSUE THREAD

**Issue by azamsharp** [flutter/flutter#33014]
I use VS Code to implement Flutter code and I have been noticing that every day 2-5 times a day CPU shows high usage and completely kills the machine. 

I am using MacBook Pro 13 8 GB RAM (2017). 

How can I collect the log. This may be related to VS Code or even Flutter leaking memory somewhere.

**Comment by iapicca** [comment]
Hi @azamsharp 
I see there's an open [issue](https://github.com/flutter/flutter/issues/43139
) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
