### ISSUE TITLE
SingleChildScrollView->Text "\t" Chinese display Error

### ISSUE THREAD

**Issue by q805699513** [flutter/flutter#33022]
```
class BookContentPage extends StatefulWidget {
  final String _bookUrl;

  BookContentPage(this._bookUrl);

  @override
  State<StatefulWidget> createState() {
    return BookContentPageState();
  }
}

class BookContentPageState extends State<BookContentPage> {
  String _content = "";

  @override
  void initState() {
    super.initState();
    getData();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: SingleChildScrollView(
          reverse: false,
          padding: EdgeInsets.fromLTRB(
              Dimens.leftMargin, 16, Dimens.rightMargin, 16),
        child: Text(
          _content,
          style:
              TextStyle(color: MyColors.textBlack3, fontSize: Dimens.textSizeM),
        ),
        ),
      ),
    );
  }

  void getData() async {
    await Repository()
        .getBookChaptersContent(this.widget._bookUrl)
        .then((json) {
      BookContentResp bookContentResp = BookContentResp(json);
      setState(() {
        _content = bookContentResp.chapter.cpContent;
      });
    }).catchError((e) {
      print(e.toString());
    });
  }
}

```

**Comment by q805699513** [comment]
{"ok":true,"chapter":{"title":"外篇二 绝世","body":"\n\r\n\r\n\r请安装最新版追书 以便使用优质资源","isVip":false,"cpContent":"今天看到书评区非常火热，还有很多人飘红，谢谢大家的热情，谢谢所有人。\n\t　　下面的不是新书《圣墟》的内容，只是几年前写的短篇，放出来给大家看。\n\t　　按照以前说的时间，11月1日上午开始上传新书《圣墟》的正文。\n\t　　天缺道人点头，蛇行鹤打，虎扑羚跳，飘逸出尘，带着一种自然，抗击钵盂，消减上面的佛光。\n\t　　“住持快走！”\n\t　　就在这一刻，共有十八名僧人冲起，每一个都如金身罗汉一样，通体绽放黄金神光，围攻向天缺道人。\n\t　　这是十八罗汉大阵，由十八位顶尖高手施展，可以对抗无上宗师，再加上从天镇压而下的佛宝钵盂，恐怖无边！\n\t　　大光明寺的人变色，没有想到慧清的一脉的强者这么多与可怕，难道真的要任他逃走不成？\n\t　　天缺道人被缠住了，独自对抗十八位金身罗汉，且还要抗衡大光明寺的镇教至宝，遭遇了极大的压力。\n\t　　“锵”\n\t　　突然，古天舒出手，铁剑横空，照耀出一片冷冽的寒芒，如一挂银河从天而降，他登天而上，追上了慧清禅师。\n\t　　剑气千幻，如九天银河垂落，绚烂夺目，铺天盖地，白茫茫一片。\n\t　　古天舒与慧清大战，杀气冲天，剑芒照亮了夜空，发出龙吟凤鸣之音，亦有千条瑞气、万道佛光不断幻灭。\n\t　　两人生死对决，最终一道神芒从天而降，“噗”的一声，像是仙剑降世，洞穿了慧清的天灵盖，将其毙掉。\n\t　　古天舒拔出铁剑，死尸坠落下半空，他人与剑合一，化成一道炫目的神光，“铮”的一声斩在光芒炽盛的钵盂上，火花四溅，将其劈飞。\n\t　　天缺道人压力顿减，大袖挥动，蛇行鹤打，猿跃龙缠，将十八位绝顶高手全部重创，倒在寺院中。\n\t　　慧清伏尸，十八位金身罗汉败亡，大局已定，剩下的战斗很快就结束了，大光明寺经历了一次大清洗。\n\t　　“小友真乃天纵奇才，在这个年龄段就已接近宗师领域，古今罕见。”天缺道人叹道。\n\t　　“前辈保重！”古天舒跃马远行，他知道这可能是最后一次见到老道士了，一代奇人寿元将尽，不久于人世。\n\t　　果然，未足半月中原震动，无上宗师天缺道人溘然长逝，结束了他辉煌而灿烂的一生。\n\t　　十方皆动，许多人悲呼，老道士身为当世无上高手，震慑天下，斩邪除孽，曾在四十年前于万军中斩草原之主，惊的铁骑止步，不敢南下，让世人敬仰。\n\t　　“前辈走好！”古天舒听闻消息后，轻叹了一口气，将一杯酒水倒在地上。\n\t　　四大无上宗师去一，而今只剩下了三人，分别为北方草原国师莫勒，迷幻海主人盖九幽，焚炎谷主戚苍。\n\t　　一道奇人天缺道人逝去，全天下瞩目，而今谁能接替他的位置，成为第四位无上宗师？\n\t　　古天舒重出世间后，仗剑而行，已过去数月之久，一路所见，烽烟四起，许多百姓流离失所，路旁常有饿死骨。\n\t　　战乱席卷大地，旧朝名存实亡，大秦、大汉、大齐三足鼎立，战场上刀光剑影，流血成河，尸骨成山。\n\t　　山河已破碎，苦的最终是百姓。古天舒一路行一路思，他想改变现状，还人间安宁，但却觉得个人再强大，也难以主天下沉浮。\n\t　　洛阳城，雄伟磅礴，远眺城墙如一道绵绵不绝的钢铁长城，坚不可摧。\n\t　　它已落入大秦之手，虽然历经战火洗礼，但是它始终屹立不倒，为中原的不朽神城。\n\t　　城内车水马龙，川流不息，叫买叫卖声不绝于耳，遭遇战火后，人心惶恐，繁华有减，已比不上昔日，不过却远胜其他城池。\n\t　　古天舒在桃源村隐居两年，而今故地重游，感慨万千，不知昔日的故友而今在何方？\n\t　　“上将军潘明远被刺杀了。”\n\t　　洛阳城一阵大乱，人喊马嘶，许多精兵身上甲胄闪烁，封锁各个交通要道，街上一片大乱。\n\t　　古天舒心头剧震，用力抓住一个人，喝问道：“哪个潘明远？”\n\t　　这个路人被吓的战战兢兢，颤抖着说出了上将军的来历，让古天舒久久未语，竟真的是他那位故人。\n\t　　他与潘明远、许长青、杨志毅等人生死与共，两年前他火拼紫发道尊时，几人得悉后连夜疾驰数千里，从天下各地赶去援救，皆大口吐血，差点活活累死。\n\t　　最终那一战，古天舒靠自己的力量斩杀了紫发道尊，不过却也元气大伤，因此而在桃源村潜修了两年。\n\t　　“潘明远死了……”他一阵失神，而后化成一道流光冲向远处的将军府。\n\t　　“不要让刺客逃走！”一群兵丁追赶，且有强者通体发光在天空中飞行追击一个青衣人。\n\t　　古天舒冷哼，一步登天而上，黑发飞舞，脸色冰冷，背后铁剑铮铮而鸣，如一尊杀神一样挡在前方。\n\t　　青衣人似很吃惊，叫道：“天舒！”\n\t　　“长青大哥是你！”古天舒一呆，为什么会这样，昔日故友为何自相残杀？\n\t　　“走，我们去城外说。”许长青道，如一颗流星一样远去，身后追兵不能及。\n\t　　古天舒心中沉重，紧随其后出城，一路追了下去，当远去几十里，两人同时停了下来。\n\t　　“真的是你杀的？”\n\t　　“是我，是我杀了昔日共历生死的潘明远兄弟。”许长青眼中有泪水滚落。\n\t　　“为什么？”\n\t　　“因为他疯了，欲引北方草原铁骑南来，助大秦平定天下，这完全是引狼入室，毁我中原！”许长青大哭，他与潘明远是生死与共的兄弟，共患难，感情深，但是却亲手杀了他，有血泪滚落。\n\t　　潘明远是一个很果敢的人，见天下四分五裂，想早日平定，还百姓太平乐业，铤而走险，想借北方草原铁骑的力量。\n\t　　“他说已布下绝杀毒计，利用完草原铁骑，将他们全部坑杀在中原，既统一了天下，又绝了北方大患。可是，他却是在拿全天下做赌注，铁骑南下，谁能保证一切可控，我们百般劝说，他根本不听，要上书秦主向草原借兵。”\n\t　　……\n\t　　昔年，古天舒火拼紫发道尊时，潘明远第一个赶到，累的元气大伤，差点死在当场。\n\t　　而今，却再也不能相见了，他死在了故人的手中，古天舒一声长叹，皆是天下大乱之祸。\n\t　　“杀潘明远后，我亦不愿独生，但却不能这样死，我要去战场，若依然有铁骑南下，必以我血溅边境。”许长青毅然决然的道。\n\t　　“长青不要做傻事！”古天舒大喊。\n\t　　青衣猎猎，许长青远去，消失在天际尽头。\n\t　　古天舒一声叹息，得悉潘明远死去，有些心灰意冷，在一座荒山上建了一座草堂，又开始隐居。\n\t　　他吐纳练气，默诵黄庭，一心修行，一晃又过去了两年。\n\t　　他生平有两志，一愿平天下，二是望证道。\n\t　　天下大乱，群雄逐鹿，烽火连天，是为大势，若投身进去，不知何日才能脱身。\n\t　　修行之路，自古孤寂，无上宗师也没有迈出最后一步，总有死去的一天，他练气修身，希望有朝一日可以窥破生死奥秘，迈出前人不能走出的那一步。\n\t　　一晃两年过去了，这一日一声大呼打破了荒山的宁静，一个披头散发的人向山上跑来。\n\t　　“天舒你果然在此隐居……”这是一个虬须大汉，满身是血，似乎刚从战场回来，身上有不少伤痕。\n\t　　“志毅！”古天舒走出草堂，露出惊喜之色。潘明远、许长青、杨志毅、赵坤几人是昔日可以换命的故友。\n\t　　“草原铁骑南下，进入了秦、汉、齐三方战场，长青他……战死了！”杨志毅虎目中滚出泪水。\n\t　　潘明远虽然死了，但是大秦两年后终究还是引草原铁骑南下了，已进入三国交界处的战场，血水染红了大地，杀伐之气冲天。\n\t　　“天舒你天纵之资，可达到了宗师之境？草原国师莫勒来了，统率高手无数，无人可敌，专杀上将，长青就是死在了他的大弟子手中。”杨志毅道。\n\t　　“我与你去三方战场！”古天舒背负铁剑下山。\n\t　　三方战场，是一片染血的魔土，也不知死去了多少人，连土地都变成了血色，每到夜间鬼火幽幽。\n\t　　若是雨天，可见到地上淌的不是雨水，而猩红的血，这里阴气缭绕，常年笼罩魔云，森然慑人。\n\t　　大秦引草原铁骑南下，震惊天下，草原宗师莫勒无人可敌，杀中原高手无数。\n\t　　同在四大宗师内，迷幻海主人盖九幽欲出手，不想却被焚炎谷主戚苍所阻，无法进入三方战场。\n\t　　铁骑南侵，无人可挡莫勒，杀的天下高手尽变色。\n\t　　就在这个月夜，传来一声大吼：“我来杀莫勒！”\n\t　　神月当空，皎洁灿灿，月光洒满战场，却难以照散死亡阴气。\n\t　　“天缺道人已逝，戚苍不出，盖九幽老迈，还有谁能与我莫勒争锋？”北方草原国师是一个高大雄伟的老人，如一头老狮子一样，满脸虬须，身上流淌有神华。\n\t　　半个月来，消息传遍天下，有奇人将出世大战草原无上宗师，也不知有多少高手关注，来到了三方战场。\n\t　　夜月下，人影闪动，除却大军外，还有很多修士，尽在远观。\n\t　　“是我，古天舒！”夜月下，一个男子脚踏虚空而来，如水的月光洒落，将他映衬的如同一名谪仙一般。\n\t　　“年轻人不懂得珍惜生命。”莫勒也登天而上，浑身黄金神光璀璨绽放，让这个高大魁伟的老人看起来如同一尊战神一样。\n\t　　“莫勒，你若率铁骑离去，我转身就走，若不然今日取你项上人头，仗剑杀入草原！”古天舒话语铿锵，如剑铮铮剑鸣。\n\t　　“轰”\n\t　　一场惊天动地的大战爆发！\n\t　　剑气纵横，照亮了整片战场，白茫茫一片，气冲斗牛！\n\t　　莫勒魁伟，大开大合，双拳挥动，惊雷阵阵，电闪雷鸣，如海啸一样的声音发出。\n\t　　古天舒左拳右剑，气贯长虹，每一击都让天地震动一下，在两人间各种光华闪烁，像是要撕裂了虚空。\n\t　　这还是人力吗？所有人都不禁要这样问，两人的表现，几近神明！\n\t　　“轰！”\n\t　　最终，古天舒一剑劈出，勾动了一片遮空的云朵，降下万丈雷电，向莫勒劈去，震惊三方战场。\n\t　　“神迹，这是神迹啊！”\n\t　　人们忍不住惊呼，技几乎道，这超出了常人的理解。\n\t　　“砰”\n\t　　莫勒被万丈雷电劈中，但并没有化成飞灰，张嘴吐了几大口鲜血，浑身金光璀璨，淹灭了电芒。\n\t　　“轰”\n\t　　就在这一刻，他的手中亦发出一片刺目的光华，如一轮太阳在绽放，莫勒大喝道：“如此年轻的无上宗师古来罕见，让我以草原至宝战神戟送你上路！”\n\t　　在其手中有一杆战戟，沉重如山，像是要压塌虚空一般，戟杆乌黑，戟刃雪亮，带着阵阵血光，一看就是饮过无尽生灵之血的可怕武器。\n\t　　“哧”\n\t　　战神戟如有生命一样，在其手中颤抖，向天一击，射出一片可怕的血芒，一下子就震碎了天穹的云朵。\n\t　　而后，莫勒双手持战神戟立劈而下，斩向古天舒，威压惊慑九天十地！\n\t　　所有人都震撼，这果然是一杆属于神明的兵器，戟杆未变，依然是原来那么粗，持在莫勒手中。可是，前方的戟刃，却光芒刺目，化成了山岳一般高，劈杀了下来。\n\t　　凡人的力量怎么阻挡？那可是与山比高的一片雪亮的戟刃，吞吐出可怕的血光，骇人心神！\n\t　　“锵”\n\t　　古天舒横剑阻挡，以手中铁剑斩在了战神戟上。\n\t　　炫目的光芒爆发而出，像是有十轮太阳炸碎了，让所有人都睁不开眼睛。\n\t　　“喀嚓”\n\t　　最终，铁剑崩碎，战神戟完好无损，向下压来，隆隆而响，电神雷鸣，惊慑世间。\n\t　　“失去了铁剑，你还拿什么与我斗？”莫勒的声音冰冷无情，站在虚空中大喝。\n\t　　“只要我这个人还在就行，即便你手持神明的兵器亦无用。”古天舒踏月而进，道法自然，与天地相合，融为了一体。\n\t　　“杀！”莫勒大喝，手持战神戟又一次劈落下来，将天穹都震裂了，光华淹没了天地。\n\t　　古天舒避过这凌厉一击，而后踩着如山岳一样大的戟刃，落在戟杆上，如一尊神灵一样化成圣光扑杀向莫勒。\n\t　　“噗”\n\t　　一道血光出现，古天舒以手代剑，在莫勒的颈项上一划，一颗染血的头颅带着不甘与不相信的神色飞了出去，无头尸体喷血，坠落在三方战场中。\n\t　　明月夜下，古天舒天人合一，手持战神戟而立。\n\t　　遥远的北方大草原，一座古老的神庙中，腾起一道划破了古今未来的光芒，一尊巨大的神明虚影上抵九天下踏九幽，眸光冰冷，望向中原。\n\t　　同一时刻，中原也有数道不朽的神光冲上九霄，像是有几尊神明觉醒，透过虚空，遥望三方战场。\n\t　　古天舒身与天地大道相合，感应到了那几束不朽的光辉，他向前踏出了一步，像是要破碎虚空而去，道：“你们真的存在，也想介入人族的战争中吗？”\n\t　　短篇到这就结束了，明天上午开始正式上传《圣墟》的正文。","currency":25,"id":"5817f1161bb2ca566b0a5974"}}

**Comment by q805699513** [comment]
![156156](https://user-images.githubusercontent.com/12568757/57994951-34eafb00-7af2-11e9-85bd-6a23b14ee2c4.png)

**Comment by q805699513** [comment]
Remove "\t" to solve
_content = bookContentResp.chapter.cpContent.replaceAll("\t","\n");

**Comment by VladyslavBondarenko** [comment]
@q805699513 
I can't reproduce it, right padding persists with `\t`.

<details>
 <summary>code sample</summary>

```

import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: SingleChildScrollView(
          reverse: false,
          padding: EdgeInsets.fromLTRB(
              16, 16, 16, 16),
          child: Text(
            '今天看到书评区非常火热，还有很多人飘红，谢谢大家的热情，谢谢所有人。\n\t　　下面的不是新书《圣墟》的内容，只是几年前写的短篇，放出来给大家看。\n\t　　按照以前说的时间，11月1日上午开始上传新书《圣墟》的正文。\n\t　　天缺道人点头，蛇行鹤打，虎扑羚跳，飘逸出尘，带着一种自然，抗击钵盂，消减上面的佛光。\n\t　　“住持快走！”\n\t　　就在这一刻，共有十八名僧人冲起，每一个都如金身罗汉一样，通体绽放黄金神光，围攻向天缺道人。\n\t　　这是十八罗汉大阵，由十八位顶尖高手施展，可以对抗无上宗师，再加上从天镇压而下的佛宝钵盂，恐怖无边！\n\t　　大光明寺的人变色，没有想到慧清的一脉的强者这么多与可怕，难道真的要任他逃走不成？\n\t　　天缺道人被缠住了，独自对抗十八位金身罗汉，且还要抗衡大光明寺的镇教至宝，遭遇了极大的压力。\n\t　　“锵”\n\t　　突然，古天舒出手，铁剑横空，照耀出一片冷冽的寒芒，如一挂银河从天而降，他登天而上，追上了慧清禅师。\n\t　　剑气千幻，如九天银河垂落，绚烂夺目，铺天盖地，白茫茫一片。\n\t　　古天舒与慧清大战，杀气冲天，剑芒照亮了夜空，发出龙吟凤鸣之音，亦有千条瑞气、万道佛光不断幻灭。\n\t　　两人生死对决，最终一道神芒从天而降，“噗”的一声，像是仙剑降世，洞穿了慧清的天灵盖，将其毙掉。\n\t　　古天舒拔出铁剑，死尸坠落下半空，他人与剑合一，化成一道炫目的神光，“铮”的一声斩在光芒炽盛的钵盂上，火花四溅，将其劈飞。\n\t　　天缺道人压力顿减，大袖挥动，蛇行鹤打，猿跃龙缠，将十八位绝顶高手全部重创，倒在寺院中。\n\t　　慧清伏尸，十八位金身罗汉败亡，大局已定，剩下的战斗很快就结束了，大光明寺经历了一次大清洗。\n\t　　“小友真乃天纵奇才，在这个年龄段就已接近宗师领域，古今罕见。”天缺道人叹道。\n\t　　“前辈保重！”古天舒跃马远行，他知道这可能是最后一次见到老道士了，一代奇人寿元将尽，不久于人世。\n\t　　果然，未足半月中原震动，无上宗师天缺道人溘然长逝，结束了他辉煌而灿烂的一生。\n\t　　十方皆动，许多人悲呼，老道士身为当世无上高手，震慑天下，斩邪除孽，曾在四十年前于万军中斩草原之主，惊的铁骑止步，不敢南下，让世人敬仰。\n\t　　“前辈走好！”古天舒听闻消息后，轻叹了一口气，将一杯酒水倒在地上。\n\t　　四大无上宗师去一，而今只剩下了三人，分别为北方草原国师莫勒，迷幻海主人盖九幽，焚炎谷主戚苍。\n\t　　一道奇人天缺道人逝去，全天下瞩目，而今谁能接替他的位置，成为第四位无上宗师？\n\t　　古天舒重出世间后，仗剑而行，已过去数月之久，一路所见，烽烟四起，许多百姓流离失所，路旁常有饿死骨。\n\t　　战乱席卷大地，旧朝名存实亡，大秦、大汉、大齐三足鼎立，战场上刀光剑影，流血成河，尸骨成山。\n\t　　山河已破碎，苦的最终是百姓。古天舒一路行一路思，他想改变现状，还人间安宁，但却觉得个人再强大，也难以主天下沉浮。\n\t　　洛阳城，雄伟磅礴，远眺城墙如一道绵绵不绝的钢铁长城，坚不可摧。\n\t　　它已落入大秦之手，虽然历经战火洗礼，但是它始终屹立不倒，为中原的不朽神城。\n\t　　城内车水马龙，川流不息，叫买叫卖声不绝于耳，遭遇战火后，人心惶恐，繁华有减，已比不上昔日，不过却远胜其他城池。\n\t　　古天舒在桃源村隐居两年，而今故地重游，感慨万千，不知昔日的故友而今在何方？\n\t　　“上将军潘明远被刺杀了。”\n\t　　洛阳城一阵大乱，人喊马嘶，许多精兵身上甲胄闪烁，封锁各个交通要道，街上一片大乱。\n\t　　古天舒心头剧震，用力抓住一个人，喝问道：“哪个潘明远？”\n\t　　这个路人被吓的战战兢兢，颤抖着说出了上将军的来历，让古天舒久久未语，竟真的是他那位故人。\n\t　　他与潘明远、许长青、杨志毅等人生死与共，两年前他火拼紫发道尊时，几人得悉后连夜疾驰数千里，从天下各地赶去援救，皆大口吐血，差点活活累死。\n\t　　最终那一战，古天舒靠自己的力量斩杀了紫发道尊，不过却也元气大伤，因此而在桃源村潜修了两年。\n\t　　“潘明远死了……”他一阵失神，而后化成一道流光冲向远处的将军府。\n\t　　“不要让刺客逃走！”一群兵丁追赶，且有强者通体发光在天空中飞行追击一个青衣人。\n\t　　古天舒冷哼，一步登天而上，黑发飞舞，脸色冰冷，背后铁剑铮铮而鸣，如一尊杀神一样挡在前方。\n\t　　青衣人似很吃惊，叫道：“天舒！”\n\t　　“长青大哥是你！”古天舒一呆，为什么会这样，昔日故友为何自相残杀？\n\t　　“走，我们去城外说。”许长青道，如一颗流星一样远去，身后追兵不能及。\n\t　　古天舒心中沉重，紧随其后出城，一路追了下去，当远去几十里，两人同时停了下来。\n\t　　“真的是你杀的？”\n\t　　“是我，是我杀了昔日共历生死的潘明远兄弟。”许长青眼中有泪水滚落。\n\t　　“为什么？”\n\t　　“因为他疯了，欲引北方草原铁骑南来，助大秦平定天下，这完全是引狼入室，毁我中原！”许长青大哭，他与潘明远是生死与共的兄弟，共患难，感情深，但是却亲手杀了他，有血泪滚落。\n\t　　潘明远是一个很果敢的人，见天下四分五裂，想早日平定，还百姓太平乐业，铤而走险，想借北方草原铁骑的力量。\n\t　　“他说已布下绝杀毒计，利用完草原铁骑，将他们全部坑杀在中原，既统一了天下，又绝了北方大患。可是，他却是在拿全天下做赌注，铁骑南下，谁能保证一切可控，我们百般劝说，他根本不听，要上书秦主向草原借兵。”\n\t　　……\n\t　　昔年，古天舒火拼紫发道尊时，潘明远第一个赶到，累的元气大伤，差点死在当场。\n\t　　而今，却再也不能相见了，他死在了故人的手中，古天舒一声长叹，皆是天下大乱之祸。\n\t　　“杀潘明远后，我亦不愿独生，但却不能这样死，我要去战场，若依然有铁骑南下，必以我血溅边境。”许长青毅然决然的道。\n\t　　“长青不要做傻事！”古天舒大喊。\n\t　　青衣猎猎，许长青远去，消失在天际尽头。\n\t　　古天舒一声叹息，得悉潘明远死去，有些心灰意冷，在一座荒山上建了一座草堂，又开始隐居。\n\t　　他吐纳练气，默诵黄庭，一心修行，一晃又过去了两年。\n\t　　他生平有两志，一愿平天下，二是望证道。\n\t　　天下大乱，群雄逐鹿，烽火连天，是为大势，若投身进去，不知何日才能脱身。\n\t　　修行之路，自古孤寂，无上宗师也没有迈出最后一步，总有死去的一天，他练气修身，希望有朝一日可以窥破生死奥秘，迈出前人不能走出的那一步。\n\t　　一晃两年过去了，这一日一声大呼打破了荒山的宁静，一个披头散发的人向山上跑来。\n\t　　“天舒你果然在此隐居……”这是一个虬须大汉，满身是血，似乎刚从战场回来，身上有不少伤痕。\n\t　　“志毅！”古天舒走出草堂，露出惊喜之色。潘明远、许长青、杨志毅、赵坤几人是昔日可以换命的故友。\n\t　　“草原铁骑南下，进入了秦、汉、齐三方战场，长青他……战死了！”杨志毅虎目中滚出泪水。\n\t　　潘明远虽然死了，但是大秦两年后终究还是引草原铁骑南下了，已进入三国交界处的战场，血水染红了大地，杀伐之气冲天。\n\t　　“天舒你天纵之资，可达到了宗师之境？草原国师莫勒来了，统率高手无数，无人可敌，专杀上将，长青就是死在了他的大弟子手中。”杨志毅道。\n\t　　“我与你去三方战场！”古天舒背负铁剑下山。\n\t　　三方战场，是一片染血的魔土，也不知死去了多少人，连土地都变成了血色，每到夜间鬼火幽幽。\n\t　　若是雨天，可见到地上淌的不是雨水，而猩红的血，这里阴气缭绕，常年笼罩魔云，森然慑人。\n\t　　大秦引草原铁骑南下，震惊天下，草原宗师莫勒无人可敌，杀中原高手无数。\n\t　　同在四大宗师内，迷幻海主人盖九幽欲出手，不想却被焚炎谷主戚苍所阻，无法进入三方战场。\n\t　　铁骑南侵，无人可挡莫勒，杀的天下高手尽变色。\n\t　　就在这个月夜，传来一声大吼：“我来杀莫勒！”\n\t　　神月当空，皎洁灿灿，月光洒满战场，却难以照散死亡阴气。\n\t　　“天缺道人已逝，戚苍不出，盖九幽老迈，还有谁能与我莫勒争锋？”北方草原国师是一个高大雄伟的老人，如一头老狮子一样，满脸虬须，身上流淌有神华。\n\t　　半个月来，消息传遍天下，有奇人将出世大战草原无上宗师，也不知有多少高手关注，来到了三方战场。\n\t　　夜月下，人影闪动，除却大军外，还有很多修士，尽在远观。\n\t　　“是我，古天舒！”夜月下，一个男子脚踏虚空而来，如水的月光洒落，将他映衬的如同一名谪仙一般。\n\t　　“年轻人不懂得珍惜生命。”莫勒也登天而上，浑身黄金神光璀璨绽放，让这个高大魁伟的老人看起来如同一尊战神一样。\n\t　　“莫勒，你若率铁骑离去，我转身就走，若不然今日取你项上人头，仗剑杀入草原！”古天舒话语铿锵，如剑铮铮剑鸣。\n\t　　“轰”\n\t　　一场惊天动地的大战爆发！\n\t　　剑气纵横，照亮了整片战场，白茫茫一片，气冲斗牛！\n\t　　莫勒魁伟，大开大合，双拳挥动，惊雷阵阵，电闪雷鸣，如海啸一样的声音发出。\n\t　　古天舒左拳右剑，气贯长虹，每一击都让天地震动一下，在两人间各种光华闪烁，像是要撕裂了虚空。\n\t　　这还是人力吗？所有人都不禁要这样问，两人的表现，几近神明！\n\t　　“轰！”\n\t　　最终，古天舒一剑劈出，勾动了一片遮空的云朵，降下万丈雷电，向莫勒劈去，震惊三方战场。\n\t　　“神迹，这是神迹啊！”\n\t　　人们忍不住惊呼，技几乎道，这超出了常人的理解。\n\t　　“砰”\n\t　　莫勒被万丈雷电劈中，但并没有化成飞灰，张嘴吐了几大口鲜血，浑身金光璀璨，淹灭了电芒。\n\t　　“轰”\n\t　　就在这一刻，他的手中亦发出一片刺目的光华，如一轮太阳在绽放，莫勒大喝道：“如此年轻的无上宗师古来罕见，让我以草原至宝战神戟送你上路！”\n\t　　在其手中有一杆战戟，沉重如山，像是要压塌虚空一般，戟杆乌黑，戟刃雪亮，带着阵阵血光，一看就是饮过无尽生灵之血的可怕武器。\n\t　　“哧”\n\t　　战神戟如有生命一样，在其手中颤抖，向天一击，射出一片可怕的血芒，一下子就震碎了天穹的云朵。\n\t　　而后，莫勒双手持战神戟立劈而下，斩向古天舒，威压惊慑九天十地！\n\t　　所有人都震撼，这果然是一杆属于神明的兵器，戟杆未变，依然是原来那么粗，持在莫勒手中。可是，前方的戟刃，却光芒刺目，化成了山岳一般高，劈杀了下来。\n\t　　凡人的力量怎么阻挡？那可是与山比高的一片雪亮的戟刃，吞吐出可怕的血光，骇人心神！\n\t　　“锵”\n\t　　古天舒横剑阻挡，以手中铁剑斩在了战神戟上。\n\t　　炫目的光芒爆发而出，像是有十轮太阳炸碎了，让所有人都睁不开眼睛。\n\t　　“喀嚓”\n\t　　最终，铁剑崩碎，战神戟完好无损，向下压来，隆隆而响，电神雷鸣，惊慑世间。\n\t　　“失去了铁剑，你还拿什么与我斗？”莫勒的声音冰冷无情，站在虚空中大喝。\n\t　　“只要我这个人还在就行，即便你手持神明的兵器亦无用。”古天舒踏月而进，道法自然，与天地相合，融为了一体。\n\t　　“杀！”莫勒大喝，手持战神戟又一次劈落下来，将天穹都震裂了，光华淹没了天地。\n\t　　古天舒避过这凌厉一击，而后踩着如山岳一样大的戟刃，落在戟杆上，如一尊神灵一样化成圣光扑杀向莫勒。\n\t　　“噗”\n\t　　一道血光出现，古天舒以手代剑，在莫勒的颈项上一划，一颗染血的头颅带着不甘与不相信的神色飞了出去，无头尸体喷血，坠落在三方战场中。\n\t　　明月夜下，古天舒天人合一，手持战神戟而立。\n\t　　遥远的北方大草原，一座古老的神庙中，腾起一道划破了古今未来的光芒，一尊巨大的神明虚影上抵九天下踏九幽，眸光冰冷，望向中原。\n\t　　同一时刻，中原也有数道不朽的神光冲上九霄，像是有几尊神明觉醒，透过虚空，遥望三方战场。\n\t　　古天舒身与天地大道相合，感应到了那几束不朽的光辉，他向前踏出了一步，像是要破碎虚空而去，道：“你们真的存在，也想介入人族的战争中吗？”\n\t　　短篇到这就结束了，明天上午开始正式上传《圣墟》的正文。',
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-6.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.18.0-6.0.pre at /Users/nevercode/dev/flutter_dev
    • Framework revision 84c84fb249 (31 hours ago), 2020-04-20 21:35:01 -0400
    • Engine revision 2bde4f0ae4
    • Dart version 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

 
[✓] Connected device (6 available)            
    • Redmi Note 7              • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554                            • android-x86    • Android 10 (API 29) (emulator)
    • Nevercode’s iPhone        • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.4.5
    • macOS                     • macOS                                    • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome                    • chrome                                   • web-javascript • Google Chrome 81.0.4044.122
    • Web Server                • web-server                               • web-javascript • Flutter Tools

• No issues found!
```

</details>

Closing as fixed.
Could everyone who still has this problem please file a new issue with complete minimal reproducible code sample and the output of `flutter doctor -v` please.
