### ISSUE TITLE
[web]: Clip Path not Work & the way to put log

### ISSUE THREAD

**Issue by tanamduit** [flutter/flutter#33029]
hi, i'm build some clip path with custom clipper to show background with half circle layout. But it just show white page. Also since print() is not working  and i try to break point but not wroking either, how i can write /  show a log. My flutter doctor : 

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-ID)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.34.0)
[✓] Connected device (1 available)
```

**Comment by ferhatb** [comment]
Hi tanamduit, 
Thanks for filing issue. Could you please share a snippet to repro.

Tried the following clipper and was not able to reproduce failure:

void main() => runApp(MaterialApp(
  home: MyApp(),
));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: ClipPath(
          clipBehavior: Clip.antiAlias,
          clipper: MyClipper(),
          child: Container(
            color: Colors.red,
            width: 200.0,
            height: 200.0,
          ),
        ),
      ),
    );
  }
}

class MyClipper extends CustomClipper<Path> {
  @override
  Path getClip(Size size) {
    final path = Path();
    path.addOval(Rect.fromLTRB(0, 0, size.width, size.height));
    path.close();
    return path;
  }

  @override
  bool shouldReclip(MyClipper oldClipper) => false;
}

**Comment by tanamduit** [comment]
hai @ferhatb  i already tried using your clipper sample  and its working. This is my custom clipper : 

```
@override
  Path getClip(Size size) {
    print(size.width.toString());
    print(size.height.toString());
   var path = Path();
    path.lineTo(0.0, size.height - 30);

    var firstControlPoint = Offset(size.width / 4, size.height);
    var firstPoint = Offset(size.width / 2, size.height);
    path.quadraticBezierTo(firstControlPoint.dx, firstControlPoint.dy,
        firstPoint.dx, firstPoint.dy);

    var secondControlPoint = Offset(size.width - (size.width / 4), size.height);
    var secondPoint = Offset(size.width, size.height - 30);
    path.quadraticBezierTo(secondControlPoint.dx, secondControlPoint.dy,
        secondPoint.dx, secondPoint.dy);

    path.lineTo(size.width, 0.0);
    path.close();

    return path;
  }
```
it will make half circle in bottom. But i think it's caught exception
