### ISSUE TITLE
Blinking cursor is not even 30fps?  Gallery > Components > Text Fields

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3302]
Add showPerformanceOverlay: true to the MaterialApp in app.dart to see.

![flutter_03](https://cloud.githubusercontent.com/assets/11857803/14507696/b9b3fc02-0178-11e6-927b-fd376d2b5ce9.png)

**Comment by eseidelGoogle** [comment]
FYI @mpcomplete @Hixie.  I haven't tried repaintRainbow, it's possible we're repainting the whole screen.

**Comment by abarth** [comment]
Looks like CPU scaling.

**Comment by abarth** [comment]
Confirmed that it's CPU scaling.  We have no trouble animating at 60 Hz while blinking the cursor.
