### ISSUE TITLE
Help me! Flutter run: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by VNAPNIC** [flutter/flutter#33034]
Help me!  Error "**Gradle task assembleDebug failed with exit code 1**"  when running Flutter: 

I tried **flutter doctor** and everything was fine:
![Capture](https://user-images.githubusercontent.com/7553452/58014771-c2930e80-7b23-11e9-9dbd-77ccc9afab82.PNG)
I tried every way such as: "FLutter Clean, Invalidate Caches / Restart " but everything is not working

![Capture2](https://user-images.githubusercontent.com/7553452/58015181-cb381480-7b24-11e9-8a79-751c80d7d68d.PNG)

**Comment by coastalgit** [comment]
Did you manage to find a solution to resolve this situation? I am experiencing the very same.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
