### ISSUE TITLE
[proposal] Show Dart version in "Flutter SDK releases"

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#33032]
I could not find this in search, so asking here.
I have a problem with the current 'stable' channel Dart SDK version and want to try the more recent flutter dev builds.
Before I start spending time on that I need to check if the dev build Dart SDK is the version where my problem was already fixed (namely 2.3.1-dev.0.0).
Where can I see which version of the Dart SDK is included in each flutter dev build?
E.g. Flutter v1.6.0 - Dart 2.3.0, etc?

**Comment by iapicca** [comment]
HI @duzenko 
I believe this is the information you are looking for https://flutter.dev/docs/development/tools/sdk/releases
Closing the issue now,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by duzenko** [comment]
I disagree. Please reopen. In the future, please ask first and close after confirmation.

**Comment by duzenko** [comment]
PLEASE REOPEN

**Comment by duzenko** [comment]
@iapicca 
@flutter

**Comment by iapicca** [comment]
Hi @duzenko 
what information you find missing in the documentation?
Thank you

> I disagree. Please reopen. In the future, please ask first and close after confirmation.
I cannot promise you that

**Comment by duzenko** [comment]
> 
> 
> Hi @duzenko
> what information you find missing in the documentation?

Not sure how you can miss this reading the original post.
I want to see what dart SDK version is included in each individual flutter release

**Comment by darshankawar** [comment]
@duzenko 
Revisiting this issue, if you check the flutter sdk release documentation: https://docs.flutter.dev/development/tools/sdk/releases?tab=macos

Here, it shows the version along with Dart version as below:

<img width="918" alt="Screenshot 2023-02-09 at 5 37 59 PM" src="https://user-images.githubusercontent.com/67046386/217809061-6eebc4f7-98f9-4ace-92de-0017658ef42b.png">

Does this help to answer your proposal ?
