### ISSUE TITLE
Grid should handle delegates that can't always determine their dimensions

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3303]
For example, consider a Grid delegate that can't handle infinite widths (e.g. because it determines its size based on the width constraint). It might assert that the width is not null. If it does so, then the grid itself should catch that, and if we're in the `RenderObject.debugCheckingIntrinsics` mode we should silently return null and if we're not we should catch that and explain that the error happened in the delegate while doing intrinsic calculations (or whatever).

cc @vlidholt

**Comment by YeungKC** [comment]
Could you please provide a minimum recurrence code?

cc @Hixie

**Comment by Hixie** [comment]
I can't figure out a situation where this would actually happen these days where we don't already provide sufficient feedback.
