### ISSUE TITLE
中美的贸易问题是否会影响到flutter未来的发展 (Will Sino-US trade issues affect the future development of flutter?)

### ISSUE THREAD

**Issue by fillfive** [flutter/flutter#33039]
谷歌此次的贴近美国政府的要求，对GMS使用提出了限制，未来美国政府如果要求Google更大范围的遵照政府意愿，是否会影响安卓的发展，是否会影响到开发者？

**Comment by ffey** [comment]
Google's proximity to the U.S. government has imposed restrictions on the use of GMS, ln future , If U.S. governments ask Google to comply more with the Government's wishes. is it will  influence the development of Android and influence the  Android's developers?

**Comment by Hi99simon** [comment]
probably yes

**Comment by excitedhaha** [comment]
我觉得对华为的海外市场影响很大，但是对安卓的发展应该没什么影响，Google只是不允许华为使用Google全家桶，更谈不上对Flutter的影响了。
I think it will hurt HUAWEI in markets outside China a lot, but the impact on Android may be small Because Google only restrict HUAWEI from using Google Apps, so not to mention the impact on Flutter

**Comment by appdev** [comment]
同关注， @excitedhaha  只是不允许华为使用Google服务，跟禁止使用Android听起来似乎有很大区别，但是实际上，海外Android用户没有Google服务谁会用？

目前比较关注，会不会以后某天美国政府要求Google执行更严格的禁令（以目前的情况来开，极有可能），会不会对多有中国手机厂家执行这个禁令，届时使用中国大陆自己开发的系统（秋季发布）不支持flutter，亦或者是Google禁止flutter运行在中国自己开发的系统上。

**Comment by BondarenkoStas** [comment]
@fillfive This is definitely not an issue with flutter sdk itself. Please see https://flutter.dev/community for support options.
