### ISSUE TITLE
Hero overlaps positioned

### ISSUE THREAD

**Issue by EugenePisotsky** [flutter/flutter#33045]
Hi,

I have a hero, and route with positioned panel. Problem is that hero overlaps positioned block during animation, when I navigate to that route. Is there a way to avoid it? Maybe an attribute similar to zIndex?

![IMG_5991](https://user-images.githubusercontent.com/5047628/58028979-5bc22500-7b24-11e9-92ed-4eef9adf37dd.PNG)
![IMG_5992](https://user-images.githubusercontent.com/5047628/58028981-5bc22500-7b24-11e9-89e6-cdbe763581e9.PNG)

**Comment by VladyslavBondarenko** [comment]
Hi @EugenePisotsky
I see there's an open issue addressing the case you described.
Please follow up on #31408  I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
