### ISSUE TITLE
Issue with flutter and google maps widgets

### ISSUE THREAD

**Issue by jorisT57** [flutter/flutter#33047]
Hello everybody,
I'm really novice in flutter and i encounter an issue with google maps widget. I tried to follow the tutorial of medium: https://medium.com/flutter-io/google-maps-and-flutter-cfb330f9a245

Unfortunately, when i'm running the app i have a blank image. 
![Screenshot_2019-05-20-16-16-43-834_com example maps_google](https://user-images.githubusercontent.com/47141553/58029477-f9195b00-7b1c-11e9-911d-37d1e060865c.png)

Does somebody have ever encountered this problem ? Do you have a suggestion in which direction i can try to investigate?

Thanks in advance,

Regards

**Comment by Rihyx** [comment]
Same for me.

**Comment by BondarenkoStas** [comment]
Is it the same while using current flutter stable and google_maps_flutter 0.5.21+7? I'm afraid that the article wasn't updated since March.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
