### ISSUE TITLE
TextField autofill for common user properties taken from iOS

### ISSUE THREAD

**Issue by agordeev** [flutter/flutter#33040]
## Use case

Autofill values that can be automatically retrieved from iOS.

## Proposal

It'd be great to add a new property to `TextField`/`TextFormField` that will allow to control over iOS' `textContentType` field. For example it is handy to auto fill the user's name, email or phone number.

More info:

https://developer.apple.com/documentation/uikit/uitextcontenttype
https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_a_text_input_view

**Comment by justinmc** [comment]
I thought that Flutter might already do this via `keyboardType`, but it looks like `textContentType`.  This would probably mean adding a field to CupertinoTextField, passing it through to the engine, and then setting `textContentType` in the engine.  That's doable and I think this is a very good feature to have.

There may be something equivalent to do for Android too.

**Comment by aaronraimist** [comment]
Related: https://github.com/flutter/flutter/issues/13015

**Comment by Evsio0n** [comment]
#https://github.com/flutter/engine/pull/13878

**Comment by Evsio0n** [comment]
I have a suggestion of add TextContent.username this properity to let iOS to know that this is a filed of Username (beacuse password textcontenttype already known by ios secure text entry.)

**Comment by justinmc** [comment]
I'm going to close this to focus all autofill discussion on https://github.com/flutter/flutter/issues/13015.  @Evsio0n your PR is still being mentioned over there.
