### ISSUE TITLE
How to resolve “pub upgrade failed (1)” in flutter-web (hummingbird)?

### ISSUE THREAD

**Issue by dev-akshat** [flutter/flutter#33052]
I am trying to create my first flutter-web project? when I run command "flutter packages upgrade" its giving me an error :

flutter packages upgrade

F:\Project\VSCode\progress>flutter packages upgrade Could not find a file named "packages/flutter_web/pubspec.yaml" in https://github.com/flutter/flutter_web 7a4c33425ddd78c54aba07d86f3f9a4a0051769b. Running "flutter packages upgrade" in progress... pub upgrade failed (1)

I am using latest version of everything.

**Comment by mezojm10** [comment]
I'm having the same problem

**Comment by tianyu704** [comment]
me too

**Comment by walker-walks** [comment]
I created my project using VSCode's plugin and I'm having same problem.
I use macOS 10.14
```terminal
Dart VM version: 2.3.2 (Tue Jun 11 15:29:47 2019 +0200) on "macos_x64"
```
```terminal
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (7 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```

**Comment by clia** [comment]
flutter pub get
Could not find a file named "packages/flutter_web/pubspec.yaml" in https://github.com/flutter/flutter_web 1ed4317aa91038ba99531037ce00c04672c4bee1.
Running "flutter packages get" in example...                            
pub get failed (1)

**Comment by KingBright** [comment]
I have met the same issue.

> platform flutter pub upgrade          
> Could not find a file named "packages/flutter_web/pubspec.yaml" in https://github.com/flutter/flutter_web 2fefa8c7315c32191aa10ef0ef03afb565e99701.
> Running "flutter pub upgrade" in platform...                            
> pub upgrade failed (1)

**Comment by SarahAbou** [comment]
SAME PROBLEM ! Pleaaaase any help ????
