### ISSUE TITLE
Issue from website page 编写您的第一个 Flutter App

### ISSUE THREAD

**Issue by chao9267** [flutter/flutter#33055]
From URL: https://www.flutterchina.club/get-started/codelab/index.md

使用 english_words: ^3.1.0   然后Packages get失败  本人使用的是windows   Android Studio   请问该如何解决？
报错 column 18 of pubspec.yaml: Mapping values are not allowed here. Did you miss a colon earlier?

**Comment by ffey** [comment]
Did you miss a colon earlier？ english_words: ^3.1.0  提示你是否漏掉了冒号？
你可以贴出你的pubspec.yaml文件中引入english_words的代码？

**Comment by stuartmorgan** [comment]
This is a community website not maintained by the Flutter team. Try https://github.com/flutterchina/website/issues
