### ISSUE TITLE
Refactor FlutterMain.java in the Android embedder

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#33054]
For context: https://github.com/flutter/engine/pull/8979

Suggested changes:
1. Create a wrapper/auto-factory for the name of the AOT blobs and remove the static fields.
2. Consider removing the resource extractor since the AOT blobs will be contained in the native lib directory. (Remove case for `mExtractTask = null`) . Confirm if this is still needed for the debug/profile variants.
3. Not related to the refactor, but figure out how to add some basic unit tests.

**Comment by pedromassangocode** [comment]
Is this still a valid issue? Not sure how to verify that this was fixed.

**Comment by reidbaker** [comment]
We are not sure this is still a relevant set of actions to take nor if they were relevant what those actions would be.
