### ISSUE TITLE
Update engine artifacts for Android

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#33059]
These are the current Engine artifacts for Android:

```
├── android-arm
│   └── flutter.jar
├── android-arm-profile
│   ├── darwin-x64
│   │   └── gen_snapshot
│   └── flutter.jar
├── android-arm-release
│   ├── darwin-x64
│   │   └── gen_snapshot
│   └── flutter.jar
├── android-arm64
│   └── flutter.jar
├── android-arm64-profile
│   ├── darwin-x64
│   │   └── gen_snapshot
│   └── flutter.jar
├── android-arm64-release
│   ├── darwin-x64
│   │   └── gen_snapshot
│   └── flutter.jar
├── android-x64
│   ├── flutter.jar
│   └── libflutter.so
├── android-x86
│   ├── flutter.jar
│   └── libflutter.so
```

Once Flutter starts generating 32 and 64 bits in app bundles, these artifacts are better structured this way:

```
├── android
│   └── flutter.jar    // <-- io.flutter .class
├── android-arm-release
│   ├── darwin-x64
│   │   └── gen_snapshot
│   └── libflutter.so
├── android-arm64
│   └── libflutter.so
├── android-arm64-profile
│   ├── darwin-x64
│   │   └── gen_snapshot
│   └── libflutter.so
├── android-arm64-release
│   ├── darwin-x64
│   │   └── gen_snapshot
│   └── libflutter.so
├── android-x64
│   └── libflutter.so
├── android-x86
│   └── libflutter.so
```

Note that `libflutter.so` is already outside `flutter.jar` in `x64` and `x86`.  

This change will:
* Reduce the size of the artifacts downloaded from Google CDN. 
* Simplify the Gradle build script and potentially make the build faster.

**Comment by blasten** [comment]
Actually, this new layout may increase the size of the artifacts by `28M`.   `(663M -> 691M)`

**Comment by blasten** [comment]
Actually, this new structure may increase the size of the artifacts by `28M`.   `(663M -> 691M)`

**Comment by jason-simmons** [comment]
The engine Java build scripts generate a `BuildConfig.java` file containing flags indicating whether this is a debug, profile, or release build.  Some embedder Java code is conditional on these flags.

So we would need to ship different `flutter.jar` binaries for debug, profile, and release.  

Some options:
  * Use the current format where each target platform has its own `flutter.jar` which includes `libflutter.so`.  If the APK needs to support multiple ABIs, then extract the `libflutter.so` binaries for the other ABIs from those platforms' `flutter.jar` files.
  * Ship separate versions of `flutter.jar` containing only Java code for debug, profile, and release.  Alongside each `flutter.jar`, provide `libflutter.so` binaries for each supported target platform.   The `libflutter.so` files could be packaged inside JARs that place them within that platform's `lib/$ABI` path.

**Comment by blasten** [comment]
Thanks for the background @jason-simmons. This is helpful! 

> Use the current format where each target platform has its own flutter.jar which includes libflutter.so. If the APK needs to support multiple ABIs, then extract the libflutter.so binaries for the other ABIs from those platforms' flutter.jar files.

This is the implementation after my changes.

On a side note, do you know why `libflutter.so` is duplicated in `x64` & `x86` (it's in `flutter.jar` and also outside)? https://github.com/flutter/flutter/blob/90f38907d70481970046652c61565f896f40595b/packages/flutter_tools/gradle/flutter.gradle#L211-L221 

Also, it doesn't seem like like `android-x64/flutter.jar` or  `android-x86/flutter.jar` is ever used.

**Comment by jason-simmons** [comment]
I think we were distributing `libflutter.so` artifacts for all platforms in the early days of Flutter before `flutter.jar` existed.

The `libflutter.so` artifacts were removed after the migration to `flutter.jar` on most platforms.  But they had to be kept around for x86/x64 because the Gradle script was using them to create ARM/x86/x64 APKs in debug mode.

**Comment by hnvn** [comment]
This update would resolve this [issue](https://github.com/flutter/flutter/issues/9253), doesn't it? Currently, I cannot run my (released) Flutter app in x86 devices. This issue is known and still stays there for a long time.

**Comment by blasten** [comment]
cc @tvolkert @xster @matthew-carroll

**Comment by blasten** [comment]
@jason-simmons suggested:

> Ship separate versions of flutter.jar containing only Java code for debug, profile, and release. Alongside each flutter.jar, provide libflutter.so binaries for each supported target platform. The libflutter.so files could be packaged inside JARs that place them within that platform's lib/$ABI path.

**Comment by blasten** [comment]
Gradle now consumes Flutter Maven artifacts, so this issue isn't relevant at this point.
