### ISSUE TITLE
Tests hang if they have an import error

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3305]
e.g. if you haven't run pub get, so package imports fail, "flutter test" just hangs forever.

**Comment by eseidelGoogle** [comment]
Is https://github.com/flutter/flutter/issues/2182 the answer?  Not sure what the plan to solve this is.

**Comment by Hixie** [comment]
yeah this is probably a dupe of that one

**Comment by eseidelGoogle** [comment]
Dupe of #2182
