### ISSUE TITLE
Harmonize FlutterPlugin on Android and iOS

### ISSUE THREAD

**Issue by xster** [flutter/flutter#33071]
Specifically, on Android, you get a callback param when attached which has an observable to get lifecycle events from. 

On iOS, the plugin always gets all lifecycle events pushed to it directly.

We should reconcile the APIs. Ideally, move the iOS side closer to the Android pattern.

**Comment by gaaclarke** [comment]
I did an audit of the current iOS API for comparison:

![iOS API](https://user-images.githubusercontent.com/30870216/60373776-4e674880-99b6-11e9-9767-ee0e3d82ef84.png)

**Comment by gaaclarke** [comment]
I looked at the lifecycle events for iOS and Android.  Here is how iOS does it:
![iOS Plugin Lifecycle](https://user-images.githubusercontent.com/30870216/61333027-9ec60f00-a7da-11e9-9492-f096e4bf2441.png)

Here is how Android will do it:
![Android Plugin Lifecycle](https://user-images.githubusercontent.com/30870216/61333057-ac7b9480-a7da-11e9-9122-51b7838ba072.png)

We already have published iOS plugins that match this interface like this: 
https://github.com/flutterapp/flutter_facebook/blob/7e5b45104614ee239cbf611ab63cbdfd4e28e6af/ios/Classes/FlutterFacebookPlugin.m#L21

I recommend we don't break the current plugins by maintaining the reflection that is used to send messages to FlutterPlugins.  One problem with the current iOS API is that it requires the use of a FlutterAppDelegate.  Are we going to require that of our add-to-app clients?  That might be an opportunity to make the subscription model like android work without the FlutterAppDelegate.

**Comment by xster** [comment]
I think forcing people to tweak their AppDelegate (they don't have to subclass FlutterAppDelegate but they still need to pass all the app delegate callbacks to Flutter https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#write-code-to-use-flutterviewcontroller-from-your-host-app) is going to be a big issue https://github.com/flutter/flutter/issues/32995. 

We should figure out a way to let people do it in a more incremental / modular way.

**Comment by gaaclarke** [comment]
For example the FlutterFacebookPlugin could look like this:
```
+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar>*)registrar {
  FlutterMethodChannel* channel = [FlutterMethodChannel
      methodChannelWithName:@"flutter_facebook"
            binaryMessenger:[registrar messenger]];
  FlutterFacebookPlugin* instance = [[FlutterFacebookPlugin alloc] init];
  [registrar addMethodCallDelegate:instance channel:channel];
  [[NSNotificationCenter defaultCenter] 
      addObserver:self 
      selector:@selector(applicationDidBecomeActive:)
      name:UIApplicationDidBecomeActiveNotification 
      object:nil];
}
```

If we encourage this it is more idiomatic to what iOS developers would expect and would remove the need for FlutterAppDelegate.

**Comment by xster** [comment]
+1000! I'd love to update the templates/instructions for new plugin developers to do this as soon as possible. And we can migrate the g3/first party plugins. 

cc @amirh 

We were saying we could make this not break for full-app and FlutterAppDelegate users. We just need some way for add-to-app normal AppDelegate users to discover whether the plugins they're using would subtly break or if they need to pass things into a FlutterPluginAppLifeCycleDelegate. 

This could potentially just be a Dart package that just reads through your pubspec and prints out which plugins are 'old' plugins.
