### ISSUE TITLE
Update the "Building an APK" page

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3307]
We might not need this page anymore: https://flutter.io/building-apk/

However, assuming we're keeping this page for now... I'm not sure this instruction is still accurate/required (it happens automatically, yes?): "Run android update sdk from the command line, and install SDK version 22 and build tools version 22.0.1. For now, Flutter currently expects only these versions."

**Comment by sethladd** [comment]
cc @devoncarew on if we still need to manually run "android update sdk"

cc @qchong would you be sad if we removed this page?

**Comment by devoncarew** [comment]
We don't need that step, just for the user to have installed an android sdk. Our current setup instructions cover that I think. And we no longer require those exact versions now.

**Comment by sethladd** [comment]
Thanks for the confirmation! I'm leaning towards removing this page and drafting up a flutter tool overview page.

**Comment by eseidelGoogle** [comment]
`flutter run` will install and apk for you every time the engine changes (but not when your dart changes).

If you want to have a "Walk away from your computer" copy, you'll want `flutter build apk; flutter install`

**Comment by qchong** [comment]
+1 on replacing with a 'Flutter Tools overview' dev guide.

On Wed, Apr 13, 2016 at 1:49 PM, Eric Seidel <notifications@github.com>
wrote:

> flutter run will install and apk for you every time the engine changes
> (but not when your dart changes).
>
> If you want to have a "Walk away from your computer" copy, you'll want flutter
> build apk; flutter install
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/flutter/flutter/issues/3307#issuecomment-209641896>
>



-- 

Quddus Chong | Technical Writer - Turquoise | quddusc@google.com
