### ISSUE TITLE
Switch to using the Skia vended Minikin alternative.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#33085]
libTXT uses a forked version of Minikin for text shaping. Skia has a drop in replacement for this that passes all unit-tests in the [`txt_unittests` target](https://github.com/flutter/engine/blob/3d2e9b24aa712ba60206e7ac392a709df0939635/third_party/txt/BUILD.gn#L164). This replacement should be added behind a runtime flag to test viability as a replacement for Minikin.

A [benchmark harness for libTXT](https://github.com/flutter/engine/blob/3d2e9b24aa712ba60206e7ac392a709df0939635/third_party/txt/BUILD.gn#L212) is also available and the same benchmarks can be run using the Minikin replacement to check performance.

We have previously used [similar runtime flags](https://github.com/flutter/engine/pull/4779/files) when we initially switched away from the Blink based text shaping library to libTXT.

**Comment by chinmaygarde** [comment]
cc @jason-simmons @GaryQian

**Comment by chinmaygarde** [comment]
cc @drwulf and @rusino

**Comment by GaryQian** [comment]
This is done via `--enable-skshaper` gn flag

**Comment by chinmaygarde** [comment]
Let's wait on closing this issue till the feature is not gated behind a flag.

**Comment by GaryQian** [comment]
Let's continue to track this in https://github.com/flutter/flutter/issues/39420 which is more of a general effort to complete the switch.
