### ISSUE TITLE
GrContext::performDeferredCleanup needs to be called on the IO context.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#33087]
Base on guidance from @brianosman, simply dropping the reference to an object on a thread with an OpenGL context is not sufficient to actually collect the GL handle. GrContext::performDeferredCleanup must also be called periodically. We already seem to be doing this on the [main GPU thread context](https://github.com/flutter/flutter/issues/24160) but not the IO thread context.

**Comment by dnfield** [comment]
This was done in https://github.com/flutter/engine/pull/14265
