### ISSUE TITLE
podhelper.rb depends on flutter_application_path being magical

### ISSUE THREAD

**Issue by xster** [flutter/flutter#33094]
Make it non-magical

Related https://github.com/flutter/flutter/issues/32994

**Comment by xster** [comment]
@jmagman would be nice to address this simultaneously too

**Comment by xster** [comment]
I think this means that you happened to have set it in the 'parent' script in https://github.com/flutter/flutter/pull/36793/files#diff-a6f9a84f8e880e4d2d6051b4f045cb75R3 but that variable being present isn't being read as a global in podhelper.rb right? (it's passed in explicitly in install_flutter_* etc)

**Comment by jmagman** [comment]
flutter_application_path isn't global, and is not required to be set at all.  I just used it to DRY out the `load` and `install_all_flutter_pods` lines.
You could do:
```ruby
load './flutterapp/.ios/Flutter/podhelper.rb'
target 'MyApp' do
  install_all_flutter_pods('flutterapp')
end
```

**Comment by xster** [comment]
SG, thanks!
