### ISSUE TITLE
Reconcile Android/iOS on usage of a builder when creating activity/vc

### ISSUE THREAD

**Issue by xster** [flutter/flutter#33098]

**Comment by xster** [comment]
On Android, starting an activity with a new engine has a builder (NewEngineIntentBuilder)
https://github.com/flutter/engine/blob/101e03c1c8417267c20fb9f448a8efb80ec2c328/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java#L223 to specify the initial route (dart entrypoint was recently removed out of security concerns wrt android intents)

On Android, starting an engine has arguments (DartEntrypoint) https://github.com/flutter/engine/blob/101e03c1c8417267c20fb9f448a8efb80ec2c328/shell/platform/android/io/flutter/embedding/engine/dart/DartExecutor.java#L256 to specify the VM entrypoint function and the path to the dart bundle. 

On iOS, starting a VC has arguments to specify the bundle (https://github.com/flutter/engine/blob/101e03c1c8417267c20fb9f448a8efb80ec2c328/shell/platform/darwin/ios/framework/Headers/FlutterViewController.h#L69) for the Flutter library and nib. 

On iOS, starting the engine has arguments to specify the bundle for the Flutter library https://github.com/flutter/engine/blob/101e03c1c8417267c20fb9f448a8efb80ec2c328/shell/platform/darwin/ios/framework/Headers/FlutterEngine.h#L80.

We should be consistent about options provided when starting Flutter. 

Ideally, in all cases, we should be able to provide the Flutter library location, the entrypoint and the initial route (with Android activity starting via Intent being one exception)

**Comment by xster** [comment]
cc @gaaclarke, we just talked about this in person.

**Comment by xster** [comment]
This doesn't solve the general platform channel timing issue such as https://github.com/flutter/flutter/issues/38914 but it would solve a lot of initial route specific timing issues, especially on iOS such as https://github.com/flutter/flutter/issues/27882, https://github.com/flutter/flutter/issues/27216.

**Comment by matthew-carroll** [comment]
@gaaclarke do you think you've made all the changes that you want to make for this issue? Or are you still investigating API refactors?

**Comment by gaaclarke** [comment]
I have nothing in the works.  I gave up on [FlutterEngineBuilder](https://docs.google.com/document/d/1dgp4EnMy-t3fpbZmNEzYaomLReNw715tUu8JOAZHXw4/edit).  I'm open to any other ideas, I've been focusing my energy elsewhere.

**Comment by matthew-carroll** [comment]
Similar to the other ticket, let's see if we can come up with a definition of done for this ticket on Thursday. If the answer is "won't do" then we can close it on Thursday. If there is something we should do, let's see if we can define it and then we can prioritize its delivery.
