### ISSUE TITLE
[firebase_crashlytics] document opt-in

### ISSUE THREAD

**Issue by pbaker5** [flutter/flutter#33095]
The [Android Crashlytics documentation](https://firebase.google.com/docs/crashlytics/customize-crash-reports?authuser=0&platform=android) says to enable collection via "Fabric.with(this, new Crashlytics());", but the Flutter plugin's FirebaseCrashlyticsPlugin.registerWith method does this. Does this mean opting out is currently not possible?

**Comment by kroikie** [comment]
@pbaker5

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1143. Any further collaboration will be done there.
