### ISSUE TITLE
Clean up new Android embedding logcat

### ISSUE THREAD

**Issue by xster** [flutter/flutter#33102]
It's too verbose presently

**Comment by matthew-carroll** [comment]
The answer to this is to create our own Log proxy with a flag based on debug mode. There may already be a ticket for this.

**Comment by xster** [comment]
Basing it on the Flutter module's flavor/debug-ness would be a neat solution.

**Comment by matthew-carroll** [comment]
FYI - for anything related to the Android embedding, can you add it to the Platform Embedding Refactor project? I added this one.

**Comment by xster** [comment]
Ah alright

**Comment by xster** [comment]
For posterity, this is https://github.com/flutter/engine/pull/9351
