### ISSUE TITLE
Create add-to-app embedding integration test

### ISSUE THREAD

**Issue by xster** [flutter/flutter#33107]
There are already some in https://github.com/flutter/flutter/issues/24117

Ideally move to engine PRs

**Comment by jmagman** [comment]
> A partial easy work around as Jenn suggested could just be to transmit the bytes as a plugin if we can't figure out something more direct.

I think this was commented in the wrong issue.

**Comment by jmagman** [comment]
Is this new integration test enough to cover this issue? 
https://github.com/flutter/flutter/pull/39945
