### ISSUE TITLE
webview fails silently when https:// not explicitly stated in url

### ISSUE THREAD

**Issue by xster** [flutter/flutter#33105]

**Comment by TahaTesser** [comment]
Related to [#27560](https://github.com/flutter/flutter/issues/27560)

**Comment by stuartmorgan** [comment]
We should probably fix this at the API level by requiring a `Uri` rather than a string; guessing URL intent from invalid URLs is not a good path to go down.

**Comment by stuartmorgan** [comment]
Closing as fixed; we're now using `Uri` rather than `String` for URLs.
