### ISSUE TITLE
GridView image disappear after some scrolling but ListView work fine

### ISSUE THREAD

**Issue by chunhunghan** [flutter/flutter#33114]
1. Use GridView to display images taken from Camera in real device Galaxy J7 Pro 
   after some scrolling, some images disappear
2. Use another page to display with ListView works fine in the same time
3. Trying to reduce image size did not work
4. Emulator works fine
5. May related to issue https://github.com/flutter/flutter/issues/17152 or https://github.com/flutter/flutter/issues/32143

Thank you for your amazing work.

		import 'package:flutter/material.dart';
		import 'dart:async';
		import 'dart:io';
		import 'dart:convert';
		import 'dart:typed_data';
		import 'package:image_picker/image_picker.dart';
		import 'package:fab12a_template/viewmodels/app_model.dart';
		import 'package:image/image.dart' as imageProcessor;

		class TakePhotoPage extends StatefulWidget {
		  AppModel appModel;

		  TakePhotoPage({Key key, this.appModel}) : super(key: key);

		  @override
		  _TakePhotoPageState createState() => _TakePhotoPageState();
		}

		class _TakePhotoPageState extends State<TakePhotoPage> //with AutomaticKeepAliveClientMixin<TakePhotoPage>
		{
		  //File _image;
		  //List<File> _imageList = [];
		  //List<Uint8List> _imageList = [];

		  Future getImage() async {
			var image = await ImagePicker.pickImage(source: ImageSource.camera);
			var bytes = image.readAsBytesSync();
			
			var imageJpg = imageProcessor.decodeJpg(bytes);
			var thumbnailJpg = imageProcessor.copyResize(imageJpg, width: 120);
			var thumbnailPng = Uint8List.fromList(imageProcessor.encodePng(thumbnailJpg));

			setState(() {
			  //_image = image;
			  //_imageList.add(image);
			  //_imageList.add(bytes);
			  widget.appModel.addImageList(bytes);
			  widget.appModel.addThumbnailList(thumbnailPng);
			});
		  }

		  @override
		  Widget build(BuildContext context) {
			print('image count ${widget.appModel.imageList.length}');
			return Scaffold(
			  appBar: AppBar(
				title: Text('Photo Album'),
			  ),
			  body: widget.appModel.imageList.length <= 1
				  ? Center(
					  child: widget.appModel.imageList.length == 0
						  ? Column(
							  mainAxisAlignment: MainAxisAlignment.center,
							  //crossAxisAlignment: CrossAxisAlignment.center,
							  children: <Widget>[
								Image.asset(
								  'assets/images/no-image.png',
								),
								//Text('No Image Available')
							  ],
							)
						  : FadeInImage(
							  placeholder: AssetImage('assets/images/photo-512.png'),
							  image: MemoryImage(widget.appModel.imageList[0]), //FileImage(_imageList[0]),
							  fit: BoxFit.fill,
							),
					)
				  : Container(
					  child: GridView.builder(
						shrinkWrap: true,
						itemCount: widget.appModel.thumbnailList.length,
						gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
							crossAxisCount: 2),
						itemBuilder: (BuildContext context, int index) {
						  //if (index < 50)
						  return Container(
							padding: EdgeInsets.all(2.0),
							child: Center(
							  child: GridTile(
								  footer: Text(
									'footer $index',
									textAlign: TextAlign.center,
									style:
										TextStyle(color: Colors.white.withOpacity(1.0)),
								  ),
								  header: Text(
									'header $index',
									textAlign: TextAlign.center,
									style:
										TextStyle(color: Colors.white.withOpacity(1.0)),
								  ),
								  child: FadeInImage(
									placeholder:
										AssetImage('assets/images/photo-512.png'),
									image: MemoryImage(widget.appModel.thumbnailList[index]), //FileImage(_imageList[index]),
									fit: BoxFit.fill,
								  )),
							),
							color: Colors.blue[200],
							margin: EdgeInsets.all(1.0),
						  );
						},
					  ),
					),
			  floatingActionButton: FloatingActionButton(
				onPressed: getImage,
				tooltip: 'Take photo',
				child: Icon(Icons.add_a_photo),
			  ),
			);
		  }

		  //@override
		  //bool get wantKeepAlive => true;
		}

## Logs

```
```

```
```

	[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.475], locale zh-TW)
		• Flutter version 1.5.4-hotfix.2 at C:\flutter
		• Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
		• Engine revision 52c7a1e849
		• Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

	[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
		• Android SDK at C:\Users\00016986\AppData\Local\Android\sdk
		• Android NDK location not configured (optional; useful for native profiling support)
		• Platform android-Q, build-tools 28.0.3
		• ANDROID_HOME = C:\Users\00016986\AppData\Local\Android\sdk
		• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
		• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
		• All Android licenses accepted.

	[√] Android Studio (version 3.4)
		• Android Studio at C:\Program Files\Android\Android Studio
		• Flutter plugin version 35.3.1
		• Dart plugin version 183.6270
		• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

	[√] IntelliJ IDEA Community Edition (version 2018.3)
		• IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.6
		• Flutter plugin version 31.3.4
		• Dart plugin version 183.4886.3

	[√] VS Code, 64-bit edition (version 1.34.0)
		• VS Code at C:\Program Files\Microsoft VS Code
		• Flutter extension version 2.25.1

	[√] Connected device (1 available)
		• Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

	• No issues found!

**Comment by Andrios-Dong** [comment]
I have the same question.And I found that the release apk or the arm64 does'nt have the issue. I doubt that the different flutter.jar or libflutter.so casue the problem

**Comment by 00SunnyDay00** [comment]
We have the same problem. Does anyone can offer a solution?

**Comment by windows7lake** [comment]
The same am I.

**Comment by a371166028** [comment]
+1

**Comment by elaith9** [comment]
+1

**Comment by starlitya** [comment]
Hi Sir, please help to check this issue.

**Comment by criswonder** [comment]
I encounter the same issue!

**Comment by a371166028** [comment]
打个release包就好了，debug包才会这样

**Comment by a371166028** [comment]
有人能明白我说的吗？？？

**Comment by jingjiewei** [comment]
> 有人能明白我说的吗？？？

我能。

As @a371166028 said, this issue will not happen in release apk

**Comment by chunhunghan** [comment]
Close this issue since release apk do not have this problem. Thank you for your kind help.

**Comment by tylorvan** [comment]
anyone knows why the issue only happen in debug mode?
