### ISSUE TITLE
[Feature Request] support “onContinuousPress” GestureDetectore

### ISSUE THREAD

**Issue by ShaiDemri** [flutter/flutter#33110]
## Use case
Add a new property to [GestureDetector](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html) 
"onContinuousPress" that will receive a (Function, Duration) and it will execute the function repeatedly once every duration as long as the finger (or the mouse click etc...) is in contact with the button and stop executing the given function once the finger is off the button. 

Right now this behaviour is achieved using combination of "onTapDown" and "onTapUp" 
it will be nice to have this feature as a built in one.

**Comment by ShaiDemri** [comment]
Right now, this behaviour can be implemented by combining 2 separate properties of the [GestureDetector](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html), as follow:
`var _timer;

  void _startTimer(Function func, {int dealy = 100}) {
    _timer = Timer.periodic(Duration(milliseconds: dealy), (_) => func());
  }

  void _stopTimer() {
    _timer.cancel();
  }


GestureDetector(
    child: Container(
            child: Icon(
                Icons.arrow_downward,
                ),
            ),
    onTapDown: (details) => _startTimer(_refToFunc, dealy: 50),
    onTapUp: (details) => _stopTimer(),
);`

**Comment by ShaiDemri** [comment]
Right now, this behaviour can be implemented by combining 2 separate properties of the [GestureDetector](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html), as follow:
```
var _timer;

void _startTimer(Function func, {int dealy = 100}) {
timer = Timer.periodic(Duration(milliseconds: dealy), () => func());
}

void _stopTimer() {
_timer.cancel();
}

GestureDetector(
child: Container(
child: Icon(
Icons.arrow_downward,
),
),
onTapDown: (details) => _startTimer(_refToFunc, dealy: 50),
onTapUp: (details) => _stopTimer(),
); 
```
But still I think this a common use case that needs to be built in to Flutter.

**Comment by dkwingsmt** [comment]
It seems to me that this feature can be implemented with your approach with decent amount of code. It would take a great amount of demand to convince us to imbed this into the core framework. 
I'm closing this issue. Feel free to follow up or reopen if necessary.
