### ISSUE TITLE
trouble running flutter after migrating to androidx

### ISSUE THREAD

**Issue by glennmichaelmejias** [flutter/flutter#33115]
Hello, I am having trouble running flutter
I execute this
`flutter run -v`

`[  +24 ms] executing: [/home/glenn/development/flutter/] git log -n 1 --pretty=format:%H
[  +26 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] d5aae54a28a2ba04f5737752edba9f5c98259c6c
[        ] executing: [/home/glenn/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +16 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.6.0-68-gd5aae54a2
[  +11 ms] executing: [/home/glenn/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/glenn/development/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +40 ms] executing: [/home/glenn/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +30 ms] executing: /home/glenn/Android/Sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /home/glenn/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           J8AXB760U099CH2        device usb:2-2 product:WW_X00TD model:ASUS_X00TDB device:ASUS_X00T_4 transport_id:2
[  +18 ms] executing: /home/glenn/development/flutter/bin/cache/artifacts/fuchsia/tools/dev_finder list -full
[   +3 ms] Invalid argument(s): Cannot find executable for /home/glenn/development/flutter/bin/cache/artifacts/fuchsia/tools/dev_finder.
[   +5 ms] /home/glenn/Android/Sdk/platform-tools/adb -s J8AXB760U099CH2 shell getprop
[ +112 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +74 ms] Found plugin firebase_auth at /home/glenn/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/
[   +3 ms] Found plugin firebase_core at /home/glenn/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.5+1/
[   +6 ms] Found plugin flutter_facebook_login at /home/glenn/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_login-1.2.0/
[  +14 ms] Found plugin image_cropper at /home/glenn/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.0.1/
[   +3 ms] Found plugin image_picker at /home/glenn/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.0+4/
[   +6 ms] Found plugin path_provider at /home/glenn/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-0.5.0+1/
[  +65 ms] Found plugin firebase_auth at /home/glenn/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/
[   +1 ms] Found plugin firebase_core at /home/glenn/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.5+1/
[   +5 ms] Found plugin flutter_facebook_login at /home/glenn/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_login-1.2.0/
[  +10 ms] Found plugin image_cropper at /home/glenn/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.0.1/
[   +1 ms] Found plugin image_picker at /home/glenn/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.0+4/
[   +4 ms] Found plugin path_provider at /home/glenn/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-0.5.0+1/
[  +57 ms] ro.hardware = qcom
[  +34 ms] Launching lib/main.dart on ASUS X00TDB in debug mode...
[  +11 ms] Initializing gradle...
[  +14 ms] Using gradle from /home/glenn/Desktop/flutterprojects/petsbook/android/gradlew.
[ +189 ms] executing: /home/glenn/Desktop/flutterprojects/petsbook/android/gradlew -v
[ +456 ms] 
                    ------------------------------------------------------------
                    Gradle 5.1.1
                    ------------------------------------------------------------

                    Build time:   2019-01-10 23:05:02 UTC
                    Revision:     3c9abb645fb83932c44e8610642393ad62116807

                    Kotlin DSL:   1.1.1
                    Kotlin:       1.3.11
                    Groovy:       2.5.4
                    Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b16-5323222)
                    OS:           Linux 4.15.0-50-generic amd64
[   +8 ms] Initializing gradle... (completed in 0.7s)
[        ] Resolving dependencies...
[        ] executing: [/home/glenn/Desktop/flutterprojects/petsbook/android/] /home/glenn/Desktop/flutterprojects/petsbook/android/gradlew app:properties
[ +711 ms] 
                    > Configure project :app
                    registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
                    registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
                    registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
                    registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
                    registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
[   +2 ms] Resolving dependencies... (completed in 0.7s)
[   +2 ms] * Error running Gradle:
           ProcessException: Process "/home/glenn/Desktop/flutterprojects/petsbook/android/gradlew" exited abnormally:
           
           > Configure project :app
           registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
           registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
           registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
           registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
           registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
             Command: /home/glenn/Desktop/flutterprojects/petsbook/android/gradlew app:properties
           
[   +3 ms] "flutter run" took 1,886ms.
[        ] "flutter run" took 1,886ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:154:7)
<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:107:34)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:101:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:154:23)
<asynchronous suspension>
#5      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:46:32)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:345:56)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:430:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#16     Future._complete (dart:async/future_impl.dart:473:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#20     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#27     Future._complete (dart:async/future_impl.dart:473:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)`

**Comment by miDeb** [comment]
Are you on master?

**Comment by glennmichaelmejias** [comment]
@miDeb what is that mean?

**Comment by glennmichaelmejias** [comment]
ayway i fix it already. thanks.

**Comment by BrjieshDevstree** [comment]
Hello @glennmichaelmejias,
I got the same error could you plz tell me how you resolve this?
