### ISSUE TITLE
Hitting enter when searching in the docs should go to the top suggestion.  Right now does nothing.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#3311]
## Steps to Reproduce

Please tell us what you were doing and what went wrong.

## Flutter Doctor

Paste the output of running `flutter doctor` here.

## Logs and Crash Reports

Please attach any relevent logs or crash reports.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by sethladd** [comment]
Moved over to https://github.com/dart-lang/dartdoc/issues/1149
