### ISSUE TITLE
support of Bamakan (bam) language in localization

### ISSUE THREAD

**Issue by munjata** [flutter/flutter#33125]
## Proposal
I am currently developing with Flutter an App that need to support localization.
The app target mainly the N'ko community, the only writing system they can use is (N'KO script).
I can provide all necessary translations.
Language to be supported: [Bamanakan](https://en.wikipedia.org/wiki/Bambara_language).
Writing system: [N'KO](https://en.wikipedia.org/wiki/N%27Ko_script) (RTL).

**Comment by timsneath** [comment]
Hi Munjata, we've worked with others in the past to provide community-supported translations. Here are examples for [Galician](https://github.com/flutter/flutter/pull/27352/files) and [Kazakh](https://github.com/flutter/flutter/pull/31578/files), which you might be able to use as a template for your own work.

**Comment by munjata** [comment]
Thanks for this quick reply, I will have a look at the examples and I come back.

**Comment by HansMuller** [comment]
Updated advice about adding support for a new language to the material library has been added to Flutter's i18n tutorial: 
https://flutter.dev/docs/development/accessibility-and-localization/internationalization#adding-support-for-a-new-language

It's going to need one more update to account for the Cupertino library localizations, which only landed in  last week or so.

**Comment by HansMuller** [comment]
At the moment, Google doesn't provide translations for Bamanakan and we don't have a mechanism in place for supporting user-contributed translations. The list of translations we do support is see https://api.flutter.dev/flutter/flutter_localizations/GlobalMaterialLocalizations-class.html.

It's possible to add support for a new language in an app, see https://flutter.dev/docs/development/accessibility-and-localization/internationalization#adding-support-for-a-new-language.

I'm going to close this issue.
