### ISSUE TITLE
Flutter web - "The Flutter SDK is not available " 

### ISSUE THREAD

**Issue by SystemTce** [flutter/flutter#33122]
`
environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  intl: ^0.15.7
  flutter:
    sdk: flutter
  firebase_dynamic_links: ^0.4.0
  firebase_core: ^0.4.0
  url_launcher: ^4.2.0
`
1. flutter packages get
2. webdev serve

[error](https://s2.ax1x.com/2019/05/21/VSRsOI.png)

why?

**Comment by kevmoo** [comment]
Try running `flutter pub global run webdev serve`

Make sure you're following along with the instructions [here](https://github.com/flutter/flutter_web)

**Comment by kevmoo** [comment]
Closing out. Please comment if you hit this again!

**Comment by eladcandroid** [comment]
Just delete pubspec.lock file and run get packages again... works for me
