### ISSUE TITLE
flutter web can't use "url_launcher"

### ISSUE THREAD

**Issue by SystemTce** [flutter/flutter#33126]
flutter web can't use "url_launcher"

**Comment by sleeyax** [comment]
I came up with a temporary solution to this problem using the [universal_html](https://pub.dev/packages/universal_htm) and [universal_io](https://pub.dev/packages/universal_io) packages:

```
import 'package:universal_html/prefer_universal/html.dart' as html;
import 'package:universal_io/prefer_universal/io.dart';
import 'package:url_launcher/url_launcher.dart';

void _openUrl(String url) async {
    // flutter web
    if (kIsWeb) {
      html.document.window.location.href = url;
    }
    // android or ios
    else if (Platform.isAndroid || Platform.isIOS) {
      if (await canLaunch(url)) {
        await launch(url);
      }else {
        throw 'Could not launch $url';
      }
    } 
    // unknown platform
    else {
      throw new Exception('Unsupported platform');
    }
}
```
Tested and working on flutter for web and android.

**Comment by jonasbark** [comment]
@sleeyax you can also use `window.open(url, 'Link');` to open the URL in a new tab.

**Comment by maheshmnj** [comment]
you can use the javascript method open to launch an url I tried it works perfectly

**Comment by hterkelsen** [comment]
`url_launcher` is supported on Flutter Web, you can find instructions on how to use it here: https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher_web

**Comment by xpat** [comment]
I'm using Flutter v1.13.6. I can't get this to work, not by hot restarting, not by rebuilding the project, not by reopening Android Studio. In pubspec.yaml, with just the dependency url_launcher_web, flutter pub get exits without an error.  With just url_launcher or that dependency with url_launcher_web, it throws an error.  In main.dart, there's a red underline in the import package:url_launcher/_url_launcher.dart';  "Target of URI doesn't exist"

**Comment by NebulaFox** [comment]
Currently on Flutter 1.19.0-4.3pre and building a flutter we app. `url_launcher` never returns  from ` await launch(url)` following the example code in `url_launcher`. Used the `dart:js` solution above to work around this.
