### ISSUE TITLE
How i do to programmer notification with the custom date?

### ISSUE THREAD

**Issue by LukeDaniel16** [flutter/flutter#33124]
Currently, exist some method for create "Reminders"? Example: the user goes by a date and in this date digited one reminder will be dispared? Being created totally by user and being remind in this date future estimated. Similar made as a alarm.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
