### ISSUE TITLE
PVRTC compression and decompression code license is missing in generated LICENSE file

### ISSUE THREAD

**Issue by alexei-sintotski** [flutter/flutter#33127]
I am using Flutter version v1.5.4-hotfix.2.

The LICENSE asset generated by Flutter build (build/app/intermediates/flutter/release/flutter_assets/LICENSE) includes license of PVRTC:

===============================================================================

The PVRTC compression and decompression code is ported from Jeffrey Lam's
PvrTcCompressor:

https://bitbucket.org/jthlim/pvrtccompressor

===============================================================================

There are two issues with this generated output:

1. The name of the author is incorrect -- should be Jeffrey Lim.
2. The full body of the license (https://bitbucket.org/jthlim/pvrtccompressor/src/default/LICENSE.TXT) is missing.

**Comment by jason-simmons** [comment]
Looks like this license comes from the `image` package, not from Flutter itself.

See https://pub.dev/packages/image and https://github.com/brendan-duncan/image/blob/master/LICENSE

**Comment by spkersten** [comment]
@filiph Could you mark this with "customer: solaris"?

**Comment by alexei-sintotski** [comment]
@jason-simmons Thanks! Could you please confirm flutter does not have direct dependency on it? I am going to contact the _image_ owner in the meantime.

**Comment by alexei-sintotski** [comment]
https://github.com/brendan-duncan/image/issues/121

**Comment by brendan-duncan** [comment]
Thanks for catching that. I updated the license file.

**Comment by remonh87** [comment]
It is now part of the Flutter licenses so this ticket can be closed
