### ISSUE TITLE
A Flex (Column/Row) like widget for slivers

### ISSUE THREAD

**Issue by spkersten** [flutter/flutter#33137]
Having a widget like `Column` for slivers would be useful. For example for applying the same amount of padding to a heading and a list. Or for allowing abstractions to be created, e.g., a widget for a screen with a SliverAppBar plus some sliver footer and a sliver body as parameter.

Example:
```dart
CustomScrollView(
  slivers: [
    SliverAppBar(/* ... */),
    SliverPadding(
      padding: EdgeInsets.symmetric(horizontal: 16),
      sliver: SliverGroup(
        slivers: [
          SliverToBoxAdapter(child: Text("Items)),
          SliverList(/* many items */)
        ]
      )
    )
  ]
)
```

**Comment by BondarenkoStas** [comment]
@spkersten I read the https://github.com/flutter/flutter/pull/33138#issuecomment-501467980, do you think the issue should stay open?

**Comment by Piinks** [comment]
Let's leave this open. I'm working on something similar that will address this and #16854 with potentially SliverFlex, SliverGroup, SliverExpanded, and SliverSpacer as well as updates to SliverPersistentHeaders etc. :)

**Comment by jamesblasco** [comment]
The progress you did it is awesome! Thanks @Piinks 💙💙.
I have been playing around with my custom RenderSliverSection and I would be happy to help with this.
What are the main points that are holding this back?

**Comment by Kavantix** [comment]
I released a package yesterday that includes a MultiSliver (essentially solving this issue)
https://pub.dev/packages/sliver_tools

It does however not include any Flex like functionality since IMO that needs to be solved differently for slivers.

Any feedback/suggestions would be appreciated

**Comment by naamapps** [comment]
Any news on this? 
Theres a lot to improve in the slivers department.
SliverCenter, SliverRow, SliverColumn, SliverSizedBox. 
These are just examples of slivers I think are needed inside the framework.
Thanks

**Comment by DenisBarzanov** [comment]
Yes, very much needed, thanks

**Comment by Piinks** [comment]
https://github.com/flutter/flutter/issues/56756#issuecomment-1331497145 linking for reference.

**Comment by thkim1011** [comment]
Hey everyone, I wrote up a [design doc](https://docs.google.com/document/d/1e2bdLSYV_Dq2h8aHpF8mda67aOmZocPiMyjCcTTZhTg/edit?usp=sharing&resourcekey=0-Xj2X2XA3CAFae22Sv3hAiA) for grouping Slivers into a single Sliver. I'd appreciate any opinions people might have!
