### ISSUE TITLE
Reconcile VM initialization between Android and iOS

### ISSUE THREAD

**Issue by xster** [flutter/flutter#33145]
Currently, iOS can initialize with a `FlutterEngine.init()` whereas Android initializes with `FlutterMain.startInitialization()`, `FlutterMain.ensureInitializationComplete()`, then `FlutterEngine()`.

**Comment by xster** [comment]
@dnfield @matthew-carroll in case you have more historical context. Otherwise, I'll go do some digging.

**Comment by matthew-carroll** [comment]
`FlutterEngine`s are independent objects in Android. I wouldn't want to have arbitrary global behavior in them. That said, I do take issue with the name `FlutterMain` and I think it has too many responsibilities. So refactoring `FlutterMain` would be a good thing in general.

**Comment by xster** [comment]
@dnfield was there a FlutterMain equivalent on iOS?

**Comment by dnfield** [comment]
No, I don't think so.  It's harder to draw comparisons because of the JNI boundaries.  Afaik FlutterMain is more about JNI initialization

**Comment by matthew-carroll** [comment]
Isn't FlutterMain mostly about locating and loading the SO?

**Comment by xster** [comment]
I'm going to fold the FlutterMain into the FlutterEngine. 

The slight unfortunate thing is that the FlutterEngine constructor creates JNI which crashes without the FlutterMain calls and a costly object construction is unintuitive but I'll do some gymnastics around it before I merge them.

**Comment by matthew-carroll** [comment]
@xster please give me a chance to review any such changes before merging.

**Comment by xster** [comment]
ya, I didn't make the PR yet

**Comment by matthew-carroll** [comment]
I merged in @xster's work on this last week. Closing this issue.
