### ISSUE TITLE
google_maps_flutter: using GoogleMap widget with Hero widget causes hard crash

### ISSUE THREAD

**Issue by brandon-irl** [flutter/flutter#33153]
### StackTrace

> D/AndroidRuntime(31473): Shutting down VM
> E/AndroidRuntime(31473): FATAL EXCEPTION: main
> E/AndroidRuntime(31473): Process: dev.brandonalexander.startup_namer, PID: 31473
> E/AndroidRuntime(31473): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.Display.getDisplayId()' on a null object reference
> E/AndroidRuntime(31473): 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3774)
> E/AndroidRuntime(31473): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime(31473): 	at android.os.Looper.loop(Looper.java:164)
> E/AndroidRuntime(31473): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
> E/AndroidRuntime(31473): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(31473): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> E/AndroidRuntime(31473): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

### Environment
LG Nexus5X Android 8.1.0

### Steps to Reproduce
Run sample app below

### Sample App
```
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(HeroApp());

class HeroApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Transition Demo',
      home: MainScreen(),
    );
  }
}

class MainScreen extends StatelessWidget {
  final _googleplex = new CameraPosition(
    target: LatLng(37.421512, -122.084101),
    zoom: 12.0,
  );
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Main Screen'),
      ),
      body: Hero(
        tag: 'mapHero',
        child: GoogleMap(
          initialCameraPosition: _googleplex,
          onTap: (latLng) {
            Navigator.push(context, MaterialPageRoute(builder: (_) {
              return DetailScreen(_googleplex);
            }));
          },
        ),
      ),
    );
  }
}

class DetailScreen extends StatelessWidget {
  DetailScreen(this._position);
  final _position;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Detail Screen'),
      ),
      body: Hero(
        tag: 'mapHero',
        child: GoogleMap(
          initialCameraPosition: _position,
        ),
      ),
    );
  }
}

```

**Comment by BondarenkoStas** [comment]
@brandon-irl Do you still experience the issue with current flutter stable and google_maps_flutter 0.5.21+7?  I see issues with the same error but without updates https://github.com/flutter/flutter/issues/35071
https://github.com/flutter/flutter/issues/38597

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
