### ISSUE TITLE
Hi, CheckMediaAccessPermission: Not supported. in WEBVIEW

### ISSUE THREAD

**Issue by enfraly** [flutter/flutter#33150]
I'm trying to access the camera or microphone from a webview but it was impossible

**Comment by enfraly** [comment]
Run webview_Flutter app for example with url : "https://test.webrtc.org/"

**Comment by BondarenkoStas** [comment]
@enfraly Could you provide a code example that reproduces the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
