### ISSUE TITLE
Issue from website page 入门: 在macOS上搭建Flutter开发环境 (Building the Flutter Development Environment on macOS)

### ISSUE THREAD

**Issue by Sxiaobai** [flutter/flutter#33158]
while running flutter doctor  I'm getting -bash: /Users/XXX/flutter/bin/flutter: Permission denied

**Comment by Sxiaobai** [comment]
Mac OS Mojave 10.14.4

**Comment by SuhwanCha** [comment]
I'm using macOS Mojave 10.14.4 but `$flutter doctor` works.
I've installed flutter in `~/Documents/flutter` and used environment variables.
For example, `declare -x PWD="/Users/suhwan/Documents/flutter"`

**Comment by BondarenkoStas** [comment]
@Sxiaobai did you manage to get it working? Did you try to change permissions on the flutter folder?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
