### ISSUE TITLE
Update flutter create templates and flutter repo to use new Android embedding

### ISSUE THREAD

**Issue by xster** [flutter/flutter#33161]

**Comment by xster** [comment]
Also migrate embedding usage code that is already materialized in the Flutter repo such as devicelab tests and examples/ etc

**Comment by xster** [comment]
should we leave this issue open for defaulting this flag to on?

**Comment by blasten** [comment]
@xster I filed https://github.com/flutter/flutter/issues/43638

**Comment by xster** [comment]
Thanks. I added that to our spreadsheet
