### ISSUE TITLE
PlatformView crash on ios on rotate and back

### ISSUE THREAD

**Issue by Dawnthorn** [flutter/flutter#33165]
## Steps to Reproduce

```
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Rotate Bug',
      home: MyHomePage(),
      routes: <String, WidgetBuilder> {
        '/sub-page': (BuildContext context) => SubPage(),
      }
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
            title: Text('Rotate Bug'),
        ),
        body: GoogleMap(
            initialCameraPosition: CameraPosition(
                target: LatLng(37.42796133580664, -122.085749655962),
                zoom: 8.0,
            ),
        ),
        bottomNavigationBar: MaterialButton(
            child: Text('Sub Page'),
            onPressed: () => Navigator.of(context).pushNamed('/sub-page'),
        ),
    );
  }
}

class SubPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
            title: const Text('Sub Page'),
        ),
        body: Text('content'),
    );
  }
}
```
Besides the above code, I also added io.flutter.embedded_views_preview to ios/Runner/Info.plist, added  [GMSServices provideAPIKey:@"YOUR KEY HERE"]; with a working API key for Google Maps to ios/Runner/AppDelegate.m, and added google_maps_flutter: ^0.5.13 to dependencies in pubspec.yml.

1. Run the above program on a real device. I've not been able to reproduce in the emulator.
2. Click on the "Sub Page" button at the bottom.
3. Rotate the device to landscape mode.
4. Click on the platform button. At this point you'll see the visual bug in #30130 .
5. Now start rotating the phone back and forth. It can take like 30 or 40 rotations. Sometimes I repeat steps 2-4 again. I can get it to crash consistently though.

## Logs

Here's the standard files and also a stack trace from lldb in Xcode where the crash happens. 

[flutter-run-verbose.log](https://github.com/flutter/flutter/files/3205643/flutter-run-verbose.log)
[flutter-analyze.log](https://github.com/flutter/flutter/files/3205648/flutter-analyze.log)
[flutter-doctor.log](https://github.com/flutter/flutter/files/3205651/flutter-doctor.log)
[rotate-bug-stack-trace.log](https://github.com/flutter/flutter/files/3205652/rotate-bug-stack-trace.log)

**Comment by manmetplok** [comment]
Maybe this is also related to #31152

**Comment by BondarenkoStas** [comment]
@Dawnthorn do you experience it still? Can you try it while using current flutter stable and google_maps_flutter 0.5.21+7?

**Comment by Dawnthorn** [comment]
I'm afraid not. I rebuilt the above program with 0.5.21+7 and flutter 1.9.1+hotfix.4 and I'm getting the same result. The same visual bug (#30130) and the same crash. I'm including a stack trace of the crash from this new build.

[rotate-bug-0.5.21-stack-trace.log](https://github.com/flutter/flutter/files/3775240/rotate-bug-0.5.21-stack-trace.log)

**Comment by darshankawar** [comment]
@Dawnthorn 
I verified this issue on iOS device (iphone 6s, OS 14.4.1) and on master version using latest plugin version and following the steps to replicate you mentioned, didn't lead me to the crash as you mentioned, although I am not sure what does step # 4 `Click on the platform button. ` mean from your code sample, wherein, running the sample shows me only `content` text using which I replicated all the steps, as below:


https://user-images.githubusercontent.com/67046386/115870343-c42a8700-a45c-11eb-98c7-d878755ed454.MP4



Can you confirm using latest master / stable and plugin [version](https://pub.dev/packages/google_maps_flutter/install) if you still see the crash ?

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.2.0-11.0.pre.187, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.2.0-11.0.pre.187 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5526dcc24b (2 days ago), 2021-04-20 22:34:02 -0700
    • Engine revision 610fd039ae
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
   • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.85

! Doctor found issues in 1 category.

```

</details>

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
