### ISSUE TITLE
flutter_driver should have some pre-canned scroll and fling behavior

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3316]
Ideally these pre-canned scrolls/flings should be more representative of what humans do.

Right now we're just copy/pasting some very artificial scrolls:
https://github.com/flutter/flutter/pull/3313#discussion_r59630268

FYI @yjbanov @HansMuller

**Comment by yjbanov** [comment]
While the numbers that have been going around our initial tests are not supported by any serious science, they are somewhat empirical in that I chose them by looking at what happens on the UI while running the test. The scrolling, for example, looked more or less like what would happen if I scrolled manually.

**Comment by Hixie** [comment]
It's not clear to me that what we do today is actually problematic. Closing until we have customer feedback to the contrary.
