### ISSUE TITLE
Reported issues find in pubspec.yaml

### ISSUE THREAD

**Issue by majakozar** [flutter/flutter#33172]
Hi All,

I'm using Flutter for some time now and I just notice that crash report for issues in pubspec.yaml are strange. 

I accidentally add additional - in assets so instead of  "- assets/logo.png" I got "- - assets/logo.png".

In Console I got the message "Gradle task assembleDebug failed with exit code 1" when I open the crash report file I got the error "_CastError: type 'YamlList' is not a subtype of type 'String' in type cast".

My suggestion is to write this error in a little more details. I spent more than a day to fix the issue.

Thanks,
Maja

**Comment by christopherfujino** [comment]
Thank you for filing this. I agree that experiencing a `_CastError` while the tool is parsing pubspec.yaml is a bad experience. However, I am going to close this general issue as when we see this in crash logging we generally fix these when we see them. If you experience this again, feel free to file with a specific stacktrace.
