### ISSUE TITLE
flutter_driver could have less boilerplate

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3317]
Context: https://github.com/flutter/flutter/pull/3313

If we had a driver_test instead of test (from package:test) we could pass in the driver, and save the setup and teardown:

```dart
    setUpAll(() async {
      driver = await FlutterDriver.connect();
    });

    tearDownAll(() async {
      if (driver != null)
        driver.close();
    });
```

Similarly instead of manually saving the summary the driver_test could do that for us:

```dart
      new TimelineSummary.summarize(timeline)
        ..writeSummaryToFile('home_scroll_perf', pretty: true)
        ..writeTimelineToFile('home_scroll_perf', pretty: true);
```

FYI @yjbanov.  Feel free to close if this is too non-specific or covered by other things.

**Comment by yjbanov** [comment]
Definitely agree that we need these utilities. What blocks this is lack of ability to pass command-line arguments into the test environment (which is also why we have issues with hard-coded observatory ports).

Also, similarly we could have

```dart
testWidget('MyWidget', (WidgetTester tester) {
  tester.blah();
});
```

Rather than today's:

```dart
test('MyWidget', () {
  testWidgets((WidgetTester tester) {
    tester.blah();
  });
});
```

**Comment by sethladd** [comment]
> What blocks this is lack of ability to pass command-line arguments into the test environment

Let's chat with the authors of test, maybe we can file a feature request.

**Comment by eseidelGoogle** [comment]
FYI @nex3 (no action required, just in case you're curious).

**Comment by nex3** [comment]
We generally discourage wrapping the `test()` function, since it means you won't get any new named arguments that are added in the future.

For the driver, you can use the new [`addTearDown()`](http://blog.sass-lang.com/posts/809572-sass-35-release-candidate) function to clean up that logic:

```dart
Future<FlutterDriver> driverForTest() async {
  var driver = await FlutterDriver.connect();
  addTearDown(() => driver.close());
  return driver;
}

test("some driver test", () async {
  var driver = await driverForTest();
  // ...
}
```

**Comment by Hixie** [comment]
@yjbanov If we're going to do this, we should do this in the next year. Otherwise we should close it.

**Comment by yjbanov** [comment]
There haven't been a lot of upvotes for this issue, so I'm not sure how useful it would be. We've actually been trending in the opposite direction lately, namely adding ability to talk to _multiple_ `FlutterDriver` instances simultaneously in one test. So I'm not sure how some test environment could pass the driver to the test, if it doesn't know how many drivers the test wants to talk to.

As for saving the timeline automatically, it might be too specific, given the diversity of tests: jank, memory usage, start-up time, integration testing, hardware matrix testing. Timeline is pretty much only useful for jank.

**Comment by jonahwilliams** [comment]
Based on the current usage of flutter driver, a change like this would likely be massively breaking. I do not think we should consider it, so I'm closing the issue
