### ISSUE TITLE
Describe hairline in BorderSide.width API docs

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#33189]
### Flutter version

```
[✓] Flutter (Channel master, v1.6.1-pre.47, on Mac OS X 10.13.6 17G4015, locale en-CN)
```

### Complete Runnable Code

```dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "test",
      theme: ThemeData(primarySwatch: Colors.blueGrey),
      home: MyWidget()
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
      ),
      backgroundColor: Colors.white,
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          _buildTabBar(0.1),
          _buildTabBar(0.0),
        ],
      ),
    );
  }

  Widget _buildTabBar(double width) {
    return CupertinoTabBar(
      backgroundColor: Colors.white,
      items: [BottomNavigationBarItem(icon: Icon(Icons.home)), BottomNavigationBarItem(icon: Icon(Icons.home))],
      border: Border(top: BorderSide(color: Colors.black, width: width, style: BorderStyle.solid))
    );
  }
}
```

### Screenshot

![flutter_08](https://user-images.githubusercontent.com/1555508/58182100-9623f180-7cdf-11e9-856b-2f9da59ae1aa.png)

### Description

From the code and screenshot, you can see that width 0.0 BorderSide has a even thicker border than the width 0.1 BorderSide.

Expected: The width 0.0 BorderSide should be gone completely (not visible at all). 

I am designing a theme and let user change the width of BorderSide, when the user changes it to 0.0, this problem occurs. 

Thanks a lot.

**Comment by shihaohong** [comment]
Hi @sgon00, 

To set it such that you don't have a border, you need to set the style to `BorderStyle.none`. Setting the width to 0.0 has the special meaning of setting the border to be a hairline border. 

If you look at the [Skia docs](https://skia.org/user/api/SkPaint_Reference), hairline is defined draw "the thinnest continuous frame."

We could add a description to the border width docs to further clarify what hairline means.

**Comment by sgon00** [comment]
@shihaohong Thank you very much for the quick reply and explanation. Got it, even though I still don't understand why it's designed like this (make life harder to deal with 0.0 width customization). Anyway, I will need to code the special case when a user inputs 0.0 width then. Closing this issue and Thanks a lot again.

**Comment by shihaohong** [comment]
Yeah, no worries! I'm going to leave this open just so that we can use it to track the API doc update that I made. I'll close it once the PR is merged.
