### ISSUE TITLE
It is too easy to accidentally press 't' when performing a hot reload

### ISSUE THREAD

**Issue by edex96** [flutter/flutter#33184]
Using Flutter from cli and trying to hot reload is hard because the 't' key is so close to the 'r' and accidently pressing on it results cli to try to print the widget tree and since this process is a long one every press end with frustratingly waiting like 2 mins every single time. And I couldn't find any info about this on how to disable it. Please add this as a feature or show me a way to avoid this.

**Comment by M001T** [comment]
Fixed ?

**Comment by edex96** [comment]
@Tree 's answer is seems to be correct but I haven't tried because It seems messy
https://stackoverflow.com/questions/56726247/how-to-disable-widget-tree-printing-in-flutter-cli-pressing-t-key-accidently

**Comment by M001T** [comment]
> @Tree 's answer is seems to be correct but I haven't tried because It seems messy
> https://stackoverflow.com/questions/56726247/how-to-disable-widget-tree-printing-in-flutter-cli-pressing-t-key-accidently

That Works!, Thanks for Help

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/49143
