### ISSUE TITLE
change the color of unfocused text field icon

### ISSUE THREAD

**Issue by Saifallak** [flutter/flutter#33183]
## Use case

Theming TextField unfouced icon color through themeData.

## Proposal

i'm trying to use ThemeData to change the app colors at any moment, also it's easier to manage app when it's colors are contained in one single file like CSS does

what flutter can do? make the icon take the color of unselectedWidgetColor of themeData , i think it's the corrected color instead of hard Coded grey color

for more info about this request, you can check this[ stackoverflow ](https://stackoverflow.com/questions/56237544/change-unfocused-text-field-icon-color-through-app-themedata)as i though it's already implemented but it wasn't , they told me some workarounds , but i think it's easy to be implemented isn't it ?

**Comment by Saifallak** [comment]
@HansMuller already asked on StackOverFlow but i think it should be implemented in Flutter in ThemeData like other widgets

**Comment by monisnap-julien** [comment]
Any update on this topic ? Still very hard to modify Textfield style...

**Comment by nxcco** [comment]
Any news on this?

**Comment by edex96** [comment]
Its hard coded
you can't use theme to override this color
but you can manage the icon's color state yourself
its not elegant but hey we developers are bombarded with so many obstacles everyday this should not upset us right.. right..
crying intensifies..

**flutter/packages/flutter/lib/src/material/input_decorator.dart**

``` dart
Color _getDefaultIconColor(ThemeData themeData) {
    if (!decoration!.enabled && !isFocused)
      return themeData.disabledColor;

    switch (themeData.brightness) {
      case Brightness.dark:
        return Colors.white70;
      case Brightness.light:
        return Colors.black45;
    }
  }
```

**Comment by JamesMcIntosh** [comment]
I can see two sensible expected behaviors:
- Icon color is the same whether focused or not
- Icon color is different when not focused

Material design doesn't have any clear specification about icon colors in text fields.
https://material.io/components/text-fields

If it's sensible to use the existing theme then `hintColor` or `themeData.colorScheme.primary` are good candidates (suggestions welcome).

My suggestion would be to replace:
```
final Color iconColor = isFocused ? activeColor : _getDefaultIconColor(themeData);

Color _getDefaultIconColor(ThemeData themeData) {
...
}
```
With:
```
final Color iconColor = _getIconColor(themeData);

Color _getIconColor(ThemeData themeData) {
  if (!decoration!.enabled && !isFocused) {
    return themeData.disabledColor;
  }

  if (isFocused) {
    return themeData.colorScheme.primary;
  }

  return themeData.hintColor;
}
```

**Comment by kamrancr7** [comment]
Any update on this??

**Comment by HansMuller** [comment]
This request has been resolved. See the last two examples on https://api.flutter.dev/flutter/material/InputDecoration-class.html
