### ISSUE TITLE
issue with embedding static and dynamic packages in iOS using flutter

### ISSUE THREAD

**Issue by srinivasuk** [flutter/flutter#33192]
Our pod file contains

use_frameworks! 

pod install fails when above property is set. if it is commented it installs fine but breaks our our code where there are dynamic packages.

**Comment by BondarenkoStas** [comment]
@srinivasuk is it still an issue? do you try to add flutter to an existing app? Adding Flutter to an existing app is experimental and only available on the master channel.

**Comment by srinivasuk** [comment]
We tried few months back and struggled a lot integrating with existing IOS
app

We are able to integrate without firebase, but when we tried to integrate
with firebase we got pod issue. We don't know if it is flutter issue or
firebase issue.

So finally we kept flutter project on hold because of this issue.

If issue is resolved we can try it again.


Thanks

**Comment by BondarenkoStas** [comment]
@srinivasuk Now it's hard to know what was the exact issue, it would be cool if you try and if it fails, then provide your flutter doctor -v output, pubspec.yaml, error logs.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
