### ISSUE TITLE
Gallery, Scrollable tabs doesn't scroll on swipes that "go off the device"

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3319]
Comparing to the behavior of "Google News", swiping horizontally between their categories.

In the gallery, scrollable tabs, I've noticed that if I start my scroll from about 1/3 of the way over from the edge of the device, and slowly/normally swipe to the left and then off the device, the tab doesn't animate fully and doesn't fully transition to the next tab.

Instead I see the tab follow my finger, but as the finger swipes off the device, the tab animates back into place.

I can show you in person :)

**Comment by sethladd** [comment]
Not sure this is a bug, but I think there are differences. Would like to investigate more with @HansMuller to help determine what's happening.

**Comment by HansMuller** [comment]
The Google News app's scrolling tabs are definitely much more sensitive to low fling velocities than ours.  It's easy to increase our sensitivity by reducing the value of  _kMinFlingVelocity in material/tabs.dart.

**Comment by sethladd** [comment]
New patch feels good!
