### ISSUE TITLE
[Help] Is that correct to wrap hardcoded padding Widgets inside a Container to adjust their hardcoded paddings?

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#33199]
Hi, I found there are many widgets hardcoded with some paddings in the code. For example, RaisedButton, IconButton, BottomNavigationBar etc...

Since their paddings are hardcoded, I can not adjust them with their properties. Instead, I found I can wrap them inside a Container/SizedBox and then change height/width of the Container/SizedBox to adjust their hardcoded paddings. I saw many people did the same way in StackOverflow too. So far it works very well in my apps on both android and iOS devices and I don't find any problems yet. 

I don't 100% understand the logic behind this and don't understand why this won't break or overflow the hardcoded padding widgets. The reason why I am asking here is just want to make sure if this is OK to do and won't break in the future flutter releases by hearing from the official team. Because I don't see any official doc mentioning this so far.

Thank you very much for your help.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
