### ISSUE TITLE
[Question] Type inference

### ISSUE THREAD

**Issue by lukasbash** [flutter/flutter#33201]
Hi together!

I am new to flutter and I have a question about the analyzer & the type inference.
In all the examples in the www and also in the flutter documentation or even in the source code of the framework itself, almost 99% of the code have fixed types assigned. Rarely I found modules or code parts where type inference is used. (I found mixed parts in e.g. the flutter cookbook)

Lets talk about some precise examples:
```
// Fair enough, I could guess it by recognizing the quotes; still, why type it?
String someString = "someValue"

// Can build return something else, other than a widget?
Widget build(BuildContext context) {

// Ok, this is really hard now; the type is even duplicated from the instantiation
final TextEditingController controller = TextEditingController();
```

I am using VSC as an editor and the integration works like a charm. I have no doubts about it. I simply want to understand why so many people favor fixed types instead of making use of the inference.
Is this a best practice?
Do people use it to read the code without possibly open it in an editor?

If I understand anything wrong or missed an important concept please do not hesitate to point out my mistakes.
Would be great if you give me feedback.
Cheers

**Comment by stuartmorgan** [comment]
This is [covered in the Flutter style guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#avoid-using-var).

**Comment by lukasbash** [comment]
> This is [covered in the Flutter style guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#avoid-using-var).

The anchor you linked does defenitely not answer my questions.

**Comment by stuartmorgan** [comment]
You asked why Flutter code uses explicit types; the answer to that question is the explanation for the style rule I linked to:

> This achieves two purposes: it verifies that the type that the compiler would infer matches the type you expect, and it makes the code self-documenting in the case where the type is not obvious (e.g. when calling anything other than a constructor).

**Comment by lukasbash** [comment]
I precisely asked why explicit types are used when the type can be clearly infered (from the analyzer and from looking at the code; see my examples above). If it is used to force self documentation why is the inference even there if its a best practice to fix them anyway.

I see it seems to be a best practice for flutter. I just wanted to discuss that because sometimes leaving out the obvious redundant types makes the code slimmer.
