### ISSUE TITLE
Running "flutter build ios --no-codesign" destroys my XCode build files changes

### ISSUE THREAD

**Issue by apecoraro** [flutter/flutter#33211]
I was following the instructions for creating a Flutter plugin here: https://flutter.dev/docs/development/packages-and-plugins/developing-packages

I ran the "flutter build ios --no-codesign" command initially, which created a bunch of XCode project and configuration files. I then went and added a bunch of iOS specific code to my plugin and updated the XCode build settings in order to get this code to compile and link. However, later I moved the my project to a new location on my filesystem. When I did this I noticed that there were several symlinks that had been created by the "flutter build ios --no-codesign" command that were no longer valid. So I thought I should just re-run "flutter build ios --no-codesign", but when I did that I found that it blew away several of the changes that I had made to my XCode project build settings.

## Steps to Reproduce

1. Run: "flutter build ios --no-codesign"
2. Open the XCode workspace generated by the command above.
3. In the Pods project modify the Header Search Path and/or the Library Search Path parameter.
4. Run: "flutter build ios --no-codesign"
5. Open the XCode workspace again.
6. Look at the Header or Library Search Path parameter and notice that it is different than what it was changed to in step 3.

**Comment by jmagman** [comment]
> In the Pods project modify the Header Search Path and/or the Library Search Path parameter.

This is a limitation of CocoaPods, not Flutter.  The `Pods/` directory can be blown away at any time by them.  You are expected to update your ios/Podfile (which would have been moved to the new filesystem location), if the changes you need are supported by them (see https://guides.cocoapods.org/syntax/podfile.html).
