### ISSUE TITLE
Flutter should provide access to Mozart's FrameInfo::presentation_time, possibly in BuildContext.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#33216]
Tracking item for [FL-222](https://fuchsia.atlassian.net/browse/FL-222) in Fuchsia's Jira repository.

**Comment by Hixie** [comment]
Assigning to @goderbauer for the trivial framework-side fix, but the engine side will also need to be done.

**Comment by goderbauer** [comment]
The framework-side of this change is done.

@cbracken Can anybody on the engine side verify 2) of FL-222?

**Comment by cbracken** [comment]
Engine side work on this is blocked waiting for [FL-233](https://fuchsia.atlassian.net/browse/FL-233) to be resolved.

**Comment by goderbauer** [comment]
I resubmitted the framework side of this.

**Comment by Hixie** [comment]
Now https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=8810

**Comment by iskakaushik** [comment]
Duplicate of https://github.com/flutter/flutter/issues/10850. Please re-open if I misunderstood the intent of this issue.
