### ISSUE TITLE
Icon and IconButton have different padding

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3321]
This makes it tricky to combine icons and buttons in layouts. Also, 'pre-made' layouts, such as GridTileBar layouts incorrectly with IconButtons as the paddings are set for Icons without padding.

A possible solution could be to add a padding property to the Icon class and have the default being the same as for the IconButton.

Test case in Grid demo in the gallery.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/3280 will probably affect this. We probably want IconButton to just fill the available vertical space or some such.

**Comment by sethladd** [comment]
Not sure if this is still an issue? The referenced https://github.com/flutter/flutter/issues/3280 is now closed.

**Comment by Hixie** [comment]
It's probably too late to change this.

**Comment by BruceFast** [comment]
Add  padding: EdgeInsets.all(0.0), as an IconButton parameter.
