### ISSUE TITLE
Add instantiateImageCodecFromUrl to dart:ui and change NetworkImage to use it

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#33215]
To unfork Flutter Web into Flutter, we need `NetworkImage` not to use `dart:io.HttpClient` to download images over the network. It won't be as simple as putting the "download the bytes" logic behind a configurable import, since on the web you can't make a cross-origin `XmlHttpRequest` to download the bytes from another domain and decode those bytes into an image, since that will violate CORS.

To get around this on Flutter for Web, we added `instantiateImageCodecFromUrl` in our version of `dart:ui`, which uses an `<img>` element to download the bytes, which we can then use in painting.

I propose we add this to the mobile version of `dart:ui` as well, and refactor `NetworkImage` to use it instead of managing its own `dart:io.HttpClient`.

**Comment by hterkelsen** [comment]
I'm trying to add `instantiateImageCodecFromUrl` to `dart:ui` by basically moving the code in [`NetworkImage._loadAsync`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/image_provider.dart#L537) into `dart:ui`, but I can't decide how to do the `ImageChunkEvent` notifications.

Should `ImageChunkEvent` move into `dart:ui` also? Then `instantiateImageCodecFromUrl` will take a `StreamController<ImageChunkEvent>` and be responsible for closing the stream.

cc @tvolkert

**Comment by tvolkert** [comment]
Does this mean you intend to move `consolidateHttpClientResponseBytes()` to dart:ui as well?  `_loadAsync()` also refers to `PaintingBinding.instance` from the painting library...

**Comment by hterkelsen** [comment]
Jonah has implemented this by putting `NetworkImage` implementations behind configurable imports: https://github.com/flutter/flutter/pull/34112

I think this is the best way to do it, considering the problems with trying to have a unified implementation discussed above.
