### ISSUE TITLE
GridTileBar doesn't correctly abbreviate  words

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3322]
The title and caption of the GridTileBar should be on a single line. If the line is too long it should use dots.

E.g. 'A too long title' -> ' A too long t...'

Test case in Grid demo in gallery.

**Comment by HansMuller** [comment]
An often requested feature.  See also:
https://github.com/flutter/flutter/issues/417
https://github.com/flutter/flutter/issues/974
https://github.com/flutter/flutter/issues/1027

**Comment by HansMuller** [comment]
I have a fix for this (just using the new ellipsis support)
