### ISSUE TITLE
Match flutter's text overflow behavior

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#33223]
Currently on the web, we do support text overflow, but not completely. There are edge cases that don't work as expected on the web today:

1. In multi-line text, the ellipsis should be shown at the first line that overflows, and subsequent lines shouldn't be rendered.
2. When `maxLines` is specified, the ellipsis should go at the last line (if it overflows).

**Comment by YemaneZewdu** [comment]
Hi, is the overflow behaviour supported now? I am on Flutter 2.0.4 • channel stable and experiencing this issue on web projects.

Thanks

**Comment by mdebbar** [comment]
@YemaneZewdu would you mind upgrading to a newer version of Flutter? There've been some fixes to ellipsis in the last few months.

**Comment by YemaneZewdu** [comment]
@mdebbar Thanks, I upgraded to the latest Flutter 2.2.0 • channel stable but still have the issue. Maybe it hasn't been covered yet. I was thinking there would be a PR or some other confirmation posted to this issue. Thanks.

**Comment by mdebbar** [comment]
@YemaneZewdu please take a look at this issue: https://github.com/flutter/flutter/issues/82639

If you are seeing a different issue, please file a new issue.
