### ISSUE TITLE
Large amount of overdraw detected on login screen

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#33221]
Placeholder for [FL-259](https://fuchsia.atlassian.net/browse/FL-259). which describes a potential problem either with the engine on Fuchsia or applications running on Fuchsia. Logging here for visibility to the Flutter triage team.

**Comment by Hixie** [comment]
(This is considered less important than https://github.com/flutter/flutter/issues/32779)

**Comment by Hixie** [comment]
This is currently blocked on FL-250.

**Comment by Hixie** [comment]
This is now https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=8842.

**Comment by Hixie** [comment]
Is this still an issue in the 2D Scenic world?

**Comment by Hixie** [comment]
This is moot in the 2D world, closing.
