### ISSUE TITLE
Drawer shadow keeps vanishing

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3323]
e.g. play with the material gallery drawer

**Comment by eseidelGoogle** [comment]
Didn't we have a bug of disappearing shadows like this that ended up in Skia before?  I wonder if @jason-simmons's new `flutter skia` debugger command could help debug?
https://sites.google.com/site/skiadocs/developer-documentation/skia-debugger

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/2670 was the bug in quesiton.

**Comment by eseidelGoogle** [comment]
Is this still an issue?  https://github.com/flutter/flutter/issues/5231 has a similar title and is a known skia issue.

**Comment by Hixie** [comment]
dupe of 5231.
