### ISSUE TITLE
[web] Using Flutter libraries in Flutter Web 

### ISSUE THREAD

**Issue by dbacinski** [flutter/flutter#33239]
## Use case

I would like to use Flutter libraries for Flutter Web, the problem is that Flutter Web is using a diffrent package flutter_web which breaks most of the Flutter libraries that import flutter widgets/foundation.

## Proposal

Would be great to have some build tool that would automatically change flutter imports from flutter to flutter_web for external libraries.

Something like this was done on Android for Android Support Lib to AndroidX migration. It was done with a build flag `android.enableJetifier=true` and it worked pretty well https://developer.android.com/jetpack/androidx/migrate#migrate

The end result could look like this: https://github.com/rrousselGit/provider/compare/master...kevmoo:flutter_web

**Comment by jonahwilliams** [comment]
Rather than spend time on temporary code generation/transformation solutions, we're going to work on https://github.com/flutter/flutter/issues/34082 so that they are the same.
