### ISSUE TITLE
More than one file was found with OS independent path libflutter.so'

### ISSUE THREAD

**Issue by mahendramahi** [flutter/flutter#33247]
## Use case
In my project we have ios and android native project. But after heard about flutter we decide that new functionality will develop into flutter module ( `flutter create -t module project_name` ) and finish work on flutter, we export .aar file from flutter project.

Now go to my android project and import flutter exported .aar file in android project as module or lib. for reference  see the image 
![Untitled](https://user-images.githubusercontent.com/9445572/58249703-37ad5080-7d7d-11e9-8441-58b5570a45dc.png)

After import we analyze .aar just like .apk file and here are image for reference  
![analyze](https://user-images.githubusercontent.com/9445572/58251588-996fb980-7d81-11e9-90a5-11284ec83d45.png)

## How can we call dart route page from Android app

`
@Override
  protected void onCreate(Bundle savedInstanceState){
        Flutter.startInitialization(getApplicationContext());
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        DisplayMetrics displayMetrics=new DisplayMetrics();
        getWindowManager().getDefaultDisplay().getMetrics(displayMetrics);
        height=displayMetrics.heightPixels;
        width=displayMetrics.widthPixels;

        View flutterView=Flutter.createView(
        MainActivity.this,
        getLifecycle(),
        "/"
        );
        FrameLayout.LayoutParams layout=new FrameLayout.LayoutParams(width,height);

        addContentView(flutterView,layout);
        }`

Call this code from my android activity .. 
and we are successfully able to load flutter view on android activity
and for android we export app.framwork and flutter.framwork , ios app also able to load same view as like android(save time of development same thing in different lang or on difference platform )

## issue
Now we create other module in flutter and import same as last time. during the import .aar we can change name of module using android studio. Here are we attaching image reference.

![next](https://user-images.githubusercontent.com/9445572/58252141-0768b080-7d83-11e9-8a7d-19d3a9a62dee.png)

Now you can see the .so file in second .aar file with the same name of last one .aar file..

when we run this it gives error 
` More than one file was found with OS independent path libflutter.so' `

## Proposal

Please suggest me way that we can resolve this and make it easy

**Comment by jmagman** [comment]
@blasten

**Comment by blasten** [comment]
The Flutter tool (`v1.12.13` now builds AARs out of the box. If you run `flutter build aar` in the module directory, you will get the `.aar` artifacts. You can read more on https://flutter.dev/docs/development/add-to-app/android/project-setup#option-a---depend-on-the-android-archive-aar.  

Feel free to file a new issue if you encounter a problem.
