### ISSUE TITLE
Google assistant support

### ISSUE THREAD

**Issue by suesitran** [flutter/flutter#33243]
## Use case

I want user to be able to talk to my app using Google assistant

**Comment by surveshoeb** [comment]
Any update?

**Comment by bipinvaylu** [comment]
Hey @kf6gpe @zoeyfan @iapicca  any update on this?

**Comment by suesitran** [comment]
really no update?

**Comment by kf6gpe** [comment]
I'm sorry, I'm no longer working on Flutter. I'll let the other Flutteristas comment!

**Comment by iapicca** [comment]
> really no update?

@suesitran 
this issue has the lowest priority possible, I wouldn't hold my breath
it's a good idea for a third party plugin though,
maybe the community can help you making one

**Comment by stuartmorgan** [comment]
Based on the updated guidance in https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues, I'm going to close this issue, better reflecting the expectation that this is not something that the Flutter team plans to implement.
