### ISSUE TITLE
[url_launcher - iOS] After window.rootViewController reset launch url is not working

### ISSUE THREAD

**Issue by jkmathew** [flutter/flutter#33259]
At some point I have to reset my application window's root view controller. After that, `launch(url);` from dart it is printing warning `Warning: Attempt to present <SFSafariViewController: 0x7fc42e866c00> on <FlutterViewController: 0x7fc42e828e00> whose view is not in the window hierarchy!` in the log.

### Steps to reproduce.
  1.  At any point reset windows root view controller. 
  2. Call from dart after that.

From [flutter/plugins](https://github.com/flutter/plugins/blob/a3988f85689d3a35fc3f1ccd8c722d228305c969/packages/url_launcher/) repo, I could see that the url_launcher plugin native side is keeping rootviewcontroller while initialising the plugin 

Code here: 
https://github.com/flutter/plugins/blob/a3988f85689d3a35fc3f1ccd8c722d228305c969/packages/url_launcher/ios/Classes/UrlLauncherPlugin.m#L72-L89

**Comment by jkmathew** [comment]
This will also happen if `FlutterViewController` is presenting to any view controller. ([like example in add to app wiki](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps)) 


```swift
    let flutterEngine = (UIApplication.shared.delegate as? AppDelegate)?.flutterEngine;
    let flutterViewController = FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil)!;
    self.present(flutterViewController, animated: false, completion: nil)
```

**Comment by TahaTesser** [comment]
Hi @jkmathew 
Given the mentioned PR is merged

if you're still experiencing this problem with latest stable, please create a new issue and provide the information required in the template.
Thank you
