### ISSUE TITLE
flutter run error

### ISSUE THREAD

**Issue by bestheroforever** [flutter/flutter#33251]
Launching lib/main.dart on SM N910H in debug mode...
Initializing gradle...                                                 ⢿
Oops; flutter has exited unexpectedly.
Sending crash report to Google.                                 
Crash report sent (report ID: ************************)                         
Initializing gradle...                                                   
Crash report written to /home/nima/project/flutter/after/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by rostopira** [comment]
Please, post flutter_01.log file here

**Comment by bestheroforever** [comment]
[flutter_01.log](https://github.com/flutter/flutter/files/3212661/flutter_01.log)

**Comment by iapicca** [comment]
Hi @bestheroforever 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
