### ISSUE TITLE
google_sign_in get user's idToken without Firebase

### ISSUE THREAD

**Issue by emilioschepis** [flutter/flutter#33261]
Hi, I would like to know if it is possible to get an user's `idToken` in the `google_sign_in` plugin without integrating Firebase.

I am currently using a Google Cloud Platform project, and the iOS version of the app works perfectly. When I try to access the user's `idToken` on an Android device, however, I always get `null` back.

The `google-services.json` file I downloaded from the GCP console is in `<root>/android/app/`.

**Comment by emilioschepis** [comment]
:tada: Solved! :tada:

I would like to add for future reference that adding a `strings.xml` file in `<root>/android/app/src/main/res/` and manually defining a `default_web_client_id` string with the value in the `google-services.json` file makes everything work again.

**Comment by steevjames** [comment]
Where do I get google-services.json from ? Isnt that from firebase ?

**Comment by gilbertKaradja** [comment]
@steevjames after scouring the net I found a solution. I didn't need to download google-services.json(didn't find a place to get it any way except firebase).

I just added a string.xml file to my android project with client id of a web client

strings.xml content(app/source/main/res/values/string.xml):

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="default_web_client_id">YOUR_WEB_CLIENT_ID</string>
</resources>

So in google cloud console go to credentials(https://console.cloud.google.com/apis/credentials) and get your web client's client id. 

Not that the client id you need is one from a web client, not Android. If you want to auto-generate a pair of credentials you cant do it from here: https://developers.google.com/identity/sign-in/android/start?pli=1&authuser=1

Cheers

**Comment by kazakovav** [comment]
> @steevjames after scouring the net I found a solution. I didn't need to download google-services.json(didn't find a place to get it any way except firebase).
> 
> I just added a string.xml file to my android project with client id of a web client
> 
> strings.xml content(app/source/main/res/values/string.xml):
> `<?xml version="1.0" encoding="utf-8"?> <resources> <string name="default_web_client_id">YOUR_WEB_CLIENT_ID</string> </resources>`
> 
> So in google cloud console go to credentials(https://console.cloud.google.com/apis/credentials) and get your web client's client id.
> 
> Not that the client id you need is one from a web client, not Android. If you want to auto-generate a pair of credentials you cant do it from here: https://developers.google.com/identity/sign-in/android/start?pli=1&authuser=1
> 
> Cheers

Many thanks!
It's working for me

**Comment by singhmitesh** [comment]
> @steevjames after scouring the net I found a solution. I didn't need to download google-services.json(didn't find a place to get it any way except firebase).
> 
> I just added a string.xml file to my android project with client id of a web client
> 
> strings.xml content(app/source/main/res/values/string.xml):
> `<?xml version="1.0" encoding="utf-8"?> <resources> <string name="default_web_client_id">YOUR_WEB_CLIENT_ID</string> </resources>`
> 
> So in google cloud console go to credentials(https://console.cloud.google.com/apis/credentials) and get your web client's client id.
> 
> Not that the client id you need is one from a web client, not Android. If you want to auto-generate a pair of credentials you cant do it from here: https://developers.google.com/identity/sign-in/android/start?pli=1&authuser=1
> 
> Cheers

This works if you don't want to use firebase and just use google_sign_in lib. thanks @kazakovav it's working for me too.

**Comment by singhmitesh** [comment]
> @steevjames after scouring the net I found a solution. I didn't need to download google-services.json(didn't find a place to get it any way except firebase).
> 
> I just added a string.xml file to my android project with client id of a web client
> 
> strings.xml content(app/source/main/res/values/string.xml):
> `<?xml version="1.0" encoding="utf-8"?> <resources> <string name="default_web_client_id">YOUR_WEB_CLIENT_ID</string> </resources>`
> 
> So in google cloud console go to credentials(https://console.cloud.google.com/apis/credentials) and get your web client's client id.
> 
> Not that the client id you need is one from a web client, not Android. If you want to auto-generate a pair of credentials you cant do it from here: https://developers.google.com/identity/sign-in/android/start?pli=1&authuser=1
> 
> Cheers

This works if you don't want to use firebase and just use google_sign_in lib. thanks @gilbertKaradja  it's working for me too.
