### ISSUE TITLE
firebase_messaging - deleteInstanceID crashes

### ISSUE THREAD

**Issue by sandaru1** [flutter/flutter#33265]
The deleteInstanceID method fails in Android. I'm using firebase_messaging 5.0.1+1.

The steps to reproduce are quite simple, just call the method. The method implementation calls the "result.success" function inside a non-UI thread which crashes the entire app.

    java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-16
        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
        at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:556)
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:131)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
        at io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin$3.run(FirebaseMessagingPlugin.java:151)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by nvquangth** [comment]
I have same issue

**Comment by marianoarga** [comment]
Same issue using firebase_messaging: 3.0.0

**Comment by kikz0rsk** [comment]
We are experiencing the same issue, looks like it is related to flutter version v1.5.9 and newer.
Similar issue with other plugins, check #32315.

**Comment by SPodjasek** [comment]
Same problem here with ```firebase_messaging: 5.0.3```
I've crashes on:
* `beta, v1.6.3, on Linux`
* `master, v1.7.5-pre.10`

And it works on stable, `v1.5.4-hotfix.2`

**Comment by wildtigon** [comment]
@sandaru1: it has been fixed in version 5.05

**Comment by iapicca** [comment]
Hi @sandaru1 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Hi @sandaru1 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
