### ISSUE TITLE
Flutter generate doesn't generate classes for classes in test folder

### ISSUE THREAD

**Issue by humblerookie** [flutter/flutter#33266]
I've tried to generate DI classes using [inject.dart](https://github.com/google/inject.dart) via `flutter generate`

It seems to generate classes under lib/* but not for test/*. It does not throw any error as such. Here are my relevant flutter classes.

**pubspec.yaml**

    name: gc_client
    description: A gc
    
    version: 1.0.0+1
    
    environment:
      sdk: ">=2.1.0 <3.0.0"
    
    dependencies:
      flutter:
        sdk: flutter
      json_annotation: ^2.0.0
      rxdart: ^0.22.0
      dio: ^2.1.3
      inject:
        path: ./inject.dart/package/inject
    
    builders:
      json_serializable: ^2.0.0
      inject_generator:
        path: ./inject.dart/package/inject_generator
    
    dev_dependencies:
      test: 1.6.1
      flutter_test:
        sdk: flutter
      mockito: ^4.0.0
    
    
    flutter:
    
      uses-material-design: true
  
      assets:
      - assets/

**Component classes**

https://i.stack.imgur.com/d8iFa.png

Am I missing something? Let me know if you need more info. Thanks in advance.

**Comment by jonahwilliams** [comment]
We're not correctly telling build_daemon to build things under test, fix is here: https://github.com/flutter/flutter/pull/33284

**Comment by humblerookie** [comment]
I've tried applying these changes to same file in my SDK, still doesn't seem to generate the required classes. Is their something do in the meanwhile before this gets deployed?

**Comment by jonahwilliams** [comment]
did you also force the tool to re-snapshot by deleting `flutter/bin/cache/flutter_tools.stamp` and `flutter/bin/cache/flutter_tools.snapshot`?

**Comment by humblerookie** [comment]
Yeah just figured, sorry about it. works 😄

**Comment by jonahwilliams** [comment]
Yay! 🎊

**Comment by humblerookie** [comment]
Also on a related note I've noticed that the new `builders` directive takes a  full path/absolute directory path instead of the relative path  for the `path` directive within the project. Is this a bug and/or is being worked on?

**Comment by jonahwilliams** [comment]
Does https://github.com/flutter/flutter/pull/33283 fix it for you?

**Comment by humblerookie** [comment]
Perfect.

**Comment by humblerookie** [comment]
@jonahwilliams  Is there any particular reason why the IDE might be unable to identify the generated files under the test folder?

**Comment by jonahwilliams** [comment]
@humblerookie would you be willing to file a new issue for that on https://github.com/dart-lang/sdk/issues/new ?

You can cc me and I will follow up with someone that knows more about the analyzer/IDE tooling.

**Comment by humblerookie** [comment]
Sure thing.
