### ISSUE TITLE
Gallery, overscroll glow doesn't seem to follow 

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3327]
In Gallery, Components, List. The overscroll glow (which, very cool!!) doesn't seem to match the behavior of the overscroll glow in Play Movies app and YouTube app.

In Play Movies and YouTube, the glow follows your finger side to side. In the gallery app, the glow only moves down.

For example, scroll down in a "J" pattern. In Play Movies and YouTube, the overflow glow follows as you make the curve with your finger. In Gallery, the glow doesn't follow the curve.

Happy to show in person. Thanks for taking a look!

**Comment by HansMuller** [comment]
To add the flexible "glow" behavior seen in native Android apps we'll need to expose the coordinates of GestureDetector events.

**Comment by Hixie** [comment]
For which gesture detector?

**Comment by abarth** [comment]
Fixing this is going to require reworking some of the gesture callbacks.

**Comment by eseidelGoogle** [comment]
@aghassemi may have looked at this already?

**Comment by aghassemi** [comment]
@eseidel Not yet. This and friends (https://github.com/flutter/flutter/issues/4502 https://github.com/flutter/flutter/issues/4406 https://github.com/flutter/flutter/issues/4169 https://github.com/flutter/flutter/issues/4167 https://github.com/flutter/flutter/issues/4129 https://github.com/flutter/flutter/issues/4127) are on my list to look at.
