### ISSUE TITLE
Impact of Building with Older Versions of Flutter

### ISSUE THREAD

**Issue by searchy2** [flutter/flutter#33273]
For CI, the Flutter version that is used to build is often not the latest. 

For example. Bitrise is using Flutter v1.2.1 and not upgrading to v1.5.4 to not break old Flutter projects. What is the impact of building with an older version of Flutter? Will a Flutter project written with v1.5.4 but built in v1.2.1 have all the benefits of v1.5.4 or will it have the bugs of v1.2.1? 

Thanks for any clarification!

**Comment by jonahwilliams** [comment]
If you build with flutter v1.2.1 you get that particular version of the framework and dart. if you need a bug fix from a later version that will not get applied.

**Comment by searchy2** [comment]
@jonahwilliams Thanks for the clarification!
