### ISSUE TITLE
Add commit hashes to release notes

### ISSUE THREAD

**Issue by JakeSays** [flutter/flutter#33276]
## Use case

I create custom flutter embedders for embedded/soc devices. My embedders track official releases, not master. Finding out the exact versions of the engine and flutter that correspond to an official release is difficult to say the least.

For example, there are two flutter branches that may be the release for 1.5.4: v1.5.4-hotfixes and stable. There are three tags: v1.5.4, v1.5.4-hotfix.1 and v1.5.4-hotfix.2

For the engine there is only one branch that makes sense: v1.5.4-hotfixes, and no tags.

Which of these are correct?

## Proposal

It would be really helpful to have the commit hashes for both flutter and the engine added to the release notes for each official release (https://github.com/flutter/flutter/wiki/Release-Notes-Flutter-1.5.4).

**Comment by stuartmorgan** [comment]
> Finding out the exact versions of the engine and flutter that correspond to an official release is difficult to say the least.

Is checking out the release (e.g., if you want the current stable release, switch to the `stable` channel and then `flutter upgrade`) and then running `flutter --version` not an option?

https://flutter.dev/docs/development/tools/sdk/releases also lists the Flutter hash.

**Comment by JakeSays** [comment]
@stuartmorgan yes that works! Thanks!
