### ISSUE TITLE
Easier FlutterEngine↔FlutterEngine interop

### ISSUE THREAD

**Issue by xster** [flutter/flutter#33288]
We're going to need to facilitate inter-engine/isolate communication moving forward.

We can

- Also leverage https://github.com/flutter/flutter/issues/32930 to establish an IPC schema between isolates
- @sjindel-google talked about work in progress for having multiple isolates sharing a single shared-heap isolate for data sharing
- Explore having multiple engines running on the same isolate while rendering distinct, isolated widget trees. This is what ByteDance explored in https://translate.google.com/translate?sl=zh-CN&tl=en&u=https%3A%2F%2Fmp.weixin.qq.com%2Fs%2F-vyU1JQzdGLUmLGHRImIvg

**Comment by gaaclarke** [comment]
Do we want to encourage this?  It seems like almost all of the time the clients will want one FlutterEngine.  The reason they might have multiple right now is a hack around multiple surfaces which we plan to implement anyways.

**Comment by xster** [comment]
Discussed offline today. FlutterEngines don't duplicate everything. It's still the same VM and there's one snapshot loaded into memory. They have their own isolates and heap which draws their own trees. 

We circumstantially recommend this, if there are 2 semi-independent Flutter things being shown simultaneously, multiple engines is ok. 

This is then about how to let them talk to each other.

**Comment by pedromassangocode** [comment]
Is this still a valid issue?

**Comment by kf6gpe** [comment]
@xster @gaaclarke I assume this is at least in part being addressed by the multi-engine work y'all are doing, right?

Feel free to downgrade priority if I'm wrong.

**Comment by 2ZeroSix** [comment]
link related: #72009

**Comment by xster** [comment]
Implementation could be https://github.com/flutter/flutter/issues/72030 or something else.

**Comment by xster** [comment]
b/186080928 for internal dependent bug.

**Comment by a-siva** [comment]
Is there still a Dart dependency for this issue considering the light weight isolate work is done ?

**Comment by a-siva** [comment]
Closing issue as done,
