### ISSUE TITLE
Get javadocs implemented with standard Flutter website style.

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#33286]
Get javadocs implemented with standard Flutter website style.

**Comment by matthew-carroll** [comment]
CC @xster for visibility. The JavaDoc pages are standard JavaDoc style, which feels completely unrelated to the main Flutter docs.

**Comment by xster** [comment]
This is about finding some css theme for javadocs that look closer to the dartdoc sites right?

**Comment by matthew-carroll** [comment]
I think this should be more than just styling. I think we should migrate the docs so that they are a part of the standard flutter.dev website. In other words, I don't think the javadocs should be located in a fundamentally different place, or feel fundamentally different than Dart docs and any other docs that are core to Flutter. I don't want to be too prescriptive because there may be other concerns for us to weigh here, but generally speaking, the closer the JavaDocs are to DartDocs in every way, the better.

**Comment by matthew-carroll** [comment]
BTW, this is what we have now: https://api.flutter.dev/javadoc/

**Comment by xster** [comment]
Do you mean also finding FlutterActivity when searching from https://api.flutter.dev?

**Comment by matthew-carroll** [comment]
Being able to search javadocs from the main Flutter website would certainly be one expectation, but that's just one detail. I would expect similar styling of the docs (but not necessarily identical). I would expect Flutter's main website navigation to surround the javadocs. At this point, it would be a shorter list to say what our current javadocs have correct in terms of styling and the surrounding website.

**Comment by reidbaker** [comment]
not sure if this is still valuable

**Comment by matthew-carroll** [comment]
@reidbaker what's up?!
