### ISSUE TITLE
[image_picker] iOs GIF file Support

### ISSUE THREAD

**Issue by diruuu** [flutter/flutter#33291]
Hi, I cannot find any related discussion here, but is there any way to pick GIF file on iOs device? Mine always converted to JPEG.

**Comment by EmreSURK** [comment]
Hello,
Do you mean selecting an image from the gallery(or Camera Roll, etc), right?

**Comment by diruuu** [comment]
Yes, from the iOs gallery. Everytime I select the GIF file, it's always converted to JPEG. I ended up using file_picker library. But it would be nice to be able to select GIF file on iOs gallery using this library too.

**Comment by xzylzz** [comment]
I'm using 0.5.0,it's always converted to PNG. Hope fix it soon.

**Comment by miguelpruivo** [comment]
As workaround you can use the [file_picker](https://pub.dev/packages/file_picker) with the `FileType.IMAGE` flag.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
