### ISSUE TITLE
[Android] Full screen Platform View fails on fullscreen devices with notch

### ISSUE THREAD

**Issue by yoavrofe** [flutter/flutter#33290]
A full screen WebView (w/o an AppBar) now produces the following error on my Pocophone on the master channel:

`E/flutter (14390): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Creating a virtual display of size: [1080, 2116] is not supported. It is larger than the device screen size: [1080, 2029]., null)`

The screen size as calculated by `MediaQuery.of(context).size.height*MediaQuery.of(context).devicePixelRatio`
is 2116.0.

**This is a critical bug**, that prevents running full-screen platform views (including Google Maps) on similar devices.

Probably caused by: https://github.com/flutter/engine/commit/7471ddea463dd0a95a2b6d8e3a9028df70c56cee

Which solved this: https://github.com/flutter/flutter/issues/28978

Flutter Doctor:
```
[✓] Flutter (Channel master, v1.6.2-pre.21, on Mac OS X 10.14.4 18E226, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.34.0)
[✓] Connected device (1 available)

```

**Comment by Eimji** [comment]
Hello

I have the same bug a real device, e.g. samsung A50 (however it works fine on emulator). Here is my flutter doctor

```
[✓] Flutter (Channel dev, v1.6.3, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.6.3 at /home/patrick/DATA/Github/flutter
    • Framework revision bc7bc94083 (il y a 3 jours), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/patrick/DATA/Applications/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/patrick/DATA/Applications/Android/Sdk
    • Java binary at: /home/patrick/DATA/Applications/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/patrick/DATA/Applications/Android/android-studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.33.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.0.2

[✓] Connected device (2 available)


• No issues found!
```

**Comment by yoavrofe** [comment]
I identified the line that causes the problem. See [here](https://github.com/flutter/engine/commit/7471ddea463dd0a95a2b6d8e3a9028df70c56cee#commitcomment-33689770). :

(But I think that it's better to check for the display size on the Dart side).

**Comment by MattL-NZ** [comment]
Thanks @yoavrofe. Hopefully they get this fixed soon! In the interim, I can switch back to the Flutter Stable channel as the issue isn't there yet. Hopefully they fix it so I can go back to using the Flutter Dev channel.

**Comment by Eimji** [comment]
Hello,
@ iskakaushik could you tell us when your change will be available with the dev channel of Flutter ?
Thanks.
