### ISSUE TITLE
TextField property  autofocus: true ，Don't show ‘cut paste’ view

### ISSUE THREAD

**Issue by dansunhappy** [flutter/flutter#33293]
## Steps to Reproduce

1. input string is null
2. autofocus: true
3. long click not show ‘paste cut’ view

## Code
```
TextField(
                    autofocus: true,
                    onSubmitted: _invitationCommit,
                    enabled: true,
                    controller: _textController,
                    maxLength: 8,
                    maxLines: 1,
                    style: TextStyle(
                      fontSize: flexible(context, 18.0),
                      height: 1.0,
                      color: Colors.black,
                      fontWeight: FontWeight.bold,
                    ),
                    decoration: InputDecoration.collapsed(
                      hintText: '',
                      filled: true,
                      fillColor: Colors.white,
                      border: InputBorder.none,
                    ).copyWith(counterText: ''),
                    keyboardType: TextInputType.numberWithOptions(),
                  ),
```
## flutter --version

```
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (3 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```

**Comment by justinmc** [comment]
You're right, I was able to reproduce this.  Thanks for submitting an issue!

It seems like any empty TextField with `autofocus: true` will not show the selection menu on long press.  Setting `autofocus: false` makes it show up again.

Here's my code:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Autofocus bug'),
        ),
        body: Center(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.start,
            children: <Widget>[
              TextField(
                autofocus: true,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by dansunhappy** [comment]
> You're right, I was able to reproduce this. Thanks for submitting an issue!
> 
> It seems like any empty TextField with `autofocus: true` will not show the selection menu on long press. Setting `autofocus: false` makes it show up again.
> 
> Here's my code:
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: Scaffold(
>         appBar: AppBar(
>           title: Text('Autofocus bug'),
>         ),
>         body: Center(
>           child: Column(
>             crossAxisAlignment: CrossAxisAlignment.start,
>             mainAxisAlignment: MainAxisAlignment.start,
>             children: <Widget>[
>               TextField(
>                 autofocus: true,
>               ),
>             ],
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```

some page ,  `autofocus: true ` & empty TextField  ,at the same time I want show the selection menu on long press，How to do？

**Comment by justinmc** [comment]
I don't know of a workaround.  There will probably have to be a change made to Flutter to fix this bug.

**Comment by AgentFabulous** [comment]
This issue was introduced by commit "Material Long Press Text Handle Flash (#32911)" (SHA: 6031c56d4ccfc70656d1a7aff93b913b4476e1bc.).
Other ways to reproduce this issue: type some text in a TextField and get rid of it all. Then long press the field; the options won't show.
Quick fix (do note, this brings back the handle flicker/flash!): 
Open `packages/flutter/lib/src/rendering/editable.dart`, method `_handlePotentialSelectionChange`, remove this check:
```    if (nextSelection == selection) {
      return;
    }```
Again, this is by no means a fix, just a workaround to restore the broken functionality for now.

**Comment by justinmc** [comment]
This should be fixed in the next release (1.8.1+) with the PR referenced above.  Make sure you're on the right [channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels) to get it.

**Comment by AgentFabulous** [comment]
@justinmc Tried the changes, there still seems to be an issue; when the user clears a text field containing text, they can't long press to paste. It works just fine if you long press an empty text field, but not when you long press a text field after clearing it's text. I made 2 changes [here](https://github.com/AgentFabulous/flutter/commits/master) sort of fix it; not sure if it's the right way to do things, though.

**Comment by justinmc** [comment]
@AgentFabulous You're right, I can reproduce that even by just using backspace.  I'll create a new issue to track this.

After taking a quick look, I'm hoping we can come up with a way to fix the root problem.  There is some really fragile dependencies between the selection menu being shown, the selection overlay being created, and setting new selections.

**Comment by AgentFabulous** [comment]
Good to know, thanks :)
