### ISSUE TITLE
RefreshIndicator unnecessarily rebuilding ListView

### ISSUE THREAD

**Issue by altherat** [flutter/flutter#33294]
This may be quite a specific problem, or maybe this is expected for some reason, but if I use a `StreamBuilder` (or `FutureBuilder`) as the child of a `RefreshIndicator`, the `ListView` is rebuilt when tapped down and tapped up. But if I put the `ListView` directly as the child of `RefreshIndicator` it does not have this problem. Workaround is to just wrap the RefreshIndicator with the builder, but it still seems like a bug.

Simple app demonstrating problem:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: RefreshIndicator(
          onRefresh: () {},
          child: StreamBuilder(
            builder: (context, snapshot) {
              return ListView.builder(
                itemBuilder: (context, index) {
                  print('build: $index');
                }
              );
            }
          )
        )
      )
    );
  }

}
```

Output of `flutter doctor -v`:
```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.503], locale en-CA)
    • Flutter version 1.5.4-hotfix.2 at C:\Flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Matt\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio Canary\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)
    • All Android licenses accepted.

[√] VS Code (version 1.34.0)
    • VS Code at C:\Users\Matt\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.2

[√] Connected device (1 available)
    • ONEPLUS A6013 • 9e76e20e • android-arm64 • Android 9 (API 28)
```

**Comment by mbellezi** [comment]
Strange, it should update the children only when tag and dragging, but any tap in the ListView triggers a new update. I think it's a bug as without Refreshindicator this not happens.

**Comment by darkmarthur** [comment]
Same here, if you are on positioned on top of the listview and you scroll to the bottom, it will rebuild the child widets

**Comment by Fintasys** [comment]
Have the same issue, having ListView.Builder inside RefreshIndicator and every tap on an item leads to refresh of my ListView. Any ideas?

**Comment by andy-yc-lin** [comment]
I wrapped my RefreshIndicator in a GestureDetector and had `onTap: () { /* do nothing*/ }` hacky but works

**Comment by Fintasys** [comment]
@andy-yc-lin Thanks, that works great !

**Comment by xuzhengquan** [comment]
but if i durg it will rebuild too. @andy-yc-lin
