### ISSUE TITLE
<webview_flutter> Page destruction, audio is still playing

### ISSUE THREAD

**Issue by hu1095878620** [flutter/flutter#33299]
Android:When the page is destroyed, the audio continues to play.

My suggestion:My suggestion:
@Override
  public void dispose() {
    if(webView != null){
      webView.clearCache(true);
      webView.removeAllViews();
      webView.destroy();
    }
    methodChannel.setMethodCallHandler(null);
  }

**Comment by Awybupt** [comment]
Mark, I also met this bug.

**Comment by charafau** [comment]
I thought it might be fixed on newest branch (because it's working on youtube) but doesnt on web work when website uses web audio api like this one:  https://webaudioapi.com/samples/script-processor/

here's quick snippet to check it:

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

main() => runApp(MainScreen());

class MainScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Webview Tester',
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          child: Text('Open webview'),
          onPressed: () {
            Navigator.of(context)
                .push(MaterialPageRoute(builder: (_) => SecondScreen()));
          },
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: WebView(
        initialUrl: 'https://webaudioapi.com/samples/script-processor/',
        javascriptMode: JavascriptMode.unrestricted,
      ),
    );
  }
}

```

When I click back button / back arrow video and audio stops.

**Comment by QingyangLiu** [comment]
Have the latest version, yet still have the same problem.  The audio persists even past a hard reload.  Had to close simulator to get rid of the audio.  Is there a dispose function that I'm missing?

**Comment by amirh** [comment]
@QingyangLiu thanks for the report can you file a separate issue for the iOS problem? (I believe the issue discussed in this thread was Android only)

**Comment by woutervanwijk** [comment]
> Have the version 0.3.14, yet still have the same problem. The audio persists even past a hard reload. Had to close iOS simulator and restart to stop the audio. Is there something I'm missing? If no, is there any workarounds?

I have the same problem

**Comment by vankhoa01** [comment]
I had the same problem with latest version webview_flutter: ^0.3.21
