### ISSUE TITLE
FocusNode does not respect requestFocus() when keyboard closed by back button

### ISSUE THREAD

**Issue by opensourcegps** [flutter/flutter#33305]
Following scenario does work with FocusNode:

Create text field with FocusNode:
```
 var _focusNode = new FocusNode();

TextField(
              focusNode: _focusNode,
              controller: textEditingController,                    
           );
```
Now user clicks on the text field and keyboard opens. User presses Back button on the device and keyboard closes.

After that it's no longer possible to open keyboard with requestFocus():

```
 FocusScope.of(context).requestFocus(_focusNode);
```

In case user didn't close keyboard with back button, everything works properly.

This looks like the same closed issue from 2018 as: https://github.com/flutter/flutter/issues/20706

 
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /home/flutter/flutter_v1.5.4-hotfix.2-stable
    • Framework revision 7a4c33425d (4 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

```

**Comment by iapicca** [comment]
Hi @opensourcegps 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by opensourcegps** [comment]
Problem still present. 
```
✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.4 at /home/flutter/flutter_linux_v1.9.1_hotfix.4-stable
    • Framework revision cc949a8e8b (12 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
```

Clearly "waiting for customer response" should not be abused too much. Many submitted bugs just get closed because of it. Does not make any sense to submit any new bug reports. Even https://github.com/flutter/flutter/issues/33305 was closed because of it. This one would be closed and forgotten, because asking for new flutter doctor.

**Comment by iapicca** [comment]
I'm not sure to understand the comment about the label.
Anyway, does this [code](https://gist.github.com/iapicca/bd70a608d1b8432a99a91f186b619199) reflect the situation you are describing?

**Comment by opensourcegps** [comment]
Yes, code looks correct. Tap the textfield to open keyboard, hardware back button to close keyboard, tap floating button to open keyboard programmatically. 

Thanks for looking into it, regarding the label, many real bugs just gets closed and forgotten because of it.

**Comment by spiritinlife** [comment]
@opensourcegps i faced the same issue, after some trial and error i solved it by explicitly unfocusing the focusNode before requesting focus again. So now when i want to open the keyboard and focus a textfield programmatically i am doing the following:
```
_focusNode.unfocus();
 FocusScope.of(context).requestFocus(_focusNode);
```

**Comment by opensourcegps** [comment]
@spiritinlife thanks, it works!

**Comment by ofer026** [comment]
Hey, 
I'm having the same issue but the solution that @spiritinlife wrote doesn't work for me. 
Any one else experiencing the same problem??

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by ofer026** [comment]
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.

hey, I don't have any errors or any logs, it's just doesn't work, the same problem as who open this issue.
If this will help you, this is my `flutter doctor -v`:
`flutter doctor -v
[√] Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [Version 10.0.18363.959], locale en-US)
    • Flutter version 1.19.0-4.3.pre at D:\Flutter\flutter
    • Framework revision 8fe7655ed2 (3 weeks ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\ofero\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at D:\OFER\Java\IDE\IntelliJ IDEA Community Edition 2019.2.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.43.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 84.0.4147.89

! Doctor found issues in 1 category.` 
(I'm using Android Studio so you can ignore the IntelliJ issue)

**Comment by jigarpatel17** [comment]
I am also getting same issue, logs are as per below.
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-IN)
    • Flutter version 1.20.2 at /Users/abc/Desktop/Work/sdk/flutter
    • Framework revision bbfbf1770c (5 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.0-rc2)
    • Android SDK at /Users/abc/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

• No issues found!
```

Testing device: Google Pixel 3a.

Also tried with explicitly unfocusing and requesting focus again. But still, it does not work.

**Comment by jsroest** [comment]
Please don't judge me for even trying, but this works.
```
_focusNode.unfocus();
await Future<void>.delayed(Duration(milliseconds: 1));
FocusScope.of(context).requestFocus(_focusNode);
```

**Comment by dfourcfive** [comment]
@jsroest jsroest 
this is what i'm facing 
i have used this code below : 
``
 setState(() {
                            fEmail.unfocus();
                            FocusScope.of(context).requestFocus(fPassword);
                          });
}
``
because I'm trying to activate the shadow on the selected text field 
do you have any other suggestions ?

**Comment by dfourcfive** [comment]
well i have used keys and it solved my problem...

**Comment by Dennis-Mwea** [comment]
@jsroest Saved the day. Thank you.
