### ISSUE TITLE
Dart analyzer not recognizing local imports or package imports

### ISSUE THREAD

**Issue by drkhannah** [flutter/flutter#33307]
![Screen Shot 2019-05-24 at 9 21 10 AM](https://user-images.githubusercontent.com/6707443/58330720-856d9b80-7e05-11e9-9ff7-8aa2a9bbc61f.png)

This just started happening randomly, I fixed it last week, randomly, but then it came back.

The Dart Analyzer or Compiler isn't recognizing local files and some packages. The app runs fine. But i keep getting these compiler errors that it can't find my imports. Any ideas?

**Comment by Loopex2019** [comment]
Yeah i have the same issue

**Comment by drkhannah** [comment]
Delete the .symlinks dir in the iOS project, that fixed it for me

**Comment by iapicca** [comment]
Hi @drkhannah 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
