### ISSUE TITLE
firebase_auth Sign-in with Google example is not working- PlatformException

### ISSUE THREAD

**Issue by ayush221b** [flutter/flutter#33303]
I was trying to sign in with my google account on my phone using firebase_auth and just after I select my Google account, this error occurs.
I am using the following plugins:

**pubspec.yaml**
```
dependencies:
  flutter:
    sdk: flutter
  provider: ^2.0.1
  firebase_auth: ^0.11.1
  google_sign_in: ^4.0.1+3
```

I have created a Firebase project. 
Registered my android app. 
Added SHA-1
Made all changes to both build.gradle files.
google-services.json file is also in place.

**Code**
```
import 'package:flutter/material.dart';

import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String name = '';

  Future signIn() async {
    final GoogleSignIn _googleSignIn = GoogleSignIn();
    final FirebaseAuth _auth = FirebaseAuth.instance;

    final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    final GoogleSignInAuthentication googleAuth =
        await googleUser.authentication;
    final AuthCredential credential = GoogleAuthProvider.getCredential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );
    final FirebaseUser user = await _auth.signInWithCredential(credential);
    setState(() {
      name = user.displayName;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              '$name',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: signIn,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```

**fluter run -v output (only error)**

```
[        ] <- accept
[        ] Connected to _flutterView/0x9d8c810c.
[   +1 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on Redmi Y2 is available at: http://127.0.0.1:45129/I06wW4iFpE8=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+3146 ms] E/flutter (13503): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception:
PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 12500: , null)
[   +1 ms] E/flutter (13503): #0      StandardMethodCodec.decodeEnvelope
(package:flutter/src/services/message_codecs.dart:564:7)
[   +1 ms] E/flutter (13503): #1      MethodChannel.invokeMethod
(package:flutter/src/services/platform_channel.dart:302:33)
[   +1 ms] E/flutter (13503): <asynchronous suspension>
[        ] E/flutter (13503): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:226:58)
[   +1 ms] E/flutter (13503): <asynchronous suspension>
[        ] E/flutter (13503): #3      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:268:20)
[   +1 ms] E/flutter (13503): #4      GoogleSignIn.signIn (package:google_sign_in/google_sign_in.dart:339:48)
[        ] E/flutter (13503): #5      _MyHomePageState.signIn (package:todoprovider/main.dart:37:64)
[        ] E/flutter (13503): <asynchronous suspension>
[        ] E/flutter (13503): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
[        ] E/flutter (13503): #7      _InkResponseState.build.<anonymous closure>
(package:flutter/src/material/ink_well.dart:711:32)
[        ] E/flutter (13503): #8      GestureRecognizer.invokeCallback
(package:flutter/src/gestures/recognizer.dart:181:24)
[        ] E/flutter (13503): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:352:11)
[        ] E/flutter (13503): #10     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:301:7)
[        ] E/flutter (13503): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
[        ] E/flutter (13503): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent
(package:flutter/src/gestures/binding.dart:222:20)
[   +1 ms] E/flutter (13503): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent
(package:flutter/src/gestures/binding.dart:198:22)
[   +1 ms] E/flutter (13503): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent
(package:flutter/src/gestures/binding.dart:156:7)
[   +1 ms] E/flutter (13503): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue
(package:flutter/src/gestures/binding.dart:102:7)
[   +1 ms] E/flutter (13503): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket
(package:flutter/src/gestures/binding.dart:86:7)
[   +1 ms] E/flutter (13503): #17     _rootRunUnary (dart:async/zone.dart:1136:13)
[        ] E/flutter (13503): #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[        ] E/flutter (13503): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
[        ] E/flutter (13503): #20     _invoke1 (dart:ui/hooks.dart:234:10)
[        ] E/flutter (13503): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
[        ] E/flutter (13503): 
```

**flutter doctor -v**

```
[✓] Flutter (Channel master, v1.6.2-pre.29, on Linux, locale en_IN)
    • Flutter version 1.6.2-pre.29 at /home/ayush/development/flutter
    • Framework revision be2918ff30 (34 hours ago), 2019-05-22 18:14:01 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/ayush/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/ayush/development/android-studio-ide-181.5056338-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /home/ayush/development/android-studio-ide-181.5056338-linux/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at /home/ayush/development/ideaIU-2018.3/idea-IU-183.4284.148
    • Flutter plugin version 31.1.4
    • Dart plugin version 183.4733

[✓] VS Code (version 1.34.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.0.2

[✓] Connected device (2 available)
    • Redmi Y2 • f9028c2 • android-arm • Android 8.1.0 (API 27)
    • Linux    • Linux   • linux-x64   • Linux

• No issues found!

```

**Comment by ayush221b** [comment]
@zoechi Can you please have a look?

**Comment by ayush221b** [comment]
**Update**: The Sign-in With Google Example in https://github.com/flutter/plugins/blob/master/packages/firebase_auth/example/lib/signin_page.dart is also not working. Same error. @collinjackson @zoechi @Hixie Can you please kindly have a look?

**Comment by pratik037** [comment]
Facing same issue. Platform Exception while using firebaseAuth

**Comment by Rajashow** [comment]
I am facing the same issue; I do not think firebase is related to this issue. I was able to access firebase by using email and password credentials via the signInWithEmailAndPassword method.  The exception only occurs when using the signIn method.

**Comment by ayush221b** [comment]
The exception is with this line:

`final GoogleSignInAccount googleUser = await _googleSignIn.signIn();`

**Comment by RobPFarley** [comment]
I'm also getting the same issue in my project. I have my project set up in firebase and have uploaded my debug SHA-1 key and downloaded the up to date google-services.json, yet I still get api exception 12500

**Comment by rubensdemelo** [comment]
> I'm also getting the same issue in my project. I have my project set up in firebase and have uploaded my debug SHA-1 key and downloaded the up to date google-services.json, yet I still get api exception 12500

Check if your google plays servires are up to date.

**Comment by RobPFarley** [comment]
They are, I've tried it on 3 different devices, all up to date, as well as
an emulator with Google play installed.

**Comment by abhishekgarg5800** [comment]
Not sure but this might be of some help. I tried everything from changing SHA1 keys to restarting multiple times. The error was solved when i gave the support email in firebase console.
<img width="938" alt="Screen Shot 2019-05-31 at 11 31 45 AM" src="https://user-images.githubusercontent.com/7248273/58685002-dea27580-8397-11e9-9994-3487a7006cc7.png">

**Comment by RobPFarley** [comment]
> Not sure but this might be of some help. I tried everything from changing SHA1 keys to restarting multiple times. The error was solved when i gave the support email in firebase console.
> <img alt="Screen Shot 2019-05-31 at 11 31 45 AM" width="938" src="https://user-images.githubusercontent.com/7248273/58685002-dea27580-8397-11e9-9994-3487a7006cc7.png">

You beautiful person, that was it. I've been fighting with this for days. As far as I know there's absolutely nothing in the documentation that says you need a support email in the firebase console to enable google sign in, or if there is it isn't very visible. Thank you :)

**Comment by collinjackson** [comment]
Thanks @abhishekamit!!

Here's a link to a related StackOverflow question: https://stackoverflow.com/questions/47632035/google-sign-in-error-12500

This issue doesn't really seem to be on the Flutter side, but I'll add a note to the README encouraging developers to include a support email.

**Comment by hassana103** [comment]
> 
> 
> Not sure but this might be of some help. I tried everything from changing SHA1 keys to restarting multiple times. The error was solved when i gave the support email in firebase console.
> <img alt="Screen Shot 2019-05-31 at 11 31 45 AM" width="938" src="https://user-images.githubusercontent.com/7248273/58685002-dea27580-8397-11e9-9994-3487a7006cc7.png">

I LOVE YooooooooooooooooooooooooooooooooooooUUUOUOOUOUOU.....

**Comment by epiphanatic** [comment]
> > Not sure but this might be of some help. I tried everything from changing SHA1 keys to restarting multiple times. The error was solved when i gave the support email in firebase console.
> > <img alt="Screen Shot 2019-05-31 at 11 31 45 AM" width="938" src="https://user-images.githubusercontent.com/7248273/58685002-dea27580-8397-11e9-9994-3487a7006cc7.png">
> 
> You beautiful person, that was it. I've been fighting with this for days. As far as I know there's absolutely nothing in the documentation that says you need a support email in the firebase console to enable google sign in, or if there is it isn't very visible. Thank you :)

This solved my issue some weeks back. Now any new project created in Firebase is going back to the 12500 error again. I've recreated projects, code, added SHA1 (and 256), support email (and changed support email just for completeness), and so on and nothing is working. However, all of my old projects still work. I even deleted an old project and recreated it and, while keeping the original code, and of course there is there is the 12500 error again.

Has something changed on Firebase / Google's side? Anyone still getting this error?

**Comment by xero88** [comment]
@epiphanatic i'm getting the same error too, i'm going to be crazy.

i tried everything : 

- completed support email
- recreated the debugkeystore, updated the SHA (tried with SHA1 only, and then with SHA1 and SHA256)
- tried with others plugin versions
- recreated from scratch the project

Nothing is working.

**Comment by rubensdemelo** [comment]
> @epiphanatic i'm getting the same error too, i'm going to be crazy.
> 
> i tried everything :
> 
> * completed support email
> * recreated the debugkeystore, updated the SHA (tried with SHA1 only, and then with SHA1 and SHA256)
> * tried with others plugin versions
> * recreated from scratch the project
> 
> Nothing is working.

Did you update your Google Play Services ?

**Comment by epiphanatic** [comment]
I did.

**Comment by xero88** [comment]
I found a solution. See my answer https://github.com/flutter/flutter/issues/33393#issuecomment-510390858

**Comment by epiphanatic** [comment]
@xero88 omg, thank you soooo much!! That did it. Although like the person says, how are we supposed to figure this stuff out if they always leave out key things in the documentation? That's my one beef with Google (I love everything else about the ecosystem).

**Comment by xero88** [comment]
@epiphanatic I agree totally with you. I have always issues with Google documentation. Glad that the solution helped you !

**Comment by vishwajit76** [comment]
**If you use flutter channel platform**

In my case, I use 3rd party library in android and load all logic on MainActivty so flutter not handle the load on the app then I moved all logic on new activity and call by intent.

it worked for me.
make sure the load on MainActivty is not increasing.

**Comment by Joxxinton** [comment]
> @epiphanatic i'm getting the same error too, i'm going to be crazy.
> 
> 
> 
> i tried everything : 
> 
> 
> 
> - completed support email
> 
> - recreated the debugkeystore, updated the SHA (tried with SHA1 only, and then with SHA1 and SHA256)
> 
> - tried with others plugin versions
> 
> - recreated from scratch the project
> 
> 
> 
> Nothing is working. 
> 
> 
> 
> 

Same here🥺

**Comment by goc20** [comment]
> @epiphanatic I found a solution. See my answer [#33393 (comment)](https://github.com/flutter/flutter/issues/33393#issuecomment-510395178)

how much time did it took to verify your app??
