### ISSUE TITLE
I need a sliverWebview widget

### ISSUE THREAD

**Issue by terryyhl** [flutter/flutter#33306]
Hi 
i need a SliverWebView widget .
like this 
CustomScrollView(
   sliver:[
   sliverList(),
  sliverGrid(),
 sliverWebView()
]
)

same as #31243 
can support this wdiget for CustomScrollView or NestedScrollView?

**Comment by lizhuoyuan** [comment]
+1

**Comment by sky126** [comment]
me too

**Comment by timrijckaert** [comment]
Don't duplicate issues just vote for the original issue.

**Comment by iapicca** [comment]
Hi @terryyhl 
I see you linked and issue addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
