### ISSUE TITLE
The Text Field doesn't Support certain Input Methods on iOS

### ISSUE THREAD

**Issue by su27** [flutter/flutter#3331]
## Steps to Reproduce

I get the latest `material_gallery` demo running on my iPhone 5S, focus on the text field, it works fine with English keyboard, but when I switch the input method to Chinese, I can't input anything at all.
## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/su27/dev/flutter
    • Framework revision a5a34d9 (3 hours ago), engine revision c3504b5

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3, Build version 7D175

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.1
```

**Comment by abarth** [comment]
/cc @mpcomplete @tvolkert 

We probably need to implement another ObjC protocol to get these input methods.

**Comment by eseidelGoogle** [comment]
This may also relate to https://github.com/flutter/flutter/issues/7459.

**Comment by xster** [comment]
I know this is older but I'll merge into the other issue that had more details :)
#6939
