### ISSUE TITLE
iOS build failed, file plugin_scaffold-swift.h not found

### ISSUE THREAD

**Issue by joaowd** [flutter/flutter#33311]
I'm getting the following error when I try to build for iOS

```
Xcode's output:
↳
    /Users/joaopalma/Development/flutter/.pub-cache/hosted/pub.dartlang.org/plugin_scaffold-0.0.1/ios/Classes/PluginScaffoldPlugin.m:2:9: fatal error: 'plugin_scaffold/plugin_scaffold-Swift.h' file not found
    #import <plugin_scaffold/plugin_scaffold-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the precompiled application for the device.

```

**Comment by solaamy** [comment]
Hi, did you have any ideas about how to solve this issue? I run into the same issue right now and struggle with it for a long time

**Comment by joaowd** [comment]
Forgot how to solved this issues, but it is possible, you need to mess around with the pod files.

**Comment by solaamy** [comment]
Thanks in advance. It should be something related to obj-c and swift. But I am in a “vicious cycle” -----fixing this issue will lead to another one, fixing that one will lead back to this issue :-/

**Comment by joaowd** [comment]
Hey there,

Do [this](https://github.com/ko2ic/image_downloader/issues/9#issuecomment-471608482)

And also update your Xcode/cocoa pods

**Comment by joaowd** [comment]
yes i use

**Comment by solaamy** [comment]
OK, thank you for all your reply!
