### ISSUE TITLE
Recurring Stacktraces - message says to file a bug

### ISSUE THREAD

**Issue by irfantusneem** [flutter/flutter#33328]
I/flutter (28817): 
I/flutter (28817): SEVERE: 2019-05-24 17:37:52.194537: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞══════════════════════
I/flutter (28817): The following assertion was thrown during performLayout():
I/flutter (28817): RenderBox was not laid out: RenderPointerListener#bde77
I/flutter (28817): relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (28817): 'package:flutter/src/rendering/box.dart':
I/flutter (28817): Failed assertion: line 1665 pos 12: 'hasSize'
I/flutter (28817): 
I/flutter (28817): Either the assertion indicates an error in the framework itself,
I/flutter (28817): or we should provide substantially more information in this error
I/flutter (28817): message to help you determine and fix the underlying cause.
I/flutter (28817): In either case, please report this assertion by filing a bug on
I/flutter (28817): GitHub:
I/flutter (28817):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (28817): 
I/flutter (28817): When the exception was thrown, this was the stack:
I/flutter (28817): #2      RenderBox.size (package:flutter/src/rendering/box.dart:1665:12)
I/flutter (28817): #3      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:106:20)
I/flutter (28817): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (28817): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (28817): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (28817): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (28817): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (28817): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #15     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter (28817): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #17     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (28817): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #19     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (28817): #20     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
I/flutter (28817): #21     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (28817): #22     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (28817): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (28817): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (28817): #27     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter (28817): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (28817): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (28817): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (28817): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (28817): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (28817): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (28817): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (28817): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #43     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3074:14)
I/flutter (28817): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter (28817): #45     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (28817): #46     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1497:7)
I/flutter (28817): #47     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter (28817): #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter (28817): #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (28817): #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (28817): #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (28817): #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (28817): #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter (28817): #54     CoreActivityZoneImpl._run.<anonymous closure> (package:ads.acx2.tracking.activity.core.zone/zone.dart:201:18)
I/flutter (28817): #57     CoreActivityZoneImpl._run (package:ads.acx2.tracking.activity.core.zone/zone.dart:198:19)
I/flutter (28817): #60     _invoke (dart:ui/hooks.dart:220:10)
I/flutter (28817): #61     _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter (28817): (elided 6 frames from class _AssertionError and package dart:async)
I/flutter (28817): 
I/flutter (28817): The following RenderObject was being processed when the exception was fired:
I/flutter (28817):   RenderSemanticsGestureHandler#8c05c relayoutBoundary=up8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter (28817):   creator: _GestureSemantics ←
I/flutter (28817):     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#8dccc]
I/flutter (28817):     ← Listener ← _ScrollableScope ←
I/flutter (28817):     _ScrollSemantics-[GlobalKey#60bc2] ← RepaintBoundary ←
I/flutter (28817):     CustomPaint ← RepaintBoundary ←
I/flutter (28817):     NotificationListener<ScrollNotification> ←
I/flutter (28817):     GlowingOverscrollIndicator ← Scrollable ←
I/flutter (28817):     SingleChildScrollView-[<'card_container'>] ← ⋯
I/flutter (28817):   parentData: <none> (can use size)
I/flutter (28817):   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=507.4)
I/flutter (28817):   size: MISSING
I/flutter (28817):   gestures: <none>
I/flutter (28817): This This RenderObject had the following descendants (showing up to depth 5):
I/flutter (28817):     child: RenderPointerListener#bde77 relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (28817):       child: RenderSemanticsAnnotations#0633f relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (28817):         child: RenderIgnorePointer#6ce05 relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (28817):           child: _RenderSingleChildViewport#59e02 relayoutBoundary=up12 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (28817):             child: RenderPadding#ef848 relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (28817): ═════════════════════════════════════════════════════════════════

```
```

**Comment by iapicca** [comment]
Hi @irfantusneem 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
