### ISSUE TITLE
Live samples in PlayStore

### ISSUE THREAD

**Issue by MikeMitterer** [flutter/flutter#3332]
Please provide the Flutter samples from https://github.com/flutter/flutter/tree/master/examples as live-Samples in PlayStore.

If someone is curious how Flutter works the first thing he/she wants is an App that can be easily installed on a device. The first step to Flutter/Dart must be as small as possible. If the first hurdle is to install a whole dev environment just to try something out then this step is way to high...

**Comment by sethladd** [comment]
Thanks for the feedback! We're working on it. Agreed, we should make it easier to try a Flutter app.

**Comment by sethladd** [comment]
Cleaning up the issues, and I'm going to close this. We aim to make it easier to try demo/sample Flutter apps. Thanks again for the suggestion!
