### ISSUE TITLE
Syncing to device taking forever

### ISSUE THREAD

**Issue by virtz** [flutter/flutter#33320]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by naeem-hasan** [comment]
Please tell us about your hardware. How much RAM have you got?
Have you tried canceling and relaunching the app?

**Comment by virtz** [comment]
I was using a plug-in that threw an uncaught exception. Thank you

**Comment by naeem-hasan** [comment]
If your issue is resolved, please close it!

**Comment by iapicca** [comment]
Hi @virtz 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
