### ISSUE TITLE
Transform scale issue

### ISSUE THREAD

**Issue by silverbuggy** [flutter/flutter#33335]
## Steps to Reproduce
1. Here's a sample dart file and screenshot that shows the bug: https://gist.github.com/silverbuggy/e191e449b1076b215db742267a5392ac

The scale is 0.5, and child dimensions are 800 width by 1000 height.

2. Render that widget in a page

Expected:
The child container should be scaled by 0.5 to 400 width by 500 height, in effect filling out the device width and more than half of the device height.

Actual:
The child container is scaled to exactly half of the device width and half of the device height, because the scale factor is 0.5. 

If you set the container width and height to values smaller than the screen width and height, respectively, then scaling works correctly. It appears that the scaling is bounded by the screen dimensions. If I use big enough width and height for the container, I would expect for the blue widget to fill the screen entirely but the max it will go is half width and half height.

This bug repros for other values of scale < 1.0. It also repros if using Matrix4 format such as:
transform: Matrix4.diagonal3Values(0.7, 0.7, 1.0),
It also repros if I use an Image instead of a Container for the child to transform.

**Comment by iapicca** [comment]
Hi @silverbuggy 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your updated `flutter doctor -v`?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
