### ISSUE TITLE
'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#33347]
PR #31978 caused some code that I've been working on to trigger an assertion failure in `package:flutter/src/rendering/sliver_grid.dart`:

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════                                                            
The following assertion was thrown during performLayout():                      
'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14:                                                                            
'childParentData.index == index': is not true.  
```

Here's a test that will trigger the assertion failure:

```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

class MyGridView extends StatelessWidget {
  const MyGridView(this.rowCount, this.columnCount);

  final int rowCount;
  final int columnCount;

  @override
  Widget build(BuildContext context) {
    final items = <Text>[];
    // Generate a list with items numbered in column-major order.
    for (int row = 0; row < rowCount; row += 1) {
      for (int col = 0; col < columnCount; col += 1) {
        final itemNumber = col * rowCount + row;
        final s = 'item-$itemNumber';
        items.add(Text(
          s,
          key: Key(s),
        ));
      }
    }
    items.removeLast();

    return Directionality(
      textDirection: TextDirection.ltr,
      child: GridView.count(
        crossAxisCount: columnCount,
        children: items,
      ),
    );
  }
}

void main() {
  testWidgets(
    'Rearranging GridView items works',
    (tester) async {
      await tester.pumpWidget(MyGridView(2, 2));
      await tester.pumpWidget(MyGridView(3, 2));
    },
  );
}
```

The relevant criteria for triggering the assert seem to be:

* A `GridView` where the number of children is not an even multiple of the number of columns. (The test passes if `items.removeLast()`is removed.)
* Each of the `GridView`'s children has a `Key`. (The test passes if the `key` named argument is removed when constructing each `Text` widget.)
* The number of children in the `GridView` changes. (The test passes if `testWidgets` is called with identical `MyGridView` instances.)
* The `Key`s are not stable when the number of children changes. (The test passes if the `items` list is built in row-major order instead of column-major.)

```
[✓] Flutter (Channel unknown, v1.6.4-pre.3, on Linux, locale en_US.UTF-8)      
    • Flutter version 1.6.4-pre.3 at /home/jamesdlin/git/flutter/flutter       
    • Framework revision 1bd85dd6c2 (5 days ago), 2019-05-23 17:05:29 -0700    
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)                      
```

**Comment by chunhtai** [comment]
The pr did change the behavior when children has keys, in a good way. What happen here is the children got moved around with gap in the middle, those gap supposed be filled out during the perform layout. SliverList does fill out the gap while SliverGrid and SliverFixExtentList does not which cause this crash.

Prior to the pr, things just get destroyed and reinitiate every time without any reusing, that is why things are ok back then.

I will put up a pr soon
