### ISSUE TITLE
Add docs to the headers in shell/common

### ISSUE THREAD

**Issue by xster** [flutter/flutter#33358]
I think the team is big enough that some docs on those c++ classes would make it easier to work on the engine :D

cc @cbracken

**Comment by pedromassangocode** [comment]
@gaaclarke can you confirm that https://github.com/flutter/engine/pull/9303 fixes this issue?

**Comment by cbracken** [comment]
There've been a ton of patches adding documentation over the past year and this was on the engine roadmap earlier in the year. Things look pretty good at the moment. Closing.
