### ISSUE TITLE
flutter trace --stop no longer works on Android

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3335]
Broke as of https://github.com/flutter/engine/commit/09972ad11cd9323e3e45b389db869ff5c8604641

I haven't tested on iOS, may be broken there too.
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L385
is the line with the bad assumption in `flutter trace --stop`

I suspect we should update it to pull the trace over observatory instead of via a test file?  @johnmccutchan or @chinmaygarde would know?

FYI @jason-simmons

**Comment by eseidelGoogle** [comment]
I ran into this while trying to use https://github.com/flutter/flutter/blob/master/dev/profile_startup.dart

**Comment by jason-simmons** [comment]
This should be fixed now
