### ISSUE TITLE
Weird assert in ScrollableState.didUpdateScrollBehavior 

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#3336]
2:59:47.857: Stack trace:
12:59:47.860: #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
12:59:47.863: #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
12:59:47.865: #2      ScrollableState.didUpdateScrollBehavior (package:flutter/src/widgets/scrollable.dart:391)
12:59:47.868: #3      _ScrollableViewportState._handlePaintOffsetUpdateNeeded (package:flutter/src/widgets/scrollable.dart:700)
12:59:47.871: #4      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:298)
12:59:47.874: #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1246)
12:59:47.877: #6      RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
12:59:47.880: #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1246)
12:59:47.882: #8      RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
12:59:47.885: #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1246)

**Comment by apwilson** [comment]
Flutter version: c40f4cfedb11e3fef3618e1a57c70275e8fa1a64

**Comment by Hixie** [comment]
We need a little more from the exception log please. :-)

**Comment by Hixie** [comment]
This stack looks like https://github.com/flutter/flutter/issues/3492
