### ISSUE TITLE
[json_rpc_2] "Method not found" running flutter_driver 

### ISSUE THREAD

**Issue by SagarBShinde** [flutter/flutter#33372]
'Method not found' error for JSON RPC Client  while running the Integration test from Android Studio
## Steps to Reproduce
1. Create an Integration Test for Flutter as per Steps https://flutter.dev/docs/cookbook/testing/integration/introduction

2. Create a run configuration for running/debugging the test as per steps in
https://stackoverflow.com/questions/53361718/how-to-automate-flutter-integration-testing-command/56286951#56286951

3. Expected : The test should run
Actual: getting following error message

00:00 +0: Flutter Driver demo (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:55319/L_Bm--V4Kjg=/
[trace] FlutterDriver: Isolate found with number: 283666305
[trace] FlutterDriver: Isolate is not paused. Assuming application is ready.
00:00 +0 -1: Flutter Driver demo (setUpAll) [E]
  JSON-RPC error -32601 (method not found): Method not found
  package:json_rpc_2/src/client.dart 110:64          Client.sendRequest
  package:json_rpc_2/src/peer.dart 68:15             Peer.sendRequest
  package:vm_service_client/src/scope.dart 64:23     Scope.sendRequestRaw

## Logs

00:00 +0: Flutter Driver demo (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:56149/-ubSQLu2cxE=/ 
[trace] FlutterDriver: Isolate found with number: 6401091
[trace] FlutterDriver: Isolate is not paused. Assuming application is ready.
00:00 +0 -1: Flutter Driver demo (setUpAll) [E]
  JSON-RPC error -32601 (method not found): Method not found
  package:json_rpc_2/src/client.dart 110:64          Client.sendRequest
  package:json_rpc_2/src/peer.dart 69:15             Peer.sendRequest
  package:vm_service_client/src/scope.dart 64:23     Scope.sendRequestRaw
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                       _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23            _asyncThenWrapperHelper
  package:flutter_driver/src/driver/driver.dart      FlutterDriver.connect
  test_driver\app_test.dart 11:36                    main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                       _CustomZone.registerUnaryCallback
  dart:async/zone.dart 967:22                        _CustomZone.bindUnaryCallbackGuarded
  dart:async/future.dart 530:34                      Future.doWhile
  dart:async/future.dart 490:12                      Future.forEach
  package:test_api/src/backend/declarer.dart 291:36  Declarer._setUpAll.<fn>.<fn>
  dart:async/zone.dart 1124:13                       _rootRun
  dart:async/zone.dart 1021:19                       _CustomZone.run
  dart:async/zone.dart 1516:10                       _runZoned
  dart:async/zone.dart 1463:12                       runZoned
  package:test_api/src/backend/declarer.dart 291:14  Declarer._setUpAll.<fn>
  package:test_api/src/backend/invoker.dart 400:25   Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                       _CustomZone.registerCallback
  dart:async/zone.dart 962:22                        _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                        new Timer
  dart:async/timer.dart 87:9                         Timer.run
  dart:async/future.dart 174:11                      new Future
  package:test_api/src/backend/invoker.dart 399:21   Invoker._onRun.<fn>.<fn>.<fn>
  
  DriverError: Failed to fulfill GetHealth due to remote error
  Original error: JSON-RPC error -32601 (method not found): Method not found
  Original stack trace:
  package:json_rpc_2/src/client.dart 110:64          Client.sendRequest
  package:json_rpc_2/src/peer.dart 69:15             Peer.sendRequest
  package:vm_service_client/src/scope.dart 64:23     Scope.sendRequestRaw
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                       _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23            _asyncThenWrapperHelper
  package:flutter_driver/src/driver/driver.dart      FlutterDriver.connect
  test_driver\app_test.dart 11:36                    main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                       _CustomZone.registerUnaryCallback
  dart:async/zone.dart 967:22                        _CustomZone.bindUnaryCallbackGuarded
  dart:async/future.dart 530:34                      Future.doWhile
  dart:async/future.dart 490:12                      Future.forEach
  package:test_api/src/backend/declarer.dart 291:36  Declarer._setUpAll.<fn>.<fn>
  dart:async/zone.dart 1124:13                       _rootRun
  dart:async/zone.dart 1021:19                       _CustomZone.run
  dart:async/zone.dart 1516:10                       _runZoned
  dart:async/zone.dart 1463:12                       runZoned
  package:test_api/src/backend/declarer.dart 291:14  Declarer._setUpAll.<fn>
  package:test_api/src/backend/invoker.dart 400:25   Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                       _CustomZone.registerCallback
  dart:async/zone.dart 962:22                        _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                        new Timer
  dart:async/timer.dart 87:9                         Timer.run
  dart:async/future.dart 174:11                      new Future
  package:test_api/src/backend/invoker.dart 399:21   Invoker._onRun.<fn>.<fn>.<fn>
  
      
  package:flutter_driver/src/driver/driver.dart 424:7   FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22:43                     _Completer.completeError
  dart:async-patch/async_patch.dart 40:18               _AsyncAwaitCompleter.completeError
  package:flutter_driver/src/driver/driver.dart         FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1062:19                          _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 86:23               _asyncErrorWrapperHelper
  package:flutter_driver/src/driver/driver.dart         FlutterDriver._sendCommand
  package:flutter_driver/src/driver/driver.dart 447:34  FlutterDriver.checkHealth
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                          _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23               _asyncThenWrapperHelper
  package:flutter_driver/src/driver/driver.dart         FlutterDriver.connect
  test_driver\app_test.dart 11:36                       main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                          _CustomZone.registerUnaryCallback
  dart:async/zone.dart 967:22                           _CustomZone.bindUnaryCallbackGuarded
  dart:async/future.dart 530:34                         Future.doWhile
  dart:async/future.dart 490:12                         Future.forEach
  package:test_api/src/backend/declarer.dart 291:36     Declarer._setUpAll.<fn>.<fn>
  dart:async/zone.dart 1124:13                          _rootRun
  dart:async/zone.dart 1021:19                          _CustomZone.run
  dart:async/zone.dart 1516:10                          _runZoned
  dart:async/zone.dart 1463:12                          runZoned
  package:test_api/src/backend/declarer.dart 291:14     Declarer._setUpAll.<fn>
  package:test_api/src/backend/invoker.dart 400:25      Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                          _CustomZone.registerCallback
  dart:async/zone.dart 962:22                           _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                           new Timer
  dart:async/timer.dart 87:9                            Timer.run
  dart:async/future.dart 174:11                         new Future
  package:test_api/src/backend/invoker.dart 399:21      Invoker._onRun.<fn>.<fn>.<fn>
  
00:00 +0 -1: Flutter Driver demo (tearDownAll)
00:00 +0 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

Process finished with exit code 255
-->
Flutter Doctor Output

[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.503], locale en-IN)
    • Flutter version 1.5.4-hotfix.2 at D:\Softwares\flutter
    • Framework revision 7a4c33425d (4 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\sagar.shinde\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\sagar.shinde\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.4
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270

[√] VS Code (version 1.34.0)
    • VS Code at C:\Users\sagar.shinde\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.2

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
![AS_run_configpng](https://user-images.githubusercontent.com/21018295/58384908-7a358e00-8006-11e9-8868-ba21b7b849c2.png)

**Comment by chenyang88** [comment]
how do you debug the driver test? when I update flutter version, I cross the problem, before the update, I use `127.0.0.1:8898` it works fine, but I update later, it changes to `127.0.0.1:8898/xxxlajg=l`, and it still can't connect the VM, what wrong.

**Comment by zedbahn** [comment]
I seem to experience the same issue with the exact same error message. One minor difference in my setup, though, is that (in VS Code launch.json) I have used `"--disable-service-auth-codes"` in args for launching the main.dart:

    "args": [
        "--observatory-port",
        "8888",
        "--disable-service-auth-codes"
    ],
in order to (as I understand) not use the authentication code generated and shared by the VM service via stdout ([see here](https://github.com/dart-lang/sdk/issues/36575)).

But when starting the debugger for the main.dart and then starting the debugger for the main_test.dart, the `RpcException (JSON-RPC error -32601 (method not found): Method not found)` exception is thrown.

Flutter Doctor output:
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [version 6.1.7601], locale da-DK)
    • Flutter version 1.7.8+hotfix.4 at C:\flutter
    • Framework revision 20e59316b8 (2 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\extaen\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Users\extaen\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code, 64-bit edition (version 1.36.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by pradarttana-sharechat** [comment]
ran through the same issue. please give a work around

**Comment by iapicca** [comment]
Hi @SagarBShinde 
are you still experiencing this issue with the latest version of Flutter?
If so could you please provide your updated `flutter doctor -v`?
Thank you

**Comment by kmanpro** [comment]
I am experiencing the same issue.
Here is my flutter doctor command output


```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
    • Flutter version 1.9.1+hotfix.4 at C:\devel\flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\devel\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.38.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```
My VSCode helpers are as follows:

```
        {
            "name": "Flutter: Integration test",
            "request": "launch",
            "type": "dart",
            "args": ["--observatory-port", "8052", "--disable-service-auth-codes"],
            "program": "lib/main.dart",
            "flutterMode": "debug"
        },
        {
            "name": "Attach: Debug Integration test",
            "request": "launch",
            "type":"dart",
            "env": {
              "VM_SERVICE_URL": "http://127.0.0.1:8052/"
            },
            "program": "test_driver/app_test.dart",
            "flutterMode": "debug",
        }
```

**Comment by shike1116** [comment]
> , but I update later, it changes to `127.0.0.1:8898/xxxlajg=l`, and it still can't connect the VM, what wrong.

Have you solved it?

**Comment by iapicca** [comment]
Thank you @kmanpro

**Comment by pvegh** [comment]
I am seeing this in Channel stable, v1.12.13+hotfix.8

**Comment by iapicca** [comment]
Hi all
for issue with the plugin [json_rpc_2](https://pub.dev/packages/json_rpc_2)
please open an issue in the  dedicated [github](https://github.com/dart-lang/json_rpc_2/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
