### ISSUE TITLE
I am trying to make paging in flutter in which i have customscrollview and scrollcontroller paging is working perfect in all emulators and devices but not in android 8.1 devices

### ISSUE THREAD

**Issue by cimplesid** [flutter/flutter#33371]
i am calling the get more data function as 

```
 if (scrollController.offset >= scrollController.position.maxScrollExtent &&
        !scrollController.position.outOfRange) {
      getMoreData();
    }


```
works perfectly in other devices rather than android 8.1 tested device redmi 6 pro. In this device only first page is shown and no more scrolling happens

**Comment by TahaTesser** [comment]
Hi @cimplesid 
Are you still experiencing this issue?
Thank you

**Comment by VladyslavBondarenko** [comment]
Closing for now,
@cimplesid please comment if the issue still persist and I'll reopen it
Thank you

**Comment by cimplesid** [comment]
no, I am over it thank you it is ok to be closed.
