### ISSUE TITLE
有跟我感觉一样的吗？

### ISSUE THREAD

**Issue by luneice** [flutter/flutter#33386]
## Use case
Material Design 在某些方面却是很不错，作为谷歌UI的标准，但是在某些方面实在无法忍受，尤其是在UI方面，有些地方确实丑的没法接受，但是却让开发者不得不遵循它的某些设计规范和标准。我只想用自己的设计规范和标准开发自己的程序，有哪些可取的办法？

**Comment by stuartmorgan** [comment]
This seems to be a duplicate of #33385
