### ISSUE TITLE
Add golden tests for disabled CupertinoTextField

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#33380]
Add golden tests for disabled CupertinoTextField. Related: #32974

**Comment by HansMuller** [comment]
Tests for PR #32974 should be part of that PR. 

It's possible to verify that a paint method is clipping correct without writing a golden image test. See for example: https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/ink_paint_test.dart#L49
