### ISSUE TITLE
On KitKat, apps are off the top of the screen

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3338]
Looks like on KitKat we don't get the right top padding, which causes the toolbar to render under the navigatior bar.

**Comment by eseidelGoogle** [comment]
Possibly related to this code?
https://github.com/flutter/engine/blob/master/sky/shell/platform/android/org/domokit/sky/shell/SkyActivity.java#L65

**Comment by eseidelGoogle** [comment]
Or this: https://github.com/flutter/engine/blob/master/sky/shell/platform/android/io/flutter/view/FlutterView.java#L319?  Not sure.

**Comment by eseidelGoogle** [comment]
I believe @jason-simmons fixed this last week?

**Comment by jason-simmons** [comment]
Yes, this should be fixed now
