### ISSUE TITLE
Flutter Doctor -v VersionCheckError: VersionCheckError:

### ISSUE THREAD

**Issue by theromie** [flutter/flutter#33388]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

VersionCheckError: VersionCheckError: Command exited with code 128: git log -n 1 --pretty=format:%ad --date=iso
Standard error: fatal: bad config line 2 in file .git/config

**Comment by kangwang1988** [comment]
@theromie 
Please follow steps below:
```shell
cd your-flutter-repo (it's supposed to be a valid git repository)
 git log -n 1 --pretty=format:%ad --date=iso
cat .git/config
```
It seems the git repo is broken now. And stackoverflow maybe a better place to resolve this kind of support questions.
