### ISSUE TITLE
SliverAppBar: provide option to delay compression/slide

### ISSUE THREAD

**Issue by derolf** [flutter/flutter#33398]
I have a floating SliverAppBar, some image, and a SliverList.

Right now, when the user scrolls up, the AppBar immediately gets compressed/slides-up.

It would be nice to let the image slide under the AppBar and only once the SliverList bumps into the AppBar to make it start compressing/sliding.

This could be done by adding some kind of compressible, transparent white space after the SliverAppBar.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Hixie** [comment]
This is possible in general if you write enough code, but I don't think it's something we will implement as part of the core framework.
