### ISSUE TITLE
[web]: How to find an example of AssetManifest.json?

### ISSUE THREAD

**Issue by mirkancal** [flutter/flutter#33402]
I get a warning in console with my flutter_web app. 

> Asset manifest does not exist at `assets/AssetManifest.json` – ignoring.

I want to add that file, how can I find example of it?

My app is on Github pages and I'm using chrome to open it. 

Version 74.0.3729.169 (Official Build) (64-bit)

**Edit**: I've added AssetManifest.json file which consist only `{}`. It solved my problem, but what to put in AssetManifest.json? I couldn't find any guide about it.

**Comment by superciccio** [comment]
that's the file
https://github.com/flutter/flutter_web/blob/master/examples/gallery/web/assets/FontManifest.json

**Comment by mirkancal** [comment]
It's FontManifest.json. Is it same?

**Comment by superciccio** [comment]
yep
https://github.com/flutter/flutter_web/blob/master/docs/migration_guide.md#webassetsfontmanifestjson-optional

**Comment by mirkancal** [comment]
I can't see any indication of that. Where it says exactly that AssetManifest.json and FontManifest.json files are the same?

**Comment by caztial** [comment]
I think without the AssetManifest.json release build images are not available

**Comment by Levi-Lesches** [comment]
Am I supposed to replace FontManifest.json with AssetManifest.json? Or do I put the same content in both?

**Comment by abinmittu** [comment]
Sample AssetManifest.json

```
{
  "assets": [
    "images/my_image_1",
    "images/my_image_2"
  ]
}
```

Directory Structure
```
web
    - assets
        - fonts
        - images
            - my_image_1
            - my_image_2
        - AssetManifest.json
        - FontManifest.json
```

**Comment by Levi-Lesches** [comment]
Thanks so much

**Comment by shivamenrichai** [comment]
can u give some example to use in dart file, not working web build

**Comment by Levi-Lesches** [comment]
What do you mean by Dart file? Like, how to refer to the assets?

**Comment by jonahwilliams** [comment]
If you're using the flutter tool to build you application the asset manifest is generated automatically. For more information see flutter.dev/web. I'm closing the issue since it is no longer relevant.

**Comment by NothingWorksToday** [comment]
> If you're using the flutter tool to build you application the asset manifest is generated automatically.

Sorry to comment on such an old issue. Does it still get generated? Where is it placed - in the `rootBundle`? How can I access it? So far I accessed my other assets with
```
content = await rootBundle.loadString('assets/my_asset_file.json');
```
Is it the same for `AssetManifest.json`? Like
```
content = await rootBundle.loadString('assets/AssetManifest.json');
```
