### ISSUE TITLE
Text Widgets use more horizontal space during flutter test than they should

### ISSUE THREAD

**Issue by MisterJimson** [flutter/flutter#33404]
## Steps to Reproduce
1. Build a widget that contains a Text widget that doesn't have much room before it would overflow
2. Write a Widget Test for this widget 
3. Run test with both `flutter test` and `flutter run test/file_name.dart`

`flutter test` will fail with a RenderFlex overflow, `flutter run test/file_name.dart` will pass.

Minimal reproducible sample here: https://github.com/MisterJimson/flutter-text-scaling-widget-tests
Single commit that demonstrates the bug: https://github.com/MisterJimson/flutter-text-scaling-widget-tests/commit/f17c50bb6edf94e4e8f09e3f35f71bc3f416ba7b

### Workaround
Change textScaleFactorTestValue to workaround until this is fixed.
```
 final TestWidgetsFlutterBinding binding =
        TestWidgetsFlutterBinding.ensureInitialized();
    if (Platform.environment.containsKey('FLUTTER_TEST')) {
      binding.window.textScaleFactorTestValue = 0.49;
    }

//do test
```

## Logs
```
[✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-CA)
    • Flutter version 1.5.4-hotfix.2 at /Users/jrai/dev/flutter
    • Framework revision 7a4c33425d (4 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jrai/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jrai/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • iPad Air 2 • B03E7C5C-5D9B-4024-AEBF-DD55BF378439 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

```

**Comment by MisterJimson** [comment]
Following up for latest stable release, this is still the same on  v1.7.8+hotfix.4. The same workaround works.

**Comment by MisterJimson** [comment]
I've also discovered the value needed to workaround is not always `0.49` as I previously thought. The value seems to be different for different contents of the text. Sample is updated to demo this.

**Comment by jonahwilliams** [comment]
This is not a bug, the flutter tester uses the Ahem font by default. This font is a bit wider than normal because all the characters are square. see https://github.com/Kozea/Ahem.

If you want to depend on a particular font size in tests, an approach you could take is loading it yourself. see https://github.com/flutter/flutter/issues/17700 for more details
