### ISSUE TITLE
Android App bundle doesn't work on 64 bit devices ? (master channel)

### ISSUE THREAD

**Issue by KirolousNashaat** [flutter/flutter#33424]
so the app bundle size now is almost doubled ( 16mb - old one was ~9.7 )
( because of 64 bit I think ) - and my apk is 9.6 (32-bit default) 
tried to publish the app on playstore
it simply show the splashscreen (defined with AndroidManifest) and then it closes
this happened on Samsung Note 9 - Honor Play devices ( the only ones i tested )
publishing the app with normal 32 bit apk works fine on all devices

btw this problem happened once to me before with the official 'Flutter Gallery'
Related : https://github.com/flutter/flutter/issues/30239
but it was fixed without me doing anything ,, idk how !!
but it's the same effect ,, it doesnt only affect me , it affects my users too now

```
[ظê?] Flutter (Channel dev, v1.6.3, on Microsoft Windows [Version 6.3.9600], locale en-US)
    ظت Flutter version 1.6.3 at E:\Setups\FLUTTER\flutter
    ظت Framework revision bc7bc94083 (5 days ago), 2019-05-23 10:29:07 -0700
    ظت Engine revision 8dc3a4cde2
    ظت Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

[ظê?] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ظت Android SDK at E:\Setups\Android
    ظت Android NDK location not configured (optional; useful for native profiling support)
    ظت Platform android-28, build-tools 28.0.3
    ظت ANDROID_HOME = E:\Setups\Android
    ظت Java binary at: E:\Sources\android-studio-ide-181.4987877-windows\android-studio\jre\bin\jav
a
    ظت Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ظت All Android licenses accepted.

[!] Android Studio (version 3.2)
    ظت Android Studio at E:\Sources\android-studio-ide-181.4987877-windows\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    ظت Dart plugin version 181.5656
    ظت Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[ظê?] IntelliJ IDEA Community Edition (version 2019.1)
    ظت IntelliJ at E:\Setups\JetBrains\IntelliJ IDEA Community Edition 2019.1.1
    ظت Flutter plugin version 35.3.3
    ظت Dart plugin version 191.7141.49

[ظê?] Connected device (2 available)
    ظت Windows ظت Windows ظت windows-x64 ظت Microsoft Windows [Version 6.3.9600]
    ظت web     ظت web     ظت web         ظت web

! Doctor found issues in 1 category.
```

**Comment by mrcoalp** [comment]
@KirolousNashaat I think that, for now, the only option is to create two separate apk, both for 32 and 64.

1. run `flutter build apk --release --target-platform=android-arm`
2. upload 32bit version to play store
3. increment `versionCode` in `pubspec.yaml`
4. run `flutter build apk --release --target-platform=android-arm64`
5. upload 64bit version to play store

Play Store will deploy app accordingly to device architecture this way.

See https://github.com/flutter/flutter/issues/18494

**Comment by hayderux** [comment]
Same problem with me after they announced support for 64&32 bit

**Comment by KirolousNashaat** [comment]
> @KirolousNashaat I think that, for now, the only option is to create two separate apk, both for 32 and 64.
> 
> 1. run `flutter build apk --release --target-platform=android-arm`
> 2. upload 32bit version to play store
> 3. increment `versionCode` in `pubspec.yaml`
> 4. run `flutter build apk --release --target-platform=android-arm64`
> 5. upload 64bit version to play store
> 
> Play Store will deploy app accordingly to device architecture this way.
> 
> See #18494



> Same problem with me after they announced support for 64&32 bit

but they already merged this : https://github.com/flutter/flutter/pull/32787
it should have worked with appbundle ? or i am missing something ?

**Comment by mrcoalp** [comment]
> but they already merged this : #32787
> it should have worked with appbundle ? or i am missing something ?

It should... But apparently it is not working. :/ Or maybe I'm also missing something!

**Comment by KirolousNashaat** [comment]
@mklim I dont know if i am supposed to mention you , but u are the one reviewed this PR , but it's not working and instead of making 64 bit devices run 32 bit apps, it breaks the app, it just flashes the splash and doesnt work (64bit devices, didnt test on 32bit but should work fine i think ), it should be reverted/fixed ?

**Comment by mklim** [comment]
cc @blasten 

Thanks for the bug report.

Can anyone affected by their app closing immediately opening it post the error logs on this bug from the time their app closes?

**Comment by KirolousNashaat** [comment]
i don't but if u are asking about someway to test it without uploading to the playstore ?
there is tool to generate apk(s) from the appbundle to test it

Docs:
https://developer.android.com/studio/command-line/bundletool
Github:
https://github.com/google/bundletool/releases

**Comment by mrcoalp** [comment]
> cc @blasten
> 
> Thanks for the bug report.
> 
> Can anyone affected by their app closing immediately opening it post the error logs on this bug from the time their app closes?

@mklim is this enough?
```
05-29 09:16:02.106  7511  7511 E flutter : [ERROR:flutter/runtime/dart_vm_data.cc(19)] VM snapshot invalid and could not be inferred from settings.
05-29 09:16:02.106  7511  7511 E flutter : [ERROR:flutter/runtime/dart_vm.cc(241)] Could not setup VM data to bootstrap the VM from.
05-29 09:16:02.107  7511  7511 E flutter : [ERROR:flutter/runtime/dart_vm_lifecycle.cc(89)] Could not create Dart VM instance.
05-29 09:16:02.107  7511  7511 F flutter : [FATAL:flutter/shell/common/shell.cc(218)] Check failed: vm. Must be able to initialize the VM.
05-29 09:16:02.107  7511  7511 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 7511 (gmob4production)
05-29 09:16:02.107   382   382 W         : debuggerd: handling request: pid=7511 uid=10212 gid=10212 tid=7511
05-29 09:16:02.172  7533  7533 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-29 09:16:02.172  7533  7533 F DEBUG   : Build fingerprint: 'HUAWEI/VNS-L31/HWVNS-H:7.0/HUAWEIVNS-L31/C33B370:user/release-keys'
05-29 09:16:02.172  7533  7533 F DEBUG   : Revision: '0'
05-29 09:16:02.172  7533  7533 F DEBUG   : ABI: 'arm64'
05-29 09:16:02.173  7533  7533 F DEBUG   : pid: 7511, tid: 7511, name: gmob4production  >>> com.beanstalkti.ggmob4production <<<
05-29 09:16:02.173  7533  7533 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
05-29 09:16:02.175  7533  7533 F DEBUG   : Abort message: '[FATAL:flutter/shell/common/shell.cc(218)] Check failed: vm. Must be able to initialize the VM.    
05-29 09:16:02.175  7533  7533 F DEBUG   : '
05-29 09:16:02.175  7533  7533 F DEBUG   :     x0   0000000000000000  x1   0000000000001d57  x2   0000000000000006  x3   0000000000000008
05-29 09:16:02.175  7533  7533 F DEBUG   :     x4   0000000000000034  x5   0000000000008000  x6   00000073a7788000  x7   0000000000000000
05-29 09:16:02.175  7533  7533 F DEBUG   :     x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  0000000000000001
05-29 09:16:02.175  7533  7533 F DEBUG   :     x12  ffffffffffffffff  x13  0000000000000000  x14  0000000000000000  x15  0001985f43dee35c
05-29 09:16:02.175  7533  7533 F DEBUG   :     x16  00000073a4514ec8  x17  00000073a44bdc38  x18  00000000ffffffff  x19  00000073a783bb40
05-29 09:16:02.175  7533  7533 F DEBUG   :     x20  0000000000000006  x21  00000073a783ba98  x22  0000000000000009  x23  000000739bc0caa0
05-29 09:16:02.175  7533  7533 F DEBUG   :     x24  00000073867db150  x25  0000000000000000  x26  00000073a38a1a98  x27  4c7e0f32ef2717fd
05-29 09:16:02.175  7533  7533 F DEBUG   :     x28  0000000000000000  x29  0000007fced42f30  x30  00000073a44bb0e0
05-29 09:16:02.175  7533  7533 F DEBUG   :     sp   0000007fced42f10  pc   00000073a44bdc40  pstate 0000000060000000
05-29 09:16:02.178  7533  7533 F DEBUG   : 
05-29 09:16:02.178  7533  7533 F DEBUG   : backtrace:
05-29 09:16:02.178  7533  7533 F DEBUG   :     #00 pc 000000000006bc40  /system/lib64/libc.so (tgkill+8)
05-29 09:16:02.178  7533  7533 F DEBUG   :     #01 pc 00000000000690dc  /system/lib64/libc.so (pthread_kill+64)
05-29 09:16:02.178  7533  7533 F DEBUG   :     #02 pc 0000000000023e68  /system/lib64/libc.so (raise+24)
05-29 09:16:02.178  7533  7533 F DEBUG   :     #03 pc 000000000001c8ec  /system/lib64/libc.so (abort+52)
05-29 09:16:02.178  7533  7533 F DEBUG   :     #04 pc 000000000001d644  /data/app/com.beanstalkti.ggmob4production-1/split_config.arm64_v8a.apk (offset 0xd4b0
00)
```

**Comment by angel1st** [comment]
@mrcoalp - I wonder if this one is not somehow related to #31922?

**Comment by blasten** [comment]
This issue is related to https://github.com/flutter/flutter/issues/31922. I'm closing this bug to track it there. Thanks!
