### ISSUE TITLE
[local_auth] Document that local_auth requires a Fragment activity

### ISSUE THREAD

**Issue by pythoneer** [flutter/flutter#33429]
## Steps to Reproduce

Create a new Flutter Application:

```dart
import 'package:flutter/material.dart';

import 'package:local_auth/local_auth.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, }) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {

    return Scaffold(

      body: Center(
        child: Column(

          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '4',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          _checkBiometric();
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  void _checkBiometric() async {
    // check for biometric availability
    final LocalAuthentication auth = LocalAuthentication();
    bool canCheckBiometrics = false;
    try {
      canCheckBiometrics = await auth.canCheckBiometrics;
    } catch (e) {
      print("error biometrics $e");
    }

    print("biometric stuff is available: $canCheckBiometrics");

    // enumerate biometric technologies
    List<BiometricType> availableBiometrics;
    try {
      availableBiometrics = await auth.getAvailableBiometrics();
    } catch (e) {
      print("error enumerate biometrics $e");
    }

    print("following biometrics are available");
    if (availableBiometrics.isNotEmpty) {
      availableBiometrics.forEach((ab) {
        print("\ttech: $ab");
      });
    } else {
      print("no biometrics are available");
    }

    // authenticate with biometrics
    bool authenticated = false;
    try {
      authenticated = await auth.authenticateWithBiometrics(
        localizedReason: 'please do the biometrix',
        useErrorDialogs: true,
        stickyAuth: false,
      );
    } catch (e) {
      print("error using biometric auth: $e");
    }
    print("authenticated: $authenticated");
  }
}


```

add  `local_auth: ^0.5.0` to the pubspec.yaml

and run. 

clicking on the floating action button results in an exception 
```
PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null)
```

Same code works with `local_auth: ^0.4.0+1`

## Logs

```
[+5256 ms] I/flutter ( 7317): biometric stuff is available: true
[  +47 ms] I/flutter ( 7317): following biometrics are available
[        ] I/flutter ( 7317): 	tech: BiometricType.fingerprint
[  +21 ms] I/flutter ( 7317): error using biometric auth: PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null)
```

```
flutter analyze
Analyzing flutter_local_auth_test...                                    
No issues found! (ran in 1.6s)
```

```
 flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.utf8)
    • Flutter version 1.5.4-hotfix.2 at /home/dustin/opt/flutter/flutter_linux_beta/flutter
    • Framework revision 7a4c33425d (4 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/dustin/opt/android-studio/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = 
    • ANDROID_SDK_ROOT = /home/dustin/opt/android-studio/sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /opt/intellij-idea-ultimate-edition
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at /usr/share/idea
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Nexus 6P • CVH7N15B04001116 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 2 categories.

```

**Comment by madaiart** [comment]
Hi @pythoneer , did you change your android main file? The change log suggest to add Flutter Fragment Activiy like this example:
https://github.com/flutter/plugins/blob/52696881a2a984dd5197e20193492d757b302925/packages/local_auth/example/android/app/src/main/java/io/flutter/plugins/localauthexample/MainActivity.java#L8

**Comment by ShaiDemri** [comment]
I'm experiencing the same problem on android devices when using `  local_auth: ^0.5.2`. 
This problem does not shows up using `local_auth: ^0.4.0+1`

**Comment by pythoneer** [comment]
@madaiart No i have not. Thanks for mentioning it! I will check this tomorrow when i am back at work. This is however very unexpected. This should be mentioned in the README. This information will get lost in the change log even though this information is crucial for every new user until Flutter is generating Fragment Activities from the get go. I leave this open approximately until tomorrow and probably close this issue and open another one for change in the README

**Comment by TechnologicznaSowa** [comment]
@madaiart provided example is broken.
@pythoneer did you overcome problem with newst local_outah version?
@ShaiDemri yeah, ^0.4.0+1 works just fine

@mehmetf could you please take a look to this problem?

**Comment by mehmetf** [comment]
@TechnologicznaSowa could you please clarify when you said provided example is broken? When I try to run it, it works.

I do concur that this needs to be documented in README. This plugin now requires a fragment activity since underlying Biometric API requires a fragment activity.

**Comment by TechnologicznaSowa** [comment]
@mehmetf Sory about that - I was addressing that the only change is in the android main file as @madaiart suggested. The whole example provided here is running without any problems.

The documentation seems that is needed to be updated. I'm not an expert on Flutter/Androird/Ios and I'm stuck to 0.4.0+1 version due to the fact I don't know how to implement fragment activity.

**Comment by ReneRamos76** [comment]
I had the same problem, leave everything as in the beginning, without changing to FlutterFragmentActivity, but I followed the official androidx documentation and it worked with the latest versions of the local_auth 0.5.2 + 3 plugin and it worked as expected. https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility...

**Comment by ReneRamos76** [comment]
I had the same problem, leave everything as in the beginning, without changing to FlutterFragmentActivity, but I followed the official androidx documentation and it worked with the latest versions of the local_auth 0.5.2 + 3 plugin and it worked as expected. https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility...

**Comment by FingerArt** [comment]
Let `MainActivity` inherit the `FlutterFragmentActivity` and add the `support-v4` package to `build.gradle`, or use `androidx`. Can refer to [the example][1]


  [1]: https://github.com/flutter/plugins/tree/master/packages/local_auth/example

**Comment by peeto** [comment]
Using FlutterFragmentActivity causes Unhandled Exception: PlatformException(error, You need to use a Theme.AppCompat theme (or descendant) with this activity., null). I fixed the issue by changing pubspec.yaml:

  intl: ^0.15.1
  local_auth: ^0.4.0+1

**Comment by mohammadne** [comment]
I can't do this because of :
 ```flutter_localizations```

**Comment by NarHakobyan** [comment]
> I can't do this because of :
> `flutter_localizations`

same for me

**Comment by andy-zhangtao** [comment]
I use 0.6.1+3  and meet this issue too.  I use `FlutterFragmentActivity` instead of `FlutterActivity` in `MainActivity`, and it works.

```
package com.andy.eqc

import androidx.annotation.NonNull
//import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}

```

**Comment by janu1428** [comment]
> I use 0.6.1+3 and meet this issue too. I use `FlutterFragmentActivity` instead of `FlutterActivity` in `MainActivity`, and it works.
> 
> ```
> package com.andy.eqc
> 
> import androidx.annotation.NonNull
> //import io.flutter.embedding.android.FlutterActivity
> import io.flutter.embedding.android.FlutterFragmentActivity
> import io.flutter.embedding.engine.FlutterEngine
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterFragmentActivity() {
>     override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
>         GeneratedPluginRegistrant.registerWith(flutterEngine)
>     }
> }
> ```

Hi Andy,
I am still facing the issue. Do we need to refer this Mainactivity somewhere. Because I am still getting the error "I/flutter (  844): PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null)"..

Below is my mainactivity class
package io.flutter.plugins.digitalappfingerprint;


import androidx.annotation.NonNull;
//import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterFragmentActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterFragmentActivity {

    /*@Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }*/

    @java.lang.Override
    public void configureFlutterEngine(FlutterEngine flutterEngine) {
        super.configureFlutterEngine(flutterEngine);
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
Kindly please point out the step i have missed

**Comment by vladimirparanitsa-devpronet** [comment]
Hey @andy-zhangtao,

Could you help me with what file should I change? I am using `local_auth: 0.6.1+3`, should I just replace 
```
import android.os.Bundle;
import io.flutter.app.FlutterActivity;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}
```
with
```
import android.os.Bundle;
import io.flutter.app.FlutterFragmentActivity;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterFragmentActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}

```
in `android/app/src/main/java/com/example/myProject/MainActivity.java` file?
