### ISSUE TITLE
Build IOS in flutter it's showing GeneratedPluginRegistrant.m Plugin headers not found ex :(#import <firebase_analytics/FirebaseAnalyticsPlugin.h>)

### ISSUE THREAD

**Issue by vrnfernando** [flutter/flutter#33423]
## Error

Launching lib/main.dart on iPhone XR in debug mode...
Running Xcode build...
Xcode build done.                                            8.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/vishwafernando/Documents/fynd/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'firebase_auth/FirebaseAuthPlugin.h' file not found
    #import <firebase_auth/FirebaseAuthPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone XR.

## Logs

[  +35 ms] executing: [/Users/vishwafernando/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/vishwafernando/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [/Users/vishwafernando/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/vishwafernando/flutter/] git log -n 1 --pretty=format:%H
[  +19 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8661d8aecd626f7f57ccbcb735553edc05a2e713
[        ] executing: [/Users/vishwafernando/flutter/] git log -n 1 --pretty=format:%ar
[  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 months ago
[        ] executing: [/Users/vishwafernando/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +43 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.2.1-0-g8661d8aecd
[ +532 ms] executing: /Users/vishwafernando/Library/Android/sdk/platform-tools/adb devices -l
[  +16 ms] Exit code 0 from: /Users/vishwafernando/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[  +17 ms] executing: idevice_id -h
[  +50 ms] /usr/bin/xcrun simctl list --json devices
[ +264 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +6 ms] /Users/vishwafernando/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +38 ms] ro.hardware = ranchu
[  +12 ms] Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
[   +1 ms] iPhone XR                 • D1A4E0C1-2928-4CDA-9F09-8A51E4B9EC6D • ios         • iOS 12.1 (simulator)
[  +17 ms] "flutter run" took 860ms.
[        ] "flutter run" took 860ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:240:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:525:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:482:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:473:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:48:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#34     main (file:///b/rr/tmp6N7O2E/w/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```
```
## Analyze
 info • Unused import: 'package:fynd/intro.dart' • lib/dash.dart:2:8 • unused_import
   info • Unused import: 'package:fynd/views/login.dart' • lib/dash.dart:8:8 • unused_import
   info • The value of the field '_connectionStatus' isn't used • lib/dash.dart:18:7 • unused_field
   info • Unused import: 'dart:async' • lib/intro.dart:1:8 • unused_import
   info • Unused import: 'package:fynd/views/login.dart' • lib/intro.dart:6:8 • unused_import
   info • Unused import: 'package:shared_preferences/shared_preferences.dart' • lib/intro.dart:7:8 • unused_import
   info • Unused import: 'package:fynd/dash.dart' • lib/intro.dart:8:8 • unused_import
warning • The parameter 'text' is required • lib/main.dart:42:58 • missing_required_param
warning • The parameter 'mapObject' is required • lib/main.dart:45:46 • missing_required_param
warning • The parameter 'textx' is required • lib/main.dart:46:54 • missing_required_param
   info • Name types using UpperCamelCase • lib/model/searchResultcompanies.dart:1:7 • camel_case_types
   info • Unused import: 'package:flutter_facebook_login/flutter_facebook_login.dart' • lib/services/auth.dart:3:8 • unused_import
   info • Unused import: 'package:fynd/views/login.dart' • lib/services/auth.dart:19:8 • unused_import
   info • The value of the local variable 'response' isn't used • lib/services/auth.dart:186:9 • unused_local_variable
   info • The value of the local variable 'response' isn't used • lib/services/auth.dart:241:9 • unused_local_variable
   info • This function has a return type of 'Future<String>', but doesn't end with a return statement • lib/services/auth.dart:379:3 • missing_return
   info • This function has a return type of 'Future<List<SearchModel>>', but doesn't end with a return statement • lib/services/auth.dart:407:3 • missing_return
   info • The value of the local variable 'category' isn't used • lib/services/auth.dart:885:14 • unused_local_variable
   info • The value of the local variable 'message' isn't used • lib/services/auth.dart:906:12 • unused_local_variable
   info • The value of the local variable 'response' isn't used • lib/services/auth.dart:1049:9 • unused_local_variable
   info • Name non-constant identifiers using lowerCamelCase • lib/services/cons.dart:41:17 • non_constant_identifier_names
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions • lib/utils/dilaogs.dart:56:3 •
          sdk_version_async_exported_from_core
   info • The method '_asyncInputDialog' isn't used • lib/utils/dilaogs.dart:56:18 • unused_element
   info • The value of the field '_value1' isn't used • lib/views/bookingAdOn.dart:33:8 • unused_field
   info • The value of the field '_connectionStatus' isn't used • lib/views/bookingAdOn.dart:35:7 • unused_field
   info • Name non-constant identifiers using lowerCamelCase • lib/views/bookingAdOn.dart:91:43 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/bookingAdOn.dart:599:14 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/bookingAdOn.dart:699:14 • non_constant_identifier_names
   info • Unused import: 'dart:async' • lib/views/bookingCart.dart:9:8 • unused_import
   info • The value of the field '_connectionStatus' isn't used • lib/views/bookingCart.dart:21:7 • unused_field
   info • Name non-constant identifiers using lowerCamelCase • lib/views/bookingInfo.dart:27:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/bookingInfo.dart:39:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/bookingInfo.dart:39:23 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/bookingInfo.dart:39:35 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/bookingInfo.dart:39:47 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/bookingInfo.dart:39:54 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/bookingInfo.dart:39:64 • non_constant_identifier_names
   info • The value of the field '_connectionStatus' isn't used • lib/views/bookingInfo.dart:41:7 • unused_field
   info • The value of the field '_result' isn't used • lib/views/bookingInfo.dart:103:10 • unused_field
   info • The value of the local variable 'data' isn't used • lib/views/bookingInfo.dart:926:10 • unused_local_variable
   info • The value of the local variable 'posNum' isn't used • lib/views/bookingInfo.dart:928:9 • unused_local_variable
   info • Name non-constant identifiers using lowerCamelCase • lib/views/bookingInfo.dart:1119:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/bookingInfo.dart:1149:16 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/bookingInfo.dart:1150:16 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/bookingInfo.dart:1151:16 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/bookingInfo.dart:1152:16 • non_constant_identifier_names
   info • The value of the local variable 'city_' isn't used • lib/views/bookingInfo.dart:1152:16 • unused_local_variable
   info • The value of the local variable 'message' isn't used • lib/views/bookingInfo.dart:1227:19 • unused_local_variable
   info • Unused import: 'dart:async' • lib/views/bookingSummery.dart:2:8 • unused_import
   info • The value of the field '_connectionStatus' isn't used • lib/views/bookingSummery.dart:11:7 • unused_field
   info • Unused import: 'dart:async' • lib/views/bookings.dart:7:8 • unused_import
   info • The value of the field '_connectionStatus' isn't used • lib/views/bookings.dart:16:7 • unused_field
   info • Name non-constant identifiers using lowerCamelCase • lib/views/cardview/adCardView.dart:8:26 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/cardview/adCardView.dart:19:20 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/cardview/bookingCartCard.dart:5:21 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/cardview/bookingCartCard.dart:17:15 • non_constant_identifier_names
   info • 'child' is deprecated and shouldn't be used • lib/views/cardview/branchCard.dart:123:58 • deprecated_member_use
   info • Name non-constant identifiers using lowerCamelCase • lib/views/cardview/pastBookingCard.dart:6:25 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/cardview/pastBookingCard.dart:18:19 • non_constant_identifier_names
   info • This function has a return type of 'Widget', but doesn't end with a return statement • lib/views/cardview/pastBookingCard.dart:143:3 • missing_return
   info • This function has a return type of 'Widget', but doesn't end with a return statement • lib/views/cardview/pastBookingCard.dart:202:3 • missing_return
   info • This function has a return type of 'Widget', but doesn't end with a return statement • lib/views/cardview/pastBookingCard.dart:228:3 • missing_return
   info • Name non-constant identifiers using lowerCamelCase • lib/views/cardview/upcomingBookingCard.dart:6:29 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/views/cardview/upcomingBookingCard.dart:17:23 • non_constant_identifier_names
   info • This function has a return type of 'Widget', but doesn't end with a return statement • lib/views/cardview/upcomingBookingCard.dart:142:3 • missing_return
   info • This function has a return type of 'Widget', but doesn't end with a return statement • lib/views/cardview/upcomingBookingCard.dart:183:3 • missing_return
   info • This function has a return type of 'Widget', but doesn't end with a return statement • lib/views/cardview/upcomingBookingCard.dart:202:3 • missing_return
   info • Unused import: 'package:fynd/views/searchAdViewList.dart' • lib/views/companyMenu.dart:10:8 • unused_import
   info • Unused import: 'package:http/http.dart' • lib/views/companyMenu.dart:12:8 • unused_import
   info • Unused import: 'dart:async' • lib/views/companyMenu.dart:15:8 • unused_import
   info • The value of the field '_connectionStatus' isn't used • lib/views/companyMenu.dart:100:7 • unused_field
   info • The value of the field '_pageController' isn't used • lib/views/companyMenu.dart:105:9 • unused_field
   info • The value of the field '_kDuration' isn't used • lib/views/companyMenu.dart:107:16 • unused_field
   info • The value of the field '_kCurve' isn't used • lib/views/companyMenu.dart:109:16 • unused_field
   info • The value of the field '_pages' isn't used • lib/views/companyMenu.dart:111:22 • unused_field
   info • 'child' is deprecated and shouldn't be used • lib/views/companyMenu.dart:308:82 • deprecated_member_use
   info • The value of the field '_connectionStatus' isn't used • lib/views/editProfile.dart:27:7 • unused_field
   info • This function has a return type of 'Future<String>', but doesn't end with a return statement • lib/views/editProfile.dart:523:3 • missing_return
   info • Unused import: 'package:firebase_auth/firebase_auth.dart' • lib/views/emailVerfication.dart:3:8 • unused_import
   info • Unused import: 'dart:async' • lib/views/emailVerfication.dart:5:8 • unused_import
   info • The value of the field '_connectionStatus' isn't used • lib/views/emailVerfication.dart:14:7 • unused_field
   info • The value of the field '_connectionStatus' isn't used • lib/views/forgetPassword.dart:15:7 • unused_field
   info • The value of the local variable 'loadingIndicator' isn't used • lib/views/forgetPassword.dart:79:12 • unused_local_variable
   info • Unused import: 'package:firebase_auth/firebase_auth.dart' • lib/views/home.dart:3:8 • unused_import
   info • Unused import: 'package:rxdart/rxdart.dart' • lib/views/home.dart:11:8 • unused_import
   info • Unused import: 'package:http/http.dart' • lib/views/home.dart:12:8 • unused_import
   info • Unused import: 'dart:convert' • lib/views/home.dart:13:8 • unused_import
   info • Unused import: 'dart:async' • lib/views/home.dart:14:8 • unused_import
   info • The value of the field '_connectionStatus' isn't used • lib/views/home.dart:119:7 • unused_field
   info • The value of the field '_connectionStatus' isn't used • lib/views/login.dart:26:7 • unused_field
   info • Unused import: 'package:firebase_auth/firebase_auth.dart' • lib/views/myProfile.dart:5:8 • unused_import
   info • Unused import: 'dart:async' • lib/views/myProfile.dart:6:8 • unused_import
   info • Unused import: 'dart:convert' • lib/views/myProfile.dart:7:8 • unused_import
   info • Unused import: 'package:http/http.dart' • lib/views/myProfile.dart:8:8 • unused_import
   info • Unused import: 'package:rxdart/rxdart.dart' • lib/views/myProfile.dart:9:8 • unused_import
   info • The value of the field '_connectionStatus' isn't used • lib/views/myProfile.dart:25:7 • unused_field
   info • The value of the field '_validate' isn't used • lib/views/register.dart:15:8 • unused_field
   info • The value of the field '_connectionStatus' isn't used • lib/views/register.dart:31:7 • unused_field
   info • Unused import: 'dart:async' • lib/views/searchAdViewList.dart:7:8 • unused_import
   info • The value of the field '_connectionStatus' isn't used • lib/views/searchAdViewList.dart:20:7 • unused_field
   info • The method '_buildCarouselItem' isn't used • lib/views/searchAdViewList.dart:153:10 • unused_element
   info • This function has a return type of 'Widget', but doesn't end with a return statement • lib/views/searchGridview.dart:201:3 • missing_return
   info • Unused import: 'dart:async' • lib/views/settingAfterLogin.dart:10:8 • unused_import
   info • The value of the field '_connectionStatus' isn't used • lib/views/settingAfterLogin.dart:32:7 • unused_field
   info • 'child' is deprecated and shouldn't be used • lib/views/settingAfterLogin.dart:261:47 • deprecated_member_use
   info • 'child' is deprecated and shouldn't be used • lib/views/settingBeforeLogin.dart:128:25 • deprecated_member_use

106 issues found. (ran in 11.8s)

```
```

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G7024, locale en-LK)
    • Flutter version 1.2.1 at /Users/vishwafernando/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/vishwafernando/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone XR                 • D1A4E0C1-2928-4CDA-9F09-8A51E4B9EC6D • ios         • iOS 12.1 (simulator)

• No issues found!

```
```

**Comment by Jumpbotron** [comment]
@vrnfernando Same issue, did you get the solution for it??

**Comment by vrnfernando** [comment]
@Jumpbotron yes, i solve that issue. 
Issue occurred with this two Flutter dependencies :  
* firebase_auth: ^0.6.6 
* firebase_core: ^0.2.5

So i just change it to :
* firebase_auth: ^0.8.4+5
* firebase_core: ^0.3.0

After that i was remove GoogleService-Info.plist from Flutter project and add the GoogleService-Info.plist file using the Xcode. After that you need to check "Copy Bundle Resources", in Runner>Build Phases>Copy Bundle Resources.

<img width="683" alt="Screen Shot 2019-06-18 at 7 00 35 PM" src="https://user-images.githubusercontent.com/9113329/59688500-71963900-91fb-11e9-8926-a652d111ea4c.png">

**Comment by limited107** [comment]
@vrnfernando 
I've just solve the problem. Just delete the ios/Podfile and rerun the iOS application.

**Comment by ctippur** [comment]
@limited107 - I have the same issue. Can you elaborate on what you had to do?

**Comment by iapicca** [comment]
Hi @vrnfernando 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by EvenerV** [comment]
I had this issue too, and I solved this by edit the profile.

1. You can create a new flutter app and have a profile in the ios project by automatic generation.
2. Compare the profile with your profile in your project, and copy the missing config to your profile.
3. `flutter clean` -> `pod install`, and you could see those not found module will be installed
4. `flutter run`

Hope this could help someone.

**Comment by Garciconx** [comment]
> I had this issue too, and I solved this by edit the profile.
> 
> 1. You can create a new flutter app and have a profile in the ios project by automatic generation.
> 2. Compare the profile with your profile in your project, and copy the missing config to your profile.
> 3. `flutter clean` -> `pod install`, and you could see those not found module will be installed
> 4. `flutter run`
> 
> Hope this could help someone.

profile or podfile?

**Comment by EvenerV** [comment]
> > I had this issue too, and I solved this by edit the profile.
> > 
> > 1. You can create a new flutter app and have a profile in the ios project by automatic generation.
> > 2. Compare the profile with your profile in your project, and copy the missing config to your profile.
> > 3. `flutter clean` -> `pod install`, and you could see those not found module will be installed
> > 4. `flutter run`
> > 
> > Hope this could help someone.
> 
> profile or podfile?

It should be Podfile, thank you.

**Comment by OhadMaor-VIA** [comment]
> I had this issue too, and I solved this by edit the podfile.
> 
> 1. You can create a new flutter app and have a podfile in the ios project by automatic generation.
> 2. Compare the podfile with your profile in your podfile, and copy the missing config to your podfile.
> 3. `flutter clean` -> `pod install`, and you could see those not found module will be installed
> 4. `flutter run`
> 
> Hope this could help someone.

Thank you very much!
I actually don't understand why the issues is there on the first place. It can easily be prevented by Flutter team.

**Comment by oTree-org** [comment]
> I had this issue too, and I solved this by edit the podfile.
> 
> 1. You can create a new flutter app and have a podfile in the ios project by automatic generation.
> 2. Compare the podfile with your profile in your podfile, and copy the missing config to your podfile.
> 3. `flutter clean` -> `pod install`, and you could see those not found module will be installed
> 4. `flutter run`
> 
> Hope this could help someone.

Hi, thanks for this reply. Regarding this: "You can create a new flutter app and have a podfile in the ios project by automatic generation." You mean that when I do "flutter create myproject" there will already be a Podfile? Because I can't find any. The ios folder just contains "Flutter", "Runner", "Runner.xcodeproj" and "Runner.xcworkspace".

**Comment by EvenerV** [comment]
> > I had this issue too, and I solved this by edit the podfile.
> > 
> > 1. You can create a new flutter app and have a podfile in the ios project by automatic generation.
> > 2. Compare the podfile with your profile in your podfile, and copy the missing config to your podfile.
> > 3. `flutter clean` -> `pod install`, and you could see those not found module will be installed
> > 4. `flutter run`
> > 
> > Hope this could help someone.
> 
> Hi, thanks for this reply. Regarding this: "You can create a new flutter app and have a podfile in the ios project by automatic generation." You mean that when I do "flutter create myproject" there will already be a Podfile? Because I can't find any. The ios folder just contains "Flutter", "Runner", "Runner.xcodeproj" and "Runner.xcworkspace".

I just created a new flutter project and found the same situation. I remembered that I had a podfile before. Now you could refer to this.
[The templates of cocoapods](https://github.com/flutter/flutter/tree/master/packages/flutter_tools/templates/cocoapods)

**Comment by Harbdollar** [comment]
> > I had this issue too, and I solved this by edit the podfile.
> > 
> > 1. You can create a new flutter app and have a podfile in the ios project by automatic generation.
> > 2. Compare the podfile with your profile in your podfile, and copy the missing config to your podfile.
> > 3. `flutter clean` -> `pod install`, and you could see those not found module will be installed
> > 4. `flutter run`
> > 
> > Hope this could help someone.
> 
> Hi, thanks for this reply. Regarding this: "You can create a new flutter app and have a podfile in the ios project by automatic generation." You mean that when I do "flutter create myproject" there will already be a Podfile? Because I can't find any. The ios folder just contains "Flutter", "Runner", "Runner.xcodeproj" and "Runner.xcworkspace".

try to run your new flutter project on ios. It should automatically create pod file

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
