### ISSUE TITLE
Plugin(url_launch): can not open itms-services link

### ISSUE THREAD

**Issue by bang88** [flutter/flutter#33422]
## Steps to Reproduce

1. `import 'package:url_launcher/url_launcher.dart';`
2.  
```dart
await launch(
                         "itms-services://?action=download-manifest&url=https://app.com/ios/manifest.plist",
                          forceSafariVC: false,
                          forceWebView: false,
                        );
```
3. ...

The result is true. but its do nothing here. Open normal link are work as expected.

## Logs

```
```

```
```

```
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale
    en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    ✗ Verify that all connected devices have been paired with this computer in
      Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may
      require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.34.0)
[✓] Connected device (1 available)
```

And does not work on 1.6.3

**Comment by weiwanfang** [comment]
兄弟这个问题你解决了吗  求交流 qq: 3114281253

**Comment by iapicca** [comment]
Hi @bang88 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by bang88** [comment]
Well. after 5 months later I don't know its working or not. and I am not use flutter at the moment. To reproduce it its very simple just call it like what I said. Does this working on the latest version of Flutter ? If you are using the latest version you can verify it in 5 minutes.

**Comment by iapicca** [comment]
If you are not experiencing any issue at the moment
I feel safe to close this one, if you disagree please 
write in the comments and I will reopen it. 
Thank you
