### ISSUE TITLE
Google Maps marker icon showing wrong colors

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#33437]
Running the example app on a PIxel 2, this is what I get in the place marker demo after selecting a marker and tapping "set marker icon":

![Screenshot_20190528-095349](https://user-images.githubusercontent.com/1024117/58496517-e8757000-812e-11e9-8f3b-3eff25b538fd.png)

IIUC the marker icon should be the `red_square.png` asset which should be red.

@iskakaushik

**Comment by iskakaushik** [comment]
This is an issue with bad naming :-(

The file name `red_square.png` should really be `dpi_aware_sqaure.png` or something like that. I created three files with same name and different colors for different dpis, to demonstrate that we pick the right image for the corresponding dpi.

**Comment by pedromassangocode** [comment]
Hi @amirh @iskakaushik 
Is this still a valid bug? A code to reproduce would help!
