### ISSUE TITLE
Anti-hysteresis code causes loss of focus occasionally.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#33435]
Reported by @eyun-tv (thank you for the report and the clear reproduction case!):

"I write a demo use DefaultFocusTraversal with ReadingOrderTraversalPolicy
But , I find when you press up or down , sometimes , the focus will lose .
I record a video https://vimeo.com/338635739 for show this bug

My code is there :
https://github.com/eyun-tv/flutter-tv/blob/master/lib/main.dart
https://github.com/eyun-tv/flutter-tv/blob/master/lib/ui/util/video.dart

My flutter version is master and my tv box is android 9"

I took a quick look, and it seems to be related to the anti-hysteresis code that makes sure we follow the same reverse path as we took forward, probably having to do with reaching the end of the history but not doing anything in that case.

**Comment by urwork** [comment]
I have the same problem.

I print all nearestScope children in focus scope _handleKeyPress
```
node.nearestScope.children.forEach((i) {
print("> $i ${++n}");
});
```
I found the FocusNode number is less than list view items .

I think maybe because the list view just keep the visible items , but remove the hide items .

How to fix this ?

**Comment by eyun-tv** [comment]
Is there any schedule for fix this ?
