### ISSUE TITLE
Replaces usages of BinaryMessages in the plugins repo

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#33446]
https://github.com/flutter/flutter/pull/30406 deprecated `BinaryMessages` which is used in multiple unit tests in the `flutter/plugins` repo.

As we cannot use the new `defaultBinaryMessenger `before https://github.com/flutter/flutter/pull/30406 makes it to stable, I'm suppressing the warnings in the plugins repository for now.

We should move to use `defaultBinaryMessenger` once it make it to stable.

cc @hterkelsen

**Comment by hterkelsen** [comment]
Since `defaultBinaryMessenger` has moved to `ServicesBinding`, I think it makes sense to wait for `ServicesBinding.instance.defaultBinaryMessenger` to make it to stable before modifying the usages of `BinaryMessages`

**Comment by hterkelsen** [comment]
`ServicesBinding.instance.defaultBinaryMessenger` won't make it to Flutter stable until the next stable release, which I believe is in December. I am changing this issue's milestone to December
