### ISSUE TITLE
Proxy for flutter cmd tool

### ISSUE THREAD

**Issue by aarmn** [flutter/flutter#33482]
Hello there
I try to use torsocks and openvpn for "flutter run" but flutter doesn't work with them and can't find my mobile phone when i use torsocks
I really need that because all gradle tools are downloaded from google and its 403 in Iran
Is there a way to proxy that, download files manually or internal proxy with socks5 support?
Please don't tag it duplicated. Check all similar ones too

**Comment by kangwang1988** [comment]
It seems to be a problem 'How can I proxy my terminal traffic to use vpn, etc'.
I believe it's not a flutter problem, however, I have some advices.
On MacOS, Proxifier could do the trick for you, it can redirect all traffics including IDE and terminals according to configuration.
Besides, you can use `flutter run --verbose` to see which step is blocked during build process, henceforth, we can find some workaround to avoid this connection issue. Including but not limited to, download from mirrors, or you can download a zip like gradle.zip using a Browser and unzip it manually.
I will close this issue as it's not a flutter one. However, I'm willing to comment below according to your feedbacks. Hope you can enjoy flutter.
@aarmn
