### ISSUE TITLE
[web]: cannot run tests

### ISSUE THREAD

**Issue by strotz** [flutter/flutter#33490]
i'm trying to add unit tests to flutter web project. 

20:50 $ flutter test
00:00 +0: loading /Users/name/project/test/main_test.dart
Compiler message:

Failed to load test harness. Are you missing a dependency on flutter_test?

00:01 +0: loading /Users/name/project/test/main_test.dart                                                                                                                                                                     Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aflutter_test%2Fflutter_test.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:589:37)
<asynchronous suspension>
#2      FrontendCompiler._outputDependenciesDelta (package:vm/frontend_server.dart:391:39)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:vm/frontend_server.dart:365:13)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:31:22)
<asynchronous suspension>
#5      listenAndCompile.<anonymous closure> (package:vm/frontend_server.dart:726:26)
<asynchronous suspension>
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#9      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#10     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#11     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#12     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#13     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#14     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#15     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#20     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#21     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#22     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#23     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#24     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#25     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#26     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#30     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#31     _StreamController._add (dart:async/stream_controller.dart:640:7)
#32     _StreamController.add (dart:async/stream_controller.dart:586:5)
#33     _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#34     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#37     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#38     _StreamController._add (dart:async/stream_controller.dart:640:7)
#39     _StreamController.add (dart:async/stream_controller.dart:586:5)
#40     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#41     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#44     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
00:01 +0 -1: loading /Users/name/project/test/main_test.dart [E]
  Failed to load "/Users/name/project/test/main_test.dart":
  Compilation failed
  Test: /Users/name/project/test/main_test.dart
  Shell: /Users/name/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester

test/main_test.dart:
import 'package:test/test.dart';

void main() {
  test('Sample', () {
  });
}

pubspec.yaml:
name: project
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0
  flutter_web_test: any
  test: ^1.6.3

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test

Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
! flutter_web 0.0.0 from git https://github.com/flutter/flutter_web at 2f74e7 in packages/flutter_web
! flutter_web_test 0.0.0 from git https://github.com/flutter/flutter_web at 2f74e7 in packages/flutter_web_test
! flutter_web_ui 0.0.0 from git https://github.com/flutter/flutter_web at 2f74e7 in packages/flutter_web_ui

**Comment by ThinkDigitalSoftware** [comment]
This isn't web only. I'm getting this on a plain dart package. It may have to do with the flutter version since I haven't made changes to this project in a while and it doesn't work all of a sudden

**Comment by jonahwilliams** [comment]
You cannot use `flutter test` on the current implementation of flutter_web and support for running tests this way is not planned

**Comment by ThinkDigitalSoftware** [comment]
@jonahwilliams , then what about for my issue? I'm not running it for web

[✓] Flutter (Channel beta, v1.7.8+hotfix.3, on Mac OS X 10.14.4 18E226, locale en-US)

**Comment by jonahwilliams** [comment]
@ThinkDigitalSoftware please file a new issue, it sounds unrelated
