### ISSUE TITLE
Create a solution to show a native loading view while a Flutter view renders its first frame

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#33494]
Create a splash View solution that wraps a FlutterView so that it can be included when/if desired, and ignored otherwise.

**Comment by matthew-carroll** [comment]
CC @xster, I had this ticket as a note in the embedding project. I went ahead and converted it to a ticket.

**Comment by xster** [comment]
I'm repurposing the bug a bit to make it more generic

**Comment by matthew-carroll** [comment]
Done via https://github.com/flutter/engine/pull/9525 and https://github.com/flutter/flutter/pull/35728

**Comment by xster** [comment]
Does the solution also work for pre-warmed engines and re-used engines?

**Comment by matthew-carroll** [comment]
@xster can you describe a specific use-case? The fundamental notion of a pre-warmed engine is orthogonal to this behavior...
