### ISSUE TITLE
textDirection != null assert in textDirectionToAxisDirection

### ISSUE THREAD

**Issue by shenqidebaozi** [flutter/flutter#33498]
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building
flutter: RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#39376](state:
flutter: RawGestureDetectorState#e8321(gestures: <none>, behavior: opaque)):
flutter: 'package:flutter/src/painting/basic_types.dart': Failed assertion: line 222 pos 10: 'textDirection
flutter: != null': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      textDirectionToAxisDirection (package:flutter/src/painting/basic_types.dart:222:10)
flutter: #3      Viewport.getDefaultCrossAxisDirection (package:flutter/src/widgets/viewport.dart:128:16)
flutter: #4      Viewport.createRenderObject (package:flutter/src/widgets/viewport.dart:139:58)
flutter: #5      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4594:28)
flutter: #6      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5074:11)
flutter: #7      _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:186:11)
flutter: #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
flutter: #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4972:14)
flutter: #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
flutter: #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4972:14)
flutter: #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
flutter: #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4972:14)
flutter: #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
flutter: #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4972:14)
flutter: #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
flutter: #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
flutter: #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3818:5)
flutter: #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3960:11)
flutter: #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3813:5)
flutter: #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
flutter: #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4972:14)
flutter: #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
flutter: #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
flutter: #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
flutter: #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3818:5)
flutter: #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3813:5)
flutter: #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
flutter: #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4972:14)
flutter: #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
flutter: #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
flutter: #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
flutter: #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3818:5)
flutter: #44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3960:11)
flutter: #45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3813:5)
flutter: #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
flutter: #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
flutter: #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
flutter: #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
flutter: #50     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3818:5)
flutter: #51     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3813:5)
flutter: #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
flutter: #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
flutter: #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
flutter: #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
flutter: #56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3818:5)
flutter: #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3813:5)
flutter: #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
flutter: #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
flutter: #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
flutter: #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
flutter: #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3818:5)
flutter: #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3813:5)
flutter: #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3052:14)
flutter: #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2855:12)
flutter: #66     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:939:16)
flutter: #67     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:910:5)
flutter: #68     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:856:17)
flutter: #69     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2294:19)
flutter: #70     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:855:13)
flutter: #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
flutter: #72     runApp (package:flutter/src/widgets/binding.dart:786:7)
flutter: #73     main (package:flutter_shop/main.dart:9:3)
flutter: #74     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:200:25)
flutter: #79     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:192:5)
flutter: #80     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
flutter: #81     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
flutter: (elided 6 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```dart
import 'package:flutter/material.dart';
import 'provide.dart';
import 'package:provide/provide.dart';

void main() {
  var counter = Counter();
  var providres = Providers();
  providres..provide(Provider<Counter>.value(counter));
  runApp(Myapp());
}

class Myapp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
        child: ListView(
      children: <Widget>[
        RaisedButton(
          onPressed: () {
            Provide.value<Counter>(context).countAdd();
          },
          child: Icon(Icons.ac_unit),
        ),
        NewPage()
      ],
    ));
  }
}

class NewPage extends StatefulWidget {
  _NewPageState createState() => _NewPageState();
}

class _NewPageState extends State<NewPage> {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Provide<Counter>(
        builder: (context, child, counter) {
          return Container(
            child:  Text(
            '${counter.countInt}',
             style: Theme.of(context).textTheme.display1,
          )
          );
        },
      ),
    );
  }
}
```

provide:

```dart
import 'package:flutter/material.dart';

class Counter with ChangeNotifier{
  int countInt = 0;
  countAdd(){
    countInt++;
    notifyListeners();
  }
}
```

**Comment by iapicca** [comment]
Hi @shenqidebaozi 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
