### ISSUE TITLE
Embiggen tap target for menu/back button in toolbar

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#335]
Might make sense to do this at the same time that we add a circular ink splash

**Comment by Hixie** [comment]
This will happen automatically when I do my ink splash change that I have in flight at home. If you need it more urgently then we can do something temporary though. (It broke because of the way hit testing now defers to the child instead of using its size, IIRC.)

**Comment by collinjackson** [comment]
It's not urgent, let's wait for your change to land
