### ISSUE TITLE
Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by yataoSang** [flutter/flutter#33509]
When using CacheStore's retrieveCacheData to get cache resources, is it necessary to judge the real existence of resources? When _memCache contains the current url, but the resource has been deleted, you should need to re-download the resource.

使用CacheStore的retrieveCacheData获取缓存资源时，是不是需要判断一下资源真实存在？当_memCache包含当前的url，但是资源已经被删除时应该需要重新下载资源

**Comment by kangwang1988** [comment]
When you talking about `CacheStore's retrieveCacheData`, which dart package are you talking about?
@yataoSang

**Comment by yataoSang** [comment]
1.4.15

**Comment by yataoSang** [comment]
> When you talking about `CacheStore's retrieveCacheData`, which dart package are you referring to?
> @yataoSang
1.4.15

**Comment by kangwang1988** [comment]
@yataoSang 
Can you post a url where the code snippet you're referring to?
