### ISSUE TITLE
Remove Upper Bar

### ISSUE THREAD

**Issue by iwanio** [flutter/flutter#33510]
I cannot seem to find a way to remove the top bar (the one that normally has a title on it) from my app. Is there any way to do it?

**Comment by loolooii** [comment]
You should ask this on StackOverflow. If you don't add an `AppBar` to your `Scaffold`, there won't be any AppBar. You can put your body content inside `SafeArea` to make sure that your content is positioned properly. You should read about those in docs or watch videos about Flutter widgets on YouTube.
