### ISSUE TITLE
[web]:can't run hello world from china--No rout to host pub.dartlang.org

### ISSUE THREAD

**Issue by dingbo8128** [flutter/flutter#33512]
flutter version: Flutter 1.5.4-hotfix.2 

Unhandled exception:
SocketException: Connection failed (OS Error: No route to host, errno = 65), address = pub.dartlang.org, port = 443
#0      IOClient.send (package:http/src/io_client.dart:33:23)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:169:38)
<asynchronous suspension>
#2      BaseClient.get (package:http/src/base_client.dart:32:7)
#3      get.<anonymous closure> (package:http/http.dart:46:36)
#4      _withClient (package:http/http.dart:166:20)
<asynchronous suspension>
#5      get (package:http/http.dart:46:5)
#6      _latestPackageInfo (package:webdev/src/pubspec.dart:230:24)
<asynchronous suspension>
#7      _validateBuildDaemonVersion (package:webdev/src/pubspec.dart:155:22)
<asynchronous suspension>
#8      checkPubspecLock (package:webdev/src/pubspec.dart:193:25)
<asynchronous suspension>
#9      readPubspecLock (package:webdev/src/command/shared.dart:63:9)
<asynchronous suspension>
#10     ServeCommand.run (package:webdev/src/command/serve_command.dart:101:29)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
<asynchronous suspension>
#13     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#14     new Future.sync (dart:async/future.dart:224:31)
#15     CommandRunner.run (package:args/command_runner.dart:111:11)
#16     run (package:webdev/src/webdev_command_runner.dart:19:56)
#17     main (file:///Users/bo/.pub-cache/hosted/pub.flutter-io.cn/webdev-2.0.5/bin/webdev.dart:17:22)

**Comment by timsneath** [comment]
Hi there, the pub.dartlang.org server is unavailable from China due to firewall issues. Information about accessing Dart packages from China can be found here: https://flutter.dev/community/china

**Comment by dingbo8128** [comment]
no no no, I know the solution for plain flutter project. But this issue is about flutter web project. 
I created a  "Flutter Web App - a simple Flutter Web app" from Dart project navigator.
