### ISSUE TITLE
Button executed but didn't click

### ISSUE THREAD

**Issue by leopalazzi** [flutter/flutter#33516]
Hello,

I have a button to get back on the first page. But when I click on this button -> the method "onPressed" of the button in the first page is executed when rendering the page.

I didn't click on the button.

The two buttons execute async function to do POST method.

Can you help me ?

**Comment by HansMuller** [comment]
If you can provide a small self-contained test app that demonstrates the problem, we'll look into it.

**Comment by leopalazzi** [comment]
I found the bug. It's because I had a Listener on Firestore and this is called even if it is in a onPressed method.
