### ISSUE TITLE
Need a way to send synchronous keyboard events from embedder to Dart and get a response.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#33521]
Internal: b/140830852

Similar to #28310, we need to be able to synchronously take keyboard events from the platform embedder, pass them to Dart to be handled, and if they are not handled, then pass them back to the platform to give it a chance to handle them.

This is needed so that add2app has a hope of working in environments with keyboards (like desktops), and so that we can capture keys before they get to a soft keyboard, as requested way back in #5986 (and has come up repeatedly).

We need a way to determine whether key events have been handled, synchronously, so that embedders know whether to continue propagating them in the native view hierarchy.

It needs to be synchronous because key events need to be responded to synchronously on host platforms.

**Comment by stuartmorgan** [comment]
Relatedly, there have been general conversations several times in the past about the need for a formal keyboard API in embedding.h, rather than passing text input and key events via a platform channel.

**Comment by jkurtw** [comment]
b/140830852

**Comment by jwinarske** [comment]
I have a [Wayland Embedder](https://github.com/jwinarske/flutter_wayland/blob/waylandpp/src/wayland_display.cc) client working with the exception of Keyboard.  I send key events, and they're dropped by the engine.  It looks like I need to modify the Engine to register a "flutter/keyevent" handler.  Will this change enable a default channel in the embedder for keyevents?

**Comment by stuartmorgan** [comment]
> It looks like I need to modify the Engine to register a "flutter/keyevent" handler.

The listener is in the framework code, and is always present. You should not need to modify the engine.

> Will this change enable a default channel in the embedder for keyevents?

No (per above), but it will provide an explicit API in embedder.h that embedders should use instead of the message channel.

**Comment by jwinarske** [comment]
I see said the blind man as he picked up the hammer and saw 😁.  Thanks for the pointer, it's all clear now 👍

**Comment by Sunbreak** [comment]
IIRC, someone were experimenting on merging Platform Runner & UI Runner.

Would it be another option?

**Comment by gspencergoog** [comment]
This was fixed by the various delay key event changes.  Closing.

**Comment by NilsUX** [comment]
This can be moved to "Done" in project "[Desktop Features](https://github.com/flutter/flutter/projects/33#card-31967822)", right?

**Comment by gspencergoog** [comment]
@NilsUX Yes, done.  Thanks.

**Comment by siavee** [comment]
> I have a [Wayland Embedder](https://github.com/jwinarske/flutter_wayland/blob/waylandpp/src/wayland_display.cc) client working with the exception of Keyboard. I send key events, and they're dropped by the engine. It looks like I need to modify the Engine to register a "flutter/keyevent" handler. Will this change enable a default channel in the embedder for keyevents?

Sorry to bump an old issue, but I'm having the same problem with this comment and I'm not sure where to ask. 

I have successfully embed Flutter in my OpenGL app using software renderer. Rendering & mouse/pointer events works fine. However, I'm not able to send or receive any platform messages to/from the flutter engine:

- The `FlutterProjectArgs.platform_message_callback` is never called, and
- sending keyboard events via `flutter/keyevent` has no effect (I implement something similar to the [glfw key handler](https://github.com/flutter/engine/blob/master/shell/platform/glfw/key_event_handler.cc))

Also if I use a native plugin, the MethodChannel never returns.

For the project args, I only filled `assets_path`, `icu_data_path` & `platform_message_callback`, and the rest I leave to the default values.

Are there other prerequisites for communication with flutter using platform messages?

Thanks!

**Comment by stuartmorgan** [comment]
@siavee That has nothing to do with this issue. Most likely you aren't servicing the engine tasks (either by providing a platform task runner, or regularly calling the deprecated `__FlutterEngineFlushPendingTasksNow`).

If that's not it, you should either file a new issue or use a resource like StackOverlfow or Discord, since this issue was about adding specific new functionality for key events.

**Comment by siavee** [comment]
@stuartmorgan Thanks for the response! That's probably it, I'll try providing a task runner and I'm very sorry about the noise.
