### ISSUE TITLE
Show the type name of the Exception?

### ISSUE THREAD

**Issue by mikejurka** [flutter/flutter#3352]
Related to https://github.com/flutter/flutter/pull/3344

Would be great to get the exception type printed out as well. Perhaps FlutterError.dumpErrorToConsole should print it out, something like this?

      print("EXCEPTION: ${s.runtimeType}");
      print (s);
      print("STACK TRACE:\n${s.stackTrace}");

**Comment by mikejurka** [comment]
cc @Hixie @apwilson

**Comment by Hixie** [comment]
can-do.

**Comment by Hixie** [comment]
done
