### ISSUE TITLE
How can I change the text colour when the text is selected/highlighted?

### ISSUE THREAD

**Issue by PabloduPontavice** [flutter/flutter#33538]
## Steps to Reproduce

I have set the textSelectionColor in the Theme in the MaterialApp to white but since most of the text in my application is white I would like to change the text color to black when it is being selected. 
Is there any existing way of doing this and if there isn't could it be implemented?

## Flutter Doctor

Pablos-Mac-mini:soulzoneapp pablodupontavice$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.13.6 17G65, locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.34.0)
[✓] Connected device (6 available)

• No issues found!
```
```

**Comment by HansMuller** [comment]
CC @johnsonmh

**Comment by Hixie** [comment]
I believe we do support changing the text selection color now, see TextSelectionTheme.
