### ISSUE TITLE
maximum widget size

### ISSUE THREAD

**Issue by arunachaleshwaran** [flutter/flutter#33542]

**Comment by arunachaleshwaran** [comment]
when I working in a project I need to know the maximum size that can handle by widgets aka what will be the width and height of the widget or space left by the widgets to work on. by media query, we can able to find the size of the device but I want to find the space left.

**Comment by mateusfsilva** [comment]
Try the widget `LayoutBuilder`
https://api.flutter.dev/flutter/widgets/LayoutBuilder-class.html

**Comment by iapicca** [comment]
Hi @arunachaleshwaran 
does the proposed solution fix the issue?

**Comment by iapicca** [comment]
Hi @arunachaleshwaran
I'm glad to hear that;
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
