### ISSUE TITLE
Theme is being reset when using SplashScreenUntilFirstFrame

### ISSUE THREAD

**Issue by rmtmckenzie** [flutter/flutter#33543]
When SplashScreenUntilFirstFrame is set, whatever the theme is set to for the flutter activity in the AndroidManifest is being reset to `activity.setTheme(android.R.style.Theme_Black_NoTitleBar);`.

This normally doesn't affect much, but it does make the new androidx BiometricPrompt look exceedingly ugly for anything running < P.  And since this is happening programatically and ignoring anything set in the styles/manifest the easiest way to get around it is to then set the theme back to whatever you had it set to before manually which is a bit of an ugly hack.

My workaround is to add a style that just sets the background:

    <style name="DefaultBackground">
        <item name="android:windowBackground">@android:color/background_dark</item>
    </style>

and then re-apply my theme, and override the background in my main activity's onCreate after calling super.onCreate:

        setTheme(R.style.LaunchTheme);
        getTheme().applyStyle(R.style.DefaultBackground, true);

It would be great if either 1) the theme that the [flutter activity delegate sets](https://github.com/flutter/engine/blob/ae14c5a2403ffd60b541035b1ef1a82d33321b43/shell/platform/android/io/flutter/app/FlutterActivityDelegate.java#L459) was configurable, or 2) the flutter activity delegate just does more or less what I did above (i.e. remove the background but keep the rest of the theme), and/or 3) makes the style that is applied configurable as well.

That would make using BiometricPrompt with flutter a much more enjoyable experience =).

**Comment by iapicca** [comment]
Hi @rmtmckenzie 
are you still experiencing this issue with the latest version of Flutter?

**Comment by rmtmckenzie** [comment]
@iapicca  I still have my workaround in place and I don't have time to test right now, but I think it's still an issue judging by the comment in the source code:

        // Resets the activity theme from the one containing the launch screen in the window
        // background to a blank one since the launch screen is now in a view in front of the
        // FlutterView.
        //
        // We can make this configurable if users want it.
        activity.setTheme(android.R.style.Theme_Black_NoTitleBar);

**Comment by camsim99** [comment]
The `Activity`s in question have changed significantly since this bug has been filed, so we think this issue is no longer relevant. We recognize that staleness is not a factor we typically consider in our triage process, but we still think that this is the right call here. Please leave a comment if this issue still comes up!
