### ISSUE TITLE
More than one file was found with OS independent path 'lib/armeabi-v7a/libflutter.so'

### ISSUE THREAD

**Issue by YugeCse** [flutter/flutter#33559]
Hi, friends, I get a problem with my application. when i build my project, but i get an error：
 
More than one file was found with OS independent path 'lib/armeabi-v7a/libflutter.so'

what should i do ? thanks!

**Comment by yy197133** [comment]
Did u solve the problem? I got the same too...

**Comment by praveenb** [comment]
I faced the same issue which fixed after running this 

gradlew flutter:assembleRelease

Hope It may help somebody
