### ISSUE TITLE
[firebase_database] Transaction crashing on v1.5.8+ with Error (Methods marked with @UiThread must be executed on the main thread)

### ISSUE THREAD

**Issue by Saifallak** [flutter/flutter#33562]
## Steps to Reproduce

Just do Transaction like :
```
final dataRef = database.reference().child('path/to/data');

dataRef.runTransaction((MutableData transaction) async{
    transaction.value = (transaction.value ?? 0) + 1;
    return transaction;
});
```

## error

> java.lang.RuntimeException: Methods marked with **@UiThread** must be executed on the main thread. Current thread: **FirebaseDatabaseWorker**

## affected/tested branches with this issue:

- v1.6.6
- v1.7.2 (https://github.com/flutter/flutter/issues/33562#issuecomment-499852519)
- v1.7.5
- v1.7.9 (https://github.com/flutter/flutter/issues/33562#issuecomment-505983248) & (https://github.com/flutter/flutter/issues/33562#issuecomment-506005608)

## known to work as expected with:

- stable branch (v1.5.4-hotfix.2)
- v1.5.8

## plugin version affected with this
well, i think it's a problem with the SDK itself not the plugin, but tested with
- firebase_database: ^3.0.3 (https://github.com/flutter/flutter/issues/33562#issuecomment-506005608)

## related with this error
correct me if i'm wrong to remove any of them

- https://github.com/flutter/engine/pull/8830
- https://github.com/flutter/plugins/pull/1701 
- https://github.com/flutter/flutter/issues/34422
- https://github.com/flutter/flutter/issues/32657
- https://github.com/flutter/flutter/issues/34993

## useful references

- [StackOverflow Issue #56209091]( https://stackoverflow.com/questions/56209091/flutter-firebasedatabase-run-transaction-chash) asked May 19 at 15:06 confirms that it's working on v1.5.8
 
## Crash Log

```
E/RepoOperation( 5654): Caught Throwable.
E/RepoOperation( 5654): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: FirebaseDatabaseWorker
E/RepoOperation( 5654): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/RepoOperation( 5654): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
E/RepoOperation( 5654): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
E/RepoOperation( 5654): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:166)
E/RepoOperation( 5654): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
E/RepoOperation( 5654): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
E/RepoOperation( 5654): 	at io.flutter.plugins.firebase.database.FirebaseDatabasePlugin$1.doTransaction(FirebaseDatabasePlugin.java:345)
E/RepoOperation( 5654): 	at com.google.firebase.database.core.Repo.startTransaction(com.google.firebase:firebase-database@@17.0.0:831)
E/RepoOperation( 5654): 	at com.google.firebase.database.DatabaseReference$4.run(com.google.firebase:firebase-database@@17.0.0:511)
E/RepoOperation( 5654): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
E/RepoOperation( 5654): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/RepoOperation( 5654): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/RepoOperation( 5654): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/RepoOperation( 5654): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/RepoOperation( 5654): 	at java.lang.Thread.run(Thread.java:764)

```
another one is at : (https://github.com/flutter/flutter/issues/33562#issuecomment-506005608)
## Flutter Doctor -v
```
flutter doctor -v
[√] Flutter (Channel dev, v1.6.6, on Microsoft Windows [Version 10.0.17763.437], locale en-US)
    • Flutter version 1.6.6 at E:\flutter
    • Framework revision e1a784ae3f (28 hours ago), 2019-05-28 21:53:03 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\eslam\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5215

[!] VS Code (version 1.28.0)
    • VS Code at C:\Users\eslam\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
    • Windows                   • Windows       • windows-x64 • Microsoft Windows [Version 10.0.17763.437]

! Doctor found issues in 1 category.
```
another one is at (https://github.com/flutter/flutter/issues/33562#issuecomment-506005608)

## experiencing the same issue ?!

"me too" and "+1" comments are pointless.
so just comment if you're going to add new info/logs or tested on new branch/version.
otherwise use ![image](https://user-images.githubusercontent.com/405837/49718793-716d1d80-fc5b-11e8-8a7a-7288f578a66d.png) on the initial comment (this) to up-vote and increase priority.
Comments cause spammy notification mails sent to all subscribers.
If you want to get notified, use ![image](https://user-images.githubusercontent.com/405837/49718838-95306380-fc5b-11e8-8900-0d9173289cc8.png)

**Comment by Saifallak** [comment]
any updates on this ?!

**Comment by jorgevvr** [comment]
Same problem on v1.7.2.

**Comment by Saifallak** [comment]
hi @zoechi , not sure but may you help us on this issue ? , Works well on 1.5.8 and before only

**Comment by jorgevvr** [comment]
someone please??

**Comment by Saifallak** [comment]
still getting the same error on [v1.7.9](https://github.com/flutter/flutter/releases/tag/v1.7.9)

**Comment by lukepighetti** [comment]
Getting transaction errors on Android Lollipop using `firebase_database: ^3.0.3`

**Comment by lukepighetti** [comment]
Switched to `flutter channel stable` and it works. Regression.

**Comment by jorgevvr** [comment]
Looks like no one is watching this issue, 29 days already. :(

**Comment by Saifallak** [comment]
this is critical for app production,
i heard that Flutter Team will pump stable branch to at least 1.7.5 by the end of this month,
but we have to consider this problem,
idk who is the responsible for Firebase Real-time Plugin,
could you mention him/her ? @Hixie

**Comment by jorgevvr** [comment]
If this transaction doesn't works i can't upgrade the version, cause i need it to my app. I will have to stay in the version 1.5 until they fix this.

**Comment by Saifallak** [comment]
+1 but we gonna still need to support 64bit devices in appbundles which are supported in 1.7.5+, i hope we get any attention here

**Comment by jorgevvr** [comment]
Maybe is good you to change the title to [firabase_database]...?

**Comment by Saifallak** [comment]
are those https://github.com/flutter/flutter/issues/34422 & https://github.com/flutter/plugins/pull/1701 & https://github.com/flutter/flutter/issues/32657 related? 

(i know that second one is Cloud_Firestore but it's the same issue i think)

**Comment by jorgevvr** [comment]
> are those #34422 & [flutter/plugins#1701](https://github.com/flutter/plugins/pull/1701) & #32657 related?
> 
> (i know that second one is Cloud_Firestore but it's the same issue i think)

I guess so, the problem started with the cloud firestore in the same version and is a very similar problema, related to the @UIThead.
I don't know why they don't give attention to the Firebase Database too.

**Comment by Saifallak** [comment]
> I guess so, the problem started with the cloud firestore in the same version and is a very similar problema, related to the @UIThead.
> I don't know why they don't give attention to the Firebase Database too.

i think they are fixing problems by priority, "+1"s on the initial comment :\

**Comment by jorgevvr** [comment]
+1 added.

**Comment by lukepighetti** [comment]
@zoechi Please tag this regression, I cannot. Thanks

**Comment by Saifallak** [comment]
@collinjackson **sorry** but this serves **firebase_database** not **cloud_firestore** , so can you add label **firebase_database** too?

**Comment by jorgevvr** [comment]
Some news about this issue?

**Comment by mcagrigoktas** [comment]
Problem is still going

**Comment by lukepighetti** [comment]
@collinjackson Can you please update the tag for firebase_database since this is not a cloud firestore issue?

**Comment by jorgevvr** [comment]
I saw thta the thread was closed, which are the next steps before we can use the fix on our projects?

**Comment by lukepighetti** [comment]
Looks like `3.0.4` is not available on pub yet, not sure how often they do releases. You can try to cherry pick it with this

```
dependencies:
  flutter:
    sdk: flutter

  firebase_database:
    git: 
      url: https://github.com/flutter/plugins.git
      path: packages/firebase_database/
```

**Comment by collinjackson** [comment]
Package version 3.0.4 has been published. Thanks for your patience.

**Comment by jorgevvr** [comment]
Very good, thank you so much. I will try it.

**Comment by AhmedAsser** [comment]
I am facing this crash  using  firestore transaction ,(crashed on emulator and real android device). 
cloud_firestore: 0.12.9+2
Flutter (Channel stable, v1.7.8+hotfix.4)

Some times the transaction work and some times it fails with a crash :
` java.util.concurrent.TimeoutException: Timed out waiting for Task
java.lang.IllegalStateException: Reply already submitted
`

This crash result when the transaction fails and attempt to Deliver the error .
class: `io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.java `

 ```
.addOnCompleteListener(
                  new OnCompleteListener<Map<String, Object>>() {
                    @Override
                    public void onComplete(Task<Map<String, Object>> task) {
                      if (task.isSuccessful()) {
                        result.success(task.getResult());
                      } else {
 line 442 >>>>>>     result.error(
                            "Error performing transaction", task.getException().getMessage(), null);
                      }
                    }
                  });
```

The  value of  `task.getException().getMessage()` which make the transaction to fail (before the crash) was:
`Methods marked with @UiThread must be executed on the main thread. Current thread: pool-3-thread-1`

**Comment by kroikie** [comment]
@Saifallak

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1072. Any further collaboration will be done there.
