### ISSUE TITLE
[web]: flutter_web_localizations/flutter_localizations.dart?

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [flutter/flutter#33560]
Hello there,
Is there a port of of `flutter_localizations/flutter_localizations.dart` for the flutter_web available? If yes, where?

Thank you,

*JasMich*

**Comment by yjbanov** [comment]
This will be auto-fixed when we are in the Flutter SDK.

**Comment by JasMich** [comment]
When about will that be?

**Comment by yjbanov** [comment]
Can't promise dates, but we're actively working on it.
