### ISSUE TITLE
Re-write dev/profile_startup.dart on top of better flutter_drive technology

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3356]
Am I correctly understanding our conversation @yjbanov that we could re-write dev/profile_startup.dart on top of flutter_drive?

I just want a way to get a number of ms between click and first paint for Android and iOS.  Right now dev/profile_startup.dart is android only.

Re-writing dev/profile_startup.dart could obviate the need for fixing flutter trace stop: https://github.com/flutter/flutter/issues/3335

**Comment by yjbanov** [comment]
I think startup profiling should be supported by the `flutter run` command. Startup could be defined as the time between the request to launch the app and the time when the first frame is rendered to the screen by the framework. It would use the same observatory API that `flutter drive` is using but it wouldn't be part of `flutter drive` itself.

If that's ok with you, @eseidelGoogle, I'll start implementing.

**Comment by eseidelGoogle** [comment]
sgtm.  I'm all about making startup easier to profile. :)

**Comment by eseidelGoogle** [comment]
FYI @devoncarew

**Comment by eseidelGoogle** [comment]
profile_startup is currently busted:

```
dev/profile_startup.dart examples/material_gallery -v
Profiling startup using flutter run --trace-startup.
Measuring from first trace event to completion of first frame upload.
aka NativeViewGLSurfaceEGL:RealSwapBuffers.

NOTE: If device is not on/unlocked tracing may fail.

5 runs using examples/material_gallery:
Running lib/main.dart on Nexus 5...
Trace file saved to trace_1.json
Unhandled exception:
Invalid argument(s): traceEvents
#0      List.[] (dart:core-patch/growable_array.dart:148)
#1      timeToFirstFrame (file:///src/flutter/dev/profile_startup.dart:34:22)
#2      test.<test_async_body> (file:///src/flutter/dev/profile_startup.dart:63:10)
#3      _RootZone.runUnary (dart:async/zone.dart:1137)
#4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:553)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:639)
#6      _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:295)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```
