### ISSUE TITLE
Flutter Plugin v35.0.1 Incompatible with Android Studio Version 3.5 beta3

### ISSUE THREAD

**Issue by lionoggo** [flutter/flutter#33561]

**Comment by cipriotto** [comment]
Android Studio 3.5 beta 3 is blocked at launch because of flutter plugin

**Comment by lionoggo** [comment]
> Hi @lionoggo
> are you still experiencing this issue with the latest version of Flutter?
> If so please reply attaching your `flutter doctor -v`

Now, it's work, thanks.

**Comment by janmoppel** [comment]
Glad to hear, it works now! Closing the issue.
