### ISSUE TITLE
Widget get built twice

### ISSUE THREAD

**Issue by edenchen123** [flutter/flutter#33566]
I came across follow issue when debugging my flutter app. Build method called twice.

```
import 'dart:math';
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    initialRoute: '/',
    routes: <String, WidgetBuilder>{
      '/': (context) => HomePage()
    },
  ));
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final num = Random().nextInt(10000);
    print(num);
    return Scaffold(
      appBar: AppBar(
        title: Text('Home'),
      ),
      body: new Center(
        child: Text('Num: $num'),
      ),
    );
  }
}
```

**Comment by rmtmckenzie** [comment]
Out of curiosity, why do you think this is an issue? The flutter engine can more or less arbitrarily decide when to rebuild and that shouldn't ever affect your UI. The point of widgets is that they contain a state (or a static state in the case of stateless widgets) and simply display that state - if you really want a randomly generated number you should do that outside of the build function.

**Comment by ph55** [comment]
Even following simple app:

```dart
import 'package:flutter/widgets.dart';

void main() {
  runApp(Home());
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('home....');
    return Container();
  }
}
```

Without any state or variables will build twice and produce following output:

```
Performing hot restart...
Syncing files to device iPhone 11 Pro Max...
Restarted application in 836ms.
flutter: home....
flutter: home....
```

So `out of curiosity`, why flutter decides to build it twice.

**Comment by sanuzzi** [comment]
Hi, can you reopen this issue?
I tried the example from @ph55 and it happens the same with v1.17.1

I have a use case when I need to show a dialog right after a navigation, and this issue causes two overlapped dialogs. In addition to a waste of processing resources of course!

Here is a simplified example that demonstrates the issue with different cases in `SecondScreen`:
```
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        initialRoute: "/",
        title: "Example",
        theme: ThemeData(primarySwatch: Colors.blue),
        routes: {
          "/": (context) => MainScreen(),
          "/second_screen": (context) => SecondScreen()
        },
      );
}

enum MyEnum { VALUE_1, VALUE_2, VALUE_3 }

class MainScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(
          title: Text("Example"),
        ),
        body: Center(
          child: RaisedButton(
            child: Text("Go to second screen"),
            onPressed: () {
              Navigator.pushNamed(
                context,
                "/second_screen",
                arguments: MyEnum.VALUE_2,
              );
            },
          ),
        ),
      );
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print("SecondScreen");
    return Scaffold(
      appBar: AppBar(
        title: Text("Example"),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            WithArgumentAndPopup(),
            WithArgument(),
            WithPopup(),
            WithNothing()
          ],
        ),
      ),
    );
  }
}

class WithArgumentAndPopup extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    MyEnum enumValue = ModalRoute.of(context).settings.arguments;
    print("WithArgumentAndPopup (built twice)");
    WidgetsBinding.instance.addPostFrameCallback((_) => showDialog(
        context: context,
        builder: (BuildContext context) => Text("Some Popup")));
    return Text("Value was: $enumValue");
  }
}

class WithArgument extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    MyEnum enumValue = ModalRoute.of(context).settings.arguments;
    print("WithArgument (built twice)");
    return Text("Value was: $enumValue");
  }
}

class WithPopup extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print("WithPopup (built once)");
    WidgetsBinding.instance.addPostFrameCallback((_) => showDialog(
        context: context,
        builder: (BuildContext context) => Text("Some Popup")));
    return Text("I have just a popup");
  }
}

class WithNothing extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print("WithNothing (built once)");
    return Text("I only have my text");
  }
}
```
Console output:
I/flutter (26678): SecondScreen
**I/flutter (26678): WithArgumentAndPopup (built twice)**
**I/flutter (26678): WithArgument (built twice)**
I/flutter (26678): WithPopup (built once)
I/flutter (26678): WithNothing (built once)
**I/flutter (26678): WithArgumentAndPopup (built twice)**
**I/flutter (26678): WithArgument (built twice)**

Fluter doctor output:
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [VersiÃ³n 10.0.18362.778], locale es-AR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[√] Connected device (1 available)

**Comment by skmishu** [comment]
Same here
But I found it only one situation while i connect my phone with Android studio

**Comment by normancarcamo** [comment]
Same here in Jun 2020.

**Comment by tgpsantos** [comment]
Same here with a simple 

Future<void> main() async {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    debugPrint("Building App");
    return Container();
  }
}

**Comment by MaheshMadushan** [comment]
same issue happening here.
`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}


class _HomeState extends State<Home> {
  List<String> myList = ['FOOD 1','FOOD 2','FOOD 3'];
  List<Widget> sliverChildList =[];
  int counter = 0;

  //create card widget
  Widget createCard(String text,String imageUrl){
    return Card(
        margin: EdgeInsets.all(10),
        elevation: 50,
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.horizontal(
              left: Radius.elliptical(20, 20),
              right:Radius.elliptical(20, 20),
            )
        ),
        child: Container(
            padding: EdgeInsets.all(10),
            height: 200.0,
            width: MediaQuery.of(context).size.width,
            child: Row(
//              crossAxisAlignment: CrossAxisAlignment.stretch,
//              mainAxisAlignment: MainAxisAlignment.start,
            children: <Widget>[
             CircleAvatar(
               backgroundImage: AssetImage('assets/image.png',),
               radius: 55,
             ),
              SizedBox(width: 30,),
              Expanded(
                child: Center(
                  child: Text(
                    text,
                    textAlign: TextAlign.center,
                    softWrap: true,
                    overflow: TextOverflow.visible,
                    style: DefaultTextStyle.of(context).style.apply(fontSizeFactor: 0.55,color: Colors.black,decoration: TextDecoration.none),
                  ),
                ),
              ),
            ],
          ),
        ),

      );

  }

//  create sliver child list
  List<Widget> createSliverChildList(myList){
    
    myList.forEach((element) => sliverChildList.add(createCard(element, 'assets/image.png') ?? Text('null')));
    return sliverChildList;
  }

  @override
  Widget build(BuildContext context) {
    setState(() {
      counter++;
    });
    print('$counter build');
    return Scaffold(
        body:CustomScrollView(
      slivers: <Widget>[
        SliverAppBar(
          flexibleSpace: FlexibleSpaceBar(
            title: Text("Food ingredients"),
            centerTitle: true,
          ),
          expandedHeight: 200.0,
          leading: Icon(Icons.menu),
        ),
        SliverOpacity(
          opacity: 0.4,
          sliver: SliverList(
              delegate: SliverChildListDelegate(createSliverChildList(myList)),
          ),
        ),
//        SliverFixedExtentList(
//          itemExtent: 200.0,
//          delegate: SliverChildListDelegate(createSliverChildList(myList)),
//        ),
      ],
    ));
  }
}

output
Performing hot restart...
Syncing files to device TA 1021...
Restarted application in 2,113ms.
I/flutter (27175): 1 build
I/flutter (27175): 2 build

**Comment by MaheshMadushan** [comment]
`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}


class _HomeState extends State<Home> {
  List<String> myList = ['FOOD 1','FOOD 2','FOOD 3'];
  List<Widget> sliverChildList =[];
  int counter = 0;

  //create card widget
  Widget createCard(String text,String imageUrl){
    return Card(
        margin: EdgeInsets.all(10),
        elevation: 50,
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.horizontal(
              left: Radius.elliptical(20, 20),
              right:Radius.elliptical(20, 20),
            )
        ),
        child: Container(
            padding: EdgeInsets.all(10),
            height: 200.0,
            width: MediaQuery.of(context).size.width,
            child: Row(
//              crossAxisAlignment: CrossAxisAlignment.stretch,
//              mainAxisAlignment: MainAxisAlignment.start,
            children: <Widget>[
             CircleAvatar(
               backgroundImage: AssetImage('assets/image.png',),
               radius: 55,
             ),
              SizedBox(width: 30,),
              Expanded(
                child: Center(
                  child: Text(
                    text,
                    textAlign: TextAlign.center,
                    softWrap: true,
                    overflow: TextOverflow.visible,
                    style: DefaultTextStyle.of(context).style.apply(fontSizeFactor: 0.55,color: Colors.black,decoration: TextDecoration.none),
                  ),
                ),
              ),
            ],
          ),
        ),

      );

  }

//  create sliver child list
  List<Widget> createSliverChildList(myList){

    myList.forEach((element) => sliverChildList.add(createCard(element, 'assets/image.png') ?? Text('null')));
    return sliverChildList;
  }

  @override
  Widget build(BuildContext context) {
    setState(() {
      counter++;
    });
    print('$counter build');
    return Scaffold(
        body:CustomScrollView(
      slivers: <Widget>[
        SliverAppBar(
          flexibleSpace: FlexibleSpaceBar(
            title: Text("Food ingredients"),
            centerTitle: true,
          ),
          expandedHeight: 200.0,
          leading: Icon(Icons.menu),
        ),
        SliverOpacity(
          opacity: 0.4,
          sliver: SliverList(
              delegate: SliverChildListDelegate(createSliverChildList(myList)),
          ),
        ),
//        SliverFixedExtentList(
//          itemExtent: 200.0,
//          delegate: SliverChildListDelegate(createSliverChildList(myList)),
//        ),
      ],
    ));
  }
}
`

**Comment by MaheshMadushan** [comment]
same issue happening here.

```import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}


class _HomeState extends State<Home> {
  List<String> myList = ['FOOD 1','FOOD 2','FOOD 3'];
  List<Widget> sliverChildList =[];
  int counter = 0;

  //create card widget
  Widget createCard(String text,String imageUrl){
    return Card(
        margin: EdgeInsets.all(10),
        elevation: 50,
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.horizontal(
              left: Radius.elliptical(20, 20),
              right:Radius.elliptical(20, 20),
            )
        ),
        child: Container(
            padding: EdgeInsets.all(10),
            height: 200.0,
            width: MediaQuery.of(context).size.width,
            child: Row(
//              crossAxisAlignment: CrossAxisAlignment.stretch,
//              mainAxisAlignment: MainAxisAlignment.start,
            children: <Widget>[
             CircleAvatar(
               backgroundImage: AssetImage('assets/image.png',),
               radius: 55,
             ),
              SizedBox(width: 30,),
              Expanded(
                child: Center(
                  child: Text(
                    text,
                    textAlign: TextAlign.center,
                    softWrap: true,
                    overflow: TextOverflow.visible,
                    style: DefaultTextStyle.of(context).style.apply(fontSizeFactor: 0.55,color: Colors.black,decoration: TextDecoration.none),
                  ),
                ),
              ),
            ],
          ),
        ),

      );

  }

//  create sliver child list
  List<Widget> createSliverChildList(myList){

    myList.forEach((element) => sliverChildList.add(createCard(element, 'assets/image.png') ?? Text('null')));
    return sliverChildList;
  }

  @override
  Widget build(BuildContext context) {
    setState(() {
      counter++;
    });
    print('$counter build');
    return Scaffold(
        body:CustomScrollView(
      slivers: <Widget>[
        SliverAppBar(
          flexibleSpace: FlexibleSpaceBar(
            title: Text("Food ingredients"),
            centerTitle: true,
          ),
          expandedHeight: 200.0,
          leading: Icon(Icons.menu),
        ),
        SliverOpacity(
          opacity: 0.4,
          sliver: SliverList(
              delegate: SliverChildListDelegate(createSliverChildList(myList)),
          ),
        ),
//        SliverFixedExtentList(
//          itemExtent: 200.0,
//          delegate: SliverChildListDelegate(createSliverChildList(myList)),
//        ),
      ],
    ));
  }
}

```

output


> Performing hot restart...
> Syncing files to device TA 1021...
> Restarted application in 2,113ms.
> I/flutter (27175): 1 build
> I/flutter (27175): 2 build

**Comment by MatthewCoetzee412** [comment]
For anybody still struggling with this, this article might help: https://flutterigniter.com/future-async-called-multiple-times/

**Comment by battlecook** [comment]
Same here in November 2020.

**Comment by papmodern** [comment]
Same here in Jan 2021 :D

**Comment by ShahabShahab** [comment]
Same here in Jan 2021 :)

I think anybody who might wanna get rid of this feature or bug, Designing a State Machine is considerable. It might be not so viable but will solve the so-called issue for now.

**Comment by roeniss** [comment]
This issue doesn't appear during development with hot-reloading. Only the first time it happens.

```dart
void main() {
  debugPrint('main function started...');
  runApp(
    ChangeNotifierProvider<AppStateModel>(
      create: (_) => AppStateModel()..loadInitialState(), // No 'notifyListeners()' in `loadInitialState()`
      child: Consumer<AppStateModel>(builder: (context, _, __) {
        debugPrint('root widget created...');
        return App();
      }),
    ),
  );
}
```

console result:

```bash
Performing hot restart...
Syncing files to device iPhone 8...
Restarted application in 402ms.
flutter: main function started...
flutter: loadInitialState done (notifyListeners not used at all)
flutter: root widget created...
flutter: build CupertinoStoreHomePage (root)
flutter: root widget created...
flutter: build CupertinoStoreHomePage (root)
```

**Comment by rajeshpatil95** [comment]
Same here April 11 2021

**Comment by nawzhinhamza** [comment]
Same here in May :(

**Comment by battlecook** [comment]
Still Same here :(

I also asked a question on stackoverflow. But no one has an answer.

https://stackoverflow.com/questions/64834702/why-build-function-gets-called-twice-when-hot-restarting

**Comment by omerasif57** [comment]
In my case it is effecting the animation. My widget tree is slightly complex and build is called more than twice (sometimes). I am a bit naive to flutter so will try to investigate and restructure my code.
My usecase involves theme switching (dark-light) with timeDilation=3.0. Animation plugin works fine with a simple example code.

Anyway, any advise would be appreciated.
Coming from [here](https://github.com/flutter/flutter/issues/57353#issuecomment-629569076)

**Comment by l-qd** [comment]
Same here (end of June 2021). I tried to use the initializer in a stateful widget to make sure and as expected, it was initialized, deactivated, then initialized again

**Comment by AkashDeveloper8758** [comment]
same here in july 6, this is really a issue

**Comment by FL8DEV** [comment]
Same, everything was working fine just a week ago, until I decided to resume working on the project today and came across this problem.

**Comment by FL8DEV** [comment]
I tried a workaround and it worked for me.
-I've declared a static boolean variable initialized to false
-In the method that runs before returning the widget in the build method, I check if the static bool is true then return void
-the bool is assigned to true at the end of the method obviously

**Comment by LongZhai** [comment]
why this ticket is closed?
rebuilding twice will interrupt my video initializer and firbase init call.

**Comment by Reitenator** [comment]
I don't know if this applies to anyone else, but this happened to me as well, but I think I was able to figure out what happened (but not why).

What I figured out is that if I use Visual Studio Code to Run the app (Start Debugging (or pressing F5)) the error occurs, i.e. it seems to re-build the widget two times. 

If I use the terminal to run it (`flutter run -d chrome`), however, it seems that it actually only build it once. 

I therefore have a theory that something in the visual studio code editor is making this bug, but that's just a speculative guess.

**Comment by MohammadAmin3509** [comment]
hello everyone 
i hope you are doing fine

this is not flutter bug ! this is vscode bug.
if you try your code in android studio or run your app with `flutter run` everything wroking fine.
and you will not have this bug in release mode.

finally i updated my vscode and now everything works fine

**Comment by erikmompean** [comment]
> hello everyone
> i hope you are doing fine
> 
> this is not flutter bug ! this is vscode bug.
> if you try your code in android studio or run your app with `flutter run` everything wroking fine.
> and you will not have this bug in release mode.
> 
> finally i updated my vscode and now everything works fine

It's happening to me in Android Studio and VSCode with latest version, but with `flutter run`  it works like a charm. 

The problem on IDEs still in my case, and it's annoying so the issue persist.

**Comment by MohammadAmin3509** [comment]
> > hello everyone
> > i hope you are doing fine
> > this is not flutter bug ! this is vscode bug.
> > if you try your code in android studio or run your app with `flutter run` everything wroking fine.
> > and you will not have this bug in release mode.
> > finally i updated my vscode and now everything works fine
> 
> It's happening to me in Android Studio and VSCode with latest version, but with `flutter run` it works like a charm.
> 
> The problem on IDEs still in my case, and it's annoying so the issue persist.

hmm try it: update your flutter plugin
 i also updated my plugins

**Comment by Mabsten** [comment]
With the last stable Flutter Sdk (`2.2.3`) and the last IntelliJ (2021.2) with flutter plugin (58.0.4) the 'fact' (build called twice) occurs in the following scenario:
(tested on Android 10 and Windows 10 as target platforms)
- **only after Hot Restart** (not after first startup or Hot reload)
- **only** launching the flutter application **through the IDE** (not launching the app 'manually' from the command line with `flutter run`).
In a previous post the unnecessary rebuild was also reported for the latest version of VSCode. 

The flutter team was clear that the unnecessary 'rebuild' at launch **should not be considered a bug***, and that therefore the flow of an app's execution should not rely on a fixed number of build's executions (for example, if an app displays a dialog at the first run of `build()`, this flow will have to be modified, for example by displaying the dialog using `WidgetsBinding.instance.addPostFrameCallback()` in `initState()`).

But on the other hand I think it is normal that during the development of an app, to understand if the behavior is as expected, the build's executions are logged/checked, and that an unexpected execution can confuse the developers and cause waste of time to ascertain the causes.
So I think this issue should be reopened, and this unexpected behavior should be documented or somehow explained.

**Comment by banderberg** [comment]
I agree, this should be reopened.  I wasted a good amount of time this morning trying to figure out what was going on.

**Comment by MohammadAmin3509** [comment]
Make your widget constructor const like :

runApp(const MarketerApp());

it's not a problem at all but if it's make problem to you , const constructor will fix your problem
