### ISSUE TITLE
[google_maps_flutter] support KML file 

### ISSUE THREAD

**Issue by longgui0318** [flutter/flutter#33563]
how can i use kml file in google_maps_flutter?

**Comment by vaimikpatel2908** [comment]
did u find the way to use kml in goolge maps flutter?

**Comment by longgui0318** [comment]
> did u find the way to use kml in goolge maps flutter?

Sorry, I didn't find it because no one is concerned about this issue, so I closed it.

**Comment by vaimikpatel2908** [comment]
No i haven't found because still google_maps_flutter haven't provided support for kml yet.

**Comment by darren-f5s** [comment]
Send me an example of a KML file - I am looking at writing a custom integration layer for `google_maps_flutter`.

**Comment by darren-f5s** [comment]
I have created a KML conversion process, is anyone still interested in this?

**Comment by vaimikpatel2908** [comment]
I am interested can you send it to me i will try and just let me know how it works

**Comment by vaimikpatel2908** [comment]
> I have created a KML conversion process, is anyone still interested in this?

you can send it on vaimikpatel2908@gmail.com.

**Comment by darren-f5s** [comment]
Waiting for confirmation on if I can share the code, will update when I know. More interest here will let me push the request

**Comment by mdehsasw** [comment]
I am extremely interested in this.

**Comment by vaimikpatel2908** [comment]
@darren-f5s  did u get confirmation or not?

**Comment by GeekBii** [comment]
also interrested here.

**Comment by vinnytwice** [comment]
Any update on the subject? Really need it. @darren-f5s any chance to receive it?

**Comment by ntancnit** [comment]
@darren-f5s is this feauture ready to use?

**Comment by joseluiz2323** [comment]
would also like to receive luizzzz1996@gmail.com

**Comment by dc-95** [comment]
> I have created a KML conversion process, is anyone still interested in this?

@darren-f5s hoping to know how to do it as well.

**Comment by lenilmarcenal** [comment]
Veja em: https://stackoverflow.com/questions/58242229/does-google-maps-flutter-or-any-other-map-plugin-for-flutter-supports-kml-file-f

**Comment by lenilmarcenal** [comment]
Veja também em:

https://github.com/googlemaps/android-maps-utils/commit/d606fcde40467abb5fae2ba78b8562a2cd1c517b

**Comment by fiorellasaro** [comment]
> I have created a KML conversion process, is anyone still interested in this?

Hi!! I'm also interested. Can you send me to fiorellasaro27@gmail.com, please??

**Comment by effedi** [comment]
Hello,
I am interested as well.
Thanks a lot .

**Comment by brunozaranza** [comment]
I am interested as well. Pls!

**Comment by sidwokeup12** [comment]
hey anything???

**Comment by mdehsasw** [comment]
Hi @darren-f5s 

Is there any movement on this?

thanks

**Comment by brunozaranza** [comment]
I got it for Android. But not yet for iOS...

**Comment by mdehsasw** [comment]
> I got it for Android. But not yet for iOS...

Would you be able to send it to me?

**Comment by mdehsasw** [comment]
> > did u find the way to use kml in goolge maps flutter?
> 
> Sorry, I didn't find it because no one is concerned about this issue, so I closed it.

I think there is definitely some interest.

**Comment by sidwokeup12** [comment]
> > I got it for Android. But not yet for iOS...
> 
> @brunozaranza Would you be able to send it to me?

me also

**Comment by fiorellasaro** [comment]
> I got it for Android. But not yet for iOS...

@brunozaranza please, send it 🙌🏼

**Comment by brunozaranza** [comment]
I wrote how do it in my language (pt-BR). This weekend, I will write in English, but if you want try use translator (but there are a biggest probability you be brazilians like me kkkkk).

https://medium.com/@brunozaranza/google-maps-flutter-com-kml-e750c8c5b793

This can still be improved, I will be grateful for the comments.

**Comment by effedi** [comment]
Obrigado !

Francesco Delre

CEng - Chartered Engineer
MRINA - Member of the Royal Institutions of Naval Architects

www.fdquadro.com
francesco@fdquadro.com

**Comment by fiorellasaro** [comment]
> I wrote how do it in my language (pt-BR). This weekend, I will write in English, but if you want try use translator (but there are a biggest probability you be brazilians like me kkkkk).
> 
> https://medium.com/@brunozaranza/google-maps-flutter-com-kml-e750c8c5b793
> 
> This can still be improved, I will be grateful for the comments.

@brunozaranza thank you so much!

**Comment by KimberleeDArmstrong** [comment]
I would like to have this for Android and iOS as well.

**Comment by vaimikpatel2908** [comment]
https://github.com/flutter/flutter/issues/50636

Please follow this link and give thumbs up to this issue. As of my knowledge, they prioritize issues based on how many people are interested and how severe the issue is. Hope so your thumbs up will drag their attention to this issue.

**Comment by Nagavikas96** [comment]
> I got it for Android. But not yet for iOS...

Hey Hi,
Can you please share with me a code snippet for kml map for android. I got stuck in kml can you please help me.

**Comment by bradleyloh** [comment]
> I got it for Android. But not yet for iOS...

Hi, 
Can i have the it? thank you! 
bradleylohwenhui@gmail.com

**Comment by Tobenna-KA** [comment]
hi, can you please share the code snippet on how to do this for android and ios? speedflakes@gmail.com

**Comment by git-gnan** [comment]
I am interested in it as well. Can you please share the code ?
