### ISSUE TITLE
Even spacing and screen keyboard

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#33579]
Repro case attached below

Problems:
1. with resizeToAvoidBottomPadding = true all spacing disappears and I get a 'bottom overflowed' error
2. with resizeToAvoidBottomPadding = false keyboard occludes the text edit
3. if I replace Column with a ListView then there's no easy way to space the controls evenly for an arbitrary screen size

I need to preserver the spacing and at the same time the edit to scroll up when keyboard shows
Does flutter allow this?

I think this question belongs here rather than on stackoverflow (where I usually post my 'how to do' questions) because it looks like a flutter limitation?

Ideally I would like a way to 'pan' the entire screen vertically by {keyboard height} x {relative edit Y}.

![Untitled](https://user-images.githubusercontent.com/1481807/58636606-608f9180-82f9-11e9-9115-beda4b618052.png)

## Source code

```
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final baseLayout = Column(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Container(
          color: Colors.red,
          child: Text('1'),
          height: 99,
        ),
        Container(
          color: Colors.yellow,
          child: Text('2'),
          height: 111,
        ),
        Container(
          color: Colors.lightGreenAccent,
          child: Text('3'),
          height: 99,
        ),
        TextField(),
        RaisedButton(
          color: Colors.green,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(22),
          ),
          child: Text(
            'Button',
          ),
        ),
      ],
    );
    return Scaffold(
//      resizeToAvoidBottomPadding: false,
      body: Container(
        color: Colors.black12,
        margin: const EdgeInsets.all(11),
        child: baseLayout,
      ),
    );
  }
}
```

**Comment by duzenko** [comment]
Somewhat similar to #13339 but exceeds its scope

**Comment by duzenko** [comment]
Based on this [answer  ](https://stackoverflow.com/a/54047013/505984)I got a half-cooked workaround 
```
        child: Container(
          child: baseLayout,
          transform: Matrix4.translationValues(0, -MediaQuery.of(context).viewInsets.bottom / 2, 0),
        ),
```
But I still need to figure out the actual absolute screen coordinate for the control I want to show right above the keyboard

**Comment by HansMuller** [comment]
If I'm understanding this correctly, you want the layout to be a column that's roughly as big as the screen. Within that column, children will be spaced evenly. The column will be contained by a SingleChildScrollView because the Scaffold's [resizeToAvoidBottomInset](https://api.flutter.dev/flutter/cupertino/CupertinoTabScaffold/resizeToAvoidBottomInset.html) is true - so the scaffold's body will shrink when the keyboard appears.

To do this you could wrap the scaffold's body with a LayoutBuilder, so that you know how much vertical space is available (that's the "roughly as big as the screen" bit).

**Comment by duzenko** [comment]
> If I'm understanding this correctly, you want the layout to be a column that's roughly as big as the screen. 
It does not need to be a Column - but Column is the only way I know in Flutter that offers equal spacing for its children. But yeah, I need to space it across the screen height (that's the app design I need to implement)

> The column will be contained by a SingleChildScrollView because the Scaffold's resizeToAvoidBottomInset is true - so the scaffold's body will shrink when the keyboard appears.
Is that a suggestion or you somehow concluded that from my message? SingleChildScrollView did not work for me because it shrank its child causing no children spacing at all.

> To do this you could wrap the scaffold's body with a LayoutBuilder, so that you know how much vertical space is available (that's the "roughly as big as the screen" bit).
I can try that - should I retrieve the app client space and pass it to LayoutBuilder as a desired size?

**Comment by duzenko** [comment]
I think LayoutBuilder is not necessary here
I ended up with just SingleChildScrollView + ConstrainedBox
Thanks for the hint

```
    SchedulerBinding.instance.addPostFrameCallback((_) {
      Scrollable.ensureVisible(scrollKey.currentContext, alignment: 1);
    });
    return Scaffold(
      body: SingleChildScrollView(
        child: ConstrainedBox(
          constraints: BoxConstraints(minHeight: MediaQuery.of(context).size.height),
          child: Container(
            margin: const EdgeInsets.symmetric(horizontal: 33),
            child: baseLayout,
          ),
        ),
      ),
    );

```

**Comment by HansMuller** [comment]
Glad to hear that you were able to get things going! Using a the BoxConstraints height provided by a LayoutBuilder, instead of the MediaQuery's  height, would work a little better if the layout further constrained the Scaffold's body. For example if you added an AppBar.

**Comment by duzenko** [comment]
> BoxConstraints height provided by a LayoutBuilder

Sorry, could you elaborate on that? I would assume that if Scaffold resizes then the nested LayoutBuilder will resize as well? How do I control that?

**Comment by HansMuller** [comment]
Sorry, of course you're right: in this case we don't want the height of the lists's content to change when the keyboard's appearance changes the height of the Scaffold's body.
