### ISSUE TITLE
[image_picker] Permission denied with camera plugin

### ISSUE THREAD

**Issue by FilipeOS** [flutter/flutter#33578]
So, I've tried so hard to make the camera work but I can only use the gallery.

Dependencies:
```
image_picker: ^0.6.0+8
permission_handler: ^3.1.0
```

/main/AndroidManifest.xml
`<uses-permission android:name="android.permission.CAMERA"/>`
(If I don't put this it says that I don't have permissions on manifest.)

Checking permissions and _getPhoto:
```
Future<bool> checkAndRequestCameraPermissions() async {
    PermissionStatus permission = await PermissionHandler().checkPermissionStatus(PermissionGroup.camera);
    if (permission != PermissionStatus.granted) {
      Map<PermissionGroup, PermissionStatus> permissions =
          await PermissionHandler().requestPermissions([PermissionGroup.camera]);
      return permissions[PermissionGroup.camera] == PermissionStatus.granted;
    } else {
      return true;
    }
  }

Future _getPhoto() async {
    if (await checkAndRequestCameraPermissions()) {
      var imageFile = await ImagePicker.pickImage(source: ImageSource.camera);

      if (imageFile != null) {
        setState(() {
          sendImageFile = imageFile;
          isLoading = true;
        });
        _uploadFile();
      }
    }
  }
```

- On the first execution I get the permissions popup, I Allow and nothing happens (but on settings I have permission to use camera now).
- If I click again it throws: `Unhandled Exception: PlatformException(already_active, Image picker is already active, null)`

- If I close and open again when I press the Camera button on my flutter app, I get :
`E/MethodChannel#plugins.flutter.io/image_picker(21872): Failed to handle method call
E/MethodChannel#plugins.flutter.io/image_picker(21872): java.lang.RuntimeException: java.io.IOException: Permission denied
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.createTemporaryWritableFile(ImagePickerDelegate.java:360)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.createTemporaryWritableImageFile(ImagePickerDelegate.java:346)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.launchTakeImageWithCameraIntent(ImagePickerDelegate.java:335)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.takeImageWithCamera(ImagePickerDelegate.java:316)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at io.flutter.plugins.imagepicker.ImagePickerPlugin.onMethodCall(ImagePickerPlugin.java:160)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at android.os.Looper.loop(Looper.java:181)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at android.app.ActivityThread.main(ActivityThread.java:7032)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/MethodChannel#plugins.flutter.io/image_picker(21872): Caused by: java.io.IOException: Permission denied
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at java.io.File.createTempFile(File.java:2018)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.createTemporaryWritableFile(ImagePickerDelegate.java:358)
E/MethodChannel#plugins.flutter.io/image_picker(21872): 	... 14 more
E/flutter (21872): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, java.io.IOException: Permission denied, null)
E/flutter (21872): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (21872): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter (21872): <asynchronous suspension>
E/flutter (21872): #2      ImagePicker.pickImage (package:image_picker/image_picker.dart:56:40)
E/flutter (21872): <asynchronous suspension>
E/flutter (21872): #3      _ChatScreenState._getPhoto (package:chat/ui/screens/chat.dart:196:41)
E/flutter (21872): <asynchronous suspension>
E/flutter (21872): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
E/flutter (21872): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
E/flutter (21872): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
E/flutter (21872): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
E/flutter (21872): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:177:9)
E/flutter (21872): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:436:9)
E/flutter (21872): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (21872): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (21872): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:221:19)
E/flutter (21872): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
E/flutter (21872): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (21872): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (21872): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (21872): #17     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (21872): #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (21872): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (21872): #20     _invoke1 (dart:ui/hooks.dart:233:10)
E/flutter (21872): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
E/flutter (21872): 
V/NativeCrypto(21872): Read error: ssl=0x797b4c0308: I/O error during system call, Software caused connection abort
V/NativeCrypto(21872): Write error: ssl=0x797b4c0308: I/O error during system call, Broken pipe
W/ManagedChannelImpl(21872): [{0}] Failed to resolve name. status={1}
V/NativeCrypto(21872): Write error: ssl=0x797b4c0308: I/O error during system call, Broken pipe
I/OkHttpClientTransport(21872): Failed closing connection
I/OkHttpClientTransport(21872): javax.net.ssl.SSLException: Write error: ssl=0x797b4c0308: I/O error during system call, Broken pipe
I/OkHttpClientTransport(21872): 	at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_write(Native Method)
I/OkHttpClientTransport(21872): 	at com.google.android.gms.org.conscrypt.NativeSsl.write(:com.google.android.gms@17122037@17.1.22 (100400-245988633):4)
I/OkHttpClientTransport(21872): 	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(:com.google.android.gms@17122037@17.1.22 (100400-245988633):6)
I/OkHttpClientTransport(21872): 	at okio.Okio$1.write(Okio.java:79)
I/OkHttpClientTransport(21872): 	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
I/OkHttpClientTransport(21872): 	at okio.RealBufferedSink.close(RealBufferedSink.java:241)
I/OkHttpClientTransport(21872): 	at io.grpc.okhttp.internal.framed.Http2$Writer.close(Http2.java:569)
I/OkHttpClientTransport(21872): 	at io.grpc.okhttp.AsyncFrameWriter$14.run(AsyncFrameWriter.java:221)
I/OkHttpClientTransport(21872): 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
I/OkHttpClientTransport(21872): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I/OkHttpClientTransport(21872): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I/OkHttpClientTransport(21872): 	at java.lang.Thread.run(Thread.java:764)
W/System  (21872): A resource failed to call close. 
W/ctec.cha(21872): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, linking)
W/System  (21872): A resource failed to call close. `

```
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: MeApp.appState, MeAppApp.title - lib\main.dart:25:7 - must_be_immutable
   info - Unused import: 'package:mechat/ui/widgets/jumping_dots.dart' - lib\ui\screens\chat.dart:21:8 - unused_import
warning - The parameter 'onPressed' is required - lib\ui\screens\chat.dart:719:15 - missing_required_param
warning - The parameter 'onWillPop' is required - lib\ui\screens\messages.dart:217:15 - missing_required_param
warning - The parameter 'onPressed' is required - lib\ui\screens\sign_in.dart:233:56 - missing_required_param
warning - The parameter 'onPressed' is required - lib\ui\screens\sign_in.dart:286:56 - missing_required_param
   info - Unused import: 'dart:io' - lib\ui\screens\user_profile.dart:12:8 - unused_import
```

**Comment by timsneath** [comment]
Filipe, this may be better suited for [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) than a GitHub issue, unless you believe there's a bug in the Flutter plug-in?

**Comment by FilipeOS** [comment]
@timsneath I think it's a bug because I can't get it working using documentation, and with or without the permission_handler plugin...

I hope some expert helps

**Comment by pearlmaknun** [comment]
i also have the same problem, is this issue still have no update?

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
Thank you
