### ISSUE TITLE
[desktop] Version 1.6.7 breaked Mac Desktop Build

### ISSUE THREAD

**Issue by mkiisoft** [flutter/flutter#33570]
Error:

```
** BUILD FAILED **


The following build commands failed:
	PrecompileSwiftBridgingHeader normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
Finished with error: Build process failed
```

Using: `Flutter (Channel master, v1.6.7-pre.24, on Mac OS X 10.14.5 18F132, locale en-US)`

**Comment by mkiisoft** [comment]
Working on Dev Channel:

`Flutter (Channel dev, v1.6.6, on Mac OS X 10.14.5 18F132, locale en-US)`

**Comment by stuartmorgan** [comment]
This was expected; see https://github.com/google/flutter-desktop-embedding/pull/403
