### ISSUE TITLE
Firebase-database not working on desktop

### ISSUE THREAD

**Issue by bmaczak** [flutter/flutter#33575]
When building for desktop (macOS) the firebase-database plugin throws an exception. Is Firebase not supported on desktop yet?

Log:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      Query._observe.<anonymous closure> (package:firebase_database/src/query.dart:53:38)
#2      _runGuarded (dart:async/stream_controller.dart:805:24)
#3      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
#4      _ControllerStream._createSubscription (dart:async/stream_controller.dart:818:19)
#5      _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
#6      Stream.first (dart:async/stream.dart:1188:25)
#7      Query.once (package:firebase_database/src/query.dart:90:55)
<asynchronous suspension>
#8      new RobotsScreen (package:example_flutter/robots.dart:9:42)
...
```

**Comment by stuartmorgan** [comment]
Currently no plugins support the desktop platforms, as the plugin APIs are not yet stable.

**Comment by stuartmorgan** [comment]
For context, this was closed because the Firebase plugins are implemented by wrapping the native Firebase SDKs for iOS and Android. Firebase doesn't have desktop SDKs, so there's currently nothing to implement desktop versions of the plugins on top of. If that changes in the future, this can be revisited.

**Comment by kroikie** [comment]
@bmaczak

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/367. Any further collaboration will be done there.

**Comment by bmaczak** [comment]
But it has been closed... ?

**Comment by ScottPierce** [comment]
Isn't there a c++ library that firebase provides that allows firebase to be wrapped for the desktop?

**Comment by stuartmorgan** [comment]
If you want to discuss further, the FirebaseExtended version of the bug linked above. is the right place now that the plugins have moved.

However, I would recommend reading [the highlighted section here](https://firebase.google.com/docs/cpp/setup#desktop-workflow) first.
