### ISSUE TITLE
MSSQL connector plugin

### ISSUE THREAD

**Issue by virtz** [flutter/flutter#33588]
If you have found a bug or if our documentation doesn't have an answer
     to what you're looking for, then fill our the template below. Please read
     our guide to filing a bug first: https://flutter.dev/docs/resources/bug-reports
-->

## Use case

<!--
     I  need  something similar to Java jdbc connector to connect my flutter app directly to Ms SQL server. Yes I'm aware of the dangers of connecting directly to a data source but I have seen any webservice or restful API that can handle stored procedures.

**Comment by timsneath** [comment]
Missing information.
