### ISSUE TITLE
Improve error surfacing from Windows builds

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#33583]
Non-verbose builds often don't have useful information about build failures. It would be helpful to run the build output through processing to try to extract errors.

**Comment by GroovinChip** [comment]
Per #36845 @jonahwilliams and I have been discussing how to improve build logging for Windows builds. We suspect`msbuild` is not being run with the right verbosity. I think this issue is the right place to continue the discussion and find the solution.

**Comment by stuartmorgan** [comment]
> We suspect `msbuild` is not being run with the right verbosity.

Could you elaborate on that? Do you have an example of a build failure that doesn't show the failure reason from msbuild when using `flutter run -v`?

The reason I filed this bug (and the macOS and Linux versions) is that in general we aren't extracting the error logging from the underlying build tools (msbuild in this case) and then putting that in the non-verbose output, which is what we should be doing. It wasn't about things missing even in verbose mode, although certainly if that's happening we should fix that too.

**Comment by GroovinChip** [comment]
No, I don't mean that things are missing when run in verbose mode, I mean that when there's a build error, no information about it is displayed to the user. Jonah was speculating that in regular builds the verbosity isn't quite right.

**Comment by stuartmorgan** [comment]
Ah, I see the confusion after re-reading the discussion in the PR. My understanding is that `msbuild` never logs anything to stderr, so this isn't related to `msbuild` verbosity. It's just that we aren't doing anything to get the relevant parts from the stdout output and redisplaying them, which I believe is what we need to do.

Alternately, we could potentially address it by turning *down* the verbosity of msbuild (`ErrorsOnly`) and disabling the vcvars64 banner (IIRC there's a flag to do that) and then showing all of the stdout.

> [...] prompt the user to run in verbose mode, but that's a band-aid IMO.

Yes, that's exactly why this bug was filed.

**Comment by GroovinChip** [comment]
What can I do to help? Frankly I'm not a Windows developer, I don't know
any of that stuff, I've just been researching and reading because I have
Windows computers and want to help improve Flutter development for it :)

**Comment by stuartmorgan** [comment]
Experiment with the output of some deliberately-induced build failures. Look at `msbuild` options, play with regexes on the Dart side, and find some combination of one or both that will print out the most useful parts of the build errors for your tests, without printing the entire log like verbose mode does. As long as it's a reasonable approach, even if it doesn't find everything we can start with that, and then iterate as there are examples of things that it doesn't print useful information for.

That's what I would do if I were working on this; I'm not a Windows developer either. (My comment about `msbuild` is just based on some reading about `msbuild` output when this first came up.)

**Comment by GroovinChip** [comment]
OK, thanks for the guidance. I will look into this.

**Comment by GroovinChip** [comment]
@stuartmorgan I haven't been able to find the `msbuild` options or the dart regexes for the build output in the codebase. Do you know where they are?

**Comment by stuartmorgan** [comment]
> I haven't been able to find the msbuild options

https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019

If you mean where they would be added, it would be [this script](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/bin/vs_build.bat)

> or the dart regexes for the build output

There aren't any currently. They would be post-processing steps after [running the build process](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/windows/build_windows.dart)

**Comment by GroovinChip** [comment]
Great, thank you!
