### ISSUE TITLE
Build webpage with relative path

### ISSUE THREAD

**Issue by ame-yu** [flutter/flutter#33580]
## Use case
Like configration in Vue
baseUrl(publicPath) attribute
If i set it to './'
I can get assets via relative path when i open index.html.

## Proposal
Use a  js file to manage all configration.

**Comment by yjbanov** [comment]
@ame-yu Do I understand correctly that you would like to host a Flutter web app on a path other than the root / path, such as /foo/bar/index.html and have an ability to specify where to fetch the assets from?

**Comment by ame-yu** [comment]
@yjbano Exactly.

**Comment by yjbanov** [comment]
Thanks for confirming!

**Comment by patniemeyer** [comment]
I may be missing something but it seems that if you simply remove the base tag the Flutter Web app will work relative to the index.html just fine.  Is there a problem with this?  Why isn't this the default?
