### ISSUE TITLE
Getting error in my first hello world app. Error is Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'

### ISSUE THREAD

**Issue by shaon007** [flutter/flutter#33591]
I just tried my first flutter app with android studio. When i select an emulator and press run it gives me the following error after a couple of mins.  Below is the text copied from RUN tab in andorid studio
```
> Running "flutter packages get" in flutter_app...                    3.6s
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

>FAILURE: Build failed with an exception.

>* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> org/apache/commons/codec/binary/Base64

>* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

>* Get more help at https://help.gradle.org

>BUILD FAILED in 13s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**Comment by Asaye** [comment]
Try adding 

```classpath "commons-codec:commons-codec:1.11" ```( the version may be different for your project)

inside the dependencies closure of your top level build.gradle file like so

``` 
dependencies {
      ....
      classpath "commons-codec:commons-codec:1.11"
}

**Comment by BondarenkoStas** [comment]
@shaon007 did you manage to solve it? can you paste your build.gradle?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
