### ISSUE TITLE
Investigate converting Dart isolate thread pooling to improve performance.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#33599]
Mirror bug for https://b.corp.google.com/issues/133485240 for customer dream. Discussion should occur on that issue, please.

**Comment by chinmaygarde** [comment]
All Dart VM threads are part of a pool already. The internal issue is tracking thread pooling in a native component. Either way, there is nothing else to do as the behavior is correct and WAI. Closing.
