### ISSUE TITLE
drive sample_app is now failing on bots

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3360]
https://build.chromium.org/p/client.flutter/builders/Mac/builds/722/steps/drive%20sample_app/logs/stdio

I suspect it's due to the fact that we are now running more than one `flutter drive` app on these bots and it may not know how to clean up between them correctly?

@chinmaygarde @yjbanov?

**Comment by yjbanov** [comment]
There's [this](https://github.com/flutter/flutter/blob/2a33e3f0c0ec62ab33ea8c947a284accffb8faee/packages/flutter_tools/lib/src/ios/simulators.dart#L567) but it's been able to load apps on top of already running ones pretty consistently. I wonder if we regressed somewhere.

**Comment by eseidelGoogle** [comment]
I'm going to hack around this for now with https://codereview.chromium.org/1892293002

**Comment by eseidelGoogle** [comment]
So now we're getting Error 159, Invalid Device State:
https://uberchromegw.corp.google.com/i/client.flutter/builders/Mac/builds/728/steps/drive%20stocks/logs/stdio

Previously we were getting Error 4.

**Comment by eseidelGoogle** [comment]
I fear we should remove the drive tests from the bots for now and wait to enlist the help of @chinmaygarde?

**Comment by chinmaygarde** [comment]
Hard to tell but it could be that the simulator has not finished booting maybe?

**Comment by eseidelGoogle** [comment]
We can/should just disable the drive tests on the bots for now. (I can do
it, or feel free to TBR=me changes to do so before I get to it.) Once
disabled, this doesn't have to be urgent.  We'll need to make them stable
before we can run them.

**Comment by yjbanov** [comment]
I am able to reproduce this on my macbook. What I'm seeing is that `flutter devices` continues to show the dead Simulator for up to 9 seconds after it was killed. I suspect the `xcrun simctl` itself reports the Simulator as "booted" for longer than it actually is. Yes, let's disable: https://codereview.chromium.org/1897653002/

To make things worse (I mean fun!) though, I actually broke the `sample_app` with my latest driver change. Will send a fixing PR shortly.

**Comment by yjbanov** [comment]
Here's the fix (I hope): https://github.com/flutter/flutter/pull/3373

**Comment by yjbanov** [comment]
Fixed by https://github.com/flutter/flutter/pull/3373
