### ISSUE TITLE
Setting the TextField widget's 'textAlign' property to 'TextAlign.center' creates an issue using the space button on the keyboard.

### ISSUE THREAD

**Issue by sunyatax** [flutter/flutter#33609]
Hi all,

I'm running the Flutter app I'm building on an iOS simulator and I have a build on my phone as well. When I set the TextField's textAlign property to TextAlign.center, pressing space on the keyboard does not result in a space until after I press another key. Any insight into what's going on? My code is below:
```
              TextField(
                buildCounter: (BuildContext context, 
                    {int currentLength, int maxLength, bool isFocused}) => null,
                decoration: InputDecoration(
                  border: InputBorder.none,
                ),              
                cursorColor: fontColor,
                cursorWidth: 2,
                maxLines: null,
                style: TextStyle(color: fontColor, fontSize: 24, fontWeight: FontWeight.w700),
                maxLength: 220,
                textAlign: TextAlign.center,
                textInputAction: TextInputAction.done                    
              )
```

**Comment by TahaTesser** [comment]
Hi @sunyatax 
Testing this issue doesn't seem to reproduce on `Flutter 1.12.13+hotfix.8 • channel stable` 
If you're still experiencing this issue, please create a new issue and provide the information required in the template.
Thank you
