### ISSUE TITLE
Improve hot-reload latency

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#33600]
customer: dream is reporting long latency in hot reload, likely due to rebuilding the whole dart package for file diffs. See https://b.corp.google.com/issues/133484748 for discussion and next steps; this is a mirror issue for that issue.

**Comment by pedromassangocode** [comment]
Is this still a valid issue today? I can't access the original issue to verify.

**Comment by pedromassangocode** [comment]
It has been some time without response, so I'm closing this issue for now. Please reopen if necessary.
