### ISSUE TITLE
Introduce hooks for providing context for engine crashes

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#33617]
Internal: b/133849502

Our clients are reporting that engine crashes are hard to diagnose and reproduce. One of the most common complaints is the lack of context around an engine crash (which page did the app crash on? which experiment flags were turned on? etc).

Is it possible to provide a callback to the framework when the engine is crashing? Something like Java's [UncaughtExceptionHandler](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.UncaughtExceptionHandler.html). 

The alternative is to ask apps to keep logging messages and scan the log to find the last one before crash. This is error-prone, cumbersome and not accurate.

**Comment by jonahwilliams** [comment]
We don't plan to do anything here
