### ISSUE TITLE
GPU thread exceeds frame time at seemingly random time intervals

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#33612]
Mirror issue for customer dream logged at https://b.corp.google.com/issues/115499688; discussion should occur on the linked issue. Some work has been done, but this remains open.

**Comment by kf6gpe** [comment]
Bug pending input from H/W vendor.

**Comment by chinmaygarde** [comment]
@kf6gpe: There hasn't been an update to this issue internally in months and the last update seemed to indicate that there is trouble reproducing the issue. It is also not assigned to any of the Flutter team members. Can this be closed? There is no action item for the Flutter team here.

**Comment by kf6gpe** [comment]
I've closed the upstream issue as obsolete, and I'll close this issue as well. We can reopen or file new issues if the problem occurs for the client team again. Thanks!
