### ISSUE TITLE
[web] Implement ImageShader for flutter web

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#33616]

**Comment by iamsabet** [comment]
Hi , i had this error you mentioned i think on master

<img width="1041" alt="Screen Shot 2019-09-10 at 4 52 00 PM" src="https://user-images.githubusercontent.com/20267993/64613525-99a4cb00-d3eb-11e9-8ee0-488a8bcb7393.png">

is that the one ? or something else ?
@jonahwilliams

**Comment by yjbanov** [comment]
This is done.
