### ISSUE TITLE
[web] Implement / fix animated images (GIF/WebP)

### ISSUE THREAD

**Issue by JRR-OSU** [flutter/flutter#33618]
Currently the image class, for example Image.network, only shows the first frame of an animated image and it does not play or loop. I’m not sure if this still needs to be implemeted or if this is a result of the bug — I’m guessing the former. Filing an issue to track progress.

**Comment by Gioxxy** [comment]
I tried on Safari and the gif changes frames when you scroll.

**Comment by JRR-OSU** [comment]
I think this is because the engine will only redraw the context when the context changes. I think basically what's happening is the Image widget isn't properly redrawing itself as it animates. The only way to get frames to shift is when the global state / context changes, which is obviously not the intended behavior.

**Comment by ferhatb** [comment]
Note: TODO-> Code needs to switch to DomCanvas to enable gif. Current code draws Image asset into bitmap canvas.

**Comment by edman** [comment]
I just tried this in my web app, a gif with `Image.network` did play as expected in Safari but not in Chrome.
