### ISSUE TITLE
Flicker/render issue - Text selection indicators flicker on initial selection

### ISSUE THREAD

**Issue by mtcliatt** [flutter/flutter#33623]
## Steps to Reproduce

1. Select text in a text field with a mouse (on desktop or mobile, and I'm guessing web too)

See this recording: https://drive.google.com/file/d/19C_uoS9a7akq1Lor4zfDDkB5cTgKX3pr/view?usp=sharing

`flutter doctor -v`:
Flutter (Channel unknown, v1.5.9-pre.220, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.5.9-pre.220
    • Framework revision 3d42e3fadf (3 weeks ago), 2019-05-12 11:05:39 -0400
    • Engine revision 7553de25db
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)

**Comment by justinmc** [comment]
I can't view your drive link, can you make it public?

I just merged a fix for what I believe is the same issue: https://github.com/flutter/flutter/pull/32911.  Try v1.6.4 or greater and hopefully this is already fixed. :crossed_fingers:

**Comment by mtcliatt** [comment]
Sorry about that, this link should work: https://drive.google.com/open?id=1JENpGbq95ThK8vnssXDeDNzWxjij8Xbk

Your linked issue looks identical to what I saw, and I would bet that your fix fixed both "versions".

I was able to reproduce with this setup:
Flutter 1.6.4-pre.18 • channel master • https://github.com/flutter/flutter.git
Framework • revision 323373d333 (3 days ago) • 2019-05-27 12:27:28 -0700
Engine • revision 8dc3a4cde2

I wasn't sure if that made the cutoff or not so I upgraded and was not able to reproduce with:
Flutter 1.6.7-pre.45 • channel master • https://github.com/flutter/flutter.git
Framework • revision 55d98ddd33 (5 hours ago) • 2019-05-30 20:22:55 -0400
Engine • revision 7f4f52f952
Tools • Dart 2.3.2 (build 2.3.2-dev.0.0 445a23a9bc)

But strangely, the fix wasn't that the indicators weren't flashing anymore, they're just not there at all. Was there a change after yours that removed them from Material, perhaps?

**Comment by justinmc** [comment]
Thanks for following up.  I see your gif now and I think the way Flutter behaves is closer now that the PR has landed, but it's still not perfect.  On native I see that the handles hide themselves during dragging and only show up after the gesture is over.  Is this what you're seeing?

Android             |  Flutter (master)
:-------------------------:|:-------------------------:
<img width="300" src="https://user-images.githubusercontent.com/389558/58736584-3a2e2c80-83b3-11e9-8581-fb10b1ad65aa.gif" /> |  <img width="300" src="https://user-images.githubusercontent.com/389558/58736598-3e5a4a00-83b3-11e9-9388-91f5c05363b8.gif" />

**Comment by mtcliatt** [comment]
Yes now that's exactly what I'm seeing on Flutter master - the handles hide themselves during dragging and only show up after the gesture is over. Thanks for the fix!
