### ISSUE TITLE
on copy and paste application is broken

### ISSUE THREAD

**Issue by lucasmatoscc** [flutter/flutter#33621]
on copy and paste application is broken

![image](https://user-images.githubusercontent.com/14240340/58663743-8752c580-8303-11e9-987d-c8aa40993791.png)

## Logs

```
```

comercial08:digitalConsig newuser$ flutter analyze
Analyzing digitalConsig...                                              

   info • The value of the field '_allowWriteFile' isn't used • lib/contracheques.dart:41:8 • unused_field
   info • The value of the local variable 'permissions' isn't used • lib/contracheques.dart:54:44 • unused_local_variable
   info • Don't explicitly initialize variables to null • lib/contracheques.dart:145:13 • avoid_init_to_null
   info • Don't explicitly initialize variables to null • lib/contracheques.dart:230:13 • avoid_init_to_null
   info • 'child' is deprecated and shouldn't be used • lib/contracheques.dart:273:9 • deprecated_member_use
   info • Set literals were not supported until version 2.2, but this code is required to be able to run on earlier versions • lib/contracheques.dart:420:42 •
          sdk_version_set_literal
   info • Set literals were not supported until version 2.2, but this code is required to be able to run on earlier versions • lib/contracheques.dart:456:36 •
          sdk_version_set_literal
   info • Set literals were not supported until version 2.2, but this code is required to be able to run on earlier versions • lib/contracheques.dart:480:36 •
          sdk_version_set_literal
   info • Don't explicitly initialize variables to null • lib/contracheques.dart:599:13 • avoid_init_to_null
   info • The value of the local variable 'path' isn't used • lib/contracheques.dart:649:15 • unused_local_variable
   info • Unused import: 'dart:io' • lib/data/rest_ds.dart:2:8 • unused_import
   info • Unused import: 'package:http/http.dart' • lib/data/rest_ds.dart:9:8 • unused_import
   info • Unused import: 'package:flutter/services.dart' • lib/pdfScreen.dart:11:8 • unused_import
   info • Unused import: 'package:path_provider/path_provider.dart' • lib/pdfScreen.dart:12:8 • unused_import
   info • The value of the field '_allowWriteFile' isn't used • lib/pdfScreen.dart:27:8 • unused_field
   info • The value of the local variable 'uri' isn't used • lib/pdfScreen.dart:94:25 • unused_local_variable
   info • Set literals were not supported until version 2.2, but this code is required to be able to run on earlier versions • lib/rendimentos.dart:269:42 • sdk_version_set_literal
   info • Set literals were not supported until version 2.2, but this code is required to be able to run on earlier versions • lib/rendimentos.dart:303:36 • sdk_version_set_literal
   info • Set literals were not supported until version 2.2, but this code is required to be able to run on earlier versions • lib/rendimentos.dart:326:36 • sdk_version_set_literal
   info • The value of the local variable 'width' isn't used • lib/telaAlterarSenha.dart:111:9 • unused_local_variable
   info • The value of the local variable 'media' isn't used • lib/telaInicial.dart:187:9 • unused_local_variable
   info • The value of the local variable 'padding' isn't used • lib/telaInicial.dart:190:9 • unused_local_variable
   info • The value of the local variable 'marginLogo' isn't used • lib/telaInicial.dart:195:14 • unused_local_variable
   info • The value of the local variable 'widthImg' isn't used • lib/telaInicial.dart:429:9 • unused_local_variable
   info • The value of the local variable 'media' isn't used • lib/telaLogin.dart:221:9 • unused_local_variable
   info • The value of the local variable 'marginLogo' isn't used • lib/telaLogin.dart:228:14 • unused_local_variable
   info • The value of the local variable 'width' isn't used • lib/telaPrimeiroAcesso.dart:153:9 • unused_local_variable
   info • Unused import: 'package:digitalConsig/ui/widgets/controls/design/styles.dart' • lib/ui/widgets/controls/masterPage.dart:1:8 • unused_import
   info • Name non-constant identifiers using lowerCamelCase • lib/ui/widgets/controls/masterPage.dart:21:12 • non_constant_identifier_names
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: DataTableHorizontal.camposFixos •
          lib/utils/dataTableHorizontal.dart:13:7 • must_be_immutable

30 issues found. (ran in 25.8s)

```
```

[✓] Flutter (Channel stable, v1.5.4-hotfix.3-pre.1, on Mac OS X 10.14.4 18E226, locale pt-BR)
    • Flutter version 1.5.4-hotfix.3-pre.1 at /Users/newuser/development/flutter
    • Framework revision e05a97b8a7 (6 hours ago), 2019-05-30 12:04:45 -0300
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/newuser/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • iPhone 5s • 71148BDB-6785-4D2D-A18C-665089E8D770 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 2 categories.

```
```

**Comment by HansMuller** [comment]
It's hard to tell exactly what's going wrong without a test case. On the face of it, the app appears to be failing to find a localization for "pasteButtonLabel"; maybe the app's supported locales aren't set up properly  https://flutter.dev/docs/development/accessibility-and-localization/internationalization

If you can provide a small complete app that demonstrates the problem, we'll look into it.

**Comment by lucasmatoscc** [comment]
the location is for Locale ('pt', 'BR')

![image](https://user-images.githubusercontent.com/14240340/58705854-cbd37500-8386-11e9-8c2f-30bb40d9ea5d.png)


![May-31-2019 09-27-38](https://user-images.githubusercontent.com/14240340/58705740-79925400-8386-11e9-8b3c-aad8a584faf4.gif)

**Comment by jans-y** [comment]
This solution worked for me:

https://stackoverflow.com/questions/53662917/how-to-change-cupertinodatepicker-display-language/53752290

**Comment by lucasmatoscc** [comment]
The problem happens specifically in the ios project

**Comment by TahaTesser** [comment]
Hi @lucasmatoscc 
Are you still experiencing this issue with latest stable? 
If yes, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
