### ISSUE TITLE
Flutter 1.5.4 Bug ???: scrambled global vars

### ISSUE THREAD

**Issue by jerryhamby** [flutter/flutter#33631]
I found a problem in my larger app I think is a bug in Flutter. Th problem didn't exist for me in Flutter 1.2. Data I store in (what I call global vars) is getting scramble and all my data is completely out of order.

Example of "scrambled":
print(MyVars.currentObject['teamname']);  this should be "atlanta braves" instead it coming back as "189" which is data I put into the "weight" field.
MyVars.currentObject is printing perfectly for part of the initState but later in the function Dart scrambles my data (as shown). This is serious.

============= good ================
MyVars.currentObject = {lastname: marris, bought: $5.00, position: outfield, publisher: anyone, firstname: roger, teamname: atlanta braves, title: , type2: , autographed: , accountid: WMY7GQWygejUZEDvLomn, sold: , weight: 189}

============= bad scrambled ================
MyVars.currentObject = {lastname: roger, bought: roger, position: 5' 11", publisher: 189, firstname: 1950, teamname: 189, title: Bought, type2: , autographed: Title, accountid: temp desc, sold: , weight: 189}

I'm rebuilding a paired down version of the app, but I still can't find the problem. Been working days on this issue and determined it wasn't my doing, that means it has to be a bug.

**Comment by mraleph** [comment]
Unfortunately it is impossible to help you with this without reproduction.

**Comment by jerryhamby** [comment]
I do have some sample code but it's rather large uncompressed. What is the best way to get this to you? I prefer to not post the code to a public forum, it's still in development.

**Comment by marcelgarus** [comment]
Typically, you don't want to store state globally, especially when developing with Flutter.

One reason is that Flutter's "hot reload" functionality doesn't work anymore because it just rebuilds the widget tree, not anything stored outside of it. Global state and "hot reload" just don't work together.

Also (on a more generally applicable note), it's much harder to reason about your state when it's globally accessible to everyone. You may consider using the `provider` package to restrict access to widget subtrees of your app.

**Comment by mraleph** [comment]
@jerryhamby usually for us to be able to look at the code it needs to be licensed under an open-source license. We would not be able to look at privately shared code that has no license attached to it. Another way is to work with lawyers to have some paperwork to be put in place between us and you - but simplest would be if you could just put the code publically with a proper open-source license attached.

**Comment by jerryhamby** [comment]
@ marcelgarus FYI, I'm a noob to Flutter. Although the provider maybe better for Flutter, I'm coming from Swift and Javascript environments, and the bottom line is my code was working in Flutter 1.2, now it's not in 1.5. I just trying to get my code back to working again and help, if I can, the Flutter team make their product better (not broken). I will start to review the provider method, but I do have a big goal of accessing FireStore as little as possible to keep my costs down. This cost issue is a big deal if my product is successful. Again, FYI "hot reload" is not important to me, maybe it will be in the future??? Thanks for taking the time to respond.

**Comment by jerryhamby** [comment]
@mraleph  I'm confused abut the requirements. I really believe you have a bug in Flutter 1.5 but if I read this correctly you will not consider the bug (look at my code) unless I make my code publicly available? Don't you care about making 1.5 stable? Code that was working in 1.2 now is broken in 1.5. If I make my code available publicly then my FireStore account id is exposed. There must be a way to get this fixed without going through a lawyer, I'm just a single developer that may have found a bug that Flutter created.

**Comment by mraleph** [comment]
> if I read this correctly you will not consider the bug (look at my code) unless I make my code publicly available? 

No, this is not what I said. What I said is that we _can not_ (actually _not allowed_) to look at third party code that does not have clear licensing attached to it. 

> If I make my code available publicly then my FireStore account id is exposed

You can publish your code - but exclude your credentials if credentials are the only thing you are concerned about.

**Comment by jerryhamby** [comment]
I have finally removed my extraneous code and account ids and I'm ready to submit the code for review. I was hoping that the new version (1.7.8) would magically fix the issue, but no luck. What is my next step?

**Comment by jerryhamby** [comment]
Hi,

Could you please review my latest post in the forum and tell me where I can post my code.
https://github.com/flutter/flutter/issues/33631 <https://github.com/flutter/flutter/issues/33631>
Jerry

**Comment by mraleph** [comment]
@eseidel can somebody from the Flutter team take over this? I am on vacation right now - but we would really like to able to diagnose the issue, if it is indeed a bug in Dart compiler.

**Comment by eseidelGoogle** [comment]
@a-siva do you have someone on your team who can take a look?

FYI @tvolkert @Hixie

**Comment by mraleph** [comment]
@jerryhamby There are two ways to proceed:

- You can choose to license your code under an OSI-approved open-source license, that is any license [listed here](https://opensource.org/licenses/alphabetical).
- You can choose to sign [Google CLA](https://cla.developers.google.com/clas)

After that you can send us your code, e.g. by creating a GitHub repository and sharing it with us or packaging your code and mailing to us. 

Note: if you choose to go for CLA + mail the code route you will need to mail it from the same email address that you signed the CLA with.

**Comment by a-siva** [comment]
Please see https://github.com/flutter/flutter/wiki/Issue-hygiene#provide-reduced-test-cases for our general guidelines on providing source code that reproduces the problem.

**Comment by jerryhamby** [comment]
I have created a private GitHub account with a URL. I have also signed a Google CLA (but haven't received any confirmation, if that matters). So, how to I get you the URL? My GitHub account only has the lib folder, it was too small to post the Android, IOS and build folders.

**Comment by mraleph** [comment]
@jerryhamby You can add me as a collaborator to your private repo - then I will get notification with its location.

**Comment by mraleph** [comment]
I got the source - but it does not have any instructions on how to reproduce the issue you are seeing. We would need to be able to reproduce it to be able to debug it.

**Comment by jerryhamby** [comment]
I think all the info you need in under the "more info" button (step-by-step). I made 2 comments there. If you have any problems let me know.
Jerry

**Comment by mraleph** [comment]
Okay, I looked at your code - and its a bug in your code: you have several `TextControllers` responsible for text fields. They have listeners attached to them which do something like this inside `map[map.keys.elementAt(0)] = controller.text`. You seem to have an expectation that `map.keys` are always in the same order as your controllers (e.g. if `firstname` is the first input field then `map.keys.elementAt(0)` is also `firstname`). However this does not hold - you maps have keys in the different order. So you end up scrambling your own object when you do `controller.text = map['somefield']` - because index used in the controller does not match index of the key `'somefield'` in the map.

I guess at some point order matched - and your code worked, but then something permuted the keys and it stopped working. 

You can fix your code by moving away from `map[map.keys.elementAt(0)]` expression in the controllers to directly using the key names `map['firstname']`.
