### ISSUE TITLE
Image widget should not flash when changing image

### ISSUE THREAD

**Issue by fralways** [flutter/flutter#33641]
I have seen that there are many issues regarding slow image loading and processing in Dart. I know there are some workarounds like precacheImage, but this is not something that works in every case. So, to put aside loading performance, my issue is that Image flashes when image provider is changed. This is a terrible experience and it's very hard to prevent especially in image heavy app (a lot of full screen images changing at fast phase). I would expect that Image renders when image is loaded rather than showing white background and then loading an image. This means that if Image is showing image1 and then I change it to display image2, Image will not try to show image2 until it's loaded. What I'm doing now is to precacheImage first and then rebuild Image with new provider.

## Steps to Reproduce

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _currentImageIndex = 0;
  List<MemoryImage> images = [];
  int numOfImages = 50;
  bool loaded = false;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();

    initImages();
  }

  void initImages() async {
    ByteData image0 = await rootBundle.load('lib/image0.png');
    ByteData image1 = await rootBundle.load('lib/image1.png');
    ByteData image2 = await rootBundle.load('lib/image2.png');
    ByteData image3 = await rootBundle.load('lib/image3.png');

    for (int i = 0; i < numOfImages; i++) {
      int index = i % 4;
      switch (index) {
        case 0:
          images.add(MemoryImage(image0.buffer.asUint8List()));
          break;
        case 1:
          images.add(MemoryImage(image1.buffer.asUint8List()));
          break;
        case 2:
          images.add(MemoryImage(image2.buffer.asUint8List()));
          break;
        case 3:
          images.add(MemoryImage(image3.buffer.asUint8List()));
          break;
      }
    }
    setState(() {
      loaded = true;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: loaded
          ? SizedBox.expand(
              child: Image(
                image: images[_currentImageIndex],
                fit: BoxFit.cover,
              ),
            )
          : Container(),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            _currentImageIndex = _currentImageIndex + 1 == numOfImages ? 0 : _currentImageIndex + 1;
          });
        },
        child: Icon(Icons.add),
      ),
    );
  }
}
```

pubspec:

```
name: flutter_test_proj
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/image0.png
    - lib/image1.png
    - lib/image2.png
    - lib/image3.png

```

images used:
![image0](https://user-images.githubusercontent.com/6430214/58688747-9ed29280-8385-11e9-9e0a-ab14be09ed97.png)
![image1](https://user-images.githubusercontent.com/6430214/58688749-9f6b2900-8385-11e9-995f-9372c4143e9e.png)
![image2](https://user-images.githubusercontent.com/6430214/58688750-9f6b2900-8385-11e9-886b-7fb662132811.png)
![image3](https://user-images.githubusercontent.com/6430214/58688751-9f6b2900-8385-11e9-9ce8-a3ec31819e40.png)

## Logs

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

```

**Comment by Nico04** [comment]
I resolve this using the parameter "gaplessPlayback: true" on the Image Widget

**Comment by fralways** [comment]
@Nico04 tnx! This solves this issue.

**Comment by daniel-meow** [comment]
Thank you so much, had the same problem!

**Comment by YehudaKremer** [comment]
> I resolved this using the parameter "gaplessPlayback: true" on the Image Widget

After 4 hours.. this fix my problem, thank you so much @Nico04 .
WHY "gaplessPlayback: **true**" is not the default ?!

**Comment by student020341** [comment]
Wow, that just saved me as well. I have an interactive viewer that contains a large image and has a transformationcontroller. I have a listener on the controller that swaps the images at different scales to give better resolutions of different levels. It was unclear to me why that while the image was being swapped, continuing to scroll yielded a massive scroll delta that jumped straight to the maximum value. By setting gapless to true, scrolling behaved as expected. Also setting the controller to Matrix4.diagonal3Values(1, 1, 1) when switching up images to reset the scale at the next image. I thought doing this from the listener was having some buggy interaction... thank goodness!

**Comment by kyczawon** [comment]
> > I resolved this using the parameter "gaplessPlayback: true" on the Image Widget
> 
> After 4 hours.. this fix my problem, thank you so much @Nico04 .
> WHY "gaplessPlayback: **true**" is not the default ?!

The reason for this is shown in the image.dart file:

### Why is the default value of [gaplessPlayback] false?

Having the default value of [gaplessPlayback] be false helps prevent
situations where stale or misleading information might be presented.
Consider the following case:

We have constructed a 'Person' widget that displays an avatar [Image] of
the currently loaded person along with their name. We could request for a
new person to be loaded into the widget at any time. Suppose we have a
person currently loaded and the widget loads a new person. What happens
if the [Image] fails to load?

* Option A ([gaplessPlayback] = false): The new person's name is coupled
with a blank image.

* Option B ([gaplessPlayback] = true): The widget displays the avatar of
the previous person and the name of the newly loaded person.

This is why the default value is false. Most of the time, when you change
the image provider you're not just changing the image, you're removing the
old widget and adding a new one and not expecting them to have any
relationship. With [gaplessPlayback] on you might accidentally break this
expectation and re-use the old widget.

**Comment by harshchau** [comment]
+1 for Nico and why is gaplessPlayback: true not the default? I understand the explanation by @kyczawon but if the miage fails to load, wouldn't the expectation be to catch the exception and deal with it?

**Comment by ahaneef29** [comment]
Thank you..!

**Comment by amundbuer** [comment]
Sallan så sprutnais!
