### ISSUE TITLE
App crashes when using a Native View and clicking android "home" button 

### ISSUE THREAD

**Issue by Vanethos** [flutter/flutter#33643]
Currently I'm using a modified version of the Android View seen in https://pub.dev/packages/fast_qr_reader_view 

The app is in production and we have seen no problems with the native view code.

However, this past week, in the `beta` channel (which is the channel we currently use) the following occurs:

When the Native View widget is shown, if I click "home" on Android, the app crashes with the following stack trace:

```
E/AndroidRuntime(22149): FATAL EXCEPTION: main
E/AndroidRuntime(22149): Process: com.ianum.app, PID: 22149
E/AndroidRuntime(22149): java.lang.NullPointerException: Attempt to invoke virtual method 'long android.view.accessibility.AccessibilityNodeInfo.getSourceNodeId()' on a null object reference
E/AndroidRuntime(22149):        at android.view.View.populateVirtualStructure(View.java:8580)
E/AndroidRuntime(22149):        at android.view.View.populateVirtualStructure(View.java:8661)
E/AndroidRuntime(22149):        at android.view.View.populateVirtualStructure(View.java:8661)
E/AndroidRuntime(22149):        at android.view.View.populateVirtualStructure(View.java:8661)
E/AndroidRuntime(22149):        at android.view.View.populateVirtualStructure(View.java:8661)
E/AndroidRuntime(22149):        at android.view.View.onProvideVirtualStructureCompat(View.java:8079)
E/AndroidRuntime(22149):        at android.view.View.onProvideVirtualStructure(View.java:8060)
E/AndroidRuntime(22149):        at android.view.View.dispatchProvideStructureForAssistOrAutofill(View.java:8726)
E/AndroidRuntime(22149):        at android.view.View.dispatchProvideStructure(View.java:8673)
E/AndroidRuntime(22149):        at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3562)
E/AndroidRuntime(22149):        at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3562)
E/AndroidRuntime(22149):        at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3562)
E/AndroidRuntime(22149):        at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:519)
E/AndroidRuntime(22149):        at android.app.assist.AssistStructure.<init>(AssistStructure.java:2047)
E/AndroidRuntime(22149):        at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3343)
E/AndroidRuntime(22149):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1890)
E/AndroidRuntime(22149):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(22149):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(22149):        at android.app.ActivityThread.main(ActivityThread.java:6940)
E/AndroidRuntime(22149):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22149):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime(22149):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W/OPDiagnose(22149): getService:OPDiagnoseService NULL
D/OSTracker(22149): OS Event: crash
```

No code was modified, and I even reverted to an old commit that worked and the same error occurs.

Possibly related to #32984

**Comment by Robbiemans** [comment]
You should create an issue in the correct repo; https://github.com/facundomedica/fast_qr_reader_view/issues

**Comment by Vanethos** [comment]
But, if the library was not updated, and the code was not changed, the only thing that changed was the fact that the Flutter tools and version were updated, is this really an issue from the library?

**Comment by BondarenkoStas** [comment]
@Vanethos is it the same while using current flutter stable v1.9.1+hotfix.4?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by Vanethos** [comment]
Hello there!

I'm terribly sorry but I dind't really have the time to check on this until now and I should have commented on it right away! My bad!

The issue is now solved! It was not due to the library but it was solved when I then again upgraded Flutter.

Thank you for your time!

**Comment by iapicca** [comment]
Hi @Vanethos 
I'm glad to hear that you solved the issue
thank you for letting me know

**Comment by PingShen** [comment]
@Vanethos which flutter version can fix this issue?
