### ISSUE TITLE
URL without video file extension can't play in video player

### ISSUE THREAD

**Issue by kalkotekedar** [flutter/flutter#33644]
I just want to use the url like ex. https://vimeo.com/6383273 These kinds of url are not working in the video player right now.

It gives an error as follows

`com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.`

**Comment by BondarenkoStas** [comment]
@kalkotekedar did you find a solution? do you mean to play url video without video_player plugin? can you provide a code example to reproduce the issue?

**Comment by kalkotekedar** [comment]
Not yet. For now, I am using custom video storage and while getting the URL it gives me with appropriate extension in the URL. If I found any solution I will put here.

**Comment by iapicca** [comment]
Hi @kalkotekedar 
can you please provide your `flutter doctor -v`?
Also, to better address the issue, it would be useful
if you could post a self contained app on github
or describe the steps to reproduce it.
Thank you

**Comment by kalkotekedar** [comment]
You can try with this video URL https://vimeo.com/6383273. It won't work on the player.

Here is the result of flutter doctor -v?
![Capture](https://user-images.githubusercontent.com/6457446/66489449-434fa880-eacd-11e9-8e1c-97e524bc4759.PNG)

**Comment by iapicca** [comment]
Thank you @kalkotekedar ,
to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Please do not post screen-shoot of the code 
but copy-past it instead.

**Comment by iapicca** [comment]
Hi @kalkotekedar
the one you linked isn't a video url 
(I'm not an expert but I believe that vimeo offers the url with some premium subscription)
I believe the problem isn't the lack of a "video extension",
but a the url doesn't target a video at all.
Are you experiencing this issue onlywith vimeo?
thank you

**Comment by zeeshan-mehdi** [comment]
experiencing this issue with vimeo and youtube
