### ISSUE TITLE
[Google Map] Unable to touch google map under the Scaffold widget

### ISSUE THREAD

**Issue by SaeedMasoumi** [flutter/flutter#33656]
I have multiple screens that need to interact with Map view. To avoid multiple rebuilding of Map widget, I put it under the scaffold widget:

 ```
return Stack(
    children: <Widget>[
      MapWidget(), //; wraps GoogleMap
      Scaffold(
       body: ...,
       bottomNavigationBar: ..., 
      )
    ],
  )
```
It looks fine but it doesn't accept any touch events.

Note: Same behavior with `Navigator`, It doesn't allow to pass any touch events to the map widget.

**Comment by BondarenkoStas** [comment]
@SaeedMasoumi did you find a solution? can you try https://stackoverflow.com/a/57088480 or other solutions from SO?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
