### ISSUE TITLE
Flutter [web] image assets do not work.

### ISSUE THREAD

**Issue by kenthinson** [flutter/flutter#33659]
When I load a image asset the result is nothing displays. If I load from network it works fine. Flutter for mobile works fine with the same code.

**Comment by YourksChan** [comment]
The way to invoke a resource?

**Comment by phelipepalte** [comment]
You already declare this image in pubspec.yaml? If yes, please copy your pubspec.yaml content here.

**Comment by kenthinson** [comment]
`name: kenthinson
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

  # exampleicon:
  fonts:
    - family: Monoton
      fonts:
        - asset: fonts/Monoton-Regular.ttf`

**Comment by kenthinson** [comment]
Gthub seems to be messing with the formatting even though i used code tags

**Comment by phelipepalte** [comment]
Try clone some project from web and run in your pc. If have problem, I say to you reintall the flutter and plugins. If don't, maybe is any mistake in your project. Print your folders, where your image is.

**Comment by glancer000** [comment]
Did you make the assets folder in the web folder? That was my mistake.

Have all your fonts and images in an asset folder under the web folder

**Comment by glancer000** [comment]
Oh, and Image.network seems to work for local images when the asset folder is under the web folder

**Comment by kenthinson** [comment]
Got it working with Image.network. Thanks :)

**Comment by sysebert** [comment]
Just wanted to chime in to say that you can keep your assets as a sibling to `ios` and `android`, but in order for it to work for web, you have to rebuild the web project. This step also needs to happen when you rename assets.

If you're using VS Code, stop your debug session and start it again, or in your terminal type `flutter run -d chrome`. This will force the web project to be rebuilt, copy the assets to the web/assets directory, and you should be good to go!

**Comment by onatcipli** [comment]
In my case `Image.network` works in debug mode but in release build it isn't working

**Comment by diego-lipinski-de-castro** [comment]
why is it so hard to display one image in flutter web? im half a fucking hour trying and I literally cant find any working example

**Comment by robinbakkerus** [comment]
You should use the Chrome debugger (F12) then you can where to put the asset, and how to access it.
Most likely you should store all images under **web/assets**
and access these without the prefix for example:
Image(
            image: AssetImage('imagename.jpg')),

**Comment by xpat** [comment]
flutter run -d chrome

**Comment by Coltae** [comment]
I am attempting to put my site build up via FileZilla and I am having this issue. I do flutter biuld web and take the contents from the web folder that appears in the build folder after using the command. My images do not show up however when I place those contents into my public_html folder. Everything works but the one singular image I am trying to use.


I do not understand some of the answers above. Are you all saying I should create an 'assets' in the root directory and then also make one under the web directory?
It appears that when I do that it builds and puts assets into a subdirectory of assets so it's assets -> assets -> images and in my pubspec.yaml I have included assets/images and I am calling the image that way.

What am I missing here? I 'd really appreciate some help on this as I have not found a good example of this.

-Colt

**Comment by xpat** [comment]
@Coltae I am having a lot of success using flutter web.  Here's a link to one web app of mine in which I was easily able to display a background image that I was also able to easily change:  https://watashiwa.soy.  In the pubspec.yaml

Flutter:
  uses-material-design: true
  assets:
    - images/

and in my main.dart

class _StoryPageState extends State<StoryPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: BoxDecoration(
          image: DecorationImage(
            image: AssetImage('images/Jupiter.jpg'),
            fit: BoxFit.cover,
          ),


p.s. I'm half-way through the LondonAppBrewery "Complete Flutter Development Bootcamp Using Dart" as referenced at https://flutter.dev/docs/codelabs.  It's $10 US.  Check it out.

**Comment by Coltae** [comment]
@xpat  Did you have to at any point create your own assets folder in the explorer? I think that's what's messing me up. I will try what you did above and check out the course.

I liked your site by the way! I'll bookmark it and check in on it :)

**Comment by Coltae** [comment]
@xpat did you have to put an assets or image folder in your main root location or just in the web?

**Comment by Coltae** [comment]
@xpat when I build web it makes an asset folder inside an asset folder :/ I cannot figure this out sadly. My pubspec is the same as yours and this is my Main.dart

`import 'package:flutter/material.dart';

void main() => runApp(OWIApp());

class OWIApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: "Getting started",
      theme: ThemeData(
        primarySwatch: Colors.green,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Center(child: Text("My Site")),
        ),
        body: HomeWidget(),
      ),
    );
  }
}

class HomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      child: Column(
        children: <Widget>[
          Center(
            child: Center(
              child: Text(
                "GIF",
                style: TextStyle(backgroundColor: Colors.green, fontSize: 55.00),
              ),
            ),
          ),
          Center(
            child: Image.asset('images/hello.gif'),
          ),
        ],
      ),
    );
  }
}`

**Comment by Coltae** [comment]
@xpat  Also, sadly it appears I missed the sale and the course is now $190 .

**Comment by jonahwilliams** [comment]
FWIW: https://flutter.dev/docs/development/ui/assets-and-images

The way that assets are declared and used on the web is exactly the same as on mobile or desktop

**Comment by Coltae** [comment]
@jonahwilliams Thank you for the link. I can get the include all assets to work locally but when I deploy my site via FileZilla (by dragging the contents of the build/web folder after performing a web build- the image does not load. I imagine it's due to the pathing of the image. But I did follow the instructions. I did 

flutter:
    assets:
        -assets/

it, however, isn't working for me.

Also, the documentation doesn't mention me having to make my own assets folder? Do I need to do this in the root? or in the web portion on the explorer window?

I appreciate you all's help and feedback on this.

**Comment by jonahwilliams** [comment]
Yes, you need to make it in the root. you can put whatever in web but it won't end up as part of the asset manifest.

If you run a local web server in `build/web` do the assets work locally? Like

```
cd build/web
python -m SimpleHTTPServer
```

**Comment by Coltae** [comment]
Okay so @xpat and @jonahwilliams I have been testing on this issue all day and I finally have my site running with the GIF I have been trying to show up. That being said; I cannot figure out why it's working now. I have narrowed it down to maybe being that fact that I changed my image logic to `child: Image(image: AssetImage('assets/myGif.GIF'))` instead of what I posted above as `child: Image.asset('images/hello.gif'),`

I was following another tutorial online and they used the latter and it worked locally but not when deployed via dropping the contents of build/web onto my public_html folder via FileZilla.

Any reason why this is? The documentation via hovering over the widgets are confusing to me so I cannot figure out how those to expressions differ or why it even accepted the second way (the original way I posted above) when it didn't seem to work?

Obviously I used it incorrectly. It'd be great to learn why/how.

**Comment by xpat** [comment]
>  did you have to put an assets or image folder in your main root location or just in the web?

@Coltae , Yes, I add an image/ directory in the main level, the same level as the pubspec.yaml and the lib/ folder. 

> flutter:
assets:
-assets/

I used -images/ and not -assets/.  (Also, the indentation is import; I trust you figured that out).  

My watashiwa.soy web app is just a modification of the "Boss Level Challenge 2 - Destini" app from here:
https://github.com/londonappbrewery/destini-challenge-starting

Are you sure they're not offering the discount anymore?  It still says $10 when I follow the link from the the Flutter Codelab page (it's a link at the very bottom of that page).  Maybe you have to follow that link to get the discount.  For $10 it's a steal.  For $199 it would still be worth it but that's a good chunk of change.  


In the meantime, here's a link to the course resources: https://github.com/londonappbrewery/Flutter-Course-Resources.  Angela Yu, who gives the class has some videos on Youtube.  https://www.youtube.com/playlist?list=PLSzsOkUDsvdtl3Pw48-R8lcK2oYkk40cm

**Comment by Coltae** [comment]
@xpat  I found a coupon and just picked up the course for $18 :).

To clarify what worked for me was: **`child: Image(image: AssetImage('assets/myGif.GIF'))`**
what did not work was: **`child: Image.asset('images/hello.gif')`**.

I am excited now to start the course and keep learning this super intriguing framework and language. I think about it all of the time. This is the first language in my career that I really want to dive right in and build stuff. I have been a dotNet engineer for years now- so this is refreshing.

Thank you all again!

**Comment by xpat** [comment]
@Coltae 

> I am excited now to start the course and keep learning this super intriguing framework and language. I think about it all of the time. This is the first language in my career that I really want to dive right in and build stuff. 

I share your enthusiasm completely.  The course is amazing!  Take notes.  I wish I had!  
I use an Asus Chromebook Flip C302, in developer mode with Daniel Schneider's Crouton Linux installed.  I installed Android Studio and in that I'm using IdeaVim and in the terminal, bash. You can serve your web app from Gihub pages.  Let me know if you need some help.

Here are a few of the apps I've published, based on the LondonAppBrewery course:

https://ambientx.dev
https://watashiwa.dev
https://pinche.website
https://poutine.app

**Comment by YggrYergen** [comment]
> Did you make the assets folder in the web folder? That was my mistake.
> 
> Have all your fonts and images in an asset folder under the web folder

Any docs address this? Running the same issue.

**Comment by xpat** [comment]
@YggrYergen  For fonts, I've been using Google Fonts package https://pub.dev/packages/google_fonts.  I use that instead of downloading the fonts. 

> FWIW: https://flutter.dev/docs/development/ui/assets-and-images

The way that assets are declared and used on the web is exactly the same as on mobile or desktop

**Comment by Staccatointeractive** [comment]
> Did you make the assets folder in the web folder? That was my mistake.
> 
> Have all your fonts and images in an asset folder under the web folder

That was the solution for me.  Thank you!
