### ISSUE TITLE
  If I  set io.flutter.embedded_views_preview in info.plist , it's become very slow when I was input with keyboard,  

### ISSUE THREAD

**Issue by GpyProject** [flutter/flutter#33652]
If I  set io.flutter.embedded_views_preview in info.plist , it's become very slow when I was input with keyboard on ios ,  my flutter version is 1.5.4,  wish reply。

**Comment by iapicca** [comment]
Hi @GpyProject 
are you still experiencing the issue with the latest master?
[sample](https://github.com/flutter/flutter/issues/56426#issuecomment-624514639)
thank you

**Comment by markusaksli-nc** [comment]
Hi @GpyProject 
Is this issue still relevant on the latest version of flutter (eg. dev or master)? Can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with the exact change you made to info.plist if this is the case?
Thank you

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
