### ISSUE TITLE
Tooltip text color is incorrect when the primarySwatch color is a light color

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#33654]
## Flutter version

```
[✓] Flutter (Channel master, v1.6.1-pre.47, on Mac OS X 10.13.6 17G4015, locale en-CN)
```

## Code

```dart
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "test",
      theme: ThemeData(
        primarySwatch: Colors.yellow
      ),
      home: MyWidget()
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.add),
            onPressed: () {},
            tooltip: 'test',
          )
        ],
      ),
    );
  }
}
```

## Screenshot

![tooltip](https://user-images.githubusercontent.com/1555508/58704914-28af4980-83e0-11e9-8308-2a6d1dc8ab36.png)

## Issue Description

Regardless what the primarySwatch color is, the tooltip background is always black. This is fine to me. But when primarySwatch is a light color, the tooltip text color changed from white to black. This really doesn't make sense. primarySwatch color has nothing to do with tooltip text color because the tooltip background color is never changed. Tooltip with black background and black text color is hard to read. 

Expected: the tooltip text color should never be changed and should remain white. (the same color when primarySwatch color is a dark color).

**Comment by justinmc** [comment]
Indeed if I try your code and change the primarySwatch color to purple, then the tooltip text background remains dark, but its text becomes white (along with all primary text).

It seems reasonable to me to keep it white, as long as we don't break anything else like optional customization of the color.  I should look into the material spec and see if it says anything about tooltip font color in cases like this.

**Comment by sgon00** [comment]
@justinmc Thank you very much for taking care of this issue. 👍

**Comment by justinmc** [comment]
Here's what it looks like with a dark primarySwatch for reference:

![Screenshot_20190603-093742](https://user-images.githubusercontent.com/389558/58818780-88c20d80-85e3-11e9-93f6-8d6b2cd4329a.png)

**Comment by shihaohong** [comment]
After https://github.com/flutter/flutter/pull/36856, the tooltip text color's defaults should be updated. Also, with the changes, the tooltip's text style can now be augmented with `Tooltip.textStyle`, as well as through the `TooltipTheme` and `ThemeData.tooltipTheme`. I'm going to close this issue since these tools should help resolve the problem!

**Comment by tapizquent** [comment]
Is tooltip.textStyle available in v1.7.8? I don't seem to find that property

**Comment by shihaohong** [comment]
It's currently available in the `master` branch and will be available when the next `stable` is released

**Comment by tapizquent** [comment]
Disregard my previous comment, just realized 1.7.8 was not the last version. Updated to 1.9.2 and it works fine now. Thanks!
