### ISSUE TITLE
localeResolutionCallback returns twice, first null

### ISSUE THREAD

**Issue by cosinus84** [flutter/flutter#33668]
localeResolutionCallback returns twice, once null and after the corect locale
```
2019-05-31 21:35:15.926735+0300 Runner[83951:12397738] flutter: null
2019-05-31 21:35:16.020703+0300 Runner[83951:12397738] flutter: en_US
```
[✓] Flutter (Channel dev, v1.6.6, on Mac OS X 10.14.4 18E226, locale en-RO)
    • Flutter version 1.6.6 at /Users/cosinus/flutter
    • Framework revision e1a784ae3f (3 days ago), 2019-05-28 21:53:03 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)
When using debug from visual code all works fine. Even from device(stopped debugging) I get this strange behaviour. 
Also when running from XCode on device.

![IMG_0EFA54FB5084-1](https://user-images.githubusercontent.com/1459132/58728103-d9244a00-83ee-11e9-91d3-0aa4b8e93628.jpeg)

https://github.com/flutter/flutter/issues/24747

If this is the desired behaviour then I think the documentation should say something about this
https://flutter.dev/docs/development/accessibility-and-localization/internationalization#specifying-the-apps-supportedlocales-parameter

**Comment by Ahmadre** [comment]
catch that with an if-clause if locale is null or not. Just a workaround

**Comment by HilalHakla** [comment]
I think you need to use Builder class in order to preserver the context

**Comment by BondarenkoStas** [comment]
@cosinus84 is it the same while using current flutter stable v1.9.1+hotfix.4?

**Comment by TahaTesser** [comment]
Hi @cosinus84 
This seems like it's fixed

![Annotation 2020-02-17 171156](https://user-images.githubusercontent.com/48603081/74650872-a272a780-51a8-11ea-8a11-258d9daf3c57.png)

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
Thank you

**Comment by cosinus84** [comment]
Thank you @TahaTesser, the project I was working is "live" no need for features so far. I am afraid to open and update things over there as the project will be full of blood as soon as I open it. :)
