### ISSUE TITLE
Route should be opaque to MouseEnter/Exit events

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#33679]
## Description

As shown in the GIF below, when a pop up menu is shown, widgets on the lower route still reacts to MouseEnter/Exit events and shows hover effect, despite ignoring mouse click events.

![1](https://user-images.githubusercontent.com/1596656/58736628-647fea00-83b3-11e9-82b8-645d7162e988.gif)

## Expected
Maybe MouseEnter/Exit events should also obey the "opaque" flag?

## Environment
Framework: 56940b544

**Comment by dkwingsmt** [comment]
@gspencergoog Are you interested in it?

**Comment by gspencergoog** [comment]
Is it a modal route?  If not, I'd say it's doing what it's supposed to.

**Comment by dkwingsmt** [comment]
@gspencergoog According to Android native app, widget should not show hover effect when under a popup menu, see the GIF below (the hover shade is barely visible)
![1](https://user-images.githubusercontent.com/1596656/58841268-ee32f000-861d-11e9-9a71-8910f600aeab.gif)

**Comment by dkwingsmt** [comment]
Update: I found out that `MouseAnnotation` was actually not respecting `behavior: HitTestBehavior.opaque`. The photo below shows two overlapping `FlatButton`, and both of them display hover effect despite that `InkWell` has set `behavior: HitTestBehavior.opaque`.

![image](https://user-images.githubusercontent.com/1596656/60376092-61cbe100-99c1-11e9-8633-13ff2ce6625b.png)

Repro:
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Stack(
            children: [
              Positioned(
                top: 20,
                left: 20,
                child: FlatButton(
                  child: Text('mmmmmmmmmmmmmmmmmmmmmm'),
                  onPressed: () {},
                ),
              ),
              Positioned(
                top: 30,
                left: 80,
                child: FlatButton(
                  child: Text('nnn'),
                  onPressed: () {},
                ),
              ),
            ]
        ),
        ),
      ),
    );
  }
}
```
