### ISSUE TITLE
PUB_CACHE Environment variable behavior on Windows

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#33672]
The logic between `flutter` and `flutter.bat` as it related to the `PUB_CACHE` environment variable are different, causing issues with installing on Windows where the `PUB_CACHE` variable is already set.
 
In flutter/bin/flutter.bat ([here](https://github.com/flutter/flutter/blob/f36a35d20ac5dc2936cab6ccc60f5d9afa34466e/bin/flutter.bat#L131)):
```bat
IF "%PUB_CACHE%" == "" (
    IF EXIST "%pub_cache_path%" SET PUB_CACHE=%pub_cache_path%
)
```

In flutter/bin/flutter ([here](https://github.com/flutter/flutter/blob/f36a35d20ac5dc2936cab6ccc60f5d9afa34466e/bin/flutter#L125)):
```bash
if [[ -d "$FLUTTER_ROOT/.pub-cache" ]]; then
    export PUB_CACHE="${PUB_CACHE:-"$FLUTTER_ROOT/.pub-cache"}"
fi
```

## Steps to Reproduce

1. Select and download a release from [SDK Releases](https://flutter.dev/docs/development/tools/sdk/releases?tab=windows).
2. Set the environment variable `PUB_CACHE`
3. Unpack and run `flutter create --offline foo`

**Comment by MrBirb** [comment]
@Piinks Do you think this issue is still relevant? Both of these snippets no longer exist

**Comment by Piinks** [comment]
Thanks @MrBirb, it looks like we can close this!
