### ISSUE TITLE
Close streams on hot restart

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#33678]
## Use case
When subscribed to streams, specifically from cloud firestore in my case, and using hot restart, these subscriptions don't seem to be canceled, causing residual effects. For one, I frequently get a `NoSuchMethodError. add was called on null`, and seems like every time I hot reload, the number of times I get that error increases. Other streams based on firebase fire repeatedly after a hot restart. I know this is hot restart based because when killing and rebuilding, this issue doesn't exist.

## Proposal
Close all streams on hot restart.

**Comment by ThinkDigitalSoftware** [comment]
Does anyone know if this is a verified issue? Especially since I see no reason for streams to be kept open when an app is restarted. This hurts the usefulness of hot restart for me

**Comment by zanderso** [comment]
The Flutter framework and Dart VM don't know anything about plugin state that might need to be destroyed or restored on a hot restart. A plugin would likely need to be specifically architected for this on a case-by-case basis.

Removing the 'tool' label since this likely can't be addressed from tooling.

**Comment by ThinkDigitalSoftware** [comment]
What  is it about streams that don't allow it to be destroyed like all the other variables do during hot restart?

**Comment by raphael-bmec-co** [comment]
Hi All.

I am seeing this same issue. It is making development untenable. Does anyone have any work arounds and/or is there any progress on a fix?

Thanks

**Comment by AlluringKettle** [comment]
Same issue. I listen to FirebaseAuth stream like this:
```
FirebaseAuth.instance.authStateChanges().listen((User? user) {
  loadFromDatabase();
});
```
On every hot restart, one more listener is added and `loadFromDatabase()` gets executed multiple times instead of once. I can't seem to find any fixes and it's really infuriating.

**Comment by raphael-bmec-co** [comment]
@AlluringKettle please see https://github.com/FirebaseExtended/flutterfire/issues/4756 for a work around. Please +1 for a fix.

**Comment by kf6gpe** [comment]
@raphael-bmec-co This was classified as such due to the fact that it's really a feature request, and we've got higher priority issues. The best thing to do is to upvote the issue pointed to by @AlluringKettle (FirebaseExtended/flutterfire#4756).

**Comment by raphael-bmec-co** [comment]
@kf6gpe thank you for the feedback. The pointed to issue (FirebaseExtended/flutterfire#4756) was actually raised by myself some time after my initial comment. At the time I forgot to come back and mention it here. Thanks again.

**Comment by stuartmorgan** [comment]
Closing as there is nothing to track here from the Flutter side, and the plugin-level issue is tracked in the issue referenced above.
