### ISSUE TITLE
Black Icons and Text on iPhoneX

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#33671]
I was testing it on a real iPhone X, in `release` build.

The app was running normally but then a tapped the button that changes the GoogleMap `mapType`  to a satelite view and then, that happened:

![image](https://user-images.githubusercontent.com/1146982/58730635-11ae2e80-83c3-11e9-8873-def635059584.png)

Am I doing something wrong or is that a real bug? I could not reproduce it again neither I know how that happened. Also, it never happened before.

[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [versÃ£o 10.0.17763.503], locale pt-BR)

```
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] Connected device (1 available)

• No issues found!

```

**Comment by BondarenkoStas** [comment]
@shinayser I'm going to close the issue as the is no info how to reproduce it, and if it's not appearing anymore (i couldn't find anything except this issue), maybe it's not an issue. If you experience it again or have new input, don't hesitate to comment and I will re-open it.
