### ISSUE TITLE
Java error when running flutter app on Android simulator. The error message says "the trustAnchors parameter must be non-empty". IOS simulator works fine. 

### ISSUE THREAD

**Issue by RaymondFontaine** [flutter/flutter#33686]
Please help! When running the Android SDK built for x86. I get the error message in the Console:

Finished with error: Processing...…     See image below. It seems to be a java issue and I am using a MAC Air. I tried to delete Java and re-download, but this did not work

![error](https://user-images.githubusercontent.com/51226442/58739246-24723480-83be-11e9-8cff-309324fe3d23.PNG)

edit: just fixed this. I needed to upgrade the Java JDK.

**Comment by JerryX** [comment]
so, which version do you switch. mine is openjdk version "1.8.0_41"
