### ISSUE TITLE
Pressing `q` in `flutter run` on Fuchsia doesn't quit the app

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#33689]
Reproduction:

`flutter run` with a Fuchsia device attached
Once it's all deployed and set to go, press `q`.

The console says `Application terminated`, but the application is still present

/cc @jonahwilliams @zanderso

**Comment by jonahwilliams** [comment]
I added a workaround to avoid calling `dart:io`'s exit in a service extension, but we'll probably need to fix this so instead it calls some tiles ctl method to kill the app

**Comment by dnfield** [comment]
Why can't we just call exit()?  

Is tiles_ctl required for running or attaching flutter to a mod?

**Comment by dnfield** [comment]
Looks like there was code added to call the tile_ctl stop method recently that may not be working: https://github.com/flutter/flutter/pull/32849

**Comment by dnfield** [comment]
So that call seems to work in at least some cases.  But not the case of pressing `q`.

**Comment by jonahwilliams** [comment]
There were some issues with embeddings that don't support all of dart:io (not web). Lets sync on this tomorrow briefly.

**Comment by jonahwilliams** [comment]
Was this fixed by https://github.com/flutter/flutter/pull/33846?

**Comment by dnfield** [comment]
Probably.  I'll reopen if I find it's not working again
