### ISSUE TITLE
[web] hover event not working correctly

### ISSUE THREAD

**Issue by kenthinson** [flutter/flutter#33707]
## Steps to Reproduce
1. Create flutter web app.
2. Add test code
`            Listener(child: Image.network("http://localhost/home.png", fit: BoxFit.cover,), 
                      onPointerHover: (event){
                        print('hover');
                      },
                      onPointerEnter: (event){
                        print('enter');
                      },
                      onPointerDown: (event){
                        print('down');
                      },
                      ),`
Expected result:
Console output should print enter when mouse is moved over the image.
Console should print hover when mouse is over image
console should print down when clicked

Actual result:
Moving mouse over image nothing happens. no response.
clicking the image prints down, and enter the first time clicked.
repeated clicking prints down without the enter.
hover is never printed.
   
Tried with both flutter stable and flutter beta branch.

**Comment by Eugene-Kolesnikov** [comment]
I have the same issue

**Comment by AppleEducate** [comment]
For me onTap must not be null for onHover to be called:

```dart
 InkWell(
        onHover: (hover) {
          if (mounted) {
            setState(() {
              _hover = hover;
            });
          }
        },
        onTap: () {},
)
```
