### ISSUE TITLE
DataTable doesn't support dark theme, text is hard to read

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3370]
The DataTable widget was just implemented to the spec, which only mentions light theme colors. We should make sure it's usable in the dark theme.

**Comment by sethladd** [comment]
Text in the data table is hard to read when using the dark theme in the gallery.

![screenshot_20160517-164004](https://cloud.githubusercontent.com/assets/5479/15342971/13dd6aac-1c4e-11e6-8bc8-d7026a8edc94.png)

**Comment by abarth** [comment]
We probably need to flip the default text style like we do in `Material`.

**Comment by Hixie** [comment]
Yeah this is a known (though apparently not filed) issue. The spec doesn't mention the dark theme so I have't implemented it yet, but we should figure out what the right thing is for each part of the table and do it. I'll probably do it once I've done data cards (which add more complexity).
