### ISSUE TITLE
problem in configuring project in flutter

### ISSUE THREAD

**Issue by smartwebzonedeveloper** [flutter/flutter#33705]
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: bafd59a37dab4da5)
Crash report written to /Users/smartwebzone/readbook/flutter_25.log;
please let us know at https://github.com/flutter/flutter/issues.
Process finished with exit code 1

**Comment by BondarenkoStas** [comment]
@smartwebzonedeveloper ok, but what is the issue? Please show the content of flutter_25.log

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
