### ISSUE TITLE
[web] Navigator needs improvements to work well for the web

### ISSUE THREAD

**Issue by aryzhov** [flutter/flutter#33717]
I tried to create a website using Flutter Web using a `TabBar` for top-level navigation. The challenge was to make the current tab in the tab bar be consistent with the URL.  I used callbacks on `TabController` and `Navigator` to make the URL reflect the current tab and vice versa. I put the entire project in a public repo [here](https://github.com/aryzhov/flutter_web_navigation_demo).

The solution works with some issues:

1. Redundant page redraw as Navigator replaces the current page with a new one. 
2. A Back button appears if the initial URL is not the home page.

These issues are described in detail in the **Issues** section of the README. 

I am not sure what the best course of action would be to address the issues but I put my thoughts on it in the **Thoughts** section of the README.

**Comment by pouledodue** [comment]
Looking at the generated html source code , if I am on Home and then change to About by typing in the location bar, it creates a second
`<flt-offset created-by="RenderRepaintBoundary"> About` on top of the 
original 
`<flt-offset created-by="RenderRepaintBoundary"> Home`

That `RenderRepaintBoundary` corresponds to which widget in the dart code?

**Comment by aryzhov** [comment]
@pouledodue If you change the URL, Navigator will call the builder for that Route. In this example, the builder returns MyHomePage for every page.

**Comment by yjbanov** [comment]
@pouledodue The previous route is likely still rendered, it's just hidden under the new route.

**Comment by darshankawar** [comment]
Issue replicable on latest master. While navigating from one tab to another, a redundant page overlaps the navigation.

[33717.mov.zip](https://github.com/flutter/flutter/files/5224438/33717.mov.zip)

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.22.0-10.0.pre.174 • channel master • https://github.com/flutter/flutter.git
Framework • revision 37b03ec2c2 (4 hours ago) • 2020-09-14 23:52:04 -0400
Engine • revision 7e962ba911
Tools • Dart 2.10.0 (build 2.10.0-124.0.dev)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-10.0.pre.174, on Mac OS X 10.15.4 19E2269, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (4 available)

• No issues found!
```

</details>

**Comment by exaby73** [comment]
I can still reproduce this issue from the code sample. Though, with the introduction of Navigator 2.0, this issue looks like it has an official solution. @aryzhov does the navigator 2.0 API help you solve this issue?
