### ISSUE TITLE
通过AndroidView集成高德地图插件后，TextField组件弹出点击弹出键盘后，AndroidView上面的地图出现异常！(After integrating the Gaode map plugin through AndroidView, the TextField component pops up and pops up the keyboard, and the map above the AndroidView is abnormal!)

### ISSUE THREAD

**Issue by android-shiyan** [flutter/flutter#33711]
W/Adreno-EGLSUB(14170): <DequeueBuffer:721>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGL(14170): <qeglDrvAPI_eglSwapBuffers:3800>: EGL_BAD_SURFACE
W/GLThread(14170): eglSwapBuffers failed: EGL_BAD_SURFACE
AndroidView集成高德地图后，TextField组件点击后弹出键盘，然后出现上面的错误，请问怎么解决，谢谢。
(google translate)
After AndroidView integrates Gaode map, the TextField component pops up the keyboard after clicking, and then the above error occurs. How to solve it, thank you.

**Comment by BondarenkoStas** [comment]
@android-shiyan did you find a way to solve it? please provide your flutter doctor. also please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
