### ISSUE TITLE
[Web] Ubuntu Flutter Webdev

### ISSUE THREAD

**Issue by EdisonTKPcom** [flutter/flutter#33721]
## Steps to Reproduce

1. flutter pub global activate webdev

## Logs
Command: /home/ubuntu/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/ubuntu/flutter/.pub-cache/global_packages/webdev/.packages --snapshot=/home/ubuntu/flutter/.pub-cache/global_packages/webdev/bin/webdev.dart.snapshot.dart2 file:///home/ubuntu/flutter/.pub-cache/hosted/pub.dartlang.org/webdev-2.0.6/bin/webdev.dart
pub failed (1)

```
```

```
```

**Comment by jakemac53** [comment]
We should move all webdev issues to the webdev repo regardless imo.

@EdisonTKPcom do you have more information here? What OS are you using, and what flutter sdk version?

**Comment by jakemac53** [comment]
Also please provide the full output with `-v`.

**Comment by jakemac53** [comment]
@kevmoo can you please move the issue to webdev

**Comment by kevmoo** [comment]
@jakemac53 – will have to copy-paste. Cannot move issues across orgs. 🤷‍♂

**Comment by ferhatb** [comment]
webdev no longer used by for flutter.
