### ISSUE TITLE
Ensure we can debug hello_services style projects from IntelliJ (was: How to debug the flutter code in Hello_Android project?)

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#3372]

**Comment by Hixie** [comment]
Does <https://flutter.io/debugging/> answer your question at all?

**Comment by tain335** [comment]
I want to use atom to debug the code in Hello_Android project, but I have no idea now.

**Comment by Hixie** [comment]
cc @devoncarew do we have any docs other than https://flutter.io/debugging/ that talk about how to do that?

**Comment by tain335** [comment]
I think atom-flutter plugin should add a new feature: can attach the activity that have flutter-view widget and debug with atom.But if I want to  use multi flutter-view widgets in a activity or application at the same time,  how to deploy and how to debug with them?

**Comment by eseidel** [comment]
It's possible we could tell flutter.yaml where to find the pre-built apk, and then the typical flutter tools (including Atom) could work. This just isn't a part of the workflow that has been worked out yet.  @jason-simmons @abarth

**Comment by abarth** [comment]
> It's possible we could tell the Atom run config file where to find the pre-built apk, and then pass the APK path to flutter run, etc.

I don't think that's a good approach.  Instead, we should use the approach described in this document:

https://docs.google.com/document/d/1DOfwpL6VojCAG_zjjcA_z5ekF7rTIohV8dWn2o7_IME/edit?usp=sharing

Specifically, once we refactor `flutter run` and `flutter build apk` to use gradle under the hood, then debugging inside atom will work as expected with hello_android.

**Comment by collinjackson** [comment]
Blocked on #3744

**Comment by abarth** [comment]
@jason-simmons is working on this issue.

**Comment by sethladd** [comment]
Is this still in progress by @jason-simmons ?

We might want to reroute to @kasperl as his team is looking at interop dev experience.

cc @johnmccutchan

**Comment by jason-simmons** [comment]
A while ago I added a feature to the Atom plugin for attaching the Dart debugger to a running Flutter app on Android.  We might need something similar for the current tools.

**Comment by eseidelGoogle** [comment]
I believe IntelliJ has support for connecting the debugger to existing processes?  At least I recall @devoncarew mentioning that feature at some point.  FYI @mit-mit in case this falls into the current gradel work.

**Comment by eseidelGoogle** [comment]
FYI @jakobr-google @mit-mit, in case you feel this relates to your current Gradle work.

**Comment by mit-mit** [comment]
Does this now track the ability to debug from IntelliJ a hello_services style project?

**Comment by devoncarew** [comment]
Yes, I think this should track making sure debugging works with hello_services style projects; I updated the title.

**Comment by mit-mit** [comment]
Debugging of hello_services should work already (see https://github.com/flutter/flutter-intellij/issues/471). I'm going to close this for now. If there are specific issues still, should open a detailed issue for that.
