### ISSUE TITLE
android_alarm_manager oneShot is not working after close app

### ISSUE THREAD

**Issue by kamlesh9070** [flutter/flutter#33720]
I want to execute some task (e.g. fetch data from server) in background even app is closed in Flutter App. So How can I achive this? Its' better If anyone provide example for that.

I am trying using android_alarm_manager but facing below issue:

I have cloned ahttps://github.com/jsoref/flutter-plugins/tree/master/packages/android_alarm_manager/example

Modified code as below:

`
    ```
 void printPeriodic() => printMessage("Periodic!");

void printonDelayed() async {

  int i = 0;

  while(i < 50) {

  printMessage("printonDelayed:" + i.toString());

  await sleep1();

  i++;
}
Future<String> sleep1() {

  return new Future.delayed(const Duration(seconds: 1), () => "1");

} 
await AndroidAlarmManager.oneShot(
  const Duration(seconds: 1), oneShotID, printOneShot, exact: true);

await AndroidAlarmManager.oneShot(
  const Duration(seconds: 1), 2, printonDelayed, wakeup: true, exact: true);`
```
`

Periodic! is printing even if I close app.
printonDelayed is not printing if I close app

Android Version: 8.1.0

**Comment by TahaTesser** [comment]
Hi @kamlesh9070 
if you're still experiencing this problem with latest stable, please create a new issue and provide the information required in the template.
Thank you
