### ISSUE TITLE
multiple issues with iOS build

### ISSUE THREAD

**Issue by suesitran** [flutter/flutter#33724]
## Steps to Reproduce

There's no specific step to reproduce this. I'm working on my own project, and suddenly the following issues start to happen, and 1 leads to the other, and I'm now stuck
1. I cant use "flutter run" on my iphone and simulator using the same ios/Flutter/App.framework. For example, If i'm currently running the build on an iPhone, when I try to run on simulator, I get error “Undefined symbols for architecture x86_64”. If i create new project, copy over the App.framework from the new project, i can run on simulator, but once i start running it on iphone again, i get similar but different error: “Undefined symbols for architecture armv7”. The same issue when I run using Xcode. So now I only run the code on my iphone
2. after accepting the fact to run my code on my iphone, i realised that whatever changes I make to the code is not applied in my phone, except the version and build number, other than that, no changes is applied, not even a print() statement. I even tried to remove runApp() from main.dart, and the app is still running as usual. And I can confirm that Android build works fine.

## Flutter doctor
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.13.6 17G8011, locale en-AU)
    • Flutter version 1.5.4-hotfix.2 at /Users/suesitran/flutter
    • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/suesitran/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by iapicca** [comment]
Hi @suesitran 
are you still experiencing this issue with the latest version of Flutter?
If so please reply attaching your `flutter doctor -v`,
you may also please post a self contained app on github 
to help us to better address the issue.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
