### ISSUE TITLE
FutureBuilder error with stream

### ISSUE THREAD

**Issue by waqarsaeed45** [flutter/flutter#33733]
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 1351): The following assertion was thrown building NewsList(dirty, dependencies: [StoriesProvider]):
I/flutter ( 1351): type 'Future<dynamic>' is not a subtype of type 'Stream<List<int>>'
I/flutter ( 1351): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 1351): more information in this error message to help you determine and fix the underlying cause.
<img width="659" alt="Screenshot 2019-06-03 at 12 50 42 AM" src="https://user-images.githubusercontent.com/46153334/58766562-c437ea00-8599-11e9-839c-0bd9b00e0888.png">

**Comment by waqarsaeed45** [comment]
Solved the issue was in the bloc.fetchTopIds() method instead of using observable i was directly calling the async method in bloc class which wasn't returning anything neither it was a stream.

**Comment by iapicca** [comment]
Hi @waqarsaeed45,
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it
