### ISSUE TITLE
[web]: How can we use javascript in flutter web

### ISSUE THREAD

**Issue by wedcel** [flutter/flutter#33744]
We need to  lead into some third-party components, which do not have flutter version , only the web version can be used. Most of these components interact through javascript. How can we use them? How do I interact with Flutter here?

**Comment by wedcel** [comment]
@pouledodue  Thank you. I'm learning about dart: js, but there's a little information. Here's a question to see if there are any other suggestions or samples.

**Comment by kenthinson** [comment]
@wedcel As flutter web is in pre-release it looks like the official way is not completed yet. Usually You would use WebView widget. However this Widget is not available for flutter web yet.

**Comment by yjbanov** [comment]
As @pouledodue points out you can use `dart:js`. There's a more ergonomic `package:js` (https://pub.dev/packages/js - this package is the recommended way of doing JS-interop).
