### ISSUE TITLE
Font khmer unicode overflow cropping

### ISSUE THREAD

**Issue by lyhourtheng** [flutter/flutter#33745]
The Khmer text Unicode is rendering outbound of screen edge on both ios and android platform.

**On iOS device (iphone 7)**

![ios](https://user-images.githubusercontent.com/29015043/58787042-23861080-8613-11e9-946e-5fab7b478239.PNG)

**On Android device (Huawei P9)**

![Android](https://user-images.githubusercontent.com/29015043/58787054-284ac480-8613-11e9-9b56-a1954a9b4470.png)

**Here is flutter doctor:**

<img width="585" alt="Screen Shot 2019-06-03 at 3 02 52 PM" src="https://user-images.githubusercontent.com/29015043/58785994-dd2fb200-8610-11e9-85eb-39db5e2cf9a5.png">

**Comment by mikhail-tokarev** [comment]
Hi @lyhourtheng 
are you still experiencing this issue with the latest version of Flutter?

If so please reply attaching your `flutter doctor -v`,
you may also please post a self contained app on github 
to help us to better address the issue.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
