### ISSUE TITLE
unreachable code crash on iOS - minimum reproducible project included

### ISSUE THREAD

**Issue by rockgecko-development** [flutter/flutter#33751]
## Steps to Reproduce

I have made a minimum reproducible project here: https://github.com/rockgecko-development/UnreachableBug
Basically, running the following 9 lines of code in a 10ms repeat loop, eventually causes the app to crash, when run on iOS in debug mode,

```dart
Timer.periodic(Duration(milliseconds: 10), (tt) {
//the values in this 3 element vector don't matter
var event = [21.1, 41.2, 98.1];

//create a new array, then copy the event values into it.
var scratchArray = List.filled(3, 0.0);
scratchArray[0] = event[0];
scratchArray[1] = event[1];
scratchArray[2] = event[2];

//calculate the magnitude of the vector:
magnitude = Math.sqrt(Math.pow(scratchArray[0], 2) +
  Math.pow(scratchArray[1], 2) +
  Math.pow(scratchArray[2], 2));
//call NumberFormat.format(any number)
magnitudeStr = df.format(1.234);
});
```

The output is:
```
../../third_party/dart/runtime/vm/compiler/backend/il_dbc.cc: 151: error: unreachable code
version=2.3.0-dev.0.5.flutter-a1668566e5 (Tue Apr 30 20:35:41 2019 +0200) on "ios_dbc"
thread=35415, isolate=main(0x108837000)
  pc 0x00000001016c3420 fp 0x000000016f9d8c30 dart::Profiler::DumpStackTrace(void*)
  pc 0x0000000000000001 fp 0x000000016f9d8ea0 Unknown symbol
  pc 0x0000000000000000 fp 0x000000016f9d9c18 Unknown symbol

-- End of DumpStackTrace
Lost connection to device.
Exited (sigterm)

```

It works fine in release mode, and on the simulator, and on Android. Changing any of the steps in the timer function cause it to no longer crash (eg, eliminating the `scratchArray` and using `event` in the magnitude calculation directly, eliminating the magnitude calculation, or removing the `NumberFormat` call). They're all necessary. It still crashes if the timer interval is increased to 50ms, it just takes a bit longer to crash.

## Logs

Tried on iPhone 6 and iPhone 7, iOS 12

>flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E227, locale
>    en-AU)
> [!] Android toolchain - develop for Android devices (Android SDK version 25.0.2)
>    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
>      To update using sdkmanager, run:
>        "/Users/build/Library/Android/sdk/tools/bin/sdkmanager"
>        "platforms;android-28" "build-tools;28.0.3"
>      or visit https://flutter.dev/setup/#android-setup for detailed
>      instructions.
>    ✗ Android license status unknown.
>      Try re-installing or updating your Android SDK Manager.
>      See https://developer.android.com/studio/#downloads or visit
>      https://flutter.dev/setup/#android-setup for detailed instructions.
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
> [!] Android Studio (version 2.2)
>    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>    ✗ Dart plugin not installed; this adds Dart specific functionality.
> [✓] Connected device (1 available)
> 
> ! Doctor found issues in 2 categories.

I've ignored the Android errors because I use a different computer to build for Android.

**Comment by mikhail-tokarev** [comment]
Hi @rockgecko-development 
are you still experiencing this issue with the latest version of Flutter?
If so please reply attaching your `flutter doctor -v`

**Comment by rockgecko-development** [comment]
Hi, I updated to v1.9.1+hotfix.4, same macbook & iPhone, and the issue appears fixed. Thanks!
