### ISSUE TITLE
Native Android View NO transparent background (works fine on iOS)

### ISSUE THREAD

**Issue by andreiafurbeis** [flutter/flutter#33756]
My flutter application on the main screen has a background image, and I would like to place a native view on it.
As for IOS I managed to make the background of the view transparent and therefore visible the image, for android instead I couldn't find a solution (it always remains white).
Has anyone managed to fix it somehow?

**Comment by AndreaMiotto** [comment]
Hi, I have the same issue in one of my projects.
This is blocking me to release the app to the store.

Anyone has a fix?

**Comment by AndreaMiotto** [comment]
Can someone help us with this issue?
@abarth, @jonahwilliams, @goderbauer, @tvolkert

**Comment by amirh** [comment]
https://github.com/flutter/engine/pull/7236 is  a proposed fix that's waiting for me to review(for pretty long now, sorry). I'm first dealing with the keyboard stuff which seems to affect more people.

**Comment by AndreaMiotto** [comment]
> [flutter/engine#7236](https://github.com/flutter/engine/pull/7236) is a proposed fix that's waiting for me to review(for pretty long now, sorry). I'm first dealing with the keyboard stuff which seems to affect more people.

Thank you for bringing you attention to this issue. We will wait for your review

**Comment by andreiafurbeis** [comment]
> [flutter/engine#7236](https://github.com/flutter/engine/pull/7236) is a proposed fix that's waiting for me to review(for pretty long now, sorry). I'm first dealing with the keyboard stuff which seems to affect more people.

Thank you so much, I'll wait you review

**Comment by dfavaro** [comment]
Hi guys! I have this problem too! Still no fix? Any temporary workaround?
