### ISSUE TITLE
camera plugin issue camera: ^0.5.2+1

### ISSUE THREAD

**Issue by jagadish906** [flutter/flutter#33755]
while recording with the front camera the screen became darker and the comparing with my mobile camera the shape of the object or face with flutter camera and is very very narrow and it is not looks like me also
I am using camera from the past three months but the camera issue is not yet resolve Please check because it is very important to all applications

**Comment by mikhail-tokarev** [comment]
Hi @jagadish906 
are you still experiencing this issue with the latest version of Flutter?
If so please reply attaching your flutter doctor -v

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
