### ISSUE TITLE
firebase_core using deprecated API

### ISSUE THREAD

**Issue by kmusham** [flutter/flutter#33769]
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.0+3\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
