### ISSUE TITLE
Weird unexplained bump in consumer dependency count

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#33767]
https://github.com/flutter/flutter/pull/33533 increased the consumer dependency count somehow.

cc @jonahwilliams

**Comment by jonahwilliams** [comment]
Its a bug in how pinned dependencies count in the benchmark

**Comment by Hixie** [comment]
Ah, I wondered if that might be the case. Easy to fix, or...?

**Comment by jonahwilliams** [comment]
Easy to fix, pending in https://github.com/flutter/flutter/pull/33786/files since I hit an issue updating packages anyway
