### ISSUE TITLE
FormatException: Bad UTF-8 encoding 0xfc (at offset 99)

### ISSUE THREAD

**Issue by baeharam** [flutter/flutter#33763]
Hello, guys! I'm suffering from this fatal error. I saw lots of answers about this kind of issues, but I couldn't solve at all.

I read #15646, but it didn't work for me.

How can I handle this?, I posted screenshot and result of `flutter doctor -v`.

> [✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale ko-KR)
>     • Flutter version 1.5.4-hotfix.2 at /Users/baeharam/haram/development/flutter
>     • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
>     • Engine revision 52c7a1e849
>     • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/baeharam/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
>     • All Android licenses accepted.
> 
> [!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.2.1, Build version 10E1001
>     ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
>         brew update
>         brew install --HEAD usbmuxd
>         brew link usbmuxd
>         brew install --HEAD libimobiledevice
>         brew install ideviceinstaller
>     ✗ ios-deploy not installed. To install:
>         brew install ios-deploy
>     ✗ CocoaPods not installed.
>         CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
>         Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
>         For more info, see https://flutter.dev/platform-plugins
>       To install:
>         brew install cocoapods
>         pod setup
> 
> [✓] Android Studio (version 3.4)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 35.3.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [✓] VS Code (version 1.34.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.1.0
> 
> [✓] Connected device (1 available)
>     • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
> 
> ! Doctor found issues in 1 category.
> 

![image](https://user-images.githubusercontent.com/35518072/58816180-ed24b180-8663-11e9-91c7-6ef45d24b9d0.png)

**Comment by janmoppel** [comment]
Hello @baeharam !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
