### ISSUE TITLE
'package_info' using deprecated API

### ISSUE THREAD

**Issue by kmusham** [flutter/flutter#33770]
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.0+3\android\src\main\java\io\flutter\plugins\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by danwulff** [comment]
Duplicate of #29772

**Comment by BondarenkoStas** [comment]
Duplicate of #29772. Thank you @danwulff !
