### ISSUE TITLE
type 'int' is not a subtype of type 'String'   

### ISSUE THREAD

**Issue by Mahesh73** [flutter/flutter#33773]
import 'dart:convert';

import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
  theme: ThemeData(
    primarySwatch: Colors.teal,
  ),
  home: HomePage(),
));

class HomePage extends StatefulWidget{
  @override
  HomePageState createState() => HomePageState();
}

class HomePageState extends State<HomePage>{
  List data;
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      appBar: AppBar(
        title: Text("load Json App"),
      ),
      body: Container(
        child: Center(
          child: FutureBuilder(
              future : DefaultAssetBundle.of(context).loadString('load_json/person.json'),
          builder: (context, snapshot){
                var myData = jsonDecode(snapshot.data.toString());

                return ListView.builder(
                  itemBuilder: (BuildContext context,int index){
                    return Card(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        children: <Widget>[
                          Text("Name: "+myData[index]['name'] ),
                          Text("Age: "+myData[index]['age'] ),
                          Text("Height: "+myData[index]['height'] ),
                          Text("Gender: "+myData[index]['gender'] ),
                          Text("Color: "+myData[index]['color'] ),
                        ],
                      ),
                    );
                  },
                  itemCount: myData == null ? 0 : myData.length,
                );
          },),
        ),
      ),
    );
  }

}

Log:    
Performing hot restart...
Syncing files to device Redmi Note 4...
Restarted application in 4,044ms.
I/flutter ( 9313): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9313): The following assertion was thrown building:
I/flutter ( 9313): type 'int' is not a subtype of type 'String'
I/flutter ( 9313): 
I/flutter ( 9313): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 9313): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 9313): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 9313):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 9313): 
I/flutter ( 9313): When the exception was thrown, this was the stack:
I/flutter ( 9313): #0      HomePageState.build.<anonymous closure>.<anonymous closure> (package:json_flutter/main.dart:40:53)
I/flutter ( 9313): #1      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:398:15)
I/flutter ( 9313): #2      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1006:67)
I/flutter ( 9313): #3      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:137:29)
I/flutter ( 9313): #4      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1006:26)
I/flutter ( 9313): #5      SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:984:69)
I/flutter ( 9313): #6      SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:998:23)
I/flutter ( 9313): #7      SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:961:7)
I/flutter ( 9313): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 9313): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 9313): #11     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9313): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9313): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #15     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter ( 9313): #16     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter ( 9313): #17     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
I/flutter ( 9313): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9313): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9313): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9313): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9313): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 9313): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 9313): #29     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9313): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9313): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 9313): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 9313): #35     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9313): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9313): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9313): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9313): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9313): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 9313): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 9313): #47     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9313): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 9313): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 9313): #51     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9313): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 9313): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 9313): #55     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9313): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 9313): #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 9313): #59     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9313): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 9313): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 9313): #63     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9313): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 9313): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 9313): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 9313): #67     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
I/flutter ( 9313): #68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter ( 9313): #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter ( 9313): #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter ( 9313): #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter ( 9313): #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter ( 9313): #76     _invoke (dart:ui/hooks.dart:219:10)
I/flutter ( 9313): #77     _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter ( 9313): (elided 3 frames from package dart:async)
I/flutter ( 9313): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by stuartmorgan** [comment]
This is not actually a framework bug; the message to report it here is mis-firing (see #18412)

Dart doesn't auto-convert ints to strings the way, say, JS does, so you can't freely mix them with `+`.

**Comment by kagz** [comment]
i have a similar problem....@stuartmorgan so what is the best move
