### ISSUE TITLE
Gallery: Cold start time to draw homescreen and header image is 3.5 seconds

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3378]
On my Nexus 6P, cold start of the gallery app, it seems to average around 3.5 seconds from tap of icon to drawing header image.

On my iPod Touch, the cold-start (all the way to displaying the header image) seems to average less than 1 second.

**Comment by eseidelGoogle** [comment]
If we switch to AOTC it will be closer to 600ms.

**Comment by eseidelGoogle** [comment]
`flutter run --release` works on both iOS and Android now.   Assigning to Seth for verification/closure.

**Comment by sethladd** [comment]
Woohoo! Happy to give it a shot.

**Comment by sethladd** [comment]
AOT makes our startup fast. Thanks!
