### ISSUE TITLE
Link to playfair API docs from Google Search returns 404

### ISSUE THREAD

**Issue by qchong** [flutter/flutter#3379]
Steps to reproduce:
1. From Google Search, type "charting flutter".
2. Click on the first link in the results (points to [https://github.com/domokit/playfair](https://github.com/domokit/playfair) which returns a 404)

The correct page to the Playfair API docs is here:
[http://docs.flutter.io/flutter/playfair/playfair-library.html](http://docs.flutter.io/flutter/playfair/playfair-library.html)

**Comment by qchong** [comment]
@sethladd How do we get Google Search to correctly index our Flutter API docs?

**Comment by sethladd** [comment]
I guess we could recreate the domokit/playfair repo and put a single README in there that redirects a user over to flutter.

**Comment by sethladd** [comment]
cc @tonygentilcore can you help us create a repo in domokit and give @qchong the permissions to add a README to that repo?

**Comment by eseidelGoogle** [comment]
I just requested removal: https://www.google.com/webmasters/tools/removals

**Comment by sethladd** [comment]
Thanks. I think this will sort itself out over time. Going to close this, but let's continue to monitor our SEO.

**Comment by sethladd** [comment]
@tonygentilcore no action required :)
