### ISSUE TITLE
Turn on references to HttpClientResponseCompressionState

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#33791]
https://github.com/flutter/flutter/commit/2467c528f530b0ad0ab952e98eaee77edb241da5 rolled the Dart SDK into flutter/flutter, and as part of that change, the API of `HttpClientResponse` changed to include a `compressionState` getter that returns a newly defined `HttpClientResponseCompressionState` enum.

Since the requisite Dart SDK commit (https://github.com/dart-lang/sdk/commit/aa2ce7cfbfaca5439b86b6ee4ad503691b8ce0ac) has not yet rolled into Google, Flutter is blocked on landing this code in Google yet.

To keep Flutter rolls (dev releases) flowing, we'll temporarily comment out these references to `HttpClientResponseCompressionState` upstream (and implement `noSuchMethod()` to keep the analyzer happy).

This issue tracks the need to turn these references back on once the requisite Dart SDK lands inside Google.

**Comment by tvolkert** [comment]
@keertip I made you a co-assignee since you'll be working on landing the Dart SDK inside Google.

**Comment by keertip** [comment]
I am seeing these failures when testing bleeding edge Dart SDK in google. So comment it out is a good way to go. It has to land in Flutter only after the Dart SDK has been updated internally.

Hoping to get a build in the next couple days.

**Comment by tvolkert** [comment]
This has been fixed.
