### ISSUE TITLE
[iOS 13] cupertino switch is different

### ISSUE THREAD

**Issue by xster** [flutter/flutter#33797]
![Kapture 2019-06-03 at 14 29 31](https://user-images.githubusercontent.com/156888/58835884-069a0f00-860c-11e9-9c00-b8eb2ff0f468.gif)

No more 3d stuff

**Comment by Hixie** [comment]
Oh wow it's much simpler.

**Comment by xster** [comment]
Ya, it's just a color fade now

**Comment by brandondiamond** [comment]
Tossed together a quick PR for this (hopefully I'm not stepping on any toes!):

https://github.com/flutter/flutter/pull/36087

**Comment by justinmc** [comment]
Closing with https://github.com/flutter/flutter/pull/36087.

The next release (>1.8.2) should contain these changes.
