### ISSUE TITLE
[iOS 13] navigation transition styles can now mix

### ISSUE THREAD

**Issue by xster** [flutter/flutter#33799]
Branching off from #33798

![Kapture 2019-06-03 at 14 34 10](https://user-images.githubusercontent.com/156888/58836126-aeafd800-860c-11e9-9e25-79bec0383bea.gif)

**Comment by xster** [comment]
Note that the inner normal push style vc was nested in the first stacked vc and both got swiped via the gesture

**Comment by justinmc** [comment]
I'm guessing that a right swipe back gesture works on the nested "Repeat" page in the gif to go back to the "New Event" page.  However, a right swipe on the "New Event" page probably does nothing, and you must swipe down or press "Cancel" to dismiss.

**Comment by justinmc** [comment]
Here's the video from WWDC about this, around the 12:00 mark talking about the tabbed top modals. https://developer.apple.com/videos/play/wwdc2019/224/

**Comment by jeroen-meijer** [comment]
Just wanted to give my two cents.

Since iOS 13 launched about a year ago, this view has become really popular and is very often used.
I feel it's essential for Flutter to support this kind of view in the near-future, especially since iOS 14 is about to release.

Cupertino deserves some love. 💙
