### ISSUE TITLE
Stocks is empty.

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#338]
cc @eseidel

**Comment by eseidelGoogle** [comment]
Do we know if it's iOS only?  Firebase uses https currently:
https://github.com/flutter/flutter/blob/master/examples/stocks/lib/stock_data.dart#L65

**Comment by Hixie** [comment]
I was seeing this on Android, but haven't been able to reliably reproduce.

**Comment by abarth** [comment]
I haven't been able to reproduce this issue.

**Comment by abarth** [comment]
Please re-open if you can reproduce again.
