### ISSUE TITLE
Make engine layers immutable

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#33807]
This would make it safer to do retained rendering, and avoid loops (in the layer tree). In the end, an engine layer would be like a Flutter framework `Widget` whose attributes and children relationships must be set during construction.

The current retained rendering already assumes such immutability. Now we need to change the engine API to enforce it.

**Comment by liyuqian** [comment]
@yjbanov : when do you think would be a good time estimate for achieving this (on Flutter for Web)?

**Comment by yjbanov** [comment]
This work hasn't been planned yet. I'd guess if we scheduled it, it would be ~2019Q4.

**Comment by kf6gpe** [comment]
@yjbanov @ferhatb Did we schedule this work on the web site for 2019Q4 or 2020Q1?

**Comment by ferhatb** [comment]
@ kf6gpe Nothing scheduled around this yet. There is a backlog rendering issues we need to burn down first. Is this blocking any other effort?

**Comment by kf6gpe** [comment]
Nope. Just checking in on whether or not it was scheduled. Thanks!

**Comment by jonahwilliams** [comment]
Closing as obsolete
