### ISSUE TITLE
Android Multiple Dex  Conflicts after update

### ISSUE THREAD

**Issue by vajohn** [flutter/flutter#33803]
Flutter package [webview ](https://pub.dev/packages/webview_flutter)conflicts with [google_sign_in ](https://pub.dev/packages/google_sign_in) and any [firebase ](https://pub.dev/packages/firebase_auth)package. I have tried updating and working on a new project. Same issue persists, not sure how to edit the gradle file if it helps with the android.support.v4.os.ResultReceive Multi Dex issue

**Comment by vajohn** [comment]
[√] Flutter (Channel master, v1.10.14-pre.20, on Microsoft Windows [Version 10.0.17763.737], locale en-US)
    • Flutter version 1.10.14-pre.20 at C:\Users\lajabuj\.f lutter
    • Framework revision 6760628147 (14 hours ago), 2019-10-08 10:39:09 -0700
    • Engine revision 49dbaae818
    • Dart version 2.6.0 (build 2.6.0-dev.6.0 aece1c1e92)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\lajabuj\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1
    • Flutter plugin version 35.2.2
    • Dart plugin version 191.6183.88

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\lajabuj\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (2 available)
    • Chrome          • chrome          • web-javascript • Google Chrome 77.0.3865.90
    • Headless Server • headless-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

**Comment by iapicca** [comment]
Hi @vajohn 
can you also provide your `flutter run --verbose`
thanks again

**Comment by christopherfujino** [comment]
I am closing this issue for now as unactionable. @vajohn if you are still experiencing this issue, feel free to re-open with an actual stack traces (e.g. via `flutter run --verbose`) and preferably a minimal reproduction with source code and `pubspec.yaml`.
