### ISSUE TITLE
FormField<T> is not useable for non-String value types

### ISSUE THREAD

**Issue by aryzhov** [flutter/flutter#33816]
`FormField` is supposed to handle field value validation. The problem is that validation occurs after the value is set, and the value is stored as T. Suppose I want to have a date field where the user can enter a date by typing it in the form MM/DD/YY. I would like to create a `FormField<DateTime>`. But how am I supposed to validate the input string if I have to call `didChange(T value)` first and `validate()` second? In order to call `didChange(date)` I have to have a parsed date, and if there is an error there's no way to communicate it to the validator, which takes a `DateTime` object.

**Comment by kenthinson** [comment]
Not a solution for the issue however it might be helpful to mention to you that there is the showDatePicker. It will prevent the user from putting in anything thats not a date.

**Comment by aryzhov** [comment]
@kenthinson Thanks, I know about `showDatePicker`, but I'd like to stress that it does not change the reasoning here. Let me make a few more examples: a number entry field, a currency field with a currency selector, a phone number entry (where the phone number is stored as an object with country code, area code, etc), distance entered in inches and feet (which combines two text fields) in a single form field, a mathematical expression that gets parsed as it's entered and is stored as an AST.

If `FormField` is designed to work only with Strings and only with TextField as the underlying widget then there's no need to the generic `T` parameter, in which case its utility would be significantly reduced. I believe that the concept of `Form` and `FormField` should evolve to the level of other frameworks where fields of different kinds support a common data binding interface.

I did in fact make a `FormField<DateTime>` that combines a text field and a date picker, but it uses a hack to store the error message separately and returning it later in `validate()`. I found the experience of making a custom `FormField` rather difficult. I had to copy/paste plenty of code from `TextFormField` including the trick of storing a `TextEditingController` in the state object and retrieving it in the `builder` function using a typecast. The ability to make custom form fields is important for the Web, as keyboard entry is much more common there.

**Comment by kenthinson** [comment]
@aryzhov I think I understand now. So you are trying to call validate on every key press instead of just on submit button being pressed?

**Comment by jifalops** [comment]
@aryzhov Check out https://pub.dev/packages/datetime_picker_formfield. It does exactly what you are asking.

**Comment by escamoteur** [comment]
I want to add that the whole way to create a custom FormField is extremely cumbersome. This should indeed much easier if we want to leverage the functionality of Forms. @Hixie

**Comment by Hixie** [comment]
I think the way to do this is to do the conversion validation in the internal text field (the one built by the builder, which is where the string is converted to T).
