### ISSUE TITLE
[Documentation] Additional BottomNavigationBar use cases through samples

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#33810]
## Use case
Currently, the `BottomNavigationBar` [documentation](https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html) supplies sample code for a simple example involving updating the displayed `Scaffold.body` widget. However, there can also be more unique interaction patterns, such as:
1) tapping an already-selected index for additional behavior (ie. to scroll to top of displayed page)
2) having a unique item that doesn't update the selectedIndex (ie. a button that opens a dropdown or modal instead of updating the displayed `Scaffold.body`)

While these are less common, there is some desire for instruction on getting these behaviors implemented.

## Proposal
Create sample docs for one or both cases above to show that `BottomNavigationBar` can be more flexible than expected.

**Comment by amanv8060** [comment]
@guidezpl this issue can be closed ?

**Comment by Piinks** [comment]
Closing as resolved by https://github.com/flutter/flutter/pull/99644
