### ISSUE TITLE
ScaleGestureRecognizer isn't transforming PointerEvents to the local coordinate system of the event receiver

### ISSUE THREAD

**Issue by mtcliatt** [flutter/flutter#33818]
After pull [32192](https://github.com/flutter/flutter/pull/32192), pointer events should be local to the event receiver. But I think I'm still seeing the previous behavior, of global PointerEvents.

I'm still getting global events from GestureDetector.onScaleUpdate. I created a minimal example, where I've got a box that renders the initial focal point of the gesture, as well as the current focal point: [example on gist.github](https://gist.github.com/mtcliatt/24fc63d7d4f58f1e928be1da47c90b2f).

Here's a screenshot of the example that shows the focal points below the box that contains the gesture detector: [link](https://drive.google.com/open?id=1vse_a0u9nISnlPSpLQDPJgDinv6SvNer).

Is this expected?

I'm running:
Flutter 1.6.8-pre.43 • channel master • https://github.com/flutter/flutter.git
Framework • revision cd1d40a (7 hours ago) • 2019-06-03 11:08:30 -0700
Engine • revision f9ce01674e
Tools • Dart 2.3.2 (build 2.3.2-dev.0.0 224f82c21c)

**Comment by VerTiGoEtrex** [comment]
Did you read the description of the pull? I don't think it's intended to change the focal point field.

**Comment by mtcliatt** [comment]
@VerTiGoEtrex My impression was that the change would affect how the focal point is calculated.

**Comment by goderbauer** [comment]
I'll take a look at this as soon as I find some time.

**Comment by goderbauer** [comment]
I can confirm that the `ScaleGestureRecognizer` (which is responsible for `onScaleUpdate`) is not transforming events to the local coordinate space. Looks like I just missed that detector in my PR #32192. I'll send out a patch for that one shortly.

@mtcliatt Your issue title is very generic. Was the scale stuff the only one where you noticed that it doesn't work or is there more?

**Comment by mtcliatt** [comment]
Thanks for the quick investigation!

Yeah the title is way too generic so I'll update that now. It should have originally started with "Some PointerEvents ...", because I only knew of this one occurrence.
