### ISSUE TITLE
[plugins] CI should check version update format

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#33812]
~~I think we should have a CI script checking if a plugins version is updated for each PR if the plugin's code is changed.~~

As well as checking the version format is correct based on https://dart.dev/tools/pub/versioning#semantic-versions

Right now, we have a lot of mistakes such as adding a +w into a post 1.0.0 plugin in the plugin repo. 

For example, I found a 4.0.1+3 version in google_sign_in which should not exist.(It should have been 4.0.2)

Note that it is not a google_sign_in issue, rather a feature request for the plugin repo. please do not label google_sign_in.on it.

**Comment by stuartmorgan** [comment]
Does our current version update script now do this?

**Comment by cyanglaz** [comment]
@stuartmorgan Not yet. 
 And there I think the issue is obslate, we should not "checking if a plugins version is updated for each PR if the plugin's code is changed", because sometimes we don't want to update the version for changes in the plugins (some example app and test changes for example)

We should still improve the tool to
"As well as checking the version format is correct based on https://dart.dev/tools/pub/versioning#semantic-versions"
Right now I think we still allow x.y.z+w while x is >= 1

**Comment by stuartmorgan** [comment]
Looks like that was already added at some point:
https://github.com/flutter/plugins/blob/master/script/tool/test/version_check_test.dart#L400-L403

Given that, closing.
