### ISSUE TITLE
After Flutter upgrade i get this error !

### ISSUE THREAD

**Issue by muss01** [flutter/flutter#33827]
```
Running "flutter pub get" in flutter_unsplash-master...             3,4s
Launching lib/main.dart on TRT LX1 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but the file was not self-contained. This might be a bug.

The Dart team would greatly appreciate it if you would take a moment to report this problem at http://dartbug.com/new.
If you are comfortable with it, it would improve the chances of fixing any bug if you included the file file:///var/folders/4b/cyxynvcx1kxb_cv2pjqdlcy00000gn/T/initialize_from.dilllMx8SK/initialize_from.dill.gz in your error report, but be aware that this file includes your source code.
Either way, you should probably delete the file so it doesn't use unnecessary disk space.
file:///Users/mustaphamouaiad/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.2.5/lib/photo_view.dart:279:24: Error: The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/mustaphamouaiad/Desktop/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/mustaphamouaiad/Desktop/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    stream.addListener(listener);
                       ^
file:///Users/mustaphamouaiad/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.2.5/lib/photo_view.dart:281:29: Error: The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/mustaphamouaiad/Desktop/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/mustaphamouaiad/Desktop/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      stream.removeListener(listener);
                            ^
Compiler failed on /Users/mustaphamouaiad/AndroidStudioProjects/flutter_unsplash-master/lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '/Users/mustaphamouaiad/Desktop/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 647

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugandroid-arm'.
> Process 'command '/Users/mustaphamouaiad/Desktop/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
Finished with error: Gradle task assembleDebug failed with exit code 1

```

**Comment by Liuhuifeng** [comment]
same issue .

**Comment by domchikdev** [comment]
same issue

**Comment by iAmStarter** [comment]
same issue

**Comment by diogocsbr** [comment]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

Compiler message:
file:///C:/Users/Diogo/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:199:38: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      oldImageStream?.removeListener(_handleImageChanged);
                                     ^
file:///C:/Users/Diogo/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:200:32: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      _imageStream.addListener(_handleImageChanged);
                               ^
file:///C:/Users/Diogo/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:210:34: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    _imageStream?.removeListener(_handleImageChanged);
                                 ^
file:///C:/Users/Diogo/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:465:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/Flutter/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
Compiler failed on C:\Users\Diogo\AndroidStudioProjects\qwe\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 647

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugandroid-arm'.
> Process 'command 'C:\Flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by tupez** [comment]
Same error here.
I haven't the exactly same messages. 
But the origen appears be the same: the source of the packages added to project.

**Comment by kamrancr7** [comment]
same issue

**Comment by kamrancr7** [comment]
> same issue

well changing to stable channel solved my issue.
For how to change channel see the following link 
[https://stackoverflow.com/questions/51586259/which-channel-do-i-use-in-flutter-sdk](url)

**Comment by ppyupp** [comment]
same issue...

**Comment by stephensamonte** [comment]
I don't quite understand what this problem. 

But, the issue went away for me after switching flutter channels to dev and then back to the master channel. This can be done with the following commands: 
```
$ flutter channel dev
$ flutter channel master
```

**Comment by spiderman20084** [comment]
I'm already on the stable channel and i keep getting this

**Comment by spiderman20084** [comment]
this is so frustrating

**Comment by GuilhermeVendramini** [comment]
Same problem

**Comment by WD-J** [comment]
Saaame error, my dudes

**Comment by adlanarifzr** [comment]
Get same error after update as well

**Comment by BeDaut** [comment]
Same issue on stable channel

**Comment by spiderman20084** [comment]
A temporary fix downgrade Flushbar all the way down to version ^0.8.0

**Comment by mrserfr** [comment]
From changelog of Flushbar 1.6.0:

"
[1.6.0] - 2019-31-05
breaking change this fixes The method 'detach' isn't defined for the class 'FocusScopeNode'
To use this version you will need Flutter 1.6, which in currently in the beta channel
If you need to use Flutter Stable channel, stay in version 1.5.3 (install it using flushbar: '1.5.3') while flutter 1.6 is in beta.
Package health score suffered a hit because it uses Flutter stable channel. It will go back to normal once 1.6 is released
"

So you can use version 1.5.3 instead of change stable -> beta

**Comment by Lizhooh** [comment]
How to solve?
`flutter channel stable` 
Still getting the error

**Comment by BeDaut** [comment]
@Lizhooh 

if your error message about missing flushbar, just downgrade it to 1.5.3, after flutter update some packages just broke, try to change versions for "missing" packages

**Comment by enzoftware** [comment]
@muss01 i found a simple solution just casting the function like this :

```stream.addListener(ImageStreamListener(imageListener));```
```stream.removeListener(ImageStreamListener(imageListener));```

Here is my ```flutter doctor```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.2, on Mac OS X 10.14.5 18F132, locale en-PE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.36.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

Hope this could help someone

**Comment by brenoprata10** [comment]
Same here :(

**Comment by guit4eva** [comment]
Upgrading photo_view to 0.4.0 fixed it for me

**Comment by Wycers** [comment]
> @muss01 i found a simple solution just casting the function like this :
> 
> `stream.addListener(ImageStreamListener(imageListener));`
> `stream.removeListener(ImageStreamListener(imageListener));`
> 
> Here is my `flutter doctor`
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.7.8+hotfix.2, on Mac OS X 10.14.5 18F132, locale en-PE)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
> [✓] iOS tools - develop for iOS devices
> [✓] Android Studio (version 3.4)
> [!] IntelliJ IDEA Ultimate Edition (version 2019.1)
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
> [✓] VS Code (version 1.36.0)
> [✓] Connected device (1 available)
> 
> ! Doctor found issues in 1 category.
> ```
> 
> Hope this could help someone

Works for me!

**Comment by antoniokarlos** [comment]
Hey guys, 

Where to set this command:

stream.addListener(ImageStreamListener(imageListener));
stream.removeListener(ImageStreamListener(imageListener));

Same problem here!

**Comment by guit4eva** [comment]
> Hey guys,
> 
> Where to set this command:
> 
> stream.addListener(ImageStreamListener(imageListener));
> stream.removeListener(ImageStreamListener(imageListener));
> 
> Same problem here!

This fixes it: https://github.com/flutter/flutter/issues/33827#issuecomment-510019328

**Comment by carta1** [comment]
Had this issue as well. Solved by going to a previous version of flutter using this command on my terminal:
flutter version v1.6.0

this command should downgrade your flutter version, the version you go back to is your decision, hope it helps!

**Comment by mamtach** [comment]
Launching lib\main_dev.dart on SM A520F in debug mode...
[{"event":"app.progress","params":{"appId":"b4296039-9034-4bc0-8c1d-e28057ae25cd","id":"0","progressId":null,"message":"Initializing gradle..."}}]Initializing gradle...

Resolving dependencies...
[{"event":"app.progress","params":{"appId":"b4296039-9034-4bc0-8c1d-e28057ae25cd","id":"2","progressId":null,"message":"Running Gradle task 'assembleDebug'..."}}]Running Gradle task 'assembleDebug'...

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
file:///C:/Users/USERNAME/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/photo_view-0.3.3/lib/photo_view.dart:380:24: Error: The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Users/USERNAME/flutter_windows_v1.5.4-hotfix.2-stable/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Users/USERNAME/flutter_windows_v1.5.4-hotfix.2-stable/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    stream.addListener(listener);
                       ^
file:///C:/Users/USERNAME/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/photo_view-0.3.3/lib/photo_view.dart:382:29: Error: The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Users/USERNAME/flutter_windows_v1.5.4-hotfix.2-stable/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Users/USERNAME/flutter_windows_v1.5.4-hotfix.2-stable/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      stream.removeListener(listener);
                            ^
file:///C:/Users/USERNAME/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/cached_network_image-0.7.0/lib/src/cached_network_image_provider.dart:46:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/Users/USERNAME/flutter_windows_v1.5.4-hotfix.2-stable/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
Compiler failed on C:\Users\USERNAME\IdeaProjects\findeflutter\lib\main_dev.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\USERNAME\flutter_windows_v1.5.4-hotfix.2-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 665

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugArm64'.
> Process 'command 'C:\Users\USERNAME\flutter_windows_v1.5.4-hotfix.2-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Finished with error: Gradle task assembleDebug failed with exit code 1

--------------------------------------

I am getting same error and tried all the related options, cleaned cache, still not able to fix this issue.
Please help me.

**Comment by Hipheckts** [comment]
Please, how do I solve this. I have tried all I know and can find on the internet??? I'm on  Flutter: 1.7.8+hotfix.3

**Comment by dhsont** [comment]
> Please, how do I solve this. I have tried all I know and can find on the internet??? I'm on Flutter: 1.7.8+hotfix.3

@Hipheckts 

Open file where you are getting error (your plugin file) 
if you are getting error for zoomable Image package open following file
```
C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\zoomable_image-1.3.1\lib\src\zoomable_image.dart
```

look for
```
_imageStream.addListener(_handleImageLoaded);
_imageStream.removeListener(_handleImageLoaded);
```
and replace it with
```
_imageStream.addListener(ImageStreamListener(_handleImageLoaded));
_imageStream.removeListener(ImageStreamListener(_handleImageLoaded));
```
it is applicable to other packages also.

**Comment by mamtach** [comment]
> * photo_view and cached_network_image
My issue is resolved, it was due to the old versions of photo_view and cached_network_image in pubspec.yaml, once I upgraded it to higher versions, it was all good.

**Comment by atazifor** [comment]
In pubspec, I upgraded photo_view to 0.4.2 and flutter_image_compress to 0.6.3. Now It's all working for me

**Comment by BogdanPolitic** [comment]
I solved it simply by running flutter upgrade.

**Comment by zhaoqiyin** [comment]
@dhsont 
It solved my problem, thank you

**Comment by rowild** [comment]
But this cannot be the real solution for the Flutter framework. I follow this tutorial: 
```
https://dragosholban.com/2019/02/16/building-a-puzzle-game-using-flutter/#comment-1354
```
and get the error message as above. It should not be a requirement to change files of the framework, they will be overwritten again. So, please, Flutter team: any chance you could fix that problem in the source code?

And could the original poster please re-open this issue? Thanks!

**Comment by lesliearkorful** [comment]
After casting the function to ImageStreamListener, is anyone having app crashes when continuously using gestures on the image for some time?

**Comment by arifai** [comment]
Yeah, same issue.

**Comment by kamrancr7** [comment]
After upgrade flutter then again facing the same issue, also changed the channel to stable but issue is still persisting.

**error: The argument type 'Null Function(dynamic, dynamic)' can't be assigned to the parameter type 'ImageStreamListener'. (argument_type_not_assignable at [iamflexi_app] lib\homepage_components\CategoryDetail.dart:46)**

**Comment by fstrazzante** [comment]
Same issue here.

Resolved downgrading flutter_map before their upgrade of cached_network_image ^1.1.0 . 
So with flutter_map: 0.7.0+2 I don't get the error

**Comment by rowild** [comment]
@kamrancr7 @fstrazzante Checkout this post:
https://stackoverflow.com/questions/44665955/how-do-i-determine-the-width-and-height-of-an-image-in-flutter
and look carefully, where the new "ImageStreamListener" widget that now wraps the "ImageInfo" widget is placed.
Maybe that helps?

**Comment by mateusdevelopes** [comment]
> The issue went away for me after switching flutter channels to stable. This can be done with the following commands:
> 
> ```
> $ flutter channel stable
> ```
> 
> Also make sure flutter is upgraded by running:
> 
> ```
> $ flutter upgrade
> ```

This solve my problem, I just do the same thing and restart my IDE! 
Thx!

**Comment by aamirpadder** [comment]
Use command **flutter channel** to check your current channel
Switch to the **stable** channel in case you are on some other channel by the below command **flutter channel stable**
then use command **flutter upgrade**
This will work for sure
