### ISSUE TITLE
Version Issue 

### ISSUE THREAD

**Issue by momoDragon** [flutter/flutter#33820]
* What went wrong:
Could not determine the dependencies of task ':firebase_core:compileDebugRenderscript'.
> The library com.google.firebase:firebase-iid is being requested by various other libraries at [[18.0.0,18.0.0]], but resolves to 17.1.2. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

  google_maps_flutter: 0.5.7
  firebase_auth: 0.11.1+5
  cloud_firestore: 0.12.1
  firebase_messaging: 5.0.2
  firebase_storage: 3.0.0
  cloud_functions: 0.4.0
  google_sign_in: 4.0.2
  firebase_core: 0.4.0+3

**Comment by momoDragon** [comment]
it works when i remove firebase messaging, it seems that its not compatible.

**Comment by fpbouchard** [comment]
I have the same issue. I need firebase messaging, what is the proposed solution?

**Comment by JmeHsieh** [comment]
Removing `implementation 'com.google.firebase:firebase-core:17.0.0'` 
from `<project>/android/app/build.gradle` works for me.

According to PR https://github.com/flutter/plugins/pull/1766, and the flutter firebase_messaging code [example](https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/example/android/app/build.gradle#L56), they neither have this dependency.

I guess the FCM Assistant isn't all correct for flutter project, at least not for android under flutter.
Here's what FCM Assistant shows for android setup:
![Screen Shot 2019-07-02 at 6 25 55 PM](https://user-images.githubusercontent.com/537814/60506296-20f10680-9cf8-11e9-9a3f-c92a60ba1537.png)

It probably has something related to #33581 as well.

**Comment by momoDragon** [comment]
All of the packages are compatible as of now

**Comment by momoDragon** [comment]
Also as of now ensure the dependencies versions

https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/example/android/build.gradle

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath 'com.google.gms:google-services:4.2.0'
    }
