### ISSUE TITLE
The flutter mixed development layout is not displayed

### ISSUE THREAD

**Issue by liangxiaotao** [flutter/flutter#33821]
I'm going to put Flutter in the Android native scrollview and set the warp_content to not show up. Can someone tell me why?
 Layout:

   `<ScrollView 
     android:layout_width="match_parent"
     android:layout_height="match_parent"
     android:orientation="vertical"
     tools:context=".HomeActivity">
  <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:id="@+id/ll">
 </FrameLayout>
</ScrollView>`

code：
`FrameLayout frameLayout = findViewById(R.id.ll);
FlutterView flutterView = Flutter.createView(this, getLifecycle(), "route1"); FrameLayout.LayoutParams params = new 
FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
frameLayout.addView(flutterView, params);`

**Comment by mikhail-tokarev** [comment]
Hi @liangxiaotao 
are you still experiencing this issue with the latest version of Flutter?
If so please reply attaching your `flutter doctor -v`

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
