### ISSUE TITLE
App crash when deleting the password in TextFormField with initial text

### ISSUE THREAD

**Issue by pakyo-pan** [flutter/flutter#33829]
it only crashes when you `flutter run` (android only).
I don't know what will happen on the Android emulator, but it will happen on my real Android device.
1. using the code samples below
2. `flutter run` (not `hot restart`)
3. delete the password and it will crash
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Flutter Demo Home Page'),
        ),
        body: Center(
          child: TextFormField(
              controller: TextEditingController(text: 'aaaa'),
              decoration: const InputDecoration(
                hintText: "设置您的密码",
                labelText: "密码",
              ),
              maxLength: 16,
              obscureText: true,
              keyboardType: TextInputType.text,
              focusNode: FocusNode(),
              textInputAction: TextInputAction.next,
              validator: (value) {
                return null;
              },
              onFieldSubmitted: (value) {}),
        ),
      ),
    );
  }
}
```

flutter doctor -v
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.13.6 17G7024, locale zh-Hans-CN)
    • Flutter version 1.6.3 at /Users/pakyo/Work/_sdk/flutter
    • Framework revision bc7bc94083 (12 days ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/pakyo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/pakyo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • EVA DL00 • B2T7N16705000926 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by justinmc** [comment]
This should be fixed with https://github.com/flutter/engine/pull/9322

Similar to https://github.com/flutter/flutter/issues/33642

@pakyo-pan Let me know if you still see this crash on master!
