### ISSUE TITLE
"FAB per tab" missing frames when animating FAB

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3383]
Open the gallery app, open Demos, and select "floating action buttons". Swipe between tabs, and watch the FAB animate in.

Tested on a Nexus 5, running Android 6.0

![screenshot_20160418-140713](https://cloud.githubusercontent.com/assets/5479/14619974/29580694-056f-11e6-951c-b0a73414acd4.png)

**Comment by abarth** [comment]
I've seen this anecdotally as well.  /me will investigate.

**Comment by abarth** [comment]
Also, the ink response in the FAB is janky.

**Comment by abarth** [comment]
Note: This screenshot is from slow mode, but I think I've see it in production mode as well.

**Comment by sethladd** [comment]
Yeah, sorry about leaving Slow Mode on by accident :(

**Comment by chinmaygarde** [comment]
Checked mode should not affect rasterizer time. Besides, I observed the same on precompiled mode on iOS. Took a capture in the OpenGLES frame debugger. A large chunk was being rendered offscreen with most of the being spent in two fragment shaders.

**Comment by abarth** [comment]
Something pathological is going on in the rasterization phase:

![tabs-fab](https://cloud.githubusercontent.com/assets/112007/14791246/e3a7fdf6-0ac9-11e6-8412-81432267e8f1.png)

**Comment by abarth** [comment]
The problem is that Skia is creating new blur kernels on every frame because we're scaling with a matrix that's novel each time due to floating point precision.  The blur kernels are n^2 to create.

**Comment by abarth** [comment]
Filed https://bugs.chromium.org/p/skia/issues/detail?id=5224 for the Skia issue.

**Comment by sethladd** [comment]
Thanks for tracking it down!

**Comment by eseidelGoogle** [comment]
Should we close this @abarth?

**Comment by abarth** [comment]
Yep.  The Skia folks fixenated it.

**Comment by sethladd** [comment]
Thanks for the help!
