### ISSUE TITLE
TextField widget is using a high cpu on iOS compared to native one

### ISSUE THREAD

**Issue by monajafi** [flutter/flutter#33833]
While TextField is focused and soft keyboard is up in iOS simulator the backboardd daemon 
shows using a high cpu in activity monitor. I've compared the behaviour with native iOS:
 In native TextField when I stopped typing the backboardd daemon cpu usage decreases a lot but in flutter cpu usage remains very high even when I was not typing anything.

**Comment by mhstoller** [comment]
Are there any updates on this? It's such a significant problem that when developing on my MacBook Pro the battery life is cut in half while I'm developing/testing apps with TextFields. The TextField(s) being displayed uses ~100% CPU, and having one in focus uses over 200% on a 2018 MacBook Pro 15" with the 2.6 GHz i7, which is insane...

**Comment by GiacomoPignoni** [comment]
I have the same problem, when I run some app with TextField, CPU of my MacBook Pro 13 2017 go 100% usage

**Comment by murilosandiego** [comment]
I have the same problem on my MacBook Pro 2014.

**Comment by mcoolidge** [comment]
Same here

**Comment by legarland** [comment]
Same issue here. Dev Tools performance overlay shows continuous cpu usage as well while the soft keyboard is up.

**Comment by liyuqian** [comment]
Can you please confirm if this issue also happens on real iOS devices, or if this is simulator-only? CC @GaryQian to see if there's any quick thought as I believe Gary has looked into some text edit performance issues recently.

**Comment by flutteradv** [comment]
I don't have iOS device please somebody test this on device

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/pull/46720 This may help with the performance. The caching of the caret was incorrect and was being recomputed.

**Comment by dakt** [comment]
Can confirm the same. When in focus, CPU usage gets around 50%

**Comment by GaryQian** [comment]
We have recently landed #46720 which address one cause of abnormal CPU usage.

Can someone confirm whether this change has helped/if the CPU usage is still high. The change is available on master/dev channel as of now.

**Comment by csells** [comment]
@monajafi can you confirm that this still happens on the master channel? We'd like to know where #46720 fixes the problem. Thanks.

**Comment by zhjuncai** [comment]
I'm still having high CUP when TextField is showing. 

flutter doctor 

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.2 19C57,
    locale en-CN)
```

**Comment by liyuqian** [comment]
@zhjuncai : the stable channel Flutter (v1.12.13+hotfix.7) doesn't have the fix (https://github.com/flutter/flutter/pull/46720) yet. Can you try to switch to the master channel, and see if that fixes the high CPU usage? If not, can you please attach `flutter doctor` again?

**Comment by dakt** [comment]
How is this still a thing? It's really annoying. My laptop is draining battery like crazy when working on forms.

Please fix this
