### ISSUE TITLE
Is there anyway to flutter build static framework？

### ISSUE THREAD

**Issue by shenyuexin** [flutter/flutter#33835]
flutter.framework & static App.framework are dynamic framework, I want to import static flutter.framework & static App.framework to my project, is it possible?

**Comment by stuartmorgan** [comment]
You would currently need to fork the engine repository to add static library targets, and you wouldn't be able the Flutter tooling or templates with the result since they expect the framework to exist.

Can you explain why you want to do this?

**Comment by shenyuexin** [comment]
> You would currently need to fork the engine repository to add static library targets, and you wouldn't be able the Flutter tooling or templates with the result since they expect the framework to exist.
> 
> Can you explain why you want to do this?

Our project is made up of two dynamic framework, all module are inside these two dynamic framework by use cocoapods.  After I add  the App.framework and Flutter.framework into the dynamic framework, when the app start, it crash and log 'dyld: Library not loaded: @rpath/Flutter.framework/Flutter'.

**Comment by stuartmorgan** [comment]
To make sure I'm understanding correctly: you're distributing a framework via CocoaPods that uses Flutter internally? If so, is this a public pod, or a private pod?

If it's public, statically linking Flutter would be highly problematic: you'd prevent anyone using your framework from using Flutter themselves, as it would cause undefined behavior at runtime due to having two different implementations of the ObjC classes.

If it's private, couldn't you just also have a private Pod that includes the prebuilt Flutter frameworks, and have it as a dependency?

**Comment by shenyuexin** [comment]
> To make sure I'm understanding correctly: you're distributing a framework via CocoaPods that uses Flutter internally? If so, is this a public pod, or a private pod?
> 
> If it's public, statically linking Flutter would be highly problematic: you'd prevent anyone using your framework from using Flutter themselves, as it would cause undefined behavior at runtime due to having two different implementations of the ObjC classes.
> 
> If it's private, couldn't you just also have a private Pod that includes the prebuilt Flutter frameworks, and have it as a dependency?

 not excatly.  Every module of my project is a private pod, and all these modules finially will be inside a dynamic framework 'base.framework', then my project just import base.framework. now the problem is  flutter.framework is a dynamic framework inside the dynamic framework base.framework cause the  runtime error 'dyld: Library not loaded: @rpath/Flutter.framework/Flutter'.
let Flutter.framework&App.framework be a independent part, not into base.framework can fix this error.   but it will change current project's architecture, so I wonder is there any way to get a static Flutter.framework & App.framework?

**Comment by stuartmorgan** [comment]
As I said, you could theoretically fork the engine and add static build rules, but that would be a lot of work. There's currently no support for building them as static libraries, and no plans to support that.

For your use case, you should just use `LD_RUNPATH_SEARCH_PATHS` to allow the application to find and load the sub-bundled frameworks.

**Comment by shenyuexin** [comment]
> As I said, you could theoretically fork the engine and add static build rules, but that would be a lot of work. There's currently no support for building them as static libraries, and no plans to support that.
> 
> For your use case, you should just use `LD_RUNPATH_SEARCH_PATHS` to allow the application to find and load the sub-bundled frameworks.

Thanks a lot.
