### ISSUE TITLE
add device os version to analytics usage

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#33844]
## Use case

Developers would like to be able to get statistics on what versions of devices flutter users are testing on.

- There is a "sessions by device"/device report that we look to not be utilizing

**Comment by sjindel-google** [comment]
It would also be helpful if we could break it down by debug/release mode.

**Comment by zanderso** [comment]
@sjindel-google The device os version would probably be per session, whereas during a session a developer may do both debug and release runs, so I don't think it makes sense to club these two variables together from the beginning. OTOH, the analytics tool allows you to analyses like you're probably thinking of.
