### ISSUE TITLE
[Flutter][iOS] TextField lost their keyboard focus

### ISSUE THREAD

**Issue by quangthang225** [flutter/flutter#33843]
I try create a text field but it lost its keyboard focus in iOS, in Android it is OK.
Here are my code used:
```dart
import 'package:flutter/material.dart';
void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context){
    return MaterialApp(
      title: 'Focus Node App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Focus Node App'),
        ),
        body: FocusNodeApp(),
      ),
    );
  }
}

class FocusNodeApp extends StatefulWidget {
  @override
  FocusNoteAppState createState() => FocusNoteAppState();
}

class FocusNoteAppState extends State<FocusNodeApp> {
  @override
  Widget build(BuildContext context){
    return Padding(
      padding: EdgeInsets.all(16),
      child: Column(
        children: <Widget>[
          TextField(
            decoration: InputDecoration(
              hintText: 'This is the first text field',
            ),
          ),
          TextField(
            decoration: InputDecoration(
              hintText: 'This is the second text field',
            ),
          )
        ],
      ),
    );
  }
}
```
And this is my Flutter Doctor result:
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.13.6 17G5019, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/khanhnt748/Documents/Devtools/flutter
    • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/khanhnt748/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone XR • 76CE5AE4-7EB9-4F42-9253-5C2EA21CF809 • ios • iOS 12.1 (simulator)

! Doctor found issues in 1 category.
```
Could someone help me check it?
Thank you!

**Comment by caseyahenson** [comment]
I've been struggling with this issue for some time now as well. Something like this should work as a patch until a real solution is found:

`import 'package:flutter/material.dart';
void main() => runApp(TestKeyboardFocus());
class TestKeyboardFocus extends StatelessWidget {
  @override
  Widget build(BuildContext context){
    return MaterialApp(
      title: 'Test Keyboard Focus',
      home: Scaffold(
        resizeToAvoidBottomPadding: true,
        resizeToAvoidBottomInset: true,
        appBar: AppBar(
            automaticallyImplyLeading: true,
            title: Text('Test Keyboard Focus'),
            leading: IconButton(icon: Icon(Icons.close),
              onPressed: () {
                Navigator.pop(context);
              },
            )
        ),
        body: FocusNodeApp(),
      ),
    );
  }
}

class FocusNodeApp extends StatefulWidget {
  @override
  FocusNoteAppState createState() => FocusNoteAppState();
}

class FocusNoteAppState extends State<FocusNodeApp> {

  /*
  init focus node for each field
   */
  FocusNode firstFieldNode = FocusNode();
  FocusNode secondFieldNode = FocusNode();

  /*
  init focus status for each field
   */
  bool firstFieldFocused = true; //set true to autofocus
  bool secondFieldFocused = false;

  _resetFocusStates() {
    this.setState(() {
      firstFieldFocused = false;
      secondFieldFocused = false;
    });
  }

  @override
  void initState() {
    super.initState();
    /*
    init listener for each field
     */
    firstFieldNode.addListener(() {
      if (firstFieldFocused) {
        FocusScope.of(context).requestFocus(firstFieldNode);
      }
    });
    secondFieldNode.addListener(() {
      if (secondFieldFocused) {
        FocusScope.of(context).requestFocus(secondFieldNode);
      }
    });
  }

  @override
  void dispose() {
    // Clean up the focus nodes when the Form is disposed.
    firstFieldNode.dispose();
    secondFieldNode.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context){

    return Padding(
      padding: EdgeInsets.all(16),
      child: Form(
        child: Column(
          children: <Widget>[
            TextFormField(
              focusNode: firstFieldNode,
              autofocus: true,
              decoration: InputDecoration(
                hintText: 'This is the first text field',
              ),
              onTap: () {
                _resetFocusStates();
                this.setState(() {
                  firstFieldFocused = true;
                });
              },
              onFieldSubmitted: (value){
                this.setState(() {
                  firstFieldFocused = false;
                });
                firstFieldNode.unfocus();
              }
            ),
            TextFormField(
              focusNode: secondFieldNode,
              autofocus: true,
              decoration: InputDecoration(
                hintText: 'This is the second text field',
              ),
              onTap: () {
                _resetFocusStates();
                this.setState(() {
                  secondFieldFocused = true;
                });
              },
              onFieldSubmitted: (value){
                this.setState(() {
                  secondFieldFocused = false;
                });
                secondFieldNode.unfocus();
              }
            ),
          ],
        ),
      ),
    );
  }
}`

**Comment by TahaTesser** [comment]
Hi @quangthang225 
I wasn't able to reproduce this issue

<details>
<summary>flutter doctor -v</summary>

```
  [✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.18.0 at /Users/taha/Code/flutter_dev
    • Framework revision 8f7327f83a (2 days ago), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.4 19E266
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.92
    • Web Server • web-server • web-javascript • Flutter Tools
• No issues found! 
```

</details>

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

Thank you
