### ISSUE TITLE
Batch canvas drawPath calls when possible

### ISSUE THREAD

**Issue by cmkweber** [flutter/flutter#33849]
When performing many calls to drawPath, the performance suffers. This is especially evident on lower end devices. The attached example demonstrates:

   1. Looping through paths and drawing using **Canvas.drawPath**
   2. Looping through paths and drawing using **Canvas.drawVertices**
   3. One batched draw using **Canvas.drawVertices**

It should be noted this demonstration creates almost the maximum amount of paths that could be drawn with one batch call (max vertex index 65,535). One could expand this demonstration to perform numerous drawVertices calls when the vertex index overflows.

Another thing to keep in mind is a facility to draw many paths in one call should allow the user to provide _n_ paints so each path can still be drawn with its own style - this may require creating a texture atlas that drawVertices can reference.

Finally, this optimization may only benefit an immutable collection of paths. For dynamically changing paths, the allocation and upload to the GPU of large vertex data each frame may become non-performant, but this could be verified through tests.

[main.zip](https://github.com/flutter/flutter/files/3253510/main.zip)

**Comment by Hixie** [comment]
cc @liyuqian @reed-at-google

**Comment by liyuqian** [comment]
@cmkweber : Is this a demonstration that one batched `drawVertices` is faster than calling `drawPath` or `drawVertices` many times? Is there anything that Flutter or Skia needs to do?

It seems to me that whether to batch the paths for a single `drawVertices` call should be decided by developers. It will be hard for Flutter or Skia to do that batching automatically because Flutter/Skia has no idea whether those paths are dynamic, and whether batching is worthwhile.

**Comment by reed-at-google** [comment]
drawVertices is very specialized -- it never antialiases, but it does allow
a different "localmatrix" for the shader on every triangle. Pretty
different than drawPath. I think its best to leave that choice to the dev.

**Comment by cmkweber** [comment]
@liyuqian - this issue was opened as a suggestion from @Hixie - see comment here:
   [https://github.com/flutter/engine/pull/8835#issuecomment-497434183](https://github.com/flutter/engine/pull/8835#issuecomment-497434183)

The issue raised in that PR is still a major issue for our app (ability to call Picture.toImage and get the result back synchronously), I probably need to open a separate issue for that.

@reed-at-google - I agree that this is a better choice left for the developer - one thing that could make it easier for the developer though is if they could get a triangulation from a Path object for use with drawVertices, but I don't think Skia exposes triangulation.

**Comment by reed-at-google** [comment]
Completely agree: a faster way to allow clients to create images (from
drawing somewhere) is very valuable.

**Comment by cmkweber** [comment]
I'm going to go ahead and close this as Impeller fully covers this by utilizing a tessellation stage.
