### ISSUE TITLE
Flutter.dev is down

### ISSUE THREAD

**Issue by f-lima** [flutter/flutter#33840]
Site can't be reached.

![Screen Shot 1](https://user-images.githubusercontent.com/14829317/58881610-e2dcd480-86b0-11e9-8dd9-76bdc0d1703c.png)

**Comment by marcelgarus** [comment]
Can't reproduce the error anymore, so I assume this issue can be closed now.

**Comment by kangwang1988** [comment]
Close this issue as the flutter.dev is working fine now.
