### ISSUE TITLE
Expose scenic Z bounds to framework

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#33853]
`Window` should know about max elevation.

**Comment by Hixie** [comment]
Scheduled for after https://github.com/flutter/flutter/issues/35831.

**Comment by dnfield** [comment]
https://github.com/flutter/engine/pull/10414 fixes this.

**Comment by dnfield** [comment]
This change actually was a bit simpler than I expected - I didn't realize until recently that someone had already done the work of getting it into the right place on the C++ side.
