### ISSUE TITLE
MediaQuery should know about Z bounds

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#33854]
`MediaQuery` should expose the max elevation reported to the `Window`.
~Blocked on https://github.com/flutter/flutter/issues/33853~

**Comment by Piinks** [comment]
Dependent on #33853.

**Comment by Piinks** [comment]
The change that resolved this issue was reverted in #37938.

**Comment by Piinks** [comment]
Blocked by https://fuchsia.atlassian.net/browse/FL-292
