### ISSUE TITLE
Drop-down buttons in Gallery bug, shows red screen

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3386]
![screenshot_20160418-141834](https://cloud.githubusercontent.com/assets/5479/14620244/8b6f4cba-0570-11e6-9735-4fc372cc9e6a.png)

On a Nexus 5, running a build from approximately 2pm on Monday (today).

**Comment by eseidelGoogle** [comment]
We should fix these by writing (simple) drive tests to touch these parts of code.  flutter.io/testing shows how, or I'm happy to give in-person demos.

**Comment by HansMuller** [comment]
This isn't a bug (anymore). 

I am writing some simple gallery smoke tests now.
