### ISSUE TITLE
"Reply already submitted" errors whenever using platform views on Android.

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#33866]
This regressed in flutter/engine#7847 fix is up for review in flutter/engine#9185.

Whenever platform views are used on Android that exception is logged(Android's `Log.e`):

```
06-04 12:01:05.997 11978 11978 E DartMessenger: Uncaught exception in binary message listener
06-04 12:01:05.997 11978 11978 E DartMessenger: java.lang.IllegalStateException: Reply already submitted
06-04 12:01:05.997 11978 11978 E DartMessenger: 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:126)
06-04 12:01:05.997 11978 11978 E DartMessenger: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:240)
06-04 12:01:05.997 11978 11978 E DartMessenger: 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:90)
06-04 12:01:05.997 11978 11978 E DartMessenger: 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:234)
06-04 12:01:05.997 11978 11978 E DartMessenger: 	at android.os.MessageQueue.nativePollOnce(Native Method)
06-04 12:01:05.997 11978 11978 E DartMessenger: 	at android.os.MessageQueue.next(MessageQueue.java:325)
06-04 12:01:05.997 11978 11978 E DartMessenger: 	at android.os.Looper.loop(Looper.java:142)
06-04 12:01:05.997 11978 11978 E DartMessenger: 	at android.app.ActivityThread.main(ActivityThread.java:6591)
06-04 12:01:05.997 11978 11978 E DartMessenger: 	at java.lang.reflect.Method.invoke(Native Method)
06-04 12:01:05.997 11978 11978 E DartMessenger: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
06-04 12:01:05.997 11978 11978 E DartMessenger: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)
06-04 12:01:06.002 11978 11978 E MethodChannel#flutter/platform_views: Failed to handle method call
06-04 12:01:06.002 11978 11978 E MethodChannel#flutter/platform_views: java.lang.IllegalStateException: Reply already submitted
06-04 12:01:06.002 11978 11978 E MethodChannel#flutter/platform_views: 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:126)
06-04 12:01:06.002 11978 11978 E MethodChannel#flutter/platform_views: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.notImplemented(MethodChannel.java:235)
06-04 12:01:06.002 11978 11978 E MethodChannel#flutter/platform_views: 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
06-04 12:01:06.002 11978 11978 E MethodChannel#flutter/platform_views: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
06-04 12:01:06.002 11978 11978 E MethodChannel#flutter/platform_views: 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:90)
06-04 12:01:06.002 11978 11978 E MethodChannel#flutter/platform_views: 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:234)
06-04 12:01:06.002 11978 11978 E MethodChannel#flutter/platform_views: 	at android.os.MessageQueue.nativePollOnce(Native Method)
06-04 12:01:06.002 11978 11978 E MethodChannel#flutter/platform_views: 	at android.os.MessageQueue.next(MessageQueue.java:325)
06-04 12:01:06.002 11978 11978 E MethodChannel#flutter/platform_views: 	at android.os.Looper.loop(Looper.java:142)
06-04 12:01:06.002 11978 11978 E MethodChannel#flutter/platform_views: 	at android.app.ActivityThread.main(ActivityThread.java:6591)
06-04 12:01:06.002 11978 11978 E MethodChannel#flutter/platform_views: 	at java.lang.reflect.Method.invoke(Native Method)
06-04 12:01:06.002 11978 11978 E MethodChannel#flutter/platform_views: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
06-04 12:01:06.002 11978 11978 E MethodChannel#flutter/platform_views: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)
```

**Comment by amirh** [comment]
This is fixed in https://github.com/flutter/engine/pull/9185 keeping the issue open until the engine is rolled(roller is currently blocked on a broken build).

**Comment by amirh** [comment]
Rolled in      * Return the current display metrics that are in effect for this resource 
     * object.  The returned object should be treated as read-only.

**Comment by amirh** [comment]
Note that the bug had a more severe implication than logging the error, when resizing a platform view, the result will be completed with `notImplemented` first which will throw in `RenderAndroidView._sizePlatformView` and will leave the render object in an inconsistent state.

**Comment by GervaisYO** [comment]
Hey,
is this fix merged in the flutter beta channel already?

**Comment by amirh** [comment]
The fix made it to the v1.7.2 release(beta is currently at v1.6.3)

**Comment by GervaisYO** [comment]
Any idea, when the fix will me merged to beta?

**Comment by amirh** [comment]
probably within a few weeks, more information on the roll process here: https://github.com/flutter/flutter/wiki/Release-process#rolling-the-beta-channel

**Comment by agueroveraalvaro** [comment]
Problems still 1.7.9 versión :(

**Comment by amirh** [comment]
@agueroveraalvaro can you share a minimal sample code that reproduces the issue?

**Comment by agueroveraalvaro** [comment]
@amirh Yes! look

          `new EventChannel(getFlutterView(), eventChannelStatus).setStreamHandler(
                    new EventChannel.StreamHandler() {
                        @Override
                        public void onListen(Object arguments, EventChannel.EventSink events)
                        {
                            eventSinkStatus = events;
                        }

                        @Override
                        public void onCancel(Object arguments) {

                        }
                    }
            );`

And I solved with this (try/catch)

        `new EventChannel(getFlutterView(), eventChannelStatus).setStreamHandler(
                    new EventChannel.StreamHandler() {
                        @Override
                        public void onListen(Object arguments, EventChannel.EventSink events)
                        {
                           try
                            {
                                eventSinkStatus = events;
                            }
                            catch (Exception e)
                            {
                                
                            }
                        }

                        @Override
                        public void onCancel(Object arguments) {

                        }
                    }
            );`

**Comment by deakjahn** [comment]
v1.9.1-hotfix.4, ditto. It could be reproduced by using flutter_pdfview and simply placing a PDF view in the middle of a page, I guess.
