### ISSUE TITLE
[web]: `webdev` command looks for `dart` command

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#33877]
I was following the instructions to run the hello_world example in [README.md](https://github.com/flutter/flutter_web/blob/master/README.md), but `webdev serve` in step 3 reported that it couldn't find the `dart` command. The instructions probably should let people know how to put the `dart` command on their path or how to install a standalone Dart SDK.

**Comment by yjbanov** [comment]
`webdev` is no longer used by Flutter for web. Please use `flutter run -d chrome`.
