### ISSUE TITLE
Gradle project does not define a task for the requested build

### ISSUE THREAD

**Issue by procoder10** [flutter/flutter#33870]
The Gradle project does not define a task suitable for the requested build.
The android/app/build.gradle file defines product flavors: development, production
You must specify a --flavor option to select one of them.
Finished with error: Gradle build aborted.

i'm stuck here and  no topic helped me at all 
thanks

**Comment by BondarenkoStas** [comment]
@procoder10 did you find a solution?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by jessetinell** [comment]
@BondarenkoStas 
What solved it for me was putting `--flavor` parameter before target file in my command.

 This does **NOT** work: 
`flutter build appbundle lib/main_production.dart --flavor production`

This works: 
`flutter build appbundle --flavor production lib/main_production.dart`

Might help someone out there :)
