### ISSUE TITLE
[iOS 13] add support for detecting device dark mode enabled

### ISSUE THREAD

**Issue by kenthinson** [flutter/flutter#33873]
[iOS 13] add support for detecting device system wide dark mode enabled.

**Comment by stuartmorgan** [comment]
@matthew-carroll

**Comment by bitsydarel** [comment]
Also please add darkTheme property to the CupertinoApp widget.

**Comment by nikhiljha** [comment]
I think a nice way to implement this would be to have a function that returns Brightness.dark. That way it’s easy to incorporate into most themes.

**Comment by bitsydarel** [comment]
Well we already have a working design for that, we specify the two theme and let the framework switch between theme when the dark mode is enabled or disabled.

**Comment by nikhiljha** [comment]
Oh, that's new. I thought that still had to be updated manually. Time to update my codebases! :)

**Comment by EliasDeuss** [comment]
This issue is also connected to this one #34441

**Comment by DSMan97** [comment]
Is already supported look 
![ios Flutter Darkmode](https://user-images.githubusercontent.com/34092854/65834249-77f77f00-e2d9-11e9-98e4-87be9b99e7b7.gif)

**Comment by GillesMontyne** [comment]
@DSMan97 
I can't send u a dm on stackoverflow but can you tell us on which branch you currently are & the implementation? 
Thx in advance :)

**Comment by DSMan97** [comment]
> @DSMan97
> I can't send u a dm on stackoverflow but can you tell us on which branch you currently are & the implementation?
> Thx in advance :)

Is not in any brach is already supported by flutter team, I don´t add anything to code just use the code properly

**Comment by DSMan97** [comment]
I use this `var darkMode = CupertinoTheme.brightnessOf(context);` 
That's all

**Comment by bitsydarel** [comment]
If I’m using the material app I don’t want to check the brightness myself, I want the framework to do it for me as it’s currently does for android.

the widget already have the darkTheme property.

I don’t want to change perfectly working code for workaround.

**Comment by DSMan97** [comment]
> If I’m using the material or Cupertino app widget I don’t want to check the brightness myself, I want the framework to do it for me as it’s currently does for android.
> 
> the material app widget already have the darkTheme property.
> 
> I don’t want to change perfectly working code for workaround.

You want to use darkmode widget property for ios13 is easy and is not a workaround check stackoverflow  https://stackoverflow.com/questions/57475630/detect-if-ios13-dark-mode-is-enabled-from-flutter-dart/58156366#58156366

**Comment by bitsydarel** [comment]
That’s useful if I want to do inline verification if darkmode is enabled and change the UI.

What I ideally want is to provide my two themes(light and dark) to widgetApp.

So that when the user enable dark mode my app is automatically updated so that in my build method I only have to do Theme.of(context) and receive the current theme.

**Comment by bitsydarel** [comment]
The cool thing is if the widget app handle it, you won’t have to change the background of the picker yourself, this will be taken care of by the dark theme you would have specify to use.

**Comment by kenthinson** [comment]
Closing as everything I need is working. Thanks flutter team.

**Comment by kgrigorian** [comment]
why is this closed as this doesnt have native support still?

**Comment by DSMan97** [comment]
> why is this closed as this doesnt have native support still?

Yes already have support look  https://stackoverflow.com/questions/57475630/detect-if-ios13-dark-mode-is-enabled-from-flutter-dart/58156366#58156366

**Comment by LongCatIsLooong** [comment]
There's still ongoing work around dark mode, but as of https://github.com/flutter/flutter/commit/ad940c7b4992a2d1b7869e25d5b6134725caebaa, `MediaQuery.platformBrightness` should be able to tell you whether the phone is in dark mode.

**Comment by ElderiedGlenvilleState2013** [comment]
> https://stackoverflow.com/questions/57475630/detect-if-ios13-dark-mode-is-enabled-from-flutter-dart/58156366#58156366

are their any good tutorials to add this to my app

**Comment by ElderiedGlenvilleState2013** [comment]
> > @DSMan97
> > I can't send u a dm on stackoverflow but can you tell us on which branch you currently are & the implementation?
> > Thx in advance :)
> 
> Is not in any brach is already supported by flutter team, I don´t add anything to code, just I use the code properly

what is the code and where can I find it
