### ISSUE TITLE
Very slow app re-foregrounding after backing out all the way to the OS home screen

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3387]
On my Nexus 5. Open the gallery, and then go into the app two levels deep. Then, hit the Android back button enough times to get back to the OS's main launch screen. Then, bring up the app switcher and select the Gallery app from the list of backgrounded apps. Tap the gallery app.

Expected: quick resume of the gallery app

Actual: black screen for a few seconds. Almost feels like a resume is slower than a cold start.

**Comment by sethladd** [comment]
cc @HansMuller

**Comment by sethladd** [comment]
I think this is related to https://github.com/flutter/flutter/issues/3244

**Comment by HansMuller** [comment]
This is a duplicate of #3244

**Comment by sethladd** [comment]
Closing as dupe.
