### ISSUE TITLE
Error importing some packages after migrating the app to androidx

### ISSUE THREAD

**Issue by MuriloRS** [flutter/flutter#33887]
Hello guys, I migrate my app to androidx today, there are some erros in 3 packages, how can i resolve this?

![errorPrint](https://user-images.githubusercontent.com/18061819/58921045-5a3f5200-870b-11e9-963e-65f11d6a2fb8.png)

**Comment by janmoppel** [comment]
Hello @MuriloRS !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by MuriloRS** [comment]
> Hello @MuriloRS !
> 
> Did you manage to solve the issue? Does the problem still persist in the latest stable version?

No, I create a new app and migrate manually.
