### ISSUE TITLE
Gallery, Item with Checklist is Red Render Error

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3389]
Open the gallery, go to components, then Menus, then choose "An item with a checklist menu".

![screenshot_20160418-143518](https://cloud.githubusercontent.com/assets/5479/14620696/06d10fb8-0573-11e6-83d7-0ab4a45138c8.png)

**Comment by HansMuller** [comment]
I am unable to reproduce this. Can you insert the flutter log output?

**Comment by sethladd** [comment]
It's now working in the latest master. Thanks for checking!
