### ISSUE TITLE
Track CPU/GPU/Energy usage in our performance benchmarks

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#33899]
Let's add CPU/GPU/Energy use percentage to all our Flutter driver performance tests. It will be a great addition to our current frame-build/rasterize-time metrics.

We've seen many developers tracking it, filing issues on it, and writing articles about it. It will help us address issues like power usage, performance cost not covered by frame build/rasterize phases, etc.

**Comment by dnfield** [comment]
We're doing this now in the Android firebase test.  We just don't have it reporting anywhere nice yet.

**Comment by liyuqian** [comment]
https://github.com/flutter/flutter/pull/39439 has been reverted due to:
- https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahFmbHV0dGVyLWRhc2hib2FyZHJYCxIJQ2hlY2tsaXN0IjhmbHV0dGVyL2ZsdXR0ZXIvMzkwZWY2MDk2MzkyNDQ1MGFlMDAyOGE4Y2FiZmE1OGY0MDExMTJlNAwLEgRUYXNrGICAoJ3LsNwJDA
- https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahFmbHV0dGVyLWRhc2hib2FyZHJYCxIJQ2hlY2tsaXN0IjhmbHV0dGVyL2ZsdXR0ZXIvNjdlMzVkNjEyZTdhMmEyYTQzMDZlMTRhNDIyNjYyMjIwNzQ1Mzg4NgwLEgRUYXNrGICAoK2Znq4LDA
- https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahFmbHV0dGVyLWRhc2hib2FyZHJYCxIJQ2hlY2tsaXN0IjhmbHV0dGVyL2ZsdXR0ZXIvYjlhMzRkZWM3ZWFiMzVhYmFlM2QyZTBiZTM3YTdkNzNmOWQ4YWNlYgwLEgRUYXNrGICAoM29ro4IDA
- https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahFmbHV0dGVyLWRhc2hib2FyZHJYCxIJQ2hlY2tsaXN0IjhmbHV0dGVyL2ZsdXR0ZXIvYWY5ZjQyNGQ1ZGI3Njk0YWQ4MDAwNmY5N2Q4NDAzNTAwZWNkOTk5MQwLEgRUYXNrGICAoK3qrOULDA
- https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahFmbHV0dGVyLWRhc2hib2FyZHJYCxIJQ2hlY2tsaXN0IjhmbHV0dGVyL2ZsdXR0ZXIvZTYyYzY4YzI0M2Q5MGYxZTUyMTY0ZGQxZjNhZTQ1NTNmZWNmMjhmNAwLEgRUYXNrGICAoJ23nr8JDA

Will investigate, fix, and reland.

**Comment by liyuqian** [comment]
https://github.com/flutter/flutter/pull/39439 is finally relanded in https://github.com/flutter/flutter/pull/41578 and now we have the CPU and GPU benchmarks in https://flutter-dashboard.appspot.com/benchmarks.html

**Comment by liyuqian** [comment]
This is currently blocked by https://github.com/flutter/flutter/issues/45435 on iOS. We'll also need to do some work to enable the measurement on Android.

**Comment by kf6gpe** [comment]
@liyuqian Blocking bug is closed. Should we get back to this now?

**Comment by liyuqian** [comment]
Yes, this is done for iOS. We discussed the Android side of work several days ago and concluded that no one has the bandwidth to tackle it in Q3. We'll revisit it in Q4 OKR planning.

**Comment by kf6gpe** [comment]
Downgrading to a P4 until we finish Q4 planning and know if this landed on the plate.

**Comment by liyuqian** [comment]
https://github.com/flutter/flutter/issues/61567 tracks the Android side of work. I'm going to close this and continue our future discussions in #61567
