### ISSUE TITLE
VersionCheckError during `flutter upgrade` on macOS 10.15 beta (Catalina)

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#33890]
Flutter is not currently supported on macOS 10.15, but adding this issue for awareness.

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter upgrade

## exception

VersionCheckError: VersionCheckError: Command exited with code -9: git log -n 1 --pretty=format:%ad --date=iso
Standard error: 

```
#0      _runSync (package:flutter_tools/src/version.dart:521:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:141:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:132:37)
#3      FlutterVersion.toString (package:flutter_tools/src/version.dart:109:99)
#4      UpgradeCommandRunner.updatePackages (package:flutter_tools/src/commands/upgrade.dart:190:32)
<asynchronous suspension>
#5      UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:90:11)
<asynchronous suspension>
#6      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:47:32)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#14     Future._complete (dart:async/future_impl.dart:473:7)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#16     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
encountered exception: VersionCheckError: Command exited with code -9: git log -n 1 --pretty=format:%ad --date=iso
Standard error: 

#0      _runSync (package:flutter_tools/src/version.dart:521:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:141:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:132:37)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:94:31)
#4      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:468:127)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:134:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:205:41)
<asynchronous suspension>
#7      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#14     _doctorText (package:flutter_tools/runner.dart:187:19)
<asynchronous suspension>
#15     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
<asynchronous suspension>
#16     _handleToolError (package:flutter_tools/runner.dart:120:33)
<asynchronous suspension>
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:64:20)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#24     runInContext (package:flutter_tools/src/context_runner.dart:54:24)
<asynchronous suspension>
#25     run (package:flutter_tools/runner.dart:51:10)
#26     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#27     main (file:///Users/timsneath/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

The log seems to complain about this line: `git log -n 1 --pretty=format:%ad --date=iso`, but the command here works from my terminal.

**Comment by jonahwilliams** [comment]
What version of `git` do you have?

**Comment by AppleEducate** [comment]
![IMG_0127](https://user-images.githubusercontent.com/31253215/58922830-b2298900-870a-11e9-90ec-fa5487918dd9.jpeg)
![IMG_0129](https://user-images.githubusercontent.com/31253215/58922831-b2298900-870a-11e9-982e-39576ebe39f0.jpeg)
![IMG_0130](https://user-images.githubusercontent.com/31253215/58922832-b2298900-870a-11e9-9769-1ed94873fabe.jpeg)
![IMG_0131](https://user-images.githubusercontent.com/31253215/58922833-b2c21f80-870a-11e9-8fdc-8d93c3f2521c.jpeg)
![IMG_0132](https://user-images.githubusercontent.com/31253215/58922834-b2c21f80-870a-11e9-8c8d-fafaf38bf8db.jpeg)
![IMG_0133](https://user-images.githubusercontent.com/31253215/58922835-b2c21f80-870a-11e9-8208-c2f3f3c13dff.jpeg)

**Comment by AppleEducate** [comment]
Also various build errors on 10.15

**Comment by stuartmorgan** [comment]
@AppleEducate Supporting Catalyst for iOS Flutter projects is completely unrelated to being able to run Flutter commands on 10.15.

**Comment by stuartmorgan** [comment]
I can't find the issue at the moment, but I know I've seen a bug about `git` failing after an OS update until you install command line tool support; this is likely a dup of that.

**Comment by kangwang1988** [comment]
@timsneath 
I'm using macos 10.15.
Though I've found several errors when running flutter with macos 10.15&ios13, however, this issue doesn't appear in myside.
It seems probably a git issue which may not related to 10.15.

**Comment by mclark4386** [comment]
did you install git from homebrew?

**Comment by rishab2113** [comment]
look at #33909 for solutions!

**Comment by timsneath** [comment]
@stuartmorgan The command 
```
git log -n 1 --pretty=format:%ad --date=iso
```
pipes to `less` on my machine. But 

```
echo `git log -n 1 --pretty=format:%ad --date=iso`
```
returns `0`.

Looking at my machine, I have two versions of `git` installed:

```bash
$ /usr/bin/git --version
git version 2.20.1 (Apple Git-117)
$ /usr/local/git/current/bin/git --version      
git version 2.19.0.605.g01d371f741-goog
```

The Google one is first on the path:
```bash
$ git --version      
git version 2.19.0.605.g01d371f741-goog
```

**Comment by stuartmorgan** [comment]
> echo `git log -n 1 --pretty=format:%ad --date=iso`
> returns a meaningful result (an ISO-formatted date) with an error code of 0.

The error code of that command is `echo`s error code though, not `git`'s.

We should probably investigate further offline.

**Comment by galvesribeiro** [comment]
I'm having other weird problems with Catalina as well. Most of the apps after the upgrade now request you access to do something. Then you need to go to Preferences and allow them on Security section. 

`flutter` cli was no different. Except that it is now ranging on the snapshot and I can't run it anymore... So VSCode don't work as well...

![image](https://user-images.githubusercontent.com/4714040/60046784-93ca0400-969e-11e9-917d-6ea6f3a6b6b8.png)

Click on Open Anyway doesn't do anything :(

Any clues?

Thanks!

**Comment by galvesribeiro** [comment]
okey... Found out tht the "Anywhere" option was removed from Preferences...

Just run `sudo spctl --master-disable` and you get it back.

Just in case anyone fall in the same pitfall...

**Comment by AppleEducate** [comment]
@galvesriberio what’s the official solution long term? Does flutter need to sign it?

**Comment by galvesribeiro** [comment]
I think so... Before Catalina, you could just click on "Anywhere" and use it... Now this options is hidden, and I would guess, will be removed on future OSes...

I still don't understand why flutter is deployed as a zip rather than an installer with multi-home updates (to support multiple SDK versions) just like .Net Core does...

**Comment by christopherfujino** [comment]
Hi @timsneath, was the original issue here resolved? It seems like there are two issues here, and I would like to track them separately.

**Comment by christopherfujino** [comment]
NOTE: I opened [36714](https://github.com/flutter/flutter/issues/36714) for the issue above with `kernel-service.dart.snapshot` not running on Catalina.

**Comment by timsneath** [comment]
It's still crashing on my machine -- I'll drop you a line tomorrow
afternoon because it might be unique to a Google configuration.

**Comment by christopherfujino** [comment]
@timsneath sounds good!

**Comment by christopherfujino** [comment]
Another (non-google) instance was [here](https://github.com/flutter/flutter/issues/36829).

**Comment by timsneath** [comment]
Just captured a fresh instance of this (crash report ID: 8ac6633e934ae3db)

Latest log attached.
[flutter_01.log](https://github.com/flutter/flutter/files/3429915/flutter_01.log)

**Comment by christopherfujino** [comment]
I also filed [a dart issue](https://github.com/dart-lang/sdk/issues/37662)

**Comment by Hixie** [comment]
@christopherfujino says he's got a new PR in the works for this.
