### ISSUE TITLE
podhelper.rb creates absolute Generated.xcconfig paths

### ISSUE THREAD

**Issue by athornz** [flutter/flutter#33897]
This may be specific to add2app.

Currently the podhelper.rb creates absolute paths for Generated.xcconfig paths in pod files.

E.g.

`#include "/Users/user/Code/myapp/.ios/Flutter/Generated.xcconfig"`

This makes it hard to work with multiple developers as these paths change each time `pod install` is run.

Is there a reason these can't be relative paths?

**Comment by athornz** [comment]
I believe this is also the cause of issues around opening Flutter iOS modules in AppCode: https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FOC-17593

@jmagman do you know if there is a restriction around these paths being absolute?

**Comment by jmagman** [comment]
> This may be specific to add2app.
> 
> Currently the podhelper.rb creates absolute paths for Generated.xcconfig paths in pod files.
> 
> E.g.
> 
> `#include "/Users/user/Code/myapp/.ios/Flutter/Generated.xcconfig"`
> 
> This makes it hard to work with multiple developers as these paths change each time `pod install` is run.
> 
> Is there a reason these can't be relative paths?

Generated.xcconfig shouldn't be checked into source control, so it shouldn't conflict with other developers or environments.  The top of the file says:
```
// This is a generated file; do not edit or check into version control.
```
Does removing the file from git and adding to your .gitignore fix the issue?

**Comment by athornz** [comment]
Thanks @jmagman yes that fixes the original issue and I think is unrelated to the AppCode issue. 

Ive opened another issue: https://github.com/flutter/flutter/issues/35417

**Comment by OPTJoker** [comment]
> > This may be specific to add2app.
> > Currently the podhelper.rb creates absolute paths for Generated.xcconfig paths in pod files.
> > E.g.
> > `#include "/Users/user/Code/myapp/.ios/Flutter/Generated.xcconfig"`
> > This makes it hard to work with multiple developers as these paths change each time `pod install` is run.
> > Is there a reason these can't be relative paths?
> 
> Generated.xcconfig shouldn't be checked into source control, so it shouldn't conflict with other developers or environments. The top of the file says:
> 
> ```
> // This is a generated file; do not edit or check into version control.
> ```
> 
> Does removing the file from git and adding to your .gitignore fix the issue?

Can flutter apply a convenient method（like: run 'flutter update' in project dir） to update Generated.xcconfig's environment path？
