### ISSUE TITLE
image_picker

### ISSUE THREAD

**Issue by a120476536** [flutter/flutter#33902]
Flutter image_picker Select more than 2M (have not tried specific values) pictures are not displayed Select 100K or so pictures no problem

**Comment by DSenanayake** [comment]
Need image picker for web.

**Comment by mikhail-tokarev** [comment]
Hi @a120476536 
are you still experiencing this issue with the latest version of Flutter?
If so please reply attaching your `flutter doctor -v`

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
