### ISSUE TITLE
[iOS 13] Support for Cupertino SF Symbols

### ISSUE THREAD

**Issue by rodydavis** [flutter/flutter#33916]
## Use case

1500 Native Cupertino Symbols announced at WWDC
https://developer.apple.com/design/human-interface-guidelines/sf-symbols/

## Proposal

Add to CupertinoIcons Class?

**Comment by AppleEducate** [comment]
<img width="782" alt="Screen Shot 2019-06-05 at 9 29 34 AM" src="https://user-images.githubusercontent.com/31253215/58960105-71fef080-8774-11e9-8287-bc16c50e62a8.png">

**Comment by kerberjg** [comment]
[This guide](https://stackoverflow.com/questions/56449218/how-to-use-sf-symbols-in-ios-12-and-below) seems like a good start.

We can just extract the TTF and map all the Unicode symbols that way.

If needed, this tool can be helpful to convert all of the symbols to SVG

**Comment by kerberjg** [comment]
UPDATE: all glyphs seem to be contained in SF Pro Display, and can be visualized with an app like Typeface, with all the Unicode values exposed

![image](https://user-images.githubusercontent.com/16939117/69536159-c2b21200-0f7d-11ea-9075-1dcb5545a7de.png)

**Comment by kerberjg** [comment]
UPDATE 2: seems actual SF Symbols glyphs start at `0x100000` but from this value on Flutter on iOS 13 (Simulator) renders them like this:

![image](https://user-images.githubusercontent.com/16939117/69537993-93050900-0f81-11ea-96a6-054c288afc3c.png)

**Comment by delef** [comment]
Is there progress?

**Comment by EliasDeuss** [comment]
@kerberjg How do you find the ```0x100000``` icon numbers? I just manually imported the font to my project.

**Comment by virskor** [comment]
https://github.com/virskor/flutter_sfsymbols

Hope this can help you guys.😊

**Comment by kerberjg** [comment]
@EliasDeuss I just took the font file mentioned in one of the links I posted, and opened it with Typeface, like shown in the screenshot 

@virskor This does seem helpful, thank you! Can you elaborate on how you obtained the font file in your library?

**Comment by virskor** [comment]
> @EliasDeuss I just took the font file mentioned in one of the links I posted, and opened it with Typeface, like shown in the screenshot
> 
> @virskor This does seem helpful, thank you! Can you elaborate on how you obtained the font file in your library?

I am just using font forge modified Framework7's icons. I am using this to simulate a sf symbol. Hope it can help. Thanks

**Comment by xster** [comment]
This is now available on master channel if you upgrade the cupertino_icons package to 1.0.0. It will roll to stable at some point in the next month. 

The list of available icons is at http://flutter.github.io/cupertino_icons.

**Comment by RyanRamchandar** [comment]
@xster simply adding 1.0.0 to pubspec on stable won't give access to the new icons?

**Comment by xster** [comment]
If you update to 1.0.0 on stable, many of the existing icon references will update to the new look, but you won't be able to access any of the new icons (unless you use RichText and reference their glyph codepoints in the icon font specifically which isn't ergonomic).

**Comment by Hannnes1** [comment]
Are all icons that are available in the SF Display Pro font supposed to be available in Flutter? I tried to to use the icon with the code U+1007BD (Heart with a bolt), but I can't find it. I tried to find it using the code as well, but I can't figure out how the codePoint in icons.dart relates to the code shown when hovering over an icon in the typeface app.
