### ISSUE TITLE
Google Maps Plugin Issue

### ISSUE THREAD

**Issue by GadepalliAditya1998** [flutter/flutter#33911]
Google Maps shows in a different color rather than normal in Redmi 6 Pro. Issue with the Android View somewhere. Colors are inverted only in Redmi 6 Pro. Please fix the issue or provide the way to fix it. It also leave some space on the top. 

![maps](https://user-images.githubusercontent.com/51157467/58950842-506e2b00-87ad-11e9-8a63-5361f67a030d.png)

**Comment by melvinsalas** [comment]
Are you using the lastest version of `google_maps_flutter`?
Can you provide the steps or code to reproduce?
And the `$ flutter doctor -v` log

**Comment by GadepalliAditya1998** [comment]
Yes it is the latest version. Infact initially I thought I was the plugin
issue, so I started writing my own plugin and found out the result to be
the same. This issue is seen in redmi mobiles and in addition to change of
map color, there is even a unwanted padding on the top of the map which is
being sent by the platform view( that is used by Google maps plugin to send
the native map from sdk to flutter).

**Comment by GadepalliAditya1998** [comment]
@melvinsalas Can you just try out the flutter google maps plugin with your available phones, if MI available. I faced the issue on MI 6 Pro. I will even post the flutter doctor logs in the comment.

**Comment by GadepalliAditya1998** [comment]
Hey @melvinsalas  I have got the issue fixed, as I used the existing issue thread and followed  the steps he did #28121 by updating the Android OS from MIYI 10.2 to 10.3 Android 9 Pie and got the issue fixed.

**Comment by melvinsalas** [comment]
@GadepalliAditya1998 It's a great news 🎉
Please close the issue and keep contributing on the community
