### ISSUE TITLE
The method 'tabLabel' wall called on null. Happen on some device

### ISSUE THREAD

**Issue by thoson-it** [flutter/flutter#33915]

**Comment by thoson-it** [comment]
![A884F54F-F514-42BB-AA02-E9783ED15CA0](https://user-images.githubusercontent.com/30921961/58958740-cb473e00-87cd-11e9-8e5e-0f4aa1bbda7f.jpg)
![1B2DF885-2699-4C2D-B1E2-A86B4E48A412](https://user-images.githubusercontent.com/30921961/58958754-d00bf200-87cd-11e9-8903-7b6bcf3222c9.jpg)

**Comment by thoson-it** [comment]
My device: Xperia XZ1 SOV36
It just happened on my phone, on other devices it did not happen.
![1B2DF885-2699-4C2D-B1E2-A86B4E48A412](https://user-images.githubusercontent.com/30921961/58958981-4872b300-87ce-11e9-994a-c19a925c001b.jpg)
![A884F54F-F514-42BB-AA02-E9783ED15CA0](https://user-images.githubusercontent.com/30921961/58958987-4a3c7680-87ce-11e9-949b-6eb3f14aa416.jpg)

**Comment by HansMuller** [comment]
This appears to be a localizations problem, maybe the device's locale doesn't match a supported locale. More about Flutter i18n here: https://flutter.dev/docs/development/accessibility-and-localization/internationalization.

If you can provide a small self-contained app that demonstrates the problem, we'll look into it.

**Comment by thoson-it** [comment]
@HansMuller thanks you, but I think this bug didn't relate to "flutter_localizations". Because of I didn't use it in my app.
This is the same issue [https://github.com/flutter/flutter/issues/16915](url)

**Comment by thoson-it** [comment]
Fixed:
Include this in MaterialApp:
`localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('en', 'US')
      ],`
