### ISSUE TITLE
Firestore Snapshot listener not receiving document changes

### ISSUE THREAD

**Issue by afnx** [flutter/flutter#33914]
I'm trying to listen changes from a collection. The code below loads the initial data, but never gets triggered when a document is updated. I already have another code without the `arrayContains` condition and it's working well. Could it be `arrayContains`, which interferes with stream updates?

## Reproduce

```dart
 final snapshots = _firestore.collection("posts")
          .where("category", arrayContains: 'technology')
          .orderBy("date", descending: true)
          .endBefore([date])
          .limit(10)
          .snapshots().
```

**Comment by afnx** [comment]
Here is the solution for people who have the same problem. It's about Indexes.

1. Open the database of your Firebase Console.
2. Go to the Indexes tab.
3. Click Add Index.
4. Add fields that you've been trying to listen.

It takes some time to create. After it is ready, you will be able to listen updates.

In addition to that, you don't have to create an index manually. You can get the direct link from the error message, which creates your index automatically. However, here is the trick. When I used `snapshots()`, I did not see the error message, but I was able to see it whenever I switch it to `getDocuments()`. So, use `getDocuments()` temporarily to get the direct link. You can change your code later. Hope that helps.

**Comment by gabrielrms-Inatel** [comment]
Thanks!

**Comment by kamleshwebtech** [comment]
There is no error / index url displaying in console of Vs-code editor. Kindly suggest what should I do? BTW how can we delete already created indexes on Firestore? 

BTW I have the same issue `.limit(1).snapshots().listen((event) {...` not working and not calling `listen` after adding new document / deleting existing document. Kindly share your suggestion. Thank you.

**Comment by afnx** [comment]
You can't get errors without setting an error handler when you use `snapshots()` method. See the following code to receive an error that contains a link to generate the required indexes:

```dart
FirebaseFirestore.instance
  .collection('users')
  .orderBy('age')
  .where("age", isGreaterThan: 30)
  .limit(10)
  .snapshots()
  .listen(
  (event) {
    print(event);
  },
  onError: (error) {
    print(error);
  },
);
```

### How to remove indexes 
Follow the instructions to remove an index:

1. Go to the Cloud Firestore section of the Firebase console.
2. Click the Indexes tab.
3. Hover over the index you want to delete and select Delete from the context menu.
4. Confirm that you want to delete it by clicking Delete from the alert.

[Please see the documentation for details.](https://firebase.google.com/docs/firestore/query-data/indexing)
