### ISSUE TITLE
Flutter TextField doesn't accept input from VIRTUAL_KEYBOARD on Android

### ISSUE THREAD

**Issue by adazh** [flutter/flutter#33925]
VIRTUAL_KEYBOARD is "a generic virtual keyboard with a full layout that can be used to synthesize key events." And in Espresso, we use this VIRTUAL_KEYBOARD API to send keyevents to editable UIs. For example, to perform a native typing text action on a TextField in Android, Espresso first taps on the TextField and then uses the VIRTUAL_KEYBOARD to send keyevents to the TextField.

However, Flutter currently filters out input from VIRTUAL_KEYBOARD. See https://github.com/flutter/engine/blob/369ba9ee5fdb5eb6d026335032a8469e53f2c6db/shell/platform/android/io/flutter/embedding/android/AndroidKeyProcessor.java#L33.

**Comment by adazh** [comment]
Cc a few folks involved in the discussion. @matthew-carroll @gspencergoog @tvolkert @goderbauer

**Comment by gspencergoog** [comment]
The bug linked when the code was moved was https://github.com/flutter/flutter/issues/28438, but as matt pointed out, he just moved the code from the original implementation.

It's not clear exactly what the original reason for the code that ignores the VIRTUAL_KEYBOARD  keys was, but it was added in flutter/engine#5324 by @slightfoot.  Maybe Simon has context?

We're talking about this clause, which was originally in `FlutterView.java` in the engine:
```dart
        if (event.getDeviceId() != KeyCharacterMap.VIRTUAL_KEYBOARD) {
            if (mLastInputConnection != null && mImm.isAcceptingText()) {
                mLastInputConnection.sendKeyEvent(event);
            }
        }
```

**Comment by slightfoot** [comment]
I remember writing this code and seem to remember it was in relation, to perhaps, circular events. The Android on-screen keyboard sends its events as Virtual and they have a different path of getting to the input connection. So, they send simulated hardware key events. So adding this code either stopped repeats or a circular event loop.

To be honest it was a long time ago and it's pretty vague at best, I should have commented it.. Apologies. I don't have time right this moment to check into this further. Hopefully my comments help.

**Comment by matthew-carroll** [comment]
@gspencergoog what do you think about us removing the if-statement and seeing if it causes a regression? Is that too risky?

**Comment by tvolkert** [comment]
That plan sgtm.  In general, if there are no tests that exercise code and show why it's there, it's liable to get cleaned up.

**Comment by adazh** [comment]
Changes are in. Closing this issue.
