### ISSUE TITLE
Windows ARM support

### ISSUE THREAD

**Issue by JakeSays** [flutter/flutter#33922]
I need to create an embedder for Windows IOT ARM. I have all the pieces in place except for an ARM build of the engine. Looking through the documentation and build files I cannot see that this configuration is supported.

Did I miss something? And if so, can I get some pointers on what it will take? My thinking is I should only have to tweak some GN[I] files and maybe some python to find the right compilers, etc.

**Comment by kenthinson** [comment]
@JakeSays should definitely be possible. Flutter runs on the Raspberry Pi after all.

I don't think windows arm is supported. Flutter x86-64 is still early days and beta not released. 

If I were you I would clone the repo then try and build it. See what errors pop up and go from there. Maybe if you have a specific compiler error then a Flutter Dev will be able to help you. Sounds like a neat project.

**Comment by mikhail-tokarev** [comment]
Hi @JakeSays 
please take a look to this issue
https://github.com/flutter/flutter/issues/7099
you can also find some resource in the [Flutter Community]( https://flutter.dev/community).

Closing, as this isn't an issue with Flutter itself,
if you disagree
please write in the comments and I will reopen it

**Comment by galvesribeiro** [comment]
@mikhail-tokarev FYI the community site points to a slack community that doesn't  exist anymore: https://fluttercommunity.dev/joinslack

**Comment by mikhail-tokarev** [comment]
You are right @galvesribeiro ,
Thank you for the notification

**Comment by JakeSays** [comment]
@mikhail-tokarev Issue #7099 is about the raspberry pi, not windows IOT arm support. But you're right it isn't a flutter issue. windows IOT places some dumb restrictions on arm instruction sets.
