### ISSUE TITLE
In App Purchase documentation

### ISSUE THREAD

**Issue by RobertBrunhage** [flutter/flutter#33968]
I believe that the documentation needs improvement in the [App Purchase plugin](https://pub.dev/packages/in_app_purchase). I know it's still in early stage but it's quite hard to test it if the documentation is lacking.

For example I want to implement a subscription but there is no clear way to do it. I can get it to display in the app but I have no clue what to do in the `purchaseUpdatedStream`

Would be great to have a step by step example on how to implement the different types of payments, especially subscription as that tends to be a bit more complicated.

Currently this is how my method looks for the stream:
```
void _listenToPurchaseUpdated(List<PurchaseDetails> purchaseDetailsList) {
    purchaseDetailsList.forEach(
      (PurchaseDetails purchaseDetails) async {
        if (purchaseDetails.status == PurchaseStatus.pending) {
          //showPendingUI();
          print('pending');
        } else {
          if (purchaseDetails.status == PurchaseStatus.error) {
            //handleError(purchaseDetails.error);
            print('error');
          } else if (purchaseDetails.status == PurchaseStatus.purchased) {
            bool valid = await _verifyPurchase(purchaseDetails);

            if (valid) {
              await RepositoryServicePurchase.setSubscribed(true);
            } else {
              await RepositoryServicePurchase.setSubscribed(false);
              //_handleInvalidPurchase(purchaseDetails);
              print('invalid');
            }
          }
          if (Platform.isIOS) {
            InAppPurchaseConnection.instance.completePurchase(purchaseDetails);
          } else if (Platform.isAndroid) {
            InAppPurchaseConnection.instance.consumePurchase(purchaseDetails);
          }
        }
      },
    );
  }
```

This is probably the one that I have the hardest time wrapping my head around. How do I verify it? Should I create a firebase https cloud function if so what is needed for the Android part and iOS part
```
  Future<bool> _verifyPurchase(PurchaseDetails purchaseDetails) {
    // IMPORTANT!! Always verify a purchase before delivering the product.
    // For the purpose of an example, we directly return true.
    final serverVerificationData = purchaseDetails.verificationData.serverVerificationData;
    if (Platform.isIOS) {
      return Future<bool>.value(true);
    } else {
      // Android
      return Future<bool>.value(true);
    }
  }
```

**Comment by monmonja** [comment]
not sure for firebase, but for other backend you can verify it with googleapis for android
https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/get or
https://developers.google.com/android-publisher/api-ref/purchases/products/get
its important to know that you might need to link google cloud console with playstore before you create an product/subscription, we cant seem to verify product/subscription that was created before linking
also using libraries from google for your language seems to work easier then oauth

for ios see https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html
use https://buy.itunes.apple.com/verifyReceipt or https://sandbox.itunes.apple.com/verifyReceipt
with json body of receipt-data and the value of serverVerificationData and get the password with
https://www.appypie.com/faqs/how-can-i-get-shared-secret-key-for-in-app-purchase

**Comment by RobertBrunhage** [comment]
Don't have much time but as soon as I get some time I will try it out. Thanks for the detailed answer!

**Comment by mikhail-tokarev** [comment]
Hi @RobertBrunhage 
are you still experiencing this issue with the latest version of Flutter?
If so please reply attaching your `flutter doctor -v`

**Comment by RobertBrunhage** [comment]
Started using RevenueCat instead so I don't have this issue anymore.

**Comment by mikhail-tokarev** [comment]
Thank you for your answer @RobertBrunhage 
I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it
