### ISSUE TITLE
Lost listview position when item is deleted

### ISSUE THREAD

**Issue by k4rolko** [flutter/flutter#33974]
Hello, I have an app, which have a database of favorite recipes and when items are displayed in listview and I delete one item the listview is scrolled up to the top.  It is peculiar because when I use the same page with the same code and I fetch items from API and then delete some items scroll position isn't lost. I tried comparing the lists of API data and database data they are the same. I don't know why it is happening, just a peculiar case.

**Comment by PsychoXIVI** [comment]
You try scroll it to the next or previous item after deleting the other item.

**Comment by k4rolko** [comment]
This is a solution, but I think there exists a better solution. When I am fetching from API everything works well.

**Comment by justinmc** [comment]
Can you provide a demo app that reproduces the problem?  Maybe using timers instead of a real API.  I'm not sure what would cause this of the top of my head.

**Comment by k4rolko** [comment]
Yes, I am going to provide an app but for now, I must fix some important problems, when it will be ok I will post it.

**Comment by justinmc** [comment]
Thanks, whenever you have time!  So far you are the only one to report this problem.

**Comment by k4rolko** [comment]
So, I fixed it. I am rebuilding UI using ValueListenableBuilder and it works perfectly. This peculiar error was probably caused by using StreamBuilder.

**Comment by justinmc** [comment]
Alright that's good news.  I'm going to close this, but if anyone runs into something similar and thinks it's a bug, please post and we can reopen.
