### ISSUE TITLE
`PaintStyle` for `Paint` of `sky_engine` 

### ISSUE THREAD

**Issue by AgainPsychoX** [flutter/flutter#33977]
## Use case

`Paint` class from `painting.dart` file of `sky_engine` is seems to missing constructor, but I see why: It would be quite useless. 

The problem I occurred is that I want to use `Paint` (or similar) class to describe how some thing would be drawn. In that case, I would love to use some const constructor, but since `Paint` works on underlying (byte) data, there is (likely) no easy way to have const constructor on it.

## Proposal

I propose some kind of `PaintStyle` class, which still having same fields as `Paint` (but rather as `final` variables) , could have the const constructor and some function like `toPaint` to create valid `Paint`.
The current `Paint` might become `PaintStyle` itself, but I suppose that would be a quite breaking change (since the vision of `PaintStyle` includes `final` fields).

I use for now this: https://gist.github.com/PsychoXIVI/e7402ed1c3e525d0b2b0a504cbc86a41

```dart
class LineChartPainter extends CustomPainter {
    // ...
    LineChartPainter({
        // ...
        PaintStyle horizontalLinesPaintStyle = const PaintStyle(color: Colors.grey),
        // ...
    }) {
        this.horizontalLinesPaint = horizontalLinesPaintStyle == null ? null : horizontalLinesPaintStyle.toPaint();
        // ...
    };
```

Of course, I see a little performance drawback - while using raw `Paint` there is no comparisons to make valid `Paint` in `toPaint`. 

Still people like me can use their own types, express more fields or make a Paint building process in some non-const object constructors or `build(context)` method. By the way, in my case the `PaintStyle`, it would be even more useful, since I could use some `const` constructed `PaintStyle` as default, and then allow user to use `null` as `horizontalLinesPaintStyle` to abort drawing the line.

Anyway, it is just a suggestion, thank for your time. 
  Regards.

**Comment by jonahwilliams** [comment]
The purpose of the paint object is for interop. Creating a const paint like api would be pointless as we'd still have to construct the real paint on every frame and copy things over
