### ISSUE TITLE
Build fails on `flutter.gradle` file repeatedly due to `ui.PlaceholderAlignment` not found

### ISSUE THREAD

**Issue by anantakrroy** [flutter/flutter#33971]
I recently upgraded Flutter to v1.7.2-pre.30 and Dart 2.3.2 . There is a recent commit on [text_painter.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/text_painter.dart) which has made some changes with regard to the PlaceholderAlignment. This has led to build failing repeatedly for a working code of mine before this upgrade. 

**Logs**

```
Compiler message:
file:///E:/Flutter/flutter/packages/flutter/lib/src/painting/text_painter.dart:61:9: Error: Type 'ui.PlaceHolderAlignment' not found.
  final ui.PlaceHolderAlignment alignment;
        ^^^^^^^^^^^^^^^^^^^^^^^
file:///E:/Flutter/flutter/packages/flutter/lib/src/painting/text_painter.dart:61:12: Error: 'PlaceHolderAlignment' isn't a type.
  final ui.PlaceHolderAlignment alignment;
           ^^^^^^^^^^^^^^^^^^^^
Compiler failed on E:\Flutter\FlutterDevelopment\easylist\lib/main.dart
FAILURE: Build failed with an exception.
* Where:
Script 'E:\Flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 648

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugandroid-arm'.
> Process 'command 'E:\Flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         3.6s
Gradle task assembleDebug failed with exit code 1
```

**Comment by justinmc** [comment]
It looks like that commit was reverted.  I think if you upgrade flutter again (assuming you are on the master channel) then it should work again.  Let me know if that doesn't work.

**Comment by anantakrroy** [comment]
@justinmc Please close this issue as the latest commit was indeed reverted. Running flutter upgrade and then running the code does not throw any above mentioned errors.

**Comment by justinmc** [comment]
Great!

**Comment by premtemp1** [comment]
I am getting the same error .. Just upgraded to 1.7.4 pre80... How do I fix. this issue

Getting the error ion VScode

**Comment by chanthuang** [comment]
Same error

**Comment by justinmc** [comment]
The commit was relanded so maybe that brought the error back https://github.com/flutter/flutter/commit/c2eaf8359d2cf951084e801d2c5d13ef12b8dd96#diff-f33d2b321b2d94f3ad59fb667ba846cc.

@GaryQian Any idea if this could be caused by your recent TextSpan work?

**Comment by TahaTesser** [comment]
Hi @justinmc 
Does this issue still exist? 
Thank you

**Comment by justinmc** [comment]
I haven't seen anything about it since my last comment. I'm in favor of closing it unless someone chimes in that it still exists.

**Comment by iapicca** [comment]
Thanks @justinmc,  closing the issue for now

Please don't hesitate to comment on the bug if you have any more information for us;
we will reopen it right away!
