### ISSUE TITLE
Is there a way to backup sqlite Database to Google Drive or Dropbox?

### ISSUE THREAD

**Issue by jv5000** [flutter/flutter#33975]
Hi, I've searched everywhere for a solution but I can find nothing that will back up my Users data that is stored in a sqlite database. 

Alternatively, is it possible to Migrate their data to Firebase and seemlessly move their data to Firestore with it's built in backup?

regards

Shaun

**Comment by tomalabaster** [comment]
Back up to users' own Google Drive or Dropbox? If so, look at this for Google Drive at least: https://stackoverflow.com/questions/52793359/how-to-integrate-google-drive-in-flutter-app

You'd have to write your own migration steps for migrating the data from SQLite on to Firestore.

**Comment by BondarenkoStas** [comment]
@jv5000 did you find a solution?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by praveen4030** [comment]
You can have a look at AutoBackup for Android. Just need to add a tag autoBackup true in maifest and boila!.
