### ISSUE TITLE
FocusNode.nextFocus() allows to focus nodes of TextField widgets that are disabled

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#33985]
1. Create an app that has 2 TextFields on the same page
2. The first TextField's input action should be set to InputAction.next and the second TextField's disabled property should be set to true.

The result will be the following:
The first TextField can receive focus by tapping inside it, and the second TextField does not. However, when focus is on the first TextField, the Next button on the keyboard will cause the second TextField to receive focus, which shouldn't happen.

It would also be great to have a way to know when a FocusNode can be focused _without_ receiving focus, so that the InputAction on the TextField could be easily updated between "next" and "done". Or better yet, the TextField widget could have a way to do this automatically.

**Comment by justinmc** [comment]
I can't get the second field to receive focus using the iOS simulator.  Is my code right?

![focus](https://user-images.githubusercontent.com/389558/59114088-40646180-88fb-11e9-8249-6b789c76a9aa.gif)

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Flutter demo'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextField(
                textInputAction: TextInputAction.next,
              ),
              TextField(
                enabled: false,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

@chunhtai Does your [read only text field](https://github.com/flutter/flutter/pull/32059) handle this sort of thing?

**Comment by dannyvalentesonos** [comment]
I was actually thinking about this last night, and I was wondering if it's maybe because we pass in our own FocusNode to the TextField. Should we not be creating and passing in a node if it's disabled? I would hope the TextField widget would handle detaching the node from the Focus tree should the widget become disabled..

**Comment by justinmc** [comment]
Ah I see, sorry for my bad example above.  Here is an updated example and gif.

I agree with you and say that it is a bug that you can focus a disable TextField using a FocusNode, especially that you can even enter text that way.  We should reexamine that for disabled and for readOnly fields.

In the meantime, you can probably work around this like you were thinking.  If you change the focusNode logic when the input becomes disabled then you should be able to recreate the desired behavior.  I know that's messy though, so hopefully we can fix this soon.

![focus2](https://user-images.githubusercontent.com/389558/59120611-b45a3600-890a-11e9-89d0-c31b846c5067.gif)


```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final FocusNode fnOne = FocusNode();
    final FocusNode fnTwo = FocusNode();

    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Flutter demo'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextFormField(
                textInputAction: TextInputAction.next,
                focusNode: fnOne,
                onFieldSubmitted: (term) {
                  fnOne.unfocus();
                  FocusScope.of(context).requestFocus(fnTwo);
                },
              ),
              TextFormField(
                focusNode: fnTwo,
                enabled: false,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by dannyvalentesonos** [comment]
awesome, thanks for checking @justinmc .
Problem with doing the workaround, we'd have to also manage the detachment of the node from the Node tree, right? I think that becomes complicated. 
If at least this bug could be fixed from within the TextField widget, then that would be the best thing, and we can wait for the right fix.

**Comment by justinmc** [comment]
I tried my hand at a quick workaround example, but I think I agree that this needs a closer look.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _enabled = true;

  void _toggleEnabled() {
    setState(() {
      _enabled = !_enabled;
    });
  }

  @override
  Widget build(BuildContext context) {
    final FocusNode fnOne = FocusNode();
    final FocusNode fnTwo = FocusNode();

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextFormField(
              textInputAction: _enabled ? TextInputAction.next : TextInputAction.done,
              focusNode: fnOne,
              onFieldSubmitted: (term) {
                fnOne.unfocus();
                if (_enabled) {
                  FocusScope.of(context).requestFocus(fnTwo);
                }
              },
            ),
            TextFormField(
              focusNode: fnTwo,
              enabled: _enabled,
              decoration: InputDecoration(
                labelText: _enabled ? 'enabled' : 'disabled',
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _toggleEnabled,
        tooltip: 'Toggle enabled/disabled',
        child: Icon(_enabled ? Icons.stop : Icons.play_arrow),
      ),
    );
  }
}
```

**Comment by nitin08bisht** [comment]
can we use focus on dropdown button

**Comment by gspencergoog** [comment]
@nitin08bisht, yes, `DropdownButton` has focus support.
