### ISSUE TITLE
Flutter Performance Issues When Running Android Emulators

### ISSUE THREAD

**Issue by azamsharp** [flutter/flutter#33983]
To best understand the issue check out this video: 
https://youtu.be/ZqQhYuqu-fY

I am running MacBook Pro 2017 8 GB RAM.

**Comment by BondarenkoStas** [comment]
@azamsharp thank you for report, but it doesn't contain any actionable information.

**Comment by azamsharp** [comment]
Action: Run Flutter on Android simulator and see your CPU performance comes to a halt.
