### ISSUE TITLE
how to open the drawer by use of left swipe like gmail in flutter?

### ISSUE THREAD

**Issue by Sudhanmanoharan** [flutter/flutter#33995]
I like to open the drawer by use of swipe like Gmail application in flutter
can u help how to do this?
:)

**Comment by Levi-Lesches** [comment]
Assuming you are using a Drawer in the Scaffold constructor, you should already be able to swipe **from the left** and **to the right** to open the drawer.

**Comment by audkar** [comment]
Doesn't work on Android Q

**Comment by Levi-Lesches** [comment]
Can you confirm that the above code works on older devices, but not Android Q? Not working on Android Q is a huge problem, but I'm not part of the Flutter team.

**Comment by justinmc** [comment]
The app below (using @Levi-Lesches's code) works for me on the iOS simulator, an emulated Pixel 2 running Pie, and an emulated Pixel 2 running Q.  Let me know if anyone can confirm a problem with Android Q and I'll definitely reopen this!

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold (
        drawer: Drawer (
          child: Text ("This will swipe from left to right"),
        ),
        endDrawer: Drawer (
          child: Text ("This will go from right to left"),
        )
      ),
    );
  }
}
```

**Comment by audkar** [comment]
Doesn't work when gesture navigation is enabled.

<img src="https://user-images.githubusercontent.com/1947112/59117413-4e939b80-8956-11e9-8dd6-4cd248d43d94.gif" width="200" />

This registered [issue](https://github.com/flutter/flutter/issues/32748). But seems that no actions/prioritization from Flutter team. Only couple months left until this version will be available to end users. I think there is no chance that gesture navigation compatible Flutter stable version will be released in time. So we as devs should be thinking how to workaround this situation.

**Comment by justinmc** [comment]
@audkar Ah I understand what you mean about Q now.  Let's keep this issue closed and track everything on the one that you referenced.  I will try to figure out the status of this in Flutter.

**Comment by mohtidawrani** [comment]
drawer: Drawer(),
drawerEdgeDragWidth: MediaQuery.of(context).size.width,       // this will make full screen swipable for drawer

try this inside scaffold
