### ISSUE TITLE
Make sure flutter build aar/framework can account for architecture/fat binary

### ISSUE THREAD

**Issue by xster** [flutter/flutter#34008]
Sub task from #26099

We should offer a flag to whether to build aar/frameworks with fat binaries or a specific architecture.

**Comment by jmagman** [comment]
It's still in beta, but XCFrameworks look interesting https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_2_release_notes?language=objc

**Comment by jmagman** [comment]
`flutter build ios-framework` generates fat binaries with the `--universal` flag (defaults to on) and can also generate XCFrameworks with `--xcframework`.  Is there anything on the Android side to track in this issue, @xster @blasten ?

**Comment by xster** [comment]
`flutter build aar` also has a --target-platform option now. Closing. Thanks all.
