### ISSUE TITLE
Could not find package sky_engine at "../../bin/cache/pkg/sky_engine"

### ISSUE THREAD

**Issue by MikeMitterer** [flutter/flutter#3400]
## Steps to Reproduce
Download ZIP from repo

Please tell us what you were doing and what went wrong.
cd stocks
flutter run

```bash
> examples $ cd stocks/
> stocks $ flutter run
Running 'pub get' in stocks...                   \
Could not find package sky_engine at "../../bin/cache/pkg/sky_engine".
Depended on by:
- flutter 0.0.21
```
## Flutter Doctor
```bash
[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /usr/local/Dart/flutter
    • Framework revision e456d86 (11 days ago), engine revision a299d69

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0-preview)
    • Android SDK at /Users/mikemitterer/Library/Android/sdk
    • Platform android-N, build-tools 24.0.0-preview
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[✓] iOS toolchain - develop for iOS devices (Xcode 6.2)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 6.2, Build version 6C131e
    x Flutter requires a minimum XCode version of 7.0.0.
      Download the latest version or update via the Mac App Store.
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

`flutter create <myapp>` + `flutter run` works

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
I would check `which flutter`, `flutter` when you run it will populate the `bin/cache` directory adjacent to the file, `examples/stocks` is depending on the existence of this `bin/cache` directory.  If you're running `flutter` from a separate flutter checkout on disk, it's likely confused.

This issue has come up before:
https://groups.google.com/forum/#!topic/flutter-dev/5wTABjmwhNs
And I suspect we may need to teach the `flutter` tool or `flutter doctor` to be smart about this error.

**Comment by Hixie** [comment]
Filed https://github.com/flutter/flutter/issues/3404 for making flutter catch this.
