### ISSUE TITLE
cmd: Can't find service: Error: ADB exited with exit code 1

### ISSUE THREAD

**Issue by MarcosdrVinicios** [flutter/flutter#34001]
i am new on flutter, when i execute flutter run console give me this:
![erro](https://user-images.githubusercontent.com/25845838/59062344-81c62400-889d-11e9-9b74-057fdc858adc.jpg)

the comand flutter doctor does not give me issues

**Comment by BondarenkoStas** [comment]
@MarcosdrVinicios did you solve it? Can you recreate the emulator?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by bgurtz** [comment]
I have been struggling with this off and on for a year, here is what I just noticed that makes it work or not work on my system. 

I discovered tonight that if I have my virus protection running my emulator stalls in the  
" --->    Built build\app\outputs\apk\debug\app-debug.apk. 
and I just get a white screen. I turn off the virus protection and it works fine in debug mode. 
If its on I have to keep going to the terminal and doing: " flutter run " to see any changes I have made. 
Maybe this will help someone.

**Comment by himanshusharma89** [comment]
You can wipe your emulator data from the Android Virtual Device Manager and then start running your app. It'll work. I just tried it, and it is working.
I guess the issue was caused because the storage of the emulator device got full.

**Comment by Vuyisile619** [comment]
@VladyslavBondarenko hie thanks for the response.Well it did kind of help i wiped out the data from the virtual device and it started working but when i hit flutter run, the virtual device would freeze or just stop itself and then the logs would end like this

C:\AndroidStudioProjects\flutterapp\test_project>flutter run
Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'... Done                      1260,5s (!)
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
  167,2s (!)
D/FlutterActivity( 5482): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate( 5482): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate( 5482): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
Flutter is taking longer than expected to report its views. Still trying...
Syncing files to device AOSP on IA Emulator...
D/FlutterActivityAndFragmentDelegate( 5482): Attaching FlutterEngine to the Activity that owns this Fragment.
D/OpenGLRenderer( 5482): Skia GL Pipeline
D/FlutterView( 5482): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@244933f
W/le.test_projec( 5482): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (light greylist, reflection)
W/le.test_projec( 5482): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (light greylist, reflection)
W/le.test_projec( 5482): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (light greylist, reflection)
W/le.test_projec( 5482): Accessing hidden method Landroid/util/LongArray;->get(I)J (light greylist, reflection)
D/FlutterActivityAndFragmentDelegate( 5482): Executing Dart entrypoint: main, and sending initial route: /
I/Choreographer( 5482): Skipped 302 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer( 5482): Initialized EGL, version 1.4
D/OpenGLRenderer( 5482): Swap behavior 1
D/HostConnection( 5482): HostConnection::get() New Host Connection established 0xe2b70150, tid 5863
D/HostConnection( 5482): HostConnection::get() New Host Connection established 0xe57a1140, tid 5503
D/HostConnection( 5482): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_1
D/HostConnection( 5482): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_1
W/OpenGLRenderer( 5482): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer( 5482): Swap behavior 0
D/eglCodecCommon( 5482): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation( 5482): eglCreateContext: 0xe57851e0: maj 3 min 1 rcv 4
D/eglCodecCommon( 5482): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation( 5482): eglCreateContext: 0xe3d32a00: maj 3 min 1 rcv 4
D/EGL_emulation( 5482): eglMakeCurrent: 0xe3d32a00: ver 3 1 (tinfo 0xe3d7c670)
E/eglCodecCommon( 5482): glUtilsParamSize: unknow param 0x000082da
E/eglCodecCommon( 5482): glUtilsParamSize: unknow param 0x000082da
D/HostConnection( 5482): createUnique: call
D/HostConnection( 5482): HostConnection::get() New Host Connection established 0xe57a1190, tid 5503
E/eglCodecCommon( 5482): GoldfishAddressSpaceHostMemoryAllocator: ioctl_ping failed for device_type=5, ret=-1
D/HostConnection( 5482): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_1
D/EGL_emulation( 5482): eglMakeCurrent: 0xe57851e0: ver 3 1 (tinfo 0xe57836f0)
E/eglCodecCommon( 5482): glUtilsParamSize: unknow param 0x000082da
E/eglCodecCommon( 5482): glUtilsParamSize: unknow param 0x000082da
I/Choreographer( 5482): Skipped 1683 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 5482): eglMakeCurrent: 0xe3d32a00: ver 3 1 (tinfo 0xe3d7c670)
D/eglCodecCommon( 5482): setVertexArrayObject: set vao to 0 (0) 1 2
I/OpenGLRenderer( 5482): Davey! duration=134875ms; Flags=1, IntendedVsync=2243599484209, Vsync=2271649483087, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=2271653219400, AnimationStart=2271653292800, PerformTraversalsStart=2271653312800, DrawStart=2271659659500, SyncQueued=2293522279700, SyncStart=2294562086000, IssueDrawCommandsStart=2294562257900, SwapBuffers=2365554445600, FrameCompleted=2379515031400, DequeueBufferDuration=4473659000, QueueBufferDuration=1135000,
I/Choreographer( 5482): Skipped 2571 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer( 5482): Davey! duration=66801ms; Flags=0, IntendedVsync=2409835137997, Vsync=2452685136283, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=2452697355600, AnimationStart=2452697499900, PerformTraversalsStart=2452701819700, DrawStart=2452709301600, SyncQueued=2452709346300, SyncStart=2452709472100, IssueDrawCommandsStart=2452709657600, SwapBuffers=2452710154400, FrameCompleted=2476637233900, DequeueBufferDuration=23705921000, QueueBufferDuration=7549000,
D/EGL_emulation( 5482): eglMakeCurrent: 0xe57851e0: ver 3 1 (tinfo 0xe57836f0)
D/eglCodecCommon( 5482): setVertexArrayObject: set vao to 0 (0) 1 0
I/Choreographer( 5482): Skipped 116 frames!  The application may be doing too much work on its main thread.
Lost connection to device.
Syncing files to device AOSP on IA Emulator...

C:\AndroidStudioProjects\flutterapp\test_project>
