### ISSUE TITLE
Allow for consistent observatory url hash for easy access

### ISSUE THREAD

**Issue by gamebox** [flutter/flutter#34010]
Internal: b/134690770

## Use case

We allow for people to specify a port for observatory which makes certain operations easier, but for tools like Dart DevTools, the hash is also required.  Finding this requires trawling through log output, and error prone copy and paste.
## Proposal

We should explore finding a way to provide a consistent or user-provided hash.  Alternatively, some other mechanism to have a consistent URL for observatory access would be acceptable.

**Comment by bkonyi** [comment]
Is it possible to pass `--disable-service-auth-codes` to whatever application you're running? This will disable the requirement for an authentication code and, when used in combination with a fixed Observatory port, will result in a stable Observatory URI.

**Comment by bkonyi** [comment]
Closing as this can be accomplished with `--disable-service-auth-codes`.
