### ISSUE TITLE
feature: Please support IntelliJ/WebStorm

### ISSUE THREAD

**Issue by MikeMitterer** [flutter/flutter#3401]
To run Flutter (flutter app) on Android you already have Android Studio on your machine wouldn't it just be logic to support IntelliJ/WebStorm???

**Comment by sethladd** [comment]
Thanks for the feedback! In the meantime, you could try using WebStorm to edit the syntax of Flutter, and then use the command-line tools to run/build the Flutter apps.

You may need to assign Flutter's dart SDK as the sdk for your Flutter project. Flutter bundles its own dart SDK, which may be different than the SDK you are using for your web projects. Not sure if WebStorm allows you to set an SDK per-project.

**Comment by devoncarew** [comment]
One thing to note is that iOS support is equally important to Flutter. It's ok to require Android Studio or the Android SDK for Flutter development on Android, but we don't want to require it if your primary target is iOS.

**Comment by sethladd** [comment]
We support IntelliJ now! :)
