### ISSUE TITLE
libtxt: Text shadow

### ISSUE THREAD

**Issue by cooler-king** [flutter/flutter#3402]
Add support for text shadowing as in [CSS](http://www.w3schools.com/cssref/css3_pr_text-shadow.asp).

Or point me to it if it already exists; doesn't seem to be in TextStyle or TextDecoration.

**Comment by cooler-king** [comment]
So this won't be addressed any time soon?

**Comment by abarth** [comment]
Looks like this is currently prioritized as something we want in the intermediate term but not something we need immediately.

**Comment by dvdwasibi** [comment]
Customer Pink requires this feature.

**Comment by Hixie** [comment]
@dvdwasibi You can fake it for now by blurring one text widget at on offset, then putting another on top.

**Comment by collinjackson** [comment]
Here's an example of the workaround Ian mentioned.

https://stackoverflow.com/a/44324381/1463116

**Comment by Hixie** [comment]
The example uses BackdropFilter, which is likely quite slow. We should ideally implement ImageFilter (https://github.com/flutter/flutter/issues/13489) and then use that.

**Comment by eseidelGoogle** [comment]
customer: dream is also interested in this.  We'll need to discuss their needs in more detail.

**Comment by denpalrius** [comment]
Eagerly hopeful for an easier way to achieve this, other than the **BackdropFilter** option

**Comment by morfinismo** [comment]
This is indispensable!

**Comment by rockingdice** [comment]
Need this really. Not a workaround but a solid feature.

**Comment by GaryQian** [comment]
PR:
https://github.com/flutter/flutter/pull/22449 (framework)
https://github.com/flutter/engine/pull/6385 (engine)

**Comment by GaryQian** [comment]
Text shadows have landed with https://github.com/flutter/flutter/commit/bdc3dda5f298f50b432faaffe71730c4fe26afda

To enable shadows, provide a List<Shadow> to TextStyle.shadows:

```
import 'dart:ui';
...
Text(
  'Hello, world!'
  style: TextStyle(
    shadows: <Shadow>[
      Shadow(
        offset: Offset(10.0, 10.0),
        blurRadius: 3.0,
        color: Color.fromARGB(255, 0, 0, 0),
      ),
      Shadow(
        offset: Offset(10.0, 10.0),
        blurRadius: 8.0,
        color: Color.fromARGB(125, 0, 0, 255),
      ),
    ],
  ),
),
...
```
