### ISSUE TITLE
Track release build performance in our benchmarks

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#34069]
We've heard story that Flutter's profile build may have significantly different performance than release build (b/134769255).

Now with https://github.com/flutter/engine/pull/8983, we should be able to track release performance in our benchmarks.

**Comment by liyuqian** [comment]
This will help https://github.com/flutter/flutter/issues/35409

**Comment by liyuqian** [comment]
@collinjackson : do you have any updates on running Flutter driver tests without host?

**Comment by chinmaygarde** [comment]
Closing this issue as the upstream issue has been closed. @liyuqian: Are there any pending work items?

**Comment by liyuqian** [comment]
@CareF is working on this. I think it's fine to keep this closed and track through https://github.com/flutter/flutter/issues/38329

**Comment by chinmaygarde** [comment]
Sounds good.
