### ISSUE TITLE
[web] Support instantiating an image with targetWidth and targetHeight

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#34075]

**Comment by deakjahn** [comment]
What would really help is adding image resize support to Skia. It doesn't have to be *added*, it's already there, `SkPixmap` and `SkImage` itself has `scalePixels()`. All it would take is to make it available from the outside. If it was there, readily available, `instantiateImageCodec()` could simply call it when it receives the target. Right now (at least, if my PR gets accepted :-) ) the only thing we, developers can do is to resize the image in a rather costly way, using the canvas. `scalePixels()` would be reasonably fast.

**Comment by netgfx** [comment]
Still having this https://github.com/flutter/flutter/issues/57659 issue on web, neither width or height have any effect.

**Comment by Tasseri** [comment]
I am also experiencing this issue on Web when trying to build a custom slider with a picture as thumbShape.

Is there any workarounds available?

**Comment by yjbanov** [comment]
A workaround is to record a scaled image into a `Picture` using a `PictureRecorder` and then use [Picture.toImage](https://api.flutter.dev/flutter/dart-ui/Picture/toImage.html) to get the scaled image back. It seems image codecs typically do not decode at given size anyway, so all we do in Flutter is decode full size then scale the image. Having the engine do the scaling has the convenience that the engine will do it on a separate thread and not block the UI thread. This is something we cannot do yet on the web (but we're working on it), so there wouldn't be any performance gains.
