### ISSUE TITLE
Flutter modules don't support custom build types

### ISSUE THREAD

**Issue by athornz** [flutter/flutter#34089]
## Steps to Reproduce

1. Create a new Flutter module project: flutter create --androidx -t module -a kotlin -i swift project_name
2. Add an additional build type to the build types of the host app, e.g. staging
3. Try to do a gradle sync or a build

You will receive the following error:

```
ERROR: Unable to resolve dependency for ':app@staging/compileClasspath': Could not resolve project :flutter.
Show Details
Affected Modules: app
```

The root cause here is that the flutter jar is only being added as a dependency on a fixed set of build types.

**Comment by athornz** [comment]
A work around for this is to specify matching fallbacks within the build type:

```groovy
buildTypes {
	staging {
	    matchingFallbacks = ['debug', 'release']
	}
}
```

**Comment by xster** [comment]
Merging into #30916 as well
