### ISSUE TITLE
Merge the web platform support with mainline Flutter.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#34082]
To date, the Flutter web platform support has been in its own fork. While you can now build an application for the web using Flutter (see [here](https://github.com/flutter/flutter/wiki/Building-a-web-application-with-Flutter), doing so causes the flutter tool to pull a bunch of cached artifacts that are forked, rather than directly derived from, the mainline.

This can have numerous unforeseen consequences --- impacts to network use and disk space, and because it's a fork, bugs you expect to be fixed in the mainline for a given channel may still not be fixed in the fork.

Flutter for web remains experimental _at least_ until this is resolved, and in all likelihood longer.

**Comment by gedw99** [comment]
Does this obviate the need to do for developers ?
````

flutter pub global activate webdev
````

**Comment by jonahwilliams** [comment]
@gedw99 yes, this would involving having a project import `flutter` and not `flutter_web` and using all of the existing flutter tooling.

**Comment by mofada** [comment]
I cloned the latest repository code, then run hello_world in example, it is blank
Is it because my flutter version is too high? Upgraded 1.8 in the last two days.

![M4LKC589A8U`}LE`PP5%F2Y](https://user-images.githubusercontent.com/22286246/61260221-e8e5cb00-a7af-11e9-92ee-d7f928a31590.png)


`flutter doctor -v`

```
[√] Flutter (Channel master, v1.8.1-pre.71, on Microsoft Windows [Version 10.0.18362.239], locale zh-CN)
    • Flutter version 1.8.1-pre.71 at D:\flutter
    • Framework revision b69feb5340 (5 days ago), 2019-07-11 01:56:27 -0400
    • Engine revision 49445ce494
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 09fc76bc51)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at D:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = D:\Android\android-sdk
    • Java binary at: D:\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.1.3)
    • Visual Studio at D:\Program Files (x86)\Microsoft Visual Studio\Community
    • Visual Studio Community 2019 version 16.1.29009.5

[√] Android Studio (version 3.4)
    • Android Studio at D:\Android\android-studio stable
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Android Studio (version 3.5)
    • Android Studio at D:\Android\android-studio
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7221

[√] Connected device (3 available)
    • Redmi 4X • c1f5972a7d74 • android-arm64  • Android 7.1.2 (API 25)
    • Windows  • Windows      • windows-x64    • Microsoft Windows [Version 10.0.18362.239]
    • Chrome   • chrome       • web-javascript • Google Chrome 75.0.3770.142

• No issues found!
```

**Comment by mofada** [comment]
I think maybe my dart version is too high.

```
F:\WorkSpace\Flutter\flutter_web\examples\hello_world>webdev serve
Can't load Kernel binary: Invalid kernel binary format version.
webdev 2.0.5 doesn't support Dart 2.1.1-dev.1.0.
```

pubspec.yaml
```
environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'
```

**Comment by sgon00** [comment]
Hi, sorry to interrupt. I have two questions related to the new approach.

(1) I am wondering wether `flutter run -d chrome` will call `webdev` in the background or not? If it calls `webdev`, should I install or update the `webdev` program manually? OR I can remove `webdev` completely?

(2) What is the best practice to manage the project for both mobile and web support? 
I am thinking of two ways. One way is creating three projects, one for common, one for mobile and one for web. And both mobile and web projects import the common project. Another way is only using one project and use some `switch` or `if` tests to determine which platform it's on and then execute the corresponding code. (btw I am not sure how to test the platform for web at present though. It seems TargetPlatform does not have a web value)

Thanks a lot.

**Comment by zTrix** [comment]
@sgon00 regarding how to test the platform for web, I can provide something.

Since [http](https://pub.dev/packages/http) is a cross-platform library in dart, supporting both web environment and native app environment, we could dig into its source code to find out how this is done.

https://github.com/dart-lang/http/blob/master/lib/src/client.dart#L14

Looking at the source code, http lib defines a `browser_client.dart` for browser env, and `io_client.dart` for native app, and combine them by conditional import using `dart.library.html` variable. Using this technique, you could also detect web platform.

Some more info about conditional import: https://medium.com/@dvargahali/dart-2-conditional-imports-update-16147a776aa8

**Comment by yjbanov** [comment]
This is done.
