### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Unable to add window -- token null is not for an application, null)

### ISSUE THREAD

**Issue by AtingTot** [flutter/flutter#34096]
flutter + webview_fluuter 0.3.9+1:

I/flutter ( 3579): initState
I/flutter ( 3579): [WEBPAGE][买车][http://47.111.168.8/app/buyCar.html]
E/flutter ( 3579): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Unable to add window -- token null is not for an application, null)
E/flutter ( 3579): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564)
E/flutter ( 3579): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316)
E/flutter ( 3579): <asynchronous suspension>
E/flutter ( 3579): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:631)
E/flutter ( 3579): <asynchronous suspension>
E/flutter ( 3579): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:556)
E/flutter ( 3579): <asynchronous suspension>
E/flutter ( 3579): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:189)
E/flutter ( 3579): <asynchronous suspension>
E/flutter ( 3579): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:170)
E/flutter ( 3579): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1604)
E/flutter ( 3579): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
E/flutter ( 3579): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter ( 3579): #9      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142)
E/flutter ( 3579): #10     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443)
E/flutter ( 3579): #11     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212)
E/flutter ( 3579): #12     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356)
E/flutter ( 3579): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter ( 3579): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
E/flutter ( 3579): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter ( 3579): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
E/flutter ( 3579): #17     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214)
E/flutter ( 3579): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter ( 3579): #19     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510)
E/flutter ( 3579): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter ( 3579): #21     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142)
E/flutter ( 3579): #22     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443)
E/flutter ( 3579): #23     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212)
E/flutter ( 3579): #24     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356)
E/flutter ( 3579): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter ( 3579): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
E/flutter ( 3579): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter ( 3579): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
E/flutter ( 3579): #29     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214)
E/flutter ( 3579): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter ( 3579): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
E/flutter ( 3579): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter ( 3579): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
E/flutter ( 3579): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter ( 3579): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
E/flutter ( 3579): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter ( 3579): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&R

before used 0.3.6 is ok

[✓] Flutter (Channel master, v1.7.3-pre.20, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✗] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
[!] Android Studio (not installed)
[!] IntelliJ IDEA Community Edition (version 2018.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

**Comment by AtingTot** [comment]
after update flutter is ok

**Comment by comptech-developer** [comment]
still having same issue 

E/flutter ( 8545): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Failed assertion: boolean expression must not be null
E/flutter ( 8545): #0      _LoginState._login (package:flutter_app/screen/login.dart:181:12)
E/flutter ( 8545): <asynchronous suspension>
E/flutter ( 8545): #1      _LoginState.build.<anonymous closure> (package:flutter_app/screen/login.dart:130:39)
E/flutter ( 8545): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter ( 8545): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter ( 8545): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 8545): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter ( 8545): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter ( 8545): #7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter ( 8545): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter ( 8545): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 8545): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter ( 8545): #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 8545): #12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter ( 8545): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter ( 8545): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 8545): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 8545): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 8545): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 8545): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 8545): #19     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter ( 8545): #20     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 8545): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 8545): #22     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter ( 8545): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter ( 8545):
