### ISSUE TITLE
camera1 api sdk 16 up support.

### ISSUE THREAD

**Issue by VTechJm** [flutter/flutter#34108]
## Proposal

please add support for android device sdk 16 up for camera 1 api
###

**Comment by khflab** [comment]
You can do it by your own, read more at https://flutter.dev/docs/development/platform-integration/platform-channels

Take camera package as example, who uses camera2 (camera1 is deprecated)

https://github.com/flutter/plugins/blob/master/packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java

**Comment by VTechJm** [comment]
yeah i know, was just a suggestion.. I have added plugin to dart pub aswell. https://github.com/VTechJm/flutter_wifi_info_plugin.Thanks for your response though.(y)

**Comment by TahaTesser** [comment]
duplicate of https://github.com/flutter/flutter/issues/19083
