### ISSUE TITLE
Documentation is missing "green arrows" for visual debugging

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#34106]
The documentation [here](https://flutter.dev/docs/testing/debugging#visual-debugging) seems like it does not mention the green arrows that get drawn for scroll views.

[Related question](https://stackoverflow.com/q/56508928/6509751) on StackOverflow.

Regarding the question, it might be worth to mention how they behave exactly, i.e. why they do not cover the entire `PageView` when it is not scrolled to the end if that is intended.

**Comment by jerryzhoujw** [comment]
[Inkwell not working properly with PageView.builder](https://github.com/flutter/flutter/issues/27744#issuecomment-462356839) mentioned this.
