### ISSUE TITLE
Admob Banner ad

### ISSUE THREAD

**Issue by headspy** [flutter/flutter#34100]
I am integrating the admob banner ads using the firebase_admob.

The test banner is loading up when it is being tested in both in debug mode and also after installing the apk in mobile manually. 

But this doesnt work when I replace the teat banner ads with real banner ads id in the code.  

I also added my payment and the banner ad unit is active for more than one week.

Code 

```
static final MobileAdTargetingInfo targetingInfo1 = new MobileAdTargetingInfo(
    testDevices: <String>[],
    keywords: <String>['wallpaper', 'walls'],
    childDirected: true,
  );

  BannerAd _bannerAd;

  BannerAd createBannerAd() {
    return new BannerAd(
        // adUnitId: BannerAd.testAdUnitId,
        adUnitId: "i have written my ad unit id here in my code ",
        size: AdSize.smartBanner,
        targetingInfo: targetingInfo1,
        listener: (MobileAdEvent event) {
          print("banner event");
          if(event == MobileAdEvent.failedToLoad){
            createBannerAd()..load();
          }
        });
  }

  @override
  void initState() {
    super.initState();
    FirebaseAdMob.instance
        .initialize(appId: "i have written my app unit id here in my code");
    _bannerAd = createBannerAd()..load()..show();
    
  }

  @override
  void dispose() {
    super.dispose();
    _bannerAd?.dispose(); 

  }
```

I wrote the above code in stateful widget before the build method,

**Comment by headspy** [comment]
@dnfield 
Hi can you look into this lot of us are facing this issue.

**Comment by dnfield** [comment]
I'm not sure I understand the problem you're having.  Are you say that using a test ID isn't working as expected?

I'm also probably not the best person to look at this right now - @amirh or @collinjackson  may know the right person for this plugin.

**Comment by headspy** [comment]
I am facing the problem when I am replacing the test ads with the real ad unit id. 
Test ads are working fine and I can see them each and every time the app is launched.

@dnfield I have attached images for your reference 



@amirh
 @collinjackson 
Can you look into this 

When using test ads
Image below
![WhatsApp Image 2019-06-12 at 12 01 26 AM](https://user-images.githubusercontent.com/23632601/59297216-59776480-8ca5-11e9-939c-60341996e6dc.jpeg)

Using real ads 
image below
![WhatsApp Image 2019-06-12 at 12 04 18 AM](https://user-images.githubusercontent.com/23632601/59297333-b246fd00-8ca5-11e9-9194-d18a9b4f3d4f.jpeg)


Error
Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
I/Ads     ( 8986): Use AdRequest.Builder.addTestDevice("xxx") to get test ads on this device.
I/AudioManager( 8986): In isSpeakerphoneOn(), calling application: com.example.first_app
W/Ads     ( 8986): Not retrying to fetch app settings
W/flutter ( 8986): onAdFailedToLoad: 3
I/Ads     ( 8986): Ad failed to load : 3
I/flutter ( 8986): banner event

**Comment by headspy** [comment]
The issue got resolved.
I think it is because I didn't add contentUrl in MobileAdTargetingInfo in my program.
Thanks.

**Comment by kroikie** [comment]
@headspy

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1180. Any further collaboration will be done there.
