### ISSUE TITLE
android_alarm_manager FATAL EXCEPTION: AsyncTask #2

### ISSUE THREAD

**Issue by Denmal1982** [flutter/flutter#34110]
Crash when running the application with the android_alarm_manager plugin

E/AndroidRuntime(21960): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime(21960): Process: ru.template.gps, PID: 21960
E/AndroidRuntime(21960): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(21960): 	at android.os.AsyncTask$3.done(AsyncTask.java:318)
E/AndroidRuntime(21960): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
E/AndroidRuntime(21960): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
E/AndroidRuntime(21960): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(21960): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/AndroidRuntime(21960): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/AndroidRuntime(21960): 	at java.lang.Thread.run(Thread.java:760)
E/AndroidRuntime(21960): Caused by: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: AsyncTask #2
E/AndroidRuntime(21960): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/AndroidRuntime(21960): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
E/AndroidRuntime(21960): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
E/AndroidRuntime(21960): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:166)
E/AndroidRuntime(21960): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
E/AndroidRuntime(21960): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
E/AndroidRuntime(21960): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
E/AndroidRuntime(21960): 	at io.flutter.plugins.androidalarmmanager.AlarmService.invokeCallbackDispatcher(AlarmService.java:170)
E/AndroidRuntime(21960): 	at io.flutter.plugins.androidalarmmanager.AlarmService.onHandleWork(AlarmService.java:151)
E/AndroidRuntime(21960): 	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
E/AndroidRuntime(21960): 	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
E/AndroidRuntime(21960): 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
E/AndroidRuntime(21960): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(21960): 	... 3 more

`void printHello() {
  final DateTime now = DateTime.now();
  print("[$now] Hello, world!");
}

void main() async {
  final int helloAlarmID = 0;
  await AndroidAlarmManager.initialize();
  runApp(MyApp());

  await AndroidAlarmManager.oneShot(
    Duration(seconds: 10),
    helloAlarmID,
    printHello,
    wakeup: true,
  ).then((val) => print(val));
}`

[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17134.765], locale ru-RU)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] Connected device (1 available)

**Comment by yuridiniz** [comment]
I was having the same problem with the version available in pub.dev `0.4.1+6`, but it looks like this commit corrected [https://github.com/flutter/plugins/commit/1586609efe312282b6c15ff87f67d0ec648a3f43](https://github.com/flutter/plugins/commit/1586609efe312282b6c15ff87f67d0ec648a3f43).

We have to wait for the version to be available, if your problem is emergency, [follow theses instructions](https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages)

**Comment by justinmc** [comment]
I'm closing this, but let me know if anyone still has a problem.

**Comment by pratik037** [comment]
@justinmc  I am facing the crashing issue while using flutter_google_places plugin
[Here's the link to the issue](https://github.com/fluttercommunity/flutter_google_places/issues/69#issue-456770398)
Please see if you can help.

**Comment by justinmc** [comment]
Hmm I'm not sure if this is related or not.  Hopefully someone from flutter_google_places will jump in with more knowledge about that plugin.

**Comment by MiguelSOliveira** [comment]
Has this been marged to the stable branch, yet?
