### ISSUE TITLE
Error retreving device properties for flutter

### ISSUE THREAD

**Issue by Dacts** [flutter/flutter#34124]
Error retrieving device properties for ro.product.cpu.abi:

Launching lib\main.dart on ONEPLUS A3003 in debug mode...
Initializing gradle...
Resolving dependencies...
--------- beginning of main
06-09 09:15:49.354 I/zygote64( 3443): Background concurrent copying GC freed 254375(12MB) AllocSpace objects, 183(12MB) LOS objects, 38% free, 37MB/61MB, paused 1.346ms total 290.901ms
Unhandled exception:
Exit code -1073740940 from: C:\Users\praveen_kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s 3d83341e shell -x logcat -v time -t 1
#0      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:360:7)
#1      runCheckedSync (package:flutter_tools/src/base/process.dart:289:10)
#2      AndroidDevice.lastLogcatTimestamp (package:flutter_tools/src/android/android_device.dart:513:27)
#3      _AdbLogReader._start (package:flutter_tools/src/android/android_device.dart:688:41)
#4      _runGuarded (dart:async/stream_controller.dart:805:24)
#5      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
#6      _ControllerStream._createSubscription (dart:async/stream_controller.dart:818:19)
#7      _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
#8      FlutterDevice.startEchoingDeviceLog (package:flutter_tools/src/resident_runner.dart:318:71)
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:361:5)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#11     AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:389:23)
#12     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:449:26)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:819:20)
#20     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:447:15)
<asynchronous suspension>
#21     AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:383:12)
<asynchronous suspension>
#22     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:301:38)
<asynchronous suspension>
#23     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#30     Future._complete (dart:async/future_impl.dart:473:7)
#31     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#32     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#33     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#34     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#35     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#40     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#41     Future._complete (dart:async/future_impl.dart:473:7)
#42     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#43     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#44     _rootRun (dart:async/zone.dart:1124:13)
#45     _CustomZone.run (dart:async/zone.dart:1021:19)
#46     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

**Comment by mizzuri** [comment]
Please refer to #33938.

**Comment by Dacts** [comment]
Yeah i found the solution which is not mentioned in that #33938 . 
What i did is just download SDK in a new folder by .
Open tools - > SDK manager .
And changed the SDK location to other dir name and selected that folder and the android studio automatically installs the new SDK which works for me.

**Comment by Polibuzz** [comment]
This a new problem. I can't run flutter in vscode all of a sudden. Here's the error:

Checking Android licenses is taking an unexpectedly long time...-Error retrieving device properties for ro.product.cpu.abi:

**Comment by Dacts** [comment]
Yeah same error come to me . This error is special case for flutter development . I was developing flutter application for more than 6 month . When my laptop hard disk failed i lost every data.So i downloaded the latest version after that this error is coming . Now i solved this error by this following steps please tell to other if this step procedure works for you .

1 .Downloaded android studio latest version.
2 . Download the flutter plugin.
3 . Run the sample application in the physical phone . If it shows error retrieving properties follow step 4 or enjoy coding flutter.
4. Tools - > SKD manager .
5. Change the sdk location . by clicking edit .
6 . Change the location of the sdk to a empty folder for example :
Create a SDK2 folder In the Android Folder where the previous SDK is present . 
At starting the SDK2 folder will be empty and after locating the sdk location to sdk2 click next in the android studio 
7. After clicking next the android studio will download the new SDK as of today the new SDk works fine for flutter for me.
8. After the 690 Mb downloaded . click finish and then restart the system after clearing catch in the android studio.

For me the above steps clears the property error.

**Comment by BondarenkoStas** [comment]
Thank you @Dacts, I think it's safe to close the issue. If you have any new input, please comment and I will re-open it.
