### ISSUE TITLE
basic_material_app_android__compile size doubled

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#34120]
According to the basic_material_app_android__compile, with change https://github.com/flutter/flutter/pull/33696 our size nearly doubles. Unclear whether this is an artifact of the benchmark, intentionally, or accidental

**Comment by jason-simmons** [comment]
APKs are now being built as arm32+arm64 fat binaries by default

**Comment by jonahwilliams** [comment]
This was due to bugs in the rolled back changes to the gradle script. This doesn't appear in the benchmarks today.
