### ISSUE TITLE
[cloud_firestore] cannot use {start{At/After}/end{At/Before}Document with Collection Group Queries

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#34135]
When trying to use e.g. `startAfterDocument` on a `collectionGroup` query, the resulting query will fail:

>Unhandled Exception: PlatformException(error, Invalid query. When querying a collection group and ordering by FieldPath.documentId(), the value passed to startAfter() must result in a valid document path, but '{documentId}' is not because it contains an odd number of segments., null)

I think that this requires to pass the full path and might look into fixing it.  
Anyway, this should be a common issue as this is a common use case.

**Comment by johnveloper** [comment]
Could you show the line of code where you perform the query?

**Comment by creativecreatorormaybenot** [comment]
@johnveloper Are you experiencing the issue as well and do not understand where it is coming from or why are you asking?  

I will try to explain it for you: Flutter [natively appends `orderBy(FieldPath.documentId()`](https://github.com/flutter/plugins/blob/f2effd6a8da0778c080592c3d1cfbf5c64aadde1/packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java#L246) when using ` {start{At/After}/end{At/Before}Document`, however, when the underlying query is a collection group query, Firestore requires to pass the full document path to `{start{At/After}/end{At/Before}`.
