### ISSUE TITLE
crash on windows-x64

### ISSUE THREAD

**Issue by gnf** [flutter/flutter#34141]
## Steps to Reproduce

1. Run desktop example on windows-x64 platform
2. Minimize the window
3. Crash occurs

## Logs

```
```

```
```

```
```

**Comment by gnf** [comment]
[fix_issues_34141.patch.txt](https://github.com/flutter/flutter/files/3270166/fix_issues_34141.patch.txt)
I tried to fix it briefly.

**Comment by stuartmorgan** [comment]
Duplicate of #30668
