### ISSUE TITLE
flutter doesn't work on first installation

### ISSUE THREAD

**Issue by olustixs01** [flutter/flutter#34149]
$ flutter doctor
$
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: c7c33e29f017c49b)
Crash report written to C:\Users\NUMEDIA\flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues

**Comment by jonahwilliams** [comment]
You haven't attached any error report so It won't be possible for us to help. It might be that you're missing permissions to read/write files.
