### ISSUE TITLE
would like a left-nav for the docs at flutter.io

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#3414]
It would be good to have a left-nav column for the docs at https://flutter.io/. I don't have any sense of where I am in the site or what other pages are available. The overview of the available pages is at that first landing page but not on the other pages.

@qchong

**Comment by qchong** [comment]
Hi Devon, thanks for opening a bug against this. I've been working just this problem but still need to make some tweaks.

**Comment by devoncarew** [comment]
👍 looks great!

**Comment by sethladd** [comment]
Thanks! Love that it's responsive :)

Do we need the big "this link goes outside the site" icons? They are as big as the fonts themselves. Can we make them smaller?
