### ISSUE TITLE
App install fails after almost randomly

### ISSUE THREAD

**Issue by mayankjanmejay** [flutter/flutter#34158]
Hello,
I recently formatted my computer re-installed all the android tools and then the trouble began. All the release versions of the same (flutter) project started not installing on real devices. Sometimes the tablets would say package is corrupts and other times app not installed because another app with the same applicationID was found. 

Now what it has come to is that I need to uninstall the current app build from the tablets restart the tablet and then only a release version will install on real devices. I have no such issues like this on the Android Emulator.  

Flutter Doc
_________

√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18908.1000], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at D:\flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[√] Android toolchain - develop for Android devices (Android SDK version 1129.0.0)
    • Android SDK at C:\Users\Mayank\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 1129.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.35.0)
    • VS Code at C:\Users\Mayank\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (1 available)
    • Lenovo TB 7304I • HKL49UGS • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.

/android/app/build.gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        multiDexEnabled true
        applicationId "com.greensoft.sfa"
        minSdkVersion 24
        targetSdkVersion 28
        versionCode 2428
        versionName "2.4.28"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
    release {
        keyAlias keystoreProperties['keyAlias']
        keyPassword keystoreProperties['keyPassword']
        storeFile file(keystoreProperties['storeFile'])
        storePassword keystoreProperties['storePassword']
    }
}
buildTypes {
    release {
        signingConfig signingConfigs.release
    }
}
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:multidex:1.0.3'    
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    implementation 'com.google.firebase:firebase-core:16.0.4'
    implementation 'com.google.firebase:firebase-firestore:17.1.5'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    
}
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.1.1"
            }
        }
    }
}
apply plugin: 'com.google.gms.google-services'

Please help

**Comment by mayankjanmejay** [comment]
I forgot to mention, 9/10 the app will install using ADB but not when the app is being run from the tablet's memory.

**Comment by jonahwilliams** [comment]
I found https://stackoverflow.com/questions/11891848/install-failed-update-incompatible-when-i-try-to-install-compiled-apk-on-device on the internet, but I don't have any particular insight into why this might happening.

Is it only on this particular tablet?
