### ISSUE TITLE
Camera plugin ImageStream causing flickering on OnePlus 6T device

### ISSUE THREAD

**Issue by Isakdl** [flutter/flutter#34152]
I'm trying to access the image stream from the camera plugin. While it works and produces the intended functionality it causes heavy flickering on OnePlus 6T device. I have tried on other Android models and this issue was not present. If the startImageStream is not used, no flickering occurs either.

The flickering starts slow and is barely noticeable the first second after the camera is open. After that, it is just flickering like crazy. 

Now the question is, is this a problem with oneplus or the plugin?
Any way to solve it? (I intend to build a QR code reader with firebase ML kit)

```dart
@override
  void initState() {
    super.initState();
    _controller = CameraController(cameras[0], ResolutionPreset.medium);
    _controller.initialize().then((_) {
      if (!mounted) {
        return;
      }

      //Using the stream makes the camera flicker on Oneplus 
      await _controller.startImageStream((CameraImage availableImage) {
        //even with no code in here
      });
      setState(() {});
    });
  }
```

**Comment by DanielWeidinger** [comment]
I have exactly the same problem with my OnePlus 6T.

**Comment by Errichamonda** [comment]
Same problem on OnePlus 6

**Comment by ProOrange** [comment]
I have same problem on Xiaomi Mi 9 SE

**Comment by topnax** [comment]
I do have the same problem with the Oneplus 6. Any news on this?

**Comment by janmoppel** [comment]
Hello @Isakdl !

Does the problem still persist in the latest stable version?

@topnax, do you use the latest plugin and flutter version?

**Comment by Isakdl** [comment]
@janmoppel 

Yes, it does, I'm currently running flutter v1.9.1+hotfix.2 w/ android SDK 28.0.3

**Comment by topnax** [comment]
> Hello @Isakdl !
> 
> Does the problem still persist in the latest stable version?
> 
> @topnax, do you use the latest plugin and flutter version?

I use the latest camera (0.5.5+1) plugin and Flutter version (1.9.1+hotfix.4). The problem still persists.

**Comment by memetea** [comment]
The same problem with OnePlus 6T. CameraPreview with startImageStream the same time causes flickering

**Comment by topnax** [comment]
I think this might be related to the camera sensor itself? 

Try to reproduce this:

1. Start an image stream
2. Wait for the flickering to start
3. Once the flickering has started, put your finger over the camera sensor to block the incoming light
4. Wait for the camera preview to go completely dark
5. Lift your finger from the sensor and watch as the flickering has stopped
6. The flickering slowly starts to build up again

This might indicate that this issue is not related to data stream itself, but to some properties that are being set to the camera. Can anyone confirm this?

**Comment by Isakdl** [comment]
@topnax 

Yes that is true, and it seems to be worse in bright lights, it might actually get in sync with the frequency of the lightbulbs. But with that said, other camera apps, like the native camera app, does not have this problem on the same phone. 

So it cannot simply be the hardware either, it's the combination of the flutter library and the phone. Does the package control the shutter speed of the camera or similar settings?

**Comment by Isakdl** [comment]
Tried the lastest camera plugin, version: 0.5.7+1 and this issue seem to be solved on my device (OnePlus 6T).

**Comment by topnax** [comment]
I can also confirm that it is solved on my device (OnePlus 6)

**Comment by darshankawar** [comment]
@Isakdl Given your last message, I am going ahead and closing this issue as resolved.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
