### ISSUE TITLE
Keyboard may get hidden when switching from a Flutter text field to an AndroidView text field.

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#34169]
On Android, starting from a state where a Flutter text field is focused and the keyboard is showing, and then tapping on a platform view (e.g WebView) text field, the expected behavior is that the keyboard stays open and is connected to the WebView's text field. We currently have a race condition that may end in the keyboard getting hidden. I actually wasn't able to get this race condition end in the buggy way, but I tweaked the code and added a delay to illustrate what the issue will look like:

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/1024117/59220092-eb358380-8b78-11e9-9c81-dc78ce54ffa9.gif)

A short term alternative would be to not allow the framework to hide the keyboard when the input connection target is a platform view. This will fix the issue illustrated above but will create a new problem where the keyboard is not hidden when it should be(e.g changing focus from a Flutter text field to a non Text field input in a WebView), leaving the app with a disconnected keyboard, this is what it would have looked like:

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/1024117/59220385-b0801b00-8b79-11e9-806c-d364d1f5a5e1.gif)

Having to choose between these to I figured the first alternative(of potentially getting the keyboard hidden when it shouldn't be) is the least bad option. Especially as without adding a synthetic delay I couldn't hit the issue.
I'm happy to be convinced that the other option is better if anyone thinks it's a better choice.

The issue is that the frame [delays the call to hide the keyboard](https://github.com/flutter/flutter/blob/71bfe3be9f66adea08a21bd533f3f826cfc21592/packages/flutter/lib/src/services/text_input.dart#L664) which means the engine gets it after the platform view got the focused(and thus potentially after the platform view has shown the keyboard).

Longer term, we may be able to refactor the framework focus/input code to guarantee that a call to set a platform view text client always happens after calls to hide keyboard. This may lead to the keyboard briefly disappearing and appearing(although it seems that Android knows how to deal properly deal with hide/show in close succession).

@jason-simmons @gspencergoog @csells

**Comment by markusaksli-nc** [comment]
Reproducible on the latest master `1.21.0-6.0.pre.223` using `webview_flutter: ^0.3.22+1`.
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: SingleChildScrollView(
          child: Column(
            children: [
              TextField(),
              TextField(),
              Container(height: 400, child: WebView(initialUrl: "https://www.google.com/")),
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.223, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.223 at /Users/markus/development/flutter_master
    • Framework revision 6d487355a3 (6 hours ago), 2020-08-05 20:21:02 -0700
    • Engine revision d728f691f4
    • Dart version 2.10.0 (build 2.10.0-3.0.dev d5ff386abe)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/markus/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

 
[✓] Connected device (4 available)            
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • macOS (desktop)   • macos              • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)  • web-server         • web-javascript • Flutter Tools
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>
