### ISSUE TITLE
expose the app's FPS as a service extension

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#3416]
Which might look like:
- [ ] get the value for the current FPS
- [ ] enable and disable receiving periodic events / updates for the FPS
- [ ] toggle in Atom
- [ ] toggle via `flutter run` (??)

IDE's and other tools could use this to display a small FPS badge or a sparkline chart. @yjbanov - your work with the driver extensions may already expose this info?

**Comment by sethladd** [comment]
Love it.

**Comment by eseidelGoogle** [comment]
Sounds like you want the data from https://github.com/flutter/engine/blob/master/flow/layers/performance_overlay_layer.cc exposed via that observatory protocol?  FYI @chinmaygarde.  Note currently gpu and cpu times are computed at the engine layer and not exposed to Dart.

**Comment by yjbanov** [comment]
It's more of a dashboard thing than a driver thing. The driver downloads the timeline all in one shot and then interprets it locally. What you probably want is subscribe to the "Timeline" [event stream](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#streamlisten) and interpret the events live. For example, you could count the number of "Engine::BeginFrame" that happened in the last second.

One thing we should filter out is idle gaps when no new frames are drawn. If you count frames during such periods you will get a wrong number. Although looking at Chrome's FPS indicator it seems to be counting everything, so if you stop interacting with the web page the FPS count drops to zero.

**Comment by chinmaygarde** [comment]
The stopwatches you need to query are at https://github.com/flutter/engine/blob/48de25e19bf3503e64f30d50cc7cde18aece8ad8/flow/paint_context.h#L65 These should also tell you how many frames were skipped in the given interval and by how much (and by which component).

Just be sure to guard access of these stopwatches though. Frames borrow the stopwatches from the context and update them with relevant information. Since frames are rendered only on the GL thread, there is no locking of the same.

**Comment by chinmaygarde** [comment]
> One thing we should filter out is idle gaps when no new frames are drawn. If you count frames during such periods you will get a wrong number.

@yjbanov: The stopwatches will never get updated if there are no new frames. So this should not be a problem.

**Comment by Hixie** [comment]
@devoncarew Did you do this recently? It sounds familiar.

**Comment by devoncarew** [comment]
Yup! The framework now sends events with frame info when they occur, in debug and profile modes.

I think we can close this bug - some of the other items are obsolete, and we have more specific bugs tracking the remaining work (https://github.com/flutter/flutter-intellij/issues/1144).
