### ISSUE TITLE
Modify fade effect of background when Drawer widget is opened?

### ISSUE THREAD

**Issue by CountPablo** [flutter/flutter#34171]
## Use case

I have a Scaffold with a black background and that has a Drawer that is also black. Since the fade effect that happens when the Drawer is opened is to fade to 'Colors.black54' (Black with opacity 54%) the Drawer's border isn't visible.

I'd like it to fade to Grey with opacity 54%.

The only way I found that this can be done is to modify Flutter's source code file "drawer.dart" directly (line 382) but this isn't an actual solution, it's more of a hack.

## Example Code (to reproduce if needed)

```
return new Scaffold(
  backgroundColor: Colors.black,
  drawer: new Drawer(
    child: new Container(
      color: Colors.black,
      child: new Center(
        child: new Text(
          'Test',
          style: new TextStyle(
            color: Colors.white
          )
        )
      ),
    ),
  ),
);
```

## Flutter Doctor

Pablos-Mac-mini:soulzoneapp pablodupontavice$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.13.6 17G65, locale en-CA)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.34.0)
[✓] Connected device (6 available)

• No issues found!

**Comment by justinmc** [comment]
If you're using Flutter v1.6.0 and above, you can pass the `drawerScrimColor` to your `Scaffold`.  This was added recently in https://github.com/flutter/flutter/pull/31025.  See more about using a higher Flutter version in the [docs about Flutter's channels](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels).

Let me know if that doesn't solve your problem and I'll reopen!

**Comment by CountPablo** [comment]
It works thanks!
