### ISSUE TITLE
Create a generic 'synchronous' engine data initialization mechanism

### ISSUE THREAD

**Issue by xster** [flutter/flutter#34170]
Currently there is setInitialRoute/pushRoute which has a timing sensitive API that could use improvements.

Simultaneously, there's asks in add-to-app to be able to send generic data initialization while loading up new isolates that's richer than sending a string to define the initial route or choosing a vm entry point. https://github.com/flutter/flutter/issues/23786

Simultaneously, in full-app cases, we need to populate the isolate initialization with iOS 13 color data.

Simultaneously, it would be nice to also be able to develop/debug add-to-app cases by just running the wrapper as a full-app using mock initialization data to do lighter development as @blasten suggested. 

Perhaps something akin to `application:(UIApplication*)application willFinishLaunchingWithOptions:(NSDictionary*)launchOptions`'s launchOptions NSDictionary.

**Comment by matthew-carroll** [comment]
@xster @dnfield I filed an issue for arbitrary data initialization to help with iOS dark mode and @chinmaygarde implemented that capability in the engine. I think all we need now is the appropriate API exposure to the embeddings and it should then be generically usable.

**Comment by xster** [comment]
Is it RuntimeController::SetUserSettingsData? I think that one is an imperative call that happens after the first frame and is consumed by dart:ui rather than by the user.

**Comment by matthew-carroll** [comment]
Here's the PR: https://github.com/flutter/engine/pull/13047

**Comment by xster** [comment]
Looks reasonable. We can dress it up a bit with https://github.com/flutter/flutter/issues/32930 to make the byte wrangling a bit more ergonomic and do the piping like you mentioned. Is getPersistentIsolateData currently used in flutter/flutter? I didn't find any references.

**Comment by matthew-carroll** [comment]
@LongCatIsLooong did you end up using this capability for iOS dark mode?

**Comment by LongCatIsLooong** [comment]
We ended up hard coding the colors because we want to make them compile time constants and we expect their values to not change much from version to version.

**Comment by matthew-carroll** [comment]
Aren't the colors runtime dynamic such that they can change at any time?

**Comment by LongCatIsLooong** [comment]
Yeah the system colors change based on the ambient UI traits, but there're only 8 variants at most so we made a new Color class and store all the possible RGB values of a dynamic color in that class. It will pick the right RGB value to use when given a `BuildContext`.

**Comment by tvolkert** [comment]
Fixed by https://github.com/flutter/engine/pull/29096
