### ISSUE TITLE
BitmapDescriptor.fromNetworkImage

### ISSUE THREAD

**Issue by Xgamefactory** [flutter/flutter#34183]
Hi,
Any plans for network image as a marker icon ?
Heremaps,Mapbox Google maps native sdk already has such support 
is it hard to implement it for flutter ?

I mean it just a passing url string and native map sdks has built it support for handling this as a marker.

**Comment by mikhail-tokarev** [comment]
Hi @Xgamefactory 
I see there's an open issue addressing the case you described;
please follow up on the issue liked above.

I'm closing the current one as duplicate
if you disagree please write in the comments
and I will reopen it
