### ISSUE TITLE
measure build times per builder for build_runner

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#34180]
This can be aggregated via a flag on build_runner itself.

**Comment by zanderso** [comment]
@jonahwilliams are you still intending to do this?

**Comment by jonahwilliams** [comment]
This may not be important to do in the near future, since we're moving away from build_runner for web support and that was the primary use-case.

**Comment by zanderso** [comment]
Okay, I'll go ahead a close this then.
