### ISSUE TITLE
Can't run flutter create on an existing flutter project

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3418]
`flutter create --help` says "if you run on a project that already exists, this will repair the project, recreating any files that are missing"

However, when I run `flutter create map` on a directory that exists and that contains a flutter project, I get this:

`Invalid project name: '/Users/sethladd/flutter/map' - refers to a directory that is not empty.`

What is the expected behavior?

**Comment by devoncarew** [comment]
This regressed (while fixing another bug). It should create files that don't exist but not overwrite existing ones.

**Comment by sethladd** [comment]
Thanks for confirming!
