### ISSUE TITLE
Widget's double-layer on first interaction.

### ISSUE THREAD

**Issue by JediBurrell** [flutter/flutter#34198]
* I've only tested this on Flutter for Web.
* This affects both debug and release.
* [flutter doctor](https://hastebin.com/yizuhodisu)
* v1.5.4-hotfix.2

I updated Flutter, and suddenly _everything_ started appeared darker when I'd click the page. My `Switch` went from grey to nearly black, chips lost its contrast, dividers became more drastic, text looked aliased.

I suspected it was because it was rendering the new frame on top of the previous frame. I have now determined this is definitely the issue. [See here.](https://photos.app.goo.gl/3SKxBy59b9EH44yK9)

The above link shows the issue, but here are some more obvious examples in picture form.

---
A black `Switch`.

![Before.](https://user-images.githubusercontent.com/9306469/59235148-f19a1e80-8bbd-11e9-9d53-5f5eb9d61742.png)
![After](https://user-images.githubusercontent.com/9306469/59235161-fced4a00-8bbd-11e9-8520-cb4f84d98bb3.png)
---
A `RawChip` without background color.

![Before](https://user-images.githubusercontent.com/9306469/59235176-0a0a3900-8bbe-11e9-9c36-cd4d8ac22ab2.png)
![After](https://user-images.githubusercontent.com/9306469/59235185-10001a00-8bbe-11e9-8bd6-6c06edbace8d.png)
---
And of course, text.

![Before](https://user-images.githubusercontent.com/9306469/59235285-6ec59380-8bbe-11e9-863c-7c05fb938f54.png)
![After](https://user-images.githubusercontent.com/9306469/59235291-74bb7480-8bbe-11e9-85d4-69f993885ec1.png)
![Before](https://user-images.githubusercontent.com/9306469/59235323-94eb3380-8bbe-11e9-8627-22ab00d96b22.png)
![After](https://user-images.githubusercontent.com/9306469/59235327-99175100-8bbe-11e9-9bb3-ef154783dd26.png)

**Comment by KenAragorn** [comment]
Is this related?
[https://github.com/flutter/flutter/issues/35114](https://github.com/flutter/flutter/issues/35114)

**Comment by JediBurrell** [comment]
@KenAragorn Yes.

**Comment by ferhatb** [comment]
Fixed via https://github.com/flutter/flutter_web/commit/3f6fd27dd05cf9a29fb64b72af5fdd56766580b3
