### ISSUE TITLE
IJ flutter test runs in verbose mode(and as a result debug console is polluted with toStringDeep methods)

### ISSUE THREAD

**Issue by aam** [flutter/flutter#34191]
When launching test(test/painting/image_provider_test.dart from packages/flutter) from IJ IDE I'm seeing following in Console:
```
Testing started at 3:45 PM ...
$FH/flutter/bin/flutter --no-color test --machine --start-paused --verbose test/painting/image_provider_test.dart
...
[        ] Connecting to service protocol: http://127.0.0.1:33463/8YJC39D-WdU=/
[ +147 ms] Successfully connected to service protocol: http://127.0.0.1:33463/8YJC39D-WdU=/
[ +852 ms] test 0: process with pid 245988 connected to test harness
[        ] test 0: awaiting test result for pid 245988[ +655 ms] -> result af1cd84b-5ebc-4b39-ad02-3b514f660f1b
[  +44 ms] -> org-dartlang-debug:synthetic_debug_expression:1:1: Error: Method not found: 'toStringDeep'.
[        ] -> toStringDeep()
[        ] -> ^^^^^^^^^^^^
[   +8 ms] -> org-dartlang-debug:synthetic_debug_expression:1:1: Error: The method 'toStringDeep' isn't defined for the class 'NetworkImage'.
[        ] ->  - 'NetworkImage' is from 'package:flutter/src/painting/image_provider.dart' ('lib/src/painting/image_provider.dart').
[        ] -> Try correcting the name to the name of an existing method, or defining a method named 'toStringDeep'.
[        ] -> toStringDeep()
[        ] -> ^^^^^^^^^^^^
[   +8 ms] -> af1cd84b-5ebc-4b39-ad02-3b514f660f1b /tmp/flutter_test_compiler.FZABGZ/output.dill 2
[ +650 ms] -> result ee931a5c-2e89-4150-8d58-fc87913a4c1f
[   +2 ms] -> org-dartlang-debug:synthetic_debug_expression:1:1: Error: Method not found: 'toStringDeep'.
[        ] -> toStringDeep()
[        ] -> ^^^^^^^^^^^^
[        ] -> org-dartlang-debug:synthetic_debug_expression:1:1: Error: The method 'toStringDeep' isn't defined for the class 'NetworkImage'.
[        ] ->  - 'NetworkImage' is from 'package:flutter/src/painting/image_provider.dart' ('lib/src/painting/image_provider.dart').
[        ] -> Try correcting the name to the name of an existing method, or defining a method named 'toStringDeep'.
[        ] -> toStringDeep()
[        ] -> ^^^^^^^^^^^^
[   +1 ms] -> ee931a5c-2e89-4150-8d58-fc87913a4c1f /tmp/flutter_test_compiler.FZABGZ/output.dill.incremental.dill 4
...
```

is this intentional? 
`toStringDeep` diagnostic is as expected in verbose mode, but why are we running flutter test in verbose mode? Basically as you move cursor over different parts of the source code and hover over various parts of the source you see those messages added to the Console, which is quite distracting.

@devoncarew , do you know?

**Comment by devoncarew** [comment]
@aam, there's a user preference to enable verbose logging for runs - possible this has been enabled on your machine? I'd check the `Languages & Frameworks > Flutter` settings for 'enable verbose logging'.

**Comment by pedromassangocode** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
