### ISSUE TITLE
Tests should fail if engine logs error

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#34194]
Per https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#expectations-around-potential-crashes-in-the-engine, engine should not crash during errors. Hence the only way for the engine to notify an error is probably `FML_LOG(ERROR) << ...`. All our unit tests and driver tests should catch such error log, and fail the test.

**Comment by liyuqian** [comment]
@Hixie @tvolkert @cbracken @chinmaygarde @jonahwilliams @dnfield : any objection on this?

**Comment by jonahwilliams** [comment]
No objection here

**Comment by tvolkert** [comment]
Agreed 👍

**Comment by dnfield** [comment]
I agree.  Not sure how we would catch stdout from the engine va anything else but it seems like a solvable problem

**Comment by pedromassangocode** [comment]
Is this still a valid issue?

**Comment by dnfield** [comment]
Yes.

**Comment by jonahwilliams** [comment]
I don't think we're going to do this
