### ISSUE TITLE
"flutter analyze" hangs if the directory doesn't have any dart files in it

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#34193]
Create an empty directory.
Run `flutter analyze` in it.
It'll hang.
Run `touch x.dart` in that directory.
The `flutter analyze` process suddenly completes.

cc @devoncarew @jonahwilliams

**Comment by jonahwilliams** [comment]
Seems like it is probably an issue with the analyzer. We could always walk the directory first to check for no dart files but that feels like a hack

**Comment by devoncarew** [comment]
`flutter analyze` relies on analysis starting / analysis stopped events from the analysis server to know when the analysis server is processing files. It doesn't send these events if there's nothing to process.

To address this issue, we'd either need to modify the analysis server to send the events even when there's nothing to process, or adapt flutter analyze to exit if there are no dart files in the directory (or child directories).

**Comment by Hixie** [comment]
@devoncarew is there a bug# for the analysis server side of this? (Or do you think we should support this entirely in the tool?)

**Comment by devoncarew** [comment]
We should address in the analysis server, or, add some capability in the analysis server to allow clients to know when analysis has started and stopped.
