### ISSUE TITLE
[web] BoxBorder doesn't work 

### ISSUE THREAD

**Issue by 461882111zzy** [flutter/flutter#34201]
## Steps to Reproduce

1. ...Container Has set the  decoration property ,which assign by BoxDecoration 
2. ...BoxDecoration has set the borderRadius and border
3. ...when borderRadius.circle(20.0), and border.width(1~5), it doesn't work.

## Logs

```
```

```
```

```
```

**Comment by ferhatb** [comment]
Tried the following:

var asymetricalRoundedCorners = Container(
  padding: EdgeInsets.all(20.0),
  child: Text("Asymetrical Rounded Corners"),
  decoration: BoxDecoration(
      border: const Border(
        left: BorderSide(color: Colors.red, width: 2),
        top: BorderSide(color: Colors.red, width: 2),
        bottom: BorderSide(color: Colors.red, width: 2),
        right: BorderSide(color: Colors.red, width: 2),
      ),
      borderRadius: BorderRadius.only(topRight: Radius.circular(20.0)),
      color: Colors.brown),
);

It is rendering identically on web and ios.
Cannot repro issue, can you please paste decoration config. Thx!

**Comment by ditman** [comment]
This is probably fixed here: https://github.com/flutter/engine/commit/851f4606f19541376b6e8915e7b8677b31853223
