### ISSUE TITLE
Flutter run not working

### ISSUE THREAD

**Issue by engr-zeeshan** [flutter/flutter#34211]
## command

flutter run

### exception

ProcessException: ProcessException: Process "C:\Users\engrz\Desktop\myexpensetracker\android\gradlew.bat" exited abnormally:
Exception in thread "main" java.lang.NullPointerException
	at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:34)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:25)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: C:\Users\engrz\Desktop\myexpensetracker\android\gradlew.bat -v

## FLutter Doctor
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18362.145], locale en-PK)
 
Checking Android licenses is taking an unexpectedly long time...-Error retrieving device properties for ro.product.cpu.abi:

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.4)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.35.0)
[√] Connected device (1 available)
```
```

**Comment by CrunchyFlannel** [comment]
Check if you have the flutter/dart plugins for vs code

**Comment by engr-zeeshan** [comment]
@CrunchyFlannel Yes, I do have installed them in VC Code. I have been developing apps for the last few months. I am facing this issue after I updated flutter few days back.

**Comment by CrunchyFlannel** [comment]
Oh ok so actually I may have encountered the same problem a couple of months ago, try making sure flutter vscode has flutter in it's path again. Sometimes after an update I would find it changed

**Comment by engr-zeeshan** [comment]
@CrunchyFlannel I thought that there might be some gradle issue. I found that I had **gradle-5.1.1** in gradle folder of Android Studio. After updating value of **distributionUrl** with **https\://services.gradle.org/distributions/gradle-5.1.1-all.zip** in **gradle-wrapper.properties** file, "flutter run" is now working fine.

**Comment by d-apps** [comment]
I thought that gradle verson 5.1.1 could be A.S default to solve this problem.
