### ISSUE TITLE
Long press options on text field not appearing when text is blank

### ISSUE THREAD

**Issue by jaysson** [flutter/flutter#34216]
The code:
```dart
TextField(
  onChanged: (text) => setState(() {
    mobileNumber = text;
  }),
  keyboardType: TextInputType.phone,
  style: Theme.of(context).textTheme.body2,
  autofocus: true,
  decoration: InputDecoration(
    labelText: 'Mobile Number', prefixText: '+91 '),
);
```
If I try to long press when the field is empty, it does not show any options. However, if I type a few characters and then long press, it displays `Paste`, `Select` options.

Using beta channel. Happens on both iOS and Android.

**Comment by jerrywell** [comment]
i have the same issue here. 
https://github.com/flutter/flutter/issues/34215
