### ISSUE TITLE
support Desktop.

### ISSUE THREAD

**Issue by catastrop** [flutter/flutter#34213]
It will be nice if we can use Flutter to create desktop application that runs cross platform ( BSDs, Linux, macos).

**Comment by AlvaroVasconcelos** [comment]
Hi, I think your wishes have been met.
The desktop flutter is already in testing.

[Flutter Desktop](https://github.com/google/flutter-desktop-embedding)

**Comment by stuartmorgan** [comment]
Closing, as there are specific issues tracking specific work related to desktop.
