### ISSUE TITLE
 Android toolchain - develop for Android devices (Android SDK version 29.0.0)  ! Some Android licenses not accepted.  

### ISSUE THREAD

**Issue by pravallik** [flutter/flutter#34217]
## Steps to Reproduce

 when  i run "flutter doctor"  This is the output I get 

## Logs

```
```

[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.765], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at C:\Users\Administrator\Desktop\flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.35.0)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

```
```
When I run flutter --andriod-licenses
```
```
$ flutter doctor --andriod-licenses
Could not find an option named "andriod-licenses".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

Administrator@DESKTOP-35FC6VU MINGW64 ~
$ flutter -h
Manage your Flutter app development.

Common commands:

  flutter create <output directory>
    Create a new Flutter project in the specified directory.

  flutter run [options]
    Run your Flutter application on an attached device or in an emulator.

Usage: flutter <command> [arguments]

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands executed.
                            If used with --help, shows hidden options.

-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --suppress-analytics    Suppress analytics reporting when this command runs.
    --bug-report            Captures a bug report file to submit to the Flutter team.
                            Contains local paths, device identifiers, and log snippets.

    --packages              Path to your ".packages" file.
                            (required, since the current directory does not contain a ".packages" file)

Available commands:
  analyze                  Analyze the project's Dart code.
  attach                   Attach to a running application.
  bash-completion          Output command line shell completion setup scripts.
  build                    Flutter build commands.
  channel                  List or switch flutter channels.
  clean                    Delete the build/ and .dart_tool/ directories.
  config                   Configure Flutter settings.
  create                   Create a new Flutter project.
  devices                  List all connected devices.
  doctor                   Show information about the installed tooling.
  drive                    Runs Flutter Driver tests for the current project.
  emulators                List, launch and create emulators.
  format                   Format one or more dart files.
  help                     Display help information for flutter.
  install                  Install a Flutter app on an attached device.
  logs                     Show log output for running Flutter apps.
  make-host-app-editable   Moves host apps from generated directories to non-generated directories so that they can be edited by developers.
  packages                 Commands for managing Flutter packages.
  precache                 Populates the Flutter tool's cache of binary artifacts.
  run                      Run your Flutter app on an attached device.
  screenshot               Take a screenshot from a connected device.
  stop                     Stop your Flutter app on an attached device.
  test                     Run Flutter unit tests for the current project.
  trace                    Start and stop tracing for a running Flutter app.
  upgrade                  Upgrade your copy of Flutter.
  version                  List or switch flutter versions.

Run "flutter help <command>" for more information about a command.
Run "flutter help -v" for verbose help output, including less commonly used options.

```
```

**Comment by aatikakhan** [comment]
i'm getting this error on ubuntu 19.04
can you guide me step by step


/home/aatikakhan/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_IN)
    • Flutter version 1.7.8+hotfix.4 at /home/aatikakhan/development/flutter
    • Framework revision 20e59316b8 (2 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /home/aatikakhan/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /home/aatikakhan/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.4)
    • Android Studio at /home/aatikakhan/android-studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.36.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.3.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by VictorsAlves** [comment]
estou com o mesmo erro. ainda não encontrei solução.

**Comment by yadavaby** [comment]
im getting this error, 
anyone solve it pls


Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

**Comment by aatikakhan** [comment]
Uninstall the flutter and dart plugin then update the IDE. After this install the plugins again.

**Comment by adywoohoo** [comment]
To fix :
1) Android toolchain - develop for Android devices (Android SDK version 29.0.0)
Open Android Studio > Configure > SDK Manager > Check boxes with desired API Level (this case 29) > Click Apply > OK

![flutter_fix](https://user-images.githubusercontent.com/55751607/65520099-9fd19600-df19-11e9-9cab-816f0fff6fbd.png)

2) Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
Go to your flutter installation folder > git bash > paste and run command : 
flutter doctor --android-licenses

3) Connected device
Open Android Studio > Configure > AVD Manager > Select Virtual Device (or create virtual device) > Run

![android_studio_device](https://user-images.githubusercontent.com/55751607/65520387-1078b280-df1a-11e9-962f-430169dcc0a9.png)

**Comment by rodrigordgfs** [comment]
How to fix:
I was heaving the following message

Doctor summary (to see all details, run flutter doctor -v):
_[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.592], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    **X Android SDK file not found: D:/SDK\build-tools\29.0.3\aapt.**
[√] Android Studio (version 3.5)
[√] VS Code (version 1.42.1)
[!] Connected device
    ! No devices available_

To solve it, I uninstalled the version in which he was saying not to find
![image](https://user-images.githubusercontent.com/32286127/74784487-c0aed500-5286-11ea-872a-5519d6092ddb.png)

After uninstalling and running the flutter doctor command, the error disappeared.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.592], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.42.1)
[!] Connected device
    ! No devices available

**Comment by Rodrigossff91** [comment]
Roda esse cara aqui

doctor --android-licenses

**Comment by tahiriabdo131** [comment]
good, it is worked for me

**Comment by tharun143** [comment]
[✓] Flutter (Channel stable, v0.0.0-unknown, on Linux, locale en_IN.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by collinsbigomba** [comment]
![IMG_20200326_160043_2](https://user-images.githubusercontent.com/49558020/77671776-20d91b00-6f99-11ea-94ce-e1216af73749.jpg)
Help
