### ISSUE TITLE
Firebase Auth Improvement: email format check before sign up.

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#34212]
Here's my situation:

When user sign up, I have a page to input email, if it's valid with my [`local regex email check`](https://github.com/dart-league/validators/blob/8334b3ffc2dee46de81fab749c70002f9d47d001/lib/validators.dart#L5), then it go to next page to input password with similar local regex check.

After that, I call `createUserWithEmailAndPassword` to get user.

I got error `ERROR_INVALID_EMAIL` with email: `aaa@aaa.a`.

What I want API improvement to see with my situation is :

- someplace to provide the email regex rule, or just email rule ?
- some api to added to valid email only in firebase server?

more detail on [stackoverflow](https://stackoverflow.com/questions/56537125/)

**Comment by mikhail-tokarev** [comment]
Hi @jerryzhoujw 
I see on the link you provided that your stackoverflow question has been answered
for more details you may check this documentation
https://firebase.google.com/docs/reference/security/database/regex.

If the issue persist, please post your  `flutter doctor -v`

**Comment by jerryzhoujw** [comment]
@mikhail-tokarev  the doc link you provide explained well enough.
