### ISSUE TITLE
"network error" crash when running flutter run, SocketException: OS Error: The semaphore timeout period has expired, errno = 121, address = clients2.google.com, port = 8855

### ISSUE THREAD

**Issue by fayzullayev** [flutter/flutter#34225]
a have this bug. What is the problem?

------------------------------------------------------------------------------------------

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.16299.15], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.4)
[√] Connected device (1 available)

-----------------------------------

flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Oops; flutter has exited unexpectedly.

Sending crash report to Google.

**Failed to send crash report due to a network error: SocketException: OS Error: The semaphore timeout period has expired.
, errno = 121, address = clients2.google.com, port = 8855**

**Comment by jonahwilliams** [comment]
Unfortunately no one got around to triaging this when it was filled, I'm sorry about that. In these cases, we can't really help unless logs and the stack trace are provided. If the flutter tool crashes, it should write out a file in the current working directory which could be uploaded to github. If I were to guess looking at what you've posted, something in the tool didn't handle a lack of network connectivity well and crashed - though it might have been fixed by now

**Comment by mamunur34** [comment]
This is what I'm seeing for 2 days. 
OS Error: The semaphore timeout period has expired.

, errno = 121, address = storage.googleapis.com, port = 3318

**Comment by eseidel** [comment]
FWIW, I've seen this issue in my own hobby usage of Dart (https://github.com/eseidel/space_traders/blob/4d9a5b6eccdaec3331b8d62cf33a6a702a204bc7/packages/cli/lib/logic.dart#L136) and we're getting reports of users encountering these when running Shorebird on the command line as well: https://github.com/shorebirdtech/shorebird/issues/790. I'm beginning to suspect it may be an issue stemming from Dart's networking implementation on Windows (not saying Dart is at-fault).  Given how much `flutter` tool is used on Windows I would expect we'd see lots of reports of these?  But maybe Flutter doesn't make a lot of network requests?  Would love any information others have found on this topic.
