### ISSUE TITLE
flutter doctor,  But  env: bash: No such file or directory 

### ISSUE THREAD

**Issue by zhangfangtaozft** [flutter/flutter#34222]
![image](https://user-images.githubusercontent.com/11926205/59257730-15666e80-8c69-11e9-8971-8b2edda9aa6c.png)

`echo $PATH`

`/Users/frank.zhang/flutter/bin`

`flutter doctor`

`env: bash: No such file or directory`

I have already done the corresponding configuration, but there is still an error in running the `flutter doctor`command. What should I do?

**Comment by zhangfangtaozft** [comment]
![image](https://user-images.githubusercontent.com/11926205/59260039-7728d780-8c6d-11e9-9181-c8bd00fbbff6.png)

The picture above shows what I displayed after opening the `/bin/flutter` file directly. It feels like there is a problem, but I did follow the tutorial.

**Comment by jonahwilliams** [comment]
It looks like you overwrote your PATH with only flutter, this won't work since you won't be able to find anything else.

See https://flutter.dev/docs/get-started/install/macos for instructions on how to add it to the PATH

**Comment by robinjohn** [comment]
Try the below and that should fix it:  

1. Clean build
``` 
flutter clean
```
2. Make the gradlew bin runnable in unix.
```
vim gradlew
:set fileformat=unix
:wq
```
3. Fix the flutter pub packages cache built from earlier session in windows
```
flutter pub cache repair
```

**Comment by steve2christ** [comment]
> env: bash: No such file or directory

you get this error message simply because the "/dev" folder is not in "/bin". It is directly in the "/flutter" folder so change your path this way:

export PATH="$PATH:[PATH_TO_FLUTTER_GIT_DIRECTORY]/flutter"
