### ISSUE TITLE
Rendering PDF stream

### ISSUE THREAD

**Issue by sk-aaludra** [flutter/flutter#34221]
Hi there, 

We are generating PDF (say invoice) in the server (node js) using jsreport libraries and from the Flutter app we wanted to download the pdf. Is there a way to do this? any help appreciated.

Regards
SK

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
