### ISSUE TITLE
[firebase_messaging] get device's apns token

### ISSUE THREAD

**Issue by Henry-Keys** [flutter/flutter#34223]
## Use case
At my company we're using firebase_messaging plugin to receive notifications on Android and it's doing fine. But we're using Azure Notification Hub on backend to do so. 

Azure Notification Hub selects the correct notification service (APNS or FCM) given the target device OS. Therefore, for iOS, devices need to be registered themselves in the backend with a APNS token. 

## Proposal
Provide a method in FirebaseMessaging class that allows the retrieval of the APNS token for iOS devices.

**Comment by nhwilly** [comment]
I, too am using ANH.

How are you planning to get the token on iOS in the meantime?

**Comment by Henry-Keys** [comment]
> I, too am using ANH.
> 
> How are you planning to get the token on iOS in the meantime?

Hi. We're thinking in a few options:
a) Fork firebase_messaging and implement this
b) Do Android/iOS code to handle notifications separately due to limitations that Flutter currently has with data messages ([see this issue](https://github.com/flutter/flutter/issues/32372))

**Comment by nhwilly** [comment]
Thanks. The sad thing is I had this all working great in Xamarin. Android, iOS and UWP.  All of it.  I switched to flutter and discovered some missing pieces, like this one.  

On iOS you literally create a entire separate project to get backgrounding working. In UWP you register some hooks in the OS or registry if I remember correctly.

I think I ended up always sending data messages and then showing local notifications, so I could manage rich content and a user interacting with the notification itself; buttons and localization and such.

I'd translate it, if I wasn't completely clueless about Dart, Kotlin.

**Comment by nhwilly** [comment]
I failed to think about how much more complex this will become when Flutter attempts to move to desktop environments, like Windows and MacOs.  Those environments are different.

It would seem the only universal way to handle this would be to have a stand alone(ish)  background app that would vary from platform to platform and communicated with or launched the flutter app with a standard communication method.  Ugh.

**Comment by marwfair** [comment]
I'm not familiar with Azure Notification Hub, but if it's similar to AWS's SNS, you just send all pushes as FCM. The firebase messaging plugin gives FCM tokens to both android and iOS devices, and your Firebase project is configured with APNS, so it will send your pushes to the correct device.

**Comment by nhwilly** [comment]
Oh, wow.

 So Google sends push to iOS devices, too?  That would be great.  

One less push service to deal with, maybe only one, period.

Depends on what they do with desktop and web I guess. 

Thanks.

**Comment by marwfair** [comment]
Yes sir! Firebase Messaging can send pushes to Android, iOS, and web, but I don't think this plugin supports Flutter web.

**Comment by Henry-Keys** [comment]
We ended up creating our own plugin that uses FCM on Android and APNS on iOS. It's far from perfect but works:
https://github.com/nextbss/flutter-push-notification

**Comment by mudi256** [comment]
> https://github.com/nextbss/flutter-push-notification

nothing found

**Comment by kroikie** [comment]
@Henry-Keys

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1058. Any further collaboration will be done there.

**Comment by Henry-Keys** [comment]
> 
> 
> > https://github.com/nextbss/flutter-push-notification
> 
> nothing found

Hey sorry for that. The project had to be removed due to business decisions made in the company I work for.
