### ISSUE TITLE
getBitmap broken due to not on main thread

### ISSUE THREAD

**Issue by hongnk** [flutter/flutter#34226]
I'm trying to record flutter view activities into a video by using `FlutterView.getBitmap()` in android. This used to work in flutter 1.2 but after upgrade now it breaks:
`java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: thread-xxx.`

Am I doing it wrong or what is alternative to capture flutter view to bitmap when it is not the main thread?

```
[√] Flutter (Channel master, v1.7.4-pre.38, on Microsoft Windows [Version
    10.0.17134.765], locale en-US)
    • Flutter version 1.7.4-pre.38 at C:\flutter
    • Framework revision 354ce1aa5a (15 hours ago), 2019-06-10 11:27:25 -0700
    • Engine revision e886d7b082
    • Dart version 2.3.2 (build 2.3.2-dev.0.1 7f146e431e)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)    • Android SDK at C:\Users\Hong\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Hong\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[√] VS Code, 64-bit edition (version 1.35.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (1 available)
    • EML L29 • UBV0218601007007 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by janmoppel** [comment]
Hello @hongnk !

Does the problem still persist in the latest stable version?

**Comment by hongnk** [comment]
Yes it still fails in latest flutter 1.9.1 stable channel.

More details:

I have a FlutterView running in main thread. Then in java code I created a new Thread(recordFunc()) in which I continuously call FlutterView.getBitmap() to capture it.

Error log: 

W/System.err( 7799): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-6
W/System.err( 7799): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:807)
W/System.err( 7799): 	at io.flutter.embedding.engine.FlutterJNI.getBitmap(FlutterJNI.java:795)
W/System.err( 7799): 	at io.flutter.view.FlutterView.getBitmap(FlutterView.java:657)
W/System.err( 7799): 	at com.example.drawapp.ViewRecorder$SurfaceTask.run(ViewRecorder.java:119)
W/System.err( 7799): 	at java.lang.Thread.run(Thread.java:784)

It works with no error if I reverted back to flutter 1.2

Apparently flutter code forces the call getBimap() only on main thread. But to record FlutterVIew it will only work if it is called from a different thread, otherwise it causes performance problem.

**Comment by iapicca** [comment]
Hi @hongnk 
can you please provide your `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by hongnk** [comment]
> Hi @hongnk
> can you please provide your `flutter run --verbose`
> together with a a minimal code sample to reproduce the problem
> thank you

I believe attributing flutterView.getBitmap() as [UiThread] is wrong, because it should run on a background thread to be able to capture image of main thread.

That's all about this issue, it's not really a coding bug. Anyway I will  find some time to prepare a sample in next few days.

**Comment by hongnk** [comment]
@iapicca 

flutter run --verbose output:
[fluter-output.txt](https://github.com/flutter/flutter/files/3833804/fluter-output.txt)
The errors are in few last lines

Sample code:
[flutter_view.zip](https://github.com/flutter/flutter/files/3833805/flutter_view.zip)
* This code is a copy of flutter_vew sample in flutter main repos. 
* Changes are in \android\app\src\main\java\com\example\view\MainActivity.java, line 92 to 113, to replace Android Increment function with a call to getBitmap()
* When running on device, just tap "+" on Android pane to see the error produced.

**Comment by chinmaygarde** [comment]
Triage: This is not really a regression because accessing the shell is only safe to do from the platform task runner. Earlier there was no warning when this threading rule was violated but now there is. Having said that, allowing callers to screenshot the view hierarchy from a background thread seems doable

cc @xster

**Comment by xster** [comment]
Like most standard android.view.View APIs, we expect most APIs on the FlutterView to be callable only from the main thread.

**Comment by tolotrasamuel** [comment]
Did you solve this issue ? I am also trying to record a video but getBitmap is blocking the UI

**Comment by tolotrasamuel** [comment]
@xster this issue is not about changing the getBitmap to be able to run outside UiThread.
It is about creating a new API that allow recording bitmap continuously in a background thread in order to make a video.

Currently, getBitmap is blocking the UI thread, so you can't make video recording
