### ISSUE TITLE
[web][upstream]: LocaleListResolutionCallback missing in app.dart

### ISSUE THREAD

**Issue by NicolasDionB** [flutter/flutter#34237]
I was trying to integrate the localization code in my app and so far it's working great. Only thing I found is that the LocaleListResolutionCallback definition is missing in app.dart. It exists in the Flutter version but not in the web version. I found the related LocaleResolutionCallback is defined, which is odd.

So I'm just reporting this, maybe it's just something that fell in the void somewhere but just saying it's missing and I don't quite understand why.

**Comment by mdebbar** [comment]
`LocaleListResolutionCallback` was added in https://github.com/flutter/flutter_web/commit/33a7316e385354066b2b4968516fe487a6b767e9.
