### ISSUE TITLE
simple_permissions/simple_permissions.modulemap' not found

### ISSUE THREAD

**Issue by Allan-Nava** [flutter/flutter#34231]
```
6 warnings generated.
    <unknown>:0: error: module map file '/Users/ies/Desktop/work/ntop/ivo_lite/build/ios/Release-iphoneos/simple_permissions/simple_permissions.modulemap' not found
    <unknown>:0: error: module map file '/Users/ies/Desktop/work/ntop/ivo_lite/build/ios/Release-iphoneos/simple_permissions/simple_permissions.modulemap' not found
    <unknown>:0: error: missing required module 'SwiftShims'
```

**Comment by mikhail-tokarev** [comment]
Hi @Allan-Nava 
can you please describe the issue in detail
and provide your `flutter doctor -v`

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
