### ISSUE TITLE
Plugins pull requests stopped passing checks after merge with upstream

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#34238]
My both PR's (1702 1719) stopped passing checks today after I merged upstream master to my forked repo.
How do I run the checks locally?
https://github.com/flutter/plugins/pull/1719
https://github.com/flutter/plugins/pull/1702

**Comment by duzenko** [comment]
CONTRIBUTING.md says

> 
> To run the integration tests:
> 
> ```
> cd example
> flutter drive test/<name_of_plugin>.dart

However I don't see `test` folder under \packages\google_maps_flutter

**Comment by TahaTesser** [comment]
Hi @duzenko 
Are you still experiencing this issue?
Thank you

**Comment by duzenko** [comment]
Yes

**Comment by stuartmorgan** [comment]
Closing, as the documentation has since been updated and reflects the current directory naming.
