### ISSUE TITLE
GLSL compilation error

### ISSUE THREAD

**Issue by butterflydesign** [flutter/flutter#34239]
I am only performing basic firebase auth

Here's the output

W/FA      (29918): setCurrentScreen cannot be called with the same class and name
D/skia    (29918): GLSL compilation error
D/skia    (29918): ----------------------
D/skia    (29918): GLSL:
D/skia    (29918):    1 #version 300 es
D/skia    (29918):    2
D/skia    (29918):    3 #extension GL_EXT_shader_framebuffer_fetch : require
D/skia    (29918):    4 precision mediump float;
D/skia    (29918):    5 inout mediump vec4 sk_FragColor;
D/skia    (29918):    6 uniform mediump vec4 uleftBorderColor_Stage1_c0;
D/skia    (29918):    7 uniform mediump vec4 urightBorderColor_Stage1_c0;
D/skia    (29918):    8 uniform sampler2D uTextureSampler_0_Stage1;
D/skia    (29918):    9 in mediump vec4 vQuadEdge_Stage0;
D/skia    (29918):   10 in mediump vec4 vinColor_Stage0;
D/skia    (29918):   11 in highp vec2 vTransformedCoords_0_Stage0;
D/skia    (29918):   12 void main() {
D/skia    (29918):   13     mediump vec4 outputCoverage_Stage0;
D/skia    (29918):   14     {
D/skia    (29918):   15         mediump float edgeAlpha;
D/skia    (29918):   16         mediump vec2 duvdx = dFdx(vQuadEdge_Stage0.xy);
D/skia    (29918):   17         mediump vec2 duvdy = -dFdy(vQuadEdge_Stage0.xy);
D/skia    (29918):   18         if (vQuadEdge_Stage0.z > 0.0 && vQuadEdge_Stage0.w > 0.0) {
D/skia    (29918):   19             edgeAlpha = min(min(vQuadEdge_Stage0.z, vQuadEdge_Stage0.w) + 0.5, 1.0);
D/skia    (29918):   20         } else {
D/skia    (29918):   21             mediump vec2 gF = vec2((2.0 * vQuadEdge_Stage0.x) * duvdx.x - duvdx.y, (2.0 * vQuadEdge_Stage0.x) * duvdy.x - duvdy.y);
D/skia    (29918):   22             edgeAlpha = vQuadEdge_Stage0.x * vQuadEdge_Stage0.x - vQuadEdge_Stage0.y;
D/skia    (29918):   23             edgeAlpha = clamp(0.5 - edgeAlpha / length(gF), 0.0, 1.0);
D/skia    (29918):   24         }
D/skia    (29918):   25         outputCoverage_Stage0 = vec4(edgeAlpha);
D/skia    (29918):   26     }
D/skia    (29918):   27     mediump vec4 output_Stage1;
D/skia    (29918):   28     {
D/skia    (29918):   29         mediump vec4 _child0;
D/skia    (29918):   30         {
D/skia    (29918):   31             mediump vec4 _child1_c0;
D/skia    (29918):   32             {
D/skia    (29918):   33                 mediump float t = vTransformedCoords_0_Stage0.x + 1.0000000000000001e-05;
D/skia    (29918):   34                 _child1_c0 = vec4(t, 1.0, 0.0, 0.0);
D/skia    (29918):   35             }
D/skia    (29918):   36             mediump vec4 t = _child1_c0;
D/skia    (29918):   37             if (t.x < 0.0) {
D/skia    (29918):   38                 _child0 = uleftBorderColor_Stage1_c0;
D/skia    (29918):   39             } else if (t.x > 1.0) {
D/skia    (29918):   40                 _child0 = urightBorderColor_Stage1_c0;
D/skia    (29918):   41             } else {
D/skia    (29918):   42                 mediump vec4 _child0_c0;
D/skia    (29918):   43                 mediump vec4 _childInput_c0_c1 = t;
D/skia    (29918):   44                 {
D/skia    (29918):   45                     mediump vec2 coord = vec2(_childInput_c0_c1.x, 0.5);
D/skia    (29918):   46                     _child0_c0 = texture(uTextureSampler_0_Stage1, coord).xyzw;
D/skia    (29918):   47                 }
D/skia    (29918):   48                 _child0 = _child0_c0;
D/skia    (29918):   49             }
D/skia    (29918):   50             {
D/skia    (29918):   51                 _child0.xyz *= _child0.w;
D/skia    (29918):   52             }
D/skia    (29918):   53         }
D/skia    (29918):   54         output_Stage1 = _child0;
D/skia    (29918):   55     }
D/skia    (29918):   56     {
D/skia    (29918):   57         mediump vec4 _dstColor = sk_FragColor;
D/skia    (29918):   58         sk_FragColor.w = output_Stage1.w + (1.0 - output_Stage1.w) * _dstColor.w;
D/skia    (29918):   59         sk_FragColor.xyz = ((1.0 - output_Stage1.w) * _dstColor.xyz + (1.0 - _dstColor.w) * output_Stage1.xyz) + output_Stage1.xyz * _dstColor.xyz;
D/skia    (29918):   60         sk_FragColor = outputCoverage_Stage0 * sk_FragColor + (vec4(1.0) - outputCoverage_Stage0) * _dstColor;
D/skia    (29918):   61     }
D/skia    (29918):   62 }
D/skia    (29918):   63
D/skia    (29918): Errors:
D/skia    (29918): ERROR: 0:3: 'GL_EXT_shader_framebuffer_fetch' : extension is not supported
D/skia    (29918): ERROR: 0:5: 'inout' : syntax error
D/skia    (29918):
D/skia    (29918): GLSL compilation error
D/skia    (29918): ----------------------
D/skia    (29918): GLSL:
D/skia    (29918):    1 #version 300 es
D/skia    (29918):    2
D/skia    (29918):    3 #extension GL_EXT_shader_framebuffer_fetch : require
D/skia    (29918):    4 precision mediump float;
D/skia    (29918):    5 inout mediump vec4 sk_FragColor;
D/skia    (29918):    6 uniform mediump vec4 uleftBorderColor_Stage1_c0;
D/skia    (29918):    7 uniform mediump vec4 urightBorderColor_Stage1_c0;
D/skia    (29918):    8 uniform sampler2D uTextureSampler_0_Stage1;
D/skia    (29918):    9 in mediump vec4 vQuadEdge_Stage0;
D/skia    (29918):   10 in mediump vec4 vinColor_Stage0;
D/skia    (29918):   11 in highp vec2 vTransformedCoords_0_Stage0;
D/skia    (29918):   12 void main() {
D/skia    (29918):   13     mediump vec4 outputCoverage_Stage0;
D/skia    (29918):   14     {
D/skia    (29918):   15         mediump float edgeAlpha;
D/skia    (29918):   16         mediump vec2 duvdx = dFdx(vQuadEdge_Stage0.xy);
D/skia    (29918):   17         mediump vec2 duvdy = -dFdy(vQuadEdge_Stage0.xy);
D/skia    (29918):   18         if (vQuadEdge_Stage0.z > 0.0 && vQuadEdge_Stage0.w > 0.0) {
D/skia    (29918):   19             edgeAlpha = min(min(vQuadEdge_Stage0.z, vQuadEdge_Stage0.w) + 0.5, 1.0);
D/skia    (29918):   20         } else {
D/skia    (29918):   21             mediump vec2 gF = vec2((2.0 * vQuadEdge_Stage0.x) * duvdx.x - duvdx.y, (2.0 * vQuadEdge_Stage0.x) * duvdy.x - duvdy.y);
D/skia    (29918):   22             edgeAlpha = vQuadEdge_Stage0.x * vQuadEdge_Stage0.x - vQuadEdge_Stage0.y;
D/skia    (29918):   23             edgeAlpha = clamp(0.5 - edgeAlpha / length(gF), 0.0, 1.0);
D/skia    (29918):   24         }
D/skia    (29918):   25         outputCoverage_Stage0 = vec4(edgeAlpha);
D/skia    (29918):   26     }
D/skia    (29918):   27     mediump vec4 output_Stage1;
D/skia    (29918):   28     {
D/skia    (29918):   29         mediump vec4 _child0;
D/skia    (29918):   30         {
D/skia    (29918):   31             mediump vec4 _child1_c0;
D/skia    (29918):   32             {
D/skia    (29918):   33                 mediump float t = vTransformedCoords_0_Stage0.x + 1.0000000000000001e-05;
D/skia    (29918):   34                 _child1_c0 = vec4(t, 1.0, 0.0, 0.0);
D/skia    (29918):   35             }
D/skia    (29918):   36             mediump vec4 t = _child1_c0;
D/skia    (29918):   37             if (t.x < 0.0) {
D/skia    (29918):   38                 _child0 = uleftBorderColor_Stage1_c0;
D/skia    (29918):   39             } else if (t.x > 1.0) {
D/skia    (29918):   40                 _child0 = urightBorderColor_Stage1_c0;
D/skia    (29918):   41             } else {
D/skia    (29918):   42                 mediump vec4 _child0_c0;
D/skia    (29918):   43                 mediump vec4 _childInput_c0_c1 = t;
D/skia    (29918):   44                 {
D/skia    (29918):   45                     mediump vec2 coord = vec2(_childInput_c0_c1.x, 0.5);
D/skia    (29918):   46                     _child0_c0 = texture(uTextureSampler_0_Stage1, coord).xyzw;
D/skia    (29918):   47                 }
D/skia    (29918):   48                 _child0 = _child0_c0;
D/skia    (29918):   49             }
D/skia    (29918):   50             {
D/skia    (29918):   51                 _child0.xyz *= _child0.w;
D/skia    (29918):   52             }
D/skia    (29918):   53         }
D/skia    (29918):   54         output_Stage1 = _child0;
D/skia    (29918):   55     }
D/skia    (29918):   56     {
D/skia    (29918):   57         mediump vec4 _dstColor = sk_FragColor;
D/skia    (29918):   58         sk_FragColor.w = output_Stage1.w + (1.0 - output_Stage1.w) * _dstColor.w;
D/skia    (29918):   59         sk_FragColor.xyz = ((1.0 - output_Stage1.w) * _dstColor.xyz + (1.0 - _dstColor.w) * output_Stage1.xyz) + output_Stage1.xyz * _dstColor.xyz;
D/skia    (29918):   60         sk_FragColor = outputCoverage_Stage0 * sk_FragColor + (vec4(1.0) - outputCoverage_Stage0) * _dstColor;
D/skia    (29918):   61     }
D/skia    (29918):   62 }
D/skia    (29918):   63
D/skia    (29918): Errors:
D/skia    (29918): ERROR: 0:3: 'GL_EXT_shader_framebuffer_fetch' : extension is not supported
D/skia    (29918): ERROR: 0:5: 'inout' : syntax error
D/skia    (29918):

**Comment by butterflydesign** [comment]
pubspec.yaml

Here's my pubspec.yaml

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  firebase_core: ^0.3.4
  firebase_analytics: ^2.1.1+3

  cloud_firestore: ^0.10.1

  firebase_auth: ^0.8.4+5
  google_sign_in: ^4.0.1+1

  rxdart: ^0.21.0
  provider: 2.0.0+1
  font_awesome_flutter: 8.4.0

**Comment by butterflydesign** [comment]
Flutter Doctor

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.7.4-pre.60, on Mac OS X 10.14.5 18F132, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
[✓] VS Code (version 1.35.0)
[✓] Connected device (2 available)

• No issues found!

**Comment by RedBrogdon** [comment]
Did you end up solving this on your own?

**Comment by bratay** [comment]
My console looks the same when I run an animation.

My flutter doctor:
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/brandentaylor/Documents/flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/brandentaylor/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone Xʀ                 • D6CC996C-6E41-4229-9AFB-9ECF60370968 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
------------------------------
MyPubspec.yaml:
name: isolate_example
description: A Flutter sample to demonstrate isolates
version: 1.0.0+1

environment:
 sdk: ">=2.1.0 <3.0.0"

dependencies:
 flutter:
   sdk: flutter
 cupertino_icons: ^0.1.2

dev_dependencies:
 flutter_test:
   sdk: flutter

flutter:
 uses-material-design: true



------------------------------------
The animation that causes the error:

class smoothAnimationWidget extends StatefulWidget {
  @override
  smoothAnimationWidgetState createState() => smoothAnimationWidgetState();
}

class smoothAnimationWidgetState extends State<smoothAnimationWidget>
    with TickerProviderStateMixin {
  AnimationController _controller;
  var borderRadius;
  var transitionTween;

  @override
  void initState() {
    super.initState();

    _controller =
    AnimationController(duration: const Duration(seconds: 1), vsync: this)
      ..addStatusListener((status) {
        if (status == AnimationStatus.completed) {
          _controller.reverse();
        } else if (status == AnimationStatus.dismissed) {
          _controller.forward();
        }
      });

    borderRadius = BorderRadiusTween(
      begin: BorderRadius.circular(100.0),
      end: BorderRadius.circular(0.0),
    ).animate(
      CurvedAnimation(
        parent: _controller,
        curve: Curves.linear,
      ),
    );

    _controller.forward();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: borderRadius,
      builder: (BuildContext context, Widget child) {
        return Center(
            child: Container(
              child: new FlutterLogo(
                size: 200,
              ),
              alignment: Alignment.bottomCenter,
              width: 350,
              height: 200,
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topLeft,
                  colors: [Colors.blueAccent, Colors.redAccent], // whitish to gray
                ),
                borderRadius: borderRadius.value,
              ),
            ));
      },
    );
  }
}

**Comment by amitkhairnar44** [comment]
This issue is in Android Emulator. I got the same issue and it got fixed by changing OpenGL ES API level to OpenGL ES 1.1/2.0 in Emulator settings

**Comment by ssg127** [comment]
> @butterflydesign @bratay This issue comes if we use Android Emulator. I got the same issue and it got fixed by changing OpenGL ES API level to OpenGL ES 1.1/2.0 in Emulator settings
> And this should fix #17102 issue too

How did you do it? I'm using Android Studio emulator but i can't found any option to change it.

**Comment by butterflydesign** [comment]
I closed this because the issue went away mysteriously and I could not reproduce it. Thinking back I did update my emulators. Thanks for the answers guys.

**Comment by amitkhairnar44** [comment]
@ssg127 See this image : After clicking **Settings** click advanced and there you'll find the option
![thumbnail-emulator_2x](https://user-images.githubusercontent.com/18245511/59777410-3b77b880-92d2-11e9-9a4c-4c6860078b55.png)
