### ISSUE TITLE
[web]Flutter For Web Uncaught Instance of 'minified:p'

### ISSUE THREAD

**Issue by wedcel** [flutter/flutter#34235]
When I debug the flutter for web program in chrome, if I choose Android, I will report this error, but if I choose iOS, this problem will not occur. Why is this? 
   The following picture is a concrete performance, in order to facilitate debugging, I used whistle to proxy the web page to a domain name for convenient mobile phone access.

client.js:367 Uncaught Instance of 'minified:p'
    at Object.b (https://wed.ww.com/webdev/src/serve/injected/client.js:367:3)
    at ng.$0 (https://wed.ww.com/webdev/src/serve/injected/client.js:5423:20)
    at Object.uw (https://wed.ww.com/webdev/src/serve/injected/client.js:1267:5)
    at kC.uB (https://wed.ww.com/webdev/src/serve/injected/client.js:1269:7)
    at lB.$1 (https://wed.ww.com/webdev/src/serve/injected/client.js:4843:3)
    at v6 (https://wed.ww.com/webdev/src/serve/injected/client.js:441:17)
    at MutationObserver.<anonymous> (https://wed.ww.com/webdev/src/serve/injected/client.js:449:51)

![image](https://user-images.githubusercontent.com/3982317/59271450-70f32500-8c86-11e9-9717-55fd325cd715.png)
![image](https://user-images.githubusercontent.com/3982317/59271464-76e90600-8c86-11e9-87e7-ddee0dde1f60.png)
![image](https://user-images.githubusercontent.com/3982317/59271506-8bc59980-8c86-11e9-8d5f-10edd7a2d613.png)

**Comment by wedcel** [comment]
If I deploy it in tomcat, there won't be this problem.

**Comment by vsmenon** [comment]
@jakemac53 @grouma - this looks like the hot-reload logic.  Should this be opened on build or webdev?

**Comment by grouma** [comment]
Yes. This looks to be a `WebDev` bug. Please open up an issue there. I'll see if I can reproduce this.

**Comment by grouma** [comment]
I can't seem to reproduce this with the simple Spinning Square example in Flutter Web. I'm using Chrome 75 on Linux with `WebDev` version `2.1.0`. I select the `Galaxy S5` window constraints and can open the Flutter Inspector / perform a manual Hot Restart. @wedcel can you provide exact reproduction steps?

**Comment by liaoweiguo** [comment]
reproduce on win10.

**Comment by grouma** [comment]
I am unable to reproduce this using Chrome 75 on Windows 10 with the latest `WebDev` version `2.1.0`. Please upgrade. If you can reproduce please give exact reproduction steps with sample code.

**Comment by wedcel** [comment]
This problem is still

**Comment by step4** [comment]
Steps to reproduce on windows 10:
```bash
choco install dart-sdk
pub global activate webdev
pub global activate stagehand
mkdir angular_dart_web
cd angular_dart_web
stagehand web-angular
pub get
webdev serve
```

**Comment by wedcel** [comment]
@grouma  
Please pay attention to the problem here.

**Comment by vsmenon** [comment]
I believe @grouma disabled minification on client.js.  If you upgrade to the latest and still see this problem, do you get a different stack trace?

**Comment by grouma** [comment]
This looks like a duplicate of: https://github.com/dart-lang/build/issues/2337

Yesterday I did publish a new version of `webdev` (`2.3.0`). These errors should no longer be minified. Please run with the latest to ensure we are hitting the same error.

In this comment I outline the issue:
https://github.com/dart-lang/build/issues/2337#issuecomment-513969122

Check your network panel and see if the `/$sseHandler` and `/main.digests` requests are going through properly.

**Comment by grouma** [comment]
@step4 I tried your reproduction steps and wasn't able to hit the problem. This is with the latest `webdev` version `2.3.0`. Please take a look at this comment and see if it applies to you as well: https://github.com/flutter/flutter/issues/34235#issuecomment-514277048
