### ISSUE TITLE
Cloud Firestore does not support combining multiple document pagination methods

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#34233]
Originally brought to my attention by https://github.com/flutter/plugins/pull/1591#issuecomment-492601295.

Essentially, you cannot use any combination of `startAtDocument`, `startAfterDocument`, `endAtDocument` & `endBeforeDocument`, i.e. you can only use one of them at most. Ideally, you should be able to combine any `start..` method with any `end...` method.

The issue is that all of the four methods add an implicit `orderBy` and the same implicit `orderBy` cannot appear twice first of all and also `Invalid query. You must not call Query.startAt() or Query.startAfter() before calling Query.orderBy()`.

The way I interpreted the problem, this should be straight forward to fix and I will take a look at doing so.

**Comment by RollyPeres** [comment]
Related to: https://github.com/flutter/flutter/issues/33212

**Comment by creativecreatorormaybenot** [comment]
@RollyPeres Thanks for mentioning. It is actually a duplicate. I was just not aware before. https://github.com/flutter/plugins/pull/1722 will fix this.

**Comment by creativecreatorormaybenot** [comment]
Duplicate of #33212.

**Comment by creativecreatorormaybenot** [comment]
duplicate of #33212
