### ISSUE TITLE
App not running in Android Device

### ISSUE THREAD

**Issue by kanishqgupta** [flutter/flutter#34232]
Here are the logs that I got - 

```
Launching lib\main.dart on ASUS X01BDA in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Failed to transform file 'flutter-x86.jar' to match attributes {artifactType=processed-jar} using transform IdentityTransform
   > Transform output file D:\AndroidProjects\flutter\heritage\build\app\intermediates\flutter\flutter-x86.jar does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

I also tried -flutter clean, but it also didn't work.
Using Android SDK Platform Tools 29.0.1 on Android Studio 3.4.1. The device I am using is Asus Zenfone Max pro m2 running on Android 9.0.

**Comment by BondarenkoStas** [comment]
@kanishqgupta Please provide ```flutter doctor -v``` output

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
