### ISSUE TITLE
Open / control DraggableScrollableSheet programmatically

### ISSUE THREAD

**Issue by tp** [flutter/flutter#34242]
## Use case

We have a view similar to this:

```
------------------------------
||        AppBar            ||
------------------------------
||                          ||
||                          ||
||                          ||
||        Vertical          ||
||        Scroll            ||
||        View              ||
||                          ||
||                          ||
------------------------------
|| DraggableScrollableSheet ||
==============================
```

Initially the center scroll is the primary UI element. But since it has only a handful of elements, it's likely to be scrolled to completion.

## Proposal

What I would like to to in the case the center scroll view starts "over-scrolling", is to bring up the `DraggableScrollableSheet` (tracking the exact amount of pixels over-scrolled).

Currently there does not seem to be any API do to that, only for the reverse, listening to Scroll Notifications bubbling up (which I plan on using to adapt the `AppBar`).

My current approach to be able to move the `DraggableScrollableSheet` is in a fork where instead of an `initialChildSize` I pass a `currentExtent` (`ValueNotifier<double>`) which then gets passed to the internal `_DraggableSheetExtent` class.

That way I can set the scroll amount from the outside (although I haven't tried it in an animated and interruptible fashion yet. I would expect some issues in the details with that).

Do you think this is a reasonable request? Is there a different kind of API that would be more appropriate / Flutter-like?

cc @dnfield

**Comment by dnfield** [comment]
I think you want a just a sliver list...

**Comment by tp** [comment]
@dnfield I looked into those as well, but would always get hung up on the very custom app bar behavior, instead of some general approach.

What I want in the above example is definitely the visuals of the `DraggableScrollableSheet` going over the "Vertical Scroll View" (which is a fixed vertical `PageView`).

I don't think that effect is supported with the `SliverList`, as I only saw example of "one after another" and never in 2D space. (But maybe I am mistaken here.)

**Comment by dnfield** [comment]
Got it.

Have you considered how this would work for a visually impaired user?  One of the more challenging parts about the draggable sheet stuff is making it accessible - I'm still not entirely thrilled with how that would work to be honest, but I think it's workable.

Anyway, an option you may have is to listen to your scroll controller in the body of your view, and when it reaches its max you could start rebuilding the scrollable sheet with an altered initialChildSize.  Does that make sense?

**Comment by tp** [comment]
> Anyway, an option you may have is to listen to your scroll controller in the body of your view, and when it reaches its max you could start rebuilding the scrollable sheet with an altered initialChildSize. Does that make sense?

Yes, that sounds like it could work. I'll give it a try.

**Comment by VladyslavBondarenko** [comment]
@tp 
Please follow up on https://github.com/flutter/flutter/issues/45009,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
