### ISSUE TITLE
[web]: Could not find a file named "pubspec.yaml" @quiver-2.0.2

### ISSUE THREAD

**Issue by 4F2E4A2E** [flutter/flutter#34246]
Hi there! Thank you so much for this great project, I am very excited about it.  
I am not able to run the default flutter template project (`flutter create`) for the web.  

Please notice that `quiver 2.0.3` got installed instead of `quiver 2.0.2` as stated in the error message.
 
Those tryouts did not solve the problem:  

- Reinstalling  
- symbolic linking .pub-cache folder  
- changing env variables
- running `flutter pub cache repair`  
- https://github.com/flutter/flutter/issues/32033#issuecomment-489255424  
- https://github.com/fluttercommunity/flutter_launcher_icons/issues/50#issuecomment-442228839  
- https://github.com/fluttercommunity/flutter_launcher_icons/issues/50#issuecomment-450067269  

### error
```bash
$ webdev build                               
webdev could not run for this project.
Could not find a file named "pubspec.yaml" in "/home/john/.pub-cache/hosted/pub.dartlang.org/quiver-2.0.2".
``` 

### ENV Variables: 
```
export PATH="$PATH:/opt/google/flutter/bin"
export PATH="$PATH:/opt/google/flutter/bin/cache/dart-sdk/bin"
export PATH="$PATH":"/opt/google/flutter/.pub-cache/bin"
```

### flutter doctor -v 
```           
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /opt/google/flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/doe/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /snap/android-studio/76/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Android Studio (version 3.4)
    • Android Studio at /snap/android-studio/76/android-studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[!] Android Studio (version 3.3)
    • Android Studio at /snap/android-studio/73/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /snap/intellij-idea-ultimate/148
    • Flutter plugin version 36.0.4
    • Dart plugin version 191.7830

[!] VS Code (version 1.34.0)
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.

```
### webdev install
```
flutter pub global activate webdev
Package webdev is currently active at version 2.0.7.
Resolving dependencies...
+ args 1.5.2
+ async 2.2.0
+ browser_launcher 0.1.2
+ build_daemon 1.0.0
+ built_collection 4.2.2
+ built_value 6.6.0
+ charcode 1.1.2
+ codemirror 0.5.6+5.47.0
+ collection 1.14.11
+ convert 2.1.1
+ crypto 2.0.6
+ devtools 0.0.19 (0.1.1 available)
+ devtools_server 0.1.2
+ dwds 0.3.2
+ fixnum 0.10.9
+ http 0.12.0+2
+ http_multi_server 2.1.0
+ http_parser 3.1.3
+ intl 0.15.8
+ io 0.3.3
+ js 0.6.1+1
+ json_annotation 2.4.0
+ logging 0.11.3+2
+ matcher 0.12.5
+ meta 1.1.7
+ mime 0.9.6+3
+ octicons_css 0.0.1
+ package_config 1.0.5
+ package_resolver 1.0.10
+ path 1.6.2
+ pedantic 1.7.0
+ platform_detect 1.3.5
+ plotly_js 0.0.1
+ polymer_css 0.0.1
+ pool 1.4.0
+ primer_css 0.0.2
+ pub_semver 1.4.2
+ pubspec_parse 0.1.4
+ quiver 2.0.3
+ rxdart 0.21.0 (0.22.0 available)
+ shelf 0.7.5
+ shelf_proxy 0.1.0+6
+ shelf_static 0.2.8
+ shelf_web_socket 0.2.3
+ source_maps 0.10.8
+ source_span 1.5.5
+ split 0.0.2
+ sse 2.0.2
+ stack_trace 1.9.3
+ stream_channel 2.0.0
+ stream_transform 0.0.19
+ string_scanner 1.0.4
+ term_glyph 1.1.0
+ typed_data 1.1.6
+ uuid 2.0.1
+ vm_service_lib 3.15.1+1 (3.17.0+1 available)
+ watcher 0.9.7+10
+ web_socket_channel 1.0.13
+ webdev 2.0.7
+ webkit_inspection_protocol 0.4.0
+ yaml 2.1.15
Precompiling executables...
Precompiled webdev:webdev.
Installed executable webdev.
Activated webdev 2.0.7.
```

**Comment by jonahwilliams** [comment]
I would try deleting the directory `/home/john/.pub-cache/hosted/pub.dartlang.org/quiver-2.0.2` to force it to be re-downloaded.

**Comment by 4F2E4A2E** [comment]
Did not work and this directory does not exist under the user home directory.

**Comment by jonahwilliams** [comment]
I wonder if this is caused by running webdev over a regular flutter project. Could you try using it following the setup in https://github.com/flutter/flutter_web ? The web implementation is still in a technical preview and the tooling doesn't work with upstream flutter

**Comment by 4F2E4A2E** [comment]
Maybe I do not understand something here, but is this not a regular project. I’ve created it with flutter. 

Can you describe which steps and commands exactly I should go through? It would be great. This problem seams to come back alive many times. 

The steps I took are in the description.

**Comment by jonahwilliams** [comment]
Web is not yet a regular project, it exists separate from flutter currently in the flutter_web repo, and has different tooling. The default app made by `fluter create` shouldn't work with web.

> Can you describe which steps and commands exactly I should go through?

The steps are described in detail on the README of the flutter_web repo that I linked.

**Comment by 4F2E4A2E** [comment]
>Web is not yet a regular project
I understand that now. 

We will wait for the regular release in the main flutter project.

Thank you.

**Comment by robertgol** [comment]
@4F2E4A2E If you have a standard flutter project I advise you to read [this great article](https://medium.com/flutter-community/migrate-your-flutter-app-to-flutter-web-4bd3c9b3e81d). It helped me to run my Android app on the web. :)

I had the same problem as you but with package `shelf_static-0.2.8`. I managed to run my project using a modified command as described in this article: `flutter packages pub global run webdev <command>`

Cheers,
Robert

**Comment by mikhail-tokarev** [comment]
Hi @4F2E4A2E 
are you still experiencing this issue with the latest version of Flutter?
If so please reply attaching your `flutter doctor -v`

**Comment by NagashreeBhat** [comment]
I could not fix the issue by `flutter pub cache repair ` but I installed protobuf manually by `pub get`, you can also use `flutter pub get`. This adds the protobuf in the required path. Now I could run `webdev build` successfully

**Comment by 4F2E4A2E** [comment]
> Hi @4F2E4A2E
> are you still experiencing this issue with the latest version of Flutter?
> If so please reply attaching your `flutter doctor -v`

Hi there and sorry for being so late whith the response.

I did install from scratch on macos catalina, using the dev channel as described [1]. 
All green and works like a charm now, congratulations on this great release!

Only one thing I must first google about is the favicon-error: 
![image](https://user-images.githubusercontent.com/64590/69071368-11195b00-0a2a-11ea-8bd8-72e283e7786d.png)

Any hint or link is of course welcome.

Cocoapos was a pain, but homebrew did - as in many times - the job.

1: https://flutter.dev/docs/get-started/web

**Comment by iapicca** [comment]
Hi @4F2E4A2E 
I'm glad that you solved the issue,
for the error you are describing please open a separate issue
providing your updated  `flutter doctor -v`
Thank you

**Comment by KOSNOWMAN** [comment]
In my case, I solved this problem using comment in pubspec.yaml file
....
#flutter_firebase_ui:
#  path: ../
....

It seems to problem "flutter_firebase_ui" package
