### ISSUE TITLE
when flutter will support the nine patch img ?

### ISSUE THREAD

**Issue by moonljt521** [flutter/flutter#34240]
when flutter will support the nine patch img ?

[✓] Flutter (Channel master, v1.3.7-pre.1, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 1.3.7-pre.1 at /Users/moon/Documents/sdk/flutter
    • Framework revision c10b3e8cdc (9 weeks ago), 2019-04-08 16:48:30 +0800
    • Engine revision 4f54a1dd94
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 7c70ab1817)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/moon/Library/Android/sdk
    • Android NDK at /Users/moon/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/moon/Library/Android/sdk/platform-tools
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • MI 5s Plus • 95a23c00 • android-arm64 • Android 8.0.0 (API 26)

**Comment by Hixie** [comment]
Nine-patch images are supported. See the `centerSlice` argument of `paintImage`.

**Comment by Hixie** [comment]
(Also supported on `DecorationImage`.)
