### ISSUE TITLE
[android_alarm_manager] What does the parameter wakeup do?

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#34254]
Both `oneShot()` and `periodic()` methods have the parameter `wakeup`. According to the documentation:

> If `wakeup` is passed as `true`, the device will be woken up when the alarm fires. If `wakeup` is false (the default), the device will not be woken up to service the alarm.

I don't think this is very clear. What does "the device will be woken up" mean in this context? I interpret this as "the device's screen is going to turn on", however I ran some code with `wakeup` set to `true`, but could not notice any particular behaviour.

**Comment by stuartmorgan** [comment]
Closing as `android_alarm_manager` is deprecated in favor of [`android_alarm_manager_plus`](https://pub.dev/packages/android_alarm_manager_plus).
