### ISSUE TITLE
Fix deprecations in Metal build

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#34256]
The Metal build requires targetting a higher iOS platform. Because of this, many items that we have in there get marked as errors (due to the `-Werror` flag).

We should either use availability guards or preprocessor macros to make the Metal build work without suppressing errors/warnings, or we should get the Metal build to target iOS 8.0 (which would require help from Skia).

A temporary work around for this is to comment out the `-Werror` flag in build/config/compiler/BUILD.gn

/cc @cbracken @chinmaygarde @gaaclarke

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/issues/33079

**Comment by gaaclarke** [comment]
Who is going to handle the runtime check to see whether to use the OpenGL renderer or Metal renderer?  Skia or Flutter?

There are a few ways to skin this cat but I'd recommend making the code that is doing the runtime check target the lower target (iOS 8) then create a separate static library that targets iOS 11 for the metal code.  Link it in and selectively run it depending on the runtime check.

**Comment by chinmaygarde** [comment]
Tracked in https://github.com/flutter/flutter/issues/41807
