### ISSUE TITLE
Refactor foundation.dart to be dart:ui agnostic

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#34263]
(Related to https://github.com/flutter/flutter/issues/29234)

There are two dependencies on dart:ui types within foundation.dart:

1. The VoidCallback type, which is exported from basic_types.dart
2. Window, which is part of a larger flutter/ui specific dependency on the binding class.

To handle the former case:

1. Introduce a VoidCallback type into the dart_sdk into dart:core. This would allow to remove the re-export from basic_types without it becoming a breaking change. dartui would still be able to use VoidCallback.

Increasing the API surface of dart:core is probably not desirable in general, though the contract of VoidCallback is fairly trivial. There is also an existing VoidCallback type (https://github.com/dart-lang/sdk/blob/edca6169c1c040702acde237e605be0bfe037326/sdk/lib/web_sql/dart2js/web_sql_dart2js.dart#L131) which seems to indicate that Flutter is not the only team that found it useful.

2. Add a new VoidCallback type to basic_types that mirrors the implementation in dart:ui and re-export that one instead.

This may cause issues in places where users import both `dart:ui` and `package:flutter/foundation.dart`. I'm less clear on what the failure mode is here. Depending on how severe it may be a breaking change

3. Rename VoidCallback to _VoidCallback in dart:ui and introduce a new VoidCallback type in basic_types.dart.

This is a breaking change in the case where someone is using VoidCallback by importing dart:ui and not package:flutter/foundation.dart. Because Function types are mostly structural, there are no type issues.

To handle the latter case:

1. Lift binding.dart out of foundation, and into a new layer which handles integration of dart:ui and foundation.

The binding class itself may be breaking the flutter/foundation contract since it is highly dependent on dart:ui via the Window, and conceptually via the flutter service extensions. This might be a breaking change, depending on how this Binding class is currently being used. To make it less breaking, we could leave an abstract interface behind.

2. Introduce a new library called `foundation_core.dart` in `flutter/lib` which re-exports all of foundation besides the binding.

This doesn't solve the underlying problem completely, but it is fully non-breaking and provides a library which meets the guarantees of foundation.

cc @jacob314

**Comment by jonahwilliams** [comment]
cc @Hixie @goderbauer for a framework perspective

**Comment by jacob314** [comment]
For the VoidCallback case, my preference would be option #1 or #3 as they minimize confusion from the Analyzer and users about which VoidCallback type to use. For example, would be nice for users to not get code completion suggestions to import VoidCallback from dart:ui.

**Comment by goderbauer** [comment]
I prefer option 1, but it has not gotten much support from the Dart-side: https://github.com/dart-lang/sdk/issues/27791

**Comment by natebosch** [comment]
There should not be any need to export typedefs, their name and the library that defines them are irrelevant.

Replace `export 'dart:ui' show VoidCallback;` with `typedef VoidCallback = void Function();`

**Comment by Hixie** [comment]
We'd rather have only one place that defines VoidCallback because otherwise the documentation can be quite confusing (not to mention that we'd need to duplicate all the docs, etc).
