### ISSUE TITLE
Which is the correct directory for iOS on flutter?

### ISSUE THREAD

**Issue by GerGodfrey** [flutter/flutter#34266]
I take a photo with the camera and I want the metadata of this image. I used the package: path_provider and multi_image_picker.

The first is used to search the path/directory of the image and save it temporarily. The second has a class Asset to transform my image to ByteData.

In Android it is fine, but in iOS I don't know how I can access the folder or directory.

In Android use file:// plus filePath (1)

In iOS I tried:

~ plus filePath (2)
@~ plus filePath (2)

(1)
extDir = await getExternalStorageDirectory() ;
final String dirPath = '${extDir.path}/example';
await new Directory(dirPath).create(recursive: true).then( (Directory directory) {print(directory.path);} );
final String filePath = '$dirPath/${timestamp()+'.jpg'}';

(2)
extDir = await getApplicationDocumentsDirectory();
final String dirPath = '${extDir.path}/example';
await new Directory(dirPath).create(recursive: true).then( (Directory directory) {print(directory.path);} );
final String filePath = '$dirPath/${timestamp()+'.jpg'}';

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
