### ISSUE TITLE
Make TabController._copyWith public instead of private

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#34264]
The TabController._copyWith is currently used in DefaultTabController to allow for dynamically changing tabs by replacing the existing TabController, while keeping the same AnimationController. This allows for the use of a single ticker rather than multiple tickers. 

Two things should be done:
- [ ] We should make this method public so that users can dynamically create new tabs with the same ticker when they use TabController and not DefaultTabController.
- [ ] Update the TabController documentation to provide an example on how to do this properly.

**Comment by shihaohong** [comment]
Discussed offline with @HansMuller and this does not seem like the appropriate solution, since that while exposing `TabController._copyWith` solves the problem at hand, it will also likely lead to incorrect usage of the method and confusion.

**Comment by ffeu** [comment]
Hi @shihaohong ,

As this one was closed, how can we handle dynamic sized TabBars after #29332 ? (see [comment](https://github.com/flutter/flutter/pull/29332#issuecomment-500977534))

**Comment by ffeu** [comment]
Ah, nevermind, the solution is here:
https://github.com/flutter/flutter/issues/39397

Thanks!
