### ISSUE TITLE
--local-engine broken for all x86 Android devices

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#34279]
# Steps

1. Open any flutter app.
2. Build the engine for android x86.
3. `flutter run --local-engine=android_debug_unopt_x86` to an x86 Android device.

# Result

```
E/flutter (10680): [ERROR:flutter/runtime/dart_vm_data.cc(19)] VM snapshot invalid and could not be inferred from settings.
E/flutter (10680): [ERROR:flutter/runtime/dart_vm.cc(241)] Could not setup VM data to bootstrap the VM from.
E/flutter (10680): [ERROR:flutter/runtime/dart_vm_lifecycle.cc(89)] Could not create Dart VM instance.
F/flutter (10680): [FATAL:flutter/shell/common/shell.cc(218)] Check failed: vm. Must be able to initialize the VM.
```

# Cause

It seems like this is a combination of changes to how we select `libflutter.so` and also flutter/engine#9260. I've been able to work around this by locally reverting flutter/engine#9260.  @jason-simmons found that the `libflutter.so` in the apk looks like it's being selected from `flutter/flutter/bin/cache` instead of `flutter/engine/out`. I'm not sure if the APK selection issue is the root cause of the VM failure or if there's some other issue here. Could potentially test for it by copying the locally built cached engine to `flutter/flutter/bin/cache` and seeing if the error still persists.

/cc @blasten

**Comment by blasten** [comment]
> found that the libflutter.so in the apk looks like it's being selected from flutter/flutter/bin/cache instead of flutter/engine/out

Did this work before @mklim? I'm looking at `flutter.gradle` before my changes, and it seems the script never read `libflutter.so` from `flutter/engine/out`.   Only for arm/arm64 debug.
https://github.com/flutter/flutter/blob/3d09f939ba1b076a584e41a9c7d69cca1d1ceb49/packages/flutter_tools/gradle/flutter.gradle#L166-L175

**Comment by blasten** [comment]
oh I see what happened, in ` master` we run that code regardless if you have a local engine passed to it.
