### ISSUE TITLE
APKs grew by ~200KB

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#34273]
Since https://github.com/flutter/flutter/pull/34123 the APKs are about 200KB bigger.

https://flutter-dashboard.appspot.com/benchmarks.html?filter=release_size_bytes

cc @blasten @tvolkert 

If this is expected and unavoidable then please feel free to close this issue.

**Comment by Hixie** [comment]
Looks like https://github.com/flutter/flutter/pull/34250 is intended to be the fix for this?

**Comment by blasten** [comment]
Yep. cc @jason-simmons

**Comment by blasten** [comment]
In the last run, the difference is just ~2KB.

**Comment by tvolkert** [comment]
This was fixed by https://github.com/flutter/flutter/pull/34250
