### ISSUE TITLE
[web] Port cupertino to material to Slider, Switch and Scrollbar

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#34274]
missing in flutter_web/lib/src/material/ directory. we need to port cupertino to the following:

1) https://github.com/flutter/flutter_web/blob/master/packages/flutter_web/lib/src/material/slider.dart
2) https://github.com/flutter/flutter_web/blob/master/packages/flutter_web/lib/src/material/switch.dart
3) https://github.com/flutter/flutter_web/blob/master/packages/flutter_web/lib/src/material/scrollbar.dart

**Comment by mdebbar** [comment]
This is also not an upstreaming issue. These are things missing in flutter web that we should sync from flutter (or wait until we unfork).

**Comment by yjbanov** [comment]
I agree with @mdebbar. This issue is more like "fix the engine enough to run these widgets". Unless they just moved, in which case there's nothing to do; they are already in the right place.

**Comment by ferhatb** [comment]
Fixed via https://github.com/flutter/flutter_web/commit/397e4eb5a2397a1df74fe39830deafb894d7e3e6
