### ISSUE TITLE
[web][upstream] Material TextField add missing properties

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#34277]
There are 4 properties to be addressed in textField to upstream:

https://github.com/flutter/flutter_web/blob/master/packages/flutter_web/lib/src/material/text_field.dart

**Comment by jonahwilliams** [comment]
Which properties are these?

**Comment by nturgut** [comment]
minLines, expands, scrollController, scrollPhysics (it made 4, editting the description.)

**Comment by jonahwilliams** [comment]
These properties are already in flutter, is this issue about adding them to flutter_web?

**Comment by mdebbar** [comment]
@jonahwilliams you are right. These properties already exist in Flutter. They need to be "downstreamed" to flutter web (or just ignored for now until we unfork).
