### ISSUE TITLE
[web]: Forward support for the Navigator

### ISSUE THREAD

**Issue by Levi-Lesches** [flutter/flutter#34280]
Describe your issue and include the command you're running, flutter_web version, browser version

As of now, the back button (or more precisely, `Alt + Left`) works surprisingly well with the Navigator. Try it with the Gallery example to see what I'm talking about. For example, when looking through the Material page, after clicking on a Material element to explore, I'm able to use the browser's back button to go to the menu of Material elements (which I'm guessing is a neat trick for `Navigator.pop`). However, the browser's "forward" button is immediately disabled. 

I guess I understand why this would happen (at least for now), as mobile devices only have a back button with no defined behavior for going forward. But in browsers -- especially with menus like I mentioned above -- this is a common feature which should be implemented similar to a browser (ie, add to a stack of pages whenever the user clicks "back" and then clear the stack when the Navigator "pushes" a new page). 

I guess it's kinda hard to explain, so I'm happy to elaborate on specifics, but I just though it would be cool to see this work out-of-the-box.

**Comment by yjbanov** [comment]
Merging into https://github.com/flutter/flutter/issues/32248
