### ISSUE TITLE
complex_layout_scroll_perf__timeline_summary worst_frame_rasterizer_time_millis regressed

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#34287]
It regressed from ~40ms to ~60ms since https://github.com/flutter/flutter/commit/6d0e61818840f8339126bdf0f5306edacaa91937

Similar regressions are also found in:
* flutter_gallery__transition_perf 99th_percentile_frame_build_time_millis
* flutter_gallery__transition_perf average_frame_build_time_millis
* flutter_gallery__transition_perf missed_transition_count
* flutter_gallery__transition_perf worst_frame_build_time_millis
* home_scroll_perf__timeline_summary worst_frame_build_time_millis

**Comment by liyuqian** [comment]
CC authors of commits in the roll @jason-simmons @chinmaygarde @dnfield

**Comment by dnfield** [comment]
If it's mine that's good news because that's set to be reverted ASAP.  Unfortunately I kind of doubt it's mine.
