### ISSUE TITLE
Broken link in examples readme

### ISSUE THREAD

**Issue by Scorpiion** [flutter/flutter#3428]
## Steps to Reproduce

Go to: https://github.com/flutter/flutter/tree/master/examples

Try the last link to the widget apps example, it's a broken link. Not completely sure, but maybe widgets have been renamed to material_gallery? 

Not a big deal, but thought I could let you guys know, should be a quick fix.

**Comment by sethladd** [comment]
Addressing https://github.com/flutter/flutter/issues/2131 might catch errors like this :)

Also, thanks for the report!
