### ISSUE TITLE
[web] hot reload from dev tools causes miss when using ancestorInheritedElementForWidgetOfExactType

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#34289]
Investigating – will provide more details soon

**Comment by kevmoo** [comment]
See https://github.com/kevmoo/flutter_web/tree/i34289 for the reproduction

**Comment by kevmoo** [comment]
This may also be that the inherited widget cache is not being cleared when main is reran

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/sdk/issues/37259

**Comment by jonahwilliams** [comment]
Potential work around: always reload the root module on start

**Comment by vsmenon** [comment]
This should be fixed upstream now.

**Comment by vsmenon** [comment]
@jonahwilliams - i think you said we're good here?  :-)  can we close?

**Comment by jonahwilliams** [comment]
SG, confirmed this is fixed in recent sdk rolls!
