### ISSUE TITLE
[android_intent]: Should support explicit component launch, e.g., a specific Activity

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#34296]
The android_intent plugin should allow developers to launch specific Android components.

Example of native behavior:

```java
Intent intent = new Intent(myContext, SomeOtherActivity.class);
```

That `Intent` constructor is documented here: https://developer.android.com/reference/android/content/Intent#Intent(android.content.Context,%2520java.lang.Class%3C?%3E)

It's possible that this functionality is already implemented by passing a "componentName". I'm not sure. I see this code:
https://github.com/flutter/plugins/blob/master/packages/android_intent/android/src/main/java/io/flutter/plugins/androidintent/AndroidIntentPlugin.java#L141

If it is already possible to launch a specific `Activity`, `Service`, etc., then the plugin should offer APIs that make it easier and more obvious to do so, e.g.,

```dart
Intent intent = Intent.forComponent('com.company.MyActivity');
```

Additionally, a component `Intent` should not require an `action`, but the Dart `Intent` definition says that an `action` is always required.

Most `Intent`s in an Android app are of the component form, so the android_intent plugin should aim to offer an API that is similar and equally convenient to the native version.

- [ ] Ensure the android_intent plugin makes it possible to launch a specific Android component.
- [ ] Expand the android_intent API surface to make it easy and familiar to send an Intent that launches and Android component.
- [ ] Add an explanation and code sample to the README that shows how to use this very common `Intent` capability.

**Comment by matthew-carroll** [comment]
CC @amirh @xster

**Comment by pedromassango** [comment]
action is always required because the plugin use the `Intent` constructor that receive an action and the library is based on actions.

From the documentation we have:

```
    /**
     * Create an intent with a given action.  All other fields (data, type,
     * class) are null.  Note that the action <em>must</em> be in a
     * namespace because Intents are used globally in the system -- for
     * example the system VIEW action is android.intent.action.VIEW; an
     * application's custom action would be something like
     * com.google.app.myapp.CUSTOM_ACTION.
     *
     * @param action The Intent action, such as ACTION_VIEW.
     */
    public Intent(String action) {
        setAction(action);
    }
```

I think that it just need a function to start Android components

**Comment by TahaTesser** [comment]
Hi  @mklim 
Is this issue still valid?
Thank you

**Comment by stuartmorgan** [comment]
Closing as `android_intent` is deprecated in favor of [`android_intent_plus`](https://pub.dev/packages/android_intent_plus).
