### ISSUE TITLE
[web]: Licenses don't show

### ISSUE THREAD

**Issue by Levi-Lesches** [flutter/flutter#34297]
Licenses don't show on the gallery example app. 

Steps to reproduce: 
- Navigate to the gallery example
- run `webdev serve`
- In the app, click the hamburger menu in the top right, then "about", then "view licenses"

Now the app will hang, and the CircularProgressIndicator will go on forever. 
Meanwhile, in the background, using Chrome's inspector tools, the following error is thrown: 

<pre>
:8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:100549 Error while trying to load an asset: Failed to load asset at "assets/LICENSE" (404)
warn @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:100549
(anonymous) @ :8080/packages/flutter_web_ui/ui.ddc.js:14920
runUnary @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:28453
handleError @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24230
handleError @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24694
_propagateToListeners @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24717
[_completeError] @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24580
(anonymous) @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24613
async._microtaskLoop @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24926
async._startMicrotaskLoop @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24932
(anonymous) @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:25007
:8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:5844 Uncaught (in promise) Error: Unable to load asset: LICENSE
    at Object.dart.throw (:8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4556)
    at load (:8080/packages/flutter_web/services.ddc.js:245)
    at load.next (<anonymous>)
    at onValue (:8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:22311)
    at async._RootZone.new.runUnary (:8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:28453)
    at _FutureListener.then.handleValue (:8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24217)
    at handleValueCallback (:8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24681)
    at Function._propagateToListeners (:8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24713)
    at _Future.new.[_completeWithValue] (:8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24573)
    at async._AsyncCallbackEntry.new.callback (:8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24591)
    at Object.async._microtaskLoop (:8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24926)
    at async._startMicrotaskLoop (:8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24932)
    at :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:25007
DartError @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:5844
dart.throw @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4556
load @ :8080/packages/flutter_web/services.ddc.js:245
onValue @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:22311
runUnary @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:28453
handleValue @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24217
handleValueCallback @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24681
_propagateToListeners @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24713
[_completeWithValue] @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24573
(anonymous) @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24591
async._microtaskLoop @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24926
async._startMicrotaskLoop @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:24932
(anonymous) @ :8080/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:25007
</pre>

Based on the 404, I'm guessing this is a simple issue of `webdev` not bundling a `LICENSE` file?

**Comment by Levi-Lesches** [comment]
Interestingly, after a bit (on the build version, not the served one), another error was thrown: 
<pre>
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
main.dart.js:1159 Another exception was thrown: Unknown keymap for key events: android
</pre>

**Comment by mikhail-tokarev** [comment]
Hi @Levi-Lesches,
are you still experiencing this issue with the latest version of Flutter?
If so please reply attaching your` flutter doctor -v`

**Comment by Levi-Lesches** [comment]
Well I haven't tested on my own device, but I found the [demo](https://flutter.github.io/samples/gallery/) anyway, and it works there, so I'm assuming this was fixed.
