### ISSUE TITLE
[engine] Locale.toLanguageTag() uses the wrong cached version when switching separators

### ISSUE THREAD

**Issue by abonander** [flutter/flutter#34307]
(This issue is in https://github.com/flutter/engine but since it has no issue tracker I assume this repo is fine.)

Package: `dart:ui`

When calling `Locale.toLanguageTag()`, it first checks if `this` is the same as the locale for a cached string, but does not check if the separator is the same as was used in the cached string:

https://github.com/flutter/engine/blob/b14d9719607a876778b27149ec37ea170187bb97/lib/ui/window.dart#L497-L503

If you're using this method with two different separators, or using code like [flutter_localizations](https://github.com/flutter/flutter/blob/d6425a2179815495a624adbae7aa6fb55d182ac7/packages/flutter_localizations/lib/src/material_localizations.dart#L572-L576) which uses `.toString()` and then calling `.toLanguageTag()` in your own code, one of the two methods is going to return the string in an unexpected format.

This is currently causing a crash at the previously linked line in `flutter_localizations` but only when our code calls `.toLanguageTag()` first and has not called it for another locale in the meantime, so it was a bit difficult to pin down.

If caching is desired for performance then the choice of separator should be cached as well so switching separators invalidates the cache.

**Comment by abonander** [comment]
The fact that `flutter_localizations` uses `toString()` when the method's own documentation discourages use except for debugging purposes is concerning as well but that's probably a separate discussion.

**Comment by jason-simmons** [comment]
Fixed by https://github.com/flutter/engine/commit/8d28215c8b5dfbbb3d3d1e36e8f6492667c2a23a
