### ISSUE TITLE
Why flutter is not in pub is a FAQ

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3430]
Could be added to flutter.io/faq and linked from our pub package.

Confusion in #flutter-discuss:
https://dartlang.slack.com/archives/flutter-discuss/p1461138131000027

**Comment by eseidelGoogle** [comment]
Duping to #3432

**Comment by sethladd** [comment]
Actually, we probably want this, too. We could add a FAQ to our FAQ :)

**Comment by sethladd** [comment]
This doesn't seem to be a FAQ any more? Easy to add, but I think this is a Dart-centric question and most new users won't ask this, I presume.
