### ISSUE TITLE
Can grammar be more friendly?

### ISSUE THREAD

**Issue by MonkeyInWind** [flutter/flutter#34304]
For example
```
color: Colors.red----->color: 'red'  / '#000' / 'rgba(0 , 0, 0, 1 )'
```
```
padding: 10  or  '10'
```
just like CSS，more concise writing.
Now the writing is very troublesome and difficult to remember.

**Comment by stuartmorgan** [comment]
Compile-time safety is a feature. Typed constants also allow for intelligent auto-complete in IDEs, making them in many cases easier to type than strings, and also providing automatic access to cross-linking, inline documentation, etc.

If you really want to be able to write, e.g., your colors as strings, you could always write your own wrappers set of widgets that take strings and then construct the underlying constants by parsing them, but it's not the direction Flutter itself will go.

**Comment by MonkeyInWind** [comment]
Not necessarily a string, and not only for color.Maybe my statement is not clear enough.
I mean, more concise.
for example
```
margin: new EdgeInsets.symmetric(vertical: 10.0)
```
Comparatively speaking, CSS is much simpler. It's just an analogy, not necessarily CSS.
I just want to ask if it is possible to make the grammar a little more concise, which will help improve development efficiency.

Of course, that's just advice.
