### ISSUE TITLE
Document when flutter packages get + pod install need to be run in add-to-app

### ISSUE THREAD

**Issue by xster** [flutter/flutter#34300]
It's currently easy to break the Flutter module <-> iOS outer app connection which requires rerunning flutter packages get in the flutter project folder followed by pod install in the iOS project folder. 

Either document them (such as when changing pubspec, when moving directories #34294) or make it less fragile (perhaps via #32993)

**Comment by ahusseini** [comment]
@xster how is this resolved? Running `flutter packages upgrade`, then `flutter packages get` then `be pod install` still doesn't work.

**Comment by xster** [comment]
What's the error message exactly?

**Comment by ahusseini** [comment]
no errors afaik, those commands randomly stop updating the integration, even wiping the Pods folder doesn't work

**Comment by ahusseini** [comment]
deleting Derived Data seems to do the trick 😬

**Comment by xster** [comment]
Merging into https://github.com/flutter/flutter/issues/32862
