### ISSUE TITLE
flutter doctor can't find android studio when the name is changed

### ISSUE THREAD

**Issue by Super-Crab** [flutter/flutter#34318]
I'm a Android developer. Use Android studio 3.4，Mac OS
But the flutter doctor cannot find my android studio because I had chang it's name to 3.4.
When I read "flutter/packages/flutter_tools/lib/src/android/android_studio.dart", i found doctor depends the software name to check it has installed,can change this to depends “Info.plist” or other fun ?
![image](https://user-images.githubusercontent.com/13375587/59333260-90dc2480-8d2a-11e9-9f36-4d7b74520a82.png)

**Comment by stuartmorgan** [comment]
Reading the Info.plist of every application would be *much* slower than scanning the file names. `lsregister` bundle ID checking could work, but that would add a fair amount more complexity to handle this edge case.

Is there a reason you don't just rename it "Android Studio 3.4" (I'm assuming the goal here is to have multiple versions) so that the check still passes?

**Comment by Super-Crab** [comment]
@stuartmorgan  Yeah,I have multiple versions and when i rename it to "Android Studio 3.4","flutter doctor" also can find it.
But just relying on the file name to determine if it exists is not accurate. It is not friendly to other developers who rename it to other strings that do not start with "Android Studio."

**Comment by jonahwilliams** [comment]
The way we're handling this for the web tools is that we check in specific places and for specific file names, but we also allow you to provide your own via an environment variable (described in the doctor). This lets us handle the 95% of cases automatically while still giving people to customize it.

That seems like a reasonable approach to take here

**Comment by christopherfujino** [comment]
@Super-Crab you can set a custom Android Studio path via `flutter config --android-studio-dir /path/to/android/studio`. Closing this issue!
