### ISSUE TITLE
Installation guide for Linux needs some update

### ISSUE THREAD

**Issue by shunjid** [flutter/flutter#34313]
I've been trying to install flutter on 'Linux Mint 19.1' according to documentation guideline. According to documentation's [this part](https://flutter.dev/docs/get-started/install/linux#update-your-path) I've to create or, modify **$HOME/.bash_profile** file to add this line to permanently update flutter path:

> export PATH="$PATH:[PATH_TO_FLUTTER_GIT_DIRECTORY]/flutter/bin"

Where **[PATH_TO_FLUTTER_GIT_DIRECTORY]** should be replaced by the folder where I've cloned the latest flutter repository in my computer. And then running this command below to refresh the current terminal:

**source $HOME/.bash_profile**

After following all these guidelines and steps I've restarted my computer but the problem arises when I opened a terminal and run the flutter command and it said:
> flutter: command not found
That means flutter path wasn't actually updated to all my terminal sessions permanently. 

**How I've overcome this problem?**

- Removed the $HOME/.bash_profile file

- Opened $HOME/.profile in an editor as Super user. In my case, it was:

> `sudo gedit .profile`

- After the last line of this **.profile** file I've added  this line below:

> export PATH="$PATH:[PATH_TO_FLUTTER_GIT_DIRECTORY]/flutter/bin"

In my case, it was like this because I've cloned flutter repository to a folder named **packages** in home directory:
> export PATH="$PATH:/home/packages/flutter/bin"

- Then I've reboot the system and it was all perfect to run the flutter command then.

My goal of writing this much of problem and solution that worked for me is to request the docs modifier to review this problem and to update documentation to make the installation process easier. 

Thank you.
#HappyProgramming

**Comment by phanirithvij** [comment]
I think rebooting is not required.
And for me I add anything related to extending the `PATH` variable in `~/.bashrc` instead of bash profile.

**Comment by khflab** [comment]
You do not need to reboot, just load your bash again (or open a new Terminal). Each Linux distribution can vary on how they find the user bash profile, so it's not the case to update the guide to describe the Linux Mint mode.

**Comment by stuartmorgan** [comment]
As it says in the linked documentation:
> The steps for modifying this variable permanently for all terminal sessions **are machine-specific**. Typically you add a line to a file that is executed whenever you open a new window. **For example**:

And then later:
> Open (or create) $HOME/.bash_profile. **The file path and filename might be different on your machine.**

(Emphasis added in both cases.)

Covering every case is beyond the scope of the documentation, so it gives an example which is labelled and such.
