### ISSUE TITLE
PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 7: , null)

### ISSUE THREAD

**Issue by am15h** [flutter/flutter#34329]
Google sign in using FirebaseAuth is not working, throws an exception 
**PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 7: , null)**

```
class SignInScreen extends StatelessWidget {
  final GoogleSignIn _googleSignIn = GoogleSignIn();
  final FirebaseAuth _auth = FirebaseAuth.instance;

  Future<FirebaseUser> _handleSignIn() async {
    final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    final GoogleSignInAuthentication googleAuth =
        await googleUser.authentication;

    final AuthCredential credential = GoogleAuthProvider.getCredential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );

    final FirebaseUser user = await _auth.signInWithCredential(credential);
    print("signed in " + user.displayName);
    return user;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
            color: Colors.lightBlue,
            child: Text('Continue with google'),
            onPressed: () {
              _handleSignIn().then((user) {
                print(user);
              }).catchError((e) {
                print(e);
              });
            }),
      ),
    );
  }
}

```

There is no solution to this problem on the internet.

**Comment by am15h** [comment]
This error occurred as I was not connected to the internet, while trying to sign in.

**Comment by tneumueller** [comment]
I am definitely connected to the internet and this error still consistently happens to me. Did work previously and didn't change anything to the login logic.

**Comment by hemangjoshi37a** [comment]
@tneumueller My internet was not working, but as soon as I turned on my wifi everything worked just fine. You can may be check your internet speed, may be your internet speed is too slow to request the Goolgle login API.

**Comment by Anikets08** [comment]
yes it is network problem 
i checked and connected it with some other internet and it worked

**Comment by praharshbhatt** [comment]
> I am definitely connected to the internet and this error still consistently happens to me. Did work previously and didn't change anything to the login logic.

Agreed. Same issue here. Network is fine.
