### ISSUE TITLE
flutter package on pub isn't explicit enough when redirecting to flutter.io

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3432]
We can make the README of the flutter package on pub.dartlang.org more clear that it's not intended to be used, and redirect the user over to flutter.io.

(Feedback from https://dartlang.slack.com/archives/flutter-discuss/p1461138131000027)

**Comment by sethladd** [comment]
cc @abarth if you can make me an uploader, I'll be happy to update the README.

Here's a proposal:

# Please visit flutter.io to get started with Flutter.

Flutter is a new project to help developers build high-performance, high-fidelity, mobile apps for iOS and Android from a single codebase.

This package is a placeholder, it is not intended to be used by developers.
Check out our _getting started guide_ to learn more.

And we can update pubspec.yaml's description to say "Please visit flutter.io to get started."

Thoughts?

cc @Scorpiion how does this sound?

**Comment by Scorpiion** [comment]
Hi @sethladd, I think it sounds great! With a description like this there will be no ambiguity, I like it.. :+1:

**Comment by abarth** [comment]
> cc @abarth if you can make me an uploader, I'll be happy to update the README.

You're an uploader now.

**Comment by sethladd** [comment]
I am drunk with power!!

**Comment by sethladd** [comment]
Thanks! All done.
