### ISSUE TITLE
Solved: android\gradlew.bat exited abnormally

### ISSUE THREAD

**Issue by angelxtrme** [flutter/flutter#34324]
on debugging:

Launching lib\main.dart on Android SDK built for x86 in debug mode...
* Error running Gradle:
ProcessException: Process "D:\Projects\Flutter\hello_world\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* What went wrong:
Could not write cache value to 'C:\Users\Jonathan Torre\.gradle\daemon\4.10.2\registry.bin'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
  Command: D:\Projects\Flutter\hello_world\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.
Exited (sigterm)

--------------------------------------------------------------------------

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18362.175], locale en-PH)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.35.0)
[√] Connected device (1 available)

• No issues found!

Uninstalled Android Studio, VSCode. Deleted folders installed. Deleted Adroid folder. Deleted Flutter SDK folder.
Re downloaded, installed, update and still has this error. Please help. No idea what to do next.

![Screenshot (1)](https://user-images.githubusercontent.com/49402928/59347456-3c936d80-8d47-11e9-87a2-277119812934.png)
![Screenshot (2)](https://user-images.githubusercontent.com/49402928/59347457-3d2c0400-8d47-11e9-90d9-a3e92534d788.png)

SOLVED: Delete '.gradle' folder in C:\Users\***\.gradle, connect to internet, rebuild project to download latest Gradle.

**Comment by angelxtrme** [comment]
Help is very much appreciated.

**Comment by phanirithvij** [comment]
https://stackoverflow.com/questions/28107112/how-to-read-gradles-registry-bin
Might help.

**Comment by d-apps** [comment]
I am not sure but I think empty spaces could be the problem.

Could not write cache value to 'C:\Users\Jonatha**n T**orre.gradle\daemon\4.10.2\registry.bin'.

**Comment by ketanm** [comment]
- Try running `flutter doctor -v`
- Is your environment path setup correctly?

**Comment by angelxtrme** [comment]
@d-apps Yes apps run successfully before. Did not edit or change Gradle files. Started error when i was adding images to a project and downloading dependencies. And was about to update Android's platform_tools to 29.0.0. Updated platform_tools to 29.0.1 but still same error. Also Android Studio and VSCode updated to latest releases.. Try installing latest Gradle same error result.

**Comment by angelxtrme** [comment]
@ketamn Already tried running flutter doctor -v and flutter doctor --android-licenses. Same result. See image attached. Environment path setup properly as instructed in flutter.dev..

**Comment by angelxtrme** [comment]
@phanirithvij Will try delete .gradle folder. Although deleted once the Andoid folder when I uninstalled Android studio and Vscode. Will update if this works

**Comment by angelxtrme** [comment]
@phanirithvij It works! Thanks. Thanks also to @ketanm @d-apps

**Comment by thekingrenz23** [comment]
i dont wanna delete my .gradle folder is there any other option?

**Comment by AnanthanAn** [comment]
I am facing the same issue now and none of these answers work for me,what should i do?

**Comment by navidanchitrali** [comment]
Same problem here! Any one gentleman to help please...

**Comment by Neuromancer93** [comment]
same problem here... really no answer for months?

**Comment by angelxtrme** [comment]
Cant help u guys. A newbie developer here. Try searching the exact error here in github. Might find the answers.. Have a good day!

**Comment by utkarshai** [comment]
non of the above solution helped!! please guide us

**Comment by bowtiedalien** [comment]
deleting the .gradle file did not work for me.

**Comment by utkarshai** [comment]
[project  gradel.txt](https://github.com/flutter/flutter/files/3633258/project.gradel.txt)

**Comment by utkarshai** [comment]
and 
[app gradel.txt](https://github.com/flutter/flutter/files/3633263/app.gradel.txt)

**Comment by utkarshai** [comment]
two changes in project gradel:
 dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.2'
    }

this is one change.


and other is
 ext.kotlin_version = '1.3.50'


and one in app gradel:
  compileSdkVersion 29



these worked for me

**Comment by vijaykanta** [comment]
I don't know how you guys solved it, because the OP didn't mark one as solution.

However, the way I solved it was to have certain conditions while using the release configurations written in the app/gradle file

```

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

```

and then in the android section
```
signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
            }
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
```

**Comment by waseber** [comment]
I'm experiencing the same issue. It seemed to have started when I upgraded to flutter 1.9, however, even downgrading/changing versions doesn't fix anything. Looking around Google, it seems like this is a rather common problem. Please Google/Flutter team, help us out!

**Comment by utkarshai** [comment]
> two changes in project gradel:
> dependencies {
> classpath 'com.android.tools.build:gradle:3.5.0'
> classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
> classpath 'com.google.gms:google-services:4.3.2'
> }
> 
> this is one change.
> 
> and other is
> ext.kotlin_version = '1.3.50'
> 
> and one in app gradel:
> compileSdkVersion 29
> 
> these worked for me

i forget to mention one more thing 
go to android->gradel-> wrapper->gradel-wrapper-properties and change it zip file to version
5.4.1
this is all i have done in my case

**Comment by waseber** [comment]
> > two changes in project gradel:
> > dependencies {
> > classpath 'com.android.tools.build:gradle:3.5.0'
> > classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
> > classpath 'com.google.gms:google-services:4.3.2'
> > }
> > this is one change.
> > and other is
> > ext.kotlin_version = '1.3.50'
> > and one in app gradel:
> > compileSdkVersion 29
> > these worked for me
> 
> i forget to mention one more thing
> go to android->gradel-> wrapper->gradel-wrapper-properties and change it zip file to version
> 5.4.1
> this is all i have done in my case

Thank you so much! This worked for me!

**Comment by geekmiester** [comment]
> > two changes in project gradel:
> > dependencies {
> > classpath 'com.android.tools.build:gradle:3.5.0'
> > classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
> > classpath 'com.google.gms:google-services:4.3.2'
> > }
> > this is one change.
> > and other is
> > ext.kotlin_version = '1.3.50'
> > and one in app gradel:
> > compileSdkVersion 29
> > these worked for me
> 
> i forget to mention one more thing
> go to android->gradel-> wrapper->gradel-wrapper-properties and change it zip file to version
> 5.4.1
> this is all i have done in my case

where do we need to use the 'ext.kotlin_version ='1.3.50'

**Comment by utkarshai** [comment]
Top of the file. Project gradel.

**Comment by kondasoft** [comment]
Changing from 
`ext.kotlin_version = '1.2.71'
`to
`ext.kotlin_version = '1.3.50'`
solved the issue for me.

**Comment by fricred** [comment]
> Changing from: (android/build.gradle)
> `ext.kotlin_version = '1.2.71'`
> to
> `ext.kotlin_version = '1.3.50'`
> solved the issue for me.

solved too tanks

**Comment by mammadovrasul** [comment]
I solve this problem: enter the Android Studio > Setting > System Setting >  Android SDK ---and install API level 24,25,26,27,28,29  after restart app.

**Comment by syedz** [comment]
Might be a bit late to the party, but in my case, `build.gradle` was referencing the `keystoreProperties` variable, but the `key.properties` file wasn't there. I guess somewhere along the way it got deleted. Created that file again and added the properties that were being referenced.

**Comment by koalazub** [comment]
> 
> 
> > two changes in project gradel:
> > dependencies {
> > classpath 'com.android.tools.build:gradle:3.5.0'
> > classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
> > classpath 'com.google.gms:google-services:4.3.2'
> > }
> > this is one change.
> > and other is
> > ext.kotlin_version = '1.3.50'
> > and one in app gradel:
> > compileSdkVersion 29
> > these worked for me
> 
> i forget to mention one more thing
> go to android->gradel-> wrapper->gradel-wrapper-properties and change it zip file to version
> 5.4.1
> this is all i have done in my case

Brilliant! This helped a lot. Cheers for that

**Comment by mziyandajoko** [comment]
I have tried to do almost all the above fixes but none of them worked. I decided to **replace the android folder with another folder from another folder it worked also delete the **_android.iml that gets created when you create a project**

**Comment by Tareque2208** [comment]
> on debugging:
> 
> Launching lib\main.dart on Android SDK built for x86 in debug mode...
> 
> * Error running Gradle:
>   ProcessException: Process "D:\Projects\Flutter\hello_world\android\gradlew.bat" exited abnormally:
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Could not write cache value to 'C:\Users\Jonathan Torre.gradle\daemon\4.10.2\registry.bin'.
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
>   Command: D:\Projects\Flutter\hello_world\android\gradlew.bat app:properties
> 
> Please review your Gradle project setup in the android/ folder.
> Exited (sigterm)
> 
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18362.175], locale en-PH)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
> [√] Android Studio (version 3.4)
> [√] VS Code (version 1.35.0)
> [√] Connected device (1 available)
> 
> • No issues found!
> 
> Uninstalled Android Studio, VSCode. Deleted folders installed. Deleted Adroid folder. Deleted Flutter SDK folder.
> Re downloaded, installed, update and still has this error. Please help. No idea what to do next.
> 
> ![Screenshot (1)](https://user-images.githubusercontent.com/49402928/59347456-3c936d80-8d47-11e9-87a2-277119812934.png)
> ![Screenshot (2)](https://user-images.githubusercontent.com/49402928/59347457-3d2c0400-8d47-11e9-90d9-a3e92534d788.png)
> 
> SOLVED: Delete '.gradle' folder in C:\Users***.gradle, connect to internet, rebuild project to download latest Gradle.

What do you mean by rebuild? Installing the packages back again?

**Comment by AlibaherMuradi2015** [comment]
if you are used Firebase in your project make the gradle classpath version same us google-services classpath in Project-level build.gradle (<project>/build.gradle)

dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:3.2.1'
    }

**Comment by and301** [comment]
> I solve this problem: enter the Android Studio > Setting > System Setting > Android SDK ---and install API level 24,25,26,27,28,29 after restart app.

did you install the whole files or just the SDKs?

**Comment by and301** [comment]
> ext.kotlin_version = '1.3.50'

I have the same problem but I am not finding this ext.kotlin_version = '1.3.50', please help

**Comment by Achintha444** [comment]
For me, the thing was I have hidden the .gradle folder. If you are using windows then try to unhide and try again.

Also PS: Don't use Windows for development 😁😉
