### ISSUE TITLE
run a flutter-app in simulator in AOT mode？

### ISSUE THREAD

**Issue by SheronLv** [flutter/flutter#34323]
I want to use the  APP.framework to integrate to existing iOS APP.  It seems simulator not support AOT and it run in debug mode .  The APP.framework in debug mode  need some files very big, such as kernel_blob.bin, isolate_snapshot_data and vm_snapshot_data.  If simulator can run app with APP.framework  in AOT mode,  I can get rid of these big files and provide a smaller APP.framework for both iphone and simulator.
 so, Is there any way to run a flutter-app in simulator with AOT mode ?

**Comment by mikhail-tokarev** [comment]
hi @SheronLv 
please take a look at this documentation
https://github.com/flutter/flutter/wiki/Flutter-engine-operation-in-AOT-Mode
let me know if the issue still persist

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
