### ISSUE TITLE
OutlineInputBorder should prevent borderRadius that is too large

### ISSUE THREAD

**Issue by anushbhatia** [flutter/flutter#34327]
I faced this issue while working with flutter can you please resolve this ?

```
Column(children: <Widget>[
  TextField(
    decoration: InputDecoration(
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(50.0),
          borderSide: BorderSide(color: Colors.teal)),
      hintText: 'Tell us about yourself',
      helperText: 'Keep it short, this is just a demo.',
      labelText: 'Life story',
      prefixIcon: const Icon(
        Icons.person,
        color: Colors.green,
      ),
      prefixText: ' ',
      suffixText: 'USD',
      suffixStyle: const TextStyle(color: Colors.green)),
    onSubmitted: (String ab) {
      setState(() {
        b = ab;
      });
    },
  ),
  Padding(
    padding: EdgeInsets.all(5.0),
  )
]);
```
![untitled](https://user-images.githubusercontent.com/40017559/59355537-c2fa8000-8d44-11e9-9d4c-24c6665e5f15.gif)

**Comment by BaderEddineOuaich** [comment]
put the column inside a SingleChildScrollView() like:
`SingleChildScrollView(child:
Column(children: <Widget>[ TextField( decoration: new InputDecoration( border: new OutlineInputBorder( borderRadius: BorderRadius.circular(50.0), borderSide: new BorderSide(color: Colors.teal)), hintText: 'Tell us about yourself', helperText: 'Keep it short, this is just a demo.', labelText: 'Life story', prefixIcon: const Icon( Icons.person, color: Colors.green, ), prefixText: ' ', suffixText: 'USD', suffixStyle: const TextStyle(color: Colors.green)), onSubmitted: (String ab) { setState(() { b = ab; }); }, ), Padding( padding: EdgeInsets.all(5.0), ) ]));`

**Comment by shihaohong** [comment]
Hi @BaderEddineOuaich, this is because you're setting `OutlineInputBorder.borderRadius` to be much larger than the actual height of the `TextField`. Once you reduce the borderRadius value, this problem is averted (try setting it to 30.0, it'll look fine). 

However, we should really be preventing this from happening.

**Comment by anushbhatia** [comment]
Thanks @shihaohong 😊

**Comment by shihaohong** [comment]
I did some more testing and noticed that if horizontal border radii (ie topLeft and topRight, or bottomLeft or bottomRight) are not equal, it leads to some unusually drawn shapes, or a border that does not line up. 
1) Bottom horizontal radii not equal 
![bottomHorizontal](https://user-images.githubusercontent.com/27032613/59527996-f991e100-8e91-11e9-8d15-10426b122cf8.png)
2) topLeft radius > topRight radius
![horizontal(left right)](https://user-images.githubusercontent.com/27032613/59527997-fac30e00-8e91-11e9-8819-15d0ee266f23.png)
3) topLeft radius < topRight radius
![topHorizontal(left right)](https://user-images.githubusercontent.com/27032613/59527998-fb5ba480-8e91-11e9-9b7e-a3f74d2b92b6.png)

These will need to be resolved while constraining the borderRadius values allowed.
