### ISSUE TITLE
[web]: any hosting

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#34328]
If I build a flutter_web where I can get hosting? Thank you

**Comment by phanirithvij** [comment]
I think you get all the compiled JavaScript and index.html in the dist folder after building.

That index.html can be hosted anywhere just like any normal static website.

Examples are 
Netlify, Heroku, Digital Ocean, GitHub pages, etc.

**Comment by NTMS2017** [comment]
I don't think everything run on index.html. I am guessing dart server produce a html page. my app connects to remote server and gets data using internal tcp/ip network socket. Example if the user need to view some list the currently my flutter web (I am using IntelliJ) get a data from my local network. My problem to use my flutter web globally. I need to use hosting to make securely connect to remote server to get data. each remote server I use Nginx and aqueduct to serve data as jSON. 

I am looking hosting company or similar to publish my app and continue work on my project.

**Comment by stuartmorgan** [comment]
Hosting is beyond the scope of the Flutter project. You might try one of the more general discussion forums listed on flutter.dev/community to get recommendations about hosting providers.
