### ISSUE TITLE
[web][upstream] upstream debugPrintDouble

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#34338]
debugPrintDouble: https://github.com/flutter/flutter_web/blob/master/packages/flutter_web/lib/src/foundation/diagnostics.dart
This method is also called from different places in the code.

**Comment by jonahwilliams** [comment]
We have debugFormatDouble - https://github.com/flutter/flutter/blob/6feedcc6a4862f2f0bca896567740ef1a06c2a42/packages/flutter/test/foundation/double_precision_test.dart#L9
