### ISSUE TITLE
Facing issues while fetching data from Firestore.

### ISSUE THREAD

**Issue by LuciferAJ** [flutter/flutter#34333]
I have two application. From one application all the clients can upload the data to Firestore.
The data which the client uploads will be stored in the form of `user/user_uid/form/formId/data`
```
user = collection
user_uid = document
form = collection
formId = document
data = name,address,email...
```
The other application is on the administrator side. The Administrator should be able to see all the data from all the clients by fetching details like `user/user_uid`. But I'm having issues in fetching the data that way, it always returns null. If  I add data in the form of `user/user_uid/data` it's fetching data, but not fetching in the earlier way.

**Comment by hemnathmouli** [comment]
This is how you can fetch document from a `collection`: https://stackoverflow.com/questions/46611369/get-all-from-a-firestore-collection-in-flutter

**Comment by janmoppel** [comment]
Hello @LuciferAJ !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by kroikie** [comment]
@LuciferAJ

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1225. Any further collaboration will be done there.
