### ISSUE TITLE
flutter_driver can't interact with native elements

### ISSUE THREAD

**Issue by nerder** [flutter/flutter#34345]
It looks like it is still not possible to interact with native elements in an automatic/programmatic fashion using `flutter drive`.

Might be related to [this](https://github.com/flutter/flutter/issues/12561) issue?

**Comment by collinjackson** [comment]
This isn't possible currently, but I'm working on it.

**Comment by beniwalraj** [comment]
@collinjackson yo bro have got a solution to this issue yet.

**Comment by nerder** [comment]
@collinjackson would you like to explain here the technical challanges of this here?

**Comment by beniwalraj** [comment]
> @collinjackson would you like to explain here the technical challanges of this here?

Hey @collinjackson  Challenge I'm facing that fluuter_driver not is not interacting with native iOS elements.
![continue](https://user-images.githubusercontent.com/2739327/60311914-99746200-999c-11e9-8417-8f6469a3f6f8.png)
and facebook login page
![fb-login](https://user-images.githubusercontent.com/2739327/60311934-b14be600-999c-11e9-91f2-fca7894ee4ef.png)
I was thinking of using puppetter.dart but that wont work either as am not using browser. This is a login link within my app to login.
Any suggestion would be greatly appreciated.

**Comment by nerder** [comment]
I think it's better to change the title of this issue into `flutter_driver can't interact with native/3rd party elements` in order to group all this kind of issues, and in this way it might be prioritized sooner 😄

**Comment by rvowles** [comment]
@collinjackson flutter driver should be made extensible. Because it is essentially a command passed over the wire mechanism, there should be an easy way to extend commands for a project's own use. In the main.dart that the test runs, we should be able to register extra commands and in the test side, we should be able to register further commands. I have experimented with this to allow a test to inject javascript into a web view to allow the test to login via a webview, but I essentially had to butcher flutter driver to be able to. 

If it was made extensible, these kinds of extensions could be built by the community instead.

**Comment by ggspark** [comment]
Any updates on this?

**Comment by rvowles** [comment]
Any in-app browser situation you can easily get around by adding a handler to your enableFlutterDriver in your test main - however interacting with stuff (including system dialogs) is still impossible for us. We drive login and url validation using the flutter driver extension mechanism.

**Comment by pradarttana-sharechat** [comment]
My flutter integration test is not working because of ios native pop up for permissions "camera", "notifications".

hence I took help of 

`
Process.run('applesimutils', ["--byId", deviceId, "--bundle", appBundleIdentifier, "--setPermissions", "location=always"]);

Process.run('applesimutils', ["--byId", deviceId, "--bundle", appBundleIdentifier, "--setPermissions", "notifications=YES"]);
`

but the springboard is restarted. and the app is closed. 

hence I used
Process.run('xcrun', ["simctl", "launch", "booted", iosBundleIdentifier]);

this does launch back the app, but the driver cannot connect to the VM.

Hence still struggling with this. any idea/hack before the proper fix would help.

**Comment by collinjackson** [comment]
I think this should be doable with the new [package:espresso](https://pub.dev/packages/espresso).

**Comment by ravuthlong** [comment]
@collinjackson But that means the tests need to be written in Kotlin? Defeats the purpose of cross-platform?

**Comment by collinjackson** [comment]
> @collinjackson But that means the tests need to be written in Kotlin? Defeats the purpose of cross-platform?
> 
> Can we get an update on this issue? We should be able to access webview and native dialogs from Flutter driver test written in Dart.

The wrapped SDKs behave very differently on iOS and Android. For testing the google_sign_in plugin itself, I think a platform-specific test is necessary. To write a cross-platform Dart end-to-end cross-platform test that gets through the login flow, I think what we need is for the Google Sign In plugin to expose a cross-platform Dart test API that handles the login flow, then the app can be tested using the e2e package. I'm working on getting an example of this ready.

**Comment by nerder** [comment]
I think this is a very good idea! 

It should be enforced by `flutter` architecture itself as for the `platform channels` we should be able to e2e test platform-specific code, this will be a great addition to `flutter_driver` and it will increase a lot the effectiveness of this kind of tests.

I think that the final outcome of this should be to add another section such as `Writing platform-specific code` here https://flutter.dev/docs/development/platform-integration

**Comment by audkar** [comment]
> To write a cross-platform Dart end-to-end cross-platform test that gets through the login flow, I think what we need is for the Google Sign In plugin to expose a cross-platform Dart test API that handles the login step, then the app can be tested using that API in combination with the e2e package.

Hmmm. I think this will be bad e2e test if it depends on "Google Sign In plugin" implementation details... 

How I would write such test for native android app: 
1. Fill username, password, click login button with UiAutomator.
2. Only then use Espresso to verify our app state.

There is tradeoff - such test will fail if Google change its login form. But test doesn't depend on implementation details. So it will work if I change login sdk e.g. from firebase -> AWS amplify -> Auth0.

And for e2e test I prefer test to start failing when behaviour to user changes (google login form), not auth implementation details.

**Comment by ravuthlong** [comment]
> > @collinjackson But that means the tests need to be written in Kotlin? Defeats the purpose of cross-platform?
> > Can we get an update on this issue? We should be able to access webview and native dialogs from Flutter driver test written in Dart.
> 
> The wrapped SDKs behave very differently on iOS and Android. For testing the google_sign_in plugin itself, I think a platform-specific test is necessary. To write a cross-platform Dart end-to-end cross-platform test that gets through the login flow, I think what we need is for the Google Sign In plugin to expose a cross-platform Dart test API that handles the login step, then the app can be tested using that API in combination with the e2e package.
> 
> I'm working on getting an example of this ready and will reference this issue.

How about other plugins that require user permission/user interaction? I don't believe the plugin and provide an API to directly enable or disable a permission. Would there be a way for flutter driver to integrate with XCUITest and UIAutomator to behave similarly as Appium where we can interact with system dialogs and HTML contents inside the webview? This would resolve native components in e2e from Flutter.

**Comment by darrinps** [comment]
> Any in-app browser situation you can easily get around by adding a handler to your enableFlutterDriver in your test main - however interacting with stuff (including system dialogs) is still impossible for us. We drive login and url validation using the flutter driver extension mechanism.

So you are saying you are able to perform a login, in a round about way, for your flutter_driver integration tests? Can you share what you did for the handler and the flutter driver extension mechanism please?

**Comment by amitkot** [comment]
> I think it's better to change the title of this issue into `flutter_driver can't interact with native/3rd party elements` in order to group all this kind of issues, and in this way it might be prioritized sooner 😄

@nerder I noticed you are the author, could you change the title as you suggest?

**Comment by JSANL** [comment]
We are currently trying to adapt driver tests but this is really just a show stopper in many cases.    
We e.g. would want to test login (Google Sign-In, Apple Sign-In, ...), file picking and buying stuff. Does not seem to be possible with flutter_driver :(

**Comment by srockytfl** [comment]
Hi, any update on this? How we are supposed to test real applications, if a simple permission dialog doesn't work?

**Comment by karayel** [comment]
Any update ?

**Comment by TianyongWang** [comment]
Any update ?

**Comment by OctavianVladut** [comment]
Hey, I'd say this is a blocker in the SDLC since e2e testing cannot be fulfilled. Developing an app without proper testing makes it extremely error prone, therefore not reliable. Is there any plan in having a solution developed for this  functionality shortage anytime soon? Can we have a raise in priority please? Thanks!

**Comment by sentrybottale** [comment]
It is so amusing. Thread is opened 1+ year ago and no-one seems to give a crap, while automation people are in a real blocker. Can't use Appium, as flutter elements are not properly recognized. Can't use - truongsinh/appium-flutter-driver as it is by itself having issues and connected blockers on flutter driver api. Can't use Flutter Driver, as it can't be used for e2e testing. What we are left is with blind x y clicking on a high-end state of the art Google framework.

**Comment by nandhini0761** [comment]
Any Updates?

**Comment by princefr** [comment]
Any updates on this ?

**Comment by nerder** [comment]
Is this something that the Flutter team is thinking about implement at all in flutter driver? Or we should simply migrate to `integration_test` in order to achieve this?

**Comment by jaumard** [comment]
`integration_test ` use `flutter_driver` under the hood to you'll have same problem with it.

**Comment by anortef** [comment]
Still nothing?

**Comment by nerder** [comment]
@jaumard thank you for the clarification. Was my understanding that with `integration_test` we were able interact with native elements using instrumentation tests by writing the test case in the respective native language*. 

_NOTE: This as pointed out before quite undermine the purpose of cross platform but is not too bad either_

**Comment by jaumard** [comment]
> @jaumard thank you for the clarification. Was my understanding that with integration_test we were able interact with native elements using instrumentation tests by writing the test case in the respective native language*.

I'm using `integration_test ` and have same issue ^^ cause my tests are in dart. Sure if you do native integration test you'll have no issue with native elements, but you'll see flutter as one view ^^ 

Not sure we have a full solution viable solution. on my side I try to avoid native popups during integration tests...

**Comment by Giuspepe** [comment]
Hi, is there any update on when this issue will be solved? And are there any workarounds e.g. is it possible to use Appium just to interact with native elements and use integration_test for everything else?

**Comment by SAGARSURI** [comment]
This is a big blocker for us to go ahead with e2e testing. Is there any progress on this?

**Comment by DevGabrielDeSouza** [comment]
Any progress or position on this?

**Comment by JessWeston** [comment]
Now using integration_test and still seeing this issue, should this have been fixed in Flutter 2.0?

**Comment by sentrybottale** [comment]
@JessWeston no, not fixed and they don’t care. A great combination! 😁

**Comment by nilsreichardt** [comment]
> Now using integration_test and still seeing this issue, should this have been fixed in Flutter 2.0?

`integration_test` uses under the hood also Flutter Driver

**Comment by felane** [comment]
Any updates? Currently running `integration_test ` and have the same issue.

**Comment by MiguelSOliveira** [comment]
I also have this issue.. It's impossible to run tests that require logging in with google sign in or apple sign in. Is there a timeline set for this? Seems to be a very popular issue.

**Comment by furaiev** [comment]
this issue has P4 priority, which means it won't be implemented never)

**Comment by rahul-insight** [comment]
It's disappointing to see no update on such an important issue. When will this be implemented?

**Comment by akramcshive** [comment]
Hello team, any update on this? I'm trying to give permission for location, access gallery but this basic functionality doesn't work. I need this to perform e2e test cases. Please provide an update on this.

**Comment by mboiman** [comment]
I need this functionality too

**Comment by Ibessas** [comment]
Any update on this feature?

**Comment by TianyongWang** [comment]
来信已收到

**Comment by akagupta9** [comment]
any updates ??

**Comment by adminant** [comment]
Any news?
I'm trying to make test of login using flutter_appauth (which shows modal browser page), but It seems impossible now using integration_test package. Maybe there is some workaround how to pass text to browser page from flutter and test it?

**Comment by adminant** [comment]
Need this feature very much

**Comment by jeremiahlukus** [comment]
Would be great to have this..

**Comment by TianyongWang** [comment]
来信已收到

**Comment by ashwinichannaveerappa** [comment]
Please provide this feature

**Comment by zmeid** [comment]
any update?

**Comment by nilsreichardt** [comment]
@darshankawar Can we also assign the `integration_test` and `t: flutter driver` label to this ticket?

**Comment by jbryanh** [comment]
I would expect this to be a real problem security-wise, so I would hope no-one is holding their breath.  You can user-interact on a dedicated device, and continue with your testing after authentication.  I suggest that.

**Comment by windows7lake** [comment]
邮件已收到，谢谢！

**Comment by jeremiahlukus** [comment]
That doesn’t really work when running the tests in a pipeline or GitHub action. Manually doing things for automated tests kind of defeats the purpose.

**Comment by bulgarian-beast** [comment]
Any update ??????

**Comment by TianyongWang** [comment]
来信已收到

**Comment by bartekpacia** [comment]
This is finally a solved problem, thanks to [Patrol](https://patrol.leancode.co) – a new Flutter testing framework which we built to eliminate this kind of problem.

[See our documentation to learn more](https://patrol.leancode.co/native/getting-started).

See also:
- [Patrol on GitHub](https://github.com/leancodepl/patrol)
- [`patrol`  on pub.dev](https://pub.dev/packages/patrol)
- [`patrol_cli` on pub.dev](https://pub.dev/packages/patrol_cli)

**Comment by felipecastrosales** [comment]
updates?

**Comment by felipecastrosales** [comment]
> This is finally a solved problem, thanks to [Patrol](https://patrol.leancode.co) – a new Flutter testing framework which we built to eliminate this kind of problem.
> 
> [See our documentation to learn more](https://patrol.leancode.co/native/getting-started).
> 
> See also:
> 
> * [Patrol on GitHub](https://github.com/leancodepl/patrol)
> * [`patrol`  on pub.dev](https://pub.dev/packages/patrol)
> * [`patrol_cli` on pub.dev](https://pub.dev/packages/patrol_cli)

did you manage to apply it? what's the coverage?

**Comment by bartekpacia** [comment]
> did you manage to apply it? what's the coverage?

What do you mean?

**Comment by felipecastrosales** [comment]
> > did you manage to apply it? what's the coverage?
> 
> What do you mean?

did you manage to interact with **native elements** using patrol?

**Comment by felipecastrosales** [comment]
> > did you manage to interact with **native elements** using patrol?
> 
> Yeah, absolutely! The inability to interact with platform UI is actually one of the main problems that we've aimed to solve with Patrol!
> 
> Below are some demos I recorded for you using [our example app](https://github.com/leancodepl/patrol/tree/master/packages/patrol/example). These are just a few features, for a full list refer to our [feature parity list](https://patrol.leancode.co/native/feature-parity).
> 
> > The startup time is the same as with `flutter test integration_test` – so quite long. That's why we'd like to focus on enabling hot restart for Patrol-based integration tests in the upcoming months. For now, please skip the videos 20-30 seconds ahead :)
> 
> ### Testing notifications on iOS
> ```
> $ patrol drive -t integration_test/features/notifications/notifications_single_test.dart
> ```
> 
>  notifications_single_test.dart.mov 
> ### Testing permissions on iOS
> ```
> $ patrol drive -t integration_test/permissions_test.dart
> ```
> 
>  permissions_test.dart.mov 
> ### Testing WebView on iOS
> ```
> $ patrol drive -t integration_test/webview_test.dart
> ```
> 
>  webview_test.dart.mov 
> ### Testing location permission on Android
> ```
> $ patrol drive -t integration_test/location_test.dart
> ```
> 
>  location_test.dart.mov

Wow, how sensational! I hope to see the growth of the package, I will be following the adoption. Success. 👏

**Comment by huycozy** [comment]
I'm not sure which team this issue should belong to, I'm thinking about team `framework` or team `tool`.

**Comment by TianyongWang** [comment]
来信已收到

**Comment by Hixie** [comment]
To set expectations: This is not something anyone who is currently working on Flutter is likely to work on any time soon. We would certainly welcome proposals for how to approach the problem; it would probably require starting with a [design doc](https://github.com/flutter/flutter/wiki/Design-Documents) and then discussing the design with the team, and then implementing it (across multiple platforms). This is, to be clear, quite a lot of work. Please see our [contributing guide](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md) if you are interested in helping here.

fyi @johnmccutchan

**Comment by matanlurey** [comment]
This is not something we will be doing, folks are able to add their own extensions to driver as necessary (as seen above).

If you want an _example_ of doing something like this with `flutter_driver` (we won't make this package public, you could take a look at https://github.com/flutter/flutter/tree/master/dev/tools/native_driver), or otherwise I recommend https://pub.dev/packages/patrol.

**Comment by TianyongWang** [comment]
来信已收到
