### ISSUE TITLE
Says Unable to connect datasource in some of working url

### ISSUE THREAD

**Issue by tjtarunkumar** [flutter/flutter#34349]
com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://mhms8.airtel.tv/PLTV/88888888/224/3221225935/index.m3u8

**Comment by jonahwilliams** [comment]
This is unrelated to flutter

**Comment by tjtarunkumar** [comment]
It is related to flutter beacause the error comes in flutter video player
