### ISSUE TITLE
[firebase_crashlytics] which version of Google Services plugin?

### ISSUE THREAD

**Issue by ghunter99** [flutter/flutter#34357]
The readme doc for firebase_crashlytics says add:
  classpath 'com.google.gms:google-services:4.2.0'
but on the Firebase Flutter setup page:
  https://firebase.google.com/docs/flutter/setup
it says:
  Note: Flutter is currently compatible with version 3.2.1 of the Google Services plugin.

Which is correct? ...and does it matter?

Thanks
-Gary

**Comment by vargavince91** [comment]
Have someone tried both? My plugins aren't working at the moment, and I'm wondering if that could be this version mismatch could be the issue

**Comment by kroikie** [comment]
@ghunter99

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/365. Any further collaboration will be done there.
