### ISSUE TITLE
`flutter create -i swift` Xcode project has warning "The use of Swift 3 @objc inference in Swift 4 mode is deprecated"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#34367]
## Steps to Reproduce

Create a new project with Swift.  Don't add plugins.
```
$ flutter create -i swift test_swift
$ open ios/Runner.xcworkspace 
```
Warning (Xcode 11.0 beta 11M336w):
> The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target. (in target 'Runner')

**Comment by jmagman** [comment]
Other issues like https://github.com/flutter/flutter/issues/15099 referencing this warning are related to plugins.  This is a pure Flutter project with no plugins.

**Comment by antoninobajeli** [comment]
Hello @jmagman, 
do you have any news about how to fix the problem?

**Comment by jmagman** [comment]
> Hello @jmagman,
> do you have any news about how to fix the problem?

Not yet, I will try to take a look next week.

**Comment by jmagman** [comment]
You can fix the warning in your app by removing the SWIFT_SWIFT3_OBJC_INFERENCE build setting override in the Runner target:
Project Settings > Runner target > Build Settings > Swift 3 @ objc Inference > Cmd + Del

Test by setting the environment variable SWIFT_DEBUG_IMPLICIT_OBJC_ENTRYPOINT to 3 in the Scheme > Run > Environment Variables.  
Exercise your app, make sure there are no crashes.  Remove the environment variable when you're done testing.  See https://github.com/apple/swift-evolution/blob/master/proposals/0160-objc-inference.md#step-2-address-opt-in-runtime-warnings
