### ISSUE TITLE
PageView entering animation

### ISSUE THREAD

**Issue by vitor-gyant** [flutter/flutter#34362]
Hi,

It seems that PageView by default animates the items from right to left when the widget first appears on the page. I'd like to remove this animation, is it possible ?

thanks in advance,

**Comment by hemnathmouli** [comment]
Are you using `PageController` ? If so just set the `initialPage` to 1

**Comment by vitor-gyant** [comment]
After some debug just found that the issue was that I was sending -1 as the initialPage value.
