### ISSUE TITLE
[Web]ImageFilter.blur not blurring

### ISSUE THREAD

**Issue by NicTanghe** [flutter/flutter#34364]
Imagefilter.blur  not working as expected.

## Code

``` Dart
import 'package:flutter_web/material.dart';
import 'package:flutter_web_ui/ui.dart';

void main() {
  runApp(new MaterialApp(home: new FrostedDemo()));
}

class FrostedDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new Stack(
        children: <Widget>[
          new ConstrainedBox(
            constraints: const BoxConstraints.expand(),
            child: new FlutterLogo()
          ),
          new Center(
            child: new ClipRect(
              child: new BackdropFilter(
                filter: new ImageFilter.blur(sigmaX: 10.0, sigmaY: 10.0),
                child: new Container(
                  width: 200.0,
                  height: 200.0,
                  decoration: new BoxDecoration(
                    color: Colors.grey.shade200.withOpacity(0.5)
                  ),
                  child: new Center(
                    child: new Text(
                      'Frosted',
                      style: Theme.of(context).textTheme.display3
                    ),
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```

###Result
https://i.imgur.com/8d946ZK.png

Expected result 
https://stackoverflow.com/questions/43550853/how-do-i-do-the-frosted-glass-effect-in-flutter

**Comment by kevmoo** [comment]
Seems more a behavior issue than a perf issue, right?

**Comment by AlBiNoS14** [comment]
I have the same issue, any updates ?

**Comment by ctrysbita** [comment]
Same issue.

**Comment by jakcharvat** [comment]
I have the same issue, although it doesn't seem to affect Safari on MacOS

**Comment by acnologia000** [comment]
i too have encountered this issue , any way we can upvote for a response ?

**Comment by matejthetree** [comment]
I have the same issue. Any progress on this one?

**Comment by NicolasDionB** [comment]
Any update on this? Anyone found a workaround? I'm looking for a blur effect on a particular image...

**Comment by ArchangelXu** [comment]
same issue +1

**Comment by frideosapps** [comment]
Same here, didn't find a way to blur...

**Comment by BataraSurya** [comment]
Same here too... it only make the background darker...

**Comment by ferhatb** [comment]
Note: Edge/Chrome/Safari/Mobile-Safari & Chrome-Android have shipped enabling feature. Upcoming PR should fix it for most browsers. For FireFox still under flag, engine defaults to darken in that case.

**Comment by NicTanghe** [comment]
when is the next pr ?

**Comment by ferhatb** [comment]
@NicTanghe , the PR is merged, you should see it fixed in master at this point. Firefox still will show dark gray. Which platform/browser/version are you seeing issue?
