### ISSUE TITLE
PageView and GestureDetector on index 1

### ISSUE THREAD

**Issue by vitor-gyant** [flutter/flutter#34361]
Hi,

Index 1 never triggers the GestureDetector onTap method. This only happens when the PageView has only two children and index 0 is selected. If we swipe left and index 1 becomes selected there is no issue when clicking on index 0. 

## Steps to Reproduce

Just launch the code on the following gist and tap on index 1 item.

> https://gist.github.com/vitor-gyant/54c54d566f50a6ee987778528d1524d8

flutter doctor -v

```
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.4 18E226, locale en-GB)
    • Flutter version 1.6.3 at /Users/vmagalhaes/flutter
    • Framework revision bc7bc94083 (3 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/vmagalhaes/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (2 available)
    • HUAWEI VNS L31 • FUH4C16507007338                     • android-arm64 • Android 7.0 (API 24)
    • iPhone 5s      • 1508106E-09A7-47FF-A6B3-9508E30FBF82 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by vitor-gyant** [comment]
@shihaohong Is there any possible workaround for this ? Thanks!

**Comment by LongCatIsLooong** [comment]
@vitor-gyant this looks like a dup of https://github.com/flutter/flutter/issues/23873. I'm going to close this issue in favor of that issue.

**Comment by vitor-gyant** [comment]
@LongCatIsLooong No problem. Any clue when this is going to be fixed and if there is any workaround currently ?

**Comment by LongCatIsLooong** [comment]
@vitor-gyant I'm working on a fix, will probably put out a PR during the weekend or early next week, and it will get merged into master once reviewed and approved. Unfortunately I'm not aware of any easy workarounds. My current plan is to fix `RenderSliverFixedExtentBoxAdaptor.performLayout` to make it account for paddings and gaps, if that helps.

**Comment by vitor-gyant** [comment]
@LongCatIsLooong Ok. I'll wait for the fix. Thanks for the help!
