### ISSUE TITLE
Can flutter develop an android smartwatch app?

### ISSUE THREAD

**Issue by giantss** [flutter/flutter#34375]
Can flutter develop an android smartwatch app? With the launch of 4G watches, this market is developing rapidly. If you don't support it now, do you have plans behind it?

**Comment by 10ndavis** [comment]
While Flutter isn’t optimized for Wear devices, experimenting on Wear is possible.

https://medium.com/@mjohnsullivan/experimenting-with-flutter-on-wear-os-f789d843f2ef

**Comment by VladyslavBondarenko** [comment]
Given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
