### ISSUE TITLE
Issue: Error syntax error near unexpected token RunCommand()  file xcode_backend.sh

### ISSUE THREAD

**Issue by adriansalim** [flutter/flutter#34377]
When im compile flutter Apps in Xcode for upload to App store i got error:

![image](https://user-images.githubusercontent.com/24728715/59405135-9772a680-8dd3-11e9-9b0d-380418d169c3.png)

Please help me anyone
I need to upload to AppStore
Thank you

**Comment by BondarenkoStas** [comment]
@adriansalim is it still relevant? Please paste your xcode_backend.sh. 
And please do not include screenshots of code/logs, it prevents them from being copied.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
