### ISSUE TITLE
ImageFit.none doesn't recenter when NetworkImage size changes.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#3437]

**Comment by abarth** [comment]
You mean when a network image changes size in layout?

**Comment by abarth** [comment]
Do you have a test case that shows the issue?

**Comment by abarth** [comment]
Not sure how to make progress here without an example that shows the issue.

**Comment by sethladd** [comment]
Going to close because we're not sure how to make progress. Please reopen if we have a repo or test case. Thanks for the feedback!
