### ISSUE TITLE
Allow direct control of scaling for BitmapDescriptor (Maps plugin)

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#34386]
Related to #34183, #27393, #1208

## Use case

I have an image that I want to use as a marker icon on Google Maps with scaling ratio 3.5.
There is no way to achieve this currently unless I provide mipmaps for it (didn't try playing with fractional ratios though so it might not work at all)

## Proposal

1. Make use of ImageConfiguration.devicePixelRatio in BitmapDescriptor.fromAssetImage
2. Preferably also offer a sync version of this function as there's nothing async required for this and async marker load will require a consecutive setState and widget rebuild.

**Comment by duzenko** [comment]
Sample code

class MeasurePage extends StatefulWidget {
  @override
  MeasurePageState createState() => MeasurePageState();
}

class MeasurePageState extends State<StatefulWidget> {
  BitmapDescriptor icon;
  Future iconLoader;

```
  @override
  Widget build(BuildContext context) {
    if (iconLoader == null) iconLoader = BitmapDescriptor.fromAssetImage(ImageConfiguration(devicePixelRatio: 3), 'images/dot.png').then((r) => setState(() => icon = r));
    return Stack(
      children: <Widget>[
        GoogleMap(
          markers: [
            Marker(
              markerId: MarkerId('1'),
              icon: icon,
              draggable: true,
            )
          ].toSet(),
          initialCameraPosition: CameraPosition(
            target: LatLng(0, 0),
          ),
        ),
        Image.asset(
          'images/dot.png',
          // scale: 1,
        ),
      ],
    );
    return Image.asset(
      'images/dot.png',
      // scale: 1,
    );
  }
}
```

**Comment by Abhishek01039** [comment]
Hello @TahaTesser @pedromassangocode 
Seems like this PR is lands to the repo.

**Comment by pedromassangocode** [comment]
Thanks @Abhishek01039
