### ISSUE TITLE
Polygon stroke width inconsistent across platforms (Maps plugin)

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#34389]
## Steps to Reproduce
1. Use the map demo and go to the Place polygon page
2. Compare the results on iPhone 6S and LG G6 devices or similar.
3. I tried to appease it by feeding devicePixelRatio to strokeWidth but it only reduced the difference so much.
```
    final polygons = polyMarkers
...
            Polygon(
...
              strokeWidth: (2 * MediaQuery.of(context).devicePixelRatio).ceil(),
...
        GoogleMap(
...
          polygons: polygons,
```

## Logs

Not attaching any as it fails even in the flutter example app

![Screenshot_2019-06-13-11-21-57](https://user-images.githubusercontent.com/1481807/59416755-b15dba80-8dce-11e9-9706-a0e7209b0b32.png)
![UNADJUSTEDNONRAW_thumb_1](https://user-images.githubusercontent.com/1481807/59416756-b15dba80-8dce-11e9-8e35-656ff0c9984e.jpg)

**Comment by BondarenkoStas** [comment]
@duzenko Thank you for such a good example! I will close the issue leaving a reference to it in #39476. The PR is waiting to land.
