### ISSUE TITLE
How to use RecognizedLanguage in TextRecognize 

### ISSUE THREAD

**Issue by MistryHiral** [flutter/flutter#34380]
```
class RecognizedLanguage {
  RecognizedLanguage._(dynamic data) : languageCode = data['languageCode'];
  final String languageCode;
}

```
how to call this class.

**Comment by BondarenkoStas** [comment]
@MistryHiral did you find any solution?

**Comment by kroikie** [comment]
@MistryHiral

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1160. Any further collaboration will be done there.
