### ISSUE TITLE
Module build.gradle has incompatible compileSdkVersion and com.android.support dependency

### ISSUE THREAD

**Issue by xster** [flutter/flutter#34396]
From https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/module/android/library/Flutter.tmpl/build.gradle.tmpl

Combining `compileSdkVersion 28` and `implementation 'com.android.support:support-v13:27.1.1'` produces 

<img width="852" alt="Screen Shot 2019-06-13 at 2 48 04 AM" src="https://user-images.githubusercontent.com/156888/59422714-afbbd480-8d85-11e9-8de1-0258ac41559a.png">

**Comment by jonahwilliams** [comment]
@xster @blasten is this fixed by moving to androidX by default? Do we support non-android X enough to go back and fix everything

**Comment by blasten** [comment]
this isn't a supported combination.
