### ISSUE TITLE
[firebase_crashlytics] Can force it to upload the reports?

### ISSUE THREAD

**Issue by KingWu** [flutter/flutter#34392]
firebase_crashlytics: 0.0.4+4

Currently, i integrated with firebase_crashlytics. I found that this plugin will upload the crashlytics report when the application restart. But, for dart, the uncaught handling is handled the exception. The application will not be forced to restart. So, the report will not be uploaded.

If i try to add exit(0) into FlutterError.onError to force kill the application, it is not recommended for iOS.

So, any solutions to force firebase_crashlytics to report? Or, any ideas to solve this problem?

**Comment by AndroidNils** [comment]
I am also interested in forcing reports to crashlytics. In Sentry you can upload an report.

**Comment by kroikie** [comment]
@KingWu

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1142. Any further collaboration will be done there.

**Comment by BondarenkoStas** [comment]
I think it's related to https://github.com/FirebaseExtended/flutterfire/issues/1138
