### ISSUE TITLE
Flutter crashes on Android on FlutterMain.startInitialization ( appCtx )

### ISSUE THREAD

**Issue by VarolOkan** [flutter/flutter#34404]
It looks likeinside FlutterMain.listLibs 

 **File[] files = (new File(applicationInfo.nativeLibraryDir)).listFiles();**
sometimes returns null, thus a NullPointerException on the next line for
  **files.length**

Android 9 / Pixel 2XL

**Comment by jason-simmons** [comment]
That code was just removed on the master branch:
    https://github.com/flutter/engine/commit/4d6847466d0b8223f2d3ba9572e397306b6debf4
