### ISSUE TITLE
Facing 'fluttertoast/FluttertoastPlugin.h' file not found issue occurs in xcode

### ISSUE THREAD

**Issue by suriyaKalidoss21** [flutter/flutter#34403]
## Steps to Reproduce

1. After adding firebase issue occurs
## Logs

Xcode's output:
↳
    While building module 'Flutter' imported from /Users/admin/Documents/rodeo/eretailapp/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/admin/Documents/rodeo/eretailapp/ios/Flutter/Flutter.framework/Headers/Flutter.h:54:
    In file included from /Users/admin/Documents/rodeo/eretailapp/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:11:
    /Users/admin/Documents/rodeo/eretailapp/ios/Flutter/Flutter.framework/Headers/FlutterPlugin.h:148:34: warning:
    'UILocalNotification' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationRequest
    [-Wdeprecated-declarations]
        didReceiveLocalNotification:(UILocalNotification*)notification;
                                     ^
    In module 'UIKit' imported from
    /Users/admin/Documents/rodeo/eretailapp/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Libra
    ry/Frameworks/UIKit.framework/Headers/UILocalNotification.h:18:12: note: 'UILocalNotification' has been explicitly marked
    deprecated here
    @interface UILocalNotification : NSObject<NSCopying, NSCoding>
               ^
    While building module 'Flutter' imported from /Users/admin/Documents/rodeo/eretailapp/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/admin/Documents/rodeo/eretailapp/ios/Flutter/Flutter.framework/Headers/Flutter.h:65:
    /Users/admin/Documents/rodeo/eretailapp/ios/Flutter/Flutter.framework/Headers/FlutterPluginAppLifeCycleDelegate.h:92:34: warning:
    'UILocalNotification' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationRequest
    [-Wdeprecated-declarations]
        didReceiveLocalNotification:(UILocalNotification*)notification;
                                     ^
    In module 'UIKit' imported from
    /Users/admin/Documents/rodeo/eretailapp/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Libra
    ry/Frameworks/UIKit.framework/Headers/UILocalNotification.h:18:12: note: 'UILocalNotification' has been explicitly marked
    deprecated here
    @interface UILocalNotification : NSObject<NSCopying, NSCoding>
               ^
    2 warnings generated.
    /Users/admin/Documents/rodeo/eretailapp/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error:
    'fluttertoast/FluttertoastPlugin.h' file not found
    #import <fluttertoast/FluttertoastPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 warnings and 1 error generated.

**Comment by stuartmorgan** [comment]
Is fluttertoast a current dependency in your project, or something that used to be used but is no longer in your pubspec.yaml?

**Comment by ctippur** [comment]
I have a similar issue.

Not sure if this is related - https://github.com/flutter/flutter/issues/41033?

**Comment by stuartmorgan** [comment]
Closing due to lack of response.

**Comment by heliosnarcissus** [comment]
I have a similar problem.
fluttertoast is working fine on my iOS simulator device but when I run the application on my REAL ios device, I get this error:
```
 fatal error: module 'fluttertoast' not found
    @import fluttertoast;
```
I posted it on stackoverflow to no avail:
https://stackoverflow.com/questions/62979803/fluttter-error-on-real-ios-device-module-fluttertoast-not-found
