### ISSUE TITLE
Expose iOS functionality to Flutter apps

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#3440]
I need to connect Bluetooth services to a Flutter app. There's currently a prototype solution on Android with a Flutter view hosted inside a Java application with some plumbing to pass messages back and forth. We need a similar solution in iOS.

**Comment by abarth** [comment]
- [ ] We need implement the message passing API on iOS: https://github.com/flutter/engine/blob/master/sky/services/platform/app_messages.mojom
- [ ] We need to make it possible for end-developers to use FlutterViewController in their own iOS apps.

**Comment by sethladd** [comment]
> currently a prototype solution on Android 

Curious, where is that code?

**Comment by abarth** [comment]
> Curious, where is that code?

https://github.com/flutter/flutter/tree/master/examples/hello_android

**Comment by abarth** [comment]
See https://github.com/flutter/flutter/issues/3256 adding support for app messages on iOS.

**Comment by chinmaygarde** [comment]
Can we close this ticket now that app messages have landed on iOS?

**Comment by abarth** [comment]
Yes.  This is now possible, although not documented completely yet.
