### ISSUE TITLE
Custom-font-issue in IOS

### ISSUE THREAD

**Issue by SaravanarajaGITHUB** [flutter/flutter#34414]
Got stuck with the custom font in IOS, Font family I used is Gotham

With my same code of login screen in android the UI look good as expected but not in IOS devices.. padding, alignment, button spacing & more are not matching : ( .. with help of pain tool in windows, in  both the screen i just hidden the app logo with dummy box (for confidential).

and in IOS screen shot, forget about the TextFormFields prefix icons missing.. that's issue of mine. 

here is the link i downloaded the font .ttf files [Link](https://www.cufonfonts.com/font/gotham)
 
**IOS SCREEN** 
![Screenshot 2019-06-13 at 6 00 34 PM](https://user-images.githubusercontent.com/6235704/59447152-72585500-8e20-11e9-8a11-b28787574df0.png)

**ANDROID screen**
![1560439398098](https://user-images.githubusercontent.com/6235704/59447182-7be1bd00-8e20-11e9-84aa-125892402272.JPEG)
![font_used](https://user-images.githubusercontent.com/6235704/59447225-88feac00-8e20-11e9-9aaa-18e863c8e381.PNG)
![yamlfileFont](https://user-images.githubusercontent.com/6235704/59447238-8ef48d00-8e20-11e9-9982-f64afaf675ef.PNG)
![que_prob](https://user-images.githubusercontent.com/6235704/59447372-be0afe80-8e20-11e9-9a34-179f399f6367.PNG)

**Comment by HansMuller** [comment]
If I'm understanding this correctly, the issue is that the Login button doesn't look the same on iOS on Android. If you could add a small self-contained example that reproduces the problem (I imagine only the code that produces the button is needed), we'll look into it.
