### ISSUE TITLE
Docs failing to upload to Firebase

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#34435]
```
Error:
 Server Error. ESOCKETTIMEDOUT
(node:3611) UnhandledPromiseRejectionWarning: Error
    at new FirebaseError (/usr/lib/node_modules/firebase-tools/lib/error.js:9:18)
    at Request._callback (/usr/lib/node_modules/firebase-tools/lib/api.js:30:31)
    at self.callback (/usr/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at ClientRequest.<anonymous> (/usr/lib/node_modules/firebase-tools/node_modules/request/request.js:819:16)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:662:40)
(node:3611) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
(node:3611) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: Unable to deploy documentation to Firebase. Retrying in five seconds... (2 tries left)
```

**Comment by tvolkert** [comment]
@kf6gpe do we have a contact on the Firebase hosting side of things?

**Comment by samtstern** [comment]
Try @memeraj, TL of Hosting

**Comment by tvolkert** [comment]
https://cirrus-ci.com/task/6261589859106816 is an example CI task where this failed.  The relevant command that's failing is:

https://github.com/flutter/flutter/blob/361e8c75d7a46ddfbfacb8ef89cdf354b7841bf4/dev/bots/docs.sh#L9

**Comment by tvolkert** [comment]
With help from @Memeriaj, I was able to resolve it by setting a sane value in the maximum number of versions to retain in the Firebase hosting settings.

**Comment by tvolkert** [comment]
Still happening, so re-opening.

**Comment by dnfield** [comment]
As of #34681 we think we have a work around that should hold us over for a bit longer.  The root problem still remains though, so I'm going to leave this open.  It's entirely possible this will start failing again, in which case we can retag this as TODAY.  But we now have a successful docs upload.

**Comment by dnfield** [comment]
I've made some additional changes that now result in less uploading of docs per commit.  These changes are somewhat hacky and probably bitrot over time, but they've lowered the overall time of the docs step.

Unfortunately, we still have to do a lot of "adding files to version", which is where we were seeing the timeouts.  So far, setting the number of connections to 100 seems to be working for that.

See https://github.com/flutter/flutter/pull/34831 and https://github.com/flutter/flutter/pull/34818

See also https://github.com/dart-lang/dartdoc/issues/1983 (which is intended to suggest a way to vastly reduce the number of files we have to upload) and https://github.com/dart-lang/dartdoc/issues/1982

**Comment by dnfield** [comment]
I think this can be closed for now, but we can re-open if it becomes an issue again.  Firebase hosting is still working on additional changes that should make it even better.
