### ISSUE TITLE
Consider running dart-sdk/tests in sky_shell

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3443]
https://github.com/dart-lang/sdk/blob/master/tests/isolate/handle_error2_test.dart is an example of one test I believe we fail, which I think explains https://github.com/flutter/flutter/issues/2182.

There are likely other tests we could/should be running from this directory to catch these errors.  @johnmccutchan

**Comment by eseidelGoogle** [comment]
@kasperl are these the tests which you're already running on devices?  If not, do you (or @iposva-google) believe we should be running these?  Unclear to me what the bang for buck here is for flutter, but we are definitely hitting occasional issues where our embedding of the Dart VM is different from the Dart CLI and possibly these tests could help find those sooner?  If you think we should be running these, are there folks on your respective teams who might be able to help us do so?

**Comment by johnmccutchan** [comment]
Kasper's team made the standalone Dart embedder run on devices. What I think we actually want is to be able to run the test suite against the sky_shell embedder.

**Comment by sethladd** [comment]
cc @chinmaygarde we chatted about this briefly yesterday

**Comment by eseidelGoogle** [comment]
I mentioned this to @a-siva and @kasperl in our 1:1s last week. I think it's definitely time for us to explore these likely could have caught recent Isolate regressions like #5926 and #5814 if nothing else. :)

**Comment by eseidelGoogle** [comment]
Adding keyword "test.py" since I often search for this issue that way.

**Comment by sethladd** [comment]
Is this for us, or for the Dart team's bots?
