### ISSUE TITLE
Flutter firebase not working on ios

### ISSUE THREAD

**Issue by MarthinBergs** [flutter/flutter#34437]
When I run flutter with firebase core it fails. 

I have the GoogleService-Info.plist placed in ios/runner folder.

Emulator: Iphone X ios 10
Android studio: 3.3.1
Flutter: 1.5.4-hotfix.2
Flutter doctor: no errors

`
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           107.0s
Configuring the default Firebase app...
6.2.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
6.2.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
6.2.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
6.2.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011104612b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001106daf41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001110bb245 +[NSException raise:format:] + 197
	3   Runner                              0x000000010c599072 +[FIRApp configure] + 562
	4   Runner                              0x000000010ca00d66 -[FLTCloudFirestorePlugin init] + 214
	5   Runner                              0x000000010ca00b64 +[FLTCloudFirestorePlugin registerWithRegistrar:] + 292
	6   Runner                              0x000000010c3dbe89 +[GeneratedPluginRegistrant registerWithRegistry:] + 121
	7   Runner                        <…>

Running with latest versions for firebase 

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  firebase_core: ^0.4.0+5
  cloud_firestore: ^0.12.5
  firebase_auth:  ^0.11.1+6

`

**Comment by elquimeras** [comment]
Hi Marthin, to solve this, you must add the GoogleService-Info.plist to the Runner using XCODE.

Open XCODE, secondary click on "Runner" and press "Add Files to Runner", then select the GoogleService-Info.plist.

**Comment by MarthinBergs** [comment]
Worked like a charm. thank you!

**Comment by GustavoContreiras** [comment]
> Hi Marthin, to solve this, you must add the GoogleService-Info.plist to the Runner using XCODE.
> 
> 1. Open Xcode, then right-click on Runner directory and select Add Files to "Runner".
> 2. Select GoogleService-Info.plist from the file manager.
> 3. A dialog will show up and ask you to select the targets, select the Runner target.
> 4. Then add the CFBundleURLTypes attributes below into the [my_project]/ios/Runner/Info.plist file.
> 
> ```
> 
> 
> <key>CFBundleURLTypes</key>
> <array>
> 	<dict>
> 		<key>CFBundleTypeRole</key>
> 		<string>Editor</string>
> 		<key>CFBundleURLSchemes</key>
> 		<array>
> 			
> 			
> 			<string>com.googleusercontent.apps.861823949799-vc35cprkp249096uujjn0vvnmcvjppkn</string>
> 		</array>
> 	</dict>
> </array>
> 
> ```

Followed this tutorial https://firebase.google.com/docs/flutter/setup and couldn't make the app connect to Firebase;
Then I did what you told to do on your answer and it still not connecting.

What should I do?

**Comment by bretie** [comment]
> > Hi Marthin, to solve this, you must add the GoogleService-Info.plist to the Runner using XCODE.
> > 
> > 1. Open Xcode, then right-click on Runner directory and select Add Files to "Runner".
> > 2. Select GoogleService-Info.plist from the file manager.
> > 3. A dialog will show up and ask you to select the targets, select the Runner target.
> > 4. Then add the CFBundleURLTypes attributes below into the [my_project]/ios/Runner/Info.plist file.
> > 
> > ```
> > 
> > 
> > <key>CFBundleURLTypes</key>
> > <array>
> > 	<dict>
> > 		<key>CFBundleTypeRole</key>
> > 		<string>Editor</string>
> > 		<key>CFBundleURLSchemes</key>
> > 		<array>
> > 			
> > 			
> > 			<string>com.googleusercontent.apps.861823949799-vc35cprkp249096uujjn0vvnmcvjppkn</string>
> > 		</array>
> > 	</dict>
> > </array>
> > 
> > ```
> 
> Followed this tutorial https://firebase.google.com/docs/flutter/setup and couldn't make the app connect to Firebase;
> Then I did what you told to do on your answer and it still not connecting.
> 
> What should I do?

I've tried it as well and its not working. I encountered this by removing and re-adding a GoogleServiceInfo.plist to add a new app.

**Comment by kroikie** [comment]
@MarthinBergs

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/364. Any further collaboration will be done there.

**Comment by workerbee22** [comment]
@kroikie Please stop transferring issues and then closing. The linked issue is now closed with no resolution or fix.

**Comment by workerbee22** [comment]
@MarthinBergs Can you reopen the issue? Obviously not fixed.

**Comment by workerbee22** [comment]
@MarthinBergs Glad this worked for you. But many of us still seem to have the issue.

**Comment by workerbee22** [comment]
@elquimeras This fix did not work for me.

**Comment by jimmyff** [comment]
I am also having this issue.

**Comment by jimmyff** [comment]
@workerbee22 I've just managed to get it working by changing the `name` property to my projectId in the options that I pass to Firebase init. So i specify a name and projectID both with the same value.

Not ideal as I'm sure the `name` is there to be a user readable app name but it seems to be working at least.

**Comment by sunjianan9900** [comment]
> @workerbee22 I've just managed to get it working by changing the `name` property to my projectId in the options that I pass to Firebase init. So i specify a name and projectID both with the same value.
> 
> Not ideal as I'm sure the `name` is there to be a user readable app name but it seems to be working at least.
hi，what's your mean with 'name'  and 'projectID'?
Did you change any name in xcode?

**Comment by workerbee22** [comment]
See new issue https://github.com/FirebaseExtended/flutterfire/issues/1329 as this one is closed.

**Comment by KieranCTaylor** [comment]
If anyone is still having this issue after following the steps below, one thing you might want to check is if you are adding going into XCode and doing "Add files to Runner" instead of just copying the Google plist file across by yourself. Still not sure why that makes a difference but XCode is obviously registering the file somewhere for you beyond just having it present in the directory.
