### ISSUE TITLE
Wierd Error

### ISSUE THREAD

**Issue by razdahan** [flutter/flutter#34445]
Hi when I run my app it automatically crashes and i cant understand why...
It just started randomly doing it and I really need help fixing it the error wont raise anything at google.
The error I get is:
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Finished with error: Gradle task assembleDebug failed with exit code 1
`

**Comment by jonahwilliams** [comment]
I don't think we have enough information to diagnose the underlying issue. while googling I found https://stackoverflow.com/questions/45340501/gradle-sync-failed-expected-begin-array-but-was-string-at-line-1-column-1-p , which looks similar.

**Comment by razdahan** [comment]
Thank you very much the problem was that i didn't had any SDK configured I don't know why...

**Comment by jonahwilliams** [comment]
Sounds like the problem has been resolved then.
