### ISSUE TITLE
Connect iOS trait to Flutter's window brightness

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#34441]
Connect iOS trait to Flutter's window brightness

**Comment by EliasDeuss** [comment]
Any updates on this @matthew-carroll ?

**Comment by matthew-carroll** [comment]
This work was finished a little while ago. The setting is passed here:
https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L928

I'm going to close this issue.
