### ISSUE TITLE
Define pattern for transitive Android native dependencies

### ISSUE THREAD

**Issue by xster** [flutter/flutter#34444]
Decide on how we want to enforce transitive native dependencies for the Flutter engine. Answer the questions of:

- [ ] If we declare a gradle native dependency in the engine (such as android support / androidx), how do add-to-app users of the engine declare conflicting versions of those dependencies.
- [ ] Same question of java version requirements
- [ ] Can an implicit breaks in the APIs signatures of those transitive dependencies cause breakages in the add-to-app usage of our engine when we automatically bring in new versions of those transitive dependencies on flutter upgrade
- [ ] Can implicit breaks in the APIs signatures cause incompatibilities in plugins' usages of our embedding APIs when we flutter upgrade
- [ ] Look at the existing Android ecosystem landscape, how to existing libraries handle non-API breaking version resolutions when libraries have transitive dependencies. 

cc @matthew-carroll, @amirh, @tvolkert for prior discussions. 

@blasten also putting this on your radar  

Existing doc go/flutter-android-native-dependencies

**Comment by xster** [comment]
Answering this is a pre-requisite in being able to answer https://github.com/flutter/flutter/issues/32989 since we currently bake them into the materialized host module wrapper project's build.gradle.

**Comment by xster** [comment]
Downstream effects of this https://github.com/flutter/flutter/issues/34401

**Comment by xster** [comment]
Specifically, answer this question for the embedding's usage of fragments and android.arch.lifecycle.

**Comment by BugsBunnyBR** [comment]
@xster would a BoM help in the management of these dependencies on Android?
https://docs.gradle.org/5.0/userguide/managing_transitive_dependencies.html#sec:bom_import
https://mrhaki.blogspot.com/2019/04/gradle-goodness-use-bill-of-materials.html

**Comment by xster** [comment]
@blasten

That's more or less the plan. Though I'm not sure what the feature differences between BOM and POM are.
