### ISSUE TITLE
`flutter run` keeps using local engine even without `--local-engine`

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#34450]
## Overview
If `flutter run` is run with `--local-engine` and dart fails to compile (because the local engine is outdated), then when it is run without `--local-engine`, it will continue using the dart files in the local engine and fail.

## Steps to reproduce
1. Clone the latest flutter to a temp folder
  - `mkdir -p ~/tmp && cd ~/tmp && git clone git@github.com:flutter/flutter.git flutter2`
  - `alias flutter2=~/tmp/flutter2/bin/flutter` for convenience
2. Clone an old revision of flutter engine
  - `mkdir -p ~/tmp/engine2`
  - Edit `~/tmp/engine2/.gclient` with an old revision from my fork
```
solutions = [ 
  {
    "managed": False,
    "name": "src/flutter",
    "url": "git@github.com:dkwingsmt/engine.git",
    "custom_deps": {},
    "deps_file": "DEPS",
    "safesync_url": "",
  },
]
```
  - (Currently its HEAD is at a revision at Jun 3, which is old enough. In case I've updated the revision, checkout `f9ce01674ed6dcdf6ad3c5b80cef6277d851cb50`)
  - `cd ~/tmp/engine2/src`, then `gclient sync`
3. Build engine
  - `./flutter/tools/gn --unoptimized && ./flutter/tools/gn --android --android-cpu x86 --unoptimized`
  - `ninja -C out/android_debug_unopt && ninja -C out/host_debug_unopt`
4. Run app
  - `cd ~/tmp/flutter2/examples/flutter_gallery`
  - Start an emulator with `crow`
  - Run the app with local engine `flutter2 run --local-engine-src-path ~/tmp/engine2/src --local-engine=android_debug_unopt_x86`, which will fail as expected
  - Then run it without local engine `flutter2 run`, it will still fail, which is unexpected

## Expected result
`flutter run` without `--local-engine` should use the default engine, no matter what it was previously run with.

**Comment by dkwingsmt** [comment]
+cc @Hixie @mklim @dnfield

**Comment by dnfield** [comment]
Can you share `echo $FLUTTER_ENGINE`?

**Comment by dkwingsmt** [comment]
@dnfield I ran it at my terminal and it is empty.

**Comment by zanderso** [comment]
@jonahwilliams Will addition/removal of the `--local-engine` flag trigger a rebuilt?

**Comment by jonahwilliams** [comment]
It looks like localEngine isn't marked as an input in gradle, so if everything else is fully cached we might keep using the old engine:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/flutter.gradle#L748
