### ISSUE TITLE
Consider deleting all io.flutter.facade classes

### ISSUE THREAD

**Issue by xster** [flutter/flutter#34458]
The io.flutter.facade classes autogenerated into .android seem to be an older attempt to create an embedding API that is mostly replaced. It adds maintenance cost since they need to keep building when the modules build and adds cognitive load since users need to realize what they are and subsequently ignore them. 

Delete these from the template. 

cc @blasten @matthew-carroll

**Comment by xster** [comment]
Another component of this bug is that once we merge #39384, people on master would have their existing project break. Part of the migration would be to announce that if their add-to-app code is currently importing `io.flutter.facade`, `flutter make-host-app-editable` should be used to keep that code in their project so that it doesn't get deleted the next time `flutter packages get` is run. 

Once a manual migration to `io.flutter.embedding` is done, the `/android` directory in the module can just be deleted to complete the migration.

**Comment by blasten** [comment]
Once the new Android embedding is turn on by default, we can close this issue since the new embedding doesn't use the facade class.

**Comment by xster** [comment]
Discussed offline. Before we flip the switch https://github.com/flutter/flutter/issues/43638, the task is to send out an announcement email instructing people how to preserve and hold onto their facade classes if they want to keep them.

**Comment by oth-libs** [comment]
Can I please get a link to that manual you're referring to

**Comment by xster** [comment]
it's at flutter.dev/go/android-project-migration
