### ISSUE TITLE
Image.network handle bad url image, like 404

### ISSUE THREAD

**Issue by cosinus84** [flutter/flutter#34451]
The code below still shows as an exception. This is a very common situation.
```
 Image.network("${image}x",
                    fit: BoxFit.cover,
                    width: 150,
                    height: 150, loadingBuilder: (BuildContext context,
                        Widget child, ImageChunkEvent loadingProgress) {
                  if (loadingProgress == null) {
                    return child;
                  }
                  return Platform.isIOS
                      ? CupertinoActivityIndicator(radius: 20)
                      : CircularProgressIndicator();
                });
              } catch(_) {
                return Container();
              }
```

[✓] Flutter (Channel dev, v1.7.3, on Mac OS X 10.14.5 18F132, locale en-RO)
    • Flutter version 1.7.3 at /Users/devx/flutter
    • Framework revision 362b999b90 (6 days ago), 2019-06-07 12:43:27 -0700
    • Engine revision 0602dbb275
    • Dart version 2.3.2 (build 2.3.2-dev.0.1 6e0d978505)

**Comment by The-Redhat** [comment]
You can use [preCacheImage](https://api.flutter.dev/flutter/widgets/precacheImage.html) to handle errors.

**Comment by cosinus84** [comment]
I will use what you suggested but this not what you expect from all million examples out there on how easy is to show an image from network with flutter. 
I think this should be fixed on the Image.network

**Comment by The-Redhat** [comment]
Yes I share your opinion. But my issue regarding this problem was closed with no comments.

**Comment by cosinus84** [comment]
Btw, thanks :)

**Comment by mikhail-tokarev** [comment]
HI @cosinus84 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it

**Comment by henperi** [comment]
I'm having the same issue. Can someone please share his/her implementation if possible?

**Comment by chornbe** [comment]
Why in the world doesn't this provide some way to gracefully capture the exception and just provide some other optional image, akin to loadingBuilder. Why wouldn't there be something like exceptionBuilder:... or something? 

Especially when stuffing the widget into a big build block that you may or may not be able or willing to otherwise break up into small parts. Maybe I'll circle back and add it to the core code after I get this project done; I don't have time at the moment. :(

**Comment by alexgarciaju** [comment]
@mikhail-tokarev this issue is still happening
