### ISSUE TITLE
flutter clean should clean the iOS Runner project/workspace

### ISSUE THREAD

**Issue by ahusseini** [flutter/flutter#34462]
## Proposal

Cleaning the derived data for Runner is one solution to unknown issues faced with the add to app integration. `flutter clean` should also run `xcodebuild clean` on the Runner project for iOS.

per discussion on #34300

**Comment by jmagman** [comment]
Notes:
```
$ xcodebuild clean
error: Could not delete `/Users/Projects/test_app_create/build/ios` because it was not created by the build system.

** CLEAN FAILED **
```
`xcodebuild clean` is defaulting to `-project Runner.xcodeproj -scheme Runner`, and `flutter clean` already deletes the `build/ios` directory.

What needs to be cleaned is the xcworkspace.
```
$ xcodebuild clean -workspace Runner.xcworkspace -scheme Runner

** CLEAN SUCCEEDED **
```
