### ISSUE TITLE
What is the relationship between fontSize, textScaleFactor, & TextField height?

### ISSUE THREAD

**Issue by blac3777** [flutter/flutter#34467]
Is there an equation to calculate TextField height (when collapsed, w/o padding, default font size, etc.) as a function of textScaleFactor?

Based on a test I did, my intuition says no... These were my results:

```
| textScaleFactor | TextField height |
|-----------------|------------------|
| 0.8             | 19               |
| 0.9             | 19               |
| 1.0             | 19               |
| 1.1             | 21               |
| 1.3             | 24               |
| 1.5             | 28               |
| 1.7             | 32               |
| 2.0             | 33               |
```

**Comment by LongCatIsLooong** [comment]
Do https://stackoverflow.com/questions/52138524/what-is-the-difference-between-fontsize-and-textscalefactor-in-flutter and https://api.flutter.dev/flutter/widgets/Text/textScaleFactor.html answer your question? Generally you don't have to know the exact height of a text field. Could you provide a use case where the height of a text field is needed?
