### ISSUE TITLE
On startup on Android, the screen flickers

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3447]
When you start a Flutter app on Android, the screen sometimes flickers once at the start.

(This is more visible when you have a precompiled build.)

**Comment by abarth** [comment]
What does it flicker?  It should start out black and then paint the final image.

**Comment by Hixie** [comment]
The Android home screen, I believe.

**Comment by Hixie** [comment]
(Have Ivan show you on his phone.)

**Comment by Hixie** [comment]
@iposva-google

**Comment by abarth** [comment]
We should probably explicitly paint black at startup instead of waiting for Dart to drive the first paint.

**Comment by abarth** [comment]
My first attempt at this didn't work, but I'll try something else.

**Comment by sethladd** [comment]
I'm noticing this, both with AOT and with the JIT build.

**Comment by abarth** [comment]
I can repro.
