### ISSUE TITLE
D/skia    (19623): ERROR: 0:3: 'GL_EXT_shader_framebuffer_fetch' : extension is not supported

### ISSUE THREAD

**Issue by xb284524239** [flutter/flutter#34479]
1. OS: Mac OS 10.14.2

2. Android Studio: 
    Current Version: Android Studio 3.4.1
    Android SDK Tools: 26.1.1
    Android Platform Version: API 28: Android 9.0(Pie) revision 6

3. When i use these two widgets: CupertinoActionSheet or CupertinoAlertDialog in my application, then the console message looks wrong:

D/skia    (19623): GLSL compilation error
D/skia    (19623): ----------------------
D/skia    (19623): GLSL:
D/skia    (19623):    1	#version 300 es
D/skia    (19623):    2	
D/skia    (19623):    3	#extension GL_EXT_shader_framebuffer_fetch : require
D/skia    (19623):    4	precision mediump float;
D/skia    (19623):    5	inout mediump vec4 sk_FragColor;
D/skia    (19623):    6	in mediump vec4 vcolor_Stage0;
D/skia    (19623):    7	void main() {
D/skia    (19623):    8	    mediump vec4 outputColor_Stage0;
D/skia    (19623):    9	    {
D/skia    (19623):   10	        outputColor_Stage0 = vcolor_Stage0;
D/skia    (19623):   11	    }
D/skia    (19623):   12	    {
D/skia    (19623):   13	        mediump vec4 _dstColor = sk_FragColor;
D/skia    (19623):   14	        sk_FragColor.w = outputColor_Stage0.w + (1.0 - outputColor_Stage0.w) * _dstColor.w;
D/skia    (19623):   15	        if (2.0 * _dstColor.x <= _dstColor.w) {
D/skia    (19623):   16	            sk_FragColor.x = (2.0 * _dstColor.x) * outputColor_Stage0.x;
D/skia    (19623):   17	        } else {
D/skia    (19623):   18	            sk_FragColor.x = _dstColor.w * outputColor_Stage0.w - (2.0 * (outputColor_Stage0.w - outputColor_Stage0.x)) * (_dstColor.w - _dstColor.x);
D/skia    (19623):   19	        }
D/skia    (19623):   20	        if (2.0 * _dstColor.y <= _dstColor.w) {
D/skia    (19623):   21	            sk_FragColor.y = (2.0 * _dstColor.y) * outputColor_Stage0.y;
D/skia    (19623):   22	        } else {
D/skia    (19623):   23	            sk_FragColor.y = _dstColor.w * outputColor_Stage0.w - (2.0 * (outputColor_Stage0.w - outputColor_Stage0.y)) * (_dstColor.w - _dstColor.y);
D/skia    (19623):   24	        }
D/skia    (19623):   25	        if (2.0 * _dstColor.z <= _dstColor.w) {
D/skia    (19623):   26	            sk_FragColor.z = (2.0 * _dstColor.z) * outputColor_Stage0.z;
D/skia    (19623):   27	        } else {
D/skia    (19623):   28	            sk_FragColor.z = _dstColor.w * outputColor_Stage0.w - (2.0 * (outputColor_Stage0.w - outputColor_Stage0.z)) * (_dstColor.w - _dstColor.z);
D/skia    (19623):   29	        }
D/skia    (19623):   30	        sk_FragColor.xyz += _dstColor.xyz * (1.0 - outputColor_Stage0.w) + outputColor_Stage0.xyz * (1.0 - _dstColor.w);
D/skia    (19623):   31	        sk_FragColor = sk_FragColor;
D/skia    (19623):   32	    }
D/skia    (19623):   33	}
D/skia    (19623):   34	
D/skia    (19623): Errors:
D/skia    (19623): ERROR: 0:3: 'GL_EXT_shader_framebuffer_fetch' : extension is not supported
D/skia    (19623): ERROR: 0:5: 'inout' : syntax error 
D/skia    (19623): 

4. Flutter Doctor:
pauldeMacBook-Pro:family_doctor_app_resident paul$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.2 18C54, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.35.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by xb284524239** [comment]
Help！Help！Help！

I need help !

**Comment by amitkhairnar44** [comment]
@xb284524239 Are you running the app in android emulator?

**Comment by xb284524239** [comment]
> @xb284524239 Are you running the app in android emulator?

Yes, it's wrong only in android emulator.

**Comment by xb284524239** [comment]
> @xb284524239 Are you running the app in android emulator?

Yes, it's wrong only in android emulator.

**Comment by xb284524239** [comment]
@amitkhairnar44 

Yes, it's wrong only in android emulator.

**Comment by amitkhairnar44** [comment]
@xb284524239 See this issue #34239

**Comment by xb284524239** [comment]
@amitkhairnar44 

Thank you! I have fixed it.
