### ISSUE TITLE
Specifying assets is too time-consuming

### ISSUE THREAD

**Issue by tianxiawoyougood** [flutter/flutter#34488]
Loading image resources is tedious and time consuming. Is there a convenient way? I like the way iOS manages pictures.

**Comment by tianxiawoyougood** [comment]
![WX20190614-180141](https://user-images.githubusercontent.com/9163388/59501647-8eb2cb00-8ece-11e9-95ad-f0a59d57b365.png)

**Comment by Zazo032** [comment]
You can write just `- images/` and all the images in that directory will be imported. If you have subdirectories you have to imported them too (e.g. `- images/android`)

**Comment by tianxiawoyougood** [comment]
ths
