### ISSUE TITLE
Please add icon  invisibility eye(hide password). Thanks.!

### ISSUE THREAD

**Issue by trgan96** [flutter/flutter#34483]

**Comment by ahusseini** [comment]
are you looking for `Icons.visibility_off`?

**Comment by Sach97** [comment]
Hi @trgan96 You can do this with a stateful widget. Take a look at this [SO](https://stackoverflow.com/questions/49125064/how-to-show-hide-password-in-textformfield)

**Comment by kawal7415** [comment]
We are looking for an eye icon with a half cut over it.

Thanks

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by jh-orange** [comment]
I suspect the request is for what appears in the Google password (change) text field.  While at it, maybe this should be a (sub option of 'obscureText'

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by douglas-wiliam** [comment]
> are you looking for `Icons.visibility_off`?

Off course xD
