### ISSUE TITLE
Add FlutterViewController to iOS UIScrollView Happen Gestures conflict

### ISSUE THREAD

**Issue by ppShuaiShuai** [flutter/flutter#34482]
I'm using flutter vc to show the ui and add it to the native `uiscrollview`. In flutter I use the `singlescrollview`, it happen gestures conflict. how can I solve this problem. looking forward to your reply . 3Q

**Comment by ppShuaiShuai** [comment]
https://github.com/flutter/flutter/issues/27071

**Comment by janmoppel** [comment]
Hello @ppShuaiShuai !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by HaoXianSen** [comment]
I have the same problem，But I think solved the problem better。Here's my solution，
1. Write a subclass of UIScrollView, and implement gesture protocol
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch {
    if ([NSStringFromClass(touch.view.class) isEqualToString:@"FlutterView"]) {
        return NO;
    }
    return YES;
}
2. Write a subclass of FlutterViewController， implement touches method
- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
    [super touchesBegan:touches withEvent:event];
    [self touchesBegan];
}

- (void)touchesMoved:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
    [super touchesMoved:touches withEvent:event];
    UITouch *touch = [touches anyObject];
    [self touchMoveWithTouch:touch];
}

- (void)touchesEnded:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
    [super touchesEnded:touches withEvent:event];
    [self touchEnd];
}

- (void)touchesCancelled:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
    [super touchesCancelled:touches withEvent:event];
    [self touchEnd];
}

- (void)touchesBegan {
    UIScrollView *superView = (UIScrollView *)self.view.superview;
    superView.panGestureRecognizer.enabled = NO;
}

- (void)touchMoveWithTouch:(UITouch *)touch {
    CGPoint previoursLocation = [touch previousLocationInView:self.view];
    CGPoint location = [touch locationInView:self.view];
    CGFloat deltax = fabs(location.x - previoursLocation.x);
    CGFloat deltay = fabs(location.y - previoursLocation.y);
    UIScrollView *superView = (UIScrollView *)self.view.superview;
    if (deltax > 2 && deltay <= 5) {
        CGPoint offset = superView.contentOffset;
        superView.panGestureRecognizer.enabled = YES;
        [superView.delegate scrollViewWillBeginDragging:superView];
        [superView setContentOffset:CGPointMake(offset.x - (location.x - previoursLocation.x), offset.y)];
    } else {
        superView.panGestureRecognizer.enabled = NO;
    }
}

- (void)touchEnd {
    UIScrollView *superView = (UIScrollView *)self.view.superview;
    superView.panGestureRecognizer.enabled = YES;
    CGPoint offset = superView.contentOffset;
    CGFloat offsetX = offset.x;
    if (offsetX > (1 * self.view.width+ self.view.width * 1 / 3)) {
        [superView setContentOffset:CGPointMake(2*self.view.width, offset.y) animated:YES];
    } else if (offsetX <=  self.view.width * 2 / 3) {
        [superView setContentOffset:CGPointMake(0, offset.y) animated:YES];
    } else {
        [superView setContentOffset:CGPointMake(self.view.width, offset.y) animated:YES];
    }
    [superView.delegate scrollViewDidEndDecelerating:superView];
}

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
