### ISSUE TITLE
Long press the paste option on TextField to display English ，how to display Chinese？

### ISSUE THREAD

**Issue by cwwng** [flutter/flutter#34487]
Now shown below：
![E](https://user-images.githubusercontent.com/12265892/59500980-20b9d400-8ecd-11e9-8a85-4989698f926f.png)

We want to display the following picture：
![C](https://user-images.githubusercontent.com/12265892/59501096-65456f80-8ecd-11e9-855e-0513568ef6cf.png)

**Comment by justinmc** [comment]
Make sure you set your local to Chinese and it should work.  Take a look at our [localization documentation](https://flutter.dev/docs/development/accessibility-and-localization/internationalization) and make sure you've got that set up properly.

For example, here is a simple app with a Chinese locale running on a phone whose language is set to Chinese:

<img width="200" src="https://user-images.githubusercontent.com/389558/59523100-458a5900-8e85-11e9-870d-397533c85877.png" />


```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      localizationsDelegates: [
         GlobalMaterialLocalizations.delegate,
         GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: [
          const Locale.fromSubtags(languageCode: 'zh'),
       ],
      home: Scaffold(
        appBar: AppBar(
          title: Text('Flutter Demo Home Page'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextField(),
            ],
          ),
        ),
      ),
    );
  }
}
```
