### ISSUE TITLE
Camera Stretching in flutter

### ISSUE THREAD

**Issue by Loopex2019** [flutter/flutter#34498]
I used the Camera Package and the `CameraPreview()` worked fine for me . But the Problem that it is always stretching on  the Android Emulator . So i used a real Android Device and it is always  stretching too . Does anybody have an Idea of why is that happening and how to solve it ?

**Comment by khflab** [comment]
You must provide more information like:

- Could you provide a print screen?
- Can you replicate it on another Android Device?
- What Flutter version/channel you are using
- What image you are running on Android Emulator
- What Android Device/OS you are using

Only with this we can help.

**Comment by Loopex2019** [comment]
Great i am using Android Oreo .  And i was using Samsung Galaxy J7 Core. And i tried it on another Android Device and both of them had the same Issues. These Devices were Samsung Galaxy J5 and 
Samsung Samsung Galaxy A50. And here is a Footage of the Stretching in Samsung Galaxy J7 Core :
![Screenshot_20190617-172516](https://user-images.githubusercontent.com/49901727/59616818-77214f80-9125-11e9-8865-ac189f2f68ba.jpg)
In Flutter i am using the latest Version 1.5 and i am on the stable channel.

**Comment by KonstantinKai** [comment]
Hi, I have the same issue
```

**Comment by KonstantinKai** [comment]
@Loopex2019 I found a solution that fixes this issue on [stackoverflow](https://stackoverflow.com/questions/49946153/flutter-camera-appears-stretched)

**Comment by Loopex2019** [comment]
Great I will try . If it succeed , I will tell

**Comment by Loopex2019** [comment]
Well no it still the same Issue . I don't really know what to do ?

**Comment by KonstantinKai** [comment]
@Loopex2019, hmm... Look at my code. It works for me.

```sh
[✓] Flutter (Channel master, v1.7.9-pre.2, on Mac OS X 10.14.4 18E227, locale en-UA)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (5 available)
```

```dart
@override
  Widget build(BuildContext context) {
    Widget child = Container();

    if (_inited) {
      final size = MediaQuery.of(context).size;
      final deviceRatio = size.width / size.height;
      child = Transform.scale(
        scale: _controller.value.aspectRatio / deviceRatio,
        child: Center(
          child: AspectRatio(
            aspectRatio: _controller.value.aspectRatio,
            child: CameraPreview(_controller),
          ),
        ),
      );
    }

    return WithStatusBarStyle(
      child: Scaffold(
        backgroundColor: Colors.black,
        body: Stack(
          fit: StackFit.expand,
          children: <Widget>[
            child,
            // ...
            // another UI
            // ...
          ],
        ),
      ),
    );
  }
```

**Comment by Loopex2019** [comment]
I did the same as you : and here is the result 
![20190629_145846](https://user-images.githubusercontent.com/49901727/60384518-0c560980-9a7f-11e9-8904-d482401fd6da.jpg)

**Comment by Loopex2019** [comment]
And here is my Code : 
Widget _cameraPreview(double deviceWidth) {
    final size = MediaQuery.of(context).size;
    final deviceRatio = size.width / size.height;
    if (_controller?.value?.isInitialized == null) {
      return Center(child: CircularProgressIndicator());
    } else {
      return OrientationBuilder(
        builder: (context, orientation) {
          if (orientation == Orientation.landscape) {
            return Transform.scale(
              scale: _controller.value.aspectRatio / deviceRatio,
              child: Center(
                child: AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: CameraPreview(_controller),
                ),
              ),
            );
          } else {
            return Transform.scale(
              scale: _controller.value.aspectRatio / deviceRatio,
              child: Center(
                child: AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: CameraPreview(_controller),
                ),
              ),
            );
          }
        },
      );
    }
  }

**Comment by Loopex2019** [comment]
Hi there i realized that the StackOverflow Solution only works for The Back Camera not the front one. So it is only solved on the back Camera , the front still the same .

**Comment by Loopex2019** [comment]
Thanks for the Support it worked for me fine
