### ISSUE TITLE
`flutter doctor` should complain when dartlang dart sdk is not flutter's

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#3449]
I had my dartlang dart sdk set to a 1.12 dart install elsewhere in my repo.  I think that may have been causing me to see analysis error in examples/material_gallery.

I would have expected doctor (or something in flutter) to have warned me that my dartlang plugin was configured to an old, possibly non-flutter compatible sdk?

Maybe I'm asking for the wrong thing?  @devoncarew

**Comment by devoncarew** [comment]
This sounds right - we can add a check in `flutter doctor` to pull the `sdkLocation` out of atom's config.cson file, and complain when it's != flutter's vendored sdk.

**Comment by eseidelGoogle** [comment]
I believe this was specific to Atom, and is likely now covered by other checks in IntelliJ?  Speculatively closing. FYI @pq (devon already cc'd too).
