### ISSUE TITLE
The following assertion was thrown running a test: 'package:flutter_test/src/binding.dart': Failed assertion: line 567 pos 14: '_pendingExceptionDetails != null'

### ISSUE THREAD

**Issue by Muldec** [flutter/flutter#34499]
## Steps to Reproduce

(see [full code](https://gist.github.com/Muldec/03a4c8f5dbfc9af475a845bc0a5bdd8f))

1. Create a widget that contains a button. When the button is pressed show a `FutureBuilder` and initialize a `Future` that will throw an exception.
2. Create a `testWidgets` that taps the button and override `FlutterError.onError` to test the exception thrown.
3. Run the test

### Logs

```
with Future finds exception
YES
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A test overrode FlutterError.onError but either failed to return it to its original state, or had
unexpected additional errors that it could not handle. Typically, this is caused by using expect()
before restoring FlutterError.onError.
'package:flutter_test/src/binding.dart':
Failed assertion: line 567 pos 14: '_pendingExceptionDetails != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#2      TestWidgetsFlutterBinding._runTest.handleUncaughtError (package:flutter_test/src/binding.dart:567:14)
#3      TestWidgetsFlutterBinding._runTest.<anonymous closure> (package:flutter_test/src/binding.dart:572:28)
#18     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1009:17)
#20     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:997:35)
(elided 32 frames from class _AssertionError, class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)

The test description was:
  with Future finds exception
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +1 -2: C:\Projects\projet_65\mobile_app\test/ui/exception_test.dart: with Future finds exception [E]
  Test failed. See exception logs above.
  The test description was: with Future finds exception
```

### flutter analyze
```
>flutter analyze
Analyzing project...
No issues found! (ran in 2.1s)
```
### flutter doctor
```
[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17763.557], locale en-GB)
    • Flutter version 1.6.3 at C:\flutter
    • Framework revision bc7bc94083 (3 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\az02332\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.4
    • Flutter plugin version 31.0.3
    • Dart plugin version 182.5124

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7221

[√] VS Code (version 1.33.1)
    • VS Code at C:\Users\az02332\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.2
```

**Comment by VladyslavBondarenko** [comment]
Reproduces with current master `1.21.0-6.0.pre.90`

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.90, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.90 at /Users/nevercode/dev/flutter
    • Framework revision 531ee9452a (85 minutes ago), 2020-07-29 02:26:03 -0400
    • Engine revision 1ba310017c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (6 available)
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • iPhone 11 Pro Max (mobile)  • 55C8466B-5367-492B-8EFE-EC45D980571F     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

**Comment by ivan-horchakov** [comment]
I'm facing such error when the "expect()" fails during running integration tests (migrated from flutter_driver to new API) via CLI command "flutter drive --driver=test_driver/integration_test.dart --target=integration_test/smoke_test.dart" instead of telling what went wrong (I mean "Expected:" and "Actual:"):

[ERROR:flutter/shell/common/shell.cc(210)] Dart Unhandled Exception: 'package:flutter_test/src/binding.dart': Failed assertion: line 754 pos 14: '_pendingExceptionDetails != null': A test overrode
FlutterError.onError but either failed to return it to its original state, or had unexpected additional errors that it could not handle. Typically, this is caused by using expect() before restoring FlutterError.onError.,
stack trace: #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)

[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
 [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (not installed)
[✓] VS Code (version 1.51.0)
[✓] Connected device (1 available)
! Doctor found issues in 1 category.

**Comment by theiskaa** [comment]
Any updates here?

**Comment by lintdeveloper** [comment]
What's the update on this issue

**Comment by SebghatYusuf** [comment]
Any updates??

**Comment by ivan-horchakov** [comment]
Flutter team, please help us with this problem, because it is not informative and brings much more time to debug integration tests. Also, it is reproducible on the latest stable Flutter:

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (2 available)

**Comment by searchy2** [comment]
Hope the Flutter team can take a look at this issue soon because all errors seem to output the error above instead of the correct error stack.

Trying to do what the error says and resetting FlutterError.onError did not work for me. 
>     FlutterError.onError = (details) => FlutterError.presentError(details);
>     FlutterError.onError = (_) => null;

**Comment by MilesAdamson** [comment]
I had this problem and I believe it's because the test starts running before `async` work is done in main. I added `await pumpEventQueue();` as the first line of my tests and I no longer get this error

``
  group('end-to-end test', () {
    testWidgets("Logging in", (tester) async {
      await pumpEventQueue();
```

**Comment by dvagala** [comment]
On flutter 2.5.0 this seems to be fixed. It no longer gets stuck when running the test. So it continues to execute the rest of the tests. Although it still shows the `_pendingExceptionDetails != null` error

**Comment by Jonas-Sander** [comment]
```dart
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets("my test", (WidgetTester tester) async {
    await app.main();
    await tester.pumpAndSettle();
    expect(true, false);
  });
}
```

This doesn't fail for me but will result in a time out.
If inside our app I don't override `FlutterError.onError` it fails properly.

This doesn't make any sense to me really. The failure is inside `testWidgets`, not inside the app. This is really confusing behavior.

**Comment by dvagala** [comment]
@Jonas-Sander is it on flutter 2.5.0? You sample code indeed timed out when I was trying on 2.2.0, but on the 2.5.0 it correctly fails, and move along

**Comment by Jonas-Sander** [comment]
Ah yeah I'm still on 2.2.0, got a bit confused with the versions, sorry :)

**Comment by Artur512** [comment]
It happens on integration tests.  Actually its possible to pass only happy path. Any updates?

**Comment by being-yash-t** [comment]
Any updates?

**Comment by hattersharath** [comment]
Same issue on 2.8.1 also

**Comment by 3nd3rs0nn** [comment]
Any update about this? I have the same error with Flutter `2.8.1`

**Comment by Tryneeth** [comment]
Any updates about this? It's also on 2.10.3

**Comment by andrewsheridan** [comment]
Also having this issue, Flutter 2.10.5.

**Comment by Yifei233** [comment]
I met the same error using Flutter 2.10.5

**Comment by CalebRBPittman** [comment]
Again, same error, Flutter 2.10.5

**Comment by thphuc** [comment]
Same error on Flutter 3.0.1

**Comment by hananmalka** [comment]
Any updates on this? 
We can't executing tests on virtual device

**Comment by jrc2139** [comment]
i was struggling with this error (flutter 3.0.1) because i thought maybe an unhandled error was causing this. 



however, i fixed it by wrapping the `runApp` call in the test with `runZoneGuarded` 💪

**Comment by hananmalka** [comment]
@jrc2139 - Unfortunately it doesn't work for me :(

**Comment by jrc2139** [comment]
> @jrc2139 - Unfortunately it doesn't work for me :(
> Also with version 3.0.1

you trying adding an isolate to catch an error as well  

```
Isolate.current.addErrorListener(RawReceivePort((pair) async {

final List<dynamic> errorAndStacktrace = pair;

print('${errorAndStacktrace.first}\n${errorAndStacktrace.last}');

}).sendPort);

```

**Comment by hananmalka** [comment]
> Isolate.current.addErrorListener(RawReceivePort((pair) async {
> 
> final List<dynamic> errorAndStacktrace = pair;
> 
> print('${errorAndStacktrace.first}\n${errorAndStacktrace.last}');
> 
> }).sendPort);

Where should I put this code?

**Comment by huwq1987** [comment]
I found this issue when running integration test on Flutter 3.0.0, and I fixed it:
```
// integration_test/smoke_test.dart

void main() async {
  final FlutterExceptionHandler? originalOnError = FlutterError.onError;

  testWidgets('integration test', (WidgetTester tester) async {
    await runMyApp();
    await tester.pumpAndSettle();
    // reset onError EACH TIME after calling pumpAndSettle()
    FlutterError.onError = originalOnError;

    // ...
  });
}
```

**Comment by amirmohammadshamss** [comment]
Same issue, Flutter 3.0.4

**Comment by Charlinjoeaht** [comment]
> I found this issue when running integration test on Flutter 3.0.0, and I fixed it like this:
> 
> ```
> // integration_test/smoke_test.dart
> 
> void main() async {
>   testWidgets('integration test', (WidgetTester tester) async {
>     final FlutterExceptionHandler? originalOnError = FlutterError.onError;
>     await runMyApp();
>     await tester.pumpAndSettle();
>     // reset onError after calling pumpAndSettle()
>     FlutterError.onError = originalOnError;
> 
>     // ...
>   });
> }
> ```

Unfortunately this doesn't work for me

**Comment by kanakapalli** [comment]
I have tried that same with flutter 3.0.4, it seems to be working right.

**Comment by kanakapalli** [comment]
I have tried that same with flutter 3.0.4, it seems to be working fine.

**Comment by workerbee22** [comment]
Also have this iss on flutter `3.0.5`

**Comment by fadulalla** [comment]
I'm on `3.0.4` and it's happening. I really don't want to change my `main` or have different entry points just to appease `integration_tests`, so as a workaround until the Flutter team fix this, I wrapped `expect` in my own function which restores `onError` just before `expect`ing and sets it back to what it was right after:

```dart
//file: utils/integration_test_helpers.dart
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

var _originalOnError;
void initCustomExpect() {
  _originalOnError = FlutterError.onError;
}

// A workaround for: https://github.com/flutter/flutter/issues/34499
void expectCustom(
  dynamic actual,
  dynamic matcher, {
  String reason,
  dynamic skip, // true or a String
}) {
  final onError = FlutterError.onError;
  FlutterError.onError = _originalOnError;
  expect(actual, matcher, reason: reason, skip: skip);
  FlutterError.onError = onError;
}
```
and then in my integration tests:
```dart
import 'utils/integration_test_helpers.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('end-to-end test', () {
    testWidgets('app loads and home screen is shown', (tester) async {
      // I call this at the top of each test
      initCustomExpect();

      app.main();
      await tester.pumpAndSettle();

      // For the remainder of the test, I just use my custom expect
      expectCustom(find.text('hello'), findsOneWidget);
    });
  });
}
```
Now the nasty exception is gone and I get the actual exception like how it should be.

**Comment by AdamBridges** [comment]
> i was struggling with this error (flutter 3.0.1) because i thought maybe an unhandled error was causing this.
> 
> however, i fixed it by wrapping the `runApp` call in the test with `runZoneGuarded(() => runApp(MyApp), (e,s) => print('$e\n$s))` 💪

Building off this suggestion, my app's `main()` calls `runZoneGuarded` first before anything as per Firebase Crashlytics documentation. As such, any calls to my app's `main()` function within an integration test requires that it be wrapped like so: `await runZoned(() async => app.main())`.

Note that this may not be the proper solution but it has been working for me thus far using Flutter `3.3.5` and seems the easiest to manage. I'll try to follow up if things change.

**Comment by AdamNSmith** [comment]
I'm still seeing this too.

**Comment by tarekmabdallah91** [comment]
I'm facing this issue too, any help please ?

**Comment by ulisseshen** [comment]
> I found this issue when running integration test on Flutter 3.0.0, and I fixed it like this:
> 
> ```
> // integration_test/smoke_test.dart
> 
> void main() async {
>   testWidgets('integration test', (WidgetTester tester) async {
>     final FlutterExceptionHandler? originalOnError = FlutterError.onError;
>     await runMyApp();
>     await tester.pumpAndSettle();
>     // reset onError after calling pumpAndSettle()
>     FlutterError.onError = originalOnError;
> 
>     // ...
>   });
> }
> ```

This worked for me on Flutter 3.3.10 stable channer.. Tks

**Comment by goderbauer** [comment]
The code snippet in https://github.com/flutter/flutter/issues/34499#issuecomment-1381789793 shows how to do this correctly.

**Comment by IlyaMax** [comment]
@goderbauer but this is still a workaround because we need to add this in every test which needs `expect`
