### ISSUE TITLE
aboutDialog documentation does not have a sample.

### ISSUE THREAD

**Issue by campcoxconsultants** [flutter/flutter#34495]
Every widget should have at least one sample.  aboutDialog does not have one.  The description can probably be improved as well.  The description says it shows name, version and copywrite while the constructor has name, version, and legalese.

@Piinks

**Comment by campcoxconsultants** [comment]
I would like to fix this, can someone with the power to, assign it to me?

**Comment by campcoxconsultants** [comment]
Also there is a children but there is no indication in what direction/order those would be laid out.  The documentation should tell us.

**Comment by jaumard** [comment]
@escamoteur I think this one is fixed :) PR is merged

**Comment by escamoteur** [comment]
Cool then I close it
