### ISSUE TITLE
There is no way to test code guarded by `kReleaseMode`

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#34505]
The only way to test this code is to run it on a device in release mode, which is only possible on a physical device.

We should provide a way for flutter_test to set the constant to true.  However, we have to do so in a way that doesn't remove its const-ness, and doesn't prevent treeshaking from working.

Example:

```dart
import 'package:flutter/foundation.dart';

String foo() {
  if (kReleaseMode) {
    return null;
  }
  return _calculateABunchOfStuffAndReturnALongString();
}
```

Is only testable in the non-release branch currently.

**Comment by dnfield** [comment]
I did make an attempt to pass in `-Ddart.vm.product=true` to the test kernel compiler, but that didn't seem to make a difference.

**Comment by jonahwilliams** [comment]
In JIT mode the flags don't get loaded from the kernel

**Comment by dnfield** [comment]
Can we tell it to do that? Or is that a dart VM thing?

**Comment by jonahwilliams** [comment]
I believe it requires a pending update to how const evaluation is handled in the VM, though I have not been able to find a tracking issue for it. This was also the case for https://github.com/flutter/flutter/pull/31696 which is why there isn't a separate flag for debug mode.

**Comment by dnfield** [comment]
This is slightly alleviated by adding a smoke test for release mode in #34474 

It would still be really nice to be able to unit test stuff that behaves differently based on `kReleaseMode`.

**Comment by littleGnAl** [comment]
This is a very useful feature. In our use case, we only want to test whether the exception will be handled in release mode, 
```dart
  void _tryCatch(VoidCallback callback) {
    if (kDebugMode) {
      callback();
    } else {
      try {
        callback();
      } catch (e) {
        // TODO(littlegnal): Should report the exception to firebase.
      }
    }
  }
```
but it is not easy to test it at this time.
