### ISSUE TITLE
What to set the testdevices in firebase-admob (targetinfo) when releasing the app with ads in flutter

### ISSUE THREAD

**Issue by headspy** [flutter/flutter#34506]
I am developing an app and I am integrating ads into it.

Initially, I am specifying the test devices as my app id which I got from the logs. 

The ads are working fine for both test and real ad units when I am using the app id in the test devices.

But when i removed the app id from test devices and set the testdevices as null(`<String>[]`) in the target info. The ads are not showing up in the debug mode or apk (created using "flutter build apk")

- So, can anyone please tell me how to release the app with ads in flutter(what to set the testdevices during release).  There are no proper instructions on the web.

- One more question AdMob doesn't work when we put the testdevices as `<String>[]`. It says that unable to load the ads error 3.

- **And can you update the info in the firebase_admob plugin page? Some of the parameters are deprecated**

**Comment by kroikie** [comment]
@headspy

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1179. Any further collaboration will be done there.
