### ISSUE TITLE
dartlang autolocate button prefers older sdk over flutters

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#3450]
I clicked the autolocate button in the dartlang plugin this evening, it reset my sdk from flutter/bin/cache/dart-sdk (1.15) to /usr/local/opt/dart/ibexect (1.13).  Is that expected behavior?  @devoncarew

**Comment by sethladd** [comment]
Moved over to https://github.com/dart-atom/dartlang

**Comment by devoncarew** [comment]
Thanks for moving the issue! We should be preferring the flutter sdk, if the user has set up the `flutter` atom plugin (it's installed, and there's a value for `flutter_root`).
