### ISSUE TITLE
[web]: TableBorder does not render correctly

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#34511]
Given

```dart
Table(
  border: TableBorder.all(color: Colors.green, width: 3),
  children: [
    TableRow(children: [Text('abcd'), Text('abcd')]),
    TableRow(children: [Text('abcd'), Text('abcd')]),
    TableRow(children: [Text('abcd'), Text('abcd')]),
    TableRow(children: [Text('abcd'), Text('abcd')]),
  ],
)
```

Flutter native @ https://github.com/flutter/flutter/commit/362b999b9

![Screen Shot 2019-06-14 at 12 33 43 PM](https://user-images.githubusercontent.com/17034/59533685-1aadfe00-8ea1-11e9-9919-01bcee111466.png)

Flutter web @ https://github.com/flutter/flutter_web/commit/14f1ccfa4000b52c9191140af1214bf5dbe066f2

![Screen Shot 2019-06-14 at 12 34 01 PM](https://user-images.githubusercontent.com/17034/59533690-1f72b200-8ea1-11e9-8bf1-6941f2787d24.png)

Related to https://github.com/flutter/flutter/issues/34342 ?

**Comment by kevmoo** [comment]
Note, I have some different text alignment defaults, just look at the border drawing

**Comment by rvowles** [comment]
This seems to impact decoration borders on text input Fields as well

**Comment by ferhatb** [comment]
Root cause: Path reuse 
Example:
  path.draw
  canvas.drawPath
  path.reset
  path.draw
  canvas.drawPath
