### ISSUE TITLE
The getter 'state' was called on null.

### ISSUE THREAD

**Issue by x8Haider** [flutter/flutter#34520]
Hello,

I'm getting the following error and I don't know where is the issue exactly.

I/flutter (11446): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (11446): The following NoSuchMethodError was thrown while handling a gesture:
I/flutter (11446): The getter 'state' was called on null.
I/flutter (11446): Receiver: null
I/flutter (11446): Tried calling: state
I/flutter (11446): 
I/flutter (11446): When the exception was thrown, this was the stack:
I/flutter (11446): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter (11446): #1      _DynamicFieldsPageState._sendUsersPage (package:my_insurance/util/dynamic_fields.dart:39:23)
I/flutter (11446): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
I/flutter (11446): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
I/flutter (11446): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
I/flutter (11446): #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
I/flutter (11446): #6      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:211:7)
I/flutter (11446): #7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (11446): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:225:20)
I/flutter (11446): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
I/flutter (11446): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (11446): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (11446): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (11446): #16     _invoke1 (dart:ui/hooks.dart:233:10)
I/flutter (11446): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
I/flutter (11446): (elided 3 frames from package dart:async)
I/flutter (11446): 
I/flutter (11446): Handler: onTap
I/flutter (11446): Recognizer:
I/flutter (11446):   TapGestureRecognizer#d7311(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
I/flutter (11446):   Offset(209.7, 401.1), sent tap down)
I/flutter (11446): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (11446): Another exception was thrown: NoSuchMethodError: The getter 'state' was called on null.

Here is my code:

`import 'package:flutter/material.dart';
import 'package:frideos_core/frideos_core.dart';
import 'package:frideos/frideos.dart';
import 'package:my_insurance/util/bloc.dart';
import 'package:progress_hud_v2/progress_hud.dart';
import 'dart:async';
const TextStyle buttonText = TextStyle(color: Colors.white);

class DynamicFieldsPage extends StatefulWidget {
  @override
  _DynamicFieldsPageState createState() => _DynamicFieldsPageState();
}

class _DynamicFieldsPageState extends State<DynamicFieldsPage> {
  //Progress indicator
  ProgressHUD progressIndicator;
  final nameFieldsController = List<TextEditingController>();
  final ageFieldsController = List<TextEditingController>();

  @override
  void initState() {
    super.initState();
    progressIndicator = new ProgressHUD(
      backgroundColor: Colors.black12,
      color: Colors.white,
      containerColor: Colors.blue,
      borderRadius: 5.0,
      text: 'Loading...',
    );
    Timer(Duration(seconds: 3), () => progressIndicator.state.dismiss());
  }
  @override
  void dispose() {
    super.dispose();
    bloc.dispose();
  }
  void _sendUsersPage() {
    final users = bloc.submit();
    progressIndicator.state.show();
    users.forEach((k, v) =>
        print('User ${k + 1} - Name: ${v['name']}, age: ${v['age']}'));
  }
  @override
  Widget build(BuildContext context) {
    List<Widget> _buildFields(int length) {
      // Clear the TextEditingControllers lists
      nameFieldsController.clear();
      ageFieldsController.clear();

      for (int i = 0; i < length; i++) {
        final name = bloc.nameFields.value[i].value;
        final age = bloc.ageFields.value[i].value;

        nameFieldsController.add(TextEditingController(text: name));
        ageFieldsController.add(TextEditingController(text: age));
      }

      return List<Widget>.generate(
        length,
            (i) => FieldsWidget(
          index: i,
          nameController: nameFieldsController[i],
          ageController: ageFieldsController[i],
        ),
      );
    }

    return new Scaffold(
        floatingActionButton: Padding(
          child: FloatingActionButton(
            onPressed: bloc.newFields,
            child: Icon(Icons.add),
          ),
          padding: const EdgeInsets.only(bottom: 25.0),
        ),
            body: Stack(
              children: <Widget>[
                ListView(
                  children: <Widget>[
                    Container(
                      height: 16.0,
                    ),
                    ValueBuilder<List<StreamedValue<String>>>(
                      streamed: bloc.nameFields,
                      builder: (context, snapshot) {
                        return Column(
                          children: _buildFields(snapshot.data.length),
                        );
                      },
                      noDataChild: const Text('NO DATA'),
                    ),
                    StreamBuilder<bool>(
                        stream: bloc.isFormValid.outStream,
                        builder: (context, snapshot) {
                          return Row(
                            mainAxisAlignment: MainAxisAlignment.spaceAround,
                            children: <Widget>[
                              RaisedButton(
                                color: Colors.blue,
                                child: snapshot.hasData
                                    ? snapshot.data
                                    ? const Text('Submit', style: buttonText)
                                    : const Text('Please add drivers name to continue', style: buttonText)
                                    : const Text('Please add drivers name to continue', style: buttonText),
                                onPressed: snapshot.hasData ? _DynamicFieldsPageState()._sendUsersPage : null,
                              )
                            ],
                          );
                        }),
                  ],
                ),
                progressIndicator
              ],
            ),
          );
  }
}

class FieldsWidget extends StatelessWidget {
  const FieldsWidget({
    this.index,
    this.nameController,
    this.ageController,
  });

  final int index;
  final TextEditingController nameController;
  final TextEditingController ageController;

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Column(
        children: <Widget>[
          Container(
              padding: EdgeInsets.all(10.0),
              child: Text(
                  'Driver ${index + 1}:',
                  style: TextStyle(
                    fontSize: 16.0
                  ),
              )
          ),
          Row(
            children: <Widget>[
              Expanded(
                child: Column(
                  children: <Widget>[
                    StreamBuilder<String>(
                        initialData: ' ',
                        stream: bloc.nameFields.value[index].outStream,
                        builder: (context, snapshot) {
                          return Column(
                            children: <Widget>[
                              Padding(
                                padding: const EdgeInsets.symmetric(
                                  horizontal: 10,
                                ),
                                child: TextField(
                                  controller: nameController,
                                  style: const TextStyle(
                                    fontSize: 14,
                                    color: Colors.black,
                                  ),
                                  decoration: InputDecoration(
                                    labelText: 'Name:',
                                    hintText: 'Insert driver name...',
                                    errorText: snapshot.error,
                                  ),
                                  onChanged: bloc.nameFields.value[index].inStream,
                                ),
                              ),
                            ],
                          );
                        }),
                    StreamBuilder<String>(
                        initialData: ' ',
                        stream: bloc.ageFields.value[index].outStream,
                        builder: (context, snapshot) {
                          return Column(
                            children: <Widget>[
                              Padding(
                                padding: const EdgeInsets.symmetric(
                                  horizontal: 10,
                                ),
                                child: TextField(
                                  controller: ageController,
                                  style: const TextStyle(
                                    fontSize: 14,
                                    color: Colors.black,
                                  ),
                                  decoration: InputDecoration(
                                    labelText: 'Age:',
                                    hintText: 'Insert driver age...',
                                    errorText: snapshot.error,
                                  ),
                                  keyboardType: TextInputType.number,
                                  onChanged: bloc.ageFields.value[index].inStream,
                                ),
                              ),
                            ],
                          );
                        }),
                    const SizedBox(
                      height: 22.0,
                    ),
                  ],
                ),
              ),
              Padding(
                padding: EdgeInsets.all(5.0),
                child: SizedBox(
                  child: FloatingActionButton(
                    backgroundColor: Colors.redAccent,
                    onPressed: () => bloc.removeFields(index),
                    child: Icon(Icons.close),
                  ),
                  width: 40.0,
                ),
              )
            ],
          )
        ],
      ),
    );
  }
}`

**Comment by BaderEddineOuaich** [comment]
Your class _DynamicFieldsPageState  extends an empty State, specify the state of what class you want it to extend as the following:
`class _DynamicFieldsPageState extends State<DynamicFieldsPage> `

**Comment by jonahwilliams** [comment]
In 

```
void _sendUsersPage() {
  final users = bloc.submit();
  progressIndicator.state.show();
  users.forEach((k, v) =>
    print('User ${k + 1} - Name: ${v['name']}, age: ${v['age']}'));
}
```

The `progressIndicator` is `null`, probably due to a logic error in how you initialize or clear it. This is unrelated to flutter

**Comment by x8Haider** [comment]
@BaderEddineOuaich
It is as you said, I think when I copy paste the code it did not copy as it should be here is a screenshot:

https://ibb.co/b7hYKFH

A copy of my code too:


class _DynamicFieldsPageState extends State<DynamicFieldsPage> {
  //Progress indicator
  ProgressHUD progressIndicator;
  final nameFieldsController = List<TextEditingController>();
  final ageFieldsController = List<TextEditingController>();

  @override
  void initState() {
    super.initState();
    progressIndicator = new ProgressHUD(
      backgroundColor: Colors.black12,
      color: Colors.white,
      containerColor: Colors.blue,
      borderRadius: 5.0,
      text: 'Loading...',
    );

**Comment by x8Haider** [comment]
@jonahwilliams it is about "progressIndicator.state.show();" when I comment this line the code is working perfectly!!! but the funny think the same code I'm using is working perfectly in an other page!
