### ISSUE TITLE
[image_picker] configurable JPEG compression

### ISSUE THREAD

**Issue by abonander** [flutter/flutter#34523]
When reencoding images with a `maxWidth` and `maxHeight` set, the picker plugin currently uses 100% for the JPEG quality level:

* (always passed `quality:nil` AFAICT) https://github.com/flutter/plugins/blob/master/packages/image_picker/ios/Classes/FLTImagePickerMetaDataUtil.m#L79
* https://github.com/flutter/plugins/blob/master/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImageResizer.java#L90

100% quality does not mean lossless compression, however; chroma subsampling and DCT coefficient rounding still occurs, so compression artifacts are still going to be introduced. 

However, if the user wants to increase the compression level they then have to re-encode _again_ which introduces yet more artifacting, besides being inefficient for multiple reasons.

This should be a good introductory issue for someone wanting to learn about the Flutter native bridge although it would touch both Android and iOS code.

**Comment by cyanglaz** [comment]
Thanks to @AmolGangadhare's PR https://github.com/flutter/plugins/pull/1896. This new feature is added in 0.6.1. I am closing this issue now, if any related issue is found, please feel free to reopen the issue or open another one with details.
