### ISSUE TITLE
Can we not enforce lowerCamelCase on developpers by default?

### ISSUE THREAD

**Issue by mathieujobin** [flutter/flutter#34532]
## Use case

I learn to use CameCaseAtSchoolLikeEveryone

Then I use ruby for many many years and my_eyes_finally_found_peace_with_snake_case

Would you please NOT enforce this rule on us by default?

## Proposal

* Do not enable this rule by default, let variables be free
* Add a snake_case linter and Allow dev to pick your favorite on `flutter create app`

Thank you

Example
```
class MonalisaClient {
  Map local_config;
  String user_uuid;
  String user_token;
  FlutterSecureStorage _secure_storage;
  final http.BaseClient http_client = http.Client();
...
}
```

**Comment by dnfield** [comment]
In the Dart ecosystem and for Flutter's style guide, it's generally the practice to use camelCase. 

You are certainly free to disable the lint in your own projects and use whatever style you so desire though.
