### ISSUE TITLE
About flutter URL encode

### ISSUE THREAD

**Issue by Echo-Joker** [flutter/flutter#34537]
## Steps to Reproduce

1.Uri.encodeQueryComponent('2019-06-19 17:00:00')

## Logs

result:2019-06-19+17%3A00%3A00
i don't want This transforms spaces (U+0020) to a plus sign ('+')
2019-06-19%2017%3A00%3A00
```

<!--
     Run `flutter analyze` and attach any output of that command below.
     If there are any analysis errors, try resolving them before filing this issue.
-->

```
```

<!-- Finally, paste the output of running `flutter doctor -v` here. -->

```
```

**Comment by NBTX** [comment]
This method isn't really "encode URL", it's "encode URL query component" - for query strings it's common practice to encode spaces as + so it seems like for this method the behaviour is desirable.

I think you want `encodeComponent` instead, which I believe does not have this behavior: https://api.dartlang.org/stable/2.3.1/dart-core/Uri/encodeComponent.html

**Comment by stuartmorgan** [comment]
The documentation for that method links to the relevant HTML spec, which specifically calls for encoding spaces with `+`, so that behavior is correct.
