### ISSUE TITLE
Cursor in TextField moving at the first in RTL languages!

### ISSUE THREAD

**Issue by pbsajjad** [flutter/flutter#34538]
I'm developing a RTL app with latest version of Flutter, 1.5. I used TextField or TextFormField Widgets to insert persian characters, and each time that I insert a space to separate each word, the cursor move at the beginning of input!!! In previous versions of Flutter, the cursor moved at the middle of latest typed word until inserting a new word and so on...!
Here is a GIF that show the issue:
![Issue in action](http://www.driversho.com/flutter.gif)

What should I do? Should I wait for Flutter updates or there is a trick to handle it?

As I mentioned, this problem for previous versions was different and here is the reported issue:
[https://github.com/flutter/flutter/issues/21679](url)

**Comment by GaryQian** [comment]
See: https://github.com/flutter/flutter/issues/34610 which may be relevant.

I may move work on this issue here instead.

**Comment by GaryQian** [comment]
@pbsajjad Do you think you can provide me with the exact TextField widget you are using to repro the bug? If possible, a minimal reproduction app would be really handy too! I want to make sure I am able to deal with the exact bug you are seeing, as RTL in an RTL field should definitely not do that.

**Comment by GaryQian** [comment]
You may have accidentally forgotten to set the TextField's `textDirection: TextDirection.rtl` property and Setting the text align to right is not enough to make the field properly support RTL.

Nonetheless, i am still working on a fix to improve typing mixed RTL/LTR text in either scenario.

**Comment by pbsajjad** [comment]
@GaryQian Thanks for attention and replying.
I test this issue with minimal set up, I remove all additional code, remove custom font and...

![Issue code](http://www.driversho.com/flutter.PNG)

As you see, I put `textDirection: TextDirection.rtl` in TextField Widget. But the result is the same!

**Comment by GaryQian** [comment]
Ok, thanks for the input! I may have something that can resolve tour issue, but it seems slightly hacky at the moment, I'll put up a WIP PR shortly...

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/9489 is a more formal fix that I have verified fixes exactly this.

**Comment by GaryQian** [comment]
Closing this now, once flutter/engine#9489 rolls into the framework, this should be fixed on master. Let me know if you see any problems with the fix!

Thanks for reporting this and helping with the debugging!

**Comment by keepfocusontechnology** [comment]
Enter two consecutive Spaces,The problem remains ...
