### ISSUE TITLE
can tabBar not centered ? 

### ISSUE THREAD

**Issue by Takeroro** [flutter/flutter#34539]
currently, tabs are in the center of the tabbar,
<img width="252" alt="WechatIMG1" src="https://user-images.githubusercontent.com/8736318/59551287-f68a1400-8fa9-11e9-8940-2e768fb48a0f.png">,
can it support the style like this? 
![31560600908_ pic](https://user-images.githubusercontent.com/8736318/59551315-51bc0680-8faa-11e9-9dd7-4c1afc2a717f.jpg)

**Comment by Takeroro** [comment]
currently, tabs are in the center of the tabbar,
<img width="252" alt="WechatIMG1" src="https://user-images.githubusercontent.com/8736318/59551287-f68a1400-8fa9-11e9-8940-2e768fb48a0f.png">,
can it support the style like this? 
![31560600908_ pic](https://user-images.githubusercontent.com/8736318/59551315-51bc0680-8faa-11e9-9dd7-4c1afc2a717f.jpg)

**Comment by NBTX** [comment]
You need to at least provide the relevant code, ideally you should provide a minimum functioning example of your code.

**Comment by Takeroro** [comment]
answer myself ==, wrap a contaier and set alignment: Alignment.topLeft done
https://takeroro.github.io/2019/06/24/Flutter-tabBar%E4%B8%80%E5%AE%9A%E8%A6%81%E5%B1%85%E4%B8%AD%E5%90%97%EF%BC%9F/

**Comment by PaulLockett** [comment]
close #34539 @shihaohong  it has been solved.
