### ISSUE TITLE
CommonFinders should notice when they're ambiguous

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3453]
From @HansMuller:
All of the CommonFinders methods work nicely if there's only one matching element. This is the sort of thing that one can guarantee in a simple test, but not so much when you're testing an application. Perhaps finders should always do an exhaustive search and fail if there's more than one match. Perhaps we should have finders that return all of the elements that match some criteria.

**Comment by Hixie** [comment]
cc @yjbanov

**Comment by Hixie** [comment]
I believe this is done now. If you use tester.widget(find.foo) then it'll throw if it matches more than one, for example.

**Comment by deonchimple** [comment]
The application I am testing has more than one element matching the same criteria like find.ByType. It was suggested by @HansMuller  here :  
> Perhaps we should have finders that return all of the elements that match some criteria.
 
Since its closed, I am assuming there's hopefully way to get a list, array, etc of these elements. I would be grateful if someone gave me a way to use it. I would also like to loop through them and access them through their index (in the list).

**Comment by yjbanov** [comment]
Several options, depending on what you are testing:

- We have multiple kinds of matchers that allow you to assert that a specific number of widgets appears on the UI, such as [findsWidgets](https://docs.flutter.io/flutter/flutter_test/findsWidgets-constant.html), [findsOneWidget](https://docs.flutter.io/flutter/flutter_test/findsOneWidget-constant.html), [findsNWidgets](https://docs.flutter.io/flutter/flutter_test/findsNWidgets.html).
- Use `WidgetTester.elementList` or `WidgetTester.widgetList`.
- Use the public methods of `Finder` directly, such as [Finder.evaluate](https://docs.flutter.io/flutter/flutter_test/Finder/evaluate.html).

**Comment by yjbanov** [comment]
Also, do you mind asking this question on StackOverflow, where it would be easier to find the answer?
