### ISSUE TITLE
Crash report sent (report ID: 54fe266803e041e7)

### ISSUE THREAD

**Issue by dhmcgrathnl** [flutter/flutter#34543]
When running on locally connected device I got the following:
[flutter_01.log](https://github.com/flutter/flutter/files/3293240/flutter_01.log)

Launching lib\main.dart on SM G950U in debug mode...
Initializing gradle...
Resolving dependencies...
error: device offline

Oops; flutter has exited unexpectedly: "Exit code 1 from: C:\devl\Android\Sdk\platform-tools\adb.exe -s 988820444f54495343 shell -x logcat -v time -t 1".
Sending crash report to Google.
Running Gradle task 'assembleDebug'...
Crash report sent (report ID: 54fe266803e041e7)
Crash report written to C:\devl\flutter\projects\rp-mobile\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by jonahwilliams** [comment]
What happens if you run `C:\devl\Android\Sdk\platform-tools\adb.exe -s 988820444f54495343 shell -x logcat -v time -t 1` ? It looks like something is up with your ADB

**Comment by RIPYTT** [comment]
> Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
> Thanks for your contribution.

PS C:\Users\hamza> e:
PS E:\> cd main
PS E:\main> flutter create adminn
Creating project adminn...
  adminn\.gitignore (created)
  adminn\.idea\libraries\Dart_SDK.xml (created)
  adminn\.idea\libraries\Flutter_for_Android.xml (created)
  adminn\.idea\libraries\KotlinJavaRuntime.xml (created)
  adminn\.idea\modules.xml (created)
  adminn\.idea\runConfigurations\main_dart.xml (created)
  adminn\.idea\workspace.xml (created)
  adminn\.metadata (created)
  adminn\android\app\build.gradle (created)
  adminn\android\app\src\main\kotlin\com\example\adminn\MainActivity.kt (created)
  adminn\android\build.gradle (created)
  adminn\android\adminn_android.iml (created)
  adminn\android\.gitignore (created)
  adminn\android\app\src\debug\AndroidManifest.xml (created)
  adminn\android\app\src\main\AndroidManifest.xml (created)
  adminn\android\app\src\main\res\drawable\launch_background.xml (created)
  adminn\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
  adminn\android\app\src\main\res\mipmap-mdpi\ic_launcher.png (created)
  adminn\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (created)
  adminn\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (created)
  adminn\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (created)
  adminn\android\app\src\main\res\values\styles.xml (created)
  adminn\android\app\src\profile\AndroidManifest.xml (created)
  adminn\android\gradle\wrapper\gradle-wrapper.properties (created)
  adminn\android\gradle.properties (created)
  adminn\android\settings.gradle (created)
  adminn\ios\Runner\AppDelegate.swift (created)
  adminn\ios\Runner\Runner-Bridging-Header.h (created)
  adminn\ios\Runner.xcodeproj\project.pbxproj (created)
  adminn\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (created)
  adminn\ios\.gitignore (created)
  adminn\ios\Flutter\AppFrameworkInfo.plist (created)
  adminn\ios\Flutter\Debug.xcconfig (created)
  adminn\ios\Flutter\Release.xcconfig (created)
  adminn\ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (created)
  adminn\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png (created)
  adminn\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png (created)
  adminn\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png (created)
  adminn\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png (created)
  adminn\macos\Runner\Assets.xcassets\AppIcon.appiconset\app_icon_64.png (created)
  adminn\macos\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (created)
  adminn\macos\Runner\Base.lproj\MainMenu.xib (created)
  adminn\macos\Runner\Configs\AppInfo.xcconfig (created)

Sending crash report to Google.
Crash report sent (report ID: 7cfbb904d26722be)
Oops; flutter has exited unexpectedly.

Crash report written to E:\main\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
PS E:\main>






C:\Users\hamza>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.418], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[!] Android Studio (not installed)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] VS Code (version 1.39.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

C:\Users\hamza>flutter upgrade
Your flutter checkout has local changes that would be erased by upgrading. If you want to keep these changes, it is
recommended that you stash them via "git stash" or else commit the changes to a local branch. If it is okay to remove
local changes, then re-run this command with --force.

C:\Users\hamza>flutter upgrade --force
Upgrading Flutter from E:\Android\flutter...
From https://github.com/flutter/flutter
 * [new branch]            Hixie-patch-2 -> origin/Hixie-patch-2
 + cc949a8e8b...e70236e36c beta          -> origin/beta  (forced update)
   0e605cc4dd..1946fc4da0  dev           -> origin/dev
   f4b4616f87..3fea2838df  master        -> origin/master
 * [new tag]               v1.10.14      -> v1.10.14
 * [new tag]               v1.10.13      -> v1.10.13
Updating c382b8e990..cc949a8e8b
 16 files changed, 435 insertions(+), 308 deletions(-)
Building flutter tool...
Running pub upgrade...

Upgrading engine...

Flutter 1.9.1+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cc949a8e8b (2 weeks ago) • 2019-09-27 15:04:59 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[!] Android Studio (not installed)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] VS Code (version 1.39.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.




























Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter create --androidx admin

## exception

TemplateException: Value was missing for variable tag: macosIdentifier. (11:29)
PRODUCT_BUNDLE_IDENTIFIER = {{macosIdentifier}}
                            ^


```
#0      Renderer.visitVariable (package:mustache/src/renderer.dart:101:9)
#1      VariableNode.accept (package:mustache/src/node.dart:45:43)
#2      Renderer.render.<anonymous closure> (package:mustache/src/renderer.dart:58:30)
#3      List.forEach (dart:core-patch/growable_array.dart:283:8)
#4      Renderer.render (package:mustache/src/renderer.dart:58:13)
#5      Template.render (package:mustache/src/template.dart:40:14)
#6      Template.renderString (package:mustache/src/template.dart:33:5)
#7      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:172:77)
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#9      Template.render (package:flutter_tools/src/template.dart:124:24)
#10     CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:623:21)
#11     CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:546:23)
<asynchronous suspension>
#12     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:397:37)
<asynchronous suspension>
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#21     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```



![Annotation 2019-10-13 001437](https://user-images.githubusercontent.com/51709861/66706624-7eacda00-ed4e-11e9-847b-4de964d454a8.png)

its just create these folder
===================================
log report Crash report file

[flutter_02.log](https://github.com/flutter/flutter/files/3721069/flutter_02.log)
