### ISSUE TITLE
Execution failed for task ':camera:compileDebugJavaWithJavac'. 

### ISSUE THREAD

**Issue by Loopex2019** [flutter/flutter#34542]
Hi there i tried launching the app but i always got that error : 
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':camera:compileDebugJavaWithJavac'.
> Unable to find source java class: 'C:\Users\Nader Khaled\flutter\.pub-cache\git\plugins-301f85e52cbf32dae44510b3f49167133df1ffc2\packages\camera\android\src\main\java\io\flutter\plugins\camera\CameraHandler.java' because it does not belong to any of the source dirs: '[C:\Users\Nader Khaled\flutter\.pub-cache\hosted\pub.dartlang.org\camera-0.5.2+1\android\src\main\java, C:\Users\Nader Khaled\flutter\.pub-cache\hosted\pub.dartlang.org\camera-0.5.2+1\android\src\debug\java, C:\Users\Nader Khaled\looper_2019\build\camera\generated\not_namespaced_r_class_sources\debug\generateDebugRFile\out, C:\Users\Nader Khaled\looper_2019\build\camera\generated\source\buildConfig\debug, C:\Users\Nader Khaled\looper_2019\build\camera\generated\source\aidl\debug, C:\Users\Nader Khaled\looper_2019\build\camera\generated\source\rs\debug]'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)`

**Comment by alfawzaan** [comment]
Please what was the solution to this issue? I am currently having the same issue.

**Comment by martin-schulze-vireso** [comment]
@alfawzaan I was seeing the same issue. I followed [this post](https://github.com/flutter/flutter/issues/51583#issuecomment-592398403) and `flutter clean` did the trick for me.

**Comment by alfawzaan** [comment]
> @alfawzaan I was seeing the same issue. I followed [this post](https://github.com/flutter/flutter/issues/51583#issuecomment-592398403) and `flutter clean` did the trick for me.

Thanks. I will check it out and see if it works.
