### ISSUE TITLE
Feature request : Support send multiple arguments to the compute function

### ISSUE THREAD

**Issue by sachaarbonel** [flutter/flutter#34540]
## Use case
Often in apps that require some "computation heavy" algorithms (like computer graphics etc), we have to use the [compute](https://api.flutter.dev/flutter/foundation/compute.html) method here and there to avoid blocking the ui and run them in an isolate. Most of the time those algorithms are not single arguments functions and thus doesn't work with compute. A work around is to put those arguments into a Map  as explained in this [SO response](https://stackoverflow.com/questions/54074857/send-multiple-arguments-to-the-compute-function-in-flutter). Modify those algorithms / or wrap them to accept a Map instead of the type we intended at the moment of designing the API is not very convenient and error prone.

## Proposal

Thus I would like the flutter team to modify compute (breaking change I think) or create an other convenient method like compute that accepts multiple arguments. This feature might or might not need this [request](https://github.com/dart-lang/language/issues/58) on dart language design repository to land;

**Comment by TheLastGimbus** [comment]
Why isn't this still a thing? It's **so annoying** to create and parse some boilerplate classes just to pass multiple arguments :roll_eyes:

**Comment by goderbauer** [comment]
You can just create a helper data structure that encapsulates all the arguments you want to pass in.

**Comment by TheLastGimbus** [comment]
...and create another 3x lines of boilerplate code -_-

luckly i think now `Isolate.run()` solves this problem (?)
