### ISSUE TITLE
Unable to use 'flutter run' with both android & iOS emulators open

### ISSUE THREAD

**Issue by eoghanosullivan** [flutter/flutter#34547]
I have just set up flutter following the steps on the flutter website when I try and use 'flutter run' when I have both the iOS and Android emulators open I get an error which you can see here https://pastebin.com/pTu0J6BU.

Flutter doctor says everything is fine and picks up both devices when I run it and says there are no errors. The strange thing is the command will run when there is only 1 emulator open, has anyone encountered this before?

**Comment by jonahwilliams** [comment]
Hi @eoghanosullivan , you didn't post the top of the strack trace, so it's possible for us to see if anything wen wrong.

Likely you need to specify `-d all` if you want to run on two devices, and the error message should say this.

**Comment by khflab** [comment]
You do not need to reboot, just load your bash again (or open a new Terminal). Each Linux distribution can vary on how they find the user bash profile, so it's not the case to update the guide to describe the Linux Mint mode.

**Comment by eoghanosullivan** [comment]
Hey @jonahwilliams thank you for getting back to me so quickly! I'll try the `-d all `  and I can upload the rest of the stack trace once I am home from work!

**Comment by eoghanosullivan** [comment]
Hey @jonahwilliams, using `flutter run -d all` solved the issue! Thank you so much 👍
