### ISSUE TITLE
EXCEPTION CAUGHT BY SCHEDULER LIBRARY

### ISSUE THREAD

**Issue by mehdidavarpanah66** [flutter/flutter#34554]
```
The following assertion was thrown during a scheduler callback:
I/flutter ( 5460): There are multiple heroes that share the same tag within a subtree.
I/flutter ( 5460): Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must
I/flutter ( 5460): have a unique non-null tag.
I/flutter ( 5460): In this case, multiple heroes had the following tag: <default FloatingActionButton tag>
I/flutter ( 5460): Here is the subtree for one of the offending heroes:
I/flutter ( 5460): # Hero(tag: <default FloatingActionButton tag>, state: _HeroState#3f159)
I/flutter ( 5460): # └SizedBox(renderObject: RenderConstrainedBox#301eb relayoutBoundary=up4 NEEDS-PAINT)
I/flutter ( 5460): #  └Offstage(offstage: false, renderObject: RenderOffstage#aa4a9 relayoutBoundary=up5 NEEDS-PAINT)
I/flutter ( 5460): #   └TickerMode(mode: enabled)
I/flutter ( 5460): #    └KeyedSubtree-[GlobalKey#e1c57]
I/flutter ( 5460): #     └RawMaterialButton(state: _RawMaterialButtonState#75374)
I/flutter ( 5460): #      └Semantics(container: true, properties: SemanticsProperties, label: null, value: null, hint:
I/flutter ( 5460): null, hintOverrides: null, renderObject: RenderSemanticsAnnotations#838de relayoutBoundary=up6
I/flutter ( 5460): NEEDS-PAINT)
I/flutter ( 5460): #       └_InputPadding(renderObject: _RenderInputPadding#1ba2c relayoutBoundary=up7 NEEDS-PAINT)
I/flutter ( 5460): #        └Focus(dependencies: [_FocusMarker], state: _FocusState#5a13f)
I/flutter ( 5460): #         └_FocusMarker
I/flutter ( 5460): #          └ConstrainedBox(BoxConstraints(w=56.0, h=56.0), renderObject: RenderConstrainedBox#2c8a8
I/flutter ( 5460): relayoutBoundary=up8 NEEDS-PAINT)
I/flutter ( 5460): #           └Material(type: button, elevation: 13.0, color: Color(0xffff6600), textStyle.debugLabel:
I/flutter ( 5460): (((englishLike button 2014).merge((blackMountainView button).apply)).copyWith).copyWith,
I/flutter ( 5460): textStyle.inherit: false, textStyle.color: Color(0xff000000), textStyle.family: Vazir,
I/flutter ( 5460): textStyle.size: 14.0, textStyle.weight: 500, textStyle.letterSpacing: 1.2, textStyle.baseline:
I/flutter ( 5460): alphabetic, textStyle.decoration: TextDecoration.none, shape:
I/flutter ( 5460): CircleBorder(BorderSide(Color(0xff000000), 0.0, BorderStyle.none)), dependencies: [TickerMode],
I/flutter ( 5460): state: _MaterialState#32fc1)
I/flutter ( 5460): #            └_MaterialInterior(duration: 200ms, shape: CircleBorder(BorderSide(Color(0xff000000),
I/flutter ( 5460): 0.0, BorderStyle.none)), elevation: 13.0, color: Color(0xffff6600), shadowColor: Color(0xff000000),
I/flutter ( 5460): dependencies: [TickerMode, Directionality], state: _MaterialInteriorState#06d33(ticker inactive))
I/flutter ( 5460): #             └PhysicalShape(clipper: ShapeBorderClipper, elevation: 13.0, color: Color(0xffff6600),
I/flutter ( 5460): shadowColor: Color(0xff000000), renderObject: RenderPhysicalShape#fc19c NEEDS-PAINT)
I/flutter ( 5460): #              └_ShapeBorderPaint(dependencies: [Directionality])
I/flutter ( 5460): #               └CustomPaint(renderObject: RenderCustomPaint#862c8 NEEDS-PAINT)
I/flutter ( 5460): #                └NotificationListener<LayoutChangedNotification>
I/flutter ( 5460): #                 └_InkFeatures-[GlobalKey#b9cde ink renderer](renderObject:
I/flutter ( 5460): _RenderInkFeatures#2651c NEEDS-PAINT)
I/flutter ( 5460): #                  └AnimatedDefaultTextStyle(duration: 200ms, debugLabel: (((englishLike button
I/flutter ( 5460): 2014).merge((blackMountainView button).apply)).copyWith).copyWith, inherit: false, color:
I/flutter ( 5460): Color(0xff000000), family: Vazir, size: 14.0, weight: 500, letterSpacing: 1.2, baseline: alphabetic,
I/flutter ( 5460): decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip, dependencies:
I/flutter ( 5460): [TickerMode], state: _AnimatedDefaultTextStyleState#07f88(ticker inactive))
I/flutter ( 5460): #                   └DefaultTextStyle(debugLabel: (((englishLike button
I/flutter ( 5460): 2014).merge((blackMountainView button).apply)).copyWith).copyWith, inherit: false, color:
I/flutter ( 5460): Color(0xff000000), family: Vazir, size: 14.0, weight: 500, letterSpacing: 1.2, baseline: alphabetic,
I/flutter ( 5460): decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip)
I/flutter ( 5460): #                    └InkWell(gestures: [tap], clipped to BoxShape.rectangle, dependencies:
I/flutter ( 5460): [_FocusMarker], state: _InkResponseState<InkResponse>#36ff3)
I/flutter ( 5460): #                     └Listener(listeners: [enter, exit], behavior: translucent, renderObject:
I/flutter ( 5460): RenderPointerListener#13fde NEEDS-PAINT)
I/flutter ( 5460): #                      └GestureDetector(startBehavior: start)
I/flutter ( 5460): #                       └RawGestureDetector(state: RawGestureDetectorState#ab6f2(gestures: [tap],
I/flutter ( 5460): behavior: opaque))
I/flutter ( 5460): #                        └_GestureSemantics(renderObject: RenderSemanticsGestureHandler#c93b2
I/flutter ( 5460): NEEDS-PAINT)
I/flutter ( 5460): #                         └Listener(listeners: [down], behavior: opaque, renderObject:
I/flutter ( 5460): RenderPointerListener#5faa3 NEEDS-PAINT)
I/flutter ( 5460): #                          └Builder(dependencies: [IconTheme])
I/flutter ( 5460): #                           └IconTheme(IconThemeData#a143c(color: Color(0xff000000)))
I/flutter ( 5460): #                            └Container(padding: EdgeInsets.zero)
I/flutter ( 5460): #                             └Padding(padding: EdgeInsets.zero, dependencies: [Directionality],
I/flutter ( 5460): renderObject: RenderPadding#643e7 NEEDS-PAINT)
I/flutter ( 5460): #                              └Center(alignment: center, widthFactor: 1.0, heightFactor: 1.0,
I/flutter ( 5460): dependencies: [Directionality], renderObject: RenderPositionedBox#9ce71 NEEDS-PAINT)
I/flutter ( 5460): #                               └Builder(dependencies: [IconTheme])
I/flutter ( 5460): #                                └IconTheme(IconThemeData#a143c(color: Color(0xff000000)))
I/flutter ( 5460): #                                 └Icon(IconData(U+0E55C), color: Color(0xffffffff), dependencies:
I/flutter ( 5460): [Directionality, IconTheme])
I/flutter ( 5460): #                                  └Semantics(container: false, properties: SemanticsProperties,
I/flutter ( 5460): label: null, value: null, hint: null, hintOverrides: null, renderObject:
I/flutter ( 5460): RenderSemanticsAnnotations#3d13f relayoutBoundary=up1 NEEDS-PAINT)
I/flutter ( 5460): #                                   └ExcludeSemantics(excluding: true, renderObject:
I/flutter ( 5460): RenderExcludeSemantics#5d79e relayoutBoundary=up2 NEEDS-PAINT)
I/flutter ( 5460): #                                    └SizedBox(width: 24.0, height: 24.0, renderObject:
I/flutter ( 5460): RenderConstrainedBox#837ee relayoutBoundary=up3 NEEDS-PAINT)
I/flutter ( 5460): #                                     └Center(alignment: center, dependencies: [Directionality],
I/flutter ( 5460): renderObject: RenderPositionedBox#8a4bf NEEDS-PAINT)
I/flutter ( 5460): #                                      └RichText(textDirection: ltr, softWrap: wrapping at box
I/flutter ( 5460): width, overflow: visible, maxLines: unlimited, text: "", dependencies:
I/flutter ( 5460): [_LocalizationsScope-[GlobalKey#3822e]], renderObject: RenderParagraph#4d648 relayoutBoundary=up1
I/flutter ( 5460): NEEDS-PAINT)
```

**Comment by mehdidavarpanah66** [comment]
import 'package:flutter/material.dart';

import 'map.dart';

class RegisterScreen extends StatefulWidget{
  @override
  State<StatefulWidget> createState() =>new RegisterScrennState();
}

class RegisterScrennState extends State<RegisterScreen>{
  @override
  Widget build(BuildContext context) {
  var  page_size=MediaQuery.of(context).size;
    // TODO: implement build
    return new Scaffold(
      appBar: new AppBar(
        backgroundColor: Colors.grey[300],
        title: new Text('Foody House',style: TextStyle(color: Color(0xffff6600)),),
        leading: new Image(image: new AssetImage("assets/images/app_bar_icon.png")),
      ),
      body: new Container(
        height: page_size.height,
        decoration: new BoxDecoration(
          gradient:new LinearGradient(
              colors:<Color>[
                 const Color(0x77ff6600),
                const Color(0xffff6600),
              ],
              begin: Alignment.topLeft,
              end: Alignment.bottomLeft
          ),
        ),
        child: new Stack(

          children: <Widget>[

            new Opacity(opacity: .6,
              child: new Container(
                width: page_size.width,
                height: page_size.height,
                decoration: new BoxDecoration(
                  image: new DecorationImage(
                      image:new AssetImage("assets/images/background.jpg"),
                      repeat: ImageRepeat.repeat
                  ),

                ),
              ),
            ),
            new SingleChildScrollView(
              child: new Container(
                child: new Column(
                  children: <Widget>[
                    new Container(

                      width: page_size.width,

                      child: new Column(
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: <Widget>[
                          new Padding(

                            padding: const EdgeInsets.symmetric(vertical: 12),
                            child: new Container(
                              height: 80,
                              width: 80,


                              decoration: new BoxDecoration(
                                  color: Color(0xffff6600),
                                  borderRadius: new BorderRadius.all(Radius.circular(15))
                              ),
                              child: new Icon(Icons.person,color: Colors.white,size: 50,),
                            ),
                          ),
                          new Text('ثبت نام',style: new TextStyle(fontWeight: FontWeight.bold),)
                        ],
                      ),
                    ),
                    new Row(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: <Widget>[
                        new Container(
                          alignment: Alignment.center,
                          child: new Text('حساب کاربری',style: TextStyle(color: Colors.white),),
                          decoration: new BoxDecoration(
                              color: Color(0xffff6600),
                              borderRadius: new BorderRadius.all(Radius.circular(20))
                          ),
                          padding: const EdgeInsets.symmetric(vertical: 12),
                          width: page_size.width*.9,
                        )
                      ],
                    ),
                    new Container(
                      width: page_size.width*.8,
                      decoration: new BoxDecoration(
                          color: Colors.grey[300],
                          borderRadius: new BorderRadiusDirectional.only(bottomEnd: Radius.circular(15),bottomStart:Radius.circular(15))

                      ),
                      child: new Column(
                        children: <Widget>[
                          new Row(
                            children: <Widget>[
                              new Expanded(child: new Container(

                                margin: const EdgeInsets.only(top: 10,left: 30,right: 30,bottom: 2.5 ),
                                decoration: new BoxDecoration(
                                    color: Colors.white,
                                    borderRadius: new BorderRadius.circular(30)
                                ),
                                child: new Row(
                                  children: <Widget>[
                                    new Icon(Icons.person,color: Color(0xffff6600),size: 30,),
                                    new Expanded(
                                        child: new Container(
                                          alignment: Alignment.center,

                                          margin: const EdgeInsets.symmetric(vertical: 4,horizontal: 12),
                                          decoration: BoxDecoration(
                                              border: BorderDirectional(top: BorderSide(color: Color(0xffff6600)),bottom:BorderSide(color: Color(0xffff6600)) )
                                          ),
                                          child: new TextField(
                                            style: TextStyle(fontSize: 12),

                                            decoration: InputDecoration(

                                                border: InputBorder.none,
                                                hintText: 'نام'
                                            ),
                                            textAlign: TextAlign.center,

                                          ),
                                        )
                                    )
                                  ],
                                ),

                              )
                              )
                            ],
                          ),
                          new Row(
                            children: <Widget>[
                              new Expanded(child: new Container(

                                margin: const EdgeInsets.only(top: 2.5,left: 30,right:30,bottom: 2.5 ),
                                decoration: new BoxDecoration(
                                    color: Colors.white,
                                    borderRadius: new BorderRadius.circular(30)
                                ),
                                child: new Row(
                                  children: <Widget>[
                                    new Icon(Icons.person,color: Color(0xffff6600),size: 30,),
                                    new Expanded(
                                        child: new Container(
                                          alignment: Alignment.center,

                                          margin: const EdgeInsets.symmetric(vertical: 4,horizontal: 12),
                                          decoration: BoxDecoration(
                                              border: BorderDirectional(top: BorderSide(color: Color(0xffff6600)),bottom:BorderSide(color: Color(0xffff6600)) )
                                          ),
                                          child: new TextField(
                                            style: TextStyle(fontSize: 12),

                                            decoration: InputDecoration(

                                                border: InputBorder.none,
                                                hintText: 'فامیلی'
                                            ),
                                            textAlign: TextAlign.center,

                                          ),
                                        )
                                    )
                                  ],
                                ),

                              )
                              )
                            ],
                          ),
                          new Row(
                            children: <Widget>[
                              new Expanded(child: new Container(

                                margin: const EdgeInsets.only(top: 2.5,left: 30,right: 30,bottom: 2.5 ),
                                decoration: new BoxDecoration(
                                    color: Colors.white,
                                    borderRadius: new BorderRadius.circular(30)
                                ),
                                child: new Row(
                                  children: <Widget>[
                                    new Icon(Icons.phone_android,color: Color(0xffff6600),size: 30,),
                                    new Expanded(
                                        child: new Container(
                                          alignment: Alignment.center,

                                          margin: const EdgeInsets.symmetric(vertical: 4,horizontal: 12),
                                          decoration: BoxDecoration(
                                              border: BorderDirectional(top: BorderSide(color: Color(0xffff6600)),bottom:BorderSide(color: Color(0xffff6600)) )
                                          ),
                                          child: new TextField(
                                            style: TextStyle(fontSize: 12),
                                            keyboardType: TextInputType.number,
                                            decoration: InputDecoration(

                                                border: InputBorder.none,

                                                hintText: 'تلفن همراه'
                                            ),
                                            textAlign: TextAlign.center,

                                          ),
                                        )
                                    )
                                  ],
                                ),

                              )
                              )
                            ],
                          ),
                          new Row(
                            crossAxisAlignment: CrossAxisAlignment.center,
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: <Widget>[
                              new Expanded(child: new Container(
                                margin: const EdgeInsets.symmetric(horizontal: 5),
                                alignment: Alignment.center,
                                child: new Text('آدرس',style: TextStyle(color: Colors.white),),
                                decoration: new BoxDecoration(
                                    color: Color(0xffff6600),
                                    borderRadius: new BorderRadius.all(Radius.circular(20))
                                ),
                                padding: const EdgeInsets.symmetric(vertical: 12),

                              ))
                            ],
                          ),
                          new Row(
                            crossAxisAlignment: CrossAxisAlignment.center,
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: <Widget>[
                              new Expanded(
                                  child: new Container(
                                    margin: const EdgeInsets.symmetric(vertical: 5,horizontal: 4),
                                    height: 80,
                                    alignment: Alignment.center,
                                    decoration: new BoxDecoration(
                                        color: Color(0xffff6600),
                                        borderRadius: new BorderRadius.all(Radius.circular(35))
                                    ),
                                    padding: const EdgeInsets.symmetric(vertical: 0),
                                    child: new Row(
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: <Widget>[
                                        new Container(
                                          child: new FlatButton(onPressed:(){
                                            Navigator.of(context).pushReplacementNamed("/map");
                                          //  go_to_map(context);
                                          },
                                            color:  Color(0xffff6600),
                                            shape: new RoundedRectangleBorder(borderRadius: new BorderRadius.circular(35)),
                                            child: new Column(
                                              mainAxisAlignment: MainAxisAlignment.center,
                                              children: <Widget>[
                                                new Icon(Icons.add_location,color: Colors.white,),
                                                new Text('نقشه',style: TextStyle(fontSize: 10,color: Colors.white),)
                                              ],
                                            ),

                                          ),
                                        ),
                                        new Expanded(
                                            child:
                                            new Container(
                                              alignment: Alignment.center,
                                              height: 80,
                                              decoration: new BoxDecoration(
                                                  color: Colors.white
                                              ),
                                              child: new TextField(
                                                style: TextStyle(fontSize: 12),
                                                decoration: InputDecoration(

                                                    border: InputBorder.none,

                                                    hintText: 'آدرس دقیق'
                                                ),
                                                textAlign: TextAlign.center,
                                              ),
                                            )
                                        ),
                                        new Container(
                                          alignment: Alignment.center,
                                          child: new FlatButton(onPressed:(){},
                                            color:  Color(0xffff6600),
                                            shape: new RoundedRectangleBorder(borderRadius: new BorderRadius.circular(35)),
                                            child: new Column(
                                              mainAxisAlignment: MainAxisAlignment.center,
                                              children: <Widget>[
                                                new Text('ثبت',style: TextStyle(fontSize: 12,color: Colors.white),)
                                              ],
                                            ),

                                          ),
                                        ),
                                      ],
                                    ),

                                  ))
                            ],
                          ),
                          new Row(
                            crossAxisAlignment: CrossAxisAlignment.center,
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: <Widget>[
                              new Container(

                                child: new RaisedButton(
                                  onPressed: (){
                                    Navigator.pushReplacementNamed(context, "/login");
                                  }
                                  ,
                                  child: new Text('ثبت اطلاعات',style: new TextStyle(color: Colors.white),),
                                  color: Color(0xffff6600),
                                  shape: new RoundedRectangleBorder(borderRadius: new BorderRadius.only(topLeft: Radius.circular(30),topRight: Radius.circular(30))),

                                ),
                              )
                            ],
                          )
                        ],
                      ),
                    )
                  ],
                ),
              ),
            )
          ],
        ),
      ),
    );
  }

  void go_to_map(BuildContext context)async {

    Map r=await Navigator.of(context).push(new MaterialPageRoute(
        builder: (context){
          return new MapScreen();

        }
    )
    );
    print(r);
  //Navigator.of(context).pushReplacementNamed("/map");

  }
}

**Comment by mehdidavarpanah66** [comment]
and second page 




import 'package:flutter_map/flutter_map.dart';
import 'package:flutter/material.dart';
import 'package:location/location.dart';
import 'package:latlong/latlong.dart';

import 'package:flutter/services.dart';

class MapScreen extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => MapScreenState();
}


class MapScreenState extends State<MapScreen>{
  final _scaffold_key=GlobalKey<ScaffoldState>();
 double  my_lat=29.5926;
 double  my_lng=52.5836;
 double final_lat;
 double final_lng;
 Marker _marker=new Marker();
final _name_controller=TextEditingController();
  MapController _mapController=new MapController();
String _access_token="sk.eyJ1IjojkhkjkjjhhhhhhhhhhhhhibWVoZGlkYXZhcnBhbmFoIiwiYSI6ImNqd3g3eWM2MTBvcTk0NG84MjJmNXRvN3EifQ.9997j-e40zjuCaIZkaredw";
@override
  void initState() {
   get_current_location();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
var page_size=MediaQuery.of(context).size;
    // TODO: implement build
    return new Scaffold(
      key: _scaffold_key,
      appBar: AppBar(
        title: new Text('انتخاب موقعیت مکانی'),

      ),
      body: new Stack(
        alignment: Alignment.bottomCenter,
        children: <Widget>[
          new FlutterMap(
            options: MapOptions(
              center: new LatLng(my_lat,my_lng),
              zoom: 18,
              onTap: (LatLng point){
setState(() {
  final_lat=point.latitude;
  final_lng=point.longitude;
  _marker=new Marker(
    width: 120,
    height: 120,
    point: point,
    builder: (ctx) =>
    new Container(
      child: Icon(Icons.location_on,color: Colors.orange,size: 50,),
    ),
  );
});
              }
            ),
            layers: [new TileLayerOptions(
              urlTemplate: "https://api.tiles.mapbox.com/v4/"
                  "{id}/{z}/{x}/{y}@2x.png?access_token=${_access_token}",
              additionalOptions: {
                'accessToken': '<PUT_ACCESS_TOKEN_HERE>',
                'id': 'mapbox.streets',
              },
            ),

              new MarkerLayerOptions(
                markers: [
              _marker
                ],
              ),
            ],
            mapController: _mapController,

          ),
          new Container(

            margin: const EdgeInsets.all(12),
            child: new Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: <Widget>[
                new FloatingActionButton(
                  tooltip: 'ثبت مشخصات مکانی',
                  elevation: 13,
                  backgroundColor: Color(0xffff6600),
                  onPressed: (){
send_position();

                  },
                  child: Icon(Icons.save,color: Colors.white,),
                ),
             new Container(
               decoration: BoxDecoration(
                 color: Colors.white,
                 borderRadius: BorderRadius.circular(30)
               ),
               width: page_size.width*.6,
               child:  new TextField(
controller: _name_controller,
                 style: TextStyle(fontSize: 12 ),

                 decoration: InputDecoration(


                     border: InputBorder.none,
                     hintText: 'نام مکان: منزل..شرکت...'
                 ),
                 textAlign: TextAlign.center,

               ),
             ),
                new FloatingActionButton(
                  elevation: 13,
                  backgroundColor: Color(0xffff6600),
                  onPressed: (){

                    get_current_location();
                  },
                  child: Icon(Icons.my_location,color: Colors.white,),
                )
              ],
            ),
          )
        ],
      ),

    );
  }

  void get_current_location() async{
    var currentLocation = LocationData;


    var location = new Location();

// Platform messages may fail, so we use a try/catch PlatformException.
    try {
    var  currentLocation = await location.getLocation();
    setState(() {
      my_lat=currentLocation.latitude;
      my_lng=currentLocation.longitude;
      _mapController.move(new LatLng(my_lat, my_lng), 18);

    });


    } on PlatformException catch (e) {
      if (e.code == 'PERMISSION_DENIED') {
       //print('Permission denied');
      }
      currentLocation = null;
    }
  }

  void send_position() {
  if(_name_controller.text.length==0){
    _scaffold_key.currentState.showSnackBar(new SnackBar(content: new Text('لطفا نام ماکن را وارد کنید',style: TextStyle(fontFamily: 'Vazir'),),duration: Duration(milliseconds: 1000),));
  }else if( final_lng ==null && final_lat==null){
    _scaffold_key.currentState.showSnackBar(new SnackBar(content: new Text('لطفا موقعیت مکانی خود را رو نقشه مشخص کنید',style: TextStyle(fontFamily: 'Vazir'),),duration: Duration(milliseconds: 1000),));

  }else{
    Map value={
      'name':_name_controller.text,
      'lat':final_lat,
      'lng':final_lng
    };
    Navigator.of(context).pop({'map_value':value});
  }




  }
}

**Comment by jonahwilliams** [comment]
Please try and put together a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to demonstrate this issue. As is it will be too difficult for someone to reproduce the problem you've posted here, and it isn't clear if it is an issue with your code or a framework bug
