### ISSUE TITLE
Flutter Driver only doing the integration test when the user interacts

### ISSUE THREAD

**Issue by hanseltertiusJCU** [flutter/flutter#34561]
Hello ladies and gentlemen, I have an issue regarding to FlutterDriver. Basically, SerializableFinder only able to find the widget when the user interacts with the application. Otherwise, it won't be able to find.

**steps to reproduce**
widgets:
https://gist.github.com/hanseltertiusJCU/3b7b8b6b8f4669cd0aae53a9e9fba3da : develop.dart
https://gist.github.com/hanseltertiusJCU/5f75b93d4c3a6eaedb3808dd0ff9b0ea : main_common.dart
https://gist.github.com/hanseltertiusJCU/afb17bdd243993b43f8649aaa886075c : detailed_page.dart
 
test_driver:
https://gist.github.com/hanseltertiusJCU/4a0df0c3cd6949f9ddb298105317f6ca : finder.dart
https://gist.github.com/hanseltertiusJCU/a685cec131fca04c0720796a44971d3a : integration_app.dart
https://gist.github.com/hanseltertiusJCU/040aee053a45f87403effea8cb3ffad0 : integration_app_test.dart

(Note that this is not a full app, for full app please see the link below)

Screenshot:
https://cdn.discordapp.com/attachments/209689284310073345/589823741559570449/unknown.png
To triggered something, just press something in the circle right here

**log integration testing**
```
00:02 +0: Meals Catalogue App Verify default app bar title
[warning] FlutterDriver: get_text message is taking a long time to complete... // when the user doesn't interact with the app
00:17 +1: Meals Catalogue App Click icon into detail item // triggered when the user interact with the app
00:18 +2: Meals Catalogue App Pressed favorite icon in detail page
00:19 +3: Meals Catalogue App Pressed back button
00:20 +4: Meals Catalogue App Click icon search and enter text
00:22 +5: Meals Catalogue App Bottom navigation bar test item
00:22 +6: Meals Catalogue App (tearDownAll)
00:22 +6: All tests passed!
Stopping application instance.
```
**flutter analyze**
```
D:\AndroidStudioProjects\MFDEProject\meals_catalogue>flutter analyze
Analyzing meals_catalogue...
No issues found! (ran in 14.3s)
```
**flutter doctor -v**
```
D:\AndroidStudioProjects\MFDEProject\meals_catalogue>flutter doctor -v
[√] Flutter (Channel master, v1.7.2-pre.30, on Microsoft Windows [Version 10.0.17134.829], locale en-ID)
    • Flutter version 1.7.2-pre.30 at D:\Android\Sdk\flutter_windows_v1.2.1-stable\flutter
    • Framework revision 14414f350a (11 days ago), 2019-06-05 18:14:17 -0700
    • Engine revision 3371da1e09
    • Dart version 2.3.2 (build 2.3.2-dev.0.1 9dcb026b26)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA 2019.1
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

```

Sorry if I wrote a long lines of code, however thats what I can do to represent the whole issue. If someone don't mind, I will provide my full code here : https://github.com/hanseltertiusJCU/meals_catalogue/tree/final_temp

So, what can I do to solve the situation? Thanks for anyone who reads the issue and trying to help it.

**Comment by janmoppel** [comment]
Hello @hanseltertiusJCU !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
