### ISSUE TITLE
compile flutter failed

### ISSUE THREAD

**Issue by ping996** [flutter/flutter#34569]
ninja: Entering directory `out/android_debug_x86'
[3533/3574] ACTION //flutter/lib/snapshot:generate_snapshot_bin(//build/toolchain/android:clang_x86)
FAILED: gen/flutter/lib/snapshot/vm_isolate_snapshot.bin gen/flutter/lib/snapshot/vm_snapshot_instructions.bin gen/flutter/lib/snapshot/isolate_snapshot.bin gen/flutter/lib/snapshot/isolate_snapshot_instructions.bin
python ../../build/gn_run_binary.py clang_x86/gen_snapshot --snapshot_kind=core --enable_mirrors=false --vm_snapshot_data=/home/wuchuanping/flutter/src/out/android_debug_x86/gen/flutter/lib/snapshot/vm_isolate_snapshot.bin --vm_snapshot_instructions=/home/wuchuanping/flutter/src/out/android_debug_x86/gen/flutter/lib/snapshot/vm_snapshot_instructions.bin --isolate_snapshot_data=/home/wuchuanping/flutter/src/out/android_debug_x86/gen/flutter/lib/snapshot/isolate_snapshot.bin --isolate_snapshot_instructions=/home/wuchuanping/flutter/src/out/android_debug_x86/gen/flutter/lib/snapshot/isolate_snapshot_instructions.bin /home/wuchuanping/flutter/src/out/android_debug_x86/flutter_patched_sdk/platform_strong.dill
Traceback (most recent call last):
  File "../../build/gn_run_binary.py", line 22, in <module>
    sys.exit(subprocess.call(args))
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
ninja: build stopped: subcommand failed.

compile the flutter engine failed with ubuntu 16.04 in window10, ubuntu install from the MS Store.  anyone can help me?

**Comment by ping996** [comment]
./flutter/tools/gn --android --unoptimized 
ninja -C out/android_debug_unopt

**Comment by krishnakeshan** [comment]
Any resolution for this??

**Comment by ping996** [comment]
no solutions   Any idear




| |
吴川平
邮箱：wcpstone@126.com
|

签名由 网易邮箱大师 定制

On 06/22/2019 19:09, Krishna Keshan wrote:

Any resolution for this??
