### ISSUE TITLE
PointerScaleEvent

### ISSUE THREAD

**Issue by mtcliatt** [flutter/flutter#34567]
## Use case

Our use case: a Flutter4Desktop application that reacts to a user's touch-scale gesture (as opposed to a drag-scale gesture).

We're already using handleScaleUpdate for other standard UI functions, so we can't use that here. Also, there's behavior that's expected by our users in response to this, which we want to able to provide. (For an example where the UI zooms in response to this scale, see [this javascript demo](https://manuelstofer.github.io/pinchzoom/demo/pinchzoom.html).

From my observations, Flutter isn't emitting anything in response to this action. When using a `Listener` and catching all pointer events, I see a lot of `PointerScrollEvent`s but that's the only `PointerSignalEvent`. When I scale, I don't see any events at all during the entire scale. This is supported by the fact that `PointerScrollEvent` is the only implementer of [PointerSignalEvent](https://api.flutter.dev/flutter/gestures/PointerSignalEvent-class.html) :p 

## Proposal

Create a `PointerScaleEvent` class to be emitted when pointers scale without contacting the screen.

-----

note: internal customer

**Comment by stuartmorgan** [comment]
This is a specific case of #23604; closing as a duplicate of that issue.

**Comment by mtcliatt** [comment]
Sounds good, thanks Stuart!
