### ISSUE TITLE
Firebase Auth: Custom Authentication

### ISSUE THREAD

**Issue by naiveai** [flutter/flutter#34564]
## Use case

I'm using "Sign in with Reddit" for an app of mine, which is not a supported method of authentication with Firebase Auth. But I do want to use the Firebase User tokens in order to validate stuff on, for example, Cloud Firestore. There is [a way to do this described in the docs](https://firebase.google.com/docs/auth/admin/create-custom-tokens), but I don't see it being supported in the Flutter plugin.

## Proposal

Support custom authentication tokens as a method of login in the flutter firebase_auth plugin.

**Comment by collinjackson** [comment]
The firebase_auth plugin supports signInWithCustomToken 

https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/signInWithCustomToken.html

**Comment by kroikie** [comment]
@naiveai

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1105. Any further collaboration will be done there.

**Comment by kherld-hussein** [comment]
closed
