### ISSUE TITLE
'activity.isScrolling': is not true 

### ISSUE THREAD

**Issue by CatEatFishs** [flutter/flutter#34568]
I have this problem,when i use NestedScrollView, this is my code;

 body: Container(
          child: NestedScrollViewRefreshIndicator(
            onRefresh: onRefresh,
            child: NestedScrollView(
                physics: new AlwaysScrollableScrollPhysics(),
                headerSliverBuilder: (c, f) {
                  return buildSliverHeader(false);
                },
                pinnedHeaderSliverHeightBuilder: () {
                  return pinnedHeaderHeight;
                },
                body: Column(
                  children: <Widget>[
                    Expanded(
                        child:
                            TabBarView(controller: _tabController, children: [
                  ])}

): 
I/flutter ( 8750): Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 487 pos 12: '_drag == null': is not true.
I/flutter ( 8750): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 674 pos 12: 'activity.isScrolling': is not true.

[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/hongka-liming/Downloads/flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/hongka-liming/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ Brew can be used to install tools for iOS device development.
      Download brew at https://brew.sh/.

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • COR AL00 • 6EJ7N18526001222 • android-arm64 • Android 9 (API 28)

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
