### ISSUE TITLE
I can't build my flutter-web because my app has dependencies on firestore and firebase plugins, is there a way to make them work? If not what other databases can i use that are supported for flutter web?

### ISSUE THREAD

**Issue by OlfatMostafa** [flutter/flutter#34563]
This is the message i get:- 

webdev could not run for this project.
You have a dependency on `cloud_firestore` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on `cupertino_icons` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on `firebase_auth` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on `firebase_core` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on `flutter` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more
details.
You have a dependency on `google_sign_in` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on `shared_preferences` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on `url_launcher` which is not supported for flutter_web tech preview. See https://flutter.dev/web for
more details.

**Comment by jonahwilliams** [comment]
As the error message says, you cannot use these flutter dependencies until both https://github.com/flutter/flutter/issues/34082 and when/if they have web implementations.

**Comment by MichealReed** [comment]
@jonahwilliams I have updated url_launcher to be compatible with flutter_web, how do I get past the error message? `You have a dependency on `url_launcher` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.`

**Comment by Ahmadre** [comment]
@MichealReed You have to fork url_launcher and change the pubspec.yaml as follows:

```dart
name: url_launcher
description: Flutter plugin for launching a URL on Android and iOS. Supports
  web, phone, SMS, and email schemes.
version: 5.1.2
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/url_launcher

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test  
```

After that you should get rid of these messages. I also made Auto_size_text available for flutter web. If you need that for flutter_web too, here it is: https://github.com/Ahmadre/auto_size_text

Greets
Rebar
