### ISSUE TITLE
ListView within another ListView, exception thrown with shrinkwrap set to true

### ISSUE THREAD

**Issue by fueler** [flutter/flutter#34570]
## Steps to Reproduce

I am only building Flutter Web.

Was given the error vertical viewport was given unbounded height. Added shrinkwrap attribute set to true in the ListView.builder. Then this exception was created and requested a bug be created.

## Logs

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
dart_sdk.js:18737 The following assertion was thrown during performLayout():
dart_sdk.js:18737 Assertion failed: is not true
dart_sdk.js:18737 
dart_sdk.js:18737 Either the assertion indicates an error in the framework itself, or we should provide substantially
dart_sdk.js:18737 more information in this error message to help you determine and fix the underlying cause.
dart_sdk.js:18737 In either case, please report this assertion by filing a bug on GitHub:
dart_sdk.js:18737   https://github.com/flutter/flutter/issues/new?template=BUG.md
dart_sdk.js:18737 
dart_sdk.js:18737 When the exception was thrown, this was the stack:
dart_sdk.js:18737 dart:sdk_internal 4495:15                                                                  assertFailed
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/viewport.dart 1658:28               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/flex.dart 781:14                    performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/flex.dart 781:14                    performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/material/list_tile.dart 1298:8                _layoutBox
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/material/list_tile.dart 1346:31               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/shifted_box.dart 219:11             performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 1195:11              performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/shifted_box.dart 219:11             performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/sliver_list.dart 171:26             performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/sliver_padding.dart 183:11          performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/viewport.dart 406:12                layoutChildSequence
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/viewport.dart 1373:12               [_attemptLayout]
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/viewport.dart 1288:20               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1707:7                  layout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/proxy_box.dart 105:13               performLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 1565:7                  [_layoutWithoutResize]
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/object.dart 823:17                  flushLayout
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/binding.dart 347:19                 drawFrame
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/widgets/binding.dart 711:13                   drawFrame
dart_sdk.js:18737 package:flutter_web/packages/flutter_web/src/rendering/binding.dart 286:5                  [_handlePersistentFrameCallback]
dart_sdk.js:18737 package:flutter_web/src/scheduler/packages/flutter_web/src/scheduler/binding.dart 1030:15  [_invokeFrameCallback]
dart_sdk.js:18737 package:flutter_web/src/scheduler/packages/flutter_web/src/scheduler/binding.dart 963:9    handleDrawFrame
dart_sdk.js:18737 package:flutter_web/src/scheduler/packages/flutter_web/src/scheduler/binding.dart 874:5    [_handleDrawFrame]
dart_sdk.js:18737 package:flutter_web_ui/packages/flutter_web_ui/src/engine.dart 154:21                      <fn>
dart_sdk.js:18737 
dart_sdk.js:18737 The following RenderObject was being processed when the exception was fired: RenderShrinkWrappingViewport#9c185 relayoutBoundary=up28 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
dart_sdk.js:18737   needs compositing
dart_sdk.js:18737   creator: ShrinkWrappingViewport ← IgnorePointer-[GlobalKey#66069] ← Semantics ← Listener ←
dart_sdk.js:18737     _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#63967] ←
dart_sdk.js:18737     Listener ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#9d5b0] ← RepaintBoundary ← CustomPaint ←
dart_sdk.js:18737     RepaintBoundary ← ⋯
dart_sdk.js:18737   parentData: <none> (can use size)
dart_sdk.js:18737   constraints: BoxConstraints(unconstrained)
dart_sdk.js:18737   size: MISSING
dart_sdk.js:18737   axisDirection: down
dart_sdk.js:18737   crossAxisDirection: right
dart_sdk.js:18737   offset: ScrollPositionWithSingleContext#77928(offset: 0.0, range: null..null, viewport: null,
dart_sdk.js:18737     ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics, IdleScrollActivity#9191f,
dart_sdk.js:18737     ScrollDirection.idle)
dart_sdk.js:18737 This This RenderObject had the following descendants (showing up to depth 5):
dart_sdk.js:18737     child 0: RenderSliverPadding#ab2ac NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
dart_sdk.js:18737       child: RenderSliverList#b3bd6 NEEDS-LAYOUT NEEDS-PAINT
dart_sdk.js:18737 ════════════════════════════════════════════════════════════════════════════════════════════════════

```
```

```
```

[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F203, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/devuser/development/flutter-tools/flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices
    • Android SDK at /Users/devuser/NVPACK/android-sdk-macosx
    • Android NDK location not configured (optional; useful for native profiling support)
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

    • ANDROID_HOME = /Users/devuser/NVPACK/android-sdk-macosx
    ✗ No valid Android SDK platforms found in /Users/devuser/NVPACK/android-sdk-macosx/platforms. Candidates were:
        - android-15
        - android-16
        - android-18
        - android-21
        - android-19
        - android-17
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed instructions.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.

```
```

**Comment by fueler** [comment]
Tested with beta channel build, 
```
Flutter 1.6.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision bc7bc94083 (3 weeks ago) • 2019-05-23 10:29:07 -0700
Engine • revision 8dc3a4cde2
Tools • Dart 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)
```

Problem still exists

**Comment by ferhatb** [comment]
Can you please provide snippet of build() code to repro? Is this web only issue or do you see same issue on ios/android?

**Comment by fueler** [comment]
I am only developing on web at this time. I’ll see if I can recreate and respond with code.
