### ISSUE TITLE
Showing Local Notifications in Flutter using Native Code

### ISSUE THREAD

**Issue by abumoallim** [flutter/flutter#34577]
I am trying to implement Push Notification in my Flutter application using Firebase Messaging.

I understand complete working of Firebase Messaging that If your app is in foreground onMessage is called for both android and IOS.

So, in that case, we need to create notifications locally and show it to the user.

I am using another flutter package for showing local notifications flutter_local_notifications. It works correctly in android but in IOS it conflicts with firebase_messaging library.

So now I need to know how I can handle onMessage. Can I just call the native code to create a local notification for each platform?

and did anyone out there handled this issue in a better way? Also if I need to call native code, How can I create notifications for both android and IOS.

**Comment by sageata** [comment]
I do, what I am doing is to comment out the delegate of the flutter_local_notification from the source code for iOS.

![image](https://user-images.githubusercontent.com/26434396/60494728-6396ec80-9cc0-11e9-94e1-241d8478f626.png)



It has the drawback that you need to maintain that in the future if you upgrade the package, but is an easy one.

I hope this works for you.

**Comment by BondarenkoStas** [comment]
@abumoallim ongoing discussions are going in https://github.com/MaikuB/flutter_local_notifications/issues/111 and https://github.com/flutter/flutter/issues/22099, please follow it. Closing as a duplicate.
