### ISSUE TITLE
plugin error 

### ISSUE THREAD

**Issue by sani3854** [flutter/flutter#34574]
the plugin breaks android app due to it requires some dependencies yet unknown please check it out.

using plugin : flutter_local_notifications:

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

**Comment by stuartmorgan** [comment]
That plugin is not made by the Flutter team; you should report issues in [its issue tracker](https://github.com/MaikuB/flutter_local_notifications/issues).
