### ISSUE TITLE
[google_maps_flutter] Possibility to Remove Directions Icon

### ISSUE THREAD

**Issue by felpsio** [flutter/flutter#34572]
## Use case

When I tap on a marker in the GoogleMap view for my application it shows the Marker InfoWindow, centralizes the map on the marker and shows two icons in the right bottom of the map: "Directions" and "Open GoogleMaps App".

I would like to take off these icons on the right bottom and create my own icons to provide these kinds of functions. I can make the marker consume the tap event and not show these icons but it would cancel the other events too. I want to keep showing the InfoWindow and centralizing the map on the market without having to handle it manually. This icons only appearrs in the Android

## Proposal

When creating a `GoogleMap()` adds an optional parameter that cancels the appearing of these bottom right icons when a market is tapped

**Comment by darran-kelinske-fivestars** [comment]
Me too. I am showing a FAB in the bottom right where the direction / google maps icon are. Is there a flag to remove these icons?

**Comment by dazza5000** [comment]
This is important and also mentioned here: https://github.com/flutter/flutter/issues/25660

**Comment by otopba** [comment]
Already fixed
https://github.com/flutter/plugins/pull/1808

**Comment by BondarenkoStas** [comment]
@felpsio so is it safe to close the issue?

**Comment by felpsio** [comment]
Yes :).
