### ISSUE TITLE
Flutter 1.5.4 on iOS, Observatory debugger can't get timeline. 

### ISSUE THREAD

**Issue by BaiKunlun** [flutter/flutter#34575]
## Steps to Reproduce

1. create a new flutter project.
2. flutter run on an iOS device.
3. click the Observatory debugger and profiler url on the terminal
4. timeline
5. Can't get any data, always show "loading"
![image](https://user-images.githubusercontent.com/26134849/59595318-2101db80-9128-11e9-96ef-65a46750129c.png)

## Logs

```
```

```
```

**Comment by BaiKunlun** [comment]
The same problem with https://github.com/dart-lang/sdk/issues/36575. Set the Xcode arguments passed on launch with "--disable-service-auth-codes=true" can resolve the problem.

**Comment by BaiKunlun** [comment]
The same problem with https://github.com/dart-lang/sdk/issues/36575. Set the Xcode arguments passed on launch with "--disable-service-auth-codes=true" can resolve the problem.

**Comment by lionoggo** [comment]
> The same problem with [dart-lang/sdk#36575](https://github.com/dart-lang/sdk/issues/36575). Set the Xcode arguments passed on launch with "--disable-service-auth-codes=true" can resolve the problem.

not work, connection failed.Dart SDK 2.3.0
