### ISSUE TITLE
[google_maps_flutter] remove map toolbar that pops after engaging with markers

### ISSUE THREAD

**Issue by mrg250** [flutter/flutter#34581]
Hello all, 
I've been using the Google Maps plugin for Flutter, and I've noticed a feature that I can't disable, which is a toolbar that appears on the map whenever clicking a marker on the map. 

Is there a way to disable it? 

_**EDIT**_:
I do want to preserve tapping functionality (onTap etc.)

(the toolbar is on the right)
![Screenshot_20190617-161359](https://user-images.githubusercontent.com/28823036/59607096-57852980-911b-11e9-83a5-2f98b95d5eb5.jpg)

**Comment by peet29** [comment]
`Marker( markerId: MarkerId('test),  consumeTapEvents : false)`
Set consumeTapEvents to false when creating a marker.  
When click on marker toolbar won't show anymore.

From Marker Class 
`/// True if the marker icon consumes tap events. If not, the map will perform
  /// default tap handling by centering the map on the marker and displaying its
  /// info window.
  final bool consumeTapEvents;
`

**Comment by mrg250** [comment]
> 
> 
> `Marker( markerId: MarkerId('test), consumeTapEvents : false)`
> Set consumeTapEvents to false when creating a marker.
> When click on marker toolbar won't show anymore.
> 
> From Marker Class
> `/// True if the marker icon consumes tap events. If not, the map will perform /// default tap handling by centering the map on the marker and displaying its /// info window. final bool consumeTapEvents; `

Thanks for the reply!
I tried this solution, however it didn't work (still poping the toolbar).

**Comment by peet29** [comment]
Sorry I mean set consumeTapEvents to **true**. 😅
`Marker( markerId: MarkerId('test), consumeTapEvents : true)`

**Comment by mrg250** [comment]
> 
> 
> Sorry I mean set consumeTapEvents to **true**. 😅
> `Marker( markerId: MarkerId('test), consumeTapEvents : true)`

Thank you!
This does solves my problem !

_**NOTE**: this prevent the camera being centered to the pin upon clicking_
