### ISSUE TITLE
SignIn with Google Replaces Other providers

### ISSUE THREAD

**Issue by rajababu3** [flutter/flutter#34580]
I have implemented Login with Email, Google, and Facebook.
I created a user using email and password.
For testing, I used the sign in with Google, and it replaces the email provider in firebase console to google provider. 
I don't understand if this is the correct behavior or the plugin has some error.

**Comment by amitkhairnar44** [comment]
@rajababu3 This is correct behaviour since the email id used to sign in is same. There is an option in Firebase console that prevents users from using same email from different authentication providers.

**Comment by BondarenkoStas** [comment]
Thank you @amitkhairnar44 ! @rajababu3 I think it's safe to close the issue.
