### ISSUE TITLE
Flutter commands are not working properly in command prompt in windows 10 even flutter SDK is correctly configured.

### ISSUE THREAD

**Issue by aravindmedamoni** [flutter/flutter#34586]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by jonahwilliams** [comment]
You've not included any information in this bug which would allow us to help you. I'm closing in the meantime, please feel free to file a new issue with more actionable information

**Comment by aravindmedamoni** [comment]
Oops; flutter has exited unexpectedly.                                           Sending crash report to Google.                                                  Crash report sent (report ID: 0fd2ea81920ecaf0)                                  Crash report written to C:\Users\aravi\OneDrive\Desktop\flutter_02.log;
--

**Comment by aravindmedamoni** [comment]
when i run flutter commands in my command prompt it will shows like above comment.
