### ISSUE TITLE
Add iPhone XS to our device lab

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#34590]
To monitor our performance on newer iPhones.

We'll later use this to test our metal performances too.

**Comment by liyuqian** [comment]
This would also help https://github.com/flutter/flutter/issues/31086

**Comment by liyuqian** [comment]
We've setup mac8 with iPhone X (currently in my desk instead of in the lab). I'll close the issue once we've done some successful performance benchmarks through https://github.com/flutter/flutter/pull/35556

**Comment by MisterJimson** [comment]
FYI I believe it's the XS, not the X, that has the higher sampling rate that causes performance issues. Just want to make sure you are setting up the correct device.

**Comment by liyuqian** [comment]
Luckily, we did buy the iPhone XS as Apple is no longer selling iPhone X on its website :) Edit the title of this issue to reflect that.

**Comment by liyuqian** [comment]
Almost done. I only need to move the Mac Mini and iPhone XS from my desk to the actual lab.

**Comment by liyuqian** [comment]
Our lab is currently running out of space. So the device will remain on my desk for a while. The test will keep running.

**Comment by liyuqian** [comment]
Moved to the new device lab desk. Closing.
