### ISSUE TITLE
[url_launcher] Add option to pass extra arguments (Android)

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#34595]
https://stackoverflow.com/questions/7306396/intent-android-youtube-player-app-in-full-screen-mode

I want to pass an extra argument to an intent on android. I do not this there is a solution for this. It would be a nice addition to the plugin

**Comment by stuartmorgan** [comment]
For controlling details of intents, using a specific plugin for intents such as https://pub.dev/packages/android_intent_plus would be the best option; url_launcher is intended to be a simple way to hand off links to the OS.
