### ISSUE TITLE
Would like to be able to distinguish users who disable analytics vs. stop using Flutter

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#34603]
Right now we can't tell the difference.  It's possible we're counting lots of "just disabled analytics" users as "lost".

**Comment by jayoung-lee** [comment]
This will greatly improve the confidence of our user retention study. Could we add a milestone for this?

**Comment by jayoung-lee** [comment]
There are two to-do's to make this change happen: 

(1) Update the notice on the Flutter tool. This notice also needs to be shown to the existing users who upgrade Flutter to a new version.

>Warning: The flutter tool uses Google Analytics to anonymously report feature usage statistics and basic crash reports. This data is used to help improve Flutter tools over time.
>
>Flutter tool analytics are not sent on the very first run. To disable reporting, type flutter config --no-analytics. To display the current setting, type flutter config. If you opt out of analytics, an opt-out event will be sent, and then no further information will be sent by the Flutter tool. 
>
>By downloading the Flutter SDK, you agree to the Google Terms of Service. Note: The Google Privacy Policy describes how data is handled in this service.
>
>Moreover, Flutter includes the Dart SDK, which may send usage metrics and crash reports to Google.

(2) Update the flutter.dev pages accordingly (e.g., [Windows install](https://flutter.dev/docs/get-started/install/windows#run-flutter-doctor)).

**Comment by zanderso** [comment]
The welcome message update and new analytics event have landed on master.

**Comment by zanderso** [comment]
The website is now updated as well.
