### ISSUE TITLE
[plugin incompat] image_picker 0.6 and firebase_analytics 3.0 cannot be used in the same project

### ISSUE THREAD

**Issue by abonander** [flutter/flutter#34602]
Even though `firebase_analytics 3.0.2` is listed on the "AndroidX Compatibility" page, it does not appear to be compatible with the `androidx.legacy:legacy-support-v4:1.0.0` package linked by `image_picker 0.6.0`. When trying to build, it fails on `:app:check<Profile>DuplicateClasses` with numerous errors:

```
Duplicate class android.support.v4.app.INotificationSideChannel found in modules classes.jar (androidx.core:core:1.0.0) and classes.jar (com.android.support:support-compat:26.1.0)
... (abridged)
Duplicate class android.support.v4.media.RatingCompat found in modules classes.jar (androidx.media:media:1.0.0) and classes.jar (com.android.support:support-media-compat:26.1.0)
... (abridged)
Duplicate class android.support.v4.os.ResultReceiver$MyRunnable found in modules classes.jar (androidx.core:core:1.0.0) and classes.jar (com.android.support:support-compat:26.1.0)
```

`firebase-analytics` transitively links `com.android.support:support-compat:26.1.0` and `com.android.support:support-media-compat:26.1.0` (`firebase-core` rendered as the root package but `firebase-analytics` is the problem one here)
![firebase-analytics links android-support](https://user-images.githubusercontent.com/3198595/59632861-129fc980-9100-11e9-9851-26afee863609.png)

As per above, these collide with classes from `androidx.core` and `androidx.media` which are transitively linked by `androidx.legacy:legacy-support-v4` imported by `image_picker 0.6`:
![image](https://user-images.githubusercontent.com/3198595/59633684-e8e7a200-9101-11e9-994c-9b20c7deb770.png)

Since we have no control over what `firebase-analytics` links (being a closed source lib), I think the solution here is to be more conservative with dependencies in `image_picker`, only using the specific `androidx.legacy` packages it needs instead of the metapackage. Looking through the source, I'm not even sure what it actually _needs_ from the support libraries anyway.

As a temp fix, downgrading to `image_picker 0.4.12` works but it's not exactly satisfactory.

**Comment by janmoppel** [comment]
Hello @abonander !

Did you manage to solve the issue? Does the problem still persist in the latest version?

**Comment by abonander** [comment]
I don't know. I've long since moved on from the Flutter project where this was occurring.

**Comment by izik1** [comment]
I also had this issue up until I upgraded flutter (1.10.7), manually switched to androidx and fixed a chain of outdated deps that were probably not related, but after doing so, I can confirm that this works with `image_picker: ^0.6.1+4` and `firebase_analytics: ^5.0.2`

**Comment by kroikie** [comment]
@abonander

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1038. Any further collaboration will be done there.

**Comment by BondarenkoStas** [comment]
Thank you @izik1 ! I'm going to close the issue, issue body's versions are not relevant already. Please open a new one, if the problem will occur.
