### ISSUE TITLE
Inconsistency in ScrollDirection enum value documentation

### ISSUE THREAD

**Issue by tarobins** [flutter/flutter#34601]
I think the definition, examples, or naming of the [ScrollDirection](https://api.flutter.dev/flutter/rendering/ScrollDirection-class.html) enum values are inconsistent with the behaviour, though I'm not sure what the original intent with the naming was.

*ScrollDirection.forward* says:

> Scrolling is happening in the positive scroll offset direction.
>
> For example, for the GrowthDirection.forward part of a vertical AxisDirection.down list, this means the content is moving up, exposing lower content. 

I'm finding that for both a RenderViewport with AxisDirection.down and a RenderSliverList in that RenderViewport with GrowthDirection.forward that when I scroll down (i.e. expose lower content), the scroll offsets for both increase from zero (`renderViewport.offset.pixels` and `renderSliverList.constraints.scrollOffset`), but the `userScrollDirection` (`renderViewport.offset.userScrollDirection` and `renderSliverList.constraints.userScrollDirection`) is  ScrollDirection.reverse.  See tests at bottom for a demonstration of the behaviours.

At the very least, it seems we need to swap the examples given in the documentation of ScrollDirection.forward and .reverse.  Though I'm wondering if the value returned for userScrollDirection should be switched so that when the user is scrolling down (revealing more data at the bottom) in a AxisDirection.down RenderViewport, and in a RenderSliver in that viewport with growthDirection of GrowthDirection.forward, the userScrollDirection should be forward.  However, at the same time, I wonder if switching that behaviour would cause problems for existing client code.

I'm happy to fix this issue and submit a PR, but I'm not sure what the preferred solution would be.

### Demonstration tests

These tests demo the issue.  I would expect all of them to pass if the documentation for ScrollDirection.forward was correct; however, the tests for ScrollDirection fail while the tests for offset pass (as noted by comments before the last line on each test):

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter_test/flutter_test.dart';

const cellHeight = 20.0;

void main() {
  Future<void> setUp(WidgetTester tester) async {
    tester.binding.window.physicalSizeTestValue = Size(200, 200);
    tester.binding.window.devicePixelRatioTestValue = 1.0;

    await tester.pumpWidget(
      MaterialApp(
        home: Material(
          child: CustomScrollView(
            slivers: <Widget>[
              SliverList(
                delegate: SliverChildListDelegate(
                  List.generate(
                    200,
                    (i) => ConstrainedBox(
                          constraints:
                              BoxConstraints.tightFor(height: cellHeight),
                          child: Text('Item $i'),
                        ),
                  ),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }

  group('RenderViewport with AxisDirection.down', () {
    testWidgets('Scroll Direction for RenderViewport',
        (WidgetTester tester) async {
      await setUp(tester);

      RenderViewport renderViewport =
          tester.element(find.byType(Viewport)).renderObject;
      ScrollDirection scrollDirection;

      renderViewport.offset.addListener(
          () => scrollDirection = renderViewport.offset.userScrollDirection);

      expect(renderViewport.axisDirection, AxisDirection.down);

      expect(find.text('Item 0'), findsOneWidget);
      expect(find.text('Item 9'), findsOneWidget);
      expect(find.text('Item 10'), findsNothing);

      await tester.drag(find.byType(CustomScrollView), Offset(0, -cellHeight));
      await tester.pump();

      expect(find.text('Item 0'), findsNothing);
      expect(find.text('Item 9'), findsOneWidget);
      expect(find.text('Item 10'), findsOneWidget);

      // FAILS: Actual value ScrollDirection.reverse
      expect(scrollDirection, ScrollDirection.forward);
    });

    testWidgets('Scroll Offset for RenderViewport',
        (WidgetTester tester) async {
      await setUp(tester);

      RenderViewport renderViewport =
          tester.element(find.byType(Viewport)).renderObject;

      final initialPixelOffset = renderViewport.offset.pixels;

      expect(renderViewport.axisDirection, AxisDirection.down);

      expect(find.text('Item 0'), findsOneWidget);
      expect(find.text('Item 9'), findsOneWidget);
      expect(find.text('Item 10'), findsNothing);

      await tester.drag(find.byType(CustomScrollView), Offset(0, -cellHeight));
      await tester.pump();

      expect(find.text('Item 0'), findsNothing);
      expect(find.text('Item 9'), findsOneWidget);
      expect(find.text('Item 10'), findsOneWidget);

      final finalPixelOffset = renderViewport.offset.pixels;

      // PASSES
      expect(finalPixelOffset, greaterThan(initialPixelOffset));
    });

    testWidgets('Scroll Direction for GrowthDirection forward RenderSliverList',
        (WidgetTester tester) async {
      await setUp(tester);

      ScrollDirection scrollDirection;
      RenderSliverList renderSliverList =
          tester.element(find.byType(SliverList)).renderObject;
      RenderViewport renderViewport =
          tester.element(find.byType(Viewport)).renderObject;
      renderViewport.offset.addListener(() => SchedulerBinding.instance
          .addPostFrameCallback((_) => scrollDirection =
              renderSliverList.constraints.userScrollDirection));

      expect(renderSliverList.constraints.axisDirection, AxisDirection.down);
      expect(renderSliverList.constraints.growthDirection,
          GrowthDirection.forward);

      expect(find.text('Item 0'), findsOneWidget);
      expect(find.text('Item 9'), findsOneWidget);
      expect(find.text('Item 10'), findsNothing);

      await tester.fling(
          find.byType(CustomScrollView), Offset(0, -cellHeight), 10);
      await tester.pump();

      expect(find.text('Item 0'), findsNothing);
      expect(find.text('Item 9'), findsOneWidget);
      expect(find.text('Item 10'), findsOneWidget);

      // FAILS: Actual value ScrollDirection.reverse
      expect(scrollDirection, ScrollDirection.forward);
    });

    testWidgets('Scroll Offset for GrowthDirection forward RenderSliverList',
        (WidgetTester tester) async {
      await setUp(tester);

      RenderSliverList renderSliverList =
          tester.element(find.byType(SliverList)).renderObject;

      final initialScrollOffset = renderSliverList.constraints.scrollOffset;

      expect(renderSliverList.constraints.axisDirection, AxisDirection.down);
      expect(renderSliverList.constraints.growthDirection,
          GrowthDirection.forward);

      expect(find.text('Item 0'), findsOneWidget);
      expect(find.text('Item 9'), findsOneWidget);
      expect(find.text('Item 10'), findsNothing);

      await tester.fling(
          find.byType(CustomScrollView), Offset(0, -cellHeight), 10);
      await tester.pump();

      expect(find.text('Item 0'), findsNothing);
      expect(find.text('Item 9'), findsOneWidget);
      expect(find.text('Item 10'), findsOneWidget);

      final finalScrollOffset = renderSliverList.constraints.scrollOffset;

      // PASSES
      expect(finalScrollOffset, greaterThan(initialScrollOffset));
    });
  });
}
```

**Comment by Hixie** [comment]
I recommend checking if it's consistent with the scrollDirection in the ScrollNotification messages.

**Comment by tarobins** [comment]
@Hixie   Yes the scrollDirections are consistent with the direction in ScrollNotifications.

The following passes:

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter_test/flutter_test.dart';

const cellHeight = 20.0;

void main() {
  ScrollDirection notificationScrollDirection;
  bool notificationCallback(UserScrollNotification notification) {
    if (notification.direction == ScrollDirection.reverse ||
        notification.direction == ScrollDirection.forward) {
      notificationScrollDirection = notification.direction;
    }
    return true;
  }

  Future<void> setUp(WidgetTester tester) async {
    tester.binding.window.physicalSizeTestValue = Size(200, 200);
    tester.binding.window.devicePixelRatioTestValue = 1.0;
    notificationScrollDirection = null;

    await tester.pumpWidget(
      MaterialApp(
        home: Material(
          child: NotificationListener<UserScrollNotification>(
            onNotification: notificationCallback,
            child: CustomScrollView(
              slivers: <Widget>[
                SliverList(
                  delegate: SliverChildListDelegate(
                    List.generate(
                      200,
                      (i) => ConstrainedBox(
                            constraints:
                                BoxConstraints.tightFor(height: cellHeight),
                            child: Text('Item $i'),
                          ),
                    ),
                  ),
                )
              ],
            ),
          ),
        ),
      ),
    );
  }

  group('RenderViewport with AxisDirection.down', () {
    testWidgets('Scroll Direction for RenderViewport',
        (WidgetTester tester) async {
      await setUp(tester);

      RenderViewport renderViewport =
          tester.element(find.byType(Viewport)).renderObject;
      ScrollDirection scrollDirection;

      renderViewport.offset.addListener(
          () => scrollDirection = renderViewport.offset.userScrollDirection);

      expect(renderViewport.axisDirection, AxisDirection.down);

      expect(find.text('Item 0'), findsOneWidget);
      expect(find.text('Item 9'), findsOneWidget);
      expect(find.text('Item 10'), findsNothing);

      await tester.drag(find.byType(CustomScrollView), Offset(0, -cellHeight));
      await tester.pump();

      expect(find.text('Item 0'), findsNothing);
      expect(find.text('Item 9'), findsOneWidget);
      expect(find.text('Item 10'), findsOneWidget);

      expect(scrollDirection, notificationScrollDirection);
      // FAILS: Actual value ScrollDirection.reverse
      // expect(scrollDirection, ScrollDirection.forward);
    });

    testWidgets('Scroll Direction for GrowthDirection forward RenderSliverList',
        (WidgetTester tester) async {
      await setUp(tester);

      ScrollDirection scrollDirection;
      RenderSliverList renderSliverList =
          tester.element(find.byType(SliverList)).renderObject;
      RenderViewport renderViewport =
          tester.element(find.byType(Viewport)).renderObject;
      renderViewport.offset.addListener(() => SchedulerBinding.instance
          .addPostFrameCallback((_) => scrollDirection =
              renderSliverList.constraints.userScrollDirection));

      expect(renderSliverList.constraints.axisDirection, AxisDirection.down);
      expect(renderSliverList.constraints.growthDirection,
          GrowthDirection.forward);

      expect(find.text('Item 0'), findsOneWidget);
      expect(find.text('Item 9'), findsOneWidget);
      expect(find.text('Item 10'), findsNothing);

      await tester.fling(
          find.byType(CustomScrollView), Offset(0, -cellHeight), 10);
      await tester.pump();

      expect(find.text('Item 0'), findsNothing);
      expect(find.text('Item 9'), findsOneWidget);
      expect(find.text('Item 10'), findsOneWidget);

      expect(scrollDirection, notificationScrollDirection);

      // FAILS: Actual value ScrollDirection.reverse
      // expect(scrollDirection, ScrollDirection.forward);
    });
  });
}

**Comment by Hixie** [comment]
cc @goderbauer

**Comment by Hixie** [comment]
If everything is consistent except the docs, best to update the docs, I guess.

**Comment by tarobins** [comment]
Another place the term scroll direction comes up is the [ListView](https://api.flutter.dev/flutter/widgets/ListView-class.html) documentation:

"[ListView] displays its children one after another in the scroll direction. "

Though this statement perhaps doesn't define the order of the children (forward or reverse) in the scroll direction, just that they are one after the other.

**Comment by brandondiamond** [comment]
(Just some random thoughts on scroll direction)

It seems like there are two main ways to think about scroll direction:

- "Physical" scroll direction: how pixels within the viewport are actually being translated relative to the axis direction (this seems to be the interpretation used today)

- "Logical" scroll direction: how newly visible content relates to previously visible content (according to the ordering defined by axis and growth direction; i.e., whether we're advancing forward through the sequence or backward).

I know "physical" and "logical" are already used to characterize paint offset-based and layout offset-based sliver parent data. Not sure if this makes these proposed names more confusing or more consistent :man_shrugging:

**Comment by tarobins** [comment]
I looked at it using the "physical" scroll direction when trying to understand how scrolling worked because it matched the how the enum was set up, though I suspect from the docs and some comments in the tests, the "logical" interpretation was intended.  We could switch to the physical interpretation and I think that would resolve things, though I don't know if switching the meaning of "scroll down" would confuse people.

I can try to put together a PR that takes that approach and see what people think.

**Comment by brandondiamond** [comment]
I’m 100% with you. The docs seem to use the logical definition whereas the code uses the physical one.

This also gets messy since SliverConstraints.userScrollDirection factors in growth direction (which blends the logical and physical interpretations in an altogether confusing way).

I think we could definitely tighten up the docs as a starting point; changing this field might be too tall an order for now.

**Comment by tarobins** [comment]
I'm going to disown this bug for now.  Don't know a clean way to fix the docs without confusing people.  Sorry.
