### ISSUE TITLE
ios simulator doesn't print when starting observatory on port 8181

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#3460]
@chinmaygarde @tvolkert @johnmccutchan 

When starting the ios simulator w/ a debugging port of 8181 (`flutter run --debug-port=8181`), we don't get a

> Observatory listening on http://127.0.0.1:xxx

message. We do when we pass any other port number, or when we don't pass any port number. This asymmetry makes it harder to use a specific port (8181) for debugging, esp. as we now rely on scrapping stdout to ensure that the observatory is up and running.

I think we should change it to always print the marker text (`Observatory listening on...`) when a `--observatory-port=xxx` flag is passed.

**Comment by chinmaygarde** [comment]
I dont see any guards around 8181 specifically. Is this still an issue? I am not too familiar with this unfortunately.

**Comment by devoncarew** [comment]
I moved to using port 8100 to work around this. I think the guard is in the VM somewhere.

**Comment by devoncarew** [comment]
We can close this -
