### ISSUE TITLE
Flutter should not allow very long strings in semantics nodes.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#34605]
For example, you should get an error if you try to construct a semantics node that has a very long label (e.g. a multi-kilobyte label string).

This will be hard for screen readers to process properly, and on Fuchsia it won't work at all.

**Comment by jonahwilliams** [comment]
How long is long and why should this not be allowed? For example, I implement an e-reader workflow. Is having each page a semantic node too much? do I need to break it down to the paragraph level? If so, what is a paragraph?

**Comment by dnfield** [comment]
I don't have a firm idea on the size - but probably something about how many characters can appear on a (large?) screen.  I don't think we should constrain it too low, but we should probably fire an assert if a developer creates a condition where the label being sent up is so many bytes long so they can figure out a way to more properly subdivide it (e.g. only include the text visible on the screen).

Alternatively, we could automatically make sure that text getting sent up is only the text currently visible, which is a bit more complicated.

**Comment by dnfield** [comment]
I suspect (2^15)kb is a good number - running on a big monitor with a full screen chrome, that much text does not fit on the screen with the default font.

That would put it at roughly half the allowed space for a Fuchsia FIDL message today.

**Comment by dnfield** [comment]
I'm going to close this.  After further consideration, it doesn't seem to make sense to check - we should just let the OS/consuming systems handle it.
