### ISSUE TITLE
Support for running tests with Live WidgetBindings in bazel-based workflows

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#34617]
Currently, in g3, tests are not invoked through the Flutter command, instead using the Bazel build system to handle building and running.

In this system, we need to tell the Flutter test runner whether or not a test is being debugged from the IDE (the equivalent of `flutter run`ing instead of `flutter test`ing a particular test).

To do this, we need to override the FLUTTER_TEST environment variable, which is currently hardcoded in several places in package:flutter_tools and package:flutter_test.

**Comment by DaveShuckerow** [comment]
The implementation for this change is at #34301

**Comment by christopherfujino** [comment]
Finished
