### ISSUE TITLE
in_app_purchase - HttpException: Connection closed before full header was received

### ISSUE THREAD

**Issue by vagrantrobbie** [flutter/flutter#34619]
Since [flutter_inapp_purchase](https://pub.dev/packages/flutter_inapp_purchase#-readme-tab-) released a deprecation notice and encourages us to move to the official [in_app_purchase](https://pub.dev/packages/in_app_purchase) plugin I have received the below error
```
Unsupported value: Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4} of type NSError
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:1024/VePyp-4tox4=/ws
```

after successful install and launch

I receive this error in both my app and the example app provided with the plugin. 

## Steps to Reproduce
I have just taken the example `main.dart` file and commented pretty much the whole project out. I'm stuck at run 

I am compiling to a real device iPhoneX, with certificates and a project that support In App Purchase.

## Logs

```
[  +87 ms] (lldb)     command script import "/tmp/93138F78-BF90-4BC7-A4DB-DE84CA7D4569/fruitstrap_e28d0990a5f7e6c9f22af32edb7df628a3528e1c.py"
[  +10 ms] (lldb)     command script add -f fruitstrap_e28d0990a5f7e6c9f22af32edb7df628a3528e1c.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_e28d0990a5f7e6c9f22af32edb7df628a3528e1c.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_e28d0990a5f7e6c9f22af32edb7df628a3528e1c.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_e28d0990a5f7e6c9f22af32edb7df628a3528e1c.safequit_command safequit
[        ] (lldb)     connect
[  +28 ms] (lldb)     run
[ +208 ms] success
[        ] (lldb)     safequit
[ +111 ms] Process 346 detached
[  +38 ms] Application launched on the device. Waiting for observatory port.
[ +185 ms] Observatory URL on device: http://127.0.0.1:60100/6NEeaJFv6pY=/
[   +1 ms] attempting to forward device port 60100 to host port 1024
[        ] executing: /usr/local/bin/iproxy 1024 60100 e28d0990a5f7e6c9f22af32edb7df628a3528e1c
[  +75 ms] Unsupported value: Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4} of type NSError
[ +934 ms] Forwarded port ForwardedPort HOST:1024 to DEVICE:60100
[        ] Forwarded host port 1024 to device port 60100 for Observatory
[   +1 ms] Installing and launching... (completed in 8.4s)
[   +3 ms] Connecting to service protocol: http://127.0.0.1:1024/6NEeaJFv6pY=/
[  +60 ms] Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:1024/6NEeaJFv6pY=/ws
[   +2 ms] "flutter run" took 23,205ms.
[        ] "flutter run" took 23,205ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:434:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#34     main (file:///Users/${UserName}/Documents/Development/sdks/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

```

```
```

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-NZ)
    • Flutter version 1.5.4-hotfix.2 at /Users/${UserName}/Documents/Development/sdks/Flutter/flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/${UserName}/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[!] VS Code (version 1.9.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

**Comment by FelixHuneburg** [comment]
I'm having the same problem as soon as I import in_app_purchase in `pubspec.yaml` and try to run on my iPhone 6.

**Comment by vagrantrobbie** [comment]
Wasn't sure if it was a plugin version problem so have tried with `in_app_purchase: 0.1.1+1` which another member had rolled back in another ticket but I'm still receiving the same error.

My Mac is running macOS Mojave if that is any more helpful

**Comment by FelixHuneburg** [comment]
I have tried `0.1.1+1`, `0.1.1+2` and `0.2.0` but getting the same error.

**Comment by jaweii** [comment]
I have the same problem.

**Comment by FelixHuneburg** [comment]
I can get my app to run on my 6th gen. iPad and but not on my iPhone 6 - both devices are running iOS `12.3.1`. It also runs on the emulator.

**Comment by greggomalley** [comment]
Same problem here with an iPhone 7

**Comment by iulian34** [comment]
Same problem here with iPhone 7

**Comment by iulian34** [comment]
One solution to start again your app is by changing your Bundle identifier, then start again implementation.

**Comment by vagrantrobbie** [comment]
@iulian34 Do you mean starting a new app bundle?

**Comment by cyanglaz** [comment]
Thank you for providing this issue. I just tried the example app with the latest version of IAP and it seems working for me. Could you make sure your set up is correct with the Apple IAP setup? If anyone can provide a more detailed reproduce steps that would be great.

**Comment by iulian34** [comment]
> @iulian34 Do you mean starting a new app bundle?

Update your current app Bundle identifier, ex. 
com.example.myapp to com.example1.myapp via xcode. 
You need also to update https://appstoreconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app your new bundle ID

**Comment by doctorlh** [comment]
> Thank you for providing this issue. I just tried the example app with the latest version of IAP and it seems working for me. Could you make sure your set up is correct with the Apple IAP setup? If anyone can provide a more detailed reproduce steps that would be great.

I have the same problem. 

**Logs**
2019-06-25 19:34:31.407506+0800 Runner[28811:818694] flutter: Observatory listening on http://127.0.0.1:54305/bdnMvL2pBaE=/
2019-06-25 19:34:31.626895+0800 Runner[28811:818642] Unsupported value: Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={_kCFStreamErrorCodeKey=54, _kCFStreamErrorDomainKey=1} of type NSError
2019-06-25 19:34:31.627250+0800 Runner[28811:818642] *** Assertion failure in -[FlutterStandardWriter writeValue:], ../../flutter/shell/platform/darwin/ios/framework/Source/FlutterStandardCodec.mm:330
2019-06-25 19:34:31.627923+0800 Runner[28811:818642] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported value for standard codec'
*** First throw call stack:
(0x1bdaa927c 0x1bcc839f8 0x1bd9c2988 0x1be486188 0x1017039e0 0x101703b14 0x101703b14 0x101703b14 0x1017038fc 0x1017025f8 0x1016f1fe0 0x101304a50 0x101301d40 0x1013002fc 0x1033ff6f0 0x103400c74 0x10340e6fc 0x1bda3ac1c 0x1bda35b54 0x1bda350b0 0x1bfc3579c 0x1ea26b978 0x1012fd070 0x1bd4fa8e0)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 


but I change the bundle ID，it worked.  why?

**Comment by cyanglaz** [comment]
One of the things I can think of is the share_preference that is used in the example app (It is not necessary to use paired with the in_app_purchase plugin, we used it as a demo purpose). If anyone can try remove everything related to the shared_preference, and see if it works?

**Comment by greggomalley** [comment]
I don't think the shared preferences are what's causing it (that said I do use shared preferences).  However when I switched from using this plugin to the [flutter_inapp_purchase plugin](https://github.com/dooboolab/flutter_inapp_purchase) everything works fine on all devices.

**Comment by iulian34** [comment]
> One of the things I can think of is the share_preference that is used in the example app (It is not necessary to use paired with the in_app_purchase plugin, we used it as a demo purpose). If anyone can try remove everything related to the shared_preference, and see if it works?

Already try that and have the same error using iPhone 7. 
```
 Forwarded port ForwardedPort HOST:1040 to DEVICE:52567
[        ] Forwarded host port 1040 to device port 52567 for Observatory
[   +2 ms] Installing and launching... (completed in 18.7s)
[   +4 ms] Connecting to service protocol: http://127.0.0.1:1040/paKL-DBS5dc=/
[  +20 ms] Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1040/paKL-DBS5dc=/ws
[   +2 ms] "flutter run" took 152,459ms.
[        ] "flutter run" took 152,459ms.
```
I think is something related to store connection.
When I change bundle ID, all working fine.

**Comment by cyanglaz** [comment]
I tried to start a new flutter project and add the plugin into the project and it still works. If someone can provide a consistent way to reproduce it, that would be helpful.

**Comment by iulian34** [comment]
> I tried to start a new flutter project and add the plugin into the project and it still works. If someone can provide a consistent way to reproduce it, that would be helpful.

It may be possible that one sandbox account get stuck with that bundle ID and now even if you try to add new account is throws this error. It is any possibility to see what account was logged before? Maybe that is the problem.

**Comment by vagrantrobbie** [comment]
I can't change my bundle ID because this app is in production.

It works fine with `flutter_inapp_purchase` plugin but I can't get a successful run with `in_app_purchase`. 

I'm wondering if it could be a network problem? A security setting maybe

**Comment by iulian34** [comment]
Reseting your phone with deleting all data, will also solve the problem but this is extreme thing to do...

**Comment by doctorlh** [comment]
I think this pull request will solve. [1819](https://github.com/flutter/plugins/pull/1819)

**Comment by cyanglaz** [comment]
@vagrantrobbie Does https://github.com/flutter/plugins/pull/1819 solve your issue?

**Comment by vagrantrobbie** [comment]
@cyanglaz YES! thanks everyone `in_app_purchase 0.2.0+5` is now working for me
