### ISSUE TITLE
CreateProcessW failed 216

### ISSUE THREAD

**Issue by haris21** [flutter/flutter#34614]
when i running flutter doctor error CreateProcessW failed 216?
anyone may be ever met this..

thanks

**Comment by jonahwilliams** [comment]
I am not sure about your particular case but https://stackoverflow.com/questions/37624369/android-studio-error-errorcreateprocess-error-216-this-version-of-1-is-not-c . looks similar

**Comment by haris21** [comment]
i get this problem when try flutter doctor
![Problem](https://user-images.githubusercontent.com/17497382/59644512-65789000-9197-11e9-8308-a22c5c83e397.png)

**Comment by jonahwilliams** [comment]
The first message is important:
`Flutter requires PowerShell 5.0 or newer`

**Comment by haris21** [comment]
I already install power shell version6
But old version not uninstall.
I looking way to uninstall from my pc

**Comment by haris21** [comment]
Does make effect if the old version is'nt deleted??

**Comment by BondarenkoStas** [comment]
@haris21 did you manage to solve it?

**Comment by haris21** [comment]
No.
