### ISSUE TITLE
Inline Navigation on google_maps_flutter

### ISSUE THREAD

**Issue by danu6677** [flutter/flutter#34622]
I'm building a flutter app which is similar to uber. Objective is to navigate to a given point and update the UI once the navigation is complete. As of now what i found was that inline navigation is not possible, therefore, I managed to open it up from the app with the below code. But i'm stuck with getting a callback once the navigation is completed. Hence, I'm not sure this is the best approach to achieve my objective mentioned above. Any help would much appreciate. My partialy completed code as bellow.

    ` String destination="6.585395,79.960739";
       String currentLocation = "6.873907,79.8810852";

    _navigate() async {
        String url = "https://www.google.com/maps/dir/?api=1&origin=" + currentLocation + "&destination=" + destination + "&travelmode=driving&dir_action=navigate";

      if (await canLaunch(url)) {
         await launch(url);
      } else {
        throw 'Could not launch $url';
     }
    }`

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
