### ISSUE TITLE
version number always 1.0.0

### ISSUE THREAD

**Issue by shyandsy** [flutter/flutter#34628]
## Steps to Reproduce

flutter version: v1.5.4-hotfix.2

## problem
the package info always get app version 1.0.0, and i tried few ways to correct it, but I failed

## what I tried

- modify the version number in  pubspec.yaml
![image](https://user-images.githubusercontent.com/5271457/59665862-48b77900-91e6-11e9-8621-176e914d1205.png)
- adjust the android build.gradle
![image](https://user-images.githubusercontent.com/5271457/59665903-5ff66680-91e6-11e9-9c03-b7e5620fa932.png)
- and use --build-name and --build-number

but the version number get by packageinfo always 1.0.0

**Comment by BaderEddineOuaich** [comment]
Maybe the build folder has the old info
try run command `flutter clean` and run the app again hopefully .

**Comment by BaderEddineOuaich** [comment]
Maybe the build folder has old info.
try run command `flutter clean` and run the app again hopefully .

**Comment by shyandsy** [comment]
the problem has been solved by
```
flutter --clean 
```

**Comment by shyandsy** [comment]
@BaderEddineOuaich 
yeah  u  are right

thank u so much

**Comment by BaderEddineOuaich** [comment]
Glad it helps! you're welcome.

**Comment by BondarenkoStas** [comment]
I think it's safe to close the issue.
