### ISSUE TITLE
Cloud firestore not work properly.

### ISSUE THREAD

**Issue by therichiekumar** [flutter/flutter#34625]
here is my code,
Is there any way to use 'hid' instead of 'widget.hid'

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:rich_alert/rich_alert.dart';

class ProvideDetails extends StatefulWidget {
  String name, hid;

  ProvideDetails(this.name,this.hid);

  @override
  _ProvideDetailsState createState() => _ProvideDetailsState();
}

class _ProvideDetailsState extends State<ProvideDetails> {
  String rname, phone, gender, message, age, pname;

  GlobalKey<FormState> _key = new GlobalKey();

  bool _autovalidate = false;

 

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.name),
      ),
      body: new SingleChildScrollView(
        child: new Container(
          padding: new EdgeInsets.all(15.0),
          child: new Form(
            key: _key,
            autovalidate: _autovalidate,
            child: formUI(context),
          ),
        ),
      ),
    );
  }
 Widget formUI(BuildContext context){
    return new Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        new Padding(padding: new EdgeInsets.all(5.0)),
     
        new Row(
          children: <Widget>[
            new Flexible(
              child: new TextFormField(
                decoration: const InputDecoration(
                  icon: const Icon(Icons.person),
                  hintText: 'Enter candidate full name',
                  labelText: 'Candidate Name',
                ),
                validator: validateName,
                onSaved: (val) {
                  pname = val;
                },
                maxLength: 32,
              ),
            ),
          ],
        ),
        new Row(
          children: <Widget>[
            new Flexible(
              child: new TextFormField(
                decoration: const InputDecoration(
                  icon: const Icon(Icons.person),
                  hintText: 'Enter candidate father name',
                  labelText: 'Candidate father Name',
                ),
                validator: validateFName,
                onSaved: (val) {
                  rname= val;
                },
                maxLength: 32,
              ),
            ),
          ],
        ),
        new TextFormField(
          decoration: new InputDecoration(
            icon: const Icon(Icons.phone),
            hintText: '9*********',
            labelText: 'Contact No',
          ),
          onSaved: (val) {
            phone = val;
          },
          validator: validatePhone,
          maxLines: 1,
          keyboardType: TextInputType.number,
        ),
          new Row(
          children: <Widget>[
            new Flexible(
              child: new TextFormField(
                decoration: const InputDecoration(
                  icon: const Icon(Icons.person),
                  hintText: 'M/F',
                  labelText: 'Gender',
                ),
                validator: validateGender,
                onSaved: (val) {
                  gender = val;
                },
                maxLength: 1,
              ),
            ),
          ],
        ),
      
        new TextFormField(
          decoration: new InputDecoration(
            icon: const Icon(Icons.date_range),
            hintText: 'Eg : 19',
            labelText: 'Age',
          ),
          onSaved: (val) {
            age = val;
          },
          validator: validateAge,
          maxLines: 1,
          keyboardType: TextInputType.number,
        ),
     
        new TextFormField(
          decoration: new InputDecoration(
              labelText: 'Message', icon: Icon(Icons.message)),
          onSaved: (val) {
            message = val;
          },
          validator: validateMessage,
          maxLines: 5,
          maxLength: 256,
        ),

        SizedBox(height: 30.0,),

           FlatButton(
              color: Theme.of(context).primaryColor,
              onPressed: () async {
                addData();
                addDataToUser();
                showDialog(
                    context: context,
                    builder: (BuildContext context) {
                      return RichAlertDialog(
                        alertTitle: richTitle("Confirmed"),
                        alertSubtitle: richSubtitle(widget.name),
                        alertType: RichAlertType.SUCCESS,
                      );
                    });
              },
              padding: EdgeInsets.symmetric(vertical: 32.0),
              child: Center(
                child: Text(
                  "Click me",
                  style: TextStyle(color: Colors.white),
                ),
              ),
            )
        
      ],
    );
  }

  
  String validateName(String val) {
    return val.length == 0 ? "Enter Name First" : null;
  }

  String validateMessage(String val) {
    return val.length == 0 ? "Enter Message First" : null;
  }

  String validatePhone(String val) {
    return val.length == 0 ? "Enter Phone First" : null;
  }

  String validateGender(String val) {
    return val.length == 0 ? "Enter Feedback First" : null;
  }

  String validateFName(String val) {
    return val.length == 0 ? "Enter Candidate fathers name First" : null;
  }

  String validateAge(String val) {
    return val.length == 0 ? "Enter Age First" : null;
  }

   Future<void> addDataToUser() async {
    final FirebaseAuth _auth = FirebaseAuth.instance;
    final Firestore _firestore = Firestore.instance;

    FirebaseUser user = await _auth.currentUser();

    return _firestore
        .collection('users')
        .document(user.uid)
        .collection('clicks')
        .add({'UID': user.uid, 'name': widget.name, 'ID': widget.hid});
  }

  Future<void> addData() async {
    final FirebaseAuth _auth = FirebaseAuth.instance;
    final Firestore _firestore = Firestore.instance;

    FirebaseUser user = await _auth.currentUser();

    return _firestore
        .collection('news')
        .document(widget.hid)
        .collection('clicks')
        .add({'userID': user.uid, 'username': user.displayName,'age': age});
  }
}

**Comment by dblokhin** [comment]
Close the issue and use https://stackoverflow.com for asking questions like this.

**Comment by therichiekumar** [comment]
@dblokhin I Did. here is my question https://stackoverflow.com/questions/56631166/how-get-documentid-from-a-stateless-class-to-another-stateful-class
