### ISSUE TITLE
[firebase_messaging] getToken not works after call deleteInstanceID() in IOS device

### ISSUE THREAD

**Issue by hebersousa** [flutter/flutter#34636]
I do not need to keep the same registration token. so I'm using deleteInstanceID () on logout. But after calling deleteInstanceID () I no longer get any token with getToken ().  I am using firebaseMessaging.setAutoInitEnabled(true); but still not works .
 I realized that this only happens if I call configure () before. This problem does not occur in the ios emulator and Android device. Only IOS device.
Has anyone had the same problem?

Iphone 6s, IOS 12.3.1
Flutter doctor
```
> [✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale
pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
```

**Comment by janmoppel** [comment]
Hello @hebersousa !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by hebersousa** [comment]
@janmoppel I didnt try again, but there is notthing about this issue in changelog in plugin page. I dont call deleteTokenId() more. I use topics to receive push messages and I subscribe/unsubscribe when I need. This is not the best solution but it is what I have.

**Comment by kroikie** [comment]
@hebersousa

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/362. Any further collaboration will be done there.
