### ISSUE TITLE
FlutterView#getBitmap block UI Thread.

### ISSUE THREAD

**Issue by chechuangfeng** [flutter/flutter#34632]
FlutterView#getBitmap must be call on ui thread,  but it cost more than 16ms....

![image](https://user-images.githubusercontent.com/3196849/59672486-27f52080-91f2-11e9-912b-43c41da87ea5.png)

**Comment by chinmaygarde** [comment]
This is working as intended. `FlutterView#getBitmap` needs to perform device to host transfer of the Flutter contents. That API was designed for applications that wanted to screenshot the contents of the FlutterView in a non-interactive manner. Accessing the the contents on the host is going to be slow.

**Comment by tolotrasamuel** [comment]
Did you solve this issue ? I am also trying to record a video but getBitmap is blocking the UI
