### ISSUE TITLE
Firebase Analytics Events do not show up

### ISSUE THREAD

**Issue by crisboarna** [flutter/flutter#34644]
Hello, can anybody help me on flutter integration with firebase analytics ?
I have followed the README to add the package, (using vanilla flutter create project) but I am unable to see the events show up on console or in BigQuery.
The events do not show up on `Events/Dashboard/StreamView` but it they do show up on `DebugView`.
After 24h the base ones that are automatically collected such as session_start or screen_viewshow up but nothing else, despite I saw them on DebugView previous day.
I have waited now for over 48h and there is no event showing up. Can anybody help on this as I am stuck :S would be eternally grateful

**Comment by janmoppel** [comment]
Hello @crisboarna !

Did you manage to solve the issue? Does the problem still persist in the latest version?

**Comment by kroikie** [comment]
@crisboarna

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1037. Any further collaboration will be done there.
