### ISSUE TITLE
[video_player] Stop playing background music/audio when a video is played on Android

### ISSUE THREAD

**Issue by recastrodiaz** [flutter/flutter#34646]
## Use case

When playing a video on Android, 3rd party music players will continue to play their content along with the audio output from the video. This results in garbled audio for the end-user.

## Proposal

I would like the default video player plugin setting to pause 3rd party audio on Android when playing a video (this is the default on iOS already).

At least ~one~ two users would like to not stop 3rd party audio on Android/iOS as his/her videos do not have sound, so this could be a user configurable setting? https://github.com/flutter/flutter/issues/30438

iOS implementation of configurable setting: https://github.com/flutter/plugins/pull/1174

**Comment by mhstoller** [comment]
Are there any workarounds for this? A way to pause/resume the background audio in Flutter manually?

**Comment by ariefwijaya** [comment]
You can use this useful plugin https://pub.dev/packages/audio_service

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/30438, which is now fixed.
