### ISSUE TITLE
[firebase_analytics] handle nested json in event params

### ISSUE THREAD

**Issue by mockturtl** [flutter/flutter#34645]
Calling [`logEvent`](https://github.com/flutter/plugins/blob/master/packages/firebase_analytics/lib/firebase_analytics.dart#L43) with parameters throws unless the map values are [primitives](https://github.com/flutter/plugins/blob/master/packages/firebase_analytics/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java#L154
) and non-null.

It should accept arbitrary JSON and flatten the map for me.

The guardrails around reserved event names are nice.  It would be nice to have more, say, [Error 5 = too many keys](https://firebase.google.com/docs/analytics/errors).

**Comment by crisboarna** [comment]
Hello @mockturtl , do you have your `logEvent` items show up on the Firebase console ? If so, did you just follow the 2 steps here [here](https://pub.dev/packages/firebase_analytics#-installing-tab-) ?

**Comment by mockturtl** [comment]
Hi @crisboarna, are you asking for help re: #34644?  I'll ping you on gitter so we don't derail this issue.

**Comment by kroikie** [comment]
@mockturtl

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1036. Any further collaboration will be done there.
