### ISSUE TITLE
video_player plugin doesn't lay out correctly in some cases on some Android devices

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#34641]
When using a VideoPlayer inside an Expanded widget, which is inside a Column that has a Container at the bottom could lead to bad layout issues on certain Android devices. This does _not_ happen on any iOS device whatsoever. If the Container's height gets tall enough, the video will have its sides cut off inexplicably. The video is set to "cover" its area. Using an image with the same dimensions instead doesn't have any issue and it fills the entire area.

I reproduce this on a Nexus 9 100% of the time.

Here's the code that has an issue:

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class VideoLayoutHomePage extends StatefulWidget {
  @override
  _VideoLayoutHomePageState createState() => _VideoLayoutHomePageState();
}

class _VideoLayoutHomePageState extends State<VideoLayoutHomePage> {
  
  VideoPlayerController _videoPlayerController;

  @override
  void initState() {
    super.initState();

    _videoPlayerController = VideoPlayerController.asset("videos/video.mp4");
    _videoPlayerController.setLooping(true);
    _videoPlayerController.play();
    _videoPlayerController.initialize();
  }

  @override
  void dispose() {
    _videoPlayerController.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return Material(
        type: MaterialType.transparency,
        elevation: 0,
        child: Align(
            // align the card to the bottom
            alignment: Alignment.bottomCenter,
            child: Container(
              decoration: BoxDecoration(
                color: Colors.grey,
                borderRadius: BorderRadius.circular(16.0),
              ),
              height: 528.0,
              width: 416.0,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: <Widget>[
                  Expanded(
                      child: ClipRRect(
                        borderRadius: BorderRadius.vertical(top: Radius.circular(16.0)),
                        /*child: FittedBox(
                          fit: BoxFit.cover,
                          child: Container(
                              width: 818.0,
                              height: 864.0,
                              child: VideoPlayer(_videoPlayerController)
                              //child: Container(color: Colors.blue)
                          ),
                        ),*/
                        child: Image.asset("images/image.png", fit: BoxFit.cover)
                      )
                  ),
                  Container(
                      height: 96.0,
                      child: Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: Align(
                            alignment: Alignment.center,
                            child: Text("Decreasing this container's height, or using an image instead of a video works.", style: TextStyle(fontSize: 18))
                        ),
                      )
                  )
                ],
              ),
            )
        )
    );
  }
}
```

**Comment by dannyvalentesonos** [comment]
The result looks like this on a Nexus 9.
![video_bad_layout](https://user-images.githubusercontent.com/40898687/59690006-a7f99700-91ae-11e9-881f-25550f2892af.png)

**Comment by dannyvalentesonos** [comment]
The same Widget tree using an image instead, that has the same dimensions looks good:
![image_good_layout](https://user-images.githubusercontent.com/40898687/59690066-c2337500-91ae-11e9-9757-cf75b1f1172c.png)

**Comment by dannyvalentesonos** [comment]
I'm not sure if this is an issue with Textures in Flutter, or specifically the video_player plugin. I haven't tried anything else that uses Textures to know for sure.

**Comment by iskakaushik** [comment]
Tried to repro on Samsung A510M, was unable to repro. Will try it on a tablet next.

**Comment by iskakaushik** [comment]
I am not able to repro it on a `Nexus 7` tablet as well. Maybe it's the video, @dannyvalentesonos mind sharing the video with me?

**Comment by Hixie** [comment]
@kf6gpe @matthew-carroll Can you reach out to @dannyvalentesonos to see if they still have the video so we can see if we can reproduce this?

**Comment by matthew-carroll** [comment]
@Hixie I believe the video has already been shared with the appropriate developer.

**Comment by iskakaushik** [comment]
@Hixie I received the video. Thanks @matthew-carroll and @dannyvalentesonos .

**Comment by iskakaushik** [comment]
https://github.com/flutter/plugins/pull/1774 will fix the issue.

**Comment by dannyvalentesonos** [comment]
@iskakaushik flutter/plugins#1774 doesn't look related?

**Comment by iskakaushik** [comment]
@dannyvalentesonos oops, fixed the link

**Comment by iskakaushik** [comment]
@dannyvalentesonos I just merged the fix. You should be able to get this once it rolls to the framework. Let me know if you still run into issues.

**Comment by dannyvalentesonos** [comment]
Thanks @iskakaushik! I'll check when it rolls out.
