### ISSUE TITLE
[google_maps_flutter] Add support for custom marker size

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#34657]
Currently we ignore the marker size in the `ImageConfiguration` and only use it to resolve the asset image `dpi`. This is to scale the image after picking the right resolution per the `size` parameter passed.

**Comment by theochampion** [comment]
Any updates on this? Happy to help if needed ;)

**Comment by dranoer** [comment]
> Any updates on this? Happy to help if needed ;)

I've issue on this, do you any way so I could change it with customSize?

**Comment by giancarlopro** [comment]
I use this as a workaround, may be useful for you. It creates a redimensioned version of the asset image on the fly.
```Dart
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/services.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

Future<Uint8List> getBytesFromAsset(String path, int width) async {
  ByteData data = await rootBundle.load(path);
  ui.Codec codec = await ui.instantiateImageCodec(data.buffer.asUint8List(), targetWidth: width);
  ui.FrameInfo fi = await codec.getNextFrame();
  return (await fi.image.toByteData(format: ui.ImageByteFormat.png)).buffer.asUint8List();
}

Future<BitmapDescriptor> getBitmapDescriptorFromAssetBytes(String path, int width) async {
  final Uint8List imageData = await getBytesFromAsset(path, width);
  return BitmapDescriptor.fromBytes(imageData);
}
```

Usage:
```Dart
final icon = await getBitmapDescriptorFromAssetBytes("asset/image.png", 35);
```

**Comment by enricobenedos** [comment]
I tried today to apply a custom marker using `google_maps_flutter` and also `devicePixelRatio` and `Size` options are ignored

**Comment by Jackwitt77** [comment]
It's been over a year now and Size and devicePixelRatio are still ignored. @giancarlopro I wish your workaround worked but the icon is still the same size no matter if I put 100 or 1 for the width.

**Comment by giancarlopro** [comment]
> It's been over a year now and Size and devicePixelRatio are still ignored. @giancarlopro I wish your workaround worked but the icon is still the same size no matter if I put 100 or 1 for the width.

it should work if you're using `.png` format. have you tested with other images?

**Comment by Jackwitt77** [comment]
> it should work if you're using `.png` format. have you tested with other images?
Sorry, I actually just did a poor job implementing the code. It works great!

**Comment by matijamatija** [comment]
Any progress on this?

**Comment by fernando-s97** [comment]
@TahaTesser @darshankawar any updates on that?

**Comment by MalteBorgwardt** [comment]
The issue with the workaround from @giancarlopro is, that there is a [notable performance drop when loading markers from bytes](https://github.com/flutter/flutter/issues/41731) (#41731).
Thus I wish there was progress on this ticket as well :)

**Comment by rushikmaniar** [comment]
@giancarlopro your code is working in android phone browsers like edge or chrome?
I am Getting error
Cannot read properties of null (reading 'Symbol(dartx.buffer)')

**Comment by giancarlopro** [comment]
> @giancarlopro your code is working in android phone browsers like edge or chrome? I am Getting error Cannot read properties of null (reading 'Symbol(dartx.buffer)')

i've tested only on android and ios, never used flutter for web.

**Comment by phungchiminhquang** [comment]
> 

Thank for your code so so so much

**Comment by sonelektrikci** [comment]
> I use this as a workaround, may be useful for you. It creates a redimensioned version of the asset image on the fly.
> 
> ```dart
> import 'dart:typed_data';
> import 'dart:ui' as ui;
> 
> import 'package:flutter/services.dart';
> import 'package:google_maps_flutter/google_maps_flutter.dart';
> 
> Future<Uint8List> getBytesFromAsset(String path, int width) async {
>   ByteData data = await rootBundle.load(path);
>   ui.Codec codec = await ui.instantiateImageCodec(data.buffer.asUint8List(), targetWidth: width);
>   ui.FrameInfo fi = await codec.getNextFrame();
>   return (await fi.image.toByteData(format: ui.ImageByteFormat.png)).buffer.asUint8List();
> }
> 
> Future<BitmapDescriptor> getBitmapDescriptorFromAssetBytes(String path, int width) async {
>   final Uint8List imageData = await getBytesFromAsset(path, width);
>   return BitmapDescriptor.fromBytes(imageData);
> }
> ```
> 
> Usage:
> 
> ```dart
> final icon = await getBitmapDescriptorFromAssetBytes("asset/image.png", 35);
> ```
Marker sizes still looks different on android and ios. I implemented the exact same code.

**Comment by AsturaPhoenix** [comment]
Thank you for looking into this.

My use case is ~ 4-6 non-resolution-aware assets ported from a website, used for ~1300 marker instances. I found it surprising that in the default usage with no prescaling or configuration, markers appeared normal-sized on web but very small on a mobile device with device pixel ratio 2.75.

Web (small window):
<img src="https://user-images.githubusercontent.com/13222934/201503168-1bb6a2c9-6e9c-480a-91f8-ae9a19fb027e.png" height="256" />

Android, observed / expected:
<img src="https://user-images.githubusercontent.com/13222934/201503296-0c147fab-2d86-49c1-ac3d-1ae33abfaa47.png" height="512" /> <img src="https://user-images.githubusercontent.com/13222934/201503353-1e9b6284-0bf3-440e-9624-0096b5f3bb2c.png" height="512" />

The "expected" image from the right is from my [local fork](https://github.com/AsturaPhoenix/flutter-plugins/commit/0358f46e9dc02cc028945c6570475d468347bd70) which uses the configuration passed along to the native layer to scale for DPI.

My opinion is that consistency, ease of use, and relative ease of implementation are arguments in favor of performing the scaling on the plugin/native side. Requiring the developer to prescale leaves several opportunities for surprises.

Regarding consistency, one thing I noticed looking at the implementation is, though I don't have an iOS test setup yet, the iOS impl does seem to do something with the scaling information:

* [GoogleMapMarkerController.m#L173-L174](https://github.com/flutter/plugins/blob/b1c457fc99a5f560f1ef2e1d9ed60393ebad5c15/packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapMarkerController.m#L173-L174)

I suspect this is related to the "markers appear much larger on iOS than Android" issues.

* #100997
* #24865

One thing it might be worth calling out on the [common side of the plugin](https://github.com/flutter/plugins/blob/b1c457fc99a5f560f1ef2e1d9ed60393ebad5c15/packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/bitmap.dart#L119-L156) is if we do choose to go with the plugin/SDK scaling route, it does not currently pass in the device pixel ratio for the `mipmaps = true` case but does for the `mipmaps = false` case, which makes my fork (and possibly the iOS implementation) behave differently on non-mipmapped assets depending on whether `mipmaps = true` or `mipmaps = false`, which is also surprising. That is, for my case, when `mipmaps = true`, `assetBundleImageKey.scale = 1` whereas if `mipmaps = false`, it's the device pixel ratio 2.75.

**Comment by balaji101010** [comment]
Any progress?? [2023]
