### ISSUE TITLE
Running flutter visual studio on BODHI linux OS

### ISSUE THREAD

**Issue by polpokpol** [flutter/flutter#34650]
newbie here, can I run flutter on BODHI linux? I cant develop and learn well on my current OS ubuntu because of my low-end laptop, and the idea that i have is making my OS very lightweight so i can maximize flutter development with emulator.

**Comment by jonahwilliams** [comment]
Hi @polpokpol, there are a lot of Linux distributions in the world and we don't test on all of them. It sounds like Bohdi is based off of Ubuntu which we do run tests on, so it will probably work.

**Comment by Vickyees** [comment]
> newbie here, can I run flutter on BODHI linux? I cant develop and learn well on my current OS ubuntu because of my low-end laptop, and the idea that i have is making my OS very lightweight so i can maximize flutter development with emulator.

Hey polpokpol, I want to try the flutter in bodhi linux. Was that successful to you ?
