### ISSUE TITLE
dart sdk file don't get unzipped

### ISSUE THREAD

**Issue by rishabh131199** [flutter/flutter#34662]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by rishabh131199** [comment]
it shows error like no such directory though I have downloaded it thrice

**Comment by stuartmorgan** [comment]
Without details, it's impossible for us to debug issues. Please file a new issue and fill in all of the information requested in the template, including the commands you are running, exact error messages, and your platform.
