### ISSUE TITLE
[Android Q] New push route animation on Android Q

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#34675]
Android Q introduced a new animation when navigating between routes inside apps, and Flutter should support that animation transition too: https://imgur.com/a/MWkK8B5

Instead of sliding from the bottom, it mixes a fade + scale from the center of the screen.

**Comment by Salby** [comment]
Do we have any specs on this transition?

Like how much to scale the parent and child screens, duration etc.

**Comment by hacker1024** [comment]
Does anyone know which Android package the activity transition animation is in? We can decompile it and have a look.

**Comment by danteissaias** [comment]
+1

**Comment by shihaohong** [comment]
I believe this has been resolved with https://github.com/flutter/flutter/pull/41935, so I'll close the issue.
