### ISSUE TITLE
Spellcheck for EditableText on iOS/Android

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#34688]
Related Issue: #12920 autocorrection
Related UIKit documentation: https://developer.apple.com/documentation/uikit/uitextinputtraits/1624461-spellcheckingtype

- Red underline to mark misspelled words
- Spellcheck on typing & double-tap selection & caret moving, etc.
- When a word is marked misspelled, show correction candidate list bubble on:
  - Single tap
  - Moving the caret to the end of the word by pressing backspace.

**Comment by HansMuller** [comment]
Android also supports a spell checking service: https://developer.android.com/guide/topics/text/spell-checker-framework

**Comment by ajviera** [comment]
Any news on this issue? It would be ideal to be able to have this so that the applications are more similar to the native ones.

**Comment by dnfield** [comment]
Would anything prevent this from being a plugin?

**Comment by LongCatIsLooong** [comment]
If we want to use the stock spell checker on iOS (probably not going to be easy) we would have to make changes to the ios text plugin I think, as there doesn't seem to be a standalone spell checking api on iOS, it's most likely a feature we get from implementing `UITextInput`.

**Comment by dnfield** [comment]
Ahh, I see.

Yeah, this sounds like something that belongs in the `TextInputPlugin` in the engine.

It actually doesn't sound like it'd be too terrible to implement - on iOS for example we should be able to just use an attributed string instead of a plain NSString, and then send annotations back to the framework as spelling corrections come in. I realize there's some async issues to tangle with there though :)

**Comment by SeanBlagsvedt** [comment]
This is a fundamental issue to any user of a flutter app. Literally my users are telling me they don't want to use my flutter-based messaging app dara.network because they end up sending out misspellings to those they are attempting to impress. It's literally hurting their social credibility. Please, please, please fix this.

**Comment by kevmoo** [comment]
Bumping to P3 – per @jenle-g – this feels like a big hole VS native platforms and the web.

**Comment by GauravCalidig** [comment]
+1

**Comment by blasten** [comment]
@LongCatIsLooong are you working or planning to work on this issue?

**Comment by blasten** [comment]
I heard @camsim99 is interested in working on this project

/cc @jmagman to scope for iOS

**Comment by SeanBlagsvedt** [comment]
I'll buy you a lovely cake if this gets fixed @camsim99 !!!

**Comment by SeanBlagsvedt** [comment]
Any updates on this for 2022?

**Comment by blopker** [comment]
I just noticed this with our app. Very surprising this doesn't work out of the box. I +1's the original post, but would love to get an update on this, or at least a workaround? Users definitely expect this to work like a native app. I guess we could somehow overlay the native component for the text fields we need this on, but that seems overly complex.

**Comment by HansMuller** [comment]
CC @camsim99

**Comment by camsim99** [comment]
Hi! I've been working on a design for this feature for Android (see [design doc](https://docs.google.com/document/d/1AVI2dwpBYtvf7TnDyfLYuE8VLwoMj3iaRLUs3qMjxWY/edit)) and have begun to look into other platforms, as well. I have begun working on implementing this and will update the implementation timeline soon, but I hope to implement this within the first half of the year.

**Comment by blopker** [comment]
Hey @camsim99, thank you for sharing that doc. This is clearly a complex issue, but it feels like it's in good hands. If you would like any testers in the future we'd be happy to give feedback. I will mention most of our customers are on iOS, however it seems like the doc is laying down a path that will help other platforms as well.

**Comment by cyanglaz** [comment]
Assigning myself as I will work on the iOS part.

**Comment by xster** [comment]
What's the state of this FR for Android?

**Comment by namvietcetera** [comment]
Any updates for it?

**Comment by camsim99** [comment]
This is still in progress. Part of Android support was added in https://github.com/flutter/flutter/pull/109643 and iOS is on the way https://github.com/flutter/flutter/pull/110193. I'll update this issue when full support for both is completed.

**Comment by mohamedali170** [comment]
Hi @camsim99,
Any updates?

**Comment by camsim99** [comment]
@mohamedali170 Android and iOS both have partial implementation. Implementation of the red underline and the toolbar with suggestions for Android and iOS is expected around EOY.

**Comment by mohamedali170** [comment]
Well, thanks very much for your efforts @camsim99  . I hope you can finish the remaining implementation in the near future.

**Comment by camsim99** [comment]
Just wanted to update here that I have merged the remaining implementation on Android into the `master` branch as of : https://github.com/flutter/flutter/pull/114460. Still working on somethings related to testing, though, as well as iOS!

**Comment by blopker** [comment]
Nice! Do you have an idea which version this might land in?

**Comment by camsim99** [comment]
> Nice! Do you have an idea which version this might land in?

@blopker This should probably be in the next stable release if not the next beta release. Eventually, you can look for a version number on the merge commit of my latest PR, but it's not tagged now: https://github.com/flutter/flutter/commit/e0742ebb24a3b81736501551fac9598a1094a88a.

**Comment by jonbhanson** [comment]
It appears this feature has landed in Flutter 3.7.  To use it, add this parameter to your EditableText or TextField:
`spellCheckConfiguration: kIsWeb ? null : SpellCheckConfiguration()`.

(The spell check configuration currently seems to break on web)

**Comment by blopker** [comment]
Good progress! Sad news about web though. Hopefully we won't have to wait until another point release for it.

**Comment by camsim99** [comment]
> It appears this feature has landed in Flutter 3.7. To use it, add this parameter to your EditableText or TextField:
> 
> ```dart
> spellCheckConfiguration: kIsWeb ? null : SpellCheckConfiguration()
> ```
> 
> (The spell check configuration currently seems to break on web)

@jonbhanson yes, spell check is partially implemented on both! Thank you for pointing out the crash on web. Filed an issue to follow up on better solutions for crashing in that case https://github.com/flutter/flutter/issues/119542

**Comment by durbek03** [comment]
Any update on this?

**Comment by leighajarett** [comment]
Closing this since it's now complete for iOS and Android as of 3.10
