### ISSUE TITLE
Pass data from native app to flutter module

### ISSUE THREAD

**Issue by dxinh89** [flutter/flutter#34690]
I have read the article: https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps.
My problem is pass data from exists native android app to flutter module (data example: token, username...etc). So, I want to ask if there is any way pass data between Native code in exists native app and code in flutter module???
Look forward to receiving an answer! Thank flutter team!

**Comment by dblokhin** [comment]
Please close the issue and use https://stackoverflow.com for asking questions like this.
I believe you can found your answer at https://flutter.dev/docs/get-started/flutter-for/android-devs#how-do-i-handle-incoming-intents-from-external-applications-in-flutter

**Comment by stuartmorgan** [comment]
As dblokhin mentioned, open-ended questions like this should go to a discussion forum like those listed at https://flutter.dev/community rather than the issue tracker.

In general, the answer to your question is https://flutter.dev/docs/development/platform-integration/platform-channels
