### ISSUE TITLE
 error: use of undeclared identifier 'sourceApplication'                                        sourceApplication:sourceApplication

### ISSUE THREAD

**Issue by pa1more** [flutter/flutter#34699]
ios Error for google sign in . 
I am stuck at this stage .

**Comment by BondarenkoStas** [comment]
Unfortunately, this report does not have any actionable information - it’s not clear if this is a bug in user code, a bug in the framework, or something else entirely.
Please feel free to comment and I will re-open if you can add the following information:
The version of Flutter you’re using
The output of flutter doctor -v
The full exception you see
A minimal reproduction that leads to this exception.
