### ISSUE TITLE
flutter devtools can't connect to my flutter app

### ISSUE THREAD

**Issue by zhang6464** [flutter/flutter#34706]
i run my flutter app using command line:
![image](https://user-images.githubusercontent.com/4263209/59744746-cee6c480-92a5-11e9-9198-eec67daa7e6d.png)
and it's ok, starting up as expect, and i recognized that `Observatory` is also started:
![image](https://user-images.githubusercontent.com/4263209/59744855-11a89c80-92a6-11e9-82ba-a810f98d692b.png)
but when i tried to connect to it with flutter devtools, error occured:
![image](https://user-images.githubusercontent.com/4263209/59744695-b5de1380-92a5-11e9-8e75-24a87fb2d582.png)

and i start devtools(v0.1.1) with:
![image](https://user-images.githubusercontent.com/4263209/59744944-3d2b8700-92a6-11e9-9a59-bc3d0007a94c.png)

flutter doctor:
![image](https://user-images.githubusercontent.com/4263209/59744988-53394780-92a6-11e9-9402-b17f522a77d4.png)

Appreciated for any help...

**Comment by ketanm** [comment]
Hi zhang6464,

Try the following steps:
- First, run DevTools as you did above - `pub global run devtools`
- Second, run your application `flutter run --observatory-port=9500`
- Now open browser and type `http://localhost:9100/?port=9500`, assuming that devtools started on port `9100` and your app is on `9500`
- If you see an error then in the dialog box enter `http://127.0.0.1:9500/UCy...../`

Let me know if this fixes your issue.

**Comment by zhang6464** [comment]
> Hi zhang6464,
> 
> Try the following steps:
> 
> * First, run DevTools as you did above - `pub global run devtools`
> * Second, run your application `flutter run --observatory-port=9500`
> * Now open browser and type `http://localhost:9100/?port=9500`, assuming that devtools started on port `9100` and your app is on `9500`
> * If you see an error then in the dialog box enter `http://127.0.0.1:9500/UCy...../`
> 
> Let me know if this fixes your issue.

That works! After i entered `http://127.0.0.1:9500/UCy...../` into the box~
