### ISSUE TITLE
Unable to check if iOS device supports Touch Id Or Face Id if not enrolled.

### ISSUE THREAD

**Issue by pratima-globant** [flutter/flutter#34705]
I am using local_auth: 0.5.2+2 package in my application.
I didn't find any way to check whether an iOS device supports Touch Id Or Face Id if it(TouchId/FaceId) <cmd-b> is not enrolled on the device.</cmd-b>

If it is enrolled I am able to get the supported biometric type using <cmd-i>getAvailableBiometrics()<cmd-i> method.
Is there any way in local_auth or some other package to check the supported biometric type for a device?

**Comment by TahaTesser** [comment]
Hi @pratima-globant 
Could you please check readme [local_auth](https://pub.dev/packages/local_auth)
```
We have default dialogs with an 'OK' button to show authentication error messages for the following 2 cases:

1. Passcode/PIN/Pattern Not Set. The user has not yet configured a passcode on iOS or PIN/pattern on Android.

2. Touch ID/Fingerprint Not Enrolled. The user has not enrolled any fingerprints on the device. Which means, if there's no fingerprint on the user's device, a dialog with instructions will pop up to let the user set up fingerprint. If the user clicks 'OK' button, it will return 'false'.

Use the exported APIs to trigger local authentication with default dialogs:
```

Looks like there is already clear indication to identify this issue 

if you disagree please write in the comments and I will reopen it 
Thank you
