### ISSUE TITLE
Issue with in_app_purchase plugin documentation

### ISSUE THREAD

**Issue by NickoftheSouth** [flutter/flutter#34708]
On [this](https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/README.md) file there are several errors in the example code;

The line:

`for (PurchaseDetails purchase : repsonse.pastPurchases) {`
Has two errors:
- ":" should be in
- "repsonse" is should be "response" as per the variable name above

Also the line:
`if (_isConsumable(productDetails)) {`
References the method "_isConsumable()" which isn't defined in the library or the scope of the example.

**Comment by Hixie** [comment]
@NickoftheSouth if you would like to submit a PR to fix these, I would be happy to review it!

**Comment by creativecreatorormaybenot** [comment]
@Hixie This is fixed. The `_isConsumable` part is supposed to be like this I think because it is up to the user to decide if a product is consumable or not (might be wrong, just a thought).

**Comment by Pragya007** [comment]
This issue is already fixed.

**Comment by nt4f04uNd** [comment]
close this
