### ISSUE TITLE
how to make ios app in Ubuntu?

### ISSUE THREAD

**Issue by rpotter12** [flutter/flutter#34709]
I am new with flutter. I was trying to learn app development with flutter. 
I was creating a flutter app for android on Android Studio. I was creating an android app on emulator and on my android device by connecting it with laptop. It was running perfectly.
But now I want to create a iOS app for that same code.
**My question is "Is there any way to create iOS app through flutter in Ubuntu?"**

OS - Linux
Distribution - Ubuntu
Version - 19.04 (Disco)

**Comment by rahulmanthena** [comment]
There is currently no way to create iOS apps on OS other than macOS.

**Comment by sangeetagupta2068** [comment]
Hey. @rpotter12 I think the code which you developed for your project should run on an iOS device as well as long as you aren't using any functionalities which require you to touch native code, for instance, camera permissions etc. In that case, you will have to add iOS and android specific components. But, essentially your code should work on iOS devices.

**Comment by jonahwilliams** [comment]
Xcode and the required iOS tooling is only officially available on macOS devices.

**Comment by rpotter12** [comment]
@sangeetagupta2068 @jonahwilliams I'm having an iPad Air(6th generation). Is there any way to connect that device with the laptop( Ubuntu OS) and build that code on the iPad?
