### ISSUE TITLE
Firebase Cloud Messaging: Push not working in release mode

### ISSUE THREAD

**Issue by kavin014** [flutter/flutter#34718]
Push not working in release mode but its working perfectly when i debug.

I couldn't identify the issue, help me someone

**Comment by BondarenkoStas** [comment]
@kavin014 did you managed to solve the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by jawad12345A** [comment]
I am also experiencing this . When the app is in background it is receiving notifications. But when the app is is removed from the system tray . I dont receive any notifications. This only happens in release mode android.
