### ISSUE TITLE
in_app_purchase plugin not updating purchaseUpdatedStream

### ISSUE THREAD

**Issue by dannnnthemannnn** [flutter/flutter#34711]
I am using hte in_app_purchase plugin and am having an issue where the InAppPurchaseConnection.instance.purchaseUpdatedStream is not firing. I am using the app in the alpha channel with test purchases (https://developer.android.com/google/play/billing/billing_testing) and it is correctly going through the google play billing process and sending me emails and everything, but it isn't calling the purchaseUpdatedStream listener. I have printed out stuff to ensure it is setting up the listener so it appears it isn't firing. 

I haven't found anything to indicate it shouldnt fire for situations where you are using test billing. Do we expect it to fire in that scenario? 

Here is my in app purchase service code:
```dart
import 'dart:async';

import 'package:in_app_purchase/in_app_purchase.dart';

class InAppPurchaseService {
  static const String subscriptionId =
      'subscription';

  Future<Map<String, ProductDetails>> _loadProductDetailsFuture;
  StreamSubscription<List<PurchaseDetails>> _subscription;

  InAppPurchaseService() {
    _initialize();
  }

  void _initialize() async {
    final bool available = await InAppPurchaseConnection.instance.isAvailable();
    if (!available) {
      // The store cannot be reached or accessed. Update the UI accordingly.
      print('not available');
    }

    print('adding listener');
    final Stream<List<PurchaseDetails>> purchaseUpdates =
        InAppPurchaseConnection.instance.purchaseUpdatedStream;
    _subscription = purchaseUpdates.listen(_handlePurchaseUpdates);
  }

  void _handlePurchaseUpdates(List<PurchaseDetails> details) {
    print('handling purchase updates');
    print(details.map((detail) => detail.productID).toList());
    print(details);
  }

  void loadSubscriptionProductDetails() {
    _loadProductDetailsFuture = _loadSubscriptionProductDetailsAsync();
  }

  Future<Map<String, ProductDetails>>
      _loadSubscriptionProductDetailsAsync() async {
    print(await InAppPurchaseConnection.instance.isAvailable());
    ProductDetailsResponse response =
        await InAppPurchaseConnection.instance.queryProductDetails(<String>[
      subscriptionId,
    ].toSet());
    if (response.notFoundIDs.isNotEmpty) {
      print('Ids not found');
    } else {
      print(response.productDetails.map((details) => details.id).toList());
    }
    return Map.fromIterable(
      response.productDetails,
      key: (details) => details.id,
      value: (details) => details,
    );
  }

  Future<void> purchaseSubscription(String subscriptionId) async {
    if (_loadProductDetailsFuture == null) {
      loadSubscriptionProductDetails();
    }
    ProductDetails productDetails =
        (await _loadProductDetailsFuture)[subscriptionId];
    if (productDetails == null) {
      print('Product details not found');
    }

    PurchaseParam purchaseParam = PurchaseParam(productDetails: productDetails);
    InAppPurchaseConnection.instance
        .buyNonConsumable(purchaseParam: purchaseParam);
  }
}
```

Any idea why the above listener wouldnt file in this situation when I call purchaseSubscription and it seems to succeed in the app?

**Comment by sageata** [comment]
Reverting to in_app_purchase: 0.1.1+1 seems the only way to go at the moment.

Make sure to delete the pubspeck.lock and also the newer version of the package from the pub-host if you want to do this.

**Comment by dannnnthemannnn** [comment]
is this a known issue? Is there another issue for tracking it?

**Comment by dannnnthemannnn** [comment]
embarrassingly for myself after a cursory search I found https://github.com/flutter/flutter/issues/34040 which seems to reference this issue. will Try 0.1.1+1 and will search more before posting next time.

**Comment by sageata** [comment]
> is this a known issue? Is there another issue for tracking it?

Is not in the priority list to be fixed from what I can see. How can we escalate this?

**Comment by cyanglaz** [comment]
This issue has been fixed with https://github.com/flutter/plugins/pull/1775
I am closing the issue now. if any related issues are found, please feel empowered to open another one with details.
