### ISSUE TITLE
[iOS 13] Context Menus

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#34728]
See https://developer.apple.com/design/human-interface-guidelines/ios/controls/context-menus/

Similar to "peek and pop", which Flutter does [not yet support](https://github.com/flutter/flutter/issues/4963), but doesn't use 3D touch.

![context-menu](https://user-images.githubusercontent.com/389558/59788193-0f334c00-9280-11e9-9f2a-3c009a761c1d.png)

**Comment by justinmc** [comment]
See [this WWDC video](https://developer.apple.com/videos/play/wwdc2019/224/) around 39:00 for more.

**Comment by TLiu2121999** [comment]
Hi @justinmc. I'm trying to implement this delegate method: 
`- (void)tableView:(UITableView *)tableView willCommitMenuWithAnimator:(id<UIContextMenuInteractionCommitAnimating>);
`
and I want to navigate to the next view (which is a view controller showing the currently selected image) after tapping that peeking view, just like the behavior in Photos on iOS13.

However this method doesn't not have a indexPath, so I don't know how to let it know which is the current selected image. 
Do you know if there is any way to do it? 

Thanks!

**Comment by justinmc** [comment]
@TLiu2121999 I don't fully follow, are you attempting to make an implementation of context menus in Flutter?

**Comment by justinmc** [comment]
Some gifs in light and dark modes for reference.

<img width="300" src="https://user-images.githubusercontent.com/389558/62391328-549e9680-b519-11e9-9d3f-e8a9d4a4e639.gif" /> <img width="300" src="https://user-images.githubusercontent.com/389558/62391329-549e9680-b519-11e9-8535-e84e3af7837d.gif" />

**Comment by justinmc** [comment]
A horizontal screenshot from the video.

![Screenshot from 2019-08-13 15-27-27](https://user-images.githubusercontent.com/389558/62981722-e42c2b00-bdde-11e9-8a3a-ddc1d196d461.png)

**Comment by YeungKC** [comment]
The current context menu will always move to the center between the screens, so it is difficult to use it in lists or other places.

like: ![](https://pbs.twimg.com/media/EPVimtRUUAA7V3j?format=jpg&name=medium)

**Comment by justinmc** [comment]
@YeungKC Could you open a separate issue with reproduction steps?

**Comment by YeungKC** [comment]
@justinmc #60334 OK~
