### ISSUE TITLE
Close web platform when tests are complete

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#34735]
In runner.dart, the FlutterWebPlatform should be closed once tests are complete.

Filing based on comments from @jonahwilliams related to the web platform tests in https://github.com/flutter/flutter/pull/34685.

**Comment by jmagman** [comment]
See code snippet in https://github.com/flutter/flutter/pull/34685#issuecomment-503357509.

**Comment by jonahwilliams** [comment]
I've investigated this and found that the web platform tests are already closed correctly.
