### ISSUE TITLE
Problem with Google Maps in iOS, app crash after switch to another page from map page

### ISSUE THREAD

**Issue by jacksun0124** [flutter/flutter#34737]
I couldn't get any error message on this crash. 

My steps was:
1. open app,

2. navigate to map page,

3. zoom out,

4. go back to home page or other page,

5. then crash..

If I remove google map page, this app will never crash. Xcode and VS code don't show any  error message. So I have no idea how it happened. 

I tested this on iPhone6 , 7, and X. This app will crash when using these phones, but it never crash on any Android phone.

I am stacking on this bug for days, so please me. 

My map page code:

```
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class Tester extends StatefulWidget {
  Tester({Key key}) : super(key: key);

  _TesterState createState() => _TesterState();
}

class _TesterState extends State<Tester> {
  GoogleMapController mapController;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
      height: MediaQuery.of(context).size.height,
      width: MediaQuery.of(context).size.width,
      child: GoogleMap(
        onMapCreated: (GoogleMapController controller) {
          mapController = controller;
        },
        initialCameraPosition:
            const CameraPosition(target: LatLng(43.6332, -79.3932), zoom: 12),
      ),
    ));
  }
}
```

My Flutter doctor info:

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale zh-Hans-CA)
    • Flutter version 1.5.4-hotfix.2 at /Users/shijiesun/flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/shijiesun/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • iPhone • 322f1e976614e48eeca824746453ccecd4645d2d • ios • iOS 12.1.4
```

Here is a video to show how it happened.

[https://youtu.be/18An4uYjF1I](https://youtu.be/18An4uYjF1I)

**Comment by salehahmedZ** [comment]
Facing the same issue!! Couldn't solve it :(

**Comment by salehahmedZ** [comment]
I managed to solve this issue by using the `MaterialPageRoute` for navigation I was using a custom PageRoute.

**Comment by Hixie** [comment]
To resolve this we will need a complete application that shows the problem; the code above is incomplete (no runApp, etc).

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
