### ISSUE TITLE
Cloud Firestore Do transaction failed. Reply already submitted

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#34747]
This might be similar to https://github.com/flutter/flutter/issues/17663, however, that issue and all others I found are closed and marked as fixed.

```
Flutter version: Channel master, v1.7.5-pre.10
cloud_firestore: 0.12.5+1
```

I am trying to run a simple transaction on Android:

```
await Firestore.instance.runTransaction((t) async {
  final document = await t.get(reference);
  t.update(document.reference, {
    'b': 'c'
  });
});
```

This immediately fails: https://gist.github.com/creativecreatorormaybenot/cd4e6885c8302bfbc0c02a2913b5bf2a

**Comment by creativecreatorormaybenot** [comment]
@kroikie @collinjackson Are you aware of this issue or do you have any idea what could cause this?  
I am running into another issue (https://github.com/flutter/flutter/issues/35269) on Android (not with transaction but increment). Maybe there is some connection?  
Anyway, I have no idea where to start with either of these.

**Comment by collinjackson** [comment]
As noted in #17663, you need to make sure to include an `await` in your call to `t.update`. We could probably handle this more gracefully though.

**Comment by creativecreatorormaybenot** [comment]
@collinjackson That works 👍   
Note that #35269 does not occur when handled in a transaction, i.e. `FieldValue.increment` works fine in transactions, however, the crash happens for me when using increment in a regular `updateData` or a batched write on the Android P Google Play AVD image.

**Comment by thevzurd** [comment]
I think its similar to the problem I had. Try this. Hope it Helps 
[FIrestore Transaction Handler](https://github.com/thevzurd/Firestore-Transaction-Handler)

**Comment by kroikie** [comment]
@creativecreatorormaybenot

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1224. Any further collaboration will be done there.
