### ISSUE TITLE
Run engine benchmarks and track in our dashboard

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#34746]
Currently, we have some microbenchmarks such as fml_benchmarks, shell_benchmarks, text_benchmarks. But their results are not tracked in our dashboards. We should add them to our (probably future) dashboards.

**Comment by liyuqian** [comment]
CC @iskakaushik @digiter . I'm not sure when this would happen. I guess it's probably better to work on this after we've migrated to the new dashboard such as skia perf or chrome perf?

**Comment by digiter** [comment]
I have no plan for new dashboard currently.

**Comment by liyuqian** [comment]
Closing this as we've adopted Skia perf dashboard and added engine benchmarks in https://github.com/flutter/engine/pull/14556.
