### ISSUE TITLE
How can i locate elements in the application with browser stack?

### ISSUE THREAD

**Issue by artAst** [flutter/flutter#34768]
Im not sure if anyone has encountered this already. But i want to do test automation on browser stack. The problem is i cannot locate the mobile elements of the application created in flutter.

**Comment by jonahwilliams** [comment]
It's not really clear what you're asking about here? Is this for flutter web?

**Comment by artAst** [comment]
Sorry i wasn't clear enough. Its flutter mobile app. In browser stack you can locate elements for mobile app

**Comment by jonahwilliams** [comment]
I don't know what you mean by browser stack or element.

The app switcher and views?
