### ISSUE TITLE
GrowthDirection enum needs clarification 

### ISSUE THREAD

**Issue by tarobins** [flutter/flutter#34763]
https://api.flutter.dev/flutter/rendering/GrowthDirection-class.html

" The direction in which the scroll offset increases is given by the AxisDirection of the sliver."

All slivers in a viewport have the same axis direction, but the scroll direction that causes the scroll offset for a sliver to increase depends on the GrowthDirection, so the above sentence, and others in the docs for GrowthDirection, need to be updated.

**Comment by tarobins** [comment]
Please assign this bug to me.

**Comment by tarobins** [comment]
The first sentence of the description for each value could also use some clarification, as if those sentences are true I think depends on if you are talking about the viewport's scroll offset or the sliver's offset, which can increase in different scroll directions if the GrowthDirection is reverse.

**Comment by Hixie** [comment]
cc @goderbauer

**Comment by Hixie** [comment]
Yeah basically I think GrowthDirection is intended to flip the meaning of AxisDirection.

**Comment by goderbauer** [comment]
Yes. @tarobins Do you intent to send a PR to fix this?

**Comment by tarobins** [comment]
Yes.
