### ISSUE TITLE
Improve Flutter.io performance

### ISSUE THREAD

**Issue by qchong** [flutter/flutter#3476]
Improve benchmark scores per Pagespeed test (https://developers.google.com/speed/pagespeed/insights/?url=flutter.io)

**Comment by sethladd** [comment]
Gained 10 points from https://github.com/flutter/website/issues/227

**Comment by sethladd** [comment]
We're at 72 for mobile now, and 87 for desktop. We should improve this more, but I think we're pretty OK for now. Please reopen if you want to eliminate render-blocking JS and CSS for the above-the-fold content.
