### ISSUE TITLE
errot

### ISSUE THREAD

**Issue by sunguotao** [flutter/flutter#34769]
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#8a63b](state:
flutter: OverlayState#36abe(entries: [OverlayEntry#2db9c(opaque: true; maintainState: false),
flutter: OverlayEntry#b5eb2(opaque: false; maintainState: true)])):
flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 1753 pos 12:
flutter: '_elements.contains(element)': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
