### ISSUE TITLE
Download image with specified size in flutter (Resizing image while downloading from url)

### ISSUE THREAD

**Issue by ManojMM026** [flutter/flutter#34779]
## Use case
I would like to download an image with a user provided size.

## Proposal
 In my case, I have very big images around 2450X1440 resolution, which is making my app crash when I scroll in grid or list, I don't need a full-size image for grid/list I would like to load thumbnail of it lets say around 200X200. I have tried several caching libraries too with no luck. Please let me know how can I achieve it.

**Comment by ketanm** [comment]
@ManojMM026 
Your question is not well defined. Please provide more information and what is wrong with flutter API or details of the crash. Where are you downloading images and who provides a path to it? etc.

Some points:
- Specified resolution is only 10MB of an image, so it is big but not that big that it should crash your app. If there is stack trace then share it.
- Why can't you resize internally for the thumbnail? Not sure why you are using caching libraries.

**Comment by BondarenkoStas** [comment]
@ManojMM026 Do you mean to download them from local storage?
You can change quality with image_picker 0.6.1+4.
