### ISSUE TITLE
NoSuchMethodError: Class 'QuerySnapshot' has no instance getter 'length'

### ISSUE THREAD

**Issue by farazahmad759** [flutter/flutter#34770]
The error appears when I try to access 'snapshot.data.length' to generate a GridView.
`                        children: List.generate(snapshot.data.length, (index) {
`
This was all working about 12 hours from now, but today after a few app-runs it started to shout out this error. Similarly, I cannot access 'snapshot.data[index]' now, the error is similar to the above mentioned.

**Comment by thejacer87** [comment]
why was this closed? i ran into this today, what was the resolution?

**Comment by farazahmad759** [comment]
> why was this closed? i ran into this today, what was the resolution?

The code that worked for me
`Future getContents(String path) async {
  var firestore = Firestore.instance;
  QuerySnapshot qn =
      await firestore.collection(path).orderBy("id").getDocuments();
  return qn.documents;
}
`
The error I was getting because I was returning qn instead of qn.documents.
