### ISSUE TITLE
reverse ‘Add Flutter to existing apps’

### ISSUE THREAD

**Issue by mcxinyu** [flutter/flutter#34775]
About "Adding flutter to an existing application," can you move existing application code into a flutter project to implement the Add Flutter feature of an existing application?

Existing applications can be introduced in the form of "git submodule", which should avoid known packaging issues and team development issues.

**Comment by kangwang1988** [comment]
@mcxinyu 
Can you give more details about your scenario which `add Flutter to existing apps` wiki can't solve your problem?

**Comment by mcxinyu** [comment]
@kangwang1988 I think there are a variety of options available to solve this problem.  Flutter was developed as a new functional module, but the current access method will destroy the development process of the original project. My colleagues have to follow the installation of flutter development environment and learning related knowledge.

**Comment by wickedman1976** [comment]
Do we know of a way to destroy the flutterviewcontroller?  I tried SystemNavigator.pop(); and I tried to destroy the presented viewcontroller?

Thanks
