### ISSUE TITLE
Error stack lost line number in release mode

### ISSUE THREAD

**Issue by FitzLu** [flutter/flutter#34771]
I use FlutterError.onError to catch global error.
```
FlutterError.onError = (errorDetails) {
    //upload errorDetails.stack
  };
```
I build a debug apk, see full information in the errorDetails.stack, all of them has line number, but when I run a release apk, the first line in stack lost line number, it always shows 0.

In debug mode:
```
Exception...
# TestPainter.drawLine(......./file: dart 132)
# TestPainter.draw(......./file: dart 52)
...
```

In release mode:
```
Exception...
# TestPainter.drawLine(......./file: dart 0)     <= (become zero) .       
# TestPainter.draw(......./file: dart 52)
...
```

**Comment by BondarenkoStas** [comment]
@FitzLu Which flutter version did you use? Can you please try it with current stable?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
