### ISSUE TITLE
W/System.err(28819): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Binder_1       image_picker plugin.

### ISSUE THREAD

**Issue by mustafal** [flutter/flutter#34774]
**I had use the [image_picker](https://pub.dev/packages/image_picker) plugin. for picking image from camera and gallery. in android device gallery works perfect but when I am using the camera I am getting thing this error.**
`W/Binder  (28819): Caught a RuntimeException from the binder stub implementation.
W/Binder  (28819): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Binder_1
W/Binder  (28819): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
W/Binder  (28819): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:556)
W/Binder  (28819): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:131)
W/Binder  (28819): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
W/Binder  (28819): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.finishWithSuccess(ImagePickerDelegate.java:481)
W/Binder  (28819): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:455)
W/Binder  (28819): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.access$000(ImagePickerDelegate.java:65)
W/Binder  (28819): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate$4.onPathReady(ImagePickerDelegate.java:422)
W/Binder  (28819): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate$3$1.onScanCompleted(ImagePickerDelegate.java:152)
W/Binder  (28819): 	at android.media.MediaScannerConnection$ClientProxy.onScanCompleted(MediaScannerConnection.java:206)
W/Binder  (28819): 	at android.media.MediaScannerConnection$1.scanCompleted(MediaScannerConnection.java:59)
W/Binder  (28819): 	at android.media.IMediaScannerListener$Stub.onTransact(IMediaScannerListener.java:60)
W/Binder  (28819): 	at android.os.Binder.execTransact(Binder.java:458)
W/System.err(28819): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Binder_1
W/System.err(28819): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
W/System.err(28819): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:556)
W/System.err(28819): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:131)
W/System.err(28819): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
W/System.err(28819): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.finishWithSuccess(ImagePickerDelegate.java:481)
W/System.err(28819): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:455)
W/System.err(28819): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.access$000(ImagePickerDelegate.java:65)
W/System.err(28819): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate$4.onPathReady(ImagePickerDelegate.java:422)
W/System.err(28819): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate$3$1.onScanCompleted(ImagePickerDelegate.java:152)
W/System.err(28819): 	at android.media.MediaScannerConnection$ClientProxy.onScanCompleted(MediaScannerConnection.java:206)
W/System.err(28819): 	at android.media.MediaScannerConnection$1.scanCompleted(MediaScannerConnection.java:59)
W/System.err(28819): 	at android.media.IMediaScannerListener$Stub.onTransact(IMediaScannerListener.java:60)
W/System.err(28819): 	at android.os.Binder.execTransact(Binder.java:458)
`

**here is my code**
`     import 'dart:async';
      import 'dart:io';
      import 'package:camera/camera.dart';
      import 'package:flutter/material.dart';
      import 'package:image_picker/image_picker.dart';
      import 'package:rect_getter/rect_getter.dart';
      import 'camera_view.dart';

      List<File> images = [];
    
      List gridKeys =
      List.generate(images.length, (i) => RectGetter.createGlobalKey());
    
    class MyImgPage extends StatefulWidget {
      MyImgPage({Key key}) : super(key: key);
    
      @override
      _MyImgPageState createState() => _MyImgPageState();
    }
    
    class _MyImgPageState extends State<MyImgPage>
        with SingleTickerProviderStateMixin {
      bool isPageViewVisible = false;
      ScrollController _scrollController = ScrollController();
      OverlayEntry transitionOverlayEntry;
      Future<File> imageFile;
    
      pickImageFromGallery() {
        setState(() {
          imageFile = ImagePicker.pickImage(source: ImageSource.gallery);
    
          imageFile.then((File file) {
            setState(() {
              if (file != null) {
                images.add(file);
              }
            });
          });
        });
      }
    
      pickImageFromCamera() async {
        File cameraFile = await ImagePicker.pickImage(source: ImageSource.camera);
    
        setState(() {
          if (cameraFile != null) {
            images.add(cameraFile);
          }
        });
      }
    
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(
            actions: <Widget>[
              IconButton(
                icon: Icon(Icons.add_a_photo),
                onPressed: () {
                  _showDialog();
                },
              )
            ],
            title: Text('Pictures'),
          ),
          body: images.length > 0 ? _buildGridView() : SizedBox(),
        );
      }
    
      Widget _buildGridView() {
        return GridView.count(
          crossAxisCount: 2,
          controller: _scrollController,
          children: images.map((imageName) {
            return GestureDetector(
              onTap: () {},
              child: Card(
                child: Center(child: Image.file(imageName)),
              ),
            );
          }).toList(),
        );
      }
    
      _showDialog() {
        showDialog(
          context: context,
          barrierDismissible: false,
          builder: (BuildContext ctxt) {
            return AlertDialog(
              title: Text(
                "Select Type",
                style: TextStyle(
                  fontFamily: "Montserrat",
                  fontSize: 22,
                  fontWeight: FontWeight.bold,
                  color: Colors.black,
                ),
              ),
              content: Column(
                mainAxisAlignment: MainAxisAlignment.start,
                children: <Widget>[
                  FlatButton(
                    onPressed: () {
                      Navigator.pop(context);
                      pickImageFromCamera();
                    },
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: <Widget>[
                        Icon(Icons.camera),
                        SizedBox(width: 15.0),
                        Text(
                          "Camera",
                          style: TextStyle(
                            fontFamily: "Montserrat",
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                            color: Colors.black,
                          ),
                        ),
                      ],
                    ),
                  ),
                  FlatButton(
                    onPressed: () {
                      Navigator.pop(context);
                      pickImageFromGallery();
                    },
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: <Widget>[
                        Icon(Icons.photo),
                        SizedBox(width: 15.0),
                        Text(
                          "Gallery",
                          style: TextStyle(
                            fontFamily: "Montserrat",
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                            color: Colors.black,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
              actions: <Widget>[
                FlatButton(
                  onPressed: () {
                    Navigator.pop(context);
                  },
                  child: Text(
                    "Cancel",
                    style: TextStyle(
                      fontFamily: "Montserrat",
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            );
          },
        );
      }
    }`
**and I uses this plugin version**
`image_picker: ^0.4.10`
**Please Help me out, Thanks in advance**

**Comment by sayurikunugi** [comment]
I have the same issue.
I'm using,
  image_picker_modern: ^0.4.12+2

**Comment by sayurikunugi** [comment]
I changed to use,
  image_picker: ^0.6.0+10
, and my problem solved.
Closed for me.

Could be related to this issue.
https://github.com/flutter/flutter/issues/32315

**Comment by mustafal** [comment]
but after do this I had get this error in my console
`D8: Program type already present: android.support.v4.media.MediaBrowserCompat$CustomActionCallback

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/127.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/55.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/12.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/73.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/112.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/49.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/67.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/94.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/106.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/88.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/118.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/64.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/52.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/79.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/16.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/76.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/91.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/103.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/61.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/109.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/100.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/115.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/121.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/58.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/70.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/46.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/82.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/124.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/97.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/85.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/11.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/20.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/21.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/5.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/13.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/4.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/1.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/22.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/18.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/10.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/23.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/19.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/25.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/8.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/24.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/9.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/17.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/0.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/14.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/6.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/7.jar, /home/serpentcs/flutter_projects/fsm_osi/build/app/intermediates/transforms/dexBuilder/debug/15.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.media.MediaBrowserCompat$CustomActionCallback

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1
`

**Comment by danielgchap** [comment]
I find the problem that if I upgrade to image_picker: ^0.6.0+10 I then get AndroidX compatability issues. Any thoughts?

**Comment by BondarenkoStas** [comment]
@mustafal So is it fixed for you while using the current image_picker version?

**Comment by mustafal** [comment]
Yes its working now.
