### ISSUE TITLE
Back iOS chevron icon not quite match the native one

### ISSUE THREAD

**Issue by miguelpruivo** [flutter/flutter#34798]
On the left is the one rendered by Flutter. On the right is the native one. The icon itself doesn’t quite match in size, neither in the corners as they’re rounded compared to the rect rendered by Flutter.

![F4EBC001-0216-4B14-BD59-375166E6510E](https://user-images.githubusercontent.com/27860743/59861730-4b96a300-9379-11e9-8b1c-d6cd825a2b1d.jpeg)![07C6784C-6DDC-42FE-B33D-1C219483BF6D](https://user-images.githubusercontent.com/27860743/59861731-4b96a300-9379-11e9-9c3c-9f66896169d3.jpeg)

```
 Flutter (Channel dev, v1.7.3, on Mac OS X 10.14.5 18F132, locale pt-PT)
    • Flutter version 1.7.3 at /Users/miguelruivo/DevTools/flutter
    • Framework revision 362b999b90 (13 days ago), 2019-06-07 12:43:27 -0700
    • Engine revision 0602dbb275
    • Dart version 2.3.2 (build 2.3.2-dev.0.1 6e0d978505)
```

**Comment by justinmc** [comment]
Thanks for pointing this out, seems like we should definitely update it.  It looks like iOS13 uses the same arrow as well.  Here is a quick screenshot (from the iOS13 Calendar app):

<img width="83" alt="Screen Shot 2019-06-21 at 11 13 58 AM" src="https://user-images.githubusercontent.com/389558/59942921-c90ff100-9415-11e9-94d7-5f9ba1ac92be.png">

**Comment by miguelpruivo** [comment]
You’re welcome @justinmc.

IMO, this is one of the things that iOS users can come across seeing in multiple screens and those with more sensitive eye for these kind of things (like me), may immediately notice and somehow, it feels like a “cheap” clone of the native one. 😄

**Comment by jeremie-movify** [comment]
Hello everyone,

We noticed this issue as well in our Flutter project. I made a PR on the cupertino_icons repo, which got recently merged :
https://github.com/flutter/cupertino_icons/pull/4

Now we'll simply have to wait until a new version is published by the repo's maintainers.

Cheers,

Jérémie

**Comment by miguelpruivo** [comment]
This is great @jeremie-movify, I’m closing this as it’s now on `master`.  Thank you! 🎉
