### ISSUE TITLE
How to set Android app "window" (screenshot says all) color?

### ISSUE THREAD

**Issue by johnveloper** [flutter/flutter#34791]
![Capture+_2019-06-20-15-08-32](https://user-images.githubusercontent.com/49095364/59852203-aa0a5400-936e-11e9-88c9-3a8b830849dc.png)

**Comment by BaderEddineOuaich** [comment]
<h4>Solution 1:</h4>
<pre>class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    FlutterStatusbarcolor.setStatusBarColor(Colors.white);
    return MaterialApp(
      title: app_title,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomePage(title: home_title),
    );
  }
}
</pre>
<hr>
<h4>Solution 2:</h4>
<pre>SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
  statusBarColor: Colors.white
));</pre>

**Comment by BaderEddineOuaich** [comment]
<pre>SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
    systemNavigationBarColor: Colors.blue, // navigation bar color
    statusBarColor: Colors.pink, // status bar color
  ));</pre>

**Comment by johnveloper** [comment]
> SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
>     systemNavigationBarColor: Colors.blue, // navigation bar color
>     statusBarColor: Colors.pink, // status bar color
>   ));

Status bar worked but the area showed on screenshot is still white 😒

**Comment by inthroxify** [comment]
I had this problem too and traced it down.

This is a bug/regression in the flutter engine, caused by [flutter/engine pr #8048](https://github.com/flutter/engine/pull/8048). I am submitting a pr on flutter/engine to fix it.

**Comment by mklim** [comment]
Thanks again for diagnosing and fixing this @inthroxify!
