### ISSUE TITLE
Scrolling vertically Listview

### ISSUE THREAD

**Issue by pekretsc** [flutter/flutter#34790]
Hi 
I havea problem that is driving me nuts in Flutter.

I have a layout that requires some widget like a simple card to be scrolled sideways.
So Listview seemed to be good choise but....

This is working but scrolldirection is vertical since this is the default

Padding(
  padding: EdgeInsets.only(left: 5),
  child: SizedBox(
      height: 105,
      width: MediaQuery.of(context).size.width - 110,
      child: ListView(
        children: <Widget>[
          ListTile(
            title: Text('halleluja'),
          ),
          ListTile(
            title: Text('halleluja'),
          ),
          ListTile(
            title: Text('halleluja'),
          ),
          ListTile(
            title: Text('halleluja'),
          ),
          ListTile(
            title: Text('halleluja'),
          ),
        ],
      )),
)

But if I do it this way:

Padding(
  padding: EdgeInsets.only(left: 5),
  child: SizedBox(
      height: 105,
      width: MediaQuery.of(context).size.width - 110,
      child: ListView(
        **scrollDirection: Axis.horizontal,**
        children: <Widget>[
          ListTile(
            title: Text('halleluja'),
          ),
          ListTile(
            title: Text('halleluja'),
          ),
          ListTile(
            title: Text('halleluja'),
          ),
          ListTile(
            title: Text('halleluja'),
          ),
          ListTile(
            title: Text('halleluja'),
          ),
        ],
      )),
)

I get :
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (16801): The following assertion was thrown during performLayout():
I/flutter (16801): BoxConstraints forces an infinite width.
I/flutter (16801): These invalid constraints were provided to RenderParagraph's layout() function by the following
I/flutter (16801): function, which probably computed the invalid constraints in question:
I/flutter (16801):   _RenderListTile._layoutBox (package:flutter/src/material/list_tile.dart:1300:9)

I just do not get where the difference is, since I have a SizedBox and Scrolling should start if a boundry overflows?!
This also prettymuch always accures when trying to do sidescrolling with the Listview, interesting is that Gridview works just fine but since I am constrained to a Grid this is no option for me:(

Maybe anybody can give me an advise if this is a bug or not, and if there is anown way to do sidescrolling effectively?!

Best regards
Peter

**Comment by dblokhin** [comment]
For the first glance I see here the problem: each ListTile tries to expand to infinite width which causes this exception for the vertical direction case.

**Comment by miDeb** [comment]
I haven't understood what you want to do exactly; maybe have a look on PageView. Otherwise, don't use ListTiles, as they try to expand horizontally, which is impossible with horizontal scrolling since there is literally infinite horizontal space.

**Comment by pekretsc** [comment]
Thanks for the responds :). You are right the expantion into vertical space is the problem. But this is verry counterintuitive. Since ListTiles are for ListViews, They should look into the scrollingdirection. 

But thanks for the hint to pageview, I have not thought about that:)

**Comment by dblokhin** [comment]
@pekretsc so close the issue
