### ISSUE TITLE
The operation of  'brew install --HEAD usbmuxd'  is successful ,but 'brew link usbmuxd' error 

### ISSUE THREAD

**Issue by tliwyl** [flutter/flutter#34797]
litaodeMacBook-Pro:~ litao$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.5
    18F132, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android    SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    ✗ libimobiledevice and ideviceinstaller are not
      installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter
      specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific
      functionality.
[✓] Connected device (1 available)

Next 

litaodeMacBook-Pro:~ litao$ brew install --HEAD usbmuxd
==> Cloning https://git.sukimashita.com/libusbmuxd.git
Updating /Users/litao/Library/Caches/Homebrew/usbmuxd--git
==> Checking out branch master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
HEAD is now at affc9af Convert README to markdown and update links
==> ./autogen.sh
Last 15 lines from /Users/litao/Library/Logs/Homebrew/usbmuxd/01.autogen.sh:
2019-06-20 23:28:34 +0800

./autogen.sh

READ THIS: https://docs.brew.sh/Troubleshooting

litaodeMacBook-Pro:~ litao$ brew link usbmuxd
Error: No such keg: /usr/local/Cellar/usbmuxd

There is no-folder named 'usbmuxd'  in  the directory of '/usr/local/Cellar/'

**Comment by kangwang1988** [comment]
A detailed log to install usbmuxd in my mac is below:
```shell
kylewong@KyleWongdeMacBook-Pro ~ % brew install --HEAD usbmuxd
Warning: You are using macOS 10.15.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this pre-release version.

==> Cloning https://git.sukimashita.com/libusbmuxd.git
Cloning into '/Users/kylewong/Library/Caches/Homebrew/usbmuxd--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> ./autogen.sh
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/usbmuxd/HEAD-a
==> make install
🍺  /usr/local/Cellar/usbmuxd/HEAD-affc9af_1: 13 files, 154.8KB, built in 56 seconds
kylewong@KyleWongdeMacBook-Pro ~ % brew link usbmuxd
Warning: Already linked: /usr/local/Cellar/usbmuxd/HEAD-affc9af_1
To relink: brew unlink usbmuxd && brew link usbmuxd
```
FYI @tliwyl  Check if /usr/local/Cellar/usbmuxd is actually existing in your mac.

**Comment by jaiswalshubham84** [comment]
@kangwang1988 
Hi, i am facing the same issue.
i have checked /usr/local/Cellar/usbmuxd.
The folder is there in my system

**Comment by kangwang1988** [comment]
@jaiswalshubham84 
Can you try 'brew install --HEAD usbmuxd -vd' as the vd options would provides more information.
```dart
  -d, --debug                      If brewing fails, open an interactive
                                     debugging session with access to IRB or a
                                     shell inside the temporary build directory
    -v, --verbose                    Print the verification and postinstall
                                     steps.
```

**Comment by uglyelf** [comment]
I have the same error. running `brew install --HEAD usbmuxd -vd` does a lot, and the tail is:
`Removing: /usr/local/Cellar/usbmuxd/HEAD-73cb5c1... (16 files, 203.3KB)
Error: Not a directory @ dir_s_rmdir - /usr/local/Cellar/usbmuxd
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:242:in `rmdir'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:242:in `rmdir'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:242:in `rmdir_if_possible'
/usr/local/Homebrew/Library/Homebrew/keg.rb:326:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:244:in `block in cleanup_keg'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:329:in `cleanup_path'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:244:in `cleanup_keg'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:230:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:230:in `cleanup_formula'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:158:in `install_formula_clean!'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:246:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:243:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:243:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'`

**Comment by zqqf16** [comment]
Try `sudo rm /usr/local/Cellar/usbmuxd` first
