### ISSUE TITLE
Adding the Object Detection Feature [Firbase ML Package]

### ISSUE THREAD

**Issue by Loopex2019** [flutter/flutter#34800]
In the Firebase Ml Package there are the following Detectors : Face , Barcode , Image Labeling , Text Recognition , Landmark Detection. There is a new Detection model called Object Detection and you can find it in this link : [https://developers.google.com/ml-kit/vision/object-detection-and-tracking/](url) . It is part of ML Kit. So can you add it please as a new Feature.

**Comment by kroikie** [comment]
@Loopex2019

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1159. Any further collaboration will be done there.
