### ISSUE TITLE
Allow to choose more images

### ISSUE THREAD

**Issue by kleinpetr** [flutter/flutter#34806]
Hey, is there some chance to use image_picker as multi_image_picker? This plugin is good but the function of choose multi images is realy missing.

Thanks

**Comment by cyanglaz** [comment]
The native image picker doesn't support multiple images. There are some photo api do that. It would be a good plugin to make if someone is interested. There are also some community packages made for multiple image pickers like https://pub.dev/packages?q=photo, https://pub.dev/packages/photo_manager. Might be worth a try.

**Comment by kleinpetr** [comment]
I think that native image supports multiple images. Because when I long press the image then shows the checkbox with in but when I click to the next image the checkbox switch to the next photo...   In another application called Bazoš in Czech republic (probably not Flutter) when I click choose images then opened exactly the same image picker when I long press to image -> shows checkbox and when I click to the next image then shows the next checkbox and next and next. I swear that is exactly the same Android image picker. 👍

**Comment by kleinpetr** [comment]
@cyanglaz Look this is the screen from flutter_image_picker where I can choose only one image
![65054401_335665903771818_8849768362377478144_n](https://user-images.githubusercontent.com/17269309/59902271-11231980-93fe-11e9-96e3-63b5c84b2c27.png)

And here is the same picker in another Android application where I can choose multiple images.
![64710559_687160331729275_2383566249230598144_n](https://user-images.githubusercontent.com/17269309/59902278-13857380-93fe-11e9-90ae-308992323dbf.png)

**Comment by cyanglaz** [comment]
@kleinpetr I am not aware any native API related to the image picker that does it. I know there is a photo assets framework on iOS and something equivalent on Android can do this. I think this plugin is using the photo asset framework to achieve this behavior. May I ask if flutter_image_picker suffices your need?

**Comment by kleinpetr** [comment]
No.. the both of pickers on screenshots looks exactly the same. It looks like in flutter_image_picker missing just some parametr to allowed multi choosing. 

In this plugin I like it, that  I can use camera and photo. When I use image_picker for camera shots and for example multi_image_picker for multi choose, so one plugin returns File and another File return somenthing Asset object and I want only one List with images.

The next benefit is that image_picker looks great (because using some native library) multi_image_picker looks not too good (Android)

The image_picker has one big bug. When I choose some photo from Recent photos, photo was loaded but not shows. When I choose photo from Google Photos, that works fine. I will open solo ticket for this bug.

So is there some chance to update image_picker to multi choose?
Thank you..

**Comment by kleinpetr** [comment]
look this
There is no official picker yet which supports all versions of Android.

Official Image picker:

See ALLOW_MULTIPLE option (API Level >=18) http://developer.android.com/reference/android/content/Intent.html#ACTION_GET_CONTENT

Third party libraries: See this question:

select multiple images in Android Gallery

https://stackoverflow.com/questions/20700115/multiple-image-video-picker-android

**Comment by cyanglaz** [comment]
You are right, it is natively supported by Android! I haven't found a good way to do it on iOS tho. There has been one issue raised regarding the same. https://github.com/flutter/flutter/issues/16054
I will close this issue, and let's follow up on the other issue?

**Comment by kleinpetr** [comment]
Ok nice, so do you implement this addon in the near future?

**Comment by cyanglaz** [comment]
I'd like to research and find a way to do it in iOS. Android should be easily done.

**Comment by kleinpetr** [comment]
Thank you it will be very very helpful for everyone!
