### ISSUE TITLE
GestureDetector sometimes does not call onTapUp after onTapDown

### ISSUE THREAD

**Issue by babakbo** [flutter/flutter#34810]
## Steps to Reproduce

Create a simple page with a gesture detector:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: GestureDetector(
          onTapUp: (detail) => print('On Tap Up'),
          onTapDown: (detail) => print('On Tap Down'),
          onTapCancel: () => print('On Tap Cancel'),
          child: Container(color: Colors.black, width: 200, height: 200),
        ),
      ),
    );
  }
}
```

Tap quickly with two fingers following these steps: 
1- tap down with first finger,
2 - tap down with second finger,
3 - lift both fingers).

Sometimes, onTapDown is not followed by onTapUp (or onTapCancel). So you end up with the following log even after lifting both your fingers:

I/flutter ( 5682): On Tap Down
I/flutter ( 5682): On Tap Up
I/flutter ( 5682): On Tap Down

It does not happen all the time but It is easily reproducible after a couple of tries.

## Logs

```
Analyzing MyApp...                                                    
No issues found! (ran in 1.7s)
```

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-CA)
    • Flutter version 1.5.4-hotfix.2 at .../Applications/flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at .../Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = .../Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • Pixel 3                   • 94EX3XT8C                            • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by BondarenkoStas** [comment]
@babakbo Is it the same while using current flutter stable?

**Comment by LNeway** [comment]
I have the same issue.

**Comment by Alishgiri** [comment]
It can happen if you tap down and slide your finger somewhere. User onTapCancel method to reset state. I presume that you are using onTapUp to set some values. So, run the same function on onTapCancel.

**Comment by EbenezerGH** [comment]
This was an issue for me, but I was able to work around by resetting values in onPanEnd().

**Comment by ControlAdad** [comment]
onTapCancel is not fired whenever onTapDown is not fired

**Comment by TahaTesser** [comment]
Hi @babakbo 
After testing your code and this [solution](https://github.com/flutter/flutter/issues/34810#issuecomment-574496853) resolves this issue.

As this [comment](https://github.com/flutter/flutter/issues/34810#issuecomment-557784696) points out, it happens on slide. 
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
