### ISSUE TITLE
Unable to run my first flutter program [FAILURE: Build failed with an exception.]

### ISSUE THREAD

**Issue by Pillai1** [flutter/flutter#34829]
**### I am new to mobile app programming. Do guide me if I have made mistakes.**

## Steps to Reproduce

. ...C:\Users\hariharan\Desktop\helloflutter>flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling
software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              0.9s
Resolving dependencies...
*Error running Gradle:
ProcessException: Process "C:\Users\hariharan\Desktop\helloflutter\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

*Where:
Build file 'C:\Users\hariharan\Desktop\helloflutter\android\build.gradle' line: 24

*What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to find target with hash string 'android-28' in: C:\Users\hariharan\AppData\Local\Android\sdk

*Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.

*Get more help at https://help.gradle.org

BUILD FAILED in 2s
  Command: C:\Users\hariharan\Desktop\helloflutter\android\gradlew.bat app:properties

## Logs

**### I am using Visual code to program and running android emulator**

C:\Users\hariharan\Desktop\helloflutter>flutter doctor -v
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.829], locale en-SG)
    • Flutter version 1.5.4-hotfix.2 at C:\flutter_windows_v1.5.4-hotfix.2-stable\flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\hariharan\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = C:\Users\hariharan\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.35.1)
    • VS Code at C:\Users\hariharan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

**Comment by web-developer-saurashtra** [comment]
install flutter plugin in your Android Studio.
Follow the document and try again
https://flutter.dev/docs/development/tools/android-studio

**Comment by Pillai1** [comment]
> install flutter plugin in your Android Studio.
> Follow the document and try again
> https://flutter.dev/docs/development/tools/android-studio

I am sort of confused, please enlighten me. I am using flutter in visual code, Why is there a need to install flutter plugin in my android studio??

**Comment by kangwang1988** [comment]
> A problem occurred configuring project ':app'.
Failed to find target with hash string 'android-28' in: C:\Users\hariharan\AppData\Local\Android\sdk

@Pillai1 
Check if https://stackoverflow.com/questions/33417537/failed-to-find-target-with-hash-string-android-23 might help.
