### ISSUE TITLE
cubic_bezier_perf__timeline_summary worst_frame_rasterizer_time_millis regressed

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#34820]
It regressed from ~65ms to ~90ms starting around https://github.com/flutter/flutter/commit/c8c20fbc1f24bde6741b7a78e86104c5b9c4f180

![image](https://user-images.githubusercontent.com/22987568/59887885-f018e500-9379-11e9-9c12-cc284ef83f04.png)

**Comment by liyuqian** [comment]
@chunhtai : can you please verify locally if the regression actually starts from your commit?

**Comment by chunhtai** [comment]
I dont think my change will affect this, but the manual roll contain 30+commit from flutter/engine, it might be one of them I couldn't tell

**Comment by liyuqian** [comment]
Thanks @chunhtai for the response! Were you able to reproduce the regression locally (run drive test locally before and after your commit)? If so, we can then start bisecting the engine commits as other framework commits are ruled out. Please let me know if you have any questions about how to run the benchmark locally.

**Comment by chunhtai** [comment]
It is pretty hard to be certain which commit cause it since it is not consistently regress.
The most likely culprit is https://github.com/flutter/engine/commit/e5918d18f
>60% chance to see ~90ms after this skia roll

**Comment by liyuqian** [comment]
@bsalomon : https://github.com/flutter/engine/commit/e5918d18f seems to have quite some GPU changes. Do you have any theory of which could cause the regression? I can help bisecting if nothing is obvious.

**Comment by chinmaygarde** [comment]
According to [Brian's comment](https://github.com/flutter/engine/commit/e5918d18f#commitcomment-34036672), the commit was reverted by Jim and the numbers are again below the baseline. Closing.

<img width="287" alt="Screen Shot 2019-06-21 at 4 35 07 PM" src="https://user-images.githubusercontent.com/44085/59956053-b06a0000-9442-11e9-831b-8907fa0df7b3.png">
