### ISSUE TITLE
iOS engine is cold for add to app use case causing initial method channel calls to fail

### ISSUE THREAD

**Issue by ahusseini** [flutter/flutter#34826]
The engine seems to be cold for the very first flutterViewController that is presented. We are using flutter in parts of our app and sending some data to flutter before presenting it. On the first presentation, the method channel call fails (I suspect) because of the call to launchEngine in viewWillAppear.

Moving the method channel call to the completion call back of present solves this issue, but we then see a flicker because the data is set after viewDidAppear.

If we dismiss the flutterViewController and launch another one, it works fine because the engine has already been launched the first time.

## Steps to Reproduce
1. run the engine in `didFinishLaunchingWithOptions`

```swift
flutterEngine = FlutterEngine(name: "io.flutter", project: nil)
flutterEngine?.run(withEntrypoint: nil)
if let engine = flutterEngine {
    GeneratedPluginRegistrant.register(with: engine)
}
```

2. instantiate a `FlutterViewController` with the engine, call the method channel before launching it modally

**_not working_**
```swift
let flutterEngine = (UIApplication.shared.delegate as? AppDelegate)?.flutterEngine
let flutterViewController = FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil)
let channel = FlutterMethodChannel(name: "feature_1", binaryMessenger: flutterEngine)
channel.invokeMethod("setData", arguments: parameters)
present(flutterViewController, animated: true, completion: nil)
```

**_working but not desired_**
call invokeMethod conditionally for a hot engine
```swift
if isHot {
    channel.invokeMethod("setData", arguments: parameters)
}

present(flutterViewController, animated: true) {
    if !isHot {
        isHot = true
        channel.invokeMethod("setData", arguments: parameters)
    }
}
```

call invokeMethod inside the completion handler
```swift
present(flutterViewController, animated: true) {
    channel.invokeMethod("setData", arguments: parameters)
}
```

**Comment by iapicca** [comment]
Hi @ahusseini 
if the issue persist with the latest stable version of flutter
could you please provide your updated `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
