### ISSUE TITLE
ListWheelScrollView with defined controller disables onSelectedItemChanged callback.

### ISSUE THREAD

**Issue by realvorl** [flutter/flutter#34843]
If I want **ListWheelScrollView** to have an offset I need to use **controller** but by doing so the 
 **onSelectedItemChanged** callback does not get triggered anymore. In my use case, I need both to happen. 

## Steps to Reproduce

1. have a `ListWheelScrollView` in a project
2. define and use a callback method for the `onSelectedItemChanged` event
3. define a `controller` for the  `ListWheelScrollView` 

after step 3, the callback method is not called anymore.

here is my implementation:
```
        child: new Center(
          child: new InkWell(
            onTap: () => gotoMainCity(context, selectedCity),
            child: new ListWheelScrollView(
              /*controller: ScrollController(
                initialScrollOffset: 480
              ),*/
              diameterRatio: 1.6,
              clipToSize: true,
              onSelectedItemChanged: setCityInTitle,
              magnification: 1.25,
              useMagnifier: true,
              physics: new BouncingScrollPhysics(),
              children: fillWithCityNames(context),
              itemExtent: 60,
            ), // ListWheelScrollView
          ), // InkWell
        ), // Center
      ), // Container
    ); // Scaffold
  }

  setCityInTitle(int cityId) {
    HapticFeedback.selectionClick();
    selectedCity = CityNames.cityIds[cityId];
    print("scrolled at: " + selectedCity);
  }
```
Without the commented lines, `setCityInTitle` gets called, the haptic feedback is triggered, the message is written to the console. Once the lines are commented in, no callback is made.

## Logs

This issue generates no errors or warnings, so I didn't add a `--verbose` log output.

###  Analyze output:

> Analyzing Bloogies...                                                 
> 
>    info • Unused import: 'dart:async' • lib/service.dart:1:8 • unused_import
>    info • Unused import: 'dart:io' • lib/service.dart:4:8 • unused_import
>    info • The function '_getUserApi' isn't used • lib/service.dart:12:1 • unused_element
> 
> 3 issues found. (ran in 1.7s)

###  Doctor output:

> [✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
>     • Flutter version 1.5.4-hotfix.2 at /home/veo/projects/flutter/flutter
>     • Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
>     • Engine revision 52c7a1e849
>     • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /home/veo/Android/Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • ANDROID_HOME = /home/veo/Android/Sdk
>     • Java binary at: /home/veo/Downloads/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
>     • All Android licenses accepted.
> 
> [✓] Android Studio (version 3.4)
>     • Android Studio at /home/veo/Downloads/android-studio
>     • Flutter plugin version 36.1.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
> 
> [✓] VS Code (version 1.35.1)
>     • VS Code at /usr/share/code
>     • Flutter extension version 3.1.0
> 
> [✓] Connected device (1 available)
>     • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)
> 
> • No issues found!

**Comment by layounisl** [comment]
the `onSelectedItemChanged` will not be triggered unless you use the `FixedExtentScrollController` instead of `ScrollController`

**Comment by realvorl** [comment]
@layounisl that fixes my problem. I have no problem with closing this issue... maybe it is written in the documentation and I didn't pay attention. Thank you.
