### ISSUE TITLE
 TabBar 切换 TabBarView 的一个Bug

### ISSUE THREAD

**Issue by mx4g** [flutter/flutter#34849]
当调用了  Navigator.pop(context)，然后 TabBar 切换 TabBarView 带有 AutomaticKeepAliveClientMixin的页面时，会被重新刷新

**Comment by HansMuller** [comment]
If you could send us a small self-contained app that demonstrates the bug you're run into, we'll look into it. It would also help to include the output of `flutter doctor` - so it's clear what version of Flutter you're using.

**Comment by mx4g** [comment]
small self-contained app ：https://github.com/mx4g/flutter_demo
Operate gif ：https://github.com/mx4g/flutter_demo/blob/master/lib/gif/%E6%93%8D%E4%BD%9C%E5%9B%BE%E7%89%87.gif

**Comment by mx4g** [comment]
> If you could send us a small self-contained app that demonstrates the bug you're run into, we'll look into it. It would also help to include the output of `flutter doctor` - so it's clear what version of Flutter you're using.

//返回上一页，然后再切换就刷新了
 Navigator.pop(context);

demo:
small self-contained app ：https://github.com/mx4g/flutter_demo
Operate gif ：https://github.com/mx4g/flutter_demo/blob/master/lib/gif/%E6%93%8D%E4%BD%9C%E5%9B%BE%E7%89%87.gif

**Comment by shihaohong** [comment]
I further distilled the issue with a fork of the original github repo: https://github.com/shihaohong/flutter_demo

**Comment by shihaohong** [comment]
@mx4g I think what's happening is that in `_PhotoWallState`, you are trying to use `AutomaticKeepAliveClientMixin` but not calling super.build(context). For example:

```
  @override
  Widget build(BuildContext context) {
    super.build(context); // add this line
    return Container(
      child: LoadingContainer(
        isLoading: _loading,
        child: RefreshIndicator(
          onRefresh: _handleRefresh,
          child: _showPic,
        ),
      ),
    );
  }
```

Let me know if that works!

**Comment by mx4g** [comment]
> super.build(context); // add this line

Thank you, Shihaohong. ^_^
