### ISSUE TITLE
Flutter run Error Throws

### ISSUE THREAD

**Issue by sabarinathancs** [flutter/flutter#34850]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Process "/Users/Mac/Dev/apps/android/gradlew" exited abnormally:
Unzipping /Users/Mac/.gradle/wrapper/dists/gradle-4.10.2-all/9fahxiiecdb76a5g3aw9oi8rv/gradle-4.10.2-all.zip to /Users/Mac/.gradle/wrapper/dists/gradle-4.10.2-all/9fahxiiecdb76a5g3aw9oi8rv

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: /Users/Mac/Dev/apps/android/gradlew -v

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:255:5)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:225:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:206:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:134:31)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:111:34)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:105:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:154:23)
<asynchronous suspension>
#7      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:46:32)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:345:56)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:428:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#18     Future._complete (dart:async/future_impl.dart:473:7)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#22     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#29     Future._complete (dart:async/future_impl.dart:473:7)
#30     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#31     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.13.6 17G3025,
    locale en-IN)
    [32m•[39m Flutter version 1.5.4-hotfix.2 at /Users/Mac/development/flutter
    [32m•[39m Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
    [32m•[39m Engine revision 52c7a1e849
    [32m•[39m Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/Mac/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling
      support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    [31m✗[39m Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[31m[✗][39m iOS toolchain - develop for iOS devices
    [31m✗[39m Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    [31m✗[39m libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    [31m✗[39m ios-deploy not installed. To install:
        brew install ios-deploy
    [31m✗[39m CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[32m[✓][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 29.0.2
    [32m•[39m Dart plugin version 181.5540.11
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[32m[✓][39m VS Code (version 1.34.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 2.24.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m Custom Phone, 5 1 0, API 22, 768x1280 • 192.168.56.101:5555 • android-x86
      • Android 5.1 (API 22)

[33m![39m Doctor found issues in 2 categories.
```

**Comment by sabarinathancs** [comment]
sudo flutter run -v
Password:
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
[  +85 ms] executing: [/Users/Mac/development/flutter/] git log -n 1
--pretty=format:%H
[ +107 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] 7a4c33425ddd78c54aba07d86f3f9a4a0051769b
[        ] executing: [/Users/Mac/development/flutter/] git describe --match
v*.*.* --first-parent --long --tags
[  +15 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[   +3 ms] v1.5.4-hotfix.2-0-g7a4c33425
[  +49 ms] executing: [/Users/Mac/development/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/Mac/development/flutter/] git ls-remote --get-url
origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +95 ms] executing: [/Users/Mac/development/flutter/] git rev-parse
--abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +249 ms] executing: /Users/Mac/Library/Android/sdk/platform-tools/adb devices
-l
[  +14 ms] Exit code 0 from: /Users/Mac/Library/Android/sdk/platform-tools/adb
devices -l
[   +1 ms] List of devices attached
           192.168.56.101:5555    device product:vbox86p
           model:Custom_Phone___5_1_0___API_22___768x1280 device:vbox86p
           transport_id:1
[  +16 ms] executing: idevice_id -h
[  +35 ms] /Users/Mac/Library/Android/sdk/platform-tools/adb -s
192.168.56.101:5555 shell getprop
[  +99 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'FuchsiaCacheArtifacts' is not required,
skipping update.
[ +409 ms] ro.hardware = vbox86
[        ] ro.build.characteristics = default
[  +63 ms] Launching lib/main.dart on Custom Phone, 5 1 0, API 22, 768x1280 in
debug
           mode...
[  +27 ms] Initializing gradle...
[   +9 ms] Using gradle from /Users/Mac/Dev/apps/android/gradlew.
[+2398 ms] executing: /usr/bin/defaults read /Applications/Android
Studio.app/Contents/Info
[  +34 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android
Studio.app/Contents/Info
[   +1 ms] {
               CFBundleDevelopmentRegion = English;
               CFBundleDocumentTypes =     (
                           {
                       CFBundleTypeExtensions =             (
                           ipr
                       );
                       CFBundleTypeIconFile = "AndroidStudio.icns";
                       CFBundleTypeName = "Android Studio Project File";
                       CFBundleTypeRole = Editor;
                   },
                           {
                       CFBundleTypeExtensions =             (
                           "*"
                       );
                       CFBundleTypeName = "All documents";
                       CFBundleTypeOSTypes =             (
                           "****"
                       );
                       CFBundleTypeRole = Editor;
                       LSTypeIsPackage = 0;
                   }
               );
               CFBundleExecutable = studio;
               CFBundleGetInfoString = "Android Studio 3.2, build
               AI-181.5540.7.32.5014246. Copyright JetBrains s.r.o., (c)
               2000-2018";
               CFBundleIconFile = "AndroidStudio.icns";
               CFBundleIdentifier = "com.google.android.studio";
               CFBundleInfoDictionaryVersion = "6.0";
               CFBundleName = "Android Studio";
               CFBundlePackageType = APPL;
               CFBundleShortVersionString = "3.2";
               CFBundleSignature = "????";
               CFBundleURLTypes =     (
                           {
                       CFBundleTypeRole = Editor;
                       CFBundleURLName = Stacktrace;
                       CFBundleURLSchemes =             (
                           idea
                       );
                   }
               );
               CFBundleVersion = "AI-181.5540.7.32.5014246";
               JVMOptions =     {
                   ClassPath =
                   "$APP_PACKAGE/Contents/lib/bootstrap.jar:$APP_PACKAGE/Content
                   s/lib/extensions.jar:$APP_PACKAGE/Contents/lib/util.jar:$APP_
                   PACKAGE/Contents/lib/jdom.jar:$APP_PACKAGE/Contents/lib/log4j
                   .jar:$APP_PACKAGE/Contents/lib/trove4j.jar:$APP_PACKAGE/Conte
                   nts/lib/jna.jar";
                   JVMVersion = "1.8*,1.8+";
                   MainClass = "com.intellij.idea.Main";
                   Properties =         {
                       "idea.executable" = studio;
                       "idea.home.path" = "$APP_PACKAGE/Contents";
                       "idea.java.redist" = Bundled;
                       "idea.paths.selector" = "AndroidStudio3.2";
                       "idea.platform.prefix" = AndroidStudio;
                   };
                   WorkingDirectory = "$APP_PACKAGE/Contents/bin";
               };
               LSApplicationCategoryType =
               "public.app-category.developer-tools";
               LSArchitecturePriority =     (
                   "x86_64"
               );
               LSMinimumSystemVersion = "10.8";
               LSRequiresNativeExecution = YES;
               NSHighResolutionCapable = 1;
               NSSupportsAutomaticGraphicsSwitching = 1;
           }
[  +11 ms] executing: /usr/bin/defaults read /Applications/Android
Studio.app/Contents/Info CFBundleShortVersionString
[  +33 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android
Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.2
[ +173 ms] executing: /Users/Mac/Dev/apps/android/gradlew -v
[+1530 ms] 
                    ------------------------------------------------------------
                    Gradle 4.10.2
                    ------------------------------------------------------------

                    Build time:   2018-09-19 18:10:15 UTC
                    Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

                    Kotlin DSL:   1.0-rc-6
                    Kotlin:       1.2.61
                    Groovy:       2.4.15
                    Ant:          Apache Ant(TM) version 1.9.11 compiled on
                    March 23 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b06)
                    OS:           Mac OS X 10.13.6 x86_64
[  +12 ms] Initializing gradle... (completed in 4.2s)
[        ] Resolving dependencies...
[        ] executing: [/Users/Mac/Dev/apps/android/]
/Users/Mac/Dev/apps/android/gradlew app:properties

**Comment by zanderso** [comment]
Will track here: https://github.com/flutter/flutter/issues/36282
