### ISSUE TITLE
[firebase_ml_vision] ImageLabeler doesn't return entityId on iOS

### ISSUE THREAD

**Issue by benadrasni** [flutter/flutter#34852]
ImageLabeler returns null in entityId on iOS. On Android it returns entity id.

I think the problem is with this (Android is using "entityId" but iOS is using "entityID"):
```
Android: 
Map<String, Object> labelData = new HashMap<>();
labelData.put("confidence", (double) label.getConfidence());
labelData.put("entityId", label.getEntityId());
labelData.put("text", label.getText());
labels.add(labelData);


iOS:
NSDictionary *data = @{
              @"confidence" : label.confidence,
              @"entityID" : label.entityID,
              @"text" : label.text,
};
```

**Comment by BondarenkoStas** [comment]
@benadrasni Is it the same while using current firebase_ml_vision 0.9.2+2?

**Comment by benadrasni** [comment]
Yes, the problem is still there. 

Very easy solution:

NSDictionary *data = @{
              @"confidence" : label.confidence,

              @"entityId" : label.entityID,

              @"text" : label.text,
};

**Comment by kroikie** [comment]
@benadrasni

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1158. Any further collaboration will be done there.

**Comment by benadrasni** [comment]
Yes, the problem is still there.

Very easy solution - replace "entityID" with "entityId" in ImageLabeler.m:

NSDictionary *data = @{
              @"confidence" : label.confidence,

              @"entityId" : label.entityID,

              @"text" : label.text,
};
