### ISSUE TITLE
Networking on iOS is broken

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#3486]
## Steps to Reproduce

Use a version of Flutter 99718794b39f5b8b4f97e6fd9df268fe46ff9743 or later.
Make a network request
Exception is thrown in mojo_client.dart

The solution is to make sure that the response.headers returned by the networking Mojo service is set correctly on iOS. (It seems to be set correctly on Android already.)

This affects the Stocks app, since it pulls data from the network.

**Comment by sethladd** [comment]
Thanks for the catch! Is there a way to write a test for this regression that can run on our buildbots?

**Comment by collinjackson** [comment]
Yes! We are actually already testing it in the stocks app performance iOS test. And the test is broken. :)

@yjbanov

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/3535

**Comment by abarth** [comment]
Should be fixed now.
