### ISSUE TITLE
Should .ios and .android folders be gitignored?

### ISSUE THREAD

**Issue by gkrawiec** [flutter/flutter#34868]
Why are these two folders `.ios` and `.android `not in gitignore if they are autogenerated and huge? I don't see any patterns in there that would include them.

**Comment by OrenLeung** [comment]
.ios and .android are not in gitignore as flutter allows adding platform specific native code into each folder.

**Comment by basselch** [comment]
Sometimes you make changes to your gradle files (to add some dependencies) and AndroidManifest (to add permissions) or to some files in the ios folder like `Info.plist`, and you want these changes to be tracked, otherwise the app may not compile/work properly after downloading a new clone.

**Comment by gkrawiec** [comment]
thanks for the info. Now I understand.
