### ISSUE TITLE
Crash report:  NoSuchMethodError: NoSuchMethodError: The method

### ISSUE THREAD

**Issue by leonardop21** [flutter/flutter#34879]
Hello, I'm reporting a flutter crash when running the flutter build apk command

I was having problems with architecture 32 and 62, I followed this tutorial and when I get to the last command does not finish

https://github.com/flutter/flutter/issues/18494#issuecomment-501544474

Log generated:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk

## exception

NoSuchMethodError: NoSuchMethodError: The method 'copySync' was called on null.
Receiver: null
Tried calling: copySync ("/ Users / wwwjsw / Desktop / leonardo / myapp / build / app / outputs / apk / app.apk")

(I.e.
 0 Object.noSuchMethod (dart: core-patch / object_patch.dart: 50: 5)
 1 _buildGradleProjectV2 (package: flutter_tools / src / android / gradle.dart: 519:20)
 2 _asyncThenWrapperHelper. <Anonymous closure> (dart: async-patch / async_patch.dart: 77:64)
 3 _rootRunUnary (dart: async / zone.dart: 1132: 38)
 4 _CustomZone.runUnary (dart: async / zone.dart: 1029:19)
 5 _FutureListener.handleValue (dart: async / future_impl.dart: 126: 18)
 6 Future._propagateToListeners.handleValueCallback (dart: async / future_impl.dart: 639:45)
 7 Future._propagateToListeners (dart: async / future_impl.dart: 668:32)
 8 Future._complete (dart: async / future_impl.dart: 473: 7)
 9 _SyncCompleter.complete (dart: async / future_impl.dart: 51: 12)
 10 _AsyncAwaitCompleter.complete (dart: async-patch / async_patch.dart: 28: 18)
 11 _completeOnAsyncReturn (dart: async-patch / async_patch.dart: 294: 13)
 12 runCommandAndStreamOutput (package: flutter_tools / src / base / process.dart)
 13 _asyncThenWrapperHelper. <Anonymous closure> (dart: async-patch / async_patch.dart: 77:64)
 14 _rootRunUnary (dart: async / zone.dart: 1132: 38)
 15 _CustomZone.runUnary (dart: async / zone.dart: 1029:19)
 16 _FutureListener.handleValue (dart: async / future_impl.dart: 126: 18)
 17 Future._propagateToListeners.handleValueCallback (dart: async / future_impl.dart: 639:45)
 18 Future._propagateToListeners (dart: async / future_impl.dart: 668:32)
 19 Future._completeWithValue (dart: async / future_impl.dart: 483: 5)
 20 Future._asyncComplete. <Anonymous closure> (dart: async / future_impl.dart: 513: 7)
 21 _rootRun (dart: async / zone.dart: 1124: 13)
 22 _CustomZone.run (dart: async / zone.dart: 1021:19)
 23 _CustomZone.runGuarded (dart: async / zone.dart: 923: 7)
 24 _CustomZone.bindCallbackGuarded. <Anonymous closure> (dart: async / zone.dart: 963:23)
 25 _microtaskLoop (dart: async / schedule_microtask.dart: 41: 21)
 26 _startMicrotaskLoop (dart: async / schedule_microtask.dart: 50: 5)
 27 _runPendingImmediateCallback (dart: isolate-patch / isolate_patch.dart: 116: 13)
 28 _RawReceivePortImpl._handleMessage (dart: isolate-patch / isolate_patch.dart: 173: 5)
(I.e.

## flutter doctor

(I.e.
? [32m [✓]? [39m Flutter (Channel dev, v1.7.4, on Mac OS X 10.13.6 17G7024, locale en-US)
    ? [32m •? [39m Flutter version 1.7.4 at / Users / wwwjsw / Documents / flutter
    ? [32m •? [39m Framework revision dfecafa4ab (7 days ago), 2019-06-14 09:46:23 -0700
    • [32m •? [39m Engine revision 2589785b5c
    ? [32m •? [39m Dart version 2.4.0

? [32m [✓]? [39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ? [32m •? [39m Android SDK at / Users / wwwjsw / Library / Android / sdk
    ? [32m •? [39m Android NDK location not configured (optional; useful for native profiling
      support)
    ? [32m •? [39m Platform android-28, build-tools 28.0.3
    ? [32m •? [39m Java binary at: / Applications / Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • [32m • • [39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    ? [32m •? [39m All Android licenses accepted.

? [33m [?]? [39m Xcode - develop for iOS and macOS (Xcode 10.1)
    • [32m • • [39m Xcode at /Applications/Xcode.app/Contents/Developer
    ? [32m •? [39m Xcode 10.1, Build version 10B61
    ? [33m!? [39m CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve iOS and macOS platform side's plugin
        code that responds to your usage plugin on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

? [32m [✓]? [39m iOS tools - develop for iOS devices
    ? [32m •? [39m ios-deploy 1.9.4

? [32m [✓]? [39m Android Studio (version 3.4)
    ? [32m •? [39m Android Studio at / Applications / Android Studio.app/Contents
    ? [32m •? [39m Flutter plugin version 35.3.1
    ? [32m •? [39m Dart plugin version 183.6270
    • [32m • • [39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

? [32m [✓]? [39m VS Code (version 1.35.1)
    • [32m • • [39m VS Code at / Applications / Visual Studio Code.app/Contents
    ? [32m •? [39m Flutter extension version 3.1.0

? [33m [!]? [39m Connected device
    ? [33m!? [39m No devices available

? [33m!? [39m Doctor found issues in 2 categories.
(I.e.

What should I do?

**Comment by kangwang1988** [comment]
The related logic seems here.
```dart
  if (!isBuildingBundle) {
    final Iterable<File> apkFiles = findApkFiles(project, androidBuildInfo);
    if (apkFiles.isEmpty)
      throwToolExit('Gradle build failed to produce an Android package.');
    // Copy the first APK to app.apk, so `flutter run`, `flutter install`, etc. can find it.
    // TODO(blasten): Handle multiple APKs.
    apkFiles.first.copySync(project.apkDirectory.childFile('app.apk').path);

    printTrace('calculateSha: ${project.apkDirectory}/app.apk');
    final File apkShaFile = project.apkDirectory.childFile('app.apk.sha1');
    apkShaFile.writeAsStringSync(_calculateSha(apkFiles.first));

    for (File apkFile in apkFiles) {
      String appSize;
      if (buildInfo.mode == BuildMode.debug) {
        appSize = '';
      } else {
        appSize = ' (${getSizeAsMB(apkFile.lengthSync())})';
      }
      printStatus('Built ${fs.path.relative(apkFile.path)}$appSize.',
          color: TerminalColor.green);
    }
  }
```
Wired, @leonardop21 
Can you verify if `/ Users / wwwjsw / Desktop / leonardo / myapp / build / app / outputs / apk / app.apk` is generated properly?

**Comment by leonardop21** [comment]
Hello, @kangwang1988, thank you for your response. Where do I enter the code? I got confused.
