### ISSUE TITLE
[web]: Transform.scale rasterizes elements

### ISSUE THREAD

**Issue by drewcovi** [flutter/flutter#34878]
When using Transform.scale, elements are simply scaled up without re-rendering elements, leading to low-resolution assets.

Tested on a Switch component.

**Comment by BondarenkoStas** [comment]
@drewcovi Please provide your flutter doctor -v output, and some code example to reproduce the issue.

**Comment by yjbanov** [comment]
This is a bug in the web engine. To fix it we need to compute pixel density based on ancestor transforms and adjust the bitmap canvas size.

**Comment by darshankawar** [comment]
@drewcovi @yjbanov Is this still a valid issue on latest Flutter version ?
@drewcovi If issue persists, can you provide a minimal complete reproducible code sample that shows the issue ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
