### ISSUE TITLE
Flutter run relies on hardcoded APK names

### ISSUE THREAD

**Issue by athornz** [flutter/flutter#34882]
## Steps to Reproduce

1. Customise the Android APK output name:
```
defaultConfig {
        ...
        setProperty("archivesBaseName", "v$versionName")
    }
```
2. Run `flutter run`
3. Build fails with `Gradle build failed to produce an Android package`

## Logs
`Gradle build failed to produce an Android package`

Flutter should get the APK name from Gradle rather than relying on a hardcoded one.

**Comment by maxlapides** [comment]
I think these issues are related:

https://github.com/flutter/flutter/issues/18232
https://github.com/flutter/flutter/issues/13977

**Comment by BondarenkoStas** [comment]
Duplicate of #13977
