### ISSUE TITLE
Engine should eagerly call onBeginFrame after running Dart's main()

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3488]
There's no reason for us to wait. On average, waiting means we wait 8ms of startup time doing nothing.

**Comment by dragostis** [comment]
Is this bug still relevant?

Running

```
void main() {
  DateTime now = new DateTime.now();

  ui.window.onBeginFrame = (Duration timeStamp) {
    print(new DateTime.now().difference(now));
  };
}
```

prints ~2ms.

**Comment by Hixie** [comment]
Weird. Why 2ms? I would have expected 0ms or an even spread from 0 to 16ms.

**Comment by Hixie** [comment]
I see a variety of numbers testing both release and debug on a Nexus 6.
Debug seems to be 0-16ms, release seems to be 11ms-100+ms.
Also, in release for some reason we seem to call onBeginFrame twice in quick succession.

In conclusion, this bug is still relevant. :-)

**Comment by jhirth** [comment]
> Also, in release for some reason we seem to call onBeginFrame twice in quick succession.

On my device, it always starts with 2 window.onMetricsChanged calls where window.physicalSize is still 0x0.

Does that event also trigger a redraw?

**Comment by abarth** [comment]
> Does that event also trigger a redraw?

By itself, that does not trigger a redraw, but it's common for code that's listening to that event to schedule a redraw.

**Comment by zoechi** [comment]
Is this issue still relevant?

**Comment by markusaksli-nc** [comment]
Engine doesn't seem to call this after Dart's main(). Can only get a print if I use runApp() at some point as well (but the duration is no longer useful then).

**Comment by chinmaygarde** [comment]
Today, frame scheduling begins eagerly as soon as the rasterizer is setup.
