### ISSUE TITLE
Update build system to produce multiple JARs

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#34889]
Update build system to produce multiple AARs with POM files:

- Core embedding AAR (FlutterJNI, FlutterEngine, FlutterView, and associated classes)
- Full Flutter AAR (FullFlutterActivity) -> Depends on Core
- Add-to-app AAR (FlutterActivity, FlutterFragment) -> Depends on Core

Steps to completion:

- [ ] Configure engine to produce AARs with resource support
- [ ] Configure engine to produce a POM for each AAR
- [ ] Configure engine to segment the embedding at the appropriate places for the desired AARs

**Comment by matthew-carroll** [comment]
CC @xster @blasten

**Comment by blasten** [comment]
I don't think this is still relevant. Feel free to reopen otherwise.
