### ISSUE TITLE
Create FullFlutterActivity

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#34887]
FullFlutterActivity needs to bring a fullscreen Flutter experience with no support lib deps.

**Comment by matthew-carroll** [comment]
CC @xster

**Comment by xster** [comment]
Connecting dots. https://github.com/flutter/engine/pull/9895 will close this.

**Comment by matthew-carroll** [comment]
Closing via https://github.com/flutter/engine/pull/9895
