### ISSUE TITLE
Emulator doesn't run in VS Code

### ISSUE THREAD

**Issue by anonymouse703** [flutter/flutter#34899]
I installed flutter in VS Code.. in the first two weeks the emulator will launched but when I updated the flutter OS the emulator doesn't launch anymore.... 

![error](https://user-images.githubusercontent.com/37643245/59958379-6c293f00-94d8-11e9-8163-6221f63fdba8.PNG)

**Comment by anonymouse703** [comment]
I installed flutter in VS Code.. in the first two weeks the emulator will launched but when I updated the flutter OS the emulator doesn't launch anymore.... 

![error](https://user-images.githubusercontent.com/37643245/59958379-6c293f00-94d8-11e9-8163-6221f63fdba8.PNG)

**Comment by timsneath** [comment]
We could really use a little more information, @anonymouse703! 

Any chance you could include the results of running `flutter doctor -v` ?

Are you able to successfully run `flutter upgrade`?

**Comment by anonymouse703** [comment]
sir @timsneath  I got this error..

![image](https://user-images.githubusercontent.com/37643245/60062433-c2da8700-972b-11e9-88bb-ca43da2dd111.png)

**Comment by kangwang1988** [comment]
It seems that your PowerShell version is not expected.
See https://flutter.dev/docs/get-started/install/windows for more.
