### ISSUE TITLE
flutter driver --no-build: remove Android SDK dependency for use in AWS Device Farm

### ISSUE THREAD

**Issue by mmcc007** [flutter/flutter#34909]
## Use case

I developed a package that enables running integration tests on AWS Device Farm (see https://pub.dev/packages/sylph). It uses the `--no-build` option for iOS devices successfully. 

However, for android devices `--no-build` has a dependency on the Android SDK to get the app id (like com.example.example), requiring installing the SDK before running the test. This runs-up the billing and requires waiting for the test to complete.

I got around this dependency by grepping for the app id in the gradle file and including in a `--no-build`-like script:
https://github.com/mmcc007/sylph/blob/3e773a21608db5e4d7e57e31a4349a63c94cb94a/lib/resources/script/test_android.sh#L49-L91

Might also be possible to extract from the .apk.

## Proposal

By-pass the Android SDK dependency by either:
- add an option to `flutter drive` to accept the app id when using the --no-build option.
or
- add an option to `flutter drive` to accept the apk to extract the app id when using the --no-build option.

Additional: the `--no-build` option was added due to this issue:
#28662

**Comment by mmcc007** [comment]
The following extracts the app id from the .apk. 
```bash
getAppIdFromApk() {
  local apk_path="$1"

  # regular expression (required)
  local re="^\"L.*/MainActivity;"
  # sed substitute expression
  local se="s:^\"L\(.*\)/MainActivity;:\1:p"
  # tr expression
  local te=' / .';

  local app_id="$(unzip -p $apk_path classes.dex | strings | grep -Eo $re | sed -n -e $se | tr $te)"

  echo "$app_id"
}
```

This approach has the advantage that since flutter drive can find the .apk if present, therefore no additional parameter should need to be passed. In Device Farm the .apk is always present (or can be guaranteed to be).

**Comment by mmcc007** [comment]
@tvolkert if installing the Android SDK, required by `flutter drive --no-build` during a test on an android device, can be avoided, test execution times become close to expected. This also improves metered (billed) time per test by the time it takes to install the Android SDK.

I am currently working around this dependency with a custom test runner which does not require the Android SDK. For improved reliability, it would be nice if this was fixed at some time in the future.

**Comment by jonahwilliams** [comment]
This is not something we're planning on adding, since `flutter drive` is mostly a convenience script. There is a use-existing-app option which can accept a vm service URI, if you have manually started the APK
