### ISSUE TITLE
Receiving intent when app is already open

### ISSUE THREAD

**Issue by sukhcha-in** [flutter/flutter#34904]
I have implemented what flutter docs say: [Here](https://flutter.dev/docs/get-started/flutter-for/android-devs#how-do-i-handle-incoming-intents-from-external-applications-in-flutter),
It works fine when app is closed and launched using share intent from other app.
Issue happens when app is already running and is on another route where widgets are already built and i try to share intent.
It just ignores the share intent. Maybe initState is not called again?

Is there any way to get share intent no matter on what route i am on my running app?

**Comment by iapicca** [comment]
Hi @sukhcha-in 
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @sukhcha-in 
Closing as there are not sufficient details to act upon this issue. If the problem persists, please create a new issue and provide the information required in the template.
Thank you
