### ISSUE TITLE
Image picker not working 8.0

### ISSUE THREAD

**Issue by maheshsystimanx** [flutter/flutter#34902]
Flutter image picker not working 8.0 mobile.but working other mobiles(include pie also).

**Comment by kangwang1988** [comment]
@maheshsystimanx 
Paster `flutter doctor -v` please.

**Comment by maheshsystimanx** [comment]
this code run by terminal or where?
please give explain

**Comment by juliengit2** [comment]
what do you mean by 8.0? android api 28 you mean?

**Comment by maheshsystimanx** [comment]
i run this command.but below show this error.pls help resolve


flutter doctor -v
[!] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_IN)
    • Flutter version 1.5.4-hotfix.2 at /home/systimanx/Downloads/flutter
    • Framework revision 7a4c33425d (9 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-gcc-libs


 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/systimanx/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /snap/android-studio/76/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.4)
    • Android Studio at /snap/android-studio/76/android-studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Android Studio (version 3.3)
    • Android Studio at /snap/android-studio/73/android-studio
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • moto e5 plus • ZF6223G4WV • android-arm • Android 8.0.0 (API 26)

! Doctor found issues in 2 categories.

**Comment by BondarenkoStas** [comment]
@maheshsystimanx did you manage to solve it?
What the linux you use?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
