### ISSUE TITLE
ios App Crashes on Navigation.push, but works fine on android

### ISSUE THREAD

**Issue by aqibfareex** [flutter/flutter#34901]
Hi,
The app runs well on android, but crashed on ios, throwing this exception.
**Logs**

    *** First throw call stack:
    (
            0   CoreFoundation                      0x0000000103eae6fb __exceptionPreprocess + 331
            1   libobjc.A.dylib                     0x0000000103452ac5 objc_exception_throw + 48
            2   CoreFoundation                      0x0000000103eccab4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
            3   CoreFoundation                      0x0000000103eb3443 ___forwarding___ + 1443
            4   CoreFoundation                      0x0000000103eb5238 _CF_forwarding_prep_0 + 120
            5   Runner                              0x00000001008d0998 -[FlutterWebviewPlugin initWebview:] + 2760
            6   Runner                              0x00000001008cf90e -[FlutterWebviewPlugin handleMethodCall:result:] + 254
            7   Flutter                             0x0000000100d61b9a __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 115
            8   Flutter  <…>
    Lost connection to device.

The app crashes when it reaches a Navigator.push method.

    name: webview_no_firebase
    description: A new Flutter application.
    
    version: 1.0.0+1
    
    environment:
      sdk: ">=2.1.0 <3.0.0"
    
    dependencies:
      flutter:
        sdk: flutter
    
      cupertino_icons: ^0.1.2
      flutter_webview_plugin: ^0.2.1+2
      android_intent: any
      share: ^0.6.1+1
      firebase_core: any
    
    dev_dependencies:
      flutter_test:
        sdk: flutter
    
    flutter:
      uses-material-design: true
    
      assets:
        - images/img.png
        - images/logo.png

**#flutter doctor -v**
    
    [✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-IN)
        • Flutter version 1.5.4-hotfix.2 at /Users/shaan/flutter
        • Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
        • Engine revision 52c7a1e849
        • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
    
     
    [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
        • Android SDK at /Users/shaan/Library/Android/sdk
        • Android NDK location not configured (optional; useful for native profiling support)
        • Platform android-28, build-tools 28.0.3
        • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
        • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
        • All Android licenses accepted.
    
    [✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
        • Xcode at /Applications/Xcode.app/Contents/Developer
        • Xcode 10.2.1, Build version 10E1001
        • ios-deploy 1.9.4
        • CocoaPods version 1.7.2
    
    [✓] Android Studio (version 3.4)
        • Android Studio at /Applications/Android Studio.app/Contents
        • Flutter plugin version 36.0.1
        • Dart plugin version 183.6270
        • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    
    [✓] Connected device (1 available)
        • iPhone Xʀ • 991644B0-5663-4B12-AA6F-69F276E821AD • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    
    • No issues found!

**Comment by aqibfareex** [comment]
@zoechi

**Comment by kangwang1988** [comment]
@aqibfareex 
Can you provide a self-contained minimal demo app which can help to reproduce this issue?
