### ISSUE TITLE
How to use AnimatedIcon ?

### ISSUE THREAD

**Issue by ADLsourceCode** [flutter/flutter#34900]
Hello,
How to use Animatedicon class ? Pls Provide examples and is this supported for ios too?

**Comment by calvinmuller** [comment]
Take a look at https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/gallery/backdrop.dart it is used in there.

**Comment by listepo** [comment]
@ADLsourceCode => [AnimatedIcon (Flutter Widget of the Week) ](https://www.youtube.com/watch?v=pJcbh8pbvJs)

**Comment by shihaohong** [comment]
Hi @ADLsourceCode, the Flutter Widget of the Week video hasn't made it into the stable documentation yet, but is already available in the [master branch documentation](https://master-api.flutter.dev/flutter/material/AnimatedIcon-class.html). It should work for iOS. I'll close this issue out for now.
