### ISSUE TITLE
Your Xcode (1) is too outdated & Your Command Line Tools are too outdated

### ISSUE THREAD

**Issue by KARIMSUNEEL** [flutter/flutter#34912]
I have installed latest version of X code from app store (Xcode 10.2) but I am still getting the below error 

Suneels-MacBook-Pro:~ suneel$ brew install --HEAD usbmuxd
Error: Your Xcode (1) is too outdated.
Please update to Xcode 8.2 (or delete it).
Xcode can be updated from
  https://developer.apple.com/xcode/downloads/

Error: Your Command Line Tools are too outdated.
Update them from Software Update in the App Store.

also i have attached the screen shot flutter doctor 
<img width="907" alt="Screen Shot 2019-06-22 at 9 40 55 AM" src="https://user-images.githubusercontent.com/25110434/59961054-fe7a1480-94d1-11e9-8b0e-b46415367cf4.png">

**Comment by kangwang1988** [comment]
@KARIMSUNEEL 
Paste result for `xcode-select -p` please.

**Comment by KARIMSUNEEL** [comment]
Hi, I have the below result.

Last login: Sat Jun 22 19:38:49 on ttys000
(base) Suneels-MBP:~ suneel$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
(base) Suneels-MBP:~ suneel$

**Comment by KARIMSUNEEL** [comment]
Hello,

Can you please update me what to do to solve this problem.

**Comment by jmagman** [comment]
What's the output of `xcodebuild -version`?
This isn't a flutter problem, you're having a problem with Xcode/usbmuxd.

**Comment by KARIMSUNEEL** [comment]
Hi,

Do you what needs to be done to solve the problem. Below is the Xcode build version

(base) Suneels-MacBook-Pro:~ suneel$ xcodebuild -version
Xcode 10.2.1
Build version 10E1001
(base) Suneels-MacBook-Pro:~ suneel$

**Comment by BondarenkoStas** [comment]
@KARIMSUNEEL did you manage to fix it?

**Comment by KARIMSUNEEL** [comment]
Yes, with the latest release of fluter version. I am able to fix and to start with flutter. Thanks

**Comment by KARIMSUNEEL** [comment]
it's fine now
