### ISSUE TITLE
InAppPurchaseConnection.instance.isAvailable() hangs

### ISSUE THREAD

**Issue by panthe** [flutter/flutter#34917]
Hi,
I'm trying to migrate from flutter_inapp_purchase 0.9.2 to in_app_purchase 0.2.0.
For now I'm simply try to adapt the example show in in_app_purchase for show the list of products that I've in my app, but InAppPurchaseConnection.instance.isAvailable() hangs if I  post a valid sku in my list of products.
If I use only the skus showed in the example the InAppPurchaseConnection.instance.isAvailable() works.
Someone have any idea regarding my issue?

**Comment by vagrantrobbie** [comment]
Probably need a minimal example here.

I assume you have set the workspace environment up as your own app and are not using the example?

**Comment by csells** [comment]
@panthe can we get a repro project?

**Comment by panthe** [comment]
Sorry, I use another plugin now.
I think that I don't have anymore that code, but was the same of the example.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
