### ISSUE TITLE
how to connect app to a local database and retrieve data to make a dynamic view?

### ISSUE THREAD

**Issue by hamzam999** [flutter/flutter#34911]
I am making an app for an existing website, I have a login page which has different users like admin, faculty, etc. How can I create a dynamic view which will work for every user?

**Comment by hamzam999** [comment]
I am making an app for an existing website, I have a login page which has different users like admin, faculty, etc. How can I create a dynamic view which will work for every user?

**Comment by kangwang1988** [comment]
It would be better to ask on StackOverflow and only create an issue if it turns out to be a bug or a missing feature that prevents you from doing what you want.
