### ISSUE TITLE
Timestamp class (cloud_firestore package) miscalculates microseconds and milliseconds

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#34929]
To test the `Timestamp` class in "Timestamp.dart" file, try this:

    int _kEndOfTime = 253402300800;
    var maxTimestamp = Timestamp(_kEndOfTime - 1, _kBillion - 1);
    Timestamp.fromMicrosecondsSinceEpoch(maxTimestamp.microsecondsSinceEpoch)

You get this error:

    Invalid argument(s): Timestamp seconds out of range: 253402300800

The problem is the use of double (floating point) in calculations, which obviously results in rounding mistakes. Please note, this won't throw errors when the date is far from the Timestamp range limits, but will still miscalculate the number of microseconds! So this must be fixed as soon as possible.

I believe the code should be changed into this:

    factory Timestamp.fromMillisecondsSinceEpoch(int milliseconds) {
      final int seconds = (milliseconds ~/ _kThousand);
      final int nanoseconds = (milliseconds - seconds * _kThousand) * _kMillion;
      return Timestamp(seconds, nanoseconds);
    }
  
    factory Timestamp.fromMicrosecondsSinceEpoch(int microseconds) {
      final int seconds = (microseconds ~/ _kMillion);
      final int nanoseconds = (microseconds - seconds * _kMillion) * _kThousand;
      return Timestamp(seconds, nanoseconds);
    }
  
    int get millisecondsSinceEpoch => (seconds * _kThousand + nanoseconds ~/ _kMillion);
  
    int get microsecondsSinceEpoch => (seconds * _kMillion + nanoseconds ~/ _kThousand);

**Comment by marcglasberg** [comment]
@Piinks Hello Kate, is there any way this bug can get some label that gives it more priority? It's creating all sorts of problems for us, and it's a security hazard. It's more serious than it seems at first look. And it's an easy fix.

**Comment by kroikie** [comment]
@marcglasberg

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1222. Any further collaboration will be done there.
