### ISSUE TITLE
Hot reload message formatted badly on Windows

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#34937]
The hot reload message isn't formatted correctly on Windows -- see the missing Unicode characters in the image below, using the standard command prompt:
![image](https://user-images.githubusercontent.com/2319867/59969813-e1face00-950b-11e9-8ccc-c229ed14ea62.png)

FWIW, this displays correctly on the new Windows terminal, but that's not released yet:
![image](https://user-images.githubusercontent.com/2319867/59969830-62b9ca00-950c-11e9-91dc-d720f00877f3.png)

`flutter doctor`:
```
C:\git\dadjokes>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.7.9-pre.3, on Microsoft Windows [Version 10.0.18362.175], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.1.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.35.1)
[√] Connected device (4 available)

• No issues found!
```

**Comment by Hixie** [comment]
This is a bug in Windows itself, not much we can do (I mean, we could just not attempt to show the flames, but it's not possible for us to detect which console we're on, so it would be bad for users on the newer terminals).
