### ISSUE TITLE
Firebase remote config dep resolution error 16.03 vs 16.1

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#34935]
Followed instructions with https://pub.dev/packages/firebase_remote_config#-readme-tab- and got an error 
> Android dependency 'com.google.firebase:firebase-common' has different version for the compile (16.0.3) and runtime (16.1.0) classpath. You should manually set the same version via DependencyResolution

(I also set min API to 21)
flutter doctor
/Users/neil/flutter/flutter/bin/flutter doctor --verbose
```
[✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Mac OS X 10.13.6 17G6030, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/neil/flutter/flutter
    • Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/neil/Library/Android/sdk
    • Android NDK at /Users/neil/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio 3.4 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3


[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio 3.3 Preview.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

```

**Comment by neiljaywarner** [comment]
FWIW, it does resolve it to do the below but a link or better documentation might help someone besides me, or better yet, getting them to not conflict in the first place..
```
configurations.all {
    resolutionStrategy {
        force 'com.google.firebase:firebase-common:16.1.0'
    }
}
// ADD THIS AT THE BOTTOM
apply plugin: 'com.google.gms.google-services'
```

**Comment by swatantra109** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForDebug'.
> tried to access method com.google.common.io.Files.fileTreeTraverser()Lcom/google/common/collect/TreeTraverser; from class com.android.utils.FileUtils

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by BondarenkoStas** [comment]
@neiljaywarner Did you manage to solve the issue? Please paste you build.gradle.

**Comment by neiljaywarner** [comment]
Yes I figured it out
..
https://github.com/flutter/flutter/issues/34935#issuecomment-504700272

Sorry.. From my phone now..I had previous Gradle knowledge but someone not used to Gradle would be confused

**Comment by jgjurrius** [comment]
change: com.android.tools.build:gradle
dependencies {
  classpath 'com.android.tools.build:gradle:3.3.0'
  ...
This worked for me. I was using an older gradle version

**Comment by DgamonP** [comment]
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForDebug'.
> > tried to access method com.google.common.io.Files.fileTreeTraverser()Lcom/google/common/collect/TreeTraverser; from class com.android.utils.FileUtils
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 8s
> Finished with error: Gradle task assembleDebug failed with exit code 1
> ```

could someone solve this error?
