### ISSUE TITLE
resizeToAvoidBottomInset doesn't work in Cupertino

### ISSUE THREAD

**Issue by namiwang** [flutter/flutter#34946]
# repro

```
import 'package:flutter/cupertino.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Dem9',
      home: CupertinoPageScaffold(
        child: SafeArea(
          child: Center(
            child: CupertinoTextField()
          ),
        )
      )
    );
  }
}
```

# what happened

![flutter_ios_keyboard_bug](https://user-images.githubusercontent.com/1160688/59973205-ed62fd80-95ce-11e9-88c4-eb3165b3438d.gif)

# what's not expected

- the widget in `Center` changed position but is still not being centered.

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
Do you expect the field to stay in the same position?  That's what I see happening on a physical iPhone7.  My simulator is not working for the moment unfortunately.

Keyboard closed                                             | Keyboard open
:-------------------------:|:-------------------------:
<img width="200" src="https://user-images.githubusercontent.com/389558/60041825-205dcd80-9671-11e9-80d6-358d6b20906c.png" />  |  <img width="200" src="https://user-images.githubusercontent.com/389558/60041826-205dcd80-9671-11e9-814e-ddbdd5b5308c.png" />

**Comment by namiwang** [comment]
Hi @justinmc, Thanks for testing this,

Correct me if I'm wrong, but I'm expecting the widget to be in the center of the remaining (screen minus the keyboard) space.

**Comment by justinmc** [comment]
I think you've found a bug.  This centering depends on the `resizeToAvoidBottomInset` parameter, but it seems to not work on Cupertino if I'm understanding correctly.

### Cupertino

```dart
import 'package:flutter/cupertino.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'asdf',
      home: CupertinoPageScaffold(
        resizeToAvoidBottomInset: true,
        child: Center(
          child: CupertinoTextField(),
        ),
      ),
    );
  }
}
```
<img width="200" src="https://user-images.githubusercontent.com/389558/60825435-8a41a100-a160-11e9-8c13-e5b70ee49c03.png" />

### Material

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'asdf',
      home: Scaffold(
        resizeToAvoidBottomInset: true,
        body: Center(
          child: TextField(),
        ),
      ),
      ),
    );
  }
}
```

<img width="200" src="https://user-images.githubusercontent.com/389558/60825543-c412a780-a160-11e9-92fd-f4fce712d5bf.png" />

**Comment by justinmc** [comment]
My fix for this was just merged.  Right now you can get it if you're on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels), or a version greater than 1.8.4 whenever it's released.
