### ISSUE TITLE
FutureBuilder rebuilds unnecessarily when navigate between screens.

### ISSUE THREAD

**Issue by quangson91** [flutter/flutter#34947]
## Steps to Reproduce

1. Run bellow code.
2. Just moving between two screens.
3. After navigate -> the futurebuilder is recalled.

Notes:
I already checked in other issues but seems it doesn't work.
```
fakeFuture = getData();
```

Demo
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  static Future<String> getData() async {
    Future.delayed(Duration(seconds: 2));
    return "hello";
  }

  Future<String> fakeFuture;

  @override
  void initState() {
    super.initState();
    fakeFuture = getData();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: FutureBuilder<String>(
        future: fakeFuture,
        builder: (context, snapshot) {
          print("Future builder rebuild - snapshot: ${snapshot.data}");
          if (snapshot.data != null) {
            return HomeScreen();
          } else {
            return LoginScreen();
          }
        },
      ),
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Container(
        child: Column(
          children: <Widget>[
            Text("Home Screen"),
            FloatingActionButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => DetailScreen()),
                );
              },
              child: Text("Open Detail"),
            )
          ],
        ),
      );
}

class DetailScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Container(child: Text("Detail Screen"));
}

class LoginScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Container(child: Text("Login Screen"));
}

```
## Logs

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/uos/Software/flutter
    • Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/uos/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ ideviceinstaller is not installed; this is used to discover connected iOS devices.
      To install with Brew, run:
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • SM G925F • 1215fc7c520f2b05 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 2 categories.
```

**Comment by bhanuka96** [comment]
> ## Steps to Reproduce
> 1. Run bellow code.
> 2. Just moving between two screens.
> 3. After navigate -> the futurebuilder is recalled.
> 
> Notes:
> I already checked in other issues but seems it doesn't work.
> 
> ```
> fakeFuture = getData();
> ```
> 
> Demo
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatefulWidget {
>   @override
>   _MyAppState createState() => _MyAppState();
> }
> 
> class _MyAppState extends State<MyApp> {
>   static Future<String> getData() async {
>     Future.delayed(Duration(seconds: 2));
>     return "hello";
>   }
> 
>   Future<String> fakeFuture;
> 
>   @override
>   void initState() {
>     super.initState();
>     fakeFuture = getData();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: FutureBuilder<String>(
>         future: fakeFuture,
>         builder: (context, snapshot) {
>           print("Future builder rebuild - snapshot: ${snapshot.data}");
>           if (snapshot.data != null) {
>             return HomeScreen();
>           } else {
>             return LoginScreen();
>           }
>         },
>       ),
>     );
>   }
> }
> 
> class HomeScreen extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) => Container(
>         child: Column(
>           children: <Widget>[
>             Text("Home Screen"),
>             FloatingActionButton(
>               onPressed: () {
>                 Navigator.push(
>                   context,
>                   MaterialPageRoute(builder: (context) => DetailScreen()),
>                 );
>               },
>               child: Text("Open Detail"),
>             )
>           ],
>         ),
>       );
> }
> 
> class DetailScreen extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) => Container(child: Text("Detail Screen"));
> }
> 
> class LoginScreen extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) => Container(child: Text("Login Screen"));
> }
> ```
> 
> ## Logs
> ```
> [✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
>     • Flutter version 1.5.4-hotfix.2 at /Users/uos/Software/flutter
>     • Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
>     • Engine revision 52c7a1e849
>     • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
> 
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/uos/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> 
> [!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.2.1, Build version 10E1001
>     ✗ ideviceinstaller is not installed; this is used to discover connected iOS devices.
>       To install with Brew, run:
>         brew install --HEAD usbmuxd
>         brew link usbmuxd
>         brew install --HEAD libimobiledevice
>         brew install ideviceinstaller
>     ✗ ios-deploy not installed. To install:
>         brew install ios-deploy
>     ✗ CocoaPods installed but not initialized.
>         CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
>         Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
>         For more info, see https://flutter.dev/platform-plugins
>       To initialize CocoaPods, run:
>         pod setup
>       once to finalize CocoaPods' installation.
> 
> [✓] Android Studio (version 3.4)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 36.0.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
>     • IntelliJ at /Applications/IntelliJ IDEA.app
>     • Flutter plugin version 36.1.4
>     • Dart plugin version 191.7830
> 
> [✓] VS Code (version 1.35.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.1.0
> 
> [✓] Connected device (1 available)
>     • SM G925F • 1215fc7c520f2b05 • android-arm64 • Android 7.0 (API 24)
> 
> ! Doctor found issues in 2 categories.
> ```

do you find any solution?

**Comment by geek-sajjad** [comment]
I have the same problem.

**Comment by alexrindone** [comment]
I have this problem to...anyone?

**Comment by RyosukeOK** [comment]
import 'package:async/async.dart';
And use AsyncMemoizer class.

👉https://medium.com/saugo360/flutter-my-futurebuilder-keeps-firing-6e774830bc2

**Comment by someoneNameGrey** [comment]
[This solution in StackOverflow](https://stackoverflow.com/a/51225879/5033470) solved my situation.
Hope it helps.

**Comment by TahaTesser** [comment]
Hi @quangson91  @geek-sajjad  @alexrindone 

Does these solutions solve your problem? [solution comment](https://github.com/flutter/flutter/issues/34947#issuecomment-576622424) [solution comment](https://github.com/flutter/flutter/issues/34947#issuecomment-588328470)

Thank you

**Comment by quangson91** [comment]
yes, it solved my problem.
I will close this issue.

Thank all you guys!
