### ISSUE TITLE
flutter build appbundle command

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter#34950]
[flutter_01.log](https://github.com/flutter/flutter/files/3317804/flutter_01.log)

**Comment by kangwang1988** [comment]
FileSystemException: FileSystemException: Cannot copy file to 'C:\Users\bened\Desktop\flutter_appkkk\ppp\build\app\outputs\bundle\app.aab', path = 'C:\Users\bened\Desktop\flutter_appkkk\ppp\build\app\outputs\bundle\app.aab' (OS Error: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.
, errno = 32)

Is the app.aab used by another process?

You can quit all related processes and rerun the procedure to see if it helps?
@benedicte69

**Comment by benedicte69** [comment]
:) thanks, may be it was. I do not remember. I was trying to editing bundles in AS and I have been invited to send this error. So I sent it. 

Envoyé depuis Yahoo Mail pour Android 
 
  Le mar., juin 25, 2019 à 9:02, KyleWong<notifications@github.com> a écrit :   
FileSystemException: FileSystemException: Cannot copy file to 'C:\Users\bened\Desktop\flutter_appkkk\ppp\build\app\outputs\bundle\app.aab', path = 'C:\Users\bened\Desktop\flutter_appkkk\ppp\build\app\outputs\bundle\app.aab' (OS Error: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.
, errno = 32)

Is the app.aab used by another process?

You can quit all related processes and rerun the procedure to see if it helps?
@benedicte69

**Comment by BondarenkoStas** [comment]
ok, then I think it's safe to close the issue. If you disagree or encounter it again, please comment and I will re-open it, or file a new issue.
