### ISSUE TITLE
Problem with firebase cloud messaging calling onlaunch more than once

### ISSUE THREAD

**Issue by GerlanStanley** [flutter/flutter#34955]
Hello everyone, I noticed a possible problem with the firebase cloud mesaging on the flutter. I will try to detail what happened:

1 - You were finished with the app and got a notification
2 - Click on the notification, onlaunch is triggered (display an alertdialog with the notification data)

Until this moment everything normal.

3 - I leave the app in the background (do not close it) for a long time until the operating system clears the memory.
4 - I open my app through the recent apps menu. The app loads as if it had been opened at that time because the system had previously cleared the memory.
5 - The onlaunch method or onresume (not sure which one was executed) is called again and the alertdialog with the notification data is displayed again.

This second call I think should not happen because I had already seen the content of the notification previously.

I have not yet tested if the onlaunch / onresume method is going to run every time I let the operating system clear the memory (without terminating the app)

**Comment by pyetti** [comment]
I'm seeing the same kind of issue. onLaunch is running repeatedly, event if the app was never terminated.

**Comment by kroikie** [comment]
@GerlanStanley

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1057. Any further collaboration will be done there.
