### ISSUE TITLE
Can not install usbmuxd

### ISSUE THREAD

**Issue by tliwyl** [flutter/flutter#34957]
litaodeMacBook-Pro:~ litao$ brew install --HEAD usbmuxd
==> Cloning https://git.sukimashita.com/libusbmuxd.g
Updating /Users/litao/Library/Caches/Homebrew/usbmuxd--git
==> Checking out branch master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
HEAD is now at affc9af Convert README to markdown and update links
==> ./autogen.sh
Last 15 lines from /Users/litao/Library/Logs/Homebrew/usbmuxd/01.autogen.sh:
2019-06-23 23:49:34 +0800

./autogen.sh

READ THIS: https://docs.brew.sh/Troubleshooting

**Comment by kangwang1988** [comment]
Duple of https://github.com/flutter/flutter/issues/34797
