### ISSUE TITLE
Should make TextSpan.height clearer

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3495]
Right now it's not super clear what our inline box model is.

From an e-mail to flutter-dev:

> "height" does two things depending on where you put it, which is why we haven't called it "lineHeight". If you put it on the style at the root of your TextSpan widget (or in a DefaultTextStyle or whatever), then it sets the line height. If you set it on a TextSpan nested inside another, it sets the height of that textspan, which influences the line height but doesn't directly set it (the line height will be the total extent from the highest inner text span to the lowest inner text span).

**Comment by markusaksli-nc** [comment]
Closing as the property in question no longer is a part of TextSpan.
