### ISSUE TITLE
Remove default paddings and margins from material and Cupertino Widgets. Or make it customizable

### ISSUE THREAD

**Issue by Renesanse** [flutter/flutter#34956]
Well, Card has a margin parameter in the constructor, what about buttons? Default Paddings and margins break my design. I know about Material Widget, but I want to write less code as Possible.

**Comment by josmilan** [comment]
Any resolution for this question?

**Comment by mgazisalik** [comment]
I am having the same issue. Please reopen this issue.

**Comment by DrokoDomi** [comment]
Same problem here. Was it resolved yet?
