### ISSUE TITLE
i have date format issue in flutter

### ISSUE THREAD

**Issue by parth22** [flutter/flutter#34969]
in formatted date i got for example 24-00-2019 month value is 00.
![image](https://user-images.githubusercontent.com/13308845/59995851-3621c180-9676-11e9-8856-13f8f56b18c5.png)

**Comment by miDeb** [comment]
"mm" stand for minutes. For months use "MM".

**Comment by parth22** [comment]
thanks

**Comment by LongCatIsLooong** [comment]
@miDeb thank you for helping out! Closing.
