### ISSUE TITLE
[web]: <webdev could not run for this project>

### ISSUE THREAD

**Issue by nxSin** [flutter/flutter#34966]
I run  ```flutter upgrade```,```flutter pub global activate webdev```.then,I can't run web project and terminal print :

```
Could not find a file named "pubspec.yaml" in "/Users/xxxx/.pub-cache/git/flutter_web-1ed4317aa91038ba99531037ce00c04672c4bee1/packages/flutter_web_ui"
```

My flutter version:

```
flutter --version
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (8 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```

webdev version:

```
webdev --version
2.1.0
```

**Comment by furkansarihan** [comment]
I am also having some issues with resolving flutter_web in pubspec.yaml.

Can you locate flutter_web and flutter_web_ui in any package folder?

My "flutter pub get" for hello_world project getting this error.

`Because flutter_web.examples.hello_world depends on flutter_web any which doesn't exist (could not find package flutter_web at https://pub.dartlang.org), version solving failed.`

I also tried it stable and dev channel.

**Comment by nxSin** [comment]
then,I delete flutter_web dir 

```
rm -rf /Users/xxxx/.pub-cache/git/flutter_web-1ed4317aa91038ba99531037ce00c04672c4bee1/packages/flutter_web_ui"
```

and then change project pubspec.yaml,

```
build_daemon: ^1.0.0
```

to

```
build_daemon: ^1.1.0
```

and pub get ..

And then , run project success , but always show Launching:

![image](https://user-images.githubusercontent.com/14179843/60023589-afe29b00-96c8-11e9-8a1b-ee0bba1de28e.png)

browser isn't show content:

![image](https://user-images.githubusercontent.com/14179843/60023762-0c45ba80-96c9-11e9-9755-db3e6b22b476.png)

**Comment by nxSin** [comment]
Use command ```webdev serve``` to Run Project

![image](https://user-images.githubusercontent.com/14179843/60231517-0f5cc880-98cc-11e9-8c13-b4a5dcfc9027.png)

But, it Seems blocked , the browser didn't open.

**Comment by nxSin** [comment]
when I run ```webdev build``` ,console print 

```
[WARNING]build_web_compilers:entrypoint on web/main.dart: Skipping compiling flutter_web_demo|web/main.dart with dart2js because some of its
transitive libraries have sdk dependencies that not supported on this platform:

dio|lib/src/dio.dart
dio|lib/src/transformer.dart
dio|lib/src/interceptors/cookie_mgr.dart
dio|lib/src/response.dart
dio|lib/src/dio_http_headers.dart
dio|lib/src/upload_file_info.dart
dio|lib/src/options.dart
dio|lib/src/form_data.dart
dio|lib/src/adapter.dart
cookie_jar|lib/src/persist_cookie_jar.dart
cookie_jar|lib/src/default_cookie_jar.dart
cookie_jar|lib/src/serializable_cookie.dart
cookie_jar|lib/src/cookie_jar.dart
```

then I deletge ``1dio``` code，

```
import 'package:flutter_web/material.dart';
// import 'package:dio/dio.dart';
```

the project can run properly.this issue resolved.
