### ISSUE TITLE
can not install  usbmuxd width parameter '--HEAD'

### ISSUE THREAD

**Issue by tliwyl** [flutter/flutter#34974]
- I'm having problems installing and configuring flutter
- On mac OS Mojave 10.14.5
- Xcode 10.2.1

I excute ：flutter doctor
########
litaodeMacBook-Pro:Cellar litao$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.4)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
litaodeMacBook-Pro:Cellar litao$
########

then 
#######
litaodeMacBook-Pro:~ litao$ brew install --HEAD usbmuxd
==> Cloning https://git.sukimashita.com/libusbmuxd.git
Updating /Users/litao/Library/Caches/Homebrew/usbmuxd--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at affc9af Convert README to markdown and update links
==> ./autogen.sh
Last 15 lines from /Users/litao/Library/Logs/Homebrew/usbmuxd/01.autogen.sh:
2019-06-24 14:59:29 +0800

./autogen.sh

READ THIS: https://docs.brew.sh/Troubleshooting

########
I have try excute 'brew update;brew uninstall --ignore-dependencies libimobiledevice;brew uninstall --ignore-dependencies usbmuxd;brew install --HEAD usbmuxd;brew unlink usbmuxd;brew link usbmuxd;brew install --HEAD libimobiledevice;brew install ideviceinstaller',but can not resolve the problem

**Comment by christopherfujino** [comment]
Hi @tliwyl, thanks for opening this issue! Can you post your `flutter doctor -v` output after the `brew install --HEAD usbmuxd` invocation? Also, can you also paste the output of `ls $(brew --prefix usbmuxd)` (it should have the binary executable `iproxy`)?

**Comment by tliwyl** [comment]
I have resolve the problem by copy the  libimobiledevice folder and usbmuxd folder from anthor computer that has installed the --HEAD versions.But I still can not install the --HEAD version width brew. I can install libimobiledevice(usbmuxd ) without parameter '--HAED'.

**Comment by christopherfujino** [comment]
This has been fixed upstream in usbmuxd. To fix a broken version: `brew upgrade --fetch-HEAD usbmuxd`. Closing.
