### ISSUE TITLE
feature request for more border styles

### ISSUE THREAD

**Issue by namiwang** [flutter/flutter#34977]
`border-style` in css got options like `inset` which is not possible to simulate with combinations of `BorderSide`, thus this request.

ref: https://developer.mozilla.org/en-US/docs/Web/CSS/border-style

**Comment by jonahwilliams** [comment]
I think the spirt of this issue is captured in https://github.com/flutter/flutter/issues/23801? I think it would be more helpful to comment there on what particular kinds of borders would be useful to you

**Comment by BondarenkoStas** [comment]
@namiwang Can you please provide more details as asked above?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
