### ISSUE TITLE
ListView shows a blank line in IOS(iphone xs)

### ISSUE THREAD

**Issue by chendanping** [flutter/flutter#34975]
It'e will have a blank line in IOS when i use the ListView widget, but it won't happen in Android.
The red box in the picture below is that blank line, anyone knows how to solve it? ths~
![image](https://user-images.githubusercontent.com/5902039/60001691-9118e000-9699-11e9-9853-7e999d5d1e9d.png)

**Comment by shihaohong** [comment]
Hi @chendanping, could you please share minimal runnable sample code with the issue? Thank you!

**Comment by chendanping** [comment]
> Hi @chendanping, could you please share minimal runnable sample code with the issue? Thank you!

Hi, the following is the code:
ListView.builder(
            shrinkWrap: true,
            itemCount: itemList.length,
            physics: NeverScrollableScrollPhysics(),
            itemBuilder: (BuildContext context, int index) {
              return SafeArea(
                child: Column(
                  children: <Widget>[
                    Container(
                      padding: EdgeInsets.all(17.0),
                      child: Flex(
                        mainAxisSize: MainAxisSize.max,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        direction: Axis.horizontal,
                        children: <Widget>[
                          Flexible(
                            fit: FlexFit.tight,
                            child: Text(
                              itemList[index].itemKey,
                              style: TextStyle(
                                color: COLOR_GRAY_TEXT,
                              ),
                            ),
                          ),
                          Flexible(
                            fit: FlexFit.loose,
                            child: Text(
                              itemList[index].itemValue,
                              textAlign: TextAlign.right,
                            ),
                          )
                        ],
                      ),
                    ),
                    Divider(height: 1.0),
                  ],
                ),
              );
            },
          )

**Comment by alvnly** [comment]
Hi, I met the same problem. Have you solved this problem?@chendanping

**Comment by VladyslavBondarenko** [comment]
Hi @chendanping ,
Is it still an issue? 
I can't reproduce it with flutter master v1.15.20 and iOS 11.0 or 13.3 simulators

**Comment by VladyslavBondarenko** [comment]
I hope it's fixed.
Could everyone who still has this problem please file a new issue with complete minimal reproducible code sample and the output of `flutter doctor -v` please.
