### ISSUE TITLE
Flutter image problem in v1.7.4 or later. 

### ISSUE THREAD

**Issue by nimesh1997** [flutter/flutter#34971]
flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:73:44: Error: Can't find ')' to match '('.
    return new OneFrameImageStreamCompleter(                            
                                           ^                            
file:///home/lucifer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:80:5: Error: Expected a class member, but got ')'.
    );                                                                  
    ^                                                                   
file:///home/lucifer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:80:6: Error: Expected a class member, but got ';'.
    );                                                                  
     ^                                                                  
file:///home/lucifer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:176:8: Error: Operators must be declared within a class.
Try removing the operator, moving it to a class, or converting it to be a function.
  bool operator ==(dynamic other) {

**Comment by tvolkert** [comment]
Closing as a dup of #31962
