### ISSUE TITLE
Scaffold not re-render in iOS platform when app inactive transmit to active

### ISSUE THREAD

**Issue by Matrixbirds** [flutter/flutter#34979]
## Steps to Reproduce

1. create Button Group by Container Widget, these buttons has their own action to change state which is determine their color.
2. mount button group on Scaffold Widget into appBar property, and mount FlutterPlatformView on the body property.
3. run flutter app, and lock phone screen and unlock screen. i always got the previous ui rendered view that button state will not update anymore but the FlutterPlatformView will update as usual

**Comment by iapicca** [comment]
Hi @Matrixbirds 
if the issue persist with the latest stable version of flutter
could you please provide your updated `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by VladyslavBondarenko** [comment]
Closing, I hope it's fixed.
If no, could everyone who still has this problem please file a new issue with reproducing code sample, logs and the output of `flutter doctor -v` please.
