### ISSUE TITLE
How can i update ui.window.devicePixelRatio on runtime?

### ISSUE THREAD

**Issue by zhang6464** [flutter/flutter#34987]
I have tried to extends `Window` class, but it is a singleton class, i got an error when trying to extend it:`The superclass 'Window' doesn't have a zero argument constructor.
Try declaring a zero argument constructor in 'Window', or declaring a constructor in CustomWindow that explicitly invokes a constructor in 'Window'.dart(no_default_super_constructor_implicit)`
and I also tried to custom a window class just by copying all the code and modify the `devicePixelRatio` property related codes, while `Window` class is in the sdk, and `native` keyword makes that impossible...
so I need some help or advice about how to update ui.window.devicePixelRatio property through application code...

**Comment by jonahwilliams** [comment]
You cannot override window, but you can wrap your application in a [`MediaQuery`](https://api.flutter.dev/flutter/widgets/MediaQuery-class.html)  that overrides the devicePixelRatio.
