### ISSUE TITLE
Are we leaking Paragraphs?

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#3498]
Although I think the answer is no, here's what led me to the question.

Using Observatory I looked at the "Persistent Handles" page while running the Gallery demo:
- showing the home screen: 42 Paragraphs
- expanded all menus: 79 Paragraphs
- scrolling the home screen for a while: 81 Paragraphs
- launching each demo in turn: 1352 Paragraphs

The heap metrics page says that only 44 Paragraphs are "strongly reachable" and that they only cost about 32K, which sounds reasonable. Unless there's some other dire implication here, I'm not sure there's any problem at all.

**Comment by eseidelGoogle** [comment]
Paragraphs hold onto big Engine objects.  I suspect we're not correctly telling Dart how much those wrappers cost from a c++ perspective. :)

https://github.com/flutter/engine/blob/master/sky/engine/core/text/Paragraph.h#L69

**Comment by eseidelGoogle** [comment]
Leaks turn into crashes, so if true this would block folks trying to ship.

**Comment by Hixie** [comment]
Closing this. If we are leaking things, we will find out when we look at profiles and so forth.
