### ISSUE TITLE
[camera] pausePreview and resumePreview

### ISSUE THREAD

**Issue by thaitanloi365** [flutter/flutter#34997]
How to pause preview and resume preview. I need to pause review when captured and resume preview when user retake. 

Thanks.

**Comment by tonisostrat** [comment]
[Here's](https://flutter.dev/docs/cookbook/plugins/picture-using-camera#6-display-the-picture-with-an-image-widget) a simple guide on how to show a preview of the captured image. After the user is done just replace the `Image` with the live `CameraPreview` widget and you're done.

**Comment by kangwang1988** [comment]
@thaitanloi365 
Is it a issue related to camera plugin: https://github.com/flutter/plugins/tree/master/packages/camera
?

**Comment by thaitanloi365** [comment]
> [Here's](https://flutter.dev/docs/cookbook/plugins/picture-using-camera#6-display-the-picture-with-an-image-widget) a simple guide on how to show a preview of the captured image. After the user is done just replace the `Image` with the live `CameraPreview` widget and you're done.

Yes, but the problem is preview image take 1-2 seconds to load with high resolution, so I would like to pause camera and show 2 options cancel/retake.

**Comment by thaitanloi365** [comment]
> @thaitanloi365
> Is it a issue related to camera plugin: https://github.com/flutter/plugins/tree/master/packages/camera
> ?

Yes, exactly. Please help. 

Thanks

**Comment by parnurzeal** [comment]
> Yes, but the problem is preview image take 1-2 seconds to load with high resolution, so I would like to pause camera and show 2 options cancel/retake.
I agreed with this point. There are many use-cases that we want to pause CameraPreview and not taking any photo as well.

**Comment by mvanbeusekom** [comment]
Closing this issue as this functionality was added in version 0.9.2 (PR: flutter/plugins#4258)
