### ISSUE TITLE
[plugins] Document min supported Android version

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#34999]
Flutter supports API 16 and above.

Our plugins however are a mixed bag. Some support 21 and above, some all the way down to 16. Some (like Camera) seem to support 16 but has a runtime check to not do anything if API <= 21.

I propose that:
- We should make an effort to support API 16 and above since that is what the framework supports.
- If it is not possible, we should document the min API support and why it is not feasible to support lower APIs.

@collinjackson FYI

**Comment by blasten** [comment]
Camera already sets `minSdkVersion` https://github.com/flutter/plugins/blob/e55659835427fdc2b3c838548ce7e49267f100fd/packages/camera/camera/android/build.gradle#L34

Other plugins like WebView also set `minSdkVersion`.

The Flutter tool also guides users toward bumping the `minSdkVersion` if a plugin has a higher `minSdkVersion`.

If there are other cases, we can file new issues and include the specific plugin label.
