### ISSUE TITLE
the issue of using Image widget.

### ISSUE THREAD

**Issue by mrkizy** [flutter/flutter#34994]
When I use Image widget, the screen show the fllowing issue:
![IMG_4681](https://user-images.githubusercontent.com/7277246/60025130-9a22a500-96cb-11e9-8ec0-d594ffa3a9ff.PNG)

**Comment by mrkizy** [comment]
![IMG_4681](https://user-images.githubusercontent.com/7277246/60025279-e372f480-96cb-11e9-9fad-71310dcb79a9.PNG)

**Comment by ketanm** [comment]
@shihaohong 
Sorry, without looking at code or more information about what is going on it is hard to suggest. 

Shared image seem to indicate TextSyle related issue, specifically background color. See [TextStyle](https://api.flutter.dev/flutter/painting/TextStyle-class.html) docs.

If you do not use `Image` or whatever you did then does it render correctly? IF so then share added code that is causing rendering issue. Also shared `flutter doctor` output to give an idea about SDK etc.

Ketan

**Comment by daniilguit** [comment]
What versuib of Flutter do you use? There was bug in 1.2 that looked exactlyt like this. It was fixed, please upgrade to latested Flutter 1.5

**Comment by kf6gpe** [comment]
Closing due to @daniilguit's comment and the age of this issue.
