### ISSUE TITLE
[BUG] TabBar shows wrong TabBarView

### ISSUE THREAD

**Issue by Robouste** [flutter/flutter#35005]
I have spotted a bug with the tab bar behavior and managed to reproduce it.

Here is the git with the code: 
[https://github.com/Robouste/flutter-tab-bug](https://github.com/Robouste/flutter-tab-bug)

**Repro**
After launching the app, if you go first to Tab 3 then Tab 2, the content will show "Content 1" instead of "Content 2".

If you first go from Tab 1 to Tab 2, it works as expected.

I couldn't reproduce this on the emulator, but only on my device (didn't test it with other real device).

I did: 

```
flutter clean
flutter build apk
flutter install
```

The issue still occurs.

Device: OnePlus 6
Android Version: 9

Doctor: 

[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.557], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at C:\Users\Robin\flutter
    • Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\Developments\Tools\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\Developments\Tools\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code, 64-bit edition (version 1.35.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (1 available)
    • ONEPLUS A6003 • 7c98741 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by LongCatIsLooong** [comment]
Tested with master on a real device, as well as emulator, wasn't able to reproduce the bug. Could you switch to master and try again, see if that fixes it for you?

**Comment by Robouste** [comment]
After updating to flutter 1.7.9-pre.10, it works as expected. 

Thank you.

**Comment by LongCatIsLooong** [comment]
No problem! Glad it works for you. Closing the issue.
