### ISSUE TITLE
Outlined Input Border doesn't display correctly in flutter web

### ISSUE THREAD

**Issue by ahmedmgh67** [flutter/flutter#35002]
## Steps to Reproduce
1. Use OutlinedInputBorder() in flutter web

**Comment by shihaohong** [comment]
Hi, is this a duplicate of https://github.com/flutter/flutter/issues/32381? If so, please close this issue and add a thumbs up to that issue instead. Thank you!

**Comment by ahmedmgh67** [comment]
okay sorry i didn't find it
