### ISSUE TITLE
Compilation error in framework, bad mixin application

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#3500]
Error: 'package:flutter/src/widgets/routes.dart': error: line 283 pos 1: cannot generate an implicit mixin application constructor forwarding to a super class constructor with optional parameters; add a constructor without optional parameters to class 'TransitionRoute' that redirects to the constructor with optional parameters and invoke it via super from a constructor of the class extending the mixin application
abstract class LocalHistoryRoute<T> extends Route<T> {

(I'm trying to add Dart_CompileAll before generating a snapshot.)

**Comment by eseidelGoogle** [comment]
@Hixie

**Comment by Hixie** [comment]
We use this code regularly and the analyzer isn't complaining... I'm not sure I understand what's wrong here.

**Comment by Hixie** [comment]
The code seems fine. ModalRoute extends TransitionRoute with LocalHistoryRoute. TransitionRoute has two constructors, one with named optionals and one named one with explict arguments. ModalRoute calls the explicit constructor. This code seems to work fine, and the analyzer is ok with it. Can you elaborate on what change you would want to see?

**Comment by rmacnak-google** [comment]
@hausner @crelier

**Comment by crelier** [comment]
I do not see anything wrong with the code either. The workaround explained in the error message seems to be correctly implemented (the error location pointing to the mixin class is confusing, but this has nothing to do with the problem).

I am not sure how to reproduce this error on my machine, but here is a code snippet illustrating the restriction and its workaround:

class S {
  S({x});
  // S.workaround(x) : this(x: x);
}

class M { }

class C extends S with M {
  // C({x}) : super.workaround(x);
}

main() {
  new C();
}

You get a similar error message unless you uncomment the 2 lines implementing the workaround and then the error disappears. I have no idea why the error remains in the flutter sources.

**Comment by Hixie** [comment]
@rmacnak-google Do you still see this?

**Comment by rmacnak-google** [comment]
I see a different error now, but I don't think this is important any more.

**Comment by sethladd** [comment]
Thanks for the follow-up!
