### ISSUE TITLE
 ~500ms spent in the Flutter UI thread before rendering the first Dream frame

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#35009]
Mirror issue for [this internal bug](https://b.corp.google.com/issues/135134294). Conversation should occur there. 

cc @cbracken, to whom the issue is currently assigned.

**Comment by liyuqian** [comment]
This may be a duplicate of https://github.com/flutter/flutter/issues/19350

**Comment by Hixie** [comment]
This has been resolved.
