### ISSUE TITLE
flutter build apk - Fail on OSX Catalina

### ISSUE THREAD

**Issue by galvesribeiro** [flutter/flutter#35018]
Hello folks!

I know Catalina is a Beta OS and unsupported now, but I think having the issue open to track the problem can help others.

So, `flutter build apk` on my OSX Catalina fail with cryptic errors:

```
$ flutter build apk 
Initializing gradle...                                              3.1s
Resolving dependencies...                                           2.2s
                                                                        
Oops; flutter has exited unexpectedly.                                  
Crash report written to /Users/guto/dev/repos/Giro/TributesApp/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.        
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      14.0s
Gradle task assembleRelease failed with exit code 1
```

The log file:
[flutter_02.log](https://github.com/flutter/flutter/files/3322422/flutter_02.log)

Can anyone guess what is going on? I'm just trying to build an APK so I can install on an Android device.

Thanks!

**Comment by galvesribeiro** [comment]
More info...

If I run with `--debug`, it works... I wonder why the release build isn't working...

**Comment by kangwang1988** [comment]
Duple of https://github.com/flutter/flutter/issues/33909
Closing now.
