### ISSUE TITLE
[iOS 13] Long press and drag to select

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#35010]
In iOS 13, long pressing on editable and non-editable text starts selecting.  Dragging extends the selection.  I think this is identical to Android now, so it should be easy for Flutter to support.  Previously, long pressing and dragging on text set the cursor and showed the loupe magnifying glass.

This was shown at WWDC in [this video](https://developer.apple.com/videos/play/wwdc2019/224/) around the 30:00 mark.  I also confirmed this in the iOS 13 simulator.

![long_press](https://user-images.githubusercontent.com/389558/60037987-ec31df00-9667-11e9-9b27-121f0c939585.gif)

**Comment by justinmc** [comment]
Tapping and dragging without waiting for a long press still drags the cursor around.

**Comment by xster** [comment]
Seems like the same behavior as Android on https://github.com/flutter/flutter/issues/26394 now.

**Comment by xster** [comment]
@DanielEdrisian here's another one you could give a try. It's slightly more involved than the last one but should still be somewhat straightforward. 

We already have some infrastructure to handle various combinations of gestures in textfields. https://github.com/flutter/flutter/pull/26001 has some example of the current behavior of long-press-dragging translating to moving a collapsed cursor. It seems like the new behavior is to select the current word and then expand the selection by letters. 

Part of the plumbing goes through https://github.com/flutter/flutter/blob/9ca15d011858dbda5d4717ef2ac9a3af99e41e49/packages/flutter/lib/src/widgets/text_selection.dart#L1367 which lets widgets customize what happens on `onSingleLongTapMoveUpdate`. 

You can get some ideas for possible options such as https://github.com/flutter/flutter/blob/9ca15d011858dbda5d4717ef2ac9a3af99e41e49/packages/flutter/lib/src/material/selectable_text.dart#L75.

**Comment by xster** [comment]
I just double checked quickly but it seems unfortunately like the premise of the bug isn't correct anymore on the latest iOS version

On long-press-drag:
![Kapture 2020-12-10 at 9 45 30](https://user-images.githubusercontent.com/156888/101809490-75dba380-3acc-11eb-9562-26763e9a9f04.gif)

On double-tap-drag:
![Kapture 2020-12-10 at 9 46 15](https://user-images.githubusercontent.com/156888/101809558-8f7ceb00-3acc-11eb-9c28-a09cd2139957.gif)

It seems like the default iOS behavior was closer to our current implementation now (though the long-press-drag now shows the cursor not bound to the textfield itself like the keyboard force-touch-press-drag magnifier). Did I hold it right?

**Comment by xster** [comment]
Spoke offline. @DanielEdrisian is correct, it's different when focused vs non-focused.
