### ISSUE TITLE
Add .dart_tool to default .gitignore

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#35015]
See:
   https://github.com/dart-lang/site-www/issues/444

Dart picked this up, but it's not part of the default `.gitignore` for `flutter create`.

This means that packages that are run during development time create crud in these folders that gets checked in, for example:
https://github.com/timsneath/dadjokes/tree/763d72bf0da6fe5c37db5c9aedc7420ec92d7927/.dart_tool/pub/bin

**Comment by rashedmyt** [comment]
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/.gitignore.tmpl#L25
It is already added to the default `.gitignore` for `flutter create`

**Comment by timsneath** [comment]
Doh! Rookie mistake from an experienced PM :) thanks - I somehow missed this.
