### ISSUE TITLE
flutter build ios --release fails. 

### ISSUE THREAD

**Issue by abbasidaniyal** [flutter/flutter#35022]
App running perfectly in Simulator (debug mode) but gives the following error on release build 
```
  ld: warning: Could not find auto-linked framework 'Flutter'
    Undefined symbols for architecture armv7:
      "_FlutterMethodNotImplemented", referenced from:
          -[FlutterPickerPlugin handleMethodCall:result:] in FlutterPickerPlugin.o
      "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
          objc-class-ref in FlutterPickerPlugin.o
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Encountered error while building for device.
```

The complete error log : https://pastebin.com/rUkVS9ds

NOTE : App signing isn't a problem as the app is already on the app store. 
I have added the following plugins :
google_sign_in 4.0.2
flutter_facebook_login 2.0.1 and
razorpay_flutter 1.1.0 
Since these addition, the release mode won't build

**Comment by kangwang1988** [comment]
Check the arch info of the Flutter.framework embedded in your project using `lipo -info`.
It's expected to be armv7 & arm64 in release mode.
Besides, if you can reproduce this issue, it would be nicer if you can provide a minimal demo project which can help to reproduce it.
Result for `flutter doctor -v` is always expected to appear in the issue.

**Comment by abbasidaniyal** [comment]
`$ lipo -info flutter
Architectures in the fat file: flutter are: x86_64 armv7 arm64 `


`$ flutter doctor -v
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.4 18E227, locale en-GB)
    • Flutter version 1.6.3 at /Users/daniyalabbasi/flutter
    • Framework revision bc7bc94083 (5 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/daniyalabbasi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.2

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.`

**Comment by abbasidaniyal** [comment]
https://github.com/abbasidaniyal/Demo

I made a demo repo. You can have a look!

**Comment by kangwang1988** [comment]
@abbasidaniyal 
The demo git is unavailable now.

**Comment by abbasidaniyal** [comment]
> @abbasidaniyal
> The demo git is unavailable now.

Opened it! It's up now

**Comment by abbasidaniyal** [comment]
@kangwang1988

**Comment by sylvesterdas-tacto** [comment]
Any resolution?

**Comment by iapicca** [comment]
Hi @abbasidaniyal 
are you still experiencing this issue with the latest stable version of flutter?
If so could you please provide your updated `flutter doctor -v` 
and your `flutter run --verbose` and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you
