### ISSUE TITLE
Cannot run on Android Jelly Bean, API level 16

### ISSUE THREAD

**Issue by shafi49** [flutter/flutter#35021]
My Flutter app shows a white screen while running on an android emulator running Android Jelly Bean, API level 16.
It works with this command "flutter run --enable-software-rendering (with the help of software rendering) but hot reload doesn't work. I have to press 'r' in the console to hot reload the application.

**Comment by kangwang1988** [comment]
As https://github.com/flutter/flutter/issues/8610 is closed and this problem remains on API level 16 using the latest master.
cc @Hixie

**Comment by mesb1** [comment]
Same here.
Problem persist on 4.1.1 (lenovo p770) and 4.2 (galaxy tab 7 gt-p3100)
For the first one, app is just closing without error, on second one blank white screen.

**Comment by mesb1** [comment]
Before some updates of flutter everything works fine on this devices few weeks ago.

**Comment by mesb1** [comment]
![image](https://user-images.githubusercontent.com/11029359/61993590-be7cf300-b076-11e9-90f3-abb7644b48e5.png)

Android 4.1 emulator.

**Comment by mesb1** [comment]
Hi.

After update:
Flutter 1.7.8+hotfix.4 • channel stable

App start working fine for 4.1 and 4.2 devices :)

**Comment by TahaTesser** [comment]
Hi @shafi49 
Please check this [comment](https://github.com/flutter/flutter/issues/35021#issuecomment-518997279) solution

if you're still experiencing this problem, please create a new issue and provide the information required in the template.
Thank you
