### ISSUE TITLE
Investigate higher than normal memory usage during tool coverage tests 

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#35025]
Our coverage tests are using enough memory that they can't be run within the same test invocation on cirrus.

Memory usages seems to regularly go over 20GB according to activity monitor when running the tool tests with coverage, though this doesn't match the vmservice reporting of about 10GB of peak memory.

We'll need to do some investigation to see how big the delta is between a regular tool tests, and whether there is any low hanging fruit to reduce the memory pressure.

**Comment by zanderso** [comment]
@jonahwilliams Did you get a chance to look at this? It would be good for the team to be able to look up recent tool coverage stats even if we aren't measuring on every commit.

**Comment by jonahwilliams** [comment]
We still measure them per commit, but it is on a post-submit basis due to noise complaints:

https://codecov.io/gh/flutter/flutter

**Comment by zanderso** [comment]
Ah, okay, cool. Is it possible for a bot to comment with that link on tool PRs? @dnfield

**Comment by dnfield** [comment]
Shouldn't be that hard.  Update the logic that does labeling to add a comment if it thinks it needs the tool label

**Comment by jonahwilliams** [comment]
This was fixed by way of switching to package:test
