### ISSUE TITLE
Memory usage regression on iOS

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#35038]
Sometime between v1.0.0 and v1.2.1, we regressed on memory usage for apps that use lots of canvas drawing - e.g. the History of Everything app went from peaking around 6-700mb memory usage to peaking around 1.1 or 1.2gb memory usage.

This regression can lead to crashes on older iPhone's (e.g. 5 or 6) that only have 1gb of ram and memory limit you around 650mb for a single process.

I started bisecting this and will continue to dig in tomorrow - at this point, I suspect it may have been something in Skia.  For what it's worth, using the Metal backend uses _far_ less memory, at least according to the same readings from Xcode.

/cc @ened

**Comment by dnfield** [comment]
I have not been able to find a clear regression point around this - partly because reproducing the bug is a bit manually intensive and sensitive to how much I scroll or zoom on the app.  I suspect, however, that we won't find many single large jumps.

What I have found is that we're not responding to memory pressure events to purge Skia's caches, which should be pretty fixable.  We also arbitrarily set the cache limit to about 538mb, which is probably too much on older iPhones.

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/issues/35091

**Comment by dnfield** [comment]
As of https://github.com/flutter/engine/pull/9491 this should no tbe an issue - but can still be further improved by fixing the linked issue above.

**Comment by miguelcmedeiros** [comment]
I have this memory issue in my app. I opened an issue in Flare repo since it's tightly coupled to the usage Flare. We somehow narrowed the root-cause to Skia and Flare team even devised a workaround (set limit of Skia cache usage). 

It's great to see that a fix has landed. I'll give it a try once it lands in the framework.

**Comment by dnfield** [comment]
Setting the cache limit is probably the right way to go right now.  We should come up with a better value for this based on device metrics.
