### ISSUE TITLE
flutter doctor -v   error

### ISSUE THREAD

**Issue by djkloop** [flutter/flutter#35035]
## Steps to Reproduce

```
// error:   ERROR: Could not connect to lockdownd, error code -7
// macOS Mojave 10.14.5
// Homebrew 2.1.6
// Homebrew/homebrew-core (git revision bacd7; last commit 2019-06-25)
// Homebrew/homebrew-cask (git revision 72946; last commit 2019-06-25)
// Xcode 10.2.1
```
Trying to use a #22595 solution doesn't work.

## Logs

```
```

```
  // error log
```
![CE8F4609-FB2A-4CE8-BE42-7766777AE35D](https://user-images.githubusercontent.com/21050914/60070297-bca6d380-9748-11e9-98a6-aa8af07dc91f.png)

**Comment by kangwang1988** [comment]
@djkloop 
Is your device locked down?
You can check as below:
```shell
kylewong@KyleWongdeMacBook-Pro ~ % idevice_id -l
xxx
kylewong@KyleWongdeMacBook-Pro ~ % ideviceinfo -u xxx -k DeviceName
```

**Comment by djkloop** [comment]
@kangwang1988 
![image](https://user-images.githubusercontent.com/21050914/60102483-6067a200-9790-11e9-9b87-7d81bec9e5fd.png)

**Comment by djkloop** [comment]
@kangwang1988 
It’s my own problem, I don’t have a trusted computer... I’m sorry.
