### ISSUE TITLE
Add new API - SystemChrome.setEnabledSystemUIOverlays versus WindowManager.LayoutParams.FLAG_FULLSCREEN

### ISSUE THREAD

**Issue by adrianvintu** [flutter/flutter#35034]
Is there a way to make FULLSCREEN work **correctly**?

There are a lot of tickets closed and open that report the issue where opening the keyboard will make the app switch from fullscreen to normal mode.

From my point of view, this is unacceptable
1. it looks horrible
2.if does not even go back to normal mode on closing the keyboard
2. it is NOT fullcreen behaviour, it is a dirty ugly hack

Can you add some API that uses the real fullscreen?
getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);

I am talking about Android here, I have no idea about the behaviour on iOS.

**Comment by adrianvintu** [comment]
Related tickets
https://github.com/flutter/flutter/issues/29431
https://github.com/flutter/flutter/issues/27988
https://github.com/flutter/flutter/issues/24494
https://github.com/flutter/flutter/issues/24968
https://github.com/flutter/flutter/issues/22061
https://github.com/flutter/flutter/pull/22221

Also related
https://github.com/flutter/flutter/issues/28426

Maybe related
https://github.com/flutter/flutter/issues/20965

**Comment by adrianvintu** [comment]
I think (Flutter beginner here, 10+ years Android) there are 2 APIs:

1. IMPLEMENTED `SystemChrome.setEnabledSystemUIOverlays` - this is **not** making the app fullscreeen, but it uses graphics to draw over the status bar.
2. NOT IMPLEMENTED `getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);` One liner to actually make the app successfuly and properly fullscreen.

Can you guys implement this?

**Comment by ccp-codex** [comment]
I have to agree. I've tried every recommendation out there and at least on a phone with a notch I can't make this work, whether it's a debug run on a simulator or a release build on my device. An open ticket recognizing this problem would at least prevent us from having to discover the hard way nothing works to resolve this issue.

**Comment by NotThatBowser** [comment]
This is also an issue where a user interacts with certain notifications while the app is running. For example Twilight on android brings up a dialog to pause the colour filter. Once the user has done this the navigation bar will be visible again with solid colour blocking part of the app and won't disappear until they switch out and back into the app.

Something that sets a persistent flag or automatically checks for changes would be very useful.

**Comment by yalscript** [comment]
I've found a **temporary solution** for going back to full screen mode when the user hides the keyboard (just for people who need this functionality **until the flutter team brings us a real solution**).

`SystemChrome.setEnabledSystemUIOverlays([]);` is not working properly when the user hides the keyboard. However, we can add some listeners in order to detect when the bottom bar (or the keyboard, it doesn't matter in this particular case) is being displayed, because it will have some height. We also know that this keyboard/bottom bar height will be equal to `MediaQuery.of(context).viewInsets.bottom` 

So, thanks to diegoveloper at [https://stackoverflow.com/questions/52140698/flutter-detect-end-of-keyboard-hide-animation](url) I've made this abstract class:

```
abstract class BaseState<T extends StatefulWidget> extends State<T> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  /// This routine is invoked when the window metrics have changed. Useful for our case 
  @override
  void didChangeMetrics() {
    if (MediaQuery.of(context).viewInsets.bottom > 0) {
      SystemChrome.restoreSystemUIOverlays();
    }
  }
}
```

When creating the StatefulWidget, instead of inheriting from State<Foo>, we can inherit from this class. Also, in the main method, we must use `SystemChrome.setEnabledSystemUIOverlays([]);`

The following code is an example of an app using all these things together:
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setEnabledSystemUIOverlays([]);
  
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(title: 'Keyboard demo')
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends BaseState<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: TextFormField()
    );
  }
}
```

Finally, I want to remark that this is only a patch (not the correct solution) for the developers that are having problems with the behaviour of the relation between the keyboard and the full screen mode (as the ones that I've had).

P.S. I've tested this only on Android devices, not on iOS.

**Comment by LipeAG** [comment]
I had the same problem, I used the commands suggested above anyway, it is not 100% in sansung 9s + MediaQuery.of (context) .viewInsets.bottom show 48 no 0 in some cases, when I open a textfield and close the keyboard .

**Comment by GaryQian** [comment]
Unfortunately, there is actually not much we can do from Flutter to automatically reset the app back to fullscreen mode. This is actually a security feature that prevents malicious apps from trapping users in their app by preventing on-screen controls from appearing. Once some event triggers the exit from full screen, the app cannot be put back into fullscreen mode for a dew seconds. Apps have no way to bypass this.

We actually added https://master-api.flutter.dev/flutter/services/SystemChrome/restoreSystemUIOverlays.html `restoreSystemUIOverlays` for this very purpose. After detecting that you are ready to go back into fullscreen, you should be able to simple call the restore method to pop back into fullscreen.

The detection of whether the app is ready to be full screen again or not is up to you to develop.

**Comment by danagbemava-nc** [comment]
@adrianvintu does https://github.com/flutter/flutter/issues/35034#issuecomment-920455417 sufficiently answer your question?

**Comment by adrianvintu** [comment]
@danagbemava-nc yes, it suffices, it's not a product breaking feature for me. thank you!

**Comment by danagbemava-nc** [comment]
Based on this comment https://github.com/flutter/flutter/issues/35034#issuecomment-971527413, I feel it is safe to close this issue. 

Closing as solved.
