### ISSUE TITLE
about Using container ClickEvent

### ISSUE THREAD

**Issue by FuXinLisc** [flutter/flutter#35044]
ask：How to distinguish between click blanks and children's click events------container
this widget  container   is  really important  but  why can not  distinguish between click blanks and children's click events?

**Comment by iapicca** [comment]
Hi @FuXinLisc 
does this [code](https://dartpad.dev/064c5e2bed61f13a985dacce366eb56f) represent the issue you are describing?
Thank you

**Comment by darshankawar** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
