### ISSUE TITLE
using aar library in a flutter project

### ISSUE THREAD

**Issue by issam1975** [flutter/flutter#35072]
hey guys,

is there a way to import and use an aar library in a flutter project .

for reference i want to use the sinch.com sdk
https://www.sinch.com/docs/resources/downloads/index.html

any idea or help is welcome

apparently there is a way to import the aar library so reuse the java code in a flutter project but i am not completly sure

 
thanks

**Comment by kf6gpe** [comment]
Closing as this is a question best left to https://flutter.dev/community.
