### ISSUE TITLE
AdMob banner ads integrated into a Flutter widget tree

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#35081]
Split off https://github.com/flutter/flutter/issues/12114

Users are would like to embed a [AdMob banner ad](https://developers.google.com/admob/android/banner) as part of the Flutter widget tree (vs. the current approach taken by the firebase_admob plugin which is to overlay the banner ad on top of the Flutter UI in a pre-set position).

**Comment by matte5031** [comment]
Yes please!!

**Comment by komapeb** [comment]
I believe this affects most of the developers out there (considering native ads are limited to a set of approved publishers) and should be highest priority.

**Comment by sageata** [comment]
> I believe this affects most of the developers out there (considering native ads are limited to a set of approved publishers) and should be highest priority.

Adding to that, normally, if you arrange a call with Google Ads Team they will normally grant you access to Native Ads.

**Comment by dblokhin** [comment]
Checking in.

**Comment by ewokhias** [comment]
Is there a roadmap for this issue?

**Comment by BPHvZ** [comment]
Would this be possible using UiKitView? https://api.flutter.dev/flutter/widgets/UiKitView-class.html

**Comment by ozexpert** [comment]
any update?

**Comment by dblokhin** [comment]
I guess this hard work #36779 is related to this and #12114.

**Comment by amirh** [comment]
#36779 is to offer common framework functionality for new platforms adding platform views, unrelated to this issue.

**Comment by serendipity1004** [comment]
So this would allow banners with various sizes to be embedded using listview separator?

**Comment by kroikie** [comment]
@amirh

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1175. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by comlaterra** [comment]
I would like to point out tho, that the flutter_admob plugin is implementing at least one discouraged banner implementation by the Admob Policies. 
I believe it's implementing "Ad overlapping with app content" and, in most of the Android cases the "Ad sandwiched between app items". They can be found [here](https://support.google.com/admob/answer/6275345?hl=en).

That being said, I'm not sure what is worst, if to be in a "grey area" as mentioned above or directly implementing something that is stated as "against policy" in the Admob policies page itself 🤔

**Comment by roysprojects** [comment]
Is this ever gonna happen?

**Comment by devibrahimkarahan** [comment]
Any update ?

**Comment by MaximeDelhorme** [comment]
Any update?

**Comment by abdllahelamri1** [comment]
Any update?

**Comment by AbdullahGaber** [comment]
Any update?

**Comment by Dabhipb** [comment]
Still no updates ?

**Comment by YuriOliveiraAbel** [comment]
Any update?

**Comment by abd0ibrahim** [comment]
There is an un official plugin for it 
https://pub.dev/packages/admob_flutter

**Comment by dayron9110** [comment]
Any update?

**Comment by angel1st** [comment]
@abd0ibrahim - what makes this plugin official? I don't think it is...

**Comment by abd0ibrahim** [comment]
@angel1st I literally said that it is un official

**Comment by bparrishMines** [comment]
There is now an open beta with this feature supported: https://github.com/flutter/flutter/issues/12114#issuecomment-725731427

**Comment by Aravin** [comment]
Any update on this request?

**Comment by GeceGibi** [comment]
Any change ?

**Comment by zoeyfan** [comment]
Given Google Mobile Ads SDK is open for beta now, I think we can close this issue now!
Please check our new plugin below:
https://pub.dev/packages/google_mobile_ads
Happy coding and advertising!
