### ISSUE TITLE
Support AdMob Native Ads Advanced in overlays

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#35082]
Split off https://github.com/flutter/flutter/issues/12114

This issue tracks adding support to overlay [AdMob Native Ads Advanced](https://developers.google.com/admob/android/native/start) ads on top of the Flutter UI (similarly to how banner ads are currently overlaid: e.g it shows in a pre-set position and on top all of the Flutter UI).

While obviously being able to embed native ads is a better option(https://github.com/flutter/flutter/issues/12114), overlaying the native ad similarly to the current banner support is something reasonable to expect within a shorter timer frame.

**Comment by RaresMihalcea** [comment]
If any kind of native ads support can be achieved in a relatively short timeframe then I believe that voting for this is worthwhile.

**Comment by kroikie** [comment]
@amirh

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1174. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by bparrishMines** [comment]
As of https://github.com/FirebaseExtended/flutterfire/pull/169 and https://github.com/FirebaseExtended/flutterfire/pull/2106, this can be closed.
