### ISSUE TITLE
Persisting user on device

### ISSUE THREAD

**Issue by yieniggu** [flutter/flutter#35090]
Hello, currently I made my first flutter app so there are things still uncertain for me. One of them is if there is a way to store the user in the device or construct it from information stored there, first to be able to get a new token to send http requests to my firebase backend adn second to maintain a login session until the user hits logout.

Thanks for any answer!

**Comment by philippDerDieDas** [comment]
That's Not an issue!

You have to figure it out yourself.
You could use the shared preferences library to save the token as string.

See https://pub.dev/packages/shared_preferences

**Comment by kf6gpe** [comment]
Closing as this is a question best for https://flutter.community.
