### ISSUE TITLE
Could not find an option named "target-platform".

### ISSUE THREAD

**Issue by unreal0** [flutter/flutter#35098]
*** flutter upgrade to 1.7.9 ***
Could not find an option named "target-platform".
delete "args": ["--target-platform", "android-arm64"]

build error

**Comment by ymback** [comment]
See this https://github.com/flutter/flutter/pull/34369
And I don't think it's right to remove this. See my comment.

**Comment by BondarenkoStas** [comment]
I think it's safe to close the issue as it doesn't lead anywhere.

**Comment by PawankumarPK** [comment]
Solution is here :+1: 
https://stackoverflow.com/a/67370078/8712102
