### ISSUE TITLE
Flutter and camera rotating the image (IOS)

### ISSUE THREAD

**Issue by bw-raiizz-a** [flutter/flutter#35108]
You guys have to fix this. In IOS when you use camera to take a photo, it rotates. 
Also, if you try to use a photo from your albums, only the lower part shows. 
User has no control over placing their photos.
We decided to use Flutter for our app based on what we read but now we are in big trouble because of this issue.

**Comment by AmanaDEV** [comment]
smae problem for me in IOS

**Comment by mhd-barikhan** [comment]
Same Issue for me in IOS

**Comment by rajeshzmoke** [comment]
```
   var image = await ImagePicker.pickImage(
      source: src,
       maxHeight: 450,
       maxWidth: 450,
    );
```
adding `maxHeight` and `maxWidth` rotates the image 90 degree when using the `camera`

**Comment by BondarenkoStas** [comment]
@bw-raiizz-a Please try it using the current image_picker 0.6.1+4 https://github.com/flutter/flutter/issues/37688#issuecomment-521864600.
