### ISSUE TITLE
TextField set maxLength,  the chinese pinyin will be cutted

### ISSUE THREAD

**Issue by qq326646683** [flutter/flutter#35106]
```

Flutter 1.6.3-pre.8 • channel master • https://github.com/flutter/flutter.git
Framework • revision be2918ff30 (5 weeks ago) • 2019-05-22 18:14:01 -0700
Engine • revision 8dc3a4cde2
Tools • Dart 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)


```

```


[✓] Flutter (Channel master, v1.6.3-pre.8, on Mac OS X 10.14.3 18D42, locale
    zh-Hans-CN)
    • Flutter version 1.6.3-pre.8 at /Users/dashuaifu/dev/flutter
    • Framework revision be2918ff30 (5 weeks ago), 2019-05-22 18:14:01 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dashuaifu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_SDK_ROOT = /Users/dashuaifu/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • nell’s iPhone • 00008020-001B24283E99002E            • ios • iOS 12.2
    • iPhone 8      • 2E6C5C1A-B83B-4BB4-8AE1-030C9385A034 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

![Jun-26-2019 15-51-04](https://user-images.githubusercontent.com/15717688/60161505-4f6b6f00-982a-11e9-9894-3d372c0ff3f1.gif)

**Comment by justinmc** [comment]
Thanks for reporting this, that's a great point!

To explain what's going on for anyone looking at this issue, the field has 2 characters of space remaining, which the user wants to fill with 2 Chinese characters.  However, the user has to type 4 Latin characters "keyi" in order to produce the two Chinese characters.  Our TextField blocks the entry of the last 2 Latin characters though, so the user can't enter the final Chinese character.

**Comment by justinmc** [comment]
I think the solution here is to not count marked text in the character limit.  So while "ke" is underlined it wouldn't count towards the character limit, if it becomes 可 then it would count as one character, and only if it stops being underlined would it count as two.

**Comment by qq326646683** [comment]
@justinmc thank you for your suggestion, but I have to limit the maxlength because of demand. if I don't set the maxlength, I listen the text change then cut the content. eg: if(controller.text.length > 27) controller.text = controller.text.substring(0, 27), but the result is same as "set maxlength = 27". so I have no idea to deal with it

**Comment by justinmc** [comment]
I mean that this will require a change to the Flutter framework.  We'll probably have to change [formatEditUpdate in LengthLimitingTextInputFormatter](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/text_formatter.dart#L170) to ignore marked text.  I'm not sure if TextEditingValue knows about marked text, though.  @GaryQian do you know?  Or will this require an engine change?

**Comment by GaryQian** [comment]
The text field is based off a TextEditingController with a TextEditingValue, which in turn specifies a composing region. This region should be ignored in the length when it is still in flux.

A potential problem is how it impacts alphabetic languages where the composing region should count as final text, whereas in other languages the composing region acts as a preview or partial representation of the final text.

It also looks like this problem mainly exists on iOS which displays the composing text directly inline with the contents. On android, it shows up in the keyboard.

**Comment by GaryQian** [comment]
I did a quick attempt through modifying material/TextField.dart:566 currentLength, but that was not sufficient to fix this. LengthLimitingTextInputFormatter should support composing ranges instead of just blindly truncating and setting composing range to empty.

**Comment by GaryQian** [comment]
I will also note that this bug exists for typing long emojis. For example, the family emojis are made of <man><woman><child><child> which would count as 4 characters. If you only have 2 characters remaining, the 2 children are truncated.

**Comment by qq326646683** [comment]
@justinmc @GaryQian thank you for your reply, I found that ios natively has the same problem. the solution is:

**Comment by qq326646683** [comment]
@justinmc @GaryQian thank you for your reply, I found that ios natively has the same problem. the solution is:
```
NSString *lang = [[self.inputTextField textInputMode] primaryLanguage];
    if([lang isEqualToString:@"zh-Hans"])
    {
        UITextRange *selectedRange = [self.inputTextField markedTextRange];
        UITextPosition *position = [self.inputTextField positionFromPosition:selectedRange.start offset:0];
        if(!position)
        {
            if(content.length > maxLength)
            {
                self.inputTextField.text = [content jjSubString:maxLength];
                [JJToastMgr showToast:@"不能超过10个字"];
            }
        }
    }
    else{
        if(content.length > maxLength)
        {
            self.inputTextField.text = [content jjSubString:maxLength];
            [JJToastMgr showToast:@"不能超过10个字"];
        }
    }

```

I hope this helps you.

**Comment by GaryQian** [comment]
Thanks for the input! I will take a look if something like this can be applied in a more general way on our text handling in the iOS embedder

**Comment by morisunshine** [comment]
> @justinmc @GaryQian thank you for your reply, I found that ios natively has the same problem. the solution is:
> 
> ```
> NSString *lang = [[self.inputTextField textInputMode] primaryLanguage];
>     if([lang isEqualToString:@"zh-Hans"])
>     {
>         UITextRange *selectedRange = [self.inputTextField markedTextRange];
>         UITextPosition *position = [self.inputTextField positionFromPosition:selectedRange.start offset:0];
>         if(!position)
>         {
>             if(content.length > maxLength)
>             {
>                 self.inputTextField.text = [content jjSubString:maxLength];
>                 [JJToastMgr showToast:@"不能超过10个字"];
>             }
>         }
>     }
>     else{
>         if(content.length > maxLength)
>         {
>             self.inputTextField.text = [content jjSubString:maxLength];
>             [JJToastMgr showToast:@"不能超过10个字"];
>         }
>     }
> ```
> 
> I hope this helps you.



> @justinmc @GaryQian thank you for your reply, I found that ios natively has the same problem. the solution is:
> 
> ```
> NSString *lang = [[self.inputTextField textInputMode] primaryLanguage];
>     if([lang isEqualToString:@"zh-Hans"])
>     {
>         UITextRange *selectedRange = [self.inputTextField markedTextRange];
>         UITextPosition *position = [self.inputTextField positionFromPosition:selectedRange.start offset:0];
>         if(!position)
>         {
>             if(content.length > maxLength)
>             {
>                 self.inputTextField.text = [content jjSubString:maxLength];
>                 [JJToastMgr showToast:@"不能超过10个字"];
>             }
>         }
>     }
>     else{
>         if(content.length > maxLength)
>         {
>             self.inputTextField.text = [content jjSubString:maxLength];
>             [JJToastMgr showToast:@"不能超过10个字"];
>         }
>     }
> ```
> 
> I hope this helps you.

@qq326646683  Hello, Did you solve this problem by flutter?

**Comment by morisunshine** [comment]
@qq326646683 Hello, Did you solve this problem by flutter?

**Comment by qq326646683** [comment]
> @qq326646683 Hello, Did you solve this problem by flutter?

not yet

**Comment by buxiaojiong** [comment]
is there any progress?

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.6 19G73, locale
    en-GB)
    • Flutter version 1.20.0-7.1.pre at /Users/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (6 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            •
      iOS 13.6
    • macOS (desktop)        • macos                     • darwin-x64     •
      Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
```

</details>

**Comment by frasker** [comment]
What's the progress now

**Comment by justinmc** [comment]
No one is assigned, so no one is currently working on this and it's up for grabs if anyone wants to try fixing it.  You can also add a 👍  to the original issue description to help give us an idea of how many people are affected.

**Comment by FrunkPiano** [comment]
try my flutter textfield plugin [custom_text_field](https://github.com/FrunkPiano/CustomTextField.git)
soleve the problem
