### ISSUE TITLE
Localization - support for Central kurdish, locale 'ckb'

### ISSUE THREAD

**Issue by ibrahim1990** [flutter/flutter#35103]
Hi all,
 Iam from iraq when i use ( (Locale('ckb') Central kurdish ) in my app show me this error

- Warning: This application's locale, ckb_IQ, is not supported by all of its 
- A MaterialLocalizations delegate that supports the ckb_IQ locale was not found

is it support ( ckb ) ? or not ?

thanks,

**Comment by HansMuller** [comment]
Currently locale ckb is not supported, see https://api.flutter.dev/flutter/flutter_localizations/GlobalMaterialLocalizations-class.html

It's possible to add support for a new language, see https://flutter.dev/docs/development/accessibility-and-localization/internationalization#adding-support-for-a-new-language

**Comment by Botanium** [comment]
I will see if I can create a pull request and add CKB to the list. It might take a while.

**Comment by HansMuller** [comment]
At the moment, Google doesn't provide translations for the ckb locale and we don't have a mechanism in place for supporting user-contributed translations. The suggestion in https://github.com/flutter/flutter/issues/35103#issuecomment-505913672 was aimed at adding ckb support to you application.

**Comment by HansMuller** [comment]
I'm going to close this because, for the near term, the only way to include support for CKB is for an app to do it, per https://github.com/flutter/flutter/issues/35103#issuecomment-507734200

**Comment by mustafa96m** [comment]
Hey @ibrahim1990, I made this small package that takes care of `Locale('ckb', 'IQ')` as well as the RTL text direction. You may also fork and PR the translations!

https://pub.dev/packages/flutter_ckb_localization
