### ISSUE TITLE
TextFormField becomes unresponsive after flutter driver test is run

### ISSUE THREAD

**Issue by DK15** [flutter/flutter#35118]
While writing integration tests using Flutter Driver, I observed that if a test inputs `Email` and `Password` in `TextFormField` widget and completes remaining steps in the test and stops the application instance, next time if you try to open the target app and manually try to type something in same `Email` and `Password` fields, the fields becomes unresponsive and doesn't display any data.

## Steps to Reproduce

1. Have a login screen with `Email` and `Password` fields implemented using `TextFormField` widget with respective hint texts and a simple `RaisedButton` as login.
2. Write a flutter driver test to input `email` and `password` and then tap on `login` button to go to next screen.
3. When the flutter driver test completes successfully and stops the application instance, open the app again and try to manually input something in `email` and `password` fields and notice that no action takes place and no input is displayed.

## Logs

There are no errors or logs generated in the terminal.

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/deeptibelsare/Documents/Flutter-sdk/flutter
    • Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 2.0.0
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    • CocoaPods version 1.7.0.beta.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26)
      (emulator)

! Doctor found issues in 2 categories.
```

**Comment by nerdnmuscles** [comment]
I had that same issue few days ago for exactly the same case scenario. You can fix it by uninstall the app and running (without flutter_driver) normally.

**Comment by Hixie** [comment]
Can you attach a test case that demonstrates the issue? Without code to reproduce the problem it's hard for us to make significant progress.

**Comment by DivyanshSultania** [comment]
@DK15 Can you give the sample test code which you used to automate textFormFields testing?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
