### ISSUE TITLE
[web] Implement "shared_preferences" plugin for web

### ISSUE THREAD

**Issue by ThangLuuQuoc** [flutter/flutter#35116]
At now I can't use 'shared_preferences' plugin for flutter_web
I think it's important feature

**Comment by deckerst** [comment]
`localStorage` is already supported thanks to the `dart:html` package. Until plugins are supported by Flutter web and `localStorage` is set up as the web flavour of `shared_preferences`, you can directly work with it like so:
```
import 'dart:html';
...
Storage localStorage = window.localStorage
```

**Comment by jld3103** [comment]
#35588

**Comment by datteroandrea** [comment]
> At now I can't use 'shared_preferences' plugin for flutter_web
> I think it's important feature

Hi i want to store data to keep the user logged in my application, is this safe to use? And also how should i do this?

**Comment by timtraversy** [comment]
Flutter for web currently doesn't support importing 'dart:html' (https://github.com/flutter/flutter/issues/35588), so you have to use 'package:js' to interop with the local storage. I created a working gist that uses this approach: https://gist.github.com/timtraversy/d663ef1e37c2a8c49437c76be7062e85

**Comment by lijovijayan** [comment]
shared_preferences dart package now supports local storage for the web from version 0.5.4.7+

Similar to shared preference on Android and iOS, the following is the code snippet for local storage on web

https://stackoverflow.com/questions/56417667/how-to-save-to-web-local-storage-in-flutter-web

**Comment by lijovijayan** [comment]
shared_preferences dart package now supports local storage for the web from version 0.5.4.7+

Similar to shared preference on Android and iOS, the following is the code snippet for local storage on web

https://stackoverflow.com/questions/56417667/how-to-save-to-web-local-storage-in-flutter-web
