### ISSUE TITLE
Flutter's required types analysis lints are at odds with dart-fmt

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3511]
This causes issues for our customers submitting internal reviews having analyzer warnings from flutter which are at odds with dart-fmt style rules.

@abarth says we can control which analysis rules we "forward on" to our customers.  This seems like one we should remove for now?

@pq @Hixie

**Comment by devoncarew** [comment]
The ones customer's see are controlled here: https://github.com/flutter/engine/blob/master/sky/packages/sky_engine/lib/_embedder.yaml#L16

The ones we see from flutter analyze are controlled here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/flutter_analysis_options

**Comment by Hixie** [comment]
We should probably forward very few of the basic lints and warnings, and only forward the ones we add that are Flutter-specific (once we add some). Our intent was that our customers be able to take whatever level of strictness they want.

**Comment by pq** [comment]
I agree that this is confusing and, am with @Hixie, that we should consider dialing embedded analyses way back.

As for user control over strictness this hits a bit of a usability nerve as defining/overriding options at the package level is cumbersome at scale (see for example, https://github.com/dart-lang/sdk/issues/26154).  

An angle that may help both is explored in this [doc](https://docs.google.com/document/d/1rRlZut75Twl8hJ6529xjGRc12miHFPpQ8gr_oP6J3dc/edit?usp=sharing)  _(TL;DR: ditch magic forwarding in favor of explicit configuration via named, published rule-sets)_.  Comments welcome!

**Comment by Hixie** [comment]
@abarth fixed this with https://github.com/flutter/engine/pull/2616
