### ISSUE TITLE
ImagePicker.pickImage(...) never returns on android

### ISSUE THREAD

**Issue by juliengit2** [flutter/flutter#35123]
The plugin doesn't work anymore.

Here is what I tried:

to change the flutter channel (I tried them all) : KO
to downgrade the plugin version : KO
to change the sdk version, 27 or 28, same result : KO
to clean the project + manually erase the build folder : KO
to pull the projet : KO
to reinstall Flutter (and to delete tmp files in .pub-cache) : KO
to add in mainActivity java file the method below : KO
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
    }
and to spend a lot of time testing and looking all over: still no result, KO

Here is my conf:

![image](https://user-images.githubusercontent.com/35921399/60184944-4e860d80-9829-11e9-8f28-e6a98bf80efd.png)

Any idea???

Any help highly appreciated.

**Comment by frankxzx** [comment]
Maybe other plugin implements PluginRegistry.ActivityResultListener and override onActivityResult callback instead of ImagePicker

**Comment by collinjackson** [comment]
The image_picker example app is working for me in a simulator, so I think there's something different about your use case.

<img width="445" alt="Screen Shot 2019-07-15 at 10 18 35" src="https://user-images.githubusercontent.com/394889/61235250-ecaf1a00-a6e9-11e9-8252-71d08d6fccad.png">

**Comment by zhaochengxiang** [comment]
I have the same issue! How can you solve it?
I user photo_manager and image_picker in my project

**Comment by zhaochengxiang** [comment]
We also encountered this problem. It turned out that we had overridden onActivityResult in MainActivity without invoking super, like fredriks' comment above. Invoking super fixed this issue.

This solve my problem!!!!!

**Comment by RohanKonda** [comment]
I too am facing the same issue. No luck so far.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
Thank you
