### ISSUE TITLE
[iOS 13] Draggable Scrollbar

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#35127]
In iOS 13, it will be possible to drag the scrollbar to scroll more quickly.  This can be done either by long pressing the scrollbar or dragging in from the right at the scrollbar.

<img width="250" src="https://user-images.githubusercontent.com/389558/60194598-80c64980-97ee-11e9-95ce-4d2603010b45.gif" />

A Reddit thread with some info: https://www.reddit.com/r/iOSBeta/comments/bx8nqv/feature_the_scroll_bar_is_grabbable_system_wide/?utm_source=share&utm_medium=ios_app&utm_name=ios_share_flow_optimization&utm_term=enabled

**Comment by KagurazakaHanabi** [comment]
On real devices, the native app will have vibration feedback, but flutter does not.

**Comment by justinmc** [comment]
Thanks for pointing that out, I missed it due to using only the simulator.  I'll create a new issue and link it back here.

**Comment by justinmc** [comment]
Here's the issue: https://github.com/flutter/flutter/issues/37628

@KagurazakaHanabi Do you know what the vibration pattern is?  Would a simple `HapticFeedback.vibrate()` work?

**Comment by KagurazakaHanabi** [comment]
The vibration like `CupertinoSliverRefreshControl`, so I think maybe `HapticFeedback.mediumImpact()` can work...

**Comment by justinmc** [comment]
@KagurazakaHanabi Please let me know if this looks right to you! https://github.com/flutter/flutter/pull/37724

**Comment by KagurazakaHanabi** [comment]
prefect!
