### ISSUE TITLE
listen/send to the same isolate receive port from different classes

### ISSUE THREAD

**Issue by nsmith1024** [flutter/flutter#35122]
Hello,

In a foreground GUI Widget im communicating with a background isolate using send/receive ports. But now it seems i may have to communicate with that same isolate from another GUI foreground Widget class too. Do i create another set of send/receive ports to the same isolate, or can i listen to the same same receive port from the other class, where now both classes are listening and communicating with the same isolate.

When the isolate does a send, will both classes receive the same data? What is the proper way to do this? When the isolate does a listen, will it receive data from both classes communicating with it on the same port?

Thanks

**Comment by kf6gpe** [comment]
Please bring this up on one of the Flutter channels at http://flutter.dev/support; folks there should be able to help you. Thanks for using Flutter!
