### ISSUE TITLE
cloud_functions -  How can I configure it to call localhost

### ISSUE THREAD

**Issue by pravinarr** [flutter/flutter#35125]
How can I configure the cloud functions plugin to call functions deployed locally.

This will help us during our local development process, since we do only EOD deployment.

Thanks in advance!

**Comment by pravinarr** [comment]
@Piinks thank you for labelling. I did some more research on the plugin and found out that [useFunctionsEmulator (String origin)](https://firebase.google.com/docs/reference/android/com/google/firebase/functions/FirebaseFunctions.html#public-void-usefunctionsemulator-string-origin); feature is not included in the current plugin. I am interested in contributing to that. Can anyone guide me the steps to raise a PR and guidelines for the code ?

**Comment by audkar** [comment]
@pravinarr contribution guide is [here](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md)

**Comment by pravinarr** [comment]
thanks @audkar
