### ISSUE TITLE
Document Flutter's pipeline

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3513]
I believe we need a doc to explain flutter's pipeline:
- Build
- Layout
- Paint

Why it's written this way (faster) and how you shouldn't go backwards through the pipeline, like you might normally on the web or other layout systems.  This is a concept which is not clear to many of our users initially.

@Hixie @qchong @abarth

**Comment by abarth** [comment]
I'm giving a talk internally at Google on this topic in two weeks.  As part of that talk, I'll generate some slides that might be a good starting point for these docs.

**Comment by abarth** [comment]
Video is posted https://www.youtube.com/watch?v=UUfXWzp0-DU

**Comment by abarth** [comment]
I'm going to close this now that the video is available and classes like PIpelineOwner have reasonable docs.  Please open a more specific issue if we need more here.
