### ISSUE TITLE
cubic_bezier_perf__timeline_summary worst_frame_rasterizer_time_millis regressed

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#35142]
The regression looks similar to https://github.com/flutter/flutter/issues/34820 and it's caused by an engine roll https://github.com/flutter/flutter/commit/0f2388e54518eecbf601058fd5eb4942e6076d42 which includes the reland of the suspected Skia commit: **Reland "Prefer using GrOvalOpFactory over GrFillRRect for circles and axis-aligned circular roundrects."** (see https://github.com/flutter/flutter/issues/34820#issuecomment-504604063)

**Comment by liyuqian** [comment]
CC @brianosman @jvanverth

**Comment by liyuqian** [comment]
Fixed by reverting the skia roll.

**Comment by liyuqian** [comment]
According to our conversions in the Flutter & Skia chat room, this performance regression is actually a performance tradeoff which improves some use cases cared by Chrome. Hence we're lowering the severity of this (and future) regression caused by this Skia commit to unblock the rollers.

**Comment by liyuqian** [comment]
We've confirmed that the number of shaders being compiled went up when the suspected Skia commit landed: https://perf.skia.org/e/?begin=1561326020&end=1561412406&queries=sub_result%3Dshader_compilations&request_type=0

**Comment by liyuqian** [comment]
Reopen has the reverted commit has relanded. Will try the shader warm-up using "a rounded stroke with AA".

**Comment by chinmaygarde** [comment]
Removing the Skia tag as this seems to be WAI.

**Comment by franciscojma86** [comment]
@liyuqian This benchmark still shows regressions. If this is expected, should it be re-baselined?

**Comment by liyuqian** [comment]
I'll re-baseline as there might be a while before we get time to fix it.

**Comment by liyuqian** [comment]
Will try the general SkSL shader warm-up once https://github.com/flutter/flutter/issues/40686 is done.

**Comment by cbracken** [comment]
@liyuqian did you get a chance to try this out? Should this issue still be kept open?

**Comment by liyuqian** [comment]
@cbracken : I'll try this out once I get back to office and have access to the device.

**Comment by liyuqian** [comment]
Update: due to the current COVID-19 situation, I've brought Moto G4 and iPhone 6s home to work on this. I'm expecting to have some work/experiment done by this month, but the COVID-19 situation could change quickly to tank the work efficiency. So some delay in our work schedule might happen.

**Comment by kf6gpe** [comment]
Just following up on this, since it's the beginning of April. @liyuqian, when you get a chance, can you update status here for our readers? Thanks!

**Comment by liyuqian** [comment]
We're making progress in https://github.com/flutter/flutter/issues/53607. Should be able to finish this by the end of April.

**Comment by liyuqian** [comment]
We're close but not there yet. Extend the milestone to June.
