### ISSUE TITLE
[in_app_purchase]Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported value for standard codec'

### ISSUE THREAD

**Issue by doctorlh** [flutter/flutter#35155]
I test plugin 'in_app_purchase', app crash . 

Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13, descriptor: <private>

Unsupported value: Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_kCFStreamErrorCodeKey=-72000, _kCFStreamErrorDomainKey=10} of type NSError

*** Assertion failure in -[FlutterStandardWriter writeValue:], ../../flutter/shell/platform/darwin/ios/framework/Source/FlutterStandardCodec.mm:330

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported value for standard codec'
*** First throw call stack:
(0x185559ea4 0x184729a50 0x18546fa2c 0x185f5e1d0 0x1014d79e0 0x1014d7b14 0x1014d7b14 0x1014d7b14 0x1014d78fc 0x1014d65f8 0x1014c5fe0 0x1031dde04 0x1031db0f4 0x1031d96b0 0x184f916c8 0x184f92484 0x184f3e9a4 0x1854e9ce4 0x1854e4bac 0x1854e40e0 0x18775d584 0x1b26f8c00 0x10070aa68 0x184fa2bb4)

**Comment by dllewellyn** [comment]
I am having the same issue. 

```
[✓] Flutter (Channel master, v1.8.1-pre.23, on Mac OS X 10.14.5 18F132, locale en-GB)
    • Flutter version 1.8.1-pre.23 at /Users/danielllewellyn/Developer/flutter
    • Framework revision 3bf91b5436 (3 days ago), 2019-07-05 12:59:32 -0700
    • Engine revision 3c51a7bfff
    • Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)

```

**Comment by doctorlh** [comment]
> I am having the same issue.
> 
> ```
> [✓] Flutter (Channel master, v1.8.1-pre.23, on Mac OS X 10.14.5 18F132, locale en-GB)
>     • Flutter version 1.8.1-pre.23 at /Users/danielllewellyn/Developer/flutter
>     • Framework revision 3bf91b5436 (3 days ago), 2019-07-05 12:59:32 -0700
>     • Engine revision 3c51a7bfff
>     • Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)
> ```

Change the bundle id or reset the phone by tap "Erase All Content and Settings". ... weird

**Comment by dllewellyn** [comment]
So I've sort of traced the crash for this. It looks like in the response from the app store when you receive an error it tries to parse the message here: 

```[self.callbackChannel invokeMethod:@"updatedTransactions" arguments:maps];```

Inside the map is something of argument NSError, when I print out the argument 'maps' I see this: 

```
                                                               
        error =         {                                               
            code = "-1003";                                             
            domain = NSURLErrorDomain;                                  
            userInfo =             {                                    
                NSErrorFailingURLKey = "https://sandbox.itunes.apple.com/WebObjects/MZFinance.woa/wa/inAppBuy";
                NSErrorFailingURLStringKey = "https://sandbox.itunes.apple.com/WebObjects/MZFinance.woa/wa/inAppBuy";
                NSLocalizedDescription = "Cannot connect to iTunes Store";
                NSUnderlyingError = "Error Domain=kCFErrorDomainCFNetwork Code=-1003 \"(null)\" UserInfo={_kCFStreamErrorCodeKey=-72000, _kCFStreamErrorDomainKey=10}";
                "_NSURLErrorFailingURLSessionTaskErrorKey" = "LocalDataTask <62783181-C95D-4D56-A674-0B84235AD7E2>.<2>";
                "_NSURLErrorRelatedURLSessionTaskErrorKey" =                 (
                    "LocalDataTask <62783181-C95D-4D56-A674-0B84235AD7E2>.<2>"
                );                                                      
                "_kCFStreamErrorCodeKey" = "-72000";                    
                "_kCFStreamErrorDomainKey" = 10;                        
            };                                                          
        };                                                              
        originalTransaction = "<null>";                                 
        payment =         {                                             
            applicationUsername = "<null>";                             
            productIdentifier = "******";                       
            quantity = 1;                                               
            requestData = "<null>";                                     
            simulatesAskToBuyInSandbox = 0;                             
        };                                                              
        transactionIdentifier = "47EC148E-2B58-4908-BE73-171A9A02A3A7"; 
        transactionState = 2;                                           
        transactionTimeStamp = "<null>";                                
    },          
```

Which ultimately fails here: 

```
  if (value == nil || value == [NSNull null]) {
    [self writeByte:FlutterStandardFieldNil];
  } else if ([value isKindOfClass:[NSNumber class]]) {
   ...
    if (CFGetTypeID(number) == CFBooleanGetTypeID()) {
    ...
    } else if (CFNumberIsFloatType(number)) {
     ...
    } else if (CFNumberGetByteSize(number) <= 4) {
      ...
  } else if ([value isKindOfClass:[NSString class]]) {
  ...
  } else if ([value isKindOfClass:[FlutterStandardTypedData class]]) {
    ...
  } else if ([value isKindOfClass:[NSData class]]) {
   ...
  } else if ([value isKindOfClass:[NSArray class]]) {
    ...
  } else if ([value isKindOfClass:[NSDictionary class]]) {
    ...
  } else {
    NSLog(@"Unsupported value: %@ of type %@", value, [value class]);
    NSAssert(NO, @"Unsupported value for standard codec");
  }
```

Because NSError isn't a supported type.

I can think of three work arounds / fixes - one to add NSError to the FlutterStandardCodec and parse it to a flutter exception, which seems like a fairly large change. Another option would be to filter the change filter just before calling [self.callbackChannel invokeMethod:@"updatedTransactions" arguments:maps]; and throw an exception if there's anything of type NSError, final one would be to create a custom method handler for the plugin to handle NSErrors.

Not sure if this sounds correct as a cause for the error to anyone?

**Comment by doctorlh** [comment]
I think this pull request will solve. [1819](https://github.com/flutter/plugins/pull/1819)

**Comment by dllewellyn** [comment]
Yep I think you're right - cheers

**Comment by hiddenfloret** [comment]
2 years later I am having the same issue. The crash happens when I call the `buyNonConsumable` method.

**Comment by stefanschaller** [comment]
I have the same issue. @hiddenfloret 

 @doctorlh Any solution to fix it this time?
