### ISSUE TITLE
INSTALL_FAILED_NO_MATCHING_ABIS  

### ISSUE THREAD

**Issue by kebeyDing** [flutter/flutter#35166]
Error: ADB exited with exit code 1
adb: failed to install /Users/xxxx/FlutterProjects/flutter_xxx/build/app/outputs/apk/app.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
Error launching application on Android SDK built for x86.

why??

**Comment by iqbalmineraltown** [comment]
Please post the `flutter doctor -v` output

did you use build flavors on your gradle?

**Comment by kebeyDing** [comment]
> flutter doctor -v

 Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.6.3 at /Users/kebey/flutter/flutter
    • Framework revision bc7bc94083 (5 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kebey/Library/Android/sdk
    • Android NDK at /Users/kebey/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

 Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

**Comment by kebeyDing** [comment]
> Please post the `flutter doctor -v` output
> 
> did you use build flavors on your gradle?

yes ,Our project needs to configure so files, so we configure armeabi, armeabi-v7a, x86,

However, we are running normally in debug mode, but not in release mode.

**Comment by iqbalmineraltown** [comment]
you should specify the flavors when running/building app as written here:
https://flutter.dev/docs/deployment/flavors
