### ISSUE TITLE
How to use FragmentActivity inside flutter project ?

### ISSUE THREAD

**Issue by Ariunbold0904** [flutter/flutter#35175]
Hello everyone. Can I use FragmentActivity inside flutter project? I want to implement BiometricPrompt with native code but it required fragmentActivity as a parameter.

Now the main activity looks like this:
public class **MainActivity** extends **FlutterActivity**

So, I can't use this kind of code:
**FragmentActivity** fActivity = this;

Please. Help guys.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
