### ISSUE TITLE
FlutterOverlayView doesn't remove from superview in some cases

### ISSUE THREAD

**Issue by Qxyat** [flutter/flutter#35177]
Steps to Reproduce
![1](https://user-images.githubusercontent.com/11627283/60264735-87e87700-9916-11e9-8255-ed1e6b30e501.gif)
 I build an iOS platform view with yellow color in the page. When app life cycle changed to the  AppLifecycleState.resumed，I rebuild the platform view. But the number below it become strange.Please take a look at the gif.

And the demo is here.
https://github.com/Qxyat/Flutter-demo/tree/master/platform_view_demo

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.7.11-pre.24, on Mac OS X 10.14.5 18F203, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 10.2)
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.34.0)
[✓] Connected device (4 available)

! Doctor found issues in 1 category.

**Comment by cyanglaz** [comment]
PR is merged, i'm closing the issue. Please feel free to reopen if related issue if found.
