### ISSUE TITLE
 keystore load: Keystore was tampered with, or password was incorrect

### ISSUE THREAD

**Issue by yossefEl** [flutter/flutter#35178]
## I'm gonna kill myself hahahaha.. i tried many solutions but no one works,
key.properties
```
storePassword=*********
keyPassword=********
keyAlias=key
```
I tried this 
```
storeFile=C:\\flutter_dev\\key.jks
```
and this 
```
storeFile=C:\flutter_dev\key.jks
```
and also this 
```
storeFile=C:/flutter_dev/key.jks
```
but every time i run the build command i get this 🤣
```
$flutter build appbundle
Initializing gradle...                                             11.8s
Resolving dependencies...                                          34.8s

FAILURE: Build failed with an exception.

 What went wrong:
Execution failed for task ':app:packageReleaseBundle'.
> java.util.concurrent.ExecutionException: java.lang.RuntimeException: jarsigner.exefailed with exit code 1 :
  jarsigner error: java.lang.RuntimeException: keystore load: Keystore was tampered with, or password was incorrect

 Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full
insights.

 Get more help at https://help.gradle.org

BUILD FAILED in 38s
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                        41.1s
```

**Comment by JonathanWilbur** [comment]
I am getting the same issue. I know the password of my store and key because I can change it, but it does not decrypt.

**Comment by JonathanWilbur** [comment]
Actually, I figured out the issue. In my case, I copied the key from elsewhere, but I was changing the password in the original location. Check that you are not doing the same.

**Comment by yossefEl** [comment]
@jonathanWilbur can you please explain how..i didn't understand what you mean by copying key from elsewhere

**Comment by yossefEl** [comment]
but before that.. thank you so much for considering my issue

**Comment by JonathanWilbur** [comment]
> 
> 
> @JonathanWilbur can you please explain how..i didn't understand what you mean by copying key from elsewhere

`cp C:\Users\Jonathan\key.jks .\android\app\key.jks`

**Comment by yossefEl** [comment]
@JonathanWilbur is till getting the same error 😣

**Comment by sssalib42** [comment]
Create the key at the <flutter app directory>/android/app folder.

**Comment by XbIK** [comment]
try `flutter clean`

**Comment by ricardochen** [comment]
We have to do flutter clean every time we change the values

**Comment by liuasher** [comment]
@sssalib42 

thanks for ur suggestion, my problem is sloved,even I don't know why I have to generate key.jks in my 'android/app' folder,hahahahah

**Comment by nb312** [comment]
> 1- Create the key at the /android/app folder.
> 2- To create the key remove the '~' from the code provided in the [flutter guide](https://flutter.dev/docs/deployment/android#create-a-keystore)
> From: `keytool -genkey -v -keystore ~/key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias key`
> To: `keytool -genkey -v -keystore key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias key`
> 3- Do not use quotes to wrap around variables in the key.properties file. So here is an example:
> 
> ```
> storePassword=mypassword
> keyPassword=mypassword
> keyAlias=key
> storeFile=key.jks
> ```

Thanks very much. I have solved this issue.

**Comment by BondarenkoStas** [comment]
Cool, I think it's safe to close the issue.

**Comment by ZurMaD** [comment]
Also useful for me https://flutter.dev/docs/deployment/android#create-a-keystore
