### ISSUE TITLE
[undefined] flutter create --ios-language objc --android-language java .

### ISSUE THREAD

**Issue by chanpanha** [flutter/flutter#35179]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by minh98** [comment]
objc and java are default. just using flutter create

**Comment by shashidharreddydakuri** [comment]
> objc and java are default. just using flutter create

I didn't understand, can you explain. i installed flutter and flutter doctor working perfect but when i run flutter: new project in vscode it showing this error
[undefined] flutter create --ios-language objc --android-language java .
Waiting for another flutter command to release the startup lock...
Creating project ....
  .gitignore (created)

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: aa59e1a8c31996c2)
Crash report written to C:\Users\mr\AppData\Local\Temp\flutter_07.log;
please let us know at https://github.com/flutter/flutter/issues.
exit code 1
[flutter_01.log](https://github.com/flutter/flutter/files/3335032/flutter_01.log)
[flutter_02.log](https://github.com/flutter/flutter/files/3335034/flutter_02.log)
