### ISSUE TITLE
Make a Snackbar configurable to be dismissable or not

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#35173]
Make a Snackbar configurable to be dismissable or not

This is a stackoverflow question with the same problem.
https://stackoverflow.com/questions/53870123/flutter-prevent-snackbar-from-getting-dismissed-on-swipe

**Comment by HansMuller** [comment]
What's the use case for creating a SnackBar that can't be dismissed? Maybe it would be better to provide a  different notifcation UI, for example  https://material.io/design/components/banners.html
