### ISSUE TITLE
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

### ISSUE THREAD

**Issue by nikosibarani** [flutter/flutter#35170]
> ## command
> 
> flutter run
> 
> ## exception
> 
> _Exception: Exception: /Users/mercatomacair1/tanamduit_project/app_project/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/OpenSSL.framework/Resources is neither File nor Directory
> 
> ```
> #0      copyDirectorySync (package:flutter_tools/src/base/file_system.dart:88:7)
> #1      copyDirectorySync (package:flutter_tools/src/base/file_system.dart:85:7)
> #2      copyDirectorySync (package:flutter_tools/src/base/file_system.dart:85:7)
> #3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:570:7)
> <asynchronous suspension>
> #4      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:382:48)
> <asynchronous suspension>
> #5      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:307:15)
> <asynchronous suspension>
> #6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:364:54)
> #7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
> #8      _rootRunUnary (dart:async/zone.dart:1132:38)
> #9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #10     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
> #11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
> #12     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
> #13     Future._complete (dart:async/future_impl.dart:473:7)
> #14     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
> #15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
> #16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
> #17     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
> #18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
> #19     _rootRunUnary (dart:async/zone.dart:1132:38)
> #20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #21     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
> #22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
> #23     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
> #24     Future._complete (dart:async/future_impl.dart:473:7)
> #25     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
> #26     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
> #27     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
> #28     FlutterProject.fromDirectory (package:flutter_tools/src/project.dart)
> #29     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
> #30     _rootRunUnary (dart:async/zone.dart:1132:38)
> #31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #32     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
> #33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
> #34     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
> #35     Future._complete (dart:async/future_impl.dart:473:7)
> #36     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
> #37     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
> #38     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
> #39     FlutterProject._readManifest (package:flutter_tools/src/project.dart)
> #40     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
> #41     _rootRunUnary (dart:async/zone.dart:1132:38)
> #42     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #43     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
> #44     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
> #45     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
> #46     Future._complete (dart:async/future_impl.dart:473:7)
> #47     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
> #48     _rootRunUnary (dart:async/zone.dart:1132:38)
> #49     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #50     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
> #51     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
> #52     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
> #53     Future._complete (dart:async/future_impl.dart:473:7)
> #54     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
> #55     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
> #56     _rootRun (dart:async/zone.dart:1124:13)
> #57     _CustomZone.run (dart:async/zone.dart:1021:19)
> #58     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
> #59     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> #60     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> #61     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
> #62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
> ```
> 
> ## flutter doctor
> 
> ```
> [32m[✓][39m Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-ID)
>     [32m•[39m Flutter version 1.5.4-hotfix.2 at /Users/mercatomacair1/flutter
>     [32m•[39m Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
>     [32m•[39m Engine revision 52c7a1e849
>     [32m•[39m Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
> 
> [32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     [32m•[39m Android SDK at /Users/mercatomacair1/Library/Android/sdk
>     [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
>     [32m•[39m Platform android-28, build-tools 28.0.3
>     [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
>     [32m•[39m All Android licenses accepted.
> 
> [33m[!][39m iOS toolchain - develop for iOS devices (Xcode 10.2.1)
>     [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
>     [32m•[39m Xcode 10.2.1, Build version 10E1001
>     [32m•[39m ios-deploy 1.9.4
>     [33m![39m CocoaPods out of date (1.5.0 is recommended).
>         CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
>         Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
>         For more info, see https://flutter.dev/platform-plugins
>       To upgrade:
>         brew upgrade cocoapods
>         pod setup
> 
> [32m[✓][39m Android Studio (version 3.4)
>     [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
>     [32m•[39m Flutter plugin version 35.3.1
>     [32m•[39m Dart plugin version 183.6270
>     [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [32m[✓][39m Connected device (1 available)
>     [32m•[39m iPhone Xʀ • 1DECEE25-6B10-4555-8D7C-F8545A475A07 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
> 
> [33m![39m Doctor found issues in 1 category.

**Comment by ketanm** [comment]
@nikosibarani 

Make sure that OpenSSL is installed correctly - https://cocoapods.org/pods/OpenSSL-Framework

Also as mentioned in `flutter doctor` - Cocoapods is out of date, there were some known issues in the prior version. Update Cocoapods as mentioned in the output.

**Comment by BondarenkoStas** [comment]
@nikosibarani did you manage to solve the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
