### ISSUE TITLE
Swift based flutter plugin that depends on Objective-C framework using bridging header

### ISSUE THREAD

**Issue by mohanraoa** [flutter/flutter#35182]
I have a requirement to develop swift based flutter plugin that depends on Objective-C framework using bridging header but I could not find any example. 

what changes are required to make swift code work with objective-c framework using bridging header .

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
