### ISSUE TITLE
examples/layers does not work in iOS simulator

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#3518]
Follow the instructions in examples/layers/README.md.

```
flutter run -t widgets/autolayout.dart                                    [/src/flutter/examples/layers]
No application found for TargetPlatform.ios.
Is your project missing an ios/Info.plist?
```

Not sure if I just need to run `flutter create` on the directory to add the ios directory, or if -t can't work with iOS simulator as currently designed?

@chinmaygarde @devoncarew

**Comment by eseidel** [comment]
Tried `flutter create .` on the layers directory, and then `flutter run` again:

```
flutter run -t widgets/autolayout.dart                                    [/src/flutter/examples/layers]
Running widgets/autolayout.dart on iPhone 6...
Unzipping Xcode project to local directory...
Xcode project created in /Stuff/Projects/flutter/examples/layers/ios/.
Could not find the built application bundle at ios/.generated/build/Release-iphonesimulator/Runner.app.
Error running application on iPhone 6.
```

**Comment by eseidel** [comment]
It looks like second failure "Error running application on iPhone 6." is unrelated.  Even `flutter create foo; cd foo; flutter run` is not working for me, so that's a separate issue.

**Comment by Hixie** [comment]
Looks like this is fixed.
