### ISSUE TITLE
[image_picker] Image taken with camera with maxHeight or maxWidth on iOS is rotated 90 degrees

### ISSUE THREAD

**Issue by BOBODDY** [flutter/flutter#35184]
I'm using the `image_picker` plugin to get images for my app, version `^0.6.0+10`. On my Android device, both the camera and gallery options work as expected. On my iOS device, gallery pictures work as expected but pictures taken with the camera are rotated 90 degrees when the `maxWidth` or `maxHeight` parameters are given.

I made a small example project to make sure it wasn't a problem in my app, which can be found [here](https://github.com/BOBODDY/rotated-image). It's mostly a copy of the plugin example.

Below are screenshots demonstrating what I'm seeing.

![IMG_0025](https://user-images.githubusercontent.com/1264583/60272321-ecc5b200-98c1-11e9-8639-0ba4c5b971a6.PNG)

![IMG_0026](https://user-images.githubusercontent.com/1264583/60272324-ee8f7580-98c1-11e9-8a3b-2e52392afccc.PNG)

**Comment by BOBODDY** [comment]
I suppose as a workaround, I could take the image full size from the plugin and do my own scaling in dart. I'll try that until I hear more on this issue.

**Comment by lukaspili** [comment]
Same issue.
Adding flutter doctor:

```
[✓] Flutter (Channel dev, v1.7.9, on Mac OS X 10.14.5 18F132, locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
[✓] VS Code (version 1.35.1)
[✓] Connected device (3 available)
```

**Comment by BOBODDY** [comment]
Tried resizing the image following [this SO answer](https://stackoverflow.com/questions/49701654/how-can-i-read-from-disk-and-resize-an-image-in-flutter-dart), but the image is still showing rotated. I think the scaling is somehow wiping the exif orientation

**Comment by davicg** [comment]
Facing the same problem here in all iOS devices. This issue started on image_picker version 0.6.0. Until  0.5.4+3 everything was working fine in iOS, but unfortunately this version presents other problems on Android.

**Comment by BondarenkoStas** [comment]
@BOBODDY it should be already fixed https://github.com/flutter/flutter/issues/37688#issuecomment-521864600. Please try and report if there will be any problems.
