### ISSUE TITLE
[undefined] flutter create --ios-language objc --android-language java .

### ISSUE THREAD

**Issue by shashidharreddydakuri** [flutter/flutter#35185]
[undefined] flutter create --ios-language objc --android-language java .

I
[flutter_01.log](https://github.com/flutter/flutter/files/3335089/flutter_01.log)
[flutter_02.log](https://github.com/flutter/flutter/files/3335090/flutter_02.log)

 installed flutter and flutter doctor working perfect but when i run flutter: new project in vscode it showing this error

[undefined] flutter create --ios-language objc --android-language java .
Waiting for another flutter command to release the startup lock...
Creating project ....
.gitignore (created)

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: aa59e1a8c31996c2)
Crash report written to C:\Users\mr\AppData\Local\Temp\flutter_07.log;
please let us know at https://github.com/flutter/flutter/issues.
exit code 1

**Comment by shashidharreddydakuri** [comment]
@jonahwilliams hi, do you know anything about the problem

**Comment by shashidharreddydakuri** [comment]
My windows defender Controlled folder access is restricting the flutter project from creating projects

**Comment by Jeluchez** [comment]
disable your antivirus.
