### ISSUE TITLE
ListView scroll issue when embedded in UIPageViewController

### ISSUE THREAD

**Issue by jkmathew** [flutter/flutter#35180]
My app contains a `UIPageViewController`, `FlutterViewController` is one of the child view controllers of page view controller. When a list view is visible in flutter view controller, the scrolling ends up in a mess. Exact vertical scroll(straight 90 degree swipe) will work, but slight change in finger to right or left  during vertical scroll will loose list view scroll and page view controller's scrollview steals the interaction.

Exact same scenario I tried with UITableView, but it works perfectly.

## Steps to Reproduce

1. Follow [this Wiki ](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps)to add flutter to existing app.
2. In flutter, make ListView as the body of scaffold.
3. Return FlutterViewController in page view controller datasource
4. Scroll left/right to flutter view controller.
5. Try to scroll ListView normally.

flutter doctor -v
```
[!] Flutter (Channel master, v1.7.4-pre.71, on Mac OS X 10.15 19A471t, locale
    en-DE)
    • Flutter version 1.7.4-pre.71 at /usr/local/custom/flutter
    • Framework revision fa174a123f (2 weeks ago), 2019-06-12 00:45:55 -0400
    • Engine revision b14d971960
    • Dart version 2.3.3 (build 2.3.3-dev.0.0 b37aa3b036)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/johnnykuttymathew/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.0

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] Connected device (2 available)
    • iPhone    • bdd4a95972ed22175d34736c3ca522bea511dcbd • ios • iOS 12.3.1
    • iPhone Xʀ • 98882BC0-AF96-4B19-B530-78A7EFAA5DFF     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
```

Minimum reproducible project: https://github.com/jkmathew/Issues/tree/master/SwipeIssue

**Comment by BondarenkoStas** [comment]
@jkmathew is it the same while using current flutter stable v1.9.1+hotfix.4?

**Comment by gaaclarke** [comment]
This maybe related to https://github.com/flutter/flutter/issues/26637

**Comment by jkmathew** [comment]
Sorry team...
I am off to flutter now, not able to check this case at the moment. 

should we close this issue?
