### ISSUE TITLE
Video_Player Package on iOS has a really annoying bug

### ISSUE THREAD

**Issue by MichelRahme** [flutter/flutter#35190]
I want to use the video_player plugin to display one simple video on the home_screen of my app. I've implemented the player and it works perfectly until, when i exit the app on my iphone and then open it again, the video player turns into a white screen. Same thing happens if i navigate to another page on my app and then come back to the home page, also when I slide the Control Center on my phone. This only happens on IOS and when the video is PAUSED.
Now if I run my app on the android simulator, this problem disappears but the audio in the video starts way before the video itself.
I won't bore you with the code because its the same exact implementation of the plug-in's example on github.
Here is a gif showing the issue: https://giphy.com/gifs/eMOy0qS09WpoAEADDl
I have no clue on what might be causing this, is there a way I can fix this ? 
When the video is paused, if I quit the app or switch to another app, when I come back, i'd like the video to still be paused on the same frame. 

Thanks

**Comment by recastrodiaz** [comment]
Related issue: https://github.com/flutter/flutter/issues/28613

**Comment by iapicca** [comment]
Hi @MichelRahme 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Thank you

**Comment by MichelRahme** [comment]
HI @iapicca 
I just finished testing it again. The issue is gone with the latest version. 
Thank you
