### ISSUE TITLE
CupertinoSegmentedControl in iOS 13 has been redesigned

### ISSUE THREAD

**Issue by miguelpruivo** [flutter/flutter#35195]
Looks like we have some changes in iOS 13 for the `CupertinoSegmentedControl`.

## OLD - (iOS 12 and older)
![CGQfXlw](https://user-images.githubusercontent.com/27860743/60285864-61224480-9906-11e9-888d-3f1219df00fb.jpg)

## NEW - (iOS 13)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/27860743/60285983-b3636580-9906-11e9-9220-ac691ed80406.gif)

**Comment by shihaohong** [comment]
An issue has been opened to track this already - https://github.com/flutter/flutter/issues/33796

There is a larger-scale issue at https://github.com/flutter/flutter/issues/35026 that tracks all iOS13 changes. I will close this for now. If you find any other iOS 13 changes that have not already been added, please feel free to add those. 

I will close this for now :) Thank you!

**Comment by Ashish8460** [comment]
is the flutter support for ios 13 dark mode?
and how to add support for dark mode for ios only?
