### ISSUE TITLE
[web]  Firestore plugin

### ISSUE THREAD

**Issue by mohamed6996** [flutter/flutter#35203]
I`m sure that i can`t use firestore plugin at the moment as it depends on the flutter sdk which is not the same as the flutter_web sdk. 

My question is, should i go to a different web platform like AngularDart and share the same business logic or should i user flutter and firestore api (instead of the plugin)

either ways i will invest much time.. should i wait for the flutter team to support flutter plugins? is there any rough estimate?

**Comment by gabber235** [comment]
If you want to use firebase with javascript, you can take a look at this plugin https://pub.dev/packages/firebase

**Comment by mohamed6996** [comment]
Yeah, I have been using it and everything works great D:
