### ISSUE TITLE
Webview_flutter sample example not working in Samsung Tab 4 (BrowserStack)

### ISSUE THREAD

**Issue by hiddencaliber** [flutter/flutter#35205]
Hi,

I tried installing app to Browserstack Samsung Tab 4 device and the example for webview flutter is not working. 

https://app-live.browserstack.com/#

Please help.

Thanks,

**Comment by VladyslavBondarenko** [comment]
@hiddencaliber 
I hope you've solved the issue. 
If it's not so, please file a new issue with the exact descriptions what happens, logs, output of `flutter doctor -v` and specifying used webview_flutter version
Thank you
