### ISSUE TITLE
IgnorePointer does not prevent Listener.hover events

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#35213]
Wrapping a hoverable widget (something using `Listener`) in an `IgnorePointer` does not suppress hover events.

A `FloatingActionButton` demonstrates the issue. 

## Steps to Reproduce

1. Create a new sample *desktop* application (I'm using macOS)
2. Wrap the application in an IgnorePointer (or AbsorbPointer)
3. Click events are suppressed, but enters/exits continue to function

**Comment by willlarche** [comment]
Polish issue.
