### ISSUE TITLE
Firebase Messaging and status done, id 1.

### ISSUE THREAD

**Issue by ghenry** [flutter/flutter#35212]
Hi all,

I've had this open for a week now and not sure where to do next:

https://stackoverflow.com/questions/56693705/what-is-the-id-and-status-option-in-the-data-payload-of-a-firebase-cloud-message

> I'm trying to figure out if I need to manage the id and status values in my backend service. Looks like it, but what are others doing here?

I think I might as when I click the notification the message is sometimes coming through as null, so maybe the ID needs to ++?

Thanks.

**Comment by BondarenkoStas** [comment]
@ghenry I saw there is an answer on SO, did it solve your issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
