### ISSUE TITLE
`flutter run` should not automatically run `web` if I don't have a connected device

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#35216]
It seems like a very confusing default behavior to automatically run an experimental project if I don't happen to have my simulator running. :(

**Comment by eseidelGoogle** [comment]
I was running `flutter/examples/flutter_gallery`

**Comment by jonahwilliams** [comment]
We discussed this in chat and via  https://docs.google.com/document/d/1xDdX2bbNKpvo_6-EtSJ5xxPfqVSJ3xNDfWBiBkmCXNQ/edit.

The conclusion is that we don't automatically run web, but that particular app supports web so it is a viable candidate.
