### ISSUE TITLE
image picker duplicate class error

### ISSUE THREAD

**Issue by jocaagura** [flutter/flutter#35214]
When i tried make a build i found this error
`D8: Program type already present: android.support.v4.media.MediaBrowserCompat$CustomActionCallback

FAILURE: Build failed with an exception.`

other plugs that works perfectly into pubspec.yaml are:

- cupertino_icons: ^0.1.2
  image_picker: ^0.6.0+10
  flutter_swiper: ^1.1.6
  http: 
  qrcode_reader: ^0.4.4
  sqflite: ^1.1.0
  path_provider: ^1.1.0
  url_launcher: ^5.0.3
  google_maps_flutter: ^0.5.19
  shared_preferences: ^0.5.3+1
  rxdart: ^0.22.0

More info:
`*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1`

**Comment by saiof95** [comment]
Use android x compatible plugins or migrate your project to android x. For more info visit https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

**Comment by BondarenkoStas** [comment]
@jocaagura Closing the issue, please report if migrating didn't solve your problem.
