### ISSUE TITLE
Request for Firebase App Indexing plugin

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#35224]
We had an internal request to add this plugin. https://firebase.google.com/docs/app-indexing

It seems on iOS, this requires universal links. Do we have core support for this? It seems this is different from Firebase Dynamic Links :-/ 

For Android, the main plugin work is around enabling this: https://firebase.google.com/docs/app-indexing/android/personal-content

**Comment by kroikie** [comment]
@mehmetf

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/361. Any further collaboration will be done there.
