### ISSUE TITLE
image_picker add timestamp to an image

### ISSUE THREAD

**Issue by rupert2133** [flutter/flutter#35235]
Feature request. Add timestamp text to an image captured via image_picker.

**Comment by PixelToast** [comment]
This would be image manipulation which is out of the scope of what image_picker is for

**Comment by BondarenkoStas** [comment]
It's right, 
> A Flutter plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.
I think it's safe to close the issue. I believe there are other ways to add a timestamp.

**Comment by maheshmnj** [comment]
> It's right,
> 
> > A Flutter plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.
> 
> I think it's safe to close the issue. I believe there are other ways to add a timestamp.

can you please specify some way to add a timestamp to an image clicked by a camera or drop some relevant links here,it would be really helpful.
