### ISSUE TITLE
Firebase auth user.getIdToken ((String s){});

### ISSUE THREAD

**Issue by henrytz** [flutter/flutter#35230]
It seems that the maximum number of character a string can hold in flutter is 1088 characters. This became a huge problem for instance. I'm trying to implement firebase auth in my flutter app I was able to log in with facebook get the token but it appears the token is incomplete because the getIdToken method assigns the result in a String variable and since it cannot hold more than 1088 characters the  token became incomplete and I receive  'Invalid Signature Exception' I really don't know how to go from here

**Comment by PixelToast** [comment]
There is no such limit on string lengths, please post your code

**Comment by BondarenkoStas** [comment]
@henrytz Can you please show where did you find a limit?
Please provide your flutter doctor -v output, firebase_auth version and a small self-contained app that demonstrates the problem, if you still encounter the issue. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
