### ISSUE TITLE
Flutter UI freezes with webview_flutter and progressindicator on iOS

### ISSUE THREAD

**Issue by YukiOya** [flutter/flutter#35244]
## Details

On running the following apps with iOS release build, the screen gets stuck frequently during scrolling WebView or transitioning the Widget contains WebView by MaterialRoute. Also, as shown in the attached screenshot below, GPU usage makes peaks during the screen freezing.

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MaterialApp(
    showPerformanceOverlay: true,
    home: Scaffold(
      body: Stack(children: <Widget>[
        WebView(initialUrl: "https://flutter.dev"),
        Center(child: CircularProgressIndicator()),
      ]),
    )));
```

![IMG_0218](https://user-images.githubusercontent.com/2102096/60317061-515b3c80-99a8-11e9-8be2-7c7cb59f190c.png)

## Test environment

- iPod touch with system iOS 10.3.1
- iPhone 8 with system iOS 12.3.1

## Logs

nothing.

`flutter doctor -v` 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale ja-JP)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] VS Code (version 1.35.1)
[✓] Connected device (1 available)
```

**Comment by evelyne24** [comment]
Tested and confirmed on iOS 12+ XS and XR.

**Comment by superwave** [comment]
same on iOS 12 with iPhone XS, iPhone 6+, iPad mini, iPhone XR.
does someone have workaround to solve this problem?

**Comment by darshankawar** [comment]
Hi @YukiOya , I tried to replicate this issue on iOS simulator (13.3) with latest Flutter` dev channel (1.20.0-0.0.pre)` and latest version of `webview_flutter`, but didn't see any freeze in UI. I was able to scroll down and up properly and screen was rendered as expected.

[35244.mov.zip](https://github.com/flutter/flutter/files/4831154/35244.mov.zip)

I tested this on release mode.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.20.0-0.0.pre at /Users/deeptibelsare/Documents/Fluttersdk/flutter
    • Framework revision d9653445f4 (8 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

</details>

<details>
<summary>code sample</summary>

```
return MaterialApp(
      showPerformanceOverlay: true,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
        home: Scaffold(
          body: Stack(children: <Widget>[
            WebView(initialUrl: "https://flutter.dev"),
            Center(child: CircularProgressIndicator()),
          ]),
        ));
```

</details>

Can you please confirm if you still see this issue on latest Flutter and `webview_flutter` plugin ?

**Comment by darshankawar** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
