### ISSUE TITLE
Firebase Admob Load InterstitialAd

### ISSUE THREAD

**Issue by RaviKavaiya** [flutter/flutter#35249]
Hello! (I am new to this, so please ignore mistakes)

**Problem I am facing :** 

I have an application in which I want to display 'Interstitial Ads' (full screen) EVERY 2 MINUTES (or any interval...)

Till now, I am successful in this.

BUT, my question is, do I have to` .load()` the Ad every time I want to display an ad?
Or simply calling `.show()` every time does the trick???

**Comment by GyuriMajercsik** [comment]
I believe this is something you would ask on stackoverflow. This is not an issue.
