### ISSUE TITLE
FlutterFragmentActivity not find setContentView

### ISSUE THREAD

**Issue by psujug** [flutter/flutter#35252]
old project for Android.  import the flutter module. android project used androidx support aar.
my activity extends FlutterFragmentActivity , the "setContentView" error . i guess it's "androidx" reason.would you give me solution. thanks

**Comment by BondarenkoStas** [comment]
@psujug did you manage to solve the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
