### ISSUE TITLE
Xcode Error when trying to build iOS app using Microsoft AppCenter

### ISSUE THREAD

**Issue by Rossdex** [flutter/flutter#35258]
I have a working iOS app that I have built using a local mac in my office, however when I try to build the app using Microsoft AppCenter I get the below error. When building on my mac I am able to change this file manually, however I have to change it every time I build and this is obviously not ideal.

Xcode Version: Xcode 10.2.1
Flutter Version: Flutter v1.5.4-hotfix.2.

If you need any more info please ask!

Xcode's output:
↳
    === BUILD TARGET device_info OF PROJECT Pods WITH CONFIGURATION Release ===
    /Users/vsts/agent/2.152.1/work/1/s/ios/Pods/SCrypto/Source/SCrypto.swift:107:111: error: using '!' is not allowed here; perhaps '?' was intended?
            typealias Function = (_ data: UnsafeRawPointer, _ len: CC_LONG, _ md: UnsafeMutablePointer<UInt8>) -> UnsafeMutablePointer<UInt8>!

**Comment by kangwang1988** [comment]
It seems a iOS issue resulted from third-party pod(SCrypto) instead of flutter one.

It would be better to ask on StackOverflow and only create an issue if it turns out to be a bug or a missing feature that prevents you from doing what you want.
