### ISSUE TITLE
ProcessException: Process "C:\Users\yashv\dartsdk-windows-x64-release\firestoredemo\android\gradlew.bat" exited abnormally: Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

### ISSUE THREAD

**Issue by yashvenrakumar** [flutter/flutter#35255]

**Comment by kangwang1988** [comment]
It seems a gradle issue instead of flutter one. 

It would be better to ask on StackOverflow and only create an issue if it turns out to be a bug or a missing feature that prevents you from doing what you want.
