### ISSUE TITLE
[web] How do I get the parameters to the request url?

### ISSUE THREAD

**Issue by YourksChan** [flutter/flutter#35261]
Example：
https://www.baidu.com?type=1

How do you get the type parameter from the flutter_web project?

**Comment by ehhc** [comment]
@YourksChan github issues are the wrong place for questions like this.. github issues are meant for framework issues (at least as long as i know).
Questions like the one you asked are better suited at stackoverflow.
Nonetheless, you could use the Uri-class to get the parameters:

```
Uri uri = Uri.dataFromString("https://www.baidu.com?type=1");
uri.queryParameters.forEach((k,v) => print(k + " - " + v));
```

**Comment by YourksChan** [comment]
> @YourksChan github问题是这样的问题的错误位置.github问题是针对框架问题的（至少只要我知道）。
> 像你问的那个问题更适合stackoverflow。
> 尽管如此，您可以使用Uri类来获取参数：
> 
> ```
> Uri uri = Uri.dataFromString("https://www.baidu.com?type=1");
> uri.queryParameters.forEach((k,v) => print(k + " - " + v));
> ```

![image](https://user-images.githubusercontent.com/50285055/60379879-f25ffb00-9a6d-11e9-9bdd-e20f23e9d363.png)

I can't get the browser url now

**Comment by deckerst** [comment]
@YourksChan you can get the query parameters by accessing `window.location.href` with the `dart:js` package:
```
import 'dart:js' as js;
...
var uri = Uri.tryParse(js.context['location']['href']);
if (uri != null) return uri.queryParameters;
```

**Comment by YourksChan** [comment]
> @YourksChan您可以通过访问获得的查询参数`window.location.href`与`dart:js`包装：
> 
> ```
> import 'dart:js' as js;
> ...
> var uri = Uri.tryParse(js.context['location']['href']);
> if (uri != null) return uri.queryParameters;
> ```

Thank you very much. You solved my problem perfectly!

**Comment by smileToWxm** [comment]
我在使用flutter_web的时候，在正式环境真机状态下，ios点击了TextField不会弹出软键盘，需要点击多次才会出现软键盘，而在Android上却不会出现该问题！！
有人可以帮助我吗？

When I use flutter_web, in the real state of the formal environment, IOS will not pop up the soft keyboard by clicking TextField. It will take many clicks to appear the soft keyboard, but it will not appear on Android!!

Can someone help me?

**Comment by ehhc** [comment]
@smileToWxm at a first look it, to me, it seems unrelated to the issue discuessed above.. maybe you should create a separated issue including a working example..?

**Comment by zhangzhenxi** [comment]
I follow the document from [Upgrading-from-package:flutter_web-to-the-Flutter-SDK](https://github.com/flutter/flutter/wiki/Upgrading-from-package:flutter_web-to-the-Flutter-SDK).
Then I find out can not import package `dart:html` or `dart:js`, so I can not access `window.location.href` to get query parameters from browser.

**Comment by zhangzhenxi** [comment]
flutter doctor -v

```
[✓] Flutter (Channel dev, v1.10.3, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
    • Flutter version 1.10.3 at /Users/zhenxi/env/flutter
    • Framework revision 2f3515de31 (5 days ago), 2019-09-13 17:52:41 -0400
    • Engine revision 7d8c6d9c1a
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 a554c8be6b)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/zhenxi/env/android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/zhenxi/env/android/sdk
    • ANDROID_SDK_ROOT = /Users/zhenxi/env/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132
    • Server • web    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by treeder** [comment]
Can also use: `Uri.base.queryParameters; => Map<String,String>`
