### ISSUE TITLE
Package flutter inside an iOS framework

### ISSUE THREAD

**Issue by vitor-gyant** [flutter/flutter#35262]
Hi,

I'm trying to create a native SDK on top of flutter but I'm not able to understand how Flutter and Plugin Podspecs interact.

I'm able to create a framework target using the app2app recipe which basically compiles App.Framework and Flutter.framework together with all the plugin frameworks declared in my pubspec.

The problem with this solution is that frameworks must be embedded at App level and not framework level which basically forces the host app to be aware of flutter and all the plugin frameworks.

Since I don't want to expose 3rd parties to all these details I started to look for a solution to pack all the dependencies together using Cocoapods packager. This basically demands that I'd create a podspec that would declare its dependencies which them are packed and mangled together.

Now since none of the Flutter, App and Plugin frameworks are deployed remotely this becomes a true challenge.

Is there a better path to achieve my goal ? 

Thanks in advance,

**Comment by vitor-gyant** [comment]
Might be related with #26099

cc @xster @dnfield

**Comment by xster** [comment]
cc @jmagman

**Comment by jmagman** [comment]
If you're willing to use CocoaPods, you could try to use [flutter build ios-framework](https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-b---embed-frameworks-in-xcode) to generate all the Release frameworks you need, then supply them as [`vendored_frameworks`](https://guides.cocoapods.org/syntax/podspec.html).  Of course that means you would need to host those binaries somewhere remotely, as you mentioned, where your users could fetch them by `pod 'Your-Framework'` in their Podfile.

Once https://github.com/flutter/flutter/issues/26712 is done, you would only need to vend the App.framework and any plugins, and your podspec would depend on the exact version of the Flutter pod they were built with.
```ruby
s.dependency 'Flutter', '1.12.1306'
```
Pretty much ditto to support Carthage once https://github.com/flutter/flutter/issues/24176 is done.

I know you created this issue first, but we're tracking this issue at https://github.com/flutter/flutter/issues/39027.  Closing this one, feel free to chime in over there.
