### ISSUE TITLE
Cloud Firestore FieldValue.increment in quick succession crashes app on Android

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#35269]
```
Flutter version: Channel master, v1.7.6-pre.48
cloud_firestore: 0.12.5+2
```

I am trying to update a document using `FieldValue.increment` and the code can be executed multiple times in a row:

```dart
await Firestore.instance
  .collection('cakes')
  .document('green')
  .updateData({'mass': FieldValue.increment(7)});
```

Basically, simply using `FieldValue.increment` in quick succession [(`< 1s`) will not produce an error](https://github.com/flutter/flutter/issues/31831#issuecomment-502773034) but crash the whole app on **Android** devices, i.e. force stop: https://gist.github.com/creativecreatorormaybenot/dd394363bb0a8dde27a5f3f33b9a9043

**Comment by thevzurd** [comment]
I think I had the same problem. Try this. Hope it Helps 
[FIrestore Transaction Handler](https://github.com/thevzurd/Firestore-Transaction-Handler)
