### ISSUE TITLE
Cannot change height of Row :( Would love if someone has a solution.

### ISSUE THREAD

**Issue by tylerreece22** [flutter/flutter#35273]
See code and image below:

```Dart
import 'package:flutter/material.dart';

// This entire widget is dropped into a Column
class WorkoutRow extends StatelessWidget {
  Widget item1;
  Widget item2;
  Widget item3;
  Widget item4;
  Widget item5;

  WorkoutRow(this.item1, this.item2, this.item3, this.item4, this.item5);

  Widget _rowItem(Widget headerName) {
    return Row( // <--------- This is the row that the height isnt changing. 
          mainAxisSize: MainAxisSize.min,
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            headerName,
          ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Container(
        height: 30.0,
        child: GridView.count(
          crossAxisSpacing: 15.0,
          physics: NeverScrollableScrollPhysics(),
          // Diables GridView scrolling
          shrinkWrap: true,
          //
          primary: true,
          crossAxisCount: 5,
          children: <Widget>[
            _rowItem(item1),
            _rowItem(item2),
            _rowItem(item3),
            _rowItem(item4),
            _rowItem(item5),
          ],
        ));
  }
}
```

![image](https://user-images.githubusercontent.com/9936635/60353764-b60e9b00-9998-11e9-86c1-5287d18059cd.png)

**Comment by pekretsc** [comment]
Hi there 

A row allways wraps around its content, so you can not change its size(Flex Widget). But what you could do is to blow it up like a balloon. 

So I guess your row Items shold look like 

Widget _rowItem(Widget headerName) {
    return Row( 
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
                  hight: 100
                  child: headerName()
             ),
             Container(
                  hight: 100
                  child: headerName()// Anything else
             ),
          ],
    );
  }

**Comment by tylerreece22** [comment]
This
```Dart
childAspectRatio: 2.0,
```
 did the trick when it comes to the button getting cut off but now there is still a problem with input padding but the RaisedButton has _inputPadding that is still messing it up. See below image.

![image](https://user-images.githubusercontent.com/9936635/60384824-920e9080-9a50-11e9-81c3-e4f3b6a64051.png)

**Comment by tylerreece22** [comment]
@pekretsc I will definitely give that a try. Thank you. Do you think it will solve the problem I mentioned right after yours? (I didn’t refresh the page before my last answer)

**Comment by tylerreece22** [comment]
This actually fixed itself once I removed a couple extra Containers throughout my code.
