### ISSUE TITLE
[flutter_driver] Driver should be able to report window scroll position

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#35275]
Internal issue: b/136260104

This is coming from customer: dream.

When using the flutter_driver for on-device UI tests (performance), we need to be able to determine the scroll position for windows/elements.  Please add this capability to the flutter_driver APIs.

@dballesteros7 FYI.

**Comment by mehmetf** [comment]
What's being required here is:

```
driver.getScrollPositions(Finder finder)
```

where the finder finds a scrollable widget (and its scroll controller) and returns a list of tuples <scroll_direction, scroll_amount>.

**Comment by mehmetf** [comment]
With this API, the test will look something like:

1) Trigger some search
2) Wait for results to load.
3) Capture the window's scroll position (should be 0,0 in this case)
4) Inject synthetic scroll gesture (at the kernel level).  Gestures have consistent finger speed, acceleration, and movement.
5) Capture window scroll position again and verify that the window scrolled (simple case) and/or that the window scrolled the expected number of pixels (more precise case).

(4) has uncovered bugs and differences in the way the device handles the touch events.

**Comment by mehmetf** [comment]
I am tentatively marking this as critical. It seems it is fairly useful to customer:dream to have this capability as they run driver tests on various devices.

**Comment by Hixie** [comment]
We're unlikely to get to this any time soon (we're working on making flutter_driver obsolete), but you should be able to implement something manually that does this pretty easily by using the mechanism for sending messages back to the driver along with some code in the app to report the scroll position.

**Comment by kf6gpe** [comment]
@Hixie Spoke with `customer: dream`  TPM this morning --- is there additional guidance that we can give them regarding how to wire this up themselves? Thanks!

**Comment by Hixie** [comment]
I'll follow-up by e-mail.
