### ISSUE TITLE
Adding Delegate Protocol to Plugin swift class causes SDK modules to not be found

### ISSUE THREAD

**Issue by drkhannah** [flutter/flutter#35270]
Hello, I'm creating a custom flutter plugin that uses a third party SDK.

I have installed an used this SDK with no problems up until the point that I needed to use a Delegate Protocol of the SDK

The second I add a Delegate Protocol to my custom plugin swift class, the project no longer recognizes my SDK

`public class SwiftCcfAwPlugin: NSObject, FlutterPlugin, SDKDelegate {}`

I have added the Protocols methods in this class, is there something else I'm missing? Do i need to add anything to the plugin's .h or .m files?

<img width="1672" alt="Screen Shot 2019-06-28 at 10 57 46 AM" src="https://user-images.githubusercontent.com/6707443/60351418-c2dcc000-9993-11e9-863b-937eef36e343.png">
<img width="1674" alt="Screen Shot 2019-06-28 at 10 57 56 AM" src="https://user-images.githubusercontent.com/6707443/60351422-c708dd80-9993-11e9-8455-c9f6141168a6.png">

**Comment by drkhannah** [comment]
bump

**Comment by jmagman** [comment]
Does AWSDK actually have a module (I'm assuming it's https://code.vmware.com/web/workspace-one/tutorials/Native-iOS/Airwatch-SDK)?  Are you able to `#import <AWSDK/AWSDKCore.h>` its umbrella header instead of `@import`?  Does your plugin example app (and maybe podspec) need anything from their Xcode embedding instructions? https://code.vmware.com/web/workspace-one/tutorials/Native-iOS/Airwatch-SDK

**Comment by iapicca** [comment]
Hi @drkhannah 
did you manage to solve this issue?

**Comment by drkhannah** [comment]
no i ditched using a plugin and used method channels in the project itself

**Comment by njovy** [comment]
I am having this issue as well. I try to implement a delegate written in Objective C.

**Comment by drkhannah** [comment]
I think it's a timing issue in the build

**Comment by njovy** [comment]
@drkhannah Oh.. Thank you for your reply. Did you find a solution? I switched back to objective c for this plugin haha

**Comment by drkhannah** [comment]
No I just moved to using method channels in a normal Flutter project and ditched creating a plug-in

**Comment by kf6gpe** [comment]
Based on @drkhannah 's comment, I'm wondering if this can't be addressed by tooling somehow. I'm going to assign it to the tools team for their triage.

**Comment by jmagman** [comment]
I don't think this is actionable without the responses to my questions at https://github.com/flutter/flutter/issues/35270#issuecomment-532940890.  Closing.
