### ISSUE TITLE
core engine size has increased significantly

### ISSUE THREAD

**Issue by rashedmyt** [flutter/flutter#35281]
In the [faq](https://flutter.dev/docs/resources/faq#how-big-is-the-flutter-engine), it says the core engine size is about 2.7MB, but it is not the case at present. Assuming `libflutter.so` file is the core engine it is at present 3.1MB, which is huge change in about 7 months I suppose.

**Edit**
The FAQ is updated to 3.2 & 3.5 MB

**Comment by dnfield** [comment]
I don't think there's any action to take on this bug right now.

The engine size grows over time as we add new features.  We work really hard to make sure it doesn't grow too much, and do whatever we can to reduce it.  We try to update the website periodically to reflect current figures.  

You can follow bugs around this by looking at the `a: size` label.
