### ISSUE TITLE
Adding measurements to dashboard

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3529]
Once https://github.com/flutter/flutter/pull/3523 lands, we can summarize on our dashboard.

Three items that would be interesting to know:
- number of new flutter apps created in the wild (per 7 days)
- number of 7DA users
- % of crash-free users (the percentage of 7DA users that had a crash-free 7 days)

**Comment by sethladd** [comment]
cc @yjbanov for help triaging this issue

**Comment by yjbanov** [comment]
Will be glad to help! What's involved in triaging it? :)

**Comment by eseidelGoogle** [comment]
This should be possible today.

**Comment by Hixie** [comment]
This is possible whenever, but I don't think we need a bug to track it. If we want to do it we should just do it.
