### ISSUE TITLE
flutter_gallery__transition_perf regressed

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#35296]
flutter_gallery__transition_perf average_frame_rasterizer_time_millis and 90th_percentile_frame_rasterizer_time_millis regressed since https://github.com/flutter/flutter/commit/43b03127d469f1f6d9a22f8dae41eea2eed2afd9

**Comment by liyuqian** [comment]
CC @dnfield as https://github.com/flutter/engine/pull/9503 seems to be the major suspect.

**Comment by dnfield** [comment]
We could experiment with increasing that cache size, although I don't think we can safely go back to the 512mb scenario.

**Comment by dnfield** [comment]
It looks like flutter/engine@63c2c3316d667e7677782d10be57982dd4a7595c did introduce at least part of this regression, but the regression appears to have gotten worse at some other point as well.  Still investigating.

**Comment by dnfield** [comment]
It also looks like that same commit showed an _improvement_ for frame build times.

**Comment by dnfield** [comment]
The skia revert:

```
    "missed_transition_count": 1,
    "average_frame_build_time_millis": 5.182537675606641,
    "90th_percentile_frame_build_time_millis": 10.572,
    "99th_percentile_frame_build_time_millis": 48.011,
    "worst_frame_build_time_millis": 107.994,
    "missed_frame_build_budget_count": 55,
    "average_frame_rasterizer_time_millis": 7.102525445292616,
    "90th_percentile_frame_rasterizer_time_millis": 11.587,
    "99th_percentile_frame_rasterizer_time_millis": 35.603,
    "worst_frame_rasterizer_time_millis": 93.946,
    "missed_frame_rasterizer_budget_count": 31,
    "frame_count": 783,
```

The caching commit:

```
    "missed_transition_count": 0,
    "average_frame_build_time_millis": 4.77816709183674,
    "90th_percentile_frame_build_time_millis": 10.104,
    "99th_percentile_frame_build_time_millis": 45.452,
    "worst_frame_build_time_millis": 96.054,
    "missed_frame_build_budget_count": 53,
    "average_frame_rasterizer_time_millis": 7.919531806615775,
    "90th_percentile_frame_rasterizer_time_millis": 14.797,
    "99th_percentile_frame_rasterizer_time_millis": 33.628,
    "worst_frame_rasterizer_time_millis": 104.201,
    "missed_frame_rasterizer_budget_count": 61,
    "frame_count": 784,
```

**Comment by dnfield** [comment]
Going to lower the severity of this - the regression seems real, but also needed.  We can leave open to continue investigating to see if we can get a better handle on this.

**Comment by liyuqian** [comment]
Agreed with Dan in an offline discussion. PR https://github.com/flutter/engine/pull/9503 fixes some crashing issues so we need it.

**Comment by liyuqian** [comment]
@dnfield : shall we close this (as an acceptable tradeoff), or do you have a plan to improve the performance?

**Comment by dnfield** [comment]
The only way I can think of to improve this is to run the benchmark with a larger cache again.  I'm not sure that is worthwhile.

**Comment by liyuqian** [comment]
Ok, then I'll close this issue for now as we're unlikely to act on it.
