### ISSUE TITLE
Clipboard action popup on iOS doesn't quite match 

### ISSUE THREAD

**Issue by miguelpruivo** [flutter/flutter#35300]
Fidelity wise speaking, if you take a look to the native iOS popup (`UIMenuController`) and to the Flutter _"copy"_, you can spot a few differences.

## iOS UIMenuController
![1*VHhWyc6QAQBXiYATqRHIXQ](https://user-images.githubusercontent.com/27860743/60376752-e3932d00-9a08-11e9-9024-a523c38a6f90.png)

## Flutter version
![Screenshot 2019-06-28 at 23 58 34](https://user-images.githubusercontent.com/27860743/60376768-fd347480-9a08-11e9-80fc-d776b56b2a15.png)

1. The text font is not quite the same;
2. There's a visible white line between the arrow and the options;
3. When you are selecting with 3D touch (swipe on keyboard) you can't press even further to start selecting the text, like you can natively.

**Comment by mikhail-tokarev** [comment]
hi @miguelpruivo 
are you still experiencing the issue with the latest Flutter stable release? 
if so, please provide the output of "flutter doctor -v"

**Comment by miguelpruivo** [comment]
I’m afraid that this one not, only #40628 that is related to this as well.
