### ISSUE TITLE
Horizontal trackpad gestures bypass NeverScrollableScrollPhysics

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#35304]
From within a Flutter application running on desktop, I'm using a TabBarView that looks something like this:
```
TabBarView(
    controller: controller,
    children: children,
    physics: NeverScrollableScrollPhysics(),
);
```
The NeverScrollableScrollPhysics seems to work as intended for most gestures. However, when I'm on a device with a trackpad (Macbook Pro), a two-finger horizontal scroll gesture causes the tabs to scroll. There doesn't seem to be a good way to prevent this behavior.

@stuartmorgan

**Comment by stuartmorgan** [comment]
Taking at least for initial investigation. There's a good chance I just never plumbed the necessary bits into the new branch of scrolling logic that was added for scroll gestures.

**Comment by gspencergoog** [comment]
@stuartmorgan are you still actively investigating this?

**Comment by stuartmorgan** [comment]
No, other things come up and I haven't looked into it. Unassigning for now.

**Comment by stuartmorgan** [comment]
Looked at this a bit; it may be as simple as adding a check for `physics.shouldAcceptUserOffset` in the scrollwheel code. The rest of the physics object wouldn't apply I believe, since there's no overscroll on scrollwheel, but I didn't realize that physics could also be used to disable scroll.
