### ISSUE TITLE
Firebase Transaction 

### ISSUE THREAD

**Issue by pekretsc** [flutter/flutter#35314]
Hi there 

I do not know if this is an old issue or if it is just me that can not find an answer. Firebase Transactions just do not seem to work in Flutter. I tried several ways read through Documentation(an extra Flutter section on the examples would be nice in the Firestore doc) But I just do not get it to work.
What I basically try to do is to add one to a counterValue (Like / Dislike) in my Firestore. I already found that some issues came from securety rules.... But I do not have any jet. So complet open to read and write.

Below are two different ways I tryed and both throw the same error which suprises me since I do not seem to be able to catch the error either.

There has not been a satisfying answer how to to use transactions. And if I did non see it and evrything  found is a year old. I would be glad if there is any advice?!
(Sorry for the unformatted code:( )

 newsRef = Firestore.instance.collection('News').document(news.newsID);

  Future<bool> addOneDislike() async {
    await newsRef.get().then((DocumentSnapshot snap) {
      count = snap.data['dislike'];
      if (count == null) {
        newsRef.updateData({'dislike': 1});
        return true;
      }
      count++;
      snap.data['dislike'] = count;
    }).then((_) async {
      try {
        await Firestore.instance.runTransaction((Transaction t) {
          t.update(newsRef, {'dislike': count});
        });
      } catch (e) {
        print('Transaction AddDislike failed');
        return false;
      }
    }).then((_) {
      return true;
    });
  }

  Future<bool> addOneLike() async {
    DocumentSnapshot doc = await newsRef.get();
    count = doc.data['like'];
    if (count == null) {
      newsRef.updateData({'like': 1});
      return true;
    }

    await Firestore.instance.runTransaction((Transaction t) {
      t.update(doc.reference, {'like': doc.data['like']++});
    }).catchError((e) {
      print(e.toString());
      return false;
    });
    return true;
}

E/flutter (13588): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(Error performing Transaction#update, Transaction has already completed., null)
E/flutter (13588): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (13588): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter (13588): <asynchronous suspension>
E/flutter (13588): #2      Transaction.update (package:cloud_firestore/src/transaction.dart:47:10)
E/flutter (13588): <asynchronous suspension>
E/flutter (13588): #3      NewsState.addOneLike.<anonymous closure> (package:ultimatecommunity/B_Blocs/NewsViewBloc.dart:96:9)
E/flutter (13588): #4      new Firestore.<anonymous closure> (package:cloud_firestore/src/firestore.dart:28:51)
E/flutter (13588): <asynchronous suspension>
E/flutter (13588): #5      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:383:55)
E/flutter (13588): <asynchronous suspension>
E/flutter (13588): #6      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:351:54)
E/flutter (13588): #7      BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:76:33)
E/flutter (13588): <asynchronous suspension>
E/flutter (13588): #8      _invoke3.<anonymous closure> (dart:ui/hooks.dart:263:15)
E/flutter (13588): #9      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (13588): #10     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (13588): #11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (13588): #12     _invoke3 (dart:ui/hooks.dart:262:10)
E/flutter (13588): #13     _dispatchPlatformMessage (dart:ui/hooks.dart:136:5)
E/flutter (13588): 
W/timatecommunit(13588): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (light greylist, linking)

**Comment by thevzurd** [comment]
I had the same problem. Try this. Hope it Helps 
[FIrestore Transaction Handler](https://github.com/thevzurd/Firestore-Transaction-Handler)
