### ISSUE TITLE
Atom is unable to locate cli tools (flutter, adb) when started from launchers on linux

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#3531]
Most likely the paths aren't set up w/ the settings from the user's login scripts. We'll need to detect when we're not running in the user's preferred shell, get the env variables from a login shell, and pass those in when shelling out to processes from atom. We have a similar workaround when atom is run from the mac dock (https://github.com/dart-atom/atom.dart/blob/master/lib/node/process.dart#L189).

**Comment by DaveShuckerow** [comment]
I encountered this in Ubuntu, running Atom from the system launcher.  My path and android-related environment variables are set up in my .bashrc.

**Comment by DaveShuckerow** [comment]
Additional info related to this: Running atom from command line, it's unable to detect when I reconnect a device.

**Comment by sethladd** [comment]
Thanks for the update!

**Comment by devoncarew** [comment]
@DaveShuckerow, the latest plugin version has a potential fix for this issue. Can you upgrade, quit atom, and try launching it from the system launcher to re-test? Thanks in advance!

**Comment by DaveShuckerow** [comment]
@devoncarew I haven't seen a flutter plugin update lately.  I updated the dartlang plugin, and I still have both problems I mentioned above -- running from the launcher fails to detect any connected devices, and running from command line doesn't detect devices connected after Atom starts.

**Comment by devoncarew** [comment]
The fix would have been in the latest dartlang plugin; thanks for checking it. Can you run `flutter doctor` from the command-line, and the atom command `flutter doctor` (available from atom's command pallette)? That will give me a point of comparison. You can PM me the info if you like.

**Comment by DaveShuckerow** [comment]
Sent.

**Comment by sethladd** [comment]
Going to close this in favor of the IntelliJ plugin.
