### ISSUE TITLE
怎么设置 TextField 的黏贴复制弹出框的位置，内容被挡住了

### ISSUE THREAD

**Issue by mx4g** [flutter/flutter#35319]
怎么设置 TextField 的黏贴复制弹出框的位置，内容被挡住了
如果想自定义黏贴复制的功能，该怎么实现。

translate：
How to set the location of the paste copy pop-up box of TextField, the content is blocked
If you want to customize the function of paste copy, how to implement it.

pic: https://github.com/mx4g/flutter_demo/blob/master/lib/gif/input.png
demo: https://github.com/mx4g/flutter_demo

**Comment by LongCatIsLooong** [comment]
Could you attach the output of `flutter doctor -v`? 
As for customizing the text edit tooltip, unfortunately you'll probably have to subclass `EditableText` in order to provide your own `TextSelectionControl` implementation.
