### ISSUE TITLE
didn't connet firebase to flutter app.

### ISSUE THREAD

**Issue by unitedmusic** [flutter/flutter#35312]
i will see this problem when i will connect firebase to my flutter app. 
**The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.**
can anyone help me to solve this problem.
Thank You.

**Comment by mikhail-tokarev** [comment]
hi @unitedmusic 
are you still experiencing the issue with the latest Flutter stable release? 
if so, please provide the output of "flutter doctor -v"

**Comment by unitedmusic** [comment]
No i have successfully connect my application to firebase

**Comment by mikhail-tokarev** [comment]
thank you @unitedmusic 
I think it's safe to close this issue,
if you disagree please write in the comments and I will reopen it.
