### ISSUE TITLE
Flutter App stopped working (only for Android)

### ISSUE THREAD

**Issue by Loopex2019** [flutter/flutter#35322]
Hi There, I am really getting fed up with this Problem . Every Time i start Debugging the App the App Closes which really waste time for Me and can not develop the App in a good way . But of course i have an error but i don't understand it :

`D/libGLESv2(23887): STS_GLApi : DTS, ODTC are not allowed for Package : com.example.looper
F/libc    (23887): Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 23907 (1.ui), pid 23887 (.example.looper)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/j7veltedx/j7velte:8.1.0/M1AJQ/J701FXXS6BSC1:user/release-keys'
Revision: '3' ABI: 'arm'
pid: 23887, tid: 23907, name: 1.ui  >>> com.example.looper <<<
signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
    r0 ce0814a4  r1 ce0814f0  r2 7f992402  r3 00000008
    r4 b191309a  r5 7f992402  r6 7f992402  r7 b08e26ce
    r8 7f992402  r9 b1913e6e  sl b080389a  fp b08194d6
    ip cf1702cc  sp b19129ca  lr b164e94f  pc f07a2b80  cpsr 600b0010
backtrace: #00 pc 00018b80  /system/lib/libc.so (sigsetjmp+116)
    #01 pc b164e94d  <unknown>
Lost connection to device.
Exited (sigterm)
`

**Comment by jabirishaq** [comment]
same issue since start of this week

**Comment by Loopex2019** [comment]
I used wireless debugging for that . 
You can check out this link here : 
https://www.fonepaw.com/usb/enable-usb-debugging-screen-broken-android.html

**Comment by aryalg** [comment]
Location is turned off on your phone! Turn on location. Worked for me.
