### ISSUE TITLE
Index sidebar on web site has many colors

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3532]
It's not clear when reading the FAQ that I'm at the FAQ:

![index](https://cloud.githubusercontent.com/assets/551196/14796648/4b7d983c-0ae3-11e6-97da-0171c70ffada.png)

There's the blue-on-grey links (some of which apparently open up).
There's the blue-highlighted section (which is what I thought I was actually looking at, initially). It has on "open up" triangle but it's not clear that it's actually open since the arrow is the same as the previous rows and the lines below it don't seem to be "part of" the Helpful Resources section.
There's blue links and black links. I'm not sure how they differ.
There's the greyed-out FAQ line. I assumed that was a non-interactive section header.

cc @qchong @sethladd

**Comment by qchong** [comment]
Looks like this has been fixed.
