### ISSUE TITLE
How to fix Unhandled Exception: type 'Future<void>' is not a subtype of type 'Future<Photography>'

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#35327]
I need to get all the data from the firestore database.

```
     Future<Photography> getPhotography() {
      Future<Photography> data = db.collection('photography')
            .document('0yUc5QBGHNNq6WK9CyyF')
            .setData(jsonDecode(jsonEncode(Photography())));

    return data;
    }
```

The error message is:

>  Unhandled Exception: type 'Future< void >' is not a subtype of type
>  'Future< Photography> '

**And next problem is, how to add to these data on bloc sink?**

    `  Sink<Photography> get inFirestore => _firestoreController.sink;`
something like this? but **error is, The argument type 'Future<Photography>' can't be assigned to the parameter type 'Photography'**

 ```
   final result = db.getPhotography();
    inFirestore.add(result);

```

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
