### ISSUE TITLE
CupertinoSliverNavigationBar and Material(BubbleBottomBar) at once

### ISSUE THREAD

**Issue by maximilianscheffel** [flutter/flutter#35326]
Hi,
i want to create an app with an CupertinoSliverNavigationBar as a Header and an BubbleBottomBar as a Bottom Navigation bar. I don't no how. Please help me :/

**Comment by darshankawar** [comment]
Hi @maximilianscheffel,
Is this question still valid ? Have you found the solution to your question ?
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
