### ISSUE TITLE
Connectivity plugin needs to update for iOS 13 due to the change in CNCopyCurrentNetworkInfo API

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#35332]
Quoted:
``` 
In iOS 13 the CNCopyCurrentNetworkInfo C function will return nil under most circumstances, 
except in some fairly restrictive cases. 
More on this in this thread on the Apple Developers forum for further explorations. 
This means apps may no longer be able to get network info 
(most commonly the Wi-Fi network SSID) with the same set of permissions in iOS 13.

CNCopyCurrentNetworkInfo is now only available to apps in three cases:
Apps with permission to access location
When the app is the currently enabled VPN app
When the app configured the WiFi network the device is currently using via NEHotspotConfiguration
```

Our connectivity plugin is using the `CNCopyCurrentNetworkInfo` API so looks like we will need a solution to handle this. Or maybe update the document on connectivity plugin to add location permission.

**Comment by danwulff** [comment]
More info was provided within an email that I received:

![image](https://user-images.githubusercontent.com/17821843/62644908-167dea00-b900-11e9-9d03-18752f8608c9.png)

It seems like the Readme should at least be updated to include information for how the change will affect iOS 13 users.

**Comment by cyanglaz** [comment]
@danwulff That sounds fair! Do you want to create a PR for adding this info to README? I would be happy to review it!

**Comment by danwulff** [comment]
@cyanglaz I created a PR (as seen above)

As well as a followup issue for requesting a feature change to support getting valid SSID and BSSID on iOS 13 #37804

**Comment by cyanglaz** [comment]
dup with https://github.com/flutter/flutter/issues/37804, closing this issue.
