### ISSUE TITLE
Custom exception class for network image failure

### ISSUE THREAD

**Issue by matanshukry** [flutter/flutter#35333]
## Use case

I'm loading an image from the network, and it is possible that the image won't exist, at which point I'll get back 404. I want to display a specific widget if I get back 404, unlike any other http error/status code.

Currently, I need to check the string message for "statusCode: ${response?.statusCode}" and extract the status code from it.

## Proposal

Use a custom exception class and give it the status code, which can be caught and cast and then easily extract the status code from it.

**Comment by BondarenkoStas** [comment]
@matanshukry As the PR was merged, can the issue be closed?

**Comment by matanshukry** [comment]
Yeah; I should of done it back then my self, my bad. Thanks!
