### ISSUE TITLE
FAQ section headings are too large compared to body text

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3533]
This is from our FAQ:

![faq](https://cloud.githubusercontent.com/assets/551196/14796762/d68b5c70-0ae3-11e6-82d4-767fa1e33c17.png)

The section headers are three times bigger than the body text. That's hugely disproportionate and makes it hard to navigate.

**Comment by Hixie** [comment]
cc @qchong @sethladd

**Comment by sethladd** [comment]
Looks like `<h2>` are all the same size across the site.
