### ISSUE TITLE
palette_generator plugin state?

### ISSUE THREAD

**Issue by matanshukry** [flutter/flutter#35339]
I can't fully understand the state of the palette_generator plugin.

(1) It seems to be located in a different repo: https://github.com/flutter/packages , with it being the only plugin?
(2) It was last updated over a year ago
(3) It doesn't work with the current version of flutter, probably just outdated due to (2)

If it is outdated - is there a reason? that is, will a PR of updated working plugin into the flutter plugins repo be accepted?

**Comment by arpit** [comment]
This is fixed in PaletteGenerator v0.2.0. Can someone close this?

**Comment by matanshukry** [comment]
I didn't check it, but good to know.
Would still love to know about (1). Why are there 2 different repos for Flutter's core team plugins?

**Comment by stuartmorgan** [comment]
palette_generator is not a plugin in Flutter terminology, because it has no native code; see https://flutter.dev/docs/development/packages-and-plugins/developing-packages#package-types

flutter/plugins contains plugins, while flutter/packages contains non-plugin packages.
