### ISSUE TITLE
Cannot use cloud_firestore and image_picker, Build fails with exception

### ISSUE THREAD

**Issue by mausamRayamajhi** [flutter/flutter#35359]
I have enable 

1. multiDexEnabled true

2. dependencies {
    implementation 'com.android.support:multidex:1.0.3'
}
3. app the packages are uptodate

but, still i am getting build error = app:transformClassesWithMultidexlistForDebug

error messge =>

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: D:\IDE\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.5+2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\IDE\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.5+2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: D:\IDE\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.0+6\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

**Comment by awazgyawali** [comment]
Your log is missing a lot of error messages. Can you paste the errors beyond the last line in the description.

**Comment by mausamRayamajhi** [comment]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 36s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by mausamRayamajhi** [comment]
> Your log is missing a lot of error messages. Can you paste the errors beyond the last line in the description?

Launching lib\main.dart on Android SDK built for x86 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 36s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by mausamRayamajhi** [comment]
[        ] [        ] ->
+file:///D:/IDE/flutter/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.1.0/lib/src/generated/ascii_glyph_set.dart
[        ] [        ] ->
+file:///D:/IDE/flutter/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.1.0/lib/src/generated/unicode_glyph_set.dart
[        ] [        ] -> +file:///D:/IDE/flutter/.pub-cache/hosted/pub.dartlang.org/source_span-1.5.5/lib/src/colors.dart
[        ] [        ] -> f010490f-4c37-4361-86c8-b60fb1318e50 build\app.dill 0
[+1413 ms] [+2156 ms] Building bundle
[        ] [        ] Writing asset files to D:\WorkSpace\flutter\rental\build\app\intermediates\flutter\debug/flutter_assets
[ +899 ms] [ +901 ms] Wrote D:\WorkSpace\flutter\rental\build\app\intermediates\flutter\debug/flutter_assets
[        ] [   +8 ms] "flutter bundle" took 13,217ms.
[        ] [        ] "flutter bundle" took 13,217ms.
[ +100 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[   +1 ms] > Task :cloud_firestore:mergeDebugShaders UP-TO-DATE
[        ] > Task :cloud_firestore:compileDebugShaders UP-TO-DATE
[        ] > Task :cloud_firestore:generateDebugAssets UP-TO-DATE
[        ] > Task :cloud_firestore:packageDebugAssets UP-TO-DATE
[        ] > Task :firebase_core:mergeDebugShaders UP-TO-DATE
[        ] > Task :firebase_core:compileDebugShaders UP-TO-DATE
[        ] > Task :firebase_core:generateDebugAssets UP-TO-DATE
[        ] > Task :firebase_core:packageDebugAssets UP-TO-DATE
[        ] > Task :image_picker:mergeDebugShaders UP-TO-DATE
[        ] > Task :image_picker:compileDebugShaders UP-TO-DATE
[   +3 ms] > Task :image_picker:generateDebugAssets UP-TO-DATE
[   +5 ms] > Task :image_picker:packageDebugAssets UP-TO-DATE
[  +42 ms] > Task :path_provider:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :path_provider:compileDebugShaders UP-TO-DATE
[        ] > Task :path_provider:generateDebugAssets UP-TO-DATE
[  +35 ms] > Task :path_provider:packageDebugAssets UP-TO-DATE
[   +1 ms] > Task :shared_preferences:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :shared_preferences:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :shared_preferences:generateDebugAssets UP-TO-DATE
[        ] > Task :shared_preferences:packageDebugAssets UP-TO-DATE
[   +3 ms] > Task :sqflite:mergeDebugShaders UP-TO-DATE
[   +4 ms] > Task :sqflite:compileDebugShaders UP-TO-DATE
[        ] > Task :sqflite:generateDebugAssets UP-TO-DATE
[   +1 ms] > Task :sqflite:packageDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +384 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:processDebugGoogleServices
[        ] Parsing json file: D:\WorkSpace\flutter\rental\android\app\google-services.json
[ +185 ms] > Task :cloud_firestore:compileDebugRenderscript UP-TO-DATE
[  +21 ms] > Task :cloud_firestore:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :cloud_firestore:generateDebugResources UP-TO-DATE
[   +1 ms] > Task :cloud_firestore:packageDebugResources UP-TO-DATE
[   +1 ms] > Task :firebase_core:compileDebugRenderscript UP-TO-DATE
[        ] > Task :firebase_core:generateDebugResValues UP-TO-DATE
[        ] > Task :firebase_core:generateDebugResources UP-TO-DATE
[   +1 ms] > Task :firebase_core:packageDebugResources UP-TO-DATE
[  +82 ms] > Task :image_picker:compileDebugRenderscript UP-TO-DATE
[   +1 ms] > Task :image_picker:generateDebugResValues UP-TO-DATE
[        ] > Task :image_picker:generateDebugResources UP-TO-DATE
[        ] > Task :image_picker:packageDebugResources UP-TO-DATE
[  +96 ms] > Task :path_provider:compileDebugRenderscript UP-TO-DATE
[   +1 ms] > Task :path_provider:generateDebugResValues UP-TO-DATE
[        ] > Task :path_provider:generateDebugResources UP-TO-DATE
[        ] > Task :path_provider:packageDebugResources UP-TO-DATE
[        ] > Task :shared_preferences:compileDebugRenderscript UP-TO-DATE
[        ] > Task :shared_preferences:generateDebugResValues UP-TO-DATE
[        ] > Task :shared_preferences:generateDebugResources UP-TO-DATE
[  +94 ms] > Task :shared_preferences:packageDebugResources UP-TO-DATE
[        ] > Task :sqflite:compileDebugRenderscript UP-TO-DATE
[        ] > Task :sqflite:generateDebugResValues UP-TO-DATE
[        ] > Task :sqflite:generateDebugResources UP-TO-DATE
[ +198 ms] > Task :sqflite:packageDebugResources UP-TO-DATE
[ +199 ms] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:splitsDiscoveryTaskDebug UP-TO-DATE
[  +97 ms] > Task :cloud_firestore:generateDebugRFile UP-TO-DATE
[        ] > Task :firebase_core:generateDebugRFile UP-TO-DATE
[ +102 ms] > Task :image_picker:generateDebugRFile UP-TO-DATE
[        ] > Task :path_provider:generateDebugRFile UP-TO-DATE
[  +99 ms] > Task :shared_preferences:generateDebugRFile UP-TO-DATE
[   +1 ms] > Task :sqflite:generateDebugRFile UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:generateDebugSources UP-TO-DATE
[        ] > Task :cloud_firestore:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :cloud_firestore:prepareLintJar UP-TO-DATE
[        ] > Task :cloud_firestore:generateDebugSources UP-TO-DATE
[        ] > Task :cloud_firestore:javaPreCompileDebug UP-TO-DATE
[        ] > Task :cloud_firestore:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :cloud_firestore:processDebugJavaRes NO-SOURCE
[        ] > Task :cloud_firestore:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
[        ] > Task :firebase_core:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :firebase_core:prepareLintJar UP-TO-DATE
[        ] > Task :firebase_core:generateDebugSources UP-TO-DATE
[        ] > Task :firebase_core:javaPreCompileDebug UP-TO-DATE
[  +94 ms] > Task :firebase_core:compileDebugJavaWithJavac UP-TO-DATE
[   +2 ms] > Task :firebase_core:processDebugJavaRes NO-SOURCE
[   +1 ms] > Task :firebase_core:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
[   +1 ms] > Task :image_picker:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :image_picker:prepareLintJar UP-TO-DATE
[   +1 ms] > Task :image_picker:generateDebugSources UP-TO-DATE
[        ] > Task :image_picker:javaPreCompileDebug UP-TO-DATE
[        ] > Task :image_picker:compileDebugJavaWithJavac UP-TO-DATE
[   +2 ms] > Task :image_picker:processDebugJavaRes NO-SOURCE
[        ] > Task :image_picker:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
[        ] > Task :path_provider:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :path_provider:prepareLintJar UP-TO-DATE
[        ] > Task :path_provider:generateDebugSources UP-TO-DATE
[        ] > Task :path_provider:javaPreCompileDebug UP-TO-DATE
[        ] > Task :path_provider:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :path_provider:processDebugJavaRes NO-SOURCE
[        ] > Task :path_provider:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
[        ] > Task :shared_preferences:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :shared_preferences:prepareLintJar UP-TO-DATE
[   +1 ms] > Task :shared_preferences:generateDebugSources UP-TO-DATE
[        ] > Task :shared_preferences:javaPreCompileDebug UP-TO-DATE
[  +66 ms] > Task :shared_preferences:compileDebugJavaWithJavac UP-TO-DATE
[  +23 ms] > Task :shared_preferences:processDebugJavaRes NO-SOURCE
[        ] > Task :shared_preferences:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
[   +1 ms] > Task :sqflite:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :sqflite:prepareLintJar UP-TO-DATE
[        ] > Task :sqflite:generateDebugSources UP-TO-DATE
[        ] > Task :sqflite:javaPreCompileDebug UP-TO-DATE
[        ] > Task :sqflite:compileDebugJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :sqflite:processDebugJavaRes NO-SOURCE
[        ] > Task :sqflite:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
[   +1 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugNdk NO-SOURCE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[  +70 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[+3122 ms] > Task :app:transformClassesWithMultidexlistForDebug FAILED
[   +1 ms] 109 actionable tasks: 6 executed, 103 up-to-date
[   +1 ms]          *********************************************************
[   +1 ms] WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with
AndroidX.
[   +1 ms]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[        ]          *********************************************************
[ +194 ms] FAILURE: Build failed with an exception.
[   +6 ms] * What went wrong:
[        ] Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
[        ] > com.android.build.api.transform.TransformException: Error while generating the main dex list.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 23s
[ +320 ms] Running Gradle task 'assembleDebug'... (completed in 23.8s)
[   +3 ms] "flutter run" took 32,311ms.
[        ] "flutter run" took 32,311ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:478:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:346:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:377:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:364:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:428:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#15     Future._complete (dart:async/future_impl.dart:473:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#26     Future._complete (dart:async/future_impl.dart:473:7)
#27     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#28     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

**Comment by awazgyawali** [comment]
Have you migrated your app to androidX?

**Comment by mausamRayamajhi** [comment]
No

**Comment by mausamRayamajhi** [comment]
No .
Should i move to it
