### ISSUE TITLE
Assertion failed: is not true

### ISSUE THREAD

**Issue by vinayagg** [flutter/flutter#35351]
## Steps to Reproduce
Source code attached. Enter some text and press submit

```
import 'package:flutter_web/material.dart';

class AddRemoveListView extends StatefulWidget {
  _AddRemoveListViewState createState() => _AddRemoveListViewState();
}

class _AddRemoveListViewState extends State<AddRemoveListView> {
  TextEditingController _textController = TextEditingController();

  List<String> _listViewData = [
    "Swipe Right / Left to remove",
    "Swipe Right / Left to remove",
    "Swipe Right / Left to remove",
    "Swipe Right / Left to remove",
    "Swipe Right / Left to remove",
    "Swipe Right / Left to remove",
    "Swipe Right / Left to remove",
    "Swipe Right / Left to remove",
    "Swipe Right / Left to remove",
  ];

  _onSubmit() {
    print("submit pressed ${_textController.text}");
    setState(() {
      _listViewData.add("asdfasfa");
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Add & Remove from ListView'),
      ),
      body: Column(
        children: <Widget>[
          SizedBox(height: 15.0),
          TextField(
            controller: _textController,
            decoration: InputDecoration(
              hintText: 'enter text to add',
            ),
          ),
          SizedBox(height: 15.0),
          Center(
            child: RaisedButton(
              onPressed: _onSubmit,
              child: Text('Add to List'),
              color: Colors.red,
            ),
          ),
          SizedBox(height: 20.0),
          Expanded(
            child: ListView(
              padding: EdgeInsets.all(10.0),
              children: _listViewData.reversed.map((data) {
                return Dismissible(
                  key: Key(data),
                  child: ListTile(
                    title: Text(data),
                  ),
                );
              }).toList(),
            ),
          ),
        ],
      ),
    );
  }
}
```

## Logs

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
dart_sdk.js:18740 The following assertion was thrown building
dart_sdk.js:18740 RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#13867](state:
dart_sdk.js:18740 RawGestureDetectorState#fa625(gestures: [vertical drag], behavior: opaque)):
dart_sdk.js:18740 Assertion failed: is not true
dart_sdk.js:18740 
dart_sdk.js:18740 Either the assertion indicates an error in the framework itself, or we should provide substantially
dart_sdk.js:18740 more information in this error message to help you determine and fix the underlying cause.
dart_sdk.js:18740 In either case, please report this assertion by filing a bug on GitHub:
dart_sdk.js:18740   https://github.com/flutter/flutter/issues/new?template=BUG.md
dart_sdk.js:18740 
dart_sdk.js:18740 When the exception was thrown, this was the stack:
dart_sdk.js:18740 dart:sdk_internal 4495:15                                                                    assertFailed
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/rendering/sliver_multi_box_adaptor.dart 268:55  [_debugVerifyChildOrder]
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/rendering/sliver_multi_box_adaptor.dart 243:14  <fn>
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/rendering/sliver_multi_box_adaptor.dart 244:69  set debugChildIntegrityEnabled
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/sliver.dart 1163:20                     performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/sliver.dart 1091:54                     update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 5069:14                  update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4769:32                  updateChildren
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 5186:17                  update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/viewport.dart 197:11                    update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 5069:14                  update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 5069:14                  update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 5069:14                  update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 5069:14                  update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4055:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 5069:14                  update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4164:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 5069:14                  update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 5069:14                  update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 5069:14                  update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 5069:14                  update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3953:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4055:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4055:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4164:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3953:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4164:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4769:32                  updateChildren
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 5186:17                  update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4164:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4164:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4769:32                  updateChildren
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 5186:17                  update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4055:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4164:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4055:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 5069:14                  update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3953:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 5069:14                  update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4055:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4055:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4164:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4164:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 4055:5                   update
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2896:14                  updateChild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3908:16                  performRebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 3713:5                   rebuild
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/framework.dart 2347:31                  buildScope
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/widgets/binding.dart 710:49                     drawFrame
dart_sdk.js:18740 package:flutter_web/packages/flutter_web/src/rendering/binding.dart 286:5                    [_handlePersistentFrameCallback]
dart_sdk.js:18740 package:flutter_web/src/scheduler/packages/flutter_web/src/scheduler/binding.dart 1030:15    [_invokeFrameCallback]
dart_sdk.js:18740 package:flutter_web/src/scheduler/packages/flutter_web/src/scheduler/binding.dart 963:9      handleDrawFrame
dart_sdk.js:18740 package:flutter_web/src/scheduler/packages/flutter_web/src/scheduler/binding.dart 874:5      [_handleDrawFrame]
dart_sdk.js:18740 package:flutter_web_ui/packages/flutter_web_ui/src/engine.dart 163:21                        <fn>
dart_sdk.js:18740 ════════════════════════════════════════════════════════════════════════════════════════════════════

$ flutter analyze
Analyzing spinning_square...
No issues found! (ran in 1.8s)

$ flutter doctor -v
[√] Flutter (Channel unknown, v1.7.10, on Microsoft Windows [Version 10.0.17763.557], locale en-US)
    • Flutter version 1.7.10 at C:\tools\flutter
    • Framework revision 9a3a7490c8 (5 days ago), 2019-06-25 15:59:15 +0200
    • Engine revision ae8e6d9f46
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\vinay\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.1.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.1.29020.237

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.35.1)
    • VS Code at C:\Users\vinay\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (2 available)
    • Windows • Windows • windows-x64    • Microsoft Windows [Version 10.0.17763.557]
    • Chrome  • chrome  • web-javascript • Google Chrome 75.0.3770.100

• No issues found!

**Comment by ferhatb** [comment]
Is the same code working correctly in Flutter ? Web only failure?
