### ISSUE TITLE
How do I slide to a specified control location?

### ISSUE THREAD

**Issue by YourksChan** [flutter/flutter#35366]
`
/// 1、
GlobalKey key = GlobalKey();
RenderBox renderBox = key.currentContext.findRenderObject();
double dy = renderBox.localToGlobal(Offset.zero).dy;

/// 2、
ScrollController.jumpTo(dy);
`
I found that it is incorrect to jump the position obtained in step 1 in step 2.

**Comment by VladyslavBondarenko** [comment]
@YourksChan 
I hope you've solved the issue
(just to say https://api.flutter.dev/flutter/widgets/Scrollable/ensureVisible.html is probably what you needed)
