### ISSUE TITLE
futurebuilder cannot read data from subcollection

### ISSUE THREAD

**Issue by virtz** [flutter/flutter#35371]
i have an application that stores items user favorite in a subcollection tied to the document which is also the uid of the user.Trying to populate a future builder with the data from the subcollection does not yield the desired result

**Comment by BondarenkoStas** [comment]
@virtz 
Unfortunately, this report does not have any actionable information - it’s not clear if this is a bug in user code, a bug in the framework, or something else entirely.
Please feel free to comment and I will re-open if you can add the following information:
The version of Flutter you’re using
The output of flutter doctor -v
The full exception you see or the result
A minimal reproduction that leads to this exception.
