### ISSUE TITLE
Firebase messaging -> onMessage() not working on iOS

### ISSUE THREAD

**Issue by kleinpetr** [flutter/flutter#35375]
When I push NOTIFICATION via firebase and app is foreground, the callback onMessage() not fired. When I push only DATA message, its working ok.

**Comment by lgfranco** [comment]
Cold you share more data about your current problem?
I'm developing a iOS app and I current don't have this issue.
You can use this to debug your push in console, im my iPhone on iOS 12.3.1, it's working as expected...

```
    _firebaseMessaging.autoInitEnabled().then((bool enabled) => print(enabled));
    _firebaseMessaging.setAutoInitEnabled(true).then((_) => _firebaseMessaging
        .autoInitEnabled()
        .then((bool enabled) => print(enabled)));
    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print("onMessage: $message");
      },
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch: $message");
      },
      onResume: (Map<String, dynamic> message) async {
        print("onResume: $message");
      },
    );
    _firebaseMessaging.requestNotificationPermissions(
        const IosNotificationSettings(sound: true, badge: true, alert: true));
    _firebaseMessaging.onIosSettingsRegistered
        .listen((IosNotificationSettings settings) {
      print("Settings registered: $settings");
    });
    _firebaseMessaging.onTokenRefresh.listen((data) {
      print('Refresh Token: $data');
    }, onDone: () => print('Refresh Token Done'));
    _firebaseMessaging.getToken().then((String token) {
      assert(token != null);
      _authenticationBloc.dispatch(SetPushToken(pushToken: token));
      print("Push Messaging token: $token");
    });
```

**Comment by kleinpetr** [comment]
I have the similar code (without autoInit) and when the app is on background notification was received as well. But when the app is opened, and I send notification with data, the onMessage() callback not fired. no print, no debug. nothing. When I send only data message without notification attributes, then working fine..

**Comment by lgfranco** [comment]
Sent message:
`flutter: onMessage: {from: ID, collapse_key: PROJECT_NAME notification: {body: This should appear on iOS, title: Test Text Notification, e: 1, tag: campaign_collapse_key_NUMBER}}`

Sent Message with data:
flutter: onMessage: {from: ID, AnOther: Data2, notification: {body: It should apear on iOS as well, title: This message contains data, e: 1, tag: campaign_collapse_key_NUMBER}, collapse_key: PROJECT_NAME, Some: Data}


I used the firebase console to sent this two push messages. This is the console output with the open app.

**Comment by harshshredding** [comment]
Had the same problem. Apparently, everything is working fine on the iOS Simulator for me - the three callbacks are being called. However, when I am debugging on device, it seems like the callbacks are not being registered properly. Don't know if this is a debugger issue, or the phone model issue.

**Comment by hussien4321** [comment]
I have also noticed this issue, the notifications are displayed in the notification tray if the app is not in the foreground (as expected), if the app is in the foreground when the notification is received however, then the onMessage function is not triggered at all.

**Comment by JaspervanRiet** [comment]
This and #36201 are the same issue I believe.

**Comment by ThinkDigitalSoftware** [comment]
> This and #36201 are the same issue I believe.

yes it is. Thanks for the link

**Comment by ThinkDigitalSoftware** [comment]
I'm having this issue as well.
I'm also getting no notification sound and all my sounds and notifications are enabled for this app and device and IosNotificationSettings()
> Flutter 1.8.3 • channel beta • https://github.com/flutter/flutter.git
> Framework • revision e4ebcdf6f4 (5 weeks ago) • 2019-07-27 11:48:24 -0700
> Engine • revision 38ac5f30a7
> Tools • Dart 2.5.0 (build 2.5.0-dev.1.0 0ca1582afd)

**Comment by obogz** [comment]
Guys, the problem is the Local Notifications plug in or any other plug in that uses notifications:


From local notifications plugin readme

> NOTE: this plugin registers itself as the delegate to handle incoming notifications and actions. This may cause problems if you're using other plugins for push notifications (e.g. firebase_messaging) as they will most likely do the same and it's only possible to register a single delegate. iOS handles showing push notifications out of the box so if you're only using this plugin to display the notification payload on Android then it's suggested that you fork the plugin code and remove the following part in the iOS code
> 
> UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
> center.delegate = instance;
> Unfortunately, this platform limitation does mean that it's not possible to use this plugin together other plugins for push notifications on iOS. If you are in this situation, then my only advice is that you'll need to need to look at writing customised platform-specific code for your application that may involve taking bits and pieces of code from the plugins you need.

**Comment by ThinkDigitalSoftware** [comment]
WOW! Thank you for finding this!


> Guys, the problem is the Local Notifications plug in or any other plug in that uses notifications:
> 

WOW! Thank you for finding this!

**Comment by sooxiaotong** [comment]
what's the ETA for this fix to release?

**Comment by nachiketkhasbag** [comment]
> Guys, the problem is the Local Notifications plug in or any other plug in that uses notifications:
> 
> From local notifications plugin readme
> 
> > NOTE: this plugin registers itself as the delegate to handle incoming notifications and actions. This may cause problems if you're using other plugins for push notifications (e.g. firebase_messaging) as they will most likely do the same and it's only possible to register a single delegate. iOS handles showing push notifications out of the box so if you're only using this plugin to display the notification payload on Android then it's suggested that you fork the plugin code and remove the following part in the iOS code
> > UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
> > center.delegate = instance;
> > Unfortunately, this platform limitation does mean that it's not possible to use this plugin together other plugins for push notifications on iOS. If you are in this situation, then my only advice is that you'll need to need to look at writing customised platform-specific code for your application that may involve taking bits and pieces of code from the plugins you need.

This worked for me too.
But if you not use local notifications, how do you handle notifications when app is in foreground?

**Comment by RashidaBegamShaik** [comment]
> > Guys, the problem is the Local Notifications plug in or any other plug in that uses notifications:
> > From local notifications plugin readme
> > > NOTE: this plugin registers itself as the delegate to handle incoming notifications and actions. This may cause problems if you're using other plugins for push notifications (e.g. firebase_messaging) as they will most likely do the same and it's only possible to register a single delegate. iOS handles showing push notifications out of the box so if you're only using this plugin to display the notification payload on Android then it's suggested that you fork the plugin code and remove the following part in the iOS code
> > > UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
> > > center.delegate = instance;
> > > Unfortunately, this platform limitation does mean that it's not possible to use this plugin together other plugins for push notifications on iOS. If you are in this situation, then my only advice is that you'll need to need to look at writing customised platform-specific code for your application that may involve taking bits and pieces of code from the plugins you need.
> 
> This worked for me too.
> But if you not use local notifications, how do you handle notifications when app is in foreground?

thank u too much for the solution @obogz ... this worked for me

**Comment by awaik** [comment]
Finally found the decision here https://stackoverflow.com/questions/64172280/flutter-fcm-on-ios-14
