### ISSUE TITLE
I hope that CupertinoApp can also have a tabBar similar to materialApp.

### ISSUE THREAD

**Issue by djkloop** [flutter/flutter#35387]
## Use case
If the application only needs to support ios, you can add a tabBar similar to the MaterialApp effect. This component is still very common.

## Proposal
```
https://pub.dartlang.org
```
The package market does not seem to have similar components based on the MaterialApp package.

**Comment by LongCatIsLooong** [comment]
Is this what you are looking for? https://api.flutter.dev/flutter/cupertino/CupertinoTabScaffold-class.html

**Comment by djkloop** [comment]
@LongCatIsLooong 

Is a component of the tabbar in the top style like the materialapp

**Comment by LongCatIsLooong** [comment]
The [iOS human interface guideline](https://developer.apple.com/design/human-interface-guidelines/ios/bars/tab-bars/) suggests that a tab bar should stick to the bottom of the screen. Unfortunately a cupertino component that doesn't follow Apple's HIG is very unlikely a good candidate of what would be shipped in the cupertino library.

FWIW if an app is only targeting iOS then it's probably a good idea to embrace the guideline.
That said it should still be possible to use a `CupertinoTabBar` and position it under the navigation bar, which sounds pretty straightforward.
