### ISSUE TITLE
How to catch URL / Text from share intent

### ISSUE THREAD

**Issue by niteshkumarniranjan** [flutter/flutter#35383]
I am building an app which can catch all the URLs from share intent and save it to a DB. but I can only share text not URLs.
Also, each share opens a new instance of the app.

**Comment by mikhail-tokarev** [comment]
hi @niteshkumarniranjan 
are you still experiencing the issue with the latest Flutter stable release? 
if so, please provide the output of "flutter doctor -v"

**Comment by niteshkumarniranjan** [comment]
I haven't checked yet.
using https://github.com/d-silveira/flutter-share as of now.

**Comment by janmoppel** [comment]
Hi @niteshkumarniranjan !

As you found the solution for now, closing this issue. 
However, feel free to open a new issue if you still encounter the same problem.
