### ISSUE TITLE
Task 'assemble' not found in root project 

### ISSUE THREAD

**Issue by wxy520ll** [flutter/flutter#35389]
when i open the project, i often am told “Task 'assemble' not found in root project ”  by as,when i build the project。![](https://i.loli.net/2019/07/01/5d197d92d15f898035.jpg)
![](https://i.loli.net/2019/07/01/5d197e1ba0dd457528.jpg)

**Comment by mikhail-tokarev** [comment]
hi @wxy520ll 
I see from your Flutter doctor that
 - you need to accept Android license, you can proceed as described [here](https://github.com/flutter/flutter/issues/16025#issuecomment-377083808)
-  also also need to install Flutter plugins, please follow this [documentation](https://flutter.dev/docs/get-started/editor)

I think it's safe to close this issue,
if you disagree please write in the comments and I will reopen it.
