### ISSUE TITLE
Crashlytics dashboard is always empty

### ISSUE THREAD

**Issue by billmeireles** [flutter/flutter#35386]

**Comment by kuadratica** [comment]
Hello,

Please, someone help me.

I put the code below in my "onPressed" action:

Crashlytics.instance.crash();

And I see in my log details:

I/flutter (13693): Error caught by Crashlytics plugin:
I/flutter (13693): Error reported to Crashlytics.

After moments, my log wrote the line below:

I/CrashlyticsCore(13693): Crashlytics report upload complete: 7G885HNF991B-9991-71D2-AC40101597262

So, my Crashlytics dashboard is always empty. I tried in my mobile device and the behavior is the same.
This crash never is showed in my Crashlytics dashboard.

Thank you.

Below is my attached.

![empty crashlytics](https://user-images.githubusercontent.com/5361348/60405573-69d57d80-9b87-11e9-9142-cc63a3e3172f.png)

**Comment by ketanm** [comment]
There are few things possible:

- If you were using Crashlytics earlier then did you migrate it to Firebase? It is a simple process on their side which starts sending data to firebase (console view that you shared above)
- There is no project setup and an app that you are setting up does not have Crashlytics configured. Make sure it is done correctly and you have correct fabric.ApiKey in your Android manifest.

**Comment by mikhail-tokarev** [comment]
hi @billmeireles 
are you still experiencing the issue with the latest Flutter stable release? 
if so, please provide the output of "flutter doctor -v"

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
