### ISSUE TITLE
SwitchListTile.adaptive has splash effect on iOS

### ISSUE THREAD

**Issue by miguelpruivo** [flutter/flutter#35399]
The [`SwitchListTile.adaptive`](https://api.flutter.dev/flutter/material/SwitchListTile/SwitchListTile.adaptive.html) shouldn't have a splash effect (from Material) on iOS devices (eg. when providing the `CupertinoSwitch`), which currently does.

```
Flutter (Channel unknown, v1.7.11, on Mac OS X 10.14.5 18F132, locale pt-PT)
    • Flutter version 1.7.11 at /Users/miguelruivo/DevTools/flutter
    • Framework revision 43b03127d4 (4 days ago), 2019-06-26 23:27:39 -0400
    • Engine revision f3761ba8d0
    • Dart version 2.4.0
```

**Comment by TahaTesser** [comment]
This issue still exist

<img width="418" alt="Screenshot 2020-03-26 at 5 18 36 PM" src="https://user-images.githubusercontent.com/48603081/77643793-fd58a500-6f85-11ea-9131-9d35a182e5ba.png">

**Comment by LongCatIsLooong** [comment]
I can't find any specific guidelines on material.io that state the ink splash effect should be disabled/enabled based on the platform. IMO the splash is a part of the design language, not a platform mechanism, thus should remain consistent across platforms. `SwitchListTile` is a material widget, and it should show the splash like other `ListTile`s do, even on iOS/macOS.

@nero-angela @miguelpruivo WDYT?

**Comment by nero-angela** [comment]
> I can't find any specific guidelines on material.io that state the ink splash effect should be disabled/enabled based on the platform. IMO the splash is a part of the design language, not a platform mechanism, thus should remain consistent across platforms. `SwitchListTile` is a material widget, and it should show the splash like other `ListTile`s do, even on iOS/macOS.
> 
> @nero-angela @miguelpruivo WDYT?

@LongCatIsLooong At first, I thought `SwitchListTile.adaptive` on iOS or macOS should not have `InkWell` because it is a Material component. However, when I read your comment and look at the code again, I found that `InkWell` belongs to the `ListTile` and it does not have different implementation cases depending on the platform like `Switch.adaptive`. 
So I think we can fix this issue correctly after widgets like `ListTile.adaptive` or `CupertinoListTile` come out.

**Comment by miguelpruivo** [comment]
@LongCatIsLooong I got your point, and in a way, it makes sense. However, for iOS users, having splash effects strictly looks and feels like a Material component which on its turn usually doesn’t have Cupertino elements.

This is kinda twisted here because we have a material widget with a Cupertino. I’d say that the right solution would be either presenting a Cupertino list tile (without the inkwell) or the Material list title, but anything that conforms to `adaptive` should behave as much as possible to its own guidelines, hence, not having the splash on iOS.

**Comment by LongCatIsLooong** [comment]
Sorry for the late reply. 

I would like to think the "adaptive" switch list tile does not produce a Cupertino widget on macOS/iOS, but rather a Material widget with iOS/macOS platform adaptation: https://material.io/design/platform-guidance/cross-platform-adaptation.html#cross-platform-guidelines.

**Comment by LongCatIsLooong** [comment]
Found the initial issue that prompted the `adaptive` constructor to be added: https://github.com/flutter/flutter/issues/22101. It looks like historically it was added to help with meeting the material platform adaptation guideline. But it's hard to tell from the docs (and it's really subtle). I think we should clarify that in the API docs. 

There's an existing issue for adding a `UITableViewCell` equivalent: https://github.com/flutter/flutter/issues/19228.
