### ISSUE TITLE
When device rotated - orientation is wrong

### ISSUE THREAD

**Issue by SmokeVLG** [flutter/flutter#35397]
I'm trying to follow the camera lesson. - https://flutter.dev/docs/cookbook/plugins/picture-using-camera . 
When I rotate the screen, the image is rotated wrong.
![Скрин1](https://user-images.githubusercontent.com/1797380/60427251-5833ba80-9c07-11e9-8b77-efdfdd2f9afc.png) when auto rotate is enabled ?

**Comment by mikhail-tokarev** [comment]
I see the resolution is ongoing through referenced issue,
please follow the aforementioned; I'm closing the present.
If you disagree, please write in the comments and I will reopen the issue.
