### ISSUE TITLE
SafeArea for Pixel 3 XL Too Small

### ISSUE THREAD

**Issue by jackschedel** [flutter/flutter#35403]
I don't know if there are any other phones where this happens, but it seems the container created by the SafeArea Widget is not small enough. The notch still partially bites into the application.

To Reproduce:
1. Create Emulator Profile for Pixel 3 XL
2. Use a SafeArea Widget in code (I also filled it with a teal colored Container)
3. Run the program, and use Flutter Inspector to most easily see it

As you can see in the attached image, roughly half the notch is still in the SafeArea.

![image](https://user-images.githubusercontent.com/26682594/60443868-16484b80-9bea-11e9-8890-9c14651aeab6.png)
![image](https://user-images.githubusercontent.com/26682594/60443917-2bbd7580-9bea-11e9-96b1-39b8832ba364.png)

**Comment by ds84182** [comment]
I think that's an emulator bug, since the status bar is also incorrect.

**Comment by jackschedel** [comment]
> I think that's an emulator bug, since the status bar is also incorrect.

I'm on Oreo 8.1 not the latest Android version that might be why the status bar looks different.
If someone has a physical Pixel 3 XL they should try it to see if its an emulator bug.

**Comment by TahaTesser** [comment]
Hi @jackschedel 
This seems to resolved and looks like more like emulator than Flutter issue

![image](https://user-images.githubusercontent.com/48603081/75334170-624cac80-58ad-11ea-8e00-09f3d18f39f8.png)

Given the test in the screenshot, i feel free to close this issue 
if you disagree please write in the comments and I will reopen it 
Thank you
