### ISSUE TITLE
 No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

### ISSUE THREAD

**Issue by helloworkcupid** [flutter/flutter#35400]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```
rror running Gradle:
ProcessException: Process "E:\DemoAll\serven\Flutter-Notebook-master\mecury_project\example\animation_demo\android\gradlew.bat" exited abnormally:
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\DemoAll\serven\Flutter-Notebook-master\mecury_project\example\animation_demo\android\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

* Try:

**Comment by mikhail-tokarev** [comment]
hi @helloworkcupid 
are you still experiencing the issue with the latest Flutter stable release? 
if so, please provide the output of "flutter doctor -v"

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
