### ISSUE TITLE
type 'RenderSliverList' is not a subtype of type 'RenderBox'

### ISSUE THREAD

**Issue by YourksChan** [flutter/flutter#35401]
```
type 'RenderSliverList' is not a subtype of type 'RenderBox'

type '_RenderSliverPinnedPersistentHeaderForWidgets' is not a subtype of typ

SliverAppBar(key: GlobalKey()) or SliverList(key: GlobalKey())


RenderBox rb = key.currentContext.findRenderObject();
double dy = rb.localToGlobal(Offset.zero).dy;
```

**Comment by shihaohong** [comment]
Hi, RenderSliver follows a different protocol from RenderBox. You'll need to update the your `RenderBox` reference to `RenderSliver`.

For more info, see https://api.flutter.dev/flutter/rendering/RenderObject-class.html

**Comment by Y-ndm** [comment]
How to get the; 

key.currentContext.findRenderObject();
rb.localToGlobal(Offset.zero).dy;

of a RenderSliver it looks like they're not there.
Best regards.

**Comment by singun-lxd** [comment]
> How to get the;
> 
> rb.localToGlobal(Offset.zero).dy;
> rb.size.height;
> 
> of a RenderSliver. It looks like they're not there.
> Best regards.

you can copy the implement of `RenderBox.globalToLocal`, this is my version:

static Offset globalToLocal(RenderObject object, Offset point, { RenderObject ancestor }) {
    final Matrix4 transform = object.getTransformTo(ancestor);
    final double det = transform.invert();
    if (det == 0.0)
      return Offset.zero;
    final Vector3 n = Vector3(0.0, 0.0, 1.0);
    final Vector3 i = transform.perspectiveTransform(Vector3(0.0, 0.0, 0.0));
    final Vector3 d = transform.perspectiveTransform(Vector3(0.0, 0.0, 1.0)) - i;
    final Vector3 s = transform.perspectiveTransform(Vector3(point.dx, point.dy, 0.0));
    final Vector3 p = s - d * (n.dot(s) / n.dot(d));
    return Offset(p.x, p.y);
  }

it works, pass RenderSliverList to the first param.

**Comment by Y-ndm** [comment]
> > How to get the;
> > rb.localToGlobal(Offset.zero).dy;
> > rb.size.height;
> > of a RenderSliver. It looks like they're not there.
> > Best regards.
> 
> you can copy the implement of `RenderBox.globalToLocal`, this is my version:
> 
> static Offset globalToLocal(RenderObject object, Offset point, { RenderObject ancestor }) {
> final Matrix4 transform = object.getTransformTo(ancestor);
> final double det = transform.invert();
> if (det == 0.0)
> return Offset.zero;
> final Vector3 n = Vector3(0.0, 0.0, 1.0);
> final Vector3 i = transform.perspectiveTransform(Vector3(0.0, 0.0, 0.0));
> final Vector3 d = transform.perspectiveTransform(Vector3(0.0, 0.0, 1.0)) - i;
> final Vector3 s = transform.perspectiveTransform(Vector3(point.dx, point.dy, 0.0));
> final Vector3 p = s - d * (n.dot(s) / n.dot(d));
> return Offset(p.x, p.y);
> }
> 
> it works, pass RenderSliverList to the first param.
> you should add an dependency in pubspec.yaml like:
> vector_math: ^2.0.8
> and add import message:
> import 'package:vector_math/vector_math_64.dart';

Do you have an example of the implementation and how it would be?? thanks.
