### ISSUE TITLE
Profile builds reporting drastically poorer performance than release builds

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#35409]
This isn't the usual performance build slowdown, but appears to be a greater disparity. Internal bug at https://b.corp.google.com/issues/134769255; please refer to the conversation there.

**Comment by Hixie** [comment]
This is scheduled to happen after customer:dream P0s.

**Comment by Hixie** [comment]
The plan here is to try to add more testing (see #34069) to identify the issue.

**Comment by Hixie** [comment]
Status: waiting for dream to give us concrete reproduction instructions.

**Comment by liyuqian** [comment]
Instructions received. Trying them now. Will give an update by the end of today.

**Comment by liyuqian** [comment]
Both Jason and I tried to follow those steps and ran into the same issue. More details of the problem is posted to b/134769255

**Comment by Hixie** [comment]
We are unaware of any actionable work here. Leaving the bug open so we remember to check with the upstream bug regularly.

**Comment by liyuqian** [comment]
Closing this issue as https://b.corp.google.com/issues/134769255 is marked as "Won't Fix (Not reproducible)"
