### ISSUE TITLE
Unable to open iOS module in AppCode

### ISSUE THREAD

**Issue by athornz** [flutter/flutter#35417]
## Steps to Reproduce

1. Create a new Flutter project
2. Add plugin to project (e.g. connectivity)
3. Run `pod install` within the ios folder
4. Open the `Runner.xcworkspace` project in AppCode
5. In AppCode project view, switch to Files. 

The files displayed will not be the project files, but all the user directory files - i.e. all files from the parent of the `.pub-cache` folder.

Related AppCode issue: https://youtrack.jetbrains.com/issue/OC-17593

This issue says the problem lies with the generated `Pods/Pods.xcodeproj/project.pbxproj`.

The generated project has paths that look like `"../../../../../../../../../../../.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.3+2/ios/Classes/ConnectivityPlugin.h";`.

I can confirm that changing these paths to a relative path from the project directory fixes the issue.

Is this a Flutter issue or does the generation of the `Pods.xcodeproj` happen from CocoaPods?

CC: @jmagman

**Comment by mikhail-tokarev** [comment]
hi @athornz 
are you still experiencing the issue with the latest Flutter stable release? 
If so, please provide the output of "flutter doctor -v"

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by albemala** [comment]
I'm having the same issue. This ticket is related to this other one: https://github.com/flutter/flutter/issues/19601

`flutter doctor -v`

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-IE)
    • Flutter version 1.22.4 at /Users/alberto/flutter
    • Framework revision 1aafb3a8b9 (3 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/alberto/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/alberto/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Alberto’s iPhone (mobile) • 00008101-0006305A0801401E • ios • iOS 14.1
    ! Error: Mawla iPhone is not connected. Xcode will continue when Mawla iPhone is connected. (code -13)

• No issues found!
```

Happy to provide any other information needed.

**Comment by iapicca** [comment]
@albemala 
this issue was closed long ago and isn't currently worked on (same for the issue you are referencing)
I recommend to open a new issue providing 
your `flutter doctor -v`, your logs and most importantly a minimal reproducible code sample

**Comment by albemala** [comment]
@iapicca okay I will, thank you for your prompt reply.
