### ISSUE TITLE
I need help. 

### ISSUE THREAD

**Issue by Emrey06** [flutter/flutter#35414]
I'm new to flutter and I'm having trouble

![1](https://user-images.githubusercontent.com/52382002/60459411-c7ca9980-9c49-11e9-800b-0a685990bd84.png)
![2](https://user-images.githubusercontent.com/52382002/60459430-d913a600-9c49-11e9-87a8-94554bca1542.png)

**Comment by minh98** [comment]
you should post it to stackoverflow

**Comment by Emrey06** [comment]
okey, thank you
