### ISSUE TITLE
Enable Flutter compositor layers

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#35410]
Enable Flutter compositor layers to allow Flutter to reduce the number of compositions when unnecessary and potentially overlay them. Mirror issue for https://b.corp.google.com/issues/132812775; conversation should occur there.

**Comment by chinmaygarde** [comment]
Work on this is in progress on the [embedder_layer](https://github.com/chinmaygarde/flutter_engine/tree/embedder_layer) branch.

**Comment by chinmaygarde** [comment]
[Patch has been posted](https://github.com/flutter/engine/pull/10195) and unit-test coverage is a superset of anticipated needs.
