### ISSUE TITLE
Mysterious lack of compilation error

### ISSUE THREAD

**Issue by mgrzechocinski** [flutter/flutter#35413]
Hi,

I'm a relatively new Flutter developer, who came from regular, native Android apps where strongly statically typed languages like Kotlin athe the first class citizens.

I was executing tasks from the official (?) [codelab](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#0) when I found an interesting piece of code which compiles with no single error or even warning but unfortunately  fails at runtime.

Take a look at the following method from the [second part](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/#5) of the above codelab:
```
 void _pushSaved() {
    Navigator.of(context).push(
      MaterialPageRoute<void>(
        builder: (BuildContext context) {
          final Iterable<ListTile> tiles = _saved.map(
            (WordPair pair) {
              return ListTile(
                title: Text(
                  pair.asPascalCase,
                  style: _biggerFont,
                ),
              );
            },
          );
          final List<Widget> divided = ListTile.divideTiles(
            context: context,
            tiles: tiles,
          ).toList();
        },
      ),
    );
  }
```
This method is basically called on some kind of user action and it should open a new screen by pushing new `MaterialPageRoute`. 

What I found interesting is the way `MaterialPageRoute`'s constructor is being invoked:
```
MaterialPageRoute<void>(
   builder: (BuildContext context) {
       ...
   }
)   
```

As far as I understand, `builder` parameter is type of `WidgetBuilder` which is actually a typedef of a function which has to return a `Widget`: 
```
typedef WidgetBuilder = Widget Function(BuildContext context);
```
Surprisingly, implementing this function without returning any Widget still compiles but when I try to run the app and push this new route I get this runtime crash:
```
I/flutter (28374): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28374): The following assertion was thrown building Builder(dirty, dependencies:
I/flutter (28374): [_LocalizationsScope-[GlobalKey#0b08b], _InheritedTheme]):
I/flutter (28374): The builder for route "null" returned null.
I/flutter (28374): Route builders must never return null.
I/flutter (28374): 
I/flutter (28374): When the exception was thrown, this was the stack:
I/flutter (28374): #0      MaterialPageRoute.buildPage.<anonymous closure> (package:flutter/src/material/page.dart:90:9)
I/flutter (28374): #1      MaterialPageRoute.buildPage (package:flutter/src/material/page.dart:96:6)
I/flutter (28374): #2      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:666:43)
I/flutter (28374): #3      Builder.build (package:flutter/src/widgets/basic.dart:6427:41)
I/flutter (28374): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:3974:28)
```
I'm using latest (as of 1st July 2019) recommended SDK: flutter_macos_v1.5.4-hotfix.2-stable.zip. I found that in the `master` branch there's new parameter in `analysis_options.yaml`:
```
missing_return: warning
```
Changing it to error indeed causes IDE to show the problem but it's just a static analysis, not a compiler error as this code still builds successfully by running `flutter run`:
![image](https://user-images.githubusercontent.com/393518/60455903-0bb4a300-9c38-11e9-87b7-bbabe07238b2.png)

I'm just wondering, wether is it a Dart compiler or any other tooling issue or am I missing something which is most likely more Dart language specific thing than the Flutter framework itself?

Thanks in advance for any comments.

**Comment by stuartmorgan** [comment]
This is indeed a Dart language behavior, not something specific to Flutter. See https://dart.dev/guides/language/language-tour#return-values

**Comment by mgrzechocinski** [comment]
Fine, I get it. I can't understand though how function can be declared as returning something `Widget` in this case) and does not return it when implemented as lambda. Either way, thanks for clarification. Will find some resources about that.

**Comment by stuartmorgan** [comment]
> I can't understand though how function can be declared as returning something (Widget in this case) and do not return it when implemented as lambda.

I linked to the explanation in my comment above: if you don't explicitly return something, a `return null` is implicitly added.

**Comment by mgrzechocinski** [comment]
Ok, i think I get it after reading it for the second time.

It's more or less like in Java where `public String foo() { return null; }` is a valid code whereas in Dart `return` statement can be ommited and the code behaves the same. 

When I try to explicitly return a value but of different type, like:
```
  return "foo";
```
compiler fails, as expected:
```
lib/main.dart:64:18: Error: A value of type 'String' can't be assigned to a variable of type 'Widget'.
```
Thanks for your help. I found it a little bit tricky and consider it as error-prone, but that's just how language works and static analysis can definitely help here.
