### ISSUE TITLE
Windows flutter has trouble with unicode characters in output

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#35425]
## Steps to Reproduce

remove windows skip in https://github.com/flutter/flutter/blob/d6bd1c0584d761e622c9f9331581bcae3655f0c4/packages/flutter_tools/test/commands/test_test.dart#L34

will cause the test to break.

The reason being that when the flutter spits out unicode character in output in windows env, it does not correctly encode it. The test fails to do a regex matching from a unicode input file to the machine code that flutter print out.

**Comment by Hixie** [comment]
Fixed by https://github.com/flutter/flutter/pull/46615

**Comment by chunhtai** [comment]
@Hixie the pr has merged, can this be closed?
