### ISSUE TITLE
Shader compilation errors in Flutter Gallery > Cupertino

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#35429]
Just ran the Flutter Gallery and navigated to Cupertino > Alerts, and then launched various alert dialogs.  Got the following errors:

```
D/skia    ( 8536): Shader compilation error
D/skia    ( 8536): ------------------------
D/skia    ( 8536):    1	#version 300 es
D/skia    ( 8536):    2	
D/skia    ( 8536):    3	#extension GL_EXT_shader_framebuffer_fetch : require
D/skia    ( 8536):    4	precision mediump float;
D/skia    ( 8536):    5	inout mediump vec4 sk_FragColor;
D/skia    ( 8536):    6	in mediump vec4 vcolor_Stage0;
D/skia    ( 8536):    7	void main() {
D/skia    ( 8536):    8	    mediump vec4 outputColor_Stage0;
D/skia    ( 8536):    9	    {
D/skia    ( 8536):   10	        outputColor_Stage0 = vcolor_Stage0;
D/skia    ( 8536):   11	    }
D/skia    ( 8536):   12	    {
D/skia    ( 8536):   13	        mediump vec4 _dstColor = sk_FragColor;
D/skia    ( 8536):   14	        sk_FragColor.w = outputColor_Stage0.w + (1.0 - outputColor_Stage0.w) * _dstColor.w;
D/skia    ( 8536):   15	        if (2.0 * _dstColor.x <= _dstColor.w) {
D/skia    ( 8536):   16	            sk_FragColor.x = (2.0 * _dstColor.x) * outputColor_Stage0.x;
D/skia    ( 8536):   17	        } else {
D/skia    ( 8536):   18	            sk_FragColor.x = _dstColor.w * outputColor_Stage0.w - (2.0 * (outputColor_Stage0.w - outputColor_Stage0.x)) * (_dstColor.w - _dstColor.x);
D/skia    ( 8536):   19	        }
D/skia    ( 8536):   20	        if (2.0 * _dstColor.y <= _dstColor.w) {
D/skia    ( 8536):   21	            sk_FragColor.y = (2.0 * _dstColor.y) * outputColor_Stage0.y;
D/skia    ( 8536):   22	        } else {
D/skia    ( 8536):   23	            sk_FragColor.y = _dstColor.w * outputColor_Stage0.w - (2.0 * (outputColor_Stage0.w - outputColor_Stage0.y)) * (_dstColor.w - _dstColor.y);
D/skia    ( 8536):   24	        }
D/skia    ( 8536):   25	        if (2.0 * _dstColor.z <= _dstColor.w) {
D/skia    ( 8536):   26	            sk_FragColor.z = (2.0 * _dstColor.z) * outputColor_Stage0.z;
D/skia    ( 8536):   27	        } else {
D/skia    ( 8536):   28	            sk_FragColor.z = _dstColor.w * outputColor_Stage0.w - (2.0 * (outputColor_Stage0.w - outputColor_Stage0.z)) * (_dstColor.w - _dstColor.z);
D/skia    ( 8536):   29	        }
D/skia    ( 8536):   30	        sk_FragColor.xyz += _dstColor.xyz * (1.0 - outputColor_Stage0.w) + outputColor_Stage0.xyz * (1.0 - _dstColor.w);
D/skia    ( 8536):   31	        sk_FragColor = sk_FragColor;
D/skia    ( 8536):   32	    }
D/skia    ( 8536):   33	}
D/skia    ( 8536):   34	
D/skia    ( 8536): Errors:
D/skia    ( 8536): ERROR: 0:3: 'GL_EXT_shader_framebuffer_fetch' : extension is not supported
D/skia    ( 8536): ERROR: 0:5: 'inout' : syntax error 
```

@liyuqian

**Comment by liyuqian** [comment]
What's the Flutter version?

Could we write a Flutter driver test to reliably reproduce this error? We could use that to guard future failure, do automatic bisection, or give Skia team an easier time to reproduce this error.

CC @bsalomon to see if there's some quick fix. It seems to me that some GL capability check mechanism has being broken.

**Comment by tvolkert** [comment]
This was against `v1.7.8+hotfix.1` (as I was doing a smoke test before the beta release).

**Comment by tvolkert** [comment]
I was able to reproduce this on tip-of-tree with the following driver tests:

`$FLUTTER_ROOT/examples/flutter_gallery`:
  - [`test_driver/cupertino.dart`](https://gist.github.com/tvolkert/e5d90df5b9c3d5ebc4668b6d57fa125b)
  - [`test_driver/cupertino_test.dart`](https://gist.github.com/tvolkert/58c371f3ec4a15fcf665f64f1e4f43b1)

```sh
$ cd examples/flutter_gallery
$ flutter drive -t test_driver/cupertino.dart --driver=test_driver/cupertino_test.dart --verbose-system-logs
```

```sh
## In a separate terminal window
$ adb logcat '*:S skia'
```

**Comment by liyuqian** [comment]
What Android device and host OS are you using? I tried Moto G4 and Android simulator on my Linux desktop. Both master and v1.7.8+hotfix.1 don't give me the compilation error above.

**Comment by chinmaygarde** [comment]
`GL_EXT_shader_framebuffer_fetch` is probably an extension that is not available on the device and Skia is not performing an extensions check before using the same. Can you perform `adb shell dumpsys SurfaceFlinger` and paste the output here? That should list the available extensions. Just want to make sure the device is not lying about available extensions.

**Comment by brianosman** [comment]
Yeah, need to see what device this is. `GL_EXT_shader_framebuffer_fetch` is an extension, but we definitely check for the existence of that extension before trying to use it. I see some older flutter bugs where people had this problem, and they were running on the Android emulator. Those issues appear to have been resolved by newer versions of the emulator or restricting the emulator to ES 2.0. This feels like a driver bug.

**Comment by steven18forever** [comment]
I just fix this error by updating the Android SDK to level 28 and use the flutter v1.7.8.

**Comment by liyuqian** [comment]
@tvolkert : can you still reproduce the issue?

**Comment by chinmaygarde** [comment]
I can't tell if this was on the simulator. This needs more information. The device or emulator type and the result of `adb shell dumpsys SurfaceFlinger`
