### ISSUE TITLE
[web] TextField restores obsolete text after TextEditingController clear

### ISSUE THREAD

**Issue by deckerst** [flutter/flutter#35438]
Test scenario:
1) in a TextField, type "first"
2) click on a button that clears the controller used by the TextField
3) type "second"

Expected behaviour (confirmed in a mobile app):
The TextField should only contain the text "second".

Observed behaviour:
When clearing the controller, the text in the TextField is indeed cleared in step 2). But in step 3) the first keystroke restores the cleared text, so the new text is appended to the obsolete text. The text is then "firstsecond" instead of "second".

Reproduction:
```dart
final controller = TextEditingController();
...
body: Row(
          children: [
            Expanded(
              child: TextField(
                controller: controller,
              ),
            ),
            IconButton(
              icon: Icon(Icons.clear),
              onPressed: () => controller.clear(),
            ),
          ],
        ),
```

The only workaround I found for this issue was by playing with the TextField `focusNode` like this:
```dart
  clearInput() {
    setState(() => controller.clear());
    focusNode.unfocus();
    focusNode.requestFocus();
  }
```

flutter_web version: commit 1ed4317 (June 22)
Mac OS X 10.14.5 18F132, locale en-KR

**Comment by bjornwilliam** [comment]
Thank you so much for your workaround.. was giving up hope here!

**Comment by jkurtw** [comment]
@deckerst is this still an issue for you?

**Comment by deckerst** [comment]
The issue still exists in Flutter 1.10.5, but this is not a blocker thanks to the workaround mentioned above.

**Comment by nturgut** [comment]
I sent https://github.com/flutter/engine/pull/12698 as fix.

Thanks for creating the issue
