### ISSUE TITLE
EventSink.endOfStream cannot be handled by custom embedders

### ISSUE THREAD

**Issue by Drakirus** [flutter/flutter#35434]
I am working on an implementation of EventChannel for [go-flutter-desktop](https://github.com/go-flutter-desktop/go-flutter). In this implementation, I have chosen to handle all 3 of the available events callbacks: success, error, and [endOfStream](https://api.flutter.dev/javadoc/io/flutter/plugin/common/EventChannel.EventSink.html#endOfStream--). Based on documentation found in the Android/Java implementation, it was my understanding that sending a null message value [into the FlutterPlatformMessage ABI](https://github.com/flutter/engine/blob/8ac7cbddace5f280dbf66579b8fcae53fb4a495e/shell/platform/embedder/embedder.h#L375) will close the [Dart Stream](https://github.com/flutter/flutter/blob/d41aac9019157f0c266cf3cd71b6da27a011a812/packages/flutter/lib/src/services/platform_channel.dart#L492).

The flutter [event stream test](https://github.com/flutter/flutter/blob/d41aac9019157f0c266cf3cd71b6da27a011a812/packages/flutter/test/services/platform_channel_test.dart#L245) and the [java](https://github.com/flutter/engine/blob/904cfc4fe3631103c656ba617d9768a832d3622a/shell/platform/android/io/flutter/plugin/common/EventChannel.java#L246) implementation seems to confirm my understanding, endOfStream should send a null message value into the FlutterPlatformMessage.

My issue comes from the fact that I cannot set [the message field](https://github.com/flutter/engine/blob/db4d6836acc4f1df66a538c79e55f4952c923e2a/shell/platform/embedder/embedder.h#L375) to null due to a check made in [embedder.cc](https://github.com/flutter/engine/blob/db4d6836acc4f1df66a538c79e55f4952c923e2a/shell/platform/embedder/embedder.cc#L818)

**Comment by Drakirus** [comment]
On the darwin/commun shell the `endOfStream` sink method sends [`null`](https://github.com/flutter/engine/blob/db4d6836acc4f1df66a538c79e55f4952c923e2a/shell/platform/darwin/common/framework/Source/FlutterChannels.mm#L286). Does it works on MacOS?

**Comment by stuartmorgan** [comment]
> Does it works on MacOS?

There's a good chance that code path has just never been run on macOS.
