### ISSUE TITLE
[in_app_purchase] Acknowledge purchases

### ISSUE THREAD

**Issue by arazinger** [flutter/flutter#35431]
in_app_purchase: 0.2.0

The new Google billing library release notes (https://developer.android.com/google/play/billing/billing_library_releases_notes) state that "Purchases must be acknowledged within three days".
For consumable products, use consumeAsync(), found in the client API.
For products that aren't consumed, use acknowledgePurchase(), found in the client API.

Searching through the source code I can find "consumeAsync" for consumable products but nothing about "acknowledgePurchase" for non-consumable products.

Is there something I'm missing or is it not implemented yet?

**Comment by arazinger** [comment]
Upon further research I found out that this plugin currently depends on billing client v1.2 (com.android.billingclient:billing:1.2), so this probably isn't really a problem as acknowledgments are required as of version 2.0.

**Comment by RaulMarquezInclan** [comment]
Hello,

I'm using **in_app_purchase: ^0.3.4+5**

And I've already had 3 IAP's refunded.

To implement IAP I followed this guide:
https://fireship.io/lessons/flutter-inapp-purchases/

Which implements this medthod among others:
```
  Future<void> _getUserPastPurchases() async {
    QueryPurchaseDetailsResponse response = await _iap.queryPastPurchases();
    for (PurchaseDetails purchase in response.pastPurchases) {
      if (Platform.isIOS) {
        **InAppPurchaseConnection.instance.completePurchase(purchase);**
      }
    }
    setState(() {
      _purchases = response.pastPurchases;
    });
  }
```

This line:
**InAppPurchaseConnection.instance.completePurchase(purchase);**
Is the only one that sounds like some sort of purchase acknowledgment, but the guy in the video said that only iOS users need this. Also this method only fetches the users past purchases.

Even so, is that line what I would need to implement for Android and run it after a successful purchase?

Please advise, this is very critical as our app is already on Google Play.

Thanks.

**Comment by Jigneshiosdeveloper** [comment]
@RaulMarquezInclan @arazinger 
Users paid in-app purchase in our app, but google automatic refunds after 72 hrs & 10 mins, I don't know why this happens. I did all code as a flutter document and also added below:

in_app_purchase: ^0.3.1+1 (pubspec.yaml)

- app/build.gradle 

dependencies { implementation 'com.android.billingclient:billing:2.0.3' 
}

but each and every time user users paid in-app purchase but google automatic refunds after 72 hrs & 10 mins. Any solutions please? (Flutter App)

**Comment by Jigneshiosdeveloper** [comment]
> Upon further research I found out that this plugin currently depends on billing client v1.2 (com.android.billingclient:billing:1.2), so this probably isn't really a problem as acknowledgments are required as of version 2.0.

==========================================================
@arazinger   if I use below:

dependencies { implementation 'com.android.billingclient:billing:1.2'
}

then what should be version for in_app_purchase: ???? (pubspec.yaml) so that there are no need to implement purchase acknowledgment.

**Comment by arazinger** [comment]
@Jigneshiosdeveloper, this is the dependency I'm using in the pubspec.yaml:
in_app_purchase: ^0.2.0+2

Also check this answer regarding the purchase acknowledgments: https://stackoverflow.com/a/59766760/11309905

Hope it helps.

**Comment by Jigneshiosdeveloper** [comment]
@arazinger 

Thanks for your reply. so you are using in_app_purchase: ^0.2.0+2 & implementation 'com.android.billingclient:billing:1.2'

so now your code working fine means you didn't phase automatic refund issue by google. Right? so if yes, then you changed any code in your in-app purchase regarding the purchase acknowledgments.

**Comment by arazinger** [comment]
@Jigneshiosdeveloper 

I'm using "in_app_purchase: ^0.2.0+2" inside pubspec.yaml without any other configuration.
I haven't set "implementation 'com.android.billingclient:billing:1.2'" anywhere as this is configured by the plugin (it is plugin's dependency).

I'm using this kind of configuration in a production app for more than a year now and haven't had any problems with automatic refunds.

AFAIK purchase acknowledgments ("completePurchase") are required as of version 2.0 only, but the above configuration uses the version 1.2.
In my source code I'm doing "completePurchase" only on iOS platform.
With the latest version "completePurchase" should be done on Android too.
See here for details: https://stackoverflow.com/a/59766760/11309905

**Comment by Jigneshiosdeveloper** [comment]
@arazinger Thanks for your reply. I implemented that and it works well.
