### ISSUE TITLE
[web]: TextField onSubmitted is not triggered when pressing enter

### ISSUE THREAD

**Issue by deckerst** [flutter/flutter#35435]
On mobile, pressing the enter key while editing a TextField triggers `onSubmitted`.
On the web, it is never called.

Example:
```dart
        body: TextField(
          onSubmitted: (s) {
            // this is never called
            debugPrint('onSubmitted s=$s');
          },
        ),
```

In the meantime, there's a workaround with RawKeyboardListener:
```dart
        body: RawKeyboardListener(
          focusNode: focusNode,
          onKey: (event) {
            if (event is RawKeyUpEvent && event.data is RawKeyEventDataAndroid) {
              var data = event.data as RawKeyEventDataAndroid;
              if (data.keyCode == 13) {
                debugPrint('onSubmitted');
              }
            }
          },
          child: TextField(),
        ),
```

But it would be nice if it was natively handled.

By the way, contrary to https://github.com/flutter/flutter/issues/19027 there is absolutely no log when pressing enter. Nothing like `inactive InputConnection`, etc.

edit:
flutter_web version: commit 1ed4317 (June 22)
Mac OS X 10.14.5 18F132, locale en-KR

**Comment by Lucas0Braz** [comment]
Maybe if you use streams with the onChanged event you could reach the same result

**Comment by deckerst** [comment]
As far as a I know, `onChanged` is triggered only on content change. The enter key does not modify the content text so `onChanged` is not triggered.

**Comment by jkurtw** [comment]
@deckerst is this still an issue for you?

**Comment by deckerst** [comment]
The issue still exists in Flutter 1.10.5, but this is not a blocker thanks to the workaround mentioned above.

**Comment by sturmf** [comment]
@deckerst Can you please elaborate on your workaround a bit? I have trouble integrating it in my program. 

First of all I did not have a `focusNode`, so I just hand in a new one `FocusNode()`  second I had to change `RawKeyEventDataAndroid` to `RawKeyEventDataWeb` and `data.keyCode == 13` to `data.code == "Enter"`

Now I finally have the print output 'onSubmited' but how would I now access the child widgets text in the event handler?

**Comment by deckerst** [comment]
@sturmf the `focusNode` was necessary for another purpose, not needed here.
And you're right: things have recently changed with regards to `RawEventDataAndroid` v `RawKeyEventDataWeb`. To access the `TextField` content, just give it a `TextEditingController` and access that later.

```dart
  final TextEditingController editingController = TextEditingController();
...
                  RawKeyboardListener(
                    onKey: onTextFieldKey,
                    child: TextField(
                      controller: editingController,
                    ),
                  )
...
  onTextFieldKey(RawKeyEvent event) {
    if (event is RawKeyUpEvent) {
      if (event.logicalKey == LogicalKeyboardKey.enter) {
        submit();
      } else if (event.data is RawKeyEventDataWeb) {
        final data = event.data as RawKeyEventDataWeb;
        if (data.keyLabel == 'Enter') submit();
      } else if (event.data is RawKeyEventDataAndroid) {
        final data = event.data as RawKeyEventDataAndroid;
        if (data.keyCode == 13) submit();
      }
    }
  }

  submit() {
    final input = editingController.text;
    // have fun
  }
```

**Comment by sturmf** [comment]
Thanks, got it working for me too. Unfortunately quite a bit of additional code, so I hope it gets fixed soon!

**Comment by johnpryan** [comment]
CC: @nturgut

**Comment by johnpryan** [comment]
Will `onSubmitted` be supported?

**Comment by jdeltoft** [comment]
I know this is closed, but I wanted to mention that it's working in an annoying way for me.  even a focus change now triggers the onFieldSubmitted, not just enter key.  So I can't tell in my dialog if they hit enter or if they just lost focus on the text field.  Should I enter a bug for that?

I entered a stackoverflow

https://stackoverflow.com/questions/60814200/flutter-handle-enter-key-for-textformfield-ignore-focus-change

**Comment by johnpryan** [comment]
@jdeltoft Using a keyboard listener is probably the best way if you want the enter key to do something other than invoke the `onSubmitted` callback on a text field. You're right, there's no way to know the _reason_ the onSubmitted callback was invoked, and it right now the framework will call it when the field loses focus or when the enter key is pressed.

**Comment by chunhtai** [comment]
FYI https://github.com/flutter/flutter/issues/52656. Some of raw keyboard event is currently not listenable

**Comment by jdeltoft** [comment]
@johnpryan  Thanks, bummer.  :( Losing focus to me seems like logically it shouldn't be "submitted".  I guess I should enter a feature request
