### ISSUE TITLE
[web] Position of TextField <input> makes Firefox scroll to top

### ISSUE THREAD

**Issue by deckerst** [flutter/flutter#35439]
This issue appears in a very specific set of circumstances, but I'd like to share it so it could help others.

My Flutter Web app is embedded in an `iframe`. So this app is not taking the whole screen but could be embedded down a long page, with scroll. This Flutter Web app contains a `TextField`, and the issue is that when the user enters text in it, Firefox triggers scrolling to the top of the page (that embeds the Flutter Web app).

Given these symptoms, I found out that it is because Flutter Web dynamically creates an `<input>` element to synchronize text input with Flutter's `TextField`. And this `<input>` is styled to be hidden out of the way, notably with the following:
```transform: translate(-99999px,-99999px);```

When the user starts typing, Firefox tries to show the edited `<input>` by scrolling to it. Going to -99999px, it scrolls to the top of the page.

Firefox auto-scroll seems reasonable to me, and I think Flutter Web should hide this `<input>` in a different way.

In the meantime, I used the following workaround (not pretty but it works):
```dart
  onFocusChange() async {
    if (!focusNode.hasFocus) return;

    await Future.delayed(Duration(milliseconds: 200));

    HtmlDocument doc = js.context['document'];
    List<Node> inputs = doc.getElementsByTagName('input');
    if (inputs.length == 0) return;
    InputElement input = inputs[0];

    final keyContext = _inputKey.currentContext;
    if (keyContext == null) return;
    final RenderBox box = keyContext.findRenderObject();
    final pos = box.localToGlobal(Offset.zero);

    // changing input type to 'hidden' prevents user input
    // changing input z-index to a negative value partially works but shows artifacts in some cases
    // so we hide the element by horizontal translation
    input.style.transform = 'translate(-10px, ${pos.dy + box.size.height - 1}px)';
  }
```

In this workaround, `_inputKey` is a global key to the TextField, and `focusNode` is the same TextField's focus node. It listens to focus events and modifies the newly created `<input>` to position it at the same level as the TextField.

flutter_web version: commit 1ed4317 (June 22)
Mac OS X 10.14.5 18F132, locale en-KR

**Comment by ferhatb** [comment]
Since we are changing input location shortly this issue should be resolved as part of update.

**Comment by ferhatb** [comment]
@deckerst : Text edit stack got updated. Please try with latest change that makes input visible during editing and should have fixed your issue as well.

**Comment by deckerst** [comment]
I just tried with Flutter web commit cc38319 (Aug 30) and it seems fixed.
Thank you!
