### ISSUE TITLE
Horizontal and Vertical Scroll to Table

### ISSUE THREAD

**Issue by BugsBunnyBR** [flutter/flutter#35445]
I need to show a monthly schedule to my users with all the appointments inline with the day of the month. A regular calendar would not be enough as it would not highlight/show the appointments properly.

A view that scrolls in the axis horizontal and vertical would better suit this need.
I tried with `Table` class and it works well but it has no scroll at all.

My suggestion is to add a new value to be used with `scrollDirection`, something like `Axis.all` that enables scrolling in both directions.

Yeah, I tried most of the calendar libs for flutter on github, but none of them had something that would work for me.

**Comment by HansMuller** [comment]
Two dimensional scrolling is supported by [DataTable](https://api.flutter.dev/flutter/material/DataTable-class.html) (try the [Flutter Gallery "Data tables" demo](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/data_table_demo.dart)) and [Table](https://api.flutter.dev/flutter/widgets/Table-class.html). Maybe try building a schedule widget based on on of those.

**Comment by BugsBunnyBR** [comment]
@HansMuller thanks for your reply.
Using
```
Scrollbar(
      child: ListView(
        children: <Widget>[
          SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Table(
...

```
works!
But I had to  add `defaultColumnWidth: IntrinsicColumnWidth(),` as I am using a `ListTile` as each cell of the table.

It looks like only `PaginatedDataTable` has support to horizontal scrolling "by design" while `Table` does not have. Is this something to standardize ? Cause it took me a white until I looked at the source code of `PaginatedDataTable` and understood how it was different.

**Comment by nadjibnet** [comment]
@BugsBunnyBR 

Hi, use:

`SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: DataTable(..........)
),),`

**Comment by stuz5000** [comment]
@nadjibnet  Doesn't this solution force the full table to rendered. What if I want I scrollable table of 2000 rows?

**Comment by ViniciusSossela** [comment]
> Two dimensional scrolling is supported by [DataTable](https://api.flutter.dev/flutter/material/DataTable-class.html) (try the [Flutter Gallery "Data tables" demo](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/data_table_demo.dart)) and [Table](https://api.flutter.dev/flutter/widgets/Table-class.html). Maybe try building a schedule widget based on on of those.

Just to update the link for [DataTable sample](https://github.com/flutter/gallery/blob/master/lib/demos/material/data_table_demo.dart) with two dimensional scrolling

**Comment by easazade** [comment]
> @HansMuller thanks for your reply.
> Using
> 
> ```
> Scrollbar(
>       child: ListView(
>         children: <Widget>[
>           SingleChildScrollView(
>             scrollDirection: Axis.horizontal,
>             child: Table(
> ...
> ```
> 
> works!
> But I had to add `defaultColumnWidth: IntrinsicColumnWidth(),` as I am using a `ListTile` as each cell of the table.
> 
> It looks like only `PaginatedDataTable` has support to horizontal scrolling "by design" while `Table` does not have. Is this something to standardize ? Cause it took me a white until I looked at the source code of `PaginatedDataTable` and understood how it was different.

there is no need to add the listview if you only want horizontal scroll
