### ISSUE TITLE
[web]: Button ripple animation does not complete

### ISSUE THREAD

**Issue by deckerst** [flutter/flutter#35444]
When pressing on a Button (`IconButton`, `FlatButton`, `RaisedButton`), the ripple animation does not complete.

Reproduction:
```
        body: IconButton(
          icon: Icon(Icons.clear),
          onPressed: () {
            debugPrint('pressed');
          },
        ),
```

![flutter_web_button_ripple](https://user-images.githubusercontent.com/13898333/60479420-bffa0c00-9cc0-11e9-8374-d2109206fecf.gif)

It does not happen 100% of the time, but it is happening most of the time. And the shade of the remaining static ripple background is not always the same, as if the animation was not stopped in a consistent way.

flutter_web version: commit 1ed4317 (June 22)
Mac OS X 10.14.5 18F132, locale en-KR

**Comment by ferhatb** [comment]
Cannot repro  after pointer binding fixes. We fixed crashes related to button state which were likely causing this.
