### ISSUE TITLE
Launcher Icons builder for Android Studio

### ISSUE THREAD

**Issue by amorenew** [flutter/flutter#35455]
I get an error when I try to make app icon launcher 
` "project must be built with sdk 26 or later to use adaptive icons"
even my gradle build tools is 28

`## Steps to Reproduce
1-Create a Flutter application 
2-Open the project by Android Studio
3-Press Right click on the drawable folder for Android and try to create launcher icons.

Solve the issue.
Check the gradle configs for the Flutter project

![image](https://user-images.githubusercontent.com/2842459/60510093-a4eac480-9cdf-11e9-9002-ecdf6a0568a0.png)

**Comment by michaelleopold** [comment]
I'm getting the same problem, please help!!!
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/38088987/62599193-704ec780-b8a0-11e9-8714-a1316b52d917.PNG">

**Comment by henryadamgordon** [comment]
Try open the `android` folder in a new Android Studio window and make the changes this way.

**Comment by mikhail-tokarev** [comment]
@amorenew 
I recommend to try with the following instructions.
flutter.dev/docs/deployment/android#adding-a-launcher-icon
if you are using the latest version of Flutter 
and you are still experiencing this issue, 
please provide the output of "flutter doctor -v"

**Comment by amreniouinnovent** [comment]
@mikhail-tokarev As @henryadamgordon suggested an alternative solution I think we can close this issue

**Comment by willhaslett** [comment]
@amreniouinnovent I think that this issue should be re-opened for two reasons: 1) The workaround is not guessable and requires the right google-fu to get here. 2) The workaround is not working. It does get me past the SDK version warning, but when I try to load a .png, the entire IDE hangs. "Cancel" or the close button do not work and to my knowledge, force-quitting AS was the only next move (this is a very simple tutorial app). Here is the dialog box, showing the absent SDK warning, but after freezing AS. The lower level instruction referenced by @mikhail-tokarev are fine, but again, not a solution to the issue.
![image](https://user-images.githubusercontent.com/2914495/70171516-ddcb0300-169c-11ea-817c-4fabba4b8160.png)

**Comment by mohyddintash** [comment]
Sorry for the late response, but in case anyone is still having this issue, this is what worked for me thanks to @Richard2926 [comment here](https://github.com/flutter/flutter/issues/29608#issuecomment-532697768 ).
Basically change project build settings to build for SDK API 26 or higher, mine was set to API 25, so changing that followed by an invalidate & restart sorted it out.
Hope this helps !

**Comment by Martin1024** [comment]
My  problem is that multiple versions of sdk including 25, 26, 27, 28 are installed on my computer. Removing the versions below 26 solved my problem.

**Comment by hanlyjiang** [comment]
> Sorry for the late response, but in case anyone is still having this issue, this is what worked for me thanks to @Richard2926 [comment here](https://github.com/flutter/flutter/issues/29608#issuecomment-532697768).
> Basically, change project build settings to build for SDK API 26 or higher, mine was set to API 25, so changing that followed by an invalidate & restart sorted it out.
> Hope this helps !

This help me，The solution for me is change the android module‘s Module SDK to 26 or higher. 
1.  Open the project settings；
2. Nav to **Modules**（Not Project） and choose a higher SDK version  
![image](https://user-images.githubusercontent.com/7868304/79037686-ea8cd400-7c05-11ea-81a1-78eb6cdf16c8.png)
3. Just try again，it works
