### ISSUE TITLE
How to add the Zooming Feature inside the Camera Plugin

### ISSUE THREAD

**Issue by Loopex2019** [flutter/flutter#35457]
Hi there i want to add the Zooming Functionality into the Camera and you can see that Feature in the SmartPhone Camera App itself. So can someone help me to figure out how to do it ?

**Comment by mikhail-tokarev** [comment]
@Loopex2019 your suggestion appears to be aiming towards 
adding new features to a specific camera plugin rather than to Flutter SDK;
I'm closing this issue, if you disagree please comment and I'll reopen it.

**Comment by mikhail-tokarev** [comment]
@Loopex2019 your suggestion appears to be aiming towards
adding new features to a specific camera plugin rather than to Flutter SDK;
I'm closing this issue, if you disagree please comment and I'll reopen it.

**Comment by BondarenkoStas** [comment]
@Loopex2019 you can take a look into this implementation https://github.com/flutter/plugins/pull/1304. Note that the PR wasn't merged yet. Did you mean such functionality?
