### ISSUE TITLE
[firebase_auth] linkWithCredential not using FirebaseUser instance

### ISSUE THREAD

**Issue by ebologger** [flutter/flutter#35454]
[linkWithCredential method was moved from FirebaseAuth to FirebaseUser in version 0.11.0](https://github.com/flutter/flutter/issues/32317). 
It seems to me this change was implemented incorrectly. It's not using the user method was invoked on. Instead it uses currently signed in user

This makes merging accounts complicated. We can't do something like `prevUser.linkWithCredential(credential)` in flutter. But it's possible in firebase.

Here's firebase doc:

The call to linkWithCredential will fail if the credentials are already linked to another user account. In this situation, you must handle merging the accounts and associated data as appropriate for your app:

```
// Get reference to the currently signed-in user
var prevUser = auth.currentUser;
// Sign in user with another account
auth.signInWithCredential(credential).then(function(user) {
  console.log("Sign In Success", user);
  var currentUser = user;
  // Merge prevUser and currentUser data stored in Firebase.
  // Note: How you handle this is specific to your application

  // After data is migrated delete the duplicate user
  return user.delete().then(function() {
    // Link the OAuth Credential to original account
    return prevUser.linkWithCredential(credential);
  }).then(function() {
    // Sign in with the newly linked credential
    return auth.signInWithCredential(credential);
  });
}).catch(function(error) {
  console.log("Sign In Error", error);
});
```

**In flutter prevUser.linkWithCredential(credential) will fail.**

**Comment by Julianojc** [comment]
Any solution?

**Comment by mikhail-tokarev** [comment]
hi, @ebologger 
does the issue persist in the latest version of Flutter and Firebase plugin,
if so please provide the output of "flutter doctor -v"

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
