### ISSUE TITLE
My app occasionally turns black with pictures and text

### ISSUE THREAD

**Issue by CeaserW** [flutter/flutter#35456]
![59466C0B52FA03E189B36A331346015C](https://user-images.githubusercontent.com/10041194/60511101-c198f380-9d03-11e9-87a2-f0290129dba9.png)

**Comment by mikhail-tokarev** [comment]
@CeaserW does this issue is still present in the current Flutter stable version, 
if so please provide the output of "flutter doctor -v"

**Comment by CeaserW** [comment]
`Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale
    zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/wanghui/Downloads/flutter
    • Framework revision 7a4c33425d (5 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)`

The problem is still there.

**Comment by CeaserW** [comment]
> @CeaserW is the issue still present in the current Flutter stable version?
> If so please provide the output of "flutter doctor -v"

Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN) • Flutter version 1.5.4-hotfix.2 at /Users/wanghui/Downloads/flutter • Framework revision 7a4c33425d (5 months ago), 2019-04-29 11:05:24 -0700 • Engine revision 52c7a1e849 • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

The problem is still there.

**Comment by mikhail-tokarev** [comment]
hi again @CeaserW 
can you please follow[ this procedure](https://flutter.dev/docs/development/tools/sdk/upgrading#upgrading-the-flutter-sdk-and-packages) to upgrade to the latest stable release.
Let me know if the issue persist.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
