### ISSUE TITLE
Appbundle building doesn't work with flavor

### ISSUE THREAD

**Issue by kevin-lot** [flutter/flutter#35460]
Build application in appbundle mode with flavor doesn't work.

## Steps to Reproduce
flutter build apk --release --flavor app1 --target lib/app1/main.dart => OK

flutter build appbundle --release --flavor app1 --target lib/app1/main.dart => KO

## Logs
Gradle build failed to produce an Android bundle package.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:602:7)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:346:14)
<asynchronous suspension>
#3      buildAppBundle (package:flutter_tools/src/android/app_bundle.dart:43:10)
<asynchronous suspension>
#4      BuildAppBundleCommand.runCommand (package:flutter_tools/src/commands/build_appbundle.dart:43:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

## Flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /home/kevin/Documents/SDK/flutter
    • Framework revision 7a4c33425d (9 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/kevin/Documents/SDK/android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/kevin/Téléchargements/software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

**Comment by mulderpf** [comment]
I'm experiencing the same issue, but the app bundle is actually created despite the error message?  I've also managed to upload it successfully to the Play Store.

**Comment by kevin-lot** [comment]
Bundle was generated but with an issue with a path.

**Comment by kevin-lot** [comment]
This issue was only concerned by 1.5.4 version of flutter.
Appbundle with flavor builds now work with 1.7.8.

**Comment by axel-op** [comment]
@kevin-lot I'm experiencing the same issue while I'm on the 1.7.8+hotfix.4 version

## Stacktrace

\# 0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
\# 1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:536:7)
\# 2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
\# 3      _rootRunUnary (dart:async/zone.dart:1132:38)
\# 4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
\# 5      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
\# 6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
\# 7      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
\# 8      Future._complete (dart:async/future_impl.dart:473:7)
\# 9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
\# 10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
\# 11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
\# 12     runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart)
\# 13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
\# 14     _rootRunUnary (dart:async/zone.dart:1132:38)
\# 15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
\# 16     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
\# 17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
\# 18     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
\# 19     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:348:9)
\# 20     _rootRun (dart:async/zone.dart:1124:13)
\# 21     _CustomZone.run (dart:async/zone.dart:1021:19)
\# 22     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
\# 23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
\# 24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
\# 25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
\# 26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
\# 27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
