### ISSUE TITLE
Asset Image not visible immediately

### ISSUE THREAD

**Issue by AndreaMiotto** [flutter/flutter#35461]
Hi, I'm using an asset image as a decoration image for my tab bar.
When the tab bar is rendered the image is not visibile, probably is too slow to load the asset.

The image is visible just after i drag the tab.
I'm guessing that when I drag the tab, the tab item is rebuilt and at that point the image that is already load is rendered properly.

I'm having this problem even in the release mode.

This is the tab widget:

```dart
Widget _buildTabBar() {
    return Material(
        elevation: 0,
        color: Colors.transparent,
        child: TabBar(
          controller: _tabController,
          labelColor: AppColors.blackText,
          labelStyle: _getTitleTextStyle(),
          isScrollable: true,
          unselectedLabelColor: AppColors.whiteText,
          unselectedLabelStyle: _getTitleTextStyle(),
          indicatorPadding: EdgeInsets.zero,
          indicator: BoxDecoration(
              image: DecorationImage(
                  fit: BoxFit.fill,
                  image: AssetImage('assets/images/wave_gray.png'))),
          tabs: [
            Tab(
              child: Container(
                width: 150,
                child: Tab(text: Localization
                    .of(context)
                    .tabOneName),
              ),
            ),
            Tab(
              child: Container(
                width: 150,
                child: Tab(text: Localization
                    .of(context)
                    . tabTwoName),
              ),
            ),
          ],
        ));
  }
```

**Comment by andreiafurbeis** [comment]
I have the same problem on my app.
The tab bar indicator is transparent at startup, then as soon as the tab is scrolled the image appears.

**Comment by daydayfull** [comment]
I have the same problem on my app.

**Comment by AndreaMiotto** [comment]
any news?

**Comment by mikhail-tokarev** [comment]
@AndreaMiotto  are you still encountering this issue on the current Flutter stable version?
If so,  please provide the output of "flutter doctor -v"

**Comment by jackeyliu** [comment]
I have the same problem on my app.

**Comment by LinHuanTanLy** [comment]
I have the same problem on my app.

**Comment by LinHuanTanLy** [comment]
> Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
> Thanks for your contribution.
` SliverPersistentHeader(
              pinned: true,
              delegate: SliverAppBarDelegate(Stack(
                alignment: Alignment.center,
                children: <Widget>[
                  Container(
                    color: ColorConf.colorFFFFFF,
                  ),
                  Container(
                    child: TabBar(
                        indicator: _b,
                        indicatorSize: TabBarIndicatorSize.label,
                        isScrollable: true,
                        unselectedLabelStyle: TextStyle(
                            fontWeight: FontWeight.normal, fontSize: 14),
                        labelStyle: TextStyle(
                            fontSize: 14, fontWeight: FontWeight.bold),
                        labelColor: ColorConf.color48586D,
                        unselectedLabelColor: ColorConf.color48586D,
                        controller: state.tabController,
                        tabs: state.listForProductMenu
                            .map((e) => Tab(
                                  child: Text(e),
                                ))
                            .toList()),
                  )
                ],
              )),
            ),`
