### ISSUE TITLE
video_player not compatible with Flutter sdk >2.0

### ISSUE THREAD

**Issue by villesau** [flutter/flutter#35476]
I'm getting

```
Because app depends on video_player >=0.10.1+3 which requires Flutter SDK version >=1.5.0 <2.0.0, version solving failed.
```

with the latest video_player package: https://pub.dev/packages/video_player and Flutter 2.1.2-dev.0.0.flutter-0a7dcf17eb. I hope it's not a big effort to update `video_player` to support more recent flutters.

**Comment by stuartmorgan** [comment]
> 2.1.2-dev.0.0.flutter-0a7dcf17eb

That appears to be a Dart version, not a Flutter version. What does `flutter --version` show?

**Comment by villesau** [comment]
```
 flutter --version
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (5 months ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

This is fresh, few days old Flutter installation.

**Comment by villesau** [comment]
Looks like `flutter upgrade` helped. Apparently this has old version: https://github.com/flutter/flutter/issues/14050#issuecomment-487780751 btw would be really nice if Flutter had an official brew formula..
