### ISSUE TITLE
Make it harder to accidentally merge changes on non-master

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#35472]
https://github.com/flutter/flutter/pull/35150 was accidentally merged onto the `dev` branch instead of `master`.  We should have a way to prevent this type of thing from happening again.

Ideas:

* Have a pre-commit check (similar to the "is the build green" check) that checks the merge target and enforces that we only merge on master.  If anyone's ever intentionally merging directly to a stable branch, they can ignore that check.
* Others?

**Comment by dnfield** [comment]
We should be able to create a webhook that would check the branch for newly created pull requests, and automatically close them if it's not master.

**Comment by dnfield** [comment]
I have a GAE app that is able to handle this .. will try testing it out next week.

I think I can also make it do some trivial tagging of new PRs (e.g. for framework, for tools, etc.).

**Comment by dnfield** [comment]
I'm going with having it change the base of the pull request to master and leaving amessage.  If it's really intended for another branch it can be changed back, but the message should be more conspicuous.
