### ISSUE TITLE
Docker build fails with hotfix releases

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#35470]
The recent beta channel push exposed the following failure (https://cirrus-ci.com/task/6498931779829760):

```
$CIRRUS_WORKING_DIR/dev/ci/docker_linux/docker_build.sh
invalid reference format
invalid argument "gcr.io/flutter-cirrus/build-flutter-image:v1.7.8+hotfix.2" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
Exit status: 125
```

**Comment by digiter** [comment]
Root cause: "v1.7.8+hotfix.2" isn't a valid docker tag.

Docker tag format:
> A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.

**Comment by gspencergoog** [comment]
Can we just convert the "+" to an underscore for docker?

**Comment by gspencergoog** [comment]
Actually, Ian pointed out that we could just use the git hash as the tag for Docker.  That seems like a better choice.

**Comment by Hixie** [comment]
I'd be fine with using an underscore, too. Or another period.
Can we tag with both a version _and_ a hash?

**Comment by digiter** [comment]
Triage: seems we don't need this any more.
