### ISSUE TITLE
Need a data model independent from the widget tree

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#3548]
The current concept of per-widget State in a widget tree does a great job managing the state of the view, but I think we need a separate mechanism for storing the model data to support a Model-View-Controller design.

I would like to see a design where:
- Model data can be stored outside of State objects.
- Changes to the model can ripple to the view, similar to `setState()`.
- There is a relationship between widgets and their model and/or controller, so that widgets deeply nested in the widget tree have easy access to the appropriate data
- The model can be saved without have to walk the widget tree.
- The model can be loaded without having to create a widget tree.
- (Maybe) State objects can define save/load functions for persistence.

All of these bullet points address issues we are seeing in our current app.

One idea - create a `ControllerWidget` that makes the model and view available to the widget tree underneath it, similar to how MediaQuery works. Allowing multiple `ControllerWidget`s in the tree might provide a foundation for Hierarchical-Model-View-Controller, in which case different controllers would apply to different parts of the widget tree. When the model changed, these widgets could observe the change and call `setState()`.

@pylaligand

**Comment by abarth** [comment]
Yes, something like this would be a good addition.  There's a relatively large design space here.  It might make sense to try some approaches and see what ends up working well.

> When the model changed, these widgets could observe the change and call setState().

One design question is how the widgets observe changes in the model.  Did you have something in mind here?

/cc @yjbanov @Hixie

**Comment by Hixie** [comment]
Another way would be to have two base classes:
* an abstract model base class that supports being registered against (add/remove listener pattern)
* an abstract StatefulWidget subclass that takes one of the above as a constructor argument and automatically registers itself with it, and on notification, call setState.

You'd then build your model out of classes derived from the aforementioned model base class, and you'd build the widgets that depend on them by inheriting from the aforementioned widget subclass, passing the model object to the widget constructor, and in the build function using the model object to build that part of the tree. Any time the model changes, you'd automatically get rebuilt.

**Comment by abarth** [comment]
The idea to combine it with an InheritedWidget is interesting.  We might want to provide developers a way to hook into the "dependenciesChanged" machinery in the framework to do automagical registration/unregistration from the model base class.

**Comment by sethladd** [comment]
Potentially related: https://facebook.github.io/flux/ https://github.com/reactjs/redux/blob/master/README.md

**Comment by yjbanov** [comment]
> an abstract model base class that supports being registered against (add/remove listener pattern)

[package:observe](https://pub.dartlang.org/packages/observe) provides such an abstraction and this package is widely accepted in the community. It provides a number of observable collections and utilities for creating custom observable objects, including a code generator for generating notification code based on annotations (to avoid reflection). There's [an issue](https://github.com/dart-lang/observe/issues/86) that prevents it from loading in a Flutter app (we crash if we see a `dart:mirrors` import), but otherwise I think it seems very suitable for this style of model-view separation.

> an abstract StatefulWidget subclass that takes one of the above as a constructor argument and automatically registers itself with it, and on notification, call setState.

This should work with observable objects that are not nested. A little more plumbing might be necessary for observing a tree of observable objects. For example, imagine a widget receives an observable `User` object that contains an observable `Address` object, and the widget needs to display `Address.city`. We need to subscribe to `Address.city` change notificatons. However, we also need to be able to renew that subscription when `User` notifies that its `address` changed. For that you need to observe path `user.address.city`. A utility for that is [PathObserver](https://github.com/dart-lang/observe/blob/master/lib/src/path_observer.dart). I'm not sure if it works without mirrors though.

/cc @jmesserly @jakemac53

**Comment by jakemac53** [comment]
> For that you need to observe path user.address.city. A utility for that is PathObserver. I'm not sure if it works without mirrors though.

It does work without mirrors (via package:smoke and generated code). However these path observers get expensive fast... it was one of the performance bottlenecks of polymer 0.5. There is a basic benchmark which we ported from JS [here](https://github.com/dart-lang/observe/tree/master/benchmark) that you can play around with, I haven't ran it in a long time though so no guarantees it still works.

I think that package:observe was originally built to mirror Object.observe on the JS side as closely as possible. That api has since been deprecated on the js side of things, and I think it might be worth re-evaluating the package, specifically to see if we could fix the deep observability issue so it doesn't require setting up a listener on each and every nested object.

Maybe some sort of event bubbling mechanism or something along those lines?

**Comment by jmesserly** [comment]
FYI, there's a lot we would like to change about the design of "package:observe" now (the design was subject to some external constraints that led to sub-optimal design--these constraints are now gone).

But it is squatting on a great name, so I've been trying to encourage folks that may want to take it over. Framework designers will have a better perspective on where it should go, in any case. I'm full time on compiler stuff right now (strong mode and DDC) so don't really have cycles for it.

"package:observe - the good parts" I would say is:
* the APIs that are common with Java's Observable and C#'s INotifyPropertyChanged
* ObservableList and ObservableMap

PathObserver is not something I would put in the "good parts" ... it's very convenient, and basically expresses the `{{foo.bar.baz}}` pattern common in template languages. But it depends on reflection or code generation to make it at all usable.

With an observable object, it's not hard to write by hand with something like:
```dart
class MyModel extends MyModelBase with ChangeNotifierMixin {
  String _name;
  String get name => _name;
  set name(value) {
    notifyPropertyChange('value', _name, value);
    _name = value;
  }
}
// here's all ChangeNotifier needs to be, BTW:
abstract class ChangeNotifierMixin {
  // note: in real impl, lazy initialize this for perf
  final _changes = new StreamController<PropertyChangeRecord>(broadcast: true);
  Stream<PropertyChangeRecord> get changes => _changes.stream;
  // note: nowadays this could be a generic method
  Object notifyPropertyChange(String name, Object oldValue, Object newValue) {
    if (oldValue != newValue) {
      _changes.add(new PropertyChangeRecord(name, oldValue, newValue));
   }
    return newValue;
  }
}
```

But if you want to support PathObserver you need to add a method like:
```dart
class MyModel extends MyModelBase with ChangeNotifierMixin {
  // ...
  Object getPropertyValue(String property) {
    switch (property) {
      case 'name':
        return _name;
        // ...
    }
  }
}
```
That's pretty ugly without code generation.

BTW, I'm not sure if Flutter is using dart:async Streams, but I found they were really slow (compared to C# Events that I was used to). So I'm not sure if that's the abstraction I would use in ChangeNotifier if I had it to do all over again.

**Comment by Hixie** [comment]
>  For example, imagine a widget receives an observable User object that contains an observable Address object, and the widget needs to display Address.city

The widget would depend on the User, and would create a child widget and pass it the Address. If the User changes, the parent widget gets rebuilt (which creates a new child). If the Address changes, just the child widget gets rebuilt.

**Comment by yjbanov** [comment]
> would create a child widget and pass it the Address

That would be a lot of boilerplate just to evaluate `user.address.city`. If I had to hand-write code that watches everything that's on the UI, I'd probably be better off with a utility like this:

```dart
class Watchers {
  void cleanup();
  void watch(Observable object, Symbol field);
}

class UserInfoState extends State<UserInfo> {
  final _watchers = new Watchers();

  @override
  build(ctx) {
    _watchers
      ..cleanup()
      ..watch(user, #name)
      ..watch(user, #address)
      ..watch(user.address, #city);

    // build UI using `user.name` and `user.address.city`
  }

  @override
  dispose() {
    _watchers.cleanup();
  }
}
```

But I think even this is a lot of boilerplate, something `package:observe` could help reduce. Speculatively:

```dart
class UserInfoState extends ObservableState<UserInfo> {

  @observe get _name => user.name;
  @observe get _city => user.address.city;

  @override
  build(ctx) {
    // build UI using `_name` and `_city`
  }
}
```

**Comment by sethladd** [comment]
An example of how data flows through an app (in this case, the F8 iOS and Android apps built with React Native): http://makeitopen.com/tutorials/building-the-f8-app/data/

**Comment by abarth** [comment]
Here's a sketch of a shallow listenable object combined with InheritedWidget:

https://gist.github.com/abarth/cad90f75fd892effdc2836cecfdf5647

**Comment by Hixie** [comment]
@abarth That avoids having to pass the model objects down the tree, but it doesn't handle deep model objects (user.address.street). Deep model objects (specifically, doing the optimal minimum amount of rebuilding for each possible change) are the hard case, I think.

**Comment by abarth** [comment]
@Hixie The hypothesis with this approach is that it's not important to compute the optimal minimum amount of rebuilding for each possible change.  That's important in normal model observation systems, but in Flutter you've got the widget framework to help you minimize the modification to the underlying render objects.  That makes it seem like you could have coarser grained notifications.

**Comment by Hixie** [comment]
If we're not trying to minimise the rebuilds, then this problem is essentially the same as `ui.window` or an `Animation<T>`. Which is to say, it's a solved problem, IMHO. But we should definitely demo this in some example somewhere (maybe stocks).

**Comment by abarth** [comment]
@jimbeveridge has graciously offered to try this approach out in his app.  That will help us learn what granularity of notifications we need.

**Comment by jimbeveridge** [comment]
Both Flux and Redux assume everything is always being redrawn and so only support coarse notifications. It's important to differentiate between View state and Model state. Animations (a typical high-performance construct) would change the View state, which is maintained within the widgets and so would support minimal redraw. Animations would not have to go through the machinery of observing the model.

**Comment by jimbeveridge** [comment]
I've tried a Flux application model in two separate applications and I now have enough information to create a proposal for Flutter.

**Comment by jimbeveridge** [comment]
My dogfood implementation can be found at:
https://github.com/jimbeveridge/flutter_flux

**Comment by abarth** [comment]
Looks like we've moved flutter_flux into the flutter organization.

**Comment by abarth** [comment]
Once https://github.com/flutter/flutter_flux/pull/2 lands, I think we can close this issue and recommend flutter_flux

**Comment by abarth** [comment]
That PR has landed.
