### ISSUE TITLE
[web]:Flutter For Web Http Request error

### ISSUE THREAD

**Issue by wedcel** [flutter/flutter#35505]
![image](https://user-images.githubusercontent.com/3982317/60558962-918e3680-9d7d-11e9-98be-e06920773733.png)
The web request I developed for Flutter For Web is no problem on PC Chrome, but running on the android webview will report the above error.

The code is:

`     

    HttpRequest.request(url, withCredentials: true)
      .then((HttpRequest resp) {
    var response = resp.response;
    print('Response status: ${resp.status} Response body: ${response}');

    String bodyString = response.toString();

    Map data = JsonDecoder().convert(bodyString);
    print('data is $data');

    if (resp.status == 200) {
      success(resp.status, data);
    } else {
      if (error != null) {
        error(resp.status, resp.statusText);
      } else {
        print('error is null not callback');
      }
    } }).catchError((e) {
    print("catch some error  ${e}");
    if (error != null) {
      error(-10001, "");
    }  });
 `

**Comment by kevmoo** [comment]
Use `package:http` for doing HTTP requests. This has proper support for both browser and native code!

**Comment by wedcel** [comment]
@kevmoo  I noticed that httpclient in package:http and dart:html are handled by browser_client. Is there any difference here? The error reported here on the mobile browser seems to be caused by the webdev conversion not being recognized.

**Comment by kevmoo** [comment]
@wedcel – not sure I understand. Could you explain more?

**Comment by wedcel** [comment]
@kevmoo  show the sample code:
`

     import 'package:http/http.dart' as http;
     doRequest(String url, Function success, {body, Function error}) {
       if (!isEmpty(body)) {
         url += "?data=${Uri.encodeFull(body)}";
       }
       print("url is $url");
       http.get(url).then((resp) {
         print('Response status: ${resp.statusCode} Response body: ${resp.body}');

         String bodyString = resp.body;
         Map data = JsonDecoder().convert(bodyString);
         print('data is $data');
         if (resp.statusCode == 200) {
           success(resp.statusCode, data);
         } else {
           if (error != null) {
             error(resp.statusCode, resp.body);
          } else {
             print('error is null not callback');
           }
         }
       }).catchError((onError) {
         print("catch some error  ${onError}");
         if (error != null) {
           error(-10001, "");
         }
       }).timeout((Duration(seconds: 15)));
     }
`
I got an error “catch some error  XMLHttpRequest error”  in iPhone XR.

**Comment by donkii** [comment]
I am getting the same error on web using package: http

**Comment by VickySalunkhe** [comment]
I was facing the same issue I solved it and have answered it on StackOverflow
Do give it a look here
https://stackoverflow.com/a/59552060/9236994

**Comment by theapphideaway** [comment]
> I was facing the same issue I solved it and have answered it on StackOverflow
> Do give it a look here
> https://stackoverflow.com/a/59552060/9236994

In your answer you said "Add below code to your websites .htaccess file" but flutter doesn't have a .htaccess file.
