### ISSUE TITLE
Create a canonical add-to-app example in examples

### ISSUE THREAD

**Issue by xster** [flutter/flutter#35503]

**Comment by xster** [comment]
Tentatively assigning to Andrew

**Comment by blasten** [comment]
@RedBrogdon is looking into _eventually_ copying the sample from https://github.com/flutter/samples/tree/master/experimental/add_to_app to flutter/flutter so we can add benchmarks, tests, and so on.

**Comment by matthew-carroll** [comment]
@RedBrogdon is the schedule still looking good for this? Is this ticket about the work that you've been doing recently with example apps?

**Comment by blasten** [comment]
Fixed by https://github.com/flutter/samples/pull/154

**Comment by RedBrogdon** [comment]
We can if it's decided that it would be worthwhile.

That said, the original rationale for the structure of the samples was covering all the important decisions:

* Do I prebuild or build from source?
* Do I use plugins or not?
* ...etc.

With the three samples we have, the first two are covered:

* Do I prebuild or build from source?
  - Build from source: platform_fullscreen
  - Prebuild: platform_using_prebuilt_module
* Do I use plugins or not?
  - No plugins: platform_fullscreen
  - Yes plugins: platform_using_plugin

Unless folks have strong feelings, I don't think a prebuilt-with-plugins sample is necessary unless there's something about combining those two things that causes it to be a distinct choice (read: you can't just take what you learn about plugins and prebuilt modules from the existing samples and combine it to get what you need).
