### ISSUE TITLE
Update flutter tools for new Android plugins API

### ISSUE THREAD

**Issue by xster** [flutter/flutter#35509]
- [ ] Generated code from flutter packages get references new API
- [ ] Generated code from flutter packages get against old plugins uses the shim
- [ ] flutter create -t plugin creates plugins based on the new template

cc @matthew-carroll

**Comment by xster** [comment]
From discussion today, we said it would be interesting to check whether we can, for the new embedding case, let the engine directly try to use reflection to specifically find the generated class which calls into the collection of new plugin API construction and into the collection of old plugin API shim construction. 

The latency cost needs to be satisfactory for us but if it were something like 20ms, that could be acceptable in exchange for users no longer needing to call anything in their own code for the plugins to be loaded. 

Optionally, add a mechanism during FlutterEngine construction to opt-out of the automatic registration. And have a public method to manually register later. But that doesn't have to be done in phase 1.

**Comment by xster** [comment]
For Matt, one component of this is also to make sure that when the new embedding's reflection of GeneratedPluginRegistrant is called, that a ShimPluginRegistry instance is passed into the registerWith function for the old plugin types

**Comment by blasten** [comment]
@matthew-carroll. If possible, it would be useful to share a link to the latest doc we discuss, so folks reading this thread know where we are now.

**Comment by blasten** [comment]
The doc is posted on https://flutter.dev/go/generated-plugin-registration.
