### ISSUE TITLE
Migrate first party plugins to new plugins API

### ISSUE THREAD

**Issue by xster** [flutter/flutter#35506]
Didn't find an existing issue. Creating one for tracking. 

cc @matthew-carroll @amirh

**Comment by xster** [comment]
First task is on the add-to-app team to provide a sample PR where a plugin from flutter/plugins is migrated to have a parallel new embedding implementation. 

Previously said to replace the io.flutter.* namespace to dev.flutter.* to avoid naming collision. 

Since new plugins only run on new embeddings, create a new examples activity based on the new embedding as well in the dev.flutter.* namespace. 

Add both activities into the AndroidManifest so their can be individually targetable in integration tests.

**Comment by matthew-carroll** [comment]
Done here:
https://github.com/flutter/plugins/pull/2114
