### ISSUE TITLE
Navigator.push not working in certain circumstances

### ISSUE THREAD

**Issue by takaoandrew** [flutter/flutter#35502]
## Steps to Reproduce

The issue only occurs in iOS, after the screen is locked and the app is reopened.

Unfortunately, the steps to reproduce this are complicated, and have to do with a certain series of steps as a user in our application that have to do with the data coming from the backend. 

I understand that this might not be a lot to go on, but if I can fundamentally understand why route.navigator might be null in CupertinoPageRoute, I might be able to fix this bug. 

But really, all that is causing this issue is the function 

Navigator.push(
      context,
      new MaterialPageRoute(builder: (context) => new QuestionPage()),
    );

1. ...
2. ...
3. ...

## Logs

```
On clicking the inkwell, which is supposed to take me to another page, I get the following message.

The following NoSuchMethodError was thrown building AnimatedBuilder:
flutter: The getter 'userGestureInProgress' was called on null.
flutter: Receiver: null
flutter: Tried calling: userGestureInProgress
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      CupertinoPageRoute.isPopGestureInProgress (package:flutter/src/cupertino/route.dart:197)
flutter: #1      PageTransitionsTheme.buildTransitions (package:flutter/src/material/page_transitions_theme.dart:315)
flutter: #2      MaterialPageRoute.buildTransitions (package:flutter/src/material/page.dart:107)
flutter: #3      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:637)
flutter: #4      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:910)
flutter: #5      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:148)
flutter: #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825)
flutter: #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739)
flutter: #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
flutter: #9      StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
flutter: #11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
flutter: #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
flutter: #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
flutter: #15     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
flutter: #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
flutter: #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
flutter: #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
flutter: #21     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
flutter: #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
flutter: #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
flutter: #25     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796)
flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
flutter: #27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
flutter: #31     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750)
flutter: #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3565)
flutter: #35     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278)
flutter: #36     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700)
flutter: #37     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286)
flutter: #38     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012)
flutter: #39     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952)
flutter: #40     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864)
flutter: #44     _invoke (dart:ui/hooks.dart:219)
flutter: #45     _drawFrame (dart:ui/hooks.dart:178)
flutter: (elided 3 frames from package dart:async)


Any further attempts to click the InkWell give me this error - Another exception was thrown: NoSuchMethodError: The getter 'userGestureInProgress' was called on null.

```

```
No analysis errors other than unused imports
```

```
No issues found!
```

**Comment by takaoandrew** [comment]
There was logic in the other page that was calling navigator.pop in initState. I wasn't seeing any changes so I thought the other activity wasn't even starting.

**Comment by yannickaboh** [comment]
Hi everyone 
i'm new on flutter 
i think that i have the same problem with navigator.push after login

**Logs**
D/ViewRootImpl@a11b4df[MainActivity](23350): ViewPostIme pointer 0
D/ViewRootImpl@a11b4df[MainActivity](23350): ViewPostIme pointer 1
E/flutter (23350): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'length' was called on null.
E/flutter (23350): Receiver: null
E/flutter (23350): Tried calling: length
E/flutter (23350): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (23350): #1      _Uri._uriEncode (dart:core-patch/uri_patch.dart:44:23)
E/flutter (23350): #2      Uri.encodeQueryComponent (dart:core/uri.dart:1103:17)
E/flutter (23350): #3      mapToQuery.<anonymous closure> (package:http/src/utils.dart:19:13)
E/flutter (23350): #4      CastMap.forEach.<anonymous closure> (dart:_internal/cast.dart:288:8)
E/flutter (23350): #5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (23350): #6      CastMap.forEach (dart:_internal/cast.dart:287:13)
E/flutter (23350): #7      mapToQuery (package:http/src/utils.dart:17:7)
E/flutter (23350): #8      Request.bodyFields= (package:http/src/request.dart:137:12)
E/flutter (23350): #9      BaseClient._sendUnstreamed (package:http/src/base_client.dart:85:17)
E/flutter (23350): #10     BaseClient.post (package:http/src/base_client.dart:32:7)
E/flutter (23350): #11     post.<anonymous closure> (package:http/http.dart:70:16)
E/flutter (23350): #12     _withClient (package:http/http.dart:166:20)
E/flutter (23350): #13     post (package:http/http.dart:69:5)
E/flutter (23350): #14     Repository.httpPost (package:canal_plus_gabon/Repository/Repository.dart:24:18)
E/flutter (23350): #15     UserService.login (package:canal_plus_gabon/Services/UserService.dart:18:30)
E/flutter (23350): #16     _LoginScreenPageState._login (package:canal_plus_gabon/Screens/LoginScreenPage.dart:41:45)
E/flutter (23350): #17     _LoginScreenPageState.build.<anonymous closure> (package:canal_plus_gabon/Screens/LoginScreenPage.dart:152:27)
E/flutter (23350): #18     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (23350): #19     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (23350): #20     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (23350): #21     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (23350): #22     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (23350): #23     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter (23350): #24     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter (23350): #25     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (23350): #26     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (23350): #27     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (23350): #28     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (23350): #29     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (23350): #30     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (23350): #31     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (23350): #32     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (23350): #33     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (23350): #34     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (23350): #35     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (23350): #36     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (23350): #37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (23350): #38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (23350): #39     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (23350): #40     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (23350):
