### ISSUE TITLE
I wanna load html string through plugin webview_flutter

### ISSUE THREAD

**Issue by Cvilia** [flutter/flutter#35517]
but i couldn't load image in my html string,meanwhile,I made WebView as child for SizedBox,its height and width were adapted to device screen.Even though,it still exceeded device's width.I check the official demo ,but it was futile
I try it like those:
```
return WebView(
      initialUrl: '',
      onWebViewCreated: (controller) async {
        String content = base64Encode(Utf8Encoder().convert(html));
        controller.loadUrl('data:text/html;base64,$content');
      },
    );
```

**Comment by Cvilia** [comment]
laod image through webview_flutter

**Comment by Cvilia** [comment]
I foud if image url started with http,webview couldn't load it,i solved it

**Comment by BondarenkoStas** [comment]
Good, I think it's safe to close the issue.
