### ISSUE TITLE
Global configuration for Tooltip

### ISSUE THREAD

**Issue by samuelg123** [flutter/flutter#35513]
## Use case

I need to customize Tooltip text color and background color across my app. 
Current solution: https://stackoverflow.com/questions/55426001/tooltip-message-text-and-background-color 

## Proposal
Please add another parameter that takes tooltip configuration on ThemeData or maybe MaterialApp. 

Thank you.

**Comment by HansMuller** [comment]
Good suggestion. We've had this project in the queue for a while, perhaps now is the time to get on with it :-).

Tooltips are rarely explicitly created or configured by apps so if a developer wants to customize their appearance, life is difficult.

Tooltip appearance should probably adapt per platform and be customizable per ThemeData.tooltipTheme. The platform adaptation may also need to include the triggering gesture.

There is an old one-liner PR that took a tiny step in this direction: https://github.com/flutter/flutter/pull/25844.
