### ISSUE TITLE
External Texture Underlying Share Context

### ISSUE THREAD

**Issue by kaisa695275735** [flutter/flutter#35515]
Currently, external textures are  very differently on iOS (CoreVideo) and Android (GL_OES_EGL_image_external). 
In China, Portrait beauty effects are basically a must-have for a camera tool. We process our video frame on the GPU to generate a texture to be rendered. If flutter needs to display this texture, it requires a GPU->CPU->GPU process, wasting performance.
So we added an interface to **Get Flutter GLContext** on our Flutter branch. Based on this modification, we implemented the Flutter plugins such as Album, Video Capture, Video Editor. 
And those plugins  has been used by hundreds of millions of users on the Xianyu APP to verify its effectiveness。
We hope we can merge this change back to the flutter master so that more develop can use our plugins to develop video App。
@chinmaygarde

**Comment by chinmaygarde** [comment]
> If flutter needs to display this texture, it requires a GPU->CPU->GPU process, wasting performance.

I am not sure I understand why you would need to do this. Are you talking about iOS specifically? Perhaps you need to process the CoreVideo pixel buffer using OpenGL and give Flutter that texture directly (instead of the pixel buffer)? If so, yes, that sounds like good idea.

Anyway, if you submit a patch via the usual pull request process on flutter/engine, I'd be happy to take a look.

**Comment by kaisa695275735** [comment]
YES，what we want to do is  give Flutter our **processed texture** directly  instead of the pixel buffer(IOS) or SurfaceTexture(Android).
So we need share our GLContext with flutter's GLContext.
Here is our pull Request:
https://github.com/flutter/engine/pull/9702/commits/dfe3d986c96a29ea40a4c9adc3eb9e811c28a64e
For time limit and not familiar with google's code style, our code may not be very  standardized, but if adapted we will continuously optimized it.

**Comment by kaisa695275735** [comment]
> I am not sure I understand why you would need to do this. Are you talking about iOS specifically? Perhaps you need to process the CoreVideo pixel buffer using OpenGL and give Flutter that texture directly (instead of the pixel buffer)? If so, yes, that sounds like good idea.
> 
> Anyway, if you submit a patch via the usual pull request process on flutter/engine, I'd be happy to take a look.

YES，what we want to do is give Flutter our processed texture directly instead of the pixel buffer(IOS) or SurfaceTexture(Android).
So we need share our GLContext with flutter's GLContext.
Here is our pull Request:
flutter/engine@dfe3d98
For time limit and not familiar with google's code style, our code may not be very standardized, but if adapted we will continuously optimized it.
@chinmaygarde

**Comment by darshankawar** [comment]
@kaisa695275735 
Is this still a valid and open issue using latest Flutter version ?
Since your original PR was closed, I don't see any activity on this. Can this be closed or need to be kept open ?
thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
