### ISSUE TITLE
The frames drop when app launches from background to foreground 

### ISSUE THREAD

**Issue by luckysmg** [flutter/flutter#35520]
When my app is running in background ,and in the one or two seconds after app restart from background to foreground ,the frames will drop aparently,even under the release mode. You can notice this kind of situation in Sliding ListView(I create it with builder so I think the problem is not on ListView),or the page-jump animation.I have notice this situation on many tested phones, so I think there is something in flutter that will cause this situation.Hoping the reply from flutter team!

**Comment by kafein** [comment]
Please add the output of **flutter doctor -v**
I think your problem related with #32170

**Comment by luckysmg** [comment]
`[!] Flutter (Channel beta, v1.7.8+hotfix.2, on Mac OS X 10.15 19A471t, locale
    zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.2 at /Users/luckysmg/flutter
    • Framework revision 2e540931f7 (32 hours ago), 2019-07-02 09:31:07 -0700
    • Engine revision b1cb0d9e9b
    • Dart version 2.4.0
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/luckysmg/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.0, Build version 11M336w
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 36.2.1
    • Dart plugin version 191.7830

[✓] Connected device (2 available)
    • 躺在文景睿手里的iPhoneX • 273b3891b80ba29ad5b7cfae8bf76006c2a5fbec • ios • iOS
      13.0
    • iPhone Xʀ       • B1868194-2FAC-40FA-B0E1-FB0F8FDD298D     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

! Doctor found issues in 3 categories.`

**Comment by tvolkert** [comment]
@luckysmg do you think this is different than https://github.com/flutter/flutter/issues/35638?
