### ISSUE TITLE
Application not hitting 90fps

### ISSUE THREAD

**Issue by fadhlisulaimi** [flutter/flutter#35522]
I am using a oneplus 7 pro which allows the display refresh rate to go up to 90hz, which also means 90fps.

Native android applications run fine and smooth on 90fps. If i can pinpoint to a specific scenarios, for example scrolling of listviews. 

But for flutter application, it is capped at 60fps or lower. Is there a way for me to unlock this limit? Thanks!

**Comment by luckysmg** [comment]
May be you should use release mode instead of debug mode

**Comment by kafein** [comment]
Can you close this issue and use #35162? Its exactly same issue.

**Comment by jckpn** [comment]
@luckysmg This issue occurs regardless of whether the app is in release mode or not.

**Comment by fadhlisulaimi** [comment]
@kafein alright shall close it
