### ISSUE TITLE
xmltree error in flutter while running the first example app

### ISSUE THREAD

**Issue by isjain35** [flutter/flutter#35537]
**Console output:**
Launching lib\main.dart on SM J700F in debug mode...
Initializing gradle...
[{"event":"app.progress","params":{"appId":"0aaf5ea6-2d71-4d0a-a009-874607aa24bd","id":"1","progressId":null,"message":"Resolving dependencies..."}}]Resolving dependencies...

W/ziparchive( 1708): Unable to open 'xmltree': No such file or directory

xmltree: error: failed to open file: The system cannot find the file specified. (2).

Finished with error: Exit code 1 from: C:\Users\admin\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree 
C:\Users\admin\AndroidStudioProjects\flutter_app1\build\app\outputs\apk\app.apk AndroidManifest.xml
![Capture](https://user-images.githubusercontent.com/23081561/60609308-09d91400-9ddf-11e9-9278-202fca75583d.PNG)

**Comment by bpadhiyar4** [comment]
Install the latest Android SDK 29.0 or any latest stable version

**Comment by kangwang1988** [comment]
Also see: https://stackoverflow.com/questions/56715292/unable-to-open-xmltree-error-in-flutter-when-i-try-to-run-fresh-sample-app

**Comment by zyllus17** [comment]
I have 29.0 sdk yet I get this error

Error message:
Finished with error: Exit code -1073741701 from: C:/Users/Zyllus/AppData/Local/Android/Sdk\build-tools\29.0.0\aapt dump xmltree E:\Android_Apps\flutter_app\build\app\outputs\apk\app.apk AndroidManifest.xml


![image](https://user-images.githubusercontent.com/50977126/60765565-1e0c6200-a0ba-11e9-98bb-41d10d1b3234.png)

**Comment by wtnumbawan** [comment]
> I have 29.0 sdk yet I get this error
> 
> Error message:
> Finished with error: Exit code -1073741701 from: C:/Users/Zyllus/AppData/Local/Android/Sdk\build-tools\29.0.0\aapt dump xmltree E:\Android_Apps\flutter_app\build\app\outputs\apk\app.apk AndroidManifest.xml
> 
> Edit: The issue can be solved by removing SDK. I had multiple SDK installed, remove the SDK mentioned and it will start working
> 
> ![image](https://user-images.githubusercontent.com/50977126/60765565-1e0c6200-a0ba-11e9-98bb-41d10d1b3234.png)

thanks, you save me
