### ISSUE TITLE
UNUserNotificationCenterDelegate didReceive is not getting triggered in iOS with Flutter App Delegate

### ISSUE THREAD

**Issue by s-doddapaneni** [flutter/flutter#35534]
I have setup push notifications using APNS for iOS (Using Swift) in the flutter App. didReceiveRemoteNotification is getting triggered when the app receives a push notification from AWS Pinpoint. But none of the other methods are getting triggered when the user taps the notification. Once I handle the user action on the push notification, I can call a scheme using openUrl to specific route on the app.

I have tried by disabling/enabling background modes in the capabilities in the Xcode. Also verified that push notifications are turned on in the capabilities. Pinpoint uses APNS to send the notification to iOS and Firebase to send the notification to Android which is working fine.

Also tried with iOS target version as 10.0, 11.0 and 12.0

UNUserNotificationCenter.current().delegate = self is declared in didFinishLaunchingWithOptions and imported UserNotifications

When I tap the push notification, this is getting printed in the console:

Warning: UNUserNotificationCenter delegate received call to -userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler: but the completion handler was never called.

Payload from pinpoint:
```
[AnyHashable("aps"): {
    alert =     {
        body = "BODY";
        title = "TITLE";
    };
    badge = 0;
    "content-available" = 1;
    "mutable-content" = 0;
    sound = default;
}]
```
iOS Code: 
```
extension AppDelegate: UNUserNotificationCenterDelegate {
        func userNotificationCenter(_ center: UNUserNotificationCenter,
                                    willPresent notification: UNNotification,
                                    withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {

            let userInfo = notification.request.content.userInfo

            // Print full message.
            print(userInfo)

            // Change this to your preferred presentation option
            completionHandler([])
        }

        func userNotificationCenter(_ center: UNUserNotificationCenter,
                                    didReceive response: UNNotificationResponse,
                                    withCompletionHandler completionHandler: @escaping () -> Void) {
            let userInfo = response.notification.request.content.userInfo

            // Print full message.
            print(userInfo)

            completionHandler()
        }

    }
```
didReceive is expected to get triggered when the user taps on the push notification which is not happening in my case.

The one I tried yesterday is "The same code is working perfectly for Native iOS App with Swift" When the same code is running through flutter app, it is not working. The major difference is when I use the FlutterAppDelegate, some call backs are not triggered. 

Can anyone help me on this issue?

**Comment by sperochon** [comment]
I was facing a similar problem with other plugin. iOS swift delegate methods were not triggered. It appears that the methods must have been declared public.

Just replace
```
func userNotificationCenter...
```
with
```
public func userNotificationCenter...
```

Maybe it will helps someone...

**Comment by VladyslavBondarenko** [comment]
Thanks  @sperochon 
@s-doddapaneni does it help?

**Comment by TahaTesser** [comment]
Hi @s-doddapaneni 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
