### ISSUE TITLE
animateTo other tabs with a Scrollable TabBar problem

### ISSUE THREAD

**Issue by SayidHosseini** [flutter/flutter#35530]
Hi,
I have an app with a Scrollable TabBar and with the push of a button, I add tabs (using **`TabController`** not the **`DefaultTabController`**) and use the **`animateTo`** method to navigate to the last tab. That works fine. When there are too many tabs and they don't fit in the screen, the animateTo method still works and navigates to that `TabView`, but the tab itself is not shown in the screen (You should scroll the TabBar **manually** to see the selected tab).
Is there any way to fix this?

I'm not sure if this is a bug report, feature request or simply my lack of knowledge on the matter. Tell me if I have to mention this somewhere else.

**Comment by HansMuller** [comment]
Sadly, this sounds like a bug.

Please provide the output of `flutter doctor` and a small self-contained app that demonstrates the problem and we'll look into it. Note also: https://gist.github.com/ is a useful way to share the code.

**Comment by SayidHosseini** [comment]
Here is the output of the `flutter doctor`:

`
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.557], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] VS Code, 64-bit edition (version 1.35.1)
[√] Connected device (1 available)

• No issues found!
`
 And [here](https://gist.github.com/SayidHosseini/f7c7647fb2bcfd1115ce05e2b60f834b) is the link to the sample self-contained app in Github Gist, demonstrating the problem (the problem presents itself after adding 6 or 7 tabs in my screen).

**Comment by juandiago** [comment]
Also having this issue, looking at the def for _TabController_, _animateTo_ seems to be skipping something on __handleTap_ which triggers a second __changeIndex_ ....

hope is not too confusing....

**Comment by TahaTesser** [comment]
Hi @SayidHosseini @HansMuller 

This issue still exist 

![untitled](https://user-images.githubusercontent.com/48603081/75336288-de94bf00-58b0-11ea-99c5-da783c230360.gif)

**Comment by SayidHosseini** [comment]
> Hi @SayidHosseini @HansMuller
> 
> This issue still exist

The issue is still open. So, yes it still exists...

**Comment by icnahom** [comment]
Had the same issue, `animateTo()` will hopefully  be fixed 🤞

**Comment by markfili** [comment]
so... while we're waiting for a fix... is there a suggestion for a working workaround?

**Comment by TahaTesser** [comment]
This doesn't look like a bug, based on example, it looks `animatedTo` being called in the same function as that created a new TabBar and repeated calling `animateTo` within the function where the new controller is created. 


There is no new issue when you call `animateTo `after the Controller is properly initialized




https://user-images.githubusercontent.com/48603081/143444508-d633eab1-db18-4e2e-8408-1d19b87d60a4.mp4




Closing as this is not an issue and you're not expected to call controller when it is being created
