### ISSUE TITLE
I think overflow should not happen in this case

### ISSUE THREAD

**Issue by drsealks** [flutter/flutter#35549]
Here is the screenshot of the problem. When I tap on the text field, I get the keyboard to type something. Note, that while main ListView is not overflowing, right small column overflows. I think this should not happen? Shouldn't the behaviour of render replicate what happens to the ListView, i.e. I think the right column should be hided under the keyboard?

![merge_from_ofoct](https://user-images.githubusercontent.com/6204851/60622662-bf549900-9dd8-11e9-9f1c-2f6bd6aa2d78.png)

## Steps to Reproduce

I have a project shared on github. I can insert the link here. It is a self contained project, I can point you to the exact location where this render happens. Will this be useful?

Thanks

## Logs

```
I have no problems running the application. Let me know if this is still needed though. 
```

```
For some reason it outputs many error messages when running flutter analyze,though I'm having no problems running the app. Let me know if this is still needed.
```

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-GB)
    • Flutter version 1.5.4-hotfix.2 at /Users/konsof01/work/flutter
    • Framework revision 7a4c33425d (9 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Users/konsof01/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[✓] Connected device (1 available)
    • Konstantin’s iPhone • 00008020-000911142150003A • ios • iOS 12.3.1

! Doctor found issues in 2 categories.
```

**Comment by eseidelGoogle** [comment]
The right column is being made smaller by the keyboard (safe area) appearing.

Is the right column something you wrote yourself, or is that a widget included in the framework?  If it's something you wrote yourself, the fix is to just make it aware of being displayed in smaller areas (e.g. smaller phones or when the keyboard is visible).

If the right column is provided by the Flutter framework, let us know and we can take another look.  Thanks!

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v`  please
