### ISSUE TITLE
Revise CupertinoColors and CupertinoTheme for dynamic colors

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#35541]
Determine whether/how we should adopt dynamic colors.

#### Progress
- [x] Introduce dynamic colors
- [x] apply dynamic colors to cupertino components
  - [x] action_sheet.dart
  - [x] activity_indicator.dart
  - [x] app.dart
  - [x] bottom_tab_bar.dart
  - [x] button.dart
  - [x] date_picker.dart
  - [x] dialog.dart
  - [x] nav_bar.dart
  - [x] page_scaffold.dart
  - [x] picker.dart 
  - [x] refresh.dart
  - [x] route.dart
  - [x] scrollbar.dart
~- [ ] segmented_control.dart~ Going to make this a new widget.
  - [x] slider.dart
  - [x] switch.dart
  - [x] tab_scaffold.dart -- PR opened
  - [x] text_field.dart -- PR opened
  - [x] text_selection.dart -- https://github.com/flutter/flutter/pull/41859
  - [x] text_theme.dart -- https://github.com/flutter/flutter/pull/41859
  - [x] theme.dart -- PR opened
  - [x] thumb_painter.dart
- [x] Make a new widget to succeed `CupertinoSegmentedControl` https://github.com/flutter/flutter/issues/33796.  
- [x] update flutter_gallery -- PR opened https://github.com/flutter/flutter/pull/43841/

#### Nice to have 
~- [ ] https://github.com/flutter/flutter/pull/41859/files#r331609336 MORE ASSERTS, e.g. if a `CupertinoDynamicColor` is used to paint before being resolved.~ Can't because that will break people using `CupertinoColors.activeBlue`
- [x] Some dynamic colors should be given canonical names (such as `systemBlue`) and should show up nicely in devtools/logs. https://github.com/flutter/flutter/pull/44317
- [ ] Code-gen constants as much as possible: https://github.com/flutter/flutter/pull/41859/files#r336199469

**Comment by xster** [comment]
@LongCatIsLooong it looks like you're done here
