### ISSUE TITLE
flutter exited unexpectedly

### ISSUE THREAD

**Issue by rajkumar112** [flutter/flutter#35545]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by rajkumar112** [comment]
My flutter unexpectedly crashed. It says flutter has exited unexpectedly when i just added some google fonts in pubspec.ymal Plz help me here ......
![Screenshot_2](https://user-images.githubusercontent.com/24261722/60618923-31d47180-9df7-11e9-98e6-b1b66d551534.png)
![Screenshot_3](https://user-images.githubusercontent.com/24261722/60618925-31d47180-9df7-11e9-8d4f-7fe5c0cb3cb2.png)
![Screenshot_4](https://user-images.githubusercontent.com/24261722/60618926-326d0800-9df7-11e9-82d8-bdb78759bfa6.png)

**Comment by Maxartes** [comment]
I have a similar bug
![E4](https://user-images.githubusercontent.com/6472346/60625804-3da44180-9dbf-11e9-9e36-f8a561e61025.png)

**Comment by BondarenkoStas** [comment]
@rajkumar112 did you manage to solve the issue? Please do not include screenshots of code. This makes it extremely tedious to reproduce the issue, as we would have to manually transcribe your example.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
