### ISSUE TITLE
cloud_firestore needs metadata for QuerySnapshot (in addition to DocumentSnapshots in it)

### ISSUE THREAD

**Issue by gazialankus** [flutter/flutter#35550]
`metadata` in `QuerySnapshot` is an existing Firestore feature in other platforms but it's not there in Flutter. 

The Flutter cloud_firestore library's `QuerySnapshot` object needs to provide a `metadata` field that indicates whether the query result is coming from the cache or the server. The individual `DocumentSnapshot` objects in `QuerySnapshot` have this `metadata` field; however, when the query result is empty, we don't get any `DocumentSnapshot` objects and we have no idea whether the `QuerySnapshot` came from the cache (offline) or from the server. 

[Android](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/QuerySnapshot.html) and [Web](https://firebase.google.com/docs/reference/js/firebase.firestore.QuerySnapshot) already have `metadata` in `QuerySnapshot`. I didn't check other platforms. 

I was hoping I could fix it myself and provide a PR, however it seems we just don't get that data under the hood. When I set a breakpoint [here](https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/lib/src/query.dart#L101), I see that `data`, which is the result of `Query#getDocuments` has only these fields: 

```
0 = {map entry} "documentChanges" -> [_List]
1 = {map entry} "documents" -> [_List]
2 = {map entry} "metadatas" -> [_List]
3 = {map entry} "paths" -> [_List]
```

The `metadatas` field is related to the individual `DocumentSnapshot`s. When the query result is empty, all of these lists are empty as well. Hence the lack of metadata about our query.

It seems this is coming from a platform channel, so definitely it must be using Android Firebase libraries. However, as I said above, Android libraries **have** `metadata` for `QuerySnapshot` but Flutter, which seems to be using the Android libraries through a platform channel does not have it. Is this because the Flutter plugin is using an old version of the Android library? 

The current way to add [Firebase to Flutter](https://firebase.google.com/docs/flutter/setup) does not have anything about Android Firebase library versions. Only `classpath 'com.google.gms:google-services:3.2.1'` seems to be a versioned thing, is it what's holding this back? I tried 4.2.0 but it's the same. 

[Here](https://firebase-community.slack.com/archives/C7CQWAH7F/p1560889979183600) is a relevant discussion in Slack. I'd appreciate any suggestion.

**Comment by katowulf** [comment]
@kroikie fyi

**Comment by kroikie** [comment]
Looks like when parsing the QuerySnapshot the metadata of the QuerySnapshot is not included in the data that is passed back to the Dart side. I don't see any reason we could not add a field for this.
