### ISSUE TITLE
Text on gallery cards screen extends beyond card

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3555]
See image (image from iPod touch)

![img_0001](https://cloud.githubusercontent.com/assets/1539812/14827705/7b19af12-0b98-11e6-8bbe-c3b1de4de454.PNG)

**Comment by sethladd** [comment]
Good catch. Just iOS?

**Comment by vlidholt** [comment]
My Android devices have a wider screen, so I think that may be why it only looks bad on iOS.

**Comment by eseidelGoogle** [comment]
@HansMuller thinks this may be fixed.
