### ISSUE TITLE
 On the Android system, how the TextField hides the keyboard but does not lose focus. I can't find the relevant api.

### ISSUE THREAD

**Issue by jicg** [flutter/flutter#35567]
On the Android system, how the TextField hides the keyboard but does not lose focus. I can't find the relevant api.

**Comment by iapicca** [comment]
Hi @jicg 
are you still experiencing this issue with the latest stable version of flutter?
If so could you please provide your updated `flutter doctor -v` 
and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by TahaTesser** [comment]
Hi @jicg 
Closing as there are not sufficient details to act upon this issue. If the problem persists, please create a new issue and provide the information required in the template.
Thank you
