### ISSUE TITLE
iOS doesn't use correct fonts and typography

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3556]
iOS screenshot:
![img_0002](https://cloud.githubusercontent.com/assets/1539812/14827860/36f1c1fc-0b99-11e6-904a-46dd1b674003.PNG)

Android for reference:
![flutter_01](https://cloud.githubusercontent.com/assets/1539812/14827943/959dc1ba-0b99-11e6-8aae-9f477ca49a29.png)

**Comment by chinmaygarde** [comment]
This fixes the font selection issue https://github.com/flutter/flutter/commit/35ea6a1cefd1af0bf72afc24adb7da0fc15333a9
