### ISSUE TITLE
[Firebase ML Vision] - Face detection and video recording running in parallel

### ISSUE THREAD

**Issue by ysrarff** [flutter/flutter#35564]
Hi, I was wondering if there is any way to use the ML kit (face detection) in real-time while also running the video recording in parallel? After inspecting the camera module, it seems that it can only do one or the other, as ML kit takes a CameraImage argument inside .startImageStream() and a String path argument inside .startVideoRecording(). 

It would be helpful if it's possible to do both at the same time. I've been exploring other methods of recording the stream as well, via encoders such as FFmpeg to resolve the conflict of camera controllers but it suffered from performance issues. Any form of assistance would be deeply appreciated.

**Comment by kroikie** [comment]
@ysrarff

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1156. Any further collaboration will be done there.
