### ISSUE TITLE
How to get the framerate of flutter desktop app?

### ISSUE THREAD

**Issue by ping996** [flutter/flutter#35579]
How to get the framerate of flutter desktop app?

## Logs

```
```

```
```

**Comment by stuartmorgan** [comment]
[The performance overlay](https://flutter.dev/docs/testing/ui-performance#the-performance-overlay) should work the same way on desktop that it does on mobile.

If you are having issues making it work on desktop, please file a new bug that includes details of exactly what steps you are trying and what is/isn't happening.

**Comment by ping996** [comment]
@stuartmorgan  Thanks for you help. I have tried it on my desktop app and works fine.
