### ISSUE TITLE
iOS toolbar color should be light by default (maybe even settable)

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3557]
The iOS toolbar is drawn in black by default. Material design usually use dark material for the top of the screen, so the iOS toolbar should probably be set to be drawn in light by default.

![img_0002](https://cloud.githubusercontent.com/assets/1539812/14828062/1901f8c8-0b9a-11e6-8122-d06eaa96823e.PNG)

**Comment by chinmaygarde** [comment]
This is now configurable via `SystemUIOverlayStyle` in `system_chrome.mojom`
