### ISSUE TITLE
Change map value in setState((){...}) will block program

### ISSUE THREAD

**Issue by FitzLu** [flutter/flutter#35570]
There is a map passed from android native, and receive in flutter through method channel. If I set the map value to _oldMap directly, program will not go on,  "2" will not be printed.

Here is the code:
```
Map newMap = methodCall.arguments;
setState(() {
    print("1");
    _oldMap = newMap;
    print("2");
});
```

console outputs:
```
1
```

But if i use a temporary map copy newMap value, then set the temporary map to _oldMap, everything is ok.

here is the code:

```
Map newMap = methodCall.arguments;
Map tempMap = Map();
newMap.forEach((k, v){
   tempMap[k] = v;
});
setState(() {
    print("1");
    _oldMap = tempMap;
    print("2");
});
```

console output:
```
1
2
```

What is the special with the map receive from method channel

**Comment by BondarenkoStas** [comment]
@FitzLu Is it the same while using current flutter stable v1.9.1+hotfix.2?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
