### ISSUE TITLE
firebase_core warning unchecked method invocation found: Map, required: E.

### ISSUE THREAD

**Issue by psyanite** [flutter/flutter#35586]
I can build my app successfully, however in the build logs I see two warnings that I am cautious of "unchecked method invocation" found: Map, required: E.

Does anyone else have this or is this just me due to a specific version of something?

## Steps to Reproduce
Run Flutter application in IntelliJ
See logs:
```
C:\Apps\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.0+6\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java:76: warning: [unchecked] unchecked method invocation: method add in interface List is applied to given types
            apps.add(asMap(app));
                    ^
  required: E
  found: Map
  where E is a type-variable:
    E extends Object declared in interface List
```

## Pubspec.yaml
```
    firebase_core: 0.4.0+6
    firebase_storage: ^3.0.2
    firebase_auth: ^0.11.1+7
```

## Flutter Doctor
```
C:\Apps\flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.829], locale en-AU)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[!] VS Code (version 1.33.0)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)
```

I'm running 1.5.4-hotfix because I think that's the most stable/latest version?

**Comment by x8Haider** [comment]
Same here, the issue is with firebse-core plugin. 
In my case the build is not working in real phone.

**Comment by BondarenkoStas** [comment]
@psyanite Is it the same while using current flutter stable and firebase_core 0.4.0+9?

**Comment by psyanite** [comment]
@BondarenkoStas 
Thanks for taking the time to look into my issue. I will check tonight and get back to you.

**Comment by kroikie** [comment]
@psyanite

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1131. Any further collaboration will be done there.

**Comment by psyanite** [comment]
Thanks!
