### ISSUE TITLE
Date picker no longer matches the spec

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3558]
From the gallery:

![img_0003](https://cloud.githubusercontent.com/assets/1539812/14828133/6d03156a-0b9a-11e6-806a-00447c755241.PNG)

From the spec (https://www.google.com/design/spec/components/pickers.html#pickers-date-pickers):

![components_pickers_date1](https://cloud.githubusercontent.com/assets/5479/15341906/613598cc-1c46-11e6-925a-1b5a4888b6fa.png)

**Comment by sethladd** [comment]
Looks like we need more space between month name and the weeks. From the calendar app:

![screenshot_20160517-153205](https://cloud.githubusercontent.com/assets/5479/15341860/11e27efc-1c46-11e6-85d0-7778356518df.png)
