### ISSUE TITLE
Because flutter_xxx depends on validator ^1.7.0 which doesn't match any versions, version solving failed.

### ISSUE THREAD

**Issue by petrfalkovsky** [flutter/flutter#35583]
Hey, when i try to get validator package, i see issue like on screenshot, how to fix it?
I tryed to do this step via 2 onether ip's - not works)
![photo_2019-07-04_11-57-07](https://user-images.githubusercontent.com/13994582/60653722-e51a8600-9e4a-11e9-8d8d-f40ff80b2cbf.jpg)

**Comment by petrfalkovsky** [comment]
I solved this problem with this steps:
1. Run Git bush as admin
2. Relocate to folder with my project using git bash comand `cd /c/Users/User/material-components-flutter/mdc_100)series/` for example
3. And run comand in git bush like 
`flutter packages get`

**Comment by BondarenkoStas** [comment]
@petrfalkovsky Cool, I think it's safe to close this one.
