### ISSUE TITLE
Flutter app build fails on Mac

### ISSUE THREAD

**Issue by ighidan** [flutter/flutter#35589]
Hi,

I get the following error when I run debug. Any idea? I use xCode 9.2 on MacOS Sierra 10.12.6 with latest version of flutter.

Note: I was able to build the Android app with no errors.

Thanks

------------

Launching lib/main.dart on iPhone X in debug mode...
Running pod install...                                              5.1s
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                           2.0s
 └─Compiling, linking and signing...                         0.9s
Xcode build done.                                            6.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    ld: warning: linking ObjC for iOS Simulator, but dylib
    (/Users/Apple/Desktop/ig/flutter/bin/cache/artifacts/engine/ios/Flutter.framework/Flutter) was compiled for MacOSX
    Undefined symbols for architecture x86_64:
      "_sqlite3_prepare_v3", referenced from:
          -[APMSqliteStore prepareSQL:error:] in GoogleAppMeasurement(APMSqliteStore_645df61703f07a6639f4b1de4d0cf5c3.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone X.

**Comment by stuartmorgan** [comment]
Firebase needs a newer version of Xcode, see https://stackoverflow.com/questions/56703880/how-to-fix-sqlite3-prepare-v3-linker-error-in-xcode

**Comment by kroikie** [comment]
@ighidan

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/359. Any further collaboration will be done there.
