### ISSUE TITLE
image_picker save Image /video

### ISSUE THREAD

**Issue by atheist1** [flutter/flutter#35585]
## Steps to Reproduce

Hi.There is a problem happened while i want to send a video which i got from the imagePicker to the internet, and there are my codes.  
 ``` javascript
    var video = await ImagePicker.pickVideo(source: ImageSource.camera);
    String path = video.path;
    // i saved the path into localstorage
    File.fromUri(Uri.file(path)) ;
    Stream<List<int>> inputStream = f.openRead();
    await _socket.addStream(inputStream);
````
## Logs
```
 Unhandled Exception: FileSystemException: Cannot open file, path = 'file:///private/var/mobile/Containers/Data/Application/1611DC5E6C-0CDAE-4D40-9137-57/tmp/BF643D8B0-C0WD1-4F82-B83X4-AA3306F01X6B2.MOV' (OS Error: No such file or directory, errno = 2)
```

**Comment by arkivika** [comment]
Hi,

Check out this issue: #29670

So if this is happening on an iOS device, try fixing the path with the following:

```
if (file.path.indexOf('file://') == 0) {
    file = File(
        file.path.split('file://')[1],
    );
}
```

**Comment by atheist1** [comment]
> Hi,
> 
> Check out this issue: #29670
> 
> So if this is happening on an iOS device, try fixing the path with the following:
> 
> ```
> if (file.path.indexOf('file://') == 0) {
>     file = File(
>         file.path.split('file://')[1],
>     );
> }
> ```

it works.Thanks.
