### ISSUE TITLE
Allow setting initial value in CupertinoPicker

### ISSUE THREAD

**Issue by dvorapa** [flutter/flutter#35599]
## Use case
There is no way to set initial value in CupertinoPicker. Therefore usage like:

95%
**100%**
105%

where 100% is the initial value is not possible.

## Proposal
Proposing `int initialValue: 0` (`initialValue: index`) as a constructor parameter.

**Comment by kangwang1988** [comment]
@dvorapa 
I found a code snippet like:
```dart
CupertinoPicker(
                scrollController: scrollController,
                itemExtent: _kPickerItemHeight,
                backgroundColor: CupertinoColors.white,
                onSelectedItemChanged: (int index) {
                  setState(() => _selectedColorIndex = index);
                },
                children: List<Widget>.generate(coolColorNames.length, (int index) {
                  return Center(
                    child: Text(coolColorNames[index]),
                  );
                }),
              )
```
Are you saying to give it a default index instead of index 0 as the default?

**Comment by dvorapa** [comment]
Code snippet does not work. Yes, there should be some option to set default/initial position/item in list, like this:

```
Text('Select size:'),
CupertinoPicker(
  itemExtent: 70.0,
  onSelectedItemChanged: _changeSize,
  children: List<Widget>.generate(5, (int index) {
    Text(['90%', '95%', '100%', '105%', '110%'][index])
  }),
  initialValue: 3,
),
```

Select size:
95%
100%
105%

**Comment by dvorapa** [comment]
Or perhaps would be better something like:

```
CupertinoPicker(
  itemExtent: 70.0,
  onSelectedItemChanged: _changeSize,
  children: List<Widget>.generate(5, (int index) {
    Text(['90%', '95%', '100%', '105%', '110%'][index])
  }),
).initial(3), // initially set index to 3,
```
as this is only used when initializing the widget in app?

**Comment by dvorapa** [comment]
Compare to numberpicker pub package, which contains initialValue option: https://pub.dev/documentation/numberpicker/latest/ but the numberpicker widget is limited to displaying int numbers only. The new option for CupertinoPicker could be named initialValue, initialIndex, or initialItem.

**Comment by LongCatIsLooong** [comment]
You should be able to set the initial index in its controller: https://api.flutter.dev/flutter/widgets/FixedExtentScrollController-class.html. Closing. Feel free to reopen if that doesn't work.

**Comment by dvorapa** [comment]
Yes that does not work, please reopen.

**Comment by LongCatIsLooong** [comment]
@dvorapa just tested with the following code it worked for me. The initial item became 105%. 
```dart
CupertinoPicker(
  itemExtent: 70,
  onSelectedItemChanged: _changeSize,
  children: List<Widget>.generate(5, (int index) {
    return Text(['90%', '95%', '100%', '105%', '110%'][index]);
  }),
  scrollController: FixedExtentScrollController(initialItem: 3),
)
```
Or maybe I missed something?

**Comment by dvorapa** [comment]
Oh, now I see, I've had a typo in my attempt, sorry :D

**Comment by SaurabhAgarwala** [comment]
When I am setting the value of `initialItem` property in FixedExtentScrollController() using the `List.indexOf(element)` method, then the value is set to 0 only, despite the element not being in the 0th index of the list. Here's my code:
```dart
CupertinoPicker(
      scrollController: FixedExtentScrollController(
        initialItem: cryptoList.indexOf(selectedCurrency),
      ),
      backgroundColor: Colors.lightBlue,
      itemExtent: 32.0,
      onSelectedItemChanged: (selectedIndex) {
        setState(() {
          selectedCurrency = currenciesList[selectedIndex];
          getExchangeRates(selectedCurrency);
        });
      },
      children: pickerItems,
    );
```

Can you please reopen this issue?

**Comment by edwin-alvarez** [comment]
I tried to use this code with a variable in my case **initialValue** but, So I can change the index with a button, but the selected index does not change.

```
CustomCupertinoPicker(
  onSelectedItemChanged: (int index) {
  },
  itemExtent: 50,
  children: List<Widget>.generate(5, (int index) {
    return Text(['0', '1', '2', '3', '4','5', '6', '7', '8', '9','10', '11', '12', '13', '14'][index]);
  }),
  scrollController: FixedExtentScrollController(initialItem: initialValue),
),
```

**Comment by edwin-alvarez** [comment]
as workarround i found that I can use assign the  FixedExtentScrollController to a variable (fe1) and then call animateTo
fe1.animateTo(50.0 * monthlySummary.totalBibleStudyCompleted,
              duration: Duration(milliseconds: 200), curve: Curves.ease);
