### ISSUE TITLE
Setting VM flags failed: Unrecognized flags: checked

### ISSUE THREAD

**Issue by AweiLoveAndroid** [flutter/flutter#35594]
What's wrong?

When I writing a test file in a plugin.When running the problem happens. 

```
E:\develop\flutter\bin\cache\dart-sdk\bin\dart.exe --checked --enable-vm-service:38306 F:\workspaces\flutter_demo\example\test\tests.dart
Setting VM flags failed: Unrecognized flags: checked

Process finished with exit code 255
```

Please solve it.Wait online.Hurry up.

**Comment by jeking3** [comment]
Did you try it without --checked ?
Did you recently update to Dart 2.4 ?
I am seeing the same thing, different build (Apache Thrift).

**Comment by AweiLoveAndroid** [comment]
@jeking3  The version is Dart 2.3,

**Comment by jeking3** [comment]
Try changing the deprecated option `--checked` to `--enable-asserts` when you run.

**Comment by BondarenkoStas** [comment]
@AweiLoveAndroid did you manage to solve the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by asriyadiPNUP** [comment]
Go to this link
https://stackoverflow.com/questions/57021221/setting-vm-flags-failed

it worked for me

**Comment by deliaslan** [comment]
Run > Edit Configurations 
VM Options (Cheched Mode) ----> uncheck it.
That's All
