### ISSUE TITLE
FlutterEngine and FlutterBinaryMessenger documentation

### ISSUE THREAD

**Issue by vitor-gyant** [flutter/flutter#35590]
Hi,

I was trying to create a FlutterMethodChannel instance by calling the following method:

```
+ (instancetype)methodChannelWithName:(NSString*)name
                      binaryMessenger:(NSObject<FlutterBinaryMessenger>*)messenger;
```

The docs state that FlutterEngine conforms to FlutterBinaryMessenger however, the interface declaration does not:

`@interface FlutterEngine : NSObject <FlutterTextureRegistry, FlutterPluginRegistry>`

It seems that I should be using engine.binaryMessenger instead. 

```
/**
 * The `FlutterBinaryMessenger` associated with this FlutterEngine (used for communicating with
 * channels).
 */
@property(nonatomic, readonly) NSObject<FlutterBinaryMessenger>* binaryMessenger;
```

I think that the documentation should be updated accordingly.

Thanks,

**Comment by stuartmorgan** [comment]
@gaaclarke

**Comment by pedromassangocode** [comment]
Hi @vitor-gyant 
Are you still facing this issue?

**Comment by stuartmorgan** [comment]
This is a valid issue; the engine is no longer itself a binary messenger.

**Comment by gaaclarke** [comment]
What documentation?  The docstrings for FlutterEngine.h are correct.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
