### ISSUE TITLE
List swipe to action is missing shadow and has incorrect padding

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3560]
The list's swipe to remove is missing shadow and have extra padding that shouldn't be there:

![img_0005](https://cloud.githubusercontent.com/assets/1539812/14828461/ec68df14-0b9b-11e6-940f-172a25d63c15.PNG)

Spec:

<img width="402" alt="screen shot 2016-04-26 at 10 43 33 am" src="https://cloud.githubusercontent.com/assets/1539812/14828473/f6cfa9b0-0b9b-11e6-8e32-fdc3fd739424.png">

**Comment by HansMuller** [comment]
We're not going to support the inset shadows shown above and in the "Leave-behinds" subsection of the MD spec for now (see  See https://www.google.com/design/spec/components/lists-controls.html#lists-controls-types-of-list-controls).

**Comment by eseidelGoogle** [comment]
@HansMuller curious why?  Presumably they're slow? :)

**Comment by abarth** [comment]
@eseidelGoogle The real solution is to use volumetric shadows, which will compute the correct shadows in all cases.  The shadows in the mock aren't correct w.r.t. the physical shadow model described in the spec (which isn't surprising because no one implements physically correct volumetric shadows yet).

**Comment by HansMuller** [comment]
Right. And it didn't seem important enough for v1 to include a hack that rendered something like what's in the MD spec.

**Comment by eseidelGoogle** [comment]
sgtm, thanks for the context!

**Comment by sethladd** [comment]
Also could be done at the same time: https://github.com/flutter/flutter/issues/3980
