### ISSUE TITLE
Firestore Transaction throws uncaught PlatformException "Transaction has already completed"

### ISSUE THREAD

**Issue by sceee** [flutter/flutter#35604]
## Steps to Reproduce
1. Use cloud_firestore: ^0.12.6 (but also happened in ^0.12.1)
2. Run a Firestore Transaction using the following code (write code would come after the get but this does not have any effect on the exception):
```
TransactionHandler orderTransactionHandler =
            (Transaction transaction) async {
          DocumentReference docRef = _db.document('coll/123/coll2/567');
          DocumentSnapshot docSnap = await transaction.get(docRef); // Exception is thrown here
          // Write code would be here...
          return new Map<String, dynamic>();
        };
Firestore.instance.runTransaction(orderTransactionHandler)
```
3. Uncaught Exception is thrown: `PlatformException (PlatformException(Error performing Transaction#get, Transaction has already completed., null))`

## Logs

```
The verbose logs do not contain logged errors but here is the Stack from VS Code
```
![image](https://user-images.githubusercontent.com/11340487/60685885-e62cd100-9ea5-11e9-807d-f9d6c1d5620c.png)

```
Analyzing App...
No issues found! (ran in 7.2s)
```

```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.829], locale de-DE)
    • Flutter version 1.5.4-hotfix.2 at ...
    • Framework revision 7a4c33425d (9 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at ...
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = ...
    • Java binary at: ...
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at ...
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.0)
    • VS Code at ...
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • ... • ... • android-arm64 • Android 6.0.1 (API 23)

• No issues found!
```

**Comment by thevzurd** [comment]
I had the same problem. Try this. Hope it Helps 
[FIrestore Transaction Handler](https://github.com/thevzurd/Firestore-Transaction-Handler)

**Comment by janmoppel** [comment]
Hello @sceee !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by baylessj** [comment]
I have also encountered this same error in the latest stable version of cloud_firestore. It has been a persistent issue for a few months now, and multiple issues have been opened for it in various places both in this repo and elsewhere on the internet, and it still has not received a fix.

**Comment by kroikie** [comment]
@sceee

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1219. Any further collaboration will be done there.
