### ISSUE TITLE
Provide flutter_infra release urls that always point to the latest for a channel

### ISSUE THREAD

**Issue by josh-burton** [flutter/flutter#35606]
Precompiled flutter_infra releases are great for CI, but I need to keep updating my CI settings whenever a new release comes out.

Can we have a URL for each channel (master/dev/beta) that always points to the latest version for that channel?

https://flutter.dev/docs/development/tools/sdk/releases?tab=macos

**Comment by tvolkert** [comment]
If we had this, we could use it to provide a more intelligent version freshness check.

https://github.com/flutter/flutter/blob/49cce984834c5a007a15e74988f7a153cff32705/packages/flutter_tools/lib/src/version.dart#L286

/cc @zanderso @digiter

**Comment by zanderso** [comment]
> If we had this, we could use it to provide a more intelligent version freshness check.

Do you mean doing something like parsing the version number out of the url that the 'latest' url resolves to?

**Comment by tvolkert** [comment]
Yeah, I'm picturing a single JSON endpoint that provides the latest version on each channel.

**Comment by digiter** [comment]
Triage: what's needed from the infra team?

**Comment by godofredoc** [comment]
Obsolete. Please reopen if still needed.
