### ISSUE TITLE
build on iOS not working

### ISSUE THREAD

**Issue by tomosullivan8** [flutter/flutter#35605]
I have an issue when trying to build on iOS.

I get the following issue -

```
Launching lib/main.dart on macOS in debug mode...
xcodebuild: error: '/Users/tomosullivan/Development/Projects/law/macos/Runner.xcworkspace' does not exist.
```

I'm not sure why it's giving this error and saying launching on macOS or looking for the Runner file in the macOS folder when it's in the iOS folder? I'm using the simulator iPhone X.

I've tried upgrading and running the flutter doctor but the issue still remains.

**Comment by stuartmorgan** [comment]
That logging indicates that it is trying to build and run for macOS, not iOS. We'll need more info to see why:

- What is the exact command you are using to try to build?
- What does `flutter version` show?
- What does `flutter devices` show?
- Do you have a `macos/` folder in that project?

**Comment by tomosullivan8** [comment]
I've realised that because the macbook itself is a connected device when I run the command `flutter run -d all` it picks up the macOS as well.

How do I choose specific devices to run on? It asks for `please specify a device with the '-d <deviceId>'` - but how do i find the device ID? I tried using those found on `flutter devices` but it didn't work.

Thanks

**Comment by tomosullivan8** [comment]
Got it to work - not sure why `flutter run -d iphone` didn't work first time round!

**Comment by stuartmorgan** [comment]
> when I run the command `flutter run -d all` it picks up the macOS as well

Thanks for following up with details; that's definitely a bug for a project with no macOS support.

**Comment by tomosullivan8** [comment]
Hopefully it can be fixed to be just be mobile devices unless specified, quite annoying opening multiple terminals and having to run separately (often I forget only one has been run on one device and wonder why it's not updated!).

**Comment by ollydixon** [comment]
1.7.8+hotfix.3 ```flutter run -d iphone``` doesn't work.

**Comment by tomosullivan8** [comment]
What output do you get with `flutter run`?

**Comment by ollydixon** [comment]
It says ```Found 2 devices with name or id matching iphone:``` lists the devices and then doesn't run. Also there are several release errors with 1.7.8+hotfix.3 :*-(

**Comment by tomosullivan8** [comment]
If you've got more than one iPhone open in the simulator you'll need to give a more unique description! So for example if you've got the iPhone 6 open you'll need to put in `flutter run -d iphone 6` and it should work? If you try that and see how you get on.

There is another way of finding the device ID, if you look at the link it'll give some example of what you can use :)

https://stackoverflow.com/q/49684621/9267159

**Comment by ollydixon** [comment]
@tomosullivan8 the behavior before (```flutter run -d all```) was that all the devices would run in debug mode and we could refresh them be pressing R and see all the errors logged on one terminal. This was awesome.

I'm testing an app now that requires 7 devices to be open at the same time, are you telling me I now have to run them all independantly? That sucks.

**Comment by tomosullivan8** [comment]
I know the feeling, I want to test to have the Tablet, Phone Portrait and Phone Landscape to ensure it works in all display sizes so have 3 emulators open but now it's a hassle trying to refresh. 

As @stuartmorgan pointed out it appears to be a bug and should be fixed soon. They have closed the issue on #35652 so hopefully it'll be with us shortly!

**Comment by tomosullivan8** [comment]
@ollydixon looks like this issue is fixed now with a flutter upgrade? Worked for me a second ago!

**Comment by ollydixon** [comment]
@tomosullivan8 yeah it's fixed on hotfix 4 :-D

**Comment by ollydixon** [comment]
From 17.0.5 it's broken again, been broken for a few months now; extremely annoying.
