### ISSUE TITLE
[android_alarm_manager] Callback is not called if app has been opened from Intent

### ISSUE THREAD

**Issue by hugocbpassos** [flutter/flutter#35603]
If you schedule an `oneShot()` to call `aFunction()` in 10 seconds, then close the app and open it again through an android-intent, `aFunction()` is never called, even if the app is in background. Alarm-manager starts working again only when the app-instance (opened from intent) terminates.

As a practical example, I use `android_alarm_manager` along with `android_intent` to open my app and show an alarm-screen at a specific time. After the first alarm opens my app, I can lose the second alarm if the same app-instance keeps opened.

## Steps to reproduce

1. Set up the Android part of alarm-manager, as described [here](https://pub.dev/packages/android_alarm_manager#getting-started).

2. Add [`flutter_local_notifications`](https://pub.dev/packages/flutter_local_notifications) dependency and copy the `ic_launcher.png` to the `drawable` folder of Android. We are going to show a local-notification from the background-function to precisely indicate whether it succeeded to run or not. This is necessary because neither the console nor the Flutter UI is going to be available.

3. Add [`android_intent`](https://pub.dev/packages/android_intent) dependency. We are going to use it to open the app from the background-function.

4. Run the following code, changing the `package` and `componentName` of the function `openApp()` to the package and component name of your app:

```dart
import 'dart:math';

import 'package:android_alarm_manager/android_alarm_manager.dart';
import 'package:android_intent/android_intent.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

void main() async {
  await AndroidAlarmManager.initialize();
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              RaisedButton(
                onPressed: scheduleAlarmManagerToShowNotificationIn5Seconds,
                child: Text('Show notification in 5 seconds'),
              ),
              RaisedButton(
                onPressed: scheduleAlarmManagerToOpenAppIn5Seconds,
                child: Text('Open app in 5 seconds'),
              ),
            ],
          ),
        ),
      ),
    );
  }

  void scheduleAlarmManagerToShowNotificationIn5Seconds() async {
    await AndroidAlarmManager.oneShot(
      const Duration(seconds: 5),
      Random().nextInt(999999999),
      showNotification,
    );
  }

  void scheduleAlarmManagerToOpenAppIn5Seconds() async {
    await AndroidAlarmManager.oneShot(
      const Duration(seconds: 5),
      Random().nextInt(999999999),
      openApp,
    );
  }
}

void showNotification() async {
  final localNotifications = FlutterLocalNotificationsPlugin()
    ..initialize(
      InitializationSettings(
        AndroidInitializationSettings('ic_launcher'),
        null,
      ),
    );

  await localNotifications.show(
    Random().nextInt(999999999),
    'Title',
    'Body',
    NotificationDetails(
      AndroidNotificationDetails(
        'channel_id',
        'channel_name',
        'channel_description',
      ),
      null,
    ),
  );
}

void openApp() async {
  await AndroidIntent(
    action: 'android.intent.action.MAIN',
    package: 'dev.hugopassos.buster',
    componentName: 'dev.hugopassos.buster.MainActivity',
  ).launch();
}
```

5. You can check that the background-function `showNotification()` is working by pressing the button "Show notification in 5 seconds" and sighting the notification.

6. Press the button "Open app in 5 seconds" and close the app. After a while, it should be restarted.

7. Now, since the app was opened from an intent, the background-functions should no longer work. If you tap "Show notification in 5 seconds", nothing is going to happen. If you tap "Open app in 5 seconds" and put your app in background, nothing in going to happen (usually, the app comes to foreground).

This can also be reproduced by using an app that opens activities, such as [Activity Manager](https://play.google.com/store/apps/details?id=com.andrefrsousa.tools.activitymanager), but, for this problem to happen, you have to open the example app through the Activity Manager twice (don't ask me why).

**Comment by hugocbpassos** [comment]
I'm closing this issue since I can no longer reproduce it.

**Comment by firedark7981** [comment]
hi

**Comment by firedark7981** [comment]
i dont know how i can replace my package name and component name i did it like this 

> 
> void openApp() async {
> 
>   await AndroidIntent(
>     action: 'android.intent.action.MAIN',
>     package: 'com.example.AlarmManagerTest',
>     componentName: 'com.example.AlarmManagerTest.Application',
>   ).launch();
> }
> 
but i got an error : ```
E/MethodChannel#plugins.flutter.io/android_intent(28440): Failed to handle method call
E/MethodChannel#plugins.flutter.io/android_intent(28440): android.content.ActivityNotFoundException: **Unable to find explicit activity class {com.example.AlarmManagerTest/com.example.AlarmManagerTest.App}; have you declared this activity in your AndroidManifest.xml?**
can you help me to do it?
```
