### ISSUE TITLE
[!] Unable to find a specification for `MTBBarcodeScanner` depended upon by `barcode_scan`

### ISSUE THREAD

**Issue by topjx** [flutter/flutter#35619]
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

cd myApp
pod install

[!] Unable to find a specification for `MTBBarcodeScanner` depended upon by `barcode_scan`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by topjx** [comment]
pod --version
1.7.2

**Comment by topjx** [comment]
https://github.com/CocoaPods/CocoaPods/issues/2543

**Comment by JiweiMaster** [comment]
how to solve this probelm???

**Comment by prakhar-goel** [comment]
I have same problem:
```
[!] Unable to find a specification for `TOCropViewController (~> 2.5.4)` depended upon by `image_cropper`
```
