### ISSUE TITLE
`CheckedPopupMenuItem` is too wide

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3561]
Too much space in drop down lists with IconButton. Also, the padding in the list is off. Example from Gallery / Menus

![img_0007](https://cloud.githubusercontent.com/assets/1539812/14828549/47c2eb3e-0b9c-11e6-9ae8-36f4a77ae826.PNG)

**Comment by sethladd** [comment]
Can you grab a screenshot from Android? We looked at this issue before and determined we met the spec.

**Comment by vlidholt** [comment]
Same issues on Android. I think this may be a regression. Also, this demo stops responding on Android.

**Comment by HansMuller** [comment]
The MD spec implies that there should be 24 pixels to the left of the check and that it should be left justified within its own 40 pixel wide column:

![spec-screenshot](https://cloud.githubusercontent.com/assets/1377460/14865148/1892daa0-0c72-11e6-90be-f3fef9f0087a.png)

The result is that the check looks roughly centered in a sea of horizontal white space. Also from the spec:

![spec-too](https://cloud.githubusercontent.com/assets/1377460/14865356/224ed7fa-0c73-11e6-9a25-d373c7c2c196.png)

I believe that in our case there's an extra 16 pixels of padding on the right that's being contributed by the margin ListItem adds  on the right of it's leading widget.

**Comment by HansMuller** [comment]
Note also: I'm not seeing any responsiveness problems with menus on Android.

**Comment by Hixie** [comment]
I don't understand what is the expected behaviour here. Can you elaborate?

**Comment by TahaTesser** [comment]
it just looks extra wide than it needs to be 

<img width="253" alt="Screenshot 2020-05-21 at 8 32 22 PM" src="https://user-images.githubusercontent.com/48603081/82572583-338b5d00-9ba2-11ea-9304-671bec9b968a.png">
<img width="245" alt="Screenshot 2020-05-21 at 8 32 13 PM" src="https://user-images.githubusercontent.com/48603081/82572593-35edb700-9ba2-11ea-9cc8-078114b34a32.png">



This is also in checklist menu example https://gallery.flutter.dev/#/demo/menu

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: CheckboxInPopupMenu(),
    );
  }
}

class CheckboxInPopupMenu extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("Checkbox in PopupMenuButton Example"),
        ),
        body: Center(
          child: PopupMenuButton(
            child: Text("Checkbox PopupMenuBotton"),
            itemBuilder: (context) => [
              CheckedPopupMenuItem(
                checked: true,
                child: Text("InduceSmile.com"),
              ),
              CheckedPopupMenuItem(
                child: Text("Flutter.io"),
              ),
              CheckedPopupMenuItem(
                child: Text("Google.com"),
              ),
            ],
          ),
        ));
  }
}

``` 

</details>

**Comment by am1tr0r** [comment]
Hi,  @vlidholt @HansMuller @TahaTesser 

any update on this issue?

can we make the following constant property customise ?

// constants
const double _kMenuMaxWidth = 5.0 * _kMenuWidthStep;
const double _kMenuMinWidth = 2.0 * _kMenuWidthStep;
const double _kMenuWidthStep = 56.0;
const double _kMenuVerticalPadding = 8.0;

these constant values cause extra space in popupMenuItems.

**Comment by guidezpl** [comment]
Closing as obsolete
