### ISSUE TITLE
(OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by marico-sun** [flutter/flutter#35620]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by BondarenkoStas** [comment]
Unfortunately, this report does not have any actionable information - it’s not clear if this is a bug in user code, a bug in the framework, or something else entirely.
Please feel free to re-open if you can add the following information:
The version of Flutter you’re using
The output of flutter doctor -v
The full exception you see
A minimal reproduction that leads to this exception or steps description.
