### ISSUE TITLE
what the most popular forum of Flutter? or here is the a popular place to ask questions?

### ISSUE THREAD

**Issue by opengpu** [flutter/flutter#35621]
what the most popular forum of Flutter? or here is the a popular place to ask questions?

**Comment by rashedmyt** [comment]
@opengpu **Join the conversation** section in https://flutter.dev/community has some amazing places where you can ask questions.. the most popular place for asking questions regarding help would be stackoverflow.. and the most popular place for asking features and reporting bugs would be github issues

**Comment by pkrawat1** [comment]
There is https://flutterforum.co also

**Comment by jonahwilliams** [comment]
Closing as the question has been answered, the above link contains several highly popular communities. Have fun fluttering! :)
