### ISSUE TITLE
Time picker goes blank if tapped multiple times

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3562]
Time picker goes blank if it is tapped multiple times. Test in Gallery / Time picker.

![img_0009](https://cloud.githubusercontent.com/assets/1539812/14828663/d66c8a0c-0b9c-11e6-89f9-1a8b5aad84b0.PNG)

**Comment by sethladd** [comment]
Dupe of https://github.com/flutter/flutter/issues/3487
