### ISSUE TITLE
video_player can't work well on IOS

### ISSUE THREAD

**Issue by hahafather007** [flutter/flutter#35631]
I used Flutter dev v1.4.5-pre.11 and used video_player's 0.10.1+3 version to play m3u8 on both Android and IOS, which is perfect. But now I switch to master v1.7.12-pre.43, it can only play normally on Android, only the first frame can be loaded on IOS. How can I solve this problem? Switching to the Flutter version is not possible, because Android has modified a lot of code to adapt AndroidX.

**Comment by martinsedoo1** [comment]
I have the same problem with **iPad pro**.

**Comment by BondarenkoStas** [comment]
@hahafather007 How's it while using current flutter stablev1.9.1+hotfix.2 and video_player 0.10.2+1?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
