### ISSUE TITLE
The Apparent Lost frames in iPhoneX (may be other iOS devices will also happen this)

### ISSUE THREAD

**Issue by luckysmg** [flutter/flutter#35638]
I found that the flutter apps will occur frame drop,very apparently on my iPhoneX device. Because I have tested it on my Android phone and it ran with smooth animation just like native apps.But !! when I use my iOS device and run even under the release mode,especially in about 0.5~1.5s when the app starts or the app switches from background to foreground, the frame drop is very apparent.At first I thought the  problem is from my code,but after I  tested some apps that has been posted to the Apple’s App store,I found the problem is also exist.So i thought the problem is in flutter framework probably. So I Hope Google can solve this problem

**Comment by luckysmg** [comment]
``[!] Flutter (Channel beta, v1.7.8+hotfix.2, on Mac OS X 10.15 19A471t, locale
zh-Hans-CN)
• Flutter version 1.7.8+hotfix.2 at /Users/luckysmg/flutter
• Framework revision 2e54093 (32 hours ago), 2019-07-02 09:31:07 -0700
• Engine revision b1cb0d9e9b
• Dart version 2.4.0
✗ Downloaded executables cannot execute on host.
See #6207 for more information

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
• Android SDK at /Users/luckysmg/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling
support)
• Platform android-28, build-tools 28.0.3
• Java binary at: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build
1.8.0_152-release-1343-b01)
! Some Android licenses not accepted. To resolve this, run: flutter doctor
--android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 11.0)
• Xcode at /Applications/Xcode-beta.app/Contents/Developer
• Xcode 11.0, Build version 11M336w
! CocoaPods out of date (1.6.0 is recommended).
CocoaPods is used to retrieve the iOS and macOS platform side's plugin
code that responds to your plugin usage on the Dart side.
Without CocoaPods, plugins will not work on iOS or macOS.
For more info, see https://flutter.dev/platform-plugins
To upgrade:
brew upgrade cocoapods
pod setup

[✓] iOS tools - develop for iOS devices
• ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 35.3.1
• Dart plugin version 183.6270
• Java version OpenJDK Runtime Environment (build
1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
• IntelliJ at /Applications/IntelliJ IDEA.app
• Flutter plugin version 36.2.1
• Dart plugin version 191.7830

[✓] Connected device (2 available)
• 躺在文景睿手里的iPhoneX • 273b3891b80ba29ad5b7cfae8bf76006c2a5fbec • ios • iOS
13.0
• iPhone Xʀ • B1868194-2FAC-40FA-B0E1-FB0F8FDD298D • ios •
com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

! Doctor found issues in 3 categories.``

**Comment by tvolkert** [comment]
@luckysmg can you reproduce this in a driver test that you could share with us so we can track it down?

FYI @liyuqian @flar

**Comment by luckysmg** [comment]
Here is the url that I tested
 [https://youtu.be/CV1YPJrXAjM](url)

**Comment by luckysmg** [comment]
here is my test video

https://youtu.be/CV1YPJrXAjM

**Comment by luckysmg** [comment]
In profile mode

**Comment by tvolkert** [comment]
@luckysmg were you able to put together a simple driver test that demonstrates this?

https://flutter.dev/docs/cookbook/testing/integration/introduction
https://medium.com/flutter-community/testing-flutter-ui-with-flutter-driver-c1583681e337

**Comment by eseidelGoogle** [comment]
This could be related to https://github.com/flutter/flutter/issues/31086?

**Comment by iapicca** [comment]
Hi @luckysmg 
are you still experiencing this issue with the latest stable version of flutter?
If so could you please provide your updated `flutter doctor -v` 
and driver_test as [proposed](https://github.com/flutter/flutter/issues/35638#issuecomment-509461405)
Thank you

**Comment by luckysmg** [comment]
@iapicca  I have tested and flutter 1.12 works great . This issue has gone

**Comment by VladyslavBondarenko** [comment]
@luckysmg 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
