### ISSUE TITLE
move chromium bot scripts into the flutter repo

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#3564]
It would be nice if the chromium bot scripts (documented here: https://github.com/flutter/flutter/blob/master/infra/README.md) lived in the `flutter` repo. There would then be some small bootstrap scripts that the chromium bots would run, to get things set up and call into the ones in flutter. It would be easier to iterate on the scripts if they were in this repo.

**Comment by Hixie** [comment]
Where are they today?

Anyway we should feel free to do this, but I don't think we need a bug to track doing it.
