### ISSUE TITLE
Must reduce Firestore cacheSizeByte minimum limit

### ISSUE THREAD

**Issue by yamauchieduardo** [flutter/flutter#35648]
The minimum Firestore `cacheSizeByte` is 1Mb, acording to [documentation](https://firebase.google.com/docs/reference/js/firebase.firestore.Settings.html#cachesizebytes ) .

This minimum limit *must* be smaller (50kb) so that we can workaround this serious performance problem [issues](https://github.com/firebase/firebase-ios-sdk/issues/1868 ) when querying large collections using persistence (cache enabled).

In my project, the average document size is around 500 bytes. If the cache is 1Mb, it will allow 2000 cached documents, and queries may take around 2 seconds or more.

**Comment by kroikie** [comment]
@yamauchieduardo

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1218. Any further collaboration will be done there.
