### ISSUE TITLE
'all' devices should only include project-supported devices

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#35652]
STR:
- Run `flutter run -d all` in a standard (mobile-only) project on master.

It will attempt to run on the desktop host device and fail, because there's not desktop support in the project. I can't think of a scenario where interpreting `all` as meaning all available devices rather than all supported devices would be desirable, so I think we can just always filter by project support.

See #35605 for an example of a case where this caused issues.

CC @jonahwilliams

**Comment by jonahwilliams** [comment]
We should also be removing fuchsia and web devices from the `--all` list as well, since the compilers are configured differently in this case
