### ISSUE TITLE
ARGB components order and kSoftware

### ISSUE THREAD

**Issue by scheglov** [flutter/flutter#35655]
I'm using embedding version `3c51a7bfff776e9e3011384f4ff09c13a697c6b6` into Java Swing, and I have a problem with the order of pixel components.

I have to do the following transformation of pixels that I get from the engine on Mac.

```java
        for (int i = 0; i < pixels.length; i++) {
            int pixel = pixels[i];
            int pa = (pixel & 0xFF000000) >> 24;
            int pb = (pixel & 0x00FF0000) >> 16;
            int pg = (pixel & 0x0000FF00) >> 8;
            int pr = (pixel & 0x000000FF);
            pixel = (pa << 24) | (pr << 16) | (pg << 8) | pb;
            pixels[i] = pixel;
        }
```
  So, that I get correct colors.
![image](https://user-images.githubusercontent.com/384794/60749342-6c502280-9f4d-11e9-8228-1e7475a96552.png)
vs. this without transformation.
![image](https://user-images.githubusercontent.com/384794/60749349-7a9e3e80-9f4d-11e9-9bfb-c49b17db285e.png)

  But on Windows 7 x64 I don't have to do this transformation, but I use MS VS compiler instead of clang. Although I don't do anything special to specify endianness. This is the same CPU, Windows 7 is run in VMWare Fusion on this Mac.

On Windows:

```BAT
"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

c:\Work\cpp\flutter\flutter-java-embedder\native>cl -I "C:\Program Files (x86)\Java\jdk8\include" -I "C:\Program Files (x86)\Java\jdk8\include\win32" -I "C:\Work\cpp\flutter\flutter-java-embedder" /std:c++latest /EHsc /MD /LD "C:\Work\cpp\flutter\flutter-java-embedder\FlutterEmbedder\flutter_engine.dll.lib" FlutterEmbedding.cc
```

On Mac:

```make
build_native:
	cd native && \
	c++ -std=c++17 \
		-F. \
		-framework FlutterEmbedder \
		-Wl,-rpath . \
		-I. -I"${JAVA_HOME}/include" \
		-I"${JAVA_HOME}/include/darwin/" \
		-o libflutterembedding.jnilib \
		-shared \
		FlutterEmbedding.cc
```

  The code for the `kSoftware` callback.
  Note that commented code that forces pixels, when I uncomment it, I get expected solid green pixels rendered on Java side.

```c++
      config.software.surface_present_callback = [](
        void* userdata,
        const void* allocation,
        size_t rowBytes,
        size_t height
      ) -> bool {
        auto instance = reinterpret_cast<FlutterEmbedding*>(userdata);

        JNIEnv* env;
        instance->jvm->AttachCurrentThread((void**) &(env), nullptr);

        jclass cls = env->GetObjectClass(instance->object);
        jmethodID method = env->GetMethodID(cls, "softwareSurfaceReady", "([III)V");

        auto nativePixels = static_cast<const int32_t*>(allocation);
        auto width = rowBytes / 4;

        auto pixelsLength = width * height;
        auto javaPixels = env->NewIntArray(pixelsLength);
        env->SetIntArrayRegion(javaPixels, 0, pixelsLength, nativePixels);

//        jint *body = env->GetIntArrayElements(javaPixels, 0);
//        for (int i = 0; i < 100000; i++) {
//          body[i] = 0xFF00FF00;
//        }
//        env->ReleaseIntArrayElements(javaPixels, body, 0);

        env->CallVoidMethod(instance->object, method, javaPixels, width, height);

        instance->jvm->DetachCurrentThread();

        return true;
      };
```

**Comment by jason-simmons** [comment]
Screenshot bitmaps are encoded using Skia's `kN32_SkColorType` format.  See https://skia.org/user/api/SkImageInfo_Reference#SkColorType

```
kN32_SkColorType selects the native 32-bit ARGB format. On Little_Endian processors, pixels containing 8-bit ARGB components pack into 32-bit kBGRA_8888_SkColorType. On Big_Endian processors, pixels pack into 32-bit kRGBA_8888_SkColorType.
```

Skia's headers select BGRA versus RGBA format here:
    https://github.com/google/skia/blob/master/include/core/SkImageInfo.h#L90

Take a look at how Skia's endianness macros are set in your build environments to check whether Skia is using a consistent encoding on each target platform.

**Comment by darshankawar** [comment]
@scheglov 
Are you still facing this issue using latest Flutter version ? Does https://github.com/flutter/flutter/issues/35655#issuecomment-509790779 answer / help to resolve your issue ?

**Comment by scheglov** [comment]
I have not worked on this project since then, so I cannot say.
Consider this issue as not important to me anymore.

**Comment by darshankawar** [comment]
Closing this based on above comment.
