### ISSUE TITLE
Keyboard configuration in Scaffold

### ISSUE THREAD

**Issue by cooler-king** [flutter/flutter#3565]
The default behavior of opening a keyboard in flutter appears to be to scrunch the app into the remaining space (if the screen has scrollable elements).  Often the preferred behavior is to simply overlay the app and not resize anything.

AndroidManifest has a way to control this behavior with the `windowSoftInputMode` setting:
http://developer.android.com/guide/topics/manifest/activity-element.html#wsoft

Consider
1 - exposing these choices in Scaffold
2 - Making the default behavior one that opts for simple overlay and no layout adjustments

Related discussion here:
https://groups.google.com/forum/#!topic/flutter-dev/87-4tLeHvBM

**Comment by abarth** [comment]
For your use cases, how would you like widgets like the floating action button and snackbars to be treated?  Do you want the keyboard to cover the float action button and snackbars (the little notifications on the bottom of the screen) or would you like them to be positioned above the keyboard?

**Comment by cooler-king** [comment]
I think it should cover everything.

**Comment by abarth** [comment]
Makes sense.
