### ISSUE TITLE
unable to pub 

### ISSUE THREAD

**Issue by aromal17** [flutter/flutter#35650]
i am not able to run the flutter doctor command.....i rechecked my installation and the path file in environment variables also,but still its not working
![Screenshot (39)](https://user-images.githubusercontent.com/33396857/60741446-0b454080-9f87-11e9-9663-3108ba413a72.png)

**Comment by BondarenkoStas** [comment]
@aromal17 This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
