### ISSUE TITLE
[google_maps_flutter] Disable street labels

### ISSUE THREAD

**Issue by pedro371** [flutter/flutter#35669]
Hello guys,

its possible to hide the street names?

Thanks!

**Comment by Aljoxa88** [comment]
Hey, you can generate on https://mapstyle.withgoogle.com/ map style (without street labels for example)  as string in json format and pass it to GoogleMap controller 
`  void _onMapCreated(GoogleMapController controller) {
    controller.setMapStyle(/* your json style string */);
  }`

**Comment by janmoppel** [comment]
Hello @pedro371 !

Did you manage to solve the issue? Does the solution by @Aljoxa88 worked for you?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
