### ISSUE TITLE
Page selector is not conforming to Material design

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3566]
Cannot find a reference in the spec, but pretty sure I've seen it. The circles are supposed to have no outline, but instead being transparent. Also, they should be smaller. May need to ask the Material design team for exact dimensions.

![img_0011](https://cloud.githubusercontent.com/assets/1539812/14829908/c50a2f02-0ba2-11e6-9da9-784c725df6a5.PNG)

**Comment by sethladd** [comment]
I don't think this is spec'ed. This is similar to a new user flow, but the version in the gallery is very different than what a user would first see in Inbox app, e.g.

If we can't find the spec for this, we can consider morphing this demo into a typical "new user orientation flow". A lot will have to change: removing the arrows in the top left and right. Adding a "next" button. Going full screen with an image that talks about a feature.

**Comment by sethladd** [comment]
Closing because we can't find a spec for this.
