### ISSUE TITLE
Error: Could not resolve URL "https://pub.dartlang.org".

### ISSUE THREAD

**Issue by snehitvaddi** [flutter/flutter#35664]
I am getting an error like : Could not resolve URL "https://pub.dartlang.org" while using `flutter create`, to create a new flutter project.

**Comment by janmoppel** [comment]
Hello @snehitvaddi !

As solution has been proposed already by @LuciferAJ, closing this issue. However, if solution doesn't work for you, feel free to open a new issue.

Thank you.
