### ISSUE TITLE
Flutter App becomes irresponsive and connection getting lost after some times (no error messages in console)

### ISSUE THREAD

**Issue by Vipin-Pootheri** [flutter/flutter#35677]
This issue is happening only when updating the line of code    `for (int i = 0; i < scat.length; i++)`
to    `for (int i = 0; i < scat.length; i+3)` in the below snippet.

`subcat = List<Subcategory>` and has properties `categoryname` and `subcategoryname` .

```dart
Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        for (int i = 0; i < scat.length; i++)
          Column(
            children: <Widget>[
              Text(scat[i].categoryname),
              Row(
                children: <Widget>[
                  for (j = 0; j < 1; j++) Text(scat[j].subcategoryname)
                  
                ],
              )
            ],
          )
      ],
    );
  }
```
Any pointers

**Comment by janmoppel** [comment]
Hello @Vipin-Pootheri !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
