### ISSUE TITLE
Image picker not showing image taken from camera. Shows a blank image

### ISSUE THREAD

**Issue by kushas** [flutter/flutter#35673]
![Screenshot_2019-07-06-17-23-47](https://user-images.githubusercontent.com/28893098/60757471-da1e4c00-a02a-11e9-9592-3ce2d2a01858.png)
It is just white image.

**Comment by janmoppel** [comment]
Hello @kushas !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
