### ISSUE TITLE
Cache<K, V> drop-in replacement for Map

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3568]
It would be useful to have a `Cache<K, V>` class that works like Map in most respects but implements memory-pressure eviction semantics. This presumably needs help from the VM.

cc @esprehn

**Comment by spierce7** [comment]
Android has an [LruCache](https://developer.android.com/reference/android/util/LruCache.html) that has an api that's proven flexible. On the link above, the documentation shows how to turn it into a bitmap cache that only allows a certain amount of memory to be used by overriding the `sizeOf` method. The `create` and `entryRemoved` methods have also proven very helpful for releasing resources when they are being removed from the cache.

I imagine these features might also be helpful in Flutter.

**Comment by jonahwilliams** [comment]
We're not going to add this
