### ISSUE TITLE
Failed to send crash report due to a network error: SocketException: OS Error: Operation timed out, errno = 60, address = clients2.google.com, port = 57272

### ISSUE THREAD

**Issue by chenxuedan** [flutter/flutter#35689]
[flutter_02.log](https://github.com/flutter/flutter/files/3365291/flutter_02.log)

**Comment by kingkadienm** [comment]
[flutter_07.log](https://github.com/flutter/flutter/files/3370856/flutter_07.log)

**Comment by janmoppel** [comment]
Hello @chenxuedan !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by janmoppel** [comment]
Hello @kingkadienm !

If your problem still persist, please open a new issue, as your logs indicates a different issue, than the one posted here.
Thank you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
