### ISSUE TITLE
A procedure runs well in debug mode but not after release, why?

### ISSUE THREAD

**Issue by rakib205** [flutter/flutter#35692]
So this is the procedure which runs well in debug mode but not after release.

**Procedure**

  Future<void> downloadFile() async{
    Dio dio = Dio();
    
    var directory = await getApplicationDocumentsDirectory();
    await dio.download(bookUrl, "${directory.path}/$className + $bookName.pdf",
    onReceiveProgress: (rec, total){
      setState(() {
        downloading = true;
        percentage = ((rec/total) * 100).toStringAsFixed(0)+'%';
      });
    }
    
    );

    setState(() {
      downloading = false;
      percentage = 'Download Completed';
    });
    
    
  }

**Error on terminal**

E/flutter (25796): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: SocketException: Failed host lookup: 'www.ets.org' (OS Error: No address associated with hostname, errno = 7)
E/flutter (25796): #0      Dio._makeRequest (package:dio/src/dio.dart:799)
E/flutter (25796): <asynchronous suspension>
E/flutter (25796): #1      Dio._request.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:711)
E/flutter (25796): #2      _rootRunUnary (dart:async/zone.dart:1132)
E/flutter (25796): #3      _CustomZone.runUnary (dart:async/zone.dart:1029)
E/flutter (25796): #4      _FutureListener.handleValue (dart:async/future_impl.dart:126)
E/flutter (25796): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639)
E/flutter (25796): #6      Future._propagateToListeners (dart:async/future_impl.dart:668)
E/flutter (25796): #7      Future._complete (dart:async/future_impl.dart:473)
E/flutter (25796): #8      _SyncCompleter.complete (dart:async/future_impl.dart:51)
E/flutter (25796): #9      _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33)
E/flutter (25796): #10     _rootRun (dart:async/zone.dart:1120)
E/flutter (25796): #11     _CustomZone.run (dart:async/zone.dart:1021)
E/flutter (25796): #12     _CustomZone.runGuarded (dart:async/zone.dart:923)
E/flutter (25796): #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
E/flutter (25796): #14     _rootRun (dart:async/zone.dart:1124)
E/flutter (25796): #15     _CustomZone.run (dart:async/zone.dart:1021)
E/flutter (25796): #16     _CustomZone.runGuarded (dart:async/zone.dart:923)
E/flutter (25796): #17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
E/flutter (25796): #18     _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter (25796): #19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
E/flutter (25796):

**Comment by jason-simmons** [comment]
If this is on Android, then check that your app has the `INTERNET` permission enabled in the manifest in release mode.

The Flutter default app template enables `INTERNET` in debug mode to support development tools like the Dart observatory.  But `INTERNET` is not on by default in release mode

**Comment by rakib205** [comment]
Thanks, i got it.

**Comment by daigewuwy** [comment]
> 如果是在Android上，则请检查您的应用是否`INTERNET`在发布模式下的清单中启用了权限。
> 
> Flutter默认应用模板`INTERNET`在调试模式下启用，以支持Dart天文台等开发工具。但是`INTERNET`在发布模式下默认情况下未启用

我在ios真机上出现这个错误，请问需要添加什么配置嘛

> If this is on Android, then check that your app has the `INTERNET` permission enabled in the manifest in release mode.
> 
> The Flutter default app template enables `INTERNET` in debug mode to support development tools like the Dart observatory. But `INTERNET` is not on by default in release mode

I got this on iOS，can you tell me how to fix it
