### ISSUE TITLE
Why can't Fluter's GridView merge cells like Html's Table?

### ISSUE THREAD

**Issue by biij5698** [flutter/flutter#35691]
Why can't Flutter's GridView merge cells like Html's table?forexample:colspan and rowspan

**Comment by shihaohong** [comment]
Thank you for your request. I believe there is a separate issue tracking this already: https://github.com/flutter/flutter/issues/21594

If you're interested in the issue, go into the original issue and put a "thumbs up" on the first comment. That's how the Flutter team determines priority for which issues to work on. For now, I'll close this issue.

**Comment by phanirithvij** [comment]
It'd be a nice feature.

**Comment by biij5698** [comment]
Very good, I am expecting this feature to be implemented as early as possible.

**Comment by ciscolxh** [comment]
How to make a table to merge cells

**Comment by goderbauer** [comment]
We are working on a table widget that should allow merging cells: https://github.com/flutter/flutter/issues/87370
