### ISSUE TITLE
xcode_backend_test.dart will fail if `flutter precache` hasn't run.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#35707]
This relies on the real cache containing iOS artifacts for the test case "Xcode backend fails for on unsupported configuration combinations".

**Comment by dnfield** [comment]
We should remove these entirely if we're going to disable them, but it probably makes sense to keep them around until we get rid of or at least greatly pare down xcode_backend.sh

**Comment by jmagman** [comment]
I believe this test is actually testing bad real behavior, I think it also fails if a customer opened `ios/Runner.xcworkspace` in Xcode without caching the ios artifacts.

**Comment by jonahwilliams** [comment]
Right, the problem is the xcode backend script is copying out of the cache - really the tool should be doing this so that we can validate and run precache if need be.

If we fix that, we could also fix the test
