### ISSUE TITLE
Flutter pub publish is stuck

### ISSUE THREAD

**Issue by aubykhan** [flutter/flutter#35703]
# Issue
The flutter pub publish command gets stuck after successfully printing the code hierarchy. No messages whatsoever and the command just fails to proceed without giving any error or printing any progress message.

# Workaround
While the recommended `flutter pub publish` command is not working, I managed to publish the packages using `flutter packages pub publish`

**Comment by icatalud** [comment]
I had the same issue, flutter pub pub publish solves the problem. The same is required for --dry-run. Apparently if you do not include a second pub, the command starts working with an alternative console, which would explain why it doesn't take the args also.

**Comment by qazyn951230** [comment]
`flutter pub pub publish` works for me.

**Comment by peyter213** [comment]
Same issue. 
Documentation lists the command `flutter pub publish` but that command will never print `Looks great! Are you ready to upload your package (y/n)?`. Using `flutter pub pub publish` solved it for me as well.
Link to the doc page: ://flutter.dev/docs/development/packages-and-plugins/developing-packages

**Comment by MSchmack** [comment]
Documentation updated, issue can be closed.
