### ISSUE TITLE
Flutter pod install generates invalid path for .xcconfig files

### ISSUE THREAD

**Issue by BarFingerman** [flutter/flutter#35700]
i have issues with integrating flutter in my existing iOS(swift) application,

according to the docs in order to user flutter i added this in my pod file:

`flutter_application_path = 'my_flutter_module/'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)`

i then run pod install and everything works fine, i manage to install my app and also to archive, but when my CI / CD server run the build it failed every time, when diving into the logs i identified that the flutter scripts generated code on all the .xcconfig files that looks like this

`#include "/Users/my_name/my_project_name/my_flutter_module/.ios/Flutter/Generated.xcconfig"`

this path is relative to my machine, but i expect that the path's will look like

`#include "${PODS_xxx}/my_flutter_module/.ios/Flutter/Generated.xcconfig"`

after some more digging i manage to find the script that generate this at:

`/Users/my_name/flutter/packages/flutter_tools/templates/module/ios/library/Flutter.tmpl/podhelper.rb `

CODE
`post_install do |installer|
installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        next if  config.base_configuration_reference == nil
        xcconfig_path = config.base_configuration_reference.real_path
        File.open(xcconfig_path, 'a+') do |file|
            file.puts "#include \"#{File.realpath(File.join(framework_dir, 'Generated.xcconfig'))}\""
        end
    end
  end 
end`

i tried to modify it but there was no affect after pod install, any help will be appreciate.

note that i use the .gitignore from [here](https://github.com/flutter/flutter/blob/master/.gitignore)
and all my development / other pods gets the wrong local path like this(my firebase pod):
<img width="1249" alt="Screen Shot 2019-07-07 at 16 26 03" src="https://user-images.githubusercontent.com/11498591/60769061-296c8700-a0d4-11e9-936d-3f8ee21bad54.png">

**Comment by mekhi** [comment]
I also encountered the same problem. Is there any solution?

**Comment by mekhi** [comment]
I temporarily add `Pods/Target Support Files/*.xcconfig` to `.gitignore` to solve this problem.

**Comment by BarFingerman** [comment]
what work for me in the end is to exclude all the pods from my git and run "pod install" before every build on the server.

**Comment by jmagman** [comment]
This should be resolved now as of https://github.com/flutter/flutter/pull/36793.  On the master branch, try updating your project.  See the instructions at https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#add-your-flutter-app-to-your-podfile and https://github.com/flutter/flutter/wiki/Upgrading-Flutter-added-to-existing-iOS-Xcode-project.

If you are still seeing problems, please re-open this or file a new issue!
