### ISSUE TITLE
[web]:Flutter For Web  Page Title Problem

### ISSUE THREAD

**Issue by wedcel** [flutter/flutter#35719]
Flutter For Web's page title is taken from the title of the material app, but when the page jumps, you should re-take the new page title, this time you can change the page title. But in fact, I found this to change. When I entered this page, the title of this page was the previous page, but when I selected the selection button, the page became the current page, I think This is a bug that should be fixed.

The first page,
![image](https://user-images.githubusercontent.com/3982317/60781478-486f2580-a175-11e9-911b-307d31610b07.png)

the second page,
![image](https://user-images.githubusercontent.com/3982317/60781513-69d01180-a175-11e9-9ad4-67644279f499.png)

when I selected the selection button of the second page, the title is changed,

![image](https://user-images.githubusercontent.com/3982317/60781568-8ff5b180-a175-11e9-866f-650c98fd5144.png)

**Comment by ferhatb** [comment]
Are you using RouteObserver and calling setState on your app so it rebuilds ? Can you please share code snippet to repro. Thx!

**Comment by ymback** [comment]
I found a way using redux or scoped_model, just set app title after initState, scoped_model may need using future.delayd with 1ms

**Comment by markusaksli-nc** [comment]
Hi @wedcel 
Can you confirm if this issue still persists on the latest version of flutter (eg. dev or master) and provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) if this is the case?
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
