### ISSUE TITLE
Flutter text overflow with ellipsis unnecessary expands parent

### ISSUE THREAD

**Issue by manteliukasx** [flutter/flutter#35710]
When a very long word is wrapped into next line, text widget size is also expanded to that word's size.
![image](https://user-images.githubusercontent.com/1338479/60774705-7d00c400-a118-11e9-96ff-0ec225cb0159.png)
The first comment is not long, so it does not expand. However, second comment expands its parent with approximately the size of wrapped word.
I have tried wrapping the comment with different containers which did not help.

```
class Comment extends StatelessWidget {
  Comment(this.comment);
  final String comment;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(top: 5, left: 8, right: 8),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.end,
        children: <Widget>[
          Flexible(
            child: Container(
              decoration: BoxDecoration(
                color: Colors.black45,
                borderRadius: BorderRadius.circular(8)
              ),
              child: Padding(
                padding: const EdgeInsets.all(5.0),
                child: Text(
                  comment,
                  style: TextStyle(color: Colors.white),
                  overflow: TextOverflow.ellipsis,
                  maxLines: 2,
                  softWrap: false,
                  textAlign: TextAlign.end,
                ),
              )
            ),
          ),
          SizedBox(width: 6),
          CircleAvatar(
            radius: 15,
            backgroundImage: NetworkImage(TestImg()),
          ),
        ],
      ),
    );
  }
}
```

**Comment by shihaohong** [comment]
Are you talking about horizontal expansion of the parent? Aka the space in between the left side of your screenshot and where the text appears?

**Comment by manteliukasx** [comment]
Yes. There is no other expansion than horizontal as shown in screenshot

**Comment by justinmc** [comment]
Have you tried using `textWidthBasis: TextWidthBasis.longestLine`?  It was added not that long ago so it might not be in the official docs yet.  See https://github.com/flutter/flutter/pull/30988#issuecomment-487680031.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
