### ISSUE TITLE
adb error cant find variable activity

### ISSUE THREAD

**Issue by A7madXatab** [flutter/flutter#35711]
im currenty having an issue on android, which states that adb cant find activity, 

![66417053_344469183144758_4542350536006959104_n](https://user-images.githubusercontent.com/38360603/60774953-f83e8780-a0d0-11e9-81f7-85e1c2315c41.png)

thank for your reply

**Comment by lewcianci** [comment]
I don't think this is a Flutter issue. I would try resetting your emulator or try using a physical device.

**Comment by saravananmnm** [comment]
if, your device is arm-v7 it need to x86 apk. otherwise normal

by adding abifilters issue will be solved. plz try this.

defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        ndk {
            abiFilters "armeabi-v7a", "x86_64", "armeabi", "mips"
           // abiFilters "arm64-v8a", "armeabi-v7a","armeabi", "mips", "x86"
        }
        applicationId "com.example.tvs_visibility"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

**Comment by BondarenkoStas** [comment]
@A7madXatab did you solved the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
