### ISSUE TITLE
Redirecting factory constructor - factory Listenable.merge(...) = _MergingListenable

### ISSUE THREAD

**Issue by PandaGeek1024** [flutter/flutter#35727]
Im just learning the Provider library and found it is using Listenable. One interesting thing in this class is that it has this line of code 

`factory Listenable.merge(List<Listenable> listenables) = _MergingListenable;`

The _MergingListenable is actually a class.

As of my knowledge, the function should use => to return expression but using equal symbol is complete new to me and I could not find any where mention about it. 

Can someone explain to me what is this and how it works? Or maybe point me to the right doc would also be appreciated. Thanks a lot.

**Comment by shihaohong** [comment]
Some context for the syntax in question (not an answer, but probably helpful for future readers of this issue): https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/change_notifier.dart#L65

**Comment by mraleph** [comment]
This is called a _redirecting factory constructor_ and it is described in the Dart Language Specification section `10.6.2 Factories`

Simply speaking `factory X.name(...) = Y` is more or less equivalent to `factory X.name(...) => Y<...>(...)` - essentially it forwards all arguments and type arguments from `X.name` factory into constructor of `Y`.

**Comment by shihaohong** [comment]
I will close this issue since an answer has been provided. I also created a new issue in the Dart Github to perhaps better expose this syntax (https://github.com/dart-lang/sdk/issues/37466)

In the future, if you have Dart-specific issues, please feel free to create one at https://github.com/dart-lang/sdk.

**Comment by ThinkDigitalSoftware** [comment]
Seems like a tear-off is more appropriate syntax than the `=` sign.
