### ISSUE TITLE
Run flutter application on weston failed

### ISSUE THREAD

**Issue by ping996** [flutter/flutter#35735]
Hi All
I have a problem with run flutter on weston desktop shell, follow the steps of https://github.com/chinmaygarde/flutter_wayland.

Run flutter doctor succussfully with no errors.
But failed when do:
flutter_wayland <asset_bundle_path> <flutter_flags>

./flutter_wayland ~/AndroidStudioProjects/flutter_app1/build/flutter_assets/ 
ERROR: ../src/main.cc:63: Arg: /home/oppo/AndroidStudioProjects/flutter_app1/build/flutter_assets/
flutter: Observatory listening on http://127.0.0.1:38682/
[ERROR:flutter/shell/common/engine.cc(112)] Engine run configuration was invalid.
[ERROR:flutter/shell/platform/embedder/embedder_engine.cc(65)] Could not launch the engine with configuration.

Any suggestion from you?

**Comment by stuartmorgan** [comment]
That project is hard-coding a specific Flutter engine version:
https://github.com/chinmaygarde/flutter_wayland/blob/master/CMakeLists.txt#L9
which means you must use a version of Flutter that uses that engine version to generate the assets. That doesn't appear to be documented, which is an issue with that project, not Flutter. This should be filed in that project's issue tracker, which it looks like you've already done.

**Comment by ping996** [comment]
@stuartmorgan Thanks for you help and sorry for my mistake of create a duplicated issues here.

**Comment by ping996** [comment]
@stuartmorgan how can I use the flutter of given engine version,  I don't known how to make the flutter tool. any suggestions?
