### ISSUE TITLE
How can I get ImageStream? Or How to add stream or uint8list to imageCache?

### ISSUE THREAD

**Issue by Rotanticu** [flutter/flutter#35739]
Hey! I have a requirement: 

I have a low definition picture and a high definition picture url. I want to use low-definition pictures as the base, and gradually load high-definition pictures to cover low-definition pictures.If this requirement can be fulfilled, users will not have to be irritated with the loading image.

I've done that. It looks great, but the code is ugly.

```
        body: ChangeNotifierProvider<DetailNotifier>(
            child: Consumer<DetailNotifier>(
              builder: (context, detailNotifier, child) {
                return Ink.image(
                    image: NetworkImage(widget.post.previewUrl),
                    fit: BoxFit.cover,
                    child: Ink(
                      child: FadeInImage(
                        placeholder: MemoryImage(Uint8List.fromList(this._detailNotifier.uint8List)),
                        image: AssetImage(""),
                        //todo With this I can cache images, but it means that each image is loaded twice.
                        //image: NetworkImage(widget.post.sampleUrl), 
                        width: widget.post.sampleWidth.toDouble(),
                        height:widget.post.sampleHeight.toDouble(),
                        fit: BoxFit.cover,
                      ),
                    ));
              },
            ),
            builder: (context) => this._detailNotifier));
```

I had to initiates requests manually.But I can't put the uint8List in imageCache.It only Get and no Add.So every time I open the same page, I download the picture again.(Here's another problem. Every time I open the same page, it's through new State (), so every time I got run initState (). Is this really an official recommendation?)

On the other hand，If I can get _imageStream or ImageInfo, I don't have to start my own image request to get the data stream.But I can't because he's a private property.

My problem is: 
Do you have any plans to add caching APIs manually?
Or plans to expose uint8list in imageInfo or expose imageSteam?

**Comment by Hixie** [comment]
Use a `MemoryImage` or the `Image.memory` widget.

**Comment by Hixie** [comment]
Wait, that's what you're doing already. I don't understand the request. Can you elaborate?
