### ISSUE TITLE
flutter run failed with wayland on linux 

### ISSUE THREAD

**Issue by ping996** [flutter/flutter#35737]
Follow the steps of https://github.com/chinmaygarde/flutter_wayland

./flutter_wayland /home/oppo/AndroidStudioProjects/flutter_app1/build/flutter_assets/ 
ERROR: ../src/main.cc:63: Arg: /home/oppo/AndroidStudioProjects/flutter_app1/build/flutter_assets/
flutter: Observatory listening on http://127.0.0.1:38682/
[ERROR:flutter/shell/common/engine.cc(112)] Engine run configuration was invalid.
[ERROR:flutter/shell/platform/embedder/embedder_engine.cc(65)] Could not launch the engine with configuration.

Any suggestions from here?

**Comment by stuartmorgan** [comment]
Please don't file duplicate bugs; I've already explained in #35735 why this isn't a Flutter issue. https://github.com/chinmaygarde/flutter_wayland/issues/4 is the right place for your issue.
