### ISSUE TITLE
Support for translucent + transparent Android's SystemNavigationBar

### ISSUE THREAD

**Issue by jamesblasco** [flutter/flutter#35748]
It would be nice to be able to make the system navigation bar transparent. Right now when i try 
```dart
SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light.copyWith(

    statusBarColor: Colors.transparent,
    systemNavigationBarColor: Colors.transparent,

  ));
```
The status bar becomes transparent but not the systemNavigationBar

![image](https://user-images.githubusercontent.com/19904063/60828202-22b44180-a1b2-11e9-8da8-e30b317dd2bd.png)
![image](https://user-images.githubusercontent.com/19904063/60828217-2d6ed680-a1b2-11e9-8479-b4d76cfd569c.png)

### GOAL 
![image](https://user-images.githubusercontent.com/19904063/60828231-35c71180-a1b2-11e9-8255-2a3c1d4645f3.png)

### WHAT I TRIED AND FAILED
I have tried doing it with Kotlin and Android following [this answer in stackoverflow](https://stackoverflow.com/a/31596735/8096916) but the  SafeArea widgets stops working and a navigation bar looks like this 

<img width="311" alt="Captura de pantalla 2019-07-08 a las 19 06 46" src="https://user-images.githubusercontent.com/19904063/60828774-9571ec80-a1b3-11e9-9aed-400b14149250.png">

**Comment by Zazo032** [comment]
Probably related to https://github.com/flutter/flutter/issues/34678

**Comment by lazylazyllama** [comment]
I really need this feature

**Comment by giga10** [comment]
Waiting for this one too...

**Comment by Reprevise** [comment]
Any update on this?

**Comment by vvVenom** [comment]
I try to make status/navigation bar transparent by following methods:

> step 1    **src/main/res/values/styles.xml**

```xml
<item name="android:statusBarColor">@android:color/transparent</item>
<item name="android:navigationBarColor">@android:color/transparent</item>
<item name="android:windowTranslucentStatus">true</item>
<item name="android:windowTranslucentNavigation">true</item>
```

> step 2    ***Activity**

```kotlin
super.onCreate(savedInstanceState)
window.decorView.apply {
    javaClass.declaredFields
        .firstOrNull { it.name == "mSemiTransparentBarColor" }
        ?.apply { isAccessible = true }
        ?.setInt(this, Color.TRANSPARENT)
}
```

At the end, i got this:
![image](https://user-images.githubusercontent.com/58068445/84908647-4df42000-b0e7-11ea-87fb-34cd74c8b679.png)
😺 

But anyway, I still hope there is a better way to solve it, rather than through reflection [DecorView](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/com/android/internal/policy/DecorView.java#L213)

**Comment by dariadobsai** [comment]
Hello, any update on this issue?
