### ISSUE TITLE
Cirrus restarting agents is interpreted as failure by our bots

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#35752]
Sometimes [plugins tests](https://cirrus-ci.com/github/flutter/plugins/master) are showing up green in Cirrus but our internal notifications (Ropey) think they failed. Possibly Cirrus flakes and restarts the agents itself, which our bot interprets as a failure. 

Other Cirrus tests may be affected as well -- I'm not sure.

<img width="514" alt="Screen Shot 2019-07-08 at 10 17 09" src="https://user-images.githubusercontent.com/394889/60832371-959cc880-a170-11e9-9f22-474be72b8901.png">
<img width="1129" alt="Screen Shot 2019-07-08 at 10 17 03" src="https://user-images.githubusercontent.com/394889/60832372-959cc880-a170-11e9-976d-53d1eeec6d66.png">
<img width="1154" alt="Screen Shot 2019-07-08 at 10 16 46" src="https://user-images.githubusercontent.com/394889/60832373-959cc880-a170-11e9-8fca-bb8d614270c0.png">

**Comment by collinjackson** [comment]
The theory about Cirrus flaking and restarting the agents was suggested by @jonahwilliams

**Comment by fkorotkov** [comment]
Does the bot check GitHub's [Commit Statuses](https://developer.github.com/v3/repos/statuses/) for a SHA or [Check Suites](https://developer.github.com/v3/checks/suites/#list-check-suites-for-a-specific-ref)? Commit status might flake to red on a restart but check's `conclusion` shouldn't.

**Comment by goderbauer** [comment]
Ropy McFlutter has retired.
