### ISSUE TITLE
Obfuscating a Flutter app can cause plugins to fail

### ISSUE THREAD

**Issue by bparrishMines** [flutter/flutter#35764]
When calling `invokeMethod`, some plugins use a method name along the lines of `$ClassName#MethodName`. When trying to obfuscate the dart code in a flutter app, this may inadvertently change the class names on the dart side, but not the native side. 

For example `invokeMethod('$Adder#add')` would be replaced with `invokeMethod('$zza#add')`.

I'm not sure of all plugins that would be affected by this, but `firebase_ml_vision` and `firebase_performance` use this format.

This could be solved by just removing the `$` in front of the method name.

Related comment: https://github.com/flutter/plugins/commit/90ed52d7431f511d89cac0939f3f368c77e08a19#commitcomment-34121822

**Comment by axel-op** [comment]
I am experiencing this issue with Dart code obfuscation. 

Do you have a workaround or a way to resolve this as soon as possible, while keeping obfuscation on?

**Comment by bparrishMines** [comment]
@axel-op In the short term, you could fork the plugin and then change all the `invokeMethod` calls to not use the `$`. If you have time, you could [create a PR](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md) from that and I could review it and merge it.

Unfortunately, I don't have time to work on it right now.

**Comment by axel-op** [comment]
> @axel-op In the short term, you could fork the plugin and then change all the invokeMethod calls to not use the $. If you have time, you could create a PR from that and I could review it and merge it.
> Unfortunately, I don't have time to work on it right now.

Done: flutter/plugins#1874.

**Comment by axel-op** [comment]
This is resolved in the last version 0.3.0+3 of the plugin. This issue can be closed.

**Comment by kroikie** [comment]
@bparrishMines

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/358. Any further collaboration will be done there.
