### ISSUE TITLE
Implement bottom navigation

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#3577]
https://www.google.com/design/spec/components/bottom-navigation.html

**Comment by sethladd** [comment]
This is also useful because iOS prefers a bottom tabbed navigation, over the left-hand nav drawer that Android seems to prefer.

**Comment by eseidelGoogle** [comment]
Dragos implemented one of these.  Probably needs tweaks still, but it exists.
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/bottom_navigation_demo.dart
