### ISSUE TITLE
my issue

### ISSUE THREAD

**Issue by kazanooova** [flutter/flutter#35770]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
C:\Users\hp>flutter doctor -v
Checking Dart SDK version...
Building flutter tool...
Running pub upgrade...
The current Dart SDK version is 2.3.0-dev.0.5.flutter-a1668566e5.

Because flutter_tools depends on xml >=3.5.0 which requires SDK version >=2.3.0 <3.0.0, version solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
```

**Comment by ketanm** [comment]
Delete issue or add relevant content.

**Comment by Piinks** [comment]
Hi @kazanooova, Can you provide more information about your issue?

**Comment by gillestasse** [comment]
I have the same issue on osx. Which relevant content would you like me to provide ?

**Comment by ketanm** [comment]
Saw you updated log later.

It appears that you have dart and flutter installations issues. May happen if you changed location of your SDK or switch channel 

Change to stable version and update or reinstall.

**Comment by HimaniKanetkar** [comment]
I was facing the same issue and resolved it by Downloading my newer version of flutter SDK from below link.
https://flutter.dev/docs/get-started/install/windows

After that I update newer Flutter SDK stored path to my environment variable path and Flutter SDK path in Android Studio setting->Languages & Frameworks->flutter.
