### ISSUE TITLE
path_provider 1.1.2 not backwards compatible

### ISSUE THREAD

**Issue by michael-cheung-thebus** [flutter/flutter#35783]
Got very lightly bitten by this.  ^1.1.0 in pubspec, suddenly some files are not where they're expected to be.

Request to have 1.1.2 be 2.0.0 instead, I guess?

**Comment by nonComBen** [comment]
I have the same issue after updating the dependency from 1.1.0.  On Android, when trying to save to External Storage, getExternalStorageDirectory is returning the application document directory.

'String dir;

  if(Platform.isAndroid) {
    dir = (await getExternalStorageDirectory()).path;
  } else if(Platform.isIOS) {
    dir = (await getApplicationDocumentsDirectory()).path;
  }
print(dir);'

I/flutter (21084): /storage/emulated/0/Android/data/com.armynoncomtools.leadersbook/files

**Comment by EdwynZN** [comment]
I have the same problem with the version 1.1.2 on Android. I wanted to save the files directly in the download folder, but after the update it saves the files directly in the application directory

final _externalDirectory = await getExternalStorageDirectory();
dir = await Directory('${_externalDirectory .path}$/Download').create();
print(dir.path);

/storage/emulated/0/Android/data/com.apptest.myapp/files/Download

**Comment by Thetyne** [comment]
Same here ....

Please provide a new method, you can't change path in getExternalStorageDirectory by getExternalFilesDir.

That doesn't make any sense.

**Comment by michael-cheung-thebus** [comment]
As a background note, I'm guessing this change may have been inspired by [changes to how storage works in the Q beta](https://developer.android.com/preview/privacy/scoped-storage#filtered-view), and resulting [deprecation of the method previously used to implement this](https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory()).

I have many comments on this which I'm sure nobody is interested in, but unless this change is ultimately discarded, nobody should be holding their breath for path_provider to go back to the way it used to be.

**Comment by aliyazdi75** [comment]
Any update?

**Comment by nivla360** [comment]
I have the same issue, any solution, please?

**Comment by JonasVautherin** [comment]
My limited understanding of the new Android way is the following:

[`getExternalFilesDir`](https://developer.android.com/reference/android/content/Context.html#getExternalFilesDir(java.lang.String)) replaces the now-deprecated [`getExternalStoragePublicDirectory`](https://developer.android.com/reference/android/os/Environment.html#getExternalStoragePublicDirectory(java.lang.String)).

One big difference between them is that with the new way (`getExternalFilesDir`), those files are erased when the app is uninstalled: 

> This is like getFilesDir() in that these files will be deleted when the application is uninstalled.

And now there may be a need to call the MediaScannerConnection:

> Though these files are not automatically scanned by the media scanner, you can explicitly add them to the media database with MediaScannerConnection.scanFile. Note that this is not the same as Environment.getExternalStoragePublicDirectory() **[i.e. the deprecated one]**, which provides directories of media shared by all applications.

It seems to me that the directories of media shared by all applications would now come from the MediaStore, e.g. [`MediaStore.downloads`](https://developer.android.com/reference/android/provider/MediaStore.Downloads.html#EXTERNAL_CONTENT_URI), though I haven't tested it.

I do agree that breaking backward compatibility is unfortunate, as this function could have been deprecated in favor of new ones reflecting the new Android direction. This said, that's done already, so the current problem I see is that `path_provider` is now missing features:

1. Access to the "directories of media shared by all applications" (through MediaStore?)
2. A way to have the files "scanned" with `MediaScannerConnection.scanFile()` when using the new way.

Suggestions:
* Could somebody confirm that the old paths are now accessible in `MediaStore`?
* Would it make sense to add them to `path_provider`?
* Would it make sense to add the "scanning" feature to `path_provider`?

**Comment by JunoNgx** [comment]
Any update? Is there reliable way to get `/storage/emulated/0/` at the moment?

**Comment by andzejsw** [comment]
Is there a way to access Android "Downloads" dir?

**Comment by allanwolski** [comment]
This issue was opened a year ago and we don't have a solution.

This is a blocker for us, as we need to access the Download directory on Android to publish our app.

**Comment by braysonjohn148** [comment]
Any solutions, please

**Comment by csongorkeller** [comment]
Also have the same problem. Please any solution...

**Comment by kw2019ltd** [comment]
@TahaTesser  Also have the same problem. Please any solution...

**Comment by nicmaster** [comment]
Also have the same problem.

**Comment by dayron9110** [comment]
News?

**Comment by vyalikvo2** [comment]
You can use a Third-party package ext_storage.
https://pub.dev/packages/ext_storage/versions

Code:
`await ExtStorage.getExternalStorageDirectory();`

returns **storage/emulated/0/**




When you get compile error change kotlin_version to version what you have in your Android Studio (maybe need to update)
Tools -> Kotlin -> Configure Kotlin Plugin Udpates

_change `Flutter Plugins / ext_storage / build.gradle`_
```
buildscript {
    ext.kotlin_version = '1.3.72' // your version here
    repositories {
        ...
    }
    dependencies {
       ...
    }
}
```

**Comment by HenryDewa** [comment]
Also have the same problem. Please any solution...

**Comment by allanwolski** [comment]
The new file system must be used when targeting Android for API 29.

> To give users more control over their files and to limit file clutter, apps that target Android 10 (API level 29) and higher are given scoped access into external storage, or scoped storage, by default. Such apps have access only to the app-specific directory on external storage, as well as specific types of media that the app has created.

We need a solution for that.

**Comment by aashitgarodia** [comment]
> I have the same issue after updating the dependency from 1.1.0. On Android, when trying to save to External Storage, getExternalStorageDirectory is returning the application document directory.
> 
> ```
> String dir;
>   if(Platform.isAndroid) {
>     dir = (await getExternalStorageDirectory()).path;
>   } else if(Platform.isIOS) {
>     dir = (await getApplicationDocumentsDirectory()).path;
>   }
> print(dir);
> ```
> 
> I/flutter (21084): /storage/emulated/0/Android/data/com.armynoncomtools.leadersbook/files



> I have the same issue after updating the dependency from 1.1.0. On Android, when trying to save to External Storage, getExternalStorageDirectory is returning the application document directory.
> 
> ```
> String dir;
>   if(Platform.isAndroid) {
>     dir = (await getExternalStorageDirectory()).path;
>   } else if(Platform.isIOS) {
>     dir = (await getApplicationDocumentsDirectory()).path;
>   }
> print(dir);
> ```
> 
> I/flutter (21084): /storage/emulated/0/Android/data/com.armynoncomtools.leadersbook/files

Hii did you find any solution?

**Comment by justkost** [comment]
https://pub.dev/packages/downloads_path_provider

**Comment by CoderJava** [comment]
I have the same issue.

**Comment by metajet98** [comment]
Do we have anything new guys?

**Comment by AliEasy** [comment]
this may help
[https://stackoverflow.com/a/62087942/10264008](https://stackoverflow.com/a/62087942/10264008)

**Comment by novas1r1** [comment]
This is really blocking. I tried to work around it for hours now, but still didnt find any solution on this.

**Comment by nateshmbhat** [comment]
any updates on this ?

**Comment by FlashChaser** [comment]
Is there any documentation for working with the new Scoped Storage in Android 11 in flutter?

**Comment by stuartmorgan** [comment]
Closing as obsolete; it's unfortunately that there was a compatibility break (I'm not familiar with the context of that decision), but that can't be retroactively fixed. As well, `path_provider` has now had a major version change due to null safety.

As for the more recent comments, please file new issues describing the specific functionality you would like added to the current version of `path_provider`, or vote for existing issues if they are already filed.
