### ISSUE TITLE
how to use video as background for any screen 

### ISSUE THREAD

**Issue by ADLsourceCode** [flutter/flutter#35781]
Hello ,
how to use video as background for any screen and adjust it like image so that the video adjust itselfs in any screen size...Pls help, I am struggling with this..

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
