### ISSUE TITLE
Resolve app switcher issue where the wrong brightness version of the app is shown.

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#35795]
Resolve app switcher issue where the wrong brightness version of the app is shown.

When an iOS app is sent to the background, e.g., when accessing the app switcher with a swipe, the app is asked to render itself twice: in light mode and in dark mode. These bitmaps are saved by the OS to show in the app switcher.

Currently this behavior does not work for Flutter because of 2 issues:

1. Flutter animates its light/dark transition, which means it cannot produce a dark frame immediately.

2. It might be the case that this render behavior does not happen on a vsync, in which case there is a larger issue that Flutter cannot fulfill a render request at the given moment that one is needed.

**Comment by LongCatIsLooong** [comment]
I think this issue describes the same problem: https://github.com/flutter/flutter/issues/43806

**Comment by xster** [comment]
Merging into https://github.com/flutter/flutter/issues/43806
