### ISSUE TITLE
eventSink just call only once

### ISSUE THREAD

**Issue by VesperHan** [flutter/flutter#35794]
@Override
    public void onListen(Object o,final EventSink eventSink) {
        System.out.println("listen");
        this.event = eventSink;
    }

First add listener, is ok, when sent message to flutter , it doesn't work, the code ios is ok, android not work. I don't know why. Why the native call flutter so difficult why??????

**Comment by Piinks** [comment]
Hi @VesperHan, Can you post a fuller reproduction of the issue? We will need more information to help you resolve it.
