### ISSUE TITLE
flutter  v1.8.1-pre.44, on Mac OS X 10.14.5  Dio request error

### ISSUE THREAD

**Issue by haomeirong** [flutter/flutter#35797]
07-09 16:22:20.877 12991-13063/com.haier.usdk.app E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: type '_StreamHandlerTransformer<List<int>, List<int>>' is not a subtype of type 'StreamTransformer<Uint8List, List<int>>' of 'streamTransformer'#0      Stream.transform (dart:async/stream.dart)
    #1      DefaultTransformer.transformResponse (package:dio/src/transformer.dart:102:48)
    <asynchronous suspension>
    #2      Dio._makeRequest (package:dio/src/dio.dart:771:38)
    <asynchronous suspension>
    #3      Dio._request.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:710:22)
    #4      _rootRunUnary (dart:async/zone.dart:1132:38)
    #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
    #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
    #8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
    #9      Future._complete (dart:async/future_impl.dart:473:7)
    #10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
    #11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
    #12     _rootRun (dart:async/zone.dart:1120:38)
    #13     _CustomZone.run (dart:async/zone.dart:1021:19)
    #14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
    #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
    #16     _rootRun (dart:async/zone.dart:1124:13)
    #17     _CustomZone.run (dart:async/zone.dart:1021:19)
    #18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
    #19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
    #20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
    #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by elisar4** [comment]
I think this is Dio package problem
see this issue: https://github.com/flutterchina/dio/issues/360

**Comment by LongCatIsLooong** [comment]
Thanks @elisar4. Closing as not directly related to flutter.
