### ISSUE TITLE
Google signin issue  flutter

### ISSUE THREAD

**Issue by yogesh1211** [flutter/flutter#35791]
When try to login with google this Exception was thrown i used google signin latest 4.0.2

11:43:35.817 13 info flutter.tools E/ConnectivityManager.CallbackHandler(20243): callback not found for RELEASED message
11:43:37.110 14 info flutter.tools E/flutter (20243): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'PlatformException' is not a subtype of type 'String'
11:43:37.110 15 info flutter.tools E/flutter (20243): #0      _LoginState._loginWithGoogle (package:offershare/login_page.dart:242:32)
11:43:37.110 16 info flutter.tools E/flutter (20243): <asynchronous suspension>
11:43:37.110 17 info flutter.tools E/flutter (20243): #1      _LoginState.build.<anonymous closure> (package:offershare/login_page.dart:95:9)
11:43:37.110 18 info flutter.tools E/flutter (20243): #2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
11:43:37.110 19 info flutter.tools E/flutter (20243): #3      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
11:43:37.110 20 info flutter.tools E/flutter (20243): #4      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:177:9)
11:43:37.110 21 info flutter.tools E/flutter (20243): #5      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:436:9)
11:43:37.110 22 info flutter.tools E/flutter (20243): #6      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
11:43:37.110 23 info flutter.tools E/flutter (20243): #7      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
11:43:37.110 24 info flutter.tools E/flutter (20243): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:221:19)
11:43:37.110 25 info flutter.tools E/flutter (20243): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
11:43:37.110 26 info flutter.tools E/flutter (20243): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
11:43:37.110 27 info flutter.tools E/flutter (20243): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
11:43:37.110 28 info flutter.tools E/flutter (20243): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
11:43:37.110 29 info flutter.tools E/flutter (20243): #13     _rootRunUnary (dart:async/zone.dart:1136:13)
11:43:37.110 30 info flutter.tools E/flutter (20243): #14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
11:43:37.110 31 info flutter.tools E/flutter (20243): #15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
11:43:37.110 32 info flutter.tools E/flutter (20243): #16     _invoke1 (dart:ui/hooks.dart:233:10)
11:43:37.110 33 info flutter.tools E/flutter (20243): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
11:43:37.110 34 info flutter.tools E/flutter (20243):

**Comment by Piinks** [comment]
Hi @yogesh1211, Can you post a reproduction of the issue along with the output of `flutter doctor`? We will need more information to help you resolve it.
