### ISSUE TITLE
i got some issue about  streambuilder 

### ISSUE THREAD

**Issue by DioBrandoLong** [flutter/flutter#35790]
here is my problem I was using TabBarView and streambuilder
first come in it's ok 
![bug1](https://user-images.githubusercontent.com/27342144/60861650-b129d100-a24d-11e9-992a-f3f832bb441b.PNG)
![bug2](https://user-images.githubusercontent.com/27342144/60861655-b424c180-a24d-11e9-9866-af237c05d7c0.PNG)

It was executed twice but it's ok i got data.
but when is click de last item and come back first item here's the problem 
![bug3](https://user-images.githubusercontent.com/27342144/60861763-0a920000-a24e-11e9-9828-e7798a774425.PNG)
It was executed three times!
![bug4](https://user-images.githubusercontent.com/27342144/60861885-74aaa500-a24e-11e9-885b-718309a654b4.PNG)
![bug5](https://user-images.githubusercontent.com/27342144/60861887-77a59580-a24e-11e9-84c5-f87990efe96a.PNG)
![bug6](https://user-images.githubusercontent.com/27342144/60861890-796f5900-a24e-11e9-86bf-d3621bc68db2.PNG)

I don't know why.

**Comment by Piinks** [comment]
Hi @DioBrandoLong, Can you post a sample of code that reproduces you issue instead of screenshots? Please also include the output of `flutter doctor`. We will need more information to help you resolve it.

**Comment by ketanm** [comment]
Hi @DioBrandoLong, 

Do share your actual `StreamBuilder` code block as suggested by @Piinks. Also, can you show whether you are using `AsyncSnapshot` in builder?

Lastly, inside the StreamBuilder body, it would be good to add check for status and error before processing data, i.e.

`StreamBuilder<QuerySnapshot>(stream: ...., builder: ...) {
   if (!snapshot.hasError) {
      switch (snapshot.connectionState) {
         case: ConnectionState.waiting:  
                some infor or waiting icon
         case ConnectionState.active:
                process data
      }
   }`
