### ISSUE TITLE
websocket become slow after debug

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#35804]
I write a websocket app, which use 
 await for (String message in socket) {

but after debug line by line for a moment , the await for becomes very slow. and sometime automatically close the socket; and at the same time http2 of dart stopped work any more.

any one can share me some glue to get the root cause;  I am not sure whether there will be no problem in released app;

**Comment by BondarenkoStas** [comment]
@wanjm Did you manage to solve the problem? Do you experience it using latest flutter stable?

**Comment by wanjm** [comment]
sorry, it is still there ;

**Comment by wanjm** [comment]
is there anything wrong with microtask, I found the it is blocked after sendData just add it to pending state, and then one mircrotask is schedule to send it out;

any more tips for me to debug this ?

**Comment by markusaksli-nc** [comment]
Hi @wanjm 
I'm afraid there is too little information for this issue to be actionable yet. Could you please provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with the steps to reproduce this behavior. It would also be helpful if you could provide the logs that demonstrate this issue.
Thank you.

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
