### ISSUE TITLE
Vscode does not give code completion suggestion 

### ISSUE THREAD

**Issue by mausamRayamajhi** [flutter/flutter#35805]
Code suggestion works fine in intellij but does not in vscode.
Black backgraound image from Vscode and other is intellij
![1](https://user-images.githubusercontent.com/28975010/60895662-c2420480-a284-11e9-98cc-1d5479a5d505.png)
![2](https://user-images.githubusercontent.com/28975010/60895665-c2da9b00-a284-11e9-8f98-ece15c1b5449.png)

**Comment by stuartmorgan** [comment]
Dart Code has [its own issue tracker](https://github.com/Dart-Code/Dart-Code/issues); this would need to be filed there.
