### ISSUE TITLE
flutter build apk --debug is slow

### ISSUE THREAD

**Issue by safield** [flutter/flutter#35807]
I have a small flutter app that is a few files which I am developing on Windows 10. 

I recently updated to flutter version Flutter 1.7.8+hotfix.2.

Prior to updating, the time it would take to for _flutter build apk --debug_ to complete (after changing 1 file)  was about 8 seconds. After the update it is around 35 seconds.

These times are based on a single changed file. I would run build apk, Then change only a single file, then run build apk again, and measure the time on the second build.

These build times are untenable.

An example of a build output is as follows

```
Initializing gradle...                                              0.9s
Resolving dependencies...                                           2.9s
Running Gradle task 'assembleDebug'...                          
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Running Gradle task 'assembleDebug'...                             37.0s
Built build\app\outputs\apk\debug\app-debug.apk.
[Finished in 43.9s]
```

**Comment by safield** [comment]
It seems that tasks that have increased in time substantially are...

compileflutterBuildDebugArm
compileflutterBuildDebugArm64

**Comment by eduardoflorendo** [comment]
#41974

**Comment by iapicca** [comment]
Hi @safield  
are you still experiencing this issue with the latest stable version of flutter?
thank you

**Comment by VladyslavBondarenko** [comment]
The issue is already long time not active and without answer.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please
