### ISSUE TITLE
Connectivity().onConnectivityChanged unexpectedly informs of connectivity state upon listen()

### ISSUE THREAD

**Issue by dspicher** [flutter/flutter#35802]
From the documentation and gleaning at the implementation, it seems like the Stream `onConnectivityChanged` in the `connectivity` package should only emit notifications to changes in the connectivity state. However, when used in a `StreamBuilder`, the stream immediately emits a current connectivity state. What is the reason for this?

The behaviour can be reproduced with the small app below. 

```dart
import 'package:connectivity/connectivity.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'connectivity demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<ConnectivityResult>(
      stream: Connectivity().onConnectivityChanged,
      builder:
          (BuildContext context, AsyncSnapshot<ConnectivityResult> snapshot) {
        if (snapshot.hasError) {
          return Text(
              "Something has gone wrong determining the connectivity state");
        }

        if (!snapshot.hasData) {
          return Text("Determining the connectivity state");
        }

        if (snapshot.data == ConnectivityResult.none) {
          return Text("Connectivity lost");
        }

        return Text("OK");
      },
    );
  }
}
```

`flutter doctor -v`:
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /home/spd/flutter/flutter
    • Framework revision 7a4c33425d (2 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/spd/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/spd/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/spd/android-studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.36.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • Moto G 5 Plus             • ZY2247B62J    • android-arm • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by BondarenkoStas** [comment]
@dspicher Is it the same using latest flutter stable and connectivity 0.4.4?

**Comment by csells** [comment]
@dspicher is this behavior causing you trouble of some kind?

**Comment by dspicher** [comment]
Sorry for the late response.

I can confirm that the issue still exists on `connectivity: '^0.4.8+5'`.

In our specific case, yes, we were relying on the `Stream` only emitting events when connectivity changed, not upon initial subscription. But regardless, this behaviour doesn't seem to be in line with what the documentation suggests.

I have also fixed an unfortunate copy-paste error in the sample app above, it should work now.

**Comment by tony123S** [comment]
Sometimes it work, but sometimes it still display ConnectivityResult.wifi although there is no network.
https://github.com/flutter/flutter/issues/81177

**Comment by stuartmorgan** [comment]
Closing as `connectivity` is deprecated in favor of [`connectivity_plus`](https://pub.dev/packages/connectivity_plus).
