### ISSUE TITLE
Why flutter' GridView can not merge cells?

### ISSUE THREAD

**Issue by biij5698** [flutter/flutter#35800]
If the flutter's GridView can merge cells, this will be very useful.
Two day's ago I opened a issues, but it be closed,i don't know why.

**Comment by phanirithvij** [comment]
It was reopened https://github.com/flutter/flutter/issues/35691

**Comment by LongCatIsLooong** [comment]
@phanirithvij thanks for pointing out. Closing in favor of the other (older) issue.
