### ISSUE TITLE
Android Studio stuck on "Installing and Launching" when using real IOS device and no console output from app.

### ISSUE THREAD

**Issue by BooberBunz** [flutter/flutter#35801]
UPDATE 2:

Problem continues to occur as of 7/17/19.

UPDATE 1:

In my case, it seems that in order for everything to work correctly, the USB connection to the iPhone simply needs to be reset (unplugged/replugged) between every cold restart of a Flutter app in Android Studio... otherwise the following bug (?) still occurs:

FACTS:

- I am new to flutter and am not a software engineer or UNIX expert
- XCode *is* able to run native IOS apps on my (real) device normally and communicate with it via USB -- with console output working.
- I checked the other threads #22603 and #22595 but updating usbmuxd and libimobiledevice did not seem to fix my particular issue.
- Flutter Doctor reports no problems and my Flutter apps generally run fine on Android devices and simulators... and IOS *simulators* ...

But as the subject line states, real IOS devices do not ever get to the point where console output becomes visible/active... as Android Studio seems to get stuck in the "Installing and launching" phase (even though the app *does* launch completely).

## Steps to Reproduce

1. ... Run any Flutter app targeting a real IOS device using Android Studio.

```
/Users/boober/flutterdev/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/boober/flutterdev/flutter
    • Framework revision 7a4c33425d (2 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/boober/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • Boober's iPhone • 61z2b2ezzz8fe49z5fz9fzzzb8ez03fzzz31z61d • ios • iOS 12.1.4

• No issues found!
```
Also:

brew info libimobiledevice
libimobiledevice: stable 1.2.0 (bottled), HEAD
Library to communicate with iOS devices natively
https://www.libimobiledevice.org/
/usr/local/Cellar/libimobiledevice/HEAD-fff10db_3 (67 files, 1MB) *
  Built from source on 2019-06-14 at 03:02:48
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libimobiledevice.rb
==> Dependencies
Build: pkg-config ✔
Required: libplist ✔, libtasn1 ✔, openssl ✔, usbmuxd ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 54,805 (30 days), 168,519 (90 days), 605,535 (365 days)
install_on_request: 47,426 (30 days), 146,970 (90 days), 523,264 (365 days)
build_error: 0 (30 days)

............... and:

Adams-MBP:~ boober$ brew info usbmuxd
usbmuxd: stable 1.0.10 (bottled), HEAD
USB multiplexor daemon for iPhone and iPod Touch devices
https://www.libimobiledevice.org/
/usr/local/Cellar/usbmuxd/HEAD-6539b02_1 (13 files, 146.3KB) *
  Built from source on 2019-07-09 at 06:26:22
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/usbmuxd.rb
==> Dependencies
Build: pkg-config ✔
Required: libplist ✔, libusb ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 38,274 (30 days), 107,747 (90 days), 338,022 (365 days)
install_on_request: 30,300 (30 days), 84,581 (90 days), 222,514 (365 days)
build_error: 0 (30 days)

**Comment by BondarenkoStas** [comment]
Seems like return of #6385.

**Comment by BondarenkoStas** [comment]
@BooberBunz does it also occurs in the latest flutter stable?

**Comment by BooberBunz** [comment]
Unfortunately I have no idea what the problem was or how it was fixed, but this particular issue is gone after updating to Android Studio 3.5 (Build #AI-191.8026.42.35.5791312), OSX 10.15 Catalina Beta (19A558d), Xcode 11 (11A420a), Flutter v1.9.1+hotfix.2, and reinstalling Cocoapods (1.8.1).
