### ISSUE TITLE
run problem.dependencies

### ISSUE THREAD

**Issue by bestheroforever** [flutter/flutter#35811]
![Screenshot from 2019-07-09 21-33-20](https://user-images.githubusercontent.com/47401731/60908592-7f3a5e00-a291-11e9-9d89-da2046da00c7.png)

**Comment by bestheroforever** [comment]
It takes a lot of time.and nothing happen :(

**Comment by BondarenkoStas** [comment]
@bestheroforever Do you encounter the issue using latest flutter stable?

**Comment by bestheroforever** [comment]
yes

**Comment by BondarenkoStas** [comment]
@bestheroforever please provide your flutter doctor -v output. Does it happen with any project or with a particular one? Does it happen when you run it on an emulator or physical device or both and which ones?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
