### ISSUE TITLE
Document how to import the http library, add example

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3581]
We embed the http library into our distro. We should:
- [x] document how to import it, as a library-level doc
- [ ] add some simple library-level docs for how to use this library in the common cases

(this assumes that we're not going to be able to merge our changes back into the main http package w/ configurable imports anytime soon)

**Comment by eseidelGoogle** [comment]
This is being replaced by fixing https://github.com/dart-lang/http/issues/1 which I'm promised will be this quarter.
