### ISSUE TITLE
[firebase_crahlytics] Handle FlutterErrorDetails without stacktrace

### ISSUE THREAD

**Issue by PabloPL** [flutter/flutter#35813]
## Steps to Reproduce
1. use firebase_crashlytics: ^0.0.4+3
2. Use library which creates FlutterErrorDetails and calls FlutterError.onError (for example flutter_svg library) or do it in code

## Current behaviour
If we have FlutterErrorDetails which doesn't have stacktrace filled, there will be another error (created by Trace.format which will call Trace.from. both from stack_trace library), when trying to handle this error.

## Expected behaviour
Exception will be handled and logged (and no exception will be generated during this).

## Explanation
Currently firebase_crashlytics when handling error (FlutterErrorDetails), assumes that it has stacktrace filled-in (for example https://github.com/flutter/plugins/blob/master/packages/firebase_crashlytics/lib/src/firebase_crashlytics.dart#L41), by calling Trace.format which will call Trace.from, which will in this case will throw ArgumentError).

By looking at comment at https://github.com/flutter/flutter/issues/30007#issuecomment-482745065 , this could be improved and in that case it could use StackTrace.current, so we won't get error during handling error.

## Flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.2 at /home/pablo/flutter
    • Framework revision 2e540931f7 (7 days ago), 2019-07-02 09:31:07 -0700
    • Engine revision b1cb0d9e9b
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/pablo/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/pablo/Programy/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[!] Android Studio (version 3.4)
    • Android Studio at /home/pablo/Programy/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

**Comment by rmtmckenzie** [comment]
I was about to open this same issue. I'd like to add to it that firebase_crashlytics should be able to handle any valid FlutterErrorDetails object - from the FlutterErrorDetails docs:

> The [exception] must not be null; other arguments can be left to
> their default values. (`throw null` results in a
> [NullThrownError] exception.)

So it should be able to handle a FlutterErrorDetails with only an exception.

**Comment by creativecreatorormaybenot** [comment]
I am glad to inform you that I fixed this awhile back in https://github.com/flutter/plugins/pull/1912, i.e. [`firebase_crashlytics` version `0.1.0+1`](https://pub.dev/packages/firebase_crashlytics#0101).

**Comment by PabloPL** [comment]
Closing this issue since it has been fixed. Thanks.
