### ISSUE TITLE
[Request] Widget error boundaries

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#35821]
This is a follow up to https://github.com/flutter/flutter/issues/19993#issuecomment-509739755

### The use case

It is currently not possible to have an error handling scoped to a widget tree.
There are methods for similar things such as `FlutterError.onError` & `ErrorWidget.builder`, but they are global variables. So the entire widget tree is affected.

One of the main use-case for scoped error handling is for UI feedback like an "Oops! Something went wrong." screen.

As an example, consider the following widget tree:

```
MaterialApp
  Home
    Scaffold
      appBar: AppBar
      body: Very
        Deep
          Tree
```

where `Home` doesn't know anything about how `Tree` is implemented (and shouldn't)
and where something unexpected happens when rendering `Tree` (typically an unhandled error on `FutureBuilder`)

In response to that exception, the UI is expected to show an error screen.
The error screen is _not_ global, it is scoped to `Home`, such that the widget tree of the error screens looks like this:

```
MaterialApp
  Home
    Scaffold
      appBar: AppBar
      body: OopsScreen
```
_____

Such a scenario is not easily possible right now.

We can't use `FlutterError.onError` because it is global. 
Routes other than `Home` may want a similar behavior. But we don't want an exception happening inside `Home` to trigger the error screen of the entire navigation history.

We can't use `ErrorWidget.builder` either for the same reasons with one bonus: Even without the global issue, the generated widget tree using `ErrorWidget.builder` would be invalid.

We'd end up with: 

```
MaterialApp
  Home
    Scaffold
      appBar: AppBar
      body: Very
        Deep
          Tree
            OopsScreen
```

which is undesired as `Very`/`Deep` are free to introduce visual changes through `Padding` or whatever similar widget.

### The suggestion

The idea is to introduce an `ErrorScope`/`ErrorBoundary` widget

Then, our `Home` could be implemented this way:

```dart
@overide
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(),
    body: ErrorBoundary(
      builder: (context, error) {
        if (error != null) {
          return OopsScreen();
        }
        return Very();
      }
    ),
  );
}
```

As for implementation details:

- `ErrorBoundary` only catch exceptions that happen inside one of the life-cycles of its descendants (so `build`, `initState`, ...). It is not triggered on exceptions from widgets that are _not_ one of its descendants.
- Calls to `FlutterError.onError` is still performed made even if a boundary catch the exception (debatable)
- `ErrorWidget.builder` is used only in a situation where no `ErrorBoundary` were found or none of them caught the error.

- `ErrorBoundary` can technically fail too, in which case, the next boundary attempts to catch the error. 
  ```dart
  ErrorBoundary(
    onError: (_, __) => Text('error'),
    child: ErrorBoundary(
      onError: (_, error) {
        print(error);
        throw errror;
      },
      child: Something(),
    )
  );
  ```

cc @eseidelGoogle

**Comment by eseidelGoogle** [comment]
Thank you @rrousselGit!  @goderbauer @Hixie

**Comment by goderbauer** [comment]
There's @Hixie's comment in https://github.com/flutter/flutter/issues/19993#issuecomment-427530444 that we don't really want to encourage people to throw in a builder. Maybe you could post a more concrete code example of where this may be OK in combination with a `FutureBuilder` to re-evaluate that statement?

**Comment by rrousselGit** [comment]
While trying to answer, I actually taught of a way to make it myself as a package. So here it is: https://github.com/rrousselGit/boundary (it still lacks error reporting)

There's an example using `FutureBuilder` [here](https://github.com/rrousselGit/boundary/blob/master/example/lib/future_builder.dart), which shows that such behavior allows greater separation of concern:

The widget that handles the loading/error state is unaware of "what is loading". 

```dart
Boundary(
  fallbackBuilder: (_, error) {
    // doesn't have the reference on the Future, but
    // is still able to display loading/error state
    if (error is Loading) {
      return const Center(child: CircularProgressIndicator());
    } else if (error is NotFoundError) {
      return const NotFoundScreen();
    } else {
      return const OopsScreen();
    }
  },
  child: SubtreeThatHasAFutureBuilder(),
)
```

![future builder example](https://raw.githubusercontent.com/rrousselGit/boundary/master/resources/future_builder.gif?token=AEZ3I3NDM2W3MC34RXS5YXS5GSIEK)



There are some limitations as a package though:
- Tests are more difficult to write, as we have to restore `FlutterError.onError`/`ErrorWidget.builder` before doing any `expect`.
- I had to use `Stack` + `Offstage` to switch between the original and the fallback tree without losing the state of the original tree.
  If it was built-in, in theory, no `RenderObject` would be needed at all. This would allow things like:

  ```dart
  Column(
    children: [
      Boundary(
        fallbackBuilder: ...,
        child: Expanded(child: ...),
      ),
    ]
  ),
  ```
  Which is currently not possible because `Boundary` adds unwanted `RenderObject`s.

**Comment by Hixie** [comment]
The entire framework is designed with the assumption that code will not throw. We have some error handling code in some places to vaguely try to avoid the entire framework falling over when some error happens, which sometimes aids with hot reload, but it's not at all supposed to be rigorous or reliable. I don't think we should attempt to provide this feature in the framework. Doing it right would require a significant overhaul and would have serious implications on performance.

**Comment by rrousselGit** [comment]
>  but it's not at all supposed to be rigorous or reliable.

In which situation is it unreliable?

From my previous tests, it seems that without changing the API at all, we can get pretty good results.

**Comment by Hixie** [comment]
> In which situation is it unreliable?

Any time the exception happens so as to leave the framework in an inconsistent state. This is common especially when the exception happens because of a violation of some framework-related contract, e.g. including a null in a child list or whatever. It also happens with user code, e.g. if the exception is thrown while the user's data model is in an inconsistent state, e.g. because it happened as a result of an invalid use of the user's data model.

**Comment by rrousselGit** [comment]
That's a fair point.

The idea of this feature is not to catch unexpected stuff though, but to _explicilty_ defer building process to a widget higher in the hierarchy.

As such, a possibility is to make this work only for a specific class, where `StateError`/... are not covered, but explicit custom made exceptions are fine.

This way, such boundary won't make the state unreliable if something happens inside `initState`.
But we still get the cool separation of concern boost from boundaries.

**Comment by rrousselGit** [comment]
What about using a widget instead of throwing?

I've slightly modified the sources of my current implementation, such that instead of:

```dart
Boundary(
  fallbackBuilder: (context, err) => Text(err.toString()),
  child: Builder(builder: (_) {
    throw 42;
  }),
)
```

we get:

```dart
Boundary(
  fallbackBuilder: (context, err) => Text(err.toString()),
  child: Builder(builder: (_) {
    return Defer(42);
  }),
)
```


_____


The end result is strictly the same:

A widget deep in the widget tree can ask to temporarily abort the building this tree, and ask one of its ancestors to create a fallback tree.

But we're not using exceptions anymore.

**Comment by Hixie** [comment]
I don't understand the problem we're trying to solve anymore. The original problem was "error handling scoped to a widget tree". The most recent comment seems unrelated to this.

Can you describe the problem you're trying to solve, without referencing the solution you would like?

**Comment by rrousselGit** [comment]
To let a widget defer the handling of a local error/loading state to one of its ancestors, without strongly coupling both widgets.
And without having to make the ancestor aware of the implementation details of the said widget.

`Notification` can be used to handle states without impact on the UI.
But there's currently no mean for a widget to say to one of its ancestors "You probably don't want to show me, and instead show a spinner or an error screen".

Currently, we have to make the ancestor aware of implementation details of the descendant.
Alternatively we can use `Offstage` or delayed `setState`, but we'll be a frame behind the state all the time (similarly to a widget trying to use `RenderBox.size` in `build`).

Such widget solves that, by being able to *synchronously* build a fallback tree if needed.

**Comment by Hixie** [comment]
I guess maybe what I don't understand is why would a widget _ever_ have error state? It seems like that kind of thing should be in the app's data model, not in a widget. Can you give a concrete example?

**Comment by rrousselGit** [comment]
An Image.network.
There's a loading state while the image is loading, and if it fails, there's an error state. 

But there's absolutely no reason to make ancestors of the image aware of the Future used to load the image.

And even then, using widgets to represent the "apps data model" is pretty good.
Widgets makes it easier to know when to create/update/delete any kind of data, not just UI related bits. 
It's very maintainable, while staying very simple.

**Comment by Hixie** [comment]
Image.network is an interesting example, because it's one of the few widgets that violates the basic principle of "widgets shouldn't do work". I think the right way to do it is to have the image loading logic in the app state, not the widget. We have the widget because it's convenient for demos, but it keeps coming up as an example of a misdesigned widget.

**Comment by rrousselGit** [comment]
> it's one of the few widgets that violates the basic principle of "widgets shouldn't do work". 

It's interesting that you think that. Why do you think that there's such rule? Because it seems like the biggest reason behind our differences in most of my proposals, including 
 https://github.com/flutter/flutter/pull/33213#issuecomment-513474323.

Coming from React, it's very natural to me for widgets to "do work". Widgets makes everything simple and maintainable. And if there's something that we want to keep simple and maintainable, that's definitely the app state. 
Even some members of the Flutter team says "You don't necessary need a state management library, start with setState".

**Comment by eseidelGoogle** [comment]
FWIW, I agree with you Ian that Image.Network was a mistake.  We should have separated out the loading from the decoding from the displaying, like how iOS and other systems do. :)

**Comment by Hixie** [comment]
> Why do you think that there's such rule?

Empirically, it leads to poorly structured code. When you separate the UI logic from the business logic you end up with a much more coherent design. In this case, we're talking about network traffic and image decoding, which isn't UI logic.

You should never need to get into a state where you build widgets that you don't want to render. It's highly inefficient and defeats much of the purpose of the way Flutter is designed, which is to minimize the work used when rendering. We're fast because we avoid this kind of thing.

**Comment by rrousselGit** [comment]
> You should never need to get into a state where you build widgets that you don't want to render

It's not that "the widget don't want to render".
More like "the rendering should be handled else-where".

There's still a rendering performed. But it's done by another widget higher in the tree, in a different branch.

In some way, it's a bit like `OverlayEntry`.


> When you separate the UI logic from the business logic you end up with a much more coherent design

I don't want to start an entire debate on that, but TD;DR:

Having business logic inside widgets is not incompatible with separating UI and business though. There are quite a few examples inside Flutter already:
- InheritedWidgets
- Builders

Using these, we can make a widget have only business logic and no UI.

For example, we could have a `User` widget, that works like `StreamBuilder`, but instead of taking a `Stream`, takes a user-id. And it'd internally do data-fetching and handle the update scenario when the user-id changes:

```dart
User(
  id: 42,
  builder: (context, AsyncSnapshot<User> snapshot) {
    if (!snapshot.hasData) return const CircularProgressIndicator();
    return Text(snapshot.data.name);
  }
);
```

The real bonus of such architecture is that we have the same level of composability/declarativeness of UI, for business-logic.

**Comment by Hixie** [comment]
> It's not that "the widget don't want to render".
> More like "the rendering should be handled else-where".
> 
> There's still a rendering performed. But it's done by another widget higher in the tree, in a different branch.

If it's done by another widget, then the first widget didn't want to render...


I would strongly recommend against using a widget to do network traffic.

If you want composability/declarativeness for business logic, you can do that; it seems like a fine idea; but I wouldn't recommend doing it in a tree optimized for UI. You shouldn't need to trigger an update to the display when no pixels need to change.

**Comment by rrousselGit** [comment]
Then the documentation and the way other team members speaks is very confusing, especially for React developers as React fully embrace that (and will recommend to do data fetching using their widgets equivalent). 

The team shouldn't say "start with setState for managing your app state" nor should the documentation say [everything is a widget](https://flutter.dev/docs/resources/technical-overview#everything's-a-widget). 

Although arguably, no frame should be drawn unless "RenderObject.paint" was called at least once. 

In any case, this and my opened PR are both for using widgets that way. So if Flutter don't want to have such architecture, these can probably be closed.

**Comment by Hixie** [comment]
"Everything" in the Flutter library is a widget. But your business logic isn't in the Flutty library. :-)

cc @mjohnsullivan @RedBrogdon for thoughts on positioning (see comments above)

**Comment by Hixie** [comment]
I'm closing this since it's not something we want to change in the framework.
