### ISSUE TITLE
TextRecognition does not work on Firebase_ml_kit iOS

### ISSUE THREAD

**Issue by OmitedClient** [flutter/flutter#35820]
Please check the link for stackoverflow that explains the issue. Just to add an information when i roleback the version to firebase_ml_vision: ^0.1.2 it worked (but does not recognize some numbers in a simple document white background and black numbers).

https://stackoverflow.com/questions/56840484/cannot-recognize-text-when-using-firebase-ml-vision-kit-from-camera

Can you please help to see if this is an issue?

Got another user reporting the same behaviour.

**Comment by Dillenwong** [comment]
Hi did you managed to solve this issue? I'm having the same issue too. it works on Andriod but not iOS

**Comment by BondarenkoStas** [comment]
@OmitedClient did you solved the issue? Is it the same using latest flutter stable and firebase_ml_vision 0.9.2+2?

**Comment by kalismeras61** [comment]
I have also same problem. It is working on simulator when i select image from gallery on IOS device but doesnt work on real device.!

**Comment by EHGOLDFISH** [comment]
Make sure you add this line
pod 'Firebase/MLVisionTextModel' 
in the Podfile

**Comment by stuartmorgan** [comment]
Closing as this plugin moved to https://github.com/FirebaseExtended/flutterfire, so the issue needs to be filed there.
