### ISSUE TITLE
GRPC connection fails in Flutter

### ISSUE THREAD

**Issue by kgignatyev** [flutter/flutter#35835]
it does not seem to be network related because the same code works on different machines and getting data from GRPC service running  at 192.168.1.125

and if I try to connect with DIO the network connection happens, server complains about invalid request method, which indicates that connection was established but protocol is wrong

I/flutter (28839): Caught GRPC error: gRPC Error (14, Error connecting: SocketException: OS Error: Connection refused, errno = 111, address = 192.168.1.125, port = 34088)
I/flutter (28839): Caught DIO error: DioError [DioErrorType.DEFAULT]: HttpException: Invalid request method, uri = http://192.168.1.125:8443

===
relevant code below
      try {
//
        final channel = new ClientChannel('192.168.1.125',
            port: 8433,
            options: const ChannelOptions(
                credentials: const ChannelCredentials.insecure()));
        ServiceClient tmp = new ServiceClient( channel,options: CallOptions(timeout: Duration(seconds: 300)) );
        final response = await tmp.list_transactions( TransactionsRequest.create());
        print(' received client received: ${response}');
      } catch (e) {
        print('Caught GRPC error: $e');
      }

      try {

        final response = await ImaniApi.dio.get('http://192.168.1.125:8443');
        print('transactions received client received: ${response}');
      } catch (e) {
        print('Caught DIO error: $e');
      }

kgignatyev$ flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.2, on Mac OS X 10.13.6 17G7024, locale en-US)
    • Flutter version 1.7.8+hotfix.2 at /Users/kgignatyev/dev/mobile/flutter
    • Framework revision 2e540931f7 (7 days ago), 2019-07-02 09:31:07 -0700
    • Engine revision b1cb0d9e9b
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/kgignatyev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.3

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830

[✓] Connected device (2 available)
    • SM G965U  • 444b37484d533098                     • android-arm64 • Android 9 (API 28)
    • iPhone XR • EA4BBCB8-CAA9-47A3-850D-EAE9D7C1D456 • ios           • iOS 12.1 (simulator)

• No issues found!

**Comment by kgignatyev** [comment]
Works after recent update. Although reporting wrong port on error messages is really annoying!!! https://github.com/dart-lang/sdk/issues/12693

**Comment by forest5013** [comment]
I got the same error today in Android 

flutter doctor -v                                                               
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.1 at C:\src\flutter
    • Framework revision c5a4b4029c (6 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\wulin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\wulin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 89.0.774.77

• No issues found!
