### ISSUE TITLE
`flutter test --platform chrome` should not be available on `stable` channel yet

### ISSUE THREAD

**Issue by truongsinh** [flutter/flutter#35847]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-VN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Steps:
- go to any package with `test` (in this case, I will use https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql as an example)
- `flutter test --platform chrome`

Observed behavior:
- test running with weird results

Expected behavior:
```
"chrome" is not an allowed value for option "platform".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

==========
Steps:
- `flutter test -h`

Observed behavior:
```
# abridged
    --[no-]test-assets          Whether to build the assets bundle for testing.
                                Consider using --no-test-assets if assets are not required.
                                (defaults to on)

    --platform                  The platform to run the unit tests on. Defaults to "tester".
                                [tester (default), chrome]
```

Expected behavior:
Platform "chrome" should not be a valid choice and should not be displayed.

# Note
`flutter test --platform chrome` should come together with flutter for web (they both should be available, or both unavailable)

**Comment by truongsinh** [comment]
cc @Hixie

**Comment by BondarenkoStas** [comment]
@truongsinh As after flutter 1.9 web support is already available in tech preview, I think it's safe to close the issue. If you disagree, please comment and I will re-open it right away.
