### ISSUE TITLE
Flutter UI testing framework questions

### ISSUE THREAD

**Issue by lanzhu1993** [flutter/flutter#35843]
## Steps to Reproduce

I have a question here I would like to ask, Flutter maps the android platform Widget to android.widget.xxx control. What is the difference between the underlying rendering mechanism and the View corresponding to android by parsing the XML file? Currently, I am developing a Flu testing UI testing framework. , refer to uiautomator+cucumber to achieve, please also advise

## Logs

```
```

```
```

```
```

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
