### ISSUE TITLE
Optionally bypass startup lock when `pub run`

### ISSUE THREAD

**Issue by chengyuhui** [flutter/flutter#35855]
## Use case
When `flutter pub run build_runner watch` is running, it is impossible to start debugging the app because of the startup lock, which is really annoying (it is reasonable to have `pub get` stuck here, but really not convenient for debugging).

## Proposal
Do not wait for startup lock when `flutter pub run`.

**Comment by janmoppel** [comment]
Hello @chengyuhui !

Does the problem still persist? Have you found the solution?
Also, this issue seems to be related to what you describing: https://github.com/google/built_value.dart/issues/361

**Comment by chengyuhui** [comment]
It is somehow different.
In my case, running `flutter run` first works flawlessly. However, when `flutter run` exits (either Ctrl-C or disconnecting device), it is not possible to start it again without killing build runner process.

**Comment by jmagman** [comment]
I think this was fixed by https://github.com/flutter/flutter/pull/59012.
