### ISSUE TITLE
Unable to locate Android sdk flutter while runnin on intellij

### ISSUE THREAD

**Issue by ChiragRayani** [flutter/flutter#35850]
![Screenshot from 2019-07-10 10-58-39](https://user-images.githubusercontent.com/32605614/60943012-543c2280-a302-11e9-9047-e9de0f0f2d91.png)

**Comment by ChiragRayani** [comment]
![Screenshot from 2019-07-10 10-58-39](https://user-images.githubusercontent.com/32605614/60942969-2fe04600-a302-11e9-9757-b5cbbbc02d09.png)

**Comment by hemnathmouli** [comment]
This issue is related to this #15114

**Comment by ChiragRayani** [comment]
its working fine now
![Screenshot from 2019-07-10 11-32-26](https://user-images.githubusercontent.com/32605614/60944453-7f287580-a306-11e9-9b49-2433f0ce9a58.png)

but when i run flutter on intellij its showing like this
![Screenshot from 2019-07-10 11-32-37](https://user-images.githubusercontent.com/32605614/60944473-90718200-a306-11e9-8d62-34e960faa9f5.png)

**Comment by hemnathmouli** [comment]
Could you trying this in your terminal?

```
$ flutter config --android-sdk /path/to/android/sdk
$ flutter config --android-studio-dir /path/to/android/studio
```
