### ISSUE TITLE
How to disable SSL pinning in flutter app

### ISSUE THREAD

**Issue by pgfepale** [flutter/flutter#35852]
Hi,
I am using latest version of flutter(1.5) and dart(>2.0). I came across some  app security testing  and they are requesting to disable the SSL pinning in my app.

I research it but all solution leads to enable.

Can any one help me to disable it.

Thanks 
Prashant.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by mdmota** [comment]
I need to bypass SSL. Any solution?

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by MadhusudhanSahni** [comment]
Hi,
I am using the version of flutter(1.20.1). I came across the same issue the security team is requesting to disable the SSL pinning in my app. but I do not enable the SSL pinning. So how we can disable default SSL pinning from the flutter app. 
Here are the dependencies used in App -
`
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc_pattern: ^0.0.1+1
  provider: ^4.3.1
  flutter_spinkit: "^4.1.1"
  google_fonts: ^0.2.0
  flutter_echarts: ^1.3.5
  number_display: ^2.3.0
  charts_flutter: ^0.9.0
  horizontal_data_table: ^1.0.5+5
  search_widget: ^1.0.2
  lottie: ^0.5.1
  dio: ^3.0.10
  xml: ^3.5.0
  fluttertoast: ^7.0.2
  shared_preferences: ^0.5.8
  firebase_crashlytics: ^0.1.4+1
  carousel_slider: ^2.2.1
  expandable: ^4.1.4
  get_it: ^4.0.4
  rxdart: ^0.24.1
  flutter_secure_storage: ^3.3.3
  local_auth: ^0.6.1
  webview_flutter: ^0.3.24
  flutter_webview_plugin: ^0.3.11
  passcode_screen: ^1.2.0
  percent_indicator: ^2.1.7+4
  url_launcher: ^5.7.6
  firebase_messaging: ^7.0.3
`
And here are the Screenshot shared by the VAPT(Security) team.

![1](https://user-images.githubusercontent.com/32368287/114514875-6080ac80-9c59-11eb-9514-1d56c59ca412.jpeg)

Thanks

**Comment by AbdullahUsmani** [comment]
> Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v' please.
> All system setups can be slightly different so it's always better to open new issues and reference related issues.

This is not a system-specific issue but something in the APK build. The decompiled APK code shows SSL checks and the security team has asked to disable it.
