### ISSUE TITLE
Pause Webview when in background.

### ISSUE THREAD

**Issue by DhruvamSharma** [flutter/flutter#35865]
## Use case

I have added a webview plugin (official flutter plugin) for viewing webpages. One of the webpage has a youtube video playing and when I press the home button and the app goes into background. But the problem is that the sound keeps on playing. There are other sections in the application that contain some component playing sound or video.

So I want to know what can be done to pause the webview altogether once I move the app to background.

I am currently using this webview plugin: webview_flutter: ^0.3.9+1 
There is no option in the plugin to pause the webview itself.

**Comment by janmoppel** [comment]
Hello @DhruvamSharma !

Does the problem still persist in the latest version of the `webview_flutter`?

Thank you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by harikautilya** [comment]
Hello Flutter, i am currently facing this situation in the application i developed. Please let me know what information you need. I can help it out.
Thanks in advance

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
