### ISSUE TITLE
[firebase_messaging] Should support Rich notifications by default on iOS.

### ISSUE THREAD

**Issue by kaumudpa** [flutter/flutter#35866]
It still does not support Rich Notifications (Notifications with Image) on iOS, Anybody has workaround for this??? If not this would be a feature request.

**Comment by khainhero** [comment]
Perhaps, this can help you. I am planning to include this for my own project when I have time. So I can modify the notification before its displayed to the user.
https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension

more info here:
https://documentation.onesignal.com/docs/service-extensions#section-notificationextenderservice-span-class-label-all-label-android-android-span-

**Comment by kaumudpa** [comment]
We need a way to send Rich Notifications out of the box for ios for FCM. The current plugin supports FCM Rich messages for Android but not for iOS.

**Comment by zanecidan** [comment]
> We need a way to send Rich Notifications out of the box for ios for FCM. The current plugin supports FCM Rich messages for Android but not for iOS.

@kaumudpa I'm looking into this too. May I know how do you send Rich Notifications for Android using current plugin?

**Comment by kaumudpa** [comment]
I will give you a small and simple example.

Without any additional efforts in the project Rich Notifications i.e. Notifications with Image can be sent to an android device. But Rich Notifications cannot be sent to the iOS Devices on the current plugin.

I have tried using Notification extension in the ios project but it created problems with the plugin. This should be an Out of the box feature for the plugin.

I am attaching screenshots of ios and android for the same notification which was sent using the following :
```
{
   "to": "Your FCM Device Token",
   "content_available": true,
   "mutable_content": true,
   "notification":
   {
              "title": "Testing Rich FCM",
              "body": "Testing FCM With images",
              "sound": "default",
              "image": "https://cdn.pixabay.com/photo/2018/01/21/01/46/architecture-3095716_960_720.jpg"
            }
}
```
![Screenshot_20190813-164806](https://user-images.githubusercontent.com/13520180/62937599-ba790100-bdea-11e9-8ef2-25f2eb440a1e.png)
![Image from iOS (4)](https://user-images.githubusercontent.com/13520180/62937674-f44a0780-bdea-11e9-9562-a2ccb183ec05.png)

**Comment by zanecidan** [comment]
@kaumudpa Thank you very much.

**Comment by janmoppel** [comment]
Hello @kaumudpa !

Does the problem still persist in the latest plugin version?

**Comment by kaumudpa** [comment]
Yes it does.

**Comment by kroikie** [comment]
@kaumudpa

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/357. Any further collaboration will be done there.

**Comment by binhnt13682104** [comment]
Maybe my answers can help  somebody: https://github.com/FirebaseExtended/flutterfire/issues/357#issuecomment-638918216
