### ISSUE TITLE
Could not parse callback cache, aborting restore

### ISSUE THREAD

**Issue by lzkkk** [flutter/flutter#35863]
today, i upgrade my flutter to  stable 1.7.8, then i cant run my application in a normal way.
and i probably find reason what is i use "[[FlutterEngine alloc] initWithName:engineName project:nil]"

[VERBOSE-1:callback_cache.cc(132)] Could not parse callback cache, aborting restore

 Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.3 at /Applications/flutter
    • Framework revision b712a172f9 (14 hours ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/wangliping/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.0.beta.1

**Comment by pgte** [comment]
@lzkkk same thing happening to me. Did you find a fix?

**Comment by iharshb** [comment]
Having same problem while running on iOS simulator. It runs proper on Android.

**[VERBOSE-1:callback_cache.cc(132)] Could not parse callback cache, aborting restore**


[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.1 at /Users/harshbhavsar/flutter
    • Framework revision f7a6a7906b (9 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/harshbhavsar/Library/Android/sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

**Comment by masanggil1986** [comment]
same here

**Comment by jpmehedi** [comment]
I am facing same problem while running on iOS simulator. It runs proper on Android.

Running pod install...                                             10.6s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        27.1s
Xcode build done.                                           110.8s
[VERBOSE0:callback_cache.cc(133)] Could not parse callback cache, aborting restore
[VERBOSE0:callback_cache.cc(133)] Could not parse callback cache, aborting restore
