### ISSUE TITLE
Unable to `flutter upgrade` if flutter repo isn't on master branch

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3586]
Here's the output from a recent run of `flutter upgrade`:

```
~/flutter/awesomesauce $ flutter upgrade
Downloading Dart SDK 1.16.0-dev.5.5...
######################################################################## 100.0%
Building flutter tool...
The Flutter tool anonymously reports feature usage statistics and basic crash reports to Google to
help Google contribute improvements to Flutter over time. Use "flutter config" to control this
behavior. See Google's privacy policy: https://www.google.com/intl/en/policies/privacy/

Downloading engine package sky_engine...             0.8s
Downloading engine package sky_services...           0.3s
Downloading engine artifacts android-arm...          4.4s
Downloading engine artifacts android-arm-release...  4.4s
Downloading engine artifacts android-x64...          2.7s
Downloading engine artifacts ios...                  3.4s
Downloading engine tools darwin-x64...               0.8s
fatal: no upstream configured for branch 'doc-import-statements'
Unable to upgrade Flutter: no upstream repository configured.
```

Note that I see "fatal: no upstream configured for branch 'doc-import-statements'
Unable to upgrade Flutter: no upstream repository configured."

This is probably rare, but would it make sense to say something like "Sorry, cannot complete the upgrade. Your flutter repository is not on the master or alpha branch. Please cd to [insert location of flutter checkout] and change to master (unstable, changing frequently) or alpha (less unstable :)."

**Comment by eseidelGoogle** [comment]
We only have master now.  I think we can close this and re-open later if needed.

**Comment by viveky259259** [comment]
You can restore peace and justice by doing something like:

cd MY_FLUTTER_PATH
git checkout master

Or if that fails:

git checkout -b master upstream/master
