### ISSUE TITLE
[webview_flutter] Input needs to be tapped twice to be registered on Samsung devices

### ISSUE THREAD

**Issue by luckmlc** [flutter/flutter#35867]
*Edit by @mklim: [Comment-511798199](https://github.com/flutter/flutter/issues/35867#issuecomment-511798199) found the Samsung issue. The first few comments in the chain refer to earlier versions of Flutter without any keyboard support at all. Quoting the relevant comment below.*

> Maybe Samsung mobile phones have this problem，I tried two Samsung phones.
> samsung galaxy s6 edge+
> samsung galaxy S7（G9300)
> 
> The problem may be that it won't get the focus for the first time , you need to click the input box again.
> 
> Please see the gif below：
> 
> ![gifhome_320x564_15s](https://user-images.githubusercontent.com/48781697/61291679-c11f5300-a801-11e9-8a4e-edfe920cbf69.gif)
> 
> flutter: Channel master, v1.8.2-pre.42
> webview_flutter: ^0.3.10+2
> 
> My environment is as follows:
> 
> ```
> /Users/mayer/development/flutter/bin/flutter doctor --verbose
> [✓] Flutter (Channel master, v1.8.2-pre.42, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
>     • Flutter version 1.8.2-pre.42 at /Users/mayer/development/flutter
>     • Framework revision 35b07a1f7f (8 hours ago), 2019-07-15 23:43:27 -0400
>     • Engine revision 74af88ba9f
>     • Dart version 2.5.0 (build 2.5.0-dev.1.0 24725a8559)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/mayer/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.2.1, Build version 10E1001
>     • CocoaPods version 1.6.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 3.4)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 37.0.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [✓] Connected device (3 available)
>     • SM G9280 • 0815f8acd00f1b04 • android-arm64  • Android 7.0 (API 24)
>     • macOS    • macOS            • darwin-x64     • Mac OS X 10.14.4 18E226
>     • Chrome   • chrome           • web-javascript • Google Chrome 75.0.3770.142 
> 
> 
> • No issues found!
> Process finished with exit code 0
> ```

Run the example in the webview_flutter plugin.
When I typed on the pop-up keyboard, the text I entered was not displayed.

Please see the gif below：

![image](https://raw.githubusercontent.com/luckmlc/php_test/master/noinput_320x564_5s.gif)

flutter  1.7.8
webview_flutter 0.3.9+1

My environment is as follows:

```
/Users/mayer/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.3 at /Users/mayer/development/flutter
    • Framework revision b712a172f9 (15 hours ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mayer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • SM G9280 • 0815f8acd00f1b04 • android-arm64 • Android 7.0 (API 24)

• No issues found!
Process finished with exit code 0
```

**Comment by jyp334** [comment]
I have same question.This problem arises  because I need to new a webview to open new window for logining facebook.My flutter version is 1.7.11.

**Comment by kangwang1988** [comment]
@jyp334 @luckmlc 
Have you tried the latest master branch for flutter & webview_flutter.
It works fine using the latest master branch.
![Untitled](https://user-images.githubusercontent.com/817851/61223394-1e0e0100-a74f-11e9-8321-80d7bbe98c27.jpg)

flutter doctor -v 
```shell
(base) kylewong@KyleWongs-MacBook-Pro example % flutter doctor -v
[!] Flutter (Channel master, v1.8.2-pre.33, on Mac OS X 10.15 19A501i, locale en-CN)
    • Flutter version 1.8.2-pre.33 at /Users/kylewong/Codes/Flutter/flutter
    • Framework revision e3ee5c6bbb (2 days ago), 2019-07-13 16:02:09 -0700
    • Engine revision 919e353236
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 24725a8559)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/kylewong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.0, Build version 11M337n
    • CocoaPods version 1.7.3

[!] iOS tools - develop for iOS devices
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (3 available)
    • PBCT10 • 80790da • android-arm64  • Android 8.1.0 (API 27)
```
git@github.com:flutter/plugins.git is at commit: 518c8f03c0018af0c5dbacfab336c82abc82d5f6

**Comment by luckmlc** [comment]
@kangwang1988  

I switched the Master version and the text entered still doesn't display.

```
/Users/mayer/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel master, v1.8.2-pre.41, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.8.2-pre.41 at /Users/mayer/development/flutter
    • Framework revision 2d08fec368 (2 hours ago), 2019-07-15 18:31:44 -0700
    • Engine revision 3f27c5724c
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 24725a8559)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mayer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
```

**Comment by kangwang1988** [comment]
@luckmlc 
Please make sure that both flutter&webview_flutter is at the latest master.
Besides, please check if it occurs on specific android device or every android devices you can get.
It might be device related.

**Comment by luckmlc** [comment]
@kangwang1988 

Maybe Samsung mobile phones have this problem，I tried two Samsung phones.
samsung galaxy s6 edge+
samsung galaxy S7（G9300)

The problem may be that it won't get the focus for the first time , you need to click the input box again.

 Please see the gif below：

![gifhome_320x564_15s](https://user-images.githubusercontent.com/48781697/61291679-c11f5300-a801-11e9-8a4e-edfe920cbf69.gif)

flutter: Channel master, v1.8.2-pre.42
webview_flutter: ^0.3.10+2

My environment is as follows:

```
/Users/mayer/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel master, v1.8.2-pre.42, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.8.2-pre.42 at /Users/mayer/development/flutter
    • Framework revision 35b07a1f7f (8 hours ago), 2019-07-15 23:43:27 -0400
    • Engine revision 74af88ba9f
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 24725a8559)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mayer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (3 available)
    • SM G9280 • 0815f8acd00f1b04 • android-arm64  • Android 7.0 (API 24)
    • macOS    • macOS            • darwin-x64     • Mac OS X 10.14.4 18E226
    • Chrome   • chrome           • web-javascript • Google Chrome 75.0.3770.142 


• No issues found!
Process finished with exit code 0
```

**Comment by luckmlc** [comment]
> @luckmlc
> Please make sure that both flutter&webview_flutter is at the latest master.
> Besides, please check if it occurs on specific android device or every android devices you can get.
> It might be device related.

Samsung mobile phones have this problem，huawei  and meitu phones is ok!

**Comment by jyp334** [comment]
@kangwang1988  Hi , I just want to create a new window to complete the login function of facebook . My flutter version is 1.7.11 dev , This is my code to create a new window,In this new webview, the pop-up box is unable to pop up or cannot enter characters after it pops up.
''
@Override
        public boolean onCreateWindow(WebView view, boolean isDialog,
                                      boolean isUserGesture, Message resultMsg) {
            Log.d(TAG, "onCreateWindow");
            mWebviewPop = new WebView(mContext);
            mWebviewPop.setVerticalScrollBarEnabled(false);
            mWebviewPop.setWebChromeClient(this);
            mWebviewPop.setWebViewClient(new FacebookWebviewClient());
            WebSettings settings = mWebviewPop.getSettings();
            settings.setDomStorageEnabled(true);
            settings.setJavaScriptEnabled(true);
            settings.setSupportMultipleWindows(true);
            settings.setJavaScriptCanOpenWindowsAutomatically(true);
            mWebviewPop.setFocusable(true);
            mWebviewPop.requestFocus(View.FOCUS_DOWN);
            mWebviewPop.requestFocusFromTouch();
            mWebviewPop.setLayoutParams(new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT));
            webView.addView(mWebviewPop);
            CookieManager cookieManager = CookieManager.getInstance();
            cookieManager.setAcceptCookie(true);
            WebView.WebViewTransport transport = (WebView.WebViewTransport) resultMsg.obj;
            transport.setWebView(mWebviewPop);
            resultMsg.sendToTarget();
            return true;
        }
''
I hope to improve the Webview_flutter plugin as soon as possible .Or if you have a good way to solve the multi-window problem in webview, you can give me some Suggestions.

**Comment by kangwang1988** [comment]
@jyp334 
Please provide a self-contained flutter demo project so I can do some digging.

**Comment by kangwang1988** [comment]
@luckmlc 
Gotcha.
I will do some checking with samsung device.

**Comment by mklim** [comment]
I can reproduce the issue with a Galaxy S6 and the latest version of Flutter and the plugin.

I haven't investigated in detail yet, but this looks exactly like the previous failure from when lock and unlocking were needed but not added yet. /cc @amirh

**Comment by mklim** [comment]
@amirh and I looked into this a little offline.

The problem appears to be [where we restart the input connection on unlock](https://github.com/flutter/plugins/blob/400a775/packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/InputAwareWebView.java#L50-L53). On Samsung devices this resets the `InputConnection` to null instead of restarting it and getting the previous good connection like on non Samsung devices. Deleting the code block "fixes" the issue completely. However that restart is there to prevent another issue on non-Samsung devices where `ViewRootImpl` cancels text events with a noisy`Cancelling event due to no window focus` log.

We don't have a good idea for a fix yet. Working theory is that hopefully we can figure out some other way to correctly set `ViewRootImpl`'s state so it doesn't try to drop these events on non Samsung devices, and then we can get rid of the restart.

**Comment by mklim** [comment]
Investigated this more today. So far I've been unable to find any state that differs between Samsung and non Samsung devices here, or any alternative ways to correctly set the window state in non Samsung devices.

The flow goes like this:

1. User taps into any text field.
2. `InputAwareWebView#onCreateInputConnection` -> returns good inputConnection
3. `IAWV#lockInputConnection()`
4. `IAWV#unlockInputConnection()` calls `InputMethodManager.restartInput(IAWV#containerView)`
5. `IAWV#onCreateInputConnection`. This returns `null` on Samsung, but the same original good input connection as `2` everywhere else.

At no point in any of these steps is there an obvious difference between Samsung and other phones' focus, windowFocus, rootView#focus, rootView#windowFocus, or any of the IMM getters. 

I think I may be able to hack around this and put in some logic like "if we've just restarted and we're about to return null from `onCreateInputConnection`, that means we're in this obscure bug condition so return this last non-null thing that we've cached instead". But that's brittle and I'm wary of adding something extra like that on here without getting to the bottom of it.

**Comment by zhhal** [comment]
I have the same problem on huawei and MI devices only when I use Baidu input method, other input method works well.

**Comment by pedrosalesmiranda** [comment]
Same issue here but **not just Samsung** devices also **MI**
Connected device (1 available)
    • Redmi Note 4 • 5TFAFYWGS475VKHQ • android-arm64 • Android 6.0 (API 23)
webview_flutter: 0.3.11

**Comment by pedrosalesmiranda** [comment]
Similar issue on Samsung device. But first at first tap input gets focus but keyboard does not show up. On second tap keyboard shows up and input is displayed.

 Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /home/psm/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /home/psm/Installs/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/psm/Installs/android-studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /home/psm/Installs/idea-IU-191.7479.19
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • SM G950F • 988a5733564c304e4d • android-arm64 • Android 9 (API 28)

**Comment by pedrosalesmiranda** [comment]
@mklim tried webview_flutter on 
• Redmi Note 4 • 5TFAFYWGS475VKHQ • android-arm64 • Android 6.0 (API 23)
webview_flutter: 0.3.11+2

issues is not solved. Nothing changed.

**Comment by mklim** [comment]
@pedrosalesmiranda thanks for the report. Just to be clear, are you still seeing needing to tap twice for the soft keyboard to appear specifically? The keyboard not dismissing itself after unfocusing a text field is a different issue still open at flutter/flutter#36478. Unfortunately I don't have that specific device to test with myself at the moment.

**Comment by pedrosalesmiranda** [comment]
@mklim you are welcome. I only tested 0.3.11+2 in MI device and in this case the issue was:
first tap:
keyboard shows up and text field gets focus. But no input.
second tap:
keyboard still present and text field with focus (all apparently the same). But input is displayed now in text field.

This device is what I have with me all the time. Do you want some kind of special logs or some video of the bug happening or something that I can help you hunt the bug? We have a project that cant move forward while this happens. Actually we tested with webview on androind wihtout flutter and it worked. So might be a solution for us. But I really wanted to go on with flutter.

**Comment by pedrosalesmiranda** [comment]
just tested on new version 0.3.13 still same issue not working with first tap. Should I open a new issue for this?

**Comment by mklim** [comment]
@pedrosalesmiranda yeah, I think a new issues makes sense. I think whatever is happening here is probably specific to the Mi device. Filed #39451. 

If you see this reproing on any other devices or Android versions, that would be really helpful to know too.
