### ISSUE TITLE
[web]:Flutter For Web TextFiled Keyboard not show in iPhone

### ISSUE THREAD

**Issue by wedcel** [flutter/flutter#35875]
There is an textfield in my flutter for web application. This textfield is no problem on Android, but on the iPhone, the keyboard does not appear. You need to click 5 to 8 times in the textfield to pop up the keyboard. What is the problem with this?
I look at the official sample, the input of textfield will be enlarged first to pop up the keyboard. Is there any problem here?

### show my code:

 main.dart
     
    void main() => runApp(MyApp());

      class MyApp extends StatelessWidget {
       // This widget is the root of your application.
       @override
       Widget build(BuildContext context) {
      print("init");
      return MaterialApp(
      title: 'Flutter Demo',
    
      home: EditableTextDemo(
      ),
    );
      }
    }

EditableTextDemo.dart（this file is copy from the sample）:

 
      import 'package:flutter_web/material.dart';

      class EditableTextDemo extends StatefulWidget {
       static String routeName = '/material/editable_text';

     @override
     State<StatefulWidget> createState() => EditableTextDemoState();
       }

    class EditableTextDemoState extends State<EditableTextDemo> {
      final cyanController = TextEditingController(text: 'Cyan');
      final orangeController = TextEditingController(text: 'Orange');
      final thickController = TextEditingController(text: 'Thick Rounded Cursor');
      final multiController =
          TextEditingController(text: 'First line\nSecond line');
 
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(
            title: Text('Text Editing'),
            centerTitle: true,
          ),
          body: ListView(
            children: [
              field(
                cyanController,
                color: Colors.cyan.shade50,
                selection: Colors.cyan.shade200,
                cursor: Colors.cyan.shade900,
              ),
              field(
                orangeController,
                color: Colors.orange.shade50,
                selection: Colors.orange.shade200,
               cursor: Colors.orange.shade900,
               center: true,
              ),
          field(
            thickController,
            color: Colors.white,
            selection: Colors.grey.shade200,
            cursor: Colors.red.shade900,
            radius: const Radius.circular(2),
            cursorWidth: 8,
          ),
          Banner(
            child: TextField(
              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20),
              controller: multiController,
              maxLines: 3,
            ),
            message: 'W.I.P',
            textDirection: TextDirection.ltr,
            location: BannerLocation.bottomEnd,
          ),
        ],
      ),
    );
      }
    }

    Widget field(
      TextEditingController controller, {
      Color color,
      Color selection,
      Color cursor,
      Radius radius ,
      double cursorWidth = 2,
      bool center = false,
    }) {
      return Theme(
        data: ThemeData(textSelectionColor: selection),
        child: Container(
          color: color,
          child: TextField(
            textAlign: center ? TextAlign.center : TextAlign.start,
            decoration: InputDecoration(
              contentPadding: EdgeInsets.fromLTRB(8, 16, 8, 16),
            ),
            controller: controller,
            cursorColor: cursor,
           cursorRadius: radius,
           cursorWidth: cursorWidth,
      ),
    ),
      );
        }

**Comment by ferhatb** [comment]
Fixed via https://github.com/flutter/flutter_web/commit/a0c8c29846ddce53f5835b86090f7c074d6a64e4
