### ISSUE TITLE
Error consuming purchase: Response code 5

### ISSUE THREAD

**Issue by RobertBrunhage** [flutter/flutter#35872]
## Problem

When trying to purchase a subscription product I get the following message `Error consuming purchase with token. Response code: 5`.

This is run from the version of the app that is on play store internal testing. and I found the error message with the following `adb shell "logcat --pid=$(pidof -s com.example.app)"`. 

So it seems like it's not consuming my purchase correctly.

## Steps to Reproduce

1. I used the same code as the `In_app_purchase` plugin
2. Upload the app with flutter stable
3. Connect the device to a computer and the command above to get the logs
4. Make the purchase

**Comment by janmoppel** [comment]
Hello @RobertBrunhage !

Did you manage to solve the issue? Does the problem still exist in the latest stable version?

**Comment by RobertBrunhage** [comment]
Not really, found revenueCat and used that instead.

So haven't tested with latest stable

**Comment by TahaTesser** [comment]
Hi @RobertBrunhage 
if you're still experiencing this problem with latest stable, please create a new issue and provide the information required in the template.
Thank you
