### ISSUE TITLE
Black margin on top and bottom of app (iOS)

### ISSUE THREAD

**Issue by Pyozer** [flutter/flutter#35879]
Hi !

We published an app, and one of our users report us a strange display bug on his iPhone.
I don't know exactly the model by it seem to be an iPhone 8 (screenshot provided is 750x1334).

<img src="https://i.ibb.co/CwCGXKd/1-1.png" height="400" />

The bug is that there is some strange black margins on top and bottom of the app.
Also, on the screenshot we can see that the statusbar is on top of the app and not of the phone, so I think the bug is not from the app but the phone, but i'm not sure about that...

I create this issue because I don't know the origin, is it the app, a bug of Flutter or a setting on the user's iPhone..

I haven't any logs, and I was not able to reproduce this.

Is anyone has an idea ?

Thank you !

**Comment by justinmc** [comment]
CC @xster Have you ever seen black bars like this?

**Comment by xster** [comment]
I have not. Could this be an airplay issue? (since the OS status bar is not where it's expected)

**Comment by justinmc** [comment]
Yeah maybe that's it...  @Pyozer Is this app on the app store?  Would you mind telling me the name so that I can try it out on my phone?  I've got an iPhone7 but it could be worth a try.

**Comment by Pyozer** [comment]
Yeah that could be this..

The app is Affluences, you can find it here :
https://apps.apple.com/fr/app/affluences/id869919405

Thank you for your help !

**Comment by justinmc** [comment]
I played around with it and couldn't see what would cause those black bars.  I'll keep an eye out for anything similar and post back here if I have more info.

Well made app by the way!

**Comment by Pyozer** [comment]
Thank you !

**Comment by TheChileanKink** [comment]
Hello! Where you able to fix this? I'm having the same issue...

**Comment by justinmc** [comment]
I have not heard of this happening anywhere else.  @TheChileanKink Do you have any idea what could be causing it or how I could reproduce it?

**Comment by TheChileanKink** [comment]
It happened to me and I just cleant the build and re ran it. Don't know what caused it...

**Comment by ruiq** [comment]
check your LaunchImage.

**Comment by socialglass** [comment]
I am getting this error too. What was the outcome of this?

**Comment by Blasanka** [comment]
This happen to me on Iphone 6 yesterday. May be the reason is I had Ionic app and updated it on App Store with new Flutter app. But few of our devices updated correctly. Only on one Iphone 6 device happen like below screenshot:

![2019-12-04](https://user-images.githubusercontent.com/7420109/70206095-6ce32400-174c-11ea-8661-a184c1dc397c.jpeg)

**Comment by TahaTesser** [comment]
Hi @Pyozer 
Are you still experiencing this issue?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions
what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference
related issues.
Thank you
