### ISSUE TITLE
Flutter 1.7.8+hotfix breaks image_picker/image_picker_saver 

### ISSUE THREAD

**Issue by bhurlbert** [flutter/flutter#35876]
The Flutter update 1.7.8+hotfix breaks **image_picker_saver** lib and does not allow the '_future_' to resolve when _getting images from the camera or gallery_, so the app just shows a black container where the normal container would return after the future is resolved.
```dart

class CameraPageRoute extends MaterialPageRoute {
  CameraPageRoute() : super(builder: (context) => new CameraPage());
}

class CameraPage extends StatefulWidget {
  @override
  _CameraPage createState() => _CameraPage();
}

class _CameraPage extends State<CameraPage> {
  bool _gettingImage = true;
  File _image;

  Future getImage() async {
    var image = await ImagePickerSaver.pickImage(
        maxHeight: 1200, maxWidth: 800, source: ImageSource.camera);

    setState(() {
      _image = image;
      _gettingImage = false;
    });
  }

  @override
  void initState() {
    super.initState();
    getImage();
  }

  @override
  void dispose() {
    _image = null;
    super.dispose();
    _image = _gettingImage = null;
  }


```

**Comment by janmoppel** [comment]
Hello @bhurlbert !

Does the problem still exist in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
