### ISSUE TITLE
I have problem with Utf8Decoder after upgrade to flutter version 1.8.1-pre.56 

### ISSUE THREAD

**Issue by mohamedMesalm** [flutter/flutter#35884]
Compiler message:
file:///Users/mohamedmesalm/development/flutter/.pub-cache/hosted/pub.dartlang.org/geocoder-0.1.2/lib/services/distant_google.dart:38:56: Error: The argument type 'Utf8Decoder' can't be assigned to the parameter type 'StreamTransformer<Uint8List, dynamic>'.
 - 'Utf8Decoder' is from 'dart:convert'.
 - 'StreamTransformer' is from 'dart:async'.
 - 'Uint8List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'StreamTransformer<Uint8List, dynamic>'.
    final responseBody = await response.transform(utf8.decoder).join();
                                                       ^
Compiler failed on /Users/mohamedmesalm/Desktop/chatapp/lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '/Users/mohamedmesalm/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 652

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugArm'.
> Process 'command '/Users/mohamedmesalm/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by stuartmorgan** [comment]
The package will need to be updated; this is due to https://groups.google.com/forum/#!topic/flutter-announce/LTe4SYU8-0Q

It looks like someone has already filed https://github.com/aloisdeniel/flutter_geocoder/issues/23 against the package.

**Comment by mohamedMesalm** [comment]
resolved by replace this line code 
`final response = await request.close().`
to 
`  response.cast<List<int>>().transform(utf8.decoder).listen((content) {
        return content;
      });
    });`

inside =>> file:///Users/mohamedmesalm/development/flutter/.pub-cache/hosted/pub.dartlang.org/geocoder-0.1.2/lib/services/distant_google.dart

and all things works fine .

**Comment by siyasangab** [comment]
This worked for me, thanks @mohamedMesalm

**Comment by PreritO** [comment]
Thank you @mohamedMesalm
