### ISSUE TITLE
Google_sign_in errors.

### ISSUE THREAD

**Issue by lt692** [flutter/flutter#35881]
Given example for google_sign_in gives alot of errors.

+ App registered on firebase
+ SHA1 and SHA256 of androiddebug also provided. Also tried to delete and repaste new keys still nothing. 
+ google json file also inside project. everything is uploaded as needed.
 tried both on stock and on androidX versions and same errors.

![image](https://user-images.githubusercontent.com/48758376/60978761-4efaca00-a33a-11e9-9751-f0036e41d337.png)

![image](https://user-images.githubusercontent.com/48758376/60978803-5e7a1300-a33a-11e9-9677-6a7f24508ed3.png)

![image](https://user-images.githubusercontent.com/48758376/60978868-73ef3d00-a33a-11e9-8224-03e1b279c9bc.png)

![image](https://user-images.githubusercontent.com/48758376/60978926-85d0e000-a33a-11e9-8890-35add3573209.png)

![image](https://user-images.githubusercontent.com/48758376/60978954-908b7500-a33a-11e9-9804-e4b9a9d4a4ff.png)

![image](https://user-images.githubusercontent.com/48758376/60979000-a00abe00-a33a-11e9-9cd1-ded60ab27a40.png)

![image](https://user-images.githubusercontent.com/48758376/60979014-a8fb8f80-a33a-11e9-8963-b528b0cbb478.png)

![image](https://user-images.githubusercontent.com/48758376/60979037-b3b62480-a33a-11e9-9597-fa2d827ac603.png)

**Comment by kalismeras61** [comment]
Same issue with me!

**Comment by kalismeras61** [comment]
If you find any solution please respond this message.

**Comment by kalismeras61** [comment]
Solution is here. It is working for me : https://github.com/flutter/flutter/issues/33393?fbclid=IwAR3o3OOYqMzPHhb0fbornoWMnDO0zUV-8hYLa8dINddLw4w8lc-0huxrgdQ#issuecomment-510395178

**Comment by lt692** [comment]
> 
> 
> Solution is here. It is working for me : #33393

Ok i will try it out soon :)

**Comment by janmoppel** [comment]
Hello @lt692 !

Have you tried the solution pointed out by @kalismeras61 ? Did it work for you?

Thank you.

**Comment by lt692** [comment]
> Hello @lt692 !
> 
> Have you tried the solution pointed out by @kalismeras61 ? Did it work for you?
> 
> Thank you.

Itried and sadly no it did nothing. I still get the same error.

**Comment by lt692** [comment]
> Hello @lt692 !
> 
> Have you tried the solution pointed out by @kalismeras61 ? Did it work for you?
> 
> Thank you.
I have managed to make it work! And yes the consent solution is the KEY. 💃
