### ISSUE TITLE
Embedders are directly calling methods on the engine instead of the shell

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#35889]
The Android, iOS, and Embedder API all directly make calls on the Engine instead of the shell for `SetViewportMetrics` and `DispatchPointerDataPacket`.

In fact, they all use very similar code that looks to be copy-pasted from shell.cc:

https://github.com/flutter/engine/tree/6cf0d1350e0ac03df9ebcbb15c35a4a035010460/shell/platform/embedder/embedder_engine.cc#L82-L115

https://github.com/flutter/engine/blob/6cf0d1350e0ac03df9ebcbb15c35a4a035010460/shell/platform/android/android_shell_holder.cc#L175-L207

https://github.com/flutter/engine/blob/6cf0d1350e0ac03df9ebcbb15c35a4a035010460/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm#L128-L147

We should refactor all of these to use the same path through shell.cc, and ideally make it impossible for embedders to call these methods directly on the engine (which I believe would be breaking).

/cc @chinmaygarde @cbracken @jason-simmons

**Comment by chinmaygarde** [comment]
> which I believe would be breaking

All those APIs are internal and we control those embedders. So there shouldn't be any breaking changes to the public embedding API. Lets refactor these today.

**Comment by chinmaygarde** [comment]
Maybe not even allow vending weak pointer for the engine subcomponents from the shell.

**Comment by dnfield** [comment]
Wouldn't that be a breaking change?

**Comment by chinmaygarde** [comment]
The Shell API is not vended directly by anyone (any embedding API I mean).

**Comment by dnfield** [comment]
Going to open a separate bug for Fuchsia, since flutter_runner uses this in some strange ways the other embeddings don't.
