### ISSUE TITLE
Hot reload fails to start: Stuck at 'syncing files to device ... (This is taking an unexpectedly long time.)...'

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#35885]
Mirror bug for https://buganizer.corp.google.com/issues/135765242 --- conversation should occur there.

cc @dnfield @keertip (who is OoO)

**Comment by kf6gpe** [comment]
cc @jonahwilliams, who is mentioned on the internal issue. Jonah, should you assign this to yourself, or delegate to someone else on the team?

**Comment by jonahwilliams** [comment]
I can assign it to myself but I'm still blocked, gave an update on the issue

**Comment by kf6gpe** [comment]
@blasten, are you looking at Fuchsia issues this quarter? Any chance you could take a look at this? The Fuchsia folks would like to resolve this sooner as opposed to later. Bumping the priority accordingly. Thanks!

**Comment by blasten** [comment]
Sounds good. I will take look.

**Comment by Hixie** [comment]
cc @zanderso

**Comment by blasten** [comment]
I followed up on the master bug.

**Comment by tomasbaran** [comment]
This may be related to this: https://github.com/flutter/flutter/issues/54876

**Comment by kf6gpe** [comment]
Upstream issue closed as obsolete; this functionality is now working correctly.
