### ISSUE TITLE
Unable to test apps on AVD - x86 

### ISSUE THREAD

**Issue by d-apps** [flutter/flutter#35898]
My laptop is weak to emulate x64 or latest android versions (6.0 - 9.0), so before flutter, I programmed in native and I always tested my apps in Nexus 4 or Galaxy Nexus with API 19 (Android 4.4) and the emulators worked fine for native apps, once I started with Flutter ( since 1.0) emulators doesn't work correctly (Only for Flutter apps). I always get this error: "**Unfortunately app_name has stopped.**"

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.

Installing build\app\outputs\apk\app.apk..
```

**My emulators configuration:**
![1](https://user-images.githubusercontent.com/20110433/60998638-b5c6b600-a32f-11e9-9bdb-251d1b29a884.JPG)
![2](https://user-images.githubusercontent.com/20110433/60998639-b5c6b600-a32f-11e9-9ebc-420fa3376b16.JPG)

`

So I tried to use other android versions, tried with 5.0, and I get the error; 

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Running Gradle task 'assembleDebug'...

Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
**Package install error: Failure [INSTALL_FAILED_DEXOPT]
Error launching application on Android SDK built for x86.**
```

**Flutter doctor**

```
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [versÃ£o 10.0.18362.239], locale pt-BR)
    • Flutter version 1.7.8+hotfix.3 at C:\src\flutter
    • Framework revision b712a172f9 (23 hours ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Dih\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 4.4.2 (API 19) (emulator)

• No issues found!
```

My laptop:
![3](https://user-images.githubusercontent.com/20110433/60999168-df341180-a330-11e9-809b-1dbd60c06a8a.JPG)

**Comment by saravananmnm** [comment]
> My laptop is weak to emulate x64 or latest android versions (6.0 - 9.0), so before flutter, I programmed in native and I always tested my apps in Nexus 4 or Galaxy Nexus with API 19 (Android 4.4) and the emulators worked fine for native apps, once I started with Flutter ( since 1.0) emulators doesn't work correctly (Only for Flutter apps). I always get this error: "**Unfortunately app_name has stopped.**"
> 
> ```
> Launching lib\main.dart on Android SDK built for x86 in debug mode...
> Initializing gradle...
> Resolving dependencies...
> Running Gradle task 'assembleDebug'...
> Built build\app\outputs\apk\debug\app-debug.apk.
> WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
> 
> Installing build\app\outputs\apk\app.apk..
> ```
> 
> **My emulators configuration:**
> ![1](https://user-images.githubusercontent.com/20110433/60998638-b5c6b600-a32f-11e9-9bdb-251d1b29a884.JPG)
> ![2](https://user-images.githubusercontent.com/20110433/60998639-b5c6b600-a32f-11e9-9ebc-420fa3376b16.JPG)
> 
> `
> 
> So I tried to use other android versions, tried with 5.0, and I get the error;
> 
> ```
> Launching lib\main.dart on Android SDK built for x86 in debug mode...
> Initializing gradle...
> Running Gradle task 'assembleDebug'...
> 
> Built build\app\outputs\apk\debug\app-debug.apk.
> Installing build\app\outputs\apk\app.apk...
> **Package install error: Failure [INSTALL_FAILED_DEXOPT]
> Error launching application on Android SDK built for x86.**
> ```
> 
> **Flutter doctor**
> 
> ```
> [√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [versÃ£o 10.0.18362.239], locale pt-BR)
>     • Flutter version 1.7.8+hotfix.3 at C:\src\flutter
>     • Framework revision b712a172f9 (23 hours ago), 2019-07-09 13:14:38 -0700
>     • Engine revision 54ad777fd2
>     • Dart version 2.4.0
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
>     • Android SDK at C:\Users\Dih\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.0
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.4)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 37.0.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [√] Connected device (1 available)
>     • Android SDK built for x86 • emulator-5554 • android-x86 • Android 4.4.2 (API 19) (emulator)
> 
> • No issues found!
> ```
> 
> My laptop:
> ![3](https://user-images.githubusercontent.com/20110433/60999168-df341180-a330-11e9-809b-1dbd60c06a8a.JPG)

plz try this lines

 defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        ndk {
            abiFilters "armeabi-v7a", "x86_64", "armeabi", "mips"
           // abiFilters "arm64-v8a", "armeabi-v7a","armeabi", "mips", "x86"
        }
        applicationId "com.example.tvs_visibility"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

**Comment by d-apps** [comment]
> > My laptop is weak to emulate x64 or latest android versions (6.0 - 9.0), so before flutter, I programmed in native and I always tested my apps in Nexus 4 or Galaxy Nexus with API 19 (Android 4.4) and the emulators worked fine for native apps, once I started with Flutter ( since 1.0) emulators doesn't work correctly (Only for Flutter apps). I always get this error: "**Unfortunately app_name has stopped.**"
> > ```
> > Launching lib\main.dart on Android SDK built for x86 in debug mode...
> > Initializing gradle...
> > Resolving dependencies...
> > Running Gradle task 'assembleDebug'...
> > Built build\app\outputs\apk\debug\app-debug.apk.
> > WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
> > 
> > Installing build\app\outputs\apk\app.apk..
> > ```
> > 
> > 
> > **My emulators configuration:**
> > ![1](https://user-images.githubusercontent.com/20110433/60998638-b5c6b600-a32f-11e9-9bdb-251d1b29a884.JPG)
> > ![2](https://user-images.githubusercontent.com/20110433/60998639-b5c6b600-a32f-11e9-9ebc-420fa3376b16.JPG)
> > `
> > So I tried to use other android versions, tried with 5.0, and I get the error;
> > ```
> > Launching lib\main.dart on Android SDK built for x86 in debug mode...
> > Initializing gradle...
> > Running Gradle task 'assembleDebug'...
> > 
> > Built build\app\outputs\apk\debug\app-debug.apk.
> > Installing build\app\outputs\apk\app.apk...
> > **Package install error: Failure [INSTALL_FAILED_DEXOPT]
> > Error launching application on Android SDK built for x86.**
> > ```
> > 
> > 
> > **Flutter doctor**
> > ```
> > [√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [versÃ£o 10.0.18362.239], locale pt-BR)
> >     • Flutter version 1.7.8+hotfix.3 at C:\src\flutter
> >     • Framework revision b712a172f9 (23 hours ago), 2019-07-09 13:14:38 -0700
> >     • Engine revision 54ad777fd2
> >     • Dart version 2.4.0
> > 
> > 
> > [√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
> >     • Android SDK at C:\Users\Dih\AppData\Local\Android\sdk
> >     • Android NDK location not configured (optional; useful for native profiling support)
> >     • Platform android-29, build-tools 29.0.0
> >     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> >     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> >     • All Android licenses accepted.
> > 
> > [√] Android Studio (version 3.4)
> >     • Android Studio at C:\Program Files\Android\Android Studio
> >     • Flutter plugin version 37.0.1
> >     • Dart plugin version 183.6270
> >     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> > 
> > [√] Connected device (1 available)
> >     • Android SDK built for x86 • emulator-5554 • android-x86 • Android 4.4.2 (API 19) (emulator)
> > 
> > • No issues found!
> > ```
> > 
> > 
> > My laptop:
> > ![3](https://user-images.githubusercontent.com/20110433/60999168-df341180-a330-11e9-809b-1dbd60c06a8a.JPG)
> 
> plz try this lines
> 
> defaultConfig {
> // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
> ndk {
> abiFilters "armeabi-v7a", "x86_64", "armeabi", "mips"
> // abiFilters "arm64-v8a", "armeabi-v7a","armeabi", "mips", "x86"
> }
> applicationId "com.example.tvs_visibility"
> minSdkVersion 16
> targetSdkVersion 28
> versionCode flutterVersionCode.toInteger()
> versionName flutterVersionName
> testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
> }

I did it with Android 4.4 emulator, same problem.
I tested Pixel API 21 1080 x 1920 with Android 5.0 (Google APIs) x86, and it worked, looks like the problem is testing apps in emulators with lower resolution. Those I tested was < 768 x 1280. And for images lower than 5.0 the same problem happened even with emulators with high resolutions (Pixel API 21 1080 x 1920):

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.

Installing build\app\outputs\apk\app.apk..
```

Emulator: "Unfortunately app_name has stopped."

**Comment by rdinkel** [comment]
In the emulated android go to factory reset. Let it run. This fixed it for me.
Seems to be a bug that android, after creating the vm, thinks its low on space even it has over 2gb of space and a lot of ram.

**Comment by bettdalpha** [comment]
> In the emulated android go to factory reset. Let it run. This fixed it for me.
> Seems to be a bug that android, after creating the vm, thinks its low on space even it has over 2gb of space and a lot of ram.

This fixed my issue

**Comment by janmoppel** [comment]
Hello @d-apps !

Thank you for posting an issue.
Have you tried solution proposed by the @rdinkel? Did it solve the problem for you?

**Comment by d-apps** [comment]
I ended up using emulator with android 6.0, changed the configuration and now it, working.

**Comment by janmoppel** [comment]
Hello @d-apps !

Great, nice to hear it's working now!

Closing this issue then.
