### ISSUE TITLE
Setting skia cache size causes crash in release mode on android

### ISSUE THREAD

**Issue by abhishekamit** [flutter/flutter#35890]
If an android flutter application invokes the Skia.setResourceCacheMaxBytes method on the skia system channel at startup it crashes in release mode because there is not yet a surface here: https://github.com/flutter/engine/blob/6cf0d1350e0ac03df9ebcbb15c35a4a035010460/shell/common/rasterizer.cc#L424

**Comment by abhishekamit** [comment]
It appears this may also be causing issues when setting a cache size running in an emulator in debug mode, though that hasn't been verified.

**Comment by dnfield** [comment]
This has been fixed by https://github.com/flutter/engine/pull/10434
