### ISSUE TITLE
header fonts on website changed from roboto

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#3590]
The header fonts on the website changed from Roboto to Helvetica - I'm not sure this was intentional?

@qchong 

<img width="327" alt="screen shot 2016-04-27 at 2 31 59 pm" src="https://cloud.githubusercontent.com/assets/1269969/14868901/0a7e1f20-0c85-11e6-9526-b22125b54823.png">

**Comment by sethladd** [comment]
Roboto is our standard font. Thanks for the catch!
