### ISSUE TITLE
Crash when using cloud_firestore 

### ISSUE THREAD

**Issue by BlueDragon709** [flutter/flutter#35911]
When i added the cloud_firestore package to my app the app won't launch anymore. I have the crash dump to this post.
[error.txt](https://github.com/flutter/flutter/files/3379363/error.txt)

**Comment by rbrose** [comment]
Change in android/app/build.gradle minSdkVersion to 21 and it will work. Because Android SDK Version under 21 haven't DEX support.

**Comment by BondarenkoStas** [comment]
@BlueDragon709 Did you manage to solve it?

**Comment by BlueDragon709** [comment]
I did what rbrose said and that worked.
Sorry for the the late reaction

**Comment by janmoppel** [comment]
Closing the issue as it was resolved.
