### ISSUE TITLE
Error when upgrading to flutter 

### ISSUE THREAD

**Issue by toger5** [flutter/flutter#35921]
## Steps to Reproduce

1. Unpack folder for flutter on linux
2. Run flutter upgrade
3. I get this error:
```
...nloading Dart SDK from Flutter engine 54ad777fd29b031b87c7a68a6637fb48c0932862
curl: (3) URL using bad/illegal format or missing URL

/dart-sdk-linux-x64.zipDart SDK from: https://storage.googleapis.com/flutter_infra/flutter/54ad777fd29b031b87c7a68a6637fb48c0932862
If you're located in China, please see this page:
  https://flutter.dev/community/china
```
Seems like sth is wrong with this link ![https://storage.googleapis.com/flutter_infra/flutter/54ad777fd29b031b87c7a68a6637fb48c0932862](https://storage.googleapis.com/flutter_infra/flutter/54ad777fd29b031b87c7a68a6637fb48c0932862). 
Also tried switching to another channel `flutter channel dev`

**Comment by toger5** [comment]
i was hoping this is just a netowork infrastructure issue. But It still didnt resolve itself.

**Comment by toger5** [comment]
This issue is actually realted to the line endings.
linux has issues with concatinating bash variables when they are loaded from a CRLF file.
```
[name@localhost bin]$ EV=$(cat /home/name/flutter/bin/test)
[name@localhost bin]$ echo $EV A
hi A
```
test is a LF file
```
[name@localhost bin]$ EV=$(cat /name/name/flutter/bin/internal/engine.version)
[name@localhost bin]$ echo "$EV" "a "
a f8bffb9620575a1c5e3026b595e7bfb68a85f3
```
engine.version somehow is a CRLF file (in a git repo... ugh ;) )

The result of that is, that the url with the ENGIEN_VERSION cannot be properly created beacuse the string is currupted when using the CRLF data from engine.version...

That is what caused my problem in the initial post. 

## Solution
changed engine.version CRLF -> LF

**Comment by toger5** [comment]
this issue can get closed but this root cause really needs to be addressed. (maybe converting the whole repo to LF?

**Comment by rishabhdeepsingh** [comment]
I am also facing the same Issue
```
flutter doctor -v
...nloading Dart SDK from Flutter engine b6b54fd60631a3828c2e2c9b079b5d1d2d8c8c37
curl: (3) URL using bad/illegal format or missing URL

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra/flutter/b6b54fd606/dart-sdk-darwin-x64.zip8c8c37
If you're located in China, please see this page:
  https://flutter.dev/community/china
```

**Comment by rishabhdeepsingh** [comment]
```
$ flutter channel dev
...nloading Dart SDK from Flutter engine af51afceb8886cc11e25047523c4e0c7e1f5d408
curl: (3) URL using bad/illegal format or missing URL

/dart-sdk-darwin-x64.zipart SDK from: https://storage.googleapis.com/flutter_infra/flutter/af51afceb8886cc11e25047523c4e0c7e1f5d408
If you're located in China, please see this page:
  https://flutter.dev/community/china
```

**Comment by cristiansoto7** [comment]
i have the same error.. are there any fix for this?

**Comment by LeeLoHoon** [comment]
same error... I can't do anything which is related to "flutter ~" command..

**Comment by darshankawar** [comment]
@toger5 Based on your comment [here](https://github.com/flutter/flutter/issues/35921#issuecomment-516226128), I am going ahead and closing this issue as solved.

@cristiansoto7  @LeeLoHoon See the solution posted by the author and check if it resolves your issue.
If not, since this is an old issue, I'd suggest anyone facing this issue, file a new one by providing all required details.
If you disagree, write in comment and I'll reopen it.
Thanks.
