### ISSUE TITLE
shaderWarmUp doesn't store shaders in PersistentCache

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#35923]
If you put a print statement in the `DefaultShaderWarmUp.execute` method and put a breakpoint at `flutter::PersistentCache::store` on an app that creates a FlutterEngine but doesn't create a FlutterViewController, you'll see that the DefaultShaderWarmUp is executed but nothing is stored in the PersistentCache.

I believe this is a great opportunity to make the first frame rendering faster on iOS, for the add-to-app case for sure, I'm not sure about the full Flutter case.

**Comment by xster** [comment]
We still manually request a frame in full-app cases before the first vsync to get a few milliseconds

**Comment by gaaclarke** [comment]
This appears to be happening because the Rasterizer doesn't have a surface so a CPU surface is getting generated:
https://github.com/flutter/engine/blob/0cdfdce7179e82a95342b7a7349c5cada5fbf4cc/shell/common/rasterizer.cc#L133

The result is that the device is a SkBitmapDevice here:
https://github.com/google/skia/blob/215ff3325230557a35dce26174b3294b570afbf9/src/core/SkCanvas.cpp#L672

**Comment by gaaclarke** [comment]
Here is the current setup: 
![shaderwarmup](https://user-images.githubusercontent.com/30870216/61090056-0e5e8780-a3f2-11e9-809f-8fc0dc811ad4.png)

What we can do is:
1. Remove Rasterizer::MakeRasterSnapshot and put the logic into Picture::RasterizeToImage
2. Switch that logic to instead of using the Rasterizer.surface_ to render, render on a surface that we've generated.  If the IOManager has a GrContext we can use that to generate an offscreen gpu surface, otherwise create a CPU surface.
3. Switch the rasterization to always happen on the IO thread instead of the GPU thread.

This is nice to because there is no reason that we should be generating these offscreen on the GPU thread and blocking regular rendering.

**Comment by jmagman** [comment]
Removed with https://github.com/flutter/flutter/pull/88455.  @gaaclarke is there any actually work here post-impeller?

**Comment by gaaclarke** [comment]
> Removed with #88455. @gaaclarke is there any actually work here post-impeller?

Nope, impeller should make this obsolete.
