### ISSUE TITLE
platform_channel_swift example project has deprecation warning: 'binaryMessenger' is deprecated

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#35928]
The example project platform_channel_swift has deprecation warning when built with Xcode:
flutter/examples/platform_channel_swift/ios/Runner/AppDelegate.swift:34:75: 'binaryMessenger' is deprecated

**Comment by jmagman** [comment]
See https://github.com/flutter/flutter/issues/35773

**Comment by gaaclarke** [comment]
I talked with Xiao offline.  We think it will be cleaner if we can:
1) remove the deprecation of that method
2) make the FlutterViewController just return the engine's binaryMessenger 
3) update the docstring for FlutterViewController.binaryMessenger explain its just a convenience method for FlutterEngine.binaryMessenger

This makes communication more clean with what already has been said and make upgrading the easiest.
