### ISSUE TITLE
LazyBlock keeps calling delegate.buildItem() after the delegate returns null

### ISSUE THREAD

**Issue by ianloic** [flutter/flutter#3593]
Our code has a LazyBlock with a delegate that returns nulls when we exhaust items. It used to stop scrolling once the delegate ran out of items. After cc9d602b12974e6a61c0a0e23e0649b7a89cf9ba it broke. The LazyBlock would keep calling the delegate's buildItem with the same index that returned null and the display went blank.

I don't have a small test case, sorry.

/cc @abarth

**Comment by abarth** [comment]
Thanks.  Will fix.
