### ISSUE TITLE
How to extend core methods?

### ISSUE THREAD

**Issue by ydwan** [flutter/flutter#35950]
Example:
'123456'.equals(str);
Not find 'equals' method in flutter.
I want add a method on class and not break too many code.

In c#, we can add 'static' on class.
``` static class String {static Boolean equals() {.........}}```

**Comment by stuartmorgan** [comment]
Since this question is about Dart, rather than Flutter, you should ask in a forum specific to the Dart language.

**Comment by ydwan** [comment]
thanks!
