### ISSUE TITLE
Camera captured Images are taking a long time to display

### ISSUE THREAD

**Issue by Loopex2019** [flutter/flutter#35953]
Hi There . I realized that after i capture a Photo using the `takePicture()` Method and then i start
displaying them using the `Image.file()` Constructor , it takes about 2 to 3  seconds to 
display them which is a lot of time .  It takes even more time like  2 to 3 seconds when using the 
`takePicture()` Method with the back Camera or the rear Camera . In the other hand , it takes nearly < second to display an image from the gallery so using now the imagePicker Package . 
Now i want to know why is that happening and if there is a Solution please tell me .
And here is my Code about capturing images :
```
             () async {
                    _animationController2.forward();
                    try {
                      await _inizializedCamera;
                      final path = join(
                     (await getTemporaryDirectory()).path,
                        '${DateTime.now()}.png',
                      );
                      await _controller.takePicture(path);
                      setState(() {
                        _imagePath = path;
                      });
                      _addImageItem(_imagePath);
                      if (img.length == _counter) {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => DisplayPhotosPage(
                                  photos: img,
                                ),
                          ),
                        );
                      }
                    } catch (_) {
                      setState(() {
                        _cameraError = true;
                      });
                      if (_cameraError == true) {
                        _showCameraException();
                      }
                    }
                   },
```
The `addImageItem()` Method adds that current `ImagePath` Variable to a List of Strings , which
represents the File Paths of each token image from the Gallery or using the `takePicture` Method . That Data Source :  `List<String>` gets display inside a `ListView()` with the help of the 
`List.generate()` Named Constructor . It takes as a first Parameter the length of the `List<String>`,
then as a second Argument it takes an Anonymous Function ,  which builds the single List Item , 
in my Case it's an `Image.file`  Named Constructor. Here i gonna pass the  `File`   Object as Positional Argument  and than pass a Path (String) to that `File` Object and for that i need to access the single item in the `List<String>` using the given index (int value) parameter in the 
`List.generate()` Named Constructor .   And here is the Code for adding Images or File Paths from the 
Gallery : 
```
 Future<void> _pickGalleryImage(BuildContext context) async {
    final imageFile = await ImagePicker.pickImage(
      source: ImageSource.gallery,
    );
    setState(() {
      img.add(imageFile.path);
    });
    if (img.length == _counter) {
      Navigator.pushReplacement(
        context,
        MaterialPageRoute(
          builder: (context) => DisplayPhotosPage(
                photos: img,
              ),
        ),
      );
    }
  }
```

**Comment by BondarenkoStas** [comment]
@Loopex2019 Can you please try it using the current flutter stable v1.9.1+hotfix.2 and camera 0.5.4+3?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
