### ISSUE TITLE
 '_debugLifecycleState == _StateLifecycle.created': is not true.

### ISSUE THREAD

**Issue by NatureDay** [flutter/flutter#35958]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by dnfield** [comment]
It looks like you may have forgotten to fill out the body of this issue.  Without more information, this isn't really actionable.

Please feel free to re-open (or open a new issue) with more details, in particular the revision of Flutter you're using and a small sample program or test that demonstrates the failure you're seeing.
