### ISSUE TITLE
Error when jumping page and having a return value

### ISSUE THREAD

**Issue by androidmh** [flutter/flutter#35966]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by hemnathmouli** [comment]
Can you provide `flutter doctor -v`

**Comment by BondarenkoStas** [comment]
@androidmh Please provide your flutter doctor -v output. Provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
