### ISSUE TITLE
Performance of flutter run on weston desktop shell

### ISSUE THREAD

**Issue by ping996** [flutter/flutter#35969]
I have test the flutter on weston(version: 6.0) desktop shell and x11 one on ubuntu 18, the flutter frame: 
weston: 
        GPU: about 30ms/frame 
        UI: about 2ms/frame
x11: 
        GPU: about 2ms/frame 
        UI: about 1ms/frame

does the flutter need to do some adaptation on weston? the GPU frame is so bigger now.
any suggestions about this topic?

**Comment by stuartmorgan** [comment]
What exactly are you testing here? Is this the separate flutter_wayland project like your previous issue reports? The Linux runner from flutter-desktop-embedding? Something else?

**Comment by ping996** [comment]
yes, weston used the https://github.com/chinmaygarde/flutter_wayland to launch a flutter application, 
the flutter-desktop-embedding for launch the same flutter application.

**Comment by stuartmorgan** [comment]
That project is not part of Flutter; please don't file bugs about it here. If you have concerns about its performance, file bugs in that project's issue tracker.

**Comment by amreniouinnovent** [comment]
@ping996 As I know that flutter is working on Linux so how is Wayland related?
is Flutter support a specific Linux type?

**Comment by ping996** [comment]
@amreniouinnovent  flutter can run linux desktop system of x11 and wayland window management protocol.
