### ISSUE TITLE
How to get Android Activity Lifecycle Events in Flutter Plugin?

### ISSUE THREAD

**Issue by shahxadakram** [flutter/flutter#35963]
How can we get Android Activity Lifecycle Events in flutter plugin developement?

I tried this,

    class MyPlugin() : MethodCallHandler, PreferenceManager.OnActivityDestroyListener, PreferenceManager.OnActivityStopListener {
    
        override fun onActivityDestroy() {
            Log.d(TAG, "Activity Destroyed")
        }
    
        override fun onActivityStop() {
            Log.d(TAG, "Activity Stopped")
        }

        override fun onMethodCall(call: MethodCall, result: Result) {
        
        }
    
    }

But these are returning nothing.

**Comment by feinstein** [comment]
Questions should be ask in Stackoverflow.com, not here.

**Comment by FullstackJack** [comment]
@LongCatIsLooong Please close.
