### ISSUE TITLE
The last GrRenderTargetOpList::onExecute function  cost too much time on the iOS platform

### ISSUE THREAD

**Issue by wangying3426** [flutter/flutter#35961]
The last GrRenderTargetOpList::onExecute function cost too much time , when we run flutter_gallery demo‘s transition animation on iOS platform, so what could be the reason ?

![Screen Shot 2019-07-11 at 3 03 19 PM](https://user-images.githubusercontent.com/4476512/61029388-7f4f7080-a3ed-11e9-9e84-f3d72f0d9778.png)

[dart-timeline.json.zip](https://github.com/flutter/flutter/files/3380663/dart-timeline.json.zip)

**Comment by dnfield** [comment]
Please include the revision of Flutter you're using and a small reproduction of the case.

FWIW, I've seen this happen on an older revision of Flutter when platform views were causing the GPU and Platform thread to be merged, and the pipeline depth was set to 2.  In general, this can happen when the GPU and CPU get out of sync with each other and someone ends up waiting for progress that the other isn't making.

**Comment by wangying3426** [comment]
iPhone 6 Plus，Flutter version is 1.5.4，and we add some timeline trace events, GrGLGpu::clear etc. Sometimes  this case appears, and may reproduction according the picture .

![Screen Shot 2019-07-11 at 5 27 39 PM](https://user-images.githubusercontent.com/4476512/61039503-75376d00-a401-11e9-81be-396e3cc0ae90.png)


> Please include the revision of Flutter you're using and a small reproduction of the case.
> 
> FWIW, I've seen this happen on an older revision of Flutter when platform views were causing the GPU and Platform thread to be merged, and the pipeline depth was set to 2. In general, this can happen when the GPU and CPU get out of sync with each other and someone ends up waiting for progress that the other isn't making.

**Comment by dnfield** [comment]
Can you try the same on the new stable (1.7.8.x)?  Or mastee

**Comment by wangying3426** [comment]
> Can you try the same on the new stable (1.7.8.x)? Or mastee
New stable (1.7.8.x) has the same problem.

**Comment by jmagman** [comment]
@dnfield I'm guessing we can close this post-impeller?
