### ISSUE TITLE
Host Card Emulation (HCE) with Flutter

### ISSUE THREAD

**Issue by OlivierGrenoble** [flutter/flutter#35960]
Is there a plan to support Host Card Emulation in Flutter? This would allow to interact with IOT objects like smartlocks. 
Here is Android documentation about HCE: https://developer.android.com/guide/topics/connectivity/nfc/hce

**Comment by dnfield** [comment]
This would probably be a plugin of some sort.  https://pub.dev/packages/nfc_in_flutter Seems like it might be what you want.

**Comment by OlivierGrenoble** [comment]
Thanks. I can see now that Apple has not opened the Host Card Emulation mode, even on IOS 13.

**Comment by amerinoo** [comment]
Has anybody tried HCE in an Android device with the plugin [nfc_in_flutter](https://pub.dev/packages/nfc_in_flutter)?

**Comment by deandreamatias** [comment]
I found [this question](https://stackoverflow.com/questions/44385724/corenfc-for-card-emulation) about card emulation in iOS. In the answer, have an interesting comment:
> iPhone's NFC hardware is complete but iOS limits it. For example, the wallet app(Apple Pay) obviously works in card emulation mode. Apple at this moment doesn't want others to have the ability to create an NFC wallet app.


About this:
> Has anybody tried HCE in an Android device with the plugin [nfc_in_flutter](https://pub.dev/packages/nfc_in_flutter)?

From what I read, the plugin only gives an option to read an HCE on Android, but not emulate a host card.

**Comment by dmacan23** [comment]
I see that this is still an open issue. I suppose that the reason this feature isn't supported through Flutter officially yet is because iOS doesn't support HCE even natively. But if you want to have a HCE support for your Flutter app, you can always do it natively on Android and then hook it up to your Flutter app. I've wrote [an article](https://zeromolecule.com/blog/host-card-emulation-hce-with-android-and-flutter/) earlier on how to do that so feel free to check it out :)

**Comment by Sylwek777** [comment]
> I see that this is still an open issue. I suppose that the reason this feature isn't supported through Flutter officially yet is because iOS doesn't support HCE even natively. But if you want to have a HCE support for your Flutter app, you can always do it natively on Android and then hook it up to your Flutter app. I've wrote [an article](https://zeromolecule.com/blog/host-card-emulation-hce-with-android-and-flutter/) earlier on how to do that so feel free to check it out :)

Could you share the whole example code mentioned in article via github?

**Comment by heeshala** [comment]
Is there any solution at the date ? 
I found this https://github.com/ryanhz/nfc_emulator
But it does not save an nfc card and emulate it generates random nfc IDs

**Comment by mipangotz** [comment]
I think the issue here is HCE on iOS. iOS 16 is coming out soon, any news?

**Comment by amirsuwal01** [comment]
Is there any solution to emulate mobile devices as HCE? Been trying for so long. Could not find any good resources

**Comment by feduke-nukem** [comment]
> Is there any solution to emulate mobile devices as HCE? Been trying for so long. Could not find any good resources.Also some resources for native would be more helpful as well

There are good old references on Xamarin:
https://github.com/xamarin/monodroid-samples/tree/main/CardEmulation
https://github.com/xamarin/monodroid-samples/tree/main/CardReader

Just adapt them to Dart/Flutter and that's all.

**Comment by jonahwilliams** [comment]
While a HCE plugin would be worthwhile, its not something the flutter team plans to provide.
