### ISSUE TITLE
firebase_auth plugin does not return the refresh_token and access token

### ISSUE THREAD

**Issue by premtemp1** [flutter/flutter#35974]
Hello,
  The firebase_auth plugin does not provide an option to get the refresh token and access token when you create a new user. This is need if you are linking to your custom backend service.. 

Can you please let me know how we get these values

Thanks

**Comment by long1eu** [comment]
I'm doing a RP for this.

**Comment by premtemp1** [comment]
@long1eu long1eu
Hello ...

Thanks for your response but I Just wanted to verify .. you said RP... you meant PR. right ?..   Also, PR #1926 is mark close.. is it possible for me to know what is the ETA for this fix..

Thanks for your help

**Comment by long1eu** [comment]
@premtemp1 :)) Thanks! Yes it was a typo. Maybe next week but this doesn't mean it will make it to pub.

**Comment by premtemp1** [comment]
Thank you.. sorry for the rush,,, I really need this information otherwise my project is in jeopardy .. I don't know of an alternative method to get this information,,,


Thank you again

**Comment by long1eu** [comment]
Hi!

Can you be more explicit on what exactly you want to expose? Maybe pointing to some docs or give some examples. 

Thanks

**Comment by premtemp1** [comment]
@long1eu ,

I would like the refresh token object that is returned for the firebase user

Here an API call --https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=[API_KEY] . You can see there is an option to get the id and refresh tokens.


Also, the firebase user object has the properties "refresh token"
https://firebase.google.com/docs/reference/js/firebase.User

The javascript version return the access token. However, the flutter plugin does not.. 

Thank for your help

**Comment by long1eu** [comment]
Can you check this PR https://github.com/flutter/plugins/pull/1932 . Does this help?

**Comment by premtemp1** [comment]
I did but it does not address my issue

**Comment by long1eu** [comment]
Thank you for doing that. For what I've seen there is not way to directly get the refreshToken using the auth SDK, so this might not be a flutter issue.

If you are referring to the [Firebase Auth REST API](https://firebase.google.com/docs/reference/rest/auth#section-api-usage), then this is another story. The `API_KEY` required for that request is not the `refreshToken` but the Web API Key, which can be obtained on the project settings page in your admin console. This endpoint `https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=[API_KEY]` will return the [`refreshToken`](https://firebase.google.com/docs/reference/rest/auth#section-create-email-password)
 
But I'm not sure why you want to use both the Rest API and this plugin. Using this plugin you don't need to worry about any of those. The equivalent of that endpoint is

```
FirebaseAuth.instance.signInWithEmailAndPassword(email: 'username@domain.com', password: 'password');
```

or 

```
    final AuthCredential credential = EmailAuthProvider.getCredential(email: 'username@domain.com', password: 'password');
    FirebaseAuth.instance.signInWithCredential(credential);
```

**Comment by premtemp1** [comment]
@long1eu  

Maybe I am not explaining correctly ..

We are authenticating again our  custom backend and we need the refresh token. The IdToken is  good but we need both ..

The firebase-auth plugin return a Firebase user. However, it does not include the refresh token.. As you can see from the spec --https://firebase.google.com/docs/reference/js/firebase.User.. The refresh token is a field in the object

I just included the API  link to show that if one should use the Api to signup with ID/pass it return the refresh token... So, the plugin should provide similar option . 

Thanks for your help

**Comment by long1eu** [comment]
I understand. Still the plugin can provide only what the underlying
platform is providing. Can you show me this field in the Android or iOS SDK?

**Comment by premtemp1** [comment]
@long1eu .
The SDK returns a firebase user. This is the definition of a Firebase user -->https://firebase.google.com/docs/reference/js/firebase.User

Here is the list properties for. firebase user.. As you can see from the official documentation that there is a properties call refreshToken which is not returned from the plugin....


Properties

displayName
email
emailVerified
isAnonymous
metadata
phoneNumber
photoURL
providerData
providerId
refreshToken
uid

**Comment by premtemp1** [comment]
@long1eu 
I added the information above... Please have a look and let me know..

Thanks for your help

**Comment by long1eu** [comment]
Hey

Thanks for getting back to me. Can you show me the exact same field on the
Android or iOS SDK. An can please explain you use case? What do you want to
do with the refresh token.

**Comment by premtemp1** [comment]
Thanks
This is the field for iOS JDK
https://firebase.google.com/docs/reference/swift/firebaseauth/api/reference/Classes/User#refreshtoken

**Comment by premtemp1** [comment]
@long1eu 

thanks
This is the field for iOS JDK
https://firebase.google.com/docs/reference/swift/firebaseauth/api/reference/Classes/User#refreshtoken

I look at SDK code and found the call..

https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Auth/Source/User/FIRUser.m

void)retrieveUserWithAuth:(FIRAuth *)auth
                 accessToken:(nullable NSString *)accessToken
   accessTokenExpirationDate:(nullable NSDate *)accessTokenExpirationDate
                refreshToken:(nullable NSString *)refreshToken
                   anonymous:(BOOL)anonymous
                    callback:(FIRRetrieveUserCallback)callback {
  FIRSecureTokenService *tokenService =
      [[FIRSecureTokenService alloc] initWithRequestConfiguration:auth.requestConfiguration
                                                      accessToken:accessToken
                                        accessTokenExpirationDate:accessTokenExpirationDate
                                                     refreshToken:refreshToken];

**Comment by kroikie** [comment]
@premtemp1

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1099. Any further collaboration will be done there.

**Comment by KFMONGF2P** [comment]
@premtemp1 , I encountered the same issue, does it have a solution for the mentioned issue? If there is, please guide, thank you in advance.
