### ISSUE TITLE
TextField in Expanded can't vertical in center

### ISSUE THREAD

**Issue by elrondliu** [flutter/flutter#35970]
## Steps to Reproduce
![image](https://user-images.githubusercontent.com/456367/61039715-df501200-a401-11e9-81a0-52fc53a42e1b.png)

![image](https://user-images.githubusercontent.com/456367/61039734-ea0aa700-a401-11e9-800e-5aa1b6700877.png)

 as it

**Comment by hemnathmouli** [comment]
You sent the bottom `contentPadding` inside InputDecoration to 0

```
decoration: InputDecoration(
     border: InputBorder.none,
     hintText: 'Hola',
     contentPadding: EdgeInsets.only(bottom: 0.0)
)
```

**Comment by FullstackJack** [comment]
@LongCatIsLooong Please close.
