### ISSUE TITLE
Manifest merger failed : Overlay manifest:package attribute declared at AndroidManifest.xml

### ISSUE THREAD

**Issue by Cumbemoz** [flutter/flutter#35976]
I was Having this issue on Flutter, After Trying to Change the package name, so it says
Manifest merger failed : Overlay manifest:package attribute declared at AndroidManifest.xml:2:5-45 value=(_my Old Package_)

        has a different value=(_My New Package_) declared in main manifest at AndroidManifest.xml:2:5-50

        Suggestion: remove the overlay declaration at AndroidManifest.xml       and place it in the build.gradle:

                flavorName {

                        applicationId = "_My old Package_"

                }

To Fix it i found another Android Manifest files, they Were on C:\Users\myusername\Desktop\MyFlutterProjects\Myappname\android\app\src\profile
and
C:\Users\myusername\Desktop\MyFlutterProjects\Myappname\android\app\src\debug

you have to change the package on this two other manifest files

**Comment by arAfnan** [comment]
I've tried this solution it was no errors but the application keep stopping :(

**Comment by Cumbemoz** [comment]
Try Changing The Package Name on The Main App Java file, And Check if you have found all the Manifest File bc there´s 3 of them

**Comment by ArivuLabs** [comment]
I had the same issue, however, I changed under 4 places.

1.)  **src/debug/AndroidManifest.xml**
2.) **src/profile/AndroidManifest.xml**
3.) **src/main/AndroidManifest.xml**
4.) **build.gradle**  
defaultConfig {
 **applicationId**
}

After changing the 4 location, I could run the app with the new application id.

**Comment by ArivuLabs** [comment]
Hi All,

I had the same issue and i changed in 5 location.

1.)   **src/profile/AndroidManifest.xml**
2.)   **src/debug/AndroidManifest.xml**
3.)   **src/main/AdroidManifest.xml**
4.)   build.gradle .     
     defaultConfig {
        **applicationId**
5.) MainActivity.java on   "**package**"

I can run without any issue.

**Comment by shashankduhan** [comment]
There are three Manifest files, try to search them and change your package name.
In these directories:
app/src/debug
app/src/profile
app/src/main

**Comment by atanudasgupta** [comment]
Yes there are 3 files indeed , so confusing. :) took me time to figure out.

**Comment by BondarenkoStas** [comment]
@Cumbemoz actually there was an article https://medium.com/@skyblazar.cc/how-to-change-the-package-name-of-your-flutter-app-4529e6e6e6fc describing all the changes, it was published before you posted the issue:) I think it's safe to close this one.

**Comment by RayhanYulanda** [comment]
What is the different between android manifest in profile and main?
