### ISSUE TITLE
[Add2App] Add To App iOS with no custom AppDelegate

### ISSUE THREAD

**Issue by Vanethos** [flutter/flutter#35984]
## Objective
Create an iOS framework that uses the Flutter Add To App feature so that it can be added to other apps without adding the Flutter SDK By hand

## Problems

So far I have done the following:

- Created a new framework
- Directly used the `podhelper.rb` modified in the Podfile so that I know what pods are imported and what is being done
- Solved conflicts in the `podsec` files for the `Flutter``engine` and the `FlutterPluginRegistrant`
- Added a convenience class to the framework that can initialize an engine and displays the correct `UIViewController`

```swift
import Foundation
import Flutter

open class FlutterFramework {
    public static let shared = FlutterFramework()
    
    private init(){}
    
    var engine : FlutterEngine?
    
    open func initializeFlutterEngine() {
        engine = FlutterEngine(name: "io.flutter", project: nil);
        engine?.run(withEntrypoint: nil);
    }
    
    open func presentFirstViewControllerOn(_ viewController:UIViewController) {
        let vc : ViewController = ViewController()
        viewController.present(vc, animated:true, completion:nil)
    }
}
```

```swift
class ViewController: UIViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        let button = UIButton(type:UIButton.ButtonType.custom)
        button.addTarget(self, action: #selector(handleButtonAction), for: .touchUpInside)
        button.setTitle("Press me", for: UIControl.State.normal)
        button.frame = CGRect(x: 80.0, y: 210.0, width: 160.0, height: 40.0)
        button.backgroundColor = UIColor.blue
        self.view.addSubview(button)
    }
    
    @objc func handleButtonAction() {
        let flutterViewController = FlutterViewController(engine: FlutterFramework.shared.engine, nibName: nil, bundle: nil)!;
        self.present(flutterViewController, animated: false, completion: nil)
    }
}
```

- Used the `initializeFlutterEngine()` in the application's `AppDelegate` to initialize the Flutter engine.

When doing so, the following occurs:

```
2019-07-11 14:01:11.895325+0100 flutter_ios_host[50001:2161925] [VERBOSE-2:engine.cc(115)] Engine run configuration was invalid.
2019-07-11 14:01:11.895555+0100 flutter_ios_host[50001:2161925] [VERBOSE-2:FlutterEngine.mm(304)] Could not launch engine with configuration.
```

So my question is: is it possible to start a `FlutterEngine` without making the changes suggested to `AppDelegate` in the [add to app page](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) ? This functionality is woking in the Android counterpart.

Also, how can we bundle this framework and use it in a computer without Flutter?

If my understanding is correct, we are using a script inside the `FLUTTER_ROOT` folder, that might not be available in other computer, so how can we proceed? Can this script be bundled with the framework and called there?

**Comment by xster** [comment]
You kinda have 2 questions in there. The solution for the latter is to solve https://github.com/flutter/flutter/issues/36968.

**Comment by jmagman** [comment]
Also relevant https://github.com/flutter/flutter/issues/32995.

**Comment by jmagman** [comment]
I tried with your repro steps on master, and when I hit the "Press Me" button I get the Flutter demo screen and can interact with the observatory.

Podfile
```swift
flutter_application_path = '../flutterapp'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'HelloWorld' do
  use_frameworks!
  install_all_flutter_pods(flutter_application_path)
end
```
AppDelegate
```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
  FlutterFramework.shared.initializeFlutterEngine()
  return true
}
```
Can you try again after a `flutter upgrade` on the master channel?  We've fixed a lot in the last few months.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
