### ISSUE TITLE
Circular progress indicators animate slowly

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#3599]
The material gallery [progress indicators demo] only manages about 30 fps, even with the non-standard elliptical progress indicator commented out.

The problem appears to be SKIA arc drawing - https://bugs.chromium.org/p/skia/issues/detail?id=5227

**Comment by sethladd** [comment]
cc @abarth might be rolling skia to help with this?

**Comment by abarth** [comment]
They're still working on this one.

**Comment by dragostis** [comment]
I'v worked on getting the Skia fix [in](https://github.com/flutter/engine/pull/2995), but the performance improvements are *marginal* at best and the stuttering is still present.

**Comment by eseidelGoogle** [comment]
@chinmaygarde my understanding from our conversation just now was that progress indicators were not the target of https://bugs.chromium.org/p/skia/issues/detail?id=5227?

**Comment by dragostis** [comment]
@eseidelGoogle I've updated https://github.com/flutter/engine/pull/2995 and it seems like the fix solves our issue.
