### ISSUE TITLE
Selection menu doesn't show after entering text then clearing/deleting

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#35998]
After https://github.com/flutter/flutter/issues/33293 was merged, a [commenter pointed out](https://github.com/flutter/flutter/issues/33293#issuecomment-510500688) that this similar problem still exists.

### Steps to reproduce

  1. Run an app with a TextField (see below for an example).
  1. Long press the field and the selection menu should show (correct).
  1. Type some text and long press outside of the text to show the menu again (correct).
  1. Delete the text so the field is empty and long press again.  The menu won't be shown (incorrect!).

### Code

```dart
import 'package:flutter/material.dart';\

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(),
      title: 'Text Field Test',
      home: MyApp(),
    );
  }
}
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("TextField Test"),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          mainAxisAlignment: MainAxisAlignment.center,
          child: TextField(),
        ),
      ),
    );
  }
}
```

**Comment by justinmc** [comment]
I think the root problem is that the selection overlay in editable_text.dart needs to be present to show the menu, but it's constantly destroyed and recreated at weird times.

When the longpress happens in the cleared field, the selection overlay does not exist.  `selectPositionAt` is called, but it doesn't call `_handlePotentialSelectionChange` because the old and new selection is the same.

However when the longpress happens after entering text, the old and new selection is different, so the overlay gets created and can be shown.  The only difference in the old and new selection is the affinity, which seems like it's a total fluke that the menu correctly shows in this case.

I think we need to dig into exactly why the overlay is created and destroyed so much, and why the ability to show the selection menu depends on that.  It seems like it should be refactored and simplified.  Otherwise a hack around that weird affinity change might work.

**Comment by masewo** [comment]
Happens to multiline TextFields (maxLines > 1) at the beginning of every new line, too.

**Comment by justinmc** [comment]
@masewo Thanks for that, I hadn't noticed that case.

**Comment by rikiyanuar** [comment]
Is there a way to get this work properly for now?
I have to make this work for my clients. 
Please help.

**Comment by justinmc** [comment]
@rikiyanuar I'm unaware of a workaround, but I plan to take a look at fixing this in Flutter soon!  It seems like this is affecting a lot of people.

**Comment by justinmc** [comment]
I've got a PR out with a working fix.  Hopefully it will go into the master channel next week.

**Comment by justinmc** [comment]
This should be in the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels) now, and will be in the next release (>v1.8.3).

**Comment by yaymalaga** [comment]
Unfortunately, if the TextField is inside a modal, like a Dialog or a BottomSheet, the first time it is opened the copy/paste is showing, but if you close it and open the modal again, the copy/paste menu won't show. I'm in master up to date.

**Comment by justinmc** [comment]
Hmm that's strange.  @yaymalaga Can you open a separate issue and include the code for a minimal app that reproduces the bug?

**Comment by yaymalaga** [comment]
@justinmc Here you go: [https://github.com/flutter/flutter/issues/37798](https://github.com/flutter/flutter/issues/37798). Can you confirm this behaviour?

**Comment by justinmc** [comment]
Yes I reproduced it with those steps.  Thanks for opening the issue.  I'll post over there.
