### ISSUE TITLE
Tab controller crashes due to wrong null check

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#35997]
Internal: b/137230214

The logic here:

https://github.com/flutter/flutter/blob/d9f6cada1ca8311e75c17cf41ea9cc3cacf74673/packages/flutter/lib/src/material/tabs.dart#L422-L423

is not right.

If both a and b are null, this block will cause a crash upon checking a.length.

The correct logic is:

```dart
if (a == null || a.length != b?.length)
  return false;
```

**Comment by mehmetf** [comment]
I would do this fix myself but I am not sure how to write a test for this to make `a` null for the Indicator.

**Comment by HansMuller** [comment]
Agreed that if a and b were both null the code after line 423 would fail when it referred to `a.length`. That said, it's not clear how that could happen. Someone is calling shouldRepaint before layout has finished? Can you provide a test case or a stack trace?

**Comment by mehmetf** [comment]
Internal bug: b/137230214 . As seen often with such corner cases, we don't have reduced test case. Specifically interesting is update #5 though.

Back to the original intent of this code. Do we mean to say one of a or b can be null but not both? or should this code assume a is never null in which case we can introduce an assert that points to a more meaningful error message?

**Comment by shihaohong** [comment]
Diving into the history of the code, it seems that it was expected that neither `a` nor `b` should have been null: 
https://github.com/flutter/flutter/pull/13164/files#diff-6d433f126d05f45352a40b9bb916ac70L317

It might make sense to re-introduce that assert, but it's still unclear to me how we got into the situation where both `a` and `b` happen to be null.

**Comment by shihaohong** [comment]
Also, I just wanted to add that if we introduce an assert, it could be a breaking change for developers who somehow get into a state where both
