### ISSUE TITLE
Running `flutter logs` just returns to the prompt

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#360]
I was experimenting to see if I could see logs from a Flutter app running on my iOS device.

I connected my device (and pressed "Trust this computer"), and then went to my prompt on my Mac, and found the source repo for the project, and then typed `flutter logs`.

Expected: some feedback to tell me if it worked or not, or ideally start streaming logs

Actual: 

```
~/Code/project[master*] $ flutter logs
~/Code/project[master*] $ 
```

Could we display to the user what happened, if there was an error, or no device found, or etc... ?

Thanks!

**Comment by Hixie** [comment]
What do you get if you run `flutter --very-verbose logs` ?

**Comment by eseidelGoogle** [comment]
`flutter logs` still doesn't work on iOS or iOS Simulator , but the behavior is different. @chinmaygarde

**Comment by devoncarew** [comment]
Dup of https://github.com/flutter/flutter/issues/1377.
