### ISSUE TITLE
Flutter does not receive meta keypresses on macOS

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#36001]
Hey!

I noticed last night that while most keypresses make their way through from the engine to Flutter on macOS, meta keypresses do not.

Don't quote me on this, but I think you might have to be listening to `flagsChanged: NSEvent`, and sending those along too.

@stuartmorgan hi :)

**Comment by stuartmorgan** [comment]
> I think you might have to be listening to `flagsChanged:`

That sounds right to me as well.

**Comment by shyndman** [comment]
Good morning.

Any news on this?

**Comment by stuartmorgan** [comment]
Nobody is currently working on it; you're welcome to submit a patch if you'd like it fixed on a specific timeframe.

**Comment by shyndman** [comment]
I'll see what I can do. Thanks Stuart.

**Comment by shyndman** [comment]
Closed via https://github.com/flutter/engine/pull/13269
