### ISSUE TITLE
flutter test --merge-coverage shows an error "Missing "coverage/lcov.base.info". Unable to merge coverage data." even when the lcov.base.info exists

### ISSUE THREAD

**Issue by lawonga** [flutter/flutter#36003]
Hello,

I'm trying to merge coverage reports of several flutter projects, and I'm getting this error:

```
"Missing "coverage/lcov.base.info". Unable to merge coverage data."
```

when I try to run the merge-coverage on any of the projects. I'm noticing the `lcov.base.info` IS in my `sdk/packages/flutter/package` location, how can I get it to read?

**Comment by apastuhov** [comment]
According to the doc - you need it. So if you want to merge coverage of several projects use next flow:
```
rm -rf coverage/
cd project1/
flutter test --no-pub --coverage --coverage-path=../coverage/lcov.base.info
cd ../project2/
flutter test --no-pub --merge-coverage
```

**Comment by BondarenkoStas** [comment]
@lawonga Did you solve the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
