### ISSUE TITLE
1.7 broke some of the objc API docs

### ISSUE THREAD

**Issue by sfshaza2** [flutter/flutter#36018]
@dnfield, has already partially fixed this.

The 1.7 release (to stable) broke the flutter/website build. Specifically, this API doc is missing:
https://api.flutter.dev/objcdoc/Classes/FlutterMethodChannel.html

Dan found that some of the objcdoc’s were not being generated. He fixed the problem and pushed it to master. Unfortunately, the link is still broken, and will continue to be broken until the docs on the site are updated. Meaning that our build will continue to break.

@Hixie suggested that we go ahead and update the docs, since it’s so close to the 1.7 release.

Please fix!

**Comment by dnfield** [comment]
I'm going to try to push the corrected docs up - will update this

**Comment by dnfield** [comment]
Ok, this should be fixed now.  Hopefully nothing else got broken in the process!

**Comment by dnfield** [comment]
/cc @tvolkert 

What I tried didn't work - it introduced #36036

**Comment by tvolkert** [comment]
@sfshaza2 is this the only broken link?  If so, can we just temporarily remove the link from the website to fix CI?

**Comment by sfshaza2** [comment]
@tvolkert, we are going to change the Travis build for the website to *not* break the build on link check errors. That will fix the problem. That is the only link that is breaking (I believe), but @danfield said that other objective C pages are missing.

**Comment by tvolkert** [comment]
That sounds like a good tide-me-over solution for now.  The ObjC docs don't get much traffic at all, so I don't think this is worth hot fixing for.

**Comment by Hixie** [comment]
If the docs process is updated (master docs are good) and we're not planning on updating the stable docs, then that means we can close this issue, right?
