### ISSUE TITLE
Eliminate Homebrew dependency in ios-usb-dependencies.py LUCI recipe

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#36019]
In order to simplify acquiring the build tools and build environment, I wrote [the LUCI recipe](https://chromium-review.googlesource.com/c/chromium/tools/build/+/1664591) which pre-builds our libimobiledevice related binaries to use a custom Homebrew tap which builds from source.

Long-term, eliminating the dependency on Homebrew would ensure that their upstream can't break our infrastructure.

**Comment by christopherfujino** [comment]
We can do this if we just install the build dependencies on a devicelab bot.

**Comment by christopherfujino** [comment]
Since we control our own physical macOS bots for the devicelab, another option would be to pre-install the required build dependencies on a particular devicelab bot (or all of them, these are relatively lightweight).

Specifically, compiling libimobiledevice (and related libraries) requires autoconf, automake, libtool, and pkg-config (Homebrew formula). These tools assume they are installed in the system root.

Once a bot is configured with these, the recipe can be simplified to simply call:

```
./autogen.sh
./configure --disable-dependency-tracking \
                          --disable-silent-rules \
                          --without-cython \
                          --enable-debug-code \

# Note, using the flag --prefix=$path may allow us to use a custom sysroot
```

After this, the recipe would also have to patch the libray links, which this WIP CL implements: [#24460](https://flutter-review.googlesource.com/c/recipes/+/24460). This would be a smaller setup cost than custom GN build rules.

We have decided to implement this as the easiest and most straightforward solution.

**Comment by keyonghan** [comment]
Confirmed devicelab mac bots are with these packages. E.g. on `mac-25`:
```
flutter@flutter-devicelab-mac-25 ~ % which autoconf
/usr/local/bin/autoconf
flutter@flutter-devicelab-mac-25 ~ % which automake
/usr/local/bin/automake
flutter@flutter-devicelab-mac-25 ~ % which libtool
/usr/bin/libtool
flutter@flutter-devicelab-mac-25 ~ % which pkg-config
/usr/local/bin/pkg-config
```

**Comment by jmagman** [comment]
Once the `libimobiledevice` binaries are rebuilt on a newer version of Xcode than the config is using now, that should give us part of https://github.com/flutter/flutter/issues/69157 for free since release versions of the binaries will contain arm64 and x64.  Which will get us closer to our users not needing to install Rosetta on arm64 macs.

**Comment by keyonghan** [comment]
> Once a bot is configured with these, the recipe can be simplified to simply call:
```
./autogen.sh
./configure --disable-dependency-tracking \
                          --disable-silent-rules \
                          --without-cython \
                          --enable-debug-code \

# Note, using the flag --prefix=$path may allow us to use a custom sysroot

make
```
(See https://flutter-mirrors.googlesource.com/homebrew-flutter/+/refs/heads/master/Formula/libimobiledevice-flutter.rb)

Could you elaborate on this? what repo/source codes are those commands running against? /cc @christopherfujino 
Also the linked url seems broken.

**Comment by keyonghan** [comment]
Never mind, found these are inside the corresponding repos.

**Comment by christopherfujino** [comment]
> Never mind, found these are inside the corresponding repos.

Here are the formulae: https://flutter.googlesource.com/homebrew-flutter/+/refs/heads/master/Formula/

**Comment by christopherfujino** [comment]
Where I got stuck on this last time is that in order to compile, for example, the iproxy target in the libimobiledevice repo, libraries from--for example--libplist must be present on the system in order to dynamically link against. These are the paths that we want to overwrite later, since at runtime we'll be linking against all our dependencies.

The problem is that it won't be present on the libimobiledevice builder. The two solutions I can think of are:

1) install the homebrew versions just so the code will compile
2) merge all the builders into a single libimobiledevice builder and compile the dependency graph from the leaves up, with iproxy last.

**Comment by christopherfujino** [comment]
I believe you can compile the dependencies sequentially in this order:

1. libplist (depended on by libimobiledevice & usbmuxd)
2. libtasn1 (depended on by libimobiledevice)
3. libusb (depended on by usbmuxd)
4. usbmuxd (depended on by libimobiledevice)
5. openssl (depended on by libimobiledevice)

**Comment by keyonghan** [comment]
I am playing around with these repos. As for `libtasn1`, by following: https://flutter.googlesource.com/homebrew-flutter/+/refs/heads/master/Formula/libtasn1-flutter.rb#17, I got below error when `make install`:
```
/bin/sh ../build-aux/ylwrap ASN1.y y.tab.c ASN1.c y.tab.h `echo ASN1.c | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output ASN1.output -- bison -y -Wno-yacc 
/opt/flutter/xcode/13f17a/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison: invalid option -- W
Try `/opt/flutter/xcode/13f17a/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison --help' for more information.
make[3]: *** [ASN1.c] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
```

@christopherfujino Do you know have any insight here?

**Comment by jmagman** [comment]
I bet the Xcode toolchain version of `bison` is too old. On Xcode 13.4 it's 2.3.  Homebrew has 3.8 https://formulae.brew.sh/formula/bison, not sure when the `--warnings` option was introduced.

**Comment by christopherfujino** [comment]
> I bet the Xcode toolchain version of `bison` is too old. On Xcode 13.4 it's 2.3. Homebrew has 3.8 https://formulae.brew.sh/formula/bison, not sure when the `--warnings` option was introduced.

Per the git blame, this flag has been in the makefile since 2019--but yeah, you're probably right.

**Comment by jmagman** [comment]
> Per the git blame, this flag has been in the makefile since 2019--but yeah, you're probably right.

2.3 was released in 2006.

**Comment by keyonghan** [comment]
Thanks for @jmagman @christopherfujino . It is indeed the `bison` too old. With latest 3.8, it works.

Tried the whole process locally, and it went through. A couple of things to note:
- `libusb` is not necessary
- a higher version of `bison` is needed
- `libimobiledevice-glue` is needed to install `libimobiledevice`
- env variables (LIBRARY_PATH, PKG_CONFIG_PATH, PATH) need update

Will work on a recipe to implement the changes.

To clarify, we still want to upload all packages to gcs in corresponding locations as of now, right? /cc @christopherfujino  Now, we are supporting below list based on [gcs](https://pantheon.corp.google.com/storage/browser/flutter_infra_release/ios-usb-dependencies/unsigned?project=flutter-infra&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false):
```
ideviceinstaller
ios-deploy
libimobiledevice
libplist
libzip
openssl
usbmuxd
```

**Comment by christopherfujino** [comment]
> Thanks for @jmagman @christopherfujino . It is indeed the `bison` too old. With latest 3.8, it works.
> 
> Tried the whole process locally, and it went through. A couple of things to note:
> 
> * `libusb` is not necessary
> * a higher version of `bison` is needed
> * `libimobiledevice-glue` is needed to install `libimobiledevice`
> * env variables (LIBRARY_PATH, PKG_CONFIG_PATH, PATH) need update
> 
> Will work on a recipe to implement the changes.
> 
> To clarify, we still want to upload all packages to gcs in corresponding locations as of now, right? /cc @christopherfujino Now, we are supporting below list based on [gcs](https://pantheon.corp.google.com/storage/browser/flutter_infra_release/ios-usb-dependencies/unsigned?project=flutter-infra&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false):

> ```
> ideviceinstaller
> ios-deploy
> libimobiledevice
> libplist
> libzip
> openssl
> usbmuxd
> ```

The tool no longer caches ideviceinstaller, but the others are needed. Note, ios-deploy is already built without homebrew in a separate flow.

**Comment by christopherfujino** [comment]
> * `libusb` is not necessary

I'm pretty sure it is needed; I'm guessing the machine you tried it already had it installed? Just pointing this out in case the final bots these build on are configured differently.

**Comment by godofredoc** [comment]
@keyonghan @christopherfujino can we close this one?

**Comment by keyonghan** [comment]
I have a last piece of related config CL to review: https://flutter-review.googlesource.com/c/infra/+/32821

**Comment by keyonghan** [comment]
Now both the builder and recipes changes have been landed ([a successful build](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/b586899538e8eb1c066e35dec7d517ae26bc95475901b2049aa85f31e3f9db30/+/build.proto))

Closing.

**Comment by jmagman** [comment]
I'm going to reopen this.  While homebrew is no longer a dependency, the library loader paths are incorrect and _still_ point to absolute paths on the luci builder, which is the reason we started this project, see go/flutter-macos-binary-verification

```
$ otool -L flutter/bin/cache/artifacts/usbmuxd/iproxy
flutter/bin/cache/artifacts/usbmuxd/iproxy:
	/opt/s/w/ir/x/w/src/libusbmuxd_install/lib/libusbmuxd-2.0.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/opt/s/w/ir/x/w/src/libimobiledeviceglue_install/lib/libimobiledevice-glue-1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
	/usr/local/opt/libplist/lib/libplist-2.0.3.dylib (compatibility version 7.0.0, current version 7.0.0)
```
These library  must instead be relative to the `loader_path`, not absolute paths from the builders.
https://github.com/flutter/flutter/issues/42969#issuecomment-553225752
https://github.com/flutter/flutter/issues/42969#issuecomment-933725997


Additionally, `libimobiledevice-glue` is the wrong library name, it should be `libimobiledevice-1.0.6.dylib`.
```
dyld[34105]: Library not loaded: '/opt/s/w/ir/x/w/src/libimobiledeviceglue_install/lib/libimobiledevice-glue-1.0.0.dylib'
  Referenced from: '/Users/magder/Projects/flutter/bin/cache/artifacts/usbmuxd/iproxy'
  Reason: tried: '/opt/s/w/ir/x/w/src/libimobiledeviceglue_install/lib/libimobiledevice-glue-1.0.0.dylib' (no such file), '/usr/local/lib/libimobiledevice-glue-1.0.0.dylib' (no such file), '/usr/lib/libimobiledevice-glue-1.0.0.dylib' (no such file)
```

**Comment by jmagman** [comment]
@keyonghan do you want me to file a new issue, or track in this one?  The recipe needs to be updated to patch the relative loader paths, from go/flutter-macos-binary-verification

"After this, the recipe would also have to patch the library links, which this WIP CL implements: [#24460](https://flutter-review.googlesource.com/c/recipes/+/24460). This would be a smaller setup cost than custom GN build rules."

**Comment by keyonghan** [comment]
> "After this, the recipe would also have to patch the library links, which this WIP CL implements: [#24460](https://flutter-review.googlesource.com/c/recipes/+/24460). This would be a smaller setup cost than custom GN build rules."

Is this something you want to continue to work based on https://flutter-review.googlesource.com/c/recipes/+/24460 @christopherfujino ? I may need more time to digest what's needed to implement.

**Comment by keyonghan** [comment]
Tried a bit `install_name_tool` with libplist:
```
install_name_tool -change /Users/swarming/libimobiledevice/libplist_bin/lib/libplist-2.0.3.dylib "@loader_path/../libplist/libplist-2.0.3.dylib"
Usage: /Library/Developer/CommandLineTools/usr/bin/install_name_tool [-change old new] ... [-rpath old new] ... [-add_rpath new] ... [-delete_rpath old] ... [-id name] input
```
What is expected for `input`?

**Comment by jmagman** [comment]
`input` is the path to the binary.

https://github.com/flutter/flutter/issues/42969#issuecomment-933725997 has some details where I ran it locally:

Example:
```
install_name_tool -change "/b/s/w/ir/k/homebrew/opt/libplist-flutter/lib/libplist-2.0.3.dylib" "@loader_path/../libplist/libplist-2.0.3.dylib" iproxy
```

**Comment by keyonghan** [comment]
What would be the artifact used in the ios-usb-dependencies recipes? We have been building several packages:
```
libplist, libtasn1, libusb, usbmuxd, openssl, libimobiledevice
```
Is the artifact same, or different based on the dependencies: https://github.com/flutter/flutter/issues/36019#issuecomment-1155794058?

**Comment by jmagman** [comment]
It's only needed for the binaries that live in the artifacts, the numbers might not match:
```
libimobiledevice-1.0.6.dylib
idevicescreenshot
idevicesyslog
libplist-2.0.3.dylib
libcrypto.1.1.dylib
libssl.1.1.dylib
iproxy
libusbmuxd-2.0.6.dylib
```

**Comment by keyonghan** [comment]
I guess I understand now.

Take `libplist` for example, I tried locally:
```
otool -L libplist-2.0.3.dylib
libplist-2.0.3.dylib:
	/Users/swarming/libimobiledevice/libplist_bin/lib/libplist-2.0.3.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)

install_name_tool -change /Users/swarming/libimobiledevice/libplist_bin/lib/libplist-2.0.3.dylib "@loader_path/libplist-2.0.3.dylib" libplist-2.0.3.dylib

otool -L libplist-2.0.3.dylib
libplist-2.0.3.dylib:
	/Users/swarming/libimobiledevice/libplist_bin/lib/libplist-2.0.3.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```

The output of otool before and after is the same. Is this expected?

**Comment by jmagman** [comment]
Looking at https://github.com/flutter/flutter/issues/42969#issuecomment-933725997 again the list should actually be:
```
idevicescreenshot
idevicesyslog
libcrypto.1.1.dylib
iproxy
```
It's only for binaries where, if you run `otool -l path/to/binary`, `LC_LOAD_DYLIB` is set to an absolute path like:
```
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 104
         name /opt/s/w/ir/x/w/src/libimobiledevice_install/lib/libimobiledevice-1.0.6.dylib (offset 24)
```
Those need to be swapped out for relative paths.

`libplist` doesn't need to be changed because it doesn't have any absolute `LC_LOAD_DYLIB` paths.

**Comment by keyonghan** [comment]
Two more following up questions:
1) with `otool -l libplist-2.0.3.dylib` (instead of `-L`), it also returns something similar
```
Load command 4
          cmd LC_ID_DYLIB
      cmdsize 96
         name /Users/swarming/libimobiledevice/libplist_bin/lib/libplist-2.0.3.dylib (offset 24)
   time stamp 1663878132 Thu Sep 22 13:22:12 2022
      current version 7.0.0
compatibility version 7.0.0
```
shall we do the relative path change?

2) should the relative path change be executed and applied to the binary list on the client bot (user's bot)? The binary path varies from bot to bot and the absolute path is also different: 
devicelab bot: `/Users/swarming/libimobiledevice/libplist_bin/lib/libplist-2.0.3.dylib`
my personal mac: `/opt/homebrew/Cellar/libusbmuxd/2.0.2/lib/libusbmuxd-2.0.6.dylib`

I am trying to understand how the relative path change from package build (from recipes) would affect the user's local binary path.

**Comment by keyonghan** [comment]
I think I mis-understood artifacts/binaries that need the path change. Now it's clear.

Following what's suggested, and also referencing https://flutter-review.googlesource.com/c/recipes/+/24460, I put up https://flutter-review.googlesource.com/c/recipes/+/34240.

Based on LED [build](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/3cf41b302b46c1af78386f4ffbd48e566aaaab926c3ee55d5132c592b359f781/+/build.proto?server=chromium-swarm.appspot.com), corresponding paths are updated to relative ones (check the `*after patch` steps, e.g. [iproxy](https://logs.chromium.org/logs/flutter/led/keyonghan_google.com/3cf41b302b46c1af78386f4ffbd48e566aaaab926c3ee55d5132c592b359f781/+/u/Get_linked_paths_from__opt_s_w_ir_x_w_src_libusbmuxd_output_iproxy_after_patch/stdout))

As for `libimobiledevice-glue` question asked earlier, it is needed to successfully build several packages, and the lib is now uploaded to [GCS](https://pantheon.corp.google.com/storage/browser/flutter_infra_release/ios-usb-dependencies/unsigned/libimobiledeviceglue?project=flutter-infra&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false) as well.

Please let me know if everything looks good now.

**Comment by buraktamturk** [comment]
Arm64 versions of these binaries already available on Homebrew. If Flutter depended on these binaries instead of bringing its own, just like the old versions, it would be arm ready without Rosetta emulation by now.

**Comment by jmagman** [comment]
Flutter set up used to require installing brew and installing these dependencies manually, and then enforced in `doctor`.  It was a mess, people couldn't figure out how to install brew, lots of `PATH` issues, developers bailing on even trying to install Flutter because there were too many installation steps.  A constant source of pain users always complained about (same with CocoaPods now), particularly for new developers.
We started bundling these ourselves in the SDK in 2019 and haven't looked back https://github.com/flutter/flutter/pull/34669

**Comment by christopherfujino** [comment]
I believe after https://flutter.googlesource.com/recipes/+/8597fcfbef6c3953793f60b6ffcfade3dbb03cba this is resolved. That gatekeeper is still not happy is being tracked in https://github.com/flutter/flutter/issues/42969.

**Comment by jmagman** [comment]
I was about to file a Technical Support Incident with Apple, but the relative paths still look incorrect.

When I run `./libimobiledevice/idevicescreenshot` I get:
```$ ./libimobiledevice/idevicescreenshot
dyld[89533]: Library not loaded: '@loader_path/../libimobiledevice-1.0.6.dylib'
  Referenced from: '/Users/m/Projects/flutter/bin/cache/artifacts/libimobiledevice/idevicescreenshot'
  Reason: tried: '/Users/m/Projects/flutter/bin/cache/artifacts/libimobiledevice/../libimobiledevice-1.0.6.dylib' (no such file), '/usr/lib/libimobiledevice-1.0.6.dylib' (no such file)
zsh: abort      ./libimobiledevice/idevicescreenshot
```
`otool -L libimobiledevice/idevicescreenshot` shows:
```
libimobiledevice/idevicescreenshot:
	@loader_path/../libimobiledevice-1.0.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	@loader_path/../libusbmuxd-2.0.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	@loader_path/../libimobiledevice-glue-1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
	@loader_path/../libplist-2.0.3.dylib (compatibility version 7.0.0, current version 7.0.0)
	@loader_path/../libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	@loader_path/../libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
```
But it's missing the subdirectories:
```
	@loader_path/libimobiledevice-1.0.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	@loader_path/../libusbmuxd/libusbmuxd-2.0.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	@loader_path/../libimobiledeviceglue/libimobiledevice-glue-1.0.0.dylib (compatibility version 1.0.0, current version 
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
	@loader_path/../libplist/libplist-2.0.3.dylib (compatibility version 7.0.0, current version 7.0.0)
	@loader_path/../openssl/libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	@loader_path/../openssl/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)1.0.0)
```
I previously thought `@loader_path` was the path to the binary, but it's actually the directory containing the binary.

**Comment by christopherfujino** [comment]
Closing this as finished
