### ISSUE TITLE
 flutter: error MissingPluginException(No implementation found for method signInWithCredential on channel plugins.flutter.io/firebase_auth)

### ISSUE THREAD

**Issue by Palbitiger** [flutter/flutter#36012]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

 not working

```
```

**Comment by BondarenkoStas** [comment]
Duplicate of #28874. @Palbitiger Please try https://github.com/flutter/flutter/issues/28874#issuecomment-486359780.
