### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY :  'package:flutter/src/widgets/viewport.dart': Failed assertion: line 62 pos 15: 'slivers != null': is I/flutter (20340): not true.

### ISSUE THREAD

**Issue by vijayredme** [flutter/flutter#36015]
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (20340): The following assertion was thrown building Scrollable(axisDirection: down, physics:
I/flutter (20340): AlwaysScrollableScrollPhysics, dirty, dependencies: [_InheritedTheme,
I/flutter (20340): _LocalizationsScope-[GlobalKey#609d1], ScrollConfiguration], state: ScrollableState#780e5(position:
I/flutter (20340): ScrollPositionWithSingleContext#d3813(offset: 0.0, range: null..null, viewport: null,
I/flutter (20340): ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics, IdleScrollActivity#a98dc,
I/flutter (20340): ScrollDirection.idle))):
I/flutter (20340): 'package:flutter/src/widgets/viewport.dart': Failed assertion: line 62 pos 15: 'slivers != null': is
I/flutter (20340): not true.
I/flutter (20340): 
I/flutter (20340): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (20340): more information in this error message to help you determine and fix the underlying cause.
I/flutter (20340): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (20340):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (20340): 
I/flutter (20340): When the exception was thrown, this was the stack:
I/flutter (20340): #2      new Viewport (package:flutter/src/widgets/viewport.dart:62:15)
I/flutter (20340): #3      ScrollView.buildViewport (package:flutter/src/widgets/scroll_view.dart:284:12)
I/flutter (20340): #4      ScrollView.build.<anonymous closure> (package:flutter/src/widgets/scroll_view.dart:309:16)
I/flutter (20340): #5      ScrollableState.build (package:flutter/src/widgets/scrollable.dart:584:29)
I/flutter (20340): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
I/flutter (20340): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
I/flutter (20340): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (20340): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #42     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
I/flutter (20340): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #44     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
I/flutter (20340): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #50     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (20340): #51     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (20340): #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (20340): #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (20340): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #82     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (20340): #83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #89     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (20340): #90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #96     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #100    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #101    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #102    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #107    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #108    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (20340): #109    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #114    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #115    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #119    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #120    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #121    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #122    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #124    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (20340): #125    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #128    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #129    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #130    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #133    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (20340): #134    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #136    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (20340): #137    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #138    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #139    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (20340): #140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #142    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (20340): #143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #146    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #147    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #148    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (20340): #149    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #150    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #151    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #153    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #154    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #155    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #156    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #157    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #159    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #160    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #161    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (20340): #162    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #165    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (20340): #166    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #169    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #170    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #171    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #172    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #173    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #174    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (20340): #175    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #176    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #178    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #179    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #180    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (20340): #181    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #182    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #183    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #185    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #186    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #189    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #190    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (20340): #191    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #192    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #193    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #194    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #195    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #196    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #197    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #198    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #199    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #200    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #201    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #202    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (20340): #203    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #204    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #205    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #206    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #207    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #208    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (20340): #209    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (20340): #210    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (20340): #211    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (20340): #212    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (20340): #213    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4659:32)
I/flutter (20340): #214    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter (20340): #215    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (20340): #216    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:607:16)
I/flutter (20340): #217    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (20340): #218    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #219    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #220    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (20340): #221    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (20340): #222    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #223    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #224    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (20340): #225    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (20340): #226    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (20340): #227    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (20340): #228    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #229    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #230    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (20340): #231    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (20340): #232    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (20340): #233    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (20340): #234    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (20340): #235    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (20340): #236    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (20340): #237    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (20340): #238    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
I/flutter (20340): #239    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (20340): #240    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (20340): #241    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (20340): #242    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (20340): #243    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter (20340): #247    _invoke (dart:ui/hooks.dart:219:10)
I/flutter (20340): #248    _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter (20340): (elided 5 frames from class _AssertionError and package dart:async)

**Comment by shihaohong** [comment]
Please provide some more context other than the error message, such as a minimal reproducible sample, as well as some explanation on what kind of issue you're facing. Otherwise, there's not much we can do with just the stack trace. Thank you!
