### ISSUE TITLE
flutter doctor -v

### ISSUE THREAD

**Issue by Palbitiger** [flutter/flutter#36013]
ciao I'm develop some app already but I'm not able to use flutter doctor and others command in the terminal. I'm in the flutter directory. 
some could help please? 
thank you a lot

**Comment by phanirithvij** [comment]
Do you have flutter in your PATH variable?

**Comment by BondarenkoStas** [comment]
@Palbitiger Did you manage to launch it?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
