### ISSUE TITLE
documentation: Please add a sample application like Udacity/Sunshine-App

### ISSUE THREAD

**Issue by MikeMitterer** [flutter/flutter#3602]
Here is the Sunshine-App (Java-Version)
https://github.com/udacity/Sunshine-Version-2

This little app uses some nice features like Preferences, SQLite / ContentProvider, Map-Intent, Services aso. If we have an equivalent in Dart, running on Android and iOS people can compare the Java-version and the Dart-version and hopefully!!! see how great Dart is. 

I would have made such a sample app by my own but at the moment the documentation for Flutter is really poor - so the effort is to high for me. But if the Dart-Team could provide such an App it could be used AS documentation for the following Apps...

**Comment by sethladd** [comment]
Thanks! That app example is a good set of features and requirements. We'll likely need to create a list of child feature issues (e.g. maps, sqlite, etc). Some of these issues exist, and help is definitely appreciated to list out the specific features Flutter would need to implement/expose to enable a Sunshine-App.

**Comment by MikeMitterer** [comment]
Thanks @sethladd, it's too bad - I thought I could use Flutter for my upcoming Android-App. Anyway - maybe I can use it for the next one.

**Comment by eseidelGoogle** [comment]
FYI @mit-mit we probably want to expand hello_services to be a bit more sophisticated like this over time.

**Comment by sethladd** [comment]
We hope to see more full examples and samples over time. I'm going to close this but yes, we're working towards allowing you to build this sample. The interop/plugins/services work is cranking along. Thanks for your feedback and interest!
