### ISSUE TITLE
How to add more delicate partition lines

### ISSUE THREAD

**Issue by shanzhenghan** [flutter/flutter#36031]
How to add more delicate partition lines？
Setting it to 1 feels a bit rough, set it to 0.5, and found that it has not become thinner, no change.
Is there a solution?   for example:Divider()

**Comment by rami-a** [comment]
I believe if you use `Divider` as it is right now you get a hairline (1 device pixel thin) line. This #38621 adds the ability to customize the thickness of Dividers to your liking.
