### ISSUE TITLE
API docs missing a property page

### ISSUE THREAD

**Issue by sfshaza2** [flutter/flutter#36036]
As of the most recent update (today), the website build is failing due to a property page that is missing:

https://api.flutter.dev/flutter/widgets/Icon/icon.html

**Comment by dnfield** [comment]
This could be related to my attemt to manually push the docs...

**Comment by shihaohong** [comment]
It seems that replacing lowercase `i` with uppercase `I` in icon works for some reason...
`https://api.flutter.dev/flutter/widgets/Icon/Icon.html`
instead of `https://api.flutter.dev/flutter/widgets/Icon/icon.html`

**Comment by chunhtai** [comment]
I can see the page now, is this issue resolved?

**Comment by dnfield** [comment]
@tvolkert rolled us back, but that reintroduced thebobj doc issue

**Comment by tvolkert** [comment]
Should we close this issue and re-open the objc doc one?
