### ISSUE TITLE
Got Socket Error Issue

### ISSUE THREAD

**Issue by hashweather** [flutter/flutter#36042]
Hello guys I have spent the past 5 hours trying to get packages from flutter with futile efforts. I keep getting "Got socket error trying to find package xxx in https://pub.dartlang.org" in Android studio.Before now I was able to get packages without any issues, I wonder what changed. I am running on Ubuntu OS and from Nigeria operating under a very strong network connection . Please help. Thanks

**Comment by BondarenkoStas** [comment]
It may be connected with #1989.
@hashweather Please try https://stackoverflow.com/a/57642636.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
