### ISSUE TITLE
Run AOT builds on the bots

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#3604]
The ahead-of-time compilation process on Android and iOS needs to tell gen_snapshot where to find various core Dart packages.  The specifics of how to do this depend on some implementation details of the engine.

The build bots should try building a Flutter app with AOT to verify that the tools aren't out of sync with the engine.

**Comment by eseidelGoogle** [comment]
Do we do this now?  @yjbanov

**Comment by yjbanov** [comment]
Yep.
