### ISSUE TITLE
google_sign_in issue: PlatformException(sign_in_required, com.google.android.gms.common.api.ApiException: 4: 4: , null))

### ISSUE THREAD

**Issue by nszeitli** [flutter/flutter#36041]
Hi guys trying to configure a simple google sign in using firebase and following the google android documentation. We are talking vanilla build of exactly the same code as the official example here: https://github.com/flutter/plugins/blob/master/packages/google_sign_in/example/lib/main.dart

I have read 10+ threads on this issue and tried these solutions so far:

1. Deleted keystore and created new SHA1, uploaded to firebase.
2. Checked that SHA1 of the apk matches firebase
3. Ensure support email is attached to firebase project.
4. Under integration tab in firebase google play is linked (not the app though because this is just an example not a release )
5. Added OAuth consent screen under google api console.
6. Tried different emulators, different API versions and made sure that Play Services was upto date.
7. Tried many different gradle versions that apparently worked for some people such as 

-     classpath 'com.android.tools.build:gradle:3.2.1'
-     classpath 'com.google.gms:google-services:4.2.0'
-     implementation 'com.google.firebase:firebase-core:16.0.9' under dependencies
-     apply plugin: 'com.google.gms.google-services' on the end of the file.

Rain hail or shine all I get is this:
![image](https://user-images.githubusercontent.com/20551368/61102810-d408ef00-a4b2-11e9-9545-27d0a2f95740.png)

## Steps to Reproduce

1. New flutter build as per https://github.com/flutter/plugins/blob/master/packages/google_sign_in/example/lib/main.dart
2. Setup firebase as per google docs

## Logs
Verbose log here: https://pastebin.com/3GVuWJQR

## Flutter Doctor
D:\flutter_projects\test_login>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.7.8+hotfix.2, on Microsoft Windows [Version 10.0.17134.885], locale en-AU)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.36.1)
[√] Connected device (1 available)

• No issues found!

Any help would be much appreciated, cant believe setting up a single login button is taking days of work.

## Update

Tried again with different machine and different google account. Exactly the same result. Commented out _googleSignIn.signInSilently(); which let me click the "Sign In" button. Sign in button instantly crashed the app but googling the crash error pointed me towards a fix for an androidX bug which can be resulved by pasting:

android.enableJetifier=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx1536M

into gradle.properties.

After applying this fix I was able to select my login account after clicking the button and after I did so I now get another PlatformException, except this time its the infamous 12500:  PlatformException(sign_in_required, com.google.android.gms.common.api.ApiException: 12500 , null)).

Not sure whats going on here but smells like androidX related issue?

**Comment by john-ravi** [comment]
**RESOLVED**: Apparently we need to save some/no info at "Oauth consent screen". Detailed Explaination @
https://github.com/flutter/flutter/issues/33393#issuecomment-510395178

**Comment by john-ravi** [comment]
Please update docs https://pub.dev/packages/firebase_auth

**Comment by nszeitli** [comment]
Resolved by filling out all OAuth consent screen fields. Thanks to all!

**Comment by sahanpasindu** [comment]
I followed those all steps, but nothing was worked.

**Comment by saurabh-619** [comment]
Yeah, that error was tormenting too, Then instead of using F5 I used ctr+F5 to debug apk in VS Code and vola my problem was solved.
