### ISSUE TITLE
Programmatically getting the data of a Firebase Dyamic Link

### ISSUE THREAD

**Issue by IonelLupu** [flutter/flutter#36056]
## Use case

I am sending Push Notifications to users that contain some custom data. One of the fields inside that custom data is a dynamic link. I would like to use the [Firebase Dynamic Liks ](https://pub.dev/packages/firebase_dynamic_links) plugin to get the real link value programmatically and then use that to change the screens in the app.

Example of push notification custom data:
```dart
final pnCustomData = {
    "dynamicLink": "my-app.page.link/6LnV" // the real link for the Android app is `/settings`
} // this will inside the push notification payload
```

## Proposal

I was thinking to add a method inside `FirebaseDynamicLinks.instance` to get the link's data based on the URL, something like this:
```dart
final url = pnCustomData['dynamicLink'];
final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.getLink(url);
```

## Current behavior
Right now I can get the Dynamic Link data ONLY IF the user opened such a link from another app using:
```dart
final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.retrieveDynamicLink();
```

**Comment by benjwilson10** [comment]
I am also interested in this functionality. I am getting the raw link from a qr-code reader inside the app, and need to able to decode it to the original. I believe iOS had a function called handleUniversalLink which did the same thing.

**Comment by kroikie** [comment]
@IonelLupu

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/356. Any further collaboration will be done there.
