### ISSUE TITLE
Dart 1.16 is now released. Upgrade Flutter's dep ?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3605]
Looks like Flutter is still downloading a dev version of 1.16. We might want to upgrade our downloaded dart sdk to 1.16.

Thanks!

**Comment by abarth** [comment]
Sure.

**Comment by alokrawatt** [comment]
`Flutter upgrade` isn't updating the SDK to 1.16.0
current version installed -1.12.13+hotfix.9.
