### ISSUE TITLE
Flutter run not working on real device

### ISSUE THREAD

**Issue by OnlineProjectsCloud** [flutter/flutter#36061]
I have configured everything, enabled debug mode on my android device, however, when I do `flutter run` this is the output.
```
Launching lib/main.dart on SUNSET2 in debug mode...
Initializing gradle...                                              1,9s
Resolving dependencies...                                           6,7s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         4,4s
Built build\app\outputs\apk\debug\app-debug.apk.
```
And it opens the aplication on the device and then closes immediately. I then tried `flutter attach`, but it stops with this message `Waiting for a connection from Flutter on SUNSET2...`. The device does appear on `flutter devices`. What is going on?

**Comment by BondarenkoStas** [comment]
@OnlineProjectsCloud did you find a solution?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
