### ISSUE TITLE
flutter 1.7.8+hotfix.3 | base.apk!/lib/arm64-v8a,  couldn't find "libopencv_java.so"

### ISSUE THREAD

**Issue by puneetsdsharma65** [flutter/flutter#36063]
after update, I am getting following error:

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.iparse.downeast-AbPvWf6NJB5l665u3EZ8fg==/base.apk"],nativeLibraryDirectories=[/data/app/com.iparse.downeast-AbPvWf6NJB5l665u3EZ8fg==/lib/arm64, /data/app/com.iparse.downeast-AbPvWf6NJB5l665u3EZ8fg==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libopencv_java.so"
W/System.err(  656):    at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
W/System.err(  656):    at java.lang.System.loadLibrary(System.java:1669)
W/System.err(  656):    at org.opencv.android.StaticHelper.loadLibrary(StaticHelper.java:54)
W/System.err(  656):    at org.opencv.android.StaticHelper.initOpenCVLibs(StaticHelper.java:85)
W/System.err(  656):    at org.opencv.android.StaticHelper.initOpenCV(StaticHelper.java:29)
W/System.err(  656):    at org.opencv.android.OpenCVLoader.initDebug(OpenCVLoader.java:51)
W/System.err(  656):    at com.iparse.plugin.md.uftmd.UftMdPlugin.onMethodCall(UftMdPlugin.java:76)
W/System.err(  656):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
W/System.err(  656):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
W/System.err(  656):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
W/System.err(  656):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(  656):    at android.os.MessageQueue.next(MessageQueue.java:326)
W/System.err(  656):    at android.os.Looper.loop(Looper.java:160)
W/System.err(  656):    at android.app.ActivityThread.main(ActivityThread.java:6718)
W/System.err(  656):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(  656):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err(  656):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
D/OpenCV/StaticHelper(  656): First attempt to load libs fails

how to fix this issue
![Screen Shot 2019-07-15 at 11 36 58 AM](https://user-images.githubusercontent.com/20636902/61197966-233e6200-a6f5-11e9-86da-73901e66737f.png)

Thanks

**Comment by tvolkert** [comment]
@puneetsdsharma65 are you using Flutter in an add-to-app scenario (where you had an existing Android app to which you're adding Flutter)?  Which plugins are you using?

**Comment by puneetsdsharma65** [comment]
@tvolkert Thanks for helping me.
Yes, I have one android app and I am adding in flutter.
In my android app, I am using **compile 'org.opencv:OpenCV-Android:3.1.0'** as dependency.
I have created .aar file of android library and added in flutter(flutterproject->android>src->libs->myaar.aar).

Thanks

**Comment by puneetsdsharma65** [comment]
I have changed .aar file, which is 64 bit supported.
Now issue is fixed
