### ISSUE TITLE
image picker should be able to return a lower resolution JPEG

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#36072]
The image picker plugin currently returns the original resolution. It will be valuable to add a new feature to return an image with custom resolution if the picked image is a JPEG.

For reference: there was an attempt to do so in https://github.com/flutter/plugins/pull/855

**Comment by bhurlbert** [comment]
@cyanglaz  - If I understand what you mean here, you can use the **maxHeight**, **maxWidth** _props_ and it will reduce the image _size_ and _resolution_ then it can be used in the app. For example...
```
await ImagePicker.pickImage(
          source: ImageSource.camera, 
          maxHeight: 450.0, 
          maxWidth: 450.0);
```
Hope that helps

**Comment by cyanglaz** [comment]
@bhurlbert Thanks for the recommendation. I was talking about reducing the resolution without changing the size. JPEG image can usually be configured (on both Android and iOS) to reduce the "quality"

**Comment by AmolGangadhare** [comment]
@cyanglaz compressing the image with BitMapFactory(for android) can solve this. It will reduce the quality of the image. Is this change already done?

**Comment by cyanglaz** [comment]
@AmolGangadhare The PR listed in the OP is trying to solve it with the BitMapFactory on android, but the original author doesn't have time to work on it anymore.

**Comment by AmolGangadhare** [comment]
@cyanglaz i can spend some time to this, if you don't mind, may I make a fresh PR to this ?

**Comment by cyanglaz** [comment]
@AmolGangadhare That'd be awesome! Thanks! Please keep me updated if you don't mind!

**Comment by AmolGangadhare** [comment]
@cyanglaz sure, I'll keep you updated with it. Thanks

**Comment by AmolGangadhare** [comment]
@cyanglaz Hi, please refer flutter/plugins/pull/1896 for the changes. Thanks

**Comment by cyanglaz** [comment]
Thanks to @AmolGangadhare's PR https://github.com/flutter/plugins/pull/1896. This new feature is added in 0.6.1. I am closing this issue now.
