### ISSUE TITLE
TabView pages do not retain scroll position

### ISSUE THREAD

**Issue by nodinosaur** [flutter/flutter#36073]
https://gist.github.com/nodinosaur/8b20b3247c7a7d92b1848ebdcb31af62

Individual pages do not retain their scroll position.
#### Steps to reproduce:

1. Scroll down any of the lists
2. tap tab or swipe across to another list
3. notice that the list in view does not show top item
4. scroll downwards on that list resets position on all other lists 

According to @efortuna in her fun video I should be implementing `PageStorageKey`
https://youtu.be/kn0EOS-ZiIc?t=502 (_Which I do_)

https://api.flutter.dev/flutter/widgets/PageStorageKey-class.html 

the source for this demonstration is an adaption of the sample code in: 
[NestedScrollView-class.html](https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html)

#### Second file `nested_scroll_error2.dart`
Same example as before but uses [SliverOverlapAbsorber] && [SliverOverlapInjector]
App bar behaviour is not correct and does not follow the examples demonstrated: 
[SliverAppBar-class.html](https://api.flutter.dev/flutter/material/SliverAppBar-class.html)
But scroll positions appear to be retained
## Logs

```
no logs produced
```

```
no analysis errors
```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F203, locale en-GB)
    • Flutter version 1.7.8+hotfix.3 at /Users/george.medve/flutter-sdk/flutter
    • Framework revision b712a172f9 (3 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/george.medve/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/george.medve/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.0

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 73B49ADA-247C-4B6F-968D-3CE2D51489F4 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by hermitdave** [comment]
This is indeed very strange issue. Tabview content should never have their scroll viewers linked.

**Comment by johnpryan** [comment]
For what it's worth, the sample code in [NestedScrollView](https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html) is working. 

I'm not sure exactly what the problem is, but the first snippet in the gist doesn't use SliverOverlapAbsorber or NestedScrollView.sliverOverlapAbsorberHandler, and the second sample uses sliverOverlapAbsorberHandler in two separate places.

**Comment by nodinosaur** [comment]
Hi @johnpryan,

Thanks for your input. 

You mentioned that the [second Gist](https://gist.github.com/nodinosaur/8b20b3247c7a7d92b1848ebdcb31af62#file-nested_scroll_error2-dart) uses `NestedScrollView.sliverOverlapAbsorberHandleFor(context)` in two places, but so does the example in [NestedScrollView-class.html](https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html).

The issue here being that the scroll behaviour is _correct_ (positions are retained), but the `SliverAppBar`'s `floating`,`snap`,`pinned` parameters does not behave as expected.

The [first Gist](https://gist.github.com/nodinosaur/8b20b3247c7a7d92b1848ebdcb31af62#file-nested_scroll_error-dart), has the desired app bar behaviour, but the individual page scroll positions are not retained.

I hope this is clearer?

Thanks

**Comment by johnpryan** [comment]
I think the best way to track down the issue would be to find the simplest change that can be made NestedScrollView example that causes this behavior. The two gists are helpful but it's unclear what specific change causes the example to break.

**Comment by nodinosaur** [comment]
Any progress on a fix for this?
(cc. @johnpryan)

Cheers

**Comment by escamoteur** [comment]
double of https://github.com/flutter/flutter/issues/40740 vote that issue
