### ISSUE TITLE
The first run of adb should also catch ProcessException

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#36074]
Here: https://github.com/flutter/flutter/blob/v1.7.8-hotfixes/packages/flutter_tools/lib/src/android/android_device.dart#L615

In addition to `ArgumentError`, `ProcessException` is also showing up in crash reports from analytics.

So far this is 1.7% of tool crashes in 1.7.8+hotfix.3. It was 2.43% of crashes in the previous stable release.

**Comment by Hixie** [comment]
Do we know what is causing ProcessException to fire in these cases? (Or ArgumentError for that matter; catching an ArgumentError seems odd.)

Since this is less common now than before (or likely as common, within the error bars), downgrading from blocker.

**Comment by zanderso** [comment]
We'll get a `ProcessException` for example if adb is not in the right place or the user doesn't have execute permissions on it. We should consider moving these sorts of installation checks to a doctor.

**Comment by blasten** [comment]
This was already fixed in https://github.com/flutter/flutter/blob/30aef0a3b9611763f8e60985e7cca9cb30c1ea6a/packages/flutter_tools/lib/src/android/android_device_discovery.dart#L71
