### ISSUE TITLE
Flutter doctor android studio validator fails to locate NDK, dart/flutter plugins

### ISSUE THREAD

**Issue by ohir** [flutter/flutter#36075]
[Related #27338, #26928]
Something is f-p with doctor detection again. Ndk is up-to date, plugins recently updated but doctor barks on it. SDK I could set manually with 
```
flutter config --android-studio-dir /testbed/opt/Android/android-studio
flutter config --android-sdk $ANDROID_SDK_ROOT
```
But there is no manual option for NDK nor plugins. Not to mention that either we need to tell users to set it manually or autodetection code needs an overhaul. Eg. it still uses log deprecated ANDROID_HOME (no time to inspect further).
So, now doctor -v output just can not be trusted, and I think that may badly affect bug reporting too. Not to mention confusion to many new users that are trying to do voo-doo with complete reinstalls.

>    • Android NDK location not configured (optional; useful for native profiling support)

```
cat /testbed/opt/Android/Sdk/ndk-bundle/source.properties
Pkg.Desc = Android NDK
Pkg.Revision = 20.0.5594570
```

> ✗ Flutter plugin not installed; this adds Flutter specific functionality.
✗ Dart plugin not installed; this adds Dart specific functionality.

These are not only only installed but also working.
```
% find ~/.AndroidStudio3.4/config/plugins -name "flutter-intellij*.jar" -o -name "Dart*.jar"
/testbed/utest7/.AndroidStudio3.4/config/plugins/Dart/lib/Dart.jar
/testbed/utest7/.AndroidStudio3.4/config/plugins/flutter-intellij/lib/flutter-intellij.jar
```

**Important** my setup peculiarity: Studio config dirs are symlinked.
Nonetheless seems so doctor is expecting "click-thru-install" locations of many things.
On other user desktop with "click-thru" and same AS/SDK (no NDK) doctor "finds" things seamlessly.

``` 
-----------
% flutter doctor -v
[✓] Flutter (Channel master, v1.8.1-pre.2, on Linux, locale pl_PL.utf8)
    • Flutter version 1.8.1-pre.2 at /testbed/opt/flutter
    • Framework revision 1a374d820d (11 days ago), 2019-07-01 16:17:11 -0700
    • Engine revision 45b66b722e
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /testbed/opt/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /testbed/opt/Android/Sdk
    • ANDROID_SDK_ROOT = /testbed/opt/Android/Sdk
    • Java binary at: /testbed/opt/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find chrome executable at google-chrome)
    ! CHROME_EXECUTABLE not set

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 3.8.0
    • GNU Make 4.0

[!] Android Studio
    • Android Studio at /testbed/opt/Android/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = /testbed/opt/Android/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Connected device (2 available)
    • Linux  • Linux  • linux-x64      • Linux
    • Chrome • chrome • web-javascript • unknown (unsupported)

! Doctor found issues in 2 categories.

-----
env | egrep $MOBI:
ANDROID_HOME=/testbed/opt/Android/Sdk
ANDROID_SDK_ROOT=/testbed/opt/Android/Sdk
ANDROID_NDK_ROOT=/testbed/opt/Android/Sdk/ndk-bundle
STUDIO_JDK=/testbed/opt/Android/android-studio/jre
FLUTTER_HOME=/testbed/opt/flutter
FLUTTER_ROOT=/testbed/opt/flutter

-----
# AS version
jq '.version, .buildNumber' /testbed/opt/Android/android-studio/product-info.json
"3.4.1"
"5522156"
```

```

**Comment by cyanit** [comment]
Still having trouble after moving SDKs to a centralised location (/home/username/Development/SDKs), dart, flutter and android are just not working.

Set the path variables in by .batchrc and it still does not work, although it should.
Also tried setting the Android Atudio location as suggested by the verbose output, still the same.

![flutterproblem2](https://user-images.githubusercontent.com/26248671/70543342-8af4be00-1b6a-11ea-9e2a-599138e890b8.png)

<pre><font color="#859900"><b>leo@pentacon</b></font>:<font color="#268BD2"><b>~</b></font>$ flutter doctor -v
<font color="#859900">[✓]</font> Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_US.UTF-8)
<b>    </b><font color="#859900"><b>•</b></font><b> Flutter version 1.9.1+hotfix.6 at /home/leo/Development/SDKs/flutter</b>
<b>    </b><font color="#859900"><b>•</b></font><b> Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700</b>
<b>    </b><font color="#859900"><b>•</b></font><b> Engine revision b863200c37</b>
<b>    </b><font color="#859900"><b>•</b></font><b> Dart version 2.5.0</b>

<font color="#DC322F">[✗]</font> Android toolchain - develop for Android devices
<b>    </b><font color="#DC322F"><b>✗</b></font><b> ANDROID_HOME = /home/leo/Development/SDKs/Android/Sdk</b>
<b>      but Android SDK not found at this location.</b>

<font color="#859900">[✓]</font> Android Studio (version 3.5)
<b>    </b><font color="#859900"><b>•</b></font><b> Android Studio at /home/leo/.local/Android Studio/android-studio</b>
<b>    </b><font color="#859900"><b>•</b></font><b> Flutter plugin version 42.0.1</b>
<b>    </b><font color="#859900"><b>•</b></font><b> Dart plugin version 191.8593</b>
<b>    </b><font color="#859900"><b>•</b></font><b> Java version OpenJDK Runtime Environment (build</b>
<b>      1.8.0_202-release-1483-b49-5587405)</b>

<font color="#B58900">[!]</font> Android Studio
<b>    </b><font color="#859900"><b>•</b></font><b> Android Studio at /home/leo/.AndroidStudio3.5</b>
<b>    </b><font color="#DC322F"><b>✗</b></font><b> Flutter plugin not installed; this adds Flutter specific functionality.</b>
<b>    </b><font color="#DC322F"><b>✗</b></font><b> Dart plugin not installed; this adds Dart specific functionality.</b>
<b>    </b><font color="#DC322F"><b>✗</b></font><b> android-studio-dir = /home/leo/.AndroidStudio3.5</b>
<b>    </b><font color="#DC322F"><b>✗</b></font><b> Unable to find bundled Java version.</b>
<b>    </b><font color="#859900"><b>•</b></font><b> Try updating or re-installing Android Studio.</b>
<b>    </b><font color="#859900"><b>•</b></font><b> Consider removing your android-studio-dir setting by running:</b>
<b>      flutter config --android-studio-dir=</b>

<font color="#859900">[✓]</font> VS Code (version 1.40.2)
<b>    </b><font color="#859900"><b>•</b></font><b> VS Code at /usr/share/code</b>
<b>    </b><font color="#859900"><b>•</b></font><b> Flutter extension version 3.7.0</b>

<font color="#B58900">[!]</font> Connected device
<b>    </b><font color="#B58900"><b>!</b></font><b> No devices available</b>
</pre>

Is there anything I could have done wrong in the process of moving the SDKs?
The point of doing this was to have them less scattered around and make maintenance easier, not more difficult.

-----------------
OS: Pop!OS 19.10 x64 (Basically Ubuntu)
Main IDE: Android Studio 3.5

**Comment by szekelyisz** [comment]
Still having this issue:

```
szabi@neo:~/android-studio/bin$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.2, on Linux, locale en_CA.UTF-8)
    • Flutter version 1.22.2 at /home/szabi/snap/flutter/common/flutter
    • Framework revision 84f3d28555 (4 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/szabi/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/szabi/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /home/szabi/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • ONEPLUS A6013 (mobile) • acd40725 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

However:

![image](https://user-images.githubusercontent.com/14320241/96522740-0f5fa500-1242-11eb-8874-edbc66257d8f.png)

This is a fresh install of Flutter & AS.

**Comment by elliotops** [comment]
szekelyisz / same here, new machine, fresh install-- have you solved it ?

**Comment by elliotops** [comment]
if you're still stuck, i found info here: 
https://stackoverflow.com/questions/64395106/update-to-android-studio-4-1-flutter-plugin-and-dart-plugin-not-installed

**Comment by danagbemava-nc** [comment]
Given that there hasn't been any activity on this issue in close to 2 years and the tool has gone through quite a lot of changes in that period, I'll be closing this issue as stale. 

If anyone is still facing this issue, kindly file a new issue and provide the relevant steps/information required to reproduce the bug. 

Thank you
