### ISSUE TITLE
Feature Request: specify flutter SDK version range in pubspec

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#36077]
## Use case
When new versions of `beta` contain breaking changes, package maintainers may want to prepare for when `beta` becomes `stable` by publishing two versions of their package ([example](https://github.com/johnpryan/flutter_map/issues/352)). It is currently difficult to do this because it involves manually communicating which version of their package is compatible with each SDK channel.

## Proposal
Allow package maintainers to specify a Flutter SDK version in the pubspec. This would allow package maintainers to support developers using the `stable` and `beta` channel simultaneously, and avoid confusion when `beta` becomes `stable`. 

For example, package `foo` could publish version `1.0.0` compatible with Flutter SDK `>=1.5.0 <1.7.0` and version `2.0.0` compatible with Flutter SDK `>=1.7.0 <1.8.0`. This would allow users to run `flutter packages get` and get version of `foo` compatible with their SDK.

The `sdk` field in the pubspec could be re-purposed to indicate a version range:

```yaml
dependencies:
  flutter:
    sdk: ">=1.7.0 <1.8.0"
```

**Comment by christopherfujino** [comment]
This has been implemented.
