### ISSUE TITLE
Investigate ungraceful failed hot restart request from daemon

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#36070]
Analytics is reporting a high incidence of crashes from the hot restart requests coming from the daemon here: https://github.com/flutter/flutter/blob/v1.7.8%2Bhotfix.3/packages/flutter_tools/lib/src/commands/daemon.dart#L874

As discussed here: https://github.com/flutter/flutter/pull/35846#discussion_r302781867

Please investigate.

So far this is 9.4% of tool crashes in 1.7.8+hotfix.3. This crash was not present in the last stable release.

**Comment by jonahwilliams** [comment]
I think we should capture some more data from this particular exception too. So far, I'm including the device type.
