### ISSUE TITLE
Pod compilation errors in Obj-C enabled project with Flutter_TTS and Flutter_Twitter_Login

### ISSUE THREAD

**Issue by MsXam** [flutter/flutter#36081]
## 🐛 Bug Report

When adding flutter_tts and flutter_twitter_login to an objective-c enabled flutter project we get compiler issues.

### Expected behavior
Adding flutter_tts on its own works without issue & there is no need to create a swift enabled project. 

Just need to ensure : 

- create standard flutter project (dont add -i swift)
- use_frameworks!
- specify swift_version = 4
- add a swift file to the project that will also create the bridging header file.
- then  add flutter_tts to your pubspec.yaml file

### Reproduction steps
 Follow the steps above to add flutter_tts to your Obj-c flutter project.  Now add flutter_twitter_login (https://pub.dev/packages/flutter_twitter_login) and ensure in your podfile you set podfile:ios, '11'

do a pod deintegrate and then flutter clean, followed by flutter pub get and finally a pod install.
Ensure one of your files (say main) imports from flutter_twitter_login.

This will install the flutter_twitter_login.

### Compiler errors

When you try and run, you will get lots of compiler issues - a snapshot is shown here  - the issue appears to be one of linking whereby the header files are not found. Perhaps there is something we are missing in our Podfile to enable this as a target activity ?

### Podfile
![podfile](https://user-images.githubusercontent.com/18722796/61147142-936d9d80-a4d3-11e9-80e1-e5fb5ab73791.png)

> /Users/xamgea/workspace/_projects/uajsh/ios/Pods/Protobuf/objectivec/google/protobuf/Wrappers.pbobjc.m:17:10: warning: non-portable path to file '<protobuf/Wrappers.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
>      #import <Protobuf/Wrappers.pbobjc.h>
>              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
>              <protobuf/Wrappers.pbobjc.h>
>     1 warning generated.
>     /Users/xamgea/.pub-cache/git/flutter_twitter_login-04b9d63fe6217cebf8c97f0ccf41719d44554c70/ios/Classes/TwitterLoginPlugin.m:2:9: fatal error: 'TwitterKit/TwitterKit.h' file not found
>     #import <TwitterKit/TwitterKit.h>
>             ^~~~~~~~~~~~~~~~~~~~~~~~~
>     1 error generated.
> Could not build the application for the simulator.
> Error launching application on iPhone Xs.
> 

### Flutter Doctor

[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-GB)
    • Flutter version 1.7.8+hotfix.3  
    • Framework revision b712a172f9 (3 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at  
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • XamGap iPhone • 88a18410346ac8a86bd9cb1f76ef1350e39ece81 • ios • iOS 12.3.1
    • iPhone Xs              • 9FAE28A0-ABB6-42C3-A6C2-146E7172D79D     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

**Comment by BondarenkoStas** [comment]
@MsXam Did you manage to solve the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by MsXam** [comment]
@iapicca Really unsure what information you are requesting as I provided a reproducible test case approx 5 months ago and believe I was thorough in the repeatable steps. To avoid any ambiguity , no we have not managed to resolve this and the issue and errors we get only occurs with an OBJ-C project.

You can easily reproduce the same by just creating the same platform project and adding the two plugins mentioned.

**Comment by iapicca** [comment]
Hi @MsXam 
If you are still experiencing this issue 
with the latest version of Flutter
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose` (or `flutter build --verbose`)?
Also note that the aforementioned plugins [ [flutter_tts](https://pub.dev/packages/flutter_tts),  [flutter_twitter_login](https://pub.dev/packages/flutter_twitter_login)] are 3rd party.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
