### ISSUE TITLE
(Re)enable fixed lints in `flutter_analysis_options`.

### ISSUE THREAD

**Issue by pq** [flutter/flutter#3608]
Tracking bug for updating `flutter_analysis_options` to re-enable lints whose blocking bugs have been fixed.

* [x] `avoid_as` (https://github.com/dart-lang/linter/issues/195)
* [x] `avoid_return_types_on_setters` (https://github.com/dart-lang/linter/issues/202)

cc @Hixie 

On deck (next `DEV` build):

* [x] `one_member_abstracts` --- new "//ignore" syntax  (https://github.com/dart-lang/linter/issues/203; https://github.com/dart-lang/sdk/issues/26181)

**Comment by abarth** [comment]
I have a patch for the `avoid_as` part.

**Comment by pq** [comment]
Regarding `one_member_abstracts`, we have one offender in `examples/flutter_gallery/lib/gallery/syntax_highlighter.dart`:

```
abstract class SyntaxHighlighter {
  TextSpan format(String src);
}
```

A few thoughts:

1. change this to a typedef a la the style guide's [suggestion](https://www.dartlang.org/effective-dart/design/#types) (like `typedef TextSpan SyntaxHighlighter(String src)`), or:
2. add an "ignore" to this class because it's OK

If we choose option 2, we might consider whether this rule is adding value and remove it from our list of lints.

Paging @HansMuller and @Hixie for thoughts!

**Comment by sethladd** [comment]
cc @vlidholt

**Comment by Hixie** [comment]
As a general rule the lint is reasonable, I think. It has more false positives than others, but it's not that common and it definitely deserves consideration whenever it happens. When I last tried turning this lint on, I did convert at least one case to a function because that was better.

I think this case is an example where a callback makes more sense than a class, since these objects are always going to be stateless as far as I can tell.

**Comment by vlidholt** [comment]
I think there are valid cases where an abstract class can have only one method. For instance, sub classes may want to add more methods, or configuration options. In this case, the subclass has configurations for choosing custom colors etc.

**Comment by pq** [comment]
> I think there are valid cases where an abstract class can have only one method. 

I agree.  This lint has always been a bit borderline.  That said, my experience lines up with @Hixie that it can be the start of a useful conversation **_especially_** for folks coming to Dart from languages that don't have closures as an option.

PS: I realize I said "offender" above...  Sorry if that sounded judgmental! 😉

**Comment by pq** [comment]
Re-enabled `one_member_abstracts` w/ d406bb9.
