### ISSUE TITLE
Considering a `flutter dart` wrapper that ensures I'm using Flutter's Dart

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3609]
In a world where there are many Darts, I want to ensure I'm using my Flutter's Dart. One way to do this: provide a wrapper entry script, something like `flutter dart`.

Otherwise, I have two Darts on my PATH and things get weird.

There may be other ways to fix this, but if we can provide our users a very solid way to ensure they are using the same Dart that is embedded into Flutter Shell and is used by the Flutter tool, we've reduced a variable.  (use case: running tests on the command line that don't require Flutter Shell, or ONLY installing Flutter and wanting to run some scripts with Flutter's blessed Dart)

**Comment by eseidelGoogle** [comment]
We have some of this for `flutter packages get`.  Unclear if we still need the general `flutter dart`?

**Comment by sethladd** [comment]
The risk is that a user may have multiple versions of Dart, and may be running their tests in a Dart that isn't the same Dart as Flutter has. But, even if we had a `flutter dart` the user could still accidentally run the wrong Dart.

I'll close this for now.
