### ISSUE TITLE
Multiple "Image" classes is confusing

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#361]
There's one Image class in flutter/lib/src/widgets/basic.dart
There's another Image class in dart:ui.

The first wraps the second.

Since I just spent an hour sorting this problem, it seems that overloading this class name will cause others confusion too.

**Comment by abarth** [comment]
We should probably rename the one in dart:ui to have a more decorated name...  Maybe DecodedImage?

**Comment by jimbeveridge** [comment]
+1 for DecodedImage.
