### ISSUE TITLE
Problem when i lock the orientation of the device and then try to initialize the camera

### ISSUE THREAD

**Issue by gabrielchaves7** [flutter/flutter#36101]
First of all sorry for my english.
When I let the phone on landscape left and then call a new page (locked on landscape left and openned by navigator push), that show a camera preview, the controller.initialize of the camera never complete.
The first image shows the page (without locked orientation) that call the page with camera preview (with locked orientation on landscape left). Anyone knows what can cause this?

![Captura de Tela (96)](https://user-images.githubusercontent.com/42660456/61159794-9c5e6f00-a4d3-11e9-8850-6a5654e5fb24.png)
![Captura de Tela (98)](https://user-images.githubusercontent.com/42660456/61159845-c6b02c80-a4d3-11e9-868a-ce1db4c3e93b.png)

**Comment by BondarenkoStas** [comment]
@gabrielchaves7 Is the issue still relevant using current flutter stable v1.9.1+hotfix.2 or master?
Please do not include screenshots of code. This makes it extremely tedious to reproduce the issue, as we would have to manually transcribe your example.
Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/. . Also provide your `flutter doctor -v``` output.

**Comment by gabrielchaves7** [comment]
It was my mistake, i wasn't using a future to initialize the camera controller. Thanks any way.
