### ISSUE TITLE
macOS 10.15 beta error related to analysis_server.dart.snapshot

### ISSUE THREAD

**Issue by Adrift001** [flutter/flutter#36114]
Hi,

I've updated to macOS 10.15 Beta, and when I try and run the Dart analysis in Android Studio, I now get the prompt:

**“kernel-service.dart.snapshot” can’t be opened because it is from an unidentified developer.** 

There were several other prompts, but I was able to approve those under Security & Privacy in System preferences, but this exception doesn't work (the button is grayed out.) Any clues so I can get back to working on my Flutter apps and continue to prep things for the beta macOS, too? This wasn't a problem in macOS 10.14.

**Comment by MartinP7r** [comment]
I ran into the same issue on Catalina.

A workaround, at your own risk, is to disable the Gatekeeper security setting by running `sudo spctl --master-disable` from your command line. this will disable the check for unknown developer.
Again, at your own risk.

**Comment by urmilshroff** [comment]
Same problem here. The "Open Anyway" button isn't greyed out for me, but when I click it, nothing happens. macOS Catalina v10.15 Beta (19A501i).

**Comment by urmilshroff** [comment]
> I ran into the same issue on Catalina.
> 
> A workaround, at your own risk, is to disable the Gatekeeper security setting by running `sudo spctl --master-disable` from your command line. this will disable the check for unknown developer.
> Again, at your own risk.

You can disable Gatekeeper, run `flutter doctor` and then quickly reenable Gatekeeper with `sudo spctl --master-enable`. Flutter works thereafter, and reenabling Gatekeeper makes things safe again😄

**Comment by christopherfujino** [comment]
There are several macOS Catalina issues all stemming from Gatekeeper issues, so I have consolidated them all into [#36714](https://github.com/flutter/flutter/issues/36714). Please subscribe to that issue for updates. The quickfix would be to disable Gatekeeper from the command-line with `sudo spctl --master-disable`.

**Comment by iamphoenix310** [comment]
I try to run this sudo command but it gives error. below message is printed:
sudo: spct1: command not found
How to disable it?
