### ISSUE TITLE
Widget is not refreshing

### ISSUE THREAD

**Issue by bobykurniawan11** [flutter/flutter#36113]
So, i'm trying to refresh my widget after i uploading an image, so i don't need to re open my page. Because for now i need to open my page again to see the new image that i upload.

```
new Container(
      child: _profileAvatar(),
      width: 150.0,
       height: 150.0,
),
```
the widget what i want refresh (below)
```
Widget _profileAvatar(){
  if(!hasProfilImage){
    return CircleAvatar(
      radius: 30.0,
      backgroundImage:
      new ExactAssetImage('assets/images/default_profile.png'),
      backgroundColor: Colors.transparent,
    );
  }else {
    return CircleAvatar(
      radius: 30.0,
      backgroundImage:
      NetworkImage( "${Configuration.url}assets/profileImage/${userProfilImage}"),
      backgroundColor: Colors.transparent,
    );
  }
}
```

and here is the choosing image and upload part

```
  Future getImage() async {
    var image = await ImagePicker.pickImage(source: ImageSource.gallery);
      if(image != null) {
        _image = image;
        _upload().then((isSuccess){
          setState(() {
            hasProfilImage = true;
          });
        });
      }
  }
```

here is my full code https://gist.github.com/bobykurniawan11/2fcb05b25ec02e7d03ac5639dc3de05b

**Comment by BugsBunnyBR** [comment]
1) cant access the link.
2) Try to add an `UniqueKey()` in the `Container` just to see what happens.

**Comment by bobykurniawan11** [comment]
I do a lot of change and still not working, i think i will create new

**Comment by bobykurniawan11** [comment]
sorry but i do lot of change (use streambuilder) so i create new issue https://github.com/flutter/flutter/issues/36187
