### ISSUE TITLE
Would like to ask the flutter tool to download the Dart SDK, but no other DEPs

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3611]
Useful when building the website, I really just want Flutter and its vendored Dart SDK. The only way I know how to ask the flutter tool to download the Dart SDK is to run `flutter doctor` but that downloads a lot of assets/DEPs that I don't need. I really only need to analyze source code.

Thanks!

**Comment by devoncarew** [comment]
You could probably do something like:
- git clone <flutter-repo>
- cd flutter
- `./bin/cache/update_dart_sdk.sh`

**Comment by sethladd** [comment]
Nice! Will try it. Thank you!
