### ISSUE TITLE
Navigator.push pushes more than one single page

### ISSUE THREAD

**Issue by AmaldevAD** [flutter/flutter#36129]
loads  the next page lot of times if the first page is delayed for sometime

**Comment by TahaTesser** [comment]
Hi @AmaldevAD 
Are you still experiencing this issue? 
If yes, can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment]
@AmaldevAD 
I hope it's fixed. Closing.
Comment please if it's not so and I'll reopen the issue
