### ISSUE TITLE
Flutter App doesn't run on Snapdragon 425 devices

### ISSUE THREAD

**Issue by abdullayev007** [flutter/flutter#36128]
Hi everyone!
We have serious problem. But we don't know what is the issue. Earlier there were no issues but after updating flutter sdk we have received some reports from subscribers that app doesn't launch. We have doubts about **--split-per-abi** change. We are having problems on different devices both on Samsung Galaxy J6+ and Samsung Galaxy J4+ (both phones using Snapdragon 425). There may be many affected users but we don't know exact affected user count. We tested on our phones and no any issue. 

Subscriber sent us this video:

[WhatsApp Video 2019-07-13 at 15.09.31.mp4.zip](https://github.com/flutter/flutter/files/3388730/WhatsApp.Video.2019-07-13.at.15.09.31.mp4.zip)

Anyone here knows any fix about this?

I can't provide logs because we haven't that devices.

Thanks.

**Comment by tvolkert** [comment]
@abdullayev007 thanks for the report.

In https://github.com/flutter/flutter/issues/35838#issuecomment-512543124, Jason was able to reproduce a crash in your project and diagnosed it as a problem with multi-dex requiring an update to your Gradle configuration.

> @abdullayev007 Took a look at your app and saw it crashing on older Android devices with this exception:
>
> ```
> java.lang.RuntimeException: Unable to get provider androidx.core.content.FileProvider: java.lang.ClassNotFoundException: androidx.core.content.FileProvider
> ```
> This was happening due to Android's MultiDex format (https://developer.android.com/studio/build/multidex)
>
> The app's android/app/build.gradle file specified multiDexEnabled true.
>
> If MultiDex is not required for this app, then remove that line. If you do need MultiDex, then change the app to use a custom Application subclass that extends MultiDexApplication.
> You can base that Application on the standard FlutterApplication class (https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/app/FlutterApplication.java)

Have you tried this?

**Comment by abdullayev007** [comment]
@tvolkert I have tried. Still doesn't work. Black screen showing on launch.

**Comment by tvolkert** [comment]
@jason-simmons and @mklim were apparently able to get your app running with updates to the MultiDex config.

**Comment by jason-simmons** [comment]
I was able to run the app on a Samsung S3 Mini and a Nexus 7 running Android Jellybean.

The Samsung J6+ problem might be related to this: https://github.com/flutter/flutter/issues/36130

**Comment by abdullayev007** [comment]
#36130 this solved my problem. Thank you.

**Comment by tvolkert** [comment]
@abdullayev007 great.  I'm gonna close this issue then, but feel free to re-open if there's more to do here.
