### ISSUE TITLE
I am having difficulty getting Packages

### ISSUE THREAD

**Issue by hashweather** [flutter/flutter#36121]
I keep getting "Got socket error trying to find package xxx " since I tried using Flutter. Please help

**Comment by BondarenkoStas** [comment]
@hashweather is the issue still relevant? There can be many reasons. Can you open https://pub.dev/ from browser? Do you have an antivirus installed? Is your flutter in the folder without write permission? Are you in China? Do you have a corporate firewall?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
