### ISSUE TITLE
Google_maps_flutter does not work on Motorola second generation like old devices.

### ISSUE THREAD

**Issue by mitesh77** [flutter/flutter#36125]
Google_maps_flutter does not work on Motorola second generation like old devices.
this device has android 6. 
my mobile continuous hanging. even I try Google_maps_flutter plugins example and I fond the same issue. my mobile not responding to any input on the screen every time and finally, I restart my phone all time.
Please check and solve this problem.
even I check another old oppo phone with this problem.
I think Google_maps_flutter plugins do not work on tow-three years old mobile.

**Comment by BondarenkoStas** [comment]
@mitesh77 Can you specify, is it related to devices, or related to android version?

**Comment by mitesh77** [comment]
I don't sure. maybe depend on hardware.

**Comment by TahaTesser** [comment]
Hi @mitesh77 
If you still have Motorola second generation 
can you please provide your `flutter doctor -v` and `flutter run --verbose` running the app on such device? 
Thank you

**Comment by mitesh77** [comment]
I don't have this phone, my client has, he is not a developer, so I am not giving you this information  "can you please provide your flutter doctor -v and flutter run --verbose running the app on such device?"

**Comment by TahaTesser** [comment]
Hi @mitesh77 

Given mentioned is still open that is related older devices on Marshmallow. Running sample code seems to be working fine 

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

Thank you
