### ISSUE TITLE
Like to have color state list

### ISSUE THREAD

**Issue by karthickr95** [flutter/flutter#36131]
Would like to have something like [ColorStateList](https://developer.android.com/reference/android/content/res/ColorStateList) to manage color in state of widgets

**Comment by HansMuller** [comment]
You might want to look at [MaterialStateColor](https://api.flutter.dev/flutter/material/MaterialStateColor-class.html)

**Comment by Piinks** [comment]
We have WidgetStateColor now available for stateful color palettes, so I am going to close this. Thank you!
