### ISSUE TITLE
webview_flutter and linear progress indicator

### ISSUE THREAD

**Issue by tedhenry100** [flutter/flutter#36136]
When loading a Web page, showing a linear progress indicator to the user estimating how much of the loading work has been done (and how much remains) is standard at least on iOS. How to get a progress estimate from `WebView` so a linear progress indicator can be updated?

**Comment by wbingz0719** [comment]
any solution?how to know the loading progress?

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/28872. Please add votes there if you are interested in this feature.
