### ISSUE TITLE
google_sign_in plugin idToken error

### ISSUE THREAD

**Issue by LucaGabi** [flutter/flutter#36147]
Hi, I use this plugin to do google login and it works but after 1h idToken expires and I can't find a way to refresh it:

```
  Future<bool> signInGoogle(BuildContext context) async {
    setState(ViewState.Busy);
    try {
      var u = await _googleSignIn.signInSilently();
      if (u==null) u = await _googleSignIn.signIn();
      // Authenticate the GoogleUser
      // This will give back an access token and id token
      GoogleSignInAuthentication googleAuth = await u.authentication;
      await _api.loginExternalG(googleAuth.idToken);
    } catch (e) {
      return false;
    }
    setState(ViewState.Idle);
    return true;
  }
```

**Comment by BugsBunnyBR** [comment]
This token is meant to be sent to your server to validate your user login. If you fail to send this token in the next hour you should logout your user from your app.
You can use the method `isSignedIn()` to check if the user is signed in.

**Comment by LucaGabi** [comment]
The problem is that this id token dose not change ever even if I do a logout and login on the client and then the server fails to validate due to being expired.

**Comment by LucaGabi** [comment]
It works now .. I added .clearAuthCache(); and it's ok.
```
Future<bool> signInGoogle(BuildContext context) async {
    setState(ViewState.Busy);
    try {
      var u = await _googleSignIn.signInSilently();
      if (u==null) u = await _googleSignIn.signIn();
      u.clearAuthCache();
      // Authenticate the GoogleUser
      // This will give back an access token and id token
      GoogleSignInAuthentication googleAuth = await u.authentication;
      await _api.loginExternalG(googleAuth.idToken);
    } catch (e) {
      return false;
    }
    setState(ViewState.Idle);
    return true;
  }
```

**Comment by LucaGabi** [comment]
It seems it's still not working .. the token is not regenerated or when it is it's not clear what triggers that ..

**Comment by LucaGabi** [comment]
It was my fault .. the test I did was with an emulator that had wrong date & time set ..
