### ISSUE TITLE
flutter upgrade failed

### ISSUE THREAD

**Issue by hujianhang2996** [flutter/flutter#36145]
every time I run flutter upgrade, it turned out this:

Downloading Dart SDK from Flutter engine 54ad777fd29b031b87c7a68a6637fb48c0932862...
dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
  Referenced from: /Users/XXX/anaconda3/lib/libssh2.1.dylib
  Reason: image not found
/Users/XXX/flutter/bin/internal/update_dart_sdk.sh: line 100:  7529 Abort trap: 6           curl --continue-at - --location --output "$DART_SDK_ZIP" "$DART_SDK_URL" 2>&1

Failed to retrieve the Dart SDK from: https://storage.flutter-io.cn/flutter_infra/flutter/54ad777fd29b031b87c7a68a6637fb48c0932862/dart-sdk-darwin-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china

**Comment by christopherfujino** [comment]
@hujianhang2996 can you add the output of `flutter doctor -v` please?

**Comment by gerlaic** [comment]
I got the same issue and when I run `flutter doctor -v`, it just returned:
```
flutter doctor -v
Downloading Dart SDK from Flutter engine fee001c93f25a1e7258e762781a7361f122d29f5...
dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
  Referenced from: /Users/binggan/anaconda3/lib/libssh2.1.dylib
  Reason: image not found
/Users/binggan/Desktop/flutter/bin/internal/update_dart_sdk.sh: line 100: 39230 Abort trap: 6           curl --continue-at - --location --output "$DART_SDK_ZIP" "$DART_SDK_URL" 2>&1

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra/flutter/fee001c93f25a1e7258e762781a7361f122d29f5/dart-sdk-darwin-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china
```

**Comment by gerlaic** [comment]
@hujianhang2996 Could you check if this helps you solving the issue?

https://stackoverflow.com/questions/38670295/homebrew-refusing-to-link-openssl

**Comment by christopherfujino** [comment]
This looks to me like anaconda overriding the system libssl with its own, of a different version. Assuming anaconda is configured in your shell config, could you try opening a new, default config bash shell like: `bash --noprofile --norc` and then try `flutter doctor` to see if that is indeed the issue?

**Comment by christopherfujino** [comment]
Closing this because of lack of user response.

**Comment by microJ** [comment]
same error，it's success after tried several times 🤣

**Comment by BharathRavi27** [comment]
Did someone find any workarounds? I am trying to upgraded flutter and not able to proceed.

**Comment by christopherfujino** [comment]
@microJ @BharathRavi27 you can test if your issue is the same as the OP (a conflict with anaconda overriding defaults) by doing:

```
env -i bash --norc --noprofile # invokes a new shell ignoring your config files
<path_to_flutter_repo>/bin/flutter doctor -v
```

And see if that is successful. If that works, then your issue is that your anaconda install is overriding libssl. Else, you are having a different issue and you should file a new issue with full logs and the output of `flutter doctor -v`.

**Comment by BharathRavi27** [comment]
I figured that my issue was related to permission. I has to give proper permissions to the flutter direcrory and also, had deleted the downloads/cache directory inside flutter/bin.
