### ISSUE TITLE
Share Image Along with a text message 

### ISSUE THREAD

**Issue by nitishpatel** [flutter/flutter#36159]

**Comment by canewsin** [comment]
not enough info provide more info to get info

**Comment by BondarenkoStas** [comment]
@nitishpatel Please explain your proposal in more details.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
