### ISSUE TITLE
This error appear after upgrading flutter 

### ISSUE THREAD

**Issue by grgbbek** [flutter/flutter#36152]
## Logs

```
## command

flutter doctor

## exception

ProcessException: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\Red Devil\AppData\Local\Android\sdk\tools\bin\sdkmanager.BAT --licenses

```
#0      AndroidLicenseValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:261:29)
<asynchronous suspension>
#1      AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:194:19)
<asynchronous suspension>
#2      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:354:52)
#3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#4      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:351:36)
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:152:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:223:41)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#8      Doctor.diagnose (package:flutter_tools/src/doctor.dart:213:24)
#9      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#10     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#11     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#19     Future._complete (dart:async/future_impl.dart:473:7)
#20     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#23     Cache.updateAll (package:flutter_tools/src/cache.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#30     Future._complete (dart:async/future_impl.dart:473:7)
#31     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#32     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#33     _rootRun (dart:async/zone.dart:1120:38)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#40     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#43     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
encountered exception: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\Red Devil\AppData\Local\Android\sdk\tools\bin\sdkmanager.BAT --licenses

#0      AndroidLicenseValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:261:29)
<asynchronous suspension>
#1      AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:194:19)
<asynchronous suspension>
#2      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:354:52)
#3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#4      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:351:36)
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:152:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:223:41)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#8      Doctor.diagnose (package:flutter_tools/src/doctor.dart:213:24)
#9      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:193:26)
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
#11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:7)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
#18     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:140:19)
#20     _doctorText (package:flutter_tools/runner.dart:192:19)
#21     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#22     _doctorText (package:flutter_tools/runner.dart:188:27)
#23     _createLocalCrashReport (package:flutter_tools/runner.dart:170:32)
#24     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#25     _createLocalCrashReport (package:flutter_tools/runner.dart:155:37)
#26     _handleToolError (package:flutter_tools/runner.dart:125:33)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#33     Future._complete (dart:async/future_impl.dart:473:7)
#34     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#35     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#36     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#37     CrashReportSender.sendReport (package:flutter_tools/src/crash_reporting.dart)
#38     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#39     _rootRunUnary (dart:async/zone.dart:1132:38)
#40     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#41     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#43     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#44     Future._complete (dart:async/future_impl.dart:473:7)
#45     Stream.fold.<anonymous closure> (dart:async/stream.dart:742:18)
#46     _rootRun (dart:async/zone.dart:1120:38)
#47     _CustomZone.run (dart:async/zone.dart:1021:19)
#48     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#49     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#50     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#51     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#52     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#53     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#54     _StringAdapterSink.close (dart:convert/string_conversion.dart:249:11)
#55     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:300:20)
#56     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:80:18)
#57     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#58     _rootRun (dart:async/zone.dart:1120:38)
#59     _CustomZone.run (dart:async/zone.dart:1021:19)
#60     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#61     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#62     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#63     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#64     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#65     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#66     _rootRun (dart:async/zone.dart:1120:38)
#67     _CustomZone.run (dart:async/zone.dart:1021:19)
#68     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#69     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#70     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#71     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#72     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#73     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#74     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:62:11)
#75     _FilterSink.close (dart:io/data_transformer.dart:637:11)
#76     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:80:18)
#77     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#78     _rootRun (dart:async/zone.dart:1120:38)
#79     _CustomZone.run (dart:async/zone.dart:1021:19)
#80     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#81     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#82     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#83     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#84     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#85     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#86     _rootRun (dart:async/zone.dart:1120:38)
#87     _CustomZone.run (dart:async/zone.dart:1021:19)
#88     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#89     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#90     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#91     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#92     _SyncStreamController._sendDone (dart:async/stream_controller.dart:772:19)
#93     _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#94     _StreamController.close (dart:async/stream_controller.dart:622:5)
#95     _HttpParser._closeIncoming (dart:_http/http_parser.dart:1037:23)
#96     _HttpParser._doParse (dart:_http/http_parser.dart:752:11)
#97     _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#98     _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#99     _rootRunUnary (dart:async/zone.dart:1132:38)
#100    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#101    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#102    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#103    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#104    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#105    _StreamController._add (dart:async/stream_controller.dart:640:7)
#106    _StreamController.add (dart:async/stream_controller.dart:586:5)
#107    _Socket._onData (dart:io-patch/socket_patch.dart:1786:41)
#108    _rootRunUnary (dart:async/zone.dart:1132:38)
#109    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#110    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#111    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#112    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#113    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#114    _StreamController._add (dart:async/stream_controller.dart:640:7)
#115    _StreamController.add (dart:async/stream_controller.dart:586:5)
#116    _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1004:19)
#117    _rootRun (dart:async/zone.dart:1120:38)
#118    _CustomZone.run (dart:async/zone.dart:1021:19)
#119    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#120    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#121    _rootRun (dart:async/zone.dart:1124:13)
#122    _CustomZone.run (dart:async/zone.dart:1021:19)
#123    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#124    Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#125    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#126    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#127    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

<!-- If possible, paste the output of running `flutter doctor -v` here. -->
```

[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.18362.239], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at C:\development\tools\flutter
    • Framework revision b712a172f9 (5 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

\CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
/CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 0d25b8a85df387d2)
\CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\Red Devil\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:634:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:343:48)
#5      runSync (package:flutter_tools/src/base/process.dart:315:10)
#6      getAdbDevices (package:flutter_tools/src/android/android_device.dart:614:12)
#7      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:63:53)
<asynchronous suspension>
#8      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:223:52)
<asynchronous suspension>
#9      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:151:46)
<asynchronous suspension>
#10     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:743:54)
<asynchronous suspension>
#11     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:152:52)
#12     Doctor.diagnose (package:flutter_tools/src/doctor.dart:223:41)
#13     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:213:24)
#15     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:193:26)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
#17     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:7)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
#24     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:140:19)
#26     _doctorText (package:flutter_tools/runner.dart:192:19)
#27     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#28     _doctorText (package:flutter_tools/runner.dart:188:27)
#29     _createLocalCrashReport (package:flutter_tools/runner.dart:170:32)
#30     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#31     _createLocalCrashReport (package:flutter_tools/runner.dart:155:37)
#32     _handleToolError (package:flutter_tools/runner.dart:125:33)
#33     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#34     _rootRunUnary (dart:async/zone.dart:1132:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#39     Future._complete (dart:async/future_impl.dart:473:7)
#40     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#41     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#42     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#43     CrashReportSender.sendReport (package:flutter_tools/src/crash_reporting.dart)
#44     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#45     _rootRunUnary (dart:async/zone.dart:1132:38)
#46     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#47     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#49     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#50     Future._complete (dart:async/future_impl.dart:473:7)
#51     Stream.fold.<anonymous closure> (dart:async/stream.dart:742:18)
#52     _rootRun (dart:async/zone.dart:1120:38)
#53     _CustomZone.run (dart:async/zone.dart:1021:19)
#54     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#55     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#56     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#57     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#58     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#59     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#60     _StringAdapterSink.close (dart:convert/string_conversion.dart:249:11)
#61     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:300:20)
#62     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:80:18)
#63     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#64     _rootRun (dart:async/zone.dart:1120:38)
#65     _CustomZone.run (dart:async/zone.dart:1021:19)
#66     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#67     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#68     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#69     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#70     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#71     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#72     _rootRun (dart:async/zone.dart:1120:38)
#73     _CustomZone.run (dart:async/zone.dart:1021:19)
#74     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#75     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#76     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#77     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#78     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#79     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#80     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:62:11)
#81     _FilterSink.close (dart:io/data_transformer.dart:637:11)
#82     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:80:18)
#83     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#84     _rootRun (dart:async/zone.dart:1120:38)
#85     _CustomZone.run (dart:async/zone.dart:1021:19)
#86     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#87     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#88     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#89     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#90     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#91     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#92     _rootRun (dart:async/zone.dart:1120:38)
#93     _CustomZone.run (dart:async/zone.dart:1021:19)
#94     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#95     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#96     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#97     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#98     _SyncStreamController._sendDone (dart:async/stream_controller.dart:772:19)
#99     _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#100    _StreamController.close (dart:async/stream_controller.dart:622:5)
#101    _HttpParser._closeIncoming (dart:_http/http_parser.dart:1037:23)
#102    _HttpParser._doParse (dart:_http/http_parser.dart:752:11)
#103    _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#104    _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#105    _rootRunUnary (dart:async/zone.dart:1132:38)
#106    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#107    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#108    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#109    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#110    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#111    _StreamController._add (dart:async/stream_controller.dart:640:7)
#112    _StreamController.add (dart:async/stream_controller.dart:586:5)
#113    _Socket._onData (dart:io-patch/socket_patch.dart:1786:41)
#114    _rootRunUnary (dart:async/zone.dart:1132:38)
#115    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#116    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#117    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#118    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#119    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#120    _StreamController._add (dart:async/stream_controller.dart:640:7)
#121    _StreamController.add (dart:async/stream_controller.dart:586:5)
#122    _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1004:19)
#123    _rootRun (dart:async/zone.dart:1120:38)
#124    _CustomZone.run (dart:async/zone.dart:1021:19)
#125    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#126    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#127    _rootRun (dart:async/zone.dart:1124:13)
#128    _CustomZone.run (dart:async/zone.dart:1021:19)
#129    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#130    Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#131    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#132    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#133    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by blasten** [comment]
This is fixed on master.
