### ISSUE TITLE
Cannot access 'android.arch.lifecycle.LifecycleOwner', incompatibility with Android Studio Kotlin plugin version 1.3.70

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#36160]
```
[✓] Flutter (Channel master, v1.8.2-pre.33, on Linux, locale en_US.UTF-8)
    • Flutter version 1.8.2-pre.33 at <flutter path>
    • Framework revision e3ee5c6bbb (18 hours ago), 2019-07-13 16:02:09 -0700
    • Engine revision 919e353236
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 24725a8559)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at <android path>
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = <android home>
    • Java binary at: <java path>
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

Android Studio (version 3.4)
```

I keep seeing the following issue:
```
Rejecting re-init on previously-failed class 
java.lang.Class<io.flutter.embedding.engine.FlutterEngine>: 
java.lang.NoClassDefFoundError: Failed resolution of: 
Landroid/arch/lifecycle/LifecycleOwner;
```

I've tried adding the dependency directly (plus `appcompat` for good measure) but the error (warning?) keeps showing up regardless. I've tried 2.0, 2.1 and 2.2 of the arch frameworks also.

Not sure if it is a version conflict issue?

```
    // arch
    def lifecycleVersion = "2.2.0-alpha02"
    implementation "androidx.lifecycle:lifecycle-extensions:$lifecycleVersion"
    implementation "androidx.lifecycle:lifecycle-runtime:$lifecycleVersion"
    kapt "androidx.lifecycle:lifecycle-compiler:$lifecycleVersion"
    // androidx
    implementation "androidx.appcompat:appcompat:1.1.0-rc01"
```

I also tried creating a fresh project and the same issue occurs. 

Not sure if Android is stripping the dep becasue it's an indirect dep (?) but I don't have proguard set up and not sure if R8 is stripping it out. It shouldn't because it is debug but I'll have a play with that anyway.

**Comment by broberts-nybble** [comment]
Hi, 

Anyway to resolve this?

**Comment by wuseal** [comment]
The same here:
```

**Comment by wuseal** [comment]
@abarth @Hixie  Need help!
With enable Android X in `pubspec.yaml`
```yaml
  module:
    androidX: true
```
Android App Could not build pass, As I look into the FlutterEngine source code it donesn't  use androidX package, so I think this should be a bug.
What I need is to want to know how to fix this temporary.

**Comment by wuseal** [comment]
After adding these two lines into `gradle.properties` file,  Clean & Build again, it works.
```gradle
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by Classy-Bear** [comment]
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:

    class io.flutter.embedding.android.FlutterActivity, unresolved supertypes: androidx.lifecycle.LifecycleOwner

    class io.flutter.embedding.engine.FlutterEngine, unresolved supertypes: androidx.lifecycle.LifecycleOwner



e: /Users/builder/clone/android/app/src/main/kotlin/com/solutions/congresos/MainActivity.kt: (3, 28): Unresolved reference: NonNull

e: /Users/builder/clone/android/app/src/main/kotlin/com/solutions/congresos/MainActivity.kt: (9, 42): Unresolved reference: NonNull

e: /Users/builder/clone/android/app/src/main/kotlin/com/solutions/congresos/MainActivity.kt: (10, 48): Type mismatch: inferred type is FlutterEngine but PluginRegistry! was expected

**Comment by Classy-Bear** [comment]
This is occurs when 
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:

    class io.flutter.embedding.android.FlutterActivity, unresolved supertypes: androidx.lifecycle.LifecycleOwner

    class io.flutter.embedding.engine.FlutterEngine, unresolved supertypes: androidx.lifecycle.LifecycleOwner



e: /Users/builder/clone/android/app/src/main/kotlin/com/solutions/congresos/MainActivity.kt: (3, 28): Unresolved reference: NonNull

e: /Users/builder/clone/android/app/src/main/kotlin/com/solutions/congresos/MainActivity.kt: (9, 42): Unresolved reference: NonNull

e: /Users/builder/clone/android/app/src/main/kotlin/com/solutions/congresos/MainActivity.kt: (10, 48): Type mismatch: inferred type is FlutterEngine but PluginRegistry! was expected

**Comment by Classy-Bear** [comment]
**Same issue here. This occurs when building in Codemagic CI/CD the android test**

Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:

    class io.flutter.embedding.android.FlutterActivity, unresolved supertypes: androidx.lifecycle.LifecycleOwner

    class io.flutter.embedding.engine.FlutterEngine, unresolved supertypes: androidx.lifecycle.LifecycleOwner



e: /Users/builder/clone/android/app/src/main/kotlin/com/solutions/congresos/MainActivity.kt: (3, 28): Unresolved reference: NonNull

e: /Users/builder/clone/android/app/src/main/kotlin/com/solutions/congresos/MainActivity.kt: (9, 42): Unresolved reference: NonNull

e: /Users/builder/clone/android/app/src/main/kotlin/com/solutions/congresos/MainActivity.kt: (10, 48): Type mismatch: inferred type is FlutterEngine but PluginRegistry! was expected

**Comment by GAM3RG33K** [comment]
I am getting the same error in my plugin code while building example app. Since My app is purely dart code based, I haven't made any changes to native projects.

Error Log;
```dart
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class io.flutter.embedding.engine.plugins.FlutterPlugin.FlutterPluginBinding, unresolved supertypes: androidx.lifecycle.LifecycleOwner
    class io.flutter.embedding.engine.FlutterEngine, unresolved supertypes: androidx.lifecycle.LifecycleOwner

e: D:\Development\Projects\Flutter\flutter_settings_screens\android\src\main\kotlin\com\happyworks\flutter_settings_screens\FlutterSettingsScreensPlugin.kt: (3, 28): Unresolved reference: NonNull
e: D:\Development\Projects\Flutter\flutter_settings_screens\android\src\main\kotlin\com\happyworks\flutter_settings_screens\FlutterSettingsScreensPlugin.kt: (13, 38): Unresolved reference: NonNull
e: D:\Development\Projects\Flutter\flutter_settings_screens\android\src\main\kotlin\com\happyworks\flutter_settings_screens\FlutterSettingsScreensPlugin.kt: (35, 32): Unresolved reference: NonNull
e: D:\Development\Projects\Flutter\flutter_settings_screens\android\src\main\kotlin\com\happyworks\flutter_settings_screens\FlutterSettingsScreensPlugin.kt: (35, 59): Unresolved reference: NonNull
e: D:\Development\Projects\Flutter\flutter_settings_screens\android\src\main\kotlin\com\happyworks\flutter_settings_screens\FlutterSettingsScreensPlugin.kt: (43, 40): Unresolved reference: NonNull

```

**Comment by Hassan-Fa** [comment]
> ```groovy-gradle
> android.useAndroidX=true
> android.enableJetifier=true
> ```

didn't work for me (it already had these lines)
#46686

**Comment by riadshuvo** [comment]
In my case I upgraded my flutter sdk then this problem had been solved ...

It happens because some packages of Flutter make conflict with Androidx LifeCycle. So you need to upgrade the Flutter then run your app.... I think then there should not be no Errors like this...

For Flutter type "flutter upgrade" in your terminal...

**Comment by lukaszciastko** [comment]
I've started to see the very same issue in every Flutter project. I can build and run the app, but Android studio complains about the LifecycleOwner and the whole MainActivity is highlighted in red. It started happening almost out of the blue (though I suppose it must be link to one of the recent updates to Android Studio or some plugins).

**Comment by lukaszciastko** [comment]
I can now confirm that the issue has been cause by the Kotlin plugin version 1.3.70. I uninstalled it and manually installed the previous version (1.3.61), and the issue has disappeared. I guess we'll have to wait for the Flutter team to address this problem before we can use the latest Kotlin plugin...

**Comment by christopherfujino** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
@christopherfujino, from reading this issue it looks more related to engine or app code interacting with a new version of Kotlin? Or, the AndroidX libraries? I don't think this is related to the Flutter IntelliJ plugin.

**Comment by christopherfujino** [comment]
@devoncarew fair enough :)

**Comment by blasten** [comment]
Is this still an issue?  Make sure to migrate the project to AndroidX by following the steps on https://flutter.dev/docs/development/androidx-migration

On master, the Flutter engine was already migrated to AndroidX. Please note that the next Flutter stable release will remove the usage of the Android support libraries. Therefore, projects that haven't been properly migrated to AndroidX won't compile.

**Comment by blasten** [comment]
Please reopen if this is still an issue and add the concrete steps to reproduce the issue starting from the `flutter create` step.

**Comment by RdeWilde** [comment]
https://flutter.dev/docs/development/androidx-migration
