### ISSUE TITLE
BottomNavigationBar BottomNavigationBarItem the gap between how to adjust

### ISSUE THREAD

**Issue by GanZhiXiong** [flutter/flutter#36169]
![image](https://user-images.githubusercontent.com/27394631/61194781-57665280-a6f6-11e9-9206-4824a6ae626b.png)

If I only added two BarItem, spacing between the two BarItem and to spacing around the screen, which shows a more ugly

Can you like Row by MainAxisAlignment. SpaceEvenly can set their spacing
``` dart
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: <Widget>[
                  Text(name),
                  Text(name),
                ],
              )
```

**Comment by Hixie** [comment]
This appears to be a support request. Please use one of our support channels (like our flutter-dev mailing list) to ask for help, rather than the issue database (which is for tracking what work needs to be done). Thanks.

**Comment by lazylazyllama** [comment]
I would also like to know, how to achieve this.
