### ISSUE TITLE
app:compileflutterBuildDebugArm FAILED

### ISSUE THREAD

**Issue by pyetti** [flutter/flutter#36166]
I'm not sure what happened, but I've been unable to get the app to run for the last couple of days. It builds and runs fine for ios. I've been trying to fix this for 2 days and I'm worn out. I really need some help.

## Steps to Reproduce
Trying to run an existing app on Android using flutter version v1.7.8+hotfix.3. I'e tried with v1.8.1, which had the same result

Log files attached.

- deleted files

1. Run flutter app

**Comment by jonahwilliams** [comment]
@pyetti does this happen even after a clean build (after `flutter clean`?)?

**Comment by pyetti** [comment]
Hi Jonah,

I've tried flutter clean many times. I've also tried changing the version of gradle, changing versions of the packages in using, and all kinds of random changed in build.gradle.

**Comment by jonahwilliams** [comment]
> and all kinds of random changed in build.gradle.

If you've made arbitrary changes to your build.gradle we're likely going to need an example project with this problem so it can be debugged.

**Comment by pyetti** [comment]
I attached the build.gradle and gradle.properties files I'm using. The changes have only been to versions of plugins and compile/minimum sdk.

[app_build_gradle.txt](https://github.com/flutter/flutter/files/3390723/app_build_gradle.txt)
[build_gradle.txt](https://github.com/flutter/flutter/files/3390724/build_gradle.txt)
[gradle_props.txt](https://github.com/flutter/flutter/files/3390725/gradle_props.txt)
[gradle_wrapper_props.txt](https://github.com/flutter/flutter/files/3390726/gradle_wrapper_props.txt)
[gradlew_assembleDebug_info.txt](https://github.com/flutter/flutter/files/3390727/gradlew_assembleDebug_info.txt)

**Comment by pyetti** [comment]
I created an app and pushed to [https://github.com/pyetti/please_work](https://github.com/pyetti/please_work). It has the same setup with the exception of `apply plugin: 'com.google.gms.google-services'` being commented out in app/build.gradle. I would need to push google-services.json for that to work

**Comment by pyetti** [comment]
I uploaded a gradle scan to [https://scans.gradle.com/s/qr7g6qos5je2w](https://scans.gradle.com/s/qr7g6qos5je2w)

**Comment by pyetti** [comment]
I fixed it. This is pretty embarrassing. At some point I deleted the the two dots in rootProject.buildDir = '../build' in the project/build.gradle file. A weekend of pain over two dots. A day per dot. That's a bummer.

Maybe someone can work on that error messaging. IOException maybe?
