### ISSUE TITLE
how to send message from flutter to javascript

### ISSUE THREAD

**Issue by leiwensu** [flutter/flutter#36167]
I need to actively send a message to the H5 page embedded in the webView. H5 uses window.addEventListener to listen for messages from flutter. Can it be implemented?

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
