### ISSUE TITLE
My Plugin Header file not found

### ISSUE THREAD

**Issue by tanamduit** [flutter/flutter#36170]
i develop a chat plugin using zendesk library ios. But My project cannot run when i use that plugin. It said

 `fatal error: 'ZDCChatAPI/ZDCChatAPI.h' file not found`

I already check in Pods directory. There is a dir ZDCChat with  ZDCChatAPI.framework inside of it.
I already check ${inherited} in build setting  section framework search paths, Path/to/go/to/Pods/ZDCChat is already exist also i already add

Path/to/go/to/Pods/ZDCChat/API/**
Path/to/go/to/Pods/ZDCChat/API/Framework/**
(consider to look in Pods path in xcode)

My flutter doctor
```
ITID000419-MAC:tanamduit-app-ios lumos$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.4 18E226, locale en-ID)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by tanamduit** [comment]
ok. it's already solved.

CMIIW.  i just add chat plugin podspec with s.static_framework = true  and the error is gone.

for consideration it works in pod 1.4.0. But  after i upgrade into the latest, it's begin show the error.

**Comment by BondarenkoStas** [comment]
@tanamduit I think it's safe to close it. If you disagree, please comment and I will re-open it.
