### ISSUE TITLE
Use WidgetSpan crash on iOS device - 1.7.8

### ISSUE THREAD

**Issue by voiddog** [flutter/flutter#36176]
I use the image in `WidgetSpan`, but it crash on iOS devices.

#environment:
## Flutter doctor:
```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] iOS tools - develop for iOS devices
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
[✓] VS Code (version 1.36.0)
[✓] Connected device (3 available)

! Doctor found issues in 3 categories.
```

## iOS devices
iphone6s(9.3) simulator

# crash demo
[demo](https://github.com/voiddog/flutter_issues_demo/tree/master/lib/demo/ios_crash_1.7.8)

# crash gif
![Imgur](https://i.imgur.com/MiNaZhq.gif)

**Comment by voiddog** [comment]
Is anyone here?

**Comment by voiddog** [comment]
@justinmc @zoechi

**Comment by justinmc** [comment]
I tried your demo code on the iOS simulator and didn't get a crash.  I just wrapped it directly in a `MaterialApp` and I could see the paperclip image and scroll around without a problem.  I also tried it on an Android device and got the same result.

Any idea what I'm doing wrong?

**Comment by voiddog** [comment]
The paperclip icon not displayed may be the url address problem, I changed the url address, please pull origin.

Crash does not necessarily occur. If there is no crash, you can quickly scroll up and down the demo list page, or advance or rewind the page. Please make sure you have tried at least 3 minutes

**Comment by voiddog** [comment]
I can easily reproduce this crash on my simulator(iphone 6s 9.3/ iphone XR 12.2).

**Comment by dnfield** [comment]
Possible duplicate of https://github.com/flutter/flutter/issues/31844#issuecomment-513487403 ?

**Comment by voiddog** [comment]
Maybe not the same, I can not product the crash on my android device. only iOS device can product the crash

**Comment by blackox626** [comment]
i tryed the demo, click the ios_crash button, crash also   

o.flutter.1.ui (8): EXC_BAD_ACCESS (code=1, address=0x4160000000000000)

**Comment by tmulin** [comment]
I got the same problem, and in my situation , when I use WidgetSpan with TextSpan , and the content  display in textSpan contains '\r\n' will cause app crash !!  
When I split the content text by \r\n, and wrap them use multi TextSpan, it looks like ok !

**Comment by GaryQian** [comment]
It may have to do with the \n character, I think I may have encountered this also a few days ago independently. I'll take a look at fixing it!

**Comment by GaryQian** [comment]
Interesting to note, the crash only happens on initial app startup. Subsequent hot restarts (when starting with a non-crash version, reloading to crash version) works fine without crashes.

**Comment by tb2761** [comment]
Having same Problem on Android. Adding a Widgetspan will Crash the app.

**Comment by GaryQian** [comment]
@tb2761 Do you think you could post your Flutter doctor and a reproduction? That would be very helpful!

**Comment by GaryQian** [comment]
I have tracked the bug down to an undefined write to unallocated memory. The fix patch is here: https://github.com/flutter/engine/pull/10295
