### ISSUE TITLE
fresh new flutter create makes an app that when ran, just won't quit

### ISSUE THREAD

**Issue by doxtitech** [flutter/flutter#36175]
## Steps to Reproduce

1. flutter create my_new_flutter_app_name
2. flutter a
3. tap on the "recent" button or the "home" button

## Logs

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
D/EGL_emulation( 7048): eglMakeCurrent: 0xdfe9f7a0: ver 2 0 (tinfo 0xcc57d080)
D/EGL_emulation( 7048): eglMakeCurrent: 0xdfe05960: ver 2 0 (tinfo 0xca33fdb0)
D/EGL_emulation( 7048): eglCreateContext: 0xdfe9f860: maj 2 min 0 rcv 2
D/EGL_emulation( 7048): eglMakeCurrent: 0xdfe9f860: ver 2 0 (tinfo 0xcc57d080)
D/EGL_emulation( 7048): eglMakeCurrent: 0xdfe9f860: ver 2 0 (tinfo 0xcc57d080)
D/EGL_emulation( 7048): eglMakeCurrent: 0xdfe05960: ver 2 0 (tinfo 0xca33fdb0)
D/EGL_emulation( 7048): eglMakeCurrent: 0xdfe05960: ver 2 0 (tinfo 0xca33fdb0)
D/EGL_emulation( 7048): eglCreateContext: 0xc9d7ed40: maj 2 min 0 rcv 2
D/EGL_emulation( 7048): eglMakeCurrent: 0xc9d7ed40: ver 2 0 (tinfo 0xcc57d080)
D/EGL_emulation( 7048): eglMakeCurrent: 0xdfe05960: ver 2 0 (tinfo 0xca33fdb0)
D/EGL_emulation( 7048): eglMakeCurrent: 0xc9d7ed40: ver 2 0 (tinfo 0xcc57d080)
```
The app just won't quit. Can't even get to android settings to force quit it

**Comment by BondarenkoStas** [comment]
@doxtitech Is the issue still relevant? Please provide your flutter doctor -v output. On which device or emulator do you test it? Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
