### ISSUE TITLE
Hot reload not working vs code.

### ISSUE THREAD

**Issue by bunny100** [flutter/flutter#36183]
Hot reload not working in vs code 1.36.1, only restart is working.

debug console shows reloaded but no change appears.

**Comment by phanirithvij** [comment]
I am using vscode 1.36.1 and hot reload works.

**Comment by DanTup** [comment]
This came up at https://github.com/Dart-Code/Dart-Code/issues/1859 too. It's only happening on the master branch, not stable. I believe it might be related to some recent VM service changes as VS Code no longer sees the `reloadSources` service registered (https://github.com/flutter/flutter/pull/35765 looks like the required fix, but I'm on tip of master and it's not working) so assumes Hot Reload is not available.

As a workaround while we find a fix, you can switch to the stable branch (which is relatively recent).

(fyi @bkonyi)

**Comment by devoncarew** [comment]
@bkonyi, I assume this is updating flutter tools to listen for `Service` events instead of `_Service` events?

**Comment by DanTup** [comment]
@devoncarew @bkonyi actually, I think this might be in Dart-Code now. We don't subscribe to "Service", only "_Service" (in the released version), so we don't see the service, and we also don't get it in our logs because we didn't start listening to that stream.

**Comment by DanTup** [comment]
Yeah, this works on the latest code. Sorry for the confusion, this is a Dart-Code issue (https://github.com/Dart-Code/Dart-Code/issues/1859) which is fixed but not released.

**Comment by DanTup** [comment]
This issue is resolved in v3.2.1 of the Dart extension for VS Code.
