### ISSUE TITLE
Failed to find snapshot: kernel_blob.bin when running Flutter with BlackBerry Dynamics

### ISSUE THREAD

**Issue by gabrielkzm** [flutter/flutter#36180]
## Steps to Reproduce

* Flutter Application with BlackBerry Dynamic (GD)*
- Flutter Application used: Flutter Starter Project
- ios project edited: AppDelegate.swift - to configure BlackBerry Dynamics GD

1. flutter attach
2. Run Flutter project in Android Studio (debug mode)
3. White Screen Appears
4. Error (See below)
5. On Terminal, enter R for Hot Restart
6. Error (See below)
7. Application restarts and screen shows but flutter attach crashes (Hot Reload/Hot Restart no longer available)

## Logs

```
Step 4:
Failed to find snapshot: kernel_blob.bin
[VERBOSE-2:engine.cc(118)] Engine run configuration was invalid.
[VERBOSE-2:FlutterEngine.mm(308)] Could not launch engine with configuration.

Step 5:
Error 105 received from application: Isolate must be runnable
{request: {method: resume, params: {isolateId: isolates/42971856}}, details: Isolate must be runnable before this request is made.}

In crash report:
_InternalLinkedHashMap<String, dynamic>: {code: 105, message: Isolate must be runnable, data: {request: {method: _reloadSources, params: {pause: false, rootLibUri: file:///private/var/mobile/Containers/Data/Application/[]/tmp/flutter_starter_app_referencesuTqsp/flutter_starter_app_reference/lib/main.dart.incremental.dill, packagesUri: file:///private/var/mobile/Containers/Data/Application/[]/tmp/flutter_starter_app_referencesuTqsp/flutter_starter_app_reference/.packages, isolateId: isolates/306673427}}, details: Isolate must be runnable before this request is made.}}
```
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.4 18E226, locale en-SG)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.0)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by chinmaygarde** [comment]
`kernel_blob.bin` is only used in debug runtime modes in Flutter and should be present at a known location for tooling assisted launches. That this file cannot be resolved indicates that the assets in the application are at a non-standard location. I don't know if Blackberry Dynamics is relevant to this but without a reducded test case, it is not possible to investigate this further.
