### ISSUE TITLE
Downloading Dart SDK from Flutter engine 54ad777fd29b031b87c7a68a6637fb48c0932862... unzip:  cannot find or open , .zip or .ZIP

### ISSUE THREAD

**Issue by liumingzhi** [flutter/flutter#36192]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by BondarenkoStas** [comment]
@liumingzhi Is the issue still relevant? Please provide your `flutter doctor -v`

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
