### ISSUE TITLE
AccessibilityEvent.getPackageName() returns null on some devices

### ISSUE THREAD

**Issue by Skyggedans** [flutter/flutter#36193]
Hi, this is a copy of my SO topic.
I'm using Flutter to develop an application for RealWear HMT-1. It's an Android industrial rugged computer, that is worn on the head and controlled by voice.
I'm using Flutter semantics mechanism to intercept voice commands and emulate gestures on widgets, like button clicks.
I spent about 3 months on development and had no problems with application, everything works like a charm on my own device, but few days ago we provided our app to other company and it crashes on the very first voice command, causing the device to be further unable to react to the voice commands even outside our application. This happens at least on 2 of their devices.
Mine and their devices all have the same firmware version.
I examined the logcat log and found, that their voice recognition service crashes when it receives AccessibilityEvent and tries to call getPackageName() on it and then call toString() on its result. And it seems that getPackageName returns null, because there's NPE on toString() call, here's the stacktrace:

> 07-10 11:46:32.810  3219  3219 E AndroidRuntime: FATAL EXCEPTION: main
> 07-10 11:46:32.810  3219  3219 E AndroidRuntime: Process: com.realwear.wearhf, PID: 3219
> 07-10 11:46:32.810  3219  3219 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
> 07-10 11:46:32.810  3219  3219 E AndroidRuntime:     at com.realwear.wearhf.MainService.onAccessibilityEvent(Unknown Source:25)
> 07-10 11:46:32.810  3219  3219 E AndroidRuntime:     at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1524)
> 07-10 11:46:32.810  3219  3219 E AndroidRuntime:     at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1710)
> 07-10 11:46:32.810  3219  3219 E AndroidRuntime:     at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
> 07-10 11:46:32.810  3219  3219 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:106)
> 07-10 11:46:32.810  3219  3219 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:164)
> 07-10 11:46:32.810  3219  3219 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6518)
> 07-10 11:46:32.810  3219  3219 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
> 07-10 11:46:32.810  3219  3219 E AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:443)
> 07-10 11:46:32.810  3219  3219 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> 

And here's the decompiled fragment of their service where does it crash:

```
String str = this.f603z;
if (str == null || !str.equals(accessibilityEvent.getPackageName().toString())) {
    this.f603z = null;
    if (accessibilityEvent.getPackageName() == null || !accessibilityEvent.getPackageName().equals(getPackageName())) {
        ...
```

That's how Flutter creates an AccessibilityEvent:
```
private AccessibilityEvent obtainAccessibilityEvent(int virtualViewId, int eventType) {
    if (BuildConfig.DEBUG && virtualViewId == ROOT_NODE_ID) {
        Log.e(TAG, "VirtualView node must not be the root node.");
    }
    AccessibilityEvent event = AccessibilityEvent.obtain(eventType);

    event.setPackageName(rootAccessibilityView.getContext().getPackageName());
    event.setSource(rootAccessibilityView, virtualViewId);
    return event;
}
```
Nothing special here, it just calls getPackageName() on main activity, which is set from manifest.
I even overridden getPackageName method on my MainActivity to explicitly return the package name, and this didn't help.
What can happen to that package name? It's a Flutter bug, or Android can set it to null on its way to the service? I have no idea. Please advice, loosing a great opportunity.

**Comment by tdassonville** [comment]
Seems related to the attribute android:packageNames:"@strings/observed_packages" not beeing set, and some devices enforcing that while most don't...
See this SO answer: https://stackoverflow.com/questions/36176996/accessibilityevent-getpackagename-returns-null and Android source code for more infos...

**Comment by darshankawar** [comment]
@Skyggedans 
Are you still facing this issue using latest Flutter version ?

**Comment by Skyggedans** [comment]
@darshankawar
In my case it wasn't related to Flutter, but to the bug in WearHF service of HMT-1.
Findings were communicated to RealWear and they successfully fixed this in Oct'19 firmware update.

**Comment by darshankawar** [comment]
Thanks for your response @Skyggedans.
Closing this as non-issue based on your comment above.
