### ISSUE TITLE
Big APK size increase when updating from 1.6.3 to 1.7.8

### ISSUE THREAD

**Issue by erickjtorres** [flutter/flutter#36196]
## Details
Updating APK size from 1.6.3 to 1.7.8 hotfix 3 increases the size from 9.7 MB to 17.3 MB. No other changes are introduced between the upgrade except the for the upgrading itself. Is this something that the flutter team is aware of?

<img width="639" alt="Screen Shot 2019-07-15 at 11 37 45 AM" src="https://user-images.githubusercontent.com/25727438/61233424-21c16980-a6f6-11e9-9ae5-239f070195ad.png">

<img width="869" alt="Screen Shot 2019-07-15 at 11 43 59 AM" src="https://user-images.githubusercontent.com/25727438/61233434-2a19a480-a6f6-11e9-8331-065626d1ad2c.png">

**Comment by jonahwilliams** [comment]
By default `flutter build apk` will create a fat apk, which includes code for 32bit and 64bit devices. To go back to the old behavior, you can pass the `--split-per-abi`


For documentation on how to build android applications see https://flutter.dev/docs/deployment/android#build-an-apk
