### ISSUE TITLE
dartdoc generates documentation for dependencies

### ISSUE THREAD

**Issue by SackSlab** [flutter/flutter#36207]
I do not know if this is a bug, or a normal behavior, but when executing `dartdoc ` in the directory of my project it generates documentation for all the packages that are on my computer.

For example one of my dependencies is flutter_svg, and the ouput says:
`parsing C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_svg-0.13.1`

Already probe with the flag -[no-]include-source and it seems not to work

**Comment by dnfield** [comment]
This should be opened as an issue on https://github.com/dart-lang/dartdoc rather than here.
