### ISSUE TITLE
[cloud_firestore] snapshots() works inconsistently on iOS

### ISSUE THREAD

**Issue by larssn** [flutter/flutter#36219]
## Steps to Reproduce

1. Add a realtime listener to a random collection on iOS.
Something like: `Firestore.instance.collection('test').snapshots().listen((_) { ... }`
2. Hook up the data you get from the collection to a ListView.
3. Add data to it while running Flutter. Wait a bit, try added more data or change the existing. Wait a bit more, rinse and repeat. Eventually you should see weird delays in data showing up on iOS. Sometimes immediately, sometimes after waiting 3-5 minutes.

We've tried multiple iOS devices, and we've tried a completely fresh Flutter project. No matter what we try, we see data quite often not arriving at the device from Firestore. Sometimes it arrives after a few minutes (!). Sometimes never. However, we found that we could make the devices fetch data by putting them into standby, and unlocking them again: that fetched data immediately.

We tested on a Samsung Galaxy S8, and a Samsung T580, and it worked fine every single time, almost instantaneous; there's never been any problems with Android yet.

The physical devices used were an iPhone 6s, and an iPad mini 3, both running iOS 12.3.1.

The iOS emulator (iPhone Xr with iOS 12.2) seems to work, but we didn't test as thoroughly as the physical devices.

## Logs

```
No issues found
```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F203, locale en-GB)
   • Flutter version 1.7.8+hotfix.3 at /Users/abk/Documents/development/flutter
   • Framework revision b712a172f9 (6 days ago), 2019-07-09 13:14:38 -0700
   • Engine revision 54ad777fd2
   • Dart version 2.4.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
   • Android SDK at /Users/abk/Library/Android/sdk
   • Android NDK location not configured (optional; useful for native profiling support)
   • Platform android-28, build-tools 28.0.3
   • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
   • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
   • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
   • Xcode at /Applications/Xcode.app/Contents/Developer
   • Xcode 10.2.1, Build version 10E1001
   • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
   • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
   • Android Studio at /Applications/Android Studio.app/Contents
   • Flutter plugin version 35.2.1
   • Dart plugin version 183.6270
   • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
   • VS Code at /Applications/Visual Studio Code.app/Contents
   • Flutter extension version 3.2.0

[!] Connected device
   ! No devices available
```

**Comment by kroikie** [comment]
@larssn

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1213. Any further collaboration will be done there.
