### ISSUE TITLE
Change orientation of PageView issues 

### ISSUE THREAD

**Issue by ahmednet0001** [flutter/flutter#36226]
I have simple PageView app , I’m try to change scrolling direction when orientation change where in portrait =>horizontal scroll while in landscape => vertical scroll .I am using this code
`scrollDirection: orientation==Orientation.portrait ? Axis.horizontal : Axis.vertical`
 It work correctly but
it work fine respect to scroll but the problem in swipe direction when I change the device Orientation ,if app starts in portrait position and change to landscape it scroll vertically and swipe horizontally and vice versa.
https://i.ibb.co/T1XLgpG/Untitled-1.jpg

**Comment by ahmednet0001** [comment]
![Untitled-1](https://user-images.githubusercontent.com/11617821/61518351-97d11380-aa09-11e9-9197-9d243c5c5046.jpg)

**Comment by ahmednet0001** [comment]
I solve this problem by using appBar attribute to scaffold , but that is not required design

**Comment by sethchhim** [comment]
@ahmednet0001 The appBar can be null, just wrap the Scaffold body in a top Padding and scrollDirection change will work. 

```
  return Scaffold(
      appBar: null,
      body: Padding(
        padding: const EdgeInsets.only(top: 0.01),
        child: ...,
      ),
    );
```

See https://github.com/flutter/flutter/issues/41617

**Comment by VladyslavBondarenko** [comment]
Thanks @sethchhim 
@ahmednet0001 please follow up on https://github.com/flutter/flutter/issues/41617,
closing current one as duplicate
