### ISSUE TITLE
Track infra performance, e.g. build time, test time, flaky rate, median time of a PR gets merged etc.

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#36227]
Mirrors the P2 task of the go/flutter-infra-planning

**Comment by liyuqian** [comment]
CC @digiter @Hixie 

@dnfield : can you link your test reporter work here? I think it's a nice step toward this. Thank you!

**Comment by dnfield** [comment]
It's related to the code that uses https://github.com/flutter/flutter/blob/master/dev/bots/flutter_compact_formatter.dart

**Comment by godofredoc** [comment]
Most of this info is already collected and @keyonghan is creating dashboards for it.

**Comment by liyuqian** [comment]
Fixed by Keyong. Closing.
