### ISSUE TITLE
google_maps_flutter

### ISSUE THREAD

**Issue by prasenjitpickcel** [flutter/flutter#36234]
The following issue comes and it results in crash with latest version of google maps flutter.

android.view.Display.getDisplayId()' on a null object reference

**Comment by TahaTesser** [comment]
Hi @prasenjitpickcel 
Are you still experiencing this issue on latest stable?
If yes, can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment]
@prasenjitpickcel 
I hope it's solved.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
