### ISSUE TITLE
[engine] Compile only a given shell

### ISSUE THREAD

**Issue by BugsBunnyBR** [flutter/flutter#36231]
To compile the whole engine is a lot of work. It takes time to configure and to compile.
I would like to be able to compile just the Android shell, for instance. As I understand that is the part the interacts with the plugins, right?

So my feature request is to be able to compile and run (in a gradle/Intellij project) just the Android shell and I think the same approach could be used for the other shells.

**Comment by stuartmorgan** [comment]
You can already compile specific targets; `ninja` lets you specify a target name as an argument. So to compile just the Android shell, and skip unit test targets, you'd `ninja -C <your/out/directory/here> android` (which per https://github.com/flutter/engine/blob/master/shell/platform/android/BUILD.gn#L283 is the name for that top-level target).

You're still going to have to compile most of the engine though, as it's a dependency. There's no way to build high-level targets without building the things they depend on.

**Comment by BugsBunnyBR** [comment]
@stuartmorgan, I just would like to say that having to compile that bunch of stuff is not easy.
I would like to do some work in the Android shell that interfaces with plugins. If there was a nightly build of all the rest that is needed to compile the android sources available in snapshots would save lots of time and struggle.
I am not saying it is easy, but I believe it is possible and welcoming to new contributors.
