### ISSUE TITLE
How to upload a new profile picture?

### ISSUE THREAD

**Issue by oderindeolayemi** [flutter/flutter#36233]
Hello, good day. I am having some trouble with uploading an image File which i retrieved from the Image picker to update a Firebase user's photoUrl? How do i go about it?

**Comment by canewsin** [comment]
Ask it on stackoverflow it is not relevent here only issues, feature requests and bugs are dealt here

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
