### ISSUE TITLE
adb.exe access denied

### ISSUE THREAD

**Issue by TerenceLeeTziHou** [flutter/flutter#36245]
I run Flutter using android studio. My adb.exe run perfectly well when I am running an android project. But for flutter project I always encounter adb.exe access denied. The log as shown below :
```
flutter --no-color run --machine --track-widget-creation --device-id=JUCDU18927002676 lib\main.dart
```
## exception
```
ProcessException: ProcessException: Access is denied.

  Command: C:/Users/thlee/AppData/Local/Android/sdk\platform-tools\adb.exe devices -l

#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:634:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:343:48)
#5      runSync (package:flutter_tools/src/base/process.dart:315:10)
#6      getAdbDevices (package:flutter_tools/src/android/android_device.dart:614:12)
#7      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:63:53)
<asynchronous suspension>
#8      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:223:52)
<asynchronous suspension>
#9      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:151:46)
<asynchronous suspension>
#10     DeviceManager.getDevicesById (package:flutter_tools/src/device.dart:116:40)
<asynchronous suspension>
#11     DeviceManager.getDevices (package:flutter_tools/src/device.dart:140:11)
#12     FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:506:48)
<asynchronous suspension>
#13     RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:282:21)
<asynchronous suspension>
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:462:11)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1463:12)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#22     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#23     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#24     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#31     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#32     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#33     new Future.sync (dart:async/future.dart:224:31)
#34     CommandRunner.run (package:args/command_runner.dart:112:14)
#35     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#36     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1500:12)
#41     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#42     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#43     _rootRun (dart:async/zone.dart:1124:13)
#44     _CustomZone.run (dart:async/zone.dart:1021:19)
#45     _runZoned (dart:async/zone.dart:1516:10)
#46     runZoned (dart:async/zone.dart:1463:12)
#47     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#48     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#49     run (package:flutter_tools/runner.dart:51:10)
#50     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#51     main (file:///C:/Users/thlee/AppData/Local/Android/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#52     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Some useful info : 
- I have tried enable permission / full control for adb.exe for all user. 
- It doesn't always happen, it usually happen when the first time i startup android studio, or 
after I put my computer into sleep and restart it. 
- I updated my sdk platform-tools to 29.0.1

**Comment by jens-wetzel** [comment]
After upgrading Android Studio to the latest version, installing a new device image (api 26) and after that running "flutter upgrade" to the latest master following error:

> $ flutter doctor
> CreateProcessW failed 5
> 
> CreateProcessW failed 5
> 
> CreateProcessW failed 5
> Unhandled exception:
> ProcessException: Zugriff verweigert
> 
>   Command: "\"C:\Program Files\Git\mingw64\bin\git.EXE\"" log -n 1 --pretty=format:%H
> #0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:496:7)
> #1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:641:18)
> #2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
> #3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:93:20)
> #4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:349:48)
> #5      runSync (package:flutter_tools/src/base/process.dart:321:10)
> #6      _runGit (package:flutter_tools/src/version.dart:535:10)
> #7      new FlutterVersion (package:flutter_tools/src/version.dart:23:26)
> #8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:85:29)
> #9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
> #10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
> #11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
> #12     AppContext.get (package:flutter_tools/src/base/context.dart:115:32)
> #13     FlutterVersion.instance (package:flutter_tools/src/version.dart:186:49)
> #14     new _DefaultUsage (package:flutter_tools/src/reporting/usage.dart:148:58)
> #15     new Usage (package:flutter_tools/src/reporting/usage.dart:70:9)
> #16     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:104:20)
> #17     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
> #18     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
> #19     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
> #20     AppContext.get (package:flutter_tools/src/base/context.dart:115:32)
> #21     Usage.instance (package:flutter_tools/src/reporting/usage.dart:76:40)
> #22     flutterUsage (package:flutter_tools/src/reporting/usage.dart:60:33)
> #23     _handleToolError (package:flutter_tools/runner.dart:120:7)
> <asynchronous suspension>
> #24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:77:13)
> <asynchronous suspension>
> #25     _rootRunBinary (dart:async/zone.dart:1148:13)
> #26     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
> #27     runZoned.<anonymous closure> (dart:async/zone.dart:1479:21)
> #28     _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
> #29     Future._propagateToListeners (dart:async/future_impl.dart:589:16)
> #30     Future._completeError (dart:async/future_impl.dart:491:5)
> #31     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
> #32     _Completer.completeError (dart:async/future_impl.dart:27:5)
> #33     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:40:18)
> #34     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart)
> <asynchronous suspension>
> #35     _rootRun (dart:async/zone.dart:1124:13)
> #36     _CustomZone.run (dart:async/zone.dart:1021:19)
> #37     _runZoned (dart:async/zone.dart:1516:10)
> #38     runZoned (dart:async/zone.dart:1500:12)
> #39     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
> <asynchronous suspension>
> #40     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
> <asynchronous suspension>
> #41     _rootRun (dart:async/zone.dart:1124:13)
> #42     _CustomZone.run (dart:async/zone.dart:1021:19)
> #43     _runZoned (dart:async/zone.dart:1516:10)
> #44     runZoned (dart:async/zone.dart:1463:12)
> #45     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
> <asynchronous suspension>
> #46     runInContext (package:flutter_tools/src/context_runner.dart:58:24)
> <asynchronous suspension>
> #47     run (package:flutter_tools/runner.dart:50:10)
> #48     main (package:flutter_tools/executable.dart:65:9)
> <asynchronous suspension>
> #49     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
> #50     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
> #51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
>

**Comment by BondarenkoStas** [comment]
@TerenceLeeTziHou Do you encounter the issue using current flutter stable or master?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
