### ISSUE TITLE
firebase_admob crashes in iOS simulator on startup after basic install

### ISSUE THREAD

**Issue by hasen6** [flutter/flutter#36241]
Steps to reproduce:

1. create default app in Android Studio
2. build and run app successfully in iOS simulator through Android Studio
3. add dependency `firebase_admob: ^0.9.0+2` in pubspec.yaml
4. app builds successfully but crashes on startup
5. follow instructions to add `GADApplicationIdentifier` with test ID code into ios/Runner/info.plist file

App still crashes on startup. Instructions followed for setting up on iOS as detailed here: https://pub.dev/packages/firebase_admob. As far as I can see, I've done everything as instructed so no idea why it doesn't work with a basic app.

The error I get after all steps above is:

`Xcode build done.                                            8.5s`
`Configuring the default Firebase app...`
`6.4.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.`
`6.4.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.`
`6.4.0 - [Firebase/Core][I-COR000005] No app has been configured yet.`
`6.4.0 - [Firebase/Core][I-COR000005] No app has been configured yet.`
`*** First throw call stack:
(
	0   CoreFoundation                      0x0000000113b521bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001130f0735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000113b52015 +[NSException raise:format:] + 197
	3   Runner                              0x000000010bd33af0 +[FIRApp configure] + 576
	4   Runner                              0x000000010bd7f1c5 -[FLTFirebaseAdMobPlugin init] + 261
	5   Runner                              0x000000010bd7ef2e +[FLTFirebaseAdMobPlugin registerWithRegistrar:] + 78
	6   Runner                              0x000000010bd333fb +[GeneratedPluginRegistrant registerWithRegistry:] + 123
	7   Runner                           <…>`

**Comment by BondarenkoStas** [comment]
@hasen6 Do you still experience the issue? If not, did you find any solution or workaround?

**Comment by hasen6** [comment]
@BondarenkoStas I seem to remember it was due to missing the GoogleService-Info.plist file. Not sure why the installation instructions don't state that you need to add your app to firebase and generate this file there and add to your project for the iOS version, while it is all unnecessary on Android.

I really think if that was part of the installation instructions it would save some confusion.

**Comment by kroikie** [comment]
@hasen6

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1172. Any further collaboration will be done there.

**Comment by hasen6** [comment]
In issue FirebaseExtended/flutterfire#1172 you say it's move to here and over there you say it's been move to here and BOTH are closed....surely this is some kind of big mistake??

**Comment by kroikie** [comment]
@hasen6 sorry for the confusion.

Since firebase_admob issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by stuartmorgan** [comment]
Closing, as `firebase_admob` is [now deprecated](https://pub.dev/packages/firebase_admob/versions/0.11.0+2).
