### ISSUE TITLE
Errors in flutter doctor need to stand out

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#3625]
## Steps to Reproduce

1. Remove `jarsigner` from your path.
2. Run `flutter doctor`
3. Note all of the checkmarks on the left, apparently showing success, when in fact there is an error in the Android toolchain section.

Two recommended changes:

- The checkmark should change to an exclamation mark if there's an issue.
- If Flutter Doctor is outputting to a tty, problems should be marked in red.

## Flutter Doctor

```
[✓] Flutter (on Linux, channel unknown)
    • Flutter at /home/jimb/sysui/src/third_party/flutter
    • Framework revision 00f10da (3 days ago), engine revision 4062813

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /home/jimb/Android/Sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
    x The jarsigner utility was not found; this is used to build Android APKs. You may need to install
      or re-install the Java JDK: https://www.oracle.com/technetwork/java/javase/downloads/.

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

**Comment by abarth** [comment]
@devoncarew

**Comment by abarth** [comment]
I would have expected the x for jarsigner to propagate up to the top-level checkmark for the Android toolchain.
