### ISSUE TITLE
Color is incorrect on iOS

### ISSUE THREAD

**Issue by HiroshiHorie** [flutter/flutter#36253]
This have been bugging me for a while that colors on iOS appear incorrectly, like the color profile is incorrect. I'm sure I'm not the only one with this issue please tell me what I am doing wrong.

In the attached image, I'm trying to achieve the color above. But on the simulator the color is off. Less saturation? I'm not sure how to describe it.

<img width="331" alt="so-ss-1" src="https://user-images.githubusercontent.com/548776/61292091-dd6fbf80-a802-11e9-8c68-072307c6f122.png">

This is how i define it in flutter:
`Color theColor = Color(0xFFFF2A68);`

Thanks in advance.

**Comment by VladyslavBondarenko** [comment]
Hi @HiroshiHorie 
It seems to not be an issue with flutter, 
Closing, if you disagree please write in the comments and I will reopen it
Thank you
