### ISSUE TITLE
Using UiKitView in two pages on the navigation stack will result in a white screen if you close and reopen the app, and then pop to the page with the first UiKitView

### ISSUE THREAD

**Issue by ronjb** [flutter/flutter#36260]
### Steps to Reproduce
Gist: [https://gist.github.com/ronjb/20723d00350e480cc965e5d990fa014d](https://gist.github.com/ronjb/20723d00350e480cc965e5d990fa014d)
1. Run the app on an iOS device (bug does not happen in the simulator).
2. Tap '+ webview' in the app bar.
2. Tap '+ webview' in the app bar again.
4. Close the app and reopen it.
5. Tap the back button and all you’ll see is a white screen, but if you close the app and reopen it again, it will refresh to show the page correctly.

Note, I'm using the webview_flutter package to demonstrate the bug, but it happens with other packages that use UiKitView as well, so it's not just a webview_flutter bug.

And, it happens in debug and release builds.

### flutter doctor -v

[✓] Flutter (Channel beta, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F203, locale en-US)
• Flutter version 1.7.8+hotfix.3 at /Users/ronjb/Development/flutter
• Framework revision b712a17 (7 days ago), 2019-07-09 13:14:38 -0700
• Engine revision 54ad777fd2
• Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
• Android SDK at /Users/ronjb/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-28, build-tools 28.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 10.2.1, Build version 10E1001
• CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
• ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 37.0.1
• Dart plugin version 183.6270
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.2.0

[✓] Connected device (2 available)
• Ron's iPhone • 00008020-001E191914D8002E • ios • iOS 12.3.1
• iPad Pro (9.7-inch) • 64D3731F-BB58-4B3A-99B6-E125588C78BD • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

**Comment by kostyaVyrodov** [comment]
@ronjb ,
I've the same problem.
My application has 4 tabs. Every tab has AdMob banner that's instantiated using UiKit view. 
When I open another app and go back to mine and start navigating between tabs, the layout gets broken.

Have you solved the issue?

**Comment by BondarenkoStas** [comment]
@ronjb Please report if it's the same using current flutter stable?

**Comment by ronjb** [comment]
@BondarenkoStas  Yes, it still happens, just tested with current master.

**Comment by ronjb** [comment]
@kostyaVyrodov Yes, we found a work-around. Using a WidgetsBindingObserver and didChangeAppLifecycleState we keep track of the number of times the app is resumed. If the count increases while the screen in question is on the nav stack, but not at the top, when it returns to the top, we push a replacement of the screen using Navigator.of(context).pushReplacement.

**Comment by VladyslavBondarenko** [comment]
May be fixed (https://github.com/flutter/flutter/issues/36416#issuecomment-598098994)
Closing for now,
@ronjb comment please if it's not so and I'll reopen it,
Thank you
