### ISSUE TITLE
Textfield is hidden by keyboard

### ISSUE THREAD

**Issue by mustafakibar** [flutter/flutter#36266]
I have same problem.  #19300 #24856 #18564

I'm working many hours and googling unfortunately I can't solve this problem.

> This may not work for all situations, but I have a modalBottomSheet that contains _only_ a TextField, and it was quite simple to make it move up with the keyboard:
> 
> ```dart
> Padding(
>   padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom),
>   child: TextField()
> )
> ```

> I made a modification and the issue is fixed you can check it out here: https://gist.github.com/crimsonsuv/b25d5ebd04236f9be2aa66accba19446

I'm using many variations but It doesn't works. I also tried this article [EnsureVisibleWhenFocused](https://www.didierboelens.com/2018/04/hint-4-ensure-a-textfield-or-textformfield-is-visible-in-the-viewport-when-has-the-focus/) and I also wrapped `Scaffold`'s body with `SingleChildScrollView` **all of them not worked**.

I'm tried different sdk's on different emulators, re-install app etc. it doesn't work, text field always behind the keyboard its very frustrating 😈.

I added example code with  flutter-doctor results, [here](https://gist.github.com/mustafakibar/3f88d9a353735c5f3056429192665fc6).

**Comment by mustafakibar** [comment]
> I have been facing the same issue using slide_up_panel flutter package but resolved it with keyboard_avoider package with some extra configurations. Hope this resolves your issues.

I tried it unfortunately did not work thx

**Comment by cadinz** [comment]
Hello, I have been facing same issue too,
As a result, In my case, it cause by 
  =>flutter_statusbar_manager 
 FlutterStatusbarManager.setHidden(true);  
This Plugin. 
If you are not using this plugin , Check Your main.dart! 
If that happens anyway,  Build [flutter_gallery](https://github.com/flutter/flutter/tree/master/examples/flutter_gallery) Example and Check Material -> TextField Section

Good Luck !

**Comment by HansMuller** [comment]
I took a quick look at https://gist.github.com/mustafakibar/3f88d9a353735c5f3056429192665fc6

Currently it doesn't compile, e.g. the Scaffold's body includes this:
```
Padding(
  padding: EdgeInsets.only(top: 60),
  child: Column(
    mainAxisAlignment: MainAxisAlignment.center,
    crossAxisAlignment: CrossAxisAlignment.center,
    children: mainContainer(context),
  ),
)
```

The value of `mainContainer()` is a widget, not a list of them.  A smaller test that compiles and runs and demos the problem would help. All is not lost though, will check the other issues you referred to.

**Comment by mustafakibar** [comment]
> I took a quick look at https://gist.github.com/mustafakibar/3f88d9a353735c5f3056429192665fc6
> 
> Currently it doesn't compile, e.g. the Scaffold's body includes this:
> 
> ```
> Padding(
>   padding: EdgeInsets.only(top: 60),
>   child: Column(
>     mainAxisAlignment: MainAxisAlignment.center,
>     crossAxisAlignment: CrossAxisAlignment.center,
>     children: mainContainer(context),
>   ),
> )
> ```
> 
> The value of `mainContainer()` is a widget, not a list of them. A smaller test that compiles and runs and demos the problem would help. All is not lost though, will check the other issues you referred to.

It tried but doesn't work

**Comment by mustafakibar** [comment]
> Hello, I have been facing same issue too,
> As a result, In my case, it cause by
> =>flutter_statusbar_manager
> FlutterStatusbarManager.setHidden(true);
> This Plugin.
> If you are not using this plugin , Check Your main.dart!
> If that happens anyway, Build [flutter_gallery](https://github.com/flutter/flutter/tree/master/examples/flutter_gallery) Example and Check Material -> TextField Section
> 
> Good Luck !

Thx but it didn't work



> I took a quick look at https://gist.github.com/mustafakibar/3f88d9a353735c5f3056429192665fc6
> 
> Currently it doesn't compile, e.g. the Scaffold's body includes this:
> 
> ```
> Padding(
>   padding: EdgeInsets.only(top: 60),
>   child: Column(
>     mainAxisAlignment: MainAxisAlignment.center,
>     crossAxisAlignment: CrossAxisAlignment.center,
>     children: mainContainer(context),
>   ),
> )
> ```
> 
> The value of `mainContainer()` is a widget, not a list of them. A smaller test that compiles and runs and demos the problem would help. All is not lost though, will check the other issues you referred to.

Thx but it didn't work

**Comment by chynamyerz** [comment]
I also tried any possible solutions with no luck.

I then tried to print the value of:
MediaQuery.of(context).viewInsets.bottom

and it turned out, it is:
0.0

all the times, whether keyboard is open or closed.

**Comment by 10686142** [comment]
Guys a tip for people on Flutter web. Since I have also been stuck with this for a while.

 The whole page is moved up on web, because of a virtual keyboard. Meaning:
- On native you'll have an inset, since the bottom is still at the location of the bottom of the screen
- On web, you won't have any bottom inset since the whole screen moves up. This means that the screen size becomes smaller, compared to an inset on the original screen size on native.

See the gifs in my comment here, to see it in action:
https://github.com/flutter/flutter/issues/53489#issuecomment-618505301

So if you want to check if the keyboard has been moved on web, you should use the
```
MediaQuery.of(context).size.height
```

To check if this is smaller than it was at the start (when there was no virtual keyboard).
And than you can add some logic, like a SizedBox() at the bottom of the screen, to simulate a similar effect.

Goodluck!

**Comment by TahaTesser** [comment]
Hi @mustafakibar  @chynamyerz  
Are you still experiencing this issue on latest `stable`?
If yes, can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by chynamyerz** [comment]
> Hi @mustafakibar @chynamyerz
> Are you still experiencing this issue on latest `stable`?
> If yes, can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample. **since the gist is complete and not runnable**
> Thank you

Hi @TahaTesser , in my case I no longer experience the issue. Thank you.

**Comment by TahaTesser** [comment]
@chynamyerz  
Thank you so much for confirming


Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues
