### ISSUE TITLE
flutter_tools ignores response from VM service when registering services

### ISSUE THREAD

**Issue by bkonyi** [flutter/flutter#36273]
`VMService` registers a few services in its constructor for hot reload and expression compilation, but it does this by sending a notification instead of a request. We recently had an issue where an RPC name was changed in such a way that these services weren't being registered, but no error was raised when registration failed.

`registerService` should instead be invoked using a standard request so that a response can be checked for errors.

cc/ @jonahwilliams @zanderso

**Comment by jonahwilliams** [comment]
@bkonyi are you talking about these:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/vmservice.dart#L143

What would be the correct way to use these, `sendRequest`?

**Comment by bkonyi** [comment]
Yep, that's them. See [sendRequest](https://pub.dev/documentation/json_rpc_2/latest/json_rpc_2/Peer/sendRequest.html).

**Comment by jonahwilliams** [comment]
Does this have different semantics/required artifacts? https://github.com/flutter/flutter/pull/36276/files caused a bunch of tests to break.

**Comment by zanderso** [comment]
@bkonyi friendly ping.

**Comment by bkonyi** [comment]
> Does this have different semantics/required ~artifacts~ arguments? https://github.com/flutter/flutter/pull/36276/files caused a bunch of tests to break.

Do you remember what the errors were? This should just work as is AFAIK.

**Comment by jonahwilliams** [comment]
Following up on this - everything is working better now that we're using `package:vm_service`. Is there anything we need to do here besides handle errors thrown via registration? I see the return type is Success so I assume it either returns or throws.

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/vmservice.dart#L160

**Comment by bkonyi** [comment]
Nope, that looks correct to me.

**Comment by jonahwilliams** [comment]
Awesome, fixed via migration to `package:vm_service` : https://github.com/flutter/flutter/issues/52179
