### ISSUE TITLE
Color constants in our Editor should be color-coded

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3628]
I saw @jimbe has the [pigments plugin](https://atom.io/packages/pigments) in Atom that colorizes any hex string that it sees. We should totally do that for any Color literal in Flutter code.

cc @devoncarew

**Comment by mit-mit** [comment]
This issue was moved to flutter/flutter-intellij#460

**Comment by mit-mit** [comment]
Moved to IntelliJ tracker.
