### ISSUE TITLE
type 'int' is not a subtype of type '(dynamic) => dynamic'

### ISSUE THREAD

**Issue by Gopalkrishanbairagi** [flutter/flutter#36280]
I am adding map<String, dynamic> to document in firebase, 
for that I am using below given code

dynamic rating = 1;
var restMap = rest.toMap();
restMap.update('rate', rating);

because update is not allowing me to add 1 directly because it is expecting dynamic not int
now, 1 cannot be dynamic because it is int

**Comment by LongCatIsLooong** [comment]
Please refer to API docs: https://api.flutter.dev/flutter/dart-core/Map/operator_put.html
