### ISSUE TITLE
`embedder_unittests` fail on Windows.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#36294]
The test harness doesn't seem to be able to find necessary fixtures.

**Comment by pedromassangocode** [comment]
Is this still a valid issue today?

**Comment by chinmaygarde** [comment]
> Is this still a valid issue today?

Yes, the latest [Windows bot runs don't invoke](https://ci.chromium.org/p/flutter/builders/prod/Windows%20Android%20AOT%20Engine/7086) the tests harness.

> is the tests in question at this file?

The unit-test harness is generated by [this GN target](https://github.com/flutter/engine/blob/89a46af119a4f9b989a6af98da2b64af810e8cd5/shell/platform/embedder/BUILD.gn#L146). While `embedder_unittests.cc` is part of this harness, there are many other translation unit-tests.

**Comment by cbracken** [comment]
Fixed by flutter/engine#29624.
