### ISSUE TITLE
Flutter support on Catalina

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#36290]
**Update:**

So we now have a [github project](https://github.com/orgs/flutter/projects/4?add_cards_query=is%3Aopen) (with all Catalina-related issues and PRs) and a [wiki page](https://github.com/flutter/flutter/wiki/State-of-Catalina-Support) to track Flutter support of Catalina.

## Issues

1. https://github.com/flutter/flutter/issues/22598
1. https://github.com/flutter/flutter/issues/33890
1. https://github.com/flutter/flutter/issues/33909
1. https://github.com/flutter/flutter/issues/35018
1. https://github.com/flutter/flutter/issues/36114
1. https://github.com/flutter/flutter/issues/36172
1. https://github.com/flutter/flutter/issues/36714
1. https://github.com/flutter/flutter/issues/36786
1. https://github.com/flutter/flutter/issues/36788
1. https://github.com/flutter/website/issues/2856
1. https://github.com/flutter/website/issues/2857

<hr>

Already ~1% of Flutter users are on Catalina.

There are a few known issues on Catalina (which are in various states of fixing), but no central location for tracking support of such.

I'm creating this bug to make sure support of Catalina is appropriately scheduled and executed on in time for Catalina's expected release later this year.

@cbracken can you please find the appropriate owner for chasing this?

I would like two things:
1.  An owner/driver for this bug.
2.  A wiki page (or some other reference, maybe even this bug?) with a set of known issues for Catalina so that those trying Flutter on Catalina can find the right resources.

Thanks.

**Comment by pouledodue** [comment]
how did you learn that 1% uses Catalina?

**Comment by eseidelGoogle** [comment]
I haven't seen the data directly, someone mentioned it to me, I can't recall who. The analytics reported by the `flutter` tool includes OS version if I recall correctly, @zanderso would know.

**Comment by christopherfujino** [comment]
Host operating system is recorded as part of flutter's anonymous usage analytics, per https://github.com/flutter/flutter/blob/aa9a115181ce5795f1618f2e032cc771896cea9f/packages/flutter_tools/lib/src/reporting/README.md

**Comment by Hixie** [comment]
I'm leaving this bug open so that there's something prompting us to check this project during triage.

**Comment by pouledodue** [comment]
good work guys for this tremendous work on Catalina support. next official release around September 15 maybe? Waiting for this to upgrade my main mac to Catalina!

**Comment by tvolkert** [comment]
@christopherfujino this can be closed now, correct (it was a roll-up bug that covered a bunch of other issues, which are now fixed).

@pouledodue we hope to have a release out to the beta channel this week with full Catalina support.  If all goes well, that'll be the release that goes to stable - I can't commit to an exact date, but it shouldn't be too long.

**Comment by christopherfujino** [comment]
@tvolkert sgtm

**Comment by tvolkert** [comment]
@pouledodue, `v1.9.1+hotfix.1` is now available on the beta channel, with Catalina support.

**Comment by pouledodue** [comment]
@tvolkert thanks!
