### ISSUE TITLE
txt_unittests can only run on Linux.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#36296]
These have been disabled on other platforms.

**Comment by chinmaygarde** [comment]
cc @GaryQian

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/13189 This will disable the invalid/acceptably broken tests on mac.

**Comment by GaryQian** [comment]
Will follow up with enabling the tests on mac/windows once confirmed working

**Comment by GaryQian** [comment]
Tests have been enabled on mac
