### ISSUE TITLE
Dart engine tests don't run on Windows hosts due to pub get failures.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#36301]

**Comment by dnfield** [comment]
Do you have a link to the failure?  I believe this is because we're invoking `pub` instead of `pub.bat` on Windows.

**Comment by chinmaygarde** [comment]
Maybe. But this [doesn't seem to be the case anymore](https://github.com/flutter/engine/blob/master/.cirrus.yml#L153). Closing.

**Comment by dnfield** [comment]
That doesn't include the pub tests.

Pub get still has weird failures on our windows container. I think it may be related to the way the container is set up.

**Comment by dnfield** [comment]
s/pub tests/dart tests

**Comment by mtolmacs** [comment]
The pub get failures seem to be resolved by mid 2022, however tests on Windows went stale. I'm opening a PR to fix these tests and restoring full Windows platform test coverage (engine and dart) at flutter/engine#34350
