### ISSUE TITLE
SafeArea does not register rounded bottom corners on Pocophone F1 on gestural navigation

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#36309]
See [gist](https://gist.github.com/shihaohong/cb314af7124c8b76c2ec9767a087b563) for reproducible sample. This could be resolved once [Android Q gestural navigation](https://github.com/flutter/flutter/issues/32748) has been addressed, since it is likely that gestural inset information will be passed to the framework.

Steps to reproduce:
1. Turn gestural navigation on for Pocophone F1
2. Run code in gist
3. Notice that bottom left and right corners are cut off despite SafeArea

**Comment by zoeyfan** [comment]
Given https://github.com/flutter/flutter/issues/32748 is closed, I assume we can close this bug now?

**Comment by ditistijn** [comment]
I am having the exact same problem. It's pretty annoying to see the bottom corners of a button being cut off.
