### ISSUE TITLE
Regression: decodeImageFromPixels

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#36312]
[`main.dart` here](https://gist.github.com/ds84182/6a949816f860a2344735383afe43e261#file-main-dart) works in `Channel beta, v1.7.8+hotfix.3` and **fails** in `Channel master, v1.8.2-pre.33`.

[`decodeImageFromPixels`](https://api.flutter.dev/flutter/dart-ui/decodeImageFromPixels.html) throws `Exception: Could not instantiate image codec.`

**Comment by Hixie** [comment]
Are you able to reproduce this with a smaller test case? The smaller the better in terms of the issue being tracked down.

**Comment by jason-simmons** [comment]
I can reproduce this with the attached sample.  Looking into it now.
