### ISSUE TITLE
Support multi-line text editing on desktop platforms

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#36316]
We need to implement full support for multi-line text editing, including:
 - [ ] cut/copy/paste/clear shortcuts and actions
 - [ ] selection via mouse
 - [ ] selection via keyboard (shift-up-arrow, etc.)
 - [ ] navigation via mouse and keyboard (jump to beginning/end, move with arrow keys, set insertion point with mouse)
 - [ ] optionally, commit text with enter key (and add newline with shift-enter).

**Comment by lesnitsky** [comment]
@gspecergoog should this be handled on engine or framework side?

**Comment by Drakirus** [comment]
@lesnitsky no, this needs to be handle by the Embedder side. [WIKI: Architecture overview](https://github.com/flutter/flutter/wiki/The-Engine-architecture#architecture-overview).

**Comment by lesnitsky** [comment]
@Drakirus as far as I remember embedder API, it sends generic key events. How would "select until the end of the line" handled by embedder? Correct me if I'm wrong, it's been a while since I worked with c embedder for flutter

**Comment by Drakirus** [comment]
> as far as I remember embedder API, it sends generic key events.

Embedders aren't sending generic key event, key event are tightly liked to the underlying rendering API, there are currently 4 (maybe more) raw_keyboard implementations. [`raw_keyboard_{linux,android,macos,..}.dart`](https://github.com/flutter/flutter/tree/master/packages/flutter/lib/src/services).

`selection via keyboard` /  `commit text with enter key` are handled by a different MethodChannel. (`flutter/textinput` instead of `flutter/keyevent`).

**Comment by lesnitsky** [comment]
Thanks for the clarification! Very helpful

**Comment by gspencergoog** [comment]
We think that a lot of these are at least partially done.  Someone needs to do some testing to see what's left.

**Comment by lesnitsky** [comment]
```
Flutter 1.10.15-pre.351 • channel master • https://github.com/flutter/flutter.git
Framework • revision 8e0799a657 (8 hours ago) • 2019-10-30 23:33:38 -0700
Engine • revision b16eab6aff
Tools • Dart 2.6.0 (build 2.6.0-dev.8.2 d50c158d42)
```

Text selection doesn't work on macos
Is there some sort of config which is required to be passed down to TextField to enable this?

**Comment by arianvp** [comment]
TextField.multiline doesnt seem to work for me on Linux. "Enter" does not insert a newline

**Comment by maks** [comment]
@arianvp there is a separate issue for that bug on Linux: #36316
