### ISSUE TITLE
App won't run after Firebase, dependency issue?

### ISSUE THREAD

**Issue by rgbinnovation** [flutter/flutter#36328]
Hi,

I added FCM to my app, and now it won't run. Seems to be a dependency issue? Error below:

```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture fingerprint of input files for task ':app:checkDebugClasspath' property 'compileClasspath' during up-to-date check.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[18.0.
  0]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.google.firebase:firebase-messaging:18.0.0 -> com.google.firebase:firebase-iid@[18.0.0], but fire
  base-iid version was 19.0.0.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends on project 'firebase_messaging' which depends onto com.google.firebase:firebase-messaging@18.0.
  0
  -- Project 'app' depends onto com.google.firebase:firebase-core@17.0.0

  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.
```

Don't really know how to resolve this, anyone has any ideas?

**Comment by AnEnigmaticBug** [comment]
I don't how to solve your issue. But whenever I face build issues due to Firebase, it often helps to ensure that all Firebase libraries are using the same major version. Check your app level `build.gradle` file and see this is true.

**Comment by rgbinnovation** [comment]
This ended up being the projects needed yo be converted to AndroidX.

**Comment by bud-mo** [comment]
I got the same issue, the project is already supporting Android X.

**Comment by byNEET** [comment]
same issue here

**Comment by ericklhe** [comment]
I'm also having the same issue.

**Comment by ericklhe** [comment]
Hi guys.

This solution worked for me:

- android_folder/build.gradle:

``
dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0' // latest version
        classpath 'com.google.gms:google-services:4.3.1' // latest version
    }
``

- gradle/wrapper/gradle-wrapper.properties

``
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip # latest version
``

- android_folder/app/build.gradle:

``
dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.google.firebase:firebase-analytics:17.0.1'
    implementation 'com.google.firebase:firebase-messaging:19.0.1' // Line added 
}

apply plugin: 'com.google.gms.google-services'
``

I'm getting some warnings, but everything is working.

**Comment by maihonganh1997** [comment]
update version: 
com.google.firebase:firebase-messaging:18.0.0 ==> com.google.firebase:firebase-messaging:20.1.1
solution worked for me

**Comment by abhiint16** [comment]
I tried all the solutions and nothing worked for me. Changing Gradle version worked for me.

I changed the following inside gradle-wrapper.properties

from

`distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip`

to

`distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip`
