### ISSUE TITLE
Clearing a TextField by tapping on its suffixIcon causes its ripple to break, and the field stays gray.

### ISSUE THREAD

**Issue by jifalops** [flutter/flutter#36324]
**Update: See the minimal example in the comment below.**

~~If you comment out [this line](https://github.com/jifalops/datetime_picker_formfield/blob/ce25e7024b9198e1a921b68a63b90574af7b0529/lib/datetime_picker_formfield.dart#L293) of `datetime_picker_formfield` and try its bundled example, an exception is thrown when when tapping the reset icon. The ripple effect slowly goes across the widget and it will be gray in color forever after. If the next line, `_effectiveController.text = '';`, is commented out, there is no exception.~~

 ```log
I/flutter (18641): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (18641): The following assertion was thrown while handling a gesture:
I/flutter (18641): invalid text selection: TextSelection(baseOffset: 16, extentOffset: 16, affinity:
I/flutter (18641): TextAffinity.upstream, isDirectional: false)
I/flutter (18641):
I/flutter (18641): When the exception was thrown, this was the stack:
I/flutter (18641): #0      TextEditingController.selection= 
I/flutter (18641): #1      EditableTextState._handleSelectionChanged 
I/flutter (18641): #2      RenderEditable._handlePotentialSelectionChange 
I/flutter (18641): #3      RenderEditable.selectPositionAt 
I/flutter (18641): #4      RenderEditable.selectPosition 
I/flutter (18641): #5      _TextFieldState._handleSingleTapUp 
I/flutter (18641): #6      _TextSelectionGestureDetectorState._handleTapUp 
I/flutter (18641): #7      TapGestureRecognizer._checkUp.<anonymous closure> 
I/flutter (18641): #8      GestureRecognizer.invokeCallback 
I/flutter (18641): #9      TapGestureRecognizer._checkUp 
I/flutter (18641): #10     TapGestureRecognizer.acceptGesture 
I/flutter (18641): #11     _TransparentTapGestureRecognizer.rejectGesture 
I/flutter (18641): #12     GestureArenaManager.sweep 
I/flutter (18641): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
I/flutter (18641): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
I/flutter (18641): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
I/flutter (18641): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
I/flutter (18641): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
I/flutter (18641): #21     _invoke1  (dart:ui/hooks.dart:250:10)
I/flutter (18641): #22     _dispatchPointerDataPacket  (dart:ui/hooks.dart:159:5)
I/flutter (18641): (elided 3 frames from package dart:async)
I/flutter (18641):
I/flutter (18641): Handler: "onTapUp"
I/flutter (18641): Recognizer:
I/flutter (18641):   _TransparentTapGestureRecognizer#b7e00
I/flutter (18641): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Flutter doctor
```shell
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.3 at /home/jphilli85/tools/flutter
    • Framework revision b712a172f9 (7 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/jphilli85/tools/android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/jphilli85/tools/android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-2~deb9u1-b03)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.36.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • moto g 6 • ZY322QW4KM • android-arm • Android 8.0.0 (API 26)
```

It happens on stable and master.

**Comment by HansMuller** [comment]
Sorry, I'm not clear on the error being reported here. Can you provide a small self-contained app that demonstrates the problem in terms of an unmodified version of Flutter? Note also: https://gist.github.com/ is a useful way to share the code.

**Comment by jifalops** [comment]
Here's a minimal example.

```dart
import 'package:flutter/material.dart';

const appName = 'Breaks Ripple';

void main() => runApp(MaterialApp(title: appName, home: BreakTheRipple()));

class BreakTheRipple extends StatelessWidget {
  final controller = TextEditingController(text: 'clear the text');
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(appName)),
      body: ListView(
        padding: EdgeInsets.all(24),
        children: <Widget>[
          TextField(
            controller: controller,
            decoration: InputDecoration(
              suffixIcon: IconButton(
                icon: Icon(Icons.close),
                onPressed: () {
                  // Workaround exception
                  // await Future.delayed(Duration(milliseconds: 10));
                  controller.clear();
                },
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```

**Comment by jifalops** [comment]
@HansMuller I'm surprised by how easy the ripple is broken here. This might be a critical bug. Just wanted to make sure you saw my last comment.

**Comment by jifalops** [comment]
This is basically the same as #35848, #35909, #36065, #36671, and similar to #17647. The workaround is to clear the controller after the next frame or some delay. I've read it's because clicking the suffix icon causes the field to gain focus, and then it attempts to select text, but there is no text.

**Comment by HansMuller** [comment]
@jifalops Thanks for the input, I've seen the test case and appreciate the [rollup of similar issues](https://github.com/flutter/flutter/issues/36324#issuecomment-518743967).

**Comment by justinmc** [comment]
The question is, should prefixes and suffixes pass taps through to the text field or not?

When vertical alignment was implemented for [Material](https://github.com/flutter/flutter/pull/34355) and [Cupertino](https://github.com/flutter/flutter/pull/34723), we made the decision to pass touch gestures through to the text field in all cases except for CupertinoTextField's built in clear button.  [This is the code](https://github.com/flutter/flutter/blob/7df82f728e44ceb33cd85e3684106b7db8915baa/packages/flutter/lib/src/cupertino/text_field.dart#L85-L91) where CupertinoTextField explicitly ignores taps on the clear button.

We could reverse the behavior and ignore taps on all prefixes and suffixes.  Or we could instead add new parameters like `ignoreTapsOnSuffix`.  @jifalops What do you think?  Any other ideas?

**Comment by jifalops** [comment]
It does seem like passing taps to the text field would be the right thing to do in principle. I'm not sure if Flutter has any mechanism to allow the suffix icon to consume the tap like in DOM. I kind of lean towards calling clear() on the controller during a tap should not cause an error either way.

**Comment by pparadox11** [comment]
Hi, @jifalops @justinmc, i was thinking about this topic when i upgraded from flutter 1.5 to 1.7, and that my whole app is pretty much broken by the fact than on 1.5 the textfield doesnt get the focus
when a suffix or prefix widget gets clicked and on 1.7 it gets focused. And in my opinion you should probably give a way to stop that propagation, because in some cases is not practical, for example:

Got a menu button icon as a prefix, and when clicked it opens the nav drawer, but with this new update
when clicking the menu icon, the textfield gets focused tries to open the keyboard and the drawer
together, as its not the way i intented for this to work, it always produces a very laggy experience.

Other case is like the minimal example given.

I think in case you dont provide a way to stop the focus on the textfield, a lot of the functionallity already given by the textfield with prefix/suffix, automatic icon coloring when focus, etc, has to be re-implemented on a new widget, by individuals/teams or a library.

Thanks looking forward to your responses :)

**Comment by jifalops** [comment]
Yeah I agree on the basis that when a prefix/suffix is a button, you most likely don't want the keyboard to pop up, and that the button use case is probably pretty central to the prefix/suffix. I still don't know if reverting the behavior would be better than adding a parameter to TextField. Just some thoughts.

**Comment by pparadox11** [comment]
Hi, if you revert the behavior means that it might break some other fixes/features on the changes occurred to the textfield, then maybe you shouldn't? Wouldn't be easier to provide a flag with a default value to ignore? Or it wouldn't be so easy to distinguish between cases:

1) IconButton: on click, ignore focus on textfield
2) Icon: on click, the textfield gets focused
3) Custom clickable widget

I mean if we need to pass a flag to each of the above cases, its not so bad right?
Being explicit maybe its better than being implicit?

**Comment by justinmc** [comment]
Unfortunately it's not possible to do something like `event.stopPropagation()` from the web world in Flutter, because Flutter uses an "event arena" model instead of event bubbling like the web.

I'm thinking the idea of some flag/flags on TextField would be a good solution.

**Comment by callumclift** [comment]
any updates on this? it's pretty much broken all of my text fields as i use the suffix icon to allow users to clear their text

**Comment by justinmc** [comment]
@callumclift I'll try to put up a "work in progress" PR as a proposal for how we might solve this later today.  I'll post back here when I do.

**Comment by justinmc** [comment]
@callumclift (and anyone else that is interested) please let me know what you think of this approach! https://github.com/flutter/flutter/pull/38722

**Comment by callumclift** [comment]
@justinmc sounds good, how are you coming along with a solution for Material? I'm using material TextFormField (due to its validator parameter which cupertino text fields don't have)

**Comment by justinmc** [comment]
Thanks, good to know that would work.  I'll keep that suffix tapping problem in mind as I build this.  It sounds like it should be fixed by this change.

I think I can solve the problem in Material in the same way (same two parameters), but the code will just be a bit more indirect.

**Comment by callumclift** [comment]
@justinmc awesome, any ideas on timescales for this?

**Comment by justinmc** [comment]
I wouldn't count on it landing in master for a few weeks.  I'm going to talk to some teammates about the Material solution tomorrow though and that will give me a better idea.

**Comment by callumclift** [comment]
@justinmc is there any updates on when a fix will be available on master roughly?

**Comment by JZ-at-TP** [comment]
This is preventing us from updating Flutter as well.

**Comment by callumclift** [comment]
@justinmc is there any progress on this that you know of?

**Comment by justinmc** [comment]
Here is an open issue about this problem: https://github.com/flutter/flutter/issues/39376

**Comment by patelkrunal78** [comment]
Very Similar To [How to add clear button to TextField Widget](https://icetutor.com/question/how-to-add-clear-button-to-textfield-widget)

**Comment by DeveloperWaybee** [comment]
Here's the solution for a suffix or prefix taps

https://github.com/flutter/flutter/issues/36948#issuecomment-599797015
