### ISSUE TITLE
#ios #App Review Flutter App being rejected by Apple saying it contains hidden feature.

### ISSUE THREAD

**Issue by Oklahomawhore** [flutter/flutter#36338]
My recent simple todo list app was rejected by apple saying it "contains hidden features or functionality that can change the behavior of the app after review", though repeated asked for exactly what hidden feature, the app review team did not response with a clarified answer and repeats the same phrase over and over again.

Here's the full comment from Apple:

```Hello,

Thank you for your reply. 

We continue to find that your app contains hidden features or functionality that can change the 
behavior of the app after review. To resolve this issue, it would be appropriate to ensure that all 
features and functions in the app are visible and fully accessible during review.


Deliberate disregard of the App Store Review Guidelines and attempts to deceive users or undermine 
the review process are unacceptable and is a direct violation Section 3.2(f) of the Apple Developer 
Program License Agreement. Continuing to violate the Terms & Conditions of the Apple Developer 
Program will result in the termination of your account, as well as any related or linked accounts, and 
the removal of all your associated apps from the App Store.



We look forward to reviewing your resubmitted app.


Best regards,

App Store Review
```

Here is the initial reject message: 

```Jul 15, 2019 at 12:39 AM
From Apple
Guideline 1.5 - Safety - Developer Information


The support URL specified in your app’s metadata, http://www.runnerlimitless.club/simplethings.html, does not properly navigate to the intended destination.

Next Steps

To resolve this issue, please revise your app’s support URL to ensure it directs users to a webpage with support information.

Guideline 2.3.1 - Performance


We discovered that your app contains hidden features. Attempting to hide features, functionality or content in your app is considered egregious behavior and can lead to removal from the Apple Developer Program.

Specifically, your app contains financial transactions without the necessary authorization.

If you feel that we have misunderstood how your app functions and that your app is compliant with the App Store Review Guidelines, please reply to this message in Resolution Center to explain how this feature works.

The next submission of this app may require a longer review time, and this app will not be eligible for an expedited review until this issue is resolved.

Next Steps

- Review the Performance section of the App Store Review Guidelines.
- Ensure your app, as well as any third-party code and SDKs implemented in your app, are compliant with all sections of the App Store Review Guidelines and the Terms & Conditions of the Apple Developer Program.
- Revise or remove the hidden features from your app. Once your app is fully compliant, resubmit your app for review.

Submitting apps designed to mislead or harm customers or evade the review process may result in the termination of your Apple Developer Program account. Review the Terms & Conditions of the Apple Developer Program to learn more about our policies regarding termination.```

**Comment by jmagman** [comment]
Are you using any plugins?

**Comment by Oklahomawhore** [comment]
maybe flutter's not the problem, I appealed and it is approved. And I still don't know why.

**Comment by qinzhe** [comment]
I also encountered this problem, how do you solve it?

Guideline 2.3.1 - Performance


We discovered that your app contains hidden features. Attempting to hide features, functionality or content in your app is considered egregious behavior and can lead to removal from the Apple Developer Program.

Specifically, your app contains real money gambling functionality without the necessary licensing and permissions.

**Comment by ydolotov** [comment]
Hello!

I am having the same issue now - they say that my app has gambling functionality... However, the app does not even have an in-app purchase.

**Comment by Mugen0** [comment]
Same issue here and the reply from Apple is exactly the same.

Plugins that I'm using:

  cupertino_icons: ^0.1.2
  path_provider: ^1.1.2
  sqflite: ^1.1.6+2
  intl: ^0.15.8
  shared_preferences: ^0.5.3+4
  overlay_support: ^1.0.1
  flutter_local_notifications: ^0.8.1
  local_auth: ^0.5.2+4

**Comment by jmagman** [comment]
Not sure if there's anything Flutter can do here, but maybe someone needs to reach out to Apple about the submission process if it's becoming common.  @tvolkert

**Comment by Oklahomawhore** [comment]
@Mugen0   I'm sensing some commonness here. d
I also used the plugins path_provider and sqflite.

**Comment by jmccarthy** [comment]
Same rejection here, also using path_provider and sqflite

**Comment by Mugen0** [comment]
Same as @Oklahomawhore, my app is approved now after I appealed. So I think Flutter or sqflite can be the problem here, as leading to misunderstanding in the machine check process. Currently, we may have to appeal every time we submit. @jmagman

**Comment by tvolkert** [comment]
We had our Apple representative within Google take a look, and the word is that these rejections (and later overturns on appeal) are entirely unrelated to Flutter's existence in the apps. As such, I'm going to close this issue, as Flutter is a red herring here.

**Comment by qinzhe** [comment]
my app rejected 4 times by this reason. In addition, I have also stated twice, for the same reason, without further explanation. It has taken a month.
the flutter version is 1.7.8+hotfix.4, and the dart version is 2.4.0. The following plugins are used:
Flutter_localizations:
Cupertino_icons: ^0.1.2
Shared_preferences: ^0.5.3+4
Firebase_core: ^0.4.0+6
Firebase_analytics: ^4.0.1
Firebase_admob: ^0.9.0+2

**Comment by yuying2012** [comment]
We have the same problem, but we don't even use flutter, we don't know how to solve it, can anyone help me？

**Comment by Xuhao** [comment]
Got same rejected reason here :(

We can't figure out where are hidden feature is.

We ask the reviewer for more details about **hidden features or functionality** , but we just got nothing useful.

**Comment by tvolkert** [comment]
@Xuhao v1.12.13 has been verified to be clean of any such issues.  If you're using that version, then it's possible that your app code or one of your plugins is using some undocumented APIs.

**Comment by leeewh** [comment]
@Oklahomawhore 
@Mugen0 
Hey,excuse me for interrupting.
Got same rejected reason here.
It seems that all of you have passed the appeal, but I don't know what to say in the appeal. Can you share your appeal? Maybe part of it.
Also, do you reply in the solution center or appeal an app rejection in "contact the app review team"?
thanks! :)

**Comment by zyx545792476** [comment]
> I also encountered this problem, how do you solve it?
> 
> Guideline 2.3.1 - Performance
> 
> We discovered that your app contains hidden features. Attempting to hide features, functionality or content in your app is considered egregious behavior and can lead to removal from the Apple Developer Program.
> 
> Specifically, your app contains real money gambling functionality without the necessary licensing and permissions.


Hello! How did you solve this problem in the end?
