### ISSUE TITLE
[web]: TextField on Firefox do not track caret move by keyboard

### ISSUE THREAD

**Issue by deckerst** [flutter/flutter#36339]
In a Flutter Web app, moving the cursor or modifying the selection of a `TextField` by pressing `<left>` `<right>` (with `<alt>` and other variations) on the keyboard works fine on Chrome. However, on Firefox the caret doesn't move. Also, the `TextEditingController` do not emit events for a change of selection in this case either.

Interestingly, the selection offset seems to be correctly tracked internally, because any letter key pressed after moving the cursor will be inserted at the expected position. It just doesn't match the visual feedback given by the blinking caret.

flutter_web version: commit 8d4c12a (June 29)
Mac OS X 10.14.5 18F132, locale en-KR

**Comment by yjbanov** [comment]
Merging into https://github.com/flutter/flutter/issues/32225

**Comment by AresVampire** [comment]
This is not working. `TextField` is working at the beginning, but once it loses focus, like tapping on button, then textfield doesn't work anymore.
