### ISSUE TITLE
[web]: <How to use shared_preferences in fluttet_web?>

### ISSUE THREAD

**Issue by xingchenxuanfeng** [flutter/flutter#36330]
How to use shared_preferences in fluttet_web?

**Comment by deckerst** [comment]
`shared_preferences` is for mobile only for now. You can use `localStorage` instead.
Cf https://github.com/flutter/flutter/issues/35116

**Comment by BondarenkoStas** [comment]
@xingchenxuanfeng I think it's safe to close the issue. If you disagree, please comment and I will reopen it right away.
