### ISSUE TITLE
[web]Flutter for web error in iPhone

### ISSUE THREAD

**Issue by wedcel** [flutter/flutter#36343]
When i run  the web page  in iPhone,  i  got  this error:  
![image](https://user-images.githubusercontent.com/3982317/61352712-a51ebe80-a8a0-11e9-8233-567974f0f699.png)
please help.

**Comment by BondarenkoStas** [comment]
@wedcel Is it still relevant? Please do not include screenshots of code/logs. This makes it extremely tedious to reproduce the issue, as we would have to manually transcribe your example.
Please provide your flutter doctor -v output.
