### ISSUE TITLE
palette_generator dont work method fromImageProvider

### ISSUE THREAD

**Issue by josuesan** [flutter/flutter#36340]
I use Palette Generator, my code is :
`Future<PaletteGenerator> _generatePalette(String imagePath) async {
    PaletteGenerator _paletterGenerator = await PaletteGenerator.fromImageProvider(
      AssetImage(imagePath),
      size: Size(110.0, 150.0),
      maximumColorCount: 20,
    );
    return _paletterGenerator;
  }`
and response with this bug:

Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.

Any can help me please !

**Comment by arpit** [comment]
Duplicate of #35339. Looks like this library broke with the 1.7 release of flutter

**Comment by arpit** [comment]
This is fixed in PaletteGenerator v 0.2.0. Can someone close this?

**Comment by josuesan** [comment]
Thanks @arpit i upgrade Palette Generator.
