### ISSUE TITLE
Integration test with browserstack or Kobiton

### ISSUE THREAD

**Issue by glassalle59** [flutter/flutter#36354]
Hello,

I want to automate tests on a flutter application. 
Because appium don't work on flutter app, I'm going to use **flutter_driver** (https://flutter.dev/docs/cookbook/testing/integration/introduction)

But I have a question, since I need the code to run my test, is it still possible to execute my test on a farm devices like browserstack or Kobiton sing capabilites ? 

Thanks per advance,

**Comment by jonahwilliams** [comment]
browserstack is for automating browser tests, flutter (mobile/desktop) does not compile to a web application. 

driver_tests require a host machine to run the test script and communicate with the target device. This generally makes it unsuited for the automated device farms.

**Comment by BondarenkoStas** [comment]
I think it's safe to close the issue. @glassalle59 if you disagree or something else to ask/say, please comment and I will re-open it right away.

**Comment by tinder-falood** [comment]
Looks like browserstack supports mobile app https://www.browserstack.com/accounts/subscriptions?tab=mobile-app-plans-tab

**Comment by pwicherski** [comment]
@jonahwilliams @BondarenkoStas @glassalle59 @tinder-falood 
Browserstack supports automation on real and virtual mobile devices.

Shall we reopen this issue or create a new one? :)
