### ISSUE TITLE
How to implement dialer app in flutter like using InCallService in android project

### ISSUE THREAD

**Issue by Nethram** [flutter/flutter#36362]
I have a `flutter` app which is used to make outgoing calls from inside the app. I am using `call_number` package of dart to make call from the app. But still the default call in-progress UI is showing, instead i need to stay in the app and control the call using the app itself. So in android i have implemented this using `InCallService` . Then i tried to implement this by implementing this in native android side and calling the methods using `Platform MethodChannels` from flutter side. It is not working and showing so many issues regarding importing packages in android side. Do you have any idea to implement this in flutter side or fix the issues in native android side guys. Please help.
Any help would be appreciated. Thanks.

stackoverflow link for this post : https://stackoverflow.com/questions/57075798/how-to-implement-dialer-app-in-flutter-like-using-incallservice-in-android-proje

**Comment by BondarenkoStas** [comment]
@Nethram I saw an answer on SO, was it helpful? Is this issue still actual?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
