### ISSUE TITLE
Some JSON objects are so complex that it's a nightmare to rely on manual decoding

### ISSUE THREAD

**Issue by zhuxiujia** [flutter/flutter#36374]
Some JSON objects are so complex that it's a nightmare to rely on manual decoding。

Can we change it to reflective analytic JSON in the later stage?

Other languages such as go and Java are all reflective parsing json's。

**Comment by zhuxiujia** [comment]
Or learn the Rust language and use macros to encode and parse Json. It can be done in static analysis of code？

**Comment by yringler** [comment]
The [docs](https://flutter.dev/docs/development/data-and-backend/json#serializing-json-using-code-generation-libraries) discuss using code generation. I'm using it in my project, and it's pretty straight forward.

It doesn't look like reflective JSON is ever going to be used. As per [discussion on the gson](https://flutter.dev/docs/development/data-and-backend/json#is-there-a-gsonjacksonmoshi-equivalent-in-flutter), reflection interferes with tree shaking and so is disabled.

As regards to rust- flutter is very deeply tied to dart, relying on it's syntax to write pleasant ui heavy code and its quick allocation of small objects, and probably lots more. It won't be changing language anytime soon, imo.

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
