### ISSUE TITLE
[Feature Request] Enable a custom obscuring character to be set for password fields

### ISSUE THREAD

**Issue by nirav4273** [flutter/flutter#36377]
In `TextFormField` need to set password field value from `dot` to `asterisk `.
As below image.
![AdobeStock_50144597-796x529](https://user-images.githubusercontent.com/22423754/61393110-dff31780-a8dd-11e9-8f99-4728782be1a0.jpeg)

**Comment by shyndman** [comment]
Take a look at [`TextField.obscureText`](https://api.flutter.dev/flutter/material/TextField/obscureText.html).

Also, there's an active community on StackOverflow that can generally help with this kind of issue. Take a look!

**Comment by nirav4273** [comment]
@shyndman  It's set text into dot format. I need to change from `dot`  to `asterisk ` format as showing in image.

**Comment by shinriyo** [comment]
@nirav4273
I want to replace dot to asterisk too.
Not `U+2022 BULLET characters`.

@timsneath It is not resolved.

**Comment by timsneath** [comment]
Ah, so you're asking to change the character used for masking passwords? That's not a property we expose in Flutter. It's controlled by `obscuringCharacter`, which is a constant value in the `RenderEditable` class. 

I'll reopen this issue and mark it as a feature request, but to set expectations, this is a fairly obscure request (e.g. the web doesn't support this as a standard feature either), so the added complexity may not justify the feature. In the meantime, the workaround would be to clone the `TextField` class and modify it to use a different `RenderEditable` class that has the value you want.

**Comment by shinriyo** [comment]
@timsneath 
> Ah, so you're asking to change the character used for masking passwords? 
Yes, we are.
Thank you.

**Comment by jargalbat** [comment]
thank you very much :)

**Comment by shinriyo** [comment]
Thanks a lot

**Comment by aditya-m123** [comment]
Change password image in flutter from circle to * by just entering obscuringCharacter and shape you wanted eg - 

 obscuringCharacter: '*', 
 obscureText: true,
