### ISSUE TITLE
[video_player] Android: Upgrade exoplayer to 2.10.x

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#36375]
ExoPlayer 2.10 contains some bug fixes and new features might be valuable to the video_player plugin.

**Comment by BugsBunnyBR** [comment]
@cyanglaz , is there anything I could do/write to speed up this ticket?

**Comment by cyanglaz** [comment]
@BugsBunnyBR we need some sort of integration test to this plugin so we know it won't break and also reduce the maintenance burden in the future. I currently don't have an idea on how we can test this plugin.
cc @collinjackson may have some thoughts.

**Comment by ened** [comment]
ExoPlayer does change parts of the public API once in a while so the build server will complain if that changed significantly.

Some of the components are loaded using reflection or by module lookups. `video_player` currently does not provide any mechanism for developers to customise the set of modules, besides a fork.

The playback is hardware dependent and may or may not work at the same testable parameters for each phone under test.

IMHO, there should be enough tests to ensure Dart <-> Java calls work and call the right thing, anything after that could possibly be tested as part of a public Flutter release?

**Comment by otopba** [comment]
Any updates from July ? =)

**Comment by hamdikahloun** [comment]
ExoPlayer upgraded to latest version 2.12.1. 
PR Merged : https://github.com/flutter/plugins/pull/3204

Thank you

**Comment by hamdikahloun** [comment]
video_player 0.11.1+3 published.
```
0.11.1+3 :
Android: Upgrade ExoPlayer to 2.12.1.
```
