### ISSUE TITLE
NavigationDelegate throws IllegalStateException

### ISSUE THREAD

**Issue by calvingoc** [flutter/flutter#36387]
While trying to limit where a user can go via a WebView with a NavigationDelegate it will throw an IllegalStateException if NavigationDecision.prevent is ever used.

## Steps to Reproduce

Using webview_flutter ^0.3.10+2 

Using a custom navigationDelegate leads to the exception being thrown.

            body: WebView(
              initialUrl: selectedUrl,
              javascriptMode: JavascriptMode.unrestricted,
              navigationDelegate: (NavigationRequest request){
                //TODO here is where we can allow or block navigation;
                debugPrint("Navigating " +request.url.toString());
                if (request.url.startsWith('https://www.google.com')) return 
                          NavigationDecision.navigate;
                final snackBar = SnackBar(content: Text("Blocked leaving google.com"),);
                Scaffold.of(this.context).showSnackBar(snackBar);

                  return NavigationDecision.prevent;

              },

If you try and navigate past google an error will be thrown and the snackbar never gets shown.

## Logs
```
etc E/MethodChannel#plugins.flutter.io/webview_0: Failed to handle method call result
    java.lang.IllegalStateException: navigationRequest calls must succeed
        at io.flutter.plugins.webviewflutter.FlutterWebViewClient$OnNavigationRequestResult.error(FlutterWebViewClient.java:157)
        at io.flutter.plugin.common.MethodChannel$IncomingResultHandler.reply(MethodChannel.java:201)
        at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:114)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:653)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)


```
```

[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at C:\FlutterSDK\flutter
    • Framework revision b712a172f9 (8 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\cgehred\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • Pixel • FA75C0302167 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.

```

**Comment by BondarenkoStas** [comment]
@calvingoc Is it the same using current flutter stable or master with webview_flutter 0.3.14+1?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by jiajunhuang** [comment]
I've met this error, too. My flutter version is:

```
$ flutter --version
Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (3 months ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
```

webview version is:

```
$ grep webview pubspec.yaml 
  webview_flutter: ^0.3.16
```

**Comment by jiajunhuang** [comment]
code is here:

```dart
        body: WebView(
          initialUrl: homePage,
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController webViewController) {
            _controller.complete(webViewController);
          },
          navigationDelegate: (NavigationRequest request) async {
            var url = request.url;
            if (url.startsWith("https://jiajunhuang.com/")) {
              print("context: $context");
              Scaffold.of(context).showSnackBar(SnackBar(content: Text("访问$url"),));
            }
            print("visit $url");

            return NavigationDecision.navigate;
          },
        ),
```

**Comment by gtux** [comment]
Hi, I get this error too. 
I'm trying to authenticate over my IDP by using SAML protocol. Also this is over Cognito User Pools infrastructure. So the webview first loads my domain oauth2, that shows one button in order to select my IDP, when the user tap on that button then redirects to my IDP.

On IOS this flow works well, but in Android I get this issue.

`$ flutter --version`
`Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git`
`Framework • revision 27321ebbad (3 weeks ago) • 2019-12-10 18:15:01 -0800`
`Engine • revision 2994f7e1e6`
 `Tools • Dart 2.7.0`

`webview_flutter: ^0.3.18+1`

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
