### ISSUE TITLE
flutter_attach_test.dart appears flaky (Windows)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#36382]
`flutter_attach_test.dart` times out on Windows.

**Comment by zanderso** [comment]
@jonahwilliams On the theory that this is having flaky time-outs due to the slow DevFS issue, is there already an issue open to switch the integration tests to an in-memory filesystem that this can be linked to?

**Comment by christopherfujino** [comment]
@jonahwilliams ping about question above ^

**Comment by Hixie** [comment]
I don't see anything in this test that skips it on Windows, so I'm closing this issue.
