### ISSUE TITLE
Tool should generate/update the BUILD.gn file with --update-packages --force-upgrade

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#36395]
This would have caught or made https://github.com/flutter/flutter/pull/36394 irrelevant. For inspiration there is already a script in fuchsia to generate gn from pubspec files.

cc @zanderso

**Comment by zanderso** [comment]
@cbracken this will help with the Flutter -> Fuchsia rolls. Would anyone on your team be interested in picking this one up?

**Comment by jonahwilliams** [comment]
This will be obsolete since we're moving these files out of the repo anyway
