### ISSUE TITLE
Dart VM crash within the TypeCheck runtime entry point

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#36398]
## Steps to reproduce:

1. Download and install the following APK: [app-production-releases-master.zip](https://github.com/flutter/flutter/files/3389487/app-production-releases-master.zip)

1. Run the app

## Observed behavior

Copied from @angel1st in https://github.com/flutter/flutter/issues/35838#issuecomment-511124589:

> I have tested 32 version on S3 mini (Android 4.1.2) and 64 on S8 (Android 9). On both phones I have the same use case - after the app is installed and started I can see the splash screen for a moment, then the app closes.

## More details:

In https://github.com/flutter/flutter/issues/35838#issuecomment-511919684, @jason-simmons said:

> Ran the provided APK on a Nexus 5X, got a segfault, and symbolized the stack trace:
> ```
> third_party/dart/runtime/vm/compiler/../object.h:847
> third_party/dart/runtime/vm/runtime_entry.cc:782
> lib/arm/libapp.so (offset 0x1000) (_kDartVmSnapshotInstructions+10668)
> ```

**Comment by tvolkert** [comment]
@a-siva perhaps @angel1st can provide more info if you have specific details you'd like?

**Comment by angel1st** [comment]
@tvolkert - thanks again for moving thing forward, I appreciate that!
@a-siva - let me know shall you need any further feedback on my end.

**Comment by a-siva** [comment]
@angel1st is there a possibility for us to get a reproduction from source?

**Comment by tvolkert** [comment]
If not the full source, perhaps you can distill the code down to a reproducible case that you're allowed to share?

**Comment by tvolkert** [comment]
@angel1st out of curiosity, can you try this on the beta channel (and upgrade to pick up latest beta)?  I just pushed `v1.7.8+hotfix.4` to the beta channel, and I'm curious if your app works against that release.  If it does, it means that this bug in the Dart VM has been introduced in a Dart commit newer than Dart 2.4.0.

Thanks.

**Comment by a-siva** [comment]
Please see https://github.com/flutter/flutter/wiki/Issue-hygiene#provide-reduced-test-cases for our general guidelines on providing source code that reproduces the problem.

**Comment by angel1st** [comment]
thanks, @tvolkert and @a-siva. Let me try each of the suggestions above, I will come back a.s.a.p.

**Comment by angel1st** [comment]
@tvolkert - I can confirm, the apks built with `v1.7.8+hotfix.4` run flawlessly on each of my test devices as specified below. Thank you very much for the excellent suggestion!
- `app-production-armeabi-v7a-release` runs on S3 mini - Android 4.1.2 and S8 Android 9
- `app-production-arm64-v8a-release` - runs on S8 Android 9

Here is my `flutter doctor -v` output:

> [√] Flutter (Channel beta, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at E:\DevTools\flutter
    • Framework revision 20e59316b8 (29 hours ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\DevTools\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_SDK_ROOT = E:\DevTools\Android\Sdk
    • Java binary at: E:\DevTools\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

> [√] Android Studio (version 3.4)
    • Android Studio at E:\DevTools\android-studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270


> [!] Connected device
    ! No devices available


Please find enclosed both APKs compiled with the above flutter version - 
[p15-production-release.zip](https://github.com/flutter/flutter/files/3413355/p15-production-release.zip)

@tvolkert - I guess, once the above hotfix has been released to `stable` channel, everything should be ok, shouldn't it?

@a-siva - do you still need app sources? I will have to strip then down to exclude some app logic prior sending to you...

**Comment by tvolkert** [comment]
@angel1st fantastic! This issue is still valid, and it would still be helpful for you to strip down the sources and send a reproducible case to @a-siva 

Basically, here's the sequence of events:

1. `v1.7.8+hotfix.3` - contains the 32/64 Android buildfix, but also contains the "`libapp.so` not found" bug on some older Samsung devices
1. _some unknown commit_ - introduces a crash in the Dart VM
1. https://github.com/flutter/engine/pull/9762 - fixes the "`libapp.so` not found" issue.  If you sync to this commit to pick up the fix, you also pick up the Dart VM crasher bug.
1. `v1.7.8+hotfix.4` - _cherrypicks_ the fix into the release branch without picking up the crasher.

That is all to say: the crasher _still exists_ on master and is tracked by this issue.  But the cherrypick will ensure that you can use the stable channel (once we promote `v1.7.8+hotfix.4` to stable in the next few days) and get the fixes you desire while we find and fix the crasher bug on master.

Make sense?

**Comment by angel1st** [comment]
@tvolkert - thanks again for your prompt feedback! All makes sense.
I will block some time in the next days to prepare sources @a-siva can use to track down # 2 from the list above and I hope, once `v1.7.8+hotfix.4` touches the `stable` channel you will find a way to let me know.

**Comment by angel1st** [comment]
@tvolkert , @a-siva - I believe I was able to strip down the sources to the minimum possible version. At least I have problem to send you these sources. 
Please, take a look at the attached APKs to confirm they failed with the same error - 
[p15-production-arm64-v8a-release-master.zip](https://github.com/flutter/flutter/files/3416898/p15-production-arm64-v8a-release-master.zip)

This is my `flutter doctor -v` output:

> [√] Flutter (Channel master, v1.8.2-pre.30, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
    • Flutter version 1.8.2-pre.30 at E:\DevTools\flutter
    • Framework revision 13382f41c0 (9 days ago), 2019-07-12 23:24:04 -0700
    • Engine revision 919e353236
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 24725a8559)


> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\DevTools\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_SDK_ROOT = E:\DevTools\Android\Sdk
    • Java binary at: E:\DevTools\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

> [√] Android Studio (version 3.4)
    • Android Studio at E:\DevTools\android-studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

> [√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Windows                   • Windows       • windows-x64    • Microsoft Windows [Version 10.0.17763.615]
    • Chrome                    • chrome        • web-javascript • Google Chrome 75.0.3770.142

> ! Doctor found issues in 1 category.

The easiest option for me is to send you over an email the zipped sources, let me know however, if you have another preferable option.

**Comment by tvolkert** [comment]
@angel1st thank you!  I'll let @a-siva try to reproduce the issue with the most recent APK.  In the meantime, before you send the code, can you sign the CLA at https://cla.developers.google.com/, so that we're allowed to look at your code? 🙂

**Comment by angel1st** [comment]
@tvolkert - I have just signed CLA. No word from @a-siva yet, however.

**Comment by jason-simmons** [comment]
I tried running the latest APK.  It crashes with a stack trace that matches the one from the previous APK.

**Comment by angel1st** [comment]
excellent! @jason-simmons - let me know how shall I handover the sources, then.

**Comment by tvolkert** [comment]
The easiest way is to either (1) attach the source in a ZIP file here, or (2) create a repo and add us as contributors.

Thank you very much for your help in tracking this down!

**Comment by angel1st** [comment]
Here they are: 
[p15.zip](https://github.com/flutter/flutter/files/3429936/p15.zip)

Command to compile
`flutter build apk --target="lib/config/main_production.dart" --flavor=production --split-per-abi`

**Comment by jason-simmons** [comment]
Looks like this was fixed by https://github.com/dart-lang/sdk/commit/63120303a7496cb36967b69937cadd2c39e82386

Try it again with the latest Flutter master branch.

**Comment by angel1st** [comment]
@jason-simmons - yes, everything seems ok now. Thanks for the feedback to you and @tvolkert!

**Comment by angel1st** [comment]
@tvolkert - I have another small issue, which I will put here, please let me know if I have to make a separate issue for it:
When I uploaded both APKs to Google Play Console, I have following warning - identical for each one:
> This APK results in unused code and resources being sent to users. Your app could be smaller if you used the Android App Bundle. By not optimizing your app for device configurations, your app is larger to download and install on users' devices than it needs to be. Larger apps see lower install success rates and take up storage on users' devices.

Please, note I am using Proguard for sources minimization and obfuscation and I did not have this warning with previous releases.

**Comment by tvolkert** [comment]
@angel1st, are you uploading an app bundle or an apk?

**Comment by angel1st** [comment]
@tvolkert - I am uploading two APKs

**Comment by tvolkert** [comment]
Gotcha.  It's basically telling you that you'll get better results uploading an app bundle (the Play Store is encouraging all developers to switch to app bundles).

In any case, I'm going to close this issue, since the original issue is fixed at master.  Thanks for your help tracking down the various issues, and feel free to open issues for any new bugs you find!
