### ISSUE TITLE
cannot find symbol

### ISSUE THREAD

**Issue by flash-gh** [flutter/flutter#36400]
C:\Users\User\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+10\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:9: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
C:\Users\User\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+10\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:10: error: cannot find symbol
import androidx.annotation.Nullable;
                          ^

**Comment by bradyt** [comment]
I see this issue with `flutter create --template=plugin`. I have the same issue trying to import `NonNull` as described above.

![Screen Shot 2019-07-27 at 4 34 48 PM](https://user-images.githubusercontent.com/6107051/62000483-01e25c00-b08d-11e9-85b5-ce05dfb3844a.png)

**Comment by bradyt** [comment]
Hello @collinjackson , I just went ahead and filed a new issue, in case the present issue was just seen as a firebase issue.

**Comment by bradyt** [comment]
@flash-gh I wonder if my fix in the linked issue works for you.

**Comment by flash-gh** [comment]
@bradyt I have been able to solve the issue. its was a package issue. I had to make it 

firebase_auth:
and insert 
android.useAndroidX=true
android.enableJetifier=true



thanks for ur help. setting the firebase_auth to the current version caused this issue

**Comment by collinjackson** [comment]
I'm hoping that flutter/plugins#1917 will help.

**Comment by kroikie** [comment]
@flash-gh

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1096. Any further collaboration will be done there.
