### ISSUE TITLE
[web]: TextSpan recognizer is ignored when style is defined

### ISSUE THREAD

**Issue by deckerst** [flutter/flutter#36427]
The following `RichText` (with a styled and clickable `TextSpan`) works fine in regular Flutter but does not with Flutter Web:

```dart
          RichText(
            text: TextSpan(
              text: 'Regular text and ',
              style: DefaultTextStyle.of(context).style,
              children: [
                TextSpan(
                  style: TextStyle(decoration: TextDecoration.underline),
                  text: 'a link',
                  recognizer: TapGestureRecognizer()
                    ..onTap = () => debugPrint('tapped the link'),
                ),
              ],
            ),
          )
```

With Flutter Web, the link recognizer is ignored when the link style (the one with decoration) is defined. When the style is removed, the recognizer works as expected.

flutter_web version: commit 8d4c12a (June 29)
Mac OS X 10.14.5 18F132, locale en-KR

**Comment by yjbanov** [comment]
Merging into https://github.com/flutter/flutter/issues/34931
