### ISSUE TITLE
No way to know whether DraggableScrollableSheet is expanded or collapsed

### ISSUE THREAD

**Issue by ferraridamiano** [flutter/flutter#36433]
I'm working with DraggableScrollableSheet and a FAB. I want the FAB be invisible if the DraggableScrollableSheet is expanded. I need to check the event of expansion
I tried to attach a listener to the scrollController and check the value of scrollController.offset. But I realized that the listener is triggered just when the DraggableScrollableSheet is completly expanded and not before. Is there another way to check if it is expanded or collapsed?

```dart
class _MyHomePageState extends State<MyHomePage> {
  double appbarSize = 0.08;
  double offsetVisibility=100.0;
  bool FAB_visibility=true;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SizedBox.expand(
          child: DraggableScrollableSheet(
        maxChildSize: 0.8,
        minChildSize: appbarSize,
        initialChildSize: appbarSize,
        builder: (BuildContext context, ScrollController scrollController) {
          _scrollListener() {
            print(scrollController.offset);              //<-----------this doesn't help
          }
          scrollController.addListener(_scrollListener);
          return Container(
            child: ListView.builder(
              controller: scrollController,
              itemCount: 25,
              itemBuilder: (BuildContext context, int index) {
                return ListTile(title: Text('Item $index'));
              },
            ),
          );
        },
      )),
      floatingActionButton: Visibility(
        visible: FAB_visibility,
        child: FloatingActionButton(
          child: Icon(Icons.add),
        ),
      ),
    );
  }
}
```

**Comment by HansMuller** [comment]
CC @dnfield

**Comment by dnfield** [comment]
Instead of adding a listener to the scroll controller, wrap your DraggableScrollableSheet in a `NotificationListener<DraggableScrollableNotification>`.  The event given to you there should have what you're looking for - if not, it's a bug.

We also should document this better than we do.

As far as the FAB goes, it should be shrinking as you drag the sheet up without any intervention from you... The scaffold has magic to do that.

**Comment by ferraridamiano** [comment]
Now, it works! I didn't find anywhere how to do it. I will answer my [own question on stackOverflow](https://stackoverflow.com/questions/57059314/how-do-you-know-if-draggablescrollablesheet-is-collapsed-or-expanded), I'm sure will help someone.
