### ISSUE TITLE
#webview_flutter plugins# When switch app to the background, it opens again, and the previous webview page displays a white screen.

### ISSUE THREAD

**Issue by luckmlc** [flutter/flutter#36437]
When opening multiple webview windows, switche app to the background, then switch back to the foreground, click the back button to return to previous webview window, find that all currently open webview windows display white screen.

Ios device has this problem，android is ok.

@kangwang1988 

see gif:

![webview_open_bug_15s](https://user-images.githubusercontent.com/48781697/61438068-32c9df00-a971-11e9-9b11-7f98d1d9843c.gif)

flutter: Channel stable, v1.7.8+hotfix.3
webview_flutter: ^0.3.10+2

My environment is as follows:

```
/Users/mayer/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.3 at /Users/mayer/development/flutter
    • Framework revision b712a172f9 (8 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mayer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • LECHENG的 iPhone • 319ce14e3c039f4f9f588e398878952f1f4ecba4 • ios • iOS 12.3.1

• No issues found!
```

main.dart  code:

```javascript
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      routes: {
        '/web_1':(BuildContext context) => WebPage(),
        '/web_2':(BuildContext context) => Web2Page(),
        '/web_3':(BuildContext context) => Web3Page(),
      },
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'webview 多开测试'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        backgroundColor: Color(0xff302e40),
        textTheme: TextTheme(
            title: TextStyle(fontSize: 18.0, fontStyle: FontStyle.normal)),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              '当打开多个webview窗口时，ios设备切到后台\n\n再切回App，返回上一层webview会白屏！',
              style: TextStyle(fontSize: 16),
            ),
            Padding(padding: EdgeInsets.only(top: 50),),
            RaisedButton(
              child: Text('打开第一个webview'),
              color: Colors.limeAccent,
              onPressed: (){
                Navigator.pushNamed(context,'/web_1');
              },
            ),
          ],
        ),
      ),
    );
  }
}

class WebPage extends StatefulWidget {
  @override
  _WebPageState createState() => _WebPageState();
}

class _WebPageState extends State<WebPage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: PreferredSize(
          child: AppBar(
            title: Text('web_1'),
            actions: <Widget>[
              Container(
                padding: EdgeInsets.all(10),
                child: RaisedButton(
                  child: Text('open2'),
                  color: Colors.limeAccent,
                  onPressed: (){
                    Navigator.pushNamed(context,'/web_2');
                  },
                ),
              ),
            ],
            centerTitle: true,
            backgroundColor: Color(0xff302e40),
            textTheme: TextTheme(
                title: TextStyle(fontSize: 18.0, fontStyle: FontStyle.normal)),
          ),
          preferredSize:
          Size.fromHeight(MediaQuery.of(context).size.height * 0.06),
        ),
        body: Builder(builder: (BuildContext context) {
          return WebView(
            initialUrl: 'https://flutter.dev',
            javascriptMode: JavascriptMode.unrestricted,
            onWebViewCreated: (WebViewController webViewController) {

            },
            javascriptChannels: <JavascriptChannel>[
            ].toSet(),
            onPageFinished: (String url_str) {
              print('Page finished loading: $url_str');
            },
          );

        }
        ));
  }
}

class Web2Page extends StatefulWidget {
  @override
  _Web2PageState createState() => _Web2PageState();
}

class _Web2PageState extends State<Web2Page> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: PreferredSize(
          child: AppBar(
            title: Text('web_2'),
            actions: <Widget>[
              Container(
                padding: EdgeInsets.all(10),
                child: RaisedButton(
                  child: Text('open3'),
                  color: Colors.limeAccent,
                  onPressed: (){
                    Navigator.pushNamed(context,'/web_3');
                  },
                ),
              ),
            ],
            centerTitle: true,
            backgroundColor: Color(0xff302e40),
            textTheme: TextTheme(
                title: TextStyle(fontSize: 18.0, fontStyle: FontStyle.normal)),
          ),
          preferredSize:
          Size.fromHeight(MediaQuery.of(context).size.height * 0.06),
        ),
        body: Builder(builder: (BuildContext context) {
          return WebView(
            initialUrl: 'https://pub.dev',
            javascriptMode: JavascriptMode.unrestricted,
            onWebViewCreated: (WebViewController webViewController) {

            },
            javascriptChannels: <JavascriptChannel>[
            ].toSet(),
            onPageFinished: (String url_str) {
              print('Page finished loading: $url_str');
            },
          );

        }
        ));
  }
}


class Web3Page extends StatefulWidget {
  @override
  _Web3PageState createState() => _Web3PageState();
}

class _Web3PageState extends State<Web3Page> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: PreferredSize(
          child: AppBar(
            title: Text('web_3'),
            centerTitle: true,
            backgroundColor: Color(0xff302e40),
            textTheme: TextTheme(
                title: TextStyle(fontSize: 18.0, fontStyle: FontStyle.normal)),
          ),
          preferredSize:
          Size.fromHeight(MediaQuery.of(context).size.height * 0.06),
        ),
        body: Builder(builder: (BuildContext context) {
          return WebView(
            initialUrl: 'https://github.com',
            javascriptMode: JavascriptMode.unrestricted,
            onWebViewCreated: (WebViewController webViewController) {

            },
            javascriptChannels: <JavascriptChannel>[
            ].toSet(),
            onPageFinished: (String url_str) {
              print('Page finished loading: $url_str');
            },
          );

        }
        ));
  }
}

```

**Comment by mklim** [comment]
Thanks for the bug report with sample code to reproduce! Makes it much easier to debug.

/cc @amirh. This is ios only so it doesn't have anything to do with the Android threading workarounds.

**Comment by nuptdzs** [comment]
I also have this problem.
what can i do to fix this bug?
This problem has seriously affected our application online.

**Comment by nuptdzs** [comment]
what can I do to avoid or investigate this problem? @amirh

**Comment by nuptdzs** [comment]
i used pageView to avoid this problem.
when my webview turn to back,pageView jumpTo 1,when my webview turn to front pageView jumpTo 0.
such as this:

```
PageView(
                      controller: _pageController,
                      physics: NeverScrollableScrollPhysics(),
                      children: <Widget>[KeepStateWidget(webView), Center()])

```
when you whant to open another page,you need call changeWeb(false),when back you need to call changeWeb(true)

```
void changeWeb(bool show){
   _pageController.jumpToPage(show ? 0 : 1);
}

goPage(name){
  changeWeb(false);
  Navigator.pushNamed(name).then((result) {
    changeWeb(true);
  });
}
```
  
but i thank this is not the resolution to fix this problem.
This seems to be a bug in ios's handling of the hidden display of platforms view.
Flutter officials are expected to take this issue seriously and fix it as soon as possible.
Looking forward to reply。

**Comment by phamnhuvu-dev** [comment]
I also have this problem.

**Comment by leishuai** [comment]
FYI: In my situation, there is a flutter app bar. After you back from background and pop webview, the app bar still displays the popped app bar content. And for sure, the webview is blank.

**Comment by luckmlc** [comment]
@mklim @amirh 

Time has passed for a long time.
Is there any plan to fix this issue? 
Our flutter project is waiting for this issue to be resolved.
thanks.

**Comment by Dronaldo17** [comment]
> @mklim @amirh
> 
> Time has passed for a long time.
> Is there any plan to fix this issue?
> Our flutter project is waiting for this issue to be resolved.
> thanks.

how to fixit？

**Comment by phamnhuvu-dev** [comment]
I fixed it by cheating on iOS, I listen to the lifecycle, when the app goes background, set visible is false, then back foreground, set visible is true to rerender again.

```dart
Visibility(
    visible: !isBackground,
    child: Center(child: CircularProgressIndicator(),
)
```

**Comment by terrycain** [comment]
I have this issue too, still no joy with the Visibility example.

**Comment by luckmlc** [comment]
> I fixed it by cheating on iOS, I listen to the lifecycle, when the app goes background, set visible is false, then back foreground, set visible is true to rerender again.
> 
> ```dart
> Visibility(
>     visible: !isBackground,
>     child: WebView(),
> )
> ```

This will cause the webview page to be refreshed when it returns.

**Comment by phamnhuvu-dev** [comment]
@luckmlc Yes, I researched and what I think the problem comes from Platform View. 
When going back from background, the old frame of WebView is not clear, so I have to force rerender.

**Comment by luckmlc** [comment]
> @luckmlc Yes, I researched and what I think the problem comes from Platform View.
> When going back from background, the old frame of WebView is not clear, so I have to force rerender.

Forced rendering will cause form data in the web to be lost. 

Is there any other way?

**Comment by phamnhuvu-dev** [comment]
> Forced rendering will cause form data in the web to be lost.
> 
> Is there any other way?
You can use javascript communication to get from webview and refill data to webview.

**Comment by yutae** [comment]
I have this issue too. 😭 

This issue occurred only device (iPhone), not simulator.

**Comment by yutae** [comment]
This issue seems to be not just a `webview_flutter` plugin problem.
It seems to occur when the `PlatformView` is stacked on top of the `PlatformView`.
So I think it looks like an `flutter/engine` issue. 

------------------------

### Steps to Reproduce

`지식iN 성지 (PlatformView)` > Detail(`PlatformView`) >
App state background > App state foreground > navigation pop > 
Nothing is shown on the screen. 
However, it can be rendered again through user interaction. 
For example, tapping `BottomNavigationBarItem` will render the screen.

![issue](https://user-images.githubusercontent.com/14192093/66565572-c4767080-eb9d-11e9-8d2e-f1c4872d732f.gif)


> Flutter 1.9.1+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision cc949a8e8b (13 days ago) • 2019-09-27 15:04:59 -0700
> Engine • revision b863200c37
> Tools • Dart 2.5.0

> $flutter doctor
> [✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale ko-KR)
> ...
> • No issues found!

**Comment by kwongfung** [comment]
I also have this problem.

**Comment by kwongfung** [comment]
Waitting for help @Hixie

**Comment by kwongfung** [comment]
> i used pageView to avoid this problem.
> when my webview turn to back,pageView jumpTo 1,when my webview turn to front pageView jumpTo 0.
> such as this:
> 
> ```
> PageView(
>                       controller: _pageController,
>                       physics: NeverScrollableScrollPhysics(),
>                       children: <Widget>[KeepStateWidget(webView), Center()])
> ```
> 
> when you whant to open another page,you need call changeWeb(false),when back you need to call changeWeb(true)
> 
> ```
> void changeWeb(bool show){
>    _pageController.jumpToPage(show ? 0 : 1);
> }
> 
> goPage(name){
>   changeWeb(false);
>   Navigator.pushNamed(name).then((result) {
>     changeWeb(true);
>   });
> }
> ```
> 
> but i thank this is not the resolution to fix this problem.
> This seems to be a bug in ios's handling of the hidden display of platforms view.
> Flutter officials are expected to take this issue seriously and fix it as soon as possible.
> Looking forward to reply。

Hi It is useful to me, bug What KeepStateWidget means ?

**Comment by nuptdzs** [comment]
> > i used pageView to avoid this problem.
> > when my webview turn to back,pageView jumpTo 1,when my webview turn to front pageView jumpTo 0.
> > such as this:
> > ```
> > PageView(
> >                       controller: _pageController,
> >                       physics: NeverScrollableScrollPhysics(),
> >                       children: <Widget>[KeepStateWidget(webView), Center()])
> > ```
> > 
> > 
> > when you whant to open another page,you need call changeWeb(false),when back you need to call changeWeb(true)
> > ```
> > void changeWeb(bool show){
> >    _pageController.jumpToPage(show ? 0 : 1);
> > }
> > 
> > goPage(name){
> >   changeWeb(false);
> >   Navigator.pushNamed(name).then((result) {
> >     changeWeb(true);
> >   });
> > }
> > ```
> > 
> > 
> > but i thank this is not the resolution to fix this problem.
> > This seems to be a bug in ios's handling of the hidden display of platforms view.
> > Flutter officials are expected to take this issue seriously and fix it as soon as possible.
> > Looking forward to reply。
> 
> Hi It is useful to me, bug What KeepStateWidget means ? @nuptdzs

when you use pageView to switch page,the view will redo initState().
你在用pageView切换的时候会遇到重复执行initState的bug，所以用KeepState来包裹pageView里的内容，可以避免这个问题。
```dart
class KeepStateWidget extends StatefulWidget {
  final child;

  KeepStateWidget(this.child);

  @override
  State<StatefulWidget> createState() {
    return KeepStateState(child);
  }
}

class KeepStateState extends State<KeepStateWidget>
    with AutomaticKeepAliveClientMixin {
  final child;


  KeepStateState(this.child);

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return child;
  }

  @override
  bool get wantKeepAlive => true;
}
```

**Comment by KiuShuo** [comment]
> > > i used pageView to avoid this problem.
> > > when my webview turn to back,pageView jumpTo 1,when my webview turn to front pageView jumpTo 0.
> > > such as this:
> > > ```
> > > PageView(
> > >                       controller: _pageController,
> > >                       physics: NeverScrollableScrollPhysics(),
> > >                       children: <Widget>[KeepStateWidget(webView), Center()])
> > > ```
> > > 
> > > 
> > > when you whant to open another page,you need call changeWeb(false),when back you need to call changeWeb(true)
> > > ```
> > > void changeWeb(bool show){
> > >    _pageController.jumpToPage(show ? 0 : 1);
> > > }
> > > 
> > > goPage(name){
> > >   changeWeb(false);
> > >   Navigator.pushNamed(name).then((result) {
> > >     changeWeb(true);
> > >   });
> > > }
> > > ```
> > > 
> > > 
> > > but i thank this is not the resolution to fix this problem.
> > > This seems to be a bug in ios's handling of the hidden display of platforms view.
> > > Flutter officials are expected to take this issue seriously and fix it as soon as possible.
> > > Looking forward to reply。
> > 
> > 
> > Hi It is useful to me, bug What KeepStateWidget means ? @nuptdzs
> 
> when you use pageView to switch page,the view will redo initState().
> 你在用pageView切换的时候会遇到重复执行initState的bug，所以用KeepState来包裹pageView里的内容，可以避免这个问题。
> 
> ```dart
> class KeepStateWidget extends StatefulWidget {
>   final child;
> 
>   KeepStateWidget(this.child);
> 
>   @override
>   State<StatefulWidget> createState() {
>     return KeepStateState(child);
>   }
> }
> 
> class KeepStateState extends State<KeepStateWidget>
>     with AutomaticKeepAliveClientMixin {
>   final child;
> 
> 
>   KeepStateState(this.child);
> 
>   @override
>   void initState() {
>     super.initState();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     super.build(context);
>     return child;
>   }
> 
>   @override
>   bool get wantKeepAlive => true;
> }
> ```

非常感谢，的确能解决这个问题，但是我建议使用IndexedStack来维持界面状态，代码更加简洁。

**Comment by nuptdzs** [comment]
> > > > i used pageView to avoid this problem.
> > > > when my webview turn to back,pageView jumpTo 1,when my webview turn to front pageView jumpTo 0.
> > > > such as this:
> > > > ```
> > > > PageView(
> > > >                       controller: _pageController,
> > > >                       physics: NeverScrollableScrollPhysics(),
> > > >                       children: <Widget>[KeepStateWidget(webView), Center()])
> > > > ```
> > > > 
> > > > 
> > > > when you whant to open another page,you need call changeWeb(false),when back you need to call changeWeb(true)
> > > > ```
> > > > void changeWeb(bool show){
> > > >    _pageController.jumpToPage(show ? 0 : 1);
> > > > }
> > > > 
> > > > goPage(name){
> > > >   changeWeb(false);
> > > >   Navigator.pushNamed(name).then((result) {
> > > >     changeWeb(true);
> > > >   });
> > > > }
> > > > ```
> > > > 
> > > > 
> > > > but i thank this is not the resolution to fix this problem.
> > > > This seems to be a bug in ios's handling of the hidden display of platforms view.
> > > > Flutter officials are expected to take this issue seriously and fix it as soon as possible.
> > > > Looking forward to reply。
> > > 
> > > 
> > > Hi It is useful to me, bug What KeepStateWidget means ? @nuptdzs
> > 
> > 
> > when you use pageView to switch page,the view will redo initState().
> > 你在用pageView切换的时候会遇到重复执行initState的bug，所以用KeepState来包裹pageView里的内容，可以避免这个问题。
> > ```dart
> > class KeepStateWidget extends StatefulWidget {
> >   final child;
> > 
> >   KeepStateWidget(this.child);
> > 
> >   @override
> >   State<StatefulWidget> createState() {
> >     return KeepStateState(child);
> >   }
> > }
> > 
> > class KeepStateState extends State<KeepStateWidget>
> >     with AutomaticKeepAliveClientMixin {
> >   final child;
> > 
> > 
> >   KeepStateState(this.child);
> > 
> >   @override
> >   void initState() {
> >     super.initState();
> >   }
> > 
> >   @override
> >   Widget build(BuildContext context) {
> >     super.build(context);
> >     return child;
> >   }
> > 
> >   @override
> >   bool get wantKeepAlive => true;
> > }
> > ```
> 
> 非常感谢，的确能解决这个问题，但是我建议使用IndexedStack来维持界面状态，代码更加简洁。

起初我也考虑过用IndexedStack，但好像并不能解决这个问题。

**Comment by luckmlc** [comment]
Still have the same problem with the latest version

```
/Users/mayer/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel master, v1.10.15-pre.367, on Mac OS X 10.14.6 18G84, locale zh-Hans-CN)
    • Flutter version 1.10.15-pre.367 at /Users/mayer/development/flutter
    • Framework revision a192e29603 (29 minutes ago), 2019-10-31 19:31:42 -0700
    • Engine revision 8ea19b1c76
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mayer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • LECHENG的 iPhone • 319ce14e3c039f4f9f588e398878952f1f4ecba4 • ios • iOS 13.1.2

• No issues found!
Process finished with exit code 0

```

**Comment by amirh** [comment]
This is fixed in https://github.com/flutter/engine/pull/13469 which wasn't rolled into the framework yet. It should be rolled soon, if you want to give it a try before the roll you can use a locally built engine.
