### ISSUE TITLE
Add device type utils

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#36436]
It would be nice to have:
- Platform.isTablet
- Platform.isPhone 
- Platform.isDesktop 
- Platform.isWeb
to make it easy for custom implementations for phone and tablet.

**Comment by BondarenkoStas** [comment]
@vanlooverenkoen I would advise you to post it to https://github.com/dart-lang/sdk/issues as well as the Platform class is in the dart:io lib and is just used by flutter.

**Comment by darshankawar** [comment]
@vanlooverenkoen 
Is this still a valid issue ? 
If this still is, you may checkout [this](https://blog.gskinner.com/archives/2020/03/flutter-simplify-platform-detection-responsive-sizing.html) blog and see if it serves your need.
