### ISSUE TITLE
can I call EventChannel.receiveBroadcastStream twice?

### ISSUE THREAD

**Issue by kuiwy** [flutter/flutter#36448]
EventChannel _broadcast = const EventChannel('flutter_broadcaster')
_broadcast.receiveBroadcastStream("A");
_broadcast.receiveBroadcastStream("B");

when I finally registered B，i can only received data from stream B,
stream A don't work.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
