### ISSUE TITLE
Exited (sigterm)

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#36447]
launched on iphone SE 
flutter version 1.7.8

```
Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: C53C5K9PTM
Xcode build done.                                           12,0s
Configuring the default Firebase app...
Configured the default Firebase app __FIRAPP_DEFAULT.
Could not update files on device: OS Error: Connection reset by peer, errno = 54
Exited (sigterm)
```

**Comment by BondarenkoStas** [comment]
I think it's safe to close the issue as it doesn't provide any new info after mentioned issues.
@alex9153 Please confirm the question above, can you run it from Xcode or `flutter run --release` without issue? If not, it may be different and I will re-open the issue right away.
