### ISSUE TITLE
i want create table like this using data table or table in flutter

### ISSUE THREAD

**Issue by manjesha12** [flutter/flutter#36449]
![table](https://user-images.githubusercontent.com/52523326/61457419-e63cce80-a985-11e9-80c7-178722dc2352.png)  like this table, i am creating the tables not able create this kind of table. through flutter how can i create this.

**Comment by HansMuller** [comment]
Have you considered using the [DataTable](https://api.flutter.dev/flutter/material/DataTable-class.html) widget?

**Comment by manjesha12** [comment]
Yes tried

**Comment by VladyslavBondarenko** [comment]
@manjesha12 
I hope you've solved it.
Feel free to create a new issue with proposal for new feature if needed
