### ISSUE TITLE
flutter/packages Palatte can not work

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#36456]
```
void imageListener(ImageInfo info, bool synchronousCall) {
      loadFailureTimeout?.cancel();
      stream.removeListener(imageListener);
      imageCompleter.complete(info.image);
    }

    if (timeout != Duration.zero) {
      loadFailureTimeout = Timer(timeout, () {
        stream.removeListener(imageListener);
        imageCompleter.completeError(
          TimeoutException(
              'Timeout occurred trying to load from $imageProvider'),
        );
      });
    }
    stream.addListener(imageListener);
```

Those code can not work with newest flutter, how to change it?

**Comment by stuartmorgan** [comment]
@tvolkert This is from https://groups.google.com/forum/#!topic/flutter-announce/NWTszrEq9U0

Is there a standard process for updating first-party packages for breaking changes?

**Comment by jinfagang** [comment]
@stuartmorgan  I think the changes of new api has been made far way, the best way is to update old packages.

Those code is from flutter/packages palatte_genereator, Does it maintained by flutter team? Why not update it's down usage anyway?

That is a good package help us get domain color from a single image even a networkimage widget.

Or, if any instructions how to edit those `error warning code` is also ok, I can change it myself...

**Comment by stuartmorgan** [comment]
> Why not update it

That's exactly what my comment was suggesting.

**Comment by tvolkert** [comment]
> Is there a standard process for updating first-party packages for breaking changes?

Right now there's no standard way.  Ian has just set up in the past week a way to run non-framework tests as part of framework commits, so we should wire up packages and plugin tests into that system so we get alerted to such breakages.

In the meantime, this should just be updated by a willing soul, and since I don't like volunteering other people, I guess that willing soul is me 🙂

**Comment by tvolkert** [comment]
Fixed in https://github.com/flutter/packages/pull/24

**Comment by jinfagang** [comment]
@tvolkert  Seems willing soul has been resolved this issue, thanks so much! I will update that package!

**Comment by tvolkert** [comment]
I haven't merged the fix yet or published a new version, so re-opening.

**Comment by jinfagang** [comment]
@tvolkert  Thanks tvolkert!  Hope you can release it soon!

**Comment by zoeyfan** [comment]
Looking at the status of https://github.com/flutter/packages/pull/24, may I assume this has been fixed now, therefore can be closed?
