### ISSUE TITLE
Build Grandle error while i use both image_picker and qr_utils or any other scanners in flutter.

### ISSUE THREAD

**Issue by praveen3edge** [flutter/flutter#36450]
I am developing an application which uses both image picker and qr_utils packages for uploading the profile pic and scanning of qr codes . When i use the packages separately , no error throws when i use both in the same project it throws error like the image below.
Flutter :
Image_picker and qr_utils
![erroringradle](https://user-images.githubusercontent.com/49227585/61460323-1dae7980-a98c-11e9-86b6-7a03f0b25c73.png)

**Comment by BondarenkoStas** [comment]
@praveen3edge Is the issue still relevant? Can you please try it with current flutter stable and current image_picker and qr_utils? 
For later, please do not include screenshots of logs or code, as then one can't not just copy paste the content.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
