### ISSUE TITLE
WebView's headers are forced to lower case

### ISSUE THREAD

**Issue by joelbrostrom** [flutter/flutter#36464]
When loading an url with `.loadUrl(url, headers)` the header keys are automatically turned to lower case.

For example
```
_webViewController?.loadUrl(_myUrl, headers:  {'X-Device-OS': '${Platform.operatingSystem}'},);
```

Is received by back end as 
```
x-device-os : android 
```

Is there any way to skip the lower casing?

**Comment by yintaibing** [comment]
Got same issue...and if anyone can help?

**Comment by murphy-li** [comment]
bro, have you ever resovled it ?

**Comment by joelbrostrom** [comment]
No.
In the end I had to change to the webview plugin library.
Then I encountered a lot of different problems down the line and the project had to be converted to react native.
I've written two flutter apps currently in production since then, and the framework is by far my favorit.
With that being said, **stay away** from all things **WebView** related!

IAP integration is a bit clunky too, but possible to overcome.

Happy coding!

**Comment by stuartmorgan** [comment]
This is not within the control of the plugin; Android's WebView changes the case. See https://stackoverflow.com/questions/52091406/why-webview-header-key-converted-in-lowercase-in-android



> If possible ask your backend to make all header keys lower keys.

Note that any backend that is requiring a specific case is violating the HTTP spec.
