### ISSUE TITLE
FlutterPlugin  for app complete release apk error

### ISSUE THREAD

**Issue by devzwy** [flutter/flutter#36470]
First of all, thanks to every developer who has contributed to the flutter project, I have a question to ask. The project integrates flutter plugin, runs dart files and Android projects directly, and does not display pictures when it runs release package, and displays abnormal pictures when it uses icons. xx. I modified the configuration of the repackaged resource file in the flutter. gradle file and solved the problem. But I believe there are better solutions. Please help me see if there are similar problems. Flutter uses version 1.7.8, dart SDK version 2.4 thanks again.

**Comment by devzwy** [comment]
I revised the content probably here.[here](https://www.jianshu.com/p/e596a5e880ba)

**Comment by BondarenkoStas** [comment]
@devzwy Is the issue still relevant? Can you confirm it using current flutter stable or master? 
Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
