### ISSUE TITLE
Platform.executable and Platform.resolvedExecutable crash

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3648]
I just tried printing them and it didn't go well.

**Comment by eseidelGoogle** [comment]
Likely just some missing plumbing for our dart:io bindings.  @johnmccutchan or @jason-simmons could likely very easily fixed.

It's possible this sort of thing would be caught by being able to run the dart sdk tests in flutter: https://github.com/flutter/flutter/issues/3443

**Comment by rmacnak-google** [comment]
If by crash you mean throw exceptions, dart-lang/sdk#26417

**Comment by jason-simmons** [comment]
Platform.executable and Platform.resolvedExecutable are segfaulting on Flutter.

Flutter never calls Platform::SetExecutableName, and Platform.executable hands the null executable name to Dart_NewStringFromCString, which fails.

Platform.resolvedExecutable is trying to read the /proc/self/exe symlink, which is not available on Android.

**Comment by Hixie** [comment]
Once this is fixed, there's a TODO in material/about.dart that can be resolved.

**Comment by Hixie** [comment]
Looks like this is fixed, in fact.
