### ISSUE TITLE
[Web]: Using tooltip with long press causes issue with web across all browsers.

### ISSUE THREAD

**Issue by MichealReed** [flutter/flutter#36488]
I changed the longpress to ontap in tooltip.dart and everything is functional. It doesn't seem like the hover approach mentioned in there is working either, let me know if I need to open a separate issue.

```
  @override
  Widget build(BuildContext context) {
    assert(Overlay.of(context, debugRequiredFor: widget) != null);
    Widget result = GestureDetector(
      behavior: HitTestBehavior.opaque,
      onTap: _handleLongPress,
      excludeFromSemantics: true,
      child: Semantics(
        label: widget.excludeFromSemantics ? null : widget.message,
        child: widget.child,
      ),
    );
```

**Comment by BondarenkoStas** [comment]
@MichealReed What the issue exactly it causes? Is it reproducible using current flutter stable or master?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
