### ISSUE TITLE
Flutter engine + a POM can bring in fragment support via gradle

### ISSUE THREAD

**Issue by xster** [flutter/flutter#36499]
To accomplish https://github.com/flutter/flutter/issues/34444, test that an engine jar + POM can add a fragment dependency during the gradle build process

cc @matthew-carroll @blasten

**Comment by xster** [comment]
@blasten this is done now with the reland reland right?

**Comment by blasten** [comment]
Yep!

**Comment by xster** [comment]
That's one box checked off from that migration graph :D
