### ISSUE TITLE
Add plugin info to flutter doctor when run from a flutter app directory

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#36496]
## Use case

Knowing which plugins an app is using is helpful for triaging certain classes of issues.

## Proposal

When people create issues they are trained to paste the output of `flutter doctor -v`.  When it is run from a directory containing a pubspec.yaml, include the plugins and versions in the output.

**Comment by jmagman** [comment]
Also see https://github.com/flutter/flutter/issues/2885.

**Comment by christopherfujino** [comment]
@jmagman I'm closing this in favor of #2885; I added a comment there with this suggestion, as we should implement it if we ever do a new command.
