### ISSUE TITLE
Firebase Test Lab release smoke test flaky: "Error during preprocessing"

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#36501]
https://github.com/flutter/flutter/blob/master/dev/bots/firebase_testlab.sh

The test matrix on Firebase Test Lab is supposed to always be green (even on failures) and it greps the logs to get the test output. Some test results are showing up as "inconclusive" on the dashboard.

"Firebase Test Lab infrastructure failure: Error during preprocessing" on Cirrus

I see https://cirrus-ci.com/task/5663511022141440?command=test#L26

This is blocking autoroll of https://github.com/flutter/engine/commit/b7b791b3fa05fe06d778c56d8ad53897f8ef05cc which fixes a TODAY bug: https://github.com/flutter/flutter/issues/36079

Looks like it started passing again on its own.

Once #36503 is landed, I'll leave this issue open so we can remember investigate and figure out why it's sometimes flaking.

**Comment by goderbauer** [comment]
@collinjackson Is this still a problem? I am not seeing any recent reports, so I am intending to close this.

**Comment by goderbauer** [comment]
I am going to close this since we haven't seen it recently. Feel free to reopen with more information if this is still a problem.
