### ISSUE TITLE
about DragStartBehavior Properties of Switch

### ISSUE THREAD

**Issue by MonkeyInWind** [flutter/flutter#36505]
The default value in the document is DragStartBehavior.start.
![image](https://user-images.githubusercontent.com/34543887/61502139-255e3480-aa05-11e9-8cdd-28746aa62d27.png)
But when I wrote that, DragStartBehavior was undefind.
![image](https://user-images.githubusercontent.com/34543887/61502438-820e1f00-aa06-11e9-88e8-45f9d982cb99.png)

Was it my mistake or something else?

**Comment by HansMuller** [comment]
You need an extra import:

```
import 'package:flutter/gestures.dart' show DragStartBehavior;
```

**Comment by HansMuller** [comment]
There doesn't seem to be a bug here (see https://github.com/flutter/flutter/issues/36505#issuecomment-513869407); please reopen the issue if I'm mistaken.

**Comment by MonkeyInWind** [comment]
> You need an extra import:
> 
> ```
> import 'package:flutter/gestures.dart' show DragStartBehavior;
> ```

Thank you for your explanation.I didn't find it in the document.Maybe I didn't read the document carefully enough.
