### ISSUE TITLE
how to fix this Route issue in scope_model 

### ISSUE THREAD

**Issue by ReshanMaduka** [flutter/flutter#36519]
I/flutter (28769): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (28769): The following assertion was thrown while handling a gesture:
I/flutter (28769): Could not find a generator for route RouteSettings("/schedule/", null) in the _WidgetsAppState.
I/flutter (28769): Generators for routes are searched for in the following order:
I/flutter (28769):  1. For the "/" route, the "home" property, if non-null, is used.
I/flutter (28769):  2. Otherwise, the "routes" table is used, if it has an entry for the route.
I/flutter (28769):  3. Otherwise, onGenerateRoute is called. It should return a non-null value for any valid route not
I/flutter (28769):     handled by "home" and "routes".
I/flutter (28769):  4. Finally if all else fails onUnknownRoute is called.
I/flutter (28769): Unfortunately, onUnknownRoute was not set.
I/flutter (28769): 
I/flutter (28769): When the exception was thrown, this was the stack:
I/flutter (28769): #0      _WidgetsAppState._onUnknownRoute.<anonymous closure> (package:flutter/src/widgets/app.dart:770:9)
I/flutter (28769): #1      _WidgetsAppState._onUnknownRoute (package:flutter/src/widgets/app.dart:783:6)
I/flutter (28769): #2      NavigatorState._routeNamed (package:flutter/src/widgets/navigator.dart:1599:22)
I/flutter (28769): #3      NavigatorState.pushNamed (package:flutter/src/widgets/navigator.dart:1637:20)
I/flutter (28769): #4      HomeReleasedShiftCard._buildShiftList.<anonymous closure>.<anonymous closure> (package:employee_clocking/widgets/shift/home_release.dart:105:39)
I/flutter (28769): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
I/flutter (28769): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
I/flutter (28769): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
I/flutter (28769): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
I/flutter (28769): #9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:211:7)
I/flutter (28769): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (28769): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:225:20)
I/flutter (28769): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
I/flutter (28769): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (28769): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (28769): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (28769): #19     _invoke1 (dart:ui/hooks.dart:233:10)
I/flutter (28769): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
I/flutter (28769): (elided 3 frames from package dart:async)
I/flutter (28769): 
I/flutter (28769): Handler: onTap
I/flutter (28769): Recognizer:
I/flutter (28769):   TapGestureRecognizer#b55b0(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
I/flutter (28769):   Offset(246.2, 531.6), sent tap down)
I/flutter (28769): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by miquelbeltran** [comment]
```
Could not find a generator for route RouteSettings("/schedule/", null) in the _WidgetsAppState.
```

This tells you that your app can't find the route `/schedule/` in your MaterialApp routes. You probably have a typo in the name (e.g. your route is named `/schedule`)

**Comment by yashwp** [comment]
This is a well know issue, I'm also facing the same issue and opened one SO question as well [here](https://stackoverflow.com/questions/64051765/could-not-find-a-generator-for-route-routesettingschat-null-in-the-customt). Instead of closing the issue, Flutter should figure out what is causing the problem and provide the solution for the same.
