### ISSUE TITLE
Switch to ELF libraries broke x86->ARM translation

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#36518]
Prior to our switch to ELF libraries, Flutter apps worked in AOT mode on x86 devices that advertised ARM translation, such as the Asus ZenFone 2 (Intel Atom Z3560), or Chromebooks.

However, after our switch to ELF libraries, this stopped working.

From https://github.com/flutter/flutter/issues/31922#issuecomment-502586413:
> The ARM/ARM64 app bundles are getting installed by Google Play onto x86 devices that advertise support for ARM via translation, but the new appbundles somehow do not work correctly on such devices (perhaps because the new ELF formats confuse the ARM translator).

We should see if we can figure out what's breaking here and find out if we can get it back to a working state.  This is a functional regression for developers upgrading to our current stable release (`v1.7.8+hotfix.3`) from our previous stable release (`v1.5.4-hotfix.2`).

@rmacnak-google @jason-simmons

**Comment by truongsinh** [comment]
I understand the the reason we switch from AOT snapshot to ELF libraries is that the 4 AOT snapshot files (`vm_snapshot_instr/_data`  and `isolate_snapshot_instr/_data`) reside in the same dir (`assets`), and having a fat APK or universal AAB with this structure is impossible. However, if debugging ELF libraries on x86 (and potentially https://github.com/flutter/flutter/issues/36128?) takes too much time, what if we temporaily revert to use AOT snapshot files, but with CPU-dependent structure, like this:

```
lib
 |--armeabi-v7a
 |    |--libflutter.so
 |--arm64-v8a
 |    |--libflutter.so
assets
 |--armeabi-v7a
 |    |--vm_snapshot_instr
 |    |--vm_snapshot_data
 |    |--isolate_snapshot_instr
 |    |--isolate_snapshot_data
 |--arm64-v8a
 |    |--vm_snapshot_instr
 |    |--vm_snapshot_data
 |    |--isolate_snapshot_instr
 |    |--isolate_snapshot_data
 |--flutter_assets
 |    |--...
 
```

**Comment by matthewlloyd** [comment]
Really glad this is being looked at!

I checked the Device Catalog on the Google Play Console for my existing Flutter 32-bit-only ARM APK, which is live in production, and searched for devices with Intel chips. Apparently, it's installed on 266 distinct types of devices with Intel chips, representing 0.4% of installs of my app on active devices. That's not a lot, but enough to keep me from switching to AABs. In case it helps, I'm attaching the full list - hopefully someone on the team can get access to one or more of them.

[arm_translation_devices.xlsx](https://github.com/flutter/flutter/files/3411836/arm_translation_devices.xlsx)

All these devices must be using ARM translation. The list includes many Chromebooks from a variety of brands, phones and tablets from Asus and Acer, and many other devices from brands including Google (Chromebooks, Pixel Slate), Dell, Lenovo, Samsung (Galaxy Tab 3), and others. 

I only know for sure that the AABs crash on the Asus ZenFone 2, and with Flutter master as of early June. It's probably the same crash as the Chromebook one linked above, but it's possible it was a different bug that has already been fixed since then - I just have no way to test. If it's still an issue, it would probably affect the other devices in the list too.

Unfortunately the two users who told me about the crash have both removed their 1-star reviews, so I don't know what version of Android they were using.

**Comment by matthewlloyd** [comment]
Maybe good news. I created a Genymotion emulator with Android 8.0 on my x86 MacBook and installed the ARM Translation Tools (i.e. libhoudini) on it.

Then installed the AAB I uploaded to the Play Store in early June, the one which crashed on Asus ZenFone 2. (I used bundletool to install the AAB on the emulator, and confirmed the binary being installed is the armeabi_v7a version). It also crashed on the Genymotion emulator:

```
07-19 19:39:41.602  2813  2813 D houdini : [2813] loaded library /data/app/com.<redacted>-KhYNgWG9V4rksHf2yIxnUg==/lib/arm/libflutter.so via Native Bridge.
07-19 19:39:41.671  2813  2813 E flutter : [ERROR:flutter/fml/platform/posix/native_library_posix.cc(16)] Could not open library 'libapp.so' due to error 'dlopen failed: (null)'.
07-19 19:39:41.673  2813  2813 E flutter : [ERROR:flutter/fml/platform/posix/native_library_posix.cc(16)] Could not open library 'libapp.so' due to error 'dlopen failed: undefined symbol: _kDartVmSnapshotData'.
07-19 19:39:41.677  2813  2813 E flutter : [ERROR:flutter/runtime/dart_vm_data.cc(19)] VM snapshot invalid and could not be inferred from settings.
07-19 19:39:41.679  2813  2813 E flutter : [ERROR:flutter/runtime/dart_vm.cc(241)] Could not setup VM data to bootstrap the VM from.
07-19 19:39:41.681  2813  2813 E flutter : [ERROR:flutter/runtime/dart_vm_lifecycle.cc(89)] Could not create Dart VM instance.
07-19 19:39:41.683  2813  2813 F flutter : [FATAL:flutter/shell/common/shell.cc(218)] Check failed: vm. Must be able to initialize the VM.
07-19 19:39:41.683  2813  2813 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 2813 (com.<redacted>)
```

Then I updated to the latest Flutter dev channel release (Channel dev, v1.8.2), built a new AAB, and installed it in the same way. It works fine! Reran the experiment on the stable channel, v1.7.8+hotfix.3, and that works fine too.

So the original bug I reported last month may already have been fixed. Still doesn't explain the Chromebook crash though...

**Comment by bayuramadeza** [comment]
hey @tvolkert i have tried a beta channel, so i have new output after downloading the app from playstore and the app was crashed.

07-23 12:00:54.408 4272-4275/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
07-23 12:00:54.416 4272-4275/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [4, 0]
07-23 12:00:54.613 377-386/? E/cutils: Failed to openat(/storage/0403-0201): Permission denied
07-23 12:00:54.617 377-386/? E/cutils: Failed to openat(/storage/0403-0201): Permission denied
07-23 12:00:54.655 10223-10223/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 10223 (pkarir.topkarir)
07-23 12:00:54.657 520-520/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-23 12:00:54.657 520-520/? A/DEBUG: Build fingerprint: 'Xiaomi/helium/helium:6.0.1/MMB29M/V7.3.14.0.MBDCNDE:user/release-keys'
07-23 12:00:54.657 520-520/? A/DEBUG: Revision: '0'
07-23 12:00:54.657 520-520/? A/DEBUG: ABI: 'arm64'
07-23 12:00:54.657 520-520/? A/DEBUG: pid: 10223, tid: 10223, name: pkarir.topkarir  >>> com.topkarir.topkarir <<<
07-23 12:00:54.657 520-520/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
07-23 12:00:54.664 520-520/? A/DEBUG:     x0   0000007fed6aefd8  x1   0000007f78d3e53f  x2   0000000000000006  x3   0000000000007472
07-23 12:00:54.664 520-520/? A/DEBUG:     x4   0000000000000000  x5   0000000000000001  x6   00000055b4e6cdb8  x7   0000007f78d3e539
07-23 12:00:54.664 520-520/? A/DEBUG:     x8   0000000000000021  x9   00000055b4e6cda0  x10  0000000055055010  x11  0000000000000033
07-23 12:00:54.664 520-520/? A/DEBUG:     x12  0000007f94d5ba70  x13  00000055b4e6cdc0  x14  00000055b4ab7000  x15  0000000000168800
07-23 12:00:54.664 520-520/? A/DEBUG:     x16  0000007f794b9a78  x17  0000007f94cc5c08  x18  1000000000000000  x19  0000007fed6af178
07-23 12:00:54.664 520-520/? A/DEBUG:     x20  0000007fed6af180  x21  0000007fed6af190  x22  0000000000000000  x23  0000007fed6aefd8
07-23 12:00:54.664 520-520/? A/DEBUG:     x24  0000007f794ca0d0  x25  0000000000000008  x26  0000000012d9e080  x27  0000000071584b40
07-23 12:00:54.665 520-520/? A/DEBUG:     x28  00000000724b5dd4  x29  0000000012e1f0e0  x30  0000007f78f33320
07-23 12:00:54.665 520-520/? A/DEBUG:     sp   0000007fed6aefd0  pc   0000007f78f33320  pstate 0000000080000000
07-23 12:00:54.665 520-520/? A/DEBUG: backtrace:
07-23 12:00:54.665 520-520/? A/DEBUG:     #00 pc 000000000004d320  /data/app/com.topkarir.topkarir-1/split_config.arm64_v8a.apk (offset 0x13a9000)
07-23 12:00:54.832 520-520/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_05
07-23 12:00:54.832 520-520/? E/DEBUG: AM write failed: Broken pipe
07-23 12:00:54.836 1287-10280/? E/ActivityManager: Invalid thumbnail dimensions: 0x0
07-23 12:00:54.877 419-419/? E/lowmemorykiller: Error writing /proc/10223/oom_score_adj; errno=22
07-23 12:00:54.996 4272-4275/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [4, 0]

**Comment by bayuramadeza** [comment]
hey @tvolkert i have tried a beta channel, so i have new output after downloading the app from playstore and the app was crashed.

> 07-23 12:00:54.408 4272-4275/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
07-23 12:00:54.416 4272-4275/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [4, 0]
07-23 12:00:54.613 377-386/? E/cutils: Failed to openat(/storage/0403-0201): Permission denied
07-23 12:00:54.617 377-386/? E/cutils: Failed to openat(/storage/0403-0201): Permission denied
07-23 12:00:54.655 10223-10223/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 10223 (pkarir.topkarir)
07-23 12:00:54.657 520-520/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-23 12:00:54.657 520-520/? A/DEBUG: Build fingerprint: 'Xiaomi/helium/helium:6.0.1/MMB29M/V7.3.14.0.MBDCNDE:user/release-keys'
07-23 12:00:54.657 520-520/? A/DEBUG: Revision: '0'
07-23 12:00:54.657 520-520/? A/DEBUG: ABI: 'arm64'
07-23 12:00:54.657 520-520/? A/DEBUG: pid: 10223, tid: 10223, name: pkarir.topkarir  >>> com.topkarir.topkarir <<<
07-23 12:00:54.657 520-520/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
07-23 12:00:54.664 520-520/? A/DEBUG:     x0   0000007fed6aefd8  x1   0000007f78d3e53f  x2   0000000000000006  x3   0000000000007472
07-23 12:00:54.664 520-520/? A/DEBUG:     x4   0000000000000000  x5   0000000000000001  x6   00000055b4e6cdb8  x7   0000007f78d3e539
07-23 12:00:54.664 520-520/? A/DEBUG:     x8   0000000000000021  x9   00000055b4e6cda0  x10  0000000055055010  x11  0000000000000033
07-23 12:00:54.664 520-520/? A/DEBUG:     x12  0000007f94d5ba70  x13  00000055b4e6cdc0  x14  00000055b4ab7000  x15  0000000000168800
07-23 12:00:54.664 520-520/? A/DEBUG:     x16  0000007f794b9a78  x17  0000007f94cc5c08  x18  1000000000000000  x19  0000007fed6af178
07-23 12:00:54.664 520-520/? A/DEBUG:     x20  0000007fed6af180  x21  0000007fed6af190  x22  0000000000000000  x23  0000007fed6aefd8
07-23 12:00:54.664 520-520/? A/DEBUG:     x24  0000007f794ca0d0  x25  0000000000000008  x26  0000000012d9e080  x27  0000000071584b40
07-23 12:00:54.665 520-520/? A/DEBUG:     x28  00000000724b5dd4  x29  0000000012e1f0e0  x30  0000007f78f33320
07-23 12:00:54.665 520-520/? A/DEBUG:     sp   0000007fed6aefd0  pc   0000007f78f33320  pstate 0000000080000000
07-23 12:00:54.665 520-520/? A/DEBUG: backtrace:
07-23 12:00:54.665 520-520/? A/DEBUG:     #00 pc 000000000004d320  /data/app/com.top.top-1/split_config.arm64_v8a.apk (offset 0x13a9000)
07-23 12:00:54.832 520-520/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_05
07-23 12:00:54.832 520-520/? E/DEBUG: AM write failed: Broken pipe
07-23 12:00:54.836 1287-10280/? E/ActivityManager: Invalid thumbnail dimensions: 0x0
07-23 12:00:54.877 419-419/? E/lowmemorykiller: Error writing /proc/10223/oom_score_adj; errno=22
07-23 12:00:54.996 4272-4275/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [4, 0]

**Comment by matthewlloyd** [comment]
Hopefully the last update from me on this issue - since ARM translation appeared to work in Genymotion, I updated all my apps to use appbundles. It's been a week and I've had zero reports of crashes from users (last time I tried they had started within a few hours) so I believe my issue must have been resolved sometime in the last two months. Thanks again to the team for the fantastic framework and support!

**Comment by Hixie** [comment]
@matthewlloyd Sounds like you're ok with us closing this bug?

**Comment by matthewlloyd** [comment]
@Hixie It's fine with me, though I haven't tested anything on Chromebooks. The Google Play Dev Console tells me Chromebook users _can_ install my app from the store, but I don't appear to have any actual installs, so it doesn't matter to me whether appbundles work correctly on them. @wreppun, who reported the issue on Chromebooks, may care, though.

**Comment by Hixie** [comment]
@matthewlloyd thanks.

@tvolkert told me that he wants to investigate this some more before closing it.

**Comment by cbracken** [comment]
@tvolkert any updates on this?

**Comment by tvolkert** [comment]
I just verified this is working.  It's slow as molasses due to the emulation, but that's covered by https://github.com/flutter/flutter/issues/9253.

Closing.

**Comment by Jon-Salmon** [comment]
I have recently upgraded from flutter version 1.0 to v1.7.8+hotfix.4 and am having reports that the app always crashes in open for chromebook users. Has this been resolved and if so what do I need to do to fix it?
