### ISSUE TITLE
flutter update-packages --force-upgrade fails to un-pin flutter sdk deps

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#36511]
## Steps to reproduce

1. Create the following `pubspec.yaml` file in a clean directory (henceforth referred to a `$DIR`):

    ```yaml
    name: bug_report
    dependencies:
      flutter:
        sdk: flutter
      meta: any
    ```

2. Update your `$FLUTTER_ROOT/packages/flutter/pubspec.yaml` file to specify a pinned version of `meta: 1.1.6` (which is what it's [currently pinned to](https://github.com/flutter/flutter/blob/82a4ba40bb59cebde169c58253599a91495b376d/packages/flutter/pubspec.yaml#L13))

3. Run the following commands:

    ```sh
    $ cd $DIR
    $ FLUTTER_ROOT=/path/to/flutter_root \
        PUB_ENVIRONMENT=flutter_cli \
        pub upgrade
    ```

## Observed results

Because your pubspec.yaml depends on the Flutter SDK, it's pinned to the same version of `meta` that Flutter is pinned to.  This is working as intended.

However, the previous steps are _exactly_ what `flutter update-packages --force-upgrade` does, with the exception of putting the Flutter SDK dependency in its synthetic `pubspec.yaml` file.  Unfortunately, some of Flutter's transitive deps require the Flutter SDK and thus are triggering this behavior.  The net result is that any non-dev dependency listed in the Flutter framework's pubspec is pinned and never upgraded.

**Comment by mit-mit** [comment]
Thanks for getting to the bottom of this! This seems serious as it will leave developers stranded on stale deps. I'm going to tag this 'customer: product' to signal my believed importance.

**Comment by tvolkert** [comment]
@mit-mit tagging it as "customer: critical" will get it seen in the weekly triage (https://github.com/flutter/flutter/wiki/Issue-hygiene).  Would you say this is critical?

**Comment by jonahwilliams** [comment]
flutter update-packages is for development on flutter itself, and force-upgrade is only for creating PRs to flutter, it should never be run by a developer using flutter.

**Comment by tvolkert** [comment]
@jonahwilliams, the issue is that it doesn't upgrade our dependencies properly.
