### ISSUE TITLE
How do you write Android code in Java or iOS code in objective-c for a project you've created

### ISSUE THREAD

**Issue by GanZhiXiong** [flutter/flutter#36522]
![image](https://user-images.githubusercontent.com/27394631/61516781-4724df00-aa38-11e9-883d-abb536f6cc72.png)

I have a project that was created by checking two boxes in the red box above. Now I'm going to call the native code.

How to write Android code in Java, or iOS code in objective-c.
I don't want to recreate Java and objective-c enabled projects, which is a bit of a slow process.

**Comment by jonahwilliams** [comment]
You would need to use whatever mechanism exists for interop in the selected language. You could also regenerate the project to use Java and Objective C.

**Comment by escamoteur** [comment]
@jonahwilliams in other words it's not possible in any easy way.
I will close the issue then.

**Comment by jonahwilliams** [comment]
>  in other words it's not possible in any easy way.

I guess that is a matter of opinion? I would say its fairly straightforward. At any rate, it has little to do with Flutter itself, so I agree this issue should be closed.
