### ISSUE TITLE
Memory leak in plugins?

### ISSUE THREAD

**Issue by BugsBunnyBR** [flutter/flutter#36520]
So, I may be wrong, but in the plugins below it looks like that registration in the `ActivityLifecycleCallbacks` and in the `LocalBroadcastManager` may become memory leaks in case the Flutter Activity is open multiple times.
For instance, when flutter is being used in add-to-app to show a product detail. Every time that Activity is open the plugin registration process is triggered and a new listener is attached, but it is never released.

https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java#L58

https://github.com/flutter/plugins/blob/master/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java#L95

https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapsPlugin.java#L36

I have some ideas of how to avoid those calls, but I would like to confirm this before trying to change the code.

**Comment by amirh** [comment]
Thanks! I believe you are correct.

For the activity lifecycle listeners we should probably remove the listener when the activity is destroyed.

@collinjackson should have more context on the broadcast manager registration in the firebase messaging plugin (sounds reasonable that we should ensure to not double register, do we also want to unregister at some point?)

**Comment by BugsBunnyBR** [comment]
I think it is easy to remove the listener when the activity is destroyed, but I did not study these plugin in full yet and don't know possible side effects.

Removing the listeners should be enough for a fix, but I believe a better approach for firebase cloud message plugin is to use background execution for the token and the `onMessage` events, but I am kinda lost about how to register the plugin to call the dart code from `FlutterFirebaseMessagingService`.
Is there any documentation of the lifecycle of a plugin? When it can created? (whenever the plugin developer wants?) When should it release resources?

**Comment by collinjackson** [comment]
FYI @matthew-carroll 

Also I believe @kroikie has been working on getting the Firebase messaging plugin to handle scenarios where the activity has been destroyed. (#17482)

**Comment by matthew-carroll** [comment]
FYI - These problems should disappear on their own if the plugins are migrated to the new Android embedding.

**Comment by BugsBunnyBR** [comment]
@matthew-carroll , so... should we wait the new android embedding be ready to tackle this issue?

**Comment by matthew-carroll** [comment]
Somebody is welcome to solve it now for the old embedding, assuming there is a way to do it that doesn't risk all plugins. But what we know for sure is that when plugins are upgraded to the new embedding, this problem should no longer exist.

**Comment by BugsBunnyBR** [comment]
I think I have found another leaking plugin...
if `onListen` is called [here](https://github.com/flutter/plugins/blob/master/packages/battery/android/src/main/java/io/flutter/plugins/battery/BatteryPlugin.java#L65)
`onCancel` is not called when the Activity is destroyed (even though the subscription is being [canceled](https://github.com/flutter/plugins/blob/master/packages/battery/example/lib/main.dart#L89) in the the widget dispose). So, if the app does more than show the FlutterActivity before killing the app it seems to cause another memory leak.

I can do another pr removing the receiver in the `onActivityDestroyed` lifecycle event, but it seems to me that the framework could cancel all `StreamHandler` that are associated with the foreground subscription. Maybe @matthew-carroll is already aware of it for the new embedding, just wanted to raise the issue for the current implementation in case it is something new.

**Comment by audkar** [comment]
Reported in this [issue](https://github.com/flutter/flutter/issues/32818). I assume nothing is being done about that since no response on that issues. Even though almost every plugin which use streams leaks activities.

And gazillion issue are created with OOM report with zero responses...

**Comment by BugsBunnyBR** [comment]
I am closing this issue as only firebase message plugin is left with the identified problem. I will open other issue at https://github.com/FirebaseExtended/flutterfire

**Comment by kroikie** [comment]
@BugsBunnyBR

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1055. Any further collaboration will be done there.
