### ISSUE TITLE
Does Text support includeFontPadding=false like Android TextView?

### ISSUE THREAD

**Issue by jerboy** [flutter/flutter#36523]
Size of Text in Flutter is more higher than the real font size.

I need some property to set like ```includeFontPadding=false ``` in Android TextView.

![1563521207414](https://user-images.githubusercontent.com/4384973/61517381-afc08b80-aa39-11e9-9a66-cd58145c2d6b.jpg)

**Comment by jerboy** [comment]
@sethladd @ianloic @anaisbetts @sgraham

**Comment by GaryQian** [comment]
To achieve this, set `TextStyle(height: 1)`

Explanation:

Each font specifies its own ascent and descent, which can vary depending on the platform. The font also specifies an EM-square, whose height adds up to exactly the font-size. By default, Flutter uses the ascent and descent values, which often adds up to a total height that is greater than the fontSize/EM-square. In a recent PR, we changed the way the height property works. `height` is now an override for the default ascent and descent. When `height` is null or omitted, the default will be used. When `height` is specified, the total height will be exactly the height of the EM-square and the fontSize times the `height`. This means setting `height: 1` is an override to force Flutter to use the exact fontSize as the height. In effect, this is removing what you see as "padding"

Let me know if you have any additional questions!

**Comment by jerboy** [comment]
@GaryQian Thank you very much!

**Comment by moonljt521** [comment]
TextStyle(height: 1) .  is not working
