### ISSUE TITLE
camera take photo return picture with error size

### ISSUE THREAD

**Issue by haianhsing** [flutter/flutter#36525]
Hello:
I use the camera plugin and change the preview size and capture size to 1440 * 1080 , but it just return a photo with size 1456 * 1456 ,what 's the problem?  Any help is grantful.

device : honor 20 , android 9.0

**Comment by BondarenkoStas** [comment]
@haianhsing Please provide your flutter doctor -v output, version of camera you use, and some sample code to reproduce the issue.

**Comment by haianhsing** [comment]
@BondarenkoStas I solved this problem by setting the automatic acquisition size.
