### ISSUE TITLE
"Google maps markers with custom icons look big on iOS #24865" this issue is back again after we got update on flutter

### ISSUE THREAD

**Issue by harshaIOT** [flutter/flutter#36534]
Custom Icon in Google maps flutter package is working fine in Android whereas it is a big icon in IOS please help us to fix this issue cause we have tried all the ways as you suggested before

**Comment by KyllianDM** [comment]
It doesn't work on Android, the markers doens't appear since I upgraded Flutter.

**Comment by hectorAguero** [comment]
Did you tried the code from the line 235 in the maps example...I'm use that and works. https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/example/lib/place_marker.dart

Also I put an answer here https://stackoverflow.com/questions/52591556/custom-markers-with-flutter-google-maps-plugin/57170321#57170321

**Comment by BondarenkoStas** [comment]
@harshaIOT Is the issue still relevant? Can you confirm it using current flutter stable and current plugin?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
