### ISSUE TITLE
Textfield inside ExpansionTile throwing this error : "'bool' is not a subtype of type 'double'"

### ISSUE THREAD

**Issue by AkhileshGahlot** [flutter/flutter#36539]
Every time after collapsing the ExpansionTile when I reopen the tile this single line error come:
" **Another exception was thrown: type 'bool' is not a subtype of type 'double'.**"

I even try the debug mode of android studio but unable to find the source of exception.

Any help would be grateful. 

Here is my code -

    function(){
    double size = MediaQuery.of(context).size.width;

    return ListView(
      padding: const EdgeInsets.fromLTRB(10.0, 10, 10, 10),
      children: <Widget>[
        Wrap(
          direction: Axis.horizontal,
          crossAxisAlignment: WrapCrossAlignment.start,
          alignment: WrapAlignment.spaceBetween,
          children: <Widget>[

            SizedBox(
              width: size / 1.4,
              child: Text(
                "KYC Details",
                style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
                maxLines: 2,
                overflow: TextOverflow.ellipsis,
              ),
            ),

            SizedBox(
              width: 50,
              child: FlatButton(
                child: Icon(
                  Icons.arrow_back,
                  color: TabIndicatorColor,
                ),
                padding: EdgeInsets.fromLTRB(10, 0, 0, 10),
                onPressed: () {
                  setState(() {
                    editmode = false;
                  });
                },
              ),
            ),
          ],
        ),

        SizedBox(
          width: size / 1.18,
          child: new MyExpansionTile(
            key: PageStorageKey('1'),
            initiallyExpanded: true,
            title: Text(
              'Personal Detail',
              style: TextStyle(fontSize: 20),
            ),
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.only(top: 20.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisAlignment: MainAxisAlignment.start,

                  children: <Widget>[

                    Padding(
                      padding: const EdgeInsets.only(bottom: 10.0),
                      child: MyTextField(data: "Natthu Lal Kumar"),
                    ),
                 ],
                ),
              ),
            ],
          ),
        ),
    }

//This class is used for textfield 

      class MyTextField extends StatefulWidget {
      String data;
  
      MyTextField({this.data = ''});
  
      @override
      State<StatefulWidget> createState() {
        // TODO: implement createState
        return MyTextFieldState();
      }
    }
  
    class MyTextFieldState extends State<MyTextField> {
      TextEditingController textEditingController = TextEditingController();
  
      _onSubmitted(String value) {
        setState(() => textEditingController.text = value);
      }
  
      @override
      void initState() {
        // TODO: implemeninitState
  
        textEditingController.text = widget.data;
  
        super.initState();
      }
  
      @override
      void dispose() {
        // TODO: implement dispose
  
        textEditingController.dispose();
        super.dispose();
      }
  
      @override
      Widget build(BuildContext context) {
        // TODO: implement build
        return TextField(
          key: UniqueKey(),
          controller: textEditingController,
          style: TextStyle(
            fontSize: 15,
            color: PrimaryTextColor,
          ),
          onSubmitted: _onSubmitted,
          decoration: InputDecoration(
            enabledBorder: OutlineInputBorder(
              borderSide: BorderSide(
                color: TransparentColor,
    //                                width: 0
              ),
            ),
            contentPadding: EdgeInsets.all(10),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.all(Radius.circular(4)),
            ),
            filled: true,
            hintStyle: TextStyle(
              color: BtnBgColor,
            ),
          ),
        );
      }
    }

**Comment by AkhileshGahlot** [comment]
Solution of above problem is to give an PageStorageKey('mytextfield'), to your textfield that's all.

**Comment by JoseGeorges8** [comment]
Could you elaborate on this? I'm getting the same error but with scrollables inside the expansionTile. e.g a listView, a SingleChildScrollView.

**Comment by JoseGeorges8** [comment]
Okay it actually worked for me and this is what I ended up doing...


```
        Container(
          height: 200,
          child: ListView(
            scrollDirection: Axis.horizontal,
            key: PageStorageKey('myScrollable'),
            children: images,
          ),
        )
```

and that is inside the expansion tile... but why is this necessary?

**Comment by jdavies** [comment]
Thanks for this. I just came across the problem today. Good, simple solution!
