### ISSUE TITLE
CocoaPods minimum required version 1.6.0 

### ISSUE THREAD

**Issue by Georgeskh** [flutter/flutter#36544]
Warning: CocoaPods minimum required version 1.6.0 or greater not installed. Skipping pod install.
But I have a higher version of CocoaPods installed.
![Screen Shot 2019-07-19 at 5 42 18 PM](https://user-images.githubusercontent.com/49345041/61543672-9d038200-aa4c-11e9-99ed-01e56c14be90.png)

**Comment by christopherfujino** [comment]
Are you by any chance using RVM? I've had this happen where the version of ruby in my environment was different from the one used by cocoapods.

**Comment by Georgeskh** [comment]
No, I'm facing this problem when i add some widget plugin in my dependencies.

**Comment by christopherfujino** [comment]
Could you copy and paste full text of `flutter doctor -v`? Also, a minimum reproduceable code example would help (including your pubspec.yaml).

**Comment by Georgeskh** [comment]
Flutter doctor output:
[✓] Flutter (Channel stable, v1.7.8, on Mac OS X 10.14.5 18F132, locale en-LB)
    • Flutter version 1.7.8 at /Users/alfredkallas/Developer/flutter
    • Framework revision d51fd86cdb (4 weeks ago), 2019-06-21 22:31:55 -0400
    • Engine revision d004bcd4d6
    • Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alfredkallas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/alfredkallas/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by Georgeskh** [comment]
In pubspec.yaml I just added the 
  flutter_blue: ^0.6.0+1 in my dependencies and run the default project

**Comment by 32h8** [comment]
try https://github.com/flutter/flutter/issues/14630#issuecomment-367447443

**Comment by Georgeskh** [comment]
Error output from CocoaPods:
↳

    [!] `<PBXGroup UUID=`97C146E51CF9000F007C117D`>` attempted to initialize an object with an unknown UUID. `CF3B75C9A7D2FA2A4C99F110` for attribute: `children`. This can be the result of a merge and  the unknown UUID is being discarded.

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone Xʀ.



If you can help with this matter. And thank you for your help so far

**Comment by christopherfujino** [comment]
@Georgeskh can you try re-installing cocoapods? As the comment 32h8 linked to suggests, this can sometimes happen if there are ruby version conflicts.

**Comment by Georgeskh** [comment]
The problem was with the pod file location i just dragged it out of the ios file into the main project repository. It worked

**Comment by softwareboy92** [comment]
How to solve this problem?

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    ! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the
        Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
[✓] VS Code (version 1.53.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
