### ISSUE TITLE
firebase_admob, Feature to hide banner ad

### ISSUE THREAD

**Issue by pdmshrestha** [flutter/flutter#36541]
Hi, 

According to adMob policy, ads cannot be displayed in empty screen. I have an app where user can download items from internet, If the user hasn't downloaded anything the downloads page is empty. I want to hide the bottom ad banner on this case.

**Comment by dvaldivia** [comment]
Use a conditional with `Opacity` or `Visibility`

```
Visibility(
  child: Text("Gone"),
  visible: false,
),
```

```
new Opacity(opacity: 0.0, child: new Padding(
              padding: const EdgeInsets.only(
                left: 16.0,
              ),
              child: new Icon(pencil, color: CupertinoColors.activeBlue),
            ))
```

**Comment by BondarenkoStas** [comment]
@pdmshrestha does the comment above answered your question? Anyway, it doesn't seem to be anything wrong with the framework, but related to implementation. Closing as it's more like StackOverflow question than flutter issue.

**Comment by kroikie** [comment]
@pdmshrestha

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1171. Any further collaboration will be done there.

**Comment by daniele777** [comment]
i have same issue ...how to hide ???Using firebase_admob 0.9.1 for show banner i use..
```
 myBanner
      ..load()
        ..show(
          anchorOffset: 60.0,
       
        );

```
And to hide???

**Comment by everoo** [comment]
@daniele777 just call the show() function but set the anchorOffset to -60 or however big it is. This re shows it and puts it off screen.

**Comment by pdmshrestha** [comment]
@everoo  thanks it helped.

**Comment by MathiasSolling** [comment]
`if (_bannerAd != null) {
      await _bannerAd.isLoaded();
      await _bannerAd.dispose();
      _bannerAd = null;
}`
