### ISSUE TITLE
webview_flutter scrolling not following finger

### ISSUE THREAD

**Issue by grandleaf** [flutter/flutter#36550]
Source code (the WiKi Octopus Demo):
"https://github.com/efortuna/wiki_browser?source=post_page---------------------------"

Steps: (Important)
1. After page is loaded, LONG PRESS the page for a couple of seconds;
2. Then try to scroll vertically you will find the page will not follow your finger.  Sounds like some gesture detector blocked the pan event.

Flutter Info:
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at C:\Utilities\flutter
    • Framework revision b712a172f9 (10 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\grandleaf\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • SM G975U1 • R58M248N4DZ • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by grandleaf** [comment]
Well, it seems set the webView's gestureRecognizer to: <Factory<OneSequenceGestureRecognizer>>[
          Factory<OneSequenceGestureRecognizer>(() => EagerGestureRecognizer()),
        ].toSet(),

can fix this.

However, I suggest this to be the default value if null input is detected.

**Comment by bojie-liu** [comment]
Thought it may be introduced by a bandage fix for issues in plugins repo at webview_android.dart. 
https://github.com/flutter/plugins/blob/3b71d6e9a4456505f0b079074fcbc9ba9f8e0e15/packages/webview_flutter/lib/src/webview_android.dart#L38

Related issues:
WebView's text selection handles are not showing on Android #24584
WebView's text selection dialog is not responding to touch events #24585

Thanks for posting the WiKi Demo which helps a lot in debugging these issues.

**Comment by qqw78901** [comment]
I have the same problem and wait to resolve

**Comment by qqw78901** [comment]
> I have the same problem and wait to resolve

and as @grandleaf said that set `gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
                Factory(() => EagerGestureRecognizer()),
       ].toSet()` can fix it.

**Comment by darshankawar** [comment]
@grandleaf @qqw78901 I tested this issue on latest` dev channel (1.20.0-0.0.pre)` and with latest version of `webview_flutter`, but I was unable to replicate it. 

[36550.mp4.zip](https://github.com/flutter/flutter/files/4803794/36550.mp4.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.20.0-0.0.pre at /Users/deeptibelsare/Documents/Fluttersdk/flutter
    • Framework revision d9653445f4 (8 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

</details>

Can you please try on latest flutter webview version to see if you still experience the issue ?
