### ISSUE TITLE
Cursor passes through the emoji and app crashes.

### ISSUE THREAD

**Issue by 2208Abhinav** [flutter/flutter#36557]
On android sometimes when I tap on an emoji in TextField the cursor passes through the emoji.

![WhatsApp Image 2019-07-19 at 11 31 21 PM](https://user-images.githubusercontent.com/30211121/61555950-30a17680-aa7e-11e9-9d48-47cdee6b4fad.jpeg)

On adding new emoji the following happens...
![WhatsApp Image 2019-07-19 at 11 36 31 PM](https://user-images.githubusercontent.com/30211121/61556005-5890da00-aa7e-11e9-8782-bc3e4e854e86.jpeg)

When I remove this new emoji I again get back the original emoji with the cursor still passing through the center.

Also when I am trying to get the text of TextField the following exception is shown
```
Invalid argument(s): string is not well-formed UTF-16
```
and TextField vanishes.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-IN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✗] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by 2208Abhinav** [comment]
On iOS also cursor passes through the emoji but when I add emoji or remove it(while the cursor is passing through the emoji) it works fine but when I try to get the text the I get the following exception
```
Invalid argument(s): string is not well-formed UTF-16
```

And app crashes with the following log:
```
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010748f1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001065b1735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010748ef42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000105fb4877 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   Flutter                             0x0000000104180586 -[FlutterJSONMessageCodec decode:] + 473
	5   Flutter                             0x0000000104180887 -[FlutterJSONMethodCodec decodeMethodCall:] + 67
	6   Flutter                             0x000000010417f7d5 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 48
	7   Flutter                             0x000000010411f476 _ZNK7flutter21PlatformMessageRout<…>
```

**Comment by 2208Abhinav** [comment]
Also, this type of behavior is seen when maxLines is set to null. The cursor passes through all the emoji except the ones on the first line.

**Comment by 2208Abhinav** [comment]
Here's the code of TextField

```
TextField(
  textInputAction: TextInputAction.sen
  keyboardType: TextInputType.multiline,
  cursorWidth: 1,
  autocorrect: false,
  cursorColor: Colors.black,
  controller: _commentTextController,
  maxLines: null,
  autofocus: true,
  decoration: InputDecoration(
    hintText: "Your comment...",
    enabledBorder: InputBorder.none,
    focusedBorder: InputBorder.none,
  ),
  style: TextStyle(fontSize: 30),
)
```

**Comment by 2208Abhinav** [comment]
Below is the gif showing buggy nature of emojis.

![ezgif com-crop](https://user-images.githubusercontent.com/30211121/61574914-688ed500-aae3-11e9-97bd-740dd85b19da.gif)

**Comment by 2208Abhinav** [comment]
This behavior can also be seen in flutter gallery app with multiline text fields.

**Comment by 2208Abhinav** [comment]
**Edit: CupertinoTextField doesn't have this bug so I guess I will try that until this is fixed**

**Comment by GaryQian** [comment]
Those family emojis are multiple single emojis connected by a "zero width joiner" character indicating that they should be rendered as one. I fixed the bug for the first line, but it seems that the second line is not seeing the impacts of the fix. See the initial fix: https://github.com/flutter/flutter/pull/24797

**Comment by GaryQian** [comment]
The ability to index between a single emoji is visually caused by our ligature handling. I am coming up with a fix to handle this properly.

In addition, the getPositionForOffset call in paragraph should take clusters into account to prevent providing mid-cluster positions, thus preventing the insertion of additional characters within a cluster.
