### ISSUE TITLE
Request to know hot reload events per device target

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#36566]
Current motivating question: "How many hot reload events (successful, not successful) are occurring per target platform (windows, mac, linux, android, ios, fuchsia)?"

Behind that question is: "What is the hot reload adoption per target platform?"

If it's easy to add, we can also track this data for Hot Restart.

Thank you very much!

**Comment by sethladd** [comment]
cc @zanderso

**Comment by zanderso** [comment]
This is in.
