### ISSUE TITLE
White Screen - App content failed to load after launch released iOS app

### ISSUE THREAD

**Issue by ishakdas** [flutter/flutter#36578]
Hello to everyone.
I installed my application play store seamlessly. However, when I tried to install the App Store, the application was rejected and I received the following message.
Guideline 2.1 - Performance - App Completeness

We discovered one or more bugs in your app when reviewed on iPad running iOS 12.3.1 on Wi-Fi.

When we launched the app, app displayed a splash screen and no further action occurred in the app during the review. 

Next Steps

To resolve this issue, please run your app on a device to identify any issues, then revise and resubmit your app for review.

If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.

For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce the issue. For updates, install the new version as an update to the previous version, then follow the steps to reproduce the issue.

Resources

For information about testing your app and preparing it for review, please see Technical Note TN2431: App Testing Guide. 

For a networking overview, please review About Networking.

Please see attached screenshots for details.

When I write flutter doctor there is no problem.
I tried the application on the real device again no problem.
But the app store made such a turn. Does anyone know the reason or are having the same problem?

**Comment by ishakdas** [comment]
Resolved
https://www.flutterforum.org/d/97-white-screen-app-content-failed-to-load-after-launch-released-ios-app

**Comment by BondarenkoStas** [comment]
@ishakdas I think it's safe to close the issue as it's already fixed on master. If you disagree or encounter it again, please comment and I will re-open it right away.
