### ISSUE TITLE
App crash after flutter upgrade

### ISSUE THREAD

**Issue by cooler-king** [flutter/flutter#3658]
An app that was working before running flutter upgrade on 30 Apr is now crashing.

The app starts, but then most attempts to change pages result in the page loading and being visible for just a moment before the app crashes.

The only feedback is:
F/libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10 in tid 12501 (gpu_thread)

No log file is generated.

**Comment by abarth** [comment]
That's concerning.  Given the format of the log statement, I presume you're using Android.  Which device are you using?  Also, does `adb logcat` give any additional information?

**Comment by abarth** [comment]
Another possible approach to debugging this issue is to use `git bisect` to learn at which Flutter revision the problem started.

**Comment by cooler-king** [comment]
LG G2.
I'll see if I can get anything from adb logcat.

**Comment by cooler-king** [comment]
`F/libc    ( 5222): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x700 in tid 5266 (gpu_thread)
I/WindowState(  955): WIN DEATH: Window{359e86a7 u0 com.example.vinteresting_flutter/org.domokit.sky.shell.SkyActivity}
W/WindowManager(  955): Force-removing child win Window{328fc6fd u0 SurfaceView} from container Window{359e86a7 u0 com.example.vinteresting_flutter/org.do
mokit.sky.shell.SkyActivity}
W/WindowManager(  955): Failed looking up window
W/WindowManager(  955): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@2db06754 does not exist
W/WindowManager(  955): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8815)
W/WindowManager(  955): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8806)
W/WindowManager(  955): 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1135)
W/WindowManager(  955): 	at android.os.BinderProxy.sendDeathNotice(Binder.java:553)
I/WindowState(  955): WIN DEATH: null
I/ActivityManager(  955): Process com.example.vinteresting_flutter (pid 5222) has died
W/ActivityManager(  955): Force removing ActivityRecord{c4fc1b7 u0 com.example.vinteresting_flutter/org.domokit.sky.shell.SkyActivity t705}: app died, no 
saved state
`

**Comment by cooler-king** [comment]
The crashes begin with flutter commit 
Upgrade engine.version (#3614)
2c70b3e4ddc6c615ba2edbcc701dba5449fd0cc8

**Comment by abarth** [comment]
Thanks for bisecting.  I'm guessing the root cause is https://github.com/flutter/engine/commit/5bc5c7b5246d62af70780ec7ba0203ac3f318226 .  I'll revert that and we can see if that resolves the issue.

**Comment by abarth** [comment]
Do you want to try flutter.git at 5a3327bb7b5f4c9d74802af72726d45ff8e7dcb5 ?  That has the patch I think might be going wrong reverted.

**Comment by cooler-king** [comment]
The app works normally on https://github.com/flutter/flutter/commit/5a3327bb7b5f4c9d74802af72726d45ff8e7dcb5

\o/

**Comment by abarth** [comment]
yay
