### ISSUE TITLE
Failed assertion: line 887 pos 15: 'animation != flutter: null': is not true.

### ISSUE THREAD

**Issue by jbrunoAtMeli** [flutter/flutter#36588]
## Steps to Reproduce

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Main(),
    );
  }
}

class Main extends StatefulWidget {
  @override
  _MainState createState() => _MainState();
}

class _MainState extends State<Main> with SingleTickerProviderStateMixin {
  Animation animation;
  AnimationController animationController;
  void init() {
    
    animationController =
        AnimationController(vsync: this, duration: Duration(seconds: 3));
    animation = Tween(
      begin: 0.0,
      end: 1.0,
    ).animate(
        CurvedAnimation(curve: Curves.bounceIn, parent: animationController.view));
    animationController.forward();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    double height = MediaQuery.of(context).size.height;
    double width = MediaQuery.of(context).size.width;
    return AnimatedBuilder(
      animation: animation,
      builder: (builder, child) {
        //print(animation.value);
        return Scaffold(
          body: Center(
            child: Card(
              child: Container(
                width: width * animation.value,
                height: height * animation.value,
                color: Colors.teal,
                child: Icon(
                  Icons.face,
                  size: 100.0 * animation.value,
                ),
              ),
            ),
          ),
        );
      },
    );
  }
}

```
1. ...
2. ...
3. ...

## Logs

 flutter analyze
Analyzing animation...                                                  
No issues found! (ran in 1.9s)
```
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-AR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

**Comment by LongCatIsLooong** [comment]
`void init()` => `void initState()`. Feel free to reopen if that doesn't fix your issue.

**Comment by jbrunoAtMeli** [comment]
@LongCatIsLooong  thanks for the hint !!

  void initState() {
    super.initState();


replace with 
....
class _MainState extends State<Main> with SingleTickerProviderStateMixin {
  Animation animation;
  AnimationController animationController;
  @override
  void initState() {
    super.initState();
    animationController =
        AnimationController(vsync: this, duration: Duration(seconds: 3));
    animation = Tween(
      begin: 0.0,
      end: 1.0,
    ).animate(
        CurvedAnimation(curve: Curves.bounceIn, parent: animationController.view));
    animationController.forward();
   
  }


and works!!

**Comment by ridwanray** [comment]
I/flutter ( 3980): 'package:flutter/src/widgets/transitions.dart': Failed assertion: line 929 pos 15: 'animation !=
I/flutter ( 3980): null': is not true.

How can I fix this?
@jbrunoAtMeli  i ALREADY PUT
@override
void initState() {
super.initState();

but it does not work....

**Comment by amar132** [comment]
@ridwanray : Though I assume you must have solved the problem. But for others. All you have to do is goto Transition.dart file and remove the assert once, reload the app and undo the change. When you reload the app for the first time. Somehow this resets the transition.dart file and the values and the app starts working.
