### ISSUE TITLE
Truecaller SDK for flutter

### ISSUE THREAD

**Issue by abhi12299** [flutter/flutter#36592]
I was looking around for some solution around mobile number verification and I found out Truecaller SDK for android and iOS. https://truecaller4developers.gitbook.io/truecallersdk/getting-started

I searched around for integration with flutter but couldn't find any. Would be great to have a plugin for the same.

**Comment by kamalkant56** [comment]
facing similar issue.

**Comment by RohithKilaparthi** [comment]
Looking for the same.

**Comment by debmaj2** [comment]
@krino @Northenlight @opayen @rools @TheMedo @truecaller

**Comment by dipinarora9** [comment]
https://pub.dev/packages/flutter_truecaller

**Comment by debmaj2** [comment]
@dipinarora9  Thank you for your work.

**Comment by abhi12299** [comment]
@debmaj2 Thanks for conforming if it works. I'm closing the issue.
