### ISSUE TITLE
Support for Grpc in flutter_web

### ISSUE THREAD

**Issue by robinbakkerus** [flutter/flutter#36600]
Currently Flutter (mobile) support Grpc, with the pub package: "grpc 2.0.0+1" but unfortunately this does not work for Flutter_web. 
One could use the  package: "grpc/grpc-web", but that provides a javascript library. 
Ideally the Grpc package is enhanced in such a way that is support out-of-the-box both mobile and web context. Second best is another Grpc generator that generates Dart code, that can communicate with Grpc.

**Comment by jonahwilliams** [comment]
This is a more appropriate issue for https://github.com/grpc/grpc-dart
