### ISSUE TITLE
cannot execute binary file : line 183 flutter/bin/cache/dart-sdk/bin/dart

### ISSUE THREAD

**Issue by Sankara98** [flutter/flutter#36601]
I have followed the installation steps in the[MacOS Installation Guide](https://flutter.dev/docs/get-started/install/macos)

~$ tar xf ~/flutter_linux_v0.5.1-beta.tar.xz
~$ echo $PATH
/Users/sankaraekane/anaconda3/bin:/Users/sankaraekane/tools/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/rvm/bin
~$ flutter doctor
/Users/sankaraekane/tools/flutter/bin/flutter: line 183: /Users/sankaraekane/tools/flutter/bin/cache/dart-sdk/bin/dart: cannot execute binary file
~$ flutter doctor -v
/Users/sankaraekane/tools/flutter/bin/flutter: line 183: /Users/sankaraekane/tools/flutter/bin/cache/dart-sdk/bin/dart: cannot execute binary file

The OS is macOS Mojave 10.14.5

based on a previous similar issue, I have run:

~$ file /home/user/flutter/bin/cache/dart-sdk/bin/dart
/home/user/flutter/bin/cache/dart-sdk/bin/dart: cannot open `/home/user/flutter/bin/cache/dart-sdk/bin/dart' (No such file or directory)

~$ uname -m
x86_64

**Comment by ja2375** [comment]
You are downloading and installing a really really old flutter version. Please try to always download the lastest versions. And also, download the version for your OS. You are installing the linux one!

**Comment by Sankara98** [comment]
Thank you that was a mistake of my own, I had the same problem with the most recent stable version for macOS, resolved it by going to the previous version, and running flutter upgrade
