### ISSUE TITLE
AutoAnimatedIcon widget

### ISSUE THREAD

**Issue by Arjunraj-k** [flutter/flutter#36615]
I don't know if its wrong to post it here, if it is please close this immediately.

I've created a package to help you build the **AnimatedIcon** easily without even knowing the animation controller. And it has some nice features too. It is known as **AutoAnimatedIcon**(package name **_auto_animated_icon_**) you can find it here [AutoAnimatedIcon](https://pub.dev/packages/auto_animated_icon)

**Comment by HansMuller** [comment]
Thanks for the heads-up. Unfortunately this isn't really the place for advertising new Flutter components, so I'm going to close the issue.
