### ISSUE TITLE
iOS File size huge compared with Android

### ISSUE THREAD

**Issue by hasen6** [flutter/flutter#36611]
I've built two apps so far, both are small with zero images and barely any resources. Both are about 30mb on iOS after uploading as working builds while the android aab files are only around 8mb. The apps were originally created on React Native but only released on iOS and were even smaller than the current Flutter android builds.

There's no difference between the React Native and Flutter version so I don't understand the reason for the huge file differences. And it stands to reason that the Android and iOS builds shouldn't have such huge file differences either.

These are the sizes

App #1 (with Admob)
Flutter iOS
archive - 243.8MB
appstoreconnect build - **36.7MB**

Flutter Android
aab - 13.5MB
play store - **8.33MB**

React Native Original
appstoreconnect build - **4.98MB**

App #2 (without Admob)
Flutter iOS
archive - 33.9MB
appstoreconnect build - **29.5MB**

Flutter Android
aab - 12.2MB
play store - **6.98mb**

React Native Original
appstoreconnect build - **2.01MB**

I just followed the instructions to build and upload the iOS archives so can't see what the problem is that's creating the huge file size.  It's the `App.framework` that is taking up all the space in the iOS build archive.

I'm new to Flutter and am enjoying using it but this is making me think I should give up and go back to React Native or something. Hopefully someone can help.

**Comment by hasen6** [comment]
Hmm no replies at all...I guess this is totally normal then? React Native is just better then or what?

**Comment by hasen6** [comment]
Now glancer000 has downvoted me saying there were no replies... Were there in fact replies then? Not sure what's going on here but it's weird.

**Comment by anticafe** [comment]
@hasen6 You should share your build config (React Native & Flutter version, main build script file...) so that user be able to understand your case.

**Comment by hasen6** [comment]
Thanks for your reply, much more useful than idiots just sneaking in and downvoting. So in your experience it should build the same size for iOS and Android? The App.framework is small for you?

**Comment by Hixie** [comment]
This bug is about reducing the download size of Flutter applications on iOS.

**Comment by HansMuller** [comment]
On the face of it, there's much to be concerned about it here. Why is there an order of magnitude difference between download size for the iOS Flutter and React native versions of the app (app #2)?  Why does the iOS version of the app grow by 6M when AdMob is added, but closer to 1M for Android?

Maybe what's needed here are some tools that help developers understand how their app's download size relates to the things the app depends on.

Similar analysis tools might help us understand what causes the download size of a benchmark app to grow.

**Comment by hasen6** [comment]
Any movement on this? I noticed something that highlighted the problem very clearly. An experienced flutter developer on youtube is making tutorials about a particular app he made previously, but I couldn't help noticing that the app is 7.9MB on Android and 62.3MB (!!!) on iOS...for the exact same app as far as I can tell.

They're both version 2.01 so I assume they must be the same flutter build exported for Android and iOS. 

https://play.google.com/store/apps/details?id=com.mtechviral.devfest - 7.9MB

https://apps.apple.com/us/app/devfest-app/id1474948247?ls=1 - 62.3MB

This really not only shows the fundamental huge size difference between even a basic app in Flutter, but also how the app becomes bloated way out of control in iOS very quickly. It doesn't have any ads either so not sure what's causing the issue at all.

**Comment by 991518961** [comment]
i met the same issue,iit can not be ignored.

**Comment by hasen6** [comment]
> i met the same issue,iit can not be ignored.

Unfortunately it can and _is_ being ignored. Since it's a google framework they're only really gonna care about Android anyway.

**Comment by jonahwilliams** [comment]
This issue has pretty quickly gone of the rails. @hasen6 if you can't communicate respectfully (in line with the [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md) ) then take your business elsewhere.

Code size is absolutely a focus of flutter, but you cannot simply measure the on-disk size of a framework to deduce the download size faced by user applications. There are a number of caveats documented at https://flutter.dev/docs/resources/faq#how-big-is-the-flutter-engine, which contains the official documentation.

**Comment by hasen6** [comment]
> This issue has pretty quickly gone of the rails. @hasen6 if you can't communicate respectfully (in line with the code of conduct ) then take your business elsewhere.

If you have a problem with my lack of respect then fine but obviously that's not a reason to close an issue that many people have had. All I said is it's being ignored, since nobody has replied in half a year then I didn't have reason to believe otherwise.

>Code size is absolutely a focus of flutter, but you cannot simply measure the on-disk size of a framework to deduce the download size faced by user applications. 

Doesn't this kind of prove it's being ignored since it's clearly stated above many times that it's the size on the app store or the site listed in appstoreconnect.

Leastways, like I said I don't think being angry is a reason to close a legitimate issue. It shows a lack of respect for all those who have this problem.
