### ISSUE TITLE
Decreasing memory

### ISSUE THREAD

**Issue by congfandi** [flutter/flutter#36617]
every time I run flutter, my memory decreases. What happened?

## Logs

```
```

```
```

**Comment by kunit1** [comment]
Please provide more information. 
- Output of the flutter doctor -v
- Minimal reproduction sample
- Memory profiles
- Device(s) tested where this problem is observed

**Comment by congfandi** [comment]
```this my memory before i run flutter```
![image](https://user-images.githubusercontent.com/10652810/61584127-e64af300-ab6c-11e9-87ec-0e02f784f16d.png)

```this after i run flutter```
![image](https://user-images.githubusercontent.com/10652810/61584148-48a3f380-ab6d-11e9-8418-c564ef81d054.png)

```and this my flutter doctor```
![image](https://user-images.githubusercontent.com/10652810/61584157-62ddd180-ab6d-11e9-9594-a832bf87aa1c.png)

**Comment by congfandi** [comment]
also, i get this document.. 
![image](https://user-images.githubusercontent.com/10652810/61584206-00390580-ab6e-11e9-8a50-1a6742fd21b3.png)

**Comment by TahaTesser** [comment]
Hi @congfandi 
Please refrain from posting pictures if not necessary.
Are you experiencing the issue with the latest stable version of flutter? 
If yes, please provide the device info (MacOS version, model etc...)  and `flutter doctor -v`

Thank you

**Comment by congfandi** [comment]
hi @TahaTesser  i have been see this issue is already solved. every i clean flutter my memory is comeback again.
thankss!
