### ISSUE TITLE
Run AX Scanner on Gallery on Android

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3662]
No clue if it will tell us much, but might as well.
https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor

FYI @Hixie

**Comment by Hixie** [comment]
Right now we have tons of known accessibility bugs already, but can't hurt to try. We should definitely run this kind of thing again once we've resolved the bulk of our known bugs though.

**Comment by jonahwilliams** [comment]
a11y support is going to be an ongoing process and this isn't really a specific bug, so lets close this and use bugs for individual issues.
