### ISSUE TITLE
How to Prevent Screen Recording and Screen shoot?

### ISSUE THREAD

**Issue by Alpesh-web** [flutter/flutter#36626]
How to Prevent Screen Recording and Screen shoot?
"I using this https://developer.android.com/reference/android/view/Display.html#FLAG_SECURE 

But it worked some latest mobile only. 

Not worked Chinese mobile like Xiaomi y1 lite, Redmi note 4, Cool Pad etc screen recording inbuilt functionality. 

I developed Educational Video courses App. 

So I want someone not copy my video. 
I want prevent screen recording in all mobile device. 
It’s possible on Android. But I developed in Flutter. Please help."

My Code :

```
package www.example.com;

import android.os.Bundle;
import io.flutter.app.FlutterActivity;
import io.flutter.plugin.common.StringCodec;
import io.flutter.plugins.GeneratedPluginRegistrant;

import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugin.common.MethodChannel.MethodCallHandler;
import io.flutter.plugin.common.MethodChannel.Result;

import android.content.Context;
import android.app.KeyguardManager;
import android.view.WindowManager.LayoutParams;

public class MainActivity extends FlutterActivity {
  private static final String CHANNEL = "www.example.com/info";

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
    getWindow().addFlags(LayoutParams.FLAG_SECURE);

    new MethodChannel(getFlutterView(), CHANNEL).setMethodCallHandler(new MethodCallHandler() {
      @Override
      public void onMethodCall(MethodCall call, MethodChannel.Result result) {
        if (call.method.equals("getDeviceStatus")) {
          KeyguardManager keyGuardManager = (KeyguardManager) getSystemService(Context.KEYGUARD_SERVICE);
          result.success(keyGuardManager.inKeyguardRestrictedInputMode());
        }
      }
    });
  }
}
```

**Comment by BondarenkoStas** [comment]
@Alpesh-web if you don't mind, I would close the issue as mentioned it in a more recent similar one.

**Comment by skaran921** [comment]
i face same issue .can anyone help me regarding this problem?

**Comment by cheikh-sadbouh** [comment]
@mohit-natu , @skaran921 I think since we can prevent screen recording in android and IOS so, you can use MethodChannel in Flutter to call the native code the help to prevent screen recording.

**Comment by skaran921** [comment]
thanks for your reply.

**Comment by Bharavi26** [comment]
i am facing same issue, 
flag secure prevent screenshot capture but not work for video capture

**Comment by atishpaul** [comment]
I found a solution for this,
add these lines into your MainActivity.kt or java

`import android.os.Bundle
import android.util.Log
import android.view.SurfaceView
import android.view.View
import android.view.ViewGroup
import android.view.WindowManager
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        if (!setSecureSurfaceView()) {
            Log.e("MainActivity", "Could not secure the MainActivity!")
            // React as appropriate.
        }
    }

    private fun setSecureSurfaceView(): Boolean {
        val content = findViewById<ViewGroup>(android.R.id.content)
        if (!isNonEmptyContainer(content)) {
            return false
        }
        val splashView = content.getChildAt(0)
        if (!isNonEmptyContainer(splashView)) {
            return false
        }
        val flutterView = (splashView as ViewGroup).getChildAt(0)
        if (!isNonEmptyContainer(flutterView)) {
            return false
        }
        val surfaceView = (flutterView as ViewGroup).getChildAt(0)
        if (surfaceView !is SurfaceView) {
            return false
        }
        surfaceView.setSecure(true)
        this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
        return true
    }

    private fun isNonEmptyContainer(view: View): Boolean {
        if (view !is ViewGroup) {
            return false
        }
        if (view.childCount < 1) {
            return false
        }
        return true
    }
}

Do not forget to flutter clean and clean install.`

**Comment by atishpaul** [comment]
I found a solution to prevent video recording.
Add the below code into your MainActivity.kt or hava file

`import android.os.Bundle
import android.util.Log
import android.view.SurfaceView
import android.view.View
import android.view.ViewGroup
import android.view.WindowManager
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        if (!setSecureSurfaceView()) {
            Log.e("MainActivity", "Could not secure the MainActivity!")
            // React as appropriate.
        }
    }

    private fun setSecureSurfaceView(): Boolean {
        val content = findViewById<ViewGroup>(android.R.id.content)
        if (!isNonEmptyContainer(content)) {
            return false
        }
        val splashView = content.getChildAt(0)
        if (!isNonEmptyContainer(splashView)) {
            return false
        }
        val flutterView = (splashView as ViewGroup).getChildAt(0)
        if (!isNonEmptyContainer(flutterView)) {
            return false
        }
        val surfaceView = (flutterView as ViewGroup).getChildAt(0)
        if (surfaceView !is SurfaceView) {
            return false
        }
        surfaceView.setSecure(true)
        this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
        return true
    }

    private fun isNonEmptyContainer(view: View): Boolean {
        if (view !is ViewGroup) {
            return false
        }
        if (view.childCount < 1) {
            return false
        }
        return true
    }
}

`
Do not forget to 

> Flutter clean

>  Fresh install

**Comment by atishpaul** [comment]
I found a solution to prevent video recording.
Add the below code into your MainActivity.kt or java file

```
import android.os.Bundle
import android.util.Log
import android.view.SurfaceView
import android.view.View
import android.view.ViewGroup
import android.view.WindowManager
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        if (!setSecureSurfaceView()) {
            Log.e("MainActivity", "Could not secure the MainActivity!")
            // React as appropriate.
        }
    }

    private fun setSecureSurfaceView(): Boolean {
        val content = findViewById<ViewGroup>(android.R.id.content)
        if (!isNonEmptyContainer(content)) {
            return false
        }
        val splashView = content.getChildAt(0)
        if (!isNonEmptyContainer(splashView)) {
            return false
        }
        val flutterView = (splashView as ViewGroup).getChildAt(0)
        if (!isNonEmptyContainer(flutterView)) {
            return false
        }
        val surfaceView = (flutterView as ViewGroup).getChildAt(0)
        if (surfaceView !is SurfaceView) {
            return false
        }
        surfaceView.setSecure(true)
        this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
        return true
    }

    private fun isNonEmptyContainer(view: View): Boolean {
        if (view !is ViewGroup) {
            return false
        }
        if (view.childCount < 1) {
            return false
        }
        return true
    }
}
```
Do not forget to 

> Flutter clean

>  Fresh install

**Comment by Thuymm** [comment]
Thanks to @atishpaul 
I just converted to Kotlin code to java just below and it work for me

`import android.os.Bundle;
import android.util.Log;
import android.view.SurfaceView;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowManager;

import androidx.annotation.Nullable;

import io.flutter.embedding.android.FlutterActivity;

public class MainActivity extends FlutterActivity {
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (!this.setSecureSurfaceView()) {
            Log.e("MainActivity", "Could not secure the MainActivity!");
        }

    }

    private boolean setSecureSurfaceView() {
        ViewGroup content = (ViewGroup)this.findViewById(android.R.id.content);
        if (!this.isNonEmptyContainer((View)content)) {
            return false;
        } else {
            View splashView = content.getChildAt(0);
            if (!this.isNonEmptyContainer(splashView)) {
                return false;
            } else {
                View flutterView = ((ViewGroup)splashView).getChildAt(0);
                if (!this.isNonEmptyContainer(flutterView)) {
                    return false;
                } else {
                    View surfaceView = ((ViewGroup)flutterView).getChildAt(0);
                    if (!(surfaceView instanceof SurfaceView)) {
                        return false;
                    } else {
                        ((SurfaceView)surfaceView).setSecure(true);
                        this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE);
                        return true;
                    }
                }
            }
        }
    }

    private boolean isNonEmptyContainer(View view) {
        if (!(view instanceof ViewGroup)) {
            return false;
        } else {
            return ((ViewGroup)view).getChildCount() >= 1;
        }
    }
}
`

**Comment by Thuymm** [comment]
Thanks to @atishpaul 
I just converted to Kotlin code to java just below and it work for me

```java
import android.os.Bundle;
import android.util.Log;
import android.view.SurfaceView;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowManager;

import androidx.annotation.Nullable;

import io.flutter.embedding.android.FlutterActivity;

public class MainActivity extends FlutterActivity {
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (!this.setSecureSurfaceView()) {
            Log.e("MainActivity", "Could not secure the MainActivity!");
        }

    }

    private boolean setSecureSurfaceView() {
        ViewGroup content = (ViewGroup)this.findViewById(android.R.id.content);
        if (!this.isNonEmptyContainer((View)content)) {
            return false;
        } else {
            View splashView = content.getChildAt(0);
            if (!this.isNonEmptyContainer(splashView)) {
                return false;
            } else {
                View flutterView = ((ViewGroup)splashView).getChildAt(0);
                if (!this.isNonEmptyContainer(flutterView)) {
                    return false;
                } else {
                    View surfaceView = ((ViewGroup)flutterView).getChildAt(0);
                    if (!(surfaceView instanceof SurfaceView)) {
                        return false;
                    } else {
                        ((SurfaceView)surfaceView).setSecure(true);
                        this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE);
                        return true;
                    }
                }
            }
        }
    }

    private boolean isNonEmptyContainer(View view) {
        if (!(view instanceof ViewGroup)) {
            return false;
        } else {
            return ((ViewGroup)view).getChildCount() >= 1;
        }
    }
}
```

**Comment by Princewil** [comment]
Thanks alot @atishpaul, but I have tried(copy and paste) 
![prevent 1](https://user-images.githubusercontent.com/40724883/106830152-c830df00-668d-11eb-9c13-6e86bd9e37d6.png)
![prevent 3 real](https://user-images.githubusercontent.com/40724883/106830186-daab1880-668d-11eb-8d64-20c9e7bf0ae8.png)

 your code a thousand times and its not still working; I can't screenshot but can screen record.
I'm testing in a Infinix Hot 5 by the way. Probably there is something I'm missing

**Comment by atishpaul** [comment]
> Thanks alot @atishpaul, but I have tried(copy and paste) your code a thousand times and its not still working; I can't screenshot though but I can still screen record, meaning that only the screenshot functionality was disabled, the screen recording functionality wasn't.
> I'm testing in a Infinix Hot 5 by the way. Probably there is something I'm missing
> 
> ![prevent 1](https://user-images.githubusercontent.com/40724883/106830152-c830df00-668d-11eb-9c13-6e86bd9e37d6.png)
> ![prevent 3 real](https://user-images.githubusercontent.com/40724883/106830186-daab1880-668d-11eb-8d64-20c9e7bf0ae8.png)

Hi @Princewil ,

As you said Screenshot blocking is working for you,that means you have implemented successfully. I have again copied my own code from above and tried in my current project,and it is working fine. Both,Screenshot and video recording blocked. (Video will be recorded,but it will be completely blacked out,like in the screenshots.
Maybe it is device to device problem.But

Alternatively You can try this package. [https://pub.dev/packages/flutter_windowmanager](url)

Have not tested personally.

Import this in your landing page of your app.

`import 'package:flutter_windowmanager/flutter_windowmanager.dart';`

add below code inside of your StatefulWidget.

`Future<void> secureScreen() async {
    await FlutterWindowManager.addFlags(FlutterWindowManager.FLAG_SECURE);
  }`

call `secureScreen()` function in `initState()` . Thats it! uninstall your app,flutter clean.reinstall and check.

If it works then great! but if it is not,then read below.

Could you please show me your path where you have pasted ?
If your project has kotlin support than go to,
`app\src\main\kotlin\com.example.test_curves\MainActivity.kt` 

and if your project has java support than go to,
`app\src\main\java`  (Go inside and find MainActivity.java, After pasting of my code,you can see a suggestion from android studio,just press convert and it will convert all of my kotlin code into Java code.Or you can copy @Thuymm code. ).

Trust me,there is nothing much going on,You just have to paste it in MainActivity.kt or MainActivity.java.
Go to temporary folder (Go to start menu and type `%temp%` and SHIFT+DEL everything.) in windows os.
And make sure you have done `flutter clean` and it is necessary to uninstall your app from your device and then re-install it..

I have tested in four physical devices : 
1. Redmi Note 7 
2. Poco X3
3. K20 PRO
4. POCO M2 Pro
(Sadly all are  XIAOMI devices 😶).

My Current tested version of Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.746], locale en-IN).

**Comment by Princewil** [comment]
Thanks a lot...I Really appreciate... I will give another trial

**Comment by Sourabhbankar** [comment]
> I found a solution to prevent video recording.
> Add the below code into your MainActivity.kt or java file
> 
> ```
> import android.os.Bundle
> import android.util.Log
> import android.view.SurfaceView
> import android.view.View
> import android.view.ViewGroup
> import android.view.WindowManager
> import androidx.annotation.NonNull
> import io.flutter.embedding.android.FlutterActivity
> import io.flutter.embedding.engine.FlutterEngine
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterActivity() {
> 
>     override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
>         GeneratedPluginRegistrant.registerWith(flutterEngine);
>     }
> 
>     override fun onCreate(savedInstanceState: Bundle?) {
>         super.onCreate(savedInstanceState)
>         if (!setSecureSurfaceView()) {
>             Log.e("MainActivity", "Could not secure the MainActivity!")
>             // React as appropriate.
>         }
>     }
> 
>     private fun setSecureSurfaceView(): Boolean {
>         val content = findViewById<ViewGroup>(android.R.id.content)
>         if (!isNonEmptyContainer(content)) {
>             return false
>         }
>         val splashView = content.getChildAt(0)
>         if (!isNonEmptyContainer(splashView)) {
>             return false
>         }
>         val flutterView = (splashView as ViewGroup).getChildAt(0)
>         if (!isNonEmptyContainer(flutterView)) {
>             return false
>         }
>         val surfaceView = (flutterView as ViewGroup).getChildAt(0)
>         if (surfaceView !is SurfaceView) {
>             return false
>         }
>         surfaceView.setSecure(true)
>         this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
>         return true
>     }
> 
>     private fun isNonEmptyContainer(view: View): Boolean {
>         if (view !is ViewGroup) {
>             return false
>         }
>         if (view.childCount < 1) {
>             return false
>         }
>         return true
>     }
> }
> ```
> 
> Do not forget to
> 
> > Flutter clean
> 
> > Fresh install

Perfect..... Thanks
