### ISSUE TITLE
Firebase Auth: ApiException: 12500 (Improve Documentation)

### ISSUE THREAD

**Issue by rlechetaudemy** [flutter/flutter#36621]
Google, I think the Firebase Auth documentation should be better. I received this error:
I/flutter ( 7909): PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 12500: , null)

My project only worked after update the "OAuth consent screen" on the Google Cloud Console.
I followed this post:
https://stackoverflow.com/questions/47632035/google-sign-in-error-12500

I think that information (and much more...) should be in the docs of the Firebase Auth and Google Sign packages, thank you.
Even the Android native docs doesn't talk about this configuration!
https://firebase.google.com/docs/auth/android/google-signin

**Comment by amrit-citrusleaf** [comment]
It's not working even after updating the correct SHA1 and updating the OAuth Consent Screen with all the required values. The consent screen has been verified from Google as well. Does google API console maintain any kind of error logs?

**Comment by kroikie** [comment]
@rlechetaudemy

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1094. Any further collaboration will be done there.
