### ISSUE TITLE
Supports Kotlin or Swift for flutter programming

### ISSUE THREAD

**Issue by oky2abbas** [flutter/flutter#36622]
Hi, I am requesting support for `Swift` or `Kotlin` languages.
These two languages are `powerful` languages and have a more beautiful  & short syntax.

Kotlin also has a lot of capabilities and helps flutter.

**Currently, most developers hate dart.**

**Comment by stuartmorgan** [comment]
Duplicate of #32427

**Comment by oky2abbas** [comment]
Dart has nothing to say about big, well-built languages like Kotlin and swift, and I also want to change the official flutter language to Kotlin or swift as soon as possible, or Google will introduce a new language.


What's important is that everything is better than dart.
