### ISSUE TITLE
What is the best practices for loading default language

### ISSUE THREAD

**Issue by ra7bi** [flutter/flutter#36639]
Hey , im working on app have multiple language and im using easy_localisation dependency and also im storing preferred language Locale in shared preferences in app ,

My question what is the best practices loading default language from shared preferences  in my main function and passed to the widget as constructor or from the widget itself ? 

I don't know where i should load the default language for best performance and practice 

Thanks

**Comment by BondarenkoStas** [comment]
@ra7bi This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
