### ISSUE TITLE
[url_launcher] add immediate dial option on phone call

### ISSUE THREAD

**Issue by frediustcDev** [flutter/flutter#36634]
# Idea
I initially wanted to build an IOS / Android app that launch some ussd request in background.
I have made some test with **True Caller** that can launch a call directly. And also give a final result of an ussd request.

# Request
I want to know If the _**url_launcher**_ plug-in has such functionality or if it you could add such functionality 

# Potential Solution
I have found **intent** that could work but it only work on Android devices.
Thanks

**Comment by stuartmorgan** [comment]
url_launcher is intended purely to open URLs by handing them off to the host system. Integration with specific components that go beyond what is available via URL handling would be something to make special-purpose plugins for.
