### ISSUE TITLE
[iOS] Comparison of distinct pointer types warning 

### ISSUE THREAD

**Issue by repentsinner** [flutter/flutter#36642]
## Steps to Reproduce

1. Include cloud_functions
```Dart
import 'package:cloud_functions/cloud_functions.dart';
```
2. `open ios/Runner.xcworkspace`
2. Build in Xcode => Warning:
```
/Users/deg/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.4.0+2/ios/Classes/CloudFunctionsPlugin.m:56:59: Comparison of distinct pointer types ('NSNumber *' and 'NSNull * _Nonnull')
```
```obj-c
timeoutMicroseconds != [NSNull null]
```

Found this while doing the recommended Xcode build per:
```Could not install build/ios/iphoneos/Runner.app on f3e62265833e1fa286a468bd734f20814f52f4f8.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace
```

Thanks for considering!

**Comment by BondarenkoStas** [comment]
@repentsinner Can you please try, is it still a problem with current stable version of flutter and latest cloud_functions 0.4.1+1 package?

**Comment by BondarenkoStas** [comment]
Thank you @repentsinner ! Checked the latest cloud_functions 0.4.1+1, the comparison is still there: `cloud_functions/ios/Classes/CloudFunctionsPlugin.m:60`

**Comment by kroikie** [comment]
@repentsinner

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1190. Any further collaboration will be done there.
