### ISSUE TITLE
[web]: Firestore example

### ISSUE THREAD

**Issue by guit4eva** [flutter/flutter#36645]
Is there an example snippet floating somewhere on the great interwebs which demonstrates using Firestore with Flutter for Web?

**Comment by BondarenkoStas** [comment]
@guit4eva `cloud_firestore` is only used for Android and iOS. For web you can use [firebase dart](https://github.com/FirebaseExtended/firebase-dart). Also there is [firebase web](https://pub.dev/packages/firebase_web) plugin.

**Comment by ditman** [comment]
This is being actively worked on here: https://github.com/flutter/flutter/issues/45293.

The example of `cloud_firestore` is being updated to work on web in the PR above. 

I also "ported" the [flutterfire codelab app](https://github.com/ditman/flutterfire_codelab) to have web support (there's not much to do really, other than adding the right changes to the web/index.html file, as you can see.

I'm closing this as dup, thanks for asking!
