### ISSUE TITLE
listView如何监听手指停止滑动，离开屏幕的那一刻？(How to monitor the moment the listview finger leaves the screen？)

### ISSUE THREAD

**Issue by PacteraJiJiaWei** [flutter/flutter#36651]

**Comment by HansMuller** [comment]
Per Google translate, this bug's title is:
```How does the listView listen to the finger to stop sliding, the moment you leave the screen? · Issue #36651 ...
```

**Comment by HansMuller** [comment]
Not clear what the issue is here. Are you just asking for information or is something not working as expected?

**Comment by PacteraJiJiaWei** [comment]
How to monitor the moment the listview finger leaves the screen？

**Comment by dnfield** [comment]
You'd have to check for whether the scroll activity has non-zero and non-null velocity.  Doing so is currently a violation, but it might be easier when something like https://github.com/flutter/flutter/pull/48536/files#diff-1b163b9e852358a1be023fe77d6e7a01R262 lands.
