### ISSUE TITLE
Firebase database : Order by key/ Order by child is not working properly 

### ISSUE THREAD

**Issue by rakib205** [flutter/flutter#36661]
## Steps to Reproduce

I am using Firebase Realtime Database for one of my flutter application. I've fetch many user data as a list and build a listview. The problem is that when i apply 'Order by key' or 'order by child' , the list stays same as before (random order).

## Here is the code

    DatabaseReference reference = FirebaseDatabase.instance.reference();
    allData.length == 0
        ? reference
            .child('teachers')
            .orderByKey()
            //.orderByChild('index')
            .once()
            .then((DataSnapshot snap) {
            var keys = snap.value.keys;

            var data = snap.value;
            allData.clear();

            for (var key in keys) {
              TeachersData d = TeachersData(
                  data[key]['bio link'],
                  data[key]['email'],
                  data[key]['name'],
                  data[key]['phone'],
                  data[key]['profile link'],
                  
                  data[key]['title']);
              allData.add(d);
              
            }

## Here the screenshot of my database

<img width="643" alt="Screenshot 2019-07-22 at 12 30 15 PM" src="https://user-images.githubusercontent.com/34546369/61611026-87749f00-ac7c-11e9-8483-0e5e2dd626fd.png">

**Comment by shirish212** [comment]
I'm facing the same issue.
OrderByKey() and OrderByValue() is not working as it should be.
Always getting data in some random manner.
suggest any solution if possible.

**Comment by oligazar** [comment]
I've got the same problem here.

**Comment by kroikie** [comment]
@rakib205

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1070. Any further collaboration will be done there.
