### ISSUE TITLE
Golden files are not consistent between Flutter versions and different OS versions

### ISSUE THREAD

**Issue by timrijckaert** [flutter/flutter#36667]
## Steps to Reproduce

We are using the golden file testing method and are seeing different output being generated on different Mac/Linux/Flutter versions.

We made a very simple Widget which renders a column of text Widgets

```dart
class SomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Text("some text", style: Theme.of(context).textTheme.display1),
        Text("some text", style: Theme.of(context).textTheme.display2),
        Text("some text", style: Theme.of(context).textTheme.display3),
        Text("some text", style: Theme.of(context).textTheme.display4),
      ],
    );
  }
}
```

We have a very simple test case which generates/asserts a golden file

```dart
void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: SomeWidget(),
        ),
      ),
    );
    await expectLater(
        find.byType(SomeWidget), matchesGoldenFile("some_file.png"));
  });
}
```

Below are the different screenshots being generated on different OS versions and different Flutter versions.

**Mac OS X El Capitan 10.11.5
Flutter 1.5.4-hotfix 2**

![flutter_1 5 4-hotfix 2_osx_10_11_5](https://user-images.githubusercontent.com/6739443/61620320-f5b36480-ac70-11e9-8b8c-a6b6f2a2ef84.png)

**Mac OS X El Capitan 10.11.5
Flutter 1.7.8-hotfix 3**

![flutter_1 7 8-hotfix 3_osx_10_11_5](https://user-images.githubusercontent.com/6739443/61620462-21364f00-ac71-11e9-824d-3c546038ff12.png)

**Mac OS X Mojave
Flutter 1.5.4-hotfix 2**

![flutter_1 5 4-hotfix 2_osx_10_14_5](https://user-images.githubusercontent.com/6739443/61620487-2dbaa780-ac71-11e9-87ce-35323899c2d4.png)

**Mac OS X Mojave
Flutter 1.7.8-hotfix 3**

![flutter_1 7 8-hotfix 3_osx_10_14_5](https://user-images.githubusercontent.com/6739443/61620513-3c08c380-ac71-11e9-8691-642e7957d3b9.png)

**Linux 4.9.93
Flutter 1.5.4-hotfix 2**

![flutter_1 5 4-hotfix 2_linux_4_9_93](https://user-images.githubusercontent.com/6739443/61620543-4fb42a00-ac71-11e9-87e8-cb76f8f4b928.png)

**Linux 4.9.93
Flutter 1.7.8-hotfix 3**

![flutter_1 7 8-hotfix 3_linux_4_9_93](https://user-images.githubusercontent.com/6739443/61620562-5b075580-ac71-11e9-84aa-3f66f3a9cfa2.png)

The complete source code can be found [here](https://github.com/timrijckaert/golden_files_bug)

**Comment by Piinks** [comment]
Hi @timrijckaert, 
Thanks for filing this issue! It appears that there are two separate things going on here.

**Gold Files Across Different Platforms**
It is common for there to be slight rendering differences across platforms, most often around text. As laid out in our wiki [Writing a golden file test for package:flutter](https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter), we have relied on a single platform for creating and testing against golden files, in order to avoid the slight differences across multiple platforms.

**Golden Files Across Different Versions of Flutter**
The changes that you have noted across different versions of Flutter may have been intentional, 
which should be communicated in our release [change-logs](https://github.com/flutter/flutter/wiki/Changelog).

**Comment by Piinks** [comment]
We now have a bot in place that will help raise visibility of golden file changes, prompting contributors to go through the proper procedures to submit their change. :)

**Comment by timrijckaert** [comment]
Thanks. 
Would your suggestion be to only run golden tests on one specific machine with one specific Flutter version?

**Comment by Piinks** [comment]
I would recommend the following:

#### Machines
Running tests on one machine may be the best solution if you would like to maintain only one set of golden files. To run across all machines successfully may require separate golden 'masters' to account for the rendering differences that can happen. For example, the flutter/flutter repository has utilized skips in golden file tests for !isLinux.

#### Flutter Versions
You should be able to always test against the latest version of Flutter. We have golden tests that we run against framework changes, and notify potential changes according to [Handling Breaking Changes](https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes). If you find that you have a golden test that fails after updating your version of Flutter, and it is not in the [changelog](https://github.com/flutter/flutter/wiki/Changelog), it may mean that it was not covered by our own golden tests. In that case, I would recommend filing an issue specific to the widgets in your golden file test so we can add a golden test to flutter/flutter that will catch related changes in the future. :) 

Is that helpful @timrijckaert?

**Comment by timrijckaert** [comment]
Yes thanks!

**Comment by krispypen** [comment]
https://github.com/flutter/flutter/issues/56383#issuecomment-627173845
