### ISSUE TITLE
FirebaseAuth failing on iOS after upgrade to flutter v1.7.8+hotfix.3 and firebase_auth: ^0.11.1+3 (the same with v1.9.1+hotfix.2)

### ISSUE THREAD

**Issue by agreensh** [flutter/flutter#36676]
Errors:
**Use of undeclared identifier 'FIRAuthErrorUserInfoNameKey' 
Property 'providerID' not found on object of type '__strong id'**
(and then many more errors).

Was working before the upgrade, and still works on Android.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)

Note: Just adding firebase_auth to the pubspec.yaml of the default created app
```dart
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.11.1+3
```
causes the same issue.

**Comment by BondarenkoStas** [comment]
@agreensh do you experience it with current stable flutter version and current firebase_auth version?

**Comment by parth22** [comment]
I also face this issue in flutter 1.9.1 firebase auth not working in IOS.

**Comment by parth22** [comment]
I solve this issue to make changes in my appdelegate.m file 
```
- (void)application:(UIApplication *)application
    didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  // Pass device token to auth as per type of your development app it should be Unknown or Prod in below line.
  [[FIRAuth auth] setAPNSToken:deviceToken type:FIRAuthAPNSTokenTypeUnknown];
  // Further handling of the device token if needed by the app.
}
```

**Comment by kroikie** [comment]
@agreensh

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1093. Any further collaboration will be done there.
