### ISSUE TITLE
Problem with Firebase Messaging (when clicking on a notification)

### ISSUE THREAD

**Issue by KyllianDM** [flutter/flutter#36670]
Hello,
When I click on a notification that I've send to my app without been on (app in background), I have an error in the console :
```
`[+5762 ms] D/ZrHung.AppEyeUiProbe(14620): notify runnable to start.
[        ] D/ZrHung.AppEyeUiProbe(14620): restart watching
[  +29 ms] D/mali_winsys(14620): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
[   +9 ms] D/mali_winsys(14620): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
[   +5 ms] E/BpSurfaceComposerClient(14620): Failed to transact (-1)
[        ] E/BpSurfaceComposerClient(14620): Failed to transact (-1)
[   +6 ms] W/InputMethodManager(14620): startInputReason = 1`
```
The onResume void isn't executed.

Thanks

**Comment by BondarenkoStas** [comment]
@KyllianDM Do you encounter it with current stable flutter version and current firebase_messaging?

**Comment by KyllianDM** [comment]
Hello,
No, this problem is fixed. But I have another problem now. 

When I click on a notification, it launch onResume, but when the onResume void open a new page, onResume is looped. It's the same thing with onLaunch…

`Future<void> notificationClick(Map<dynamic, dynamic> message, context) async {
  print('notifClick');
  Navigator.pushNamed(context, 'event', arguments: null);
}`

**Comment by BondarenkoStas** [comment]
@KyllianDM Cool! Please file this another problem into another issue, otherwise it may get lost. I will close this one then.

**Comment by kroikie** [comment]
@KyllianDM

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1054. Any further collaboration will be done there.
