### ISSUE TITLE
Audio_service import in MainApplication.java error

### ISSUE THREAD

**Issue by nbfajanilan** [flutter/flutter#36675]
I followed the instructions for audio_service plugins but I am encountering import issue in my MainApplication.java. The **import com.ryanheise.audioservice.AudioServicePlugin** is not being recognized hence AudioServicePlugin renders an error.

It also shows error in AndroidManifest.xml for **com.ryanheise.audioservice.AudioService**. Is this mainly due to referencing issue?

**Comment by BondarenkoStas** [comment]
@nbfajanilan is the issue still relevant?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
