### ISSUE TITLE
Flutter run on iOS simulator takes ages to start app

### ISSUE THREAD

**Issue by codenamics** [flutter/flutter#36678]
After flutter run app is starting on simulator after 20 min sometimes more then 1 hours. this is only on iOS simulator when i just android it works. Also fresh new app is affected with this super slow and stuck start;(

Updating to 1.7.8 nothing changed still flutter run for iOS simulator is stuck and very slow to start  

## Steps to Reproduce

1. Run iOS simulator
2. flutter run

## Logs

```
+file:///Users/db/Desktop/Mobile/flutter/packages/flutter/lib/widgets.d
art
[        ] -> +file:///Users/db/Desktop/Flutter/iamsmart/lib/main.dart
[        ] -> 35191e22-84d6-4fab-abef-178ae9e4c665 build/app.dill 0
[ +319 ms] Building bundle
[        ] Writing asset files to build/flutter_assets
[  +55 ms] Wrote build/flutter_assets
[  +12 ms] Using legacy Xcode build system.
[  +27 ms] executing: [/Users/db/Desktop/Flutter/iamsmart/ios/]
/usr/bin/xcodebuild -list
```

```
[✓] Flutter (Channel master, v1.6.4-pre.14, on Mac OS X 10.14.5 18F132, locale
    pl-PL)
    • Flutter version 1.6.4-pre.14 at /Users/db/Desktop/Mobile/flutter
    • Framework revision 81c38b22cb (32 hours ago), 2019-05-24 22:51:02 -0400
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)



[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/db/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.0

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone 8 • F35EFD3E-C637-427A-8405-30EDF202939A • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by yorickreum** [comment]
Same problem. /usr/bin/xcodebuild -list takes forever…

**Comment by BondarenkoStas** [comment]
@codenamics is it the same with v1.9.1+hotfix.2?

**Comment by yorickreum** [comment]
I've done the following things now:

1. Removed Xcode 10 completely, installed Xcode 11
2. Switched from master to stable, so using Flutter v1.9.1+hotfix.2
3. Recreated ./ios folder by running `flutter create .`

Opening the project with Xcode now is much faster (although not perfectly fast). 
`/usr/bin/xcodebuild -list` inside ./ios now takes around 30 to 34 seconds.
Running Xcode build now succeeds (takes around 70s).

So, for me, it's fixed (although not perfectly, still takes quite a while for Xcode to finish "Loading Runner"...).

**Comment by codenamics** [comment]
@BondarenkoStas yes

**Comment by codenamics** [comment]
@BondarenkoStas yes

**Comment by codenamics** [comment]
i think i could be something about recou

**Comment by codenamics** [comment]
sorry for mistake closing, windows flutter run is ok IOS takes ages

**Comment by codenamics** [comment]
today's flutter run on iphone 8 took 42 min

**Comment by codenamics** [comment]
looks like update to 1.9.1+hotfix.4 did the job

**Comment by yorickreum** [comment]
Another thing I recognised concerning this: I always had my source code in an iCloud folder. Moving the code out of the iCloud folder speeded up to xCode startup impressively.
