### ISSUE TITLE
webview_flutter iOS  Xcode build error

### ISSUE THREAD

**Issue by dragen18** [flutter/flutter#36686]
Hello, I created a webview application that works just fine on Android, tested it on my phone also. Works. Tested on iPhone, Works. But when I try to build from xcode i am having the error: library not found for -lwebview_flutter. I did the steps required to have it work on iOS( adding the boolean in plist) Any suggestions? I can share any additional info if needed

**Comment by artashsanoyan** [comment]
It works fine for me, are you sure that you did everything right ?

This is how i have added permission for embedded views in my info.plist: 

```
  <key>io.flutter.embedded_views_preview</key>
  <string>YES</string>
```

**Comment by BondarenkoStas** [comment]
@dragen18 Did you find any way to solve the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
