### ISSUE TITLE
Flutter Blank Screen

### ISSUE THREAD

**Issue by DisIsGAndhi** [flutter/flutter#36697]
Flutter Application showing **blank screen** when kept in the background about half an hour that means when I resuming the app after sometime it is showing blank screen. If anyone  experienced this problem could you help me please. For normal resuming (i.e, minimize and resuming), the application was working without any problem. But after some **long time(more than 1 hour)** it was showing blank screen.
  Here I am sharing application screenshot when I got the blank screen.

flutter doctor output:
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Linux, locale en_IN)
    • Flutter version 1.7.8+hotfix.3 at /home/ag-purplle/Flutter/flutter
    • Framework revision b712a172f9 (2 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /home/ag-purplle/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /home/ag-purplle/Android/Sdk
    • Java binary at: /home/ag-purplle/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/ag-purplle/Downloads/android-studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[!] Connected device
    ! No devices available

**Comment by DisIsGAndhi** [comment]
![Blank Screen](https://user-images.githubusercontent.com/50875162/61687460-14346100-ad40-11e9-8f01-13dd40654e08.png)

**Comment by l-k22** [comment]
Can you edit your post to include your 'flutter doctor -v' output

**Comment by l-k22** [comment]
I think I've managed to replicate the issue with my own application. Left the application in background for over an hour, used other applications in the meantime. Opened the app by viewing background applications.

I was able to capture the following error message from Android Studio's logcat

```
2019-07-23 13:22:08.660 2683-2770/? I/ThermalEngine: Sensor:msm_therm:34000 mC
2019-07-23 13:22:08.834 3345-4645/? D/ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{167aac4 com.mycompany.myapp} is now in focus and seems to be in full-screen mode
2019-07-23 13:22:08.834 3345-4645/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.mycompany.myapp/com.mycompany.myapp.MainActivity/1
2019-07-23 13:22:08.834 3345-4645/? D/ActivityTrigger: ActivityTrigger activityPauseTrigger 
2019-07-23 13:22:08.835 3345-4645/? D/PowerManagerService: acquireWakeLockInternal: lock=265463535, flags=0x1, tag="*launch*", ws=WorkSource{10523}, uid=1000, pid=3345
2019-07-23 13:22:08.835 3345-4645/? D/PowerManagerService: updateWakeLockSummaryLocked: mWakefulness=Awake, mWakeLockSummary=0x1
2019-07-23 13:22:08.835 3345-4645/? D/PowerManagerService: updateUserActivitySummaryLocked: mWakefulness=Awake, mUserActivitySummary=0x1, nextTimeout=544262992 (in 292923 ms)
2019-07-23 13:22:08.835 3345-4645/? D/PowerManagerService: updateDisplayPowerStateLocked: mDisplayReady=true, policy=3, mWakefulness=1, mWakeLockSummary=0x1, mUserActivitySummary=0x1, mBootCompleted=true, screenBrightnessOverride=-1, useAutoBrightness=false, mScreenBrightnessBoostInProgress=false, mIsVrModeEnabled= false, sQuiescent=false
2019-07-23 13:22:08.836 3345-4645/? D/CompatibilityInfo: mCompatibilityFlags - 0
2019-07-23 13:22:08.836 3345-4645/? D/CompatibilityInfo: applicationDensity - 480
2019-07-23 13:22:08.836 3345-4645/? D/CompatibilityInfo: applicationScale - 1.0
2019-07-23 13:22:08.839 3345-4301/? D/ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{167aac4 com.mycompany.myapp} is now in focus and seems to be in full-screen mode
2019-07-23 13:22:08.839 3345-4301/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.mycompany.myapp/com.mycompany.myapp.MainActivity/1
```

**Comment by DisIsGAndhi** [comment]
Have You got the blank screen as like me only?

**Comment by l-k22** [comment]
Yes, all blank. But the app I've using isn't the production build it's the debug installation. I have to kill the application and reopen it for the app to work.

I will try replicating the issue with a production version.

**Comment by DisIsGAndhi** [comment]
Have you @l-k22  got the same screen after an hour?

**Comment by l-k22** [comment]
roughly an hour, I wasn't purposely trying to cause this bug, I was just using my phone as normal, and then when I returned to work on my application I found the blank screen. I don't know if there is a set time or what causes it, it could be caused by how Android frees up memory, so the timing may be influenced by how soon the device starts garbage collection. 

The error mentions whitelisting, I don't know what this is and can't find anything on google that is related specifically to Flutter.

**Comment by DisIsGAndhi** [comment]
Yeah Thank you for your response. Is there any problem with flutter coding or completely device dependent?

**Comment by l-k22** [comment]
I think it's a bug with Flutter, I've only seen this issue with my own Flutter apps. I'm not sure who the right person is to ask so I'll ping a developer I've seen post recently. @dnfield

**Comment by rahuldevanavar91** [comment]
@eseidel Please look into this, we  are facing  on production apps

**Comment by rahuldevanavar91** [comment]
@dnfield 
I don't think this is Android issue bottom three buttons are there Dev , Sandbox and Prod  View  in native Android .that shows without any issue.

**Comment by dnfield** [comment]
I mean the Android embedding, as opposed to the iOS embedding

**Comment by eseidelGoogle** [comment]
FYI @xster

**Comment by xster** [comment]
Can you describe your app a bit more? Did you follow a process similar to something like https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps? 

Is there a FlutterFragment or an io.flutter.embedding.android.FlutterView somewhere in there? 

Are you making your own FlutterEngine instance? 

Try turning on "Don't keep activities" in your Android developer options menu and see if this becomes reproducible instantly on backgrounding.

**Comment by rahuldevanavar91** [comment]
Yes, we followed the  [same process](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps).

We are using ` io.flutter.embedding.android.FlutterView` .

We are not making any changes in FlutterEngine instance.

If enable Don't keep activities option it's instantly reproducible on backgrounding.

**Comment by matthew-carroll** [comment]
Are you able to use `FlutterFragment` instead of `FlutterView`, or do you need to use a `View`? If you use `FlutterView` directly then you become responsible for doing everything that is in `FlutterFragment`, including sending app lifecycle events to Flutter at the appropriate times. My guess is that your blank screen is the result of not sending one of the required messages from Android to Flutter. Can you check that and report back?

**Comment by rahuldevanavar91** [comment]
How to send life cylce messages  to flutter if we use `FlutterView`

**Comment by matthew-carroll** [comment]
Please take a look at where/how `FlutterFragment` sends those messages:
https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterFragment.java#L616

Also, if you choose to use `FlutterView` directly you should be aware that it requires taking much more responsibility for coordinating how Flutter works. This is the tradeoff. You can use `FlutterView` in more places, but you have to do more work. It will also be more susceptible to API changes in the future. So if it's possible, I would recommend using `FlutterFragment` instead. But if you have to use a `View` then `FlutterView` can work, if you provide the right setup.

**Comment by rahuldevanavar91** [comment]
for `FlutterFragment` problem is we won't get the `FutterView` 
then the problem will be for `platformChannnel`.
```
GeneratedPluginRegistrant.registerWith(flutterView.getPluginRegistry());
        methodChannel = new MethodChannel(flutterView, PLATFORM_CHANNEL);
        
```

**Comment by matthew-carroll** [comment]
Are you referring to the old `FlutterView`? The new `io.flutter.embedding.android.FlutterView` does not have a method called `getPluginRegistry()`:
https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterView.java

The way to register channels and plugins with a `FlutterFragment` is to override `configureFlutterEngine(engine)`:
https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterFragment.java#L463

You can declare something like:

```java
public class MyFlutterFragment extends FlutterFragment {
  @Override
  protected void configureFlutterEngine(FlutterEngine engine) {
    MethodChannel myChannel = new MethodChannel(engine.getDartExecutor(), PLATFORM_CHANNEL);
  }
}
```

**Comment by rahuldevanavar91** [comment]
Thanks for the update. 
I will check this

**Comment by rahuldevanavar91** [comment]
@matthew-carroll   I have the confusion
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps as per this link.

to use fragment we have to use `Flutter.createFragment`. that returns the` io.flutter.facade.Fragment`.

but as you said to use `io.flutter.embedding.android.Flutter.FlutterFragment`

**Comment by l-k22** [comment]
> "Don't keep activities" in your Android developer

My app doesn't and it's 100% Flutter app =/

**Comment by rahuldevanavar91** [comment]
it's reproducible  if you add it in the existing native app and when you FlutterView it's confirmed

**Comment by matthew-carroll** [comment]
> @matthew-carroll I have the confusion
> https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps as per this link.
> 
> to use fragment we have to use `Flutter.createFragment`. that returns the` io.flutter.facade.Fragment`.
> 
> but as you said to use `io.flutter.embedding.android.Flutter.FlutterFragment`

Please ignore the references to `io.flutter.facade.Fragment` in that guide, it is out of date and we have a ticket filed to update it. For the sake of debugging this particular issue, please try the approach I mentioned so that we can try to locate the root cause.

**Comment by rahuldevanavar91** [comment]
After using Flutter fragment it's  working

**Comment by xster** [comment]
The remaining action items on us are to:

- Remove the facade classes from the doc https://github.com/flutter/flutter/issues/36580
- Remove the facade classes https://github.com/flutter/flutter/issues/34458
- Clearly document when using FlutterView that lifecycle messages must be pass in manually for it to work https://github.com/flutter/flutter/issues/32863

Otherwise, if you're unblocked on this symptom, we'll go ahead and close this issue.

**Comment by duongtruong12** [comment]
i faced this issues too, on latest version 1.17.3. But it on ios platform, android platform running fine
