### ISSUE TITLE
[web]: GPU accelerated listviews - Roadmapping Question

### ISSUE THREAD

**Issue by MichealReed** [flutter/flutter#36696]
I started with flutter web and have not built a native app yet, but have noticed performance issues across all browsers and devices with list view. I am working with financial data and color each row of the list view based on an underlying system I created. This works fine across all platforms when I set the item extent of the ListView to 20, but when I change the extents to lower numbers, it is almost unscrollable and maxes out the cpu on desktop web browsers and mobile web browsers. Upon further investigation, I noticed that the GPU was not being utilized in the slightest for this task.

Does flutter have plans to support hardware acceleration for listviews on web in the near future?

Are there any recommendations on how to proceed if not? Should I build out something using custom painter instead of listviews for this task?

**itemExtent: 20**
![image](https://user-images.githubusercontent.com/12153323/61649838-d835c900-ac77-11e9-9c86-482e13f80a2e.png)

**itemExtent: 1**
![image](https://user-images.githubusercontent.com/12153323/61649255-c3a50100-ac76-11e9-9cd6-3f46ea60bbad.png)

**Comment by yjbanov** [comment]
@MichealReed Could you please send us a sample code snippet that reproduces this? You could also try our CanvasKit backend, which is based on WebGL. To enable it, set the `FLUTTER_WEB_USE_SKIA` environment variable to `true` and rebuild the app with `--release` mode.

BTW, did you use `--release` mode when you benchmarked the app? By default, we build in debug mode, which is known to be slower, but gives you fast rebuilds.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
