### ISSUE TITLE
Error connecting: HandshakeException: Handshake error in client (OS Error:  	CERTIFICATE_VERIFY_FAILED: Hostname mismatch(handshake.cc:352)) - gRPC

### ISSUE THREAD

**Issue by alespotocnik** [flutter/flutter#36708]
Hi,

thanks for Flutter - it's awesome.

I do have an issue connecting to my gRPC (GO) server via Android (emulator and device).

My gRPC (GO) server is using a SSL/TLS certificate and same certificate is on my client Flutter. 
It works without any issues on iOS Simulator as well as on iPhone. 
It does not work on Android emulator nor on any Android device i tested (debug and release). 
It always returns: 
Error connecting: HandshakeException: Handshake error in client (OS Error:  	CERTIFICATE_VERIFY_FAILED: Hostname mismatch(handshake.cc:352)) 

Certificate i am using is self-signed (development of a prototype) and the gRPC (GO) server is on gcloud (GCE). 
I can communicate with the server also via grpcurl using the certificate option.

I run the certificate on https://www.digicert.com/help/ and all is marked as OK except: SSL Certificate is not trusted obviously as i issued it myself.

Is there something special to be made for Android? (permission wise, ...)
Debugging the code the certificate is loaded as an asset and is added to the call.
Here is the code: (sorry masked out the IP and port)

```
import 'package:grpc/grpc.dart';

class GrpcClientSingleton {
  ClientChannel client;
  static List<int> _certificate;
  static final GrpcClientSingleton _singleton = GrpcClientSingleton._internal();

  factory GrpcClientSingleton(List<int> certificate) {
    _certificate = certificate;
    return _singleton;
  } 

  GrpcClientSingleton._internal() {
    final channelCredentials = ChannelCredentials.secure(certificates: _certificate);
    client = ClientChannel('************',
        port: ****,
        options: ChannelOptions(
          credentials: channelCredentials,
          idleTimeout: Duration(minutes: 1),
        ));
  }
}
```

Could it be Android Studio related issue? I do not have it installed as I run Android SDK/emulator from CLI.

flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-SI)
    • Flutter version 1.7.8+hotfix.3 at /Users/alespotocnik/flutter
    • Framework revision b712a172f9 (13 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alespotocnik/Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/alespotocnik/Android
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

flutter analyze
Analyzing lwgmobile...                                                  
No issues found! (ran in 2.8s)

If i do not use SSL/TLS on gRPC all works perfectly.

thank you very much for your help, BR!

**Comment by alespotocnik** [comment]
OK i figured it out!

This is super strange - maybe just to me - all i had to do was to name (CN) the server certificate with the actual IP address and then it works on Android!?!

**Comment by jack-xiaobaicai** [comment]
I have encountered the same problem with you, please ask how to solve this problem, thank you very much.

**Comment by alespotocnik** [comment]
Hi,
i provided a solution in my last comment:

This is super strange - maybe just to me - all i had to do was to name (CN) the server certificate with the actual IP address and then it works on Android!?!

BR

**Comment by Yowims** [comment]
Hello!

Can you just write an example with a fake IP address and port? I don't understand how you managed to solve your problem.

Thanks! ^^

**Comment by kbokarius** [comment]
My problem is similar but slightly different, I'm getting the following error only with Android (iOS works fine) when connecting to a gRPC service over SSL:

```
I/flutter (11616): gRPC Error (14, Error connecting: HandshakeException: Handshake error in client (OS Error:
I/flutter (11616): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354)))
```

I'm using a Let's Encrypt SSL certificate on the backend.
