### ISSUE TITLE
Get flutter version from package_info

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#36709]
Is it possible to get the current version of flutter using the package_info plugin?

ie:
```
import 'package:package_info/package_info.dart';

PackageInfo packageInfo = await PackageInfo.fromPlatform();

String flutterVersion = packageInfo.flutterVersion;
```

**Comment by stuartmorgan** [comment]
Closing as `package_info` is deprecated in favor of [`package_info_plus`](https://pub.dev/packages/package_info_plus).
