### ISSUE TITLE
Text becomes heavier when mouse enters window (macOS)

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#36703]
`Text` widgets that have been wrapped in a `Listener` (with at least one callback defined) become heavier when the mouse enters the window. 

When the mouse is outside the window, character outlines are crisp and clear, appearing as they should.

When the mouse enters the window, whether or not the pointer is over a region that responds to mouse events, outlines become jagged and wrong looking.

If I were to _guess_, it looks like double drawing. The edges are being rendered as entirely black far more often.

<img width="200" alt="Screen Shot 2019-07-22 at 12 29 19 PM" src="https://user-images.githubusercontent.com/42326/61659607-ae32d580-ac7c-11e9-95f4-eb74d6362121.png">
<img width="189" alt="Screen Shot 2019-07-22 at 12 29 40 PM" src="https://user-images.githubusercontent.com/42326/61659608-aecb6c00-ac7c-11e9-9ca3-cd51784c7e9d.png">

@gspencergoog (I see your name on some of the more recent commits)

**Comment by shyndman** [comment]
Ran another quick test to validate the double drawing hypothesis. It appears that this is the case.

If I render one of those labels at 50% opacity, it becomes nearly black after the mouse enters the window.

**Comment by stuartmorgan** [comment]
I'm sure this is the same issues as #32529. Thanks for the extra info, I'll add that there since it narrows down the strangeness.

**Comment by shyndman** [comment]
Yup, looks like it. Thanks Stuart.
