### ISSUE TITLE
Flutter device daemon #1: process exited during startup. Exit code: 1, stderr: 'where' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ArtfulDodgerB92** [flutter/flutter#36721]
## Steps to Reproduce

Full error message:
```
java.lang.Throwable: Flutter device daemon #1: process exited during startup. Exit code: 1, stderr:
'where' is not recognized as an internal or external command,
operable program or batch file.

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:137)
	at io.flutter.run.daemon.DeviceDaemon$Command.start(DeviceDaemon.java:240)
	at io.flutter.run.daemon.DeviceService.chooseNextDaemon(DeviceService.java:225)
	at io.flutter.utils.Refreshable.runInBackground(Refreshable.java:221)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
1. In Android Studio it shows my devices list as "Loading..." but never finds the device
2. I have reinstalled:   Flutter, SDK, Android Studio, Git
3. Nothing resolves this error

## Logs

#From command prompt:#
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>flutter doctor -v
[ÔêÜ] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version
    6.1.7601], locale en-AU)
    ÔÇó Flutter version 1.7.8+hotfix.3 at X:\flutter
    ÔÇó Framework revision b712a172f9 (13 days ago), 2019-07-09 13:14:38 -0700
    ÔÇó Engine revision 54ad777fd2
    ÔÇó Dart version 2.4.0

[ÔêÜ] Android toolchain - develop for Android devices (Android SDK version 29.0.
1)
    ÔÇó Android SDK at X:\Android\sdk
    ÔÇó Android NDK location not configured (optional; useful for native profili
ng
      support)
    ÔÇó Platform android-29, build-tools 29.0.1
    ÔÇó ANDROID_HOME = X:\Android
    ÔÇó ANDROID_SDK_ROOT = X:\Android\sdk
    ÔÇó Java binary at: X:\Installations\Android Studio\jre\bin\java
    ÔÇó Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    ÔÇó All Android licenses accepted.

[ÔêÜ] Android Studio (version 3.4)
    ÔÇó Android Studio at X:\Installations\Android Studio
    ÔÇó Flutter plugin version 37.1.1
    ÔÇó Dart plugin version 183.6270
    ÔÇó Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[ÔêÜ] Connected device (1 available)
    ÔÇó SM G970F ÔÇó RF8M33L3WLK ÔÇó android-arm64 ÔÇó Android 9 (API 28)

ÔÇó No issues found!
```
C:\Windows\System32>

#From Gitbash#
```
$ flutter doctor -v
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 6.1.7601], locale en-AU)
    • Flutter version 1.7.8+hotfix.3 at X:\Flutter
    • Framework revision b712a172f9 (13 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at X:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = X:\Android
    • ANDROID_SDK_ROOT = X:\Android\sdk
    • Java binary at: X:\Installations\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at X:\Installations\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • SM G970F • RF8M33L3WLK • android-arm64 • Android 9 (API 28)

• No issues found!
```
#From Android Studio Terminal#
```
X:\Projects\Apps\Flutter\MyApp>flutter doctor -v
'where' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to find git in your PATH.
```
The template doesn't ask for anything else here, so if you do need something please just ask.

One thing that might be useful, my PATH, as it mentions it from Android Studio:
```
C:\Windows\System32>Path
PATH=C:\Users\Me\AppData\Roaming\npm;X:\Installations\Yarn\bin;X:\Installati
ons\Microsoft VS Code\bin;X:\Flutter\bin;X:\flutter\bin\mingit\cmd;C:\Program Fi
les\Git\cmd;C:\Users\Me\AppData\Roaming\npm;X:\Installations\Yarn\bin;X:\Ins
tallations\Microsoft VS Code\bin;X:\Flutter\bin;X:\flutter\bin\mingit\cmd
```

**Comment by ArtfulDodgerB92** [comment]
Actually, just noticed something as I posted.   The locations I am running flutter doctor from are different for Android Studio terminal.  When I navigate to C:\Windows\System32 and run it from there like the other examples, it seems to work fine........... is this something weird going on with my path variable?   I don't see it.

**Comment by ArtfulDodgerB92** [comment]
Can someone please help me?   I was able to resolve my path issues, and not being able to run flutter doctor from anywhere by adding c:\windows\system32 back to my PATH variable.   This is fine now and I can run flutter doctor from the AS terminal.   This is fine.   It still will not load any devices and I am still getting the IDE error I posted at the very start.  The java.lang.throwable error.   How can I resolve this?   What is it exactly that is breaking?   Can I reinstall this component?   Is it the Java SDK?

**Comment by BondarenkoStas** [comment]
@ArtfulDodgerB92 Can you confirm that you have `where.exe` at `C:\Windows\System32`? I'm not sure, but as you using Windows 7 you may need to put it to `C:\Windows\SysWOW64\` as well. From a similar issue I also saw that Anyway, did you manage to solve it?

**Comment by FilippBerzenin** [comment]
Maybe it help. I had also this problem. Add to variable system path %SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem

**Comment by mrhmamun** [comment]
I have had the same issue, I just solved my problem, after tons of search I couldn't resolve.  When I am reviewing my flutter installation using flutter doctor, I noticed that mistakenly I uninstalled Git from my computer.  After reinstalling it, now it's ok.

**Comment by iapicca** [comment]
Hi all,
if someone, after attempting the resolution proposed by @mrhmamun (thank you)
is still experiencing the issue, cold please provide
the updated  `flutter doctor -v`
and your `flutter run --verbose` or `flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by csells** [comment]
error message guides users towards putting where.exe on the path and running ```flutter doctor``` correctly reported the lack of git. this seems to be working as expected.

**Comment by harshityadav007** [comment]
In my system git is installed already everything was working fine a day before but now its taking much time to get connected with device please help.........#ANYOTHERSOLUTION

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by Sam474850601** [comment]
I have had the same issue. and i have solved it. you could delete the flutter sdk , and use a new sdk to instead of it. I guess there's something wrong with the cache

**Comment by surajjagtap8604** [comment]
no need to uninstall or reinstall anything just add "C:\Windows\System32" to the environment variable in path

**Comment by jaydip-makwana** [comment]
> I have had the same issue, I just solved my problem, after tons of search I couldn't resolve. When I am reviewing my flutter installation using flutter doctor, I noticed that mistakenly I uninstalled Git from my computer. After reinstalling it, now it's ok.

This is working for me.
Thank you :)

**Comment by askarali** [comment]
When i run the android studio as administrator it works for me

**Comment by muhammetisler** [comment]
Please help me.

**Comment by muhammetisler** [comment]
Please help me.

**Comment by Ahioma** [comment]
This is the error message I am getting 

Cannot run program "C:\Users\Uche\AppData\Local\Android\Sdk\platform-tools\adb.exe": CreateProcess error=193, %1 is not a valid Win32 application

Any suggestions on how to go about this
