### ISSUE TITLE
Application can't get data from api on google play

### ISSUE THREAD

**Issue by jindovu** [flutter/flutter#36725]
Dear Team,
      I got issue when publish app on google play, the application can't get data from server, I checked api working fine, and I run local device it's also doing well but when I build appbundle on google play it doesn't working, I don't know where issue come from
- I assign permission bellow 
> view network connections
>          full network access

![image](https://user-images.githubusercontent.com/19401173/61677836-2bb51f00-ad2b-11e9-98ad-772bc5d485f9.png)

Please help me,
Thank you.

**Comment by AlbertoGalleguillos** [comment]
Check permissions in AndroidManifest, you need to add `android.permission.INTERNET` in order to work properly with http calls

**Comment by jindovu** [comment]
I added already, but it not working, please check image bellow 
![image](https://user-images.githubusercontent.com/19401173/61687308-4e0b6480-ad4c-11e9-9b19-9768b071e619.png)

**Comment by VladyslavBondarenko** [comment]
Hi @jindovu 
have you solved your problem? can I close the issue?
Thank you

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
Thank you
