### ISSUE TITLE
Add an example illustrating drag and drop

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#3673]
We could potentially extend the shopping cart example to show drag and drop reordering.

**Comment by krisgiesing** [comment]
@abarth

**Comment by Hixie** [comment]
We have a demo of drag and drop outside the gallery. Is there a compelling reason to add one to the gallery at this time?

I'm going to close this for now. Please re-open if there's a particular customer need for this.

**Comment by shamrin** [comment]
Google "flutter drag example" query currently leads to this issue. @Hixie, where's the drag and drop demo? I couldn't find it. [Gestures docs][1] also don't mention the demo.

[1]: https://flutter.io/gestures/

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/blob/master/dev/manual_tests/lib/drag_and_drop.dart

**Comment by deborah-ufw** [comment]
hi Flutter, UI team is spec'ing interactions for our dev team and there's no where we can find to see the drag & drop in action, understand what its capabilities are or how close it comes to 

1) the requirements we have been given by our Product team, or
2) the use cases we want to solve with drag & drop

Would really like to see this re-opened.

**Comment by Hixie** [comment]
@deborah-ufw does https://github.com/flutter/flutter/blob/master/dev/manual_tests/lib/drag_and_drop.dart provide enough of an example? If not, could you file a new bug saying what you would like demonstrated? Thanks.
