### ISSUE TITLE
Textfield value should be stored inside table 

### ISSUE THREAD

**Issue by manjesha12** [flutter/flutter#36735]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by manjesha12** [comment]
``
                                DataColumn(
                                  numeric: true,
                                  label:Container(child: Text("NAME", style: TextStyle(fontSize: 14,color: Colors.white),),
                                      alignment: Alignment.center,
                                      width: 50,
                                      height: 30,

                                      decoration: BoxDecoration(
                                        border:Border.all(),
                                        color: Colors.lightBlue,

                                      )),
                                  tooltip: "NAME",
                                ),

                                DataColumn(
                              numeric: true,
                                  label:Container(child: Text("DATA", style: TextStyle(fontSize: 14,color: Colors.white),),
                                      alignment: Alignment.center,
                                      width: 50,
                                      height: 30,

                                      decoration: BoxDecoration(
                                        border:Border.all(),
                                        color: Colors.lightBlue,
                                      )),
                                  tooltip: "DATA OF THE NAME",
                                ),

                              ],

                              rows: _add.map((data) =>


                                DataRow(cells:
                                <DataCell>[
                                  DataCell(

                                  Container(height: 80,width: 3.0, child: VerticalDivider(color: Colors.black)),
                                  ),

                                  DataCell(
                                    Container(height: 80,width: 3.0, child: VerticalDivider(color: Colors.black)),

                                  ),
                                  DataCell(
                                    Container(height: 80,width: 17.0, child: VerticalDivider(color: Colors.black)),

                                  ),

                                ]
                                )

                              ).toList()

                          ),


                        ]
                    ),
                  ),

              


/*This design i am getting , but the desing is ok but how can add the values enterd in the textfelid in the rows , Where i not able use both storing and Vertical divider to for creating a table.*/
![Screenshot_1563861950](https://user-images.githubusercontent.com/52523326/61688544-eac90480-ad42-11e9-96d6-139bd8dc5d2c.png)

**Comment by HansMuller** [comment]
Please update this issue's description with an explanation of what's wrong and how to reproduce the problem. Please also  provide the output of `flutter doctor` and a small self-contained app that demonstrates the issue. Note also: https://gist.github.com/ is a useful way to share the code.
