### ISSUE TITLE
I wanted add the values textfield values to the table as it connsist of three different column

### ISSUE THREAD

**Issue by manjesha12** [flutter/flutter#36734]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by HansMuller** [comment]
Please update this issue's description with an explanation of what's wrong and how to reproduce the problem. Please also provide the output of flutter doctor and a small self-contained app that demonstrates the issue. Note also: https://gist.github.com/ is a useful way to share the code.
