### ISSUE TITLE
Unable to install flutter IOS app on non development IOS device

### ISSUE THREAD

**Issue by sydshahed** [flutter/flutter#36736]
I am working on a flutter application. although I am able to build the release version of my app without any issue. But for IOS when I use DIAWI to give link to any other user with Enterprise distribution. Installation will not complete and we have unfocused icon on the device and clicking it will do nothing. Pleas help

**Comment by BondarenkoStas** [comment]
@sydshahed I see you found a solution, great! I will post it here in case it will be useful to somebody, and close the issue.
https://stackoverflow.com/a/57176195
