### ISSUE TITLE
Flutter is taking longer than expected to report its views. Still trying...

### ISSUE THREAD

**Issue by Abdaallaa** [flutter/flutter#36742]
hey i am facing a problem : when i am trying to run me app for the first time on my phone 
the "Flutter is taking longer than expected to report its views. Still trying..." message starts to appear and i want to know where is the problem please .

and what i meant by the first time is that : when the app starts to create the db 
please want to know what is wrong and how to avoid it 

what Show Up to me i the terminal ::

```
Launching lib\main.dart on Redmi Note 5 in debug mode...
Initializing gradle...                                              1.7s
Resolving dependencies...                                           5.5s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         5.1s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                        11.8s
Flutter is taking longer than expected to report its views. Still trying...
W/Activity(20834): Slow Operation: Activity com.example.iam_here_to_try/.MainActivity onCreate took 3278ms
W/iam_here_to_tr(20834): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (light greylist, reflection)
W/iam_here_to_tr(20834): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (light greylist, reflection)
W/iam_here_to_tr(20834): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (light greylist, reflection)
W/iam_here_to_tr(20834): Accessing hidden method Landroid/util/LongArray;->get(I)J (light greylist, reflection)
I/OpenGLRenderer(20834): Initialized EGL, version 1.4
D/OpenGLRenderer(20834): Swap behavior 2
Syncing files to device Redmi Note 5...
 2,949ms (!)

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Redmi Note 5 is available at: http://127.0.0.1:53210/Xj1O8udEUT4=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
I/iam_here_to_tr(20834): ProcessProfilingInfo new_methods=465 is saved saved_to_disk=1 resolve_classes_delay=8000
```

**Comment by Narayanareddy96** [comment]
I also get the same error with an android emulator, but the app is working fine with ios simulator.

Thanks in advance.

**Comment by fuyoo** [comment]
hell

> I also get the same error with an android emulator, but the app is working fine with ios simulator.
> 
> Thanks in advance.

Buddy. I had the same problem. The SDK version is too high and the Android version of the simulator is too low. At first, my Android simulator version was Android 6.0, but the SDK version was Android Q. Later, I switched the Android version of the simulator to the latest version and compiled it.

**Comment by fuyoo** [comment]
> hey i am facing a problem : when i am trying to run me app for the first time on my phone
> the "Flutter is taking longer than expected to report its views. Still trying..." message starts to appear and i want to know where is the problem please .
> 
> and what i meant by the first time is that : when the app starts to create the db
> please want to know what is wrong and how to avoid it
> 
> what Show Up to me i the terminal ::
> 
> Launching lib\main.dart on Redmi Note 5 in debug mode...
> Initializing gradle... 1.7s
> Resolving dependencies... 5.5s
> Running Gradle task 'assembleDebug'...
> Running Gradle task 'assembleDebug'... Done 5.1s
> Built build\app\outputs\apk\debug\app-debug.apk.
> Installing build\app\outputs\apk\app.apk... 11.8s
> Flutter is taking longer than expected to report its views. Still trying...
> W/Activity(20834): Slow Operation: Activity com.example.iam_here_to_try/.MainActivity onCreate took 3278ms
> W/iam_here_to_tr(20834): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (light greylist, reflection)
> W/iam_here_to_tr(20834): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (light greylist, reflection)
> W/iam_here_to_tr(20834): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (light greylist, reflection)
> W/iam_here_to_tr(20834): Accessing hidden method Landroid/util/LongArray;->get(I)J (light greylist, reflection)
> I/OpenGLRenderer(20834): Initialized EGL, version 1.4
> D/OpenGLRenderer(20834): Swap behavior 2
> Syncing files to device Redmi Note 5...
> 2,949ms (!)
> 
> 🔥 To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
> An Observatory debugger and profiler on Redmi Note 5 is available at: http://127.0.0.1:53210/Xj1O8udEUT4=/
> For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
> I/iam_here_to_tr(20834): ProcessProfilingInfo new_methods=465 is saved saved_to_disk=1 resolve_classes_delay=8000

Buddy. I had the same problem. The SDK version is too high and the Android version of the simulator is too low. At first, my Android simulator version was Android 6.0, but the SDK version was Android Q. Later, I switched the Android version of the simulator to the latest version and compiled it.

**Comment by BondarenkoStas** [comment]
@Abdaallaa Is the issue still relevant? Can you please try it with current stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by tony123S** [comment]
After updated to sdk 1.12.13, I hit this issue too 

> 
Flutter is taking longer than expected to report its views. Still trying... 

I running on real device.

**Comment by balajiks-dev** [comment]
Hi guys, as the same code is running in iOS simulator perfectly but for android emulator it is very slow and showing this warning and error.
Note: /Users/dev/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.5.1/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/dev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Flutter is taking longer than expected to report its views. Still trying...

**Comment by tony123S** [comment]
It happened to me too after update sdk to 1.12...

**Comment by nsjcorps** [comment]
Are you running any async calls in your main functions?

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by Birinder-Gill** [comment]
Launching lib\main.dart on Redmi Note 7 Pro in debug mode...
Running Gradle task 'assembleDebug'...
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.9\android\src\main\java\io\flutter\plugins\firebasemessaging\FirebaseMessagingPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.0\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Flutter is taking longer than expected to report its views. Still trying...
Lost connection to device.

**Comment by serenebkj** [comment]
I solved this problem by opening my plugin in Settings, where under the 'installed' tab I opened the blue text  'Plugin homepage' which was a shortcut to the  JetBrains plugin page. I noticed that there was an agreement that I had to accept, being notified in the page. It said I had to accept them to get the full functionality. I did so and my problem disappeared.
