### ISSUE TITLE
curl: (3) Illegal characters found in URL

### ISSUE THREAD

**Issue by shaohui93** [flutter/flutter#36744]
When I run flutter doctor on the terminal

Downloading Dart SDK from Flutter engine 1f3013163d48f46cc967b31aac193691ef28f7d9...
curl: (3) Illegal characters found in URL

/flutter_infra/flutter/1f3013163d48f46cc967b31aac193691ef28f7d9/dart-sdk-darwin-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china

**Comment by saijayaprakash** [comment]
What is the Solution ?

**Comment by shaohui93** [comment]
I deleted everything and started all over again.

**Comment by robillo** [comment]
Having the same error.

**Comment by saijayaprakash** [comment]
This error occurred when I tampered with the git in VS Code.
Solution : 
1. Just clone the new SDK in another folder.
2. Delete the old folder.
3. If you open VS Code it will ask the SDK location .Point it to the new location. 

Ref for easy installation : https://medium.com/@sethladd/installing-flutter-on-a-mac-13a26340f80a

**Comment by robillo** [comment]
Hi. I could replicate the error every time I switch to channel master from channel stable. Everything works fine on the stable channel, but exactly this error pops up when I switch to master channel. Can you speculate why this error occurs?
