### ISSUE TITLE
Cannot change dependencies of configuration ':flutter:releaseApi' after it has been included in dependency resolution.

### ISSUE THREAD

**Issue by kuiwy** [flutter/flutter#36740]
build apk success.

Add Flutter to existing apps sync fail when I upgrade flutter sdk to 1.7.8
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)
```

**Comment by kuiwy** [comment]
Executing tasks: [assembleDebug]

Parallel execution with configuration on demand is an incubating feature.

> Configure project :LibCore
taskNames is [assembleDebug]
current module is LibCore
compilemodule  is app
apply plugin is com.android.library

> Configure project :loginlib
taskNames is [assembleDebug]
current module is loginlib
compilemodule  is app
apply plugin is com.android.library

> Configure project :app
taskNames is [assembleDebug]
current module is app
compilemodule  is app
apply plugin is com.android.application
there is no add dependencies 
=============apply===============

FAILURE: Build failed with an exception.

* Where:
Script '/Users/kuikui/flutter/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 341

* What went wrong:
A problem occurred configuring root project 'weidai.CSOnline'.
> A problem occurred configuring project ':flutter'.
   > Cannot change dependencies of configuration ':flutter:releaseApi' after it has been included in dependency resolution.

**Comment by BondarenkoStas** [comment]
@kuiwy Can you please try it with current stable version?
