### ISSUE TITLE
Connectivity plugin getWifiIP

### ISSUE THREAD

**Issue by LaurentiuSimionescu** [flutter/flutter#36747]
getWifiIP() returns device's ip not the gateway ip
Is this the normal behaviour ?
```
_connectivity.getWifiIP().then((ip) => {
    // ip is 10.100.102.222, my device's IP address
    // gateway ip is 10.100.102.1
}
```

**Comment by TahaTesser** [comment]
Hi @LaurentiuSimionescu 
Here is the [asnwer](https://pub.dev/documentation/connectivity/latest/connectivity/Connectivity/getWifiIP.html) to your question 
Thank you
