### ISSUE TITLE
Error running 'main.dart': Unknown run configuration type FlutterRunConfigurationType

### ISSUE THREAD

**Issue by Rachanashenoy** [flutter/flutter#36759]

**Comment by Rachanashenoy** [comment]
![problem](https://user-images.githubusercontent.com/46644342/61711768-7443fb00-ad72-11e9-8287-243c05fd01ae.PNG)

**Comment by Rachanashenoy** [comment]
You can see the error  message  at the botttom left.  I am stuck coz of this from the past 4 days.
Can sombody tell me what is wrong? I had recently updated android studio

**Comment by jmagman** [comment]
This looks like https://github.com/flutter/flutter/issues/16128.  Can you confirm the fix there works?
