### ISSUE TITLE
need to create UI like expand and collapse 

### ISSUE THREAD

**Issue by Nishit-Chauhan** [flutter/flutter#36750]
![Screenshot 2019-07-23 at 3 25 25 PM](https://user-images.githubusercontent.com/45855322/61702870-245b3900-ad5e-11e9-847f-aedc5ec75bce.png)

how can i create this type of UI in flutter

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
