### ISSUE TITLE
Start-up time

### ISSUE THREAD

**Issue by spierce7** [flutter/flutter#3676]
One thing I'm a little concerned with that I haven't seen anyone mention is the startup time of flutter. I opened the old sky demo, and for my nexus 5x I'm seeing startup times of 3 to 4 seconds. That's rather high for a mobile application. What's a little concerning to me is that the demo application isn't very large either.

Is start-up time something that's on the teams radar to try and lower / optimize?

**Comment by Hixie** [comment]
We are actively working on this as we speak. Our goal is to get the startup time to be in the order of a few hundred milliseconds (significantly below one second).

**Comment by eseidelGoogle** [comment]
As of last week we have a --release mode for Android which uses Dart's new ahead of time compilation support to start up in under 1s.

To try yourself:
```
cd examples/material_gallery
pub get # work around https://github.com/dart-lang/sdk/issues/26362
flutter build apk --release
flutter install
```

@yjbanov is also working on helping flutter to track these metrics better to so we can further improve this number.

Let me know if this doesn't answer your concern. :)

**Comment by spierce7** [comment]
@eseidelGoogle I've followed the project closely after it was announced as project sky. Every time I've had a concern about performance or some other issue, the flutter team always seem to be on top of it with smart, reasonable solutions. I'm very excited about flutter, and have high hopes for the project.

I'll give the code sample a try later today. Thanks for answering my questions.

**Comment by spierce7** [comment]
@eseidelGoogle I just tried this and I'm seeing an error:

```
spierce7:material_gallery spierce7$ flutter build apk --release
Building APK in release mode (android-arm-release)...
Missing files: [/Users/spierce7/frameworks/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot]
Failed to build AOT snapshot
```

```
spierce7:material_gallery spierce7$ flutter doctor
[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/spierce7/frameworks/flutter
    • Framework revision 5460e94488 (3 days ago), engine revision 76d5cf230a

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/spierce7/Android/sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.7.0_80-b15)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.1
```

**Comment by abarth** [comment]
@jason-simmons Looks like we're missing `gen_snapshot` for Mac hosts.

**Comment by yjbanov** [comment]
Known issue. Mac hosts aren't yet supported for Android AOT builds. @chinmaygarde is working on it.

**Comment by spierce7** [comment]
@yjbanov Is there some sort of ticket I can follow for the issue so I can try again once it's fixed?

**Comment by yjbanov** [comment]
@spierce7 https://github.com/flutter/flutter/issues/3719 should be close enough

**Comment by spierce7** [comment]
Awesome! Thanks :-)
