### ISSUE TITLE
Hot reload option isn't activated in android studio 3.4.2

### ISSUE THREAD

**Issue by vasubandhu** [flutter/flutter#36761]

**Comment by janmoppel** [comment]
Hello @vasubandhu !

Thank you for posting.

Closing this issue, as similar issues were already solved before: #23442, #16881, #40352. Please check, whether proposed solutions work for you. If not, then feel free to open a new issue.

Thank you.

**Comment by AhsaanAn** [comment]
Hot reload is not working in android 3.5 either, why is the case?
