### ISSUE TITLE
Flaky build failures with the latest AAR changes

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#36776]
Since flutter/flutter@242a4225a I've been occasionally seeing what seems like random and inconsistent build failures while trying to run the example plugin apps.

I've tried a few things to try to consistently reproduce the problem but so far haven't had any luck. It seems to have something to do with a race condition where `<plugin_root>/android/gradle/wrapper/gradle-wrapper.properties` will be mysteriously missing at a point where the build script relies on it.

# Crash report

 ## command

flutter build aar --quiet --suppress-analytics --output-dir plugins/packages/webview_flutter/example/build/app --debug

## exception

ProcessException: ProcessException: Process "plugins/packages/webview_flutter/android/gradlew" exited abnormally:
Exception in thread "main" java.lang.RuntimeException: Wrapper properties file 'plugins/packages/webview_flutter/android/gradle/wrapper/gradle-wrapper.properties' does not exist.
	at org.gradle.wrapper.WrapperExecutor.forWrapperPropertiesFile(WrapperExecutor.java:45)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:60)
  Command: plugins/packages/webview_flutter/android/gradlew -v

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:301:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:282:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:193:31)
<asynchronous suspension>
#4      _gradleLibraryProject (package:flutter_tools/src/android/gradle.dart:118:41)
<asynchronous suspension>
#5      buildGradleAar (package:flutter_tools/src/android/gradle.dart:511:27)
<asynchronous suspension>
#6      AarBuilderImpl.build (package:flutter_tools/src/android/aar.dart:54:11)
<asynchronous suspension>
#7      BuildAarCommand.runCommand (package:flutter_tools/src/commands/build_aar.dart:77:22)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:380:33)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:371:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#27     new Future.sync (dart:async/future.dart:224:31)
#28     CommandRunner.run (package:args/command_runner.dart:112:14)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#30     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1500:12)
#35     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1463:12)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#42     runInContext (package:flutter_tools/src/context_runner.dart:58:24)
<asynchronous suspension>
#43     run (package:flutter_tools/runner.dart:51:10)
#44     main (package:flutter_tools/executable.dart:63:9)
<asynchronous suspension>
#45     main (file://flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

/cc @blasten

**Comment by blasten** [comment]
The Flutter tool left the file system in an incorrect state. The file `gradle-wrapper.properties` is written by the tool, but it's possible that the build was cancelled before the file was generated.  The tool doesn't try to write `gradle-wrapper.properties` if `gradlew` or `gradlew.bat` exists, which is why you can't get out of this state without removing `gradlew` or `gradlew.bat` manually.

The fix could be to always check if `gradle-wrapper.properties` exists.  Going a step further, we need to introduce transactions and refactor the code to leverage the new build assemble system. cc @jonahwilliams @zanderso

**Comment by blasten** [comment]
I updated the template, so new plugins don't have this issue. The `gradle-wrapper.properties` file is always generated at `build create -t plugin` time.

**Comment by jonahwilliams** [comment]
Nothing done via Gradle dsl will benefit from assemble changes really. Perhaps we could ensure that the config file is generated correctly.

I'm highly skeptical that there is a transactional model that works cross process

**Comment by blasten** [comment]
@jonahwilliams `gradle-wrapper.properties` is generated in dart land.

**Comment by zanderso** [comment]
> The fix could be to always check if gradle-wrapper.properties exists.

What is the corrective action in this case? Generate it?

**Comment by mklim** [comment]
I have a little more info. This happened again after at least a dozen successful `flutter run` commands. The previous command was a `flutter run` command that successfully ran that I canceled after a few minutes of running on the device with `crtl+c` instead of `q`. No `flutter_log` this time and the error message was slightly different. I looked into my `../android` directory immediately after and there was still a `gradle-wrapper.properties` file, but this could be a different bug than the original one.

```
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script 'flutter/packages/flutter_tools/gradle/flutter.gradle' line: 946

* What went wrong:                                                      
Execution failed for task ':app:buildPluginDebugWebviewFlutter'.        
> Process 'command 'flutter/bin/flutter'' finished with non-zero exit value 1


$ git status
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	../android/gradle/
	android/settings_aar.gradle

$ tree ../android/gradle
../android/gradle
└── wrapper
    ├── gradle-wrapper.jar
    └── gradle-wrapper.properties
```

Subsequent runs went back to passing.

**Comment by blasten** [comment]
@zanderso yep. In this case, we should generate the file `gradle-wrapper.properties`.

**Comment by mklim** [comment]
I think [issuecomment-514350806](https://github.com/flutter/flutter/issues/36776#issuecomment-514350806) is a separate issue from the original flutter log, see [issuecomment-514775322](https://github.com/flutter/flutter/issues/36842#issuecomment-514775322).

**Comment by blasten** [comment]
This issue is fixed. The follow-up tasks are being discussed on https://github.com/flutter/flutter/issues/38988
