### ISSUE TITLE
setSystemUIOverlayStyle statusBarColor Colors.transparent don't work in Android 5.1

### ISSUE THREAD

**Issue by LeandroMoura3** [flutter/flutter#36775]
I can't make the `statusBarColor` transparent with `setSystemUIOverlayStyle` in Android 5.1.

It works fine in Android 8.1.

Someone have any suggestion?
Thanks!

**Comment by janmoppel** [comment]
Hello @LeandroMoura3 !

Thank you for posting an issue.
Can you please provide a `flutter doctor -v` output? Also, it would be very helpful if you could create a self-contained repository, so that your issue could be easily reproduced.

This issue might be also related to the #35748

Thank you.

**Comment by Reprevise** [comment]
https://github.com/flutter/flutter/issues/34678#issuecomment-536028077
You can't set `statusBar` translucency in API level 21-22 which is what Android 5.1 is.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
