### ISSUE TITLE
[flutter_tools] If `--local-engine`is specified, don't download Dart

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#36771]
When doing local engine development and/or testing, it would be nice if the tool skipped downloading Dart when a `--local-engine` flag is passed.  It should be able to just use the host dart from the engine.

This has an impact on our CI in the engine repo in particular, but is annoying when doing local testing against the framework.

/cc @jonahwilliams @zanderso

**Comment by jonahwilliams** [comment]
The logic to conditionally download dart would need to be in the flutter.sh and flutter.bat scripts, which places it at considerable risk

**Comment by dnfield** [comment]
As a local work around, I believe copying `bin/internal/engine.version` to `bin/cache/engine-dart-sdk.stamp` should short circuit the download.  I can fool around with that locally.  This probably doesn't belong in the tool though.

**Comment by jonahwilliams** [comment]
I'm going to close this issue because I really don't think we should implement anything which could place any further complexity on artifact downloading
