### ISSUE TITLE
Extract common PlatformView functionality (framework)

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#36779]
The AndroidView and UiKitView widgets are currently responsible for:
  * Managing the lifetime of the backing view (this is done in the widgets layer)
  * Assigning unique identifiers for platform views
  * Instructing the engine how to paint the widget (this is done in the rendering layer)
  * Integrating with gesture arenas (this is done in the rendering layer)
  * Adding a node to the semantics tree (this is currently done in the rendering layer)
  * Integrating with the focus tree (this is done in the widgets layer)

When supporting platform views for a new platform (whether officially supported or an external implementation of the embedding API) the platform implementers have to write code doing all of the mentioned above.

To make it easier for platform implementers, and to keep the platform view experience more consistent across platforms we'd like to expose utilities dealing with the responsibilities above that can be reused for new platforms.

### Proposal (my current recommendation)
The platform implementer would implement a PlatformViewController, sketch:

```dart
abstract class PlatformViewController {
  void clearFocus();
  void dispatchPointerEvent(PointerEvent event);
  void dispose();
}
```

The platform implementer would also implement a CreatePlatformView function, sketch signature:

```dart
class PlatformViewCreationParams {
  final int id;
  final PlatformViewCreatedCallback onPlatformViewCreated;
  final ValueChanged<bool> onFocusChanged;

  PlatformViewCreationParams(this.id, this.onPlatformViewCreated, this.onFocusChanged);
}

typedef PlatformViewController CreatePlatformView(PlatformViewCreationParams params);
```

We will provide 2 separate widgets:
  * PlatformViewControllerWidget deals with:
    * Lifetime (creating / disposing)
    * Focus
  * PlatformViewSurface deals with:
    * Painting
    * Gesture arenas
    * Semantics

A sample `FooPlatformView` widget implementation could look like:

```dart
class FooPlatformView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // (TODO: revisit the name, PlatformViewController is already defined above)
    return PlatformViewControllerWidget(
      createCallback: createFooWebView,
      builder: (BuildContext context, int id, PlatformViewController controller) {
        return PlatformViewSurface(
            id: id,
            gestureRecognizers: gestureRecognizers,
            controller: controller,
        );
      },
    );
  }
}
```

### Alternative proposal considered
Same as above, but instead of implementing `PlatformViewControllerWidget` and `PlatformViewSurface` we'd implement a single widget `PlatformView` widget, in which case the `FooPlatformView` implementation would look like:

```dart
class FooPlatformView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return PlatformView(
      createCallback: createFooWebView,
      gestureRecognizers: gestureRecognizers,
    );
  }
}
```

#### Issues with the alternative proposal
The sketch above makes assumptions that aren’t true for all platforms:
  * Platform views can be created at any time
    * This is untrue on Android, where we first need to know the size of the platform view.
  * A flow platform view layer is used to composite the platform view
    * This is untrue on Android where we composite a texture.
    * This is untrue on Fuchsia where we use a ChildView widget.

**Comment by cyanglaz** [comment]
Closing this issue as it is done in master.
