### ISSUE TITLE
flutter_view_ios__start_up is flaky

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#36783]
flutter_view_ios__start_up started being flaky around the time of https://github.com/flutter/flutter/pull/36521, which is an engine roll.

cc @gaaclarke (the sheriff for that commit), @jason-simmons (who rocks at tracking this kind of thing down).

**Comment by gaaclarke** [comment]
@Hixie Can you link the evidence of this problem so I know where to start looking?

**Comment by gaaclarke** [comment]
Here is a link to one of the failures, a timeout:
https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci9lNWVhOTk2YTFmNzMxZjZhY2NjNGU5YmY1ZDI0MzBhODQwYzk3NWY3DAsSBFRhc2sYgIDAlNeEiQsM

What future is not completing?  How do we reproduce this locally?

**Comment by gaaclarke** [comment]
I ran `flutter run --verbose --profile --trace-startup -d 4d2c437717c3dd3afed1052d955ff9a82a10d378` 10 times and never got a hang.  I was running with:

```
[✓] Flutter (Channel master, v1.8.2-pre.158, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.8.2-pre.158 at /Users/aaclarke/dev/flutter
    • Framework revision 15fa2f2226 (4 hours ago), 2019-07-23 14:03:50 -0400
    • Engine revision 7d320c45ab
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 fedd74669a)
```

Engine version 7d320c45ab is newer than the rolled version 5467f6f63046620b0ef1edc72ae06f9fad941cee

**Comment by gaaclarke** [comment]
https://github.com/flutter/flutter/blob/3b4d9f67800d6031d47df2cc44f0315e00ab285a/dev/devicelab/bin/tasks/flutter_view_ios__start_up.dart  Is the source of the test.

**Comment by Hixie** [comment]
yeah sorry, i was looking at the dashboard https://flutter-dashboard.appspot.com/build.html

**Comment by gaaclarke** [comment]
I ran this 10 times against `flutter/examples/flutter_view` like the dart test does and I've never gotten it to hang.  The same setup I mentioned earlier.  @dnfield Do you know what I could try next, is there something goofy with that device?

**Comment by dnfield** [comment]
Would be worth checking the device out and physically seeing if it looks ok

**Comment by gaaclarke** [comment]
This test has run successfully 5 times in a row since the last engine roll.  I'm going to keep an eye on it today.

**Comment by gspencergoog** [comment]
So, is this still a TODAY bug? Should it still block the roll?

**Comment by gaaclarke** [comment]
> So, is this still a TODAY bug? Should it still block the roll?

The test stopped being flakey yesterday.  It looks consistent today too:
![Screen Shot 2019-07-25 at 2 04 47 PM](https://user-images.githubusercontent.com/30870216/61908736-33b8be80-aee5-11e9-82cc-f3d931113cd6.png)

When this was reported every other run was yellow or red.

**Comment by gspencergoog** [comment]
@Hixie, what do you think?  I would like to remove the TODAY label for this: it appears to be a transient problem that has resolved itself.

**Comment by Hixie** [comment]
Ok, closing.
