### ISSUE TITLE
Call Activity.reportFullyDrawn when the first frame has rendered in Android embedding

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#36796]
See https://developer.android.com/reference/android/app/Activity.html#reportFullyDrawn()

This enables some reporting around time to first frame at the Android system level, particularly in Firebase test lab.

/cc @matthew-carroll @xster  @collinjackson

**Comment by xster** [comment]
Seems like a reasonable addition to the embedding

**Comment by dnfield** [comment]
I'm not sure that this has to be prioritized all that highly - it's not that hard to do as a consumer currently, whereas in the embedding you'll have to figure out if you even have an activity (and if the consumer _wants_ you to call it when the instance of Flutter rendering you're aware of is ready, as opposed to when some other instance is ready or when they do something else non-Flutter related).

**Comment by dnfield** [comment]
The more I think about this, the more I think of reasons we shouldn't do this (and maybe instead just document how an implementer could do it if they want).

**Comment by matthew-carroll** [comment]
Done here: https://github.com/flutter/engine/pull/11357

@dnfield if you think it should be undone, please file a ticket and we can remove it.

**Comment by dnfield** [comment]
I think this is fine.  There's a slight chance that someone would want to do _other_ things before reporting fully drawn, but I'm not sure I can think of a good case for that if they're direclty using `FlutterActivity`.  Thanks for implementing this!
