### ISSUE TITLE
[web]: Image.network not sending headers

### ISSUE THREAD

**Issue by sayurikunugi** [flutter/flutter#36798]
I'm creating an app by flutter for web.
When I tried to display images from internet like below, headers are not sent.

Image.network(loadPath,
          headers: {...
          })

Can you fix it, please?

----------------------------
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.8.2-pre.120, on Mac OS X 10.13.6 17G65, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 10.0)
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
        pod setup
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by jonahwilliams** [comment]
We should have some sort of assert in the network image. In general, browsers do not allow you to modify the headers for a request sent for a resource like img, see also https://stackoverflow.com/questions/27000152/set-custom-header-for-the-request-made-from-img-tag.

**Comment by sayurikunugi** [comment]
@jonahwilliams 
Thank you for your quick reply!
I understand. I'll do some work around suggested in the link.

**Comment by MoacirSchmidt** [comment]
This is quite inconvenient. Perhaps flutter team could improve web implementation for some workaround...

**Comment by carmas123** [comment]
Please reopen the issue, there is no resolutions to this problem.
