### ISSUE TITLE
If SnackBar.animation is asserted as non-null, why isn't it @required?

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#36804]
I noticed that `SnackBar` asserts that its `animation` field is non-null in `build()`. Why not make it required in the constructor?

**Comment by shyndman** [comment]
Hello Hans,

So this isn't a StackOverflow question. It's an API issue. 

There's a perfectly good way of statically hinting to a user that a field is required, and it's not being used — `@required`. Or alternatively, providing a reasonable default animation.

It's also a documentation problem. It's not mentioned that animation is asserted on.

Adding a `@required` should be non-breaking (except for tests). Because the absence of the field is a runtime error, it's already _effectively_ required.

CC @willlarche

**Comment by shyndman** [comment]
Ah, I did a little more research. I see that when used with a `Scaffold`, it ensures the animation exists by calling `SnackBar.withAnimation`. I guess is the common usage pattern.

**Comment by HansMuller** [comment]
You're correct that the snackbar's animation is provided by the the scaffold in the typical use case, via `SnackBar.withAnimation`.  
```
// calls snackBar.withAnimation(...)
Scaffold.of(context).showSnackBar(SnackBar(content: Text('Have a snack!')));
```

This bit of the API is a little quirky to smooth over the common use case. Thanks for the feedback though.
