### ISSUE TITLE
GC cause scrolling janky

### ISSUE THREAD

**Issue by mm-public-tx** [flutter/flutter#36808]
A. I found that in the process of Animator::BeginFrame(native) to SchedulerBinding# handleBeginFrame(dart), the most frames  take 1~2ms,  but some frames take a lot of time(shown in the screenshot).

**_TimePoint[Animator::BeginFrame]:_**  I use the parameter int the [void handleBeginFrame(Duration rawTimeStamp)](https://github.com/flutter/flutter/blob/4e973adc796415fe6bf1cf9c1afb1af590b4b476/packages/flutter/lib/src/scheduler/binding.dart#L917), the rawTimeStamp it is the Field #last_begin_frame_time_# of [Animator](https://github.com/flutter/engine/blob/0a2e28d797faf797f348e0338e6536791d279166/shell/common/animator.cc#L130)

**_TimePoint[handleBeginFrame]:_**  is the current time of invoking [SchedulerBinding# handleBeginFrame()](https://github.com/flutter/flutter/blob/4e973adc796415fe6bf1cf9c1afb1af590b4b476/packages/flutter/lib/src/scheduler/binding.dart#L917)

![image](https://user-images.githubusercontent.com/51780582/61768409-f804f280-ae19-11e9-9f0e-b70298a7d757.png)

Question:
### **Is it normal?   if it is normal , what may occur the problem, and how can I fix it?**

![image](https://user-images.githubusercontent.com/51780582/61843217-7c647d80-aecd-11e9-97b5-6a607ace14c6.png)

------------------------------------------------------------

**Comment by l-k22** [comment]
I've noticed that debug build can be a little janky but production build ran perfectly. What are you using?

**Comment by mm-public-tx** [comment]
> I've noticed that debug build can be a little janky but production build ran perfectly. What are you using?

 I  use profile mode.

**Comment by coreysprague** [comment]
What device? There is an issue (with a pending fix) that affects iPhone X/XS

https://github.com/flutter/flutter/issues/31086

**Comment by mm-public-tx** [comment]
> What device? There is an issue (with a pending fix) that affects iPhone X/XS
> 
> #31086
Android SM9600

**Comment by mm-public-tx** [comment]
> A. I found that in the process of Animator::BeginFrame(native) to SchedulerBinding# handleBeginFrame(dart), the most frames take 1~2ms, but some frames take a lot of time(shown in the screenshot).
> 
> **_TimePoint[Animator::BeginFrame]:_** I use the parameter int the [void handleBeginFrame(Duration rawTimeStamp)](https://github.com/flutter/flutter/blob/4e973adc796415fe6bf1cf9c1afb1af590b4b476/packages/flutter/lib/src/scheduler/binding.dart#L917), the rawTimeStamp it is the Field #last_begin_frame_time_# of [Animator](https://github.com/flutter/engine/blob/0a2e28d797faf797f348e0338e6536791d279166/shell/common/animator.cc#L130)
> 
> **_TimePoint[handleBeginFrame]:_** is the current time of invoking [SchedulerBinding# handleBeginFrame()](https://github.com/flutter/flutter/blob/4e973adc796415fe6bf1cf9c1afb1af590b4b476/packages/flutter/lib/src/scheduler/binding.dart#L917)
> 
> ![image](https://user-images.githubusercontent.com/51780582/61768409-f804f280-ae19-11e9-9f0e-b70298a7d757.png)
> 
> Question:
> 
> ### **Is it normal? if it is normal , what may occur the problem, and how can I fix it?**
> ![image](https://user-images.githubusercontent.com/51780582/61843217-7c647d80-aecd-11e9-97b5-6a607ace14c6.png)

I  had found the root cause of scrolling janky :   GC

My ListView  had many images,  when I scroll fast, the isolate would try to GC the images which scroll out of the viewport, and the GC operator take a long time.


![image](https://user-images.githubusercontent.com/51780582/61862291-3d035480-af00-11e9-8754-cd4a5631705e.png)
![image](https://user-images.githubusercontent.com/51780582/61862306-42f93580-af00-11e9-8ca9-69c05e1d5fbc.png)

**Comment by mm-public-tx** [comment]
@nathanrogersgoogle Whether I have a chance to avoid or reduce GC during scrolling???

**Comment by eseidelGoogle** [comment]
FYI @a-siva

**Comment by rmacnak-google** [comment]
Something seems wrong with the growth policy here. It should be attempting to use concurrent marking (application is not paused), and only fall back to parallel marking (application is paused) if concurrent marking doesn't make progress quickly enough. But in the attached timeline, the GCs are immediately resorting to parallel marking.

To debug this, I'll need a Flutter program with this behavior. Please see https://github.com/flutter/flutter/wiki/Issue-hygiene#provide-reduced-test-cases for our general guidelines on providing source code that reproduces the problem.

**Comment by markusaksli-nc** [comment]
Hi @mm-public-tx 
Is this issue still relevant on the latest master? If this is the case could you please provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
