### ISSUE TITLE
Appear confusion of fonts when using some word on iOS

### ISSUE THREAD

**Issue by ShinyG** [flutter/flutter#36801]
![75C89C9C-BA62-411C-A56C-8F29A7EECFCC](https://user-images.githubusercontent.com/17675303/61765809-30ec9980-ae11-11e9-9813-06b40e65fa07.png)

**When some text is displayed,like ⊙∀⊙！, the global font style is changed**

**Comment by janmoppel** [comment]
Hello @ShinyG !

Thank you for posting an issue.
Can you please also attach the `flutter doctor -v` command output?

Thank you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
