### ISSUE TITLE
Does flutter 1.5 require enableD8?

### ISSUE THREAD

**Issue by nesger** [flutter/flutter#36819]
There was no problem with the development with Flutter 1.0 before.   
After upgrading to 1.5, the following information is displayed at compile time:
```
android.enableD8.desugaring= true
```
This requires minSDkVersion 26, is there any way to prevent minSdkVersion from being so high, like 21?

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
