### ISSUE TITLE
Scaffold property extendBody seems to do nothing

### ISSUE THREAD

**Issue by dasmikko** [flutter/flutter#36815]
I'm experiencing some lag when having a listview inside a scaffold, where the Bottom app bar hides on scroll via SizeTransition.

I quickly noticed that the body, extends when the bottom appbar shows thought I could combat this, by setting the `extendBody` to `false`, but this changes nothing.

This seems like a bug

## Steps to Reproduce

1. Create a widget with a Scaffold
2. Set the property `extendBody` to `false`
3. Make a bottom app bar that hides on scroll via a SizeTransition
4. Scroll (bottom app bar should hide)
5. Body still extends 

```
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.615], locale da-DK)
    • Flutter version 1.7.8+hotfix.3 at C:\flutter
    • Framework revision b712a172f9 (2 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\user\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code, 64-bit edition (version 1.36.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.2.0
```

**Comment by TahaTesser** [comment]
Hi @dasmikko 
Are you still experiencing with issue with latest stable?
If yes,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by dasmikko** [comment]
Oh wow... I decided to give this a look again, and I have completely misunderstood how extendBody works.
After setting it to true, it now behaves as expected.

Closing this.
