### ISSUE TITLE
Make it easier to override shell arguments in the Android Embedding

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#36812]
Today, to enable the Dart profiler, you need to pass a boolean intent extra to Android.

There doesn't currently appear to be a way to do that for Firebase (it seems like you can do String extras, but not booleans).

We might want some way for an implementer to enable profiling based on some other intent or configuration value anyway - e.g. in MyFlutterActivity or Fragment or whatever, I tell Flutter to start the shell with profliing enabled.

/cc @matthew-carroll @liyuqian @jason-simmons 

EDIT(mattcarroll): the goal of this ticket can probably be reduced to offering a `protected FlutterShellArgs getFlutterShellArgs()` in `FlutterActivity` that operates the same way as `getInitialRoute()` and other configurations (currently the shell args are directly pulled from an `Intent`, which prevents subclass overriding in an easy way).

**Comment by dnfield** [comment]
So it's actually possible to do this already if I use the new embedding.  Something like this is working:

```java
// ...
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.android.FlutterFragment;
import io.flutter.embedding.android.FlutterView;
import io.flutter.embedding.engine.FlutterShellArgs;

public class MainActivity extends FlutterActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // ...
    }

    private FlutterShellArgs getFlutterShellArgs() {
        FlutterShellArgs args = FlutterShellArgs.fromIntent(getIntent());
        args.add(FlutterShellArgs.ARG_TRACE_STARTUP);
        args.add(FlutterShellArgs.ARG_ENABLE_DART_PROFILING);
        args.add(FlutterShellArgs.ARG_VERBOSE_LOGGING);

        return args;
    }

    @Override
    @NonNull
    protected FlutterFragment createFlutterFragment() {
        return new FlutterFragment.Builder()
                .dartEntrypoint(getDartEntrypoint())
                .initialRoute(getInitialRoute())
                .appBundlePath(getAppBundlePath())
                .flutterShellArgs(getFlutterShellArgs())
                .renderMode(FlutterView.RenderMode.surface)
                .transparencyMode(FlutterView.TransparencyMode.opaque)
                .shouldAttachEngineToActivity(true)
                .build();
    }
}
```

I think that could possibly be more ergonomic, but this is probably not all that crucial either since ther'es a way to do it and it's not likely to be needed in a lot of cases.

**Comment by matthew-carroll** [comment]
@dnfield do you still think we should make changes for this ticket, or do you think the new embedding is good enough to close this?

**Comment by dnfield** [comment]
I think we're good
