### ISSUE TITLE
Table cell spacing

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#36816]
I have a problem with table child widgets being too close to each other.
This issue is similar to https://github.com/flutter/flutter/issues/16957 but this is about Table/TableRow.
On my side I am perfectly able to work around the lack of spacing support but still would like to have it out of the box.
Not only it will save me some typing but I assume it will be faster to implement on the renderer level than by spawning tons of unnecessary Padding/Container widget instances, etc.

**Comment by timsneath** [comment]
Closed in the same vein as the comments to https://github.com/flutter/flutter/issues/16957

**Comment by chitgoks** [comment]
why is this closed? does this mean we will have to be forced to use rows/columns instead of the table class?

**Comment by duzenko** [comment]
Poor judgement on Flutter side. I expect you will at some point add this and even advertise as 'major improvement' in release notes. Hopefully I will have long switched to a better product by then.

**Comment by jlubeck** [comment]
Desperately need this... even html tables have a way to control the spacing between their cells...

**Comment by HugoHeneault** [comment]
For anyone having this issue, you can add `padding` to your cell by using this kind of `TableCellPadded` as a drop-in replacement of :

```dart
class TableCellPadded extends StatelessWidget {
  final EdgeInsets padding;
  final Widget child;
  final TableCellVerticalAlignment verticalAlignment;

  const TableCellPadded({Key key, this.padding, @required this.child, this.verticalAlignment}) : super(key: key);

  @override
  TableCell build(BuildContext context) => TableCell(
    verticalAlignment: verticalAlignment,
      child: Padding(
          padding: padding ?? EdgeInsets.all(5.0),
          child: child));
}
```

@duzenko @jlubeck feel free to provider a PR to the flutter team if you think it should be included

**Comment by duzenko** [comment]
>       child: Padding(
> 
> @duzenko @jlubeck feel free to provider a PR to the flutter team if you think it should be included

> 
> 
> ...I assume it will be faster to implement on the renderer level than by spawning tons of unnecessary Padding/Container widget instances, etc.

**Comment by HugoHeneault** [comment]
Faster, maybe. Unless you have thousands and thousands of cells, I don't think it will make a notable difference.
