### ISSUE TITLE
flutter FileSystemException

### ISSUE THREAD

**Issue by alylhb** [flutter/flutter#36825]
![image](https://user-images.githubusercontent.com/38207968/61785114-96ef1600-ae3d-11e9-9cbc-89c381def43f.png)

**Comment by BondarenkoStas** [comment]
@alylhb Is it still relevant? Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.
Please do not include screenshots of code or logs. This makes it extremely tedious to reproduce the issue, as we would have to manually transcribe your example.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
