### ISSUE TITLE
Allow obscured TextField to paste from clipboard

### ISSUE THREAD

**Issue by sterrenburg** [flutter/flutter#36826]
## Use case

`TextField` widgets do not allow users to paste the content of the clipboard by default. 

Currently, the alternative is to set `enableInteractiveSelection: true`, however this allows users to copy obscured text.

## Proposal

Add the paste functionality to the `TextField` when `obscureText: true`.

**Comment by TahaTesser** [comment]
Hi @sterrenburg 
Flutter now supports `TextField`  with ` obscureText: true` supports paste functionality 
If you're still experiencing this issue, please create a new issue and provide the information required in the template.
Thank you for your contribution
