### ISSUE TITLE
setting_aar.gradle breaks Gradle build

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#36842]
After a few hours of playing around with all variables I could think of (clearing cache, switching channels, changing Gradle versions etc.), I finally found what variable was causing my Android builds to fail.

`flutter run -v` only says that the `assembleDebug` task failed and `gradlew assembleDebug --info` does not give any information. It simply ends with exit code 1 after building all plugins (no matter what plugins, they build fine) and then it crashes and stops the daemons.

## Cause

[Commit 242a4225a1bfc726360e7d0f26325d5ac4d30891](https://github.com/flutter/flutter/commit/242a4225a1bfc726360e7d0f26325d5ac4d30891) introduced this issue.

The change I noticed when copying `android` directories from working builds is that a new file `settings_aar.gradle` was added, i.e. only builds that print the following at the beginning break (it is only printed when the file did not exist before):

```
flutter.tools ✅ `android\settings_aar.gradle` created successfully.
```

## Environment

 - Gradle version `5.1.1` (I also tried upgrading, but that did not help)
 - `com.android.tools.build:gradle:3.4.0`

I tried to follow `flutter_gallery` and downgraded to Gradle version `4.10.2` and build tools `3.2.1`, but this only lead to me [this problem](https://stackoverflow.com/q/54627009/6509751) and I have no idea how to solve that in my Flutter project either.

**Comment by prasant10050** [comment]
i am also facing this issue in the same version
Script '/Users/me/Library/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 946

**Comment by creativecreatorormaybenot** [comment]
@blasten #36732 causes this, i.e. breaks my builds.

**Comment by blasten** [comment]
Which plugins are you using in `pubspec.yaml`?  

To temporarily disable this feature, you can run `flutter config --no-enable-build-plugin-as-aar`, and you run the same command again.

**Comment by creativecreatorormaybenot** [comment]
>To temporarily disable this feature, you can run `flutter config --no-enable-build-plugin-as-aar`, and you run the same command again.

This fix worked for me, which is already great.

I am using essentially all of [these plugins](https://github.com/flutter/plugins/blob/master/FlutterFire.md) (with some exceptions, but I would think that they are very similar), [`wakelock`](https://pub.dev/packages/wakelock), and [`path_provider`](https://pub.dev/packages/path_provider) + [`shared_preferences`](https://pub.dev/packages/shared_preferences).

**Comment by blasten** [comment]
Would you mind sharing your pubspec.yaml?

**Comment by creativecreatorormaybenot** [comment]
@blasten The following dependency will produce the issue (with `flutter config --enable-build-plugin-as-aar`, i.e. `"enable-build-plugin-as-aar" value as "true"`:

```yaml
cloud_firestore: any
```
Upon removing the dependency again, the application builds fine and `pubspec.yaml` contains no other dependency. I did not test other dependencies as this seems to reproduce the issue just fine for me.

**Comment by blasten** [comment]
@creativecreatorormaybenot I just found that you need to enable `multiDex` in `android/app/build.gradle` to fix "8: Cannot fit requested classes in a single dex file (# methods: 74584 > 65536)", but this is true with flag on or off.

Would you mind sharing the output of `flutter doctor`?

**Comment by mklim** [comment]
May be related to flutter/flutter#36776. Difference is that one has been flaky but it sounds like this is totally blocking.

Also sounds like flutter/flutter#36846.

**Comment by creativecreatorormaybenot** [comment]
@blasten Well, you are correct. I forgot to share the `build.gradle` file. It contains the following dependencies (with `multiDexEnabled true` in the `android` section):

```
dependencies {
    implementation 'androidx.multidex:multidex:2.0.1'
}
```

However, as I described earlier, there are no error messages in `gradlew assembleDebug --info` (I would certainly see the dex limit and that even without the verbose flag on `flutter run` and certainly without running `--info` on the Gradle task) and I tested that it certainly fails only with the commit I referred to in my [original comment]()

[Output of `flutter doctor -v`](https://gist.github.com/creativecreatorormaybenot/388ce22bb8de93d3b661f8d5a0f94af2). Note that I did edit the paths etc., so this is not **exactly** the output and one important notice, to prevent fallacies.., the issue occured with Android SDK version `28` as well, i.e. I have that installed and ran the build with `targetSdkVersion 28`.

**Comment by mklim** [comment]
I went from a state where this error would happen very infrequently to where it was suddenly happening every time and blocking all my builds. After debugging I figured out that it was because of a syntax error in the plugin's Java source code I was working on.

I think maybe this Gradle error is logged every time a plugin dependency fails to compile for any reason?

Disabling the new build flag with `flutter config --no-enable-build-plugin-as-aar` and reverting to the old compile system ended up printing the actual syntax error instead of the Gradle one. Fixing the syntax error fixed the Gradle failure when I switched back to the new system.

**Comment by creativecreatorormaybenot** [comment]
@mklim 

>I think maybe this Gradle error is logged every time a plugin dependency fails to compile for any reason?

What error do you mean? For me there is no error printed apart from the `assembleDebug failed` message when executing `flutter run -v`.

**Comment by mklim** [comment]
@creativecreatorormaybenot Sorry, I was referring to the `WHERE: Script 'flutter_tools/gradle/flutter.gradle' line: 946` message mentioned in [issuecomment-514651692](https://github.com/flutter/flutter/issues/36842#issuecomment-514651692). Are you not seeing that specific one?

**Comment by creativecreatorormaybenot** [comment]
@mklim Thanks and sorry, I saw the issue you referenced late.

No, I never saw that message.

**Comment by mklim** [comment]
Got it, my mistake. Sorry about that, I'll move my comment to the right issue. :)

**Comment by creativecreatorormaybenot** [comment]
@blasten I tested it again and #36886 did not fix it.

**Comment by blasten** [comment]
In Gradle `5.1.1`, `TaskInternal.execute()` has been removed. Unfortunately, my changes relied on this method to execute the task that builds the plugins during the configuration phase.  As a result, this feature has been disabled until I find a fix.
