### ISSUE TITLE
Flutter needs a [decent] way to auto hide keyboard when scrolling a list

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#36869]
Auto hide keyboard on scroll is a really popular feature on apps that contain a search screen. Just check, for example **Netflix** app. It's, however, really really hard to implement this in Flutter. Every step of the way is unintuitive and it feels the framework is fighting back.

You can't use `_scrollController.position.isScrollingNotifier.addListener(...)` because when the list changes it triggers the scroll notifier and hides the keyboard. You can't use `NotificationListener<ScrollNotification>` for the same reason and a few others (like, what if you tap to show the keyboard after it began scrolling). On Android, `onScrollListener` from RecyclerView is only triggered when user is physically scrolling, and not when the list is changing.. but no problem. Let's use GestureDetector to detect a gesture and dismiss the keyboard:
```dart
GestureDetector(
    onVerticalDragUpdate: (details) {
        if (details.primaryDelta > 20) {
            FocusScope.of(context).unfocus();
        }
    },
```
Oh, ops! This would be the perfect solution but https://github.com/flutter/flutter/issues/23325 ListView eats the scroll callback, so GestureDetector is not triggered. It seems the only possible way to hide a keyboard when scrolling is using `Listener`, which gives you `onPointerDown: (PointerDownEvent event)`. You don't get verticalDragUpdate, you don't get anything. Even if user just taps on an item, you get the callback to remove the keyboard. So you need to take care of everything manually, which is terrible.

So, in review:
[x] isScrollingNotifier or NotificationListener<ScrollNotification> -> triggered when list changes
[x] GestureDetector -> ListView swallows it
[x] Listener -> Works, but you have to suffer.

Flutter really needs a better way to do this. In my opinion, if GestureDetector started working (i.e. ListView stopped eating the scroll callback), this problem would be solved. It is really basic and it is frustrating there is no decent way.

**Comment by bernaferrari** [comment]
Additional info: I would like to hide a bottom sheet when it is on top and user scrolls. If I use ScrollController's addListener, I get every scroll movement. I need to use GestureDetector, but ListView is incompatible with it, which is frustrating. 

Just fix the GestureDetector, I'll be happy. Two issues will be solved.

**Comment by szotp** [comment]
Try this.

```dart
void dismissKeyboard(BuildContext context) {
  FocusScope.of(context).requestFocus(FocusNode());
}

class DismissKeyboardOnScroll extends StatelessWidget {
  final Widget child;
  final Function onDismiss;

  const DismissKeyboardOnScroll({Key key, this.child, this.onDismiss})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return NotificationListener<ScrollStartNotification>(
      onNotification: (x) {
        if (x.dragDetails == null) {
          return;
        }

        dismissKeyboard(context);
        if (onDismiss != null) {
          onDismiss();
        }
      },
      child: child,
    );
  }
}

```

**Comment by truongsinh** [comment]
> FocusScope.of(context).requestFocus(FocusNode());

maybe changed to `FocusScope.of(context).unfocus();`, ref https://github.com/flutter/flutter/issues/7247#issuecomment-491038982

**Comment by szotp** [comment]
@truongsinh Thanks for suggestion, I changed my snippet.

**Comment by bernaferrari** [comment]
Well, that surprisingly works! I tried a lot of approaches, contacted many people, but no one had the idea of merging NotificationListener with dragDetails. I guess I'll need to close the issue - I still think this is not-trivial and this issue is going to get more popular in the future as more people need this behaviour. Thank you, @szotp!

**Comment by officer47p** [comment]
> Well, that surprisingly works! I tried a lot of approaches, contacted many people, but no one had the idea of merging NotificationListener with dragDetails. I guess I'll need to close the issue - I still think this is not-trivial and this issue is going to get more popular in the future as more people need this behaviour. Thank you, @szotp!

Hey @bernaferrari , happy new year.
It;'s been more than a year since you faced this issue, I have faced this issue lately too, and I was wondering if you could find a better solution for it.

**Comment by valvoline** [comment]
Hi all, may I suggest a little change to the @szotp approach, in order to detect just the bottom dragging user interation that, in my case, was what I needed for:

```
class DismissKeyboardOnScroll extends StatelessWidget {
  final Widget child;
  final Function onDismiss;

  const DismissKeyboardOnScroll({Key key, this.child, this.onDismiss}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return NotificationListener<ScrollNotification>(
      onNotification: (x) {
        if (x is UserScrollNotification && x.direction == ScrollDirection.forward) {
          FocusScope.of(context).unfocus();
          onDismiss?.call();
          return;
        }
        return;
      },
      child: child,
    );
  }
}
```

**Comment by Urkman** [comment]
This does not work on a SliverList(CustomScrollView)...
Is there something else that could work?
