### ISSUE TITLE
Firebase_Auth: need the Refresh token and access token

### ISSUE THREAD

**Issue by premtemp1** [flutter/flutter#36873]
Hello,
 How do I get the refresh_token and Access token when a user create an account with ID/pass or social login (facebook, google).
 
I need this information in order to authenticate my user with out custom API backend

Currently, the Firebase object does not contain the refresh_token.

I look at the rest api and there instances where the token is returned

https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=[API_KEY]

Can you update the plugin to return token or suggest another option to get this value

Thanks

**Comment by collinjackson** [comment]
duplicate of #35974

**Comment by kroikie** [comment]
@premtemp1

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1092. Any further collaboration will be done there.
