### ISSUE TITLE
PageView doesn't always fully complete its nextPage() animation

### ISSUE THREAD

**Issue by exo-pla-net** [flutter/flutter#36876]
After calling _pageController.nextPage(), the PageView will appear to animate to the next page, as expected.

However, when looking at _pageController.page when the animation stops, you will sometimes find that, for instance, (_pageController.page == 2.999998), instead of (_pageController.page == 3.0).

This behavior is inconsistent -- it happens on my Pixel 2, but not on my Pixel 3.

This is a _problem_, because developers will sometimes be inclined to do something like: 

`bool animationIsComplete =`
`_pageController.page.floor() == _pageController.page.ceil();`

Given that this boolean will never be true, but only on certain devices, some nasty, difficult-to-isolate bugs are inevitable.

**Comment by Piinks** [comment]
Hi @exo-pla-net, 
Welcome! And thanks for opening this issue. We'll need some more information to be able to better address it. 
Can you provide a minimum runnable code sample that we can test to observe the inconsistent behavior? And can you also provide the output of `flutter doctor -v`?

**Comment by goderbauer** [comment]
@chunhtai You fixed something in this area recently. Would that have covered this?

**Comment by chunhtai** [comment]
No, the fixing was mainly dealing with how to handle the floating point precision error in comparison. We did not do any error correction in the controller itself, and I don' think there is any plan to fix this yet as the error correction itself might still introduce error as long as we are using double. One way to address this is to provide a int value instead, but I think this will over complicate the api.
If your goal is to check whether animation is complete, one way you can do that is checking scroll notification.

```
NotificationListener(
      onNotification: (ScrollNotification notification) {
        if (notification is UserScrollNotification) {
          if (notification.direction.toString() == "ScrollDirection.idle") {
            print('it is idle');
          }
        }
        return true;
      },
    child:PageView(
        controller: PageController(viewportFraction: 1),
        children: [
          Text('text1'),
          Text('text2'),
          Text('text3'),
        ]
      ))
```
