### ISSUE TITLE
Discuss how we would like devs to approach splash behavior when using FlutterView directly

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#36888]
Discuss how we would like devs to approach splash behavior when using FlutterView directly

**Comment by darshankawar** [comment]
This is probably mentioned in [this](https://flutter.dev/docs/development/ui/advanced/splash-screen) document on how to use splash screen using FlutterView.
I am going ahead and closing this as resolved. If anybody disagrees or think this should be kept open, please write in comments and I'll reopen.
Thanks.
