### ISSUE TITLE
Document instructions for building/debugging a locally built engine for iOS

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#3689]
It's pretty easy to do on Android - just supply `--engine-src-path` to `flutter run`. On iOS this option does not seem to work. If such a document already exists, then perhaps all we need is link to it from https://github.com/flutter/engine/blob/master/CONTRIBUTING.md.

/cc @chinmaygarde @tvolkert

**Comment by abarth** [comment]
My understanding is that this is the state of the art:

https://github.com/flutter/engine/wiki/Flutter-Apps-on-iOS

I'm hopeful we can do a bit better here, but it will probably require some effort.

**Comment by yjbanov** [comment]
Thanks! The instructions worked!

**Comment by yjbanov** [comment]
https://github.com/flutter/engine/pull/2641

**Comment by eseidelGoogle** [comment]
@chinmaygarde has planned to fix --engine-debug, etc. for iOS by making the artifacts.zip buckets we upload to GCS match the layout of our out/ directory better.  Right now the flutter tool has a bunch of hard-coded paths in --engine-debug, etc. for Android out/ directories.

**Comment by yjbanov** [comment]
It would certainly be nice to have a consistent solution between Android and iOS for consuming a custom engine build (e.g. not to have to launch Xcode). This specific issue is solved though, as all I was looking for is the instructions, and those that @abarth pointed to worked just fine for me. So closing.
