### ISSUE TITLE
How to Long Press Pictures to Save to Mobile Phone?????Who can help me.Thanks

### ISSUE THREAD

**Issue by R907** [flutter/flutter#36905]

**Comment by wendyadi** [comment]
@R907 You should ask on stackoverflow instead of making an issue in github.

**Comment by BondarenkoStas** [comment]
@R907 This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
