### ISSUE TITLE
Flutter doctor cant execute jdk

### ISSUE THREAD

**Issue by phaalonso** [flutter/flutter#36900]
I have this problems in flutter doctor

<pre><font color="#4E9A06">[✓]</font> Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale pt_BR.UTF-8)
<b>    </b><font color="#8AE234"><b>•</b></font><b> Flutter version 1.7.8+hotfix.4 at /home/pedro/development/flutter</b>
<b>    </b><font color="#8AE234"><b>•</b></font><b> Framework revision 20e59316b8 (6 days ago), 2019-07-18 20:04:33 -0700</b>
<b>    </b><font color="#8AE234"><b>•</b></font><b> Engine revision fee001c93f</b>
<b>    </b><font color="#8AE234"><b>•</b></font><b> Dart version 2.4.0</b>

<font color="#C4A000">[!]</font> Android toolchain - develop for Android devices (Android SDK version 29.0.1)
<b>    </b><font color="#8AE234"><b>•</b></font><b> Android SDK at /home/pedro/Android/Sdk/</b>
<b>    </b><font color="#8AE234"><b>•</b></font><b> Android NDK location not configured (optional; useful for native profiling</b>
<b>      support)</b>
<b>    </b><font color="#8AE234"><b>•</b></font><b> Platform android-29, build-tools 29.0.1</b>
<b>    </b><font color="#8AE234"><b>•</b></font><b> Java binary at: /usr/local/jdk-11.0.2/bin/java</b>
<b>    </b><font color="#EF2929"><b>✗</b></font><b> Cannot execute /usr/local/jdk-11.0.2/bin/java to determine the version</b>

<font color="#4E9A06">[✓]</font> Android Studio (version 3.4)
<b>    </b><font color="#8AE234"><b>•</b></font><b> Android Studio at /home/pedro/development/android-studio</b>
<b>    </b><font color="#8AE234"><b>•</b></font><b> Flutter plugin version 37.1.1</b>
<b>    </b><font color="#8AE234"><b>•</b></font><b> Dart plugin version 183.6270</b>
<b>    </b><font color="#8AE234"><b>•</b></font><b> Java version OpenJDK Runtime Environment (build</b>
<b>      1.8.0_152-release-1343-b16-5323222)</b>

<font color="#C4A000">[!]</font> Android Studio
<b>    </b><font color="#8AE234"><b>•</b></font><b> Android Studio at /home/pedro/.AndroidStudio3.4/</b>
<b>    </b><font color="#EF2929"><b>✗</b></font><b> Flutter plugin not installed; this adds Flutter specific functionality.</b>
<b>    </b><font color="#EF2929"><b>✗</b></font><b> Dart plugin not installed; this adds Dart specific functionality.</b>
<b>    </b><font color="#EF2929"><b>✗</b></font><b> android-studio-dir = /home/pedro/.AndroidStudio3.4/</b>
<b>    </b><font color="#EF2929"><b>✗</b></font><b> Unable to find bundled Java version.</b>
<b>    </b><font color="#8AE234"><b>•</b></font><b> Try updating or re-installing Android Studio.</b>
<b>    </b><font color="#8AE234"><b>•</b></font><b> Consider removing your android-studio-dir setting by running:</b>
<b>      flutter config --android-studio-dir=</b>

<font color="#4E9A06">[✓]</font> VS Code (version 1.36.1)
<b>    </b><font color="#8AE234"><b>•</b></font><b> VS Code at /usr/share/code</b>
<b>    </b><font color="#8AE234"><b>•</b></font><b> Flutter extension version 3.2.0</b>

<font color="#C4A000">[!]</font> Connected device
<b>    </b><font color="#FCE94F"><b>!</b></font><b> No devices available</b>

<font color="#C4A000">!</font> Doctor found issues in 3 categories.
</pre>

**Comment by BugsBunnyBR** [comment]
Do you need the jdk 11? How about to downgrade to jdk 8 as you will not be able to compile android code with jdk 11?

**Comment by BondarenkoStas** [comment]
@phaalonso Is it still relevant? how about with current stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
