### ISSUE TITLE
http request 403 Forbidden

### ISSUE THREAD

**Issue by althurzard** [flutter/flutter#36913]
My server is located in vietnam, my friend at singapore has make some requests in flutter then got error "403 Forbidden. The request was a legal request, but the server is refusing to respond to it"
But in the postman its working fine.

**Comment by BondarenkoStas** [comment]
@althurzard Please provide you `flutter doctor -v`

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
