### ISSUE TITLE
Android Log don't show

### ISSUE THREAD

**Issue by GanZhiXiong** [flutter/flutter#36912]
![image](https://user-images.githubusercontent.com/27394631/61844217-37424a80-aed1-11e9-9b7b-73cf66d28fe0.png)

The Log that I wrote in Android MainActivity onCreate, the debug Flutter App doesn't show that, how do I fix that?

**Comment by BondarenkoStas** [comment]
@GanZhiXiong Please provide your `flutter doctor -v` output.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
