### ISSUE TITLE
Update flutter.io's social sharing metadata

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3691]
Currently, it looks like we're not advertising the right metadata when we're shared. We show this:

![screen shot 2016-05-03 at 7 52 15 am](https://cloud.githubusercontent.com/assets/5479/14987259/1575cd82-1104-11e6-9771-401f421b22a3.png)

We could:
- [ ] display an image
- [ ] show relevant description

**Comment by Hixie** [comment]
We need this before beta for sure!

**Comment by Hixie** [comment]
cc @sethladd This should be pretty easy to do, right?

**Comment by sethladd** [comment]
We'll likely do this as part of the website upgrades we envision.

cc @maguinis

**Comment by Hixie** [comment]
cc @filiph
