### ISSUE TITLE
Scaffold drawer start drag point too much near the edge

### ISSUE THREAD

**Issue by fralways** [flutter/flutter#36929]
I'm receiving a lot of bug reports saying that scaffold drawer doesn't work, but actually it is working just the start point for dragging is too much near the edge. I'm unsure for android users, but iOS users consider starting point to be too much near the edge and because of this many users are not aware that drawer exists in the app. They try the gesture but it fails. Solution would be to either increase offset from the edge for starting the gesture or to allow developer to insert his own offset value. 
This is same for both left and right scaffold drawers.

```
 Flutter (Channel beta, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E226, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by fralways** [comment]
@shihaohong any eta? I need to do update for the app soon, and would be nice to know if I should wait or implement custom solution.

**Comment by shihaohong** [comment]
Hi @fralways, I cannot provide an ETA since I'm unsure when I will start to work on this, as I currently have higher priority issues I have to work on. I think your best bet is to implement a custom solution for now. In the meantime, one thing you could do is go into the `drawer.dart` source code, make a copy of it, and directly change the constant values in there.
