### ISSUE TITLE
ScrollController does not connect to ListView

### ISSUE THREAD

**Issue by AhmetAY** [flutter/flutter#36939]
Although I add the ScrollController to the ListView, the client of the ScrollController does not appear. Result of print : ScrollController#a6158(no clients)

```
ScrollController sc = new ScrollController();
ListView(
  controller: sc,
  padding: const EdgeInsets.all(8.0),
  children: <Widget>[
    Container(
      height: 150,
      color: Colors.amber[600],
      child: const Center(child: Text('Entry A')),
    ),
    Container(
      height: 150,
      color: Colors.amber[500],
      child: const Center(child: Text('Entry B')),
    ),
    Container(
      height: 150,
      color: Colors.amber[100],
      child: const Center(child: Text('Entry C')),
    ),
  ],
);
print(sc.toString());
```

**Comment by BondarenkoStas** [comment]
Just to have a [link](https://stackoverflow.com/questions/57199866/scrollcontroller-does-not-connect-to-listview) here in case any answer will appear.
@AhmetAY Did you find a solution? 
Please provide your ```flutter doctor -v```.

**Comment by VladyslavBondarenko** [comment]
@AhmetAY 
I hope you've solved your problem.
Probably you needed to add listener 
https://medium.com/@diegoveloper/flutter-lets-know-the-scrollcontroller-and-scrollnotification-652b2685a4ac
Closing the issue
