### ISSUE TITLE
When the release product is compiled in IOS mode, the Flutter product does not work correctly and is still a debug product.

### ISSUE THREAD

**Issue by mengshuaiyu** [flutter/flutter#36930]
When the release product is compiled in IOS mode, the Flutter product does not work correctly and is still a debug product.

Version: v1.7.8 + hotfix.4

**Comment by vagrantrobbie** [comment]
How are you compiling your release version?

**Comment by mengshuaiyu** [comment]
Publish using xcode  @vagrantrobbie

**Comment by vagrantrobbie** [comment]
did you build the Dart using the --release flag as per the docs here [https://flutter.dev/docs/deployment/ios](https://flutter.dev/docs/deployment/ios)

`flutter build ios --release`

And then you Run or Archive it from XCode. Don't forget to open the `Runner.xcworkspace` in Xcode and not Runner.xcodeproj

**Comment by BondarenkoStas** [comment]
@mengshuaiyu is the issue still relevant?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
