### ISSUE TITLE
How can I debug the flutter engine code on the ios simulator?

### ISSUE THREAD

**Issue by wangqianjun** [flutter/flutter#36931]
How can I debug the flutter engine code on the ios simulator?

**Comment by gaaclarke** [comment]
1) Checkout [Flutter Engine](https://github.com/flutter/engine) (it uses [depot_tools](https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up) to pull in third party code)
2) use gn to create your ninja build files: `./flutter/tools/gn --ios --simulator --unoptimized`
3) use ninja to build the engine: `ninja -j 100 -C out/ios_debug_sim_unopt && ninja -j 100 -C out/host_debug_unopt/`
4) Run your flutter project with the custom engine: `flutter --local-engine-src-path $FLUTTER_ENGINE_SRC_DIR --local-engine=ios_debug_sim_unopt run`

You'll find more information on the [Flutter Engine](https://github.com/flutter/engine) page.
