### ISSUE TITLE
web  dart: not found

### ISSUE THREAD

**Issue by Baloneo** [flutter/flutter#36933]
➜  hello_world git:(stable)  webdev serve
/home/baloneo/software/flutter/.pub-cache/bin/webdev: 7: /home/baloneo/software/flutter/.pub-cache/bin/webdev: dart: not found

**Comment by Baloneo** [comment]
when i add flutter/bin/cache/dart-sdk/bin to $PATH
➜  hello_world git:(stable) webdev serve                                  
Unhandled exception:
ProcessException: ***OUT***

***ERR***
The Flutter SDK is not available.

***
  Command: /home/baloneo/software/flutter/bin/cache/dart-sdk/bin/pub deps
#0      _runPubDeps (package:webdev/src/pubspec.dart:70:5)
<asynchronous suspension>
#1      PubspecLock.read (package:webdev/src/pubspec.dart:84:11)
<asynchronous suspension>
#2      readPubspecLock (package:webdev/src/command/shared.dart:62:39)
<asynchronous suspension>
#3      ServeCommand.run (package:webdev/src/command/serve_command.dart:104:29)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#5      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CommandRunner.run (package:args/command_runner.dart:112:14)
#9      run (package:webdev/src/webdev_command_runner.dart:19:56)
#10     main (file:///home/baloneo/software/flutter/.pub-cache/hosted/pub.flutter-io.cn/webdev-2.3.0/bin/webdev.dart:17:22)
<asynchronous suspension>
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by vsmenon** [comment]
@jakemac53 - any ideas here?

**Comment by jakemac53** [comment]
This looks like it is an issue relating to the multiple pub caches. The recommended fix is to delete the `.pub_cache` directory under your flutter sdk, at which point `flutter packages <command>` will start using your normal global pub cache.

**Comment by vsmenon** [comment]
Closing this in favor of #37481
