### ISSUE TITLE
Consider adding test coverage to the pub.dev scoring model

### ISSUE THREAD

**Issue by DrPaulT** [flutter/flutter#36934]
Hi,

I have reviewed the criteria for scoring packages on pub.dev (https://pub.dev/help#scoring) and it looks like there is no requirement for automated tests to be included in popular packages.

Would it be an idea to make some of the score depend on the coverage of automated tests included with a package?  Flutter's support for tests seems to be quite good to me, so we should encourage package maintainers to include a full test suite.

As part of the calculation of the score, this would probably include running the tests so I guess some kind of CI system would be needed that would add to the ongoing expense and complexity of pub.dev, but that could be a worthwhile gate for package maintainers as a final quality check before going live with a new release.

What do you think?

Kind regards
Paul.

**Comment by kf6gpe** [comment]
This is a good suggestion for https://github.com/dart-lang/pub-dev; I'll file an issue there and close this one.
