### ISSUE TITLE
Expose a low level API that mimicks the behavior of MultiChildRenderObjectElement for widgets

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#36937]
Currently the logic of handling a `List<Widget>` is tied to `MultiChildRenderObject` and won't work for a typical `StatefulWidget`.

The idea behind this request is to expose a function that compares two `List<Widget>` and is able to list:
- forgotten children
- new children
- moved children
- everything else

This logic would respect [Widget.canUpdate](https://api.flutter.dev/flutter/widgets/Widget/canUpdate.html) and handle the scenarios where the list transitioned from:

```dart
List<Widget> previous = [
  Foo(key: Key('foo')),
  Foo(key: Key('bar')),
]
```

to:

```dart
List<Widget> current = [
  Foo(key: Key('bar')),
  Foo(key: Key('foo')),
]
```

where the state of both widgets is preserved.

_____

This would allow custom widgets to make advanced behavior when treating a `List<Widget>`

A potential use-case is an `ImplicitlyAnimatedListView`, which would automatically handle the `AnimatedState` based on a `List<Widget>` instead of a builder.

**Comment by creativecreatorormaybenot** [comment]
Why did you close this?

**Comment by rrousselGit** [comment]
Because when I tried to make it myself, I realized that an `ImplicitlyAnimatedList` would still not be possible.

Changing:

```dart
Row(children: [
  Foo(key: Key('foo')),
  Foo(key: Key('bar')),
]);
```

to:

```dart
Row(children: [
  Foo(key: Key('bar')),
  Foo(key: Key('foo')),
]);
```

destroy the state of both `Foo` (when in React they keep their state).
We'd have to do a lot more than just such function, to have them preserve their state.
