### ISSUE TITLE
Error running Gradle :  gradlew.bat exited abnormally

### ISSUE THREAD

**Issue by rooholaminr** [flutter/flutter#36945]
hello
please help find out how to start.
I decided to use flutter for a project and I'm an absolute beginner. I tried hard for two days to find out how to fix this gradle error and read every issue here about my problem. 
everyone suggested a simple change in here :
`` C:\flutter\packages\flutter_tools\gradle ``
I did those suggestions and nothing happened so far.
## Steps to Reproduce
1 - I've installed android studio last version yesterday
2 - I've installed flutter's last version also yesterday
3 - I've run `flutter doctor` and everything is ok.
4 - emulator is up and running
5 - I opened a flutter project (as simple as that) and changed nothing.
6 - I hit the run button in android studio and I get the following error :

![image](https://user-images.githubusercontent.com/35699729/61878749-d170b580-af06-11e9-9420-55360cd2f66e.png)

![image](https://user-images.githubusercontent.com/35699729/61879058-7db29c00-af07-11e9-882b-62e49eef3898.png)

and this is the error text :
```
* Error running Gradle:
ProcessException: Process "C:\Users\rooholamin\AndroidStudioProjects\flutter_app\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:3.2.0.
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.0/gradle-3.2.0.pom
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.0/gradle-3.2.0.jar
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.2.0/gradle-3.2.0.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.2.0/gradle-3.2.0.jar
         https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/3.2.0/gradle-3.2.0.pom
         https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/3.2.0/gradle-3.2.0.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
  Command: C:\Users\rooholamin\AndroidStudioProjects\flutter_app\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.
```

**Comment by BugsBunnyBR** [comment]
https://stackoverflow.com/questions/50279792/could-not-find-com-android-tools-buildaapt23-2-0

**Comment by rooholaminr** [comment]
thanks. I did this :
I've changed the building block of the file in this address: "C:\flutter\packages\flutter_tools\gradle"
now it looks like this:

but still, I get the same error.
![image](https://user-images.githubusercontent.com/35699729/61910627-6ba61d00-af4a-11e9-8db9-c855d6951b40.png)

**Comment by dikongue** [comment]
salut a tous ...
je suis débutant dans flutter . je veux ajouter le service d'authentification de firebase a mon projet après avoir suivi les instructions sur le site de firebase et l'orsque je compile mon projet j'obtient ce type d' erreur:
* Error running Gradle:
ProcessException: Process "C:\Users\User\Desktop\authentif\android\gradlew.bat" exited abnormally:

> Configure project :app

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\User\Desktop\authentif\android\app\build.gradle' line: 26

**Comment by dikongue** [comment]
une solution sera la bien venu ..........

**Comment by BiTiSET** [comment]
@dikongue Avez-vous trouvé une solution?

**Comment by DyaryRaoof** [comment]
in my case, I had a & sign in the name of the folder that I had put in the flutter project. removing it solved the problem for me.

**Comment by dikongue** [comment]
Non j'ai été obligé de restaurer  la version précédente du programme pour
 continuer

**Comment by jonahwilliams** [comment]
This is not really a flutter-specific Gradle error. I would recommend searching for help on a community site at flutter.dev/community or on stack overlfow
