### ISSUE TITLE
when i write a GridView in a Clumn,all Clumn‘s children disappear

### ISSUE THREAD

**Issue by aboutmydreams** [flutter/flutter#36940]
![image](https://user-images.githubusercontent.com/34613360/61872573-4697b700-af16-11e9-941f-8802495bc302.png)

**Comment by BondarenkoStas** [comment]
@aboutmydreams Please provide your ```flutter doctor -v``` output.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
