### ISSUE TITLE
libMobileGestalt MobileGestalt.c:890: MGIsDeviceOneOfType is not supported on this platform.

### ISSUE THREAD

**Issue by btonyb236** [flutter/flutter#36944]

**Comment by christopherfujino** [comment]
Hi @btonyb236, can you please provide the full crash log and the output of `flutter doctor -v` and any other context that would help in reproducing and diagnosing this bug?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
