### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method currentUser on channel plugins.flutter.io/firebase_auth

### ISSUE THREAD

**Issue by rtessler** [flutter/flutter#36958]
For IOS flutter builds I am finding that calling any function in any of my introduced pubspec.yaml plugins causes a MissingPluginException. I have FirebaseAuth and Sqflite defined. I cant call any functions in those without getting an exception. This happens on both device and simulator. there are no build errors. I have done flutter clean, flutter packages get, and flutter run multiple times with no effect

pubspec.yaml

dependencies:
flutter:
sdk: flutter
firebase_auth: ^0.11.1+12
sqflite: ^1.1.6+2
path: ^1.6.2

GeneratedPluginRegistrant.m

#import "GeneratedPluginRegistrant.h"
#import <firebase_auth/FirebaseAuthPlugin.h>
#import <firebase_core/FirebaseCorePlugin.h>
#import <sqflite/SqflitePlugin.h>

@implementation GeneratedPluginRegistrant

(void)registerWithRegistry:(NSObject*)registry {
[FLTFirebaseAuthPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTFirebaseAuthPlugin"]];
[FLTFirebaseCorePlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTFirebaseCorePlugin"]];
[SqflitePlugin registerWithRegistrar:[registry registrarForPlugin:@"SqflitePlugin"]];
}
AppDelegate.m

#include "AppDelegate.h"
#include "GeneratedPluginRegistrant.h"
@import UIKit;
@import Firebase;

@implementation AppDelegate

(BOOL)application:(UIApplication *)application
didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
[FIRApp configure];
return YES;
}
I added these to a standard flutter create app to isolate the problem
I dont have these problems on android. It's as if the headers are there but no functions can be executed. Could it be related to the Podfile. I dont enough about IOS and Xcode to debug it

main.dart

import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {

      _counter++;
    });
  }

  openDatabase() async {

    var databasesPath = await getDatabasesPath();
    String path = join(databasesPath, 'demo.db');
  }

  signIn() {

    FirebaseAuth.instance.signInWithCustomToken(token: 'jdhfjdhfjshf');
  }

   Future<bool> isLoggedIn() async {

     if (FirebaseAuth.instance != null) 
      print('FirebaseAuth.instance is defined');

     FirebaseUser user = await FirebaseAuth.instance.currentUser();

     if (user != null)
      print('logged in');
    else
      print('not logged in');

     return (user != null);
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(

        title: Text(widget.title),
      ),
      body: Center(

        child: Column(

          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RaisedButton(child: Text('login'), onPressed: () { isLoggedIn(); },),
            RaisedButton(child: Text('open database'), onPressed: () { openDatabase(); },),
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

**Comment by brianmituka** [comment]
Hey, try running flutter doctor, maybe there's a license you need to accept or there's some other issue. flutter doctor will be able to tell you. Post the output here.

**Comment by rtessler** [comment]
solution: I copied the AppDelegate.m from the firebase app setup page. This works fine if there are no plugins but causes the MissingPluginException as soon as you start adding plugins. Correct code is:

#include "AppDelegate.h"
#include "GeneratedPluginRegistrant.h"
@import UIKit;
@import Firebase;

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  
    [FIRApp configure];
    [GeneratedPluginRegistrant registerWithRegistry:self];
    return [super application:application didFinishLaunchingWithOptions:launchOptions];
    //return YES;
}
