### ISSUE TITLE
Ability to block or show alert from taking a screenshot

### ISSUE THREAD

**Issue by jonataslaw** [flutter/flutter#36954]
I decided to migrate one of my messaging apps to the flutter, however, I realized that there is something completely basic, which in any development framework in the world is present but not in the flutter: ScreenShot Detection (IOS) or Screenshot Lock ( I believe this is only possible on Android).
Even the Cordova I used almost 1 decade ago had this feature, and Flutter has no way of doing that.

**Comment by KirolousNashaat** [comment]
search for plugins , if u don't find what you want then create your own plugin.. for more info [(CLICK HERE)](https://flutter.dev/docs/development/packages-and-plugins/developing-packages)

**Comment by BondarenkoStas** [comment]
@jonataslaw Did you find any workaround? Please check the comment https://github.com/flutter/flutter/issues/38517#issuecomment-521549922. I think it will make sense to rename the issue into proposal.

**Comment by jonataslaw** [comment]
> @jonataslaw Did you find any workaround? Please check the comment [#38517 (comment)](https://github.com/flutter/flutter/issues/38517#issuecomment-521549922). I think it will make sense to rename the issue into proposal.

I can block capture on android using FLAG_SECURE.
getWindow().setFlags(LayoutParams.FLAG_SECURE, LayoutParams.FLAG_SECURE);

In iOS there is no way to prevent capture, but there is a warning.
I believe than Snapchat app monitors screenshot folders, or system screenshot events. I could work on a PR for android, however, I can't do it on iOS.

**Comment by goderbauer** [comment]
This should be implemented as a (third-party) plugin.
