### ISSUE TITLE
Flutter - Counter and Navigate to a new screen

### ISSUE THREAD

**Issue by 007fred50** [flutter/flutter#36957]
I have 2 problems with the code below:

I can create a counter in flutter, but i can't Navigate to a new screen and vise versa. That means: I can't do both things at the same time.

> I need this here setState(() {}); in my RaisedButton

I got this error message:

> Another exception was thrown: Navigator operation requested with a context that does not include a Navigator.

Here is my code:

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget{
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp>{

  @override
  Widget build(BuildContext context){
    return new MaterialApp(
      title: 'Welcome',
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to view by view'),
        ),
        body: Center(
          child: Wrap(
            children: <Widget>[
              RaisedButton(
                child: Text('View 2'),
                onPressed: (){
                  setState(() {
                    Navigator.push(
                    context,
                    MaterialPageRoute(builder: (context) => SecondRoute()),
                 );
                 });
               },
             )
           ],
         ),
       ),
     )
   );
 }


class SecondRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Route"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```

Can someone help me with this?

**Comment by KirolousNashaat** [comment]
separate your widgets. move the 'home' screen to new widget (ex: HomeScreen) and just pass it to home property 'home: HomeScreen()' instead of making all your UI in one widget.
btw this questions are better asked on stackoverflow not here :)

**Comment by BondarenkoStas** [comment]
@007fred50 This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
