### ISSUE TITLE
Create flutter build framework for iOS

### ISSUE THREAD

**Issue by xster** [flutter/flutter#36968]
Extracted from https://github.com/flutter/flutter/issues/26099 for the iOS part of the work.

The end goal is for producing neatly packaged standard iOS artifacts that can be agnostic of Flutter SDKs that iOS developers can easily integrate into their existing xcode project.

This ticket is also for documentation that accompanies the tooling.

**Comment by jonahwilliams** [comment]
See also https://github.com/flutter/flutter/pull/34732

I don't think the linked approach is the one we want to take.

**Comment by jmagman** [comment]
@jonahwilliams What "linked approach"?

**Comment by xster** [comment]
I think Jonah's talking about the PR in #34732

**Comment by xster** [comment]
Rando reminder: check that the module_test_ios for this checks that a google analytics screen ping is sent when invoking `flutter build ios-framework`

**Comment by jmagman** [comment]
(This workflow for apps with plugins is blocked on https://github.com/flutter/flutter/pull/40927).

This issue will track wrapping these in a nice `flutter build` command, but here are the commands to manually do this, mostly for my own records.

Release mode for iOS (not the simulator):
```shell
$ mkdir ~/Desktop/flutter_module_frameworks/
$ cd flutter_module/
$ flutter clean
$ flutter build ios --release
$ cp -R .ios/Flutter/engine/Flutter.framework ~/Desktop/flutter_module_frameworks/
$ cp -R .ios/Flutter/App.framework ~/Desktop/flutter_module_frameworks/
```
If you are using plugins, add:
```shell
$ cd .ios/Pods/
$ xcrun xcodebuild -alltargets -sdk iphoneos -configuration Release ONLY_ACTIVE_ARCH=NO SYMROOT="${HOME}/Desktop/flutter_module_frameworks"
```
then
```shell
$ cd ~/Desktop/flutter_module_frameworks
$ mv Release-iphoneos/**/*.framework . # only if using plugins
$ rm -rf Pods.build/ Release-iphoneos/ XCBuildData/ Pods_Runner.framework
```

In your existing Xcode app you need to embed the new frameworks, link them, and make sure `LD_RUNPATH_SEARCH_PATHS=@executable_path/Frameworks`

#### Embed
1. Open the project settings > Build Phases
1. `+` New Copy Files Phase
1. Rename the new Build Phase to something like Embed Frameworks
1. Destination: Frameworks
1. Drag in all the ~/Desktop/flutter_module_frameworks frameworks.
1. Check Copy items if needed > Finish

#### Link
Add the frameworks you just copied into your project to Link Binary With Libraries (make sure it's the ones you added to your project, not the ones in your Desktop directory).
![Screen Shot 2019-09-19 at 5 11 51 PM](https://user-images.githubusercontent.com/682784/65290058-48d75580-db02-11e9-9e3d-066f27fa39ef.png)

#### LD_RUNPATH_SEARCH_PATHS
1. Project settings > Build Settings
1. Under Linking > Runpath Search Paths add `@executable_path/Frameworks`.
![Screen Shot 2019-09-19 at 5 11 24 PM](https://user-images.githubusercontent.com/682784/65290303-943e3380-db03-11e9-87b6-704d79bc345f.png)

You should now be able to call Flutter and plugin code [in your app](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#write-code-to-use-flutterviewcontroller-from-your-host-app).

#### Caveats
1. These frameworks must always be generated at the same time.  If you `flutter upgrade`, recompile, but only embed some of them, you will have binary compatibility issues.
1. This will not work with apps using plugins until https://github.com/flutter/flutter/pull/40927 is merged.

**Comment by shali3** [comment]
Thanks for making progress on this!
If you are actively working on this maybe you should move it to in-progress in the project:
https://github.com/flutter/flutter/projects/51

@xster is your PR contains most of the work to get a compiled framework for iOS, or is it just the just initial work?

**Comment by jmagman** [comment]
> @xster is your PR contains most of the work to get a compiled framework for iOS, or is it just the just initial work?

It's to get all the .frameworks and/or .xcframeworks needed to embed into another app.

You can try it now on the master channel:
```
$ flutter build ios-framework  -h
Produces a .framework directory for a Flutter module and its plugins for integration into existing, plain Xcode projects.
This can only be run on macOS hosts.

Usage: flutter build ios-framework [arguments]
-h, --help                           Print this usage information.
-t, --target=<path>                  The main entry-point file of the application, as run on the device.
                                     If the --target option is omitted, but a file name is provided on the command line, then that is used instead.
                                     (defaults to "lib/main.dart")

    --flavor                         Build a custom app flavor as defined by platform-specific build setup.
                                     Supports the use of product flavors in Android Gradle scripts, and the use of custom Xcode schemes.

    --[no-]pub                       Whether to run "flutter pub get" before executing this command.
                                     (defaults to on)

    --[no-]debug                     Whether to produce a framework for the debug build configuration. By default, all build configurations are built.
                                     (defaults to on)

    --[no-]profile                   Whether to produce a framework for the profile build configuration. By default, all build configurations are built.
                                     (defaults to on)

    --[no-]release                   Whether to produce a framework for the release build configuration. By default, all build configurations are built.
                                     (defaults to on)

    --[no-]universal                 Produce universal frameworks that include all valid architectures. This is true by default.
                                     (defaults to on)

    --[no-]xcframework               Produce xcframeworks that include all valid architectures (Xcode 11 or later).
-o, --output=<path/to/directory/>    Location to write the frameworks.
```
From a flutter module directory, you can make fat universal frameworks for Debug, Profile, and Release:
```
$ flutter build ios-framework
Running "flutter pub get" in flutterapp...                          0.4s
Building framework for com.m.flutterapp in debug mode...
 ├─Populating Flutter.framework...                                 221ms
 ├─Add placeholder App.framework for debug...                      195ms
 ├─Assembling Flutter resources for App.framework...                6.7s
Running pod install...                                              1.9s
 ├─Building plugins...                                              5.6s
 └─Moving to build/ios/framework/Debug                              0.0s
Building framework for com.m.flutterapp in profile mode...
 ├─Populating Flutter.framework...                                 144ms
 ├─Building Dart AOT for App.framework...                          22.5s
 ├─Assembling Flutter resources for App.framework...                0.1s
 ├─Building plugins...                                              5.5s
 └─Moving to build/ios/framework/Profile                            0.1s
Building framework for com.m.flutterapp in release mode...
 ├─Populating Flutter.framework...                               1,056ms
 ├─Building Dart AOT for App.framework...                          15.5s
 ├─Assembling Flutter resources for App.framework...                0.1s
 ├─Building plugins...                                              5.8s
 └─Moving to build/ios/framework/Release                            0.0s
Frameworks written to /Users/m/Projects/test_add2app/flutterapp/build/ios/framework.
$ ls -la /Users/m/Projects/test_add2app/flutterapp/build/ios/framework/Debug 
total 0
drwxr-xr-x  7 m  primarygroup  224 Nov  8 17:18 .
drwxr-xr-x  5 m  primarygroup  160 Nov  8 17:19 ..
drwxr-xr-x  5 m  primarygroup  160 Nov  8 17:18 App.framework
drwxr-xr-x  7 m  primarygroup  224 Nov  8 17:18 Flutter.framework
drwxr-xr-x  6 m  primarygroup  192 Nov  8 17:18 FlutterPluginRegistrant.framework
drwxr-xr-x  6 m  primarygroup  192 Nov  8 17:18 device_info.framework
drwxr-xr-x  6 m  primarygroup  192 Nov  8 17:18 path_provider.framework
```
or Debug, Profile, and Release xcframeworks on Xcode 11+
```
$ flutter build ios-framework --no-universal --xcframework
...
$ ls -la  /Users/m/Projects/test_add2app/flutterapp/build/ios/framework/Debug
total 0
drwxr-xr-x  7 m  primarygroup  224 Nov  8 17:16 .
drwxr-xr-x  5 m  primarygroup  160 Nov  8 17:16 ..
drwxr-xr-x  5 m  primarygroup  160 Nov  8 17:16 App.framework
drwxr-xr-x  5 m  primarygroup  160 Nov  8 17:16 Flutter.xcframework
drwxr-xr-x  5 m  primarygroup  160 Nov  8 17:16 FlutterPluginRegistrant.xcframework
drwxr-xr-x  5 m  primarygroup  160 Nov  8 17:16 device_info.xcframework
drwxr-xr-x  5 m  primarygroup  160 Nov  8 17:16 path_provider.xcframework

```

**Comment by shali3** [comment]
🤩 Amazing!
Will try it soon :)
