### ISSUE TITLE
Wake up a closed application

### ISSUE THREAD

**Issue by saxcws** [flutter/flutter#36973]
Hi everyone,

I'm working in a application that needs to wake up when its closed, similar when we receive a call on whatsapp. Cause I have to notify my customers that they have a new order in my app. Not just notify, but also shake theirs phones or play a sound because they work in a noisy environment. Im already using firebase notifications, but it's not enough. I cant just implement a voice call system cause apple wont let my app go on. But, Im ok if there is no solution for ios.
I just need a solution, or something like that, does anybody knows how to solve this problem?

**Comment by BondarenkoStas** [comment]
@saxcws This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
