### ISSUE TITLE
There is no local storage option to select files from phone

### ISSUE THREAD

**Issue by dmkraus** [flutter/flutter#36977]
A new feature could be to play local videos from the file system like VideoPlayerController.local_storage(
     filePath
    );

**Comment by BugsBunnyBR** [comment]
I think you can use `VideoPlayerController.file`, but you need to have permissions to read that file.
https://github.com/flutter/plugins/blob/master/packages/video_player/lib/video_player.dart#L167

**Comment by BondarenkoStas** [comment]
@dmkraus Please report, did using `VideoPlayerController.file` worked for you? Or would like to propose some extra features?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
