### ISSUE TITLE
Text Edit Loop on iOS

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#36971]
Internal: b/138398009

Much like its predecessors (https://github.com/flutter/flutter/issues/12782, https://github.com/flutter/flutter/issues/12347, https://github.com/flutter/flutter/issues/13961), this issue manifests itself in a similar way.

Here's a repro that uses a slow text formatter.

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

// Identity formatter, with some slowness.
class SimpleTextFormatter extends TextInputFormatter {
  SimpleTextFormatter();

  static final instance = SimpleTextFormatter();

  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    var result =
        TextEditingValue(text: newValue.text, selection: newValue.selection);

    // Some slow calculation!
    int sum = 0;
    for (int i = 0; i < 100000000; ++i) sum += i;
    if (sum % 2 == 1) return null;

    // Note: Just returning newValue does *NOT* trigger the problem
    return result;
  }
}

void main() => runApp(TextFieldTest());

class TextFieldTest extends StatefulWidget {
  @override
  _TextFieldTestState createState() => _TextFieldTestState();
}

class _TextFieldTestState extends State<TextFieldTest> {
  final _controller = TextEditingController();
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Text Editing Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: Scaffold(
          appBar: AppBar(
            title: Text('Text Editing Demo'),
          ),
          body: SizedBox(
              width: 100,
              child: TextField(
                controller: _controller,
                inputFormatters: [SimpleTextFormatter.instance],
              )),
        ));
  }
}
```

**Comment by mehmetf** [comment]
Filer of the bug asks:

> 
> Should these constants be -1 instead of 0?
> 
> https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L594-L595
>  
> see: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/text_input.dart#L509-L510

**Comment by mehmetf** [comment]
@jonahwilliams who would be the best person to triage this? (I pinged you because you seem to have fixed the previous issue that is very similar).

**Comment by jonahwilliams** [comment]
Probably @goderbauer

**Comment by goderbauer** [comment]
I am unable to reproduce anything buggy on neither the simulator nor a real device. I can type characters into the textfield and delete them without problems (well, the app hangs after every character, but that seems expected given the "slow computation" in the input formatter). Based on the linked github issues I expected to see some flickering in the content of the text field when deleting a character, but I am not seeing any of that.

Any more instructions on how to reproduce this?

**Comment by goderbauer** [comment]
Ah, the internal issue contains actual instructions describing how to reproduce this:

> Launch app.
> Press 1,2,3,4 quickly together.

Unlike previous issues this one is not triggered by deleting characters. It's typing them in quickly...

**Comment by goderbauer** [comment]
Not for debugging: reducing the 100,000,000 to 10,000,000 makes the problem more visible on an iPhone 8.

**Comment by mehmetf** [comment]
From what I hear, this is also reproducible on the Gallery app with no changes to formatters (if you type fast enough).

**Comment by goderbauer** [comment]
To answer the other question:

> Should these constants be -1 instead of 0?

Yes, those should be -1. That's what the framework and the android engine use to indicate "no composition range". Only iOS uses 0, which should be unified. However, if I change that text input breaks completely on iOS (entered text doesn't appear at all anymore). I am debugging that right now.

**Comment by goderbauer** [comment]
I had an embarrassing typo in my change, setting the constants to -1 does fix the problem as expected. PR posted at https://github.com/flutter/engine/pull/10381.

This fixes the infinite loop. There is still a separate (unrelated) problem that not all keypresses will end up in the text field if you type fast and have a really slow TextInputFormatter. I filled https://github.com/flutter/flutter/issues/37390 for that one.

**Comment by Vivannaboa** [comment]
I believe I have the same problem here, in some situations TextInputFormatter goes looping. I tested in the example https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/text_form_field_demo.dart and the same problem happens.

![problema 1](https://user-images.githubusercontent.com/11863525/71983132-db604980-3204-11ea-8fb5-e4c56d017003.gif)
