### ISSUE TITLE
cloud_firestore 'where' method has no 'isNotEqualTo' operator

### ISSUE THREAD

**Issue by TPLinux** [flutter/flutter#36980]
I think you should add , "isNotEqualTo" argument to "where" method in "cloud_firestore" package , it's very important argument , for example if I want to get all users having 'desc' != '', i can not , because we have not "isNotEqualTo" operator

I checked it out , its not exists. I hope you add it soon.
# Available argument

- isEqualTo
- isLessThan
- isLessThanOrEqualTo
- isGreaterThan
- isGreaterThanOrEqualTo
- arrayContains
- isNull

# **But there is NO "isNotEqualTo"**

_I tried to add it manually by editing some lines in package file , but it fail._

I hope u add it soon , its very important, and ty !

**Comment by 2n-1** [comment]
It's not a flutter issue. Cloud Firestore does not support inequality checks for its database architecture itself. As per documentation (https://firebase.google.com/docs/firestore/query-data/queries) where method allows only <, <=, ==, =>, > comparison operations.

One possible work around would be:
1. Query with lessThan comparison
2. Query with moreThan comparison
3. Merge the results from point 1 and 2 locally

**Comment by TPLinux** [comment]
> It's not a flutter issue. Cloud Firestore does not support inequality checks for its database architecture itself. As per documentation (https://firebase.google.com/docs/firestore/query-data/queries) where method allows only <, <=, ==, =>, > comparison operations.
> 
> One possible work around would be:
> 
> 1. Query with lessThan comparison
> 2. Query with moreThan comparison
> 3. Merge the results from point 1 and 2 locally

!= is called "isNotEqualTo" , in cloud_firestore u can not use 3 arguments 

you just allowed to use 2 arguments, and on is optional 

`Firestore.instance.collection('users').where('username', '!=', 'useritself')`

this code above will throw an error 

you should use it like this 

`Firestore.instance.collection('users').where('username', isEqualTo: 'useritself')`

but there is no 'isNotEqualTo' .


i do not think that i can use lessThan and moreThan for strings , and if i will , it will be long solution , 

looping will be easier . 

thank for your replay but issue still exists

**Comment by collinjackson** [comment]
I would be happy to review pull requests for this.

**Comment by 2n-1** [comment]
The point is Cloud Firestore database (_not the Flutter plugin_) **does not** support inequality checks.

**Comment by collinjackson** [comment]
Thanks @2n-1.

I'm closing this issue since I don't think there's a way for the plugin to support this functionality.

**Comment by kroikie** [comment]
@TPLinux

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1211. Any further collaboration will be done there.
