### ISSUE TITLE
on IOS device or simulator, Calling any function in firebase_auth causes MissingPluginException. Ive tried flutter clean, flutter packages get, flutter run but the problem persists. Im experiencing the same problem in other plugins: location and sqflite. Android works fine. No plugins seem to work for me on IOS.

### ISSUE THREAD

**Issue by rtessler** [flutter/flutter#36995]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by brianmituka** [comment]
This could be an androidX issue check what versions of the packages you are using if it's the latest versions of those packages, you might need to enable androidX in your project or use earlier versions of those packages

**Comment by brianmituka** [comment]
Similar to https://github.com/flutter/flutter/issues/36958

**Comment by jmagman** [comment]
@rtessler How are you running on the device or simulator?  `flutter run` or from Xcode?
If it's from Xcode, are you running from Runner.xcworkspace?
