### ISSUE TITLE
The rebound at the bottom is incorrect when using NestedScrollView

### ISSUE THREAD

**Issue by cunc** [flutter/flutter#36991]
![Record_2019-07-26-11-13-01](https://user-images.githubusercontent.com/43318850/61925674-ee0cfc00-af9f-11e9-95fa-508518242086.gif)

As above, after scrolling and holding for a while, the last one of the list shoule be 'Item 29' but it spring back to 'Item 28'.
How to solve this?
The code is as same as this [example](https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html).

**Comment by TahaTesser** [comment]
Hi @cunc 
Here is the code sample [Dartpad](https://dartpad.dev/4af804236d66a2cc4618a988bd79d549)
Does this issue still exist fro you?
Thank you

**Comment by VladyslavBondarenko** [comment]
Hi @cunc 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/10318,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
