### ISSUE TITLE
ReorderableListView can you add more functionality

### ISSUE THREAD

**Issue by atul161** [flutter/flutter#36994]
**ReorderableListView**
In Current ReorderableListView widget there are only 4 to 5 property. I think flutter developer
must need these property 
1)DragStarted
2)DragEnded 

so that we  can perform several opertaions on these callbacks.

[✓] Flutter (Channel dev, v1.8.1, on Linux, locale en_IN)
    • Flutter version 1.8.1 at /home/atul/flutterpermanent/flutter
    • Framework revision d3eee57c0b (3 weeks ago), 2019-07-08 11:04:24 -0700
    • Engine revision 3c51a7bfff
    • Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/atul/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /home/atul/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/atul/android-studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /home/atul/idea-IU-191.7479.19
    • Flutter plugin version 36.0.4
    • Dart plugin version 191.7830

[✓] Connected device (1 available)
    • Redmi Note 5 Pro • 1b5fd6c6 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by carmenkerim12** [comment]
I think it would be beneficial if there was more control such as disabling and enabling reordering!

**Comment by JulianBissekkou** [comment]
Besides that we also need an API to customize the look of the item while its beeing dragged.

**Comment by dzliergaard** [comment]
Came to ask for this. I'll add on to this instead.

## Use case

I have a ReorderableListView in which the elements are ExpansionTiles. When one is expanded and I long-press on something within it (that doesn't itself have a LongPress GestureDetector), the behavior of the ExpansionTile within the ReorderableListView jumps around and overflows.

## Proposal

Please add an OnDragStart or similar callback to ReorderableListView so that its elements can respond appropriately to being reordered.

**Comment by Piinks** [comment]
ReorderableList now has callbacks for onReorder, onReorderStart and onReorderEnd from #96049
