### ISSUE TITLE
OverlayRoute.didPop shouldn't remove the overlays

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#370]
Or at least, we should provide a way for that to be delayed. Right now, didPop() on _BottomSheetRoute delays its super.didPop() call, which is a contract violation.

**Comment by Hixie** [comment]
TransitionRoute does this too, but even worse (didPop doesn't call super.didPop, then a completely unrelated _handleStatusChanged method calls super.didPop).

**Comment by HansMuller** [comment]
I found the didPop() linkages in TransitionRoute difficult to follow and I definitely didn't improve matters in _BottomSheetRoute().

Some of the tension comes from tests that want to call Navigator.pop() and then verify that their route is indeed gone. Similarly, the tests want to verify that showFoo().then( <verify> ) has removed whatever was being shown.
