### ISSUE TITLE
Can't get both to work at same time

### ISSUE THREAD

**Issue by 007fred50** [flutter/flutter#37005]
Hello,

I can make a Counter app.
I can make a Navigate to a new screen.

But i can't make it at same time :(

Can some one help me with it ?

Thanks :)

**Comment by BondarenkoStas** [comment]
@007fred50 This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
