### ISSUE TITLE
how can i get a flutter widget on native viewControllers, and add the widgte to the native UIs

### ISSUE THREAD

**Issue by nikisu** [flutter/flutter#37001]
## Use case

flutter -> native case

in the flutter and native(iOS and Android) hybrid development，how can i get a flutter widget in 
the native(if on iOS platform) viewController not flutterViewController ? 
In addition, can i use native methods like someView.addSubViews to add a flutter widget to the native views in viewController not in FlutterViewController ?  or can we call the addSubViews method to add a designated widget to the native views in the viewController ?

if we can do these, the business scene in flutter native hybrid development will be more than now!

**Comment by goderbauer** [comment]
This question seems more suitable for stackoverflow.
