### ISSUE TITLE
[cloud_firestore] Add MetadataChanges to documentReference.snapshot()

### ISSUE THREAD

**Issue by basketball-ico** [flutter/flutter#37007]
I want to use MetadataChanges like in [Android](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/DocumentReference)

**Comment by collinjackson** [comment]
I believe that this is a duplicate of flutter/flutter#16432 and it was fixed in https://github.com/flutter/plugins/pull/1918. Please let me know if I'm mistaken

**Comment by kroikie** [comment]
@basketball-ico

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1210. Any further collaboration will be done there.
