### ISSUE TITLE
EventChannel cannot receive message from android platform

### ISSUE THREAD

**Issue by YWD** [flutter/flutter#37004]
I'v upgrade flutter and find a serious bug. the EventChannel cannot work on android platform.
below are related code:
```dart
const eventChannel = EventChannel("event_stream");
eventChannel.receiveBroadcastStream().listen(_onResult);
_onResult(dynamic obj) {
    print('obj:$obj');
    String key = obj['key'];
    String url = obj['picUrl'];
    print('result:$key,$url');
}
android:
EventChannel.StreamHandler streamHandler = new EventChannel.StreamHandler() {
            @Override
            public void onListen(Object o, EventChannel.EventSink eventSink) {
                Log.d("-------------->  ", "event channel on listen");
                MainActivity.this.eventSink = eventSink;
            }

            @Override
            public void onCancel(Object o) {
                Log.d("-------------->  ", "event channel on cancel");
            }
        };

Map<String, Object> stringStringMap = new HashMap<>();
 LogUtil.d("eventSink:" + "index");
 stringStringMap.put("index", "index");
 eventSink.success(stringStringMap);
```
logcat:
```
D/-------------->  (10368): event channel on listen
D/LogUtil (10368): eventSink:https://**clean-img.oss-ap-northeast-1.aliyuncs.com/**/P_20190726_174232_cmp.jpg
```
but I can't receive message in dart _onResult method

**Comment by YWD** [comment]
here are flutter doctor print
yangwendongdeMacBook-Pro:ocs_crowd ywd$ flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.4 at /Users/ywd/FlutterProj/flutter
    • Framework revision 20e59316b8 (7 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ywd/Library/Android/sdk
    • Android NDK at /Users/ywd/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/ywd/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Redmi 6 Pro • 57a1ca789905 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.

**Comment by YWD** [comment]
how can I downgrade flutter version. I use 'flutter version v1.2.1' or in flutter directory 'git checkout v1.2.1'  the operation will loss channel info 
![image](https://user-images.githubusercontent.com/8605395/61947354-8ffc0b00-afd7-11e9-9535-517d13ad3652.png)
and the app cannot run with this error
![image](https://user-images.githubusercontent.com/8605395/61947376-9c806380-afd7-11e9-8bfc-04678e2ba8e7.png)

**Comment by YWD** [comment]
I solved this problem temporary by delete 'flutter/bin/cache' directory

**Comment by YWD** [comment]
I solved downgrade problem temporary by delete 'flutter/bin/cache' directory

**Comment by BondarenkoStas** [comment]
@YWD Do you experience such issue with the current stable version? I mean without the workaround with deleting the cache directory.

**Comment by YWD** [comment]
The mortal problem is that on android platform I can't receive message from EventChannel. I'v upgrade flutter to v1.9.1+hotfix.2,  this serious problem still not solve. please solve this problem. otherwise, I still need to downgrade flutter version!

Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (3 weeks ago) • 2019-09-06 18:39:49 -0700
Engine • revision b863200c37
Tools • Dart 2.4.0

Running "flutter pub upgrade" in ocs_operator...                    3.3s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by sujithTSR** [comment]
I am facing the same issue. 
I upgraded my flutter project from 1.5.4 to 1.9.6 hotfix.6 
sending an intent from Android activity and was now not able to receive anything from the stream.
This stuff was working fine with  1.5.4 though.

**Comment by sujithTSR** [comment]
I've tried integrating an existing android project to flutter. I was able to communicate and trigger flutter from the native android project. 
I was even able to invoke methods from flutter to my native existing project and transfer data. 
Now with the event channel, when I try to send data from the native project to flutter, Flutter is not able to listen to event channel. 

"EventChannel cannot receive a message from the android platform"
Any idea why this is happening?

**Comment by YWD** [comment]
I'm using flutter version 1.2.1🙂

**Comment by blackmenthor** [comment]
I don't know about you guys, but I've come across a similar problem and its happening because there's an error that says

```
Methods marked with @UiThread must be executed on the main thread.
```

but it's shadowed and I had to spend hours searching for this issue. and I can solve it using Android's `Handler`.
Maybe it could help someone.

**Comment by iapicca** [comment]
Hi @YWD 
are you still experiencing this issue with the latest stable version of flutter?
If so could you please provide your updated `flutter doctor -v` 
and your `flutter run --verbose` and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by YWD** [comment]
I found this problem only happens when I open system camera use Intent.
if I don't open camera event channel can receive data.
here's one log I found in log cat may help, It seems something break？
“W/CAM_ScenarioTrackUtil: track SwitchCameraTime event end cancel, due to scenario has not started!”

flutter doctor
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.41.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 3 categories.

**Comment by matpag** [comment]
> I don't know about you guys, but I've come across a similar problem and its happening because there's an error that says
> 
> ```
> Methods marked with @UiThread must be executed on the main thread.
> ```
> 
> but it's shadowed and I had to spend hours searching for this issue. and I can solve it using Android's `Handler`.
> Maybe it could help someone.

This comment saved me. 
I had the same problem in my plugin and fixed it wrapping the `eventSink.success(...)` in a `activity.runOnMainThread{ ... }`
