### ISSUE TITLE
Cannot run after upgrade 

### ISSUE THREAD

**Issue by MuthuSubramaniam** [flutter/flutter#37000]
Cannot run the project after upgrage my flutter! getting below error:(

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.8.1, on Mac OS X 10.14.5 18F132, locale en-MY)
⣻ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -2

**Comment by jmagman** [comment]
Does it work to unpair and re-pair the device?
Xcode > Window > Devices and Simulators > Ctrl-click device > Unpair Device
To re-pair:
Unplug and re-plug in device.  On device, hit the Trust button.

**Comment by MuthuSubramaniam** [comment]
Tried lot of stuffs, meaning to say close and opened not working, Invalidate and caches/Restarted not working, then finally I just downgraded my update then it seems fine now! Thanks @jmagman  for your reply!
