### ISSUE TITLE
showDialogue should allow changing barrier color

### ISSUE THREAD

**Issue by fralways** [flutter/flutter#37008]
I would like to be able to change barrier color in showDialog. I often use showDialog to display fullscreen loading animation and changing background color is necessary.

```
Flutter (Channel beta, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E226, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by HansMuller** [comment]
The [showDialog function](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/dialog.dart#L691) is just a simple cover for [showGeneralDialog](https://api.flutter.dev/flutter/widgets/showGeneralDialog.html) which does allow setting the barrier color.  Maybe write an app-specific showDialog function that adds the barrierColor parameter.

**Comment by BondarenkoStas** [comment]
Closing in favour to https://github.com/flutter/flutter/issues/43718
