### ISSUE TITLE
Unable to locate Android SDK.

### ISSUE THREAD

**Issue by bernardohrl** [flutter/flutter#37014]
So, I'm using Windows and Flutter v1.7.8+hotfix.4.

I followed the [get-started guide](https://flutter.dev/docs/get-started/install/windows) and installed Android Studio. But, I ran  

```
flutter doctor run
```
 and got

![sdk0](https://user-images.githubusercontent.com/20937488/61963806-d8e59c80-afa2-11e9-9826-07139e83dc9f.PNG)

so I added the environment variable **ANDOID_HOME** 
 as **C:\Users\04860826108\AppData\Local\Android\Sdk**

![sdk1](https://user-images.githubusercontent.com/20937488/61963976-38dc4300-afa3-11e9-82e5-43fcd36ef6f5.PNG)

So now i got this error:

![sdk2](https://user-images.githubusercontent.com/20937488/61964012-4bef1300-afa3-11e9-9237-dc0a6a96b60b.PNG)

But the path is correct, as it can be seen on Adroid Studio:

![sdk3](https://user-images.githubusercontent.com/20937488/61964124-8fe21800-afa3-11e9-8056-bcded12632b4.PNG)

So, I don't know what to do now.

**Comment by sumanabhi** [comment]
Hi,

are you able to find any fix for the issue?

I am also facing the same one

**Comment by bernardohrl** [comment]
Nothing yet...

**Comment by bernardohrl** [comment]
@sumanabhi I just fixed this problem following [this issue](https://github.com/flutter/flutter/issues/19805).

Just adding ```%ANDROID_HOME%\tools``` and ```%ANDROID_HOME%\platform-tool```s to the PATH and running
```
flutter doctor --android-licenses
```
