### ISSUE TITLE
Update release steps on Wiki to include post-release responsibilities.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#37016]
Need:
  * Crash monitoring instructions.
  * Hotfix criteria & updating process.

**Comment by darshankawar** [comment]
Below are the related topics I found in flutter wiki:

https://github.com/flutter/flutter/wiki/Hotfix-Documentation-Best-Practices
https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel
https://github.com/flutter/flutter/wiki/Crashes

I am going ahead and optimistically close this as resolved. If anybody disagrees, please write in comments and I'll reopen it.
