### ISSUE TITLE
WebView_Flutter: How can I get headers from response after loading a page?

### ISSUE THREAD

**Issue by joelbrostrom** [flutter/flutter#37012]
Is there a way to get headers from a http response?
I am supposed to send extra data if the server passes `{"x-details": "high"}` in the headers.

**Comment by BondarenkoStas** [comment]
@joelbrostrom This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.

**Comment by joelbrostrom** [comment]
Your right.
Don't know what I was thinking.

**Comment by thenixoncompany** [comment]
@BondarenkoStas this question is right. There isn't anything in the documentation for that and with your answer you don't level up this ISSUE.
