### ISSUE TITLE
Use mdns for Fuchsia device discovery

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#37022]
`dev_finder` is not sufficiently portable, causing running and attaching from a MacOS host not to work, and may have other issues (FL-283). The tool should use mdns as with iOS devices instead.

**Comment by jonahwilliams** [comment]
From looking at the issue, the reason that dev_finder does not support macOS is missing network functionality required for the reverse lookup. That same functionality is missing in Dart and the Dart mDNS library.

**Comment by zanderso** [comment]
@jonahwilliams Could you give some more detail on this or link to a Dart SDK or Fuchsia issue? Thanks!

**Comment by jonahwilliams** [comment]
If i remember the details correctly, I can identify the device but not which network interface was used to discover the device. This is prevented me from spawning the package server at the correct address.

**Comment by jonahwilliams** [comment]
I could have also just been missing something, or maybe more features needed to be added to the mDNS package

**Comment by jonahwilliams** [comment]
We're not going to do this.
