### ISSUE TITLE
Update the In App Purchase plugin to use Play Billing Library 2

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#37021]
The IAP plugin currently uses PBL 1.2.

This library is being deprecated and replaced by PBL 2.0.

We've been getting reports of developers getting the following warning when submitting their apps to the play store:

> We’ve detected that your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available. Update to version 3 before this date.

Edited(cyanglaz):
The design doc for this migration can be found here:
https://docs.google.com/document/d/1XM16UsLE_aPWoZnheE9waO06mhxLkkWjpPf9jtI1AdY/edit?usp=sharing

**Comment by amirh** [comment]
Update: after checking with the play team, PBL isn't the dependency that's triggering this warning and is not shutting down on 12/2019. Changed the milestone to goals.

**Comment by cyanglaz** [comment]
2.0 now asks users to call a confirm purchase API after a purchase is made. Which matches the iOS API better. We will update the dart api `completePurchase` work on both iOS and Android instead of only iOS.

**Comment by cyanglaz** [comment]
Done in https://github.com/flutter/plugins/pull/2287

**Comment by abu0435** [comment]
How to migrate(in_app_purchares) to play billing library in flutter. Plugin lastest version doesn't include it. How to upgrade manually.
