### ISSUE TITLE
Having a focussed text field that is populated with some text causes the app to misbehave

### ISSUE THREAD

**Issue by chingjun** [flutter/flutter#37032]
Forwarded from internal bug: b/138449750

*In our app, this problem actually causes an exception*

I've reduced this to a tiny test case which behaves unexpectedly, which if resolved, I believe will also solve the problems I'm seeing.

Video of the problem: (please check the internal bug for video)

What you're seeing: I launch the app, the text field has autofocus set and populated with 'a'. Clicking on the next button doesn't work, instead it shows the popup menu. Clicking to dismiss that, then clicking on the button works as expected.

If the text field is empty, or the text field does NOT have focus, then the next button can be clicked. But if both conditions are true, the button doesn't work.

This seems to have been introduced with yesterday's flutter roll.

I theorise this file is directly involved with this:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/text_selection.dart

Note: autofocus and initial text isn't required, it just makes quicker to get to the problem. If autofocus isn't set, and initial text isn't specified, the problem occurs as soon as you click on the text fiend and enter one character.

Repro test case:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TestPage(),
    );
  }
}

class TestPage extends StatefulWidget {
  State createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  final controller = TextEditingController(text: 'a');

  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(children: [
        TextField(autofocus: true, controller: controller),
        RaisedButton(
            child: Text('Next'),
            onPressed: () => Navigator.of(context).push(
                  MaterialPageRoute(
                    builder: (_) => NextPage(),
                  ),
                )),
      ]),
    );
  }
}

class NextPage extends StatelessWidget {
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
    );
  }
}
```

**Comment by LongCatIsLooong** [comment]
I couldn't reproduce it with the repro code on Android. Let me try on iOS.

**Comment by shihaohong** [comment]
It does not happen on an Android simulator, but it does occur on an iOS simulator for me

**Comment by LongCatIsLooong** [comment]
https://github.com/flutter/flutter/pull/36757 fixes this. But it doesn't have a test.
