### ISSUE TITLE
Symbols tool failed error on xcode upload to itunes connect.

### ISSUE THREAD

**Issue by jodymac** [flutter/flutter#37047]
[✓] Flutter (Channel master, v1.8.2-pre.189, on Mac OS X 10.13.6 17G3025, locale
    en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.1)
[✓] Connected device (4 available)

• No issues found!

This can be fixed downgrading to a lower version.  I backed down to v1.7.8+hotfix.4 and the uploads worked again.  Did not test against any in between versions.

**Comment by jmagman** [comment]
What was the error? Can you include repro steps?

**Comment by jodymac** [comment]
To reproduce,

in mac terminal in your flutter project, type ‘flutter build ios —release
Open the project in Xcode.
Archive the app for submission to iTunes connect.
Once the app is archived, you can press distribute or validate and once it gets to processing frameworks it will fail with the message ‘Symbols tool failed’.
You can uncheck 'Unchecking Include app symbols allows it to upload’ when that option appears and it will not fail.  But the app would not load properly when downloaded from test flight.  It would hang after the splash screen which was most likely the Xcode launch screen.
Cleaning the build before archiving does not make a difference.

**Comment by calvinmuller** [comment]
Same issue here
```
Build failed :|
Unable to export archive:
2019-07-30 07:50:30.674 xcodebuild[4137:23872] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/r7/d9twdq011sb8d3q1p8f39cdr0000gn/T/Runner_2019-07-30_07-50-30.673.xcdistributionlogs'.
error: exportArchive: Symbols tool failed

Error Domain=IDEFoundationErrorDomain Code=1 "Symbols tool failed" UserInfo={NSLocalizedDescription=Symbols tool failed}

** EXPORT FAILED **
```

**Comment by jmagman** [comment]
@jodymac Can I get flutter doctor -v?  I want to know what commit you're on.  May be related to https://github.com/flutter/flutter/pull/37217 but I can't tell if you're on a commit than includes https://github.com/flutter/flutter/pull/36471.

**Comment by jodymac** [comment]
This is all I have that is listed above.  [✓] Flutter (Channel master, v1.8.2-pre.189, on Mac OS X 10.13.6 17G3025, locale
en-US)

I’ve backed off to 1.7.8 hot fix 4 so I can upload and test off apple testflight immediately.

**Comment by calvinmuller** [comment]
```
[✓] Flutter (Channel master, v1.8.2-pre.229, on Mac OS X 10.14.4 18E226, locale en-ZA)
    • Flutter version 1.8.2-pre.229 at /Users/calvinmuller/iStreet/Mobile/flutter
    • Framework revision 9357e70dfd (16 hours ago), 2019-07-29 22:11:51 -0700
    • Engine revision 09f8bffb96
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 0ca1582afd)
```

**Comment by jmagman** [comment]
@calvinmuller Thank you!  You are on Framework revision 9357e70dfd which does include https://github.com/flutter/flutter/pull/36471.  
@dnfield @xster  Do you know if this should be resolved with https://github.com/flutter/flutter/pull/37217?  I can't tell from https://github.com/flutter/flutter/pull/36471#discussion_r308521828 if the symptoms would be the same.

Let me try to repro.

**Comment by xster** [comment]
It's plausible that #37217 could solve but @goderbauer could perhaps confirm.

#36471 could have retriggered the same issues that https://github.com/flutter/flutter/pull/22540 previously fixed. But since https://github.com/flutter/flutter/pull/22540 had no bug attached, it's unclear what the failure symptoms were. @goderbauer: was the OP's description of the issue the same as what you fixed with https://github.com/flutter/flutter/pull/22540?

**Comment by goderbauer** [comment]
Yeah, prior to #22540 xcode would show the exact same failure message. So, I would suspect that #37217 will fix this issue (there is a little uncertainty since "Symbols tool failed" is xcode's catch-all error for any problem it had when invoking the symbols tool...).

**Comment by shenwilly** [comment]
Had this issue on v1.8.2-pre.181. `flutter upgrade` to v1.8.2-pre.242 and 'flutter clean' fixes mine.

**Comment by calvinmuller** [comment]
I'm on master and the highest I can go is ```Flutter 1.8.2-pre.229``` so not sure how you got to pre.242

**Comment by calvinmuller** [comment]
Thanks @shenwilly, when I build again on CodeMagic I will switch it back to master and give it a try. btw switching to dev allowed to build and publish.

**Comment by jodymac** [comment]
Confirmed.  [✓] Flutter (Channel master, v1.8.2-pre.242, on Mac OS X 10.13.6 17G3025, locale
    en-US)

This fixes the error.  I was able to upload to iTunes connect and run the app successfully from test flight.

**Comment by dnfield** [comment]
Hooray!  Sorry about that!
