### ISSUE TITLE
Add Flutter manifest info to flutter doctor when run from a flutter app directory

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#37041]
## Use case
There are details about an app that would be helpful for triaging certain classes of issues.

## Proposal
When people create issues they are instructed to paste the output of flutter doctor -v. When it is run from a directory containing a pubspec.yaml, include the Flutter manifest details:
- App name
- Build name
- Build number
- Uses material design
- Uses Anfroid X
- is module
- is plugin
- Android package
- iOS bundle identifier
- Supported platforms (if plugin)
etc.

**Comment by jmagman** [comment]
Related to https://github.com/flutter/flutter/issues/36496.

**Comment by jonahwilliams** [comment]
I think we've backed off the idea of making doctor contextual. One important concern is that the working directory will often not be the project root when it is run via the daemon (vscode, intellij, android studio).

cc @csells @christopherfujino

**Comment by jmagman** [comment]
Maybe something explicit?
```
flutter doctor -v --project
```
which just works if you're in the root, or
```
flutter doctor -v --project path/to/app
```
And update the "I have a problem with my Flutter application > Logs" template with instructions. Or the screener can ask for the originator to run it, if they need additional info to triage.

That output would have been helpful highlighting pubspec parsing issue like https://github.com/flutter/flutter/issues/34477.

**Comment by christopherfujino** [comment]
I do like the idea of either making an explicit flag, or perhaps even a new command altogether (though not sure what to call it).

**Comment by jonahwilliams** [comment]
I don't want to add anymore flags to the doctor command, because it's not obvious how we would surface that in the context of an IDE. We've talked about a `flutter check` command, or attaching more diagnostics to `flutter analyze`

**Comment by jmagman** [comment]
Duplicate of https://github.com/flutter/flutter/issues/2885.
