### ISSUE TITLE
Ability to create Slider without margins on both sides

### ISSUE THREAD

**Issue by Saifallak** [flutter/flutter#37057]
## Use case

it's just a small edit in Slider class to add new parameter that indicates how much margins/padding should be on all sides instead of that fixed 8/16 pixel (idk how much is it).

## Proposal

i want to create a widget like this:
![image](https://user-images.githubusercontent.com/6053156/61988472-13424e80-b022-11e9-9d57-68e9db7a5455.png)
but as what you can see , all what i can do is this:
![image](https://user-images.githubusercontent.com/6053156/61988483-31a84a00-b022-11e9-8d63-51dc44532115.png)
with that all padding/margins on top and both sides , i can't do it;
i have searched alot for plugins and other stuff.
but since Slider is part of flutter itself. i think it should add that ability for the ease of building layouts. thanks

**Comment by HansMuller** [comment]
CC @clocksmith

**Comment by clocksmith** [comment]
This is because the track makes room for the thumb and overlay. These centers are centered on the track, so when they are all the way left or all the way right, they go off the track. You can override the track shape:

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double _value = 0;

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      body: Center(
        child: SliderTheme(
          data: SliderThemeData(
            trackShape: CustomTrackShape(),
          ),
          child: Slider(
            value: _value,
            onChanged: (double value) {
              setState(() {
                _value = value;
              });
            },
          ),
        ),
      ),
    );
  }
}

class CustomTrackShape extends RoundedRectSliderTrackShape {
  Rect getPreferredRect({
    @required RenderBox parentBox,
    Offset offset = Offset.zero,
    @required SliderThemeData sliderTheme,
    bool isEnabled = false,
    bool isDiscrete = false,
  }) {
    final double trackHeight = sliderTheme.trackHeight;
    final double trackLeft = offset.dx;
    final double trackTop = offset.dy + (parentBox.size.height - trackHeight) / 2;
    final double trackWidth = parentBox.size.width;
    return Rect.fromLTWH(trackLeft, trackTop, trackWidth, trackHeight);
  }
}
```

**Comment by Saifallak** [comment]
> This is because the track makes room for the thumb and overlay. These centers are centered on the track, so when they are all the way left or all the way right, they go off the track. You can override the track shape:
> 
> ```
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: MyHomePage(title: 'Flutter Demo Home Page'),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   MyHomePage({Key key, this.title}) : super(key: key);
>   final String title;
> 
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   double _value = 0;
> 
>   @override
>   Widget build(BuildContext context) {
> 
>     return Scaffold(
>       body: Center(
>         child: SliderTheme(
>           data: SliderThemeData(
>             trackShape: CustomTrackShape(),
>           ),
>           child: Slider(
>             value: _value,
>             onChanged: (double value) {
>               setState(() {
>                 _value = value;
>               });
>             },
>           ),
>         ),
>       ),
>     );
>   }
> }
> 
> class CustomTrackShape extends RoundedRectSliderTrackShape {
>   Rect getPreferredRect({
>     @required RenderBox parentBox,
>     Offset offset = Offset.zero,
>     @required SliderThemeData sliderTheme,
>     bool isEnabled = false,
>     bool isDiscrete = false,
>   }) {
>     final double trackHeight = sliderTheme.trackHeight;
>     final double trackLeft = offset.dx;
>     final double trackTop = offset.dy + (parentBox.size.height - trackHeight) / 2;
>     final double trackWidth = parentBox.size.width;
>     return Rect.fromLTWH(trackLeft, trackTop, trackWidth, trackHeight);
>   }
> }
> ```

okay, it worked with your suggestion for width, and for height i used stack to place it over the container not inside it ^^ thanks.

**Comment by gujianxing** [comment]
> This is because the track makes room for the thumb and overlay. These centers are centered on the track, so when they are all the way left or all the way right, they go off the track. You can override the track shape:
> 
> ```
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: MyHomePage(title: 'Flutter Demo Home Page'),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   MyHomePage({Key key, this.title}) : super(key: key);
>   final String title;
> 
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   double _value = 0;
> 
>   @override
>   Widget build(BuildContext context) {
> 
>     return Scaffold(
>       body: Center(
>         child: SliderTheme(
>           data: SliderThemeData(
>             trackShape: CustomTrackShape(),
>           ),
>           child: Slider(
>             value: _value,
>             onChanged: (double value) {
>               setState(() {
>                 _value = value;
>               });
>             },
>           ),
>         ),
>       ),
>     );
>   }
> }
> 
> class CustomTrackShape extends RoundedRectSliderTrackShape {
>   Rect getPreferredRect({
>     @required RenderBox parentBox,
>     Offset offset = Offset.zero,
>     @required SliderThemeData sliderTheme,
>     bool isEnabled = false,
>     bool isDiscrete = false,
>   }) {
>     final double trackHeight = sliderTheme.trackHeight;
>     final double trackLeft = offset.dx;
>     final double trackTop = offset.dy + (parentBox.size.height - trackHeight) / 2;
>     final double trackWidth = parentBox.size.width;
>     return Rect.fromLTWH(trackLeft, trackTop, trackWidth, trackHeight);
>   }
> }
> ```

It works for me.

**Comment by MuhammadFaizan980** [comment]
> This is because the track makes room for the thumb and overlay. These centers are centered on the track, so when they are all the way left or all the way right, they go off the track. You can override the track shape:
> 
> ```
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: MyHomePage(title: 'Flutter Demo Home Page'),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   MyHomePage({Key key, this.title}) : super(key: key);
>   final String title;
> 
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   double _value = 0;
> 
>   @override
>   Widget build(BuildContext context) {
> 
>     return Scaffold(
>       body: Center(
>         child: SliderTheme(
>           data: SliderThemeData(
>             trackShape: CustomTrackShape(),
>           ),
>           child: Slider(
>             value: _value,
>             onChanged: (double value) {
>               setState(() {
>                 _value = value;
>               });
>             },
>           ),
>         ),
>       ),
>     );
>   }
> }
> 
> class CustomTrackShape extends RoundedRectSliderTrackShape {
>   Rect getPreferredRect({
>     @required RenderBox parentBox,
>     Offset offset = Offset.zero,
>     @required SliderThemeData sliderTheme,
>     bool isEnabled = false,
>     bool isDiscrete = false,
>   }) {
>     final double trackHeight = sliderTheme.trackHeight;
>     final double trackLeft = offset.dx;
>     final double trackTop = offset.dy + (parentBox.size.height - trackHeight) / 2;
>     final double trackWidth = parentBox.size.width;
>     return Rect.fromLTWH(trackLeft, trackTop, trackWidth, trackHeight);
>   }
> }
> ```

Life savor <3

**Comment by vireakpanha-khy** [comment]
> This is because the track makes room for the thumb and overlay. These centers are centered on the track, so when they are all the way left or all the way right, they go off the track. You can override the track shape:
> 
> ```
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: MyHomePage(title: 'Flutter Demo Home Page'),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   MyHomePage({Key key, this.title}) : super(key: key);
>   final String title;
> 
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   double _value = 0;
> 
>   @override
>   Widget build(BuildContext context) {
> 
>     return Scaffold(
>       body: Center(
>         child: SliderTheme(
>           data: SliderThemeData(
>             trackShape: CustomTrackShape(),
>           ),
>           child: Slider(
>             value: _value,
>             onChanged: (double value) {
>               setState(() {
>                 _value = value;
>               });
>             },
>           ),
>         ),
>       ),
>     );
>   }
> }
> 
> class CustomTrackShape extends RoundedRectSliderTrackShape {
>   Rect getPreferredRect({
>     @required RenderBox parentBox,
>     Offset offset = Offset.zero,
>     @required SliderThemeData sliderTheme,
>     bool isEnabled = false,
>     bool isDiscrete = false,
>   }) {
>     final double trackHeight = sliderTheme.trackHeight;
>     final double trackLeft = offset.dx;
>     final double trackTop = offset.dy + (parentBox.size.height - trackHeight) / 2;
>     final double trackWidth = parentBox.size.width;
>     return Rect.fromLTWH(trackLeft, trackTop, trackWidth, trackHeight);
>   }
> }
> ```

Is there anyway that I can remove that overlay?

**Comment by fzyzcjy** [comment]
@clocksmith Seems to have a serious problem: If the user moves the tracker to the left or right end, then he **cannot** drag it when his touch is **outside the bounding box of the Slider widget**. This is because of the Flutter's hit test mechanism...

**Comment by agreensh** [comment]
You can use a **Stack** and **Align**

`SizedBox(
  width: 308.0,
  height: 40.0,
  child: Stack(
    children: [
      Align(alignment: Alignment.centerLeft, child: Icon(Icons.accessible)),
      Align(alignment: Alignment.centerRight, child: Icon(Icons.accessibility_new)),
      Align(
        child: SizedBox(
          width: 300.0,
          child: Slider(
            value: _slidarVal,
            onChanged: (value) {
              setState(() {
                _slidarVal = value;
              });
            },
          ),
        ),
      ),
    ],
  ),
),
`

**Comment by karanivincent** [comment]
> class CustomTrackShape extends RoundedRectSliderTrackShape {
>>   Rect getPreferredRect({
>     @required RenderBox parentBox,
>     Offset offset = Offset.zero,
>     @required SliderThemeData sliderTheme,
>     bool isEnabled = false,
>     bool isDiscrete = false,
>   }) {
>>>    final double trackHeight = sliderTheme.trackHeight;
>     final double trackLeft = offset.dx;
>     final double trackTop = offset.dy + (parentBox.size.height - trackHeight) / 2;
>     final double trackWidth = parentBox.size.width;
>     return Rect.fromLTWH(trackLeft, trackTop, trackWidth, trackHeight);
>   }
> }
> ```

How would we do this in regard to null safety?
