### ISSUE TITLE
Is it at all possible to utilize fushcia flutter plugins from Topaz if I am using Targetplatform.fuschia?

### ISSUE THREAD

**Issue by MostHated** [flutter/flutter#37054]
Hey there,
   I was hoping to use webview in my desktop flutter application (using go-flutter, so I am currently using the ```debugDefaultTargetPlatformOverride = TargetPlatform.fuchsia;``` setting). [I came across this Topaz repo](https://github.com/fuchsia-rs/topaz-rs) that had an actual fuschia_webview_flutter plugin so I figured I would give it a go, as currently when I tried to use wevbiew I would get errors that since I am running as fuchsia, webview plugin didn't have a default or working fuchsia config. 

So for giggles, I  added the following:

```
  fuchsia_webview_flutter:
    git:
      url: git@github.com:fuchsia-rs/topaz-rs.git
      path: public/dart/fuchsia_webview_flutter/
```
Which seemed like it might work, but then when I went to run it I received tons of other errors like these:

```
file:///home/mosthated/_dev/sdk/flutter/.pub-cache/git/topaz-rs-2a01f333151a9e565b58d55226dc652d1c6fa35d/public/dart/fuchsia_webview_flutter/lib/src/fuchsia_web_services.dart:12:8: Error: Not found:
'package:fidl_fuchsia_web/fidl_async.dart'
import 'package:fidl_fuchsia_web/fidl_async.dart' as fidl_web;
       ^
```
Unfortunately I don't think there is much I can do about that. : (

So really, my question is that if I am using go-flutter and Targetplatform.fuchsia, is there any plugin or way for me to use webview? The whole reason for wanting to use that was to try and get this [Apexcharts dart adaptation](https://github.com/mdemyanov/dart_apex_charts) to work in flutter.
Thanks!
-MH

**Comment by jonahwilliams** [comment]
The fuchsia implementation of the Webview plugin requires building with a Dart SDK that includes the fuchsia `dart:*` libraries. That won't be possible outside of a Fuchsia device, setting the target platform is really just for themeing + scroll physics.

**Comment by stuartmorgan** [comment]
More generally, two important points about plugins:

- By definition plugins involve platform-specific implementation (if they didn't they would just be packages). Trying to use a plugin implementation written for another platform is essentially the same as trying to compile and run, say, a macOS application on Windows.
- In addition, plugin APIs are provided by the embedding layer. You mentioned that you are using the go-flutter-desktop project, which means the only plugins you will be able to use are plugins specifically written for that project, using its plugin API. Plugin implementations written for Flutter's official desktop embeddings won't work with that project even on the same platform.
