### ISSUE TITLE
Keyboard will show with height event for Android platform

### ISSUE THREAD

**Issue by sandijs-private** [flutter/flutter#37064]
Android platform is missing keyboard will show broadcast with keyboard size as parameter.

On iOS it is possible to animate screen resizing when keyboard shows up.

That allows to create beautiful apps. On Android screen is being suddenly resized.

Keyboard will show detection principles currently are very esoteric too.

At least iOS style mechanism would suffice too.

**Comment by sandijs-private** [comment]
Why can't you create special Flutter only Android customizations which are available only for Flutter? No changes for classical Android programming, just special hidden api for Flutter engine?

**Comment by sandijs-private** [comment]
How about creating "top 10 things to improve in Android" poll, and creating some bounties for the community?

**Comment by reidbaker** [comment]
I believe this is something that is now possible. See https://stackoverflow.com/questions/54563854/how-to-animate-flutter-layout-on-keyboard-appearance for more information.
