### ISSUE TITLE
We shouldn't strip dSYM for App.framework on profile mode

### ISSUE THREAD

**Issue by xster** [flutter/flutter#37065]
Otherwise, it gets annoying while instrumenting etc to always have to go find the dSYM since it's not with the dylib. Since no one is going to upload the profile build to the App Store, we should optimize debugging rather than the output size. 

i.e. purely splitting on https://github.com/flutter/flutter/blob/d2b86edbd2e899ca4d7fb4b5fef758f265aa374f/packages/flutter_tools/bin/xcode_backend.sh#L167 might be oversimplified. 

cc @goderbauer @jmagman

**Comment by goderbauer** [comment]
Sounds reasonable.
