### ISSUE TITLE
After installed new upgrade to 1.7.8 + hotfix 4 

### ISSUE THREAD

**Issue by QponCoin** [flutter/flutter#37069]
## Steps to Reproduce

1. flutter create test2 installs flutter in ro project test2 successfully
    All done!
[√] Flutter is fully installed. (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.175], locale de-AT)
[√] Android toolchain - develop for Android devices is fully installed. (Android SDK version 29.0.0)
[√] Android Studio is fully installed. (version 3.4)
[√] VS Code is fully installed. (version 1.36.1)
[√] Connected device is fully installed. (1 available)

2. cd test2

3. flutter run --release --verbose
```
[  +34 ms] executing: [d:\flutter\] git log -n 1 --pretty=format:%H
[  +84 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] 20e59316b8b8474554b38493b8ca888794b0234a
[   +1 ms] executing: [d:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +66 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] v1.7.8+hotfix.4-0-g20e59316b
[  +30 ms] executing: [d:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +60 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[   +2 ms] executing: [d:\flutter\] git ls-remote --get-url origin
[  +55 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[  +87 ms] executing: [d:\flutter\] git rev-parse --abbrev-ref HEAD
[ +173 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +5 ms] stable
[  +89 ms] executing: C:\Users\Tayfun\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +33 ms] Exit code 0 from: C:\Users\Tayfun\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[   +2 ms] List of devices attached
           d638256                device product:i9000S model:i9000S device:msm8916_32 transport_id:6
[  +17 ms] C:\Users\Tayfun\AppData\Local\Android\Sdk\platform-tools\adb.exe -s d638256 shell getprop
[ +139 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +190 ms] ro.hardware = qcom
[  +34 ms] Initializing gradle...
[   +3 ms] Using gradle from D:\MobileApp\flutter\test2\android\gradlew.bat.
[ +114 ms] executing: D:\MobileApp\flutter\test2\android\gradlew.bat -v
[+6550 ms]
                    ------------------------------------------------------------
                    Gradle 4.10.2
                    ------------------------------------------------------------

                    Build time:   2018-09-19 18:10:15 UTC
                    Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

                    Kotlin DSL:   1.0-rc-6
                    Kotlin:       1.2.61
                    Groovy:       2.4.15
                    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                    OS:           Windows 10 10.0 amd64
[  +17 ms] Initializing gradle... (completed in 6,7s)
[   +2 ms] Resolving dependencies...
[   +2 ms] executing: [D:\MobileApp\flutter\test2\android\] D:\MobileApp\flutter\test2\android\gradlew.bat app:properties
c:\b\s\w\ir\k\src\third_party\dart\runtime\vm\thread_pool.cc: 341: error: Could not start worker thread: result = 22.
version=2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "windows_x64"
thread=18944, isolate=(null)(0000000000000000)
  pc 0x00007ff608872b1b fp 0x00000079b05ff4c0 Unknown symbol
-- End of DumpStackTrace
```

**Comment by QponCoin** [comment]
flutter doctor -v
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.175], locale de-AT)
    • Flutter version 1.7.8+hotfix.4 at d:\flutter
    • Framework revision 20e59316b8 (8 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Tayfun\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = C:\Users\Tayfun\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\AndroidStudio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\Tayfun\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • i9000S • d638256 • android-arm • Android 5.1.1 (API 22)

• No issues found!

**Comment by VladyslavBondarenko** [comment]
@QponCoin 
Closing this issue as not related directly to Flutter
https://github.com/dart-lang/sdk/issues/37155#issuecomment-503242572
if you disagree please write in the comments and I will reopen it
thank you
