### ISSUE TITLE
flutter run broken on iOS hardware

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#3707]
## Steps to Reproduce

- attach an iPhone 5S to your mac
- attempt to "flutter run" from inside of examples/material_gallery on alpha or master.
- The app icon is installed on the phone.
- After opening the app it immediately closes.

Note: The app runs fine on the iOS simulator.
I have not done a git bisect to find the offending commit.

## Flutter Doctor
```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision 50626e9b21 (15 minutes ago), engine revision d85ead8ec2

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.2.1, Build version 7C1002

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```
## Logs and Crash Reports

Nothing is output to flutter logs
```
Showing iPhone logs:
```

**Comment by drewwarren** [comment]
731c590 is the most recent commit in my reflog that works on iOS hardware.

**Comment by eseidelGoogle** [comment]
@chinmaygarde @tvolkert

**Comment by chinmaygarde** [comment]
Have a repro. Investigating.

**Comment by chinmaygarde** [comment]
This is because the `--profile` flag went away from the Dart VM during precompilation and we were passing in `--no-profile` on startup. This caused to VM to die on an unrecognized flag. There is a PR pending that amends this. Will need an engine roll after.
