### ISSUE TITLE
[web] tried to call a non-function, such as null: 'dart.global.firebase.storage'

### ISSUE THREAD

**Issue by mohamed6996** [flutter/flutter#37079]
Im using Firebase plugin for web and managed to work with firestore and authentication. Now, Im trying to enable firebase storage but when i instanciate Storage gives me this error 
`tried to call a non-function, such as null: 'dart.global.firebase.storage`

for firestore and authentication I use : 

```
import 'package:firebase/firebase.dart' as fb;
import 'package:firebase/firestore.dart';

 fb.Auth _firebaseAuth = fb.auth();
  Firestore _firestore =fb.firestore();
```

for Storage :
`    fb.Storage storage = fb.storage();
`

**Comment by zanecidan** [comment]
Same issue faced here.

**Comment by mohamed6996** [comment]
I have solved it 
please check my answer on [stackoverflow ](https://stackoverflow.com/questions/57242045/flutter-web-tried-to-call-a-non-function-such-as-null-dart-global-firebase-s)

**Comment by BondarenkoStas** [comment]
@mohamed6996 Awesome! Thank you for finding a solution. I think it's safe to close it.

**Comment by zaid13** [comment]
i have these in my index.html 

  <script src="https://www.gstatic.com/firebasejs/7.14.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.14.0/firebase-firestore.js"></scrip
    <script src="https://www.gstatic.com/firebasejs/7.14.0/firebase-storage.js"></script>
  <script defer src="main.dart.js" type="application/javascript"></script>


but my 

import 'package:firebase/firebase.dart' as fb;
import 'package:firebase/firestore.dart';

 fb.Auth _firebaseAuth = fb.auth();
  Firestore _firestore =fb.firestore();



gives me this

TypeError: dart.global.firebase.storage is not a function

**Comment by azzamjafri** [comment]
Same here... your answer is not working :)

**Comment by santhonydo** [comment]
<script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-storage.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-firestore.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-analytics.js"></script>

make sure all the versions match up. i'm using 7.5.0 here. prior to this, i was using a different storage version. hope it that helps

**Comment by officialasit** [comment]
@santhonydo Thanks, my other js files were not of same version so it gave me the error. Making all them same version makes the issue solve.
