### ISSUE TITLE
Compositing could be much faster for examples with lots of layers

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3708]
We've seen @abarth's flow demo run slowly on some hardware. Rasterizer thread long pole being ~7ms in LayerTree::Paint, and Engine thread being 1ms Paint, but 5-10ms in Compositing.  @abarth says compositing could be 2x - 4x faster if made incremental.

**Comment by abarth** [comment]
Some progress in https://github.com/flutter/flutter/commit/0f3bd3ae842e8b287152140aca8d641aca0c035a

Also experimenting in https://github.com/flutter/engine/compare/master...abarth:encoded_buffer?expand=1

**Comment by Hixie** [comment]
@abarth Is this still something you're looking at, or should we close this until we run into an actual issue?

**Comment by abarth** [comment]
Let's close this issue.  We did culling instead, and that seems to have addressed the cases that were causing us trouble.
