### ISSUE TITLE
#Issues with =>  com.google.gms:google-services:4.3.0

### ISSUE THREAD

**Issue by pokkeerr** [flutter/flutter#37081]
Hi all ,

I Have Issues with
(  classpath 'com.google.gms:google-services:4.3.0'  )

when i added it to the dependencies in android/build.gradle to get Firebase Authentication and Google Sing in plug-ins , get this Erorr : 

-------------------------------------------------------------------------------
 Error running Gradle:
ProcessException: Process "C:\Users\POKER\IdeaProjects\Udemy\Course 3\introflutter\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

 Where:
Build file 'C:\Users\POKER\IdeaProjects\Udemy\Course 3\introflutter\android\app\build.gradle' line: 24

 What went wrong:
A problem occurred evaluating project ':app'.
ASCII

 Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

 Get more help at https://help.gradle.org

BUILD FAILED in 2s
  Command: C:\Users\POKER\IdeaProjects\Udemy\Course 3\introflutter\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.
Exited (sigterm)

**Comment by d-apps** [comment]
I changed to classpath 'com.google.gms:google-services:4.2.0' and it's working.

**Comment by pokkeerr** [comment]
@d-apps thanks for help ,
after change it to 'com.google.gms:google-services:4.2.0' i get this Error :
__________________________________________________________________________________________________
Launching lib\main.dart on Android SDK built for x86 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+12\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:9: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+12\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:10: error: cannot find symbol
import androidx.annotation.Nullable;
                          ^
  symbol:   class Nullable
  location: package androidx.annotation
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+12\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:759: error: cannot find symbol
  private void reportException(Result result, @Nullable Exception exception) {
                                               ^
  symbol:   class Nullable
  location: class FirebaseAuthPlugin
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+12\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:668: error: cannot find symbol
    public void onComplete(@NonNull Task<AuthResult> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.SignInCompleteListener
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+12\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:687: error: cannot find symbol
    public void onComplete(@NonNull Task<Void> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.TaskVoidCompleteListener
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+12\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:705: error: cannot find symbol
    public void onComplete(@NonNull Task<SignInMethodQueryResult> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.GetSignInMethodsCompleteListener
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+12\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:540: error: cannot find symbol
              public void onComplete(@NonNull Task<GetTokenResult> task) {
                                      ^
  symbol: class NonNull
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+12\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:617: error: cannot find symbol
          public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
                                          ^
  symbol: class NonNull
8 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_auth:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 47s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

________________________________________________
and i follow all the steps in this link  https://goo.gl/CP92wY and fix The androidX , get new error : 
__________
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:51079/gM04ir90Rpc=/ws

**Comment by pokkeerr** [comment]
i solved 👍 

after changed 
classpath 'com.google.gms:google-services:4.3.0'
to
classpath 'com.google.gms:google-services:4.2.0'

then followed this steps here : https://goo.gl/CP92wY

and run my emulator in Pie "28"

**Comment by jennsenr** [comment]
> Lo resolví 👍
> 
> después de cambiar 
> classpath 'com.google.gms: google-services: 4.3.0' 
> a 
> classpath 'com.google.gms: google-services: 4.2.0'
> 
> luego seguí estos pasos aquí: https://goo.gl/CP92wY
> 
> y ejecuta mi emulador en Pie "28"

Hola, hay manera de ejecutarlo en versión menor a 28?

**Comment by addy419** [comment]
This is a recent issue that I'm facing, which was actually resolved in previous months

**Comment by QuinnZillian** [comment]
As of this posting, I have success using... 
**flutter doctor**
`
Flutter 1.7.8+hotfix.4
Develop for Android devices (Android SDK version 29.0.0)
Android Studio (version 3.4)
`


**android/build.gradle**
`
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.gms:google-services:4.3.0'
    }
`
**android/app/build.gradle**
`
...
    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.app.firebase"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
...

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'androidx.multidex:multidex:2.0.0'
    implementation 'com.google.firebase:firebase-core:17.0.0'
}

apply plugin: 'com.google.gms.google-services'
`

**android/gradle/wrapper/gradle-wrapper.properties**
`
distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
`


** running gradle **
I do get a few red Notes but everything is working 
`
Note: \flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.9\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: \flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.9\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
`

**pubspec.yaml**
`
  firebase_core: ^0.4.0+8
  firebase_auth: ^0.14.0+1
  cloud_firestore: ^0.12.9
`

Good Luck

**Comment by Xentraxx** [comment]
I face the same issue and for me downgrading to 4.2.0 (which with it works) is not an option as I would like to use plugins which require 4.3.0. 
Is there any other solution?

**Comment by Mastersam07** [comment]
I Have Issues with any of classpath 'com.google.gms:google-services:4.3.0' and classpath 'com.google.gms:google-services:4.3.0' when i added it to the dependencies in android/build.gradle to get Firebase Authentication and Google sign in. classpath 'com.google.gms:google-services:4.3.0' keeps telling me somethings are deprecated and either of 'com.google.gms:google-services:4.3.0' and classpath 'com.google.gms:google-services:4.3.0' returns the below error:

```
* Error running Gradle:
ProcessException: Process "C:\Users\QSERVERS\Desktop\FlutterApps\FlutterGrocery-ShoppingAppUI\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\QSERVERS\Desktop\FlutterApps\FlutterGrocery-ShoppingAppUI\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 52s
  Command: C:\Users\QSERVERS\Desktop\FlutterApps\FlutterGrocery-ShoppingAppUI\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

```
What's the way forward?

**Comment by AnanthanAn** [comment]
facing the same issue..please assist

**Comment by Mastersam07** [comment]
@AnanthanAn you could try using "com.google.gms:google-services:4.2.0" instead. It worked fine the only thing is that you will get a message that some things are deprecated. However, you could include androidX compatibility. That should also solve it.

**Comment by Mastersam07** [comment]
However, if you need plugins that require 4.3.0 and above, you could try migrating your flutter project to androidX [Click here](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility) @AnanthanAn .
