### ISSUE TITLE
[local_auth] App doesn't load with FragmentActivity and doesn't work without it.

### ISSUE THREAD

**Issue by SamuelMTDavies** [flutter/flutter#37083]
My app uses Local Auth to securely store and retrieve data. 

I have migrated to Android X with no issues. 

But when I come to use the app on a physical device the app tries to authenticate I get the following Platform Exception:

`I/flutter (11159): PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null)`

So I have read and seen that I need to change the MainActivity.java file to extend FlutterFragmentedActivity.

My project does not contain a MainActivity.java file but it does contain a MainActivity.kt file.

So I change the file from

```
import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}
```

TO

```

import android.os.Bundle
import io.flutter.app.FlutterFragmentActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}
```

When I then try to run the app it crashes before it even loads. With the following error:

```
Initializing gradle...
Resolving dependencies...
Launching lib/main_edge.dart on LYA L09 in profile mode...
[{"event":"app.progress","params":{"appId":"29dcadd4-764a-481e-930e-b87311600b33","id":"2","progressId":null,"message":"Running Gradle task 'assembleProfile'..."}}]Running Gradle task 'assembleProfile'...

e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class io.flutter.app.FlutterFragmentActivity, unresolved supertypes: android.support.v4.app.FragmentActivity


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileProfileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleProfile failed with exit code 1

```

I have no android experience but I migrated my project to android X with no issues and I don't have any dependencies that are not android x ready.

Any help locating the root cause of this issue would be greatly appreciated. Could it be as simple as my Kotlin code being written wrong?

**Comment by sarbagyastha** [comment]
Ensure that you have enabled jetifier.

**Comment by SamuelMTDavies** [comment]
Ok, great that was simple to do and it now appears to be working - before I close this issue.

I followed the [Migrate to AndroidX using Android Studio instructions](https://developer.android.com/jetpack/androidx/migrate?authuser=1#migrate).

Maybe there is room to make the instructions clearer? Especially for those not familiar with android concepts?

When the instructions say:

> If you have any Maven dependencies that have not been migrated to the AndroidX namespace, the Android Studio build system also migrates those dependencies for you when you set the following two flags to true in your `gradle.properties` file:
```
android.useAndroidX=true
android.enableJetifier=true
```
What does it mean exactly and how does someone tell if they have such dependencies?


When I look at the instructions on how to migrate manually to android X I can see that some of my files have not been changed. Considering I have run the automatic migration to androidX tool.

My `build.gradle` file for example still has the following dependencies:
```
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
```

Am I going to run into issues further down the line? Should this not have been converted to the following as part of the refactoring to androidX?

```
androidTestImplementation 'androidx.test:runner:1.1.1'
androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
```

**Comment by theindianappguy** [comment]
Facing the same issue

Was not able to find the mainactivity thannks got the mainactivity.kt here how to looks

`package com.theindianappguy.rest_app

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
`
 This is how i updates 

`package com.theindianappguy.rest_app

import androidx.annotation.NonNull;
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.app.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
`

says configureFlutterEngine overrides nothing so i removed override still not working 

shows the error 
I/flutter (16049): PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null)

as the code for mainactivity.kt has changed i am not able to understand what to update please help

**Comment by caiquecruz** [comment]
@theindianappguy

In build.gradle file, just downgraded from:

classpath 'com.android.tools.build:gradle:3.5.0' 

to:

classpath 'com.android.tools.build:gradle:3.3.0'

Worked for me.

**Comment by fabioselau077** [comment]
> @theindianappguy
> 
> In build.gradle file, just downgraded from:
> 
> classpath 'com.android.tools.build:gradle:3.5.0'
> 
> to:
> 
> classpath 'com.android.tools.build:gradle:3.3.0'
> 
> Worked for me.

not worked for me :/

**Comment by ayinloya** [comment]
I followed the solutions provided above, still getting errors.
The project was started with Androidx support
When using FlutterActivity the error  `PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null)` is returned

When I change FlutterActivity to FlutterFragmentActivity

I get `/flutter (30051): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`
and the app gets stack with a white screen

**Comment by stevenspiel** [comment]
I'm having the same issue @ayinloya is having

**Comment by stevenspiel** [comment]
https://stackoverflow.com/a/60935905/1411004 This answer fixed it for me.

**Comment by ayinloya** [comment]
Thanks @stevenspiel , it's fixed now

**Comment by hcaz** [comment]
The answer that @stevenspiel gave should probably be added to the documentation to make it clear what changes are needed on androidX

**Comment by toxicOxygen** [comment]
@stevenspiel  thanks man

**Comment by donaldkg** [comment]
@stevenspiel thanks you are the man

**Comment by omarvbnet** [comment]
> https://stackoverflow.com/a/60935905/1411004 This answer fixed it for me.
> 
> My `MainActivity.kt` needed to be:
> 
> ```kotlin
> package com.[my.package]
> 
> import androidx.annotation.NonNull;
> import io.flutter.embedding.android.FlutterFragmentActivity
> import io.flutter.embedding.engine.FlutterEngine
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterFragmentActivity() {
>     override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
>         GeneratedPluginRegistrant.registerWith(flutterEngine);
>     }
> }
> ```

thank u its work with me too
