### ISSUE TITLE
Why does `flutter create` make things to ignore, in particular, the `.idea/` directory?

### ISSUE THREAD

**Issue by bradyt** [flutter/flutter#37095]
When I run `flutter create --template=plugin .`, the results include a `.idea/` directory. This seems to me to conflict with https://dart.dev/guides/libraries/private-files, where they say the following.

> Don’t commit files and directories created by other development environments. For example, if your development environment creates any of the following files, consider putting them in a global ignore file:
> 
> ```
> *.iml         // IntelliJ
> *.ipr         // IntelliJ
> *.iws         // IntelliJ
> .idea/        // IntelliJ
> .DS_Store     // Mac
> ```

Ideally, I'd like to create a project, git commit everything that is produced, and begin. I feel that `git clean -dfx`, or similar, should not change much from the state found after the first `flutter create`.

My flutter version is as follows.

```
> flutter --version
Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (9 days ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0
```

**Comment by jmagman** [comment]
The `.idea/` directory is in the .gitignore so it shouldn't be checked in and doesn't conflict with https://dart.dev/guides/libraries/private-files.

See https://github.com/flutter/flutter/issues/5876.

Let's close this in favor of https://github.com/flutter/flutter/issues/14723.
