### ISSUE TITLE
Oops; flutter has exited unexpectedly

### ISSUE THREAD

**Issue by DJRahim** [flutter/flutter#37097]
## Steps to Reproduce

1. ...i installed flutter on fedora 30
2. ...i tried to use to use it in IntelliJ and VS code (after installing extension)
3. ...it's not working

## Logs

```
```

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 4ea6a32e33347b65)
Crash report written to /home/rahim/Documents/eclipse-workspace/TestFX/src/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by BugsBunnyBR** [comment]
Post the log file as described in the log..

 /home/rahim/Documents/eclipse-workspace/TestFX/src/flutter_01.log

**Comment by bsas3** [comment]
I just started having the same problem. I'm using the latest versions of both Flutter & IntelliJ. The problem started about an hour ago.  All was fine before that.  Hope someone has some good ideas to fix the problem.

**Comment by jmagman** [comment]
@DJRahim Can you attach the log?
/home/rahim/Documents/eclipse-workspace/TestFX/src/flutter_01.log

**Comment by bsas3** [comment]
@jmagman thanks for getting back to me.  I managed to track down the fault.  When I added Assets to the pubspec.yaml I tapped the return key, which added a dash to the next line. Once I deleted that line, all was good again.
Thanks again & hope this helps someone else.

**Comment by jmagman** [comment]
Thanks!
