### ISSUE TITLE
lost connection to device,when i send camera preview data to native.

### ISSUE THREAD

**Issue by bladeofgod** [flutter/flutter#37127]
when i send a camera preview data(cameraImage) to native,app will lost connection to device. it will happen on medium and high quality of cameraImage, low quality it's OK,  i checked permission and code,and didn't find anything. plz help me,thanks a lot. :)

**Comment by BondarenkoStas** [comment]
@bladeofgod Please provide your `flutter doctor -v``` output. Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
