### ISSUE TITLE
Flutter not recognizing Android device running N Preview

### ISSUE THREAD

**Issue by qchong** [flutter/flutter#3712]
## Steps to Reproduce

Running the 'flutter devices' command with my device (Nexus 6 running Android N Preview) connected via USB (and USB Debugging enabled), but it gives this output:

> Building flutter tool...
> Unexpected failure parsing device information from adb output:
> ZX1G22JJWR             device usb:3-3 product:shamu model:Nexus_6 device:shamu features:cmd,shell_v2
> Please report a bug at https://github.com/flutter/flutter/issues/new
> No devices detected.

## Flutter Doctor

> [✓] Flutter (on Linux, channel master)
>     • Flutter at /usr/local/google/home/quddusc/flutter
>     • Framework revision 4d88752c39 (75 minutes ago), engine revision d85ead8ec2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 23.0.1)
>     • Android SDK at /usr/local/google/home/quddusc/android-sdk
>     • Platform android-23, build-tools 23.0.1
>     • OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.2)
> 
> [✓] Atom - a lightweight development environment for Flutter
>     • Atom installed; Flutter plugin version 0.2.1

**Comment by eseidelGoogle** [comment]
@devoncarew fixed one of these the other day.  maybe adb has a more parser friendly format?
