### ISSUE TITLE
Flutter web borderradius problem

### ISSUE THREAD

**Issue by serdarpolat** [flutter/flutter#37121]
`Container(
                            width: 50,
                            height: 50,
                            decoration: BoxDecoration(
                              border: Border.all(
                                color: Colors.white,
                                width: 1.2,
                              ),
                              borderRadius: BorderRadius.circular(50),
                            ),
                            child: Icon(
                              Icons.shopping_cart,
                              size: 24,
                              color: Colors.white,
                            ),
                          ),`

it works fine when I delete borderRadius parameter. otherwise, all borders are invisible...

**Comment by ditman** [comment]
I'm closing this one as fixed, here: https://github.com/flutter/engine/commit/851f4606f19541376b6e8915e7b8677b31853223

**Comment by shinewanna** [comment]
use Card with evaluation:0 for temporary fix.
