### ISSUE TITLE
Unable to call a platform channel method from a another isolate

### ISSUE THREAD

**Issue by hetian9288** [flutter/flutter#37132]
original issues #13937

When I try to invoke a platform channel method from a custom spawned isolate, the app crashes badly (both on iOS and Android). I'm trying to figure out whether this is expected or not.

If it's not, it's probably worth to mention that somewhere.

Anyways I think that this can potentially be a strong limitation. Is there a way to be able to call platform plugins from a secondary isolate?

**Comment by stuartmorgan** [comment]
Please don't deliberately file duplicate issues. If you want to indicate interest in an issue being fixed, vote for it.

**Comment by MichealReed** [comment]
@stuartmorgan, @hetian9288 opened a duplicate issue because the issue has gone stale. The previous issue owner no longer works at Google. How are issues reassigned?
