### ISSUE TITLE
[dashboard] add charts for active users of flutter tool

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#3713]
@sethladd 

> Maybe try this: https://developers.google.com/analytics/devguides/reporting/embed/v1/getting-started#sample

**Comment by sethladd** [comment]
Update: I got this working, but ran into permission problems between internal and external accounts. No current plan on how to resolve.

**Comment by yjbanov** [comment]
`<iframe>` perhaps?

**Comment by sethladd** [comment]
Someone still needs to login for that iframe, from the chromebox. Meanwhile, I have an email out to the analytics folks.

**Comment by sethladd** [comment]
Not currently planned. Ping me if you want to see the analytics dashboard.
