### ISSUE TITLE
Silent failure to unzip dart SDK in flutter.bat leads to 'pub upgrade' error

### ISSUE THREAD

**Issue by sedlund** [flutter/flutter#37135]
I tried to update the channel with on Windows 10:

1.  flutter channel master
2. flutter upgrade

I then received the error:
```
Downloading Dart SDK from Flutter engine ead227f a... 
Unzipping Dart SDK... 
Updating flutter tool... 
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

Waiting for 0 seconds, press CTRL+C to quit ... 
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...
```

Debugging it I found I had two copies of 7z in my path (from installs of Choco and Scoop) and the first one was a broken shim link.

The error comes from line 66 in `update_dart_sdk.ps1`

`If (Get-Command 7z -errorAction SilentlyContinue) {`

It does as told and SilentlyContinues after failing to unzip the dart-sdk and then repeatedly tries to run pub upgrade...

To resolve I had to remove the broken shim.   Some error checking and better output may be good here.

**Comment by croxx5f** [comment]
Hello I had the same issue in my case using linux. I had not installed the 'unzip' package and my upgrade failed too. after installind said package i was able to upgrade properly. i found out due to the error on the update_dart_sdk.sh calling unzip and it being unaviable at the time

**Comment by klokoleva** [comment]
I have same issues,
error in : Unzipping Dart SDK...

**Comment by christopherfujino** [comment]
This is the linux version of this issue https://github.com/flutter/flutter/issues/47307

**Comment by christopherfujino** [comment]
I believe this was fixed by https://github.com/flutter/flutter/pull/65929
