### ISSUE TITLE
How to convert images to PDF

### ISSUE THREAD

**Issue by ShashankSirmour** [flutter/flutter#37138]
I want to create pdf from images I tried pdf 1.3.17  for that but when the pdf size is big due to high-quality images  the app is killed by the OS because it used too much RAM

**Comment by miyoyo** [comment]
This should not be a github issue.
Use a native image->pdf converter instead of that package.

**Comment by ShashankSirmour** [comment]
any image to pdf conversion native package suggestion?

**Comment by ShashankSirmour** [comment]
https://github.com/DavBfr/dart_pdf/issues/109#issue-471226514

if someone wants to fix the issue in pdf package flutter

**Comment by BondarenkoStas** [comment]
@ShashankSirmour This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
