### ISSUE TITLE
SharedPreferences 

### ISSUE THREAD

**Issue by Wiwo99** [flutter/flutter#37137]
Hello guys, I'm trying to save a "List <MyClass>" list as "List <String>" to add items to SharedPreferences ... what should I do? Thank you.

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by miyoyo** [comment]
This should not be a github issue.
Shared Preferences can only store lists of String, serialize your data to a format like JSON before commiting it.

**Comment by BondarenkoStas** [comment]
@Wiwo99 This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
