### ISSUE TITLE
firebase_auth "Use the plugin" typo in example, doesn't build

### ISSUE THREAD

**Issue by mrmax99** [flutter/flutter#37146]
The below example is listed in the firebase_auth plugin page on pub.dev:
https://pub.dev/packages/firebase_auth

```
Future<FirebaseUser> _handleSignIn() async {
  final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
  final GoogleSignInAuthentication googleAuth = await googleUser.authentication;

  final AuthCredential credential = GoogleAuthProvider.getCredential(
    accessToken: googleAuth.accessToken,
    idToken: googleAuth.idToken,
  );

  final FirebaseUser user = await _auth.signInWithCredential(credential);
  print("signed in " + user.displayName);
  return user;
}
```

The function "signInWithCredential" returns an AuthResult, which is not the same type as user (FirebaseUser).  It should look something like this I think:

`  final FirebaseUser user = (await _auth.signInWithCredential(credential)).user;
`

**Comment by kroikie** [comment]
@mrmax99

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1090. Any further collaboration will be done there.
