### ISSUE TITLE
Firebase plugin networking debug log output

### ISSUE THREAD

**Issue by lookfirst** [flutter/flutter#37148]
I added Firebase plugins to my flutter project and now I'm seeing this networking debug output. I'd like the option to turn it off. I have done a ton of googling and grepping and I can't seem to find out where that option is.

```
[C19.1 :64617<->172.217.25.10:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.254s, DNS @0.000s took 0.018s, TCP @0.020s took 0.041s, TLS took 0.120s
	bytes in/out: 4901/1095, packets in/out: 10/9, rtt: 0.043s, retransmitted packets: 0, out-of-order packets: 0
```

**Comment by lookfirst** [comment]
@jmagman ?

**Comment by jmagman** [comment]
@collinjackson

**Comment by kroikie** [comment]
@lookfirst

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1130. Any further collaboration will be done there.
