### ISSUE TITLE
[web]: <Please update PaginatedDataTable class in flutter_web to support custom row height>

### ISSUE THREAD

**Issue by xingchenxuanfeng** [flutter/flutter#37157]
Flutter for android and ios already support custom row height when using PaginatedDataTable.

But flutter_web is still not support now.

I think it's a very useful feature for PaginatedDataTable.

Please update PaginatedDataTable class in flutter_web to support custom row height!

**Comment by yjbanov** [comment]
`flutter_web` is deprecated. Please use the normal Flutter SDK: https://flutter.dev/docs/get-started/web
