### ISSUE TITLE
[dashboard] rename package to 'dashboard'

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#3715]
@devoncarew 

> What about renaming this repo from dashboard_box to dashboard? It's shorter and still pretty descriptive of what it does. It might look better in the list of other flutter repos: https://github.com/flutter.

@yjbanov

> The paths are hardcoded in the build script and currently dashboard is used for the resulting dashboard site itself. I also wonder if "dashboard" might give a wrong impression that this is something developers should use, while in fact this is just ad hoc scripts building our own dashboard. Perhaps we should rename it to dashboard_builder, as the "_box" suffix is indeed weird.

**Comment by sethladd** [comment]
Are we planning to do this? If not, let's close.

**Comment by devoncarew** [comment]
I'd still be in favor but will defer to @yjbanov.

**Comment by yjbanov** [comment]
Should become possible as soon as the conflicting directory is removed by https://github.com/flutter/dashboard_box/pull/30

**Comment by yjbanov** [comment]
Ok, so this is possible now. However, changing the name involves:

* Renaming everything in the code
* Renaming the repository
* Redeploying to the dashboard box
* Redeploying the golem script
* Updating everyone's git clients

Is it worth the trouble?

I prefer that bugs don't linger in the system, so we should either fix it, or close it. Thoughts?

**Comment by yjbanov** [comment]
I do not have a preference for the name, and seeing how fixing this involves work, my vote is "no".

**Comment by sethladd** [comment]
Close it. If someone wants to change it, you provided a very good list :)

> Updating everyone's git clients

fwiw, this isn't necessarily required. GitHub does a very good job in maintaining redirects.

**Comment by devoncarew** [comment]
Lots of work just to make my OCD slightly happier. Closing...
