### ISSUE TITLE
[webview_flutter]cannot copy/paste/translate in webview_flutter

### ISSUE THREAD

**Issue by apm29** [flutter/flutter#37163]
## Steps to Reproduce

1. use the plugin webview_flutter with version 0.3.10+4
2. load any website with some text or input
3. long press cannot popup copy/paste/translate popup window as expected
4. devices i used : XIAOMI/HUAWEI phones/tablets ,new and old, works fine on iOS,
here is one device info  : HUAWEI BTV , Android 7.0 emui 5.0.4

## Logs
flutter doctor :

```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.8.2-pre.216, on Mac OS X 10.14.6 18G84, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Community Edition (version 2019.1.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.35.1)
[✓] Connected device (1 available)

```

**Comment by Sarthaktydy** [comment]
flutter's webview is in really bad shape. You cant open storage from input tags you cant call 'tel:' 'mailto:' functionality, Keyboard doesn't work properly.  Because of these issues, I started using flutter_webview_plugin.

**Comment by apm29** [comment]
does any one has the solution? 😭

**Comment by BondarenkoStas** [comment]
@apm29 Is it the same with current `webview_flutter 0.3.14+1`?

**Comment by GitTradWang** [comment]
> @apm29 Is it the same with current `webview_flutter 0.3.14+1`?
Yes！！

**Comment by deandreamatias** [comment]
This issue seems the same as #24584. If this is the case, it would be ideal to close one of the two

**Comment by BondarenkoStas** [comment]
Closing in favour of https://github.com/flutter/flutter/issues/24584 to avoid duplication, please follow it there.

**Comment by davidakinfenwa** [comment]
Please is the issue fixed i am having the same issue with copy and paste

**Comment by BigNateBombBomb** [comment]
Any resolution to this issue yet?
