### ISSUE TITLE
Crash in firebase_auth with email/password user

### ISSUE THREAD

**Issue by lookfirst** [flutter/flutter#37160]
`firebase_auth: 0.13.0`

The rest is the same as: #37133

I did a build clean in xcode and `pod cache clean --all` to ensure I'm using latest version. 

I have a user created in Firebase as a email/password user.

I can login via google auth with that same user email and their google password.

When I try to login with that user via email/password (defined in firebase), I get this crash.

Please note that I also had to run this in the simulator on my desktop. Running it on the device, connected via USB, did not produce any output.

```
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001090178db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001085baac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000108f65fac _CFThrowFormattedException + 194
	3   CoreFoundation                      0x0000000109083e11 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x00000001090135bb +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   Runner                              0x00000001035676c5 -[FLTFirebaseAuthPlugin sendResult:forAuthDataResult:error:] + 1349
	6   Runner                              0x0000000103565a49 __49-[FLTFirebaseAuthPlugin handleMethodCall:result:]_block_invoke.284 + 137
	7   Runner                              0x00000001033d16d0 __64-[FIRAuth signInFlowAuthDataResultCallbackByDecoratingCallback:]_block_invoke_2 + 48
	8   libdispatch.dylib                   0x0000000109562d7f _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x0000000109563db5 _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x0000000109571080 _dispatch_main_queue_callback_4CF + 1540
	11  CoreFoundation                      0x0000000108f7ea79 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	12  CoreFoundation                      0x0000000108f79126 __CFRunLoopRun + 2310
	13  CoreFoundation                      0x0000000108f784d2 CFRunLoopRunSpecific + 626
	14  GraphicsServices                    0x000000010ba7b2fe GSEventRunModal + 65
	15  UIKitCore                           0x0000000111372fc2 UIApplicationMain + 140
	16  Runner                              0x00000001033c2080 main + 112
	17  libdyld.dylib                       0x00000001095d8541 start + 1
```

**Comment by lookfirst** [comment]
Reverting to `0.11.1+12` produces an error message of: 'The password is invalid or the user does not have a password'

**Comment by lookfirst** [comment]
Using `0.11.1+12`, I just deleted that user in firebase and recreated them. Now I can login using either account or methodology. I think I'll stick at this version for a while until you get all the bugs sorted out. =)

**Comment by collinjackson** [comment]
@lookfirst could you let me know if updating to 0.13.1 resolves this issue for you?

**Comment by lookfirst** [comment]
@collinjackson 
I am not able to reproduce this for some reason. I saw it a couple times, then reloaded the app a few times and suddenly it is working.

What I saw in my stack trace was that I was setting up a listener `_googleSignIn.onCurrentUserChanged.listen...` before a `_googleSignIn.signIn` and getting a NPE.

```
class FirebaseUser extends UserInfo {
  FirebaseUser._(Map<String, dynamic> data, FirebaseApp app)
      : providerData = data['providerData']
            .map<UserInfo>((dynamic item) => UserInfo._(item, app))
            .toList(),
        _metadata = FirebaseUserMetadata._(data),
        super._(data, app);
```

I was seeing that `data['providerData']` was null. Seems like there is a case somehow that that could end up creating a user but with null providerData.

So, maybe add some tests around that usecase and see if you can duplicate the issue?

Regardless, I think this particular issue is fixed now.

**Comment by kroikie** [comment]
@lookfirst

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1089. Any further collaboration will be done there.
