### ISSUE TITLE
How to make a new Flutter SDK by open source?

### ISSUE THREAD

**Issue by luori-mvp77** [flutter/flutter#37167]
Hi,
I analyze the flutter projects likes : flutter , flutter-engine,dart sdk, and the flutter sdk almost come from them. now i want to try make a new flutter sdk like https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_v1.7.8+hotfix.4-stable.zip. So I want a guidance for how to build it now.

I just find how to building dart (https://github.com/dart-lang/sdk/wiki/Building), i wanna whether some devTools could build flutter sdk cover some different projects?

**Comment by miyoyo** [comment]
If you want to build the sdk, [follow this page](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md)
