### ISSUE TITLE
path_provider changed download directory. How can I access download directory?

### ISSUE THREAD

**Issue by hebersousa** [flutter/flutter#37179]
From version 1.1.2 path_provider changed on android its native method from getExternalStorageDirectory to getExternalFilesDir (related to app directory). path_provider no more support access to generic download directory.
Why did this change happen? How can I access the generic download directory on android?

**Comment by jmagman** [comment]
I believe this is being tracked with https://github.com/flutter/flutter/issues/35783.  If not, please re-open!
