### ISSUE TITLE
Curl Upload and Install command response as java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by murlidhar2019** [flutter/flutter#37170]
Hi, I am getting response as "**java.util.zip.ZipException: error in opening zip file**" and Status Code **500** when I run the Upload and Install command 
curl -u admin:admin -F file=@"dam-backup.zip" -F name="dam-backup.zip" -F force=true -F install=true http://localhost:4502/crx/packmgr/service.jsp

I am also getting the same error when I try the curl Upload command
curl -u admin:admin -F package=@"dam-backup.zip" http://localhost:4502/crx/packmgr/service/.json/?cmd=upload

**Comment by escamoteur** [comment]
this isn't a flutter problem
