### ISSUE TITLE
Clip.antiAlias property  dose not working in ClipPath class on new update 1.7 flutter.

### ISSUE THREAD

**Issue by mitesh77** [flutter/flutter#37172]

**Comment by escamoteur** [comment]
Is this still a problem with the latest version?
if so, can you describe the problem more clearly possibly with a screenshot and your source code.
Also attach the out put of `flutter doctor`

**Comment by mitesh77** [comment]
sorry for the delay, it's working fine in new flutter 1.9.1

**Comment by mitesh77** [comment]
now I closed this issue.
