### ISSUE TITLE
build_benchmark_second_debug_build regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#37175]
Time's nearly doubled since https://github.com/flutter/flutter/commit/51d2d3511c11f6b101f97ff28864d204313b4e4b.

**Comment by jonahwilliams** [comment]
I've re re re disabled the kernel finger print due to https://github.com/flutter/flutter/issues/16604. This will be addressed via flutter assemble, but ultimately is not resolvable until that is landed

**Comment by franciscojma86** [comment]
Regression re-introduced by https://github.com/flutter/flutter/commit/99fe0d078b7698e8f6f0f51344fe6c67c29ae6c9. 
@jason-simmons

**Comment by franciscojma86** [comment]
after_config_change_build_debug_millis is also affected.

**Comment by jonahwilliams** [comment]
I'm removing this from benchmark, as it is due to a bug fix from above. It is not a today issue

**Comment by liyuqian** [comment]
Shall we close this as the benchmark is removed?

**Comment by liyuqian** [comment]
Closing this issue as the benchmark is removed and there's no objection of closing.
