### ISSUE TITLE
[webview_flutter] Support passing title of web page to Dart

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#37177]
Internal: b/138576954

Internal issue: b/138576428

Let's propagate these platform methods:
https://developer.apple.com/documentation/webkit/wkwebview/1415015-title
https://developer.android.com/reference/android/webkit/WebView.html#getTitle()

**Comment by mehmetf** [comment]
@amirh FYI

**Comment by niugengyun** [comment]
怎么解决？  how to fix?

**Comment by amirh** [comment]
Added in webview_flutter 0.3.12

**Comment by nichtverstehen** [comment]
The change has been reverted in https://github.com/flutter/plugins/pull/1981.

**Comment by cyanglaz** [comment]
@nichtverstehen This change seems to be re-landed in https://github.com/flutter/plugins/pull/2056. And I can see the related code in upstream.
I am going close this issue. Please feel free to reopen or post comment in the issue if it has not been fixed.
