### ISSUE TITLE
Last step of Firebase for Flutter Codelab doesn't work

### ISSUE THREAD

**Issue by Seanmyr** [flutter/flutter#37188]
I was following the Firebase for Flutter Codelab and everything was great up through step 10.  Everything worked great.  Then Step 11 (the last actual coding step) has one seemingly minor change.  It is making the firebase call be wrapped in a transaction.

At first I typed the changes myself.  Then I hot reloaded and tried the application because no errors came up.  When I would tap on a baby name to upvote it nothing happened.  So I rechecked what I typed several times and still could not get it to work.  So then I tried copy and paste of only the code that was changed in Step 11.  Still did not work.

Lastly I tried a copy and paste of the whole main.dart file because Step 11 gives the whole main.dart file for reference as to what it should look like.  Even then it still does not work.  I tried doing a search but could not find anything.  So at this point I have absolutely no idea why my flutter app, that is 
a copy and paste of the code from the actual codelab step 11, does not work.

Any help would greatly be appreciated.

Thanks

**Comment by djkowa** [comment]
same here

**Comment by Hixie** [comment]
cc @sfshaza2

**Comment by domesticmouse** [comment]
I believe this is for the retired Flutter for Firebase codelab that has been replaced by [Get to know Firebase for Flutter](https://firebase.google.com/codelabs/firebase-get-to-know-flutter)
