### ISSUE TITLE
Host add-to-app staging guides on Firebase

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#37197]
There is a staging branch which is accumulating guides for the new Android embedding, and possibly other add-to-app behavior:
https://github.com/flutter/website/tree/staging_add-to-app

This ticket is to setup a Firebase project to host the latest version of this staging branch so that we can share the current guide progress with team members and customers.

**Comment by matthew-carroll** [comment]
CC @xster @sfshaza2

**Comment by xster** [comment]
@sfshaza2 it looks like our staging branch was removed from the website repo. Do you know what happened to it?

**Comment by xster** [comment]
Re-fished out the orphaned commits back onto https://github.com/flutter/website/tree/staging-add-to-app

**Comment by xster** [comment]
Created project hosted at https://add-to-app-2019.web.app/. Added team to write access. This is done.
