### ISSUE TITLE
Java MethodChannel.error crashes when errorDetails is Exception

### ISSUE THREAD

**Issue by jklint-g** [flutter/flutter#37191]
The MethodChannel API for reporting errors from Java isn't very clear about what you can pass as `errorDetails`, and it's very tempting to write error-handling code which looks safe but will end up crashing the app.

For instance, we wrote several custom plugins with Java exception handling like:
```
catch (Exception e) {
  result.error(e.getClass().getName(), e.getMessage(), e);
}
```
This crashes at the Java level due to passing an Exception for the final arg `errorDetails`, which is an Object that MethodChannel just passes through to StandardMessageCodec for encoding ([1](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/plugin/common/MethodChannel.java#L230), [2](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/plugin/common/StandardMethodCodec.java#L70)). Since the codec doesn't support Exception types, it falls into [this case](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/plugin/common/StandardMessageCodec.java#L294) and throws.

The [docs](https://api.flutter.dev/javadoc/io/flutter/plugin/common/MethodChannel.Result.html#error-java.lang.String-java.lang.String-java.lang.Object-)  for MethodChannel.error could clarify that Object errorDetails can only be the usual channel-supported types, and not an Exception. Better though might be some explicit handling of Exception type in `encodeErrorEnvelope`, like getting a stacktrace string.

**Comment by mehmetf** [comment]
I like this suggestion, especially the last part. It is fairly common for Android developers to call logger functions with exceptions objects so that habit is hard to break. The platform channel implementation on Android should be able to handle these.

**Comment by mehmetf** [comment]
This has been fixed with https://critique-ng.corp.google.com/cl/338379561
