### ISSUE TITLE
[google_maps_flutter] Plugins Repo is 0.5.20+1 but NOT available from pub.dev

### ISSUE THREAD

**Issue by workerbee22** [flutter/flutter#37202]
pubspec.yaml of the google_maps_flutter package clearly shows the new version, but pub.dev has NOT been updated with this new version and is therefore unavailable to me.

Expected behaviour:
1. Flutter plugin version s available on pub.dev match the version in the plugin repo
2. Latest versions are available from pub.dev

**Comment by jmagman** [comment]
@iskakaushik

**Comment by iskakaushik** [comment]
@workerbee22 Done. Sorry for the delay here.

**Comment by workerbee22** [comment]
Thanks for the quick fix @iskakaushi. We can always reference the repo from pubspec.yaml, but thought I'd better point it out for others.
