### ISSUE TITLE
Dropdown extends off the top of the screen

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#3720]
## Steps to Reproduce

1. Have a dropdown at or near the top of your screen with >4 items in it
2. Select an item from near the bottom of the list.
3. Open the dropdown again.  The first item(s) will be unselectable.

**Comment by eseidelGoogle** [comment]
This occurred in an internal App, so here is a correspondingly internal screenshoot link (only viewable to google.com accounts): https://drive.google.com/a/google.com/file/d/0B2PCjPc6nmyrSXVOYU9LNHlPd1k/view?usp=sharing
