### ISSUE TITLE
firebase_auth _auth.onAuthStateChanged.listen() should pass in an AuthResult

### ISSUE THREAD

**Issue by lookfirst** [flutter/flutter#37215]
With the new api, shouldn't this method pass in an AuthResult instead of a FirebaseUser?

**Comment by lookfirst** [comment]
@collinjackson ?

**Comment by collinjackson** [comment]
On iOS the equivalent notification gets a user rather than an `AuthResult` so I think we should do the same.

```
typedef void (^FIRAuthStateDidChangeListenerBlock)(FIRAuth *_Nonnull,
                                                   FIRUser *_Nullable)
```

**Comment by lookfirst** [comment]
Here is my train of thought, correct me if I'm wrong:

Sign in and Creation now return an `AuthResult` instead of a `FirebaseUser`. I figure that this was changed in order to pass back `AdditionalUserInfo` since that is the only extra field in `AuthResult` right now.

```
    final AuthResult authResult = await _auth.signInWithEmailAndPassword(email: username, password: password);

    final AuthResult authResult = await _auth.createUserWithEmailAndPassword(email: username, password: password);
```

I would think that updates to this same data as a result of a state change via `onAuthStateChanged` would also result in an `AuthResult` in order to retrieve any updated `AdditionalUserInfo` (which is the extra information contained in the AuthResult). In the same way that `signInWithEmailAndPassword` returns an `AuthResult` now.

Currently, `onAuthStateChanged` is only signin/signout events, but I could see it also containing updated `AdditionalUserInfo` when that information changes as well. Otherwise, how would my app know that any `AdditionalUserInfo` has changed?

Hope this explains things a bit further.

**Comment by kroikie** [comment]
@lookfirst

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1088. Any further collaboration will be done there.
