### ISSUE TITLE
The google reports through android studio directed me here guys so i guess it's a new issue, My project is adding data to the firestore but can't retrieve it and wrote my code right i guess!!!

### ISSUE THREAD

**Issue by abddi** [flutter/flutter#37214]
crud.dart
import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

[class crudMedthods {
  String userID;
  bool isLoggedIn() {
    if (FirebaseAuth.instance.currentUser() != null) {
      return true;
    } else {
      return false;
    }
  }
//================= For SignUp =====================
  Future<void> signUpData(signUpData) async {
    await FirebaseAuth.instance.currentUser().then((user)
{
userID = user.uid;
}).then((result){
      Firestore.instance.collection('vendors').document(userID).collection('data').add(signUpData);}).catchError((e) {
        print(e);
      });
  }
//================= For CreateD ================
  Future<void> createDiscountData(createData) async {
   await FirebaseAuth.instance.currentUser().then((user){userID = user.uid;}).then((result){
      Firestore.instance.collection('vendors').document(userID).collection('discount').add(createData);}).catchError((e) {
      print(e);
    });
  }
//======================= For SignUp ==================
  getSignUpData() async {
    return await Firestore.instance.collection('vendors').document(userID).collection('data').snapshots();
  }

  //================= For CreateD ====================
  getDiscountData() async {
    return await Firestore.instance.collection('vendors').document(userID).collection('discount').snapshots();
  }

  updateData(selectedDoc, newValues){
    Firestore.instance.collection(userID).document(selectedDoc).updateData(newValues).catchError((e){
      print(e);
    });
  }

  deleteData(docId){
    Firestore.instance.collection(userID).document(docId).delete().catchError((e){
      print(e);
    });
  }
}](url)
sigunUp.dart
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:dapp_v/signup_login/login.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:dapp_v/model/data.dart';
import 'package:dapp_v/services/crud.dart';
import 'package:dapp_v/pages/CreateD.dart';

[class SignUp extends StatefulWidget {

  @override
  _SignUpState createState() => _SignUpState();
}

[class _SignUpState extends State<SignUp> {
  DataModel model = DataModel();
  crudMedthods crudObj = crudMedthods();
//================ For CheckBox ================
  bool isCheked = false;
 //============== Those are for the Firebase Auth ==========================
  String _email, _password;
//=============== Those for Firestore =====================

  //String  name, phone, email,coNumber;
   final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
          appBar: AppBar(
            title: Text('Signup', style: TextStyle(color: Colors.black),),
            backgroundColor: Colors.white,
            centerTitle: true,
          ),
      body: Form(
        key: _formKey,
        child:
              Padding(
                padding: const EdgeInsets.all(20.0),
                child: ListView(
                  children: <Widget>[
                    SizedBox(height: 30.0),
                    Image.asset('logo/logo.jpg',height: 70.0, width: 70.0,),
                    SizedBox(height: 20.0,),
                    Column(
                      children: <Widget>[

                         TextFormField(
                            decoration: InputDecoration(
                            labelText: 'Co. name',
                             icon: Icon(Icons.business),
                        ),
                          keyboardType: TextInputType.text,
                          // ignore: missing_return
                          validator: (input){
                            if(input.isEmpty){
                                return 'Co. name field cannot be empty';
                            }
                          },
                            onChanged: (value){
                             model.name = value;
                                     },
                         ),
                          TextFormField(
                          decoration: InputDecoration(
                          labelText: 'Phone',
                          icon: Icon(Icons.phone_android),
                          ),
                          keyboardType: TextInputType.number,
                          // ignore: missing_return
                          validator: (input){
                          if(input.isEmpty){
                          return 'Phone field cannot be empty';
                          }else if (input.length<10){
                          return 'Phone should be at least 10 characters';
                          }
                          },
                          onChanged: (value){
                            model.phone = value;
                          },
                          ),
                          TextFormField(
                          decoration: InputDecoration(
                          labelText: 'Email',
                          icon: Icon(Icons.email),
                          ),
                          keyboardType: TextInputType.emailAddress,
                          // ignore: missing_return
                          validator: (input){
                          if(input.isEmpty){
                          return 'Email field cannot be empty';
                          }
                          },
                           onSaved: (input)=> _email = input,
                            onChanged: (value){
                              model.email = value;
                          },
                          ),
                          TextFormField(
                              decoration: InputDecoration(
                              labelText: 'Password',
                               icon: Icon(Icons.lock),
                                ),
                                  // ignore: missing_return
                                  validator: (input){
                                     if(input.isEmpty){
                                       return 'Password field cannot be empty';
                                     }else if(input.length<6){
                                         return 'Password should be at least  6 characters';
                                     }
                                   },
                                       onSaved: (input)=> _password = input,
                                          obscureText: true,
                          ),
                          TextFormField(
                               decoration: InputDecoration(
                                 labelText: 'Co. national number',
                                  icon: Icon(Icons.folder_shared),
                            ),
                                keyboardType: TextInputType.number,
                            // ignore: missing_return
                                 validator: (input){
                                   if(input.isEmpty){
                                     return 'Co. national number field cannot be empty';
                                   }else if(input.length<10){
                                      return 'Co. national number should be at least 10 characters';
                                   }
                                   },
                                        onChanged: (value){
                                          model.coNumber = value;
                                     },
                          ),

                        SizedBox(height: 10.0,),
                          ],
                        ),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: <Widget>[
                           RaisedButton(
                                  onPressed: (){
                                  addData();
                              },
                                  child: Text('Signup'),
                              color: Colors.green,
                              textColor: Colors.white,
                              ),
                          ],
                        ),
                    ],
                  ),
        ),
            ),
    );
  }
  Future <void> addData() async{
    if(_formKey.currentState.validate()){
      _formKey.currentState.save();
      try{
        FirebaseUser user = await FirebaseAuth.instance.createUserWithEmailAndPassword(email: _email, password: _password);
    //    user.sendEmailVerification();
            crudObj.signUpData(({
            'Co. name': model.name,
            'Phone': model.phone,
            'Email': model.email,
            'Co. national number': model.coNumber
          })).catchError((e){
          print(e);
        });

        Navigator.of(context).push(MaterialPageRoute(builder: (BuildContext context)=> Login()));
      }catch(e){
        print(e.message);
      }

    }
  }
}
profile.dart
want to retrieve the data from signUp.dart here
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:dapp_v/model/data.dart';
import 'package:dapp_v/services/crud.dart';
import 'dart:async';

class Profile extends StatefulWidget {
  @override
  _ProfileState createState() => _ProfileState();
}

class _ProfileState extends State<Profile> {
  crudMedthods crudObj = crudMedthods();
  var info;
  @override
  void initState() {
    crudObj.getSignUpData().then((results) {
      setState(() {
        info = results;
      });
    });
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Profile'),
        centerTitle: true,
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.refresh),
            onPressed: () {
              crudObj.getSignUpData().then((results) {
                setState(() {
                  info = results;
                });
              });
            },
          )
        ],
      ),
      body: _profile(),
    );
  }

  Widget _profile(){
    if(info != null){
          return StreamBuilder(
            stream: info,
            builder: (context, snapshot){
              return ListView.builder(
                  itemCount: snapshot.data.documents.length,
                  padding: EdgeInsets.all(5.0),
                  itemBuilder: (context, i){
                    return  Column(
                        children: <Widget>[
                          Text(snapshot.data.documents[i].data['Co. name']),
                          Text(snapshot.data.documents[i].data['Phone']),
                          Text(snapshot.data.documents[i].data['Email']),
                          Text(snapshot.data.documents[i].data['Co. national number']),
                        ],
                    );
                  }
              );
            },
          );
    }else{
      return Center(child: Text('Loading......'));
    }
  }

}
CreateD.dart
adding and retrieving data in the same page through dialogs
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:dapp_v/services/crud.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:dapp_v/signup_login/signup.dart';
import 'package:dapp_v/model/data.dart';
class CreateD extends StatefulWidget {
  @override
  _CreateDState createState() => _CreateDState();
}

class _CreateDState extends State<CreateD> {

  crudMedthods crudObj = crudMedthods();
  DataModel model = DataModel();
  var createD;

 // crudMedthods crudObj = crudMedthods();

  //============================= Create (Add) =================================
  Future<bool> addDialog(BuildContext context) async {
    return showDialog(
        context: context,
        barrierDismissible: false,
        builder: (BuildContext context) {
          return AlertDialog(
            title: Text('Add Discount', style: TextStyle(fontSize: 15.0)),
            content: ListView(
              children: <Widget>[
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Column(
                    children: <Widget>[
                      TextField(
                        decoration: InputDecoration(hintText: 'Branch'),
                        onChanged: (value) {
                          model.branch = value;
                        },
                      ),
                      SizedBox(height: 5.0),
                      TextField(
                        decoration: InputDecoration(hintText: 'Discount'),
                        onChanged: (value) {
                          model.discount = value;
                        },
                      ),
                      SizedBox(height: 5.0),
                      TextField(
                        decoration: InputDecoration(hintText: 'Social media'),
                        onChanged: (value) {
                          model.socialMedia = value;
                        },
                      ),
                      SizedBox(height: 5.0),
                      TextField(
                        decoration: InputDecoration(hintText: 'App web link'),
                        onChanged: (value) {
                         model.appWebLink = value;
                        },
                      ),
                    ],
                  ),
                ),
              ],
            ),
            actions: <Widget>[
              FlatButton(
                child: Text('Add'),
                textColor: Colors.blue,
                onPressed: () {
                  Navigator.of(context).pop();
                 inputData().then((value){
                   dialogTrigger(context);
                 });
                },
              )
            ],
          );
        });
  }
  Future<bool> dialogTrigger(BuildContext context) async {
    return showDialog(
        context: context,
        barrierDismissible: false,
        builder: (BuildContext context) {
          return AlertDialog(
            title: Text('Job Done', style: TextStyle(fontSize: 15.0)),
            content: Text('Added'),
            actions: <Widget>[
              FlatButton(
                child: Text('ok'),
                textColor: Colors.blue,
                onPressed: () {
                  Navigator.of(context).pop();
                },
              )
            ],
          );
        });
  }

  @override
  void initState() {
   crudObj.getDiscountData().then((results) {
      setState(() {
        createD = results;
      });
    });
    super.initState();
  }
  //==================== Update data =============================
  Future<bool> updateDialog(BuildContext context, selectedDoc) async {
    return showDialog(
        context: context,
        barrierDismissible: false,
        builder: (BuildContext context) {
          return AlertDialog(
            title: Text('Update Data', style: TextStyle(fontSize: 15.0)),
            content: Column(
              children: <Widget>[
                TextField(
                  decoration: InputDecoration(hintText: 'Enter Branch'),
                  onChanged: (value) {
                    model.branch = value;
                  },
                ),
                SizedBox(height: 5.0),
                TextField(
                  decoration: InputDecoration(hintText: 'Enter Discount'),
                  onChanged: (value) {
                    model.discount = value;
                  },
                ),
                SizedBox(height: 5.0),
                TextField(
                  decoration: InputDecoration(hintText: 'Social media'),
                  onChanged: (value) {
                    model.socialMedia = value;
                  },
                ),
                SizedBox(height: 5.0),
                TextField(
                  decoration: InputDecoration(hintText: 'App/Web link'),
                  onChanged: (value) {
                    model.appWebLink = value;
                  },
                ),
              ],
            ),
            actions: <Widget>[
              FlatButton(
                child: Text('Update'),
                textColor: Colors.blue,
                onPressed: () {
                  Navigator.of(context).pop();
//                  updateData(selectedDoc,{
//                    'Branch': model.branch,
//                    'Discount': model.discount,
//                    'Social media': model.socialMedia,
//                    'App web link': model.appWebLink
//                  }).then((result) {
//                    dialogTrigger(context);
//                  }).catchError((e) {
//                    print(e);
//                  });
                },
              )
            ],
          );
        });
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Discount'),
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.add),
            onPressed: () {
              addDialog(context);
            },
          ),
          IconButton(
            icon: Icon(Icons.refresh),
            onPressed: () {
              crudObj.getDiscountData();
            },
          )
        ],
      ),
      body: _createList(),
    );
  }
  Widget _createList() {
    if (createD != null) {
      return StreamBuilder(
        stream: createD,
        builder: (context, snapshot){
          return ListView.builder(
              itemCount: snapshot.data.documents.length,
              itemBuilder: (context, i){
                return Padding(padding: EdgeInsets.all(8.0),
                  child: Column(
                    children: <Widget>[
                      Text(snapshot.data.documents[i].data['Branch']),
                      Text(snapshot.data.documents[i].data['Discount']),
                      Text(snapshot.data.documents[i].data['Social media']),
                      Text(snapshot.data.documents[i].data['App/Web link']),
                    ],
                  ),
                );
              });
        },
      );
    }else{
      return  Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          CircularProgressIndicator(),
          Text('Loading.....')
        ],
      );
    }
  }
  Future<void> inputData()async{
    return await crudObj.createDiscountData(({
      'Branch': model.branch,
      'Discount': model.discount,
      'Social media': model.socialMedia,
      'App/Web link': model.appWebLink
    })).catchError((e){
      print(e);
    });
  }

}

 here is the error:
I/flutter (13488): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13488): The following NoSuchMethodError was thrown building StreamBuilder<dynamic>(dirty, state:
I/flutter (13488): _StreamBuilderBaseState<dynamic, AsyncSnapshot<dynamic>>#21863):
I/flutter (13488): The getter 'documents' was called on null.
I/flutter (13488): Receiver: null
I/flutter (13488): Tried calling: documents
I/flutter (13488): When the exception was thrown, this was the stack:
I/flutter (13488): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter (13488): #1      _ProfileState._profile.<anonymous closure> (package:dapp_v/pages/Profile.dart:54:44)
I/flutter (13488): #2      StreamBuilder.build (package:flutter/src/widgets/async.dart:425:74)
I/flutter (13488): #3      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:125:48)
I/flutter (13488): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4021:27)
I/flutter (13488): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3933:15)
I/flutter (13488): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (13488): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3916:5)
I/flutter (13488): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4062:11)
I/flutter (13488): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3911:5)
I/flutter (13488): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
I/flutter (13488): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2896:12)
I/flutter (13488): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3944:16)
I/flutter (13488): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (13488): #14     ProxyElement.update (package:flutter/src/widgets/framework.dart:4228:5)
I/flutter (13488): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (13488): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3944:16)
I/flutter (13488): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (13488): #18     ProxyElement.update (package:flutter/src/widgets/framework.dart:4228:5)
I/flutter (13488): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (13488): #20     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4826:32)
I/flutter (13488): #21     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5217:17)
I/flutter (13488): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (13488): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3944:16)
I/flutter (13488): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (13488): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:4094:5)
I/flutter (13488): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (13488): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3944:16)
I/flutter (13488): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (13488): #29     ProxyElement.update (package:flutter/src/widgets/framework.dart:4228:5)
I/flutter (13488): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (13488): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3944:16)
I/flutter (13488): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (13488): #33     StatefulElement.update (package:flutter/src/widgets/framework.dart:4094:5)
I/flutter (13488): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (13488): #35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5108:14)
I/flutter (13488): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (13488): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3944:16)
I/flutter (13488): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (13488): #39     StatelessElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (13488): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (13488): #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5108:14)
I/flutter (13488): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (13488): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3944:16)
I/flutter (13488): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (13488): #45     StatefulElement.update (package:flutter/src/widgets/framework.dart:4094:5)
I/flutter (13488): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (13488): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3944:16)
I/flutter (13488): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (13488): #49     StatefulElement.update (package:flutter/src/widgets/framework.dart:4094:5)
I/flutter (13488): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (13488): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3944:16)
I/flutter (13488): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (13488): #53     ProxyElement.update (package:flutter/src/widgets/framework.dart:4228:5)
I/flutter (13488): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (13488): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3944:16)
I/flutter (13488): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (13488): #57     ProxyElement.update (package:flutter/src/widgets/framework.dart:4228:5)
I/flutter (13488): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (13488): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3944:16)
I/flutter (13488): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (13488): #61     StatefulElement.update (package:flutter/src/widgets/framework.dart:4094:5)
I/flutter (13488): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (13488): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3944:16)
I/flutter (13488): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (13488): #65     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
I/flutter (13488): #66     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (13488): #67     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (13488): #68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1032:15)
I/flutter (13488): #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:974:9)
I/flutter (13488): #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:890:5)
I/flutter (13488): #74     _invoke (dart:ui/hooks.dart:236:10)
I/flutter (13488): #75     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter (13488): (elided 3 frames from package dart:async)
I/flutter (13488): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (13488): Another exception was thrown: NoSuchMethodError: The getter 'documents' was called on null.

**Comment by abddi** [comment]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.8.1, on Microsoft Windows [Version 10.0.17763.615], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code (version 1.36.1)
[√] Connected device (1 available)

• No issues found!

**Comment by tapizquent** [comment]
Have you set up the permissions for read and write correctly in the database ? Make sure you include your “vendors” collection in there’s

**Comment by abddi** [comment]
> Have you set up the permissions for read and write correctly in the database ? Make sure you include your “vendors” collection in there’s

yes you can find it in the crud.dart i have posted in my first comment section

**Comment by escamoteur** [comment]
Please ask this here https://github.com/FirebaseExtended/flutterfire
