### ISSUE TITLE
Ordinal day 1th 2nd, in DateTime or DateFormat

### ISSUE THREAD

**Issue by amreniouinnovent** [flutter/flutter#37221]
## Use case

I want to get the ordinal number of the day of the month but DateFormat doesn't support this feature.

## Proposal
I wonder if you could support ordinal number for the day of the month
1st, 2nd,3rd,4th, 21st, etc

I used a function but I think DateFormat should support it

```
  String today() {
    final DateTime now = DateTime.now();
    String suffix = 'th';
    final int digit = now.day % 10;
    if ((digit > 0 && digit < 4) && (now.day < 11 || now.day > 13)) {
      suffix = <String>['st', 'nd', 'rd'][digit - 1];
    }
    return DateFormat("E, MMM d'$suffix'").format(now); // 'Sun, Jun 30th'
  }
```

**Comment by BondarenkoStas** [comment]
@amreniouinnovent the DateFormat class belongs to dart intl library, which is just used by flutter. I can not move it there, so please file a proposal by yourself to https://github.com/dart-lang/intl/issues.

**Comment by toxaq** [comment]
So this is Ouroboros? https://github.com/dart-lang/intl/issues/226
