### ISSUE TITLE
FCM Large Icon

### ISSUE THREAD

**Issue by DagobertDokate** [flutter/flutter#37228]
How to set the large icon on a fcm message?

I set the small icon via ` <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_notification" />`

But how to set the big one?

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.

**Comment by fenchai23** [comment]
@DagobertDokate did you ever figure this out? I'm searching like crazy and there is not a single soul asking for this but you... aaaand it's closed.
