### ISSUE TITLE
Stepper: Custom Connector Line Colours

### ISSUE THREAD

**Issue by Kyaw-Zin-Thant** [flutter/flutter#37229]
I want to change custom colour in material stepper.

**Comment by Hixie** [comment]
@mub-pro wrote a PR to address this: https://github.com/flutter/flutter/pull/97576 
Unfortunately it was not completed (it has some outstanding review comments) so the PR has been closed. If anyone would like to start from that PR and apply the review comments and drive this PR to completion, you are definitely welcome to do so!
