### ISSUE TITLE
After running flutter doctor I get the following error

### ISSUE THREAD

**Issue by michaelodafe** [flutter/flutter#37223]
After installing flutter (putting the files in my C drive), I tried running the command "flutter doctor" on the terminal but I got the below error. Please help me out with a fix.

C:\Users\Michael Odafe>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.885], locale en-US)
\CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

Command: C:\Users\Michael Odafe\AppData\Local\Android\sdk\platform-tools\adb.EXE devices -l
#0      _ProcessImpl._runAndWait (dart:io/runtime/binprocess_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io/runtime/binprocess_patch.dart:634:18)
#2      Process.runSync (dart:io/runtime/binprocess_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:325:48)
#5      runSync (package:flutter_tools/src/base/process.dart:299:10)
#6      getAdbDevices (package:flutter_tools/src/android/android_device.dart:545:12)
#7      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:55:53)
<asynchronous suspension>
#8      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:171:52)
<asynchronous suspension>
#9      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:99:46)
<asynchronous suspension>
#10     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:694:54)
<asynchronous suspension>
#11     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#12     Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
#13     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:179:24)
#15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#16     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#25     Future._complete (dart:async/future_impl.dart:473:7)
#26     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#27     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#33     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by blasten** [comment]
Looks like this issue was fixed by https://github.com/flutter/flutter/pull/37196. cc @zanderso

**Comment by michaelodafe** [comment]
> Looks like this issue was fixed by #37196. cc @zanderso

I get the following error after doing all he instructed

C:\Users\Michael Odafe>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.885], locale en-US)
\CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\Michael Odafe\AppData\Local\Android\sdk\platform-tools\adb.EXE devices -l
#0      _ProcessImpl._runAndWait (dart:io/runtime/binprocess_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io/runtime/binprocess_patch.dart:634:18)
#2      Process.runSync (dart:io/runtime/binprocess_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:325:48)
#5      runSync (package:flutter_tools/src/base/process.dart:299:10)
#6      getAdbDevices (package:flutter_tools/src/android/android_device.dart:545:12)
#7      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:55:53)
<asynchronous suspension>
#8      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:171:52)
<asynchronous suspension>
#9      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:99:46)
<asynchronous suspension>
#10     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:694:54)
<asynchronous suspension>
#11     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#12     Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
#13     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:179:24)
#15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#16     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#25     Future._complete (dart:async/future_impl.dart:473:7)
#26     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#27     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#33     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by zanderso** [comment]
This looks like it is probably a different issue. This doc might be relavent: https://support.microsoft.com/en-us/help/812486/event-id-7000-and-1-is-not-a-valid-win32-application-error-message-whe

@michaelodafe could we trouble you to try moving your Android SDK to a path without a space in it?

**Comment by michaelodafe** [comment]
> This looks like it is probably a different issue. This doc might be relavent: https://support.microsoft.com/en-us/help/812486/event-id-7000-and-1-is-not-a-valid-win32-application-error-message-whe
> 
> @michaelodafe could we trouble you to try moving your Android SDK to a path without a space in it?

Hello @zanderso Thank you very much, I figured that out yesterday and then ran into a new problem

**Trying to run flutter on my emulator and ran into this problem**

Launching lib\main.dart on Android SDK built for x86 in debug mode...
[{"event":"app.progress","params":{"appId":"388e08e0-3eab-4353-a94f-41784b36b253","id":"0","progressId":null,"message":"Initializing gradle..."}}]Initializing gradle...

Finished with error: ProcessException: Process "C:\android\flutterprojects\flutter_appplswork\android\gradlew.bat" exited abnormally:
Unzipping C:\Users\Michael Odafe.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2-all.zip to C:\Users\Michael Odafe.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.(ZipFile.java:219)
at java.util.zip.ZipFile.(ZipFile.java:149)
at java.util.zip.ZipFile.(ZipFile.java:163)
at org.gradle.wrapper.Install.unzip(Install.java:214)
at org.gradle.wrapper.Install.access$600(Install.java:27)
at org.gradle.wrapper.Install$1.call(Install.java:74)
at org.gradle.wrapper.Install$1.call(Install.java:48)
at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
at org.gradle.wrapper.Install.createDist(Install.java:48)
at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Command: C:\android\flutterprojects\flutter_appplswork\android\gradlew.bat -v

Please help me out with a fix!

**Comment by zanderso** [comment]
We're tracking the ZipException here: https://github.com/flutter/flutter/issues/36282

**Comment by blasten** [comment]
If you try to delete the file `C:\Users\Michael Odafe.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2-all.zip` and then try again, does that fix the issue?  It's possible that the file got corrupted.

**Comment by michaelodafe** [comment]
> If you try to delete the file `C:\Users\Michael Odafe.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2-all.zip` and then try again, does that fix the issue? It's possible that the file got corrupted. Also related to: #13645.

Thank you! I just did that and got the below error..

Launching lib\main.dart on Android SDK built for x86 in debug mode...
[{"event":"app.progress","params":{"appId":"9b2d16a7-4f89-48b1-b618-8b05e224ccef","id":"0","progressId":null,"message":"Initializing gradle..."}}]Initializing gradle...

[{"event":"app.progress","params":{"appId":"9b2d16a7-4f89-48b1-b618-8b05e224ccef","id":"1","progressId":null,"message":"Resolving dependencies..."}}]Resolving dependencies...

[{"event":"app.progress","params":{"appId":"9b2d16a7-4f89-48b1-b618-8b05e224ccef","id":"2","progressId":null,"message":"Running Gradle task 'assembleDebug'..."}}]Running Gradle task 'assembleDebug'...

Built build\app\outputs\apk\debug\app-debug.apk.
CreateProcessW failed 193
Finished with error: ProcessException: %1 is not a valid Win32 application.

  Command: C:\android\Sdk\build-tools\28.0.3\aapt.EXE dump xmltree C:\android\flutterprojects\flutter_biko\build\app\outputs\apk\app.apk AndroidManifest.xml

**Comment by blasten** [comment]
It might be that the `ANDROID_HOME `env variable has spaces in the path.
This issue: https://stackoverflow.com/a/53232266.

**Comment by michaelodafe** [comment]
FIXED!!! I actually needed to reinstall my SDK Build Tool v28.0.3 again... Thank you for your help without your first hint I won't have gone this far... 

> If you try to delete the file `C:\Users\Michael Odafe.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2-all.zip` and then try again, does that fix the issue? It's possible that the file got corrupted. Also related to: #13645.

**Comment by blasten** [comment]
The issue about spaces in the Android SDK path is being tracked here: https://github.com/flutter/flutter/issues/19359
