### ISSUE TITLE
Remove firebase from the engine build rules and repo

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3722]
We still have an `//engine/src/sky/services/firebase` directory and corresponding rules in the BUILD.gn.

cc @collinjackson @mpcomplete

**Comment by Hixie** [comment]
Also GCM and google_sign_in which are in the BUILD.gn file.

**Comment by collinjackson** [comment]
https://codereview.chromium.org/1970403002

**Comment by collinjackson** [comment]
assigned to @jamesr for review

**Comment by jamesr** [comment]
Done but I'm not sure if I have all the powers you need there.

**Comment by collinjackson** [comment]
@jason-simmons

**Comment by sethladd** [comment]
Hi! Did we finish this?

**Comment by jason-simmons** [comment]
This should be done now.  GCM was removed last week.
