### ISSUE TITLE
firebase_auth build warnings in xcode

### ISSUE THREAD

**Issue by lookfirst** [flutter/flutter#37230]
Personally, I'm a fan of a clean build. Broken window theory and all.

firebase_auth v0.14.0

![image](https://user-images.githubusercontent.com/85355/62123222-aa90f580-b2f1-11e9-9826-0b7448d23328.png)

**Comment by jmagman** [comment]
Surprisingly I don't see a duplicate for this.

**Comment by lookfirst** [comment]
Surprisingly I don't see a build failure from CI. ;-)

**Comment by kroikie** [comment]
@lookfirst

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1087. Any further collaboration will be done there.
