### ISSUE TITLE
E/com.difrancescogianmarco.arcore_flutter_plugin.RenderableCustomFactory: Unable to load Renderable.     java.util.concurrent.CompletionException: java.io.FileNotFoundException: ArcticFox_Posed.sfb (No such file or directory)

### ISSUE THREAD

**Issue by Taimoors95** [flutter/flutter#37233]
I am trying to run this code https://github.com/giandifra/arcore_flutter_plugin/blob/master/example/lib/screens/assets_object.dart
but after the plane is detected and I select the object from the list, its giving me error that no sfb file is found

**Comment by miyoyo** [comment]
This should not be in this repository, that issue is either a missing asset, or should be over to that repository.
