### ISSUE TITLE
Add COMPILER_INDEX_STORE_ENABLE=NO to Xcode build arguments

### ISSUE THREAD

**Issue by andrijasinski** [flutter/flutter#37231]
This issue is triggered due to an inability to pass Xcode build arguments to flutter build ios command. 

## Use case
Indexing in Xcode is used mostly for
 - Autocomplete
 - Ability to quickly jump to definition
 - Get class and method help by alt clicking.

None of these are necessary to run builds in a CI environment and disabling indexing has shown significant improvement in build speeds for developers.
* https://twitter.com/steipete/status/1100404024224804871?lang=en

## Proposal
To improve the performance of flutter build process in CI environment I suggest adding `buildCommands.add('COMPILER_INDEX_STORE_ENABLE=NO');` line to `packages/flutter_tools/lib/src/ios/mac.dart:182-284` and add this line in case if environment variable `CI` exists and equals to `true`. Moreover, I would like to also suggest adding support for any kind of additional arguments for `xcodebuild` command. For example, execution of `flutter build ios -- FOO=BAR` will end up in `xcrun xcodebuild ... FOO=BAR`.

**Comment by jmagman** [comment]
Fixed with https://github.com/flutter/flutter/pull/37378.
