### ISSUE TITLE
Error loading some .gif images

### ISSUE THREAD

**Issue by yuanbinbinbin** [flutter/flutter#37235]
## Description
`
Image.network("http://koalareading-online.oss-cn-beijing.aliyuncs.com/images/n1.gif")
`

The first load is normal，but only one of frames is displayed when you jump from the current page to another page and return.

When returning from other pages, I think it should show the last frame or start animation from the first frame.

****Attention**：_The number of repetitionCount of the GIF image is one。_**

## Repetition
[GIF](https://github.com/yuanbinbinbin/yuanbinbinbin.github.io/blob/master/images/video2gif_20190730_191526.gif)

[Video](https://github.com/yuanbinbinbin/yuanbinbinbin.github.io/blob/master/images/Screenrecorder-2019-07-30-19-14-07-508.mp4)

## Code
```
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: GifTest(),
    );
  }
}
```
```
class GifTest extends StatefulWidget {
  @override
  _GifTestState createState() => _GifTestState();
}

class _GifTestState extends State<GifTest> {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: GestureDetector(
        child: Center(
          child: Image.network(
            "http://koalareading-online.oss-cn-beijing.aliyuncs.com/images/n1.gif",
          ),
        ),
        onTap: () {
          Navigator.of(context).push(
            MaterialPageRoute(builder: (context) {
              return Container(
                color: Colors.red,
              );
            }),
          );
        },
      ),
    );
  }
}
```

## Step
1. Run my code
2. You will see that GIF will play normally at the first time.
3. Click GIF，go to the page with a red background.
4. Return from the red page.
5. Check if GIF is normal.

## flutter doctor -v
```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.829], locale zh-CN)
    • Flutter version 1.7.8+hotfix.4 at C:\software\flutter\flutter
    • Framework revision 20e59316b8 (11 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\software\androidsdk\android-sdk_r24.4.1-windows\android-sdk-windows
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\software\androidstudio\android-studio-ide-173.4697961-windows_3.1\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Android Studio (version 3.1)
    • Android Studio at C:\software\androidstudio\android-studio-ide-173.4697961-windows_3.1\android-studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected device (1 available)
    • MI 8 • b4a02273 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by BaderEddineOuaich** [comment]
You have to trigger the initState() and load the gif inside it. so whenever the widget initialized it will load the gif as its first time.

<pre>
class GifTest extends StatefulWidget {
  @override
  _GifTestState createState() => _GifTestState();
}

class _GifTestState extends State<GifTest>
 {
 var gif;

 @override
 void initState()
 {
    gif = Image.network("http://koalareading-online.oss-cn-beijing.aliyuncs.com/images/n1.gif");
    super.initState();
 }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: GestureDetector(
        child: Center(
          child: gif
        ),
        onTap: () {
          Navigator.of(context).push(
            MaterialPageRoute(builder: (context) {
              return Container(
                color: Colors.red,
              );
            }),
          );
        },
      ),
    );
  }
}
</pre>

**Comment by yuanbinbinbin** [comment]
@BaderEddineOuaich 
Thanks for your reply，but your method doesn't work.

## Step
1. Run my code or your code
2. You will see that GIF will play normally at the first time.
3. Click GIF，go to the page with a red background.
4. Return from the red page.
5. Check if GIF is normal.

**Comment by BaderEddineOuaich** [comment]
Hi there, i tried the code. you're right. it wasn't working. i come up with this solution. looks just fine for me. clearing the image cache before pushing another widget will make the gif load again. here is the complete code.


<pre>
class GifTest extends StatefulWidget {
  @override
  _GifTestState createState() => _GifTestState();
}

class _GifTestState extends State<GifTest> 
{
  

  @override
  Widget build(BuildContext context) 
  {
    return Container(
      child: GestureDetector(
        child: Center(
          child:<strong>Image.network("http://koalareading-online.oss-cn-beijing.aliyuncs.com/images/n1.gif",
            loadingBuilder: (BuildContext ctx, Widget gif, ImageChunkEvent loadingProgress)
            {
              if(loadingProgress?.cumulativeBytesLoaded == loadingProgress?.expectedTotalBytes)
              {
                return gif;
              }
              return CircularProgressIndicator();
            }),</strong>
        ),
        onTap: () {
          Navigator.of(context).push(
            MaterialPageRoute(builder: (context)
             { 
            <strong>
             //clear cache
              imageCache.clear();
             </strong>
              return Container(
                color: Colors.red,
              );
            }),
          );
        },
      ),
    );
  }
}
</pre>


_I hope it helps, have a nice day!_

**Comment by BaderEddineOuaich** [comment]
Hi there, i tried the code. you're right. it wasn't working. i come up with this solution. works just fine for me. clearing the image cache before pushing another widget will make the gif load again. here is the complete code.


<pre>
class GifTest extends StatefulWidget {
  @override
  _GifTestState createState() => _GifTestState();
}

class _GifTestState extends State<GifTest> 
{
  

  @override
  Widget build(BuildContext context) 
  {
    return Container(
      child: GestureDetector(
        child: Center(
          child:<strong>Image.network("http://koalareading-online.oss-cn-beijing.aliyuncs.com/images/n1.gif",
            loadingBuilder: (BuildContext ctx, Widget gif, ImageChunkEvent loadingProgress)
            {
              if(loadingProgress?.cumulativeBytesLoaded == loadingProgress?.expectedTotalBytes)
              {
                return gif;
              }
              return CircularProgressIndicator();
            }),</strong>
        ),
        onTap: () {
          Navigator.of(context).push(
            MaterialPageRoute(builder: (context)
             { 
            <strong>
             //clear cache
              imageCache.clear();
             </strong>
              return Container(
                color: Colors.red,
              );
            }),
          );
        },
      ),
    );
  }
}
</pre>


_I hope it helps, have a nice day!_

**Comment by escamoteur** [comment]
Have you tried to `await` the push of the page and after that call `setState`?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
