### ISSUE TITLE
Add support for APNG (Animated PNG)

### ISSUE THREAD

**Issue by ndac-todoroki** [flutter/flutter#37247]
## Use case

I want to create a animation picture viewer, and many of the contents are APNG.
APNG is a standard and most of the modern browsers (Firefox, Chrome, Safari and iOS supports it), has good binary size compression compared to GIF, is more colourful, and artists love PNG!

## Proposal

It would be great if the `Image` widget supports APNG out of the box. Currently it supports PNG, so the first frame of the file will be shown (APNG has backward compatibility for PNG).

**Comment by premingiet** [comment]
Is there any progress regarding APNG support ? I currently feel like i need it a lot. Why is APNG format not supported in image widget out of the box ? Its a very common format.

**Comment by aminjoharinia** [comment]
we are waiting for APNG support :)

**Comment by justinperezd** [comment]
still waiting for the apng support

**Comment by sveinbjornt** [comment]
I, too, would like to see APNG support!

**Comment by hienlh** [comment]
Waiting!

**Comment by daniuwo** [comment]
Looking forward to seeing apng support!

**Comment by apwilson** [comment]
+1 for apng support.

In addition as part of the API I'd like to see:
1. a callback where we can trigger something to happen after the Nth frame of the animation
2. a callback when the animation is done.

**Comment by kf6gpe** [comment]
(for triage) @cbracken How's this looking for the October milestone? I've had conversations with `customer: dream (g3)` and they're interested in this too.

**Comment by cbracken** [comment]
I suspect this will slip by a couple weeks to mid-Nov. It is WIP but there's a lot of edge-cases to test in the [spec](https://wiki.mozilla.org/APNG_Specification).

**Comment by wanjm** [comment]
when will it be suported.

**Comment by kf6gpe** [comment]
(Critical issue triage) @cbracken How is this looking? Mid-Nov is nearly upon us! Thanks.

**Comment by loody5566** [comment]
apng support please，

**Comment by loody5566** [comment]
still waiting for the apng support

**Comment by chinmaygarde** [comment]
@cbracken I updated the milestone since the previous one expired. Please feel free to update it to something else if that is not realistic.

**Comment by miaosun009** [comment]
关于APNG支持有什么进展吗？我目前觉得我非常需要它。为什么开箱即用的图像小部件中不支持APNG格式？这是一种非常常见的格式。

**Comment by minikupa** [comment]
When will this be supported?

**Comment by zanderso** [comment]
@cbracken Did you have a draft going for this that could be handed off to someone else to wrap up?

**Comment by SeasonLeee** [comment]
@chinmaygarde 
@cbracken 
@zanderso 
@kf6gpe 

 is the conversation going private or do we miss anything here? the last reply is commented on March 11, and now it's April 30...

**Comment by zanderso** [comment]
I believe this work was reprioritized, but the issue was not updated to match. I will update the priority to match my understanding. I will also repeat my gentle ping to @cbracken to ask if there is a draft PR that could be handed off.

**Comment by MadSheogorath** [comment]
I'm currently developing custom 2d engine canvas widget and came to conclusion that APNG support is so much required :) WEBP is cool, but not good enough. And not so common as APNG. So, +1 for APNG support.

**Comment by biij5698** [comment]
still waiting for the apng support

**Comment by ChristopherDelgado** [comment]
still waiting for apng support!

**Comment by ConanShin** [comment]
still waiting...

**Comment by Formerly** [comment]
still waiting for apng support!

**Comment by hieudz** [comment]
still waiting for apng support!, please :'(

**Comment by EdJang21** [comment]
still waiting for apng support desperately!

**Comment by bdero** [comment]
I'm currently working on a stopgap solution for this. We might be able to support this in Skia's PNG codec directly, so I filed a request for that too: https://bugs.chromium.org/p/skia/issues/detail?id=12474

**Comment by Til555** [comment]
Thanks @bdero for looking into this!

**Comment by AphinityApp** [comment]
this would be a much-needed addition. hoping this gets added soon

**Comment by keanallen** [comment]
Any update? HAHA

**Comment by sveinbjornt** [comment]
APNG support in Flutter would be really great!

**Comment by lucianobargmann** [comment]
This is is great, but much more needed is support for transparent WEBM (VP8 or VP9 codecs); I would use APNG if it was available as a workaround.

**Comment by eximius313** [comment]
@bdero - maybe you could publish your code as a plugin?

**Comment by sveinbjornt** [comment]
Thanks @bdero, there is real need for this.

**Comment by bugrevealingbme** [comment]
any update?
