### ISSUE TITLE
google_sign_in configuration of dialog text

### ISSUE THREAD

**Issue by lookfirst** [flutter/flutter#37240]
When I execute, `googleSignIn.signIn()`, it shows a dialog on ios as seen in the picture below.

I want to configure the name under the red section:

![image](https://user-images.githubusercontent.com/85355/62128615-fbf3b180-b2fe-11e9-90b6-f8107a0759d2.png)

Right now, it seems to take a value from who knows where. It happens to be the same as my pubspec.yaml::name though, so maybe that is it?

**Comment by lookfirst** [comment]
@collinjackson ?

**Comment by TahaTesser** [comment]
Hi @lookfirst 
It's the app name from your platform 
You can modify your app name to change that text in your dialog
Thank you

**Comment by lookfirst** [comment]
@TahaTesser 

I'm seeing it being set to the `name` field at the top of the `pubspec.yaml`. I would like it to be set to the `description` field, which is being used as the pretty name for the app as well as the name that is generated for the iOS app. I can't set the `name` field to be the same as the description field because I get an error like this:

```
Error on line 1, column 7 of pubspec.yaml: "name" field must be a valid Dart identifier.
  ╷
1 │ name: Foo Bar
  │       ^^^^^^^^^^^
  ╵
pub get failed (65;   ╵)
```

Please reopen.

**Comment by stuartmorgan** [comment]
> I'm seeing it being set to the `name` field at the top of the `pubspec.yaml`

Have you validated that that's the case by changing it to something that works? I would expect this to be coming from the server registration you did (for security reasons), for which you may have used the same name as your Flutter project.
