### ISSUE TITLE
I/flutter (28463): Google Login Error: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 12500: , null)

### ISSUE THREAD

**Issue by Vandana-kanwar** [flutter/flutter#37242]

**Comment by miyoyo** [comment]
This should not be a github issue.
https://stackoverflow.com/questions/53094767/exception-com-google-android-gms-common-api-apiexception-12500

**Comment by amrit-citrusleaf** [comment]
It's not working even after updating the correct SHA1 and updating the OAuth Consent Screen with all the required values. The consent screen has been verified from Google as well. Does google API console maintain any kind of error logs?

**Comment by BondarenkoStas** [comment]
@Vandana-kanwar Please check the discussion here #33393 and here #36656 and try suggestions. Closing as the report doesn't provide any additional information to the existing issues.

**Comment by zhangsong9008** [comment]
I have the same problem. Finally, I found that my phone didn't support Google Play Service, so before calling Google to login, Please make sure that Google Play Service was supported, use the plugin 'google_api_availability: 2.0.4' to make sure it wasn't, and then return. The problem bothered me for several days. > _ <
