### ISSUE TITLE
Flutter Debug isn't working

### ISSUE THREAD

**Issue by w0rdism** [flutter/flutter#37261]
When trying to debug app it won't work and gives back error similar to "Error cannot connect to service protocol: HttpExeption..."

How do I fix this? to reproduce click debug. Tried everyting in #25112 but still didn't work...

**Comment by blasten** [comment]
Are you running a simulator that runs Android Q? If yes, this might be related to https://github.com/flutter/flutter/issues/32696, https://github.com/flutter/flutter/issues/33050

**Comment by w0rdism** [comment]
> Are you running a simulator that runs Android Q? If yes, this might be related to #32696, #33050

Okay thanks, I see this is an issue with Q and downgraded to Pie and it works now. 👍
