### ISSUE TITLE
Improve handling of infinite values in the Flutter framework

### ISSUE THREAD

**Issue by flar** [flutter/flutter#37277]
There are a number of places in the Flutter framework where an assert alerts developers to the presence of infinite values in various data structures. A few places in the framework have had code which performs calculations in such a way that infinite values cause problems, such as introducing a NaN value in subsequent operations.

We should generally harden the implementation against mishandling infinite values, and also to deal with absurdly large values in areas where they might cause us to request infeasibly large resources.

As the implementation is updated to deal gracefully with infinite values, we should also remove the assertions as they become obsolete.

**Comment by flar** [comment]
I've seen the following code pattern used in a number of places, sometimes in implementing a compare method:
```
  int compareTo(Type other) {
    return (value - other.value).sign.toInt();
  }
```
The problem with this pattern is that subtracting 2 `infinity` values would result in a `nan` value which doesn't have a sign (`nan.sign` returns `nan`) and can't be converted to an int, resulting in an exception at runtime.

The appropriate value for a comparator can be obtained directly from the `double.compareTo()` method which deals well with `infinity` and `nan` values and creates a consistent ordering of all doubles.

A similar pattern is used in other places where `(a - b).sign` is used to indicate which direction to move some other value (as in `a + b * (c-d).sign`) but fails if both of the values are `infinity`. Such code could instead use a construct such as `a + b * c.compareTo(d).sign` or a helper function `_direction(c, d)` that performs the proper comparison.

**Comment by Hixie** [comment]
I recommend filing specific bugs for each of these. I don't think it makes sense to audit this as a whole, because there's a wide array of reasons for these asserts.

**Comment by goderbauer** [comment]
Closing this as per the previous comment.
