### ISSUE TITLE
flutter channel should indicate if install is not on any channel

### ISSUE THREAD

**Issue by paul-hammant** [flutter/flutter#37286]
I suggest `flutter channels` should list channels.

And maybe `flutter --channel` should tell you what channel you're on.

Then `flutter channel` should suggest it has been replaced by the other two.

**If it is the case that none of the channels are current/selected, then the output as it is today should say "no channel selected" clearly**

**Comment by miyoyo** [comment]
It does, actually
```
Flutter channels:
* beta
  dev
  master
  stable
```
The asterisk denotes which channel you're currently using.

**Comment by paul-hammant** [comment]
And when there's no asterisk, what's that telling you?

**Comment by timsneath** [comment]
You're probably not on any channel. What does `flutter doctor -v` tell you?

**Comment by paul-hammant** [comment]
I'm raising a suggestion for `flutter channel`. It is to do with no-channel selected.

**Comment by timsneath** [comment]
Got it. Updated title accordingly. Thanks for the suggestion, @paul-hammant!

**Comment by mannprerak2** [comment]
I don't think this is an issue.
The current channel is indicated with an asterisk
It's only when you are on some local branch that doesn't exist on the remote branch no asterisk is shown.

Here are the outputs in different cases (upon running `flutter channel`)

#### when on some official branch
```
Flutter channels:
  beta
  dev
  master
* stable
```

#### when on some other branch which is also on remote
```
Flutter channels:
  beta
  dependabot
  dev
  fill_paginated_data_table_card
  master
  revert-45126-gallery_enable_platform_views
  revert-45951-driver
  revert-46090-gallery_density
  revert-47027-fix-sliver-layout-assert
  revert-47177-setEditingState
* scrollphysics-to-textformfield
  sort-channel-by-stability
  stable
  v1.12.13-hotfixes
  v1.4.5-hotfixes
  v1.4.6-hotfixes
  v1.4.9-hotfixes
  v1.5.4-hotfixes
  v1.7.8-hotfixes
  v1.9.1-hotfixes
```

#### when on some local branch which isn't on remote ( no asterisks in this case )
```
Flutter channels:
  beta
  dependabot
  dev
  fill_paginated_data_table_card
  master
  revert-45126-gallery_enable_platform_views
  revert-45951-driver
  revert-46090-gallery_density
  revert-47027-fix-sliver-layout-assert
  revert-47177-setEditingState
  scrollphysics-to-textformfield
  sort-channel-by-stability
  stable
  v1.12.13-hotfixes
  v1.4.5-hotfixes
  v1.4.6-hotfixes
  v1.4.9-hotfixes
  v1.5.4-hotfixes
  v1.7.8-hotfixes
  v1.9.1-hotfixes
```
