### ISSUE TITLE
Barrier functionality for showBottomSheet

### ISSUE THREAD

**Issue by MahdiPishguy** [flutter/flutter#37283]
in flutter `showBottomSheet` doesn't support `barrier` like with `showModalBottomSheet`, is any feature to implementing that?

**Comment by dark-chocolate** [comment]
By `barrier` did you mean `showModalBottomSheet` is dismissible when tapping outer space? If yes, 
that's why they are 2 different things, if `showBottomSheet` also gets `barrier`, there will be no main difference between the two.

**Comment by MahdiPishguy** [comment]
@dark-chocolate i think by `showBottomSheet` we can implementing `scroll` easily, but with `showBottomSheet` is hard, now we can made it for `showBottomSheet` and we need to have `barrier`

**Comment by miyoyo** [comment]
`showBottomSheet` doesn't have a barrier because it is part of the scaffold, not in front of it.
`showModalBottomSheet` has a barrier because it is *another page entirely*, therefore it's shown in front of the scaffold.

**Comment by VladyslavBondarenko** [comment]
Closing since the issue seems solved
if you disagree please write in the comments and I will reopen it. 
Thank you
