### ISSUE TITLE
Flutter TextAlign ignored in Row widget

### ISSUE THREAD

**Issue by hasen6** [flutter/flutter#37293]
I'm using **TextAlign** to centre one piece of text and then again to send another piece of text to the right, all contained in a **Row**, but the alignment does nothing at all.

## Steps to Reproduce

```
Scaffold(
  body: Row(
    children: <Widget>[
      Text('Align Centre', textAlign: TextAlign.center),
      Text('Align Right', textAlign: TextAlign.right),
    ],
  ),
);
```
![text](https://user-images.githubusercontent.com/15882674/62197834-2606ab80-b3b3-11e9-9cda-53e573e97f5a.png)

**Comment by MahdiPishguy** [comment]
@hasen6 did you try to use two `Row` for each `Text`?

**Comment by hasen6** [comment]
@MahdiPishguy You mean each single piece of text is in it's own row too? I don't see why it doesn't work as is to be honest, it seems the most logical way to do it.

**Comment by MahdiPishguy** [comment]
@hasen6 yes my mean is each single piece of text is in it's own row

**Comment by hasen6** [comment]
@MahdiPishguy No that doesn't change anything. I think it would be weird if that were the way to do it anyway.

**Comment by miyoyo** [comment]
This should not be an issue on github.
The problem here is that your text does not expand, it therefore cannot be aligned.
Wrap with Expanded or other such widgets.

**Comment by escamoteur** [comment]
If you still have problems please ask this question again on stackoverflow
