### ISSUE TITLE
after adding packages in project, android is ok but ios crash during start

### ISSUE THREAD

**Issue by farhang-fallah** [flutter/flutter#37297]
## Steps to Reproduce

1. hi. im adding packages in my application.

## Logs 

```dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  shared_preferences: ^0.5.2
```
successfully run on Android device.
then it run  
 flutter build ios 
  and successful building and installing in xcode.
but when running app in device error :

```#import <UIKit/UIKit.h>

#import <Flutter/Flutter.h>

#import "AppDelegate.h"



int main(int argc, char * argv[]) {

  @autoreleasepool {

    return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));  Thread 1: signal SIGABRT

  }

}
```
**How to fixet in??**

**Comment by miyoyo** [comment]
This should probably not be an issue, please collect the logs you have been given instead of just pasting the error after the source, and go over to [StackOverflow](https://stackoverflow.com/questions/tagged/flutter)

**Comment by escamoteur** [comment]
could you fix this ?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
