### ISSUE TITLE
To perfect the webview

### ISSUE THREAD

**Issue by zhangruiyu** [flutter/flutter#37291]
Add more configurations, such as:
setUseWideViewPort
setLoadWithOverviewMode
setBuiltInZoomControls
setSupportZoom
setDomStorageEnabled
setJavaScriptCanOpenWindowsAutomatically
setSupportMultipleWindows
setAllowFileAccess
setAppCacheEnabled
setAllowFileAccessFromFileURLs
setAllowUniversalAccessFromFileURLs
setMixedContentMode
setDisplayZoomControls

**Comment by escamoteur** [comment]
Can you please elaborate what you want?

**Comment by yjbanov** [comment]
This doesn't seems to be web-related, but specifically WebView.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
