### ISSUE TITLE
flutter, then i change folder i got this error here

### ISSUE THREAD

**Issue by 007fred50** [flutter/flutter#37298]
I'm wokring on flutter, but my question is i changed folder path.

I'm running

> flutter run

But now i got this error here:

```
* Error running Gradle:
ProcessException: Process "/Volumes/free44you/007fred/flutter_apps/flutter_tts/android/gradlew" exited
abnormally:

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using
BuildScopeServices.createScriptPluginFactory().
> Could not create service of type FileHasher using BuildSessionScopeServices.createFileSnapshotter().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: /Volumes/free44you/007fred/flutter_apps/flutter_tts/android/gradlew app:properties


Please review your Gradle project setup in the android/ folder.
```

Can some one help me with this? Thanks :)

**Comment by ketanm** [comment]
@007fred50  - Can you clarify what folder path did you change? Did you change location to flutter?

Above text shows that you are running into gradle execution. 
* Do `flutter clean` inside the project and 
* also delete `android/.gradle`. If you have changed the flutter path then `android/local.properties` would still have an old path.

It is better to delete old android and ios build files and re-run `flutter build xxx` as needed.

**Comment by escamoteur** [comment]
Have you solved your problem?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
