### ISSUE TITLE
Flutter's webview doesn't open storage.

### ISSUE THREAD

**Issue by Sarthaktydy** [flutter/flutter#37301]
have input tags in my angular project it doesn't open storage to upload documents.

**Comment by BondarenkoStas** [comment]
@Sarthaktydy Is the issue still relevant? Can you provide your ```flutter doctor -v``` and some code to reproduce the issue? Were there any error logs?

**Comment by Sarthaktydy** [comment]
There is no error whatsoever. And the code is simple (I started using flutter_webview_plugin instead so can't give you the exact code ) let me explain
So I have a website on that website we have an upload button to upload the document which has an input tag with type as file and I open the website in flutter's webview and everything works fine but when you click on upload button it should open your gallery or storage but it doesn't. It doesn't show any error. I tried using all the webview_flutter plugin's version but no luck.

**Comment by Sarthaktydy** [comment]
> @Sarthaktydy Is the issue still relevant? Can you provide your `flutter doctor -v` and some code to reproduce the issue? Were there any error logs?

There is no error whatsoever. And the code is simple (I started using flutter_webview_plugin instead so can't give you the exact code ) let me explain
So I have a website on that website we have an upload button to upload the document which has an input tag with type as file and I open the website in flutter's webview and everything works fine but when you click on upload button it should open your gallery or storage but it doesn't. It doesn't show any error. I tried using all the webview_flutter plugin's version but no luck.

**Comment by BondarenkoStas** [comment]
Unfortunately it's still not enough, there is no unambiguous way create it, also without knowledge on which version of the framework and environment it should be tested. I searched and couldn't find something similar. We are therefore reluctantly going to close this bug for now. Please don’t hesitate to comment on the bug if you have any more information or encounter it again; we will reopen it right away!
Thanks for your contribution.

**Comment by Sarthaktydy** [comment]
> Unfortunately it's still not enough, there is no unambiguous way create it, also without knowledge on which version of the framework and environment it should be tested. I searched and couldn't find something similar. We are therefore reluctantly going to close this bug for now. Please don’t hesitate to comment on the bug if you have any more information or encounter it again; we will reopen it right away!
> Thanks for your contribution.

Ok. I give you the information I can.

1) Tried with every plugin version (oldest to latest)
2) The website that I'm opening is created in Angular
3) Every input tag have issue in flutter's webview, Earlier keyboard doesn't use to popup, although it's fixed now (at least on the beta channel)
4) My scenario is 
--- I open my website in flutter's webview works fine. now there is a form section on my website which requires the user to upload their image and on the angular side we have  
`<input type="file>`
this code and it suppose to open the storage/gallery on the mobile phone but it doesn't.
It works fine in"flutter_webview_plugin" but not in "webview_flutter". Please let me know if you want to know anything

**Comment by BondarenkoStas** [comment]
@Sarthaktydy oh sorry, somehow I misunderstood you. It's https://github.com/flutter/flutter/issues/27924. I think it will be correct to close this issue to avoid duplication, and please follow it there.
