### ISSUE TITLE
NetworkImage sends 'get' instead of 'GET' to load images

### ISSUE THREAD

**Issue by ianloic** [flutter/flutter#3730]
Using a [recent](https://github.com/flutter/flutter/tree/00062761bec186102c1c5c2c73162accdf2e1ddb) Flutter, a trivial use of NetworkImage, for example:
```
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(primarySwatch: Colors.blue),
      home: new FlutterDemo()));
}

class FlutterDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Center(child: new NetworkImage(
        width: 100.0,
        height: 100.0,
        src: 'http://scratch.ianloic.com/thumb.jpg'));
  }
}
```
Fails to load the image. Different servers return different errors, but the core problem can be seen in my server logs. Compare Chrome to Flutter:
```
104.132.0.91 - - [04/May/2016:10:09:17 -0700] "GET /thumb.jpg HTTP/1.1" 200 74435 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
104.132.1.105 - - [04/May/2016:10:09:43 -0700] "get /thumb.jpg HTTP/1.1" 501 430 "-" "okhttp/2.2.0"
```

**Comment by ianloic** [comment]
@abarth, it looks like you've been touching this part of the stack recently.

**Comment by abarth** [comment]
Sorry about that.  Fix is trivial.  On line 129 of mojo_client.dart:

`mojom.UrlRequest request = _prepareRequest('get', url, headers);`

Should have `GET` instead of `get`.

**Comment by ianloic** [comment]
Confirmed. Making that change locally fixes it for me.
