### ISSUE TITLE
Way to avoid pushing same route twice

### ISSUE THREAD

**Issue by LinusU** [flutter/flutter#37304]
## Use case

We are building an app that has several chat conversations. When the user presses a notification we want the app to open with the conversation open corresponding to the notification tapped.

The closes we have come to getting this working is something like the following:

```dart
_firebaseMessaging.configure(
  onMessage: (message) async {},
  onLaunch: (message) async {
    if (message.containsKey('threadId') && message.containsKey('messageId')) {
      navigatorKey.currentState.pushNamedAndRemoveUntil('/thread', (Route<dynamic> route) => route.isFirst, arguments: message);
    }
  },
  onResume: (message) async {
    if (message.containsKey('threadId') && message.containsKey('messageId')) {
      navigatorKey.currentState.pushNamedAndRemoveUntil('/thread', (Route<dynamic> route) => route.isFirst, arguments: message);
    }
  },
);
```

This makes sure that the navigation stack is being reset to the start page, and then pushes in the page showing the conversation.

The only small problem is if the app is already open with the same conversation that the notification is trying to open. The current page will reload which makes images briefly flash, the scroll position will be lost, and other small glitches.

## Proposal

It would be great if we could either 1) inspect the current state of the navigator, so that we can determine wether the target page is already open or not, or if we could 2) expose an option that tells the navigator to not replace the current page if the new pages name and arguments matches.

I would be happy to discuss any ideas on how this could look, and help with an implementation!

**Comment by kroikie** [comment]
@LinusU

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1052. Any further collaboration will be done there.
