### ISSUE TITLE
SkImage memory delayed release

### ISSUE THREAD

**Issue by chechuangfeng** [flutter/flutter#37302]
I add some code to monitor SkImage's instantiation and finalization.   Sometime I found that some SkImages seem to be finalize delayed, and It look like a batch finalization。

I have a listview with many image  (my custom ImageCache size is 0)

1. . launch app,  my ListView offset is 0， current number of SkImage is 32
2. . first scroll down a distance, then scroll up to the top,  the number of SkImage is 91
3. . I scroll a little distance, just trigger a frame. a this time  SkImage reduce to 32.

 
Is there something keep the ref of the SkImages?  When to trigger batch finalization？@eseidelGoogle @rmacnak-google 
![image](https://user-images.githubusercontent.com/3196849/62211211-81936200-b3d0-11e9-9de4-20c15311bdf1.png)
![image](https://user-images.githubusercontent.com/3196849/62211704-d2f02100-b3d1-11e9-9a1b-7320a0ac4c0e.png)

**Comment by eseidelGoogle** [comment]
@chinmaygarde or @liyuqian would know.

**Comment by jason-simmons** [comment]
See https://github.com/flutter/engine/blob/master/flow/skia_gpu_object.cc

After `Image` objects are garbage collected by Dart, the underlying Skia `SkImage` is placed on a queue for deletion.  The UI thread that runs Dart code does not have a context for invoking graphics APIs like OpenGL ES, so the deletion of graphics objects must be done on a different thread.

Draining the queue used to be done after a 250 ms delay with the goal of reducing contention between the draining thread and the UI thread.  This was recently reduced to 8 ms.  See https://github.com/flutter/engine/commit/ad582b5089256e56727b2d7306fb097078a3dcdc

**Comment by rmacnak-google** [comment]
The batching is because `Image` objects are only known to be unreachable at the end of a garbage collection cycle, not immediately when the last reference is overwritten/destroyed.

**Comment by chechuangfeng** [comment]
THX @rmacnak-google @jason-simmons  
Is blink or cc has the same mechanism to delayed Image release？
I compare this case between Flutter and WebView, it seem that WebView can  release memory immediately to a normal level that I  expect.

**Comment by chinmaygarde** [comment]
While the observed behavior is WAI for the reasons Ryan & Jason mentioned, an effort is underway to more aggressively collect these references. This is being tracked in https://github.com/flutter/flutter/issues/56482. Closing this as duplicate.
