### ISSUE TITLE
Pass existing SurfaceTexture to TextureRegistry

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#37313]
```
[✓] Flutter (Channel master, v1.8.2-pre.242, on Linux, locale en_US.UTF-8)
    • Flutter version 1.8.2-pre.242 at <install location>
    • Framework revision 9bb7142ef7 (21 hours ago), 2019-07-30 14:45:00 -0700
    • Engine revision c41bbc63d9
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 1e43d65d4a)
```

Is it possible to call `registerTexture` to register a surface that was created outside of Flutter so that Flutter knows how to render it? It seems to be possible using a plugin via the registrar (?) but I think it should be possible to do so in an app directly.

Sorry if there is a way, I haven't been able to spot one. My thought is that `FlutterView` should have a set of `register` and `unregister` functions for this purpose.

**Comment by pedromassangocode** [comment]
Is this issue still relevant?

**Comment by lukef** [comment]
Yeah. No one replied or looked at it so I assume it is still relevant.

**Comment by ColdPaleLight** [comment]
I also hope that Flutter has this ability very much. Because I want to use external texture to display image, I want to create a `SurfaceTexture` with `singleBufferMode`.

**Comment by ColdPaleLight** [comment]
Closing this issue as fixed in the linked PR
