### ISSUE TITLE
How to make a sequence of http requests on a widget before build method

### ISSUE THREAD

**Issue by bernardohrl** [flutter/flutter#37316]
I have 3 classes: Users, Posts and Comments. **User** has many **Posts** and
**Posts** has many **Comments**.

I want that all data has been fetched before the widget's build method is called.

I tryed to use **initState()** to do this:
```
class FetchDataExample extends StatefulWidget {
  final User _user;

  FetchDataExample(this._user);

  @override
  _State createState() => _State(_user);
}

class _State extends State<FetchDataExample> {
  final User _user;

  _State(this._user);

  @override
  void initState() {
    _user.setPosts();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    print(this._user.posts[0]);


    return Container(
      
    );
  }
}
```

In **User class**  I have: 
```
void setPosts() async {

    String url = 'https://jsonplaceholder.typicode.com/posts?userId=' + this.id.toString();
    var request = Requester.get(url); // Returns a Future<Response>

    await request.then((value) => this.posts = Post.jsonToPosts(json.decode(value.body)));

    this.posts.forEach((post) => post.setComments());

    print(this.posts[0]);
}
```

The 'setComments()' has the same logic. 

I have two prints:

1. Inside **build** that returns **null**;
2. Inside **setPosts** the returns **Instance of 'Post'**;

So, by the time that Build method is called in the widget, the initState has not finished yet.

I need it be finished, does anyone know how can I do that?

**Comment by kenwen** [comment]
Rewrite setposts as a future, then use it as part of a futurebuilder

so

`future<posts>setPosts() async {
 ...your code...
return posts[0]`

in you widget build method

`return futurebuilder(future: _user.setPosts, builder: ...the widget that uses the data goes here`

Recommend reading the docs here for more details, [https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html](url)

**Comment by WevertonCouto** [comment]
You can use FutureBuilder 
Follow this link
https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html

**Comment by bernardohrl** [comment]
@kenwen on my App, I need to do about 4-5 different requests that uses previous requests values. 

The only way I can do that is nesting FutureBuilders?

**Comment by kenwen** [comment]
@bernardohrl recommend reading the docs and SO, but off the top of my head you could use .then to chain all your futures together into one future

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
