### ISSUE TITLE
Regressions on multiple microbenchmarks

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#37325]

**Comment by franciscojma86** [comment]
All the following metrics show regressions after https://github.com/flutter/flutter/commit/bf3a907ce73126026914df70fd8f1fd6e752768b
MatrixUtils_affine_transformPoint_iteration
MatrixUtils_affine_transformRect_iteration
MatrixUtils_persp_transformPoint_iteration
MatrixUtils_persp_transformRect_iteration

**Comment by johnsonmh** [comment]
Are these still happening now that this optimization has re-landed? https://github.com/flutter/flutter/pull/37275

**Comment by franciscojma86** [comment]
https://github.com/flutter/flutter/commit/c7596da5a489b8000a5313035fe887df758b0d42 is back to green. Will keep monitoring.
