### ISSUE TITLE
Regression on hot_mode_dev_cycle__benchmark hotReloadMillisecondsToFrameAfterChange

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#37321]
Introduced on https://github.com/flutter/flutter/commit/3a674421299e9a90700e7e23b6112f04c7687c61

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/35551

**Comment by franciscojma86** [comment]
Closing this issue since it's being tracked elsewhere.
