### ISSUE TITLE
local_auth plugin not testable

### ISSUE THREAD

**Issue by twfarnam** [flutter/flutter#37337]
Hey, there. We are using the local_auth plugin for our app but we have an issue writing tests for it. The plugin validates that the OS is Android or iOS before it makes the call to the platform channel:
https://github.com/flutter/plugins/blob/master/packages/local_auth/lib/local_auth.dart#L64-L74 This means that we can't use setMockMethodCallHandler on the channel to simulate the user's actions.

Is there another way to write tests in this case? Perhaps the plugin should still pass the call to the channel so testing of the results is possible. Much obliged!

**Comment by stuartmorgan** [comment]
This would be fixed by federating the plugin, since it would provide a platform interface to stub out.

**Comment by stuartmorgan** [comment]
Closing; https://docs.flutter.dev/development/packages-and-plugins/plugins-in-tests explains the available options here.
