### ISSUE TITLE
Flutter Runner crashes while enqueuing Scenic commands

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#37336]
Mirror issue for https://fuchsia.atlassian.net/browse/FL-287. Conversation should occur there, please.

**Comment by Hixie** [comment]
@cbracken, can you see who would be available to address this? Or should we consider it blocked behind FL-250?

**Comment by Hixie** [comment]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=8869 is marked closed, should this be closed also?

**Comment by cbracken** [comment]
Yep this is now fixed.
