### ISSUE TITLE
Feature request: Z constraints

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#37335]
## Use case

Embedding arbitrary child widget hierarchies on Fuchsia at different, potentially conflicting, elevations, and wanting to render one of the child widget hierarchies on top of the others.

## Proposal

Support setting z constraints on widget hierarchies so that a parent layout can have arbitrary children at different elevations and guarantee that they don't have z bound conflicts. 

For example, assume that a parent Widget has two direct children, A and B. The parent wants to render B on top of A. Right now it's impossible to guarantee this for arbitrary children because child A could have children of its own with elevations greater than B. 

(In this example positive z means "closer to the camera" to match elevation's axis.)

```
          +--------+
          |        |
          | Parent |
          |        |
          +--+----++
             |    |
       +-----+    |
+--------------+  |
|    Child A   |  |
|    z: 5      |  |
+-------+------+  |
        |         |
        |  +------+------+
        |  |   Child B   | <------Expected top widget
        |  |   z: 10     |
        |  +-------------+
 +------+------+
 | Grandchild  |
 | z: 15       | <---------Conflict
 +-------------+
```

Ideally there would be some kind of Widget that Parent could apply to A to constrain it and its children to z<=5, and then it could safely position B at 10.

## Ideas

This is a similar concept to [BoxContraints](https://flutter.dev/docs/development/ui/layout/box-constraints) but applying to z/elevation instead of x and y.

None of the widget layout code takes elevation/z into any kind of account, which makes this extremely difficult to fix. My intuition is that adding in logic to consider and handle 3D bounds properly in the framework would probably be a non starter. I wonder if it would be possible to get the end desired behavior here (None of the children conflict with each other on the z axis) without actually having to care about three dimensions. Maybe it would be sufficient to flatten all the "constrained" children to a single layer? Like some kind of "CancelElevation" widget that makes sure any children are elevation=0. Or maybe we could somehow route the constraint down to the physical layer for the constrained child in the engine so it was clamped in the same place we normally clamp widgets that are out of global bounds?

It's not immediately obvious how out of constraint child widgets should be handled once this is implemented. The engine is clamping in this situation for when any widget goes out of global bounds, but I can see normalization being better here.

This probably requires at least flutter/flutter#33854 and flutter/flutter#33853. /cc @dnfield

**Comment by Hixie** [comment]
I suspect that any flattening would result in a warped UI that would be considered unacceptable.

**Comment by Hixie** [comment]
Given the direction of Scenic's development, let's punt on this until we have better clarity about the needs here.
