### ISSUE TITLE
Log local time with Analytics

### ISSUE THREAD

**Issue by jayoung-lee** [flutter/flutter#37334]
Google Analytics currently logs UTC time. Could we add local time to each hit?

`YYYY-MM-DD HH:MI:SS Timezone` format would be ideal (e.g., `2018-08-24 18:43:03 PDT`)

cc: @zanderso

**Comment by zanderso** [comment]
Local time without timezone is on the local_time custom dimension on every screen and event following: https://github.com/flutter/flutter/pull/36545. I'll look into getting the timezone in there, too.
