### ISSUE TITLE
IAP items not appear using plugin example

### ISSUE THREAD

**Issue by zukinaru** [flutter/flutter#37346]
I try to run IAP (in-app-purchase) example apps that provided by flutter here: https://github.com/flutter/plugins/tree/master/packages/in_app_purchase/example

I follow all step, except upload signed `App Bundle` instead of `APK` to Alpha Phase at Google Play Console. 

Also, all of my IAP items that has been created at play console not appear.

However, when i open the screen example, it said warning:

>**Consumable, Upgrade, Subscription Not found, This app need special configuration to run. Please see example/README.md for instructions.**

Any idea to solve ?

## Steps to Reproduce

1. Create New Project
2. Get Some Source Code from https://github.com/flutter/plugins/tree/master/packages/in_app_purchase/example
3. Run `Flutter build appbundle --release`
4. Upload AppBundle to `Alpha`
5. Prepare list of User Test
6. as User Test, Sign Up for Alpha/Beta Apps Link
7. Create Subscribe Item at PlayStore Console
8. Make Subscribe Item to be active
9. Run Apps
10. Go to IAP Example Screen

**Comment by TahaTesser** [comment]
Hi @zukinaru 
Are you still experiencing this issue?
Thank you

**Comment by TahaTesser** [comment]
Hi @zukinaru 
if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
