### ISSUE TITLE
crash android 4.4 kit kat after multiDex 

### ISSUE THREAD

**Issue by ClaudineiOlSantos** [flutter/flutter#37347]
Hi.

My project had problems with muilti dex I installed a dependency as described in [the link](https://developer.android.com/studio/build/multidex). But in android 4.4 the app compiles but closes automatically

```
[√] Flutter (Channel master, v1.8.2-pre.242, on Microsoft Windows [versÃ£o 10.0.17134.885], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc1)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.36.1)
[√] Connected device (1 available)

• No issues found!

```
On current android phones works perfectly.

**Comment by VladyslavBondarenko** [comment]
Hi @ClaudineiOlSantos 
I see there's an open issue addressing the case you described.
Please follow up on [#39779](https://github.com/flutter/flutter/issues/39779)
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
