### ISSUE TITLE
add possibility to set visible extent of BottomSheet programmatically

### ISSUE THREAD

**Issue by The-Redhat** [flutter/flutter#37348]
## Use case

In order to build expanding bottom sheets it's necessary to expand them when the user taps on a button. This behavior is also shown in the official material [docs](https://material.io/design/components/sheets-bottom.html#usage). In the current situation the user must expand the bottom sheet with a gesture.     

## Proposal

The expected behavior could be achieved by adding a method to the controller returned by `Scaffold.of(context).showBottomSheet`

**Comment by TahaTesser** [comment]
Hi @The-Redhat 
Looks like this exist in Flutter now 

### This will expand the bottom sheet when you tap on FAB 
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final height = MediaQuery.of(context).size.height;
    final GlobalKey<ScaffoldState> scaffoldKey = GlobalKey<ScaffoldState>();
    return Scaffold(
      key: scaffoldKey,
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
          child: Icon(Icons.add),
          onPressed: () =>
              scaffoldKey.currentState.showBottomSheet((context) => Container(
                    height: height / 3,
                    color: Colors.white,
                  ))),
    );
  }
}
```
Closing this issue as resolved
if you disagree please write in the comments and I will reopen it 
Thank you
