### ISSUE TITLE
[Google_sign_in] Provide a fix so that the exceptions in `signIn` method can be caught correctly by plugin users.

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#37343]
Issue to track a possible fix to #26705.
cc @cyanglaz

**Comment by feinstein** [comment]
@cyanglaz do you know if any tests or examples already on the package will trigger the exception? So that I can get things up to speed.

**Comment by cyanglaz** [comment]
@feinstein I think you can just call signIn() method in the example app and try to catch exception for it. You might need to use the IDE's `uncaught exceptions` break pointer to see the issue. I think the original issue has some examples as well.

**Comment by feinstein** [comment]
I got the exception as soon as I started the example, as `signInSilently()` triggers it.

Now I am wondering how to fix the code...

Line 302 of the `google_sign_in.dart` has:

```dart
return result.catchError((dynamic _) => null);
```

I am new to dart, but I think this is wrapping the `Future` into a new one that upon execution will have that `catchError` that ignores errors. I am trying to figure out what's the traditional `try-catch` equivalent of this, if any.... maybe I have to wrap a `try-catch` inside a new `Future`?

**Comment by feinstein** [comment]
Ok, I think I fixed it, at least I am not getting any Exceptions any more here... but apparently I broke the tests, so I will investigate this as well.

**Comment by feinstein** [comment]
Ok, fixed it. I will land a PR so you can review it.

**Comment by feinstein** [comment]
PR flutter/plugins#1937

@cyanglaz please also review the styling as the style guide is too long and I probably won't remember it all, thanks :)

**Comment by feinstein** [comment]
@cyanglaz I follower the versioning doc [here](https://dart.dev/tools/pub/versioning) and since this change doesn't change the public API, I added a `+1`, but the automatic checks apparently don't like this. Am I understanding the usage of `+1` wrongly?

**Comment by feinstein** [comment]
I tried to run the flutter_plugin_tools, but I am getting some errors like this one:

> c:\Programacao\Flutter\plugins>pub global run flutter_plugin_tools test --plugins google_sign_in
> RUNNING google_sign_in tests...
> CreateProcessW failed 2
> Unhandled exception:
> ProcessException: The system cannot find the file specified.
> 
>   Command: flutter test --color
> #0      runAndStream (package:flutter_plugin_tools/src/common.dart:199:7)
> <asynchronous suspension>
> #1      TestCommand.run (package:flutter_plugin_tools/src/test_command.dart:38:26)
> <asynchronous suspension>
> #2      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
> <asynchronous suspension>
> #3      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
> #4      new Future.sync (dart:async/future.dart:224:31)
> #5      CommandRunner.run (package:args/command_runner.dart:112:14)
> #6      main (package:flutter_plugin_tools/src/main.dart:47:17)
> #7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
> #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by cyanglaz** [comment]
The PR https://github.com/flutter/plugins/pull/1937 is merged, closing the issue now.

**Comment by feinstein** [comment]
@cyanglaz thanks for all the help.

As a side note, the pub badge [here ](https://github.com/flutter/plugins) is updated, but the one at the plugin page [here ](https://github.com/flutter/plugins/tree/master/packages/google_sign_in) is still on 4.0.4.

**Comment by feinstein** [comment]
@cyanglaz I think we will need to reopen this issue as recent changes in the API have brought back the usage of the `Future` API, which leads to exception leakage in debug mode.

![image](https://user-images.githubusercontent.com/8120472/69102193-6eb8a200-0a40-11ea-9b5c-2da7368bcabf.png)
