### ISSUE TITLE
Error -32601 received from application: Method not found,dart:mirrors

### ISSUE THREAD

**Issue by miroda** [flutter/flutter#37359]
```
[VERBOSE-2:shell.cc(184)] Dart Error: error: import of dart:mirrors with --enable-mirrors=false
[VERBOSE-2:engine.cc(186)] Could not prepare to run the isolate.
[VERBOSE-2:engine.cc(125)] Engine not prepare and launch isolate.
[VERBOSE-2:FlutterEngine.mm(308)] Could not launch engine with configuration.
Syncing files to device iPhone Xʀ...
```

**Comment by miroda** [comment]
after i annotation this line,the problem has gone,is there anybody konw why?
//import 'package:json_serializable/json_serializable.dart';

**Comment by BondarenkoStas** [comment]
@miroda I think it should be helpful https://stackoverflow.com/a/53009646. What the version of json_serializable you use? Do you still encounter the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
