### ISSUE TITLE
Material gallery smoke test hangs on the bots

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#3735]
Sometimes the `smoke_test.dart` from Material Gallery hangs on the bots.  I've skipped the test for now, but we should figure out the hang and re-enable the test.

/cc @HansMuller

**Comment by HansMuller** [comment]
The hang occurs if the test is launched (with `flutter test`) repeatedly. Typically it takes between 10 to 25 iterations before the hang occurs.  Just making the test loop internally does not cause any trouble.

When the test hangs it's not possible to discover what's on the stack with Observatory, since Observatory also hangs.

Attaching to the hung test with gdb isn't helpful because the profile version of the test doesn't have symbols.

I ran the test against a debug build of the engine. 1000 iterations and no hang.

**Comment by eseidelGoogle** [comment]
The non-debuggability/recoverability of the hang may be related to https://github.com/flutter/flutter/issues/2182 or https://github.com/flutter/flutter/issues/3362 and may be changed in part by @Hixie's grand testing re-write.

**Comment by HansMuller** [comment]
This hang still happens, for example: https://build.chromium.org/p/client.flutter/builders/Linux/builds/996/steps/test.sh/logs/stdio

I ran my own test case over the weekend and it hung after 200 iterations.
```
(for i in {1..1000}; do (cd /builds/dev/flutter/examples/flutter_gallery; flutter test test/smoke_test.dart); done) > /tmp/smoke_test.`date +'%m-%d-%H:%M'``
```

The bot swan song is:
```
+ cd examples/flutter_gallery
+ flutter test

00:00 +0: ...e/Linux/build/flutter/examples/flutter_gallery/test/example_code_parser_test.dart     
00:00 +0: ...ld/slave/Linux/build/flutter/examples/flutter_gallery/test/simple_smoke_test.dart     
00:00 +0: ... Flutter gallery example code parser test                                             
00:00 +1: ... /b/build/slave/Linux/build/flutter/examples/flutter_gallery/test/smoke_test.dart     
00:01 +1: ... /b/build/slave/Linux/build/flutter/examples/flutter_gallery/test/smoke_test.dart     
00:01 +1: ... - Flutter Gallery app simple smoke test                                              
00:02 +1: ... - Flutter Gallery app simple smoke test                                              
00:02 +2: ... - Flutter Gallery app smoke test                                                     
00:03 +2: ... - Flutter Gallery app smoke test                                                     
00:04 +2: ... - Flutter Gallery app smoke test                                                     
00:05 +2: ... - Flutter Gallery app smoke test                                                     
00:06 +2: ... - Flutter Gallery app smoke test                                                     
00:06 +2: loading /b/build/slave/Linux/build/flutter/examples/flutter_gallery/test/smoke_test.dart 
Shell: Attempt:1 waiting for 1 threads to check in
Shell: Attempt:2 waiting for 1 threads to check in
Shell: Attempt:3 waiting for 1 threads to check in
...
```
The message is coming from `dart/runtime/vm/safepoint.cc` which was instrumented about a month ago: https://codereview.chromium.org/1886583002/

**Comment by HansMuller** [comment]
This was fixed in the Dart VM.  See https://github.com/dart-lang/sdk/commit/79e4792dd609ef2bb1f66588a912e420bc058709
