### ISSUE TITLE
PlatformView is blank and prevents unlocking the screen lock

### ISSUE THREAD

**Issue by p30arena** [flutter/flutter#37362]
I wrote a camera widget using PlatformView, similar to the [camera](https://github.com/flutter/plugins/tree/master/packages/camera) plugin.
But instead of using Texture I'm using AndroidView.

On the first time the widget is pushed, everything is working fine, but when I push another widget then pushReplacementNamed back to this widget, the view (PlatformView) gets blank, and if the screen gets locked, I can't unlock it anymore and need a full restart of the device.

**The Device:**

**Device Model**: Samsung Galaxy A5 2014 (SM-A500H)
**Android Version**: 5.0.2
https://www.gsmarena.com/samsung_galaxy_a5_duos-6802.php

**This is not happening on this device:**

**Device Model**: Samsung Galaxy A5 2016 (SM-A510FD)
**Android Version**: 7.0
https://www.gsmarena.com/samsung_galaxy_a5_(2016)-7789.php

I tested this on another Samsung device that I can't remember its model (had android greater than 5), and the screen was blank on the first try and device was unresponsive at the screen lock.

**If the issue is confusing, I'll try to provide a sample.**

```
[√] Flutter (Channel master, v1.8.4-pre.46, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.8.4-pre.46 at M:\flutter
    • Framework revision 21d6d7efb2 (2 hours ago), 2019-07-31 17:52:05 -0700
    • Engine revision a29ef66013
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 80c4954d4d)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_45\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] Connected device (1 available)
    • SM A500H • 6b30dad7 • android-arm • Android 5.0.2 (API 21)

! Doctor found issues in 1 category.
```

**Comment by p30arena** [comment]
This is happening when:

1. show the camera widget (PlatformChannel)
2. show a native activity and receive the result
3. push a widget
4. push back to camera widget  (PlatformChannel)

**Comment by p30arena** [comment]
Sample:
### [platform_views_bug.zip](https://github.com/flutter/flutter/files/3458425/platform_views_bug.zip)

**Comment by p30arena** [comment]
The point here is, I call setState before launching the Crop-Activity, I can be sure that's the reason for the blank screen and the device freezing on the screen lock.

**Comment by p30arena** [comment]
@eseidel 
could you please mention someone who can respond to this issue? :flower_playing_cards:

**Comment by eseidelGoogle** [comment]
@amirh is the right person to ask about PlatformView bugs.

**Comment by TahaTesser** [comment]
Hi @amirh @p30arena 
Is this issue still valid?
Thank you

**Comment by edTheGuy00** [comment]
I think [this](https://github.com/AgoraIO/Flutter-SDK/issues/136) might be related. it only happens on Samsung phones

**Comment by pr-1** [comment]
> I think [this](https://github.com/AgoraIO/Flutter-SDK/issues/136) might be related. it only happens on some Samsung phones. Galaxy Note 10, Galaxy s10, Galaxy s10e have been tested and have this issue.
> 
> Basically the touch screen becomes completely unresponsive

Happens with Samsung M30 also.

**Comment by kedarchiselcut** [comment]
Also happens with Samsung A30.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
