### ISSUE TITLE
No animation when calling RefreshIndicatorState.show method

### ISSUE THREAD

**Issue by gzxg1234** [flutter/flutter#37367]
RefreshIndicator has no animation when i call RefreshIndicatorState.show method, it looks bad.

I think the problem is in build method, when the widget is in the initialization state, field **_mode** is null, the method build will return child directly, the Animation **_positionController** has no effect at this time.

```
@override
  Widget build(BuildContext context) {
    ...
    if (_mode == null) {
      assert(_dragOffset == null);
      assert(_isIndicatorAtTop == null);
      return child;
    }
    ...
  }
```

Here's my solution: set field **_mode** to **_RefreshIndicatorMode.done** and call **setState** method before call **_show**.

```
Future<void> show({bool atTop = true}) {
    if (_mode != _RefreshIndicatorMode.refresh &&
        _mode != _RefreshIndicatorMode.snap) {
      if (_mode == null) _start(atTop ? AxisDirection.down : AxisDirection.up);
      _mode = _RefreshIndicatorMode.done;
      setState(() {
        _show();
      });
    }
    return _pendingRefreshFuture;
  }
```

**Comment by TahaTesser** [comment]
Hi @gzxg1234 
Are you still experiencing this issue with latest stable?
If yes, can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
