### ISSUE TITLE
Invalid `Podfile` file: undefined method `pod' for main:Object.

### ISSUE THREAD

**Issue by gaodeying** [flutter/flutter#37373]
When I do pod install, I get a surprise. please

![image](https://user-images.githubusercontent.com/11342991/62275761-38491e00-b475-11e9-81ad-4ff413d96c1f.png)

![image](https://user-images.githubusercontent.com/11342991/62275983-a42b8680-b475-11e9-85d0-f6fb56cae208.png)

**Comment by gaodeying** [comment]
how to fix it. pod 1.7.2 , flutter dev

**Comment by zhouyangyng** [comment]
> how to fix it. pod 1.7.2 , flutter dev

I have the same problem with you

**Comment by ishkawa** [comment]
What [release channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels) do you use? [Documentation](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) says add-to-app feature is only available in master channel. I also encountered the same error in `stable` channel, but it went away after switching to `master` channel.

**Comment by xster** [comment]
Can you paste your `flutter doctor -v` output?

**Comment by KlausLiu** [comment]
> > how to fix it. pod 1.7.2 , flutter dev
> 
> I have the same problem with you

me too

**Comment by KlausLiu** [comment]
me too.

```
[✓] Flutter (Channel master, v1.8.4-pre.65, on Mac OS X 10.14.5 18F203, locale zh-Hans-CN)
    • Flutter version 1.8.4-pre.65 at /Users/peipeiliu/works/tools/flutter
    • Framework revision af1bbc4374 (2 hours ago), 2019-08-01 17:22:17 -0700
    • Engine revision bf92885975
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 bd049f5b53)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/peipeiliu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode_10.2.1.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • Klaus's iPhone7 • c955d19cd11568a669bfa0ecf5d7ecc4befb39af • ios • iOS 12.3.1
    • iPhone Xʀ       • 2CF53EBF-971E-448A-B7DD-80AD142AA108     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 1 category.
```

Podfile
```
platform :ios, '10.0'

workspace 'FlutterTest.xcworkspace'
project 'HostApp/HostApp.xcodeproj'

flutter_application_path = './v_flutter/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'HostApp' do
  use_frameworks!
  platform :ios, '10.0'
  project 'HostApp/HostApp.xcodeproj'
end

target 'FWA' do
  use_frameworks!
  platform :ios, '10.0'
  project 'FWA/FWA.xcodeproj'

  install_all_flutter_pods(flutter_application_path)
end
```
error:
```
[!] Invalid `Podfile` file: undefined method `pod' for main:Object.

 #  from /Users/peipeiliu/works/FT/Podfile:7
 #  -------------------------------------------
 #  flutter_application_path = './vira_flutter/'
 >  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
 #
 #  -------------------------------------------
```

**Comment by OPTJoker** [comment]
我 也 是 ！

**Comment by OPTJoker** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E227, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)
• No issues found!

**Comment by OPTJoker** [comment]
====== Flutter Doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E227, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)
• No issues found!

====== PodFile
flutter_application_path = '../flutter_library/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Jiazheng' do  
install_all_flutter_pods(flutter_application_path)
···· some code else ···
end

===== pod --version
1.7.5

==========================================
[!] Invalid `Podfile` file: undefined method `pod' for main:Object.

 #  from /Users/allen/Documents/Project/jz_app_ios/Jiazheng/Podfile:14
 #  -------------------------------------------
 #  flutter_application_path = '../flutter_library/'
 >  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
 #  -------------------------------------------

**Comment by OPTJoker** [comment]
====== Flutter Doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E227, locale
zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)
• No issues found!

====== PodFile
flutter_application_path = '../flutter_library/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Jiazheng' do
install_all_flutter_pods(flutter_application_path)
···· some code else ···
end

===== pod --version
1.7.5

====================错误 信息======================
[!] Invalid Podfile file: undefined method `pod' for main:Object.

from /Users/allen/Documents/Project/jz_app_ios/Jiazheng/Podfile:14
-------------------------------------------
flutter_application_path = '../flutter_library/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

-------------------------------------------

**Comment by OPTJoker** [comment]
I have the same problem：
====== Flutter Doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E227, locale
zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)
• No issues found!

====== PodFile
flutter_application_path = '../flutter_library/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Jiazheng' do
install_all_flutter_pods(flutter_application_path)
···· some code else ···
end

===== pod --version
1.7.5

==================== 错误 信息
[!] Invalid `Podfile` file: undefined method `pod' for main:Object.

 #  from /Users/allen/Documents/Project/jz_app_ios/Jiazheng/Podfile:14
 #  -------------------------------------------
 #  flutter_application_path = '../flutter_library/'
 >  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
 #  
 #  -------------------------------------------

**Comment by OPTJoker** [comment]
I have the same problem：
====== Flutter Doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E227, locale
zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)
• No issues found!

====== PodFile
flutter_application_path = '../flutter_library/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Jiazheng' do
install_all_flutter_pods(flutter_application_path)
···· some code else ···
end

===== pod --version
1.7.5

==================== 错误 信息
`
[!] Invalid `Podfile` file: undefined method `pod' for main:Object.
 #  from /Users/allen/Documents/Project/jz_app_ios/Jiazheng/Podfile:14
 #  -------------------------------------------
 #  flutter_application_path = '../flutter_library/'
 >  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
 #  
 #  -------------------------------------------`

**Comment by OPTJoker** [comment]
I have the same problem：

====== Flutter Doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E227, locale
zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)
• No issues found!

====== PodFile
flutter_application_path = '../flutter_library/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Jiazheng' do
install_all_flutter_pods(flutter_application_path)
···· some code else ···
end

===== pod --version
1.7.5

**Comment by jmagman** [comment]
@OPTJoker You are on the stable channel. Adding Flutter to an existing app is experimental and only available on the master channel. https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#intro.  See https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels for instructions on how to switch to master.

@gaodeying Can you paste the contents of /Users/garodeying/Desktop/Git_FlutterHybrid/flutter_to_native/.ios/Flutter/podhelper.rb

Then regenerate it by running:
```
cd /Users/garodeying/Desktop/Git_FlutterHybrid/flutter_to_native
rm -rf .ios
flutter build ios
```
Did the podhelper.rb change?  Does it work now?

**Comment by OPTJoker** [comment]
> @OPTJoker You are on the stable channel. Adding Flutter to an existing app is experimental and only available on the master channel. https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#intro. See https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels for instructions on how to switch to master.
> 
> @gaodeying Can you paste the contents of /Users/garodeying/Desktop/Git_FlutterHybrid/flutter_to_native/.ios/Flutter/podhelper.rb
> 
> Then regenerate it by running:
> 
> ```
> cd /Users/garodeying/Desktop/Git_FlutterHybrid/flutter_to_native
> rm -rf .ios
> flutter build ios
> ```
> 
> Did the podhelper.rb change? Does it work now?

Yeah, it works!   thk U : )

**Comment by OPTJoker** [comment]
@jmagman Yeah, it works! thk U !

**Comment by jmagman** [comment]
@gaodeying Can you paste your `flutter doctor -v`?  We can't diagnose if we don't know what commit and channel you were on.

**Comment by gaodeying** [comment]
@jmagman 
`cd /Users/garodeying/Desktop/Git_FlutterHybrid/flutter_to_native
rm -rf .ios
flutter build ios`

It work for me. Thank u very much. you r so beautiful

**Comment by jmagman** [comment]
I added podhelper regeneration to the migration instructions. https://github.com/flutter/flutter/wiki/Upgrading-Flutter-added-to-existing-iOS-Xcode-project#regenerate-podhelperrb

**Comment by Hixie** [comment]
@gaodeying We are glad that your problem has been resolved. Please note that "you r so beautiful" is not really an appropriate response in a professional setting and we would rather you avoid making comments that refer to people's appearances. Thanks.

**Comment by kongdelu** [comment]
@jmagman thanks!,it works
