### ISSUE TITLE
flutter create iosapp

### ISSUE THREAD

**Issue by SilmeLyy** [flutter/flutter#37372]
cd iosapp/ios
pod install 
[!] No `Podfile' found in the project directory.

flutter run 
Command PhaseScriptExecution failed with a nonzero exit code

why no Podfile directory

flutter --version
Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (13 days ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0

**Comment by jmagman** [comment]
Do you have plugins?  If so, have you run `flutter packages get` since you added them?  You don't need to pod install unless you have plugins.  Can you paste your pubspec.yaml?

**Comment by SilmeLyy** [comment]
> Do you have plugins? If so, have you run `flutter packages get` since you added them? You don't need to pod install unless you have plugins. Can you paste your pubspec.yaml?

name: iosapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by SilmeLyy** [comment]
> Do you have plugins? If so, have you run `flutter packages get` since you added them? You don't need to pod install unless you have plugins. Can you paste your pubspec.yaml?

Wrong full snapshot version, expected '1d7acad1540192ac459cf60344efb7c1' found '0c73eb70aa4d30f450273cb424be8c62'

Compiler failed on lib/main.dart
Failed to package /Users/mihisao/Desktop/HTML5/Flutter/one_app.
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by jonahwilliams** [comment]
This sounds like the tool's cache might have failed to update properly. To remedy this, try deleting the existing cache and re-running flutter:

```
rm -rf $FLUTTER_ROOT/bin/cache
flutter
```

**Comment by jmagman** [comment]
You don't have any plugins, so you shouldn't need to run `pod install`, and no Podfile is generated.
Please reopen if you think there's another issue here.
