### ISSUE TITLE
I have a problem with my Flutter application that I use flutter_screenutil when I use widget about animation

### ISSUE THREAD

**Issue by progressorTCH** [flutter/flutter#37381]
I have some questions about animation.
I am developing a project,you know,an App must fit to all type of mobile phone.
So I used flutter_screenutil but when I use it in some widget about animation.
I build an apk with release then I saw that where I use flutter_screenutil is unuseful.
But when I build an apk with debug flutter_screenutil is useful.
Is there any friend tell me how to solve?
Thank you!

**Comment by progressorTCH** [comment]
Oh,I have try another idea.That get mobile phone size then do something like this:
width/750 * wantWidth
but it unuse too.

**Comment by BondarenkoStas** [comment]
@progressorTCH Is the issue still relevant? Do you mean that flutter_screenutil had some error while building a release version?

**Comment by progressorTCH** [comment]
Not always，just when I used animation widget



发自我的iPhone


------------------ Original ------------------

**Comment by BondarenkoStas** [comment]
@progressorTCH Please provide your ```flutter doctor -v``` output. Also some small self-contained app that demonstrates the issue would be very helpful. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
