### ISSUE TITLE
image_picker cannot pop native UIPhotoPickerView on ios

### ISSUE THREAD

**Issue by beargates** [flutter/flutter#37385]
When add my flutter_app into an existing native ios app, i find i cannot open the view;
But i modify the  'image_pick''s source-code by this:

(This code is on "ImagePickerPlugin.m" file:)

`UIViewController *viewController = [UIApplication sharedApplication].delegate.window.rootViewController;`

when replace with :
`UIViewController *topRootViewController = [[UIApplication  sharedApplication] keyWindow].rootViewController;`

it works!

**Comment by jmagman** [comment]
\cc @cyanglaz

**Comment by cyanglaz** [comment]
\cc @xster 
Seems like in add to app, somehow [UIApplication sharedApplication].delegate.window doesn't return the correct window object?

**Comment by beargates** [comment]
> \cc @xster
> Seems like in add to app, somehow [UIApplication sharedApplication].delegate.window doesn't return the correct window object?

i'm a FE, not ios developer

**Comment by xster** [comment]
delegate.window.rootViewController and keyWindow.rootViewController are generally the same but not always. See https://stackoverflow.com/questions/21698482/what-is-the-difference-between-uiapplication-sharedapplication-delegate-window-a. But you can always have multiple UIWindows. 

@cyanglaz what expectations does the plugin have on the view controller it's trying to retrieve? We certainly can't expect it to be the FlutterViewController in add-to-app cases but AFAICT, the plugin isn't making that assumption.

**Comment by cyanglaz** [comment]
@xster Ah, I see. The plugin expects to retrieve the rootViewController, it doesn't necessarily have to be the FlutterViewController. Although I think we should update it to retrieve the top most view controller instead, to make it more compatible for add to app situations.

@beargates I think in your case, there was another UIWindow being displayed on top of the `[UIApplication sharedApplication].delegate.window`. It could be helpful to get more details on the app is doing when initializing the plugin.

**Comment by darshankawar** [comment]
@beargates 
Are you still experiencing this issue using [latest](https://pub.dev/packages/image_picker/install) `image_picker` plugin ?
If so, can you provide `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
