### ISSUE TITLE
I have a problem to add flutter to my existing iOS app

### ISSUE THREAD

**Issue by zhouyangyng** [flutter/flutter#37382]
I have run 'flutter create -t module my_flutter' in terminal and created a dirctory. Then I modify Podfile:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../my_flutter/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target '123' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  install_all_flutter_pods(flutter_application_path)
  
end
```
run 'pod install' and failed with '[!] Invalid `Podfile` file: undefined method `pod' for main:Object':
![image](https://user-images.githubusercontent.com/22138883/62283859-10fa4d00-b485-11e9-9dc7-262e18e19c85.png)

**Comment by jmagman** [comment]
Does `../my_flutter/.ios/Flutter/podhelper.rb` exist?

**Comment by xster** [comment]
Can you paste your `flutter doctor -v` output?

**Comment by zhouyangyng** [comment]
> ../my_flutter/.ios/Flutter

yes, podhelper.rb exists.
![image](https://user-images.githubusercontent.com/22138883/62338266-7e9c8c80-b50a-11e9-8111-71e26ecec1fb.png)

**Comment by zhouyangyng** [comment]
> flutter doctor -v

Here is the output:

```
➜  Flutter flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.4 at /Users/xmly/flutter
    • Framework revision 20e59316b8 (2 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/xmly/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • zhouyangyng • 00008020-0005598E1438002E            • ios • iOS 12.3.1
    • iPhone 8    • E6CEA99A-4A09-429C-93A1-AF2B71C02E28 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by jmagman** [comment]
You are on the stable channel. Adding Flutter to an existing app is experimental and only available on the master channel. https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#intro

See https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels for instructions on how to switch to master!

**Comment by zhouyangyng** [comment]
> You are on the stable channel. Adding Flutter to an existing app is experimental and only available on the master channel. https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#intro
> 
> See https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels for instructions on how to switch to master!

Thanks! I'll try it by master channel.
