### ISSUE TITLE
I have a problem with my Flutter application that I use flutter_screenutil when I use widget about animation

### ISSUE THREAD

**Issue by progressorTCH** [flutter/flutter#37380]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by jerald-jacob** [comment]
This plugin is still under development, and some APIs might not be available yet.
https://github.com/OpenFlutter/flutter_screenutil

**Comment by BondarenkoStas** [comment]
Duplicate of #37381
