### ISSUE TITLE
Camera/Video save to gallery

### ISSUE THREAD

**Issue by AriCohen8** [flutter/flutter#37398]
There is currently no first party plugin to save an image or video to a phone's gallery. Also path_provider does not even provide the path. There are some third party plugins being developed for this which currently do not work for video. Can I request this be catered for by either an existing first party plug-in or a new one?

I am a new to mobile development so apologies if there is a workaround I have not spotted (I have searched SO and Flutter Github issues before posting this).

**Comment by tvolkert** [comment]
@AriCohen8 we're unlikely to add such a new plugin to Flutter's repository, instead relying on the flutter community to provide a rich set of plugins.  As such, I'm closing this issue.
