### ISSUE TITLE
flutter drive device identifier

### ISSUE THREAD

**Issue by ireinhart** [flutter/flutter#37395]
## Use case

We run more than one android emulator and have now the problem, that we can't select the correct AVD with the flutter -d '...' drive command.

Could you please change the line 
     https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L760

to

        info['model'] = cleanAdbDeviceName(info['model']) + ' ' + deviceID;

Than it is possible to select the emulators more specific.

Look at https://github.com/flutter/flutter-intellij/issues/1244 to get an idea of the details (if I am unclear).

**Comment by timsneath** [comment]
Thanks for the feedback, @ireinhart. Curious: is there a reason why you're not comfortable submitting this as a pull request? Thank you again!

**Comment by ireinhart** [comment]
Ok, thanks for your hint. I found a better solution and create a PR.

See https://github.com/flutter/flutter/pull/38296
