### ISSUE TITLE
The following assertion was thrown building IndexPage(dirty, dependencies: [_InheritedProviders]): I/flutter (20675): 'package:provide/provide.dart': Failed assertion: line 258 pos 12: 'provider != null': is not true.

### ISSUE THREAD

**Issue by jian007** [flutter/flutter#37393]
Resolving dependencies...                                           5.4s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        15.4s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                         4.2s
I/flutter (20675): 0
I/flutter (20675): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (20675): The following assertion was thrown building IndexPage(dirty, dependencies: [_InheritedProviders]):
I/flutter (20675): 'package:provide/provide.dart': Failed assertion: line 258 pos 12: 'provider != null': is not true.
I/flutter (20675):
I/flutter (20675): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (20675): more information in this error message to help you determine and fix the underlying cause.
I/flutter (20675): In either case, please report this assertion by filing a bug on GitHub:

**Comment by mannprerak2** [comment]
Please provide your use-case details and steps to reproduce,
Otherwise, you can instead use [Provider](https://pub.dev/packages/provider#-analysis-tab-) or [Scoped Model](https://pub.dev/packages/scoped_model) packages

**Comment by jian007** [comment]
> 请提供您的用例详细信息和重现步骤，
> 否则，您可以使用[Provider](https://pub.dev/packages/provider#-analysis-tab-)或[Scoped Model](https://pub.dev/packages/scoped_model)包

So I'm done. I'm going to create a new project and I'm going to copy the original code and run it again. There we go.
