### ISSUE TITLE
Hot-reload does not work when import plugins into the project

### ISSUE THREAD

**Issue by DQvsRA** [flutter/flutter#37392]
Hello Flutter team,

In my application, I need specific code for one of the plugins (video_player) and I added the whole "plugins" folder into the root of the project, did change the code, it works, however because of the dependencies in the plugin's projects hot-reload stop working and analysis tool show a lot of errors. My question is how can I get rid of them?

![Screenshot 2019-08-01 at 16 57 14](https://user-images.githubusercontent.com/442111/62304373-24ee8080-b47e-11e9-96c9-24a61b23c9f2.jpg)

**Comment by jmagman** [comment]
Have you run `flutter packages get` without getting an error?  If that worked, try restarting your IDE.

**Comment by DQvsRA** [comment]
I have tried it many times, looks like some of the plugins can't be updated from the root of project or something. Video plugin test file does not implement `setStreamType`.

**Comment by jmagman** [comment]
It can't find the packages so it doesn't look like they updated.  What does "some of the plugins can't be updated from the root of project or something" mean?

**Comment by DQvsRA** [comment]
Good day @jmagman `some of the plugins can't be updated from the root of project or something` means that running `flutter packages get` does not update dependencies from imported github `plugins` repo in the root of the project.

**Comment by jmagman** [comment]
@DQvsRA Is there an error message?

**Comment by DQvsRA** [comment]
No errors in my project, just a lot of red in the `plugins` folder. And Dart Analysis telling "Reload not performed. Analysis issues found".

**Comment by DQvsRA** [comment]
However when I open the Event Log I can see `Dart Analyzer Error: Encountered a Dart Analysis Server error`.

```
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.4.0`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6 unknown, screens 1920x1080, 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/kj/92h1mpws2_5_ztlyzq0s465m_54_06/T/report.txt

```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Analysis failed: /Users/vladimir.minkin/Documents/Projects/Repos/DTAG/Videoload/videoload/test/widget_test.dart context: exception_20190807_192800_779
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      new _LibraryResynthesizer (package:analyzer/src/summary/resynthesize.dart:666:32)
#2      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:384:56)
#3      __InternalLinkedHashMap
```

**Comment by DQvsRA** [comment]
Hi @jmagman, do you need any additional information from my side?

**Comment by jmagman** [comment]
Adding the tool label, not sure what else to ask to make this actionable.

**Comment by jonahwilliams** [comment]
The issue with the analysis server crashing should be opened at github.com/dart-lang/sdk. Otherwise, there is nothing actionable for us here. The feature to prevent hot reload during analysis errors is one of intellij and not flutter
