### ISSUE TITLE
Calling showSnackBar() twice in a row will fail

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#374]
If I'm reading the code right, if you call showSnackBar() while an existing snack bar is up, we'll just replace the previous one with the new one, rather than doing a transition or something. Then later we'll set the placeholder to null even while one of the snack bars is still up.

**Comment by HansMuller** [comment]
https://github.com/flutter/flutter/pull/376 adds an assert() for this case

I think the right thing to do would be to dismiss the old snackbar and show the new one. Exactly what "dismiss" means in this context is TBD.

**Comment by HansMuller** [comment]
http://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-usage
> There is only ever one snackbar displayed. When a second snackbar is triggered while the first is displayed, the first should start the contraction motion downwards before the second one animates upwards.
