### ISSUE TITLE
Add semantics child tree ID to semantics node

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#37400]
Internal: b/144521534

Internal: b/143427154

A child tree ID field should be added to flutter's semantics node struct.

Mirror issue for https://b.corp.google.com/issues/135114539; discussion should occur there.

**Comment by Hixie** [comment]
We don't currently understand this request.

**Comment by Hixie** [comment]
This is about having a way to graft webviews' accessibility trees into our accessibility tree, in other platforms than iOS/Android.

Seems like ideally we'd do this the same way we do for iOS/Android.

**Comment by Hixie** [comment]
Blocked behind FL-250.

**Comment by Hixie** [comment]
Is this fixed?

**Comment by cbracken** [comment]
The Flutter side of this is fixed, the internal side of this is expected to be fixed within days.

**Comment by cbracken** [comment]
This is was fixed internally.
