### ISSUE TITLE
Colors.grey should be Colors.gray or Colours.grey

### ISSUE THREAD

**Issue by dfmiller** [flutter/flutter#37406]
Colors is American English
grey is British English

According to https://material.io/design/color/the-color-system.html#tools-for-picking-colors it should be Colors.gray

**Comment by timsneath** [comment]
Adding @Hixie to investigate whether he'd add this to #24722. Frustratingly, this is inconsistent between `CupertinoColors` and the Material `Colors` class.

**Comment by Hixie** [comment]
added to https://github.com/flutter/flutter/issues/24722.

**Comment by HansMuller** [comment]
I'm going to close this as the change is now covered by #24722

**Comment by dfmiller** [comment]
This seems like a simple request. How does adding Colors.gray and Colors.blueGray create a breaking change?

**Comment by Hixie** [comment]
Adding is fine. It's the removing of the now redundant value that's the issue.
