### ISSUE TITLE
flutter - share folder smb on ubuntu server

### ISSUE THREAD

**Issue by 007fred50** [flutter/flutter#37412]
Hello,

flutter run, on mount drev.

i trying to move folder to mount drev it works fine.
then i trying to mount smb to my computer it failed.

Thanks for helping me :)

**Comment by timsneath** [comment]
Thanks for your question. The Flutter issue database is for bugs, rather than requests for help. You might be better off posting this on [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or a support forum. Sorry -- we simply aren't able to do support on GitHub.
