### ISSUE TITLE
webview_flutter does not work with firebase_messaging

### ISSUE THREAD

**Issue by arieosdmin** [flutter/flutter#37414]
When using both dependencies I get the problem of duplicate classes.

**Comment by mannprerak2** [comment]
can you provide more details and the exact error message?

**Comment by arieosdmin** [comment]
I just started a new flutter project in android studio.
The only thing I do is adding 
  firebase_messaging: "^5.1.2"
  webview_flutter: "^0.3.10+4"
Adding it seperately it works without any problem.

Error:
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/32.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/50.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/22.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/18.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/47.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/41.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/35.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/44.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/38.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/1.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/11.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/10.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/24.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/15.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/16.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/5.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/7.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/0.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/14.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/19.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/20.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/23.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/8.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/4.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/21.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/26.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/13.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/9.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/12.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/25.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/17.jar, /Users/osdm/AndroidStudioProjects/osdm_4_0/build/app/intermediates/transforms/dexBuilder/debug/6.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel

**Comment by mannprerak2** [comment]
Hi @arieosdmin,
I successfully reproduced your error and was able to fix this, Do the following.

1. Delete your Android Folder
2. Open a terminal in your project directory and type
```bash
flutter create --androidx .
``` 
(the dot at the end is essential, basically, we have to migrate the project to use AndroidX. )
3. Open your android/build.gradle file and in the 'buildscript', do the following
```gradle
buildscript{
.
.
//add this
subprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'androidx.lifecycle') {
                    details.useVersion "2.0.0"
                }
                else if (details.requested.group == 'androidx.localbroadcastmanager') {
                    details.useVersion "1.0.0"
                }
                else if (details.requested.group == 'androidx.core' 
                        && !details.requested.name.contains('androidx.core:core')) {
		            details.useVersion "1.0.0"
                }
            }
        }
    }
}
``` 
Thats it :) I hope this works for you. Let me know

**Comment by arieosdmin** [comment]
It worked.
Have done what you said and it fixed the problem. After that done it to my real project and it fixed the problem. 

Thank you.
