### ISSUE TITLE
Performance issues between versions

### ISSUE THREAD

**Issue by angel66bol** [flutter/flutter#37427]
Hello everyone, I have a map application using flutter_map, I have the following scenario: when I use v1.5.4-hotfix.2 the application does not present any performance problems, but when I do it with flutter v1.7.8 + hotfix.3 or v1 .7.8 + hotfix.4 the application becomes slow even until it hangs. Any suggestions will be very grateful

**Comment by TahaTesser** [comment]
Hi @angel66bol 
Are you still experiencing this issue on newer version of Flutter?
If yes, can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment]
@angel66bol 
I hope it's fixed, closing,
if you disagree please write in the comments and I will reopen it
Thank you
