### ISSUE TITLE
TextField cursor movement causes issues with maxLength

### ISSUE THREAD

**Issue by adkam** [flutter/flutter#37420]
I found that there are a number of documented issues related to the TextField class, but I have not seen this issue be addressed as of yet. In my textField widget, maxLength is set to 255. As you can see in the character counter with the attached gif, the user cannot advance past 255 characters. However, if the user moves the cursor to a location that is not at the end of the text field and then begins to type, then the text at the end of the line starts to get cut off.

![TextFieldBug](https://user-images.githubusercontent.com/17662807/62324873-65e39680-b478-11e9-9581-a55600a9e274.gif)

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale
    en-US)
    • Flutter version 1.7.8+hotfix.3 at
      /Users/ashishkamath/Desktop/Kumanu/flutter
    • Framework revision b712a172f9 (3 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/ashishkamath/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Users/ashishkamath/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5522156/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.3

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/ashishkamath/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5522156/Android
      Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[!] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone Xʀ • 64FFB7B1-B741-4FA2-9CB8-A4647F8E1A5C • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

! Doctor found issues in 1 category.
```

**Comment by justinmc** [comment]
I tried to look at what native Android does in this situation, and it seems to be very similar and equally weird.  If I go to the credit card number entry field in Google Play, fill up the field with numbers, and then move the cursor to the center, I can still enter characters.  New characters are added to the right of the cursor while the cursor stays in the same place.

Is anyone else seeing similar behavior in native max length fields on Android or iOS?  Should Flutter try to mimic that behavior?

**Comment by yangchao110** [comment]
I have the same problem, when input contain emotion and reach the maxlength,the cursor will jump to the textfield center, flutter version is hotfix 1.7.8

**Comment by Mohammad-fs** [comment]
@justinmc The default behavior of EditText in the native Android when we set maxLength property is not like that we have in the flutter TextField:

```
android:maxLength="10"
```

![Feb-09-2020 11-33-54](https://user-images.githubusercontent.com/57225262/74098947-3f8f6980-4b33-11ea-8f52-67175594d293.gif)

**Comment by Omar-Fayad** [comment]
Any updates on this issue ?!

**Comment by justinmc** [comment]
Well here's one super simple proposal for preventing characters from being entered in the center of a maxed-out field: https://github.com/flutter/flutter/pull/52130
