### ISSUE TITLE
flutter has exited unexpectedly || after latest upgrade

### ISSUE THREAD

**Issue by ijogendrajat** [flutter/flutter#37429]
![image](https://user-images.githubusercontent.com/47884778/62329957-f8b21e80-b4d4-11e9-9f3f-949f9b3bc4cf.png)

**Comment by timsneath** [comment]
Please include the results of `flutter doctor -v` in text form. Thanks! (The `-v` flag is for "verbose", and we need it in text form for easy searching.)

**Comment by ijogendrajat** [comment]
![image](https://user-images.githubusercontent.com/47884778/62334315-db854c00-b4e4-11e9-9499-e1dc7306474a.png)

**Comment by ijogendrajat** [comment]
Thanks
