### ISSUE TITLE
Is it still recommended to use `const Widget()`

### ISSUE THREAD

**Issue by kjeremy** [flutter/flutter#37426]
Is it still recommended to construct Widgets as `const` if they have a `const` constructor or does dart take care of that for us?

**Comment by jonahwilliams** [comment]
You always have to specify whether or not to use `const`, since doing so will change the semantics of the program. Example:

```
 foo([]);
...
foo(List<Object> xs) => xs.add(2);
```

If we tried to automatically infer `[]` as const, this program would crash at runtime.

**Comment by kjeremy** [comment]
Is there a lint to tell when it's applicable in the widget tree?

**Comment by jonahwilliams** [comment]
Yes! See https://dart-lang.github.io/linter/lints/prefer_const_constructors.html

**Comment by kjeremy** [comment]
@jonahwilliams 

So just to be clear: if I create a `Text` widget in my tree as `const Text("foo")` vs `Text("foo")` that will perform better? If that were the case I'm surprised that the lint isn't enabled by default.

**Comment by kjeremy** [comment]
Oh I see why it's not enabled by default. I just tried to make the title `Text` below `const` and it failed because of `theme`

```
ListTile(
                title: Text('Network',
                    style: TextStyle(color: theme.accentColor))),
```
