### ISSUE TITLE
`flutter analyze --flutter-repo` should detect if user has not run `flutter update-packages`

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#37439]
Anecdotally, it seems very common to have `flutter analyze --flutter-repo` to complain about missing import targets, e.g.

`Target of URI doesn't exist: 'package:flutter_test/flutter_test.dart'`

It would be nice if we could do *some* kind of check to detect if `pub get` had ever been run, perhaps check for `.packages` file?

**Comment by Hixie** [comment]
going to close this for now, if we ever want to do it let's just do it but in practice everyone probably just has a script that runs both back to back now anyway.

**Comment by christopherfujino** [comment]
Turns out this was not so entertaining after all.
