### ISSUE TITLE
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2216 pos 12: '!_debugLocked':

### ISSUE THREAD

**Issue by kshivam117** [flutter/flutter#37430]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by timsneath** [comment]
Hi @kshivam117  -- we need a lot more to go on than this, as per the new issue template. What were you doing at the time? Is there some repro code? What version of Flutter are you using (`flutter doctor -v`)? Thanks!
