### ISSUE TITLE
Centralize performance metrics, provide universal alerts, and improve performance dashboard

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#37434]
Our current [performance dashboard](https://flutter-dashboard.appspot.com/benchmarks.html) is very slow to load and does not support
- zoom in or zoom out in time
- move the time window
- automatic regression alerts
- show known regressions on a commit

It would be nice to migrate all our performance benchmarks data to some well maintained dashboard such as https://chromeperf.appspot.com or https://perf.skia.org to support those functions.

It would be even better if we can port all our performance metrics in various dashboards to a single place for easier discovery and analysis. We can also share the alert mechanism among all of them.

At most, we may setup 2 dashboards, 1 for internal, and 1 for public access. Any more than that makes it difficult to see the full picture and maintain.

There might be multiple views in a single dashboard to accommodate different audiences. But having multiple versions of UIs, tools, and protocols seems unnecessary.

**Comment by liyuqian** [comment]
This may let us react to regressions faster. For example, it seems that the regression https://github.com/flutter/website/issues/2983 took us a month to react.  That issue drops 2/3 of our downloads, although many of them may be replaced by `git clone`, so it's unclear how many new users we've lost exactly by having a more involved installation process. 

See also https://github.com/flutter/cocoon/issues/363#issuecomment-532308996

**Comment by godofredoc** [comment]
This is something we can solve by reusing some of the tools already available on golem.

**Comment by liyuqian** [comment]
We've had https://flutter-perf.skia.org/ running. Our next step is to enable proper loggings through GAE handlers so it can be more reliable: https://github.com/flutter/flutter/issues/51607

**Comment by liyuqian** [comment]
This is ongoing. Our latest PR is https://github.com/flutter/flutter/pull/69996.

**Comment by kf6gpe** [comment]
We've migrated to skia-perf, which addresses the issues described above. I'm closing this and leaving #51607 open.
