### ISSUE TITLE
FlutterView interface

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#3744]
Master tracking issue for the build system refactoring described here:

https://docs.google.com/document/d/1DOfwpL6VojCAG_zjjcA_z5ekF7rTIohV8dWn2o7_IME/edit

This will hopefully allow developers to use CocoaPods (on iOS) and Maven repositories (on Android)

**Comment by abarth** [comment]
This interface now exists on both Android and iOS.  There's still a bunch of work left to integrate it into the developer workflows, but I think we can close the issue and open more specific issues.
