### ISSUE TITLE
Cloud_functions error  Exception: Unable to call function

### ISSUE THREAD

**Issue by AbhishekVel** [flutter/flutter#37453]
Code:
```
  CloudFunctions cf = CloudFunctions(region: 'us-central1');
  try {
    HttpsCallable callable = cf.getHttpsCallable(
      functionName: 'helloWorld',
    );

    dynamic resp = await callable.call();

    print(resp);
  } on CloudFunctionsException catch (e) {
    print('caught firebase functions exception');
    print(e.code);
    print(e.message);
    print(e.details);
  } catch (e) {
    print('caught generic exception');
    print(e);
  }

```

results: flutter: caught generic exception
flutter: Exception: Unable to call function helloWorld

**Comment by elvisgn** [comment]
@AbhishekVel : Can you please post the solution to the problem above...I'm having the same problem...nothing seems to work

**Comment by parth22** [comment]
me also have the same issue i'm using 
cloud_functions: ^0.4.1+1

**Comment by jgrocott** [comment]
@elvisgn @parth22 Not sure if this will resolve your issue however I had the same problem and the fix for me was to provide the firebase app instance and region to the CloudFunctions constructor;

```
final CloudFunctions firebaseFunctions =
    new CloudFunctions(app: FirebaseApp.instance, region: 'asia-northeast1');

final HttpsCallable createUserFunction =
            firebaseFunctions.getHttpsCallable(
          functionName: 'onboardComplete',
        );

HttpsCallableResult resp = await createUserFunction.call(store.state.onboarding.toJson());
```

**Comment by walsha2** [comment]
@jgrocott thanks for that recommendation. I tried it, but it did not seem to work. Not sure if I have the same issues as this thread, but maybe someone has an answer or idea.

The weird thing is that my function executes just fine, the firebase logs show that it worked fine, it performs the necessary tasks but ultimately the return from `.call()` always errors out - even though the function completed. The stack trace is not all that useful either - thats pretty much it below:

```
Unhandled Exception: Instance of 'CloudFunctionsException'
#0      HttpsCallable.call 
package:cloud_functions/src/https_callable.dart:48
<asynchronous suspension>
```

Any thoughts? Even though it fails in flutter code, it executes so my only solution right now is to `try/except` the function call and assume it always passes. Not safe so I dont want to keep this in place for long. @AbhishekVel  how did you resolve your issue?

**Comment by elvisgn** [comment]
Hi,
I got it fixed but I'm not sure it works for all...anyway, try it.

Use `cloud_functions: 0.4.0+2`.
My android build.gradle contains `implementation 'com.google.firebase:firebase-functions:18.1.0'`, I've also seem working projects without anything being set in the build.gradle
No region setting, just function name in the HttpsCallable call.

If it works, let everyone know. Best of luck.

**Comment by cmregazzo** [comment]
Hi,

I have the same problem:

[ERROR: flutter / lib / ui / ui_dart_state.cc (148)] Unhandled Exception: Instance of 'CloudFunctionsException'
E / flutter (11096): # 0 HttpsCallable.call (package: cloud_functions / src / https_callable.dart: 48: 9)

I am using 'com.google.firebase: firebase-functions: 18.1.0' within the Android APP build.gradle and my cloud_functions plugin version is ^ 0.4.1 + 4.

Is there any defensive solution?

Thank you,

Cristian Regazzo

**Comment by jaddoescad** [comment]
Same issue with ^ 0.4.1+4.

**Comment by elvisgn** [comment]
> Hi @elvisgn,
> 
> I have the same problem:
> 
> [ERROR: flutter / lib / ui / ui_dart_state.cc (148)] Unhandled Exception: Instance of 'CloudFunctionsException'
> E / flutter (11096): # 0 HttpsCallable.call (package: cloud_functions / src / https_callable.dart: 48: 9)
> 
> I am using 'com.google.firebase: firebase-functions: 18.1.0' within the Android APP build.gradle and my cloud_functions plugin version is ^ 0.4.1+4.
> 
> Is there any defensive solution?
> 
> Thank you,
> 
> Cristian Regazzo

Try versions within 0.4.0.

**Comment by jsakhnin** [comment]
The cloud_functions package did not work for me either, I got the same error.

Instead, I used the dart http package. Below is an example of calling a hello world function by its url:

`import 'package:http/http.dart' as http;

Future<http.Response> helloWorld() async {
    var url = 'YOUR_FUNCTION_URL_HERE';

    Map<String, String> headers = {"Content-type": "application/json"};
    String jsonInput = '{"name": "from the other side"}';

    final response =
        await http.post(url, headers: headers, body: jsonInput);

    if (response.statusCode == 200) {
      // If server returns an OK response, parse the JSON.
      print('body: ' + response.body);
    } else {
      // If that response was not OK, throw an error.
      throw Exception('Failed to load post');
    }
  }`
