### ISSUE TITLE
flutter install error

### ISSUE THREAD

**Issue by XXEgges** [flutter/flutter#37458]
flutter -v error

```
awen@awen-mac  ~/develop  flutter -v
Downloading Dart SDK from Flutter engine eac7ef065dbd1056943a9ae46d0cba993caf3788...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     56      0 --:--:-- --:--:-- --:--:--    56
[/Users/awen/develop/flutter/bin/cache/dart-sdk-darwin-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/awen/develop/flutter/bin/cache/dart-sdk-darwin-x64.zip or
        /Users/awen/develop/flutter/bin/cache/dart-sdk-darwin-x64.zip.zip, and cannot find /Users/awen/develop/flutter/bin/cache/dart-sdk-darwin-x64.zip.ZIP, period.

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md
```

**Comment by ketanm** [comment]
@XXEgges 
As error informs, try to repeat install steps properly. 
Before doing it again, It may be useful to clear the cache by just deleting partial files or all files from `/Users/awen/develop/flutter/bin/cache/`.

**Comment by BondarenkoStas** [comment]
@XXEgges is the issue still relevant?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by glm-mawla** [comment]
run these :
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

then try again 💯
