### ISSUE TITLE
Plans to Integrate with angular 2?

### ISSUE THREAD

**Issue by Andruj** [flutter/flutter#3746]
I have been using the angular 2 beta with dart, and was wondering if there are plans to integrate with flutter, similar to NativeScript?

**Comment by abarth** [comment]
Sounds like a question for the Angular folks.  In any case, not something for this issue tracker.

**Comment by sethladd** [comment]
Thanks for reaching out! The Flutter team isn't working on making Angular 2 work on Flutter.

(btw, feel free to direct questions to our mailing list: flutter-dev@googlegroups.com)

Keep the feedback coming!

**Comment by ansarizafar** [comment]
Flutter team should consider Flutter integration with Angular2. It would be a game changer for mobile app development.
