### ISSUE TITLE
[google_sign_in] Signing out doesn't work

### ISSUE THREAD

**Issue by klaszlo8207** [flutter/flutter#37465]
Is there any way to signIn with a different user second time?

1, First I signIn with a google account (I can select from a dialog list of the accounts)
2, Second time the signIn method just using the firstly selected account, and Log in with that.

Any way to select an other account from the first list and login with that?

Thanks

**Comment by tomalabaster** [comment]
Is signing out first not appropriate?

**Comment by klaszlo8207** [comment]
Tried that, not worked. Only thing is helped me when I deleted all my app's datas.

**Comment by iapicca** [comment]
Hi @klaszlo8207
I believe that the correct way to proceed is what @tomalabaster proposed,
therefore the issue that signing out doesn't work in your case.
If you are still experiencing this issue with the latest stable version of flutter and [google_sign_in](https://pub.dev/packages/google_sign_in)?
please provide your updated `flutter doctor -v` 
and your `flutter run --verbose` and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by klaszlo8207** [comment]
now it is working, with the new library, so I think they just FIXED the probleme, thanks

**Comment by iapicca** [comment]
I'm glad to hear that 
thank you for letting me know @klaszlo8207
