### ISSUE TITLE
Application name is not set

### ISSUE THREAD

**Issue by VnurtureTechnologies** [flutter/flutter#37467]
is:issue is:open Application name is not set. Call Builder#setApplicationName.

**Comment by ketanm** [comment]
Provide more information so that someone can help you.

**Comment by BondarenkoStas** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don’t hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
