### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 0123cf** [flutter/flutter#37477]
Last login: Fri Aug  2 20:33:24 on ttys001
xiexiuyuedeMacBook-Pro:~ xiexiuyue$ flutter doctor
Error: The Flutter directory is not a clone of the GitHub project.
       The flutter tool requires Git in order to operate properly;
       to set up Flutter, run the following command:
       git clone -b stable https://github.com/flutter/flutter.git
xiexiuyuedeMacBook-Pro:~ xiexiuyue$ ls
Applications	Documents	Library		Music		Public
Desktop		Downloads	Movies		Pictures
xiexiuyuedeMacBook-Pro:~ xiexiuyue$ cd Documents/
xiexiuyuedeMacBook-Pro:Documents xiexiuyue$ git clone -b stable https://github.com/flutter/flutter.git
Cloning into 'flutter'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (11/11), done.
Receiving objects:  43% (78291/181161), 41.57 MiB | 27.00 KiB/s   

remote: Total 181161 (delta 2), reused 3 (delta 0), pack-reused 181150
Receiving objects: 100% (181161/181161), 67.07 MiB | 47.00 KiB/s, done.
Resolving deltas: 100% (138591/138591), done.
warning: unable to access '/Users/xiexiuyue/.config/git/attributes': Permission denied
xiexiuyuedeMacBook-Pro:Documents xiexiuyue$ 
xiexiuyuedeMacBook-Pro:Documents xiexiuyue$ 
xiexiuyuedeMacBook-Pro:Documents xiexiuyue$ flutter doctor
Error: The Flutter directory is not a clone of the GitHub project.
       The flutter tool requires Git in order to operate properly;
       to set up Flutter, run the following command:
       git clone -b stable https://github.com/flutter/flutter.git
xiexiuyuedeMacBook-Pro:Documents xiexiuyue$ ls
dex2jar-2.0		flutter-1.8.3		jadx
flutter			flutter-1.8.3.zip	www
xiexiuyuedeMacBook-Pro:Documents xiexiuyue$ cd flutter
xiexiuyuedeMacBook-Pro:flutter xiexiuyue$ flutter doctor
Error: The Flutter directory is not a clone of the GitHub project.
       The flutter tool requires Git in order to operate properly;
       to set up Flutter, run the following command:
       git clone -b stable https://github.com/flutter/flutter.git
xiexiuyuedeMacBook-Pro:flutter xiexiuyue$ cd ..
xiexiuyuedeMacBook-Pro:Documents xiexiuyue$ cd flutter
xiexiuyuedeMacBook-Pro:flutter xiexiuyue$ ls
AUTHORS			README.md		examples
CODE_OF_CONDUCT.md	analysis_options.yaml	flutter_console.bat
CONTRIBUTING.md		bin			packages
LICENSE			dartdoc_options.yaml
PATENTS			dev
xiexiuyuedeMacBook-Pro:flutter xiexiuyue$ flutter doctor
Error: The Flutter directory is not a clone of the GitHub project.
       The flutter tool requires Git in order to operate properly;
       to set up Flutter, run the following command:
       git clone -b stable https://github.com/flutter/flutter.git
xiexiuyuedeMacBook-Pro:flutter xiexiuyue$ cd ..
xiexiuyuedeMacBook-Pro:Documents xiexiuyue$ ls
dex2jar-2.0		flutter-1.8.3		jadx
flutter			flutter-1.8.3.zip	www
xiexiuyuedeMacBook-Pro:Documents xiexiuyue$ cd flutter-1.8.3
xiexiuyuedeMacBook-Pro:flutter-1.8.3 xiexiuyue$ git init
Initialized empty Git repository in /Users/xiexiuyue/Documents/flutter-1.8.3/.git/
xiexiuyuedeMacBook-Pro:flutter-1.8.3 xiexiuyue$ flutter doctor
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Downloading Dart SDK from Flutter engine 38ac5f30a7026e870619c2e8e8c99c070d74036f...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  125M  100  125M    0     0  11.1M      0  0:00:11  0:00:11 --:--:-- 10.2M
Building flutter tool...

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool anonymously reports feature usage statistics and crash    ║
  ║ reports to Google in order to help Google contribute improvements to       ║
  ║ Flutter over time.                                                         ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://github.com/flutter/flutter/wiki/Flutter-CLI-crash-reporting        ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://www.google.com/intl/en/policies/privacy/                           ║
  ║                                                                            ║
  ║ Use "flutter config --no-analytics" to disable analytics and crash         ║
  ║ reporting.                                                                 ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure
you trust this source!
Downloading Material fonts...                                       0.4s
Downloading android-arm-profile/darwin-x64 tools...                 0.4s
Downloading android-arm-release/darwin-x64 tools...                 0.3s
Downloading android-arm64-profile/darwin-x64 tools...               0.5s
Downloading android-arm64-release/darwin-x64 tools...               0.4s
Downloading android-x86 tools...                                    1.7s
Downloading android-x64 tools...                                    1.7s
Downloading android-arm tools...                                    1.0s
Downloading android-arm-profile tools...                            0.8s
Downloading android-arm-release tools...                            0.4s
Downloading android-arm64 tools...                                  1.5s
Downloading android-arm64-profile tools...                          0.6s
Downloading android-arm64-release tools...                          0.5s
Downloading Gradle Wrapper...                                       0.1s
Downloading package sky_engine...                                   0.2s
Downloading common tools...                                         1.1s
Downloading common tools...                                         1.1s
Downloading darwin-x64 tools...                                     3.6s
Downloading libimobiledevice...                                     0.1s
Downloading usbmuxd...                                              0.1s
Downloading libplist...                                             0.1s
Downloading openssl...                                              0.2s
Downloading ideviceinstaller...                                     0.1s
Downloading ios-deploy...                                           0.1s
Doctor summary (to see all details, run flutter doctor -v):
 
Oops; flutter has exited unexpectedly.
Crash report written to /Users/xiexiuyue/Documents/flutter-1.8.3/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
xiexiuyuedeMacBook-Pro:flutter-1.8.3 xiexiuyue$ vim /Users/xiexiuyue/Documents/flutter-1.8.3/flutter_01.log

#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#29     runInContext (package:flutter_tools/src/context_runner.dart:58:24)
<asynchronous suspension>
#30     run (package:flutter_tools/runner.dart:51:10)
#31     main (package:flutter_tools/executable.dart:63:9)
<asynchronous suspension>
#32     main (file:///Users/xiexiuyue/Documents/flutter-1.8.3/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by ketanm** [comment]
@0123cf  - you need to follow steps fully. 

After cloning make sure that path to the flutter is updated in the `PATH` env variable and you are able to execute `flutter -v`.

You are not having flutter but setup issues. Provide more details once above changes are done.

**Comment by 0123cf** [comment]
It's done. Thank you very much.
[![](https://s2.ax1x.com/2019/08/11/ejG311.md.png)](https://imgchr.com/i/ejG311)
