### ISSUE TITLE
FadeInImage widget image loading issues while ListView pull to refresh

### ISSUE THREAD

**Issue by dhavalagile** [flutter/flutter#37470]
In my app Listview used for display Food List. Listview working fine first-time list loading if the image exists or not, placeholder image or food item image display.

When some new item added in API and image, not exists in the newly added item then when user use pulls to refresh then newly added widget whose image not available display past loaded image instead of the placeholder image.

Please refer my code, and provide a solution for image replicated issues.

    Widget _getRestaurantLogoImage({String imageUrl}) {
       final imageWidth = UIUtills().getProportionalWidth(width: 50.0);
       final borderRadius = BorderRadius.circular(imageWidth / 2.0);
       print("Restaurants.image :: $imageUrl");
       var image = FadeInImage(image: NetworkImage(imageUrl), placeholder: AssetImage(AppImage.restaurantPlaceholder), fit: BoxFit.cover, width: imageWidth, height: imageWidth,);
       final imageClipRect = ClipRRect(child: image, borderRadius: borderRadius,);
       return imageClipRect;
    }

**Comment by BondarenkoStas** [comment]
@dhavalagile Please provide your ```flutter doctor -v``` output.

**Comment by dhavalagile** [comment]
Hi @BondarenkoStas 
Here is my doctor output
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.4 18E226, locale
    en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.35.1)
[✓] Connected device (1 available)

• No issues found!
```

but my main issues for listview when one I perform pull to refresh operation and server add some new record during this time period and image URL is invalid or image does not exist in a new record at that case images display on past repeated for a new record.

**Comment by darshankawar** [comment]
Hi @dhavalagile,
Can you please confirm if you still experience this issue on latest Flutter version (eg: dev, stable, master) ?
Thanks.

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
