### ISSUE TITLE
Flutter tool process is killed when using use-application-binary option

### ISSUE THREAD

**Issue by davidmartos96** [flutter/flutter#37471]
When using the `use-application-binary` option with `flutter run` there is some code that kills the flutter tool running process. 

For example:

`flutter run --use-application-binary my_executable_path`

When this code https://github.com/flutter/flutter/blob/3fedb8cb5ada929a697f29fb1e5783f9cfa76a15/packages/flutter_tools/lib/src/desktop.dart#L13 runs from https://github.com/flutter/flutter/blob/d6bd1c0584d761e622c9f9331581bcae3655f0c4/packages/flutter_tools/lib/src/linux/linux_device.dart#L90, any process that includes the string `my_executable_path` is killed, even the one that is running the flutter tool, since the string is passed as an argument.

My suggestion would be to exclude the current running process when looking for processes to kill using https://api.dartlang.org/stable/2.4.0/dart-io/pid.html

**Comment by jonahwilliams** [comment]
Sounds like a good idea
