### ISSUE TITLE
Flutter project failed to implement native view in to flutter widget using PlatformView

### ISSUE THREAD

**Issue by JayM96** [flutter/flutter#37474]
implement a webview platformview to my flutter widget in specific height and width constraints. I have implemented it surfing some tutorials on medium and google.

But, At last I'm getting below error. 

A Flutter plugin files has been attached as webviewplugin-demo.zip as the whole project size is very large.

Also, I want to implement a flutter plugin or widget like, 

I will have a textformfield in flutter side and i can enter numbers from 1 to 100 in it and then whatever number i enter it must be added to seekbar in the android native side. So, i can understand this platformview briefly.  I'm stuck with this topic since last 2 days. 

Please help.

Below, is the log i'm getting when i run my webviewplugin project.

[webviewplugin-demo.zip](https://github.com/flutter/flutter/files/3461031/webviewplugin-demo.zip)
```
W/ResourceType(32277): No package identifier when getting name for resource number 0x00000000
W/ResourceType(32277): No package identifier when getting name for resource number 0x00000000
I/WebViewFactory(32277): Loading com.android.chrome version 73.0.3683.90 (code 368309002)
I/cr_LibraryLoader(32277): Time to load native libraries: 6 ms (timestamps 6968-6974)
W/ResourceType(32277): No package identifier when getting name for resource number 0x00000000
I/chatty  (32277): uid=10324(com.example.webviewplugin_example) identical 1 line
W/ResourceType(32277): No package identifier when getting name for resource number 0x00000000
I/chromium(32277): [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader(32277): Expected native library version number "73.0.3683.90", actual native library version number "73.0.3683.90"
W/cr_ChildProcLH(32277): Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
I/cr_BrowserStartup(32277): Initializing chromium process, singleProcess=false
W/ResourceType(32277): Failure getting entry for 0x7f130530 (t=18 e=1328) (error -2147483647)
W/wplugin_example(32277): type=1400 audit(0.0:70613): avc: denied { read } for name="vmstat" dev="proc" ino=4026532370 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc:s0 tclass=file permissive=0
D/EgretLoader(32277): EgretLoader(Context context)
D/EgretLoader(32277): The context is not activity
I/flutter (32277): _onPlatformViewCreated : 0
W/ContentCatcher(32277): Failed to notify a WebView
```
Thank you.

**Comment by BondarenkoStas** [comment]
@JayM96 Please provide your ```flutter doctor -v``` output.

**Comment by TahaTesser** [comment]
Hi @JayM96 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
