### ISSUE TITLE
What does the PerformanceOverlay options mask do?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3748]
http://docs.flutter.io/flutter/widgets/PerformanceOverlay/optionsMask.html

@chinmaygarde

**Comment by chinmaygarde** [comment]
This mask is documented here. Not sure why that comment isn't being picked up. https://github.com/chinmaygarde/flutter/blob/master/packages/flutter/lib/src/rendering/performance_overlay.dart#L49

**Comment by eseidelGoogle** [comment]
@devoncarew @pq any ideas?

**Comment by abarth** [comment]
It's documented for RenderPerformanceOverlay but not for PerformanceOverlay.  Those are different classes and often need duplicated docs.

**Comment by pq** [comment]
Right.  Missing doc: https://github.com/chinmaygarde/flutter/blob/master/packages/flutter/lib/src/widgets/performance_overlay.dart#L29

**Comment by eseidelGoogle** [comment]
My bad. :(  Sorry for not noticing.

**Comment by Hixie** [comment]
This is fixed now. I considered making a constructor that just takes a list of the options and builds the mask for you but we always just use allEnabled so there's not much point.
