### ISSUE TITLE
CustomPaint doesn't respect parent padding

### ISSUE THREAD

**Issue by wassafr** [flutter/flutter#37480]
I have the follow extract of code. Basically `MyListViewItem` is a `ListViewI` item that displays a `MyCard` widget, which has a default padding of 15.0. Inside this widget, I add a `Row` with a `CustomPaint`.

The issue is the `CustomPaint` widget doesn't respect the `MyCard` padding and is painted from the border of `MyCard`. I know the padding is correct because the `CustomTitle` widget respects it perfectly.  It leads the `CustomPaint` and the `CustomTitle` to overlap. This is clearly visible when activating "Debug Paint" in the Dev Tools ([See image](https://ibb.co/1v9cW0N)).

I tried to surround the `CustomPain` inside a `Container` but it doesn't change.

I worked around this issue by adding a `Padding` directly around the `CustomPaint` but it will quickly become a pain in the ass : each time I change the padding of `MyCard` I have to change it on `CustomPaint` also.

```dart
// MyListViewItem
// ...
@override
  Widget build(BuildContext context) {
    return Padding( // Only used as a separator because the widget is a ListView item, the issue is the same without this
        padding: EdgeInsets.symmetric(vertical: 5),
        child: MyCard(
            child: Row(
          children: <Widget>[
            CustomPaint(painter: DrawCircle(alarm)),
            CustomTitle.l2(alarm.definition.description ?? alarm.definition.name)
          ],
        )));
  }

// MyCard
// ...
MyCard(
      {@required this.child,
      this.color = Colors.white,
      this.borderRadius = const BorderRadius.all(Radius.circular(10.0)),
      this.padding = const EdgeInsets.all(10.0),
      this.margin = const EdgeInsets.all(0),
      this.boxShadow = const BoxShadow(
          color: Color.fromRGBO(0, 0, 0, .2),
          blurRadius: 10,
          offset: Offset(0.0, 5.0)),
      Key key})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      child: child,
      padding: padding,
      margin: margin,
      decoration:
          BoxDecoration(boxShadow: [boxShadow], borderRadius: borderRadius, color: color),
    );
  }

// DrawCircle
// ...
class DrawCircle extends CustomPainter {
  Paint _paint;
  AlarmEvent alarm;

  DrawCircle(this.alarm) {
    _paint = Paint()
      ..color = alarm.state == 0 ? themeColorRed : themeColorGreen
      ..strokeWidth = 10.0
      ..style = PaintingStyle.fill;
  }

  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawCircle(Offset(0.0, 0.0), 10.0, _paint);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return false;
  }
}
```

**Comment by spkersten** [comment]
The first argument of `drawCircle` is the circle's centre and the centre looks aligned with the start of the text as you would expect.

**Comment by BondarenkoStas** [comment]
@wassafr Please report if you found a solution or workaround.
Please provide your ```flutter doctor -v``` output.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
