### ISSUE TITLE
Medial distribution  Stay on the Launch page,   iOS。

### ISSUE THREAD

**Issue by YelenaLemon** [flutter/flutter#37485]
Medial distribution  Stay on the Launch page,   iOS。
Channel stable, v1.7.8

**Comment by vici-5423** [comment]
I had the same problem

**Comment by BondarenkoStas** [comment]
@YelenaLemon Can you please provide more details, what do you mean exactly?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
