### ISSUE TITLE
Openned my first dart package but made some mistakes in package name and author (2 times) 

### ISSUE THREAD

**Issue by danielR2001** [flutter/flutter#37483]
hi, I'm new to flutter and it's my first package uploaded and by mistake I opened two packages flutter_exoplayer and exoplayer (with author name luan) that I want to be removed because I made some mistakes in the package name and the author name, I know that you recommend not doing that but I uploaded these packages just right now and don't think someone is depending on it.
please help me.

**Comment by stuartmorgan** [comment]
This request needs to go to pub.dev, not the Flutter project.
