### ISSUE TITLE
Switch from package:vm_service_client to package:vm_service

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#37499]
package:vm_service_client as of 0.2.6+3 is marked as deprecated and recommends switching to package:vm_service instead.

For now, I'm pinning vm_service_client 0.2.6+2 (https://github.com/flutter/flutter/pull/37444) until code is properly migrated.

Probably also relevant to https://github.com/flutter/flutter/issues/31688.

**Comment by BondarenkoStas** [comment]
@jamesderlin As I understand, the issue is not relevant anymore?

**Comment by jamesderlin** [comment]
I'm not sure where you got that impression.

`packages/flutter_tools/lib/src/commands/update_packages.dart` is still explicitly pinned to `vm_service_client` 0.2.6+2.

There are a number of files that still import `package:vm_service_client`, and it's not any less deprecated.

**Comment by escamoteur** [comment]
No directly to this topic but I had an exception in another issue that came from vm_client in a flutter web app. I had no idea what vm_client is. Could you enlight me?

**Comment by jamesderlin** [comment]
I don't know what `vm_client` is.  Do you mean `vm_service_client`?  If so, see the package descriptions for [`vm_service_client`](https://pub.dev/packages/vm_service_client) and for [`vm_service`](https://pub.dev/packages/vm_service).  If you still have questions, there are other channels for help (e.g. StackOverflow).

**Comment by escamoteur** [comment]
Sorry I was not clear, while triaging another issue I saw the package vm_client in the stack trace of an exception and didn't know what this could be.

**Comment by davidmorgan** [comment]
Please take a look and see if this would be quick to do--if so, it's probably worth doing, as it will reduce risk :)

Background: I would like to delete `vm_service_client` from google3 and `flutter_driver` is the only/last user. `vm_service_client` has been unsupported for a while; most of its tests have never passed with Dart 2. The only test that did, has now broken due to an unrelated/correct SDK change, so it now has no test coverage of its own.

Thanks.

**Comment by CareF** [comment]
Currently devicelab also depends on vm_service_client.

**Comment by dnfield** [comment]
This will be a blocker for NNBD migration of flutter_driver.

package:vm_service is not migrated yet either, but presumably package:vm_service_client never will be.

**Comment by dnfield** [comment]
I have a patch to do this for flutter_driver, but will have to do some more digging on making sure it doesn't break any google3 stuff.

This bug should remain open for the rest of dev/ folders that are using vm_service_client, which is probably lower priority since those don't go anywhere else.

**Comment by dnfield** [comment]
There are still a few instances of usage in the `dev/` folder, I can try to take a look at those as well - but driver is now migrated.

**Comment by dnfield** [comment]
Once driver rolls internally, vm_service_client can be dropped internally.

**Comment by dnfield** [comment]
I'm going to see if I can get the rest of the devicelab stuff off of this.
