### ISSUE TITLE
[iOS] App rejected by Apple - ITMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by Cayke** [flutter/flutter#37498]
Yesterday i tried to upload an app to App Store. After processing the upload, i received an email from Apple with the content:

************************************************************************
Dear Developer,

We identified one or more issues with a recent delivery for your app, "BIG BOX Delivery" 3.0.2 (58). Please correct the following issues, then upload again.

ITMS-90338: Non-public API usage - The app references non-public symbols in BIG BOX Delivery: _pb_decode, _pb_decode_varint, _pb_encode, _pb_encode_string, _pb_encode_submessage, _pb_encode_tag_for_field, _pb_encode_varint, _pb_istream_from_buffer, _pb_ostream_from_buffer, _pb_read. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
************************************************************************

After removing **firebase_crashlytics** package, i tried again and it worked fine. Think that this issue is somewhere related with functions used in firebase_crashlytics.

I was using **firebase_crashlytics: ^0.1.0+2**

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G84, locale pt-BR)
    • Flutter version 1.7.8+hotfix.4 at /Users/cayke/development/flutter
    • Framework revision 20e59316b8 (2 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/cayke/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • iPhone Cayke • df829d3f13775d4a6b4d947efeb8cd542ad36bae • ios • iOS 12.3.1

• No issues found!
```

**Comment by Hixie** [comment]
We suspect this is a false positive and that those are just protobuf symbols.

**Comment by kroikie** [comment]
We do not use any private APIs in the Firebase Crashlytics plugin and neither does the native iOS SDK so unless something is happening at build time to introduce private APIs I don't see how this is related to the Crashlytics plugin.

> Think that this issue is somewhere related with functions used in firebase_crashlytics.

@Cayke could you give any more information about what functions you think could be causing this?

**Comment by Cayke** [comment]
Closing this issue as it seems that the error were caused by not generating iOS IPA properly by my side. Tried again today with the firebase crashlytics plugin and it went all good.

**Comment by Levi-Lesches** [comment]
How specifically did you fix this? I'm running the same steps as before, and only after adding `firebase_crashlytics` to my pubspec am I getting this error.

**Comment by Cayke** [comment]
> How specifically did you fix this? I'm running the same steps as before, and only after adding `firebase_crashlytics` to my pubspec am I getting this error.

Try to run the commands above before generating Xcode archive

```
flutter clean
flutter build ios
```

**Comment by Levi-Lesches** [comment]
Thanks, am trying this now (will edit this when it finishes). Just wondering, what's the point of running `flutter build ios`? Doesn't clicking `Archive` essentially do this anyway?

**Comment by morfinismo** [comment]
I was having the same problem and the suggestion by @Cayke did the trick. Thank you very much!

**Comment by kroikie** [comment]
@Cayke

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1141. Any further collaboration will be done there.

**Comment by QOFOL** [comment]
Flutter clean

flutter build ios --release

Works for me :)
