### ISSUE TITLE
Copy/paste toolbar needs smarter positioning, same issue in Flutter version 1.78

### ISSUE THREAD

**Issue by FrankYan09** [flutter/flutter#37501]
Reproduce the issue:

long press the TestField area, the copy/paste toolbar appears on top of the screen.
see the screenshot below:
![Screen Shot 2019-08-02 at 11 03 23 AM](https://user-images.githubusercontent.com/49292023/62390307-cde8ba00-b516-11e9-8ed3-e2412233d57e.png)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G84, locale
    en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
[✓] VS Code (version 1.36.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

The codes:

        body: Column(
          children: <Widget>[
            _isInEditingMode ? Container() : _titleBar,
            _isInEditingMode
                ? Expanded(
                    child: Padding(
                      padding: const EdgeInsets.all(12.0),
                      child: TextField(
                        cursorColor: Theme.of(context).colorScheme.background,
                        focusNode: _focusNode,
                        style: Theme.of(context)
                            .textTheme
                            .body1
                            .copyWith(color: surface),
                        controller: _controller,
                        maxLines: 160,
                        maxLength: _descriptionMaxLength,
                        keyboardType: TextInputType.multiline,
                        autofocus: true,
                        onChanged: (String text) {
                          _photoDescription = text;
                        },
                        decoration: InputDecoration(
                          hintText: null,
                          counterStyle: Theme.of(context)
                              .textTheme
                              .body1
                              .copyWith(color: surface),
                        ),
                      ),
                    ),
                  )
                : Expanded(child: _descriptionTextBox),
          ],
        ),

**Comment by samuelg123** [comment]
Same issue here

**Comment by justinmc** [comment]
This should be fixed with https://github.com/flutter/flutter/pull/36974, which was just merged.  You can get the fix in the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels).  Let me know if something still looks wrong.

**Comment by FrankYan09** [comment]
Works! Thank you very much!
