### ISSUE TITLE
Flutter codelab branch fails Atom plugin

### ISSUE THREAD

**Issue by samthor** [flutter/flutter#3751]
## Steps to Reproduce

Installed flutter's codelab branch. Installed flutter plugin in Atom, got error creating new project.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel codelab)
    • Flutter at /Users/codelab/Desktop/flutter
    • Framework revision 00e0075f8b (2 days ago), engine revision d85ead8ec2

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0-preview)
    • Android SDK at /android-sdk
    • Platform android-N, build-tools 24.0.0-preview
    • Java(TM) SE Runtime Environment (build 1.8.0_77-b03)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3, Build version 7D175
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2

note: Ignore the ideviceinstaller/ios-deploy stuff, that works fine.

## Logs and Crash Reports

Atom basically says this-

> Could not find an option named "out".
> Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
> Finished with exit code 64.

It looks like the Atom plugin thinks it can pass `--out` to `flutter create`, but that doesn't look like an option.

Creating a project manually with `flutter create` on the command-line works fine.

**Comment by samthor** [comment]
ping @qchong

**Comment by eseidelGoogle** [comment]
@devoncarew

**Comment by devoncarew** [comment]
fixed in https://github.com/dart-atom/dartlang/commit/a7319bb942bda1b1f827783bf1222bad8b3e8867

**Comment by devoncarew** [comment]
I new version of the plugin is available - can you update (and restart atom), and re-test? Thanks!
