### ISSUE TITLE
Deflake and re-enable module_test_ios

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#37525]
module_test_ios was turned off with https://github.com/flutter/flutter/pull/37442.  Turn it back on once it no longer causes failures.  See that PR for error details.

**Comment by Hixie** [comment]
module_test was similarly turned off on mac with https://github.com/flutter/flutter/pull/43375.

**Comment by jmagman** [comment]
There seems to be some flakiness related to the pubspec modified date being in the future.
```
[module_test_ios] [STDOUT] Executing: /private/tmp/flutter sdk/bin/flutter build ios --no-codesign in /var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/flutter_module_test.PCYYnC/hello
[module_test_ios] [STDOUT] stderr: Warning: File "/private/var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/flutter_module_test.PCYYnC/hello/pubspec.yaml" was created in the future. Optimizations that rely on comparing time stamps will be unreliable. Check your system clock for accuracy.
[module_test_ios] [STDOUT] stderr: The timestamp was: 2019-11-04 15:47:32.000
[module_test_ios] [STDOUT] stderr: The time now is: 2019-11-04 15:43:17.832054
```
When the pubspec changes, the framework doesn't get regenerated:
https://github.com/flutter/flutter/issues/42956

**Comment by jmagman** [comment]
The fix I found for module_test_ios is purely related to the iOS path, so I split this out from turning back on the module_test. https://github.com/flutter/flutter/issues/44216

**Comment by jmagman** [comment]
Fixed by https://github.com/flutter/flutter/pull/45877/files.
