### ISSUE TITLE
[webview_flutter] Package on pub.dev is v0.3.10+4 but repo is v0.3.10+5

### ISSUE THREAD

**Issue by workerbee22** [flutter/flutter#37536]
pub.dev is behind the repo release of the package. See the package `pubspec.yaml` here:

https://github.com/flutter/plugins/blob/master/packages/webview_flutter/pubspec.yaml

**Comment by jmagman** [comment]
@amirh

**Comment by workerbee22** [comment]
All look to be in sync at v0.3.11 now 👍
