### ISSUE TITLE
[firebase_core] Package on pub.dev is v0.4.0+1 but repo is v0.4.0+8

### ISSUE THREAD

**Issue by workerbee22** [flutter/flutter#37538]
pub.dev is behind the repo release of the package. See the package `pubspec.yaml` here:

https://github.com/flutter/plugins/blob/master/packages/firebase_core/pubspec.yaml

**Comment by eldraco19** [comment]
It's 0.4.0+8 on https://pub.dev/packages/firebase_core

**Comment by jmagman** [comment]
@collinjackson @kroikie

**Comment by workerbee22** [comment]
To be clear the issue is actually with the pub.dev tag being out of date. Your are correct the version on pub.dev seems to be **0.4.0+8** ... but tag is **0.4.0+1** (see image).

![image](https://user-images.githubusercontent.com/5154664/62762148-c6538300-bacb-11e9-8334-59507a9e7d93.png)

Same tag issue on the Flutter Plugins Github page here: https://github.com/flutter/plugins

**Comment by kroikie** [comment]
Seems like shields.io is stuck on the old v0.4.0+1. @collinjackson any idea how to force them to update?

**Comment by kroikie** [comment]
@workerbee22

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1129. Any further collaboration will be done there.
