### ISSUE TITLE
[firebase_in_app_messaging] Package on pub.dev is v0.0.1 but repo is v0.0.1+2

### ISSUE THREAD

**Issue by workerbee22** [flutter/flutter#37539]
pub.dev is behind the repo release of the package. See the package `pubspec.yaml` here:

https://github.com/flutter/plugins/blob/master/packages/firebase_in_app_messaging/pubspec.yaml

`Readme.md `also missing pub.dev link here: 

https://github.com/flutter/plugins/blob/master/packages/firebase_in_app_messaging/README.md

**Comment by jmagman** [comment]
@collinjackson

**Comment by workerbee22** [comment]
Actually just a problem with the pub.dev tag showing the wrong version number. Shows v0.0.1 in tag image below on this page https://github.com/flutter/plugins

![image](https://user-images.githubusercontent.com/5154664/62762332-3bbf5380-bacc-11e9-9518-fed5dad29b59.png)

But actual pub.dev version shows as **0.0.1+3**

**Comment by kroikie** [comment]
@workerbee22

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/350. Any further collaboration will be done there.
