### ISSUE TITLE
[firebase_auth] Package on pub.dev is v0.14.0 but repo is v0.14.0+1

### ISSUE THREAD

**Issue by workerbee22** [flutter/flutter#37537]
pub.dev is behind the repo release of the package. See the package `pubspec.yaml` here:

https://github.com/flutter/plugins/tree/master/packages/firebase_auth

**Comment by jmagman** [comment]
@collinjackson @kroikie

**Comment by workerbee22** [comment]
All look to be correct now ie. **v0.14.0+1** 👍

**Comment by kroikie** [comment]
@workerbee22

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1086. Any further collaboration will be done there.
