### ISSUE TITLE
[image_picker] Package on pub.dev is v0.6.1 but repo is v0.6.1+1

### ISSUE THREAD

**Issue by workerbee22** [flutter/flutter#37533]
pub.dev is behind the repo release of the package. See the package `pubspec.yaml` here:

https://github.com/flutter/plugins/blob/master/packages/image_picker/pubspec.yaml

**Comment by jmagman** [comment]
@cyanglaz

**Comment by cyanglaz** [comment]
Thank you for catching this! I published the plugin, it should be up to date now.
