### ISSUE TITLE
[fireabse_auth] call reauthenticateWithCredential by EmailAuthProvider using current email and password (NoSuchMethodError: The method '[]' was called on null).

### ISSUE THREAD

**Issue by masashi-sutou** [flutter/flutter#37542]
## description

- I use firebase_auth: 0.14.0.
- I would like to update the user's email, but if the user's last sign-in time does not meet the security threshold, I need to use the reauthentication method to resolve.
- I tried to call `reauthenticateWithCredential` on `EmailAuthProvider` with my current email address and password before `firebaseUser.updateEmail`, but the data returned from `reauthenticateWithCredential` on iOS has no user and crashes with the following error.

## error

```
Tried calling: []("user")
flutter: 💥 #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      new AuthResult._ (package:firebase_auth/src/auth_result.dart:12:36)
#2      FirebaseUser.reauthenticateWithCredential (package:firebase_auth/src/firebase_user.dart:214:23)
...
````

## my code

```dart 
final baseUser = await _firebaseAuth.currentUser();
// occurs error
final authResult = await baseUser.reauthenticateWithCredential(
  EmailAuthProvider.getCredential(
    email: baseUser.email,
    password: password,
  ),
);
return authResult.user;
```

## workaround

- I downgraded to 0.11.1+12, and it works.

```dart 
final baseUser = await _firebaseAuth.currentUser();
final firebaseUser = await baseUser.reauthenticateWithCredential(
  EmailAuthProvider.getCredential(
    email: baseUser.email,
    password: password,
  ),
);
return firebaseUser;
```

**Comment by MiguelSOliveira** [comment]
Getting the same error here.. Workaround also works for me..

**Comment by masashi-sutou** [comment]
>  but don't really like to have to downgrade..

@MiguelSOliveira What's your workaround without downgrading?

**Comment by AndreHaueisen** [comment]
I'm getting the same error with PhoneAuthProvider.

**Comment by AndreHaueisen** [comment]
The problem was probably generated [on this commit](https://github.com/flutter/plugins/commit/533ee023b7b5aa52ece6643bb82d1dca20380818#diff-70fb14b82a30b7ea4cc387fc26f291d1)

Trying to debug it

**Comment by Akyna** [comment]
any update ?

**Comment by rodriigovieira** [comment]
I was able to reproduce the problem here.

Another possible workaround is simply reauthenticate the user again.

`await _auth.signInWithEmailAndPassword(email: _user.email, password: currentPassword);
`

**Comment by kroikie** [comment]
@masashi-sutou

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1085. Any further collaboration will be done there.
