### ISSUE TITLE
[firebase_messaging] Package on pub.dev is v5.1.2 but repo is v5.1.3

### ISSUE THREAD

**Issue by workerbee22** [flutter/flutter#37540]
pub.dev is behind the repo release of the package. See the package `pubspec.yaml` here:

https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/pubspec.yaml

**Comment by jmagman** [comment]
@collinjackson @kroikie

**Comment by kroikie** [comment]
Thanks for flagging this. Updated.

**Comment by kroikie** [comment]
@workerbee22

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1051. Any further collaboration will be done there.
