### ISSUE TITLE
Bad file descriptor, errno = 9

### ISSUE THREAD

**Issue by wind-hx** [flutter/flutter#37547]
## Steps to Reproduce

using udp module in iphonex error
simulator normal

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: OS Error: Bad file descriptor, errno = 9
#0      _NativeSocket.getOption (dart:io-patch/socket_patch.dart:1106:28)
#1      _RawDatagramSocket.broadcastEnabled (dart:io-patch/socket_patch.dart:1949:40)
#2      UDP.send.<anonymous closure> (package:udp/src/udp_base.dart:98:31)
<asynchronous suspension>
#3      new Future.microtask.<anonymous closure> (dart:async/future.dart:202:37)
#4      _rootRun (dart:async/zone.dart:1120:38)
#5      _CustomZone.run (dart:async/zone.dart:1021:19)
#6      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: OS Error: Bad file descriptor, errno = 9
#0      _NativeSocket.getOption (dart:io-patch/socket_patch.dart:1106:28)
#1      _RawDatagramSocket.broadcastEnabled (dart:io-patch/socket_patch.dart:1949:40)
#2      UDP.send.<anonymous closure> (package:udp/src/udp_base.dart:98:31)
<asynchronous suspension>
#3      new Future.microtask.<anonymous closure> (dart:async/future.dart:202:37)
#4      _rootRun (dart:async/zone.dart:1120:38)
#5      _CustomZone.run (dart:async/zone.dart:1021:19)
#6      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: OS Error: Bad file descriptor, errno = 9
#0      _NativeSocket.getOption (dart:io-patch/socket_patch.dart:1106:28)
#1      _RawDatagramSocket.broadcastEnabled (dart:io-patch/socket_patch.dart:1949:40)
#2      UDP.send.<anonymous closure> (package:udp/src/udp_base.dart:98:31)
<asynchronous suspension>
#3      new Future.microtask.<anonymous closure> (dart:async/future.dart:202:37)
#4      _rootRun (dart:async/zone.dart:1120:38)
#5      _CustomZone.run (dart:async/zone.dart:1021:19)
#6      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by fzyzcjy** [comment]
how did you solve it? thanks!
