### ISSUE TITLE
dio request error Unhandled Exception: DioError [DioErrorType.DEFAULT]: SocketException: Connection failed (OS Error: No route to host, errno = 65), address = 192.168.10.241, port = 80

### ISSUE THREAD

**Issue by dinner** [flutter/flutter#37546]
Hello everyone,i have a problem of my app.
When I request the server use dio,I will get this error:
`Unhandled Exception: DioError [DioErrorType.DEFAULT]: SocketException: Connection failed (OS Error: No route to host, errno = 65), address = 192.168.10.241, port = 80`
And on some phone there is no error but on some phone it will show these errors.
I cannot figure it out.
Please answer for that if you know.

'flutter doctor -v' is natural

**Comment by ja2375** [comment]
That error indicates your device cannot reach the desired server with the IP 192.168.10.241, most likely because you are not connected to the same network or maybe there are network issues. 

Please double check that your device is on the same network.

As you are trying to connect to Port 80 I assume it is a web server. You could also verify that your phone can load the website by entering the server's IP in your browser.

**Comment by mohitjadav** [comment]
In your case it seems like  that the connection has been closed by the server end of the connection. This could be an issue with the request you are sending or an issue at their end.
if you working with localhost it seems like You are Not in same Network

**Comment by dinner** [comment]
> That error indicates your device cannot reach the desired server with the IP 192.168.10.241, most likely because you are not connected to the same network or maybe there are network issues.
> 
> Please double check that your device is on the same network as your server.
> 
> As you are trying to connect to Port 80 I assume it is a web server. You could also verify that your phone can load the website by entering the server's IP in your browser.

Thank you for your reply,but the network is right and I use the browser to open the web of 192.168.10.241 I can open it.So I am sure it's in the same network.And the outer net server I can not request the server success either.But on some phone it can work and some phone it can not work

**Comment by dinner** [comment]
> In your case it seems like that the connection has been closed by the server end of the connection. This could be an issue with the request you are sending or an issue at their end.
> if you working with localhost it seems like You are Not in same Network

Thank you for your reply.The server and the client are in the same network.And the same code some phone can connect right but some can not.I can not figure it out

**Comment by dinner** [comment]
@zoechi ,hello ,if you know this?I have be worried for few days

**Comment by BondarenkoStas** [comment]
@dinner ```flutter doctor -v``` is mostly used to see which version of the framework and what the environment you use. Sorry for coming so late. Did you find any solution for the situation? Can you specify on which exactly physical devices you encounter the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
