### ISSUE TITLE
flutter 

### ISSUE THREAD

**Issue by ameennio** [flutter/flutter#37554]
can anyone illustrate the problem.

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 9455c3203b74c83c)

Crash report written to C:\Users\A\flutter_11.log;

**Comment by jonahwilliams** [comment]
Hi @ameennio , you need to include the information from `C:\Users\A\flutter_11.log` otherwise we have no idea what the problem is
