### ISSUE TITLE
PopupCheckedMenuItem can't handle radio-button-style check marks

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3756]
If you have a menu with three items and you can switch between them, you can give the current one a check mark, using PopupCheckedMenuItem. But if you select another one, while we'll start animating its checkmark in, we won't animate the _old_ one _out_.

This will affect the "Grid" demo once I convert it to using PopupCheckedMenuItem.

**Comment by sethladd** [comment]
Does this still impact the Grid demo? I don't see checked menu items in the "Grid list" upper-right menu.

**Comment by Hixie** [comment]
We should make sure we do demo this somewhere, if nothing else just to prove it can be done.

**Comment by YeungKC** [comment]
Could you please provide a minimum recurrence code?

cc @Hixie

**Comment by guidezpl** [comment]
https://gallery.flutter.dev/#/demo/menu showcases the supported menu options (including checklist), so closing as obsolete
