### ISSUE TITLE
runing at profile mode failed

### ISSUE THREAD

**Issue by weeChanc** [flutter/flutter#37567]
```
Could not resolve project  XXXX.                   
     Required by:                                                       
         project :xxxx                                       
      > Unable to find a matching configuration of project :XXXX
          - Configuration 'debugApiElements':                           
              - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'debug'.
```

**Comment by BondarenkoStas** [comment]
@weeChanc Do you have any clues how to reproduce the issue? Can you provide a small self-contained app that demonstrates it?
Also please provide you ```flutter doctor -v``` output.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
