### ISSUE TITLE
Type of sub maps is _InternalLinkedHashMap<dynamic, dynamic>

### ISSUE THREAD

**Issue by rtessler** [flutter/flutter#37574]
When running a query using cloud firestore. The dart command on `json.runtimeType.toString()` reports the type of sub maps is `_InternalLinkedHashMap<dynamic, dynamic>` where as the type of the top level json is `_InternalLinkedHashMap<String, dynamic>`. I have to use  `Map<String, dynamic>.from(json[prop]);` to convert sub maps to `Map<String, dynamic>`. Also the type of array properties is `List<dynamic>` for lists of Maps. I was expecting `List<Map<String, dynamic>>`. Again I need to convert

**Comment by kroikie** [comment]
@rtessler

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1207. Any further collaboration will be done there.
