### ISSUE TITLE
Want separate click regions for triangle vs. the rest in TwoLevelListItem

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3758]
A customer wants a TwoLevelListItem whereby clicking on the disclosure triangle does the normal behavior, but clicking anywhere else (like on the name of the item) has a separate behavior.

Ideally both click regions would have separate InkWells, but I'm not sure that's required.  They have an existing Android app with this behavior, but no InkWells.

They attempted to replicate this behavior in Flutter, by placing an InkWell in the title of the TwoLevelListItem, but that produced bad behavior in a couple ways, including having 2 overlapping Ink splashes on click of the title, and also that the padding around the title resulted in taking the disclosure triangle action which was confusing if you happened to click just left of the title, you'd get the action associated all the way to the right (the triangle).

I don't have an easy screenshot to post externally, but we can work one up if necessary.  @HansMuller

**Comment by HansMuller** [comment]
Should we continue to have one InkWell for the entire TwoLevelSublist widget but only expand when the user hits the expand/collapse icon? And if they don't hit the icon, then we'd fire whatever onTap action was provided to the TwoLevelSublist.

Alternatively we could make the expand/collapse icon a separate InkWell. That makes it harder to see its  ink splash - since it's rather small - but it would make the tap location a little clearer to the user. Of course, the user can tell if they've hit the icon, since that triggers the expand/collapse animation.

**Comment by abarth** [comment]
We probably should do something similar to what we do for checkboxes in drawer items.  If you tap directly on the checkbox, you get a small circular ink reaction.  If you tap on the drawer item, the whole thing splashes.

**Comment by HansMuller** [comment]
Giving TwoLevelSublist's expand/collapse widget it's own InkResponse is easy enough (included when a new TwoLevelSublist onTap parameter was specified) however the underlying ListItem's layout still exposes some problems.  Here's a screenshot of a single TwoLevelSublist from the gallery home screen. I've set ` debugPaintSizeEnabled = true`.

![screenshot](https://cloud.githubusercontent.com/assets/1377460/15156272/10c8aaf6-169b-11e6-9d78-66e3665bc16f.png)

What I think we want is for the tap-sensitive-area defined by the trailing expand/collapse icon to include all of the space to the right of the "Demos" text. ListItem has included margins per the Material Design spec to ensure that the text is distinct from the trailing expand/collapse icon and that the icon lines up with the rightmost toolbar action from the AppBar. Unfortunately tapping in the margins around the icon dispatches events to the ListItem's InkWell. Not what we want.

I could add more ListItem etc properties to allow one to get the exact tap-sensitive/splash-generating layout that's wanted here. However I think it might be simpler to just write a custom widget that DTRT.

**Comment by HansMuller** [comment]
Here's a demo of a pair of CustomWidgets based on the TwoLevelList et al implementation. 

The list item layout is greatly simplified. CustomListItem is essentially  a placeholder for an app-specific widget. It contains whatever all of the list items have in common. It has an InkWell whose onTap callback would be set up in some app-specific way. Here it just demonstrates that tapping on the item does not trigger the expand/collapse animation.

CustomSublistItem adds the expand/collapse animation. Its content is just another CustomListItem, and its children are the sublist it reveals when expanded. CustomSublistItem just arranges its content and the expand/collapse icon in a row, which appears at the top of the column that contains the sublist children. The icon gets its own (circular!) ink splash that is isolated from the rest of the widget.

```
import 'package:flutter/material.dart';

class CustomListItem extends StatelessWidget {
  CustomListItem({ Key key, this.content, this.onTap }) : super(key: key);

  final Widget content;
  final GestureTapCallback onTap;

  @override
  Widget build(BuildContext context) {
    return new InkWell(
      onTap: () { print('CustomListItem onTap'); },
      child: new Container(
        height: 48.0,
        padding: const EdgeInsets.symmetric(horizontal: 16.0),
        child: new Align(
          alignment: FractionalOffset.centerLeft,
          child: content
        )
      )
    );
  }
}

class CustomSublistItem extends StatefulWidget {
  CustomSublistItem({ Key key, this.content, this.children }) : super(key: key);

  final Widget content;
  final List<Widget> children;

  @override
  CustomSublistItemState createState() => new CustomSublistItemState();

}

class CustomSublistItemState extends State<CustomSublistItem> {
  AnimationController _controller;
  CurvedAnimation _easeInAnimation;
  ColorTween _iconColor;
  Animation<double> _iconTurns;

  bool _isExpanded = false;

  @override
  void initState() {
    super.initState();
    _controller = new AnimationController(duration: const Duration(milliseconds: 300));
    _easeInAnimation = new CurvedAnimation(parent: _controller, curve: Curves.easeIn);
    _iconColor = new ColorTween();
    _iconTurns = new Tween<double>(begin: 0.0, end: 0.5).animate(_easeInAnimation);

    _isExpanded = PageStorage.of(context)?.readState(context) ?? false;
    if (_isExpanded)
      _controller.value = 1.0;
  }

  void _handleOnTap() {
    setState(() {
      _isExpanded = !_isExpanded;
      if (_isExpanded)
        _controller.forward();
      else
        _controller.reverse();
      PageStorage.of(context)?.writeState(context, _isExpanded);
    });
  }

  Widget buildList(BuildContext context, Widget child) {
    return new Column(
      children: <Widget>[
        new IconTheme(
          data: new IconThemeData(color: _iconColor.evaluate(_easeInAnimation)),
          child: new Row(
            children: <Widget>[
              new Flexible(child: config.content),
              new InkResponse(
                onTap: _handleOnTap,
                containedInkWell: true,
                highlightShape: BoxShape.circle,
                child: new RotationTransition(
                  turns: _iconTurns,
                  child: new Icon(icon: Icons.expand_more)
                )
              )
            ]
          )
        ),
        new ClipRect(
          child: new Align(
            heightFactor: _easeInAnimation.value,
            child: new Column(children: config.children)
          )
        )
      ]
    );
  }

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    _iconColor
      ..begin = theme.unselectedWidgetColor
      ..end = theme.accentColor;

    return new AnimatedBuilder(
        animation: _controller.view,
        builder: buildList
    );
  }
}

class CustomListItemDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(title: new Text('Custom expand/collapse list')),
      body: new Block(
        children: <Widget>[
          new CustomListItem(content: new Text('Top')),
          new CustomSublistItem(
            content: new CustomListItem(content: new Text('Sublist')),
            children: <Widget>[
              new CustomListItem(content: new Text('One')),
              new CustomListItem(content: new Text('Two')),
              new CustomListItem(content: new Text('Free')),
              new CustomListItem(content: new Text('Four'))
            ]
          ),
          new CustomListItem(content: new Text('Bottom'))
        ]
      )
    );
  }
}

void main() {
  runApp(new CustomListItemDemo());
}
```

**Comment by Hixie** [comment]
Closing this since @HansMuller provided an example of how to hand-roll this. We decided not to provide this at the framework level since it's off-spec behavior.
