### ISSUE TITLE
OutlineButton documentation is very vague and unclear

### ISSUE THREAD

**Issue by MichaelM97** [flutter/flutter#37587]
When creating an 'OutlineButton', I _presume_ setting the 'color' tag should result in the button being filled with the specified color; but it doesn't.

Here's the button code
```
Container(
            alignment: Alignment.center,
            child: Padding(
              padding: EdgeInsets.only(bottom: 25.0),
              child: OutlineButton(
                color: Colors.red,
                child: Text(
                  'Log in',
                  style: TextStyle(color: Colors.blue),
                ),
                onPressed: () {
                  print("TODO");
                },
                borderSide: BorderSide(color: Colors.blue),
              ),
            ),
          ),
```

Here's the visual output

<img width="101" alt="OutlineButton" src="https://user-images.githubusercontent.com/22373058/62429036-48752d80-b701-11e9-9ebe-2654af681840.png">

**Comment by HansMuller** [comment]
OutlineButtons always have a transparent fill unless the button's highlightElevation is set to a value > 0. If that's the case then the outline button is filled with the specified `color` when pressed - before it's elevation is increased and its shadow appears.

The OutlineButton documentation is not clear on this, we need to fix that.

**Comment by Hixie** [comment]
The documentation for OutlineButton is actually really unclear on many aspects. It should have examples of basic usage, sample images showing cases with elevation, etc.

**Comment by hello-addweb** [comment]
Try  this 
 DecoratedBox(
decoration:
ShapeDecoration(shape: CircleBorder(), color: Colors.pinkAccent),
child: Theme(
data: Theme.of(context).copyWith(
buttonTheme: ButtonTheme.of(context).copyWith(
materialTapTargetSize: MaterialTapTargetSize.shrinkWrap)),
child: OutlineButton(
shape: CircleBorder(),
child: Text('A'),
onPressed: () => {},
),
),
);

**Comment by Abhishek01039** [comment]
Hello @Hixie 
`OutlineButton` is obsolete. 
should we close this issue now or have to update the docs?

**Comment by HansMuller** [comment]
I'm closing this issue because the OutlineButton widget is deprecated and has been replaced by OutlinedButton.  The new OutlinedButton widget _does_ need examples, as do TextButton and ElevatedButton.  Many examples can be found in flutter.dev/go/material-button-migration-guide and in https://github.com/flutter/flutter/pull/59702 as well as the [ButtonStyle API doc](https://api.flutter.dev/flutter/material/ButtonStyle-class.html).

I've opened an issue for the API doc lacunae - https://github.com/flutter/flutter/issues/75642
