### ISSUE TITLE
Cloud_Firestore Plugin Readme Documentation Error

### ISSUE THREAD

**Issue by AriCohen8** [flutter/flutter#37591]
Readme documentation is incorrect for transactions which causes user errors.

The Readme is missing collection when setting the DocumentReference

_Running a transaction:
final DocumentReference postRef = Firestore.instance.document('posts/123');
..._

Should be:
final DocumentReference postRef = Firestore.instance.collection('myCollection').document('posts/123');

Thank you,

**Comment by jmagman** [comment]
Not technically docs.flutter.dev docs, but d: api docs was close enough.

**Comment by kroikie** [comment]
@AriCohen8

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1206. Any further collaboration will be done there.
