### ISSUE TITLE
Instantiating Flutter in an embedded host app prior to display

### ISSUE THREAD

**Issue by ch-robert** [flutter/flutter#37602]
I've embedded my Flutter app in my Xamain.Forms app. It works when I'm displaying a content page in Xamarin with embedded Flutter app. I can also send messages from Flutter to Xamain via method channel.

The problem occurs when I'm trying to send a message from Xamarin to Flutter.
I have no idea how to access the method channel which gets initialized in a content page renderer from a shared project. Or how to initialize a flutter app instance without displaying it.
I want to have a static Flutter instance and route all the traffic through it from Xamarin.

Any ideas?

**Comment by bsheen** [comment]
@here further to the above. Is it possible to initialise an embedded Flutter app off screen?

In the above scenario, it would be ideal to initialise the Flutter app and hold a reference to that in the host app. This would allow the host to send messages to the Flutter app prior to presenting the Flutter view to the User.

The goal with the above is to develop new features in Flutter and embed that in a Xamarin app. All method channels to and from the app work as intended once the Flutter app has initialised. However, in this use case it isn't appropriate to show the Flutter app straight away but only once the User navigates to the Flutter app feature.
