### ISSUE TITLE
Compile linux arm 32 or 64 version

### ISSUE THREAD

**Issue by ping996** [flutter/flutter#37604]
I used the command to compile the flutter engine:
./flutter/tools/gn --linux-cpu arm64
ninja -C out/host_debug_arm64

result:
compiled successfully,  I used the file command to see the libflutter_engine.so

libflutter_engine.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[xxHash]=1a5505531d219cf5, with debug_info, not stripped

It is also a x86_64.
Any suggestions about the compile?
Thanks.

**Comment by kangwang1988** [comment]
Can you elaborate?
Besides, `flutter doctor -v` might be helpful.
