### ISSUE TITLE
Firebase Analytics different method names?

### ISSUE THREAD

**Issue by BugsBunnyBR** [flutter/flutter#37600]
So,
it looks like Android has `setSessionTimeoutDuration`
https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.html#setSessionTimeoutDuration(long)

and iOS has `setsessiontimeoutinterval`
https://firebase.google.com/docs/reference/ios/firebaseanalytics/api/reference/Classes/FIRAnalytics#+setsessiontimeoutinterval:

They seems to me to be the same action, but with different names in each platform?
Firebase Analytics plugin current implementation only tracks the `setSessionTimeoutDuration`.

If so, how to proceed ?
1) Create an `FirebaseAnalyticsIos` namespace and add the method `setsessiontimeoutinterval`?
2) Create the iOS version of `setSessionTimeoutDuration` and call `setsessiontimeoutinterval` ? Leaving it documented in the dart side?

cc: @collinjackson

**Comment by iapicca** [comment]
Hi @BugsBunnyBR  given the open issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
I'm closing this one as isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
