### ISSUE TITLE
How to debug IOS by flutter in Windows

### ISSUE THREAD

**Issue by wangshiyang** [flutter/flutter#37607]
flutter在windows中怎么支持调试ios，就像visual studio c#+xamarin中可以增加远程mac 配对 然后就可以在vs c#中选择iphone设备调试了 
请问flutter有没有这种类似的功能？
还有flutter有没有 视图设计器之类的东西 可以通过拖拽生成相应的布局？

**Comment by Saifallak** [comment]
you can try VM for Mac ex: https://techsviewer.com/install-macos-mojave-vmware-windows/
else try codeMagic to generate IPA but not debugging

there is no other way

**Comment by jmagman** [comment]
> flutter在windows中怎么支持调试ios，就像visual studio c#+xamarin中可以增加远程mac 配对 然后就可以在vs c#中选择iphone设备调试了
> 请问flutter有没有这种类似的功能？
> 还有flutter有没有 视图设计器之类的东西 可以通过拖拽生成相应的布局？

Google translate:
> How does flutter support debugging ios in windows, just like visual studio c#+xamarin can add remote mac pairing and then you can select iphone device debugging in vs c#
> Does flutter have this similar function?
> And flutter has something like view designer. Can you generate the corresponding layout by dragging and dropping?

**Comment by kangwang1988** [comment]
flutter在windows中怎么支持调试ios，就像visual studio c#+xamarin中可以增加远程mac 配对 然后就可以在vs c#中选择iphone设备调试了
请问flutter有没有这种类似的功能？
> Short answer is no.
还有flutter有没有 视图设计器之类的东西 可以通过拖拽生成相应的布局？
> Not officially supported, but there is some provided by the community, you can search it.
