### ISSUE TITLE
[desktop] Accented non-ASCII characters do not show in TextField on Windows

### ISSUE THREAD

**Issue by gazialankus** [flutter/flutter#37617]
Accented non-ASCII characters such as the Turkish accented letters ğüşıöçĞÜŞİöç do not show in TextField on Windows 10. 

They actually cause weird behavior. "ı" shows as "1", "ü" hides characters that follow, etc.

**Comment by stuartmorgan** [comment]
Can you explain what exactly you mean by "show"? Are you attempting to type these characters and they aren't showing up correctly, or are you setting them programmatically and they aren't showing up?

If the former this is #30661. The latter would be unexpected.

**Comment by gazialankus** [comment]
For these letters it's #30661: ğşıĞŞİ
For these, there is a "switch to hiding mode" behavior, which is different: üöçÜÖÇ.

When you press any of these "hiding" keys, nothing happens visually (no broken character shows). After that, whatever letter you press is also hidden. However, if you press backspace enough number of times and delete that invisible "hiding" character, new keys that you press work normally. 

So, I type "abcüde" and see: "abc|", where | is the cursor. Then, I press backspace three times, this deletes the hidden "üde". Then, I type "fg" and see "abcfg|". Hope it makes sense.

**Comment by stuartmorgan** [comment]
That's all text input, so it's all part of #30661.
