### ISSUE TITLE
[p:connectivity] Detect mobile connection subtype. 

### ISSUE THREAD

**Issue by bubunyo** [flutter/flutter#37618]
## Use case

the ability to detect 2g, 3g and 4g connection on devices using the connectivity plugin. 

## Proposal

Extend the connectivity plugin functionality to return the mobile connection subtype.

**Comment by stuartmorgan** [comment]
Thanks for the submission! However, we’re currently not accepting non-critical PRs for this plugin, as we hope that in time we’re able to transition users to the corresponding plugin in [the Flutter Community Plus Plugins repository](https://plus.fluttercommunity.dev/). We encourage you to submit your PR there.

We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.
