### ISSUE TITLE
[flutter][google_maps][google_maps_flutter] Problem with two existing Google Maps Widgets

### ISSUE THREAD

**Issue by Menelphor** [flutter/flutter#37619]
Duplicate of #25653 && #24900
## Explanation of the Problem:

My problem only occurs on IOs on real devices (not Simulator) on debug and release.

I do use the google Maps widget with some markers. Tapping on on Marker opens another Screen with more Information, another google Maps widget and the possibility to Navigate via url launcher. (I reduced the Screens to only show the widgets causing the problem)

Also the problem occurs when opening the control center.

Leaving the app from this screen (by tapping start navigation for example or going to the IOs homescreen) and then comming back to the app leads to an issue.

Also opening the control center leads to this [problem](https://youtu.be/3vVJwH_rN5M)

If i go back to the App homescreen again, only a white screen is shown.

### Addition:

Wrapping the Google Maps Widget in the info Screen in a Flex Widget (Column or Row) even leads to a worse behaviour. When returning to the Apps HomeScreen, additional content of the Flex Widget (for example a Container with Text) will stay visible.

### What I tried so far to get it to work, but failed

1. Release Mode
2. Disabled Navigation Transition
3. async await url launch
4. Building on IOs 12.3 & 12.4
5. Switching to flutter master

### Steps to reproduce:

1. Install [google_maps_flutter 0.5.20+1](https://pub.dev/packages/google_maps_flutter) and [url_launcher: 5.0.3](https://pub.dev/packages/url_launcher) (I know it is not the latest, but thats not the problem)

2. Copy the CodeSnippet in a flutter project and build on IOs.

3. Tap on the Marker
4. Tap on Button "Start Navigation" or leave the App
5. Tap in Apple Maps on the upper left corner redirecting to the App or reopen the App
6. Your back in the info screen, tap on the left Arrow in the upper left corner
7. Only a white screen is visible

## Code:
[https://github.com/Menelphor/google_maps_bug](github repo with code)

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:url_launcher/url_launcher.dart';
import 'dart:io';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      initialRoute: "/",
      routes: {
        "/": (context) => HomePage(),
      },
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GoogleMap(
        initialCameraPosition: CameraPosition(
          target: const LatLng(47.6, 8.8796),
          zoom: 7,
        ),
        markers: Set<Marker>()
          ..add(
            Marker(
              markerId: MarkerId('hi'),
              position: LatLng(47.6, 8.8796),
              consumeTapEvents: true,
              onTap: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => InfoScreen()),
                );
              },
            ),
          ),
      ),
    );
  }
}

class InfoScreen extends StatelessWidget {
  LottoInfo lottoInfo = LottoInfo();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("info Page"),),
      body: GoogleMap(
        initialCameraPosition: CameraPosition(
          target: const LatLng(47.6, 8.8796),
          zoom: 7,
        ),
        markers: Set<Marker>()
          ..add(
            Marker(
              markerId: MarkerId('hi2'),
              consumeTapEvents: true,
              position: LatLng(47.6, 8.8796),
              onTap: () {
                if (Platform.isIOS) {
                  launch('https://maps.apple.com/?q=47.6,8.8796');
                } else {
                  launch(
                      'https://www.google.com/maps/search/?api=1&query=47.6,8.8796');
                }
              },
            ),
          ),
      ),
      bottomNavigationBar: BottomAppBar(
        elevation: 0,
        child: Container(
          padding: const EdgeInsets.symmetric(vertical: 19, horizontal: 25),
          height: 80,
          child: InkWell(
            onTap: () {
              if (Platform.isIOS) {
                launch('https://maps.apple.com/?q=47.6,8.8796');
              } else {
                launch(
                    'https://www.google.com/maps/search/?api=1&query=47.6,8.8796');
              }
            },
            child: Text(
              'START NAVIGATION',
              style: TextStyle(
                letterSpacing: 0.35,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

### flutter analyze
```
Analyzing flutter_app...                                                
No issues found! (ran in 1.9s)
```
### flutter doctor:

```
dynClient36:flutter_app mhein$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale de-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.1)
[✓] Connected device (2 available)

• No issues found!
dynClient36:flutter_app mhein$ 

```

**Comment by terrycain** [comment]
I have exactly this issue, works fine on android. Any fix or workaround?

**Comment by Menelphor** [comment]
no fix yet, seems to be an issue with the platform views. See the linked issus. 

A little workaround i did was:
1. Dont have the first google maps screen as your root screen. (I will still refer to this screen as Home Screen, bc it is called so in the code)
2. Set the 2nd Google Maps screen  (Info Screen) in a WillPopScope.
3.  onWillPop: () {
        Navigator.of(context).pop();
        Navigator.of(context).pop();
        Navigator.push(
          context,
          MaterialPageRoute(builder: (context) => HomeScreen()),
        );
       return false;
      },

So the pop method in the Info Screen pops twice and then repushes my HomeScreen which forces it to rebuilt. (I tried to force a rubuilt via setState after the pop but this didn't work)

**Comment by terrycain** [comment]
I'll give that a go when I get some time. Currently I've changed the 2nd map to a static image for now, which does the trick

**Comment by Sthefanny** [comment]
I'm having the same problem, but your workaround didn't work for me... Does anyone have some more workaround or any solution?

**Comment by qypengzai** [comment]
I met same case, do you have any other solution?

**Comment by Menelphor** [comment]
unfortunately not. It seemed to work first with flutter 1.9, but a college was able to reproduce the problem.

**Comment by rubann7** [comment]
Having a similar issue like yours. Found the solution for this problem?

**Comment by Menelphor** [comment]
Only that you pushReplace the second screen. And to navigate back you use pushReplace again in a WillPopScope.

But this does not fix all the problems.

**Comment by RyanRamchandar** [comment]
I ran across and documented the same issue as you: #40050

**Comment by timeuser** [comment]
The opacity hack referenced in issue 40655 seems to work around the problem. Not elegant but it's something.
https://github.com/flutter/flutter/issues/40655#issuecomment-532149553

**Comment by jbxbergdev** [comment]
Might be related to the bug I'm dealing with (I'm only experiencing the behaviour on Android, though): #40284

**Comment by TahaTesser** [comment]
Hi @Menelphor 
Given you duplicate issues you mentioned on first post.
Are you still experiencing this issue?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`?

**Comment by Menelphor** [comment]
Sorry had been corona afk :D

Couldn't reproduce the problem anymore. 

Currently we are using v1.12.13+hotfix.9,

**Comment by TahaTesser** [comment]
Hi @Menelphor 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you for confirmation
