### ISSUE TITLE
While setting theme on my page

### ISSUE THREAD

**Issue by ravikantsharmagit** [flutter/flutter#37612]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by HansMuller** [comment]
I'm closing this because the description doesn't describe a problem with what I assume was a material library theme.  Or any problem at all.

**Comment by ravikantsharmagit** [comment]
You got a log I think so it was sufficient, by the way I have created a
class that extends theme class and it's method are returning themedata but
when I set this themedata as theme of stateless widget I got that crash. It
might helpful to you.
