### ISSUE TITLE
Provide an API to set a custom pixel ratio in the desktop embedder.

### ISSUE THREAD

**Issue by skycomposter** [flutter/flutter#37620]
## Use case

Given the same aspect ratio, I would like my applications to look the same on my embedder, regardless of the actual size of the window. The pixel ratio is exposed as part of the FlutterWindowMetricsEvent struct, but no way to set it explicitly is provided as part of the desktop embedder (I'm working on Linux specifically).

## Proposal

It should be fairly straightforward to pass in the pixel ratio to the FlutterWindow, maybe as part of the WindowFrame passed in SetFrame() or as its own new method.
Currently it seems that the pixel ratio is used to deal with non-standard monitor resolutions, so that might make the change nontrivial.

**Comment by stuartmorgan** [comment]
> Given the same aspect ratio, I would like my applications to look the same on my embedder, regardless of the actual size of the window.

So you want to override it not to a fixed value, but a value that's constantly recomputed as the window resizes?

> Currently it seems that the pixel ratio is used to deal with non-standard monitor resolutions, so that might make the change nontrivial.

The existing logic would determine the default; a manual setting would just override that. So I don't think it should be complicated.

**Comment by skycomposter** [comment]
In my specific use case, I have a number of preset resolutions with a pixel ratio associated to each. I think it would be good enough to allow the value to be set manually when necessary without recomputing as the window resizes.
