### ISSUE TITLE
Regression on flutter_gallery__image_cache_memory start-min

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#37622]
Started at https://github.com/flutter/flutter/commit/09002457f9ceb989af570a40b1441f1e5c27eab4 which seems to enable some tests that weren't running before. @Piinks do you think this might be causing the benchmark tests to take longer? Should this metric be rebaselined?

**Comment by Piinks** [comment]
Could be. I don't know that the change there affected flutter_gallery tests though.

**Comment by franciscojma86** [comment]
It might actually be https://github.com/flutter/flutter/commit/eef3d48377045a846fa865c54c1cccad30a410f9 (I missed that one earlier). Running local tests to figure it out.

**Comment by franciscojma86** [comment]
This metric was rebaselined with https://github.com/flutter/flutter/issues/37273. The increase was expected due to a change in the implementation.
