### ISSUE TITLE
[dashboard] consider a new name for build.json

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3763]
The dashboard box generates a "build.json" file. Since we're not building, I wonder if a new name like "job-status.json" or "dashboard-job-metadata.json" similar would make more sense.

**Comment by sethladd** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
How about `dashboard-status.json`?

**Comment by sethladd** [comment]
I think this file is scoped smaller than the dashboard status. It's only generated by the box itself. The dashboard will grow to have stats from many sources. To start, perhaps we call it "dashboard-bot-status.json"

**Comment by yjbanov** [comment]
👍

**Comment by yjbanov** [comment]
Will rename to `dashboard_bot_status.json` since all other files use underscores.
