### ISSUE TITLE
Document the recommended way of producing multiple embedded Flutter UI / navigation states

### ISSUE THREAD

**Issue by xster** [flutter/flutter#37644]
add-to-app cases adding Flutter as not a single contiguous navigation segment will want to preserve multiple Flutter instances' states and navigations stacks such as 2 Flutter tabs or a Flutter->native->Flutter navigation stack. 

This involves first fleshing out the details of https://github.com/flutter/flutter/issues/37643 and deciding on a multi engine approach or a single engine approach. 

This will likely be scheduled for 2020. Until then, using something like https://github.com/alibaba/flutter_boost (a single engine approach) seems reasonable.

**Comment by xster** [comment]
https://github.com/flutter/flutter/issues/30701 seems like a possibly related feature as well.

**Comment by xster** [comment]
Brainstorming doc go/multiple-flutters (google shared for now)

**Comment by xster** [comment]
Also consider de-globalizing any states in the FVC when going through this (context https://github.com/flutter/flutter/issues/52456)

**Comment by scutlight** [comment]
@xster : Hello, I'm interested in this multiple embedded flutter navigation, could you please offer more info, such as the road map, design doc, or discussions? Thanks!

**Comment by xster** [comment]
It's in our plans. Aaron is doing some prototyping this week. I'll send a doc shortly. We want to make sure we capture all the scenarios flutter_boost needs to solve as well.

**Comment by xster** [comment]
https://flutter.dev/go/multiple-flutters is a doc listing the constrains and requirements. Please take a look and check whether we've listed the needs correctly. The community's existing experience with this topic is highly valued.

**Comment by liyuqian** [comment]
"customer: headline" recently mentioned that they're also very interested in this especially from the memory performance perspective.

**Comment by wanjm** [comment]
no update for a long time any updates?

**Comment by gaaclarke** [comment]
I've been working on a proposal for a Flutter plugin that will encapsulate best practices for most scenarios outlined in the multiple flutters doc.  It isn't published publicly yet.  It's still a work in progress but you can see my design here:
![Screen Shot 2020-09-08 at 10 29 53 AM](https://user-images.githubusercontent.com/30870216/92508932-44e28e80-f1be-11ea-847d-e45b2846fcbe.png)

There is a working prototype here (also a work-in-progress): https://github.com/gaaclarke/host_router

**Comment by wanjm** [comment]
when will it be made public

**Comment by gaaclarke** [comment]
@wanjm https://docs.google.com/document/d/1L_tiTeZpZuJstJmwt6sN6b-79Qy0LzMibCpCmxbtVfU/edit?usp=sharing

I'm still working on it for clarity.

**Comment by xster** [comment]
The new design doc for this that supports concurrent views is at https://flutter.dev/go/multiple-engines

**Comment by Timoteohss** [comment]
That's pretty freaking cool @xster 

I do not mean to be pushy or anything, and I've seen the Release Plan on the document, but is there any chance we see this new API on stable by Q1 2021?
