### ISSUE TITLE
Flutter style guide conflicst with Dart Style guide.

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#37640]
The [Flutter style](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo) and the Dart [style guide](https://dart.dev/guides/language/effective-dart/style) appear to conflict on some cases, like:

[Flutter](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#separate-the-if-expression-from-its-statement):

```dart
// GOOD:
if (notReady)
  return;
```

[Dart](https://dart.dev/guides/language/effective-dart/style#do-use-curly-braces-for-all-flow-control-structures):

```dart
// BAD
if (overflowChars != other.overflowChars)
  return overflowChars < other.overflowChars;
```

Maybe the Flutter style guide should mention this at the introduction? 

I am probably being pedantic, but beginners might find this conflicting and get confused on what to follow.

**Comment by jmagman** [comment]
There was some discussion about this in https://github.com/flutter/flutter/issues/31448.
This is a request for doc clarification though, not a style change.

@Hixie

**Comment by feinstein** [comment]
I think there other stances where the two style guides differ, so it would be nice to discuss it in general.

**Comment by Hixie** [comment]
updated https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#overview
