### ISSUE TITLE
ListView ensure an entry is visible

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#37651]
## Use case

When constructing a ListView of content in an app, I want to be able to scroll the content to ensure a specific item is visible. Example APIs:

* [.NET `ListView.EnsureVisible(Int32)`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listview.ensurevisible?view=netframework-4.8)
* [Qt `QAbstractItemView scrollTo`](https://doc.qt.io/qt-5/qabstractitemview.html#scrollTo)

## Proposal

Add functionality to `ListView` to enable developer to ensure a specific index is visible, scrolling if required.

**Comment by VladyslavBondarenko** [comment]
Hi @domesticmouse 
is https://api.flutter.dev/flutter/widgets/Scrollable/ensureVisible.html what you need?

**Comment by domesticmouse** [comment]
Perfect! How ever did I miss that one.
