### ISSUE TITLE
 [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception: E/flutter (26558): HandshakeException: Handshake error in client (OS Error:  E/flutter (26558):      CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:363))

### ISSUE THREAD

**Issue by naseefro** [flutter/flutter#37655]
I got this error when i run my FLUTTER  app in my phone

[ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (26558): HandshakeException: Handshake error in client (OS Error: 
E/flutter (26558):      CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:363))

![Screenshot 2019-08-06 at 8 19 02 AM](https://user-images.githubusercontent.com/40655679/62507737-eca2c580-b822-11e9-853b-f939a4dddd0d.png)
`

**Comment by naseefro** [comment]
This is my Code

`class _LoginPageState extends State<LoginPage> {
  static const CREATE_POST_URL =
      'https://aniqapidev.mozafgapps.com/api/v1/auth/signin';

  TextEditingController titleControler = TextEditingController();
  TextEditingController bodyControler = TextEditingController();

  Future<User> login(String url, {Map body}) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    return http.post(url, body: body).then((http.Response response) {
      final int statusCode = response.statusCode;
      Map mapRes = json.decode(response.body);
      bool success = mapRes["success"];

      if (statusCode < 200 ||
          statusCode > 400 ||
          json == null ||
          success == false) {
        throw new Exception("Error while fetching data");
      }
      // print('Response from server: $mapRes');
      // if (mapRes['data'] != null) {}
      // Map jwt = mapRes["data"];
      print(mapRes);
      if (success == true) {
        prefs.setString('email', 'useremail@gmail.com');
        //  prefs.setString('jwt', );
        Navigator.push(
            context,
            MaterialPageRoute(
                builder: (context) => MaterialApp(home: Bnavigation())));
      }

      return User.fromJson(json.decode(response.body));
    });
  }
`

**Comment by pouledodue** [comment]
did you find a fix? I have the problem too

**Comment by BondarenkoStas** [comment]
@naseefro Can you try to run ```flutter doctor --android-licenses``` to accept all the licenses if some of them were not accepted?
Also, current stable version is v1.9.1+hotfix.2, please upgrade your flutter.
Is this related to self-signed certificates?

**Comment by naseefro** [comment]
@BondarenkoStas  I did that, still have issues

**Comment by BondarenkoStas** [comment]
@naseefro Please provide your current flutter doctor -v output, and the log in text form. Please do not include screenshots of code/logs. This makes it extremely tedious to reproduce the issue, as we would have to manually transcribe your example.

**Comment by La-Buse** [comment]
I have the same problem. This is the output of flutter doctor -v : 

> [√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.914], locale en-CA)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\levas\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • SM A520W • 5210f162fc09144b • android-arm64 • Android 8.0.0 (API 26) (emulator)

• No issues found!

**Comment by La-Buse** [comment]
This error seems to disappear after deleting unused Kotlin files.

**Comment by iapicca** [comment]
Hi @naseefro 
are you still experiencing this issue with the latest stable version of flutter?
If so could you please provide your updated `flutter doctor -v` 
and your `flutter run --verbose` and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

Thank you
