### ISSUE TITLE
How about decoupling the style out of the dart file

### ISSUE THREAD

**Issue by qiwang97** [flutter/flutter#37669]
## Use case
i start to develop my app this week and i used to work with html/css/js and other framework.
i feel hard to learn and use flutter.

Flutter framework is design to has a lot of classes especially the container widget class such as listview,row,grid. It's hard to remember most of them with its parameters. OK ,i can do it. But another problem raises, too much deep nested structure of widgets and too much textStyle, container style to write and therefore i cannot control the file size. It need much  courage to checkout its correctness.

How much i miss the work i used to do. The sites have three different kinds of files: HTML/CSS/JS. The html decides what it has ,the css file decides what it looks like,the js file decides how it works. Each of them can work independently and i can think how to design its style after i finish its content. But when turn to flutter, i have had to deside to which widget class should i use, what to wtite about its textStyle and its contatner's style.  All put into the dart file together, much complex than i think. Or another file to contain only one class? Much files isn't much complex?

## Proposal
To conclude:
+ would you please consider to decoupling the style out of the dart file with a new language designed for flutter or just use css/stylus/scss? i just want to emphasize the importance of separating the code from the presentation and the structure from the styling.

+ would you consider to simplify the class especially the widget ? Too much widget class to choose to use and remember. Much lightly Much freely. i think developers can decide themselves to use the container like 'div' to design their apps better than others tell them like this: 'Use this,you can do batter".

**Comment by fliermanrw** [comment]
You can separate the style, by creating a dart file like 'style.dart' and having e.g. some TextStyle functions. No need to create or use another language for this:

```
TextStyle boldText({color: Colors.blue}){
    return TextStyle(
      color: color,
      fontSize: 30.0,
      fontWeight: FontWeight.w800
    );
  }
```

then call it like;

```
Widget textExample(){
    return Text(
      "hello text",
      style: boldText(color: Colors.red),
    );
  }
```

I do not agree with your proposal to simplify the widgets. Flutter has (at least for me) made it much easier to create layouts/design exactly because of the big Widget library.

**Comment by qiwang97** [comment]
> You can separate the style, by creating a dart file like 'style.dart' and having e.g. some TextStyle functions. No need to create or use another language for this:
> 
> ```
> TextStyle boldText({color: Colors.blue}){
>     return TextStyle(
>       color: color,
>       fontSize: 30.0,
>       fontWeight: FontWeight.w800
>     );
>   }
> ```
> 
> then call it like;
> 
> ```
> Widget textExample(){
>     return Text(
>       "hello text",
>       style: boldText(color: Colors.red),
>     );
>   }
> ```
> 
> I do not agree with your proposal to simplify the widgets. Flutter has (at least for me) made it much easier to create layouts/design exactly because of the big Widget library.

Thanks and i will try. Maybe you are right.

**Comment by Hixie** [comment]
Closing per coments above.
