### ISSUE TITLE
Switch to 'assemble' regressed track-widget-creation on macOS

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#37660]
The recent switch to using `assemble` for macOS builds regressed #31274, so hot reload in IDEs crashes.

/cc @jonahwilliams

**Comment by stuartmorgan** [comment]
@jonahwilliams Assigning to you; please fix ASAP or revert the assemble change (here and in FDE). I thought this might be straightforward to fix so I wired it back up in the script as a new `-d` and passed it to the `trackWidgetCreation:` that's currently hard-coded to false in `dart.dart`.

The result was that clean builds failed on the copy of flutter_assets, and non-clean builds silently used the wrong (stale) flutter_assets—it took me a while to figure out, since didn't start with a clean build. I don't see any error output from the asset compilation step, it's just apparently silently not actually working correctly once I pass that flag. The build is convoluted enough that I gave up for now on trying to figure out why.

**Comment by jonahwilliams** [comment]
Fix is pending https://github.com/flutter/flutter/pull/37512. Sorry about the trouble this caused. I had though the builtin transformer had landed but that isn't the case.

For the failure case, it would be good to understand why this is happening. Separately I'll revert the assemble change in FDE and the tool

**Comment by jonahwilliams** [comment]
For more context, the prs for landing the SDK included transformer are:

https://github.com/flutter/engine/pull/9227
https://github.com/flutter/engine/pull/9134
https://github.com/flutter/engine/pull/9085

**Comment by jonahwilliams** [comment]
Oh, I think I know what happened there. The re-entrancy of the whole thing is kind of wonky. The Environment created by https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/macos/build_macos.dart#L29 needs to match what gets created by the bash script, or we can' find the executable

**Comment by stuartmorgan** [comment]
I didn't change that, so that would explain it.

Is that a long-term design behavior, or a temporary state because the transition to assemble is in-progress? Having to remember to replicate behavior across two files, in two different languages, 100% correctly, in order to avoid nasty failures (submarine breakages, apparently successful builds using stale data, etc.) that are also hard to understand/debug is something that we should try hard not to have stay around.
