### ISSUE TITLE
Keyboard glitching

### ISSUE THREAD

**Issue by kaifiappsmaven** [flutter/flutter#37666]
hi, whenever keyboard opens either in android/IOS there is glitch that can be seen when keyboard opens. Its not smooth

**Comment by BondarenkoStas** [comment]
@kaifiappsmaven Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

Also please provide your ``` flutter doctor -v``` output

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
