### ISSUE TITLE
how to make flutter ios app soft keyboard follow with input text

### ISSUE THREAD

**Issue by chinacode** [flutter/flutter#37679]
how to make flutter ios app soft keyboard follow with input text？plz help me， our team all in flutter for developer app.

**now issues**：we use flutter developer ios  app . then we find ios soft keyboard do not smooth. 
**expected value**：pop up softboard  like ios native.

**Comment by BondarenkoStas** [comment]
@chinacode Please provide your ```flutter doctor -v``` output. Also, does it reproduced on an emulator or on physical device? On which exactly?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
