### ISSUE TITLE
Flutter doesn't find plugins if Android Studio config path is changed

### ISSUE THREAD

**Issue by cremor** [flutter/flutter#37670]
## Steps to Reproduce

1. Install Android Studio, the Android SDK, the Flutter plugin and the Flutter SDK. Choose a custom path for the Android SDK installation and set `ANDROID_HOME`. Run `flutter doctor`. Everything is fine:
```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.615], locale de-AT)
    • Flutter version 1.7.8+hotfix.4 at C:\Android\flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```
2. Modify `C:\Program Files\Android\Android Studio\bin\idea.properties` so that `idea.config.path` and `idea.system.path` point to custom paths.
3. Move the existing folder `C:\Users\Username\.AndroidStudio3.4` to the new location as configured in step 2.
4. Run `flutter doctor`. It doesn't find Android Studio (and the JDK) any more:
```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.615], locale de-AT)
    • Flutter version 1.7.8+hotfix.4 at C:\Android\flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Android\Sdk
    X No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in
      your PATH. You can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```
5. Call `flutter config --android-studio-dir "C:\Program Files\Android\Android Studio"`. (Note: This is actually the default dir, but it still changes the output!) Now `flutter doctor` does find Android Studio, but not the plugins:
```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.615], locale de-AT)
    • Flutter version 1.7.8+hotfix.4 at C:\Android\flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

Seems like Flutter expects the Android Studio config path (and therefore the plugins) to always be in the user folder? This should be changed so it honors the settings in the `idea.properties` config file.

**Comment by rj-hwang** [comment]
Same problem with me.

**Comment by zkmark** [comment]
Same problem with me. 
Andoid studio 3.6 and flutter 1.12.13
This has not been solved after almost half a year?

**Comment by zkmark** [comment]
install java jdk 8
https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html

Add path
![licences](https://user-images.githubusercontent.com/10190162/76280249-cc266800-6256-11ea-8bb4-912be8e371a1.png)


from step 1 to 12
https://www.360logica.com/blog/how-to-set-path-environmental-variable-for-sdk-in-windows/

run 
flutter doctor --android-licenses

**Comment by androidgj** [comment]
Same problem with me.

**Comment by karthickramanathan95** [comment]
https://github.com/flutter/flutter-intellij/issues/5031

**Comment by HaroldBeyer** [comment]
Same problem here :disappointed:

**Comment by nicolaspernoud** [comment]
Same for me...

**Comment by androidgj** [comment]
> Same problem with me.

I‘ve fixed the problem by update flutter version .

**Comment by worldsoon** [comment]
我也是这个问题，还没修复吗？我只找到了Mac的解决办法，没有window的

**Comment by hammadalishah01** [comment]
I once tried with flutter **_`config --android-studio-dir C:\Program Files\Android\Android Studio`_** but unfortunately it does not work because of empty space which breaks the tree structure. Later I used the quotes like this: `**_flutter config --android-studio-dir "C:\Program Files\Android\Android Studio"_**`. I hope it works for you too!

**Comment by hammadalishah01** [comment]
I once tried with `flutter config --android-studio-dir C:\Program Files\Android\Android Studio` but unfortunately it does not work because of empty space which breaks the tree structure. Later I used the **quotes("")** like this: `flutter config --android-studio-dir "C:\Program Files\Android\Android Studio"`. I hope it works for you as well!

**Comment by yukon-pasindujayanath** [comment]
> I once tried with `flutter config --android-studio-dir C:\Program Files\Android\Android Studio` but unfortunately it does not work because of empty space which breaks the tree structure. Later I used the **quotes("")** like this: `flutter config --android-studio-dir "C:\Program Files\Android\Android Studio"`. I hope it works for you as well!

That work perfectly! Thanks in advance.

**Comment by darshankawar** [comment]
@cremor 
Given the age of this issue, are you still experiencing this using latest version of AS and framework ?
A working solution seems to be given here https://github.com/flutter/flutter/issues/37670#issuecomment-842535926

**Comment by cremor** [comment]
@darshankawar Sorry, I can't answer this because I haven't used Flutter since shortly after I created this issue.

**Comment by darshankawar** [comment]
Based on above comment and considering that a working solution is provided, https://github.com/flutter/flutter/issues/37670#issuecomment-842535926, I am going ahead and closing this as solved.
If anybody still seeing this issue using latest stable version and using Android Studio version, please open a new issue using template so that we can address it properly.
If anybody disagrees, write in comments and I'll reopen it.
