### ISSUE TITLE
firebase_auth Android crash when using the Github AuthProvider

### ISSUE THREAD

**Issue by rafern** [flutter/flutter#37681]
When signing in with GithubAuthProvider credentials with Firebase Auth, the app crashes on Android (stack trace below). This happens because info.getProfile() in mapFromAdditionalUserInfo() has JSONObject.NULL values, and JSONObject.NULL is not null, so the message codec does not detect it as a null.

Most likely related to #37294

Stack trace:
`E/AndroidRuntime(31676): java.lang.IllegalArgumentException: Unsupported value: null
E/AndroidRuntime(31676): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/AndroidRuntime(31676): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
E/AndroidRuntime(31676): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
E/AndroidRuntime(31676): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
E/AndroidRuntime(31676): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:57)
E/AndroidRuntime(31676): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime(31676): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$SignInCompleteListener.onComplete(FirebaseAuthPlugin.java:691)
E/AndroidRuntime(31676): 	at com.google.android.gms.tasks.zzj.run(Unknown Source)
E/AndroidRuntime(31676): 	at android.os.Handler.handleCallback(Handler.java:836)
E/AndroidRuntime(31676): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(31676): 	at android.os.Looper.loop(Looper.java:203)
E/AndroidRuntime(31676): 	at android.app.ActivityThread.main(ActivityThread.java:6251)
E/AndroidRuntime(31676): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31676): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1067)
E/AndroidRuntime(31676): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)`

**Comment by blasten** [comment]
cc @mklim @amirh

**Comment by mklim** [comment]
Thanks for the bug report! /cc @collinjackson and @kroikie, codeowners for `firebase_auth`.

**Comment by Fallenstedt** [comment]
I have a similar issue when signing in a user with TwitterAuthProvider
```
import 'package:flutter_twitter_login/flutter_twitter_login.dart';
...
 final TwitterLoginResult twitterResult = await _twitter.authorize();
      final AuthCredential userCredentials = TwitterAuthProvider.getCredential(
          authToken: twitterResult.session.token,
          authTokenSecret: twitterResult.session.secret,
      );

      final AuthResult authResult =
          await _firebaseAuth.signInWithCredential(userCredentials);
```

This only occurs when I call `_firebaseAuth.signinWithCredential`. If you would like an example repo, please let me know

**Comment by Fallenstedt** [comment]
Has anyone found a work around? I've been tinkering with what I can do and digging into the source of the firebase_auth plugin and I cannot create a solution. If you have a found a work around, I would love to know. My android compileSdkVersion and targetSdkVersion are set to `28`.

At this point, the firebase_auth might be an adoption blocker until this is fixed.

**Comment by rafern** [comment]
@Fallenstedt Sorry, I should have added this earlier, but this works for me with the Github auth provider (it might work for Twitter too but I can't test with Twitter):
Comment out line 775 in FirebaseAuthPlugin.java:
```java
  private Map<String, Object> mapFromAdditionalUserInfo(AdditionalUserInfo info) {
    if (info != null) {
      Map<String, Object> additionalUserInfoMap = new HashMap<>();
      //additionalUserInfoMap.put("profile", info.getProfile()); // THIS LINE
      additionalUserInfoMap.put("providerId", info.getProviderId());
      additionalUserInfoMap.put("username", info.getUsername());
      additionalUserInfoMap.put("isNewUser", info.isNewUser());
      return Collections.unmodifiableMap(additionalUserInfoMap);
    } else {
      return null;
    }
  }
```
Here's a diff:
```diff
775c775
<       additionalUserInfoMap.put("profile", info.getProfile());
---
>       //additionalUserInfoMap.put("profile", info.getProfile());
```

As for the actual solution, I found that it would be best to just add support for JSONObject.NULL to the message codec, but this would be a fix for the Flutter engine and not firebase_auth:
In StandardMessageCodec.java:
```java
        } else if (value instanceof Map) {
            stream.write(MAP);
            final Map<?, ?> map = (Map) value;
            writeSize(stream, map.size());
            for (final Entry<?, ?> entry: map.entrySet()) {
                writeValue(stream, entry.getKey());
                writeValue(stream, entry.getValue());
            }
        } else if (value.equals(null)) { // These two lines should be added
            stream.write(NULL);
        } else {
            throw new IllegalArgumentException("Unsupported value: " + value);
        }
```
Again, diff:
```diff
292a293,294
>         } else if (value.equals(null)) {
>             stream.write(NULL);
```

If anyone could test the above I would really appreciate it as I don't have a Flutter engine build environment and, therefore, haven't made a PR.

**Comment by Fallenstedt** [comment]
I wanted to post an update to this. I got `firebase_auth` working on iOS perfectly when authenticating with Twitter. This crash occurs on Android only.

**Comment by gasscoelho** [comment]
I'm having the same problem. First attempt my app crash but when i lauch again it got the authentication. Did you find a solution to run this on Android?

**Comment by rafern** [comment]
@gasscoelho There is a workaround above in this thread. You can follow the PR for the solution as well in https://github.com/flutter/engine/pull/11283

**Comment by gasscoelho** [comment]
I'm sorry for this question but i'm new to flutter and git. 
I tried to follow your suggestion but I couldn't find this FirebaseAuthPlugin.java file. I tried to look in my project's folder but i was only able to find the .class. Can you send me the path of this file?

**Comment by rafern** [comment]
@gasscoelho If you're using intellij or androidstudio, on the left there is the project pane. At the bottom of the project pane, open "external libraries". Then, open "flutter plugins". Then, go to the firebase_auth folder and the file should be in android > src.main > java.io.flutter.plugins.firebaseauth > FirebaseAuthPlugin.java. The file extension may be hidden and so the file name may be just FirebaseAuthPlugin
![screen](https://user-images.githubusercontent.com/15365765/64360863-4275b380-d003-11e9-8d6f-aef7d75b71fe.png)

**Comment by gasscoelho** [comment]
@rafern I was using vscode but then I reopened my project with android studio. I found the file though the path you showed me and changed it as you suggested. I run my project again and now it's working. Thank you so much!

**Comment by dshukertjr** [comment]
This issue should not be closed as the issue is not truly resolved.

**Comment by rafern** [comment]
@dshukertjr I just tried it out and you have to use the dev channel for now, since the fix for the engine hasn't even gone to the beta branch yet. To switch to the dev channel, run this:
```
flutter channel dev 
flutter upgrade
```
You will probably run into other issues since its the dev branch, so, if I were you, I would use the workaround mentioned above for now until the fix goes to beta or stable

**Comment by yudi43** [comment]
Finally it worked!!!

**Comment by kroikie** [comment]
@rafern

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/348. Any further collaboration will be done there.

**Comment by niypoo** [comment]
I'm Facing this issue too
