### ISSUE TITLE
BugFix: RoundedRectSliderTrack rendering

### ISSUE THREAD

**Issue by Amjad50** [flutter/flutter#37683]
## Use case

Better in rendering RoundedRectSliderTrack which is the default Track

## Proposal
- before: if the slider is high enough there were some bugs:
  + the left arc was always coloured even if the slider is zero.
  + the right arc was always not coloured even if the slider is full.
  + some space between the track and the thumb in the middle,
     this happened when the thumb was a circle (default) or
     any shape that does not have a flat right and left sides.

![image](https://user-images.githubusercontent.com/26300843/62537738-d8c68600-b859-11e9-8ef8-600d08b09f08.png)

- after: fixed the stated above bugs

![image](https://user-images.githubusercontent.com/26300843/62537770-eda31980-b859-11e9-82f1-30735183a223.png)

*the above images are at 100%, 0%, 55% respectively*

the code is 
```flutter
    final Rect leftTrackArcRect = Rect.fromLTWH(
      trackRect.left - trackRect.height / 2,
      trackRect.top,
      trackRect.height,
      trackRect.height,
    );

    final Rect rightTrackArcRect = Rect.fromLTWH(
      trackRect.right - trackRect.height / 2,
      trackRect.top,
      trackRect.height,
      trackRect.height,
    );

    final Rect leftTrackSegment = Rect.fromLTRB(
      trackRect.left,
      trackRect.top,
      thumbCenter.dx,
      trackRect.bottom,
    );

    final Rect rightTrackSegment = Rect.fromLTRB(
      thumbCenter.dx,
      trackRect.top,
      trackRect.right,
      trackRect.bottom,
    );

    // draw
    if (!leftTrackArcRect.isEmpty)
      context.canvas.drawArc(leftTrackArcRect, math.pi / 2, math.pi, false,
          leftTrackSegment.isEmpty ? rightTrackPaint : leftTrackPaint);

    if (!rightTrackArcRect.isEmpty)
      context.canvas.drawArc(rightTrackArcRect, -math.pi / 2, math.pi, false,
          rightTrackSegment.isEmpty ? leftTrackPaint : rightTrackPaint);

    if (!leftTrackSegment.isEmpty)
      context.canvas.drawRect(leftTrackSegment, leftTrackPaint);

    if (!rightTrackSegment.isEmpty)
      context.canvas.drawRect(rightTrackSegment, rightTrackPaint);
```

in the bottom of `paint` function

**Comment by HansMuller** [comment]
CC @clocksmith

**Comment by clocksmith** [comment]
This looks great! Can you open a PR with the fix (and a test) ?

**Comment by Amjad50** [comment]
OK, thanks :)

**Comment by Amjad50** [comment]
Sorry, I wasn't done yet
