### ISSUE TITLE
Update Draggable child when enters dragtarget

### ISSUE THREAD

**Issue by Taqbeel** [flutter/flutter#37694]
I am using flutter for some drag and drop. I have a draggable item and it has a child, childwhendragging and a feedback. All of these working perfectly. but when I drag the child to dragtarget and dragtarget accept that child, I then want to change draggable child and make that child undraggable. I mean disable that item.
here is the code.
```
Container(
                            child: Draggable(
                              child: new Image.asset('assets/images/Visa_Cal.png', width: 50, height: 50,),
                              feedback: new Image.asset('assets/images/Visa_Cal.png', width: 50, height: 50,),
                              childWhenDragging: Container(child: new Image.asset('assets/images/Visa_Cal_blur.png', width: 50, height: 50,)),
                              data: Image.asset('assets/images/Visa_Cal.png', width: 50, height: 50,),
                            ),
                        ),

________________________________________________

new Positioned(
                  right: 15.0,
                  bottom: 0.0,

                  child: success ? Container() :  DragTarget(
                    builder: (context, List<Image> data, rj) {
                      return tempImg;
                    },
                    onAccept: (data) {
                      tempImg=data;
                      success = true;
                      count++;
                    },
                  ),
                ),
```

**Comment by BondarenkoStas** [comment]
@Taqbeel This is a question better suited for StackOverflow, since there doesn't seem to be anything wrong with Flutter itself, but related to implementation.
Please check for example https://stackoverflow.com/questions/54470230/how-to-update-draggable-child-when-entering-dragtarget-in-flutter, it may be helpful.
Closing it. If you disagree, feel free to comment and I will reopen it.
