### ISSUE TITLE
[!] Invalid `Podfile` file: undefined method `pod' for main:Object.

### ISSUE THREAD

**Issue by azizoy** [flutter/flutter#37692]
I have an existing app and try to install flutter on it but i get this issue:

<img width="571" alt="Jepretan Layar 2019-08-06 pukul 21 14 30" src="https://user-images.githubusercontent.com/34239570/62547457-6ec8d380-b88f-11e9-9ce6-b27cba40ed6e.png">

i have no idea how to solve this issue.

**Flutter Version :** 
`Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (3 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0`

**Flutter Doctor**
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E226, locale
    id-ID)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
[✗] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.`

**Comment by jmagman** [comment]
1. Adding to an existing application is an experimental feature. You are on the stable channel but must be on the master channel.

2. The required format of the Podfile recently changed. Check out these instructions to migrate: https://github.com/flutter/flutter/wiki/Upgrading-Flutter-added-to-existing-iOS-Xcode-project

**Comment by jmagman** [comment]
See https://github.com/flutter/flutter/issues/37373 for further discussion.
