### ISSUE TITLE
Gradle Build failing after adding firebase_messaging plugin

### ISSUE THREAD

**Issue by byshy** [flutter/flutter#37696]
when adding the firebase_messaging: ^5.1.2 my app doesn't build, after removing it, the app builds with no problems, I tried to migrate to androidX but this didn't help, also tries to use multi dex, didn't help

I only get one red error line that says: Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by blasten** [comment]
Would you mind running the command with the `--verbose` flag?

**Comment by byshy** [comment]
here is the outcome of running the `flutter run --verbose`

Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:507:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:346:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:426:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:371:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:251:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:469:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#27     new Future.sync (dart:async/future.dart:224:31)
#28     CommandRunner.run (package:args/command_runner.dart:112:14)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#30     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1500:12)
#35     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1463:12)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#42     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#43     run (package:flutter_tools/runner.dart:51:10)
#44     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#45     main (file:///C:/Users/byshy/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by byshy** [comment]
I created a new project with firebase_messaging being the only plugin in the project, and it worked! 
**BUT** as soon as I added the other libraries same problem again

**Comment by kroikie** [comment]
@byshy In your app's android directory could you run `./gradlew assembleDebug` and see if that gives more gradle specific error logs.

**Comment by Akmal02** [comment]
Hi.
I'm having the same problem as @byshy, adding fIrebase_messaging ^5.1.2 broke my app's build process, and ending up with a single line saying 'Finished with error: Gradle task assembleDebug failed with exit code 1'. 

Currently using this firebase plugin version in pubspec.yaml

```
  firebase_core: ^0.4.0
  firebase_database: ^3.0.5
  firebase_auth: ^0.14.0
  firebase_messaging: ^5.1.2
  cloud_functions: ^0.4.1

```

flutter run -v output:

```
...
[  +21 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] executing: [C:\Users\Akmal\AndroidStudioProjects\FLUTTER\ofisku\android\] C:\Users\Akmal\AndroidStudioProjects\FLUTTER\ofisku\android\gradlew.bat -Pverbose=true
-Ptarget=C:\Users\Akmal\AndroidStudioProjects\FLUTTER\ofisku\lib/main.dart -Ptrack-widget-creation=false -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64
assembleDebug
[+2274 ms] > Configure project :app
[   +1 ms] WARNING: API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'.
[        ] It will be removed at the end of 2019.
[        ] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[        ] To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
[        ] WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
[        ] It will be removed at the end of 2019.
[   +3 ms] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[        ] To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
[        ] WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
[        ] It will be removed at the end of 2019.
[        ] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[   +1 ms] To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
[+8969 ms] Dependency resolved to an incompatible version: Dependency(fromArtifactVersion=ArtifactVersion(groupId=com.google.firebase, artifactId=firebase-messaging, version=18.0.0),
toArtifact=Artifact(groupId=com.google.firebase, artifactId=firebase-iid), toArtifactVersionString=[18.0.0])
[   +8 ms]          *********************************************************
[   +2 ms] WARNING: This version of cloud_functions will break your Android build if it or its dependencies aren't compatible with AndroidX.
[   +1 ms]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[   +1 ms]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[   +1 ms]          *********************************************************
[ +555 ms] Running Gradle task 'assembleDebug'... (completed in 11.8s)
[   +8 ms] "flutter run" took 19,074ms.
[        ] "flutter run" took 19,074ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:507:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:346:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:426:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:371:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:251:39)
<asynchronous suspension>
...
```

./gradlew assembleDebug output

```
...
WARNING: This version of cloud_functions will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************
In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[18.0.
0]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

Dependency failing: com.google.firebase:firebase-messaging:18.0.0 -> com.google.firebase:firebase-iid@[18.0.0], but fire
base-iid version was 19.0.0.

The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
ifact with the issue.
-- Project 'app' depends onto com.google.firebase:firebase-iid@{strictly 19.0.0}
-- Project 'app' depends onto com.google.firebase:firebase-core@17.0.1
-- Project 'app' depends onto com.google.firebase:firebase-analytics@{strictly 17.0.0}
-- Project 'app' depends on project 'firebase_messaging' which depends onto com.google.firebase:firebase-messaging@18.0.
0
-- Project 'app' depends on project 'cloud_functions' which depends onto com.google.firebase:firebase-functions@17.0.0
-- Project 'app' depends onto com.google.firebase:firebase-functions@{strictly 17.0.0}
-- Project 'app' depends on project 'firebase_core' which depends onto com.google.firebase:firebase-core@16.0.9
-- Project 'app' depends onto com.google.firebase:firebase-messaging@{strictly 18.0.0}
-- Project 'app' depends onto com.google.firebase:firebase-core@{strictly 17.0.1}
-- Project 'app' depends onto com.google.android.gms:play-services-measurement-api@{strictly 17.0.0}

For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
uild.gradle file.
...
```

Have even tried disabling version check by adding **com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true** as per https://stackoverflow.com/questions/53007342/flutter-version-conflict-with-location-and-firebase-messaging, however the build process failed faster than before.


```
...
[  +13 ms] Initializing gradle... (completed in 1.0s)
[   +1 ms] Resolving dependencies...
[   +1 ms] executing: [C:\Users\Akmal\AndroidStudioProjects\FLUTTER\ofisku\android\] C:\Users\Akmal\AndroidStudioProjects\FLUTTER\ofisku\android\gradlew.bat app:properties
[+1906 ms] Resolving dependencies... (completed in 1.9s)
[   +3 ms] * Error running Gradle:
           ProcessException: Process "C:\Users\Akmal\AndroidStudioProjects\FLUTTER\ofisku\android\gradlew.bat" exited abnormally:
           
             Command: C:\Users\Akmal\AndroidStudioProjects\FLUTTER\ofisku\android\gradlew.bat app:properties
           
[   +5 ms] "flutter run" took 3,524ms.
[        ] "flutter run" took 3,524ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:158:7)
<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:111:34)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:105:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:160:23)
<asynchronous suspension>
#5      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:47:32)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:352:56)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:251:39)
<asynchronous suspension>
...

```

I believed this is caused by Firebase dependencies conflicts similar to other issues I found. Have considered to downgrading to the older firebase plugin version but didn't know the correct combination of them to make it work without conflicting with each other. (Other solution I found mostly use the older firebase version).

I have also enable AndroidX and updated the Google service dependencies to the latest version in project build.gradle app/build.gradle

```

buildscript {

    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.gms:google-services:4.3.0'
    }
...

```

```
...
dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.google.firebase:firebase-core:17.0.1'
}

apply plugin: 'com.google.gms.google-services'
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
...

```


My flutter doctor -v output:
```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.239], locale en-MY)
    • Flutter version 1.7.8+hotfix.4 at C:\src\flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\Akmal\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Users\Akmal\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1
    • Flutter plugin version 35.2.2
    • Dart plugin version 191.6183.88

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\Akmal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • Redmi 4X • 6b0cd797d440 • android-arm64 • Android 7.1.2 (API 25)

• No issues found!

```

Current workaround is I need to avoid using firebase_messaging for now, hoping this issue can be resolved.

**Comment by byshy** [comment]
@kroikie I solved the error but I'm not sure how, maybe it's related to Multidex, because the way I added it the second time was different from the first

@Akmal02 you can find how to enable Multidex here https://developer.android.com/studio/build/multidex and make sure that you migrated to android x correctly (you can find it here https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility)

please state here if this was successful or not because I want to be sure if this was my issue or not

**Comment by blasten** [comment]
I was unable to repro this issue by just adding the dependencies:
```
  firebase_core: ^0.4.0
  firebase_database: ^3.0.5
  firebase_auth: ^0.14.0
  firebase_messaging: ^5.1.2
  cloud_functions: ^0.4.1
```
or just:
```
  firebase_messaging: ^5.1.2
```

The app is created by running `flutter create` or `flutter create --androidx`.

I'd need the exact steps that reproduces the issue. Otherwise, the source code of the app if you can.

**Comment by byshy** [comment]
I added all the following packages then after a while added the messaging one

firebase_core: ^0.4.0+6
firebase_auth: ^0.11.1+8
google_sign_in: ^4.0.4
cloud_firestore: ^0.12.7
firebase_storage: ^3.0.5
flutter_bloc: ^0.20.0
equatable: ^0.3.0
http: ^0.12.0+2
shared_preferences: ^0.5.3+4
image_picker: ^0.6.1
image_cropper: ^1.0.2
cached_network_image: ^1.1.1
intl: ^0.15.8

also the problem is back I don't know why AGAIN!

**Comment by byshy** [comment]
I made a new project in both android studio and firebase, what I found is that there where new steps in the process of making a new firebase project, now everything works perfectly after following them, please try it and give me some feedback on it to decide if this issue should be closed or not.

**Comment by Akmal02** [comment]
I guess i have solved the problem for now. After following https://firebase.google.com/docs/flutter/setup I have noticed the line that says **"Note: Flutter is currently compatible with version 3.2.1 of the Google Services plugin."**. Checking back on the current project and it uses version 4.3.0 (Maybe I had used Android Studio intention feature and accidentally upgrading that. Downgrading back by modifying build.gradle and replacing the line to **classpath 'com.google.gms:google-services:3.2.1'**. Now everything compiles and builds as expected. 

Anyway I still think it's weird since my project compiles properly prior to including firebase_messaging even though I had used version 4.3.0 on the build.gradle before . I have tried to reproduce this by creating new projects and building them with firebase plugins included, and somehow i get different results depending on how i create the new Flutter project.

1. Create a new Flutter project*
2. Following https://firebase.google.com/docs/flutter/setup, create a new Firebase project at console.firebase.google.com, and register the new project in Firebase by including the application package name, in my case I used _com.example.firetest_
3. Download the google-services.json and copy it into the projects's android/app directory.
4. Returning from the project, include these lines under dependencies part in pubspec.yaml

```
  firebase_core: ^0.4.0
  firebase_database: ^3.0.5
  firebase_auth: ^0.14.0
  firebase_messaging: ^5.1.2
  cloud_functions: ^0.4.1

```
5. In project's build.gradle, add `  classpath 'com.google.gms:google-services:3.2.1'` in dependencies part.
6. In app/build.gradle, add `apply plugin: 'com.google.gms.google-services'` at the bottom of the file.
7. Run `flutter packages get`
8. Run `flutter run -v`

* Using `flutter create` from terminal, everything compiles perfectly.
* Using `flutter create --androidx` the build process crashed and produces the following error. 

```
[   +3 ms] FAILURE: Build failed with an exception.
[  +40 ms] * What went wrong:
[   +4 ms] Execution failed for task ':app:preDebugBuild'.
[   +5 ms] > Android dependency 'androidx.localbroadcastmanager:localbroadcastmanager' has different version for the compile (1.0.0-rc01) and runtime(1.0.0) classpath. You should manually set the same version via DependencyResolution
[  +11 ms] * Try:
[  +22 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get fullinsights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 30s
[ +250 ms] Running Gradle task 'assembleDebug'... (completed in 31.5s)
[        ] *******************************************************************************************
[        ] The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
[   +1 ms] See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ] *******************************************************************************************
```

**Comment by byshy** [comment]
this is it, closing the issue now
happy coding everyone

**Comment by kroikie** [comment]
@byshy

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1050. Any further collaboration will be done there.
