### ISSUE TITLE
Why there is not a flutter/web issue icon in the github 

### ISSUE THREAD

**Issue by Noisre** [flutter/flutter#37698]
Why there is not a flutter/web issue icon in the github

**Comment by yjbanov** [comment]
Did you mean label instead of icon? We use `platform-web` label for flutter web issues.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
