### ISSUE TITLE
`defaults` command parsing plist files differently on macOS Catalina

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#37701]
*NOTE* This was copy-pasted from https://github.com/flutter/flutter/issues/33909 by @kangwang1988.

The output of `flutter run -v`:

```
The domain/default pair of (/Users/kylewong/Desktop/hello_flutter/ios/Runner/Info, CFBundleIdentifier) does not exist
```

In flutter, defaults comand instread of plutil is used to parse plist files. However, defaults command in MacOS 10.15 seems working unexpectedly.

```
kylewong@KyleWongdeMacBook-Pro Downloads % md5 /Applications/Android\ Studio.app/Contents/Info.plist 
MD5 (/Applications/Android Studio.app/Contents/Info.plist) = 35022a129a5bc23c51b2c05c9029ebe9
kylewong@KyleWongdeMacBook-Pro Downloads % md5 /Users/kylewong/Downloads/Info.plist 
MD5 (/Users/kylewong/Downloads/Info.plist) = 35022a129a5bc23c51b2c05c9029ebe9
```

Those two plist has the same md5, however, defaults works differently.

```
% defaults read /Users/kylewong/Downloads/Info
2019-06-06 10:26:27.505 defaults[26063:176464] 
Domain /Users/kylewong/Downloads/Info does not exist
kylewong@KyleWongdeMacBook-Pro Downloads % defaults read /Applications/Android\ Studio.app/Contents/Info
{
    CFBundleDevelopmentRegion = English;
    CFBundleDocumentTypes =     (
                {
            CFBundleTypeExtensions =             (
                ipr
            );
            CFBundleTypeIconFile = "studio.icns";
            CFBundleTypeName = "Android Studio Project File";
            CFBundleTypeRole = Editor;
        },
```

It seems plutil works fine now while the defaults command fails.

```
plutil -p /Users/kylewong/Downloads/Info.plist
{
  "CFBundleDevelopmentRegion" => "English"
  "CFBundleDocumentTypes" => [
    0 => {
      "CFBundleTypeExtensions" => [
        0 => "ipr"
      ]
      "CFBundleTypeIconFile" => "studio.icns"
      "CFBundleTypeName" => "Android Studio Project File"
      "CFBundleTypeRole" => "Editor"
    }
    1 => {
      "CFBundleTypeExtensions" => [
        0 => "*"
      ]
      "CFBundleTypeName" => "All documents"
      "CFBundleTypeOSTypes" => [
        0 => "****"
      ]
      "CFBundleTypeRole" => "Editor"
      "LSTypeIsPackage" => 0
    }
```

cc @vanelizarov

As it is not a blocker now and macos 10.15 is still in beta, I don't think it's a good practice to change the plist parsing logic in flutter.

Updated at 2019-06-06 10:34:59

**Comment by christopherfujino** [comment]
This looks similar https://github.com/flutter/flutter/issues/35256

**Comment by christopherfujino** [comment]
@kangwang1988 could you provide a minimal reproduceable setup for this? I cannot reproduce it. Thanks

**Comment by stuartmorgan** [comment]
> As it is not a blocker now and macos 10.15 is still in beta, I don't think it's a good practice to change the plist parsing logic in flutter.

The use of `defaults` to read arbitrary plists is explicitly unsupported. From its man page (this is on 10.14):
```
     filepath  Domains may also be specified as a path to an arbitrary plist
               file, with or without the '.plist' extension. For example:
[...]
               WARNING: The defaults command will be changed in an upcoming
               major release to only operate on preferences domains. General
               plist manipulation utilities will be folded into a different
               command-line program.
```

I don't see any reason to assume that this error output isn't exactly the change that has been previously warned about. Even if it's not, rewriting our parsing logic to not rely on a behavior that is explicitly documented as something that shouldn't be relied is a good idea; it'll break in a later release if not this one.

**Comment by tvolkert** [comment]
We say not to rely on `PlistBuddy` here:

https://github.com/flutter/flutter/blob/ca5411e3aa99d571ddd80b75b814718c4a94c839/packages/flutter_tools/lib/src/ios/plist_utils.dart#L17-L19

But then, we rely on `/usr/libexec/PlistBuddy` here:

https://github.com/flutter/flutter/blob/ca5411e3aa99d571ddd80b75b814718c4a94c839/packages/flutter_tools/bin/xcode_backend.sh#L57

Since we already have such a dependency, should we formalize it by checking for it in doctor and using it explicitly?

**Comment by tvolkert** [comment]
Then again, if the user doesn't have `PlistBuddy`, that command in `xcode_backend.sh` will just produce an empty `$FLTAssetsPath`, so it's a soft dependency.

**Comment by tvolkert** [comment]
If we can use `plutil`, that's probably the best way to go, no?

**Comment by tvolkert** [comment]
Whatever hard dependency we take on, we need to make sure to add a doctor check for it so the user can see what's wrong if they don't have that tool.

**Comment by christopherfujino** [comment]
Looking at using `plutil`, must add a doctor check for it

**Comment by Hixie** [comment]
Assigning per recent discussion. ETA is tomorrow.

**Comment by tvolkert** [comment]
Writing tests for this, I found the case that triggers the OP bug: Plist files that are encoded as JSON no longer work with `defaults` in Catalina.
