### ISSUE TITLE
Requesting example of iOS + FlutterView + messaging (similar to hello_android)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3771]
Now that https://github.com/flutter/flutter/issues/3256 is closed (yay!) we might be able to add a hello_ios example (equivalent to hello_android).

**Comment by abarth** [comment]
Not.  Still need to land https://github.com/abarth/engine/tree/extensible_ios

**Comment by abarth** [comment]
Patches have landed but there are a few bugs to work out still.

**Comment by chinmaygarde** [comment]
Can we close this now?

**Comment by abarth** [comment]
We don't actually have an example yet.  I was going to factor the Xcodeproject into the developer-controlled and Flutter-controlled pieces before creating the example.

**Comment by abarth** [comment]
This example now exists: https://github.com/flutter/flutter/tree/master/examples/hello_services
