### ISSUE TITLE
A new, consistent name for the Gallery app?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3773]
When I install the app on Android, I see "Flutter Material" in my home screen. On iOS, I see "Material Gallery".

We're a bit more than just material. What about "Flutter Gallery" ?

**Comment by sethladd** [comment]
cc @HansMuller @vlidholt @mpcomplete

**Comment by abarth** [comment]
+1 to Flutter Gallery.  We should probably rename the directory to match too.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/blob/master/examples/material_gallery/ios/Info.plist#L14
https://github.com/flutter/flutter/blob/master/examples/material_gallery/android/AndroidManifest.xml#L11

**Comment by HansMuller** [comment]
We'd intended to call the app "Flutter Gallery", I will make it so.
