### ISSUE TITLE
[web]: How to use SVG image in listview

### ISSUE THREAD

**Issue by Parmendrakumar** [flutter/flutter#37749]
Flutter SDK v1.8.3

I am unable to find SvgPicture.network(), Its working fine on Mobile. When I use dart.svg packge then I don''t have option of SVG Images

 return ListTile(title: Text(country[index].name,style: TextStyle(fontWeight: FontWeight.bold)), subtitle: Text(country[index].capital),leading:  SvgPicture.network(country[index].flag, width: 20,
              height: 20,), trailing: Icon(Icons.keyboard_arrow_right),

**Comment by mannprerak2** [comment]
Use this package -> https://pub.dev/packages/flutter_svg
```dart
final Widget networkSvg = new SvgPicture.network(
  'https://site-that-takes-a-while.com/image.svg',
  semanticsLabel: 'A shark?!',
  placeholderBuilder: (BuildContext context) => new Container(
      padding: const EdgeInsets.all(30.0),
      child: const CircularProgressIndicator()),
);
```

**Comment by Parmendrakumar** [comment]
Its working on Flutter Mobile, But getting issue on Web? Is this work on flutter_web?

**Comment by jld3103** [comment]
The plugin is not usable with flutter web.

**Comment by mannprerak2** [comment]
It won't work on flutter web as it depends on flutter sdk
(flutter web isn't available in the stable channel yet)
Even then.. I wouldn't recommend making a flutter web app for production as of now, its very heavy and lags a lot..
and then rendering SVG would contribute even more to lag.

**Comment by jld3103** [comment]
I'm using the unforked version of flutter and it's working for me.

**Comment by Parmendrakumar** [comment]
Any Idea about how to use SVG in flutter_web

**Comment by jld3103** [comment]
You have the dart:svg library, but as long as your app is usable without the svg I think the cost of implementation for web is too high.

**Comment by jld3103** [comment]
OK sorry. I checked today again and either the plugin broke in the mean time or it never worked and I remembered wrong :(

**Comment by jld3103** [comment]
So after implementing my own web "plugin" for firebase messaging yesterday, I would say it should be feasible to implement a web plugin for flutter_svg, because the library for svg drawing is right in dart.
My web firebase messaging "plugin": https://github.com/jld3103/ginko/commit/9eef819d808077515d46dcdcd5f1c0ab018e4ebc

**Comment by jld3103** [comment]
My idea is to provide the same interface as flutter_svg.
On Android/iOS it simply calls the real plugin, but on web it insert something like a container and the uses js to insert the svg into the DOM tree.

**Comment by jld3103** [comment]
I'm able to replace a DOM node and display the svg, but the svg currently shows as big as possible.

**Comment by jld3103** [comment]
Finally I got it!
https://github.com/jld3103/ginko/commit/deebb54397d4f3b89047d7e57045d5a996a964e2
Ask me any question about it if you want :)

**Comment by Parmendrakumar** [comment]
Thanks you let me try

**Comment by Parmendrakumar** [comment]
@jld3103 Can I use .jpg or .png image in flutter web.

I want to display any static image in flutter web app. Where I can store this image and how to use it.

**Comment by jld3103** [comment]
@Parmendrakumar This has nothing to do with this issue, but you simply use it like a normal image in flutter.
https://flutter.dev/docs/development/ui/assets-and-images

**Comment by BondarenkoStas** [comment]
@Parmendrakumar is the issue solved as proposed in https://github.com/flutter/flutter/issues/37749#issuecomment-520401616?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
