### ISSUE TITLE
[dashboard] periodically refresh Firebase page

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#3774]
Our code is unlikely to be robust enough to keep the page healthy for extended periods of time purely based on Firebase notifications.

/cc @sethladd

**Comment by sethladd** [comment]
The page should be refreshing every 2 hours.

https://github.com/flutter/dashboard_box/blob/master/web/script.js#L3

**Comment by yjbanov** [comment]
nvm then, closing :)
