### ISSUE TITLE
GoogleMaps screen garbled after screen rotation in a secondary screen

### ISSUE THREAD

**Issue by babaosoftware** [flutter/flutter#37745]
Add GoogleMaps on a basic screen. Navigate to a second screen. Rotate phone screen once, and go back to the first screen. The screen is garbled, and stays like that even after subsequent rotations. See attached sample file and screenshots.
Problem reproduces on both simulator and real devices.
If GoogleMaps widget is removed and/or replaced with other widgets, there are no problems.
Google Maps SDK for iOS version: 3.3.0.0 (same problem with previous versions)
google_maps_flutter: ^0.5.20+1 (same problem with previous versions)
Sample file:
```
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'GoogleMaps Rotation Bug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  void _showSecondScreen() {
    Navigator.push(
        context,
        MaterialPageRoute(
        builder: (context) => SecondScreen()));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Stack(
          children: <Widget>[
            GoogleMap(
              initialCameraPosition: CameraPosition(
                target: LatLng(40.731753, -73.986115),
                zoom: 12.0,
              ),
            )          ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _showSecondScreen,
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class SecondScreen extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    return SafeArea(
        top: false,
        bottom: true,
        left: true,
        right: true,
        child: Scaffold(
            appBar: AppBar(
              title: Text("Second Screen"),
            ),
            body: Center(child: Text("Rotate screen once and back!"))));
  }

}
```

![Simulator Screen Shot - iPhone X - 2019-08-06 at 23 15 55](https://user-images.githubusercontent.com/8468554/62592181-3978b180-b8a0-11e9-9c11-35bcb570f197.png)
![Simulator Screen Shot - iPhone X - 2019-08-06 at 23 16 05](https://user-images.githubusercontent.com/8468554/62592188-3ed5fc00-b8a0-11e9-8e9f-e0c65c9a8e68.png)
![Simulator Screen Shot - iPhone X - 2019-08-06 at 23 16 12](https://user-images.githubusercontent.com/8468554/62592194-43021980-b8a0-11e9-9316-01ee1cb2ff87.png)
![Simulator Screen Shot - iPhone X - 2019-08-06 at 23 16 20](https://user-images.githubusercontent.com/8468554/62592199-4695a080-b8a0-11e9-8955-cf89a6a32c95.png)

**Comment by Dawnthorn** [comment]
Looks the same as #30130

**Comment by babaosoftware** [comment]
Indeed, this is a duplicate of https://github.com/flutter/flutter/issues/30130
Too bad its not fixed yet.
