### ISSUE TITLE
Wrong 2nd argument type. Found "androidx.lifecycle.Lifecycle", required "Lifecycle"

### ISSUE THREAD

**Issue by rrifafauzikomara** [flutter/flutter#37757]
I created an Android host application in the `Android Studio 3.4.2 version` and created a new project with type `Empty Activity`. After I successfully configure the `Add-To-App` in my host application, I plan to call the Flutter module in my host application, but I get an error when I want to call the Flutter screen in the `getLifecycle()` code. The error says `Wrong 2nd argument type. Found "androidx.lifecycle.Lifecycle", required "Lifecycle"`. How will I call the `getLifecycle()` function but not part of AndroidX?

The full source code is:
```
Button btnCall =  findViewById(R.id.btnFlutter);
        btnCall.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                View flutterView = Flutter.createView(MainActivity.this, getLifecycle(), "router1");
                FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(600, 800);
                layoutParams.leftMargin = 100;
                layoutParams.topMargin = 200;
                addContentView(flutterView, layoutParams);
            }
        });
```

**Comment by gptshubham595** [comment]
Just go to new module and from refractor option migrate it to Androidx

**Comment by BondarenkoStas** [comment]
@rrifafauzikomara is the issue still relevant?

**Comment by po1arbear** [comment]
the same problem, anyone help?

**Comment by BondarenkoStas** [comment]
@po1arbear Please provide your flutter doctor -v output and the log you are receiving.

**Comment by po1arbear** [comment]
@BondarenkoStas 
Caused by Androidx，I've solved the problem. Below is the solution:

https://juejin.im/post/5d4002b4f265da03925a2165
