### ISSUE TITLE
Am trying to use SVG as decoration background, how do I do it?

### ISSUE THREAD

**Issue by michaelodafe** [flutter/flutter#37754]
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          decoration: BoxDecoration(
            image: DecorationImage(
                image: AssetImage('assets/Subtle-Prism.svg'), fit: BoxFit.fill),
          ),
        ),
      ),
    );
  }
}

**Please what do I change or add in order to achieve this?**

**Comment by mannprerak2** [comment]
Flutter has no inbuilt support for SVG as of now..
But **you can try this package** -> https://pub.dev/packages/flutter_svg

```dart
final Widget svg = new SvgPicture.asset(
  "assets/image.svg",
);
```
However, I'd recommend not using an SVG, instead convert your image to a png format

**Comment by michaelodafe** [comment]
Thank you...I'd apply that.

**Comment by davidgaspardev** [comment]
@mannprerak2 Why not use svg ? Performance ?

**Comment by mannprerak2** [comment]
@davidgaspardev see #1831

**Comment by Adnantjexx** [comment]
but SvgPicture not working inside DecorationImage

**Comment by fabioselau077** [comment]
> but SvgPicture not working inside DecorationImage

same problem, has resolved?

**Comment by scheung38** [comment]
> Flutter has no inbuilt support for SVG as of now..
> But **you can try this package** -> https://pub.dev/packages/flutter_svg
> 
> ```dart
> final Widget svg = new SvgPicture.asset(
>   "assets/image.svg",
> );
> ```
> 
> However, I'd recommend not using an SVG, instead convert your image to a png format

@mannprerak2 SVG scales without pixelating correct?

**Comment by kingmaster772** [comment]
> but SvgPicture not working inside DecorationImage

You may use stacking Widget
- Stack
  - SVG
  - AnotherWidget

**Comment by fluttercorner** [comment]
[How to set Background Image to Scaffold in Flutter](https://fluttercorner.com/how-to-set-background-image-to-scaffold-in-flutte/)

**Comment by Umar-Khan-Yousafzai** [comment]
I am amazed that Flutter is such a big platform now and it still doesn't support so many basic things
