### ISSUE TITLE
App crashes when entering space in TextFormField in Vivo V7+ (Android) device

### ISSUE THREAD

**Issue by rakeshparveen5** [flutter/flutter#37758]
## Steps to Reproduce

1. Enter space in TextFormField and app crashes in vivo v7+ android device

My flutter application is working fine on every device except the vivo v7+ (Android device). As space is entered in any of the TextFormField in any screen of my application, the app crashes for this vivo device. The app is working fine on other devices.

## Logs

```
```

flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/rakesh/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /home/rakesh/My_Data/softwares/Ubuntu_setups/AndroidStudioLatest/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /home/rakesh/My_Data/softwares/Ubuntu_setups/AndroidStudioLatest/android-sdk
    • ANDROID_SDK_ROOT = /home/rakesh/My_Data/softwares/Ubuntu_setups/AndroidStudioLatest/android-sdk
    • Java binary at: /home/rakesh/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /home/rakesh/My_Data/softwares/Ubuntu_setups/AndroidStudioLatest/android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Android Studio (version 3.4)
    • Android Studio at /home/rakesh/android-studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.36.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

```
```

**Comment by HansMuller** [comment]
It would help if you could provide a small self-contained app that demonstrates the problem (understood that it only occurs on "vivo v7+ android device").

**Comment by rakeshparveen5** [comment]
@HansMuller Thanks for your reply. I will share the app code for sure. I had just created a sample project that contains TextFormField as child. I had shared this build with my testers. They will test this app on vivo v7 device and then will share the code here once it crashes.

**Comment by HansMuller** [comment]
OK, sounds good.

**Comment by TahaTesser** [comment]
Hi @rakeshparveen5 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
