### ISSUE TITLE
TextFormField is auto selecting text on first tap, causes overwriting unless tap twice

### ISSUE THREAD

**Issue by jdeltoft** [flutter/flutter#37769]
This issue only happens on Android.  I've tested on iOS and don't see the issue but when I test on Android ( Moto Z2 and Galaxy S9 ) I get an odd behavior with TextFormField.  I have autofocus set to false, and the text of the controller preset to a server URL such as:

https://api.mydomainhere.com/

 so on the first tap of the textformfield I get my keyboard to come up BUT I get the "https" to be selected (shows underlined of just that text).  So even if my cursor is somewhere else when I start typing I overwrite the https.  That's my main complaint.

I've tried turning off spell check, suggestions, etc.  I'm using gboard on both phones I believe.  Nothing seems to help.  I have confirmed that validation doesn't seem to be causing this either. I looked at other options of textformfield like disabling interactive selection but then I can't even place the cursor anywhere.

Here's a picture on first click:

![image](https://user-images.githubusercontent.com/4506303/62622160-52ef1d00-b8e3-11e9-9a9b-e2a7fc3bcbfd.png)

Here's my code for the text form field:

```
child: TextFormField(
                    autofocus: false,
                    controller: _serverUrlController,
                    decoration: InputDecoration.collapsed(hintText: "Server URL"),
                    autocorrect: false,
                    textAlign: TextAlign.center,
                    autovalidate: false,
                    obscureText: false,
                    style: Theme.of(context)
                        .textTheme
                        .body1
                        .copyWith(fontSize: 18),
                    validator: (value) {
                      if (isValidUrl(value) == false) {
                        return 'Invalid URL';
                      }
                    },
                  ),
```

**Comment by jdeltoft** [comment]
I upgraded to the latest 1.7 flutter and still fails.

**Comment by TahaTesser** [comment]
Hi @jdeltoft 

Please try code sample, there is no auto selecting on first tap

### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final myController = TextEditingController();

  @override
  void initState() {
    super.initState();
    myController.text = 'https://flutter.dev/';
    myController.addListener(_printLatestValue);
  }

  @override
  void dispose() {
    // Clean up the controller when the widget is removed from the widget tree.
    // This also removes the _printLatestValue listener.
    myController.dispose();
    super.dispose();
  }

  _printLatestValue() {
    print("Second text field: ${myController.text}");
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Material App',
        home: Scaffold(
          appBar: AppBar(
            title: Text('Material App Bar'),
          ),
          body: Center(
            child: TextFormField(
              autofocus: false,
              decoration: InputDecoration.collapsed(hintText: "Server URL"),
              autocorrect: false,
              controller: myController,
              textAlign: TextAlign.center,
              autovalidate: false,
              obscureText: false,
            ),
          ),
        ));
  }
}

```

Are you still experiencing with issue?
Thank you

**Comment by jdeltoft** [comment]
Ok, I just tested with my latest app (hadn't thought about this issue much since I opened it) and on both Moto Z2 and Galaxy S9 this doesn't happen any more.  Thanks for the refresh, and the hard work on flutter!  I'm closing now.
