### ISSUE TITLE
Getting error for firebase_crashlytics:

### ISSUE THREAD

**Issue by MansiShah12** [flutter/flutter#37765]
```
*/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-0
.1.0+2/lib/src/firebase_crashlytics.dart:36:43: Error: Too few positional
arguments: 1 required, 0 given.
[        ]             : details.informationCollector());
[        ]                                           ^
[        ]
*/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-0
.1.0+2/lib/src/firebase_crashlytics.dart:35:13: Error: This expression has type
'void' and can't be used.
[        ]             ? null
[        ]             ^
[+8196 ms] Compiler terminated unexpectedly.
```

**Comment by omhoumz** [comment]
same problem

**Comment by omhoumz** [comment]
@MansiShah12 I tried to use the 0.1.0 version and it worked:
```yaml
firebase_crashlytics: 0.1.0
```

**Comment by thedejifab** [comment]
I experienced same this morning, any chance of getting a resolution soon?

**Comment by NaiveMonkey** [comment]
I have same issue. Although I try to downgrade my firebase_crashlytics, error message doesn't disappear. 😱 
Interesting things is that I remove all codes relating to crashlytics excluding pubspec.yaml, error message is gone.
But when I write down **import 'package:firebase_crashlytics/firebase_crashlytics.dart';** at some dart file, error message appear again.

**Comment by creativecreatorormaybenot** [comment]
I am sorry for introducing this issue. Can any of you @thedejifab @omhoumz @MansiShah12 further elaborate on exactly when you are receiving this error?

The [`InformationCollector` typedef](https://api.flutter.dev/flutter/foundation/InformationCollector.html) has no positional arguments, so I am not sure where they are coming from. What version of Flutter are you using?

**Comment by creativecreatorormaybenot** [comment]
I found out that this was changed with #30983. 

## Upgrade Flutter (>=1.6.0)

It turns out that you are using an **outdated** version of Flutter, i.e. `stable` is way ahead of where you are.  
Run `flutter upgrade` or upgrade to a version that is greater than or equal to `v1.6.0`.

---

@collinjackson Is this fine or should I change something? `stable` is already at `v.1.7.8+hotfix.4`, but should the plugin support older versions?

**Comment by NaiveMonkey** [comment]
@creativecreatorormaybenot 
I used 1.7.3 version. 
Now, I upgrade 1.7.3 to 1.7.8 hotfix version and then error message is gone!!! 😄 
Thank you!

**Comment by BondarenkoStas** [comment]
@MansiShah12 Reading the comments above, I think it's safe to close the issue. If you still encounter it or have new input, please comment and I will re-open it right away.
