### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by azizoy** [flutter/flutter#37768]
i try add flutter in my existing apps but when i run my XCode this is happen:

<img width="735" alt="Jepretan Layar 2019-08-07 pukul 19 10 46" src="https://user-images.githubusercontent.com/34239570/62621825-17863a00-b947-11e9-8a21-abe59d658511.png">

**Flutter Version:**

`Flutter 1.8.4-pre.127 • channel master • https://github.com/flutter/flutter.git
Framework • revision c08a3c7a0a (7 hours ago) • 2019-08-06 22:38:09 -0700
Engine • revision 4291770479
Tools • Dart 2.5.0 (build 2.5.0-dev.1.0 574c4a51c6)`

Any idea to fix this issue?

**Comment by ahai0831** [comment]
and i  also have this problem...

**Comment by zhangtong217** [comment]
the same problem

**Comment by BenBtg** [comment]
Same problem here, using later Flutter on an old project. Any help?

**Comment by VB10** [comment]
Hello , It's remove app.framework and flutter framework in project/ios/flutter folder and try flutter clean and flutter run (for ios devices).
I solved in this way. @BenBtg  @zhangtong217
