### ISSUE TITLE
The textfield will showToolBar uncorrectly.

### ISSUE THREAD

**Issue by shaqima123** [flutter/flutter#37767]
## Steps to Reproduce

1. first there is a textfield and a normal button, when I tap the button ,I can change the text in the textfield by using TextEditingController. （you also can don't use the button to control the text, just a button doest do anything is also ok.）The key here is to use TextEditingController to change the text, like this: 

```controller.text = "1111";```

2. then after the text in textfield changed, you can tap on the textfield and focus on it.

3. at last ,you tap on the button ,any widget with a tap gesture, the toolbar of the textfield will appear, but I didn't touched on the textfield, I want to trigger the things of the button , but it doesn't response.

## Logs

```
```

```
```

```
```

**Comment by LongCatIsLooong** [comment]
Per your description, It sounds like [this bug](https://github.com/flutter/flutter/issues/37032). It should have been fixed on master, could you please try switching to master and see if it's still reproducible?

**Comment by shaqima123** [comment]
ok I switched to master and find this problem fixed.thank you!
