### ISSUE TITLE
[web]: Webdev --launch-in-chrome to launch Chrome instance with logged in user

### ISSUE THREAD

**Issue by TheRealWelshCJ** [flutter/flutter#37774]
## Use case

When using the developer console in Chrome you can save several custom devices for testing layouts against.  When running webdev (as below), it launches a Chrome instance with no logged in user, meaning that custom devices are not accessible (and are lost on the the non-logged in chrome if you restart it)

```
flutter pub global run webdev serve --launch-in-chrome --auto refresh
```

## Proposal

Have --launch-in-chrome launch an instance of chrome with the normal chrome user (if any).

**Comment by jonahwilliams** [comment]
Flutter does not use or support the webdev command line tool, please file an issue at https://github.com/dart-lang/webdev
