### ISSUE TITLE
Firebase Phone Auth Token mismatch 

### ISSUE THREAD

**Issue by nizo-m** [flutter/flutter#37770]
Hi,

I'm trying to use phone Authentication and it's working as expected on Android, but on iOS I always get `Token mismatch` and don't receive a code.

other Firebase services like cloud firestore and email Auth are working fine on iOS.

I made sure of the following:
- APN key is added in Firebase
- Google Services file is updated 
- Background Modes and Push Notification capabilities are on

Update:

i get these messages in log
`Userinfo {
    "com.google.firebase.auth" =     {
        warning = "This fake notification should be forwarded to Firebase Auth.";
    };
}
UserDate : {
    "com.google.firebase.auth" =     {
        warning = "This fake notification should be forwarded to Firebase Auth.";
    };
}
UserDate Json : {
  "com.google.firebase.auth" : {
    "warning" : "This fake notification should be forwarded to Firebase Auth."
  }
}
flutter: 

TRUE
flutter: Call Back {
  "com.google.firebase.auth" : {
    "warning" : "This fake notification should be forwarded to Firebase Auth."
  }
}`

Here is my flutter doctor
```

[✓] Flutter (Channel unknown, v1.5.4-hotfix.2, on Mac OS X 10.13.6 17G7024, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/nizarmalaika/Documents/Dev/flutter
    • Framework revision 7a4c33425d (3 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nizarmalaika/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

**Comment by nizo-m** [comment]
Changing the Firebase Auth version from 0.14.0 to

  firebase_auth:
    git:
      url: https://github.com/collinjackson/plugins.git
      ref: 441417c2fed0ff26bf84a49ab2c5ffd2aa5487de
      path: packages/firebase_auth

fixed my issue. see https://github.com/flutter/flutter/issues/35267 for more details

**Comment by khachuong** [comment]
@nizo-m Thank you very much, you saved my day

**Comment by nrooban** [comment]
simply upgrade the firebase_auth version to latest
firebase_auth: ^0.15.3+1

**Comment by KodyDevSAGAR** [comment]
same error on firebase_auth: ^0.15.3+1
