### ISSUE TITLE
[google_maps_flutter] When Android key is restricted, api functionality doesn't work 

### ISSUE THREAD

**Issue by mikron123** [flutter/flutter#37785]
The Android Key used in the app works when not restricted.
However, when I restrict to specific app package name + Sha-1 key in the Google Cloud console (yes, I provided all 3 Sha-1 - debug, prod, and google signing prod) none of the environments work, and I get a message the access is not authorized.

Therefore, the keys cannot be restricted as of now.
Am I missing something, or is it a flutter package issue?

**Comment by TahaTesser** [comment]
Hi @mikron123 
Testing restricted API key for Android seems to be working on 
```
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (2 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```
Are you still experiencing this issue?  If yes, please a create new issue and provide necessary details
Thank you
