### ISSUE TITLE
[flutter_web]Input candidates do not follow the TextField

### ISSUE THREAD

**Issue by luojieerr** [flutter/flutter#37788]
Input candidates do not follow the TextField when language is Chinese
![01](https://user-images.githubusercontent.com/11175495/62638704-92b01600-b970-11e9-9808-7939bb50899d.png)

**Comment by BondarenkoStas** [comment]
@luojieerr Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by nturgut** [comment]
This looks like an issue from the previous version of text editing. We implemented a new version which positions the input element on top of editable text widgets which only works fully on the unforked flow. 

You can follow [this link](https://flutter.dev/docs/get-started/web). Can you please update the issue if you are still having trouble?

**Comment by luojieerr** [comment]
It works fine in the latest version！
