### ISSUE TITLE
[Web] Getting Mouse Events To Work 

### ISSUE THREAD

**Issue by hashweather** [flutter/flutter#37797]
Is there a way to make hovering and mouse event listeners work on Flutter Web?

I wish to change the color of a button when it is moused-over

**Comment by yjbanov** [comment]
Have you tried https://api.flutter.dev/flutter/widgets/Listener-class.html `onPointerHover`?

**Comment by yjbanov** [comment]
But heads up, this API is changing to `MouseRegion`. This should land soon.
