### ISSUE TITLE
[web] Bug/weird behaviour TextFormField in flutter_web packaged as Chrome extension

### ISSUE THREAD

**Issue by ja2375** [flutter/flutter#37800]
TextFormField widget behaves weirdly in flutter_web app packaged as Chrome extension that opens in a popup:

## Steps to reproduce

1. Create a flutter_web project
2. Add a TextFormField widget
3. webdev build
4. Copy all build files inside another folder (intended to be our Chrome extension package)
5. Edit the index.html file to add this code to the `<head>` tag:
```
  <style type="text/css">
    html, body{
      width:350px;
      height:650px;
    }
  </style>
```
This is a temporary fix i found for the popup not to get resized by javascript (If you don't add this, when you open the popup it will be 0px height 0px width).
6. Add a manifest.json file to the folder with these contents:
```
{
  "name": "Flutter_web test",
  "version": "1.0",
  "description": "TextFormField bug",
  "browser_action": {
    "default_popup": "index.html"
  },
  "content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'",
  "manifest_version": 2
}
```
7. Open Chrome and navigate to chrome://extensions
8. Click _Load unpacked_ and locate the folder we just created. The extension should be installed.
9. Open the new extension popup and try to type something inside the TextFormField

As you see, the TextFormField is behaving weirdly. It won't allow to enter any text unless you click and hold it until the bubble animation fills the entire field. At this point you can release the mouse button and the TextFormField will let you enter text normally.

**UPDATE:**
This seems to happen only sometimes but randomly.

**UPDATE 2:**
This exact same behavior happens on a Scaffold AppBar back button. Which makes it really hard to click.

**Comment by yjbanov** [comment]
We will also need this feature for embedding Flutter web in existing apps.

**Comment by ja2375** [comment]
This seems to be fixed now with the combination of:
- Chrome 76.0.3809.100 (official build)
- Flutter 1.9.0 (dev channel)
- flutter_web (from official git repo)
- build_runner 1.6.6 (from pub)
- build_web_compilers 2.2.3 (from pub)
