### ISSUE TITLE
[connectivity] iOS 13, add location authorization request to enable getWifiName and getWifiBSSID to return valid values

### ISSUE THREAD

**Issue by danwulff** [flutter/flutter#37804]
## Problem

With the changes to iOS 13, [CNCopyCurrentNetworkInfo](https://developer.apple.com/documentation/systemconfiguration/1614126-cncopycurrentnetworkinfo) will return invalid SSID and BSSID values. This leads to the connectivity plugin returning invalid values for the `getWifiName()` and `getWifiBSSID()` methods.

## Use case

Apps that require valid SSID and BSSID values to be returned within iOS 13.

## Proposal

Update the connectivity plugin iOS code to request one of the authorizations required to return valid SSID and BSSID values with: `requestWhenInUseAuthorization()` or `requestAlwaysAuthorization()`

## More Info

The announcement email from apple:
![image](https://user-images.githubusercontent.com/17821843/62651560-18e74080-b90e-11e9-96e9-ca345442ff68.png)

The documentation for CNCopyCurrentNetworkInfo:https://developer.apple.com/documentation/systemconfiguration/1614126-cncopycurrentnetworkinfo.

Info for requesting the "When In Use" Location authorization: https://developer.apple.com/documentation/corelocation/choosing_the_authorization_level_for_location_services/requesting_when-in-use_authorization?language=objc

Info for requesting the "Always" Location authorization: https://developer.apple.com/documentation/corelocation/choosing_the_authorization_level_for_location_services/requesting_always_authorization

**Comment by cyanglaz** [comment]
This should be easy to implement. I would be happy to review the PR if anyone wants to give it a try!

**Comment by cyanglaz** [comment]
Moving back the milestone a bit since we need to discuss the approach of using location permissions.

**Comment by bawantha** [comment]
Similar situation happend to Android 9
SSID : null
BSSID: 02:00:00:00:00:00

**Comment by ali-coder1** [comment]
> Similar situation happens to Android 9
> SSID : null
> BSSID: 02:00:00:00:00:00

Yeah I have the same issue, so I think it is settings issue

anyone has idea to fix that Null output for SSID

**Comment by cyanglaz** [comment]
Added methods to request location permission in connectivity plugin https://github.com/flutter/plugins/pull/1999. Also added more information on README to explain the iOS 13 breakage. 
I'm going to close this issue.

For the similar issue happening on Android 9 for some of you guys. It is probably not related to the iOS13 breakage. Please open a different ticket to explain the issue you are facing and tag me there.
