### ISSUE TITLE
AppBar too close from statusBar (Android) 

### ISSUE THREAD

**Issue by yvrez** [flutter/flutter#37803]
## Steps to Reproduce

When creating an application with status bar hidden on android (SystemChrome.setEnabledSystemUIOverlays([]) ) the status bar reappears when the keyboard shows up (which is normal). 

Seems that the Appbar widget doesn't take into account the newly added status bar height and doesn't add the necessary padding. Visually this result in the Appbar content (title, back button, leadings, ...) being too close from the status bar which is not pretty at all.

https://www.dropbox.com/s/376vrfhjavlx3nw/Capture%20d%27%C3%A9cran%202019-08-07%2021.21.01.png?dl=0

flutter doctor -v output : 

[✓] Flutter (Channel dev, v1.8.4, on Mac OS X 10.14.4 18E226, locale fr-BE)
    • Flutter version 1.8.4 at /Users/yvrez/Desktop/DevTools/flutter
    • Framework revision 954714c967 (5 days ago), 2019-08-02 10:10:39 -0700
    • Engine revision 26368225b5
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 bd049f5b53)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/yvrez/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/yvrez/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.0.beta.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

**Comment by HansMuller** [comment]
Thanks for the report! If you have a small self-contained app that demonstrates the problem, that would help.

**Comment by TahaTesser** [comment]
Hi @yvrez 
Are you still experiencing this issue with latest stable Flutter?
If yes,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
