### ISSUE TITLE
iOS embedding should not assume resource context presence means app is in foreground

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#37813]
The image decoding logic on iOS currently checks for a resource context to determine whether the app is in the foreground, but this is not really safe - the resource context survives being backgrounded, and must do so to avoid dropping live references in Dart land to images/fonts.

https://github.com/flutter/engine/blob/master/lib/ui/painting/multi_frame_codec.cc#L118 should be updated to make sure the work either finishes before going to background or can't happen when in the background. This can lead to crashes when decoding an image and going to the background, which is more likely to happen with multiframe images.

/cc @chinmaygarde @amirh @ponycui

**Comment by MrLittleStrong** [comment]
Same issue, any progress now?

**Comment by dnfield** [comment]
@gaaclarke has been working on this more recently.  There's a PR with some discussion at https://github.com/flutter/engine/pull/13454

**Comment by dnfield** [comment]
This is fixed by https://github.com/flutter/engine/pull/13908 and landed in the framework as of 5fb790e
