### ISSUE TITLE
Optimize pre-warmed first frame on iOS

### ISSUE THREAD

**Issue by xster** [flutter/flutter#37817]
In add-to-app flows, an engine can be prewarmed with the Flutter Dart program before the user attaches UI. The UI attach on a prewarmed engine is critical user visible latency. 

On an iPod touch, that time is currently 200ms, and over 1/4 of it is spent creating the SkSL Compiler and on Compile::convertProgram even though conceptually, that would could be done on ShaderWarmUp.execute before it. 

@liyuqian proposes that we can remove that time by moving the ShaderWarmUp to the GPU thread. Then the shader binary can be used directly when attaching UI rather than writing the shader SL program to persistent cache on the IO thread and then re-doing half of the work on the GPU thread later on attach.

**Comment by xster** [comment]
To summarize our second discussion offline, we said that ideally, the embedding could provide hints for whether a frame is meant for prewarming or for drawing (such as a layer tree coming back but no surface existing yet). 

Instead of dropping that layer tree on the floor, we should instead avoid doing the hand-picked shader warm-up on the IO thread and try to draw that layer tree for real on the GPU thread. Yuqian mentioned that it's possible to draw it into a non-memory backed context so that it only has the side effect of compiling the shader programs without consuming memory during this warm-up.

**Comment by liyuqian** [comment]
Remove myself from the assignment as I'm not actively working on this. Will reassign myself once I get some time to work on it.

**Comment by jmagman** [comment]
Closing this post-impeller.
