### ISSUE TITLE
InkWell and FlatButton do not ripple when inside a container with opaque background

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#3782]
## Steps to Reproduce

I have only tested this against an android emulator.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue
      ),
      home: new FlutterDemo()
    )
  );
}

class FlutterDemo extends StatelessWidget {

  Widget buttons(BoxDecoration decoration) {
    return new Container(
      decoration: decoration,
      child: new Row(
        children: [
          new FlatButton(
            child: new Text("FLAT BUTTON"),
            onPressed: () => null
          ),
          new InkWell(
            child: new Text("WELL"),
            onTap: () => null
          ),
          new RaisedButton(
            child: new Text("RAISED BUTTON"),
            onPressed: () => null
          )
        ]
      )
    );
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Flutter Demo')
      ),
      body: new Column(
        children: [
          // INK DOES NOT SHOW
          buttons(new BoxDecoration(backgroundColor: Colors.yellow[100])),
          buttons(null),
          // INK DOES NOT SHOW
          buttons(new BoxDecoration(gradient: new LinearGradient(colors: [Colors.grey[100], Colors.grey[500]]))),
          buttons(new BoxDecoration(gradient: new LinearGradient(colors: [Colors.black26, Colors.grey[500]]))),
          buttons(new BoxDecoration(backgroundColor: Colors.white10))
        ]
      )
    );
  }
}

```

Note that the ripple does not appear on the FlatButton and InkWell for first and third rows (the ones that use opaque backgrounds). The ripple works fine on the raised button for all rows.
## Flutter Doctor

```
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /usr/local/google/home/drewwarren/flutter
    • Framework revision 5460e94488 (4 days ago), engine revision 76d5cf230a

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/users/drewwarren/aswb-sdk
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-119990345-117822431)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```
## Logs and Crash Reports

No logs. Requires visual inspection.

**Comment by Hixie** [comment]
This is actually as expected, though we should update the docs to make it clearer.

What's going on is that the Material spec says that the splashes are actually ink _on the Material_. So when we splash, what we do is we literally have the Material widget do the splash. If you have something on top of the Material, we splash under it, and you can't see it.

I have wanted to add a "MaterialImage" widget which conceptually prints its image into the Material as well, so that then the splashes would be over the image. We could have a MaterialDecoration which does something similar for a Decoration. Or we could have Material itself take a decoration. Right now it takes a color, but we could extend that to taking a whole decoration. It's not clear whether it's really material-spec-compatible to have a material with a gradient, though, so I'm not sure whether we should do that.


On the short run, if you just need a workaround, you can put a Material on top of the container, with the material set to use the "transparency" type, and then put the ink well inside that.

**Comment by drewwarren** [comment]
Thanks for the workaround. Surprising behavior.

**Comment by Hixie** [comment]
We should also have a widget that prints a Decoration on a Material, since otherwise there's no good way to color a subpart of a material. (Container has the same problem Image has of blocking ink splashes.)

**Comment by eseidelGoogle** [comment]
@FaisalAbid just hit this as well attempting to create a custom button but wanting to give that button a background color.

**Comment by Hixie** [comment]
The MaterialImage widget I mention above also sometimes gets called PrintedInk or InkPrint or InkDecoration or some such.

**Comment by eseidelGoogle** [comment]
Just noting that @lukef hit this as well.  This is a pretty common confusion.

**Comment by branflake2267** [comment]
Another case of this. Feels like the leaf widgets should be stacking and painting on top. Whatever the case ends up being to properly configure the ink splashing on a tap, it's hard to configure. 

![screen shot 2017-06-10 at 9 57 15 pm](https://user-images.githubusercontent.com/1326504/27008521-64517bec-4e28-11e7-92d9-b9e7ae19755c.png)

```
import 'package:flutter/material.dart';

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => new _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    Widget buttonSection = new Container(
      child: new Row(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: [
          buildButtonColumn(Icons.account_circle, "Create Account", _createAccount ),
          buildButtonColumn(Icons.person, "Sign In", _signIn ),
        ],
      ),
    );

    var _container = new Container(
      margin: const EdgeInsets.symmetric(horizontal: 10.0, vertical: 5.0),
      padding: const EdgeInsets.symmetric(horizontal: 15.0, vertical: 10.0),
      decoration: new BoxDecoration(
        color: Colors.grey.shade200.withOpacity(.9),
        borderRadius: new BorderRadius.circular(5.0),
      ),
      child: buttonSection,
    );

    return new Scaffold(
      appBar: new AppBar(
        title: new Text("Wrightway Economy"),
      ),
      body: _container,
    );
  }

  Widget buildButtonColumn(IconData icon, String label, Function onPress) {
    Color color = Theme
        .of(context)
        .primaryColor;

    var column = new Column(
      mainAxisSize: MainAxisSize.min,
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        new Icon(icon, color: color),
        new Container(
          margin: const EdgeInsets.only(top: 8.0),
          child: new Text(
            label,
            style: new TextStyle(
              fontSize: 12.0,
              fontWeight: FontWeight.w400,
              color: color,
            ),
          ),
        ),
      ],
    );

    var inkWell = new InkWell(
      child: column,
      onTap: onPress,
    );

    return inkWell;
  }

  _signIn() {
    print("sign in");
  }

  _createAccount() {
    print("create account");
  }

}
```

**Comment by passsy** [comment]
I hit this as well and couldn't find a way to show a card ripple effect on a card which has a full sized image.

This example demonstrates that the ripple effect is always below the icon even when `InkWell` and the `Material` are placed on top of the `Icon` in the `Stack`

```dart
return new Card(
  color: Colors.white,
  child: new Stack(
    children: <Widget>[
      new Positioned.fill(
        child: new Icon(Icons.map, size: 50.0)
      ),
      new Positioned.fill(
        top: null,
        child: new Container(
          padding: new EdgeInsets.all(4.0),
          decoration: new BoxDecoration(
            color: Colors.black26
          ),
          child: new Text(
            item.name,
            style: theme.textTheme.subhead.copyWith(
              color: Colors.white),
          )
        )
      ),
      new Positioned.fill(
        child: new InkWell(
          highlightColor: Colors.red,
          splashColor: Colors.redAccent,
          onTap: () {
            print("clicked ${item.name}");
          },
          child: new Material(color: Colors.black26)
        )
      )
    ]
  )
);
```

**Comment by Rishab-1065** [comment]
I don't see any ripple effect in the drawer if i provide the color to the container wrapped inside the drawer. Please tell if this the desired behaviour. @eseidelGoogle

**Comment by bramvbilsen** [comment]
@Rishab-1065 provide the color to the Material and don't use the container's color.

**Comment by p30arena** [comment]
https://stackoverflow.com/questions/47708063/long-press-inkresponse-not-working-when-using-container-with-decoration/47721295?noredirect=1#comment82616379_47721295

**Comment by alanrussian** [comment]
Mulligan just ran into this. It took me a ~ 20 min to 30 min to figure out why my button wasn't showing the highlight effect.

**Comment by bramzz** [comment]
Here's another example of a circular gradient button with a ripple effect by overlaying a container with a transparant Material

```
Container(
        height: 60,
        width: 60,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            colors: [
              Color.fromRGBO(255, 111, 0, 1),
              Color.fromRGBO(255, 190, 58, 1)
            ],
            begin: Alignment(-1, -2),
            end: Alignment(1, 2),
          ),
          borderRadius: BorderRadius.all(Radius.circular(50)),
          boxShadow: [
            BoxShadow(
              // color: Color.fromARGB(95, 48, 48, 48),
              blurRadius: 12.0, // has the effect of softening the shadow
              spreadRadius: .5, // has the effect of extending the shadow
              offset: Offset(
                0, // horizontal, move right 10
                3, // vertical, move down 10
              ),
            )
          ],
        ),
        child: Material(
          color: Colors.transparent,
          child: InkWell(
            splashColor: Color.fromRGBO(255, 190, 58, 1),
            borderRadius: BorderRadius.all(Radius.circular(50)),
              onTap: () {},
              child: Icon(
                Icons.add,
                color: Colors.white,
              )),
        ),
      ),
```

**Comment by ingsoto83** [comment]
> I hit this as well and couldn't find a way to show a card ripple effect on a card which has a full sized image.
> 
> This example demonstrates that the ripple effect is always below the icon even when `InkWell` and the `Material` are placed on top of the `Icon` in the `Stack`
> 
> ```dart
> return new Card(
>   color: Colors.white,
>   child: new Stack(
>     children: <Widget>[
>       new Positioned.fill(
>         child: new Icon(Icons.map, size: 50.0)
>       ),
>       new Positioned.fill(
>         top: null,
>         child: new Container(
>           padding: new EdgeInsets.all(4.0),
>           decoration: new BoxDecoration(
>             color: Colors.black26
>           ),
>           child: new Text(
>             item.name,
>             style: theme.textTheme.subhead.copyWith(
>               color: Colors.white),
>           )
>         )
>       ),
>       new Positioned.fill(
>         child: new InkWell(
>           highlightColor: Colors.red,
>           splashColor: Colors.redAccent,
>           onTap: () {
>             print("clicked ${item.name}");
>           },
>           child: new Material(color: Colors.black26)
>         )
>       )
>     ]
>   )
> );
> ```
> 
> ## Update
> The `InkWell` has to be the child of an overlaying transparent `Material` to show the ripple effect above.
> 
> ```dart
> new Positioned.fill(
>   child: new Material(
>     color: Colors.transparent,
>     child: new InkWell(
>       onTap: () {
>         print("clicked ${item.name}");
>       },
>     )
>   )
> ),
> ```

This works for me!

**Comment by liudonghua123** [comment]
I have the same issue, Thanks for 
```
Material(
    color: Colors.transparent,
    child: InkWell()
)
```

**Comment by R12-cookies** [comment]
Faced the same issue while trying to make an animated play button inside a stack, wrapping it in a material widget solved the issue tho, thank you @Hixie
