### ISSUE TITLE
flutter packages get failed (255) in android studio

### ISSUE THREAD

**Issue by zhujinsheng** [flutter/flutter#37829]
detail:![image](https://user-images.githubusercontent.com/16300475/62668548-dd587f00-b9be-11e9-95c4-6146881493f2.png)

**Comment by kangwang1988** [comment]
@zhujinsheng 
Try run
```dart
flutter packages get --verbose
```
and paste the full log here.
It seems to be resulted from batch recursion call which cause the stack limit overflow, however, the log you paste seems not enough to diagnose.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
