### ISSUE TITLE
[Plugins] Splitting into separate repos 

### ISSUE THREAD

**Issue by raveesh-me** [flutter/flutter#37835]
## Use case
Reporting searching and tracking bugs on plugins is really hard if all of it is in the same flutter/flutter repo.

## Proposal
Please break flutter/plugins into flutter/plugin_xyz repos for each plugin, with their own issue tracking systems.

In gitlab, we could just have a separate flutter/plugins group where we could better organise repos.

While the current system is optimised for a smaller number of issues and a yet smaller number of contributors, it is not scaling well especially on the pace of official plugins development, and keeping track of plugin related issues.

Even as we develop, it is hard to search the current issues for the specific issue we are facing.

**Comment by iampawan** [comment]
@Hixie @chinmaygarde @sethladd @eseidel I guess this is one of the most needed change. We struggle a lot because of this.

**Comment by basselch** [comment]
Especially that now there are around 40+ plugins whose issues are being reported in the main Flutter repository (according to the labels). It makes things a lot harder to maintain.

**Comment by Sun3** [comment]
It's making finding and tracking specific plugin bugs/feature request harder. I would be a great change to improve the plugin's tracking.

**Comment by Hixie** [comment]
We intentionally did the opposite to reduce the confusion around our repos. To find bugs for a particular plugin, use the labels to filter for bugs relating to that plugin.

**Comment by erf** [comment]
I would also like to give my vote for splitting up the plugins into separate repos, the main reason being i would like to examine every commit made to a spesific plugin, e.g the `in_app_purchase` plugin. As of now you would have to search for commit messages and filter on commits in `flutter/plugins`, this is not a good solution, with a difficult ui and easy to miss certain commits. There is also not possible to watch and get notifications on a spesific plugin change/release. Also handling issues to a single plugin repo sounds alot simpler than having to deal with one massive repository with 5k+ issues and counting, i think. Please give this a second thought. Thanks! 😄
