### ISSUE TITLE
flutter 1.7.8 fix 4 cannot build aar

### ISSUE THREAD

**Issue by pouloghost** [flutter/flutter#37834]
after upgrade to flutter 1.7.8, flutter build don't support subcommand aar. How can I build aar?

$ flutter build -h
Flutter build commands.

Usage: flutter build <subcommand> [arguments]
-h, --help    Print this usage information.

Available subcommands:
  aot         Build an ahead-of-time compiled snapshot of your app's Dart code.
  apk         Build an Android APK file from your app.
  appbundle   Build an Android App Bundle file from your app.
  bundle      Build the Flutter assets directory from your app.
  ios         Build an iOS application bundle (Mac OS X host only).

Run "flutter help" to see global options.

**Comment by wjbd** [comment]
I had the same problem.

**Comment by jmagman** [comment]
This feature was very recently added and is only available on the master channel.  See https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels.
