### ISSUE TITLE
[Plugins] Semantic Versioning For Firebase Plugins

### ISSUE THREAD

**Issue by raveesh-me** [flutter/flutter#37837]
## Use case
Sometimes, the latest versions of one firebase plugin don't go well with the latest versions of other firebase plugins.

The cloud_firestore is on version `v0.12.9` while firebase_messaging plugin is at `v5.1.2`. There is no way to know if these will work together

## Proposal
Come up with a semantic versioning strategy for official plugins falling under the same group, so it is easy to understand which plugins will go together with each other and which will not

**Comment by collinjackson** [comment]
I think that https://github.com/FirebaseExtended/flutterfire/pull/39 might help with this issue. Previously, all the Flutterfire plugins had to have compatible Android dependencies, and with this change, you'll be able to mix and match dependencies without breaking the Android build.

**Comment by stuartmorgan** [comment]
These plugins have moved, so this would need to be filed in the Flutterfire repository if this is still an issue.
