### ISSUE TITLE
 Exception in thread "main" java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by Miftaudeen** [flutter/flutter#37846]

**Comment by BondarenkoStas** [comment]
@Miftaudeen Do you have any clues how to reproduce the issue? Ideally some self-contained app.
Please provide your ```flutter doctor -v``` output and full log if possible.

**Comment by BharatsDruv** [comment]
Add more description for better understand the issue.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by epsi95** [comment]
I have a similar issue, here is the result of `flutter doctor -v`, I am running Flutter behind a corporate firewall, and proxies are set.

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter_windows_v1.12.13+hotfix.8-stable\flutter
    • Framework revision 0b8abb4724 (7 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\298115\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by epsi95** [comment]
I have a similar issue, here is the result of flutter doctor -v, I am running Flutter behind a corporate firewall, and proxies are set.

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
• Flutter version 1.12.13+hotfix.8 at C:\src\flutter_windows_v1.12.13+hotfix.8-stable\flutter
• Framework revision 0b8abb4 (7 months ago), 2020-02-11 11:44:36 -0800
• Engine revision e1e6ced81d
• Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
• Android SDK at C:\Users\<my_staff_id>\AppData\Local\Android\sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.3
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
• All Android licenses accepted.

[√] Android Studio (version 3.5)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin version 43.0.1
• Dart plugin version 191.8593
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Proxy Configuration
• HTTP_PROXY is set
• NO_PROXY is localhost,127.0.0.1
• NO_PROXY contains 127.0.0.1
• NO_PROXY contains localhost

[√] Connected device (1 available)
• AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by berrylawchingman** [comment]
Nil:/Berry

**Comment by iapicca** [comment]
@epsi95 
your flutter version is super obsolte
run `flutter upgrade -f`
