### ISSUE TITLE
How to know if a user is scrolling up or down the page in flutter?

### ISSUE THREAD

**Issue by saurabhpetkar** [flutter/flutter#37849]
Hi, I am currently working on a flutter project.
I have made a page which has AnimatedContainer and ListView widgets. the page is a bit lengthy. All I want to do is, reduce the size of the Animated container whenever I scroll down the ListView and increase the size when scrolled up.
this is my code: 
```
Stack(
    children: <Widget>[
      AnimatedContainer(
        duration: Duration(milliseconds: 500),
        width: text_height,
        height: text_height,
      ),
      NotificationListener<ScrollNotification>(
        child: ListView(
          children: <Widget>[
          // containe huge/lengthy content.
          ],
        ),
        onNotification: (scrollNotification) {
             print('inside the onNotification');
              if (scrollNotification.metrics.axisDirection == AxisDirection.down) {
            print('scrolled down');
            //the setState function
          }
          else if (scrollNotification.metrics.axisDirection == AxisDirection.up) {
                print(
              'scrolled up'); 
              //setState function
           }        
        },
      )
    ],
  )
```

When I scroll my screen (on emmulator), I am not even getting the message 'inside the onNotification' in my console.
I dont know whats wrong.
this is the output of my flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.6.3, on Linux, locale en_IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by nightMue** [comment]
Hello, I created a project and put your code in as is and I get the message "inside the onNotification" and "scrolled down".  Possibly need to see more of the code to help you on this one.

**Comment by saurabhpetkar** [comment]
https://github.com/flutter/flutter/issues/37849#issuecomment-519682854

Are you getting only 'scrolled down' printed in your console? I tried it once again, its working partially.
I mean, if I scroll down, i am getting 'inside the onNotification' and 'scrolled down' printed, but when i scroll up, I am still getting 'scrolled down' printed. Why so?

**Comment by nightMue** [comment]
I don't get scroll up... the flow never reaches inside that else statement. I think the issue is because you are using the "metrics.axisDirection". I am not 100% sure but I think this is the how the scrolling will work not a variable that is updated on scroll such as switching from up to down. You might need to take a different approach such as saving a temp scroll point from the controller and on scroll update check if it is larger or smaller than that temp to know if your scrolling up or down.

**Comment by bubupro9x** [comment]
You try:
up: _scrollController.position.userScrollDirection == ScrollDirection.forward 
down: _scrollController.position.userScrollDirection == ScrollDirection.reverse

**Comment by BondarenkoStas** [comment]
@saurabhpetkar Please report did you find a solution?

**Comment by patelkrunal78** [comment]
Wrap your widget tree inside a SingleChildScrollView

body: SingleChildScrollView(
child: Stack(
children: <Widget>[
new Container(
decoration: BoxDecoration(
image: DecorationImage(...),
new Column(children: [
new Container(...),
new Container(...... ),
new Padding(
child: SizedBox(
child: RaisedButton(..),
),
....
...
); // Single child scroll view

Find At [Here](https://icetutor.com/question/how-to-scroll-page-in-flutter)

**Comment by saurabhpetkar** [comment]
> You try:
> up: _scrollController.position.userScrollDirection == ScrollDirection.forward
> down: _scrollController.position.userScrollDirection == ScrollDirection.reverse

It worked, ty.

**Comment by vanlooverenkoen** [comment]
For me I had to use scrollController.addListener() to set my new state. With the notificationlistener I got render errors when I called set state.

**Comment by bilal2-1** [comment]
> > You try:
> > up: _scrollController.position.userScrollDirection == ScrollDirection.forward
> > down: _scrollController.position.userScrollDirection == ScrollDirection.reverse
> 
> It worked, ty.

how to use it?

**Comment by unknownaloy** [comment]
> 
> 
> You try:
> up: _scrollController.position.userScrollDirection == ScrollDirection.forward
> down: _scrollController.position.userScrollDirection == ScrollDirection.reverse

Worked for me!

**Comment by seonar22** [comment]
@bilal2-1 , you can try with following example.

```
class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  int _counter = 0;

  final ScrollController _scrollController = ScrollController();

  @override
  Widget build(BuildContext context) {
    final title = 'Grid List';
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),

      body: NotificationListener<ScrollNotification>(
        onNotification: (scrollNotification) {
          print('inside the onNotification');
          if (_scrollController.position.userScrollDirection ==
              ScrollDirection.reverse) {
            print('scrolled down');
            //the setState function
          } else if (_scrollController.position.userScrollDirection ==
              ScrollDirection.forward) {
            print('scrolled up');
            //setState function
          }
          return true;
        },
        child: ListView(
          controller: _scrollController,
          // This next line does the trick.
          scrollDirection: Axis.vertical,
          children: <Widget>[
            Container(
              height: 200.0,
              color: Colors.red,
            ),
            Container(
              height: 160.0,
              color: Colors.blue,
            ),
            Container(
              height: 160.0,
              color: Colors.green,
            ),
            Container(
              height: 160.0,
              color: Colors.yellow,
            ),
            Container(
              height: 160.0,
              color: Colors.orange,
            ),
          ],
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

```

**Comment by seonar22** [comment]
> For me I had to use scrollController.addListener() to set my new state. With the notificationlistener I got render errors when I called set state.
@bilal2-1 Also might need to use like this, I didn't test with StatefulWidget and setState().

**Comment by chinkysight** [comment]
If someone who wants to use the `ScrollNotification` to get the user's scroll direction, then I would reading this conversation https://groups.google.com/g/flutter-dev/c/h-X9UkSAls4
