### ISSUE TITLE
Requesting a way to ask the device "what are the observatory ports running for each FlutterView"

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3784]
Consider the use case of using an arbitrary build system to create a mobile app using Flutter. After the build is done, and the application is running, the developer would like to know how to connect to the running FlutterView(s) in order to profile/observe.

In other words, I have a Flutter app running on my phone (build with debug or profile modes). I'd like to now connect observatory to my app to inspect it. How do I do that?

Without something like this, here's my workflow to try to get an observatory trace of a "cold start" of an animation:
- uninstall APK from device
- flutter run --no-checked
- copy the observatory URL from console
- new tab, load observatory
- navigate to feature/animation in app
- try to capture trace for feature/animation

If I miss it, I need to repeat all the steps (including uninstall, because I don't trust what's on my device) and rebuild. :(

Thanks!

**Comment by Hixie** [comment]
Seth, do you still need this?

**Comment by sethladd** [comment]
We'll probably need something like this, but our tools have changed a lot since this was first filed. Closing for now.
