### ISSUE TITLE
First load of Gallery side drawer doesn't animate out, seems to pop into place

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3785]
I'm finding that the first tap of the side drawer icon of the gallery app seems to not trigger an animation. Instead, on the first tap, the side drawer just pops into place (maybe sometimes I see one frame between tap and final destination).

Second, third, etc taps of the upper-left icon do trigger a smoother animation of the drawer.

This is on a Nexus 5, non-slow mode, and:

```
Flutter on channel master (from git@github.com:flutter/flutter.git)
Framework revision ac2c8fec34 (2 hours ago); engine revision 86837edd4e
```

**Comment by Hixie** [comment]
AOT or JIT?

**Comment by sethladd** [comment]
Whatever `flutter run --no-checked` does. :) Trying to see if I can get a trace now.

**Comment by Hixie** [comment]
Throw --no-checked away. Use --release for all profiling right now. :-)

**Comment by sethladd** [comment]
> Use --release for all profiling right now

Once that works on a Mac, will do :)

**Comment by chinmaygarde** [comment]
> Once that works on a Mac, will do :)

Looking into it. @yjbanov need this too.

**Comment by yjbanov** [comment]
> Once that works on a Mac, will do :)

@chinmaygarde this should already work with Mac + an iDevice, no?

**Comment by abarth** [comment]
I believe the issue is that we need to include a `gen_snapshot` binary built for mac hosts and Android targets in `bin/cache` somewhere.

**Comment by sethladd** [comment]
Assigning to me so I can get a trace for yall.

**Comment by abarth** [comment]
Verified with a high-speed camera that we produce a large number of frames in AOT mode.  I didn't load the video into a video editor to validate that we actually hit every frame, but we certainly don't pop the drawer into place all at once anymore.
