### ISSUE TITLE
split image by locale like Android

### ISSUE THREAD

**Issue by v7lin** [flutter/flutter#37851]

**Comment by BondarenkoStas** [comment]
@v7lin Explain please in more details what is your proposal about? Do you mean to be able to specify which image from assets images to use basing on the locale?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
