### ISSUE TITLE
Android Studio Flutter plugin not able to [hot reload]

### ISSUE THREAD

**Issue by baoxiehao** [flutter/flutter#37854]
## Steps to Reproduce

The flutter Android Studio plugin works just fine, but when I upgrade it to the latest v38.1.1 version, the hot reload function just break down. Pls help.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
[✓] VS Code (version 1.33.1)
[✓] Connected device (1 available)
```

**Comment by baoxiehao** [comment]
Very strange, I've downgrade the plugin back to old v37.0.1, the hot reload still "not works".

In fact, the hot reload works, but in the very slow way. About 20 secs at a time, 5 secs for the code push to phone, another 15 secs to wait until it really hot reloaded....

**Comment by jld3103** [comment]
I had that problem too and also when using the command line, but it only happened randomly.
Currently it's working for me.
When I was using the command line, it didn't even show the text about hot- and state-reload.

**Comment by baoxiehao** [comment]
I have a different situation with you, the hot reload in the command line is very quick. So I just switch the command line for now. It's really painful without hot reload function after you are used to it.

**Comment by baoxiehao** [comment]
> I had that problem too and also when using the command line, but it only happened randomly.
> Currently it's working for me.
> When I was using the command line, it didn't even show the text about hot- and state-reload.
> I think the problem is the sdk and not the plugin.

The randomly not working for hot reload seems as expected, cause I also encountered it occasionally before either using IDE plugin or command line.

**Comment by baoxiehao** [comment]
Upgrade to the latest version v38.2.1 today still not works.

**Comment by kf6gpe** [comment]
This looks like an isolated failure. @baoxiehao I'm going to close this at this point. If you see this with the latest version of the IDE plugin and Flutter (1.12), please reopen. Thanks!

**Comment by baoxiehao** [comment]
The latest AS seems to not have this problem, thanks. 
And I've also used to run the flutter run from the command line, since the log area is bigger and easier to use.
