### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by yassineakermi** [flutter/flutter#37857]
Whenever I try to run flutter command, I get this issue.

> Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: d47fa39ff302d5a3)
Crash report written to C:\Program Files (x86)\Microsoft Visual Studio\2019\Com
unity\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

This is the flutter_01.log content.

> Flutter crash report; please file at https://github.com/flutter/flutter/issues.
> 
> ## command
> 
> flutter doctor
> 
> ## exception
> 
> VersionCheckError: VersionCheckError: Command exited with code 128: git log -n 1 --pretty=format:%ad --date=iso
> Standard error: error: packfile .git/objects/pack/pack-68b6600584298f0f9ed8673f8235c973f20b25ac.pack does not match index
> error: packfile .git/objects/pack/pack-68b6600584298f0f9ed8673f8235c973f20b25ac.pack does not match index
> error: packfile .git/objects/pack/pack-68b6600584298f0f9ed8673f8235c973f20b25ac.pack does not match index
> error: packfile .git/objects/pack/pack-68b6600584298f0f9ed8673f8235c973f20b25ac.pack does not match index
> fatal: bad object HEAD
> 
> 
> ```
> #0      _runSync (package:flutter_tools/src/version.dart:522:5)
> #1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:142:12)
> #2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
> #3      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:289:62)
> <asynchronous suspension>
> #4      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:41)
> <asynchronous suspension>
> #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
> <asynchronous suspension>
> #6      _rootRun (dart:async/zone.dart:1124:13)
> #7      _CustomZone.run (dart:async/zone.dart:1021:19)
> #8      _runZoned (dart:async/zone.dart:1516:10)
> #9      runZoned (dart:async/zone.dart:1463:12)
> #10     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
> <asynchronous suspension>
> #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
> <asynchronous suspension>
> #12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
> #13     new Future.sync (dart:async/future.dart:224:31)
> #14     CommandRunner.run (package:args/command_runner.dart:112:14)
> #15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
> #16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
> <asynchronous suspension>
> #17     _rootRun (dart:async/zone.dart:1124:13)
> #18     _CustomZone.run (dart:async/zone.dart:1021:19)
> #19     _runZoned (dart:async/zone.dart:1516:10)
> #20     runZoned (dart:async/zone.dart:1500:12)
> #21     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
> <asynchronous suspension>
> #22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
> <asynchronous suspension>
> #23     _rootRun (dart:async/zone.dart:1124:13)
> #24     _CustomZone.run (dart:async/zone.dart:1021:19)
> #25     _runZoned (dart:async/zone.dart:1516:10)
> #26     runZoned (dart:async/zone.dart:1463:12)
> #27     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
> <asynchronous suspension>
> #28     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
> <asynchronous suspension>
> #29     run (package:flutter_tools/runner.dart:51:10)
> #30     main (package:flutter_tools/executable.dart:62:9)
> <asynchronous suspension>
> #31     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
> #32     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
> #33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
> ```
> 
> ## flutter doctor
> 
> ```
> encountered exception: VersionCheckError: Command exited with code 128: git log -n 1 --pretty=format:%ad --date=iso
> Standard error: error: packfile .git/objects/pack/pack-68b6600584298f0f9ed8673f8235c973f20b25ac.pack does not match index
> error: packfile .git/objects/pack/pack-68b6600584298f0f9ed8673f8235c973f20b25ac.pack does not match index
> error: packfile .git/objects/pack/pack-68b6600584298f0f9ed8673f8235c973f20b25ac.pack does not match index
> error: packfile .git/objects/pack/pack-68b6600584298f0f9ed8673f8235c973f20b25ac.pack does not match index
> fatal: bad object HEAD
> 
> 
> #0      _runSync (package:flutter_tools/src/version.dart:522:5)
> #1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:142:12)
> #2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
> #3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:95:31)
> #4      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:501:127)
> <asynchronous suspension>
> #5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:152:52)
> #6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:223:41)
> <asynchronous suspension>
> #7      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:193:26)
> #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
> <asynchronous suspension>
> #9      _rootRun (dart:async/zone.dart:1124:13)
> #10     _CustomZone.run (dart:async/zone.dart:1021:19)
> #11     _runZoned (dart:async/zone.dart:1516:10)
> #12     runZoned (dart:async/zone.dart:1463:12)
> #13     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
> <asynchronous suspension>
> #14     _doctorText (package:flutter_tools/runner.dart:192:19)
> <asynchronous suspension>
> #15     _createLocalCrashReport (package:flutter_tools/runner.dart:170:32)
> <asynchronous suspension>
> #16     _handleToolError (package:flutter_tools/runner.dart:125:33)
> <asynchronous suspension>
> #17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:65:22)
> <asynchronous suspension>
> #18     _rootRun (dart:async/zone.dart:1124:13)
> #19     _CustomZone.run (dart:async/zone.dart:1021:19)
> #20     _runZoned (dart:async/zone.dart:1516:10)
> #21     runZoned (dart:async/zone.dart:1500:12)
> #22     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
> <asynchronous suspension>
> #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
> <asynchronous suspension>
> #24     _rootRun (dart:async/zone.dart:1124:13)
> #25     _CustomZone.run (dart:async/zone.dart:1021:19)
> #26     _runZoned (dart:async/zone.dart:1516:10)
> #27     runZoned (dart:async/zone.dart:1463:12)
> #28     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
> <asynchronous suspension>
> #29     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
> <asynchronous suspension>
> #30     run (package:flutter_tools/runner.dart:51:10)
> #31     main (package:flutter_tools/executable.dart:62:9)
> <asynchronous suspension>
> #32     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
> #33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
> #34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
> ```

**Comment by kangwang1988** [comment]
@yassineakermi 
It seems resulted from a bad flutter build which is expected to be a valid git repo.
You can get a new copy of the flutter repo, I think the issue would be resolved.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by Davidromerojimenez** [comment]
same

Sending crash report to Google.
Crash report sent (report ID: 171de65440438788)
Oops; flutter has exited unexpectedly.
Crash report written to C:\Users\david\flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.
