### ISSUE TITLE
Invalid `Podfile` file: cannot load such file -- ../my_flutter/.ios/Flutter/podhelper.rb.

### ISSUE THREAD

**Issue by JefferyKingChou** [flutter/flutter#37866]
I got a problem which is the same with #37373  .I wanted to regenerate podhelper.rb according to https://github.com/flutter/flutter/wiki/Upgrading-Flutter-added-to-existing-iOS-Xcode-project#regenerate-podhelperrb，but the podhelper.rb not be generated after the command “flutter build ios” executed.

flutter doctor ====
[✓] Flutter (Channel master, v1.8.2-pre.169, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.8.2-pre.169 at /Users/jefferyzhou/Documents/flutter
    • Framework revision aa6384cbac (2 weeks ago), 2019-07-24 08:55:51 -0700
    • Engine revision ef99738baf
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 fedd74669a)

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jefferyzhou/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
        pod setup

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6156.11
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • Jeffery's iPhone • 00f7f906d10494220de2b0c07c145ca2d71da1bf • ios • iOS 12.3.1

! Doctor found issues in 2 categories.

podfile =====
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

flutter_application_path = '../my_flutter/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Test' do

install_all_flutter_pods(flutter_application_path)

end

**Comment by jmagman** [comment]
Can you run the following from your app directory:
```
cd ../my_flutter/
rm -rf .ios
flutter build ios
```
Then paste the contents of .ios/Flutter/podhelper.rb so we can see what it generated?

**Comment by JefferyKingChou** [comment]
The podhelper.rb:

def parse_KV_file(file, separator='=')
    file_abs_path = File.expand_path(file)
    if !File.exists? file_abs_path
        return [];
    end
    pods_array = []
    skip_line_start_symbols = ["#", "/"]
    File.foreach(file_abs_path) { |line|
        next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
        plugin = line.split(pattern=separator)
        if plugin.length == 2
            podname = plugin[0].strip()
            path = plugin[1].strip()
            podpath = File.expand_path("#{path}", file_abs_path)
            pods_array.push({:name => podname, :path => podpath});
         else
            puts "Invalid plugin specification: #{line}"
        end
    }
    return pods_array
end

def flutter_root(f)
    generated_xcode_build_settings = parse_KV_file(File.join(f, File.join('.ios', 'Flutter', 'Generated.xcconfig')))
    if generated_xcode_build_settings.empty?
        puts "Generated.xcconfig must exist. Make sure `flutter pub get` is executed in #{f}."
        exit
    end
    generated_xcode_build_settings.map { |p|
        if p[:name] == 'FLUTTER_ROOT'
            return p[:path]
        end
    }
end

# If this wasn't specified, assume it's two levels up from the directory of this script.
flutter_application_path ||= File.join(__dir__, '..', '..')
framework_dir = File.join(flutter_application_path, '.ios', 'Flutter')

engine_dir = File.join(framework_dir, 'engine')
if !File.exist?(engine_dir)
    # Copy the debug engine to have something to link against if the xcode backend script has not run yet.
    debug_framework_dir = File.join(flutter_root(flutter_application_path), 'bin', 'cache', 'artifacts', 'engine', 'ios')
    FileUtils.mkdir_p(engine_dir)
    FileUtils.cp_r(File.join(debug_framework_dir, 'Flutter.framework'), engine_dir)
    FileUtils.cp(File.join(debug_framework_dir, 'Flutter.podspec'), engine_dir)
end

pod 'Flutter', :path => engine_dir
pod 'FlutterPluginRegistrant', :path => File.join(framework_dir, 'FlutterPluginRegistrant')

symlinks_dir = File.join(framework_dir, '.symlinks')
FileUtils.mkdir_p(symlinks_dir)
plugin_pods = parse_KV_file(File.join(flutter_application_path, '.flutter-plugins'))
plugin_pods.map { |r|
    symlink = File.join(symlinks_dir, r[:name])
    FileUtils.rm_f(symlink)
    File.symlink(r[:path], symlink)
    pod r[:name], :path => File.join(symlink, 'ios')
}

# Ensure that ENABLE_BITCODE is set to NO, add a #include to Generated.xcconfig, and
# add a run script to the Build Phases.
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            next if  config.base_configuration_reference == nil
            xcconfig_path = config.base_configuration_reference.real_path
            File.open(xcconfig_path, 'a+') do |file|
                file.puts "#include \"#{File.realpath(File.join(framework_dir, 'Generated.xcconfig'))}\""
            end
        end
    end
end

**Comment by jmagman** [comment]
You need to run `flutter upgrade` before following the instructions in https://github.com/flutter/flutter/wiki/Upgrading-Flutter-added-to-existing-iOS-Xcode-project.

**Comment by jmagman** [comment]
Please re-open if that doesn't fix it!

**Comment by JefferyKingChou** [comment]
I will try it,thanks.

**Comment by JefferyKingChou** [comment]
It works!Thanks!

**Comment by dalewking** [comment]
I am experiencing this error in one circumstance that I cannot explain.

I have these tasks defined in build.gradle.kts in root of the project:

tasks.register<Exec>("setupCocoaPods") {
    workingDir(iosProjectDir)

    commandLine("pod", "setup")
}

tasks.register<Exec>("installCocoaPods") {
    dependsOn(":setupCocoaPods")
    workingDir(iosProjectDir)

    commandLine("pod", "install", "--repo-update")
}

and when I run ./gradlew installCocoaPods I get the error.

BUT if I run the `pod setup` commands and `pod install --repo-update` at the command line there is no error.

Can't explain it

**Comment by Anoirwork** [comment]
had the same issue i did a `flutter clean` then `cd ios ; pod install` and everything went as expected 
i don't know if this help b ut i wanted to share it with you guys

**Comment by abhishekbedi1432** [comment]
> Can you run the following from your app directory:
> 
> ```
> cd ../my_flutter/
> rm -rf .ios
> flutter build ios
> ```
> 
> Then paste the contents of .ios/Flutter/podhelper.rb so we can see what it generated?

In my case, to avoid code signing I used `flutter build ios --simulator`
