### ISSUE TITLE
Need a memory benchmark

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3786]
When profiling with customer: spicy, we used top and watched the flutter engine process grow slowly over time.  This seemed indicative of a leak in our engine or framework, but we didn't debug further.

Would be useful to record memory usage from some long-running flutter drive test to catch this kind of bug.

FYI @yjbanov

**Comment by yjbanov** [comment]
Was the application running with `--trace-startup` by any chance? In that mode we are recording all trace events indefinitely, so memory is expected to grow. If not, there must be a memory leak.

Regardless, we should provide a way to measure memory usage and catch leaks using a benchmark.

**Comment by Hixie** [comment]
We have one now right?

**Comment by abarth** [comment]
Yes.
