### ISSUE TITLE
[web] How to load custom font?

### ISSUE THREAD

**Issue by tapkain** [flutter/flutter#37864]
Hello, I have problems with loading custom font into flutter web. Did somebody manage to do this?

**Comment by michaelmontero** [comment]
Have you tried that: https://flutter.dev/docs/cookbook/design/fonts?

**Comment by MaikuB** [comment]
believe this should be the example with doing custom fonts on the web https://github.com/flutter/flutter_web/tree/master/examples/custom_fonts

**Comment by tapkain** [comment]
Thanks guys, beautiful fonts are on my flutter web page right now! 🙏
