### ISSUE TITLE
why not add extra_gen_snapshot_options_or_none to xcode_backend.sh

### ISSUE THREAD

**Issue by v7lin** [flutter/flutter#37873]

**Comment by tvolkert** [comment]
@v7lin this issue has no content in the body describing what use case you're trying to solve specifically what changes you're proposing.  Can you elaborate of what you're trying to do and what change you'd like?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
