### ISSUE TITLE
[Sentry] source maps stacktrace

### ISSUE THREAD

**Issue by irux** [flutter/flutter#37875]
Hello, I have the following question:
Is it possible to have a better stacktrace in sentry when something crash in my flutter app? Sometimes sentry doesn't give you something useful because the the stacktrace is only flutter internal libraries. Can I have something like source maps in JavaScript? Thank you!

**Comment by benoitskipr** [comment]
in flutter_web it's even worse, it's minified :
```
main.dart.js in Object.c at line 2313:3
main.dart.js in auM.$0 at line 69921:23
main.dart.js in HY.CS at line 43336:29
main.dart.js in HX.Ik at line 43470:5
main.dart.js in aug.$0 at line 43546:29
main.dart.js in fD.Nc at line 41149:9
main.dart.js in fD.eM at line 41155:30
main.dart.js in fD.MW at line 41279:14
main.dart.js in fD.Gd at line 41261:3
main.dart.js in fD.MU at line 41238:3```

**Comment by bruno-garcia** [comment]
When I upload the generated sourcemaps, I do see it at least unminified:

![image](https://user-images.githubusercontent.com/1633368/92009633-cd70b300-ed16-11ea-8c37-9b753ef8bb08.png)

More specifically, the:

```
../../../lib/main.dart in $0 at line 138:34
```

Although far from ideal, points to the correct line of the code.
Definitely has room for improvement but at least tell your where your code broke.

To get it to work I built the Flutter app providing the release name:


```
export SENTRY_RELEASE=release-name
flutter build web --dart-define=SENTRY_RELEASE=$SENTRY_RELEASE

# Upload source maps
sentry-cli releases new $SENTRY_RELEASE

sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps . \
    --ext dart \
    --rewrite

pushd $OUTPUT_FOLDER_WEB
sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps . \
    --ext map \
    --ext js \
    --rewrite

sentry-cli releases finalize $SENTRY_RELEASE
```

Make sure the app sends the release to Sentry:

```
const String _release =
    String.fromEnvironment('SENTRY_RELEASE', defaultValue: 'unknown');

    final event = Event(
        exception: error,
        stackTrace: stackTrace,
        // release is required on Web to match the source maps
        release: _release);
    await _sentry.capture(event: event);
```

We'll be taking the `release` through the SDK `init` once we implement that. Improvements are incoming.

**Comment by bruno-garcia** [comment]
Seems like my last comment has been useful. And since then, the Sentry SDK moved to another org so the issue tracking any progress in this area is tracked now here: https://github.com/getsentry/sentry-dart/issues/417
