### ISSUE TITLE
CameraPreview is stretching when adding it inside an Expanded Widget

### ISSUE THREAD

**Issue by Loopex2019** [flutter/flutter#37874]
Hi there. I recently want my CameraPreview to take the rest of the available space inside my Column Widget , it worked but the CameraPreview is now stretched ( By the way i added it inside an AspectRatio ) , here is my code :
```
 @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FutureBuilder(
        future: _inizializedCamera,
        builder: (BuildContext context, AsyncSnapshot snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            return Column(
              children: <Widget>[
                _buildBlackBox(context),
                Expanded(
                  child: _buildCameraPreview(),
                ),
              ],
            );
          } else {
            return Center(
              child: CircularProgressIndicator(
                strokeWidth: 1.5,
                valueColor: AlwaysStoppedAnimation(Colors.black),
              ),
            );
          }
        },
      ),
    );
  } 
```

**Comment by Loopex2019** [comment]
Anybody who could answer this ?

**Comment by BondarenkoStas** [comment]
@Loopex2019 is it still relevant?

**Comment by BondarenkoStas** [comment]
Sorry, accidentally closed

**Comment by Loopex2019** [comment]
Yes

**Comment by BondarenkoStas** [comment]
Please provide your ```flutter doctor -v``` output.

**Comment by TahaTesser** [comment]
Hi @Loopex2019 

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
