### ISSUE TITLE
firebase_ml_vision 0.9.2 visionText.text return empty result

### ISSUE THREAD

**Issue by sooxiaotong** [flutter/flutter#37879]
![image](https://user-images.githubusercontent.com/13378059/62725556-f48f7f00-ba47-11e9-99ef-253ff98c6215.png)

Note: the cloudLabeler works find, but not text recognition.

**Comment by nachtmaar** [comment]
Did you try with images in different orientations? Portrait/Landscape? 

For me using `flutter_image_compress` solves the problem. See https://github.com/nachtmaar/flutter-meetup-munich-ocr-demo/blob/master/lib/main.dart#L93

Do you have the same problem in earlier `firebase_ml_vision` version too?

**Comment by nachtmaar** [comment]
Did you try with images in different orientations? Portrait/Landscape? 

For me using `flutter_image_compress` solves the problem. See https://github.com/nachtmaar/flutter-meetup-munich-ocr-demo/blob/master/lib/main.dart#L93

Do you have the same problem in earlier `firebase_ml_vision` version too?

**Comment by sooxiaotong** [comment]
@nachtmaar I don't think it's related to orientation problem since i can change the orientation by turning the document. Maybe it's related to image size and compression?

**Comment by sooxiaotong** [comment]
VisionText visionText = await textRecognizer.processImage(visionImage);

i think the textRecognizer not even try to process the image, it just return empty visionText.text instantly after it triggered.

**Comment by sooxiaotong** [comment]
@nachtmaar  i think i know why, i didn't add this
> pod 'Firebase/MLVisionTextModel'

I try to use cloud text recognition and tried all four orientation, i only can get some random text.

**Comment by sooxiaotong** [comment]
> pod 'Firebase/MLVisionTextModel' 

case close~

**Comment by sooxiaotong** [comment]
@nachtmaar Do you have any ideas when the orientation bug will be fixed? I think the issue is related to camera plugin on specific iPhone

**Comment by nachtmaar** [comment]
I don't know if it is a bug. I think `firebase_ml_vision` just expects the image to be in landscape mode, but this is only a guess.

My current workaround is using the `flutter_image_compress` plugin as described above. You can read EXIF information with `exif ` plugin if you think there is a EXIF bug.
See [How to read exif orientation](https://github.com/nachtmaar/flutter-meetup-munich-ocr-demo/blob/master/lib/image.dart#L3).

You could also give `image_picker` a try. But both for `camera` and `image_picker` I am using the workaround :/

It should be easier to use `firebase_ml_vision` :/

**Comment by nachtmaar** [comment]
@sooxiaotong The reason why it might be specific to certain phones is probably the rotation of the camera sensor itself because width and height of the sensor are not the same.
