### ISSUE TITLE
Ensure that Flutter works well with Pixel 4 / Pixel 4 XL

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#37888]
This is a tracking issue to ensure that we test Flutter with the new Pixel 4 phones and ensure that there are no gotchas.

https://www.cnet.com/news/googles-pixel-4-to-reportedly-come-with-a-90hz-smooth-display/

**Comment by Hixie** [comment]
Downgrading from blocker as this isn't actually blocking anyone.

**Comment by liyuqian** [comment]
Is the next step to get a Pixel 4 and add it to our device lab? I already have an idle Mac Mini so I only need a Pixel 4, and a space with power and network. @digiter : is there any spare space in the 1808 device lab?

**Comment by Hixie** [comment]
Removing `critical` label since we have checked that things work and this is now just about testing more long-term.

**Comment by liyuqian** [comment]
Closing as we've returned the Pixel 4.
