### ISSUE TITLE
Camera is being used after Camera.release() was called

### ISSUE THREAD

**Issue by agungjk** [flutter/flutter#37887]
Camera crash on device with android pie
on this line
      cameras = await availableCameras();

**Comment by Loopex2019** [comment]
Could you provide a screenshot of your camera code .

**Comment by agungjk** [comment]
i test using
https://flutter.dev/docs/cookbook/plugins/picture-using-camera
and
https://github.com/flutter/plugins/tree/master/packages/camera/example

with no success on nokia 3 (stock android 9 - pie)
but working on emulator with android 9

**Comment by BondarenkoStas** [comment]
@agungjk Is the issue still relevant?

**Comment by agungjk** [comment]
@BondarenkoStas yes, on nokia 3 android 9
![Screen Shot 2019-09-26 at 15 46 08](https://user-images.githubusercontent.com/6745353/65673700-7cbbf900-e075-11e9-8553-11582397bb3d.png)

**Comment by Martin-Pucalka** [comment]
I have same problem on nokia 3 android 9

**Comment by TahaTesser** [comment]
Hi @agungjk 
if you're still experiencing this problem with latest stable, please create a new issue and provide the information required in the template.
Thank you
