### ISSUE TITLE
flutter run doesn't know that a user switched from debug to release

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3788]
Consider this series of steps:

* flutter run
* flutter run --release

Expected: the second run should be in release mode.

Actual: the second run is still using debug mode.

From the logs:

```
  4 ms • Running build command.
   0 ms • APK up to date; skipping build step.
   4 ms • Stopping app 'app.apk' on Nexus 5.
```

Workaround: `rm -rf build` before you toggle `--release` (or, before you switch between modes).

Could we check if the requested mode isn't the previous mode, and use different assets in build?

@jason-simmons suggested a layout something like `build/debug` and `build/release` etc.

Thanks!

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by eseidelGoogle** [comment]
Possibly related https://github.com/flutter/flutter/issues/3455

**Comment by Hixie** [comment]
When fixing this we should also fix that we don't rebuild the apk when you switch engine (by first specifying --engine-debug and then not specifying it, for instance).

**Comment by sethladd** [comment]
Just ran into this again. :(  If the user switches between modes, we should delete whatever previous artifacts we put in place.

**Comment by Hixie** [comment]
@devoncarew/@jason-simmons do you have any ideas on how this should be addressed?

**Comment by devoncarew** [comment]
Yeah, I had a PR out for this (https://github.com/jason-simmons/flutter/pull/1) - it needs to get rebased against the current source and sent out again. It's a quick fix.
