### ISSUE TITLE
Running a second copy of a macOS app kills the first

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#37889]
We need to figure out how we want this to work if it's actually the same .app, but certainly the kill-old-instance logic is too aggressive in that even if you have to actually different apps but they have the same name (e.g., you are using the FDE example shell without renaming) launching one will kill the other.

**Comment by jonahwilliams** [comment]
I think we should kill the killing of processes on run. Let quit kill the current process, but otherwise leave anything running as is.
