### ISSUE TITLE
Scrolbar drag interaction fidelity

### ISSUE THREAD

**Issue by Kavantix** [flutter/flutter#37892]
The current implementation of the draggable scrollbar has a few quirks.

1. The longpress gesture takes 500ms (since that is the default for flutter). But on native it seems much faster, almost instant even.
From my testing it seems that the value should be somewhere between 50 and 150ms. It might even be that it just differentiates between a drag and a tap down.
I was able to change this value by adding a `deadline` field to the constructor of `LongPressGestureRecognizer` which I set to the values 50-150.

2. The current implementation also has a drag from the right gesture, I haven’t been able to reproduce this on a native iOS 13 device. Even with my apple pencil on the iPad pro it does not work. However, on the sim it ‘seems’ to happen. This is possibly just because the long press gesture is so short and thus already detected which gives the impression of the drag from the right working.

**Comment by justinmc** [comment]
1. I think I'm on board with this approach to correct this.  Add a parameter like `deadline` to `LongPressGestureRecognizer`, then set it to ~50-150ms in `CupertinoScrollbar`.  I'll ask around if anyone has had a reason to tweak the long press threshold before.

  2. I'm planning to try this out on a physical device tomorrow.  If it seems like it's just an accidental long press, it will be really easy to just remove the drag-from-right functionality.

**Comment by justinmc** [comment]
I agree that swipe-in-from-right is a ruse!  I played around with a physical iOS 13 device and it seems like it is probably just activating the longpress method.

I think we should remove swipe-in-from-right and adjust the timing of longpress.  We should try out just using a tap or something first, but if that doesn't work out ok then I think something like `deadline` would be nice.

**Comment by justinmc** [comment]
Closing with https://github.com/flutter/flutter/pull/41799.
