### ISSUE TITLE
Form autovalidate happens on first build

### ISSUE THREAD

**Issue by kjeremy** [flutter/flutter#37897]
If I have a `Form` with `autovalidate: true` then all of the fields evaluate before any data has been entered. I only want to show error message when something has changed, not when the form is first displayed.

**Comment by bobykurniawan11** [comment]
What i did 

` bool _autoValidate = false;`

Then  when the user submit the form 

```
  void _validateInputs() {
    if (_formKey.currentState.validate()) {
      setState(() {
        _isInAsyncCall = true;
        _login();
        _formKey.currentState.save();
      });
    } else {
      setState(() {
        _autoValidate = true;
        _isInAsyncCall = false;
      });
    }
  }
```

then you can change `autovalidate: true` to `autovalidate: _autoValidate `

**Comment by melwinlobo18** [comment]
`autoValidate` property is used to trigger the validator function of the TextFormFields of a Form. So if you have set it to `true` then the validator is called at the beginning which shows the error message. So it's better to implement it as @bobykurniawan11 has shown above.

**Comment by TahaTesser** [comment]
Hi @kjeremy 
Looks like there is proposal to improve this option
Closing in favor of [#48876](https://github.com/flutter/flutter/issues/48876)
Thank you

**Comment by kjeremy** [comment]
But that proposal has not been accepted or implemented. This issue should remain open until then.

**Comment by nateshmbhat** [comment]
See PR #56132
