### ISSUE TITLE
Dropdown menu is not scrollable using FLUTTER DRIVER 

### ISSUE THREAD

**Issue by snickersv2** [flutter/flutter#37903]
## Steps to Reproduce

1. Add a `DropdownButtonHideUnderline` widget in your app
2. Launch your app, open the `DropdownButtonHideUnderline` you created
3. Notice you can scroll through the dropdown items manually
4. Create a driver test and use **driver.scroll** function(https://flutter.dev/docs/cookbook/testing/integration/scrolling) passing your `SerialiazableFinder` for `DropdownButtonHideUnderline`. 
I notice also in the Flutter Inspector that there is no widget that contains all the `DropdownMenuItem`. They are all contained within the `MaterialApp` but using this as the `SerializableFinder` to use for scrolling doesn't work as well!

![image](https://user-images.githubusercontent.com/49699862/62745938-1bc35d80-ba02-11e9-86e3-1dccfa26233c.png)

<details>
<summary> flutter doctor -v</summary>

```
/Users/user/Documents/Flutter/sdk/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/user/Documents/Flutter/sdk/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.4.3
    • Dart plugin version 191.6183.87

[✓] Connected device (1 available)
    • SM A520F • 52105109ea678475 • android-arm64 • Android 8.0.0 (API 26) (emulator)

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by jonsamwell** [comment]
Could this be bump up as a priority?

**Comment by pedromassangocode** [comment]
Hi @snickersv2,
I wasn't able reproduce the issue based on the steps you provided. Please provide a minimal complete reproducible code sample.

@jonsamwell please provide a minimal complete reproducible code sample.

Thank you.

**Comment by darshankawar** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
