### ISSUE TITLE
Flutter test's output on test failure is too verbose.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#3790]
I currently get 156 lines of exception backtraces with relevant information embeded within it.

Only 10 lines of the 156 lines are actually useful:  ie. they tell me what the failure is and where.

We can do better.

Maybe we need to make a metric for the board.  % lines of test failure useful:  6%

**Comment by Hixie** [comment]
There's three bugs here.
-[ ] #3639 - for some reason, the test framework outputs tests twice.
-[ ] I can't control the output of the test framework in the first place. If I could, I'd make the exceptions prettier without needing to throw a fake one.
-[ ] We don't currently post-process the stack traces to remove dart-internal frames. I plan to add that at some point.

**Comment by Hixie** [comment]
Fixed by https://github.com/flutter/flutter/pull/3936.
