### ISSUE TITLE
`flutter clean` should remove platform ephemeral directories

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#37909]
## Use case
Sometimes the ephemeral directories are produced from out-of-date templates that must be re-created, or just get in a weird state.  

## Proposal
`flutter clean` should remove the ephemeral directories like `.android` and `.ios` and let them be re-generated on the next build.  This shouldn't impact modules that have been made editable.

**Comment by jmagman** [comment]
@xster Do you think this is a good idea?

**Comment by jonahwilliams** [comment]
flutter clean should probably remove every single file generated by the tool, whether those are the ephemeral host artifacts, build thingies, .flutter-plugins, et cetera.

Separately, needing to flutter clean is a sign of a very severe issue with asset/build invalidation that needs to be fixed.

> Sometimes the ephemeral directories are produced from out-of-date templates

This seems like a bug

**Comment by jmagman** [comment]
> > Sometimes the ephemeral directories are produced from out-of-date templates
> 
> This seems like a bug

Can be benign, like the Xcode template being updated to newest version build setting recommendations, for example.

**Comment by jmagman** [comment]
> flutter clean should probably remove every single file generated by the tool, whether those are the ephemeral host artifacts, build thingies, .flutter-plugins, et cetera.

If `.flutter-plugins` gets deleted do you think people will get confused that they always have to run `flutter packages get` after a `flutter clean`?  That could break existing scripts (some of our CI integration tests, for example).

**Comment by jonahwilliams** [comment]
Yeah that's a good point, probably not the .flutter-plugins then.
