### ISSUE TITLE
There's so many crashes on Android with release

### ISSUE THREAD

**Issue by hahafather007** [flutter/flutter#37911]
I saw on the third-party crash report that there are a lot of crashes inside Flutter on Android devices, and I have switched many different versions of Flutter without getting better.
![image](https://user-images.githubusercontent.com/23414420/62750872-29c1be80-ba94-11e9-83a7-8f94c8d29482.png)
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.7.8+hotfix.4-pre.4, on Mac OS X 10.14.5 18F132,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Community Edition (version 2018.2.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```
This is my current version of Flutter. The new version of the app released yesterday also has these crashes.
I think these crashes are a very serious problem that needs to be resolved as soon as possible.

**Comment by goderbauer** [comment]
There's not enough information here to track down the crashes. Feel free to reopen if you can provide more information about the crashes.
