### ISSUE TITLE
The message of Firebase Phone Auth not change according its template (Localization)

### ISSUE THREAD

**Issue by khachuong** [flutter/flutter#37918]
I am using firebase_auth for verify user's phone number, although I already tried to chaneg the language code to Vietnamese, and the template on the Firebase also is Vietnamese but I still got the SMS like this: "Your Firebase App verification code is: 099211" 

Here is my code:

` _auth.setLanguageCode("vi");`

Here is my Firebase Console setting: 
[https://i.ibb.co/2d4pthC/Screen-Shot-2019-08-09-at-2-02-13-PM.png](https://i.ibb.co/2d4pthC/Screen-Shot-2019-08-09-at-2-02-13-PM.png)

I also wonder how to change the "Firebase App" name for the SMS?

Thank you very much!

**Comment by BondarenkoStas** [comment]
@khachuong Is the issue still relevant?

**Comment by khachuong** [comment]
@BondarenkoStas I still got this issue, do you have any solution?
![Image-1](https://user-images.githubusercontent.com/7900124/65520193-69901880-df11-11e9-9603-b9ec73605571.jpeg)

**Comment by kroikie** [comment]
@khachuong

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1084. Any further collaboration will be done there.
