### ISSUE TITLE
local_auth is crashed the app with AndroidX 

### ISSUE THREAD

**Issue by Den-Ree** [flutter/flutter#37926]
Hello, dear Flutter team. 

I have migrated the Flutter app to use AndroidX and after that the app started crashing on Android with the logs in debug console, if I remove the package and hide according code from the app, everything works. For migration I use the [guideline](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility).

## Logs

```
[ +193 ms] > Task :local_auth:compileDebugJavaWithJavac FAILED
[        ]          *********************************************************
[        ] WARNING: This version of local_auth will break your Android build if it or its dependencies aren't compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[        ]          *********************************************************
[        ] 58 actionable tasks: 1 executed, 57 up-to-date
[   +1 ms]
/Users/denree/Projects/Others.../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/local_auth-0.5.2+4/android/src/main/java/io/flutter/plugins/localau
th/AuthenticationHelper.java:63: error: cannot find symbol
[   +2 ms]   private final FingerprintManagerCompat fingerprintManager;
[        ]                 ^
[        ]   symbol:   class FingerprintManagerCompat
[        ]   location: class AuthenticationHelper
[        ]
/Users/denree/Projects/Others.../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/local_auth-0.5.2+4/android/src/main/java/io/flutter/plugins/localau
th/AuthenticationHelper.java:76: error: cannot find symbol
[        ]     this.fingerprintManager = FingerprintManagerCompat.from(activity);
[        ]                               ^
[        ]   symbol:   variable FingerprintManagerCompat
[   +4 ms]   location: class AuthenticationHelper
[        ] 2 errors
```

## The output error

```
.../Projects/Others.../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/local_auth-0.5.2+4/android/src/main/java/io/flutter/plugins/localauth/AuthenticationHelper.java:63: error: cannot find symbol
  private final FingerprintManagerCompat fingerprintManager;
                ^
  symbol:   class FingerprintManagerCompat
  location: class AuthenticationHelper
.../Projects/Others.../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/local_auth-0.5.2+4/android/src/main/java/io/flutter/plugins/localauth/AuthenticationHelper.java:76: error: cannot find symbol
    this.fingerprintManager = FingerprintManagerCompat.from(activity);
                              ^
  symbol:   variable FingerprintManagerCompat
  location: class AuthenticationHelper
2 errors
Gradle task assembleAccDebug failed with exit code 1
```

**Comment by sarbagyastha** [comment]
Restarting the application will fix the issue. You'll need to full restart your app once you upgrade the plugin.

**Comment by Den-Ree** [comment]
Hi, @sarbagyastha! 
Thanks for the help.
I have done it, also I deleted the app and did a fresh install. Few times deleted all packages and cache in Flutter packages. 

If I correctly understood the problem that `FingerprintManagerCompat` is [deprecated on AndroidX ](https://androidx.de/androidx/core/hardware/fingerprint/FingerprintManagerCompat.html) and need to use BiometricPrompt instead.

I'm not good at Android development, but maybe you know if I change the class as suggested, it will not affect the core functionality of the package?

**Comment by sarbagyastha** [comment]
Yes you understood it well. FingerprintCompatManager was from support library.

You need not change the class on your own. Full restart of your ap should fix it. But you need change FlutterActivity to Flutter FragmentActivity as in the [docs](https://pub.dev/packages/local_auth#android-integration).

**Comment by sarbagyastha** [comment]
Example for changing FlutterActivity to FlutterFragmentActivity: [https://github.com/flutter/plugins/blob/master/packages/local_auth/example/android/app/src/main/java/io/flutter/plugins/localauthexample/MainActivity.java](https://github.com/flutter/plugins/blob/master/packages/local_auth/example/android/app/src/main/java/io/flutter/plugins/localauthexample/MainActivity.java)

**Comment by Den-Ree** [comment]
@sarbagyastha thanks, I will try to change it.

**Comment by Den-Ree** [comment]
@sarbagyastha I have tried, but then new errors appears and there is no methods in  BiometricPrompt to check  `isHardwareDetected()` and `hasEnrolledFingerprints()`. 
Looks like I'm stuck. 

@mehmetf I saw you did changes in the local_auth repo, could you please check the issue and suggest something?

**Comment by sarbagyastha** [comment]
@Den-Ree you can use `getAvailableBiometrics()` which works as `isHardwareDetected()`. And as an alternative to `hasEnrolledFingerprints()` you can catch PlatformException as [shown here](https://pub.dev/packages/local_auth#exceptions).

**Comment by Den-Ree** [comment]
@sarbagyastha after I did the following fixes: 
1. changed `FingerprintCompatManager` to `BiometricPrompt`
2. changed `isHardwareDetected()` to `getAvailableBiometrics ()`
3. deleted `hasEnrolledFingerprints()` 

then now it's showing the errors:
```
/Users/denree/Projects/Others.../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/local_auth-0.5.2+4/android/src/main/java/io/flutter/plugins/localauth/AuthenticationHelper.java:76: error: cannot find symbol
    this.biometricManager = BiometricPrompt.from(activity);
                                           ^
  symbol:   method from(FragmentActivity)
  location: class BiometricPrompt
/Users/denree/Projects/Others.../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/local_auth-0.5.2+4/android/src/main/java/io/flutter/plugins/localauth/AuthenticationHelper.java:89: error: cannot find symbol
    if (biometricManager.getAvailableBiometrics()) {
                        ^
  symbol:   method getAvailableBiometrics()
  location: variable biometricManager of type BiometricPrompt
2 errors
```

**Comment by sarbagyastha** [comment]
@Den-Ree You need not change anything in the JAVA file. Everything is handled by the plugin itself. You just need to implement the same using DART only. [See the examples](https://github.com/flutter/plugins/tree/master/packages/local_auth/example)

**Comment by Den-Ree** [comment]
@sarbagyastha but the initial problem that it gives me error in the java file, when I tried to run on the device with Android 9. 
Therefore I'm trying to change the library. If I remove the library from my project, the app is launched on the device.

**Comment by sarbagyastha** [comment]
Go to `Users/denree/Projects/Others.../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org` this directory .. delete local_auth related folders and run `flutter pacakages get`

**Comment by Den-Ree** [comment]
@sarbagyastha it helps. Don't understand why it shows old code there, looks like I used `update packages` instead of `get` them. 
Thank you for the help.
