### ISSUE TITLE
VScode debug not work with underline prefix variables

### ISSUE THREAD

**Issue by dsfsdsfs2007** [flutter/flutter#37920]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5109853/62765457-bd11e880-bac2-11e9-9c03-ffe725285dea.gif)

**Comment by kangwang1988** [comment]
cc @DanTup

**Comment by dsfsdsfs2007** [comment]
[flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✗] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Community Edition (version 2018.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

! Doctor found issues in 3 categories.
exit code 0

**Comment by DanTup** [comment]
This looks like https://github.com/Dart-Code/Dart-Code/issues/1880 which I can only repro in `stable` and not `master` so I think it's been fixed in a Dart SDK update.

Let me know if you still see this on a more recent build (or the next stable).
