### ISSUE TITLE
AndroidView is not clickable

### ISSUE THREAD

**Issue by MarcoMihaiCondrache** [flutter/flutter#37925]
As the title suggests i'm using the androidView to display a particular image.
The problem is that AndroidView is not clickable, wrapping it in a gesturedetector or inkwell the onTap is never called when i click the widget

```
GestureDetector(
onTap: (){ print("CLICKED"); },
child: AndroidView(
viewType: '..',
onPlatformViewCreated: onPlatformViewCreated,
creationParams: creationParams,
creationParamsCodec: const StandardMessageCodec(),
gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
        new Factory<OneSequenceGestureRecognizer>(
          () => new TapGestureRecognizer(),
        ),
      ].toSet(),
),
),
```

**Comment by BondarenkoStas** [comment]
@MarcoMihaiCondrache is the issue still relevant?

**Comment by MarcoMihaiCondrache** [comment]
No and the issue can be closed sorry for the discomfort

**Comment by wjyconan** [comment]
I have the same problem. How did you solve it? @MarcoMihaiCondrache

**Comment by zyw** [comment]
I have the same problem. How did you solve it? @MarcoMihaiCondrache

**Comment by xiaxiayige** [comment]
I have the same problem. How did you solve it? @MarcoMihaiCondrache

**Comment by xiaxiayige** [comment]
> I have the same problem. How did you solve it? @MarcoMihaiCondrache

I now add empty view solve the problem
eg:

` Stack(
          children: [
            AndroidView(),
            InkWell(onTap: (){},child: SizedBox())
          ],
        )`
