### ISSUE TITLE
Test Flutter on every commit to flutter/flutter on Fuchsia

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#37937]
Specifically, we want to test hot reload and run complex_layout tests.

**Comment by dnfield** [comment]
Engine should happen this month, but Flutter/flutter is going tbe pushed back.

**Comment by dnfield** [comment]
In particular, we're going to be blocked by inability to start/stop trace data short of giving it an arbitrary duration.

**Comment by dnfield** [comment]
@gw280 have you been working on this one?  I can pick it up again when I'm back later this week.

**Comment by gw280** [comment]
@dnfield I'm more focused on the engine side, but right now I'm dealing with some fires elsewhere. Feel free to take a look and thanks!

**Comment by dnfield** [comment]
This is blocked on getting timeline events into the Dart observatory at the moment.

@blasten @gw280 and @iskakaushik all have context on that.  I'm not actively working on this and have some other high priority items, so I'm unassigning.  Last I understood, @iskakaushik was going to be looking into the blocker for this.

**Comment by dnfield** [comment]
I don't think this is a goal for us anymore, or at least not meant to be tracked in this repository.
