### ISSUE TITLE
after webdev build ,don't  Access by nginx

### ISSUE THREAD

**Issue by heibaikn** [flutter/flutter#37931]
## Steps to Reproduce

1.  new a web flutter by vscode
2.  run webdev serve is ok
3.  run webdev build is ok
4.  but when I  run the application using a static HTTP server,  get a error 

## Picture

2
![image](https://user-images.githubusercontent.com/17714507/62780258-dbd6a600-bae7-11e9-975b-c5f8d91b69fc.png)
3
![image](https://user-images.githubusercontent.com/17714507/62780299-fa3ca180-bae7-11e9-9202-5531d813a089.png)

4
![image](https://user-images.githubusercontent.com/17714507/62780144-91edc000-bae7-11e9-9cef-ad8aa0192c88.png)
```



```
## flutter doctor -v

![image](https://user-images.githubusercontent.com/17714507/62780423-3b34b600-bae8-11e9-8c3a-01e6e9d54f52.png)

**Comment by BondarenkoStas** [comment]
@heibaikn is the issue still relevant? For future, please do not include screenshots of code. This makes it extremely tedious to reproduce the issue, as we would have to manually transcribe your example.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  

Thanks for your contribution.Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
