### ISSUE TITLE
Project build fails at debug execution

### ISSUE THREAD

**Issue by TJMusiitwa** [flutter/flutter#37939]
Recently after updating to the latest Flutter version 1.7.8+hotfix4 running on Windows 10 Pro, the latest VS Code version, I am unable to execute the debugBuild on an old project I had before the update. 
I attempted a flutter-clean command option to see if that would fix the problem but that still does not help the problem.
The error system told me about having to add android tools to the Android Manifest but even after that an error still shows. Any option into how to solve this problem.
It doesn't show up when I create and run a new project however.

### Error Message:
_* What went wrong:
Execution failed for task ':app:generateDebugBuildConfig'.
> org.xml.sax.SAXParseException; systemId: file:/C:/Users/______/Desktop/FLUTTER-PROJ/foodie_grub/android/app/src/main/AndroidManifest.xml; lineNumber: 15; columnNumber: 44; Attribute "replace" bound to namespace "http://schemas.android.com/tools" was already specified for element "application"._

### AndroidManifest.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.foodie_grub"
    xmlns:tools="http://schemas.android.com/tools">

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        tools:replace="android:icon"
        tools:replace="android:label"
        android:name="io.flutter.app.FlutterApplication"
        android:label="foodie_grub"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>
```

**Comment by jason-simmons** [comment]
The `application` element in the manifest will not parse if it has two `tools:replace` attributes.  Try changing `tools:replace` to a comma separated list (`tools:replace="android:icon,android:label"`)

**Comment by TJMusiitwa** [comment]
Thank you so much, that happened to fix the problem.

Jonathan Musiitwa

________________________________
