### ISSUE TITLE
ID token result is not a string

### ISSUE THREAD

**Issue by JoshRice1** [flutter/flutter#37933]

**Comment by yclive0925** [comment]
Can you provide some details?

**Comment by jmagman** [comment]
What ID token?  Where are you seeing that message?  Need additional context.

**Comment by JoshRice1** [comment]
Sorry was searching for an issue and must have accidentally hit enter.  FYI
though reme says to use classpath 'com.google.gms:google-services:4.3.0'
In the Setup but causes build errors.  I had to roll back to 4.2.0

**Comment by jmagman** [comment]
Please file a full issue and fill out the template to give us enough context to figure out how to help.
