### ISSUE TITLE
[web] Small Sample request form firebase interation with fllutter web

### ISSUE THREAD

**Issue by Parmendrakumar** [flutter/flutter#37949]
I am new in flutter and I want to integrate flutter web with firebase.

Can you please provide a sample sample or step for how to integrate flutter web with firebase.

**Comment by Parmendrakumar** [comment]
I have created one sample but its not working https://drive.google.com/file/d/1z1HmKdrP_gXIlN6mxJb7k0A2bezMbRB0/view?usp=sharing

**Comment by BondarenkoStas** [comment]
@Parmendrakumar Please consider to read #32637.
