### ISSUE TITLE
automate the process for updating the code that runs on the benchmark box

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#3794]
We should automate the process for updating the code on the benchmark box. Currently it's a manual process (by one person) to get the latest code over to the box.

I _think_ currently the cron job just invokes the dashboard's `run.sh` script. Instead, it could cd to the dashboard repo checkout, run `git pull`, and then run `run.sh`. This way the code would be up-to-date when it runs.

@yjbanov

**Comment by Hixie** [comment]
You could also have a setup.sh that pulls the update, then a run.sh that setup.sh runs. The setup.sh script wouldn't need to be updated ever (and when updated, would require two iterations).

**Comment by yjbanov** [comment]
With auto-updates we need to watch out for [this problem](http://stackoverflow.com/questions/3398258/edit-shell-script-while-its-running). Luckily our `run.sh` is now very small and shouldn't need frequent updating. It could result in undefined behavior when it does update though.

**Comment by devoncarew** [comment]
Yup, that would be a problem, but perhaps alleviated if we try @Hixie's split between `setup.sh` and `run.sh`?
