### ISSUE TITLE
No vibration

### ISSUE THREAD

**Issue by cooler-king** [flutter/flutter#3795]
In my own app and in the MaterialGallery date and time pickers I get no vibration, despite calls to HapticFeedback.vibrate().

Device: LG LS980

All the vibration-related settings on the device seem to be enabled.  

## Flutter Doctor

[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/vinteresting/dev/github/flutter
    • Framework revision 5460e94488 (6 days ago), engine revision 76d5cf230a

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /home/vinteresting/dev/android-sdk-linux
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2

**Comment by abarth** [comment]
I think I broke this recently.  /me will fix.
