### ISSUE TITLE
macOS list overscroll with mousepad gesture doesn't go past bounds

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#37968]
In a desktop macOS application with a Material `ListView` running as `TargetPlatform.iOS`, the expected over scroll behavior of list scrolling too far and then bouncing back doesn't happen for mousepad two finger scroll gesture. 

Material ListViews do scroll (and properly overscroll) with click'n'drag. Which they probably shouldn't.

**Comment by stuartmorgan** [comment]
Duplicate of #23604. My gestural scrolling WIP handled this correctly; it doesn't work right now because we're treating the trackpad scroll as a mouse wheel.
