### ISSUE TITLE
When i run the application AAPT2 error appears

### ISSUE THREAD

**Issue by aliiezzeddine** [flutter/flutter#37979]
C:\Users\Dell\.gradle\caches\transforms-2\files-2.1\df8769253324bf63b48e6752fd9a3507\res\values\values.xml:4:5-6:11: AAPT: error: :string>.

C:\Users\Dell\.gradle\caches\transforms-2\files-2.1\df8769253324bf63b48e6752fd9a3507\res\values\values.xml:4:5-6:11: AAPT: error: :string>.

C:\Users\Dell\.gradle\caches\transforms-2\files-2.1\df8769253324bf63b48e6752fd9a3507\res\values\values.xml:4:5-6:11: AAPT: error: :string>.

Error: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT2 error: check logs for details

**Comment by goderbauer** [comment]
This bug does not have enough information to reproduce. Feel free to reopen when you can provide more information.
