### ISSUE TITLE
Add a `flutter update-packages --force-upgrade` auto-roller

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#37985]
## Use case

Add an auto-roller to periodically merge the results of a `flutter update-packages --force-upgrade` if no tests fail.

**Comment by jmagman** [comment]
This has been mentioned a few times in a few chats, but I couldn't find an issue for it.

**Comment by jmagman** [comment]
Right now this is done manually: https://github.com/flutter/flutter/pull/37971

**Comment by Hixie** [comment]
keywords: autoroller update packages force upgrade

**Comment by Hixie** [comment]
@godofredoc this would be a really useful bot, fwiw.

**Comment by Hixie** [comment]
cc @dnfield since he's worked on some of our bots

**Comment by dnfield** [comment]
@rmistry could this be a good candidate to fit in with what the Skia autorollers do?

We could write a custom bot to do this in Dart, but if there's already functionality to do it in the Skia autorollers that would be nice.

Effectively, we'd have to:

clone the repo
run `flutter update-packages --force-upgrade`
Commit the result of that
Open a PR with it.
cc or notify someone if it fails (it frequently can fail if, for example, a package we try to upgrade has a breaking change in it).

**Comment by zanderso** [comment]
There are some examples of using github actions to accomplish what we want: https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#use-case-create-a-pull-request-to-update-x-periodically. Thoughts about this approach?

**Comment by godofredoc** [comment]
There are several restrictions on using github actions, we may need to validate with security before implementing.

**Comment by jmagman** [comment]
There's also dependabot, if pub support gets implemented. https://github.com/dependabot/dependabot-core/issues/2166

**Comment by LostInDarkMath** [comment]
Hi, is there any progress here? The libraries in the Flutter SDK have still outdated dependencies, `flutter_driver` for example.

**Comment by jmagman** [comment]
@LostInDarkMath this issue is for automatically running the dart package dependency upgrade script so maintainers don't have to run the script manually periodically, it's not tracking any changes to that script or the way package versions are maintained.

`flutter_test` and `flutter_driver` are shipped in the Flutter SDK, so aren't subject to pub version resolving--you get whatever is in the Flutter SDK you have installed.  If you're seeing a particular problem related to this, you should file a new issue with more details.

**Comment by LostInDarkMath** [comment]
I have created a new issue for this: https://github.com/flutter/flutter/issues/82537

**Comment by godofredoc** [comment]
@christopherfujino I believe you already implemented this, can we close this bug?

**Comment by christopherfujino** [comment]
> @christopherfujino I believe you already implemented this, can we close this bug?

Ahh thanks, didn't know about this! Closing as superceded by https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+autoroll+pub
