### ISSUE TITLE
Crash on flutter upgrade

### ISSUE THREAD

**Issue by StorminGorman** [flutter/flutter#37992]
Attached is the error report
[flutter_01.log](https://github.com/flutter/flutter/files/3488334/flutter_01.log)

**Comment by kbrmimbyl** [comment]
I think it's best to tie production projects to a certain version of flutter. @passsy's flutter_wrapper helps. I couldn't upgrade flutter for my app because the refactoring effort is too high.

**Comment by kangwang1988** [comment]
```
Command exited with code -9: git log -n 1 --pretty=format:%ad --date=iso
Standard error
```
It seems resulted from a broken flutter build which is expected to be a good git repo. Try get a clean copy of the flutter, it would help.
@StorminGorman

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  

Thanks for your contribution.Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
