### ISSUE TITLE
AutomaticKeepAliveClientMixin and wantKeepAlive does not work when new route was pushed/popped.

### ISSUE THREAD

**Issue by opensourcegps** [flutter/flutter#38006]
## Steps to Reproduce

1. Setup standard tabs, make second tab page widget with:

```
with AutomaticKeepAliveClientMixin
``` 
and
```
@override
  bool get wantKeepAlive => true;
```

2. Inside that tab, open any new route:
```
Navigator.push(...)
```
3. Return back from that route:
```
Navigator.pop(context);
```
4. Your tab will be displayed on the screen in saved state. Now switch to other tab and return to your "saved" tab and tab gets reloaded, ignoring 
```
 bool get wantKeepAlive => true;
```

This only happens after opening the route and poping back. Just switching between tabs works properly and state is saved. 
 

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/flutter/flutter_linux_v1.7.8-hotfix.4-stable
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

```

**Comment by goderbauer** [comment]
Can you post a complete working code snippet that showcases the problem?

**Comment by opensourcegps** [comment]
Here is code with persistent tabs:
https://github.com/diegoveloper/flutter-samples/tree/master/lib/persistent_tabbar

Then just push any new route from page2.dart and pop back and wantKeepAlive will stop working.

**Comment by Icyoung** [comment]
@opensourcegps   Same with you.  Can you solve this? It occurs When I use PageView. But I am not sure if because of the itemPage is ChangeNotifierProvider.  Look forward your reply.

**Comment by clong1995** [comment]
I had the same problem

**Comment by awafL** [comment]
The problem persists as of today.

**Comment by CyrilHu** [comment]
don't forget to call super.build(context);
ref:
https://stackoverflow.com/a/53702330

**Comment by xJon** [comment]
This is still an issue, even after calling `super.build(context);`.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by andzejsw** [comment]
I have same issue. I am using my class with `AutomaticKeepAliveClientMixin`. I have overriden method: 
```
  @override
  bool get wantKeepAlive => true;
```
But still dart analysis shows warning. But everything works as it should!

**Comment by andzejsw** [comment]
I found fix in some Chinese programming blog. I only needed to add `super.build(context);` to my widget build method. So keep alive should be used this way: 
```
class MyClass extends State<Mystate> with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @protected
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Scaffold(
      body: Text("Test text"),
    );
  }
}
```

**Comment by zohaib304** [comment]
`  Widget build(BuildContext context) {
    super.build(context);
    return Scaffold(...);
  }`

before you return the Scaffold.

**Comment by hailemix** [comment]
I have added like this but the error still persists.
`import 'dart:math';
import 'package:flutter/material.dart';
import 'color_generator.dart';

void main() => runApp(new MaterialApp(home: PositionedTiles()));

class PositionedTiles extends StatefulWidget {
  @override
  _PositionedTilesState createState() => _PositionedTilesState();
}

class _PositionedTilesState extends State<PositionedTiles> {
  List<Widget> tiles = [
    Padding(
      padding: const EdgeInsets.all(8.0),
      child: MainTile(key: UniqueKey()),
    ),
    Padding(
      padding: const EdgeInsets.all(8.0),
      child: MainTile(key: UniqueKey()),
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
          alignment: Alignment.center,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Row(mainAxisAlignment: MainAxisAlignment.center, children: tiles),
              SizedBox(height: 20),
              FlatButton(
                child: Text(
                  'Next',
                  style: TextStyle(color: Colors.white),
                ),
                color: Colors.blueGrey,
                onPressed: () {
                  Navigator.push(
                      (context),
                      MaterialPageRoute(
                          builder: (BuildContext context) => DetailClass()));
                },
              )
            ],
          )),
      floatingActionButton: FloatingActionButton(
          child: Icon(Icons.sentiment_very_satisfied), onPressed: swapTiles),
    );
  }

  swapTiles() {
    setState(() {
      tiles.insert(1, tiles.removeAt(0));
    });
  }
}

class MainTile extends StatefulWidget {
  MainTile({Key key}) : super(key: key);

  @override
  _StatefulTileState createState() => _StatefulTileState();
}

class _StatefulTileState extends State<MainTile> {
  Color myColor;

  @override
  void initState() {
    super.initState();
    myColor = UniqueColorGenerator().getColor();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      color: myColor,
      child: Padding(
        padding: EdgeInsets.all(70.0),
      ),
    );
  }
}

class DetailClass extends StatefulWidget {
  DetailClass({Key key}) : super(key: key);

  @override
  _DetailClassState createState() => _DetailClassState();
}

class _DetailClassState extends State<DetailClass>
    with AutomaticKeepAliveClientMixin {
  List names = ['John', 'Benny', 'Sam', 'Chris', 'Matt', 'Susan'];

  var random = Random();

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Scaffold(
      appBar: AppBar(),
      body: PageView(children: <Widget>[
        SafeArea(
          child: Container(
            child: ListView.builder(
              itemBuilder: (BuildContext context, int index) {
                return Padding(
                    padding: EdgeInsets.all(10.0),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text('$index'),
                        SizedBox(width: 10.0),
                        Text(
                          names[random.nextInt(names.length)],
                          style: TextStyle(fontStyle: FontStyle.normal),
                        ),
                      ],
                    ));
              },
              itemCount: 100,
            ),
          ),
        ),
      ]),
    );
  }

  @override
  void updateKeepAlive() {}

  @override
  bool get wantKeepAlive => true;
}
`
