### ISSUE TITLE
iOS App Size in FAQ incorrect

### ISSUE THREAD

**Issue by hasen6** [flutter/flutter#38016]
**Steps to Reproduce**

1. create new flutter app in Android studio - no platform channel language support

2. run on iOS simulator and then on Android simulator

3. in terminal run `flutter build appbundle`

4. open XCode and select Team

5. in terminal run `flutter build ios`

6. in XCode set to release and generic device, and then build archive

**app.aab 10.4 MB**

**iOS archive 27.1 MB**

On the app stores in my experience the android app will be about 6MB or less but the iOS will be basically 27 MB or so.

In the iOS archive we can see that in products/applications/Runner it’s the frameworks folder that is taking up all the space. The flutter framework it always 13.7 MB no matter what and the App framework is 10.7MB.

In the FAQ https://flutter.dev/docs/resources/faq#how-big-is-the-flutter-engine the sizes for Android are broken down as 3-4 MB for the flutter framework and about 1MB for the app code. For iOS these values are not given and then download size of 10.9MB seems to be incorrect. It seems to be more like:

**Flutter framework: iOS 13.7 MB Android 4MB**
**Minimal app code size: iOS 10.7MB Android 1MB**

I see in this recent post that others are also getting very large app sizes in iOS. https://blog.codemagic.io/flutter-vs-swift/

How about anyone else? Am I doing anything wrong in the build that could lead to this extra size?

`$ flutter doctor -v`

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.13.6 17G7024, locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.4 at /Users/hasen/Developer/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/hasen/Library/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/hasen/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version openjdk version "1.8.0_152-release"
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.3

[!] iOS tools - develop for iOS devices
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version openjdk version "1.8.0_152-release"

[✓] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • iPhone 6s • 20BAE8DB-DE0B-4E6C-9B1E-C04CB6A20AF0 • ios • iOS 12.1 (simulator)

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment]
The download size of an iOS application is not the same as the on disk size of the application. unfortunately there is no easy way to tell ahead of time what the size of a given app will be, because Apple performs additional thinning/packaging/obfuscating on the uploaded artifacts. 

The reported size is based on our own measurements of the download size of an application

**Comment by hasen6** [comment]
Of course you can find the size of your app, by uploading it to the App store. I have several apps that have zero images, very minimal and are basically the same as the default app but are all 30MB on the App store but only 6-8MB on Android.
Also you _can_ in fact find the size your app will be using this method: https://stackoverflow.com/questions/29152093/how-to-check-approximate-app-store-size-of-app-in-xcode/42317342#42317342 which is quite accurate based on the tests I've made. It shows the default flutter App as being 24.9 MB.

It's impossible to get an app where it's Universal size is under 20MB in the App store. I already posted another issue here showing real app sizes but that was ignored. https://github.com/flutter/flutter/issues/36611 If the same App is 6MB on Android then there's no way it can be 30MB on iOS without something very odd going on. One of my examples was 2MB on React Native and 30MB with Flutter for the exact same app, both actual App store sizes.

Others seem to have mentioned it before too without solution https://github.com/flutter/flutter/issues/21813
Not to mention the other link I gave above which shows a 50MB app on iOS.

**Comment by hasen6** [comment]
Can you please link to an App on the iOS store that was built with Flutter but is under 20MB? I have an App there built with React Native that is 2MB....surely at least under 20MB must be possible.

I'm a big fan of Flutter, and really want to use it but these iOS app sizes are putting me off. I'm not a super fan of React Native per se, I'm just using it as an example since it's also not a native framework. 

Not sure why this issue was just closed and my other post ignored. If I'm doing something wrong that is resulting in these huge app sizes then surely I should be given some advice how to solve it?

**Comment by Hixie** [comment]
We should definitely update the FAQ to address these issues, since this is a common question.

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/36611 which is about actually reducing the size. This is about updating our FAQ once we understand why the size is the way it is.

**Comment by hasen6** [comment]
Any update on this? Check here for an extreme example but is surely commonplace in Flutter https://github.com/flutter/flutter/issues/36611#issuecomment-526894680

**Comment by jmagman** [comment]
`xcodebuild` can be coerced into generating an "App Thinning Size Report".  See https://github.com/flutter/flutter/issues/40471.

**Comment by hasen6** [comment]
@jmagman Yes and the uncompressed size from the report is very near to the actual app store size. But anyway the sizes I've reported are all from the actual app store itself, so even more accurate.

**Comment by jmagman** [comment]
> @jmagman Yes and the uncompressed size from the report is very near to the actual app store size. But anyway the sizes I've reported are all from the actual app store itself, so even more accurate.

I was documenting for the sake of any FAQ updates.

**Comment by hasen6** [comment]
@jmagman Ok I see, yeah the FAQ needs to be updated to a minimum iOS app size of 25-30 MB rather than the 10.9MB. 

More of an issue I noticed recently is the way the iOS app size so quickly bloats out of proportion way beyond the minimum app size. Like we see in the example I linked to above where the exact same app is 7.9MB on Android and 62.3MB on iOS.

**Comment by ejain** [comment]
Haven't compared minimal app sizes, but I just published [an app](https://github.com/zenobase/zenobase-durations) that ends up with the following sizes:

**Android** 
- 20MB aab/apk
- 6.6MB in the Play Store
- 18.6MB on a Nexus 5X

**iOS** 
- 83.4MB ipa
- 201MB unzipped ipa (incl 140MB in "SwiftSupport"!)
- 47.4MB in the App Store preview
- 6.9-37.1MB download size according to App Store Connect
- 19-48.6MB install size according to App Store Connect
- 22MB on an iPhone SE

The smallest iOS sizes are for newer devices, and the largest size is for a "universal" version. Despite the bloated ipa, actual download and install sizes appear to be comparable to Android.

**Comment by dnfield** [comment]
I've updated the FAQ in a few places, but I haven't updated the actual size measurement anywhere.  AFAIK that hasn't been touched in a while.

There are several reasons an iOS binary can look bigger:

1. Bitcode.  There's a very large blob of IR that gets stuffed into the binary that Apple strips away. It's possible to get closer to what Apple actually uses, as described in https://github.com/flutter/flutter/issues/40471
2. We ship multiple architectures per IPA.
3. If you need to support older iOS versions and/or older versions of Swift, Swift adds a _lot_ of space. Swift 5 now has ABI stability, but you can only really take advantage of that on more recent versions of iOS (definitely 13, would have to double check about 12, definitely not 11 and below).

**Comment by BobbyBriQz** [comment]
Any update on this issue? I love building with flutter but these .ipa file size issues are a major turnoff and would impact management's decision when it comes to stack choice for a particular project. This might just be my last flutter app for my employers if this issue isn't resolved soon enough.

**Comment by dnfield** [comment]
Assigning this to @jmagman since her PR will close it.

**Comment by hasen6** [comment]
> Any update on this issue? I love building with flutter but these .ipa file size issues are a major turnoff and would impact management's decision when it comes to stack choice for a particular project. This might just be my last flutter app for my employers if this issue isn't resolved soon enough.

No chance unfortunately, all the threads regarding this are being closed for no reason.

**Comment by dnfield** [comment]
This thread was closed becuase the website documentation has been updated. The new section is live here: https://flutter.dev/docs/perf/app-size#ios

If we don't agree that this resolved the issue we can re-open!  Or, if there's a different (even if related) issue, let's just file a new one.

**Comment by hasen6** [comment]
@dnfield No the issue was never with the documentation, it was always with the framework itself.

**Comment by dnfield** [comment]
Referring to contributors and others trying to help you as idiots is a good way to get your issues closed :)

The iOS apps are bigger. This is both due to the binary format apple uses as well as the order of encryption and compression. The FAQ describes this. There's not much else for us to do.
