### ISSUE TITLE
http.get throwing an exception on the iOS simulator

### ISSUE THREAD

**Issue by Clay3981** [flutter/flutter#3802]
I made a simple demonstration app that does a http.get which throws an exceptions. The stocks example throws the same error.

## Steps to Reproduce
Click button which invokes 

var response = await http.get(_url)

## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/toney/flutter
    • Framework revision 5460e94488 (7 days ago), engine revision 76d5cf230a

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1012

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2

## Logs and Crash Reports

```
May  9 11:07:36 --- last message repeated 1 time ---
══╡ EXCEPTION CAUGHT BY NETWORKING HTTP LIBRARY ╞═══════════════════════════════════════════════════
The following NoSuchMethodError was thrown while sending bytes to the Mojo network library:
The null object does not have a getter 'iterator'.
NoSuchMethodError: method not found: 'iterator'
Receiver: null
Arguments: []
When the exception was thrown, this was the stack:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      MojoClient._send.<_send_async_body> (package:flutter/src/http/mojo_client.dart:183:39)
#3      _RootZone.runUnary (dart:async/zone.dart:1137)
#4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:553)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:639)
#6      _Future._completeWithValue (dart:async/future_impl.dart:426)
#7      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:481)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Clay3981** [comment]
Should also mention the same http.get works on the android simulator.

**Comment by eseidelGoogle** [comment]
FYI @chinmaygarde @tvolkert

**Comment by eseidelGoogle** [comment]
Note: this is on the alpha branch (7 days ago) in case that matters.  This file has been changed once since that time,here is the current head version of that line:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/http/mojo_client.dart#L183

I'm surprised this is a funny async stack.  Isn't there a stacktrace library to help make stacks across async boundaries like this readable?  Maybe we're not using it?  @devoncarew 

Also a little surprised we don't have any `flutter drive` test which covers use of the http library in the simulator, definitely should fix that either with this change or shortly after.

**Comment by devoncarew** [comment]
I'm  guessing that the code that threw is running on the device, and that we're not using the `stack_trace` package there. I think it has performance implications? Or just if you have very very long chained async calls? @nex3 would know.

Here's where we use it in flutter_tools: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/executable.dart#L80. If it does have perf implications, we could just enable it on the runtime when in `--debug` mode.

**Comment by eseidelGoogle** [comment]
The thrown code is running in --debug mode on iOS simulator.

**Comment by eseidelGoogle** [comment]
Filed https://github.com/flutter/flutter/issues/3810 about using package:stacktrace in flutter in --debug mode.

**Comment by chinmaygarde** [comment]
Fixed on master 
![screen shot 2016-05-09 at 12 53 22 pm](https://cloud.githubusercontent.com/assets/44085/15126047/07267c96-15e5-11e6-9c2a-09108e909f52.png)

Verifying ns_net in engine next.
