### ISSUE TITLE
Decoding images on the main thread

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3803]
This trace: https://github.com/flutter/flutter/issues/3082#issuecomment-217916705
...shows decoding happening on the main thread.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/engine/blob/master/sky/engine/core/painting/painting.cc#L104 is likely the culprit.  It's posting to the current loop, which is presumably the main thread?  Unless painting.cc typically runs on a background thread?

**Comment by abarth** [comment]
Correct.  painter.cc runs on the ui_thread.

**Comment by abarth** [comment]
Are we calling DecodeImageFromList or DecodeImageFromDataPipe in this case?  /me will investigate.
