### ISSUE TITLE
[web] Unable to save data to firebase in flutter_Web

### ISSUE THREAD

**Issue by Parmendrakumar** [flutter/flutter#38036]
I have create a simple flutter_web app and try to save and retrieve data from firestore.
But I am unable to do that, I am not sure where is the problem.

Sample project: https://drive.google.com/file/d/1z1HmKdrP_gXIlN6mxJb7k0A2bezMbRB0/view?usp=sharing

**Comment by jonahwilliams** [comment]
This is likely an issue with your usage of the firebase package, nothing here indicates a problem with Flutter.
