### ISSUE TITLE
50ms GC loading Weather demo

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3804]
This trace: https://github.com/flutter/flutter/issues/3082#issuecomment-217916705
...includes a 46-54ms GC at t=87,611.486 ms.

cc @iposva-google

To reproduce, open the gallery app and run the Weather demo.

**Comment by eseidelGoogle** [comment]
FYI @a-siva, happy to help someone who's interested in GC issues to repro.

**Comment by rmacnak-google** [comment]
The longest GC I see running the gallery app on a Nexus 4 is 26 ms. With some extra timeline events, I see 18 ms of this is spent processing weak handles, with 952 of 1012 being finalized. How expensive is destructing Path, Picture, Paragraph, and friends?

**Comment by abarth** [comment]
They might be taking time.  We can move them to a finalization queue and destruct them in small chunks.  Most of them can be destructed on a background thread.

**Comment by eseidelGoogle** [comment]
Sounds like we should check in these extra timeline events. :)  Makes it clear when it's flutter's bug to fix :D

**Comment by abarth** [comment]
@rmacnak-google Let's chat tomorrow about how best to hand off the set of things that need finalization from the GC to the embedder.

**Comment by rmacnak-google** [comment]
Extra timeline events in dart-lang/sdk@18c87ab02c62fb2cb5737bf2bc8f7c6b27191e66.

Current thought is for the VM to invoke the finalizers on a background thread.

**Comment by eseidelGoogle** [comment]
@chinmaygarde didn't we have a threading issue with finalizers before?  Could this new proposal be an alternate solution?

**Comment by chinmaygarde** [comment]
@eseidel If you are referring to https://github.com/flutter/engine/commit/3a5dd866, that was just the modification of the reference count of the `DartWrappable` from any thread that was not the `ui_thread`. I believe this is a bit different.

**Comment by abarth** [comment]
@eseidelGoogle The solution for that issue is what makes this approach attractive for this issue.  Given that we need to be prepared for finalizers to be called on any thread, the VM might as well call them on a background thread instead of the UI thread to avoid janking the UI thread.

**Comment by eseidelGoogle** [comment]
@abarth says this is solved.
