### ISSUE TITLE
Flutter Desktop Embedding - http plugin does not work

### ISSUE THREAD

**Issue by giaur500** [flutter/flutter#38046]
Latest master version, I use `http` plugin usual way. It works on Android, but on desktop app, I am never getting any response, it just hangs forever on call and never returns anything, without any exception nor error message.

Please confirm, is that some kind of bug or http is not implemented yet?

**Comment by jld3103** [comment]
For me it works, but I use a slight older version, because I had to fork the plugin and fix an error that didn't get merged yet (dart-lang/http#286).

**Comment by giaur500** [comment]
Linux or Windows? I use http for rest webservice on Linux and I am unable to get it working

**Comment by jld3103** [comment]
I use Linux (Ubuntu 18.04).

**Comment by giaur500** [comment]
Ok, that was my fault, plugin is fine indeed. My server was not responding, sorry for making fuss.

**Comment by stuartmorgan** [comment]
FYI, `http` is just a package, not a plugin. A plugin, in Flutter terminology, is a package that contains platform-specific code (and as such, most of them currently don't work in desktop because they need to be ported, as opposed to normal packages, which should).
