### ISSUE TITLE
 Unhandled Exception: NoSuchMethodError: The getter 'defaultBinaryMessenger' was called on null.

### ISSUE THREAD

**Issue by mickyliu945** [flutter/flutter#38056]
E/flutter (27819): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'defaultBinaryMessenger' was called on null.
E/flutter (27819): Receiver: null
E/flutter (27819): Tried calling: defaultBinaryMessenger
E/flutter (27819): #0      MethodChannel.get:binaryMessenger (package:flutter/src/services/platform_channel.dart:138)
E/flutter (27819): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:312)
E/flutter (27819): <asynchronous suspension>
E/flutter (27819): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:347)
E/flutter (27819): <asynchronous suspension>
E/flutter (27819): #3      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:152)
E/flutter (27819): <asynchronous suspension>
E/flutter (27819): #4      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:25)
E/flutter (27819): <asynchronous suspension>
E/flutter (27819): #5      SPUtils.init (package:island/utils/sp_utils.dart:15)
E/flutter (27819): <asynchronous suspension>
E/flutter (27819): #6      main (package:island/main.dart:22)
E/flutter (27819): <asynchronous suspension>
E/flutter (27819): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:218)
E/flutter (27819): #8      _rootRun (dart:async/zone.dart:1124)
E/flutter (27819): #9      _CustomZone.run (dart:async/zone.dart:1021)
E/flutter (27819): #10     _runZoned (dart:async/zone.dart:1516)
E/flutter (27819): #11     runZoned (dart:async/zone.dart:1500)
E/flutter (27819): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:210)
E/flutter (27819): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305)
E/flutter (27819): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172)

[√] Flutter (Channel master, v1.8.5-pre.101, on Microsoft Windows [Version 10.0.17763.107], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.4)
[√] Connected device (1 available)
• No issues found!

**Comment by mickyliu945** [comment]
When i switch to the stable. There is no error.
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.107], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.4)
[√] Connected device (1 available)

• No issues found!

**Comment by goderbauer** [comment]
The change responsible for this has been reverted. Can you check that everything is wokring again as expected? Feel free to reopen this, if not.

**Comment by Moncader** [comment]
@goderbauer 

I'm still seeing this error on today's master

```
2019-08-31 16:02:29.895644+0900 Runner[16318:16525335] [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'defaultBinaryMessenger' was called on null.
Receiver: null
Tried calling: defaultBinaryMessenger
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:98)
<asynchronous suspension>
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67)
<asynchronous suspension>
#2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:162)
#3      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291)
#4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:162)
```
[✓] Flutter (Channel master, v1.9.8-pre.32, on Mac OS X 10.13.6 17G8030, locale en-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.37.1)
[✓] Connected device (1 available)

**Comment by nocommentsplz** [comment]
I m also getting this error.

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'defaultBinaryMessenger' was called on null.
Receiver: null
Tried calling: defaultBinaryMessenger
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51)
#1      get:defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:87)
#2      MethodChannel.get:binaryMessenger (package:flutter/src/services/platform_channel.dart:140)
#3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314)
<asynchronous suspension>
#4      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:429)
<asynchronous suspension>
#5      SystemChrome.setPreferredOrientations (package:flutter/src/services/system_chrome.dart:228)
<asynchronous suspension>
#6      main (package:tempah_app/main.dart:34)
<asynchronous suspension>
#7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229)
#8      _rootRun (dart:async/zone.dart:1124)
#9      _CustomZone.run (dart:async/zone.dart:1021)
#10     _runZoned (dart:async/zone.dart:1516)
#11     runZoned (dart:async/zone.dart:1500)
#12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172)
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'defaultBinaryMessenger' was called on null.
Receiver: null
Tried calling: defaultBinaryMessenger
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51)
#1      get:defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:87)
#2      MethodChannel.get:binaryMessenger (package:flutter/src/services/platform_channel.dart:140)
#3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314)
<asynchronous suspension>
#4      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:25)
<asynchronous suspension>
#5      main (package:tempah_app/main.dart:42)
#6      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43)
#7      main (package:tempah_app/main.dart:26)
#8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229)
#9      _rootRun (dart:async/zone.dart:1124)
#10     _CustomZone.run (dart:async/zone.dart:1021)
#11     _runZoned (dart:async/zone.dart:1516)
#12     runZoned (dart:async/zone.dart:1500)
#13     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221)
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172)


Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.9.8-pre.35, on Mac OS X 10.14.5 18F132, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.37.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by Kiruel** [comment]
The issue should be reopen @goderbauer.

**Comment by askarsyzdykov** [comment]
same issue

**Comment by goderbauer** [comment]
We would need additional information to re-open this. How does the error reproduce? Can somebody post a minimal code example that shows the error?

Also, did you update your app as explained in https://groups.google.com/forum/#!topic/flutter-announce/sHAL2fBtJ1Y: If you use message channels before calling runApp you need to initialize the  bindings manually by calling `WidgetsFlutterBinding.ensureInitialized()`.

**Comment by askarsyzdykov** [comment]
@goderbauer thank you, with `WidgetsFlutterBinding.ensureInitialized()` works fine

**Comment by Kiruel** [comment]
With this line before runApp `WidgetsFlutterBinding.ensureInitialized();` it works but we should not have to do this. It's add complexity.

**Comment by LauDijksterhuis** [comment]
I think @mickyliu945 is right,

After switching the channel to stable in the terminal, everything works just fine.
Go to terminal and type: `flutter channel stable`

When running the app in debug / release mode it will work again.

**Comment by GuoZhiQiang** [comment]
It's worked with `WidgetsFlutterBinding.ensureInitialized();`.  My flutter version is `1.17.4`
