### ISSUE TITLE
Images are uploaded to the GPU synchronously

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3805]
This trace: https://github.com/flutter/flutter/issues/3082#issuecomment-217916705
...includes a 300ms frame which we suspect corresponds to the frame during which we upload images to the GPU.

To reproduce, open the gallery app and run the Weather demo.

I'd like us to use a solution that keeps the developer in control, i.e. not one that always replaces loading images with a checkboard or some such. We could solve this in various ways, maybe a function that says "pin this to the GPU" and returns a Future that resolves when it's ready (but then how do you handle eviction?); maybe the function that takes the image (`drawImage` and friends) would also optionally return a bool, and if the bool is false (meaning that the image won't be painted this frame in all likelihood) you'd be able to paint something cheaper that frame. We'd also need a way to retrigger a paint once an image was uploaded (maybe a Future again).

**Comment by sethladd** [comment]
Blocked https://github.com/flutter/flutter/issues/3478

**Comment by eseidelGoogle** [comment]
I spoke with @abarth just now.  It will probably be a while before we tackle this.  That could change with more examples, but for now expect this to be a few months away.

**Comment by eseidelGoogle** [comment]
I also mentioned this to @jason-simmons today in case he's interested in more meaty engine work.

**Comment by eseidelGoogle** [comment]
I just spoke with @chinmaygarde and he's willing to tackle this asap.

**Comment by sethladd** [comment]
Thanks @chinmaygarde !

**Comment by sethladd** [comment]
I believe we landed this. There are some bugs, but I think we can close.
