### ISSUE TITLE
Flutter does not receive key up events when cmd key is pressed (macOS)

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#38076]
This has the effect of "sticking" keys in `RawKeyboard.instance.keysPressed`, which in turn causes the `Shortcuts` widget to fail.

After a bit of research, it might be worthwhile to send events directly from the `NSApplication` to the engine. Looks like everything passes through `- sendEvent` before it is interpreted and delegated to the various the `NSResponder` methods. 

Related to #36001

**Comment by shyndman** [comment]
cc @stuartmorgan

**Comment by shyndman** [comment]
Any thoughts on approach Stuart? I had the thought that subclassing `NSApplication` might make integration into existing projects more difficult, but that could be outweighed by the value of dealing with the raw event stream.

Also, is the preference to do this work in Objective-C?

**Comment by stuartmorgan** [comment]
> Any thoughts on approach Stuart?

No, I haven't spent any time investigating this issue. Labelling an issue isn't an indication that I've spent time investigating it.

> Also, is the preference to do this work in Objective-C?

Well, "this work" hasn't been clearly defined; the answer to that question depends on whether the work in in the framework or the template.

**Comment by shyndman** [comment]
And commenting on an issue isn't an indication that I need an answer right away.

I just thought I could help. I'll leave it to you.

**Comment by shyndman** [comment]
Just a quick update here. We managed to get around this with my suggestion above. I'm not sure if it's the best way to go about it, but might be useful when you choose to implement.

```
@objc(MyApplication)
class MyApplication : NSApplication {
  override func sendEvent(_ event: NSEvent) {
    if event.type == .keyUp && event.modifierFlags.intersection(.command).rawValue != 0 {
      self.keyWindow?.sendEvent(event)
    } else {
      super.sendEvent(event)
    }
  }
}
```

Before going down this path, we first tried hooking into `ExampleWindow`'s `sendEvent` (which seems less intrusive), but the keyUp never arrives.

**Comment by hpoul** [comment]
I'm experiencing a similar issue of "sticky" keys in `RawKeyboard.instance.keysPressed`
when I have a key down for <kbd>shift</kbd>+<kbd>X</kbd> but then let go of the <kbd>shift</kbd> before releasing <kbd>x</kbd> i'll have a stick X which never disappears and hence the `Shortcuts` widget & co won't work at all.
Should I open a separate issue for this? Imho the sticky key problem seems very related, especially i'm not sure how this could work in a desktop environment where it's not unusual to switch apps or otherwise lose focus before receiving a matching keyup event? 

```dart
    RawKeyboard.instance.addListener(_debugEvent);

  void _debugEvent(RawKeyEvent ev) {
    final keys = RawKeyboard.instance.keysPressed.map((k) => '${k.keyId} (${k.keyLabel})');
    _logger.fine('Got key event. $keys');
  }
```

```
Got key event. (65 (A))           //// keep shift + A pressed
Got key event. (65 (A))
Got key event. (65 (A), 97 (a))   /// released shift
Got key event. (65 (A), 97 (a))
Got key event. (65 (A))           /// released A
```

**Comment by shyndman** [comment]
Hi @hpoul,

This narrows down some problems we've been seeing, so thanks. That said, definitely a separate issue.

**Comment by gspencergoog** [comment]
/cc @franciscojma86 

This is a result of macOS engine not monitoring the `flagsChanged` message.  We'll need to keep track of the modifier state and send additional key events when modifiers are pressed and released, similar to this example for CapsLock: https://developer.apple.com/library/archive/qa/qa1519/_index.html

**Comment by franciscojma86** [comment]
Landed, @shyndman LMK if you see any issues, thanks for filing!
