### ISSUE TITLE
Flutter SDK Download Link MISSING

### ISSUE THREAD

**Issue by Aug911** [flutter/flutter#38109]
I am new to Flutter and Im trying to download Flutter SDK, but I am unable to find the download link. Did the link change? Or did I miss something?
[Flutter for WIndows](https://flutter.dev/docs/get-started/install/windows) 
[What I see](https://drive.google.com/file/d/109zS4vq-Tqedei7tD-lS6SgzSSeZC0vQ/view?usp=drivesdk)

**Comment by Ahmadre** [comment]
This is the download link: you have to clone it locally and set your PATH env variable if you want to execute flutter commands globally
