### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by AlaaKriedy** [flutter/flutter#38106]
I have problem when I run my Application first time 
when I run I have This message 
```
Oops; flutter has exited unexpectedly.
Crash report written to F:\programer\codecanyon-WG8lwxQX-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework\FluxStore 1.3.5\source\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.

FAILURE: Build failed with an exception.

* Where:
Script 'F:\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 665

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugX64'.
> Process 'command 'F:\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 15s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**Comment by kangwang1988** [comment]
@AlaaKriedy 
Contents for F:\programer\codecanyon-WG8lwxQX-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework\FluxStore 1.3.5\source\flutter_02.log are expected to paste here.

**Comment by AlaaKriedy** [comment]
@kangwang1988 
this is file flutter_02.log
[flutter_02.log](https://github.com/flutter/flutter/files/3492234/flutter_02.log)

**Comment by BondarenkoStas** [comment]
@AlaaKriedy Looking at the error I wonder, may it be related to the use of front slashed in the filename?

**Comment by VladyslavBondarenko** [comment]
I'm going to close because that looks like a support request that is better discussed
in one of the other channels listed at http://flutter.io/support
