### ISSUE TITLE
Consider using package:stacktrace in flutter in --debug mode

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3810]
@devoncarew says this can give us nicer stacktraces.  Here is an example from the flutter_tools:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/executable.dart#L80

Presumably we'd only need/want this in --debug mode?

**Comment by Hixie** [comment]
I'm actually not really convinced they're better. They don't show the full filenames, for example, which messes with IDEs. I'm working on stuff on my test branch that will trim down the stack traces to be just the interesting frames, but that depends on them being in the format that StackTrace emits. If people want them to be prettier in other ways I'm happy to add support for that to the foundation library.

**Comment by devoncarew** [comment]
Yeah, I think the nice part that the stack_trace package provides is a view across several async calls. We can do that ourselves; I think most of the work for that for stack_trace is done here: https://github.com/dart-lang/stack_trace/blob/master/lib/src/stack_zone_specification.dart.

**Comment by Hixie** [comment]
Do you have an example (in Flutter specifically) where the cross-async-call stack_trace logic actually works and gives something useful?

**Comment by devoncarew** [comment]
No, I haven't tried using it in flutter. I've found it useful - in dart:io apps - with code that uses `async` or Futures. Exceptions (like this one: https://github.com/flutter/flutter/issues/3825) are easier to debug then if you only have the top set of frames.

**Comment by Hixie** [comment]
I'm going to close this in favour of the older https://github.com/flutter/flutter/issues/130 which is the more general issue on the same topic.
