### ISSUE TITLE
I am facing the problem with Flutter when I enabled Firebase firestore

### ISSUE THREAD

**Issue by zarub2k** [flutter/flutter#38121]
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: /Users/tham/softwares/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.9/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/tham/softwares/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.9/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
D8: Cannot fit requested classes in a single dex file (# methods: 80668 > 65536)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/0.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/1.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/4.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/5.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/6.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/7.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/8.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/9.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/10.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/11.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/12.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/13.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/14.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/15.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/16.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/17.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/18.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/19.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/20.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/21.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/22.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/23.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/24.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/25.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/26.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/27.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/28.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/29.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/30.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/31.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/32.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/33.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/34.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/35.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/36.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/37.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/38.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/39.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/40.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/41.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/42.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/43.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/44.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/45.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/46.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/47.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/48.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/49.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/50.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/51.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/52.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/53.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/54.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/55.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/56.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/57.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/58.jar, /Users/tham/work/repos/public/hustlebar/flutterwire/build/app/intermediates/transforms/dexBuilder/debug/59.jar
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 2s
Finished with error: Gradle task assembleDebug failed with exit code 1

My application is not compiling and I am not able to make progress with this error. I have no idea how to resolve this.

**Comment by braysonjohn148** [comment]
try lower dependancy, cloud_firestore: ^0.12.9 bring this problem too

**Comment by amitkhairnar44** [comment]
@zarub2k Did you enable multidex in gradle?

**Comment by melwinlobo18** [comment]
I was facing the same issue. Its because your app and the libraries it references exceed 65,536 methods. To fix this follow the steps given in the link below.

[https://developer.android.com/studio/build/multidex](url)

**Comment by tulusda** [comment]
i changed to cloud_firestore: ^0.12.8, and no errors.
apk build

**Comment by melwinlobo18** [comment]
Well, when you have too many dependencies the number of methods eventually go more than 64k. So consider using this option in future if you run in to 'The number of method references in a .dex file cannot exceed 64K.' error.

**Comment by amitkhairnar44** [comment]
@zarub2k Is your issue fixed? If it is fixed then close this issue.

**Comment by zarub2k** [comment]
This was fixed after i downgraded my Firebase version to cloud_firestore: ^0.12.7

**Comment by samigimix** [comment]
> This was fixed after I downgraded my Firebase version to cloud_firestore: ^0.12.7

But it didn't work for me !
