### ISSUE TITLE
[firebase_performance] HttpMetric PayloadSize field can throw a NullPointerException

### ISSUE THREAD

**Issue by axel-op** [flutter/flutter#38133]
When following the example for "Adding monitoring for network requests" on the plugin Readme page (https://pub.dev/packages/firebase_performance), an uncaught `java.lang.NullPointerException` can be thrown when `responsePayloadSize` or `requestPayloadSize` are given a null value. 

This should be handled, as sometimes these values aren't available (especially in the case of streamed responses).

**Comment by kroikie** [comment]
@axel-op

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1135. Any further collaboration will be done there.
