### ISSUE TITLE
Flutter leaks adb ports; requires occasional adb restart

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#3813]
The symptom is `adb` refusing to forward a port because it's full.

Workaround: `adb kill-server`

**Comment by Hixie** [comment]
In `android/android_device.dart` there's a TODO that says:
```
// TODO(devoncarew): Remember the forwarding information (so we can later remove the
// port forwarding).
```
...which seems relevant here.

**Comment by Hixie** [comment]
@yjbanov Do you know if this has been fixed?

**Comment by yjbanov** [comment]
I have not observed this in a while, although the devicelab does restart `adb` regularly. If our developers are not seeing this, I'm ok with closing.

**Comment by Hixie** [comment]
Closing for now.
