### ISSUE TITLE
[firebase_crashlytics] Gradle build failed

### ISSUE THREAD

**Issue by TheVinhLuong** [flutter/flutter#38163]
I am trying to integrate firebase crashlytics into my Android project following the [docs](https://pub.dev/packages/firebase_crashlytics#-readme-tab-) and ended up with gradle build falilure:
```
FAILURE: Build failed with an exception.

* Where:
Build file 'F:\Flutter\Projects\Alola\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII
```

After some struggling I was able to find the cause for it is because of the google service's version specified in the doc . After I downgrade google service version from `4.3.0` to `4.2.0` then the error is gone.

My Flutter doctor output:
```
[√] Flutter (Channel beta, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.885], locale vi-VN)
    • Flutter version 1.7.8+hotfix.4 at F:\Flutter\flutter_windows_v0.7.3-beta\flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at F:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = F:\AndroidSDK;F:\AndroidSDK\platform-tools\;
    • Java binary at: F:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at F:\AndroidStudio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code, 64-bit edition (version 1.31.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.23.0

[√] Connected device (2 available)
    • D6603                        • BH902VHB1L    • android-arm • Android 6.0.1 (API 23)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 8.0.0 (API 26) (emulator)
```

**Comment by acip** [comment]
+!

**Comment by livingstonex** [comment]
Please, where can i find the google services version, in the flutter app... I'm also trying to solve the same error?

**Comment by SpajicM** [comment]
@TheVinhLuong Had the same issue, your workaround worked, thanks!

@livingstonex If you've followed [instructions](https://pub.dev/packages/firebase_crashlytics#-readme-tab-), you've added
`classpath 'com.google.gms:google-services:4.3.0` to dependencies android/build.gradle. Lowering that version to 4.2.0 fixes the issue.

**Comment by livingstonex** [comment]
@SpajicM Thanks a lot... app finally loads after 2 days of trying different proipositions online.
Thanks.

**Comment by FindtheTreasure** [comment]
Sweet mother of Christ...!!...This was doing my head in. Thanks so much :)

**Comment by LCostaN** [comment]
Adding a comment line in the "Add your App" tutorial would be bad practice/idea?
Like " // use gradle 4.2.0 if using firebase analytics "

**Comment by prateekkr94** [comment]
![image](https://user-images.githubusercontent.com/43040768/65328688-dbb8d400-db84-11e9-9c3d-aa3d613df7b7.png)

Hi, I am getting the following error, I am using everything as the latest version(flutter, dart, Android studio) and have all checks in flutter doctor.

P.S. the app was running until I tried to register it with firebase, after that I am starting to get the build Gradle error and a red underline in app/build.gradle. Please help!

**Comment by BwesShr** [comment]
downgrading google service version from 4.3.0 to 4.2.0 worked like a charm... thanx @TheVinhLuong  ...

**Comment by TheVinhLuong** [comment]
@prateekkr94 Did you change `classpath 'com.google.gms:google-services:4.3.0` in `android/build.gradle` to `classpath 'com.google.gms:google-services:4.2.0`? If not then please do it then try again.

**Comment by DaniyarGilimov** [comment]
There should be a solution without downgrading the google services version. In my case i need 4.3.1 version of google-services, so what should i do

**Comment by d1039fx** [comment]
hello, I solved and documented a solution in the following file but this in spanish https://docs.google.com/document/d/16Csy9CEjTx9Bt6vcTJY4DpLtCe2DOCKdDkogXAHu9iw/edit?usp=sharing

**Comment by kroikie** [comment]
@TheVinhLuong

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/347. Any further collaboration will be done there.

**Comment by danteehome** [comment]
It solves the problem by down-grading the version. thanks.

**Comment by Isonomic** [comment]
I downgraded and it doesnt work for me. I am using google sign in

**Comment by Diegitsen** [comment]
You are a genius!!! That works for me :)

**Comment by icripps** [comment]
this problem occurs immediately you open 'flutter_app\android\app\build.gradle', even in a newly created flutter app. i have been stuck on this for three weeks now. please i need a fix.

**Comment by kroikie** [comment]
@icripps It looks like your issue is unrelated to Firebase or Crashlytics. You should file a separate issue with details relating to your specific issue.

**Comment by phamconganh** [comment]
this bug only on windows, on ubuntu it does not happen. And I don't want to change google-services dependency from 4.3.0 to 4.2.0

**Comment by ammarqusailah** [comment]
its worked after adding 
 classpath 'com.google.gms:google-services:4.2.0'

**Comment by sumiayia** [comment]
Thank God.. This was a huge help!! Thanks a lot.

**Comment by g0bichan** [comment]
thank you so much

**Comment by abd0ibrahim** [comment]
> hello, I solved and documented a solution in the following file but this in spanish https://docs.google.com/document/d/16Csy9CEjTx9Bt6vcTJY4DpLtCe2DOCKdDkogXAHu9iw/edit?usp=sharing

Totally works ! Gracias 👍

**Comment by spyderboy** [comment]
Same here, on Windows. This doc was very helpful! Here's an English translation:
https://docs.google.com/document/d/1dX7T0kxlpuE5Aiv7LkPCRxlaEuXYQdrHWWrnhlfX3_8/edit?usp=sharing
