### ISSUE TITLE
Sync focused element between Dart and iOS

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#3817]
Right now, when VoiceOver is enabled, layout changes and scrolling mess with the focused element in an unintuitive manner.  We need to sync the focused element from Dart back to the accessibility subsystem on iOS.

**Comment by goderbauer** [comment]
Closing this as @tvolkert and I are not sure what was meant by this.

**Comment by Hixie** [comment]
Focus in the Flutter framework refers to FocusNode. Text fields and such.
