### ISSUE TITLE
Flutter build_number not updating for iOS

### ISSUE THREAD

**Issue by aabanaag** [flutter/flutter#38191]
## Steps to Reproduce

I had to re-create the iOS project to support swift. After that I noticed that whenever I change the version on my pubspec it doesn't update on iOS after building the app.
1. Change iOS project to support swift
2. update pubspec.yaml
3. flutter build ios
4. Check build folder then show packing contents then check info.plist to verify

```
Analyzing tennisconnect-app...                                          

   info • The value of the field '_error' isn't used • lib/screens/manage_attachments/index.dart:29:10 • unused_field
   info • This function has a return type of 'Future<BaseResponse>', but doesn't end with a return statement • lib/service/auth/auth_provider.dart:73:3 • missing_return
   info • The value of the field '_file' isn't used • lib/widgets/add_media.dart:14:8 • unused_field

3 issues found. (ran in 3.7s)
```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-PH)
    • Flutter version 1.7.8+hotfix.3 at /Users/aabanaag/Documents/framework/flutter
    • Framework revision b712a172f9 (5 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/aabanaag/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.4

[!] iOS tools - develop for iOS devices
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by jmagman** [comment]
What is the value of `version:` in your pubspec?  You may be hitting the issue described here https://github.com/flutter/flutter/issues/34477.

**Comment by aabanaag** [comment]
`version: 1.0.1+29` is the value of `version:` in my pubspec

**Comment by jmagman** [comment]
Hm, I would expect CFBundleShortVersionString to be 1.0.1 and CFBundleVersion to be 29 then.  Can you attach your built app's Info.plist (looks like you already know where to find that) and attach ios/Runner/Info.plist?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  

Thanks for your contribution.Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by arthurzou21** [comment]
I also find this issue. 
But i got `flutter run and flutter build updates the Generated.xcconfig file too, just use its values.`
Solution:
So open simulator and start with debug in vs code, then close app and build again, find the build number update.

**Comment by ch-muhammad-adil** [comment]
I am using version like this inside `pubspec.yaml` , 
`version: 1.0.7+12`

open Your xCode and let it index for a while you will you will see the exact values. 

So in my case, You have to set `CFBundleVersion` and `CFBundleShortVersionString` values like this . Here is How `info.plist` will look after change. 

<img width="719" alt="Screenshot 2020-03-30 at 3 18 39 PM" src="https://user-images.githubusercontent.com/8264639/77902032-fee1e000-7299-11ea-93eb-d49020666604.png">

You can use below source code too 

`       <key>CFBundleShortVersionString</key>
 	<string>$(FLUTTER_BUILD_NAME)</string>
        <key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
`

Please paste it inside your info.plist file.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by Bonissauro** [comment]
In my case, the related behavior started after I, acidentally of course, changed the build number direcly on Xcode, when I should have done it on pubspec.yaml in Android Studio. 
@ch-muhammad-adil tip helped me to correct this and now pubspec's changes reflect in Xcode's project again.

10x a lot for the help
