### ISSUE TITLE
[firebase_messaging] iOS onMessage inconsistency

### ISSUE THREAD

**Issue by dvird** [flutter/flutter#38206]
The message in ios comes in this form
{gcm.message_id: 1565547628558818, thread_id: -LlwL2xHCWRXSCuFIJ3U, google.c.a.e: 1, aps: {alert: {title: abcd, body: abcd}, category: /*Package */_TARGET_NOTIFICATION}}

please look at aps and alert which different from notification on the android side

**Comment by kroikie** [comment]
@dvird

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1049. Any further collaboration will be done there.
