### ISSUE TITLE
InkWell splashes aren't visible and no opaque Material ancestor.

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#38215]
The `InkWell` docs say:

> If there is an opaque graphic, e.g. painted using a Container, Image, or DecoratedBox, between the Material widget and the InkWell widget, then the splash won't be visible because it will be under the opaque graphic. This is because ink splashes draw on the underlying Material itself, as if the ink was spreading inside the material.

And this is my code:

```dart
Card(
  clipBehavior: Clip.antiAlias,
  child: InkWell(
    onTap: () => print('Tap on a Card!'),
    child: AspectRatio(
      aspectRatio: 16/9,
      child: Image.asset(
        'assets/picture.jpg',
        fit: BoxFit.cover,
      ),
    ),
  ),
);
```

As you can see, there's nothing between the `InkWell` and the `Card`, still I don't get an ink splash, which goes against the docs.

I got it to work by using an `Ink`, but this makes the code kinda ugly:

```dart
Card(
  clipBehavior: Clip.antiAlias,
  child: AspectRatio(
    aspectRatio: 16/9,
    child: Ink.image(
      image: AssetImage('assets/picture.jpg'),
      fit: BoxFit.cover,
      child: InkWell(
        onTap: () => print('Tap on a Card!'),
      ),
    ),
  ),
)
```

**Comment by melwinlobo18** [comment]
There's nothing wrong with the documentation. You have Card widget between the Material and the InkWell widget so the splash is not visible. Wrap the Card widget inside the InkWell widget so you can see the splash.

```dart
      InkWell(
          onTap: () {
            print('Tapped');
          },
          child: Card(
            clipBehavior: Clip.antiAlias,
            child: AspectRatio(
              aspectRatio: 16 / 9,
              child: Image.asset(
                'images/gray.jpg',
                fit: BoxFit.cover,
              ),
            ),
          ),
        )
```

**Comment by feinstein** [comment]
But `Card` isn't opaque, and this works:

```dart
Card(
clipBehavior: Clip.antiAlias,
child: AspectRatio(
  aspectRatio: 16/9,
    child: InkWell(
      onTap: () {print('hi');},
      child: Text('Hello')
    ),
  ),
),
```

**Comment by feinstein** [comment]
Also, I just tested your code and it doesn't work, the `InkWell` splash appears outside the boundaries of the `Card`, the `Card` itself doesn't change at all.

**Comment by melwinlobo18** [comment]
Sorry about that. It's because of the order in which the widgets are rendered. Your initial solution renders the widgets as Card > InkWell > Image so the splash effects are not visible (Even though its there!). Whereas the second solution renders the InkWell on top of the Image widget so you can see the splash effect. 
And when you use the Text widget you can see the splash as the text doesn't fill the entire area. SOo the splash will be visible in the available space but whereas an image (opaque graphics) fills the entire available area.
The Ink Class docs say:

> Ink splashes and highlights, as rendered by InkWell and InkResponse, draw on the actual underlying Material, under whatever widgets are drawn over the material (such as Text and Icons). If an opaque image is drawn over the Material (maybe using a Container or DecoratedBox), these ink effects will not be visible, as they will be entirely obscured by the opaque graphics drawn above the Material.
>
Anyways, thanks for including the solution too. It helped me understand the InkWell widget better.

**Comment by feinstein** [comment]
I think the source of confusion is the `Material`. Since `Card` is a special kind of material in the Material Design specs, I was considering it as a `Material` without realizing in Flutter it's not and the `Material` is bellow everything in my code.

Maybe the docs could make this more explicit?

**Comment by TahaTesser** [comment]
Hi @feinstein 
Looks like we can `InkWell` splash in first sample code on latest  `dev` channel


![1](https://user-images.githubusercontent.com/48603081/80230469-9e16af00-866f-11ea-8250-d2a829f59b5e.gif)




<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-6.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-6.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 84c84fb249 (3 days ago), 2020-04-20 21:35:01 -0400
    • Engine revision 2bde4f0ae4
    • Dart version 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10
      (API 29) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Chrome                    • chrome        • web-javascript • Google Chrome
      81.0.4044.122
    • Web Server                • web-server    • web-javascript • Flutter Tools
• No issues found!
```

</details>

Do you think this issue still valid?
Thank you

**Comment by feinstein** [comment]
Give me some days so I can properly test this, thanks.

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
