### ISSUE TITLE
VALIDATION_ERROR_UNEXPECTED_STRUCT_HEADER on master using auth

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3823]
From a customer:

I checked out master and now I can't sign in getting this error
`Invalid message: VALIDATION_ERROR_UNEXPECTED_STRUCT_HEADER`

This relates to using google_sign_in.  FYI @collinjackson

I believe @chinmaygarde is looking.

**Comment by eseidelGoogle** [comment]
Any update?  My understanding last time I spoke to this customer was that they were blocked since this bug blocked working with google_login on the iOS simulator, and https://github.com/flutter/flutter/issues/2740 blocked working on the device, and AFAIK google_login isn't wired up for Android atm.

**Comment by chinmaygarde** [comment]
Fixed by https://github.com/flutter/google_sign_in/pull/5
