### ISSUE TITLE
how to use runWithEntrypoint:libraryURI function?

### ISSUE THREAD

**Issue by cuong1112035** [flutter/flutter#38250]
Currently I have a flutter application which has some main() functions in some difference dart files. Eg main1.dart, main2.dart
I want to integrate my flutter application to my native ios app. After some researches, I know that I have to call runWithEntrypoint:libraryURI function from the native side to indicate where my main() function is.
So my question is what parameters should I pass into the runWithEntrypoint:libraryURI to make it work?
Thanks so much

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
