### ISSUE TITLE
Flutter google map markers change 'clickability' when zIndex is added

### ISSUE THREAD

**Issue by simonh1000** [flutter/flutter#38269]
I have a map with a collection of markers on them. I need to be able to control the zIndex of the markers.

Without any zIndex code, the map works as expected, each marker is clickable (if it can be seen).

But after adding zIndex information the markers seem to gain a significant invisible wrapper and block access to nearby markers (see picture - it is now hard to click on one of the pink markers).

```
  Set<Marker> mkMarkers(List<Resto> restos) {
    this.widget._zIndex = restos.length.toDouble();

    return Set.from(
      restos.asMap().map(
        (int idx, Resto r) {
          double hue = (r.qname == this.widget.viewModel.selectedResto)
              ? BitmapDescriptor.hueOrange
              : 319.0;
          return MapEntry(
              idx,
              Marker(
                markerId: MarkerId(r.name),
                position: LatLng(r.lat, r.lng),
                onTap: () => this.widget.viewModel.onSelectResto(r.qname),
                icon: BitmapDescriptor.defaultMarkerWithHue(hue),
                // code below does not work as expected
                zIndex: (r.qname == this.widget.viewModel.selectedResto)
                    ? this.widget._zIndex
                    : idx.toDouble(),
              ));
        },
      ).values,
    );
  }
```

I can also replicate this error with Google's example code for the plugin itself - see https://youtu.be/l0CYIiA4Tpk

**Comment by BondarenkoStas** [comment]
@simonh1000 Is the issue still relevant? What the versions of flutter and google_maps_flutter you use?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
