### ISSUE TITLE
Displaying large images on low-performance phones fails with no error message

### ISSUE THREAD

**Issue by mcxinyu** [flutter/flutter#38263]
Displaying large images on low-performance phones fails with no error message.

device: xiaomi m4
image url: https://app.njf2016.com:8888/njf/resource/2019/8/12/2639a309-7-8888.jpg

set `filterQuality: FilterQuality.none`  before running
`
                  Image.network('https://app.njf2016.com:8888/njf/resource/2019/8/12/2639a309-7-8888.jpg',
                    filterQuality: FilterQuality.none,
                  ),
`

**Comment by ZQ1297089376** [comment]
set quality: FilterQuality.none

**Comment by BondarenkoStas** [comment]
@mcxinyu Is the issue still relevant?

**Comment by mcxinyu** [comment]
Temporarily solved, close please.
