### ISSUE TITLE
App gets stuck or never reloads when Table has >6 children

### ISSUE THREAD

**Issue by melwinlobo18** [flutter/flutter#38261]
When there are more than 6 children in Table widget the app gets stuck and never reloads (Need to stop the app in IDE) . The issue is faced in following phones Mi A1, Mi A2, Lenovo Vibe k4, etc. It works fine in POCO F1 (Haven't tried it with more devices). 
If I try with the release apk using 'flutter build apk', the installed app gets stuck when opened and should be closed forcefully.
Everything works fine if there are less than 6 children. The issue is seen only in the above devices for now but is significant to look at as the app gets stuck and has to be closed.

## Steps to Reproduce

1. Build the apk in above-mentioned phones
2. Hot reload
I have included the link to the gist below.
[https://gist.github.com/melwinlobo18/52edc2c842e75df7aa0a1b2bf9d3a5a1](url)

## Logs
```
Analyzing timetable_app...                                                 
No issues found! (ran in 2.0s)
```
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.3 at /home/melwin/development/flutter
    • Framework revision b712a172f9 (5 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/melwin/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /home/melwin/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /home/melwin/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.35.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • Lenovo A7010a48 • U4UWZSFQU8CY9SRC • android-arm64 • Android 6.0 (API 23)

• No issues found!

```

**Comment by jason-simmons** [comment]
This should be fixed by https://github.com/flutter/flutter/commit/1b57006c82493a6609481dda507128202f466412

**Comment by melwinlobo18** [comment]
Thanks a lot. It works fine now.
