### ISSUE TITLE
CupertinoTabView will cause quit app on android

### ISSUE THREAD

**Issue by luckysmg** [flutter/flutter#38268]
I have a page A which is in a CupertinoTabView, and on A,I push a new route B. On the B page, when on iOS ,I can go back to  page A  by sliding from left to right,but on android, when I press the back，the app will quit instead of back to A page

**Comment by luckysmg** [comment]
here is video

https://youtu.be/qf0wxKYww1g

**Comment by HansMuller** [comment]
It would help if you could provide the output of `flutter doctor` and a small self-contained app that demonstrates the problem. Note also: https://gist.github.com/ is a useful way to share the code.

On the face of it, it sounds like you need to use [WillPopScope](https://api.flutter.dev/flutter/widgets/WillPopScope-class.html) to intercept attempts to back out of the application when the user is viewing a (nested navigator) CupertinoTabView tab.

**Comment by luckysmg** [comment]
I have solve this  problem.The answer to question is that when I tested,I found that every TabView has a Independent navigation in CupertinoTabScaffold ，so when I want to do the first push on tabview. I should add a param called 
'rootNavigator: true'  .When this param is added , everything is all right.
