### ISSUE TITLE
Document release, debug, profile modes on website

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3827]
I searched for "modes" and "release" on the website, and nothing obvious popped up. Now that `flutter build apk --release` is a thing (mostly, not quite working on a mac), it might be time to queue up some mentions of these modes on the website, and what the trade-offs are.

Thanks!

**Comment by sethladd** [comment]
From the wiki: https://github.com/flutter/flutter/wiki/Flutter%27s-modes

**Comment by Hixie** [comment]
Searching for [modes] or [release] on the web site still doesn't bring up anything interesting.

**Comment by sethladd** [comment]
I would expect to see a doc called "Building Flutter apps" in the HOW-TO section, under/near "Upgrading Flutter". In that doc (which might be short :) I would expect to see some documentation around the various types of builds (release, debug, etc) and what they mean.

**Comment by Sfshaza** [comment]
I've added this to the dash branch. (Master is frozen, except for P0s.)

https://github.com/flutter/website/pull/1330
