### ISSUE TITLE
when i click on the Run button, im getting the following error

### ISSUE THREAD

**Issue by arjunc369** [flutter/flutter#38275]
plz help me with this..im new in flutter

![Capture](https://user-images.githubusercontent.com/54022144/62854701-f3a75900-bca4-11e9-8c39-b344cd29a7ca.PNG)

**Comment by BondarenkoStas** [comment]
@arjunc369 is the issue still relevant?

**Comment by arjunc369** [comment]
No.. its solved.. thanks anyway
