### ISSUE TITLE
[Feature Request] Flutter Music Plugin

### ISSUE THREAD

**Issue by Purukitto** [flutter/flutter#38271]
## Use case

The Flutter library despite having a Video Player does not have a Music Player plugin. Even though there are open-source , user developed plugins to achieve the same, but they are either abandoned or not updated regularly.

## Proposal

An inbuilt music player and associated  plugins to achieve the same

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/47105 as that's where most of the votes and discussion around this request have ended up.
