### ISSUE TITLE
FlutterDownloaderPlugin.java使用或覆盖了已过时的 API

### ISSUE THREAD

**Issue by mulieli** [flutter/flutter#38273]
FlutterDownloaderPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。

**Comment by stuartmorgan** [comment]
Third-party plugin issues need to be filed with the authors of those plugins.

**Comment by mulieli** [comment]
> Third-party plugin issues need to be filed with the authors of those plugins.

thank you
