### ISSUE TITLE
Lose Icons in android release

### ISSUE THREAD

**Issue by excitedhaha** [flutter/flutter#38286]
I used 'add to app' to integrate flutter to my app and used material icons, it shows in flutter host app, but not work in release build.  I'm in the master channel, latest commit:83a8a575e.
![device-2019-08-12-193555](https://user-images.githubusercontent.com/14888929/62862733-54807100-bd39-11e9-8c1a-6ca39c0dc244.png)

**Comment by excitedhaha** [comment]
I solved this problem by include copyFlutterAssets task, changed my app module's gradle file.
```
    android.applicationVariants.all { variant ->
        Task copyFlutterAssetsTask = project.tasks.findByPath(":flutter:copyFlutterAssets${variant.name.capitalize()}")
        Task mergeAssets = project.tasks.findByPath(":app:merge${variant.name.capitalize()}Assets")
        if (mergeAssets) {
            mergeAssets.dependsOn(copyFlutterAssetsTask)
        }

    }
```
And I looked into flutter project's 'flutter.gradle', found the flutter team just remove 'mergeAssets' task to avoid the error: "Cannot change dependencies of configuration ':flutter:releaseApi' after it has been included in dependency resolution".
Please be precise about these issues.

**Comment by blasten** [comment]
> it shows in flutter host app, but not work in release build.

Does this mean that if you build the host app in release mode, the icon doesn't show up?

**Comment by excitedhaha** [comment]
@blasten Yes, I customized Gradle by the wiki, and I think it only happens in a complex project.
And I create a [PR](https://github.com/flutter/flutter/pull/38542) to fix it, you can review my code, thank you.

**Comment by blasten** [comment]
@excitedhaha We won't be able to merge the PR unless we have the exact steps that reproduces the issue and an integration test. Would you be able to come up with a minimal reproduction?

**Comment by excitedhaha** [comment]
@blasten Maybe you can try to add a module manually, to reproduce the error.
