### ISSUE TITLE
iOS restricting performance, affecting Flutter frame rate

### ISSUE THREAD

**Issue by tomalabaster** [flutter/flutter#38293]
iOS sometimes appears to restrict the performance of the device causing Flutter apps to run at a lower frame rate. There aren't any conditions for which I seem to notice this e.g. low power mode isn't on, plenty of battery etc.

This first video is of a Flutter app downloaded from the App Store. (I did also try another Flutter app from the App Store). I start off just using the app with a noticeably slower frame rate to usual (watch the video in 60fps to notice it clearly). I then start screen recording on the device. An outcome of this is that the Flutter app appears to be running at a normal frame rate again. I then stop screen recording and the frame rate drops again: [https://youtu.be/XZQkxxD-YQA](https://youtu.be/XZQkxxD-YQA)

This second video is of Google Maps with screen recording off then on. Google Maps also has this issue and as far as I know Google Maps uses OpenGL. I also tried Apple Maps but there aren't any frame rate issues here. [https://youtu.be/zStY0TZrJoc](https://youtu.be/zStY0TZrJoc)

This was on an iPhone 7 running iOS 12.4. Shortly after recording both of these the issue went away so I wasn't able to profile the device while this was happening.

I know there's an issue open about using Metal instead of OpenGL on >=11.0 then falling back to OpenGL on <11.0: [#18208](https://github.com/flutter/flutter/issues/18208). I haven't used a device running <11.0 in a while so haven't been able to check this is true for <11.0, but I've seen it on 12.1.2 as well.

**Comment by derolf** [comment]
Do you see it in landscape mode?

**Comment by chinmaygarde** [comment]
We were running into OpenGL driver issues that showed similar behavior. I haven't observed this after the switch to Metal. Can you try again on the latest stable branch to see if this is happening now.

**Comment by AtixD** [comment]
@chinmaygarde Hi, I see this problem in 1.17.3 stable version (release mode).
You can just start record screen in iOS and you will see that the frame is better.

**Comment by tomalabaster** [comment]
@chinmaygarde I've not seen it happen in a while now.

**Comment by darshankawar** [comment]
@tomalabaster 
Given your last message, I am going ahead and closing this as resolved. If you disagree or think this need to be kept open, write in comments and I'll reopen.
Thanks.
