### ISSUE TITLE
[Add2App] Cleaning Android host project removes necessary files, causing crash if the flutter module isn't re-built

### ISSUE THREAD

**Issue by lucascolli** [flutter/flutter#38319]
I'm assuming this behavior isn't desired... every time I clean the outer project, I have to build the module again. This started after flutter upgrade from 1.8.4-pre.??? to 1.8.5-pre.117.

This problem has been tough to pinpoint... The first time I encountered this (on older versions of flutter), the .android/Flutter/build/intermediates/library_assets/.../flutter_assets directory was missing. Now after upgrading, it seemed to come back when .android/Flutter/build/outputs/aar/flutter-debug.aar, but subsequent attempts were able to reproduce the error when both the aforementioned were present.

## Steps to Reproduce

1. Set up Android embedding project following [Add Flutter to existing apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) wiki
2. Make the native modules editable with flutter make-host-app-editable
3. Instantiate a new FlutterEngine from the new embedding API
4. Clean outer Android project
5. Run and launch an Activity that creates the engine and FlutterView

## Logs

<img width="1261" alt="Screen Shot 2019-08-12 at 11 10 46 AM" src="https://user-images.githubusercontent.com/47360587/62875995-05631d80-bcf2-11e9-9eab-0454759146e9.png">
<img width="550" alt="Screen Shot 2019-08-12 at 11 01 51 AM" src="https://user-images.githubusercontent.com/47360587/62876027-10b64900-bcf2-11e9-8437-00765d063e8a.png">

Before clean:
<img width="442" alt="Screen Shot 2019-08-12 at 12 35 14 PM" src="https://user-images.githubusercontent.com/47360587/62881484-e7031f00-bcfd-11e9-9819-0cb49a80d164.png">

After clean:
<img width="443" alt="Screen Shot 2019-08-12 at 12 36 46 PM" src="https://user-images.githubusercontent.com/47360587/62881509-eff3f080-bcfd-11e9-84eb-8bf0b90cad79.png">

```
[✓] Flutter (Channel master, v1.8.5-pre.117, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.8.5-pre.117 at /Users/.../Desktop/lcedev/flutter
    • Framework revision 83a8a575ee (2 days ago), 2019-08-10 12:38:20 -0700
    • Engine revision ff49ca1c6e
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 f29f41f1a5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/.../Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

```

**Comment by xiejinpeng007** [comment]
same problem , my app crash when instantiate a new FlutterEngine , but log is different.

**Comment by blasten** [comment]
It's expected that if you clean the project, Gradle will delete the output artifacts.  

To make this easier, the Flutter tool can now build AARs automatically if you run `flutter build aar` within the module directory. You can read more on https://flutter.dev/docs/development/add-to-app/android/project-setup#option-a---depend-on-the-android-archive-aar
