### ISSUE TITLE
Make some driver-like test work without a host, in release mode

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#38329]
This will unblock https://github.com/flutter/flutter/issues/34069 and https://github.com/flutter/flutter/issues/53609

**Comment by liyuqian** [comment]
@collinjackson : To help tracking the progress, I've created this issue according to our offline discussions. Please feel free add more details and reference this from related PRs.

**Comment by liyuqian** [comment]
@digiter : please reference this issue from your PRs on driver tests.

Here are some example driver tests that you can test your PR:
- `cd dev/benchmarks/complex_layout && flutter drive test_driver/scroll_perf.dart`
- `cd examples/flutter_gallery && flutter drive test_driver/transitions_perf.dart`

**Comment by liyuqian** [comment]
This is now (partially?) available in e2e tests: https://github.com/flutter/plugins/blob/master/packages/package_info/example/test_driver/package_info_e2e.dart

It seems that we'll continue to work on `WidgetTester` API to enable this and achieve parity with the `flutter_driver` package.

**Comment by liyuqian** [comment]
Design doc in https://docs.google.com/document/d/1VumsuG6dEFUVpPQLqqKJnhI0CoIS9fCAMN-NFHIPmo0/edit#heading=h.l6kdsrb6j9id

**Comment by chinmaygarde** [comment]
Closing as there is no upstream issue for this. Also, the issue that this would have unblocked has been closed as wont-fix.

**Comment by liyuqian** [comment]
Added https://github.com/flutter/flutter/issues/53609 to the unblock list and reopen this issue. @CareF is currently working on this so I'm assigning this issue to him. His design doc is in go/flutter-nonhost.

**Comment by liyuqian** [comment]
Remove myself from the assignment as I'm not actively working on this. Will reassign myself once I get some time to work on it.

**Comment by cbracken** [comment]
Not planned.
