### ISSUE TITLE
flutter attach should not assume that the application dill and local filesystem are in sync

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#38320]
During `flutter run`, a dill file (1) contain all sources is built and bundled into the APK/IPA that is installed onto the device. Then, when the tool attaches to the observatory for debugging and hot reload, it initializes the frontend server from the existing dill file and recompiles all sources (2). For here on out, any time a hot reload is requested, the filesystem is stat'd and updated sources are passed into the frontend server. This produces an incremental dill based on the updated sources and the state of (2). By construction (1) and (2) are identical files, so this works as expected.

During `flutter attach`, an APK/IPA that has already been built in some other tool/process/session is started on a device. This must contain a dill file (1) from some previous compile. We connect to the observatory and initialize the frontend server from an existing dill file (if it exists)  and recompile all sources into a new dill file (2). For here on out, any time a hot reload is requested, the filesystem is stat'd and updated sources are passed into the frontend server. Unlike `flutter run`, there is no guarantee that (1) and (2) were the same file.

Consider the following sequence of user actions:

1. User edits flutter sources and builds APK, installs on device.
2. User further edits source code.
3. User starts app and runs flutter attach.
4. User requests hot reload, changes from (2) are not observed.

By the time the tool has reached (4), it assumes based on the `flutter run` workflow that the initial compile from the frontend server represents the source of truth. Therefore the hot reload does not result in any changes, since in this case the stat tells us the file was updated prior to the compile.

Fix:
In the case of flutter attach, the first hot reload should assume that every source file has been invalidated. This will significantly slow down the first reload, but will not effect subsequent reloads.

See also: https://github.com/flutter/flutter/issues/37976

cc @zanderso @feinstein

**Comment by zanderso** [comment]
Is it also the case that a sufficiently speedy person (or bot/ide) could modify sources between (1) and (2) during `flutter run`?

**Comment by jonahwilliams** [comment]
Yes, that's a good point. I'll confirm locally but changes after the APK/IPA has been built but before the attach are likely to be lost in the run case as well.

**Comment by jonahwilliams** [comment]
I'm closing this issue because I don't think this is possible to fix in a way that is generally useful. Performing a hot restart to bring things in sync is not particularly expensive, but doing it every time adds a lot of overhead

**Comment by feinstein** [comment]
But wouldn't it be needed only once, after flutter attach has started?
