### ISSUE TITLE
[web] How to integrate Map in flutter web

### ISSUE THREAD

**Issue by Parmendrakumar** [flutter/flutter#38327]
Flutter web does not support google_maps_flutter 0.5.20+2.

Its working fine on Mobile with does not support Flutter Web

**Comment by jld3103** [comment]
Same as #37749. But implementing google maps the same way would be really a lot of effort.

**Comment by BondarenkoStas** [comment]
@Parmendrakumar is the issue still relevant?

**Comment by ShivamSinghania** [comment]
google_maps_flutter plugin doesn't seem to support flutter web yet.
Any updates/plans for this ?

**Comment by yjbanov** [comment]
Deduplicating this issue with https://github.com/flutter/flutter/issues/45292.

If you do not need API compatibility with the mobile plugin, you can use `package:js` to call Google Maps JavaScript library directly and use `HtmlElementView` to embed it in Flutter.
