### ISSUE TITLE
[firebase_messaging] iOS notifications only working while in foreground.

### ISSUE THREAD

**Issue by Klingens13** [flutter/flutter#38336]
After implementation of firebase_messaging with the official documentation and adding the configuration functions with this guide : https://medium.com/flutterpub/enabling-firebase-cloud-messaging-push-notifications-with-flutter-39b08f2ed723 .
onMessage, onResume and onLaunch output also only shows, while app is in foreground. If not in foreground, the notification will be returned as soon as the app is again in foreground. Also linked all onMessage, onResume and onLaunch with the local_notifications plugin. As with the Log Output, notifications only appear while app is in foreground.

Has anyone experienced a similar issue or/and can please help me?

**Comment by athornz** [comment]
This is a known limitation of the firebase messaging plugin. It's explained under the `Receiving Messages` section of the readme: https://github.com/flutter/plugins/tree/master/packages/firebase_messaging

There is a PR open to implement receiving messages when the app is in the background but it's only for Android at this stage: https://github.com/flutter/plugins/pull/1900

I've got a branch of the plugin which implements background messages on both Android and iOS if you want to try that directly: https://github.com/flutter/flutter/issues/32372#issuecomment-514804317

**Comment by Klingens13** [comment]
> This is a known limitation of the firebase messaging plugin. It's explained under the `Receiving Messages` section of the readme: https://github.com/flutter/plugins/tree/master/packages/firebase_messaging
> 
> There is a PR open to implement receiving messages when the app is in the background but it's only for Android at this stage: [flutter/plugins#1900](https://github.com/flutter/plugins/pull/1900)
> 
> I've got a branch of the plugin which implements background messages on both Android and iOS if you want to try that directly: [#32372 (comment)](https://github.com/flutter/flutter/issues/32372#issuecomment-514804317)

Thank you very much for your answer! 

Could you further explain what I have to do to apply the changes you mentioned in your pinned post?
Thanks!

**Comment by kroikie** [comment]
@Klingens13

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1048. Any further collaboration will be done there.

**Comment by mubashirbashir** [comment]
i tried many things but was not not able to make push notification work on ios 13.5.1. I followed the official documentation and uploaded the build on test flight. Strangely i start receiving push notification on resume, on launch as well as on message. Also working fine with local notification plugin.

**Comment by Klingens13** [comment]
> i tried many things but was not not able to make push notification work on ios 13.5.1. I followed the official documentation and uploaded the build on test flight. Strangely i start receiving push notification on resume, on launch as well as on message. Also working fine with local notification plugin.

@mubashirbashir Sorry I forgot to mention this here but I published a fix over on stackoverflow : https://stackoverflow.com/questions/57641550/firebase-messaging-no-notifications-coming-through/58763480#58763480
