### ISSUE TITLE
[web] cupertino/refresh.dart compiler error in DDC

### ISSUE THREAD

**Issue by ferhatb** [flutter/flutter#38352]
## Steps to Reproduce

transitionNextState() method in cupertino/refresh.dart generates a reference to a label called 'done' which doesn't exist. refresh_test fails due to a call to this method.

**Comment by vsmenon** [comment]
@ferhatb - internal (DDC) or external (DDK)?  

DDK has bug fixes on continue-to-label cases that are broken in DDC.

E.g., the following works correctly in DDK:
```dart
void main() {
  int x = 0;

  switch (x) {
    case 0:
      print(0);
      continue done;
    case 1:
      print(1);
      continue done;
    done:
    default:
      print('done');
  }
}
```

but generates `SyntaxError: Undefined label 'done'` in DDC.

**Comment by ferhatb** [comment]
Internal. Test failure. We have a workaround if this is internal only.

**Comment by vsmenon** [comment]
Should be internal only.  The code pattern in `refresh.dart` is more or less the same.

We should move you onto DDK internally as soon as possible.  @jakemac53

**Comment by vsmenon** [comment]
Closing - works with DDK.
