### ISSUE TITLE
Hello world example doesn't run on iOS device

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#3835]
## Steps to Reproduce

`~/examples/hello_world $ flutter run -d <real_device_id>`

#### Relevant error:
> error: CFBundleIdentifier 'io.flutter.example.hello_world' contains illegal character '_' invalid bundle identifier 'io.flutter.example.hello_world'

#### Verbose log output:
[flutter_run_output.txt](https://github.com/flutter/flutter/files/257975/flutter_run_output.txt)

## Additional notes

This works on the simulator

**Comment by eseidelGoogle** [comment]
We had this long ago, @devoncarew fixed `flutter create` to warn about this iirc?

**Comment by chinmaygarde** [comment]
Yeah, this seems to be a regression. Was fixed a long time ago.

**Comment by devoncarew** [comment]
We're stripping out the chars we don't like (https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/create.dart#L196). Not sure why `'_'` isn't caught in this case.

**Comment by chinmaygarde** [comment]
@tvolkert figured it out. The "." is not escaped in that regex.
