### ISSUE TITLE
How can I embed CalendarView written in Kotlin?

### ISSUE THREAD

**Issue by laxxxguy** [flutter/flutter#38360]
I am trying to implement [Android library](https://github.com/kizitonwose/CalendarView) written in Kotlin via platform channels. I don't know how to achieve this. I have chosen this library because it is highly customizable and there is not any Flutter library advanced like this. So I thought may be I can implement this via platform channels like `admob_flutter` plugin. I asked this question on Stackoverflow but there is no answer yet. I would be appreciated if you can give me any ideas, sample codes. (or some Flutter library which is like that)

[Here is my question on Stackoverflow](https://stackoverflow.com/questions/57450032/embedding-kotlin-library-with-layout-xml-file-in-flutter-with-platform-channels)

**Comment by jld3103** [comment]
The Google Maps plugin uses a platform view: https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
