### ISSUE TITLE
Could not create service of type DefaultUserHomeScopedCompileCaches using UserHomeScopeServices.createCompileCaches().

### ISSUE THREAD

**Issue by wecloud2008** [flutter/flutter#38383]
C:\Users\02\AndroidStudioProjects\flutter_app>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.239], locale en-US)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.36.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.

C:\Users\02\AndroidStudioProjects\flutter_app>flutter run
Launching lib/main.dart on MI 8 in debug mode...
Initializing gradle...                                              1.0s
Resolving dependencies...                                          17.5s

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not create service of type DefaultUserHomeScopedCompileCaches using UserHomeScopeServices.createCompileCaches().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         4.1s
Gradle task assembleDebug failed with exit code 1

C:\Users\02\AndroidStudioProjects\flutter_app>./gradlew build
'.' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\02\AndroidStudioProjects\flutter_app>gradlew build
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :buildEnvironment

------------------------------------------------------------
Root project
------------------------------------------------------------

classpath
No dependencies

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 27s
1 actionable task: 1 executed
C:\Users\02\AndroidStudioProjects\flutter_app>flutter run
Launching lib/main.dart on MI 8 in debug mode...
Initializing gradle...                                              0.8s
Resolving dependencies...                                           4.8s

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not create service of type DefaultUserHomeScopedCompileCaches using UserHomeScopeServices.createCompileCaches().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         3.4s
Gradle task assembleDebug failed with exit code 1

**Comment by wecloud2008** [comment]
JDK 1.8.0_221

flutter.gradle content

buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
}

**Comment by wecloud2008** [comment]
resolved

https://dev.szpost.com/?p=71

**Comment by IQBigBang** [comment]
Same issue here, link posted by @wecloud2008 not working.

**Comment by wecloud2008** [comment]
@IQBigBang 
http://dev.szpost.com/?p=71
