### ISSUE TITLE
I get an error when I installing the dependencies

### ISSUE THREAD

**Issue by PythonNaChen** [flutter/flutter#38399]
Running "flutter pub get" in flutter_gallery...                 
Because every version of flutter_goldens from sdk depends on string_scanner 1.0.4 and flutter_gallery depends on string_scanner ^1.0.5, flutter_goldens from sdk is forbidden.

So, because flutter_gallery depends on flutter_goldens any from sdk, version solving failed.
pub get failed (1)
exit code 1

**Comment by jld3103** [comment]
Change the version of string_scanner in flutter_gallery to 1.0.4

**Comment by PythonNaChen** [comment]
> Change the version of string_scanner in flutter_gallery to 1.0.4

Compiler message:
lib/demo/material/banner_demo.dart:50:27: Error: Method not found: 'MaterialBanner'.
    final Widget banner = MaterialBanner(
                          ^^^^^^^^^^^^^^
lib/demo/material/banner_demo.dart:50:27: Error: The method 'MaterialBanner' isn't defined
for the class '_BannerDemoState'.
 - '_BannerDemoState' is from 'package:flutter_gallery/demo/material/banner_demo.dart'
 ('lib/demo/material/banner_demo.dart').
Try correcting the name to the name of an existing method, or defining a method named
'MaterialBanner'.
    final Widget banner = MaterialBanner(
                          ^^^^^^^^^^^^^^
Compiler failed on
/Users/lucifel/Downloads/flutter-master/examples/flutter_gallery/lib/main.dart
Error launching application on iPhone Xʀ.

**Comment by ZKXSparke** [comment]
I have this problem too，but the compiler message shows “**### Because flutter_gallery depends on flutter_goldens any from sdk which depends on quiver 2.0.3, quiver 2.0.3 is required.
So, because flutter_gallery depends on quiver 2.0.5, version solving failed.
pub upgrade failed (1)
Process finished with exit code 1**”
after I changed to 1.0.4.
If I change the version number according to the information, there will be another problem with the new SDK version.These problems will make me change the version number to a smaller.

**Comment by ZKXSparke** [comment]
> I have this problem too，but the compiler message shows “**### Because flutter_gallery depends on flutter_goldens any from sdk which depends on quiver 2.0.3, quiver 2.0.3 is required. So, because flutter_gallery depends on quiver 2.0.5, version solving failed. pub upgrade failed (1) Process finished with exit code 1**”
> after I changed to 1.0.4.
> If I change the version number according to the information, there will be another problem with the new SDK version.These problems will make me change the version number to a smaller.

**I solved this, just**
My environment variable sets the Chinese mirror address，delete it and run **flutter channel dev**,**flutter docter**。

**Comment by BondarenkoStas** [comment]
@PythonNaChen is it still relevant?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
