### ISSUE TITLE
Windows builds aren't using GOMA since https://github.com/flutter/engine/pull/9319

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#38396]
See https://github.com/flutter/engine/pull/9319

On LUCI, our builds have drastically slowed down since that roll of buildroot. I have not tested on a local windows machine yet to verify.

/cc @tvolkert @chinmaygarde @cbracken @jason-simmons

**Comment by chinmaygarde** [comment]
This has been fixed.
