### ISSUE TITLE
TextField hintText not vertical center when using flutter_localizations for Chinese

### ISSUE THREAD

**Issue by figbin** [flutter/flutter#38407]
When I using "flutter_localizations" for Chinese TextField hintText not vertical center
pubspec.yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

here is my localization code
```
MaterialApp(
    localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
    ],
    supportedLocales: [
        Locale('en'),
        Locale.fromSubtags(languageCode: 'zh'),
    ],
```
here is my TextField code:
```
    Padding(
      padding: const EdgeInsets.all(8.0),
      child: TextField(
        textInputAction: TextInputAction.search,
        decoration: InputDecoration(
          contentPadding: EdgeInsets.symmetric(vertical: 10.0, horizontal: 10),
          border: OutlineInputBorder(),
          hintText: "输入要搜索的内容", //enter your keywords
          hintStyle: TextStyle(color: Color(0xFF999999), fontSize: 10),
        ),
        style: TextStyle(color: Color(0xFF444444), fontSize: 14.0),
      ),
    );
```

I have try to remove the MaterialApp Locale code `Locale.fromSubtags(languageCode: 'zh'),` and work correct.

picture1: using LanguageCode: zh
![](https://images2.imgbox.com/c7/68/CQ3ayq63_o.png)

picture2: remove LanguageCode zh
![](https://images2.imgbox.com/c3/2a/EocvV3BO_o.png)

**Comment by figbin** [comment]
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.8.3, on Mac OS X 10.14.6 18G87, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by muyuballs** [comment]
a worst solutions:
create a Localizations extends MaterialLocalizations  like this:
```dart
class ALocalizations extends MaterialLocalizations{
 ALocalizations._withAnother(this.another);
 MaterialLocalizations another;
// implements property and method ,like this:
@override
  String get alertDialogLabel => another.alertDialogLabel;
....
//important
@override
  ScriptCategory get scriptCategory => ScriptCategory.englishLike; //another.scriptCategory;
}
```
create a delegate linke this:
```dart
class ADelegate extends LocalizationsDelegate<MaterialLocalizations>{
...
  @override
  Future<MaterialLocalizations> load(Locale locale) async {
    return ALocalizations._withAnother(await GlobalMaterialLocalizations.delegate.load(locale));
  }
...
}
```
and ,then put it in MaterialApp.localizationsDelegates
```dart
MaterialApp(
localizationsDelegates:<LocalizationsDelegate<dynamic>>[
...
ADelegate (),
...
]
)
```

**Comment by githubhai** [comment]
试试 TextField > style > textBaseline: TextBaseline.alphabetic

**Comment by unclexiao** [comment]
@githubhai Thank you very much , and it worked

**Comment by zhangranran** [comment]
> 试试 TextField > style > textBaseline: TextBaseline.alphabetic

如果hintText设置为中文，第一次进入页面没问题，多次进入又会出问题。

**Comment by Quanhua-Guan** [comment]
> 试试 TextField > style > textBaseline: TextBaseline.alphabetic
this solution works with flutter 1.9.1.hotfix6
not work with flutter: 1.12.13.hotfix5

Something interesting I get from testing around (iPhone simulator, iOS 13.3):
_**TextField height (using Container to control) should be >= (greater then or equal with) TextField.style.fontSize * 3.**_

e.g.

```
Container(
      height: 48, /// 48 = 16 * 3, if set value < 48, the vertical position is not centered
      child: TextField(
        style: TextStyle(
          fontSize: 16,
          textBaseline: TextBaseline.alphabetic,
        ),
        decoration: InputDecoration(
          hintText: hintText,
          border: InputBorder.none,
        ),
      ),
    );
```

This might be a workaround .

**Comment by Quanhua-Guan** [comment]
> > 试试 TextField > style > textBaseline: TextBaseline.alphabetic
> 
> this solution works with flutter 1.9.1.hotfix6
> not work with flutter: 1.12.13.hotfix5
> 
> Something interesting I get from testing around (iPhone simulator, iOS 13.3):
> **1.**
> _**TextField height (using Container to control) should be >= (greater then or equal with) TextField.style.fontSize * 3.**_
> 
> e.g.
> 
> ```
> Container(
>       height: 48, /// 48 = 16 * 3, if set value < 48, the vertical position is not centered
>       child: TextField(
>         style: TextStyle(
>           fontSize: 16,
>           textBaseline: TextBaseline.alphabetic,
>         ),
>         decoration: InputDecoration(
>           hintText: hintText,
>           border: InputBorder.none,
>         ),
>       ),
>     );
> ```
> 
> **2.**
> Another solution : just don't set the height of TextField, and let it decides it self. (**the final height of TextField is equal to 3 * TextField.style.fontSize**)
> 
> ```
> Container(
>       //height: 48, /// get rid of this line of code, works
>       child: TextField(
>         style: TextStyle(
>           fontSize: 16,
>           textBaseline: TextBaseline.alphabetic,
>         ),
>         decoration: InputDecoration(
>           hintText: hintText,
>           border: InputBorder.none,
>         ),
>       ),
>     );
> ```
> 
> Hope this might help.

Try to change  'TextField -> style -> height ' to adjust the vertical position.

**Comment by ossgoossgo** [comment]
Add enabledBorder and focusedBorder can fix it
enabledBorder: OutlineInputBorder(
                              borderSide: BorderSide(color: Colors.transparent),
                            ),
                            focusedBorder: OutlineInputBorder(
                              borderSide: BorderSide(color: Colors.transparent),
                            ),
----------------------
copy this code
TextField(
                        decoration: InputDecoration(
                            contentPadding:
                                EdgeInsets.symmetric(horizontal: 10),
                            enabledBorder: OutlineInputBorder(
                              borderSide: BorderSide(color: Colors.transparent),
                            ),
                            focusedBorder: OutlineInputBorder(
                              borderSide: BorderSide(color: Colors.transparent),
                            ),
                            errorBorder: InputBorder.none,
                            disabledBorder: InputBorder.none,
                            filled: true,
                            fillColor: Colors.white,
                            hintText: "請輸入訂單編號",
                            hintStyle: TextStyle(
                                color: Colors.grey,
                                fontSize: 14,
                                height: 1.0)))
