### ISSUE TITLE
Getting **in tgkill** Real-time crashes from Play Console

### ISSUE THREAD

**Issue by rohansohonee** [flutter/flutter#38406]
## Play Console crash report

- **Device:** Samsung Galaxy S6 (zerofltebmc), Android 7.0.
- **Link:** Followed these [steps](https://flutter.dev/docs/deployment/android) to build a release app bundle for Google Play Store.
- **Application:** Word Game Solver (rohansohonee.wordgamesolver).
```
backtrace:
  #00  pc 000000000006b5b4  /system/lib64/libc.so (tgkill+8)
  #01  pc 0000000000068a50  /system/lib64/libc.so (pthread_kill+64)
  #02  pc 0000000000023f68  /system/lib64/libc.so (raise+24)
  #03  pc 000000000001c9ec  /system/lib64/libc.so (abort+52)
  #04  pc 000000000001ded8  /data/app/rohansohonee.wordgamesolver-1/split_config.arm64_v8a.apk
```
## Flutter Doctor Summary
``` console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.267], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.37.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by VladyslavBondarenko** [comment]
Hi @rohansohonee 
I see there's an open issue addressing the case you described.
Please follow up on [#24286](https://github.com/flutter/flutter/issues/24286).
although it's newer, it's active.
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
