### ISSUE TITLE
It's surprising that DefaultTextStyle does not inherit color

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#3842]
I'm not sure if this is a bug or intended behavior. This was my first time using DefaultTextStyle. I was using it to increase the font size across two adjacent text widgets. It surprised me that it changed the text to white (from the theme default of black87). It would be nice if I could use `new DefaultTextStyle(style: new TextStyle(fontSize: 22.0), child: ...)` without specifying a color in the TextStyle.

**Comment by abarth** [comment]
You probably want the `DefaultTextStyle.inherit` constructor:

http://docs.flutter.io/flutter/widgets/DefaultTextStyle/DefaultTextStyle.inherit.html

We should probably give the other DefaultTextStyle constructor a scarier name like `DefaultTextStyle.explicit`.  We could also assert that the style you give to `DefaultTextStyle.explicit` doesn't have the `inherit` bool set.   /cc @Hixie

**Comment by drewwarren** [comment]
Ahh, now I see you added that 4 days ago :) I'm wondering if I had been up to date with master if I would have found it.

**Comment by abarth** [comment]
The docs for http://docs.flutter.io/flutter/widgets/DefaultTextStyle/DefaultTextStyle.html point to it, but it's probably better if we're more practive about guiding people towards the constructor they want.  (There are use cases for both constructors.)

**Comment by Hixie** [comment]
> We should probably give the other DefaultTextStyle constructor a scarier name like `DefaultTextStyle.explicit`.  We could also assert that the style you give to `DefaultTextStyle.explicit` doesn't have the `inherit` bool set. 

Agreed on both counts.
