### ISSUE TITLE
HarmonyOS Support

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#38437]
## Use case
Adding a new OS to the flutter family

**Comment by tvolkert** [comment]
@YazeedAlKhalaf thanks for the issue!  At this time, we have no plans to build stock support for HarmonyOS, but Flutter's architecture is such that this support could be built on top of Flutter's embedder API. See https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedders if you're interested in experimenting with this.

**Comment by tikodrack** [comment]
most respectfully I _suggest this issue should be reopened_...

indeed, developers who use flutter are absolutely interested in reaching larger markets, which now also include **Hongmeng OS** (Harmony) besides **Android**, **iOS** and the upcoming **Fuchsia**...

please, please, please do consider making **Hongmeng Flutter deployment** available also...

**THANKS !**

**Comment by YazeedAlKhalaf** [comment]
Any updates on the support or untill now nothing?

**Comment by bfazeli** [comment]
Any updates?

**Comment by handicraftsman** [comment]
> most respectfully I _suggest this issue should be reopened_...
> 
> indeed, developers who use flutter are absolutely interested in reaching larger markets, which now also include **Hongmeng OS** (Harmony) besides **Android**, **iOS** and the upcoming **Fuchsia**...

Yeah. Providing support for very experimental Fuchsia but killing off Harmony OS which is almost done, already works on some devices, and will get released in 2021 is actually unfair.

**Comment by jayadevanraja** [comment]
@handicraftsman @tikodrack @YazeedAlKhalaf 
Please share your knowledge and ideas on these:
(1) Will Android apps built for EMUI work for HarmonyOS now?
(2) Does Flutter support HMS at least as much as GMS?

**Comment by liuhong1happy** [comment]
+1

**Comment by YazeedAlKhalaf** [comment]
@jayadevanraja 
For question number 1 I don't know
For question number 2 I think you mean like this: [https://pub.dev/publishers/developer.huawei.com/packages](https://pub.dev/publishers/developer.huawei.com/packages). Huawei added a lot of packages to flutter that can be alternatives to google's

**Comment by jayadevanraja** [comment]
@YazeedAlKhalaf
Thanks.

**Comment by YazeedAlKhalaf** [comment]
Huawei is transitioning from Android to Harmony OS.
[https://www.xda-developers.com/huawei-transition-from-android-harmony-os-beta/](https://www.xda-developers.com/huawei-transition-from-android-harmony-os-beta/)

They even have a full IDE built on IntelliJ IDEA that will be released soon. And they have developer program.

**Comment by jayadevanraja** [comment]
@YazeedAlKhalaf 
That is awesome.

The obstacle I (and most likely most people) face is that, I don't know Chinese.  Hopefully they translate the documentation to English, although the domination by English language in the field of programming should never be supported.

**Comment by colinshin** [comment]
Harmony os 2.0 beta has been released just now, it's time to considering  to add harmonyos to the support program.

**Comment by WoodpeckerBaby** [comment]
I think Huawei will fork and release an official backward compatible version of Flutter that natively includes all the support for HMS and HarmonyOS.

**Comment by WoodpeckerBaby** [comment]
Flutter is created by Google to upend Apple’s iOS. I can understand why Google wouldn’t support HarmonyOS, which is the most credible competitor to Android-iOS duopoly.

**Comment by Sunbreak** [comment]
Harmony Java SDK and JS SDK result in different packages
Java SDK runs via Android-View-like pipeline.
JS packages runs via Flutter render pipeline, i.e. a striped Skia and some Flutter native render logic.

The latter is more popular and mature internally

**Comment by Shuliyey** [comment]
https://tech.meituan.com/2021/01/22/flutter-in-harmonyos.html 美团meituan got flutter working on HarmonyOS beta

**Comment by ILAgent** [comment]
As I know android apps run on Harmony. Why wouldn't android flutter apps run?

**Comment by kekko7072** [comment]
1

**Comment by NetFly-VPN** [comment]
+1

**Comment by colinshin** [comment]
+1

**Comment by gfb-47** [comment]
The issue is in chinese, do we have any updates on this?

**Comment by hetao29** [comment]
+1
