### ISSUE TITLE
firebase_messaging problems on android and ios 

### ISSUE THREAD

**Issue by eparenti76** [flutter/flutter#38430]
Hy, first of all sorry for my english.

I have some problems using firebase_messaging plugin.

On Android:

In the emulator work well. Push notifications work when app is terminated, foreground and background, but when I install my app on my device Asus ZenPhone 5 and the app is terminated push notifications not work. Documentation says that when the app is terminated only Notification works.

OK, I Use FirebaseAdmin library on C# and I try exclude data and push only simple notification but not work.
I try from firebase console but nothing change.

```
Dictionary<string, string> data = new Dictionary<string, string>();
        data.Add("click_action", "FLUTTER_NOTIFICATION_CLICK");
        data.Add("istanza", istanza);
        data.Add("username", username);
        data.Add("oggetto", oggetto);
        data.Add("id", id);

        // See documentation on defining a message payload.
        var message = new FirebaseAdmin.Messaging.Message();

        message.Token = token;
        //message.Data = data;
        message.Notification = new Notification();
        message.Notification.Title = title;
        message.Notification.Body = body;


        //non mi interessa aspettare l'esito
        FirebaseMessaging.DefaultInstance.SendAsync(message);
```
On Android when app is teminated this notifications not work and not work even i add data payload.
The strange is that in emulator work all fine even i add data payload.

On IOS:

I configure all in firebase console and app store.

In IOS push notification works well when the app is in background and terminated, but when is in foreground not work.
The strange is that id I install the .ipa manually on my IPhone, push notifications work only if the app is foreground.
I think is normally that not work push notification if I install my app manually but the strange is that works in foreground and the playstore installation not works in foregrand.

Can you help me?
Thanks

**Comment by kroikie** [comment]
@eparenti76

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1047. Any further collaboration will be done there.
