### ISSUE TITLE
[google_maps] Generate Image/Screenshot

### ISSUE THREAD

**Issue by julianmarangoni** [flutter/flutter#38445]
## Use case

Right now im using static maps to generate images by getting all the coordinates of all the polylines, polygons and markers on my map and creating a url link to static maps, and then download the generated image.

The issue with this is having to rely on the static maps api and not being able to use custom markers from the app.

I'v tried using the screenshot plugin (https://pub.dev/packages/screenshot), however, it just captures white space.

## Proposal
I would like to be able to capture whatever is visible on the map (including markers, polylines and polygons), and generating an image/screenshot.

**Comment by pinkeshAubergine** [comment]
I am facing same issue. Looking forward to your quick help.

**Comment by julianmarangoni** [comment]
Any chance of adding a "severe: customer critical" label? Planning on releasing app by end of year and would rather not rely on using static maps.

**Comment by Hemedy** [comment]
Any help on this?

**Comment by ndhbr** [comment]
Why did you close this issue? Did you find any solution? I need this urgently @julianmarangoni

**Comment by julianmarangoni** [comment]
Hi @ndhbr .

This issue was closed as a function was added to flutter to generate screenshots:
https://github.com/flutter/plugins/commit/03182d26309a05f483b58d6c5f29946e066c94f5

**Comment by ndhbr** [comment]
@julianmarangoni aaah, perfect! Thanks.
