### ISSUE TITLE
Making an IDE for Flutter

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#38440]
**The Idea**

My idea is about making an IDE for Flutter like the Android Studio, maybe name it Flutter Studio. Someone in the community made a website for this purpose but still, the website is so simple to be an IDE.

**Pros**

- Making Flutter easier for everybody, even it is easy now.
- The IDE would make updates reach faster
- The IDE would give developers the feel of an ecosystem to work for Flutter.
-  Anyone who likes the idea, you could contribute in this and help Flutter reach more people.

**Cons**
- I think there is no cons for it except maybe the time it will consume from the team, but will help people.

**Notes**
Don’t judge me depending on this idea, I am 15 years old so hope you like it.

**Comment by christopherfujino** [comment]
@YazeedAlKhalaf do you have ideas about specific features that Android Studio with the Flutter plugin lacks that you would like to see in a specific Flutter IDE?

**Comment by Solido** [comment]
It is a very difficult task to build an IDE for a specific tech.
Most of the time you build on existing one adding features that you need, this is the case with Flutter that build on top of IntelliJ and VSCode.

For a configurable Widget Builder this guy is working on something where you'll be able to join soon : https://twitter.com/norbertkozsir/status/1144141261374443520

**Comment by YazeedAlKhalaf** [comment]
I have some ideas:

* making an IDE will help make Flutter sdk more stronger and easier to download, update, remove, fix, etc...
* making an IDE (Features):
- compiling will be easier with a click of a button, maybe selecting which platforms to compile for, since Flutter will be used for all platforms.
- adding a drag and drop feature which will make Flutter so easy to use, btw it is easy now but will make it easier.
- it will make Flutter an independent environment rather than installing many apps, it will be the Flutter Studio(name example) installer hat will take care of everything you need to get started with Flutter.

And it must be a light weight one, not so heavy like Android Studio

Just some ideas for contribution!

Hope it helps!

**Comment by tvolkert** [comment]
@YazeedAlKhalaf thank you very much for the suggestion!  At this time, we're not considering building a Flutter IDE (though we do maintain the Flutter plugins to IntelliJ And VSCode), so I'm going to close this issue.  If you decide to undertake such a project yourself, we'd love to hear about it once it's done!

**Comment by YazeedAlKhalaf** [comment]
Any Updates?

**Comment by christopherfujino** [comment]
> Any Updates?

@YazeedAlKhalaf: Tvolkert's comment from Sep 5, 2019 still applies, the officially supported ways to develop Flutter apps is through the plugins for IntelliJ and VSCode, which I think meets most of the goals that a dedicated IDE would, without having hte increased maintenance of creating a whole IDE.

**Comment by YazeedAlKhalaf** [comment]
Okay, thanks! 🎈😊
