### ISSUE TITLE
Using macos catalina beta 5, I cannot run flutter doctor in terminal!

### ISSUE THREAD

**Issue by railsudemydale** [flutter/flutter#38449]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```
![Screen Shot 2019-08-13 at 11 48 02 am](https://user-images.githubusercontent.com/18106944/62956426-ed0e0400-bdc0-11e9-90e8-b60278c9324d.png)
![Screen Shot 2019-08-13 at 11 54 44 am](https://user-images.githubusercontent.com/18106944/62956613-437b4280-bdc1-11e9-91ca-9ec29220969c.png)

**Comment by christopherfujino** [comment]
Hello, thanks for filing this issue! I am currently working on this, and it is being tracked on [this issue](https://github.com/flutter/flutter/issues/36714). I am closing this issue as a duplicate, so please subscribe to the other issue for updates. tl;dr at this time the workaround is disabling gatekeeper altogether on Catalina, via `sudo spctl --master-disable`.

**Comment by phoelapyae69** [comment]
I'm facing with the same problem. I cannot run the command "flutter run". I got the error. I think snapshot folder is something wrong.
