### ISSUE TITLE
cloud_functions - Error when using useFunctionsEmulator(origin:)

### ISSUE THREAD

**Issue by matuella** [flutter/flutter#38452]
The error is not with the function per se, but it happens when I change the origin of the lib to localhost - so I can actually develop locally. I'm not quite sure what's the purpose of the `useFunctionsEmulator(origin:)` as, in my perspective, this just changes the `_origin` variable - which is not enough to be able to call functions locally, given the current implementation.

To structure the test, I create this `HttpsCallable`:
```dart
final HttpsCallable _callableFunc = CloudFunctions.instance.useFunctionsEmulator(origin: "http://localhost:5000").getHttpsCallable(functionName: "callableFunction");
```

While running this - in cloud functions - using `firebase emulators:start`:
```typescript
export const callableFunction = functions.https.onCall((data, context) => {
  console.log("Incoming request...")

  return setTimeout(() => { 
    if (context.auth) {
      console.log("Authenticated request")
      return { response: "Authenticated request!" }
    } else {
      console.log("Unauthenticated request")
      return { response: "Unauthenticated request!" }
    }
  }, 1000)
})
```

Then, in the tests below, I just call: `_callableFunc.call()`.

## Quick tests

When testing in the iOS platform, we can see that it throws multiple different errors:
1. When changing the origin to: **`http://localhost:5000` or `http://{my_local_address}:5000`**, where `my_local_address` is just the my localhost address, it throws:
```
    "LocalDataTask <EBB99248-FD9A-44E1-B851-0A52A37FED22>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <EBB99248-FD9A-44E1-B851-0A52A37FED22>.<1>, NSUnderlyingError=0x6000028b14a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1022 "(null)"}} [-1022]
flutter: Exception: Unable to call function callableFunction
```

- The specific `kCFErrorDomainCFNetwork` with code `1022` [means "App Transport Security disallowed a connection because there is no secure network connection"](https://developer.apple.com/documentation/foundation/1508628-url_loading_system_error_codes/nsurlerrorapptransportsecurityrequiressecureconnection?language=objc) - let's discuss that later.

2. Now, when changing the origin to: **`https://localhost:5000` or `https://{my_local_address}:5000`**, where `my_local_address` is just the my localhost address, it throws:
```
    "LocalDataTask <9709A701-FB6F-4A7F-AC35-310E9D3A5144>.<1>"
), NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://10.41.200.212:5001/authenticatedcallablefirebase/us-central1/callableFunction, NSUnderlyingError=0x6000028c99e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValu [<decode: missing data>]
flutter: Exception: Unable to call function callableFunction
```

- `kCFErrorDomainCFNetwork` with code `1200` [means "An attempt to establish a secure connection failed for reasons that can’t be expressed more specifically."](https://developer.apple.com/documentation/foundation/1508628-url_loading_system_error_codes/nsurlerrorapptransportsecurityrequiressecureconnection?language=objc), which is quite obvious because localhost is not in `https`.

So, if I understood correctly, the plugin is simply changing the origin string and does not actually changes its behavior to "be able to call unsecure" - here, it means localhost - connections, thus throwing these errors - making me wonder if this function is not actually implemented, just exposed there.

Also, for reference, you can see the lib implementation:
```dart
  /// Changes this instance to point to a Cloud Functions emulator running locally.
  ///
  /// @param origin The origin of the local emulator, such as "//10.0.2.2:5005".
  CloudFunctions useFunctionsEmulator({@required String origin}) {
    _origin = origin;
    return this;
  }
```

Quick note: I am not assuming anything here, I've just began in the flutter ecosystem and this is just my two cents on what's going on with my problem - given the fact that I've seen the issue here #35125

**Comment by densa** [comment]
Emulator use http. iOS rejected any request to http allow only https.
So you need add into ios/runner/Info.plist 

`<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>`
and then run `flutter run` again

**Comment by matuella** [comment]
That was it - thanks @densa
