### ISSUE TITLE
[firebase_dynamic_links v0.5] - Dynamic link always null when link is pressed in Gmail App on IOS

### ISSUE THREAD

**Issue by Baileypollard** [flutter/flutter#38455]
## Steps to Reproduce

1. Use the example project provided here https://github.com/flutter/plugins/tree/master/packages/firebase_dynamic_links/example
2. Send the dynamic link to a gmail account
3. Open the link in the Gmail App on an IOS device
4. The link will be null.
5. Send another link to the same gmail
6. Open safari/chrome, log into gmail.
7. Click the link, the link will be valid

## Logs

```
No real logs, just a log statement printing out the value of the dynamic link which is indeed null when click from gmail.
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E226, locale
    en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by Baileypollard** [comment]
Anyone else experiencing this issue?

**Comment by PerLycke** [comment]
@Baileypollard Are you experiencing this only when clicking the link in Gmail? It works fine if you paste it into the notes app and open it from there?

**Comment by Baileypollard** [comment]
@PerLycke Yes, specifically the Gmail App on IOS. If I open gmail in safari/chrome the link works fine. If it helps any, when clicking the link from gmail it successfully opens the app but when getting the link programatically it returns null. The same code works for android perfectly.

**Comment by PerLycke** [comment]
No not really for that specific issue. I was experiencing some general issues with links not opening for some users, but it turned out they were using a VPN which prevented links from opening correctly due to their setup.

For the Gmail-specific issue, I actually have no idea :/ sorry about that

**Comment by kroikie** [comment]
@Baileypollard

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1125. Any further collaboration will be done there.
