### ISSUE TITLE
[google_sign_in] Error on google play release

### ISSUE THREAD

**Issue by marvin-42** [flutter/flutter#38451]
Hi. I just deployed my app which use google_sign_in plugin. I checked on debug and works fine, I build apk and deployed to device also works fine, but after deploy to google play when i try to sign in i've exception:

`type '_InternalLinkedHashMap<String, dynamic> is not a subtype of type 'String'`

**Comment by BondarenkoStas** [comment]
@marvin-42 Can you please provide your ```flutter doctor -v``` output, as well as some code example to be sure to reproduce the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
