### ISSUE TITLE
MediaQuery viewPadding inconsistent

### ISSUE THREAD

**Issue by Kavantix** [flutter/flutter#38465]
The viewPadding of mediaQuery is currently not consistent, for instance it changes when the keyboard is shown.
This is caused by `removePadding` and `removeViewInsets` having a side effect on the viewPadding, even if all the remove booleans are false.

For instance remove padding has the following code: 
```dart
      viewPadding: viewPadding.copyWith(
        left: math.max(0.0, viewPadding.left - padding.left),
        top: math.max(0.0, viewPadding.top - padding.top),
        right: math.max(0.0, viewPadding.right - padding.right),
        bottom: math.max(0.0, viewPadding.bottom - padding.bottom),
      ),
```

This does not check whether it should remove any padding from any of the sides, so the only case the viewPadding has a value is when the corresponding side of the padding happens to be zero (which happens when the keyboard is shown)

In my opinion`viewPadding` should never be affected by `removePadding` or `removeViewInsets`.

**Comment by shihaohong** [comment]
Could you share a reproducible case displaying the issue you're facing? It's hard to tell from just the description what the undesired behavior is.

**Comment by Kavantix** [comment]
```dart
final media1 = MediaQuery.of(context).copyWith(
  padding: EdgeInsets.all(8.0);
  viewPadding: EdgeInsets.all(8.0);
); // Media1 viewpadding: (8.0, 8.0, 8.0, 8.0) 
final media2 = media1.removePadding(
  removeBottom: false,
  removeLeft: false,
  removeRight: false,
  removeTop: false,
); // Media2 viewpadding: (0.0, 0.0, 0.0, 0.0) but expected: (8.0, 8.0, 8.0, 8.0)
```

The `removePadding` in the code above should do nothing to the mediaquery since all sides are false (which is also the default)
