### ISSUE TITLE
Engine JUnit tests don't support newer SDKs

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#38471]
The JUnit tests are using Robolectric 3.8. As mentioned in [the README](https://github.com/flutter/engine/blob/master/shell/platform/android/test/README.md#why-are-we-using-robolectric-38-when-robolectric-4-is-current) Robolectric 4+ uses the AndroidX libraries, and the engine sources use the deprecated android.support ones. See flutter/flutter#23586. However we need to use Robolectric 4+ in order to test SDK 28+ methods. Currently the tests are compiling with SDK 29, but they only have the option to use SDK 16 at runtime. Just recently @shihaohong needed this to be able to test some SDK 29 specific code.

If we want to be able to test any code paths that use the new SDK 29 methods we'll need to upgrade Robolectric and any of its affected deps to the latest 4+ version and then add the SDK 29 android-all robolectric jar to our runtime dependencies. This may also require running Jetifier on `flutter.jar` after it's compiled and before the tests are run in order to avoid any AndroidX incompatibilities. I suspect we may be able to get away without using Jetifier in the immediate short term, but it would probably end up becoming a long term problem whenever we needed to put a class using `android.support` under test for the first time.

/cc @matthew-carroll @dnfield

**Comment by mklim** [comment]
This is blocking flutter/flutter#32748, so landing at least flaky non-Jetified support in the short term is important.

**Comment by matthew-carroll** [comment]
@mklim do you have bandwidth to try this out?

**Comment by mklim** [comment]
@matthew-carroll yeah, I'm looking into it now.

**Comment by mklim** [comment]
I have a rough patch implementing this up at mklim/engine@9392080. However the new version does have some deprecation warnings that I'm not seeing a way to fix without using Gradle. Going to try to dig into fixing that before landing the patch.

**Comment by mklim** [comment]
So it's not as simple as I thought. The above patch isn't actually _running_ the tests on SDK 29. JUnit reports that the cases run and counts them, but nothing in the SDK 29 cases actually executes. They're being silently skipped but still tallied in the total "Tests run" count and treated as "OK" for some reason.

In part this looks like this it has to do with Robolectric 4.3 deprecating "legacy" resources and requiring "binary" resources for SDK 29. Up until this point our tests haven't been using any resources at all. If I compile a basically empty binary from the engine's AndroidManifest.xml with AAPT2 and point the tests at it using a jar containing a [ `com/android/tools/test_config.properties` config file](http://robolectric.org/build-system-integration/), the tests do run but now throw failures saying that API 29 isn't available (same stack trace as robolectric/robolectric#5207).

I've noticed in debugging this that Java 9 is required to run API 29 tests (also going to be a hurdle getting this working in CI), but that on its own is unrelated to the strange API 29 stack trace above. It's not the same message for an API being found but it not finding the jar, at least from my testing with SDK 16. Seems like there's some deeper issue going on.

Still investigating. If something immediately high priority is blocked on this I recommend unfortunately landing the tests as part of a follow up and not blocking on this since there's some unknown unknowns here still with getting SDK 29 up and working.

**Comment by mklim** [comment]
Dug into this some more today but didn't succeed with diagnosing or working around robolectric/robolectric#5207. This is unfortunately blocked until that's either resolved or there's a known fix/workaround for it.

**Comment by mklim** [comment]
[This is unblocked](https://github.com/robolectric/robolectric/issues/5207#issuecomment-541795921):

> sorry for the delay on this issue. Robolectric 4.3.1 was just pushed which should fix this issue.

**Comment by xster** [comment]
I think this is now fixed with https://cs.opensource.google/flutter/engine/+/master:shell/platform/android/embedding_bundle/build.gradle;l=60 and https://github.com/flutter/engine/pull/17996
