### ISSUE TITLE
Implement release mode for Windows

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#38477]
Currently a release build (from the `flutter` tool perspective) is using a debug library build, in JIT mode; the only part that's different is anything at the Runner level (e.g., build flags for the native Runner code).

We should be building and uploading a release build of the engine library, and using that with AOT for [release mode builds](https://flutter.dev/docs/testing/build-modes), as on mobile.

**Comment by stuartmorgan** [comment]
Blocked by #50778

**Comment by GroovinChip** [comment]
I don't really understand why we can't package the contents of the debug runner for release? I read #50778 but I don't understand any of it.

**Comment by stuartmorgan** [comment]
@GroovinChip Neither this issue nor #50778 have anything to do with packaging. They are about implementing Flutter's [release mode](https://flutter.dev/docs/testing/build-modes).

**Comment by GroovinChip** [comment]
Alright, would you be so kind as to point me in the right direction?

**Comment by stuartmorgan** [comment]
There's currently nothing to point you to if your question is about packaging Windows applications.

**Comment by GroovinChip** [comment]
What do you guys envision release mode for Windows being, then? I know UWP is on the roadmap, but wouldn't packaging up an installer exe have merit as well?

**Comment by stuartmorgan** [comment]
@GroovinChip I've already linked to an explanation of what "release mode" means for Flutter, and I've already explained that this issue has nothing to do with packaging. Please stop trying to derail this issue to be about something completely different.

**Comment by Airbus5717** [comment]
Any Dates For this ?
