### ISSUE TITLE
Long delay when building (run) for iOS, print/show a spinner?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3847]
I'm waiting a long time for `flutter run` to complete for iOS, easily over a minute. It's stuck on:

```
~/Code/flutter/examples/flutter_gallery[master*] $ flutter -d 2175 run
Running lib/main.dart on Seth Ladd’s iPod...
Unzipping Xcode project to local directory...
Xcode project created in /Users/sethladd/Code/flutter/examples/flutter_gallery/ios/.

```

Can we print a spinner here? I almost control-c'ed the process, thinking it got stuck.

Thanks!

**Comment by devoncarew** [comment]
Did it eventually finish, and is this an expected amount of time for this step? /cc @chinmaygarde @tvolkert

**Comment by tvolkert** [comment]
@sethladd just to confirm, it's stuck _after_ `Xcode project created in ...`?  It was slow for me yesterday, but definitely not over a minute (more like 15-20 seconds).

**Comment by sethladd** [comment]
> Xcode project created in

was the last thing I saw for a "long time" (1 minute-ish?)

It eventually finished. But I almost canceled it. I think we need to show a spinner.

**Comment by chinmaygarde** [comment]
I have seen on ~45 second delays for AOTC on my old Macbook Air. I am almost done wiring in the dbc in debug mode though. So this should only apply for final deployment.

**Comment by Hixie** [comment]
Are long times building for iOS still an issue? Do we show a spinner?

**Comment by chinmaygarde** [comment]
They should be about as long as Android now for both Debug and release configurations. When this bug was filed, the Xcode project had to be fetched and setup before the precompiler could do its thing (which often took a long time).

**Comment by Hixie** [comment]
Ok I'm going to close this then.
