### ISSUE TITLE
[video_player ] Ability to play local mp3 audio files.

### ISSUE THREAD

**Issue by Sun3** [flutter/flutter#38480]
## Use case

When you try to load a local asset audio file you receive an error that the File is not Found.

Code:
```
    _controller = VideoPlayerController.asset('assets/audios/angelus.mp3')
      ..initialize().then((_) {
        print('VALUE');
      setState(() {});
    });
```

Error:
```
E/ExoPlayerImplInternal(22088): Source error.
E/ExoPlayerImplInternal(22088): com.google.android.exoplayer2.upstream.AssetDataSource$AssetDataSourceException: java.io.FileNotFoundException: flutter_assets/assets/audios/angelus.mp3
```

## Proposal

I would like to request the ability to play local audio files from the Flutter assets folder.

**Comment by lucasvps** [comment]
Same issue here, do you find a way to solve ?

**Comment by iapicca** [comment]
Hi @Sun3  and @lucasvps 
are you still experiencing the issue with the latest version of [video_player](https://pub.dev/packages/video_player)?
Does it occour both on iOS and Android?
Could you please provide your updated  `flutter doctor -v`?
Thank you

**Comment by ChristianKleineidam** [comment]
I can replicate the above error with video_player 0.10.3+3 on Android.

**Comment by Sun3** [comment]
Yes, I am still getting an error in trying to load a local audio assets from the Flutter folder.

Error:
```
I/ExoPlayerImpl( 5287): Init fcb167 [ExoPlayerLib/2.9.6] [generic_x86_arm, AOSP on IA Emulator, Google, 28]
I/ExoPlayerImpl( 5287): Release a32ff89 [ExoPlayerLib/2.9.6] [generic_x86_arm, AOSP on IA Emulator, Google, 28] [goog.exo.core]
D/SurfaceUtils( 5287): disconnecting from surface 0xc4b70008, reason disconnectFromSurface
E/ExoPlayerImplInternal( 5287): Source error.
E/ExoPlayerImplInternal( 5287): com.google.android.exoplayer2.upstream.AssetDataSource$AssetDataSourceException: java.io.FileNotFoundException: flutter_assets/assets/the_angelus.mp3
E/ExoPlayerImplInternal( 5287): 	at com.google.android.exoplayer2.upstream.AssetDataSource.open(AssetDataSource.java:98)
E/ExoPlayerImplInternal( 5287): 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
E/ExoPlayerImplInternal( 5287): 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal( 5287): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal( 5287): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal( 5287): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 5287): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 5287): 	at java.lang.Thread.run(Thread.java:764)
E/ExoPlayerImplInternal( 5287): Caused by: java.io.FileNotFoundException: flutter_assets/assets/the_angelus.mp3
E/ExoPlayerImplInternal( 5287): 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
E/ExoPlayerImplInternal( 5287): 	at android.content.res.AssetManager.open(AssetManager.java:744)
E/ExoPlayerImplInternal( 5287): 	at com.google.android.exoplayer2.upstream.AssetDataSource.open(AssetDataSource.java:79)
E/ExoPlayerImplInternal( 5287): 	... 7 more
I/flutter ( 5287): Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.AssetDataSource$AssetDataSourceException: java.io.FileNotFoundException: flutter_assets/assets/angelus.mp3
```

**Comment by marwan-at-work** [comment]
The same can be said of a URL-based audio files. Not sure if this should be a separate issue

**Comment by timsneath** [comment]
The video_player plugin is not designed for audio file playback, so this is working as intended. 

While there are no plans on the Flutter roadmap for us to create a separate audio player plugin, there are a number of plugins available that support audio and are rapidly growing in maturity, for example https://pub.dev/packages/audioplayers. We'd encourage contributions to that or other audio player plug-ins.

**Comment by Kretin1** [comment]
> The video_player plugin is not designed for audio file playback, so this is working as intended.

AVPlayer on iOS and ExoPlayer on Android both support audio, as evidenced by the "Supported Formats" links you provide. If video_player does not support audio then please consider changing this section of your README where it says it does.

But since both underlying systems support audio, there's really no reason not to support audio with this plugin by making into a general purpose Media Player.

I have been modifying video_player to support mixing multiple audio tracks with optional video. Merely enabling audio is quite trivial. For iOS removing only 3 lines enables audio (without causing problems for video), and so far on Android is playing M4A audio tracks so it shouldn't be difficult for it to play other formats.

iOS change:
```
- (void)sendInitialized {
  if (_eventSink && !_isInitialized) {
    CGSize size = [self.player currentItem].presentationSize;
    CGFloat width = size.width;
    CGFloat height = size.height;

    // The player has not yet initialized.
//    if (height == CGSizeZero.height && width == CGSizeZero.width) {
//      return;
//    }
    // The player may be initialized but still needs to determine the duration.
    if ([self duration] == 0) {
      return;
    }

    _isInitialized = true;
    _eventSink(@{
      @"event" : @"initialized",
      @"duration" : @([self duration]),
      @"width" : @(width),
      @"height" : @(height)
    });
  }
}
```

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by wanjm** [comment]
@iapicca @TahaTesser   #68154 has the same request, but is closed, 
I think there is no need to provide " doctor " result;
as there is controller and videoplayer in "video_player" plug, so if use just use controller, then he can play audio or audio in mp4 files; and if he show VideoPlayer then video image can be show;

**Comment by TahaTesser** [comment]
@wanjm 
Please check out this  https://github.com/flutter/flutter/issues/38480#issuecomment-570458759

**Comment by Kretin1** [comment]
@TahaTesser if that is the case, why does the documentation still state that this supports audio formats?
https://pub.dev/packages/video_player#supported-formats
