### ISSUE TITLE
Breaking Proposal: MouseRegion defaults to opaque; Layers are required to implement findAnnotations

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#38488]
_If you don't use `MouseRegion` (formerly `Listener.onPointer{Enter,Exit,Hover}`), and you don't have custom layer classes, you can stop reading now._

## Overview
1. `MouseRegion` will have a new parameter, `bool opaque`. Its current behavior will be available as `opaque: false`, but we decide to make its default value to be `opaque: true`.
2. Subclasses of `Layer` will be required to implement a new method `findAnnotations`, and should no longer override `find` and `findAll`.

### Mouse region
`MouseRegion` will have a new parameter, `bool opaque`. The current behavior is available as `opaque: false`, which checks each mouse region independently whether it contains the mouse position. For example, consider a button that is stacked on top of another with some overlap, if the mouse pointer is within the overlapping area, both buttons will display hover highlight at the same time, which might be considered unintended.

![Opaque: false](https://user-images.githubusercontent.com/1596656/63204566-d203f400-c04d-11e9-83b0-8f967fd65207.gif)
_When the top button has opaque false_

Therefore we propose to add a new mode to `MouseRegion`, `opaque: true`. It means that, when it's hovered by a mouse pointer, the pointer is considered outside of any other mouse regions that are visually behind it and not ancestors of it. In the aforementioned example, if the top button is opaque, when the mouse pointer is hovering the overlapping area, the bottom one will not show hover highlight.

![Opaque: true](https://user-images.githubusercontent.com/1596656/63204570-ddefb600-c04d-11e9-83b3-80680ce770f3.gif)
_When the top button has opaque true_

We assume `opaque: false` should be a minor usage compared to `true`, therefore we propose to change the default behavior.

### Layers
Currently custom layers are required override `find` and `findAll` and implement similar recursive traveral logic twice.

We propose to add a protected method, `findAnnotations`, to handle both cases. Now `findAnnotations` will call itself recursively and traverse children, and `Layer` will provide a default implementation of `find` and `findAll`, both of which simply call `findAnnotations` with different arguments and return the result.

Additionally, `findAnnotations` returns a `bool`, which controls whether its parent should continue the remaining children after this layer. This is how `MouseRegion.opaque = true` is implemented (you might find it similar to `RenderObject.hitTest`), and is left abstract in order to encourage subclasses to implement it.

> Update: We discovered that more changes are needed to provide local position of the event. See [this update](https://github.com/flutter/flutter/issues/38488#issuecomment-527688254).

### Mouse region
For each usage of `MouseRegion`, decide which behavior is desired. To keep the current behavior, add `opaque: false`. If the current behavior is considered a bug, no change is needed.

### Layers
All custom layers will no longer be compilable due to lack of implementation of `findAnnotations`. To fix it, layers should no longer override either `find` and `findAll`, instead override `findAnnotations` to make it handle both cases and return the desired opacity. 

Here are some examples of migrating common patterns:
- Layers that will never have annotations in it or its descendants: [here](https://github.com/flutter/flutter/pull/37896/files#diff-58600d3d2645a66835eb03f3c41b447bR401)
- Layers that filter before delegating to `super`: [here](https://github.com/flutter/flutter/pull/37896/files#diff-58600d3d2645a66835eb03f3c41b447bR1121)
- Layers that transform before delegating to `super`: [here](https://github.com/flutter/flutter/pull/37896/files#diff-58600d3d2645a66835eb03f3c41b447bR1412)
- Layers that iterate its children: [here](https://github.com/flutter/flutter/pull/37896/files#diff-58600d3d2645a66835eb03f3c41b447bR770)
- Layers that add annotation: [here](https://github.com/flutter/flutter/pull/37896/files#diff-58600d3d2645a66835eb03f3c41b447bR2198)

Feel free to comment in this issue if you need help migrating.

## Changes and discussion
A proposed list of change can be found at https://github.com/flutter/flutter/pull/37896, which includes full documentation about the new properties and changed behaviors.

_If you have any concerns or otherwise feel that this change should not be made, please comment on the above PR or this issue._

**Comment by krisgiesing** [comment]
I would expect, by default, to get the same occlusion behavior with hover and click. That is, if I've already determined that the widget underneath won't get click events, then it wouldn't get hover effects either. Is that the case with this proposal?

**Comment by dkwingsmt** [comment]
@krisgiesing It's a very complicated issue. 

**Short (less precise) answer**: Yes if `GestureDetector` has children, no otherwise.

**Explanation**: "Clicks" are handled at `GestureDetector`, whose default behavior is
> [HitTestBehavior.deferToChild] if [child] is not null and [HitTestBehavior.translucent] if child is null.

Where `HitTestBehavior.deferToChild` loosely resembles `opaque: true`, while `HitTestBehavior.translucent` loosely resembles `opaque: false`. 

Now, why can't we do the same with `MouseRegion` and change behavior based on its children? Well, due to performance reasons, mouse-exclusive events (“mouse events”) are calculated on layers, while general pointer events ("gesture events") are calculated on objects, and they don't map together. The children objects of `MouseRegion` might not necessarily create a new layer, instead they might just draw on the `AnnotatedRegionLayer` created by the `MouseRegion`.

So we have to choose to either violate the consistency when `GestureDetector` has children, or violate when it doesn't. My personal belief is that the former case is more popular, so I think this change will generally benefit developers in the long run.

Note that generally speaking the area specified by a `HitTestBehavior.deferToChild` object can severely deviate from the region of the layer, in which case there is simply no way to keep the behavioral consistency.

**Comment by dkwingsmt** [comment]
## Update

We discovered that it is necessary to break the return value of `Layer.find` and `Layer.findAll` to contain the local position. 

### Justification 

Some layers transform the coordinate space from their parents to their children, such as `OffsetLayer` and `TransformLayer`. This transformation should be transparent to the children. For example, a layer that is a box of 30x30 should only receive hover events between (0, 0) and (30, 30), no matter what ancestors it belongs to, so that its behavior can be planned statically.

Moreover, when a mouse moves in a region and clicks, it is expected the `PointerHoverEvent` and the `PointerDownEvent` have the same `localPosition`.

Both cases requires that `Layer.findAll` not only returns the annotation, but also the local position that the event takes place, which can not be done with the current design.

`Layer.find` does not need the `localPosition` for now, but we think it is better to be update it as well to keep it consistent with `findAll`.

### Changes 
The return value of `Layer.find` and `Layer.findAll`, as well as the parameter of `Layer.findAnnotations`, will be changed. 
```dart
// Before
S find<S>(Offset regionOffset);
List<S> findAll<S>(Offset regionOffset);
bool findAnnotations<S>(List<S> result, Offset regionOffset, { @required bool onlyFirst, });

// After
AnnotationEntry<S> find<S>(Offset localPosition);
AnnotationResult<S> findAll<S>(Offset localPosition);
bool findAnnotations<S>(AnnotationResult<S> result, Offset localPosition, { @required bool onlyFirst, });
```

(We also renamed `regionOffset` to `localPosition` to be consistent with other code in Flutter, but it does not affect its meaning or your code.)

### Migration
If you use the result of `Layer.find`, you can change them in this way:
```dart
// Before
int result = layer.find<S>(myPosition);
// After
int result = layer.find<S>(myPosition)?.annotation;
```

If you use the result of `Layer.findAll`, you can change them in this way:
```dart
// Before
List<int> results = layer.findAll<S>(myPosition);
// After
Iterable<int> results = layer.findAll<S>(myPosition).annotations;
List<int> results = layer.findAll<S>(myPosition).annotations.toList(); // Or if you really need a list
```

If you modify the list during the recursion of `Layer.findAll`, after this change you'll only be able to `add` to the end the list (instead of removing or reordering). This is to enforce the transparency between layers. If this limitation breaks your project and can not be overcome, feel free to comment in this issue.

**Comment by dkwingsmt** [comment]
#37896 has been merged
