### ISSUE TITLE
How should I add the Text controller（like 【cancel】 and 【confirm】） to Cupertino Picker?

### ISSUE THREAD

**Issue by PythonNaChen** [flutter/flutter#38502]
like this：
![CB6D0BB6-FA05-4E32-A218-7C2920D420D1](https://user-images.githubusercontent.com/26499420/62992869-bfd85900-be87-11e9-9ea0-eec7ef732b2b.png)

It would be better if you had sample code.I'm a beginner，Thank you very very very much~

![20CBCADED4F17FEA8290D6AB10BE8FB0](https://user-images.githubusercontent.com/26499420/62992962-147bd400-be88-11e9-908c-0ad7b0abaf66.jpg)

**Comment by vanelizarov** [comment]
You can wrap `CupertinoPicker` in `Column` with `.end` alignment, and then add a kind-of toolbar with `CupertinoButton`s above it:

```dart
showCupertinoModalPopup(
  context: context,
  builder: (context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.end,
      children: <Widget>[
        Container(
          decoration: BoxDecoration(
            color: Colors.white,
            border: Border(
              bottom: BorderSide(
                color: Color(0xff999999),
                width: 0.0,
              ),
            ),
          ),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              CupertinoButton(
                child: Text('Cancel'),
                onPressed: () {},
                padding: const EdgeInsets.symmetric(
                  horizontal: 16.0,
                  vertical: 5.0,
                ),
              ),
              CupertinoButton(
                child: Text('Confirm'),
                onPressed: () {},
                padding: const EdgeInsets.symmetric(
                  horizontal: 16.0,
                  vertical: 5.0,
                ),
              )
            ],
          ),
        ),
        Container(
          height: 320.0,
          color: Color(0xfff7f7f7),
          child: CupertinoPicker(
            /* the rest of the picker */
          ),
        )
      ],
    );
  },
);
```

It will then look like this (ignore colors and options, this is just the example of using this method):

<img width="434" alt="Screen Shot 2019-08-14 at 18 13 25" src="https://user-images.githubusercontent.com/5096148/63032826-3cd2f500-bebf-11e9-8ae0-89ffd06143a3.png">

**Comment by VladyslavBondarenko** [comment]
Seems solved, closing.
@PythonNaChen if you disagree please write in the comments and I will reopen it
thank you
