### ISSUE TITLE
Firebase Messaging not show when app close in some device (

### ISSUE THREAD

**Issue by mukhtarfauzi** [flutter/flutter#38505]
#37081 

I have a problem with my app, I use Firebase Messaging plugin and found there is no notification that I get only when my app closed (terminated). for some reason, I can't get a notification in a few devices.

Tested Devices:
1. Asus Zenfone 5 (Model: ASUS_X00QD) **Not work**
2. Asus Zenfone 5 (Model: ASUS_Z01FD) **Not Work**
3. Redmi Note 7 **Work**
4. Redmi 6 **Work**
5. Huawei Nova 3i **Work**
6. Samsung Galaxy S7 **Work**
7. Emulator Pixel 2 Api 27 **Work**
8. ASUS Zenfone 3 (Model: ASUS_Z017DB) **Not Work**

 Steps to Reproduce

1. Install App
2. Close App
3. Send a notification from firebase console
4. Get notification only in few devices

## Logs
no logs

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.885], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code (version 1.37.0)
[√] Connected device (1 available)
```

**Comment by jld3103** [comment]
Seems to be only a problem with ASUS devices.
Some OEM Androids kill apps in the background. Maybe that's the problem.

**Comment by BondarenkoStas** [comment]
May be related to #38430

**Comment by kroikie** [comment]
@mukhtarfauzi

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1046. Any further collaboration will be done there.
