### ISSUE TITLE
How add CI/CD in Flutter existing Android app

### ISSUE THREAD

**Issue by rahuldevanavar91** [flutter/flutter#38511]
We have added Flutter in existing native Android.so now we have two repositories.`Flutter_module` and  `Android_module`. I am using GitLab for `CI/CD` pipeline. Now the problem is how to set include_flutter.groovy path in `setting.gradle` because it is in another repository.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
