### ISSUE TITLE
Can I listen to the screenshot?

### ISSUE THREAD

**Issue by qq125183592** [flutter/flutter#38517]
I want to monitor the user to take a screen shot on the phone, and then handle the follow-up actions, what can I do? Looking forward to your reply!

**Comment by hberrayana** [comment]
It has to be done in a plugin using platform channels. Very similar to what this cordova plugin does: https://www.npmjs.com/package/cordova-plugin-detect-screenshot

**Comment by qq125183592** [comment]
> It has to be done in a plugin using platform channels. Very similar to what this cordova plugin does: https://www.npmjs.com/package/cordova-plugin-detect-screenshot

Thanks,  can it take effect in android system?

**Comment by hberrayana** [comment]
For Android there is no dedicated event but you can do it by listening to the screenshots directory.
See this thread: https://stackoverflow.com/questions/29621903/detect-only-screenshot-with-fileobserver-android

**Comment by BondarenkoStas** [comment]
@qq125183592  Hope the comment of @hberrayana was helpful to you. 
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report.
If you disagree, feel free to comment and I will reopen it.

**Comment by qq125183592** [comment]
thank you~  @hberrayana @BondarenkoStas
