### ISSUE TITLE
DateTime add(Duration duration) not working?

### ISSUE THREAD

**Issue by LinnDang** [flutter/flutter#38516]
Hi, I found the DateTime class with the method "DateTime add(Duration duration)” not working, the demo code is below:
DateTime dateTime = DateTime.now();
Debug.v('now DateTime:${dateTime.toString()}');
dateTime.add(Duration(days: 1, seconds: 50));
Debug.v('add DateTime:${dateTime.toString()}');
Test Result is below:
I/flutter (16939):   v  now DateTime:2019-08-14 15:28:28.370735
I/flutter (16939):   v  add DateTime:2019-08-14 15:28:28.370735
I don't know why?

My run envirement as the below:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[!] VS Code (version 1.37.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

**Comment by jld3103** [comment]
```dart
dateTime = dateTime.add(Duration(days: 1, seconds: 50));
```
