### ISSUE TITLE
crash on iOS at shell::WrapOnscreenSurface

### ISSUE THREAD

**Issue by yantao608** [flutter/flutter#38519]
## Steps to Reproduce

iOS ViewController -> flutterPage -> iOS ViewController  then back to flutterPage I got this crash

this is crash log:
```
Thread 28 name:  io.flutter.1.gpu
 Thread 28 Crashed:
0   Flutter                         shell::WrapOnscreenSurface(GrContext*, SkISize const&, long) (gpu_surface_gl.cc:172)
1   Flutter                         shell::GPUSurfaceGL::AcquireFrame(SkISize const&) (gpu_surface_gl.cc:235)
2   Flutter                         shell::GPUSurfaceGL::AcquireFrame(SkISize const&) (gpu_surface_gl.cc:235)
3   Flutter                         shell::Rasterizer::DrawToSurface(flow::LayerTree&) (rasterizer.cc:163)
4   Flutter                         shell::Rasterizer::DoDraw(std::__1::unique_ptr<flow::LayerTree, std::__1::default_delete<flow::LayerTree> >) (rasterizer.cc:153)
5   Flutter                         std::__1::__function::__func<std::__1::__bind<void (shell::Rasterizer::*)(std::__1::unique_ptr<flow::LayerTree, std::__1::default_delete<flow::LayerTree> >), shell::Rasterizer*, std::__1::placeholders::__ph<1> const&>, std::__1::allocator<std::__1::__bind<void (shell::Rasterizer::*)(std::__1::unique_ptr<flow::LayerTree, std::__1::default_delete<flow::LayerTree> >), shell::Rasterizer*, std::__1::placeholders::__ph<1> const&> >, void (std::__1::unique_ptr<flow::LayerTree, std::__1::default_delete<flow::LayerTree> >)>::operator()(std::__1::unique_ptr<flow::LayerTree, std::__1::default_delete<flow::LayerTree> >&&) (functional:1572)
6   Flutter                         shell::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flow::LayerTree> >) (pipeline.h:130)
7   Flutter                         std::__1::__function::__func<shell::Shell::OnAnimatorDraw(fml::RefPtr<flutter::Pipeline<flow::LayerTree> >)::$_24, std::__1::allocator<shell::Shell::OnAnimatorDraw(fml::RefPtr<flutter::Pipeline<flow::LayerTree> >)::$_24>, void ()>::operator()() (functional:1572)
8   Flutter                         fml::MessageLoopImpl::RunExpiredTasks() (message_loop_impl.cc:142)
9   Flutter                         fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (message_loop_darwin.mm:76)
10  CoreFoundation                  __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
11  CoreFoundation                  __CFRunLoopDoTimer + 864
12  CoreFoundation                  __CFRunLoopDoTimers + 248
13  CoreFoundation                  __CFRunLoopRun + 1844
14  CoreFoundation                  CFRunLoopRunSpecific + 436
15  Flutter                         fml::MessageLoopDarwin::Run() (message_loop_darwin.mm:47)
16  Flutter                         std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*, void*) (thread:352)
17  libsystem_pthread.dylib         _pthread_body + 128
18  libsystem_pthread.dylib         _pthread_start + 44
```
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.2.1-hotfix.2, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
   ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
   ✗ Flutter plugin not installed; this adds Flutter specific functionality.
   ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by BondarenkoStas** [comment]
@yantao608 is it still relevant? Did you try to upgrade your flutter?

**Comment by yantao608** [comment]
I upgrade my flutter to 1.5.4 hotfix.2 still have this crash。

the crash info is:
----------------------------------------------------------
Thread 18 name:  io.flutter.1.gpu
Thread 18 Crashed:
0   Flutter                         flutter::Rasterizer::DoDraw(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >) (rasterizer.cc:155)
1   Flutter                         flutter::Rasterizer::DoDraw(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >) (rasterizer.cc:154)
2   Flutter                         std::__1::__function::__func<std::__1::__bind<void (flutter::Rasterizer::*)(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >), flutter::Rasterizer*, std::__1::placeholders::__ph<1> const&>, std::__1::allocator<std::__1::__bind<void (flutter::Rasterizer::*)(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >), flutter::Rasterizer*, std::__1::placeholders::__ph<1> const&> >, void (std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >)>::operator()(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >&&) (functional:1572)
3   Flutter                         flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >) (pipeline.h:131)
4   Flutter                         std::__1::__function::__func<flutter::Shell::OnAnimatorDraw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >)::$_24, std::__1::allocator<flutter::Shell::OnAnimatorDraw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >)::$_24>, void ()>::operator()() (functional:1572)
5   Flutter                         fml::MessageLoopImpl::FlushTasks(fml::MessageLoopImpl::FlushType) (message_loop_impl.cc:141)
6   Flutter                         fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (message_loop_darwin.mm:76)
7   CoreFoundation                  __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
8   CoreFoundation                  __CFRunLoopDoTimer + 872
9   CoreFoundation                  __CFRunLoopDoTimers + 244
10  CoreFoundation                  __CFRunLoopRun + 1572
11  CoreFoundation                  CFRunLoopRunSpecific + 444
12  Flutter                         fml::MessageLoopDarwin::Run() (message_loop_darwin.mm:47)
13  Flutter                         std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*, void*) (thread:352)
14  libsystem_pthread.dylib         _pthread_body + 240
15  libsystem_pthread.dylib         _pthread_body + 0
----------------------------------------------------------

**Comment by BondarenkoStas** [comment]
@yantao608 current stable version is ```v1.9.1+hotfix.2```, do you encounter the crash on it? 
If yes, please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by seeuli** [comment]
Using PlatformView on 1.5.4 hotfix.2, this problem also occurs in the main thread.

Thread 0 Crashed:
0   Flutter                         flutter::WrapOnscreenSurface(GrContext*, SkISize const&, long) (gpu_surface_gl.cc:129)
1   Flutter                         flutter::GPUSurfaceGL::AcquireFrame(SkISize const&) (gpu_surface_gl.cc:192)
2   Flutter                         flutter::GPUSurfaceGL::AcquireFrame(SkISize const&) (gpu_surface_gl.cc:192)
3   Flutter                         flutter::Rasterizer::DrawToSurface(flutter::LayerTree&) (rasterizer.cc:174)
4   Flutter                         flutter::Rasterizer::DoDraw(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >) (rasterizer.cc:157)
5   Flutter                         std::__1::__function::__func<std::__1::__bind<void (flutter::Rasterizer::*)(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >), flutter::Rasterizer*, std::__1::placeholders::__ph<1> const&>, std::__1::allocator<std::__1::__bind<void (flutter::Rasterizer::*)(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >), flutter::Rasterizer*, std::__1::placeholders::__ph<1> const&> >, void (std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >)>::operator()(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >&&) (functional:1572)
6   Flutter                         flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >) (pipeline.h:131)
7   Flutter                         std::__1::__function::__func<flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >)::$_0, std::__1::allocator<flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >)::$_0>, void ()>::operator()() (functional:1572)
8   Flutter                         fml::MessageLoopImpl::FlushTasks(fml::MessageLoopImpl::FlushType) (message_loop_impl.cc:141)
9   Flutter                         fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (message_loop_darwin.mm:76)

**Comment by seeuli** [comment]
Appears when pop PlatformView page.

**Comment by keshiim** [comment]
I got same problem on 1.5.4 hotfix.2

Stack Info：
`Date/Time:       2019-12-17 16:10:53.000 +0800
OS Version:      iOS 12.1 (16B92)
Report Version:  104

Crash Type: signal
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: 0x00000000 at 0x0000000000000080
Crashed Thread:  0

Thread 0 name:  N
Thread 0 Crashed:
0   Flutter                         flutter::WrapOnscreenSurface(GrContext*, SkISize const&, long) (gpu_surface_gl.cc:129)
1   Flutter                         flutter::GPUSurfaceGL::AcquireFrame(SkISize const&) (gpu_surface_gl.cc:192)
2   Flutter                         flutter::GPUSurfaceGL::AcquireFrame(SkISize const&) (gpu_surface_gl.cc:192)
3   Flutter                         flutter::Rasterizer::DrawToSurface(flutter::LayerTree&) (rasterizer.cc:174)
4   Flutter                         flutter::Rasterizer::DoDraw(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >) (rasterizer.cc:157)
5   Flutter                         std::__1::__function::__func<std::__1::__bind<void (flutter::Rasterizer::*)(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >), flutter::Rasterizer*, std::__1::placeholders::__ph<1> const&>, std::__1::allocator<std::__1::__bind<void (flutter::Rasterizer::*)(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >), flutter::Rasterizer*, std::__1::placeholders::__ph<1> const&> >, void (std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >)>::operator()(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >&&) (functional:1572)
6   Flutter                         flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >) (pipeline.h:131)
7   Flutter                         std::__1::__function::__func<flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >)::$_0, std::__1::allocator<flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >)::$_0>, void ()>::operator()() (functional:1572)
8   Flutter                         fml::MessageLoopImpl::FlushTasks(fml::MessageLoopImpl::FlushType) (message_loop_impl.cc:141)
9   Flutter                         fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (message_loop_darwin.mm:76)
10  CoreFoundation                  __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
11  CoreFoundation                  __CFRunLoopDoTimer + 864
12  CoreFoundation                  __CFRunLoopDoTimers + 248
13  CoreFoundation                  __CFRunLoopRun + 1880
14  CoreFoundation                  CFRunLoopRunSpecific + 436
15  GraphicsServices                GSEventRunModal + 100
16  UIKitCore                       UIApplicationMain + 212
17  qcs.r                           main (main.m:36)
18  libdyld.dylib                   start + 4`
