### ISSUE TITLE
Unable to load asset: AssetManifest.json

### ISSUE THREAD

**Issue by HDHunter** [flutter/flutter#38510]
MyProject run flutter as a module,because of sourcemerge can't copy assets to mainModule, I always copy flutter_assets fold to mainModule (app module). flutter pager is OK.

but can't load image.

## Steps to Reproduce
run flutter project as application , everything is fine . run my java project , dependency flutter module . can't work.

## Logs
![image](https://user-images.githubusercontent.com/12092336/62998611-aabaf480-be9e-11e9-8349-dd6bc7fb7f68.png)

flutter analyze:

just some varible spelling warn info.
and comment /// worn , nothing fatal.

flutter doctor

![image](https://user-images.githubusercontent.com/12092336/62998775-20bf5b80-be9f-11e9-941f-aeb73cd3985d.png)

**Comment by HDHunter** [comment]
![image](https://user-images.githubusercontent.com/12092336/62998834-48aebf00-be9f-11e9-9e28-fc0ff4440df8.png)
copy the build intermediates file to mainModule assets folder.

**Comment by HDHunter** [comment]
some people said master channel have this issue , so I change to dev channel , also happend.

**Comment by minikin** [comment]
@HDHunter Can you post your `pubspec.yaml`, please?

**Comment by BondarenkoStas** [comment]
@HDHunter is it still relevant?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by EHBradford** [comment]
Hi, 
I just encountered this problem and I found what caused my issue.  I had placed an image.png in the assets folder.  Then I went to the pubspec.yaml file and placed a reference to the file there.

Unfortunately I misspelled the name of the image.png file.  Such as in the pubspec.yaml file I placed immage.png in the appropriate location when it should have been image.png.

The Android Studio editor did highlight the issue, but for me the highlight was not readily noticeable, thus I missed the fact that there was a spelling issue.  The coloring of the highlighted error was only slightly different from the normal text.

Hope this helps someone who perhaps has this issue.

BTW, flutter doctor -v revealed no errors.

**Comment by shivanchalaeologic** [comment]
you need to set up your assets like in the image given below, you just need to manage space correctly
![Screenshot from 2020-09-01 16-49-29](https://user-images.githubusercontent.com/66462755/91843370-4b7b7e00-ec73-11ea-9a5e-60b53a71bdc8.png)

**Comment by moseskarunia** [comment]
Hi, I experienced this problem as well, but only in testing (the actual run works)

**Comment by shinayser** [comment]
> Hi, I experienced this problem as well, but only in testing (the actual run works)
> 
> Wrote it in an SO post [here](https://stackoverflow.com/questions/65917228/the-following-assertion-was-thrown-while-resolving-an-image-unable-to-load-asse) along with the error message, code, and flutter doctor.

I'm having this exacly right now. Occurs only on testing but runs fine on app. Maybe a framework bug?
