### ISSUE TITLE
[path_provider] getApplicationSupportDirectory crashes

### ISSUE THREAD

**Issue by catacs** [flutter/flutter#38529]
## Steps to Reproduce

1. Init app with path_provider version 1.2.0 in a device with Android 6
2. Try to get getApplicationSupportDirectory `await getApplicationSupportDirectory()`

## Logs

```
E/MethodChannel#plugins.flutter.io/path_provider(26592): Failed to handle method call
E/MethodChannel#plugins.flutter.io/path_provider(26592): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#plugins.flutter.io/path_provider(26592):        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:135)
E/MethodChannel#plugins.flutter.io/path_provider(26592):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.notImplemented(MethodChannel.java:235)
E/MethodChannel#plugins.flutter.io/path_provider(26592):        at io.flutter.plugins.pathprovider.PathProviderPlugin.onMethodCall(PathProviderPlugin.java:44)
E/MethodChannel#plugins.flutter.io/path_provider(26592):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/path_provider(26592):        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/path_provider(26592):        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#plugins.flutter.io/path_provider(26592):        at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/path_provider(26592):        at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#plugins.flutter.io/path_provider(26592):        at android.os.Looper.loop(Looper.java:135)
E/MethodChannel#plugins.flutter.io/path_provider(26592):        at android.app.ActivityThread.main(ActivityThread.java:5525)
E/MethodChannel#plugins.flutter.io/path_provider(26592):        at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/path_provider(26592):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
E/MethodChannel#plugins.flutter.io/path_provider(26592):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
E/DartMessenger(26592): Uncaught exception in binary message listener
E/DartMessenger(26592): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(26592):         at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:135)
E/DartMessenger(26592):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:240)
E/DartMessenger(26592):         at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/DartMessenger(26592):         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/DartMessenger(26592):         at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(26592):         at android.os.MessageQueue.next(MessageQueue.java:323)
E/DartMessenger(26592):         at android.os.Looper.loop(Looper.java:135)
E/DartMessenger(26592):         at android.app.ActivityThread.main(ActivityThread.java:5525)
E/DartMessenger(26592):         at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(26592):         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
E/DartMessenger(26592):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

```
```

```
```

```
```

**Comment by jmagman** [comment]
See https://github.com/flutter/flutter/issues/13474.
@collinjackson

**Comment by singun-lxd** [comment]
break is missing in case "getApplicationSupportDirectory", source file is PathProviderPlugin.java, 

`  @Override
  public void onMethodCall(MethodCall call, Result result) {
    switch (call.method) {
      case "getTemporaryDirectory":
        result.success(getPathProviderTemporaryDirectory());
        break;
      case "getApplicationDocumentsDirectory":
        result.success(getPathProviderApplicationDocumentsDirectory());
        break;
      case "getStorageDirectory":
        result.success(getPathProviderStorageDirectory());
        break;
      case "getApplicationSupportDirectory":
        result.success(getApplicationSupportDirectory());
      default:
        result.notImplemented();
    }
  }`

**Comment by andyqp** [comment]
It is fixed in repo 2 days ago. Unfortunately, the new version 1.2.1 is not published yet...

**Comment by yohane55** [comment]
Stacktrace:
`E/MethodChannel#plugins.flutter.io/path_provider: Failed to handle method call
    java.lang.IllegalStateException: Reply already submitted
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:135)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.notImplemented(MethodChannel.java:235)
        at io.flutter.plugins.pathprovider.PathProviderPlugin.onMethodCall(PathProviderPlugin.java:44)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:7094)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)`

**Comment by andyqp** [comment]
Version 1.2.2 is published, with this fix included!

**Comment by singun-lxd** [comment]
great, I've update the plugin

**Comment by jmagman** [comment]
@catacs Are you still seeing this on the newest version of path_provider?

**Comment by catacs** [comment]
@jmagman Everything is working as expected. We can close the issue.
