### ISSUE TITLE
[Dekstop] Unable to compile sample

### ISSUE THREAD

**Issue by giaur500** [flutter/flutter#38523]
What I did:

`flutter channel master`
`flutter upgrade`

Then, enable desktop embedding:

`export ENABLE_FLUTTER_DESKTOP=true`

Flutter doctor output:

```
[✓] Flutter (Channel master, v1.8.5-pre.143, on Linux, locale pl_PL.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.4)
[!] Connected device
    ! No devices available

```
Inded no devices, but there should be linux device listed:
```

~$ flutter devices
No devices detected.

Run 'flutter emulators' to list and start any available device emulators.

Or, if you expected your device to be detected, please run "flutter doctor" to
diagnose potential issues, or visit https://flutter.dev/setup/ for
troubleshooting tips.
```

When trying to compile sample from flutter git, I'm getting error linux is not supported:

```
$ flutter build linux
"build linux" is not currently supported.
```
Any advice what's wrong there? `flutter run` fails with error saying no devices available. I guees current master has desktop embedding broken, or what? Known issue?

**Comment by jld3103** [comment]
Are you using IntelliJ?

**Comment by jld3103** [comment]
Android Studio somehow ignore files like ```.bashrc```. You have to use ```/etc/environment``` to get it to work.

**Comment by giaur500** [comment]
Well it seems thing have changed. For desktop embedding, that command:

`flutter config --enable-linux-desktop`

is required. `export ENABLE_FLUTTER_DESKTOP=true` does not work anymore

**Comment by giaur500** [comment]
Yes. But still does not work, only flutter config works

**Comment by jonahwilliams** [comment]
If flutter config is working for you I assume the problem is solved?

**Comment by stuartmorgan** [comment]
I've checked that the environment variable still works locally, and we have unit testing coverage of that as well. I'm curious why it's not working for you, but given that the fact that it still works is undocumented behavior and not what our instructions say to do, I don't think trying to troubleshoot this specific instance further is necessary.

**Comment by giaur500** [comment]
Yes, I managed to make it working, so issue can be closed. I have no idea why environment variable does not work in my case, but as long as documented way works, it does not matter

**Comment by agentydragon** [comment]
I'm having the same issue. I just checked out the repo today, ran `flutter config --enable-linux-desktop` and `flutter build linux` says `"build linux" is not currently supported.`. My `flutter doctor` output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Linux, locale de_DE.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

Also, nothing desktop shows up in `flutter devices`:

```
2 connected devices:

Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
Web Server • web-server • web-javascript • Flutter Tools
```

**Comment by giaur500** [comment]
You need to use master channel, afaik there is no support for desktop in beta

**Comment by stuartmorgan** [comment]
Channel requirements are [documented here](https://github.com/flutter/flutter/wiki/Desktop-shells#tooling).

> The device does not show up even if I do `export ENABLE_FLUTTER_DESKTOP=true`

There is no reason to do this with current versions of Flutter; see my earlier comment.

**Comment by agentydragon** [comment]
Re: channel requirements: thanks, that didn't occur to me, I'll try that and if I don't report any more issues, you can assume that fixed them :)

It's a little surprising to me that the "master" channel includes features the "beta" channel does not. Under the typical meaning of those terms, I would not expect that some feature would make it to master before beta.

**Comment by stuartmorgan** [comment]
> It's a little surprising to me that the "master" channel includes features the "beta" channel does not.

See the description of the Flutter channels, which is linked from the instructions referenced above. All changes start on master.

**Comment by benwinding** [comment]
`flutter channel master`

Then it works...
