### ISSUE TITLE
TextFields do not show native actions

### ISSUE THREAD

**Issue by gctommy** [flutter/flutter#38530]
Hello, I am trying to get the Native actions to show on any TextField (to access Clip Tray) but I am unable to do so. How can I trigger the Native actions to show?

Please see steps and screen shots below.

## Steps to Reproduce

1. Open official **Flutter Gallery** app > **Material** > **Text fields**
2. Focus and hold on any of the text fields to show the actions
3. Try Step 2 in a native app such as **Messages** or any core Google app such as Chrome using the address bar

### Expected hover actions to show:
![flutter-textfield-actions-02](https://user-images.githubusercontent.com/3850550/63016643-cdf99a00-bec6-11e9-8d7f-eb9e26f87195.jpg)

### Actual actions shown:
![flutter-textfield-actions-01](https://user-images.githubusercontent.com/3850550/63016642-cdf99a00-bec6-11e9-9d9a-26ce90843bd2.jpg)

```
[√] Flutter (Channel beta, v1.8.3, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.8.3 at C:\flutter
    • Framework revision e4ebcdf6f4 (3 weeks ago), 2019-07-27 11:48:24 -0700
    • Engine revision 38ac5f30a7
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 0ca1582afd)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code (version 1.36.1)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • LM G710N • LMG710Ne7a954c2 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by justinmc** [comment]
Currently the text selection menu items are hardcoded, and the only ones supported are Cut, Copy, Paste, and Select All.  There is an [issue](https://github.com/flutter/flutter/issues/31412) to support custom items, which might solve this problem for some people once it's implemented.

**Comment by gnprice** [comment]
I think this is now covered by a couple of more-specific issues:
* #107578 
* #107603
* #82907

Those have accumulated more discussion, so let's track this feature request there.
