### ISSUE TITLE
What kind of metrics/analytics/logging support is out there?

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#3853]
What kind of metrics/analytics/logging support is out there?
- Get notified when users experience a log.warning
  - Which logging library should we use?
- Get notified when users experience an exception
- Get metrics on how often the users open the app and what they do in it

**Comment by sethladd** [comment]
cc @HansMuller (we'll need something similar for Gallery)

**Comment by sethladd** [comment]
Thanks for the feedback!

Closing this in favor of other issues:

* Analytics for a Flutter app: https://github.com/flutter/flutter/issues/5497

* Crash reporting: https://github.com/flutter/flutter/issues/4070 from within a Flutter app

re: logging, presumably one could wire up logging to either crash reporting or analytics.
