### ISSUE TITLE
Is it possible to use decorators or validation attributes

### ISSUE THREAD

**Issue by maxime-aubry** [flutter/flutter#38536]
Hello.

I would like to know if i can use an equivalent of "Model validation is ASP.NET Core MVC" with Flutter ?
[https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.2](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.2)

I would be easier to add rule to validate a form.
Thanks.

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
