### ISSUE TITLE
Please export rootFlutterViewController in FlutterAppDelegate.h

### ISSUE THREAD

**Issue by sma** [flutter/flutter#38535]
Right now, the pregenerated iOS app expects the `FlutterViewController` to be the window's root view controller. There is even a method called `rootFlutterViewController` in `FlutterAppDelegate` to access it. 

If this would be exported – preferable as property – in FlutterAppDelegate.h, subclasses could override this and for example wrap the view controller in a `UINavigationController` or `UITabBarController`.

Of course, this property should be used by the FlutterAppDelegate internally, too.

Right now, three other methods in FlutterAppDelegate.mm (line 148 and 157 and 165) use a different way to access the Flutter view controller, still assuming it is the window's root view controller.

Please modify them so that they use the provided property.

**Comment by gaaclarke** [comment]
This can be accomplished with the add-to-app workflow: https://flutter.dev/docs/development/add-to-app
