### ISSUE TITLE
Floating point precision error makes restore position failure in NestedScrollView

### ISSUE THREAD

**Issue by voiddog** [flutter/flutter#38534]
![Imgur](https://i.imgur.com/9QKVIre.png)
As shown in picture, durning in an user scroll, the **Inner Position** can consume all delta. But this is not the case

> `abs(clampedDelta)` is smaller than `abs(delta)`

This error makes **Outer Position** scroll `1E-13`.

`restoreScrollOffset` function in `_NestedScrollPosition` is:
```dart
@override
void restoreScrollOffset() {
if (coordinator.canScrollBody)
  super.restoreScrollOffset();
}
```
Because **Outer Position** scrolls a little, causing `coordinator.canScrollBody` to fail.

The final result is 'NestedScrollView' can not restore position when switch tab

Here is the [demo](https://github.com/voiddog/flutter_issues_demo/tree/master/lib/demo/nested_scroll_view)

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Xcode - develop for iOS and macOS (Xcode 10.3)
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] iOS tools - develop for iOS devices
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
[✓] VS Code (version 1.37.0)
[✓] Connected device (2 available)

! Doctor found issues in 3 categories.
```

**Comment by VladyslavBondarenko** [comment]
Hi @voiddog 
please follow up on https://github.com/flutter/flutter/issues/40740
I'm closing the current one as duplicate,
If you disagree please write in the comments and I will reopen it.
Thank you
