### ISSUE TITLE
TextField on iOS - Cannot specify textContentType

### ISSUE THREAD

**Issue by vincekruger** [flutter/flutter#38533]
I'm implementing a login screen in Flutter and I cannot set the Content-Type on an email text field. On an iOS app, the content type needs to be set in order for email addresses suggestions to display while editing.

UITextContentType as found in the iOS documentation:
https://developer.apple.com/documentation/uikit/uitextcontenttype

Am I missing something or is this not yet supported?

## Example

```
TextFormField(
    keyboardAppearance: Brightness.light,
    keyboardType: TextInputType.emailAddress,
    textInputAction: TextInputAction.next,
    autofocus: true,
    decoration: InputDecoration(
      hintText: 'Email',
      icon: Icon(
        Icons.mail,
        color: Colors.grey,
      ),
    ),
)
```

There is an option for this in Xcode: 
<img width="250" alt="vmDld" src="https://user-images.githubusercontent.com/360833/63022454-42badd00-bea3-11e9-8a33-24c4084a9b63.png">

**Comment by HansMuller** [comment]
Thanks for the report! This is a reasonable request and has come up before: https://github.com/flutter/flutter/issues/33040

I'm going to close this issue as a duplicate.
