### ISSUE TITLE
Option to deactivate overflow errors when running tests

### ISSUE THREAD

**Issue by yamauchieduardo** [flutter/flutter#38545]
Tests run with weird fonts, and sometimes it overflows, breaking tests. Some tests don´t care about overflow anyway, so there should be a way to deactivate them. 

I have many tests which run ok in the simulator, but break in tests.

Please, allow us to deactivate overflow errors in tests.

**Comment by marcglasberg** [comment]
The **Ahem font** overflows everything. We are forced to prevent overflows for widgets which will never overflow in reality, or else provide fonts for the tests just for the sake of not overflowing them. It makes no sense that overflow errors are tested, unless you are doing overflow error tests.

**Comment by marcglasberg** [comment]
https://stackoverflow.com/questions/57499131/how-to-deactivate-or-ignore-layout-overflow-messages-in-flutter-widget-tests/57499255#57499255

**Comment by yamauchieduardo** [comment]
Issue resolvida. https://stackoverflow.com/a/57501230/9440362
