### ISSUE TITLE
Can't have if condition with { } inside Column widget

### ISSUE THREAD

**Issue by melwinlobo18** [flutter/flutter#38541]
When I write 'if' condition with '{ }' inside the children of Column widget  I get `The element type 'Set<Widget>' can't be assigned to the list type 'Widget'` error. This prevents me from having statements inside the 'if' condition.

**Comment by jld3103** [comment]
As far as I know you can only do single line statements

**Comment by jonahwilliams** [comment]
@jld3103 is correct, the if and for elements in collections can only contain expressions. you could always use a method to implement more complex functionality:

```
int doThing() {
  //...
  //...
  return 2l
}

var x = [
  a,
  b,
  if (c) _doThing(),
]
```

more information at https://dart.dev/guides/language/language-tour#lists
