### ISSUE TITLE
Best practice for flutter path in pubspec.yaml

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#3854]
`flutter create` used a relative path which is very fragile for teams working on the same code base. This assumes everyone checked out the project in the same relative path to where they installed flutter. I have seen some projects instead use a symlink to flutter in their root application directory. They .gitignore the symlink, requiring people to set it up when they first checkout the repository.

Are there other best practices? What do you suggest?

I am refering to `pubspec.yaml`

```
dependencies:
  flutter:
    path: ../../../../../flutter/packages/flutter
```

**Comment by sethladd** [comment]
cc @nex3 @kevmoo

**Comment by Hixie** [comment]
This is obsolete now.
