### ISSUE TITLE
[web] BoxDecoration rendering with cornerRadius>constraintWidth/2 is inconsistent between web/native

### ISSUE THREAD

**Issue by ferhatb** [flutter/flutter#38549]
Workaround: reduce incorrect borderradius.

## Steps to Reproduce

import 'package:flutter_web/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Center(
          child: Container(
            width: 48,
            height: 48,
            alignment: Alignment.center,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(60),  // <--- This large radius causes failure
              color: Colors.amber,
            ),
            child: Text(
              'A',
              style: TextStyle(
                fontSize: 24,
                color: Colors.white,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
      ),
    ),
  );
}

**Comment by ditman** [comment]
The CSS spec has a good solution for this, I'll try to follow this as inspiration:

https://www.w3.org/TR/css-backgrounds-3/#corner-overlap

**Comment by ditman** [comment]
Turns out the CSS3/Skia algo is [already implemented in the ui.RRect class](https://github.com/flutter/flutter_web/blob/master/packages/flutter_web_ui/lib/src/ui/geometry.dart#L1450-L1455), so I'll use that instead of writing my own version of the same thing.

**Comment by ditman** [comment]
Submitted fix

**Comment by ferhatb** [comment]
Fixed via https://github.com/flutter/flutter_web/commit/3a9ad66ba585f564d26630b82423488529f7ddea
