### ISSUE TITLE
App size increased by 80% from upgrading flutter

### ISSUE THREAD

**Issue by spnda** [flutter/flutter#38557]
Hello,
After upgrading flutter from 1.5-hotfix2 to the latest flutter version 1.7.8-hotifx.4 I have experienced issues regarding app size.
For the release of the app I am trying to get it to be sized between 10 and 20MB.

Before the update:
APK Size: ~8MB
App Size: ~26MB

After the update:
APK Size: ~15MB
App Size: ~47MB

So is this an issue of the latest flutter version that I shouldn't worry about and wait until a new version with a fix comes out or is this going to be standard?
If this is what standard app sizes will look like in the future I am downgrading to a old flutter version or might even consider using Kotlin or Java instead.... But this was such a good tool for making beautiful apps :(

**Comment by jason-simmons** [comment]
Flutter now builds APKs targeting both 32- and 64-bit ARM platforms by default.  The APK generated by the older version of Flutter is probably smaller because it only contains binaries for one of those platforms.

**Comment by spnda** [comment]
Yes, I tried doing --split-by-abi which decreased the size slightly. Do you know the command line option for just building APKs that run on 64-bit ARM?

**Comment by giaur500** [comment]
Even after split, still installed apk size on phone is bigger than before

**Comment by vvasc** [comment]
https://github.com/flutter/flutter/issues/38557#issuecomment-521388727 @spnda You can use
`flutter build apk --release --target-platform=android-arm`

**Comment by giaur500** [comment]
Isn't that the same as split and take 32-bit variant?

**Comment by vvasc** [comment]
yes, you can try something like:
`flutter build appbundle --target-platform android-arm,android-arm64` To generate an app bundle, or to split the APKs per ABI `flutter build apk --target-platform android-arm,android-arm64 --split-per-abi`. You can check this two links for more information https://developer.android.com/guide/app-bundle, https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split

**Comment by spnda** [comment]
So, I tried doing `flutter build apk --split-per-abi` of course it built. But it still didn't decrease the installed app size on my phone.
I also just updated flutter to 1.9.3 and the installed app increased by another 4MB. I don't feel like there's anything new taking up this much more storage...

**Comment by giaur500** [comment]
Well that's where Flutter goes, it becomes more and more fat
