### ISSUE TITLE
url launcher on ios can't include subject or body for mailto

### ISSUE THREAD

**Issue by jdeltoft** [flutter/flutter#38555]
I'm trying to do the following and it won't work on ios.  

```
launchUrlContactUs() async {
  var url = 'mailto:contactus@yourdomainhere.com?subject=Need Help&body='
      '<Full Name>\n'
      '<Best Contact Method>\n'
      '<Detailed Issue Description>\n'
      '<Frequency of Issue>\n'
      '<Setup/Steps to Reproduce>\n';
  if (await canLaunch(url)) {
    await launch(url);
  } else {
    throw 'Could not launch $url';
  }
}
```

I don't even get the "could not launch" error.  It gives this error instead:

`[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Could not launch ....
`

So I tried removing all prepopulation of the email and that worked ok.  I don't think it's the \n's either since I tried putting a simple subject and that still failed.  I'm using an old iphone 5 for testing

Here is what did work:

```
launchUrlContactUs() async {
  var url = 'mailto:contactus@yourdomainhere.com?subject=Need Help&body='
      '<Full Name>\n'
      '<Best Contact Method>\n'
      '<Detailed Issue Description>\n'
      '<Frequency of Issue>\n'
      '<Setup/Steps to Reproduce>\n';
  if (Platform.isIOS) {
    //url = url.replaceAll('\n', ' ');
    url = 'mailto:contactus@yourdomainhere.com';
  }
  if (await canLaunch(url)) {
    await launch(url);
  } else {
    throw 'Could not launch $url';
  }
}
```

**Comment by stuartmorgan** [comment]
Your template contains characters that are not valid in URL components; see https://api.dartlang.org/stable/2.4.1/dart-core/Uri/encodeComponent.html

**Comment by jdeltoft** [comment]
Ok, thanks, let me look at that.  Is it odd that it works on Android and not iOS though?

**Comment by stuartmorgan** [comment]
NSURL (on iOS) is strict in what it will accept when constructing a URL. The Android equivalent may be more tolerant of invalid URLs.

**Comment by stuartmorgan** [comment]
Closing; if you continue to have this problem even when you've created a valid and properly escaped URL I can re-open.
