### ISSUE TITLE
Best way to color text the secondary color of current theme?

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#3856]
Material design has a concept of a secondary text color: https://www.google.com/design/spec/style/color.html#color-text-background-colors

I can access this color in flutter using the very verbose: `Theme.of(context).textTheme.caption.color`. I don't want any of the extra styling (weight, fontSize) from from caption or display[1-4]. Using `Colors.black54` directly is not ideal since it wouldn't adapt to theme changes. Is there a less verbose way for me to get the secondary text color of the current theme? Currently I made a package level function but it feels like there should be a better way:

```dart
Color secondary(BuildContext context) =>
  Theme.of(context).textTheme.caption.color;
```

This allows me to say 
```dart
new TextStyle(color: secondary(context))
``` 
instead of 
```dart
new TextStyle(color: Theme.of(context).textTheme.caption.color)
```

**Comment by abarth** [comment]
@Hixie Sounds like `ThemeData` should have a field for this.

**Comment by Hixie** [comment]
Agreed.

**Comment by Hixie** [comment]
The secondary color is the accent color. There's a field on ThemeData for the accent color; we should point to it from the TextStyle docs or some such.

**Comment by patelkrunal78** [comment]
Maybe a bit late... but you can use this:

ThemeData(
    primaryTextTheme: Typography(platform: TargetPlatform.iOS).white,
    textTheme: Typography(platform: TargetPlatform.iOS).white,
)

https://icetutor.com/question/how-to-change-the-entire-themes-text-color-in-flutter
