### ISSUE TITLE
the attribute backgroundColor of the BottomNavigationBar doesn't seem to work

### ISSUE THREAD

**Issue by DianeAnth** [flutter/flutter#38571]

**Comment by HansMuller** [comment]
If you can provide a more complete description of the problem and a small self-contained app that demonstrates it, we'll look into the issue.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
