### ISSUE TITLE
Investigate using /MD (dynamic CRT) for Windows embedding

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#38585]
Currently the Windows engine build is using /MT. Given that we're building a DLL that we expect to load into a Runner that is also using the CRT, we should probably be using /MD so they can share the runtime. My understanding is that we can avoid issues passing objects across the DLL boundary that way as well.

I'm not clear on whether this means clients need to bundle the library, or whether we can rely on it being on the end-user's system. (Even if we do need to bundle it, we already need to bundle DLLs anyway, so adding one more would be better than shipping two static copies).

If there's something I'm missing that would make this a bad idea, input welcome.

/cc @csells @clarkezone

**Comment by shoryukenn** [comment]
Hi,  I am not sure if this is really a good idea.
1. Sharing CRT will make the program more vulnerable and the heap problem will be more serious.
2. Simplify the transfer of some memory object state through the shared heap, which requires all DLLs and EXEs to use the same compiler. If you link to different versions of CRT (for example: plug-in projects), you can't share the same CRT heap as well.
3. It will make the natural physical boundary between DLLs obscure, and the unreasonable call across the boundary that can be blocked by /MT can not be found.

Do we have enough reason to do this?

**Comment by stuartmorgan** [comment]
> which requires all DLLs and EXEs to use the same compiler

Interesting, I thought a core idea of dynamic CRT linking was that it allowed getting CRT updates via the OS (rather than each application needing to recompile and ship a new version to get CRT updates), which seems like it would require cross-version compatibility. Could you point me to more details on this by any chance?

> Do we have enough reason to do this?

Not necessarily, no. Feedback like your comment is extremely useful in evaluating this, given my lack of experience in this domain.

**Comment by stuartmorgan** [comment]
I'm going to close this given the potential toolchain issues, and the potential for unexpected effects if we aren't controlling the version; the size relative to the library itself isn't a major issue based on the exploration with static vs dynamic runtime libraries on the runner/plugin side (where the tradeoff is more significant).
