### ISSUE TITLE
flutter run should delete old build artifacts when switching run modes or device targets

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#3858]
## Steps to Reproduce

1. Create a virtual Nexus 5 at API level 23 (Marshmallow) for x86
2. Wait for it to come online and be visible in `flutter devices`
3. `flutter run` produces the following:

> `Installing app.apk to Android SDK built for x86...`
> `Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]`

Repeat for an x64 device.

## Flutter Doctor

[✓] Flutter (on Linux, channel alpha)
    • Flutter at ...
    • Framework revision cc93170894 (2 days ago), engine revision 98f020ff2d

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0-preview)
    • Android SDK at ...
    • Platform android-N, build-tools 24.0.0-preview
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-119990345-117822431)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2

**Comment by eseidelGoogle** [comment]
My understanding from @jason-simmons is that this should work.  It's possible it has regressed.

@jason-simmons can you take this?  FYI @devoncarew

**Comment by jason-simmons** [comment]
Flutter on an x64 emulator is working on my setup.

Try deleting your app's "build" directory and rerunning "flutter run".

You might get the INSTALL_FAILED_NO_MATCHING_ABIS error if an ARM build of the APK had been left in the build directory by a previous run.  "flutter run" might not realize that the APK needs to be rebuilt because the new device needs an x64 build.

**Comment by DaveShuckerow** [comment]
That does it.  Thanks!

Is there a way of making sure that flutter run will build the new apk in the future if I want to do dev cycles to both emulator and physical device?

**Comment by devoncarew** [comment]
We'll need to add some logic which will clear out build artifacts when switching between emulator or physical devices, or `--debug` / `--release` modes. I'll repurpose this bug for that.

**Comment by sethladd** [comment]
> Is there a way of making sure that flutter run will build the new apk in the future if I want to do dev cycles to both emulator and physical device?

Maybe https://github.com/flutter/flutter/issues/3788 is related?

**Comment by eseidelGoogle** [comment]
I think this was fixed by https://github.com/flutter/flutter/issues/3788?  The `flutter` tool now knows how to do the right thing when switching from --debug to --release, etc.  Please re-open if I'm wrong!

**Comment by abarth** [comment]
Yes, I believe this is fixed.
