### ISSUE TITLE
Define TextStyle with dynamic values

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#38584]
`TextStyle` only has a `const` constructor, so I can't create one using a runtime value like:

```dart
TextStyle(
        color: Theme.of(context).primaryColor, // Error as this is not a const Color
        fontWeight: FontWeight.w500,
        fontSize: 20
);
```

**Comment by jonahwilliams** [comment]
>TextStyle only has a const constructor, so I can't create one using a runtime value like:

That's not true, just don't use `const`. `const` constructor means "may be constructed const," it's not required. In the example you posted, it is likely that some parent is `const` placing you in a `const` context

**Comment by feinstein** [comment]
Sorry, you are right, I was editing old code and didn't see it, my apologies.
