### ISSUE TITLE
Add mouse button support to Window embedding

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#38598]
The embedding API now has the ability to pass mouse buttons through, enabling right click, middle click, etc. It's been wired up in the macOS shell, but still needs to be done for the Windows shell.

**Comment by franciscojma86** [comment]
Closing since the most common buttons are covered.

Opened https://github.com/flutter/flutter/issues/41323 to handle more buttons and other devices

**Comment by SahajRana** [comment]
Hi @stuartmorgan, how can we implement this functionality of mouse buttons?

**Comment by stuartmorgan** [comment]
It was implemented several months ago, per the comment above.
