### ISSUE TITLE
Switch windows embedding to Win32 version

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#38590]
The Win32 embedding has landed, but is not the version being posted. The list of tasks here is:

- [ ] ~Fix #36420~
- [x] Fix #38589

**Comment by clarkezone** [comment]
i have a patch to address #36420 in the works so u can assign to me if u like

**Comment by stuartmorgan** [comment]
The artifact/recipe groundwork is complete, so once we're happy with the state of the Win32 embedding we can switch the `flutter` tooling to pull that instead of the GLFW artifacts (and then stop posting the GLFW artifacts after things have settled; we'll want to leave them for a bit in case we need to revert to it temporarily).

**Comment by stuartmorgan** [comment]
Per discussion elsewhere, we've decided not to block on #36420. Removing that from the checklist.

Addressing that regression is still a high-priority item, but getting more feedback on the Win32 embedding earlier is worth the regression.
