### ISSUE TITLE
RenderStack object was given an infinite size during layout

### ISSUE THREAD

**Issue by lliuwenlong** [flutter/flutter#38596]
RenderStack object was given an infinite size during layout

**Comment by dnfield** [comment]
Unfortunately, this report does not have any actionable information - it's not clear if this is a bug in user code, a bug in the framework, or something else entirely.

Please feel free to re-open if you can add the following information:

1. The version of Flutter you're using
2. The output of `flutter doctor -v`
3. The full exception you see
4. A minimal reproduction that leads to this exception.

**Comment by snnmeatball** [comment]
#38596
