### ISSUE TITLE
Implement cursor enter/leave in Windows embedding

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#38591]
Based on discussion with @clarkezone, my understanding is that the Win32 embedding doesn't yet implement mouse enter/leave, which means there may be stuck hover effects depending on what's under the mouse at the point where the cursor exits the window.

**Comment by hayhv** [comment]
I tested and has been an errro occurrent. I think you need release state down of mouse  before call SendPointerLeave

![error](https://user-images.githubusercontent.com/6427590/65524527-26857380-df18-11e9-9c01-6b98e5e8fa45.png)

**Comment by stuartmorgan** [comment]
@hayhv Please file a new bug for the error you are seeing, with steps to reproduce and the full stack (the most relevant part is cut off in your screenshot). And in general, please paste stacks rather than pictures of them, so they are searchable.
