### ISSUE TITLE
If I swipe up hard in card_collection, it goes off to infinity

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#386]
STEPS TO REPRODUCE:
1. Run card_collection.
2. Swipe up so fast that a single swipe from the top is enough to swipe all 27 items up.

ACTUAL RESULTS
You see the items scroll up until the list is empty, and you can't scroll back.

EXPECTED RESULTS
Bounce at the bottom.

**Comment by abarth** [comment]
Seems to work correctly now.  Please re-open if you can still reproduce the issue.
