### ISSUE TITLE
Padding vs Margin

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#3860]
Is there a real difference between padding vs margins? I’ve been using padding in some places that really should be thought of as margins. This is because it’s obvious from the Padding widget that I’m not doing anything else. Using a container with margin you have to look closer to see if anything else is being done with the container. This also seems to be what some flutter widgets do (button bar is wrapped in padding that is more of a margin in my opinion)

Pretty much the only time I actually use margin is if I want a container with both margin and padding.

**Comment by eseidelGoogle** [comment]
CC @Hixie

**Comment by abarth** [comment]
> Is there a real difference between padding vs margins?

The difference is only in relation to the `decoration` of the `Container`.  The margin is outside the decoration whereas the padding is inside the decoration.  Otherwise, they're the same thing (empty space of a certain size).

**Comment by Hixie** [comment]
I don't really know what to document or where to document it, so in the absence of something more actionable, I'm going to close this.

**Comment by amreniouinnovent** [comment]
@Hixie I wonder why all widget don't have padding and margin in it?

**Comment by Hixie** [comment]
See https://gitter.im/flutter/flutter?at=58ff58a908c00c092ab41dc9
