### ISSUE TITLE
Crash on release mode

### ISSUE THREAD

**Issue by GyuriMajercsik** [flutter/flutter#38619]
I have a crash reported on Google Play with the following stacktrace: 

```
#00  pc 00000000000173a8  /system/lib64/egl/libGLES_mali.so
  #01  pc 00000000000194bc  /system/lib64/egl/libGLES_mali.so (__egl_platform_destroy_surface_android+124)
  #02  pc 000000000006f210  /system/lib64/egl/libGLES_mali.so
  #03  pc 000000000006fa60  /system/lib64/egl/libGLES_mali.so
  #04  pc 000000000006fc50  /system/lib64/egl/libGLES_mali.so
  #05  pc 000000000006bfdc  /system/lib64/egl/libGLES_mali.so (eglCreateWindowSurface+84)
  #06  pc 000000000002b898  /system/lib64/libEGL.so (eglCreateWindowSurface+412)
  #07  pc 0000000000028c88  /system/lib64/libhwui.so
  #08  pc 00000000000253b4  /system/lib64/libhwui.so
  #09  pc 00000000000297fc  /system/lib64/libhwui.so
  #10  pc 00000000000296c4  /system/lib64/libhwui.so
  #11  pc 000000000002afe0  /system/lib64/libhwui.so
  #12  pc 000000000002c438  /system/lib64/libhwui.so (_ZN7android10uirenderer12renderthread12RenderThread10threadLoopEv+124)
  #13  pc 000000000001640c  /system/lib64/libutils.so (_ZN7android6Thread11_threadLoopEPv+208)
  #14  pc 0000000000092bf0  /system/lib64/libandroid_runtime.so (_ZN7android14AndroidRuntime15javaThreadShellEPv+96)
  #15  pc 0000000000015c5c  /system/lib64/libutils.so
  #16  pc 00000000000684e4  /system/lib64/libc.so (_ZL15__pthread_startPv+52)
  #17  pc 000000000001d544  /system/lib64/libc.so (__start_thread+16)
```

The release was built with `flutter build appbundle`, so it should contain both 32 and 64 bit versions. The used Flutter version is:` Flutter 1.7.8+hotfix.4 channel stable.`

**Comment by BondarenkoStas** [comment]
@GyuriMajercsik Is it still relevant? Is there any more information you can provide?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
