### ISSUE TITLE
Improve invalid primary color Material ThemeData exception report

### ISSUE THREAD

**Issue by nuarneuer20** [flutter/flutter#38616]
## Steps to Reproduce

Hi,

I've just had the following error occurring in my flutter project.

It says to report it, so I have!

Let me know if there's anything further I can help with. I haven't yet found a flaw in my code that is causing this - but that doesn't mean there isn't one!

Many thanks,

Nuar

## Logs

I/flutter (12320): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12320): The following assertion was thrown building WidgetsApp-[GlobalObjectKey
I/flutter (12320): _MaterialAppState#dbb31](dirty, state: _WidgetsAppState#0f7c8):
I/flutter (12320): 'package:flutter/src/widgets/title.dart': Failed assertion: line 24 pos 15: 'color != null &&
I/flutter (12320): color.alpha == 0xFF': is not true.
I/flutter (12320):
I/flutter (12320): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (12320): more information in this error message to help you determine and fix the underlying cause.
I/flutter (12320): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (12320):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (12320):
I/flutter (12320): When the exception was thrown, this was the stack:
I/flutter (12320): #2      new Title 
package:flutter/…/widgets/title.dart:24
I/flutter (12320): #3      _WidgetsAppState.build 
package:flutter/…/widgets/app.dart:1181
I/flutter (12320): #4      StatefulElement.build 
package:flutter/…/widgets/framework.dart:3921
I/flutter (12320): #5      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3835
I/flutter (12320): #6      Element.rebuild 
package:flutter/…/widgets/framework.dart:3656
I/flutter (12320): #7      ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:3818
I/flutter (12320): #8      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:3960
I/flutter (12320): #9      ComponentElement.mount 
package:flutter/…/widgets/framework.dart:3813
I/flutter (12320): #10     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3052
I/flutter (12320): #11     Element.updateChild 
package:flutter/…/widgets/framework.dart:2855
I/flutter (12320): #12     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3846
I/flutter (12320): #13     Element.rebuild 
package:flutter/…/widgets/framework.dart:3656
I/flutter (12320): #14     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:3818
I/flutter (12320): #15     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:3813
I/flutter (12320): #16     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3052
I/flutter (12320): #17     Element.updateChild 
package:flutter/…/widgets/framework.dart:2855
I/flutter (12320): #18     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3846
I/flutter (12320): #19     Element.rebuild 
package:flutter/…/widgets/framework.dart:3656
I/flutter (12320): #20     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:3818
I/flutter (12320): #21     StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:3960
I/flutter (12320): #22     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:3813
I/flutter (12320): #23     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3052
I/flutter (12320): #24     Element.updateChild 
package:flutter/…/widgets/framework.dart:2855
I/flutter (12320): #25     RenderObjectToWidgetElement._rebuild 
package:flutter/…/widgets/binding.dart:933
I/flutter (12320): #26     RenderObjectToWidgetElement.mount 
package:flutter/…/widgets/binding.dart:904
I/flutter (12320): #27     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> 
package:flutter/…/widgets/binding.dart:850
I/flutter (12320): #28     BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2294
I/flutter (12320): #29     RenderObjectToWidgetAdapter.attachToRenderTree 
package:flutter/…/widgets/binding.dart:849
I/flutter (12320): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget 
package:flutter/…/widgets/binding.dart:736
I/flutter (12320): #31     runApp 
package:flutter/…/widgets/binding.dart:780
I/flutter (12320): #32     main 
package:flutter_travel/main.dart:4
I/flutter (12320): #33     _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:200:25)
I/flutter (12320): #38     _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:192:5)
I/flutter (12320): #39     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:300:19)
I/flutter (12320): #40     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:171:12)
I/flutter (12320): (elided 6 frames from class _AssertionError and package dart:async)
I/flutter (12320): ════════════════════════════════════════════════════════════════════════════════════════════════════
D/EGL_emulation(12320): eglMakeCurrent: 0xd319b980: ver 2 0 (tinfo 0xe6fff690)

## Screenshot: 

![Screenshot_1565860244](https://user-images.githubusercontent.com/41313228/63086037-913ea900-bf81-11e9-9ca3-cc69191d8e06.png)

```
```

[√] Flutter (Channel dev, v1.6.0, on Microsoft Windows [Version 10.0.17134.950], locale en-US)
    • Flutter version 1.6.0 at C:\Users\anwar\Documents\flutter
    • Framework revision ed90d05596 (3 months ago), 2019-05-14 17:09:29 -0700
    • Engine revision 832cdacc6f
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\anwar\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\anwar\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.37.0)
    • VS Code at C:\Users\anwar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] VS Code, 64-bit edition (version 1.25.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

## My Code:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_travel/CustomShapeClipper.dart';

void main() => runApp(MaterialApp(
  title: 'Flight Ticket',
  debugShowCheckedModeBanner: false,
  home: HomeScreen(),
  theme: appTheme,
));

Color firstColor = Color(0xFFF47D15);
Color secondColor = Color(0xFFEF772C);

ThemeData appTheme = ThemeData(
  primaryColor: Color(0xFF3791A),
  fontFamily: 'Oxygen'
);

List<String> locations = ['Boston (BOS)', 'New York City (JFK)'];

class HomeScreen extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: <Widget>[
          HomeScreenTopart(),
        ],
      ),
    );
  }
}

const TextStyle dropDownLabelStyle = TextStyle(color: Colors.white, fontSize: 16.0);
const TextStyle dropDownMenuItemStyle = TextStyle(color: Colors.black, fontSize: 16.0);

//Top Part of Screen Ui
class HomeScreenTopart extends StatefulWidget {
  HomeScreenTopart({Key key}) : super(key: key);

  _HomeScreenTopartState createState() => _HomeScreenTopartState();
}

class _HomeScreenTopartState extends State<HomeScreenTopart> {

  var selectedLocationIndex = 0;
  var isFlightSelected = true;

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        ClipPath(clipper: CustomShapeClipper(),
          child: Container(
            height: 400.0,  
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [
                  firstColor,
                  secondColor
                ]
              )
            ),
            child: Column(
              children: <Widget>[
                SizedBox(height: 50.0),
                Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: Row(
                    children: <Widget>[
                      Icon(Icons.location_on, color: Colors.white),
                      SizedBox(width: 16.0),
                      PopupMenuButton(
                        onSelected: (index){
                          setState(() {
                           selectedLocationIndex = index; 
                          });
                        },
                        child: Row(
                          children: <Widget>[
                            Text(locations[selectedLocationIndex], style: dropDownLabelStyle),
                            Icon(Icons.keyboard_arrow_down, color: Colors.white,)
                          ],
                        ),
                        itemBuilder: (BuildContext context) => <PopupMenuItem<int>>[
                          PopupMenuItem(
                            child: Text(locations[0], style: dropDownMenuItemStyle),
                            value: 0,
                          ),
                          PopupMenuItem(
                            child: Text(locations[1], style: dropDownMenuItemStyle),
                            value: 1,
                          )
                        ],
                      ),
                      Spacer(),
                      Icon(Icons.settings, color: Colors.white)
                    ],
                  ),
                ),
                SizedBox(height: 50.0),
                Text('Where would\nyou want to go?', 
                style: TextStyle(
                  fontSize: 24.0, 
                  color: Colors.white
                  ),
                  textAlign: TextAlign.center,
                ),
                SizedBox(height: 30.0),
                Padding(
                  padding: EdgeInsets.symmetric(horizontal: 32.0),
                  child: Material(
                    elevation: 5.0,
                    borderRadius: BorderRadius.all(Radius.circular(30.0)),
                    child: TextField(
                      controller: TextEditingController(text: locations[1]),
                      style: dropDownMenuItemStyle,
                      cursorColor: appTheme.primaryColor,
                      decoration: InputDecoration(
                        contentPadding: EdgeInsets.symmetric(horizontal: 32.0, vertical: 14.0),
                        suffixIcon: Material(
                          elevation: 2.0,
                          borderRadius: BorderRadius.all(Radius.circular(30.0)),
                          child: Icon(Icons.search, color: Colors.black),
                        ),
                        border: InputBorder.none
                      ),
                    ),
                  ),
                ),
                SizedBox(height: 20.0),
                Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  children: <Widget>[
                    InkWell(
                      onTap: (){
                        setState(() {
                         isFlightSelected = true; 
                        });
                      },
                      child: ChoiceChip(Icons.flight_takeoff, "Flights", isFlightSelected)
                    ),
                    SizedBox(width: 20.0),
                    InkWell(
                      onTap: () {
                        setState(() {
                         isFlightSelected = false; 
                        });
                      },
                      child: ChoiceChip(Icons.hotel, "Hotels", !isFlightSelected)
                    ),
                  ],
                )
              ],
            ),
          )
        )
      ],
    );
  }
}

class ChoiceChip extends StatefulWidget {
  
  final IconData icon;
  final String text;
  final bool isSelected;

  ChoiceChip(this.icon, this.text, this.isSelected);

  _ChoiceChipState createState() => _ChoiceChipState();
}

class _ChoiceChipState extends State<ChoiceChip> {
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.symmetric(horizontal: 18.0, vertical: 8.0),
      decoration: widget.isSelected ? BoxDecoration(
        color: Colors.white.withOpacity(0.15), 
        borderRadius: BorderRadius.all(
          Radius.circular(20.0),
        )
      ) : null,
      child: Row(
        mainAxisSize: MainAxisSize.min,
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: <Widget>[
          Icon(
            widget.icon,
            size: 20.0,
            color: Colors.white,
          ),
          SizedBox(width: 8.0),
          Text(
            widget.text,
            style: TextStyle(
              color: Colors.white,
              fontSize: 16.0
            )
          )
        ],
      ),
    );
  }
}

```

**Comment by KirolousNashaat** [comment]
primaryColor: Color(0xFF3791A)
Alpha != 0xff
I think u forgot 'f' at the start

**Comment by HansMuller** [comment]
@KirolousNashaat yes, that's correct. Colors usually specify all 8 hex digits. 

This isn't really a bug although the error message could be improved by displaying the problematic color value.

**Comment by HansMuller** [comment]
I changed this issue's title to focus on the problem that should be fixed.

**Comment by nuarneuer20** [comment]
I didn't notice that. It's working now. Thanks a lot!!
