### ISSUE TITLE
Crash on compiling iPhone when missing pubspec.yaml version: xcrun exited abnormally

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#38610]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -d iphone

## exception

ProcessException: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Could not hardlink copy /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Containers/Bundle/Application/6C2DD5C8-0BDC-4F58-82E2-98AF3EE83439/Runner.app to /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Library/Caches/com.apple.mobile.installd.staging/temp.7KjtG1/extracted/Payload/Runner.app with manifest /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Library/Caches/com.apple.mobile.installd.staging/temp.7KjtG1/extracted/com.apple.deltainstallcommands.com.example.example
Could not hardlink copy /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Containers/Bundle/Application/6C2DD5C8-0BDC-4F58-82E2-98AF3EE83439/Runner.app to /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Library/Caches/com.apple.mobile.installd.staging/temp.7KjtG1/extracted/Payload/Runner.app with manifest /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Library/Caches/com.apple.mobile.installd.staging/temp.7KjtG1/extracted/com.apple.deltainstallcommands.com.example.example
Underlying error (domain=MIInstallerErrorDomain, code=8):
	Could not hardlink copy /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Containers/Bundle/Application/6C2DD5C8-0BDC-4F58-82E2-98AF3EE83439/Runner.app to /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Library/Caches/com.apple.mobile.installd.staging/temp.7KjtG1/extracted/Payload/Runner.app with manifest /Users/timsneath/Library/Developer/CoreSimulator/Devices/58EC574B-DF41-477A-BC0A-0BC6B51AEB56/data/Library/Caches/com.apple.mobile.installd.staging/temp.7KjtG1/extracted/com.apple.deltainstallcommands.com.example.example
  Command: /usr/bin/xcrun simctl install 58EC574B-DF41-477A-BC0A-0BC6B51AEB56 /Users/timsneath/git/flutter_flip_view/example/build/ios/iphonesimulator/Runner.app

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:145:16)
#2      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:437:31)
<asynchronous suspension>
#3      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:339:15)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:378:54)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.8.5-pre.167, on Mac OS X 10.14.6 18G87, locale en-US)
    [32m•[39m Flutter version 1.8.5-pre.167 at /Users/timsneath/flutter
    [32m•[39m Framework revision 8cf40e90b0 (35 minutes ago), 2019-08-15 02:32:36 -0400
    [32m•[39m Engine revision 426ea8dba6
    [32m•[39m Dart version 2.5.0 (build 2.5.0-dev.2.0 e35e8833ee)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    [32m•[39m Android SDK at /Users/timsneath/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.1
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 10.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.3, Build version 10G8
    [32m•[39m CocoaPods version 1.7.5

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 37.1.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m VS Code (version 1.37.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.3.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m iPhone Xʀ • 58EC574B-DF41-477A-BC0A-0BC6B51AEB56 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
    [32m•[39m Chrome    • chrome                               • web-javascript • Google Chrome 76.0.3809.100 


[32m•[39m No issues found!
```

**Comment by timsneath** [comment]
I cleared this by deleting the `ios/` folder and running `flutter create .`, for others running into the same issue. We should have a better error message here if we can't guard against this condition.

**Comment by jmagman** [comment]
Possibly related to the CFBundleShortVersionString and CFBundleVersion not being readable from the Info.plist?
Can you attach /Users/timsneath/git/flutter_flip_view/example/build/ios/iphonesimulator/Runner.app/Info.plist?

**Comment by timsneath** [comment]
Sure! Here it is (zipped):
[Info.plist.zip](https://github.com/flutter/flutter/files/3509052/Info.plist.zip)

The original `Info.plist` (that is, `example/ios/Runner/Info.plist`) is here:
[Info.plist.zip](https://github.com/flutter/flutter/files/3509058/Info.plist.zip)

**Comment by jmagman** [comment]
Hm, the CFBundleShortVersionString and CFBundleVersion are missing from the app's Info.plist.
You are after the commit where I would have expected this to be fixed (https://github.com/flutter/flutter/pull/37036).
What's your pubspec version?

**Comment by timsneath** [comment]
I'm starting vacation today, so let me point you at the repo:
https://github.com/timsneath/flutter_flip_view/blob/master/example/pubspec.yaml

**Comment by joeblew99** [comment]
@jmagman what is the min pubspec that will enforce this ?

I am on master channel, and used:
flutter create --org $(ORG) --template=plugin -i objc -a java testproject

So i would have thought that the "flutter create" would do the right thing regarding versioning, etc ?

crash log:

```

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -d iPhone SE

## exception

ProcessException: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Could not hardlink copy /Users/apple/Library/Developer/CoreSimulator/Devices/18D80E89-328E-4BA6-954D-50CD74F3C3C3/data/Containers/Bundle/Application/9E900E6C-E907-4602-BDAB-8A83A20E1F58/Runner.app to /Users/apple/Library/Developer/CoreSimulator/Devices/18D80E89-328E-4BA6-954D-50CD74F3C3C3/data/Library/Caches/com.apple.mobile.installd.staging/temp.fBo5xF/extracted/Payload/Runner.app with manifest /Users/apple/Library/Developer/CoreSimulator/Devices/18D80E89-328E-4BA6-954D-50CD74F3C3C3/data/Library/Caches/com.apple.mobile.installd.staging/temp.fBo5xF/extracted/com.apple.deltainstallcommands.mycompany.myprojectExample
Could not hardlink copy /Users/apple/Library/Developer/CoreSimulator/Devices/18D80E89-328E-4BA6-954D-50CD74F3C3C3/data/Containers/Bundle/Application/9E900E6C-E907-4602-BDAB-8A83A20E1F58/Runner.app to /Users/apple/Library/Developer/CoreSimulator/Devices/18D80E89-328E-4BA6-954D-50CD74F3C3C3/data/Library/Caches/com.apple.mobile.installd.staging/temp.fBo5xF/extracted/Payload/Runner.app with manifest /Users/apple/Library/Developer/CoreSimulator/Devices/18D80E89-328E-4BA6-954D-50CD74F3C3C3/data/Library/Caches/com.apple.mobile.installd.staging/temp.fBo5xF/extracted/com.apple.deltainstallcommands.mycompany.myprojectExample
Underlying error (domain=MIInstallerErrorDomain, code=8):
	Could not hardlink copy /Users/apple/Library/Developer/CoreSimulator/Devices/18D80E89-328E-4BA6-954D-50CD74F3C3C3/data/Containers/Bundle/Application/9E900E6C-E907-4602-BDAB-8A83A20E1F58/Runner.app to /Users/apple/Library/Developer/CoreSimulator/Devices/18D80E89-328E-4BA6-954D-50CD74F3C3C3/data/Library/Caches/com.apple.mobile.installd.staging/temp.fBo5xF/extracted/Payload/Runner.app with manifest /Users/apple/Library/Developer/CoreSimulator/Devices/18D80E89-328E-4BA6-954D-50CD74F3C3C3/data/Library/Caches/com.apple.mobile.installd.staging/temp.fBo5xF/extracted/com.apple.deltainstallcommands.mycompany.myprojectExample
  Command: /usr/bin/xcrun simctl install 18D80E89-328E-4BA6-954D-50CD74F3C3C3 /Users/apple/workspace/go/src/github.com/worldiety/goup/example/myproject/example/build/ios/iphonesimulator/Runner.app

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:339:7)
<asynchronous suspension>
#1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:145:16)
#2      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:435:31)
<asynchronous suspension>
#3      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:338:15)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:378:54)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.10.1-pre.41, on Mac OS X 10.14.6 18G95, locale en-DE)
    [32m•[39m Flutter version 1.10.1-pre.41 at /Users/apple/fvm/master
    [32m•[39m Framework revision 5a3a46ada2 (33 hours ago), 2019-09-07 18:37:41 -0400
    [32m•[39m Engine revision c9ea4dba8d
    [32m•[39m Dart version 2.5.0 (build 2.5.0-dev.4.0 ec7ec4ecf7)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/apple/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = /Users/apple/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [31m✗[39m Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 10.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.3, Build version 10G8
    [32m•[39m CocoaPods version 1.7.5

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 39.0.3
    [32m•[39m Dart plugin version 191.8423
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m VS Code (version 1.38.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.4.1

[32m[✓][39m Connected device (2 available)
    [32m•[39m iPhone SE • 18D80E89-328E-4BA6-954D-50CD74F3C3C3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
    [32m•[39m Chrome    • chrome                               • web-javascript • Google Chrome 76.0.3809.132 


[33m![39m Doctor found issues in 1 category.
```

```

**Comment by jmagman** [comment]
@timsneath (sorry for the delay).
The [pubspec.yaml](https://github.com/timsneath/flutter_flip_view/blob/master/example/pubspec.yaml) is missing a `version:`.  The version is required to deploy on iOS.  Can you confirm when you add it this works?

`flutter run` when targeting an iOS device, and `flutter build ios` could check for a version and give a better error.

@joeblew99 Are you also missing a `version:` in your pubspec.yaml?  The `flutter create` templates should provide one by default.

**Comment by jmagman** [comment]
@joeblew99 Should be `version: 1.0.0+1` by default.

**Comment by timsneath** [comment]
Oh, that's interesting: thanks for spotting that. I must have deleted it by accident... 

Yeah, it would be great to have a check for this since it's not possible for a mortal like me to divine the source of the error from the message; and it's not immediately obvious which fields in `pubspec.yaml` are mandatory. (An alternative _might_ be to have a default value for version if it's not specified, I suppose?)

**Comment by jmagman** [comment]
> An alternative _might_ be to have a default value for version if it's not specified, I suppose?

Unfortunately App Store submissions require these numbers be incremented on every submission, so a default would work for the first submission but not any subsequent ones.  
Prime spot for a tool exit with a nice message in an `else` here:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/xcodeproj.dart#L171

> it's not possible for a mortal like me

ha, me either, I was scratching my head on these problems for awhile!

**Comment by zanderso** [comment]
Assigned @jmagman to take a look at adding the tool exit.

**Comment by jmagman** [comment]
> > An alternative _might_ be to have a default value for version if it's not specified, I suppose?
> 
> Unfortunately App Store submissions require these numbers be incremented on every submission, so a default would work for the first submission but not any subsequent ones.

I [decided to add default number and version fallback](https://github.com/flutter/flutter/pull/40611), but warn in the tool that a real one needs to be set before submission to the App Store.
