### ISSUE TITLE
[web]: Fidelity with animated transform

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#38615]
See https://timsneath.github.io/flutter_flip_view/#/

Gradient doesn't rotate cleanly with transform. 

Source at https://github.com/timsneath/flutter_flip_view/tree/master/example

**Comment by ferhatb** [comment]
Fixed via https://github.com/flutter/flutter_web/commit/50f7fcfce93ecf557f86b3a345c9c460299ef5e5
