### ISSUE TITLE
Flutter Tool currently does not allow different plugin class names for android and ios impls

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#38628]

**Comment by iskakaushik** [comment]
@stuartmorgan i'm working on the proposal as we speak :-) filing some TODOs as I implement this proposal piece-wise.

**Comment by jmagman** [comment]
[Is this done?](https://github.com/flutter/flutter/issues/44287)  Or is this documenting a bug here where you can't have different values for pluginClass across different platforms?

**Comment by stuartmorgan** [comment]
This is fixed by the new schema.
