### ISSUE TITLE
Visual examples to accompany new TweenAnimationBuilder

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#38625]
Include animated diagrams to illustrate the sample snippets provided for the new `TweenAnimationBuilder`. 
This change will have to land first before diagrams can be generated. (https://github.com/flutter/flutter/pull/38317)

**Comment by Piinks** [comment]
@brianegan Are you interested in adding this to your next batch? :)

**Comment by brianegan** [comment]
@Piinks Hey there -- I think the current round of API doc diagrams will be my last for this round of work! I'll be moving back to updating the Flutter Cookbook for the next few weeks. Happy to add this one to a "working list" of future ideas if I join back in on this documentation :)

**Comment by Piinks** [comment]
Sounds great! Thanks!

**Comment by Piinks** [comment]
This is actually done and running on dartpad in the api docs! :)
