### ISSUE TITLE
Significant regression in ios after_config_change_build_debug_millis benchmark

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#38627]
Our "build_benchmark_ios after_config_change_build_debug_millis" benchmark has gotten significantly worse in the past three weeks (2x build times), with what looks like two separate regressions.

The first regression like it's one of (https://github.com/flutter/flutter/pull/37023, https://github.com/flutter/flutter/pull/36598):

![XUd3KEHAzyL](https://user-images.githubusercontent.com/15253456/63115720-a6e5ab80-bf4c-11e9-994a-d5e57336cae6.png)

The second regression looks like it was one of (https://github.com/flutter/flutter/pull/38495, https://github.com/flutter/flutter/pull/38498):

![RPgDXHzsqxU](https://user-images.githubusercontent.com/15253456/63115722-a9e09c00-bf4c-11e9-8001-039237d839b7.png)

**Comment by jonahwilliams** [comment]
The underlying cause is likely my removal of the fingerprinter in kernel. This should have been disabled since we know that it is not sufficient to guarantee correct caching.

Re introducing this would be risking the correctness of builds

**Comment by tvolkert** [comment]
I thought you removed the fingerprinter longer ago than 3 weeks, though?

**Comment by tvolkert** [comment]
Does that also explain the two separate regressions?

**Comment by stuartmorgan** [comment]
Suggestions on how to proceed for the second one? I'm not sure what the normal process here for suspected engine-roll-related regressions is. I inherited a ~50-commit (5 day, IIRC) engine roll that had broken the tree; I had to revert it, get a Dart fix landed and rolled into the engine, then re-land the engine roll, which is what that 60-commit PR was. I have no idea how I would go about trying to tease out individual changes there for a Flutter-level test.

Nor is it currently possible to revert that change at this point to see if that bring it back down without reverting other changes that have landed on top of it (and doing so would likely cause a new cascade of issues).

**Comment by aam** [comment]
> The underlying cause is likely my removal of the fingerprinter in kernel. This should have been disabled since we know that it is not sufficient to guarantee correct caching.

Did we get to the root cause for this, or it was more empirical?

> Suggestions on how to proceed for the second one?  

Bisecting large roll locally on just one or two benchmarks should still be possible because breakages that required incremental fixes likely didn't affect those benchmark(dart fix was for windows build, for example).

**Comment by stuartmorgan** [comment]
> Bisecting large roll locally on just one or two benchmarks

Is there a description somewhere of how to do local debugging of benchmarks? My experience is that benchmarks are often very sensitive to the specific configuration they are tested on.

**Comment by aam** [comment]
Hardware issues aside(it helps to have exact same model of android phone or iphone available), normally you should be able to run benchmarks locally with locally-built engine like so:
```
cd $FH/flutter/dev/devicelab
$FH/flutter/bin/cache/dart-sdk/bin/dart bin/run.dart -t hot_mode_dev_cycle_linux__benchmark --local-engine android_debug  
```
For some benchmarks you need to tweak their source code so it indeed uses local engine:
```
diff --git a/dev/devicelab/lib/tasks/hot_mode_tests.dart b/dev/devicelab/lib/tasks/hot_mode_tests.dart
index 28991044b..1e36b682f 100644
--- a/dev/devicelab/lib/tasks/hot_mode_tests.dart
+++ b/dev/devicelab/lib/tasks/hot_mode_tests.dart
@@ -23,7 +23,7 @@ TaskFunction createHotModeTest() {
     final File benchmarkFile = file(path.join(_editedFlutterGalleryDir.path, 'hot_benchmark.json'));
     rm(benchmarkFile);
     final List<String> options = <String>[
-      '--hot', '-d', device.deviceId, '--benchmark', '--verbose', '--resident',
+      '--local-engine', 'android_debug', '--hot', '-d', device.deviceId, '--benchmark', '--verbose', '--resident',
     ];
     int hotReloadCount = 0;
     Map<String, dynamic> twoReloadsData;
```

**Comment by jonahwilliams** [comment]
I disabled the fingerprinter, but didn't remove it from everywhere. I either missed this location or through reland/revert it was restored.

**Comment by digiter** [comment]
The chart seems no longer a regression.
