### ISSUE TITLE
Disable analytics pings when flutter tool is used by other tools

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3862]
We're seeing a lot of pings for the 'flx' command. This is not a normal user-driven command. It's possible that a bot or other wrapping command is calling into `flx`. In order to have analytics reflect actual user intention, I wonder if we can look to see if another one of our tools is driving `flx` and if so, disable analytics pings.

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by Hixie** [comment]
Could it be that we're seeing "flutter run" invoke "flutter build flx" or something?

Do we have any sort of metrics on whether this is happening in one particular geographic area or all over or something?

**Comment by sethladd** [comment]
Actually, we do. "Mountain View" :)

**Comment by Hixie** [comment]
Oh interesting. Probably us then. Maybe one of our bots is doing it? Or someone at home? What kind of volume are we seeing vs other Mountain View traffic?

**Comment by sethladd** [comment]
`ios/.generated/Tools/common/PackagerInvoke` calls `flutter build flx`. Can we also say `--also-dont-ping-analytics` from that script?

**Comment by devoncarew** [comment]
Yup, easy enough.

**Comment by devoncarew** [comment]
Thanks for investigating!
