### ISSUE TITLE
Make it clearer on how to "pin" a button to the bottom of a list

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#38640]
@Piinks recently fixed some issues with `SliverFillRemaining` that should make it easier to have a scroll list where a button (or any last item) is "pinned" to the bottom of the screen or the bottom of the list, whichever is higher.  However, it seems like this is probably not documented very well and could use an example.

It would also be nice to make it clearer what to use instead of things like `SingleChildScrollView` or `ListView` for cases like this, since those don't take slivers. 

/cc @goderbauer @slightfoot @evelyne24

**Comment by Piinks** [comment]
The aforementioned recent work for reference: https://github.com/flutter/flutter/pull/35810

**Comment by Piinks** [comment]
Also related to : https://github.com/flutter/flutter/issues/35753

**Comment by Piinks** [comment]
While we buff up the docs, here is a solution for current seekers:

![sfr3](https://user-images.githubusercontent.com/16964204/63304286-4f6e7500-c297-11e9-8348-1c1d5066b51b.gif)

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Home());
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('AppBar'),
      ),
      body: SafeArea(
        child: CustomScrollView(
          slivers: <Widget>[
            SliverToBoxAdapter(
              child: Container(
                color: Colors.amber,
                height: 150,
              ),
            ),
            SliverFillRemaining(
              hasScrollBody: false,
              // fillOverscroll: true, // Set true to change overscroll behavior. Purely preference.
              child: Align(
                alignment: Alignment.bottomCenter,
                child: RaisedButton(
                  child: Text('Bottom'),
                  onPressed: () {},
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}

```

**Comment by Piinks** [comment]
And another, which illustrates behavior when the list exceeds the size of the viewport: 

![sfr4](https://user-images.githubusercontent.com/16964204/63304695-cce6b500-c298-11e9-94a3-c939b5e18d86.gif)


```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Home());
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('AppBar'),
      ),
      body: CustomScrollView(
        slivers: <Widget>[
          SliverFixedExtentList(
          itemExtent: 150.0,
          delegate: SliverChildBuilderDelegate(
            (BuildContext context, int index) {
              return Container(
                color:
                    index % 2 == 0 ? Colors.amber[100] : Colors.blue[100],
              );
            },
            childCount: 7,
          ),
        ),
          SliverFillRemaining(
            hasScrollBody: false,
            // fillOverscroll: true, // Set true to change overscroll behavior. Purely preference.
            child: Align(
              alignment: Alignment.bottomCenter,
              child: Padding(
                padding: const EdgeInsets.all(20.0),
                child: RaisedButton(
                  child: Text('Bottom'),
                  onPressed: () {},
                ),
              ),
            ),
          )
        ],
      ),
    );
  }
}

```

**Comment by evelyne24** [comment]
> While we buff up the docs, here is a solution for current seekers:
> 
> ![sfr3](https://user-images.githubusercontent.com/16964204/63304286-4f6e7500-c297-11e9-8348-1c1d5066b51b.gif)
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:flutter/rendering.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(home: Home());
>   }
> }
> 
> class Home extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('AppBar'),
>       ),
>       body: SafeArea(
>         child: CustomScrollView(
>           slivers: <Widget>[
>             SliverToBoxAdapter(
>               child: Container(
>                 color: Colors.amber,
>                 height: 150,
>               ),
>             ),
>             SliverFillRemaining(
>               hasScrollBody: false,
>               // fillOverscroll: true, // Set true to change overscroll behavior. Purely preference.
>               child: Align(
>                 alignment: Alignment.bottomCenter,
>                 child: RaisedButton(
>                   child: Text('Bottom'),
>                   onPressed: () {},
>                 ),
>               ),
>             )
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```

Thanks for this example. This is not the behaviour I want. I don't want my screen to be scrollable if there is not enough content to do so, which is the case you are showing in your example above with Slivers.

**Comment by Piinks** [comment]
Thanks for the feedback @evelyne24! 
This specific gif of the solution shows `BouncingScrollPhysics` by default as it is running on iOS. By using `ClampingScrollPhysics`, which is the default for Android, your described use case can be satisfied.

Since we are using a `CustomScrollView`, setting the `ScrollPhysics` is easily done to override defaults and have a consistent scrolling behavior across all platforms. Just use the `physics` parameter:

```dart
//...
CustomScrollView(
  physics: ClampingScrollPhysics(),
  slivers: <Widget>[ 
//...
```

**Comment by dnfield** [comment]
I wonder if you'd want something where you could set those dynamically based on whether there's additional scrollable content, so that you'd still get the expected platform physics when it does scroll.

**Comment by Piinks** [comment]
Could you do that by checking the ScrollPosition, set the ScrollPhysics dynamically? I'm testing that now.

**Comment by evelyne24** [comment]
> Thanks for the feedback @evelyne24!
> This specific gif of the solution shows `BouncingScrollPhysics` by default as it is running on iOS. By using `ClampingScrollPhysics`, which is the default for Android, your described use case can be satisfied.
> 
> Since we are using a `CustomScrollView`, setting the `ScrollPhysics` is easily done to override defaults and have a consistent scrolling behavior across all platforms. Just use the `physics` parameter:
> 
> ```dart
> //...
> CustomScrollView(
>   physics: ClampingScrollPhysics(),
>   slivers: <Widget>[ 
> //...
> ```

Oh, I will definitely try the `ClampingScrollPhysics`, thanks so much for pointing it out!

**Comment by evelyne24** [comment]
I've tried the above. How do you align a widget in the middle of the screen, like it was in my [original](https://github.com/evelyne24/flutter_layout_weirdness) layout? It just doesn't work. If I have `Column` inside the `CustomScrollView` instead of the `Container` with an `Expanded` widget inside, then the layout crashes.

**Comment by jeeali** [comment]
> While we buff up the docs, here is a solution for current seekers:
> 
> ![sfr3](https://user-images.githubusercontent.com/16964204/63304286-4f6e7500-c297-11e9-8348-1c1d5066b51b.gif)
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:flutter/rendering.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(home: Home());
>   }
> }
> 
> class Home extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('AppBar'),
>       ),
>       body: SafeArea(
>         child: CustomScrollView(
>           slivers: <Widget>[
>             SliverToBoxAdapter(
>               child: Container(
>                 color: Colors.amber,
>                 height: 150,
>               ),
>             ),
>             SliverFillRemaining(
>               hasScrollBody: false,
>               // fillOverscroll: true, // Set true to change overscroll behavior. Purely preference.
>               child: Align(
>                 alignment: Alignment.bottomCenter,
>                 child: RaisedButton(
>                   child: Text('Bottom'),
>                   onPressed: () {},
>                 ),
>               ),
>             )
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```

Thanks @Piinks
