### ISSUE TITLE
FlutterDriver.waitFor is successful and doesn't timeout but the element is not visible on the screen

### ISSUE THREAD

**Issue by snickersv2** [flutter/flutter#38657]
## Steps to Reproduce
Scenario 1
1. Create a scrollable dropdown menu that contains multiple texts
2. Run your app and use Flutter Inspector
3. Notice that the texts not visible on the screen are found on Flutter Inspector
4. Run an integration test and use FlutterDriver.waitFor on a text in the scrollable dropdown that is not yet visible on the screen.
5. Notice it will not timeout (assuming because it is found on Flutter Inspector)

This is why we need flags like isVisible, etc because even though waitFor doesn't timeout, it doesn't mean that it is visible in the screen.

## Logs
/Users/user/Documents/Flutter/sdk/flutter/bin/flutter doctor --verbose
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E226, locale en-US)
• Flutter version 1.7.8+hotfix.4 at /Users/user/Documents/Flutter/sdk/flutter
• Framework revision 20e5931 (3 weeks ago), 2019-07-18 20:04:33 -0700
• Engine revision fee001c93f
• Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
• Android SDK at /Users/user/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-28, build-tools 28.0.3
• ANDROID_HOME = /Users/user/Library/Android/sdk
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 10.2, Build version 10E125
• CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
• ios-deploy 1.9.4

[✓] Android Studio (version 3.3)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 33.4.1
• Dart plugin version 182.5215
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1)
• IntelliJ at /Applications/IntelliJ IDEA CE.app
• Flutter plugin version 33.4.3
• Dart plugin version 191.6183.87

[✓] Connected device (1 available)
• SM A520F • 52105109ea678475 • android-arm64 • Android 8.0.0 (API 26) (emulator)

• No issues found!
Process finished with exit code 0
```

**Comment by BondarenkoStas** [comment]
@snickersv2 If possible, please provide a code example, to be sure to reproduce it correctly.

**Comment by snickersv2** [comment]
@BondarenkoStas we tried to create a dropdown using the following:

Scaffold(
      backgroundColor: AppColors.background,
      body: Center(
        child: Theme(
          data: Theme.of(context).copyWith(canvasColor: AppColors.background),
          child:
          DropdownButtonHideUnderline(
            key: const Key('countryDropDownMenu'),
            child: DropdownButton<String>(
              isExpanded: true,
              iconSize: AppDimen.dropdownSize,
              style: TextStyle(
                  color: AppColors.white,
                  fontSize: AppDimen.fontSize_19,
                  letterSpacing: -0.49),
              icon: Icon(Icons.arrow_down, color: AppColors.white),
              value: selectedLocation,
              hint: SizedBox(
                width: AppDimen.padding_170,
                child: Text("🇺🇸 \ \ United States",
                  style: TextStyle(
                      color: AppColors.white,
                      fontSize: AppDimen.fontSize_19,
                      letterSpacing: -0.49),
                  textAlign: TextAlign.center,
                ),
              ),
              onChanged: (country) {
                setState(() {
                  selectedLocation = country;
                  SelectedCountryInfo.selectedCountry = country.toLowerCase();
                });
              },
              items: countryList.map<DropdownMenuItem<String>>((data) {
                return DropdownMenuItem(
                  value: data.countryName,
                  child: SizedBox(
                    width: AppDimen.padding_170,
                    child: Text(data.countryName,
                      style: TextStyle(
                          color: AppColors.white,
                          fontSize: AppDimen.fontSize_19,
                          letterSpacing: -0.49),
                      textAlign: TextAlign.center,),
                  ),
                );
              }).toList(),
            ),
          ),
        ),
      ),
    );

then in our integration test, we call 

String countryToSelect = 'INPUT A COUNTRY NOT VISIBLE ON THE SCREEN';

await flutterDriver.tap(find.byKey('countryDropDownMenu'));
expect( await isPresent(find.byText(countryToSelect) , flutterDriver), false );

below is the isPresent function:
static Future<bool> isPresent(SerializableFinder finder, FlutterDriver driver,
      {Duration timeout = const Duration(seconds: 1)}) async {
    try {
      await driver.waitFor(finder, timeout: timeout);
      return true;
    } catch (_) {
      return false;
    }
  }

The Flutter inspector is constructed this way below and all the items of the dropdown are in the widget tree even if some are not visible on the display
![image](https://user-images.githubusercontent.com/49699862/64447361-0e949f80-d090-11e9-8d6d-8ee406f2ccf0.png)

**Comment by kalebhermes** [comment]
I just opened #79581 to try and resolve this issue. I added a method `waitForTappable` that will only succeed if the requested widget is 'tappable' or within the view.

**Comment by danagbemava-nc** [comment]
Closing this as the PR that was meant to fix this has been merged.
