### ISSUE TITLE
Attempt to invoke virtual method 'android.view.inputmethod.InputConnection android.view.View.onCreateInputConnection(android.view.inputmethod.EditorInfo)' on a null object reference

### ISSUE THREAD

**Issue by qq3094128766** [flutter/flutter#38668]
io.flutter.plugin.editing.TextInputPlugin.createInputConnection(TextInputPlugin.java:195)
--
2 io.flutter.view.FlutterView.onCreateInputConnection(FlutterView.java:397)
3 android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1351)
4 android.view.inputmethod.InputMethodManager.onPostWindowFocus(InputMethodManager.java:1688)
5 android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:2823)
6 android.view.ViewRootImpl.access$1100(ViewRootImpl.java:174)
7 android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4518)
8 android.os.Handler.dispatchMessage(Handler.java:112)
9 android.os.Looper.loop(Looper.java:216)
10 android.app.ActivityThread.main(ActivityThread.java:7625)
11 java.lang.reflect.Method.invoke(Native Method)
12 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
13 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by dnfield** [comment]
What version of Flutter? Can you provide some code/steps to reproduce this?

**Comment by luffynas** [comment]
I also experienced the same thing. This issue occurs when opening a `WebView` and writing in a field (input type = "text") and characters are not successfully entered into that field. then return to the previous page, and this is where the bug occurs.

dependencies:
webview_flutter: ^0.3.12+1

VS Code (version 1.37.1)
Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-ID)
Device: Nexus-5

**Comment by qq3144225600** [comment]
I have also encountered this problem, that is, the opening of third-party pages in WebView

**Comment by matthew-carroll** [comment]
@luffynas @qq3144225600 I believe the issue that both of you are interested in is specific to the webview plugin. You can follow that issue here: https://github.com/flutter/flutter/issues/36453
