### ISSUE TITLE
keyboard slides up and covers the TextField in flutter

### ISSUE THREAD

**Issue by longdw** [flutter/flutter#38669]
i run my pure flutter project, when keyboard is presented the textfield can move above it, and the widget can self-adaption very well. but when i add flutter module to native project, the keyboard corvers textfield.

i don't know how to solve this problem.

and i post a problem to [stackoverflow](https://stackoverflow.com/questions/57518284/keyboard-slides-up-and-covers-the-textfield-in-flutter/57518615#57518615)

**Comment by dnfield** [comment]
Android, iOS, or both?

/cc @xster

**Comment by longdw** [comment]
in android, i haven't used in iOS yet.

**Comment by longdw** [comment]
@xster @dnfield i found it's ok in iOS. and i found another problem this is [issue](https://github.com/flutter/flutter/issues/38730) that is `setInitialRoute` doesn't work.

**Comment by longdw** [comment]
can anyone help? our project can't go online because of this problem.

**Comment by longdw** [comment]
add `android:windowSoftInputMode="adjustResize"`, it's ok now!
