### ISSUE TITLE
Running flutter leads to BITS Transfer which fails

### ISSUE THREAD

**Issue by Tobi696** [flutter/flutter#38673]
I just installed flutter and ran the flutter command for the first time, which led to:
```
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine fee001c93f25a1e7258e762781a7361f122d29f5...
Downloading the Dart SDK using the BITS service failed, retrying with WebRequest...
```
This process takes an eternity.

**Comment by BondarenkoStas** [comment]
@Tobi696 Is it still relevant?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by azrinsultana** [comment]
I just installed flutter and ran the flutter command (flutter --version) for the first time its showing these
![Screenshot_34](https://user-images.githubusercontent.com/61706762/108057849-60ab6400-707d-11eb-8b73-1f833d78033a.png)

**Comment by iapicca** [comment]
@azrinsultana 

> Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v' please.
> All system setups can be slightly different so its always better to open new issues and reference related issues.
