### ISSUE TITLE
Document the pros and cons of using push vs pushNamed

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#3867]
Right now I’m only using `Navigator.push(context, new MaterialPageRoute(...` I know there are some other options like the `routes` named parameter to `MaterialApp` constructor. What are the pros/cons to each approach? Which do you think we should take?

**Comment by abarth** [comment]
That's a somewhat complex question.  We generally prefer using named routes whenever possible, but many of the advantages of named routes aren't implemented yet.  For example, when Android kills your app and then resumes it, we want to restart the app with the same route as the user previous viewed.  That system will likely be based on the route name.

**Comment by sethladd** [comment]
For better searching: routing

**Comment by jtlapp** [comment]
I have also been trying to answer this question. I encountered [this explanation](https://resocoder.com/2019/04/27/flutter-routes-navigation-parameters-named-routes-ongenerateroute/) by Matej Rešetár:

> While navigation without using named routes is OK for smaller projects, in more complex apps it adds code duplication. This is especially true if you have a route guard to only allow signed-in users enter certain pages, or any other kind of logic which needs to run as the user navigates.

**Comment by jtlapp** [comment]
[This article](https://medium.com/@larsenthomasj/from-flutter-to-flight-3-navigation-8d567d2cb011) by Tom Larsen treats routes like URLs in a stateless web server. Rather than having one page pass objects to the next, he passes object IDs, which the page has to look up. His reason:

> I am not sure if this is entirely the ‘right’ way of doing it, but it feels much cleaner and alleviates some concerns I had about state management in response to lifecycle events.

**Comment by jtlapp** [comment]
Another possible reason is so that page code can be shared between mobile and web apps.

**Comment by pedromassangocode** [comment]
Hi @drewwarren
The following page talks about the difference between push and pushNamed: https://flutter.dev/docs/cookbook/navigation/named-routes

I'm considering this as fixed. If you disagree please feel free to comment and I will reopen it.
Thank you
