### ISSUE TITLE
in_app_purchase: PurchaseStatus is null

### ISSUE THREAD

**Issue by vince-nyanga** [flutter/flutter#38671]
I have implemented in-app purchases for my app and have added a non-consumable product in the Play Console. When I test the purchase it goes through successfully. When I call `queryPastPurchases()` the purchase I made is returned but the `status` is null instead of `pending`, `purchased` or `error`. I'm using version  ^0.2.0+6 of the library.

**Comment by nanox77** [comment]
I'm running in real device and I have same issue using version  **^0.2.1**.

**Comment by BondarenkoStas** [comment]
@vince-nyanga Please provide a minimum reproducible example, also your ```flutter doctor -v``` output.

**Comment by vince-nyanga** [comment]
Here's `flutter doctor -v` output
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-GB)
    • Flutter version 1.7.8+hotfix.4 at /Users/vince/dev/flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/vince/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6459

[!] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.

```

### Steps to reproduce:
- Purchase non-consumable product
- Query past purchases 
- Handle past purchase response:
```dart
void _handlePastPurchases(List<PurchaseDetails> pastPurchases) {
    pastPurchases.forEach((purchase) {
      print('Purchase status: ${purchase.status}'); // This prints null
    });
  }
```

**Comment by kasbst** [comment]
I have the same issue when testing in-app purchases for my application using the non-consumable product. Everything runs fine, however PurchaseStatus is null. Therefore I cannot successfully verify if the item was purchased. 

Is this affecting only test purchases or also the real ones? 

Is there any update regarding this issue? I'm using the latest version in_app_purchase 0.2.2+2

Thanks!

**Comment by alekxlight** [comment]
> I have the same issue when testing in-app purchases for my application using the non-consumable product. Everything runs fine, however PurchaseStatus is null. Therefore I cannot successfully verify if the item was purchased.
> 
> Is this affecting only test purchases or also the real ones?
> 
> Is there any update regarding this issue? I'm using the latest version in_app_purchase 0.2.2+2
> 
> Thanks!

I discovered a work around that you need only in Android (iOS works fine).
There is some json data called verificationData.  I parse that and look at the purchaseState.  This gives valid information about purchases.  Here is my code.

 var purchaseData = jsonDecode(purchase.verificationData.localVerificationData);
  return (purchaseData.containsKey("purchaseState") && (purchaseData["purchaseState"] == 0))
      ? true //purchased
      : false;

Note: Make sure you do not call this for iOS.  The jsonDecode will fail, which happened to me.
I hope this helps.

**Comment by kasbst** [comment]
> I discovered a work around that you need only in Android (iOS works fine).
> There is some json data called verificationData. I parse that and look at the purchaseState. This gives valid information about purchases. Here is my code.
> 
> ```
>  var purchaseData = jsonDecode(purchase.verificationData.localVerificationData);
>   return (purchaseData.containsKey("purchaseState") && (purchaseData["purchaseState"] == 0))
>       ? true //purchased
>       : false;
> ```
> 
> Note: Make sure you do not call this for iOS. The jsonDecode will fail, which happened to me.
> I hope this helps.

Works flawlessly. Thank you very much for help!

**Comment by olga0** [comment]
The same issue with purchase id for test purchase. It is null.

**Comment by BeMacized** [comment]
Just checking in to ask if this is still an issue? I've tried reproducing this on 0.5.1 using the example app, but to no avail. 
When calling `queryPastPurchases()`, it returns the purchase of the non-consumable with the `PurchaseStatus.purchased` as it should. 

This issue is already quite old, so I can imagine this has already been fixed in the meantime.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
