### ISSUE TITLE
How to manually install packages

### ISSUE THREAD

**Issue by hasen6** [flutter/flutter#38681]
Can someone please tell me a way to manually install a package. `flutter pub get` is just stuck forever and who knows what it's doing since there is no progress indication whatsoever.

I've tried downloading the package from github and manually copying them into `Developer/flutter/.pub-cache/hosted/pub.dartlang.org/` and then running `flutter pub get` again which worked before but will not work with this current package. I even tried adding an entry into pubspec.lock but it still won't go. The package is right there but it won't use it.

I've spent the whole day trying to get this simple package installed which is only 6 MB, I just want to continue with my project. I feel like I'm remote controlling a robot to give me the drink that is on the table right in front of me.

Please can someone help so I can continue programming. Thanks.

**Comment by kf6gpe** [comment]
This sounds like a local network issue for you; we don't directly support hand-copying packages. You might want to try one of the forums at https://flutter.dev/support to see if anyone else has a woraround for this. I'm closing this issue as it appears not to be an issue with Flutter itself.
