### ISSUE TITLE
Face detect not work with medium resolution preset

### ISSUE THREAD

**Issue by hoangquy4897** [flutter/flutter#38683]
I'm making a face detect app on Android and it only detects faces with any resolution but medium. I don't know why because it wont work with all resolution if the problem came from my code. Anyone have the same problem? 

By the way, when i change the orientation of device to landscape, the camera preview turn to opposite (180).
Sorry for my bad English.

**Comment by BondarenkoStas** [comment]
@hoangquy4897 Please provide an example of code to reproduce the issue. Also your ```flutter doctor -v``` output.
Also I would advise you to post the issue to StackOverflow (there you may find help faster), as it may relate to the implementation, not to flutter itself.

**Comment by greenlihui** [comment]
I have same issue, see https://github.com/FirebaseExtended/flutterfire/issues/1518
