### ISSUE TITLE
If  set io.flutter.embedded_views_preview=YES in info.plist , app become very slow on ios

### ISSUE THREAD

**Issue by wxtiankong** [flutter/flutter#38689]
If  set io.flutter.embedded_views_preview=YES in info.plist , app become very slow on ios . if dont set it is very  good. but map plugin need set.

**Comment by VladyslavBondarenko** [comment]
Hi @wxtiankong 
Are you still experiencing the issue?

**Comment by TahaTesser** [comment]
Hi @wxtiankong 
if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
