### ISSUE TITLE
Document that key parameter should be passed to super for Widgets

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#3869]
I have not been doing this but I could see it being unsafe in the future. Thoughts?

example:

```
class PointlessChildWrapper extends StatelessWidget {
  final Widget child;

  PointlessChildWrapper({this.child});

  @override
  Widget build(BuildContext context) => child;
}
```

**Comment by eseidelGoogle** [comment]
CC @Hixie

**Comment by abarth** [comment]
Dart inserts calls to `super` in constructors for you, so it's not strictly necessary for correctness.  However, you'll notice that all of the widgets in the framework take a `Key key` parameter (which the pass along to their superclass in their constructors).  If your widget is intended to be general purpose, I'd recommend adding a Key parameter as a best practice in case future clients wants to give it a key.

**Comment by Hixie** [comment]
Where would be a good place to document this?

**Comment by Hixie** [comment]
Seems like StatelessWidget's API docs are the best place for this.

**Comment by amirfeqhi** [comment]
> Dart inserts calls to `super` in constructors for you, so it's not strictly necessary for correctness. However, you'll notice that all of the widgets in the framework take a `Key key` parameter (which the pass along to their superclass in their constructors). If your widget is intended to be general purpose, I'd recommend adding a Key parameter as a best practice in case future clients wants to give it a key.

Thanks for your explanation. but why is this necessary to invoke super class constructor in the child constructor at all?

**Comment by Hixie** [comment]
To pass the key to the superclass, where it is stored in the `key` property.

**Comment by amirfeqhi** [comment]
@Hixie Thanks.

**Comment by goderbauer** [comment]
This is "documented" via a lint rule now: https://dart.dev/tools/linter-rules/use_key_in_widget_constructors
