### ISSUE TITLE
Flutter plugins assume that there will be an Activity available at registration

### ISSUE THREAD

**Issue by BugsBunnyBR** [flutter/flutter#38692]
If [android_alarm_manager](https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager) is being used, it will try to register all plugins at `Application.onCreate`, right?

If so, [cloud_firestore](https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java#L80), [firebase_database](https://github.com/flutter/plugins/blob/master/packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java#L55) and [in_app_purchase](https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/android/src/main/java/io/flutter/plugins/inapppurchase/InAppPurchasePlugin.java#L73) will get a null reference to the activity, right?

**Comment by mklim** [comment]
Thanks for pointing this out. /cc @bkonyi and @collinjackson. I'm not super familiar with this code but at a first read it looks like we'd have this problem IFF android_alarm_manager spun off its background service and started the plugins from a callback there. Does that sound correct to either of you?

Long term I'm also not sure what this would look like with the new plugins embedding @matthew-carroll is working on. I'm pretty sure that doesn't have an activity accessor at all right now, so this logic would have to look extremely different.

**Comment by matthew-carroll** [comment]
The new embedding does provide access to an `Activity`, but *when* that happens depends entirely on the implementation details. `Activity`s will come and go and every plugin must be ready to handle that.

**Comment by matthew-carroll** [comment]
PS - Wherever it is relevant, we should never bake in an expectation that plugin registration occurs in Application#onCreate(). In fact, it almost always happens in an `Activity`, but we also can't assume it's the first `Activity`. It's important from this point forward that plugins make themselves resilient to these platform constructs coming and going at undefined times.

**Comment by collinjackson** [comment]
The only thing we're using the activity for in Flutterfire is transactions (which use `AsyncTask` and `runOnUiThread`). There's probably a better way of getting the result of the transaction back to the thread where `result` can be invoked.

**Comment by matthew-carroll** [comment]
`runOnUiThread()` can be replaced by `new Handler(Looper.getMainLooper()).post(new Runnable() {...});`

`AsyncTask` only really exists for the purposes of running within an `Activity`, so I'm not sure what migrating that part would mean. It depends on the implementation, I suppose.

**Comment by kroikie** [comment]
@BugsBunnyBR

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/346. Any further collaboration will be done there.

**Comment by BugsBunnyBR** [comment]
@kroikie yes, this is still an issue here
https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java#L80
