### ISSUE TITLE
Unhandled Exception: type 'int' is not a subtype of type 'bool'

### ISSUE THREAD

**Issue by crushman1** [flutter/flutter#38696]
This issue seems straight-forward but its not. My application works on most iphones and ALL android devices. But some iphones and ipads crash everytime they encounter this :
`Firestore.instance.collection('collection').document('documentname').get()`

It works if i use `snapshots()`. What is happening here? my app is already live and NOW i see this bug...

**Comment by tvolkert** [comment]
@collinjackson

**Comment by crushman1** [comment]
any updates or work-arounds? like maybe an alternative to the `get()` besides `snapshots()` ? @tvolkert @collinjackson 
i'm starting to get desperate here... :(

**Comment by tvolkert** [comment]
@crushman1 can you include a simple reproducible code snippet, as well as a stack trace, your `pubspec.yaml`, and the output of `flutter doctor -v`?

**Comment by crushman1** [comment]
Code snippet:
Open a fresh project in android studio and just use `Firestore.instance.collection('collection').document('documentname').get()` Pretty much anywhere in the code. Its gonna work for androids and most iphones.

pubspec.yaml:
`dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  font_awesome_flutter: ^8.2.0
  fluttertoast: ^3.0.4
  datetime_picker_formfield: ^0.2.0
  date_range_picker: ^1.0.6
  flutter_image_compress: ^0.4.0
  cloud_firestore: ^0.12.9
  firebase_auth: ^0.11.1
  google_sign_in: ^4.0.1+3
  firebase_messaging: ^5.0.2
  shared_preferences: ^0.5.2
  firebase_storage: ^3.0.0
  flutter_rating: ^0.0.2
  flutter_typeahead: ^1.4.0
  url_launcher: ^4.0.3
  flutter_facebook_login: ^2.0.0
  algolia: ^0.1.5
  geolocator: ^4.0.3
  provider: ^2.0.1
  share: ^0.6.1+1
  add_2_calendar: ^1.3.0
  image_picker: ^0.6.0+8
  shake_event: ^0.0.4
  audioplayers: ^0.12.0
  transparent_image: ^1.0.0
  grouped_buttons: ^1.0.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.19
  flutter_staggered_grid_view: ^0.3.0
  stripe_payment: ^0.1.0`

`(c) 2018 Microsoft Corporation. All rights reserved.

C:\apps\w2e>flutter doctor -v
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17134.885], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at C:\fluttersdk\flutter
    • Framework revision b712a172f9 (6 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\rg\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\rg\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
`

Unfortunately, I cant get the logcat data as it works on all my iphones and ipad. But i think the error will come up on iphone 6 v10.33

**Comment by tvolkert** [comment]
Thanks! Are you seeing these errors when testing on certain iOS devices, and do you have access to those devices so you can access the error logs?  If not, how are you being alerted to these failures?

**Comment by crushman1** [comment]
Currently, i don't have "full" access to any device with this error. It was a friend of a friend of mine who reported that the app was not getting passed the first screen. To date, 4 users have experienced this and the number increases every week. They usually let me know through whatsapp or email.
this is the live app here : 
https://play.google.com/store/apps/details?id=com.regiondesigns.w2e

Since everyone is very uncomfortable with plugging their device into a stranger's laptop it was very difficult for me to get it, but eventually he allowed it and when i plugged in i noticed it:
In the `InitState`, the app gets all the countries using `get()` and puts it into a dropdownlist. The code crashes just on that statement. if i by-pass it using snapshots() it works but the problem is i use `get()` EVERYWHERE so the app eventually crashes either way.

**Comment by crushman1** [comment]
I will try to reconnect to that iphone and i will copy and paste the logcat response but its gonna take me a while...

**Comment by tvolkert** [comment]
The fact that you only see this on iOS means the problem is likely in [this code path](https://github.com/flutter/plugins/blob/61c39d1e79e8f36030162a5f85fb491c65f4e51c/packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m#L500):

```objc
  } else if ([@"DocumentReference#get" isEqualToString:call.method]) {
    FIRDocumentReference *document = getDocumentReference(call.arguments);
    FIRFirestoreSource source = getSource(call.arguments);
    [document
        getDocumentWithSource:source
                   completion:^(FIRDocumentSnapshot *_Nullable snapshot, NSError *_Nullable error) {
                     if (snapshot == nil) {
                       result(getFlutterError(error));
                     } else {
                       result(@{
                         @"path" : snapshot.reference.path,
                         @"data" : snapshot.exists ? snapshot.data : [NSNull null],
                         @"metadata" : @{
                           @"hasPendingWrites" : @(snapshot.metadata.hasPendingWrites),
                           @"isFromCache" : @(snapshot.metadata.isFromCache),
                         },
                       });
                     }
                   }];
```

@collinjackson you see anything amiss in there?

**Comment by crushman1** [comment]
Are you guys able to replicate the error on your end? Am i the only one how's experiencing this bug?

**Comment by collinjackson** [comment]
I don't see anything obvious that's amiss. There's an integration test of `get()` that's passing, so I think there must be something that is different about your setup.

https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/example/test_driver/cloud_firestore.dart#L146

If you could contribute a failing integration test I'd be look into it further.

Alternatively, try running the app in the Xcode debugger and catch the exception and post a stack trace here.

**Comment by mwillner** [comment]
hey @kika , @crushman1 could you fix this?
I am getting this error suddenly on an old iPad 3 running iOS 9.3.5, in debug builds as well as production builds.
Other, more recent Apple Devices seem to have no trouble...

**Comment by kika** [comment]
@mwillner I just consider iPhone5 unsupported as of now.

**Comment by ankits47b** [comment]
I got same issue on iPhone 5c and its work on iPhone 6S

**Comment by kroikie** [comment]
@crushman1

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1205. Any further collaboration will be done there.
