### ISSUE TITLE
Enabling/disabling elevated button causes it to flash black

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#387]
When you tap "ADD" the first time in the sector demo, the "REMOVE" button blinks black.

**Comment by Hixie** [comment]
This is also experiencing some of #399. Also, tapping "add" then "remove" then "remove" again causes the entire engine to crash.

**Comment by Hixie** [comment]
I can't reproduce the crash mentioned in the second comment. The issue in the first comment seems to be related to the animated container inside a MaterialButton. It slows down and becomes clear if you set a time dilation.

**Comment by Hixie** [comment]
Ok, here's the problem. Disabled raised buttons use `Colors.black12`, aka `const Color(0x1F000000)`. Enabled raised buttons use `Colors.grey[300]`, aka `const Color(0xFFE0E0E0)`.

When you switch from one to the other, we animate between them, which, when composited against the material background behind, means it cycles through these colours:

![screenshot_20160112-221942](https://cloud.githubusercontent.com/assets/551196/12286666/1c601084-b97b-11e5-8de8-fff1d22a2949.png)

...and that's where the blackness comes from.

**Comment by Hixie** [comment]
There's also something really weird going on with the shadow transitions.

**Comment by Hixie** [comment]
I have an in-progress fix for this but it's blocked on making progress on https://github.com/flutter/flutter/issues/1701.

**Comment by Hixie** [comment]
What I'm going to do for the color transition is instead of transitioning the color of the print, I'll transition a circle clip of the material laid on top.

**Comment by Hixie** [comment]
Need to fix https://github.com/flutter/flutter/issues/3493 first though.

**Comment by eseidelGoogle** [comment]
Is this still an issue?

**Comment by abarth** [comment]
Yep.

**Comment by zoechi** [comment]
This is how it looks currently

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/405837/51376145-ea3b8100-1b07-11e9-90dc-a0b6b61c3f36.gif)

```dart
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';

void main() {
  timeDilation = 3.0;
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _buttonEnabled = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'foo text',
            ),
            RaisedButton(
                child: Text(_buttonEnabled ? 'Enabled' : 'Disabled'),
                onPressed: _buttonEnabled ? () {} : null),
            RaisedButton(
                child: Text('Toggle enabled'),
                onPressed: () =>
                    setState(() => _buttonEnabled = !_buttonEnabled)),
          ],
        ),
      ),
    );
  }
}
```
```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.1 18B75, locale en-AT)
```

**Comment by shuhuaxie** [comment]
When _MaterialInteriorState rebuild, _MaterialInterior's color change from Color(0x1f000000) to Color(0xffe0e0e0). 
But identical(oldColor, newColor) return true.

**Comment by shuhuaxie** [comment]
Add new Reproduce Code.
`class MyRenderPhysicalShapeDemo extends StatefulWidget {
  @override
  MyRenderPhysicalShapeState createState() {
    return MyRenderPhysicalShapeState();
  }
}

class MyRenderPhysicalShapeState extends State<MyRenderPhysicalShapeDemo> {
  double _insets = 0.0;
  double _opacity = 0.0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text('MyRenderPhysicalShapeDemo')),
        body: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Slider(
                value: _insets,
                onChanged: (value) => setState(() => _insets = value),
              ),
              MyPhysicalShape(
                insets: _insets,
                child: Container(
                  width: 50,
                  height: 50,
                ),
              )
            ]));
  }
}

class MyPhysicalShape extends SingleChildRenderObjectWidget {
  final _insets;

  MyPhysicalShape({double insets, Widget child})
      : this._insets = insets,
        super(child: child);
  @override
  RenderPhysicalShape createRenderObject(BuildContext context) {
    return RenderPhysicalShape(
      clipBehavior: Clip.none,
      color: Color(0x61000000),
      clipper: ShapeBorderClipper(
        shape: CircleBorder(),
        textDirection: Directionality.of(context),
      ),
      shadowColor: Colors.black,
      elevation: _insets * 2,
    );
  }

  @override
  void updateRenderObject(BuildContext context, RenderPhysicalShape renderObject) {
    renderObject
      ..elevation = _insets * 2;
  }
}`

**Comment by Hixie** [comment]
The solution is to split the animation into two phases, one where we turn the transparent elevation=0 raised button into an opaque elevation=0 raised button, and a second phase where we adjust the elevation.

**Comment by dnfield** [comment]
I think fixing https://github.com/flutter/flutter/issues/48534 would fix this, right?

i.e. if Color.lerp handled lerping through transparent colors more gracefully we wouldn't see the darker grays.

**Comment by dnfield** [comment]
Just verified it would not - there's a different issue going on here.

**Comment by pedromassangocode** [comment]
I was able to reproduce this on latest `master` channel.

![brun](https://user-images.githubusercontent.com/67424416/91289003-9a17ac80-e789-11ea-91f9-a1d2f602f263.gif)

<details>
<summary> sample code</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';

void main() {
  timeDilation = 3.0;
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _buttonEnabled = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'foo text',
            ),
            RaisedButton(
                child: Text(_buttonEnabled ? 'Enabled' : 'Disabled'),
                onPressed: _buttonEnabled ? () {} : null),
            RaisedButton(
                child: Text('Toggle enabled'),
                onPressed: () =>
                    setState(() => _buttonEnabled = !_buttonEnabled)),
          ],
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.77, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.22.0-2.0.pre.77 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision c8f3df7ea5 (8 hours ago), 2020-08-25 21:26:05 -0400
    • Engine revision b1d9f863db
    • Dart version 2.10.0 (build 2.10.0-56.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.6397.47

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API
      30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • Mac OS X
      10.15.6 19G2021
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools
    • Chrome (web)            • chrome        • web-javascript • Google Chrome
      84.0.4147.135

! Doctor found issues in 3 categories.
```
</details>

**Comment by pedromassangocode** [comment]
@Hixie since the widget in question (`RaisedButton`) was deprecated in https://github.com/flutter/flutter/pull/59702 by @HansMuller I'm wondering if this issue is worth a fix and if it should remain opened.

**Comment by Hixie** [comment]
Does the problem exist with ElevatedButton?

**Comment by HansMuller** [comment]
The problem does still occur with ElevatedButton. I will look into it.

**Comment by HansMuller** [comment]
The source of the problem is that Material with non-zero elevation is filled with the (default gray) shadowColor. In the screenshot below the top rectangle is defined with
```dart
Material(elevation: 0.0001, color: Colors.blue.withOpacity(0.12))
```
The bottom rectangle is:
```dart
Material(elevation: 0, color: Colors.blue.withOpacity(0.12))
```
The fill color for a disabled button has opacity 0.12. When the button's fill color animates from its opaque enabled color to the translucent disabled fill color, the elevation shadow continues to show through until the elevation finally reaches 0. To avoid this, we'll need to do the transition in two steps: first the elevation, then the color.

![elevation](https://user-images.githubusercontent.com/1377460/91617343-ae4fdb00-e93c-11ea-9330-0b29ef1a2044.png)

**Comment by HansMuller** [comment]
Just FTR, the original OutlineButton widget dealt with this problem, see https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/outline_button.dart#L396
