### ISSUE TITLE
Google APIs support for Flutter?

### ISSUE THREAD

**Issue by kevin-haynie** [flutter/flutter#38707]
When is Google going to release direct support for all the Google APIs for Flutter?  Pretty much every other language is supported by its own SDK except for Dart/Flutter.  What's the deal?!  It seems that Google would want to make their own APIs first class citizens in Flutter.

**Comment by download8866** [comment]
You can go to pub.dev search google api keywords.

**Comment by kevin-haynie** [comment]
Pub.dev has a lot of great packages we can use for Flutter but some of them
don't work very well.  My point is that Google as a company needs to add
direct support for Flutter and their APIs.

For example, if you want to integrate Google Drive into your Flutter app,
you basically just have to go to the REST API to do it since there are no
published SDKs for Flutter.  See
https://developers.google.com/drive/api/v3/manage-uploads as an example of
the variety of languages that Google provides.: Java, Node, Python, etc.
Nothing for Flutter.  Nothing at all.  This makes me wonder whether Google
is really committed to Flutter at all....

Kevin

**Comment by xvrh** [comment]
A lot of Google Apis are available in this package: https://pub.dev/packages/googleapis 
For instance to upload to the drive api:

```dart
import 'package:googleapis/drive/v3.dart';
import 'package:googleapis_auth/auth_io.dart';
import 'dart:io' as io;

main() async {
  AuthClient client = await clientViaServiceAccount(
      ServiceAccountCredentials.fromJson({/* here the credentials */}),
      ['https://www.googleapis.com/auth/drive']);

  var driveApi = DriveApi(client);

  var fileToUpload = io.File('my_file.png');

  await driveApi.files.create(File()..name = 'my_file.png',
      uploadMedia: Media(fileToUpload.openRead(), fileToUpload.lengthSync()));
}
```

**Comment by kevin-haynie** [comment]
Yes, I've looked at that before but documentation on how to use it was
*severely* lacking.  Your example above is excellent, but where did you
find the docs on the use of DriveAPI?  Other API docs?

I know I can look at the official documentation for each of the APIs but
that doesn't really help me understand how to use the Dart API.

The other problem I've had with googleapis package is that it was huge and
bloated my app.  Is there a way to only take and use parts of it?

Thanks
Kevin

**Comment by xvrh** [comment]
To understand how to use a particular API, I often use a mix of several sources: 
- Look at the API reference. ie: https://pub.dev/documentation/googleapis/latest/googleapis.drive.v2/FilesResourceApi-class.html
- Look the Dart source code: https://github.com/dart-lang/googleapis/tree/master/generated/googleapis/lib
- Look at other's languages examples to see the possibilities of the API.

> The other problem I've had with googleapis package is that it was huge and
bloated my app.  Is there a way to only take and use parts of it?

Dart has a "tree-shaking" phase during compilation (https://en.wikipedia.org/wiki/Tree_shaking). The unused part are automatically removed and your release build will only contains the API's that you really use.
The googleapis package seems to have clean separation between each api, so I don't see a reason why the tree-shaker would not work.
May be you could try the size-analysis tools listed here: https://flutter.dev/docs/resources/faq#how-big-is-the-flutter-engine ?

**Comment by kevin-haynie** [comment]
Thanks very much, Xavier.  I wasn't aware of the API reference you mention
above.  And I was familiar with the tree shaking algorithms used since I'm
still fairly new to Flutter and have been compiling in debug mode all the
time.

That being said, it would be very helpful to have some more sample code
demonstrating the use of the various google APIs (like the one you provided
for Drive).  I wish Google could just provide that to us devs.  It seems in
their best interest to do so.

Kevin

**Comment by kf6gpe** [comment]
Unfortunately, this isn't really an actionable discussion for us --- we're always looking to extend Flutter's reach --- and welcome contributions from the community, since Flutter's open source! There's a bunch of great work so far in flutter/plugins, and the packages at pub.dev as others have observed. I'm going to close this issue with this in mind. Thanks for your interest in Flutter!
