### ISSUE TITLE
[android_intent] Intents should take `ACTIVITY_` flags 

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#38701]
## Use case

Android exposes the ability to customize how activities are launched, would be helpful if the plugin also allowed this.

Some examples:

- `FLAG_ACTIVITY_NO_HISTORY`
- `FLAG_ACTIVITY_NEW_TASK` (and the related `FLAG_ACTIVITY_CLEAR_` flags)
- `FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS`
- `FLAG_GRANT_READ_URI_PERMISSION`

## Proposal

It probably makes sense to do this by defining a `flags` member on `AndroidIntent`, and then some enum constants for common flags. `FLAG_ACTIVITY_NEW_TASK` is .a common one.

**Comment by stuartmorgan** [comment]
Closing as `android_intent` is deprecated in favor of [`android_intent_plus`](https://pub.dev/packages/android_intent_plus).
