### ISSUE TITLE
Adjust GridView child width

### ISSUE THREAD

**Issue by mohamed6996** [flutter/flutter#38717]
Im trying to implement Gridview with two columns and pagination. when the user scroll to last element in the list, a progress indicator is shown till fetching the new elements and so on. The problem is that the progress indicator appears inside the first column and take the same height, width as of the images. I want to display it at the bottom of the screen in the center and the height should be small.

```
Widget _buildGridView(
      List<PhotoModel> models, ScrollController scrollController) {
    return Container(
        child: GridView.builder(
            controller: scrollController,
            itemCount: models.length + 1,
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 2,
              childAspectRatio: .55,
            ),
            itemBuilder: (context, index) {
              if (index == models.length) {
                return SpinKitThreeBounce(
                  color: Colors.purple,
                  size: 30.0,
                );
              } else {
                return GestureDetector(
                  onTap: () {
                    onImagePressed(models[index]);
                  },
                  child: GridItemView(
                    models[index],
                    () => onFavoritePressed(index),
                  ),
                );
              }
            }));
  }
```

[![enter image description here][1]][1]

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/L6rCI.jpg
  [2]: https://i.stack.imgur.com/6BBwX.jpg

**Comment by BondarenkoStas** [comment]
@mohamed6996  This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but related to implementation.

**Comment by mohamed6996** [comment]
@BondarenkoStas  I asked on StackOverflow before here but no answer. so, i found an alternative to achieve this. I used  [flutter_staggered_grid_view ] (https://pub.dev/packages/flutter_staggered_grid_view).

**Comment by VladyslavBondarenko** [comment]
Closing since solved
