### ISSUE TITLE
Flutter fails to install on Windows 10

### ISSUE THREAD

**Issue by alanwhite** [flutter/flutter#38720]
## Steps to Reproduce

Follow the instructions at https://flutter.dev/docs/get-started/install/windows
got clone works
flutter doctor fails

## Logs

C:\Users\whitea5\devtools>git clone -b stable https://github.com/flutter/flutter.git
Cloning into 'flutter'...
remote: Enumerating objects: 78, done.
remote: Counting objects: 100% (78/78), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 183567 (delta 41), reused 22 (delta 16), pack-reused 183489
Receiving objects: 100% (183567/183567), 68.30 MiB | 3.35 MiB/s, done.
Resolving deltas: 100% (140505/140505), done.
Checking out files: 100% (3513/3513), done.

C:\Users\whitea5\devtools>flutter doctor
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine fee001c93f25a1e7258e762781a7361f122d29f5...
Unzipping Dart SDK...
Remove-Item : Cannot find path 'C:\Users\whitea5\devtools\flutter\bin\cache\dart-sdk\bin\dart.exe' because it does not
exist.
At
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:410
char:46
+ ...                 $expandedItems | % { Remove-Item $_ -Force -Recurse }
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\whitea...dk\bin\dart.exe:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Remove-Item : Cannot find path 'C:\Users\whitea5\devtools\flutter\bin\cache\dart-sdk\bin\dart.lib' because it does not
exist.
At
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:410
char:46
+ ...                 $expandedItems | % { Remove-Item $_ -Force -Recurse }
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\whitea...dk\bin\dart.lib:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Remove-Item : Cannot find path 'C:\Users\whitea5\devtools\flutter\bin\cache\dart-sdk\bin\dart2js.bat' because it does
not exist.
At
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:410
char:46
+ ...                 $expandedItems | % { Remove-Item $_ -Force -Recurse }
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\whitea...bin\dart2js.bat:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Remove-Item : Cannot find path 'C:\Users\whitea5\devtools\flutter\bin\cache\dart-sdk\bin\dartanalyzer.bat' because it
does not exist.
At
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:410
char:46
+ ...                 $expandedItems | % { Remove-Item $_ -Force -Recurse }
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\whitea...artanalyzer.bat:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Remove-Item : Cannot find path 'C:\Users\whitea5\devtools\flutter\bin\cache\dart-sdk\bin\dartdevc.bat' because it does
not exist.
At
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:410
char:46
+ ...                 $expandedItems | % { Remove-Item $_ -Force -Recurse }
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\whitea...in\dartdevc.bat:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Exception calling "ExtractToFile" with "3" argument(s): "The process cannot access the file
'C:\Users\whitea5\devtools\flutter\bin\cache\dart-sdk\bin\dartdoc.bat' because it is being used by another process."
At
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:1033
char:25
+ ...             [System.IO.Compression.ZipFileExtensions]::ExtractToFile( ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IOException

Building flutter tool...
Running pub upgrade...
The system cannot find the path specified.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
The system cannot find the path specified.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
The system cannot find the path specified.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left)

Waiting for 2 seconds, press CTRL+C to quit ...
Terminate batch job (Y/N)? Y

**Comment by download8866** [comment]
pls,put your OS system details.

**Comment by alanwhite** [comment]
Windows 10, Version 1703, (OS Build 15063.1155)

**Comment by alanwhite** [comment]
Anything I need to do to make this work on Windows plse, any more info required?

**Comment by alanwhite** [comment]
For anyone else struggling, the downloaded dart ask failed to unzip, despite correct version on powershell and confirming expand module working. This was fixed by installing 7-Zip and adding to the path, deleting the flutter/bin/cache directory and running flutter doctor again. 

Aka the install instructions need fixing, I’m not alone in needing to install 7-Zip to make flutter install.
