### ISSUE TITLE
An option to provide space (margin) between pages in PageView

### ISSUE THREAD

**Issue by amankataria** [flutter/flutter#38739]
In many cases, we have things using the full width of pages in PageView.

For example:
![](https://i.stack.imgur.com/x3hBWm.png)

I think an option to provide some space(margin) between `PageVIew `could be handy.

**Example:**
Consider pages with 2 colors:
```
PageView.builder(
          itemCount: _pagesList.length,
          itemBuilder: (BuildContext context, int index) {
            return Container( 
                    color: _pagesList[index],
                           );
                        }
                     )
```
<img width="300" alt="portfolio_view" src="https://i.stack.imgur.com/T5hDs.gif">

Here we have no space between 2 pages, it may seem congested in many cases.

A simple parameter of `margin `could be very useful:
```
PageView.builder(
          margin: 35,
          itemCount: _pagesList.length,
          itemBuilder: (BuildContext context, int index) {
            return Container( 
                    color: _pagesList[index],
                          );
                        }
                      )
```
![](https://i.stack.imgur.com/ny1mF.png)
 
Now it looks much better. This would be useful in many cases.

**Comment by SwissCheese5** [comment]
Does adding Padding(padding: EdgeInsets.symmetric(horizontal: 20, child: <widget here>)) work?

**Comment by amankataria** [comment]
> I believe adding Padding(padding: EdgeInsets.symmetric(horizontal: 20, child: )) does the job

I hope you understand that this margin/space will be visible between pages when we scroll through pages. 

Padding would be visible within each page's boundaries. The margin/space property I have requested is outside the page. Hope I am clear now.

**Comment by SwissCheese5** [comment]
Ah, I understand, my bad

**Comment by Solido** [comment]
Have you try `viewportFraction` 

`PageController({int initialPage: 0, bool keepPage: true, double viewportFraction: 1.0 })`

**Comment by BondarenkoStas** [comment]
@amankataria Please report if @Solido comment solved your issue.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by mono0926** [comment]
This should work fine ✨✨

```dart
final pageController = PageController(viewportFraction: 1.1);

PageView.builder(
  controller: pageController,
  itemCount: _pagesList.length,
  itemBuilder: (BuildContext context, int index) {
    return FractionallySizedBox(
      widthFactor: 1 / pageController.viewportFraction,
      child: Container(
        color: _pagesList[index],
      ),
    );
  },
);
```

**Comment by isaiascardenas** [comment]
Thanks @mono0926 , this work for me!

**Comment by tewshi** [comment]
```final pageController = PageController(viewportFraction: 1.1);```
this line gave me a sweet night sleep

**Comment by jlavyan** [comment]
Seems initialPage not working correct for above solution

**Comment by Ibtesam-Mahmood** [comment]
@jlavyan Can you please explain where you added this, I'm still facing the same issue. Thanks.

**Comment by cachapa** [comment]
@iapicca I would like to request that this issue be reopened.

The proposed solution using `viewportFraction` doesn't allow fine control of the margin between pages (it will be relative to the width of the parent widget) and seems to break the `initialPage` parameter.

Ideally we would have a simple `double pageMargin` parameter that allows specifying the exact spacing between pages.

**Comment by iapicca** [comment]
@cachapa 
this issue was closed more than a year ago,
please open a new issue provide your `flutter doctor -v` and a complete runnable [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by cachapa** [comment]
Opened #78200
