### ISSUE TITLE
Get children count on Firebase database without downloading all the children

### ISSUE THREAD

**Issue by sarat12us** [flutter/flutter#38732]
## Use case
Will be able to get children count on Firebase database without downloading all the children

## Proposal
I don't know , probably need to add a children count variable in Firebase Database and increment it as in when a new child is added

**Comment by kroikie** [comment]
@sarat12us

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1069. Any further collaboration will be done there.
