### ISSUE TITLE
Platform View on iPhone shows black screen

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#38735]
Reproduction: run the webview_example on an physical iphone.

Result: Black screen

This is currently happening on master (c02e38e35f3d209f8d2558fbdf763a409a8ff318).  Will try to find out when it last worked...

**Comment by dnfield** [comment]
Bisected to c92a0d992aeab439c13a494448575f8124120d6a, which is a large engine roll :\  Updated bad builds.

**Comment by dnfield** [comment]
Culprit is https://github.com/flutter/engine/pull/10949 (and likely the one before it)

**Comment by iskakaushik** [comment]
https://github.com/flutter/engine/pull/11075 should fix the bug. Leaving this open till this rolls to framework.

**Comment by tvolkert** [comment]
This rolled into the framework in https://github.com/flutter/flutter/pull/38756.  Thanks @iskakaushik
