### ISSUE TITLE
Please add The Native Add Feature in firebase admob package

### ISSUE THREAD

**Issue by Loopex2019** [flutter/flutter#38738]
## Proposal

It's been a long time so can you guys please add the support for native ads in firebase admob 
package?

**Comment by nemoryoliver** [comment]
I have been patiently waiting as well..

**Comment by Loopex2019** [comment]
I am trying to think about
what's difficulty to add this Feature ?

**Comment by nemoryoliver** [comment]
The admob_flutter was able to implement the native banner ads so I wonder why this can't be done yet on the official package

**Comment by kroikie** [comment]
@Loopex2019

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1170. Any further collaboration will be done there.
