### ISSUE TITLE
firebase_dynamic_link 0.5.0 is not correctly working in ios device when application is in running/background state.

### ISSUE THREAD

**Issue by dhanrajvermaRepo** [flutter/flutter#38744]
In android application firebase dynamic link 0.5.0 is working fine. But in ios device dynamic link is not working when app is in running/background state. But in killed state it works fine means when link is clicked in killed state it open correct location in the application.
I have no idea why it is happening.
should I use one of the old versions?

**Comment by AndroidNils** [comment]
For me is everything working fine, when the ios app is in background/running. If the app is closed, the dynamic link doesn't work. It opens the app, but then is nothing happing. In Android is everything fine.

**Comment by dhanrajvermaRepo** [comment]
> For me is everything working fine, when the ios app is in background/running. If the app is closed, the dynamic link doesn't work. It opens the app, but then is nothing happing. In Android is everything fine.

Which version of firebase dynamic links plugin are you using?

**Comment by dhanrajvermaRepo** [comment]
> For me is everything working fine, when the ios app is in background/running. If the app is closed, the dynamic link doesn't work. It opens the app, but then is nothing happing. In Android is everything fine.

Which version of firebase dynamic links are you using?

**Comment by AndroidNils** [comment]
> > For me is everything working fine, when the ios app is in background/running. If the app is closed, the dynamic link doesn't work. It opens the app, but then is nothing happing. In Android is everything fine.
> 
> Which version of firebase dynamic links are you using?

I use also version 0.5.0

**Comment by dhanrajvermaRepo** [comment]
> > > For me is everything working fine, when the ios app is in background/running. If the app is closed, the dynamic link doesn't work. It opens the app, but then is nothing happing. In Android is everything fine.
> > 
> > 
> > Which version of firebase dynamic links are you using?
> 
> I use also version 0.5.0

Can you show me example in which dynamic link is working fine in running/back round state on ios device?

**Comment by nizo-m** [comment]
> For me is everything working fine, when the ios app is in background/running. If the app is closed, the dynamic link doesn't work. It opens the app, but then is nothing happing. In Android is everything fine.

I'm having the same problem in iOS.

using version 0.5.0 as well.

**Comment by BondarenkoStas** [comment]
@dhanrajvermaRepo Please provide your flutter doctor -v output, and maybe some code example to be sure to reproduce the issue correctly.

**Comment by dhanrajvermaRepo** [comment]
> @dhanrajvermaRepo Please provide your flutter doctor -v output, and maybe some code example to be sure to reproduce the issue correctly.

> Flutter doctor output

[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-IN)
    • Flutter version 1.7.8+hotfix.4 at /Users/root-flutter/Documents/development/flutter
    • Framework revision 20e59316b8 (8 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/root-flutter/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode10.3.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[!] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

> Example Code


`void main() => runApp(
    MaterialApp(
    theme: new ThemeData(
      primaryColor: Colours.appThemeColour,
    ),
    onGenerateRoute: (RouteSettings settings) {
      switch (settings.name) {

//This is my root widget

        case '/': return new MyCustomRoute(
          builder: (_) => new SplashScreen(),
          settings: settings,
        );
...
   }
      assert(false);
    }
)
);

class SplashScreen extends StatefulWidget {
  @override
  _SplashScreenState createState() => new _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen>
    with SingleTickerProviderStateMixin {
  final scaffoldKey = new GlobalKey<ScaffoldState>();
  _handleDeepLink(Uri deepLink) async {
    if (deepLink != null && deepLink.queryParameters["token"] != null) {
      print("querParam=${deepLink.queryParameters["token"]}");
      Navigator.of(context).pushNamed('/setpassword', arguments: [
        deepLink.queryParameters["token"].toString(),
        deepLink.queryParameters["otp"]
      ]);
} else {
//This function is used to check current version of app and compares to latest available version //and takes to appropriate screen.
      getVersion();
    }
  }
  initDynamicLinks() async {
    final PendingDynamicLinkData data =
        await FirebaseDynamicLinks.instance.getInitialLink();
    final Uri deepLink = data?.link;
    _handleDeepLink(deepLink);
    FirebaseDynamicLinks.instance.onLink(
        onSuccess: (PendingDynamicLinkData dynamicLink) async {
      final Uri deepLink = dynamicLink?.link;
      _handleDeepLink(deepLink);

    }, onError: (OnLinkErrorException e) async {
      print('onLinkError');
      print(e.message);
    });
  }


 @override
  void initState() {
    super.initState();
    initDynamicLinks();

  }
`
**On android this code is working fine but on ios dynamic link always takes me to app store**

**Comment by kroikie** [comment]
@dhanrajvermaRepo

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1124. Any further collaboration will be done there.
