### ISSUE TITLE
#05 pc 001374df /data/app/com.app.zhongcai-1/lib/arm/libflutter.so [armeabi-v7a]

### ISSUE THREAD

**Issue by qq3144225600** [flutter/flutter#38743]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

00 pc 00049d68 /system/lib/libc.so (tgkill+12) [armeabi-v7a::9b9f935454ad138c1261262c9518fccb]
--
2 #01 pc 000474e3 /system/lib/libc.so (pthread_kill+34) [armeabi-v7a::9b9f935454ad138c1261262c9518fccb]
3 #02 pc 0001d765 /system/lib/libc.so (raise+10) [armeabi-v7a::9b9f935454ad138c1261262c9518fccb]
4 #03 pc 000192a1 /system/lib/libc.so (__libc_android_abort+34) [armeabi-v7a::9b9f935454ad138c1261262c9518fccb]
5 #04 pc 00017308 /system/lib/libc.so (abort+4) [armeabi-v7a::9b9f935454ad138c1261262c9518fccb]
6 #05 pc 001374df /data/app/com.app.zhongcai-1/lib/arm/libflutter.so [armeabi-v7a::bb45fd19f169eb5441970181b0b00b84]
7 #06 pc 0012ccbb /data/app/com.app.zhongcai-1/lib/arm/libflutter.so [armeabi-v7a::bb45fd19f169eb5441970181b0b00b84]
8 #07 pc 0015ec51 /data/app/com.app.zhongcai-1/lib/arm/libflutter.so [armeabi-v7a::bb45fd19f169eb5441970181b0b00b84]
9 #08 pc 00137b09 /data/app/com.app.zhongcai-1/lib/arm/libflutter.so [armeabi-v7a::bb45fd19f169eb5441970181b0b00b84]
10 #09 pc 0013a401 /data/app/com.app.zhongcai-1/lib/arm/libflutter.so [armeabi-v7a::bb45fd19f169eb5441970181b0b00b84]
11 #10 pc 00011e6f /system/lib/libutils.so (_ZN7android6Looper9pollInnerEi+610) [armeabi-v7a::c4ccb4ea4f548e5d2ecf256d527f4a43]
12 #11 pc 00011b7f /system/lib/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+26) [armeabi-v7a::c4ccb4ea4f548e5d2ecf256d527f4a43]
13 #12 pc 000822a5 /system/lib/libandroid_runtime.so (_ZN7android18NativeMessageQueue8pollOnceEP7_JNIEnvP8_jobjecti+22) [armeabi-v7a::51691ae423baaf83a11f0e9d6dae8fae]
14 #13 pc 01c15d35 /system/framework/arm/boot-framework.oat (oatexec+6507829) [armeabi::d4e1a18fcf847259771ea5514d958124]
15 java:
16 android.os.MessageQueue.next(MessageQueue.java:323)
17 android.os.Looper.loop(Looper.java:138)
18 android.app.ActivityThread.main(ActivityThread.java:6120)
19 java.lang.reflect.Method.invoke(Native Method)
20 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
21 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```
```

**Comment by BondarenkoStas** [comment]
Unfortunately, this report does not have any actionable information - it’s not clear if this is a bug in user code, a bug in the framework, or something else entirely.
Please feel free to re-open if you can add the following information:
The version of Flutter you’re using
The output of flutter doctor -v
A minimal reproduction that leads to this exception.
