### ISSUE TITLE
Where is the FirebaseAuthUI implementation for Flutter?

### ISSUE THREAD

**Issue by ErstwhileIII** [flutter/flutter#38749]
Where is the Flutter implementation of FirebaseAuthUI?

FIrebase authentication is quite powerful and useful. Where is the "UI" support for flutter so each developer does not have to re-implement all the logic within this FIrebase UI module?

https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md

Note: Query first made in May 2017 (https://github.com/flutter/flutter/issues/17706 ).  I had hoped that a year would make a difference.

Who is handling the ecosystem associated with using all of the FIrebase features in Flut

**Comment by stuartmorgan** [comment]
Please don't deliberately file duplicate bugs; it will not change the priority of the original.
