### ISSUE TITLE
 Error: A value of type 'AuthResult' can't be assigned to a variable of type 'FirebaseUser'.

### ISSUE THREAD

**Issue by Mahesh73** [flutter/flutter#38757]
final FirebaseUser user = await _auth.signInWithCredential(credential);
this line i got error how to resolve it please help me

  Future<String> signInWithGoogle() async {
    final GoogleSignInAccount googleSignInAccount = await googleSignIn.signIn();
    final GoogleSignInAuthentication googleSignInAuthentication =
        await googleSignInAccount.authentication;
  
    final AuthCredential credential = GoogleAuthProvider.getCredential(
      accessToken: googleSignInAuthentication.accessToken,
      idToken: googleSignInAuthentication.idToken,
    );
  
    final FirebaseUser user = await _auth.signInWithCredential(credential);
  
    // Checking if email and name is null
    assert(user.email != null);
    assert(user.displayName != null);
    assert(user.photoUrl != null);
  
    name = user.displayName;
    email = user.email;
    imageUrl = user.photoUrl;
  
    // Only taking the first part of the name, i.e., First Name
    if (name.contains(" ")) {
      name = name.substring(0, name.indexOf(" "));
    }
  
    assert(!user.isAnonymous);
    assert(await user.getIdToken() != null);
  
    final FirebaseUser currentUser = await _auth.currentUser();
    assert(user.uid == currentUser.uid);
  
    return 'signInWithGoogle succeeded: $user';
  }

[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.950], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at C:\src\flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\sky\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\sky\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code (version 1.36.1)
    • VS Code at C:\Users\sky\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Redmi Note 4 • 230068319804 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.

**Comment by alexpavelm** [comment]
The signInWithCredential method returns AuthResult. If you want to retrieve the userid, add .user on the await call, like this:
final FirebaseUser user = (await _auth.signInWithCredential(credential)).user;

**Comment by Mahesh73** [comment]
It solve when i add .user

final FirebaseUser user = await _auth.signInWithCredential(credential).user

**Comment by roberto198907** [comment]
> The signInWithCredential method returns AuthResult. If you want to retrieve the userid, add .user on the await call, like this:
> final FirebaseUser user = (await _auth.signInWithCredential(credential)).user;

Thanks, it resolves my problem when I uploaded firebase_auth the latest.

**Comment by RanylFoumbi** [comment]
> The signInWithCredential method returns AuthResult. If you want to retrieve the userid, add .user on the await call, like this:
> final FirebaseUser user = (await _auth.signInWithCredential(credential)).user;

Thanks a lot big man.

**Comment by fred164** [comment]
thanks guys...error resolved

**Comment by cyprian-nziim** [comment]
Thanks Guys resolved the error

**Comment by fartunhussein** [comment]
` FirebaseUser firebaseUser= (await firebaseAuth.signInWithCredential(credential)).firebaseUser;`

**Comment by fartunhussein** [comment]
looks like my error isnt going away,,,,,help guys

**Comment by alexpavelm** [comment]
Please check the documentation of the package you are using, it might change it's methods and values and that's exactly what has happened here.

`firebaseUser -> user`

`FirebaseUser firebaseUser= (await firebaseAuth.signInWithCredential(credential)).user;`

**Comment by fartunhussein** [comment]
if(formState.validate()){
                                     FirebaseUser user= await firebaseAuth.currentUser();
                                  
                                      if (user == null){
                                        firebaseAuth.createUserWithEmailAndPassword(
                                          email: _emailTextController.text, password:_passwordTextController.text)
                                          .then((user) => {
                                            _userServices.createUser(
                                              user.uid,
                                              {
                                                "username":user.user.displayName,
                                                "email":user.user.email,
                                                "userId":user..user.uid,
                                               "gender" :gender,

                                                 
                                           
                                            }
                                            )
                                          });
                                      }
                               }



why do i have to use user.user.displayName  and not just user.DisplayName?

**Comment by neezystudio** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/51094739/81413412-0d9b9c80-914e-11ea-969f-f422ef2a6e5f.png)

ive tried everything and my error still is there..please help

**Comment by alexpavelm** [comment]
I've just checked again, the newest version of firebase_auth and it still works the same as I've explained above.

Are you sure flutter is set up correctly? As far as I can see, your IDE didn't highlight the code, so it's not seen as a flutter/dart project. Can you run the example app and confirm flutter is working?

**Comment by alexpavelm** [comment]
> if(formState.validate()){
> FirebaseUser user= await firebaseAuth.currentUser();
> 
> ```
>                                   if (user == null){
>                                     firebaseAuth.createUserWithEmailAndPassword(
>                                       email: _emailTextController.text, password:_passwordTextController.text)
>                                       .then((user) => {
>                                         _userServices.createUser(
>                                           user.uid,
>                                           {
>                                             "username":user.user.displayName,
>                                             "email":user.user.email,
>                                             "userId":user..user.uid,
>                                            "gender" :gender,
> 
>                                              
>                                        
>                                         }
>                                         )
>                                       });
>                                   }
>                            }
> ```
> 
> why do i have to use user.user.displayName and not just user.DisplayName?

The createUserWithEmailAndPassword method returns AuthResult, which you named as "user". It's working as intended, as the result contains FirebaseUser in its user field.

To "fix", try and rename it to "result", like so:
` .then((result) => `

**Comment by neezystudio** [comment]
thanks so much Alex it worked

**Comment by anmolseth06** [comment]
use UserCredential

UserCredential userCredential;
userCredential = (await _auth.createUserWithEmailAndPassword(
          email: email,
          password: password,
        ));
 await FirebaseFirestore.instance
            .collection('users')
            .doc(userCredential.user.uid)
            .set({
          'username': username,
          'email': email,
          'image_url': url,
        });

**Comment by rohankumara** [comment]
> The signInWithCredential method returns AuthResult. If you want to retrieve the userid, add .user on the await call, like this:
> final FirebaseUser user = (await _auth.signInWithCredential(credential)).user;

Thanks, Lot

**Comment by Faisalbutt555** [comment]
i am stck with error
I/flutter (11529): type 'User' is not a subtype of type 'FirebaseUser'

here is my code of rejister with google

Future signupWithGooglo() async {
    final GoogleSignInAccount googleSignInAccount = await googleSignIn.signIn();
    final GoogleSignInAuthentication googleSignInAuthentication =
        await googleSignInAccount.authentication;

    final AuthCredential credential = GoogleAuthProvider.getCredential(
      accessToken: googleSignInAuthentication.accessToken,
      idToken: googleSignInAuthentication.idToken,
    );

    // ignore: deprecated_member_use
    final FirebaseUser user =
        (await _firebaseAuth.signInWithCredential(credential)).user;

// Checking if email and name is null
    assert(user.email != null);
    assert(user.displayName != null);

    name = user.displayName;
    email = user.email;

// Only taking the first part of the name, i.e., First Name
    if (name.contains(" ")) {
      name = name.substring(0, name.indexOf(" "));
    }

    assert(!user.isAnonymous);
    assert(await user.getIdToken() != null);

    final FirebaseUser currentUser = await _firebaseAuth.currentUser;
    assert(user.uid == currentUser.uid);

    return Fluttertoast.showToast(
      msg: 'signInWithGoogle succeeded: $user',
      toastLength: Toast.LENGTH_SHORT,
      gravity: ToastGravity.CENTER,
    );
  }

**Comment by Faisalbutt555** [comment]
i am trying to set google name and email in firestore collection fetching from signup through google using upper and below code
 InkWell(
                                onTap: () async {
                                  setState(() {
                                    loader = true;
                                  });
                                  await signupWithGooglo().then((value) {
                                    FirebaseFirestore.instance
                                        .collection('Data')
                                        .doc()
                                        .set({'email': email, 'name': name});
                                  }).catchError((e) {
                                    print(e);
                                  }).then((value) {
                                    AppRoutes.push(context, MainBody());
                                  }).catchError((e) {
                                    Fluttertoast.showToast(
                                      msg: 'something is wrong',
                                      toastLength: Toast.LENGTH_SHORT,
                                      gravity: ToastGravity.CENTER,
                                    );
                                    AppRoutes.pop(context);
                                  });
                                  setState(() {
                                    loader = false;
                                  });
                                },
                                child: Text(
                                  'G',
                                  style: TextStyle(
                                      color: Colors.red,
                                      fontSize: 25,
                                      fontWeight: FontWeight.bold),
                                ),
                              ),
