### ISSUE TITLE
Native Actions overflow in some phones

### ISSUE THREAD

**Issue by melwinlobo18** [flutter/flutter#38759]
## Steps to reproduce
1. Press and hold the TextField

<p align="center">
<img src="https://raw.githubusercontent.com/melwinlobo18/HTML/master/overflow.png" alt="drawing" width="300" height="600"/>
</p>

**Comment by EmreSURK** [comment]
That should be normal behavior. 
You can face that situation in any Android app.

**Comment by goderbauer** [comment]
This should be foxed now thanks to @justinmc's work. Please open a new bug if there are still issues.
