### ISSUE TITLE
Is Flutter Simplex implementation patented ?

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#38760]
I'm very happy to see that Flutter has an implementation for Simplex but it's not clear how this relate to Kenneth Perlin patent : https://patents.google.com/patent/US6867776

To my understanding this limit the use of this implementation in 3D/ complex graphics  processing.

As an example, Simplex is often used in field/planet generation like Minecraft and we can't use it in Flutter as for now.

To respond to this problem the community came with **[OpenSimplex](https://en.wikipedia.org/wiki/OpenSimplex_noise)** that has others properties and is NOT under any patent.

You can find many public implementations

C#
https://gist.github.com/digitalshadow/134a3a02b67cecd72181/

Modified JS
https://gist.github.com/Spongman/d3786384fe4c6ee5b2770473b15bce19

Can you confirm the legal status we're in ? Thank you !

**Comment by stuartmorgan** [comment]
It's not clear to me what this issue is about. Can you provide a link to the specific code you are referring to?

**Comment by Solido** [comment]
In the context of Simplex you will find many implementation.
One is called Open Simplex and is a response to the Patent that comes with Simplex.

My question is on https://api.flutter.dev/flutter/vector_math/SimplexNoise-class.html

**Comment by creativecreatorormaybenot** [comment]
@stuartmorgan Here you can find the patent in question:

https://patents.google.com/patent/US6867776B2/en

You can find the relevant section under "Simplex Grid".  

If Flutter's `SimplexNoise` class uses the Simplex Grid algorithm patented by Kenneth Perlin, then yes that is not the best idea.

**Comment by creativecreatorormaybenot** [comment]
I implemented an `UNLICENSE`d algorithm "OpenSimplex2" here: https://pub.dev/packages/open_simplex_2

My whole repo has BSD-3, but the algorithm is licensed here: https://github.com/KdotJPG/OpenSimplex2/blob/master/UNLICENSE

**Comment by stuartmorgan** [comment]
> If Flutter's `SimplexNoise` class

Flutter doesn't have a `SimplexNoise` class. The link above is to a class in the `vector_math` library, which isn't Flutter code.

**Comment by creativecreatorormaybenot** [comment]
@stuartmorgan I see, I did not notice.

I checked the reference: https://github.com/google/vector_math.dart/blob/37c59407da0e21055a9cc7e99c0a52196969fa0f/lib/src/vector_math/third_party/noise.dart#L26  
This points to an implementation that is described here: https://weber.itn.liu.se/~stegu/simplexnoise/simplexnoise.pdf

And this definitely uses the patent: https://weber.itn.liu.se/~stegu/simplexnoise/simplexnoise.pdf

I think the whole simplex noise thing is somewhat controversial, but @stuartmorgan @Solido, should this issue be moved to https://github.com/google/vector_math.dart?

**Comment by creativecreatorormaybenot** [comment]
If you check the patent, it only convers "G06T11/001 Texturing; Colouring; Generation of texture or colour", so basically texture generation. I am not sure what simplex noise is used for in Flutter, but I assume this _could_ apply.

Either way, for me this is just a reason to not use it and part of why I created https://pub.dev/packages/open_simplex_2 in the first place.

**Comment by stuartmorgan** [comment]
> I am not sure what simplex noise is used for in Flutter

https://github.com/flutter/flutter/search?q=SimplexNoise&type=code

This code is not part of Flutter, and I see no evidence that it is used in Flutter. I'm not sure why it's being discussed here at all.
