### ISSUE TITLE
Read unfiltered prefs with shared_preferences

### ISSUE THREAD

**Issue by nuzelac** [flutter/flutter#38769]
## Use case

I'm rebuilding an existing app in Flutter. There is some data stored in shared preferences from the "old" app that I would like to read and use in the new app. E.g. session token for users that have been logged in, so they don't have to login again.

From what I gathered reading `shared_preferences` code, it works only with keys that use "flutter." prefix.

## Proposal

Is it possible to have a method in plugin that would return unfiltered data from shared prefs, or maybe make prefix configurable so it can be set to blank?

**Comment by BondarenkoStas** [comment]
@nuzelac  Looking at the referenced above PR, I think it's safe to close this issue. If you disagree, feel free create a new one, or to comment this one and I will reopen it.
