### ISSUE TITLE
Cloud Firestore orderBy doesn't return null values

### ISSUE THREAD

**Issue by Vluf** [flutter/flutter#38771]
The [docs](https://firebase.google.com/docs/firestore/manage-data/data-types#value_type_ordering) say that null values should come first in any ordering.
However, the following stream excludes any documents where the `createdAt` field is null:
`Firestore.instance.collection('someCollection').orderBy('createdAt', descending: true).snapshots()`

How do I get all the documents, orders, including null values (first)?

Thanks!

**Comment by kroikie** [comment]
@Vluf

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1204. Any further collaboration will be done there.
