### ISSUE TITLE
flutter should error out if pubspec.yaml flutter does not match

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3877]
Per https://github.com/flutter/flutter/issues/3865#issuecomment-218641417 if the flutter tool with a project for which the package:flutter doesn't match, we should error out (or offer to correct?).

I hit this confusion with some regularity at home where I have a project with flutter pinned to a specific version via git submodules.  I don't update that project as often as other flutter projects.  I still have flutter in my path as recommended by https://flutter.io/setup/#get-the-flutter-sdk.   See https://github.com/flutter/flutter/issues/3770 about pinning flutter.

@devoncarew @abarth

**Comment by eseidelGoogle** [comment]
Related (but less critical) is the fact that when you specify --local-engine with the flutter tool, we could warn if sky_services and sky_engine paths are not overridden to match.

**Comment by Hixie** [comment]
We do now catch this kind of thing.
