### ISSUE TITLE
CustomScrollView scroll position changes spuriously when rendering images

### ISSUE THREAD

**Issue by cvolzke4** [flutter/flutter#38776]
## Steps to Reproduce

1. Create a CustomScrollView that renders a SliverList.
2. Create two buttons that switch the list in SliverList to:
   - A list of cards with an image each.
   - A list of cards without images.
3. Add logic to jump to the top when a button is tapped (see below).
4. Scroll to the bottom of the list with images, then tap the button to switch lists.
5. Scroll to the bottom of the list without images, then tap the button to switch lists.
6. Scroll to the bottom of the list with images, then tap the button to switch lists.

Expected behaviour:
* When tapping the button to switch to the list with images, the scroll position should be set to the top.

Actual behaviour:
* The scroll position moves from 0 to ~3000 after a 10-50 millisecond delay.

Code to set the scroll position to the top:

```dart
  void didUpdateWidget(PostList oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.buttonThatWasSelected != widget.buttonThatWasSelected) {
      _jumpToTop();
    }
  }

  void _jumpToTop() async {
    // Yield so that [ScrollController.jumpTo] is called outside the
    // didUpdateWidget() method, which isn't supported.
    await null;

    if (_scrollController.hasClients && _headersTotalHeight != null) {
      _scrollController.jumpTo(0);

      ScrollPosition.forThisReproTemporarilyShowStackTraceOfPixelChange = true;
      await Future.delayed(Duration(milliseconds: 100));
      ScrollPosition.forThisReproTemporarilyShowStackTraceOfPixelChange = false;

      if (mounted && target.round() != _scrollController.offset.round()) {
        print('====Scroll position didnt remain');
      }
  }
```

I'm using `NetworkImages`, but this is reproducible when the `NetworkImages` are cached. The delay between setting the offset to zero and the position jumping doesn't increase when setting the phone to 3G or airplane mode (using cached images).

During the delay period, no build() methods are called on any of the app's widgets.

I suspect this is happening because the images render a little after the scroll position was updated to 0, and the scroll offset calculation is somehow not right.

## Logs

Here is the stack trace when the scroll position is updated from 0 to 3000:

```bash
ScrollPosition._pixels= (package:flutter/src/widgets/scroll_position.dart:128:146)
I/flutter (19352): #1      ScrollPosition.correctBy (package:flutter/src/widgets/scroll_position.dart:302:5)
I/flutter (19352): #2      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1254:16)
I/flutter (19352): #3      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1516:7)
I/flutter (19352): #4      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:783:18)
I/flutter (19352): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter (19352): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:761:13)
I/flutter (19352): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&Paintin...........

```

**Comment by VladyslavBondarenko** [comment]
Hi @diegovar 
does the issue persist? could you provide a complete reproducible code sample?

**Comment by cvolzke4** [comment]
See b/139847982 for a sample app with reproduction steps.

**Comment by darshankawar** [comment]
@cvolzke4 Can you confirm if this is still a valid issue ? If so, could you provide a minimal code sample that shows the issue ?
We don't have access to / know what `b/139847982` is, so not sure how to get reproducible steps from there, as you mentioned.
Thanks.

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
