### ISSUE TITLE
5.1.3 does not work 5.1.2 work fine

### ISSUE THREAD

**Issue by orgio** [flutter/flutter#38779]
![Capture](https://user-images.githubusercontent.com/27058809/63236763-9b0e2800-c271-11e9-987d-e0fe60a68d2b.PNG)

**Comment by BondarenkoStas** [comment]
@orgio Is it still relevant? Please provide more information. Any steps to reproduce the issue. Also, please paste code and logs in text form, not screenshots.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
