### ISSUE TITLE
[web]: Cache Image Network package

### ISSUE THREAD

**Issue by git-maspaad** [flutter/flutter#38781]
Hi Dart Team.
I am currently and expected to use CacheImageNetwork packages to implement in my flutter web. Please upvote this package support for flutter web. Thank you.

Regards,
Fadhli - Jakarta, Indonesia

**Comment by yjbanov** [comment]
We plan to rely on browser's built-in caching capabilities. There's no explicit API. The browser is expected to respect the cache headers sent by the server.

Is there anything beyond this that your app needs? Otherwise, the implementation of this plugin for the Web would be a noop.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
