### ISSUE TITLE
website at 991 pixels wide has layout bug

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3878]
Resize the website to 991 pixels wide:

![screen shot 2016-05-12 at 8 42 25 am](https://cloud.githubusercontent.com/assets/5479/15220763/85896a82-181d-11e6-903d-6ad52a5fdfaf.png)

**Comment by sethladd** [comment]
cc @qchong

**Comment by qchong** [comment]
Looks like this was fixed.
