### ISSUE TITLE
[web]: Routes have /#/ in them

### ISSUE THREAD

**Issue by TheOnlyArtz** [flutter/flutter#38785]
I'm defining named routes and there's always this `/#/` addition, for example:
`localhost:8080/#/` and this is pretty bad in my opinion, is there an option of removing it?

**Comment by jld3103** [comment]
I think it's technically possible, but there are reasons why it is the way it is.
Everything after the ```#``` doesn't reload the page when updating it so I think it's a good way to maintain state. Updating the history would also be possible.

**Comment by b-strauss** [comment]
> I think it's technically possible, but there are reasons why it is the way it is.
> Everything after the `#` doesn't reload the page when updating it so I think it's a good way to maintain state. Updating the history would also be possible.

Theres the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) for that. It changes the url but doesn't do a page reload.

**Comment by jld3103** [comment]
That was what I meant

**Comment by yjbanov** [comment]
We currently provided only the hash strategy. We should provide support for push/pop state and other strategies, including user-defined strategies. I'll mark this as a new feature.

**Comment by olivernybroe** [comment]
A HTML5 History strategy would be awesome! ❤️ 
However it does require a little more work for users to setup on static hosting providers and some doesn't support it.

It would also require some extra code in the local web server, so it tries to resolve it as an asset first and if it  is not an asset it let's the strategy handle it.

**Comment by johnpryan** [comment]
I think this is a dupe of https://github.com/flutter/flutter/issues/33245

**Comment by mdebbar** [comment]
Thanks @johnpryan. Given that the other issue (https://github.com/flutter/flutter/issues/33245) has more thumbs-ups, I'll close this one.
