### ISSUE TITLE
[web]: Hi , i am new to flutter and working on flutter web project. i am able to create the basic web page ..I want to know how can i enable vertical scrollbar in browser when the browser height is smaller than the required size ?

### ISSUE THREAD

**Issue by rajujin1** [flutter/flutter#38795]
Hi , i am new to flutter and working on flutter web project. i am able to create the basic web page ..I want to know how can i enable vertical scrollbar in browser when the browser height is smaller than the required size ?

**Comment by jld3103** [comment]
Currently there is no scrollbar. You can just scroll.

**Comment by BondarenkoStas** [comment]
@rajujin1 I think this issue can be closed. Feel free to file a new issue with request for the scrollbar for flutter_web.
