### ISSUE TITLE
[web] How to publish my flutter web app to firebase. 

### ISSUE THREAD

**Issue by Parmendrakumar** [flutter/flutter#38793]
Hi,

I have developed a demo based application and I want to host this web app, How I can host this app on firebase or any thing better than firebase for free.

**Comment by jld3103** [comment]
You will find and index.html in ```build/web``` and all the files that belong to it after running ```flutter build web```. Then you can host it like any normal web page, but that doesn't belong to this issue tracker.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
