### ISSUE TITLE
Build number being modified

### ISSUE THREAD

**Issue by b0bh00d** [flutter/flutter#38798]
Ok, this appears to relate to https://github.com/flutter/flutter/issues/37320, which I reported last month.

I disabled the "version" value in the pubspec.yaml file.  I am passing the "--build-name" and "--build-number" on the flutter build line:

`flutter build apk --target-platform android-arm,android-arm64 --split-per-abi --flavor beta --release --build-name="2020.0" --build-number=1908182245`

However, when I go to install the APK, it is displaying the value "1908183143" as the build number.  Something in this toolchain is modifying the build number value I keep trying to set, and I don't see how an app can be published when the build number (which is the version that Google Play will regard when I need to upload a new version) is being randomly changed by Flutter each time a build is run.

`flutter doctor -v` output:

[√] Flutter (Channel master, v1.8.5-pre.145, on Microsoft Windows [Version 10.0.17134.254], locale en-US)
    • Flutter version 1.8.5-pre.145 at M:\Flutter\flutter_sdk
    • Framework revision 9cba33d0b1 (5 days ago), 2019-08-14 05:47:36 -0400
    • Engine revision 25c56bcaeb
    • Dart version 2.5.0 (build 2.5.0-dev.2.0 b173229baa)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at Y:\Dev\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = Y:\Dev\Android\Sdk
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by b0bh00d** [comment]
The above behavior is what I observed on our CI system.  However, I ran the command line I provided above on my local development machine, and the resulting APK is displaying the value "1908183245" when I try to install it.  The build number is even being modified on my local machine somewhere--and for some unknown reason--in this toolchain.

**Comment by b0bh00d** [comment]
I executed the build line again, setting "build-number" to 1.  The resulting APK displays "1001" for the build number on install.  Where is this behavior documented?

**Comment by b0bh00d** [comment]
Ok, I did some digging, and found where the toolchain is applying this "1000" multiplier.  It's in `packages/flutter_tools/gradle/flutter.gradle`.  This behavior is being triggered by the `--split-per-abi` command line option.  The code in `flutter.gradle` is enforcing the behavior defined by the "Configure versioning" section of this page:

https://developer.android.com/studio/build/configure-apk-splits

Mystery solved.  Now I know how to work around it--build each APK separately, and rename them in between, and the build number I want will stick.

Assuming somebody ultimately reads this, please be aware that I am not uploading APKs to the Play Store (I'm uploading an appbundle), but the these APKs are provided to internal testers to side-load for initial testing/usage before the appbundle is uploaded.

**Comment by fzyzcjy** [comment]
@b0bh00d Hi how do you "build each APK separately, and rename them in between"? Do you mean changing the build number manually?
