### ISSUE TITLE
[Flutter Web] Non-default entrypoint breaks run command

### ISSUE THREAD

**Issue by rostopira** [flutter/flutter#38797]
I've missed exact moment, when after upgrading flutter web is completely broken again
After running `flutter run -d chrome` I see only "Build application for the web..." in terminal and following error in JS console:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:143 Uncaught Error: Script error for "main_web_entrypoint.dart.bootstrap"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168)
    at HTMLScriptElement.onScriptError (require.js:1738)
```
Flutter Doctor:
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.9.1-pre.89, on Mac OS X 10.14.4 18E226, locale en-BY)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
[✓] VS Code (version 1.37.0)
[✓] Connected device (4 available)

• No issues found!
```
UPD: with `--verbose` there is no errors as well. Actually reproduces only on one project, which I can't share

**Comment by rostopira** [comment]
![image](https://user-images.githubusercontent.com/16724952/63277781-9f0c6b00-c2ae-11e9-8553-6d2e807f4c55.png)

**Comment by rostopira** [comment]
When using `flutter build web -t lib/web/main.dart` it works fine
However, I've noticed in `--verbose` mode `run` command finishes with:
```
[ +392 ms] About to build [web]...
[   +7 ms] Running build...
[  +50 ms] Serving DevTools at http://127.0.0.1:65365

[ +359 ms] Running build completed, took 169ms

[   +1 ms] Caching finalized dependency graph...
[  +66 ms] Caching finalized dependency graph completed, took 338ms

[   +8 ms] Succeeded after 519ms with 0 outputs (0 actions)
```
Zero outputs?

**Comment by rostopira** [comment]
I've finally figured out: it fails when using non-default entry point.
I've moved `lib/web/main.dart` to `lib/main.dart` and it's working

**Comment by yjbanov** [comment]
We should be able to support entrypoints anywhere inside lib/

/cc @jonahwilliams
