### ISSUE TITLE
Flutter doctor not working with `alpine/git` system in Docker

### ISSUE THREAD

**Issue by gmonna** [flutter/flutter#38799]
I am trying to deploy a Flutter Web project with Docker, and I would like to install a light system when setting up Flutter. The problem is that if I install `node:10` (with `FROM node:10`) everything works fine, but if I try to use `alpine/git` or `node:10-alpine` (that are way lighter and smaller than `node`) the `flutter doctor` command does not work, with the output I am pasting below. Is there something I am not doing and I should do when using `alpine/git` that maybe is automatically done with `node`?

## Steps to Reproduce

When setting up the Dockerfile, do the following steps

1. Start file with `FROM alpine/git`
2. Install `bash` and `curl` with `RUN apk add --no-cache bash curl curl-dev`
3. Try to add `RUN flutter doctor` and you will have the following log

## Logs

```
flutter doctor -v
```

```
Building flutter tool...
/usr/local/flutter/bin/cache/dart-sdk/bin/pub: line 49: /usr/local/flutter/bin/cache/dart-sdk/bin/dart: No such file or directory
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
/usr/local/flutter/bin/cache/dart-sdk/bin/pub: line 49: /usr/local/flutter/bin/cache/dart-sdk/bin/dart: No such file or directory
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)
/usr/local/flutter/bin/cache/dart-sdk/bin/pub: line 49: /usr/local/flutter/bin/cache/dart-sdk/bin/dart: No such file or directory
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left)
^C
```

**Comment by gmonna** [comment]
Solved by using `FROM buildpack-deps:stretch-scm` and by installing `unzip`.

**Comment by matsp** [comment]
Anyone has a solution for the Alpine base image? I am running in the same problem when migrating from archlinux to Alpine. It shouldn't be a path problem. Dart SDK is in the path but not executable..
