### ISSUE TITLE
[Dart lang] Improve functional programming (FP) with `@pure` annotation

### ISSUE THREAD

**Issue by truongsinh** [flutter/flutter#38807]
Continue from https://groups.google.com/a/dartlang.org/forum/?utm_medium=email&utm_source=footer#!msg/analyzer-discuss/mRAZmh9tdUE/nbAIDGpYAwAJ

This is a Dart feature request, but I assume it's very much aligned with Flutter's philosophy of functional reactive. FP has only 2 principles, `immutability` and `referential transparency`. Right now, `immutability` can only be achieved/guarded by `@immutable` annotation (ref https://api.flutter.dev/flutter/meta/Immutable-class.html and https://medium.com/dartlang/an-intro-to-immutability-with-dart-d4de871865c7). With proposed `@pure` (and some utilities from https://github.com/spebbe/dartz), hopefully we can achieve much better support for FP in Dart.

## Use case
```dart
class RandomWordsState extends State<RandomWords> {
  @override @pure
  Widget build(BuildContext context) {
    final wordPair = WordPair.random(); // analyzer throws error because `WordPair.random` cannot be invoked in a `pure` method/function
    return Text(wordPair.asPascalCase);
  }
}
```

```dart
@pure
int sum (int a, int b) {
  return a + b; // good
}
```

```dart
@pure
int sum (int a, int b) {
  print(a); // analyzer throws error because `print` is a side-effect invocation
  return a + b;
}
```
## Proposal

Adding `@pure` annotation to https://pub.dev/packages/meta

## Related
- https://dlang.org/spec/function.html#pure-functions
- https://discuss.kotlinlang.org/t/rationalizating-pure-functions-on-kotlin/9430
- https://discuss.kotlinlang.org/t/feature-request-pure-function-annotation-and-analysis

**Comment by jonahwilliams** [comment]
It seems like this issue would be better suited for the dart-lang/sdk or dart-language repository?

**Comment by jonahwilliams** [comment]
I'm curious to know whether it is possible to annotate any non-trivial function as pure. You example of printing has a side effect usually, but by that standard so do exceptions which may invoke methods on the current Zone https://api.dartlang.org/stable/2.4.1/dart-async/Zone/handleUncaughtError.html

**Comment by truongsinh** [comment]
> It seems like this issue would be better suited for the dart-lang/sdk or dart-language repository?

Completely agree, however, I got in touch with dart-lang folks earlier and they suggested me to see whether we have strong use case in Flutter, as they (dart-lang folks) don't have other strong use cases for FP for the time being (see the discussion in https://groups.google.com/a/dartlang.org/forum/?utm_medium=email&utm_source=footer#!msg/analyzer-discuss/mRAZmh9tdUE/nbAIDGpYAwAJ)

> but by that standard so do exceptions

I think throwing exceptions does indeed count as side-effect. To my limited knowledge, in FP, there should be no exception. [Errors are values](https://blog.golang.org/errors-are-values), and usually they are returned from a pure function in [`Either` data type](https://www.scala-lang.org/api/2.9.3/scala/Either.html)

> Convention dictates that Left is used for failure and Right is used for success.

I'm not saying we have to change the Flutter SDK code to follow this convention and convert all exceptions to `Either`, but the possibility of using `@pure` and more FP styles would be appealing, and it's trivial for the coders to convert an exception to `Either` using a utility function anyway (similar to [Node's `promisify` utility](https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original))

**Comment by jonahwilliams** [comment]
I'm not really qualified to speak on the merits of functional programming. But I do think there is value in writing idiomatic dart, of which things like Exceptions/Errors are a part of. Similarly, one strong value of OOP paradigms is that I can swap out the implementation of an interface without updating the call sites. For example, I might have a class which caches certain operations (non-pure).

It sounds like @pure would mostly be useful for top level functions or small closures. While it is perfectly reasonable to utilize these when provided, I don't know how this annotation could be used for classes/methods which constitute the bulk of Dart code.

**Comment by truongsinh** [comment]
> Similarly, one strong value of OOP paradigms is that I can swap out the implementation of an interface without updating the call sites. For example, I might have a class which caches certain operations (non-pure).

Swapping out should be the same in any clean architecture (interface vs implementation). Caching is an interesting example. If we're referring to I/O caching, I/O itself is already impure (in which case the solution in FP is `io monad`). If we're referring to memoization, a quick [Googling](https://www.google.com/search?q=memoization+functional+programming), shows that it's not a problem, though I myself haven't put a lot of thought into it.

>  I don't know how this annotation could be used for classes/methods which constitute the bulk of Dart code.

`build` method of the `Widget` is one where we mostly want to have pure methods I think.

**Comment by truongsinh** [comment]
I just found out @rrousselGit 's interesting repo https://github.com/rrousselGit/functional_widget , which can help to write the whole UI in functions (not class)

**Comment by darshankawar** [comment]
@truongsinh 
Revisiting this issue, I came across this recently published community package https://pub.dev/packages/fpdart that you can take a look and check if it helps to serve the original purpose you described ?

**Comment by rrousselGit** [comment]
This shouldn't be closed.

The packages mentioned have nothing to do with a `@pure` annotation for analysis purpose. They are side tools to help implementing a "pure" function, not tools to detect if a pure function isn't actually pure
