### ISSUE TITLE
Malformed link in Encoding.getByName() documentation.

### ISSUE THREAD

**Issue by bstichter** [flutter/flutter#38802]
The documentation page for Encoding.getByName() has a link to supporting documentation on the IANA website.  Unfortunately, the link is malformed and contains an extra character so the intended page does not come up on the IANA site.  The intended link is:
     https://www.iana.org/assignments/character-sets/character-sets.xml
The actual link is:
     http://www.iana.org/assignments/character-sets/character-sets.xml)

**Comment by BondarenkoStas** [comment]
Lack of space before the bracket after url
https://api.dartlang.org/stable/2.4.1/dart-convert/Encoding/getByName.html
