### ISSUE TITLE
ListWheelScrollView children do not respond on gesture (onTap) events

### ISSUE THREAD

**Issue by kofan** [flutter/flutter#38803]
## Steps to Reproduce

Hi! Here is my widget that uses `ListWheelScrollView` with `FixedExtentScrollController`:

```dart
import 'package:flutter/material.dart';

class LetterWheel extends StatefulWidget {
  const LetterWheel({Key key}) : super(key: key);

  @override
  _LetterWheelState createState() => _LetterWheelState();
}

class _LetterWheelState extends State<LetterWheel> {
  FixedExtentScrollController scrollController;

  @override
  void initState() {
    scrollController = FixedExtentScrollController();
    super.initState();
  }

  @override
  void dispose() {
    scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ListWheelScrollView(
      controller: scrollController,
      physics: const FixedExtentScrollPhysics(),
      itemExtent: 110,
      children: ['A', 'B', 'C', 'D', 'E', 'F', 'G']
          .map(
            (letter) => Container(
              margin: const EdgeInsets.all(10),
              height: 90,
              color: Colors.yellow,
              child: GestureDetector(
                onTap: () => print('Letter "$letter" is pressed.'),
                child: Center(
                  child: Text(
                    letter,
                    style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                  ),
                ),
              ),
            ),
          )
          .toList(),
    );
  }
}
```

**Expected result:** When the list item is tapped the message is printed to the console.

**Actual result:** When the list item is tapped nothing happens.

Here is my `flutter doctor -v` output:

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F203, locale en-UA)
    • Flutter version 1.7.8+hotfix.3 at /Users/mkofan/Software/flutter
    • Framework revision b712a172f9 (6 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/mkofan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)
```

**Comment by kofan** [comment]
Here is a similar _unresolved_ issue on **[Stackoverflow](https://stackoverflow.com/questions/56255739/listtile-ontap-is-working-when-i-use-listview-but-when-i-use-listwheelscrollvie)**.

**Comment by spiderion** [comment]
I have the same issue. Is there any solution?

**Comment by spiderion** [comment]
@kofan did you find any solution?

**Comment by kofan** [comment]
Unfortunately, no. I didn't find a solution. I've abandoned the initial design that was based on `ListScrollView` and fallen back to a regular `ListView` 😔

**Comment by TimG38** [comment]
A couple reports from:
- https://stackoverflow.com/questions/54890731/listwheelscrollview-children-do-not-recognize-ontap
- https://stackoverflow.com/questions/56255739/listtile-ontap-is-working-when-i-use-listview-but-when-i-use-listwheelscrollvie
- https://stackoverflow.com/questions/54314573/ontap-doesnt-work-on-listwheelscrollview-children-items-flutter

And my own testing, example snippet:
```
    for (var i = 0; i < 30; i++) {
      _myList.add(ListTile(
        enabled: true,
        onTap: () {
          print('hello world$i');
        },
        title: Text('title$i',),
        subtitle: Text('subtitle$i'),
      ));
    }
      ...
    body: ListWheelScrollView(
        controller: _controller, // FixedExtentScrollController
        itemExtent: 30,
        children: _myList,
    ),
```
That ListTile’s `onTap` doesn’t respond, no print is seen.

Even if I wrap a child with `GestureDetector`, such as:
```
    _myList.add(GestureDetector(
      onTap: () {
        print('hello world$i');
      },
      child: ListTile(
        enabled: true,
        title: Text('title$i',),
        subtitle: Text('subtitle$i'),
      ),
```
The GestureDetector’s `onTap` also doesn’t respond.
I’ve also tried a `Button`, same thing with the `onPressed`.

But if I replace ListWheelScrollView with `ListView`, then all is working as expected.

It seems the only ways to interact with this is through `onSelectedItemChanged` or the controller’s `selectedItem`?

**Comment by charlessfriend** [comment]
```
 GestureDetector(
     child: ListWheelScrollView(
          onSelectedItemChanged: (index) => selectedItem = index
     ),
     onTap: () => print('Selection: $selectedItem')
```

**Comment by TimG38** [comment]
> ```
>  GestureDetector(
>      child: ListWheelScrollView(
>           onSelectedItemChanged: (index) => selectedItem = index
>      ),
>      onTap: () => print('Selection: $selectedItem')
> ```

We're looking for tap/touch response on the individual children of the `ListWheelScrollView`, not on the list itself.

**Comment by charlessfriend** [comment]
> > ```
> >  GestureDetector(
> >      child: ListWheelScrollView(
> >           onSelectedItemChanged: (index) => selectedItem = index
> >      ),
> >      onTap: () => print('Selection: $selectedItem')
> > ```
> 
> We're looking for tap/touch response on the individual children of the `ListWheelScrollView`, not on the list itself.

As a workaround, you can use that same code and just calculate where the tap occurred. Based on the size of your ListWheelScrollView, you can figure out if the tap is within the child's rect.  And you should know which child based on the onSelectedItemChanged.  You can also use GlobalKey to get the context of the selected child and get the rect of that child and it's descendants. You can  then use callbacks to call child methonds.

```
TapUpDetails tapDetails;
    Rect childRect;
    return GestureDetector(
      onTapUp: (t) {
        tapDetails = t;
      },
      onTap: () {
        var thisWidget = context.findRenderObject();
        var childPosition = Rect.fromCenter(
            center: thisWidget.semanticBounds.center,
            width: childRect.width,
            height: childRect.height);
        print('parent tapped: ${tapDetails.localPosition}');
        if (childPosition.contains(tapDetails.localPosition))
          print('child was tapped');
        else
          print('child was not tapped');
      },
      child: ListWheelScrollView.useDelegate(
        physics: FixedExtentScrollPhysics(),
        itemExtent: 200,
        childDelegate: ListWheelChildLoopingListDelegate(
          children: rotatedChildren,
        ),
        onSelectedItemChanged: (index) {
          var childWidget = rotatedChildren[index];
          var childKey = childWidget.key as GlobalKey;
          childRect = childKey.currentContext.findRenderObject().semanticBounds;
          print('parent bounds: ${context.findRenderObject().semanticBounds}');
          print('child bounds: $childRect');
```

**Comment by Moatasem1994** [comment]
..... No Solution yet?

**Comment by rostopira** [comment]
@Moatasem1994 yeah, get used to it. Google's promise to acquire more devs to resolve thousands of  Flutter issues counts only for "Solve as many easy issues as possible", not to fix something more complicated than 10 lines of code. I've been looking through the source code for 4 hours, and the only solution I could think of, is to rewrite evyrthing from scratch to fix it. I felt a bit guilty, that I couldn't fix it, but hey, "everything is a widget" isn't a case here, even with years of experience with native development. And now I have end up with some of the ugliest hacks I've ever made, looking for the renderbox of every widget in list and checking if global position of tap is in it

**Comment by sgehrman** [comment]
I need this too.

**Comment by Stuazt** [comment]
A lot of issues with ListWheelScrollView... use this widget with caution...

**Comment by Adel-Cabrera** [comment]
I don't feel alone anymore.

**Comment by dannyboy424242** [comment]
I just spent three days building a really neat pair of ListWheelScrollView's that can interact, wheeling to certain positions depending on the other, building out widgets for the children that look really nice... finally get to the end-game having JUST PRESUMED the child widgets would be just normal child widgets and I find that I cant click on them!!?!? My impossibly nice looking double wheel menu is now unusable. I either implement hack as per others have mentioned, or switch to something far more dull and abandon the work. Seriously, 'everything is a widget' well it isn't in this case is it? The children of this widget lose one of the most vital parts of their widgetiness and cannot be clicked on. Fix it, fix it, fix it, fix it.

**Comment by istornz** [comment]
> I just spent three days building a really neat pair of ListWheelScrollView's that can interact, wheeling to certain positions depending on the other, building out widgets for the children that look really nice... finally get to the end-game having JUST PRESUMED the child widgets would be just normal child widgets and I find that I cant click on them!!?!? My impossibly nice looking double wheel menu is now unusable. I either implement hack as per others have mentioned, or switch to something far more dull and abandon the work. Seriously, 'everything is a widget' well it isn't in this case is it? The children of this widget lose one of the most vital parts of their widgetiness and cannot be clicked on. Fix it, fix it, fix it, fix it.

Exactly the same story for me 😔

**Comment by savy-91** [comment]
> > I just spent three days building a really neat pair of ListWheelScrollView's that can interact, wheeling to certain positions depending on the other, building out widgets for the children that look really nice... finally get to the end-game having JUST PRESUMED the child widgets would be just normal child widgets and I find that I cant click on them!!?!? My impossibly nice looking double wheel menu is now unusable. I either implement hack as per others have mentioned, or switch to something far more dull and abandon the work. Seriously, 'everything is a widget' well it isn't in this case is it? The children of this widget lose one of the most vital parts of their widgetiness and cannot be clicked on. Fix it, fix it, fix it, fix it.
> 
> Exactly the same story for me pensive

You are not alone..

**Comment by emvaized** [comment]
Maybe some sort of `GestureArena` should be implemented, in order to ignore only taps?
I've seen how a similar problem was fixed this way [here](https://github.com/akshathjain/sliding_up_panel/pull/135).

**Comment by GuiHS01** [comment]
And any solution? 😫

**Comment by pydoni** [comment]
Well I guess that Google will prepair an aniversary party for this bug....

**Comment by zkx2020** [comment]
I have the same problem when I finished my listwheelscrollview design....I just can't ontap the item...who could help me!!

**Comment by dannyboy424242** [comment]
> I have the same problem when I finished my listwheelscrollview design....I just can't ontap the item...who could help me!!

Someone posted a solution above using a gesture detector above this one. In theirs they used callbacks when each item was rendered to save their location to some vars in state. They then used the callback from the gesture detector and some logic to determine if the click was in that location. I couldn't get that to work as the first of those callbacks - the post render one, wasn't consistent, it would simply not be called sometimes and was wrong other times. Seemed to relate to the on-demand nature of the sub-widgets (of the listwheelscrollview) and their builds. In the end I used some messages from a scroll controller (you can create one and pass it to the view rather than letting it use its own), in combination with some info from a box constraints above the widget, to then handle gesture detector events and determine if they are over the sub-items. It wasn't perfectly accurate as I didn't compute the dynamic shape the items are squished into, but for my purpose that didn't matter. So sorry for not posting code, I'm under contract for that work and can't put it here, but I think that description includes everything. Just start from the solution mentioned above with the gesture detector and build your own method to see where exactly the items are.

Obviously that doesn't let widgets inside the items behave differently, oh and I think they are built once because I cant get them to repsond to state changes via react or providor / notify listener type events. Again, I just gave up a bit and left them a little featureless in the end.

Others likely have better solutions, I'm not the best with Flutter yet - love it - but it still has a fair few things like this in it.

**Comment by zkx2020** [comment]
> 
> 
> > I have the same problem when I finished my listwheelscrollview design....I just can't ontap the item...who could help me!!
> 
> Someone posted a solution above using a gesture detector above this one. In theirs they used callbacks when each item was rendered to save their location to some vars in state. They then used the callback from the gesture detector and some logic to determine if the click was in that location. I couldn't get that to work as the first of those callbacks - the post render one, wasn't consistent, it would simply not be called sometimes and was wrong other times. Seemed to relate to the on-demand nature of the sub-widgets (of the listwheelscrollview) and their builds. In the end I used some messages from a scroll controller (you can create one and pass it to the view rather than letting it use its own), in combination with some info from a box constraints above the widget, to then handle gesture detector events and determine if they are over the sub-items. It wasn't perfectly accurate as I didn't compute the dynamic shape the items are squished into, but for my purpose that didn't matter. So sorry for not posting code, I'm under contract for that work and can't put it here, but I think that description includes everything. Just start from the solution mentioned above with the gesture detector and build your own method to see where exactly the items are.
> 
> Obviously that doesn't let widgets inside the items behave differently, oh and I think they are built once because I cant get them to repsond to state changes via react or providor / notify listener type events. Again, I just gave up a bit and left them a little featureless in the end.
> 
> Others likely have better solutions, I'm not the best with Flutter yet - love it - but it still has a fair few things like this in it.

Thanks! That solution sounds difficult...Because I need to use a lot of accurate ontap function. I maybe will choose listview widget to replace the listwheelscrollview..though listwheelscrollview widget looks so cool...

**Comment by CompillerMaster** [comment]
You can use onSelectedItemChanged this alternative is easy.

ListWheelScrollView({...
ValueChanged<int> onSelectedItemChanged
})
example: 
 ListWheelScrollView(
                    ...
                    onSelectedItemChanged: (index) {
                      lookmymsg();
                    },
...
)
chek Flutter API reference documentation : https://api.flutter.dev/flutter/widgets/ListWheelScrollView-class.html

**Comment by istornz** [comment]
> You can use onSelectedItemChanged this alternative is easy.
> 
> 
> 
> ListWheelScrollView({...
> 
> ValueChanged<int> onSelectedItemChanged
> 
> })
> 
> example: 
> 
>  ListWheelScrollView(
> 
>                     ...
> 
>                     onSelectedItemChanged: (index) {
> 
>                       lookmymsg();
> 
>                     },
> 
> ...
> 
> )
> 
> chek Flutter API reference documentation : https://api.flutter.dev/flutter/widgets/ListWheelScrollView-class.html
> 
> 

The issue related here is to add a tap gesture on items not to detect when an item change !

**Comment by CompillerMaster** [comment]
I can resolved this problem with:

GestureDetector(
                    child: ListWheelScrollView(
                      ...
                      onSelectedItemChanged: (index) {
                        lookmymsg(index);
                      },
...
                      children: <Widget>[
                        for (int i = 0; i < blogs.length; i++)
                          MyItem(blogs: blogs[i], index: i + 1)
                      ],
                    ),
                    onTap: () => print('Selection: $keyBlog')
)

Function lookmymsg(int i) {
    for (int j = 0; j < blogs.length; j++) {
      if (j == i) {
        setState(() {
          keyBlog = blogs[j].id;
        });
      }
    }
  }

**Comment by ldesordi** [comment]
same issue

**Comment by Creolophus** [comment]
Same issue, sad

**Comment by fisksektionen** [comment]
Same issue. It is a rather big problem for me.

**Comment by iamporus** [comment]
It's so frustrating to see such an important bug being neglected for such a long time.
Please fix it.

**Comment by SimplyProgger** [comment]
Same problem...

**Comment by definev** [comment]
Please fix this, I have the same issue :(((

**Comment by rahuldange09** [comment]
Instead of commenting on thread. Please vote(thumbs up) on main asked issue. So then only it will move to higher priority for fixes.

**Comment by leejunofan** [comment]
Same problem... its stuck in app...

**Comment by william198824** [comment]
Same problem...

**Comment by AnavrinApps** [comment]
Same problem, its been over a year and no one is bothered to fix this issue

**Comment by TahaTesser** [comment]
<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: LetterWheel(),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

class LetterWheel extends StatefulWidget {
  const LetterWheel({Key key}) : super(key: key);

  @override
  _LetterWheelState createState() => _LetterWheelState();
}

class _LetterWheelState extends State<LetterWheel> {
  FixedExtentScrollController scrollController;

  @override
  void initState() {
    scrollController = FixedExtentScrollController();
    super.initState();
  }

  @override
  void dispose() {
    scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ListWheelScrollView(
      controller: scrollController,
      physics: const FixedExtentScrollPhysics(),
      itemExtent: 110,
      children: ['A', 'B', 'C', 'D', 'E', 'F', 'G']
          .map(
            (letter) => Container(
              margin: const EdgeInsets.all(10),
              height: 90,
              color: Colors.yellow,
              child: InkWell(
                onTap: () => print('Letter "$letter" is pressed.'),
                child: Center(
                  child: Text(
                    letter,
                    style: const TextStyle(
                        fontSize: 20, fontWeight: FontWeight.bold),
                  ),
                ),
              ),
            ),
          )
          .toList(),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-4.0.pre.57, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-4.0.pre.57 at /Users/tahatesser/Code/flutter_master
    • Framework revision fdac8a9d1f (14 hours ago), 2020-10-25 19:47:02 -0400
    • Engine revision d4a3c9c471
    • Dart version 2.11.0 (build 2.11.0-256.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.1
    • iPhone 12 (mobile)     • 318957C3-E4BB-4B35-A3C7-14F515B0E665 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 86.0.4240.111

• No issues found!
```

```bash
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 84f3d28555 (11 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • iPhone 12 (mobile) • 318957C3-E4BB-4B35-A3C7-14F515B0E665 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by rp3droso** [comment]
I solved the problem. I hope is helpful.
1) create a int variable in State class.

```
class _MenuWheelState extends State<MenuWheel> {
  int _vIndiceWheel;
```

  
2) in the Function onSelectedItemChanged of the ListWheelScrollView set the variable:

```
    onSelectedItemChanged: (ValueChanged) {
        setState(() {
           _vIndiceWheel = ValueChanged; });
    },

```
3) create a GestureDetecture and put the ListWheelScrollView inside:

```
    GestureDetector(
                  child: ListWheelScrollView(...

```
4) create onTap function at the GestureDetecture like this code:
  
```
    // this is necessary 
    if (_vIndiceWheel == null) {
       _vIndiceWheel = 0;
       }

    switch (_vIndiceWheel) {
     case 0:
        {
         Navigator.push(
           context,
           MaterialPageRoute(
           builder: (context) {
             return YourSecondScreen();
              },
       ...
```

**Comment by krisztianodor** [comment]
> I solved the problem. I hope is helpful.
> 
> 1. create a int variable in State class.
> 
> ```
> class _MenuWheelState extends State<MenuWheel> {
>   int _vIndiceWheel;
> ```
> 
> 1. in the Function onSelectedItemChanged of the ListWheelScrollView set the variable:
> 
> ```
>     onSelectedItemChanged: (ValueChanged) {
>         setState(() {
>            _vIndiceWheel = ValueChanged; });
>     },
> ```
> 
> 1. create a GestureDetecture and put the ListWheelScrollView inside:
> 
> ```
>     GestureDetector(
>                   child: ListWheelScrollView(...
> ```
> 
> 1. create onTap function at the GestureDetecture like this code:
> 
> ```
>     // this is necessary 
>     if (_vIndiceWheel == null) {
>        _vIndiceWheel = 0;
>        }
> 
>     switch (_vIndiceWheel) {
>      case 0:
>         {
>          Navigator.push(
>            context,
>            MaterialPageRoute(
>            builder: (context) {
>              return YourSecondScreen();
>               },
>        ...
> ```

**No, it's not helpful. Why don't you read back? Why are you spamming? We're looking for tap/touch response on the individual children of the ListWheelScrollView...**

**Comment by istornz** [comment]
> > I solved the problem. I hope is helpful.
> 
> > 
> 
> > 1. create a int variable in State class.
> 
> > 
> 
> > ```
> 
> > class _MenuWheelState extends State<MenuWheel> {
> 
> >   int _vIndiceWheel;
> 
> > ```
> 
> > 
> 
> > 1. in the Function onSelectedItemChanged of the ListWheelScrollView set the variable:
> 
> > 
> 
> > ```
> 
> >     onSelectedItemChanged: (ValueChanged) {
> 
> >         setState(() {
> 
> >            _vIndiceWheel = ValueChanged; });
> 
> >     },
> 
> > ```
> 
> > 
> 
> > 1. create a GestureDetecture and put the ListWheelScrollView inside:
> 
> > 
> 
> > ```
> 
> >     GestureDetector(
> 
> >                   child: ListWheelScrollView(...
> 
> > ```
> 
> > 
> 
> > 1. create onTap function at the GestureDetecture like this code:
> 
> > 
> 
> > ```
> 
> >     // this is necessary 
> 
> >     if (_vIndiceWheel == null) {
> 
> >        _vIndiceWheel = 0;
> 
> >        }
> 
> > 
> 
> >     switch (_vIndiceWheel) {
> 
> >      case 0:
> 
> >         {
> 
> >          Navigator.push(
> 
> >            context,
> 
> >            MaterialPageRoute(
> 
> >            builder: (context) {
> 
> >              return YourSecondScreen();
> 
> >               },
> 
> >        ...
> 
> > ```
> 
> 
> 
> **No, it's not helpful. Why don't you read back? Why are you spamming? We're looking for tap/touch response on the individual children of the ListWheelScrollView...**

Please be more polite he just try to help... 🤯

**Comment by krisztianodor** [comment]
To be honest when I started writing I was polite but then I deleted and replaced it. I have been polite too many times. Maybe it's more effective. Next time i can assure you i will put this at the beginning: 'i know you want to be helpful, but' or 'no offense, but'. Sorry :S

**Comment by savy-91** [comment]
@krisztianodor unless "you have been polite too many times" with this specific user, I doubt your message will have any positive effect. Possibly, you have discouraged this user from contributing to any issue in the future because of your toxic attitude.

**Comment by AnavrinApps** [comment]
Honestly, I don't think we can blame anybody here and we know the only solution is when the Flutter team fixes this issue and whats terrible is that they even made a video on Youtube about it even though they knew that this has been a bug since so long.

**Comment by AnavrinApps** [comment]
Also for anyone who urgently needs to use this Widget, I tried using flutter swiper - https://pub.dev/packages/flutter_swiper to   recreate something similar to ListWheelScrollView and its a workaround but not exactly the same thing.

**Comment by rp3droso** [comment]
> >        ...
> > ```
> 
> **No, it's not helpful. Why don't you read back? Why are you spamming? We're looking for tap/touch response on the individual children of the ListWheelScrollView...**

Wow.. I know is not the perfect solution, but I managed to create the situation that you want the user to see, in other words, the user chooses an item on the wheel and when tapping something happens exclusively related to this item. In my case, I wanted the wheel to be a menu and call up other screens. That's what I managed to do. The solution may not be a response per child, but it simulates very well. My intention was to help.

**Comment by doppio** [comment]
Maybe this should be a separate issue, but is there any way to just get ListWheelScrollView to jump/animate to tapped items? That seems like core functionality that should exist in this widget. I don't even need a callback to know which one was tapped, I just want tapped items to be selected.

**Comment by LeLoMAu** [comment]
I know that is just a workaround but worked quite good in my case and maybe could be useful for someone else as well.

As many of you I tried to make ListWheelScrollView children clickable, but since Flutter doesn't fix this issue it is not possible. 

So I thought to workaround by wrapping ListWheelScrollView with Stack widget. 
Then add just above the selected child (i.e. the one centered) a centered clickable SizedBox with GestureDetector() widget, using onTap() method and setting HitTestBehavior.translucent to distinguish from drag the ListWheelScrollView() and tap a children.

The problem then was the alignment of the selected child of ListWheelScrollView which not always match with the centered clickable Sizedbox(), even if they are the same size. 
Therefore I solved transforming ListWheelScrollView() in CupertinoPicker(), which is quite the same but force the selected child to be exactly in the center. 

Here below the code: 

`
class Example extends StatelessWidget{

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        CupertinoPicker.builder(
          itemExtent: 100,
          diameterRatio: 2,
          squeeze: 1.3,
          childCount: 20,
          onSelectedItemChanged: (value) {
            changeSelectedValue(value);
          },
          itemBuilder: (BuildContext context, int index) {
            return cards[index];
          },
        ),
        Center(
          child: GestureDetector(
            behavior: HitTestBehavior.translucent,
            onTap: () {
              print("Tapped");
            },
            child: SizedBox(
              height: 100, // same height as CupertinoPicker itemExtent
              width: MediaQuery.of(context).size.width,
            ),
          ),
        ),
      ],
    );
  }
}
`

**Comment by lucasjbyoung** [comment]
That's great, I'm gonna try it

**Comment by nt4f04uNd** [comment]
shouldn't this have crowd label

**Comment by Cilestal** [comment]
My workaround

`import 'package:flutter/cupertino.dart';

import 'measure_size.dart';

class ClickableListWheelWidget extends StatefulWidget {
  final ListWheelScrollView child;
  final ScrollController scrollController;
  final double listHeight;
  final double itemHeight;

  const ClickableListWheelWidget({
    Key key,
    this.scrollController,
    this.listHeight,
    this.child,
    this.itemHeight
  }) : super(key: key);

  @override
  State<StatefulWidget> createState() => _ClickableListWheelWidgetState();
}

class _ClickableListWheelWidgetState extends State<ClickableListWheelWidget> {
  double _listHeight;
  Offset _tapUpDetails;

  @override
  void initState() {
    _listHeight = widget.listHeight ?? 0.0;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    if (_listHeight == .0) {
      return MeasureSize(
        child: Container(
          height: double.infinity,
        ),
        onChange: (value) {
          setState(() {
            _listHeight = value.height;
          });
        },
      );
    }

    return GestureDetector(
      onTap: _onTap,
      onTapUp: (tapUpDetails) {
        _tapUpDetails = tapUpDetails?.localPosition;
      },
      child: widget.child,
    );
  }

  double _getClickedOffset() {
    if (_tapUpDetails == null) {
      return 0;
    }
    return _tapUpDetails.dy - (_listHeight / 2.0);
  }

  int _getClickedIndex() {
    final currentIndex = widget.scrollController.offset ~/ widget.itemHeight;
    final clickOffset = _getClickedOffset();
    final indexOffset = (clickOffset / widget.itemHeight).round();
    final newIndex = currentIndex + indexOffset;
    return newIndex;
  }

  Future<void> _onTap() async {
    if (widget.scrollController is FixedExtentScrollController) {
      final index = _getClickedIndex();
      (widget.scrollController as FixedExtentScrollController).animateToItem(
          index, duration: Duration(milliseconds: 1000), curve: Curves.ease);
    } else {
      final offset = _getClickedOffset();
      await widget.scrollController.animateTo(widget.scrollController.offset + offset,
          duration: Duration(milliseconds: 1000), curve: Curves.ease);
    }
  }
}`

**Comment by TiffaaMC** [comment]
> My workaround: https://gist.github.com/Cilestal/3efbfa7d172c6bd08aff77e5f08514b3
> MeasureSize: https://gist.github.com/Cilestal/71200abfd44f42881bc49f50e35089c3

Could you include an implementation example please ? Beginner here :)

**Comment by Cilestal** [comment]
> My workaround: https://gist.github.com/Cilestal/3efbfa7d172c6bd08aff77e5f08514b3
> MeasureSize: https://gist.github.com/Cilestal/71200abfd44f42881bc49f50e35089c3

```
final _scrollController = FixedExtentScrollController();
ClickableListWheelWidget(
            scrollController: _scrollController,
            itemHeight: _itemHeight,
            itemCount: widget.items.length,
            child: ListWheelScrollView(
              controller: _scrollController,
              itemExtent: _itemHeight,
              physics: FixedExtentScrollPhysics(),
              overAndUnderCenterOpacity: 0.5,
              perspective: 0.00001,
              onSelectedItemChanged: (index) {
                _focusedIndex = index;
              },
              children: [...widget.items.map((item) => _itemView(item))],
            ),
          )
```

**Comment by jamesnicholls04** [comment]
> https://gist.github.com/Cilestal/3efbfa7d172c6bd08aff77e5f08514b3

Thank you so much for this! I was wondering whether I could have your permission to use it commercially?

Thanks again!

**Comment by definev** [comment]
> My workaround: https://gist.github.com/Cilestal/3efbfa7d172c6bd08aff77e5f08514b3
> MeasureSize: https://gist.github.com/Cilestal/71200abfd44f42881bc49f50e35089c3

should you publish this as a clickable_list_wheel_scroll_view package?

**Comment by Cilestal** [comment]
> > https://gist.github.com/Cilestal/3efbfa7d172c6bd08aff77e5f08514b3
> 
> Thank you so much for this! I was wondering whether I could have your permission to use it commercially?
> 
> Thanks again!

Of course

**Comment by Cilestal** [comment]
For ListWheelScrollView with a fixed height for child, you can use https://pub.dev/packages/clickable_list_wheel_view

**Comment by mjlorenzo** [comment]
Google,

I understand ListWheelScrollView children not receiving input gestures is a fairly reasonable design decision. On the other hand, not making this crystal clear in your documentation is obnoxious. It stands to reason items in this list widget would behave identically to a standard list views **unless otherwise specified**. I wasted three hours today trying to figure out where I was going wrong because this behavior is completely ignored by the official API reference. I may waste more changing course completely. One sentence on the class reference page would do wonders.

**Comment by medst** [comment]
bad user experience here with flutter

**Comment by Cilestal** [comment]
> Guys any solution after 3 years?

https://pub.dev/packages/clickable_list_wheel_view

**Comment by Adrift001** [comment]
马勒戈壁, 我看等谷歌倒闭了, 这个问题也解决不了

**Comment by Terranic** [comment]
I think, the issue is not yet closed. Because if you have a child in a ListWheelScrollView which e.g. has a set of buttons, you can't click the buttons.

**Comment by LkyYuen** [comment]
damn it is 2023 already and Flutter team still not solved it

**Comment by anypwx** [comment]
so sad

**Comment by nt4f04uNd** [comment]
Please read https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs and https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md before commenting here

**Comment by anypwx** [comment]
> Please read https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs and https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md before commenting here

Im sorry，i want  to expression some one emotion only,.but, this bug did't fix, too long time. im use ListWheelScrollView with loop today and same bug.  add gestures on child with  ListWheelScrollView , no respond.  seems you fix the bug ,really?
