### ISSUE TITLE
[cloud_firestore] create document only if it doesn't already exists

### ISSUE THREAD

**Issue by LinusU** [flutter/flutter#38806]
## Use case

I'm trying to create a document in Firestore with a predictable id. I want to make sure that the document is only created once, and never overwritten. In our cloud functions, we are using the JavaScript `create` function for this:

```javascript
const admin = require('firebase-admin')

// ...

const ref = admin.firestore().collection('foobar').doc(id)

await ref.create({ foo: 'bar' })
```

It seems like the `create` function is missing from the Flutter version of the API though, only `set` and `update` is present.

## Proposal

It would be great if we could add `createData` in addition to `setData` and `updateData`:

```dart
import 'package:cloud_firestore/cloud_firestore.dart';

// ...

final ref = Firestore.instance.collection('foobar').document(id);

await ref.createData({ 'foo': 'bar' })
```

**Comment by kroikie** [comment]
@LinusU

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1203. Any further collaboration will be done there.
