### ISSUE TITLE
Clear terminal output

### ISSUE THREAD

**Issue by Levi-Lesches** [flutter/flutter#38819]
## Use case
As someone who runs Flutter from the command line, the tool often fills the windows with output. It would be nice if I could press, say, `c` to clear the output (eg, after fixing an error I don't care about the logs)

## Proposal
  Pressing `c` would clear the console output.

**Comment by Levi-Lesches** [comment]
Can anyone give an update on this? Or how I can help implement this?

**Comment by zanderso** [comment]
Some related source locations:
https://github.com/flutter/flutter/blob/8b2993337acf2ec9517060ce62e530e6c6746366/packages/flutter_tools/lib/src/resident_runner.dart#L1161

https://github.com/flutter/flutter/blob/8b2993337acf2ec9517060ce62e530e6c6746366/packages/flutter_tools/lib/src/base/command_help.dart#L38

**Comment by Levi-Lesches** [comment]
Thank you so much. I'll try to get this work on my device, and if I can I'll make it into a PR (I haven't really contributed much so idk if it'll be good quality).

**Comment by zanderso** [comment]
@Levi-Lesches Thanks for taking a look. We're happy to work with you on your PR once you have something working =)

**Comment by Levi-Lesches** [comment]
I got it to work, but then I realized I was doing it on the `stable` branch. I should be starting from the `master` branch instead, right? I ask also because there appears to have been a change to the terminal in the `master` branch.

**Comment by zanderso** [comment]
Yes, it would have to be on the master branch.

**Comment by Levi-Lesches** [comment]
Thanks, I'll wrap it up tomorrow, but it's coming along (I really like the new changes to the terminal command by the way. So much easier than what's currently in stable).

**Comment by Levi-Lesches** [comment]
PR is at #49819, can you please look it over?

**Comment by Levi-Lesches** [comment]
That one closed since I configured the PR wrong. #50034 is the new one.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/50034 is merged, closing.
