### ISSUE TITLE
Test flake: Issue 34854: Flutter crashing with "could not instantiate image codec"

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#38812]
Filed as https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=34854 Conversation should occur there.

**Comment by ccadieux** [comment]
This is happening on one of our tests after upgrading to flutter 1.9.1+hotfix.2 

Don't have permissions to see the discussion that is linked. Any workarounds would be appreciated.

**Comment by jorgecoca** [comment]
Seeing the same issue as well on a Flutter codebase with no Fuchsia dependencies.

**Comment by Nico04** [comment]
Similar issue here...

**Comment by eliezedeck** [comment]
People are not allowed to view the discussions in the first post. Please, any fix for this?

**Comment by chinmaygarde** [comment]
Triaging engine flake issues: That message is the standard response from the engine for requests to decompress image formats that are not supported. If the decompression is happening from a file, we'd need to find the format of the file (attached to this issue if possible or just ensure that the file is valid and a supported image format). If the image is to be [created from already decompressed pixels](https://api.flutter.dev/flutter/dart-ui/decodeImageFromPixels.html), we'd need to know the width, height and pixel format so we can ensure no bounds checks are being tripped. Without this information, there will be limited progress on this.

**Comment by Hixie** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
