### ISSUE TITLE
web font assets are requested from incorrect url.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#38829]
Currently fonts for the web are being requested from `/fonts/asset-name`, however the bundle structure is `flutter_assets/fonts/asset-name`. this should be consistent with non web applications.

cc @zoeyfan @yjbanov

**Comment by jonahwilliams** [comment]
Actually, this was another case of relative paths coming back to bite us. Good to know the failure case for the web

Duplicate of https://github.com/flutter/flutter/issues/8403

**Comment by zoeyfan** [comment]
Thanks Jonah for your help!
