### ISSUE TITLE
when running a flutter web app, we don't print any information about the debug service url

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#38820]
When running a flutter web app, we don't print any information about the debug service url. Most launches will likely come from IDEs, but when run strictly from the console (`flutter run -d chrome`) we don't print the port+url of the debug service, so user's can't connect IDEs or performance tooling to the running app.

Short term we may just want to print out the debug service url (which, the output is currently going to the verbose logging stream):

```
Debug service listening on ws://localhost:49626/2xD4oFUz73c=
```

In the medium term, we'll also want to provide an easy way for the user to open DevTools against the running session. Perhaps, a hyperlink in the console output, that connects to a local server, installs DevTools if necessary, and re-directs to the session? Or, DevTools could be bundled directly into the flutter sdk or the Dart VM. In any case, we'll just want to make it easier for users to access.

cc @jonahwilliams @jacob314

**Comment by jonahwilliams** [comment]
I'll leave this open for determining a solution for devtools.

**Comment by ocelili** [comment]
i have the same error.
`[INFO] Connecting to the build daemon...
[INFO] Generating build script...
[INFO] Generating build script completed, took 2.1s
[INFO]
[INFO] Daemon is already running.
[INFO] Registering build targets...
[INFO] Starting initial build...
[INFO] Starting resource servers...
[INFO] Serving DevTools at http://127.0.0.1:55069
[INFO] Serving web on http://127.0.0.1:55066
[INFO] About to build [web]...
[INFO] Running build...
[INFO] Running build completed, took 298ms
[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 697ms
[INFO] Succeeded after 1.0s with 0 outputs (0 actions)
[INFO] Debug service listening on ws://localhost:55096/Hc6Z4lcC6_o=`

and in the browser only white pages

**Comment by jonahwilliams** [comment]
The debug uri is printed out, the follow up issue is tracked in https://github.com/flutter/flutter/issues/41407. Closing
