### ISSUE TITLE
[in_app_purchase]: Add Amazon Support

### ISSUE THREAD

**Issue by jrmarkham** [flutter/flutter#38850]
## Proposal
Please add purchase support for android amazon apps.

**Comment by Rockvole** [comment]
https://github.com/dooboolab/flutter_inapp_purchase/blob/master/KINDLE.md

**Comment by jrmarkham** [comment]
@Rockvole That is for an older 3rd party plugin and the author stop supporting it in favor of the "official flutter version." I was using it actully and switched.

**Comment by Rockvole** [comment]
Looks like there is some activity for the next version :
https://github.com/dooboolab/flutter_inapp_purchase/pull/94

**Comment by stuartmorgan** [comment]
Closing, as wrapping third-party SDKs is out of scope for 1P plugins. This would be best implemented as a third-party plugin, potentially a federated implementation of `in_app_purchase` for API compatibility.
