### ISSUE TITLE
Look into gatherTransparentRegion as root cause for talkback issue when using a splash screen.

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#38856]
Look into gatherTransparentRegion as root cause for talkback issue when using a splash screen.

gatherTransparentRegion is defined in View.java:
https://android.googlesource.com/platform/frameworks/base/+/a175a5b/core/java/android/view/View.java?source=post_page---------------------------#13411

**Comment by GaryQian** [comment]
What is specifically wrong with talkback in splash screens? It is unclear from the info in this issue.
