### ISSUE TITLE
[web]: Need support for handling UI when browser size changes by the user..

### ISSUE THREAD

**Issue by rajujin1** [flutter/flutter#38865]
.Currently i am facing problem that scrollbar is not getting visible when the size is reduce.
So want to know how to handle the ui when the user changes the browser size.

**Comment by jld3103** [comment]
There is no scrollbar by default in flutter. You can use the [Scrollbar](https://api.flutter.dev/flutter/material/Scrollbar-class.html) widget.

**Comment by BondarenkoStas** [comment]
@rajujin1 Is it still relevant?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
