### ISSUE TITLE
flutter_gallery_ios32__transition_perf 90th_percentile_frame_build_time_millis regressed

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#38860]
It increased from 7ms to 9ms from https://github.com/flutter/flutter/commit/a11d73148c90dd2980f0ab5a2d88159269937e3a

Similar benchmarks also regressed:
- flutter_gallery__transition_perf 90th_percentile_frame_build_time_millis
- flutter_gallery_ios__transition_perf 99th_percentile_frame_build_time_millis

CC @gspencergoog

**Comment by gspencergoog** [comment]
I am suspicious of this benchmark change: Golem seems to think that this change also reduced the hello world application size by a lot (and I just can't see that being true), and improved some other things. See [here](https://golem.corp.goog/Comparison#targetA%3Dflutter-profile%3BmachineTypeA%3Dandroid-armv7%3BrevisionA%3D84463%3BpatchA%3DNone%3BtargetB%3Dflutter-profile%3BmachineTypeB%3Dandroid-armv7%3BrevisionB%3D84462%3BpatchB%3DNone).

I'm happy to revert this and see if it truly is problematic, however.

**Comment by gspencergoog** [comment]
Note that if Golem is right, this is likely to cause a 3-5% increase in hello_world size, and a 15% reduction in velocity_tracker_bench_aot_frontend (Moto G4).

**Comment by liyuqian** [comment]
Thank you Greg for the quick reaction! Can you reproduce any performance regressions (90th build time, hello_world size, etc.) locally using either Moto G4 or iPhone 6S?

**Comment by gspencergoog** [comment]
I've been trying to reproduce this on a Moto G4 and have been able to reproduce a smaller change (at least for `flutter_gallery__transition_perf`, both for the average and the 90th percentile), of about 7%.

I'm stepping through my changes to see what is causing the regression.

**Comment by liyuqian** [comment]
It's nice to hear that it can be reproduced. LGTM on the revert.

**Comment by gspencergoog** [comment]
I recommend removing the TODAY status of this issue.  Reverting the change would cause more of a regression.

**Comment by gspencergoog** [comment]
Hmm, actually I was reading the Golem results wrong (compile time will regress by 15%, not run time).  Proceeding with the revert.
