### ISSUE TITLE
macOS xcode projects will require additional inputs to correctly skip the script phase

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#38863]
Switching build modes does not re-trigger the script. I don't believe this is currently an issue because the dart build is identical for release/debug, but this needs to be fixed before I can land full release mode support.

Alternatively, I could temporarily remove the xcfilelist inputs/outputs. The flutter tool would still correctly cache artifacts, so it wouldn't be a complete loss.

**Comment by jonahwilliams** [comment]
Actually, I might just have forgotten to add a dependency on the prebuilt engine...

**Comment by jmagman** [comment]
Can the frameworks build to different directories depending on the Xcode build configuration?

Example: App framework output, embedding and linking at `macos/Flutter/${CONFIGURATION}/App.framework`.

**Comment by jmagman** [comment]
(this would be awesome on iOS too)

**Comment by jmagman** [comment]
This should handle custom build configurations, i.e. "App Store Release" (with spaces!) directory gets created and the release bits get generated and copied there.  New build configs should gracefully get added.

**Comment by jonahwilliams** [comment]
The way I've handled this for the build caching is by hashing all configuration to generate a unique build directory. I originally tried to update the macOS project to use whatever the last build directory but that a) requires a ton of coordination between xcode & flutter due to the re-entrant calls and b) doesn't work when you update the configuration from xcode.

One issue with specifying these output paths ahead of time is that the set of possible configurations is quite large due to the ability to specify an arbitrary entrypoint file.

I'd be interested in trying to find an xcode-idiomatic way to express these inputs/dependencies. But at the very least, we do have caching at the flutter tool level of the dill/assembly artifacts.
