### ISSUE TITLE
Flutter app push notification callback issue (flutter app 推送通知回调问题)

### ISSUE THREAD

**Issue by Echo-Joker** [flutter/flutter#38871]
app适配 ios9以上
推送通知到了来的时候没有调用
- (void)application:(UIApplication *)application
didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler

反而是调用了
- (void)application:(UIApplication *)application
didReceiveRemoteNotification:(NSDictionary *)userInfo

不继承FlutterAppDelegate就是正常的
Flutter 版本
Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (5 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0

**Comment by jmagman** [comment]
Translation:
App adapter ios9 or higher
Push notifications are not called when they arrive.

(void)application:(UIApplication *)application
didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler

Instead, it is called:

(void)application:(UIApplication *)application
didReceiveRemoteNotification:(NSDictionary *)userInfo

Not inheriting the FlutterAppDelegate is normal

**Comment by iapicca** [comment]
Hi @Echo-Joker 
if the issue persist with the latest stable version of flutter
could you please provide your updated `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @Echo-Joker 
if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
