### ISSUE TITLE
Homebrew's  "findutils" causes "find: invalid mode '+100'"

### ISSUE THREAD

**Issue by rowild** [flutter/flutter#38878]
On a Mac with Homebrew and its formular "findutils" installed, things like "flutter channel master", "flutter update" etc result in a "find: invalid mode '+100'" error message.

## Steps to Reproduce

1. On a Mac, install Homebrew
2. install the findutils formula
3. run "flutter channel master" (e.g. to test the new desktop features)

Flutter attempts to download, but results in a "find: invalid mode '+100'".
So do any other command followed after that, like "flutter doctor" etc.

At "Homebrew" people say "it is not a homebrew issue, but an issue with flutter" ...

**Comment by stuartmorgan** [comment]
What does `which find` return?

**Comment by rowild** [comment]
@stuartmorgan Currently, after having findutils uninstalled, `which find` returns `/usr/bin/find`.

When reinstalling findutils and adding `gnubin` to the path, it returns the path to the brew formular, of course. With this version, flutter commands like "channel master", "doctor", "upgrade" etc throw errors.
Removing 'gnubin' from the path resolves the problem.

I don't know, if this should be respected by flutter (it would make sence, since homebrew brings in "missing" Linux tools and functionalities, IMO, but it could soon turn into an endless cycle respecting all brew formulas... and then there is MacPorts, to...)

Thanks for the feedback!

**Comment by stuartmorgan** [comment]
Theoretically we could hard-code the path to `find` on macOS. To some extent that kind of thing is an endless game of whack-a-mole though; `flutter` uses many utilities, and trying to work around the possibility of any of them being replaced by an incompatible version would get messy very quickly.

> and adding `gnubin` to the path

It sounds like a local solution that would not require you to uninstall findutils would be to just not add that to the path, and make an alias with some other name that runs the GNU version.

**Comment by rowild** [comment]
@stuartmorgan Exactly. I agree that this would soon get out-of-hand.

I would suggest: Let's leave this issue for people who search for "find -100" (I adjusted the issue's header), but close it without any further action. Agreed?

**Comment by stuartmorgan** [comment]
Closing per above.
