### ISSUE TITLE
implementing auto-fill from app to browsers

### ISSUE THREAD

**Issue by Mario2334** [flutter/flutter#38877]
I have an app which is concept stage. I need to figure out how we can implement third party browser actions using flutter app (like auto-fill authentication credentials stored in app , some click commands)

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow (you will find help there faster), since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
