### ISSUE TITLE
TextStyle.body2 lines are too close together

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#3887]
I stacked several lines together using a Column that were created with

```
new Text('abcdef', style: textTheme.body2);
```

This code worked well until https://github.com/flutter/flutter/pull/3008 was landed. Now the lines are too close together. An alternative solution needs to be found that will correctly adjust the line spacing. 
### flutter doctor

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /media/jimbe/mojossd/sysui/src/third_party/flutter
    • Framework revision 76b04cddde (9 days ago), engine revision d85ead8ec2

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/home/jimbe/Android/Sdk
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-119990345-117822431)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

**Comment by abarth** [comment]
Can you describe the effect you're trying to produce?

**Comment by HansMuller** [comment]
I would think that if you wanted a block of text you'd using a single Text object (not a Column of them) and either include line breaks or let the Text object break the lines.

If you want the lines centered you can use the Text textAlign parameter which moved from TextStyle to the Text widget pretty recently.

**Comment by abarth** [comment]
Depending on the effect, a single Text widget probably makes sense.  My question is more about what sort of line spacing @jimbeveridge is looking for.  The examples of line spacing in the spec are different from what I've seen in real-world apps, which is why I'm curious what space Jim's looking for in his app.

**Comment by Hixie** [comment]
@jimbeveridge I'm closing this since you never responded to Adam's question about what exactly you wanted, but please don't hesitate to reopen if it's still an issue.
