### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

### ISSUE THREAD

**Issue by yqjroy** [flutter/flutter#38873]
## Steps to Reproduce

1. When I press the button on my flutter page, it will transit to the Android native WebViewActivity which is declared as my plugin in the android module.
2. But the screen come into black.
3. Meanwhile, the verbose prints out the crash information.

My MainActivity code as below:
`public class MainActivity extends FlutterActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
    registerCustomPlugin();
  }

  private void registerCustomPlugin() {
JumpToNativePage2NPlugin.registerWith(this.registrarFor(JumpToNativePage2NPlugin.CHANNEL));
  }
}`

The plugin code:
`public class JumpToNativePage2NPlugin implements MethodChannel.MethodCallHandler {

    public static String CHANNEL = "com.bozhong.jump_2_native/plugin";

    static MethodChannel channel;

    private Activity activity;

    private JumpToNativePage2NPlugin(Activity activity) {
        this.activity = activity;
    }

    public static void registerWith(PluginRegistry.Registrar registrar) {
        channel = new MethodChannel(registrar.messenger(), CHANNEL);
        JumpToNativePage2NPlugin instance = new JumpToNativePage2NPlugin(registrar.activity());
       
        channel.setMethodCallHandler(instance);
    }

    @Override
    public void onMethodCall(MethodCall call, MethodChannel.Result result) {
        if (call.method.equals("permission")) {
            Intent intent = new Intent(activity, PermissionRequestActivity.class);
            activity.startActivity(intent);
            result.success("success");
        } else if (call.method.equals("web_view")) {
            String webUrl = call.argument("url");
            String title = call.argument("title");
            Intent intent = new Intent(activity, WebViewActivity.class);
            intent.putExtra("url", webUrl);
            intent.putExtra("title", title);
            activity.startActivity(intent);
            Map map = new HashMap();
            map.put("1", 1);
            map.put(2, "2");
            result.success(map);
        } else {
            result.notImplemented();
        }
    }

}
`
I have seen many people reported the same issue on StackOverflow, but none can solve it.
Is it a bug in current version of flutter?

## Logs

2019-08-20 12:05:57.062 22755-22774/com.bozhong.hssm I/flutter: AppLifecycleState.inactive
2019-08-20 12:05:57.062 22755-22774/com.bozhong.hssm I/flutter: AppLifecycleState.inactive
2019-08-20 12:05:57.092 22755-22819/com.bozhong.hssm W/cr_ChildProcLH: Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
2019-08-20 12:05:57.100 22755-22755/com.bozhong.hssm D/EGL_emulation: eglCreateContext: 0x85b34940: maj 3 min 0 rcv 3
2019-08-20 12:05:57.103 22755-27682/com.bozhong.hssm D/EGL_emulation: eglMakeCurrent: 0x85b34940: ver 3 0 (tinfo 0x900f3bb0)
2019-08-20 12:05:57.239 22755-27681/com.bozhong.hssm D/EGL_emulation: eglCreateContext: 0x85a5c6c0: maj 3 min 0 rcv 3
2019-08-20 12:05:57.253 22755-27681/com.bozhong.hssm D/EGL_emulation: eglMakeCurrent: 0x85a5c6c0: ver 3 0 (tinfo 0x7f79d390)
2019-08-20 12:05:57.498 22755-22790/com.bozhong.hssm D/EGL_emulation: eglMakeCurrent: 0xa6d87b60: ver 3 0 (tinfo 0x91b51f90)
2019-08-20 12:05:57.613 22755-27680/com.bozhong.hssm E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
    <asynchronous suspension>
    #1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:344:48)
    <asynchronous suspension>
    #2      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:158:25)
    <asynchronous suspension>
    #3      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:25:17)
    <asynchronous suspension>
    #4      Application.initSp (package:hssm/utils/application.dart:35:49)
    <asynchronous suspension>
    #5      main (package:hssm/main.dart:21:21)
    <asynchronous suspension>
    #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:216:25)
    #7      _rootRun (dart:async/zone.dart:1124:13)
    #8      _CustomZone.run (dart:async/zone.dart:1021:19)
    #9      _runZoned (dart:async/zone.dart:1516:10)
    #10     runZoned (dart:async/zone.dart:1500:12)
    #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:208:5)
    #12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
    #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
2019-08-20 12:05:57.619 22755-22865/com.bozhong.hssm D/EGL_emulation: eglCreateContext: 0x85b32ea0: maj 3 min 0 rcv 3
2019-08-20 12:05:57.620 22755-22865/com.bozhong.hssm D/EGL_emulation: eglMakeCurrent: 0x85b32ea0: ver 3 0 (tinfo 0x79bfc000)
2019-08-20 12:05:57.929 22755-22774/com.bozhong.hssm I/flutter: AppLifecycleState.paused
2019-08-20 12:05:57.929 22755-22774/com.bozhong.hssm I/flutter: AppLifecycleState.paused

 flutter doctor -v
[✓] Flutter (Channel beta, v1.8.3, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.8.3 at /Users/roy/flutter
    • Framework revision e4ebcdf6f4 (3 weeks ago), 2019-07-27 11:48:24 -0700
    • Engine revision 38ac5f30a7
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 0ca1582afd)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/roy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code (version 1.36.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.

**Comment by BugsBunnyBR** [comment]
The log talks about a `shared_preferences` call. Check your code and project setup.

> 
```
SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:158:25)

#3 SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:25:17)

#4 Application.initSp (package:hssm/utils/application.dart:35:49)

#5 main (package:hssm/main.dart:21:21)
```

**Comment by yqjroy** [comment]
> The log talks about a `shared_preferences` call. Check your code and project setup.
> 
> > 
> 
> ```
> SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:158:25)
> 
> #3 SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:25:17)
> 
> #4 Application.initSp (package:hssm/utils/application.dart:35:49)
> 
> #5 main (package:hssm/main.dart:21:21)
> ```

This is why I am really confused. If I don't call the JumpToNativePlugin, the crash of shared_preferences will never happen. 
Here is my init sp code in main.dart:
`void main() async {
  **await Application.initSp();**
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);
  runApp(MyApp());
}`

And here is the concrete initial code:
`    static SharedPreferences sharedPreferences;
static Future initSp() async {
    sharedPreferences = await SharedPreferences.getInstance();
  }`

And the plugin callback:
`var account = AccountCacheUtil.getAccount();
                        var params = {
                          'title': '${detail.patientName}',
                          'url': Uri.encodeFull(Config.CHAT_URL + 'appointId=${detail.id}&patientId=patientId_${detail.patientAccountId}'
                              '&patientName=${detail.patientAccountName}&nurseId=nurseId_${account.id}'
                              '&nurseName=${account.name}&useType=2&chatMode=1&Access-Token=${tokenEntity.userToken}'),
                        };
                        **MethodChannel('com.bozhong.jump_2_native/plugin').invokeMapMethod(
                            'web_view', params); // If I replace this line with others, everything will be ok. **`

**Comment by BugsBunnyBR** [comment]
In the Android part your MethodChannel is named `com.roy.jump_2_native/plugin`... in the Dart part `com.bozhong.jump_2_native/plugin`.. they should have the same name, right?

**Comment by yqjroy** [comment]
> In the Android part your MethodChannel is named `com.roy.jump_2_native/plugin`... in the Dart part `com.bozhong.jump_2_native/plugin`.. they should have the same name, right?

Sorry, a clerical error here in the issue description. But it is right in my project code. They are both named 'com.bozhong.jump_2_native/plugin'.

**Comment by BugsBunnyBR** [comment]
so the MethodChannel was correct in the Android side?
Anyway, Have you verified the existence of new versions of the plugin? Try to run
`flutter pub upgrade` in your project.

**Comment by yqjroy** [comment]
I delete some lines (PS: These lines of code work well in my other Android Project) in the Android activity. This crash problem never occurs. But the red-crash information still exists in the logcat console. Once I call the plugin, I will get the red message.
`SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:158:25)

#3 SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:25:17)

#4 Application.initSp (package:hssm/utils/application.dart:35:49)

#5 main (package:hssm/main.dart:21:21)`

**Comment by yqjroy** [comment]
> so the MethodChannel was correct in the Android side?
> Anyway, Have you verified the existence of new versions of the plugin? Try to run
> `flutter pub upgrade` in your project.

And I have another way leading to the same app crash result. The app may crash four in five times.
I call myself plugin in the initState method as below:
`@override
  void initState() {
    timer = Timer(Duration(seconds: 2), () {
      Channels.CHANNEL_TO_NATIVE.invokeMethod(Channels.METHOD_PERMISSION_OF_CHANNEL_TO_NATIVE_CHANNEL);
    });
  }`

**Comment by mjaakkol** [comment]
Happy to see that you found a solution for this but I don't think this is the way folks who developed shared_preferences intended things to work. I'm facing the same issue and very reluctant to add undocumented workarounds like this into my code. Does anybody have a clue what's the scalable version to address the situation.

**Comment by yashj-occipitaltech** [comment]
Does anybody have any solution for this error ? I have been facing this issue for days now

**Comment by tolstenko** [comment]
Me too @yashj-occipitaltech 
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

**Comment by mbeloded** [comment]
@tolstenko I faced with the same issue, looking forward for the solution

**Comment by gzlock** [comment]
#29356 
I solved this issue in my project.
@mbeloded @tolstenko @yashj-occipitaltech

**Comment by tony123S** [comment]
Been stucked for three days !

**Comment by msbjhandeer** [comment]
Issue was coming in emulator, since i used sharedpreference in last project as well. So i have changed emulator and it works great now.

**Comment by palexs** [comment]
In our app we use `shared_preferences` and started getting this issue. Upgrading the lib to the latest version (as of the time of writing - 0.5.7) has helped.

**Comment by bdlukaa** [comment]
The issue goes away when I stop the app and run it again. I think it has to build again to the channel works. It's actually boring we can't create/use new channels while the app is running.
It also happens with other packages, not only shared preferences.

**Comment by saranyalekshmanan** [comment]
https://stackoverflow.com/questions/54523760/flutter-sharedpreference-do-not-persist/63595310#63595310. Please check my answer (Saranya Subramanian)

**Comment by fayaz07** [comment]
I wonder why this issue marked as closed without prior solution

**Comment by saranyalekshmanan** [comment]
> I wonder why this issue marked as closed without prior solution

try with above mentioned solution , it worked for me

**Comment by deepak786** [comment]
I also faced the same issue in the release build.
I tried several solutions:
1. switching the flutter channel
2. tried several versions of shared_preferences
3. deleting the .pub-cache folder as described here https://github.com/flutter/flutter/issues/38873#issuecomment-680788165

but nothing worked.
The app worked fine in the debug build but not in the release build.

Then I tried 
`flutter build apk --no-shrink`
`flutter build appbundle --no-shrink`

and the app worked fine in the release build as well. **But the issue is resolved without shrinking the code.**
So this needs to be fixed. 

**Hopefully, the Flutter team will look into the issue and will resolve that.**

**Comment by bhanuka96** [comment]
no solutions, but bug closed 😂

**Comment by deepak786** [comment]
@bhanuka96 follow a similar issue https://github.com/flutter/flutter/issues/65334 for update.

**Comment by Fatimamostafa** [comment]
Fixed it by adding the below code to `AndroidManifest.xml`

`     <meta-data
            android:name="flutterEmbedding"
            android:value="1" />`

And below code inside `MainActvity.kt`

`class MainActivity : FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(this)
    }
}
`

**Comment by NerdFaisal404** [comment]
> Fixed it by adding the below code to `AndroidManifest.xml`
> 
> ```
>    <meta-data
>            android:name="flutterEmbedding"
>            android:value="1" />
> ```
> 
> And below code inside `MainActvity.kt`
> 
> ```
> class MainActivity : FlutterActivity() {
>     override fun onCreate(savedInstanceState: Bundle?) {
>         super.onCreate(savedInstanceState)
>         GeneratedPluginRegistrant.registerWith(this)
>     }
> }
> ```

Thanks

**Comment by n00bsys0p** [comment]
After struggling with this issue in our team for quite a while, it turned out that it was caused by Flutter itself silently ignoring that the plugin setup process in `android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java` had stopped due to the `flutter_facebook_auth` package not being set up correctly for Android.

While this was driven by user error, the fact that Flutter silently handled this error without providing any useful feedback, I see this as firmly being an important improvement for Flutter. Many people have come across this issue, and almost none have actually figured out the root cause - just applied a hack on top to work around the symptom - and in many cases these weren't even actually effective to resolve the issue, and just silenced the error message

As this situation requires fairly strict circumstances to replicate, here is a repository that I have created that experiences this issue: https://github.com/n00bsys0p/flutter-plugin-registration-error

If you do `flutter run` with an Android device, the error will consistently occur. Hopefully this will help the Flutter dev team to improve the quality of the messaging on this error - as we wasted quite some time figuring out what was wrong.

**Comment by psvm** [comment]
@n00bsys0p  Thank you very much for solving this problem. I faced the same thing. I spent several days trying to find the reason. In my case, the reason was in the keyboard_visibility plugin. Removing this plugin solved the problem

**Comment by nhingo-312** [comment]
I've got the same issue without any error and I think deleting pub-cache and modified the version in pubspec.yaml mentioned in here, 38873#issuecomment-687762478, did work for me!

**Comment by iqbalabdurrazaq** [comment]
> > Fixed it by adding the below code to `AndroidManifest.xml`
> > ```
> >    <meta-data
> >            android:name="flutterEmbedding"
> >            android:value="1" />
> > ```
> > 
> > 
> > And below code inside `MainActvity.kt`
> > ```
> > class MainActivity : FlutterActivity() {
> >     override fun onCreate(savedInstanceState: Bundle?) {
> >         super.onCreate(savedInstanceState)
> >         GeneratedPluginRegistrant.registerWith(this)
> >     }
> > }
> > ```
> 
> Thanks

in my case, i solved, change mainactivity.kt like this.

`import androidx.annotation.NonNull
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
   override fun configureFlutterEngine(@NonNull flutterEngine: 
     FlutterEngine) {
     GeneratedPluginRegistrant.registerWith(flutterEngine)
   }
}
`

**Comment by snaphers** [comment]
> no solutions, but bug closed 😂

how did you fix this?

**Comment by hoc081098** [comment]
## Step 1: Update `buildTypes` in `/android/app/build.gradle`
```gradle

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
       ...
    }

    signingConfigs {
        release {
            ...
        }
    }

    buildTypes {
        debug {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            // signingConfig signingConfigs.debug

            signingConfig signingConfigs.release

            minifyEnabled false
            shrinkResources false

            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
```

## Step 2: Add file `android/app/proguard-rules.pro`:
```pro
-keep class androidx.lifecycle.DefaultLifecycleObserver
```

## Step 3: Update `MainActivity`

```kotlin

import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
  override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine) // add this line
  }
}

```
