### ISSUE TITLE
SchedulerBinding.addFrameCallback's rescheduling parameter's description doesn't make sense to me.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#3888]
```
  /// If `rescheduling` is true, the call must be in the context of a
  /// frame callback, and for debugging purposes the stack trace
  /// stored for this callback will be the same stack trace as for the
  /// current callback.
```

If rescheduling is not true then what context would it be in?  I'd expect a FrameCallback to be called from within  a frame callback's context as its a FrameCallback... right?  It's the name of the thing!

I could be especially dense and only spent a minute thinking about it but I don't get it.

**Comment by Hixie** [comment]
Yeah that description is pathetic. My bad.
