### ISSUE TITLE
image_picker resizes image from camera on iOS without keeping aspect ratio 

### ISSUE THREAD

**Issue by mponkin** [flutter/flutter#38882]
## Steps to Reproduce
image_picker version 0.6.1+3   
Issue is not reproduced on android or gallery images

1. request image picker to get image from camera on ios device with both maxWidth and maxHeight set
2. observe resulting image: it will be scaled without keeping aspect ratio.  

you can find minimal app [here](https://gist.github.com/mponkin/2f3ce0cb93467b4af97d4b460b3aa306)  

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Users/mikhail.ponkin/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5549111/Android Studio 3.5 Preview.app/Contents
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.37.0)
[✓] Connected device (1 available)
```

**Comment by Xgamefactory** [comment]
i have same issue with lates version 0.6.1+4

**Comment by Xgamefactory** [comment]
does developer consider fix this issue ?

**Comment by bogdannedelcu** [comment]
any updates on this?

**Comment by sivanookalatt** [comment]
Can you please help? Thanks a lot.

**Comment by bogdannedelcu** [comment]
We just check for iOS and rotate the image. Seems to work. A fix however is necessary. Thanks

**Comment by agarzas** [comment]
I´m experiencia the same issue on ^0.6.1+8 version

**Comment by LSmint** [comment]
any update?

**Comment by sivanookalatt** [comment]
Please help.

**Comment by NoizyCr1cket** [comment]
I don't have a physical iOS device to test with, but does version [0.6.1+10](https://pub.dev/packages/image_picker#06110) solve this issue? The release notes lead me to believe it might.

**Comment by ksilz** [comment]
@NoizyCr1cket:  I encountered this bug as "squished images" in my Flutter app in August/September last year, too. It's gone with `image_picker` 0.6.3 on my iPhone XS Max with iOS 13.3.

**Comment by NoizyCr1cket** [comment]
> @NoizyCr1cket, @sivanookalatt: I encountered this bug as "squished images" in my Flutter app in August/September last year, too. It's gone with `image_picker` 0.6.3 on my iPhone XS Max with iOS 13.3.

That's great to know! Thank you for the confirmation.

**Comment by charafau** [comment]
Just checked with newest version of the plugin `^0.6.3+1` and it's indeed fixed. Can someone close the issue? @zoechi

**Comment by mponkin** [comment]
I can confirm it's working with 0.6.3
