### ISSUE TITLE
A few things I found in the Android Engine code

### ISSUE THREAD

**Issue by BugsBunnyBR** [flutter/flutter#38891]
What's up doc?
 I was able to take a look at the android shell using Android Studio and it pointed some warnings to me that I thought that made sense.

1) In `FlutterActivity.java` and `FlutterActivityDelegate.java`, `GET_ACTIVITIES` is used as part of flags for reading METADA, but AS says it is being miss used. (screenshot attached).
As far as I can tel, the `GET_ACTIVITIES` is not needed.

2) At `PlatformPlugin.java` there is a switch statement with this code..

``` java
            case HEAVY_IMPACT:
                // HapticFeedbackConstants.CONTEXT_CLICK from API level 23.
                view.performHapticFeedback(6);
                break;
            case SELECTION_CLICK:
                view.performHapticFeedback(HapticFeedbackConstants.CLOCK_TICK);
                break;
```
I understood the magic number 6 being used to replace the constant `HapticFeedbackConstants.CONTEXT_CLICK` that only exist in API +23, but 
`HapticFeedbackConstants.CLOCK_TICK` is API +21, shouldn't this have the same handling? I.e., using the literal instead of the constant.

3) also in `PlatformPlugin.java` there is this block
```java
        if (overlaysToShow.size() == 0) {
            enabledOverlays |= View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY;
        }
```
that is not SDK_INT checked, with `SYSTEM_UI_FLAG_IMMERSIVE_STICKY` being is API +19, this would result a crash for older phones, right?

4) In `FlutterActivityAndFragmentDelegate .java` there is this code
```java
 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
     flutterSplashView.setId(View.generateViewId());
  } else {
    // TODO(mattcarroll): Find a better solution to this ID. This is a random, static ID.
    // It might conflict with other Views, and it means that only a single FlutterSplashView
    // can exist in a View hierarchy at one time.
    flutterSplashView.setId(486947586);
  }
```
The TODO can be removed be doing
    `flutterSplashView.setId(ViewCompat.generateViewId());`

cc: @matthew-carroll 

<img width="1280" alt="Captura de Tela 2019-08-20 às 06 03 44" src="https://user-images.githubusercontent.com/70573/63356268-dece6380-c33d-11e9-8b42-71b29676f991.png">

**Comment by matthew-carroll** [comment]
@BugsBunnyBR thanks for looking through the code. I'll add this ticket to the embedding refactor project and take a look at each issue you mentioned as soon as I have time.

**Comment by matthew-carroll** [comment]
Hi @BugsBunnyBR I'm finally getting around to reviewing this. Here is what I'm seeing.

1. GET_ACTIVITIES issue

In my Android Studio I'm not seeing any warning about `GET_ACTIVITIES`. Also, the docs say:

```java
    /**
     * {@link PackageInfo} flag: return information about
     * activities in the package in {@link PackageInfo#activities}.
     */
    public static final int GET_ACTIVITIES              = 0x00000001;
```

So I do think we want `GET_ACTIVITIES` so that we limit the meta-data search to `Activity`s. Does that sound right?

2. Haptic values and API versions

I'm going to make 2 changes to this. First, I'm going to add if-statements around the haptic invocations so that we don't pass values to older Android versions that won't understand them. Second, I'm going to change the magic number of the real declaration - the reason we used a magic number wasn't actually about backwards compatibility, I think it was for forwards compatibility back when Flutter was building against old Android versions.

3. SYSTEM_UI_FLAG_IMMERSIVE_STICKY API version

I'm not sure if passing a newer value would crash or just be ignored, but I'll add an API guard in the if-statement.

4. Use ViewCompat for generating an ID

Unfortunately, I don't think we can use anything in `ViewCompat` because we need to minimize all possible library dependencies for binary size and future compatibility purposes.

**Comment by BugsBunnyBR** [comment]
#### About GET_ACTIVITIES
When I create a project **MyApplication** inside **/git/engine/shell/platform/**
and a sync link to **android/io**
``` shell
cd ~/git/engine/shell/platform/MyApplication/app/src/main/java
ln -s ../../../../../android/io
```
and open **MyApplication** in Android Studio it does show the warning to my, the engine code does not compile due the missing dependencies, but it still shows the warning. (I am using the newest version of Android Studio 3.5.2)

When I look at other libraries for android, like [facebook sdk](https://github.com/facebook/facebook-android-sdk/blob/master/facebook-applinks/src/main/java/com/facebook/applinks/AppLinks.java#L55), 
 and [MixPanel](https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/MPConfig.java#L502) there is no GET_ACTIVITIES flag there, so I guess it could be removed as suggested by the IDE if there is not side effect to what it is supposed to be doing.

#### About ViewCompat.

Even though you may wish to minimize the number of dependencies, there is something to take in consideration, that is, the value you get when using that given library. The engine code can become easier to read and keep by avoiding a number of version checks (`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT)`) and the lib offers options some things that are not available in a given platform version (`ViewCompat.generateViewId()`). The engine depends of android_support_compat and other android support libraries and View compat is part of the set of libraries provided in the set of "support libraries"  and any "future compatibility issue" will be reduced because it is a COMPAT library as because wraps the diffs for you when possible.

**Comment by matthew-carroll** [comment]
The `GET_ACTIVITIES` flag has been removed: https://github.com/flutter/engine/pull/13932

WRT to ViewCompat, the Flutter team has had many discussions around dependencies. It would be great from a development standpoint to depend on various libraries. Unfortunately, managing the implications of those dependencies in terms of version resolution is intractable at this point in time. Perhaps at some point versioning will be at a place where Flutter can reasonably depend upon Android libraries, but for the foreseeable future the only such libraries are Fragment, for add-to-app, and Lifecycle, for plugins.

**Comment by xster** [comment]
Closing this for now. We can't bring on additional transitive dependencies on the engine at the time.
