### ISSUE TITLE
Decide what "ephemeral routes" are.

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#389]
We should list the use cases, then determine how to address each one.

**Comment by Hixie** [comment]
Right now they are used by:
* popup menus
* dropdown menus
* snack bars
* modal bottom sheets
* non-modal bottom sheets

They are not used by the following, but maybe should be:
* drawers
* drag-and-drop

These fall into the following categories.

#### Modality.

* _modal_. you cannot interact with the routes below them while they are up. **popup menus, dropdown menus, modal bottom sheets, drawers.**

* _non-modal_. you can interact with other stuff while they are up. **snack bars, non-modal bottom sheets, drag-and-drop.**

#### Pop behaviour.

* _autopop on all push_. when any new route is pushed, these must be popped. **popup menus, dropdown menus, modal bottom sheets, drawers.**

* _autopop on page push_. when a new page route is pushed, these must be popped, but they can remain while other things are pushed on top. **snack bars.**

* _tied to parent lifetime_. these don't go away until they are popped explicitly or their parent route is popped. **non-modal bottom sheets.**

* _long-lived_. these don't go away until they are popped explicitly, they can even survive their parent being popped unless that explicitly pops them. **drag-and-drop.**

**Comment by Hixie** [comment]
modal + autopop on all push is common to: popup menus, dropdown menus, modal bottom sheets, drawers.

**Comment by Hixie** [comment]
Conclusions:
* drag-and-drop has no place in this conversation.
* non-modal bottom sheets should just use StateRoutes. #431
* snack bars are a feature of a Scaffold. They should not time out while another route (e.g. a dialog) is over them, they should reset their timeout when their parent route resumes being the current route, they should be displayed consecutively in time, etc. They probably shouldn't use routes at all. #432

Right now, we handle the drawer as a regular modal route and manually pop it when pushing another route on top. This seems reasonable for now, though we may wish to revisit it if it becomes too painful.

This leaves one group: popup menus, dropdown menus, and modal bottom sheets, which are all auto-popping-on-any-push modal routes. There's only ever one of these at a time.

I think the way to handle these is just to use regular routes, and when a new route is pushed on top, tell them, and have them automatically pop themselves off then.

**Comment by abarth** [comment]
Seems reasonable.

**Comment by HansMuller** [comment]
A modal bottom sheet might have a menu, but we wouldn't want to dismiss the bottom sheet when its menu is shown. 

Similarly a modal bottom sheet might pop up a dialog and not expect to be dismissed first.

**Comment by HansMuller** [comment]
So modal bottom sheets and popup menus would be WidgetRoutes and pushing a modal PageRoute would dismiss (pop) the WidgetRoutes?  This seems right to me. I'm not sure if it's necessary to encode the "dismiss me if I'm obscured by a page route" feature with a type, maybe it's just a Route flag?

**Comment by Hixie** [comment]
I'm wary of making Routes have too many flags, but yeah, maybe. It's certainly hard to encode all the different axes in a class hierarchy.

**Comment by Hixie** [comment]
So I implemented this, but I'm not at all convinced it's the way to go. I think it's actually fine for us to say "if you push a page route, you have to have popped your popup routes".

So unless someone objects, I'm going to just assert that you have.
