### ISSUE TITLE
KeySet.hashCode depends on ordering of keys provided to constructor

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#38919]
Simple example:
```dart
final a = LogicalKeySet(LogicalKeyboardKey.shiftLeft, LogicalKeyboardKey.arrowRight);
final b = LogicalKeySet(LogicalKeyboardKey.arrowRight, LogicalKeyboardKey.shiftLeft);
print(a == b); // true 
print(a.hashCode == b.hashCode); // false 
```

It appears that the Set literal's iteration order is influenced by insertion order. See use of `hashList` in `KeySet.hashCode`.

cc @gspencergoog

**Comment by shyndman** [comment]
Oh, slightly more info as to why this matters.

The `ShortcutManager` performs a hash lookup of the currently pressed keys to determine whether there's a matching intent. With the hash mismatch, the intent is sometimes not found.

**Comment by gspencergoog** [comment]
Oh, my.  OK, we'll have to do something to fix that (probably sort them when inserting, or just use a different data structure).

**Comment by jonahwilliams** [comment]
By default the Set and Map types or via literals in dart preserve insertion order. To get an unordered set you'd have to explicitly use HashSet or HashMap

**Comment by gspencergoog** [comment]
Well, but would iteration order matter in a hash set?  Or, even better, does `hashCode` on a `HashSet` provide a hash of the contents?

**Comment by jonahwilliams** [comment]
Iteration order is the preserved insertion order for LinkedHashSet and LinkedHashMap (the defaults). Map/Sets in general are mutable and don't have a meaningful hashCode.

**Comment by shyndman** [comment]
One thought is to use a `TreeSet` sorted on `keyId`? That would make iteration order consistent, and therefore the value produced by `hashList`

**Comment by jonahwilliams** [comment]
Do the key sets always contain 4 keys?

**Comment by shyndman** [comment]
No, at most 4 in the default constructor, but there's a `fromSet` constructor for arbitrary length.

**Comment by gspencergoog** [comment]
I have a PR that fixes this.  `HashSet` is sufficient, since the iteration seems to depend on the hash value of the elements.

**Comment by gspencergoog** [comment]
From the docs for `HashSet`:

"The iteration order of the set is not specified and depends on the hashcodes of the provided elements. However, the order is stable: multiple iterations over the same set produce the same order, as long as the set is not modified."

This is perfect for this use case.

**Comment by shyndman** [comment]
What would happen if two hash codes collide? It may depend on the implementation of the map. I'm going to throw together a dartpad and see if I can break it.

**Comment by jonahwilliams** [comment]
FWIW SplayTreeSet is as slow as molasses

**Comment by shyndman** [comment]
OK, it's a contrived example, but demonstrative. Using a `HashSet`, I forced a hash collision by having two elements return the same `hashCode`. In this case, iteration order reflects insertion order.

It's difficult to say how this might happen in a real-world scenario, but it's entirely possible since it's presumably based on the number of buckets the `HashSet` uses.

**Comment by shyndman** [comment]
> FWIW SplayTreeSet is as slow as molasses

Just a suggestion. Might be useful just to get things into sorted order, and generating the hashCode up front. You can ditch it after that, since the set is immutable and the only check you need afterwards is set equality.

**Comment by shyndman** [comment]
Scratch that. After trying pretty hard to get a collision in a real-world situation, I couldn't do it. It's probably not a big deal.

**Comment by gspencergoog** [comment]
Yeah, that definitely won't happen with `LogicalKeyboardKey`s.  They use their unique `keyId` for both the `operator==` and the `hashCode`.

And if something does return false from `operator=` and produce the same `hashCode`, it is violating the contract for the `hashCode` [property](https://api.dartlang.org/stable/2.4.1/dart-core/Object/hashCode.html), which states "Hash codes must be the same for objects that are equal to each other according to operator ==. "

**Comment by shyndman** [comment]
If you read that carefully, you'll see it doesn't say that.

If they are equal, they must return the same hashCode, but it doesn't say anything about the behavior when they're unequal. That's why hash sets and maps rely on both hashCode and equality to determine membership.

Thanks for the PR though. Appreciate it.

**Comment by gspencergoog** [comment]
My apologies, you're correct.

In this case, `LogicalKeyboardKey` is always going to return a different hash code if the two keys have different `keyId`s, so it isn't a concern.
