### ISSUE TITLE
Provide a way to check if a message channel is registered, or fail if it is not.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#38914]
Ideally, there would be a way to wait for the engine to finish setting up.  E.g., the following code is racy (and consistently is a no-op for me on a simulator):

```objc
 FlutterEngine* engine = [[FlutterEngine alloc] initWithName:@"PlatformViewTest" project:nil];
    [engine runWithEntrypoint:nil];
  
    [engine.binaryMessenger sendOnChannel:@"set_scenario" message:[@"text_platform_view" dataUsingEncoding:NSUTF8StringEncoding]];
```

Adding a `sleep` makes things "work".

Ideally, this message would get delivered once the engine was ready.

/cc @jmagman @xster @chinmaygarde @gaaclarke

**Comment by jmagman** [comment]
@dnfield Sounds like you figured this out and there is already a channel message for this?

**Comment by chinmaygarde** [comment]
The race is because both Dart and native sides needs to have setup the channels before they can communicate over the same. You can setup a mechanism where one side pings the other and sets up a response handler (`sendOnChannel:message:binaryReply:` in your case). Message that are dropped on the floor because the other side is not setup yet will not get a response. Retry till you get a response.

**Comment by dnfield** [comment]
I did figure this out.  I wonder if there's a way that we could throw an error if you try to send a message to a channel that isn't registered?

**Comment by chinmaygarde** [comment]
Makes sense but that would be a significant breaking change.

**Comment by dnfield** [comment]
Perhaps it could be another overload that you opt into, e..g on iOS it'd be something like `sendOnChannel:@"set_scenario" message:foo failIfNotRegistered:YES`, and default it to NO on the existing overloads.

**Comment by xster** [comment]
I think this class of problems (confusing setInitialRoute, deep linking etc) will keep re-occurring until we solve the channel timing issue https://docs.google.com/document/d/1AKPWL50wzQFTSaEz2AbGZm5Fkm01uvunZH8AEoLJMRI (sorry, not public yet)

**Comment by gaaclarke** [comment]
If we used a ring buffer to hold messages when getting communicated from objc to dart this could work.  This would mean messages sent too early won't get dropped, just postponed (unless you overflow the buffer before the reader gets initialized).

**Pseudocode:**
-- Objc Thread --
sendMessage(data) {
  ring_buffer_.push(data);
  condition_.signal();
}

-- Dart Thread --
run() {
  while (true) {    
    while (!ring_buffer_.empty()) {
      handle(ring_buffer_.pop());
    }
    condition_.wait();
  }
}

**Comment by dnfield** [comment]
It's probably enough to just hold the last message. It would also be nice to do this in some platform agnostic way if possible, so we don't have separate implementations for Android/iOS/Fuchsia/macOs/Windows/Linux/Web ... although web might need to be separate.

**Comment by dnfield** [comment]
FWIW, this code is what I used to make things work reliably:

```objc
engine.binaryMessenger
        setMessageHandlerOnChannel:@"scenario_status"
              binaryMessageHandler:^(NSData* _Nullable message, FlutterBinaryReply _Nonnull reply) {
                [engine.binaryMessenger
                    sendOnChannel:@"set_scenario"
                          message:[@"text_platform_view" dataUsingEncoding:NSUTF8StringEncoding]];
              }];
```

And on the dart side: 

```dart
  final ByteData data = ByteData(1);
  data.setUint8(0, 1);
  window.sendPlatformMessage('scenario_status', data, null);
```

at the end of `main` (after I set up my handler for the channel).

**Comment by gaaclarke** [comment]
https://github.com/flutter/engine/blob/25ffa223b9576e8db64a6d24b164f5fb6c4e2d5c/shell/common/engine.cc#L272

I suspect this is where the messages are getting dropped.  This method silently drops messages if IsRootIsolateRunning() returns false.

**Comment by dnfield** [comment]
It's that, but it's also in lib/ui/runtime_controller.cc and lib/ui/window.cc:264.  We can drop messages if there's no window, and we can drop messages if the dart state has disappeared after that, and we can drop messages if they get to hooks.dart:152 and the message handler just hasn't finished setting up yet on the Dart side.

**Comment by gaaclarke** [comment]
This is reproducible 100% of the time with the following patch and running `testing/scenario_app/run_ios_tests.sh`
```
--- a/testing/scenario_app/ios/Scenarios/Scenarios/AppDelegate.m
+++ b/testing/scenario_app/ios/Scenarios/Scenarios/AppDelegate.m
@@ -21,17 +21,19 @@
   // under test will create platform views.
   if ([[[NSProcessInfo processInfo] arguments] containsObject:@"--platform-view"]) {
     FlutterEngine* engine = [[FlutterEngine alloc] initWithName:@"PlatformViewTest" project:nil];
+    NSLog(@"foobar run start");
     [engine runWithEntrypoint:nil];
-
+    NSLog(@"foobar run stop");
     FlutterViewController* flutterViewController =
         [[NoStatusBarFlutterViewController alloc] initWithEngine:engine nibName:nil bundle:nil];
-    [engine.binaryMessenger
-        setMessageHandlerOnChannel:@"scenario_status"
-              binaryMessageHandler:^(NSData* _Nullable message, FlutterBinaryReply _Nonnull reply) {
+//    [engine.binaryMessenger
+//        setMessageHandlerOnChannel:@"scenario_status"
+//              binaryMessageHandler:^(NSData* _Nullable message, FlutterBinaryReply _Nonnull reply) {
+                NSLog(@"foobar send message");
                 [engine.binaryMessenger
                     sendOnChannel:@"set_scenario"
                           message:[@"text_platform_view" dataUsingEncoding:NSUTF8StringEncoding]];
-              }];
+//              }];
     TextPlatformViewFactory* textPlatformViewFactory =
         [[TextPlatformViewFactory alloc] initWithMessenger:flutterViewController.binaryMessenger];
     NSObject<FlutterPluginRegistrar>* registrar =
```

**Comment by gaaclarke** [comment]
The fix Dan did to make this test pass doesn't work how we thought it did.  It makes the test pass because the initializer for the `_scenarios`[1] variable constructs a `PlatformViewScenario` which in its constructor it asynchronously sets himself up to be rendered.[2]

The question still remains, "Why isn't the set_scenario message getting delivered?"

[1]https://github.com/flutter/engine/blob/8f4a0a7c9aa041bd0fc60a7d994bd956be2f3c5c/testing/scenario_app/lib/main.dart#L18
[2]https://github.com/flutter/engine/blob/8f4a0a7c9aa041bd0fc60a7d994bd956be2f3c5c/testing/scenario_app/lib/src/platform_view.dart#L86
