### ISSUE TITLE
Allow async navigation decisions

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#38929]
Right now the [navigationDelegate](https://pub.dev/documentation/webview_flutter/latest/webview_flutter/WebView/navigationDelegate.html) is required to synchronously decided whether to allow the navigation or not.

"customer: dream" could use the ability to make the decision asynchronously.

**Comment by BugsBunnyBR** [comment]
That would be great!
Another use case would be dynamic links plugin, where you expect to get a deeplink as route, but have to have a navigation after the initial route is loaded.
example: https://github.com/flutter/plugins/blob/master/packages/firebase_dynamic_links/example/lib/main.dart#L44

**Comment by stuartmorgan** [comment]
Closing as fixed; in v4, `onNavigationRequest` can return a `Future`.
