### ISSUE TITLE
Improve fidelity of multi-pointer drag gestures

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#38926]
The current implementation of `DragGestureRecognizer` does not work well when multiple pointers (fingers) are involved.

Consider _n_ pointers in contact with the screen. At one frame pointer _i_ moved by _delta(i)_. 

**Current Flutter behavior**
- When dragging: _delta(combined)_ = sum of _delta(n)_ 
  - This is **very wrong**. When multiple pointers are moving in the same direction, the scrollable will be moved at double or triple the speed.
- When a pointer leaves: all remaining pointers still work.

After investigation, I discovered that Android and iOS have different implementation.

**Android behavior (pan)**
Android seems to maintain a stack of pointers in the order of time of first contact, latest being the stack top.
- When dragging: _delta(combined)_ = _delta(latest pointer)_
  - It means that when you're dragging with one finger, and then add another finger, the scrollable is acting as if there is only the 2nd finger.
- When a pointer leaves: the latest of the remaining pointers works. No end speed.

**Android behavior (horizontal or vertical)**
- When dragging: _position(combined)_ = _position(latest pointer)_
- When a pointer leaves: the latest of the remaining pointers works.
  - It means that the draggable will jump from the previous pointer to the next pointer.

**iOS behavior (pan)**
- When dragging: _position(combined)_ = average(i of n) _position(i)_
- When a pointer leaves: all remaining pointers still work
  - It means that the draggable will jump from the previous average position to the next average position.

**iOS behavior (horizontal or vertical)**
- When dragging: _delta(combined)_ = max(i of n that are positive) _delta(i)_ - max(i of n that are negative) _delta(i)_
  - It means that, if two fingers are moving +50 and +10 respectively, it will move +50; if they're moving at +50 and -10 respectively, it will move +40.
- When a pointer leaves: all pointers stop working (but the gesture is still in "accepted" state)

## Challenge
The iOS behavior requires the information of which events belong to the same batch, which is not provided by the current gesture API.

A possible solution is to synthesize it by record the events in a map from pointers to events. When the recognizer sees an event for a pointer that already has an event, all events currently in the map are considered a batch, and the map is cleared.

**Comment by MaxBittker** [comment]
I think this is worth a second look if there's a good self-contained fix, it's very noticeable in certain apps

**Comment by SoolyChristy** [comment]
any update?

**Comment by dkwingsmt** [comment]
Hi, this is currently not on our radar. But we'd be happy to review if you'd like to draft a fix!

**Comment by SoolyChristy** [comment]
my colleague @xiaoyanermiemie would like to draft a fix.

**Comment by xiaoyanermiemie** [comment]
> Hi, this is currently not on our radar. But we'd be happy to review if you'd like to draft a fix!

please have a review of the pr, thank you!
