### ISSUE TITLE
Local engine workflow for iOS profile/release mode is broken.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#38933]
The local engine workflow looks for `gen_snapshot_armv7` or `gen_snapshot_arm64`. This is now because the `gen_snapshot` is no longer a multi-arch lipo-ed binary.

**Comment by chinmaygarde** [comment]
cc @flar

**Comment by chinmaygarde** [comment]
Temporary workaround is to symlink `gen_snapshot_armv7` or `gen_snapshot_arm64` to `gen_snapshot` while developing locally.

**Comment by liyuqian** [comment]
Is there anyone working on this @chinmaygarde ? @LongCatIsLooong encountered this issue today again.

**Comment by chinmaygarde** [comment]
No. This has not been assigned to anyone.

**Comment by liyuqian** [comment]
What would the fix look like? Modify some BUILD.gn file to do symlink automatically?

**Comment by chinmaygarde** [comment]
> What would the fix look like?

Update the flutter tool to look for the artifact at the correct location based on target architecture.

**Comment by xster** [comment]
I don't know the background for why the split was there in the first place. Sounds like we just want to remove https://github.com/flutter/flutter/blob/369860bcf61d5516cf6e7f8bae653e05b2e5f174/packages/flutter_tools/lib/src/base/build.dart#L61

**Comment by jmagman** [comment]
Split was introduced in https://github.com/flutter/flutter/pull/37445 and https://github.com/flutter/engine/pull/10430/files#diff-171e051c99b0c510f27a1860c2d658d5R32-R33.

@jonahwilliams I see your TODO:
https://github.com/flutter/flutter/pull/49224/files#diff-04225b1c8fbe3e7386415e564500d35aR93-R99

**Comment by iskakaushik** [comment]
+1 I hit this today as well.

**Comment by chinmaygarde** [comment]
Triage: @jmagman, it seems like the current behavior is intentional as fixing this for local engine workflows would cause issues for end users because of Xcode caching certain build variable. Is that an accurate assessment of the challenges in resolving this? I am assigning a low priority for this accordingly. If you think both workflows can be adequately served, please revise the priority. Thanks.

**Comment by chinmaygarde** [comment]
For local engine developers looking for a workaround, https://github.com/flutter/flutter/issues/38933#issuecomment-523688766 is the way to go for now.

**Comment by jonahwilliams** [comment]
The local engine workflow does not represent a customer-facing regression, so I am relabeling as team/quality

**Comment by xster** [comment]
FWIW many of our customers build their own local engines too. But I don't think they're blocked either since this is a small workaround.

**Comment by Vadaski** [comment]
A easy way to solve this problem is copy gen_snapshot and rename the copy one's name to gen_snapshot_arm64.
It works for me.

**Comment by jmagman** [comment]
Hm I just hit this with a `ios_release_unopt` on engine top of tree.

```
    Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for /Users/magder/Projects/engine/src/out/ios_release_unopt/clang_x64/gen_snapshot_arm64.".
```

**Comment by AlBlanc** [comment]
I just has the same with `ios_release`
