### ISSUE TITLE
package:flutter_driver should support package:flutter_tools

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#3893]
There's a big overlap between `package:flutter_driver` and `package:flutter_tools`. Both packages control Flutter apps remotely in some way. A lot of it is the same, such as fetching timeline data.

Suggestion:
- `driver_extension.dart` moves into `package:flutter_test`
- `package:flutter_driver` stops depending on `package:flutter` and `package:flutter_test`
- `package:flutter_tools` starts depending on `package:flutter_driver`

`package:flutter_driver` will over time expand its functionality to give more power to our developers to control Flutter apps programmatically and at the same time it will provide API to `package:flutter_tools`.

/cc @Hixie @devoncarew

**Comment by devoncarew** [comment]
Have flutter_tools depend on flutter_driver makes sense to me (I'll still want to consume our own service protocol client).

**Comment by yjbanov** [comment]
> I'll still want to consume our own service protocol client

+1. We could clean this up too.

**Comment by Hixie** [comment]
We'll also want to move flutter_test and flutter_driver towards more similar APIs now that flutter_test is also async.

Please hold off on making changes like this to flutter_test for a few more days, I really want to land my thing first since it changes everything in there.

**Comment by Hixie** [comment]
(in case that wasn't clear, I'm entirely in favour of everything discussed in this issue.)

**Comment by Hixie** [comment]
I think this is done now, right?
