### ISSUE TITLE
Google Maps Flutter Crashes ios app when opening google maps

### ISSUE THREAD

**Issue by dalebulmer** [flutter/flutter#38944]
Using google_maps_flutter 0.5.20+3 displays map correctly on Android and iOS but crashes the app when tap on the marker to open location in Google Maps app.
```
Error:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'The specified URL has an unsupported scheme. Only HTTP and HTTPS URLs are supported
```

info.plist includes:
```
<key>io.flutter.embedded_views_preview</key>
	<true/>
```

Flutter doctor output:
C:\fluttersdk\flutter\bin\flutter.bat doctor --verbose
```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.295], locale en-GB)
    • Flutter version 1.7.8+hotfix.4 at C:\fluttersdk\flutter
    • Framework revision 20e59316b8 (5 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\daleb\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by KlausJokinen** [comment]
Can you please give us a minimal runnable productions in a single file.

**Comment by dalebulmer** [comment]
We are working to provide the minimal runnable. The issue has been isolated to be with the launch package rather than maps, however, it does not do it with a basic info.plist so we are trying to identify the conflict and will update the issue soon.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
