### ISSUE TITLE
Android Studio 3.5 Update Flutter & Dart Plugin

### ISSUE THREAD

**Issue by jacksonw765** [flutter/flutter#38948]
Been working on a flutter app for a few months now and haven't run into any major problems until now. Everything was working fine until I upgraded Android Studio to 3.5 and updated flutter/dart plugin. Since then I have been getting this error message and have no idea how to fix it. I would submit code samples but the app is over 40k lines and I don't even know where to begin to start diagnosing the issue. 

I/flutter (12768): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12768): The following assertion was thrown building Settings:
I/flutter (12768): The default constructor of ListenableProvider/ChangeNotifierProvider
I/flutter (12768): must create a new, unused Listenable.
I/flutter (12768): 
I/flutter (12768): If you want to reuse an existing Listenable, use the second constructor:
I/flutter (12768): 
I/flutter (12768): - DO use ChangeNotifierProvider.value to provider an existing ChangeNotifier:
I/flutter (12768): 
I/flutter (12768): MyChangeNotifier variable;
I/flutter (12768): ChangeNotifierProvider.value(
I/flutter (12768):   value: variable,
I/flutter (12768):   child: ...
I/flutter (12768): )
I/flutter (12768): 
I/flutter (12768): - DON'T reuse an existing ChangeNotifier using the default constructor.
I/flutter (12768): 
I/flutter (12768): MyChangeNotifier variable;
I/flutter (12768): ChangeNotifierProvider(
I/flutter (12768):   builder: (_) => variable,
I/flutter (12768):   child: ...
I/flutter (12768): )
I/flutter (12768): 'package:provider/src/listenable_provider.dart':
I/flutter (12768): Failed assertion: line 136 pos 14: '!listenable.hasListeners'

**flutter doctor -v**

[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18963.1000], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at C:\Users\jacks\Documents\flutter_windows_v1.7.8+hotfix.4-stable\flutter
    • Framework revision 20e59316b8 (5 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\jacks\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Users\jacks\Downloads\android-studio-ide-192.5787298-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8405
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • Pixel 3 XL                • 8APY0P1FE     • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)

**Comment by mannprerak2** [comment]
For the Provider package, there was a breaking change from v2.00 to v3.00.
See [here](https://pub.dev/packages/provider#migration-from-v200-to-v300)

Maybe reverting to your last version of the Provider package fix this.

**Comment by jacksonw765** [comment]
Thank you sir! I fixed my ListenableProviders and everything is back to working!

**Comment by jacksonw765** [comment]
I changed my ListenableProviders to the new format. 

Old: 
`ListenableProvider<ThemeModel>(builder: (_) => _model..init(),`
New: 
`ListenableProvider<ThemeModel>.value(value: _model..init(),`

For me it was this easy, you have a more complex use of the Provider class

**Comment by daqniwloe** [comment]
You look like a Expert in Flutter. Do you have a wpp for we talk more and you help me in my project in flutter ? 

> For the Provider package, there was a breaking change from v2.00 to v3.00.
> See [here](https://pub.dev/packages/provider#migration-from-v200-to-v300)
> 
> Maybe reverting to your last version of the Provider package fix this.

**Comment by mannprerak2** [comment]
@daqniwloe you can explain your issue here. So that it helps others too
