### ISSUE TITLE
AOT build on Android flashes on start

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3895]
With an AOT build on Android, I'm seeing the following sequence after tapping the icon for the app:

* draw full screen black
* then show the app launcher background
* then draw black
* then load the app

Here's a slow-mo video: https://dl.dropboxusercontent.com/u/316685/for-github-issues/IMG_0006.mp4.mp4

**Comment by eseidelGoogle** [comment]
I believe @abarth looked at this briefly last week.

**Comment by abarth** [comment]
Yeah, we wait for Dart to paint the first frame.  Instead, we should push one black frame in parallel with starting Dart.

**Comment by abarth** [comment]
I'm assigning this issue to myself to keep track of it, but feel free to steal it.  (I'll post again before starting work on it.)

**Comment by sethladd** [comment]
Related: https://github.com/flutter/flutter/issues/3447

**Comment by sethladd** [comment]
I'm closing this as a dupe of https://github.com/flutter/flutter/issues/3447
