### ISSUE TITLE
intl.dart Conflict with TextDirection

### ISSUE THREAD

**Issue by MisterioRee** [flutter/flutter#38962]
## intl.dart Conflict with TextDirection 

after importing 
 `import 'package:intl/intl.dart';`
`TextDirection.ltr`
Or
`TextDirection.ltr`

Throws compile time error

 
 
![Untitled](https://user-images.githubusercontent.com/18234947/63414908-dfcec600-c40d-11e9-8ac3-ffc2aba94223.png)

**Comment by BondarenkoStas** [comment]
@MisterioRee Is it still relevant? Please provide your ```flutter doctor -v``` output, and specify do you use the 0.16.0 intl version?

**Comment by MisterioRee** [comment]
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.295], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at C:\FlutterDev\flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\rehan\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code, 64-bit edition (version 1.37.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.3.0

[!] Connected device
    ! No devices available

**Comment by saeedjassani** [comment]
I am having the same issue. Any solutions/work around yet?

**Comment by MisterioRee** [comment]
Yeah i am using `  date_format: 1.0.6 `
