### ISSUE TITLE
Finished with error: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by wuyuancai** [flutter/flutter#38961]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  C:\Users\mi\.gradle\caches\transforms-1\files-1.1\core-1.0.2.aar\33f6b97f368ad6398dd91e0b75f1ac4a\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  C:\Users\mi\.gradle\caches\transforms-1\files-1.1\core-1.0.2.aar\33f6b97f368ad6398dd91e0b75f1ac4a\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.678], locale zh-CN)
    • Flutter version 1.7.8+hotfix.3 at C:\Program Files\flutter
    • Framework revision b712a172f9 (6 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\mi\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Users\mi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
    • All Android licenses accepted.

**Comment by Jayant11** [comment]
> https://goo.gl/CP92wY

How did you solve it?

**Comment by wuyuancai** [comment]
change compileSdkVersion 28

Jayant Dabas <notifications@github.com> 于2019年8月28日周三 下午5:01写道：
