### ISSUE TITLE
Can I use almost the same command to manipulate Flutter, such as the release command:

### ISSUE THREAD

**Issue by Juneor** [flutter/flutter#38964]
Can I use almost the same command to manipulate Flutter, such as the release command:
flutter build apk
flutter build ios
flutter build fuchsia
flutter build windows
flutter build mac
flutter build linux
flutter build web

When debugging, we can use 
flutter run --params(apk, ios, Windows, MAC, Linux, web) 
to run onto the corresponding platform

**Comment by BondarenkoStas** [comment]
@Juneor Please explain in more detailed way the changes you propose. And please, don't use emoji unless they are needed, it may mislead.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
