### ISSUE TITLE
not show AlertDialog !

### ISSUE THREAD

**Issue by 007fred50** [flutter/flutter#38968]
Hello,

How can i work with AlertDialog.?
I create a simple way to access AlertDialog.
i got error in the code below. how can i fix the issues ?

my code in dart (flutter)
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return MyAppState();
  }
}

class MyAppState extends State<MyApp> {

  createAlertDialog(BuildContext context){

    TextEditingController customController = TextEditingController();

    return showDialog(context: context, builder: (context) {
      return AlertDialog(
        title: Text("Your Name !"),
        content: TextField(
          controller: customController,
        ),
        actions: <Widget>[
          MaterialButton(
            elevation: 5.0,
            child: Text("submit"),
            onPressed: (){},
          )
        ],
      );
    });
  }


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Scaffold(
            appBar: AppBar(
              actions: <Widget>[
                Container(
                  alignment: Alignment.topRight,
                  child: IconButton(icon: Icon(Icons.settings), onPressed: () {
                    setState(() {
                      createAlertDialog(context);
                    });
                  }),
                ),
              ],
            )
        ));
  }
}
```

my error code:
I```
/flutter (15368): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (15368): The following assertion was thrown while handling a gesture:
I/flutter (15368): No MaterialLocalizations found.
I/flutter (15368): MyApp widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
I/flutter (15368): Localizations are used to generate many different messages, labels,and abbreviations which are used
I/flutter (15368): by the material library.
I/flutter (15368): To introduce a MaterialLocalizations, either use a  MaterialApp at the root of your application to
I/flutter (15368): include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
I/flutter (15368): The specific widget that could not find a MaterialLocalizations ancestor was:
I/flutter (15368):   MyApp
I/flutter (15368): The ancestors of this widget were:
I/flutter (15368):   [root]
I/flutter (15368): 
I/flutter (15368): When the exception was thrown, this was the stack:
I/flutter (15368): #0      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:125:7)
I/flutter (15368): #1      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:128:4)
I/flutter (15368): #2      showDialog (package:flutter/src/material/dialog.dart:702:10)
I/flutter (15368): #3      MyAppState.createAlertDialog (package:thrift_settings/main.dart:24:12)
I/flutter (15368): #4      MyAppState.build.<anonymous closure>.<anonymous closure> (package:thrift_settings/main.dart:57:23)
I/flutter (15368): #5      State.setState (package:flutter/src/widgets/framework.dart:1141:30)
I/flutter (15368): #6      MyAppState.build.<anonymous closure> (package:thrift_settings/main.dart:52:21)
I/flutter (15368): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
I/flutter (15368): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
I/flutter (15368): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter (15368): #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
I/flutter (15368): #11     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
I/flutter (15368): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
I/flutter (15368): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
I/flutter (15368): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
I/flutter (15368): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
I/flutter (15368): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter (15368): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (15368): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (15368): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (15368): #23     _invoke1 (dart:ui/hooks.dart:250:10)
I/flutter (15368): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
I/flutter (15368): (elided 3 frames from package dart:async)
I/flutter (15368): 
I/flutter (15368): Handler: "onTap"
I/flutter (15368): Recognizer:
I/flutter (15368):   TapGestureRecognizer#fd412
I/flutter (15368): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Thanks for helping me :)

**Comment by KirolousNashaat** [comment]
just move the 'MaterialApp' widget to  a separate widget with the container in another child widget ('home') .. don't put all your app in one widget.
btw this question should be on stackoverflow not here.

**Comment by VladyslavBondarenko** [comment]
@007fred50 
I hope you've solved the issue.
Closing.
if you disagree please write in the comments and I will reopen it
Thank you
