### ISSUE TITLE
Finish plumbing message responses through desktop method channel implementations

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#38977]
The follow-up work to https://github.com/flutter/flutter/issues/18852 missed a few spots where replies should be supported:
- For macOS, the MethodChannel version is still marked iOS-only
- For Windows/Linux, the client-wrapper is still missing a reply version at the MethodChannel level.

**Comment by a5l3** [comment]
Heya this is just a ping, 
Awesome to see the desktop api evolve. 
Found a TODO in FlutterChannels.h today, ``` // TODO: Add macOS support for replies once```
after running ```flutter create myapp```.

**Comment by stuartmorgan** [comment]
@a5l3 you are either not on master, or your version of master is very outdated; that TODO was fixed and removed several months ago in the PR above.

**Comment by a5l3** [comment]
@stuartmorgan yip, looks like I need to update, thanks.
