### ISSUE TITLE
Build plugins using Flutter assemble for Android

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#38988]
Context: https://github.com/flutter/flutter/issues/36842#issuecomment-516220880

The alternative is to build the plugins as AAR in the tool using Flutter assemble before calling Gradle. 

The downside is that folks using `include_flutter.grovy` in [add to app](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) scenarios need to run the Flutter tool before building the host app.

**Proposal to remove include_flutter.grovy:** [flutter.dev/go/remove-include-flutter-groovy](https://flutter.dev/go/remove-include-flutter-groovy).

@xster suggested that this can be addressed in a IntelliJ plugin. The plugin would provide a button that calls the Flutter tool before calling Gradle. If this is the case, let's answer:
1. How does the IntellJ plugin knows about the location of Flutter module. (This is require to build the module's plugins)
2. How does it know about flavors and custom build types?

**Comment by blasten** [comment]
cc @creativecreatorormaybenot

**Comment by creativecreatorormaybenot** [comment]
Will I have to run `flutter config --enable-build-plugin-as-aar` manually again or will you be able update that via the PR when you do manage to build during Flutter assemble?

**Comment by blasten** [comment]
yeah, the flag would need to be re-enabled manually. Once the feature is stable, then this will happen automatically even if you turned it off before.

**Comment by xster** [comment]
1) the Android project doesn't know the Flutter source location but it has to know the Flutter aar location. Can we leave a breadcrumb back from the maven repo back to the Flutter project root?

**Comment by xster** [comment]
Splitting concerns from sync meeting: from the add to app perspective, the work remaining is documenting that build aar and include_flutter.groovy works with androidx via a flag.
