### ISSUE TITLE
Provide checksums of Flutter binary artifacts

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#38980]
We should be providing checksums of our engine binaries that get uploaded to GCP, so that developers (and the Flutter tool) can verify that the binaries have been successfully downloaded and not tampered with.  Especially since the artifacts are now being mirrored (e.g. for users in China).

Somewhat related: https://github.com/flutter/flutter/issues/27574

**Comment by jonahwilliams** [comment]
This could also be used by the tool to verify that the cache contents are up to date in a safer manner than stamp files

**Comment by tvolkert** [comment]
FYI @godofredoc

**Comment by chinmaygarde** [comment]
@christopherfujino Are you planning on working on this? Can you adjust the priority accordingly? Just sweeping through P3s to make sure they are correctly prioritized.

**Comment by christopherfujino** [comment]
> @christopherfujino Are you planning on working on this? Can you adjust the priority accordingly? Just sweeping through P3s to make sure they are correctly prioritized.

Yes, assigning myself to this, and adding September milestone.

**Comment by christopherfujino** [comment]
Updating milestone to November, this slipped due to release work.

**Comment by godofredoc** [comment]
@christopherfujino is this implemented?

**Comment by godofredoc** [comment]
This will be addressed as signed provenance generation aligned with the SLSA framework. Additional work will be required in the tool to validate provenance.

**Comment by godofredoc** [comment]
Closing as obsolete. Provenance and signature validations will address this.
