### ISSUE TITLE
Problem in scoped_model in flutter web

### ISSUE THREAD

**Issue by AndAlex10** [flutter/flutter#38984]
Is scoped model in flutter web already working? I try to add the library but it does not support version 1.0.1

**Comment by yjbanov** [comment]
Can you please send the output of `flutter packages get`?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
