### ISSUE TITLE
Error: It appears that the downloaded file is corrupt

### ISSUE THREAD

**Issue by foncyc** [flutter/flutter#38995]
## Steps to Reproduce

1. ... cloned repository from within WSL Ubuntu in Windows 10,
2. ... successfully cloned
3. ... run flutter doctor and got  an error message

## Logs

flutter doctor -v
Downloading Dart SDK from Flutter engine fee001c93f25a1e7258e762781a7361f122d29f5...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  120M  100  120M    0     0  3208k      0  0:00:38  0:00:38 --:--:-- 3158k
/mnt/c/Users/foncy/flutter/bin/internal/update_dart_sdk.sh: line 82: unzip: command not found

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md
```
```

flutter doctor -v
Downloading Dart SDK from Flutter engine fee001c93f25a1e7258e762781a7361f122d29f5...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  120M  100  120M    0     0  3208k      0  0:00:38  0:00:38 --:--:-- 3158k
/mnt/c/Users/foncy/flutter/bin/internal/update_dart_sdk.sh: line 82: unzip: command not found

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md
```
```

**Comment by goderbauer** [comment]
In your logs it says "unzip: command not found". Looks like the unzip util is not available on your machine, which is a requirement for Flutter: https://flutter.dev/docs/get-started/install/linux

**Comment by foncyc** [comment]
I see, yes. I tried running the command in powershell and it worked. thanks.

**Comment by gsusI** [comment]
Inside WSL:
```bash
sudo apt install unzip
flutter doctor
`
