### ISSUE TITLE
Be careful when stopping on caught exceptions in an editor

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3899]
The framework tries to catch most exceptions and report them in detail. However, by breaking on all exceptions, Atom is stealing the framework's thunder! :-)

We probably need to coordinate better. There's some exceptions where the handler is able to give really detailed helpful messages, and there's others where it's just "uh, something bad happened".

cc @devoncarew

**Comment by sethladd** [comment]
This will probably be true in the IntelliJ plugin, too?

**Comment by mit-mit** [comment]
This issue was moved to flutter/flutter-intellij#459

**Comment by mit-mit** [comment]
Moved to IntelliJ tracker.
