### ISSUE TITLE
Images contained in a widget are not displayed on WIDGET TESTS

### ISSUE THREAD

**Issue by snickersv2** [flutter/flutter#38997]
## Steps to Reproduce

1. We have screens/widgets that load some assets like:
Image.asset(
'lib/assets/icons/icon_image.png',
)
2. When we run the app, the screens are loading fine.
3. When we created a widget test on one of our screens, the images are not displayed
flutter run test/your_test.dart

Below is the asset section of the pubspec.yaml file

assets:
    - lib/assets/
    - lib/assets/icons/

## Logs

/Users/user/Documents/Flutter/sdk/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/user/Documents/Flutter/sdk/flutter
    • Framework revision 20e59316b8 (5 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.4.3
    • Dart plugin version 191.6183.87

[✓] Connected device (1 available)
    • SM A520F • 52105109ea678475 • android-arm64 • Android 8.0.0 (API 26) (emulator)

• No issues found!
Process finished with exit code 0

**Comment by chunhtai** [comment]
Do you have a runnable example? This should be supported if you use testWidget.

**Comment by snickersv2** [comment]
@chunhtai I tried this as an example:
void main(){

Widget testWidget() => MaterialApp(
    home: Scaffold(
      body: RepaintBoundary(
        child: Container(
          width: 200.0,
          height: 200.0,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: AssetImage(
                'lib/assets/icons/icon_image.png',
              ),
            ),
          ),
        ),
      ),
    ),
  );

  testWidgets('Widget Test', (WidgetTester tester) async {

    await tester.pumpWidget(testWidget());

    await expectLater(find.byType(Container),
      matchesGoldenFile('sample_golden.png'),);

  });
}

and then ran `flutter test --update-goldens test/widget_test.dart`
00:03 +1: All tests passed!    

but sample_golden.png is a blank image.

**Comment by chunhtai** [comment]
Since the assets loaded in an async manner, you will need to run in async

```dart
void main(){

  Widget testWidget() => MaterialApp(
    home: Scaffold(
      body: RepaintBoundary(
        child: Container(
          width: 200.0,
          height: 200.0,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: AssetImage(
                'lib/assets/icons/icon_image.png',
              ),
            ),
          ),
        ),
      ),
    ),
  );

  testWidgets('Widget Test', (WidgetTester tester) async {
    await tester.runAsync(() async {
      await tester.pumpWidget(testWidget());
    });
    await expectLater(find.byType(Container),
      matchesGoldenFile('sample_golden.png'),);
  });
}
```

**Comment by snickersv2** [comment]
@chunhtai I tried your code but it ran too fast when I executed `flutter run test/widget_test.dart` (instead of `flutter test`) .

I tried to add `await tester.pumpAndSettle(Duration)` after calling tester.pumpWidget(testWidget) and the image appeared. However, when i executed `flutter test --update-goldens` in order to update the golden file. The images are still not part of the snapshot to be used in golden test.

**Comment by snickersv2** [comment]
@chunhtai 
I'm experiencing the same thing with PieChart
https://pub.dev/packages/charts_flutter
https://github.com/google/charts/blob/master/charts_flutter/lib/src/pie_chart.dart

Can you please advise?

Thank you!

**Comment by chunhtai** [comment]
@snickersv2 
Do you runnable test example? It depends on how you set up the test to manually precache the image.

**Comment by snickersv2** [comment]
@chunhtai I don't have one yet but it seems we need to call tester.runAsync to load the widget that contains the chart.

await tester.runAsync(() async {
      await tester.pumpWidget(MaterialApp(home: ChartContainingWidget(
          data: dataModel )));
      await tester.pumpAndSettle();
    });

**Comment by chunhtai** [comment]
@snickersv2 yes, you will need to use runAsync if the widget relies on any asynchronized function to build which loading asset does

**Comment by chunhtai** [comment]
Closing this one.

**Comment by albertusangga** [comment]
Just in case someone is testing multiple asset images in a single widget in their test, this line of code might be helpful (assuming that you are using Image class to create the Widget, not DecoratedBox).

```dart
  /// current workaround for flaky image asset testing.
  /// https://github.com/flutter/flutter/issues/38997
  Future<void> pump(WidgetTester tester, Widget w) async {
    await tester.runAsync(() async {
      await tester.pumpWidget(w);
      for (var element in find.byType(Image).evaluate()) {
        final Image widget = element.widget;
        final ImageProvider image = widget.image;
        await precacheImage(image, element);
        await tester.pumpAndSettle();
      }
    });
  }
```

**Comment by Hixie** [comment]
Several of the comments above suggest running WidgetTester methods like `pump` and `pumpWidget` inside a `runAsync` callback. This will not have the desired effect -- in fact, I'm surprised it doesn't crash or otherwise fail. The only part that's appropriate to put inside a `runAsync` is the `precacheImage` call.
