### ISSUE TITLE
Include Xcodeproj files in initial Flutter app template

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#390]
When we generate a new Flutter app in our tools, we could also generate all the necessary Xcodeproj files. This could help our new Flutter devs get started on iOS easier/faster.

**Comment by sethladd** [comment]
cc @chinmaygarde

**Comment by eseidelGoogle** [comment]
We might have both filed the same bug? https://github.com/flutter/flutter/issues/391

**Comment by chinmaygarde** [comment]
Dupe of #391. Closing.
