### ISSUE TITLE
PageView.custom is not fully compatible with SliverChildBuilderDelegate

### ISSUE THREAD

**Issue by zbarryte-luminopia** [flutter/flutter#39002]
## Steps to Reproduce

1. Create a new flutter project, and replace the contents of your `main.dart` file with the following:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PageView.custom Defect',
      home: Page(),
    );
  }
}

class Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: PageView.custom(
        childrenDelegate: SliverChildBuilderDelegate(
          (context, index) {
            if (index <= 2) {
              return Center(child: Text('Page $index'));
            }
            return null;
          },
        ),
      ),
    );
  }
}

```
2. Launch the application on an iOS device or simulator.
3. Observe the screen.  Note that a single page in a `PageView` appears, stating "Page 0".
4. Swipe to the right until you reach "Page 2".
5. Swipe once to the right, revealing a blank page.
6. Swipe one more time to the right (no visual change will occur).
7. Swipe to the left two times, resulting in returning to "Page 2".

## Issue Description

It appears that `PageView.custom` is not fully compatible with `SliverChildBuilderDelegate`.  It is expected that returning `null` in the `SliverChildBuilderDelegate` builder results in no pages for a given index, the same way that doing so results in no items for a given index in `ListView.custom`.

However, returning `null` here simply results in a blank page, and does not limit the child count dynamically.

While it is possible to limit the child count by using the `childCount` parameter, this does not allow `PageView.custom` to utilize the full potential of `SliverChildBuilderDelegate`, limiting its utility.

## Output of `flutter doctor -v`

[✓] Flutter (Channel unknown, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/me/Library/Flutter/flutter
    • Framework revision 20e59316b8 (5 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/me/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/me/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (3 available)
    • MyIpad • bd6d5d3fb9848d40f136a65d792cb59f587a2af2 • ios            • iOS 12.4
    • macOS       • macOS                                    • darwin-x64     • Mac OS X 10.14.5 18F132
    • web         • web                                      • web-javascript • Google Chrome 76.0.3809.100 

• No issues found!

**Comment by chunhtai** [comment]
I can reproduce it. While I am investigating, here is workaround you can do
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PageView.custom Defect',
      home: Page(),
    );
  }
}

class Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: PageView.custom(
        childrenDelegate: SliverChildBuilderDelegate(
            (context, index) {
            if (index <= 2) {
              return Center(child: Text('Page $index'));
            }
            return null;
          },
          childCount: 3,
        ),
      ),
    );
  }
}
```
explicit set the child count will work

**Comment by zbarryte-luminopia** [comment]
@chunhtai - Yes, while it is possible to use the `childCount` argument to limit the number of children, the issue raised here is that `SliverChildBuilderDelegate` does not limit the child count simply by returning `null` in `PageView.custom`, as it does when doing the same thing in `ListView.custom`.  This limits the utility of `PageView.custom`, which is the issue here.

**Comment by chunhtai** [comment]
@zbarryte-luminopia yes, this is a bug we will need to fix. The issue is in RenderSliverFixedExtentBoxAdaptor.performLayout it does not correct the scroll offset when it reaches the end of children. I will put up a pr to address this issue soon.

**Comment by zbarryte-luminopia** [comment]
@chunhtai - Thank you!
