### ISSUE TITLE
version-related screen names in latest analytics

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#39008]
Not sure if this is intentional or not, but this is the latest top-screens:

![Screenshot 2019-08-21 at 2 33 00 PM](https://user-images.githubusercontent.com/11857803/63473194-6e9d0c00-c429-11e9-9caf-5021a17d2458.png)

@zanderso feel free to close if this is desired.

**Comment by zanderso** [comment]
These should be suppressed after

https://github.com/flutter/flutter/commit/0bba472858c8f8b22b689c8bbb0ecc5080109638

See:

https://github.com/flutter/flutter/pull/37514#discussion_r310762170
