### ISSUE TITLE
Eliminate redirect on initial load of docs.flutter.io

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3900]
docs.flutter.io redirects to docs.flutter.io/flutter.

I think, now that we have a unified API doc set, we can eliminate this redirect and speed up the initial load of our site.

Bonus, this helps verify the site in Webmaster Tools :)

**Comment by sethladd** [comment]
Warning: this will break a lot of links, unless I can get a redirect working. Maybe another reason to put App Engine in front?

**Comment by sethladd** [comment]
Step one was to land this: https://github.com/flutter/flutter/pull/3902

**Comment by abarth** [comment]
We're still planning to keep the docs at their current location, correct?  From this bug, it sounds like we're just moving the front page.

**Comment by sethladd** [comment]
Putting the homepage at docs.flutter.io/index.html and keeping the rest of the links where they are definitely makes it easier for now. We don't have infrastructure to maintain redirects anyway, so I'd like to scope this only to the front page (for now?)

**Comment by abarth** [comment]
SGTM
