### ISSUE TITLE
The sliding of NestedScrollView affects the sliding of child content in TabBarView

### ISSUE THREAD

**Issue by wbingz0719** [flutter/flutter#39018]
When using AppBar + Flexible SpaceBar + tabbar + tabbarview to display the contents of the home page, Tabbarview's children show different types of goods。 if Flexible SpaceBar has more content and the page slides upward, it is not time to display tabbar, but the list of goods has started to slide, and when it slides to tabbar, the list of goods is not the first place to display

**Comment by VladyslavBondarenko** [comment]
Hi @HansMuller 
does the issue persist? 
could you provide a minimal complete reproducible code sample?

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
