### ISSUE TITLE
Connect Flutter Hot Reload with Appetize.io

### ISSUE THREAD

**Issue by rubencg195** [flutter/flutter#39011]
## Use case

Appetize provides the flexibility of running native apps in the browser. This can be useful for developers who do not have access to their pc with all the simulators and Andriod/IOS dependencies at that moment and want to change their flutter app on the go (Maybe on a Chromebook or public computer hardware without Flutter's requirements). 

## Proposal

**Is there any way to integrate Appetize + Flutter?**
Appetize lets the users upload the APK, but that can take some time to build the app every the user saves. I wanted to know if there is a way of connecting flutter to Appetize to enable Hot reloading with the browser for native mobile apps or a way to generate the APK in a quicker way every time the user saves the flutter code to send it to Appetize as a new app.

![image](https://user-images.githubusercontent.com/25628940/63474327-5346f680-c453-11e9-9eea-5b5cfd6af297.png)

### +

![image](https://user-images.githubusercontent.com/25628940/63474432-b20c7000-c453-11e9-9dcb-ad2f46923f10.png)

**Comment by stuartmorgan** [comment]
This is something you would need to take up with Appetize.io. To use hot reload, you need to be able to connect to the Observatory; they would need to launch the app, get the observatory URL, and proxy it in a way that you could access remotely. Given that the Observatory is already exposed as a URL locally, I don't see any changes that would be required from the Flutter side.
