### ISSUE TITLE
Gridview has space below on Nexus 10 

### ISSUE THREAD

**Issue by MitchellQ** [flutter/flutter#39022]
I have posted this on SO but I wanted to post it here as well

https://stackoverflow.com/questions/57566613/gridview-not-filling-body-in-landscape/

I am building an application and working on a view in tablet landscape  I am using a gridview however when the view is in landscape the gridview doesn't fill the entire body and there there is a gap across the entire screen

**Comment by BondarenkoStas** [comment]
@MitchellQ I suppose it is safe to close the issue as it is mentioned in your issue above, which is taken into account. In case you disagree, I will reopen it.
