### ISSUE TITLE
Android Keyboard disconnect with TextField after value is modified using TextInputFormatter

### ISSUE THREAD

**Issue by Jasphere-Appsploration** [flutter/flutter#39047]
## Steps to Reproduce

1. Run the app with code in https://gist.github.com/Jasphere-Appsploration/7d2533638c2084ad0fc5dd843a2d8b39
2. Focus on the textfield and start typing "1234..."
3. After "123" is entered to textfield, text input formatter will format the value to 12-3
4. After the value is formatted, the soft keyboard is disconnected and any input further on is not inserted into the textfield
5. If manually tap on the text field again, the soft keyboard will reconnect and can continue typing.

This behaviour does not present on ver1.8.5-pre.78  and only happen on Android Devices. Currently tested with Nexus 6P and Samsung Galaxy S9.

flutter doctor -v output as below
```
[✓] Flutter (Channel master, v1.9.3-pre.58, on Mac OS X 10.13.6 17G65, locale en-MY)
    • Flutter version 1.9.3-pre.58 at /Users/jaspherelee/Desktop/Application/flutter
    • Framework revision 33e7af728a (3 hours ago), 2019-08-21 23:44:39 -0700
    • Engine revision fc27f80a12
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jaspherelee/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (2 available)
    • SM G960F • 2208229a21017ece                         • android-arm64 • Android 8.0.0 (API 26)
    • iPhone   • 54450a47f970529a18dbd35d22e5c558f062b51d • ios           • iOS 12.1.4

• No issues found!
```
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/25500437/63504685-a75de380-c504-11e9-889c-2b4b163032a5.gif)

**Comment by tvolkert** [comment]
We reverted the offending commit in flutter/engine#11720, which merged into the framework in https://github.com/flutter/flutter/commit/471c8058291327e6832b36e0fe0992211a0397af -- so this should be fixed now.

**Comment by MallorcaSoftware** [comment]
What is the plan for release this fix?

**Comment by tvolkert** [comment]
@MallorcaSoftware this bug was introduced in 6815f54 and fixed in 471c805 -- and thus exists in versions `v1.9.2` - `v1.9.7`.  As such, it's not present in the current stable release (`v1.9.1+hotfix.2`).  If you're seeing a related issue, please file an issue with details.  Thanks!

**Comment by ened** [comment]
@tvolkert should https://github.com/flutter/flutter/wiki/Bad-Builds be updated to reflect the affected version range (1.9.2 - 1.9.7)?

**Comment by tvolkert** [comment]
@ened yep - done!
