### ISSUE TITLE
[web]: After Build the web application has minified errors

### ISSUE THREAD

**Issue by MyracleDesign** [flutter/flutter#39049]
Development and webdev serve works well, but when I wanted to deploy my project to Heroku, I got a red screen with a lot of minified errors. You can find the deployed project [here](https://digital-journal-client.herokuapp.com/#/).

```
The following minified:AC was thrown building minified:tW:
main.dart.js:1218 CastError: Instance of 'minified:nl<minified:bQ<minified:eW>>': type
main.dart.js:1218 'minified:nl<minified:bQ<minified:eW>>' is not a subtype of type 'minified:aK<minified:eW>'
```

You can find the source code [here](https://github.com/MyracleDesign/voyage-prework-tier3-journal-app), and you can just run the `webdev build` and check the outcome in the build folder.

**Comment by jld3103** [comment]
In general I would love to get better error messages on web than these.

**Comment by jonahwilliams** [comment]
This is not a minification error, it is a type error in your code, see https://api.flutter.dev/flutter/dart-core/CastError-class.html.

> In general I would love to get better error messages on web than these.

I think it's unrealistic to expect verbose errors from a minified release. That said, it would be easier to debug this if we could produce an un-minified release build (i.e. profile).

**Comment by MyracleDesign** [comment]
After your comment I figured out that I can do also the opposite and let webdev serve run in production mode. Then I started to comment everything step by step out and found in my provider.setup.dart following line.
```
List<SingleChildCloneableWidget> providers = [
  ...independentService,
  ...dependentService,
  ...uiConsumableService
];

List<SingleChildCloneableWidget> independentService = [
  Provider.value(value: ApiService())
];
List<SingleChildCloneableWidget> dependentService = [
  ProxyProvider<ApiService, AuthService>(
    builder: (context, api, auth) => AuthService(api: api),
  )
];
List<SingleChildCloneableWidget> uiConsumableService = [
  /* StreamProvider<User>(
    builder: (context) => Provider.of<AuthService>(context, listen: false).user,
  ),*/
];
```
That solved the problem, interesting that the dart compiler did not picked it up.

I think that PR can be closed. Thanks for your help everyone.
