### ISSUE TITLE
Expose Firebase Storage's new ability to list files in Flutter

### ISSUE THREAD

**Issue by puf** [flutter/flutter#39054]
The Firebase SDKs for Cloud Storage recently added the ability to list files in the storage bucket ([Android](https://firebase.google.com/docs/storage/android/list-files), [iOS](https://firebase.google.com/docs/storage/ios/list-files)). It would be great if this functionality were also available in the `firebase_storage` Flutter plugin.

**Comment by rosariopfernandes** [comment]
@puf This has already been reported on the [FirebaseExtended/FlutterFire](https://github.com/FirebaseExtended/flutterfire) repo (See FirebaseExtended/flutterfire#83) and there's already a PR (FirebaseExtended/flutterfire#232) that should implement it. :)

**Comment by kroikie** [comment]
@puf

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1077. Any further collaboration will be done there.
