### ISSUE TITLE
[bluetooth_flutter]

### ISSUE THREAD

**Issue by luisdiaz14** [flutter/flutter#39051]
Hi, 

I work for a development company. We do have any application on flutter. We use bluetooth to connect to devices. 

We need a plugin developed by flutter team to connect using bluetooth with other devices.

There is a flutter_bluetooth_serial, but it only works on Android platform.
https://pub.dev/packages/flutter_bluetooth_serial

Some help would be appreciatted

Thanks

**Comment by pauloamaral93** [comment]
I use https://pub.dev/packages/flutter_blue , I recommend v0.5.

**Comment by BondarenkoStas** [comment]
@luisdiaz14 Please report if ```flutter_blue``` solved your problem? If yes, please close the issue.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
