### ISSUE TITLE
Consider supporting MSBuild without Visual Studio

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#39067]
Currently we require Visual Studio for building for Windows. We could instead support a direct toolchain+SDK install so that people who didn't want the IDE portion didn't have to install all of VS.

This would add more complexity to the `flutter` tool though; we'd need to figure out how to validate that all the necessary pieces were installed, defined where they are, etc.

**Comment by andreujuanc** [comment]
I would love this. Since lots of people are starting to use vscode instead.

**Comment by stuartmorgan** [comment]
For anyone interested in this, there's a PR at https://github.com/flutter/flutter/pull/42034 that implements this, but needs tests. See my last comment there for a description of what the test needs to do and pointers to examples. I'm happy to review a complete and tested PR for this.

**Comment by fisforfaheem** [comment]
Yes we would love to see this by july 2020 it would be so awesome! and UWP apps are so easy

**Comment by stuartmorgan** [comment]
This was fixed by the PR above.
