### ISSUE TITLE
[camera] Developer should be able to lock camera orientation

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#39071]
Sometimes I want the camera to follow rotation, sometimes I don't.
It should be an option in the API.

For example if I am writing a photo taking app I might want to rotate my device to take a landscape photo so I want the camera to follow the rotation (camera locked to device orientation).

Another example is I am writing a kiosk and I want the camera to always be a certain orientation no matter how the device is oriented. (camera on a swivel always pointing up).

_Originally posted by @RussellZornes in https://github.com/flutter/flutter/issues/16587#issuecomment-499657320_

**Comment by troy379** [comment]
Hey @mklim 
Any updates on this?

**Comment by Katekko** [comment]
Waiting an update...

**Comment by ganisback** [comment]
+1

**Comment by locskot** [comment]
+1

**Comment by dlmonnink** [comment]
+1

**Comment by SathusanK** [comment]
+1

**Comment by DQvsRA** [comment]
Subscribe

**Comment by jpiabrantes** [comment]
+1

**Comment by alfred-risb** [comment]
This issue has reported more than a year, but still no solution yet

**Comment by AndruByrne** [comment]
+1

**Comment by stanciuoctavian** [comment]
+1

**Comment by buzzySmile** [comment]
+1

**Comment by mvanbeusekom** [comment]
Closing since this issue is solved in version 0.7.0 of the camera plugin. If you disagree please comment and I will reopen it.
