### ISSUE TITLE
video_player plugin cannot handle some URL formats

### ISSUE THREAD

**Issue by jtmcdole** [flutter/flutter#39076]
The video player plugin tries to divine the format of the video from the URL alone. We need to be able to suggest the format as our URLs do not end in ".format" (and cannot).

**Comment by amirh** [comment]
@iskakaushik @cyanglaz heads up that community is working on a PR for this.

**Comment by dnfield** [comment]
Can we close this issue then?

**Comment by jtmcdole** [comment]
Yes
