### ISSUE TITLE
Attempt to execute code removed by Dart AOT compiler (TFA)

### ISSUE THREAD

**Issue by SourabhShastri90** [flutter/flutter#39096]
I see this error once I install the release apk - "Attempt to execute code removed by Dart AOT compiler (TFA)" on the Material Widget.
I used ```charts_flutter: ^0.6.0``` to implement some charts in my flutter project then tested the project using the ```flutter run``` command. It was running fine. After completing my project I generated a Release APK with the command ```flutter build apk --release```. Now I see this error once I install the release apk - 
```
Attempt to execute code removed by Dart AOT compiler (TFA)
```
How do I resolve this?

![20190822_145545 1](https://user-images.githubusercontent.com/53648028/63569436-ffddc100-c596-11e9-8a38-311de841ac0c.jpg)

**Comment by SourabhShastri90** [comment]
charts_flutter: ^0.5.0 with charts_common: ^0.5.0 and charts_flutter: ^0.7.0 with charts_common: ^0.7.0 is working fine. 0.7.0 has been released yesterday.

**Comment by mraleph** [comment]
Which version of Flutter are you using? Please post `flutter doctor` output.

We would need a reproduction or more information about the problem - you should be able to see stack traces in the device log.

/cc @alexmarkov

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
