### ISSUE TITLE
Flutter App Restarts after relaunching from background

### ISSUE THREAD

**Issue by balajiks-dev** [flutter/flutter#39098]
Hi,
I did my app for the employee details list display after 4 API response. It works well but when I went to another app and relaunch this app, the app is restarting from the First like going all the API and response like that. I want to go to the same state where left while relaunching. Suggest any ideas .

**Comment by BondarenkoStas** [comment]
@Balajiks-alt Please provide your ```flutter doctor -v``` output. Also, do you encounter it only with this exact app, or with any other? Please provide info about your device. Did you test it on emulators as well?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by ochamo** [comment]
Hello there I have the same issue. It happens with every app I have done, for example Let's say my app has three screens, and then the user wants to checkout another app, after a time when he returns, the app will restart from the root route again. Is there anyway I can preserve my stack of navigation.

This is my flutter doctor -v output
![image](https://user-images.githubusercontent.com/60203851/83567258-8d631f80-a4de-11ea-9e33-af0a93f10c56.png)
