### ISSUE TITLE
AndroidStudio3.6 c6 can't startup with flutter plugin installed.

### ISSUE THREAD

**Issue by CuiTianci** [flutter/flutter#39092]
I just can't start AndroidStudio3.6 c6 up aflter i installed flutter plugin.

**Comment by BondarenkoStas** [comment]
@CuiTianci Is it still relevant? Please provide your ```flutter doctor -v``` output. Also version of the plugin.

**Comment by CuiTianci** [comment]
I have updated AndroidStudio to 3.6C9 and it works fine now.
But i have another issue of AndroidStuiod.It has been several months that the preview version of AndroidStuiod cannot be downloaded from this page.https://developer.android.google.cn/studio/preview 




------------------ 原始邮件 ------------------
发件人: "Stanislav Bondarenko"<notifications@github.com>;
发送时间: 2019年9月4日(星期三) 晚上7:36
收件人: "flutter/flutter"<flutter@noreply.github.com>;
抄送: "崔天赐"<772145859@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [flutter/flutter] AndroidStudio3.6 c6 can't startup with flutterplugin installed. (#39092)




@CuiTianci Is it still relevant? Please provide your flutter doctor -v output. Also version of the plugin.

**Comment by BondarenkoStas** [comment]
@CuiTianci Then I think it's safe to close the issue, thank you.
About your second comment, I would advise you to direct the issue to support of develper.android.google.cn, as anyway flutter team can't do anything with it.
