### ISSUE TITLE
Make it possible for customers to create their own .ipa w/o building from flutter/engine

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#391]
@chinmaygarde has started on this and likely has some plans.

**Comment by eseidelGoogle** [comment]
My understanding is that @chinmaygarde completed this, and we're just blocked on travis, etc.
https://travis-ci.org/flutter/buildbot

Interestingly the recent builds look green, so maybe we're correctly producing the necessary assets on travis now?

**Comment by abarth** [comment]
> Interestingly the recent builds look green, so maybe we're correctly producing the necessary assets on travis now?

I turned it off on the bot.  There's no way to turn off the bot entirely because Travis.

**Comment by eseidelGoogle** [comment]
This is now possible.  We need a bot for this, but I"m working on that.  Closing.
