### ISSUE TITLE
 ListView physics: BouncingScrollPhysics(), it can‘t work.

### ISSUE THREAD

**Issue by Juneor** [flutter/flutter#39103]
Drawer(
      child: ListView(
        padding: EdgeInsets.all(0),
        physics: BouncingScrollPhysics(),
}

 physics: BouncingScrollPhysics(), it can‘t work.

**Comment by LongCatIsLooong** [comment]
Please provide more information as to what didn't work for you, the `flutter doctor -v` output and a minimal reproducible sample. My guess would be your `ListView` doesn't have enough content so you need not only `BouncingScrollPhysics` but also `AlwaysScrollableScrollPhysics`.

**Comment by Juneor** [comment]
Thank you very much! 
My problem is solved.
