### ISSUE TITLE
#56305 SIGABRT #01 pc 001374df /data/app/com.yyfax.app-5DtzosItRWAKfq3DzxdajA==/lib/arm/libflutter.so [armeabi-v7a]

### ISSUE THREAD

**Issue by Luozf12345** [flutter/flutter#39102]
I have a proplem with my Flutter application. Some mobile phones of MI and SAMSUNG have crashed.

## Logs
```

1 #00 pc 0004a230 /system/lib/libc.so (tgkill+12) [armeabi-v7a]
--
2 #01 pc 000479c3 /system/lib/libc.so (pthread_kill+34) [armeabi-v7a]
3 #02 pc 0001d9c5 /system/lib/libc.so (raise+10) [armeabi-v7a]
4 #03 pc 00019511 /system/lib/libc.so (__libc_android_abort+34) [armeabi-v7a]
5 #04 pc 00017150 /system/lib/libc.so (abort+4) [armeabi-v7a]
6 #05 pc 001374df /data/app/com.yyfax.app-2/lib/arm/libflutter.so [armeabi-v7a]
7 #06 pc 0012ccbb /data/app/com.yyfax.app-2/lib/arm/libflutter.so [armeabi-v7a]
8 #07 pc 0015ec51 /data/app/com.yyfax.app-2/lib/arm/libflutter.so [armeabi-v7a]
9 #08 pc 00137b09 /data/app/com.yyfax.app-2/lib/arm/libflutter.so [armeabi-v7a]
10 #09 pc 0013a401 /data/app/com.yyfax.app-2/lib/arm/libflutter.so [armeabi-v7a]
11 #10 pc 00011fcb /system/lib/libutils.so (android::Looper::pollInner(int)+614) [armeabi-v7a]
12 #11 pc 00011cd7 /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+26) [armeabi-v7a]
13 #12 pc 00087c51 /system/lib/libandroid_runtime.so (android::NativeMessageQueue::pollOnce(_JNIEnv*, _jobject*, int)+22) [armeabi-v7a]
14 #13 pc 025e2605 /system/framework/arm/boot-framework.oat (oatexec+7390725) [armeabi]
15 java:
16 android.os.MessageQueue.next(MessageQueue.java:323)
17 android.os.Looper.loop(Looper.java:136)
18 android.app.ActivityThread.main(ActivityThread.java:6682)
19 java.lang.reflect.Method.invoke(Native Method)
20 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
21 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

```

**Comment by Levi-Lesches** [comment]
Please include a meaningful title. What happens to trigger this error? Also, please format your error by surrounding it with ```

**Comment by qq3144225600** [comment]
Packaging encountered this problem。
There have been too many times, I hope to get a good solution.

**Comment by Levi-Lesches** [comment]
Again, what EXACTLY. Were you building an APK, AppBundle, or an ipa? Did you get this EXACT stack trace? (with all the numbered details)? Does it give you a log file to look at? Can you reliably reproduce it to show us?

**Comment by BondarenkoStas** [comment]
@Luozf12345 as asked above, please provide more information. Is it still relevant?

**Comment by qq3144225600** [comment]
I have not tested the problem myself. I built it with flutter build apk. It is a log reflected by the third-party killing log. I suspect that it is a problem with packaging.
Below is my ndk configuration:
      ndk {
            //设置支持的SO库架构
            abiFilters 'armeabi-v7a'//, 'arm64-v8a'//, 'x86', 'x86_64'
        }

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
