### ISSUE TITLE
Error: 

### ISSUE THREAD

**Issue by Juneor** [flutter/flutter#39105]
Container(
      color: Color(0xFFF7F7F7),
      height: 55,
      decoration: BoxDecoration(
        
      ),
}
That would be report an error..

If   color: Color(0xFFF7F7F7), put  in  decoration，that will not report an error.

**Comment by keshava19** [comment]
The `color` argument is a shorthand for `decoration: new BoxDecoration(color: color)`, which means you cannot supply both a `color` and a `decoration` argument.

**Comment by Levi-Lesches** [comment]
Next time, please post with a meaningful title and description, along with the actual error you get. It can get you help faster

**Comment by Juneor** [comment]
> Next time, please post with a meaningful title and description, along with the actual error you get. It can get you help faster

Ok，Thank you！

**Comment by Juneor** [comment]
> The `color` argument is a shorthand for `decoration: new BoxDecoration(color: color)`, which means you cannot supply both a `color` and a `decoration` argument.

Thank you！
