### ISSUE TITLE
Tooltip waitDuration default could be increased to 500 - 1000ms

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#39111]
The current default of 0ms is quite irritating to use.

**Comment by shyndman** [comment]
You can do this with a `TooltipTheme` https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/tooltip_theme.dart

Oddly enough, I can't find docs for it though.

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by shihaohong** [comment]
Hi @cbenhagen, the current `waitDuration` is based off of the [material design specifications](https://material.io/components/tooltips/#behavior), so we aim to stay as true to it by default. You can change the `waitDuration` for you own use-case via the `Tooltip.waitDuration` property, and once `TooltipTheme` is in stable, set all `Tooltip`s for you application that way.
