### ISSUE TITLE
[google_maps_flutter] onTap on Circles is not called

### ISSUE THREAD

**Issue by neokree** [flutter/flutter#39116]
I am using `google_maps_flutter: ^0.5.20+6` in my app.
The `onTap` method of Circles seems not to be working. Specifically, when tapped it does not call the callback method specified in the onTap named property.

## Steps to Reproduce

1. Add this code as build method of the example application:
```
  @override
  Widget build(BuildContext context) {
    return GoogleMap(
      circles: [
        Circle(
            circleId: CircleId("123"),
            fillColor: Colors.red,
            center: LatLng(45.28495108140074, 9.191062646500313),
            radius: 300,
            onTap: () => print('test'))
      ].toSet(),
    );
  }
```
2. Build the application (on iOS or Android)
3. Tap on the circle

No prints happen. 

I have also tried to use breakpoints, but the method seems to not be called ever.
Tested on Android and iOS

**Comment by bsr203** [comment]
Same issue as touch event just passes through to the map as you can slide, zoom etc clicking on the circle.

**Comment by bsr203** [comment]
@neokree It works if you set 
```
              consumeTapEvents: true,
```
:-)
