### ISSUE TITLE
Analytics tweaks for flutter_tool

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3912]
- [x] Build an analytics dashboard, summarizing the measurements we're watching
- [x] Measure what OS our developers are using when developing
- [x] Measure which mobile OS our developers are targeting
- [x] Check that our bots are not sending analytics pings
- [x] whitelist the codelab branch
- [x] Learn how long an analytics session is
- [x] Disable analytics pings when our tools call our tools (e.g. `flx`) (tracked: https://github.com/flutter/flutter/issues/3862)
- [ ] Filter out, or disable, flutter engineers

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
Looks like a session ends after 30 mins of inactivity, and its adjustable.

**Comment by devoncarew** [comment]
No analytics on bots: https://build.chromium.org/p/client.flutter/builders/Linux/builds/935/steps/setup.sh/logs/stdio and https://travis-ci.org/flutter/flutter/builds/130140833#L312.

**Comment by devoncarew** [comment]
@sethladd, I think we've accomplished the bulk of what this bug was tracking; ok to close?

**Comment by sethladd** [comment]
We did great! Let's call this done for now. Thanks!
