### ISSUE TITLE
Option to save state after last hot restart (R)

### ISSUE THREAD

**Issue by dvorapa** [flutter/flutter#39121]
## Use case
When going afk from my PC, I usually leave currently developed apps installed on my phone (from `flutter run`) and test them offline when bored (while waiting for subway etc.). For this I can not just unplug the phone and go, because when I unplug the phone, all hot reload and hot restart changes are thrown away.

Therefore I have to quit `flutter run` and run it once more to save the final state. It would be helpful to save hot restart state by using some key or by using some command line parameter.

**Comment by jonahwilliams** [comment]
We cannot add this functionality. The underlying APK may not be modified, and we cannot guarantee that the temporary directory used to store artifacts is persisted.

**Comment by dvorapa** [comment]
Another option would be to add a new letter (let's call it `a`), which would just make things easier. Instead of doing `q` (quit) -> `flutter run --release`, `a` would do exactly that (quit `flutter run` and rebuild app in release mode).
