### ISSUE TITLE
required parameter in slider

### ISSUE THREAD

**Issue by Joao-b4** [flutter/flutter#39129]
I think it would be nice for the `Slider `widget to contain a `required` parameter, or a way to display the `label `even without actions

**Comment by JoseAlba** [comment]
This ticket sounds like a duplicate to: https://github.com/flutter/flutter/issues/34704

**Comment by Joao-b4** [comment]
yes, the same thing, show the label programmatically, without user interaction

**Comment by rydmike** [comment]
This is duplicate of https://github.com/flutter/flutter/issues/34704 consider closing this in favor of the first reported issue.

**Comment by TahaTesser** [comment]
closing as duplicate of https://github.com/flutter/flutter/issues/34704
