### ISSUE TITLE
Flutter for Web Screen Reader support for Windows Narrator and Orca

### ISSUE THREAD

**Issue by anticode-403** [flutter/flutter#39133]
Title says it all. I want to use Flutter for Web in a project where accessibility is a requirement and Flutter for Web does not seem to support screen readers.

**Comment by Levi-Lesches** [comment]
I've noticed there doesn't seem to be a logical order to the DOM when it comes to Flutter for Web. I remember seeing an issue about this but I can't find it now. But this is super important.

**Comment by nturgut** [comment]
closing this one as duplicate of: https://github.com/flutter/flutter/issues/66383 

thanks for filing the issue.
