### ISSUE TITLE
is there any plan to support playing multimedia (audio, video) by flutter itself? plugins are not a optimized solution for multimedia

### ISSUE THREAD

**Issue by jkmpariab** [flutter/flutter#39137]

**Comment by Levi-Lesches** [comment]
Just curious, why would you say plugins are not optimal? Flutter _itself_ is a plugin!

**Comment by jkmpariab** [comment]
> Just curious, why would you say plugins are not optimal? Flutter _itself_ is a plugin!

flutter is not a plugin but a package.
and why?
there's tons of problem to platform channel plugins on supporting different formats or different functionality. and with support of web and desktop it goes further.
so native support from flutter itself is far better

**Comment by jkmpariab** [comment]
> Right, fair point about packages vs plugins.
> 
> But wouldn't you say that having the OS control the media is the best way to do it? That way the OS can offer additional features, such as showing a thumbnail of the media in the volume controls, pause/resume the media from the lockscreen/bluetooth device, etc.

by flutter support (whether by implementing its own solution (like skia for ui) or native solution (os control) ) rather than platform channel you have direct implementation for each os. i mean playing a video or audio is a heavy task that should perform with no delay.

**Comment by stuartmorgan** [comment]
Closing; implementing audio and video playback completely from scratch is out of scope.
