### ISSUE TITLE
Why are ChangeNotifier.listeners private?

### ISSUE THREAD

**Issue by Levi-Lesches** [flutter/flutter#39146]
I am writing an app that basically runs off `ChangeNotifier`s (they work like `BLoC`s, but better). In my app I want a call from FCM to refresh everyone's data, which means re-assigning some `InheritedWidget` `ChangeNotifier` properties. This works, but the UI won't change since they are waiting for a callback from a no-longer-present `ChangeNotifier`.

My first reaction was to simply re-assign all listeners from the old notifier to the new one. Then I found out that they are private properties, and I couldn't access them. So I subclassed `ChangeNotifier`, and just re-wrote the logic there. But why can't another class access the listeners? Is there a really good reason not to? If so, I could just wait for users to close the app (given my use case, this isn't terrible, and is actually what I was planning originally). But I think the owner of a `ChangeNotifier` should be able to manipulate the listeners, as long as it's documented that this isn't the preferred way.

**Comment by Levi-Lesches** [comment]
Of course, this isn't blocking anything important. I could probably re-write the class to do all it's initialization logic on demand, I just wanted to know if there was an important reason why not to simply replace the object, as is generally the way when it comes to Dart.

**Comment by mannprerak2** [comment]
I think you shouldn't replace the ChangeNotifier object.
Because it is meant to hold your **state**. 
The state held is being used by **multiple widgets across the app**, so you can't just replace the state completely as then you would have to update every widget using this state.
It would be more efficient to change objects inside your ChangeNotifiers and call notifyListeners() in setters.

**Comment by Levi-Lesches** [comment]
Right so that's what I ended up doing. After a weekend of thinking it over, I realize that, yeah, I probably shouldn't be playing around with private properties and this is a good reason why. 

But if it makes any sense, my original plan was to replace the `ChangeNotifier`, and for every listener in the old notifier, remove it and assign it to the new one.
