### ISSUE TITLE
[android_intent] Add support for setType

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#39148]
## Use case

[From @shaxxx](https://github.com/flutter/plugins/pull/1983#issue-307951664):

> This is needed if IE. you want to send intent to stream video. You would need to set both data (some http Uri) and mime type (ie. 'video/*').

## Proposal

flutter/plugins#1983

**Comment by shaxxx** [comment]
Resolved by https://github.com/flutter/plugins/pull/1983
