### ISSUE TITLE
Let platformviews on Android have hooks to get the current Android view

### ISSUE THREAD

**Issue by xster** [flutter/flutter#39155]
Let the PlatformView API have some access to the Android view that Flutter renders into. 

The callback will alert when the Flutter view becomes available or unavailable. Related to:
https://github.com/flutter/flutter/issues/34156

Make it composable such that if in the future, the FlutterPlugin API needs it too, it can be extended to plugins in general. 

cc @amirh

**Comment by matthew-carroll** [comment]
PR landed.
