### ISSUE TITLE
stock_build_iteration regressed

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#39154]
stock_build_iteration has gone from about 4.5ms to about 5.5ms since April. It's been mostly a gradual slowdown, but it would be worth profiling and optimising any low-hanging fruit.

**Comment by goderbauer** [comment]
Looks like this only regressed on android? On iOS it changed from ~2.7 to ~2.9.

**Comment by liyuqian** [comment]
Any update on this? I wonder why this is not marked as TODAY initially?

**Comment by goderbauer** [comment]
It wasn't marked TODAY because it is a gradual slowdown over time (there doesn't seem to be one cause for it). We didn't have bandwidth to investigate this yet.

**Comment by liyuqian** [comment]
It seems that this benchmark further regressed from 5.5ms to 5.6ms in https://github.com/flutter/flutter/commit/9aea03f4afb1c616dd98c2b328032af7849f99cc on 08/21/2019. Does anyone have bandwidth to check it? CC @LongCatIsLooong

**Comment by liyuqian** [comment]
@LongCatIsLooong : I think you've recently looked into this. Any update?

**Comment by LongCatIsLooong** [comment]
@liyuqian I reverted the commit in question. See https://github.com/flutter/flutter/issues/39060.

**Comment by liyuqian** [comment]
@LongCatIsLooong : great! Are we good to close this issue, or is there more to be fixed?

**Comment by liyuqian** [comment]
I guess all low-hanging fruits are already picked, @LongCatIsLooong ? If so and there's no further action that we can do, I'm going to close this issue.

**Comment by goderbauer** [comment]
Closing per previous comment.
