### ISSUE TITLE
Add pixel and raw rgba functionality to Image class

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#39152]
consumer_dependencies_count increased recently, during the benchmarks blackout.

Should be easy to bisect.

cc @tvolkert @jonahwilliams @goderbauer

**Comment by jonahwilliams** [comment]
Looks like it regressed with https://github.com/flutter/flutter/pull/38473, due to the addition of the `package:image` dependency, which in turn pulled in several more transitive dependencies.

cc @Piinks @gspencergoog 

We should consider writing our own image parser, or finding one with fewer deps

**Comment by franciscojma86** [comment]
As discussed on https://github.com/flutter/flutter/issues/39850, this metric was re-baselined. It might be worth capturing the discussion for posterity and closing this issue.

**Comment by Piinks** [comment]
@goderbauer and I discussed leaving this in and investigating his suggestions above as means to replace. There is already work that is dependent on this change. 
I will re-frame this issue to keep track of that then?

**Comment by jakemac53** [comment]
I looked at doing this and was able to fix most everything, but it looks like we are currently missing the functionality to go from raw the pixel data back to png format.

One option would be the ability to create an `Image` instance from raw rgba values (likely a `List<Uint32>`). @goderbauer do you know the feasability of that?

**Comment by jakemac53** [comment]
Oh wait, it looks like `decodeImageFromPixels` is possibly what I want, just hard to find :)

**Comment by goderbauer** [comment]
@jakemac53 Was there a specific place you were looking for that? We should cross-link this function better in the docs to make it easier to find. :)

**Comment by jakemac53** [comment]
It is just that top level functions in general are hard to find. I was looking for something on the `Image` class itself.
