### ISSUE TITLE
flutter build never works

### ISSUE THREAD

**Issue by jacksonw765** [flutter/flutter#39158]
When I run the command ```flutter build apk --release -v``` I get the following:
```
[+3081 ms] > Task :app:compileflutterBuildReleaseArm
[        ] Waiting for another flutter command to release the startup lock...
```

It will just sit on this screen until I cancel the batch job. I've tried reinstalling android studio/flutter/dart, deleting the lock file and restarting. No luck so far. 

Any idea?

**Comment by jacksonw765** [comment]
Update: I managed to get build working on different Intel based laptop. (Not sure if that matters) I have the exact same version of Dart/Flutter/Android Studio on both computers yet one still shows that "Waiting for another flutter command to release..." Any help would be great.

**Comment by Levi-Lesches** [comment]
Well clearly, an instance of Flutter is still running. Try restarting your computer, that should close everything.

**Comment by jacksonw765** [comment]
Yeah I've tried this about 15 times lol. Flutter seems to be firing off multiple jobs and one is never finishing when I run "flutter build"

**Comment by Levi-Lesches** [comment]
Try to find Flutter in the Task Manager. Try tracking how many instances pop up/go away if you start/quit a command. 

Also, are you on stable?

**Comment by jacksonw765** [comment]
Unable to find flutter.exe running but there are quite a few dart.exe. Disabling any one of them crashes the build. 

Yes I am on stable. I've also tried running it on dev and master.

**Comment by Levi-Lesches** [comment]
Is it possible you have two Flutter/dart installations? Try removing one if so

**Comment by amitkhairnar44** [comment]
@jacksonw765 This happens when there's already an instance of dart running.
Close Android Studio and check in task manager for dart. If it's there then end it's process (kill it). Then start android studio and wait for analyser to finish it's job and then run that command.

**Comment by BondarenkoStas** [comment]
@jacksonw765 Please report do you still encounter the issue?

**Comment by jacksonw765** [comment]
yep still an issue. Everything runs smooth on my hackintosh and on my laptop. I'll close the issue just since it seems to be something I got myself into lol. Thanks for the help.
