### ISSUE TITLE
flutter text field issues on ios

### ISSUE THREAD

**Issue by ye9ine** [flutter/flutter#39169]
latest flutter v.7 has text field issues on ios. can type myanmar unicode font correctly on text field but if back delete the the text skip some character and not deleting. but in flutter 1.5 it has no issues so please review it

**Comment by ye9ine** [comment]
ok i will reply a video later thank you for your reply

**Comment by ye9ine** [comment]
in flutter version 1.9 unicode is fix bro but i have to test zaw gyi font

**Comment by GaryQian** [comment]
I will consider this fixed then. If this is not fixed, feel free to comment here and we can reopen this!
