### ISSUE TITLE
basic_material_app_win__compile regressed with kotlin

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#39162]
"[flutter_tool] Flip create language defaults to swift and kotlin #38339" caused basic_material_app_win__compile to regress.

cc @zanderso @timsneath

**Comment by zanderso** [comment]
In a separate discussion, I believe that @cbracken and @jason-simmons mentioned that additional overhead from the swift and kotlin templates was expected.

**Comment by audkar** [comment]
Kotlin has worse compile time then Java. However Flutter project template uses very old versions of Gradle and Kotlin. And newer versions has a lot of improvements on speed (especially incremental build and cache)

**Comment by zanderso** [comment]
Upgrading versions is in progress here https://github.com/flutter/flutter/pull/32550

**Comment by audkar** [comment]
That PR is being reviewed for such long time that new stable versions are already released :)

**Comment by blasten** [comment]
Was the baseline updated recently? It doesn't look like a regression on the dashboard anymore.

**Comment by zanderso** [comment]
Since the dashboard is green, I'll close this issue. We can track upgrading the version in the place we're already doing that.
