### ISSUE TITLE
flutter generate during development

### ISSUE THREAD

**Issue by szotp** [flutter/flutter#39175]
I'm working on a package that utilizes `build.yaml`:
https://github.com/flutter/flutter/wiki/Code-generation-in-Flutter
But there are some usability problems, at least for me.

Problem 1:
After each change in the code, I want to run `flutter generate` to see if it works. The problem is: flutter does not use new version of this package, I need to do manually clean everything:
`flutter clean && flutter generate --verbose`
but this takes 30 seconds, downloads packages from network, etc. And VSCode handles it in a weird way.

Can this be speed up? At least to not download packages again.

Problem 2:
Is there a simple way to see log output from my builder? `flutter generate --verbose` shows it, but its super verbose.

CC: @jonahwilliams

**Comment by szotp** [comment]
I managed to fix the first problem by using build_test.

The second problem still exists I think. And not only during development, logs emitted by Builder seem to be swallowed completely during flutter build, if something fails, user will not know what is happening.

**Comment by BondarenkoStas** [comment]
@szotp Can you please create a new issue report with the second problem, so it will be a proposal? Once you do, I will close this issue as solved.

**Comment by szotp** [comment]
Ok, maybe I will be able to submit a PR for the logging problem.
