### ISSUE TITLE
Don't run pod install when there are no macos plugins

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#39184]
STR:
- Starting with the FDE example (which has no plugins), add just a plugin that doesn't support macOS
- build

Expected results:
- No effect

Actual results:
- The whole `pod install` flow runs, and just doesn't do anything useful.

We should check whether any of the plugins support macOS before doing the pod step, rather than running it when there are *any* plugins.

**Comment by lesnitsky** [comment]
>  just doesn't do anything useful

I played with flutter tool locally to fix this issue and managed to do the "whether any of the plugins support macOS before doing the pod step" part, but `pod install` step is still required to generate `Pods/Target Support Files/**`
Or do you want to tune inputPaths as well in scope of this issue?

**Comment by stuartmorgan** [comment]
> `pod install` step is still required to generate `Pods/Target Support Files/**`

I don't follow; a macOS project that has never had any plugins works fine. `Pods/` is not required by it at all. This bug is about the fact that from the perspective of the macOS build, adding a plugin that doesn't support macOS shouldn't do anything.

The solution to this is likely to move away from the monolithic `.flutter-plugins` as described in #39659

**Comment by jmagman** [comment]
I believe this was fixed by #72020 which parses platform-aware `.flutter-plugins-dependencies`.
