### ISSUE TITLE
video_player can't read local directory file

### ISSUE THREAD

**Issue by ghanyin** [flutter/flutter#39180]
i download a mp4 file in my device directory:
```/var/mobile/Containers/Data/Application/6F710006-FCC2-4D6B-8F20-A76AE119D0DF/Library/Application Support/movie/...mp4```

then 
```
File file = File.fromUri(Uri.parse(localPath));
VideoPlayerController.file(file)
```
but videoplayer not show the mp4,
the mp4 file is available

**Comment by BondarenkoStas** [comment]
Seems as file is not loaded while File.fromUri(). Can you confirm that? Can't It load a specific video or any? Need more details to investigate as it may be something wrong with localPath, the way you specify it.

**Comment by ghanyin** [comment]
> Seems as file is not loaded while File.fromUri(). Can you confirm that? Can't It load a specific video or any? Need more details to investigate as it may be something wrong with localPath, the way you specify it.

thank you! I have resolve this issue. I save thee video in the library directory, but can't read it. so I save it in the document  directory. and it can work now!

**Comment by BondarenkoStas** [comment]
Closing the issue as it is resolved
