### ISSUE TITLE
firebaseStorage and imagepicker do not work together

### ISSUE THREAD

**Issue by pekretsc** [flutter/flutter#39193]
If I make a new FlutterProject and import 

image_picker: ^0.6.1
firebase_storage: ^3.0.4

I always get the following:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:preDebugBuild'.
> > Android dependency 'androidx.core:core' has different version for the compile (1.0.0-rc01) and runtime (1.0.2) classpath. You should manually set the same version via DependencyResolution
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2s
> *******************************************************************************************
> The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
> See https://goo.gl/CP92wY for more information on the problem and how to fix it.
> *******************************************************************************************
> Finished with error: Gradle task assembleDebug failed with exit code 1

Interesting ist that I have an old Project where I use both packages together and it works just fine??

I tried both: new project with androidx and without. Still the same thing. 
if you remove one of them the Project compiles

Does anybody know why that is?
___________________________________________________________________________________________________
> [√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.295], locale de-DE)
>     • Flutter version 1.7.8+hotfix.4 at C:\Flutter\flutter\flutter
>     • Framework revision 20e59316b8 (5 weeks ago), 2019-07-18 20:04:33 -0700
>     • Engine revision fee001c93f
>     • Dart version 2.4.0
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at C:\Users\peter\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.5)
>     • Android Studio at C:\Program Files\Android\Android Studio1
>     • Flutter plugin version 38.2.3
>     • Dart plugin version 191.8423
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> 
> [√] VS Code, 64-bit edition (version 1.31.1)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 2.25.1
> 
> [√] Connected device (1 available)
>     • SM G850F • 4100f4474548918d • android-arm • Android 5.0.2 (API 21)
> 
> • No issues found!

**Comment by melwinlobo18** [comment]
It's because of the AndroidX incompatibility. You can read more about the issue and the fix here:

https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

**Comment by pekretsc** [comment]
> 
> 
> It's because of the AndroidX incompatibility. You can read more about the issue and the fix here:
> 
> https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

Hi melwinlobo18
Thanks for the reply:), but I do not think that this is the issue here. At the end of the Artikel there is a list with the latest non AndroidX versions of both. 

image_picker: 0.4.12+1
firebase_storage: 1.0.4

and as I mentioned, my old project that I migrated myself months ago is able to handle both of them together. My guess is that the new sampleproject is configured differently somehow but I just can't figure out where

**Comment by melwinlobo18** [comment]
Sorry about that.:( I had faced the similar problem before but I solved it changing the version. If you find any other solution please do let me know.:)

**Comment by pekretsc** [comment]
Update on the Issue. Igot it to work again by using 
image_picker: 0.5.0 and firebase_storage: 3.0.4 on an androidX project

[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.295], locale de-DE)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.31.1)
[√] Connected device (1 available)

• No issues found!

So this will hopefully be resolved in a new version of imagePicker?!

**Comment by pekretsc** [comment]
Oh and since the issue is not really resolved... Am I supposed to leave this issue open or close it anyways ?

**Comment by pekretsc** [comment]
> 
> 
> Sorry about that.:( I had faced the similar problem before but I solved it changing the version. If you find any other solution please do let me know.:)

No reason to feel sorry, not migrating to androidX throws the same error and it drove me nuts befor ;) too

**Comment by BondarenkoStas** [comment]
@pekretsc Please can you try that latest image_picker (0.6.1) with latest firebase_storage (3.0.6 instead of 3.0.4)? If it doesn't work, I will mark the issue with 'regression' label and it will worth to be open.

**Comment by pinnisi** [comment]
> 
> 
> @pekretsc Please can you try that latest image_picker (0.6.1) with latest firebase_storage (3.0.6 instead of 3.0.4)? If it doesn't work, I will mark the issue with 'regression' label and it will worth to be open.

Hi, I have the same issue with image_picker  0.6.1+4

**Comment by pinnisi** [comment]
changing "implementation 'androidx.core:core:1.0.2'" to 1.0.0 into image_picker's android\build.gradle fixed it for me

**Comment by kroikie** [comment]
@pekretsc

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1076. Any further collaboration will be done there.
