### ISSUE TITLE
Use system ICU on iOS

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#392]
Should reduce our binary size by ~2mb

@chinmaygarde may have thoughts as to how.

**Comment by eseidelGoogle** [comment]
@jason-simmons and @chinmaygarde looked into this some.  The subset Apple exposes isn't the complete set which we depend on.  Notably line-breaking is missing:
https://developer.apple.com/library/ios/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/LowerLevelText-HandlingTechnologies/LowerLevelText-HandlingTechnologies.html

**Comment by Hixie** [comment]
Currently our target platforms just don't give us what we need to solve this.
