### ISSUE TITLE
How to create map data and  fill data to 4 top tabbar pending cancelled .. from api with this json 

### ISSUE THREAD

**Issue by nguyentrunghieutcu** [flutter/flutter#39204]
{
    "count": 12,
    "data": {
        "Pending": [{},{}],
        "Cancelled": [{},{}],
        "Completed": [{},{}],
        "Processing": [{},{}]
    }
}
Service Api :
 

> @override
>   Future<Orders> getAdminOrders({UserAdminModel userModel}) async {
>     try {
>       var response =
>           await http.get("https://$subDomainAdmin.$domain/orders", headers: {
>         "content-type": "application/json",
>         "lang": 'vi',
>         "X-Requested-With": 'XMLHttpRequest',
>         "Authorization": 'Bearer ' + token
>       });
>       final body = convert.jsonDecode(response.body);
>       Orders orders;
>       if (response.statusCode == 200) {
>         orders =  Orders.fromJson(body);
>       }
>       return orders;
>     } catch (err) {
>       throw err;
>     }
>   }

My tab ui 
![Screen Shot 2019-08-25 at 16 27 35](https://user-images.githubusercontent.com/24294935/63648125-5133af00-c755-11e9-8211-174e75860283.png)

**Comment by Levi-Lesches** [comment]
Sorry, what exactly are you asking? 

Also, this is a question better suited for [StackOverflow](https://stackoverflow.com/), since there doesn't seem to be anything wrong with Flutter itself.

**Comment by stuartmorgan** [comment]
Closing, as this is not an issue report. See https://flutter.dev/community for support options.

**Comment by Levi-Lesches** [comment]
If you want additional help now that it's closed, just post it on StackOverflow and put the link here so I can follow up.

**Comment by nguyentrunghieutcu** [comment]
> If you want additional help now that it's closed, just post it on StackOverflow and put the link here so I can follow up.

thanks

**Comment by Levi-Lesches** [comment]
...did you do it yet?
