### ISSUE TITLE
 authentication problem

### ISSUE THREAD

**Issue by ameennio** [flutter/flutter#39209]
Am developing blood donation app. I have 3 different users: admin , user and blood center. The problem when I login to the app idk how to tell the app is this user or admin or blood center becz every one has different functions. So there’s any idea to solve this problem

**Comment by Levi-Lesches** [comment]
You could have a list in your database denoting which UIDs are in which group. Or, if you're using FirebaseAuth, you could use [custom claims](https://firebase.google.com/docs/auth/admin/custom-claims)

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
