### ISSUE TITLE
It can provide functions similar To Android 'Go To XML'，find widget quickly,it will be easy to develop and maintain code.

### ISSUE THREAD

**Issue by Juneor** [flutter/flutter#39219]
It can provide functions similar To Android 'Go To XML'，find widget quickly,it will be easy to develop and maintain code.

**Comment by andrijasinski** [comment]
Please, provide more context about this issue/request.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
