### ISSUE TITLE
"type 'int' is not a subtype of type 'String'" during app execution without context

### ISSUE THREAD

**Issue by hasen6** [flutter/flutter#39229]
I often see this error and it leaves me puzzled since most errors give a line number where the error actually occurs. All I get is:

`I/flutter (27667): Another exception was thrown: type 'int' is not a subtype of type 'String'`

How am I supposed to fix an error like this when I've no idea where in the code it occurs?

**Comment by aneeshjose** [comment]
Could you please post your code?

**Comment by hasen6** [comment]
No because I don't know where in the code the error is referring to. That's exactly the problem...it doesn't indicate where the error is whatsoever.

**Comment by aneeshjose** [comment]
Then please post the error message fully and mention the 'filename'.dart you are working on.

**Comment by hasen6** [comment]
I don't think you understand what I'm saying at all. That is the entire error message! That's the point. That's what the problem is.

**Comment by aneeshjose** [comment]
I understand that you were trying to point out a bug in flutter. My intention was to help you in fixing the code, if there were any, that I could help you with.

**Comment by hasen6** [comment]
Yes I realise you're trying to help but you don't seem to have understood my original post at all. My problem is that that is the ENTIRE error message. It's that the error message did not give any more information, nor did it tell me where in my code the error occurred.

Your response was to ask for the whole error message...and where in the code it occurred...!

 If I knew that it wouldn't have been a problem in the first place...

**Comment by christopherfujino** [comment]
@hasen6 Is this error still occurring? If so, could you try running your app with `flutter run -v` and see if that surfaces more logs?

**Comment by jonahwilliams** [comment]
Without any response we're unable to make progress here
