### ISSUE TITLE
Visual explanation for State object lifecycle

### ISSUE THREAD

**Issue by mtcliatt** [flutter/flutter#39227]
The docs for the [State class](https://api.flutter.dev/flutter/widgets/State-class.html) uses a lengthy bulleted list to describe the lifecycle of State objects. Some users, especially those who are visual learners, may benefit from a diagram detailing the lifecycle.

**Comment by 120011676** [comment]
Missing widget exit (navigator. Push), return (navigator. Pop), background operation, foreground obfuscation, lifecycle method

**Comment by goderbauer** [comment]
Duplicate of https://github.com/flutter/flutter/issues/13615.
