### ISSUE TITLE
problem when starting flutter web debugging

### ISSUE THREAD

**Issue by ocelili** [flutter/flutter#39224]
when I try to start debugging flutter web using vscode, the debug console only arrives ..
```[INFO] Connecting to the build daemon... 

[INFO] Generating build script...
[INFO] Generating build script completed, took 2.1s
[INFO]
[INFO] Daemon is already running.
[INFO] Registering build targets...
[INFO] Starting initial build...
[INFO] Starting resource servers...
[INFO] Serving DevTools at http://127.0.0.1:55069
[INFO] Serving `web` on http://127.0.0.1:55066
[INFO] About to build [web]...
[INFO] Running build...
[INFO] Running build completed, took 298ms
[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 697ms
[INFO] Succeeded after 1.0s with 0 outputs (0 actions)
[INFO] Debug service listening on ws://localhost:55096/Hc6Z4lcC6_o=
```

and the notification pop up is only until launching, after that it's finished and the display in the browser is only white

**Comment by andrijasinski** [comment]
Hi @ocelili, can you provide more information about your flutter env with `flutter doctor -v` output and if you have tried to debug this issue yourself?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
