### ISSUE TITLE
languageCode always return en on iOS, works on Android.

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter#39230]
I'm coming from [here](https://github.com/flutter/flutter/issues/26382#issuecomment-516356096)

## Steps to Reproduce
```
void main() => runApp(MaterialApp(home: HomePage()));

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Builder(
        builder: (newContext) {
          return Center(
            child: Text(
              // always shows `en` in iOS and works fine in Android
              window.locale?.languageCode ?? "Searching",
              style: Theme.of(context).textTheme.headline,
            ),
          );
        },
      ),
    );
  }
}

```

The above print statement always show `en` on iOS no matter what locale you have selected. I did full start of the application after stopping the ongoing process. Tested it on Simulator and iPhone 6s real device, both show `en`, however this code works fine in Android emulator and Samsung Galaxy S8+ real device. 

### Flutter doctor
```
[✓] Flutter (Channel dev, v1.8.3, on Mac OS X 10.14 18A389, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by amreniouinnovent** [comment]
@dark-chocolate in iOS I think there is a place in .plist file to add languages..did you added it in .plist in xcode?

**Comment by dark-chocolate** [comment]
@amreniouinnovent  I am not aware of anything like that, I am from Android side, not much familiar with iOS and Xcode, can you guide me where to add that file?

**Comment by amreniouinnovent** [comment]
@dark-chocolate check last section
https://flutter.dev/docs/development/accessibility-and-localization/internationalization#appendix-updating-the-ios-app-bundle

**Comment by dark-chocolate** [comment]
OK, thanks a lot. I am not in front of my system, so I am not able to test it out, however I am sure this would solve the problem so I am closing this issue now. In case it didn't solve, I'll reopen it.
