### ISSUE TITLE
Using a custom font crashes the app

### ISSUE THREAD

**Issue by boylenssen** [flutter/flutter#39233]
Only found this [issue](https://github.com/flutter/flutter/issues/19452), but the solution there was removing spaces.

I'm using the latest Flutter version Flutter 1.7.8+hotfix.4, downloaded it freshly again, tried on iOS simulator, Android emulator and a real device.

I get the same error:

> E/flutter (18374): [ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
E/flutter (18374): 
E/flutter (18374): [ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
E/flutter (18374): 
F/flutter (18374): [FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
F/libc    (18374): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 18440 (1.ui), pid 18374 (r_app_font_test)

Attached a minimum app which produces this error.

[flutter_app_font_test.zip](https://github.com/flutter/flutter/files/3540428/flutter_app_font_test.zip)

**Comment by boylenssen** [comment]
The fonts were not ok. They were shortcuts instead of real files #facepalm

**Comment by jhionan** [comment]
Removing spaces worked for me!,  Thank you very much
