### ISSUE TITLE
[Feature Request] CupertinoTimerPicker 24 hour format

### ISSUE THREAD

**Issue by keshava19** [flutter/flutter#39238]
## Use case

I want time with AM/PM in the CupertinoTimerPicker in our application.

## Proposal

In the CupertinoTimerPicker add the option for 24 hour format to be able to do it.

![image](https://user-images.githubusercontent.com/19950180/63687970-af2ec800-c823-11e9-819e-9825af350c3e.png)

**Comment by keshava19** [comment]
I wanted to use that  `CupertinoDatePicker` but it did limit the time, so I went with `CupertinoTimerPicker` and function to limit the selection.

**Comment by keshava19** [comment]
Yes it's a workaround for that issue.

**Comment by kerberjg** [comment]
@LongCatIsLooong AM/PM is absolutely not the only time format used for wall time.

Most countries in the world actually use the 24h format, and I can assure you that iOS does too, if the user so prefers, so it makes sense for CupertinoTimerPicker to include this option. Screenshots included

![IMG_4046](https://user-images.githubusercontent.com/16939117/63978855-b8d05e00-cab7-11e9-8856-b3aca49a73c8.PNG)
![IMG_4047](https://user-images.githubusercontent.com/16939117/63978872-c1289900-cab7-11e9-8e57-4e7c3d36cdbc.PNG)

I'm planning on working on a PR for #34951 and #24820 after I'm done with #38194, I could do this afterwards.

PS: @keshava19 I didn't think using it as a workaround, thanks for the idea!

**Comment by LongCatIsLooong** [comment]
@kerberjg what I meant was "AM/PM" is a notation for wall time and thus doesn't make sense for a count down timer. `CupertinoTimerPicker` (as well as `UIDatePicker`'s count down timer mode) is essentially a count down timer so it shouldn't have the "AM/PM" column. The `CupertinoDatePicker` does have a [`use24hFormat`](https://api.flutter.dev/flutter/cupertino/CupertinoDatePicker/use24hFormat.html) option.

**Comment by LongCatIsLooong** [comment]
I'm going to start working on https://github.com/flutter/flutter/issues/34951. Closing this in favor of #34951.
