### ISSUE TITLE
[web] Minification interferes with generic functions

### ISSUE THREAD

**Issue by CiriousJoker** [flutter/flutter#39248]
**TLDR:**

Minification changes generic type names which could lead to problems if they're hardcoded.

**Example code:**

```
void doSmth<T>() {
    switch(T) {
      case A:
        // This will never be reached since during runtime,
        // T might be mB or some other minified string
        doSmthElse();
        break;
    }
}

doSmth<A>();
```

**Proposed solution:**
Don't minify generic type names.

**Workaround:**
I can imagine that this can be worked around using enums as types, but my switch statement is quite large and I would rather not refactor all the code.

**Comment by CiriousJoker** [comment]
I just read that dart2js has different minification options, but I can't figure out how to make use of them since I can only pass parameters to webdev itself.

**Comment by yjbanov** [comment]
This looks like a compiler bug. /cc @vsmenon

**Comment by vsmenon** [comment]
dart2js bug is here:

https://github.com/dart-lang/sdk/issues/38005
