### ISSUE TITLE
run  error  

### ISSUE THREAD

**Issue by joucksHua** [flutter/flutter#39242]

**Comment by andrijasinski** [comment]
@joucksHua Can you provide more information f.e. `flutter doctor -v` output as well as full stack trace for your issue.

**Comment by AdoBeatTheWorld** [comment]
这个应该是 StatefulWidget 的使用问题，看下堆栈应该可以看出来是哪个组件的问题；
自定义的StatefulWidget需要：
`
 @override
  State<StatefulWidget> createState() => _XXXState();
`
