### ISSUE TITLE
OOM after approximately 15-20 user invocations of a feature

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#39249]
Mirror issue for https://b.corp.google.com/issues/139666100. Comments should occur there.

**Comment by Hixie** [comment]
@rmacnak-google Any news?

**Comment by rmacnak-google** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/114721 + https://dart-review.googlesource.com/c/sdk/+/114722
