### ISSUE TITLE
Error: Unable to Update Dart SDK. Retriyng...

### ISSUE THREAD

**Issue by Zefyrrrr** [flutter/flutter#39243]
![Sem título](https://user-images.githubusercontent.com/54542206/63697209-d9b45d00-c7f2-11e9-8fd3-90507496486b.png)

**Comment by andrijasinski** [comment]
Hi @Zefyrrrr. Can you provide more information regarding your issue (preferably in a text way) and if or how you have tried to fix it.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by chjsoliveira** [comment]
Verify that powershell is installed and set in the system variables in Path as follows:
"% SYSTEMROOT% \ System32 \ WindowsPowerShell \ v1.0 \"
