### ISSUE TITLE
Strange bug with builders key on pubspec

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#39256]
From https://github.com/dart-lang/build/issues/2422.

> Below pubspec uses `builders` key so flutter run will watch and generate mobx code.
> 
> But all of sudden it stoped working. When I rename folder it starts working. I have tired reinstalling flutter, do flutter clean. Remove ~/.pub-cache.
> 
> ```
> name: yala
> description: SME Payment App
> 
> version: 1.0.0+1
> 
> environment:
>   sdk: ">=2.2.0 <3.0.0"
> 
> builders:
>   mobx_codegen: ^0.3.5
> 
> dependencies:
>   flutter:
>     sdk: flutter
>   cupertino_icons: ^0.1.2
>   flutter_hooks: ^0.6.0
>   graphql_flutter: ^2.1.0
>   mobx: ^0.3.6
>   flutter_mobx: ^0.3.1+1
>   back_button_interceptor: ^4.0.9
>   shape_of_view: ^1.0.1
>   page_transition: ^1.1.4
>   animated_card: ^1.0.0+6
>   sliver_animated_list: ^0.0.1+1
>   rect_getter: ^0.0.1
>   locales: ^0.1.0
>   intl: ^0.15.8
>   enum_to_string: ^1.0.7
>   bezier_chart: ^1.0.14
>   after_layout: ^1.0.7+2
>   provider: ^3.1.0
>   dotted_border: ^1.0.2
> 
> dev_dependencies:
>   build_runner: ^1.6.7
> 
> flutter:
>   uses-material-design: true
> 
>   assets:
>     - assets/images/
> ```
> 
> Thx

**Comment by jascodes** [comment]
@jonahwilliams Its not generating code without error but if I remove/rename project folder it starts working again. Is there something flutter run globally cache. I even reinstalled flutter from stcrach and remove .pub-cache, as well as other temp folders in the project.
Thx

**Comment by jascodes** [comment]
I understand.. but can provide me list of places which flutter and/or dart use to persist anything say cache,log etc. I think I might have missed something...

Thx

**Comment by jascodes** [comment]
didn't had problem again, don't know what was wrong with that folder,
feel free to close.
