### ISSUE TITLE
i cant run flutter app on android 8

### ISSUE THREAD

**Issue by mehdidavarpanah66** [flutter/flutter#39255]
```
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install G:\flutter_project\f_project\asas\build\app\outputs\apk\app.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl592356915.tmp/base.apk: AndroidManifest.xml]
Error launching application on SM J730F.
```

**Comment by andrijasinski** [comment]
@mehdidavarpanah66 can you give steps to reproduce as well as your flutter env config (`flutter doctor -v`) and specs of your device.

**Comment by mehdidavarpanah66** [comment]
yes every things is ok and i can run on other real phone but when run in my phone i have error

**Comment by BondarenkoStas** [comment]
Please, can you give steps to reproduce as well as your ```flutter doctor -v``` output and specs of your device? Currently it's not possible to investigate the issue as it's not clear where to start

**Comment by mehdidavarpanah66** [comment]
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install G:\flutter_project\f_project\asas\build\app\outputs\apk\app.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl1154459958.tmp/base.apk]
Uninstalling old version...
Installing build\app\outputs\apk\app.apk...
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install G:\flutter_project\f_project\asas\build\app\outputs\apk\app.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl2061563969.tmp/base.apk]
Error: Failed to install APK again.
Error launching application on SM J730F.

**Comment by mehdidavarpanah66** [comment]
this is my error in top but my android version is 9

**Comment by mehdidavarpanah66** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.7.8, on Microsoft Windows [Version 6.3.9600], locale fa-IR)
[!] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

    X No valid Android SDK platforms found in C:\Users\ASUS\AppData\Local\Android\Sdk\platforms. Directory was empty.
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
[√] Android Studio (version 3.4)
[√] Connected device (3 available)

**Comment by mehdidavarpanah66** [comment]
i want use my phone as emulator

**Comment by BondarenkoStas** [comment]
Error says: Failed to parse /data/app/vmdl592356915.tmp/base.apk: AndroidManifest.xml. So there may be something wrong with it. Can you please provide your AndroidManifest.xml?
And in general, this question is better suited for StackOverflow as it seems not to have anything wrong with flutter itself.

**Comment by mehdidavarpanah66** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.partopars.www.Asas">

    
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="asas"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
    </application>
</manifest>

**Comment by BondarenkoStas** [comment]
Check please https://developer.android.com/guide/topics/manifest/manifest-intro and https://developer.android.com/guide/topics/manifest/manifest-element.

Probably it can't parse as ```<?xml version="1.0" encoding="utf-8"?>``` and ```<manifest>``` outer tags are missed.

**Comment by mehdidavarpanah66** [comment]
this taqg already existed but i forget copy that

**Comment by mehdidavarpanah66** [comment]
somtimes  i can run and many time i have error

**Comment by jonahwilliams** [comment]
Without more information we're unable to make any progress here. I did find https://stackoverflow.com/questions/31911149/adb-install-parse-failed-unexpected-exception which suggests that uninstalling the app could help
