### ISSUE TITLE
[web]: Safari is blank when Cupertino font is included 

### ISSUE THREAD

**Issue by QuattroNinos** [flutter/flutter#39259]
Using the unforked version of Flutter for web:
flutter channel master
flutter upgrade --force
flutter create web .
flutter run (just to verify in chrome)
flutter build web

Works in Chrome and Firefox, but Safari is a blank white window. The Safari JavaScript console shows a bunch of errors.

After removing the references to Cupertino icons and fonts, it loads in Safari.  Specifically,
- Remove all references to Cupertino in
  - build/web/assets/AssetManifest.json
  - build/web/assets/FontManifest.json
- Delete build/web/assets/packages/cupertino_icons/assets/CupertinoIcons.ttf

**Comment by suhmeanhuck** [comment]
I have the exact same issue **only on Safari**. Firefox, Microsoft Edge, and Chrome are all working perfectly. I tried to delete the font weights using bold and deleting Cupertino icons and fonts to no effect. Sorry for the duplicate comment, I didn't know whether to comment here or #35982 

Safari Console:

[Error]
$0 (main.dart.js:34302)
aWS (main.dart.js:4369)
aXa (main.dart.js:4371)
$1 (main.dart.js:33185)
aYZ (main.dart.js:2806)
(anonymous function) (main.dart.js:2814)

Flutter Doctor -v report:

[✓] Flutter (Channel beta, 1.22.0, on Mac OS X 10.15.5 19F101, locale en-US)
• Flutter version 1.22.0 at /Users/redacted/Downloads/flutter
• Framework revision d408d30 (5 months ago), 2020-09-29 11:49:17 -0700
• Engine revision 5babba6c4d
• Dart version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /Users/redacted/Library/Android/sdk
• Platform android-29, build-tools 29.0.2
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.5, Build version 11E608c
• CocoaPods version 1.10.1

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 49.0.1
• Dart plugin version 192.8052
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
• iPhone 8 (mobile) • D0C7B53E-F48C-41CA-804D-2FB21EF32023 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
• Web Server (web) • web-server • web-javascript • Flutter Tools
• Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.192

• No issues found!

**Comment by ditman** [comment]
@suhmeanhuck this issue was closed over a year ago. Can you please [create a new issue](https://github.com/flutter/flutter/issues/new/choose)? Otherwise, nobody will be able to help you with your issue.
