### ISSUE TITLE
[web]: Roboto-Regular.ttf is a dependency, but not included in the default Flutter for web project

### ISSUE THREAD

**Issue by jkurtw** [flutter/flutter#39260]
Using unforked Flutter for web:
flutter channel master
flutter upgrade --force
flutter create web .
flutter run (just to verify in chrome)
flutter build web
Remove references to Cupertino as in https://github.com/flutter/flutter/issues/39259

Open in Safari. Look at the errors and see it is trying to load Roboto-Regular.ttf, which is not included in the build.

**Comment by yjbanov** [comment]
/cc @hterkelsen 

I'm not sure we should special-case Roboto in the engine. We should probably ask that users provide fonts they want to use. However, for convenience, we might want `flutter create web` to provide Roboto. @jonahwilliams WDYT?

**Comment by jonahwilliams** [comment]
There is no distinct `flutter create web`, only a single flutter template that optionally includes platform support. If we added roboto for the web, it would be added to all (and we would be required to ship it with the flutter sdk)

**Comment by yjbanov** [comment]
@hterkelsen does Chrome bundle Roboto? Is that why we have https://github.com/flutter/engine/blob/fad38e252f0748d49471bf2e09a2eb74ea04ce0b/lib/web_ui/lib/src/engine/text/font_collection.dart#L59?

**Comment by hterkelsen** [comment]
Yes, Chrome bundles Roboto, so we added that as an optimization.

**Comment by jonahwilliams** [comment]
I pointed this out in the chat but I think the logic there is a bit backwards. it should remove the network request for Roboto on chrome, instead of adding one on non-chrome browsers. Even if we included Roboto in the default template, we don't want to require users to ship Roboto to avoid odd network request failures in their app.

**Comment by yjbanov** [comment]
According to @ditman's research, this is not Chrome, but the OS. If the OS bundles Roboto, so does Chrome. So it looks like we'll need a new strategy.
