### ISSUE TITLE
How set velocity in ListView 

### ISSUE THREAD

**Issue by Hellomik2002** [flutter/flutter#39273]
I want to set Velocity of LitsView, can someone explain how to do it? I met this question here but noOne answered https://stackoverflow.com/questions/51261935/flutter-how-to-controll-the-velocity-of-a-listview-builder#new-answer

**Comment by mannprerak2** [comment]
You can create a Scroll Position 
and then maybe toggle the ensureVisible() property of that scroll position object.

I don't know if this will work but try this

**Comment by BondarenkoStas** [comment]
Closing, as this is not an issue report and doesn't point on anything wrong with flutter itself. See https://flutter.dev/community for more support options.
