### ISSUE TITLE
Migrate the engine to AndroidX

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#39283]
Internal: b/144623948

The engine is still using the support libraries.  Now, that we generate Maven artifacts, we can update the engine dependencies: https://github.com/flutter/engine/blob/3103499019d4b5235b44806a3ea387e1dca5c66a/tools/android_support/files.json

**Comment by xster** [comment]
@shihaohong are we actually conceptually depending on SDK 29 now via https://github.com/flutter/buildroot/pull/291? If so, this is a good reason to try to migrate earlier rather than later.

**Comment by shihaohong** [comment]
@xster Yes, the engine depends on Android SDK 29 now
