### ISSUE TITLE
Flutter command to initialize Firebase

### ISSUE THREAD

**Issue by Levi-Lesches** [flutter/flutter#39290]
## Use case

Adding Firebase to a Flutter project is a little confusing for beginners. A command like `flutter firebase` would be MUCH easier. 

## Proposal

Behavior for typing in `flutter firebase` would differ depending on whether Firebase changes to officially support Flutter in a truly cross-platform manner:

- If Firebase were to support this: The Firebase SDK console would give a JSON file to download that contains all the data necessary for making both `google-services.json` and `GoogleService-Info.plist`. Running `flutter firebase` would simply populate both the `android` and `ios` folders with the necessary files. Additionally, the all-inclusive file offered by Firebase could be downloaded to the `lib` folder, and automatically put in the `.gitignore`.
- If Flutter were to go independently: The user could download both the JSON and `plist` files from the Firebase console and typing in `flutter firebase` with paths to both would do the rest.

**Comment by mannprerak2** [comment]
> If Flutter were to go independently: The user could download both the JSON and plist files from the Firebase console and typing in flutter firebase with paths to both would do the rest.

This would make a good package, you can create a command-line tool to do this.
I don't think they will consider adding a `flutter firebase` command as such, 
the Flutter CLI is meant only for things/setup related directly to flutter.

**Comment by mannprerak2** [comment]
If you really think about it, it's not much work, and
- We only need to do this once per project
- We have to further setup other stuff (other firebase sub-modules which we require) which is via the Firebase Console only
- With Flutter being even more cross-platform soon, setup for android, iOS, Web and Desktop would be different and users will only setup the stuff they are targetting.
- And as pointed out earlier, it's better to keep flutter CLI separate from additional Firebase related commands

However, you can try putting an issue on the firebase repo to treat flutter as a first-class platform, that has a **completely different setup for Firebase specific to Flutter** (which internally automatically maps to the setup for the underlying platform).

**Comment by mannprerak2** [comment]
Well, just explain your use case properly, and how it will benefit firebase users and make it more accessible to beginners. Optionally include a proposal about what you think would be a good workflow for the setup. That seems good enough. 
Put a reference to that issue here as well, before closing this issue.

**Comment by Levi-Lesches** [comment]
I couldn't find a GitHub repo to post an issue, so I sent a (private) feature request instead. Do you know of a GitHub repo to post on?

**Comment by mannprerak2** [comment]
The flutter/plugins repo doesn't seem to have an option for posting an issue. So i guess this repo is a good place for this issue..

**Comment by Levi-Lesches** [comment]
Ok, since I already sent the feature request (with a link here), and there is nothing left for the Flutter team to do (unless *they* want to help make the package?...), I'm just gonna close this and update if/when I finish.
