### ISSUE TITLE
Stop users from closing bottom sheet. Disable drag and touch outside bottom sheet region

### ISSUE THREAD

**Issue by saurav12** [flutter/flutter#39297]
## Use case
There should be a `BottomSheet` which cannot be dragged by a user swipe of touch. This can be achieved using BottomSheet widget on Scaffold. But while calling `showModalBottomSheet` currently, there is no option to disable the `enableDrag` property. Which is not exposed to line `297` of `bottom_sheet.dart`:
```
child: CustomSingleChildLayout(
  delegate: _ModalBottomSheetLayout(animationValue, widget.isScrollControlled),
  child: BottomSheet(
    animationController: widget.route._animationController,
    ...
```

## Proposal
I'd suggest exposing the `enableDrag` property to the BottomSheet can fix the issue, Like:
```
child: CustomSingleChildLayout(
  delegate: _ModalBottomSheetLayout(animationValue, widget.isScrollControlled),
  child: BottomSheet(
    animationController: widget.route._animationController,
    enableDrag: widget.enableDrag  // Adding this line
    ...
```

**Comment by saurav12** [comment]
> This seems like a reasonable feature to add. Would you be interested in submitting a pull request that implements it (along with tests/doc)?

Ya, I'd love to contribute. I'll be submitting a pull request soon (along with test/doc).

**Comment by saurav12** [comment]
I've created a PR for this issue. Can someone please tell me what test cases should I cover in this?

**Comment by nickpnmrv** [comment]
Hey there, so what would be a solution to prevent the user from closing the modal bottom sheet?

**Comment by saurav12** [comment]
> Hey there, so what would be a solution to prevent the user from closing the modal bottom sheet?

Check this PR description.

**Comment by nickpnmrv** [comment]
> > Hey there, so what would be a solution to prevent the user from closing the modal bottom sheet?
> 
> Check this PR's description.

Hey @saurav12 , thanks for your prompt reply. The question had to be set differently: what is the work around until your PR approved? I do not want to make changes to any Flutter code, it will be overridden with the next update...

**Comment by saurav12** [comment]
> Hey @saurav12 , thanks for your prompt reply. The question had to be set differently: what is the work around until your PR approved? I do not want to make changes to any Flutter code, it will be overridden with the next update...

There are some testing cases which are still pending. If you know to write test cases, you can contribute.

**Comment by shihaohong** [comment]
Since https://github.com/flutter/flutter/pull/46685 has been merged, I believe that this can be closed out now.

**Comment by jeshpren** [comment]
I need to use the "controller = _scaffoldKey.currentState.showBottomSheet<Null>(..." implementation of bottomsheet, because I need to close it programmatically.
Is there a way to set "enableDrag = false" when using bottom sheet like I am?
