### ISSUE TITLE
flutter analyze crashes if you have two pubspec.yamls with the same package name

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3929]
We call:

``` dart
dependencies.addCanonicalCase(packageName, packagePath, pubSpecYamlPath);
```

...without first checking that `packageName` isn't already registered. Thus we then assert on:

``` dart
  void addCanonicalCase(String packagePath, String pubSpecYamlPath) {
    assert(canonicalSource == null);
    add(packagePath, pubSpecYamlPath);
    canonicalSource = pubSpecYamlPath;
  }
```

This is easy to reproduce. Copy an existing directory in the repo to add a new example, and then run `flutter analyze` before you update the new `pubspec.yaml` file to have a different name.

**Comment by gspencergoog** [comment]
This appears to be fixed.
