### ISSUE TITLE
Internationalisation (i18n)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#393]
We need to go through the following steps to make sure Flutter is positioned to handle i18n needs in the future:
- [ ] Get a list of tricky issues that affect localisation (strings with numbers, strings with user-generated content, people's names, locale-specific CJK characters, etc)
- [ ] Add features to the Stocks app to exercise all these issues.
- [ ] Add support for on-the-fly changing the language of the Stocks app to Arabic.

**Comment by eseidelGoogle** [comment]
https://pub.dartlang.org/packages/intl may provide some help at least.

**Comment by eukreign** [comment]
Will it support services such as transifex.com or oneskyapp.com out of the box?

Integration with gettext would be pretty useful. Even if gettext isn't used on the mobile device, being able to generate .pot and merge .po files would be pretty nice in working with existing translation tools.

**Comment by eseidelGoogle** [comment]
To follow up on my earlier suggestion to use package:intl.  It does work.  However there are currently two large known drawbacks:
1.  package:intl doesn't integrate with iOS or Android translation systems (so you can't currently use translations from 3rd-party packages for example.
2.  package:intl currently stores strings as compiled .dart code, which means that all of your translation strings end up compiled into your application binary (and thus the App stores don't know how to filter out languages not needed for a specific install, etc.)
I expect we'll fix both of the above as part of resolving this cluster of bugs.

**Comment by Hixie** [comment]
Our current plan is to start working on this in the first week of August; full support will take a few months but basic support should be ready to test a few weeks after we start.

**Comment by Hixie** [comment]
Closing in favour of the project which is tracking individual bugs.
