### ISSUE TITLE
cupertino_icons is not all

### ISSUE THREAD

**Issue by jsu93** [flutter/flutter#39308]
![](https://raw.githubusercontent.com/flutter/cupertino_icons/master/map.png)

just a few icons in the icons.dart, not all in the above.

This is just a case that not completed for the flutter package. and so many package is not completed.

**Comment by HansMuller** [comment]
CC @willlarche

**Comment by jsu93** [comment]
maybe we can just write a script loop the icons to the icons.dart, not naming every icon

**Comment by xster** [comment]
Merging into #16102
