### ISSUE TITLE
Feature Request for Alarm Manager running status.

### ISSUE THREAD

**Issue by GadepalliAditya1998** [flutter/flutter#39314]
Need API for knowing whether the alarm is running or not, when it scheduled.

**Comment by GadepalliAditya1998** [comment]
Even when the alarm is started or cancelled, The API returns true which is supposed to be the actual status (true/false). Please event fix it.

**Comment by GadepalliAditya1998** [comment]
I have added this API, could any one verify it?

**Comment by GadepalliAditya1998** [comment]
May be i will be having issue with pull request as i dont have a mac machine

**Comment by GadepalliAditya1998** [comment]
Hey Ben , I even need your help in geofencing

**Comment by GadepalliAditya1998** [comment]
iam facing this issue

[image: image.png]

**Comment by GadepalliAditya1998** [comment]
Hey @bkonyi , My pull request is getting failed every time. Because of the Build issue. Can you suggest me any way?

**Comment by estevez-dev** [comment]
That is awesome! Thanks @GadepalliAditya1998 . Could we have a link to your PR?

**Comment by GadepalliAditya1998** [comment]
Hey,

I just signed the petition "CM Devendra Fadnavis, JICA Stop the cutting of
3500 trees in Aarey Forest" and wanted to see if you could help by adding
your name.

Our goal is to reach 500,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/CYx7YKJtms

Thanks!
Aditya

**Comment by stuartmorgan** [comment]
Closing as `android_alarm_manager` is deprecated in favor of [`android_alarm_manager_plus`](https://pub.dev/packages/android_alarm_manager_plus).
