### ISSUE TITLE
Google Oauth give additional scope when app request login

### ISSUE THREAD

**Issue by telinx** [flutter/flutter#39325]
Our app uses google Oauth for app user to sign in. We only request basic scopes. We didn't request contact scope. But when user sign it, it ask user to allow this app to see and download contacts. Attached are screenshot links from console and mobile, can't post images yet. Any help?
dependencies: google_sign_in: ^4.0.1+3
![ Image Text](https://i.stack.imgur.com/yLzOp.jpg)
![ Image Text](https://i.stack.imgur.com/4HMaS.jpg)

**Comment by TahaTesser** [comment]
Hi @telinx 
Are you still experiencing this issue?
Thank you

**Comment by telinx** [comment]
> Hi @telinx
> Are you still experiencing this issue?
> Thank you

google oauth don't to get contacts
```
GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: <String>[
    'email',
    'https://www.googleapis.com/auth/contacts.readonly',   // delete this line 
  ],
);
```
