### ISSUE TITLE
Bad error message when there's a signing error for iOS

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3933]
```
%flutter install                              [/src/flutter/examples/flutter_gallery]
Installing io.flutter.gallery to iPhone...
Uploading .generated package contents... DONE.
Installing '(null)'
 - CreatingStagingDirectory (5%)
 - ExtractingPackage (15%)
 - InspectingPackage (20%)
 - Error occurred: PackageInspectionFailed
```

```
%flutter doctor                               [/src/flutter/examples/flutter_gallery]
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /src/flutter
    • Framework revision c5ff156f24 (20 minutes ago), engine revision a1f4a12baa

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/eseidel/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

@devoncarew @chinmaygarde

**Comment by eseidelGoogle** [comment]
`flutter run` also failed on this device https://gist.github.com/eseidelGoogle/9e2a11443c2ad6ba91f81ad7cde77f63

**Comment by eseidelGoogle** [comment]
Even if I did something wrong, I would like to tools to explain it better. :)

**Comment by chinmaygarde** [comment]
The gist indicates a code signing error. Will make it clearer.

**Comment by sethladd** [comment]
(making it clearer that the problem is a signing issue should help https://github.com/flutter/flutter/issues/2952 too

**Comment by Hixie** [comment]
Leaving in current milestone because everyone tries to publish on iOS, and anyone who tries to publish on iOS runs into error messages about signing, and so they're likely to run into this.

**Comment by eseidelGoogle** [comment]
@xster did a ton of work on this last fall.  I don't know what the current status of this is.  I'm sure there are still better things we could do here. :/

**Comment by xster** [comment]
We specifically check for build time messages like ios-deploy[49239:3898442] [ !! ] Error 0xe8008015 and show a user digestible message now. Should also less likely happen in the first place with automatic signing.
