### ISSUE TITLE
uid isn't defined for the class 'AuthResult'.

### ISSUE THREAD

**Issue by ameennio** [flutter/flutter#39331]
```The getter 'uid' isn't defined for the class 'AuthResult'.
Try importing the library that defines 'uid', correcting the name to the name of an existing getter, or defining a getter or field named 'uid'.dart(undefined_getter)
```

this the problem i cant assign the uid to the currentUser

![Capture](https://user-images.githubusercontent.com/53660430/63785693-57778600-c923-11e9-9c8e-1692e6fa99fa.PNG)

**Comment by andrijasinski** [comment]
From `AuthResult` object call `getUser` function (see https://firebase.google.com/docs/reference/android/com/google/firebase/auth/AuthResult#public-method-summary), which will return you `FirebaseUser` object and use `getUid` function on that (see https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser.html#public-method-summary). Hope it helps!
