### ISSUE TITLE
 FlutterCompositor doesn't use the FlutterTransformation provided by the FlutterRendererConfig

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#39339]
Mirror issue for https://b.corp.google.com/issues/139758641. Discussions should occur there, please.

Assigning to @chinmaygarde as he's currently working the issue on the Google tracker. Chinmay, can you comment as to whether or not this is a blocker?

**Comment by chinmaygarde** [comment]
Fixed in https://github.com/flutter/engine/pull/11384
