### ISSUE TITLE
Camera Escura Moto C

### ISSUE THREAD

**Issue by VictorsAlves** [flutter/flutter#39334]
The Camera Goes Dark on Moto C.

When comparing the operating system camera quality with the floating camera package quality, you see the poor quality, especially in dark places, meaning the camera gets a lot worse than the "native" quality.

**Comment by VictorsAlves** [comment]
The Camera Goes Dark on Moto C.

When comparing the operating system camera quality with the floating camera package quality, you see the poor quality, especially in dark places, meaning the camera gets a lot worse than the "native" quality.

**Comment by TahaTesser** [comment]
Hi @VictorsAlves 
if you're still experiencing this problem with latest stable, please create a new issue and provide the information required in the template.
Thank you
