### ISSUE TITLE
[web][upstream] Upstream new platform messages for text editing

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#39343]
PR coming...

**Comment by lesnitsky** [comment]
@mdebbar @stuartmorgan are there any plans to unify text editing on desktop and web? 
as mentioned in #39344
> we place a transparent DOM input field right on top of flutter's text field
is this really the best way to achieve all necessary goals?

Sorry if my question is completely irrelevant, I know you guys are knowledge owners and have your reasons for such kind of decisions :)
