### ISSUE TITLE
Textures should fail with a better error message when using software rendering

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#39348]
Right now it just crashes when it tries to use a gl context that was never initialized, the error message should explicitly say that textures cannot be used with software rendering.

**Comment by chinmaygarde** [comment]
Can you specify the platform you saw this on? On a related note, we seem to be doing this in a platform specific manner today, we should probably refactor this to be platform agnostic.

**Comment by amirh** [comment]
This was a while ago, IIRC O saw this on an Android emulator using software rendering (just start any app that's using a texture)

**Comment by jonahwilliams** [comment]
We're removing support for software rendering from the Android backend. Closing as obsolete.
