### ISSUE TITLE
PlatformException(error, Support for pending purchases must be enabled. Enable this by calling 'enablePendingPurchases()' on BillingClientBuilder., null)

### ISSUE THREAD

**Issue by mallikarjunayeruku** [flutter/flutter#39350]
Got Exception On Flutter 
when calling 
    ProductDetailsResponse detailsResponse=await _connection.queryProductDetails(_consumableList.toSet());

```
 Unhandled Exception: PlatformException(error, Support for pending purchases must be enabled. Enable this by calling 'enablePendingPurchases()' on BillingClientBuilder., null)
E/flutter (18411): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (18411): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (18411): <asynchronous suspension>
E/flutter (18411): #2      BillingClient.startConnection (package:in_app_purchase/src/billing_client_wrappers/billing_client_wrapper.dart:89:62)
E/flutter (18411): <asynchronous suspension>
E/flutter (18411): #3      GooglePlayConnection._connect (package:in_app_purchase/src/in_app_purchase/google_play_connection.dart:166:21)
E/flutter (18411): #4      new GooglePlayConnection._ (package:in_app_purchase/src/in_app_purchase/google_play_connection.dart:27:20)
E/flutter (18411): #5      GooglePlayConnection._getOrCreateInstance (package:in_app_purchase/src/in_app_purchase/google_play_connection.dart:161:38)
E/flutter (18411): #6      GooglePlayConnection.instance (package:in_app_purchase/src/in_app_purchase/google_play_connection.dart:32:47)
E/flutter (18411): #7      InAppPurchaseConnection._getOrCreateInstance (package:in_app_purchase/src/in_app_purchase/in_app_purchase_connection.dart:225:40)
E/flutter (18411): #8      InAppPurchaseConnection.instance (package:in_app_purchase/src/in_app_purchase/in_app_purchase_connection.dart:216:50)
E/flutter (18411): #9      _PaymrntPage.initState (package:rewards_pay/pages/Payment.dart:60:43)
E/flutter (18411): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
E/flutter (18411): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
E/flutter (18411): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter (18411): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter (18411): #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
E/flutter (18411): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter (18411): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter (18411): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter (18411): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter (18411): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
E/flutter (18411): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
E/flutter (18411): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter (18411): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter (18411): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
E/flutter (18411): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter (18411): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter (18411): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
E/flutter (18411): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter (18411): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter (18411): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
E/flutter (18411): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter (18411): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter (18411): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
E/flutter (18411): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter (18411): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter (18411): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter (18411): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter (18411): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
E/flutter (18411): #38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
E/flutter (18411): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
E/flutter (18411): #40     Element.inflateWidget (package:flutter/src/widgets/
```

**Comment by mallikarjunayeruku** [comment]
var available =  InAppPurchaseConnection.instance;

Getting exception on calling instance 

`E/flutter ( 2578): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Support for pending purchases must be enabled. Enable this by calling 'enablePendingPurchases()' on BillingClientBuilder., null)
E/flutter ( 2578): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter ( 2578): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter ( 2578): <asynchronous suspension>
E/flutter ( 2578): #2      BillingClient.startConnection (package:in_app_purchase/src/billing_client_wrappers/billing_client_wrapper.dart:89:62)
E/flutter ( 2578): <asynchronous suspension>
E/flutter ( 2578): #3      GooglePlayConnection._connect (package:in_app_purchase/src/in_app_purchase/google_play_connection.dart:166:21)
E/flutter ( 2578): #4      new GooglePlayConnection._ (package:in_app_purchase/src/in_app_purchase/google_play_connection.dart:27:20)
E/flutter ( 2578): #5      GooglePlayConnection._getOrCreateInstance (package:in_app_purchase/src/in_app_purchase/google_play_connection.dart:161:38)
E/flutter ( 2578): #6      GooglePlayConnection.instance (package:in_app_purchase/src/in_app_purchase/google_play_connection.dart:32:47)
E/flutter ( 2578): #7      InAppPurchaseConnection._getOrCreateInstance (package:in_app_purchase/src/in_app_purchase/in_app_purchase_connection.dart:225:40)
E/flutter ( 2578): #8      InAppPurchaseConnection.instance (package:in_app_purchase/src/in_app_purchase/in_app_purchase_connection.dart:216:50)
E/flutter ( 2578): #9      new _PaymrntPage (package:rewards_pay/pages/Payment.dart:52:44)
E/flutter ( 2578): #10     Payment.createState (package:rewards_pay/pages/Payment.dart:29:12)
E/flutter ( 2578): #11     new StatefulElement (package:flutter/src/widgets/framework.dart:3989:25)
E/flutter ( 2578): #12     StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:802:38)
E/flutter ( 2578): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3082:40)
E/flutter ( 2578): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2578): #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
E/flutter ( 2578): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2578): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2578): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter ( 2578): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter ( 2578): #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
E/flutter ( 2578): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
E/flutter ( 2578): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2578): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2578): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
E/flutter ( 2578): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2578): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2578): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
E/flutter ( 2578): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2578): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2578): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
E/flutter ( 2578): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2578): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2578): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
E/flutter ( 2578): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2578): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2578): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter ( 2578): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter ( 2578): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
E/flutter ( 2578): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
E/flutter ( 2578): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:
E/libc    ( 2578): Access denied finding property "vendor.debug.egl.swapinterval"`

**Comment by mallikarjunayeruku** [comment]
if you have biliing dependency in app.gradle 
REMOVE IT

**Comment by ThinkSimple** [comment]
> if you have biliing dependency in app.gradle
> REMOVE IT
Can you give me some more information?

**Comment by mallikarjunayeruku** [comment]
When you adding in-app purchases library or  dependency to flutter pubspec.yml file
There is no need add in app purchases to app.Gradle in native Android side.
Because of  flutter library internally adding that dependency into Android Gradle .
So,there is conflict when you adding dependency into Android app.gradle,So remove it.

**Comment by emvaized** [comment]
> When you adding in-app purchases library or dependency to flutter pubspec.yml file
> There is no need add in app purchases to app.Gradle in native Android side.
> Because of flutter library internally adding that dependency into Android Gradle .
> So,there is conflict when you adding dependency into Android app.gradle,So remove it.

Hi!
Here's my build.gradle content:
` dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
} `

The error still occurs. What else can you suggest?
