### ISSUE TITLE
Update documentation about bitcode requirements

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#39359]
Related to: https://github.com/flutter/flutter/issues/39356

Once https://github.com/flutter/flutter/pull/39357 lands, we should update our documentation, particularly for Add to App, about the requirements to disable bitcode.  We should also update any remaining scripts we have that try to turn bitcode off for Add to App use cases.

/cc @xster @jmagman

**Comment by jmagman** [comment]
Is this specific to add-to-app, or should we update all examples and templates?

**Comment by dnfield** [comment]
All, but I'm pretty sure there's add to app docs that mention this specifically.

**Comment by jmagman** [comment]
If this is just add-to-app host:
1. Remove step 4 here https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#add-your-flutter-app-to-your-podfile.
1. Turn on bitcode for the host app example Xcode project.

If it's also the add-to-app module:
1. Remove ENABLE_BITCODE=NO from the module Xcode project template
1. Remove config.build_settings['ENABLE_BITCODE'] = 'NO' from the module Podfile.
1. Turn on bitcode for the ephemeral app example Xcode project.

**Comment by jmagman** [comment]
> I guess I suggest doing both since there seem to be some bugs about not cleaning up between runs.

Although I guess that doesn't matter if all the assets have bitcode on.

**Comment by jmagman** [comment]
@RedBrogdon Do you need to remove ENABLE_BITCODE=NO from any samples?

**Comment by jmagman** [comment]
Blocked on https://github.com/flutter/flutter/issues/39458.

**Comment by jmagman** [comment]
Documentation updated at [flutter/wiki/Add-Flutter-to-existing-apps/8ad360](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps/8ad360f164712f7f3e79ff814bddc6c0649db0f0).

Templates and examples updated with https://github.com/flutter/flutter/commit/0b93c96f524227b0b78021f551bbfae92fb54467.

Pending PR to update sample at https://github.com/flutter/samples/pull/140.

**Comment by jmagman** [comment]
I believe everything is done.  Let me know if I missed anything!
