### ISSUE TITLE
在苹果真机上运行无法热重载Could not update files on device: OS Error: Connection reset by peer, errno = 54

### ISSUE THREAD

**Issue by ly410726** [flutter/flutter#39372]
如果我断开蓝牙 热重载报错Could not update files on device: OS Error: Connection reset by peer, errno = 54

**Comment by mikhail-tokarev** [comment]
Please provide more details about the issue as well as the steps to reproduce it.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
