### ISSUE TITLE
Android alarm Manager failed to handle doze mode.

### ISSUE THREAD

**Issue by GadepalliAditya1998** [flutter/flutter#39377]
Hello, I have used the alarm Manager before and saw that it wasn't handling doze mode set by the OS but day before yesterday i.e. on 26th Aug 2019, the plugin was updated and given the way to handle it doze mode. I used it in my plugin to see the results but the alarms are not getting fired when the screen is turned off by keeping the app open. My use case is to run a background service that triggers timely for every 10 min say to fetch Location and push to my server. Initially it works fine. Later after an hour it starts delaying and after sometime it completely stops triggering. I need support for handling ideal cases when mobile is completely kept idle.

**Comment by TahaTesser** [comment]
Hi @GadepalliAditya1998 
Are you still experiencing this issue?
Thank you

**Comment by VladyslavBondarenko** [comment]
@GadepalliAditya1998 
I hope it's fixed.
If no, could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
