### ISSUE TITLE
iPhone doesn't hot-reload debugging under wifi

### ISSUE THREAD

**Issue by ly410726** [flutter/flutter#39373]
Apple mobile phone can not be hot overloaded under wifi status
`苹果手机在wifi状态下无法热重载报错`
Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1033/gTyWYAI_inw=/ws

**Comment by mikhail-tokarev** [comment]
Please provide more details about the issue as well as the steps to reproduce it.

**Comment by jmagman** [comment]
I don't think wireless debugging works.  Some context in https://github.com/flutter/flutter/issues/15072 and https://github.com/flutter/flutter/issues/37699, though those are manifesting differently.

**Comment by thavlik** [comment]
This may be related to https://github.com/flutter/flutter/issues/38677#issuecomment-528980904

**Comment by jmagman** [comment]
Closing, I don't think there's enough to go on in this issue.  If you see this again, please file a new issue and completely fill out the template, including the output of `flutter doctor -v` and attach `flutter run` with the verbose `-v` log.
