### ISSUE TITLE
flutter tool doesn't handle missing resources well

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3937]
I copied the flutter_gallery android manifest into the flutter package then ran `flutter run -t test/widget/draggable_test.dart` and got:

```
Building APK in debug mode (android-arm)...
android/AndroidManifest.xml:11: error: Error: No resource found that matches the given name (at 'icon' with value '@mipmap/ic_launcher').

Oops; flutter has exited unexpectedly: "Exit code 1 from: /usr/local/google/home/ianh/dev/engine/src/third_party/android_tools/sdk/build-tools/22.0.1/aapt package -M android/AndroidManifest.xml -A /tmp/flutter_too\
lsPJ9tjR/assets -I /usr/local/google/home/ianh/dev/engine/src/third_party/android_tools/sdk/platforms/android-22/android.jar -F /tmp/flutter_toolsPJ9tjR/app.apk.unaligned /tmp/flutter_toolsPJ9tjR/artifacts".
Crash report written to /usr/local/google/home/ianh/dev/flutter/packages/flutter/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by eseidelGoogle** [comment]
I presume you're asking for nicer log messages?  The error is that the AndroidManifest.xml mentions a resource which doesn't exist on disk where specified, and so aapt is dying.  Not a ton we can do here I don't think.  @devoncarew

**Comment by Hixie** [comment]
Well we shouldn't crash, at least.

**Comment by gspencergoog** [comment]
We don't crash anymore, and the error message does actually say what is wrong "No resource found that matches the given name..."

I'm going to call this fixed.
