### ISSUE TITLE
Taps on TextField prefix/suffix

### ISSUE THREAD

**Issue by MattL-NZ** [flutter/flutter#39376]
I'm experiencing weird issues with the latest stable version of Flutter: 1.7.8+hotfix.4.
I have a simple textfield widget that has an `onTap()` action. The textfield widget also has a prefix icon which has its own `onTap()` action. When I press the prefix icon, it completes everything inside the prefix `onTap()` but it also then goes and completes everything in the textfield `onTap()`.

I've been able to replicate it with the below code. Both onTap methods print outputs to the console. When the prefix icon is clicked, it is outputting the icon onTap as well as the textfield onTap actions.

**Replicated in below code**
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  void _incrementCounter() {
    setState(() {
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              color: Colors.red,
              child: TextField(
                onTap: () {
                  print('Hello this is a print out');
                },
                decoration: InputDecoration(
                  hintText: 'Hint text',
                  border: InputBorder.none,
                  contentPadding: EdgeInsets.only(left: 25.0, top: 16.0),
                  prefixIcon: IconButton(
                    icon: Icon(Icons.hotel, color: Colors.green, size: 40.0,),
                    onPressed: () {
                      print("Hi this is a second print out");
                    },
                  ),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}
```
**Flutter Doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-NZ)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.37.1)
[✓] Connected device (1 available)

• No issues found!
```
I have switched back to the master channel in the mean time to get around this issue but would be good to have it fixed. 
Thanks.

**Comment by MattL-NZ** [comment]
@HansMuller @mikhail-tokarev Hey guys, is there any idea on when this might be fixed?

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
There is a discussion at the end of https://github.com/flutter/flutter/issues/36324 about this problem, and a work in progress PR to fix it https://github.com/flutter/flutter/pull/38722.  I'm hoping to get some time to finish that up soon.

**Comment by JZ-at-TP** [comment]
Any update on this? I'de love to update my Flutter version but can't with this outstanding.

**Comment by justinmc** [comment]
@JZ-at-TP I haven't had time to circle back to that WIP PR, and I won't for at least a week or two.  If this is a blocker for you (or anyone else reading this), and you want to take over the PR yourself, I would be happy to help you through it.  Otherwise I will hopefully be pushing commits to that PR in a few weeks to finish it up.

**Comment by MattL-NZ** [comment]
Hey @justinmc I would be happy to look at doing the PR. Can you point me in the right direction on where to look? You can reach me at mattylist@gmail.com if you want to touch base via email.

**Comment by justinmc** [comment]
@MattL-NZ Thanks so much!  I'll email you with some details.

**Comment by MattL-NZ** [comment]
Hi @justinmc, just thought i would check in and see how you are progressing with this issue? Have you been able to get something working?

**Comment by justinmc** [comment]
Sorry, I haven't had time to finish https://github.com/flutter/flutter/pull/38722, but I plan to revisit it when I can!

**Comment by Lecarvalho** [comment]
Do we have a workaround for instant?

**Comment by DeveloperWaybee** [comment]
SOLUTION

Here's the solution for a suffix or prefix taps

[Solution Link](https://github.com/flutter/flutter/issues/36948#issuecomment-599797015)

**Comment by MattL-NZ** [comment]
@DeveloperWaybee, Your solution doesn't work for me unfortunately.
I still get the same outcome. See if you can get your solution working with the bit of my code at the top of this page.

**Comment by DeveloperWaybee** [comment]
You have to place a simple check inside onTap function. Please check below

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // Focus nodes are necessary

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  final textFieldFocusNode = FocusNode();

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _incrementCounter() {
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              color: Colors.red,
              child: TextField(
                focusNode: widget.textFieldFocusNode,
                onTap: () {
                  if (widget.textFieldFocusNode.canRequestFocus) {
                    print('Hello this is a print out');
                  }
                },
                decoration: InputDecoration(
                  hintText: 'Hint text',
                  border: InputBorder.none,
                  contentPadding: EdgeInsets.only(left: 25.0, top: 16.0),
                  prefixIcon: IconButton(
                    icon: Icon(
                      Icons.hotel,
                      color: Colors.green,
                      size: 40.0,
                    ),
                    onPressed: () {
                      // Unfocus all focus nodes
                      widget.textFieldFocusNode.unfocus();

                      // Disable text field's focus node request
                      widget.textFieldFocusNode.canRequestFocus = false;

                      // Do your stuff
                      print("Thanks for the solution");

                      //Enable the text field's focus node request after some delay
                      Future.delayed(Duration(milliseconds: 100), () {
                        widget.textFieldFocusNode.canRequestFocus = true;
                      });
                      print("Hi this is a second print out");
                    },
                  ),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 15a28159bc (8 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • SM M305F      • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS desktop • macos            • darwin-x64     • Mac OS X 10.15.5
      19F101
    • Web Server    • web-server       • web-javascript • Flutter Tools
    • Chrome        • chrome           • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!
``` 

</details>

**Comment by drekka** [comment]
Whilst this may work for a single field, it doesn't work for multiple fields.

**Comment by MarsGoatz** [comment]
TextField working properly without bugs is bare minimum TBH and writing hacks for these bare minimum widgets is just another level crazy.

Hoping a fix will be out soon!

**Comment by ilkercankaya** [comment]
> @MattL-NZ,
> You have to place a simple check inside onTap function. Please check below
> 
> ```
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   // Focus nodes are necessary
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: MyHomePage(title: 'Flutter Demo Home Page'),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   MyHomePage({Key key, this.title}) : super(key: key);
>   final String title;
>   final textFieldFocusNode = FocusNode();
> 
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   void _incrementCounter() {
>     setState(() {});
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text(widget.title),
>       ),
>       body: Center(
>         child: Column(
>           mainAxisAlignment: MainAxisAlignment.center,
>           children: <Widget>[
>             Container(
>               color: Colors.red,
>               child: TextField(
>                 focusNode: widget.textFieldFocusNode,
>                 onTap: () {
>                   if (widget.textFieldFocusNode.canRequestFocus) {
>                     print('Hello this is a print out');
>                   }
>                 },
>                 decoration: InputDecoration(
>                   hintText: 'Hint text',
>                   border: InputBorder.none,
>                   contentPadding: EdgeInsets.only(left: 25.0, top: 16.0),
>                   prefixIcon: IconButton(
>                     icon: Icon(
>                       Icons.hotel,
>                       color: Colors.green,
>                       size: 40.0,
>                     ),
>                     onPressed: () {
>                       // Unfocus all focus nodes
>                       widget.textFieldFocusNode.unfocus();
> 
>                       // Disable text field's focus node request
>                       widget.textFieldFocusNode.canRequestFocus = false;
> 
>                       // Do your stuff
>                       print("Thanks for the solution");
> 
>                       //Enable the text field's focus node request after some delay
>                       Future.delayed(Duration(milliseconds: 100), () {
>                         widget.textFieldFocusNode.canRequestFocus = true;
>                       });
>                       print("Hi this is a second print out");
>                     },
>                   ),
>                 ),
>               ),
>             )
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```

Instead of giving 100ms as delay, try

```
WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      textFieldFocusNode.canRequestFocus = true;
    });
```

It seems to work and is a smaller window.

**Comment by drekka** [comment]
Not sure if this will help, but here's what I ended up with to stop the field from taking focus when I tap a suffix button.

First I created a function to deactivate and restore focus like this:

```dart
typedef IconAction = void Function(void Function());

void textFormFieldIconAction({FocusNode focusNode, IconAction action}) {
  focusNode?.unfocus();
  focusNode?.canRequestFocus = false;
  action(() {
    focusNode?.canRequestFocus = true;
  });
}
```

This deactivates the ability of the field to accept focus, then calls the buttons action, passing it a closure to restore the focus ability. This allows the button to perform any amount of async work before calling the completion. I'm using this in an extension like this:

```dart
extension InputDecorationFactory on InputDecoration {

  /// Factory that creates an input decoration set with the apps standard look and feel.
   static InputDecoration formFieldDecoration({@required String label, @required String hint, IconData suffixIcon, IconAction action, FocusNode focusNode}) {
    return InputDecoration(
      labelText: label,
      hintText: hint,
      enabledBorder: UnderlineInputBorder(
        borderSide: BorderSide(color: Colors.black12),
      ),
    ).withSuffixIcon(suffixIcon, focusNode: focusNode, action: action);
  }

  /// Adds a suffix icon to an input decoration.
  InputDecoration withSuffixIcon(IconData suffixIcon, {IconAction action, FocusNode focusNode}) {

    // If there is no icon there's nothing to change.
    if (suffixIcon == null) {
      return this;
    }

    // If there's just an icon then add it and return.
    if (action == null) {
      return this.copyWith(suffixIcon: Icon(suffixIcon));
    }

    // otherwise setup the action and focus node.
    return this.copyWith(
      suffixIcon: IconButton(
        icon: Icon(suffixIcon),
        onPressed: () => textFormFieldIconAction(focusNode: focusNode, action: action),
      ),
    );
  }
}
```

**Comment by bayramaliunuvar** [comment]
all you have to do is define a variable.
`bool vadeTarihiClear=false;`

SuffixIcon
`      decoration: InputDecoration(
          suffixIcon: IconButton(
              icon: Icon(clearButtonIcon),
              onPressed: () {
                vadeTarihiClear = true;
                Future.delayed(Duration(seconds: 1), () {
                  vadeTarihiClear = false;
                });
              })
      ),
`

TextField ontap
`onTap: () async {
 if (vadeTarihiClear) return;
`

**Comment by drekka** [comment]
I learned long ago o never trust code that relies on time. Too many bugs come out of it and sometimes some bad user experiences. Not saying that won’t work. It’s just been my experience to avoid such code.

**Comment by LongCatIsLooong** [comment]
internal link: b/183372823

**Comment by cpboyd** [comment]
This also applies to other uses of touchable components on top of widgets that utilize `onTapDown`, e.g. `CupertinoContextMenu`.

Putting an `IconButton` on top will result in the `CupertinoContextMenu`'s internal `onTapDown` still triggering.

**Comment by wwwqyhme** [comment]
1. set textfield's decoration to null
2. wrap your textfield with InputDecorator

``` dart
AnimatedBuilder(
              animation: Listenable.merge(<Listenable>[focusNode]),
              builder: (BuildContext context, Widget? child) {
                return InputDecorator(
                  decoration:
                      effectiveDecoration.copyWith(errorText: state.errorText),
                  isFocused: focusNode.hasFocus,
                  isEmpty: state.value == null,
                  child: child,
                );
              },
              child: textField,
            );
          }
```

**Comment by LongCatIsLooong** [comment]
@justinmc @chunhtai as I understand it the tap "leaks" because of the use of the `_TransparentTapGestureRecognizer` in the text field right? The text field wants to handle double/triple taps but single taps should be handled by the selection handle, but as a result taps that landed on something other than the selection handle are now leaking to the text field as well.

After testing on my android devices and iphone I have a different interpretation of the tap gesture: 

|| iOS | Android |
| --- | --- | --- |
| selection handle | The handle can be dragged but **DOES NOT HANDLE TAPS**. <br/>I tested this on a simulator so I can precisely land my taps on the tiny selection handle. It turns out the "current" behavior might be a result of inaccurate tapping  | The handle can be dragged and tapped. Tap down brings up a magnifier and tap up dismisses the magnifier. Tapping in quick succession performs multiple single taps. <br/>I doubt it has a dedicated tap recognizer, as it makes more sense to implement using a pan gesture recognizer |
| selection highlight | Tapping expands the selection to the corresponding text boundary (single - word edge, double - word, triple - paragraph). If the target selection is already part of the current selection, it keeps the selection as is and toggles the text selection toolbar. | tap gestures seem to do the same as on regular text | 

So I guess we can retire the `_TransparentTapGestureRecognizer` class. And maybe deprecate the `onSelectionHandleTapped` callback on `EditableText`s, etc. too. 

I think one of the main challenges to implement the iOS selection highlight gesture behavior would be that if the entire document is selected the user won't be able to tap somewhere that doesn't have a glyph to collapse the selection to a caret (since the current API only tells us the text position to the closest glyph: `GetGlyphPositionAtCoordinate` always return a valid position in the text even if the given coordinate is far away from every glyph).

**Comment by LongCatIsLooong** [comment]
This has caused several really annoying issues (e.g., https://github.com/flutter/flutter/issues/78918), and I'd like to fix this before continuing with https://github.com/flutter/flutter/pull/79414 (it's difficult to port some of the hacks to the new implementation). I'm going to work on it ASAP.
