### ISSUE TITLE
Launch Screen - Pinning image to the bottom doesn't work properly while running the app (iOS)

### ISSUE THREAD

**Issue by nassifbasheer** [flutter/flutter#39378]
I just started learning the flutter technology (from iOS). I am trying to create a starter app, which just uses a LaunchScreen and Home Screen.

I am facing the following couple of issues.

- In LaunchScreen.Storyboard, there is an image pinned to the bottom , left , right and fixed height. How ever while running the application the images is shown at the top.
- There is a white screen that is visible for some time before showing the launch screen and the home screen. Also the launch screen goes off within a 1 second. Is there a solution to the white screen and the bottom layout issue

**Comment by BondarenkoStas** [comment]
Maybe it is not an issue with flutter itself, but is some mistake in implementation. In that case the question belongs to StackOverflow.
Anyway can you please provide an example of code to reproduce the issue?

**Comment by nassifbasheer** [comment]
Regarding the splash screen:

- I tried in an actual Xcode project with the same layout position and the launch screen showed exactly with the image at the bottom

Regarding the white screen.

- I used the code from this page [navitagion with animation](https://flutter.dev/docs/cookbook/navigation/hero-animations)

![Xcode - Launch Screen Storyboard auto-layout](https://user-images.githubusercontent.com/5028245/63908281-44a4a480-ca3c-11e9-8013-3705bcc17cac.png)

![Flutter launch screen](https://user-images.githubusercontent.com/5028245/63908311-643bcd00-ca3c-11e9-88f3-2b285b4e6e72.png)

**Comment by nassifbasheer** [comment]
@BondarenkoStas Did you get a chance to look into this issue

**Comment by BondarenkoStas** [comment]
@nassifbasheer Sorry, I doubt I can help with it, I'm doing initial issues triage and not much experienced with flutter.
The issues is labeled, no worries, let's wait for some help.

**Comment by nassifbasheer** [comment]
may be this could be the solution 

Place the assets or custom UI elements to the Launch screen storyboard without adding any auto layout constraints.
There was no black screen or white screen or multiple screens

**Comment by VladyslavBondarenko** [comment]
Hi @nassifbasheer 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
