### ISSUE TITLE
[Material] Card shadow blinking

### ISSUE THREAD

**Issue by dblokhin** [flutter/flutter#39380]
## Steps to Reproduce
The bottom `Card` shadow is blinking with using `ContinuousRectangleBorder` shape. I've wrote the video: [https://www.youtube.com/watch?v=zJe-bRUO8SA](https://www.youtube.com/watch?v=zJe-bRUO8SA)

```dart
return MaterialApp(
      home: Scaffold(
        body: ListView.builder(
          itemBuilder: (_, __) => Card(
            shape: ContinuousRectangleBorder(
                borderRadius: BorderRadius.circular(20)),
            clipBehavior: Clip.antiAlias,
            child: Container(
              height: 200,
            ),
          ),
        ),
      ),
    );
```
```
[✓] Flutter (Channel dev, v1.9.2-pre.34, on Linux, locale ru_RU.UTF-8)
    • Flutter version 1.9.2-pre.34 at /home/lee/Run/flutter
    • Framework revision e833a5820e (7 дней назад), 2019-08-20 11:00:21 -0700
    • Engine revision 10167db433
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/lee/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/lee/Run/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/lee/Run/android-studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

```

**Comment by alexpavelm** [comment]
I tried doing the same and i can't reproduce it on a pixel 3 @1080x2160, 440 dpi. Can you tell me which deviced you used there?
Cards use default elevation of 1 px and it might not be able to display it on a low dpi/res in certain positions when you scroll.

**Comment by dblokhin** [comment]
Sorry for waiting, I could not get to the pc.
I reproduce it on Samsung S6 Edge, Sony Z1 Tablet, Meizu M6 note. All of those devices have high dpi/res but Meizu. I guess the problem is slighty wider because this code doesn't show shadow on Samsung S8 at all.

**Comment by dblokhin** [comment]
Also I see that the shadow is growing with follow items. Check this code with `height: 100`:
![Screenshot_20190902-174154](https://user-images.githubusercontent.com/3104793/64098074-473f2b00-cda9-11e9-86d6-bd8ab51b6a65.png)

**Comment by ricpar11** [comment]
Why did you close this issue? 
Did you find a workaround?
@dblokhin

**Comment by doppio** [comment]
@dblokhin Did you find a fix to this? I'm experiencing the same issue.

**Comment by hsul4n** [comment]
#28463
