### ISSUE TITLE
Xcode Product Archive failed

### ISSUE THREAD

**Issue by mofada** [flutter/flutter#39383]
I tried uploading the app store, but it went wrong. But I use `flutter build ios ` is normal, the operation is normal, only product->archive will fail, I really don't know how to solve it. I tried it, but I can't do it. I am so tired.

![code signing "flutter.framework" failed.](https://user-images.githubusercontent.com/22286246/63831888-37d37280-c9a2-11e9-9dff-ad666ed8d278.jpg)

When I create a new project, I don't add any plugins, he is successful, but adding a plugin will fail.

## Logs
[IDEDistribution.standard.log](https://github.com/flutter/flutter/files/3549468/IDEDistribution.standard.log)
[IDEDistribution.verbose.log](https://github.com/flutter/flutter/files/3549469/IDEDistribution.verbose.log)
[IDEDistributionPipeline.log](https://github.com/flutter/flutter/files/3549470/IDEDistributionPipeline.log)
[IDEITunesSoftwareService.log](https://github.com/flutter/flutter/files/3549471/IDEITunesSoftwareService.log)

## flutter doctor -v
```
fadadeiMac:~ fada$ flutter doctor -v
[✓] Flutter (Channel master, v1.9.6-pre.6, on Mac OS X 10.14.6 18G87, locale
    zh-Hans-CN)
    • Flutter version 1.9.6-pre.6 at /Users/fada/Library/flutter
    • Framework revision d37a38cee1 (3 days ago), 2019-08-25 10:57:54 -0700
    • Engine revision deca2c0da8
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/fada/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/fada/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.7830
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • macOS • macOS • darwin-x64 • Mac OS X 10.14.6 18G87

! Doctor found issues in 1 category.
```

**Comment by mofada** [comment]
## flutter build ios -v
[flutter-build-ios-v.txt](https://github.com/flutter/flutter/files/3549631/flutter-build-ios-v.txt)

**Comment by mofada** [comment]
When I create a new project with a demo directly archived, it is normal.
![TIM图片20190828165302](https://user-images.githubusercontent.com/22286246/63840882-5a6e8700-c9b4-11e9-8187-851ab225fdf5.jpg)

**Comment by mofada** [comment]
When I add `shared_preferences: ^0.5.3+4` to pubspec.yaml, the archive will fail, and Linked Frameworks has one more line here.
![TIM图片20190828171838](https://user-images.githubusercontent.com/22286246/63842892-0ebddc80-c9b8-11e9-9a51-7dc1ba4f3aa5.jpg)

**Comment by jmagman** [comment]
This isn't related to the plugin, it seems to be a code signing issue when CocoaPods gets involved.

```
2019-08-27 10:35:35 +0000  Writing entitlements for <IDEDistributionItem: 0x7fbba9748040 'io.flutter.flutter' '<DVTFilePath:0x7fbba95e61b0:'/Users/fada/Library/Developer/Xcode/Archives/2019-08-27/Runner 2019-8-27, 18.16.xcarchive/Products/Applications/Runner.app/Frameworks/Flutter.framework'>'> to: /var/folders/gf/769gy_k92_101wy84mx7s8zr0000gn/T/XcodeDistPipeline.~~~vNlcp6/entitlements~~~WklDkc
2019-08-27 10:35:35 +0000  Running /usr/bin/codesign '-vvv' '--force' '--sign' '6A958D174CBB940F0F834770359949A6E642DA1E' '--entitlements' '/var/folders/gf/769gy_k92_101wy84mx7s8zr0000gn/T/XcodeDistPipeline.~~~vNlcp6/entitlements~~~WklDkc' '--preserve-metadata=identifier,flags,runtime' '/var/folders/gf/769gy_k92_101wy84mx7s8zr0000gn/T/XcodeDistPipeline.~~~vNlcp6/Root/Payload/Runner.app/Frameworks/Flutter.framework'
2019-08-27 10:35:35 +0000  /var/folders/gf/769gy_k92_101wy84mx7s8zr0000gn/T/XcodeDistPipeline.~~~vNlcp6/Root/Payload/Runner.app/Frameworks/Flutter.framework: replacing existing signature
2019-08-27 10:35:35 +0000  /var/folders/gf/769gy_k92_101wy84mx7s8zr0000gn/T/XcodeDistPipeline.~~~vNlcp6/Root/Payload/Runner.app/Frameworks/Flutter.framework: code object is not signed at all
```

I'm not able to reproduce.  Maybe some non-ASCII issues?  https://github.com/electron/electron-osx-sign/issues/155

Can you try a `flutter upgrade` and then `flutter clean` to get new copy of that framework?

**Comment by mofada** [comment]
Yes, I have tried everything.
1. `flutter upgrade` and  `flutter clean`
2. delete ios and `flutter create .`
3. xcode produce -> clean and product -> build
4. file -> workspace setting -> Build System
![workspace setting](https://user-images.githubusercontent.com/22286246/63904497-cf3cd200-ca43-11e9-9365-d28824e70ef0.jpg)

**Comment by mofada** [comment]
I am trying to add `flutter_swiper: ^1.1.6`, it can be archived normally, because it does not interact with ios, and `shared_preferences/device_info` will interact with ios, there will be problems

**Comment by mofada** [comment]
I' confused.

**Comment by jmagman** [comment]
Can you try deleting `<path_to_flutter>/bin/cache/` and running `flutter doctor` to get new copies of those frameworks?
Please revert that build system change and change it back to New Build System, you'll get different issues.
If you make a new non-Flutter iOS project in Xcode and set up your development team, does it archive?  This is some Xcode code signing issue, I'm not sure how much Flutter is involved.

> I am trying to add `flutter_swiper: ^1.1.6`, it can be archived normally, because it does not interact with ios, and `shared_preferences/device_info` will interact with ios, there will be problems

Adding any plugin that has native iOS code (not just shared_preferences) will probably make you hit the same thing.

**Comment by mofada** [comment]
However, my new flutter project is normal, can be put on the app store, but the plugin that interacts with ios will be wrong.

**Comment by jmagman** [comment]
Can you try deleting <path_to_flutter>/bin/cache/ and running flutter doctor to get new copies of those frameworks?

**Comment by mofada** [comment]
@jmagman   Yes, I solve it according to your steps. Thank you very much.

> 您可以尝试删除<path_to_flutter>/bin/cache/并运行flutter doctor以获取这些框架的新副本吗？
请恢复构建系统更改并将其更改回New Build System，您将遇到不同的问题。

**Comment by mofada** [comment]
Use xcode run to get a blank
```
2019-08-29 14:02:30.952544+0800 Runner[14391:11777103] Failed to find snapshot: /var/containers/Bundle/Application/439FA3EF-1336-4BA9-AFFF-3DAFED899966/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin
2019-08-29 14:02:31.641220+0800 Runner[14391:11777213] [VERBOSE-2:engine.cc(120)] Engine run configuration was invalid.
2019-08-29 14:02:31.641289+0800 Runner[14391:11777213] [VERBOSE-2:shell.cc(407)] Could not launch engine with configuration.
2019-08-29 14:02:31.753223+0800 Runner[14391:11777222] flutter: Observatory listening on http://127.0.0.1:56010/GwJ1QWdBM-Q=/

```

**Comment by michael-zhao-pte** [comment]
I have the same problem ,you can try delete
Build Phases->Run Script
#"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
#"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed
it will be work

**Comment by jmagman** [comment]
@michael-zhao-pte If you delete that script then Flutter will not be embedded in your app and it will crash.  Could you file a new issue and completely fill out the template?  I suspect you are not seeing the exact same problem this issue is describing.
