### ISSUE TITLE
ShowCupertinoDialog USES a TextField,How to lose focus。

### ISSUE THREAD

**Issue by zhangxu123123** [flutter/flutter#39386]
![aaa](https://user-images.githubusercontent.com/38719680/63839229-6c025f80-c9b1-11e9-966c-60d6371c575b.png)

**Comment by mikhail-tokarev** [comment]
Please provide more details about the issue as well as the steps to reproduce it.

**Comment by janmoppel** [comment]
Hello @zhangxu123123 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
