### ISSUE TITLE
FlutterFire link is broken on the codelab

### ISSUE THREAD

**Issue by rnitta** [flutter/flutter#39385]
On the bottom of [the tutorial about using Crashlytics with flutter,](https://codelabs.developers.google.com/codelabs/flutter-firebase/#6)
we can see "FlutterFire GIthub Page",
and it links to [https://github.com/flutter/plugins/blob/master/FlutterFire.md](https://github.com/flutter/plugins/blob/master/FlutterFire.md),
and it is broken.

> <img width="789" alt="スクリーンショット 2019-08-28 17 18 09" src="https://user-images.githubusercontent.com/31783570/63838177-d4ecd600-c9b7-11e9-9a1e-9136c44c26c1.png">

The correct link may be [https://github.com/FirebaseExtended/flutterfire](https://github.com/FirebaseExtended/flutterfire)

https://twitter.com/FlutterDev/status/1166070213407694848
:D

**Comment by domesticmouse** [comment]
That codelab has been retired. Thanks for the report!
