### ISSUE TITLE
How to fix firebase_admob package problem in Flutter

### ISSUE THREAD

**Issue by MrPala06** [flutter/flutter#39382]
When I import flutter_admob in my flutter project and run the project it gives an error.

I already tried things android studio offered me([in this tutorial](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility)) and I got a different error. And also I tried connect to firebase and change some version but nothing changed.

**Here is the final error message:**
```
Launching lib\main.dart on Android SDK built for x86 in debug mode... Initializing gradle... Resolving dependencies... 
Error running Gradle: ProcessException: Process "D:\android\projects\black_dot\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

Where: Build file 'D:\android\projects\black_dot\android\app\build.gradle' line: 1

What went wrong: A problem occurred evaluating project ':app'.

Could not find method Properties() for arguments [] on project ':app' of type org.gradle.api.Project.

Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUİLD FAILED in 1s Command: D:\android\projects\black_dot\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.
```

**Comment by mannprerak2** [comment]
Try deleting your android folder and run
```flutter create --androidx .```
you can add the --org for changing package name if required. like this
```flutter create --org com.example.app --androidx .```

**Comment by kroikie** [comment]
@MrPala06

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1168. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since firebase_admob issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by BondarenkoStas** [comment]
@MrPala06 did you manage to get it working?

**Comment by stuartmorgan** [comment]
Closing, as `firebase_admob` is [now deprecated](https://pub.dev/packages/firebase_admob/versions/0.11.0+2).
