### ISSUE TITLE
cannot prevent iOS app from opening in landscape mode

### ISSUE THREAD

**Issue by durduman** [flutter/flutter#39388]
Trying to put the iOS app to be displayed only in portrait (up).

```
void main() async {
     await SystemChrome.setPreferredOrientations([
        DeviceOrientation.portraitUp
    ]); 
   //    also tried with .then(() => runApp(Application()))
    runApp(Application());
 }
```

When opening the app directly in landscape, the app will be displayed in landscape.
At the first orientation switch, all will work as expected.

Only way to properly enforce this on iOS is by configuring the Runner project.

**flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.6 18G87, locale en-RO)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (2 available)
```

**Comment by iapicca** [comment]
Hi @durduman 
could you please run 
`
 flutter channel stable
`
`
 flutter upgrade
`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by gaaclarke** [comment]
> Only way to properly enforce this on iOS is by configuring the Runner project.

I think that is the solution.  Unfortunately the problem can only be solved before flutter is executed.
