### ISSUE TITLE
https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter%2Fissues%2Fnew%3Ftemplate%3DBUG.md

### ISSUE THREAD

**Issue by Rajeshhmuthyala** [flutter/flutter#39392]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by mikhail-tokarev** [comment]
Closing as no information was provided. If you have a problem to report, please open a new issue and fill in the information requested in the template.
