### ISSUE TITLE
[web] Chrome OS virtual desktops invert Widgets

### ISSUE THREAD

**Issue by CiriousJoker** [flutter/flutter#39393]
## Steps to Reproduce

1. Open my project at https://pokeroute.web.app/ (this may change in the future, sourcecode will be provided upon asking)
2. Switch to a new virtual desktop with the 4 finger swipe gesture and back. Normal switching does **not** trigger this bug.
3. Background image and text fields are now vertically inverted.

### Notes

- This is reproducable with 100% accuracy on my machine
- I'm running Chrome OS Version 78.0.3889.0 (Official Build) dev (64-bit)

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/ciriousjoker/flutter
    • Framework revision 20e59316b8 (6 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/ciriousjoker/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/ciriousjoker/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.37.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.3.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by CiriousJoker** [comment]
I have the feeling that this is related to the Stack widget.

Take this code:

```
            child: Stack(
              children: <Widget>[
                AspectRatio(
                  aspectRatio: 2.5 / 3.5,
                  child: Image(
                    image: some image
                  ),
                ),
                
                Align(
                  alignment: Alignment.topRight,
                  child: Card(
                      margin: EdgeInsets.all(0),
                      child: Container(
                        margin:
                            EdgeInsets.symmetric(vertical: 4, horizontal: 8),
                        child: Text("Some text 1"),
                      )),
                ),
                Positioned(
                  bottom: 0.0,
                  left: 0.0,
                  right: 0.0,
                  child: Container(
                    constraints: BoxConstraints(maxHeight: 300),
                    color: Colors.black.withOpacity(0.4),
                    child: Text(
                      "Some text 2",
                      style: Theme.of(context).textTheme.title,
                    ),
                  ),
                ),
              ],
            ),
```

Some text 1 is displayed correctly, while some text 2 is inverted vertically (just like the image).

**Comment by CiriousJoker** [comment]
I've noticed the same behavior using Gravit designer. However, that bug is different in that with Gravit, it only ever flips the panel where the image is in (so when I scroll the image upwards and trigger the bug, it's now flipped and at the bottom). Scrolling inside the image panel is also inverted.

**Also, I've noticed that this bug is triggered when I switch virtual desktops normally, via gestures or if I switch the tab (again, normal or gestures). Not 100% sure if it was that way before but now it's like this.**

This seems to go beyond Flutter, so I'll create a Chromium issue for that.

**Comment by ferhatb** [comment]
@CiriousJoker , do you have a link to Chromium issue?

**Comment by CiriousJoker** [comment]
Sorry forgot to add, here it is:
https://bugs.chromium.org/p/chromium/issues/detail?id=999296

**Comment by CiriousJoker** [comment]
Couldn't reproduce with the newest chrome. Haven't touched the code since then, so this wasn't a Flutter issue.
