### ISSUE TITLE
 Failed assertion: line 136 pos 14: '!listenable.hasListeners

### ISSUE THREAD

**Issue by mo7ammedgaber** [flutter/flutter#39396]
![68939865_393567518025133_2504789527906746368_n](https://user-images.githubusercontent.com/54624558/63847598-67787f80-c98e-11e9-8e62-96f0b9b64115.jpg)

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by mikhail-tokarev** [comment]
Please provide more details about the issue as well as the steps to reproduce it and flutter version

**Comment by mo7ammedgaber** [comment]
now when i make build 
source: pub did not update .packages file (pubspec.yaml file has a newer timestamp)

**Comment by helinanever** [comment]
Closing, as the issue you describe remains unclear and cannot be acted upon. If the problem persists, please create a new issue and provide details according to the template.
