### ISSUE TITLE
AnimatedSwitcher with IndexedStack

### ISSUE THREAD

**Issue by DanielScholte** [flutter/flutter#39398]
I have to use IndexedStack to maintain the state of my widgets for my BottomNavigationBar.  
Now i want to use AnimatedSwitcher (or an alternative) to create an animation when i switch tabs.
I'm having issues getting AnimatedSwitcher to trigger on change of IndexedStack. I'm having IndexedStack as the child of AnimatedSwitcher, which obviously causes AnimatedSwitcher to not trigger because the IndexedStack widget doesn't change, only it's child.
```
body: AnimatedSwitcher(  
  duration: Duration(milliseconds: 200),  
  child: IndexedStack(  
    children: _tabs.map((t) => t.widget).toList(),  
    index: _currentIndex,  
  ),  
)
```
Is there any way around this issue? By manually triggering the AnimatedSwitcher, or by using a different method to create an animation?

**Comment by BondarenkoStas** [comment]
Seems like it's not an issue with flutter and is related to organising of widgets. Please try to post it to StackOverflow to get some help.
