### ISSUE TITLE
Listview does not display

### ISSUE THREAD

**Issue by pengchengfuGit** [flutter/flutter#39391]
```
new Column(
        children: <Widget>[
          new Row(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            textDirection: TextDirection.ltr,
            children: <Widget>[
              new Expanded(
                  child: new ListView.builder(
                    itemCount: 50,
                    itemExtent: 50.0,
                    itemBuilder: (BuildContext context, int index) {
                      return ListTile(
                        title: Text("I am List item $index"),
                      );
                    },
                  )),
              new Text("1321312312312312312")
            ]
          )
        ]
      )
```

**Comment by andrijasinski** [comment]
Hi, your code fails with next stack trace: 
```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performResize():
flutter: Vertical viewport was given unbounded height.
flutter: Viewports expand in the scrolling direction to fill their container.In this case, a vertical
flutter: viewport was given an unlimited amount of vertical space in which to expand. This situation
flutter: typically happens when a scrollable widget is nested inside another scrollable widget.
flutter: If this widget is always nested in a scrollable widget there is no need to use a viewport because
flutter: there will always be enough vertical space for the children. In this case, consider using a Column
flutter: instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size
flutter: the height of the viewport to the sum of the heights of its children.
flutter:
flutter: When the exception was thrown, this was the stack:
```
Is that something you have seen as well, @pengchengfuGit ? If not, share your logs please.

Most likely you need to set constraints for your Column and Row elements. Try to play around with widgets or start just with ListView builder and wrap it with widgets you need.

**Comment by jugalw13** [comment]
@pengchengfuGit ListView by default has an unbounded height by wrapping it with column it will throw an exception as it cannot determine the height to call internal methods to render the widget. It's not an issue with flutter. It's a use case issue. 
`@override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Container(
          padding: EdgeInsets.all(15),
          height: 100,
          child: Row(
            children: <Widget>[
              Expanded(
                child: ListView.builder(
                  itemCount: 2,
                  itemBuilder: (
                    BuildContext context,
                    int index,
                  ) {
                    return Container(
                      child: Text("I am List item $index"),
                    );
                  },
                ),
              ),
              Text('Hello World'),
            ],
          ),
        ),
      ],
    );
  }`
Here's a small snippet of code showing it's working because I bounded the Row in a container of height 100.

**Comment by mikhail-tokarev** [comment]
Thank you @jugalw13 
@pengchengfuGit I'm going to close this issue, as this isn't an issue with Flutter itself
