### ISSUE TITLE
[Bug?Feature?]A problem about GestureDetector and number of fingers

### ISSUE THREAD

**Issue by rs5173** [flutter/flutter#39394]
I found a very interesting phenomenon. When using GestureDetector to detect sliding gestures, the value of details.delta will increase exponentially with the number of fingers. Is this a bug or a feature?

This does not seem reasonable in Android Native.

**Comment by iapicca** [comment]
Hi @mikhail-tokarev 
I see there's an open [issue](https://github.com/flutter/flutter/issues/38926) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
