### ISSUE TITLE
Use system ICU on Android

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#394]
We don't actually know if this is possible yet, unlike iOS (https://github.com/flutter/flutter/issues/392).  However if we can, it would save ~2MB of our APK size.

**Comment by eseidelGoogle** [comment]
@jason-simmons is going to do a bit of research this afternoon.

**Comment by eseidelGoogle** [comment]
It looks like Android at least documents which versions are included on which OS releases: http://developer.android.com/reference/java/util/Locale.html

**Comment by eseidelGoogle** [comment]
We also currently only support back to v16: http://flutter.io/faq/#what-devices-and-os-versions-does-flutter-run-on

**Comment by jason-simmons** [comment]
From what I can tell, Android ships with the ICU libraries and data table, but it doesn't expose them through the NDK APIs.

In theory it would be possible to dlopen the ICU library and load the needed symbols.  However, this would be an unsustainable hack.  Android ships different versions of ICU with each release, and ICU adds version tags to the exported symbols.  So we would need to customize the symbol resolution and test extensively on every version of Android that we support.

**Comment by abarth** [comment]
The verdict here is that doing this would be an unsustainable hack.

**Comment by dnfield** [comment]
Just in case anyone else comes here again: the NDK considered and rejected exposing ICU.

The basic reason is that not all vendors are required to ship it, and there's no way of knowing whether a vendor has shipped the necessary bits or not at this point.

**Comment by eseidelGoogle** [comment]
FYI @drwulf and @Hixie who have both brought this up recently.

**Comment by dnfield** [comment]
See https://github.com/android/ndk/issues/548#issuecomment-528080058 for the NDK bug.
