### ISSUE TITLE
Xcode 11 Beta 6 keeps stale code between clean builds and archive commands

### ISSUE THREAD

**Issue by evelyne24** [flutter/flutter#39401]
## Steps to Reproduce

I ran multiple Flutter `clean` and `build` commands, then use Xcode to archive the ipa and submit it to TestFlight. Although the printed version in my app was correct, the actual code in the build was stale, belonging to previous builds. 

The only way to solve it was to manually delete everything inside `/Users/evelina/Library/Developer/Xcode/DerivedData` and `/Users/evelina/Library/Developer/Xcode/Archives` before each build.

Also found this related post (I'm not an iOS dev so this is news to me):  https://t.co/Q6IkeWcORy

**Second attempt:** 

1. Ran the following Flutter commands, as per [official documentation](https://flutter.dev/docs/deployment/ios#create-a-build-archive)
```
flutter clean
flutter build ios --release --no-codesign -v --flavor live -t lib/main_live.dart --build-name=1.2.0 --build-number=$(git rev-list HEAD --count)
```
2. Use Xcode to archive the ipa
3. Distribute the ipa either Ad-Hoc (on device) or on TestFlight
4. The version code and name looks correct. The actual code is one release before (the previous archived code).

**Second attempt:** 

1. Ran the following Flutter commands
```
flutter clean
flutter build ios --release --no-codesign -v --flavor live -t lib/main_live.dart --build-name=1.2.0 --build-number=$(git rev-list HEAD --count)
```
2. Use Xcode to archive the ipa
3. Distribute the ipa either Ad-Hoc (on device) or on TestFlight
4. The version code and name look correct. The actual code is the one for development (the previous archived code).

## Logs

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-GB)
    • Flutter version 1.7.8+hotfix.4 at /Users/evelina/bin/flutter
    • Framework revision 20e59316b8 (6 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/evelina/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/evelina/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/evelina/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.0, Build version 11M392q
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6262.58

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • Evelina's iPhone • 00008020-00196DAE0A90003A • ios • iOS 13.0

• No issues found!
```

*Note* Before anyone comments about _why using Beta_: that is because I need Xcode beta Signing and Capabilities to properly handle multiple Flutter flavours/environments with different bundle ids, something that I found extremely painful and buggy in Xcode 10.

**Comment by jmagman** [comment]
Your description mentions `flutter build apk` which is for distributing an Android app, not an iOS app.  Can you confirm you ran `flutter build ios` instead, which is what the [doc you linked](https://flutter.dev/docs/deployment/ios#create-a-build-archive) to suggests?

Obviously having to `flutter clean` at all isn't a good solution, but a few days ago I merged https://github.com/flutter/flutter/commit/892d62f03ac93c24738a59fa9e6d03b63afb8d5a (in 1.9.3, currently in the dev channel), which should clean up DerivedData, though not the Archives directory.  I don't think `flutter` should delete anything in Archives though since I don't see any way to figure out which archives are from the Flutter app.  

Next time you submit, if you could try on that build it would let us know if whatever is incorrectly cached was in DerivedData or Archives.

**Comment by ianrumac** [comment]
OMG @evelyne24 you just saved my build! Thank you!

Same issue happening to me - **XCode 10.3**, Flutter both **v1.7.8+hotfix.4** and **v1.8.3**.
Tried archiving multiple times, only thing that changed was the version.

Can confirm, 
> The only way to solve it was to manually delete everything inside /Users/evelina/Library/Developer/Xcode/DerivedData and /Users/evelina/Library/Developer/Xcode/Archives before each build.

Simply deleting `DerivedData` didn't work.

**Comment by evelyne24** [comment]
Yeah sorry, pasted the wrong command by mistake. Obviously is iOS.

**Comment by jmagman** [comment]
Cleaning the workspace was taken care of with https://github.com/flutter/flutter/pull/38992, and I think that's all this is tracking since `flutter` doesn't have enough information to know which Archives are safe to delete.
Closing.
