### ISSUE TITLE
Catalina issues seen by bots

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#39418]
It looks like not all our bots are Catalina-clean:
https://flutter-dashboard.appspot.com/build.html

We should get to a state where none of our Catalina-related tests are marked flaky, and the tree is green.

**Comment by jmagman** [comment]
@digiter it looks like my one un-flakification https://github.com/flutter/flutter/pull/38999 was reverted here https://github.com/flutter/flutter/commit/a690b0b8e221910ffc9ac2b5e85cc9994b2ca10a.

**Comment by digiter** [comment]
> @digiter it looks like my one un-flakification #38999 was reverted here [a690b0b](https://github.com/flutter/flutter/commit/a690b0b8e221910ffc9ac2b5e85cc9994b2ca10a).

It was intended, because I changed the platform of `smoke_catalina_start_up` from catalina/ios to catalina/android, therefore it's a new test and marked flaky at first.

**Comment by tvolkert** [comment]
@digiter are you driving this?

**Comment by digiter** [comment]
Yes, I'm waiting to see whether https://github.com/flutter/flutter/pull/39594 would fix the flaky hot reload test.

**Comment by christopherfujino** [comment]
Looks like #39594 & #39772 fixed this
