### ISSUE TITLE
flutter_gallery__transition_perf is flaky

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#39419]
The first failure starts at https://github.com/flutter/flutter/commit/2b03e2089db2ae212869426cd923dd0c35a334fe , and my bisection shows that the culprit is https://github.com/flutter/flutter/commit/ea323851627cb09f75fd5e3282c36c3cc3f4b3c7 (please see the attached bisection log).

[bisect.out.zip](https://github.com/flutter/flutter/files/3552249/bisect.out.zip)

**Comment by yjbanov** [comment]
I think reverting https://github.com/flutter/flutter/commit/ea323851627cb09f75fd5e3282c36c3cc3f4b3c7 would be counterproductive. That commit touches code that's nowhere near flutter_gallery__transition_perf benchmark. My best guess is the issue is in the devicelab.

**Comment by liyuqian** [comment]
@yjbanov : agree, especially now that my 80-time experiment just shows that your commit can pass the test 80 times continuously... I wonder if this is a device specific issue. I think that I recently turned off the system update between the 40-time and 80-time experiment. Then suddenly the test seems to be much harder to fail. I'll probably go and check the device. CC @digiter

**Comment by Hixie** [comment]
This test has now gone entirely red. We need to get this fixed and marked non-flaky ASAP.

**Comment by yjbanov** [comment]
@liyuqian have you found anything suspicious on the test device?

**Comment by liyuqian** [comment]
I found emergency alerts being enabled last week. I haven't checked it today.

**Comment by liyuqian** [comment]
This seems to be still flaky. I'll further investigate on the device lab.

**Comment by jonahwilliams** [comment]
I think these machines/phones are reaching EOL.

**Comment by liyuqian** [comment]
This is no longer flaky as of 09/13/2019. Closing.
