### ISSUE TITLE
createWithFrame should tolerate a `nil` response

### ISSUE THREAD

**Issue by raycardillo** [flutter/flutter#39410]
##  Use case

Writing up as a feature request but may be a bug. I cannot tell because the `FlutterPlatformView` documentation isn't specific about what to do if there is a problem or internal error and a view cannot be returned by `createWithFrame`. Experimentally, I am seeing a crash when that happens (see below). The use case here is that sometimes we try to do something that may fail (e.g., load a resource, or the user of our library did something unexpected and we're in a bad state). In these cases we simply want to log an error and return `nil` because there's not much we can do. However, if we return `nil` from this method, we see a crash.

## Proposal

`createWithFrame` (and the equivalent on Android) should allow a `nil` (or `null`) response, or have some other way to deal with error handling if a view cannot be created. In this case, the PlatformView is not created, and the problem should be logged, or at least handled gracefully in Flutter by providing an error on the PlatformView creation, and not a crash.

## Crash Stack

*** First throw call stack:
```
(
	0   CoreFoundation                      0x000000010be096fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010b3adac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010bd57ddc _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010bde386d -[__NSPlaceholderArray initWithObjects:count:] + 237
	4   CoreFoundation                      0x000000010bdf82a4 +[NSArray arrayWithObjects:count:] + 52
	5   Flutter                             0x00000001089d07fa -[FlutterPlatformViewSemanticsContainer initWithSemanticsObject:] + 405
	6   Flutter                             0x00000001089d16dc _ZN7flutter19AccessibilityBridge15UpdateSemanticsENSt3__113unordered_mapIiNS_13SemanticsNodeENS1_4hashIiEENS1_8equal_toIiEENS1_9al<…>
```

**Comment by chinmaygarde** [comment]
`FlutterPlatformViewSemanticsContainer` has been reworked and this should no longer be an issue.
