### ISSUE TITLE
urllauncher\WebViewActivity.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by Xgamefactory** [flutter/flutter#39423]
`Note: C:\Users\user\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher-5.1.2\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
`

**Comment by Jayant11** [comment]
@Xgamefactory Which Gradle version are you using?

**Comment by BondarenkoStas** [comment]
Duplicate of #37616

**Comment by iamshubhamsaurav** [comment]
Try changing the minSdkVerion to a higher version. I changed the minSdkVerion from 16 to 23 and it worked. Go to the app/build.gradle file and changing the version.

**Comment by bwerere** [comment]
I tried the minSdkVersion from 16 to 23 even after flutter clean and it did not work. Still having the issue.

**Comment by tony123S** [comment]
not working for me too. I'm using `Flutter 1.20.2 • channel stable `

**Comment by leszekkrol** [comment]
Not working for me too Flutter (Channel dev, 1.23.0-18.0.pre)

**Comment by yaroaxito** [comment]
I am having the same problem.
