### ISSUE TITLE
Linking to the Rendering Pipeline tech talk video from website

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3943]
Hi,

Can we link to our new Rendering Pipeline tech talk video, from flutter.io ? Here's the video: https://www.youtube.com/watch?v=UUfXWzp0-DU

Thanks!

**Comment by sethladd** [comment]
cc @qchong

**Comment by qchong** [comment]
Added a link to the video, under the 'Developer guides' section.

**Comment by sethladd** [comment]
Thank you!
