### ISSUE TITLE
Style guides, coding conventions for Flutter Engine

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#39442]
While we have a [style guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo) for the flutter/flutter repo, we should also document style/coding conventions for the flutter/engine repo. 

This should be linked from the wiki and the engine's CONTRIBUTING.md file, and cover the following languages:
* C++
* Objective-C / Objective-C++
* Java

**Comment by cbracken** [comment]
Due to common history and our current `clang-format` conventions, I'd be tempted to use the Chromium style guides (or create some minor variant thereof) unless we've got a strong preference for something else (e.g. Google's style guides).

/cc @chinmaygarde @stuartmorgan @Hixie for thoughts.

**Comment by chinmaygarde** [comment]
go/fluttercpp has always pointed to the Google Style guide.

**Comment by cbracken** [comment]
I'm thinking something public-facing, linked from the wiki/CONTRIBUTING.md, since go links are Google-internal.

**Comment by chinmaygarde** [comment]
https://google.github.io/styleguide/cppguide.html is public. I have been pointing to sections from the same on reviews. Sorry, the go link was just for convenience.

**Comment by stuartmorgan** [comment]
Over time there have been deliberate efforts to minimize the number of things in the Chromium style guide (i.e., make it as much as possible just "follow the Google style guide"). I'm not sure there's much if anything left there that we need.

My preference would be to point to Google style, and only document divergences if we absolutely have to (and if that becomes equivalent to "follow the Chromium style guide", we could do that).

**Comment by cbracken** [comment]
SGTM. Does either one of you want to do the honours of linking them from the style guide page of our wiki?

**Comment by stuartmorgan** [comment]
PR out for updating CONTRIBUTING. Once that lands I'll update the wiki to point there for engine code; it's so heavily framework-focused right now, and already so long, that I think pointing to CONTRIBUTING makes more sense than inlining it there.
