### ISSUE TITLE
How do I get the currently displayed page？

### ISSUE THREAD

**Issue by dingzuhua** [flutter/flutter#39454]
I have a requirement that I need to jump to a specific page when I receive a notification, but I don't need to jump if the current display page is the page specified in the notification. How do I get the current page? BuildContext is not the current Context, it's something I saved when I created the jpush service.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
