### ISSUE TITLE
Implement Multi image picker view in image picker plugin

### ISSUE THREAD

**Issue by b-jan** [flutter/flutter#39452]
There is currently another library for multi image picker:
https://github.com/Sh1d0w/multi_image_picker

![hero](https://user-images.githubusercontent.com/24225949/63901738-33d93c00-ca06-11e9-85df-00528c0e760c.png)

We could improve the official flutter image picker library with the same mosaic view which is a lot better on Android that the files view.

Is this on the roadmap?

**Comment by darshankawar** [comment]
There's already a similar open proposal describing this issue, https://github.com/flutter/flutter/issues/16054
Closing this as duplicate.
