### ISSUE TITLE
[webview_flutter] Input needs to be tapped twice on Redmi Note 4

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#39451]
>I only tested 0.3.11+2 in MI device and in this case the issue was:
first tap:
keyboard shows up and text field gets focus. But no input.
second tap:
keyboard still present and text field with focus (all apparently the same). But input is displayed now in text field.

_Originally posted by @pedrosalesmiranda in https://github.com/flutter/flutter/issues/35867#issuecomment-521035335_

**Comment by pedrosalesmiranda** [comment]
@deandreamatias super thanks for the tip. In fact in one of the MI devices i tried it worked I will test in others soon and if all ok I will suggest to close this issue. However keyboard still does not go way when we go to different url. Does it also happen to you @deandreamatias ?

**Comment by deandreamatias** [comment]
@pedrosalesmiranda 
Yes, this bug exists and is tracked here #36478. There have a discussion about this and possible solutions

**Comment by deandreamatias** [comment]
@mklim you can close this issue please? Thanks
