### ISSUE TITLE
Bitcode on in Xcode 11: Unable to parse Clang version from "Apple clang version 11.0.0 (clang-1100.0.33.5)". Expected a string like "Apple LLVM version  #.#.# (clang-####.#.##.#)"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#39458]
## Steps to Reproduce

When I turn on bitcode I get this error in from Xcode 11:
```
[module_test_ios] [STDOUT] stdout:     Unable to parse Clang version from "Apple clang version 11.0.0 (clang-1100.0.33.5)". Expected a string like "Apple LLVM version  #.#.# (clang-####.#.##.#)".
```

Maybe this template changed between the version of clang packaged in Xcode 10 and Xcode 11?

See https://github.com/flutter/flutter/blob/cb965495d7ab4fb8d35ea141685bfcb60aa1618c/packages/flutter_tools/lib/src/commands/build_aot.dart#L229

**Comment by jmagman** [comment]
@dnfield https://github.com/flutter/flutter/commit/07f079a9324953a3da47c9f040f6b67f44323854

**Comment by jmagman** [comment]
(@dnfield Good error message, by the way!)

**Comment by jmagman** [comment]
Here's the full output:
```
$ xcrun clang --version   
Apple clang version 11.0.0 (clang-1100.0.33.5)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /path/to/Xcode-beta6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by dnfield** [comment]
this makes me sad.  I actually thought to myself "would they change this?" and checked 9.x and saw it was the same and thought I was ok.  This should be easy to fix though.
