### ISSUE TITLE
PHPSESSID changes on every request even when encrypted cookie remains same

### ISSUE THREAD

**Issue by thehitechpanky** [flutter/flutter#39468]
I am using new http client for flutter http requests. When I make first request to server, it sends me cookie and phpsessid. When I make subsequent request to server it sends me same encrypted cookie but this time phpsessid is different. The server is unable to identify me client on subsequent requests.

PS. I have also tried requests library and dio and nothing good happened.
PS. My server is https (secured)
PS. While using same apis via chrome, no issue occurs. Same is case with Java app.

Kindly please explain detailed steps (working example) to maintain cookies and sessions with https server in flutter as I couldn't find any specific documentation for the same.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn't seem to be something wrong with Flutter itself.
Anyway will set the documentation label and keep issue open.

**Comment by kf6gpe** [comment]
I'd like to refer you to one of the channels at https://flutter.dev/support --- if this looks like a bona fide bug, you might want to consider opening an issue in the Dart language repo at https://github.com/dart-lang/sdk. Thanks!
