### ISSUE TITLE
camera requestPermissions Error

### ISSUE THREAD

**Issue by wangbang79408854** [flutter/flutter#39460]
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0\n//
io.flutter.plugins.camera.CameraPermissions$CameraRequestPermissionsListener.onRequestPermissionsResult(CameraPermissions.java:63)\n// 
io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:194)\n/io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:127io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:137)\
android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7111)\
t android.app.Activity.dispatchActivityResult(Activity.java:6963)\n//
android.app.ActivityThread.deliverResults(ActivityThread.java:4371)

**Comment by BugsBunnyBR** [comment]
Hello @wangbang79408854  and thanks for your bug report!
Would you mind informing which version of Camera plugin are you using?
Could you describe how to reproduce this issue?

**Comment by wangbang79408854** [comment]
Hello, @BugsBunnyBR ，I am using the ^0.5.4 version of the machine plug-in. When packaging the online market application store, the machine traversal test is returned by the market. The error log is as seen above. I would like to ask for your help. Thank you.

**Comment by BugsBunnyBR** [comment]
Thanks for your reply @wangbang79408854, at the moment I am unable to replicate the problem.
 Could you describe how to reproduce this issue in more detail? Could you provide a small project where it occurs?

**Comment by janmoppel** [comment]
Hello @wangbang79408854 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
