### ISSUE TITLE
Is there any way to add required asteric sign in InputDecoration labelText and give red color for sign?

### ISSUE THREAD

**Issue by Basher7** [flutter/flutter#39467]
> I want to add asteric sign in InputDecoration labelText and change color(red) of it so that user understand easily this field is required. how can I do this?

```dart
TextField(
    autofocus: true,
    controller: _nameCtrlr,
    keyboardType: TextInputType.text,
    decoration: InputDecoration(
    labelText: "Name *",
   ))
```
**Expected result**
![label](https://user-images.githubusercontent.com/30956773/63916194-b8a17580-ca59-11e9-8f03-51878962fbd4.png)

Thanks in advanced.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn't seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
