### ISSUE TITLE
gradlew seems not to work for flutter run

### ISSUE THREAD

**Issue by flenst111** [flutter/flutter#39473]
```
ProcessException: ProcessException: Process "/home/paulsen/mygit/web/services/untitled/android/gradlew" exited abnormally:
Fehler: Hauptklasse java.se.ee konnte nicht gefunden oder geladen werden
  Command: /home/paulsen/mygit/web/services/untitled/android/gradlew -v
```

I don't know why! I tried to  update gradle in different places, but it does n#t work,

**Comment by BondarenkoStas** [comment]
Please provide ```flutter doctor -v``` output as well as the steps to reproduce the issue.

**Comment by flenst111** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale de_DE.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/paulsen/flutter
    • Framework revision 20e59316b8 (vor 6 Wochen), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/paulsen/ide/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/paulsen/ide/android-sdk-linux
    • Java binary at: /home/paulsen/ide/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/paulsen/ide/android-studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /home/paulsen/ide/ideaiu
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423

[✓] Connected device (1 available)
    • AGS2 W09 • U8BBB19114151058 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by BondarenkoStas** [comment]
The question doesn't seem to be a flutter issue but related to Android SDK and configuration. Closing it as it's not an issue report.
