### ISSUE TITLE
Invalid `Podfile` file: undefined method `script_phase'

### ISSUE THREAD

**Issue by mxl123** [flutter/flutter#39471]
## Steps to Reproduce

Flowing the guid https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps, install flutter module to my iOS APP, my iOS project path is "/Users/xxx/PPP/XXXXXX/"

1. Create my_flutter module
```
$ cd /Users/xxx/PPP/XXXXXX/
$ flutter create -t module my_flutter
```

1. Add code in my podfile
```
flutter_application_path = 'my_flutter/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
```
2. Run shell 
```
$ pod _1.6.0_ install
```

## Logs

```
[!] Invalid `Podfile` file: undefined method `script_phase' for #<Pod::Podfile:0x007f97d2341400>.

 #  from /Users/xxx/PPP/XXXXXX/Podfile:18
 #  -------------------------------------------
 #  target 'XXXXXX' do
 >    install_all_flutter_pods(flutter_application_path)
```

```
$ flutter doctor -v
[✓] Flutter (Channel master, v1.9.7-pre.21, on Mac OS X 10.14.2 18C54, locale zh-Hans-CN)
    • Flutter version 1.9.7-pre.21 at /usr/local/flutter
    • Framework revision 9f4ab273f1 (5 hours ago), 2019-08-28 20:02:08 -0700
    • Engine revision f52c0b9270
    • Dart version 2.5.0


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.1)
    • Android SDK at /Users/mxl/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        "/Users/mxl/Library/Android/sdk/tools/bin/sdkmanager" "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.dev/setup/#android-setup for detailed instructions.
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
        pod setup

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] Connected device (1 available)
    • ip7 • c16d87b80cec2bc50991179f841ff2841xxxxxx • ios • iOS 11.1

! Doctor found issues in 3 categories.

```

I also have cocoapods 1.6.0

```
$ gem list --local | grep cocoapods
cocoapods (1.7.5, 1.7.4, 1.6.0, 1.4.0, 1.2.1)
cocoapods-core (1.7.5, 1.7.4, 1.6.0, 1.4.0, 1.2.1)
cocoapods-deintegrate (1.0.4)
cocoapods-downloader (1.2.2)
cocoapods-packager (1.5.0)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.1.0)
cocoapods-trunk (1.3.1)
cocoapods-try (1.1.0)
```

My Podfile is like this.
```
source 'https://github.com/CocoaPods/Specs.git'
source 'http://xxx/tfs/xxx/xxSpecs'
platform :ios, '9.0'
inhibit_all_warnings!
install! 'cocoapods',
:deterministic_uuids => false

flutter_application_path = 'my_flutter/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'XXXXXX' do
  install_all_flutter_pods(flutter_application_path)
end
```

**Comment by BondarenkoStas** [comment]
Not sure if it may help, but can you please try to create my_flutter as sibling? I mean in ```cd /Users/xxx/PPP``` and to set absolute ```flutter_application_path``` in Podfile?

**Comment by mxl123** [comment]
> Not sure if it may help, but can you please try to create my_flutter as sibling? I mean in `cd /Users/xxx/PPP` and to set absolute `flutter_application_path` in Podfile?

Thank you, I tried, but don't work, the same error.

**Comment by mxl123** [comment]
I try the same Podfile in my new Project, it work fine. I don't know what 'script_phase' means.

I find the  'script_phase' in podhelper.rb

```
script_phase :name => 'Run Flutter Build Script',
    :script => "set -e\nset -u\nsource \"#{flutter_export_environment_path}\"\n\"$FLUTTER_ROOT\"/packages/flutter_tools/bin/xcode_backend.sh build",
    :input_files => [
      File.join('${SRCROOT}', flutter_application_path, '.metadata'),
      File.join('${SRCROOT}', relative, 'App.framework', 'App'),
      File.join('${SRCROOT}', relative, 'engine', 'Flutter.framework', 'Flutter'),
      flutter_export_environment_path
    ],
    :execution_position => :before_compile
```

**Comment by mxl123** [comment]
Maybe it's because some of my Xcode configurations are causing this problem.

**Comment by jmagman** [comment]
```
! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
```
I know you have CocoaPods 1.6.0 installed somewhere, but I think it's grabbing something much older.  Can you make sure your `pod --version` is > 1.6.0?

**Comment by mxl123** [comment]
> ```
> ! CocoaPods out of date (1.6.0 is recommended).
>         CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
>         Without CocoaPods, plugins will not work on iOS or macOS.
>         For more info, see https://flutter.dev/platform-plugins
> ```
> 
> I know you have CocoaPods 1.6.0 installed somewhere, but I think it's grabbing something much older. Can you make sure your `pod --version` is > 1.6.0?

I run install with version like:
```
$ pod _1.6.0_ install
```
And this is the version info:
```
$ pod _1.6.0_ --version
1.6.0
```

**Comment by mxl123** [comment]
> ```
> ! CocoaPods out of date (1.6.0 is recommended).
>         CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
>         Without CocoaPods, plugins will not work on iOS or macOS.
>         For more info, see https://flutter.dev/platform-plugins
> ```
> 
> I know you have CocoaPods 1.6.0 installed somewhere, but I think it's grabbing something much older. Can you make sure your `pod --version` is > 1.6.0?

Thanks for your reply.

As I said before, it is fine for me to use it in new projects. So it may not be related to the pod version？ 

I am curious that 'script_phase' has something to do with the configuration in the xcode. Which part of the configuration should I focus on? I will check and try to fix them.

**Comment by jmagman** [comment]
But what's the output of `pod --version` without the `_1.6.0_`?  It's not picking up 1.6.0 as the default, it's picking up something lower.  Until you stop getting `! CocoaPods out of date (1.6.0 is recommended).` in your `flutter doctor` it's not going to pick up the `script_phase` (a requirement for modules but not new apps).

**Comment by mxl123** [comment]
> But what's the output of `pod --version` without the `_1.6.0_`? It's not picking up 1.6.0 as the default, it's picking up something lower. Until you stop getting `! CocoaPods out of date (1.6.0 is recommended).` in your `flutter doctor` it's not going to pick up the `script_phase` (a requirement for modules but not new apps).

Thank you, I uninstalled all other versions and it works fine.
