### ISSUE TITLE
[google_maps_flutter] Polygon and Circles stroke width different between iOS and Android

### ISSUE THREAD

**Issue by JamesMcIntosh** [flutter/flutter#39476]
When creating a polygon with stroke of 10 on Android the actual number of pixels is 10 while on iOS is multiplied by the screen density making it much thicker on iOS than Android.

Looks like this problem has already been fixed for polylines in the PolylineController but hasn't been done for circles or polygons.

https://github.com/iskakaushik/plugins/commit/5be4feca4983532ed5a1b85baf05b8fa088546d3#diff-1c7f83c2ba58345880fe8a6abd5bdaf4

The SDK docs for each platform describe strokeWidth as:

Android: Line segment width in screen pixels.
https://developers.google.com/android/reference/com/google/android/gms/maps/model/Polygon

iOS: The width of the polygon outline in screen points.
https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_polygon.html

Screen points are the same as idea as density pixels.
https://developer.apple.com/library/archive/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/Displays/Displays.html

My temporary workaround is to do the multiplication myself
```
void toStrokeWidth(int width) {
  if (Platform.isAndroid) {
    return width * WidgetsBinding.instance.window.devicePixelRatio.ceil();
  }

  return width;
}
```

I'm not sure if this has any flow on effects if the value is changed in regards to serializing / deserializing as I haven't looked to see if the API returns objects from native back to flutter which contain the stroke width.

**Comment by TahaTesser** [comment]
Hi @JamesMcIntosh 
Is this issue still valid?
Thank you

**Comment by JamesMcIntosh** [comment]
@TahaTesser  The fix we merged on Feb 11 2020
