### ISSUE TITLE
Graphics Memory very high in real device

### ISSUE THREAD

**Issue by lequanghiep74** [flutter/flutter#39475]
I use [flutter flame](https://github.com/flame-engine/flame) to make animation and `precacheImage` to preload Image.
In emulator, everything's fine. But when i run app in real device, graphics memory is very high and app crash. My other application only shows the list and the image has the same issue.
Ps: Flutter v1.9.6

In emulator:
![](https://i.ibb.co/16CN1Y1/Screen-Shot-2019-08-29-at-5-19-56-PM.png)

In real device:
![](https://i.ibb.co/DpbQXkf/Screen-Shot-2019-08-29-at-5-16-54-PM.png)

**Comment by BondarenkoStas** [comment]
Please provide ```flutter doctor -v``` output as well as the steps to reproduce the issue. It may be connected to a specific device.

**Comment by lequanghiep74** [comment]
This issue only appear on android device with chipset Snapdragon - gpu Adreno (LG G6, LG v40, huawei honor 7A). Galaxy Note 5 with exynos working fine. 

`[✓] Flutter (Channel unknown, v1.9.6, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.9.6 at /Users/hieplq/Downloads/flutter
    • Framework revision 35de8d5278 (21 hours ago), 2019-08-28 16:49:49 +0300
    • Engine revision f8c4546eb4
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/hieplq/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/hieplq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/hieplq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android Studio.app/Contents
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.6)
    • IntelliJ at /Users/hieplq/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • LGM G600L                 • LGMG600L743f1c72 • android-arm64 • Android 8.0.0 (API 26)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 9 (API 28) (emulator)

**Comment by mjaffa-figure** [comment]
@dnfield Does this have to do with this issue:
#28037
https://github.com/flutter/flutter/issues/28037

**Comment by mjaffa-figure** [comment]
@lequanghiep74 Try running this on flutter 1.1.8 and see if the crashing goes away for you. If flutter flare is supported on that version of flutter.

**Comment by maks** [comment]
I would also suggest trying current master channel:
```
Flutter 1.10.15-pre.37 • channel master • https://github.com/flutter/flutter.git
Framework • revision 609de08881 (12 minutes ago) • 2019-10-09 19:33:43 -0400
Engine • revision e693192167
Tools • Dart 2.6.0 (build 2.6.0-dev.6.0 41d13f0ffe)
```
for me this resolved an issue with OOM crashes (using profile build) of my app running on a Neuxs 5x (also an adreno gpu though not sure if thats relevant). 

My crash came from scrolling back and forwards through a listview (~60 items) with medium sized images (850x435 JPEGs) on each item, memory usage would just keep grtowing until OOM using Flutter current stable and beta, but on master the mem usage peeks at around 100MB below the 800MB threshold that would cause the OOM crashes, so some of the recent fixes for image memory management issues on master branch fixed at least my issue.

**Comment by darshankawar** [comment]
Hi @lequanghiep74 
Is this still a valid issue using latest Flutter version ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by dnfield** [comment]
This may be helped by https://github.com/flutter/flutter/issues/58870

**Comment by pedromassangocode** [comment]
@dnfield should this be reopened?
