### ISSUE TITLE
flutter install fails for iOS

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3947]
```
%flutter install                                                                                      [/src/game]
Installing io.flutter.spaceblast to flutter_ipod_touch...
Uploading .generated package contents... DONE.
Installing '(null)'
 - CreatingStagingDirectory (5%)
 - ExtractingPackage (15%)
 - InspectingPackage (20%)
 - Error occurred: PackageInspectionFailed
```

`flutter run` works fine.

@chinmaygarde @devoncarew

**Comment by eseidelGoogle** [comment]
This is mostly important because it blocks @yjbanov for using --profile builds for testing.

**Comment by eseidelGoogle** [comment]
I've asked @tvolkert to own or find an owner for.

**Comment by tvolkert** [comment]
@eseidel I'm still seeing problems with `flutter run` as well - https://github.com/flutter/flutter/issues/1823

Does it work for you on a device?

**Comment by eseidelGoogle** [comment]
I have an iPod Touch which appears to have the right certs set up for which `flutter run` works but `flutter install` fails as the above.  I don't think I've hit #1823 myself yet.

**Comment by eseidelGoogle** [comment]
I appear to have filed this twice, also #3933.

**Comment by eseidelGoogle** [comment]
Chinmay or Todd could you take a look at this today?  Hopefully it's an easy fix since `flutter run` clearly knows how to install. :)

**Comment by tvolkert** [comment]
I'm on it
