### ISSUE TITLE
[web]: listview item click event bug in some android devices' browser--flutter_web

### ISSUE THREAD

**Issue by JiweiMaster** [flutter/flutter#39478]
when come into page which contained listview on the first time,slide the page and click the item of listview ,the click event won't happened on some android mobile device browers, such as the dingding app

**Comment by BondarenkoStas** [comment]
Please provide ```flutter doctor -v``` output as well as more detailed information to reproduce the issue (maybe code example reproducing it etc.)

**Comment by JiweiMaster** [comment]
import 'package:flutter_web/material.dart';

class Test2 extends StatefulWidget{
  @override
  State<StatefulWidget> createState() {
    return Test2State();
  }
}

class Test2State extends State<Test2>{
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: ListView.builder(
          itemCount: 25,
          itemExtent: 60,
          itemBuilder: (BuildContext context, int position){
            return GestureDetector(
              child: Container(
                child: Text("item->>>"+position.toString()),
              ),
              onTap: (){
                showAlertDialog(context,"test");
              },
            );
          }
        ),
      ),
    );
  }


  void showAlertDialog(context,String message){
    showDialog(
        context: context,
        builder: (BuildContext context){
          return AlertDialog(
            title: Text("Alert"),
            content: Text("$message"),
            actions: <Widget>[
              FlatButton(
                color: Color(0xff3A99D8),
                child: Text("SURE",style: TextStyle(color: Colors.white),),
                onPressed: (){
                  Navigator.pop(context);
                },
              )
            ],
          );
        }
    );
  }

}

**Comment by JiweiMaster** [comment]
> Please provide `flutter doctor -v` output as well as more detailed information to reproduce the issue (maybe code example reproducing it etc.)

you can try it, but must run(html ,js) on the Android device's browser not on chrome,

**Comment by JiweiMaster** [comment]
on moretest,it happened on some mobiles or some apps,phone like HUAWEI, app like dingding

**Comment by JiweiMaster** [comment]
may be browser incompatibility problem

**Comment by darshankawar** [comment]
Hi @JiweiMaster 
Is this still a valid issue ?
If so, can you provide `flutter doctor -v`  ? You may want to test this with `webview_flutter` plugin to see if it resolves your issue.
Thanks.
