### ISSUE TITLE
Is there is a way to use NoiseSuppressor in Flutter camera plugin to avoid background noise?

### ISSUE THREAD

**Issue by divyanshub024** [flutter/flutter#39489]
Android provides a way to use NoiseSuppressor to avoid background noise. Can this be achieved with the flutter camera API?

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
