### ISSUE TITLE
Flutter Plugin(ver 38.2.4) cause android studio not to start properly

### ISSUE THREAD

**Issue by Vixb1122** [flutter/flutter#39481]
## Steps to Reproduce

1. Upgrade Android Studio to Version 3.6 Canary 8
2. Install flutter plugin with newest version
3. Restart Android Studio and Android Studio can't start properly.
![Snipaste_2019-08-29_20-59-16](https://user-images.githubusercontent.com/17810492/63944136-95031d00-caa3-11e9-95d3-096efd280fb7.jpg)
4. Delete `flutter-intellij` folder from `%USERPROFILE%\.AndroidStudioPreview3.6\config\plugins` path.
5. Android Studio can start properly.

## Output

```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.295], locale zh-CN)
    • Flutter version 1.7.8+hotfix.4 at C:\Develop Tools\flutter
    • Framework revision 20e59316b8 (6 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at E:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = E:\Android\sdk
    • Java binary at: C:\Develop Tools\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.
[√] Android Studio (version 3.6)
    • Android Studio at C:\Develop Tools\Android Studio
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6527
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
```

**Comment by BondarenkoStas** [comment]
Please post the issue to https://github.com/flutter/flutter-intellij as well.

**Comment by BugsBunnyBR** [comment]
There is already some issues there https://github.com/flutter/flutter-intellij/issues/3840 and https://github.com/flutter/flutter-intellij/issues/3834, should we close this one?
