### ISSUE TITLE
[web] Icon font from package doesn't load correctly

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#39486]
```
[✓] Flutter (Channel master, v1.9.7-pre.21, on Mac OS X 10.14.5 18F132, locale en-CN)
    • Flutter version 1.9.7-pre.21 at /Users/user/opt/flutter
    • Framework revision 9f4ab273f1 (10 hours ago), 2019-08-28 20:02:08 -0700
    • Engine revision f52c0b9270
    • Dart version 2.5.0
```

I am using the unforked flutter web version. (I use `flutter create --web <project_name>` to create the project).

I am wondering how I can use an icon plugin for instance https://pub.dev/packages/material_design_icons_flutter

**Edited:**

I tried many ways to make it work, but none of them works. For example, the normal flutter workflow:

pubspec.yaml:

```yaml
dependencies:
  material_design_icons_flutter: 3.2.4096
```

main.dart:

```dart
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';

....
            Icon(MdiIcons.account,),
...
```

and then execute `$ flutter run -d chrome`

The font file `materialdesignicons-webfont.ttf` is loaded in chrome browser, but it's not rendered:

<img width="500" alt="Screen Shot 2019-08-30 at 01 07 49" src="https://user-images.githubusercontent.com/1555508/63961793-27b3b400-cac4-11e9-94f2-ff7aeadd8bc2.png">

So can anyone please teach me how I can use `material_design_icons_flutter` package in unforked flutter web? Thanks a lot.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.

**Comment by sgon00** [comment]
@BondarenkoStas I friendly disagree. Because (1) there are many such questions here and still open. (2) If you disagree with my first point, you can consider this is a feature request which is allowed to be asked here. Because I think this is not doable at present. (3) This question is about cutting-edge technique unforked flutter web and I doubt anyone in stackoverflow can answer it, otherwise, I will simply ask there instead. 
But whatever, you are the Boss.

**Comment by BondarenkoStas** [comment]
Actually yes, it makes sense, sorry for closing without proper attention. I reopened it, hope the help will come:)

**Comment by sgon00** [comment]
@BondarenkoStas thank you very much for reopening this issue. I hope I will get some help. ^_^

**Comment by jonahwilliams** [comment]
Please see https://flutter.dev/docs/development/ui/assets-and-images. The workflow for Flutter for web is not different from regular flutter

**Comment by sgon00** [comment]
@jonahwilliams  I am sorry to interrupt you. did you really read my question? I read that link many times. That has nothing to do with my question. Especially, you said "The workflow for Flutter for web is not different from regular flutter". How is that even possible? To use `material_design_icons_flutter` icon in flutter, I simply do `import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';`, that's all. Do you mean I can do the same for unforked flutter_web? That is impossible. That won't work at all.

**Comment by jonahwilliams** [comment]
Sorry!

**Comment by jonahwilliams** [comment]
Looks like the ttf is loaded correctly for web fonts, but in this case it isn't rendering.


<img width="790" alt="Screen Shot 2019-08-29 at 9 36 16 AM" src="https://user-images.githubusercontent.com/8975114/63959197-82a3c780-ca40-11e9-8235-74f24ddcd000.png">


cc @yjbanov @mdebbar

**Comment by jonahwilliams** [comment]
Repro code:
```

import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';

class MyWidget extends StatelessWidget {
  Widget build(BuildContext context) {
    return IconButton(
      // Use the MdiIcons class for the IconData
      icon: new Icon(MdiIcons.infinity),
      onPressed: () { print('Using the sword'); }
     );
  }
}
void main() => runApp(MaterialApp(home: Scaffold(body: Center(child: MyWidget()))));

```

**Comment by yjbanov** [comment]
@hterkelsen Anything changed in the way we load fonts recently?

**Comment by hterkelsen** [comment]
Fonts that come from package assets have '/' in the family name, eg 'packages/material_design_icons_flutter/MaterialDesignIcons'. This is new in the external workflow. There may be some places where we are not quoting the font family name, which causes font-strings like '12px packages/material_design_icons_flutter/MaterialDesignIcons' to be improperly parsed.

I think the solution will be to quote the font family name whenever we create a CSS font string.

**Comment by hterkelsen** [comment]
That seems to have been the problem. I updated us to quote font family names and I'm seeing this now:

![infinity](https://user-images.githubusercontent.com/1961493/63978630-a4667400-ca6b-11e9-9a06-06cf3c5354ef.png)

I'll send out a PR with the fix. This should also fix the cupertino icons problem as well.
