### ISSUE TITLE
Flutter Drive Run All Test

### ISSUE THREAD

**Issue by timrijckaert** [flutter/flutter#39482]
In our Flutter application we have multiple integration tests.
I run them one by one by issuing:

`flutter drive --target=test_driver/screenshot.dart`

However I can't seem to figure out how to run all integration test inside the `test_driver` folder?

The [official documentation](https://flutter.dev/docs/cookbook/testing/integration/introduction) does not tell.

**Comment by Bucerella** [comment]
I know there is no such thing yet.

**Comment by jonahwilliams** [comment]
We're not going to add this functionality to flutter drive because it is trivially scriptable for CI systems or locally.
