### ISSUE TITLE
Running app creates new ephemeral files without gitignoring them

### ISSUE THREAD

**Issue by RedBrogdon** [flutter/flutter#39491]
## Steps to Reproduce

With the current master branch (v1.9.6-pre.57), the project structure for a Flutter app includes an ephemeral file called `flutter_export_environment.sh`. There's a comment included in the file that indicates it shouldn't be checked into source control, and projects created with v1.9.6 automatically get a gitignore that ignores the file (q.v. #37593).

If you create a project with the current stable branch (v1.7.8+hotfix.4), though, then upgrade flutter to master and run that project, you end up in an annoying situation in which `flutter_export_environment.sh` is generated by flutter, but it's *not* in your gitignore (which the SDK generates for new projects but doesn't modify afterward). 

This forces devs to:

1.  Notice that Flutter added a new file to their project.
2. Examine the file to see the comment that it's ephemeral.
3. Manually add it to their gitignores.

Odds are, the majority of devs will miss either Step 1 or Step 2.

It would be better for our overall DevExp if we had some way of avoiding this problem (one solution suggested by @stuartmorgan is to create a folder for the files that shouldn't be checked in and then gitignore that folder).

**Comment by jmagman** [comment]
Another option is a naming convention so a regex can be added to the .gitignore so going forward they get excluded.  Generated.xcconfig has the same issue.

**Comment by stuartmorgan** [comment]
A nice thing about the folder approach that I've found useful several times is that it's really easy to know what it's safe to nuke when there are issue. Deleting a folder is easier in some contexts (and I'd argue easier to understand in all) than deleting all files matching a pattern.

**Comment by christopherfujino** [comment]
I will add that once you get in this state, you cannot cleanly `flutter upgrade` again, because your git state isn't clean.

**Comment by jmagman** [comment]
As of https://github.com/flutter/flutter/pull/76830 there's a `Flutter/ephemeral` directory for future generated files.  It doesn't move any existing ones into that directory, though.

**Comment by christopherfujino** [comment]
> As of #76830 there's a `Flutter/ephemeral` directory for future generated files. It doesn't move any existing ones into that directory, though.

Due to this, I'm going to close this issue. It seems unlikely we'll apply a retroactive solution.
