### ISSUE TITLE
WidgetsFlutterBinding.ensureInitialized() takes down splash screen too early.

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#39494]
In https://github.com/flutter/flutter/pull/38464 we changed it to require a call to `WidgetsFlutterBinding.ensureInitialized` before your runApp if you want to access method channels. Unfortunately, this means that the native splash screen gets taken down too early and a black screen is shown. Repro-case:

```dart
import 'package:flutter/material.dart';
import 'dart:async';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  Timer(Duration(seconds: 10), () {
    runApp(Placeholder());
  });
}
```

(Instead of running a timer, a real app may wait for data from the native side before calling runApp).

**Comment by goderbauer** [comment]
It looks like the splash screen is taken down the first time we call `Window.render` [1]. We call this in a response to the engine calling our `Window.onDrawFrame` [2] callback. We set this callback up in `SchedulerBinding.initInstances()`, which is called as part of `WidgetsFlutterBinding.ensureInitialized()`.

So it looks like because we require the call to `WidgetsFlutterBinding.ensureInitialized()` earlier before runApp has had a chance to attach the root widget, we give the engine a chance to request a frame (by setting up our onDrawFrame callback) before we are ready. Since there is nothing to draw, it will return an empty Scene via `Window.render`, which unintentionally takes down the splash screen to reveal a blank black screen.


[1] https://master-api.flutter.dev/flutter/dart-ui/Window/render.html
[2] https://master-api.flutter.dev/flutter/dart-ui/Window/onDrawFrame.html

**Comment by goderbauer** [comment]
Before calling `Window.render` could we maybe check if the scene is empty and not send it down to the engine via Window.render? Or have the engine ignore empty scenes? @chinmaygarde 

Or can/should we delay setting up the onDrawFrame callback and friends to avoid that the engine asks us for the empty frame in the first place?

**Comment by tvolkert** [comment]
FYI, I've marked this in our bad builds (`v1.9.4`+)

**Comment by Hixie** [comment]
We should probably just not hook up onDrawFrame and onBeginFrame until someone calls scheduleFrame the first time. Should be a relatively easy change to the scheduler binding, IIRC.

**Comment by goderbauer** [comment]
Slight correction: It's not the framework setting the onDrawFrame callbacks that's causing the engine to request a frame at an inopportune moment. As Chimney confirmed, the framework has to actively request a frame via `Window.scheduleFrame`. That ultimately triggers the engine to call the framework's onDrawFrame callback.

Unfortunately, the WidgetsFlutterBinding calls `Window.scheduleFrame` when it is created via `RendererBinding.initRenderView`. (Which causes the engine to request a frame, which causes the framework to produce an "empty" frame, which takes down the splash screen.)

**Comment by goderbauer** [comment]
After more digging it turns out that the engine can actually request a frame from the framework without the framework ever asking for it via Window.scheduleFrame (e.g. when the viewport metrics become available, the engine will schedule a frame). The only way to avoid servicing that frame request on the framework side seems to be to not have onDrawFrame set up.

**Comment by vitor-gyant** [comment]
@goderbauer I'm facing this issue and it doesn't look to be fixed, yet. 

My flutter version is  1.9.8-pre.108 and I still see a black screen during the boot phase of the app.

This happens because I want to lock my app in portrait and I use the following code before calling runApp:

```
WidgetsFlutterBinding.ensureInitialized();

await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]);
```

In previous versions of Flutter WidgetsFlutterBinding.ensureInitialized() was not required but suddenly it started to crash on new versions and the fix is to call WidgetsFlutterBinding.ensureInitialized() before calling SystemChrome.setPreferredOrientations. The side effect was the black screen now.

Could you please let me know if a fix is expected soon or a possible workaround for this ? 

Thanks in advance,

**Comment by phoenixsky** [comment]
It's work on my iPhone
Only iOS simulator is not ok .

**Comment by HofmannZ** [comment]
I'm still facing this issue, I'm using the `beta` channel though.

```
Flutter 1.10.7 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e70236e36c (5 weeks ago) • 2019-10-02 09:32:30 -0700
Engine • revision 9e6314d348
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 1103600280)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.15.1 19B88, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)

• No issues found!
```

As de [bad builds](https://github.com/flutter/flutter/wiki/Bad-Builds#v194---v1104) wiki page describes this should be fixed in 1.10.4 and above, right?

**Comment by martinrybak** [comment]
This is still happening on `master`. To repro:

```dart
import 'package:flutter/material.dart';
import 'dart:async';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  Timer(Duration(seconds: 10), () {
    runApp(Placeholder());
  });
}
```

```
[✓] Flutter (Channel master, v1.12.5-pre.23, on Mac OS X 10.14.6 18G95, locale
    en-US)
    • Flutter version 1.12.5-pre.23 at /Applications/Flutter/master
    • Framework revision b5a85fcf48 (2 hours ago), 2019-11-19 18:58:28 +0100
    • Engine revision ecb32952ff
    • Dart version 2.7.0
```

**Comment by tvolkert** [comment]
@iapicca can you see if you can reproduce at tip-of-tree?

**Comment by goderbauer** [comment]
Also: What devices are people using that shows the problem? iOS or Android?

**Comment by martinrybak** [comment]
I can reproduce on iOS (both simulator and device), but not in the Android emulator. So it seems to be limited to iOS.

**Comment by goderbauer** [comment]
FWIW, I can reproduce this on tip-of-tree in an iOS simulator. 

@chinmaygarde When does the iOS embedder take the splash screen down? On Android, it happens the first time we call window.render, which is the expected behavior. On iOS it seems to happen earlier, though.

**Comment by tomgilder** [comment]
One option to work-around a black flash with another color is setting the UIWindow color at the top of didFinishLaunching in AppDelegate.swift:

```
    if let window = UIApplication.shared.delegate?.window as? UIWindow {
        window.backgroundColor = .white
    }
```

**Comment by matthewlloyd** [comment]
Still happening on the latest Flutter stable release, on the iOS simulator using martinrybak's repro code above.

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-US)

**Comment by matthewlloyd** [comment]
I worked around the issue by editing `flutter/packages/flutter/lib/src/rendering/binding.dart`, moving the line `addPersistentFrameCallback(_handlePersistentFrameCallback);` from `initInstances` into its own new method `initPersistentFrameCallback`, and calling that method from `main()` as `RendererBinding.instance.initPersistentFrameCallback();` immediately before the call to `runApp(app);`.

**Comment by azizainunnajib** [comment]
> I worked around the issue by editing `flutter/packages/flutter/lib/src/rendering/binding.dart`, moving the line `addPersistentFrameCallback(_handlePersistentFrameCallback);` from `initInstances` into its own new method `initPersistentFrameCallback`, and calling that method from `main()` as `RendererBinding.instance.initPersistentFrameCallback();` immediately before the call to `runApp(app);`.

@matthewlloyd i think i will need this in iOS device. are you sure this can solve the issue?
i still focus in android device because i dont have iOS device to simulating the issue.

**Comment by matthewlloyd** [comment]
It worked for my app in the iOS simulator and on a real device, but I can't guarantee it will work equally for yours; in any case I wouldn't recommend releasing an app for iOS without testing first, at least in the simulator. If you only have Windows available, you can create a Mac VM using the free VMWare Player and run the iOS simulator using instructions easily found online.

**Comment by azizainunnajib** [comment]
yeah, i know it. but my laptop is just like, you know, "baby hardware", so it will be hard. hahaha, but someday i'll try it.

**Comment by RoyGuanyu** [comment]
I have same issue on Android real device Asus Zenfone5Z Android 10, and iOS simulator. Android simulator doesn't have this issue.

Thanks for @azizainunnajib  's work around, this works in both ios/android x simulator/real device.
Hope this issue can be solved in master branch, thanks.

**Comment by cbracken** [comment]
@RoyGuanyu, this issue is iOS-specific. If you're experiencing something similar on Android, would you mind opening a [new issue](https://github.com/flutter/flutter/issues/new/choose) so we can track the work to fix it there? When you do so, if you wouldn't mind referencing this issue so that people can find one from the other, that would be fantastic. Thanks!

**Comment by Piinks** [comment]
> this issue is iOS-specific. If you're experiencing something similar on Android, would you mind opening a [new issue](https://github.com/flutter/flutter/issues/new/choose) 

🤦‍♀ I just closed an issue mentioning android that appeared to be a dupe, #47582

**Comment by BWhiteApps** [comment]
> I worked around the issue by editing `flutter/packages/flutter/lib/src/rendering/binding.dart`, moving the line `addPersistentFrameCallback(_handlePersistentFrameCallback);` from `initInstances` into its own new method `initPersistentFrameCallback`, and calling that method from `main()` as `RendererBinding.instance.initPersistentFrameCallback();` immediately before the call to `runApp(app);`.

This hack fixes the problem for me on both Android and iOS.

**Comment by xing634325131** [comment]
https://github.com/flutter/flutter/issues/47582 like this issue.
I have same issue on Android real device Samsung SM-G8850 Android9.

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.3 19D76,
    locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)`

**Comment by samueladekunle** [comment]
> I worked around the issue by editing `flutter/packages/flutter/lib/src/rendering/binding.dart`, moving the line `addPersistentFrameCallback(_handlePersistentFrameCallback);` from `initInstances` into its own new method `initPersistentFrameCallback`, and calling that method from `main()` as `RendererBinding.instance.initPersistentFrameCallback();` immediately before the call to `runApp(app);`.

@matthewlloyd, it works on Android, thank you for this fix. I was experiencing this issue on ```Flutter 1.12.13+hotfix.5```, I upgraded from ```v1.9.1+hotfix.6-stable```, where the issue was non-existent, at least for me. Please, does anybody know, if this issue has been fixed, on the latest stable channel (```Flutter v1.12.13+hotfix.8```)?

**Comment by floridait** [comment]
When will this fix end up in Stable?

**Comment by GensaGames** [comment]
Any updates on this? It's not friendly at all.

**Comment by floridait** [comment]
This is blocking us from going live. Can anyone say when this fix will be in stable?

**Comment by chernandez7** [comment]
+1

**Comment by danilof** [comment]
Hi to all, I use @matthewlloyd solution but black screen was again there. And then I added timer for 2s and change order to call his function and now it is OK:
...
WidgetsFlutterBinding.ensureInitialized();
runApp(MyApp());
Timer(Duration(milliseconds: 2000), () {
      RendererBinding.instance.initPersistentFrameCallback();
 });
...
I know it is ugly workaround but we need to publish app!  Flutter team come on!

**Comment by Genora51** [comment]
Any news on when this will be in stable?

**Comment by chunhtai** [comment]
I investigated a little bit, Both android and IOS will take down the splash screen when they receive the first frame from flutter. In IOS, it will sends a semantics enable signal to framework as soon as the binding is initialized. When framework received the signal, it will call scheduleInitialSemantics which then calls requestVisualUpdate to schedule a frame. This makes engine think framework is ready to produce the first frame and take down the splash.

I am currently to see if we can defer the schedule frame until the root widget has been attached.

**Comment by goderbauer** [comment]
Interesting. I wonder if scheduleInitialSemantics should inly request a visual update if the first frame has already been rendered.

**Comment by zzterrozz** [comment]
Still facing the same issue with flutter 1.22
What is the correct way to fix this please ?

**Comment by chunhtai** [comment]
@zzterrozz the original issue has been fixed, it is likely a different issue, can you file a new issue?

**Comment by AlmogRnD** [comment]
I'm still facing this issue any news

**Comment by chunhtai** [comment]
@AlmogRnD please file a new issue

**Comment by AlmogRnD** [comment]
@chunhtai just did that https://github.com/flutter/flutter/issues/73418
