### ISSUE TITLE
flutter/plugins should be linted

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#39499]
`flutter/engine` has a lint in place to catch issues like the wrong SDK methods being used for the bound. Ideally we should have this for our first party plugins as well, it would catch issues like flutter/plugins#2029. I'm not sure exactly how we'd go about setting this up on our CI. [The engine linter is here](https://github.com/flutter/engine/tree/master/tools/android_lint). flutter/plugins has different packages with different minSdk versions, and also uses gradle.

**Comment by stuartmorgan** [comment]
We're now running the Java linter as part of CI.
