### ISSUE TITLE
Cannot codesign Flutter.framework, replacing existing signature, Permission denied

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#39507]
## Steps to Reproduce

```
cd dev/
SHARD=add2app_test dart bots/test.dart
```

## Logs
https://cirrus-ci.com/task/6430807339565056?command=test_all#L54
```
total size is 94542653  speedup is 1.00
Stripped /Users/m/Library/Developer/Xcode/DerivedData/ios_add2app-btprswwixqqclofvuogmdxvymovu/Build/Products/Debug-iphonesimulator/ios_add2app.app/Frameworks/Flutter.framework/Flutter of architectures: armv7 arm64
Code Signing /Users/m/Library/Developer/Xcode/DerivedData/ios_add2app-btprswwixqqclofvuogmdxvymovu/Build/Products/Debug-iphonesimulator/ios_add2app.app/Frameworks/Flutter.framework with Identity -
/usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements '/Users/m/Library/Developer/Xcode/DerivedData/ios_add2app-btprswwixqqclofvuogmdxvymovu/Build/Products/Debug-iphonesimulator/ios_add2app.app/Frameworks/Flutter.framework'
/Users/m/Library/Developer/Xcode/DerivedData/ios_add2app-btprswwixqqclofvuogmdxvymovu/Build/Products/Debug-iphonesimulator/ios_add2app.app/Frameworks/Flutter.framework: replacing existing signature
/Users/m/Library/Developer/Xcode/DerivedData/ios_add2app-btprswwixqqclofvuogmdxvymovu/Build/Products/Debug-iphonesimulator/ios_add2app.app/Frameworks/Flutter.framework: Permission denied
Command PhaseScriptExecution failed with a nonzero exit code


Test session results, code coverage, and logs:
	/Users/m/Library/Developer/Xcode/DerivedData/ios_add2app-btprswwixqqclofvuogmdxvymovu/Logs/Test/Test-ios_add2appTests-2019.08.29_11-37-54--0700.xcresult

Testing failed:
	Command PhaseScriptExecution failed with a nonzero exit code
	Testing cancelled because the build failed.

** TEST FAILED **


The following build commands failed:
	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/magder/Library/Developer/Xcode/DerivedData/ios_add2app-btprswwixqqclofvuogmdxvymovu/Build/Intermediates.noindex/ios_add2app.build/Debug-iphonesimulator/ios_add2app.build/Script-7FADF19EC61F97E525982780.sh
(1 failure)
```

**Comment by jmagman** [comment]
git bisect says it's caused by https://github.com/flutter/flutter/commit/78cca6250a7104cc1dd89edf1982878530e55ee6.

**Comment by jmagman** [comment]
The Flutter.framework/Flutter binary is made read-only, so can't be signed:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/bin/xcode_backend.sh#L145

But that was added with https://github.com/flutter/flutter/commit/cb2b89c389e06c2cceb1a3361d520eaccb4cec8c (and changed with https://github.com/flutter/flutter/commit/e22d0e603c13b6d54cc3e4e567a434c6471be81a) back in 2017, with the intention of making the headers (not the binary) read-only.  So how did this ever work?  What recently changed with signing?  Why does this only seem to happen in modules and not for other Flutter apps using CocoaPods?

@christopherfujino Do you have any insights?

**Comment by jmagman** [comment]
On a normal Flutter app:

```
$ ls -la DerivedData/Runner-bccqvzuansojwlfqejmweubuujjs/Build/Products/Release-iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter
-rwxr-xr-x   1 m  primarygroup  339098928 Aug 29 17:37 Flutter
```

In the module app:
```
-r-xr-xr-x  1 m  primarygroup  33486788 Aug 29 17:35 Flutter
```
Why is the app version writable (and therefore signable) but the module one isn't?

**Comment by xster** [comment]
ummm this is really curious... I have no idea. Maybe @cbracken knows.

**Comment by cbracken** [comment]
I am equally surprised :(

**Comment by jmagman** [comment]
And now I can't reproduce on my machine even on master.

**Comment by jmagman** [comment]
Reopening, PR was reverted.

**Comment by mleonhard** [comment]
I'm hitting this exact same error:
```
$ flutter build ios -t lib/main_qa_ios.dart --flavor=qa --release
...
/usr/bin/codesign --force --sign ...  --preserve-metadata=identifier,entitlements
'/Users/.../app/build/ios/Release-qa-iphoneos/Runner.app/Frameworks/Flutter.framework'
/Users/.../app/build/ios/Release-qa-iphoneos/Runner.app/Frameworks/Flutter.framework: replacing existing signature
/Users/.../app/build/ios/Release-qa-iphoneos/Runner.app/Frameworks/Flutter.framework: Permission denied
Command PhaseScriptExecution failed with a nonzero exit code
```

A reboot did nothing.

I tried:
- `channel dev` build fails with above error.
- Changed channel to `beta`, `flutter upgrade`, `flutter clean`, build still fails with above error.
- Changed to `Flutter 1.9.1+hotfix.6 • channel stable` and build fails with above error.
- Changed to `Flutter 1.10.7 • channel beta`.  Builds but fails to install because of #42877 whose fix landed in 1.10.15.
- Changed to `Flutter 1.12.4 • channel dev`. Build succeeds.

Something about the process of switching channels master -> dev -> beta -> stable -> beta -> dev solved it on my machine.

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.12.4, on Mac OS X 10.15.1 19B88, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.2.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by endrelovas** [comment]
Checkouts time to time resolves the problem. No matter if it is stable, master or dev. At a certain moment it builds and runs. Than fails again. Incredible annoying.

**Comment by jmagman** [comment]
> Checkouts time to time resolves the problem. No matter if it is stable, master or dev. At a certain moment it builds and runs. Than fails again. Incredible annoying.

I reopened https://github.com/flutter/flutter/issues/40146, I'm going to remove the chmod.

**Comment by endrelovas** [comment]
Bit of update: for some reason Frameworks become read-only in the last build step "[CP] Embed Pods Frameworks". If I delete that step all Frameworks hold write permission correctly. So permissions are fine after Flutter shell scripts.

I edited the file and added chmod -R +w $1 inside "code_sign_if_enabled" method. Now it looks like this:

```
code_sign_if_enabled() {
  if [ -n "${EXPANDED_CODE_SIGN_IDENTITY:-}" -a "${CODE_SIGNING_REQUIRED:-}" != "NO" -a "${CODE_SIGNING_ALLOWED}" != "NO" ]; then
    # Use the current code_sign_identity
    echo "Code Signing $1 with Identity ${EXPANDED_CODE_SIGN_IDENTITY_NAME}"
    chmod -R +w $1
    local code_sign_cmd="/usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} ${OTHER_CODE_SIGN_FLAGS:-} --preserve-metadata=identifier,entitlements '$1'"

    if [ "${COCOAPODS_PARALLEL_CODE_SIGN}" == "true" ]; then
      code_sign_cmd="$code_sign_cmd &"
    fi
    echo "$code_sign_cmd"
    eval "$code_sign_cmd"
  fi
}
```

The app installs and starts at least.

**Comment by TheBestMoshe** [comment]
> code_sign_if_enabled() {
>   if [ -n "${EXPANDED_CODE_SIGN_IDENTITY:-}" -a "${CODE_SIGNING_REQUIRED:-}" != "NO" -a "${CODE_SIGNING_ALLOWED}" != "NO" ]; then
>     # Use the current code_sign_identity
>     echo "Code Signing $1 with Identity ${EXPANDED_CODE_SIGN_IDENTITY_NAME}"
>     chmod -R +w $1
>     local code_sign_cmd="/usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} ${OTHER_CODE_SIGN_FLAGS:-} --preserve-metadata=identifier,entitlements '$1'"
> 
>     if [ "${COCOAPODS_PARALLEL_CODE_SIGN}" == "true" ]; then
>       code_sign_cmd="$code_sign_cmd &"
>     fi
>     echo "$code_sign_cmd"
>     eval "$code_sign_cmd"
>   fi
> }

This gets overwritten every time `flutter clean` is run

**Comment by endrelovas** [comment]
> > code_sign_if_enabled() {
> > if [ -n "${EXPANDED_CODE_SIGN_IDENTITY:-}" -a "${CODE_SIGNING_REQUIRED:-}" != "NO" -a "${CODE_SIGNING_ALLOWED}" != "NO" ]; then
> > # Use the current code_sign_identity
> > echo "Code Signing $1 with Identity ${EXPANDED_CODE_SIGN_IDENTITY_NAME}"
> > chmod -R +w $1
> > local code_sign_cmd="/usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} ${OTHER_CODE_SIGN_FLAGS:-} --preserve-metadata=identifier,entitlements '$1'"
> > ```
> > if [ "${COCOAPODS_PARALLEL_CODE_SIGN}" == "true" ]; then
> >   code_sign_cmd="$code_sign_cmd &"
> > fi
> > echo "$code_sign_cmd"
> > eval "$code_sign_cmd"
> > ```
> > 
> > 
> > fi
> > }
> 
> This gets overwritten every time `flutter clean` is run

Yes it does. What I do I keep open terminal with vim running. Then I save the file again typing ":w"
This is not a solution but we can work at least until Flutter never ending beta test fixes this.

**Comment by Yud4du** [comment]
![Screen Shot 2019-11-29 at 09 55 57](https://user-images.githubusercontent.com/56818149/69840555-999bc500-128e-11ea-8978-707a82784ec3.png)

Open Xcode -> Pods File on the left bar -> build settings -> on Install permissions, set the value to **-R +w $1**

its not going to replace after flutter run..

poke @endrelovas @TheBestMoshe

**Comment by endrelovas** [comment]
> ![Screen Shot 2019-11-29 at 09 55 57](https://user-images.githubusercontent.com/56818149/69840555-999bc500-128e-11ea-8978-707a82784ec3.png)
> 
> Open Xcode -> Pods File on the left bar -> build settings -> on Install permissions, set the value to **-R +w $1**
> 
> its not going to replace after flutter run..
> 
> poke @endrelovas @TheBestMoshe

Nice catch if works. I will revert you back when I am in trouble again with this "feature".

**Comment by endrelovas** [comment]
> ![Screen Shot 2019-11-29 at 09 55 57](https://user-images.githubusercontent.com/56818149/69840555-999bc500-128e-11ea-8978-707a82784ec3.png)
> 
> Open Xcode -> Pods File on the left bar -> build settings -> on Install permissions, set the value to **-R +w $1**
> 
> its not going to replace after flutter clean..
> 
> poke @endrelovas @TheBestMoshe

It does not work for me.

**Comment by garrettlove8** [comment]
Still getting this issue 12/9/19
I am on a Mac using 10.15.1. Something to note which changed in macOS Catalina is that Apple became more strict on what app they allow you open, so now the only options in Security and Privacy settings are "App Store" and "App Store and identified developers". If you follow the steps in this article to allow apps that are downloaded from anywhere this issue seems to go away

https://www.imore.com/how-open-apps-anywhere-macos-catalina-and-mojave

**Comment by endrelovas** [comment]
> Still getting this issue 12/9/19
> I am on a Mac using 10.15.1. Something to note which changed in macOS Catalina is that Apple became more strict on what app they allow you open, so now the only options in Security and Privacy settings are "App Store" and "App Store and identified developers". If you follow the steps in this article to allow apps that are downloaded from anywhere this issue seems to go away
> 
> https://www.imore.com/how-open-apps-anywhere-macos-catalina-and-mojave

I experience issue on both Mojave and High Sierra. IMO it is either flutter or cocoapods related bug.

**Comment by ArtemGr** [comment]
I was hitting this after downgrading from v1.12.13+hotfix.5 to v1.9.1+hotfix.6 and cleaning the Pods resolved the issue. `(cd ios && rm -rf Podfile.lock Podfile Pods)`

**Comment by darren-f5s** [comment]
> I was hitting this after downgrading from v1.12.13+hotfix.5 to v1.9.1+hotfix.6 and cleaning the Pods resolved the issue. `(cd ios && rm -rf Podfile.lock Podfile Pods)`

FINALLY a working solution! Thank you, I also downgraded from 12 to 9

**Comment by ZQ1297089376** [comment]
You can try to change configuration item，Build Phases->Thin Binary
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" thin

**Comment by jmagman** [comment]
@ZQ1297089376 Depending on what version you are on, if you remove the `embed` part Flutter and your compiled dart code will not actually be embedded in your app.  You are likely hitting some different problem than this issue, please file a new GitHub issue and completely fill out the template.

**Comment by mumusa** [comment]
> I was hitting this after downgrading from v1.12.13+hotfix.5 to v1.9.1+hotfix.6 and cleaning the Pods resolved the issue. `(cd ios && rm -rf Podfile.lock Podfile Pods)`

it work

**Comment by TahaAli07** [comment]
> I was hitting this after downgrading from v1.12.13+hotfix.5 to v1.9.1+hotfix.6 and cleaning the Pods resolved the issue. `(cd ios && rm -rf Podfile.lock Podfile Pods)`

I did this , but after that if I run pod install , its says "Podfile not found"

**Comment by TahaAli07** [comment]
Moved from v1.9.1+hotfix.6 to v1.11.0 .

To change flutter version to 1.11.0 just run

`flutter version v1.11.0`

This fixed this issue for me , tried all other other highly voted solutions but none worked.
