### ISSUE TITLE
Video quality between [video_player] vs <video> [webview_flutter]

### ISSUE THREAD

**Issue by marcosgallardo** [flutter/flutter#39506]
There is an important quality difference between a video rendered with the `video_player` plugin vs the same video rendered in a `<video></video>` using the `webview_flutter` plugin.

Here is a screenshot using the `video_player` plugin.

![Screenshot_1567104553](https://user-images.githubusercontent.com/4549886/63969019-535c7d00-ca77-11e9-8aee-823daf38fbec.png)

And here is a screenshot using a `<video></video>` and  `webview_flutter` plugin.

![Screenshot_1567104386](https://user-images.githubusercontent.com/4549886/63968899-08db0080-ca77-11e9-9882-5747bfdf39ba.png)

The exactly same video is used and, as you can see, **the video played with the `video_player` plugin looks like pixeled.**

Is there something I am doing wrong?

## Steps to Reproduce

1. Go to this repo https://github.com/marcosgallardo/flutter_video_player_vs_webview
2. Switch to `video_player` branch and run the app
3. Switch to `webview` branch and run the app.

## Logs

The output of running `flutter doctor -v` here.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.678], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.37.1)
[√] Connected device (1 available)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @marcosgallardo 
Are you still experiencing this issue with latest stable?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`?
 Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by marcosgallardo** [comment]
Hi @TahaTesser I just did a quick test and seems to be fixed.

Regarding the code sample, you can [find it here](https://github.com/marcosgallardo/flutter_video_player_vs_webview) (_see "Steps to reproduce" section on this issue_).

Cheers!

**Comment by TahaTesser** [comment]
Hi @marcosgallardo 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it.
 Thank you
