### ISSUE TITLE
[webview_flutter] Catch and handle all HTTP errors codes (eg 404) to redirect to a custom error page

### ISSUE THREAD

**Issue by majicomajico** [flutter/flutter#39502]
## Use case

it is currently impossible to capture and manage HTTP status codes and avoid displaying the default page of the missing internet connection.

## Proposal

I suggest to create a new property such as "onPageError" to allow an easy iterception of these status codes

**Comment by paulobreim** [comment]
it is very important

**Comment by sbd2015** [comment]
Do we have any updates on this?

**Comment by pushparajbhatta** [comment]
Is there any update on this ?

**Comment by Stitch-Taotao** [comment]
This is very very important feauture!

**Comment by dinbtechit** [comment]
This is a much need feature!!!!!

**Comment by ClubAce** [comment]
The onWebResourceError property in the webview_flutter plugin does not catch 404 errors. Thus it seems that the need for an onPageError property is very relevant. Please consider implement the suggested feature in the near future, to the benefit of all that have chosen to utilize this otherwise fine plugin.

**Comment by katsuyuki-ouchi** [comment]
I have one solution to this problem.
We could use just `http.get` and the response like this:
```dart
onWebResourceError: (WebResourceError error) async {
  final response = await http.get(Uri.parse('https://something.com'));
  print(response.statusCode);
}
```

Of course, I want to use a new property like `onPageError`, but currently, we could solve it with this solution.

**Comment by bakatsuyuki** [comment]
I have one solution to this problem.
We could use just `http.get` and the response like this:
```dart
import 'package:http/http.dart' as http;
// ...
onWebResourceError: (WebResourceError error) async {
  final response = await http.get(Uri.parse('https://something.com'));
  print(response.statusCode);
}
```

Of course, I want to use a new property like `onPageError`, but currently, we could solve it with this solution.
