### ISSUE TITLE
Review and complete all relevant Java/ObjC docs for add-to-app

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#39516]

**Comment by xster** [comment]
@RedBrogdon would you like to help us perform a pre-launch check to make sure that all relevant classes have reasonable API docs on them?

**Comment by jmagman** [comment]
Was this done, @xster?

**Comment by jmagman** [comment]
There's also https://github.com/flutter/flutter/issues/32377 and https://github.com/flutter/flutter/issues/21781 and https://github.com/flutter/flutter/issues/21779

**Comment by xster** [comment]
It was not. All the docs still need a review. https://github.com/flutter/flutter/issues/32377 is for supporting docset readers like Dash.

**Comment by RedBrogdon** [comment]
CC: @sfshaza2.
