### ISSUE TITLE
Engine needs to expose VM causal_async_stacks as a configuration option

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#39511]
See: b/140166286

Large clients have observed performance problems due to causal_async_stacks. They are willing to live with nonsensical stack traces to get better performance. In order for us to support this, engine needs to allow configuring [this option](https://github.com/flutter/engine/blob/37c5510c075b1d8b6ee224ed181d2fdd3d7d38f1/runtime/dart_vm.cc#L64) in [switches](https://github.com/flutter/engine/blob/master/shell/common/switches.h) as opposed to hardcoding it.

**Comment by mehmetf** [comment]
@cbracken FYI

**Comment by Hixie** [comment]
Have we filed a bug on Dart regarding this performance bottleneck? I'd rather fix the performance problem than have multiple codepaths.

**Comment by mehmetf** [comment]
Yes: https://github.com/dart-lang/sdk/issues/37668

**Comment by Hixie** [comment]
@kf6gpe is going to see if he can encourage the Dart folks to increase the priority of the performance issue on the Dart side, so we can avoid having a flag whose modes are "Slow" vs "Inconvenient".

**Comment by liyuqian** [comment]
Any update? Shall we mark this as a duplicate of dart-lang/sdk#37668 if our solution is improve the performance without exposing a new option?

**Comment by a-siva** [comment]
Our first step would be to expose causal_async_stacks as a configuration option so that folks not needing it will turn it off

**Comment by mkustermann** [comment]
@a-siva Did you have any time looking at this? Maybe someone from the engine team could also take a look?

**Comment by a-siva** [comment]
The engine currently supports a mechanism to pass dart flags through (--dart-flags).
I believe the gallium folks should be able to set this on the command line of their invocation.
Something like --dart-flags=no-causal-async-stacks should turn this off.

**Comment by mehmetf** [comment]
Customer: Dream cannot currently configure this because it is hardcoded in the engine: https://github.com/flutter/engine/blob/master/runtime/dart_vm.cc#L60-L66

**Comment by jason-simmons** [comment]
The engine adds user-supplied Dart flags after the default Dart flags:
    https://github.com/flutter/engine/blob/master/runtime/dart_vm.cc#L379

Fuchsia is apparently using this to disable causal async stacks:
    https://github.com/flutter/engine/blob/master/shell/platform/fuchsia/dart_runner/dart_runner.cc#L40

Does Dart guarantee that a `--no-feature` flag will override an earlier `--feature` flag?  If not, then the engine will need to resolve the conflicting flags itself.

**Comment by a-siva** [comment]
Yes it does, see the example

```
sivalinuxmach[sdk]>out/ReleaseX64/dart --causal-async-stacks /tmp/junk.dart
Unhandled exception:
Not Supported
#0      bar1 (file:///tmp/junk.dart:2:3)
<asynchronous suspension>
#1      foo (file:///tmp/junk.dart:6:3)
<asynchronous suspension>
#2      main (file:///tmp/junk.dart:10:9)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```

```
sivalinuxmach[sdk]>out/ReleaseX64/dart --causal-async-stacks --no-causal-async-stacks /tmp/junk.dart
Unhandled exception:
Not Supported
#0      bar1 (file:///tmp/junk.dart:2:3)
#1      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#2      bar1 (file:///tmp/junk.dart:1:5)
#3      foo (file:///tmp/junk.dart:6:3)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#5      foo (file:///tmp/junk.dart:5:4)
#6      main (file:///tmp/junk.dart:10:9)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#8      main (file:///tmp/junk.dart:9:5)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by mehmetf** [comment]
Thanks @jason-simmons . It does not seem that dart-flags switch is being used in all embedders though. Android embedder is missing the option so we still have some piping to do. 

https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/engine/FlutterShellArgs.java#L26-L47

**Comment by jason-simmons** [comment]
The `ARG_` constants in `FlutterShellArgs` are used for shell flags that are extracted from the activity launch intent (using `FlutterShellArgs.fromIntent`)

Application code on Android can set other shell flags using the `FlutterShellArgs` constructors or calling `FlutterShellArgs.add`

**Comment by mehmetf** [comment]
OK. It seems like we will need to bypass the args and call `ensureInitializationComplete()` with that flag. I think this issue can be closed then.

**Comment by mehmetf** [comment]
This still seems problematic. The dart_flags setting is controlled by switches.cc.

Need to pass --dart-flags=... flag whose values are passed through to Dart VM. But only whitelisted flags are allowed to pass (https://github.com/flutter/engine/blob/6f5eb1332f9d22342fc60e9fd0108720c179e55d/shell/common/switches.cc#L342) and not in release mode (https://github.com/flutter/engine/blob/6f5eb1332f9d22342fc60e9fd0108720c179e55d/shell/common/switches.cc#L332).

**Comment by liyuqian** [comment]
Now it seems that we'll need someone to work on `switches.cc` to enable the flag. Shall we have a super-whitelist that can be turned on even in release? @jason-simmons @chinmaygarde

**Comment by jason-simmons** [comment]
Tried adding `--no-causal_async_stacks` to the Dart flags whitelist in `switches.cc`.  It turns out that this is insufficient - the snapshot will also need to be built with `--no-causal_async_stacks` in order to run in that configuration.

**Comment by mehmetf** [comment]
`The snapshot` refers to core snapshot?

**Comment by jason-simmons** [comment]
It's the AOT snapshot compiled from the app's Dart code.  flutter_tools will need to pass `--no-causal_async_stacks` when invoking `gen_snapshot`.

**Comment by mehmetf** [comment]
Good. That was my original understand; I wanted to make sure. That's not a problem internally.
