### ISSUE TITLE
iOS crashes on device in File::isClosed

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3952]
Flutter`dart::bin::File::IsClosed:
    0x1010dc7fc <+0>:  ldr    x8, [x0, #8]
->  0x1010dc800 <+4>:  ldr    w8, [x8]
    0x1010dc804 <+8>:  cmn    w8, #1                    ; =1
    0x1010dc808 <+12>: cset   w0, eq
    0x1010dc80c <+16>: ret

Presumably this line:
https://github.com/dart-lang/sdk/blob/f262fad6396d7525b931010f0fd12487f19477d5/runtime/bin/file_macos.cc#L77

```
  Future loadCachedSettings() async {
    var dir = (await PathProvider.getTemporaryDirectory()).path;
    _file = new File(dir + "/settings");
    setState(() async {
      try {
        if ( await _file.exists()) {
          settings = new pb.Settings.fromBuffer(await _file.readAsBytes());
        }
      } catch (e) {
        print("Error loading settings: $e. Using defaults.");
      } finally {
        _isLoaded = true;
      }
    });
  }
```
I believe the above is this code in question.  I can get you access to the full app if necessary.  @chinmaygarde 

This may be related to https://github.com/flutter/flutter/issues/3951, but I doubt it.  I suspect this is just that the File code has some bug on iOS devices?

**Comment by chinmaygarde** [comment]
Doesn't seem to be an issue when using DBC. Investigating.

**Comment by chinmaygarde** [comment]
Cant reproduce in any variant. Though I did have to prepare a reduced test case. So I may have missed something. Please reopen with a reduced test case if you run into this again.
