### ISSUE TITLE
Creating widget test for pie-chart

### ISSUE THREAD

**Issue by kausha9** [flutter/flutter#39527]
While creating the widget test for pie-chart , i cannot see the pie-chart in either the widget test or the golden image.

**Comment by BondarenkoStas** [comment]
Please provide ```flutter doctor -v``` output as well as the steps to reproduce the issue.

**Comment by kausha9** [comment]
I have created the widget test and golden image for the whole page and it is able to capture everything but not the pie-chart.

Code for pie-chart :

return Container(
  height: 175.0,
  child: Stack(
    children: <Widget>[
      // container for the pie chart
      Container(
        key: const Key('graphFigure'),
        child: charts.PieChart<String>(
          pieChartData,
          animate: true,
          // arcWidth variable decides with size of the pie pieces in the chart
          defaultRenderer:
              charts.ArcRendererConfig(arcWidth: AppDimen.graphArcWidth),
        ),
      ),
code for widget test :

final Finder graphFigure = find.byKey(Key('graphFigure'));
  final Finder irpercentageValueInGraph = find.byKey(Key('percentageValueInGraph'));
  final Finder pcSignInGraph = find.byKey(Key('percentageSignInGraph'));

expect(getGraphFigure(), findsOneWidget, reason: 'The Pie Chart is not visible');
expect(getIRPercentageValueInGraph(), findsOneWidget, reason: 'The In Range percentage value inside the graph not visible');
expect(getPcSignInGraph(), findsOneWidget, reason: 'Percentage sign inside the graph not visible');

**Comment by BondarenkoStas** [comment]
@kausha9 Please provide your ```flutter doctor -v``` output as well, as it's essential to know the versions where it occurs.

**Comment by kausha9** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/xyz/flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/xyz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6262.13

**Comment by darshankawar** [comment]
Hi @kausha9,
Can you confirm if you still experience this issue on latest Flutter version (eg: dev, master, stable) ?
Thanks.

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
