### ISSUE TITLE
Add a flutter run/drive option that deletes old persistent shader cache

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#39526]
This will help debugging issues related with shader compilations (https://github.com/flutter/flutter/issues/32170).

For more information, please reference the internal design doc by "go flutter-compile-janks".

**Comment by zanderso** [comment]
@liyuqian Could you provide a little more detail here? Is this as simple as passing a flag to the engine, or is this more involved?

**Comment by liyuqian** [comment]
Yes, the framework or Flutter tools side of work should be as simple as sending a flag to the engine. I'll create an engine PR to use that flag to clear the cache.

**Comment by zanderso** [comment]
Thanks to the 'customer critical' and 'tool' labels, this is showing up in my triage list =) It looks like @liyuqian is driving this. @liyuqian If you need help with this please update this issue with any pertinent information and set a milestone. Thanks!
