### ISSUE TITLE
NotificationListener on Overscrollnotification do not work on ios but works on Android

### ISSUE THREAD

**Issue by mlg-hub** [flutter/flutter#39522]
## This is snippets of my code

```
Scaffold(
body: NotificationListener<ScrollNotification>(
        onNotification: (notification) => onNotification(notification, bloc),
        child: StreamBuilder<List<Photo>>(
          stream: bloc.stream,
          builder: (context, AsyncSnapshot<List<Photo>> snapshot) {
            return buildListView(context, snapshot);
          },
        ),
)
```

<b> once notified this function is called</b>
```
bool onNotification(ScrollNotification scrollInfo, PhotoBloc bloc) {
    // print(scrollInfo is ScrollEndNotification);
 if (scrollInfo is OverscrollNotification) { // this verification always returns false on iphone hence new data can not be fetched.
      print("fetch new data");
      bloc.sink.add(scrollInfo);
    }
    return false;
  }
```

**Comment by BondarenkoStas** [comment]
@mlg-hub Please attach your ```flutter doctor -v``` output, and please format your code properly to be sure the issue can be reproduced.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by MawiraIke** [comment]
Could this be related to this issue? https://stackoverflow.com/q/58962396/10081740
