### ISSUE TITLE
Improvements and fixes for "flutter build aar"

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#39520]
I attempted to use `flutter build aar` for a presentation and ran into a few issues that we should address.

- [ ] Document all possible configurations of `flutter build aar` in the wiki guide, explain the implications of each, and even point out that we don't support certain configurations, e.g., building an AAR for release as x86

- [ ] Document the distinction and independence between `debugImplementation`/`releaseImplementation` in `build.gradle` vs the AAR path string, e.g., `flutter_debug` and `flutter_release`.

- [ ] Catch bad `flutter build aar` requests in the tool and output error messages that tells the user that the given configuration is invalid.

**Comment by matthew-carroll** [comment]
CC @xster @blasten

**Comment by xster** [comment]
Anything left here @blasten?

**Comment by xster** [comment]
Same here. Should we close this?

**Comment by blasten** [comment]
This is done
