### ISSUE TITLE
ListTile.divideTiles now requires context: The method 'inheritFromWidgetOfExactType' was called on null.

### ISSUE THREAD

**Issue by indiestream** [flutter/flutter#39533]
Upgraded to the latest Flutter and it looks like there is an error with ListTiles and/or ListView

I/flutter ( 8416): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 8416): The following NoSuchMethodError was thrown building FormTileGroup(dirty):
I/flutter ( 8416): The method 'inheritFromWidgetOfExactType' was called on null.
I/flutter ( 8416): Receiver: null
I/flutter ( 8416): Tried calling: inheritFromWidgetOfExactType(DividerTheme)
I/flutter ( 8416): 
I/flutter ( 8416): User-created ancestor of the error-causing widget was:
I/flutter ( 8416):   ListView
I/flutter ( 8416):   file:///Users/user/AndroidStudioProjects/conquered_time/lib/src/drawers/profile_drawer.dart:279:20
I/flutter ( 8416): 
I/flutter ( 8416): When the exception was thrown, this was the stack:
I/flutter ( 8416): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter ( 8416): #1      DividerTheme.of (package:flutter/src/material/divider_theme.dart:162:47)
I/flutter ( 8416): #2      Divider.createBorderSide (package:flutter/src/material/divider.dart:122:36)
I/flutter ( 8416): #3      ListTile.divideTiles (package:flutter/src/material/list_tile.dart:740:25)
I/flutter ( 8416): #4      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:144:12)
I/flutter ( 8416): #5      new List.from (dart:core-patch/array_patch.dart:45:19)
I/flutter ( 8416): #6      Iterable.toList (dart:core/iterable.dart:398:5)
I/flutter ( 8416): #7      FormTileGroup.build (package:conquered_time/src/ui/controls/form_controls.dart:31:38)

**Comment by indiestream** [comment]
I've resolved this by passing the context in. Looks like a breaking change to ListTile.divideTiles method.

**Comment by jonahwilliams** [comment]
Added an explanation at https://github.com/flutter/flutter/pull/38621#issuecomment-526414591, seems like this should be fixable

**Comment by jonahwilliams** [comment]
Updated the name to reflect the error
