### ISSUE TITLE
Use feature flag, rather than hiding, to control desktop 'build' options

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#39548]
I noticed today that `flutter build` help still doesn't list desktop, which I believe is just a legacy of when we were using obscurity rather than explicit controls to gate desktop exposure. If someone has enabled the flag for a given desktop platform, we should show it in the help list.

/cc @jonahwilliams

**Comment by jld3103** [comment]
Also doesn't show web

**Comment by stuartmorgan** [comment]
The PR addresses that.
