### ISSUE TITLE
Is there a RenderTexture-like widget in flutter?

### ISSUE THREAD

**Issue by Zhang-Yi** [flutter/flutter#39544]
I want use flutter implement a function like as PowerPoint, which thumbnail is syhc all change with stage area.But i did not find appropriate widget，finally i used RepaintBoundary to pick the image from stage area at the every frame.
Do you have any better suggestions?

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
