### ISSUE TITLE
flutter doctor with java 12

### ISSUE THREAD

**Issue by lookfirst** [flutter/flutter#39549]
There is an issue with Android sdkmanager where it does not work with Java > 8.

You can google it and find tons of issues around this with various fixes. The simplest fix is just to revert your JVM install to java 8. If you want to use Java < 11, you can apply this fix:

`export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'`

But then that does not work with Java 11 and Java 12, with a new unhelpful error.

Let's just assume I only want to have Java 12 on my machine since I like latest and greatest...

The thing that overlaps with flutter is that this breaks flutter doctor which attempts to use the sdkmanager to check the license status.

This is causes flutter doctor to error out with a totally unhelpful message:

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.8.3, on Mac OS X 10.14.6 18G95, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.4)
```

So, one solution to this problem is to rely on the JDK installed with Android Studio:

```
JAVA_OPTS="" JAVA_HOME="/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home" flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.8.3, on Mac OS X 10.14.6 18G95, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.1)
[!] Connected device
    ! No devices available
```

Given that flutter doctor already has the dependency, on Android studio, the path could be used to set JAVA_HOME before calling sdkmanager. This would hide the problem from flutter doctor.

**Comment by FlashJonas** [comment]
Thanks, 
`JAVA_OPTS="" JAVA_HOME="/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home" flutter doctor`
worked for me!

**Comment by blacroix** [comment]
If you are using a Mac it works with JDK 8:
`JAVA_OPTS="" JAVA_HOME="/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home" flutter doctor`

**Comment by lookfirst** [comment]
> If you are using a Mac it works with JDK 8:
> `JAVA_OPTS="" JAVA_HOME="/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home" flutter doctor`

Yea... no thanks. I want >8, which is the point of this issue.

**Comment by blacroix** [comment]
> > If you are using a Mac it works with JDK 8:
> > `JAVA_OPTS="" JAVA_HOME="/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home" flutter doctor`
> 
> Yea... no thanks. I want >8, which is the point of this issue.

Yes, me too as I am using JDK12 elsewhere but to validate licences for example it works this way for now. I would be happy to have a fix too!

**Comment by iMAHMOD** [comment]
i have same problem with java 14

**Comment by benjaminhorner** [comment]
@iMAHMOD the solution given by @blacroix **solves the issue of signing the Android licenses**. Once you have done that, you can use JAVA 14 no problem.

Do remember to install JAVA 8 though. 
**NOTE**: the given solution assumes you installed `adoptopenjdk-8` using home brew (`brew cask install adoptopenjdk-8`).

**Comment by lookfirst** [comment]
@benjaminhorner The solution provided at the very top solves this issue without having to install JDK8. 🤦‍♂

**Comment by lookfirst** [comment]
This seems fixed.

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en-US) 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
[✓] VS Code (version 1.38.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

$ java -version
openjdk version "14" 2020-03-17
OpenJDK Runtime Environment AdoptOpenJDK (build 14+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14+36, mixed mode, sharing)
```
