### ISSUE TITLE
Alignment of the documentation

### ISSUE THREAD

**Issue by pranishres** [flutter/flutter#39565]
Please center align the content its little aligned to the right.

**Comment by BondarenkoStas** [comment]
@pranishres Please specify, what the documentation exactly? Can you post a link here?

**Comment by janmoppel** [comment]
Hello @pranishres !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
