### ISSUE TITLE
List Class getRange (and sublist) don't return single item

### ISSUE THREAD

**Issue by craigsailor** [flutter/flutter#39564]
Not sure if it's intended behaviour, but when start and end index value is the same getRange returns and empty list. Even a list with one item is still a list and should be returned as such.

To be more specific, in my case I was using myList.getRange(0,0) and getting an empty list.

If the index is a valid index, say 0, and you call List.getRange(0,0), a List containing the single item at index 0 should be returned.

**Comment by aneeshjose** [comment]
@craigsailor 
 Could you please update the question with your intended output?

**Comment by aneeshjose** [comment]
Try using `myList.elementAt(0)` . If you want to check that index is a valid one ,try the code inside a try-catch block

**Comment by BondarenkoStas** [comment]
@craigsailor documentation https://api.flutter.dev/flutter/dart-core/List/getRange.html says that the range is valid if 0 <= start <= end <= len, where len is this list's length. The range starts at start and has length end - start.
An empty range (with end == start) is valid. 
I believe that it was intended to have the length of returned Iterable as end - start, and the end points on the element which will not be included.
I believe myList.getRange(0,1) solves the problem. Can you try?

**Comment by aneeshjose** [comment]
`myList.getRange(0,1)` also solved the problem like `myList.elementAt(0)`.

**Comment by craigsailor** [comment]
Using getRange(0,1) fails if there is only a single element in the list as 1 is an invalid index.
The same problem would happen any time you are trying to get a range that is at the end of your list.

**Comment by aneeshjose** [comment]
Please provide the error log while using `myList.getRange(0,1)` along with your list. I am not getting an error with it.
My code:
`
var x=['hai'];
 print(x.getRange(0,1));
`
this will print `(hai)'

**Comment by craigsailor** [comment]
Apologies. That does work.
I would recommend that the documentation be improved slightly to make it more clear that the end index must be one more than the index of the last time you'd like to retrieve.

Many Thanks.
