### ISSUE TITLE
Flutter build or run ios --release hangs

### ISSUE THREAD

**Issue by hazelf42** [flutter/flutter#39576]
First off, first time opening an issue, hope I don't screw it up.
**Issue**
Unable to run ```flutter build ios --release```, stuck on building for Xcode, have tried piping to build.log as suggested in other threads, does not work either. flutter run --release to my iphone has the same issue. Without building for ios --release I'm getting a blank white screen upon upload to Testflight.

**Logs**
Result of ```flutter build ios --release -v```
Deleted output before Xcode build, no errors, for readability, let me know if I should post the whole thing.
```
[   +4 ms] Running Xcode build...
[        ] executing: [/Users/hazelf/Desktop/cool_date_night-1/ios/]
/usr/bin/env xcrun xcodebuild -configuration Release VERBOSE_SCRIPT_LOGGING=YES
-workspace Runner.xcworkspace -scheme Runner
BUILD_DIR=/Users/hazelf/Desktop/cool_date_night-1/build/ios -sdk
iphoneos
SCRIPT_OUTPUT_STREAM_FILE=/var/folders/m5/15hrwg5j3y503fclv9dgnyv80000gn/T/flutt
er_build_log_pipe.uGvRLJ/pipe_to_stdout
```

**Output of flutter doctor -v**
```
[✓] Flutter (Channel unknown, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132,
    locale en-US)
    • Flutter version 1.5.4-hotfix.2 at
      /Users/hazelf/Desktop/Edibly/Flutter/flutter
    • Framework revision 7a4c33425d (4 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/hazelf/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • Sparky • 28233f5925128c33e62875285b2df48911cfd400 • ios • iOS 12.4

• No issues found!
```

**Comment by BondarenkoStas** [comment]
@hazelf42 Did you try to upgrade your flutter version?

**Comment by janmoppel** [comment]
Hello @hazelf42 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
