### ISSUE TITLE
"Open Widget Sample" in IntelliJ creates the Counter sample

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#39571]
On the master channel, the "Open Widget Sample" feature creates the Counter sample, not the sample that was selected.

## Steps to Reproduce
1. open the Flutter framework package in IntelliJ
2. Navigate to src/material/chips.dart
3. select the onDeleted widget sample and hit "Go..."

![Screen Shot 2019-08-30 at 7 49 09 AM](https://user-images.githubusercontent.com/1145719/64030591-bf80c480-cafb-11e9-81c7-32af1f920fc3.png)

4. Observe that the sample is the counter sample, not the sample in the docs.

## Flutter doctor output

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.9.6-pre.57, on Mac OS X 10.14.6 18G84, locale
    en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
[✓] VS Code (version 1.37.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by RedBrogdon** [comment]
CC: @gspencergoog

**Comment by gspencergoog** [comment]
CC @devoncarew
