### ISSUE TITLE
Clicking on a button on top of Google Maps plugin can trigger onTap event for the south-most marker

### ISSUE THREAD

**Issue by babaosoftware** [flutter/flutter#39582]
Simple app - google map on main screen, and a button on top to navigate to a second screen. 
Added a single marker on map. When clicking on the button to navigate, the onTap handler for the marker is called. The marker doesn't have to be visible, or anywhere near the button.
Here is the sample app:

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'GoogleMaps onTap Bug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  Map<String, Marker> _markers = <String, Marker>{};

  void _showSecondScreen() {
    Navigator.push(
        context,
        MaterialPageRoute(
            builder: (context) => SecondScreen()));
  }

  @override
  initState() {
    _markers["aaa"] = Marker(markerId: MarkerId("aaa"), onTap: _onTap);
    super.initState();
  }

  void _onTap(){
    debugPrint("onTap called without the user tapping on the marker!");
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Stack(
        children: [
          GoogleMap(
            initialCameraPosition: CameraPosition(
              target: LatLng(40.731753, -73.986115),
              zoom: 12.0,
            ),
            markers: Set<Marker>.of(_markers.values),
          ) ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _showSecondScreen,
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class SecondScreen extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    return SafeArea(
        top: false,
        bottom: true,
        left: true,
        right: true,
        child: Scaffold(
            appBar: AppBar(
              title: Text("Second Screen"),
            ),
            body: Center(child: Text("Check debub output - onTap was called for the marker!"))));
  }

}
```

**Comment by KlausJokinen** [comment]
I'm unable to re-produce this issue.
Steps taken:
- Start the app.
- Tap FAB on the right.
- Navigate back to start screen (Map screen).

**Comment by babaosoftware** [comment]
It happens to me all the time. I've seen the problem first in a real app I am writing. The repro above is a stripped down version. You don't need to go back to the map screen. The onTap is called immediately after navigating. Here is my console output when running in simulator (it happens on real iPhone too). See the last line of output:
Launching lib/mainmap.dart on iPhone X in debug mode...
Running Xcode build...
Xcode build done.                                           14.3s
Syncing files to device iPhone X...
Google Maps SDK for iOS version: 3.3.0.0
	[C1.1 C5FB55AA-8389-48AC-A582-2F4046E49D92 192.168.86.234:49478<->172.217.10.238:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.418s, DNS @0.007s took 0.036s, TCP @0.046s took 0.011s, TLS took 0.259s
	bytes in/out: 4227/676, packets in/out: 9/8, rtt: 0.010s, retransmitted packets: 0, out-of-order packets: 0
**flutter: onTap called without the user tapping on the marker!**

The only dependency added to pubsec.yaml is 
  google_maps_flutter: ^0.5.20+1

My best guess is that when you have a widget on top of the map, a click on that widget will incorrectly bubble to the map, and it's being interpreted as a click on a marker.
Not a show stopper for me, just annoying. I'm still looking for a workaround, but the call to onTap is async, and have no way to tell if it's a real one or not.

**Comment by BondarenkoStas** [comment]
@babaosoftware does it occur only on 0.5.20? Did you try to upgrade google_maps_flutter to the current 0.5.21 version?
Also, can you please provide ```flutter doctor -v output```?

**Comment by babaosoftware** [comment]
It happens with both 0.5.20 and 0.5.21. Here is the doctor output:
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/babao/development/flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/babao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.0

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2018.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • iPhone X • C917E604-207E-4A63-A523-EF8438E804D2 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

! Doctor found issues in 1 category.

**Comment by pamir72** [comment]
I have the same issue. But instead floatingActionButton I press button on PersistentBottomSheet to navigate to a second screen and get unexpected onTap event for the unexpected marker.  It happens when I select marker (**issue happens not for all markers !**) before press button. And after unexpected onTap another unexpected marker is selected.
google_maps_flutter: ^0.5.20+1

**Comment by duarte-diegodr** [comment]
> I have the same issue on iOS only. But instead floatingActionButton I press button on PersistentBottomSheet to navigate to a second screen and get unexpected onTap event for the unexpected marker. It happens when I select marker (**issue happens not for all markers !**) before press button. And after unexpected onTap another unexpected marker is selected.
> google_maps_flutter: ^0.5.21

I have the exactly same issue on IOS. 
google_maps_flutter: ^0.5.21+3

**Comment by duarte-diegodr** [comment]
> I have the exactly same issue on IOS.
> google_maps_flutter: ^0.5.21+3

Checking a way to restrict the root cause of the bug, I could identify that the Bug only occurs if you click a widget over the bottom of the map, if you place the float Action Button on the topCenter, topLeft or topRight, the bug does not occur. 
But anywhere below 1/3 of the map, the onTap handler for the marker is called.

I don't know why just at the bottom of the map this bug occurs

**Comment by JorgeDeAG** [comment]
Still happening in google_maps_flutter: ^0.5.21+7

It is not the las added marker. It is the marker out of the visible area with the lowest latitude (the southest one). This can be easily tested by dragging markers around.
(The visible area canvas, actually goes further than the screen borders)

As babaosoftware said, there must be a marker outside the visible area to reproduce it And occurs when calling Navigator.push from the onTap of the FAB.
The tap event is not being blocked at the FAB and is propagated to the map layer.

If all the markers are inside the visible area, the marker tap event will be fired instead at the top left corner of the map. (Probably coordinates 0, 0 what could indicate an unitialized tap event).
When this happens, you can move any (or all) the markers outside the view without getting again the marker tap event fired. As soon as you move the map enough to force a new group of tiles to be loaded, the marker tap event starts firing again. Also, if you change the zoom level enough, at some point (probably when loading tiles), the marker tap starts firing again.

**Comment by duarte-diegodr** [comment]
It's not just with the FAB, if you put a widget at the bottom of the map and tap it, then clicking another button off the map calling Navigator.push will trigger the tap on the marker.

**Comment by JorgeDeAG** [comment]
Yes, you are right @duarte-diegodr. I made independent the tap on the widget and the Navigator.push and I found the following situations:

a) Anytime you tap(1) on the widget (over the map) an uncompleted tap(-) event is generated on the map. Then, if you tap(2) anywhere on the map, the latitude and longitude of the new tap(2) event is replaced by the previous tap(1) latitude and longitude under the widget at the exact point of your tap(1) on the widget. This tap(2) event will "complete" the uncompleted/pending tap(-) and the Navigator.push now **will Not fire** the marker tap event.

b) If you tap(1) the widget at any point that is Not hoovering over the map (centerDocked), the tap(-) is not generated, and the Navigator.push **will Not fire** the marker tap event.

c) If you tap(1) on a point hoovering over the map, but you launch the Navigator.push from the AppBar, **will Not fire** the marker tap event

**Comment by babaosoftware** [comment]
Since this issue is not getting any attention, I had to deal with it myself, and find a workaround.
First of all, this seems to be a problem only in iOS.
The idea I used was to intercept the marker tap events myself. You do this by setting consumeTapEvents to true for your marker and override onTap getter to call your function. In that function you would just move the map camera to the coordinates of the tapped marker which is the default behavior.
So far so good, the problem is still there, but now you control the callback.
Next thing I did was to add a fake marker with coordinates as south as possible, so it will be guaranteed to have the most southern longitude, and also make its alpha to 0, so it is not visible even if the user zooms the map. I only add this fake marker where the map widget is built, so it won't affect other parts of the app. I also gave it a recognizable marker id.
Now in the callback for the marker tap, if it's the fake marker that's clicked, I do nothing, just return.
This will also work if in the future the bug is fixed, as the fake marker cannot be explicitly clicked.
It's ugly but it works.

**Comment by ozz-rjq** [comment]
Any progress? Same problem with 0.5.24+1

**Comment by woutergoossens** [comment]
Same issue here. Any fix?

**Comment by babaosoftware** [comment]
Seems that, as of today, 4/4/2020, the problem has been solved in the beta channel. Cannot test the stable channel though, as there were other Xcode related problems that forced me to switch to the beta channel.

**Comment by kinex** [comment]
Maybe a related issue: I have an `IconButton` aligned to the top/right edge of the map. When I manipulate the map (far from the `IconButton`) , sometimes an `onPressed` event is generated for the `IconButton`. I can reproduce this easily in Android with these steps:
1. First tap the `IconButton` once (not sure if required)
2. Pan and zoom the map 10-20 seconds
3. Suddenly `IconButton.onPressed` event is generated (if not, try again these steps few times and it will happen)

**Comment by TahaTesser** [comment]
Hi @woutergoossens 
I can't reproduce the issue when tapping on the marker area from the next screen, marker onTap is not called





<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'GoogleMaps onTap Bug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Map<String, Marker> _markers = <String, Marker>{};

  void _showSecondScreen() {
    Navigator.push(
        context, MaterialPageRoute(builder: (context) => SecondScreen()));
  }

  @override
  initState() {
    _markers["aaa"] = Marker(markerId: MarkerId("aaa"), onTap: _onTap);
    super.initState();
  }

  void _onTap() {
    debugPrint("onTap called without the user tapping on the marker!");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Stack(
        children: [
          GoogleMap(
            initialCameraPosition: CameraPosition(
              target: LatLng(40.731753, -73.986115),
              zoom: 12.0,
            ),
            markers: Set<Marker>.of(_markers.values),
          )
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _showSecondScreen,
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
        top: false,
        bottom: true,
        left: true,
        right: true,
        child: Scaffold(
            appBar: AppBar(
              title: Text("Second Screen"),
            ),
            body: Center(
                child: Text(
                    "Check debub output - onTap was called for the marker!"))));
  }
}

``` 

</details>


```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_maps_flutter: ^2.0.3
  google_maps_flutter_web: ^0.3.0
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (6 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.2
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.85

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.2.0-11.0.pre.215, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.2.0-11.0.pre.215 at
      /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5865c14d67 (7 hours ago), 2021-04-22 06:44:03 +0200
    • Engine revision 7e69744ede
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Community Edition (version unknown)
    ✗ Invalid IntelliJ version number.

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.2
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.85

! Doctor found issues in 1 category.
```
	
</details>


If the problem persists, Can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you
