### ISSUE TITLE
Toggle buttons for material widgets

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3959]
As spec'ed: https://www.google.com/design/spec/components/buttons.html#buttons-toggle-buttons

(For the other buttons: https://github.com/flutter/flutter/issues/1535)

**Comment by gspencergoog** [comment]
I was taking a look at this, and (to my Flutter-newbie eye), it seems that this would be implemented by:

- Adding a new ButtonGroupController class that manages the state of any RenderToggleable subclasses that register with it.
  - It has parameters about the type of control needed (radio button, multi-select, etc.).
- Then, a constructor argument is added to RenderToggleable and any subclasses to pass in a controller if desired (and they act as they do now if it's null).
- Add a DefaultButtonGroupController Widget (like the TabController/DefaultTabController model) to handle cases where it wants to be in a tree of stateless widgets, or passing a controller directly is inconvenient.
- There are also probably accessibility aspects that need addressing with some kind of Semantics node?

Does that sound about right?  Would it also need to handle non-toggleable buttons (e.g. a group that has a "reset" button in it that isn't a toggle, but resets the other toggle buttons)?

**Comment by Hixie** [comment]
If we're just talking about these:
![](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3V2JKWk9EbzFaMjg/components_buttons_togglebuttons1.png)

...then a simpler solution might just be to make a new widget that takes a list of widgets, and a current state that's an index, and it renders the thing above, putting as many slots as there are widgets in the list, and making the indexth one be selected.

**Comment by yathit** [comment]
👍  Any update on this.

**Comment by alanrussian** [comment]
+1, while it's not too difficult to implement on our own, this would be really nice to have. mulligan has ran into use cases

**Comment by Hixie** [comment]
We might be able to reuse some of our work on CupertinoSegmentedControl.

**Comment by neerajyadav** [comment]
Any update on this.

**Comment by karnadii** [comment]
I really need this

**Comment by dblokhin** [comment]
Wow, yea! I hope this will be at stable as soon as possible, thanks!

**Comment by msarkrish** [comment]
ToggleButtons available in Flutter 1.9 Update. Go and Upgrade your Flutter.

**Comment by parammittal162** [comment]
Any idea how to implement Toggle Buttons Vertically ?

**Comment by Swepilot** [comment]
> Any idea how to implement Toggle Buttons Vertically ?

@parammittal162 Also looking for vertical ToggleButtons. Have you found anything?
