### ISSUE TITLE
Does the current clang can build flutter engine on raspberry pi 3 system

### ISSUE THREAD

**Issue by ping996** [flutter/flutter#39603]
Hi,

I have used the customed compile command:
```
./flutter/tools/gn --linux-cpu arm --runtime-mode debug --no-lto --target-os linux --arm-float-abi hard --no-goma --embedder-for-target --target-toolchain /home/wu/wuchuanping/flutter/src/src/buildtools/linux-x64/clang --target-triple arm-linux-gnueabihf --target-sysroot /home/wu/wuchuanping/tools/arm-bcm2708/arm-linux-gnueabihf/arm-linux-gnueabihf/sysroot
```
to build the flutter engine, the library was created, but it can't run on my target system.
I use the raspberry pi corss compile tool from the https://github.com/raspberrypi/tools .
does the flutter compile tools of clang support the raspberry pi system now? if it is not, how can I build the flutter engine successfully?
Thanks.

**Comment by ping996** [comment]
I compile the flutter engine and run on device successfully by follow the steps to create a custom a cross-compile envirnoment[https://solarianprogrammer.com/2019/05/04/clang-cross-compiler-for-raspberry-pi/](url)

**Comment by andyjjones28** [comment]
Ping996 as far as I can see that is only for setting up an armhf Clang(++) cross-compiler C/C++ programs.  How did you extend upon that to build cross-compile the flutter engine for armhf?  As far as I can tell you need the 'gn' tool, but my one keeps complaining with "ERROR Can't find source root."

**Comment by andyjjones28** [comment]
Never mind, disregard the above message.  The part that I was missing was the [contributing](https://chromium.googlesource.com/external/github.com/flutter/engine/+/b7358b33dbd61e124720165dd939fa49cbd0ecb6/CONTRIBUTING.md) guide for the flutter engine.  That gave me yet _another_ version of gn.  This one actually worked.
