### ISSUE TITLE
[Web] Named Routes as page URL

### ISSUE THREAD

**Issue by Akora-IngDKB** [flutter/flutter#39602]
Is possible to get named routes to be the page URL? If possible, how do I achieve that?

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. @Akora-IngDKB see also https://flutter.dev/community for support options.

**Comment by Akora-IngDKB** [comment]
@BondarenkoStas sure👍
