### ISSUE TITLE
Document Android embedding testing approaches

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#39604]
Currently, there isn't a clear or documented approach to write unit tests for the Android embedding code. Since unit tests and the testing framework were added after the code was written, it can be difficult to write good tests to ensure that we're testing behavior instead of the implementation details. 

For example, in https://github.com/flutter/engine/pull/11451 and https://github.com/flutter/engine/pull/11441 both test for the inner `MethodChannel.MethodCallHandler`. This required revealing what feels like an implementation detail to be visible for testing, which is not ideal.

We should come up with a better testing strategy for the Android embedding. Once that's been decided, we can refactor existing code and/or unit tests as necessary

**Comment by xster** [comment]
We have a number of ways of testing the embedding now. Document them.

**Comment by chinmaygarde** [comment]
Presumably, [this has already been done](https://github.com/flutter/flutter/wiki/Testing-the-engine#java---android-embedding).

**Comment by xster** [comment]
Correct. Thanks
