### ISSUE TITLE
Need to relocate google logo of google_maps_flutter package

### ISSUE THREAD

**Issue by ramioooz** [flutter/flutter#39610]
## Use case
I am using google_maps_flutter: ^0.5.19
I would like to have control over google logo position,
by default the logo is positioned at the bottom-left corner of GoogleMap() widget,
as per google-maps terms of service, their logo should be visible and not obscured by any of your app widgets. 
I have a rectangular button at the bottom of my app covering google logo, so in this case I think relocating google logo will go with google-maps terms of service.

case discussed here : 
https://stackoverflow.com/questions/57735253/flutter-how-to-relocate-re-position-google-maps-logo

## Proposal
I suggest that you expose access to control logo position in your upcoming version of the package, just like the one in javascript google-maps api.

Thank you

**Comment by ramioooz** [comment]
hello @KlausJokinen ,

adding padding in GoogleMap() widget shifts the whole map. meaning, all locations you will pick later from the map will be shifted/offset which is not what we want.

**Comment by betorcs** [comment]
Yeah.. I believe many time we want to change the padding without change the camera.

**Comment by bero93** [comment]
just adding the choice to choose from the four corners will be enough

**Comment by BataraSurya** [comment]
plus one for this. It would be nice to have a stack over the map without fear of covering up the Google logo. An options to relocate the logo will be great from UI design perspective

**Comment by gdlin** [comment]
I have the same issue, I think that choosing between the corners is more than enough. I currently have a stack over the map and I had to make sure that the logo is visible, I'd prefer to relocate it to another corner.

**Comment by xapatjb4** [comment]
Having the same issue as well

**Comment by leahcim601** [comment]
Same here.

**Comment by MaekawaTakahiro** [comment]
`
GoogleMap(
    padding: const EdgeInsets.only(bottom: 100),
　・
　・
)
`

google_maps_flutter: 2.1.1

Only the logo has moved. Is this ok?

**Comment by juskek** [comment]
Same here.

@MaekawaTakahiro this shifts the camera position as well; all future camera positioning on the map will need to account for the padding.

**Comment by Aristidios** [comment]
Same here - logo is hidden by a button

**Comment by Andrushka1012** [comment]
end of 2022, same here..

**Comment by brianmutiso** [comment]
Any solution to fix the camera positioning?

**Comment by manafire** [comment]
Adding padding to the GoogleMap shifts the map on IOS but does not on Android; the behaviour is inconsistent, making it incredibly difficult for folks to adhere to the strict terms on ensuring the logo always remains visible.
Using latest `google_maps_flutter v2.2.1` and `flutter 3.3.9`.

**Comment by kennethj** [comment]
@manafire  I am having the same issue on Android. I swore padding worked before.

**Comment by stuartmorgan** [comment]
This does not appear to be supported by the SDK (unsurprisingly since the Android docs specifically say it must be in the lower left corner).

Given that, there's nothing that can be done in the plugin, so closing.
