### ISSUE TITLE
Flutter HTTP Request get packages issue 

### ISSUE THREAD

**Issue by Reeloz** [flutter/flutter#39611]
1. I want to make an HTTP request so i use the import 'package: http/http.dart' but it display an error and it's not functioning (app couldn't resolve the 'http' ).
I updated my pubspec and added the http dependency ( http: ^0.12.0+2), and when 'flutter packages get' command run nothing happened  and when I tried to upgrade my flutter crashes occur.

## Logs

```
```

```
```

```
```

**Comment by BugsBunnyBR** [comment]
Hello there @Reeloz ,
You may want to read https://flutter.dev/docs/cookbook/networking/fetch-data ,
If you still struggle, it is better to open an stackoverflow issue than here.
When opening your issue there (or here), be sure to post the output of `flutter doctor -v`, your pubspec.yaml (if possible) and the log you get when trying to run your app.

You can open an issue there and post the link here if you find no help there.

Please close this issue as it does not seem to be a bug in flutter or it's related repositories.

**Comment by janmoppel** [comment]
Hello @Reeloz !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
