### ISSUE TITLE
Flutter app not run white screen

### ISSUE THREAD

**Issue by xesun** [flutter/flutter#39620]
## Steps to Reproduce
void main() {
BlocSupervisor.delegate = SimpleBlocDelegate();
final UserRepository userRepository = UserRepository();
  runApp(
    BlocProvider(
      builder: (context) => AuthenticationBloc(userRepository: userRepository)
        ..dispatch(AppStarted()),
      child: App(userRepository: userRepository),
    ),
  );
}

1. ...
2. ...
3. ...

## Logs
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
#0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:73:7)
#1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:86:4)
#2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
#3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
<asynchronous suspension>
#4      FirebaseApp.appNamed (package:firebase_c<…>

```
```

```
```

```
[✓] Flutter (Channel master, v1.9.6-pre.31, on Mac OS X 10.14.6 18G87, locale en-MN)
    • Flutter version 1.9.6-pre.31 at /Users/khamchunovog/Documents/Dev/flutter/flutter
    • Framework revision 677c4d5bb4 (4 days ago), 2019-08-27 06:12:06 -0400
    • Engine revision 4d7ea15cae
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/khamchunovog/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/khamchunovog/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 7AEA134C-6530-4F53-95E2-8F3F05D6E222 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

! Doctor found issues in 1 category.

```

**Comment by jld3103** [comment]
The error message says what you have to do...

**Comment by minh98** [comment]
paste `WidgetsFlutterBinding.ensureInitialized()` above runapp()

**Comment by xesun** [comment]
WidgetsFlutterBinding.ensureInitialized() above runapp()

**Comment by curtiscovington** [comment]
For me I was confused because I WidgetsFlutterBinding.ensureInitialized(); above runApp but it still wasn't working. Solution was to call in first in the main function above my   SystemChrome.setPreferredOrientations call. Hope that helps anyone else with this issue.

**Comment by rodrigolangowski** [comment]
> WidgetsFlutterBinding.ensureInitialized() above runapp()

I did that, make flutter clean, and the error still showing.

**Comment by zericksp** [comment]
i found an solution online:
just put this row to the top of the main function:
WidgetsFlutterBinding.ensureInitialized();

**Comment by GJson** [comment]
Firstly，use 'WidgetsFlutterBinding.ensureInitialized();'
Then, Debug mode  flutter use  ’kernel_bob.bin‘ communication，but in  Release mode  use 'app.so ', so   confirm your abiFilters like ’armeabi-v7a / arm64-v8a / x86_64‘  with project 'build.gradle'

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by tony123S** [comment]
@iapicca  have a look pls..Thanks
https://github.com/flutter/flutter/issues/55287#issuecomment-617207121
