### ISSUE TITLE
Cupertino Icons improvements

### ISSUE THREAD

**Issue by Nash0x7E2** [flutter/flutter#39629]
Working with Cupertino icons I found the following issues:
- The Character Map shown under the cupertino_icons package is outdated and should be updated to include the new character codes. Perhaps an automated script can be set up to keep this in sync 
 
-  The actual implementation for cupertino_icons is located in the framework and not the package. The `lib` folder found in cupertino_icons contains a placeholder from over a year ago.

**Comment by HansMuller** [comment]
CC @willlarche

**Comment by jeremie-movify** [comment]
Hi there,

here's my PR with an update Back chevron glyph :

https://github.com/flutter/cupertino_icons/pull/4

I'll open different PRs for subsequent font updates (mainly after integrating the SF Symbols font : https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/, as long as there are no Licence issues to use it).

Regards

**Comment by TahaTesser** [comment]
Related to [#42886](https://github.com/flutter/flutter/issues/42886)

**Comment by xster** [comment]
Merging into https://github.com/flutter/flutter/issues/33916
