### ISSUE TITLE
flutter engine install : gclient sync .   have a wrong :  cipd: failed to fetch flutter/android/ndk/mac-amd64:Kv-gU-BDcih2ZunKKGlBe2t9AXwHYFsG_HImF_CBnxoC - failed to download the package file after multiple attempts

### ISSUE THREAD

**Issue by yingyangios** [flutter/flutter#39630]

**Comment by BondarenkoStas** [comment]
@yingyangios Please add more information about the issue. Do you encounter it while setting up the Engine development environment and running ```gclient sync```? Any information about how to reproduce it?

**Comment by janmoppel** [comment]
Hello @yingyangios !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
