### ISSUE TITLE
cloud_functions parameters get back on JS, how?

### ISSUE THREAD

**Issue by klaszlo8207** [flutter/flutter#39638]
I have a flutter app, my code looks like this:

      dynamic result = await CloudFunctions.instance.getHttpsCallable(functionName: 'getAllItemsAfterDatetime').call(
        <String, dynamic> {"datetime": "1563109861142"}
      );

and a JS file:

```
exports.getAllItemsAfterDatetime= functions.https.onRequest(async (req, res) => {
  if (!mysqlPool) {
    mysqlPool = mysql.createPool(mysqlConfig);
  }
  
  let datetime = req.body.datetime;
  if (datetime == null) datetime = req.query.datetime;
  if (datetime == null) datetime = req.params.datetime;
  if (datetime == null) datetime = "3100000012120000";
```

I got allways "3100000012120000", so basically I can't get my datetime param back from mobil. It is working in browser. How to do this in a mobil app?

req.parameters is the correct word or WHAT?

Thanks

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, it's not a flutter issue report. See also https://flutter.dev/community for support options.

**Comment by VladyslavBondarenko** [comment]
Hi @klaszlo8207 
I understand that your are referring to a 3rd party plugin, 
you might want to consider opening an issue on the [plugin's github](https://github.com/FirebaseExtended/flutterfire/issues)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you
