### ISSUE TITLE
In webview_flutter, back buttom exit the app

### ISSUE THREAD

**Issue by ehsanrocket** [flutter/flutter#39645]
I have created a web view app with webview_flutter.
when I pressed the back button it exit the app instead of back to the previous web page 
here is my code :

` @override`
`  Widget build(BuildContext context) {`
`    return Scaffold(`
`      body: SafeArea(`
`        child: WebView(`
`            key: _key,`
`            javascriptMode: JavascriptMode.unrestricted,`
`            initialUrl: _url),`
`      ),`
`    );`
`  }`

how to override the back button behaviour

**Comment by mannprerak2** [comment]
Use the OnWillPopScope widget,
```dart
return WillPopScope(
  onWillPop: () async {
    return false;
  },
  child: Scaffold(
    …
  ),
);
```
This will stop the Navigator from popping on pressing the back button.
To intercept the back button to do something else change the onWillPop method. 
[See this answer](https://stackoverflow.com/a/49356916/7186086)`

**Comment by mannprerak2** [comment]
@ehsanrocket please close the issue if you think it has been resolved

**Comment by ehsanrocket** [comment]
thanks @mannprerak2
but still I need help
I am searching how to change the onWillPop method to back to the previous web page.

**Comment by ehsanrocket** [comment]
this works for me 
````flutter
return WillPopScope(
      onWillPop: _x,
      child: Scaffold(

  Future<bool> _x() {
    _controller.goBack();
  }
````
but how can i use `canGoBack()` method to see if there is a history item to back or not.

````flutter

**Comment by mannprerak2** [comment]
try this
```dart
Future<bool> _x(){
     if(canGoBack()){
         _controller.goBack():
         return false:
     }else{
          return true: // this will pop the widget
     }
}
```
and one last thing
@ehsanrocket this isn't a discussion forum, this is only meant for issues, please use stackoverflow or any other medium for your implementation doubts, so i request you to close this issue.

**Comment by ehsanrocket** [comment]
thanks @mannprerak2 
this works for me :
````flutter
 Future<bool> _x() {
    var canGoBack = _controller.canGoBack();
    if (canGoBack != null) {
      _controller.goBack();
    }
  }
````

**Comment by anubhavsinghgtm** [comment]
please share the whole code my _controller is giving some error

**Comment by iamraunakchatt** [comment]
return MaterialApp(
      home: WillPopScope(
        onWillPop: () async {
          webViewController!.goBack();
          return false;
        },
......


Do this that's it

@anubhavsinghgtm
