### ISSUE TITLE
Flutter in Docker - cannot seem to work 

### ISSUE THREAD

**Issue by zeromaro** [flutter/flutter#39648]
Hello,
I have an issue regarding Flutter in Docker. I cannot seem to be able to access 

> flutter

I tried putting flutter into regular directory, under /usr. Issues still there.
Here is my **Dockerfile**

> FROM ubuntu:18.04
> 
> ARG PROJECT_DIR=/srv/api
> RUN mkdir -p $PROJECT_DIR
> 
> WORKDIR $PROJECT_DIR
> 
> 
> RUN apt-get -y upgrade
> RUN apt-get update
> 
> RUN apt-get install -y xz-utils
> RUN apt-get install -y curl
> RUN curl https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.7.8+hotfix.4-stable.tar.xz -o /flutter.tar.xz
> RUN tar xf /flutter.tar.xz 
> #RUN mv flutter /srv/api/flutter
> RUN ls /srv/api/flutter
> RUN chmod a+x /srv/api/flutter
> RUN flutter doctor
> 
> RUN flutter upgrade
> RUN flutter packages pub global activate webdev
> RUN flutter packages upgrade
> 
> 
> COPY ./ ./
> 

It fails at **RUN flutter doctor**.
If I put in path **/srv/api/flutter** I receive error **flutter: not found**.
If I put in path **/usr/local/bin/flutter** I receive error **flutter: Permission Denied.**.

What do I do wrong here?

**Comment by stuartmorgan** [comment]
Flutter binaries are in the `bin` subdirectory; see https://flutter.dev/docs/get-started/install/linux for instructions on correctly configuring your path to use Flutter.

**Comment by zeromaro** [comment]
> Flutter binaries are in the `bin` subdirectory; see https://flutter.dev/docs/get-started/install/linux for instructions on correctly configuring your path to use Flutter.

Thank you for reply, Stuart. I was following this tutorial and I was not able to make it work. However, I just got help from StackOverflow. Guys helped me to fix this. Full solution is here. https://stackoverflow.com/questions/57747795/cannot-get-flutter-running-in-docker/57747991?noredirect=1#comment101934344_57747991
