### ISSUE TITLE
Should we use pub get instead of upgrade at end of flutter upgrade?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3964]
I noticed that running `flutter upgrade` also runs `pub upgrade`. That last step might be a little dangerous for developers. A `pub upgrade` might pull down a newer version of a package than what was specified in the `pubspec.lock`. That might be surprising, especially since `pub upgrade` is automatically run.

A better option might be `pub get`, which uses the `pubspec.lock` file if it exists. The `lock` file is nice, because further runs of `pub get` will get the same versions as specified in the `lock` file.

The user (developer) can then later, on their own and when they are ready, run `pub upgrade` and then test if any upgraded dependencies broke their app.

Output:

```
~/Code/flutter/examples/flutter_gallery[master] $ flutter upgrade
Building flutter tool...
Upgrading Flutter from /Users/sethladd/Code/flutter...
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter on channel master (from git@github.com:flutter/flutter.git)
Framework revision a6b8980d3e (7 minutes ago); engine revision a1f4a12baa

Running 'pub upgrade' in flutter_gallery...          12.5s
```

**Comment by abarth** [comment]
The thinking behind the current approach is that `flutter upgrade` would supersede `pub upgrade` as the way to pull in newer versions of a Flutter project's dependencies.

**Comment by sethladd** [comment]
Ah, I think I understand. `flutter upgrade` is a wrapper, in a way. Is there an equivalent of `flutter get` ?

**Comment by abarth** [comment]
We do something of a `flutter get` implicitly whenever you `flutter run`, but we could add an explicit command for it.

**Comment by sethladd** [comment]
Oh! We run `pub get` when we `flutter run` ?

**Comment by abarth** [comment]
Yes, if we detect that it's needed.

**Comment by sethladd** [comment]
OK, thanks for the explanation. I'll close as "works as intended" because upgrade means upgrade! :)
