### ISSUE TITLE
Allow plugins to not support Android

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#39657]
#10288 added a formal way to allow plugins to indicate which platforms they support, but any plugin that doesn't support Android (as in, has no `android/` folder) will cause Gradle failures. It looks from initial investigation like this is because `flutter.gradle` uses `.flutter-plugins`, which isn't platform-specific and thus isn't subject to platform filtering.

Presumably we should move away from having a single `.flutter-plugins` at all, and migrate all current clients to new platform-specific versions.

Currently the only way to make, say, a desktop-specific plugin that doesn't break Android is with a dummy directory.

**Comment by blasten** [comment]
This makes sense.  @amirh's proposal: "Distributed Platform Ownership for Flutter Plugins" touches on this--we could start by listing the platforms in the plugin's pubspec file.  I saw you made some comments in the doc, is there general agreement around that?

**Comment by stuartmorgan** [comment]
> we could start by listing the platforms in the plugin's pubspec file

#38632 already added support for that. This bug is specifically about making the right thing happen when you don't list Android there, which currently isn't the case.

**Comment by blasten** [comment]
oh excellent. I wasn't aware of that. 

We might still need `.flutter-plugins` though, but maybe we can split it by platform? Ootherwise, we need to pass the plugin list to Gradle as an argument, but that breaks add to app scenarios where the host app is built from Android Studio instead of the Flutter tool.

**Comment by stuartmorgan** [comment]
> We might still need .flutter-plugins though, but maybe we can split it by platform?

That's what I meant by "new platform-specific versions". (iOS and macOS would also benefit from having such files.)

**Comment by amirh** [comment]
So I guess the plan is to split `.flutter-plugins` into multiple `.flutter-plugins-<platform>` files. It sounds like we will need to implement auto-migration for for the gradle/xcode stuff (e.g the tool will update existing settings.gradle to refer to `.flutter-plugins-android`).

Any thoughts? better options?

@blasten @stuartmorgan @jonahwilliams

**Comment by blasten** [comment]
sgtm. One more reason for https://github.com/flutter/flutter/issues/40460

**Comment by stuartmorgan** [comment]
We don't necessary *have* to migrate; we could keep making `.flutter-plugins` for all existing projects, and tell people who want to start using plugins that don't support all of their project's platforms to manually delete the appropriate files (e.g., Podspec) and rebuild so it would generate a new version.

Not ideal, but possible.

**Comment by jonahwilliams** [comment]
I think there are a few independent pieces of work here.

One would be for all of the tooling to _gracefully_ handle a missing plugin implementation. This would at least unblock work in the short-term even it isn't the final strategy.

Separately, rather than create N `.flutter-plugins-platform` files I think we should update the tooling to look in the platform projects' ephemeral/output directory and then fall back to the project root. We can output platform specific .flutter-plugins in these directories without breaking any current workflows.

Once that is done, we can evaluate the cost of removing the project root plugins

**Comment by amirh** [comment]
> One would be for all of the tooling to _gracefully_ handle a missing plugin implementation. This would at least unblock work in the short-term even it isn't the final strategy.

@jonahwilliams can you sketch how you envision that? (to make sure we're all on the same page)

**Comment by amirh** [comment]
> One would be for all of the tooling to _gracefully_ handle a missing plugin implementation. This would at least unblock work in the short-term even it isn't the final strategy.

@jonahwilliams can you sketch how you envision that? (to make sure we're all on the same page)

**Comment by jonahwilliams** [comment]
In the android case, it would mean updating `flutter.gradle` to check for the correct files before creating a plugin task here:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/flutter.gradle#L250

Maybe it should print an error or warning, but definitely not crash.

**Comment by blasten** [comment]
> In the android case, it would mean updating flutter.gradle to check for the correct files before creating a plugin task here:

This also requires changes to `android/settings.gradle` since the plugins are still included as subprojects in app projects.

> Separately, rather than create N .flutter-plugins-platform files I think we should update the tooling to look in the platform projects' ephemeral/output directory and then fall back to the project root. 

@jonahwilliams This sounds good too. Do you plan to change `flutter create` so that it takes the list of target platforms as an argument?

**Comment by jonahwilliams** [comment]
> @jonahwilliams This sounds good too. Do you plan to change flutter create so that it takes the list of target platforms as an argument?

.flutter-plugins is not a part of flutter create. 

> This also requires changes to android/settings.gradle since the plugins are still included as subprojects in app projects.

Ahh yes, that's unfortunate. I would suggest @stuartmorgan's plan then

**Comment by amirh** [comment]
I prototyped excluding plugins without an `android/build.gradle` file from the list of plugins we're building in https://github.com/amirh/flutter/commit/bdcf4c5d19122a6bd7403d3eda4fb54d8d40f627. It seem to work, though I know very little about Gradle so am likely missing something. @blasten what should I expect to break if I didn't change anything in `android/settings.gradle`?

Also - do we have a reasonable harness to test such a thing?

**Comment by blasten** [comment]
> Also - do we have a reasonable harness to test such a thing?

We don't have a test where the app depends on a plugin that doesn't have an Android implementation.

If you remove the `android` directory in a plugin, and then `build apk` with your patch, you would get this error:

```
AILURE: Build failed with an exception.

* Where:
Script '.../flutter_tools/gradle/flutter.gradle' line: 695

* What went wrong:
A problem occurred configuring project ':device_info'.
> Could not get unknown property 'android' for project ':device_info' of type org.gradle.api.Project.

```

**Comment by amirh** [comment]
That's not what I'm seeing, this is what I'm trying (with the flutter.gradle patch):

```
flutter create -t plugin ios_only && cd ios_only && rm -rf android
```

Edit `pubspec.yaml` to use the new platforms schema with only iOS.

```
cd example && flutter build apk
```
^ it builds

**Comment by blasten** [comment]
Correction: @amirh patch works very well. We don't need change settings.gradle to make this work in the short term.

**Comment by stuartmorgan** [comment]
> Separately, rather than create N .flutter-plugins-platform files I think we should update the tooling to look in the platform projects' ephemeral/output directory

Agreed. I've been sloppy about referring to `.flutter-plugins-<platform>` for simplicity, but certainly for desktop I would much rather have `<platform>/flutter/ephemeral/.flutter-plugins` (or some similar file name; it doesn't necessarily need to be a dot-file in that location)

> I prototyped excluding plugins without an android/build.gradle file from the list of plugins we're building

Echoing my comment from the iOS bug: what's the advantage of doing this? This is the same file we'd need to change to point it to a different, Android-specific `.flutter-plugins` file, so this is doing more throw-away work with no benefit that I can see. Generating these platform-specific files in Dart should be trivial given that we already have all the code for filtering plugins by platform, including handling of fallbacks depending on whether or not plugins are using the new or old schema. And if we do that once, we can do iOS and Android the way we want to support long term right now, without an intermediate step.

**Comment by jonahwilliams** [comment]
> Echoing my comment from the iOS bug: what's the advantage of doing this? 

I see this as a general tool hardening, we shouldn't crash if files/folders are missing in easily anticipated ways. The fact that it unblocks some work temporarily is just a side effect.

**Comment by jonahwilliams** [comment]
>Generating these platform-specific files in Dart should be trivial given that we already have all the code for filtering plugins by platform

I agree, it's not much more difficult- we should do that also.

**Comment by amirh** [comment]
> Echoing my comment from the iOS bug: what's the advantage of doing this? This is the same file we'd need to change to point it to a different, Android-specific `.flutter-plugins` file, so this is doing more throw-away work with no benefit that I can see. Generating these platform-specific files in Dart should be trivial given that we already have all the code for filtering plugins by platform, including handling of fallbacks depending on whether or not plugins are using the new or old schema. And if we do that once, we can do iOS and Android the way we want to support long term right now, without an intermediate step.

I'm not sure how simple and/or reliable can the auto migration of existing apps' `settings.gradle` will be (which currently points to `.flutter-plugins), without that migration we need something like the current patch.

**Comment by stuartmorgan** [comment]
Oh, I missed that this is a file that's part of Flutter itself, not the project. I was assuming it would be similar to iOS, where the file is generated into the project and then left there, requiring some kind of update (migrated or manual). If we can retroactively fix all existing projects to handle this gracefully I definitely understand why it's worth doing.

**Comment by stuartmorgan** [comment]
I started playing around with generating platform-specific plugin files; [WIP here](https://github.com/flutter/flutter/compare/master...stuartmorgan:wip-platform-plugin-files?expand=1). It's totally untested (even manually), and we'd need to figure out if those are the right file locations on mobile, but I think that's basically the right structure.

Then we can incrementally work on removing all internal use of `.flutter-plugins`, except for continuing to write it for existing projects until/unless we migrate them.

I'm not sure when I'll have time to continue with that so if someone wants to take that and turn it into a real PR please feel free.

**Comment by jmagman** [comment]
@franciscojma86 Will this also be fixed by https://github.com/flutter/flutter/pull/47258?

**Comment by franciscojma86** [comment]
@jmagman That's an obsolete PR for now. The JSON logic has already [landed](https://github.com/flutter/flutter/pull/49085). The migration part will be discussed [here ](https://docs.google.com/document/d/1W_IpXetVIgjHipKnu-zPHnDApdiwXR0RfugY6Sm8NAg/edit), which might depend on the decisions taken in [this proposal](url)

**Comment by jmagman** [comment]
@franciscojma86  Can this issue be closed?  Or is there more work to track here?

**Comment by franciscojma86** [comment]
We still need no-op implementations for plugins, so we can't close this yet. We will close after  we migrate the templates.

**Comment by blasten** [comment]
This issue was fixed by https://github.com/flutter/flutter/pull/47015. Plugins that don't have an `android/build.gradle` aren't used when building for Android.

**Comment by ditman** [comment]
This is great! Does this mean we can remove the noop `android` directories from plugin packages?

**Comment by blasten** [comment]
Yep! However, I'd wait until the next stable release is rolled out. https://github.com/flutter/flutter/issues/46304 is tracking that
