### ISSUE TITLE
[in_app_purchase] transactionDate is in different format on iOS and Android

### ISSUE THREAD

**Issue by hillelcoren** [flutter/flutter#39652]
Here are example values for transactionDate:

iOS: 1567349262000 (milliseconds since epoch) 
Android: 1567361621 (seconds since epoch)

I think it would be best if the library abstracted the difference and provide a consistent value.

**Comment by kinex** [comment]
I guess you mean `PurchaseDetails.transactionDate`. Are you sure about this? I haven't noticed this issue in my app (plugin version 0.2.2+4) and also did not see any issue in the plugin code with a quick look. Value should be in milliseconds both for Android and iOS. Maybe there was such an issue in an older version.

**Comment by hillelcoren** [comment]
This was definitely a problem when I created the issue, I think you'd need to process a sample payment to see the issue rather than review the code.

**Comment by kinex** [comment]
Both my apps are already in stores and so far I have not seen related issue. I see correct timestamps saved in Firestore. So either there is no issue or then I am magically fixing the timestamps in some place which I cannot remember right now.

**Comment by hillelcoren** [comment]
Ok, I'll close the issue for now. If I can reproduce the problem with further testing I'll reopen it. Thanks for looking into it!

**Comment by kinex** [comment]
Ok. Please reopen if you can reproduce this with the latest version! It is a clear bug if the values are not in milliseconds.
