### ISSUE TITLE
Allow plugins to not support iOS

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#39659]
#10288 added a formal way to allow plugins to indicate which platforms they support, but any plugin that doesn't support iOS (as in, has no ios/ folder) will cause CocoaPods failures. This is because the Podspec uses `.flutter-plugins`, which isn't platform-specific and thus isn't subject to platform filtering.

When I added initial macOS plugin support I addressed this in [a somewhat hacky way](https://github.com/flutter/flutter/blob/fc05c3738ca64f65484527d7a9a824a0f0bc5706/packages/flutter_tools/templates/cocoapods/Podfile-macos#L38). While we could do the same on iOS, we should probably solve this by changing the use of `.flutter-plugins` instead (and update the macOS Podspec template to match). See also https://github.com/flutter/flutter/issues/39657

**Comment by amirh** [comment]
I like @jonahwilliams's proposal in https://github.com/flutter/flutter/issues/39657#issuecomment-531935682

The longer term solution would be separate `.flutter-plugins` files for each platform.

@stuartmorgan @jonahwilliams @jmagman for the shorter term, are we okay with landing something similar to [the macos hack](https://github.com/flutter/flutter/blob/fc05c3738ca64f65484527d7a9a824a0f0bc5706/packages/flutter_tools/templates/cocoapods/Podfile-macos#L38) for iOS as well? I guess if we're not going to fully parse the pubspec similarly to the current workaround we will need to assume a plugin supports ios if it has no ` *platforms:` lines or if it has ` *ios:`, note that FPs are possible, though I think they are unlikely in real world scenarios.

Alternatively we could make it more robust by adding a flutter tool command that actually parses the full pubspec and outputs the supported platforms, though if that isn't something we want to support for the longer term we should probably avoid it.

**Comment by stuartmorgan** [comment]
If we know we want to go to .flutter-plugins-ios, it's not clear to me that we save much effort by doing the hack. Adding the creation of .flutter-plugins-ios seems like it should be pretty simple.

If we do the hack then later do .flutter-plugins-ios then we have two legacy formats to document or write migration for instead of one.

**Comment by jmagman** [comment]
Just for CocoaPod-consuming platforms, another option (pending plugin migration) would be to create a podspec at the top level of the plugin, to be shared by all platforms:

Example:
https://github.com/flutter/plugins/blob/master/packages/path_provider/ios/path_provider.podspec
and
https://github.com/flutter/plugins/pull/1716/files#diff-92c55de68260e2180bcbca84b620a0e8
would be combined into one podspec at `packages/path_provider/path_provider.podspec`
```
Pod::Spec.new do |s|
  s.name             = 'path_provider'
  s.version          = '0.0.1'
  s.summary          = 'A Flutter plugin for getting commonly used locations on the filesystem.'
  s.description      = <<-DESC
A Flutter plugin for getting commonly used locations on the filesystem.
                       DESC
  s.homepage         = 'https://github.com/flutter/plugins/tree/master/packages/path_provider'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Flutter Team' => 'flutter-dev@googlegroups.com' }

  s.ios.source_files = 'ios/Classes/**/*'
  s.ios.public_header_files = 'ios/Classes/**/*.h'
  s.ios.dependency 'Flutter'
  s.ios.deployment_target = '8.0'

  s.osx.source_files = 'macos/Classes/**/*'
  s.osx.public_header_files = 'macos/Classes/**/*.h'
  s.osx.dependency 'FlutterMacOS'
  s.osx.deployment_target  = '10.12'
end
```
Then the tool can look for the `.flutter-plugins` podspec and let it describe the location of the source files.


There's also something to combining the platform Flutter.podspec and FlutterMacOS.podspec for the same reason.

**Comment by stuartmorgan** [comment]
That doesn't seem compatible with plugin federation, where macOS and iOS may not be in the same repo.

(I think it's also mostly orthogonal to this issue, because a plugin without macOS or iOS support shouldn't need a podspec, so we still can't unconditionally look for this combo podspec.)

**Comment by jmagman** [comment]
I wasn't suggesting it would unconditionally look for the podspec, I was suggesting the [hack](https://github.com/flutter/flutter/blob/fc05c3738ca64f65484527d7a9a824a0f0bc5706/packages/flutter_tools/templates/cocoapods/Podfile-macos#L38) wouldn't have to exist and no platform paths would have to be hard-coded if the podspec did exist.

I was hoping to avoid any macos or ios hacks at all by letting CocoaPods use the dependency or not based on the platforms it supports, but it doesn't work the way I hoped when only one is supported:
```ruby
platform :ios

abstract_target 'FlutterTarget' do
  pod 'macos_only_pod', :path => '.flutter-plugins/../macos_only_pod' # top-level podspec only has `s.osx.*` properties pointing to macos/ paths.

  target 'Runner' do
    platform :ios, '8.0'
  end
end
```

```shell
$ pod install
Analyzing dependencies
[!] The dependency `path_provider (from `path_provider.podspec`)` is not used in any concrete target
```
so... that won't work.

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/issues/39657#issuecomment-532050568 for a WIP implementation of platform-specific `.flutter-plugins` files, which would make newly created Podspecs only look at iOS/macOS plugins. (No migration in that patch; it's something we'd probably want to consider in a follow-up.)

**Comment by jmagman** [comment]
@franciscojma86 Will this also be fixed by https://github.com/flutter/flutter/pull/47258?

**Comment by franciscojma86** [comment]
@jmagman That's an obsolete PR for now. The JSON logic has already [landed](https://github.com/flutter/flutter/pull/49085). The migration part will be discussed [here ](https://docs.google.com/document/d/1W_IpXetVIgjHipKnu-zPHnDApdiwXR0RfugY6Sm8NAg/edit), which might depend on the decisions taken in [this proposal](url)

**Comment by blasten** [comment]
Is there any ETA for supporting this feature?  I tried creating a plugin that doesn't support iOS, but I got: 
```
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `camerax` from `.symlinks/plugins/camerax/ios`
    [!] No podspec found for `camerax` in `.symlinks/plugins/camerax/ios`
```

**Comment by jmagman** [comment]
I think the work here is to migrate the Podfile to parse `.flutter-plugins-dependencies` instead of `.flutter-plugins` and only include the iOS plugins
https://github.com/flutter/flutter/blob/e491544588e8d34fdf31d5f840b4649850ef167a/packages/flutter_tools/templates/cocoapods/Podfile-ios-objc#L70

This will be much easier once https://github.com/flutter/flutter/issues/45197 is done so we don't need to migrate Podfile's twice (or hopefully ever again) like:
https://github.com/flutter/flutter/blob/4ecb1bbe2d9eb5efabc13ba25eba50b3fdf788d2/packages/flutter_tools/lib/src/macos/cocoapods.dart#L36-L38
☹️

**Comment by stuartmorgan** [comment]
> I think the work here is to migrate the Podfile to parse .flutter-plugins-dependencies instead of .flutter-plugins

Alternately, there's now `flutter` logic for setting up a symlink folder just like that one, which Windows and Linux uses. We could have iOS (and macOS) use that instead, and just iterate over the directories that are created by `flutter`, instead of having to parse the file.

But either way it's a migration.
