### ISSUE TITLE
flutter pub global run devtools doesn't release the startup lock

### ISSUE THREAD

**Issue by bradyt** [flutter/flutter#39660]
I was following the instructions at https://flutter.dev/docs/development/tools/devtools/cli.

If I run the following in two separate terminals.

```
flutter pub global run devtools
flutter run
```

Then flutter hangs with the following message:

```
Waiting for another flutter command to release the startup lock...
```

If I swap the order of the commands, everything works.

**Comment by Hixie** [comment]
cc @jonahwilliams

**Comment by jonahwilliams** [comment]
This was fixed with https://github.com/flutter/flutter/pull/36218

**Comment by csells** [comment]
fixed
