### ISSUE TITLE
TextField API docs don't show how to GET value

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#39661]
There's various examples of TextField on the API docs, e.g. https://master-api.flutter.dev/flutter/material/TextField-class.html, but they don't show how you actually get the value from the user, which is probably the most important thing you can do with a text field.

We should have a simple example of using a text field to get a string from the user.

cc @justinmc

**Comment by Hixie** [comment]
https://master-api.flutter.dev/flutter/material/TextField/onChanged.html should have a sample too

**Comment by justinmc** [comment]
Agreed.
