### ISSUE TITLE
ios13 , keyboard , input , Interface jamming

### ISSUE THREAD

**Issue by BBBCat** [flutter/flutter#39667]
when I input  chinese  on iOS 13 , and click "done" on the keyboard , then view dead and no response

**Comment by BondarenkoStas** [comment]
@BBBCat Please provide ```flutter doctor -v``` output. And if possible some code example to reproduce the issue.

**Comment by BBBCat** [comment]
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/cjq/flutter
    • Framework revision 7a4c33425d (4 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/cjq/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode10.2.1.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • iPhoneM •******** • ios • iOS 13.0
• No issues found!
```

*****************************************


Code
Such as

```dart
Container(
            // need to fill space
            child: Expanded(
              // TextField need a  Material 
              child: Material(
                // ...
                child: TextField(
                  controller: inputController,
                  maxLength: widget.maxCount,
                  keyboardType: widget.keyboardType == null ? TextInputType.text : widget.keyboardType,
                  textAlign: (widget.rightTextAlign == null) ? TextAlign.start : widget.rightTextAlign,
                  maxLines: (widget.rightLines == null) ? 1 : widget.rightLines,
                  style: TextStyle(
                    fontSize: (widget.rightFontSize == null) ? 15 : widget.rightFontSize,
                  ),
                  decoration: InputDecoration(
                    hintText: defaultPlaceHolder,
                    border: OutlineInputBorder(),contentPadding: EdgeInsets.all(5.0),
                  ),
                ),
              ),
            ),
          )
```

PS：when I test another code which is only using a simple Textfield , it will crush on the iOS 13, but when I run the same code on iOS 13.1 , it's fine , thans for help!

**Comment by gilnuy** [comment]
i got the same problem.

**Comment by justinmc** [comment]
I don't see this happening in a simple `TextField()` in the iOS 13.0 simulator:

![chinese_text_2](https://user-images.githubusercontent.com/389558/65913481-dded1080-e384-11e9-9a4e-52db986fd7a0.gif)

Anything else I should be doing to reproduce it?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
