### ISSUE TITLE
[device_info] Add Windows support

### ISSUE THREAD

**Issue by Tumbler0809** [flutter/flutter#39674]
Is there any plan to support the windows platform? https://pub.dev/packages/device_info

**Comment by stuartmorgan** [comment]
Support for Windows in published plugins is currently blocked on a finalized plugin API and plugin tooling for Windows.

**Comment by zhileichen** [comment]
@stuartmorgan Is there any updates on the plugin API and tools for windows ? Is it possible to estimate when to finalize that ?

**Comment by zhileichen** [comment]
> @stuartmorgan Is there any updates on the plugin API and tools for windows ? Is it possible to estimate when to finalize that ?

Just ignore it.  I found  https://github.com/flutter/flutter/issues/32719 is tracking on it. Will watching on it.

**Comment by stuartmorgan** [comment]
This is blocked on https://github.com/flutter/flutter/issues/64569

**Comment by Ali-Fadaei** [comment]
any update or estimating for this? getting mac Address or something unique in windows is very important to me. appreciate if answer 🙏🏻

**Comment by stuartmorgan** [comment]
You may want to look at https://pub.dev/packages/device_info_plus, which has Windows support, to see if it meets your needs.

**Comment by stuartmorgan** [comment]
Closing as `device_info` is deprecated in favor of [`device_info_plus`](https://pub.dev/packages/device_info_plus).
