### ISSUE TITLE
How to full screen on windows platform

### ISSUE THREAD

**Issue by Tumbler0809** [flutter/flutter#39677]
I want to make my Flutter a full-screen app, but in fact it's height is high and the width is not full.

**Comment by stuartmorgan** [comment]
Please don't file duplicates of your own issues. You previously filed this as #39556

@BondarenkoStas In general, bugs about desktop are not documentation bugs, but lack of functionality, so shouldn't be tagged with documentation labels.

**Comment by BondarenkoStas** [comment]
@stuartmorgan Sorry, didn't get about this one, will check more carefully for future.
