### ISSUE TITLE
CupertinoDatePicker text color and background color are white in ios 13 dark mode

### ISSUE THREAD

**Issue by karan-appgambit** [flutter/flutter#39685]
CupertinoDatePicker text color and background color are white in ios 13 dark mode
![Simulator Screen Shot - iPhone Xs - 2019-09-02 at 18 13 49](https://user-images.githubusercontent.com/43993176/64115536-88d1d500-cdad-11e9-8b53-05f89819df7d.png)

**Comment by LongCatIsLooong** [comment]
I assume you're using the master channel? With https://github.com/flutter/flutter/pull/39056 merged you should be able to specify `CupertinoDatePicker`'s background color now.  Or you could simply disable system dark mode in `MediaQuery` or `CupertinoTheme`, for the time being.

We're working to update Cupertino components to support dark mode and this is an unfortunate side effect of the work in progress. It should finish relatively soon, maybe in one week or two. Sorry for the inconvenience!
