### ISSUE TITLE
The function 'setState' isn't defined.

### ISSUE THREAD

**Issue by heinzan** [flutter/flutter#39681]
This is mystateful widget.

   
    
    import 'package:flutter/material.dart';
    import 'package:tolymoly/models/user.dart';
    
    class Profile extends StatefulWidget{
      final User user;
      Profile({this.user});
      @override
      State<StatefulWidget> createState() {
        // TODO: implement createState
        return _ProfileState();
      }
    
    }
    
    class _ProfileState extends State<Profile>{
    
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(
            title: Text(
              "Profile",
              style: TextStyle(
                  fontWeight: FontWeight.w700,
                  fontSize: 18.0,
                  color: Colors.white,
                  fontFamily: "Gotik"),
            ),
            centerTitle: true,
            iconTheme: IconThemeData(color: Color(0xFF6991C7)),
            elevation: 0.0,
          ),
          body: SingleChildScrollView(
            child: Container(
              child: Column(
                children: <Widget>[
                  setting(widget.user),
                  Padding(
                    padding: const EdgeInsets.only(top: 5.0),
                    child: Container(
                      height: 50.0,
                      width: 1000.0,
                      color: Colors.white,
                      child: Padding(
                        padding: const EdgeInsets.only(
                            top: 13.0, left: 20.0, bottom: 15.0),
                        child: Text(
                          "Logout",
                        ),
                      ),
                    ),
                  )
                ],
              ),
            ),
          ),
        );
      }
    }
    

 I want to use setState method in this function.but cann't use.I
 comment setState place

    
    Widget setting(User user){
    
        return Padding(
          padding: const EdgeInsets.only(top: 5.0),
          child: Container(
            decoration: BoxDecoration(
              color: Colors.white,
            ),
            child: Padding(
              padding: const EdgeInsets.only(left: 14.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisAlignment: MainAxisAlignment.start,
                children: <Widget>[
                  Padding(
                    padding: EdgeInsets.symmetric(horizontal: 10.0, vertical: 15.0),
                    child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: <Widget>[
                          Text(
                            'Photo',
                          ),
                          Container(
                           child: Row(
                             children: <Widget>[
    
                               Image.network(user.image),
                               Icon(
                                 Icons.keyboard_arrow_right,
                                 color: Colors.black38,
                               )
                             ],
    
                           ),
                          ),
    
    
                        ]),
                  ),
                  Padding(
                    padding: const EdgeInsets.only(left: 10.0, right: 20.0),
                    child: Divider(
                      color: Colors.black12,
                      height: 0.5,
                    ),
                  ),
                 
                  Padding(
                    padding: const EdgeInsets.only(left: 10.0, right: 20.0),
                    child: Divider(
                      color: Colors.black12,
                      height: 0.5,
                    ),
                  ),
                
                  Padding(
                    padding: const EdgeInsets.only(left: 10.0, right: 20.0),
                    child: Divider(
                      color: Colors.black12,
                      height: 0.5,
                    ),
                  ),
                  Padding(
                    padding: EdgeInsets.symmetric(horizontal: 10.0, vertical: 
    15.0),
                    child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: <Widget>[
                          Text(
                            'Display phone to buyer',
                          ),
                          Checkbox(
                              tristate: true,
                              value: true,
                              onChanged: (bool newValue){
    `
                             setState((){
                                 //Cann't use
                             })
                              })
                        ]),
                  ),
                
            ),
          ),
        );
      }

i haven't find that solution.

Please help.

**Comment by Prathik-Jain** [comment]
Hi @heinzan ,

You should have the `setting` method inside the `_ProfileState` class, as that has to do with the state.
If you call `setState` outside, there is no way for flutter to recognize on which state should be updated!

Also I noticed some misplaced braces.
Here's the updated code for you.

```dart
class Profile extends StatefulWidget {
  final User user;
  Profile({this.user});
  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    return _ProfileState();
  }
}

class _ProfileState extends State<Profile> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          "Profile",
          style: TextStyle(
              fontWeight: FontWeight.w700,
              fontSize: 18.0,
              color: Colors.white,
              fontFamily: "Gotik"),
        ),
        centerTitle: true,
        iconTheme: IconThemeData(color: Color(0xFF6991C7)),
        elevation: 0.0,
      ),
      body: SingleChildScrollView(
        child: Container(
          child: Column(
            children: <Widget>[
              setting(widget.user),
              Padding(
                padding: const EdgeInsets.only(top: 5.0),
                child: Container(
                  height: 50.0,
                  width: 1000.0,
                  color: Colors.white,
                  child: Padding(
                    padding: const EdgeInsets.only(
                        top: 13.0, left: 20.0, bottom: 15.0),
                    child: Text(
                      "Logout",
                    ),
                  ),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }


Widget setting(String user) {
  return Padding(
    padding: const EdgeInsets.only(top: 5.0),
    child: Container(
      decoration: BoxDecoration(
        color: Colors.white,
      ),
      child: Padding(
        padding: const EdgeInsets.only(left: 14.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            Padding(
              padding: EdgeInsets.symmetric(horizontal: 10.0, vertical: 15.0),
              child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: <Widget>[
                    Text(
                      'Photo',
                    ),
                    Container(
                      child: Row(
                        children: <Widget>[
                          Image.network(user.image),
                          Icon(
                            Icons.keyboard_arrow_right,
                            color: Colors.black38,
                          )
                        ],
                      ),
                    ),
                  ]),
            ),
            Padding(
              padding: const EdgeInsets.only(left: 10.0, right: 20.0),
              child: Divider(
                color: Colors.black12,
                height: 0.5,
              ),
            ),
            Padding(
              padding: const EdgeInsets.only(left: 10.0, right: 20.0),
              child: Divider(
                color: Colors.black12,
                height: 0.5,
              ),
            ),
            Padding(
              padding: const EdgeInsets.only(left: 10.0, right: 20.0),
              child: Divider(
                color: Colors.black12,
                height: 0.5,
              ),
            ),
            Padding(
              padding: EdgeInsets.symmetric(horizontal: 10.0, vertical: 15.0),
              child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: <Widget>[
                    Text(
                      'Display phone to buyer',
                    ),
                    Checkbox(
                        tristate: true,
                        value: true,
                        onChanged: (bool newValue) {
                          setState(() {
                            // Works now :)
                          });
                        }),
                  ]),
            ),
          ],
        ),
      ),
    ),
  );
}

}
```

**Comment by BondarenkoStas** [comment]
Thank you @Prathik-Jain! @heinzan please report if that will solve your issue.
Also, this is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. See https://flutter.dev/community for support options.

**Comment by heinzan** [comment]
> Thank you @Prathik-Jain! @heinzan please report if that will solve your issue.
> Also, this is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. See https://flutter.dev/community for support options.

I post this issue but stackoverflow show error in code.
"It looks like your post is mostly code, please add some more details"
so i post in github.

**Comment by heinzan** [comment]
@Prathik-Jain .Thanks you bro.My stupid false.
