### ISSUE TITLE
Reuse already compiled app when debugging

### ISSUE THREAD

**Issue by dancojocaru2000** [flutter/flutter#39688]
## Use case
I have an old laptop and even building the debug app takes around 45 seconds. Sometimes the phone locks itself during this time and when the debug app is finally built, deployment fails because the phone is locked.

## Proposal

If no changes to things like assets happened, instead of rebuilding, use the old debug app and just deploy it.

**Comment by jonahwilliams** [comment]
This is supported via the `--use-application-binary` flag.

```
    --use-application-binary                          Specify a pre-built application binary to use when running.
```
