### ISSUE TITLE
Flutter uses http to connect with device?

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#39680]
I received this error on android (ASUS ZB605KL)

```
Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:56333/3co9he_oiVs=/
```
If Flutter uses http to connect with device - this is total bullshit. Only an idiot can come up with this

**Comment by BondarenkoStas** [comment]
@alex9153 advice you to post the question to StackOverflow as well.
It's a physical device, right?

**Comment by stuartmorgan** [comment]
If you have issues with the design of the Dart observatory, you'll need to file a bug against Dart. Closing as this is out of the scope of Flutter.

I would recommend taking a more constructive tone in your issue if you do so.

**Comment by broberts-nybble** [comment]
Hi Gents, 

Any solution to this?
