### ISSUE TITLE
"Tree-hygiene" link to "AUTHORS" pointing to wiki, not repo

### ISSUE THREAD

**Issue by jeffque** [flutter/flutter#39695]
[Tree-hygiene](../wiki/Tree-hygiene#using-git) link to `AUTHORS` is pointing to a wiki page on  GitHub/Flutter-wiki, not to the actual file `AUTHORS` in the repo.

Highlighint what is show:

> You must complete the [Contributor License Agreement] (https://cla.developers.google.com/clas). You can do this online, and it only takes a minute. If you've never submitted code before, you must add your (or your organization's) name and contact info to the [AUTHORS] (https://github.com/flutter/flutter/wiki/AUTHORS) file.

And then what I was expecting:

> You must complete the [Contributor License Agreement] (https://cla.developers.google.com/clas). You can do this online, and it only takes a minute. If you've never submitted code before, you must add your (or your organization's) name and contact info to the [AUTHORS] (https://github.com/flutter/flutter/blob/master/AUTHORS) file.

**Comment by jmagman** [comment]
Done with https://github.com/flutter/flutter/wiki/Tree-hygiene/b75082895127b524d1423470ac10e90df6048b79.  Thank you for the detailed issue, @jeffque!
