### ISSUE TITLE
update_dart_sdk.ps1 is not digitally signed on Windows

### ISSUE THREAD

**Issue by newuser44** [flutter/flutter#39692]
## Steps to Reproduce
Trying to set up flutter on a new work laptop with windows 10.  
1. Follow the command to clone flutter.
2. Run flutter doctor in power shell gives the following error. 

> PS C:\dev\Flutter> flutter doctor
> Checking Dart SDK version...
> & : File C:\dev\Flutter\bin\internal\update_dart_sdk.ps1 cannot be loaded. The file
> C:\dev\Flutter\bin\internal\update_dart_sdk.ps1 is not digitally signed. You cannot run this script on the current
> system. For more information about running scripts and setting execution policy, see about_Execution_Policies at
> https:/go.microsoft.com/fwlink/?LinkID=135170.
> At line:1 char:73
> + ... te_dart_sdk.ps1'; & 'C:\dev\Flutter/bin/internal/update_dart_sdk.ps1'
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : SecurityError: (:) [], PSSecurityException
>     + FullyQualifiedErrorId : UnauthorizedAccess
> Error: Unable to update Dart SDK. Retrying...

--- I have tried to run the update_dart.sdk.ps1 manually but same results.  
PS C:\dev\Flutter\bin\internal> Get-ExecutionPolicy
AllSigned

PS C:\dev\Flutter\bin\internal> Unblock-File -Path .\update_dart_sdk.ps1
(runs with no output)

> PS C:\dev\Flutter\bin\internal> .\update_dart_sdk.ps1
> .\update_dart_sdk.ps1 : File C:\dev\Flutter\bin\internal\update_dart_sdk.ps1 cannot be loaded. The file
> C:\dev\Flutter\bin\internal\update_dart_sdk.ps1 is not digitally signed. You cannot run this script on the current
> system. For more information about running scripts and setting execution policy, see about_Execution_Policies at
> https:/go.microsoft.com/fwlink/?LinkID=135170.
> At line:1 char:1
> + .\update_dart_sdk.ps1
> + ~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : SecurityError: (:) [], PSSecurityException
>     + FullyQualifiedErrorId : UnauthorizedAccess

Unable to run

**Comment by BondarenkoStas** [comment]
@newuser44 Can you please specify exactly what the version of Windows 10 you have? Can you confirm that you did ```git clone -b stable https://github.com/flutter/flutter.git```, not downloading zip package from git?

**Comment by newuser44** [comment]
Yes.  I cloned it again. I got the same error.  But i think its something with my work laptop and how the permissions are set up on there.  

PS C:\dev\flutter> Get-ExecutionPolicy -list

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       AllSigned
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine          Bypass

I tried to set up local machine but it does't matter.  I have to get my company to change the policy?

**Comment by dgbaena** [comment]
Hi guys, any update about this issue?

**Comment by yuniorlaureano** [comment]
En mi caso lo qui hice fue descargar el zip de flutter, no clonarlo desde git. Esto me solucionó el problema.

**Comment by yuniorlaureano** [comment]
Flutter the da la opcion de descargar el zip, o clonar desde git, en mi caso para solucionar el problema lo hice utilizando el zip, ya que el del repositorio me daba ese error.

**Comment by dbaengine** [comment]
I download the .zip file and still have the issue :( 

I haven't been able to work on flutter for a month....

**Comment by ziyko** [comment]
This problem still exists, help me solve it.

**Comment by darshankawar** [comment]
@newuser44  @ziyko 
Can you confirm if this is still an issue using latest version of framework ? The framework has gone through lot of updates since this issue was filed and has stable support for windows, so let us know if this is still an issue or not.

**Comment by JoshuaWi** [comment]
Hi @darshankawar I am not the OP but I can confirm I'm still seeing this issue when running `flutter upgrade` I'm on a client windows 10 machine and have the same issue. It occurs when attempting to run the ps1 file manually as well
