### ISSUE TITLE
[google_maps_flutter] Custom marker size does not adapt to screen resolution

### ISSUE THREAD

**Issue by simonabadoiu** [flutter/flutter#39691]
Hi!

I am using google_maps_flutter with custom marker icons.
Everything used to be ok before version 0.5.19. When version 0.5.19 was launched, with the change *"Allow BitmapDescriptor scaling override"*, the old icon images started to be displayed at a very small size compared to before.
Our marker images start at size 35x46. The example in google_maps_flutter uses an image of size 48x48 which is supposed to be the standard marker size, isn't it?..
Also, if we change our marker images, and make the start size ~400x400, then the markers would be displayed at an OK size on a FHD screen resolution, but an HD resolution setting would display considerably bigger markers. Is it a normal behavior?
Sending the optional size parameter when calling *createLocalImageConfiguration* makes no difference.
Since no issue was opened on this topic until now, I imagine I am doing something wrong but I really don't know what 🤔

The tests have been made with version 0.5.21

P.S. The other markers are loaded directly from the 3.0x folder and they seem to have the same behavior

This is the code for loading an image:
```
_createMarkerImageFromAsset(
        context,
        'assets/markers/unselected/troti_selected_full.png'
    ).then((BitmapDescriptor fullMarkerIcon) {
      store.dispatch(SetMarkerIconsAction(fullMarkerIcon: fullMarkerIcon));
    });

 static Future<BitmapDescriptor> _createMarkerImageFromAsset(BuildContext context, String path) {
    final ImageConfiguration imageConfiguration =
    createLocalImageConfiguration(context);
    return BitmapDescriptor.fromAssetImage(imageConfiguration, path);
  }
```

Loading the image with size param:
```
 static Future<BitmapDescriptor> _createMarkerImageFromAsset(BuildContext context, String path) {
    final Size size = Size(10, 10);
    final ImageConfiguration imageConfiguration =
    createLocalImageConfiguration(context, size: size);
    return BitmapDescriptor.fromAssetImage(imageConfiguration, path);
  }
```
I have attached 4 screenshots - *please pay attention to the marker with a green battery and an e-scooter compared to the standard red marker*.

this is how the markers started to be displayed once we upgraded to version 0.5.19
![small_image_size_FHD_screen](https://user-images.githubusercontent.com/1610123/64117721-9338a280-cd9e-11e9-9bb3-198146e86a59.jpg)

this is how the markers started to be displayed once we upgraded to version 0.5.19, using HD screen resolution
![small_image_size_HD_screen](https://user-images.githubusercontent.com/1610123/64117727-9764c000-cd9e-11e9-9416-291b09558a7b.jpg)

this is the marker after using the ~400x400 image for 1.0x on Full HD
![large_image_size_FHD_screen](https://user-images.githubusercontent.com/1610123/64117728-99c71a00-cd9e-11e9-927d-518cdec36700.jpg)

this is the marker after using the ~400x400 image for 1.0x on HD
![large_image_size_HD_screen](https://user-images.githubusercontent.com/1610123/64117731-9b90dd80-cd9e-11e9-8b9a-4ca78553ca3c.jpg)

**Comment by rafaelferreirapt** [comment]
Any updates?

**Comment by theochampion** [comment]
Having the same problem here

**Comment by bogdannedelcu** [comment]
Can we help on this one?

**Comment by rafaelferreirapt** [comment]
This PR is in review for days... 
https://github.com/flutter/plugins/pull/1821

**Comment by darshankawar** [comment]
@simonabadoiu 
Is this still a valid issue using [latest](https://pub.dev/packages/google_maps_flutter/install) plugin version ? 
If so, can you provide a complete minimal reproducible code sample that we can directly use to verify this ?

Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
