### ISSUE TITLE
race condition on restart, file change notifications, and the flutter web compilation service

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#39696]
There's a race condition when Flutter web is used from IntelliJ; this race (which we generally always loose) means that people don't see their changes after a restart - they have to restart twice.

When reloading (or restarting), IntelliJ saves all files before we reload. We then issue a reload (or a restart) command to the flutter process. However, it looks like the package:build based compilation service used in flutter web only knows about file changes when notified by its own watcher. So, there's a race condition:

- the user makes changes in one or more files, and (via a keybinding or icon) issues a restart command
- IntelliJ saves file contents
- it then tells the flutter daemon to restart a flutter web app
- it restarts
- it gets notified of changes top the file system (from the file save earlier)
- the changes get compiled

We nearly always loose this race condition. https://github.com/flutter/flutter-intellij/pull/3842 has more details (and a temporary workaround for IntelliJ).

We likely want to do something like explicitly poll the file system for changes at the start of a reload request, instead of just relying on being kept up to date by the watcher.

cc @jonahwilliams

**Comment by jonahwilliams** [comment]
cc @grouma 

My understanding is the the "manual" build daemon mode is supposed to cover this by disabling automatic file watching and rebuilding. If it is instead still watching for changes and only has manual triggers of builds, then that would explain the race.

An unfortunate short term workaround would be to add a fixed delay. Longer term, we might need to re-explore having the flutter tool provide the list of changed assets.

_____

See

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_runner/web_fs.dart#L386

This was added to build daemon here:

https://github.com/dart-lang/build/blob/9c37817df024e86052d78e3c886c1d12ed5b9e63/build_daemon/CHANGELOG.md#200

**Comment by grouma** [comment]
That's correct. We still watch for file changes because it's the build system that knows what directories to watch, e.g. where in the pub cache to look for changes.

**Comment by jonahwilliams** [comment]
Instead of watching, could build_daemon walk the filesystem when triggered via the manual mode? Otherwise we're going to be fighting with race conditions here indefinitely.

**Comment by grouma** [comment]
The API would allow for that fairly easy as we "collect" changes before doing a build. However, the actual implementation simply buffers the changes as we don't manually do a file poll. I'm less familiar with the graph watcher implementation and this may be something we can change. 

@jakemac53 or @natebosch is the graph watcher capable of doing a poll for changes: https://github.com/dart-lang/build/blob/118025f4c498208028f5301fc458e3a4c34e7119/build_runner/lib/src/daemon/daemon_builder.dart#L196

**Comment by natebosch** [comment]
It isn't an option today, but we could take a look at adding something. We already have some code that crawls looking for changed files which we used at startup and we could extract that to make it available to collect changes on a manual build.

The reason we probably lose the race more often than not today is the delay for debounce on file changes.

**Comment by jakemac53** [comment]
I can go ahead and work on switching this to a manual scan

**Comment by jakemac53** [comment]
I have now published build_runner_core 3.1.0 and build_runner 1.6.8 which will switch this to do a manual file system scan on demand.

**Comment by jakemac53** [comment]
@jonahwilliams can you pull these into flutter_tool and after that @devoncarew can you validate the issue is solved and close if so?

**Comment by jonahwilliams** [comment]
Will do, thanks Jake

**Comment by jonahwilliams** [comment]
Opened https://github.com/flutter/flutter/pull/39988

**Comment by devoncarew** [comment]
> @jonahwilliams can you pull these into flutter_tool and after that @devoncarew can you validate the issue is solved and close if so?

Awesome, thanks for the fix; I'll verify it locally.

**Comment by jonahwilliams** [comment]
@devoncarew does this fix the race condition with intellij?

**Comment by jonahwilliams** [comment]
Confirmed locally this works with intellij

**Comment by devoncarew** [comment]
> @devoncarew does this fix the race condition with intellij?

Sorry, a bit delayed, but I also confirmed it works (as well as the updated reload/restart behavior for flutter web).
