### ISSUE TITLE
Phone number text field could open a number keyboard

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3970]
In the gallery, we have text field demo. One of the fields is for a phone number. Currently, it opens a text keyboard. We could instead open a number keyboard.

This can then show the developer how to open different keyboards, and also how to configure an input widget as "only numbers".

From the gallery:

![screenshot_20160517-101555](https://cloud.githubusercontent.com/assets/5479/15331993/bbc070e2-1c18-11e6-8ced-ce07de8d98cb.png)

From the contacts app on android:

![screenshot_20160517-101910](https://cloud.githubusercontent.com/assets/5479/15332076/050f3a9e-1c19-11e6-81ba-a5c8efcb95b3.png)

**Comment by sethladd** [comment]
@mpcomplete not sure how easy this is to configure. If easy, let's try to do it for the first version. If it takes a bunch of plumbing, then we can move to the next release. Thanks!

**Comment by abarth** [comment]
The plumbing should all be there already.  You just need to supply the appropriate http://docs.flutter.io/flutter/material/Input/keyboardType.html

**Comment by sethladd** [comment]
Great, thanks for the tip!

**Comment by mpcomplete** [comment]
Oh duh.. that didn't even occur to me. Fixing.

**Comment by sethladd** [comment]
Closed by https://github.com/flutter/flutter/pull/3983

Thanks for the quick turnaround!
