### ISSUE TITLE
Flutter plugin not install in simulator and real device

### ISSUE THREAD

**Issue by caiovncius** [flutter/flutter#39700]
I am making a new plugin for Flutter.

I ran and plugin template generator: 
```
flutter create --org example.com - template = plugin -i swift my_plugin
```

So far, I haven't written any lines of code. I run: 
```
cd my_plugin
flutter build ios --no-codesign
```

I opened the project in Xcode and had it run in the emulator. The build runs successfully. But when it will run in the emulator, it presents the following error:

![Captura de Tela 2019-09-02 às 17 24 25](https://user-images.githubusercontent.com/4031854/64132687-e7945000-cda7-11e9-89aa-d187420863f5.png)

And on the physical device, it even installs, even though an error cannot create the Flutter VM.

**Comment by caiovncius** [comment]
In my tests, i see, when in first build, install the app in emulator, the app, run ok. But, after, not run. If I uninstall the app, back run, work fine.

**Comment by iapicca** [comment]
Hi @caiovncius 
if the issue persist with the latest stable version of flutter
could you please provide your updated `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by VladyslavBondarenko** [comment]
@caiovncius 
I hope you've solved the issue.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
