### ISSUE TITLE
Flutter create fails: pub upgrade, "still failing after 10 tries, giving up"

### ISSUE THREAD

**Issue by osunkoyadavid** [flutter/flutter#39705]
when i run flutter create app in the flutter console.bat it gives an error when i run flutter create app in the flutter console.bat it gives an errorwhen i run flutter create app in the flutter console.bat it gives an errorError: 
```
'pub upgrade' still failing after 10 tries, giving up. Cannot create a project within the Flutter SDK. Target directory 'C:\Users\Tola.Osunkoya\Desktop\flutter_windows_v1.0.0-stable\flutter\packages\flutter_tools\app' is within the Flutter SDK at 'C:\Users\Tola.Osunkoya\Desktop\flutter_windows_v1.0.0-stable\flutter'.Waiting for 0 seconds, press CTRL+C to quit ... Running pub upgrade... The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.  Because flutter_tools requires SDK version >=2.2.2 <3.0.0, version solving failed. Error Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)
```

**Comment by osunkoyadavid** [comment]
when i run flutter create app in the flutter console.bat it gives an error when i run flutter create app in the flutter console.bat it gives an errorwhen i run flutter create app in the flutter console.bat it gives an errorError: 'pub upgrade' still failing after 10 tries, giving up. Cannot create a project within the Flutter SDK. Target directory 'C:\Users\Tola.Osunkoya\Desktop\flutter_windows_v1.0.0-stable\flutter\packages\flutter_tools\app' is within the Flutter SDK at 'C:\Users\Tola.Osunkoya\Desktop\flutter_windows_v1.0.0-stable\flutter'.Waiting for 0 seconds, press CTRL+C to quit ... Running pub upgrade... The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297. Because flutter_tools requires SDK version >=2.2.2 <3.0.0, version solving failed. Error Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)

**Comment by BondarenkoStas** [comment]
@osunkoyadavid Please follow the guidelines and file your issue report properly.
Don't put all the info to header. Use ``` ``` ``` to outline logs and code, provide flutter doctor output etc.

Shortly looking at the issue, did you try to update Dart SDK as the error log advises?

**Comment by janmoppel** [comment]
Hello @osunkoyadavid !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.

**Comment by osunkoyadavid** [comment]
> @osunkoyadavid Please follow the guidelines and file your issue report properly.
> Don't put all the info to header. Use ``` to outline logs and code, provide flutter doctor output etc.
> 
> Shortly looking at the issue, did you try to update Dart SDK as the error log advises?

How can i do that, i really am frustrated and really want to use flutter

**Comment by osunkoyadavid** [comment]
Error: The Flutter directory is not a clone of the GitHub project.
       The flutter tool requires Git in order to operate properly;
       to set up Flutter, run the following command:
       git clone -b beta https://github.com/flutter/flutter.git
Another issue that i'm getting
When i ran git clone -b beta https://github.com/flutter/flutter.git command, it still gives the same error,
I'm sorry but flutter is too compilcated
