### ISSUE TITLE
The key to becoming a future-oriented flutter

### ISSUE THREAD

**Issue by wikiworldlang** [flutter/flutter#39712]
## Use case
[![](http://img.youtube.com/vi/ZGcOqnVGAbE/0.jpg)](http://www.youtube.com/watch?v=ZGcOqnVGAbE "")

## Proposal
How to make it intuitive
=============
You can write your code in gui.
----------------

**Comment by BondarenkoStas** [comment]
@wikiworldlang It's not in the flutter roadmap. Closing, as this is not an issue report. If you insist, please make a detailed proposal about the change, otherwise it's not helpful at all.
If you want to share your idea, please check https://flutter.dev/community for support options.
