### ISSUE TITLE
Unable to locate android sdk while installing flutter on Ubuntu.

### ISSUE THREAD

**Issue by sagarsolace123** [flutter/flutter#39719]
Hi Folks,

Need small help for configuring Android SDK in flutter configuration over Linux server.
We are trying to achieve a Cordova kind of solution to compile android apps using Flutter SDK.

But, While running command "flutter doctor" it's throwing an error for not able to locate Android SDK even setting up the necessary paths.

1. "flutter config --android-sdk /path/to/android/sdk"
2. export ANDROID_HOME="/usr/lib/android-sdk/"
3. export PATH="${PATH}:${ANDROID_HOME}tools/:${ANDROID_HOME}platform/"

Also, We are successfully able to execute Android SDK commands that clearly seen it's working fine. Only the challenge is to configure this Android SDK information within Flutter config.

Really appreciate a help on this.

Best,
SagarSolace

**Comment by BondarenkoStas** [comment]
@sagarsolace123 May there be a typo in your 3th command?
I believe it's supposed to be 
```
export PATH="${PATH}:${ANDROID_HOME}tools/:${ANDROID_HOME}platform-tools/"
```

**Comment by janmoppel** [comment]
Hello @sagarsolace123 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
