### ISSUE TITLE
Codelabs on adding Crashlytics version error

### ISSUE THREAD

**Issue by alemangui** [flutter/flutter#39721]
### On https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#6

The codelab specifies to use version 3.2.1 of ```com.google.gms:google-services``` and **not to use a higher version**. However, version 3.2.1 has a bug and does not find the google-services.json file (```Could not find google-services.json while looking in [src/nullnull/profile, src/profile/nullnull, src/nullnull, src/profile, src/nullnullProfile]```). 

This bug is not present in version 4.3.1 of ```com.google.gms:google-services```. See first comment on [this SO answer](https://stackoverflow.com/a/47565868/1046444).

To make matters more confusing, but the codelab then links to [this guide](https://firebase.google.com/docs/android/setup#manually_add_firebase) which specifies 4.3.1 as the version to use on the Android side.

**Comment by kroikie** [comment]
@alemangui

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/342. Any further collaboration will be done there.
