### ISSUE TITLE
Power BI

### ISSUE THREAD

**Issue by oscarlagatta** [flutter/flutter#39726]
I'm willing to embed Power BI reports on a Flutter application, what are the libraries needed for flutter/Dart to work with the reports ?

**Comment by BondarenkoStas** [comment]
@oscarlagatta Sorry to say, there is no such library/plugin. Developer's community will create a request at some point.
You can ask for help at StackOverflow, also you may check https://flutter.dev/community for support options. 
Closing, as this is not an issue report.
