### ISSUE TITLE
CheckboxListTile setState not working

### ISSUE THREAD

**Issue by Xavjer** [flutter/flutter#39731]
## Steps to Reproduce

I have a PopupMenuButton with PopupMenuItems which have an AnimatedBuilder as a child with a CheckboxListTile built.

Clicking the row of the Checkbox does not set the State automatically, which seems to be as designed. But calling **setState will not rebuild the view**, therefore the Checkbox is not visibly selected (Even tough it's set correctly). Reopening the PopupMenu will then display the Checkbox checked.

I also have RadioListTile which have the same hierarchy as the CheckboxListTile. Clicking one of these works as expected, this **also rebuild the Checkboxes which are shown correctly afterwards**.

<img width="291" alt="Screenshot 2019-09-03 at 11 59 53" src="https://user-images.githubusercontent.com/4498205/64163893-6342db00-ce42-11e9-936d-7067d9d157c3.png">

```
  @override
  Widget build(BuildContext context) {
    var sfo = widget.searchFilterSortOptions;

    return PopupMenuButton<dynamic>(
        icon: Icon(SSAIcons.FILTER),
        itemBuilder: (BuildContext context) {
          var list = List<PopupMenuEntry<dynamic>>();

          list.add(PopupMenuItem(
              value: null,
              child: new AnimatedBuilder(
                  child: new Text("Gruppierung und Filter", style: TEXT_GRAY),
                  animation: _selectedItem,
                  builder: (BuildContext context, Widget child) {
                    return new ListTile(title: Text("Gruppierung und Filter",style: TextStyle(fontWeight: FontWeight.bold)));
                  })));

          for (Filter f in sfo.availableFilters) {
            list.add(PopupMenuItem(
                value: f,
                child: new AnimatedBuilder(
                    child: new Text(sfo.getNameForBase(f, context), style: TEXT_GRAY),
                    animation: _selectedItem,
                    builder: (BuildContext context, Widget child) {
                        return new RadioListTile<BaseSortFilter>(
                            value: f,
                            groupValue: _selectedItem.value,
                            title: child,
                            controlAffinity: ListTileControlAffinity.trailing,
                            onChanged: (BaseSortFilter value) {
                              _selectedItem.value = value;
                              sfo.setActiveSort(value);
                              widget.selectedCallback(sfo);
                              Navigator.of(context).pop();
                            });
                    })));
          }

          list.add(PopupMenuDivider());

          if (sfo.displayLastEdited || sfo.displayCreator) {
            if (sfo.displayLastEdited) {
              list.add(PopupMenuItem(
                  value: sfo.lastEdited.active,
                  child: new AnimatedBuilder(
                      child: new Text(sfo.getNameForBase(sfo.lastEdited, context), style: TEXT_GRAY),
                      animation: _selectedItem,
                      builder: (BuildContext context, Widget child) {
                        return new CheckboxListTile(
                            value: sfo.lastEdited.active,
                            selected: sfo.lastEdited.active,
                            title: child,
                            controlAffinity: ListTileControlAffinity.trailing,
                            onChanged: (bool value) {
                              setState(() {
                                sfo.lastEdited.active = value;
                                widget.selectedCallback(sfo);
                              });
                            });
                      })));
            }

            if (sfo.displayCreator) {
              list.add(PopupMenuItem(
                  value: sfo.creator.active,
                  child: new AnimatedBuilder(
                      child: new Text(sfo.getNameForBase(sfo.creator, context), style: TEXT_GRAY),
                      animation: _selectedItem,
                      builder: (BuildContext context, Widget child) {
                        return new CheckboxListTile(
                            value: sfo.creator.active,
                            selected: sfo.creator.active,
                            title: child,
                            controlAffinity: ListTileControlAffinity.trailing,
                            onChanged: (bool value) {
                              setState(() {
                                sfo.lastEdited.active = value;
                                widget.selectedCallback(sfo);
                              });
                            });
                      })));
            }
            list.add(PopupMenuDivider());
          }

          list.add(PopupMenuItem(
              value: null,
              child: new AnimatedBuilder(
                  child: new Text("Mehr Filter", style: TEXT_GRAY),
                  animation: _selectedItem,
                  builder: (BuildContext context, Widget child) {
                    return new ListTile(title: Text("Mehr Filter", style: TextStyle(fontWeight: FontWeight.bold)), trailing: Icon(SSAIcons.CHEVRON_LARGE_RIGHT));
                  })));

          return list;
        });
  }
```
## Logs
```
No error messages thrown
```

`flutter analyze` is just giving information and one warning, all unrelated

```
[✓] Flutter (Channel unknown, v1.9.8-pre.54, on Mac OS X 10.14.5 18F132, locale
    en-CH)
    • Flutter version 1.9.8-pre.54 at /Users/c.wyss/Documents/Projects/flutter
    • Framework revision 16fcb83fec (6 hours ago), 2019-09-02 23:44:41 -0400
    • Engine revision e7f9ef6aa0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 36985859e4)

```

**Comment by DoubleHub** [comment]
I have the very same problem!

**Comment by xperiafan13-rom** [comment]
same problem!

**Comment by DoubleHub** [comment]
A workaround you can apply is to rebuild the whole tree when updating the state of a checkbox in the list. But this is so heavy! Definitely need a proper solution for this!!!

**Comment by StancuFlorin** [comment]
I replicated this issue on v1.9.1+hotfix.6
Do you know in what version it was added?

**Comment by ateymurazov7** [comment]
hey guys, any progress?

**Comment by richardrobinson0924** [comment]
You can wrap the `CheckboxListTile` in a `StatefulBuilder` widget and call the second argument of the builder instead of setState.

For example,

```dart
PopupMenuButton(
            onSelected: (_) {},
            itemBuilder: (_) => [
                  PopupMenuItem<bool>(
                    child: StatefulBuilder(
                      builder: (context, _setState) => CheckboxListTile(
                        value: Model.instance().widgetIndex == index,
                        onChanged: (newValue) {
                          _setState(() => Model.instance().widgetIndex =
                              newValue ? index : 0);
                        },
                      ),
                    ),
                  )
                ],
            icon: Icon(Icons.more_vert))
```

**Comment by DoubleHub** [comment]
> You can wrap the `CheckboxListTile` in a `StatefulBuilder` widget and call the second argument of the builder instead of setState.
> 
> For example,
> 
> ```dart
> PopupMenuButton(
>             onSelected: (_) {},
>             itemBuilder: (_) => [
>                   PopupMenuItem<bool>(
>                     child: StatefulBuilder(
>                       builder: (context, _setState) => CheckboxListTile(
>                         value: Model.instance().widgetIndex == index,
>                         onChanged: (newValue) {
>                           _setState(() => Model.instance().widgetIndex =
>                               newValue ? index : 0);
>                         },
>                       ),
>                     ),
>                   )
>                 ],
>             icon: Icon(Icons.more_vert))
> ```

This is what I did like 1 month ago, and it works! I was always forgetting to post it here tho...

**Comment by kf6gpe** [comment]
I believe that @richardrobinson0924's fix is the correct one, so I'm going to close this issue. Thank you, and thanks to all for using Flutter!

**Comment by UsamaAndroid** [comment]
same problem! i used checkbox in bottom sheet setState is not working

**Comment by debjeetdebnath** [comment]
I am also getting the same error when I am including CheckBox in ListTile 
here is my code 

class TaskCheckBox extends StatelessWidget {

  bool isChecked = false;

  @override
  Widget build(BuildContext context) {
    return Checkbox(value: isChecked,
        onChanged: (newValue) {
          setState(() {
            isChecked =true;
          });
    }
    );
  }
}

**Comment by UsamaAndroid** [comment]
@debjeetdebnath below is the best implementation of CheckBox with text (CheckBoxListTile). I have used this in my project recently you can also use this as given below in your code.
.
bool checkBoxFollowingDeals = false;
CheckboxListTile(
                          title: Text("Following Deals"),
                          value: checkBoxFollowingDeals,
                          activeColor: Colors.green,
                          checkColor: Colors.white,
                          onChanged: (newValue) {
                            setState(() {
                              checkBoxFollowingDeals = newValue;
                            });
                          },
                          controlAffinity: ListTileControlAffinity
                              .trailing, //  <-- leading Checkbox
                        ),

**Comment by debjeetdebnath** [comment]
> @debjeetdebnath below is the best implementation of CheckBox with text (CheckBoxListTile). I have used this in my project recently you can also use this as given below in your code.
> .
> bool checkBoxFollowingDeals = false;
> CheckboxListTile(
> title: Text("Following Deals"),
> value: checkBoxFollowingDeals,
> activeColor: Colors.green,
> checkColor: Colors.white,
> onChanged: (newValue) {
> setState(() {
> checkBoxFollowingDeals = newValue;
> });
> },
> controlAffinity: ListTileControlAffinity
> .trailing, // <-- leading Checkbox
> ),

Hello @UsamaAndroid  , Thanks for the reply but I got my problem with my code 
I was using Stateless widget .... after converting it to stateful my code is now working with the help of setState .. here is my working code - 

class TaskCheckBox extends StatefulWidget {

  @override
  _TaskCheckBoxState createState() => _TaskCheckBoxState();
}

class _TaskCheckBoxState extends State<TaskCheckBox> {
  bool isChecked = false;

  @override
  Widget build(BuildContext context) {
    return Checkbox(value: isChecked,
        onChanged: (newValue) {
          setState(() {
            isChecked =true;
          });
    }
    );
  }
}

**Comment by UsamaAndroid** [comment]
> > @debjeetdebnath below is the best implementation of CheckBox with text (CheckBoxListTile). I have used this in my project recently you can also use this as given below in your code.
> > .
> > bool checkBoxFollowingDeals = false;
> > CheckboxListTile(
> > title: Text("Following Deals"),
> > value: checkBoxFollowingDeals,
> > activeColor: Colors.green,
> > checkColor: Colors.white,
> > onChanged: (newValue) {
> > setState(() {
> > checkBoxFollowingDeals = newValue;
> > });
> > },
> > controlAffinity: ListTileControlAffinity
> > .trailing, // <-- leading Checkbox
> > ),
> 
> Hello @UsamaAndroid , Thanks for the reply but I got my problem with my code
> I was using Stateless widget .... after converting it to stateful my code is now working with the help of setState .. here is my working code -
> 
> class TaskCheckBox extends StatefulWidget {
> 
> @override
> _TaskCheckBoxState createState() => _TaskCheckBoxState();
> }
> 
> class _TaskCheckBoxState extends State {
> bool isChecked = false;
> 
> @override
> Widget build(BuildContext context) {
> return Checkbox(value: isChecked,
> onChanged: (newValue) {
> setState(() {
> isChecked =true;
> });
> }
> );
> }
> }

Welldone I appreciate that.
