### ISSUE TITLE
[google_maps_flutter] plugin 0.5.21 regression, polylines updates are not displayed.

### ISSUE THREAD

**Issue by SirJohn2024** [flutter/flutter#39737]
Polylines are not updated because the new added ```hasChanged()``` method in ```_PolylineUpdates.from()```, always found the previous and current polyline being the same.
As a test, returnig true from ```hasChanged()``` restore the correct behavior.

The polyline was used to track the user route on the map, the only thing changing being the number of points.
Now, to restore the behavior, the PolylineId() must be unique, causing the old one to be removed.

**Comment by joaquinperaza** [comment]
This is really severe

**Comment by iskakaushik** [comment]
@ppicas I agree with you. When we store the state of `Polygons`, `Polylines` etc, can we store a clone of the object? Maybe adding `clone` a method to each of these would make it consistent. Let me know if you can get to this in the next couple of days, if not I can do it.

**Comment by ppicas** [comment]
Of  course @iskakaushik, I'll prepare a pull request :slightly_smiling_face:

**Comment by sergicastellsague** [comment]
this can be closed now
