### ISSUE TITLE
ios flutter communication error

### ISSUE THREAD

**Issue by gitzhangliang** [flutter/flutter#39746]
I hava three page;   one flutter page;
                                 two ios page;
                                 three ios page;
the issue is: 
    when one skip to  two ,and two back one .it is ok.
   but one skip to two,and two skip to three ,and three back to two, and two back to one ,it is error;
the error is : 'package:flutter/src/gestures/converter.dart': Failed assertion: line 156 pos 20: '!state.down': is not true.

**Comment by glancer000** [comment]
This is more of a coding error than an issue with Flutter.

This should be a question asked on https://stackoverflow.com/

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but with implementation. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
