### ISSUE TITLE
local.properties not in .gitignore

### ISSUE THREAD

**Issue by car-anubis** [flutter/flutter#39742]
Create new flutter app.
There are two local.properties files:
```android/local.properties```
```.android/local.properties```

Both of these files contain references to local directories, but .gitignore lists only
**/android/local.properties
So file .android/local.properties is still put in source control.
It should also be in .gitignore, possibly with some other files from .android folder

```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.950], locale pl-PL)
    • Flutter version 1.7.8+hotfix.4 at C:\flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Grzegorz\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Grzegorz\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88

[!] VS Code, 64-bit edition (version 1.34.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • SM J510FN • ae08ec9e • android-arm • Android 7.1.1 (API 25)
```

**Comment by tbm98** [comment]
I was added both of them
```
android/local.properties
.android/local.properties
```
but local.properties still show on source control :( 
how to fix it?

**Comment by ronniechew** [comment]
same issue...

already added this:
`**/android/local.properties`

yet, changes in local.properties still present in Source Control tab

**Comment by tbm98** [comment]
resolved. 
add 
```
android/local.properties
.android/local.properties
```
to .gitignore file and run `git rm --cached <path to file>` and local.properties should be remove :D

**Comment by PushkaraSharma** [comment]
Hello, thanks for this easy issue, I would like to contribute to it , and will send a PR soon for it. Thanking you 
Kindly lemme know how to connect with the team and solve issues, I am really looking forward to solving more issues and contribute to this great Project.

**Comment by PushkaraSharma** [comment]
https://github.com/flutter/flutter/pull/57134 i have resolved it , Kindly review

**Comment by Pragya007** [comment]
I tried reproducing it, but `flutter create project_name` doesn't create `.android` folder..

**Comment by SirusCodes** [comment]
Fixed in #40864
Can be closed.

**Comment by TahaTesser** [comment]
@SirusCodes 
Thanks!
Closing as fixed, If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by allanlaal** [comment]
should this include /local.properties ?
