### ISSUE TITLE
Expected a value of type 'double', but got one of type 'bool' while nesting ListViews

### ISSUE THREAD

**Issue by chandraka** [flutter/flutter#39743]
Using ExpansionTile in a Flutter Web Project.

I am trying to build a ListView with ExpansionTile which nests another ListView inside the ExpansionTile. I am facing the following exception when I expand the First (outermost) Tile.
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════ dart_sdk.js:18998:15
The following assertion was thrown building ListView(scrollDirection: vertical, primary: using dart_sdk.js:18998:15
primary controller, AlwaysScrollableScrollPhysics, dependencies: [MediaQuery, dart_sdk.js:18998:15
PrimaryScrollController]): dart_sdk.js:18998:15
Expected a value of type 'double', but got one of type 'bool' dart_sdk.js:18998:15
dart_sdk.js:18998:15
Either the assertion indicates an error in the framework itself, or we should provide substantially dart_sdk.js:18998:15
more information in this error message to help you determine and fix the underlying cause. dart_sdk.js:18998:15
In either case, please report this assertion by filing a bug on GitHub: dart_sdk.js:18998:15
  https://github.com/flutter/flutter/issues/new?template=BUG.md dart_sdk.js:18998:15
dart_sdk.js:18998:15
When the exception was thrown, this was the stack: dart_sdk.js:18998:15
dart:sdk_internal 21414:17                                                     check_num dart_sdk.js:18998:15
package:flutter_web/src/widgets/scroll_position.dart 352:20                    restoreScrollOffset dart_sdk.js:18998:15
package:flutter_web/src/widgets/scroll_position.dart 80:27                     new dart_sdk.js:18998:15
package:flutter_web/src/widgets/scroll_position_with_single_context.dart 57:8  new dart_sdk.js:18998:15
package:flutter_web/src/widgets/scrollable.dart 328:10                         [_updatePosition] dart_sdk.js:18998:15
package:flutter_web/src/widgets/scrollable.dart 336:5                          didChangeDependencies dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 4080:12                         [_firstBuild] dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 3913:5                          mount dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 3095:13                         inflateWidget dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 2898:12                         updateChild dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 3955:16                         performRebuild dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 3732:5                          rebuild dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 3918:5                          [_firstBuild] dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 3913:5                          mount dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 3095:13                         inflateWidget dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 2898:12                         updateChild dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 3955:16                         performRebuild dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 3732:5                          rebuild dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 3918:5                          [_firstBuild] dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 3913:5                          mount dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 3095:13                         inflateWidget dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 2898:12                         updateChild dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 3955:16                         performRebuild dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 3732:5                          rebuild dart_sdk.js:18998:15
package:flutter_web/src/widgets/framework.dart 2342:31                         buildScope dart_sdk.js:18998:15
package:flutter_web/src/widgets/binding.dart 704:20                            drawFrame dart_sdk.js:18998:15
package:flutter_web/src/rendering/binding.dart 279:5                           [_handlePersistentFrameCallback] dart_sdk.js:18998:15
package:flutter_web/src/scheduler/binding.dart 1014:15                         [_invokeFrameCallback] dart_sdk.js:18998:15
package:flutter_web/src/scheduler/binding.dart 954:9                           handleDrawFrame dart_sdk.js:18998:15
package:flutter_web/src/scheduler/binding.dart 866:5                           [_handleDrawFrame] dart_sdk.js:18998:15
package:flutter_web_ui/src/engine.dart 168:21                                  <fn> dart_sdk.js:18998:15
dart_sdk.js:18998:15
════════════════════════════════════════════════════════════════════════════════════════════════════ dart_sdk.js:18998:15
```

**Comment by BondarenkoStas** [comment]
@chandraka Please provide ```flutter doctor -v``` output, and if possible some code snippet to be sure to reproduce the issue.

**Comment by chandraka** [comment]
Code:
ListView --> ExpansionTile -> ListView -> ExpansionTile and so on based on returns from the DB

----------------------------BEGIN
import 'package:flutter_web/material.dart';

import 'splitbar.dart';

import 'model/product.dart';

import 'model/product-methods.dart';

import 'model/readable-container.dart';
import 'model/readable-container-methods.dart';

class ReadableDashboardHomePage extends StatefulWidget{
  ReadableDashboardHomePage({Key key,this.title}) : super(key:key);

  final String title;

  @override
  ReadableDashboardHomePageState createState(){
    return new ReadableDashboardHomePageState(title:this.title);
  }
}

class ReadableDashboardHomePageState extends State<ReadableDashboardHomePage>{

  final String title;

  Future<List<dynamic>> productsFuture;

  ReadableDashboardHomePageState({Key key,this.title}) : super();

  @override
  void initState(){
    super.initState();
    productsFuture = ProductMethods.listProducts();
  }

  @override
  Widget build(BuildContext context){
    return Scaffold(
      appBar : AppBar(
        title: Text(title),
      ),
      body:SplitBar(
        onWeightChanged: (weight) => print('weight: $weight'),
        left: Container(
          child: new FutureBuilder(
            future: productsFuture,
            builder:(BuildContext context,AsyncSnapshot<List<dynamic>> productsSnapshot){
              if(!productsSnapshot.hasData){
                return new Center(child:new Text("Loading ..."));
              } else {
                return new ProductsExpansionTileList(productsSnapshot.data);
              }
            },
          ),
          color : Theme.of(context).accentColor
        ),//^^^ Left Side Content
        right: Container(
          color : Theme.of(context).primaryColor
        ),//^^^ Right Side Content
      ),//Split Bar
    );//Scaffold
  }
}

///Product
class ProductsExpansionTileList extends StatelessWidget{
  final List<Product> products;

  ProductsExpansionTileList(this.products);

  @override
  Widget build(BuildContext context){
    return ListView.builder(
      itemCount:products.length,
      itemBuilder:(BuildContext context,int index){
        return new ProductExpansionTile(products[index]);
      }
    );
  }
}

class ProductExpansionTile extends StatefulWidget{
  final Product product;

  ProductExpansionTile(this.product);

  @override
  State createState() => new ProductExpansionTileState();
}

class ProductExpansionTileState extends State<ProductExpansionTile>{
  PageStorageKey key;

  Future<List<dynamic>> readableContainersFuture;

  Map<String,String> makeQueryParameters(int productId){
    Map<String,String> qp = {};
    qp['productId'] = productId.toString();
    return qp;
  }

  @override
  void initState(){
    super.initState();
    readableContainersFuture = ReadableContainerMethods.listReadableContainers(makeQueryParameters(widget.product.id));
  }

  @override
  Widget build(BuildContext context){
    key = new PageStorageKey('PRODUCT${widget.product.id}');

    return new ExpansionTile(
      key:key,
      title:new Text(widget.product.name),
      children:<Widget>[
        new FutureBuilder(
          future:readableContainersFuture,
          builder:(BuildContext context,AsyncSnapshot<List<dynamic>> readableContainersSnapshot){
            if(!readableContainersSnapshot.hasData){
              return new Center(
                child: new Text("Loading ...")
              );
            } else if(readableContainersSnapshot.hasError){
              return new Center(
                child: new Text("ERROR:" + readableContainersSnapshot.error.toString())
              );
            }
            else {
              return new ReadableContainersExpansionTileList(readableContainersSnapshot.data);
            }
          }
        )
      ]
    );
  }

}
///// Readablecontainer
class ReadableContainersExpansionTileList extends StatelessWidget{
  final List<ReadableContainer> readableContainers;

  ReadableContainersExpansionTileList(this.readableContainers);

  @override
  Widget build(BuildContext context){
    try{
      List<Widget> children = [];

      for(ReadableContainer readableContainer in readableContainers){
        children.add(new ReadableContainerExpansionTile(readableContainer));
      }
      return ListView.builder(
        itemCount:readableContainers.length,
        itemBuilder:(BuildContext context,int index){
          return new ReadableContainerExpansionTile(readableContainers[index]);
        }
      );
    } catch(e){
      print("ERROR while building ReadableContainersExpansionTileList:" + e.toString());
    }
  }
}

class ReadableContainerExpansionTile extends StatefulWidget{
  final ReadableContainer readableContainer;

  ReadableContainerExpansionTile(this.readableContainer);

  @override
  State createState() => new ReadableContainerExpansionTileState();
}

class ReadableContainerExpansionTileState extends State<ReadableContainerExpansionTile>{
  PageStorageKey key;

  Map<String,String> makeQueryParameters(int parentReadableContainerId){
    Map<String,String> qp = {};

    qp['parentReadableContainerId'] = parentReadableContainerId.toString();

    return qp;
  }

  @override
  Widget build(BuildContext context){
    try{
      key = new PageStorageKey('READABLECONTAINER${widget.readableContainer.id}');

      return new ExpansionTile(
        key:key,
        title: new Text(widget.readableContainer.name),
        children:<Widget>[
          new FutureBuilder(
            future:ReadableContainerMethods.listReadableContainers(makeQueryParameters(widget.readableContainer.id)),
            builder:(BuildContext context,AsyncSnapshot<List<dynamic>> readableContainersSnapshot){
              try{
                if(!readableContainersSnapshot.hasData){
                  return new Center(
                    child: new Text("Loading ...")
                  );
                } else if(readableContainersSnapshot.hasError){
                  return new Center(
                    child: new Text("ERROR:" + readableContainersSnapshot.error.toString())
                  );
                }else {
                  return new ReadableContainersExpansionTileList(readableContainersSnapshot.data);
                }
              }catch(e){
                print("ERROR while running future builder:" + e.toString());
              }
            }
          )
        ]
      );
    } catch(e){
      print("ERROR while building ReadableContainerExpansionTileState:" + e.toString());
    }
  }

}

-----------------------------END

**Comment by chandraka** [comment]
godel% flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-GB)
    • Flutter version 1.7.8+hotfix.4 at /Users/chandraka/Applications/flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/chandraka/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✗] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
godel%

**Comment by ferhatb** [comment]
Hi, modified version of your sample is below (to be able to run it standalone to repro). It crashed in flutter as well. Modified to make it pass in flutter and the exception went away in Flutter web as well. Please take a look, if you can still repro web specific failure, please send it modified to repro.

```
import 'dart:async';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: const ReadableDashboardHomePage(title: 'AppTitle1')));

class ReadableDashboardHomePage extends StatefulWidget{
  const ReadableDashboardHomePage({Key key, @required this.title}) : super(key:key);

  final String title;

  @override
  ReadableDashboardHomePageState createState(){
    return ReadableDashboardHomePageState(title: title);
  }
}

Map<String, String> makeQueryParameters(String productid) => <String, String>{};

class ReadableContainerMethods {
  static Future<List<dynamic>> listReadableContainers(Map<String, String> params) => Future<List<dynamic>>.value(<dynamic>[]);
}

class ReadableContainer {
  ReadableContainer(this.id, this.name);

  final int id;
  final String name;
}

class Product {
  Product(this.id, this.name);

  final int id;
  final String name;
}

class ProductMethods {
  static Future<List<Product>> listProducts() =>
      Future<List<Product>>.value(<Product> [
      ]);
}

class ReadableDashboardHomePageState extends State<ReadableDashboardHomePage>{

  ReadableDashboardHomePageState({Key key, @required this.title}) : super();

  final String title;

  Future<List<dynamic>> productsFuture;

  @override
  void initState(){
    super.initState();
    productsFuture = ProductMethods.listProducts();
  }

  @override
  Widget build(BuildContext context){
    return Scaffold(
      appBar : AppBar(
        title: Text(title),
      ),
      body:
        SizedBox(width: 600, height: 800, child:
          Row(children: <Widget>[
            Container(
              child: FutureBuilder<List<dynamic>>(
                future: productsFuture,
                builder:(BuildContext context,AsyncSnapshot<List<dynamic>> productsSnapshot){
                  if(!productsSnapshot.hasData){
                    return Center(child: const Text('Loading ...'));
                  } else {
                    return ProductsExpansionTileList(productsSnapshot.data);
                  }
                },
              ),
              color : Theme.of(context).accentColor
            ),//^^^ Left Side Content
            Container(
              color : Theme.of(context).primaryColor
            ),//^^^ Right Side Content
          ]),//Split Bar
        ),
    );//Scaffold
  }
}

///Product
class ProductsExpansionTileList extends StatelessWidget{
  const ProductsExpansionTileList(this.products);

  final List<Product> products;

  @override
  Widget build(BuildContext context){
    return SizedBox(width: 600, height: 800, child: ListView.builder(
      itemCount:products.length,
      itemBuilder:(BuildContext context,int index){
        return ProductExpansionTile(products[index]);
      }
    ),);
  }
}

class ProductExpansionTile extends StatefulWidget{
  const ProductExpansionTile(this.product);

  final Product product;

  @override
  State createState() => ProductExpansionTileState();
}

class ProductExpansionTileState extends State<ProductExpansionTile>{
  PageStorageKey<String> key;

  Future<List<dynamic>> readableContainersFuture;

  Map<String,String> makeQueryParameters(int productId){
    Map<String,String> qp = {};
    qp['productId'] = productId.toString();
    return qp;
  }

  @override
  void initState(){
    super.initState();
    readableContainersFuture = ReadableContainerMethods.listReadableContainers(makeQueryParameters(widget.product.id));
  }

  @override
  Widget build(BuildContext context){
    key = PageStorageKey<String>('PRODUCT${widget.product.id}');

    return ExpansionTile(
      key:key,
      title: Text(widget.product.name),
      children:<Widget>[
        FutureBuilder(
          future:readableContainersFuture,
          builder:(BuildContext context,AsyncSnapshot<List<dynamic>> readableContainersSnapshot){
            if(!readableContainersSnapshot.hasData){
              return Center(
                child: const Text('Loading ...')
              );
            } else if(readableContainersSnapshot.hasError){
              return Center(
                child: Text('ERROR:' + readableContainersSnapshot.error.toString())
              );
            }
            else {
              return ReadableContainersExpansionTileList(readableContainersSnapshot.data);
            }
          }
        )
      ]
    );
  }

}
///// Readablecontainer
class ReadableContainersExpansionTileList extends StatelessWidget{
  ReadableContainersExpansionTileList(this.readableContainers);

  final List<ReadableContainer> readableContainers;

  @override
  Widget build(BuildContext context){
    try{
      List<Widget> children = [];

      for(ReadableContainer readableContainer in readableContainers){
        children.add(ReadableContainerExpansionTile(readableContainer));
      }
      return ListView.builder(
        itemCount:readableContainers.length,
        itemBuilder:(BuildContext context,int index){
          return ReadableContainerExpansionTile(readableContainers[index]);
        }
      );
    } catch(e){
      print('ERROR while building ReadableContainersExpansionTileList: $e');
    }
  }
}

class ReadableContainerExpansionTile extends StatefulWidget{
  final ReadableContainer readableContainer;

  ReadableContainerExpansionTile(this.readableContainer);

  @override
  State createState() => ReadableContainerExpansionTileState();
}

class ReadableContainerExpansionTileState extends State<ReadableContainerExpansionTile>{
  PageStorageKey key;

  Map<String,String> makeQueryParameters(int parentReadableContainerId){
    Map<String,String> qp = {};

    qp['parentReadableContainerId'] = parentReadableContainerId.toString();

    return qp;
  }

  @override
  Widget build(BuildContext context){
    try{
      key = PageStorageKey<String>('READABLECONTAINER${widget.readableContainer.id}');

      return ExpansionTile(
        key:key,
        title: Text(widget.readableContainer.name),
        children:<Widget>[
          FutureBuilder<List<dynamic>>(
            future: ReadableContainerMethods.listReadableContainers(makeQueryParameters(widget.readableContainer.id)),
            builder:
                (BuildContext context,AsyncSnapshot<List<dynamic>> readableContainersSnapshot){
                    try{
                      if(!readableContainersSnapshot.hasData){
                        return Center(
                          child: const Text('Loading ...')
                        );
                      } else if(readableContainersSnapshot.hasError){
                        return Center(
                          child: Text('ERROR:' + readableContainersSnapshot.error.toString())
                        );
                      }else {
                        return ReadableContainersExpansionTileList(readableContainersSnapshot.data);
                      }
                    } catch(e){
                      print('ERROR while running future builder:' + e.toString());

                    }
                  return null;
                }
          )
        ]
      );
    } catch(e) {
      print('ERROR while building ReadableContainerExpansionTileState:' + e.toString());
    }
    return null;
  }
}
```

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
