### ISSUE TITLE
basic_material_app_win__compile  release_size_bytes regression

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#39758]
Regression introduced at https://github.com/flutter/flutter/pull/39157/files
![Capture](https://user-images.githubusercontent.com/2388229/64194941-28867600-ce35-11e9-8154-e78d36686113.PNG)

**Comment by franciscojma86** [comment]
hello_world_android__compile5138K bytesrelease_size_bytes is also affected

**Comment by Hixie** [comment]
@blasten Are you reverting your PR?
