### ISSUE TITLE
Maps SDK for Flutter

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#39750]
## Use case

While the [google_maps_flutter](https://pub.dev/packages/google_maps_flutter) is under active development, it still needs [quite a bit](https://github.com/flutter/flutter/labels/p%3A%20maps) of work.  Also, as Flutter grows to support more platforms, each new platform will have to implement the plugin, leading to it's own fork of issues and instability.

## Proposal

A solution that uses **pure** Flutter/Dart from the Google Maps SDK team.  
This would allow for maps to run on any platform (Android, iOS, Web, Linux, etc) -- no platform views or specific code.
Also since it's completely integrated, things like "Widgets as Markers", or "Flare animations as polylines", should become a lot easier.

_Side note: The current plugin has accelerated the development and provided clear use cases for platform views. In much the same way, I feel a pure Flutter solution could be a real benefit to Flutter itself, and allow us to flex test the Flutter framework in ways we haven't before._

**Comment by stuartmorgan** [comment]
> from the Google Maps SDK team

Since this request isn't for the Flutter project, the Flutter issue tracker isn't the right place for it. See https://developers.google.com/maps/support/ for options for getting this request to the right people.

**Comment by pauldemarco** [comment]
The feature request is open here: https://issuetracker.google.com/issues/140415468

Everyone should feel free to star it and add their use case.
