### ISSUE TITLE
bug in polygon

### ISSUE THREAD

**Issue by Jou21** [flutter/flutter#39754]
in ```google_maps_flutter: 0.5.20 + 2``` I could draw my polygon as I moved the map with a fixed point in the center of the map ... 
I created a function and threw it into 
```
onCameraMove (object) {centerMapPosition = object.target; myFunction (centerMapPosition)} 
```
and this myFunction as I updated the centerMapPosition variable I drew the polygon line. Just upgrading to ```google_maps_flutter: 0.5.21``` I can't do this drawing anymore. Have you had a polygon change from one library to another?

**Comment by BondarenkoStas** [comment]
Possibly related to #39737
@Jou21 Please add more consistent code snippet to be sure to reproduce the issue correctly. Also please add you ```flutter doctor -v``` output.

**Comment by janmoppel** [comment]
Hello @Jou21 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
