### ISSUE TITLE
Date Picker widget shows each month starting on a Monday

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#3976]
Using the date picker widget in the Flutter Gallery, each month starts on a Monday, which is incorrect.

@HansMuller

**Comment by sethladd** [comment]
Is this something that could be localizable?

**Comment by tvolkert** [comment]
@sethladd no, the bug is that the Flutter date picker reports the 1st of each month as blindly falling on Monday (whereas May 1, 2016 was, for instance, a Sunday).

**Comment by abarth** [comment]
How did we never notice that?  :)
