### ISSUE TITLE
Specify custom keystore within `flutter build`

### ISSUE THREAD

**Issue by CiriousJoker** [flutter/flutter#39764]
## Use case

Building appbundles without wanting to store the keystore password somewhere.

## Proposal

In [this ](https://stackoverflow.com/questions/41632934/how-to-sign-flutters-apps) post on stackoverflow, he used this command:

`flutter build apk --release --keystore /Users/user/Desktop/Sign/my-key-release.keystore --keystore-password=p@$$w0rd --keystore-key-alias=name-alias`

However, this is not possible in the current version of flutter. It was added at some point with this commit:
[LINK](https://github.com/flutter/flutter/commit/b4591274c93db8e69cd8c56380df164a853c249c)

Could you please add this feature back in for the build commands?

**Comment by dcortesnet** [comment]
??????????????????????

**Comment by jonahwilliams** [comment]
This has not been supported since flutter started delegating apk building to gradle several years ago. The proper way to do this is via build.gradle configuration

**Comment by jonahwilliams** [comment]
See for example: https://stackoverflow.com/questions/18328730/how-to-create-a-release-signed-apk-file-using-gradle
