### ISSUE TITLE
[Flutter Web] Explanation about FontManifest.json

### ISSUE THREAD

**Issue by matanshukry** [flutter/flutter#39775]
When running the hello_world example of flutter web using chrome, one will encounter the errors regarding font manifest, including:
(1) an error, a failed network request (404) to `http://localhost:8080/assets/FontManifest.json 404`
(2) a warning, about a missing font manifest "Font manifest does not exist at `assets/FontManifest.json` – ignoring.".

I couldn't find a section about it in the official flutter site, although I did understood some of it from this site: https://www.didierboelens.com/2019/05/flutter-for-the-web/

## Resolution
Possible resolutions:
(1) Not sure if it's a good idea, but perhaps some bool parameter in the build configuration so that FontManifest.json will not even be attempted to load. For now it seems an app can be used without needing it, and as far as I know the only way of not showing a network error on the chrome console is by not requesting it to begin with.

(2) Give a link with more information, preferably from the official Flutter site.

**Comment by jonahwilliams** [comment]
I don't get either of those errors when running the flutter/flutter hello world. Can you please share how you are running these examples?

**Comment by matanshukry** [comment]
I just followed the Readme in flutter web github, specifically the part about "Getting Started", up until and including "Run the hello_world example": https://github.com/flutter/flutter_web#run-the-hello_world-example

How are you not getting the errors though? I even found the source file where it's from, and it make sense; Unless you provided the FonttManifest.json file ?

p.s.
Just to clarify, I'm seeing those errors in the web console, not in my console where I'm running `webdev serve`

**Comment by jonahwilliams** [comment]
Ahh that is the forked flutter web, I thought you were talking about the flutter/flutter example.

The plan is to upstream/merge the repositories (already under way) - the font manifest and all asset logic is handled by the flutter tool, just the same as with android or iOS applications

**Comment by matanshukry** [comment]
What do you mean by "the forked flutter web" ? I don't see any fork text on github, and I understood flutter web is maintained in a different repo until merged, which doesn't seem as done yet (even if it's under way).

"the font manifest and all asset logic is handled by the flutter tool"
Can you explain that too? is there some tool I was supposed to use?

**Comment by yjbanov** [comment]
By "unforked" we mean that you'd be using this: https://flutter.dev/docs/get-started/web

Specifically for fonts, these instructions should work: https://flutter.dev/docs/cookbook/design/fonts

Please, give it a shot, and feel free to reopen this issue if it's still there.
