### ISSUE TITLE
[webview_flutter] Multiple parent widget recreations

### ISSUE THREAD

**Issue by divan** [flutter/flutter#39770]
I've noticed in my logs that tons of widgets in widget tree are being re-created (not rebuilt, but re-created) when widget with webview is opened. When the page is being loaded, I see usually from 10 to 20 log entries from parent widget constructors.

Flutter Inspector doesn't show any extra widgets in a tree, so I cannot explain what's happening. I see this only with widgets that use webview_flutter plugin, so I believe it's an issue with plugin.

Minimal code to reproduce an issue:

## Steps to Reproduce

1. Create new flutter app
2. Add webview_plugin to pubspec.yaml (and update Info.plist, according to README)
3. Replace main.dart code with this:

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: ListPage(),
    );
  }
}

class BrowserPage extends StatelessWidget {
  final String url;
  BrowserPage({this.url}) {
    print('Create BrowserPage widget for $url');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(url),
        leading: IconButton(
          icon: Icon(
            Icons.arrow_back_ios,
          ),
          onPressed: () {
            Navigator.of(context).pop();
          },
        ),
      ),
      body: WebView(
        initialUrl: url,
      ),
    );
  }
}

class ListPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    List<String> urls = <String>['https://google.com', 'https://wikipedia.com'];
    return Scaffold(
      appBar: AppBar(),
      body: ListView.builder(
        itemCount: urls.length,
        itemBuilder: (context, idx) => ListTile(
          title: Text(urls[idx]),
          onTap: () {
            print('Navigate to ${urls[idx]}');
            Navigator.of(context).push(MaterialPageRoute(
                builder: (context) => BrowserPage(url: urls[idx])));
          },
        ),
      ),
    );
  }
}
```
## Logs

```
flutter: Navigate to https://google.com
flutter: Create BrowserPage widget for https://google.com
flutter: Create BrowserPage widget for https://google.com
flutter: Create BrowserPage widget for https://google.com
flutter: Create BrowserPage widget for https://google.com
flutter: Create BrowserPage widget for https://google.com
flutter: Create BrowserPage widget for https://google.com
flutter: Create BrowserPage widget for https://google.com
flutter: Create BrowserPage widget for https://google.com
flutter: Create BrowserPage widget for https://google.com
flutter: Create BrowserPage widget for https://google.com
flutter: Create BrowserPage widget for https://google.com
flutter: Create BrowserPage widget for https://google.com
flutter: Navigate to https://wikipedia.com
flutter: Create BrowserPage widget for https://wikipedia.com
flutter: Create BrowserPage widget for https://wikipedia.com
flutter: Create BrowserPage widget for https://wikipedia.com
flutter: Create BrowserPage widget for https://wikipedia.com
flutter: Create BrowserPage widget for https://wikipedia.com
flutter: Create BrowserPage widget for https://wikipedia.com
flutter: Create BrowserPage widget for https://wikipedia.com
flutter: Create BrowserPage widget for https://wikipedia.com
flutter: Create BrowserPage widget for https://wikipedia.com
flutter: Create BrowserPage widget for https://wikipedia.com
flutter: Create BrowserPage widget for https://wikipedia.com
flutter: Create BrowserPage widget for https://wikipedia.com
flutter: Create BrowserPage widget for https://wikipedia.com
flutter: Create BrowserPage widget for https://wikipedia.com
flutter: Create BrowserPage widget for https://wikipedia.com
```

```
$ flutter analyze
Analyzing test_routes...
No issues found! (ran in 2.9s)
```

<details>
  <summary>flutter doctor -v</summary>
<pre>
$ flutter doctor -v
[✓] Flutter (Channel beta, v1.8.3, on Mac OS X 10.14.5 18F132, locale en-ES)
    • Flutter version 1.8.3 at /Users/divan/flutter
    • Framework revision e4ebcdf6f4 (5 weeks ago), 2019-07-27 11:48:24 -0700
    • Engine revision 38ac5f30a7
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 0ca1582afd)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/divan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/divan/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/divan/Library/Android/sdk/ndk-bundle/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.3

[!] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.0

[✓] Connected device (1 available)
    • divan’s iPhone • ******** • ios • iOS 12.4

! Doctor found issues in 2 categories.
</pre>
</details>

Anyone have any glues what's happening here?
Thanks in advance.

**Comment by divan** [comment]
If I add stacktrace print to the BrowserPage constructor:
```dart
    print(StackTrace.current);
    print('Create BrowserPage widget for $url')
```
I get this:
<details>
<summary>Stacktrace</summary>
<pre>
flutter: #0      new BrowserPage (package:test_routes/main.dart:19:22)
#1      ListPage.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_routes/main.dart:57:39)
#2      MaterialPageRoute.buildPage (package:flutter/src/material/page.dart:87:27)
#3      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:666:43)
#4      Builder.build (package:flutter/src/widgets/basic.dart:6445:41)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4001:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3933:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
#8      StatelessElement.update (package:flutter/src/widgets/framework.dart:4008:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#14     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4844:32)
#15     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5235:17)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
#19     StatefulElement.update (package:flutter/src/widgets/framework.dart:4112:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
#25     StatefulElement.update (package:flutter/src/widgets/framework.dart:4112:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
#31     StatefulElement.update (package:flutter/src/widgets/framework.dart:4112:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
#37     StatefulElement.update (package:flutter/src/widgets/framework.dart:4112:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
#41     StatelessElement.update (package:flutter/src/widgets/framework.dart:4008:5)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
#44     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
#45     StatefulElement.update (package:flutter/src/widgets/framework.dart:4112:5)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
#51     ProxyElement.update (package:flutter/src/widgets/framework.dart:4246:5)
#52     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#54     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
#58     StatefulElement.update (package:flutter/src/widgets/framework.dart:4112:5)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
#62     StatelessElement.update (package:flutter/src/widgets/framework.dart:4008:5)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
#67     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
#68     ProxyElement.update (package:flutter/src/widgets/framework.dart:4246:5)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
#72     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
#73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:20)
#74     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
#75     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
#76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
#77     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
#78     _rootRun (dart:async/zone.dart:1124:13)
#79     _CustomZone.run (dart:async/zone.dart:1021:19)
#80     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#81     _invoke (dart:ui/hooks.dart:236:10)
#82     _drawFrame (dart:ui/hooks.dart:194:3)
flutter: Create BrowserPage widget for https://google.com
</pre>
</details>

**Comment by divan** [comment]
@ezmegy I don't think I tried this on emulator – observed only on real device.
But let me check again with latest versions.

**Comment by divan** [comment]
Ok, I can confirm that I see this also on emulator:

<img width="1167" alt="Screenshot 2019-10-20 at 14 08 12" src="https://user-images.githubusercontent.com/880202/67159327-2e7fda00-f343-11e9-8273-7bc503c7915c.png">

<details>
<summary>My current flutter doctor output:</summary>
<pre>
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A602, locale en-ES)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio (version 3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
</pre>
</details>

webview_flutter version is ^0.3.15+1

**Comment by TahaTesser** [comment]
Hi @divan 

Running on 
```
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (3 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```

<details>
 <summary>Code Sample</summary>

```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: ListPage(),
    );
  }
}

class BrowserPage extends StatelessWidget {
  final String url;
  BrowserPage({this.url}) {
    print('Create BrowserPage widget for $url');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(url),
        leading: IconButton(
          icon: Icon(
            Icons.arrow_back_ios,
          ),
          onPressed: () {
            Navigator.of(context).pop();
          },
        ),
      ),
      body: WebView(
        initialUrl: url,
      ),
    );
  }
}

class ListPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    List<String> urls = <String>['https://google.com', 'https://wikipedia.com'];
    return Scaffold(
      appBar: AppBar(),
      body: ListView.builder(
        itemCount: urls.length,
        itemBuilder: (context, idx) => ListTile(
          title: Text(urls[idx]),
          onTap: () {
            print('Navigate to ${urls[idx]}');
            Navigator.of(context).push(MaterialPageRoute(
                builder: (context) => BrowserPage(url: urls[idx])));
          },
        ),
      ),
    );
  }
}

```

</details>

<details>
 <summary>Logs</summary>
```
I/flutter ( 9268): Navigate to https://google.com
I/flutter ( 9268): Create BrowserPage widget for https://google.com
W/System  ( 9268): A resource failed to call release.
W/System  ( 9268): A resource failed to call release.
D/EGL_emulation( 9268): eglMakeCurrent: 0xd621a0c0: ver 3 0 (tinfo 0xd620f810)
E/eglCodecCommon( 9268): glUtilsParamSize: unknow param 0x000088ef
E/eglCodecCommon( 9268): glUtilsParamSize: unknow param 0x000088ef
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 5 (5) 0 0
E/eglCodecCommon( 9268): glUtilsParamSize: unknow param 0x000088ef
E/eglCodecCommon( 9268): glUtilsParamSize: unknow param 0x000088ef
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 9 (9) 0 0
E/eglCodecCommon( 9268): glUtilsParamSize: unknow param 0x000088ef
E/eglCodecCommon( 9268): glUtilsParamSize: unknow param 0x000088ef
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 10 (10) 0 0
E/eglCodecCommon( 9268): glUtilsParamSize: unknow param 0x000088ef
I/chatty  ( 9268): uid=10134(com.example.stable_flutter) Chrome_InProcGp identical 2 lines
E/eglCodecCommon( 9268): glUtilsParamSize: unknow param 0x000088ef
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 9 (9) 0 0
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 0 (0) 1 2
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 5 (5) 1 34
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 0 (0) 1 2
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 5 (5) 1 34
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 0 (0) 1 2
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 5 (5) 1 34
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 0 (0) 1 2
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 5 (5) 1 34
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 0 (0) 1 2
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 5 (5) 1 34
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 0 (0) 1 2
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 5 (5) 1 34
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 0 (0) 1 2
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 5 (5) 1 34
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 0 (0) 1 2
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 5 (5) 1 34
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 0 (0) 1 2
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 5 (5) 1 34
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 0 (0) 1 2
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 5 (5) 1 34
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 0 (0) 1 2
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 5 (5) 1 34
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 0 (0) 1 2
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 5 (5) 1 34
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 0 (0) 1 2
D/eglCodecCommon( 9268): setVertexArrayObject: set vao to 5 (5) 1 34
```

</details>

It's only called once
`flutter: Create BrowserPage widget for https://google.com`

I wasn't able to reproduce the same issue 
if you're still experiencing this problem, please create a new issue and provide the information required in the template.

Thank you
