### ISSUE TITLE
Pick-up-and-move gesture for cards

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3978]
From https://www.google.com/design/spec/components/cards.html#cards-behavior

"The pick-up-and-move gesture may be used if it is important for the user to be able to sort cards within a collection. But consider if filtering or sorting would better organize the content."

**Comment by eseidelGoogle** [comment]
I can't think of an Android app which uses this, can you?

**Comment by abarth** [comment]
It might not be implemented in the Java framework.  There are lots of iOS apps that do similar things.

**Comment by pylaligand** [comment]
Google Keep has it.

**Comment by Hixie** [comment]
I don't really see what we'd have to do in the framework for this. Combining Card with the drag-and-drop widgets should be relatively straight-forward. Closing; please re-open if you have a more specific API in mind.
