### ISSUE TITLE
ReorderableListView glitches on contained textfield when located on non main screen

### ISSUE THREAD

**Issue by gkillick** [flutter/flutter#39789]
I am working on a project with textfields that are members of a reorderable list. The bug occurs when the list is accessed from a Navigator push to a new screen containing a ReorderableListView of textfields. The text fields within the ReorderableListView on the new screen glitch when focused, causing the keyboard to pop up then quickly disappear. The same list on the main screen works as expected, this bug only occurs after the Navigator push. The code is identical for both lists, does anyone know what may be causing this bug? I created a sample main.dart to demonstrate the effect:
 [https://github.com/gkillick/sortable_list_bug/blob/master/lib/main.dart](https://github.com/gkillick/sortable_list_bug/blob/master/lib/main.dart)

**Comment by TahaTesser** [comment]
Hi @gkillick 

Tested your code sample,  i wasn't able reproduce issue with  "keyboard to pop up then quickly disappear"

flutter doctor -v
```
[✓] Flutter (Channel dev, v1.16.4-pre.50, on Mac OS X 10.15.4 19E266, locale
    en-GB)
    • Flutter version 1.16.4-pre.50 at /Users/taha/Code/flutter_dev
    • Framework revision d14a301e41 (3 days ago), 2020-03-31 19:14:22 -0400
    • Engine revision 8166a91bca
    • Dart version 2.8.0 (build 2.8.0-dev.19.0 fae35fca47)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

 
[✓] Connected device (4 available)            
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E266
    • Chrome     • chrome           • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server • web-server       • web-javascript • Flutter Tools

• No issues found!
```

Are you still experiencing this issue with latest version of Flutter?
If yes, can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem  Thank you

**Comment by TahaTesser** [comment]
Hi @gkillick 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
