### ISSUE TITLE
Can you add a scrollDirection property to SilverList that changes its scrolling direction like ListIView?

### ISSUE THREAD

**Issue by 2534290808** [flutter/flutter#39795]
Can you add a scrollDirection property to SilverList that changes its scrolling direction like ListIView?
I want to use horizontal scrolling on the CustomScrollView

**Comment by goderbauer** [comment]
You can specify the `scrollDirection` you want in the constructor for the CustomScrollView: https://master-api.flutter.dev/flutter/widgets/CustomScrollView/CustomScrollView.html. You probably want `Axis.horizontal`.

**Comment by 2534290808** [comment]
You misunderstand me, What I mean is that there are two sliverlists in the CustomScrollView, and I only change the scroll direction of one SliverList, not the whole CustomScrollView 😄 😄 😄

**Comment by goderbauer** [comment]
You'd have to add another nested (horizontal) CustomScrollView within your existing (vertical) CustomScrollView to achieve that.
