### ISSUE TITLE
Google Signin  release Error

### ISSUE THREAD

**Issue by htetwaiyan** [flutter/flutter#39794]
PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null) error

**Comment by sarimk80** [comment]
Error 10  Is a Developer Error:
https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes#DEVELOPER_ERROR

maybe you SHA1 is incorrect.

also check out the link below:
https://github.com/googlesamples/google-services/issues/360

**Comment by BondarenkoStas** [comment]
@htetwaiyan Please provide your ```flutter doctor -v``` output. Also specify which version of google_sign_in you use.
Please also check #33393 and #27599 as it may be helpful.

**Comment by janmoppel** [comment]
Hello @htetwaiyan !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
