### ISSUE TITLE
vs code debugging not working after package name change in flutter.

### ISSUE THREAD

**Issue by Zeeshan0201** [flutter/flutter#39796]
## Logs

```
```

```
```
![Screenshot from 2019-09-04 11-22-47](https://user-images.githubusercontent.com/45591301/64229054-57205180-cf06-11e9-8cf6-a5f96498e8db.png)

**Comment by BondarenkoStas** [comment]
@Zeeshan0201 Please provide your ```flutter doctor -v``` output.
And if possible a code snippet to make sure to reproduce the issue.

**Comment by Zeeshan0201** [comment]
just solved by deleting .vscode file in the visual studio after changing the package name.
