### ISSUE TITLE
Two adjacent cards at the same level will overlap shadows

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#398]
If you have two cards at a high level next to each other, the later one's shadows will overlap the earlier one, rather than all the shadows being under all the cards.

**Comment by Hixie** [comment]
Realistically, for a real fix, this depends on https://github.com/flutter/flutter/issues/5467.
A work-around could come in the form of something like https://github.com/flutter/flutter/issues/5089.

**Comment by Hixie** [comment]
Dupe of #5467.

**Comment by illia-romanenko** [comment]
Hi @Hixie, we still can see this one in the recent versions of Flutter. Any suggestions?

**Comment by Hixie** [comment]
If your cards are so close together that the shadows overlap, and you can't make them have more separation, then you probably have to do what we do in MergeableMaterial and implement the shadows as a separate pass.
