### ISSUE TITLE
iOS13  TextField  inputText set Chinese crash

### ISSUE THREAD

**Issue by Tianao1992** [flutter/flutter#39800]

**Comment by BondarenkoStas** [comment]
@Tianao1992 Please edit your report to add there your ```flutter doctor -v``` output, logs, minimal code snippet to reproduce the issue etc. Right now there is not enough information to investigate it.

**Comment by janmoppel** [comment]
Hello @Tianao1992 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
