### ISSUE TITLE
onTap for Dismissible, or seperate actions for left and right swipe

### ISSUE THREAD

**Issue by AnuragVadd** [flutter/flutter#39816]
I am working on a To do list app and i displayed the tasks added by the user in a ListView.builder. i essentially want to use Dismissble to delete and mark a task as done by adding a LineStrike. I am using a database to use store, display and delete funtionalities. 
I had two approaches in mind : 
Approach 1: use onDismissed to delete and use an onTap to mark as complete.
Approach 2: use the left to right swipe to mark the task as complete and right to left to delete the task. The below gif is an idea of how approach 2 would look like but instead of displaying an icon, it would simply delete or mark the task as complete by swiping left or right 

Either of the suggested features would be of great help .
(credits to https://github.com/letsar/flutter_slidable for the gif).
![slidable_overview](https://user-images.githubusercontent.com/38868279/64250651-4edf0b00-cf34-11e9-8325-9b3938ba60df.gif)

**Comment by BondarenkoStas** [comment]
@AnuragVadd This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
