### ISSUE TITLE
[Android 10] New transition when opening new activities

### ISSUE THREAD

**Issue by charafau** [flutter/flutter#39812]
Got upgrade to android 10 this morning - seems like new activities open with `zoom` + `transparency` animation but on api < 28 they open with `slide` + `transparency` 

Flutter could detect android version and run different animation for android 10

**Comment by shihaohong** [comment]
**New zoom/transparency transition**:
![](https://i2.wp.com/9to5google.com/wp-content/uploads/sites/4/2019/06/android_q_beta_4_transition_1.gif?zoom=1.5&w=496&h=1021&quality=82&strip=all&ssl=1)

**Previous slide/transparency transition**:
![](https://i2.wp.com/9to5google.com/wp-content/uploads/sites/4/2019/06/android_q_beta_3_transition_1.gif?zoom=1.5&w=496&h=1021&quality=82&strip=all&ssl=1)

**Comment by vanlooverenkoen** [comment]
The current transition does not animate the previous screen as well. 
On android 10 the current screen and new screen both animate. In flutter only the new screen animates.

Is it possible to reopen this ticket?
