### ISSUE TITLE
StreamBuilder returning data even page is not loading

### ISSUE THREAD

**Issue by viratshukla** [flutter/flutter#39824]
Hi, 
I am using bloc (PublishSubject) to fetch data from internet. In one API, I am not getting the result due to expected reason hence displaying bottom sheet to display that error.
Now I navigate to some other screen, but since back screen is also rebuilt, it is causing bottom sheet of first screen to popup again.

Note - I am calling API only in initState(). Just listening for the stream.

Is there anyway, I can stop rebuilding widget of previous screen or stop listening to stream of previous screen.

**Comment by VladyslavBondarenko** [comment]
Hi @viratshukla 
Take a look at https://github.com/felangel/bloc/issues/201
Thank you
