### ISSUE TITLE
[Flutter web] Cursor text field don't move correctly 

### ISSUE THREAD

**Issue by mahmoudsalah37** [flutter/flutter#39826]
I have a problem when I try to type or modify the cursor text in the wrong place
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31797198/64267932-19163400-ceec-11e9-9e5d-a2d3a26dc34d.gif)
![Capture](https://user-images.githubusercontent.com/31797198/64472603-c61fc500-d115-11e9-871f-2b8064e40ea4.PNG)

**Comment by BondarenkoStas** [comment]
@mahmoudsalah37 Please provide your ```flutter doctor -v``` output, as well as some code snippet to be sure to reproduce the issue.

**Comment by mahmoudsalah37** [comment]
> @mahmoudsalah37 Please provide your `flutter doctor -v` output, as well as some code snippet to be sure to reproduce the issue.

[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.950], locale
    en-US)
    • Flutter version 1.7.8+hotfix.4 at C:\flutter\flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\flutter\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\flutter\sdk
    • Java binary at: C:\flutter\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Android Studio (version 3.5)
    • Android Studio at C:\flutter\android-studio
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)

[√] VS Code (version 1.38.0)
    • VS Code at C:\Users\Mahmoud salah eldin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by BondarenkoStas** [comment]
@mahmoudsalah37 Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by mahmoudsalah37** [comment]
> @mahmoudsalah37 Please provide a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

import 'package:flutter_web/material.dart';
import 'package:iso/styles/all/all.dart';

class PolicyPage extends StatefulWidget {
  _PolicyPageState createState() => _PolicyPageState();
}

class _PolicyPageState extends State<PolicyPage> {
  String _textPolicy;
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          Container(
            color: colorContext,
            height: 40.0,
            child: Center(
                child: Text(
              'Policy',
              style: tsMainText,
            )),
          ),
          Expanded(
            child: SingleChildScrollView(
              child: Container(
                color: Colors.white,
                child: Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: TextField(
                    
                    style: TextStyle(color: Colors.black),
                    decoration: InputDecoration(
                      hintText: 'Policy statement',
                      hintStyle: TextStyle(
                        color: colorHintText,
                      ),
                    ),
                    maxLines: 30,
                    onChanged: (String textPolicy) {
                      this._textPolicy = textPolicy;
                      setState(() {});
                    },
                    textAlign: TextAlign.center,
                  ),
                ),
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: FlatButton(
              highlightColor: Colors.blueAccent[300],
              hoverColor: Colors.blueAccent[100],
              color: Colors.white,
              child: Text(
                'Save',
                style: TextStyle(color: Colors.blue),
              ),
              onPressed: () {
                setState(() {});
              },
            ),
          )
        ],
      ),
    );
  }
}

**Comment by nturgut** [comment]
Thanks for sharing the code. 

Looks like text editing is working. This issue is about text measurement on a multi-line text. Solution depends on issue: https://github.com/flutter/flutter/issues/33523

**Comment by mahmoudsalah37** [comment]
and it isn't work correctly with arabic language (rtl)

**Comment by maxzod** [comment]
any updates ?
