### ISSUE TITLE
Flutter on Android 10 (API level 29) issues

### ISSUE THREAD

**Issue by TutOsirisOm** [flutter/flutter#39827]
## Steps to Reproduce

1. Update physical device to the final version of Android 10.
2. Try to run app on device.

I've been able to successfully run my app on the same device (Pixel XL) on all the beta version of Android 10. Yesterday upon updating to the final update via OTA I was no longer able to compile. The same build on other devices not running Android 10 works perfectly.

## Logs

Captured in [this gist](https://gist.github.com/tvolkert/0d300cbf6e58fc07dcf924728128081e)

I'm 99% sure the analyze log issues aren't the source as the build works fine on other devices.
```
   info - The value of the field '_lastNameTextController' isn't used - lib\screens\auth\auth_screen.dart:37:31 - unused_field
   info - The method '_buildPriceTextField' isn't used - lib\screens\manager\widgets\tab_create.dart:210:10 - unused_element
   info - This function has a return type of 'Future<bool>', but doesn't end with a return statement - lib\screens\profile\profile_screen.dart:100:18 - missing_return
```

```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.295], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at C:\src\flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\adam\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.37.1)
    • VS Code at C:\Users\adam\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.0

[√] Connected device (1 available)
    • Pixel XL • HT6990207404 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by shihaohong** [comment]
Just to clarify -- is this only on a physical device, or also for emulators?

**Comment by TutOsirisOm** [comment]
@shihaohong This issue specifically is about just the physical device. I am able to transfer the built apk to the same device and it works.

**Comment by shihaohong** [comment]
I tried building on my Pixel 2 physical device and it builds successfully. Could you check Android Studio and see if your toolchain is upgraded to the latest and see if it still fails? Namely:
1) SDK version 29.0.2 instead of 29.0.1
2) build-tools 29.0.2 instead of 29.0.1
3) 
```
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Path/to/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Path/to/Android/Sdk
    • Java binary at: /Path/to/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
```

**Comment by tvolkert** [comment]
Thanks for the report!  FYI, I updated the issue to move the log output to a gist to make this more readable.  Can you include an `adb bugreport` after the crash as well?

**Comment by tvolkert** [comment]
The relevant bit from the log snippet is:

```
[   +3 ms] executing: C:\Users\adam\AppData\Local\Android\sdk\platform-tools\adb.exe -s HT6990207404 install -t -r D:\Karmka\App\karmka\build\app\outputs\apk\app.apk
[+3262 ms] Performing Streamed Install

                    adb: failed to install D:\Karmka\App\karmka\build\app\outputs\apk\app.apk:
[   +1 ms] Installing build\app\outputs\apk\app.apk... (completed in 3.3s)
[   +1 ms] Error: ADB exited with exit code 1
```

(which is why I want to see if anything was going on in the `adb logcat` at that time)

**Comment by charafau** [comment]
My apks work on Android 10 - pixel 3

**Comment by TutOsirisOm** [comment]
I was about to update with the errors but it actually compiled fine just now. Only difference between today and yesterday was restarting my phone. Perhaps a full restart was needed for something. I did also install some other device emulators. So with that said I'm closing this issue and if anyone else has this problem, try restarting... lol

**Comment by tvolkert** [comment]
Glad to hear it.  Thanks for taking the time to report the issue!

**Comment by zahoramouss** [comment]
i still have the same issue
