### ISSUE TITLE
Replace Proguard rules with @Keep annotations in the embedding 

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#39839]
Add the `@Keep` annotation to the methods that are called from C++, so they aren't removed.

This way, we don't need to keep proguard rules in synced with the engine dependencies.  

The rules we currently tell folks to set are:

```
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
```

@matthew-carroll could you help with this?

**Comment by xster** [comment]
You meant adding this to the default flutter created templates right?

**Comment by blasten** [comment]
the .java files in the embedding (old and new ones)

**Comment by matthew-carroll** [comment]
@xster and @blasten I'm not clear on those comments. The ticket mentions C methods, which I assume means JNI callbacks, but then @xster you mentioned project templates, and then @blasten you mentioned java files....can we clarify what the goal is here?

**Comment by matthew-carroll** [comment]
We spoke offline. @blasten is gonna apply the existing rules using the keep annotation, and add it to the at least `FlutterJNI`. Then he is going to see roughly what kind of binary size decrease we can gain by using more specific rules.
