### ISSUE TITLE
Map hot reload command to hot restart for flutter for web

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#39848]
At least until hot reload is implemented. 

This might also require us to register a hot reload service in either the flutter tool or dwds, depending on what intellij needs

**Comment by grouma** [comment]
See logic here:
https://github.com/dart-lang/webdev/blob/7cbe3ac3cc91c6fae53f59d01941fe72236db3db/dwds/lib/src/dwds_vm_client.dart#L41
