### ISSUE TITLE
TabPageSelector has non-localized string "Page N of M"

### ISSUE THREAD

**Issue by andywolff** [flutter/flutter#39840]
This label appears to be properly localized with localizations.tabLabel:
https://github.com/flutter/flutter/blob/af9f210443971a86484c4772f54003838e64b388/packages/flutter/lib/src/material/tabs.dart#L1067

But this label appears to be a plain string in English "Page x of x": https://github.com/flutter/flutter/blob/af9f210443971a86484c4772f54003838e64b388/packages/flutter/lib/src/material/tabs.dart#L1480

Is there some reason the latter doesn't need to be localized? Is this new since issue #13162 was fixed?

**Comment by TahaTesser** [comment]
This is still same
https://github.com/flutter/flutter/blob/bd6ccb606a11dacf7c72970a9d623e6b89668d70/packages/flutter/lib/src/material/tabs.dart#L1491

**Comment by fernandormoraes** [comment]
@TahaTesser My fix is already merged, can you take a look at this issue? I think it can be closed
