### ISSUE TITLE
SliverAppBar Actions layout bug. Does not match standard Appbar.

### ISSUE THREAD

**Issue by kenthinson** [flutter/flutter#39846]
Hello I believe I found a bug in SliverAppBar. If I add a action button to the bar it appears too close to the right side of the screen. It doesn't match the standard App bar layout. I have attached example images.

This is an example of standard AppBar. You can see it is well spaced from the right of the screen.
![IMG_0018](https://user-images.githubusercontent.com/2245494/64290813-703bf900-cf2c-11e9-95c9-ad993a3eadc3.jpg)

This is an example of SliverAppBar. You can see the icon is pushed up to the right of the screen more then the normal AppBar.
![IMG_0017](https://user-images.githubusercontent.com/2245494/64290893-93ff3f00-cf2c-11e9-8038-bef6b2b3f540.jpg)

**Comment by BondarenkoStas** [comment]
@kenthinson Please provide your ```flutter doctor -v``` output, as well as some code snippet to be sure to reproduce it correctly.

**Comment by kenthinson** [comment]
Closing. I accidentally assigned Icon() instead of IconButton(). After making that change it's working. Sorry for taking your time. Thanks for the replay.
