### ISSUE TITLE
Plugins: "Community" for 3rd party plugins

### ISSUE THREAD

**Issue by cpboyd** [flutter/flutter#39841]
## Use case

Based on discussion from https://github.com/roughike/flutter_facebook_login/issues/170

flutter_facebook_login hasn't kept up-to-date with the Facebook SDK and Apple is starting to notify developers because the older SDK is using deprecated APIs.

## Proposal

React Native handles this with the @react-native-community where the community as a whole can effectively help maintain important plugins.

Perhaps something similar would be nice for important Flutter plugins that Google may not specifically want to maintain, like Facebook logins.

**Comment by audkar** [comment]
Such initiative already exists for Flutter https://github.com/fluttercommunity/community

**Comment by cpboyd** [comment]
@audkar That's awesome.  I'm surprised I haven't run across that yet.

I guess I was just hoping that there might be a more explicit nod to it from Google, like how Facebook does with modules they remove from React Native core:
https://facebook.github.io/react-native/docs/segmentedcontrolios

pub.dev could potentially reference it or something.

**Comment by BondarenkoStas** [comment]
@cpboyd Thank you for your input, please create a new issue with the proposal to mention the community in documentation more explicitly.
