### ISSUE TITLE
"Connectivity" plugin libraries are using deprecated methods

### ISSUE THREAD

**Issue by kmusham** [flutter/flutter#39842]
```
Note: C:\Users\km\AppData\Local\Flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.4\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by LaurentiuSimionescu** [comment]
*********************************************************
WARNING: This version of connectivity will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

**Comment by antoninobajeli** [comment]
Same problem

**Comment by collinjackson** [comment]
If anyone wants to submit a PR suppressing this deprecation warning I would approve it.

**Comment by stuartmorgan** [comment]
Closing as `connectivity` is deprecated in favor of [`connectivity_plus`](https://pub.dev/packages/connectivity_plus).
