### ISSUE TITLE
technical_debt__cost consumer_dependencies_count regression

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#39850]
https://github.com/flutter/flutter/commit/6ff212b328d8940b400e0138bcfd05e82757b2e0 introduced 5 new dependencies. Should this be re-baselined?

**Comment by Piinks** [comment]
This is already being tracked in https://github.com/flutter/flutter/issues/39152
Per offline discussion with @goderbauer, we were going to leave it in.
I think we should re-baseline then?

**Comment by franciscojma86** [comment]
Oh sorry, didn't see it earlier. SGTM.

**Comment by franciscojma86** [comment]
Re-baselined.
