### ISSUE TITLE
Android 10 / Android Q Issues and Features

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#39858]
This is a continuation of https://github.com/flutter/flutter/issues/32748, since it's preferable to have the complete list of to-dos for Android Q as its own issue rather than as part of a comment thread.

These are the different tasks that need to be completed to help myself keep track of progress and what else needs to be done. This will also help if I missed anything:

- [x] **Expose insets.systemGestureInsets on MediaQuery.of(context).systemGestureInsets**
Done with https://github.com/flutter/flutter/pull/37416 - This allows developers to place draggable widgets outside of the system gesture insets 
- [ ] ~~**Expose setSystemGestureExclusionRects API**
This allows developers to change remove gestures from non-mandatory insets. After exposing the API to the framework, the next step would be to create a convenience widget that sends wraps itself in the exclusion rect.~~ See https://github.com/flutter/flutter/issues/54397
- [ ] ~~**Expose getSystemGestureExclusionRects API**
Conversely, it would be good to have a way to query what system gesture exclusion rects have been set.~~ See https://github.com/flutter/flutter/issues/54397
- [x] **Android 10 not building on a physical device** - see https://github.com/flutter/flutter/issues/39827 for more details
- [x] **New Android 10 activities transition** - see https://github.com/flutter/flutter/issues/39812 for more details

Edit: We don't plan to expose an API for mandatory system gesture insets, since they are a subset of the complete system gesture insets. Developers using system exclusion rects should follow a request to `setSystemGestureExclusionRects()` with `getSystemGestureExclusionRects()` and work with whatever exclusion rects the system granted, rather than assuming that the request was met.

**Comment by PieterAelse** [comment]
Isn't the `setSystemGestureExclusionRects` already done? 
https://github.com/flutter/engine/pull/11451

**Comment by shihaohong** [comment]
@PieterAelse not quite -- it still needs to be properly exposed on the framework.

**Comment by bernaferrari** [comment]
Well.. I just found out that BottomNavigationBar works weirdly on iOS: it has a hard-coded padding for the bottom bar. This won't work on Android since the gesture/transparent bar can be of any size. I suggest a refactor to solve both issues.

![image](https://user-images.githubusercontent.com/351125/64933724-cc502880-d81c-11e9-888a-49d0cf24bfe1.png)

**Comment by shihaohong** [comment]
Hi @bernaferrari, could you clarify what you're expecting and what you actually get for iOS? I took a quick look at the `BottonNavigationBar` implementation and I'm under the impression that it's not hardcoded and uses MediaQuery's padding to determine the required spacing. 

For Android, you could use `MediaQuery.systemGestureInsets` to create this padding yourself.

**Comment by shihaohong** [comment]
Actually, I just checked and unfortunately realized that `Window.systemGestureInsets` made it into the recent `stable`, whereas `MediaQuery.systemGestureInsets` did not since it was introduced in a later PR. 

You could either wait until the next stable release or [use `Window` directly](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/media_query.dart#L121) in the meantime

**Comment by bernaferrari** [comment]
@shihaohong well, I think you have said everything. And this made me realise it was actually two issues in one. Besides what you mentioned,
there is no way to disable `additionalBottomPadding`, which makes BottomNavigationBar unsuitable for places other than the absolute bottom of the screen. In my situation, as shown in the picture above, I am laying out Material Design Components (to help make theming easier), but BottomNavigationBar has an undesirable bottom padding when it is not at the bottom of the screen. But yeah, that's a lot lower priority than the missing `MediaQuery.systemGestureInsets`.

**Comment by Hixie** [comment]
We believe we've done the critical work, but there is still some work remaining.

**Comment by slightfoot** [comment]
@Hixie Since the Pixel 4 release we have been having an issue with our latest app and the need to call setSystemGestureExclusionRects is required.

[I see it's in the engine](https://github.com/flutter/engine/blob/14e41878ad7d237f83a01298fe47f9302cf858a1/shell/platform/android/io/flutter/embedding/engine/systemchannels/PlatformChannel.java#L136) but it has not yet been been exposed though SystemChrome in the framework yet. Is there a reason why?

**Comment by PieterAelse** [comment]
Any updates on this? 
Btw, I'm not sure if there are any changes, but Android 11 developer preview 1 is already out.

**Comment by shihaohong** [comment]
I'm planning on coming back to implement set/getSystemGestureExclusionRects soon now that some free time has opened up for me. 

I'll take a look into the slated changes for Android 11, but so far, it doesn't seem like there's any significant changes like Android 10's system gesture insets. I've created an issue titled `Android 11 Issues and Features` to collect these issues, so please put a comment down in https://github.com/flutter/flutter/issues/51365 if there's anything that catches anybody's eye!

**Comment by shihaohong** [comment]
After some discussion on the discord channel and an offline chat with @HansMuller, we've decided that it doesn't make sense to expose this via the framework and would be better for this to be a plugin because it is very specific to just one platform, and only Android 10+ versions of that one platform. I've closed the framework side PR and will likely revert the engine side ones

**Comment by PieterAelse** [comment]
Sounds valid indeed. 

Will that plugin be build by the Flutter team or is it some work for the community?

**Comment by shihaohong** [comment]
@PieterAelse I'll need to figure that out myself, I haven't worked on plugins with the Flutter team before so I'll need to check with someone who is more familiar. I'll post here when I have more info!

**Comment by shihaohong** [comment]
From the discussion so far, it sounds like it would be work for the community.

**Comment by shihaohong** [comment]
Since the core work for this has been complete, I'm going to close out this issue. I opened a separate issue (https://github.com/flutter/flutter/issues/54397) to track implementing the exclusion rects API so for those interested in the feature, please move the conversation there :) Thank you!
