### ISSUE TITLE
Textdirection RTL Not working !

### ISSUE THREAD

**Issue by ThamerRamzi** [flutter/flutter#39865]
Please fix this problem ! 
Textdirection RTL Not working 
```
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.16299.1087], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at C:\Program Files\flutter
    • Framework revision b712a172f9 (8 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0
```

**Comment by Rahiche** [comment]
Do you have any steps to reproduce the problem?

**Comment by janmoppel** [comment]
Hello @ThamerRamzi !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.

**Comment by sgsm74** [comment]
for using **TextDirection.rtl** remove this piece of code from your file:
`import 'package:intl/intl.dart';`

**Comment by sgsm74** [comment]
for using **TextDirection.rtl** remove this piece of code from your file:
`import 'package:intl/intl.dart';`
