### ISSUE TITLE
devicelab should verify that nothing was marked read-only before the test ends

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#39861]
We should not mark anything read-only, because it can cause all kinds of problems for end users. Devicelab should verify that we don't break that rule.

(e.g. today the lab was red all day because we marked something read-only.)

**Comment by godofredoc** [comment]
This will be obsolete after DeviceLab tests start running on LUCI. LUCI uses a temporary chroot to run tests and deletes everything after the task completes.

@digiter please close this bug when migration is complete.
