### ISSUE TITLE
(我需要二开video_player 需要获取加载速度如何获取)i custom build video_player i need get buffer speed how to get

### ISSUE THREAD

**Issue by 0-php** [flutter/flutter#39869]
我需要二开video_player 需要获取加载速度如何获取

i custom build video_player i need get buffter speed how to get

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but related to implementation.
Keeping it open as it may relate to the lack of documentation.
Can you please add more details, what exactly you mean by buffer speed?

**Comment by jerryzhoujw** [comment]
I guess  `buffer speed` means  display  `download speed`   like  `30kb/s`  when playing video.

**Comment by stuartmorgan** [comment]
Closing due to lack of clarification about what exactly is desired here. If you can clarify what specific functionality you are looking for, please let us know and we can re-open.
