### ISSUE TITLE
We should not mark files read-only

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#39862]
Apparently we sometimes mark files read-only. This seems like it will just cause confusion (it certainly confused us in the devicelab when we did it today). We should rely on READMEs instead to document that files should not be modified.

**Comment by jmagman** [comment]
See https://github.com/flutter/flutter/pull/8748.
@cbracken

**Comment by zanderso** [comment]
@jmagman can this be closed following https://github.com/flutter/flutter/pull/45189 ?

**Comment by jonahwilliams** [comment]
Marking this as fixed
