### ISSUE TITLE
devicelab should handle read-only files when deleting them

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#39860]
When devicelab deletes files, it should be able to handle deleting read-only files. For example, we should be able to remove `.cocoon/flutter` when it gets marked read-only.

**Comment by digiter** [comment]
How about delete `.cocoon/flutter` every time?

**Comment by godofredoc** [comment]
This will be obsolete after DeviceLab tests start running on LUCI. LUCI uses a temporary chroot to run tests and deletes everything after the task completes.

@digiter please close this bug when migration is complete.
