### ISSUE TITLE
Easy to use the wrong binaryMessenger handler set pattern on iOS

### ISSUE THREAD

**Issue by xster** [flutter/flutter#39870]
Somewhat related to https://github.com/flutter/flutter/issues/33099

Users might reasonably think that I better set up all my listeners before running the engine entrypoint so they might end up with a pattern like

```swift
let engine = FlutterEngine(name: "blah", project: nil)
engine.binaryMessenger.setMessageHandlerOnChannel("blah", binaryMessageHandler:...)
engine.run(withEntryPoint: nil)
```

But that may fail silently since the binaryMessenger is routing back through the engine which sends it to the IOSPlatformView which isn't created yet. 

https://github.com/flutter/engine/blob/fc64cadb1f4044d4376cd5a6b58af37173c7d639/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm#L546. 

We might want to turn the FML_DCHECK in front of it into something stricter or let the FlutterBinaryMessengerRelay just hold onto it while the engine is setting up. 

By contrast, this issue can't happen on Android since the DartExecutor and FlutterJNI are setup on the FlutterEngine's constructor.

**Comment by dnfield** [comment]
If we don't make this work, it should probably throw at runtime, or at least print some very obnoxious warning

**Comment by xster** [comment]
@gaaclarke would you like to take a look at this one too? It's somewhat the other side of the coin vs https://github.com/flutter/flutter/issues/38914

**Comment by gaaclarke** [comment]
If we go ahead with our plan for buffered channels, the requirement for having the the engine running before you send messages should be removed.

**Comment by xster** [comment]
This is about receiving. The receiving hook-up silently fails today if done before the engine runs. What we were talking about yesterday was that the channel buffer also solves the lifecycle issue (which is still a send issue). This is a separate receive issue.

**Comment by gaaclarke** [comment]
> This is about receiving. The receiving hook-up silently fails today if done before the engine runs. What we were talking about yesterday was that the channel buffer also solves the lifecycle issue (which is still a send issue). This is a separate receive issue.

I was referring to what I proposed in the design doc i sent out earlier today.  I addressed sending and receiving.  I'm not sure it would make sense to only implement one of them buffered.

**Comment by xster** [comment]
Channel buffers https://github.com/flutter/engine/pull/12167 solves this. Closing.
