### ISSUE TITLE
Unable to remove the outer margin of pdf which is created using html/css in flutter iOS-App.

### ISSUE THREAD

**Issue by jazzbpn** [flutter/flutter#39875]
[Elaborated question at stackoverflow](https://stackoverflow.com/questions/57725618/unable-to-remove-the-page-outer-margin-of-the-pdf-which-is-created-using-html-cs)

**Comment by BondarenkoStas** [comment]
@jazzbpn I saw your issues, hope the one on dart_pdf will be reopened and taken into account. 
It's seems to me that the issue is with with libraries which are out of flutter repository, so the team won't be able to help with it( 
Anyway keeping it open in case somebody wants/can deal with it.

**Comment by stuartmorgan** [comment]
Third-party package issues need to be reported to their authors, not the Flutter project.
