### ISSUE TITLE
Update FAQ re: interop

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3987]
Current answer: https://flutter.io/faq/#can-i-interop-with-my-mobile-platforms-default-programming-language

We might want to mention something about the message pipe and FlutterView, at least so developers know that we're working on options other than just Mojo.

**Comment by sethladd** [comment]
cc @abarth if you want to mention anything? I think we do want to provide a hint that we're working on other options.

**Comment by abarth** [comment]
Yeah, we should update that answer.  Do you want to write up a patch for it?

**Comment by sethladd** [comment]
Sure thing!
