### ISSUE TITLE
cannot update my List

### ISSUE THREAD

**Issue by kirobass** [flutter/flutter#39874]
## Steps to Reproduce

1. ... I have a list that is initialised globally.
2. ...The list gets populated when someone selects shopping items
3. ...They then select (within a popup window or a show modal dialog) additional supplements for that item. 

When updating the price as 

```mainMenuList[listCounter][ItemPrice] += supplementsList[supplementCounter]['supplementPrice']; ```

--> it should increment or add the price to the mainMenuList. But instead I get the error:
```
flutter: Unsupported operation: read-only
```

```
[✓] Flutter (Channel master, v1.9.8-pre.37, on Mac OS X 10.14.6 18G87, locale
    en-GB)
    • Flutter version 1.9.8-pre.37 at /Users/ebk/flutter
    • Framework revision e468296af3 (4 days ago), 2019-08-31 11:39:00 -0700
    • Engine revision 381307b5b7
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 36985859e4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/ebk/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPhone Xs • 734CC229-C350-4AA0-9A56-7DF3860B27A1 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!

```

**Comment by BondarenkoStas** [comment]
@kirobass Can you please provide a minimum code example to be sure to reproduce it correctly?

**Comment by janmoppel** [comment]
Hello @kirobass !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
