### ISSUE TITLE
Need to modify document 

### ISSUE THREAD

**Issue by Ydetective** [flutter/flutter#39887]
locatoin: [Hero page](https://flutter.dev/docs/development/ui/animations/hero-animations)
at  class **RadialExpansion**  ,  build function missing a "{"

**Comment by susonsapkota** [comment]
https://github.com/flutter/website/pull/2978 Fixed 😃

**Comment by susonsapkota** [comment]
Fixed #39887

**Comment by VladyslavBondarenko** [comment]
Given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
