### ISSUE TITLE
Uncomment out the global :ios platform in the Podfile to make all apps default to iOS 9.0.

### ISSUE THREAD

**Issue by 3rsin3rgul** [flutter/flutter#39886]
Hello,
Is it possible to fix the boilerplate podfile (Can you uncomment the platform).
Like this;
```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
```

**Comment by BondarenkoStas** [comment]
@3rsin3rgul Do you mean to have "this line" instead of "the next line"?

**Comment by 3rsin3rgul** [comment]
This is the default podfile :
```
# Using a CDN with CocoaPods 1.7.2 or later can save a lot of time on pod installation, but it's experimental rather than the default.
# source 'https://cdn.cocoapods.org/'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
```

But after the pub get pod wants the define the platform. I guess because of the firebase plugin im not sure. If you update the podfile boiler plate like this it will save lots of issues 👍 
```
# Using a CDN with CocoaPods 1.7.2 or later can save a lot of time on pod installation, but it's experimental rather than the default.
# source 'https://cdn.cocoapods.org/'

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
```

Thanks

**Comment by jmagman** [comment]
What problem exactly are you trying to solve?  Are you trying to get rid of the `The iOS deployment target is set to x, but the range of supported deployment target versions for this platform is 8.0 to 12.0.` warnings?

**Comment by 3rsin3rgul** [comment]
Hello,
You can make platform: ios, '8.0' also. The problem is for me whenever I create a new app none of the plugin can install because of the pod problem. I thought it might be a good solution to uncomment the boiler plate podfile. 

Thanks

**Comment by jmagman** [comment]
The minimum supported version of Flutter is currently iOS 8.  If we set the Podfile version to `platform :ios, '9.0'` then Flutter apps wouldn't be able to deploy to iOS 8 devices.

Feel free to keep manually editing the file though, based on the needs of the plugins you are using!
