### ISSUE TITLE
Process '\bin\flutter.bat'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by Dheerendra007** [flutter/flutter#39885]
I am trying to run build in android studio then i got below issue.
Process 'command 'D:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

**Comment by BondarenkoStas** [comment]
@Dheerendra007 Please provide your ```flutter doctor -v``` output if it's possible. Also full log would be helpful, and steps how to reproduce the issue.

**Comment by roshenLiang** [comment]
D:\MyData\ex_liangls>flutter doctor -v
[âˆš] Flutter (Channel dev, v1.10.6, on Microsoft Windows [Version 6.1.7601],
    locale zh-CN)
    â€¢ Flutter version 1.10.6 at
      D:\FlutterSDK\flutter_windows_v1.10.6-dev\flutter
    â€¢ Framework revision cc3ca9a916 (15 hours ago), 2019-09-25 10:57:58 -0400
    â€¢ Engine revision 63949eb0fd
    â€¢ Dart version 2.6.0 (build 2.6.0-dev.2.0 69b5681546)

[âˆš] Android toolchain - develop for Android devices (Android SDK version 28.0.
3)
    â€¢ Android SDK at D:/AndroidSDK
    â€¢ Android NDK location not configured (optional; useful for native profili
ng
      support)
    â€¢ Platform android-28, build-tools 28.0.3
    â€¢ ANDROID_HOME = D:/AndroidSDK
    â€¢ Java binary at: D:\AndroidStu\jre\bin\java
    â€¢ Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b03)
    â€¢ All Android licenses accepted.

[âˆš] Android Studio (version 3.5)
    â€¢ Android Studio at D:\AndroidStu
    â€¢ Flutter plugin version 39.0.3
    â€¢ Dart plugin version 191.8423
    â€¢ Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b03)

[âˆš] Connected device (1 available)
    â€¢ HUAWEI MLA AL10 â€¢ 127.0.0.1:62001 â€¢ android-x86 â€¢ Android 5.1.1 (A
PI 22)

â€¢ No issues found!


please help me~~!!

**Comment by BondarenkoStas** [comment]
@roshenLiang do you encounter the same error message? Can you please run it with -v to paste the log here, and full error message.

**Comment by roshenLiang** [comment]
> @roshenLiang do you encounter the same error message? Can you please run it with -v to paste the log here, and full error message.

please look here
[https://github.com/flutter/flutter/issues/41350](https://github.com/flutter/flutter/issues/41350)

**Comment by Dheerendra007** [comment]
Thanks

*Thanks and regards*
*Dheerendra Kapariya*
*Sr.Android Developer*

**Comment by dpedrinha** [comment]
@Dheerendra007 did you fix it? how?

**Comment by yaoguangdong** [comment]
delete your my_flutter directory，and recreate module：
flutter create -t module --org com.example my_flutter
by shis，my problem is solved. hope it will help you!

**Comment by rehamalraee** [comment]
@yaoguangdong  what do you mean by My_flutter  directory ? is it the same of flutter sdk folder?
