### ISSUE TITLE
macos was not recognized as a target platform

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#39881]
By developing a cross platform app with web and desktop I encounter this error:
`macos was not recognized as a target platform. Consider updating the list of TargetPlatforms to include this platform.`

I was able to avoid this by:

```
if(!Platform.isAndroid && !Platform.isIOS) platform.debugDefaultTargetPlatformOverride = TargetPlatform.fuchsia;
```

But that doesn't work on web platform, for the web I need: 
```
if(defaultTargetPlatform != TargetPlatform.android && defaultTargetPlatform != TargetPlatform.iOS) platform.debugDefaultTargetPlatformOverride = TargetPlatform.fuchsia;
```

Which is not working for desktop ^^ 

Would be nice to have a way to make it work for both 

Env:
```
[✓] Flutter (Channel master, v1.9.8-pre.81, on Mac OS X 10.14.6 18G87, locale fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.1)
[✓] Connected device (2 available)

```

**Comment by stuartmorgan** [comment]
You can use `kIsWeb` to avoid breaking the web with the desktop logic; see: https://github.com/csells/flutter_image_search/blob/master/lib/main.dart

The actual solution to this is #31366.
