### ISSUE TITLE
[local_auth]  How to change the dialog design of local auth plugin?

### ISSUE THREAD

**Issue by RenanDelfanti** [flutter/flutter#39894]
Current design: 
![Screenshot_1567688903](https://user-images.githubusercontent.com/8375899/64344852-a8434a80-cfc5-11e9-8376-2f28d702a8c2.png)

Change to this: 
![Screenshot_1567689269](https://user-images.githubusercontent.com/8375899/64345367-9ca45380-cfc6-11e9-9972-9026c35bf93b.png)

Is there any way to change this design?

**Comment by utopicnarwhal** [comment]
https://github.com/flutter/flutter/issues/35724#issuecomment-516294763
Just downgrade version.
Or you can change activity theme in AndroidManifest.xml to "@style/Theme.AppCompat.Light"

**Comment by RenanDelfanti** [comment]
Thanks @utopicnarwhal
