### ISSUE TITLE
errno = 121, address = accounts.google.com, port = 50852

### ISSUE THREAD

**Issue by may1112** [flutter/flutter#39892]
我在中国
想上传项目到pub上
Then click "Allow access".

Waiting for your authorization...
Authorization received, processing...
It looks like accounts.google.com is having some trouble.
Pub will wait for a while before trying to connect again.
OS Error: 信号灯超时时间已到
, errno = 121, address = accounts.google.com, port = 50852

help

**Comment by catalsdevelop** [comment]
下载 可以设置国内的pub镜像，参考这里
https://flutter.cn/community/china
发布 需要设置全局代理或者终端代理，参考这里
https://www.kikt.top/posts/flutter/package/publish-fail/

**Comment by puming** [comment]
> 我在中国
> 想上传项目到pub上
> Then click "Allow access".
> 
> Waiting for your authorization...
> Authorization received, processing...
> It looks like accounts.google.com is having some trouble.
> Pub will wait for a while before trying to connect again.
> OS Error: 信号灯超时时间已到
> , errno = 121, address = accounts.google.com, port = 50852
> 
> help

**Comment by VladyslavBondarenko** [comment]
https://github.com/flutter/flutter/issues/14110#issuecomment-357848969
