### ISSUE TITLE
Some cards lack shadows in horizontal "media_query" example

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#399]
Open `examples/widgets/media_query.dart` and rotate the device to landscape mode.
Notice how the first card on all but the first row has no shadows.

**Comment by Hixie** [comment]
Same is visible on the second button in the "navigation.dart" demo.

**Comment by afandria** [comment]
I'm seeing this too. The cards look much better in portrait mode than in landscape.

**Comment by Hixie** [comment]
dupe of https://github.com/flutter/flutter/issues/1576
