### ISSUE TITLE
Gallery dark theme should probably turn buttons dark gray

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3990]
Looks like the dark theme should have buttons with a dark gray color:

![materialdark](https://cloud.githubusercontent.com/assets/5479/15340093/8b56e05c-1c3c-11e6-9f49-77168326181a.png)

(More about the material theme: https://developer.android.com/training/material/theme.html)

https://www.google.com/design/spec/style/color.html#color-themes seems to indicate the top-level gray (which is probably the buttons?) is #424242.

In the gallery app today, with the dark theme, the buttons are purple:

![screenshot_20160517-135303 1](https://cloud.githubusercontent.com/assets/5479/15340110/9e64a864-1c3c-11e6-9df5-18daf8cb60ff.png)

**Comment by sethladd** [comment]
cc @Hixie who has looked at colors and themes before?

**Comment by abarth** [comment]
The first screenshot contains flat buttons.  The second contained a raised button.  See https://www.google.com/design/spec/components/buttons.html#buttons-raised-buttons

**Comment by abarth** [comment]
I believe our behavior is correct.  It possible we should change the date picker to be more like a form, which would use a flat button.

**Comment by sethladd** [comment]
Ah, thanks for the clarification. I see the show a blue example in the dark theme:

![components_buttons_main16](https://cloud.githubusercontent.com/assets/5479/15341807/d531a096-1c45-11e6-97b5-86425e5aba0a.png)
