### ISSUE TITLE
Symlinks in any path that `xcodebuild` treats as a resource cause `FBSOpenApplicationErrorDomain` errors

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#3991]
`pub` likes to create symlinks in weird spots. Specifically, they are of the form `.packages/`. If any of these symlinks appear in a directory that `xcodebuild` uses are a resources directory, an obscure error is thrown. This is not documented anywhere and the only way to get rid of these errors is to get rid of the symlinks.

Investigate why these symlinks appear and either get rid of them before run or warn the user that sadness lies ahead.

**Comment by sethladd** [comment]
Try `pub get --no-package-symlinks`

**Comment by eseidelGoogle** [comment]
FYI @devoncarew.  We used to see pub dump packages/ symlinks throughout the whole repo at times.  Now that we use `.packages` files instead that hasn't been a problem, but it does seem like something we could have the flutter tool check for on iOS as a safety precaution.  Coming from a clean checkout this shouldn't be an issue, but if you ever run `pub get` yourself you could get yourself in this trouble.

**Comment by chinmaygarde** [comment]
From what I saw on a users machine, there was a .packages symlink in all subdirectories. I had to `git clear -fdx` to get back to a consistent state.

**Comment by abarth** [comment]
We should use `--no-package-symlinks`.  I think the only only blocker is teaching `gen_snapshot` about `.packages` files.

**Comment by chinmaygarde** [comment]
I think our use of `--no-package-symlinks` is only part of the solution. I have have gone `pub get` crazy several times myself. This would have added the incorrect symlinks. We should also add some diagnostics to the tooling that checks for errant symlinks.

**Comment by eseidelGoogle** [comment]
We can run `find . -type l` from the ios `flutter build` code if necessary or we could recognize certain error codes like FBSOpenApplicationErrorDomain and return the user a more useful message.  Maybe there are better solutions still?

**Comment by devoncarew** [comment]
Yup, getting rid of the use of symilnks (the gen_snapshot) issue, is tracked here: https://github.com/dart-lang/sdk/issues/26362.

We should probably also do some work pre flutter build/run for ios, to strip pub symlinks in inconvenient locations, or catch the error from xcodebuild and provide a good error message to the user (about how they can recover from the problem).

**Comment by Hixie** [comment]
As far as I can tell this is resolved now. We wrap pub pretty tightly so people won't be running pub get all the time, and as far as I'm aware we don't create packages directories any more.
