### ISSUE TITLE
Validate that there is sufficient font fallback on macOS

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#39914]
See #30700 for context. Most of the issues that have been reported have been on Linux, but we should do more testing on macOS to ensure that we have sufficient fallback logic implemented on macOS (in particular for cases like emoji and other character-not-available-in-this-font cases).

**Comment by franciscojma86** [comment]
I've tested this thoroughly on Linux, and confirmed on Mac. The current fallback steps are

1. Look for a fallback family font specified by the host
