### ISSUE TITLE
Cocoon agent needs to handle INSTALL_FAILED_INSUFFICIENT_STORAGE

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#39925]
Otherwise we need to manually reset the phones

**Comment by jonahwilliams** [comment]
cc @digiter

**Comment by digiter** [comment]
How to handle INSTALL_FAILED_INSUFFICIENT_STORAGE other than reseting the phones?

**Comment by jonahwilliams** [comment]
https://stackoverflow.com/questions/4709137/solution-to-install-failed-insufficient-storage-error-on-android

**Comment by jonahwilliams** [comment]
At the very least, when failing with this error we should mark the agent as unhealthy and stop using that machine

**Comment by christopherfujino** [comment]
Yeah, we should do the accepted solution in that SO article. Also, we should add device available disk space to the agent health checks.

**Comment by christopherfujino** [comment]
Maybe the easiest fix for this would be to always `flutter install --uninstall_only` before installing the app in the devicelab.

**Comment by digiter** [comment]
The above command doesn't seem to work: 
```
flutter-devicelab-mac-19:macrobenchmarks flutter$ ../../../bin/flutter install --uninstall-only
app.apk not found on Moto G 4, skipping uninstall
```

**Comment by digiter** [comment]
Related issue: https://github.com/flutter/flutter/issues/65512

**Comment by jonahwilliams** [comment]
Going to take a look at automating this today

**Comment by jonahwilliams** [comment]
This is mostly resolved by added uninstall steps and by a ~30 run autoreboot
