### ISSUE TITLE
We should be proactively testing all features on upcoming OS versions

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#39920]
This came up as part of #38375.

Right now we're not methodically testing all of our features on upcoming OS versions. This can lead to features unexpectedly regressing like in the linked issue. In the above example Android 10 had a public beta that spanned several months but this issue was only really root caused after the public release.

I'm thinking of two main approaches to try and prevent this going forward, there may be more that I'm not thinking of.

- Deliberately run our automated test suite against beta OS versions. Manual one-offs with an attached device in the simplest case. I think this is the most feasible and "should" guarantee our features work. The main catch I can think of here is that, at least for Android, our most brittle OS-dependent code doesn't have automated tests. In those cases it tends to be so tightly coupled with the underlying operating system that we don't have the ability to write meaningful Flutter driver tests for it. Automated tests wouldn't have caught the linked issue, for example. We are attempting to improve the automated tests to cover cases like it though.
- Come up with a manual test plan and verify. This would probably be full time work for a QA team. But it would catch tricky OS-dependent edge cases that are out of scope from our automated tests, and just general behavior that the tests don't cover.

/cc @Hixie @dnfield @collinjackson

**Comment by mklim** [comment]
From an offline discussion, part of the problem here is that keeping track of upcoming operating system releases is non-trivial given how many OSes Flutter runs on and the cadence of how often updates tend to roll out. It adds up really quickly.

Maybe it's possible to shard the burden across multiple people for the different OSes? I as an individual can keep an eye out for upcoming Android releases and manually run the test suite when they're in beta.

**Comment by dnfield** [comment]
@reidbaker - I believe there's some other issue tracking this now?

We are, in any case, in a better state now - we test against more recent OS versions, and Reid has or is working on a process to make sure that gets kept up to date as new versions become available for testing.

I think we can close this. Feel free to re-open if it's not better tracked elsewhere.

**Comment by reidbaker** [comment]
Yes if someone comes across this bug in 2023 we are working on or have a test that will ensure flutter can target preview releases as a ci test. Additionally we have manual testing triggered for preview builds.
