### ISSUE TITLE
NotificationListener with child as ListView not emittting ScrollEndNotification DragDetails properly

### ISSUE THREAD

**Issue by nimishbansal** [flutter/flutter#39929]
When I add child to a NotificationListener as ListView and when I am scrolling the list view several notifications are captured.one of them being ScrollEndNotification which has DragEndDetails parameter named as (dragDetails)

Now what happens is dragDetails is not null only at the ends of the list view. If I scroll by flinging the list view and the final location is in middle of the list view then dragDetails of scrollEndNotification instance is null. 

What I think is it is happening due to

> If a drag ends with some residual velocity, a typical ScrollPhysics will start a ballistic scroll, which delays the ScrollEndNotification until the ballistic simulation completes, at which time dragDetails will be null.

[https://api.flutter.dev/flutter/widgets/ScrollEndNotification/dragDetails.html](url)

- Now if this dragDetails are None how can I find actual DragEndDetails?

- Is there any method already available, or I have to make it my own and how can I make it?.

### Steps to Reproduce:
```
class MyListView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(itemCount:500,itemBuilder: (context, index) {
      return Text(index.toString());
    });
  }
}

class TemporaryTest extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _TemporaryTestState();
  }
}

class _TemporaryTestState extends State<TemporaryTest> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return NotificationListener(
      child: MyListView(),
      onNotification: (notification) {
        if (notification.runtimeType == ScrollEndNotification) {
          print((notification as ScrollEndNotification).dragDetails); //prints mostly null, only prints instance of DragEndDetails when either we are overscrolling at start or end, not in middle
        }
        return true;
      },
    );
  }
}

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body:TemporaryTest(),
    );
  }
}

```

**Comment by BondarenkoStas** [comment]
@nimishbansal Please provide your ```flutter doctor -v``` output

**Comment by nimishbansal** [comment]
Here is my output for the command flutter doctor -v 

> [✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_IN)
>     • Flutter version 1.7.8+hotfix.4 at /home/nimish/flutterdev/flutter
>     • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
>     • Engine revision fee001c93f
>     • Dart version 2.4.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /home/nimish/Android/Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • ANDROID_HOME = /home/nimish/Android/Sdk
>     • Java binary at: /opt/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
>     • All Android licenses accepted.
> 
> [✓] Android Studio (version 3.4)
>     • Android Studio at /opt/android-studio
>     • Flutter plugin version 38.2.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
> 
> [✓] IntelliJ IDEA Community Edition (version 2017.3)
>     • IntelliJ at /home/nimish/Downloads/idea-IC-173.4301.25
>     • Flutter plugin version 29.0.1
>     • Dart plugin version 173.4700
> 
> [!] VS Code (version 1.33.1)
>     • VS Code at /usr/share/code
>     ✗ Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [✓] Connected device (1 available)
>     • Redmi 5A • c7c5c52c7cf5 • android-arm64 • Android 8.1.0 (API 27)
> 
> ! Doctor found issues in 1 category.
>

**Comment by nimishbansal** [comment]
Can I commit my workaround and create a pull request for this issue (with the new feature of ScrollDragLiftNotification( a new notification similar to ScrollEndNotification)?

**Comment by BondarenkoStas** [comment]
@nimishbansal Sure, it's more than welcomed to create PRs. Please reference this issue in your pull request, and follow the template.

**Comment by nimishbansal** [comment]
@BondarenkoStas  Do I have to ping someone or they will have a look at the PR themselves?

**Comment by goderbauer** [comment]
It is correct that we currently do not give you access to the velocity (via ScrollNotifications) at the point in time when the drag gesture ended. The question is: Why should we? What's your use case for needing this information?

**Comment by nimishbansal** [comment]
We do have ScrollStartNotification, ScrollUpdateNotification which provides the attribute DragStartDetails, DragUpdateDetails(respectively) perfectly (and it seems redundant to provide ScrollDragStart, ScrollDragUpdate since the former is already enough for that), but if there is an attribute in ScrollEndNotification then DragDetails makes sense only when the user is over scrolling because in rest of the cases that won't make any sense since that would be null.

What I actually tried was putting list view in GestureDetector but it will detect events only when list view has physics as NeverScrollablePhysics.

My simple use case could be that I would like to know with what velocity user is flinging the list view 
and I might have to change the styles of widgets on the basis of velocity etc.

I can't guarantee if it is a good use case,  but I just think [ScrollDragEndNotification] provides enough useful information. 
since if we use Listener that it can tell that pointer has moved up but it doesn't provide the velocity, and neither GestureDetector works with the child as ListView.
The images used in ExampleUsage in the pull request seems to give information that I think is quite useful. ( for e,g it tells how much scrolling is caused by the ballistic animation without user interaction something like that). That's all from My side :-)

**Comment by goderbauer** [comment]
I would suggest that we wait with adding such an API until we have an actual use case. The ScrollNotifications are already somewhat complicated and adding more just because it may seem useful at some point just adds more maintenance overhead without much benefit.

**Comment by dnfield** [comment]
@nimishbansal - there's a non-trivial cost to maintaining new API surface in the framework. I think I can vaguely see why someone would want to do what you're suggesting, but I'm not getting the sense that you actually have plans to use this right now.

My concern is that if we add this API surface that no one needs to use right now, we're not even sure we're solving an actual real world problem - and we're incurring additional maintenance cost and complexity in an already complex method.

If you have a clearer case for this, please feel free to update the issue.

**Comment by nimishbansal** [comment]
To be honest, I just have a  simple ListView inside a AnimatedContainer and I want simple scrolling if we are scrolling normally but in case,  I do fling down the list view I just want that AnimatedContainer height to be reduced to 1/3 of its initial full size and in case I fling up(list view), it(AnimatedContainer) reoccupies original full-screen height. And what I studied from dismissible widget there is a function 
_describeFlingGesture https://github.com/flutter/flutter/blob/a7c06e113b6b4655bbf404094be4455a1e411a8f/packages/flutter/lib/src/widgets/dismissible.dart#L375
that determines fling velocity from velocity attribute in  DragEndDetails.

So is there any other way I could achieve this.  One more doubt :-) Also if there is no other obvious good way to detect the fling gesture inside list view how can I use my workaround(as in PR) so that flutter repository remains intact(without altering the main community version of flutter). I think it is quite deeper buried, that will increase overhead if I do the complete inheritance stuff, and I tthink monkey patching is probably not an option in Dart :-(

**Comment by dnfield** [comment]
It sounds like what you'd want is something like a custom ScrollPhysics.  Have you looked into that at all?

**Comment by nimishbansal** [comment]
Yes, I already had a look at it but wasn't able to accomplish what I was trying until now. But today, I tried again and was able to achieve what I wanted. Thanks a lot :tada: :tada:

**Comment by goderbauer** [comment]
Awesome!
