### ISSUE TITLE
Upgrade the mac bots Xcode

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#39921]
devicelab bots are running on Xcode 10.0.1.  We should upgrade to 10.3.  

This is blocking building our example apps (particularly Gallery) with bitcode.

It'd be even nicer if we just automated this so that Xcode could be updated across all the devices.

/cc @digiter @godofredoc @keyonghan

**Comment by godofredoc** [comment]
@digiter and I were talking about this yesterday. We'll need a few NUCs and a Mac to start experimenting with salt configurations. Although we may not want to block the xcode updates until the automated solution is ready.

**Comment by dnfield** [comment]
From offline discussion: This will involve upgrading macOS since several of the bots are still on High Sierra (!)

**Comment by digiter** [comment]
Quote on the priority "is to unblock testing of the migration to bitcode on iOS, which would reduce binary size on iOS and various other optimizations and required Xcode 10.3 (I believe that's the required 10.x version). And we want to support Swift 5, so upgrade to at least Xcode 10.2.  Also Xcode 9.0 is 2 years old and Apple stops supporting Xcode pretty fast since the upgrade is free, and Xcode 11 just dropped"

**Comment by digiter** [comment]
Related #41577

**Comment by digiter** [comment]
Upgraded mac1, mac2, and mac4 to use Xcode 10.3.

**Comment by jmagman** [comment]
@digiter It looks like mac5 and mac6 are the only two on Xcode 10.1/High Sierra that have iOS devices plugged in.  Could we plugin in android devices to those instead?  mac2 <=> mac5 and mac6 <=> mac10, for example?

**Comment by liyuqian** [comment]
@jmagman has the swapping done yet? I'm going to reland some PRs once all iOS macs are at 10.3

**Comment by jmagman** [comment]
@digiter is doing this.  I believe he's waiting for some racks to get set up, but he can speak to that.

**Comment by digiter** [comment]
Instead of swapping, we will just upgrade the Xcode. That should be done within this week.

**Comment by digiter** [comment]
After getting and provisioning new hardware, all the mac machines are using Xcode 11.0 now.

**Comment by jmagman** [comment]
> After getting and provisioning new hardware, all the mac machines are using Xcode 11.0 now.

Thank you so much, @digiter!
🎉🎉🎉
