### ISSUE TITLE
Add a headless mode to the embedding API

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#39935]
Currently if you run a headless engine on desktop (e.g., using the ObjC FlutterEngine API, which explicitly is intended for that purpose) the embedder layer logs errors:
```
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(107)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
```
```
[ERROR:flutter/shell/gpu/gpu_surface_gl.cc(42)] Could not make the context current to setup the gr context.
```

We shouldn't be logging errors for the expected case in a mode that the higher-level APIs support.

**Comment by stuartmorgan** [comment]
@chinmaygarde Should we make headless mode a `FlutterRendererConfig` option?

**Comment by chinmaygarde** [comment]
Sounds reasonable.

**Comment by jonahwilliams** [comment]
headless mode could be implemented today by using the software backend and discarding the buffer.
