### ISSUE TITLE
CupertinoTextField with placeholder fails to serialize diagnostics for dev tools

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#39937]
Repro steps:
1. Return a `CupertinoTextField` from your build method. Ensure `placeholder` is set.
2. Open dev tools
3. Attempt to view details about the text field
4. An exception is encountered, and details do not display

Did a little bit of investigation. Looks like `CupertinoTextField` is creating a `SizedBox` with `double.infinity` width ([`cupertino/text_field.dart:748`](https://github.com/flutter/flutter/blob/a24bfed0e7b65f4a927af2ddc8ff7440a2051e24/packages/flutter/lib/src/cupertino/text_field.dart#L748)). When the service layer attempts to serialize this value to send it to the devtools, it's found to be infinite, cannot serialize ([`dart:core/json.dart:658`](https://github.com/dart-lang/sdk/blob/770436d47781a3aa6c9113fdd6684e3d613bd133/sdk/lib/convert/json.dart#L656)), and throws an exception.

Introduced in #33739 
cc @HaijunWei, @LongCatIsLooong

**Comment by jacob314** [comment]
You can fix this issue by editing the following line to only allow finite numeric values.
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/diagnostics.dart#L2673

Interestingly JSON in JavaScript also fails to handle infinite and NaN values replacing them with null.
<img width="167" alt="Screen Shot 2019-09-09 at 9 16 58 AM" src="https://user-images.githubusercontent.com/1226812/64548207-06806e00-d2e3-11e9-9a3b-408ceb2d4633.png">

**Comment by shyndman** [comment]
Thank you :)
