### ISSUE TITLE
Use 12pt text when tab text wraps to two lines

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3993]
We should switch from 14 to 12 point for tab label text when the text needs to wrap to a second line.

See https://www.google.com/design/spec/components/tabs.html#tabs-content and https://www.google.com/design/spec/components/tabs.html#tabs-specs and specifically "12sp when wrapped across a maximum of two lines" for more info.

**Comment by Hixie** [comment]
What about when making it 12pt makes it only take one line?

**Comment by Hixie** [comment]
Looks like this is now just an option you're allowed to do, and not an especially recommended one either. Closing since you can already do this manually.
