### ISSUE TITLE
[Web] 界面显示错误

### ISSUE THREAD

**Issue by liuzhengcai** [flutter/flutter#39947]
在手机上浏览时，随机的会出现界面错误，好像是获取的浏览器窗口的宽度出错了。
（sometimes the width of main view is wrong on mobile）
正确的界面：(right )
[http://www.liuzhengcai.top/images/right.jpg](http://www.liuzhengcai.top/images/right.jpg)
错误的界面 (error)
[http://www.liuzhengcai.top/images/error.jpg](http://www.liuzhengcai.top/images/error.jpg)

**Comment by liuzhengcai** [comment]
Widget _buildtaskcar(String url,Size linesize,Color taskcolor,Size screensize,bool inleft,List<String> desclst,OnTAPFun func)
  {
      return Container(
        //width: double.infinity,
        width: screensize.width,
        height: linesize.height,
        child: _buildcard(taskcolor,screensize,inleft,desclst,func),
        decoration: BoxDecoration(
          image: DecorationImage(
            //image: AssetImage(url),
            image: NetworkImage('assets/'+url),
            fit: BoxFit.fill,
          )),
      );
  }

**Comment by liuzhengcai** [comment]
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.950], locale zh-CN)
    • Flutter version 1.7.8+hotfix.4 at D:\WebAPP\flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at D:\WebAPP\androidsdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = D:\WebAPP\androidsdk
    • Java binary at: D:\WebAPP\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\WebAPP\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at D:\WebAPP\IntelliJ\IntelliJ IDEA Community Edition 2019.1.3
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[!] Connected device
    ! No devices available

**Comment by blackredscarf** [comment]
Screen width is MediaQuery.of(context).size.width

**Comment by BondarenkoStas** [comment]
@luizdubas Please write in english, in this way it will be easier to understand the problem for those who don't know chinese, and will not scare away potential helpers.
Please also provide correct links to your images as current ones seems to be void.

**Comment by HansMuller** [comment]
Google translate's output:

```
When browsing on a mobile phone, an interface error will appear randomly, as if the width of the obtained browser window is wrong. 
(sometimes the width of main view is wrong on mobile) The 
correct interface: (right) 
http://www.liuzhengcai.top/images/right.jpg The
wrong interface (error) 
http://www.liuzhengcai.top/images/error.jpg
```

The image links appear to be correct.

**Comment by liuzhengcai** [comment]
(right  screen view)
[http://www.liuzhengcai.top/images/right.jpg](http://www.liuzhengcai.top/images/right.jpg)
(error   screen view)
[http://www.liuzhengcai.top/images/error.jpg](http://www.liuzhengcai.top/images/error.jpg)

@override
  Widget build(BuildContext context) {
    final screensize = MediaQuery.of(context).size;
    return Scaffold(
      backgroundColor: Colors.blue[300],
      body: createBody(screensize,context),
    );
  }

Widget _buildtaskcar(String url,Size linesize,Color taskcolor,Size screensize,bool inleft,List<String> desclst,OnTAPFun func)
  {
      return Container(
        //width: double.infinity,
        width: screensize.width,
        height: linesize.height,
        child: _buildcard(taskcolor,screensize,inleft,desclst,func),
        decoration: BoxDecoration(
          image: DecorationImage(
            //image: AssetImage(url),
            image: NetworkImage('assets/'+url),
            fit: BoxFit.fill,
          )),
      );
  }

**Comment by TahaTesser** [comment]
Hi @liuzhengcai 
Are you still experiencing this issue?
Thank you

**Comment by VladyslavBondarenko** [comment]
@liuzhengcai 
I hope you've solved it or it's fixed, closing for now,
comment please if it's not so and I will reopen it
Thank you
