### ISSUE TITLE
[web] Flutter create --web option is not documented

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#39958]
Per https://github.com/flutter/flutter/wiki/Building-a-web-application-with-Flutter, you can add the web runner to a Flutter project with `flutter create --web .`

However, this option is not documented in `flutter create --help`, even in the current master channel builds. 

We should fix this. Tagging @jonahwilliams.

**Comment by jonahwilliams** [comment]
I'll update the documentation. To align with the current behavior and avoid stepping on the multi-platform create plans I've updated `flutter create` to unconditionally add a web project if the flag is enabled.

**Comment by jonahwilliams** [comment]
Updated the wiki
