### ISSUE TITLE
Chips text baseline is a little low

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3995]
See https://www.google.com/design/spec/components/chips.html#chips-specs

See "Bananas" below. It appears that the word should be moved up just a few pixels.

![screenshot_20160517-145701](https://cloud.githubusercontent.com/assets/5479/15340934/e602a1fe-1c40-11e6-90ea-cd9ae6a29655.png)

Feedback from a review: "baseline of type looks a little low, makes the type seem vertically off centered"

**Comment by eseidelGoogle** [comment]
We also have a funny hairline in that clip of the black circle in blueberry.

**Comment by sethladd** [comment]
Good catch!

**Comment by gspencergoog** [comment]
I think this is fixed now with the rewrite of chips.
