### ISSUE TITLE
Gallery app could use a compelling demo/usage of chips

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3996]
The gallery (and our material widgets) have chips (https://www.google.com/design/spec/components/chips.html#chips-specs) but we don't have a good demo of them.

We could consider building a demo that shows "chips in action":
- [ ] dragging a chip for reordering
- [ ] adding multiple chips to a row
- [ ] editable chips

**Comment by gspencergoog** [comment]
Fixed with new Chip demo.
