### ISSUE TITLE
google_maps_flutter in stack with myLocationButton hidden issue iOS

### ISSUE THREAD

**Issue by cataCostea** [flutter/flutter#39965]
I have a map in a stack where you can add markers on the map on the onTap event. The button for removing the marker is in the right bottom corner in the myLocationButton area. If the myLocationEnabled and myLocationButtonEnabled are set to false, after tapping the button placed in the myLocationButton area, every gesture used on the map is onTap, placing the marker in the button area. The issue appeared only on iOS, on Android seems to work fine. google_maps_flutter 0.5.21. I tried downgrading the plugin to 0.5.7, but the problem is the same, with both flutter versions from stable channel and beta channel.

**Comment by BondarenkoStas** [comment]
@cataCostea Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.
Also please provide your ```flutter doctor -v``` output

**Comment by otopba** [comment]
I think it will help you
https://github.com/flutter/plugins/pull/1809
But still in review ...

**Comment by janmoppel** [comment]
Hello @cataCostea !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
