### ISSUE TITLE
[docs] Moving Flutterfire plugins to FirebaseExtended broke many links

### ISSUE THREAD

**Issue by lookfirst** [flutter/flutter#39975]
Pretty much every link on this page is broken:

https://firebaseopensource.com/projects/flutter/plugins/

Thanks to this commit...

https://github.com/flutter/plugins/commit/3ad2d1d300b0d901ea9739e3b9f08eeebda8be04

Where is the source code now? Just a big treasure hunt. =(

**Comment by superciccio** [comment]
https://github.com/FirebaseExtended/flutterfire/tree/master/packages

**Comment by lookfirst** [comment]
Beyond this, there is an infinite number of documentation resources, code links, issues, etc... all broken now. Couldn't have left directories with a README.md file in it?

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by kroikie** [comment]
@lookfirst

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/341. Any further collaboration will be done there.
