### ISSUE TITLE
Tiny hairline on left side of chip

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3998]
On the left of the B for Blueberry. Notice the thin arc of white.

![e602a1fe-1c40-11e6-90ea-cd9ae6a29655](https://cloud.githubusercontent.com/assets/5479/15341629/b3050c02-1c44-11e6-9b4d-52390ec05e09.png)

**Comment by gspencergoog** [comment]
This is fixed now: the Chip spec has a border around the avatar now, so it's no longer exactly the same size.  Not to mention that the chip demo has been completely rewritten.
