### ISSUE TITLE
Routes do not ignore pointers during Cupertino page transitions, breaking apps

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#39989]
## Steps to Reproduce

1. Open any Flutter app, like Flutter Gallery
   1.5. If on an Android device, change the platform to iOS
2. Navigate to a route, like the contacts demo
3. Initiate a backswipe, but don't release it
4. Hit the on screen back button (can be the one in the top bar, system back button also works on Android)
5. Complete the back swipe. Some Flutter versions cancel the back swipe, so just retry and complete the back swipe.

Both the Gallery and Contacts Demo routes disappear. The user is left with a black screen.

We can repro this with Flutter Gallery from Google Play, and with our internal app. Native iOS apps disable touches during a back swipe.

GIF: 

![gallery](https://user-images.githubusercontent.com/2268005/64446935-01c37c00-d08f-11e9-9423-31819e1cd1c5.gif)

**Comment by jkurtw** [comment]
b/140830897

**Comment by jkurtw** [comment]
I was able to repro this. You have to tap the back button with a second finger _while_ holding the backswipe mid gesture, then complete the backswipe.

**Comment by jkurtw** [comment]
(also, you need to turn off gesture based system navigation if you are running Android 10, since it grabs the backswipe gesture needed to repro this)
