### ISSUE TITLE
[web] [HtmlElementView] Set width and height on the registered HTML 

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#39982]
As discussed with @hterkelsen:
>.. when Flutter puts the `HtmlElementView` in the DOM, it puts it inside a container `<div>` sets width and height on the container. Would it fix your problem if we set width and height on the registered HTML element as well? That way you wouldn't need to worry about pre-sizing the `<video>`, Flutter would handle it for you.

**Comment by hterkelsen** [comment]
I definitely think this is the right thing to do. The registered view should just expect Flutter to size it correctly

**Comment by hterkelsen** [comment]
A PR is about to land for this: https://github.com/flutter/engine/pull/12227

**Comment by cbenhagen** [comment]
Nice! Will update my video_player PR accordingly as soon as decisions on the plugins repo structure have been made.

**Comment by hterkelsen** [comment]
The PR has landed
