### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by sushannnt** [flutter/flutter#39995]
#36353 
```
CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error: The remote computer refused the network connection.
, errno = 1225, address = clients2.google.com, port = 53316
\CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
Sending crash report to Google.                                                                                                                          |CreateProcessW failed 193                                                                                                                                Crash report written to C:\Users\sushant dhore\Desktop\longin\flutter_07.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by BondarenkoStas** [comment]
@sushannnt Can you please provide more information? Why did you reference the issue in the beginning?
It will be hard to investigate without crash report and steps to reproduce.
Please provide your ```flutter doctor -v``` as well.

**Comment by sushannnt** [comment]
@BondarenkoStas 
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.1006], locale en-IN)
    • Flutter version 1.7.8+hotfix.4 at c:\flutter
    • Framework revision 20e59316b8 (8 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

\CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
Sending crash report to Google.                                                                                        -CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error: The remote computer refused the network
connection.
, errno = 1225, address = clients2.google.com, port = 59690
\CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\sushant dhore\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:634:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:343:48)
#5      runSync (package:flutter_tools/src/base/process.dart:315:10)
#6      getAdbDevices (package:flutter_tools/src/android/android_device.dart:614:12)
#7      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:63:53)
<asynchronous suspension>
#8      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:223:52)
<asynchronous suspension>
#9      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:151:46)
<asynchronous suspension>
#10     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:743:54)
<asynchronous suspension>
#11     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:152:52)
#12     Doctor.diagnose (package:flutter_tools/src/doctor.dart:223:41)
#13     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:213:24)
#15     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:193:26)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
#17     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:7)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
#24     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:140:19)
#26     _doctorText (package:flutter_tools/runner.dart:192:19)
#27     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#28     _doctorText (package:flutter_tools/runner.dart:188:27)
#29     _createLocalCrashReport (package:flutter_tools/runner.dart:170:32)
#30     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#31     _createLocalCrashReport (package:flutter_tools/runner.dart:155:37)
#32     _handleToolError (package:flutter_tools/runner.dart:125:33)
#33     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#34     _rootRunUnary (dart:async/zone.dart:1132:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#39     Future._complete (dart:async/future_impl.dart:473:7)
#40     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#41     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#42     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#43     CrashReportSender.sendReport (package:flutter_tools/src/crash_reporting.dart)
#44     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:84:45)
#45     _rootRunBinary (dart:async/zone.dart:1144:38)
#46     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#47     _FutureListener.handleError (dart:async/future_impl.dart:140:20)
#48     Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#49     Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#50     Future._completeError (dart:async/future_impl.dart:491:5)
#51     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#52     _Completer.completeError (dart:async/future_impl.dart:27:5)
#53     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:40:18)
#54     IOClient.send (package:http/src/io_client.dart)
#55     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:84:45)
#56     _rootRunBinary (dart:async/zone.dart:1144:38)
#57     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#58     _FutureListener.handleError (dart:async/future_impl.dart:140:20)
#59     Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#60     Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#61     Future._completeError (dart:async/future_impl.dart:491:5)
#62     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:539:7)
#63     _rootRun (dart:async/zone.dart:1124:13)
#64     _CustomZone.run (dart:async/zone.dart:1021:19)
#65     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#66     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#68     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

**Comment by BondarenkoStas** [comment]
@sushannnt Can you please try it on ```master``` channel? It should already be fixed there.
https://github.com/google/process.dart/pull/38

**Comment by sushannnt** [comment]
@BondarenkoStas would you tell how to do it?

**Comment by BondarenkoStas** [comment]
@sushannnt In general just run ```flutter channel [<channel-name>]```, and then run ```flutter upgrade``` to ensure you're on the latest. It doesn't mean that you will be required to do you application on ```master```, but for the sake of checking if the issue is gone it worth to try. After some time it will go to the stable version, but not yet.
Also, you may try to move your Android SDK from ```C:\Users\sushant dhore\AppData\Local\``` to any other folder where path doesn't contain spaces (in you case the space in username), like ```C:\temp\``` or any. Be sure to setup your filepath to the new location.

**Comment by janmoppel** [comment]
Hello @sushannnt !

Did you manage to solve the issue?
