### ISSUE TITLE
Material Typography on Flutter Web

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#39994]
If you run the template app (output of `flutter create`) on Chrome, the fonts work correctly:

<img width="411" alt="Screen Shot 2019-09-05 at 3 01 05 PM" src="https://user-images.githubusercontent.com/1961493/64448186-f6258480-d091-11e9-89ad-c81717c87880.png">

On Safari, however, the fonts don't load and we end up with a default serif font:

<img width="430" alt="Screen Shot 2019-09-05 at 3 02 02 PM" src="https://user-images.githubusercontent.com/1961493/64448337-50264a00-d092-11e9-8a4f-f970526537e2.png">

On Flutter Web, since we default to `TargetPlatform.android`, the default Material Typography uses the Roboto font family. It seems that Roboto is bundled by default in Chrome, so it works when running on Chrome, but it's not available in Safari, so we end up defaulting to the serif font.

Several ideas have been discussed to fix this issue:

# 1. Require users to add Roboto to their assets

If Flutter Web users want to use Roboto, they should bundle it with their app by declaring it in their assets.

## Pros

* This will work today.
* All fonts that are used are declared in the assets.

## Cons

* Bundling Roboto in the assets will also cause it to be unnecessarily bundled in the Android and iOS apps. This could be solved by platform-specific assets: https://github.com/flutter/flutter/issues/8230
* Flutter mobile developers don't need to declare extra fonts to get Material working, it just works "by default", but on Flutter Web we would require extra setup to use Material.

# 2. Flutter Web Engine bundles Roboto if you use Material

If the developer has `uses-material-design: true` in their `pubspec.yaml`, we can pass that information to the generated entrypoint, causing the Flutter Web engine to download Roboto.

## Pros

* Developers can use Material by default.

## Cons

* Automatically downloading a font that hasn't been specifically requested could violate developer expectations.

# 3. Change Material Typography on Web to use a web safe font

In addition to the "Mountain View" and "Cupertino" typographies (the default for `TargetPlatform.android` and `TargetPlatform.iOS`, respectively), we create another typography for web, which uses a web safe font family (Arial?).

## Pros

* Developers don't need to add Roboto to their assets.

## Cons

* There may be no web safe font that looks good in Material Design.

# Discussion

We should decide on one of these options so we can move forward. What do you prefer @Hixie @ferhatb @yjbanov @jonahwilliams @mdebbar @nturgut

**Comment by mdebbar** [comment]
Another pro for the last option (using a web safe font) is that the app starts pumping frames sooner since it's not blocked on the Roboto font request anymore.

**Comment by ditman** [comment]
The Roboto font doesn't work out of the box on Chrome either, at least on my personal mac:

<img width="502" alt="Screen Shot 2019-09-06 at 10 08 28 AM" src="https://user-images.githubusercontent.com/1255594/64466129-0c990380-d0c5-11e9-9d9e-765a5c84fe33.png">

**Comment by hterkelsen** [comment]
Another consideration: on the CanvasKit/Skia backend, we can't even render system fonts (e.g. Arial), so option 3 won't work.

**Comment by JarrodCColburn** [comment]
IMO, #1 and #3 are deviations from expectations for Flutter devs.

While concern on #2 that "Automatically downloading a font that hasn't been specifically requested could violate developer expectations." ...I think devs will measure the deltas from Flutter, not from the web.

**Comment by Hixie** [comment]
we're hoping to get rid of `uses-material-design: true` in due course, so I'd rather not add more cases of that.

What do the Web Material Design Components do?

**Comment by HangingClowns** [comment]
I’m a bit surprised that iOS works, android works, but web doesn’t work when using Roboto font. As a dev who finds this as a third platform, I would expect that just to export to another platform, the font should be included from the framework. If I just need to add to the assets for it to be available then why does it work for the other two platforms?

**Comment by Hixie** [comment]
We don't use Roboto on iOS, we use San Francisco. We don't embed Roboto on any platform currently.

**Comment by HangingClowns** [comment]
> We don't use Roboto on iOS, we use San Francisco. We don't embed Roboto on any platform currently.

Oh! thanks for letting me know that! I didn't realize that they are so similar. I guess this shows I'm more of a developer than a designer :p

**Comment by hterkelsen** [comment]
In the CanvasKit backend we are bundling Roboto by default now
