### ISSUE TITLE
web CI tests are timing out

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#39991]
See https://cirrus-ci.com/task/5757648030400512

These should be either fixed on set to pass on timeout

**Comment by jonahwilliams** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
Is this a recent reoccurrence or has it been happening for a while? Do we get any analytics from Cirrus?

**Comment by jonahwilliams** [comment]
I noticed it just recently. No additional analytics that I'm aware. Might be possible that the machines were overloaded and web is just fairly expensive.

**Comment by yjbanov** [comment]
Fixed by https://github.com/flutter/flutter/pull/40630
