### ISSUE TITLE
[Plugins] Google Sign In - Consent Screen Keeps Loading

### ISSUE THREAD

**Issue by surr34** [flutter/flutter#40010]
I want to run the example provided with the [google_sign_in](https://pub.dev/packages/google_sign_in) package. Therefore I setup a project on firebase and the google developer console, enabled the People API, filled out the required information on the OAuth Consent Screen and finally updated the google-services.json. 

When I try to login I don't receive any exception, however the consent screen keeps on loading forever.
![image](https://user-images.githubusercontent.com/50893442/64466814-c6de3a00-d0c8-11e9-9263-2528b8d285af.png)

**Comment by ashutoshkmr** [comment]
Can you please provide debug log

**Comment by surr34** [comment]
Which one? There was none related to the call to `signIn`

**Comment by BondarenkoStas** [comment]
@surr34 Please provide your `flutter doctor -v` output.

**Comment by surr34** [comment]
After doing some more investigations it seems not to be related to flutter, I experience the same issues with a native android app.

**Comment by yahu1031** [comment]
@surr34 Can you please provide us the information how to solve it.

**Comment by hmarat** [comment]
> @surr34 Can you please provide us the information how to solve it.

Did you solve it?
