### ISSUE TITLE
Developing frontend with Flutter/AndroidStudio for backend done with Swift/ObjC/Xcode

### ISSUE THREAD

**Issue by kakyoism** [flutter/flutter#40025]
I'm new to Flutter app dev for mobile and would like to clarify the basic dev process.

Say if I already have a backend done with Swift/ObjC in Xcode, how should I interface the Xcode part with Flutter / Android Studio. I know about making Flutter talk to native code through platform channels. But that seems to require that the source code should be compiled with the Android Studio pipeline, right? 

In terms of dev process, it's unclear to me how to connect these two different pipelines. Or is it possible at all?

**Comment by BondarenkoStas** [comment]
Just to reference it here for other reviewers in case answer on SO will come faster. https://stackoverflow.com/questions/57832845/developing-frontend-with-flutter-androidstudio-for-backend-done-with-swift-objc

**Comment by escamoteur** [comment]
I close this because that's definitely out of this scope
