### ISSUE TITLE
cupertino cutbuttonlable display chinese with problem

### ISSUE THREAD

**Issue by virskor** [flutter/flutter#40027]
## Details
using default localization supporting, you will see Chinese is unable to display completely on cut button label.
![81E46793-6A5F-4451-AF0E-1D61C22706C1](https://user-images.githubusercontent.com/16968535/64474041-01b3a100-d1a1-11e9-83c5-17f70860eedc.png)
look at the label bottom carefully. you will find this problem.
``
## Logs
```
```

✓] Flutter (Channel dev, v1.10.0, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
    • Flutter version 1.10.0 at /Users/weizhang/flutter
    • Framework revision 3932ffb1cd (2 天前), 2019-09-04 23:13:16 -0400
    • Engine revision e7f9ef6aa0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 36985859e4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/weizhang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPhone Xʀ • 6B346D8A-52D3-4978-A61E-3E201D436D3C • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

```
```

**Comment by virskor** [comment]
The bottom character is not fully displayed and part of it is hidden.

**Comment by HansMuller** [comment]
CC @GaryQian

**Comment by virskor** [comment]
@GaryQian found this problem come with set font width factor(any ,like 1, 1.2 ....). even English locale.

**Comment by virskor** [comment]
![47CE7F48-6DCF-46F8-9399-7AE49049E979](https://user-images.githubusercontent.com/16968535/64917709-b19e9500-d7c5-11e9-80ba-ef3dbb23dee6.png)

**Comment by TahaTesser** [comment]
Hi @virskor 
Are you still experiencing this issue with latest `stable` channel?
Thank you

**Comment by virskor** [comment]
@TahaTesser Thanks for your great job, this problem already fixed on my device as i rebuild by using latest stable channel

**Comment by TahaTesser** [comment]
Hi @virskor 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
