### ISSUE TITLE
Issue from website page Flutter for iOS 开发者

### ISSUE THREAD

**Issue by maoweipengft** [flutter/flutter#40020]
From URL: https://www.flutterchina.club/flutter-for-ios.md
如何将生成objc的iOS项目呢？现在默认生成的都是swift的

**Comment by chunlea** [comment]
Using `flutter create --help`, and you'll find:

```
-i, --ios-language             [objc, swift (default)]
```

**Comment by jmagman** [comment]
Translation:
> From URL: https://www.flutterchina.club/flutter-for-ios.md
How to generate objc iOS project? Now the default is generated by swift

I don't even see docs in English for this.  Maybe a conscious choice to push people to Swift?

**Comment by kf6gpe** [comment]
I'm not sure what's actionable here, so I'm going to close this issue. If folks want to reopen with actionable feedback (using Google translate is fine!) we're happy to re-triage.
