### ISSUE TITLE
i can't add MarqueeWidget to Column or ListView

### ISSUE THREAD

**Issue by huaiguoguo** [flutter/flutter#40028]
## Steps to Reproduce

![image](https://user-images.githubusercontent.com/1888094/64474832-f9f9f980-d1ac-11e9-9dff-cd1989ab3751.png)

![image](https://user-images.githubusercontent.com/1888094/64474878-8a383e80-d1ad-11e9-8cb5-31caf47741ef.png)

![image](https://user-images.githubusercontent.com/1888094/64474879-93c1a680-d1ad-11e9-95a7-7f60c2347187.png)

**Comment by huaiguoguo** [comment]
i has two column text to marquee,  so   i   add  MarqueeWidget to ListView or Column , but it's not work

**Comment by lukepighetti** [comment]
I would post this on the marquee_widget GitHub issues or provide a minimum viable reproduction.

**Comment by BondarenkoStas** [comment]
@lukepighetti Please provide an example of code to reproduce the issue and your ```flutter doctor -v``` output.
Please do not include screenshots of code or logs. This makes it extremely tedious to reproduce the issue, as we would have to manually transcribe your example.

**Comment by lukepighetti** [comment]
@BondarenkoStas literally not my issue

**Comment by janmoppel** [comment]
Hello @huaiguoguo !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
