### ISSUE TITLE
image_picker video recording length

### ISSUE THREAD

**Issue by klaszlo8207** [flutter/flutter#40035]
Hello, is there any way to record only 10 seconds? Thanks

**Comment by sarimk80** [comment]
You can play 10 second video with this flutter library:
 https://pub.dev/packages/video_player
https://github.com/flutter/plugins/tree/master/packages/video_player

and do you want to record the video of your app screen and save it to phone ?

**Comment by klaszlo8207** [comment]
I want to record only 10 seconds.

**Comment by cyanglaz** [comment]
This feature is added in https://github.com/flutter/plugins/pull/2643 with image_picker 0.6.5. Closing the issue.
