### ISSUE TITLE
[web] Text Getting Cut Off

### ISSUE THREAD

**Issue by xeu100** [flutter/flutter#40037]
## Steps to Reproduce

1. Use Flutter Web
2. Use any font

This appears on mobile most of the time, usually with any font (tested with Nunito, Roboto, and Concert One) where the text is in paragraphs. No visual errors appear.

It's impossible to use sites on mobile because of this. Layouts work fine.

**Comment by jonahwilliams** [comment]
I can't reproduce this on 5a3a46ada2417957415c58a5a1adff0fc11f7fc5 using the unforked workflow. Please try https://github.com/flutter/flutter/wiki/Building-a-web-application-with-Flutter and let me know if you still experience the issue

**Comment by xeu100** [comment]
The project can't run in the unforked webflow. It's an issue with the fact the rendering system doesn't give each line enough space so either it overlaps or cuts off.

**Comment by xeu100** [comment]
https://imgur.com/a/bd2V9zT

**Comment by xeu100** [comment]
Any fixes that anyone is aware of?

**Comment by cbenhagen** [comment]
@xeu100 can you please provide a full non-working example?

**Comment by xeu100** [comment]
https://pastebin.com/sKQ2Fugd

**Comment by ykaito21** [comment]
@xeu100 any update? I am facing the similar issue with this. I am building flutter web app hosing on Firebase. I don't have physical Android device, I tried to open with simulator's chrome, but every bottom of text cut off. I am not sure this will also happen on physical device. There seems no problem with ios.  

<img width="374" alt="スクリーンショット 2019-12-19 19 18 13" src="https://user-images.githubusercontent.com/35805590/71165610-7f08aa80-2294-11ea-9625-16d8a23da142.png">

**Comment by ferhatb** [comment]
@xeu100 , @TahaTesser  Tried the pastebin sample above on latest master with Chrome and iPhone11, see screen shots below. Which device are you using? Anything i need to change on that sample to repro ?

![Screen Shot 2020-04-09 at 1 48 48 PM](https://user-images.githubusercontent.com/5061034/78939655-67cf1200-7a69-11ea-9584-8d98b375503d.png)

**Comment by sladecapasso** [comment]
![Gif of issue](https://user-images.githubusercontent.com/22378804/79917408-71a52d80-83f8-11ea-9433-c5ceecd04ecb.gif)

Also experiencing this across form factors when I type more than 5 characters in this text field I set up for usage with a Slider.

```
class SliderTextField extends StatefulWidget{
  SliderTextField({
    this.textStyle,
    this.inputDecoration,
    this.onChanged,
    this.textChangeTimeout = const Duration(seconds:2),
    this.value,
    this.validator,
    this.autovalidate = false,
  });

  final TextStyle textStyle;
  final InputDecoration inputDecoration;
  final ValueChanged<double> onChanged;
  final Duration textChangeTimeout;
  final String value;
  final FormFieldValidator<String> validator;
  final bool autovalidate;

  @override
  _SliderTextFieldState createState() => _SliderTextFieldState();
}

class _SliderTextFieldState extends State<SliderTextField> {
  final TextEditingController _controller = TextEditingController();
  final _focusNode = FocusNode();
  Timer _timer;

  initState() {
    super.initState();
    _focusNode.addListener(() {
      if(_focusNode.hasFocus) {
        _controller.selection = TextSelection(baseOffset: 0, extentOffset: _controller.text.length);
      }
    });
  }
  
  @override
  Widget build(BuildContext context) {
    _controller.text = double.parse(widget.value).round().toString();
    return GestureDetector(
      onTap: () {
        final FocusScopeNode currentFocus = FocusScope.of(context);
        if (!currentFocus.hasPrimaryFocus) {
          currentFocus.unfocus();
        }
      },
      child: SizedBox(
        width:  60,
        height: 80,
        child: TextFormField(
          focusNode: _focusNode,
          onChanged: (String value){
            if(_timer != null) {
              _timer.cancel();
            }
            _timer = Timer(widget.textChangeTimeout, () {
              widget.onChanged(double.parse(value));
            });
          },
          controller: _controller,
          textAlign: TextAlign.center,
          textAlignVertical: TextAlignVertical.center,
          keyboardType: TextInputType.numberWithOptions(),
          maxLines: 1,
          validator: widget.validator,
          autovalidate: widget.autovalidate,
          decoration: const InputDecoration(
            helperText: ' ',
            contentPadding: EdgeInsets.symmetric(vertical: 25.0, horizontal: 10.0),
            enabledBorder: OutlineInputBorder(
              borderSide: BorderSide(color: Colors.transparent),
              gapPadding: 0.0,
            ),
            focusedBorder: OutlineInputBorder(
              borderSide: BorderSide(color: Color(0xFF1967D2), width: 2),
            ),
            focusedErrorBorder: OutlineInputBorder(
              borderSide: BorderSide(color: Color(0xFFE53935), width: 2),
            ),
            filled: true,
            fillColor: const Color(0xFFEBEBEB),
          ),
          style: const TextStyle(
            fontSize: 16.0,
          ),
        )
      ),
    );
  }
}
```

**Comment by ferhatb** [comment]
@sladecapasso, can you please file a separate issue. This one is about rendering when using specific tall fonts.

**Comment by eriko13** [comment]
I have the same issue but for me, it gets cut off by the end of the String:


![Screen Shot 2020-10-05 at 7 32 56 PM](https://user-images.githubusercontent.com/36830415/95149003-09e26500-0742-11eb-9069-fd7cef0c4486.png)

steps to recreate: on the flutter dev channel, 
1.-  create a new app
2.- run web (chrome) 
3.- set screen size to 90% 

And you will see that the text gets cut off.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
