### ISSUE TITLE
Daily Repeating Notifications based on Calendar like native development

### ISSUE THREAD

**Issue by 4RSIM3R** [flutter/flutter#40030]
## Assalamualaikum
I have a problem when i want to creating a daily notification based on Calendar/Hour Of day like In native, and worse again i do not find any Plugin to help me here, because current plugin just supporting make notifications based on Duration not a calendar 

## My Hope
I Hope the flutter create a built in notifications and alarm service,

**Comment by jld3103** [comment]
You could implement it by lookin up the duration until that date.

**Comment by stuartmorgan** [comment]
Closing as `android_alarm_manager` is deprecated in favor of [`android_alarm_manager_plus`](https://pub.dev/packages/android_alarm_manager_plus).
