### ISSUE TITLE
 Cannot find runner for main.dart

### ISSUE THREAD

**Issue by shayanahmedkhan** [flutter/flutter#40040]
while I am running my application so it gives this error, I have upgraded my android studio after upgrading I face this problem please help me out.

**Comment by Akora-IngDKB** [comment]
Please provide a log of `flutter doctor -v` and your console.

**Comment by TheVinhLuong** [comment]
You have to reconfigure the FlutterSDK path in Android Studio: Go to Setting -> Language & Frameworks -> Flutter and set the path to Flutter SDK

**Comment by Akora-IngDKB** [comment]
@TheVinhLuong it's quite interesting my Android Studio 3.5 doesn't have Flutter and Dart under Languages and Frameworks settings

**Comment by TheVinhLuong** [comment]
@Akora-IngDKB IIRC we need to set path to those SDKs manually, just remember to do it every time you do a fresh AS installation.

**Comment by Akora-IngDKB** [comment]
How do I do that or any link to that please?

**Comment by TheVinhLuong** [comment]
Here is the [link](https://stackoverflow.com/questions/48650831/dart-sdk-is-not-configured), it is basically as I have said. You first need to locate the location of Flutter and Dart SDKs folder in your PC.
For example on my Window PC:
Flutter SDK:
`E:\Flutter\flutter_windows_v0.7.3-beta\flutter`
Dart SDK (it is resides in flutter sdk folder if you have run `flutter` command in command line once):
`E:\Flutter\flutter_windows_v0.7.3-beta\flutter\bin\cache\dart-sdk`
In case you don't know where FLutter SDK is then you should re-download it again and this time remember its location.

**Comment by Akora-IngDKB** [comment]
Sure👍

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by vinac-07** [comment]
> You have to reconfigure the FlutterSDK path in Android Studio: Go to Setting -> Language & Frameworks -> Flutter and set the path to Flutter SDK

thank you it works
