### ISSUE TITLE
iOS App Store Submission Rejection

### ISSUE THREAD

**Issue by BK1031** [flutter/flutter#40046]
I submitted a build to App Store Connect and got the following response (binary was rejected):
<img width="687" alt="Screen Shot 2019-09-07 at 6 46 11 PM" src="https://user-images.githubusercontent.com/33289435/64482102-c4024880-d19f-11e9-95cf-c2a7e8e443dc.png">

I only ran into this issue today. I was able to upload binaries perfectly fine before. I didn't add any new plugins today, just UI stuff. You can find the flutter project [here](https://github.com/equinox-initiative/vc-deca-flutter)

**Comment by jonahwilliams** [comment]
The error message indicates that you attempted to upload a debug binary to the app store. Ensure that your app is build in release mode `flutter build ios --release`.

**Comment by BK1031** [comment]
lmao I totally forgot I needed to do that. thank you!
