### ISSUE TITLE
How to delete a flutter plugin

### ISSUE THREAD

**Issue by XingXiaoWu** [flutter/flutter#40047]
I made a plug-in, but upload plugin name wrong, then I changed the plug-in name to upload, the results of flutter plug-in warehouse have two same function but is not the same as the name of the plug-in, I feel very bad, I want to delete the plugin, I write the wrong name, I'm sure no one use it, what should I delete?

In https://dart.dev/tools/pub/publishing#publishing-is-forever I noticed the document said

```
Publishing is forever
Keep in mind that publishing is forever. As soon as you publish your package, users will be able to depend on it. Once they start doing that, removing the package would break theirs. To avoid that, pub strongly discourages deleting packages. You can always upload new versions of your package, but old ones will continue to be available for users that aren’t ready to upgrade yet.
```
I think that means you can delete it, but how to do?

**Comment by stuartmorgan** [comment]
The Pub server has [its own issue tracker](https://github.com/dart-lang/pub-dev/issues); this is out of the scope of the Flutter project.

**Comment by XingXiaoWu** [comment]
Sorry. It's my fault
