### ISSUE TITLE
Flutter Web Changing Sizes Resets State

### ISSUE THREAD

**Issue by xeu100** [flutter/flutter#40044]
## Steps to Reproduce

1. Create a flutter web project with states
2. Set a variable to a retrieved value
3. Change screenview using preview tools

## Logs

```
N/A
```

```
Analyzing [REMOVED]...

   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: AboutCard._title, AboutCard._content, AboutCard._date - lib\elements\AboutCard.dart:4:7 - must_be_immutable
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: Member._name, Member._position, Member._description, Member._image_url - lib\elements\Member.dart:4:7 -
          must_be_immutable
   info - Unused import: 'package:flutter_web_ui/ui.dart' - lib\pages\portal\DashboardPage.dart:6:8 - unused_import
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: DashboardPage._username - lib\pages\portal\DashboardPage.dart:9:7 - must_be_immutable

4 issues found. (ran in 7.8s)

```

```
[√] Flutter (Channel master, v1.10.1-pre.39, on Microsoft Windows [Version 10.0.18362.295], locale en-US)
    • Flutter version 1.10.1-pre.39 at D:\ProgramStorage\Applications\Flutter
    • Framework revision af07bb50fa (21 hours ago), 2019-09-06 21:48:41 -0400
    • Engine revision 50bdbd769e
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 ec7ec4ecf7)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\[REDACTED]\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Users\liamr\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\192.6603.28
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (2 available)
    • Windows • Windows • windows-x64    • Microsoft Windows [Version 10.0.18362.295]
    • Chrome  • chrome  • web-javascript • Google Chrome 76.0.3809.132

! Doctor found issues in 3 categories.

```

**Comment by jonahwilliams** [comment]
Please include a minimal example that reproduces the issue

**Comment by xeu100** [comment]
Any text that's in paragraph form causes the issue.

**Comment by jonahwilliams** [comment]
I can't reproduce this with an example project on 5a3a46ada2417957415c58a5a1adff0fc11f7fc5 using the unforked workflow at https://github.com/flutter/flutter/wiki/Building-a-web-application-with-Flutter

Please include an example that reproduces the issue

**Comment by xeu100** [comment]
`class DashboardPage extends StatefulWidget {

  Map<String, dynamic> _userdata = getUserDataBase();

  @override
  State<StatefulWidget> createState() {
    return DashboardPageState();
  }

}

class DashboardPageState extends State<DashboardPage> {

  @override
  void initState() {
    super.initState();
    setupUserData();
  }

  void setupUserData() async {
     await getUser(Firebase.app, context).then((snapshot) => {
       if(snapshot == null) {
         navigateLogin(context)
       } else {
         setState(() {
           widget._userdata = snapshot.data();
         })
       }
    }).catchError((err) => {
       navigateLogin(context)
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white10,
      body: Stack(
        children: <Widget>[
          ListView(
            children: <Widget>[
              Padding(padding: EdgeInsets.only(top: 60.0),),
              Text('Welcome, ${widget._userdata["nickname"]}!', style: getTextStyle().copyWith(fontSize: 20.0),),
              Padding(padding: EdgeInsets.only(bottom: MediaQuery
                  .of(context)
                  .size
                  .width >= 850 ? 70.0 : 130.0))
            ],
          ),
          NavBar(),
        ],
      )
    );
  }

}`
