### ISSUE TITLE
[Desktop] Binding Getsures to Mouse buttons

### ISSUE THREAD

**Issue by NexisHunter** [flutter/flutter#40057]
## Use case
I'm currently working to port my flutter android application to desktop, and I have context menus that generate on long press. Currently, from my understanding there isn't a way to bind a secondary mouse button click to the gesture.

## Proposal
   On desktop users would generally activate contextual menus in an application through the secondary mouse click, generally there are a few desktop environments for Linux that can have this changed. On Android and iOS, the concept of the long press is applied in its replacement. I would like to see flutter be able to bind the inputs. So that the folowing:
![Screenshot_20190908_104205](https://user-images.githubusercontent.com/29546913/64489891-f9517980-d225-11e9-94eb-ccaf401ff4d2.png)
Is triggerable through a right/secondary click on a mouse instead of a long press.

Also, I'd be willing to help with the development, I'm not 100% where to start.
Thanks :smile:

**Comment by stuartmorgan** [comment]
As far as I know all that's missing here is GLFW passing non-primary mouse buttons, which is #33220 for Linux. Marking this a duplicate, but if there's something other than that piece that you've found to be missing please let me know and I can re-open.

If you're interested in implementing that, https://github.com/flutter/engine/pull/9054 gives an example of how to translate OS button events to the Flutter embedding API. Similar logic would be needed in `shell/platform/glfw`.
