### ISSUE TITLE
Widget gesture actions don't work when Htmlview contains an iframe

### ISSUE THREAD

**Issue by vikramkapoor** [flutter/flutter#40058]
## Steps to Reproduce

1. Snackbar onTap action doesn't work when placed over Google Maps in htmlView in Flutter Web. The gesture is consumed by Google Maps. See code below and picture. Instead of the yes action getting called the map zooms out when I click on Yes.
![Capture](https://user-images.githubusercontent.com/3178673/64490286-4d516380-d210-11e9-83c5-3a4dbf96f237.PNG)

```
 Widget showMap() {
    debugPrint("PANICS: showMap()");
    showPanics(this.panics);
    return Column( children : <Widget>  [
 Container(
        height: MediaQuery.of(context).size.height ,
        padding: EdgeInsets.fromLTRB(10, 10, 10, 10),
        decoration: new BoxDecoration(
    border: new Border.all()
  ),
    child:HtmlView(viewType: createdViewId,
                          onPlatformViewCreated: _onPlatformViewCreated,
                        ),
     ),   SizedBox(height: 48)
    ]);
  }

  void _confirmDeletePanics(BuildContext context) {
    debugPrint("Panic:_confirmDeletePanics");
    Scaffold.of(context).showSnackBar(SnackBar(
        content: Text("Please confirm. Are you sure you want to delete the ${isSelected.length} selected alert${(isSelected.length>1)?"s":""}"),
        duration: Duration(seconds: 5),
        action: SnackBarAction(
          label: 'Yes',
          onPressed: () => _deletePanics(),
    )));
  }
```

**Comment by jonahwilliams** [comment]
Please include the output of `flutter doctor -v ` as well as a minimal example to reproduce the issue

**Comment by vikramkapoor** [comment]
@jonahwilliams 

Please see the min repro code below. I found that this happens with Flatbutton and likely another Widget covering HtmlView and not limited to BottomBar or SnackBar so I have updated the issue's title.  In the code below I put Flatbutton over HtmlView in a Stack. The Flatbutton action should work since it is in front of the HtmlView but it doesn't. The action starts working if we replace HtmlView with a Text widget.

```
// Copyright 2018 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:html';
import 'package:flutter_web_ui/ui.dart' as ui;
import 'package:flutter_web/material.dart';

void main() {
  runApp(new Center(child: new Directionality( textDirection: TextDirection.ltr,child:HtmlExample())));
}

class HtmlExample extends StatefulWidget {
  @override
  _HtmlExampleState createState() => new _HtmlExampleState();
}

class _HtmlExampleState extends State<HtmlExample> {
int count;
  @override
  void initState() {
    count = 0;
    ui.platformViewRegistry.registerViewFactory(
        'hello-world-html',
            (int viewId) => IFrameElement()
          ..width = '640'
          ..height = '360'
          ..src = 'https://www.youtube.com/embed/IyFZznAk69U'
          ..style.border = 'none');
    super.initState();
    // We use 3600 milliseconds instead of 1800 milliseconds because 0.0 -> 1.0
    // represents an entire turn of the square whereas in the other examples
    // we used 0.0 -> math.pi, which is only half a turn.
  }

  @override
  Widget build(BuildContext context) {
    return Stack(children: <Widget>[
      SizedBox(
      width: 640,
      height: 360,
      child:  HtmlView(viewType: 'hello-world-html')), //Text("Count = $count")),
      Text("Count = $count"),
      Column (children: <Widget>[
        FlatButton(child: Text("Count"), color: Colors.red, onPressed: () => setState((){count++;})),
        Text("Count = $count"),
      ],)
    ],);
  }

  @override
  void dispose() {
    super.dispose();
  }
}
```

**Comment by yjbanov** [comment]
This is a known issue when you have iframes in your `HtmlElementView`. This is a fundamental limitation in browsers, but we are investigating ways to address it, at least partially.

Just a heads up, this is not a small project, so it will take time. In the meantime, consider using non-iframe HTML (which google maps may have; dunno for sure).

**Comment by vikramkapoor** [comment]
Thank you for the analysis. I will try with the non-iframe HTML ASAP and get back.

    On Thursday, September 19, 2019, 03:22:02 PM PDT, Yegor <notifications@github.com> wrote:  
 
 
This is a known issue when you have iframes in your HtmlElementView. This is a fundamental limitation in browsers, but we are investigating ways to address it, at least partially.

Just a heads up, this is not a small project, so it will take time. In the meantime, consider using non-iframe HTML (which google maps may have; dunno for sure).

**Comment by theshivamlko** [comment]
@vikramkapoor can u provide resource or code for GoogleMap in Flutter or using iFrame. I am unabe to make it work. the same UI that u posted

**Comment by vikramkapoor** [comment]
Here is the code that displays the map with markers. I believe this has to be re-done now since HtmlView that is using is from the Flutter_web package which is no longer needed/works after flutter converged the web support last month. I am hoping we can just use the flutter google maps plugin instead like on the mobile.



|  Widget showMap() { |
|  | 
 |
|  |  showPanics(this.panics); |
|  |  return |
|  |  Container( |
|  |  //height: MediaQuery.of(context).size.height, |
|  |  padding: EdgeInsets.fromLTRB(10, 10, 10, 10), |
|  |  decoration: new BoxDecoration( |
|  |  border: new Border.all() |
|  |  ), |
|  |  child:HtmlView(viewType: createdViewId, |
|  |  onPlatformViewCreated: _onPlatformViewCreated, |
|  |  ), |
|  |  ); |
|  |  }
| void showPanics(List<fs.DocumentSnapshot> panics) { |
|  |  String markers = ""; |
|  |  String latlng = "var myLatLng = {lat: 41.850033, lng: -87.6500523}"; |
|  |  DateTime max = DateTime.fromMicrosecondsSinceEpoch(0); |
|  |  fs.GeoPoint lastPanicPosition; |
|  |  if (panics != null) { |
|  |  debugPrint("PANICS: Number of panics = ${panics.length}"); |
|  |  panics.forEach((data) { |
|  |  Panic panic = Panic.fromSnapshot(data); |
|  |  debugPrint("PANICS: Reference = ${panic.reference.id}"); |
|  |  String strIcon = (panic.status == 'new') |
|  |  ? "http://maps.google.com/mapfiles/ms/icons/red-dot.png" |
|  |  : "http://maps.google.com/mapfiles/ms/icons/green-dot.png"; |
|  |  String marker = |
|  |  "var marker = new google.maps.Marker({position: new google.maps.LatLng(${panic.position.latitude}, ${panic.position.longitude})," |
|  |  //+ "infoWindow: InfoWindow(title: '${panic.status}', snippet: 'Room: ${panic.roomId}')," |
|  |  + |
|  |  "map: map," + |
|  |  "icon:\"$strIcon\"," + |
|  |  "title: '${Globals.globals.getUserName(panic.userId)} needs help!'});\n"; |
|  |  markers += marker; |
|  |  DateTime time = panic.timeStamp; |
|  |  if (time.compareTo(max) > 0) { |
|  |  max = time; |
|  |  lastPanicPosition = panic.position; |
|  |  } |
|  |  }); |
|  |  if (lastPanicPosition != null) |
|  |  latlng = |
|  |  "var myLatLng = {lat: ${lastPanicPosition.latitude}, lng: ${lastPanicPosition.longitude}}"; |
|  |  } |
|  |  // debugPrint("Panics: showPanic markers = $markers"); |
|  |  // debugPrint("Panics: showPanic latlng = $latlng"); |
|  |  |
|  |  this.createdViewId = DateTime.now().toString(); |
|  |  String value = '''  |
|  |  <!DOCTYPE html> |
|  | <html> |
|  | <head> |
|  |  <meta name="viewport" content="initial-scale=1.0, user-scalable=no"> |
|  |  <meta charset="utf-8"> |
|  |  <title>Simple Markers</title> |
|  |  <style> |
|  |  /* Always set the map height explicitly to define the size of the div |
|  |  * element that contains the map. */ |
|  |  #map { |
|  |  height: 74%; |
|  |  width: 98% |
|  |  } |
|  |  /* Optional: Makes the sample page fill the window. */ |
|  |  html, body { |
|  |  height: 100%; |
|  |  margin: 0; |
|  |  padding: 0; |
|  |  } |
|  |  </style> |
|  | </head> |
|  | <body> |
|  | <div id="map"></div> |
|  | <script> |
|  |  |
|  |  function initMap() { |
|  |  var myLatLng = {lat: 41.850033, lng: -87.6500523}; |
|  |  |
|  |  var map = new google.maps.Map(document.getElementById('map'), { |
|  |  zoom: 17, |
|  |  center: myLatLng, |
|  |  gestureHandling: 'auto' |
|  |  }); |
|  |  |
|  |  markers |
|  |  |
|  |  } |
|  |  </script> |
|  | <script async defer |
|  |  src="https://maps.googleapis.com/maps/api/js?key=<Put your Google Maps Key here>&callback=initMap"> |
|  | </script> |
|  | </body> |
|  | </html> |
|  | '''; |
|  |  String strMapUpdate = value.replaceAll( |
|  |  new RegExp(r'var myLatLng = {lat: 41.850033, lng: -87.6500523}'), |
|  |  latlng); |
|  |  strMapUpdate = strMapUpdate.replaceAll(new RegExp(r'markers'), markers); |
|  | // debugPrint("Panics strMapUpdate =: $strMapUpdate"); |
|  |  ui.platformViewRegistry.registerViewFactory( |
|  |  createdViewId, |
|  |  (int viewId) => IFrameElement() |
|  |  ..width = (MediaQuery.of(context).size.width - 400).toString() |
|  |  ..height = MediaQuery.of(context).size.height.toString() |
|  |  //..src = 'https://www.youtube.com/embed/tgbNymZ7vqY' |
|  |  ..srcdoc = strMapUpdate |
|  |  ..style.border = 'none'); |
|  | /* if (mounted) { |
|  |  setState(() { |
|  |  debugPrint("PANICS setState in showPanics"); |
|  |  inProgress = false; |
|  |  this.panics = panics; |
|  |  }); |
|  |  }*/ |
|  |  } |

 |


Vikram
    On Sunday, October 13, 2019, 12:07:54 AM PDT, shivam srivastava <notifications@github.com> wrote:  
 
 
@vikramkapoor can u provide resource or code for GoogleMap in Flutter or using iFrame. I am unabe to make it work. the same UI that u posted

**Comment by rostopira** [comment]
I don't receive `onTap` with `InkWell` when child contains video element
However ripple effect is appearing on every tap
I suppose, this is a different bug?

**Comment by Abhilash-Chandran** [comment]
I notice this issue as well. I also believe this is not an issue related to using `Iframes` inside `HTMLElementView`. I have created a flutter web project which makes use of `HTMLElementView` and other Material components like `PopupMenuButton`, `showDialog` etc. Its easy to notice this when the popup menu open and if we scroll the mouse wheel eventlistener on the `DivElement` which is rendered below this menu.  Additionally the click event is passed down as well. This also applies when a dialog is shown  which effectively uses `ModalBarrier` to prevent the user from interacting with anything below this dialog.

This i especially inconvenient when a Plot is being rendered below the popup menu or the dialog. In my case I am rendering a plotly Plot which is unnecessarily consuming these events and reacting.

![image](https://user-images.githubusercontent.com/4489849/67342835-9bf25d00-f533-11e9-9ecf-a5458fb11ceb.png)


I have uploaded this simple project in Github for [reference](https://github.com/Abhilash-Chandran/flutter_web_htmlelementview_test).

**Comment by AngusPei** [comment]
same issues....😂

Is there any other way?

**Comment by AngusPei** [comment]
> This is a known issue when you have iframes in your `HtmlElementView`. This is a fundamental limitation in browsers, but we are investigating ways to address it, at least partially.
> 
> Just a heads up, this is not a small project, so it will take time. In the meantime, consider using non-iframe HTML (which google maps may have; dunno for sure).

I have the same issue with my project. Are you sure about the modification completion time?

**Comment by AngusPei** [comment]
```dart
// ignore: avoid_web_libraries_in_flutter
import 'dart:html';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() {
  // ignore:undefined_prefixed_name
  ui.platformViewRegistry.registerViewFactory('someViewType', (int viewId) {
    final wrapper = DivElement();
//     final div = DivElement()
//       ..contentEditable = 'true'
//       ..style.width = '100%'
//       ..style.height = '100%';
//     wrapper.append(div);
    final div = IFrameElement()
        ..width = '640'
        ..height = '360'
        ..src = 'https://www.youtube.com/embed/IyFZznAk69U'
        ..style.border = 'none';
    wrapper.append(div);
    return wrapper;
  });
  
  // ignore:undefined_prefixed_name
  ui.platformViewRegistry.registerViewFactory(
      'hello-world-html',
      (int viewId) => IFrameElement()
        ..width = '640'
        ..height = '360'
        ..src = 'https://www.youtube.com/embed/IyFZznAk69U'
        ..style.border = 'none');
  
  runApp(MaterialApp(home: HomeScreen()));
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      drawer: Drawer(child: Container(color:Colors.yellow, child: RaisedButton(
      onPressed:()=>debugPrint("123123")
      ))),
      body:  SizedBox(
      width: 640,
      height: 360,
      child: HtmlWidget(),
    ),
      floatingActionButton: Builder(builder: (context) {
        return FloatingActionButton(
          child: Icon(Icons.menu, color: Colors.white),
          onPressed: () {
            Scaffold.of(context).openDrawer();
          },
        );
      }),
    );
  }
}

class HtmlWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return HtmlElementView(viewType: 'someViewType');
  }
}

class HtmlHelloWorldWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return HtmlElementView(viewType: 'hello-world-html');
  }
}
```
![image](https://user-images.githubusercontent.com/4378435/78151088-c6ddc700-746a-11ea-9117-8e3776b53d78.png)

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/54027.
