### ISSUE TITLE
I use Flutter to create an APP and need to dynamically modify the app name

### ISSUE THREAD

**Issue by Dygood** [flutter/flutter#40051]
I want to globalize the app, app name should be how to implement according to the app select different languages to display the corresponding language app name.

**Comment by Akora-IngDKB** [comment]
This seems much of a stackoverflow question than an issue with the Flutter SDK itself.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
