### ISSUE TITLE
flutter run very slow on Android devices

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#4005]
Running the flutter gallery on Android devices in debug mode is incredibly slow.  For example, building the front page takes 626.875 ms.

It's true that high performance isn't a goal for debug mode, but we shouldn't be off by 100x.  This used to be much faster.  It's unclear what changed.

/cc @jason-simmons

**Comment by eseidelGoogle** [comment]
Is this Android built from a Mac or Android?

**Comment by abarth** [comment]
Mac host, Android target.

**Comment by Hixie** [comment]
Building for Android from Linux, using cloud-provided artifacts, I see the flutter gallery _idling_ at 230ms/frame.

Running the smoke test on the device, the first part of the test, which just calls the `main` function which just does a single `runApp` without even building it, takes about 20 _seconds_.

**Comment by Hixie** [comment]
That's a factor of 1000 off from where we used to be.

**Comment by Hixie** [comment]
Filed https://github.com/flutter/flutter/issues/4008 to track regressions in the future.

**Comment by eseidelGoogle** [comment]
Unfortunately I can't take this.

**Comment by abarth** [comment]
Doesn't seem to affect non-checked mode.

**Comment by Hixie** [comment]
It might be an assert I added in my big test landing maybe?

**Comment by abarth** [comment]
Bisecting.

**Comment by abarth** [comment]
First bad commit in flutter.git:

```diff
commit 833942788d028afe83b892f134ba96c807a00329
Author: Jason Simmons <jason-simmons@users.noreply.github.com>
Date:   Tue May 17 15:19:41 2016 -0700

    Update the engine (#3997)

diff --git a/bin/cache/engine.version b/bin/cache/engine.version
index 069757f..2018998 100644
--- a/bin/cache/engine.version
+++ b/bin/cache/engine.version
@@ -1 +1 @@
-a1f4a12baa3dd4382e395743ff16ffbe3d188b88
+eceadfd14734121da019c0f05161bcdeeffad14a
```

**Comment by Hixie** [comment]
Well there's a few candidates but the obvious one is the Dart roll.

**Comment by abarth** [comment]
Yeah, trying a local build just prior to that point.

**Comment by abarth** [comment]
Looks like it might have been https://github.com/flutter/engine/commit/f641f6baa1a46d85fdf14764dec3ef60f23e4a17

That appears to turn the dart_experimental_interpreter on everywhere in debug mode.

/cc @chinmaygarde

**Comment by abarth** [comment]
Need to do a couple more builds to confirm.

**Comment by chinmaygarde** [comment]
Yeah, this is definitely my fault. Regressed in f641f6baa1a46d85fdf14764dec3ef60f23e4a17. The dart_experimental_interpreter setter needs to be guarded for iOS.

**Comment by abarth** [comment]
```
f641f6baa1a46d85fdf14764dec3ef60f23e4a17 is the first bad commit
commit f641f6baa1a46d85fdf14764dec3ef60f23e4a17
Author: Chinmay Garde <chinmaygarde@gmail.com>
Date:   Mon May 16 13:45:24 2016 -0700

    Flip the switch on enabling the interpreter by default in debug runtime mode. (#2691)

:040000 040000 9fa7322da855ccf7d7c03991b394d2a3cabaffb7 0f21b87323d5c7d89b36f8bbc21ac3d94a1ac100 M	sky
```
