### ISSUE TITLE
exception was thrown, this was the stack: 

### ISSUE THREAD

**Issue by tarbundiyahitesh21** [flutter/flutter#40071]
```
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:2216:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
...
```

**Comment by BondarenkoStas** [comment]
@tarbundiyahitesh21 Please provide more information, currently it's not possible to investigate.

Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

Also please provide your ```flutter doctor -v``` output.

If there are more logs, they may be helpful as well.

**Comment by tarbundiyahitesh21** [comment]
@override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      color: AppColor.themeColor,
      home: Container(
        color: AppColor.themeColor,
        child: Center(
          child: Stack(
            children: <Widget>[
              Container(
                margin: EdgeInsets.all(Dimension.dimen_48),
                child:  Center(
                  child: ScaleTransition(scale: _animation, child: ImagesList.Image_splash,),
                  
                ),
              ),
            Container(

              child: FlatButton(onPressed: Dialogs.dialog_alertOne(context, "My First dialog", "Testinf my dialog any way and test again.", "dismiss"), child: Text("Close")),
            )
            ],

          ),
        ),
      ),
    );
  }



import 'package:flutter/material.dart';

class Dialogs {
  static dialog_alertOne(BuildContext _context, title, description, buttonName) {
    showDialog(
        context: _context,
        builder: (_context) => AlertDialog(
              title: Text(title),
              content: Text(description),
              actions: <Widget>[
                FlatButton(
                    onPressed: () {
                      Navigator.of(_context).pop();
                    },
                    child: Text(buttonName)),
              ],
            ));
  }
}

**Comment by tarbundiyahitesh21** [comment]
` @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      color: AppColor.themeColor,
      home: Container(
        color: AppColor.themeColor,
        child: Center(
          child: Stack(
            children: <Widget>[
              Container(
                margin: EdgeInsets.all(Dimension.dimen_48),
                child:  Center(
                  child: ScaleTransition(scale: _animation, child: ImagesList.Image_splash,),
                  
                ),
              ),
            Container(

              child: FlatButton(onPressed: Dialogs.dialog_alertOne(context, "My First dialog", "Testinf my dialog any way and test again.", "dismiss"), child: Text("Close")),
            )
            ],

          ),
        ),
      ),
    );
  }`


`import 'package:flutter/material.dart';

class Dialogs {
  static dialog_alertOne(BuildContext _context, title, description, buttonName) {
    showDialog(
        context: _context,
        builder: (_context) => AlertDialog(
              title: Text(title),
              content: Text(description),
              actions: <Widget>[
                FlatButton(
                    onPressed: () {
                      Navigator.of(_context).pop();
                    },
                    child: Text(buttonName)),
              ],
            ));
  }
}
`

**Comment by BondarenkoStas** [comment]
@tarbundiyahitesh21 please provide your flutter doctor -v output.

**Comment by tarbundiyahitesh21** [comment]
Flutter command not found

**Comment by BondarenkoStas** [comment]
@tarbundiyahitesh21 but where is the log from, did you run `flutter run`? It's strange about flutter doctor, did you run it from the same place? We just need it to know exactly which version of the framework to use to reproduce the issue, at least to know if it's on stable or on master channel, and about environment etc

**Comment by janmoppel** [comment]
Hello @tarbundiyahitesh21 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
