### ISSUE TITLE
How do i make DataTable or PaginatedDataTable occupy the full width of its parent Card

### ISSUE THREAD

**Issue by neeleshramputh** [flutter/flutter#40081]
Is there any Widget (SizedBox.expand was mentioned in another issue) or configuration which will enable me to make a DataTable/PaginatedDataTable occupy the full width of its parent Card?

Thanks.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. See https://flutter.dev/community for support options.

**Comment by neeleshramputh** [comment]
The same question has been already asked on stackoverflow and no acceptable answer atm.

https://stackoverflow.com/questions/56625052/how-do-you-make-a-multi-column-flutter-datatable-widget-span-the-full-width

**Comment by bkonyi** [comment]
I've run into this myself and I've posted the following answer on the [StackOverflow post](https://stackoverflow.com/questions/56625052/how-do-you-make-a-multi-column-flutter-datatable-widget-span-the-full-width):

`SizedBox.expand` results in the `DataTable` taking an infinite height which the `SingleChildScrollView` won't like. Since you only want to span the width of the parent, you can use a `LayoutBuilder` to get the size of the parent you care about and then wrap the `DataTable` in a `ConstrainedBox`.

```dart
    Widget build(BuildContext context) {
      return Scaffold(
        body: LayoutBuilder(
          builder: (context, constraints) => SingleChildScrollView(
            child: Column(
              children: [
                const Text('My Text'),
                Container(
                  alignment: Alignment.topLeft,
                  child: SingleChildScrollView(
                    scrollDirection: Axis.horizontal,
                    child: ConstrainedBox(
                      constraints: BoxConstraints(minWidth: constraints.minWidth),
                      child: DataTable(columns: [], rows: []),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      );
    }
```

Unfortunately, this doesn't work for `PaginatedDataTable`, which is basically a `DataTable` rendered within a `Card`. #47555 should have a fix for this.

**Comment by git-xbits** [comment]
I have same problem. I need to expand a PaginatedDataTable, because I really need pagination. The solution above is just to DataTable, whihout pagination.

**Comment by bkonyi** [comment]
@git-xbits see #47555 for the fix for `PaginatedDataTable`.

**Comment by VladyslavBondarenko** [comment]
Seems to be solved, closing
If you disagree please write in the comments and I will reopen it
Thank you

**Comment by shasank27** [comment]
> I've run into this myself and I've posted the following answer on the [StackOverflow post](https://stackoverflow.com/questions/56625052/how-do-you-make-a-multi-column-flutter-datatable-widget-span-the-full-width):
> 
> `SizedBox.expand` results in the `DataTable` taking an infinite height which the `SingleChildScrollView` won't like. Since you only want to span the width of the parent, you can use a `LayoutBuilder` to get the size of the parent you care about and then wrap the `DataTable` in a `ConstrainedBox`.
> 
> ```dart
>     Widget build(BuildContext context) {
>       return Scaffold(
>         body: LayoutBuilder(
>           builder: (context, constraints) => SingleChildScrollView(
>             child: Column(
>               children: [
>                 const Text('My Text'),
>                 Container(
>                   alignment: Alignment.topLeft,
>                   child: SingleChildScrollView(
>                     scrollDirection: Axis.horizontal,
>                     child: ConstrainedBox(
>                       constraints: BoxConstraints(minWidth: constraints.minWidth),
>                       child: DataTable(columns: [], rows: []),
>                     ),
>                   ),
>                 ),
>               ],
>             ),
>           ),
>         ),
>       );
>     }
> ```
> 
> Unfortunately, this doesn't work for `PaginatedDataTable`, which is basically a `DataTable` rendered within a `Card`. #47555 should have a fix for this.

didn't work for me
pasted the exact code
