### ISSUE TITLE
Play music on flutter_web pages

### ISSUE THREAD

**Issue by zhangruiyu** [flutter/flutter#40084]
Play music on flutter_web pages

**Comment by BondarenkoStas** [comment]
@zhangruiyu Is it a proposal? Can you describe in more details?

**Comment by janmoppel** [comment]
Hello @zhangruiyu !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
