### ISSUE TITLE
ResolutionPreset.max doesn't work (vivo x21)

### ISSUE THREAD

**Issue by wujianqiang6** [flutter/flutter#40083]
Android :
```
CameraController  controller = CameraController(
      cameraDescription,
      ResolutionPreset.max, //set size
      enableAudio: false,
    );
```
max  is not work ,my phone is vivo x21

**Comment by BondarenkoStas** [comment]
@wujianqiang6 Please provide your ```flutter doctor -v``` output.

**Comment by wujianqiang6** [comment]
> @wujianqiang6 Please provide your `flutter doctor -v` output.
max is OK ,but it's not still Full screen

**Comment by wujianqiang6** [comment]
@BondarenkoStas  max is OK ,but it's not still Full screen

**Comment by iapicca** [comment]
Hi @wujianqiang6 
I'm not sure to understand your answer:
are you still experiencing the issue?
If so can you please describe the issue in detail
and provide your `flutter doctor -v`
thank you

**Comment by wujianqiang6** [comment]
perfect! thanks very much


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Francecsco Iapicca"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月4日(星期一) 下午3:28
收件人:&nbsp;"flutter/flutter"<flutter@noreply.github.com&gt;;
抄送:&nbsp;"WJQ"<735127892@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [flutter/flutter] ResolutionPreset.max doesn't work (vivo x21) (#40083)




Hi @wujianqiang6
 I'm not sure to understand your answer:
 are you still experiencing the issue?
 If so can you please describe the issue in detail
 and provide your flutter doctor -v
 thank you

**Comment by wujianqiang6** [comment]
My problem has been solved！Thanks


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Francecsco Iapicca"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月4日(星期一) 下午3:28
收件人:&nbsp;"flutter/flutter"<flutter@noreply.github.com&gt;;
抄送:&nbsp;"WJQ"<735127892@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [flutter/flutter] ResolutionPreset.max doesn't work (vivo x21) (#40083)




Hi @wujianqiang6
 I'm not sure to understand your answer:
 are you still experiencing the issue?
 If so can you please describe the issue in detail
 and provide your flutter doctor -v
 thank you

**Comment by iapicca** [comment]
Hi again @wujianqiang6 
I'm glad to hear that,
thank you for letting me know
