### ISSUE TITLE
[google_sign_in] Document how to use google_sign_in without Firebase and setup steps 

### ISSUE THREAD

**Issue by PaoloGi** [flutter/flutter#40091]
In the readme of the google_sign_in plugin the "register your application" link redirects to firebase now ( https://developers.google.com/mobile/add?platform=android) 

Where do i have to register Android and IOS application if i do not want Firebase now ?

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.

**Comment by PaoloGi** [comment]
> This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
> If you disagree, feel free to comment and I will reopen the issue.

Hi thanks for the feedback, i edited the issue

**Comment by VladyslavBondarenko** [comment]
Hi @PaoloGi 
This is not an issue, you are supposed to register your app with firebase
https://medium.com/flutter-community/flutter-implementing-google-sign-in-71888bca24ed

**Comment by PaoloGi** [comment]
> Hi @PaoloGi
> This is not an issue, you are supposed to register your app with firebase
> https://medium.com/flutter-community/flutter-implementing-google-sign-in-71888bca24ed

Nope.
I did it without Firebase and it is not mandatory.

What is missing in the Readme is the possibility for the user to use it with only  a project on Google Cloud.

Just download the .json on the credential, rename as google-services.json and place it in the app.

**Comment by TahaTesser** [comment]
This issue about using `google_sign_in` without firebase 
As mentioned here and https://github.com/flutter/flutter/issues/40091#issuecomment-588718984 
> Where do i have to register Android and IOS application if i do not want Firebase now ?


Closing as duplicate of https://github.com/flutter/flutter/issues/36673
