### ISSUE TITLE
`flutter run -d chrome` is not logging print statements on initial run

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#40115]
Repro:
```dart
import 'package:flutter/widgets.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('Important logging info');
    return SizedBox.expand();
  }
}
```

When I run this with `flutter run -d chrome` I don't see `"Importing logging info."` in the output. However, it appears after I do a hot restart (by pressing `r`).

**Comment by jonahwilliams** [comment]
The issue here is that I call main before setting up the vmservice registration. Fix should be to move it to after
