### ISSUE TITLE
debug_full_compile_millis regressed by 2x

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#40111]
Since https://github.com/flutter/flutter/commit/f19e4ab4f7a74e89e2cf4b5de1e6963765d0728c,
-`basic_material_app_android__compile debug_full_compile_millis` regressed from ~24000ms to ~55000ms
-`complex_layout_android__compile debug_full_compile_millis` regressed from ~22000ms to ~55000ms.

**Comment by liyuqian** [comment]
CC @jonahwilliams

**Comment by liyuqian** [comment]
@digiter : is there any recent update in the device lab that could cause this regression (e.g., replaced the linux box)?

**Comment by digiter** [comment]
No, except I switched the phones on linux1 and linux2.

**Comment by jonahwilliams** [comment]
I cannot reproduce this on a local device. I'm also extremely skeptical that a version bump in a web debugging library regressed dar compilation time on Android.

**Comment by blasten** [comment]
I couldn't reproduce this issue either. 

cc @dnfield. Could this be related to the changes you made to the JVM heap size?

**Comment by dnfield** [comment]
I did update the gradle settings to make them consistent across linux1 and linux2 - I doubt that did it but i can try to look at it in the morning.

**Comment by dnfield** [comment]
This is due to disabling the gradle daemon on the bots.

I would like to keep it disabled because currently, it runs until it leaks enough memory to fail a test for other reasons (anytime you see logs like "Java Heap Space" - see https://github.com/flutter/flutter/issues/39944).

I'm going to rebaseline the benchmarks. We should re-enable the gradle daemon either after fixing https://github.com/flutter/flutter/issues/31089 or updating the devicelab to more effectively manage state between test runs (e.g. use containers or kill the daemon between runs or so many times a day, etc.).

/cc @blasten @godofredoc

**Comment by dnfield** [comment]
(I reproduced this locally by running the test with and without the gradle daemon - that can be disabled globally by setting `org.gradle.daemon=false` in your `$HOME/.gradle/gradle.properties`)

**Comment by liyuqian** [comment]
@dnfield : any update on this? Shall we close this now, or close this until https://github.com/flutter/flutter/issues/31089 is fixed and gradle daemon is re-enabled?

**Comment by dnfield** [comment]
IMO we should leave this open until we re-enable the gradle daemon on CI - or, alternatively, we disable it for all customers.

**Comment by liyuqian** [comment]
@dnfield : any update on re-enabling gradle?

**Comment by dnfield** [comment]
I am not working on this issue and not aware as to whether anyone is or not.  @blasten may know if it's on the docket.

**Comment by liyuqian** [comment]
Closing this as they've gone down to below 20000ms

**Comment by dnfield** [comment]
Did the device lab reenable Gradle daemon recently?

**Comment by liyuqian** [comment]
I have no idea. CC @blasten on that question.

**Comment by blasten** [comment]
I'm not aware of such change. Maybe @godofredoc knows.

**Comment by godofredoc** [comment]
We haven't enabled graddle. This is a side effect of replacing the old machines with more powerful ones and installing linux as server rather than as desktop.

**Comment by dnfield** [comment]
The Gradle daemon is enabled by default.  Was it explicitly disabled on the new machines?
