### ISSUE TITLE
Finished with error: ProcessException: /beginnerflutterapp/android/gradlew" exited abnormally:

### ISSUE THREAD

**Issue by kondasusmithareddy** [flutter/flutter#40123]
## Steps to Reproduce

1.I Installed flutter and added i set path 
2.While running the project its getting error. 
3. ...please help me

## Logs

```
Exception in thread "main" java.lang.NullPointerException
	at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:34)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:25)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: /Users/charissoftware/practice/sushmita/begineerflutterapp  /beginnerflutterapp/android/gradlew -v

```

**Comment by CoderNeilz** [comment]
clean ur flutter object , such as .ios .android/xxx， old file .
then, run flutter clean

**Comment by BondarenkoStas** [comment]
@kondasusmithareddy what is the output of ```flutter doctor -v```? What is the content of the file ```<app>\android\gradle\gradle-wrapper.properties```?

**Comment by kondasusmithareddy** [comment]
> clean ur flutter object , such as .ios .android/xxx， old file .
> then, run flutter clean

this is not working i tried

**Comment by kondasusmithareddy** [comment]
> @kondasusmithareddy what is the output of `flutter doctor -v`? What is the content of the file `<app>\android\gradle\gradle-wrapper.properties`?

The Output of flutter doctor -v is working fine  no errors. and the gradle-wrapper.properties is
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip

**Comment by BondarenkoStas** [comment]
@kondasusmithareddy Please try to upgrade your gradle. I found also an interesting comment, maybe it's related to your issue https://github.com/flutter/flutter/issues/34211#issuecomment-503666986.
In general flutter doctor output is needed to check the framework version where the issue occurs, check environment etc.

**Comment by BondarenkoStas** [comment]
@blasten I just saw you comment on the #37598 and decided maybe you can help with it.
There are a bunch of similar issues:
#35659
#34211
#33569
I think it would be nice to post some kind of solution if there is any.

**Comment by tsinis** [comment]
> @blasten I just saw you comment on the #37598 and decided maybe you can help with it.
> There are a bunch of similar issues:
> #35659
> #34211
> #33569
> I think it would be nice to post some kind of solution if there is any.

Hey, try to create dummy project via
`flutter create dummy`
then just backup your old android folder inside your flutter project and replace it with folder from dummy project. You may keep an "app" folder inside android folder as far as I know. Also don't forget to migrate to androidx if you did it in original grade

**Comment by jonahwilliams** [comment]
With a way to reproduce this locally, it's unlikely that we can make progress here. Its likely there is some misconfiguration in the local android project - this could be detected by checking if a freshly created project works.
