### ISSUE TITLE
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:1027/K3wiFxA0qFk=/ws

### ISSUE THREAD

**Issue by adrian999999** [flutter/flutter#40127]
Hi @danrubel ,

I have upgraded to v1.9.1+hotfix.2.

Somehow this issue come up,
This time is not Android, I was trying to debug in IOS device.

I have created logs in the gist, Please check

## Logs
https://gist.github.com/adrian999999/9080fa630b43a5acae26acba7eda932a

**Comment by AnnatarHe** [comment]
Launching lib/main.dart on iPhone Xʀ in debug mode...
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                           8.4s
 └─Compiling, linking and signing...                        12.4s
Xcode build done.                                           31.1s
*** First throw call stack:                                             
(                                                                       
        0   CoreFoundation                      0x00000001114b18db __exceptionPreprocess + 331
        1   libobjc.A.dylib                     0x000000011030dac5 objc_exception_throw + 48
        2   CoreFoundation                      0x00000001114cfc94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
        3   CoreFoundation                      0x00000001114b6623 ___forwarding___ + 1443
        4   CoreFoundation                      0x00000001114b8418 _CF_forwarding_prep_0 + 120
        5   flutter_secure_storage              0x000000010fe6c087 -[FlutterSecureStoragePlugin handleMethodCall:result:] + 327
        6   Flutter                             0x000000010d5694fd __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
        7   Flutter                             0x000000010d502ec0 _ZNK7flutter21PlatformMessageRouter21Handl<…>
Lost connection to device.                                              
Syncing files to device iPhone Xʀ...

**Comment by BondarenkoStas** [comment]
@adrian999999 just wondering, as has nothing to do with #34200?

**Comment by adrian999999** [comment]
Thanks @BondarenkoStas, Its during flutter run not `flutter pub get/upgrade`

**Comment by AnnatarHe** [comment]
after upgrade flutter_secure_storage to 3.3.1 solve this issue

**Comment by adrian999999** [comment]
Thanks guys, I can rebuild successfully now
