### ISSUE TITLE
[InputDecorator] Unwanted padding in TextField when you disable the counter

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#40121]
TextField shouldn't have a bottom padding when you don't need a counter. It gets noticeably worse when you use TextFormField and a Card.
![image](https://user-images.githubusercontent.com/351125/64581136-5d2b8d80-d35f-11e9-9902-49839d3b3798.png)

This is the problem: https://github.com/flutter/flutter/blob/77f71ef48f5d1c7c50774dc862e0688d052cc82f/packages/flutter/lib/src/material/input_decorator.dart#L970

If you set counter to null, it defaults to the one that is default. If you set counter to anything (like a SizedBox.shrink()), the counterHeight is 0+8 = 8. 

```dart
Container(
    color: Colors.red,
    child: SizedBox(
        width: 150,
        child: TextField(
            textAlign: TextAlign.center,
            maxLength: 6,
            decoration: InputDecoration(
                border: InputBorder.none,
                contentPadding: EdgeInsets.zero,
                counter: SizedBox.shrink(),
            ),
        ),
    ),
),
```

```
➜ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.0, on Mac OS X 10.14.6 18G95, locale en-BR)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.2)
[✓] VS Code (version 1.38.0)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by AlexVincent525** [comment]
Might duplicate with #44909 which was fixed.

**Comment by bernaferrari** [comment]
Yes, thanks @AlexVincent525

**Comment by AlexVincent525** [comment]
> Yes, thanks @AlexVincent525
> 
> Your solution is a bit weird, you need to set the counter callback to null, not the counter, but I guess it works.

Sure. But I think that's the only way to handle this now. :smile:

**Comment by AlexVincent525** [comment]
Before it released, you can edit the source code and play around. Because the counter was included with a semantic widget, it actually takes some gap whether your counter's value is.
