### ISSUE TITLE
Custom AppBar Height.(eg. 48，not only kToolbarheight(56))

### ISSUE THREAD

**Issue by v7lin** [flutter/flutter#40134]

**Comment by BondarenkoStas** [comment]
Tangential related to #7330.

**Comment by AyushBherwani1998** [comment]
@Piinks Can I work on this issue? I see there are already two closed PRs already and one with the only issue in the test.

**Comment by Piinks** [comment]
> @Piinks Can I work on this issue? I see there are already two closed PRs already and one with the only issue in the test.

Hey @AyushBherwani1998! Of course! I would be happy to review a PR if you would like to open one, thanks! :)

**Comment by AyushBherwani1998** [comment]
@Piinks I have opened a PR, looking forward to reviews :)

**Comment by Piinks** [comment]
> @Piinks I have opened a PR, looking forward to reviews :)

Hey @AyushBherwani1998 thank you! I will be able to check it out today.

**Comment by v7lin** [comment]
@AyushBherwani1998 why not add toolbarHeight to AppBarTheme?
