### ISSUE TITLE
Degration 1.7.8-hotfix.4 rootBundle.load "unable to load asset"

### ISSUE THREAD

**Issue by DavidKuennen** [flutter/flutter#40136]
After upgrading from 1.7.8-hotfix.3 to 1.7.8.hotfix.4, rootBundle.load always failes with "unable to load asset"

**Comment by BondarenkoStas** [comment]
@DavidKuennen Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by janmoppel** [comment]
Hello @DavidKuennen !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
