### ISSUE TITLE
add flutter module to exist ios project, xcode output 'multi_image_picker/multi_image_picker-Swift.h' file not found

### ISSUE THREAD

**Issue by longdw** [flutter/flutter#40133]
## Steps to Reproduce
1. create a flutter module
2. add a plugin write by swift to flutter module, such as add `multi_image_picker: ^4.5.3` in pubspec.yaml
3. add flutter module to exist project follow this  https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#ios

## Logs

when I run my native ios project, xcode output:

```
Module map file '/Users/longdw/Library/Developer/Xcode/DerivedData/Runner-grijtckhfwcfwbatccjavbisjvsj/Build/Products/Debug-iphonesimulator/multi_image_picker/multi_image_picker.modulemap' not found

Failed to emit precompiled header '/Users/longdw/Library/Developer/Xcode/DerivedData/Runner-grijtckhfwcfwbatccjavbisjvsj/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_1KTVSY7L9NXDI-clang_1CAHUYQRUY429.pch' for bridging header '/Users/longdw/Documents/iOSLab/flutter_keyboard/.ios/Runner/Runner-Bridging-Header.h'

/Users/longdw/flutter/.pub-cache/hosted/pub.flutter-io.cn/multi_image_picker-4.5.3/ios/Classes/MultiImagePickerPlugin.m:2:9: 'multi_image_picker/multi_image_picker-Swift.h' file not found
```

```
Flutter (Channel master, v1.9.1-pre.58, on Mac OS X 10.14.6 18G95, locale
    zh-Hans-CN)
    • Flutter version 1.9.1-pre.58 at /Users/longdw/flutter
    • Framework revision bc95f0881c (4 weeks ago), 2019-08-16 03:14:36 -0400
    • Engine revision bfa9be9978
    • Dart version 2.5.0 (build 2.5.0-dev.2.1 e35e8833ee)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/longdw/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1
```
I try to add `use_frameworks!` to `.ios/Podfile`, the .ios project can run successfully, but my native ios project still output those errors. I can't add `use_frameworks!` to my native ios project, because when I add it, it will cause other errors.

@Hixie @zoechi  @mravn-google @collinjackson @xster

**Comment by xster** [comment]
@jmagman might know

**Comment by jmagman** [comment]
Looks like https://github.com/flutter/flutter/issues/24099 and https://github.com/flutter/flutter/issues/25676, probably not related to add-to-app.

**Comment by jmagman** [comment]
Actually, reopening.  Maybe there's a way to `use_frameworks` with just the plugins.

**Comment by jmagman** [comment]
CocoaPods says no. https://github.com/CocoaPods/CocoaPods/issues/3839
I don't think there's anything add-to-app workflows can do if the plugins just don't work in Swift.

Closing again.  Please add any feedback you feel is necessary to https://github.com/flutter/flutter/issues/24099 and https://github.com/flutter/flutter/issues/25676.  Thanks!
