### ISSUE TITLE
How to make flutter use the Xcode 11 beta tools? 

### ISSUE THREAD

**Issue by Kartik-715** [flutter/flutter#40137]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

I have installed Xcode 11 beta 7 along with my old Xcode 10! Flutter still uses the old Xcode 10 to build apps and I cannot develop apps for ios 13!  I have to open Runner manually and run it! Any help?

**Comment by he2lec** [comment]
How did you solve this ?

**Comment by Kartik-715** [comment]
sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer/

**Comment by he2lec** [comment]
Using Xcode 11 and ios 13, you didn't have any issue with ˋflutter run` hot reloading ?
As described here: #40542
