### ISSUE TITLE
Flutter run slow for android on macOS

### ISSUE THREAD

**Issue by nimitwalia89** [flutter/flutter#40139]
Last week i downloaded flutter and installed flutter on my system. For IOS flutter run works fine and fast. but for android it always takes 5+ minutes. Initializing gradle always takes up 2 minutes. When i tried to setup flutter on windows it runs withing 30 seconds. 

Can any1 help with this issue? I am talking about simple app that flutter generates without any modification. Cuz spending 5 minutes on every build is way too much. Even first time run on windows is faster than macOS.

**Comment by BondarenkoStas** [comment]
@nimitwalia89 Please provide your ```flutter doctor -v``` output.

**Comment by nimitwalia89** [comment]
@BondarenkoStas Here is the output. 
`flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-IN)
    • Flutter version 1.9.1+hotfix.2 at /Users/nimtwalia/DevTools/flutter
    • Framework revision 2d2a1ffec9 (3 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nimtwalia/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/nimtwalia/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.`

Also flutter doctor command also takes long time. around 5 minutes. on windows it takes 5 seconds.

**Comment by baoxiehao** [comment]
Same problem, which seems to happen after flutter latest upgrade.

**Comment by nimitwalia89** [comment]
@BondarenkoStas Any update?

**Comment by BondarenkoStas** [comment]
@nimitwalia89 Sorry, I would like help but don't know how, I'm just doing initial issue triage. Let's wait for help.

**Comment by electricjohnsn** [comment]
I experienced the same problem: running `flutter doctor` got stuck while checking android licences for some minutes and said they were accepted afterwards (though they weren't). 
As I'm behind a corporate proxy (and cntlm) it helped to go some _proxyless_ network and run `flutter doctor --android-licenses` and then switch back. Maybe this behaviour is related to the problem described above.

However, creating a new flutter project in android studio still takes some minutes and I don't know any workaround other than going to some other network permanently. 

btw, my proxy config looks fine as far as I can tell:
```
[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost
```

**Comment by jonahwilliams** [comment]
We can't make Gradle any faster unfortunately. If you think a network proxy is interfering with it, you might try searching the interwebs, such as https://medium.com/@petehouston/execute-gradle-behind-a-corporate-proxy-network-509260961813
