### ISSUE TITLE
image_picker video recording time limit

### ISSUE THREAD

**Issue by ggichure** [flutter/flutter#40149]
## Use case
video recording based on durations  say a short video about 5 seconds long

**Comment by BondarenkoStas** [comment]
@ggichure Please describe more detailed what is your proposal and if possible some case why would you want to have it? Image_picker is still under development and probably the feature is on the roadmap already.

**Comment by ggichure** [comment]
added use case

**Comment by BondarenkoStas** [comment]
https://github.com/flutter/plugins/pull/2048
Closing as it's a duplicate. If you disagree, feel free to comment and I will reopen the issue.
