### ISSUE TITLE
Is there a way to close the listening socket and listen again on the same websocket connection.

### ISSUE THREAD

**Issue by quangkhoiuit98** [flutter/flutter#40145]
I have a parent class that contains a method to initialize a web socket and listen to it here. But I have a subclass inheriting from a superclass and redefining a function that will run when the socket receives the data, but it doesn't seem to be updating the method of the subclass itself after I've defined it.

Is there any way for websocket to listen for parent class creation automatically updated?

Thank.

**Comment by quangkhoiuit98** [comment]
parent class : 

import 'dart:async';
import 'dart:convert';

import 'package:aladin/PageData/sideMenuData.dart';
import 'package:aladin/PageData/webSocketData.dart';
import 'package:aladin/Private/Suitable.dart';
import 'package:aladin/Public/AboutUs.dart';
import 'package:aladin/Public/BlogOverview.dart';
import 'package:aladin/Public/Contact.dart';
import 'package:aladin/Public/DenyRisk.dart';
import 'package:aladin/Public/InvestorServiceTerms.dart';
import 'package:aladin/Public/Jobs.dart';
import 'package:aladin/Public/PrivacyPolicy.dart';
import 'package:aladin/Public/TraderGuide.dart';
import 'package:aladin/Public/TraderServiceTerms.dart';
import 'package:aladin/Public/TradingInstruction.dart';
import 'package:aladin/Public/InvestorListing.dart';
import 'package:aladin/Public/Login.dart';
import 'package:aladin/Public/Register.dart';
import 'package:aladin/Public/TraderListing.dart';
import 'package:aladin/Service/RootTemplateService.dart';
import 'package:aladin/Util/Network.dart';
import 'package:aladin/Util/http.dart';
import 'package:aladin/Util/notificationAction.dart';
import 'package:aladin/Util/userSession.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_speed_dial/flutter_speed_dial.dart';

class RootTemplateEvent implements RootTemplateService {
  State state;

  RootTemplateEvent(this.state);

  @override
  GlobalKey<ScaffoldState> scaffoldKey = new GlobalKey<ScaffoldState>();

  @override
  String currentTile;

  @override
  Widget currentPage;

  @override
  bool quickButtonVisible = false;

  @override
  bool isSwipeDown = true;

  @override
  bool isLogin = false;

  NotiFicationAction localNotiService;
  WebSocketPageData webSocketData = new WebSocketPageData();
  Function socketFunction;
  Timer timer;
  int notiId = 0;

  @override
  SideMenuData sideMenuData = new SideMenuData();

  @override
  Widget setTitle(String title) {
    Widget titleWidget;
    if (title == null || title.isEmpty || title == 'null') {
      currentTile = '';
      titleWidget = new Image.asset('assets/aladin_white.png',
          color: Colors.white, fit: BoxFit.fitHeight);
    } else {
      currentTile = title;
      titleWidget = Text(title);
    }

    return titleWidget;
  }

  @override
  void setCurrentPage(Widget page) {
    currentPage = page;
  }

  @override
  void setQuickButtonVisible(bool quickButtonVisibleValue) {
    quickButtonVisible = quickButtonVisibleValue;
  }

  @override
  Future<bool> exitApp() async {
    return showDialog(
        context: state.context,
        builder: (context) => AlertDialog(
              contentPadding: EdgeInsets.all(20.0),
              backgroundColor: Colors.white,
              content: Text(
                'Bạn sẽ không nhận được tín hiệu giao dịch. Bạn đồng ý đóng ứng dụng?',
                style: TextStyle(color: Colors.black),
                textAlign: TextAlign.justify,
              ),
              actions: <Widget>[
                Container(
                  child: FlatButton(
                      onPressed: () => Navigator.pop(context, false),
                      child: Text(
                        'Hủy',
                        style: TextStyle(color: Color(0xfff16731)),
                      )),
                ),
                Container(
                  margin: EdgeInsets.only(right: 10.0),
                  child: FlatButton(
                      onPressed: () => Navigator.pop(context, true),
                      child: Text(
                        'Đồng ý',
                        style: TextStyle(color: Color(0xfff16731)),
                      )),
                ),
              ],
              shape: OutlineInputBorder(
                  borderRadius: BorderRadius.all(Radius.circular(30.0))),
            ));
  }

  @override
  Widget sideMenuChooseActivePage() {
    Navigator.pop(state.context);

    GlobalKey<ScaffoldState> newScaffoldKey = new GlobalKey<ScaffoldState>();
    String before = currentPage.runtimeType.toString();
    bool isLogin = (userData != null);
    switch (sideMenuData.id) {
      case 2:
        Navigator.push(
          state.context,
          MaterialPageRoute(builder: (context) => RegisterPage()),
        );
        return null;
        break;
      case 3:
        currentTile = 'Nhà tư vấn';
        currentPage = new TraderListingPage(
          scaffoldKey: newScaffoldKey,
          isLogin: isLogin,
        );
        break;
      case 4:
        currentTile = 'Nhà đầu tư';
        currentPage = new InvestorListingPage(
          scaffoldKey: newScaffoldKey,
          isLogin: isLogin,
        );
        break;
      case 5:
        currentPage = _returnStaticPage();
        return currentPage;
        break;
      case 6:
        currentTile = 'Liên hệ';
        currentPage = new ContactPage(
          scaffoldKey: newScaffoldKey,
          isLogin: isLogin,
        );
        break;
      case 7:
        currentTile = 'Blog đầu tư';
        currentPage = new BlogOverviewPage();
        break;
      case 8:
        currentTile = 'Nhà ' +
            (userData['usertype'] == 'TRADER' ? 'đầu tư' : 'tư vấn') +
            ' phù hợp';
        currentPage = new SuitablePage(
          title: currentTile,
        );
        break;
      default:
        currentTile = '';
        currentPage = new LoginPage(
          scaffoldKey: newScaffoldKey,
        );
        break;
    }

    if (before != currentPage.runtimeType.toString()) {
      Navigator.pushReplacement(
        state.context,
        MaterialPageRoute(builder: (context) => currentPage),
      );
    }

    return currentPage;
  }

  Widget _getFAB() {
    return SpeedDial(
      animatedIcon: AnimatedIcons.menu_close,
      animatedIconTheme: IconThemeData(size: 22),
      backgroundColor: Color(0xFF801E48),
      visible: true,
      curve: Curves.bounceIn,
      children: [
        // FAB 1
        SpeedDialChild(
            child: Icon(Icons.assignment_turned_in),
            backgroundColor: Color(0xFF801E48),
            onTap: () {
              /* do anything */
            },
            label: 'Button 1',
            labelStyle: TextStyle(
                fontWeight: FontWeight.w500,
                color: Colors.white,
                fontSize: 16.0),
            labelBackgroundColor: Color(0xFF801E48)),
        // FAB 2
        SpeedDialChild(
            child: Icon(Icons.assignment_turned_in),
            backgroundColor: Color(0xFF801E48),
            onTap: () {
              state.setState(() {
                // _counter = 0;
              });
            },
            label: 'Button 2',
            labelStyle: TextStyle(
                fontWeight: FontWeight.w500,
                color: Colors.white,
                fontSize: 16.0),
            labelBackgroundColor: Color(0xFF801E48))
      ],
    );
  }

  void quickButtonRedirectPageEvent(Widget pageRoute) {
    Navigator.push(
      state.context,
      MaterialPageRoute(builder: (context) => pageRoute),
    );
  }

  Widget _returnStaticPage() {
    GlobalKey<ScaffoldState> newScaffoldKey = new GlobalKey<ScaffoldState>();
    Widget returnPage;

    bool isLogin = (userData != null);
    switch (sideMenuData.subIndex) {
      case 0:
        if (sideMenuData.subTabIndex == 0) {
          currentTile = 'Hướng dẫn nhà tư vấn';
          returnPage = new TraderGuidePage(
            scaffoldKey: newScaffoldKey,
            title: currentTile,
            isLogin: isLogin,
          );
        } else {
          currentTile = 'Hướng dẫn nhà đầu tư';
          returnPage = new TradingInstructionPage(
            scaffoldKey: newScaffoldKey,
            title: currentTile,
            isLogin: isLogin,
          );
        }
        break;
      case 1:
        if (sideMenuData.subTabIndex == 0) {
          currentTile = 'Giới thiệu về chúng tôi';
          returnPage = new AboutUsPage(
            scaffoldKey: newScaffoldKey,
            title: currentTile,
            isLogin: isLogin,
          );
        } else {
          currentTile = 'Nghề nghiệp';
          returnPage = new JobsPage(
            scaffoldKey: newScaffoldKey,
            title: currentTile,
            isLogin: isLogin,
          );
        }
        break;
      case 2:
        if (sideMenuData.subTabIndex == 0) {
          currentTile = 'Chính sách bảo mật';
          returnPage = new PrivacyPolicyPage(
            scaffoldKey: newScaffoldKey,
            title: currentTile,
            isLogin: isLogin,
          );
        } else {
          currentTile = 'Khước từ rủi ro';
          returnPage = new DenyRiskPage(
            scaffoldKey: newScaffoldKey,
            title: currentTile,
            isLogin: isLogin,
          );
        }
        break;
      case 3:
        if (sideMenuData.subTabIndex == 0) {
          currentTile = 'Điều khoản nhà đầu tư';
          returnPage = new InvestorServiceTermsPage(
            scaffoldKey: newScaffoldKey,
            title: currentTile,
            isLogin: isLogin,
          );
        } else {
          currentTile = 'Điều khoản nhà tư vấn';
          returnPage = new TraderServiceTermsPage(
            scaffoldKey: newScaffoldKey,
            title: currentTile,
            isLogin: isLogin,
          );
        }
        break;
    }

    Navigator.pushReplacement(
      state.context,
      MaterialPageRoute(builder: (context) => returnPage),
    );
    return returnPage;
  }

  @override
  void setScaffoldKey(GlobalKey<ScaffoldState> key) {
    scaffoldKey = key;
  }

  @override
  Map<String, dynamic> userData;

  @override
  Future<Map<String, dynamic>> getUserData() async {
    return await UserSession(scaffoldKey).getLoggedUser();
  }

  @override
  void setUserData(Map<String, dynamic> data) {
    userData = data;
  }

  void preload() {
    UserSession(scaffoldKey).checkAuthen((value) {}).then((value) {
      state.setState(() {
        isLogin = value;
      });
      setQuickButtonVisible(value);
    });

    getUserData().then((value) {
      state.setState(() {
        setUserData(value);
      });
      _getSessionID();
      localNotiService = new NotiFicationAction(
          currentContext: state.context,
          localNoti: new FlutterLocalNotificationsPlugin(),
          redirectPage: () {});
      localNotiService.preLoadLocalnoti();
    });
  }

  //websocket

  void _registerAndAddReconnect(Map<String, dynamic> content) {
    webSocketData.snbSession = content['sessionid'];

    print(socketFunction('da'));
    sendRegisterAndAddEvent();

    timer = new Timer.periodic(new Duration(seconds: 48), (timer) {
      int closeCode = webSocketData.webSocketChannel.closeCode;
      if (closeCode != null) {
        print('do reconnect');
        webSocketData.ReconnectWhenClosed();
        sendRegisterAndAddEvent();
      } else {
        webSocketData.webSocketChannel.sink
            .add('{type: "register", content: "' + content['sessionid'] + '"}');
      }
      print(webSocketData.webSocketChannel.hashCode);
      debugPrint(timer.tick.toString());
    });
  }

  void sendRegisterAndAddEvent() {
    webSocketData.webSocketChannel.sink
        .add('{type: "register", content: "' + webSocketData.snbSession + '"}');

    // webSocketData.webSocketChannel.stream.listen(setIdAndShowNoti);

    print('123456');

    webSocketData.webSocketChannel.stream.forEach((data) {
      setIdAndShowNoti(data);

      print(this.socketFunction == null);
      this.socketFunction(data);
    });
  }

  void setIdAndShowNoti(dynamic data) {
    localNotiService.showNotificationWithDefaultSound(
        notiId, data, /*template_1Event.getNumUnseenNoti*/ () {});
    notiId += 1;
  }

  void _getSessionID() async {
    bool isConnected = await Session().checkInternetConnection();
    if (isConnected) {
      Post response =
          await Session().createPost('/authenapi/userapi/getSessionId', '{}');
      if (response.result == 'success') {
        Map<String, dynamic> content = Map.from(json.decode(response.content));

        _registerAndAddReconnect(content);
      } else {}
    } else {
      Network(scaffoldKey).noticeCheckConnection();
    }
  }
}

**Comment by BondarenkoStas** [comment]
@quangkhoiuit98 I guess it's a good question for StackOverflow, I would advise you to post it there as well, help there may come faster.
Please provide your ```flutter doctor -v``` output.

**Comment by quangkhoiuit98** [comment]
> @quangkhoiuit98 I guess it's a good question for StackOverflow, I would advise you to post it there as well, help there may come faster.
> Please provide your `flutter doctor -v` output.

Thank you so much
