### ISSUE TITLE
Archiving my flutter Project in Xcode fails because of .h file not found

### ISSUE THREAD

**Issue by Antonwy** [flutter/flutter#40143]
I'm trying to upload my flutter app to the app store. Everything works except archiving the project in XCode. Everytime I try to archive the project, I get the error `'firebase_ml_vision/FirebaseMlVisionPlugin.h' file not found`.
```
[✓] Flutter (Channel beta, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale de-DE)
    • Flutter version 1.9.1+hotfix.2 at /Users/antonwy/FlutterProjects/flutter
    • Framework revision 2d2a1ffec9 (3 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/antonwy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.0, Build version 11M374r
    • CocoaPods version 1.7.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] VS Code (version 1.31.1)
    • VS Code at /Users/antonwy/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPhone 8 • 2243E9B1-B00B-4E7D-821D-0191F5B56C60 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!
```

**Comment by BondarenkoStas** [comment]
Will just copy the link to your SO question for other reviewers https://stackoverflow.com/questions/57868563/archiving-my-flutter-project-in-xcode-fails-because-of-h-file-not-found

@Antonwy Can you come up with a small self-contained app that demonstrates the problem? You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by Antonwy** [comment]
@BondarenkoStas Hey! Thanks for the help... The Problem is, I really don't know whats the problem and why its not working... Its probably something referring to IOS and the Podfile... but I don't know how to replicate the error...

https://github.com/Antonwy/vocabulary_scanner This is the App... You can try archiving it... the only thing you must add is the GoogleService-Info.plist file!

**Comment by kroikie** [comment]
@Antonwy

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/339. Any further collaboration will be done there.
