### ISSUE TITLE
zsh: command not found: flutter - macOS

### ISSUE THREAD

**Issue by abtisam** [flutter/flutter#40140]
I have added path in .bash_profile but unfortunately, it doesn't work. I have gone through multiple articles & stackoverflow post but nothing helps. Please suggest, how can I add this path permanently. 
When ever I need to run flutter app I need to add path in terminal.
Given below is the complete .bash_profile

source ~/.bash_profile#export JAVA_HOME=$(/usr/libexec/java_home)
export ANDROID_HOME=/Users/$USER/Library/Android/sdk
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export PATH=$PATH:/Users/air/Documents/development/flutter/bin

**Comment by stuartmorgan** [comment]
You need to use .zshrc if you are using zsh; see https://flutter.dev/docs/get-started/install/macos#update-your-path

**Comment by abtisam** [comment]
@stuartmorgan I have used .zshrc and works fine. But I just need to understand one thing that I am working on mojave and according to the flutter docs, I used .bash_profile. Whereas, .zshrc is for Catalina.

**Comment by stuartmorgan** [comment]
As the docs say (emphasis added):
> Open (or create) the rc file *for your shell*. For example, Linux and Mac OS Mojave (and earlier) use the Bash shell *by default*

.zshrc is for zsh, not for Catalina specifically. If you are using a non-default shell on Mojave, then you the *default* instructions for Mojave don't apply to your case.

**Comment by Sarmed-armis** [comment]
Dears i have same issue when i upgrade to catalina  so how to solve that please

**Comment by abtisam** [comment]
@Sarmed-armis If you are using bash terminal then you should update the .bash_profile & if you are using zsh terminal then you should update path variables in .zsh file.
One more work around, you can change default terminal. For this, please have a look below:
https://support.apple.com/lt-lt/guide/terminal/trml113/mac

**Comment by amitmishra0807** [comment]
Please update your flutter path.  https://flutter.dev/docs/get-started/install/macos#update-your-path

**Comment by ErangaHeshan** [comment]
For me removing double quotes did the fix.
Try changing `export PATH="$PATH:~/development/flutter/bin"` into `export PATH=$PATH:~/development/flutter/bin`

**Comment by CaicoLeung** [comment]
> For me removing double quotes did the fix.
> Try changing `export PATH="$PATH:~/development/flutter/bin"` into `export PATH=$PATH:~/development/flutter/bin`

This worked for me
