### ISSUE TITLE
Graphical glitches in flutter UI

### ISSUE THREAD

**Issue by erikhric** [flutter/flutter#40169]
I'm experiencing weird graphical glitches in my flutter app at random times.
Screenshot:
![IMG_2529](https://user-images.githubusercontent.com/5880119/64641983-96223b80-d40d-11e9-9846-4072f63006af.JPG)

Device: iPhone X, iOS 12.4.1
flutter doctor output:

> flutter doctor --verbose
> [✓] Flutter (Channel beta, v1.8.3, on Mac OS X 10.14.6 18G95, locale en-SK)
>     • Flutter version 1.8.3 at /Users/erikhric/Tools/flutter/flutter
>     • Framework revision e4ebcdf6f4 (6 weeks ago), 2019-07-27 11:48:24 -0700
>     • Engine revision 38ac5f30a7
>     • Dart version 2.5.0 (build 2.5.0-dev.1.0 0ca1582afd)
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
>     • Android SDK at /Users/erikhric/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.1
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 10.3)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.3, Build version 10G8
>     • CocoaPods version 1.7.4
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 39.0.3
>     • Dart plugin version 191.8423
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] VS Code (version 1.37.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.3.0
> 
> [!] Connected device
>     ! No devices available
> 
> ! Doctor found issues in 2 categories.

**Comment by BondarenkoStas** [comment]
@erikhric I would be great if you can come up with a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.
It may be very hard to investigate it if it's just random.

**Comment by erikhric** [comment]
@BondarenkoStas I updated everything I could to the latest version and I'm not able to reproduce the bug again. I'll let you know when it'll appear again.
Thank you and keep up good work :)

**Comment by BondarenkoStas** [comment]
@erikhric Then we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don’t hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
