### ISSUE TITLE
Need to version devicelab infrastructure in a way that is visible to benchmarks

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#40162]
Some change to devicelab hardware, software versions, or other configuration is the likely culprit for https://github.com/flutter/flutter/issues/40111. Nevertheless, it appears as if a trivial change to a web debugging library is the culprit.

updates to the devicelab should be captured in the dashboard or benchmarks, so that large swings in performance could be correctly attributed.

**Comment by jonahwilliams** [comment]
cc @tvolkert

**Comment by tvolkert** [comment]
@godofredoc

**Comment by kf6gpe** [comment]
cc @kf6gpe

**Comment by godofredoc** [comment]
Devicelab is deprecated and code is being removed. Marking this one as obsolete.
