### ISSUE TITLE
Proguard error after upgrating stable to v1.9.1+hotfix.2

### ISSUE THREAD

**Issue by yaymalaga** [flutter/flutter#40168]
I am using the stable channel, and I have just upgraded to the new 1.9.1 version, also in stable. Previously my app could compile without any problem, but just after the upgrade, flutter build apk command has stopped working to due ProGuard errors:
```
Warning: io.flutter.embedding.android.FlutterView: can't find referenced method 'android.graphics.Insets getSystemGestureInsets()' in library class android.view.WindowInsets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced method 'android.graphics.Insets getSystemGestureInsets()' in library class android.view.WindowInsets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets
```

My flutter doctor output is:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.9.1+hotfix.2 at /home/yaymalaga/Android/flutter
    • Framework revision 2d2a1ffec9 (4 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /home/yaymalaga/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /home/yaymalaga/Downloads/android-studio-ide-191.5791312-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/yaymalaga/Downloads/android-studio-ide-191.5791312-linux/android-studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 3.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

This is the same error as #39883, but in that case it was the dev channel. I just opened this issue to show that this bug is still present in the stable channel, what is really a shame. As a workaround, it could be fixed by modifying proguard-rules.pro to skip io.flutter.embedding.** and io.flutter.view.**.

**Comment by RenanDelfanti** [comment]
Same error for me.

**Comment by ReginFell** [comment]
Same error, as a workaround you could ignore android related warnings by `-dontwarn android.**`

**Comment by dalebulmer** [comment]
Same error on new stable version

**Comment by pipinfitriadi** [comment]
> Same error, as a workaround you could ignore android related warnings by `-dontwarn android.**`

Thanks @ReginFell .. your solution are the best so far.

**Comment by ashutoshkmr** [comment]
@yaymalaga  Had same issue
Upgrading gradle to 3.5.0 worked for me

**Comment by quanixstudio** [comment]
> @yaymalaga Had same issue
> Upgrading gradle to 3.5.0 worked for me

This fixed it for me too

**Comment by yaymalaga** [comment]
I tried upgrading gradle following #40181. I can confirm that it now builds, but proguard warnings and related messages have also disappeared. The output size is also bigger, so it seems as if proguard was not being used.

**Comment by TheVinhLuong** [comment]
@ashutoshkmr Did you have to change `gradle-wrapper.properties`'s `distributionUrl` to gradle version 5? I have a warning with content like that after upgrade gradle to 3.5 and just wonder if it is safe to change it.

**Comment by limzhipeng-kumoten** [comment]
> Same error, as a workaround you could ignore android related warnings by `-dontwarn android.**`

This worked for my case. Thanks.

**Comment by grandpa-guru** [comment]
Indeed changing gradle version to 3.5.0 works but it brings a new problem which can be bypassed by following https://github.com/flutter/flutter/issues/38934#issuecomment-523548897.

**Comment by rajeshjeshar** [comment]
Thae following changes solved the issue as @ashutoshkmr  and @realvotum said
**Project level build.gradle**
changed `'com.android.tools.build:gradle:3.3.0'` to `'com.android.tools.build:gradle:3.5.0'` 

**In gradle-wrapper.properties**

`https\://services.gradle.org/distributions/gradle-4.10.2-all.zip` to  `https://services.gradle.org/distributions/gradle-5.4.1-all.zip`

**Comment by RenanDelfanti** [comment]
> Thae following changes solved the issue as @ashutoshkmr and @realvotum said
> **Project level build.gradle**
> changed `'com.android.tools.build:gradle:3.3.0'` to `'com.android.tools.build:gradle:3.5.0'`
> 
> **In gradle-wrapper.properties**
> 
> `https\://services.gradle.org/distributions/gradle-4.10.2-all.zip` to `https://services.gradle.org/distributions/gradle-5.4.1-all.zip`

When changed this, works to build apk, but aab fails.

**Comment by rajeshjeshar** [comment]
> > Thae following changes solved the issue as @ashutoshkmr and @realvotum said
> > **Project level build.gradle**
> > changed `'com.android.tools.build:gradle:3.3.0'` to `'com.android.tools.build:gradle:3.5.0'`
> > **In gradle-wrapper.properties**
> > `https\://services.gradle.org/distributions/gradle-4.10.2-all.zip` to `https://services.gradle.org/distributions/gradle-5.4.1-all.zip`
> 
> When changed this, works to build apk, but aab fails.

Yes the abb fails only the split apk alone itself works

**Comment by brianmituka** [comment]
> -dontwarn android.**

This worked for me

**Comment by gurmukhp** [comment]
> > > Thae following changes solved the issue as @ashutoshkmr and @realvotum said
> > > **Project level build.gradle**
> > > changed `'com.android.tools.build:gradle:3.3.0'` to `'com.android.tools.build:gradle:3.5.0'`
> > > **In gradle-wrapper.properties**
> > > `https\://services.gradle.org/distributions/gradle-4.10.2-all.zip` to `https://services.gradle.org/distributions/gradle-5.4.1-all.zip`
> > 
> > 
> > When changed this, works to build apk, but aab fails.
> 
> Yes the abb fails only the split apk alone itself works

Any idea how to fix for split? Or a workaround?

**Comment by realvotum** [comment]
@gurmukhp check @grandpa-guru response from above, flutter tool produces an error while building app bundle, still the bundle is generated in the output directory. I released such a bundle to the play store with no issues, it updated the app version for my users.

Reminder: there is another ongoing issue with v1.9.1 flutter version [https://github.com/flutter/flutter/issues/36130](url) which I discovered after my users downloaded the version build with v1.9.1 flutter tool, mainly in Galaxy 4+ and Galaxy 6+. So I decided to revert to flutter v1.7.1 and build my app older but not that problematic flutter version which solved the issue with OpenGL. This is my experience with v1.9.1, careful guys :)

**Comment by gurmukhp** [comment]
> @gurmukhp check @grandpa-guru response from above, flutter tool produces an error while building app bundle, still the bundle is generated in the output directory. I released such a bundle to the play store with no issues, it updated the app version for my users.
> 
> Reminder: there is another ongoing issue with v1.9.1 flutter version [https://github.com/flutter/flutter/issues/36130](url) which I discovered after my users downloaded the version build with v1.9.1 flutter tool, mainly in Galaxy 4+ and Galaxy 6+. So I decided to revert to flutter v1.7.1 and build my app older but not that problematic flutter version which solved the issue with OpenGL. This is my experience with v1.9.1, careful guys :)

Thank you for the explanation, it wasn't clear that the build passed due to the wall of red text!

**Comment by realvotum** [comment]
@gurmukhp No prob, yet I got only one red error from the flutter build tool that app bundle build failed, if u got more than that, it may be another case that I am not aware of, hope it's not :D

**Comment by VladyslavBondarenko** [comment]
Since [solution](https://github.com/flutter/flutter/issues/40168#issuecomment-530895358) were proposed 
I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
