### ISSUE TITLE
TextField with TextEditingController will clear inputted data when keyboard closed

### ISSUE THREAD

**Issue by samuelg123** [flutter/flutter#40172]
Hi,
I discovered a problem. TextField with TextEditingController will clear inputted data when keyboard closed using Keyboard Done Button [ ✓ ].

Flutter version: 1.9.1+hotfix.2

## Steps to Reproduce
![ezgif com-resize (1)](https://user-images.githubusercontent.com/12625711/64642885-7ef94300-d439-11e9-9ac7-8d79d9143bed.gif)

## Sample Code
```
TextEditingController _ctr = TextEditingController();

TextField(
    controller: _ctr,
    decoration: InputDecoration(hintText: "Input Key"),
);
```
Thank you.

**Comment by HansMuller** [comment]
It would help if you would provide the output of `flutter doctor` and a small self-contained app that demonstrates the problem. Note also: https://gist.github.com/ is a useful way to share the code.

**Comment by HansMuller** [comment]
Thanks for the update, I'll close this issue.
