### ISSUE TITLE
Support for verifying that animations have finished in a test

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4017]
In a test like the following the expect() call assumes that we've waited long enough for all of the animations to have finished.  It would nice to be able to add an expect() statement which verified that animations had really stopped.

```
    fling(-1.0);
    await tester.pump();
    await tester.pump(const Duration(seconds: 2));
    expect(scrollOffset, closeTo(0.0, 1.0));
```

**Comment by Hixie** [comment]
Basically this bug is asking for a shorthand for:
```
expect(SchedulerBinding.instance.hasScheduledFrame, isFalse);
```
I suggest providing a getter on the tester object called "hasRunningAnimations" so that you would do:
```
expect(tester.hasRunningAnimations, isFalse);
```

Another useful shorthand would be something for:
```
while (SchedulerBinding.instance.hasScheduledFrame)
   await tester.pump();
```
I propose to add this as `await tester.pumpUntilAnimationsComplete();` or some such.
