### ISSUE TITLE
Test Finished victory declaration is pretty small

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4018]
This isn't super important :-).

![test_finished](https://cloud.githubusercontent.com/assets/1377460/15373337/fa560ea2-1cf9-11e6-9f9a-316d0ebea163.png)

**Comment by eseidelGoogle** [comment]
Where are the balloons?

**Comment by Hixie** [comment]
definitely not adding balloons -- this should really just be black text, anything we add increases the likelihood of some hard-to-debug issues. But I can make the font size slightly bigger.
