### ISSUE TITLE
Build engine with Xcode 11

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#40198]
Starting April 2020, all new apps and app updates will need to be built with the iOS 13 SDK.

https://developer.apple.com/news/?id=09102019a

**Comment by cbracken** [comment]
I'm unlikely to look at this this week, but hope to get a chance to take a look next week. If someone else wants to grab it in the meantime, it's theirs :)

**Comment by gaaclarke** [comment]
@cbracken can you point to where this is controlled?  This is just the matter of updating xcode on some build machine?

**Comment by gaaclarke** [comment]
@Hixie is this going to be an issue for Flutter?  The announcement talks about the requirement for apps.  All that should matter is what version of Xcode a user has on their machine.

**Comment by Hixie** [comment]
Hard to say, sometimes they care about what frameworks are built with too. This is more about removing all doubt than about a specific known risk.

**Comment by LongCatIsLooong** [comment]
Closing now that the manual engine roll has landed and the post submit checks seem to be passing.
