### ISSUE TITLE
NoSuchMethodError, The method '[]' was called on null

### ISSUE THREAD

**Issue by creativeminds22** [flutter/flutter#40199]
I build my application with success.
But when i open it on my phone i have red screen with this.
nosuchmethoderror: the method '[]' was colled on null. 
receiver: null 
Tried calling: []("setting")

Please help me

**Comment by creativeminds22** [comment]
This is the code of my : settings.dart
`import 'package:flutter/material.dart';
import 'package:intercom_flutter/intercom_flutter.dart';
import 'package:notification_permissions/notification_permissions.dart';
import 'package:provider/provider.dart';
import 'package:rate_my_app/rate_my_app.dart';

import '../common/config.dart' as config;
import '../common/constants.dart';
import '../common/styles.dart';
import '../generated/i18n.dart';
import '../models/app.dart';
import '../models/user.dart';
import '../models/wishlist.dart';
import '../screens/chat/chat_list_by_admin.dart';
import '../widgets/smartchat.dart';
import 'language.dart';
import 'notification.dart';

class SettingScreen extends StatefulWidget {
  final User user;
  final VoidCallback onLogout;

  SettingScreen({this.user, this.onLogout});

  @override
  State<StatefulWidget> createState() {
    return SettingScreenState();
  }
}

class SettingScreenState extends State<SettingScreen>
    with TickerProviderStateMixin, WidgetsBindingObserver {
  final bannerHigh = 200.0;
  bool enabledNotification = true;

  RateMyApp _rateMyApp = RateMyApp(
    minDays: 7,
    minLaunches: 10,
    remindDays: 7,
    remindLaunches: 10,
  );

  @override
  void initState() {
    super.initState();

    Future.delayed(Duration.zero, ()async{
      if (config.kIntercomAPIKey['appID'] != null)
        await Intercom.initialize('${config.kIntercomAPIKey['appID']}',
          iosApiKey: '${config.kIntercomAPIKey['ios']}',
          androidApiKey: '${config.kIntercomAPIKey['android']}');

      checkNotificationPermission();
    });
  }

  void checkNotificationPermission() async {
    try {
      NotificationPermissions.getNotificationPermissionStatus().then((status) {
        if (mounted)
          setState(() {
            enabledNotification = status == PermissionStatus.granted;
          });
      });
    } catch (err) {
//      print(err);
    }
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      checkNotificationPermission();
    }
  }

  @override
  Widget build(BuildContext context) {
    final wishListCount = Provider.of<WishListModel>(context).products.length;

    return Scaffold(
      backgroundColor: Theme.of(context).backgroundColor,
      floatingActionButton: (widget.user.username == config.adminEmail)
          ? FloatingActionButton(
              backgroundColor: Theme.of(context).primaryColor,
              onPressed: () {
                Navigator.push(context,
                    MaterialPageRoute(builder: (context) => ListChat(user: widget.user))); //
              },
              child: Icon(
                Icons.chat,
                size: 22,
              ),
            )
          : SmartChat(user: widget.user),
      body: CustomScrollView(
        slivers: <Widget>[
          SliverAppBar(
            backgroundColor: Color(0xFF0084C9),
            leading: IconButton(
              icon: Icon(
                Icons.blur_on,
                color: Colors.white70,
              ),
              onPressed: () {
                Scaffold.of(context).openDrawer();
              },
            ),
            expandedHeight: bannerHigh,
            floating: true,
            pinned: true,
            flexibleSpace: FlexibleSpaceBar(
                title: Text(S.of(context).settings,
                    style:
                        TextStyle(fontSize: 18, color: Colors.white, fontWeight: FontWeight.w600)),
                background: Image.network(
                  kProfileBackground,
                  fit: BoxFit.cover,
                )),
          ),
          SliverList(
            delegate: SliverChildListDelegate(
              <Widget>[
                Padding(
                  padding: const EdgeInsets.all(15.0),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      SizedBox(
                        height: 10.0,
                      ),
                      ListTile(
                        leading: widget.user.picture != null
                            ? CircleAvatar(backgroundImage: NetworkImage(widget.user.picture))
                            : Icon(Icons.face),
                        title: Text(widget.user.name, style: TextStyle(fontSize: 16)),
                      ),
                      ListTile(
                        leading: Icon(Icons.email),
                        title: Text(widget.user.email, style: TextStyle(fontSize: 16)),
                      ),
                      SizedBox(height: 30.0),
                      Text(S.of(context).generalSetting,
                          style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600)),
                      SizedBox(height: 10.0),
                      Card(
                        margin: EdgeInsets.only(bottom: 2.0),
                        elevation: 0,
                        child: ListTile(
                          leading: Image.asset(
                            'assets/icons/profile/icon-heart.png',
                            width: 20,
                            color: Theme.of(context).accentColor,
                          ),
                          title: Text(S.of(context).myWishList, style: TextStyle(fontSize: 15)),
                          trailing: Row(mainAxisSize: MainAxisSize.min, children: [
                            if (wishListCount > 0)
                              Text(
                                "$wishListCount ${S.of(context).items}",
                                style:
                                    TextStyle(fontSize: 14, color: Theme.of(context).primaryColor),
                              ),
                            SizedBox(width: 5),
                            Icon(Icons.arrow_forward_ios, size: 18, color: kGrey600)
                          ]),
                          onTap: () {
                            Navigator.pushNamed(context, "/wishlist");
                          },
                        ),
                      ),
                      Divider(
                        color: Colors.black12,
                        height: 1.0,
                        indent: 75,
                        //endIndent: 20,
                      ),
                      Card(
                        margin: EdgeInsets.only(bottom: 2.0),
                        elevation: 0,
                        child: SwitchListTile(
                          secondary: Image.asset(
                            'assets/icons/profile/icon-notify.png',
                            width: 25,
                            color: Theme.of(context).accentColor,
                          ),
                          value: enabledNotification,
                          activeColor: Color(0xFF0066B4),
                          onChanged: (bool value) {
                            if (value) {
                              NotificationPermissions.requestNotificationPermissions(
                                      const NotificationSettingsIos(
                                          sound: true, badge: true, alert: true))
                                  .then((_) {
                                checkNotificationPermission();
                              });
                            }
                            setState(() {
                              enabledNotification = value;
                            });
                          },
                          title: Text(
                            S.of(context).getNotification,
                            style: TextStyle(fontSize: 16),
                          ),
                        ),
                      ),
                      Divider(
                        color: Colors.black12,
                        height: 1.0,
                        indent: 75,
                        //endIndent: 20,
                      ),
                      enabledNotification
                          ? Card(
                              margin: EdgeInsets.only(bottom: 2.0),
                              elevation: 0,
                              child: GestureDetector(
                                onTap: () {
                                  Navigator.push(context,
                                      MaterialPageRoute(builder: (context) => Notifications()));
                                },
                                child: ListTile(
                                  leading: Icon(
                                    Icons.list,
                                    size: 24,
                                    color: Theme.of(context).accentColor,
                                  ),
                                  title: Text(S.of(context).listMessages),
                                  trailing: Icon(
                                    Icons.arrow_forward_ios,
                                    size: 18,
                                    color: kGrey600,
                                  ),
                                ),
                              ),
                            )
                          : Container(),
                      enabledNotification
                          ? Divider(
                              color: Colors.black12,
                              height: 1.0,
                              indent: 75,
                              //endIndent: 20,
                            )
                          : Container(),
                      Divider(
                        color: Colors.black12,
                        height: 1.0,
                        indent: 75,
                        //endIndent: 20,
                      ),
                      Card(
                        margin: EdgeInsets.only(bottom: 2.0),
                        elevation: 0,
                        child: GestureDetector(
                          onTap: () {
                            Navigator.push(
                                context, MaterialPageRoute(builder: (context) => Language()));
                          },
                          child: ListTile(
                            leading: Icon(
                              Icons.language,
                              color: Theme.of(context).accentColor,
                              size: 24,
                            ),
                            title: Text(S.of(context).language),
                            trailing: Icon(
                              Icons.arrow_forward_ios,
                              size: 18,
                              color: kGrey600,
                            ),
                          ),
                        ),
                      ),
                      Divider(
                        color: Colors.black12,
                        height: 1.0,
                        indent: 75,
                        //endIndent: 20,
                      ),
                      Card(
                        margin: EdgeInsets.only(bottom: 2.0),
                        elevation: 0,
                        child: SwitchListTile(
                          secondary: Icon(
                            Icons.dashboard,
                            color: Theme.of(context).accentColor,
                            size: 24,
                          ),
                          value: Provider.of<AppModel>(context).darkTheme,
                          activeColor: Color(0xFF0066B4),
                          onChanged: (bool value) {
                            if (value) {
                              Provider.of<AppModel>(context).updateTheme(true);
                            } else
                              Provider.of<AppModel>(context).updateTheme(false);
                          },
                          title: Text(
                            S.of(context).darkTheme,
                            style: TextStyle(fontSize: 16),
                          ),
                        ),
                      ),
                      SizedBox(height: 30.0),
                      Text(S.of(context).orderDetail,
                          style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600)),
                      SizedBox(height: 10.0),
                      GestureDetector(
                        onTap: () {
                          Navigator.pushNamed(context, "/orders");
                        },
                        child: Card(
                          margin: EdgeInsets.only(bottom: 2.0),
                          elevation: 0,
                          child: ListTile(
                            leading: Icon(
                              Icons.history,
                              color: Theme.of(context).accentColor,
                              size: 24,
                            ),
                            title: Text(S.of(context).orderHistory, style: TextStyle(fontSize: 16)),
                            trailing: Icon(Icons.arrow_forward_ios, size: 18, color: kGrey600),
                          ),
                        ),
                      ),
                      Divider(
                        color: Colors.black12,
                        height: 1.0,
                        indent: 75,
                        //endIndent: 20,
                      ),
                      Card(
                        margin: EdgeInsets.only(bottom: 2.0),
                        elevation: 0,
                        child: ListTile(
                          onTap: () {
                            _rateMyApp.showRateDialog(context).then((v) => setState(() {}));
                          },
                          leading: Image.asset(
                            'assets/icons/profile/icon-star.png',
                            width: 24,
                            color: Theme.of(context).accentColor,
                          ),
                          title: Text(S.of(context).rateTheApp, style: TextStyle(fontSize: 16)),
                          trailing: Icon(Icons.arrow_forward_ios, size: 18, color: kGrey600),
                        ),
                      ),
                      Divider(
                        color: Colors.black12,
                        height: 1.0,
                        indent: 75,
                        //endIndent: 20,
                      ),
                      Card(
                        margin: EdgeInsets.only(bottom: 2.0),
                        elevation: 0,
                        child: ListTile(
                          onTap: widget.onLogout,
                          leading: Image.asset(
                            'assets/icons/profile/icon-logout.png',
                            width: 24,
                            color: Theme.of(context).accentColor,
                          ),
                          title: Text(S.of(context).logout, style: TextStyle(fontSize: 16)),
                          trailing: Icon(Icons.arrow_forward_ios, size: 18, color: kGrey600),
                        ),
                      ),
                    ],
                  ),
                )
              ],
            ),
          ),
        ],
      ),
    );
  }
}
`

**Comment by creativeminds22** [comment]
My logcat


09-11 05:16:46.916 9402-9402/? E/Zygote: MountEmulatedStorage()
09-11 05:16:46.916 9402-9402/? E/Zygote: v2
09-11 05:16:46.916 9402-9402/? I/libpersona: KNOX_SDCARD checking this for 10270
09-11 05:16:46.916 9402-9402/? I/libpersona: KNOX_SDCARD not a persona
09-11 05:16:46.916 9402-9402/? I/SELinux: Function: selinux_compare_spd_ram, SPD-policy is existed. and_ver=SEPF_SM-A300FU_5.0.2-1 ver=51
09-11 05:16:46.926 9402-9402/? I/SELinux: Function: selinux_compare_spd_ram , priority [1] , priority version is VE=SEPF_SM-A300FU_5.0.2-1_0051
09-11 05:16:46.926 9402-9402/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
09-11 05:16:46.926 9402-9402/? I/art: Late-enabling -Xcheck:jni
09-11 05:16:47.056 9402-9402/? D/TimaKeyStoreProvider: TimaSignature is unavailable
09-11 05:16:47.066 9402-9402/? D/ActivityThread: Added TimaKeyStore provider
09-11 05:16:47.556 9402-9402/com.sedjromediasolution.onaayo W/ActivityThread: Application com.sedjromediasolution.onaayo can be debugged on port 8100...
09-11 05:16:47.876 9402-9432/com.sedjromediasolution.onaayo W/ResourcesManager: Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
09-11 05:16:47.876 9402-9432/com.sedjromediasolution.onaayo W/ResourcesManager: Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
09-11 05:16:47.976 9402-9432/com.sedjromediasolution.onaayo V/FA: Deferring to Google Analytics for Firebase for event data collection. https://goo.gl/J1sWQy
09-11 05:16:48.086 9402-9432/com.sedjromediasolution.onaayo I/DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:20461
09-11 05:16:48.086 9402-9432/com.sedjromediasolution.onaayo I/DynamiteModule: Selected remote version of com.google.android.gms.ads.dynamite, version >= 20461
09-11 05:16:48.086 9402-9432/com.sedjromediasolution.onaayo V/DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
09-11 05:16:48.146 9402-9452/com.sedjromediasolution.onaayo W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
09-11 05:16:48.406 9402-9454/com.sedjromediasolution.onaayo W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
09-11 05:16:48.436 9402-9402/com.sedjromediasolution.onaayo I/FirebaseInitProvider: FirebaseApp initialization successful
09-11 05:16:48.446 9402-9454/com.sedjromediasolution.onaayo I/FirebaseAuth: [FirebaseAuth:] Preparing to create service connection to gms implementation
09-11 05:16:48.606 9402-9426/com.sedjromediasolution.onaayo W/art: Suspending all threads took: 70.525ms
09-11 05:16:48.616 9402-9426/com.sedjromediasolution.onaayo I/art: Background sticky concurrent mark sweep GC freed 18889(1192KB) AllocSpace objects, 10(171KB) LOS objects, 12% free, 6MB/7MB, paused 73.736ms total 297.507ms
09-11 05:16:48.816 9402-9473/com.sedjromediasolution.onaayo I/FA: App measurement is starting up, version: 16250
09-11 05:16:48.816 9402-9473/com.sedjromediasolution.onaayo I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
09-11 05:16:48.816 9402-9473/com.sedjromediasolution.onaayo I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.sedjromediasolution.onaayo
09-11 05:16:48.816 9402-9402/com.sedjromediasolution.onaayo W/ContextImpl: Failed to ensure directory: /storage/extSdCard/Android/data/com.sedjromediasolution.onaayo/cache
09-11 05:16:48.826 9402-9402/com.sedjromediasolution.onaayo W/ContextImpl: Failed to ensure directory: /storage/extSdCard/Android/data/com.sedjromediasolution.onaayo/files
09-11 05:16:49.026 9402-9426/com.sedjromediasolution.onaayo W/art: Suspending all threads took: 170.422ms
09-11 05:16:49.046 9402-9426/com.sedjromediasolution.onaayo I/art: Background partial concurrent mark sweep GC freed 7874(494KB) AllocSpace objects, 4(64KB) LOS objects, 40% free, 7MB/12MB, paused 186.157ms total 329.802ms
09-11 05:16:49.186 9402-9482/com.sedjromediasolution.onaayo I/System.out: (HTTPLog)-Static: SBServiceAPI: getService class android.os.ServiceManager
09-11 05:16:49.186 9402-9482/com.sedjromediasolution.onaayo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
09-11 05:16:49.186 9402-9482/com.sedjromediasolution.onaayo I/System.out: (HTTPLog)-Static: isShipBuild true
09-11 05:16:49.186 9402-9482/com.sedjromediasolution.onaayo I/System.out: (HTTPLog)-Thread-6173-692544410: SmartBonding Enabling is false, SHIP_BUILD is true, log to file is false, DBG is false
09-11 05:16:49.186 9402-9482/com.sedjromediasolution.onaayo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
09-11 05:16:49.266 9402-9402/com.sedjromediasolution.onaayo D/PhoneWindow: *FMB* installDecor mIsFloating : false
09-11 05:16:49.266 9402-9402/com.sedjromediasolution.onaayo D/PhoneWindow: *FMB* installDecor flags : -2139029248
09-11 05:16:49.476 9402-9482/com.sedjromediasolution.onaayo I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
09-11 05:16:49.476 9402-9482/com.sedjromediasolution.onaayo I/qtaguid: Tagging socket 52 with tag f00d00000000{61453,0} for uid -1, pid: 9402, getuid(): 10270
09-11 05:16:49.526 9402-9402/com.sedjromediasolution.onaayo I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: SKARAJGA_AU_LINUX_ANDROID_LA.BR.1.1.2_RB1.05.00.02.031.018+PATCH[ES]_msm8916_32_refs/tags/AU_LINUX_ANDROID_LA.BR.1.1.2_RB1.05.00.02.031.018__release_ENGG (I856e09677e)
    OpenGL ES Shader Compiler Version: E031.25.03.02
    Build Date: 04/06/15 Mon
    Local Branch: 
    Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.BR.1.1.2_RB1.05.00.02.031.018
    Local Patches: 112c106f3772623daa7b4181c6cf23491044ead1 Revert "Disable ASTC on A405"
                     58a118cb818fdc906095a49a90977c15f9d3b223 Remove ASTC
09-11 05:16:50.076 9402-9504/com.sedjromediasolution.onaayo I/flutter: Observatory listening on http://127.0.0.1:33921/p05xBwVyT2E=/
09-11 05:16:50.616 9402-9482/com.sedjromediasolution.onaayo I/qtaguid: Untagging socket 52
09-11 05:16:50.716 9402-9480/com.sedjromediasolution.onaayo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
09-11 05:16:50.716 9402-9480/com.sedjromediasolution.onaayo I/qtaguid: Tagging socket 52 with tag f00d00000000{61453,0} for uid -1, pid: 9402, getuid(): 10270
09-11 05:16:50.716 9402-9480/com.sedjromediasolution.onaayo I/qtaguid: Tagging socket 61 with tag f00d00000000{61453,0} for uid -1, pid: 9402, getuid(): 10270
09-11 05:16:50.746 9402-9402/com.sedjromediasolution.onaayo W/ContextImpl: Failed to ensure directory: /storage/extSdCard/Android/data/com.sedjromediasolution.onaayo/files/Pictures
09-11 05:16:50.856 9402-9402/com.sedjromediasolution.onaayo I/art: Rejecting re-init on previously-failed class java.lang.Class<com.lyokone.location.LocationPlugin$3>
09-11 05:16:50.866 9402-9402/com.sedjromediasolution.onaayo I/art: Rejecting re-init on previously-failed class java.lang.Class<com.lyokone.location.LocationPlugin$3>
09-11 05:16:50.946 9402-9480/com.sedjromediasolution.onaayo I/qtaguid: Untagging socket 52
09-11 05:16:51.046 9402-9473/com.sedjromediasolution.onaayo I/FA: Tag Manager is not found and thus will not be used
09-11 05:16:51.066 9402-9402/com.sedjromediasolution.onaayo D/SensorManager: registerListener :: 0, BMC150 Acceleration Sensor, 66667, 0,  
09-11 05:16:51.116 9402-9528/com.sedjromediasolution.onaayo D/OpenGLRenderer: Render dirty regions requested: true
09-11 05:16:51.146 9402-9402/com.sedjromediasolution.onaayo D/PhoneWindow: *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
09-11 05:16:51.146 9402-9402/com.sedjromediasolution.onaayo D/PhoneWindow: *FMB* isFloatingMenuEnabled return false
09-11 05:16:51.276 9402-9402/com.sedjromediasolution.onaayo D/SRIB_DCS: log_dcs ThreadedRenderer::initialize entered! 
09-11 05:16:51.276 9402-9528/com.sedjromediasolution.onaayo I/OpenGLRenderer: Initialized EGL, version 1.4
09-11 05:16:51.286 9402-9528/com.sedjromediasolution.onaayo D/OpenGLRenderer: Get maximum texture size. GL_MAX_TEXTURE_SIZE is 4096
09-11 05:16:51.286 9402-9528/com.sedjromediasolution.onaayo D/OpenGLRenderer: Enabling debug mode 0
09-11 05:16:51.366 9402-9487/com.sedjromediasolution.onaayo W/AnalyticsUserIDStore: initStore should have been called before calling setUserID
09-11 05:16:51.366 9402-9487/com.sedjromediasolution.onaayo W/UserDataStore: initStore should have been called before calling setUserID
09-11 05:16:51.386 9402-9478/com.sedjromediasolution.onaayo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
09-11 05:16:51.396 9402-9478/com.sedjromediasolution.onaayo I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
09-11 05:16:51.416 9402-9487/com.sedjromediasolution.onaayo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
09-11 05:16:51.416 9402-9487/com.sedjromediasolution.onaayo I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
09-11 05:16:51.586 9402-9402/com.sedjromediasolution.onaayo I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@21cbe56d time:113157757
09-11 05:16:51.606 9402-9426/com.sedjromediasolution.onaayo I/art: Background sticky concurrent mark sweep GC freed 44940(2MB) AllocSpace objects, 16(855KB) LOS objects, 7% free, 11MB/12MB, paused 11.940ms total 169.231ms
09-11 05:16:51.836 9402-9426/com.sedjromediasolution.onaayo I/art: Background sticky concurrent mark sweep GC freed 19877(791KB) AllocSpace objects, 0(0B) LOS objects, 1% free, 12MB/12MB, paused 6.781ms total 107.287ms
09-11 05:16:51.956 9402-9426/com.sedjromediasolution.onaayo I/art: Background partial concurrent mark sweep GC freed 17925(749KB) AllocSpace objects, 5(543KB) LOS objects, 40% free, 12MB/20MB, paused 6.235ms total 65.437ms
09-11 05:16:52.116 9402-9478/com.sedjromediasolution.onaayo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: The following NoSuchMethodError was thrown building Consumer<AppModel>:
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: The method '[]' was called on null.
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: Receiver: null
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: Tried calling: []("Setting")
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: When the exception was thrown, this was the stack:
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50)
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: #1      AppState.build.<anonymous closure> (package:fstore/app.dart:166)
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: #2      Consumer.build (package:provider/src/consumer.dart:180)
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:3974)
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924)
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3721)
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: #6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340)
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700)
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285)
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016)
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958)
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874)
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: #15     _invoke (dart:ui/hooks.dart:236)
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: #16     _drawFrame (dart:ui/hooks.dart:194)
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: (elided 3 frames from package dart:async)
09-11 05:16:52.126 9402-9497/com.sedjromediasolution.onaayo I/flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
09-11 05:17:20.526 9402-9402/com.sedjromediasolution.onaayo D/SensorManager: unregisterListener ::   
09-11 05:17:20.546 9402-9402/com.sedjromediasolution.onaayo V/ActivityThread: updateVisibility : ActivityRecord{2df1d249 token=android.os.BinderProxy@21cbe56d {com.sedjromediasolution.onaayo/com.sedjromediasolution.onaayo.MainActivity}} show : true

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but related to implementation. See https://flutter.dev/community for support options.
Anyway, keeping it open, but most probably help on SO would come faster. 
By a rough guess, something was not initialized, sorry for me not being able to help with it.

**Comment by csells** [comment]
This is a question better suite to Stackoverflow.
