### ISSUE TITLE
Remove SkVirtualCanvasEnforcer (used by CanvasSpy) subclasses from the engine.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#40192]
This is currently used in [CanvasSpy](https://github.com/flutter/engine/blob/5566be141cfd0b62907e7bf4a3306623ec503d9a/shell/common/canvas_spy.h#L25). However, the API of the virtual canvas enforcer is quite large and our use of the same is getting in the way of the Skia team from iterating on the same.

The options discussed were:
* Replace `CanvasSpy::DidDrawIntoCanvas()` with an as yet unimplemented method in Skia to ask the picture if it has contents to render onto the surface.
* Have an engine specific abstraction over pictures and use that to analyze the effective draw operations. This is also what Chrome & Android do.

**Comment by chinmaygarde** [comment]
cc @lhkbob

**Comment by chinmaygarde** [comment]
References for Chrome and Android provided by mtklein@:

Android: android/frameworks/base/libs/hwui/RecordingCanvas.h
Chrome: chromium/src/cc/paint/paint_op_buffer.h

**Comment by chinmaygarde** [comment]
xref https://bugs.chromium.org/p/skia/issues/detail?id=9411

**Comment by jonahwilliams** [comment]
I cannot find this class in the engine: https://github.com/search?q=repo%3Aflutter%2Fengine+SkVirtualCanvasEnforcer&type=code
