### ISSUE TITLE
pageable_list.dart weirdness on cards 3/4

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#402]
Open `examples/widgets/pageable_list.dart`
Open the drawer, set vertical, close the drawer.
Page up one page at a time up to page 3 (three swipes up).
Notice that page 3 turns into page 4.

**Comment by HansMuller** [comment]
I wasn't able to reproduce this.

**Comment by Hixie** [comment]
I can't reproduce this any more. Closing.
