### ISSUE TITLE
NoSuchMethodError: The getter 'connectedApps' was called on null

### ISSUE THREAD

**Issue by zch9** [flutter/flutter#40203]
The web app run throw a exception
Flutter version:
Flutter 1.10.2-pre.33 • channel master • https://github.com/flutter/flutter.git
Framework • revision f614144f0a (32 minutes ago) • 2019-09-10 19:29:31 -0700
Engine • revision 7ea9884ab0
Tools • Dart 2.5.0 (build 2.5.0-dev.4.0 be66176534)

NoSuchMethodError: The getter 'connectedApps' was called on null.
Receiver: null
Tried calling: connectedApps
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      WebFs.runAndDebug (package:flutter_tools/src/build_runner/web_fs.dart:110:29)
#2      ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:176:41)
<asynchronous suspension>
#3      AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:452:23)
#4      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:513:26)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#11     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:894:20)
#12     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:511:15)
<asynchronous suspension>
#13     AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:446:12)
<asynchronous suspension>
#14     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:313:38)
<asynchronous suspension>
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#17     _rootRunUnary (dart:async/zone.dart:1132:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#25     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#26     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#27     _rootRunUnary (dart:async/zone.dart:1132:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#32     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#33     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#38     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#39     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#40     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

Finished with error: Failed to build application for the web.

**Comment by jrnelson333** [comment]
I am seeing the exact same error

**Comment by xbo1** [comment]
same error

**Comment by jiechic** [comment]
same error with `flutter run -d chrome`
then use `flutter run -d web` is normal

**Comment by mukhtarfauzi** [comment]
same error

**Comment by saviourdog** [comment]
same error

**Comment by pulyaevskiy** [comment]
Can confirm running with `-d web` works, though not sure what's the difference.

**Comment by jahnli** [comment]
same error

**Comment by wchenwa** [comment]
same error

**Comment by jonahwilliams** [comment]
Just landed a fix, sorry for the trouble

**Comment by hieutle2011** [comment]
It works after the fix. Run `flutter upgrade` and you're good to go with `-d chrome`.

**Comment by wchenwa** [comment]
Good
