### ISSUE TITLE
About `Flow` widget issues

### ISSUE THREAD

**Issue by z624821876** [flutter/flutter#40206]
The Flow widget can fail in some cases！
### First example (Normal)：
```
Container(
      margin: EdgeInsets.only(top: 100),
      color: Colors.black,
      child: Flow(
        delegate: CustomWrapDelegate(columnSpacing: 10, lineSpacing: 10),
        children: <Widget>[
          new Container(width: 80.0, height: 80.0, color: Colors.pink),
          new Container(width: 80.0, height: 80.0, color: Colors.yellow),
          new Container(width: 80.0, height: 80.0, color: Colors.green),
          new Container(width: 80.0, height: 80.0, color: Colors.blue),
          new Container(width: 80.0, height: 80.0, color: Colors.lightBlue),
          new Container(width: 80.0, height: 80.0, color: Colors.yellow),
          new Container(width: 80.0, height: 80.0, color: Colors.blueGrey),
          new Container(width: 80.0, height: 80.0, color: Colors.brown),
          new Container(width: 80.0, height: 80.0, color: Colors.yellow),
        ],
      ),
    );
```
![image](https://user-images.githubusercontent.com/8405670/64665026-aaa11b00-d483-11e9-875c-5ee776bf3ec5.png)

### Second example：
```
Container(
      color: Colors.white,
      child: Container(
        height: 300,
        width: 300,
        margin: EdgeInsets.only(top: 100),
        color: Colors.black,
        child: Flow(
          delegate: CustomWrapDelegate(columnSpacing: 10, lineSpacing: 10),
          children: <Widget>[
            new Container(width: 80.0, height: 80.0, color: Colors.pink),
            new Container(width: 80.0, height: 80.0, color: Colors.yellow),
            new Container(width: 80.0, height: 80.0, color: Colors.green),
            new Container(width: 80.0, height: 80.0, color: Colors.blue),
            new Container(width: 80.0, height: 80.0, color: Colors.lightBlue),
            new Container(width: 80.0, height: 80.0, color: Colors.yellow),
            new Container(width: 80.0, height: 80.0, color: Colors.blueGrey),
            new Container(width: 80.0, height: 80.0, color: Colors.brown),
            new Container(width: 80.0, height: 80.0, color: Colors.yellow),
          ],
        ),
      ),
    );
```
![image](https://user-images.githubusercontent.com/8405670/64665158-18e5dd80-d484-11e9-9479-292b20258842.png)
In the second example, 'CustomWrapDelegate - >paintChildren() context.getchildsize (I)' gets an incorrect size

**Comment by BondarenkoStas** [comment]
@z624821876 Please provide your ```flutter doctor -v``` output as it will help to know which version of the framework you use.

**Comment by z624821876** [comment]
> flutter doctor -v

[✓] Flutter (Channel master, v1.10.2-pre.12, on Mac OS X 10.14.4 18E226, locale
    zh-Hans-CN)
    • Flutter version 1.10.2-pre.12 at /Users/aladin/flutter
    • Framework revision 77f71ef48f (2 days ago), 2019-09-10 10:32:27 +0900
    • Engine revision 7ea9884ab0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/aladin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

**Comment by markusaksli-nc** [comment]
Hi @z624821876 
Could you please provide the complete minimal reproduction code you used here? There is a missing reference to your `CustomWrapDelegate`.
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
