### ISSUE TITLE
Update documentation to be clearer about how Stack only clips children whose _size_ overflows the stack, it doesn't matter if they paint outside the stack

### ISSUE THREAD

**Issue by ukomiljon** [flutter/flutter#40216]
After appling scale, it ignores overflow.clip on Stack Widget.
It becomes overflow.visible always. I think it must be inside of parent, when it is overflow.clip.
if scale is 1, it works; overflow.clip is accepted.
But if scale is more than 1, it does not work.
```
AnyParent Widget(
child:
Transform.scale(
                            scale: 2, 
                            child: Stack(
                              overflow: Overflow.clip,
                              children: <Widget>[
                                Positioned(
                                  left: 220,
                                  top: 200,
                                  child: FlutterLogo(),
                ), 
          ],
     ),
  ),
)
```

**Comment by ukomiljon** [comment]
After appling scale, it ignores overflow.clip on Stack Widget.
It becomes overflow.visible always. I think it must be inside of parent, when it is overflow.clip.
if scale is 1, it works; overflow.clip is accepted.
But if scale is more than 1, it does not work.

AnyParent Widget(
child:
Transform.scale(
                            scale: 2, 
                            child: Stack(
                              overflow: Overflow.clip,
                              children: <Widget>[
                                Positioned(
                                  left: 220,
                                  top: 200,
                                  child: FlutterLogo(),
                ), 
          ],
     ),
  ),
)

**Comment by BondarenkoStas** [comment]
@ukomiljon If you don't mind, I moved your commend to the issue body (as that was empty).
Please provide your ```flutter doctor -v``` output (it's needed to know which version of the framework you use)

**Comment by ukomiljon** [comment]
sorry for empty body.

here is the result for flutter doctor -v :
-------------------------------------------------------------------------------
flutter doctor -v
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.295], locale en-MY)
    • Flutter version 1.7.8+hotfix.4 at C:\flutter\flutter
    • Framework revision 20e59316b8 (8 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\gpuguy\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.38.0)
    • VS Code at C:\Users\gpuguy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (2 available)
    • CPH1801            • 224258cb      • android-arm64 • Android 7.1.1 (API 25)
    • sdk google atv x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

• No issues found!

**Comment by goderbauer** [comment]
Can you provide a runnable code snippet that we can just copy, paste, and run to see the issue?

**Comment by ukomiljon** [comment]
import 'package:flutter/material.dart';
 

void main() => runApp(MyApp());

 Color backrgoundColor = Color.fromRGBO(245, 245, 245, 100);
Color backrgoundColor2 = Color.fromRGBO(228, 228, 228, 100);
Color borderColor = Colors.grey[700]; //.fromRGBO(78, 78, 78, 100);
Color selectedColor = Color.fromRGBO(38, 38, 38, 100);

double iconSize = 20.0;
double verticalLeftBarWidth = 40.0;
double horizontalTopBarHeight = 30.0;
double paddingIconsWidth = 20.0;
double paddingIconHeight = 20.0;

var textStyle = TextStyle(
    fontWeight: FontWeight.normal,
    color: borderColor,
    fontFamily: 'Montserrat',
    fontSize: 14.0);

var selectedTextStyle = TextStyle(
  fontWeight: FontWeight.normal,
  color: Colors.black,
  fontFamily: 'Montserrat',
  fontSize: 14.0,
);


 
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      theme: ThemeData(fontFamily: 'Raleway'),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SafeArea(
          child: Container(
            decoration: BoxDecoration(color: backrgoundColor2),
            child: Column(
              children: <Widget>[
                Expanded(
                  child: Row(
                    children: <Widget>[
                      Container(
                        decoration: BoxDecoration(
                            border: Border(
                                top: BorderSide(color: backrgoundColor2)),
                            color: backrgoundColor),
                        width: verticalLeftBarWidth,
                        child: Column(
                          children: <Widget>[
                            SizedBox(
                              height: 20,
                            ),
                            Icon(
                              Icons.play_arrow,
                              color: borderColor,
                              size: iconSize,
                            ),
                            Expanded(
                              child: SizedBox(
                                height: double.infinity,
                              ),
                            ),
                            Icon(
                              Icons.table_chart,
                              color: borderColor,
                              size: iconSize,
                            ),
                            SizedBox(
                              height: paddingIconHeight,
                            ),
                          ],
                        ),
                      ),
                      Expanded(
                        child: Container(
                          decoration: BoxDecoration(color: backrgoundColor2),
                          child: Container(
                            decoration: BoxDecoration(color: Colors.blueGrey),
                            child: Transform.scale(
                              scale: 2,
                              child: Stack(
                                overflow: Overflow.clip,
                                children: <Widget>[
                                  Positioned(
                                    left: 150,
                                    top: 200,
                                    child: FlutterLogo(
                                      size: 200,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                      )
                    ],
                  ),
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}

**Comment by ravenblackx** [comment]
A related example in unit test form:
```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

class OverflowingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        title: 'Overflowing Stack widget',
        home: Wrap(
          children: [
            Container(
              height: 200,
              width: 200,
              color: Colors.amber,
              child: Stack(
                children: [
                  Positioned.fromRect(
                    rect: Rect.fromLTRB(90, 90, 190, 190),
                    child: Transform.scale(
                      origin: Offset(-100, -100),
                      scale: 2.0,
                      child: Container(
                        color: Colors.blue,
                      ),
                    ),
                  ),
                ],
              ),
            )
          ],
        ),
      );
}

void main() {
  testWidgets('blue is contained inside amber box', (tester) async {
    await tester.pumpWidget(OverflowingWidget());
    await tester.pumpAndSettle();
    await expectLater(find.byType(MaterialApp).first,
        matchesGoldenFile('blue_contained_inside_amber'));
  });
}
```
![image](https://user-images.githubusercontent.com/1923229/68620554-8f05c100-0482-11ea-866f-e7655e737468.png)

**Comment by goderbauer** [comment]
I can reproduce the issue. The stack only applies a clip when one of its direct children end up outside of the bounds of the stack. The Positioned in the example is fully within its bounds. Therefore, it doesn't see a need to clip and it doesn't (clipping is expansive, so we avoid it where we can). The stack doesn't see that a child of the Positioned is painting outside the bounds of the stack.

I don't really see a good way to fix this short of making the stack always apply a clip even when it is not necessary (which would be bad for performance).

As a work-around you can just wrap the Stack in a ClipRect (and set overflow to Overflow.visible to avoid a double clip).

**Comment by ravenblackx** [comment]
Maybe consider this a documentation bug? Make note of the fact that Overflow.clip actually only means clip direct children. (Is that true everywhere that Overflow.clip is an option?) I looked for any notes to that effect and couldn't find one.

And/or make note of the fact that Transform widgets specifically will do unexpected things with respect to clipping (I'm guessing that if the Positioned was half out of bounds, the Transformed child would be rendered half-size in its new location?)

**Comment by cookmscott** [comment]
@ukomiljon ... not sure if Stack widget supports proper overflow clipping for transformed widgets. I opened an issue here: https://github.com/flutter/flutter/issues/47860 that's in a similar light. 

My only work-around so far was to `ClipRect` around the Stack widget which cleaned up any children (transformed or not) spilling outside the parent Stack.

**Comment by Hixie** [comment]
ClipRect is the correct solution here.

**Comment by TahaTesser** [comment]
i believe this can mentioned here https://api.flutter.dev/flutter/widgets/Stack/overflow.html

**Comment by ravenblackx** [comment]
That quoted comment describes what we all expected to happen, not what actually happens.
Compare it to the bug title which describes the reality.
The comment says children *cannot* paint outside the stack's box, the reality is children *can* paint outside the stack's box if they're transformed or if they paint outside their own bounds.

**Comment by cookmscott** [comment]
I agree with @ravenblackx .. the information I received on #47860 from Hixie makes it seem that a child's size is the determining factor for Overflow.clip, not paint boundaries.. That makes the quoted comment from TahaTesser confusing as ravenblackx mentioned.
> children cannot paint outside of the stack's box. -[TahaTesser ](https://github.com/flutter/flutter/issues/40216#issuecomment-676357972)

> if [children] paint outside their bounds, that's not considered overflow -[Hixie](https://github.com/flutter/flutter/issues/47860#issuecomment-569174876)
