### ISSUE TITLE
A non-null String must be provided to a Text widget, Failed assertion: line 269 pos 10: 'data != null'

### ISSUE THREAD

**Issue by jasonmurray33** [flutter/flutter#40214]
Hit this recently when installing a test app to an iPhone X during an online course, reporting the bug as mentioned in the terminal. The same action works without issue in the iOS simulator. From the AddTaskScreen class below, I notice that when I type into the TextField with the iOS keyboard, choose 'Done' to dismiss the keyboard, and then use the FlatButton to trigger onpressed, I'm seeing the issue. But if I type text in via the keyboard and immediately use the FlatButton to trigger onpressed without dismissing the keyboard first, the action works on the iPhone X. 

I just upgraded to ```Flutter 1.9.1+hotfix.2``` and ```Dart 2.5```, not sure if that has anything to do with the issue.
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building TaskTile(dirty):
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 269 pos 10: 'data != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

User-created ancestor of the error-causing widget was: 
  ListView file:///{myProject}/lib/widgets/tasks_list.dart:10:25
When the exception was thrown, this was the stack: 
#2      new Text (package:flutter/src/widgets/text.dart:269:10)
#3      TaskTile.build (package:{myProject}/widgets/tasks_tile.dart:19:14)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4009:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
...
```
Contents of tasks_tile.dart:
```
dart
import 'package:flutter/material.dart';

class TaskTile extends StatelessWidget {
  final bool isChecked;
  final String taskTitle;
  final Function checkboxCallback;
  final Function longPressCallback;

  TaskTile({
    this.isChecked,
    this.taskTitle,
    this.checkboxCallback,
    this.longPressCallback,
 });

  @override
  Widget build(BuildContext context) {
    return ListTile(
      title: Text(
        taskTitle,
        style: TextStyle(
          decoration: isChecked ? TextDecoration.lineThrough : null,
        ),
      ),
      selected: false,
      trailing: Checkbox(
        activeColor: Colors.lightBlueAccent,
        value: isChecked,
        onChanged: checkboxCallback,
      ),
      onLongPress: longPressCallback,
    );
  }
}
```

Contents of tasks_list.dart:
```
dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:{myProject}/model/task_data.dart';
import 'package:{myProject}/widgets/tasks_tile.dart';

class TasksList extends StatelessWidget {
  Widget build(BuildContext context) {
    return Consumer<TaskData>(
      builder: (context, taskData, child) {
        return ListView.builder(
          itemBuilder: (context, index) {
            final task = taskData.tasks[index];
            return TaskTile(
              taskTitle: task.name,
              isChecked: task.isDone,
              checkboxCallback: (checkboxState) {
                taskData.updateTaskState(task);
              },
              longPressCallback: () {
                taskData.removeTask(task);
              },
            );
          },
          itemCount: taskData.taskCount,
        );
      },
    );
  }
}
```

Here's the screen adding a task:
```
dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '{myProject}/model/task_data.dart';

class AddTaskScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    String newTaskValue;

    return Container(
      color: Color(0xff757575),
      child: Container(
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(20.0),
            topRight: Radius.circular(20.0),
          ),
        ),
        padding: EdgeInsets.all(20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            Text(
              'Add Task',
              textAlign: TextAlign.center,
              style: TextStyle(
                fontSize: 30.0,
                color: Colors.lightBlueAccent,
              ),
            ),
            TextField(
              autofocus: true,
              textAlign: TextAlign.center,
              onChanged: (value) {
                newTaskValue = value;
              },
            ),
            FlatButton(
              child: Text(
                'Add',
                style: TextStyle(color: Colors.white),
              ),
              color: Colors.lightBlueAccent,
              onPressed: () {
                Provider.of<TaskData>(context).addTask(newTaskValue);
                Navigator.pop(context);
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

Here's the TaskData class:
```
dart
import 'dart:collection';

import 'package:flutter/foundation.dart';
import 'package:{myProject}/model/task.dart';

class TaskData extends ChangeNotifier {
  List<Task> _tasks = [
    Task(name: 'Buy Milk'),
    Task(name: 'Buy Bread'),
    Task(name: 'Buy Eggs'),
  ];

  UnmodifiableListView<Task> get tasks => UnmodifiableListView(_tasks);

  int get taskCount => _tasks.length;

  void addTask(String text) {
    _tasks.add(Task(name: text));
    notifyListeners();
  }

  void removeTask(Task task) {
    _tasks.remove(task);
    notifyListeners();
  }

  void updateTaskState(Task task) {
    task.toggleCompletionStatus();
    notifyListeners();
  }
}
```
Here is the main view displaying the tasks list:
```
dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '{myProject}/model/task_data.dart';
import 'package:{myProject}/widgets/tasks_list.dart';

import 'add_tasks_screen.dart';

class TasksScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.lightBlueAccent,
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Container(
            padding: EdgeInsets.only(
              top: 60.0,
              left: 30.0,
              right: 30.0,
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                CircleAvatar(
                  backgroundColor: Colors.white,
                  radius: 30.0,
                  child: Icon(
                    Icons.list,
                    color: Colors.lightBlueAccent,
                    size: 30.0,
                  ),
                ),
                SizedBox(
                  height: 10.0,
                ),
                Text(
                  'Todoey',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 50.0,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                Text(
                  '${Provider.of<TaskData>(context).taskCount} Tasks',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 18.0,
                  ),
                ),
              ],
            ),
          ),
          Expanded(
            child: Container(
              padding: EdgeInsets.symmetric(horizontal: 20.0),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(20.0),
                  topRight: Radius.circular(20.0),
                ),
              ),
              child: TasksList(),
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        backgroundColor: Colors.lightBlueAccent,
        child: Icon(
          Icons.add,
        ),
        onPressed: () {
          showModalBottomSheet(
            context: context,
            builder: (context) => AddTaskScreen(),
          );
        },
      ),
    );
  }
}

```

**Comment by goderbauer** [comment]
This looks like a problem with your app. In `TaskTile.build (package:{myProject}/widgets/tasks_tile.dart:19:14)` you're providing `null` to a `Text` widget, which is not allowed. You could change that to `Text(variableThatMayBeNull ?? 'default value')`.

**Comment by jasonmurray33** [comment]
Goderbauer i updated the code to do that, but the challenge is that when I use the ‘Done’ button to dismiss the iOS keyboard, the test I just typed is getting lost. The only way I can get the text to remain is to click the FlatButton without dismissing the keyboard first. Any suggestions on how to resolve that? Also, why does this code work as is in the simulator but does not on a device?

**Comment by godilite** [comment]
How did you add this `TextDecoration.lineThrough ?? 'default value',` I dont seem to understand, having the same error

**Comment by godilite** [comment]
> Goderbauer i updated the code to do that, but the challenge is that when I use the ‘Done’ button to dismiss the iOS keyboard, the text I just typed is getting lost. The only way I can get the text to remain is to click the FlatButton without dismissing the keyboard first. Any suggestions on how to resolve that? Also, why does this code work as is in the simulator but does not on a device?

change the widget to a statefulwidget

**Comment by jahidRatul** [comment]
@jasonmurray33 did u get the solution? i am facing same problem in android ..

**Comment by jasonmurray33** [comment]
@jahidRatul yes, the solution for me was to convert the TasksScreen task to a stateful widget and to set a default value when calling the .addTask method of the task data class: 

`import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:todoey_app/constants.dart';
import 'package:todoey_app/model/task_data.dart';

class AddTaskScreen extends StatefulWidget {
  @override
  _AddTaskScreenState createState() => _AddTaskScreenState();
}

class _AddTaskScreenState extends State<AddTaskScreen> {
  String taskText;

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Color(0xff757575),
      child: Container(
        decoration: BoxDecoration(
          color: kMainColor,
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(20.0),
            topRight: Radius.circular(20.0),
          ),
        ),
        padding: EdgeInsets.all(20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            Text(
              'Add Task',
              textAlign: TextAlign.center,
              style: TextStyle(
                fontSize: 30.0,
                color: kBackgroundColor,
              ),
            ),
            TextField(
              autofocus: true,
              textAlign: TextAlign.center,
              onChanged: (value) {
                taskText = value;
              },
            ),
            FlatButton(
              child: Text(
                'Add',
                style: TextStyle(color: kMainColor),
              ),
              color: kBackgroundColor,
              onPressed: () {
                Provider.of<TaskData>(context).addTask(taskText ?? '');
                Navigator.pop(context);
              },
            ),
          ],
        ),
      ),
    );
  }
}
`

**Comment by jahidRatul** [comment]
Thanks a lot for your help.

**Comment by dhaladitya108** [comment]
Text(
    '$taskTitle', => this will fix the error
     ......
    )

**Comment by sayanmondal31** [comment]
> @jahidRatul yes, the solution for me was to convert the TasksScreen task to a stateful widget and to set a default value when calling the .addTask method of the task data class:
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:provider/provider.dart';
> import 'package:todoey_app/constants.dart';
> import 'package:todoey_app/model/task_data.dart';
> 
> class AddTaskScreen extends StatefulWidget {
>   @override
>   _AddTaskScreenState createState() => _AddTaskScreenState();
> }
> 
> class _AddTaskScreenState extends State<AddTaskScreen> {
>   String taskText;
> 
>   @override
>   Widget build(BuildContext context) {
>     return Container(
>       color: Color(0xff757575),
>       child: Container(
>         decoration: BoxDecoration(
>           color: kMainColor,
>           borderRadius: BorderRadius.only(
>             topLeft: Radius.circular(20.0),
>             topRight: Radius.circular(20.0),
>           ),
>         ),
>         padding: EdgeInsets.all(20.0),
>         child: Column(
>           crossAxisAlignment: CrossAxisAlignment.stretch,
>           children: <Widget>[
>             Text(
>               'Add Task',
>               textAlign: TextAlign.center,
>               style: TextStyle(
>                 fontSize: 30.0,
>                 color: kBackgroundColor,
>               ),
>             ),
>             TextField(
>               autofocus: true,
>               textAlign: TextAlign.center,
>               onChanged: (value) {
>                 taskText = value;
>               },
>             ),
>             FlatButton(
>               child: Text(
>                 'Add',
>                 style: TextStyle(color: kMainColor),
>               ),
>               color: kBackgroundColor,
>               onPressed: () {
>                 Provider.of<TaskData>(context).addTask(taskText ?? '');
>                 Navigator.pop(context);
>               },
>             ),
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```

but when I try to add with same procedure( keyboard off first)  to my list it shows blank at the title but it added .
