### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by Troublebreaker** [flutter/flutter#40212]
## Steps to Reproduce
```
1.  dependencies:
  awesome_package:
2. flutter:
  fonts:
    -family: Raleway
    fonts:
      - asset: packages/awesome_package/fonts/Raleway-Regular.ttf
      - asset: packages/awesome_package/fonts/Raleway-Italic.ttf
        style: italic
  uses-material-design: true
3. Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: c82741d42ed9ee89)
Crash report written to /Users/qyg/AndroidStudioProjects/flutter_app1/flutter_05.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by BondarenkoStas** [comment]
@Troublebreaker Can you please provide that ```flutter_05.log```?
Please provide you ```flutter doctor -v``` output, it's needed to know which version of the framework and which environment you use.

**Comment by janmoppel** [comment]
Hello @Troublebreaker !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
