### ISSUE TITLE
Add Flutter to existing apps - Problem with FlutterAppLifeCycleProvider

### ISSUE THREAD

**Issue by amen71311** [flutter/flutter#40217]
Hi guys,

Before the August update, I add Flutter to my existing app and it runs just fine, but when I follow the new [instruction](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) to switch to master branch and upgrade flutter then I got this issue:

`No visible @interface for 'FlutterPluginAppLifeCycleDelegate' declares the selector 'applicationDidEnterBackground:'`

When I check the FlutterPluginAppLifeCycleDelegate.h there is no interface applicationDidEnterBackground. 

The followings are the same: 
- (void)applicationDidEnterBackground:(UIApplication*)application {
    [_lifeCycleDelegate applicationDidEnterBackground:application];
}

- (void)applicationWillEnterForeground:(UIApplication*)application {
    [_lifeCycleDelegate applicationWillEnterForeground:application];
}

- (void)applicationWillResignActive:(UIApplication*)application {
    [_lifeCycleDelegate applicationWillResignActive:application];
}

- (void)applicationDidBecomeActive:(UIApplication*)application {
    [_lifeCycleDelegate applicationDidBecomeActive:application];
}

- (void)applicationWillTerminate:(UIApplication*)application {
    [_lifeCycleDelegate applicationWillTerminate:application];
}

Now when I run my app, it just show the black screen with no error and no logs even I print some line in the Flutter App.

**Comment by sexiong306** [comment]
i meet the same prolblem. how do you deal with it?

**Comment by amen71311** [comment]
> i meet the same prolblem. how do you deal with it?

I just don't add those line. They removed the implementation of those.
