### ISSUE TITLE
Async call cause to state not dispose.

### ISSUE THREAD

**Issue by zf19820621** [flutter/flutter#40215]
I use video_player to play video in stateful widget. I fetch server data in initState, and begin playing video when it returns. So if i tap the phone back key quickly enough, when the video is intializing, the video page is closed, but in the next seconds, the video start playing in the background, and the state's dispose is not called, where i call VideoPlayerController's dispose. As a result, the video is      
playing in the background. I expect that i close my page, and call dispose of widget state. 

Why it does not call dispose, is it due to my async call? I search something about flutter widget life cycle. I just find initState, didChangeDependencies, deactivate, dispose, and build. I can't find override function which means widget close. So what can i do, can you give me some advice.

**Comment by BondarenkoStas** [comment]
@zf19820621 Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

Also please provide your ```flutter doctor -v``` output, it's needed to know the version of the framework. And do you use ```video_player 0.10.2+1``` or any other version?

**Comment by BugsBunnyBR** [comment]
@zf19820621 you should check `if(mounted){ // play video}` when you receive data from the server.

**Comment by janmoppel** [comment]
Hello @zf19820621 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
