### ISSUE TITLE
when I'm using onPressed: () {                 Navigator.push(context, MaterialPageRoute(builder: (context) => screen_three()));},  It is returning me black screen, When I'm trying to do this with other screens it is working fine.

### ISSUE THREAD

**Issue by DeekshithRajBasa** [flutter/flutter#40226]
when I'm using 
```
onPressed: () { Navigator.push(context, MaterialPageRoute(builder: (context) => screen_three()));}, 
```
It is returning me black screen, When I'm trying to do this with other screens it is working fine.

**Comment by BondarenkoStas** [comment]
@DeekshithRajBasa Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.
Please also provide you ```flutter doctor -v``` output, it's needed to know which version of the framework you use, and what is the environment.

**Comment by DeekshithRajBasa** [comment]
``

[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.356], locale en-IN)
    • Flutter version 1.9.1+hotfix.2 at F:\flutter sdk\flutter
    • Framework revision 2d2a1ffec9 (8 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Deekshith Raj Basa\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.38.0)
    • VS Code at C:\Users\Deekshith Raj Basa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by BondarenkoStas** [comment]
@DeekshithRajBasa can you please paste here some minimal code example which reproduces the issue?
