### ISSUE TITLE
how judge Text overflow Conainer？

### ISSUE THREAD

**Issue by dev-zl** [flutter/flutter#40223]
how judge Text overflow Conainer？

Android marquee

**Comment by BondarenkoStas** [comment]
@dev-zl Not sure if I understood the question, can you please explain it in more details?

**Comment by dev-zl** [comment]
@BondarenkoStas 
![image](https://user-images.githubusercontent.com/36152331/64695716-57ed5080-d4cf-11e9-9dee-5559b6664457.png)

![image](https://user-images.githubusercontent.com/36152331/64695751-6fc4d480-d4cf-11e9-93f3-d015df47c914.png)

I want to judge the text overflow and scroll it

**Comment by dev-zl** [comment]
> @BondarenkoStas
> ![图片](https://user-images.githubusercontent.com/36152331/64695716-57ed5080-d4cf-11e9-9dee-5559b6664457.png)
> 
> ![图片](https://user-images.githubusercontent.com/36152331/64695751-6fc4d480-d4cf-11e9-93f3-d015df47c914.png)
> 
> 我想判断文本溢出并滚动它

But I don't know how to get the width of the Text(Widget) ?

**Comment by goderbauer** [comment]
You can use a TextPainter [1] to figure out how tall Text is going to be, but that's fairly expensive. Why do you need to know this beforehand? You could just remove the height restriction from the container and it would size itself to fit the text.

[1] https://master-api.flutter.dev/flutter/painting/TextPainter-class.html

**Comment by dev-zl** [comment]
> 您可以使用TextPainter [1]来确定Text的高度，但这相当昂贵。为什么你需要事先知道这个？您可以从容器中删除高度限制，它将自身调整大小以适合文本。
> 
> [1] https://master-api.flutter.dev/flutter/painting/TextPainter-class.html

 Why do you need to know this beforehand?
for  I want to judge the Text Widget  if overflow and scroll it.
scroll it

**Comment by dev-zl** [comment]
@goderbauer 

Why do you need to know this beforehand?
for  I want to judge the Text Widget  if overflow and scroll it.
scroll it

**Comment by dev-zl** [comment]
> @goderbauer
> 
> Why do you need to know this beforehand?
> for I want to judge the Text Widget if overflow and scroll it.
> scroll it

I think you guys should add a feature.
PreRendering
by  PreRendering get Widget  [height ,width ,position] info .
When it comes to real rendering,Continue to get rendering information from PreRendering to speed up rendering

**Comment by dev-zl** [comment]
I wanna know if there are some methods that I can invoke to give me a feedback  whenever overflow happenes like the picture above, thank you

**Comment by dev-zl** [comment]
@goderbauer  I think I understand thank you for your help.
