### ISSUE TITLE
flutter run with armv7

### ISSUE THREAD

**Issue by 39499740** [flutter/flutter#40222]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.2.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.37.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

I need to use face recognition in my program.
Face recognition is provided by ArcSoft.
But the Android version only provides the SDK for Armv7.
I've been developing with 1.5.4 before, and after upgrading, I found that there was an error in the operation.
```
Could not find an option named "target-platform".
```
```flutter run --release --target-platform=android-arm```    doesn't work
What commands should I use to replace it?

**Comment by BondarenkoStas** [comment]
@39499740 Please check the comment and report if you are able to run it at all https://github.com/flutter/flutter/pull/34369#issuecomment-506889854

**Comment by 39499740** [comment]
> @39499740 Please check the comment and report if you are able to run it at all [#34369 (comment)](https://github.com/flutter/flutter/pull/34369#issuecomment-506889854)

I don't think it's a good idea, but it solved my problem.

Thank you
