### ISSUE TITLE
Using AndroidView Black Screen in VIVO Brands,Just In First Install And First loading Situation

### ISSUE THREAD

**Issue by DylanXing** [flutter/flutter#40229]
I use AndroidView to show a baiduMap View and it looks normal in other brands except VIVO
The puzzling thing is that only the first time you install and the AndroidView will display a black screen for the first time. If you quit the app and re-enter it, everything will be fine. Even after the black screen appears, take a screenshot and then return to the app. The refresh is normal.
In addition to the custom map view, we tried other native Views (a text) using AndroidView display, which is still the same black screen. In addition, webview_flutter is the same problem.
I once thought that the same as the #24974 is a VirtualDisplay problem. But I use the [https://gist.github.com/amirh/33e2765206d6107bd52beeaca8b634cc](https://gist.github.com/amirh/33e2765206d6107bd52beeaca8b634cc) for VirtualDisplay test, there is a red color block in the middle of the screen, so it should not be a problem with VirtualDisplay?
There are some JVMContainer VMSG error logs I posted below can be seen, I hope to get your help.

![2141568184782_ pic](https://user-images.githubusercontent.com/15811655/64674734-0bd8e680-d4a4-11e9-91c3-5b062a607157.jpg)
![2131568184781_ pic](https://user-images.githubusercontent.com/15811655/64674744-109d9a80-d4a4-11e9-8727-83741f553a0e.jpg)
![2161568184784_ pic](https://user-images.githubusercontent.com/15811655/64674752-15fae500-d4a4-11e9-8010-1f8a19b77979.jpg)
![581568184998_ pic](https://user-images.githubusercontent.com/15811655/64674883-607c6180-d4a4-11e9-9496-51ce20cf1e25.jpg)

## Logs

```
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         9.8s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                        38.0s
E/        (14396): nFreeSize: 41264242688
E/        (14396): nFreeSize: 41264242688
Syncing files to device vivo X20A...                                    
 4,279ms (!)                                       

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on vivo X20A is available at: http://127.0.0.1:62903/TDA9hwhBM1E=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

E/        (14396): nFreeSize: 41261236224
E/        (14396): nFreeSize: 41261129728

E/JVMContainer VMSG(14396): RegisterNatives
E/        (14396): nFreeSize: 41259544576
E/        (14396): nFreeSize: 41259524096
E/        (14396): nFreeSize: 41259458560
E/        (14396): nFreeSize: 41258377216
E/        (14396): nFreeSize: 41258094592
E/        (14396): nFreeSize: 41257959424
E/        (14396): nFreeSize: 41257025536
E/        (14396): nFreeSize: 41256558592
E/        (14396): nFreeSize: 41256087552
E/        (14396): nFreeSize: 41255469056
E/        (14396): nFreeSize: 41255452672
E/        (14396): nFreeSize: 41255383040
E/        (14396): nFreeSize: 41255305216
E/        (14396): nFreeSize: 41255301120
E/        (14396): nFreeSize: 41255288832
E/        (14396): nFreeSize: 41255280640
E/        (14396): nFreeSize: 41255342080
D/PhoneWindow(14396): DEBUG_ALIENSCREEN:getRotation mRotation=0
I/DecorView(14396): setWindowBackground mBackgroundPadding = Rect(0, 0 - 0, 0), mFramePadding = Rect(0, 0 - 0, 0), pkg = com.lalamove.huolala.edriver
I/TouchMotionHandler(14396): handler onAttached
I/TouchMotionHandler(14396): window type filtered
I/View    (14396): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 0, 0), windowBounds = Rect(0, 0 - 0, 0), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{abea637 V.ED..... ......I. 0,0-0,0}
I/View    (14396): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 0, 0), windowBounds = Rect(0, 0 - 0, 0), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{abea637 V.ED..... ......I. 0,0-0,0}
I/View    (14396): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 1080, 1794), windowBounds = Rect(0, 0 - 1080, 1794), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{abea637 V.ED..... ......ID 0,0-1080,1794}
D/baidu_location_client(14396): baidu location connected ...

D/PhoneWindow(14396): DEBUG_ALIENSCREEN:getRotation mRotation=0
I/DecorView(14396): setWindowBackground mBackgroundPadding = Rect(0, 0 - 0, 0), mFramePadding = Rect(0, 0 - 0, 0), pkg = com.lalamove.huolala.edriver
I/TouchMotionHandler(14396): handler onAttached
I/TouchMotionHandler(14396): window type filtered
I/View    (14396): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 0, 0), windowBounds = Rect(0, 0 - 0, 0), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{b6c239c V.ED..... ......I. 0,0-0,0}
I/View    (14396): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 0, 0), windowBounds = Rect(0, 0 - 0, 0), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{b6c239c V.ED..... ......I. 0,0-0,0}
I/View    (14396): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 1080, 1794), windowBounds = Rect(0, 0 - 1080, 1794), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{b6c239c V.ED..... ......ID 0,0-1080,1794}
D/baidu_location_client(14396): baidu location connected ...

```

## quit and run again,every thing is fine ,the following is the log,it seems error logs is less

```
E/JVMContainer VMSG(14878): RegisterNatives
E/        (14878): nFreeSize: 41251532800
D/PhoneWindow(14878): DEBUG_ALIENSCREEN:getRotation mRotation=0
I/DecorView(14878): setWindowBackground mBackgroundPadding = Rect(0, 0 - 0, 0), mFramePadding = Rect(0, 0 - 0, 0), pkg = com.lalamove.huolala.edriver
I/TouchMotionHandler(14878): handler onAttached
I/TouchMotionHandler(14878): window type filtered
I/View    (14878): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 0, 0), windowBounds = Rect(0, 0 - 0, 0), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{81e2a77 V.ED..... ......I. 0,0-0,0}
I/View    (14878): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 0, 0), windowBounds = Rect(0, 0 - 0, 0), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{81e2a77 V.ED..... ......I. 0,0-0,0}
I/View    (14878): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 1080, 1794), windowBounds = Rect(0, 0 - 1080, 1794), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{81e2a77 V.ED..... ......ID 0,0-1080,1794}
D/NetworkSecurityConfig(14878): Using Network Security Config from resource network_security_config debugBuild: true
I/DpmTcmClient(14878): RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
I/DpmTcmClient(14878): RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor

```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.4 at /Users/xingdi/Documents/flutter
    • Framework revision 20e59316b8 (8 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xingdi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.3

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • vivo X20A • 6de3dc08 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```

**Comment by junyao-yu** [comment]
I also met this problem, could you tell me the problem solved？

**Comment by junyao-yu** [comment]
> I use AndroidView to show a baiduMap View and it looks normal in other brands except VIVO
> The puzzling thing is that only the first time you install and the AndroidView will display a black screen for the first time. If you quit the app and re-enter it, everything will be fine. Even after the black screen appears, take a screenshot and then return to the app. The refresh is normal.
> In addition to the custom map view, we tried other native Views (a text) using AndroidView display, which is still the same black screen. In addition, webview_flutter is the same problem.
> I once thought that the same as the #24974 is a VirtualDisplay problem. But I use the https://gist.github.com/amirh/33e2765206d6107bd52beeaca8b634cc for VirtualDisplay test, there is a red color block in the middle of the screen, so it should not be a problem with VirtualDisplay?
> There are some JVMContainer VMSG error logs I posted below can be seen, I hope to get your help.
> 
> ![2141568184782_ pic](https://user-images.githubusercontent.com/15811655/64674734-0bd8e680-d4a4-11e9-91c3-5b062a607157.jpg)
> ![2131568184781_ pic](https://user-images.githubusercontent.com/15811655/64674744-109d9a80-d4a4-11e9-8727-83741f553a0e.jpg)
> ![2161568184784_ pic](https://user-images.githubusercontent.com/15811655/64674752-15fae500-d4a4-11e9-8010-1f8a19b77979.jpg)
> ![581568184998_ pic](https://user-images.githubusercontent.com/15811655/64674883-607c6180-d4a4-11e9-9496-51ce20cf1e25.jpg)
> 
> ## Logs
> ```
> Running Gradle task 'assembleDebug'...                                  
> Running Gradle task 'assembleDebug'... Done                         9.8s
> Built build/app/outputs/apk/debug/app-debug.apk.
> Installing build/app/outputs/apk/app.apk...                        38.0s
> E/        (14396): nFreeSize: 41264242688
> E/        (14396): nFreeSize: 41264242688
> Syncing files to device vivo X20A...                                    
>  4,279ms (!)                                       
> 
> 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
> An Observatory debugger and profiler on vivo X20A is available at: http://127.0.0.1:62903/TDA9hwhBM1E=/
> For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
> 
> E/        (14396): nFreeSize: 41261236224
> E/        (14396): nFreeSize: 41261129728
> 
> E/JVMContainer VMSG(14396): RegisterNatives
> E/        (14396): nFreeSize: 41259544576
> E/        (14396): nFreeSize: 41259524096
> E/        (14396): nFreeSize: 41259458560
> E/        (14396): nFreeSize: 41258377216
> E/        (14396): nFreeSize: 41258094592
> E/        (14396): nFreeSize: 41257959424
> E/        (14396): nFreeSize: 41257025536
> E/        (14396): nFreeSize: 41256558592
> E/        (14396): nFreeSize: 41256087552
> E/        (14396): nFreeSize: 41255469056
> E/        (14396): nFreeSize: 41255452672
> E/        (14396): nFreeSize: 41255383040
> E/        (14396): nFreeSize: 41255305216
> E/        (14396): nFreeSize: 41255301120
> E/        (14396): nFreeSize: 41255288832
> E/        (14396): nFreeSize: 41255280640
> E/        (14396): nFreeSize: 41255342080
> D/PhoneWindow(14396): DEBUG_ALIENSCREEN:getRotation mRotation=0
> I/DecorView(14396): setWindowBackground mBackgroundPadding = Rect(0, 0 - 0, 0), mFramePadding = Rect(0, 0 - 0, 0), pkg = com.lalamove.huolala.edriver
> I/TouchMotionHandler(14396): handler onAttached
> I/TouchMotionHandler(14396): window type filtered
> I/View    (14396): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 0, 0), windowBounds = Rect(0, 0 - 0, 0), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{abea637 V.ED..... ......I. 0,0-0,0}
> I/View    (14396): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 0, 0), windowBounds = Rect(0, 0 - 0, 0), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{abea637 V.ED..... ......I. 0,0-0,0}
> I/View    (14396): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 1080, 1794), windowBounds = Rect(0, 0 - 1080, 1794), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{abea637 V.ED..... ......ID 0,0-1080,1794}
> D/baidu_location_client(14396): baidu location connected ...
> 
> D/PhoneWindow(14396): DEBUG_ALIENSCREEN:getRotation mRotation=0
> I/DecorView(14396): setWindowBackground mBackgroundPadding = Rect(0, 0 - 0, 0), mFramePadding = Rect(0, 0 - 0, 0), pkg = com.lalamove.huolala.edriver
> I/TouchMotionHandler(14396): handler onAttached
> I/TouchMotionHandler(14396): window type filtered
> I/View    (14396): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 0, 0), windowBounds = Rect(0, 0 - 0, 0), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{b6c239c V.ED..... ......I. 0,0-0,0}
> I/View    (14396): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 0, 0), windowBounds = Rect(0, 0 - 0, 0), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{b6c239c V.ED..... ......I. 0,0-0,0}
> I/View    (14396): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 1080, 1794), windowBounds = Rect(0, 0 - 1080, 1794), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{b6c239c V.ED..... ......ID 0,0-1080,1794}
> D/baidu_location_client(14396): baidu location connected ...
> ```
> 
> ## quit and run again,every thing is fine ,the following is the log,it seems error logs is less
> ```
> E/JVMContainer VMSG(14878): RegisterNatives
> E/        (14878): nFreeSize: 41251532800
> D/PhoneWindow(14878): DEBUG_ALIENSCREEN:getRotation mRotation=0
> I/DecorView(14878): setWindowBackground mBackgroundPadding = Rect(0, 0 - 0, 0), mFramePadding = Rect(0, 0 - 0, 0), pkg = com.lalamove.huolala.edriver
> I/TouchMotionHandler(14878): handler onAttached
> I/TouchMotionHandler(14878): window type filtered
> I/View    (14878): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 0, 0), windowBounds = Rect(0, 0 - 0, 0), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{81e2a77 V.ED..... ......I. 0,0-0,0}
> I/View    (14878): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 0, 0), windowBounds = Rect(0, 0 - 0, 0), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{81e2a77 V.ED..... ......I. 0,0-0,0}
> I/View    (14878): updateSystemUiVisibility, blackBackground = true, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(0, 0 - 1080, 1794), windowBounds = Rect(0, 0 - 1080, 1794), view = TextureView:com.baidu.mapsdkplatform.comapi.map.ac{81e2a77 V.ED..... ......ID 0,0-1080,1794}
> D/NetworkSecurityConfig(14878): Using Network Security Config from resource network_security_config debugBuild: true
> I/DpmTcmClient(14878): RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
> I/DpmTcmClient(14878): RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
> ```
> 
> ```
> [✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
>     • Flutter version 1.7.8+hotfix.4 at /Users/xingdi/Documents/flutter
>     • Framework revision 20e59316b8 (8 weeks ago), 2019-07-18 20:04:33 -0700
>     • Engine revision fee001c93f
>     • Dart version 2.4.0
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/xingdi/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.2.1, Build version 10E1001
>     • CocoaPods version 1.7.3
> 
> [✓] iOS tools - develop for iOS devices
>     • ios-deploy 1.9.4
> 
> [!] Android Studio (version 3.4)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [✓] VS Code (version 1.38.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.4.1
> 
> [✓] Connected device (1 available)
>     • vivo X20A • 6de3dc08 • android-arm64 • Android 8.1.0 (API 27)
> 
> ! Doctor found issues in 1 category.
> ```
你好，你这个问题解决了么？

**Comment by DylanXing** [comment]
@kangwang1988 大佬我怎么加不了from china标签
@junyao-yu  还没有解决

**Comment by ozyl** [comment]
Anyone solve this?

**Comment by libo1223** [comment]
I have the same question in vivo nex s.The test of VirtualDisplay is also ok.What's more , it open the demo of flutter_webview doesn't play black screen.(maybe by chance.) also , click the black sreen ,webview can receive the click events and the black screen will display.if you click the button on webview when it is black screen,
The button will be triggered , black screen will disappear

**Comment by xuzhengquan** [comment]
Anyone solve this?

**Comment by ikkyu0319** [comment]
Anyone solve this?

**Comment by DylanXing** [comment]
connect the VIVO system developer several times And get nothing help.
heard that VIVO rewrite the webview in system.
vivo is in my black list

**Comment by suhail-zartek** [comment]
Same situation in OPPO Color OS7 while using exoplayer.The audio plays well. But the video is on the black screen. Please reopen this issue

**Comment by darshankawar** [comment]
@DylanXing 
Is this still a valid issue using latest Flutter version ?
If so, can you provide updated `flutter doctor -v` and a minimal reproducible use case that could help to replicate the issue ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Rickyballs** [comment]
My app will be black when I open the web for the first time, but it will disappear when I click or open the app for the second time.Strangely, it only appears in a certain version of a certain brand, such as vivo X20.

A special log will be printed before the problem occurs

2021-01-26 11:11:14.699 31077-31448/com.app.companyE/chromium: [ERROR:service_manager.cc(156)] Connection InterfaceProviderSpec prevented service: content_renderer from binding interface: blink::mojom::BudgetService exposed by: content_browser

android version:8.1.0
devices:vivo x20
webview_flutter:1.0.7
flutter_version:1.22.2

> I have the same question in vivo nex s.The test of VirtualDisplay is also ok.What's more , it open the demo of flutter_webview doesn't play black screen.(maybe by chance.) also , click the black sreen ,webview can receive the click events and the black screen will disapper.if you click the button on webview when it is black screen,
> The button will be triggered , black screen will disappear

**Comment by Rickyballs** [comment]
@darshankawar

**Comment by darshankawar** [comment]
> If so, can you provide updated `flutter doctor -v` and a minimal reproducible use case that could help to replicate the issue ?
> Thanks.

@Rickyballs 
I'd suggest you to open a new issues by providing above mentioned details to better address your issue.

**Comment by franticn** [comment]
Same error in vivo iQOO Neo, only the first time install app and open page which contains webview_flutter widget
- Android 10
- Flutter 1.17.5
- Dart 2.8.4
- Android Studio 4.1

**Comment by pedromassangocode** [comment]
> * Flutter 1.17.5

@franticn please upgrade Flutter, your current version is six months old.

**Comment by franticn** [comment]
> please upgrade Flutter, your current version is six months old.
Sorry, I can't.
We use `FlutterBoost` to manage flutter engine,but `FlutterBoost` only support specific Flutter versions
