### ISSUE TITLE
[Web] 'flutter devices' does not list chrome as a device when Flutter is in STABLE channel.

### ISSUE THREAD

**Issue by yuvi1947** [flutter/flutter#40232]

**Comment by holoc285** [comment]
Flutter on the web just support from the master or dev channel

**Comment by yuvi1947** [comment]
Is there any timeline available for using it in STABLE and BETA channels as well ?

**Comment by holoc285** [comment]
Unfortunately, I don't know, I am also waiting for a release in stable and beta

**Comment by chenfei-io** [comment]
yeah, wondering why?

**Comment by vishna** [comment]
I've run into this as well. As the [docs](https://flutter.dev/docs/development/platform-integration/web) say:

> As of the 1.9 release, the web version of Flutter is available as a technical preview on the master channel.

...which I missed while reading those docs the first time 😿 maybe that should be written in red.

**Comment by chenfei-io** [comment]
```

**Comment by BondarenkoStas** [comment]
Thank you @chenfei-io ! @yuvi1947 Please report if that solved your issue.

**Comment by yuvi1947** [comment]
So I guess we have to just wait for it to be available in stable and beta channels.

I'll use either master or Dev channels for time being.

**Comment by hiashutoshsingh** [comment]
how to run in firefox and safari with the command line ?
