### ISSUE TITLE
Add a target OS to an existing project

### ISSUE THREAD

**Issue by amreniouinnovent** [flutter/flutter#40231]
## Use case

I have a flutter project that supports iOS and Android and I want to support web platform

## Proposal

I want a flutter command for adding web support or desktop support with the required files like index.html for web and so on.

Suggested command `Flutter add -d web`

**Comment by Saifallak** [comment]
the only needed file is
index.html
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>untitled</title>
</head>
<body>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
```

**Comment by jonahwilliams** [comment]
See https://flutter.dev/docs/get-started/web#add-web-support-to-an-existing-app
