### ISSUE TITLE
Visibility not restored for Hero after pop

### ISSUE THREAD

**Issue by hahafather007** [flutter/flutter#40239]
After clicking the `Hero` widget to jump to a list page, scroll down the list until the `Hero` widget of the corresponding tag leaves the screen and then return to the page. The `Hero` widget of the previous page will be blank. This is a very serious problem, and now our online project has been plagued by this problem.
<img width="403" alt="QQ20190911-173956@2x" src="https://user-images.githubusercontent.com/23414420/64686778-d04a1680-d4bb-11e9-87be-09e187921060.png">
<img width="403" alt="QQ20190911-174016@2x" src="https://user-images.githubusercontent.com/23414420/64686782-d213da00-d4bb-11e9-8f41-00e58de74cfc.png">
Flutter version:
```
[✓] Flutter (Channel beta, v1.7.8+hotfix.4-pre.7, on Mac OS X 10.14.6 18G87,
    locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.2.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] Connected device (1 available)
```
Reproduce code like this:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: GestureDetector(
          onTap: () {
            Navigator.of(context).push(MaterialPageRoute(builder: (context) {
              return Scaffold(
                body: ListView(
                  children: <Widget>[
                    Center(
                      child: Hero(
                        tag: "111",
                        child: Container(
                          width: 50,
                          height: 50,
                          color: Colors.blue,
                        ),
                      ),
                    ),
                    Container(
                      height: 2000,
                    ),
                  ],
                ),
              );
            }));
          },
          child: Hero(
            tag: "111",
            child: Container(
              width: 50,
              height: 50,
              color: Colors.blue,
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by hahafather007** [comment]
@ianloic @anaisbetts @sgraham @sethladd

**Comment by goderbauer** [comment]
@chunhtai This may be caused by your change in https://github.com/flutter/flutter/pull/37341. Maybe you can take a look?

**Comment by LongCatIsLooong** [comment]
@goderbauer It's probably not introduced in the PR. We didn't handle the case where `fromHero` is `null` so the hero transition technically lasts forever. Working on a fix now.

**Comment by goderbauer** [comment]
But prior to that PR we would restore the visibility of the from Hero once the flight is completed so it would always be visible when you do the pop, no?

**Comment by LongCatIsLooong** [comment]
Sorry I phrased it poorly. We set offstage to false when the animation finishes (i.e. in an animation status change callback) but there's no animation to begin with because the `fromHero` is null (garbage collected by the `ListView`).

**Comment by chunhtai** [comment]
I wonder what is the expected behavior of this situation
There are two possible scenarios.
1, the fromHero is destroyed
2, the fromHero is keptalive but outside viewport.

**Comment by LongCatIsLooong** [comment]
My original plan was to fade in the toHero (since we're fading out the hero if the flight is aborted) but it doesn't look as good as I expected because the hero `OverlayEntry` is the topmost `OverlayEntry`, so it's entirely visible during the transition, even when the from route overlaps with it. So I'm planning to end the hero transition right away if fromHero is null. Thoughts?

**Comment by chunhtai** [comment]
@LongCatIsLooong I think ending it if fromHero is null make sense. What about the fromHero is keptalive, will the hero transition trigger in this case?

**Comment by LongCatIsLooong** [comment]
Oh I didn't realize #37341 keeps the original invisible.

**Comment by dshukertjr** [comment]
Why is this issue closed? It is not solved.

**Comment by LongCatIsLooong** [comment]
@dshukertjr are you using the master channel? If you are and the issue is still reproducible, could you provide a minimal repro?

**Comment by dshukertjr** [comment]
@LongCatIsLooong No, I'm using the stable channel. Is the issue solved in the master channel?

**Comment by LongCatIsLooong** [comment]
@dshukertjr it should be. The issue was closed because #40306 was merged.

**Comment by aleksandar-radivojevic** [comment]
This issue is not solved in 1.9.1+hotfix.4 !!!!

**Comment by vitor-gyant** [comment]
@LongCatIsLooong I'm still facing this issue on stable branch version 1.9.1+hotfix4. Could you please double check if the issue is solved in this version ? Thanks.

**Comment by LongCatIsLooong** [comment]
@vitor-gyant it is not in 1.9.1. The earliest version with the fix is v.1.10.14: https://github.com/flutter/flutter/commit/64300123faa692c1ac3d8feeba171a6e079a741e.

**Comment by vitor-gyant** [comment]
@LongCatIsLooong I see. Any plans to cherry pick it to 1.9 on the stable branch ?

**Comment by LongCatIsLooong** [comment]
Unfortunately, not that I know of. You could try applying the patch locally, or consider switching to dev/master: https://github.com/flutter/flutter/wiki/Flutter-build-release-channels.

**Comment by iassal** [comment]
This caused a severe regression in our app as we use hero animations for input fields. Had to deprecate all pop calls as a hotfix

**Comment by LongCatIsLooong** [comment]
FYI the hotfix request is being evaluated.

**Comment by vitor-gyant** [comment]
@tvolkert Hot fix is a must for us, at least. Keeping a fork of the flutter repo just to be able to apply the cherry pick creates a big maintenance issue. Moreover, our app uses several hero animations in the primary flows and now they simply don't work and the visual impact is a blocker for the release.

We've started the migration process to the master branch but it will take time to finish plus the QA rounds. Since we also have app2app changes on master this will slow down us for a while if the hot fix is not approved.

**Comment by chickenblood** [comment]
What is the status of this? Is there a workaround? This bug is affecting my new app which I hoped to get out on December 1. It seems like a common pattern that would affect many apps.

**Comment by chickenblood** [comment]
Nevermind. I just did flutter upgrade and it looks like it has made it into stable.

**Comment by limyeanfen** [comment]
> Nevermind. I just did flutter upgrade and it looks like it has made it into stable.

May i know which version you upgraded ?

**Comment by iassal** [comment]
@limyeanfen I think it was fixed in `Flutter 1.9.1+hotfix.6` as per the head commit here https://github.com/flutter/flutter/releases/tag/v1.9.1%2Bhotfix.6

**Comment by Deepanshu-Rohilla** [comment]
It is not fixed in the latest version

**Comment by violet-dev** [comment]
How to fix it?

**Comment by LongCatIsLooong** [comment]
The bug you're seeing is likely a different bug, since this one has long been hotfixed on the stable branch (unless you're still on a version older than 1.9.1). Could you file a new issue using [this link](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=BUG.md&title=)?
