### ISSUE TITLE
I can not found the button listed in the Android Studio setup procedure.

### ISSUE THREAD

**Issue by y-skt** [flutter/flutter#40245]
https://flutter.dev/docs/get-started/editor?tab=androidstudio

In 4th step of plugins install.
[Browse repositories] button is no longer existed on latest stable version now.

latest stable 3.5
https://developer.android.com/studio/releases#3-5-0
<img width="1002" alt="スクリーンショット 2019-09-11 19 37 53" src="https://user-images.githubusercontent.com/53812251/64693909-56258c00-d4d3-11e9-8fd0-97bda3b79bc1.png">

3.1
<img width="1019" alt="スクリーンショット 2019-09-11 19 33 01" src="https://user-images.githubusercontent.com/53812251/64693927-6178b780-d4d3-11e9-93e9-25d13aaca8bf.png">

**Comment by VladyslavBondarenko** [comment]
Hi @y-skt ,
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
