### ISSUE TITLE
'constraints.hasBoundedHeight': is not true

### ISSUE THREAD

**Issue by Rutuja02** [flutter/flutter#40242]

**Comment by BondarenkoStas** [comment]
@Rutuja02 Unfortunately, this report does not have any actionable information - it’s not clear if this is a bug in user code, a bug in the framework, or something else entirely.
Please feel free to re-open if you can add the following information:
The version of Flutter you’re using
The output of flutter doctor -v
The full exception you see
A minimal reproduction that leads to this exception.

Roughly looking on the error, probably you didn't specify the height of a box, and the infinite box height will lead to infinite box size.
