### ISSUE TITLE
Android Nexus5 Text 'ja' Locale is not working

### ISSUE THREAD

**Issue by sho-1990** [flutter/flutter#40246]
Flutter is very good. Sorry, My English is so bad.

Set 'Ja' Locale. Almost good work, but not work on Nexus5.
What should I do?

I tried this. But not work.
https://medium.com/@najeira/flutter-and-cjk-font-4e372b37083c
https://medium.com/@najeira/flutter-and-cjk-font-selection-2-2ba06e32dd8d

## Logs

|nexus 5 device screen shot|expected screen shot(This is other device)|
|---|---|
|![screen](https://user-images.githubusercontent.com/11487727/64694118-e9f75800-d4d3-11e9-8ff2-d67241db6ae7.png)|![screen](https://user-images.githubusercontent.com/11487727/65222855-e890e580-dafa-11e9-9eaf-55b18d9e644c.png)|

source code
```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'test',
      locale: Locale('ja', 'JP'),
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: [
        Locale('ja', 'JP'),
      ],
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("test"),),
      body: Container(
        padding: const EdgeInsets.only(top: 20),
        constraints: BoxConstraints.expand(),
        child: Column(
          children: <Widget>[
            Text("半角英数記号", locale: Locale('ja', 'JP'),),
            Text("今骨刃直", locale: Locale('ja', 'JP'),),
          ],
        ),
      ),
    );
  }
}


```

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale ja-JP)
    • Flutter version 1.7.8+hotfix.3 at /usr/local/lib/flutter
    • Framework revision b712a172f9 (9 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sh.sato/Library/Android/sdk
    • Android NDK at /Users/sh.sato/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (version 2.3)
    • Android Studio at /Applications/bk-androidstudio2.3.3/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8369

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Nexus 5 • 06dedc2f13cc87b6 • android-arm • Android 6.0 (API 23)

! Doctor found issues in 1 category.

```

Thank you very much for reading.

**Comment by GaryQian** [comment]
Have you tried setting the locale of your nexus 5 device to `ja_JP`? This can help determine if this bug is in the text widget stack or the localization stack.

@cbracken Can you confirm the text is indeed not the Japanese version of the characters?

**Comment by sho-1990** [comment]
@GaryQian 
Thank you for much for your reply.
My nexus 5 device locale is "ja-JP".
Please see below adb_command_log and screenshot.

### Log
```
$ adb shell getprop|grep locale
 [persist.sys.locale]: [ja-JP]  
 [ro.product.locale]: [en-US]
```

### Screenshot
![screen](https://user-images.githubusercontent.com/11487727/65213219-3fd58c80-dae0-11e9-994c-f8e09380eb81.png)

**Comment by sho-1990** [comment]
I tried run app on flutter v1.0.0. 
Not reproduced and good japanese text.
I hope this will help.

**Comment by sho-1990** [comment]
I added expected screen shot.(this is other device)

**Comment by sho-1990** [comment]
I tried run app on flutter between v1.0.0 and v1.7.8+hotfix.3.
v1.1.4: Not reproduced
v1.1.5: Reproduced

v.1.1.5 change caused ?

**Comment by GaryQian** [comment]
One more thing, if you have other devices available, do you know if this is only on Nexus 5 or other devices as well?

**Comment by sho-1990** [comment]
@GaryQian 
As far as I know, Only Nexus 5.
I tried Pixel 3, Galaxy s8, Xperia XZ2. There are OK.

**Comment by GaryQian** [comment]
flutter/engine#12426 has landed, can you try this now on master? It may fix this, but it also may not.

**Comment by sho-1990** [comment]
@GaryQian
Thank you so much. 
Text 'ja' worked on Nexus 5 !!

I have one more question.
A few days later, I must release app.
If possible I want to release on v1.7.8+hotfix.3. and this fix.
Is there any solution?

**Comment by cbracken** [comment]
@sho-1990 thanks for confirming! We'll close this out.

It's unlikely this will make it as a hotfix on 1.7.8 since the latest release branch is 1.9, but you could choose to build off master, or wait until this graduates to beta branch.

**Comment by sho-1990** [comment]
Thank you for your replay.
My team decided this fix into next release.

Thanks.
