### ISSUE TITLE
Api "endRecording().toImage" May appear empty data in version "1.9.1+hotfix.2"

### ISSUE THREAD

**Issue by a27919478** [flutter/flutter#40244]
First , I paint a picture on the canvas and call "endRecording().toImage" to save the image. It is possible to return empty data.This operation may need to be repeated multiple times.
This problem does not appear in the version "v1.7.8+hotfix.4".

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale zh-Hans-HK)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.37.1)
[!] Connected device
    ! No devices available
```

**Comment by BondarenkoStas** [comment]
@a27919478  Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by a27919478** [comment]
@BondarenkoStas Maybe it's my code problem, I didn't reproduce it in DEMO.

**Comment by DavidKuennen** [comment]
Having the same issue after updating. It seems to be random (maybe a race condition).

**Comment by a27919478** [comment]
@DavidKuennen Yes, I am not having this problem in "v1.7.8+hotfix.4", so I am confused too.

**Comment by DavidKuennen** [comment]
Yes and I don't seem to find any way to fix it.

**Comment by DavidKuennen** [comment]
I was able to reproduce it and create a demo, so I opened another issue of this.

**Comment by a27919478** [comment]
I will attention to your issue.

**Comment by a27919478** [comment]
@DavidKuennen I will attention to your issue
