### ISSUE TITLE
How to stop this constant stream of logs in webview screen?

### ISSUE THREAD

**Issue by amsmu** [flutter/flutter#40247]
`I/BufferQueueProducer(17118): [SurfaceTexture-0-17118-0](this:0xcf5ce000,id:0,api:1,p:414,c:-1) connect(P): api=1 producer=(414:???) producerControlledByApp=false
D/BufferQueueProducer(17118): [SurfaceTexture-0-17118-0](this:0xcf5ce000,id:0,api:1,p:414,c:-1) cancelBuffer: slot 0
D/BufferQueueProducer(17118): [SurfaceTexture-0-17118-0](this:0xcf5ce000,id:0,api:1,p:414,c:-1) cancelBuffer: slot 0`

I'm getting the constant stream of the above-mentioned log as soon as webview activity is loaded. This stream is annoying and I'm unable to see my own logs. How to stop them or at least filter them? I'm using visual studio code.

**Comment by FarmaanElahi** [comment]
@amsmu  Are you testing on emulator?

**Comment by raphael-bmec-co** [comment]
Same issue. Testing on device. Any assistance would be great.

**Comment by TahaTesser** [comment]
Hi @amsmu 
if you're still experiencing this problem with latest stable, please create a new issue and provide the information required in the template.
Thank you
