### ISSUE TITLE
[Web] When will Flutter Web go out of Technical Preview

### ISSUE THREAD

**Issue by hashweather** [flutter/flutter#40255]
I so much love flutter for Web and I was wondering, When will it go out of technical preview and become production ready?

I so much hate CSS but I see myself loving Web Development once again because of flutter

Thanks

**Comment by BondarenkoStas** [comment]
@hashweather I believe that flutter/flutter repo issues is not the right place for the question. My guess is that if there was an answer to it, it would be already out. Please see See https://flutter.dev/community for support options. And thank you for such a lovely feedback!
