### ISSUE TITLE
defaultBinaryMessenger was accessed before the binding was initialized ...

### ISSUE THREAD

**Issue by EmadKaizen** [flutter/flutter#40253]
## Steps to Reproduce

1. Upgrade Flutter
2. Run existing project.

## To solve this error I comment first three lines.

```
void main() async {
  // await SystemChrome.setPreferredOrientations([
  //   DeviceOrientation.portraitUp,
  // ]);

 runZoned<Future<void>>(() async {
    runApp(LoadingProvider(
      themeData: LoadingThemeData(
        animDuration: const Duration(milliseconds: 0),
        backgroundColor: Colors.transparent,
      ),
      child: MtApp(),
      loadingWidgetBuilder: (ctx, data) {
        return Center(
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              new CircularProgressIndicator(),
            ],
          ),
        );
      },
    ));
  }, onError: (dynamic error, dynamic stackTrace) {
    _reportError(error, stackTrace);
  });
}
```

## Error

```
Exception has occurred.
FlutterError (ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.)
```

## Flutter doctor

```
[√] Flutter (Channel master, v1.10.2-pre.36, on Microsoft Windows [Version
    10.0.17763.678], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Chrome - develop for the web
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code (version 1.38.0)
[√] Connected device (2 available)

• No issues found!
```

**Comment by BondarenkoStas** [comment]
Seems related to #38464.
https://stackoverflow.com/a/57703060 may possible help
Please report if you experience the same error after calling ```WidgetFlutterBinding.ensureInitialized()``` as first thing in Main.

**Comment by EmadKaizen** [comment]
Adding ```  WidgetsFlutterBinding.ensureInitialized();``` as fisrt code in main solve this issue, Thanks .

**Comment by primemb** [comment]
i have same issue after update to v1.12.13 hotfix 5. i tried `WidgetFlutterBinding.ensureInitialized()` but it not work , the app is running but i get an error in run log

**Comment by maryfalcon** [comment]
Have the same issue at 1.12.13+hotfix.5. Like @primemb said: After adding line WidgetFlutterBinding.ensureInitialized() app works, but there's an error in log.

**Comment by bikash-rai** [comment]
I also have the same error with v1.12.13 hotfix 5. My main code is 

`WidgetsFlutterBinding.ensureInitialized();  
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
      .then((_) {
    runApp(myApp());`

**Comment by 5lineofcode** [comment]
> Seems related to #38464.
> https://stackoverflow.com/a/57703060 may possible help
> Please report if you experience the same error after calling `WidgetFlutterBinding.ensureInitialized()` as first thing in Main.

its, WidgetsFlutterBinding.ensureInitialized();

**Comment by alexZaicev** [comment]
Why is this issue is closed, when some developers including me are experiencing the same error in their log? The app runs, but error still exists, when trying to access Crashlytics for example

**Comment by MoffatMore** [comment]
Guys i'm also experiencing the same issue with v1.12.13 hotfix 5
````
main() async {
  SharedPreferences prefs = await SharedPreferences.getInstance();
  var token = prefs.getString('token');
  var mode = prefs.getString('mode');
  var id = prefs.getString('uid');

  WidgetsFlutterBinding.ensureInitialized();
  runApp(App(
    auth: token != null,
    client: Config.initailizeClient(),
    mode: mode ?? "",
    id: id ?? "",
  ));
}
```
what should i do guys?

**Comment by DJFreh** [comment]
I had same issue and been fixed by removing codes 
void main() {
//  WidgetsFlutterBinding.ensureInitialized();
//  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
//      .then((_) {
  runApp(new MyApp());
//  });
}

Flutter 1.14.2-pre.53
hope help somone.

**Comment by leonetosoft** [comment]
Add:

`WidgetsFlutterBinding.ensureInitialized();`

In first line main() ... 
```Flutter 1.13.6 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 659dc8129d (5 weeks ago) • 2019-12-30 09:24:47 -0800
Engine • revision bdc9708d23
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)```

**Comment by MarFelix** [comment]
Para mi funciono  WidgetsFlutterBinding.ensureInitialized();

**Comment by Hassan-Fa** [comment]
i'm having the same problem and channel Master and Beta both have this problem (Flutter 1.15.17 • channel beta)

- not using async main()
getting sharedpref. instance in initstate() of one of the widgets was causing the problem
and i'm not sure why but putting it inside a try-catch was the only thing that solved it (didn't throw, actually worked in a try-catch 🤔 )

does someOne know what's going on ?
