### ISSUE TITLE
Remove Windows ephemeral directory during a flutter clean

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#40265]
## Proposal

Remove the new [Windows ephemeral directory](https://github.com/flutter/flutter/pull/40194) during a `flutter clean` to match macOS behavior.

\cc @stuartmorgan

**Comment by stuartmorgan** [comment]
Whoops, forgot about that when I added it. We should indeed do that. (I'll try to remember to do that in the initial PR when I update Linux to have one.)
