### ISSUE TITLE
Can't use a Dismissible with a TextField

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#40271]
Putting a TextField in a Dismissible widget makes the Dismissible unable to capture drag gestures.

## Steps to Reproduce

1. Go to https://dartpad.dev/embed-flutter.html?id=ac6b3d73b86f584da1f86d1e8574b9ac
2. Drag the checkbox to the right
3. observe Dismissible widget works
4. drag the text field to the right
5. observe the Dismissible widget doesn't work

On iOS, the list items can be dismissed by dragging from the center.

**Comment by lukepighetti** [comment]
I'm having a related problem where you cannot use any horizontal scrolling widgets inside a Dismissible even if it's directoin is DismissDirection.down

**Comment by theochampion** [comment]
I'm also having issues with textfield inside dismissible, it looses focus instantly

**Comment by Jpec57** [comment]
I am currently having the same issue with this on Android as well:
`
ListView.builder(
              physics: const AlwaysScrollableScrollPhysics(),
              itemCount: textEditingControllers.length,
              shrinkWrap: true,
              itemBuilder: (context, index) {
                return Dismissible(
                  key: UniqueKey(),
                  onDismissed: (DismissDirection direction){
                    textEditingControllers.removeAt(index);
                    print("Bye bye ${textEditingControllers[index].text}");
                  },
                  child: Padding(
                    padding: const EdgeInsets.only(left: 8.0, right: 8.0),
                    child: Card(
                      child: ListTile(
                        title: TextField(
                          controller: textEditingControllers[index],
                          maxLines: null,
                          keyboardType: TextInputType.multiline,
                          decoration: InputDecoration(
                            border: InputBorder.none,
                            labelStyle: TextStyle(fontSize: 20),
                            hintText: 'Possible answer ${index + 1}',
                          ),
                        ),
                      ),
                    ),
                  ),
                );
              })
`

replacing the TextField widget with a simple Text widget resolves the focus issue but I cannot get it to work with a TextField. Seems like @nturgut is right

**Comment by johnpryan** [comment]
I'm starting to think that putting the text selection first is more correct. When you [run the sample in DartPad](https://dartpad.dev/ac6b3d73b86f584da1f86d1e8574b9ac) it's natural to expect the text selection to take priority over the drag gesture, since it's further down in the widget tree.

@nturgut I think we should close this issue, @Jpec57 would you mind filing a separate issue for the Android behavior you are seeing?

**Comment by nturgut** [comment]
Thanks a lot for the feedback @johnpryan. I am closing the issue. Please feel free to create other issues  and cc me whenever you think text editing is behaving in unexpected ways. This our tracking project for text editing related issues: https://github.com/flutter/flutter/projects/57

**Comment by cornerman** [comment]
> I'm also having issues with textfield inside dismissible, it looses focus instantly

I am having the same issue. Any solution for this? I could not find any open issue tracking this problem.

**Comment by johnpryan** [comment]
@cornerman If the TextField takes up the entire Dismissible, then it will handle the gesture. But if you leave some some empty space then it will be handled by the Dismissible. In [this example](https://dartpad.dev/ac6b3d73b86f584da1f86d1e8574b9ac) if you drag the icon on the right it will work correctly.
