### ISSUE TITLE
High CPU usage on Linux

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#40281]
On current master, Linux is using 100% of a core just running the example. Unless I mis-tested before, this is a recent regression (see https://github.com/flutter/flutter/issues/35995#issuecomment-524016444)

**Comment by jason-simmons** [comment]
This started with the new run loop from https://github.com/flutter/engine/commit/fa161274fb5dfc8fbde383fb3db47e5666061a17

`FlutterDesktopRunWindowEventLoopWithTimeout` is passing `std::chrono::milliseconds::max()` to `GLFWEventLoop::WaitForEvents`, which expects a `std::chrono::nanoseconds`.  The resulting overflow causes a negative `duration_to_wait` and nonstop calls to `glfwPollEvents`.

However, if I change it to `std::chrono::nanoseconds::max()`, then the application does not seem to render correctly.

**Comment by jason-simmons** [comment]
The `std::chrono::nanoseconds::max()` fix was causing the app to become unresponsive because tasks posted by the engine were not being executed promptly.

This happens because `GLFWEventLoop::WaitForEvents` is holding the `task_queue_mutex_` during the call to `glfwWaitEventsTimeout`.  This prevents `GLFWEventLoop::PostTask` from enqueuing tasks until the wait completes.

**Comment by stuartmorgan** [comment]
> The resulting overflow causes a negative `duration_to_wait`

Good find. I was assuming that the time conversion between durations would handle that in a reasonable way (using the max of the new duration type if it was too large to express) rather than overflow.

> `GLFWEventLoop::WaitForEvents` is holding the `task_queue_mutex_` during the call to `glfwWaitEventsTimeout`

Ouch, indeed it is. I completely missed that in review.

Assigning to you since it sounds like you have a fix in progress, but feel free to assign to me if you aren't going to have time to post a PR.
