### ISSUE TITLE
catch network error exception code in google_sign_in plugin

### ISSUE THREAD

**Issue by Reekoooo** [flutter/flutter#40288]
in google_sign_in_plugin ,
How to catch network error exception ? I checked the android side of the plugin , if the exception is not ApiException and it is  RuntimeExecutionException will finishWithError (ERROR_REASON_EXCEPTION, e.toString()) which means in Dart  I will recieve a PlatformException with code 'exception'  but I need to be able to recieve a proper code that I can take action upon, 

Am I missing something ?

**Comment by csells** [comment]
@Reekoooo Please ask questions like these on Stackoverflow. Thanks!
