### ISSUE TITLE
[web] Add screenshot test capability to flutter/flutter

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#40297]
We currently do not run any screenshot Web tests. We need to build this capability.

It seems like the easiest way to achieve this is to piggyback on @Piinks' Skia gold work in Flutter for mobile.

**Comment by jonahwilliams** [comment]
Original testing here: https://github.com/flutter/flutter/pull/34117. I can investigate re-opening. 

I believe @chingjun was also interested in this.

**Comment by yjbanov** [comment]
@jonahwilliams I'm just populating the infra project with issues, but if you are interested in getting this off the ground, for sure!

**Comment by chingjun** [comment]
Fixed in #45530
