### ISSUE TITLE
[WIDGET TEST] Colors are not compared in GOLDEN TESTS 

### ISSUE THREAD

**Issue by snickersv2** [flutter/flutter#40295]
Steps to Reproduce:
1. Create a test for a widget containing Text and PieChart widgets.
(https://pub.dev/packages/charts_flutter, https://github.com/google/charts/blob/master/charts_flutter/lib/src/pie_chart.dart)
- PieChart colors should vary per data

2. add a line to compare golden file
await expectLater(find.byType(Container), matchesGoldenFile('goldenImageFile.png'));

3. generate golden image files using the command below and confirm that image files are created in the project:
flutter test --update-goldens test/widget_test.dart

4. run the test command below to confirm the test:
flutter test test/widget_test.dart

5. Change color of the Text and if there is a PieChart, change the values in the PieChart as well

6. run the test command below again and notice the test still PASSED INSTEAD OF FAILED:
flutter test test/widget_test.dart

flutter doctor:
```
/Users/user/Documents/Flutter/sdk/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/user/Documents/Flutter/sdk/flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.4.3
    • Dart plugin version 191.6183.87

[✓] Connected device (1 available)
    • SM test • serialnumber • android-arm64 • Android 8.0.0 (API 26) (emulator)

• No issues found!
Process finished with exit code 0
```

**Comment by Piinks** [comment]
Hi @snickersv2,
Thanks for opening this issue! Would you be able to provide the two images that resulted in a false positive? 

On the version you are running these tests on, `Channel stable, v1.7.8+hotfix.4`, golden file tests are done via a bit-for-bit comparison, instead of pixel comparison. This can sometimes lead to inconsistent results like the one you have described. 

However, there is good news! 🎉 
A re-work of the golden file comparator is now available on the master and dev branches, the change is documented in #38473. This new comparator will compare pixels for better accuracy, _and_ it will even provide output so you can see the difference it detected. I welcome you to try it out and let me know if it works for you! 🙂

**Comment by snickersv2** [comment]
Hi @Piinks , i'm having trouble with master and dev branches so I can't try it out yet:

> Because every version of flutter_driver from sdk depends on intl 0.16.0 and charts_flutter >=0.5.0 depends on intl ^0.15.2, flutter_driver from sdk is incompatible with charts_flutter >=0.5.0.
So, because care_partner_app depends on both charts_flutter 0.8.0 and flutter_driver any from sdk, version solving failed.

Do you have any advise on this? Thank you :)

**Comment by Piinks** [comment]
Hey @snickersv2 
The fix for this is now available on the stable channel.
I am going to close this, but if your issue persists, feel free to re-open. :)
