### ISSUE TITLE
[web] Implement screenshot storage and comparison in flutter/engine tests

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#40300]
We need a solution for storing and robust screenshot comparison for flutter/engine Web tests. Only then we will be able to allow the tests to fail when screenshots do not match.

**Comment by ditman** [comment]
Implemented image-aware comparison here: https://github.com/flutter/engine/pull/12353

**Comment by yjbanov** [comment]
Fixed by https://github.com/flutter/engine/pull/12274
