### ISSUE TITLE
Rerun analysis after pub get (do not trust analyzer to reanalyze)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4031]
After the user runs `pub get`, we should always re-analyze in Atom. I saw a user today run `pub get`, and then wonder why Atom was complaining so much.

Turns out, the analyzer just didn't know to rerun. The fix was to "reanalyze sources", but our user didn't know about that option nor would expect they would need to take action.

Suggestion is to re-run analysis after `pub get` in Atom to eliminate the chance the analyzer misses whatever clues it's looking for when trying to re-analyze.

The bigger issue is, when the user sees all these errors, it's not clear what action they need to take. Is their code bad? Did the tool fail? What do I do now? Luckily, in this case, we can force a re-analyze at the appropriate time.

View of the Atom problems view after the user ran `pub get` (which should have fixed all these errors):

![img_20160518_140806](https://cloud.githubusercontent.com/assets/5479/15379507/bebca260-1d22-11e6-87f8-fa159d9e9bdb.jpg)

**Comment by sethladd** [comment]
cc @pq for the "need to reanalyze sources to get rid of errors"

**Comment by pq** [comment]
@devoncarew : is this a known issue?

**Comment by devoncarew** [comment]
No, at least not previously known to me. It sounds like the analysis server did not pick up on the changed `.packages` file.

**Comment by pq** [comment]
Yeah.  I'm shuddering at the thought of another `watcher` bug.

@sethladd : is this on the latest flutter tools?

**Comment by sethladd** [comment]
We might want to track how many times someone clicks "reanalyze sources". I still need to do it from time to time. The more important issue is: a new user probably wouldn't know how to resolve this.

**Comment by sethladd** [comment]
Codelab branch

**Comment by pq** [comment]
@jwren, @stevemessick : I'm curious.  What do we do in IntelliJ?  Do we rely on the file watcher to trigger a reanalysis or do we initiate from the IDE?  (I seem to recall in `DartEditor`, we had forced reanalysis as part of the pub action.)

**Comment by stevemessick** [comment]
@pq I'm not an expert on the IntelliJ virtual file system but I suspect this line would cause the file watcher to trigger re-analysis:
`VfsUtil.markDirtyAndRefresh(true, true, true, pubspecYamlFile.getParent());`
That's done after the pub command has executed. The way I read that is to cause the entire project file system to be refreshed.

The code that forces re-analysis,`DartAnalysisServerService.analysis_reanalyze()`, is only called by the menu action attached to `Reanalyze Sources`.

**Comment by pq** [comment]
Great.  Thanks for the details!

@devoncarew : it looks like we should consider doing something similar in atom?

**Comment by devoncarew** [comment]
I'm not sure the above call would tell the analysis server that the packages changed. It looks more like a refresh resources type thing from eclipse - to sync intellij's virtual filesystem with any on-disk changes that pub might have done.

I suspect the issue is that the analysis server is not recognizing changes in the .packages file.

**Comment by devoncarew** [comment]
> The bigger issue is, when the user sees all these errors, it's not clear what action they need to take. Is their code bad? Did the tool fail? What do I do now?

Yup, we should show something in-line at the top of the errors view which they can click on to run pub get, and run pub automatically when the pubspec file is changed from atom; I believe these are already tracked in other issues.
