### ISSUE TITLE
 io.flutter.embedding.engine.FlutterJNI.attachToNative 

### ISSUE THREAD

**Issue by RootKatherine** [flutter/flutter#40319]
Flutter 1.7.8+hotfix.5-pre.1 • channel unknown • unknown source
Framework • revision cccc4e51c5 (27 hours ago) • 2019-09-11 10:23:54 +0800
Engine • revision fee001c93f
Tools • Dart 2.4.0

flutter doctor
```
[✓] Flutter (Channel unknown, v1.7.8+hotfix.5-pre.1, on Mac OS X 10.14.4 18E226,
    locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Community Edition (version 2018.2.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)
```

**Comment by RootKatherine** [comment]
Occurs when leaving the flutter page.

phone ：
HUAWEI

**Comment by RootKatherine** [comment]
reference:
https://github.com/flutter/flutter/issues/33511

**Comment by BondarenkoStas** [comment]
I think it will be better to close the issue as you referenced it to a very similar one. If you disagree, please comment and I will reopen it asap.
