### ISSUE TITLE
Is there any interpolation function in flutter like the React Native? For example, I want the input range to be [0,50,80,100] and the output range to be [0,10,15,30]

### ISSUE THREAD

**Issue by 2534290808** [flutter/flutter#40311]
Is there any interpolation function in flutter like the React Native? For example, I want the input range to be [0,50,80,100] and the output range to be [0,10,15,30],Similar to the React  Native  [Animated. Value. Interpolate ](https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/nodes/AnimatedInterpolation.js)function

**Comment by VladyslavBondarenko** [comment]
Hi @2534290808 
[animated_interpolation](https://pub.dev/packages/animated_interpolation)
Closing the issue
