### ISSUE TITLE
How to disable corner folded when open flutter app

### ISSUE THREAD

**Issue by bestK** [flutter/flutter#40324]
![图像](https://user-images.githubusercontent.com/14979305/64759380-83247e00-d569-11e9-8e82-df0076b50f09.gif)

**Comment by bestK** [comment]
When open flutter app, screen bottom right will be like book corner folded，i don't wanna this

**Comment by VladyslavBondarenko** [comment]
Hi @bestK 
Closing, as this isn't an issue with Flutter itself,
This behavior probably depends on your device.
if you disagree please write in the comments and I will reopen it
Thank you
