### ISSUE TITLE
BottomNavigationBar 可以设置未读消息 (BottomNavigationBar can set unread messages)

### ISSUE THREAD

**Issue by dingchangsheng** [flutter/flutter#40326]
## Proposal
(Google translate) BottomNavigationBar can set unread messages

**Comment by LongCatIsLooong** [comment]
@dinglovezx are you looking for something like:
![image](https://user-images.githubusercontent.com/31859944/64902788-96ffdb00-d662-11e9-89ec-fa609f98ff68.png)

**Comment by dinglovezx** [comment]
yes ,That's all.

**Comment by Piinks** [comment]
This is now supported with the badge widget. See this example: https://api.flutter.dev/flutter/material/NavigationBar-class.html
