### ISSUE TITLE
Consider App side feature container

### ISSUE THREAD

**Issue by pouloghost** [flutter/flutter#40328]
Here in China, app tends to grow into a small os(giant app). Lots of features (each one will be developed by a small team) have to share quite little resources provided by real os. A container is desperately needed to monitor and manage resource usage inside a single app. My vision is each feature will run in a container/sand-box, all resource usage will be distributed by application into each container. A resource manager will coordinate usage between each feature to make important features go smoother.

**Comment by Balajiks-alt** [comment]
Okay I will help!

**Comment by xster** [comment]
Not clear what the concrete tasks are. Is this about containerizing runtimes? Dart Isolates already don't share memory. Is this about build artifacts? If so, it's https://github.com/flutter/flutter/issues/39707

**Comment by pouloghost** [comment]
> Not clear what the concrete tasks are. Is this about containerizing runtimes? Dart Isolates already don't share memory. Is this about build artifacts? If so, it's #39707

It's about containerizing runtimes, but the main purpose is about monitoring and restricting resource(all kinds of resource) usages, not just isolating memory.

For example, a youtube-like App in China will consist of video feature, live-show feature, gossip feature and so on. Each feature will try to use as many resources as possible whenever possible, but the App can't provide enough, thus the choppiness. What I'm proposing is flutter provide a solution like :

```
runInContainer(()=>VideoFeature.main(), networkProvider, fileProvider, memoryProvider...);
```

All resource access inside the runInContainer block must go through providers, and each one of the providers can be replaced by App maintainer with monitor and limitation inside them.

Overall, it's just like run app features in different JVM with all the startup parameters defined by operation engineers.

**Comment by xster** [comment]
> Most of the providers can be achieved by using a certain type of code formation, but memory usage limitation is just impossible.

Which half of the question are you asking for? For a mechanism to enforce a memory ceiling per Isolate? Or for a best practice guide for doing, essentially, dependency injection in Dart code?

**Comment by pouloghost** [comment]
> > Most of the providers can be achieved by using a certain type of code formation, but memory usage limitation is just impossible.
> 
> Which half of the question are you asking for? For a mechanism to enforce a memory ceiling per Isolate? Or for a best practice guide for doing, essentially, dependency injection in Dart code?

I was ask for a mechanism to enforce a memory ceiling per container/sandbox. Running feature code in different isolates is not practical.

**Comment by xster** [comment]
@mit-mit this is probably a feature request on the Dart VM than a Flutter feature.

**Comment by Hixie** [comment]
I'm marking this as "Declined" for now to indicate that we're unlikely to work on this in the near term (we're focusing on fixing bugs rather than adding new features at the moment; see our [roadmap](https://github.com/flutter/flutter/wiki/Roadmap) for details). Please let us know if this becomes a blocker for you. Thanks!

**Comment by Hixie** [comment]
I'm going to close this, as we have not seen much demand for this feature and it would be a significant departure from our current architecture. I would recommend approaching the Dart team directly about adding this to isolates.
