### ISSUE TITLE
Aot file size grows very fast.

### ISSUE THREAD

**Issue by pouloghost** [flutter/flutter#40323]
We are currently using 1.7.8 horfix4. Recently we added approximately 65000 lines of dart code(including import and everything), and the compiled libapp.so is approximately 3.5mb larger. Will compiler do more shrink in future releases?

**Comment by GaryQian** [comment]
@aam We talked about this. We should file this under dart also!

**Comment by zoeyfan** [comment]
@GaryQian 
Do you know if this issue is the same as (https://github.com/flutter/flutter/issues/40345)?

**Comment by xster** [comment]
It is. Let's dedupe it.
