### ISSUE TITLE
You have a dependency on `cached_network_image` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.

### ISSUE THREAD

**Issue by derolf** [flutter/flutter#40332]
When trying to run `flutter pub global run webdev serve` in my project:

```
You have a dependency on `cached_network_image` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
```

It's understandable because `cached_network_image` has some native dependencies.

For this, I'd like to create a "shim"-package for `cached_network_image` and add a dependency-override that is ONLY active for web target.

**Comment by yjbanov** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/39998. The issue is with `dart:io`. We are investigating what to do about it on the Web.
