### ISSUE TITLE
No error messages generated when fail to login using google_sign_in plugin

### ISSUE THREAD

**Issue by VickySalunkhe** [flutter/flutter#40337]
I am using google_sign_in plugin to login using firebase

when I press on button first time a popup comes showing account to select for login

but after I select an account  nothing happens and the popup disappears

there Is no log after that in console

and also the button doesn't work.

**Note**
I have been using the same code and plugin since last 5 months and there was no issue with this
but I guess the issue only arrived after I upgraded my flutter version to stable v1.9.1

log I received

> I/Timeline( 9559): Timeline: Activity_launch_request time:323024472 intent:Intent { act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.writco cmp=com.writco/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (has extras) }
I/Timeline( 9559): Timeline: Activity_launch_request time:323024507 intent:Intent { act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.google.android.gms (has extras) }
W/ResourceType( 9559): No package identifier when getting name for resource number 0x00000000

**flutter doctor**

> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.17763.678], locale en-US)

> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
> [√] Android Studio (version 3.4)
> [√] VS Code (version 1.38.0)
> [√] Connected device (1 available)
> 
> • No issues found!
>

**Comment by VickySalunkhe** [comment]
issue got solved
issue was caused because of [flutter_upi](https://pub.dev/packages/flutter_upi) library

> but the point here to note is there were no related error messages being generated while either building the app or while runtime


I solved this issue by just removing the code/functionality step by step which I added in backwards manner.

you can close this issue but I think the text highlighted can play part which needs to be solved.

**Comment by BondarenkoStas** [comment]
@VickySalunkhe Can you please specify how you solved it, just with removing the flutter_upi library or you needed to change something? Also, in which way #40339 is related to the current issue? flutter_upi causes no errors output to both plugins?

**Comment by VickySalunkhe** [comment]
I just removed the flutter_upi library which solved the issue wit h image_picker and google_signin  plugin

there were no error output thrown while using flutter_upi instead flutter _upi library is working fine

but for some unknown reasons both those plugins are not working

**Comment by TahaTesser** [comment]
Hi @VickySalunkhe 
if you're still experiencing this problem with latest stable, please create a new issue and provide the information required in the template.
Thank you
