### ISSUE TITLE
Flutter doctor show installed packages as missing on Windows 7

### ISSUE THREAD

**Issue by marinat** [flutter/flutter#40335]
flutter doctor -v
```
[√] Flutter (Channel master, v1.10.2-pre.54, on Microsoft Windows [Version 6.1.7601], locale ru-RU)
• Flutter version 1.10.2-pre.54 at C:\flutter
• Framework revision f5733f7a62 (4 hours ago), 2019-09-11 21:03:42 -0700
• Engine revision 7ea9884ab0
• Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

[X] Android toolchain - develop for Android devices
X Unable to locate Android SDK.
Install Android Studio from: https://developer.android.com/studio/index.html
On first launch it will assist you in installing the Android SDK components.
(or visit https://flutter.dev/setup/#android-setup for detailed instructions).
If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
You may also want to add it to your PATH environment variable.


[!] Visual Studio - develop for Windows (Visual Studio CommunityВ 2019 16.2.5)
• Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
• Visual Studio CommunityВ 2019 version 16.2.29306.81
X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
development with C++" workload, and include these components:
MSBuild
MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.21)
Windows 10 SDK (10.0.17763.0)

[!] Android Studio (not installed)
• Android Studio not found; download from https://developer.android.com/studio/index.html
(or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] Connected device (1 available)
• Windows • Windows • windows-x64 • Microsoft Windows [Version 6.1.7601]

! Doctor found issues in 3 categories.
```

![Безымянный (1)](https://user-images.githubusercontent.com/978076/64765986-df79a480-d54d-11e9-9fec-ab7ec0b292ca.jpg)

I tried to restart computer as described here: https://github.com/flutter/flutter/issues/39970

Unfortunately on windows 7 that not helped.

**Comment by marinat** [comment]
vswhere.exe -format json -utf8 -latest -prerelease -all
[
{
"instanceId": "ebc81321",
"installDate": "2019-09-11T08:23:59Z",
"installationName": "VisualStudio/16.2.5+29306.81",
"installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
"installationVersion": "16.2.29306.81",
"productId": "Microsoft.VisualStudio.Product.Community",
"productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
"state": 6466455516217343,
"isComplete": true,
"isLaunchable": true,
"isPrerelease": false,
"isRebootRequired": false,
"displayName": "Visual Studio Community 2019",
"description": "Бесплатная полнофункциональная интегрированная среда разработки для учащихся, разработчиков решений
с открытым кодом и индивидуальных разработчиков",
"channelId": "VisualStudio.16.Release",
"channelUri": "https://aka.ms/vs/16/release/channel",
"enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Mi
crosoft.VisualStudio.Setup.Service",
"releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.2.5",
"thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
"updateDate": "2019-09-11T08:23:59.3155742Z",
"catalog": {
"buildBranch": "d16.2",
"buildVersion": "16.2.29306.81",
"id": "VisualStudio/16.2.5+29306.81",
"localBuild": "build-lab",
"manifestName": "VisualStudio",
"manifestType": "installer",
"productDisplayVersion": "16.2.5",
"productLine": "Dev16",
"productLineVersion": "2019",
"productMilestone": "RTW",
"productMilestoneIsPreRelease": "False",
"productName": "Visual Studio",
"productPatchVersion": "5",
"productPreReleaseMilestoneSuffix": "1.0",
"productSemanticVersion": "16.2.5+29306.81",
"requiredEngineVersion": "2.2.3074.64249"
},
"properties": {
"campaignId": "1491687598.1568189926",
"channelManifestId": "VisualStudio.16.Release/16.2.5+29306.81",
"defaultProgram": "VisualStudio.ebc81321",
"nickname": "",
"setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
}
}
]

 vswhere.exe -format json -utf8 -latest -prerelease -all -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763
[]

**Comment by stuartmorgan** [comment]
According to that output, you don't have an in-progress install, but you also don't have those three components; if `vswhere` isn't giving us correct information, the `doctor` output is going to reflect that.

Please [file a `vswhere` bug](https://github.com/microsoft/vswhere/issues) and link it here, since based on your installer screenshot I don't see any reason for the second output to be empty. Hopefully the `vswhere` developers can help debug that.

**Comment by heaths** [comment]
Based on installed packages (using the `VSSetup` PowerShell cmdlets I also wrote), @marinat is missing "MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.23)". Install that and you should be fine.

**Comment by stuartmorgan** [comment]
Ah, I see; there was apparently a minor tools update so now we're listing the wrong version in the string for new installs. The current version listed [here](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019) is now
```
MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.22)
```
and not
```
MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.21)
```

And based on the comment above, now it'll soon be v14.23. It seems like we need to make that string say something more generic, but I'm not sure how to phrase that in a way that's not going to be confusing.

Thanks @heaths for the debugging, and sorry for sending that non-bug your way. We'll be sure to keep the component-listing instructions you posted in that bug in mind for future reports.

**Comment by stuartmorgan** [comment]
@heaths I don't suppose there's a way to express "Any version of that v142 toolchain" as a `vswhere` query?

**Comment by heaths** [comment]
The existing component ID should do that, but I believe it corresponds to the latest that VS ships. You'd have to ask the Visual C++ team that owns their package authoring.

**Comment by stuartmorgan** [comment]
> I believe it corresponds to the latest that VS ships.

Right, I was specifically hoping for a way to say "any, not necessarily the latest". E.g., something like `Microsoft.VisualStudio.Component.VC.*.x86.x64` (which I can see doesn't work, but I'm wondering if there's a way to express that conceptual query to `vswhere`).

**Comment by stuartmorgan** [comment]
@franciscojma86 For now, let's change the text from:
```
MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.21)
```
to
```
MSVC v142 - VS 2019 C++ x64/x86 build tools
- If there are multiple versions, install the latest one.
```

**Comment by marinat** [comment]
All works! Many thanks for all! :)

**Comment by stuartmorgan** [comment]
Re-opening, as this is tracking fixing the incorrect message.
