### ISSUE TITLE
DropdownButtonFormField acting strange since flutter 1.9

### ISSUE THREAD

**Issue by MasterSirae** [flutter/flutter#40333]
Hi all, I have a question about flutter lifecycle.

Something strange is happening since I updated from flutter 1.7 to 1.9 yesterday. My forms that were working perfectly started to act weird.

I have a stateful widget, which if given no object instantiates a new one in its constructor, so that the user can add a new object or use this widget to edit an existing object. something like this:

```
    final MyObject object;
    MyForm() : this.object = MyObject(name: "", origin: Origin.EARTH);
    MyForm.edit(this.object);
```

Name is a simple string and origin is an enum.

In the form state I have a global key: `final _formKey = GlobalKey<FormState>();`

Later in the code I have a field name, and a dropdown with the different values of the origin.

   ```
 TextFormField(
        initialValue: widget.object.name,
        onSaved: (value) {widget.object.name = value;),
    ),

    DropdownButtonFormField(
        decoration: InputDecoration(labelText: "Origin"),
        items: _originList,
    	value: widget._object.origin,
    	onChanged: (value) {
    	    setState(() {
    		    widget._object.origin = value;
            });
        },
    	onSaved: (value) {
    	    widget._object.type = value;
        },
    ),

```
So for instance when I change my dropdown value, to something like mars, it indeed selects mars in my object and it shows mars on the dropdown. (confirmed by debugger) 

Then when I click on the name textfield to change the name of the object, the dropdown goes back to earth. 

Now the really strange thing is, if I save my object... it saves it correctly ! (with mars and the name I chose) 

I found out that for some reason (that I do not understand) the constructor of the form (not the form state, but the form) is called when I click on other fields of the form, which recalls my constructor MyForm() which sets up a new MyObject with the value earth... 

But then why does it saves it correctly boggles my mind... If it would be consistent with this behavior it should save the object with earth selected and not mars...

Any idea on how this is happening ? (also I make it very clear nothing wrong was happening before the update to flutter 1.9 so it may be a bug in that new version...)

Also I am testing this with an iPhone simulator if that is of any help.

Thank you for any feedback !

**Comment by TahaTesser** [comment]
Hi @MasterSirae 
Are you still experiencing this issue with latest stable?
If yes, can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem  Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
