### ISSUE TITLE
CupertinoNavigationBar not changing status bar items color on iOS 13 on real devices

### ISSUE THREAD

**Issue by vanelizarov** [flutter/flutter#40349]
Let's say, we have a simple application, which consists of two screens. Each screen is `CupertinoPageScaffold` which contains `CupertinoNavigationBar`. On the first screen nav bar is red, so the status bar items are light and on the second screen the nav bar is white, so the status bar items are dark. 

The problem is, that on simulator everything looks fine when I switch from one screen to another: `CupertinoNavigationBar` changes `SystemUiOverlayStyle` automagically based on nav bar color's luminance. It can be seen in [flutter/lib/src/cupertino/nav_bar.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/nav_bar.dart#L94-L102):
```dart
final bool darkBackground = backgroundColor.computeLuminance() < 0.179;
final SystemUiOverlayStyle overlayStyle = darkBackground
    ? SystemUiOverlayStyle.light
    : SystemUiOverlayStyle.dark;
result = AnnotatedRegion<SystemUiOverlayStyle>(
  value: overlayStyle,
  sized: true,
  child: result,
);
```

But when I run this app on real device, status bar color doesn't change. 

I've tested two cases of screen switching:
1. `CupertinoTabScaffold`. The first two screenshots are from simulator, other two are from real device (iPhone 7, iOS 13.1 dev beta 2, but the same behavior was on iOS 13.0 betas too)

<img width="250" alt="tab1_sim" src="https://user-images.githubusercontent.com/5096148/64785364-dfd96600-d574-11e9-95d0-81305f03e3bd.png">

<img width="250" alt="tab2_sim" src="https://user-images.githubusercontent.com/5096148/64785363-df40cf80-d574-11e9-8c28-820517cd77b4.png">

<img width="250" alt="tab1_real" src="https://user-images.githubusercontent.com/5096148/64785409-f67fbd00-d574-11e9-9ce6-7803da8c4d99.PNG">

<img width="250" alt="tab2_real" src="https://user-images.githubusercontent.com/5096148/64785408-f67fbd00-d574-11e9-820d-77e935338aca.jpg">

2. `Navigator.of(context).push()`
<img width="250" alt="navigator1_sim" src="https://user-images.githubusercontent.com/5096148/64785666-89205c00-d575-11e9-8fff-ff898fdaf696.png">

<img width="250" alt="navigator2_sim" src="https://user-images.githubusercontent.com/5096148/64785665-89205c00-d575-11e9-82c8-6ad9104180a1.png">

<img width="250" alt="navigator1_real" src="https://user-images.githubusercontent.com/5096148/64785668-89b8f280-d575-11e9-83a9-f73c786d4c27.PNG">

<img width="250" alt="navigator2_real" src="https://user-images.githubusercontent.com/5096148/64785667-89b8f280-d575-11e9-8beb-1b7b39979304.PNG">

Hers's the minimal runnable example:

```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      debugShowCheckedModeBanner: false,
      home: CupertinoTabScaffold(
        tabBuilder: (context, idx) {
          if (idx == 0) {
            return Screen1();
          } else {
            return Screen2();
          }
        },
        tabBar: CupertinoTabBar(
          activeColor: const Color(0xffe30613),
          inactiveColor: const Color(0xffb3b3b3),
          iconSize: 24.0,
          items: [
            BottomNavigationBarItem(
              icon: Icon(CupertinoIcons.bus),
              title: Text('Bus'),
            ),
            BottomNavigationBarItem(
              icon: Icon(CupertinoIcons.car),
              title: Text('Car'),
            )
          ],
        ),
      ),
      // home: Screen1(),
    );
  }
}

class Screen1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        backgroundColor: const Color(0xffe30613),
      ),
      // child: Center(
      //   child: CupertinoButton.filled(
      //     child: Text('Next'),
      //     onPressed: () {
      //       Navigator.of(context).push(CupertinoPageRoute(
      //         builder: (context) => Screen2(),
      //       ));
      //     },
      //   ),
      // ),
      child: Container(),
    );
  }
}

class Screen2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(),
      child: Container(),
    );
  }
}

```

And `flutter doctor -v` output:

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.15 19A558d, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/vanelizarov/flutter
    • Framework revision 2d2a1ffec9 (5 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/vanelizarov/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.0, Build version 11M382q
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • iPhone 8           • 2F87C04E-9C8E-410E-AC47-4F08D2CC6C5E     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!
```

**Comment by spkersten** [comment]
We have this issue when using just `AnnotatedRegion<SystemUiOverlayStyle>`, so it doesn't seem to be `CupertinoPageScaffold` specific.

**Comment by maxlapides** [comment]
This issue seems related: https://github.com/flutter/flutter/issues/41067

**Comment by vanelizarov** [comment]
Turning off Dark Mode is temp solution

**Comment by LongCatIsLooong** [comment]
#41067 is closed, closing this one as well. Please let me know if this issue should remain open.
