### ISSUE TITLE
Does any widget can drag the ScrollBar?

### ISSUE THREAD

**Issue by Liuzhiyang94** [flutter/flutter#40346]
I have a feature that can drag the scrollbar to scroll the listview. But I just found the `Scollbar` which can not been dragged. 
So i go to the pub.dev , and find the `DraggableScrollbar` .But if i set `initialScrollOffset` of `ScrollController` ,the `DraggableScrollbar` not work fine. 
How to handle this?
Thanks.

**Comment by Liuzhiyang94** [comment]
> See also #31753

Yes. I just did like this. But is there any some `offical` widget implement this..  :)

**Comment by Liuzhiyang94** [comment]
> We just implemented a draggable scrollbar for iOS 13, would that work? #35829

It's still on the master now . Will it be merged in `Stable` channel?

**Comment by justinmc** [comment]
It looks like that is in v1.8.4 and above, so whenever stable reaches that version you'll have it.

If you do end up creating your own draggable scrollbar instead, that code could be useful at least.

**Comment by justinmc** [comment]
There is no current plan to officially support a draggable scrollbar beyond the iOS 13 widget, so I'm going to close this issue.  Let me know if there's anything else though.
