### ISSUE TITLE
When press back button , how to let the flutter app run in background rather than exit?

### ISSUE THREAD

**Issue by mrd2242** [flutter/flutter#40344]
I want to know when press back button,  how to let the flutter app run in background rather than exit . I found a function `Systemnavigator.pop()`, and it's document [https://api.flutter.dev/flutter/services/SystemNavigator/pop.html](url)

>  Instructs the system navigator to remove this activity from the stack and return to the previous activity.
> 
> On iOS, calls to this method are ignored because Apple's human interface guidelines state that applications should not exit themselves.
> 
> This method should be preferred over calling dart:io's exit method, as the latter may cause the underlying platform to act as if the application had crashed.

But it doesn't work. My app still exits.
And I found some solutions need platform specific code. Is there a solution using pure dart code? Thanks !!!

**Comment by hanxu317317** [comment]
Building  a music app, it seems very important to play music in the background

**Comment by bmwmy** [comment]
https://pub.dev/packages/minimize_app

**Comment by darshankawar** [comment]
@mrd2242 
Is this still a valid issue using latest Flutter version or your question has been resolved / answered ?
