### ISSUE TITLE
How do I save and restore the scroll position of a ListView between app restarts?

### ISSUE THREAD

**Issue by jamrelian** [flutter/flutter#40340]
I'm writing an open source Flutter app, and I'd like to persist the scroll position of a ListView so it is restored between app restarts.

So I guess it should be saved on disk using something like shared_preferences (in NSUserDefaults on iOS and SharedPreferences on Android)

Is there a built-in (or plugin) way to do that?

If I have to do it manually, when should I save the scroll position? In a native Android app I would do it in the onPause Activity life-cycle method.

**Comment by sarimk80** [comment]
In Android you do it on onPause but on flutter with the help of _controller.addListener()  it will always update the scroll position.
```

ScrollController _controller;

 _ScrollPosition() async {
    final prefs = await SharedPreferences.getInstance();
    prefs.setDouble("position", _controller.position.pixels);
  }

 @override
  void initState() {
    super.initState();
    _controller = ScrollController(initialScrollOffset: widget.position ?? 0.0);
    _controller.addListener(_ScrollPosition);
   
  }

ListView.builder(
                  controller: _controller,
                  itemCount: 1,
                  shrinkWrap: true,
                  physics: ClampingScrollPhysics(),
                  itemBuilder: (BuildContext context, index) {
                    return ListView(
                        shrinkWrap: true,
                        physics: ClampingScrollPhysics(),
                        children: snapshot.data.map(_builtlist).toList());
                  });
```
where widget.positon is the integer which we are retrieving with the help of sharedPeference in different widget

**Comment by anaurelian** [comment]
> In Android you do it on onPause but on flutter with the help of _controller.addListener() it will always update the scroll position.

The scroll position may change very rapidly, I don't think it's wise to write to SharedPreferences repeatedly (especially as it involves writing to disk).

**Comment by shinlh** [comment]
> You need two things to achieve your desire result:
> 
> 1. SharedPrefrences (https://pub.dev/packages/shared_preferences)
> 2. Scroll Controller (_controller.position.pixels) will give you the current scroll position of the list view

Does this work if the ListView is always receiving new items? I'm using a ListView.separated as a news/posts feed.

**Comment by hatemragab** [comment]
easy way 

```
ListView.builder(
                key: PageStorageKey<String>('controllerA'),
                controller: statelessControllerA,
                itemCount: 2000,
                itemBuilder: (context, i) {
                  print("Rebuilded 1");
                  return ListTile(
                      title: Text(
                    i.toString(),
                    textScaleFactor: 1.5,
                    style: TextStyle(color: Colors.blue),
                  ));
                }),
```

**Comment by cool-id** [comment]
> easy way
> 
> ```
> ListView.builder(
>                 key: PageStorageKey<String>('controllerA'),
>                 controller: statelessControllerA,
>                 itemCount: 2000,
>                 itemBuilder: (context, i) {
>                   print("Rebuilded 1");
>                   return ListTile(
>                       title: Text(
>                     i.toString(),
>                     textScaleFactor: 1.5,
>                     style: TextStyle(color: Colors.blue),
>                   ));
>                 }),
> ```

This isn't working for SingleChildScrollView. I read somewhere that we have to use bucket and PageStorage but unsure of the usage.

**Comment by cool-id** [comment]
> In Android you do it on onPause but on flutter with the help of _controller.addListener() it will always update the scroll position.
> 
> ```
> 
> ScrollController _controller;
> 
>  _ScrollPosition() async {
>     final prefs = await SharedPreferences.getInstance();
>     prefs.setDouble("position", _controller.position.pixels);
>   }
> 
>  @override
>   void initState() {
>     super.initState();
>     _controller = ScrollController(initialScrollOffset: widget.position ?? 0.0);
>     _controller.addListener(_ScrollPosition);
>    
>   }
> 
> ListView.builder(
>                   controller: _controller,
>                   itemCount: 1,
>                   shrinkWrap: true,
>                   physics: ClampingScrollPhysics(),
>                   itemBuilder: (BuildContext context, index) {
>                     return ListView(
>                         shrinkWrap: true,
>                         physics: ClampingScrollPhysics(),
>                         children: snapshot.data.map(_builtlist).toList());
>                   });
> ```
> 
> where widget.positon is the integer which we are retrieving with the help of sharedPeference in different widget

I was looking for much more automated way of persisting scroll position. Specifically when the document says:

```
Each time a scroll completes, save the current scroll offset with PageStorage and restore it if this controller's scrollable is recreated.
If this property is set to false, the scroll offset is never saved and initialScrollOffset is always used to initialize the scroll offset. If true (the default), the initial scroll offset is used the first time the controller's scrollable is created, since there's no scroll offset to restore yet. Subsequently the saved offset is restored and initialScrollOffset is ignored.
```

**Comment by sameerkhan24** [comment]
> 

widget.position is not working. Did u define position somewhere?

**Comment by Blacktaler** [comment]
> > easy way
> > ```
> > ListView.builder(
> >                 key: PageStorageKey<String>('controllerA'),
> >                 controller: statelessControllerA,
> >                 itemCount: 2000,
> >                 itemBuilder: (context, i) {
> >                   print("Rebuilded 1");
> >                   return ListTile(
> >                       title: Text(
> >                     i.toString(),
> >                     textScaleFactor: 1.5,
> >                     style: TextStyle(color: Colors.blue),
> >                   ));
> >                 }),
> > ```
> 
> This isn't working for SingleChildScrollView. I read somewhere that we have to use bucket and PageStorage but unsure of the usage.

By wrapping ListView.builder to pageStorage you can save the scrollPosition of listview, but only in tabbars, or in bottomNavigationBars. If the app restarts the position of the listview is reset. Here is the example:
https://blacktaler.medium.com/using-pagestorage-and-keeping-offset-of-scrollable-widgets-in-flutter-55183a66380

**Comment by goderbauer** [comment]
You can now do this by using state restoration. https://master-api.flutter.dev/flutter/services/RestorationManager-class.html gives an overview of how state restoration works in Flutter.
