### ISSUE TITLE
Scrollable position of a TextSpan within a RichText

### ISSUE THREAD

**Issue by lpongetti** [flutter/flutter#40348]
Hi, i have many TextSpan in my RichText.
I would like to scroll in a specific TextSpan, but for to know the position i must have the context.
TextSpan is not a widget.
So how can i get the TextSpan's position?

I can't use WidgetSpan because my Spans are pieces of the same sentence.

Thanks

**Comment by janmoppel** [comment]
Hello @lpongetti !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
