### ISSUE TITLE
Google Maps: No lines on Polygon

### ISSUE THREAD

**Issue by darren-f5s** [flutter/flutter#40354]
Using `google_maps_flutter 0.5.20+2`, I have a map widget that allows a user to dynamically add points to a map to form a polygon, with the ability to change the color of the polygon.

Since `google_maps_flutter 0.5.21`, the functionality to add a polygon still works, however the actual lines do not show initially until I change the color of the line.

![image](https://user-images.githubusercontent.com/50330436/64791214-ac4c0b00-d577-11e9-9c07-f3cf9d7e6985.png)

**Comment by darren-f5s** [comment]
@BondarenkoStas Fair! It'll be quite the 'small self-contained' app (Because there's quite a bit that goes into it) - so please give me a while to set that up :)

**Comment by iapicca** [comment]
Hi @darren-f5s 
did you manage to reproduce the issue in a self contained app,
alternatively you can also provides the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
