### ISSUE TITLE
Flutter hot reload not working in Android studio 3.5

### ISSUE THREAD

**Issue by budo385** [flutter/flutter#40352]
I have problems with hot reload. It doesn't work on cmd+s or from toolbar.
Hot restart works fine.

Please, could you give some input how to solve this. What to look or where to look.

Here is the flutter doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-HR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by budo385** [comment]
@devoncarew terribly sorry for the inconvenience but the bug on my side.

**Comment by ZahidRamzan** [comment]
Hi @budo385 ,
I have same kind of problem , hot reload is disabled on my android studio 3.5.
I'm using Android Studio and recently installed Flutter but the hot reload button disabled on Windows 10.

I deleted android studio also Flutter plugin and reinstall them again but still not working

I'm creating a mobile application and running it on android real devices.

Flutter Doctor is also saying no issues. Any expert opinion?

**Comment by budo385** [comment]
@ZahidRamzan check out these:
https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#hot-reload-not-working
#23442
#16881

like in my comment above

**Comment by zidzid1234** [comment]
How to use Flutter Hot Reload in a StatelessWidget inside Android Studio 3.6.2 and Flutter v1.12.13+hotfix.9 on Linux ... inside main.dart file:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // StatelessWidget turns this class into a widget
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Text('Hello'),
    );
  }
}
```

**Comment by sud007** [comment]
Doesn

> How to use Flutter Hot Reload in a StatelessWidget inside Android Studio 3.6.2 and Flutter v1.12.13+hotfix.9 on Linux ... inside main.dart file:
> 
> Make sure in Android Studio > File > settings > Languages & Frameworks > Flutter > check "Perform hot reload on save"!!!
> 
> Use the code below -> change the 'Hello' -> save it -> see the hot reload result
> 
> ```
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   // StatelessWidget turns this class into a widget
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: Text('Hello'),
>     );
>   }
> }
> ```

This issue is still there in **AndroidStudio version 3.6.3**. And I already have Hot Reload Enabled!.

"Performing Hot Restart..." just keeps running and never succeeds!

While VS code is just working like a charm!.

**Comment by brandinchiu** [comment]
Am having the same issue on Windows on Android Studio version 3.6.3.

Oddly, same version on Linux @ Ubuntu 16.04 LTS does not have this issue -- hot reload works without issue.

**Comment by saidulhaqueriaz** [comment]
Sadly I'm having same issue about hot reload on Android Studio version 3.6.3

**Comment by Sakthithebeginner** [comment]
I am too facing the same issue no options for using hot reload in android studio 3.4.1.

**Comment by neobie** [comment]
Same too for me. No problem on VS code. But having problem in Android Studio.

**Comment by zanderso** [comment]
If you are seeing a similar issue, please file a new issue with full reproduction steps. Thanks!
