### ISSUE TITLE
LicensePage widget forces iOS phone language to English

### ISSUE THREAD

**Issue by tchabot22** [flutter/flutter#40353]
Preconditions:
- iOS Simulator is set to a language other than English (in my case Korean)
- Flutter application has localized strings in that language

1. Run Flutter application in iOS Simulator with above preconditions
2. Load Root page of the application, make sure it has localized strings on it to show the language set is being displayed
3. Navigate to License Page widget loaded in its own page, the text of the licenses should be English, the title of the page, if localized, should appear in the phone's set language.
3. Press back to navigate to the root page
4. The root page's localized strings are now in English

Three screenshots are provided to show the 'before' and 'after' of this issue:
<img width="437" alt="Screen Shot 2019-09-12 at 8 37 35 AM" src="https://user-images.githubusercontent.com/34530777/64788742-bb5f9880-d538-11e9-8e0b-502bc33209bb.png">

<img width="424" alt="Screen Shot 2019-09-12 at 8 37 47 AM" src="https://user-images.githubusercontent.com/34530777/64788755-c0244c80-d538-11e9-8ff0-1fc0557205be.png">

<img width="427" alt="Screen Shot 2019-09-12 at 8 37 58 AM" src="https://user-images.githubusercontent.com/34530777/64788765-c4506a00-d538-11e9-906d-55a596c055eb.png">

We believe the issue may line on the highlighted lines of code in packages/flutter/lib/src/material/about.dart
<img width="998" alt="Screen Shot 2019-09-12 at 8 45 50 AM" src="https://user-images.githubusercontent.com/34530777/64789394-e4345d80-d539-11e9-91f2-a2ab42f2d451.png">

Does this setting of the Locale need to be reverted when popping the widget?

## Logs

No useful logging information as this issue doesn't cause an exception, just seems to force the language to English while the application is running.

No issues found with `flutter analyze`

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.13.6 17G6030, locale en-US)
    • Flutter version 1.7.8+hotfix.3 at /Users/xxxxxxx/Projects/Flutter/flutter
    • Framework revision b712a172f9 (9 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxxxxxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/xxxxxxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

• No issues found!
```

**Comment by yasargil** [comment]
I had the same or a similar issue see my comment:
https://github.com/flutter/flutter/issues/28456#issuecomment-498608580

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by goderbauer** [comment]
As far as I can tell the issue here is that we're people giving bad advice on https://flutter.dev/docs/development/accessibility-and-localization/internationalization#defining-a-class-for-the-apps-localized-resources. We tell them to modify the global `Intl.defaultLocale` whenever a new locale is loaded, which affects the entire app since it is a global variable. That's bad when the newly loaded locale is only meant to apply to parts of the app (here: the license screen).

I created a PR to update the advice on the website to no longer do that: https://github.com/flutter/website/pull/3013

People, who already followed that old advice will have to update their apps accordingly.

**Comment by semone** [comment]
I had the same issue with the LicencePage setting the language to English until i updated the code not to modify `Intl.defaultLocale`. I now use the new advice stated in PR flutter/website#3013. Now I have an other issue, my numbers and dates are no longer formatted in the selected locale. When modifying `Intl.defaultLocale` they were all correct without me explicitly having to pass in the locale every time doing a DateFormat. Is there something else that needs to be added for this to work as it did before?

**Comment by goderbauer** [comment]
@semone Can you open a new bug and cc me? Preferable with some example code that shows the problem when I run it on my device.
