### ISSUE TITLE
SystemChrome.setEnabledSystemUIOverlays isn't sticky on android.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#4038]
I am assuming it should but will entertain that my assumption is wrong.

**Comment by apwilson** [comment]
https://github.com/flutter/engine/blob/0e991c74b241a0c7e3744e1991ca3a9da119df6e/sky/services/platform/src/org/domokit/platform/SystemChromeImpl.java#L58  called without top and bottom should probably do what https://github.com/domokit/mojo/blob/df314089817655626186198e87189f788c86ee41/services/android/src/org/chromium/mojo/android/ActivityImpl.java#L264 does when IMMERSIVE is set.

**Comment by apwilson** [comment]
Oh!  I see the issue.  setEnabledSystemUIOverlays is actually doing what 'setDisabledSystemUIOverlays' would do if it existed.  ie. It's doing the inverse of what it's supposed to.

**Comment by apwilson** [comment]
It's also not sticky.  If the use brings up the system overlays they won't go away.  If both overlays are disabled we should probably do what this does - goes into immersive mode:

https://github.com/domokit/mojo/blob/df314089817655626186198e87189f788c86ee41/services/android/src/org/chromium/mojo/android/ActivityImpl.java#L264

**Comment by abarth** [comment]
@tvolkert Fixed the first part of this issue.  The remaining issue is that it's not sticky.

**Comment by eseidelGoogle** [comment]
Oh, I think @jason-simmons may have fixed this yesterday.  We noticed this with the game as well.  Or maybe this was already fixed separately?

**Comment by jason-simmons** [comment]
https://github.com/flutter/engine/pull/2791/ will retain these flags across an activity pause/resume
