### ISSUE TITLE
Move atom-flutter issues to flutter/flutter and close issue tracker on atom-flutter

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4039]
Tracking issue for closing the issue tracker for the atom-flutter repo , in order to file all issues here in the flutter/flutter issue tracker.

**Comment by devoncarew** [comment]
👍 

There are only three issues left - I think they can be closed out (will double check).

**Comment by sethladd** [comment]
OK, issues closed out. The README for the project points to this issue tracker.
