### ISSUE TITLE
Material Toolbar "Flexible space with overlapping content" feature

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#404]
https://www.google.com/design/spec/patterns/scrolling-techniques.html
(edit: now https://material.io/archive/guidelines/patterns/scrolling-techniques.html#scrolling-techniques-behavior)

See in particular the bottom two videos.

**Comment by Hixie** [comment]
We could do this pretty easily now, and it is part of the material spec, but we haven't had any demand for it.

**Comment by reyesal** [comment]
I would like this plz make it

**Comment by Hixie** [comment]
The tricky part is the paint order. Other than that you should be able to do this easily enough by following the way the SliverPersistentHeader is made.

**Comment by cdharris** [comment]
Some direction on implementing this would be great please, It's a really cool visual pattern that I'd love to have in my flutter app.

**Comment by mare011** [comment]
I'd love to have it too, designers in my team love drawing a card overlapping the flexible space, it's like a must in every app :-) Also some ideas of how to do it are welcome. Thanks.

**Comment by zoechi** [comment]
@reyesalex @cdharris @mare011 

Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by Hixie** [comment]
This seems like it should be possible by transitioning where the toolbar is renderered right as you cross scrollOffset = 0, and then having some negative region of scroll represent the overscrolled region, or some such (maybe by having a sliver inside). In general though I think we're going to leave this to be done in a package rather than put it in the main library since we've not had that much demand for it (just a few comments and five thumbs after more than 5 years).
