### ISSUE TITLE
"no runnable apps" for the codelab, step 5

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4040]
![screen shot 2016-05-19 at 10 43 37 am](https://cloud.githubusercontent.com/assets/5479/15403664/fa4a8676-1dae-11e6-8852-485f8e20507c.png)

I wonder if we should add a "refresh" button? I have step_5 open in Atom, and I just ran `pub get`. However, I'm still seeing "No runnable apps", which is weird.

I don't know how to take action here. I can't click the gear button, because the cursor is disabled when I hover over the gear button.

I fell off the flow, not sure how to get back on.

**Comment by sethladd** [comment]
Ah, I had to double click "lib/main.dart". Can we make that a bit more automatic? I'm not sure a new user would know to double click that file to activate/configure the runnable apps drop-down.

**Comment by devoncarew** [comment]
We create flutter apps with the right `.atom/launches/main.yaml` file so that runnable pulldown is populated on start. I think the launch config file just needs to be added to this codelab project (to the git repo).

**Comment by sethladd** [comment]
Could we auto-detect that the user just opened a Flutter app, and create a main.yaml for them?

(Maybe better question: does `flutter create` create the main.yaml launch config for them?)

**Comment by devoncarew** [comment]
Yup, flutter create does create an atom launch config for the app.

**Comment by sethladd** [comment]
Not on radar for now.
