### ISSUE TITLE
When does the Slider widget support deep customization?

### ISSUE THREAD

**Issue by zhanghaigang666** [flutter/flutter#40420]
I have two questions:
1, when the Slider widget can support customizable sliders, I don't need solid color
2, at this stage flutter v1.9.1 material widget does not accept flexible customization, resulting in it is difficult to achieve some beautiful DIY interface

**Comment by HansMuller** [comment]
You can change the slider's appearance with [SliderTheme/SliderThemeData](https://api.flutter.dev/flutter/material/SliderTheme-class.html).

CC @clocksmith

**Comment by clocksmith** [comment]
The 5 shapes can be custom painted: thumb, track, tickMarks, overlay, and value indicators
