### ISSUE TITLE
cliprrect widget doesnt expose bug on real time

### ISSUE THREAD

**Issue by wikiworldlang** [flutter/flutter#40426]
im using vscode. and i dont see any msg in Problems tab in vscode.
i copied and pasted msg in Debug Console tab below.
```
@override
  Widget build(BuildContext context) {
    return ClipRRect(
      child: GridTile(
        child: Image.network(
          imageUrl,

I/flutter (16230): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (16230): The following assertion was thrown building ProductItem(dirty, dependencies:
I/flutter (16230): [_LocalizationsScope-[GlobalKey#5f225], _InheritedTheme]):
I/flutter (16230): 'package:flutter/src/widgets/basic.dart': Failed assertion: line 642 pos 15: 'borderRadius != null
I/flutter (16230): || clipper != null': is not true.
I/flutter (16230):
I/flutter (16230): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (16230): more information in this error message to help you determine and fix the underlying cause.
I/flutter (16230): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (16230):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (16230):
I/flutter (16230): User-created ancestor of the error-causing widget was:
I/flutter (16230):   GridView
```

**Comment by BondarenkoStas** [comment]
@wikiworldlang Please provide your ```flutter doctor -v``` output. Can you provide a small self-contained app that demonstrates the problem?
Also, It may worth to post it to https://github.com/flutter/flutter-intellij/issues/new as well.

**Comment by wikiworldlang** [comment]
> @wikiworldlang Please provide your `flutter doctor -v` output. Can you provide a small self-contained app that demonstrates the problem?
> Also, It may worth to post it to https://github.com/flutter/flutter-intellij/issues/new as well.

other widget  is ok to show error msg for what this one need to have required property (ex: Text widget must need to have String data)

**Comment by BondarenkoStas** [comment]
But can you please provide a code sample that reproduces the issue, so it will be a starting point for investigation?
