### ISSUE TITLE
It should be possible to pin Flutter Projects to a specific Flutter version

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#40428]
## Use case

As its part of the Flutter philosophy to allow breaking changes between version to keep the framework improving you immediately get the problem how to ensure that your app is build with a compatible version.
Adding the whole Flutter repository to each project seems sub-optimal.
  
## Proposal

When defining a specific flutter version in pubspec flutter should automatically checkout/download the correct version and build the app. 
Ideally in a separate folder so that after the build the latest selected version is active again.

**Comment by passsy** [comment]
You can use [flutterw](https://github.com/passsy/flutter_wrapper) to achieve this.

**Comment by escamoteur** [comment]
@passi I know, but if I understand it correctly it adds the whole Flutter framework as gut submodule to your project.
This should be directly in the tooling by setting a Flutter version in the pubspec and the tooling automatically checks out the correct Flutter version.

**Comment by passsy** [comment]
A similar PR #26577 was closed with

> @Hixie https://github.com/flutter/flutter/pull/26577#issuecomment-456220568: I think it would make sense to make this available to people as an independent package that they can use with Flutter, but I think if we want to make this be part of Flutter itself, the way to do it is to have flutter run notice that the pubspec.yaml has a Flutter SDK constraint in its environment section, and then have it automatically check out the most recent appropriate version based on that, then re-run itself.

Pretty much what you're suggesting. I personally don't like having `flutter` installed on my system which then automatically changes its version based on the project I'm running it. I keep a flutter copy per project.

**Comment by jonahwilliams** [comment]
I agree with the above comments - this is unlikely to be a feature we would implement in the tool, or one that we would accept as a contribution.
