### ISSUE TITLE
"No implementation found for method TextInput.setEditableSizeAndTransform on channel flutter/textinput"

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#40427]
Hi,

I just hit this exception when I have `Break on all exceptions`enabled in VS code and I click on a TextFormField on my Emulator.
Is this as designed?

![image](https://user-images.githubusercontent.com/16635729/64861237-bd585300-d62f-11e9-9d83-d8f91bbf439c.png)
```
[√] Flutter (Channel master, v1.10.2-pre.4, on Microsoft Windows [Version 10.0.18362.295], locale de-DE)
    • Flutter version 1.10.2-pre.4 at C:\Entwicklung\flutter
    • Framework revision 5a3a46ada2 (6 days ago), 2019-09-07 18:37:41 -0400
    • Engine revision c9ea4dba8d
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 ec7ec4ecf7)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\escam\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.5
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4892.25

[√] VS Code, 64-bit edition (version 1.38.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)
```

**Comment by samcharles93** [comment]
same issue here.

**Comment by ThinkDigitalSoftware** [comment]
I have the same problem. Tapping a TextField and gaining focus throws this.

Flutter 1.10.1 • channel dev • https://github.com/flutter/flutter.git
Framework • revision ce45c2d3e6 (8 days ago) • 2019-09-06 20:11:41 -0400
Engine • revision b9ce2500d9
Tools • Dart 2.5.0 (build 2.5.0-dev.4.0 be66176534)

**Comment by gabuldev** [comment]
I have the same problem.

**Comment by lrmoorejr** [comment]
Seeing it on the latest dev and master channels.

Flutter 1.10.6-pre.69 • channel master • https://github.com/flutter/flutter.git
Framework • revision 5142238c85 (2 hours ago) • 2019-09-25 11:26:06 -0700
Engine • revision 48ad8a08e4
Tools • Dart 2.6.0 (build 2.6.0-dev.2.0 69b5681546)

**Comment by escamoteur** [comment]
Hi, am I right that you only get that breaking when you have selected 'break on all exceptions'?

**Comment by lrmoorejr** [comment]
That was my approach.


On Sep 25, 2019, at 7:51 PM, escamoteur <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, am I right that you only get that breaking when you have selected 'break on all exceptions'?

**Comment by darren-f5s** [comment]
@escamoteur Yes, when breaking on all exceptions. But turning that off shouldn't be a fix ;)

**Comment by escamoteur** [comment]
I agree this should not be the fix. As it does not really crash the app I think we can live with it till its fixed :-)

**Comment by ThinkDigitalSoftware** [comment]
Just read this in the [docs](https://github.com/flutter/flutter/blob/df4bf453abbd9244eec053bfd7a4117be8e0abfc/packages/flutter/lib/src/services/system_channels.dart#L162-L163).

>  /// Calls to methods that are not implemented on the shell side are ignored
>   /// (so it is safe to call methods when the relevant plugin might be missing).

**Comment by justinmc** [comment]
@yjbanov Is `setEditableSizeAndTransform` something from web?

**Comment by adithyaxx** [comment]
Seems like the web sdk is causing this issue. Disabling web support with `flutter config --no-enable-web` fixed it for me. And that is if you are not developing for web.

**Comment by mtcliatt** [comment]
Disabling web support did not fix the problem for our desktop application.

**Comment by yjbanov** [comment]
@justinmc 

Yes, we use `setEditableSizeAndTransform` on the Web. The C++ engine can ignore it.

**Comment by justinmc** [comment]
Is there anything that Flutter can do here to avoid pausing when "Break on all exceptions" is set, or is this the intended behavior?

**Comment by yjbanov** [comment]
@justinmc 

> Got it. Is there anything that Flutter can do here to avoid pausing when "Break on all exceptions" is set, or is this the intended behavior?

I'm not sure if the question is directed at me, but I'm not sure how to answer that. Why should there be any exceptions at all?

**Comment by justinmc** [comment]
@yjbanov Sorry, just addressing anyone interested in this issue in general.  Sounds like this is something we need to fix and the issue should stay open.

**Comment by sgehrman** [comment]
same issue, please fix.

**Comment by seanfreiburg** [comment]
Seeing this also on Android flutter version v1.12.2

**Comment by chickenblood** [comment]
Just upgraded to Flutter 1.12.13+hotfix.5 after today's Flutter Interact keynote and now I'm seeing this exception being thrown. This really negatively affects the debugging experience.

**Comment by ThinkDigitalSoftware** [comment]
> Just upgraded to Flutter 1.12.13+hotfix.5 after today's Flutter Interact keynote and now I'm seeing this exception being thrown. This really negatively affects the debugging experience.

It's been in master for a while, I do agree with you though

**Comment by chickenblood** [comment]
> > Just upgraded to Flutter 1.12.13+hotfix.5 after today's Flutter Interact keynote and now I'm seeing this exception being thrown. This really negatively affects the debugging experience.
> 
> It's been in master for a while, I do agree with you though

I guess my larger point is today’s publicity will probably result in a lot of new potential users downloading Flutter for the first time. Not a great first impression.

**Comment by ThinkDigitalSoftware** [comment]
I think if they worried about impressions over functionality, they’d be Apple. Lol

**Comment by eseidelGoogle** [comment]
FYI @cbracken @Hixie

**Comment by jonsamwell** [comment]
Please fix this leads to a terrible developer experience

**Comment by dnfield** [comment]
This happens because the Flutter Web introduced a method on the platform channel for text editing that isn't handled by other embeddings.  We should just avoid calling it when not on web.  PR incoming.

**Comment by chickenblood** [comment]
> I think if they worried about impressions over functionality, they’d be Apple. Lol
> […](#)

Being able to debug effectively is important functionality.

**Comment by dnfield** [comment]
You can work around this for now by unchecking the `All exceptions` and `Uncaught exceptions` in the debugger.   You may also be able to use what's suggested in https://github.com/Microsoft/vscode/issues/53795#issuecomment-403424534 to just skip the file this is getting thrown from.

**Comment by bradyt** [comment]
Getting this in terminal.app with `flutter run`. I'm on master `Flutter 1.13.9-pre.59`. Do I file an issue, or is this a duplicate? I'm not sure how the solution above applies to terminal.

**Comment by dnfield** [comment]
@bradyt please file a new bug with a reproduction.  Feel free to tag me.

**Comment by sachinshrestha483** [comment]
getting the same error

**Comment by alex7egli** [comment]
This is still happening in Flutter v1.12.13+hotfix.8. My team looked into the source code and saw that this fix is not in it. This bug is in the December Milestone though, shouldn't it have gone out back in hotfix.7 at the latest? This is preventing us from upgrading from 1.9.1+hotfix.6

**Comment by justinmc** [comment]
I think the earliest version this fix got into was v.1.13.3 if I'm not mistaken.  I'm looking at the [merge commit](https://github.com/flutter/flutter/commit/948e2b010126d9f03b590a636a8af01b797c2b0f) and expanding the tagged versions at the top.

**Comment by alex7egli** [comment]
@justinmc Thanks, I couldn't figure out how to tell what release an issue was planned for and went off the milestone listed in this issue and the flutter milestone wiki page explaining how those were used by the flutter team.

**Comment by buzzicards** [comment]
> I think the earliest version this fix got into was v.1.13.3 if I'm not mistaken. I'm looking at the [merge commit](https://github.com/flutter/flutter/commit/948e2b010126d9f03b590a636a8af01b797c2b0f) and expanding the tagged versions at the top.

So is this resolved?

**Comment by dnfield** [comment]
Yes

**Comment by nicolasvahidzein** [comment]
This is still an issue for me and quite annoying. Anyone know how to get rid of this? I am not able to debug properly.

**Comment by StanfordLin** [comment]
has anyone filed a new report? If so please comment so we can be redirected

**Comment by nicolasvahidzein** [comment]
@StanfordLin i did, i need help getting rid of this error.

**Comment by diver2** [comment]
Yes, this is still a bug.
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/emaciel/flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/emaciel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • SM G920F • 06157df6c54bcd08 • android-arm64 • Android 7.0 (API 24)

**Comment by dnfield** [comment]
This bug exists on stable, but not on beta/dev/master.  We do not plan to hotfix it.
