### ISSUE TITLE
How to configure release mode with Atom plugin?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4042]
When I run my Flutter app via Atom, it's not clear how to run it in our various modes.

![screen shot 2016-05-19 at 10 51 57 am](https://cloud.githubusercontent.com/assets/5479/15403957/2b1eea7a-1db0-11e6-94f2-543042fbbb4a.png)

I click the gear, and I'm shown a YAML file. I don't see a placeholder for `mode` ? Should we add a mode configuration option here, with a comment that contains the various valid options?

Thanks for taking a look!

**Comment by eseidelGoogle** [comment]
We might follow the pattern of other ides and rename "Run" to "Debug" and add a "Profile" command and a "Publish" command.

Debug would do what we do now.
Profile would use the --profile build and presumably also launch observatory.
Publish would do `flutter build apk`, etc and then open the folder in the filesystem viewer.

Thoughts?  @devoncarew

**Comment by sethladd** [comment]
> rename "Run" to "Debug"

Did you mean "Debug" to "Run" ?

**Comment by eseidelGoogle** [comment]
Nope, rename "Run" to "Debug" in the command-R sense:

<img width="564" alt="screen shot 2016-05-19 at 12 32 14 pm" src="https://cloud.githubusercontent.com/assets/11857803/15407012/c594b762-1dbd-11e6-93c9-76c6b242ef63.png">

**Comment by sethladd** [comment]
Oh, yes. That one, too :)
