### ISSUE TITLE
 High load seems to cancel scroll animation

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#40434]
Internal: b/143427030

Mirror issue for https://buganizer.corp.google.com/issues/132975410. Conversation should occur there, please.

**Comment by Hixie** [comment]
(Currently it appears this is an upstream issue; we are leaving this open to remind us to check on the status each week until it is confirmed that this is not a Flutter issue.)

**Comment by liyuqian** [comment]
It's still in the upstream client's backlog to debug the issue as of 09/30/2019.

**Comment by mehmetf** [comment]
Internal bug is closed as fixed.
