### ISSUE TITLE
[Flutter Web] floating sliver app bar  behavior on mouse scrolling

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#40430]
hi, I noticed than scrolling up with the mouse
doesn't make the sliver app bar reappear
[video ](https://photos.app.goo.gl/rnHMwW1TB5Q34PTR6)(notice the mouse's movements)

[code sample](https://dartpad.dev/bcebbc4c42dc05f18b350c8a1f9d161d)

**Comment by janmoppel** [comment]
Hello @iapicca.

Thank you for posting this issue!
Can you please also provide an output of the `flutter doctor -v` command to give an overview of your Flutter and Dart versions?

Thank you.

**Comment by iapicca** [comment]
hi, sorry for the delay, there you go

> [√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.10019], locale en-US)
>     • Flutter version 1.9.1+hotfix.2 at C:\src\flutter
>     • Framework revision 2d2a1ffec9 (8 days ago), 2019-09-06 18:39:49 -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at C:\Users\iapic\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.4)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 38.2.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [√] VS Code, 64-bit edition (version 1.38.1)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 3.4.1
> 
> [!] Connected device
>     ! No devices available

**Comment by sh0umik** [comment]
Does flutter has any Mouse Scroll event ? I can see the MouseRegion but it only limited to `enter`, `exit` and `hover`. Support for scroll event would be great.

**Comment by deckerst** [comment]
@sh0umik you could use the `Listener` widget and filter for `PointerScrollEvent` 
```dart
Listener(
  onPointerSignal: (e) {
    if (e is PointerScrollEvent) {
      ...
    }
  },
  child: ...
)
```

**Comment by yjbanov** [comment]
Does this only happen on the Web or does it also happen on desktop?

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/55362

**Comment by iapicca** [comment]
closing in favor of https://github.com/flutter/flutter/issues/55362 due to the higher priority assigned

**Comment by jascodes** [comment]
This is true for desktop as well for flutter 1.22.5. Any workarounds for the moment?

**Comment by mordivgor** [comment]
@iapicca is this issue somehow resolved? The https://github.com/flutter/flutter/issues/55362 is closed while I am facing the same problem at this moment..

**Comment by iapicca** [comment]
@mordivgor 
should to be fixed in master
https://github.com/flutter/flutter/pull/66039
can you confirm?

**Comment by mordivgor** [comment]
I missed the purpose of this issue ;) I thought it is about different behaviour between dragging and mouse scrolling when it comes to sliverappbar (mouse scrolilng does not trigger "floating" appbar in my case, only drag does). Sorry for inconvenience.
