### ISSUE TITLE
Flutter web compilation error not helpful

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#40436]
On the last master I'm getting this: 

```
Launching lib/main.dart on Chrome in debug mode...
Building application for the web...
Skipping compiling lisa_flutter|lib/main_web_entrypoint.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

path_provider|lib/path_provider.dart
platform|lib/src/interface/local_platform.dart
flutter_svg|lib/src/utilities/http.dart
flutter_svg|lib/src/picture_provider.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings
```

Previously it was working "fine", I mean I was able to compile it in debug mode and work like this. Now it show me this, what should I do with this ? 

I'm not using those dependencies in my project so I guess it's a sub dependency of one of mine. But how can I find where those dependency are used ? Is there any trick ? 

Also is there any workaround such errors ? As I was able to compile previously maybe there a flag I can set to ignore those for now ?

**Comment by pjcau** [comment]
I have the same issue. I wait a answer from Google Guys.

**Comment by Pareshoct7** [comment]
I have exactly the same issue

**Comment by blissfulldev** [comment]
I am also having the same issue.

**Comment by BondarenkoStas** [comment]
It seems to have the same cause as #40341. Please follow updates in #39998. Can you please try if https://github.com/flutter/flutter/issues/40341#issuecomment-531045473 will help?
