### ISSUE TITLE
Unable to connect to Observatory message when running on iOS hardware

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4044]
When I run the codelab on an iPad or iPhone, I see this error message:

![screen shot 2016-05-19 at 11 09 22 am](https://cloud.githubusercontent.com/assets/5479/15404419/3e4e4580-1db2-11e6-8340-0f3671b4dde6.png)

Note: running in Simulator does not produce this error.

**Comment by sethladd** [comment]
@chinmaygarde known issue?

**Comment by chinmaygarde** [comment]
Known issue. Don't know if there is a ticket for this.

**Comment by eseidelGoogle** [comment]
I'm seeing this just now with iOS simulator.  Presumably that's a separate regression?

**Comment by sethladd** [comment]
Haven't heard about this in a long time. Closing optimistically.
