### ISSUE TITLE
initState not called when `Navigator.pop`ing to a `Screen`.

### ISSUE THREAD

**Issue by ScottPierce** [flutter/flutter#40449]
## Use case
If I have `Screen1`, which watches data `A`, it's very natural for me to create a request for `A` in the `initState` method of my screen `Widget`. The problem comes in when I navigate from `Screen1` to `Screen2`, and `Screen2` modifies the data `A`, and then calls `Navigator.pop`. `initState` is never called on `Screen1` again, with the end result is that `Screen1` shows old data.

We have a few methods to work around this. None of which are ideal, being either overkill, or obtrusive / annoying:
1. Watch the `Future` returned from `Navigator.pop`, and refresh the data there.
2. Watch a `bool` or a `null` value in the `build` method, and trigger a data request when certain conditions are met. This would require setting that `bool`, or `null`ing out the data before leaving the screen.
3. Creating global streams of data which `Screen1` can watch via the `StreamBuilder`. This is overkill for simple problems though.

## Proposal
There are several ways this could be fixed. One way that would be convenient is by providing some sort of `resume` equivalent lifecycle method that would be called on create, and also when coming poping the backstack.

Another option is to ofcourse dispose of the old screens, and then re-creating them when navigating back. This is possible as `builders` for the screens are being provided anyways.

**Comment by brianschardt** [comment]
I agree with this. I am running into significant issues with my animation controllers being disposed of on pop, and then initState not being called. Is there a solution? Does the flutter team even recognize this as a problem?

**Comment by humayuntanwar** [comment]
did you guys find any solution ?
I m navigating to another page using the constructor as i m using the general dialog and page builder, not the navigation to push, and when i do pop , i need to update the previous page

**Comment by evandrmb** [comment]
I don't believe this is really an issue. InitState is called only when the widget is inserted into the three when you do Navigator.pop() the first screen is already on the three and it shouldn't call initState again.

Also, there's another workaround: you could extend RouteAware and do your update inside of the didPopNext method. For this to work you will also need to declare a routeObserver in your Material app and inside of the build method of the widget you want to update call this routeObserver and subscribe (Remember to unsubscribe in the dispose method).

**Comment by goderbauer** [comment]
The explanation in the previous comment is correct.
