### ISSUE TITLE
`flutter run` doesn't attach to observatory service on ios13

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#40448]
This is sort of related to [#37699](https://github.com/flutter/flutter/issues/37699). On an iPhone Xr device with ios 13, I am seeing very little device logs, and nothing from a flutter debug app. At first I thought this was a problem with `idevicesyslog`, but then I'm seeing the same thing from the macOS console app.

So I tried debugging flutter apps, running flutter apps, running non-flutter apps, changing system settings, and none of these produced any logs I could see in macOS's console app. The only logs I could get from the device where when I first attached it to my mac host: https://gist.github.com/christopherfujino/6e22a26d15c91fadd9feaf8fde97c5b4.

In an earlier version of ios, these syslogs are very busy.

My WIP PR to get `flutter run` to work using MDNS is [#40447](https://github.com/flutter/flutter/pull/40447).

## Logs

```
[✓] Flutter (Channel master, v1.10.2-pre.78, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.10.2-pre.78 at /Users/fujino/git/flutter
    • Framework revision 066cad21a6 (28 minutes ago), 2019-09-13 11:05:00 -0700
    • Engine revision 7ea9884ab0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/fujino/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Users/fujino/Downloads/./Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A419c
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • Christopher’s iPhone • 00008020-00017DA80CC1002E • ios • iOS 13.1

• No issues found!
```

**Comment by christopherfujino** [comment]
cc @cbracken @chinmaygarde

**Comment by christopherfujino** [comment]
cc @cbracken @chinmaygarde @zanderso 

I created a new issue and closed the other one, because there were actually two issues and I didn't want to confuse things. I fixed the other issue by rolling the newest ios-deploy to master, and am working on putting a band-aid on this one by implementing MDNS for `flutter run`. Both will need to be hotfixed into stable. There should probably be a third (if it's possible?) fix to bring back syslogs.

**Comment by cbracken** [comment]
We've had this issue once before, when Apple moved from ASL to os_log (iOS 9.3 and again in iOS 10 IIRC). We currently log via `syslog` [here](https://github.com/flutter/engine/blob/09ef73ff6eb0d3306571be62c59176008a465de1/fml/logging.cc#L85), but it's possible that something's changed with iOS 13 and we need to migrate to os_log. We'll want to test that patch against all iOS versions we can get our hands on, in particular: iOS 8 (oldest iOS we support), iOS 9 (last supported OS for iPhone 4S), iOS 10 (last supported OS for iPhone 5).

**Comment by christopherfujino** [comment]
@chwo @sfarestam @he2lec @jgrandchavin I just closed this issue with PR #40447, would love if you could test this out on Master and confirm if it's fixed!

**Comment by sfarestam** [comment]
Just tried it on master and it seems to work fine. Thanks!!

**Comment by jgrandchavin** [comment]
Hello ! 

I tried it and it is not working... 

It seems that flutter build et run on my device but the application stay with a white screen on my device (iPhone X, iOS 13.1).

And when I hot reload, I have the message:  Error -32601 received from application: Method not found.

But no error message before.

PS: My version is Flutter 1.10.5-pre.22

**Comment by christopherfujino** [comment]
@jgrandchavin and does the same app run in a simulator/pre-ios 13 device?

can you post here the full output of both `flutter doctor -v` and `flutter run -v`? Thank you!

**Comment by chwo** [comment]
@christopherfujino  I checked your fix on the master channel (v1.10.6-pre.19) with the now public available iOS 13 version and can confirm that it is fixed. Thank you!

Because iOS 13 is now released to the public are there any plans to cherry pick this as a hotfix in the stable channel?

**Comment by jgrandchavin** [comment]
Hello ! 

Everything's working now,  I've just need to add WidgetsFlutterBinding.ensureInitialized(); in my main.dart and everything's ok.

Thanks a lot @christopherfujino !

**Comment by jgrandchavin** [comment]
Last things, I've just seen that print() or printDebug() doesn't work any more in iOS devices, any idea ?

**Comment by RyanRamchandar** [comment]
Tested on my iPhone XS w/ iOS 13.0 and no debug logs are appearing. I get the following message:

```
Launching lib/main.dart on iPhone XS in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project:
Running Xcode build...
Xcode build done.                                           29.6s
Installing and launching...
Checking for advertised Dart observatories...
Checking for available port on com.example.googleMapTest._dartobservatory._tcp.local
Checking for authentication code for com.example.googleMapTest._dartobservatory._tcp.local
Syncing files to device iPhone XS...
Could not update files on device: OS Error: Connection reset by peer, errno = 54
```

Running on latest dev channel
```
[✓] Flutter (Channel dev, v1.10.5, on Mac OS X 10.14.6 18G95, locale en-CA)
    • Flutter version 1.10.5 at /Users/ryan/Documents/flutter
    • Framework revision 3cf88fed6d (5 days ago), 2019-09-18 23:09:41 -0400
    • Engine revision 33ad6757e8
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 cb80ea7ba9)

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.4

[✓] Connected device (1 available)
    • iPhone XS • 00008020-0019544602D8002E • ios • iOS 13.0

```

**Comment by tudor07** [comment]
Thanks for fix, any change you will release a hotfix on `stable` channel with this fix? This issue impacted how I develop with Flutter quite a lot and I am sure I am not the only one.

**Comment by christopherfujino** [comment]
@tudor07 this has been hotfixed to stable.
