### ISSUE TITLE
TextAlign.right in SelectableText widget is broken

### ISSUE THREAD

**Issue by OsamaAbbas** [flutter/flutter#40444]
Consider this widget:

```dart
      Container(
        color: Colors.lightBlue,
        height: 150.0,
        width: 300.0,
        child: Padding(
          padding: const EdgeInsets.all(18.0),
          child: Text(
            "Flutter's SelectableText\nIssue",
            textAlign: TextAlign.right,
            style: TextStyle(color: Colors.white, fontSize: 18.0),
          ),
        ),
      )
```

You will get something like this:

![image](https://user-images.githubusercontent.com/3346502/64883379-2ffe1880-d69a-11e9-8fff-9f1d1af79829.png)

Now, change the `Text` widget to `SelectableText`, and you will get this behavior:

![image](https://user-images.githubusercontent.com/3346502/64883406-4310e880-d69a-11e9-8f24-e040663cb648.png)

Is this a bug in `SelectableText`? If not, why does it have this behavior? How can we make it fill its parent width?

Here is `flutter doctor` output:

```bash
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by OsamaAbbas** [comment]
Flutter Inspector shows that the SelectableText widget expands in fact to fill its parent. However, the text itself does not wrap itself correctly to the right edge.

Even if we register an `onTap` callback and click on the right gap in the above picture, it will execute our callback.

```dart
              onTap: () {
                print('widet was clicked');
              }
```

So this is clearly a bug or an issue in SelectableText widget.

**Comment by OsamaAbbas** [comment]
I figured out how to change this behavior. It's by adding: `textWidthBasis: TextWidthBasis.longestLine` to the `SelectableText` constructor.

I hope someone finds this useful.

**Comment by OsamaAbbas** [comment]
In some cases in non latin text, the previous solution is not enough. I had to change `forceLine` (from the SelectableText source file) to `true`, instead of `false` (the default value).

![image](https://user-images.githubusercontent.com/3346502/64896772-f0482880-d6bb-11e9-853f-5cadb9536802.png)

I think we should expose this as a parameter in `SelectableText` constructor.

**Comment by HansMuller** [comment]
CC @chunhtai

**Comment by chunhtai** [comment]
Finished investigation, the issue is that when forceLine = false, it does not respect the constraint minWidth and always hardcoded it to zero.
I will put up a pr to fix it.
