### ISSUE TITLE
Allow null `String` for `Text` widget

### ISSUE THREAD

**Issue by ScottPierce** [flutter/flutter#40459]
`Text` shouldn't throw an error if I give it a null `String`. It should handle that gracefully and display the same as if I gave it an empty `String`. Otherwise, you create more work for me, processing `null` Strings to empty Strings, and from what I've found so far, Dart is bad at things like that compared to Kotlin.

**Comment by sma** [comment]
You can use `Text(variable ?? "")` which is the same with Swift and Kotlin, I think.  And once Dart NNBD support lands, you will hopefully catch most of not all "optional type" problems at compile time.

**Comment by ScottPierce** [comment]
I didn't know about the `??` operator. Thank you. That's far more convenient than what I've been doing.
