### ISSUE TITLE
Best way to execute code whenever the route changes

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4045]
I am using `package:usage/usage.dart` to send events to google analytics. Is there a way for me to hook into ANY route change to send a "Screen View" to google analytics? Or should I explicitly do this alongside all my calls to Navigator.push, as well as initially when the home route is set up? Note that when sending a screen view you provide a name for the screen. This means the hook would ideally give me a way to access the route name or the class of the widget the route builds.

Off-topic: Would you prefer these questions through a different medium since they aren't necessarily issues?

**Comment by eseidelGoogle** [comment]
This is a fine medium.  Almost all your issues are valid documentation issues if nothing else.  This one is asking for a callback in the routing system, which would be for @Hixie to answer.

**Comment by Hixie** [comment]
There's no good way today. That's a good use case. We should definitely handle it better.

In the meantime you could clone MaterialApp and have it create the Navigator with a NavigatorObserver that then forwards all calls onto the hero navigator observer, and do the watching there. But that's not a good solution long-term.

**Comment by eseidelGoogle** [comment]
@drewwarren: is this blocking you?  @Hixie would you be comfortable with drew shipping using your above workaround of cloning MaterialApp?

**Comment by drewwarren** [comment]
This is not blocking. There are acceptable workarounds. As @Hixie mentioned a more tailored solution would be better long-term.

**Comment by goderbauer** [comment]
I while ago we added RouteObservers [1], which seem to do what is asked here. We are actually using them in the firebase_analytics plugin for the exact same purpose to send an event to firebase when the current pageroute changes, see [2]

With that, I am closing this issue. Please re-open or file a new issue with more details if this is not fixing the problem. 

[1] https://master-docs.flutter.io/flutter/widgets/RouteObserver-class.html
[2] https://github.com/flutter/plugins/blob/master/packages/firebase_analytics/lib/observer.dart#L19

**Comment by fzyzcjy** [comment]
P.S. For those who visit this webpage at 2020, the latest link for `observer.dart` ([2] above) is: https://github.com/FirebaseExtended/flutterfire/blob/80b558bd28aad5e687023d728843fa74cb93cfc9/packages/firebase_analytics/firebase_analytics/lib/observer.dart#L1

**Comment by AAverin** [comment]
Was this issue resolved in general?
Analytics is not the only possible use-case. For example I need to refresh user JWT token every time screen changes to make sure I have fresh state if user made a purchase on the web.
