### ISSUE TITLE
The engine should be tested with 32 bit iOS builds

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#40450]
Right now the only tests we have for this build are the device lab tests, which means regressions to this in Dart and the engine aren't caught until it's time to roll. So far this has caused two separate issues with the current roll. #40114 and flutter/engine#12263.

/cc @dnfield

**Comment by dnfield** [comment]
For posterity - it appears that there are still a substantial number of users out there with older iPads and even iPhone 4/4S  out there that would need this.

Unfortunately, I'm not aware of any good OOB way to test this. Even if we could find a 32 bit emulator for it, that would stop working soon on Catalina. We'd need something like our devicelab setup to test this, with our own stock of 32 bit devices.

**Comment by mehmetf** [comment]
> For posterity - it appears that there are still a substantial number of users out there with older iPads and even iPhone 4/4S out there that would need this.

Do we have data to back this up? I found some websites attempting to quantify the market share of various iPhone models (such as https://david-smith.org/iosversionstats/) but there's no definitive answer. According to that link for instance, less than 0.2% of users use a 32-bit device. Then again, that's users of a popular AudioBook app so I don't think India is their target market.

**Comment by dnfield** [comment]
The david-smith site is the closest I've found to data on that - but .2% is still a large number of customers for some segments.

It would be good to get any internal metrics we have on that (for any apps we have that still run on 32 bit iPads).  We could also try to reach out to some of our other partners.

**Comment by jmagman** [comment]
We're about to remove support for 32-bit iOS, see https://github.com/flutter/flutter/issues/97327. Closing.
