### ISSUE TITLE
flutter test should support --machine and --coverage together

### ISSUE THREAD

**Issue by bitsydarel** [flutter/flutter#40456]
## Use case

As an user i want to be able to generate code coverage result and test result from a single command so that i won't have to re-run my tests twice.

i tried to run the following command:
flutter test --machine --coverage --coverage-path=reports | tojunit > reports/test-results.xml

but got the following error:
The test command doesn't support --machine and coverage together.

**Comment by jmagman** [comment]
Duplicate of https://github.com/flutter/flutter/issues/30108.
