### ISSUE TITLE
Issues in release mode when running Flutter Web

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#40463]
## Steps to Reproduce

running: flutter run -d chrome --release --local-engine=host_debug_unopt --web-port=8080

We saw two issues running in release mode today:
1) The runner doesn't use the given web-port put uses a random port.
2) After making a change, to make it visible, I needed to run flutter clean to remove the cache. Otherwise my change didn't took effect.

Thanks!

**Comment by yjbanov** [comment]
Is it fixed now?

**Comment by jonahwilliams** [comment]
The first issue is fixed, the second issue requires  https://github.com/flutter/flutter/pull/41447 first

**Comment by jonahwilliams** [comment]
Reopen due to rollback
