### ISSUE TITLE
[web]: TextField unable to write text

### ISSUE THREAD

**Issue by mudi256** [flutter/flutter#40476]
Flutter_web,I'm trying to write some text in TextField but unable to write

**Comment by piedcipher** [comment]
I'm facing the same issue.

**Comment by jonahwilliams** [comment]
Please include the output of `flutter doctor -v`.

**Comment by mudi256** [comment]
@jonahwilliams please check the attachment
<img width="592" alt="Screenshot 2019-09-15 at 1 09 45 AM" src="https://user-images.githubusercontent.com/36504724/64913226-ae6bc080-d755-11e9-86cb-c09a9f4b1dde.png">

**Comment by jonahwilliams** [comment]
This issue has already been fixed, but It looks like you're using the forked flutter_web. This library is no longer being updated as we've completed the unfork into upstream flutter.

For more information see https://flutter.dev/web
