### ISSUE TITLE
Rename AnimatedSize to RawAnimatedSize and then create a new AnimatedSize to wrap RawAnimatedSize

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#40475]
## Use case
`AnimatedSize` bucks the naming convention of "all AnimatedFoo widgets were implicitly animated" -- [it takes a `vsync` parameter](https://master-api.flutter.dev/flutter/widgets/AnimatedSize/AnimatedSize.html
).

## Proposal
I discussed this with Ian on Discord. He pointed that this is because AnimatedSize is implemented as a render object widget. We should probably rename it RawAnimatedSize and then create a stateful widget called AnimatedSize that wraps it, and knows how to create its own ticker provider.

**Comment by goderbauer** [comment]
AnimatedSize no longer takes a vsync (the param is deprecated and ignored; will be removed in a future version of flutter).
