### ISSUE TITLE
Need more tests for flutter_gallery

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4047]
The Tabs component demo is broken, but the tests pass. There appear to be no tests for it, not even trivial tests that instantiate the class. Therefore, the breakage in https://github.com/flutter/flutter/issues/4046 went undetected.

**Comment by sethladd** [comment]
I wonder if we can make this more specific, so we know when we can close? Perhaps we can rename this to "Add a test for the Tabs component demo in Gallery". Or, perhaps another way: "Get code coverage up to XX% in the gallery app".

**Comment by HansMuller** [comment]
We have a test that instantiates all of the demos however we're not running it because of an intermittent failure: https://github.com/flutter/flutter/issues/3735

**Comment by sethladd** [comment]
Thanks for the update. I'm going to close this one and we'll track https://github.com/flutter/flutter/issues/3735

Sorry that @jimbeveridge got caught here.
