### ISSUE TITLE
[Web] Specify hostname with flutter run

### ISSUE THREAD

**Issue by qrsd** [flutter/flutter#40473]
Pre-flutter 1.9 we had webdev serve and could specify a hostname to serve. Anything similar with flutter run -d (chrome/web)? I'd like to access what i'm working on with different devices in my LAN. Also does hot reload on save not work with flutter run chrome?

**Comment by jonahwilliams** [comment]
Use `--web-hostname` which works in debug mode. It will work in release and profile after https://github.com/flutter/flutter/pull/40465
