### ISSUE TITLE
No default value for NetworkImage.scale in constructor.

### ISSUE THREAD

**Issue by xclud** [flutter/flutter#40485]
The comments in `NetworkImage` constructor says `scale` must not be null. however there is no default value provided.

Similarly `FileImage`'s `scale` requires a non-null value and the default value is set to 1.0.

Is this a bug or i am missing something?

https://github.com/flutter/flutter/blob/0ab7047b72836630d16eb8cbcc8c79d1b893b2e0/packages/flutter/lib/src/painting/image_provider.dart#L485

https://github.com/flutter/flutter/blob/0ab7047b72836630d16eb8cbcc8c79d1b893b2e0/packages/flutter/lib/src/painting/image_provider.dart#L512

**Comment by jonahwilliams** [comment]
That is a redirecting constructor, the actual constructor implementation is here:

https://github.com/flutter/flutter/blob/0ab7047b72836630d16eb8cbcc8c79d1b893b2e0/packages/flutter/lib/src/painting/_network_image_io.dart#L22

Note the default value and the assert.
