### ISSUE TITLE
[web]: White Screen issue

### ISSUE THREAD

**Issue by manishvill** [flutter/flutter#40488]
I have upgraded my flutter version to Flutter 1.10.3-pre.37. I have configure flutter web in my project. and after running "flutter run -d chrome" command it open chrome browser and stays on "White Screen", my Chrome browser version is "Version 76.0.3809.132 (Official Build) (64-bit)"

**Comment by butterflydesign** [comment]
Pre-existing project?

**Comment by jonahwilliams** [comment]
@manishvill please run in verbose mode `flutter run -d chrome -v` and also check in the console of the browser window for errors/warnings. Without more information we also won't be able to help any further

**Comment by pjcau** [comment]
I have the same situation on some days. I used the verbose mode but I didn't see any error.

**Comment by rydmike** [comment]
Same issue here, getting the error: 

_Skipping compiling win_breakpoint|lib/main_web_entrypoint.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:
win_breakpoint|lib/main.dart_

This was on a very simple new project just to test and experiment with layout breakpoints that basically contained no libs other than:

```dart
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
```

I noticed that of the above 'dart.io' is the culprit, if I eliminate it, it compiles OK for WEB too. In this case I was using dart.io to check platform for desktop, iOS, Android etc. As per this logic recommendation for experimenting with Desktop:

``` dart
void _setTargetPlatformForDesktop() {
  TargetPlatform targetPlatform;
  if (Platform.isMacOS) {
    targetPlatform = TargetPlatform.iOS;
  } else if (Platform.isLinux || Platform.isWindows) {
    targetPlatform = TargetPlatform.android;
  }
  if (targetPlatform != null) {
    debugDefaultTargetPlatformOverride = targetPlatform;
  }
}
```

Not sure if that is still a valid practice for Desktop, but using it effectively blocks WEB from compiling, so that is not so nice.

Is there a plan to add WEB as just another platform supported in dart.io now when the branches have been merged?

Is there a list of what will compile for WEB somewhere? Can you add your own ignores to it?

---

The above issues were on Windows 10, here is a verbose Flutter doctor output:

```
flutter doctor -v
[√] Flutter (Channel master, v1.10.3-pre.67, on Microsoft Windows [Version 10.0.17763.678], locale
    en-US)
    • Flutter version 1.10.3-pre.67 at c:\src\flutter
    • Framework revision df4bf453ab (63 minutes ago), 2019-09-17 16:23:44 +0200
    • Engine revision 63873d9f42
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 7799f424f4)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at \AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.2.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.2.29306.81

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.1
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.8423

[√] VS Code (version 1.38.0)
    • VS Code at \AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (4 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64    • Android 9 (API 28) (emulator)
    • Windows                      • Windows       • windows-x64    • Microsoft Windows [Version
      10.0.17763.678]
    • Chrome                       • chrome        • web-javascript • Google Chrome 76.0.3809.132
    • Server                       • web           • web-javascript • Flutter Tools

• No issues found!
```

**Comment by AppleEducate** [comment]
Here is an example project of how to override the platform for desktop on every platform not web. https://github.com/AppleEducate/moor_shared

**Comment by rydmike** [comment]
Thanks @AppleEducate this works for me, for now at least!

**Comment by janmoppel** [comment]
Hello @manishvill !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
