### ISSUE TITLE
MULTIPLE DEPENDENT DROPDOWN. i pulled States by calling future builder on the initState. when i select each state from the future result populated in the dropdown, i get major call major cities according to the selected state and populate it too. But when i try to reselect a state again, i get errors in the major cities dropdown

### ISSUE THREAD

**Issue by nelkassy** [flutter/flutter#40486]
MULTIPLE DEPENDENT DROPDOWN. i pulled States by calling future builder on the initState. when i select each state from the future result populated in the dropdown, i get major call major cities according to the selected state and populate it too. But when i try to reselect a state again, i get errors in the major cities dropdown

**Comment by BondarenkoStas** [comment]
@nelkassy Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.
Provide you ```flutter doctor -v``` output for us to know what the version of the framework you use.
Also please mention what the error, or paste logs here if possible.

**Comment by janmoppel** [comment]
Hello @nelkassy !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
