### ISSUE TITLE
hot reload disabled in android studio

### ISSUE THREAD

**Issue by ZahidRamzan** [flutter/flutter#40495]

**Comment by ZahidRamzan** [comment]
Hi Everyone,
I'm using Android Studio and recently installed Flutter but the hot reload button disabled on Windows 10.

I deleted android studio also Flutter plugin and reinstall them again but still not working

Flutter Doctor is also saying no issues. Any expert opinion?

Attaching logs for flutter doctor:

C:\src\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.17763.737], locale en-US)
    • Flutter version 1.9.1+hotfix.2 at C:\src\flutter
    • Framework revision 2d2a1ffec9 (8 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\zahid\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • SM G950W • 988b5148384a555542 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by jonahwilliams** [comment]
This is likely to be an issue with the IDE itself and not flutter

**Comment by iapicca** [comment]
Hi @ZahidRamzan   
following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) 
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you for your understanding
