### ISSUE TITLE
RawKeyboard has stuck pressed keys when shift is released — shortcuts fail as a result

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#40496]
Reproduction:
1. Press shift+a
2. Release shift
3. Release a

Now evaluate the state of `RawKeyboard.pressedKeys`: capital A is still reported as being pressed. As such, shortcuts fail to match from this point forward, unless the user happens to go through a similar sequence but releases the a key before shift.

This happens surprisingly often when you're typing quickly.

Related to #38076
@gspencergoog

**Comment by gspencergoog** [comment]
@shyndman What platforms does this happen on? macOS?

**Comment by shyndman** [comment]
Yes, macOS.

**Comment by gspencergoog** [comment]
Actually, I think this isn't quite fixed.  The modifier syncing happens reliably now, but we probably also need to clear keys that are marked as down whenever the main window loses focus.

**Comment by gspencergoog** [comment]
Oooh, actually I think this is a duplicate of https://github.com/flutter/flutter/issues/44135, since it's the "A" that gets stuck.  I'll just close this and keep that one.
