### ISSUE TITLE
Any one using Github Actions for their flutter project?

### ISSUE THREAD

**Issue by kaumudpa** [flutter/flutter#40492]
I am trying to setup Github actions for my flutter project to:
1: Build
2: Codesign
3: Publish my artifacts to App store connect and Play Console.
via Github actions, anyone out there succeeded in doing this? 

If yes, Requesting flutter team to put out a doc to help with this, It would be really helpful.

**Comment by jonahwilliams** [comment]
This seems like a discussion better suited for one of the channels at https://flutter.dev/community and not an issue with flutter itself.
