### ISSUE TITLE
send crash

### ISSUE THREAD

**Issue by maaroufiomar** [flutter/flutter#40493]
Failed to send crash report due to a network error: SocketException: Failed host lookup: 'clients2.google.com' (OS Error: Hôte
inconnu.
, errno = 11001)

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by BondarenkoStas** [comment]
Unfortunately, this report does not have any actionable information - it’s not clear if this is a bug in user code, a bug in the framework, or something else entirely.
Please feel free to re-open if you can add the following information:
The version of Flutter you’re using
The output of flutter doctor -v
The full exception you see
A minimal reproduction that leads to this exception.
