### ISSUE TITLE
Paint() need a copyWith method like ThemeData

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#40497]
When pushing some works on canvas, it soon become very verbose and error prone when you need to declare painters.

You need to restart full setup of a Paint() that share parameters when sometimes you just need to mutate a field.

You end up with a lot of overlapping declarations.

Please consider adding a copyWith method like ThemeData, this will drop my lines count by high ratio.

Thanks !

**Comment by matanlurey** [comment]
Fwiw, this was just added as `Paint.from` (https://github.com/flutter/flutter/issues/142871) and assuming no reverts, will make it into an upcoming master branch.
