### ISSUE TITLE
[web] Firefox can't load fonts from packages

### ISSUE THREAD

**Issue by michaelspiss** [flutter/flutter#40501]
I was trying to reproduce https://github.com/brianegan/font_awesome_flutter/issues/54 when I found that the icons were loading fine in chrome, but not in firefox. I did some digging and found some inconsistencies in the flutter font loading behaviour. Chrome loads the icon fonts, but does not even try to load Roboto - and firefox tries to load Roboto, fails with a 404, and ignores the custom icon fonts. For some reason both are able to load the material icons font file (and display material icons).

The content of FontMainfest.json both browsers received was the same and there were no browser addons blocking anything.

How to reproduce: Create a new flutter project, add `font_awesome_flutter` as dependency and use an icon (e.g. `Icon(FontAwesomeIcons.book)`) anywhere.

![screenshot](https://user-images.githubusercontent.com/17252710/64911944-6aae9200-d728-11e9-9c27-e36764797ef8.png)

**Comment by jonahwilliams** [comment]
Please include the output of `flutter doctor -v`

**Comment by michaelspiss** [comment]
Sorry, I forgot.

```
[√] Flutter (Channel master, v1.10.3-pre.38, on Microsoft Windows [Version 10.0.18362.356], locale de-DE)
    • Flutter version 1.10.3-pre.38 at C:\fast_files\flutter
    • Framework revision cf7e7e4529 (5 hours ago), 2019-09-14 07:56:05 -0700
    • Engine revision 00c8941dae
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 a554c8be6b)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\fast_files\android_sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\fast_files\android_sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[√] Connected device (3 available)
    • BLA L29 • AQH7N18104012166 • android-arm64  • Android 9 (API 28)
    • Chrome  • chrome           • web-javascript • Google Chrome 77.0.3865.75
    • Server  • web              • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment]
I think both of the issues you've described should have been fixed recently, but the flutter version you're on is newer than both of them.

To confirm there are no issues with stale build caching, could you try running `flutter clean` and rebuilding?

**Comment by michaelspiss** [comment]
I saw some issues which fixed similar problems, but not this one specifically. I did a rebuild and everything stays the same, except firefox now also ignores the roboto font (no longer requests it).

**Comment by jonahwilliams** [comment]
Okay, thanks! I'll take a look and see if I can't figure this one out

**Comment by michaelspiss** [comment]
Thanks! Please let me know if you need more information

**Comment by jonahwilliams** [comment]
Looks like an issue loading the ttf, from the console window I see:

```
Error while trying to load font family "packages/font_awesome_flutter/FontAwesomeBrands":
SyntaxError: An invalid or illegal string was specified
```

**Comment by jonahwilliams** [comment]
https://github.com/flutter/engine/blob/e174b4b9b0a2a08e8c5f04a27555303baedb82c3/lib/web_ui/lib/src/engine/text/font_collection.dart#L121

This line needs to be updated for firefox as well

**Comment by timtraversy** [comment]
I'm on the latest master (1.10.6-pre.40) and when I build and deploy my site the fonts are still not rendering.

<img width="502" alt="Capture d’écran 2019-09-24 à 4 56 10 PM" src="https://user-images.githubusercontent.com/21370530/65549781-36875e00-deec-11e9-82a0-22785db1662f.png">

**Comment by timtraversy** [comment]
Same behavior with a freshly created app on Safari.
<img width="501" alt="Capture d’écran 2019-09-24 à 5 07 17 PM" src="https://user-images.githubusercontent.com/21370530/65550571-db566b00-deed-11e9-9819-f007fa0c1135.png">
