### ISSUE TITLE
[Android] Auto hyperlink links in a Text widget

### ISSUE THREAD

**Issue by Kwasow** [flutter/flutter#40505]
## Use case

I'm parsing a JSON file and displaying a string part of it in a Text widget in my flutter app. That text contains links to external websites. As of my knowledge there is no way of formating those links to become hyperlinks. This can only be done with a RichText widget, but it requires the developer to specify the link manualy.

## Proposal

Native android TextView allows to set the `android:autoLink="web"` and then the links are automatically formated and become clickable. An optional parameter should be added to the flutter Text widget that would enable that.

**Comment by KagurazakaHanabi** [comment]
Maybe [highlight.dart](https://github.com/KagurazakaHanabi/daily_pics/blob/master/lib/widget/hightlight.dart) can help you

This is a sample
```dart
Highlight(
  text: data.content,
  style: TextStyle(color: Colors.blue),
  defaultStyle: TextStyle(color: Colors.black),
  patterns: {
    RegExp(
      r"(?:http(s)?:\/\/)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!\$&'\(\)\*\+,;=.]+",
    ): HighlightedText(
      recognizer: (RegExpMatch e, int i) {
        return TapGestureRecognizer()
          ..onTap = () {
            launch(e.input.substring(e.start, e.end));
          };
      },
    ),
  },
);
```

**Comment by Kwasow** [comment]
Seems like a nice workaround, but this feature should be included in the framework itself. Both Android and iOS are capable of doing that automatically (although I don't know if Flutter does that on iOS - it doesn't on Android).

**Comment by fayeed** [comment]
@Kwasow a few months back I faced the same problem and I created this package [flutter_parsed_text](https://github.com/fayeed/flutter_parsed_text), it uses `RichText` and comes with few built-in types like email, phone, and URL and if you need something custom like mentions or hashtags you can use Regex to do that.

**Comment by xster** [comment]
customer: chalk points out this is feasible on Android and iOS from the framework
