### ISSUE TITLE
Help with troubleshooting "gRPC keepAlive support"

### ISSUE THREAD

**Issue by PavelPZ** [flutter/flutter#40502]
I apologize for this issue, but: the Flutter project is moving forward very fast (congratulations on closing the "Unfork Flutter for web" project). Since March, blocking issues for me is implementation of protobuf and gRPC. 

Without perfect gRPC client it is difficult to create robust Flutter mobile applications:

* **protobuf 3 JSON serialization incompatibility** (just now **SOLVED** in https://github.com/dart-lang/protobuf/pull/274, thanks a lot)
* **missing gRPC client KeepAlive support**. Please treat this issue as lobbying to solve the https://github.com/grpc/grpc-dart/issues/157.

**Comment by jonahwilliams** [comment]
These issues are already filled on the grpc repo, which is the appropriate place for them. tracking them here isn't necessary.
