### ISSUE TITLE
Background Service

### ISSUE THREAD

**Issue by hiteshgarg002** [flutter/flutter#40506]
Provide a way to enable background services like android in flutter so that the app can still run while in background.

**Comment by darshankawar** [comment]
@hiteshgarg002 
Have you checked [this](https://flutter.dev/docs/development/packages-and-plugins/background-processes) document and underlying article link to see if it answers your question ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by audkar** [comment]
What is point to re-create exactly same issue? To farm statistics of closed tickets?

_Embedding V2_ system is not complete. It has `ServiceAware` and to`BroadcastMessageAware` components. But these aren't hooked up to system (like `ActivityAware` is)
