### ISSUE TITLE
"INSTALL_FAILED_NO_MATCHING_ABIS" when trying to run codelab on phone

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4050]
You can probably repro this by running the codelab on the emulator, then switching targets to a physical phone, then trying to run again.

Here's what I see in the console:

![screen shot 2016-05-19 at 12 34 12 pm](https://cloud.githubusercontent.com/assets/5479/15407093/24b8dbe2-1dbe-11e6-979b-da1c518de821.png)

A workaround is to delete the `build/` directory.

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
will be fixed by https://github.com/flutter/flutter/pull/4032

**Comment by sethladd** [comment]
Cool, thanks for the quick triage!
