### ISSUE TITLE
type 'FixedScrollMetrics' is not a subtype of type 'PageMetrics' (Listview inside PageView)

### ISSUE THREAD

**Issue by Bestfastfire** [flutter/flutter#40518]
I trying put one ListView inside a PageView but i having this error when I sweep scroll up/down, dont when change horizontal on PageView, only when I scroll ListView, I tried change it to SingleScrollView but it has same error:

```
type 'FixedScrollMetrics' is not a subtype of type 'PageMetrics'

When the exception was thrown, this was the stack: 
#0      PageContainerState._onScroll (package:page_indicator/src/container.dart:114:25)
#1      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:127:27)
#2      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:45:20)
#3      ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:31:18)
#4      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:3509:39)

...
Handler: "onUpdate"
Recognizer: VerticalDragGestureRecognizer#53e29
  start behavior: down
```

Code:

```
PageView(
  controller: _pageController,
  children: <Widget>[
    JFragMed(
      count: 0,
      data: data,
      path: path,
      def: def,
      gen: Generation.one,
      stream: _bloc.outStreamResult,
    ),
    JFragMed(
      count: 1,
      data: data,
      path: path,
      def: def,
      gen: Generation.two,
      stream: _bloc.outStreamResult,
    ),
    JFragMed(
      count: 2,
      data: data,
      path: path,
      def: def,
      gen: Generation.three,
      stream: _bloc.outStreamResult,
    ),
    JFragMed(
      count: 3,
      data: data,
      path: path,
      def: def,
      gen: Generation.four,
      stream: _bloc.outStreamResult,
    ),
  ],
)
```

JFragMed widget:

```
@override
  Widget build(BuildContext context) {
    return ListView(
      children: <Widget>[
        ...
      ],
    );
  }
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.13.6 17G8030, locale pt-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.2.2)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

**Comment by varpa89** [comment]
hi @Bestfastfire! how did you fix it?

**Comment by Juliano-SantAna** [comment]
hi @Bestfastfire! how did you fix it?

**Comment by DaGump** [comment]
@Bestfastfire @varpa89  @Juliano-SantAna 
I am having the same issue ... can anybody please tell me if there is a solution?

**Comment by eug48** [comment]
This is due to a bug in a package, not in flutter itself.

From the stack trace the problem is in this package:page_indicator/src/container.dart:114:25
The code is https://github.com/CaiJingLong/flutter_page_indicator/blob/master/lib/src/container.dart#L114
So it looks like a buggy type cast which fails at runtime

**Comment by Garrison88** [comment]
I was experiencing this error using https://pub.dev/packages?q=flutter+page+indicator package. It has since been fixed
