### ISSUE TITLE
Unable to conditionally pass pointer taps to backward widgets in Flutter

### ISSUE THREAD

**Issue by mayurdhurpate** [flutter/flutter#40516]
## Proposal

I'm trying to implement a [Card Paginator Component][1] (single card) in Flutter. 

Here is an example of a basic demo I've created:
```dart
class CardComponent extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Positioned(
          top: 20.0,
          left: 20.0,
          child: 
          GestureDetector(
          // onTap should run while the text is visible on the screen
          // The text will become invisible when the Listview gest scrolled upwards
          onTap: (){print('text tapped');},
            child:
          Container(
          alignment:Alignment.topCenter,
          color: Colors.blueAccent,
        // This is fixed Text over which the card should scroll
        child: Text('Test Button')))),
        ListView(
          children: [
            //  This margin in first empty container pushes the whole card downward and makes the 'Test Button visible'
            Container(margin: EdgeInsets.only(top: 50.0)),
            // This is where the scrolling card actually starts
            Container(color: Colors.cyan[100], height: 120.0, width: 20.0),
            Container(color: Colors.cyan, height: 120.0, width: 20.0),
            Container(color: Colors.cyan[100], height: 120.0, width: 20.0),
            Container(color: Colors.cyan, height: 120.0, width: 20.0),
            Container(color: Colors.cyan[100], height: 120.0, width: 20.0),
            Container(color: Colors.cyan, height: 120.0, width: 20.0),
          ]
        )
      ],
    );
  }
}

```
Here, the fixed 'Test Button' is visible on the screen because of the empty dummy Container pushing the scrollable `ListView` downwards. Yet, since the `ListView` covers the full screen by default, the `onTap` never runs on tapping the button when it's visible.

[![enter image description here][3]][3]  

If I surround the `ListView`/`SinglleChildScrollView` with `IgnorePointer` class, the whole scrolling behaviour stops and also any taps to the children of the ListView stops working which is not desired.

How to tap on the button (backward widget in Stack) while allowing scrolling/tapping in ListView? Maybe we can conditionally check if the if the click is on the dummy empty container and ignore the pointer on that condition only.  

Or should I approach building [Card Paginator Component][1] is some different way?

  [1]: https://dribbble.com/shots/6160500-Card-Paginator-Component
  [2]: https://i.stack.imgur.com/dBPfc.jpg
  [3]: https://i.stack.imgur.com/A0aAk.png

**Comment by mayurdhurpate** [comment]
@BondarenkoStas I tried getting as much help as possible fro the community, on StackOverflow [with bounty] (https://stackoverflow.com/questions/57929582/how-to-pass-taps-to-widgets-below-the-top-widget?noredirect=1#comment102326421_57929582) but it seems that the solution requires low level modifications using `RenderObjects` (`RenderProxyBox` in this case). The UI seemed to be a bit basic one yet the implementation seem to be very difficult. Am I missing something here? How do I pass hit events conditionally to different children of your Stack?

**Comment by BondarenkoStas** [comment]
Sorry @mayurdhurpate, didn't read it with proper attention. I would gladly answer if I know how to do that. Let's wait for help from member and the community.

**Comment by mayurdhurpate** [comment]
I think there are 2 ways to implement this as answered in the above SO answer. One is using the `findRenderObject` in ListView and conditionally handle the `onTapUp`. Another way in which I implemented it, is using `SliverAppBar`s `flexibleSpace` which hosts the content over which the card will scroll. Seems a bit of a hack, with `ClipRect` to clip the invisible content but gives the desired effect.
