### ISSUE TITLE
[web]: <Firebase Admob Support on the web>

### ISSUE THREAD

**Issue by imtusharrai** [flutter/flutter#40520]
Throwing away cached asset graph because the build phases have     changed. This most commonly would happen as a result of adding a
new dependency or updating your dependencies.
Skipping compiling flutter_app|lib/main_web_entrypoint.dart withddc because some of its
transitive libraries have sdk dependencies that not supported on
this platform:

firebase_admob|lib/firebase_admob.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-
i-resolve-skipped-compiling-warnings

**Comment by yjbanov** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/39998

**Comment by kroikie** [comment]
@imtusharrai

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1167. Any further collaboration will be done there.
