### ISSUE TITLE
Bug: Large pixel image disappears

### ISSUE THREAD

**Issue by jascodes** [flutter/flutter#40528]
Hey guys

I was trying to animate large image via clipping but found strange behaviour. In project attached below, there is cover fitted image with infinite width and small height 50; and image won't render. But if you increase the height the image will start appearing at some point. 

PS: it seems to be with there are large pixel image which very high height to width ratio or very high width to height ratio. At some point it stops rendering.

Lemme know if you need more info 

[bug_large_image.zip](https://github.com/flutter/flutter/files/3613939/bug_large_image.zip) **<<< EXAMPLE FLUTTER PROJECT**

## Logs

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.3-pre.39, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.5)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.0)
[✓] Connected device (4 available)
```

**Comment by jason-simmons** [comment]
This image is very large (3456 × 5184 pixels) and is exceeding the limits of Skia's caches.

If you can not reduce the image size, then try working around this by setting a higher cache limit.

Example:
`SystemChannels.skia.invokeMethod<void>('Skia.setResourceCacheMaxBytes', 256 << 20);`

**Comment by VladyslavBondarenko** [comment]
Hi @jascodes 
given the last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
