### ISSUE TITLE
ISO Week Number

### ISSUE THREAD

**Issue by jacwib** [flutter/flutter#40525]
## Use case

Flutter lacks an easy way to get an ISO Week number.  
Often used in Europe, week numbers are often found on calendars.  
Many languages (like googles own go) have a ISOWeek() feature that returns a int between 1-52, which is the current ISO week based on a date.  
Flutter however, lacks this. Which means I have to figure out annoying math to get a week number, and I could not even find a pub.dev package solving this.

## Proposal

Add a ISOWeek() function in DateTime, returning a int between 1-52 which is the current ISO week number.

**Comment by BondarenkoStas** [comment]
@jacwib I would advise you to post the proposal on https://github.com/dart-lang/sdk/issues/new as well, as DateTime class is laying in dart:core library, which is just used by flutter.

**Comment by jacwib** [comment]
(should i close this?)

**Comment by jonahwilliams** [comment]
Is this information not present in [package:intl/intl.dart](https://github.com/dart-lang/intl) ?

**Comment by zoeyfan** [comment]
I am closing this issue as this information has been moved to Dart. Please reopen if this is incorrect.

**Comment by devj3ns** [comment]
For anyone who finds this thread in the future, I created a lightweight Dart package which provides the class Week. 

It's called [isoweek](https://pub.dev/packages/isoweek) and available on [pub.dev](https://pub.dev/packages/isoweek).
