### ISSUE TITLE
Flutter Desktop for Windows no longer builds with master 1.10.3-pre.39

### ISSUE THREAD

**Issue by rydmike** [flutter/flutter#40532]
The Flutter Build for Windows was working fine until I upgraded to master 1.10.3-pre.39.

Looks like some change in the build scripts/tools might have broken the capability to build using Visual Studio 2019 Community version. At least there is something in the error message indicating that. The error message in question is:

**MSB8020**: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install Visual Studio 2017 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution

The build has worked fine before using Visual Studio 2019, never even had 2017 installed on this PC, not sure why now 2017 version would be needed now or why you would revert to an older version. Maybe the error is something completely different and my interpretation of the message is wrong. In either case the Windows build no longer completes in this release.

----

The complete compile error is as follows:  flutter run -d windows -v

[  +23 ms] executing: [c:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +65 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0ef89bb9696f322f27e03a64143399c84b3fbf9f
[        ] executing: [c:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +102 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] v1.10.2-39-g0ef89bb96
[   +6 ms] executing: [c:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [c:\src\flutter\] git ls-remote --get-url origin
[  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +70 ms] executing: [c:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +114 ms] executing: \AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +20 ms] Exit code 0 from: \AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64 transport_id:1
[  +24 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +51 ms] Found plugin flutter_statusbarcolor at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_statusbarcolor-0.2.1\
[  +11 ms] Found plugin liquid_swipe at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\liquid_swipe-1.1.0\
[   +6 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.3.0\
[  +12 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.1.2\
[  +38 ms] Found plugin flutter_statusbarcolor at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_statusbarcolor-0.2.1\
[   +5 ms] Found plugin liquid_swipe at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\liquid_swipe-1.1.0\
[   +3 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.3.0\
[  +12 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.1.2\
[  +84 ms] Launching lib\main.dart on Windows in debug mode...
[  +25 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -requires
Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763
[  +33 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -requires
Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763
[   +1 ms] [
             {
               "instanceId": "a99864e3",
               "installDate": "2019-07-03T20:08:40Z",
               "installationName": "VisualStudio/16.2.5+29306.81",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.2.29306.81",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "Free, fully-featured IDE for students, open-source and individual developers",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.2.5",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2019-09-11T14:11:07.4375023Z",
               "catalog": {
                 "buildBranch": "d16.2",
                 "buildVersion": "16.2.29306.81",
                 "id": "VisualStudio/16.2.5+29306.81",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.2.5",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "5",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.2.5+29306.81",
                 "requiredEngineVersion": "2.2.3074.64249"
               },
               "properties": {
                 "campaignId": "",
                 "canceled": "0",
                 "channelManifestId": "VisualStudio.16.Release/16.2.5+29306.81",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
               }
             }
           ]
[  +19 ms] Building Windows application...
[ +143 ms] **********************************************************************
[        ] ** Visual Studio 2019 Developer Command Prompt v16.2.5
[        ] ** Copyright (c) 2019 Microsoft Corporation
[        ] **********************************************************************
[+1977 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[  +95 ms] Microsoft (R) Build Engine version 16.2.37902+b5aaefc9f for .NET Framework
[        ] Copyright (C) Microsoft Corporation. All rights reserved.
[        ] Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
[  +39 ms] Build started 15.09.2019 21:48:37.
[ +176 ms] Project "\flutter\talo\windows\Runner.sln" on node 1 (default targets).
[   +1 ms] ValidateSolutionConfiguration:
[        ]   Building solution configuration "Debug|x64".
[ +211 ms] Project "\flutter\talo\windows\Runner.sln" (1) is building
"\flutter\talo\windows\Runner.vcxproj.metaproj" (2) on node 1 (default targets).
[   +1 ms] Project "\flutter\talo\windows\Runner.vcxproj.metaproj" (2) is building
"\flutter\talo\windows\FlutterBuild.vcxproj" (3) on node 1 (default targets).
[   +1 ms] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(379,5): error
MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please
install Visual Studio 2017 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or
right-click the solution, and then selecting "Retarget solution". [\flutter\talo\windows\FlutterBuild.vcxproj]
[   +2 ms] Done Building Project "\flutter\talo\windows\FlutterBuild.vcxproj" (default targets) -- FAILED.
[        ] Done Building Project "\flutter\talo\windows\Runner.vcxproj.metaproj" (default targets) -- FAILED.
[        ] Done Building Project "\flutter\talo\windows\Runner.sln" (default targets) -- FAILED.
[        ] Build FAILED.
[   +5 ms] "\flutter\talo\windows\Runner.sln" (default target) (1) ->
[        ] "\flutter\talo\windows\Runner.vcxproj.metaproj" (default target) (2) ->
[        ] "\flutter\talo\windows\FlutterBuild.vcxproj" (default target) (3) ->
[        ] (PrepareForBuild target) ->
[        ]   **C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(379,5): error
MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please
install Visual Studio 2017 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or
right-click the solution, and then selecting "Retarget solution".** [\flutter\talo\windows\FlutterBuild.vcxproj]
[   +3 ms]     0 Warning(s)
[        ]     1 Error(s)
[        ] Time Elapsed 00:00:00.39
[  +21 ms] Building Windows application... (completed in 2.7s)
[  +22 ms] "flutter run" took 3,227ms.

Build process failed. To view the stack trace, please run `flutter run -d windows -v`.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:94:5)
<asynchronous suspension>
#2      WindowsDevice.startApp (package:flutter_tools/src/windows/windows_device.dart:84:13)
<asynchronous suspension>
#3      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:379:54)
<asynchronous suspension>
#4      HotRunner.run (package:flutter_tools/src/run_hot.dart:258:39)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:483:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:519:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#24     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

-----

**For info here is also a Flutter Doctor run**

**flutter doctor -v**

[√] Flutter (Channel master, v1.10.3-pre.39, on Microsoft Windows [Version 10.0.17763.678], locale en-US)
    • Flutter version 1.10.3-pre.39 at c:\src\flutter
    • Framework revision 0ef89bb969 (20 hours ago), 2019-09-14 15:34:29 -0700
    • Engine revision 00c8941dae
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 a554c8be6b)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at \AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.2.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.2.29306.81

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.1
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.8423

[√] VS Code (version 1.38.0)
    • VS Code at AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (4 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64    • Android 9 (API 28) (emulator)
    • Windows                      • Windows       • windows-x64    • Microsoft Windows [Version 10.0.17763.678]
    • Chrome                       • chrome        • web-javascript • Google Chrome 76.0.3809.132
    • Server                       • web           • web-javascript • Flutter Tools

• No issues found!

**Comment by stuartmorgan** [comment]
This is actually an FDE bug, not a Flutter bug, but since I have a fix ready there's no need to move it.

**Comment by rydmike** [comment]
Wow thanks @stuartmorgan ! 
That was quick and I can confirm that the fix works, Thanks a lot! You guys rock!

And apologies for not posting the issue in the FDE repo. I was going to do so, but when I started to do so there was a messages that all work on it had moved over to the main Flutter repo, so that is why I posted it here.

**Comment by stuartmorgan** [comment]
There's not really any way for someone to know whether a build failure is in the FDE repo or the `flutter` tool; when in doubt I would say start with the FDE issue tracker when builds break, but it's not a big deal either way.
