### ISSUE TITLE
Multiple bundle_id in google-services.json

### ISSUE THREAD

**Issue by egorges** [flutter/flutter#40536]
Hi experts,
Although my App looks to work ok, the generated google-services.json includes 2 entries:
```
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "xxx",
        "android_client_info": {
          "package_name": "br.com.gorges.secondapp"
        }
      },
```
but it also has:
```
    {
      "client_info": {
        "mobilesdk_app_id": "xxx",
        "android_client_info": {
          "package_name": "br.com.gorges.myfirstapp"
        }
      },
```
I downloaded it as described in Firebase Console.

I am wondering why the info from 1st app is there and whether Flutter might use it improperly.

Should I leave this? Or how to fix it?
If this is a Firebase Console bug, Flutter instructions might give directions to clean it.

**Comment by janmoppel** [comment]
Hello @egorges !

Thank you for posting an issue.
Can you please clarify in details, how to reproduce this problem?

However, from the provided information, it seems that this is a normal behaviour for multiple Android apps. Author of this blogpost writes about it: https://medium.com/@MiBLT/multiple-build-types-in-firebase-on-android-6f6715f6dd83

Thank you.

**Comment by egorges** [comment]
Hello @janmoppel 
I created the first project with Firebase Console:
https://console.firebase.google.com/project/my-project/overview
Project Overview
Add app
Select platform, and so on.

Did the same with the 2nd one - which is an unrelated App.

Although I understand I could have several "package_name"s should I have .debug and other .profile version, the case is that the generated google-services.json in the 2nd app is improperly referencing the 1st one.

Thanks in advance.

**Comment by egorges** [comment]
Any hints on this?

**Comment by kroikie** [comment]
@egorges

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/336. Any further collaboration will be done there.
