### ISSUE TITLE
xcode10.3 can't output flutter logs when i add flutter to exist app

### ISSUE THREAD

**Issue by longdw** [flutter/flutter#40538]
## Steps to Reproduce
1. use `print` or `log` in flutter project
2. add flutter to exist iOS app
3. run app, the Xcode can't show flutter logs

But it can show flutter logs when I run pure flutter project.

## Logs

```
 Flutter (Channel master, v1.9.1-pre.58, on Mac OS X 10.14.6 18G95, locale
    zh-Hans-CN)
    • Flutter version 1.9.1-pre.58 at /Users/longdw/flutter
    • Framework revision bc95f0881c (4 weeks ago), 2019-08-16 03:14:36 -0400
    • Engine revision bfa9be9978
    • Dart version 2.5.0 (build 2.5.0-dev.2.1 e35e8833ee)
```

**Comment by janmoppel** [comment]
Hello @longdw !

Thank you for posting an issue.
Can you please clarify, did you use `log` function according to the documentation: https://flutter.dev/docs/testing/code-debugging#logging ?

Thank you.

**Comment by longdw** [comment]
@janmoppel  yes, I use `log` function by `import 'dart:developer' as Log`, and use `print` function. It can output logs when I run the pure flutter module project whether on Android or iOS, but when I add flutter module project to exist app according to this document https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#ios, the `log` and `print` function is useless.

**Comment by jmagman** [comment]
I see [dart:core print()](https://api.dartlang.org/stable/2.5.0/dart-core/print.html) results in Xcode's console in both the module and in the existing app, and it looks like that's using `syslog` under the covers.  

Runner module app:
![Screen Shot 2019-09-18 at 7 03 37 PM](https://user-images.githubusercontent.com/682784/65207629-10bf0c80-da47-11e9-8588-1b381308c16f.png)

Existing app with embedded module:
![Screen Shot 2019-09-18 at 7 03 43 PM](https://user-images.githubusercontent.com/682784/65207631-10bf0c80-da47-11e9-9fec-ff5b48a79021.png)

However, I can't see dart:developer log() results in either place in Xcode. @cbracken do you know what API that uses or who to ask?

**Comment by jmagman** [comment]
Is this on iOS 13?  See https://github.com/flutter/flutter/issues/41133.

**Comment by janmoppel** [comment]
Hello @longdw !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
