### ISSUE TITLE
Target URI doesn't exist.

### ISSUE THREAD

**Issue by bencozy** [flutter/flutter#40543]
This is the error message after adding this package to my project
```
Target of URI doesn't exist: 'package:package_info/package_info.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.dart(uri_does_not_exist). 
```

**Comment by janmoppel** [comment]
Hello @bencozy !

Thank you for posting an issue.
It seems like there was a similar behaviour reported before: #40154 and https://stackoverflow.com/questions/44909653/visual-studio-code-target-of-uri-doesnt-exist-packageflutter-material-dart

Please try to run the `flutter packages get` command and then restart your IDE.

As similar problem was reported before, closing this thread for now. If proposed solutions won't work for you, please feel free to re-open the issue.

Thank you.
