### ISSUE TITLE
How to make flutter load only the specified flavor resource to reduce the size of the generated package.

### ISSUE THREAD

**Issue by Liujingguang** [flutter/flutter#40552]
Let flutter have multi-channel capabilities instead of relying on Android native.

**Comment by Liujingguang** [comment]
I have submitted a pr for this question.
https://github.com/flutter/flutter/pull/40561

**Comment by QDJdeveloper** [comment]
I have submitted a pr for this question

**Comment by ckdgit** [comment]
yes，this is very important，our project needs.

**Comment by dnfield** [comment]
Duplicate of https://github.com/flutter/flutter/issues/21682
