### ISSUE TITLE
 Android SDK file not found:

### ISSUE THREAD

**Issue by uwaiphyoaung** [flutter/flutter#40551]
`D:\IntelliJProject\flutter\assignment>flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows
    [Version 10.0.18362.30], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\MIT-170\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    X Android SDK file not found: C:\Users\MIT-170\AppData\Local\Android\Sdk\platforms\android-29\android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Android Studio (version 3.4)
    X Flutter plugin not installed; this adds Flutter specific
      functionality.
    X Dart plugin not installed; this adds Dart specific
      functionality.
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] VS Code (version 1.38.1)
[√] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by janmoppel** [comment]
Hello @uwaiphyoaung !

Thank you for posting an issue here.
This error means that you didn't install the Android SDK. For that you also have to install the Android Studio. Please follow instructions on how to do that here: https://flutter.dev/docs/get-started/install/windows#android-setup

Closing an issue for now, but feel free to re-open it, if problem reappears.

Thank you.

**Comment by uwaiphyoaung** [comment]
Thanks

**Comment by Bukharee** [comment]
i have downloaded android studio and install it properly, i even unchecked the hide obsolete option to download old sdk but uptill now the same outcome
  X Android SDK file not found: C:\Users\BUKHARI AUWAL
      IDRIS\AppData\Local\Android\sdk\platforms\android-29\android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed instructions.
