### ISSUE TITLE
Material Buttons should have onLongPress (or at least a configurable InkWell)

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#40558]
I'm having a hard time making Material Buttons work with LongPress. If I use `InkWell`, I need to add `clipBehavior: Clip.antiAlias` and put an empty `onPressed: () {}`. Then, `InkWell` is going to be on top of another `InkWell` and if the child view doesn't cover the full area, there are going to be additional issues (like image below). I'm almost using Cards for the task, but then there are other trade-offs. It is simply too much boilerplate and problems for such a simple task.

![image](https://user-images.githubusercontent.com/351125/64935902-beed6b00-d829-11e9-8003-4323cea7da22.png)

In other platforms, like Android, both tap and onLongPress are supported. As Flutter comes to the Web, I believe eventually more developers might face this issue.

My suggestion is either, or both:

1. Allow RawMaterialButton to receive InkWell as a parameter, instead of a hard coded one.
2. Add onLongPress to the hard-coded InkWell in RawMaterialButton.

**Comment by HansMuller** [comment]
Adding an onLongPress callback to RawMaterialButton sounds like a safe change.  Would you be interested in submitting a pull-request?
