### ISSUE TITLE
Enable unit tests on the Mac buildbots

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#4056]
After https://github.com/flutter/flutter/pull/4027 is up and running on Travis, also enable `dev/bots/test.sh` on the Mac [buildbots](https://chromium.googlesource.com/chromium/tools/build.git/+/master/scripts/slave/recipes/flutter/flutter.py#139).

/cc @Hixie

**Comment by Hixie** [comment]
closing as dupe of https://github.com/flutter/flutter/issues/6958
