### ISSUE TITLE
What design pattern Should use. Help

### ISSUE THREAD

**Issue by uwaiphyoaung** [flutter/flutter#40562]
Hello I'm new for Flutter Development. I have to make a project with this. But, I don't know what design pattern should use. 
There are variety of design pattern when i discovered. BLoC, Redux, Provider and so on. What design pattern I should use please suggest me.

**Comment by mannprerak2** [comment]
Hi @uwaiphyoaung this is not a place to ask suggestions.
I will give you some links to read and request you to close this issue. 

- https://medium.com/flutter-community/let-me-help-you-to-understand-and-choose-a-state-management-solution-for-your-app-9ffeac834ee3
- https://www.youtube.com/watch?v=d_m5csmrf7I
- https://www.youtube.com/watch?v=3tm-R7ymwhc&t=17s
