### ISSUE TITLE
AndroidView方式的百度地图加载，首次出现黑屏 (Baidu map loading in AndroidView mode, black screen for the first time)

### ISSUE THREAD

**Issue by junyao-yu** [flutter/flutter#40568]
I met a problem, on Android, flutter when loading baidu map using AndroidView way, first open the page will be blank screen?

**Comment by Falways** [comment]
Have you set a loading animation ?

**Comment by junyao-yu** [comment]
> Have you set a loading animation ?

He is a black screen, restart unless kill process, or after the lock screen come in again

**Comment by BondarenkoStas** [comment]
@junyao-yu Please provide your ```flutter doctor -v``` output, and if possible a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by junyao-yu** [comment]
> @junyao-yu Please provide your `flutter doctor -v` output, and if possible a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

[✓] Flutter (Channel master, v1.10.3-pre.45, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
    • Flutter version 1.10.3-pre.45 at /Users/yujunyao/flutter/flutter
    • Framework revision d11c0e3d7b (20 hours ago), 2019-09-16 01:28:41 -0400
    • Engine revision 47991fe122
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 d0052c1b31)

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/yujunyao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2017.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • vivo Z1 • 9099106 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.

The following is the address of the making my project, please use the master branch, when login password input casually.### https://github.com/wangyin8866/flutter_bd

Use baidu map met two problems, black screen and the black line：
![Uploading WechatIMG33.jpeg…]()

![Uploading WechatIMG34.jpeg…]()

**Comment by junyao-yu** [comment]
> @junyao-yu Please provide your `flutter doctor -v` output, and if possible a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

Use baidu map met two problems, black screen and black line, two problems to upload pictures：

![WechatIMG33](https://user-images.githubusercontent.com/11766056/65005279-e891b980-d931-11e9-8c82-8bc3eac0dd3a.jpeg)
![WechatIMG34](https://user-images.githubusercontent.com/11766056/65005281-e92a5000-d931-11e9-9757-fd1d2427b1a0.jpeg)

**Comment by junyao-yu** [comment]
> @junyao-yu Please provide your `flutter doctor -v` output, and if possible a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

Use baidu map met two problems, black screen and black line, two problems to upload pictures：

![Uploading WechatIMG33.jpeg…]()

**Comment by junyao-yu** [comment]
> @junyao-yu Please provide your `flutter doctor -v` output, and if possible a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

Sorry, I accidentally closed the problem

**Comment by BondarenkoStas** [comment]
Hm, I saw you opened a new issue, so closing this one again. @junyao-yu For future, you always can re-open own issue if you closed it yourself.

**Comment by xiaobeifeng** [comment]
> > @junyao-yu Please provide your `flutter doctor -v` output, and if possible a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.
> 
> Use baidu map met two problems, black screen and black line, two problems to upload pictures：
> 
> ![WechatIMG33](https://user-images.githubusercontent.com/11766056/65005279-e891b980-d931-11e9-8c82-8bc3eac0dd3a.jpeg)
> ![WechatIMG34](https://user-images.githubusercontent.com/11766056/65005281-e92a5000-d931-11e9-9757-fd1d2427b1a0.jpeg)

你好，请问你解决这个问题了吗？
