### ISSUE TITLE
Concurrent builds of same Flutter project for two iOS devices fail

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#40576]
With #40171, it's possible to run two instances of `flutter run` from the same directory at the same time to run on two devices. However if you try this with two iOS Simulators, one of the builds fails with:

> /Developer/Xcode/DerivedData/Runner-cqvvjujagpbkjpcfmgxfzeqtjdep/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.

Handling the error better would be nice, but actually supporting this would be even nicer (even if just waiting for one build to complete then doing the other). It'd be nice to run on an iOS and iPad simulator concurrently while working on different layouts for screen sizes to ensure tweaking one doesn't break the other.

FYI @jonahwilliams

**Comment by DanTup** [comment]
I did some testing by calling `xcodebuild` manually:

> xcrun xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/dantup/Dev/Google/flutter/examples/flutter_gallery/build/ios -sdk iphonesimulator -arch x86_64 FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO

Running this in two terminals at the same time for `flutter_gallery` fails with the same error as above. However, adding `-derivedDataPath /tmp/1` on to the end of one and `-derivedDataPath /tmp/2` on to the end of the other *appears* to resolve the issue (though further on in the build, one of them stalls a little waiting for Flutter to release a startup lock that the other presumably is holding).

@jonahwilliams is this something we could reasonably generate per-device ID (or similar) or allow to be passed on the command line for `flutter run`?

**Comment by jonahwilliams** [comment]
Do we know what derivedData is used for? cc @jmagman

**Comment by jmagman** [comment]
DerivedData is where all the intermediate object files, cached modules, code index, logs, etc. lives.  If we run each build from a different derived data directory everything will be re-cached on every build, which I expect is a pretty grim performance price.

**Comment by DanTup** [comment]
But what about if we use a folder per-device (eg. by using the device ID or similar in the path)? The problem with a single global folder is that it prevents running two `flutter run`'s at the same time (it doesn't lock and wait, one of them just fails). It would be really nice to enable running from an IDE on multiple devices (eg. an iPad and iPhone or macOS and iPhone) and iterate on a layout with hot-reload-on-save.

**Comment by jonahwilliams** [comment]
@DanTup can we get around this at all with --use-application-binary? in theory that should skip xcode builds

**Comment by jmagman** [comment]
@DanTup Once one is built and running, are you able to build and run the second one?  I've seen that warning when building the same project from Xcode and the `xcodebuild` at the same, but it usually goes away when the first build is complete.

**Comment by DanTup** [comment]
@jmagman yep, that's correct - this is specifically about running `flutter run` twice *at the exact same time*. The use case is launching from an IDE where I've selected multiple devices and want to press Run and have it launch on both (without having to do locking on the IDE side - which would either mean understanding which devices can build in parallel or making all builds run sequentially regardless of platform which would be slow).

I think https://github.com/flutter/flutter/pull/45608 is a good compromise. Most builds will still run concurrently, and although the iOS builds are forced sequentially, using the shared derived data directory might make the second build use less resources than if it overlapped.
