### ISSUE TITLE
Flutter tinymix acces

### ISSUE THREAD

**Issue by AlbeRex** [flutter/flutter#40579]
Dear all, 
I would like to access to "tinymix" commands in Flutter application. Basically there are some test functions in the Audio Codec driver I can access with ADB command right now with Terminal/Command line. I want to use the same commands directly in Flutter UI to simplify the debug. Do you know a way/an example/documentation to do this? I found something related to open a channel but not so easy to implement.

Thanks a lot for your help

**Comment by AlbeRex** [comment]
One step more: looking on the web seems that manage a process can help in what I need. In the example found (for Android environment) is to:
- Create a process
   Process p = null;
- Get the runtime in root mode
   p = Runtime.getRuntime().exec("su");
- Create an output stream
   DataOutputStream os = new DataOutputStream(p.getOutputStream());
- loop along the command list I want into the DataOutputStream
   ...
   os.writeBytes(tmpCmd.get(i)+"\n");
   ...
- flush
   os.flush();

This implementation seems working well for my target, now the point is "how to translate" in Flutter.

**Comment by escamoteur** [comment]
I guess you will have to write a plugin for that. Please ask this on Stack-overflow
