### ISSUE TITLE
Multiple GestureDetector onPan event in Stack not working

### ISSUE THREAD

**Issue by meeradshenoy** [flutter/flutter#40574]
I have to implement a custom analog clock where the clock hands indicate the breakfast,lunch and dinner time and user is able to reset the time by rotating the hands. I was able to draw the clock and hands with the help of canvas and CustomPaint and i haved stacked up in Stack Widget.I have added GestureDetector for each hand and using onPan events am able to rotate the hands also.But the issue is that when multiple hands are put in Stack only the last added clock hand is moving with the gesture others are not detecting the gesture

**Comment by BondarenkoStas** [comment]
@meeradshenoy Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.
And also please provide your ```flutter doctor -v`` output.

**Comment by VladyslavBondarenko** [comment]
Related SO question - https://stackoverflow.com/questions/57955621/multiple-gesturedetector-onpan-event-in-stack-not-working

@meeradshenoy I hope you've solved the problem.
Not sure, with using not infinity width and height for clock hand containers

Closing the issue as not active and without answer
