### ISSUE TITLE
video_player white background, only sounds

### ISSUE THREAD

**Issue by klaszlo8207** [flutter/flutter#40573]
https://github.com/brianegan/chewie/issues/202

I am using with this package: https://pub.dev/packages/overlay_container

I can hear only voices, but not any picture :(

Android 9.0
Huawei Mate 20 Pro

**Comment by BondarenkoStas** [comment]
@klaszlo8207 Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

Also please provide your ```flutter doctor -v``` output. Do you encounter it only on Android? Do you encounter it only on a physical device?

**Comment by janmoppel** [comment]
Hello @klaszlo8207 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
