### ISSUE TITLE
image_picker plugin can't take camera images.

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#40578]
I have image_picker plugin version(^0.6.1+4). the plugin successfully takes the image from the gallery and take camera images in most of the device and give file object but there is a problem with camera in one plus 6 devices.i can see the file has been created in my app folder but with 0 bytes.

**Comment by BondarenkoStas** [comment]
@deep-stl Please provide your ```flutter doctor -v``` output. 
Also please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by deep-stl** [comment]
@BondarenkoStas okay will provide you the details.

**Comment by deep-stl** [comment]
Hello @BondarenkoStas 
below is the code snippet i am using 
 ```
openCamera() async {
    ImagePicker.pickImage(source: ImageSource.camera)
        .then((file) => cropImage(file))
        .then((image) => _listener.userImage(image))
        .catchError((error) => print(error));
  }
```
it is working absolutely fine except on oneplus devices.

**Comment by rickchen1004** [comment]
I got the same problem on 
Device : Nokia 3.1 plus (TA-1104)
Android Version : Android 9
Android security patch level : September 5, 2019
Kernel Version : 4.9.117+

**Comment by deep-stl** [comment]
Hi @rickchen1004 did you find any solution?

**Comment by deep-stl** [comment]
@BondarenkoStas any updates on this?

**Comment by darshankawar** [comment]
@ghost
Are you still experiencing this issue using [latest](https://pub.dev/packages/image_picker/install) plugin version and on latest stable ?
Can you try the official plugin [example](https://pub.dev/packages/image_picker/example) on the same device to see if issue persists or not ? Also, what OS does your phone have (One plus 6) ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
