### ISSUE TITLE
Firebase codelab shouldn't include a google_services.json file

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#4058]
We are getting rate limited with the default google_services.json file. Instead, I think we should probably make people make their own. But first we need to make the Firebase wrapper show an intelligent error message (possibly with a dialog) when the google_services.json file is missing.

@sethladd

**Comment by qchong** [comment]
@collinjackson Should we try reaching out to the Firebase team to see if they can increase the quota for the codelab project (as a temporary workaround until the Firebase wrapper fix is ready)?

**Comment by Hixie** [comment]
Closing bugs relating to our old codelab. We will have a new codelab at some point.

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1029. Any further collaboration will be done there.
