### ISSUE TITLE
 How to leave socket connection open after application closes?

### ISSUE THREAD

**Issue by arthurlaranjo** [flutter/flutter#40592]
I have an application where a socket issues an alert when security parameters are exceeded, but when closing the application that connection is terminated and the socket stops issuing the alert. It is of paramount importance to leave this connection open so that the socket will continue to issue alerts even when the application is closed, so that the client has control over these parameters. I would like to know if there is any plugin or some way to leave this connection open even with closed application, either leaving a thread running or something.

**Comment by escamoteur** [comment]
Please ask on Stackoverflow
