### ISSUE TITLE
Allow Flutter embedder to filter trace events

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#40593]
Mirror issue for https://buganizer.corp.google.com/issues/151346868 ( Conversation should occur there.)

(gaaclarke edit: previously tracked http://b.corp.google.com/issues/138311646)

**Comment by kf6gpe** [comment]
cc @cbracken Chris, this isn't a blocker, but is high-visibility for `customer: dream (g3)` and may be easy to do. We should at least look and see if we have clarifying questions while the engine team's queue drains.

**Comment by goderbauer** [comment]
@gaaclarke Can you assign a conservative milestone to this one please?

**Comment by gaaclarke** [comment]
@goderbauer It seems a bit "horse before the cart".  There hasn't been a technical design that has been proposed and accepted.  It's a high-level request that may be rejected once we look at the tradeoffs.

**Comment by gaaclarke** [comment]
We have a solution in place once https://github.com/flutter/engine/pull/17108 is rolled.

**Comment by kf6gpe** [comment]
Closed upstream.
