### ISSUE TITLE
Flutter drive coverage report

### ISSUE THREAD

**Issue by bismarabia** [flutter/flutter#40604]
How to generate the coverage report from Flutter Driver test? that is, after running 

`flutter drive --target=test_driver/file.dart`

I checked `flutter driver --help` and it doesn't say anything regarding coverage report.

**Comment by janmoppel** [comment]
Hello @bismarabia !

Thank you for posting an issue.
Similar discussion has already started here and Flutter team is aware of this need: #7474. You can follow the development progress of this feature there. 

As there is another thread discussing the same problem, closing this issue for now. 

Thank you.

**Comment by Bucerella** [comment]
Hey hello @janmoppel !

Any news regarding this issue? Will flutter driver test support coverage report any time soon?

**Comment by Bucerella** [comment]
Hey, hello, hi @janmoppel !

Any news regarding this issue? Will flutter driver test support coverage report any time soon? **X 2**

**Comment by Bucerella** [comment]
Hello, hello, hello, @janmoppel, it's me again. 😄
Let's make an improvement on this, please. I need. Thank you.
