### ISSUE TITLE
[web]: Dark Mode for Web

### ISSUE THREAD

**Issue by jamesblasco** [flutter/flutter#40605]
## Use case

Light mode             |  Dark mode
:-------------------------:|:-------------------------:
<img width="300" alt="Captura de pantalla 2019-09-16 a las 19 33 38" src="https://user-images.githubusercontent.com/19904063/64979907-04a54480-d8b9-11e9-8ee2-f2321996bdd1.png">  | <img width="300" alt="Captura de pantalla 2019-09-16 a las 19 32 59" src="https://user-images.githubusercontent.com/19904063/64979909-053ddb00-d8b9-11e9-871b-7989de166c60.png">

Hi! I don't know if you are considering to add support to dark mode on web but I think it would be an awesome feature.

Apparently there is a media query **'prefers-color-scheme'** that indicates the user theme preference: 
 https://chromestatus.com/feature/5109758977638400.

## Testing

Here I made a demo working with javascript that updates when you change the device theme.

https://www.w3schools.com/code/tryit.asp?filename=G82VZTDRDDND (Tested on MacOS with Chrome 76)

Light mode             |  Dark mode
:-------------------------:|:-------------------------:
<img width="300" alt="Captura de pantalla 2019-09-16 a las 19 47 17" src="https://user-images.githubusercontent.com/19904063/64980921-361f0f80-d8bb-11e9-9f3b-bf9fcf7d0224.png">  |  <img width="300" alt="Captura de pantalla 2019-09-16 a las 19 47 28" src="https://user-images.githubusercontent.com/19904063/64980919-361f0f80-d8bb-11e9-9c6d-a27214d7e705.png"> 

I don't know how hard it's to implement it with the flutter engine. 
I will try to make a plugin ~in the following days~ as soon as plugins are available for web 🙃

**Comment by jamesblasco** [comment]
I updated the description with more details

**Comment by jonahwilliams** [comment]
Since the brightness property is on the dart:ui window, this would need to be done in the engine and not in a plugin

**Comment by jamesblasco** [comment]
> Since the brightness property is on the dart:ui window, this would need to be done in the engine and not in a plugin

Oh true, I just saw it, it is named _platformBrightness.

If web dark mode is not a feature planned short-term, I think I could try a workaround using 'prefers-color-scheme'  and adapting the themes within a plugin. 

I would like to contribute but I don't how I can, flutter engine looks too complex for me.

**Comment by jonahwilliams** [comment]
if you can write a small Dart program that can pull the platform brightness, even if you don't land it yourself I can take a look and adapt it to the flutter engine

**Comment by jamesblasco** [comment]
I can't believe I succeed doing it. Here it is the dart file.

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

// ignore: uri_does_not_exist
import 'dart:html' as HTML;

// ignore: uri_does_not_exist
import 'dart:js' as JS;

void main() {
  debugDefaultTargetPlatformOverride = TargetPlatform.fuchsia;
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _AppState();
}

class _AppState extends State<MyApp> {
  Brightness brightness = Brightness.light;

  final mq = HTML.window.matchMedia('(prefers-color-scheme: dark)');

  @override
  void initState() {
    super.initState();
    onBrightnessChange(mq);
    mq.addListener(onBrightnessChange);
  }

  ThemeData get theme => ThemeData(
        brightness: brightness,
      );

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: theme,
        home: Scaffold(
          body: Center(
            child: Text('Hello Flutter Community!'),
          ),
        ));
  }

  @override
  void dispose() {
    mq.removeListener(onBrightnessChange);
    super.dispose();
  }

  onBrightnessChange(mq) {
    if (mq.matches) {
      setState(() {
        brightness = Brightness.dark;
      });
      print('window is dark');
    } else {
      setState(() {
        brightness = Brightness.light;
      });
      print('window is light');
    }
  }
}
```

**Comment by jamesblasco** [comment]
I could try to add it on the engine but don't know where to start

**Comment by jonahwilliams** [comment]
cc @yjbanov @mdebbar maybe you could give @jamesblasco some help here?

**Comment by yjbanov** [comment]
Great research, @jamesblasco! It shouldn't be hard to implement in the engine. All you need to do is implement [Window.platformBrightness](https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/ui/window.dart#L639). Need to be careful with cross-browser support though.

**Comment by jamesblasco** [comment]
@yjbanov about cross-browser support. 
The API for finding out whether or not a media query applies to the document is available for all browsers => https://caniuse.com/#search=matchMedia. 

This api is already implemented at dart:html => https://api.dartlang.org/stable/2.5.0/dart-html/Window/matchMedia.html

Right now the 'prefers-color-scheme' media query is available for Chrome, Firefox, Opera, and Safari  for MacOS but not iOS.  => https://caniuse.com/#search=prefers-color-scheme

In the case of 'prefers-color-scheme' not being available it should be set as Brightness.light by default.

**Comment by yjbanov** [comment]
@jamesblasco That sounds like a good approach. Would you be interested in sending a PR to the engine with a fix? As a side benefit it would be valuable for us to know how easy it is to contribute to the engine. If there are any barriers we'd like to remove them.

**Comment by jamesblasco** [comment]
So I have been researching a bit for how should it be done. And my assumptions are:

Create a file similar to [engine/keyboard.dart](https://github.com/flutter/engine/blob/cd920398e40ee6b1427e912423cd00ef095c62a3/lib/web_ui/lib/src/engine/keyboard.dart) for the brightness or all the 'flutter/settings' channel messages

One doubt I have is why 'flutter/settings' channel is not implemented on the web engine while exits for the other platforms. (Ex. [Android](https://github.com/flutter/engine/blob/3bcd6a8f7b360cbdfe527b5e21eaca108c24f31f/shell/platform/android/io/flutter/embedding/engine/systemchannels/SettingsChannel.java)) 

It could be added [here](https://github.com/flutter/engine/blob/d5139465f6be120888d3aa874f89ad3806f24fa3/lib/web_ui/lib/src/engine/window.dart#L132) at the **engine/window.dart**, and from there I am not sure how would be the best approach to access the private property [io.window._platformBrightness](https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/ui/window.dart#L639  ) and change it.

Example of Brightness file 
```dart
part of dart.ui;

/// Provides brightness bindings, such as the `flutter/brightness` channel.
class BrightnessEvent {
  /// Initializes the [BrightnessEvent] singleton.
  ///
  /// Use the [instance] getter to get the singleton after calling this method.
  static void initialize() {
    _instance ??= BrightnessEvent._();
  }


  /// The [BrightnessEvent] singleton.
  static BrightnessEvent get instance => _instance;
  static BrightnessEvent _instance;

  final _mediaQuery = html.window.matchMedia('(prefers-color-scheme: dark)');

  html.EventListener _brightnessListener;

  BrightnessEvent._() {
    _brightnessListener = (html.MediaQueryListEvent event) {
      _handleMediaQueryEvent(event);
    };
    _handleMediaQueryEvent(_mediaQuery);
    _mediaQuery.addListener(_brightnessListener);

  }
  
  /// Uninitializes the [BrightnessEvent] singleton.
  ///
  /// After calling this method this object becomes unusable and [instance]
  /// becomes `null`. Call [initialize] again to initialize a new singleton.
  void dispose() {
    _mediaQuery.removeListener(_brightnessListener);
    _brightnessListener = null;
    _instance = null;
  }

  static const JSONMessageCodec _messageCodec = JSONMessageCodec();

  void _handleMediaQueryEvent(mq) {
    final Map<String, dynamic> eventData = <String, dynamic>{
      'type': event.type,
      'platformBrightness': mq.matches ? ui.Brightness.dark : ui.Brightness.light
    };
    ui.window.onPlatformMessage('flutter/settings',
        _messageCodec.encodeMessage(eventData), _noopCallback);*/
  }
}

void _noopCallback(ByteData data) {}
```

Another question I have is where it would be the appropriate init to initialize call BrightnessEvent.initialize(). I think here next to the [Keyboard.initialize();](https://github.com/flutter/engine/blob/57f4ea4d3712631d39f407b7c0cebbf8c95f22ca/lib/web_ui/lib/src/engine.dart#L175)

**Comment by jamesblasco** [comment]
@yjbanov I have never done a pull request before on GitHub, but I think it can’t be hard.

Related to the engine. I have to follow the  [Setting-up-the-Engine-development-environment document](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment), no? 

For compiling it there is not specific instructions for web at [Compiling-the-engine document](https://github.com/flutter/flutter/wiki/Compiling-the-engine). 
Does it work like the other platforms? Something like: 
```
Compiling for Web (Inspired from Compiling for iOS)
These steps build the engine used by flutter run for Web.

Run the following steps, from the src directory created in the steps above:

- git pull upstream master in src/flutter to update the Flutter Engine repo.

- gclient sync to update dependencies.

- ./flutter/tools/gn --unoptimized to prepare the build files for host-side executables.

-- [No idea what should be done here, maybe a dart2js command?]   ninja -C out/ios_debug_unopt && ninja -C out/host_debug_unopt to build all artifacts (use out/ios_debug_sim_unopt for Simulator).

```

**Comment by mdebbar** [comment]
> Related to the engine. I have to follow the Setting-up-the-Engine-development-environment document, no?

Correct.

> For compiling it there is not specific instructions for web at Compiling-the-engine document.
Does it work like the other platforms?

After you are done setting up your engine development environment, you could try out the new tool we've been working on. The tool is called `felt` and it aims to facilitate the development of the web engine. See more information in this [README file](https://github.com/flutter/engine/blob/master/lib/web_ui/dev/README.md). Please let us know if you encounter any problems.

**Comment by jamesblasco** [comment]
Oh @mdebbar, thanks for the info! I will give it a try tomorrow (It's midnight here in spain). The tool looks very intuitive.

**Comment by jamesblasco** [comment]
@mdebbar or @yjbanov, could any of you give me a feedback of [this approach I wrote in a previous comment](https://github.com/flutter/flutter/issues/40605#issuecomment-532397073)? Thanks ☺️

**Comment by yjbanov** [comment]
@jamesblasco I don't think you need the 'flutter/settings' channel. That channel is only used to communicate between the platform thread (written in Java/ObjC) and the engine thread (written in C++). Platform channels seemed like an easy way to achieve this, since they are language-agnostic and thread-safe.

However, on the Web there is no language barrier, nor are there thread-safety concerns. So I think we should just implement it in plain Dart exactly how you proposed in https://github.com/flutter/flutter/issues/40605#issuecomment-531987246.

**Comment by mdebbar** [comment]
@jamesblasco here a few ideas and thoughts:

1. The framework already uses `window.onPlatformBrightnessChanged` to listen to brightness changes. So there is no need to use the `flutter/settings` platform channel.
2. `engine.window` should override the `platformBrightness` getter and have its own private `_platformBrightness`.
3. The `BrightnessEvent` class should be `part of engine` not `part of ui`. Then it would have access to private properties of `engine.window`.
4. Maybe rename `BrightnessEvent` to `BrightnessWatcher` or `BrightnessListener`?

Hope these ideas help guide you in the right direction.

In any case, please go ahead and open a PR and I look forward to reviewing it :)

**Comment by jamesblasco** [comment]
@mdebbar thanks for the feedback, but following the @yjbanov i did it inside the ui.Window class. 

I opened a PR [(12335)](https://github.com/flutter/engine/pull/12335) some hours ago (my first one ever 🥳). Let me know if you think it would be better to group it separated in a BrightnessListener class.

**Comment by yjbanov** [comment]
Fixed by https://github.com/flutter/engine/pull/12335
