### ISSUE TITLE
Add-to-app "Flutter/Flutter.h file not found error" when adding to a cordova iOS app

### ISSUE THREAD

**Issue by mikhail-karan** [flutter/flutter#40606]
Hi Flutter team
I’ve been having some issues adding a flutter module to my Cordova packaged iOS app

I have been following your GitHub [add-to-app tutorial ](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps)step by step and managed to update the pod file and get the app to build. I had to add a POD_ROOT and PODS_PODFILE_DIR_PATH user variables  but after that it built. Now once I start trying to add flutter to my iOS app in the AppDelegate.h file it is not able to import the Flutter header

`#import <Flutter/Flutter.h>`
Throws a `Flutter/Flutter.h file not found error`

I’m wondering if I’m just missing something simple or is this just a edge case issue since my add is packaged with Cordova

Here is my pod file for reference:

```

flutter_application_path = '/Users/user/Development/workingfolder/flutter_clvm_module/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'qplayer2' do
  install_all_flutter_pods(flutter_application_path)
  project 'qplayer2.xcodeproj'
end
```

Let me know if there’s anything else you need me to post to help with this. I’ve tried recreating the project multiple times and still run into the same error every time.

**Comment by jmagman** [comment]
What's the output of `flutter doctor -v`?

**Comment by jmagman** [comment]
Also, if you can make a sample app that reproduces, that would be extremely helpful!

**Comment by mikhail-karan** [comment]
```
MacBook-Pro-2:qplayer user$ flutter doctor -v
[✓] Flutter (Channel master, v1.10.3-pre.2, on Mac OS X 10.14.6 18G87, locale en-CA)
    • Flutter version 1.10.3-pre.2 at /Users/user/Development/flutter
    • Framework revision ddb06331b2 (4 days ago), 2019-09-12 11:07:41 -0400
    • Engine revision bf91a8d62a
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 e6887536aa)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by jmagman** [comment]
Can we get a sample app that reproduces?

**Comment by mikhail-karan** [comment]
Yup I'll try my best to create one.

**Comment by mikhail-karan** [comment]
Heres a repo that should reproduce the issue:

https://github.com/mikhail-karan/flutter-add-to-app-test

**Comment by mikhail-karan** [comment]
You probably know this but you'll have to change the

`flutter_application_path = '/Users/user/Development/workingfolder/addToAppTest/my_flutter/' `

**Comment by jmagman** [comment]
There's some hint warnints when I `pod install` from your test project:
```
$ cd my_flutter
$ flutter packages get
$ cd ../ios
...
Pod installation complete! There are 3 dependencies from the Podfile and 3 total pods installed.

[!] Automatically assigning platform `ios` with version `10.0` on target `HelloWorld` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] The `HelloWorld [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-HelloWorld/Pods-HelloWorld.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `HelloWorld [Debug]` target overrides the `PODS_PODFILE_DIR_PATH` build setting defined in `Pods/Target Support Files/Pods-HelloWorld/Pods-HelloWorld.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `HelloWorld [Debug]` target overrides the `PODS_ROOT` build setting defined in `Pods/Target Support Files/Pods-HelloWorld/Pods-HelloWorld.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `HelloWorld [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-HelloWorld/Pods-HelloWorld.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `HelloWorld [Release]` target overrides the `PODS_PODFILE_DIR_PATH` build setting defined in `Pods/Target Support Files/Pods-HelloWorld/Pods-HelloWorld.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `HelloWorld [Release]` target overrides the `PODS_ROOT` build setting defined in `Pods/Target Support Files/Pods-HelloWorld/Pods-HelloWorld.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

1. Your Configurations are not based on the generated CocoaPods configuration file, they are based on your custom build-debug.xcconfig.  
2. When I switch the base confis to Pods-HelloWorld.debug I can remove your custom PODS_PODFILE_DIR_PATH and PODS_ROOT because they are defined in the xcconfig.
3. Follow their other instructions for `$(inherited)` suggestions.
4. It builds.

Let CocoaPods set the base xcconfig, and you can use [post_install](https://guides.cocoapods.org/syntax/podfile.html#post_install) to set any missing build settings you want put in the xcconfig (or just set them in the project target build settings in the UI with `$(inherited)`).
We're actively working on ways to add Flutter to existing apps without using CocoaPods.  That work is being tracked with https://github.com/flutter/flutter/issues/36968

**Comment by mikhail-karan** [comment]
Thanks for this! I'm pretty new to the CocoaPods and Obj C world to be honest and don't really know how to do some of the things you mentioned.

1. How do I switch my base configs to Pods-HelloWorld.debug ?
2. How do I apply the `$(inherited)` suggestions, do I just replace whats currently there with `$(inheritied)` or do I add it?

**Comment by jmagman** [comment]
You have build and build-debug configurations set now In 
![build-debug](https://user-images.githubusercontent.com/682784/64990714-2e447880-d885-11e9-8300-951198132ba5.png)
You should be able to go into your project settings > Info > Configurations and make it look like:
![Screen Shot 2019-09-16 at 1 24 12 PM](https://user-images.githubusercontent.com/682784/64990808-63e96180-d885-11e9-9d9b-9647dd56fe63.png)
Unfortunately Flutter currently forces you into using CocoaPods at the moment, but you are really having a CocoaPods setup issue, not a Flutter setup issue.  StackOverflow might be a better place to get answers, or just Google the warnings you get when you `pod install`.
