### ISSUE TITLE
Flutter renders a frame on every mouse move

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#40600]
Repro steps:
Run example from the flutter-desktop-embedding repo in debug mode.
https://github.com/google/flutter-desktop-embedding/tree/master/example

The open the devtools timeline page and verify that frames are drawn every time the mouse is moved. 
Interestingly, the https://giphy.com/apps/giphycapture screen recording tool does further odd things to the flutter desktop app resulting in frames showing up in bunches. Without screen recording, devtools updates one frame at a time and all the frames are shown as rendering quickly but with screen recording some of the frames are very slow.
![desktop_demo](https://user-images.githubusercontent.com/1226812/64977359-13174000-d868-11e9-96c8-4b7a16f7c89e.gif)

**Comment by jacob314** [comment]
Fyi @gspencergoog

**Comment by jason-simmons** [comment]
Also noticed this happening on the Linux desktop embedder.

It looks like the `MouseTracker` will schedule a frame on every change to the pointer's location if any widget is listening for hover events:
    https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/gestures/mouse_tracking.dart#L173

**Comment by gspencergoog** [comment]
OK, I have a fix for this in https://github.com/flutter/flutter/pull/41014.

This was a problem for all platforms, actually, so I updated the title.
