### ISSUE TITLE
flutter logs doesn't show Firebase exceptions

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#4061]
## Steps to Reproduce

Clone https://github.com/flutter/firechat-flutter/tree/master/step_5

Remove android/assets/google-services.json

flutter run (on Android)

The actual error is "Missing google-services.json. Please add it to the assets folder." It shows up in adb logcat but not flutter logs.

**Comment by devoncarew** [comment]
> 05-19 15:28:35.336 31014 31014 E FirebaseImpl: Missing google-services.json. Please add it to the assets folder.

Is our firebase integration responsible for logging to to the adb tag `FirebaseImpl`, or is that logged by the firebase SDK?

**Comment by collinjackson** [comment]
It's our integration: https://github.com/flutter/firebase-dart/blob/master/android/mojo/src/main/java/com/google/firebase/mojo/FirebaseImpl.java#L93

However, I could imagine devs wanting to third-party SDK errors as well, because sometimes they are informative, like this one:

05-19 12:45:42.249  3329  3369 W GooglePlayServicesUtil: Google Play services out of date.  Requires 9060000 but found 8489480

**Comment by collinjackson** [comment]
I could change the tag to include a string we're filtering on. This won't show third-party SDK errors, but maybe they're a lost cause?

**Comment by devoncarew** [comment]
Yeah, it's a tough issue. I think the raw adb stream will be too noisy for users in general - it'll include a lot of issues from other processes running on the phone.

Perhaps we can change the firebase tag to something like `flutter-firebase`, and on the tools side, filter for anything starting with `flutter-`. That'll catch the firebase integration, and be a bit ore general purpose than it is currently.

**Comment by devoncarew** [comment]
From a quick look around, `FlutterFirebase` would match existing adb tags better.
