### ISSUE TITLE
[web] TextFormField resets after controller value changes

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#40612]
Reproduces at https://github.com/kevmoo/vote.dart/tree/master/knarly @ Flutter HEAD

Mobile - works fine
![editing_moble](https://user-images.githubusercontent.com/17034/64983648-d3efeb80-d875-11e9-8e95-c08f2eb5ae91.gif)

Web - notice how the text updates, then when I click back it goes back to the value before update
![editing_web](https://user-images.githubusercontent.com/17034/64983670-e0744400-d875-11e9-8c07-ae3c400acdcc.gif)

**Comment by kevmoo** [comment]
@nturgut – this appears fixed – as of 532a8fed4

I have other issues about the cursor jumping around when I click w/ the mouse, but I'll file a separate issue there.

**Comment by nturgut** [comment]
Thanks Kevin!

This might be fixed even earlier. After https://github.com/flutter/engine/pull/12698 (which solved two more issues about wrong editing state.)

Please cc me to all bugs about text editing.

Cheers,
