### ISSUE TITLE
 The socket breaks data transmission. Urgent need help!! please!!

### ISSUE THREAD

**Issue by Denmal1982** [flutter/flutter#40621]
a problem occurs when you pass a long array of data.

     Socket.connect(host, port).then((_soc){
     socket = _soc;

     socket.add(utf8.encode("..........text the length of the array 3000")); 
      socket.listen((byte){
        print(byte);
      },onDone: (){
        socket.destroy();
      },cancelOnError: false);
    })

on the server side, I get 1448 characters instead of 3000.
If I send a long array of data to another client, the server receives it in full!

What could be the reason that I'm doing wrong?

**Comment by janmoppel** [comment]
Hello @Denmal1982 !

Thank you for posting an issue.
Can you please also provide additional information such as an output of the `flutter doctor -v` command?

Thank you.

**Comment by Denmal1982** [comment]
> Hello @Denmal1982 !
> 
> Thank you for posting an issue.
> Can you please also provide additional information such as an output of the `flutter doctor -v` command?
> 
> Thank you.

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 37.1.4
    • Dart plugin version 192.5728.98

[✓] Connected device (2 available)
    • Redmi Note 4 • de78d0c19804                         • android-arm64 • Android 7.0 (API 24)
    • iPhone 5s    • CCE4EC62-9509-448E-989B-391EA5CCA58E • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

**Comment by cbracken** [comment]
@Denmal1982 this sounds like it may be due to buffering. What happens if you add `socket.flush()` after your writes?

**Comment by TahaTesser** [comment]
Hi @Denmal1982 

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
