### ISSUE TITLE
PointerEnterEvent erases value of `event.down`

### ISSUE THREAD

**Issue by kristini-ho** [flutter/flutter#40637]
In `PointerEnterEvent` class documentation:

/// The pointer has moved with respect to the device **while the pointer is not
/// in contact with the device**, and entered a target object.

Implies pointer is always up.

In `MouseRegion` documentation for` PointerEnterEvent onEnter`:

/// Called when a mouse pointer **(with or without buttons pressed)** enters the
  /// region defined by this widget, or when the widget appears under the
  /// pointer.

Implies pointer can be up OR down.

In  `PointerEnterEvent` constructor, the param `down` is not exposed, and instead, in the call to super, `down: false` is always passed. 

I'd suggest that it should expose the parameter so as to take its original value (because right now, in cases such as `.fromMouseEvent (PointerMoveEvent(...))` the value will filp flop), and simply give it a default value of false, and the class doc should change to match that used in MouseRegion (otherwise, `PointerEnterEvent`s have no way of detecting whether or not the mouse/etc is down).

**Comment by Hixie** [comment]
cc @gspencergoog

**Comment by gspencergoog** [comment]
cc @dkwingsmt
