### ISSUE TITLE
Custom ProgressIndicators

### ISSUE THREAD

**Issue by andywolff** [flutter/flutter#40631]
## Use case

I want to create a custom ProgressIndicator which has some slight differences from LinearProgressIndicator. Namely, I want the background and value to be rounded rectangles, and I want a different height.

Currently, in order to do this, I have to fork not only LinearProgressIndicator, but also the _LinearProgressIndicatorPainter, the _LinearProgressIndicatorState, and even the ProgressIndicator parent. The actual change I need is pretty minimal, mostly in the Painter's paint() method, and one line of the State's _buildIndicator method.

Looking at the way LinearProgressIndicator and CircularProgressIndicator extend ProgressIndicator, my first thought was that my custom ProgressIndicator should also extend ProgressIndicator. To make this possible, I suggested PR #40625, but the advice I received is that we should favor composition instead of inheritance and discuss further in an issue. I'd like to have that discussion here.

## Proposal

I don't really have detailed ideas on how to make it easier to customize ProgressIndicators. What can we do to make this easier? 
Or, is the current state expected and acceptable? I don't have a sense of the flutter ecosystem yet, so maybe this amount of forking is not really a problem.

As a related point, I feel the ProgressIndicator class should be either:

- A private parent to be extended only by classes in that package (in which case the class itself should be declared as private).
- A public parent intended to be extended by others (in which case the private methods need to be public).

**Comment by HansMuller** [comment]
The progress indicator widget is almost trivial except for the indeterminate animation and (maybe) its semantics nodes. Maybe we should factor out a class that computes the indeterminate  line segments given the value of an animation controller?

**Comment by HansMuller** [comment]
@Piinks - as we work on making simple components adaptive, hopefully we can finally address this issue.

**Comment by Piinks** [comment]
> Namely, I want the background and value to be rounded rectangles, and I want a different height.

I think all of this is now supported, LinearProgressIndicator allows the border radius and line height to be customized now. Is this issue resolved?

**Comment by andywolff** [comment]
The product I needed this for has been shut down. Since you say LinearProgressIndicator allows the border radius and line height to be customized now, I'm happy to mark this as resolved
