### ISSUE TITLE
Improve Android embedding testing infrastructure

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#40632]
Currently, the engine supports JVM testing of the Android embedding via unit tests and robolectric tests, as well as end-to-end tests within a "scenario app". While this infrastructure makes testing possible for some things, it still comes with a significant friction that stalls forward momentum and often requires adjustments to the infrastructure to write new tests.

Existing frictions include:

- [ ] Often need to add new dependencies, either Android libs or robolectric libs. First we have to run into a failure, then debug it, then find the appropriate lib to solve it, then add that lib to the internal distribution system.

- [ ] The scenario app that is intended to run end-to-end tests in the engine does not have any easy support to launch different Android Activitys, which means we can't easily test the majority of the embedding.

- [ ] The scenario app is in a completely different place than the JVM tests, which makes it difficult to discover for devs who need to write tests but are not completely familiar with the project setup. It would be much easier if the JVM and end-to-end tests were located together.

**Comment by mklim** [comment]
/cc @dnfield, who added the scenario app.

> Often need to add new dependencies, either Android libs or robolectric libs. First we have to run into a failure, then debug it, then find the appropriate lib to solve it, then add that lib to the internal distribution system.

This process is painful. The steps are described in detail at ["Updating a CIPD dependency"](https://github.com/flutter/engine/blob/master/shell/platform/android/test/README.md#updating-a-cipd-dependency).

I don't think this step can be automated further. Adding something to CIPD is inherently manual. It may be possible to remove a little bit of friction by automatically including everything in the CIPD directory at compile time so `BUILD.gn` doesn't also need to be edited, but I don't think that's the major source of pain here on it's own.

When I originally added the test infra, I added the bare minimum dependencies that the suite would run with. Part of my reasoning at the time was that doing that meant that we wouldn't be downloading jars for tests that didn't exist yet every CI run. This may not be worth the friction.

One way I can think of to fix this friction would be to step back, figure out all the potential transitive runtime dependencies of the engine, robolectric, mockito, etc, and then include them all. I think this would be extremely difficult to do and verify. The reason why this adds so much friction up front is that these missing classes tend to be deeply transitive ones that are hard to track down, and our build system is unique so adding them can cause unexpected problems.

Another potential mitigation would be to stop the tests from being hermetic and ready to build after `gclient sync`. Robolectric can download its own internal dependencies at runtime. I had disabled this and pointed to a manually managed CIPD bucket instead for consistency with CI and our `gclient sync` process, but using it would remove the need for us to manage Robolectric's deps. It wouldn't save us from transitive deps for mockito or the engine itself though.

#38471 is another engine Java test infra bug.

**Comment by dnfield** [comment]
Adding dependencies should be painful :\

The scenario app can support launching new activities by just writing the right stuff in MainActivity.java, probably driven by intent extras right?  It already does something close to that for the Firebase Testlab test(s), which specify that information and we use it here: https://github.com/flutter/engine/blob/master/testing/scenario_app/android/app/src/main/java/dev/flutter/scenarios/MainActivity.java#L33

**Comment by matthew-carroll** [comment]
@mklim points taken. I don't know what all we might do or could do, so maybe what you've outlined are our only options. This ticket primarily captures the pain of the problem rather than a clear solution.

@dnfield I don't think its a good idea for anything in the world of testing to be painful. Testing should be easier than writing source code, but it's not. It's currently much, much more difficult.

The dependencies that we're talking about are testing dependencies, not source code dependencies. And it's a direct result of Flutter not using the standard Android build system that every other project uses (for the most part). So now we have humans who are looking up transitive dependencies on the web, downloading those dependencies, and adding their jars and licenses to CIPD. We should not ignore the impact this has on developers trying to get things done. It's a complete tangent, involving steps and technologies that the implementing developer might be encountering for the very first time. Even I can't remember how to do this each time, so thankfully as @mklim pointed out, we have a README with the steps. But it's still tedious and it's still a distraction from testing new embedding code.

With regard to the scenario app, I'm mostly suggesting that we have either some Java scaffolding, or we integrate something like espresso, so that when a developer comes in, that developer only has to introduce test code specific to what they're testing, rather than build out additional infrastructure to be able to begin testing the behavior in question. So I agree that we can get from where we are to where we should be, but I do not think that we're at a great place currently. Driving apps via pure instrumentation is quite tedious and often error prone.

So overall, hopefully the message isn't too muddy. I'm not saying that what we have is fundamentally broken or bad. I'm just saying that we should take seriously the goal of making testing a frictionless process because good tests really are important, and the greater the friction, the higher the likelihood that low value tests are written just to comply with project rules. I really want to see accessible, high value tests for the embedding, so I very much want to achieve a low friction testing environment.

**Comment by matthew-carroll** [comment]
BTW I also CC'ed @xster on the email, so I'll add him here, too.

**Comment by dnfield** [comment]
I have some general thoughts I'm going to write up at some point baout moving the bulk of the Android Java embedding dependencies out of the engine tree.  I think it would help with this problem (e.g. we could use Gradle to build them instead of GN/Ninja), and would also help us with some potential versioning issues (e.g. we don't have to marry releases of the Android high level embedding with stable releases of the full Flutter product).  WDYT?

**Comment by dnfield** [comment]
It wouldn't fully solve this problem - we'd still have at least some tests in the engine that are still challenging to maintain (but maybe could be improved with tooling updates?), but it would reduce the friction for embedding tests at least.

**Comment by matthew-carroll** [comment]
I think the possibility of leaning on Gradle sounds very intriguing to me. I'm generally a fan of us utilizing the traditional technologies wherever we can. I agree that if we can setup a somewhat traditional Gradle environment for building the embedding, it would probably automatically resolve a lot of these testing difficulties. I don't know if you've peaked into the transitive dependencies within robolectric, but it's almost intractable from a human standpoint. Gradle should resolve that instantly.

**Comment by dnfield** [comment]
https://docs.google.com/document/d/1nQujwZfEe3QOHTyZn160eImpoJOYioADP09DtumcLcc/edit?ts=5d8041db# - will be at https://flutter.dev/go/android-embedding-move once https://github.com/flutter/website/pull/3006 lands.

**Comment by mklim** [comment]
Relying on Gradle for the unit tests would help with a lot of the pain using Robolectric in general. We've done a lot of hoop jumping to get it to work and run on Ninja at all, and from what I can tell our unique build system may be why we've been blocked on getting it fully working with SDK 29. A lot of the manual transitive dependency finding is stuff that Gradle would normally attempt to do and resolve for us.

Of course, then we will probably be dealing with Gradle build issues instead. :) We may start seeing issues like the tests timeout as Gradle is downloading jars at test time, obscure Gradle mismatch version errors when we try to include something new and run them, etc. It's hard to predict ahead of time.

**Comment by tvolkert** [comment]
How are the "scenario app" end-to-end tests currently run?  Would the budding Espresso-Flutter integration help there?

/cc @adazh and @digiter

**Comment by adazh** [comment]
Thanks @tvolkert for looping me in!

By reading through this thread, I see there are possible improvements in the current testing infra regarding the building system, and testing tools like Robolectric, and Espresso.

Speaking to testing:
1) Unit/integration testing using Robolectric. Since Robolectric fakes/mocks out native dependencies and has unclear/undefined discoverability of these fakes, it makes developers' life even harder to figure out the dependencies. We have an effort to improve testing fidelity especially for native code dependencies, which I think would help but it's still a WIP.

2) End-to-end testing using Espresso. This is going to be the heaviest tests you would have for your embeddings, and you should only write 20% of your tests using Espresso (other 80% should either be unit tests or integration tests for better coverage with less efforts). But from a couple of bugs caught by Espresso, these tests are still valuable in a sense that it can catch user-facing bugs, and also flakiness issues that you sometimes wouldn't be able to with unit testing.
We have some internal tests written for Espresso-Flutter testing framework itself, but they happen to discover a couple of embedding/engine bugs :). Currently I report these bugs when I occasionally scan the test results, but I'll see if I can set up some notification if you guys find the results useful.
Furthermore, @collinjackson plans to work with me on making the Espresso-Flutter library accessible to external in Q4. I believe it's currently a blocker to run Espresso-Flutter tests on Flutter's CI.

**Comment by xster** [comment]
@blasten fixed this in https://github.com/flutter/engine/pull/17116 (thank you!!!)
