### ISSUE TITLE
Can't copy callstack from Atom

### ISSUE THREAD

**Issue by jamesr** [flutter/flutter#4064]
## Steps to Reproduce

Run a Flutter app in Atom with cmd-R, get to an exception.  Try to copy-paste the exception callstack out to (for instance) file a bug.  Nothing happens.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
• Flutter at /Users/jamesr/flutter
• Framework revision a48b063 (4 hours ago), engine revision 8ecb015767

[✓] Android toolchain - develop for Android devices (Android SDK 22.0.1)
• Android SDK at /Users/jamesr/Library/Android/sdk
• Platform android-23, build-tools 22.0.1
• Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
• XCode at /Applications/Xcode.app/Contents/Developer
• Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
• Atom installed; Flutter plugin version 0.2.2

## Logs and Crash Reports

N/A

/cc @devoncarew

**Comment by eseidelGoogle** [comment]
I hit this again today.  I don't know any way to get my stacktrace out of Atom and into a bug. :/

**Comment by tvolkert** [comment]
I was able to copy mine a few days ago.  @devoncarew has this since been fixed?

**Comment by devoncarew** [comment]
I think it repros for some people and not for others. We do have specific code to support copying from the console, but that code hasn't changed in several months. Will re-test locally -

**Comment by sethladd** [comment]
Thanks for the feedback! Going to close in favor of IntelliJ plugin.
