### ISSUE TITLE
Text widget can't warp correctly with some text.

### ISSUE THREAD

**Issue by jihongboo** [flutter/flutter#40645]
The Text widget works fine with normal text, but can't warp correctly with some text. 
## example: 
0.564571260155513397['a', 't', 'd', ' ', '-', '以', 'd', '-', 'i', ' ', '摄', 'd', 'g', 'a', 'd', '载', '拍', 'c', 'f', 'p']
## code
```
Padding(
    padding: const EdgeInsets.all(200.0),
    child: Center(
    child: Text(
     "0.564571260155513397['a', 't', 'd', ' ', '-', '以', 'd', '-', 'i', ' ', '摄', 'd', 'g', 'a', 'd', '载', '拍', 'c', 'f', 'p']",
    ),
),
```
## result
![1741568692702_ pic](https://user-images.githubusercontent.com/15397647/65010864-db7dc600-d943-11e9-9bcf-67afd24ca35e.jpg)
The `a',`  is seems not at the right position.

**Comment by janmoppel** [comment]
Hello @jihongboo !

Thank you for posting an issue.
Can you please attach an output of the `flutter doctor -v` command as well? 

This question also seems to be a good question for the StackOverflow. Flutter has a very active and helpful community there, so feel free to post it there too.

Thank you.

**Comment by jihongboo** [comment]
[!] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.15 19A558d, locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.4 at /Users/jihongbo/Development/Flutter/flutter
    • Framework revision 20e59316b8 (9 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jihongbo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.4

[!] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 2 categories.


I'm using macOS Catalina 10.15 Beta(19A558d) personally, but the problem shows on other systems too. 
Thank you for your advice.

**Comment by VladyslavBondarenko** [comment]
Seems to be fixed, closing.
Comment please if it's not so
