### ISSUE TITLE
type 'ArgumentError' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by damanjeetkaurchadha** [flutter/flutter#40646]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by janmoppel** [comment]
Hello @damanjeetkaurchadha !

Thank you for posting an issue.
As no information was provided, closing it for now. If you have a problem to report, please open a new issue and fill in the information requested in the template (including steps to reproduce and a `flutter doctor -v` command output).

Thank you.
