### ISSUE TITLE
[google_maps_flutter] iOS: Child route draws partially over parent route after pop route

### ISSUE THREAD

**Issue by martin-fink** [flutter/flutter#40655]
I encountered a strange issue with google_maps_flutter (^0.5.21+2), that I can only reproduce on iOS devices, but not on the simulator:

I have two pages, both containing a google map widget. When I press the home button or open another app on the second screen, the re-open my flutter app, and go back to the previous page, flutter does not correctly redraw the first page.  
I observed that I can still click on elements that are on Page 1, but I cannot see them. If you remove the google map widget from either of those two pages, the bug does not occur.

Here is a video with the sample app: https://imgur.com/a/KFeJsUS

## Steps to Reproduce

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Page 1'),
      ),
      body: GoogleMap(
        initialCameraPosition: CameraPosition(
          target: LatLng(0, 0),
          zoom: 9.5,
        ),
        mapType: MapType.normal,
        markers: {
          Marker(markerId: MarkerId('123'), onTap: () {
            Navigator.of(context).push(MaterialPageRoute(
              builder: (context) => PageTwo(),
            ));
          }),
        },
      ),
    );
  }
}

class PageTwo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Page 2'),
      ),
      body: GoogleMap(
        initialCameraPosition: CameraPosition(
          target: LatLng(0, 0),
          zoom: 9.5,
        ),
      ),
    );
  }
}
```

1. Open the app
2. Click on the marker (lat: 0, lng: 0)
3. Close the app by pressing the home button (App goes into the background, does not get killed)
4. Open the app again
5. Click on the back chevron in the navigation bar

## Logs

No log is printed while executing the steps described above.

```
$ flutter analyze
Analyzing maps_bug_example...
No issues found! (ran in 5.8s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G87, locale
    en-DE)
    • Flutter version 1.9.1+hotfix.2 at /usr/local/bin/flutter
    • Framework revision 2d2a1ffec9 (10 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/martin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/martin/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/martin/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android
      Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.2)
    • IntelliJ at /Users/martin/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        •
      android-x86 • Android 10 (API 29) (emulator)
    • iPhone Xʀ                 • 954462E6-5F2A-4FC3-85F1-E62C8BEC4AE5 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

! Doctor found issues in 1 category.
```

**Comment by benoitjadinon** [comment]
also happens when shutting down the phone (instead of pressing the Home button)

**Comment by louisdedecker** [comment]
We experienced the same problem this morning with @benoitjadinon.
The dirty fix we found was to toggle the opacity of the Google map widget to 0 when navigating page 2, and toggle it back to 1 when coming back.
(also works with the "Visibility" widget except you lose the position changes on google maps every time you make it appear)
I know ... it's a dirty solution ;)

`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double opactity = 1;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Page 1'),
      ),
      body: Opacity(
        opacity: opactity,
        child: GoogleMap(
          initialCameraPosition: CameraPosition(
            target: LatLng(0, 0),
            zoom: 9.5,
          ),
          mapType: MapType.normal,
          markers: {
            Marker(
                markerId: MarkerId('123'),
                onTap: () async {
                  setState(() {
                    opactity = 0;
                  });
                  await Navigator.of(context).push(MaterialPageRoute(
                    builder: (context) => PageTwo(),
                  ));
                  setState(() {
                    opactity = 1;
                  });
                }),
          },
        ),
      ),
    );
  }
}

class PageTwo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Page 2'),
      ),
      body: GoogleMap(
        initialCameraPosition: CameraPosition(
          target: LatLng(0, 0),
          zoom: 9.5,
        ),
      ),
    );
  }
}
`

**Comment by martin-fink** [comment]
@louisdedecker Thanks, this works! Better dirty than displaying a white page to the user :)

**Comment by timeuser** [comment]
@louisdedecker Thank you! Dirty workaround but at least it works.

**Comment by RyanRamchandar** [comment]
@timeuser this workaround was inconsistent for me and caused odd UI artifacts or it would ignore gestures altogether after swiping back. It seems for complex apps it is not a reliable workaround.

**Comment by timeuser** [comment]
@RyanRamchandar @louisdedecker It seems to depend on your widget tree how effective it can be. I ended up having to use a Visibility widget as mentioned instead of Opacity on a Drawer widget I had farther up the tree that was disappearing also. It is definitely not what I consider a solution. It's dirty and makes the app screen flicker and flash but I've been able to make our app function at least. Hopefully the Flutter team fixes the underlying problem soon.

**Comment by RyanRamchandar** [comment]
@timeuser Good idea. I'll try moving the Opacity/Visibility widget higher up the tree to see if that is more consistent. I agree that making it functional > looking pretty in this case. Currently, this is a pain point for all my iOS users.

**Comment by TyrWang** [comment]
Thanks a lot! The dirty workaround works to me. 
Is there any update for this?

**Comment by TyrWang** [comment]
#35183

**Comment by martin-fink** [comment]
This workaround does work, but it doesn't prevent another problem:

I have a Drawer in my first page. After going through the steps I described above, applying the workaround by toggling opacity to 0.0 before pushing the route and back to 1.0 after the user returned, I open the navigation drawer, but the drawer is invisible. It does listen for clicks, I just can't see the drawer, the buttons are there.

I've tried to move the Opacity widget further up the tree to include the whole scaffold, which didn't prevent it from happening.

I am only able to make the drawer visible again by blindly clicking on another menu item in the nav drawer and opening another route (without Google Maps) by doing this.

Again, this only happens on physical iOS devices, not on Android or on the Simulator.

**Comment by timeuser** [comment]
@martin-fink As mentioned above I had the same problem with a Drawer. The only way to make it work was to use Visibility widget instead of Opacity in the hack. That effectively removes that widget subtree completely and causes it to lose state but it is displayed for me then. 

Hopefully this is actually fixed soon. Comment [here](https://github.com/flutter/flutter/issues/40050#issuecomment-554573461) indicates it may be fixed in Dev channel.

**Comment by martin-fink** [comment]
@timeuser Yeah, I tried to use Visibility, but somehow that caused the whole app to crash after repeatedly opening and closing the second page with a `Terminated due to memory issue` error.

Thanks for linking me to that thread!

**Comment by martin-fink** [comment]
I've tested the bevhavior with the latest beta channel, and it seems that everything should work fine now. Hopfully the fix will soon be merged into the stable channel.

```
Flutter 1.12.13+hotfix.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 4f54e46f56 (23 hours ago) • 2019-12-04 09:20:18 -0800
Engine • revision 6955b06ced
Tools • Dart 2.7.0
```

**Comment by pro100svitlo** [comment]
to prevent losing map data (position and zoom) I store it on main screen, and when map widget become `visible again` - populate stored data to it.
The only one feelable issue - when ios user make swipe screen back - the previous screen (with map) is white, so its confusing little bit for them.
