### ISSUE TITLE
动态更新数据时控件显示异常 (Control displays an exception when dynamically updating data)

### ISSUE THREAD

**Issue by gqdy365** [flutter/flutter#40658]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by janmoppel** [comment]
Hello @gqdy365 !

Thank you for posting an issue.
We've translated this issue's title into English using Google Translate and wrote it in brackets. If you're comfortable writing in English, please check the translation and update it if necessary. 

Also, can you please provide more details and steps on how to reproduce it?

Thanks you.

**Comment by janmoppel** [comment]
Hello @gqdy365 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
