### ISSUE TITLE
Difficult to understand error from markNeedsBuild 

### ISSUE THREAD

**Issue by jamesr** [flutter/flutter#4065]
## Steps to Reproduce

When modifying the demo app I ended up crafting a scenario equivalent to applying the following diff to the sample app produced by 'flutter create': https://gist.github.com/jamesr/2dd7b2a3bc6a4e43781d43c966f6555f

When run, this threw an exception from inside markNeedsBuild() that is not easy to map back to my application code.  The call stack is 254 frames deep but the only frames in my application's code is main()'s call to runApp().

## Flutter Doctor

Paste the output of running `flutter doctor` here.

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/jamesr/flutter
    • Framework revision a48b063a10 (3 hours ago), engine revision 8ecb015767

[✓] Android toolchain - develop for Android devices (Android SDK 22.0.1)
    • Android SDK at /Users/jamesr/Library/Android/sdk
    • Platform android-23, build-tools 22.0.1
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2

## Logs and Crash Reports

Here is the exception stack as recorded by 'flutter logs'.  Be aware that the callstack frame numbering is inconsistent between this and what Atom shows:

https://gist.github.com/jamesr/04327cab1ce3c454feb459ec73414613

/cc @hixie

**Comment by jamesr** [comment]
Inconsistent frame number filed as #4062

**Comment by abarth** [comment]
I can reproduce the issue.

**Comment by abarth** [comment]
For the record, I don't think you did anything wrong.  This is just a bug in the framework.
