### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.inputmethod.InputConnection android.view.View.onCreateInputConnection(android.view.inputmethod.EditorInfo)' on a null object reference

### ISSUE THREAD

**Issue by wd668944** [flutter/flutter#40659]
```
E/AndroidRuntime(10560): 	at android.view.inputmethod.InputMethodManager.onWindowFocus(InputMethodManager.java:1447)
E/AndroidRuntime(10560): 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3316)
E/AndroidRuntime(10560): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10560): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(10560): 	at android.app.ActivityThread.main(ActivityThread.java:5293)
E/AndroidRuntime(10560): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10560): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(10560): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(10560): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
I/Process (10560): Sending signal. PID: 10560 SIG: 9
Lost connection to device.
```

how to solve?  thanks.

**Comment by wd668944** [comment]
my flutter doctor

**Comment by wd668944** [comment]
my flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4-pre.1, on Microsoft Windows [Version 10.0.17763.1], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Android Studio (version 3.2)
[√] Connected device (1 available)

• No issues found!

**Comment by escamoteur** [comment]
What did you do when this happened?

**Comment by wd668944** [comment]
> What did you do when this happened?
i used flutter_inappbrowser...Leave  route that has a webview ...Use the url_launcher to jump to other apps,Cut back to app flash back

**Comment by escamoteur** [comment]
`Cut back to app flash back` what do you mean by this?

**Comment by wd668944** [comment]
> `Cut back to app flash back` what do you mean by this?

Use the url_launcher to jump to other apps, back my app.....my app exit

**Comment by wd668944** [comment]
> `Cut back to app flash back` what do you mean by this?

this is my catlog
09-17 19:30:07.643 E/InputDispatcher(1752): channel '3e85b054 com.zhiyeit.mall/com.zhiyeit.mall.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by BondarenkoStas** [comment]
@wd668944 Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by wd668944** [comment]
this is my webview plugin:flutter_inappbrowser  
this page in route"service"
InAppWebView(
        initialFile: "assets/lost/index.html",
        initialHeaders: {},
        initialOptions: {},
        onWebViewCreated: (InAppWebViewController controller) {},
        onLoadStart: (InAppWebViewController controller, String url) {
          print("started $url");
          setState(() {
            this.url = url;
          });
        },
        onLoadStop: (InAppWebViewController controller, String url) {},
        onProgressChanged: (InAppWebViewController controller, int progress) {
          setState(() {
            this.progress = progress / 100;
          });
        },
      );
i leave route"service" to route"tabs"
in route "tabs"
i use url_launcher to other app
return my application...My application exits

**Comment by wd668944** [comment]
> @wd668944 Please provide a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

look up

**Comment by escamoteur** [comment]
Sorry but that seems to be a problem with the plugin. Please raise there an issue.

**Comment by wd668944** [comment]
> Sorry but that seems to be a problem with the plugin. Please raise there an issue.

thanks，Is the reason why I used flutter_inappbrowser，The previous mistake was that it was the cause of flutter，Now I provide the error to flutter_inappbrowser and hope they can solve it，thank you！
