### ISSUE TITLE
pubspec.yaml is not getting updated with flutter packages upgrade

### ISSUE THREAD

**Issue by ShivamArora** [flutter/flutter#40657]
## Steps to Reproduce

1. I had an existing project running on Flutter version 1.5.4+hotfix.2
2. I used the `flutter upgrade` command to upgrade to the latest version i.e 1.9.1. This should upgrade flutter as well as all the packages being used.
3. After `flutter upgrade`, I can see some of the package version upgrades in `pubspec.lock` but none in `pubspec.yaml`.
4. I tried manually running `flutter packages upgrade` but that didn't serve any purpose.
5. All the dependencies are still using their previous version in `pubspec.yaml` and not being updated to their latest versions.

Output of `flutter doctor -v`:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.4 18E226, locale
    en-IN)
    • Flutter version 1.9.1+hotfix.2 at /Users/shivam/sdks/flutter
    • Framework revision 2d2a1ffec9 (10 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/shivam/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.7019
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by escamoteur** [comment]
This is by design. `flutter packages upgrade` never touches your pubspec.yaml maybe vote for this issue https://github.com/flutter/flutter/issues/12627 which would make it easier to update your pubspec.yaml manually after an upgrade.
I recommend using `any` if you don't have to use a specific version.

**Comment by ShivamArora** [comment]
@escamoteur What's the point of upgrading the package versions in `pubspec.lock` then? I believe when we run the app, it uses the versions specified in `pubspec.lock` and not from `pubspec.yaml`.

Am I right?

**Comment by escamoteur** [comment]
Yes indeed it will use that in pubspec lock. The poitn is that you can have in your pubspec: some_package: '^1.0.1' which means you allow package upgrade to use any package >1.0.1 but smaller '2.0.0'  see https://dart.dev/tools/pub/versioning#semantic-versions

But somewhere the actually selected versions have to be stored. This is done in pubspec.lock. Thats also why you should include that file in source control so that everyone checking out the project gets the same versions

**Comment by rgisi** [comment]
After running `pub upgrade` and re-testing my app:
Is there any way to port the higher dependency numbers in `pubspec.lock` to `pubspec.yaml`?
(Apart from the obvious way of copying by hand, of course...)

**Comment by chitgoks** [comment]
> This is by design. `flutter packages upgrade` never touches your pubspec.yaml maybe vote for this issue #12627 which would make it easier to update your pubspec.yaml manually after an upgrade.
> I recommend using `any` if you don't have to use a specific version.

i remember when i started with flutter that it highlights libs that can be upgraded to a higher version.
then im not sure when at some point it does not work anymore.

i like it better that pubspec.yaml is affected instead of .lock

**Comment by bensal-kb** [comment]
Opening 'widget_test.dart' and running it solved my issue
