### ISSUE TITLE
Issue from website page Flutter for Web开发者

### ISSUE THREAD

**Issue by LISONG040576** [flutter/flutter#40661]
From URL: https://www.flutterchina.club/web-analogs.md

请问，flutter 写 web 应用 ，如何获取电脑上的文件呢？

(Google translation) Excuse me, flutter writes web application, how to get the files on the computer?

**Comment by LISONG040576** [comment]
例如：我想上传一张图片，怎么实现呢？

**Comment by BondarenkoStas** [comment]
@LISONG040576 Not sure If I correctly understood the question, will this be helpful https://flutter.dev/docs/development/ui/assets-and-images?
What is the exact issue you mentioned in the topic? The page https://flutterchina.club/web-analogs/ opens.

**Comment by janmoppel** [comment]
Hello @LISONG040576 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
