### ISSUE TITLE
Does not show

### ISSUE THREAD

**Issue by 007fred50** [flutter/flutter#40667]
Hello

I trying to get flutter to work, but i got an problem. but then i done with isntall the app. i just get stuck in installing app. i get no print() state. i only see (**Built build/app/outputs/apk/debug/app-debug.apk.**)

Flutter run:
```
Launching lib/main.dart on X23 in debug mode...
Initializing gradle...                                              0.9s
Resolving dependencies...                                           3.3s
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         4.1s
Built build/app/outputs/apk/debug/app-debug.apk.
```

What i expert is i can see the log (print()) from my code. but nothing shows up.

**Comment by escamoteur** [comment]
Looking at the log output your app wasn't deployed to the device at all. Is that all output you get?
Can you reproduce this with an empty sample project?
Also please add the output of flutter doctor -v

**Comment by 007fred50** [comment]
Hej,

Sorry for the issue, i fixed it with restart my PC.
So now it works again.
