### ISSUE TITLE
Gallery's homepage toolbar doesn't change color when theme is changed

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4067]
To repro:

* Open gallery
* Open drawer
* Change theme to Dark
* Close drawer

Expected: Toolbar to change from purple to dark gray (or similar)

Actual: toolbar stays purple _until you scroll up/down_

**Comment by sethladd** [comment]
cc @Hixie

**Comment by Hixie** [comment]
I'll take a look.

**Comment by Hixie** [comment]
Got a fix. I'll write a test then submit it.

**Comment by sethladd** [comment]
:metal:
