### ISSUE TITLE
ProcessException: Process “…\gradlew.bat” exited abnormally: Starting a Gradle Daemon (subsequent builds will be faster)

### ISSUE THREAD

**Issue by PE-Jeon** [flutter/flutter#40676]
**Summary**
I'm starting studying Flutter with Firebase. I have some experience with using Firebase through Kotlin android. When run a new flutter application which is completely new one through Android Studio, it works well. However, after finish settings for Firebase such as...

Adding google-services.json from Firebase project.

app/build.gradle `apply plugin: 'com.google.gms.google-services'`

android/build.gradle `classpath 'com.android.tools.build:gradle:3.2.1'`

pubspec.yaml `firebase_core: ^0.2.5  # add dependency for Firebase Core`

and below are
**versions of**

```
android studio 3.4.1

flutter --version
Flutter 1.9.1+hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2d2a1ffec9 (10 days ago) • 2019-09-06 18:39:49 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

gradle version : gradle-4.10.2-all.zip
```

When I ran, I've got
**Error**

```
* Error running Gradle:
ProcessException: Process "D:\DEV\flutter_firebase1\flutter_app\android\gradlew.bat" exited abnormally:
Starting a Gradle Daemon (subsequent builds will be faster)


FAILURE: Build failed with an exception.

* Where:
Build file 'D:\DEV\flutter_firebase1\flutter_app\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
  Command: D:\DEV\flutter_firebase1\flutter_app\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.`
```

I swear I completely followed instruction of documentation of Firebase. And I tried it again with completely new project. How can I do for it?

**Comment by SKYHIT-98** [comment]
I am having the same problem please help me

**Comment by escamoteur** [comment]
Did this work with older versions of flutter? Alternatively try it if it works on master channel.

**Comment by SKYHIT-98** [comment]
It is working well without the firebase implementation but as soon as i add the firebase setup it crashes saying build gradle is failed
![bug](https://user-images.githubusercontent.com/55046432/65148222-62629980-da3d-11e9-81d9-11306d7f8956.png)

**Comment by BondarenkoStas** [comment]
@PE-Jeon I just wonder, does it have something to do with https://github.com/flutter/flutter/issues/38163#issuecomment-520429066? Can you please try to lower google-services?

**Comment by BugsBunnyBR** [comment]
@PE-Jeon , please provide your app/build.gradle, it looks like you have some miss configuration there.

## NOTE: If you have hardcoded your signing keys and passwords there you should replace it with some gibberish before posting.

**Comment by PE-Jeon** [comment]
Sorry for late reply since I had a trip for two weeks.

this is all of my app/build.gradle

`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutter_app"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
apply plugin 'com.google.gms.google.services'`

**Comment by PE-Jeon** [comment]
> @PE-Jeon , please provide your app/build.gradle, it looks like you have some miss configuration there.
> 
> ## NOTE: If you have hardcoded your signing keys and passwords there you should replace it with some gibberish before posting.

Sorry for late reply since I had a trip for two weeks.

this is all of my app/build.gradle

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutter_app"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
apply plugin 'com.google.gms.google.services'
```

**Comment by PE-Jeon** [comment]
> @PE-Jeon , please provide your app/build.gradle, it looks like you have some miss configuration there.
> 
> ## NOTE: If you have hardcoded your signing keys and passwords there you should replace it with some gibberish before posting.

Sorry for late reply since I had a trip for two weeks.

this is all of my app/build.gradle

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutter_app"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
apply plugin 'com.google.gms.google.services'
```

**Comment by PE-Jeon** [comment]
> @PE-Jeon I just wonder, does it have something to do with [#38163 (comment)](https://github.com/flutter/flutter/issues/38163#issuecomment-520429066)? Can you please try to lower google-services?

I tried 4.2.0 of google-services, but it doesn't work also,...

**Comment by kroikie** [comment]
@PE-Jeon

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/335. Any further collaboration will be done there.
