### ISSUE TITLE
After adding shared_preferences: ^0.5.3+4 Failed to build iOS app

### ISSUE THREAD

**Issue by Kartik-AI** [flutter/flutter#40672]
@mehmetf @zoechi @kangwang1988 @mklim 
## Steps to Reproduce

1. Create new Flutter app
2. Add shared_preferences: ^0.5.3+4 in pubspec.yaml file and run flutter pub get command
3. Than run flutter run command

## After flutter run output is

Launching lib/main.dart on iPhone 8 Plus in debug mode...
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                           9.4s
 └─Compiling, linking and signing...                         5.0s
Xcode build done.                                           16.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    mkdir -p /Users/ivorywebdesign/Documents/Kartik/VikramGandhi'sProject/gonal/build/ios/Debug-iphonesimulator/Runner.app/Frameworks
    rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "-
    Modules" "/Users/ivorywebdesign/Documents/Kartik/VikramGandhi'sProject/gonal/ios/Pods/../.symlinks/flutter/ios/Flutter.framework"
    "/Users/ivorywebdesign/Documents/Kartik/VikramGandhi'sProject/gonal/build/ios/Debug-iphonesimulator/Runner.app/Frameworks"
    building file list ... done
    Flutter.framework/
    Flutter.framework/Flutter
    Flutter.framework/Info.plist
    Flutter.framework/icudtl.dat
    Flutter.framework/_CodeSignature/
    Flutter.framework/_CodeSignature/CodeResources

    sent 94440063 bytes  received 120 bytes  188880366.00 bytes/sec
    total size is 94428117  speedup is 1.00
    Stripped /Users/ivorywebdesign/Documents/Kartik/VikramGandhi'sProject/gonal/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework/Flutter of architectures: armv7
    arm64
    Code Signing /Users/ivorywebdesign/Documents/Kartik/VikramGandhi'sProject/gonal/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework with Identity -
    /usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements
    '/Users/ivorywebdesign/Documents/Kartik/VikramGandhi'sProject/gonal/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework'
    /Users/ivorywebdesign/Documents/Kartik/VikramGandhi'sProject/gonal/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh: eval: line 131: unexpected EOF while looking
    for matching `''
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build systemnote: Planning buildnote: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 8 Plus.

## Flutter doctor is

[✓] Flutter (Channel unknown, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G84, locale en-IN)
    • Flutter version 1.9.1+hotfix.2 at /Users/ivorywebdesign/FlutterSdk/flutter
    • Framework revision 2d2a1ffec9 (10 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPhone 8 Plus • BF7B0797-9EA9-4E9D-B4E0-1F6A6B598C47 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 2 categories.

## flutter run -verbose last error is 

 sent 94440063 bytes  received 120 bytes  62960122.00 bytes/sec
               total size is 94428117  speedup is 1.00
               Stripped

/Users/ivorywebdesign/Documents/Kartik/VikramGandhi'sProject/gonal/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework/F
               lutter of architectures: armv7 arm64
               Code Signing

/Users/ivorywebdesign/Documents/Kartik/VikramGandhi'sProject/gonal/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework
               with Identity -
               /usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements

'/Users/ivorywebdesign/Documents/Kartik/VikramGandhi'sProject/gonal/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework'
               /Users/ivorywebdesign/Documents/Kartik/VikramGandhi'sProject/gonal/ios/Pods/Target Support
Files/Pods-Runner/Pods-Runner-frameworks.sh:
               eval: line 131: unexpected EOF while looking for matching `''
               Command PhaseScriptExecution failed with a nonzero exit code
           
           
[  +87 ms] Could not build the application for the simulator.
[   +1 ms] Error launching application on iPhone 8 Plus.
[   +5 ms] "flutter run" took 32,125ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:477:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:58:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main (file:///Users/ivorywebdesign/FlutterSdk/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by jmagman** [comment]
You have a single quote in your path, which CocoaPods can't handle.  See https://github.com/CocoaPods/CocoaPods/issues/1532.
CocoaPods bug, not Flutter.  Closing.

**Comment by naveedahmad99** [comment]
Oh Thanks man, I have a quote mark "  '  " in the Build name, that created issue in building
