### ISSUE TITLE
Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by sumujain1995** [flutter/flutter#40683]
When i build for generic devices or run for real devices it gives me following error on xcode
```
> ld: warning: Could not find auto-linked framework 'Flutter'
> Undefined symbols for architecture armv7:
>   "_FlutterMethodNotImplemented", referenced from:
>       -[FLTDeviceInfoPlugin handleMethodCall:result:] in DeviceInfoPlugin.o
>   "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
>       objc-class-ref in DeviceInfoPlugin.o
> ld: symbol(s) not found for architecture armv7
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
And flutter build command runs without error

flutter doctor:
```
> 121:flutter_module sumeetjain$ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-IN)
> [✗] Android toolchain - develop for Android devices
>     ✗ Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
>       If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
>       You may also want to add it to your PATH environment variable.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 10.3)
> [!] Android Studio (not installed)
> [✓] Connected device (2 available)
> 
> ! Doctor found issues in 2 categories. 

```

But when i changed channel to master, error doesn't come.
Since i want to release my app, i cant do that on Master channel right !
Master channel flutter doctor 

```
[✓] Flutter (Channel master, v1.10.3-pre.70, on Mac OS X 10.14.6 18G95, locale en-IN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by jmagman** [comment]
Can we get a sample app that reproduces the issue?

**Comment by sumujain1995** [comment]
[https://drive.google.com/file/d/14PI_Dhy0aAkyO3MrUsxNp2pRpKPg4ss0/view?usp=sharing
](url)

Added all my dependencies and created the sample flutter module and got the same above issue while building on STABLE channel

**Comment by escamoteur** [comment]
Actually you can use the master channel if your App works with it without problems

**Comment by sumujain1995** [comment]
Hey for the release purpose i downgraded to **v1.7.8-hotfixes** and got rid of the errors..
Flutter doctor ->

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel v1.7.8-hotfixes, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-IN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.
```

**Comment by sumujain1995** [comment]
@escamoteur 

From [Flutter wiki](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels)

**master**
The current tip-of-tree, absolute latest cutting edge build. Usually functional, though sometimes we accidentally break things.

**stable**
When we believe we have a particularly good build, we promote it to the stable channel. We intend to do this more or less every quarter, but this may vary. We recommend that you use this channel for all production app releases. We may ship hotfixes to the stable channel for high-priority bugs, although our intent is to do this rarely.

**Comment by escamoteur** [comment]
I know, but if it works, why not :-)

**Comment by jmagman** [comment]
@sumujain1995 I don't have permission to that Google drive link, plus I don't think anyone triaging these bugs wants to download an arbitrary file onto their machine.  If you could put it on GitHub or just put in reproduction steps that works too.
Sounds like you created a flutter module and added some pubspec dependencies, then it just reproduced?

**Comment by jmagman** [comment]
@sumujain1995 Also you said "created the sample flutter module".  Are you talking about an [add-to-app module](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#the-flutter-module-project-template)?  Or something else?

**Comment by sumujain1995** [comment]
@jmagman sorry for that Google Drive link !
Yes, i created a flutter module and added some pubspec dependencies, then it just reproduced !!
Yes i created sample flutter module using this steps  [add-to-app module](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#the-flutter-module-project-template)

Added the sample project in [repo](https://github.com/sumujain1995/sampleFlutterModule)

**Comment by jmagman** [comment]
I tried to reproduce. I dropped back to v1.9.1+hotfix.2.
```shell
$ git clone git@github.com:sumujain1995/sampleFlutterModule.git
$ cd sampleFlutterModule
$ flutter build ios
...
    /usr/bin/codesign --force --sign 417E25D92E31F4C76B558F84F01E31D25BC8FA16  --preserve-metadata=identifier,entitlements
    '/Users/magder/Projects/sampleFlutterModule/build/ios/Release-iphoneos/Runner.app/Frameworks/Flutter.framework'
    /Users/magder/Projects/sampleFlutterModule/build/ios/Release-iphoneos/Runner.app/Frameworks/Flutter.framework: replacing existing signature
    /Users/magder/Projects/sampleFlutterModule/build/ios/Release-iphoneos/Runner.app/Frameworks/Flutter.framework: Permission denied
    Command PhaseScriptExecution failed with a nonzero exit code
```
I hit https://github.com/flutter/flutter/issues/39507.  So I cherry-picked that onto v1.9.1+hotfix.2 to get past it since that's not what you're hitting.
```shell
$ flutter build ios
Building flutter tool...
Running "flutter pub get" in sampleFlutterModule...                 0.6s
Building com.example.myFlutter for device (ios-release)...
Found saved certificate choice "iPhone Developer: Jenn Magder (2867XHZLGW)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "iPhone Developer: Jenn Magder (2867XHZLGW)"
Running pod install...                                              1.5s
Running Xcode build...
etc
$ open .ios/Runner.xcworkspace
```
Then in Xcode I set the development team in the Runner target, and the build succeeded.

@sumujain1995 What am I missing from my steps?

This is kind of academic since it's working on master and you are using the add-to-app flow.  Add-to-app is in preview and is only supported on the master channel.  See caveats here https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#intro.

**Comment by sumujain1995** [comment]
@jmagman thanks for noting out that, i missed that totally
 Is there any plans to push this changes on Stable Channel ??

**Comment by sumujain1995** [comment]
Is there any plans to push this changes on Stable Channel ?? @jmagman @escamoteur @BondarenkoStas

**Comment by escamoteur** [comment]
@sumujain1995 You won't expedite this by reopening the issue.
