### ISSUE TITLE
Automatic shader-compile jank removal using SkSL precompile

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#40686]
Original title: "Shader compilations during image scrolling on ToT"

See https://b.corp.google.com/issues/140174804 for discussion. Conversation should occur there.

**Comment by liyuqian** [comment]
Skia has fixed the bug and I've successfully prototyped a solution that sees a 90% decrease in compile time (from 10ms per shader to about 1ms per shader). Hence our stage 2 solution SkSL seems to be valid, and we will continue to work on it and track the progress here.

**Comment by liyuqian** [comment]
With https://skia-review.googlesource.com/c/skia/+/243739, we've now seen the shader compilation time drop to 0.1ms/shader even on a very weak GPU which spends 40ms/shader before that patch.

**Comment by cbracken** [comment]
I'm closing this to match the status of  https://b.corp.google.com/issues/140174804, however, @liyuqian is still working on long-term solutions for shader jank.

@liyuqian if there isn't a bug open yet to track that work, please open it and cross-reference it here.
