### ISSUE TITLE
how get current path in (flutter web)

### ISSUE THREAD

**Issue by mahmoudsalah37** [flutter/flutter#40680]
i want to create db in any path in flutter web 
how i can do it?
like=>
// File path to a file in the current directory
String dbPath = 'sample.db';
DatabaseFactory dbFactory = databaseFactoryIo;

// We use the database factory to open the database
Database db = await dbFactory.openDatabase(dbPath);

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
