### ISSUE TITLE
RaisedButton.icon should have padding argument

### ISSUE THREAD

**Issue by cpboyd** [flutter/flutter#40696]
## Use case

`RaisedButton` already has a `padding` argument, but the named constructor `RaisedButton.icon()` does not.

As a result, it's not as easy to modify padding on a `RaisedButton.icon()`.

## Proposal

Configuration parity between `RaisedButton` and the named constructor `RaisedButton.icon()`.

**Comment by AyushBherwani1998** [comment]
I would like to work on this issue @shihaohong @escamoteur

**Comment by shihaohong** [comment]
Sounds good @AyushBherwani1998 let me know if you need help preparing the PR and if you need a review!

**Comment by AyushBherwani1998** [comment]
@shihaohong What kind of test case would you suggest to check the added functionality? Getting the `RaisedButton.icon` object in the widget test and checking the padding of the button will work?

**Comment by AyushBherwani1998** [comment]
@shihaohong thanks for the leads. I have submitted a PR, can you please review it.
