### ISSUE TITLE
Wavy underlines don't work anymore

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#407]
Run `flutter/examples/widgets/styled_text.dart`.
The bold text ("Dave", "HAL") should be underlined with a wavy underline. It is not.

**Comment by jason-simmons** [comment]
In InlineTextBox we're flowing through the code path for drawing a wavy underline.  But the textDecorationThickness (obtained from the font metrics) is so small that the wave can't be seen.

The wave will be visible if you enlarge the fontSize of the text style in the app.

**Comment by Hixie** [comment]
Looks fine to me on Nexus 6. What device are you on?

**Comment by jason-simmons** [comment]
I'm using a Nexus 4

**Comment by Hixie** [comment]
We used the Nexus 6 to zoom in on the Nexus 4 and it turns out it's barely visible but it is wavy! Not clear what the right behaviour is here, so without a concrete customer request I'm going to close this for now.
