### ISSUE TITLE
[web] Missing border/boxShadow in flutter web when both border and border radius are set

### ISSUE THREAD

**Issue by ymback** [flutter/flutter#40728]
```dart
Container(
          width: 260.0,
          height: 50.0,
          decoration: BoxDecoration(
            border: Border.all(
              width: 1.0,
              color: Colors.white,
            ),
            borderRadius: BorderRadius.all(
              Radius.circular(
                25.0,
              ),
            ),
            color: Colors.pink,
          ),
)
```
Look, using code above, works on native and show white border, but not show when using flutter web, and debug in chrome.
However, when i change border width, it shows, set 7.0 not show, but 8.0 shows.

```
[√] Flutter (Channel master, v1.10.4-pre.52, on Microsoft Windows [Version 10.0.18362.356], locale zh-CN)
    • Flutter version 1.10.4-pre.52 at C:\Temp\Android\flutter
    • Framework revision 110db03f24 (4 hours ago), 2019-09-17 17:10:18 -0700
    • Engine revision 63873d9f42
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 7799f424f4)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Temp\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • ANDROID_HOME = C:\Temp\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2017.3.5
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700

[√] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[√] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132
    • Server • web    • web-javascript • Flutter Tools

• No issues found!

```

**Comment by ymback** [comment]
Also boxShadow

**Comment by ymback** [comment]
I found this https://github.com/flutter/flutter/issues/37121#issuecomment-532389899. @ditman 
Now my demo code in https://github.com/flutter/flutter/issues/40728#issue-494977485 works as expect, but I have new demo code, shows nothing, even the child is disappeared.
```dart 
Container(
      alignment: Alignment.center,
      width: 88.0,
      height: 48.0,
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(
            6.0,
          ),
          bottomLeft: Radius.circular(
            6.0,
          ),
        ),
        border: Border(
          top: BorderSide(
            color: Colors.blue,
            width: 1.0,
          ),
          left: BorderSide(
            color: Colors.blue,
            width: 1.0,
          ),
          bottom: BorderSide(
            color: Colors.blue,
            width: 1.0,
          ),
        ),
      ),
      child: Text(
        "Previous",
        style: TextStyle(
          fontSize: 18.0,
          color: Colors.black,
        ),
      ),
    );
```
![Nothing](https://user-images.githubusercontent.com/6318614/65300650-d076a000-dba6-11e9-8318-fa6158567c7b.jpg)
And after remove
```dart
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(
            6.0,
          ),
          bottomLeft: Radius.circular(
            6.0,
          ),
        ),
```
The border and child appears
![Appear](https://user-images.githubusercontent.com/6318614/65300763-382ceb00-dba7-11e9-8640-da47dda01fc6.jpg)

flutter doctor -v
```
[√] Flutter (Channel dev, v1.10.5, on Microsoft Windows [Version 10.0.18362.356], locale zh-CN)
    • Flutter version 1.10.5 at C:\Temp\Android\flutter
    • Framework revision 3cf88fed6d (26 hours ago), 2019-09-18 23:09:41 -0400
    • Engine revision 33ad6757e8
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 cb80ea7ba9)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Temp\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • ANDROID_HOME = C:\Temp\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2017.3.5
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700

[√] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[√] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

• No issues found!
```
https://github.com/flutter/engine/commit/33ad6757e88311f4fb9d341918894e2bc30e3b20 newer than https://github.com/flutter/engine/commit/851f4606f19541376b6e8915e7b8677b31853223

**Comment by ditman** [comment]
Very interesting! Thanks for the repro case, I'll take a look ASAP!

**Comment by ditman** [comment]
This is what I'm seeing in my error console: 

> "A borderRadius can only be given for uniform borders."

Looks like it comes from the [painting part](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/box_border.dart#L510) of the framework, and not from the web engine (I just verified your code [here](https://github.com/flutter/flutter/issues/40728#issuecomment-533410081) fails in the same way in Android).

**Can you confirm you see the same error, @ymback?**

PS: Here's the full stack trace that you'll see on your browser console or `flutter run` output:

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
Assertion failed: org-dartlang-app:///packages/flutter/src/painting/box_border.dart:510:12
borderRadius == null
"A borderRadius can only be given for uniform borders."

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new?template=BUG.md

User-created ancestor of the error-causing widget was:
Container org-dartlang-app:///packages/borders/main.dart:52:16

When the exception was thrown, this was the stack:
package:build_web_compilers/src/dev_compiler/dart_sdk.js 3990:11  throw_
package:build_web_compilers/src/dev_compiler/dart_sdk.js 3936:15  assertFailed
package:flutter/src/painting/box_border.dart 510:28               paint
package:flutter/src/painting/box_decoration.dart 464:25           paint
package:flutter/src/rendering/proxy_box.dart 1976:16              paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/proxy_box.dart 123:14               paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/shifted_box.dart 70:14              paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/box.dart 2501:14                    defaultPaint
package:flutter/src/rendering/custom_layout.dart 361:5            paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/proxy_box.dart 123:14               paint
package:flutter/src/material/material.dart 550:11                 paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/proxy_box.dart 123:14               paint
package:flutter/src/rendering/object.dart 384:12                  pushLayer
package:flutter/src/rendering/proxy_box.dart 1755:14              paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/proxy_box.dart 123:14               paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/proxy_box.dart 123:14               paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 135:10                  _repaintCompositedChild
package:flutter/src/rendering/object.dart 95:5                    repaintCompositedChild
package:flutter/src/rendering/object.dart 201:7                   [_compositeChild]
package:flutter/src/rendering/object.dart 182:7                   paintChild
package:flutter/src/rendering/proxy_box.dart 123:14               paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/proxy_box.dart 919:16               paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/proxy_box.dart 123:14               paint
package:flutter/src/rendering/proxy_box.dart 2462:13              paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/proxy_box.dart 123:14               paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 135:10                  _repaintCompositedChild
package:flutter/src/rendering/object.dart 95:5                    repaintCompositedChild
package:flutter/src/rendering/object.dart 201:7                   [_compositeChild]
package:flutter/src/rendering/object.dart 182:7                   paintChild
package:flutter/src/rendering/proxy_box.dart 123:14               paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/proxy_box.dart 123:14               paint
package:flutter/src/rendering/proxy_box.dart 3153:11              paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/box.dart 2501:14                    defaultPaint
package:flutter/src/rendering/stack.dart 594:5                    paintStack
package:flutter/src/rendering/stack.dart 602:7                    paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/proxy_box.dart 123:14               paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/proxy_box.dart 123:14               paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/proxy_box.dart 123:14               paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/proxy_box.dart 123:14               paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/proxy_box.dart 123:14               paint
package:flutter/src/rendering/custom_paint.dart 569:11            paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/proxy_box.dart 123:14               paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                  paintChild
package:flutter/src/rendering/view.dart 208:14                    paint
package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
package:flutter/src/rendering/object.dart 135:10                  _repaintCompositedChild
package:flutter/src/rendering/object.dart 95:5                    repaintCompositedChild
package:flutter/src/rendering/object.dart 937:29                  flushPaint
package:flutter/src/rendering/binding.dart 342:19                 drawFrame
package:flutter/src/widgets/binding.dart 774:13                   drawFrame
package:flutter/src/rendering/binding.dart 279:5                  [_handlePersistentFrameCallback]
package:flutter/src/scheduler/binding.dart 1040:15                [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 982:9                  handleDrawFrame
package:flutter/src/scheduler/binding.dart 791:7                  <fn>
package:build_web_compilers/src/dev_compiler/dart_sdk.js 28423:9  internalCallback

The following RenderObject was being processed when the exception was fired: RenderDecoratedBox#88a4a:
creator: DecoratedBox ← ConstrainedBox ← Container ← Center ← _BodyBuilder ← MediaQuery ←
LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ←
AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#d13c6 ink renderer] ← ⋯
parentData: <none> (can use size)
constraints: BoxConstraints(w=88.0, h=48.0)
size: Size(88.0, 48.0)
decoration: BoxDecoration:
border: Border(top: BorderSide(MaterialColor(primary value: Color(0xff2196f3)), 1.0,
BorderStyle.solid), bottom: BorderSide(MaterialColor(primary value: Color(0xff2196f3)), 1.0,
BorderStyle.solid), left: BorderSide(MaterialColor(primary value: Color(0xff2196f3)), 1.0,
BorderStyle.solid))
borderRadius: BorderRadius.only(topLeft: Radius.circular(6.0), bottomLeft: Radius.circular(6.0))
configuration: ImageConfiguration(bundle: PlatformAssetBundle#4ae01(), devicePixelRatio: 1.0,
locale: en_US, textDirection: TextDirection.ltr, platform: android)
This RenderObject had the following descendants (showing up to depth 5):
child: RenderPadding#9bde3 NEEDS-PAINT
child: RenderPositionedBox#830a7 NEEDS-PAINT
child: RenderParagraph#abd36 relayoutBoundary=up1 NEEDS-PAINT
text: TextSpan
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by ymback** [comment]
> This is what I'm seeing in my error console:
> 
> > "A borderRadius can only be given for uniform borders."
> 
> Looks like it comes from the [painting part](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/box_border.dart#L510) of the framework, and not from the web engine (I just verified your code [here](https://github.com/flutter/flutter/issues/40728#issuecomment-533410081) fails in the same way in Android).
> 
> **Can you confirm you see the same error, @ymback?**
> 
> PS: Here's the full stack trace that you'll see on your browser console or `flutter run` output:
> 
> ```
> ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
> The following assertion was thrown during paint():
> Assertion failed: org-dartlang-app:///packages/flutter/src/painting/box_border.dart:510:12
> borderRadius == null
> "A borderRadius can only be given for uniform borders."
> 
> Either the assertion indicates an error in the framework itself, or we should provide substantially
> more information in this error message to help you determine and fix the underlying cause.
> In either case, please report this assertion by filing a bug on GitHub:
> https://github.com/flutter/flutter/issues/new?template=BUG.md
> 
> User-created ancestor of the error-causing widget was:
> Container org-dartlang-app:///packages/borders/main.dart:52:16
> 
> When the exception was thrown, this was the stack:
> package:build_web_compilers/src/dev_compiler/dart_sdk.js 3990:11  throw_
> package:build_web_compilers/src/dev_compiler/dart_sdk.js 3936:15  assertFailed
> package:flutter/src/painting/box_border.dart 510:28               paint
> package:flutter/src/painting/box_decoration.dart 464:25           paint
> package:flutter/src/rendering/proxy_box.dart 1976:16              paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/proxy_box.dart 123:14               paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/shifted_box.dart 70:14              paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/box.dart 2501:14                    defaultPaint
> package:flutter/src/rendering/custom_layout.dart 361:5            paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/proxy_box.dart 123:14               paint
> package:flutter/src/material/material.dart 550:11                 paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/proxy_box.dart 123:14               paint
> package:flutter/src/rendering/object.dart 384:12                  pushLayer
> package:flutter/src/rendering/proxy_box.dart 1755:14              paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/proxy_box.dart 123:14               paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/proxy_box.dart 123:14               paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 135:10                  _repaintCompositedChild
> package:flutter/src/rendering/object.dart 95:5                    repaintCompositedChild
> package:flutter/src/rendering/object.dart 201:7                   [_compositeChild]
> package:flutter/src/rendering/object.dart 182:7                   paintChild
> package:flutter/src/rendering/proxy_box.dart 123:14               paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/proxy_box.dart 919:16               paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/proxy_box.dart 123:14               paint
> package:flutter/src/rendering/proxy_box.dart 2462:13              paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/proxy_box.dart 123:14               paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 135:10                  _repaintCompositedChild
> package:flutter/src/rendering/object.dart 95:5                    repaintCompositedChild
> package:flutter/src/rendering/object.dart 201:7                   [_compositeChild]
> package:flutter/src/rendering/object.dart 182:7                   paintChild
> package:flutter/src/rendering/proxy_box.dart 123:14               paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/proxy_box.dart 123:14               paint
> package:flutter/src/rendering/proxy_box.dart 3153:11              paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/box.dart 2501:14                    defaultPaint
> package:flutter/src/rendering/stack.dart 594:5                    paintStack
> package:flutter/src/rendering/stack.dart 602:7                    paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/proxy_box.dart 123:14               paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/proxy_box.dart 123:14               paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/proxy_box.dart 123:14               paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/proxy_box.dart 123:14               paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/proxy_box.dart 123:14               paint
> package:flutter/src/rendering/custom_paint.dart 569:11            paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/proxy_box.dart 123:14               paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 184:12                  paintChild
> package:flutter/src/rendering/view.dart 208:14                    paint
> package:flutter/src/rendering/object.dart 2193:7                  [_paintWithContext]
> package:flutter/src/rendering/object.dart 135:10                  _repaintCompositedChild
> package:flutter/src/rendering/object.dart 95:5                    repaintCompositedChild
> package:flutter/src/rendering/object.dart 937:29                  flushPaint
> package:flutter/src/rendering/binding.dart 342:19                 drawFrame
> package:flutter/src/widgets/binding.dart 774:13                   drawFrame
> package:flutter/src/rendering/binding.dart 279:5                  [_handlePersistentFrameCallback]
> package:flutter/src/scheduler/binding.dart 1040:15                [_invokeFrameCallback]
> package:flutter/src/scheduler/binding.dart 982:9                  handleDrawFrame
> package:flutter/src/scheduler/binding.dart 791:7                  <fn>
> package:build_web_compilers/src/dev_compiler/dart_sdk.js 28423:9  internalCallback
> 
> The following RenderObject was being processed when the exception was fired: RenderDecoratedBox#88a4a:
> creator: DecoratedBox ← ConstrainedBox ← Container ← Center ← _BodyBuilder ← MediaQuery ←
> LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ←
> AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#d13c6 ink renderer] ← ⋯
> parentData: <none> (can use size)
> constraints: BoxConstraints(w=88.0, h=48.0)
> size: Size(88.0, 48.0)
> decoration: BoxDecoration:
> border: Border(top: BorderSide(MaterialColor(primary value: Color(0xff2196f3)), 1.0,
> BorderStyle.solid), bottom: BorderSide(MaterialColor(primary value: Color(0xff2196f3)), 1.0,
> BorderStyle.solid), left: BorderSide(MaterialColor(primary value: Color(0xff2196f3)), 1.0,
> BorderStyle.solid))
> borderRadius: BorderRadius.only(topLeft: Radius.circular(6.0), bottomLeft: Radius.circular(6.0))
> configuration: ImageConfiguration(bundle: PlatformAssetBundle#4ae01(), devicePixelRatio: 1.0,
> locale: en_US, textDirection: TextDirection.ltr, platform: android)
> This RenderObject had the following descendants (showing up to depth 5):
> child: RenderPadding#9bde3 NEEDS-PAINT
> child: RenderPositionedBox#830a7 NEEDS-PAINT
> child: RenderParagraph#abd36 relayoutBoundary=up1 NEEDS-PAINT
> text: TextSpan
> ════════════════════════════════════════════════════════════════════════════════════════════════════
> ```

Oh my god, you are right, the console not show this error when using flutter web.
So the wordground is this:
```dart
        Container(
          width: 88.0,
          height: 48.0,
          child: Stack(
            children: <Widget>[
              Positioned(
                left: 0.0,
                right: -2.0,
                top: 0.0,
                bottom: 0.0,
                child: Container(
                  alignment: Alignment.center,
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(
                        6.0,
                      ),
                      bottomLeft: Radius.circular(
                        6.0,
                      ),
                    ),
                    border: Border.all(
                      color: Colors.blue,
                      width: 1.0,
                    ),
                  ),
                  child: Text(
                    "Previous",
                    style: TextStyle(
                      fontSize: 18.0,
                      color: Colors.black,
                    ),
                  ),
                ),
              ),
            ],
          ),
        );
```
Though it may not be a good wordaround, at least it shows what I want.
Thank you @ditman, I think this issue could be closed.

**Comment by ymback** [comment]
Oh, sorry @ditman, just I use my workaround above, not show the border in flutter web, you can try it.
It works in android.

**Comment by ditman** [comment]
You're right, this renders fine in android but not in web. Let me take a quick look why is that happening!

Thanks for the extended repro case!

**Comment by ditman** [comment]
(There's some instability in the tree and I can't override the Engine to diagnose what's going on. I'll take a look after this gets fixed: https://github.com/flutter/flutter/issues/40876)

**Comment by ditman** [comment]
I think the commit above fixed the issue:

![screenshot](https://user-images.githubusercontent.com/1255594/65560746-a7cb0f00-def4-11e9-8fba-d8cb7d2fb354.png)

**Comment by ymback** [comment]
Thank you.

**Comment by ymback** [comment]
Cause the master channel is broken now https://github.com/flutter/flutter/issues/40876#issuecomment-534780288, I'll try it later.
