### ISSUE TITLE
How to monitor flutter http traffic (pure dart instead of native calls by channel)?

### ISSUE THREAD

**Issue by feng562925462** [flutter/flutter#40725]
想采集flutter中的性能和行为等数据应该怎么做呢，
我尝试让程序发生崩溃，但只能出现js错误这种，
flutter网络请求不能被抓包工具进行采集的原因是什么呢
Translate by google translate:
> What should I do if I want to collect data such as performance and behavior in flutter?
I tried to make the program crash, but only the js error occurred.
What is the reason that the flutter network request cannot be collected by the packet capture tool?

**Comment by zxhwyp** [comment]
抓包需要配置指定一下dio库里面的代理吧

**Comment by ymback** [comment]
想Crash就搞个NPE
想抓包就自己设定个proxy，系统那个设定没用反正

**Comment by feng562925462** [comment]
抓包我使用的charles，保持手机和电脑同一网络，设置代理，flutter发起的网络请求无法抓取到，我不能理解这个原因

**Comment by feng562925462** [comment]
npe 是什么，我想制作多种crash，使用crash采集工具进行采集，但是我只能写出几个类似js的错误（数组越界、使用未定义变量等），都无法导致程序退出

**Comment by ymback** [comment]
> npe 是什么，我想制作多种crash，使用crash采集工具进行采集，但是我只能写出几个类似js的错误（数组越界、使用未定义变量等），都无法导致程序退出

APP的运行并不在native层，自然不会产生native的crash崩溃退出，所以你会看到红色的屏幕，以及越界等错误，想拦截这个错误，自己定义ErrorWidget，里面会返回给你错误信息，你再做个友好的界面
dart虚拟机并不会读取你在系统网络里设置的代理，你必须在app里自行设置代理，用dio或者别的网络请求工具，把proxy塞进去

**Comment by feng562925462** [comment]
> > npe 是什么，我想制作多种crash，使用crash采集工具进行采集，但是我只能写出几个类似js的错误（数组越界、使用未定义变量等），都无法导致程序退出
> 
> APP的运行并不在native层，自然不会产生native的crash崩溃退出，所以你会看到红色的屏幕，以及越界等错误，想拦截这个错误，自己定义ErrorWidget，里面会返回给你错误信息，你再做个友好的界面
> dart虚拟机并不会读取你在系统网络里设置的代理，你必须在app里自行设置代理，用dio或者别的网络请求工具，把proxy塞进去

非常感谢您的回复，我们团队想开发一款flutter的线上apm产品，因为iOS和安卓都很难采集到flutter应用的相关信息，我们应该如何入手

**Comment by ymback** [comment]
> > > npe 是什么，我想制作多种crash，使用crash采集工具进行采集，但是我只能写出几个类似js的错误（数组越界、使用未定义变量等），都无法导致程序退出
> > 
> > 
> > APP的运行并不在native层，自然不会产生native的crash崩溃退出，所以你会看到红色的屏幕，以及越界等错误，想拦截这个错误，自己定义ErrorWidget，里面会返回给你错误信息，你再做个友好的界面
> > dart虚拟机并不会读取你在系统网络里设置的代理，你必须在app里自行设置代理，用dio或者别的网络请求工具，把proxy塞进去
> 
> 非常感谢您的回复，我们团队想开发一款flutter的线上apm产品，因为iOS和安卓都很难采集到flutter应用的相关信息，我们应该如何入手

FlutterError.onError，你用这个拦截到所有的flutter端错误，然后看看你是直接做上传处理还是传递到原生做一次缓存，后续批量提交

**Comment by feng562925462** [comment]
> > > > npe 是什么，我想制作多种crash，使用crash采集工具进行采集，但是我只能写出几个类似js的错误（数组越界、使用未定义变量等），都无法导致程序退出
> > > 
> > > 
> > > APP的运行并不在native层，自然不会产生native的crash崩溃退出，所以你会看到红色的屏幕，以及越界等错误，想拦截这个错误，自己定义ErrorWidget，里面会返回给你错误信息，你再做个友好的界面
> > > dart虚拟机并不会读取你在系统网络里设置的代理，你必须在app里自行设置代理，用dio或者别的网络请求工具，把proxy塞进去
> > 
> > 
> > 非常感谢您的回复，我们团队想开发一款flutter的线上apm产品，因为iOS和安卓都很难采集到flutter应用的相关信息，我们应该如何入手
> 
> FlutterError.onError，你用这个拦截到所有的flutter端错误，然后看看你是直接做上传处理还是传递到原生做一次缓存，后续批量提交

不不不，我的意思是一个完整的apm产品，包括网络、web、行为、视图、崩溃或者错误等（现在我们的apm产品iOS和安卓只能采集到卡顿和webview的数据），当然也可以在原来的apm基础上添加对flutter的支持，类似于hook、runtime那种，有没有相关的资料推荐一下，麻烦啦

**Comment by ymback** [comment]
> > > > > npe 是什么，我想制作多种crash，使用crash采集工具进行采集，但是我只能写出几个类似js的错误（数组越界、使用未定义变量等），都无法导致程序退出
> > > > 
> > > > 
> > > > APP的运行并不在native层，自然不会产生native的crash崩溃退出，所以你会看到红色的屏幕，以及越界等错误，想拦截这个错误，自己定义ErrorWidget，里面会返回给你错误信息，你再做个友好的界面
> > > > dart虚拟机并不会读取你在系统网络里设置的代理，你必须在app里自行设置代理，用dio或者别的网络请求工具，把proxy塞进去
> > > 
> > > 
> > > 非常感谢您的回复，我们团队想开发一款flutter的线上apm产品，因为iOS和安卓都很难采集到flutter应用的相关信息，我们应该如何入手
> > 
> > 
> > FlutterError.onError，你用这个拦截到所有的flutter端错误，然后看看你是直接做上传处理还是传递到原生做一次缓存，后续批量提交
> 
> 不不不，我的意思是一个完整的apm产品，包括网络、web、行为、视图、崩溃或者错误等（现在我们的apm产品iOS和安卓只能采集到卡顿和webview的数据），当然也可以在原来的apm基础上添加对flutter的支持，类似于hook、runtime那种，有没有相关的资料推荐一下，麻烦啦

关于hook，我所掌握的知识告诉我，dart，你除了能知道有没有这个函数，没法进去拦截加上你的逻辑，那么你不能像java那样hook，所以别的也……
也许dart的stack_trace可以帮助你，但是我这边之前要求做事件跟踪的时候，除了继承widget或者显式调用外，无法直接在初始化的时候一次性使用代码做到跟踪你要的那些信息……

**Comment by kangwang1988** [comment]
hook->aop可以参考我写的aspectd:https://github.com/alibaba-flutter/aspectd
charles抓包，如果是dart调用http部分的内容，需要httpclient做一些设置操作，具体我需要验证下。

**Comment by feng562925462** [comment]
> dart的hook-> aop可以参考我写的aspectd：[https](https://github.com/alibaba-flutter/aspectd)：[//github.com/alibaba-flutter/aspectd](https://github.com/alibaba-flutter/aspectd)
> charles抓包，如果是直接通过dart提供的http部分的内容（不是透过channel调用），需要HttpClient的做一些设置操作，具体我需要验证下。

非常感谢您的回复，这对我很有帮助

**Comment by feng562925462** [comment]
> > > > > > npe 是什么，我想制作多种crash，使用crash采集工具进行采集，但是我只能写出几个类似js的错误（数组越界、使用未定义变量等），都无法导致程序退出
> > > > > 
> > > > > 
> > > > > APP的运行并不在native层，自然不会产生native的crash崩溃退出，所以你会看到红色的屏幕，以及越界等错误，想拦截这个错误，自己定义ErrorWidget，里面会返回给你错误信息，你再做个友好的界面
> > > > > dart虚拟机并不会读取你在系统网络里设置的代理，你必须在app里自行设置代理，用dio或者别的网络请求工具，把proxy塞进去
> > > > 
> > > > 
> > > > 非常感谢您的回复，我们团队想开发一款flutter的线上apm产品，因为iOS和安卓都很难采集到flutter应用的相关信息，我们应该如何入手
> > > 
> > > 
> > > FlutterError.onError，你用这个拦截到所有的flutter端错误，然后看看你是直接做上传处理还是传递到原生做一次缓存，后续批量提交
> > 
> > 
> > 不不不，我的意思是一个完整的apm产品，包括网络、web、行为、视图、崩溃或者错误等（现在我们的apm产品iOS和安卓只能采集到卡顿和webview的数据），当然也可以在原来的apm基础上添加对flutter的支持，类似于hook、runtime那种，有没有相关的资料推荐一下，麻烦啦
> 
> 关于hook，我所掌握的知识告诉我，dart，你除了能知道有没有这个函数，没法进去拦截加上你的逻辑，那么你不能像java那样hook，所以别的也……
> 也许dart的stack_trace可以帮助你，但是我这边之前要求做事件跟踪的时候，除了继承widget或者显式调用外，无法直接在初始化的时候一次性使用代码做到跟踪你要的那些信息……

非常感谢您的回复，我大概理解可能很难完成这个产品，我可以请教一下flutter的网络请求是基于什么来做的吗，或者说flutter的网络设计原理是什么，

**Comment by kangwang1988** [comment]
MVP code:
```dart
import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String restContent = 'Empty';

  void _requestNet() async {
    var cityCode = '101030100';
    var url = "http://t.weather.sojson.com/api/weather/city/${cityCode}";

    // Await the http get response, then decode the json-formatted responce.
    HttpClient client = new HttpClient();
    client.findProxy = (url) {
      return HttpClient.findProxyFromEnvironment(url, environment: {
        "http_proxy": '30.10.56.193:8888',
      });
    };
    client.getUrl(Uri.parse(url)).then((HttpClientRequest request) {
      return request.close();
    }).then((HttpClientResponse response) {
      if (response.statusCode == 200) {
        response.transform(utf8.decoder).listen((contents) {
          restContent = "Response: $contents.";
          setState(() {});
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Expanded(
              flex: 1,
              child: SingleChildScrollView(
                  child: Text(
                '$restContent',
                style: Theme.of(context).textTheme.display1,
              )),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _requestNet,
        tooltip: 'Request Network',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
It can be captured by charles over mac:
![image](https://user-images.githubusercontent.com/817851/65242881-c5296300-db19-11e9-83c1-56f7cdcd21c2.png)

**Comment by kangwang1988** [comment]
@feng562925462 
I think my demo has resolved the flutter traffic capture issue you want to solve, so i'm closing this issue.
If you have other problem, file a new one issue and add the from: china tag, I will have a look when available.
