### ISSUE TITLE
[web] Container width works different in web compare to ios.

### ISSUE THREAD

**Issue by Swifree** [flutter/flutter#40723]
Here is my code,  I set the width property of the container to be 100.  in ios platform the container's width is 100, which is same as expected. But in web, the code "width: 100" doesn't work. The Container will be as big as possible.
``` code
void main() {
  runApp(JustApp());
}
class JustApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          width: 100,
          color: Colors.red,
          child: Text("test"),
        ),
      ),
    );
}
```

**Comment by jonahwilliams** [comment]
Please include the output of `flutter doctor -v`

**Comment by janmoppel** [comment]
Hello @Swifree !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
