### ISSUE TITLE
Issue from website page Flutter for Web开发者

### ISSUE THREAD

**Issue by LISONG040576** [flutter/flutter#40720]
From URL: https://www.flutterchina.club/web-analogs.md

您好，我的问题是，我要开发一个web界面，这个界面上有上传文件的功能，比如图片，视频，文件等，一般来说是点击一个上传按钮，然后在桌面上弹出浮窗，可以选择你想要上传的文件，请问目前flutter web 应用支持这个功能吗？具体怎么实现呢？

(Google translate) Hello, my problem is, I want to develop a web interface, this interface has the function of uploading files, such as pictures, videos, files, etc. Generally speaking, click an upload button, then pop up the floating window on the desktop, you can Select the file you want to upload. Does the current flutter web app support this feature? How to achieve it?

**Comment by ymback** [comment]
这么问谁回答你，怪不得都是踩，学习首先要自己去查，查不到再来问，难不成要大家双手奉上代码吗？
既然问了，那么先告诉你怎么去查答案，去谷歌搜“flutter web upload file”，你就知道。
我帮你搜好了，你先去看看FileUploadInputElement，这个在dart:html里，你会发现你现在引用不到，为什么issue里有说明，换成引入universal_html的pub包，去Google搜索FileUploadInputElement怎么用，再去看看dio或者http怎么上传文件，你就知道了。

**Comment by BondarenkoStas** [comment]
Thank you @ymback!
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
