### ISSUE TITLE
firebase cloud messaging Error

### ISSUE THREAD

**Issue by uwaiphyoaung** [flutter/flutter#40727]
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':firebase_messaging:lintClassPath'.
> Could not download intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.3.0)
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/26.3.0/intellij-core-26.3.0.jar'.
      > Premature end of Content-Length delimited message body (expected: 14623712; received: 4456416
> Could not download kotlin-compiler.jar (com.android.tools.external.com-intellij:kotlin-compiler:26.3.0)
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/kotlin-compiler/26.3.0/kotlin-compiler-26.3.0.jar'.
      > Premature end of Content-Length delimited message body (expected: 21121529; received: 5504992

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17m 19s
Finished with error: Gradle task assembleDebug failed with exit code 1

firebase_messaging: ^4.0.0+2

**Comment by bobykurniawan11** [comment]
how do you fix this ?
