### ISSUE TITLE
[dashboard] track number of dartdocs missing

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4072]

**Comment by Hixie** [comment]
I can in theory just add this to the "benchmark" number that the analyzer tool puts out.

**Comment by devoncarew** [comment]
Yeah, just getting the number up there would help. We could then work to graph it separately.

/cc @pq

**Comment by pq** [comment]
👍  I'd love to be tracking this.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/4088
