### ISSUE TITLE
Firebase Message Error on Samsung

### ISSUE THREAD

**Issue by uwaiphyoaung** [flutter/flutter#40737]
Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.FirebaseMessagingService>
I/art     ( 5377): Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.FirebaseMessagingService>
I/art     ( 5377): Rejecting re-init on previously-failed class java.lang.Class<io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService>
D/AndroidRuntime( 5377): Shutting down VM
E/AndroidRuntime( 5377): FATAL EXCEPTION: main
E/AndroidRuntime( 5377): Process: com.example.asignment.assignment, PID: 5377
E/AndroidRuntime( 5377): java.lang.IllegalAccessError: io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
E/AndroidRuntime( 5377): 	at dalvik.system.DexFile.defineClassNative(Native Method)
E/AndroidRuntime( 5377): 	at dalvik.system.DexFile.defineClass(DexFile.java:226)
E/AndroidRuntime( 5377): 	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
E/AndroidRuntime( 5377): 	at dalvik.system.DexPathList.findClass(DexPathList.java:321)
E/AndroidRuntime( 5377): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
E/AndroidRuntime( 5377): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime( 5377): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime( 5377): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3639)
E/AndroidRuntime( 5377): 	at android.app.ActivityThread.access$2000(ActivityThread.java:218)
E/AndroidRuntime( 5377): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
E/AndroidRuntime( 5377): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5377): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime( 5377): 	at android.app.ActivityThread.main(ActivityThread.java:6917)
E/AndroidRuntime( 5377): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5377): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5377): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/AndroidRuntime( 5377): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
I/Process ( 5377): Sending signal. PID: 5377 SIG: 9

**Comment by dimpleagola** [comment]
Hey uwaiphyoaung,

I also get this error.
Please let me know how to solve this error.

**Comment by MarkStepp** [comment]
Any info on how it was solved?
