### ISSUE TITLE
iOS presentViewController 引起的问题

### ISSUE THREAD

**Issue by chaishuanzhu** [flutter/flutter#40739]
当我用presentViewController弹出一个原生页面的时候，flutter页面仍然可以接收点击事件。(image_picker插件有这个问题)

这与presentViewController有关。
目前Flutter engine的根控制器是FlutterViewController。
当使用presentViewController弹出B页面之后。B页面的presentingViewController为FlutterViewController。此时点击B页面，它的presentingViewController可以接收点击事件。
使用UINavigationController作为根控制器可以避免这个问题。

(Google translate) 
> When I pop up a native page with presentViewController, the flutter page can still receive click events. (image_picker plugin has this problem)
This is related to the presentViewController.
The root controller of the current Flutter engine is the FlutterViewController.
After using the presentViewController to pop up the B page. The presentationViewController of the B page is the FlutterViewController. At this point click on the B page, its presentingViewController can receive click events.
This problem can be avoided by using UINavigationController as the root controller.

```
// Returns the key window's rootViewController, if it's a FlutterViewController.
// Otherwise, returns nil.
- (FlutterViewController*)rootFlutterViewController {
  UIViewController* viewController = [UIApplication sharedApplication].keyWindow.rootViewController;
  if ([viewController isKindOfClass:[FlutterViewController class]]) {
    return (FlutterViewController*)viewController;
  }
  return nil;
}
```

**Comment by BondarenkoStas** [comment]
@chaishuanzhu If possible, can you please check how accurate is the translation? The first sentence is fine, but it's hard to understand the next steps how to exactly reproduce the problem. Do you file it as a proposal to use UINavigationController? Please explain it in more details.

**Comment by chaishuanzhu** [comment]
sorry! you can look the [simple demo](https://github.com/chaishuanzhu/flutter_app)

when you touch add button, take a photo, touch the photo , look log, print("onTap $index"); is not expect.

**Comment by chaishuanzhu** [comment]
> @chaishuanzhu If possible, can you please check how accurate is the translation? The first sentence is fine, but it's hard to understand the next steps how to exactly reproduce the problem. Do you file it as a proposal to use UINavigationController? Please explain it in more details.

sorry! you can look the [simple demo](https://github.com/chaishuanzhu/flutter_app)

when you touch add button, take a photo, touch the photo , look log, print("onTap $index"); is not expect.
