### ISSUE TITLE
StatelessElement.build 

### ISSUE THREAD

**Issue by yeras-is** [flutter/flutter#40738]
Performing hot restart...
Syncing files to device Redmi 4X...
Restarted application in 3,147ms.
I/flutter (25499): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (25499): The following assertion was thrown building MyApp(dirty):
I/flutter (25499): type 'Future<dynamic>' is not a subtype of type 'Future<List<Client>>'
I/flutter (25499): 
I/flutter (25499): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (25499): more information in this error message to help you determine and fix the underlying cause.
I/flutter (25499): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (25499):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (25499): 
I/flutter (25499): When the exception was thrown, this was the stack:
I/flutter (25499): #0      MyApp.build (package:jira/main.dart:21:31)
I/flutter (25499): #1      StatelessElement.build (package:flutter/src/widgets/framework.dart:4009:28)
I/flutter (25499): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
I/flutter (25499): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (25499): #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (25499): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (25499): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (25499): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (25499): #8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:998:16)
I/flutter (25499): #9      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:969:5)
I/flutter (25499): #10     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:915:17)
I/flutter (25499): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2328:19)
I/flutter (25499): #12     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:914:13)
I/flutter (25499): #13     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:795:7)
I/flutter (25499): #14     runApp (package:flutter/src/widgets/binding.dart:845:7)
I/flutter (25499): #15     main (package:jira/main.dart:7:16)
I/flutter (25499): #16     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229:25)
I/flutter (25499): #21     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221:5)
I/flutter (25499): #22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
I/flutter (25499): #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter (25499): (elided 4 frames from package dart:async)
I/flutter (25499): 
I/flutter (25499): ════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building MyApp(dirty):
type 'Future<dynamic>' is not a subtype of type 'Future<List<Client>>'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#0      MyApp.build (package:jira/main.dart:21:31)
#1      StatelessElement.build (package:flutter/src/widgets/framework.dart:4009:28)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#4      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348:33)
...

<MAIN.DART>
```Dart
import 'dart:async';
import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'data/DBProvider.dart';
import 'model/Client.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  List<Client> testClients = [
    Client(firstName: "Raouf", lastName: "Rahiche", blocked: false),
    Client(firstName: "Zaki", lastName: "oun", blocked: true),
    Client(firstName: "oussama", lastName: "ali", blocked: false),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Flutter SQLite")),
      body: FutureBuilder<List<Client>>(
        future: DBProvider.db.getAllClients(),
        builder: (BuildContext context, AsyncSnapshot<List<Client>> snapshot) {
          if (snapshot.hasData) {
            return ListView.builder(
              itemCount: snapshot.data.length,
              itemBuilder: (BuildContext context, int index) {
                Client item = snapshot.data[index];
                return Dismissible(
                  key: UniqueKey(),
                  background: Container(color: Colors.red,),
                  onDismissed: (direction){
                    DBProvider.db.deleteClient(item.id);
                  },
                  child: ListTile(
                    title: Text(item.lastName),
                    leading: Text(item.id.toString()),
                    trailing: Checkbox(
                      onChanged: (bool value) {
                        DBProvider.db.blockClient(item);
                        setState(){};
                      },
                      value: item.blocked,
                    ),
                  ),
                );
              },
            );
          } else {
            return Center(child: CircularProgressIndicator());
          }
        },
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () async {
          Client rnd = testClients[math.Random().nextInt(testClients.length)];
          await DBProvider.db.newClient(rnd);
          setState(){};
        },
      ),
    );
  }
}


class ClientsBloc {
  ClientsBloc() {
    getClients();
  }
  final _clientController =     StreamController<List<Client>>.broadcast();
  get clients => _clientController.stream;

  dispose() {
    _clientController.close();
  }

  getClients() async {
    _clientController.sink.add(await DBProvider.db.getAllClients());
  }
}
```
</MAIN.DART>

<DBProvider.dart>
```Dart
import 'dart:io';
import 'dart:core';

import 'package:jira/model/Client.dart';
import 'package:path_provider/path_provider.dart';
import 'package:sqflite/sqflite.dart';
import 'package:sqflite/sqlite_api.dart';
import 'package:uuid/uuid.dart';

class DBProvider {
  DBProvider._();

  static final DBProvider db = DBProvider._();

  static Database _database;

  Future<Database> get database async {
    if (_database != null) return _database;

    _database = await initDB();
    return _database;
  }

  initDB() async {
    Directory documentsDirectory = await getApplicationDocumentsDirectory();
    String path = documentsDirectory.path + "/TestDB.db";
    return await openDatabase(path, version: 1, onOpen: (db) {},
        onCreate: (Database db, int version) async {
          await db.execute("CREATE TABLE Client ("
              "id INTEGER PRIMARY KEY,"
              "first_name TEXT,"
              "last_name TEXT,"
              "blocked BIT"
              ")");
        });
  }

  newClient(Client client) async {
    final db = await database;
    return await db.insert("Client", client.toMap()); //bool
  }

  newClientSerial(Client client) async {
    final db = await database;

    var table = await db.rawQuery("SELECT MAX(id)+1 as id FROM Client");
    int id = table.first["id"];

    return await db.rawInsert(
        "INSERT Into Client(id,first_name,last_name,blocked) "
            " VALUES(?,?,?,?)",
        [id, client.firstName, client.lastName, client.blocked]);
  }

  getClientBuId(Uuid id) async {
    final db = await database;
    var res = await db.query("Client", where: "id = ?", whereArgs: [id]);
    return res.isNotEmpty ? Client.fromMap(res.first) : Null;
  }

  getAllClients() async {
    final db = await database;
    var res = await db.query("Client");
    return res.isNotEmpty ?
    res.map((c) => Client.fromMap(c)).toList() :
    [];
  }

  getAllBlockedClients() async {
    final db = await database;
    var res = await db.rawQuery("SELECT * FROM Client WHERE blocked=1");
    return res.isNotEmpty ? res.map((c) => Client.fromMap(c)).toList() : [];
  }

  updateClient(Client client) async {
    final db = await database;
    return await db.update("Client", client.toMap(),
        where: "id = ?", whereArgs: [client.id]);
  }

  blockClient(Client client) async {
    final db = await database;
    client.blocked = true;
    return await db.update("UPDATE Client SET blocked=1", client.toMap(),
        where: "id = ?", whereArgs: [client.id]);
  }

  unblockClient(Client client) async {
    final db = await database;
    client.blocked = false;
    return await db.update("UPDATE Client SET blocked=1", client.toMap(),
        where: "id = ?", whereArgs: [client.id]);
  }

  deleteClient(Uuid id) async {
    final db = await database;
    return db.delete("Client", where: "id = ?", whereArgs: [id]);
  }

  deleteAllClient(Uuid id) async {
    final db = await database;
    return db.rawDelete("DELETE * from Client");
  }
}
```
</DBProvider.dart>

<CLIENT.DART>
```Dart
// To parse this JSON data, do
//
//     final welcome = welcomeFromJson(jsonString);

import 'dart:convert';

import 'package:uuid/uuid.dart';

Client welcomeFromJson(String str) => Client.fromMap(json.decode(str));

String welcomeToJson(Client data) => json.encode(data.toMap());

class Client {
  Uuid id;
  String firstName;
  String lastName;
  bool blocked;

  Client({
    this.id,
    this.firstName,
    this.lastName,
    this.blocked,
  });

  factory Client.fromMap(Map<String, dynamic> json) => Client(
    id: json["id"] == null ? null : json["id"],
    firstName: json["firstName"] == null ? null : json["firstName"],
    lastName: json["lastName"] == null ? null : json["lastName"],
    blocked: json["blocked"] == null ? null : json["blocked"],
  );

  Map<String, dynamic> toMap() => {
    "id": id == null ? null : id,
    "firstName": firstName == null ? null : firstName,
    "lastName": lastName == null ? null : lastName,
    "blocked": blocked == null ? null : blocked,
  };

}
```
</CLIENT.DART>

```
pubspec.yaml 
    dependencies:
      flutter:
            sdk: flutter
      english_words: ^3.1.0
      sqflite: ^1.1.6+4
      path_provider: ^1.3.0
      uuid: 2.0.1
```

**Comment by escamoteur** [comment]
Your DBProvider's methods all have not a return type declared though the return type of an async function is just a Future.
Add correct return types and it should be solved.
Please consider to ask this type of questions on Stackoverflow the next time.

**Comment by yeras-is** [comment]
Thanks for your time.

ср, 18 сент. 2019 г. в 16:17, escamoteur <notifications@github.com>:
