### ISSUE TITLE
[Future already completed] run ‘flutter doctor ’failed

### ISSUE THREAD

**Issue by bianxiang** [flutter/flutter#40734]
```
bianxiangdeMacBook-Pro-2:swapwallet-app bianxiang$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.7.3, on Mac OS X 10.14.3 18D42, locale zh-Hans-CN)
⣽Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:39:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:521:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:874:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:881:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:902:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
bianxiangdeMacBook-Pro-2:swapwallet-app bianxiang$ 
```

**Comment by bianxiang** [comment]
Bad state: Future already completed

**Comment by BondarenkoStas** [comment]
This is likely a firewall issue
If you are in China see https://flutter.io/community/china
If you are using a self-signed certificate see https://github.com/flutter/flutter/issues/15014

I'm not sure if it's the case, but I saw such comment on this "Future already completed" error. Please let me know if that won't be helpful.

**Comment by bianxiang** [comment]
It do not work,I am using VPN,can connect to google
![image](https://user-images.githubusercontent.com/16380379/65415610-ad5b2300-de28-11e9-85c2-a91db6230df0.png)

**Comment by iapicca** [comment]
Hi @bianxiang 
does this proposed [solution ](https://github.com/flutter/flutter/issues/14866#issuecomment-549282198)works for you?
thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
