### ISSUE TITLE
C Native Libraries Features Like SQLite

### ISSUE THREAD

**Issue by BaderEddineOuaich** [flutter/flutter#40744]
Now <strong>Dart 2.5</strong> Supports <strong>ffi</strong> 😃 🎉!
is there a possibility that we can call native SQLite library using C code ?
Will be just awesome if we could use native features as SQLite by calling C code or some Flutter/Dart class that uses ffi and takes care of it.
Thank you ❤️

**Comment by escamoteur** [comment]
Maybe this helps?
https://github.com/dart-lang/sdk/tree/master/samples/ffi/sqlite

**Comment by escamoteur** [comment]
@mit-mit any aditional thoughts?

**Comment by mit-mit** [comment]
Should be possible to create a wrapper using `dart:ffi`. The link above is for demonstration only; the Dart team doesn't plan on creating a full wrapper. If someone in the community wanted to do that, that would be fantastic.

**Comment by sroddy** [comment]
some progress has been done here
https://github.com/simolus3/moor/issues/76

**Comment by escamoteur** [comment]
As there isn't a plan to implement such a package from the Dart/Flutter Team I close this issue.
