### ISSUE TITLE
flutter run --resident interactive commands fail in emacs shell

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4074]
```
cd examples/flutter_gallery
flutter run --resident
Type "h" or F1 for help, "r" or F5 to restart the app, and "q", F10, or ctrl-c to quit.
h


```

Many interactive command-line programs work fine in an emacs shell but  `flutter run` doesn't appear too.

Just FTR, the interactive commands do work (in a sense) from a terminal window but:

```
Re-starting application...
Error restarting app: JSON-RPC error -32601 (method not found): Method not found
```

**Comment by devoncarew** [comment]
Yup, this guy:

> Re-starting application...
Error restarting app: JSON-RPC error -32601 (method not found): Method not found

is available, but not fully plumbed through yet. Re-start does work for android devices and emulators.

When you say fail, what do you see? No output until the process terminates? Or it not responding to the keyboard commands?

**Comment by Hixie** [comment]
I'm guessing what's going on is that we're reading the stdin pipe in a way that doesn't work with line-orientated buffering.

**Comment by Hixie** [comment]
This works now IIRC.
