### ISSUE TITLE
if download fails in `update_dart_sdk.sh` unzip fails

### ISSUE THREAD

**Issue by biij5698** [flutter/flutter#40741]
My Flutter current version is:1.10.4-pre.54,when i "flutter doctor",then:
flutter doctor
Downloading Dart SDK from Flutter engine 36be89da497b14e0aa2c2e03897b46f9eb1e655f...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     51      0 --:--:-- --:--:-- --:--:--    51
[/home/adminpc/pro/flutter/bin/cache/dart-sdk-linux-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/adminpc/pro/flutter/bin/cache/dart-sdk-linux-x64.zip or
        /home/adminpc/pro/flutter/bin/cache/dart-sdk-linux-x64.zip.zip, and cannot find /home/adminpc/pro/flutter/bin/cache/dart-sdk-linux-x64.zip.ZIP, period.

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md

**Comment by biij5698** [comment]
My Linux version is:
uname -a:
Linux adminpc 4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018 x86_64 GNU/Linux
uname -r:
4.15.0-29deepin-generic

**Comment by biij5698** [comment]
Befor the "flutter doctor" command,I executed the "flutter upgrade" command,then the error occured.

**Comment by biij5698** [comment]
When i change the "PUB_HOSTED_URL" and "FLUTTER_STORAGE_BASE_URL" to:
 export PUB_HOSTED_URL=https://pub.flutter-io.cn
 export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
Then,it can be worked,but some times it can not be worked.

**Comment by christopherfujino** [comment]
This has been fixed with https://github.com/flutter/flutter/commit/bdc06194fb21c4342f121809714497b1c7be42f3, where we exit if curl fails.
