### ISSUE TITLE
how to handle firebase cloud messaging (backgroud) in Flutter.

### ISSUE THREAD

**Issue by uwaiphyoaung** [flutter/flutter#40747]
V/ActivityThread(15973): updateVisibility : ActivityRecord{bb2b184 token=android.os.BinderProxy@ccc9b9a {com.example.asignment.assignment/com.example.asignment.assignment.MainActivity}} show : false
E/FlutterFcmService(15973): Fatal: failed to find callback

This is Application.java
public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        FlutterFirebaseMessagingService.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry pluginRegistry) {
        GeneratedPluginRegistrant.registerWith(pluginRegistry);
    }
}

**Comment by uwaiphyoaung** [comment]
manifest file =>

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.asignment.assignment">

    
    <application
        android:name="com.example.asignment.assignment.Application"
        android:label="assignment"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
    </application>
</manifest>

**Comment by escamoteur** [comment]
please file this issue here https://github.com/FirebaseExtended/flutterfire
as its not a Flutter issue.
Also please give it another name there like **Java Exception: E/FlutterFcmService(15973): Fatal: failed to find callback**
Also add which version of the plugin you are using.
Good luck.
