### ISSUE TITLE
Update style on calculator example and merge into gallery

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4075]

**Comment by sethladd** [comment]
Looks like the calculator has been merged into gallery?

**Comment by Hixie** [comment]
I did merge it in. I didn't update the style. It should probably be tweaked if we keep it.

**Comment by sethladd** [comment]
Do we have specs/mocks for the new styles?

**Comment by Hixie** [comment]
No, there's no mocks for any of this. We could copy Android's colours, it has a very similar calculator.

**Comment by HansMuller** [comment]
I'll fix up the colors like the Android version.

**Comment by HansMuller** [comment]
Fixed in https://github.com/flutter/flutter/pull/4363
