### ISSUE TITLE
Install a bug trucker: I need to edit FlutterApplication class but I do not find it

### ISSUE THREAD

**Issue by GiacomoK** [flutter/flutter#40753]
Hi,
I want to install a bug trucker and to do that I need to add a line code to my Application class.

I saw that the application class for a flutter project is `io.flutter.app.FlutterApplication`. I am looking for it but I am not able to find the file.
Where is it?

**Comment by escamoteur** [comment]
Hi, this seems to be a question for stackoverflow.
Please post it there.
