### ISSUE TITLE
NoSuchMethodError: The method 'split' was called on null

### ISSUE THREAD

**Issue by biij5698** [flutter/flutter#40754]
windows10:
flutter.bat upgrade
Upgrading Flutter from D:\pro\flutter...
Updating 2f3515de3..abfad9cc4
 305 files changed, 5485 insertions(+), 3467 deletions(-)

Upgrading engine...
Downloading Android Maven dependencies...                          14.7s

Flutter 1.10.4-pre.55 • channel master • https://github.com/flutter/flutter.git
Framework • revision abfad9cc49 (9 hours ago) • 2019-09-18 00:14:41 -0400
Engine • revision 36be89da49
Tools • Dart 2.6.0 (build 2.6.0-dev.1.0 f22f62c85d)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.4-pre.55, on Microsoft Windows [Version 10.0.17763.194], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[☠] Visual Studio - develop for Windows (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X NoSuchMethodError: The method 'split' was called on null.
      Receiver: null
      Tried calling: split(".")
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by biij5698** [comment]
flutter version is 1.10.4 pre.55

**Comment by escamoteur** [comment]
This is a double of https://github.com/flutter/flutter/issues/40748
