### ISSUE TITLE
is there any ways to check if app is run on web and not a smartphone ?

### ISSUE THREAD

**Issue by Hassan-Fa** [flutter/flutter#40768]
found nothing about this , is it possible ?
or any reliable workarounds ?
♥️

**Comment by KirolousNashaat** [comment]
You can use Platform.isAndroid , Platform.isIOS

**Comment by BondarenkoStas** [comment]
@Hassan-Fa You can check if you are on the web by:
```
import 'package:flutter/foundation.dart';

if (kIsWeb) {

} else {

}
```
