### ISSUE TITLE
当我滑动Gridview的时候，遇到了一些掉帧问题。When I scroll the gridview in my app,the frame drop is serious

### ISSUE THREAD

**Issue by yuxiaoyang88** [flutter/flutter#40760]
Hi
我写的一个Gridview出现了掉帧问题。
I wrote a Gridview that has dropped frames.
我觉得这个问题与使用了ClipRRect有关。
I think this problem is related to the use of ClipRRect.
希望大神们能够帮我看一下。
I hope the gurus can help me look at it.
我不确定是组件的使用错误，还是有些bug在里面。
I am not sure if the component is being used incorrectly or if there are some bugs in it.
我把所有代码放在这个仓库里了。
I put all the code in this repository.

https://github.com/yuxiaoyang88/A_Flutter_Example.git

墙裂感谢。
Many thanks.
```
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.356], locale zh-CN)
    • Flutter version 1.9.1+hotfix.2 at D:\Java\Flutter
    • Framework revision 2d2a1ffec9 (12 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\Program\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\Program\SDK
    • Java binary at: E:\Program\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at E:\Program\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)                                       
[!] IntelliJ IDEA Ultimate Edition (version 2019.2)                                                                         • IntelliJ at D:\IDE\JetBrains\IntelliJ IDEA                                                                            X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.                                                     • For information about installing plugins, see                                                                           https://flutter.dev/intellij-setup/#installing-the-plugins                                                        
[√] Connected device (1 available)                                                                                          • MI 8 • 40ccfd8c • android-arm64 • Android 9 (API 28) 
```

**Comment by chinmaygarde** [comment]
I went over the application and it looks like multiple images are being used to simulate a video(?). Not sure because I cannot seem to access the images at the URL (possible country restrictions maybe). Would it be possible to prepare a reduced test case with all the image in the application bundle packaged as assets? Beyond that, it may be that there are too many images that need decompression for display. Hard to say because I cannot get this application to function.

**Comment by yuxiaoyang88** [comment]
我已经把修改后的代码放入。
I have put my code into this repo.
https://github.com/yuxiaoyang88/A_Flutter_Example_Pro
我用小米10和红米K30Pro测试了一下。
I tested it with Mi10 and RedmiK30Pro.
掉帧的问题有些减轻，红米K30Pro几乎没有感觉掉帧问题。
The problem of frame dropping is alleviated,hardly feel frame dropping in RedmiK30Pro.
我第一次提交问题时，觉得这个问题与使用了ClipRRect有关，现在不知道还算不算做问题。
When I first post the question,I think this problem is related to the use of ClipRRect,now I don't know if it's a problem.
而且觉得，比我第一次提交问题时，掉帧问题有改观。
And I think the frame dropping problem has changed since I first submitted it.
我也觉得很有可能，确实是一次性加载过多的图片，造成了这样的结果。。。
It may be that there are too many images that need decompression for display.

**Comment by darshankawar** [comment]
@yuxiaoyang88 
Is this still a valid issue using latest Flutter version ?
