### ISSUE TITLE
Missing Visual Studio components

### ISSUE THREAD

**Issue by angelhdz** [flutter/flutter#40777]
**flutter doctor** complains that my Visual Studio is missing these components:

-         MSBuild
-         MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.21)
-         Windows 10 SDK (10.0.17763.0)

I installed MSBuild, MSVC v142 v14.21, but the issue is with Windows 10 SDK. I install the **10.0.17763.0**, manually and from Visual Studio, but version **10.0.17763.132** gets installed instead.

```
```
![image](https://user-images.githubusercontent.com/10191085/65177634-1146ab80-da25-11e9-9900-4d9524348f53.png)

**Comment by stuartmorgan** [comment]
This is likely a duplicate of #40335. Does installing the latest `MSVC v142 - VS 2019 C++ x64/x86 build tools` version instead of `14.21` resolve the issue?

**Comment by angelhdz** [comment]
> This is likely a duplicate of #40335. Does installing the latest `MSVC v142 - VS 2019 C++ x64/x86 build tools` version instead of `14.21` resolve the issue?

Thanks for replying @stuartmorgan. I'm installing version v14.22 to see if it solves it, but it would be a bug that flutter SDK asks for v14.21 when in reality it needs v14.22...
Will update this as far as the installation completes.

**Comment by stuartmorgan** [comment]
> it would be a bug that flutter SDK asks for v14.21 when in reality it needs v14.22...

Yes: bug #40335.

**Comment by angelhdz** [comment]
### Solved

**Comment by ThinkDigitalSoftware** [comment]
I have this issue with the latest auto-selected by vscode. I couldn't catch the tooltip without it fading, but if you look closely, you'll see that it's the 14.22 version that's already installed. I've also restarted the computer just before taking this screenshot. I'm getting the same error as the OP
![Annotation 2019-09-22 175148](https://user-images.githubusercontent.com/23037821/65397068-ad442000-dd61-11e9-9de0-bee540940ce0.png)

**Comment by stuartmorgan** [comment]
@ThinkDigitalSoftware  Please follow #40335, which this is a duplicate of, for updates. The fix for it hasn't landed yet.

**Comment by ThinkDigitalSoftware** [comment]
Much appreciated
