### ISSUE TITLE
DropdownMenuItems are fixed height

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#40773]
Internal: b/140830819

The height of dropdown menu items is fixed at 48. This is big enough to show one or two lines of text using the default font or one line of text with the default font and the maximum text scale factor on Android devices.

Menu items whose intrinsic heights are > 48 do not fit. This example demos the limitation:
https://gist.github.com/HansMuller/7df11ac474609a759b616d8258443f29

**Comment by HansMuller** [comment]
I have a fix for this. Writing tests today.

**Comment by Hixie** [comment]
(guessed at milestone, feel free to update)

**Comment by rajeshzmoke** [comment]
@HansMuller  @shihaohong any idea when this will be available in the "stable" channel
