### ISSUE TITLE
examples/calculator hits 9fps in gpu_thread on my nexus 5

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4077]
Not sure what it's doing that's so slow.  FYI @Hixie @MitchRudominer

**Comment by eseidelGoogle** [comment]
You can see this with the "Performance Overlay" toggle from Atom.

**Comment by MitchRudominer** [comment]
Can you tell me what expressions you entered?

**Comment by MitchRudominer** [comment]
Never mind. I see it. It has nothing to do with what expression is entered. I guess it is unrelated to the calculator logic and is somehow caused by the manner in which I have used the widgets. Could it be related to the fact that I am passing the state object from the stateful widget top-level widget into the stateless component widgets?

**Comment by MitchRudominer** [comment]
When I comment out the entire body of the calculator from my build() method and leave only the Scaffold with an AppBar the Performance overly still shows me 6.3 frames per second.

**Comment by MitchRudominer** [comment]
This is on an old Nexus 5.

**Comment by Hixie** [comment]
cc @HansMuller in case it's the appbar.

**Comment by HansMuller** [comment]
I'm testing on a Nexus 5X.

If I comment out the body of the calculator, I see about 50-60FPS, with all the work being done in the GPU.
```
    return new Scaffold(
      appBar: new AppBar(title: new Text('Calculator')),
      body: new RaisedButton(child: new Text("DEBUG"), onPressed: () { setState((){}); })
    );
```

![perf](https://cloud.githubusercontent.com/assets/1377460/15443957/0f5695d0-1ea1-11e6-8414-7682128c9fee.png)

**Comment by abarth** [comment]
We made this go fast by removing the shadows.  There's a bug on file for the shadows being slow: https://github.com/flutter/flutter/issues/4367
