### ISSUE TITLE
Quantify the impact of iOS 13 on the Flutter package size

### ISSUE THREAD

**Issue by xster** [flutter/flutter#40785]
Apple's iOS 13 marketing references app size decreases

https://www.slashgear.com/ios-13-is-obsessed-with-iphone-speed-and-app-size-03578962/

It could hypothetically be related to the encrypting/compressing ordering. 

Test and quantify its impact with Flutter package download size.

**Comment by liyuqian** [comment]
@goderbauer : while our current device lab hello_world size benchmark on iOS only executes some command like the one in https://flutter.dev/docs/perf/app-size#ios, I wonder if it's possible for us to setup a CI test that will go through the whole Apple signing/encrypting/compressing process, and get a final IPA size for either `hello_world` or `flutter_gallery` size?

**Comment by goderbauer** [comment]
I don't know if that's possible, maybe @digiter does?

For what it's worth, I was unable to see any size decrease with iOS 13 in Flutter apps.

**Comment by digiter** [comment]
If the whole process can be done in pure command line, then that's possible with the devicelab.

**Comment by xster** [comment]
@goderbauer did you mean reported size from the App Store? i.e. our hypothesis about iOS 13's marketed app size decrease / reshuffled compress/encrypt order did not take place and didn't affect Flutter apps?

**Comment by goderbauer** [comment]
The size for Flutter apps reported on App Store connect didn't change with iOS 13 when I was looking at it a couple of weeks ago.

Since we have no way of quantifying this, I am going to close this.
