### ISSUE TITLE
Package import fails for new dependency ("Target of URI doesn't exist:")

### ISSUE THREAD

**Issue by sowens-csd** [flutter/flutter#40788]
I've resolved this issue but I think the way it was resolved might help identify a cause even though I can't reproduce it. The short version is that I wonder if creating a new plugin using a flutter template can _fix_ a broken dependency resolution. This is related to #30845 and #1642. 

Here's what happened while working on a plugin package example project using VSCode. 

1. Added a new dependency to the permission_handler package to **pubspec.yaml** in the plugin example app. 
2. Tried to import permission_handler but it could not be found. 
3. Ran `flutter pub get` with no errors.
4. Import still not working, tried `flutter analyze` and it showed the same error "**Target of URI doesn't exist**"
5. Checked another project which already had the same dependency and import statement, everything working there
6. Tried adding the same dependency and import to a different plugin, that worked fine. 
7. Ran `flutter pub deps` in the non-working project and it showed the dependency as expected
8. Restarted the IDE a bunch of times. Rebuilt the flutter package cache using `flutter pub cache repair`
9. Removed the dependency and the import statement, ran `flutter clean`, removed the **.packages** and **.flutter-plugins** files in the non-working example directory. Closed the IDE and restarted. Everything at this point was clean and error free without the dependency and import statement.   
10. Added the dependency back, rebuilt the project, tried to add the import statement. It still cannot resolve the URI, the dependency continues to work properly in other projects. 

Here's the dependency and import statement. 

```
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  permission_handler: ^3.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  my_plugin:
    path: ../
```

```
import 'package:permission_handler/permission_handler.dart';
```

All of that to say I tried everything I can think of to ensure that I'd forced a completely clean build of the project and it failed. I learned a lot about the flutter package cache locations and other trivia over > 2 hours of trying to beat this into submission. Since everything else had failed I decided to create a new plugin and copy my code from the non-working plugin to a working version as a way to work around the dependency problem. 

```
flutter create --template=plugin -i swift -a kotlin new_clean_plugin
```

After creating the new plugin I decided to try the dependency / import one last time in the old non-working plugin before copying the code to the newly created plugin. And it worked perfectly, no problem with the import. From there on it worked reliably with no problems in the previously non-working plugin project. 

That leads to me to wonder if something about creating the new plugin invalidated a cache / restarted a process in Flutter that made it start working for that project. Feel free to close this issue unless it is useful to the team. My current problem is resolved. 

`[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-CA)`

**Comment by frank06** [comment]
Not sure I had the exact same problem but it's annoying as hell.

Developing a library, I got the dreaded `Target of URI doesn't exist` on the example app. It took me hours to figure out but the solution is to place ALL dependencies on the library (even in `dev_dependencies` and NOT on the example app.

**Comment by jonahwilliams** [comment]
This problems seem to be specific to dependencies in the example app folder, correct?

**Comment by frank06** [comment]
@jonahwilliams Correct. Even starting a new project scaffold from scratch and copying over the source files. Tried this with a few different Flutter versions. For now I moved the example app outside the project

**Comment by jonahwilliams** [comment]
Are you running `flutter packages get`/`flutter pub get` in the root directory or in the example directory? If the former, I expect that it will only fetch packages for the plugin

**Comment by chimon2000** [comment]
I have the same issue with my example project.  Running `flutter pub get` does not resolve it regardlesss of whether it's run in the *root* directory or the *example* directory.

**Comment by pratikpwr** [comment]
restart the IDE. this solve Target of URI doesn't exist: 'package:dartz/dartz.dart'.  the issue for me.

**Comment by sowens-csd** [comment]
I'm going to do my bit to help with the Flutter issue sprawl by closing this. It was informational only in any event and people can still find it if it's closed.
