### ISSUE TITLE
[google_maps_flutter] - Markers on iOS don't show InfoWindow

### ISSUE THREAD

**Issue by evertonfoz** [flutter/flutter#40780]
Hello, how are you? I have the map displayed on the device, but when adding a Marker, its `InfoWindow` is not displayed. Can anyone help me?

**Comment by janmoppel** [comment]
Hello @evertonfoz !

Thank you for posting an issue.
Can you please provide an output of the `flutter doctor -v` command? 
Also, it would be very helpful if you could create a self-contained repository, so that your issue could be easily reproduced.

Thank you.

**Comment by janmoppel** [comment]
Hello @evertonfoz !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
