### ISSUE TITLE
flutter create should include a test

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4080]
There are a bunch of steps to set up your dev_dependencies and write the small amount of test boilerplate.  I think we should consider including an example test.  @Hixie @devoncarew

**Comment by aghassemi** [comment]
:+1:  Maybe both a widget test and a driver test.

**Comment by aghassemi** [comment]
Just realized driver tests can be generated by doing `flutter create --with-driver-test <output_dir>`

**Comment by Hixie** [comment]
This is done now.
