### ISSUE TITLE
[cleanup] Provide a single way for detecting if a project is using AndroidX

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#40800]
Depending on the project type, AndroidX is determined by reading `pubspec.yaml` or `gradle.properties`.

**Comment by escamoteur** [comment]
Maybe the Team understands what you mean, but could you elaborate what exactly the problem is?

**Comment by blasten** [comment]
The problem is that there are two ways of detecting if a project is using AndroidX, but the two ways belong to two different abstraction layers:
* `pubspec.yaml` belongs to `FlutterManifest`.
* `gradle.properties` belongs to `AndroidProject`.

An `AndroidProject` instance doesn't know anything about `FlutterManifest`.

**Comment by escamoteur** [comment]
You mean so that the App can access this information at runtime?

**Comment by blasten** [comment]
> You mean so that the App can access this information at runtime?

The tool. This information is not exposed to the app at runtime.

**Comment by blasten** [comment]
This is obsolete now.
