### ISSUE TITLE
backgroundColor in `Text` widgets not shown correctly in arabic texts(rtl) when rendering a space character

### ISSUE THREAD

**Issue by adals** [flutter/flutter#40803]
<img width="965" alt="Screen Shot 2019-09-19 at 4 38 06 AM" src="https://user-images.githubusercontent.com/169691/65206859-9a4afa80-da98-11e9-8285-acdb22157937.png">
<img width="988" alt="Screen Shot 2019-09-19 at 8 25 15 AM" src="https://user-images.githubusercontent.com/169691/65215726-31bf4600-dab7-11e9-8314-38f85647c1ac.png">

**Comment by janmoppel** [comment]
Hello @adals !

Thank you for posting an issue here.
Can you please also provide additional information such as an output of the `flutter doctor -v` command?

Thank you.

**Comment by adals** [comment]
$ flutter doctor -v
[✓] Flutter (Channel dev, v1.10.3, on Mac OS X 10.14.6 18G95, locale en-SA)
    • Flutter version 1.10.3 at /Users/aaa/flutter
    • Framework revision 2f3515de31 (5 days ago), 2019-09-13 17:52:41 -0400
    • Engine revision 7d8c6d9c1a
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 a554c8be6b)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/aaa/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by escamoteur** [comment]
Could you tell us what you made different between the two screenshots above?

**Comment by adals** [comment]
> Could you tell us what you made different between the two screenshots above?

nothing I just wanted to see if there is any different "rendering" between ios and android

**Comment by escamoteur** [comment]
Sorry, I missed that one was iOS, thanks for clarifying

**Comment by adals** [comment]
no problem

<img width="1021" alt="Screen Shot 2019-09-19 at 2 04 58 PM" src="https://user-images.githubusercontent.com/169691/65238936-85955380-dae6-11e9-95c4-d3889b587ea9.png">

**Comment by escamoteur** [comment]
Thanks a lot! Could you now just paste your code here as code snippet so that the flutter team can copy it out,

**Comment by adals** [comment]
```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Container(
//        padding:EdgeInsets.only(top:35.0),
          child: SafeArea(
            child: Column(
              children: <Widget>[
                Text(
                  "انا اريد",
                  style: TextStyle(
                      backgroundColor: Colors.blue,
                      fontStyle: FontStyle.normal,
                      decoration: TextDecoration.none,
                      color: Colors.amber),
                ),
                Text(
                  "ich wünche ",
                  style: TextStyle(
                      backgroundColor: Colors.red,
                      fontStyle: FontStyle.normal,
                      decoration: TextDecoration.none,
                      color: Colors.green),
                ),
                Text(
                  "I Want ",
                  style: TextStyle(
                      backgroundColor: Colors.brown,
                      fontStyle: FontStyle.normal,
                      decoration: TextDecoration.none,
                      color: Colors.lightGreenAccent),
                ),
              ],
            ),
          ),
        ),
      ),
    );
```

**Comment by OsamaAbbas** [comment]
A workaround fot this issue (until it's fixed): use a custom Arabic font. Any Arabic font (other that the default font in Android) should work fine.

**Comment by adals** [comment]
@OsamaAbbas yes tested and it works with 'Cairo' fonts
<img width="410" alt="Screen Shot 2019-09-19 at 11 50 56 PM" src="https://user-images.githubusercontent.com/169691/65280117-5f000880-db38-11e9-83da-716a96ac96c7.png">

**Comment by GaryQian** [comment]
This is most likely due to different fonts being on iOS and android. Using a custom font guarantees the same font is being used on all platforms.

If there are no further questions comments, I will close this :)

**Comment by OsamaAbbas** [comment]
> This is most likely due to different fonts being on iOS and android. Using a custom font guarantees the same font is being used on all platforms.
> 
> If there are no further questions comments, I will close this :)

While I don't know for sure, I think it's because the font engine (when dealing with some fonts that may have different height settings for glyphs) considers the space charachter a latin charachter, so it gets the height of latin charachters instead of the surrounding Arabic (or Hebrew, or RTL in general) charachters. It could also be related to the other long standing issues [39755 and 44449] of mixed charachters in the case of justified text.
