### ISSUE TITLE
"Operation not supported" when run "flutter doctor" after installed it on Mac

### ISSUE THREAD

**Issue by CrisChr** [flutter/flutter#40818]
## Steps to Reproduce

1. Download the latest Flutter bundle and unzip into desired location
2. Add the flutter tool to PATH and update the PATH
3. run "flutter doctor"

## Logs

![image](https://user-images.githubusercontent.com/38416380/65214054-03ebf880-dadb-11e9-9352-0ddbe04bd894.png)

![image](https://user-images.githubusercontent.com/38416380/65214076-1e25d680-dadb-11e9-991b-6270b3f95793.png)

**OS:** Mac Mojave 10.14.6
**Flutter verion:** 
![image](https://user-images.githubusercontent.com/38416380/65214253-e8352200-dadb-11e9-800a-41fa312459fc.png)

I followed this guide: https://flutter.dev/docs/get-started/install/macos

Anybody knows the reason?

Thanks

**Comment by CrisChr** [comment]
When I run `which flutter`, the output path is `/Volumes/Whatever/flutter/bin/flutter`. Is that correct?
![image](https://user-images.githubusercontent.com/38416380/65216014-1e75a000-dae2-11e9-9098-fa2046b91712.png)

**Comment by pouledodue** [comment]
my path is like yours `/something/flutter/bin/flutter`

**Comment by janmoppel** [comment]
Hello @CrisChr !

Thank you for posting an issue.
Have you tried to install Flutter into other folder? Also, can you please check, what are your `/Volumes` folder permissions (run `ls -l /` command)?

Thank you.

**Comment by CrisChr** [comment]
Thanks @janmoppel 
I re-installed Flutter into `~/flutter` folder and it worked
