### ISSUE TITLE
Type check difference in release mode and debug more

### ISSUE THREAD

**Issue by KylinGu** [flutter/flutter#40813]
#40180  

## 1. Steps to Reproduce

Please fix this bug about type check exception, it should be throw exception or pass all test, but not no any hint log in release mode.

1. running the code below.
```
double px(number){
    getTypeName(number);
    return number;
  }

  getTypeName(obj) {
    if(obj is int){
      print("int");
    }

    if(obj is num){
      print("num");
    }

    if(obj is double){
      print("double");
    }
  }
```

## 2. Logs
1. Running in release mode
you will get result .
```
I/flutter (22730): int
I/flutter (22730): num
```
**No Exception, No hint. This is leading a fatal issue that blank screen in our app and we have no any info to debug in release mode.**
2. Running in debug mode
you will get Exception.
`type 'int' is not a subtype of type 'double'`

Maybe someone would say you could avoid this issue in debug, but actually, in debug mode, we would not running the code.

3. Runnning in dart pad.
```
int
num
double
```
**There's no exception, and it is both int and num type.**

## 3. flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G87, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.7)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.36.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

```

**Comment by escamoteur** [comment]
I just tried myself in DartPad and as you said no error.
Please report this error at https://github.com/dart-lang/sdk/issues
