### ISSUE TITLE
flutter run -d server fails when Chrome not present

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#40814]
I'm in the process of attempting to run Flutter tooling alongside the VS Code in the Cloud product [code-server](https://github.com/cdr/code-server). I can install the `flutter` tooling, change to master, upgrade, and set the config to enable web, but then attempting to run just the server fails.

```bash
$ flutter doctor --verbose
[✓] Flutter (Channel master, v1.10.4-pre.72, on Linux, locale en_US.UTF-8)
    • Flutter version 1.10.4-pre.72 at /home/coder/flutter
    • Framework revision 4c724b9b7d (2 hours ago), 2019-09-18 21:48:41 -0400
    • Engine revision 7f7250f476
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 cb80ea7ba9)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✗] Chrome - develop for the web (Cannot find chrome executable at google-chrome)
    ! CHROME_EXECUTABLE not set

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • unknown (unsupported)
    • Server • web    • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
$ flutter config
Configure Flutter settings.

[Elided help output - bjm]

Settings:
  enable-web: true

Analytics reporting is currently enabled.
$ flutter run -d server
Unable to locate a development device; please run 'flutter doctor' for information about installing additional components.
```

**Comment by jonahwilliams** [comment]
The device id is called `web` - perhaps I should change the name from Server to Web to make it more apparent?

**Comment by domesticmouse** [comment]
Hmm, my command line disagrees with you.

```bash
$ flutter run -d web
Unable to locate a development device; please run 'flutter doctor' for information about installing
additional components.
```

**Comment by jonahwilliams** [comment]
Oh, I see the issue:

>   • Chrome • chrome • web-javascript • unknown (unsupported)

You need @DanTup 's fix at https://github.com/flutter/flutter/pull/40757

**Comment by DanTup** [comment]
Yeah, this is the same issue I saw on GitPod - the web workflow is disabled when Chrome is not available. I'll try and figure out the test failures on that PR this morning so I can get it landed.

**Comment by bprayush** [comment]
Similar issue in Manjaro Linux platform. Chrome defaults to google-chrome-stable, the SDK is unable to find google chrome executable.

**Comment by DanTup** [comment]
@bparrishMines I think  your issue is a little different - @domesticmouse was passing `-d server` which is to use the headless server (doesn't launch a browser). This isn't really what you want, as it disables significant functionality. I think you should raise a new issue if Chrome's executable isn't named `chrome` on your platform.

**Comment by bprayush** [comment]
> @bprayush I think your issue is a little different - @domesticmouse was passing `-d server` which is to use the headless server (doesn't launch a browser). This isn't really what you want, as it disables significant functionality. I think you should raise a new issue if Chrome's executable isn't named `chrome` on your platform.

Okay.

**Comment by felipsoarez** [comment]
> Similar issue in Manjaro Linux platform. Chrome defaults to google-chrome-stable, the SDK is unable to find google chrome executable.

I had this same problem in manjaro, if you installed by AUR run the following command

`$ export CHROME_EXECUTABLE=/opt/google/chrome/chrome`

and then

`$ flutter doctor `

Result: 

<pre>(base) <font color="#2CB02C"><b>[felipe@datacrypto-analytics</b></font><font color="#FFFFFF"><b> ~</b></font><font color="#2CB02C"><b>]$</b></font> flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
<font color="#5FEB5F">[✓]</font> Flutter (Channel beta, 1.25.0-8.3.pre, on Linux, locale pt_BR.utf8)
<font color="#5FEB5F">[✓]</font> Android toolchain - develop for Android devices (Android SDK version 30.0.3)
<font color="#5FEB5F">[✓]</font> Chrome - develop for the web
<font color="#AA5500">[!]</font> Android Studio (not installed)
<font color="#5FEB5F">[✓]</font> Connected device (1 available)

<font color="#AA5500">!</font> Doctor found issues in 1 category.
</pre>
