### ISSUE TITLE
webview_flutter 不支持 (doesn't support) onConsoleMessage

### ISSUE THREAD

**Issue by bineanzhou** [flutter/flutter#40815]
项目里需要监听 (Google Translate: **Need to monitor in the project**) onConsoleMessage
```
@Override
public boolean onConsoleMessage(ConsoleMessage consoleMessage) {
            if (processConsoleMessage(consoleMessage.message())) {
                return true;
            }
            return super.onConsoleMessage(consoleMessage);
}
```

**Comment by janmoppel** [comment]
Hello @bineanzhou !

Thank you for posting an issue. We've translated its description into English using Google Translate. If you're comfortable writing in English, please check the translation and update it if necessary.

Can you please also provide additional information such as an output of the `flutter doctor -v` command? 

Thank you.

**Comment by bineanzhou** [comment]
hope to support consoleMessageDelegate
https://github.com/bineanzhou/webview_flutter_ext

**Comment by bineanzhou** [comment]
> Hello @bineanzhou !
> 
> Thank you for posting an issue. We've translated its description into English using Google Translate. If you're comfortable writing in English, please check the translation and update it if necessary.
> 
> Can you please also provide additional information such as an output of the `flutter doctor -v` command?
> 
> Thank you.

zhoubing1deMacBook-Pro:ttdd_flutter zhoubin$ flutter doctor -v
Waiting for another flutter command to release the startup lock...
^[[A[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.13.6 17G4015, locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.4 at /Users/zhoubin/work/flutter/sdk/flutter
    • Framework revision 20e59316b8 (10 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/zhoubin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/zhoubin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

zhoubing1deMacBook-Pro:ttdd_flutter zhoubin$ flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.13.6 17G4015, locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.4 at /Users/zhoubin/work/flutter/sdk/flutter
    • Framework revision 20e59316b8 (10 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/zhoubin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/zhoubin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • ALP AL00 • UYT7N18201001243 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

**Comment by VladyslavBondarenko** [comment]
Please follow up on the proposal and thumb it up
https://github.com/flutter/flutter/issues/32908
