### ISSUE TITLE
Consider a different default dimension than 800x600 for tests

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4082]
It makes @eseidelGoogle unhappy. :-)

**Comment by eseidelGoogle** [comment]
Just is one more thing to explain when giving someone a demo of flutter.

**Comment by Hixie** [comment]
What dimension would you want us to default to?

**Comment by eseidelGoogle** [comment]
Well, just like 800x600 was the defacto size of the time, I'd just pick Nexus 5 or current iPhone portrait screen size.  Anything portrait would be better than 800x600. :)

**Comment by abarth** [comment]
Awww...  ok.  I kind of liked that it was a reference to our past, but if it's causing trouble we can change it.  /me isn't looking forward to rewriting the tests that depend on it though.

**Comment by Hixie** [comment]
Personally I think the size doesn't matter. What made Eric say we should change it was me demoing live tests on a Nexus 6 in portrait, where, sure, 800x600 looks silly. But it also happens to exactly match the ratio of an iPad Pro in landscape. So...

**Comment by abarth** [comment]
There's some value in having the tests default to landscape since developers are likely to manually test more in portrait.

**Comment by eseidelGoogle** [comment]
My use case was that I wanted to demo our testing framework to developers and not have to explain why the test looks strange.  It's possible I should just get used to explaining.  Does this use case make sense?

**Comment by abarth** [comment]
Seems like you could just demo in landscape and say that it uses a standardized size for consistency.

**Comment by eseidelGoogle** [comment]
Here is the default template in landscape on an iPhone 6.

![simulator screen shot may 23 2016 7 55 35 pm](https://cloud.githubusercontent.com/assets/11857803/15490873/73d86b60-2120-11e6-834b-f311df984b7e.png)

Presumably the fab sizing is just a bug?  But it generally feels pretty awkward to try and demo in this mode, but for now I'll just live with it. :)

**Comment by eseidelGoogle** [comment]
Maybe we're running demos at a different density than the actual device screen is part of it?

**Comment by abarth** [comment]
> Presumably the fab sizing is just a bug?

I suspect the fab is animating in.

> But it generally feels pretty awkward to try and demo in this mode.

Maybe I'm not sure what you're trying to demo about it...  It might be more efficient to discuss in person.

**Comment by eseidelGoogle** [comment]
I'm sure there are things to improve here as more folks use this aspect of the testing framework, but for now I think we can close this bug.
