### ISSUE TITLE
How to change TextFormField prefixIcon color by ThemeData

### ISSUE THREAD

**Issue by JasperLee-LJP** [flutter/flutter#40829]
How to change TextFormField prefixIcon color by ThemeData?

**Comment by BondarenkoStas** [comment]
@JasperLee-LJP It would be good if you post it on StackOverflow as well and paste the link here, as help there may come faster.

**Comment by JasperLee-LJP** [comment]
I have posted it on StackOverflow, the link is [StackOverflow](https://stackoverflow.com/questions/58008625/flutter-how-to-change-textformfield-prefixicon-not-focus-color-by-themedata)

**Comment by VladyslavBondarenko** [comment]
Closing since solved
