### ISSUE TITLE
we want the 32 bit version

### ISSUE THREAD

**Issue by othmane53** [flutter/flutter#40839]
we love using 32 bit architecture, is there any chance to come up with flutter on 32 bit ?
Thanks

**Comment by escamoteur** [comment]
Which platform are you talking about?

**Comment by janmoppel** [comment]
Hello @othmane53 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
