### ISSUE TITLE
use switch-case in Dart

### ISSUE THREAD

**Issue by Maskedheroe** [flutter/flutter#40834]

**Comment by Maskedheroe** [comment]
I want to handle objects with a switch case. Just like Kotlin, why not increase this ability? Currently it can only handle constants...
                                                                   Sincerely
                                                                      A flutter fans😋

**Comment by NMateu** [comment]
@Maskedheroe you should ask / request here https://github.com/dart-lang/language/issues/27

**Comment by escamoteur** [comment]
Please request this feature here https://github.com/dart-lang/language
