### ISSUE TITLE
No visible @interface for 'FLBFlutterViewControllerAdaptor' declares the selector 'sendOnChannel:message:'

### ISSUE THREAD

**Issue by wendaovswendao** [flutter/flutter#40832]

**Comment by BondarenkoStas** [comment]
@wendaovswendao Please provide your ```flutter doctor -v``` and full log here.
Also if possible provide a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by escamoteur** [comment]
Please give more context for this issue what are you doing, on which platform does this happen. if you got an exception please provide stacktraces or log outputs

**Comment by stuartmorgan** [comment]
That class is not part of Flutter or any plugin maintained by the Flutter team. It appears to come from https://github.com/alibaba/flutter_boost/, so you'll need to file bugs about using it there.
