### ISSUE TITLE
null I/flutter ( 8097): 'package:flutter/src/widgets/text.dart': Failed assertion: line 253 pos 10: 'data != null': A non-null String must be provided to a Text widget.

### ISSUE THREAD

**Issue by HarshaBandlamudi** [flutter/flutter#40843]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by escamoteur** [comment]
I think its pretty clear from the message, you have passed `null` as value to a `Text`widget.
For more help please ask at stackoverflow
