### ISSUE TITLE
In iOS project, create a FlutterViewController class has crash.  How to solve it？

### ISSUE THREAD

**Issue by chenliangloveyou** [flutter/flutter#40847]
```

0 Flutter | fml::MessageLoopTaskQueues::NotifyObservers(unsigned long) (functional:1923)
-- | --
1 Flutter | fml::MessageLoopTaskQueues::NotifyObservers(unsigned long) (__tree:180)
2 Flutter | fml::MessageLoopImpl::FlushTasks(fml::FlushType) (iterator:1390)
3 Flutter | fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (message_loop_darwin.mm:76)
4 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
5 CoreFoundation | ___CFRunLoopDoTimer + 864
6 CoreFoundation | ___CFRunLoopDoTimers + 248
7 CoreFoundation | ___CFRunLoopRun + 1844
8 CoreFoundation | CFRunLoopRunSpecific + 436
9 Flutter | fml::MessageLoopDarwin::Run() (message_loop_darwin.mm:47)
10 Flutter | _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE3$_0EEEEEPvSJ_ (message_loop_impl.cc:84)
11 libsystem_pthread.dylib | __pthread_body + 128
12 libsystem_pthread.dylib | _pthread_start + 44

```

```

0 libsystem_malloc.dylib | 0x000000020228cba4 nanov2_size$VARIANT$mp
-- | --
1 libsystem_malloc.dylib | 0x000000020229c300 free
2 IOAccelerator | 0x000000020478d408 IOAccelContextSubmitDataBuffersExt2
3 libGPUSupportMercury.dylib | 0x000000021e5e0f8c gpusSubmitDataBuffers
4 libGPUSupportMercury.dylib | 0x000000021e5e0dc8 gldCreateContext
5 GLEngine | 0x0000000223c0fd3c gliCreateContextWithShared
6 OpenGLES | 0x00000002058c43c8 -[EAGLContext commonInitWithAPI:properties:]
7 OpenGLES | 0x00000002058c40c4 -[EAGLContext initWithAPI:properties:]
8 Flutter | 0x0000000102d40840 _ZNSt3__110__function6__funcIZ40-[FlutterEngine createShell:libraryURI:]E3$_3NS_9allocatorIS2_EEFNS_10unique_ptrIN7flutter12PlatformViewENS_14default_deleteIS7_EEEERNS6_5ShellEEEclESC_ (ios_gl_context.mm:0)
9 Flutter | 0x0000000102db20c8 _ZNSt3__110__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter5Shell6CreateENS5_11TaskRunnersENS5_8SettingsENS2_6RefPtrIKNS5_12DartSnapshotEEESC_NS_8functionIFNS_10unique_ptrINS5_12PlatformViewENS_14default_deleteISF_EEEERS6_EEENSD_IFNSE_INS5_10RasterizerENSG_ISM_EEEESJ_EEENS5_9DartVMRefEE3$_1EENS_9allocatorIST_EEFvvEEclEv (memory:2623)
10 Flutter | 0x0000000102db1430 flutter::Shell::Create(flutter::TaskRunners, flutter::Settings, std::__1::function<std::__1::unique_ptr<flutter::PlatformView, std::__1::default_delete<flutter::PlatformView> > (flutter::Shell&)>, std::__1::function<std::__1::unique_ptr<flutter::Rasterizer, std::__1::default_delete<flutter::Rasterizer> > (flutter::Shell&)>) (functional:1872)
11 Flutter | 0x0000000102d3e4c0 -[FlutterEngine createShell:libraryURI:] (memory:2628)
12 Flutter | 0x0000000102d4b60c -[FlutterViewController initWithProject:nibName:bundle:] (FlutterViewController.mm:79)
13 project | 0x0000000100dcf3cc +[GTLoginLogic presnetLoginViewControllerWithCallback:] (GTLoginLogic.m:122)

```

**Comment by escamoteur** [comment]
Please add the output of `flutter doctor`
Do I understand this right, this is a native iOS project with a Flutter view?
Can you share the code where you create this flutter view?

**Comment by chenliangloveyou** [comment]
`xxdeMacBook-Pro:~ xx$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G95, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.5)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.`

--------

`
yes，this is a ios project, and a  few page use flutter , flutter and native communication frequently. 
`
`
Our App crash has some features, usually within 1 - 5 seconds of boot, all on old devices, and none of the devices above the iPhone 7 have ever appeared. But before the introduction of flutter, there were no such crashes. I suspect it's a memory problem.
`


    FlutterViewController *mineVC = [[FlutterViewController alloc]init];
    [mineVC setInitialRoute:@"account"];

    [[FlutterMethodChannelManager sharedInstance] registerAccountFlutterMethodChannelsWithController:mineVC];

    [FlutterMethodChannelManager sharedInstance].loginCallback = callback;

    UINavigationController *mineNav = [[UINavigationController alloc] initWithRootViewController:mineVC];

    [mineNav setNavigationBarHidden:YES animated:NO];

    [self presentViewController:mineNav animated:YES completion:^{
       // [GTLoginLogic shareInstance].isPresnet = NO;
    }];

**Comment by escamoteur** [comment]
I see you are on a pretty old flutter version. Could you please upgrade to the latest version?

**Comment by chenliangloveyou** [comment]
**Like these crashes in the flutter stack, can you tell me what caused them?**

0 #id SIGSEGV
SEGV_ACCERR

libGPUSupportMercury.dylib _gpus_ReturnNotPermittedKillClient` libGPUSupportMercury.dylib   | _gpus_ReturnNotPermittedKillClient + 12
-- | --
1 AGXGLDriver | gldUpdateDispatch + 7184
2 libGPUSupportMercury.dylib | gpusSubmitDataBuffers + 176
3 AGXGLDriver | gldUpdateDispatch + 12604
4 Flutter | SkImage::MakeCrossContextFromEncoded(GrContext*, sk_sp<SkData>, bool, SkColorSpace*, bool) (SkRefCnt.h:288)
5 Flutter | _ZNSt3__110__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter12_GLOBAL__N_121InstantiateImageCodecEP21_Dart_NativeArgumentsE3$_1EENS_9allocatorISA_EEFvvEEclEv (codec.cc:0)
6 Flutter | fml::MessageLoopImpl::FlushTasks(fml::FlushType) (ref_ptr.h:116)
7 Flutter | fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (message_loop_darwin.mm:76)
8 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
9 CoreFoundation | ___CFRunLoopDoTimer + 864
10 CoreFoundation | ___CFRunLoopDoTimers + 248
11 CoreFoundation | ___CFRunLoopRun + 1844
12 CoreFoundation | CFRunLoopRunSpecific + 436
13 Flutter | fml::MessageLoopDarwin::Run() (message_loop_darwin.mm:47)
14 Flutter | _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE3$_0EEEEEPvSJ_ (message_loop_impl.cc:84)
15 libsystem_pthread.dylib | __pthread_body + 128
16 libsystem_pthread.dylib | _pthread_start + 44

`

**Comment by chenliangloveyou** [comment]
> I see you are on a pretty old flutter version. Could you please upgrade to the latest version?

Next version I will upgrade .

**Comment by aslanTT** [comment]
> > I see you are on a pretty old flutter version. Could you please upgrade to the latest version?
> 
> Next version I will upgrade .

Hello，have you solve the problem？ we use flutter 1.9.2+hotfix version, and still have many the crash.

**Comment by chenliangloveyou** [comment]
> > > I see you are on a pretty old flutter version. Could you please upgrade to the latest version?
> > 
> > 
> > Next version I will upgrade .
> 
> Hello，have you solved the problem？ we use flutter 1.9.1+hotfix.5 version, and still have many the crash.

no way, Quick launch, and then quickly back to the background can reproduce the problem. I suspect it's the OpenGL problem in flutter.

**Comment by escamoteur** [comment]
As this is a native/Flutter mixed app, please try to switch to the master channel if this solves your problem

**Comment by MrLittleStrong** [comment]
> As this is a native/Flutter mixed app, please try to switch to the master channel if this solves your problem

Seems this had been recorded.  Yet still not solved.
[#37813](https://github.com/flutter/flutter/issues/37813#issue-478157079)

**Comment by dnfield** [comment]
I agree that this is very likely another case of OpenGL calls happening while the app is in the background.  @gaaclarke @chinmaygarde

**Comment by gaaclarke** [comment]
> I agree that this is very likely another case of OpenGL calls happening while the app is in the background. @gaaclarke @chinmaygarde

Yep seems like it because of `gpus_ReturnNotPermittedKillClient`.  The user didn't post the thread of the crash but this may be the platform thread that is creating the OpenGL context.  I don't think we do anything to protect the platform thread.  If that's the case, this crash seems very unlikely since it would require you to background the app just as setup is happening.

**Comment by fengyuxx** [comment]
We have a lot of this crash in iOS too.

Crash stack:

#6 Thread
SIGSEGV
SEGV_ACCERR

0 libGPUSupportMercury.dylib | _gpus_ReturnNotPermittedKillClient + 12
-- | --
1 AGXGLDriver | gldUpdateDispatch + 7184
2 libGPUSupportMercury.dylib | gpusSubmitDataBuffers + 176
3 AGXGLDriver | gldUpdateDispatch + 12604
4 AGXGLDriver | gldPresentFramebufferData + 98004
5 AGXGLDriver | gldPresentFramebufferData + 1968
6 GLEngine | _glReadPixels_Exec + 964
7 Flutter | GrGLGpu::readOrTransferPixelsFrom(GrSurface*, int, int, int, int, GrColorType, GrColorType, void*, int) (GrGLGpu.cpp:2266)
8 Flutter | GrGpu::readPixels(GrSurface*, int, int, int, int, GrColorType, GrColorType, void*, unsigned long) (GrGpu.cpp:392)
9 Flutter | GrSurfaceContext::readPixels(GrPixelInfo const&, void*, unsigned long, SkIPoint, GrContext*) (GrSurfaceContext.cpp:206)
10 Flutter | SkImage_GpuBase::onReadPixels(SkImageInfo const&, void*, unsigned long, int, int, SkImage::CachingHint) const (SkImage_GpuBase.cpp:159)
11 Flutter | SkImage::makeRasterImage() const (SkImage.cpp:420)
12 Flutter | _ZNSt3__110__function6__funcIZN7flutter7Picture16RasterizeToImageE5sk_spI9SkPictureEjjP12_Dart_HandleE3$_1NS_9allocatorIS9_EEFvvEEclEv (SkRefCnt.h:287)
13 Flutter | fml::MessageLoopImpl::FlushTasks(fml::FlushType) (ref_ptr.h:116)
14 Flutter | fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (message_loop_darwin.mm:76)
15 CoreFoundation | 0x00000001c5d26000 + 701780
16 CoreFoundation | 0x00000001c5d26000 + 701060
17 CoreFoundation | 0x00000001c5d26000 + 699064
18 CoreFoundation | 0x00000001c5d26000 + 678408
19 CoreFoundation | CFRunLoopRunSpecific + 436
20 Flutter | fml::MessageLoopDarwin::Run() (message_loop_darwin.mm:47)
21 Flutter | _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE3$_0EEEEEPvSJ_ (message_loop_impl.cc:84)
22 libsystem_pthread.dylib | __pthread_body + 128
23 libsystem_pthread.dylib | _pthread_start + 44



Flutter doctor:
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale
    zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/myspace/Develop/language/flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/myspace/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 516EA7B5-8691-4D91-A2F6-02BA780C3570 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

**Comment by gaaclarke** [comment]
This should be fixed in after https://github.com/flutter/engine/pull/13908 . Try out the flutter master channel.  I believe flutter 5fb790e6ed4717166c8b9a7b38dae79119560557 and later should be good.
