### ISSUE TITLE
Issue using firebase_ml_vision

### ISSUE THREAD

**Issue by Kyaw-Zin-Thant** [flutter/flutter#40841]
Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:2702
I/DynamiteModule(31079): Selected remote version of com.google.android.gms.vision.dynamite, version >= 2702
V/DynamiteModule(31079): Dynamite loader version >= 2, using loadModule2NoCrashUtils
I/Vision  (31079): Loading library libocr.so
I/Vision  (31079): libocr.so library load status: true

I used firebase_ml_vision-0.9.2+1.

**Comment by escamoteur** [comment]
Please ask this at https://github.com/FirebaseExtended/flutterfire
And please add what excatly you problem is.
