### ISSUE TITLE
use  webview_flutter select file problem

### ISSUE THREAD

**Issue by gitzhangliang** [flutter/flutter#40844]
when i use webview_flutter, my html is
```
<body>
<input type="file" title="upload image" multiple="multiple" accept="image/gif,image/jpeg,image/jpg,image/png,image/svg"/>
</body>
```
but i can not select file

**Comment by gitzhangliang** [comment]
<body>
<input type="file" title="上传图片" multiple="multiple" accept="image/gif,image/jpeg,image/jpg,image/png,image/svg"/>
</body>

**Comment by gitzhangliang** [comment]
'<body>
<input type="file" title="上传图片" multiple="multiple" accept="image/gif,image/jpeg,image/jpg,image/png,image/svg"/>
</body>'

**Comment by gitzhangliang** [comment]
![upload](https://user-images.githubusercontent.com/30276946/65239672-1df4fd80-db12-11e9-8593-c7ec9ce5a7bf.png)

**Comment by gitzhangliang** [comment]
![image](https://user-images.githubusercontent.com/30276946/65239882-8348ee80-db12-11e9-9528-338ce63fd354.png)
when i want to select image, but i can not.

**Comment by escamoteur** [comment]
Please attach the output of `flutter doctor`here
What do you mean by you can not? Doesn't it open a file dialog?
Can you share a small example project that shows this error please?

**Comment by gitzhangliang** [comment]
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.17763.720], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.2)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by gitzhangliang** [comment]
yes,  it can not open a file dialog.
i only replace the initialUrl of example.  my html file body 
![upload](https://user-images.githubusercontent.com/30276946/65264668-b0f95c00-db41-11e9-818a-49c110627ad9.png)

i can open a file dialog useing chrome ,  but user webview_flutter,  i can not.
when i use webview_flutter include rich text html, i can not open a file  dialog to select image ,just the second picture.  my english is poor..  wish you can understand what i say

**Comment by gitzhangliang** [comment]
no no  no!
![image](https://user-images.githubusercontent.com/30276946/65265509-b657a600-db43-11e9-8745-9eaf76605e7e.png)
 

this is my project  . when i click image,  i can not  open a file dialog

**Comment by escamoteur** [comment]
ok, understood. Just curious why do you write a Flutter app and then have a web app inside?

**Comment by gitzhangliang** [comment]
beacuse my project hope everyone can edit content  just like use ckeditor ( https://ckeditor.com/ ), make content beautiful in flutter  app.  i find a plugin for Zefyr.  it can .  but this plugin content  does not  html ellment.  my project  hope the content is html element .just like  this
![9](https://user-images.githubusercontent.com/30276946/65266619-ff105e80-db45-11e9-9589-fb11509fea5d.png)

**Comment by pakyo-pan** [comment]
I am facing the same problem，`<input type="file" accept="image/*" />` can not open a file dialog on android.

**Comment by deandreamatias** [comment]
This issue its similar with this one #27924.
Please @escamoteur, check if this issue is duplicate and close it if you want. Thanks

**Comment by escamoteur** [comment]
@deandreamatias yep seems like the same issue I close this one
