### ISSUE TITLE
flutter should fail hard if the pubspec.yaml file of a project points to a different flutter package than expected

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4084]
We're getting numerous cases of people having multiple flutter checkouts but having the "flutter" tool not correspond to the directory to which their code points, leading to huge confusion.

**Comment by Hixie** [comment]
cc @devoncarew

**Comment by pallaviashim** [comment]
To resolve the issue with path dependency, what i do is, delete the pubspec.yaml file and use the command -  flutter create "path of the project folder" in terminal. Do you have any other method to solve the dependancy?
