### ISSUE TITLE
Support Route Params

### ISSUE THREAD

**Issue by aghassemi** [flutter/flutter#4087]
Currently `onGenerateRoute` is the only way to handle dynamic routes and developers have to manually split the route to get the dynamic parts out. We should provide some basic route param support and leave `onGenerateRoute` for more complex cases.

Maybe `:param` and `:optionalParam?` to start with.
e.g.

```
routes: {
  `/blogs/:blogId/:page?` : (BuildContext ctx, Map<String, String> routeParams) => new Widget()
}
```

**Comment by abarth** [comment]
Yeah, we probably want something similar to https://pub.dartlang.org/packages/shelf_route .  I wonder if we can share code or ideas with the shelf web server.

**Comment by sethladd** [comment]
cc @kevmoo

**Comment by kevmoo** [comment]
The "shelf model" works really well. Based off proven patterns in rails, node and other places.

Ping @nex3 and me if you want to chat...

**Comment by paolosoares** [comment]
This is required by project:mulligan for deep-linking.

**Comment by eseidelGoogle** [comment]
I think we have some other bugs on this.  My understanding is the primatives exist such that it's possible eto build this with onGeneratedRoute, but the higher-level parsing infrastructure isn't pre-built yet.

https://github.com/google/uri.dart might be a library useful for doing parsing like this?

I also believe that @lukef and possibly others have built systems like this while writing their flutter apps.

**Comment by eseidelGoogle** [comment]
I think we have some other bugs on this.  My understanding is the primatives exist such that it's possible eto build this with onGeneratedRoute, but the higher-level parsing infrastructure isn't pre-built yet.

https://github.com/google/uri.dart might be a library useful for doing parsing like this?

I also believe that @lukef and possibly others have built systems like this while writing their flutter apps.

**Comment by lukef** [comment]
We have a preliminary package here: https://github.com/goposse/flutter-router.

I'm open to renaming it to avoid confusion. We're also working to add transitions so consider it a WIP. Hopefully we will be done in the next few days.

**Comment by neiljaywarner** [comment]
@Lukef @Hixie @eseidelGoogle can we have an update please?

**Comment by lukef** [comment]
Fluro (https://github.com/theyakka/fluro) supports route params. I have no information on whether the built in navigator will support parameters in this fashion or not.

**Comment by goderbauer** [comment]
You can now pass arguments to a named route and access them via RouteSettings, see https://flutter.dev/docs/cookbook/navigation/navigate-with-arguments.

Does that resolve this issue for people? What else would you need to resolve it?

**Comment by micaelsn** [comment]
You can make a 
Map<String, dynamic> list = {"argument1":agr1, "argument2":agr2, }; 
and pass in (...) arguments:list (...)
in you router class:
case '/upload':
        Map<String, dynamic> args = settings.arguments;
         return MaterialPageRoute(builder: (_) => Upload(list: args));

It's more easy :)
