### ISSUE TITLE
Scaffold.body ---> Scaffold.builder

### ISSUE THREAD

**Issue by LCostaN** [flutter/flutter#40881]
### Change Scaffold's body to a builder attribute to give it's own context
That would remove the necessity of "hacks" when using `Scaffold.of(context)`.

*Example:*
`AppBar` actions that call `Scaffold.of(context).showSnackbar()`.

**Comment by dblokhin** [comment]
- It is not a hack.
- You can use a `Builder` widget to get `context`:
```dart
child: Builder(builder: (context) => SomeYourWidget()),
```
- You can use a `key` to get Scaffold state to manage you `Snackbar`:
```dart
// create Scaffold gloabl key
var _key = new GlobalKey<ScaffoldState>();

/// ...

// creating Scaffold with key
new Scaffold(
        key: _key,
        /// ...
);

///...

// using the scaffoldKey to show snackbar
scaffoldKey.currentState.showSnackBar(snackbar);
```

**Comment by LCostaN** [comment]
@dblokhin Indeed, that's the usual way to solve this. I'm just saying that usually it's preferred (according to docs at least) to use `Scaffold.of(context)` instead of `_scaffodlKey.currentState`. It's not forbidden or anything just not recommended by the Flutter's docs to do that way.

When showing snackbar from an AppBar's IconButton for example, you need to use a builder to create a context with a Scaffold parent as Scaffold can't find itself as a parent.

I'm not proposing making Scaffold find itself as this could cause problems, but I think making the body a separate context would achieve the desired result without having to use `Builder() widgets` or the not recommended `_myScaffoldKey.currentState`.

**Comment by Hixie** [comment]
While I agree that this would have made sense as the initial design, I think we've taken too long to consider this now and at this point we're better off just leaving it as-is to avoid breaking people.
