### ISSUE TITLE
Firebase test on LUCI is flaky

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#40890]
/cc @godofredoc 

This seems to have started with the new Debian images. We occasionally get errors like this: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8901873118703817104/+/steps/Firebase_test/0/stdout

```
Traceback (most recent call last):
  File "/usr/bin/../lib/google-cloud-sdk/lib/gcloud.py", line 20, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__
```

This has happened 3 times in the last day or so:

https://ci.chromium.org/p/flutter/builders/prod/Linux%20Android%20AOT%20Engine/2253
https://ci.chromium.org/p/flutter/builders/prod/Linux%20Android%20AOT%20Engine/2244
https://ci.chromium.org/p/flutter/builders/prod/Linux%20Android%20AOT%20Engine/2241

**Comment by dnfield** [comment]
For now, will make that step always pass in https://chromium-review.googlesource.com/c/chromium/tools/build/+/1814433

**Comment by cbracken** [comment]
@dnfield have you seen this recently (2020?). I wonder if this was related to premptive migration to python3 features before the python2 d-day and end-of-year 2019?

**Comment by Hixie** [comment]
Is this step still being skipped? Is it still failing?

**Comment by godofredoc** [comment]
Is firebase test using python outside of a vpython sandbox? Ideally anything using python should be using vpython for dependencies. Also I think luci started enforcing vpython as default a couple of days ago.

**Comment by zanderso** [comment]
@dnfield Are you working on this at the moment? Is this issue stale?

**Comment by dnfield** [comment]
This should be fixed now - the LUCI bots are not having issues invoking gcloud since we went to the Fuchsia recipes, and we also retry invocations when FTL returns an exit code that suggests a transient or infra failure.
