### ISSUE TITLE
unable to debug 

### ISSUE THREAD

**Issue by glenfordwilliams** [flutter/flutter#4089]
## Steps to Reproduce

tried running the app using the flutter atom plugin but the device screen was blank followed by the following in the atom console

```
flutter run --debug-port=16229 --start-paused • flutter logs
first/ • debug
Installing app.apk to KFARWI...
Running lib/main.dart on KFARWI...
Timed out while waiting for a debug connection.
Error running application on KFARWI.
```

note though that even though it does not work trying to use atom-flutter to launch and debug, launching the installed package on the device works

## Flutter Doctor

```
[kingwill101@kingtech first]$ flutter doctor
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/kingwill101/flutter
    • Framework revision cc93170894 (11 days ago), engine revision 98f020ff2d

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /home/kingwill101/Android/Sdk/
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0_92-b14)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

## Logs and Crash Reports

I later tried running it from the command line and got this

```
[kingwill101@kingtech first]$ flutter run
Installing app.apk to KFARWI...
Running lib/main.dart on KFARWI...
Timed out while waiting for a debug connection.
Error running application on KFARWI.
```

trying to use a different device kept giving the following error

```
[kingwill101@kingtech first]$ flutter run
Installing app.apk to HUAWEI Y600 U151...
Package install error: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
[kingwill101@kingtech first]$ ```

know its a android error but not sure how to fix it in the flutter project.

```

**Comment by eseidelGoogle** [comment]
http://stackoverflow.com/questions/2914105/android-what-is-install-parse-failed-no-certificates-error mentions `ant`, I wonder if our (out of date) dependence on `ant` is related.  @jason-simmons?  https://github.com/flutter/flutter/issues/3917

**Comment by gdelca5** [comment]
Same issue with Samsung GT-I9070 - Android 4.1.2:

bash-3.2$ flutter build clean
Deleting 'build/'.
bash-3.2$ flutter build apk
Building APK in release mode (android-arm-release)...      
Warning: signing the APK using the debug keystore.
Built build/app.apk (8.1MB).
bash-3.2$ flutter run
Building APK in debug mode (android-arm)...              
Warning: signing the APK using the debug keystore.
Built build/app.apk (8.6MB).
Installing app.apk to 28412FAEA620CF1A1D858760ED8FAFE...
Package install error: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
bash-3.2$ flutter build clean
Deleting 'build/'.
bash-3.2$ flutter build apk
Building APK in release mode (android-arm-release)...      
Warning: signing the APK using the debug keystore.
Built build/app.apk (8.1MB).
bash-3.2$ flutter run
Building APK in debug mode (android-arm)...              
Warning: signing the APK using the debug keystore.
Built build/app.apk (8.6MB).
Installing app.apk to 28412FAEA620CF1A1D858760ED8FAFE...
Package install error: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
bash-3.2$ flutter doctor
[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/gdc/flutter
    • Framework revision 6d2d495369 (11 days ago), engine revision a943c732d5

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/opt/android-sdk
    • Platform android-22, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_92-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.25

**Comment by viru** [comment]
I was able to workaround this by installing legacy Java (6) from here: https://support.apple.com/kb/dl1572?locale=en_US and then building my app with `JAVA_HOME=/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home flutter build apk`. The problem was with signing method in newer version of Java and trying to build a package for very old Android (4.1.2). Source: http://stackoverflow.com/a/10083280/3201908 App still doesn't work, but at least is installs, so I'm still debugging.

**Comment by mit-mit** [comment]
Closing; signing is now expected to happen as part of a gradle-based build.
