### ISSUE TITLE
ValueListenableBuilder: listen to more than one value

### ISSUE THREAD

**Issue by n8crwlr** [flutter/flutter#40906]
I am using `ValueListenableBuilder` to watch some values in several animated custom widgets. Those are using several values, based on their childrens sizes, to animate depending actions.

My problem is _listening to more than one value_. I have to nest them.

The following is a reduced example to explain:

```dart
class MyWidget extends StatelessWidget {
  final ValueNotifier<double> _height1 = ValueNotifier<double>(40);
  final ValueNotifier<double> _height2 = ValueNotifier<double>(120);
  final ValueNotifier<double> _height3 = ValueNotifier<double>(200);

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder(
      builder: (BuildContext context, double h1, Widget child) {
        return ValueListenableBuilder(
          builder: (BuildContext context, double h2, Widget child) {
            return ValueListenableBuilder(
                builder: (BuildContext context, double h3, Widget child) {
                  return GestureDetector(
                    // i am using h1, h2 and h3 here ...
                    child: Stack(
                      children: <Widget>[
                        Positioned(
                          left: 0,
                          right: 0,
                          bottom: value,
                          child: Column(
                            children: <Widget>[
                              Container(height: _height1.value),
                              Container(height: _height2.value),
                              Container(height: _height3.value),
                            ],
                          ),
                        ),
                      ],
                    ),
                  );
                },
                valueListenable: _height3,
                child: null);
          },
          valueListenable: _height2,
          child: null,
        );
      },
      valueListenable: _height1,
      child: null,
    );
  }
}
```

Is it possible to add `valuesListenable` in case of listening to a **list of values**?

**Comment by lucasccustodio** [comment]
I think this is a case for [Listenable.merge](https://api.flutter.dev/flutter/foundation/Listenable/Listenable.merge.html)

**Comment by escamoteur** [comment]
If you have further questions please ask on stackoverflow

**Comment by n8crwlr** [comment]
@lucasccustodio 

> I think this is a case for `Listenable.merge`

do you mean this would work? I didn't understand this. Maybe, you can give me a short introduction.

https://stackoverflow.com/questions/58030337/valuelistenablebuilder-listen-to-more-than-one-value

Thank you

**Comment by n8crwlr** [comment]
@escamoteur you didn't provide any help to me. Good job. Thank you for just closing the issue.

**Comment by escamoteur** [comment]
@n8crwlr I commented on your stackoverflow post to help you there

**Comment by n8crwlr** [comment]
@escamoteur you didn't help me - you didn't understand anything

**Comment by escamoteur** [comment]
Just because I didn't give you the the final solution but tried to get you selve to a solution. See my comment on stackoverflow. Am 21.09.2019 22:03 schrieb n8crwlr <notifications@github.com>:@escamoteur you didn't help me - you didn't understand anything

**Comment by n8crwlr** [comment]
I am talking about _one_ `ValueListenableBuilder`, which listens to several properties.

With `.merge`, again, i have _three_`ValueListenableBuilder`. That's the same ugly code like nesting.

Do you know a solution which is as small as _one_ `ValueListenableBuilder`?

**Comment by escamoteur** [comment]
See answer on stackoverflow. Am 22.09.2019 07:27 schrieb n8crwlr <notifications@github.com>:I am talking about one ValueListenableBuilder, which listens to several properties.
With .merge, again, i have threeValueListenableBuilder. That's the same ugly code like nesting.
Do you know a solution which is as small as one ValueListenableBuilder?

**Comment by n8crwlr** [comment]
Thomas, you are annoying me. I do not feel like warring with you or constantly reading myself into your thoughts. Do you play teacher? Just leave it. I suggested a FR here, it was a thought. I have other things to do all day than to study this approach. It may be that you spend your life just in front of your monitor, but I do not do that. I just want to have fun with Flutter, and for days you've been scrounging with me. If you do not have a solution, just leave it. Do not always tell me that you're presenting a solution somewhere else now, and when I'm there I just get nonsense. You cost me time and nerves. For nothing. Just for your personal feeling.

Please, i do not want to read anything more about it.

**Comment by n8crwlr** [comment]
I had done this way, but it does not work. It errors. I will have a look again next time. Thank you

**Comment by escamoteur** [comment]
Look you had the solution on front of your nose. Yes I try to teach things if I think it's worth it. The solution is on stackoverflow where it belongs. When I first asked you what's your problem you could not express it clearly.On stackoverflow now you tell me you had tried this before but it didn't work. Why the... Didn't you tell that and say what error you get. This hear isn't a support place. It also takes my time to help you. For some one asking for help you are pretty rude from the beginning.Don't come for support questions again. Am 22.09.2019 19:15 schrieb n8crwlr <notifications@github.com>:Thomas, you are annoying me. I do not feel like warring with you or constantly reading myself into your thoughts. Do you play teacher? Just leave it. I suggested a FR here, it was a thought. I have other things to do all day than to study this approach. It may be that you spend your life just in front of your monitor, but I do not do that. I just want to have fun with Flutter, and for days you've been scrounging with me. If you do not have a solution, just leave it. Do not always tell me that you're presenting a solution somewhere else now, and when I'm there I just get nonsense. You cost me time and nerves. For nothing. Just for your personal feeling.
Please, i do not want to read anything more about it.

**Comment by n8crwlr** [comment]
My first thought about this was: `valueListenable: Listenable.merge([_height1, _height2, _height3])`.

> Look you had the solution on front of your nose. Yes I try to teach things if I think it's worth it. The solution is on stackoverflow where it belongs. When I first asked you what's your problem you could not express it clearly.On stackoverflow now you tell me you had tried this before but it didn't work. Why the... Didn't you tell that and say what error you get. This hear isn't a support place. It also takes my time to help you. For some one asking for help you are pretty rude from the beginning.Don't come for support questions again. 

But, the same as you wrote on stackoverflow https://stackoverflow.com/a/58035263/12083567:

```dart
class MyWidget extends StatelessWidget {
  final ValueNotifier<double> _height1 = ValueNotifier<double>(40);
  final ValueNotifier<double> _height2 = ValueNotifier<double>(120);
  final ValueNotifier<double> _height3 = ValueNotifier<double>(200);

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder(
      valueListenable: Listenable.merge([_height1, _height2, _height3]),
      child: null,
      builder: (BuildContext context, double h3, Widget child) {
        return GestureDetector(
          // i am using h1, h2 and h3 here ...
          child: Stack(
            children: <Widget>[
              Positioned(
                left: 0,
                right: 0,
                bottom: value,
                child: Column(
                  children: <Widget>[
                    Container(height: _height1.value),
                    Container(height: _height2.value),
                    Container(height: _height3.value),
                  ],
                ),
              ),
            ],
          ),
        );
      },
    );
  }
}
```

### The Error

`type '_MergingListenable' is not a subtype of type 'ValueListenable<double>'`:

```bash
I/flutter ( 8815): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 8815): The following assertion was thrown building Slider(dirty):
I/flutter ( 8815): type '_MergingListenable' is not a subtype of type 'ValueListenable<double>'
I/flutter ( 8815): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 8815): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 8815): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 8815):   https://github.com/flutter/flutter/issues/new?template=BUG.md
```

**Comment by escamoteur** [comment]
It's a really subtle one. You had the value parameter of the builder defined as `double` which set the whole `ValueListenableBuilder` to be of type `double`. Removing the `double` should fix it. Then all types should be `dynamic` und the problem gone.

**Comment by n8crwlr** [comment]
`type '_MergingListenable' is not a subtype of type 'ValueListenable<dynamic>'`

`type '_MergingListenable' is not a subtype of type 'ValueListenable<ValueNotifier<dynamic>>'`

I tried several things in this direction

**Comment by escamoteur** [comment]
Yeah I checked it again. You just can't use ValueListenableBuilder together with merge because the return value is just a Listenable but not a ValueListenable. 
Use AnimatedBuilder instead, despite the name its in reality a ListenableBuilder.

**Comment by n8crwlr** [comment]
You noticed the difference between

```dart
Widget TransitionBuilder (
  BuildContext context,
  Widget child
)
```

and

```dart
Widget ValueWidgetBuilder (
  BuildContext context,
  T value,
  Widget child
)
```

? It needs `value`(s).

**Comment by escamoteur** [comment]
Just access your ValueChangenotifier directly inside the builder. Am 23.09.2019 02:07 schrieb n8crwlr <notifications@github.com>:You noticed the difference between
Widget TransitionBuilder (
  BuildContext context,
  Widget child
)
and
Widget ValueWidgetBuilder (
  BuildContext context,
  T value,
  Widget child
)
? It needs value(s).

**Comment by n8crwlr** [comment]
This all makes no sense. Would be better to use Keys instead.

> Man just start thinking! You want a rebuild whenever one of your ValueListenables changes. You can combine multiple ValueListenable into one with Listenable.merge. If don't figure it out till tomorrow I give you the full answer! – Thomas

You tried this now for two days. Thanks for your friendly help.

**Comment by n8crwlr** [comment]
For me, this feature request takes place. The above is monkeycode.

For my problem, as written, the GestureDetector can check the properties at start.

**Comment by escamoteur** [comment]
May I remind you that we could have been way faster if you had asked the right question. Again you are more than rude.
In your code above you don't even use h3 you already access your ValueChangenotifier directly. 
What has the GesturesDetector to do with it. 
My solution works! 
If you don't like it use something else than ValueChangenotifier like Streams.

**Comment by escamoteur** [comment]
And as said, the feature is closed this isn't a support site.

**Comment by n8crwlr** [comment]
It is an animation and is just reduced to the widgets needed.

No, @escamoteur you did a really bad job. It's just your opinion you followed. You want it this way.

But ok, you are a great contributor :clap:

**Comment by n8crwlr** [comment]
> And as said, the feature is closed this isn't a support site.

This was a feature request!

**Comment by escamoteur** [comment]
You behave like a spoiled kid with no respect. To use an AnimatedBuilder with a Listenable is absolute correct.If you insist using an ValueListenableBuilder you will have to derive your own ValueListenable that takes three ValueListenable and combine them to one that returns an List of real. Way more complicated but possible. Am 23.09.2019 09:02 schrieb n8crwlr <notifications@github.com>:It is an animation and is just reduced to the widgets needed.

No, @escamoteur you did a really bad job. It's just your opinion you followed. You want it this way.

But ok, you are a great contributor 👏

**Comment by escamoteur** [comment]
What feature did you request? I didn't read anything as a feature description. Am 23.09.2019 09:04 schrieb n8crwlr <notifications@github.com>:
And as said, the feature is closed this isn't a support site.

This was a feature request!

**Comment by n8crwlr** [comment]
> What feature did you request? I didn't read anything as a feature description.

That's confusing, you are right. I started using the feature request issue. Cannot remember what's happened here.

The requested feature should be kind of listening to a list of `Listenable`s

```dart
ValueListenableBuilder(
  valueListenable: [_height1, _height2, _height3],
  builder: (BuildContext context, T value, Widget child) {
  // ...
```

instead of nesting.

As `Listenable.merge()` did not work i had no concrete idea for this and i just wanted to start a talk for the flutter way of handling this, as it sounds correct that a `ValueListenableBuilder` can listen to several `Listenable`s, like `AnimatedBuilder` in your proposal.

Your solution https://stackoverflow.com/a/58035263/12083567
and the complexity of https://stackoverflow.com/a/58058091/12083567
confirm this request at least for me.

**Comment by escamoteur** [comment]
You could just open a new issue with this description but I don't think there is a good chance for it because there are several way so solve it.
My solution is comletely valid, actually you didn't do it differently in your original approach.

Another way would be to derive your own ValueChangeNotifier class that takes a list of of ValueChangeNotifiers<T> and returns a  List<T>

Then  you could use it 
 ```Dart
ValueListenableBuilder<List<double>>(
  valueListenable: ValueChangeNotifierMerger<double>([_height1,_height2,_height1 ]) ,
  builder: (BuildContext context, List<double> heightValues, Widget child) {
....
```

This would be pretty elegant solution, you could also use a Map instead of a List if you want more control over the values.

A third solution would be using RxDart with a StreamBuilder and CombineLatest.

You see there are enough possibilities so I don't think a feature request makes sense. But go ahead if you want.

**Comment by n8crwlr** [comment]
Thank you very much, i will remember this idea. The `Listenable`s-solution does not exactly fit my needs, it's overwhelming a bit, as at least no listening is required st this stage - the `GestureDetector` catches those values at start, which is at least the more appropriate solution.

Thanks for the journey and your efforts

**Comment by 6643** [comment]
```
import 'package:flutter/cupertino.dart';

extension ReBuilder on ValueNotifier {
  ValueListenableBuilder reBuilder(Widget Function() widget, {Widget? child}) {
    return ValueListenableBuilder(
      valueListenable: this,
      builder: (context, value, child) => widget(),
      child: child,
    );
  }
}

extension reBuilders on List<ValueNotifier> {
  ValueListenableBuilder reBuilder(Widget Function() widget, {Widget? child}) {
    final first = this.removeAt(0);
    return ValueListenableBuilder(
      valueListenable: first,
      builder: (_, value, child) {
        return this.length == 1 ? this.first.reBuilder(() => widget(), child: child) : this.reBuilder(widget);
      },
      child: child,
    );
  }
}

```

**Comment by escamoteur** [comment]
actually I created a package for such things https://pub.dev/packages/functional_listener
