### ISSUE TITLE
analyzer_benchmark_flutter_repo_batch_maximum &  analyzer_benchmark_flutter_repo_watch_maximumregression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#40910]
Looks like the regression occurred around https://github.com/flutter/flutter/commit/c4c7e033bd8bc4ea86885f8806625923ac1d3306.

**Comment by iskakaushik** [comment]
Removing the TODAY label on this bug as we've identified that https://github.com/dart-lang/sdk/commit/e32706ec05 is the cause of this regression. The change was indeed anticipated to make analyze slower by about 20% which is what happened.

@kf6gpe if we think this is not acceptable, let's open an issue with dart to identify a solution.

**Comment by kf6gpe** [comment]
SGTM. We should still re-baseline, if this is an anticipated change.

**Comment by devoncarew** [comment]
cc @stereotype441 

I'm going to re-baseline, and work with the analyzer team to determine how we can re-coop this.

**Comment by devoncarew** [comment]
I ran into https://github.com/flutter/flutter/issues/41109 while trying to re-baseline.

**Comment by mraleph** [comment]
@devoncarew do you think this should just be closed by now? seems stale.

**Comment by devoncarew** [comment]
Yes, thanks, this can be closed.
