### ISSUE TITLE
Support "direct booking" in the current firebase Admob plug-in

### ISSUE THREAD

**Issue by zoeyfan** [flutter/flutter#40921]
Customer mentioned that it is a requirement for them to add custom ads beside those from Google, namely, direct bookings. 

However, the current firebase Admob plug-in does not support direct bookings. Direct bookings is a feature available in Double Click. Hence, customer is requesting Flutter to support either DoubleClick, or at least add this feature to existing Admob plug-in.

**Comment by zoeyfan** [comment]
@amirh FYI

**Comment by escamoteur** [comment]
All Firebase plugins are now here to find : https://github.com/FirebaseExtended/flutterfire

Please open this issue there again.

**Comment by zoeyfan** [comment]
Reopened here: https://github.com/FirebaseExtended/flutterfire/issues/192

**Comment by kroikie** [comment]
@zoeyfan

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1166. Any further collaboration will be done there.
