### ISSUE TITLE
cannot hide elevation of the appbar

### ISSUE THREAD

**Issue by itAlvy** [flutter/flutter#40939]
I need a consistent gradient color as a whole, but I can't hide the elevation of the appbar.
---

```dart
  @override
  Widget build(BuildContext context) {

    Widget regionalSelectionContainer = Container(
      decoration: BoxDecoration(
          gradient: LinearGradient(colors: [
            Color(0xff1AB99D),
            Color(0xff2E2888)
          ])
        )
      );
 
    return Scaffold(
      backgroundColor: Color(0xfff2f1f8),
      appBar: GradientAppBar(
        gradientStart: Color(0xff1AB99D),
        gradientEnd: Color(0xff2E2888),
        elevation: 0, // -----------invalid------------
        title: Text('Regional Selection', style: TextStyle(fontSize: 14)),
        centerTitle: true,
      ),
      body: Container(child: regionalSelectionContainer,)
    );
  }
```
![Snipaste](https://user-images.githubusercontent.com/34973898/65298320-a2409280-db9d-11e9-84b7-4a7a5d615f3e.png)

**Comment by sma** [comment]
`GradientAppBar` is not a standard Flutter component. You should probably ask [here](https://github.com/joostlek/GradientAppBar).

**Comment by itAlvy** [comment]
> `GradientAppBar` is not a standard Flutter component. You should probably ask [here](https://github.com/joostlek/GradientAppBar).

 Thank you. but `GradientAppBar` just copy, no modification

**Comment by BondarenkoStas** [comment]
@itAlvy Please provide your flutter doctor -v and also specs what the emulator you use.

**Comment by janmoppel** [comment]
Hello @itAlvy !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.

**Comment by sahq-azhar** [comment]
Hello
Did anyone get the solution for this?
