### ISSUE TITLE
Can we use 'vw', 'vh' and so on when setting widget size?

### ISSUE THREAD

**Issue by gzf6** [flutter/flutter#40944]
## Use case

As we all know, if we want the flutter app to run on a high resolution device, we must handle the size If we want to get a correct proportion. For example, handle the size by the flutter_screenutil package. Or we can calculate ’vw‘ by the following method:

`1vw = window.physicalSize.width / window.devicePixelRatio / 100`

We can define a function like this to use it in everywhere:

```
double vw(double widthPer) {
  return widthPer * 1vw ;
}

Future main() {
  runApp(MyApp());
}

// some widget
Container(
  width: vw(50);
);
```

## Proposal

So can we have a built-in unit like ’vw‘?  Then we can use it like this:

```
Container(
  width: 50vw;
);
```

**Comment by dblokhin** [comment]
Your proposal is about the Dart syntax not a Flutter issue.
