### ISSUE TITLE
Unable to run flutter web, its working fine on android

### ISSUE THREAD

**Issue by Parmendrakumar** [flutter/flutter#40941]
I am on master build and unable to run flutter web. I have followed  https://flutter.dev/docs/get-started/web

TerminalLog:
```
Exception: Unable to connect to Chrome debug port: 58487
 SocketException: OS Error: The remote computer refused the network connection.
, errno = 1225, address = localhost, port = 58495
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      ChromeLauncher._connect (package:flutter_tools/src/web/chrome.dart:139:9)
<asynchronous suspension>
#2      ChromeLauncher.launch (package:flutter_tools/src/web/chrome.dart:120:12)
<asynchronous suspension>
#3      ChromeDevice.startApp (package:flutter_tools/src/web/web_device.dart:134:36)
<asynchronous suspension>
#4      ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:176:20)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:480:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:527:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#24     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#25     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#26     IosProject.isSwift (package:flutter_tools/src/project.dart)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#33     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#34     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#38     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#41     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)


Building application for the web...                                24.5s
Failed to build application for the web.
PS C:\Users\e01699\web\web1>


DebugLog:
Launching lib\main.dart on Chrome in debug mode...
Exception: Unable to connect to Chrome DevTools.
#0      throwToolExit  (package:flutter_tools/src/base/common.dart:28:3)
#1      ChromeLauncher.launch.<anonymous closure>  (package:flutter_tools/src/web/chrome.dart:116:11)
#2      _rootRun  (dart:async/zone.dart:1120:38)
#3      _CustomZone.run  (dart:async/zone.dart:1021:19)
#4      Future.timeout.<anonymous closure>  (dart:async/future_impl.dart:767:33)
#5      _rootRun  (dart:async/zone.dart:1120:38)
#6      _CustomZone.run  (dart:async/zone.dart:1021:19)
#7      _CustomZone.runGuarded  (dart:async/zone.dart:923:7)
#8      _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:963:23)
#9      _rootRun  (dart:async/zone.dart:1124:13)
#10     _CustomZone.run  (dart:async/zone.dart:1021:19)
#11     _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:947:23)
#12     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:21:15)
#13     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:382:19)
#14     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:416:5)
#15     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)


Failed to build application for the web.
Exited (sigterm)
```

**Comment by Parmendrakumar** [comment]
PS C:\Users\e01699\web\web1> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.6-pre.19, on Microsoft Windows [Version 10.0.17763.379], locale en-IN)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[√] Android Studio (version 3.4)
[√] VS Code (version 1.38.1)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

**Comment by BondarenkoStas** [comment]
@Parmendrakumar Tried as in the guide, it worked, buy I tried on Mac. It seems to be a network issue, maybe the localhost is blocked, or Chrome can't reach localhost.
Does `dart --observe <script>.dart` print something like 
`Observatory listening on http://127.0.0.1:8181/M1K0DBd3DOo=/`?

**Comment by Parmendrakumar** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
PS C:\Users\e01699\web\web1> flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Exception: Unable to connect to Chrome debug port: 63550
 SocketException: OS Error: The remote computer refused the network connection.
, errno = 1225, address = localhost, port = 63555
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      ChromeLauncher._connect (package:flutter_tools/src/web/chrome.dart:139:9)
<asynchronous suspension>
#2      ChromeLauncher.launch (package:flutter_tools/src/web/chrome.dart:120:12)
<asynchronous suspension>
#3      ChromeDevice.startApp (package:flutter_tools/src/web/web_device.dart:134:36)
<asynchronous suspension>
#4      ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:176:20)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:480:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:527:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#24     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#25     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#26     IosProject.isSwift (package:flutter_tools/src/project.dart)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#33     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#34     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#38     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#41     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)


Building application for the web...                                15.6s
Failed to build application for the web.
PS C:\Users\e01699\web\web1>

**Comment by Parmendrakumar** [comment]
I am  able to run flutter web app when its separate, But getting issue when Mobile and web has merged, Its fresh template.

**Comment by Parmendrakumar** [comment]
PS C:\Users\e01699\web\flutterapp> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.6-pre.29, on Microsoft Windows [Version 10.0.17763.379], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Chrome - develop for the web
[√] Android Studio (version 3.4)
[√] VS Code (version 1.38.1)
[√] Connected device (2 available)

• No issues found!

**Comment by BondarenkoStas** [comment]
@Parmendrakumar What do you mean exactly? Do you mean the issue occured after flutter/flutter_web was moved to flutter/flutter?

**Comment by Parmendrakumar** [comment]
Do you mean the issue occured after flutter/flutter_web was moved to flutter/flutter? Yes
localhost is not reachable
PS C:\Users\e01699\web\flutterapp> flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Exception: Unable to connect to Chrome debug port: 51228
 SocketException: OS Error: The remote computer refused the network connection.
, errno = 1225, address = localhost, port = 51232

**Comment by Parmendrakumar** [comment]
PS C:\Users\e01699\web\flutterapp> flutter build web
Compiling lib\main.dart for the Web...                             61.8s
PS C:\Users\e01699\web\flutterapp> flutter devices
2 connected devices:

Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
Server • web    • web-javascript • Flutter Tools
PS C:\Users\e01699\web\flutterapp>

**Comment by Parmendrakumar** [comment]
App with command: flutter run -d web
