### ISSUE TITLE
Widget CheckBox default color

### ISSUE THREAD

**Issue by virskor** [flutter/flutter#40943]
Any method to modify default checkbox color?

I am using checkbox on dark mode.
Black color will be unfriendly to my user.

![F45CBF8F-FEC6-47F1-8EFD-A7CF3FE0691E](https://user-images.githubusercontent.com/16968535/65301518-8099d800-dbaa-11e9-8653-8a364be1f595.png)

## Use case
If you are using dark mode, check box should support modify default color black to any color you want to use.

## Proposal
CheckBox(
   color: Colors.white, //// modify default color if user not selected
);

**Comment by sma** [comment]
On dark schemes (if `brightness` is set to `Brightness.dark`) Flutter automatically uses light gray. If you want to change this color, override `unselectedWidgetColor` in your `ThemeData`.

**Comment by dblokhin** [comment]
I guess the `CheckBox` color is `secondary` color according to Materil specs.
So to change the `CheckBox` color change it in the your Theme or use widget scope theming:
```dart
         Theme(
              data: ThemeData(accentColor: Colors.red),
              child: Checkbox(
                value: true,
                onChanged: _onChanged,
              ),
            ),
```

**Comment by virskor** [comment]
@sma @dblokhin Thank you very much, I will close this issue.
