### ISSUE TITLE
android studio 3.5  flutter dart plugins not compatible

### ISSUE THREAD

**Issue by feng562925462** [flutter/flutter#40946]

**Comment by BondarenkoStas** [comment]
@feng562925462 Please provide more information, which exactly plugins? Can you paste the error message?

**Comment by janmoppel** [comment]
Hello @feng562925462 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
