### ISSUE TITLE
White on white is hard to see with tab selection indicator

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4094]
The default color for the tab selection indicator is white, and the default color for the background is also white (or very close to white). The tab indicator gets lost against the background.

## Steps to Reproduce

Run the Flutter Gallery
Select Components
Select Tabs
Notice this result:

![flutter_01](https://cloud.githubusercontent.com/assets/7953123/15449099/f5efbf30-1f28-11e6-8b3e-87a3be52ba6b.png)

**Comment by HansMuller** [comment]
The tab indicator color is specified by the theme. So you should  be able to wrap your TabBar with
```
new Theme(
  themeData: new ThemeData(indicatorColor: yourIndicatorColor),
  child: yourTabBar,
)
```

**Comment by abarth** [comment]
ThemeData doesn't inherit, so you'd probably want to start with the current theme as a base and use `themeData.copyWith(indicatorColor: yourIndicatorColor)` to make a copy with the new indicator color.  Unfortunately, `themeData.copyWith` doesn't exist yet.  ;)

**Comment by HansMuller** [comment]
https://github.com/flutter/flutter/issues/4096

**Comment by HansMuller** [comment]
I suppose an indicatorColor TabBar parameter would be a simpler way to enable this.

**Comment by abarth** [comment]
Yeah, we should have that too.

**Comment by jimbeveridge** [comment]
I really like the color scheme shown on this page under Surfaces and shadows:
http://android-developers.blogspot.com/2014/08/material-design-in-2014-google-io-app.html
