### ISSUE TITLE
Local_auth : user can dismiss the dialog without authenticating.

### ISSUE THREAD

**Issue by Theo6890** [flutter/flutter#40958]
Hello,

Local_auth allows the app to use the phone's biometrics. 

There is a parameter called **stickyAuth** but it only sticks the dialog if the user open another app on the top or if he gets a phone call. It does not prevent the user hiding the dialog when he taps outside. 

I need to display the dialog no matter what until the user uses his biometrics. How can I do that?

**Comment by escamoteur** [comment]
Hi,
please add the output of `flutter doctor` also please tell us which version of `local_auth` you are using.
On which Platform does this happen?

Thanks

**Comment by Theo6890** [comment]
First of all, thanks for the answer !
I am using **local_auth: 0.6.0**. I also forgot to tell that I tried to use the  **stickyAuth** parameter in the basic project example **flutter\...\local_auth-0.6.0**

Here is the doctor -v
`[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.17763.737], locale en-US)
    • Flutter version 1.9.1+hotfix.2 at C:\flutter
    • Framework revision 2d2a1ffec9 (13 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\thr\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Users\thr\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.5791312\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Users\thr\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\183.5522156
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\thr\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.5791312
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Users\thr\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-1\192.6603.28
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[√] Connected device (1 available)
    • POCO F1 • 57b60ae4 • android-arm64 • Android 9 (API 28)
`

**Comment by escamoteur** [comment]
Does this only happen on Android?

**Comment by Theo6890** [comment]
Yes it happens on Android. The new title resume it perfectly.

**Comment by TahaTesser** [comment]
Hi @Theo6890 
Are you still experiencing this issue with latest stable?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @Theo6890 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
