### ISSUE TITLE
How to add if and else condition for container in flutter( for margin and bottom)?

### ISSUE THREAD

**Issue by chethangowda08** [flutter/flutter#40959]

**Comment by dblokhin** [comment]
Use stackoverflow for questions like that and close the issue.

**Comment by chethangowda08** [comment]
Not der in stackoverflow...

**Comment by chethangowda08** [comment]
if u want to reply ,answer me or else dont comment.....

**Comment by escamoteur** [comment]
Please ask such question on stackoverflow or reddit. Thanks
