### ISSUE TITLE
Provider with futurebuilder not working properly for me in statefulwidget

### ISSUE THREAD

**Issue by JayM96** [flutter/flutter#40957]
Hello,
[provider.txt](https://github.com/flutter/flutter/files/3635398/provider.txt)

Currently I am working in an app.

I have added provider in that app. but, i don't know how to use futurebuilder in stateful management without continuously firing future attribute.

Also, I want to add circular progress indicator while initialising, no data found message when fetch data is null. otherwise i will display data.

But, I am not able to found proper way to do it. Can you please do that thing in one of my future builder demo ?

Can anybody please suggest me a best way using provider in statefulwidget using futurebuilder and consumer attached for the file attached code.

**Comment by dblokhin** [comment]
Close the issue and use stackoverflow for questions like that.
Looking at your question I think you don't really need a Statefull widget for wrapping `FutureBuilder`.
In short my suggestion for you case is `StatelessWidget` like this:
```dart
class FutureBuilderApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("FutureBuilder App"),
      ),
      body: FutureBuilder<List<User>>(
        future: _getUserData(),
        builder: (context, snapshot) {
          // You must check the error first
          if (snapshot.hasError) return ErrorWidget(snapshot.error);
          if (!snapshot.hasData) return const LoadingWidget();
          
          // the data widget
          // some thing code here...
        },
      ),
    );
  }
}
```
Note that if your future returns `null` for some reasons it will be loading always. You should make sure that you future never returns `null`. For example, if there is empty user list then it should return List: `[]`, not the `null`.
