### ISSUE TITLE
Switching to an old version leaves the flutter tool on an unknown channel

### ISSUE THREAD

**Issue by talisk** [flutter/flutter#40950]
## Use case

The latest version on stable channel of Flutter is 1.9.1+hotfix.2. Our team are maintaining two Flutter Projects which use different version of Flutter at the same time.

For example, there's two projects named A and B. A's Flutter version is 1.7.8+hotfix.4 and B's Flutter version is 1.9.1+hotfix.2. 

Now Flutter environment is 1.9.1+hotfix.2 on the MacPro and building for Project A is successful. And then I run 'flutter version v1.7.8+hotfix.4' and 'flutter doctor', now the output shows 'Channel unknown, v1.7.8+hotfix' but not 'Channel stable'. If now I run 'flutter channel stable', the Flutter will turn to 'Channel stable, v1.9.1+hotfix.2'.

## Proposal

User can jump to an old version with stable channel.

**Comment by zanderso** [comment]
The `version` command is putting the repo in a detached HEAD state. Ideally, the `version` command would retain the current branch.

@zoeyfan I'm not sure this should be customer critical since the functionality that is being looked for here can be replicated with the right git commands, which one of us will suggest after verifying that they work as expected. If the suggested workaround is effective, we can downgrade this to a feature request or 'annoyance'.

@jonahwilliams @christopherfujino @jmagman

**Comment by christopherfujino** [comment]
It looks like there is no way to do this with a `checkout`. I think the best way to do this locally would be:

```
git checkout <desired_branch> # This must have desired commit as an ancestor
git reset --hard <desired_commit_or_tag>
```

**Comment by zoeyfan** [comment]
@zanderso I agree. I think this should be a new feature request. I will change the label, and communicate it to the customer.

**Comment by talisk** [comment]
Thanks @zanderso @christopherfujino @zoeyfan 

This does not seriously affect our development. But at the beginning, `flutter version` still brought us a lot of confusion. Especially for beginners, this command does not let them switch to the appropriate version.

Now our development environment has multiple Flutter SDKs in different path. I wrote a shell script to switch them and call it in one line. This may also be a good solution.

**Comment by christopherfujino** [comment]
maybe the meta issue for this is that `flutter version` is ill-documented and confusing.

**Comment by jonahwilliams** [comment]
We've deprecated and removed flutter version, since by default its behavior is unsafe
