### ISSUE TITLE
[web]: draggable scrollbar for ScrollView widgets on desktop browser

### ISSUE THREAD

**Issue by deckerst** [flutter/flutter#40952]
The `ScrollView` widget shows a scrollbar only for visual feedback. It cannot be dragged, as is common on mobile. But desktop browser users expect to be able to scroll by dragging a thumb in the scrollbar.

A friendlier behaviour for a `ScrollView` on Flutter web would be to display a visual scrollbar on mobile, but a draggable scrollbar on desktop. Is there a plan to implement such a behaviour ?

Otherwise, should the developers check whether the app is running on desktop and if so wrap the `ScrollView` with a custom scrollbar widget (something like https://github.com/fluttercommunity/flutter-draggable-scrollbar but more native looking)?

```
[✓] Flutter (Channel dev, v1.10.5, on Mac OS X 10.14.6 18G95, locale en-KR)
    • Flutter version 1.10.5 at /Users/thibaultdeckers/projects/flutter
    • Framework revision 3cf88fed6d (30 hours ago), 2019-09-18 23:09:41 -0400
    • Engine revision 33ad6757e8
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 cb80ea7ba9)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/thibaultdeckers/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/thibaultdeckers/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/thibaultdeckers/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132
    • Server • web    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by justinmc** [comment]
I added a draggable scrollbar for iOS 13 recently: https://github.com/flutter/flutter/pull/35829

Not quite what's needed for web, but maybe some code can be shared.

**Comment by deckerst** [comment]
Thanks for the suggestion.

Just to see what works / doesn't, I tried `CupertinoScrollbar` in a web context. The long press and side grab gestures seem to be ignored on the web (Chrome desktop), even though the same code works fine on mobile (both iOS & Android).

**Comment by justinmc** [comment]
Hmm that's good to know, thanks for trying it out.  I'm not sure how gestures on different on Flutter web.

**Comment by stuartmorgan** [comment]
This appears to be the same as #31753; closing as a duplicate to consolidate discussion.

**Comment by ImDeZz** [comment]
Since there is no update from the flutter team about the scrollbar on the web, I have developed my own scrollbar, that works exactly like the basic html scrollbar.

I hope you could use it. You can check it out here:
https://hobbister.com/2020/11/24/flutter-web-scrollbar-with-generic-desktop-feel/
