### ISSUE TITLE
flutter ellipsis not working 

### ISSUE THREAD

**Issue by ashishkumar90052** [flutter/flutter#40964]
Flexible(
              child: Container(
                padding: const EdgeInsets.all(2),
                child: FittedBox(
                  fit: BoxFit.contain,
                  child: InkWell(
                    child: Center(
                      child: Text(
                        args.category,
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                    onTap: () => Navigator.of(context).pop(),
                  ),
                ),
              ),
            ),

**Comment by escamoteur** [comment]
Hi, what do you mean bei not working? Can you add a screenshot?
Could you please add the output of flutter doctor.
