### ISSUE TITLE
mac os 10.15 issue.

### ISSUE THREAD

**Issue by PrasadKavuru** [flutter/flutter#40963]
While installing the Cocoapods getting the following issue.

Updating Homebrew...
Warning: You are using macOS 10.15.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

Error: The following directories are not writable by your user:
/usr/local/share/man/man5
/usr/local/share/man/man7

You should change the ownership of these directories to your user.
  sudo chown -R $(whoami) /usr/local/share/man/man5 /usr/local/share/man/man7

And make sure that your user has write permission.
  chmod u+w /usr/local/share/man/man5 /usr/local/share/man/man7

 Please help me.

**Comment by escamoteur** [comment]
Maybe this can help? https://stackoverflow.com/questions/56572116/this-terminal-wont-let-me-run-or-install-cocoa-pods-because-i-am-on-macos-catal

**Comment by PrasadKavuru** [comment]
Working fine. Thank u.
