### ISSUE TITLE
FLAG_SECURE in main activity not preventing from capturing screen in flutter (Xiaomi-devices)

### ISSUE THREAD

**Issue by Olifemus** [flutter/flutter#40961]
```
super.onCreate(savedInstanceState)
        SurfaceView(applicationContext).setSecure(true)
        this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
        window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
        GeneratedPluginRegistrant.registerWith(this)`
```
still allowing me to capture video(not screenshots) in flutter 

Doctor summary:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale ru-RU)
    • Flutter version 1.9.1+hotfix.2 at /Users/user/Documents/flutter
    • Framework revision 2d2a1ffec9 (13 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

**Comment by Olifemus** [comment]
only Xiaomi-devices

**Comment by BondarenkoStas** [comment]
Found a similar issue #36626.

**Comment by mikeesouth** [comment]
This prevents screenshot on my phone (Huawei Mate 20 Pro) but it does not prevent screenshots for my emulated Pixel C. Or maybe the emulator screenshot button overrides this setting?

**Comment by jonataslaw** [comment]
In the current version
class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        SurfaceView(this@MainActivity).setSecure(true)
        window.setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_SECURE)
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}

Has no effect on the Motorola Z2 Force. 
I can record screen 

I use this code on the native android, and nothing is recorded, I insert it into the Flutter application, and I can record it.

**Comment by jonataslaw** [comment]
> ```
> super.onCreate(savedInstanceState)
>         SurfaceView(applicationContext).setSecure(true)
>         this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
>         window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
>         GeneratedPluginRegistrant.registerWith(this)`
> ```
> 
> still allowing me to capture video(not screenshots) in flutter
> 
> Doctor summary:
> 
> ```
> [✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale ru-RU)
>     • Flutter version 1.9.1+hotfix.2 at /Users/user/Documents/flutter
>     • Framework revision 2d2a1ffec9 (13 days ago), 2019-09-06 18:39:49 -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/user/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 10.3)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.3, Build version 10G8
>     • CocoaPods version 1.7.5
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 39.0.3
>     • Dart plugin version 191.8423
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> ```

try this on MainActivity.kt

package com.app.contatinhos

import android.os.Bundle
import android.util.Log
import android.view.SurfaceView
import android.view.View
import android.view.ViewGroup
import android.view.WindowManager
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
  
  override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    if (!setSecureSurfaceView()) {
      Log.e("MainActivity", "Could not secure the MainActivity!")
      // React as appropriate.
    }
  }

  private fun setSecureSurfaceView(): Boolean {
    val content = findViewById<ViewGroup>(android.R.id.content)
    if (!isNonEmptyContainer(content)) {
      return false
    }
    val splashView = content.getChildAt(0)
    if (!isNonEmptyContainer(splashView)) {
      return false
    }
    val flutterView = (splashView as ViewGroup).getChildAt(0)
    if (!isNonEmptyContainer(flutterView)) {
      return false
    }
    val surfaceView = (flutterView as ViewGroup).getChildAt(0)
    if (surfaceView !is SurfaceView) {
      return false
    }
    surfaceView.setSecure(true)
    this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
    return true
  }

  private fun isNonEmptyContainer(view: View): Boolean {
    if (view !is ViewGroup) {
      return false
    }
    if (view.childCount < 1) {
      return false
    }
    return true
  }
}

**Comment by MagnumDingusEdu** [comment]
> > ```
> > super.onCreate(savedInstanceState)
> >         SurfaceView(applicationContext).setSecure(true)
> >         this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
> >         window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
> >         GeneratedPluginRegistrant.registerWith(this)`
> > ```
> > 
> > 
> > still allowing me to capture video(not screenshots) in flutter
> > Doctor summary:
> > ```
> > [✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale ru-RU)
> >     • Flutter version 1.9.1+hotfix.2 at /Users/user/Documents/flutter
> >     • Framework revision 2d2a1ffec9 (13 days ago), 2019-09-06 18:39:49 -0700
> >     • Engine revision b863200c37
> >     • Dart version 2.5.0
> > 
> > [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> >     • Android SDK at /Users/user/Library/Android/sdk
> >     • Android NDK location not configured (optional; useful for native profiling support)
> >     • Platform android-29, build-tools 29.0.2
> >     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> >     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> >     • All Android licenses accepted.
> > 
> > [✓] Xcode - develop for iOS and macOS (Xcode 10.3)
> >     • Xcode at /Applications/Xcode.app/Contents/Developer
> >     • Xcode 10.3, Build version 10G8
> >     • CocoaPods version 1.7.5
> > 
> > [✓] Android Studio (version 3.5)
> >     • Android Studio at /Applications/Android Studio.app/Contents
> >     • Flutter plugin version 39.0.3
> >     • Dart plugin version 191.8423
> >     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> > ```
> 
> try this on MainActivity.kt
> 
> ```
> import android.os.Bundle
> import android.util.Log
> import android.view.SurfaceView
> import android.view.View
> import android.view.ViewGroup
> import android.view.WindowManager
> import androidx.annotation.NonNull
> import io.flutter.embedding.android.FlutterActivity
> import io.flutter.embedding.engine.FlutterEngine
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterActivity() {
>   
>   override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
>     GeneratedPluginRegistrant.registerWith(flutterEngine);
>   }
> 
>   override fun onCreate(savedInstanceState: Bundle?) {
>     super.onCreate(savedInstanceState)
>     if (!setSecureSurfaceView()) {
>       Log.e("MainActivity", "Could not secure the MainActivity!")
>       // React as appropriate.
>     }
>   }
> 
>   private fun setSecureSurfaceView(): Boolean {
>     val content = findViewById<ViewGroup>(android.R.id.content)
>     if (!isNonEmptyContainer(content)) {
>       return false
>     }
>     val splashView = content.getChildAt(0)
>     if (!isNonEmptyContainer(splashView)) {
>       return false
>     }
>     val flutterView = (splashView as ViewGroup).getChildAt(0)
>     if (!isNonEmptyContainer(flutterView)) {
>       return false
>     }
>     val surfaceView = (flutterView as ViewGroup).getChildAt(0)
>     if (surfaceView !is SurfaceView) {
>       return false
>     }
>     surfaceView.setSecure(true)
>     this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
>     return true
>   }
> 
>   private fun isNonEmptyContainer(view: View): Boolean {
>     if (view !is ViewGroup) {
>       return false
>     }
>     if (view.childCount < 1) {
>       return false
>     }
>     return true
>   }
> }
> ```
The app doesn't open at all when I use this, and crashes immediately on boot

**Comment by jonataslaw** [comment]
> > > ```
> > > super.onCreate(savedInstanceState)
> > >         SurfaceView(applicationContext).setSecure(true)
> > >         this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
> > >         window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
> > >         GeneratedPluginRegistrant.registerWith(this)`
> > > ```
> > > 
> > > 
> > > still allowing me to capture video(not screenshots) in flutter
> > > Doctor summary:
> > > ```
> > > [✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale ru-RU)
> > >     • Flutter version 1.9.1+hotfix.2 at /Users/user/Documents/flutter
> > >     • Framework revision 2d2a1ffec9 (13 days ago), 2019-09-06 18:39:49 -0700
> > >     • Engine revision b863200c37
> > >     • Dart version 2.5.0
> > > 
> > > [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> > >     • Android SDK at /Users/user/Library/Android/sdk
> > >     • Android NDK location not configured (optional; useful for native profiling support)
> > >     • Platform android-29, build-tools 29.0.2
> > >     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> > >     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> > >     • All Android licenses accepted.
> > > 
> > > [✓] Xcode - develop for iOS and macOS (Xcode 10.3)
> > >     • Xcode at /Applications/Xcode.app/Contents/Developer
> > >     • Xcode 10.3, Build version 10G8
> > >     • CocoaPods version 1.7.5
> > > 
> > > [✓] Android Studio (version 3.5)
> > >     • Android Studio at /Applications/Android Studio.app/Contents
> > >     • Flutter plugin version 39.0.3
> > >     • Dart plugin version 191.8423
> > >     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> > > ```
> > 
> > 
> > try this on MainActivity.kt
> > ```
> > import android.os.Bundle
> > import android.util.Log
> > import android.view.SurfaceView
> > import android.view.View
> > import android.view.ViewGroup
> > import android.view.WindowManager
> > import androidx.annotation.NonNull
> > import io.flutter.embedding.android.FlutterActivity
> > import io.flutter.embedding.engine.FlutterEngine
> > import io.flutter.plugins.GeneratedPluginRegistrant
> > 
> > class MainActivity: FlutterActivity() {
> >   
> >   override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
> >     GeneratedPluginRegistrant.registerWith(flutterEngine);
> >   }
> > 
> >   override fun onCreate(savedInstanceState: Bundle?) {
> >     super.onCreate(savedInstanceState)
> >     if (!setSecureSurfaceView()) {
> >       Log.e("MainActivity", "Could not secure the MainActivity!")
> >       // React as appropriate.
> >     }
> >   }
> > 
> >   private fun setSecureSurfaceView(): Boolean {
> >     val content = findViewById<ViewGroup>(android.R.id.content)
> >     if (!isNonEmptyContainer(content)) {
> >       return false
> >     }
> >     val splashView = content.getChildAt(0)
> >     if (!isNonEmptyContainer(splashView)) {
> >       return false
> >     }
> >     val flutterView = (splashView as ViewGroup).getChildAt(0)
> >     if (!isNonEmptyContainer(flutterView)) {
> >       return false
> >     }
> >     val surfaceView = (flutterView as ViewGroup).getChildAt(0)
> >     if (surfaceView !is SurfaceView) {
> >       return false
> >     }
> >     surfaceView.setSecure(true)
> >     this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
> >     return true
> >   }
> > 
> >   private fun isNonEmptyContainer(view: View): Boolean {
> >     if (view !is ViewGroup) {
> >       return false
> >     }
> >     if (view.childCount < 1) {
> >       return false
> >     }
> >     return true
> >   }
> > }
> > ```
> 
> The app doesn't open at all when I use this, and crashes immediately on boot

f you are not using the Stable branch, things have changed (on Beta/Dev/Master). Now you have the FlutterSurfaceView exposed to be able to call setSecure(true);

**Comment by MagnumDingusEdu** [comment]
> > > > ```
> > > > super.onCreate(savedInstanceState)
> > > >         SurfaceView(applicationContext).setSecure(true)
> > > >         this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
> > > >         window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
> > > >         GeneratedPluginRegistrant.registerWith(this)`
> > > > ```
> > > > 
> > > > 
> > > > still allowing me to capture video(not screenshots) in flutter
> > > > Doctor summary:
> > > > ```
> > > > [✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale ru-RU)
> > > >     • Flutter version 1.9.1+hotfix.2 at /Users/user/Documents/flutter
> > > >     • Framework revision 2d2a1ffec9 (13 days ago), 2019-09-06 18:39:49 -0700
> > > >     • Engine revision b863200c37
> > > >     • Dart version 2.5.0
> > > > 
> > > > [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> > > >     • Android SDK at /Users/user/Library/Android/sdk
> > > >     • Android NDK location not configured (optional; useful for native profiling support)
> > > >     • Platform android-29, build-tools 29.0.2
> > > >     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> > > >     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> > > >     • All Android licenses accepted.
> > > > 
> > > > [✓] Xcode - develop for iOS and macOS (Xcode 10.3)
> > > >     • Xcode at /Applications/Xcode.app/Contents/Developer
> > > >     • Xcode 10.3, Build version 10G8
> > > >     • CocoaPods version 1.7.5
> > > > 
> > > > [✓] Android Studio (version 3.5)
> > > >     • Android Studio at /Applications/Android Studio.app/Contents
> > > >     • Flutter plugin version 39.0.3
> > > >     • Dart plugin version 191.8423
> > > >     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> > > > ```
> > > 
> > > 
> > > try this on MainActivity.kt
> > > ```
> > > import android.os.Bundle
> > > import android.util.Log
> > > import android.view.SurfaceView
> > > import android.view.View
> > > import android.view.ViewGroup
> > > import android.view.WindowManager
> > > import androidx.annotation.NonNull
> > > import io.flutter.embedding.android.FlutterActivity
> > > import io.flutter.embedding.engine.FlutterEngine
> > > import io.flutter.plugins.GeneratedPluginRegistrant
> > > 
> > > class MainActivity: FlutterActivity() {
> > >   
> > >   override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
> > >     GeneratedPluginRegistrant.registerWith(flutterEngine);
> > >   }
> > > 
> > >   override fun onCreate(savedInstanceState: Bundle?) {
> > >     super.onCreate(savedInstanceState)
> > >     if (!setSecureSurfaceView()) {
> > >       Log.e("MainActivity", "Could not secure the MainActivity!")
> > >       // React as appropriate.
> > >     }
> > >   }
> > > 
> > >   private fun setSecureSurfaceView(): Boolean {
> > >     val content = findViewById<ViewGroup>(android.R.id.content)
> > >     if (!isNonEmptyContainer(content)) {
> > >       return false
> > >     }
> > >     val splashView = content.getChildAt(0)
> > >     if (!isNonEmptyContainer(splashView)) {
> > >       return false
> > >     }
> > >     val flutterView = (splashView as ViewGroup).getChildAt(0)
> > >     if (!isNonEmptyContainer(flutterView)) {
> > >       return false
> > >     }
> > >     val surfaceView = (flutterView as ViewGroup).getChildAt(0)
> > >     if (surfaceView !is SurfaceView) {
> > >       return false
> > >     }
> > >     surfaceView.setSecure(true)
> > >     this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
> > >     return true
> > >   }
> > > 
> > >   private fun isNonEmptyContainer(view: View): Boolean {
> > >     if (view !is ViewGroup) {
> > >       return false
> > >     }
> > >     if (view.childCount < 1) {
> > >       return false
> > >     }
> > >     return true
> > >   }
> > > }
> > > ```
> > 
> > 
> > The app doesn't open at all when I use this, and crashes immediately on boot
> 
> f you are not using the Stable branch, things have changed (on Beta/Dev/Master). Now you have the FlutterSurfaceView exposed to be able to call setSecure(true);

Got it. I was on the master branch. Thanks for the tip !

**Comment by malikmani** [comment]
> > ```
> > super.onCreate(savedInstanceState)
> >         SurfaceView(applicationContext).setSecure(true)
> >         this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
> >         window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
> >         GeneratedPluginRegistrant.registerWith(this)`
> > ```
> > 
> > 
> > still allowing me to capture video(not screenshots) in flutter
> > Doctor summary:
> > ```
> > [✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale ru-RU)
> >     • Flutter version 1.9.1+hotfix.2 at /Users/user/Documents/flutter
> >     • Framework revision 2d2a1ffec9 (13 days ago), 2019-09-06 18:39:49 -0700
> >     • Engine revision b863200c37
> >     • Dart version 2.5.0
> > 
> > [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> >     • Android SDK at /Users/user/Library/Android/sdk
> >     • Android NDK location not configured (optional; useful for native profiling support)
> >     • Platform android-29, build-tools 29.0.2
> >     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> >     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> >     • All Android licenses accepted.
> > 
> > [✓] Xcode - develop for iOS and macOS (Xcode 10.3)
> >     • Xcode at /Applications/Xcode.app/Contents/Developer
> >     • Xcode 10.3, Build version 10G8
> >     • CocoaPods version 1.7.5
> > 
> > [✓] Android Studio (version 3.5)
> >     • Android Studio at /Applications/Android Studio.app/Contents
> >     • Flutter plugin version 39.0.3
> >     • Dart plugin version 191.8423
> >     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> > ```
> 
> try this on MainActivity.kt
> 
> ```
> import android.os.Bundle
> import android.util.Log
> import android.view.SurfaceView
> import android.view.View
> import android.view.ViewGroup
> import android.view.WindowManager
> import androidx.annotation.NonNull
> import io.flutter.embedding.android.FlutterActivity
> import io.flutter.embedding.engine.FlutterEngine
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterActivity() {
>   
>   override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
>     GeneratedPluginRegistrant.registerWith(flutterEngine);
>   }
> 
>   override fun onCreate(savedInstanceState: Bundle?) {
>     super.onCreate(savedInstanceState)
>     if (!setSecureSurfaceView()) {
>       Log.e("MainActivity", "Could not secure the MainActivity!")
>       // React as appropriate.
>     }
>   }
> 
>   private fun setSecureSurfaceView(): Boolean {
>     val content = findViewById<ViewGroup>(android.R.id.content)
>     if (!isNonEmptyContainer(content)) {
>       return false
>     }
>     val splashView = content.getChildAt(0)
>     if (!isNonEmptyContainer(splashView)) {
>       return false
>     }
>     val flutterView = (splashView as ViewGroup).getChildAt(0)
>     if (!isNonEmptyContainer(flutterView)) {
>       return false
>     }
>     val surfaceView = (flutterView as ViewGroup).getChildAt(0)
>     if (surfaceView !is SurfaceView) {
>       return false
>     }
>     surfaceView.setSecure(true)
>     this.window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)
>     return true
>   }
> 
>   private fun isNonEmptyContainer(view: View): Boolean {
>     if (view !is ViewGroup) {
>       return false
>     }
>     if (view.childCount < 1) {
>       return false
>     }
>     return true
>   }
> }
> ```

This works for me prett fine.

**Comment by iampopal** [comment]
I am looking for a stable solution for this

**Comment by Bharavi26** [comment]
i am facing same issue **FLAG_SECURE** prevent screenshot but not preventing video recorder,
anyone have idea about prevent video record in flutter

**Comment by darshankawar** [comment]
@Olifemus 
Is this still a valid issue using latest Flutter version or has this been resolved ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by pradeep-gc** [comment]
is any way to prevent screenshot capture and recording video in iOS in flutter?
