### ISSUE TITLE
[WEB]  'DillClassBuilder' is not a subtype of type 'SourceClassBuilder'

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#40966]
Flutter 1.10.5-pre.28 • channel master • https://github.com/flutter/flutter.git
Framework • revision 6911a1513c (il y a 4 heures) • 2019-09-19 10:48:57 -0700
Engine • revision 1cada0a6dc
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 ea969c358e) 

dartdevc -k arguments: --dart-sdk-summary=/Users/robbie/INSTALL/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --modules=amd --no-summarize -o packages/path_forms/expert/individual/forms/code/code_field_state.ddc.js --source-map --summary=packages/meta/meta.ddc.dill=packages/meta/meta --summary=packages/mobx/mobx.ddc.dill=packages/mobx/mobx --summary=packages/path_forms/mobx/error_context.ddc.dill=packages/path_forms/mobx/error_context --summary=packages/path_forms/mobx/field_state.ddc.dill=packages/path_forms/mobx/field_state --packages=file:///var/folders/jl/c9_s07wd0wq2t8d2ph18vgn40000gn/T/kernel_builder_lB8vLb/.packages --module-name=packages/path_forms/expert/individual/forms/code/code_field_state --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///Users/robbie/INSTALL/flutter/bin/cache/flutter_web_sdk/libraries.json package:path_forms/expert/individual/forms/code/code_field_state.g.dart package:path_forms/expert/individual/forms/code/code_field_state.dart
dart --version: 2.6.0-dev.0.0.flutter-ea969c358e (Wed Sep 18 23:54:26 2019 +0000) on "macos_x64"

Crash when compiling null,
at character offset null:
type 'DillClassBuilder' is not a subtype of type 'SourceClassBuilder'
#0 KernelTarget.installForwardingConstructors (package:front_end/src/fasta/kernel/kernel_target.dart:469:37)
#1 KernelTarget.installSyntheticConstructors (package:front_end/src/fasta/kernel/kernel_target.dart:409:11)
#2 KernelTarget.buildOutlines. (package:front_end/src/fasta/kernel/kernel_target.dart:270:7)

#3 withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)

#4 KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:251:12)

Thanks !

**Comment by escamoteur** [comment]
@Solido there is a newer version on master. Could you try that?

**Comment by Solido** [comment]
Updated 4 hours ago. I'm on master, 2 upgrade per day. Updating now !
Web is first citizen with this project even if we use an Ipad to get faster.

**Comment by Solido** [comment]
@pavanpodila This may concern MobX too

**Comment by pavanpodila** [comment]
@Solido is it related to codegen?

**Comment by Solido** [comment]
No idea ! but it's linked to MobX Form in some way.

Maybe we should start some more simple samples to see where it fails precisely.

**Comment by pavanpodila** [comment]
Ah got it. Thanks for being the brave explorer on flutter web :-)

**Comment by escamoteur** [comment]
@Solido so we wait till you have more information

**Comment by jonahwilliams** [comment]
cc @jakemac53 this happened when we updated build_runner dependencies, not sure why yet:

https://github.com/flutter/flutter/pull/40979/files#diff-ccd13eb4cfb3b033c92487b8a9175a34

**Comment by jakemac53** [comment]
I can't think of anything specific that has changed relating to this - it seems like a kernel issue?

**Comment by jakemac53** [comment]
cc @jensjoha

**Comment by Solido** [comment]
Hi @jonahwilliams 

Updated to last master but still got is there a coming update ? 

Thank you !

```
Crash when compiling null,
at character offset null:
type 'DillClassBuilder' is not a subtype of type 'SourceClassBuilder'
#0      KernelTarget.installForwardingConstructors (package:front_end/src/fasta/kernel/kernel_target.dart:469:37)
#1      KernelTarget.installSyntheticConstructors (package:front_end/src/fasta/kernel/kernel_target.dart:409:11)
#2      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:270:7)
<asynchronous suspension>
#3      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#4      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:251:12)
```

**Comment by jensjoha** [comment]
Fixed in dart with https://github.com/dart-lang/sdk/commit/fdda2729c330ceecc926476cfb8987700c03e3c0.
