### ISSUE TITLE
ThemeData doesn't inherit from the enclosing Theme

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4096]
And a ThemeData.copyWith() method isn't provided.
https://github.com/flutter/flutter/issues/4094#issuecomment-220794182

Say someone just wanted override the current theme's indicator color....

**Comment by Hixie** [comment]
copyWith is a bit weird with this class because if you do a copyWith then override, say, primarySwatch, nothing much will happen. We might want to find a slightly more subtle approach here.

**Comment by HansMuller** [comment]
If you do a copyWith and override primarySwatch and the ThemeData you're inheriting from overrides colors based on primarySwatch, then I think the overrides should survive. Which implies that we'd have to keep track of the overrides.

**Comment by Hixie** [comment]
If we agree on the approach in https://github.com/flutter/flutter/pull/9358 then I think we should use the same approach here. That won't be a breaking change, so I'm punting this to later. Please let us know if this is important to you.

**Comment by Hixie** [comment]
Duping to https://github.com/flutter/flutter/issues/9148.
