### ISSUE TITLE
[Android 10] Unable to set transparent navigation bar

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#40974]
## Steps to Reproduce

Run the provided code on an Android 10 device. Tested on a physical Pixel 3 XL running latest Android 10 stable release.

Expected: The blue background pushes until the bottom of the screen, while the gestures bar stays floating over the app.

Result: The navigation bar is still black, the app doesn't draw until the bottom.

### Sample code

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(SampleApp());
}

class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.light(),
      darkTheme: ThemeData.dark(),
      home: Scaffold(
        backgroundColor: Colors.blue,
        body: Center(
          child: Text('Test'),
        ),
      ),
    );
  }
}
```

### Flutter doctor output
```
[√] Flutter (Channel master, v1.10.6-pre.20, on Microsoft Windows [Version 10.0.18362.356], locale es-ES)
    • Flutter version 1.10.6-pre.20 at C:\src\flutter
    • Framework revision c238045a96 (35 minutes ago), 2019-09-20 07:58:53 -0700
    • Engine revision 70f21b0edb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 7c1821c4aa)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Cristian\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Pixel 3 XL • 89PY09NNV • android-arm64 • Android 10 (API 29)

• No issues found!
```

Related to https://github.com/flutter/flutter/issues/34678

cc/ @shihaohong

**Comment by escamoteur** [comment]
`    SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);`
I think you are not passing the right value, it should either be .top or .bottom.

I close this issue if you have further problems please reopen it.

**Comment by Zazo032** [comment]
Passing .values passes both .top and .bottom, also passing .bottom or .bottom + .top results in the same behavior.

**Comment by escamoteur** [comment]
Sorry you are right, I didn't see that it accepts a List.

**Comment by shihaohong** [comment]
Hi, you're supposed to pass a list of the system UI overlays  _that you want to show_ into `SystemChrome.setEnabledSystemUIOverlays`. So, to hide the navigation bar, you have to use `SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.top])`, meaning you'd only like to display the top status bar. 

Please check to see if this works for you. Thank you!

**Comment by cpboyd** [comment]
@shihaohong 

I think what he's trying to do is something more like:

```dart
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      systemNavigationBarColor: Colors.transparent,
      systemNavigationBarDividerColor: Colors.transparent,
    ));
```

However, I'll note that setting that on my dark mode theme results in a white background beneath the `Scaffold`.

**Comment by Zazo032** [comment]
> Hi, you're supposed to pass a list of the system UI overlays _that you want to show_ into `SystemChrome.setEnabledSystemUIOverlays`. So, to hide the navigation bar, you have to use `SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.top])`, meaning you'd only like to display the top status bar.
> 
> edit: If what you're looking for is to have the app appear fullscreen (to also hide the status bar), you'd do `SystemChrome.setEnabledSystemUIOverlays([])`
> 
> Please check to see if this works for you. Thank you!

@shihaohong that solution _hides_ (you have to swipe up to enable it again) the gestures navigation bar, but the desired behavior is to make it transparent so the gestures bar "floats" over the UI. Here are the desired vs. actual screenshots explaining it for a better understanding. Also, here's a small explanation on how to achieve it, and a GIF showing the result: https://twitter.com/davey_burke/status/1126878112170405888

**Comment by shihaohong** [comment]
I think @cpboyd's suggestion achieves the effect you want, but the issue is that for some reason, Flutter apps are laid out above the navigation bar. Unfortunately, having a transparent navigation bar does not make a difference since the app is never laying out where the navigation bar is.

Some experimenting I did found me a way to remove both the system status bar and the navigation bar, but it also causes `MediaQuery.padding` to be set to zero (which will cause some layout problems with existing widgets). I'll need to figure out if: 
1) there's a way to preserve the system window padding while laying out full screen
2) there's a way to set just the nav bar or status bar to transparent, not both simultaneously

- in `{path-to-project}/android/app/src/main/java/com/example/{project_name}/`, add the following:
```
// add these imports
import android.os.Build;
import android.view.Window;
import android.view.WindowManager;

// ...

public class MainActivity extends FlutterActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    // add these lines
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
        Window window = getWindow();
        window.setFlags(
            WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,
            WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS
        );
    }
    // ...
  }
}

```

Screenshot of achieved effect
<img width="309" alt="Screen Shot 2019-09-23 at 5 59 50 PM" src="https://user-images.githubusercontent.com/27032613/65417155-feb8e180-de2b-11e9-92b6-7e5dc5244fe8.png">

**Comment by escamoteur** [comment]
@HansMuller could you please have a look at this if we have an issue here or just mistakes by the users?

**Comment by shihaohong** [comment]
Alternatively, adding 
```
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      systemNavigationBarColor: Colors.transparent,
      systemNavigationBarDividerColor: Colors.transparent,
    ));
    SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.top]);
```

to the `build` method looks good until we tap anywhere on the screen results in the navigation bar re-appearing.

**Comment by sgehrman** [comment]
Seems everyone wants this feature, but there are no simple instructions on how to get a fully transparent system navigation bar.  Anyone solved this yet?

**Comment by Zazo032** [comment]
The framework currently doesn't support it, it can't render _under_ the navigation bar to achieve that effect.

**Comment by cachapa** [comment]
@Zazo032 of course it does. Here's a screenshot of you saying that on Google photos :-)
Pixel 4 - Android 10

![image](https://user-images.githubusercontent.com/1006207/79193360-c3631c00-7e2a-11ea-9c15-119673d0f030.png)

**Comment by athornz** [comment]
Well Android supports it but I think @Zazo032 is saying Flutter doesn't.

**Comment by cachapa** [comment]
Point taken. I may have misread that.

**Comment by anik786** [comment]
@cachapa Just to add what @athornz said, the navigation bar is the buttons at the bottom (usually the back, home, and switch screens / or a gesture bar). The screenshot does not show a bottom navigation bar at all.

![image](https://user-images.githubusercontent.com/5897460/79225900-60d34580-7e55-11ea-8904-e207996af391.png)

The only things transparent in the image you uploaded from what I can see is the status bar and a bottom app bar, which can all be done in Flutter.

**Comment by cachapa** [comment]
@anik786 my screenshot is showing the navigation bar, but it's the new one in Android 10 (gesture navigation): It appears as a thin horizontal line.
The new navigation bar looks especially out of place if the background isn't transparent, which is why Google is now recommending it.

**Comment by anik786** [comment]
Oh sorry my bad. The touch gesture bar on my screen is a lot larger, hence why I was confused.

**Comment by cachapa** [comment]
No worries, I don't think anybody can be blamed for not keeping up with every change in Android

**Comment by dhruvweaver** [comment]
It should be noted that I am incredibly new to Flutter, so forgive me if this is a ridiculous suggestion. Would it be possible to do this in XML using the platform-specific files, and implementing the following?
https://developer.android.com/training/gestures/gesturenav

**Comment by o4x** [comment]
you can check [this plugin](https://pub.dev/packages/infinity_ui). It's use api to get navigation bar height ,
so after it enable and setFlags you can still get the navigation bar height.

**Comment by andrewtzhang** [comment]
@o4x That sorta works, but its really janky to work with. Having it work natively would def be preferable.

**Comment by shihaohong** [comment]
I'm not actively working on this right now, so I'm going to un-assign myself from the issue.

**Comment by GaryQian** [comment]
So we have two types of insets: `padding` and `viewInset`. Padding prevents drawing, while viewInset prevents UI elements from laying out over it. It looks like what is desired is a way for padding to remain zero while having the nav bar height applied to the viewInset.

If you look at https://github.com/flutter/engine/blob/d8b6602c3600c4fcd3336cfb78af34eed4d3a9fd/shell/platform/android/io/flutter/embedding/android/FlutterView.java#L437, We currently can only distinguish between keyboard and no keyboard, which is done using a hacky heuristic. We currently do not handle this case. I can see if there is a way to achieve this with the information we already have, but if not, we may have to add additional API. I would prefer not to however.

**Comment by Zazo032** [comment]
The framework should be able to render to the bottom of the screen (maybe even by default, like it does on iOS), and then handle the insets with `SafeArea` (again, like iOS). Not sure how can this be implemented to behave similar in both platforms.

**Comment by vvVenom** [comment]
I try to make status/navigation bar transparent by following methods:

> step 1    **src/main/res/values/styles.xml**

```xml
<item name="android:statusBarColor">@android:color/transparent</item>
<item name="android:navigationBarColor">@android:color/transparent</item>
<item name="android:windowTranslucentStatus">true</item>
<item name="android:windowTranslucentNavigation">true</item>
```

> step 2    ***Activity**

```kotlin
super.onCreate(savedInstanceState)
window.decorView.apply {
    javaClass.declaredFields
        .firstOrNull { it.name == "mSemiTransparentBarColor" }
        ?.apply { isAccessible = true }
        ?.setInt(this, Color.TRANSPARENT)
}
```

At the end, i got this:
![image](https://user-images.githubusercontent.com/58068445/84908647-4df42000-b0e7-11ea-87fb-34cd74c8b679.png)
😺 

But anyway, I still hope there is a better way to solve it, rather than through reflection [DecorView](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/com/android/internal/policy/DecorView.java#L213)

**Comment by not-holar** [comment]
@vvVenom does this make flutter automagically lay stuff out behind the navbar or is some additional trickery required?

**Comment by vvVenom** [comment]
> @vvVenom does this make flutter automagically lay stuff out behind the navbar or is some additional trickery required?

Yep, but you may also need to set transparent for flutter as @cpboyd said

**Comment by hectorAguero** [comment]
@vvVenom doesn't work well for me, it's show me a grey background on both(statusbar and navbar), would appreciate if you could create a sample repo.

**Comment by vvVenom** [comment]
> @vvVenom doesn't work well for me, it's show me a grey background on both(statusbar and navbar), would appreciate if you could create a sample repo.

I think I will take the time to create it, but before, can you tell me your device info?

**Comment by hectorAguero** [comment]
> > @vvVenom doesn't work well for me, it's show me a grey background on both(statusbar and navbar), would appreciate if you could create a sample repo.
> 
> I think I will take the time to create it, but before, can you tell me your device info?

I test with flutter beta branch, on Pixel 2 XL with Android 11 and also on Android Studio Emulator with Android 10 (Pixel 2)

**Comment by KermitTheFrogerino** [comment]
@vvVenom Your trick doesn't work for me either. I'm trying it with the Pixel 3 Emulator API 29 and with my Oneplus 7 Pro with Android 10. The status bar is fully transparent while the navigation bar is translucent. I've set "systemNavigationBarColor" and "systemNavigationBarDividerColor" to Colors.transparent.

When trying to consume the insets in the activity with "insets.consumeSystemWindowInsets()", flutter stops detecting all of the insets but the navbar is transparent.

**Comment by markusaksli-nc** [comment]
Reproducible on the latest master `1.22.0-2.0.pre.59`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-2.0.pre.59, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-2.0.pre.59 at C:\Development\flutter_master
    • Framework revision be7c7faee6 (7 hours ago), 2020-08-24 22:31:02 -0400
    • Engine revision 8107b36c7b
    • Dart version 2.10.0 (build 2.10.0-56.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```
</details>

**Comment by NickM-27** [comment]
> I try to make status/navigation bar transparent by following methods:
> 
> > step 1    **src/main/res/values/styles.xml**
> 
> ```
> <item name="android:statusBarColor">@android:color/transparent</item>
> <item name="android:navigationBarColor">@android:color/transparent</item>
> <item name="android:windowTranslucentStatus">true</item>
> <item name="android:windowTranslucentNavigation">true</item>
> ```
> 
> > step 2    ***Activity**
> 
> ```kotlin
> super.onCreate(savedInstanceState)
> window.decorView.apply {
>     javaClass.declaredFields
>         .firstOrNull { it.name == "mSemiTransparentBarColor" }
>         ?.apply { isAccessible = true }
>         ?.setInt(this, Color.TRANSPARENT)
> }
> ```
> 
> At the end, i got this:
> ![image](https://user-images.githubusercontent.com/58068445/84908647-4df42000-b0e7-11ea-87fb-34cd74c8b679.png)
> 😺
> 
> `Reference`
> https://stackoverflow.com/questions/56608171/how-to-make-flutter-app-draw-behind-android-navigation-bar-and-make-navigation-b
> 
> But anyway, I still hope there is a better way to solve it, rather than through reflection [DecorView](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/com/android/internal/policy/DecorView.java#L213)

Instead of reflection I believe this accomplishes the same thing:
``` kotlin
try {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q && this is Activity)
            window.isNavigationBarContrastEnforced = false
    } catch (e: NoSuchMethodError) {
    }
```

**Comment by cachapa** [comment]
@NickM-27 the question is, can you draw below the navigation bar?
The problem with the other solutions given here is that the bar may be transparent but the Flutter framework refuses to draw 
under it. An easy way to test it is to create a container with a background color different from the one in your app's theme and see if it's drawn all the way to the bottom of the screen.

**Comment by NickM-27** [comment]
> @NickM-27 the question is, can you draw below the navigation bar?
> 
> The problem with the other solutions given here is that the bar may be transparent but the Flutter framework refuses to draw 
> 
> under it.
> 
> An easy way to test it is to create a container with a background color different from the one in your app's theme and see if it's drawn all the way to the bottom of the screen.

Yeah, it worked just fine for me, I have a scrolling list drawing below the bar no problem. I just needed Scaffold(resizeToAvoidBottomInsets = false);

**Comment by KermitTheFrogerino** [comment]
@NickM-27 Awesome! I'm gonna try it rn 🙂

**Comment by KermitTheFrogerino** [comment]
@NickM-27 compileSdkVersion is set to 29 which is when the "isNavigationBarContrastEnforced" void was introduced but I can't seem to find / use the function. Any ideas why?

**Comment by NickM-27** [comment]
@KermitTheFrogerino it was giving me trouble too, I'm still trying to figure that part out now. But the drawing behind the bar still works there's just the semitransparent overlay.

**Comment by KermitTheFrogerino** [comment]
@NickM-27 
`AnnotatedRegion<SystemUiOverlayStyle>(
      sized: widget.sized,
      child: widget.child,
      value: SystemUiOverlayStyle.dark.copyWith(
        statusBarColor: Colors.transparent,
        systemNavigationBarColor: Colors.transparent,
        systemNavigationBarDividerColor: Colors.transparent,
      ),
    ),`
This made the navbar translucent but not fully transparent

**Comment by KermitTheFrogerino** [comment]
@NickM-27 I fixed the error by removing old API v28 versions and now it detects "isNavigationBarContrastEnforced"

**Comment by NickM-27** [comment]
@KermitTheFrogerino Damn, that's frustrating

**Comment by shatterball** [comment]
Any word on drawing behind the system navigation bar?

**Comment by not-holar** [comment]
https://github.com/flutter/flutter/issues/69999#issuecomment-739510272

**Comment by goderbauer** [comment]
I just tried this on my phone. When I run the app from the following gist on the latest master of Flutter it appears to do what I would expect:

https://gist.github.com/goderbauer/e435f9290211b180d2eb98344007b2c1


https://user-images.githubusercontent.com/1227763/106822941-ed453380-6634-11eb-973a-c010b550b16c.mp4

Is there anything we're still missing?

**Comment by cachapa** [comment]
@goderbauer from my testing in latest master, this works in your case because of the line: `SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.top]);`

The issue is that it also causes the navigation bar to start invisible, and the first tap to be ignored (it exits "overlay mode" and brings the navigation bar back).

Removing that line reverts to the previous behaviour, where the navigation bar isn't transparent.

**Comment by goderbauer** [comment]
@cachapa Thanks for the explanation. I see that now too in my example. As other's have pointed out, as a work around you can call the Andorid API's from the Java/Kotlin side of your Flutter application for now. I've uploaded an example for that here: https://github.com/goderbauer/scratchpad/commit/fb5c97d3ecadf6c48bff20b5a8d83f8b19226070. But yeah, we should come up with a way to easily configure this from Flutter land.

**Comment by cachapa** [comment]
@goderbauer thanks a lot for your update. I tested it here and your solution seems to work well.

I changed two things though:
1. You're setting the navigation bar color in the Android code as `window.navigationBarColor = 0` but that can be moved to Flutter instead: `systemNavigationBarColor: Colors.transparent` as you had in your original solution.
2. Adding the androidx dependency bumped my method count over the limit which required another dependency just so I could use multidex (ugh, now I remember why I dislike Android native dev). I just imported the code for `setDecorFitsSystemWindows` from androidx and avoided the hassle.

**Comment by rydmike** [comment]
Thanks @goderbauer et co for looking into this. This really is an issue that has been open for a long time and being discussed in a few issues at least. I would love to see a solution that makes it possible to configure this from Flutter land as well. 

I'm going to try the solutions mentioned here as well. Previously I followed the setup discussed here: https://github.com/flutter/flutter/issues/69999#issuecomment-759579542

Worked well once I got the Android magic to work, but yes it requires Android tinkering as well and only worked with API 30 and higher, so not so useful yet. Something that works starting with API 28 would be superb, but 29 is much better than 30 already, since 30 is still barely used.

---

Regarding the experiment in https://github.com/flutter/flutter/issues/69999#issuecomment-759579542 the right GIF show a slider adjusting the transparency in a `systemNavigationBarColor: myColor.withOpacity(x)` when x hits **0** then we get a translucent scrim applied instead, so the nav bar is no longer fully transparent, whereas a color with an opacity very close to zero, will look fully transparent.

**Comment by Piinks** [comment]
I think this can be done without the consumed tap to bring up the navigation bar mentioned in https://github.com/flutter/flutter/issues/40974#issuecomment-773124957

I have found that by explicitly setting the enabledSystemUIOverlays to an empty list, it appears you actually end up in a native full screen mode. When I tried this, a native pop up let me know that I was in full screen mode and could bring up navigation by swiping the edges of the screen.

I have tried this on a Pixel 2 and Pixel 4.
Please let me know if this is the desired effect. :)

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
    systemNavigationBarColor: Colors.transparent,
  ));
  // This appears to result in native full screen mode
  SystemChrome.setEnabledSystemUIOverlays([]);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: BottomNavigationBar(
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.business),
            label: 'Business',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.school),
            label: 'School',
          ),
        ],
        currentIndex: 0,
        selectedItemColor: Colors.amber[800],
        onTap: (_) {},
      ),
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

flutter doctor -v
```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.390, on macOS 11.2.3 20D91 darwin-x64, locale en)
    • Flutter version 2.1.0-13.0.pre.390 at /Users/katelovett/_github/flutter
    • Framework revision 88f2db6214 (47 minutes ago), 2021-04-01 14:54:02 -0400
    • Engine revision 2edfc020bb
    • Dart version 2.13.0 (build 2.13.0-190.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/katelovett/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio with Blaze.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Pixel 4 (mobile) • 99051FFAZ00B06 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos          • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

**Comment by LasseRosenow** [comment]
@Piinks I think this issue is not about the native fullscreen mode, but about the Edge-To-Edge mode, which is something different.

Your solution completely hides the navigationbar, but the goal was to keep the navigation bar, but make its background transparent. So that the draws behind the navigation bar, but the long horizontal line for gesture navigation would still be visible

**Comment by graycatdeveloper** [comment]
try set the navBar Color(0x00010000) instead of Colors.transparent
