### ISSUE TITLE
Unexpected error occur

### ISSUE THREAD

**Issue by KyawKyawThar** [flutter/flutter#40985]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by KyawKyawThar** [comment]
Someone can explain me, why was i face this problem

**Comment by BondarenkoStas** [comment]
@KyawKyawThar Unfortunately, this report does not have any actionable information - it’s not clear if this is a bug in user code, a bug in the framework, or something else entirely.
Please feel free to comment and I will re-open if you can add the following information:
The version of Flutter you’re using
The output of flutter doctor -v
The full exception you see
A minimal reproduction that leads to this exception.
