### ISSUE TITLE
[google_maps_flutter] Marker InfoWindow title text is not visible on iOS 13 with Dark Mode enabled

### ISSUE THREAD

**Issue by RyanRamchandar** [flutter/flutter#40982]
## Steps to Reproduce

![bug](https://user-images.githubusercontent.com/3187342/65343824-99e75800-db9b-11e9-80c2-46ad69756652.png)

Tested on Simulator and iPhone XS w/ iOS 13.

1. Enable Dark Mode in settings.
2. Run sample code, tap Marker. InfoWindow title will be blank (white text on white bg)
3. Disable Dark Mode in settings.
4. Click Marker again. Text appears normally.

Note: InfoWindow snippet appears correctly in either mode:

![image](https://user-images.githubusercontent.com/3187342/65344040-314cab00-db9c-11e9-82a3-4abf366f4d02.png)

## Code to reproduce

**main.dart**
```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

const LOCATION = LatLng(45.423733, -75.6987);

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: GoogleMap(
      initialCameraPosition: CameraPosition(target: LOCATION, zoom: 16),
      markers: {
        Marker(
            markerId: MarkerId('test'),
            position: LOCATION,
            infoWindow: InfoWindow(title: 'I am a marker!'))
      },
    ));
  }
}
```

Google Maps plugin version
```yaml
google_maps_flutter:
    dependency: "direct main"
    description:
      name: google_maps_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.21+2"
```

**flutter doctor**
```
[✓] Flutter (Channel dev, v1.10.5, on Mac OS X 10.14.6 18G95, locale en-CA)
    • Flutter version 1.10.5 at /Users/ryan/Documents/flutter
    • Framework revision 3cf88fed6d (2 days ago), 2019-09-18 23:09:41 -0400
    • Engine revision 33ad6757e8
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 cb80ea7ba9)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ryan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.4

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 440E0415-7103-44C6-8254-E1BEF94943E3 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

! Doctor found issues in 1 category.
```

**Comment by RyanRamchandar** [comment]
@mklim @iskakaushik

**Comment by mklim** [comment]
@escamoteur, which `customer: ` label should be applied here?

**Comment by RyanRamchandar** [comment]
Also tested on Android 10 emulator w/ Dark Theme enabled and the InfoWindow title text is visible as expected.

![image](https://user-images.githubusercontent.com/3187342/65345096-12034d00-db9f-11e9-8311-b44ac2920eb8.png)

**Comment by escamoteur** [comment]
I don't always add one. Only if its obvious. Am 20.09.2019 18:59 schrieb Michael Klimushyn <notifications@github.com>:@escamoteur, which customer:  label should be applied here?

**Comment by mklim** [comment]
@escamoteur got it, thanks. In that case I'm going to remove the label following [Issue hygiene](https://github.com/flutter/flutter/wiki/Issue-hygiene#customers):

> (Bugs marked "customer blocker" or "customer critical" must have the corresponding customer label as well, so that we know who is actually asking for the issue.)

**Comment by evertonfoz** [comment]
It worked. Thanks

**Comment by escamoteur** [comment]
What did you change?

**Comment by RyanRamchandar** [comment]
@evertonfoz were you able to get the example working?

**Comment by evertonfoz** [comment]
@escamoteur I updated Xcode to the latest version and ios to version 13

**Comment by evertonfoz** [comment]
@RyanRamchandar Yes, I updated XCode and iOS and just copied the @escamoteur code. I was just in doubt to change InfoTitle to a color that is displayed in dark mode

**Comment by RyanRamchandar** [comment]
@evertonfoz can you post your flutter doctor -v

**Comment by evertonfoz** [comment]
Sure @RyanRamchandar 

[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale pt-BR)
    • Flutter version 1.9.1+hotfix.2 at /Users/evertoncoimbradearaujo/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/evertoncoimbradearaujo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by RyanRamchandar** [comment]
@evertonfoz how were you able to get around #37699 and deploy to a device on flutter stable branch (1.9.1+hotfix.2)? I had to switch to the dev branch to even just deploy to my phone. I am thinking this might be reason for the missing InfoWindow text.

**Comment by evertonfoz** [comment]
Hello @RyanRamchandar . To run on iOS I used 1.9. But I was having various version issues for android and on another machine, I needed to change the branch to dev too. But it was related to versions of Kotlin and Gradle. Some like this https://stackoverflow.com/questions/54693595/flutter-the-android-gradle-plugin-supports-only-kotlin-gradle-plugin-version-1

**Comment by escamoteur** [comment]
@RyanRamchandar #37699  should be fixed with the latest master. please give it a try and report back.

**Comment by evertonfoz** [comment]
Hello @RyanRamchandar and @escamoteur . Now I was trying to deploy to an iPhone XR, with iOS 13 and the #37699 problem appeared.

I opened the project in XCode and it worked.

I returned to Android Studio and the #37699 error continued.

Perform flutter upgrade and still it was no use.

Do I need to change the branch to dev?

**Comment by escamoteur** [comment]
could you please give it a try from VS code? This is pretty strange and should be solved although there seems to be another problem with the XR does this https://github.com/flutter/flutter/issues/40448 look familiar?
Have you tried it with another model?

**Comment by evertonfoz** [comment]
@escamoteur The problem also occurs by VS Code.

Unfortunately I have no model other than XR to test. Recommend changing the branch to dev?

This was also the first problem I had with XR.

**Comment by escamoteur** [comment]
What happens if you use the Simulator? Am 23.09.2019 16:53 schrieb evertonfoz <notifications@github.com>:@escamoteur The problem also occurs by VS Code.
Unfortunately I have no model other than XR to test. Recommend changing the branch to dev?
This was also the first problem I had with XR.

**Comment by evertonfoz** [comment]
@escamoteur After the upgrade of XCode appear only simulators of Iphone 11 and with it also works.

**Comment by RyanRamchandar** [comment]
@escamoteur @evertonfoz I'll try to summarize my results here (the three test variables being flutter channel, device and IDE):

## Test Variables

Flutter channels:
- stable: Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-CA)
- dev: Flutter (Channel dev, v1.10.5, on Mac OS X 10.14.6 18G95, locale en-CA)

Devices: 
- iPhone 11 Pro Max • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
- iPhone XS • ios • iOS 13.0 (physical device)

IDEs:
- IntelliJ 2019.3 EAP (Flutter plugin: 39.0.5, Dart plugin: 193.3519.31)
- Xcode 11.0, Build version 11A420a

## Results

#### Flutter channel stable:
- iPhone 11 Pro Max (simulator)
  - IntelliJ: App launches and InfoWindow text title is _not_ visible in dark mode.
  - Xcode 11: App launches and InfoWindow text title is _not_ visible in dark mode.
- iPhone XS
  - IntelliJ: app does not run due to #37699 
  - Xcode: App launches and InfoWindow text title is _not_ visible in dark mode.

#### Flutter channel dev:
- iPhone 11 Pro Max (simulator)
  - IntelliJ: App launches and InfoWindow text title is _not_ visible in dark mode.
  - Xcode 11: App launches and InfoWindow text title is _not_ visible in dark mode.
- iPhone XS
  - IntelliJ: App launches and InfoWindow text title is _not_ visible in dark mode. However, no debugs are appearing, which I believe is #40448
  - Xcode: App launches and InfoWindow text title is _not_ visible in dark mode. However, no debugs are appearing, which I believe is #40448

**Comment by evertonfoz** [comment]
@RyanRamchandar @escamoteur I apologize for the inattention to reading in a previous post of @escamoteur 
.
I changed the channel to master and was able to deploy and install.

But the dark mode problem persists.

**Comment by RyanRamchandar** [comment]
@evertonfoz Okay, thanks for confirming that the issue still exists for you.

**Comment by RyanRamchandar** [comment]
@matthew-carroll should this issue be added to the Cupertino Dark Mode project?

**Comment by matthew-carroll** [comment]
Couldn't hurt. I'll tag it.

**Comment by davystrong** [comment]
Has any workaround been found for this Dark mode problem?

**Comment by RyanRamchandar** [comment]
@davystrong not to my knowledge.

**Comment by radvansky-tomas** [comment]
First of all infoWindow should be proper Widget
If not possible then add simple 2 Text Widgets or at least expose some styling

**Comment by RyanRamchandar** [comment]
Maps SDK for iOS v3.5.0 contains the fix for this: https://developers.google.com/maps/documentation/ios-sdk/releases#version_350_-_october_08_2019

@matthew-carroll To fix this issue the iOS maps SDK version should be bumped in the `google_maps_flutter` plugin.

**Comment by matthew-carroll** [comment]
CC @amirh for plugins and @LongCatIsLooong for Dark Mode support.

**Comment by RyanRamchandar** [comment]
@matthew-carroll this is probably a candidate for the `easy fix` label.

**Comment by rdev-software** [comment]
Any update on this ? Can you release that fix ?

**Comment by RyanRamchandar** [comment]
I would submit a PR but I don't see an obvious place to bump the version. Any hints here?

**Comment by rdev-software** [comment]
@RyanRamchandar dark mode support for iOS? Isnt about it the whole thread ?

**Comment by RyanRamchandar** [comment]
@rdev-software the fix for this issue is in the newest iOS Maps SDK: https://github.com/flutter/flutter/issues/40982#issuecomment-540235842

**Comment by rdev-software** [comment]
@RyanRamchandar yes exactly, in plugin dependency...so you need to bump it there and release new plugin version, no ?

**Comment by zerox1212** [comment]
Subscribed. I need this fix badly! Thanks for the efforts.

**Comment by rdev-software** [comment]
So, can you finally bump it, or for what we are waiting ?

**Comment by RyanRamchandar** [comment]
@rdev-software 
> so you need to bump it there and release new plugin version, no ?

https://github.com/flutter/flutter/issues/40982#issuecomment-547472072 Not sure where to bump it. If you do please open a PR.

**Comment by zerox1212** [comment]
I looked through the plugin and I can't find where the iOS Maps SDK is defined. I only found the definition in android.

**Comment by zerox1212** [comment]
On further investigation it looks like flutter adds `GoogleMaps` in the `podspec` without version restriction. So in theory if you manually run cocoa pods update you should get the latest iOS Maps SDK. I checked the podspec file on cocoa pods and it is indeed already upgraded to 3.6.0.

I do not think there is anything to add in Flutter itself.

**Comment by rdev-software** [comment]
@zerox1212 thx for clarification, I will update it today again. But I am quite sure that I am using latest version of everything and upgrading regularly and issue with dark-mode is still present. (which is obviously not a flutter fault)

**Comment by rdev-software** [comment]
@zerox1212 @RyanRamchandar Issue found. Even though you've specified GoogleMaps without version, IOS version is set to iOS8.0 (yes that ancient version). Which basically force POD to install version 2.7.0 (yes 2 years old version). So please change version to iOS9 (which is supported by latest 3.6.0)

**Comment by RyanRamchandar** [comment]
@rdev-software did you verify on your device that this fixes the issue for you?

**Comment by rdev-software** [comment]
@RyanRamchandar, yes I changed version of project to 9.0 and podspec for plugin to 9.0. Then run pod update. And now its showing info window title correctly

**Comment by zerox1212** [comment]
@rdev-software Good catch. I was actually suspicious about the `8.0` but wasn't sure of it's impact on cocoa pods. I suppose it makes sense that it impacts dependency versions, but I can't help but blame Apple for not having a real package system...

**Comment by rdev-software** [comment]
@zerox1212  there is on https://swift.org/package-manager/ just no one is using it

**Comment by Nexuist** [comment]
Can confirm I was also stuck on maps version 2.7.0 and after updating the platform to 9.0, I was able to upgrade to 3.6.0 and got my visible InfoWindow titles back :)

**Comment by xyzbilal** [comment]
> Can confirm I was also stuck on maps version 2.7.0 and after updating the platform to 9.0, I was able to upgrade to 3.6.0 and get my visible InfoWindow titles back :)

how did you update it? changing target ios version to 9  in xcode and uncommenting version line in pods didnt worked for me.

**Comment by Nexuist** [comment]
@xyzbilal Make sure you run 'pod install' after changing your platform number because pods won'd do it automatically.

**Comment by amirh** [comment]
This seems like a Google Maps SDK bug: https://b.corp.google.com/issues/137173762
seems to have been fixed in version 3.5.0, I'm closing this issue as I don't think there's an action item on the Flutter side.

**Comment by rdev-software** [comment]
@amirh except for changing platform version in plugin podspec !

**Comment by amirh** [comment]
IIUC it's not the plugin's podspec that sets the platform version, but it's the application's Podfile.
I think this is normally coming from this template: https://github.com/flutter/flutter/blob/cce445e278584589d072e21a84bbf1e8d511efc9/packages/flutter_tools/templates/cocoapods/Podfile-ios-objc

I'm not sure whether we want to make the default required platform >=9.0 as long as Flutter supports 8.0... I guess a potentially reasonable thing to do is to set platform to a higher version by default and have the developers that actually need to support lower platforms manually change the requirement. Another overlooked aspect of this is the size of our test matrix (we're currently testing on CI targeting 8.0 which is probably not what we want to do). I'll file a separate issue for the default/CI target platform discussion.

**Comment by rdev-software** [comment]
Supporting iOS8 is not reasonable, but I get your point ;)

**Comment by zerox1212** [comment]
I have to agree with @rdev-software . Devices in the wild on iOS 8 has got to be less than .1%?

**Comment by Nexuist** [comment]
@amirh You have the perfect solution by defaulting to iOS 9 and allowing devs that need lower versions to set it manually. I think it is an acceptable tradeoff to have to deal with this bug if you need to support 5 year old operating systems. I'm not sure if Apple still even provides iOS 8 simulator images.

**Comment by chickenblood** [comment]
> This seems like a Google Maps SDK bug: https://issuetracker.google.com/issues/137173762
> seems to have been fixed in version 3.5.0, I'm closing this issue as I don't think there's an action item on the Flutter side.

Has this change made it into google_maps_flutter Flutter yet? I still don't see it.

**Comment by RyanRamchandar** [comment]
Because the google_maps_flutter podspec has a default required platform of 8.0 it will not grab the newest Google Maps iOS SDK which has this fix.

See here for reasons not to upgrade the podspec platform version https://github.com/flutter/flutter/issues/40982#issuecomment-555275801

**Comment by chickenblood** [comment]
Is there a workaround then? Do I just edit the Podfile manually?

**Comment by RyanRamchandar** [comment]
> Is there a workaround then? Do I just edit the Podfile manually?

That should work. @rdev-software did this and it worked for them:
https://github.com/flutter/flutter/issues/40982#issuecomment-554095441

Please report back if it worked for you.

**Comment by rdev-software** [comment]
@chickenblood @RyanRamchandar Yes you can manually set iOS version and edit pod. But thats not how its should be done. I explained that in my post, that supporting iOS8 will only bring more problems. General rule is to support current + last 2 versions. iOS13,12,11 (and I can understand support for iOS10, as there are not many changes between 10,11). Anyhow even if so, than you shouldnt specify version in PODspec and therefore force google pod to download old version!

**Comment by chickenblood** [comment]
@rdev-software I don't follow you. 'Supporting iOS8 will only bring more problems'. But that is what Flutter is already doing by default right?

'you shouldnt specify version in PODspec and therefore force google pod to download old version!'

My intention is to specify a *higher* version so that  the newer Google Maps SDK will be downloaded in order to get rid of this bug. Of course I need to remove this workaround as soon as Flutter catches up and drops iOS8 support.

**Comment by rdev-software** [comment]
@chickenblood by supporting I dont mean that you cannot use old versions of flutter/plugins.
But we should use semantic versioning to stop at certain version. Like many iOS/Android plugins. 

So you will select for example ^8.0.0 version for google maps plugin, which will be for iOS8, will have old iOS POD etc...but rest of us can bump up to ^13.0.0 and use latest iOS etc.

Its really weird that plugin will specify iOS version, specially not for plugin like google maps, which is updated like every month :D

**Comment by chickenblood** [comment]
@rdev-software  You lost me. I have no interest in supporting iOS8, just fixing this bug.

**Comment by rdev-software** [comment]
not you @chickenblood , but owners of google maps flutter plugin

**Comment by chickenblood** [comment]
Gotcha. I'm still not clear on *exactly which file* I need to edit.

**Comment by rdev-software** [comment]
@chickenblood you need to change your iOS project version (open in xcode, click on runner project and change version) and then I've changed podspec iOS version of google maps plugin, deep in pods project

**Comment by chickenblood** [comment]
I have tried the following:

**Open** <flutter install path>/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.21+8/ios/google_maps_flutter.podspec

**Change** the value of **s.ios.deployment_target** from '8.0' to '9.0'

**Set iOS Deployment Target in your Xcode project** to something  >= 9.0

**In <your project directory>/ios** pod install

Clean and rebuild Flutter project.

Still doesn't work.

**Comment by lukepighetti** [comment]
Won't that fix get obliterated next time you run `pub get` ?

**Comment by zerox1212** [comment]
From the Apple developer email:
>Apps for iPhone or iPad must be built with the iOS 13 SDK or later and use an Xcode storyboard to provide the app’s launch screen. Deadline June 30, 2020.
