### ISSUE TITLE
Update Flutter protobuf package dependency to latest version

### ISSUE THREAD

**Issue by Jimicy** [flutter/flutter#40989]
https://pub.dev/packages/protobuf
The current version of the dart protobuf library is 0.14.3

https://github.com/flutter/flutter/search?q=protobuf+0&unscoped_q=protobuf+0
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/pubspec.yaml
It looks like the version tracked here is protobuf: 0.14.1

Not sure if this is relevant. Looking at the git history, it looks like there was an effort to update the packages. But it was reverted.
https://github.com/flutter/flutter/commit/57c319a9a0c687c4e0b3f64edf16cd39a42a82b5
Revert "Run `flutter update-packages --force-upgrade`.

**Comment by Jimicy** [comment]
@zanderso

**Comment by zanderso** [comment]
Assigning to @digiter to close when package update relands and sticks

**Comment by jonahwilliams** [comment]
We'll need to pin the `package:build` dependencies. If that keeps us on a lower version of protobuf, well there isn't much we can do without fixing build_web_compiler

**Comment by digiter** [comment]
Fixed.
