### ISSUE TITLE
Skipping compiling flutter_web_demo|web/main.dart with dart2js because some of its transitive libraries have sdk dependencies that not supported on this platform:

### ISSUE THREAD

**Issue by Andylove1314** [flutter/flutter#40996]
Skipping compiling flutter_web_demo|web/main.dart with dart2js because some of its
transitive libraries have sdk dependencies that not supported on this platform:

**Comment by johnpryan** [comment]
@Andylove1314 can you provide more information?

**Comment by yjbanov** [comment]
This issue is tracked here: https://github.com/flutter/flutter/issues/39998
