### ISSUE TITLE
StreamBuilder should retain data through state-change(dispose/createState)

### ISSUE THREAD

**Issue by JAicewizard** [flutter/flutter#40991]
## Use case
Widgets might get unmounted and remounted at times, it just happens(eg: listbuilder).
When a Streambuilder gets unmounted its data is lost. This reduces the thought required to reason about Streambuilder. Usually Streambuilders are very easy to reason about, but it retaining state would reduce the debugging/reasoning required to find the cause of issues (when the Streambuilder rebuild with the initial data after being removed from and added back into the tree).

## Proposal

To make streambuilder more seamless, and make the Streambuilder behave more like a stateless widget.

**Comment by goderbauer** [comment]
Within a listview you can use the "keep alive" feature to avoid getting unmounted. If that's not an option, you need to move the state higher up in the widget tree.
