### ISSUE TITLE
when the android process exits, `flutter logs` should exit as well

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#41]
From https://github.com/flutter/tools/issues/109:

When the android process exits, flutter logs should exit as well. Right now the process will continue to run; it should exit (probably with a code of 0).

**Comment by Hixie** [comment]
What if the user goes into the Android recent tasks list and reselects the app?

**Comment by eseidelGoogle** [comment]
I don't think this still applies.  @devoncarew is working on a new mode for flutter run --resident anyway.
