### ISSUE TITLE
Switching tabs doesn't animate

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#410]
When you switch tabs it's supposed to animate the page in from the left or right. See also #68.

See: http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsY1JuWnJGSHpiQkE/components-tabs-typesoftabs_scrollable_tabs_01_xhdpi_003.webm

**Comment by abarth** [comment]
Hans did this.
