### ISSUE TITLE
Flutter not finding connected iOS device

### ISSUE THREAD

**Issue by carlleeswanson** [flutter/flutter#41006]
I used to be able to connect to my iPhone 6 Plus for testing/debugging. However, for the past several weeks I have been working just with the iOS simulator (& Android emulator). Now flutter no longer sees the iPhone when it is connected.  

Unfortunately, during the intervening weeks I have upgraded iOS (now 12.4.1), MacOS (now 10.14.6), & Flutter (now 1.9.1+hf2). So no clues as to which (if any) caused the break.
Also, just FYI, I am using VSCode (1.38.1) & Xcode (10.3) on a MacMini (2012).

The phone is connected via USB. It is visible/accessible to iTunes and Xcode, but not Flutter. I have tried disconnecting, rebooting both the Mac and the iPhone, and reconnecting (using various USB ports) all to no avail. So it seems to be a Flutter configuration issue or bug...

I've scoured the docs for info but haven't found anything useful. Flutter doctor doesn't provide me with much help either. Output is:
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Development/tools/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by christopherfujino** [comment]
@carlleeswanson can you try `rm -rf /Development/tools/flutter/bin/cache; flutter doctor -v` and see if that fixes it? There was an issue with our cached artifacts that I just fixed, and that could be this issue.

**Comment by carlleeswanson** [comment]
Yes, that resolved it! Thanks so much @christopherfujino!

As you probably know, this triggered a re-download of the Dart SDK and flutter tool rebuild.

I also had to stop/re-launch VS Code in order for it to see the device. On re-launch, VS Code had to download additional iOS tools as well.

For others' reference, I have included the output below. Note that my download times are unusually long because my network connection was being throttled at the time of download. Should be much faster for those with a normal speed internet connection.

FROM FLUTTER DOCTOR
-------------------------
$ rm -rf /Development/tools/flutter/bin/cache
$ flutter doctor -v
Downloading Dart SDK from Flutter engine b863200c37df4ed378042de11c4e9ff34e4e58c9...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  263M  100  263M    0     0   162k      0  0:27:47  0:27:47 --:--:--  165k
Building flutter tool...
Downloading Material fonts...                                      12.2s
Downloading android-arm-profile/darwin-x64 tools...                19.9s
Downloading android-arm-release/darwin-x64 tools...                15.7s
Downloading android-arm64-profile/darwin-x64 tools...              20.4s
Downloading android-arm64-release/darwin-x64 tools...              19.8s
Downloading android-x86 tools...                                        
  167.1s (!)                                       
Downloading android-x64 tools...                                        
  176.2s (!)                                       
Downloading android-arm tools...                                   89.4s
Downloading android-arm-profile tools...                           49.1s
Downloading android-arm-release tools...                           39.1s
Downloading android-arm64 tools...                                 97.0s
Downloading android-arm64-profile tools...                         55.3s
Downloading android-arm64-release tools...                         39.5s
Downloading Gradle Wrapper...                                       3.3s
Downloading package sky_engine...                                  11.1s
Downloading common tools...                                       102.1s
Downloading common tools...                                             
  122.2s (!)                                       
Downloading darwin-x64 tools...                                         
  379.4s (!)                                       
Downloading libimobiledevice...                                     4.0s
Downloading usbmuxd...                                              3.0s
Downloading libplist...                                             2.8s
Downloading openssl...                                             13.5s
Downloading ideviceinstaller...                                     2.7s
Downloading ios-deploy...                                           4.5s
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Development/tools/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Carl’s iPhone • c634ce90eef5364b7c13961bccd0001339eb28a5 • ios • iOS 12.4.1

• No issues found!

FROM VSCODE
---------------
Downloading ios tools...                                          268.8s (!)
Downloading ios-profile tools...                                  212.4s (!)
Downloading ios-release tools...                                  141.0s (!)
Running "flutter pub get" in lapis_flutter...                       1.8s
Launching lib/main.dart on Carl’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: xxxxxxxxxxx
Xcode build done.                                           71.5s

**Comment by albertpeiro** [comment]
FYI This fixed my issue, coming from exactly same context (upgrades)

**Comment by edgarfroes** [comment]
Can confirm that it works.

**Comment by FlyingToddler** [comment]
I have this same issue and have tried @christopherfujino's solution, but it didn't work for me. My Flutter Doctor output is below. Basically, the iOS tools do not download. E.g. folder "ios-deploy" in bin/cache is empty.

### FROM FLUTTER DOCTOR

Checking Dart SDK version...
Downloading Dart SDK from Flutter engine bdc9708d235e582483d299642ad8682826ebb90d...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...
Downloading Material fonts...                                       0.6s
Downloading Gradle Wrapper...                                       0.5s
Downloading package sky_engine...                                   0.2s
Downloading common tools...                                         0.5s
Downloading common tools...                                         0.5s
Downloading windows-x64 tools...                                    1.3s
Downloading android-arm-profile/windows-x64 tools...                0.2s
Downloading android-arm-release/windows-x64 tools...                0.2s
Downloading android-arm64-profile/windows-x64 tools...              0.2s
Downloading android-x64-profile/windows-x64 tools...                0.2s
Downloading android-x64-release/windows-x64 tools...                0.2s
[√] Flutter (Channel master, v1.13.6-pre.44, on Microsoft Windows [Version 10.0.18362.535], locale en-GB)
    • Flutter version 1.13.6-pre.44 at C:\src\flutter
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

    • Android SDK at C:\src\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\src\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\Anders Ojgaard\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

**Comment by christopherfujino** [comment]
@FlyingToddler debugging on iOS devices is only supported on macOS, as we depend on Xcode.

**Comment by AhmedPro2013** [comment]
> @carlleeswanson can you try `rm -rf <flutter_repo_directory>/bin/cache; flutter doctor -v` and see if that fixes it? There was an issue with our cached artifacts that I just fixed, and that could be this issue.

thx it worked!

**Comment by JamesKarl** [comment]
> @carlleeswanson can you try `rm -rf <flutter_repo_directory>/bin/cache; flutter doctor -v` and see if that fixes it? There was an issue with our cached artifacts that I just fixed, and that could be this issue.

works for me. thank you!

**Comment by haifzhan** [comment]
I confirm the solution @christopherfujino shared works!

**Comment by VictorUvarov** [comment]
This issue happens for me really often, Its annoying to have to keep running that command and re downloading all the flutter tools. I am switching from real iPhone and iPad devices. @christopherfujino

**Comment by avinashk369** [comment]
go to Xcode->preferences->locations->set value for command Line tools.
CLT reference was missing there, giving the CLT value solved the issue for me.

**Comment by anhduong28** [comment]
> go to Xcode->preferences->locations->set value for command Line tools.
> CLT reference was missing there, giving the CLT value solved the issue for me.

work for me

**Comment by siddakumarpatil** [comment]
> go to Xcode->preferences->locations->set value for command Line tools.
> CLT reference was missing there, giving the CLT value solved the issue for me.

Thanks Man! This Worked for me!!

**Comment by jinfagang** [comment]
Not work for me. I still can not found my iPhone

**Comment by jinfagang** [comment]
```
→ flutter devices                                                                          ⎇  master ✔ |5a5078c
1 connected device:

macOS (desktop) • macos • darwin-x64 • Mac OS X 10.15.7 19H1030 darwin-x64
```

<img width="275" alt="Screen Shot 2021-05-04 at 6 36 29 PM" src="https://user-images.githubusercontent.com/21303438/116991823-b6e88480-ad07-11eb-8f58-3ba8813af3b3.png">

while Xcode can

**Comment by jeffreywolberg** [comment]
> go to Xcode->preferences->locations->set value for command Line tools.
> CLT reference was missing there, giving the CLT value solved the issue for me.

Great! Solved it for me, while clearing the cache did not. Flutter only didn't recognize my device after I used an external disc along with my mac. Perhaps that had something to do with it. Anyways, this fixed it. Cheers!
