### ISSUE TITLE
typo in codelab about the fat arrow tip

### ISSUE THREAD

**Issue by a14n** [flutter/flutter#4100]
In the codelab https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..%2Findex#7 there's a little typo :

>Tip: In Dart syntax, the fat arrow function declaration `=> expression;` is shorthand for `{ return expression };`.

should be

>Tip: In Dart syntax, the fat arrow function declaration `=> expression;` is shorthand for `{ return expression; }`.

Note the position of the semicolon.

**Comment by sethladd** [comment]
Thanks for the report!

cc @collinjackson @qchong

**Comment by qchong** [comment]
Fixed in the doc source. Refreshed codelab instructions are published [here](https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..%2Findex#7).
