### ISSUE TITLE
Allow formatting from stdin with flutter format

### ISSUE THREAD

**Issue by natebosch** [flutter/flutter#41011]
The flutter SDK doesn't expose the `dartfmt` command and users are expected to run `flutter format`. In the Dart vim plugin we format files by piping them through `stdin` instead of formatting in place. Can we add an option, maybe by specifying the input file as `--`, to accept input from stdin and write the formatted result to stdout?

See https://github.com/dart-lang/dart-vim-plugin/issues/80#issuecomment-480427574

**Comment by zanderso** [comment]
The `dartfmt` invocation is here:
https://github.com/flutter/flutter/blob/8b2993337acf2ec9517060ce62e530e6c6746366/packages/flutter_tools/lib/src/commands/format.dart#L65

Adding an option to `flutter format` that takes the tool's `stdin` and adds it to the `stdin` stream of the `dartfmt` subprocess should be straightforward.

**Comment by tfinlay** [comment]
Hi. I'm interested in doing this as my first contribution to an open source project.

I have cloned a fork of the flutter repo, where should I go from here?

**Comment by zanderso** [comment]
@tfinlay thanks for your interest. However, since `dartfmt` is now exposed by Flutter next to the `flutter` CLI as `dart format`, I believe this issue may be obsolete. I'll close this, but @natebosch can re-open if I'm mistaken.

**Comment by natebosch** [comment]
Yes, the `dart format` command looks like it should work. Thanks!
