### ISSUE TITLE
DropDownButton is not working properly

### ISSUE THREAD

**Issue by Abosrie** [flutter/flutter#41021]
After I updated Flutter to **v1.10.4** the DropDownButton is not working properly.
I have to tab _long-press twice_ so the menu can be visible.

Is there anyone facing the same issue? Is there any fix for this?

<img width="373" alt="Screenshot 2019-09-21 at 7 19 34 PM" src="https://user-images.githubusercontent.com/34103922/65372712-1a927b00-dca6-11e9-874e-8b15483c1c84.png">

**Comment by BondarenkoStas** [comment]
@Abosrie Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by dangngocduc** [comment]
I have the same issue after update to v1.10.5

**Comment by dangngocduc** [comment]
@Abosrie, I downgrade to v1.9.0 and it working fine.

**Comment by Abosrie** [comment]
Thanks @dangngocduc! I had to downgrade the version to 1.5 again to work but I will try 1.9 too

**Comment by HansMuller** [comment]
@Abosrie - we're not seeing this bug. Please provide a test case per https://github.com/flutter/flutter/issues/41021#issuecomment-533814069

**Comment by janmoppel** [comment]
Hello @Abosrie !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
