### ISSUE TITLE
USB-C only Macbook Air no devices found

### ISSUE THREAD

**Issue by rbucker** [flutter/flutter#41022]
I realize this is pretty terse and feels uncooperative unfortunately the machine with the logs is air gapped at the moment I have reasonable details that when I search for did not produce results, So please be patient.

## Steps to Reproduce

I followed the EXACT instructions step by step on both a 2012 macbook air and the current 2019 model. The physical difference is that the 2012 model has USB-A and 2019 is strictly USB-C. In order to get android phones to connect to flutter on the 2019 model I had to use a USB-A dongle. It would not work with the USB-C cable.

I was able to get the 2012 model to see the iPhone but only with itunes launched. (never 
 previously documented) 

## Logs

flutter doctor said there are no devices and everything else passes

**Comment by GustavoContreiras** [comment]
Same here. XCode recognizes my iPhone but flutter doctor -v don't.

Flutter 1.9.1+hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2d2a1ffec9 (3 weeks ago) • 2019-09-06 18:39:49 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[!] Connected device
    ! No devices available
```

**Comment by rbucker** [comment]
I have also found ```idevice_id```. The PROBLEM here is that if you do a ```flutter doctor -v --bug-report``` then open the zipfile... and grep the files for ```idevice_id``` you'll eventually find the file but the path either may not resolve or the program does not produce the correct results. This is in conflict with the brew installation of ```libimobiledevice```. That project puts the ```idevice_id``` in ```/usr/local/bin``` and not in the flutter home path.

**Comment by AMShehanAmarakoon** [comment]
Any updates on this issue?I'm having the same problem in MAC Boor Pro 2018. Cannot detect iphones in flutter projects.

**Comment by rbucker** [comment]
@AMShehanAmarakoon I have 2 solutions... [a] delete the contents of ```flutter/bin/cache```; when you ``flutter update``` is is supposed to rebuild the cache folder. [b] or you can delete flutter and reinstall. which is what I did resolving that the flutter folder was essentially static.

I think this happened because I installed flutter and then ```brew install``-ed libimobiledevices which then complained about some links and libs. Taking some course of action I must have disassociated the tools, that are deployed inside flutter, from the libs.

Someone suggested that the ```.stamp``` files in the cache folder are the thing that the flutter tools use to identify versions and that's why the entire folder needs to be deleted.

**Comment by AMShehanAmarakoon** [comment]
There is a update available from flutter today(2019-10-03). I updated the flutter package. All iphone devices seems to work fine now. @rbucker  Thank You

**Comment by BondarenkoStas** [comment]
Good, I think it's safe to close the issue. If you have new input, please comment and I will re-open it right away.

**Comment by allen1996** [comment]
Could not find my iPhone running with iOS 13.2 beta 2 (17B5068e).

**Comment by BondarenkoStas** [comment]
@allen1996 is it the same after deleting cache and upgrading flutter? is it the same in dev channel?

**Comment by allen1996** [comment]
@BondarenkoStas Yes, I have tried to upgrade flutter to dev channel and still can't find my device. When I run `flutter devices -v`, I found this
```failed with Invalid argument(s): Cannot find executable for
/Users/allen/Library/flutter/bin/cache/artifacts/libimobiledevice/idevice_id.```

**Comment by rbucker** [comment]
@allen1996 I deleted flutter directory and reinstalled it.
