### ISSUE TITLE
Flutter Driver crashing when main has async operations

### ISSUE THREAD

**Issue by jamesdixon** [flutter/flutter#41029]
Internal: b/147455985

My app has a few async operations that are initialized in `main()`. This works fine in my actual application. However, when attempting to run integration tests using Flutter Driver, the tests fail with the following error:

```
Result (on Emulators):
DriverError: Error in Flutter application: Uncaught extension error while executing tap: 'package:flutter_driver/src/extension/extension.dart': Failed assertion: line 193 pos 14: 'WidgetsBinding.instance.isRootWidgetAttached || !command.requiresRootWidgetAttached': No root widget is attached; have you remembered to call runApp()?
```

From what I can tell, Flutter Driver doesn't let the app fully initialize before running the tests. If I remove the async operation, things run as expected. 

## Steps to Reproduce

I've created a minimal reproduction in this repo: https://github.com/jamesdixon/hive_flutter_driver_issue

1. Clone the repo
2. Run `flutter drive --target=test_driver/run_app.dart`

## Logs

The log output was quite long so I pasted it into a gist here: https://gist.github.com/jamesdixon/0b4d0895f6707bdaba439b158eb1110c

```
No issues found! (ran in 2.3s)
```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/jamesdixon/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jamesdixon/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jamesdixon/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPhone 7 Plus • 790FC845-4FE6-49C0-8B15-09E3BE74FA3F • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
```

**Comment by earyzhe** [comment]
Also getting this issue

**Comment by bgetsug** [comment]
Same issue here...my current workaround is to add some `sleep()`:

```dart
//...
setUpAll(() async {
    driver = await FlutterDriver.connect();

    await sleep(Duration(seconds: 10));

   // more setup...
}   
 ```

**Comment by zeucxb** [comment]
Same here!

**Comment by russell-sf** [comment]
Since the call to await in main defers the creation of the app, the flutter driver starts up immediately and starts running tests. Problem is the app may not be fully initialized since the awaited call could still be in flight. That's why adding the delay before running your tests fixes the problem.

Flutter should not start the tests until runApp is actually called.

**Comment by jonahwilliams** [comment]
To fix this, the driver bindings could be updated to send a handshake single to the command line test. Then FlutterDriver.connect could be updated to wait for this signal before beginning


DriverBinding: https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/extension/extension.dart#L45

**Comment by msmaromi** [comment]
Sometimes I got this also

**Comment by matejhocevar** [comment]
@jonahwilliams can you give more instructions on how to update `FlutterDriver.connect` in order for Flutter driver to work with async main?

**Comment by jonahwilliams** [comment]
connect would need to wait for a firstFrame event or similar event from when the Widget tree is attached. I'm not quite sure what the exact approach would be

**Comment by bionara** [comment]
I can't seem to get mine working - even putting the sleep i get the same error:
```[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:64294/dKJMCZxaNc0=/
[trace] FlutterDriver: Isolate found with number: 420724065357151
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[warning] FlutterDriver: Flutter Driver extension is taking a long time to become available. Ensure your test app (often "lib/main.dart") imports "package:flutter_driver/driver_extension.dart" and calls enableFlutterDriverExtension() as the first call in main().

```

I tried the enableFlutterDriverExtension in main, but that didn't do anything; furthermore, this actually stopped it working on my teammate's machine!

**Comment by Boehrsi** [comment]
I also encountered this and tried to avoid hardcoded waiting times. I create a Gist (https://gist.github.com/Boehrsi/93c26371431367a639476a3a860ead60) which works well for me. Feel free to give it a try, hopefully it helps you too.

**Comment by jiahaog** [comment]
I'm currently looking into this as well because it affects internal clients. (b/147455985)

**Comment by jerseysu** [comment]
I am also encountering this issue, any luck for fixing it?

**Comment by jiahaog** [comment]
This has been fixed with the above two PRs, you should be able to call `await driver.waitUntilFirstFrameRasterized()` after `FlutterDriver.connect()` directly without the looping workaround mentioned in https://github.com/flutter/flutter/issues/41029#issuecomment-611416884 if you're expecting to do heavy work before `runApp` in your application main.

**Comment by amreniouinnovent** [comment]
@jiahaog Flutter 1.17.5 not working is your fix on the stable branch?

**Comment by jiahaog** [comment]
I don't think so, you'll have to wait a bit for it to hit stable 🙂

**Comment by urmilshroff** [comment]
I'm facing this issue with the newly released [integration_test](https://pub.dev/packages/integration_test) package as well.

Adding `await sleep(Duration(seconds: 10));` in my `setUpAll()` or `testWidgets()` methods doesn't work, and since I'm not using the old `FlutterDriver` method, I'm a bit stuck.

**Comment by fernandocerkal** [comment]
> I'm facing this issue with the newly released [integration_test](https://pub.dev/packages/integration_test) package as well.
> 
> Adding `await sleep(Duration(seconds: 10));` in my `setUpAll()` or `testWidgets()` methods doesn't work, and since I'm not using the old `FlutterDriver` method, I'm a bit stuck.

Me too.
I have been faced the same issue using integration_test.
I tried put "sleep" in all methods without success. 

**integration_test.dart:**
`import 'package:integration_test/integration_test_driver.dart';

Future<void> main() => integrationDriver();`

**app.dart:**
`import 'package:com.unclewash.partnerapp/common/core/locator.dart';
import 'package:com.unclewash.partnerapp/main.dart';
import 'package:flutter/material.dart';
import 'package:flutter_driver/driver_extension.dart';

Future<void> main() async {
  // This line enables the extension.
  enableFlutterDriverExtension();
  WidgetsFlutterBinding.ensureInitialized();

  setupLocator();
  
  runApp(MyApp());
}`

**app_test.dart:**
`// Imports the Flutter Driver API.
import 'dart:io';
import 'package:com.unclewash.partnerapp/common/core/locator.dart';
import 'package:flutter_driver/flutter_driver.dart';
import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:test/test.dart';

//import 'package:flutter_test/flutter_test.dart';

import 'workaround.dart';

void main() {
   
  print('group');
  group("All test", (){
    print("All test");
    final loginPage = find.byValueKey('LoginPage');
    final login = find.byValueKey('_loginFieldKey');
    final password = find.byValueKey(Key('_passwordFieldKey'));
    final join = find.text('Entrar');

    FlutterDriver driver;
    IsolatesWorkaround workaround;

    Future<bool> isPresent(SerializableFinder byValueKey, {Duration timeout = const Duration(seconds: 1)}) async {
      try {
        await driver.waitFor(byValueKey, timeout: timeout);
        return true;
      } catch (exception) {
        return false;
      }
    }

    // Connect to the Flutter driver before running any tests.
    setUpAll(() async {      
      driver = await FlutterDriver.connect();       
      workaround = IsolatesWorkaround(driver);
      await workaround.resumeIsolates();
      await driver.waitUntilFirstFrameRasterized();
      
      
      if (!await Directory('screenshots').exists()) {
        await Directory('screenshots').create();
      }
    });

    // Close the connection to the driver after the tests have completed.
    tearDownAll(() async {
      if (driver != null) {
        await driver?.close();
        await workaround.tearDown();
      }
    });
    
    test('check flutter driver health', () async {
      Health health = await driver.checkHealth();
      print(health.status);
    });

    test("Login", () async {
      print('login..');
      await sleep(Duration(seconds: 5));
      await driver.waitFor(loginPage);
      
      setupLocator();
      await driver.waitFor(login);
      await driver.tap(login);
      await driver.enterText("luiz@unclewash.com");
      await driver.tap(password);
      await driver.enterText("Brasil123");
      
      
      await driver.tap(join);   

      await driver.waitFor(find.text("Serviços"));     
      
    }); 

     //test("Add Services", () async {});
  });
}

 Widget buildTestableWidget(Widget widget) {
   return MediaQuery(data: MediaQueryData(), child: MaterialApp(home: widget));
 }`

**pubspec.yaml:**
`dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: 
  integration_test:`

**flutter doctor -v:**
`[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.5 at /home/luiz/Development/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/luiz/Android/Sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /home/luiz/Development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/luiz/Development/android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!`

**command line:**
`flutter drive --driver=test_driver/integration_driver.dart --target=test_driver/app.dart`

**console output:**
`Using device Android SDK built for x86.
Starting application: test_driver/app.dart
Installing build/app/outputs/flutter-apk/app.apk...                 0.8s
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        16.2s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 0.8s
I/flutter ( 3357): Observatory listening on http://127.0.0.1:42497/d6xnCTDB5vc=/
E/FlutterFcmService( 3357): Fatal: failed to find callback
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:39509/d6xnCTDB5vc=/
VMServiceFlutterDriver: Isolate found with number: 955153920992255
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
VMServiceFlutterDriver: Connected to Flutter application.
Unhandled exception:
FormatException: Unexpected character (at character 1)
No requestData Extension registered
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1271:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:936:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
#4      JsonDecoder.convert (dart:convert/json.dart:505:36)
#5      JsonCodec.decode (dart:convert/json.dart:156:41)
#6      Response.fromJson (package:integration_test/common.dart:59:52)
#7      integrationDriver (package:integration_test/integration_test_driver.dart:73:38)
<asynchronous suspension>
#8      main (file:///home/luiz/projects/ewash/ewashPartnerApp/code/src/app/test_driver/integration_driver.dart:3:24)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Stopping application instance.
Driver tests failed: 255`

**Comment by fernandocerkal** [comment]
I/flutter ( 5443): Observatory listening on http://127.0.0.1:38955/uy7RO1jCdyE=/

VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:39733/uy7RO1jCdyE=/

**Comment by fernandocerkal** [comment]
Guys, I solved this changing 'package:test/test.dart' to flutter_test.dart

**Comment by SherlockShoe** [comment]
I am still having this issue on the most recent dev build. My app.main method has several async tasks and the test starts while there is still "Starting Test..." on the device screen. If I add a manual wait I can avoid the issue but that feels very wrong.
