### ISSUE TITLE
Expanded JSON documentation is needed for local storage

### ISSUE THREAD

**Issue by EcoGames** [flutter/flutter#41025]
I've come here to write about the need for expanded JSON file documentation. I know we have the [read and write files docs](https://flutter.dev/docs/cookbook/persistence/reading-writing-files) and the [JSON and serialization docs](https://flutter.dev/docs/development/data-and-backend/json) but maybe a section for specifically reading and writing JSON files instead of just .txt files since I mean, for local storage, those aren't great. For those of us who don't want to use Firebase since it's kind of expensive for small developers like myself, the ability to use the device itself for app data storage is a lifesaver. I know about `SharedPreferences` but that isn't good for big data. This would also be perfect for a new Codelab. I know a lot of other developers who are slamming their heads on their desks on using local storage with JSON files in Flutter. Typical Android development has great support for JSON files, and Flutter needs that too.

**Comment by EcoGames** [comment]
For further information, the documentation would include some of the same steps taken in the [read and write files docs](https://flutter.dev/docs/cookbook/persistence/reading-writing-files) like in the steps of creating the file itself. However, you can't write to a JSON file like a text file. By use of the `dart:convert` library, encoding JSON data is pretty easy.

The true issue is getting that encoded data into a file and reading the values from it and official documentation on creating & then handling  JSON files would really help developers like myself out with local storage instead of using a service like [Firebase](https://firebase.google.com).

**Comment by stuartmorgan** [comment]
> but that isn't good for big data

A JSON file isn't a good choice for storing large amounts of data either, since the entire file will be rewritten for every change. There are better solutions for storing significant amounts of data locally, such as SQLite, which is [already part of the cookbook](https://flutter.dev/docs/cookbook/persistence/sqlite).

Closing, since recommending JSON for storing large amounts of data isn't something we would want to do.
