### ISSUE TITLE
'package:flutter/src/material/text_form_field.dart': Failed assertion: line 117 pos 15: 'initialValue == null || controller == null': is not true.

### ISSUE THREAD

**Issue by jiharal** [flutter/flutter#41028]
final stock = TextEditingController();
TextFormField(
                      initialValue: "${product.stockAvailable}",
                      controller: stock,
                    ),

**Comment by sma** [comment]
This isn't a bug, I think. You can provide an initial value or a controller, but not both. You provided both. You probably want to use `TextFormField(controller: TextEditingController(text: "${product.stockAvailable}"))`.

**Comment by BondarenkoStas** [comment]
@jiharal This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
