### ISSUE TITLE
The image is not extracted for the build folder (flutter web & android)

### ISSUE THREAD

**Issue by mahmoudsalah37** [flutter/flutter#41026]
image not deploy in path
- build 
   - web
     - asset 
when deployed app by `flutter build web`
**note: i added photos in web folder, path in pubspec.yaml and project show correctly in debug mode**

![pubyaml](https://user-images.githubusercontent.com/31797198/65374332-c489ed00-dc3d-11e9-9160-7b6067dbfa55.PNG)

![images](https://user-images.githubusercontent.com/31797198/65374309-6c52eb00-dc3d-11e9-91da-d499d7c8e27e.PNG)

```
[√] Flutter (Channel unknown, v1.10.2-pre.40, on Microsoft Windows [Version 10.0.17134.1006], locale en-US)
    • Flutter version 1.10.2-pre.40 at C:\flutter\flutter
    • Framework revision b4ab5cfe79 (5 days ago), 2019-09-16 20:34:25 -0700
    • Engine revision 7ea9884ab0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\flutter\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\flutter\sdk
    • Java binary at: C:\flutter\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Android Studio (version 3.5)
    • Android Studio at C:\flutter\android-studio
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\Mahmoud salah eldin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132
    • Server • web    • web-javascript • Flutter Tools
```

**Comment by sma** [comment]
According to the [documentation](https://flutter.dev/docs/development/ui/assets-and-images): _Note that only files located directly in the directory are included. To add files located in subdirectories, create an entry per directory._ 

Perhaps you need to add `- assets/icons/` to your `pubspec.yaml`.

**Comment by BondarenkoStas** [comment]
Thank you @sma ! @mahmoudsalah37 Please report if you got it working. Or you are concerned about it working in debug but not working in release?

**Comment by mahmoudsalah37** [comment]
yes it is work now but why worked with debug and not with release

**Comment by TahaTesser** [comment]
Hi @mahmoudsalah37 
Based on [comment](https://github.com/flutter/flutter/issues/41026#issuecomment-533811534) and it should definitely work with release if correct paths are provided

given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by mahmoudsalah37** [comment]
Now when i write my code like below code:-
-------------------------------------------------
      assets:
         - assets/icons/
- Icons repeat again (see below photo).

![Capture](https://user-images.githubusercontent.com/31797198/75620704-aa611d00-5b94-11ea-864a-fd379c44d9dd.PNG)

But if i change path to below code:- 
--------------------------

      assets:
         - assets/

- Icons not repeat again (see below photo).

![Capture1](https://user-images.githubusercontent.com/31797198/75620753-5d317b00-5b95-11ea-936f-e4022bb28972.PNG)
