### ISSUE TITLE
Flutter Doctor [!] Proxy Configuration

### ISSUE THREAD

**Issue by aljibbs** [flutter/flutter#41034]
When I run flutter doctor i have this warning. How do I solve it?

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

**Comment by BondarenkoStas** [comment]
@aljibbs Please try to add `export NO_PROXY=localhost,127.0.0.1` to `~/.bash_profile`.

**Comment by aljibbs** [comment]
Done. Warning solved. Thanks.

**Comment by 84091829** [comment]
hello I have the same problem and did not understand how it was solved.

**Comment by 84091829** [comment]
in which file I place this code "export NO_PROXY = localhost, 127.0.0.1a ~ / .bash_profile."

**Comment by daybson** [comment]
Same doubt here! Where is this file? 
I'm using VSCode on Windows.

**Comment by dareekun** [comment]
for window you can use 'set' on cmd 
set https_proxy=hostname:port
set NO_PROXY=hostname:port

**Comment by nesteiner** [comment]
@BondarenkoStas how about using `zsh`?  
I have set the `no_proxy` in `.zshrc`, `.profile`, `/etc/profile`, but doesn't work in IDEA: Tools -> Flutter -> flutter doctor

**Comment by Eclipse-Kio** [comment]
`set NO_PROXY=localhost,127.0.0.1`  has no effect in new cmd window, how to save this configuration permanently?
