### ISSUE TITLE
[video_player] Message from debugger: Terminated due to memory issue

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#41036]
Hi all, I am 'caching' `video_player` controllers in an attempt to cache videos in a timeline. Once I get to about 750mb of cached video Flutter exits without warnings. However, looking in XCode debugger I see the following:

```
Message from debugger: Terminated due to memory issue
```

This does seem reasonable, but there are a couple issues.

1) this error was not in Flutter console, only XCode console. 
2) any chances of `video_player` native caching?
3) how do we operate near memory ceiling in Flutter apps?
4) is there any way to cache these on disk instead of in memory?

**Comment by Charles1198** [comment]
same issue!

**Comment by lukepighetti** [comment]
@Charles1198 There is a fork of `video_player` that @9999eagle is working on, I have a few open PRs so you can use mine in the meantime but hers is really the repo to watch https://github.com/999eagle/plugins/pull/2

**Comment by kf6gpe** [comment]
Strikes me that we definitely have an issue if we're not pulling the feedback from XCode.

While it's image- and not video-specific, there's been a lot of work done on our memory footprint and tooling --- see, for example, #50024, #47380, and the tooling we've wired up discussed (here)[https://flutter.dev/docs/development/tools/devtools/memory].

**Comment by maheshmnj** [comment]
Hi @lukepighetti,
Is this issue still valid with the latest ```video_player: ^2.0.8```?
Thank you.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
