### ISSUE TITLE
No devices found with name or id matching 'chrome'

### ISSUE THREAD

**Issue by amrfarid140** [flutter/flutter#41031]
## Steps to Reproduce

1. run `flutter upgrade` to get Flutter 1.9.1+hotfix.2
2. run `flutter config --enable-web`
3. run `flutter devices` and you will get `No devices detected.`
4. try to run `flutter run -d chrome` for an existing flutter web application and you will get  `No devices found with name or id matching 'chrome' `

## Flutter Doctor Output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.2.2)
[✓] VS Code (version 1.38.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by amrfarid140** [comment]
Turns out you need to be on the master channel not stable.

**Comment by rocboronat** [comment]
More info about the channels: https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

**Comment by maheshmnj** [comment]
but the flutter docs for web suggests to be on the dev channel https://flutter.dev/docs/get-started/web

**Comment by jjpaulo2** [comment]
I had the same problem after do the official Flutter getting started. I solved my problem setting an environment variable CHROME_EXECUTABLE with the path of the Chrome executable on my system.
