### ISSUE TITLE
How to let the child of PopupMenuItem take up all remaining width and height?

### ISSUE THREAD

**Issue by Martibis** [flutter/flutter#41032]
I will start off with saying, I misunderstood PopupMenuButton when I started writing my application, and added GestureDetector inside of PopupMenuItems everywhere inside my application. Only later did I realize that now only the Text inside of my GestureDetector is tappable instead of the entire PopUpMenuItem. Is there  a way to let the Text (and with that the GestureDetector) take up all available space?

`
PopupMenuButton<int>(  
                              itemBuilder: (context) =>
                              [
                                PopupMenuItem(child: GestureDetector(child: Text("Not taking up all available space"),)),
                                PopupMenuItem(child: GestureDetector(child: Text("Not taking up all available space and now the other one takes up even less"),)),
                              ]
                            )
`

**Comment by sma** [comment]
Use `Container(width: double.infinity, child: Text("..."))` to make it fill the available width of the `PopupMenuItem`. You can't get rid of the outer 16 point padding without creating your own custom `PopupMenuEntry`, though. But if you already know that using the `GestureDector` is wrong, why not remove it and use the `PopupMenuButton`s `onSelected` callback instead?

**Comment by Martibis** [comment]
> Use `Container(width: double.infinity, child: Text("..."))` to make it fill the available width of the `PopupMenuItem`. You can't get rid of the outer 16 point padding without creating your own custom `PopupMenuEntry`, though. But if you already know that using the `GestureDector` is wrong, why not remove it and use the `PopupMenuButton`s `onSelected` callback instead?

Worked like a charm, really appreciate it. The main reason for not using the onSelected at my current stage of development is because it would be way more work to change everything to work with onSelected the way my code is at the moment. In a later stage when there is more time it's something that should be done of course!
