### ISSUE TITLE
Any reason why UniqueKey has no constant constructor?

### ISSUE THREAD

**Issue by icatalud** [flutter/flutter#41043]
If possible make constant please.

**Comment by jonahwilliams** [comment]
There is no const constructor because that implies canonicalization, which would in turn remove the uniqueness. If this isn't already documented, we should add this to the unique key docstring.

**Comment by icatalud** [comment]
I just realized about that, I was using const Object() but it is equal to another const Object(). Is there any way to create const instances of an Object that are always going to be unique (ideally using empty constructor)?

I stumbled upon with symbols, however the same problems exists, if I define mySym1 = #mySym somewhere in the app and then I defined another symbol mySym2 = #mySym, mySym1==mySym2.

This is useful to guarantee uniqueness across the whole app. Of course the alternative is to not use consts.
