### ISSUE TITLE
TextField's toolbar options look very ugly

### ISSUE THREAD

**Issue by caseyryan** [flutter/flutter#41047]
Hi! 
I need to customize TextField's toolbar options view' somehow, but I just can't find a way to do it. There seems to be nothing except for boolean values that will turn some of them on and off. 
Look at this screenshot 
[Preview](https://i.ibb.co/HgytBMd/Screenshot-2019-09-22-13-21-27-219.jpg)
I need to replace the texts with icons. The problem is that those text must be in Russian, and Russian words are even longer than the English, so they won't fit the screen at all. 

Is there any way to do it? (even a hacky way will do)

 Here's the doc's stuff 
```
> $ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel dev, v1.10.0, on Microsoft Windows [Version 6.1.7601], locale ru-RU)
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [√] Android Studio (version 3.5)
> [!] IntelliJ IDEA Ultimate Edition (version 2018.1)
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
> [√] IntelliJ IDEA Ultimate Edition (version 2019.1)
> [!] VS Code (version 1.38.1)
>     X Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> [√] Connected device (1 available)
> 
> ! Doctor found issues in 2 categories.
```

**Comment by sma** [comment]
`TextField` is based on a low-level `EditableText` widget for which you can provide your own `TextSelectionControls` implementation. `TextField` chooses either a hardcoded implementation for iOS or for Android/Fuchia. In your own implementation, override `buildToolbar` and use icons instead of text.

But I agree, this could (and should) be easier to do. At least additional custom actions would be nice. On iOS this is possible by adding `UIMenuItem`s to the shared `UIMenuController`. I once tried to do this in Flutter and gave up because the feature was not worth the effort.

**Comment by caseyryan** [comment]
> `TextField` is based on a low-level `EditableText` widget for which you can provide your own `TextSelectionControls` implementation. `TextField` chooses either a hardcoded implementation for iOS or for Android/Fuchia. In your own implementation, override `buildToolbar` and use icons instead of text.
> 
> But I agree, this could (and should) be easier to do. At least additional custom actions would be nice. On iOS this is possible by adding `UIMenuItem`s to the shared `UIMenuController`. I once tried to do this in Flutter and gave up because the feature was not worth the effort.

Thanks for your reply! Sounds interesting, I'll give it a shot

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
I agree that @sma 's approach is best here.

There is an open PR that is trying to fix the overflow problem: https://github.com/flutter/flutter/pull/39624

The ability to use custom text selection menu items is an important missing feature, but no one is actively working on it yet, so it's likely a long ways from being available: https://github.com/flutter/flutter/issues/31412

I'm going to close this issue and use https://github.com/flutter/flutter/issues/31412 to track the ability to add custom items.  @caseyryan feel free to reply and reopen if you have any trouble.

**Comment by caseyryan** [comment]
> I agree that @sma 's approach is best here.
> 
> There is an open PR that is trying to fix the overflow problem: #39624
> 
> The ability to use custom text selection menu items is an important missing feature, but no one is actively working on it yet, so it's likely a long ways from being available: #31412
> 
> I'm going to close this issue and use #31412 to track the ability to add custom items. @caseyryan feel free to reply and reopen if you have any trouble.

I will probably make my own implementation and put it on github after I finish other tasks with the app

**Comment by MsXam** [comment]
Additionally - I find that when FONT size is increased via accessibility - then the ToolBarOptions that appears has overflow errors - Is there any open issue for this specific problem ?

![image](https://user-images.githubusercontent.com/18722796/72639904-96ec5080-395e-11ea-9ec4-79431e9f04cc.png)

**Comment by justinmc** [comment]
@MsXam Thanks for the clear screenshot!  https://github.com/flutter/flutter/issues/44005 is a specific issue for that, but I closed it and referenced it in the main issue about this  https://github.com/flutter/flutter/issues/35826.  I think it's probably worth it to post your screenshot in https://github.com/flutter/flutter/issues/35826 if you agree.

**Comment by MsXam** [comment]
@justinmc  Thank you ...

have uploaded image to that issue 

https://github.com/flutter/flutter/issues/35826#issuecomment-575794348

**Comment by adeolaex** [comment]
This might be old, but I've been noticing an issue with the toolbar on iOS. The title of this issue led me here. The divider isn't centred and also looks ugly.

[✓] Flutter (Channel master, 1.20.0-1.0.pre.132, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.132 at /Users/adeola/Downloads/flutter
    • Framework revision 5995661777 (5 days ago), 2020-06-19 16:15:58 -0700
    • Engine revision 676cd566f7
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/adeola/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone • 7301a50cae9aaf2e903ef313e632bfed64bb3704 • ios • iOS 13.4

• No issues found!

![IMG_C36B06593AE5-1](https://user-images.githubusercontent.com/42682873/85640163-528e7a80-b68b-11ea-81c4-6e932e891368.jpeg)

**Comment by adeolaex** [comment]
This might be old but is there a reason why the toolbar has this weird border shadow ?

[✓] Flutter (Channel master, 1.20.0-1.0.pre.132, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.132 at /Users/adeola/Downloads/flutter
    • Framework revision 5995661777 (5 days ago), 2020-06-19 16:15:58 -0700
    • Engine revision 676cd566f7
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/adeola/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone • 7301a50cae9aaf2e903ef313e632bfed64bb3704 • ios • iOS 13.4

• No issues found!
![IMG_8902](https://user-images.githubusercontent.com/42682873/85707372-68c82500-b6e3-11ea-8741-149c0fd26d8a.PNG)

**Comment by justinmc** [comment]
@adeolaex Could you open a new issue about this and mention me in it?  And if you can, please include a screenshot of the native menu as well to show the difference.  I think you're right that there's a border we should remove.

**Comment by adeolaex** [comment]
@justinmc Will do 👍
