### ISSUE TITLE
[image_picker]On iOS13 device, pickVideo does not work.

### ISSUE THREAD

**Issue by Shunsuke-Satoh** [flutter/flutter#41046]
**1.Problem**
pickVideo method returns a selected File.
But my App can not touch the File!
(file.copy(), file.readAsBytesSync() does not work.)

**2.Source code**
```
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: _showImagePicker,
          child: Text('Image Picker'),
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  void _showImagePicker() async {
    var image = await ImagePicker.pickVideo(source: ImageSource.gallery);
    print(image.path);
    print(image.statSync());
  }
}
```

**3. plist**
add below.
```
<key>NSMicrophoneUsageDescription</key>
<string>Test</string>
<key>NSCameraUsageDescription</key>
<string>Test</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>Test</string>
```

**4. yaml**
  add below.
  `image_picker: 0.6.1+4`

**5. Run And Select a File on Xcode And iOS13 device(Connected by USB)**
[MyLogs]
```
2019-09-22 14:33:29.441392+0900 Runner[789:194590] flutter: /private/var/mobile/Containers/Data/PluginKitPlugin/2D965F91-7793-48FC-966A-8850E1976AE9/tmp/trim.4A522F8F-C4BC-4910-B4CE-3DB62A292BE6.MOV
2019-09-22 14:33:29.443625+0900 Runner[789:194590] flutter: FileStat: type notFound
          changed null
          modified null
          accessed null
          mode ---------
          size -1
```
**5-a) Reason (I think)**
Because the File path contains [PluginKitPlugin]Folder.
(App have No permission for the Directory)
Like [/private/var/mobile/Containers/Data/PluginKitPlugin/xxx/tmp/trim.xxx.MOV].

**5-b) on iOS12**
On iOS12 device, works fine!
Like[/private/var/mobile/Containers/Data/Application/xxx/tmp/xxx.MOV]

**6. flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale ja-JP)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!
```

**7. Please Help ...**
Thank you for reading.

**Comment by Shunsuke-Satoh** [comment]
I think it is related to this article.

https://stackoverflow.com/questions/57798968/didfinishpickingmediawithinfo-returns-different-url-in-ios-13

**Comment by lifenautjoe** [comment]
Same issue is affecting the file_picker package.

We have a release on hold for iOS because of this 😬

**Comment by miguelpruivo** [comment]
Like @lifenautjoe reported, the `file_picker` had the same issue as the procedures to pick the video files from the gallery were the same. I've just landed a fix on the `beta` branch for the `file_picker`, if it's ok, I may PR a fix for this as well. 

You can follow the thread [here](https://github.com/miguelpruivo/flutter_file_picker/issues/141).

**Comment by miguelpruivo** [comment]
Issued a fix for this with [#2083](https://github.com/flutter/plugins/pull/2083).

**Comment by Shunsuke-Satoh** [comment]
@miguelpruivo @NikoTron
Thanks for PRs!
Surely the audience would be grateful to you too.

#2083 works fine on iOS12.4.1(iPhone6), 13.0,13.1(iPhone8).

I'm curious about the file name, but there is no problem.
on iOS13~, file name added [trim.] on file header.(Like xxx.MOV=> trim.xxx.MOV)
No problem if we pay attention to this.

I will close this issue when it is merged.

**Comment by mstorsjo** [comment]
FWIW, a different fix that seemed to work for me, when running into the same issue, is to keep a reference to the `(NSDictionary<NSString *, id> *)info` object around for as long as the url is used. This dictionary contains references to a PHAsset object, which I presume controls access to the given url - when this object is unreferenced and released, the url also becomes inaccessible at the same time.

**Comment by cs118651** [comment]
> Issued a fix for this with [#2083](https://github.com/flutter/plugins/pull/2083).

I hope the official to merge this PR as soon as possible because our application has the same problem to solve.

**Comment by alexei-g-aloteq** [comment]
Newbie question: How I can use #2083 fix do not waiting for the merge?

**Comment by Shunsuke-Satoh** [comment]
> Newbie question: How I can use #2083 fix do not waiting for the merge?

copy fixed code and paste to local imagePickerPlugin.m

1. copy fixed code
imagePickerPlugin.m L244-L261

2. paste to local imagePickerPlugin.m
you can find image_picker package class files on Xcode.
[In my case]
`Pods/Development Pods/image_picker/../../../../../../../[projectname]/ios/.symlinks/plugins/image_picker/ios/Classes/imagePickerPlugin.m`

You must  take responsible by yourself.
Be carefull of  local code when you do [pod update, install].
local code will be overwrited or not.

**Comment by ailic88** [comment]
@miguelpruivo please be aware that this fix create new issue when source is camera(not gallery).

**Comment by miguelpruivo** [comment]
@ailic88 you are right, just committed a fix. Thank you for pointing out.

**Comment by ailic88** [comment]
Hi guys,
While this PR gets merged, you can add dependency on fix like this:
```
image_picker:
    git:
      url: git@github.com:miguelpruivo/plugins.git
      path: packages/image_picker
      ref: image_picker-Fix-#41046
```

**Comment by escamoteur** [comment]
@ailic88 the URL in your sample looks a bit strange shouldn't it be 

`git://github.com/miguelpruivo/plugins.git`

**Comment by cyanglaz** [comment]
Fixed with https://github.com/flutter/plugins/pull/2083. I'm closing this issue. 
If any related issue is found after updating to 0.6.2
