### ISSUE TITLE
[video_player] Example video link is broken

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#41040]
apparently https://www.sample-videos.com went down sometime today and it doesn't look like it's coming back up. Maybe we should find a different host for example videos for `video_player` ?

**Comment by BondarenkoStas** [comment]
@lukepighetti Checked, the site is up. After all, it's just an example.

**Comment by lukepighetti** [comment]
Looks like its back up, like you said, will close. Thanks!
