### ISSUE TITLE
Do flutter have a plan to develop games?

### ISSUE THREAD

**Issue by biij5698** [flutter/flutter#41054]
The flutter have a high performance,it ability to develop games, did you teams have a plan to let flutter support develop games?

**Comment by sma** [comment]
I think, this is something the community can provide, at least for [2D games](https://pub.dev/packages/flame).

**Comment by escamoteur** [comment]
Currently there are no plans to expose 3D features from Skia to Flutter.
2D games are indeed possible.
Also Unity has ported Flutter so you can build Flutter UI in Unity.
