### ISSUE TITLE
FirebaseAdMobPlugin: kGADSimulatorID

### ISSUE THREAD

**Issue by samlotti** [flutter/flutter#41068]
Hi,

I am running admob flutter with the simulator IOS.  I see the following:
`To get test ads on this device, set: request.testDevices = @[ kGADSimulatorID ];`

The android emulators are automatically added as test devices, but it appears IOS is not.  How can we add this ID as a test device? 

There's no reference to this in the documentation.

Thank you

**Comment by janmoppel** [comment]
Hello @samlotti !

Thank you for posting an issue.
There seemed to be similar discussions on the StackOverflow: https://stackoverflow.com/questions/19527478/to-get-test-ads-on-this-device-call-request-testdevices-nsarray-arraywithob
https://stackoverflow.com/questions/39108558/admob-bannerview-request-error-no-ad-to-show

Can you please check, maybe some of the proposed solutions work for you?

Also, can you please provide an output of the `flutter doctor -v` command?

This issue may be related to the #27947 as well.

Thank you.

**Comment by samlotti** [comment]
flutter doctor -v

[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/sam/dev2/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sam/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/sam/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    • IntelliJ at /Users/sam/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 36.1.2
    • Dart plugin version 191.7830

[✓] Connected device (1 available)
    • iPhone Xʀ • D0493663-EA51-429D-90AB-4941A9D60B25 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!

**Comment by samlotti** [comment]
> Hello @samlotti !
> 
> Thank you for posting an issue.
> There seemed to be similar discussions on the StackOverflow: https://stackoverflow.com/questions/19527478/to-get-test-ads-on-this-device-call-request-testdevices-nsarray-arraywithob
> https://stackoverflow.com/questions/39108558/admob-bannerview-request-error-no-ad-to-show
> 
> Can you please check, maybe some of the proposed solutions work for you?
> 
> Also, can you please provide an output of the `flutter doctor -v` command?
> 
> This issue may be related to the #27947 as well.
> 
> Thank you.

Hi,

I looked at those and I don't believe they solve the issue.

Ideally the plugin should take care of this.  If not there should be some reference to get test device id from the plugin.

Ex:
    MobileAdTargetingInfo targetingInfo = MobileAdTargetingInfo(
      nonPersonalizedAds: nonPer,  // Need to get consent for personalized
      testDevices: <String>[
        **FirebaseAdMob.testDeviceID()**
Where the testDeviceID would return kGADSimulatorID for IOS and maybe a random guid or empty string for non IOS.

-Sam

**Comment by samlotti** [comment]
Hi,

I solved this by creating a channel and calling to get the simulator id.   This is the first time creating a channel for platform code, maybe there is a better approach.

In case others are interested, i did the following:
in the main dart class:

     static const platform = const MethodChannel('admob.support/simulatorID'); 

     if (Util.isIOS()) {
          try {
            simulatorID = await platform.invokeMethod("getSimulatorID");
            print("Simulator id: $simulatorID");
          } catch (e) {
            print("Error determing simulator id: $e");
          }
        }



In IOS AppDelegate.h

     #include <GoogleMobileAds/GADRequest.h>

 
    - (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

    // Simulator ID support
    FlutterViewController* controller = (FlutterViewController*)self.window.rootViewController;
    FlutterMethodChannel* simulatorIDChannel = [FlutterMethodChannel
                methodChannelWithName:@"admob.support/simulatorID"
                binaryMessenger:controller];

    [simulatorIDChannel setMethodCallHandler:^(FlutterMethodCall* call, FlutterResult result) {
        if ([@"getSimulatorID" isEqualToString:call.method]) {
            NSLog(@"Simulator Id = %@", kGADSimulatorID);
            return result( [NSString stringWithFormat: @"%@", kGADSimulatorID] );
        } else {
            result(FlutterMethodNotImplemented);
        }
    }];

     [GeneratedPluginRegistrant registerWithRegistry:self];
     // Override point for customization after application launch.
     return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

**Comment by kroikie** [comment]
@samlotti

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/332. Any further collaboration will be done there.

**Comment by casualcoder404** [comment]
> Hi,
> 
> I solved this by creating a channel and calling to get the simulator id. This is the first time creating a channel for platform code, maybe there is a better approach.
> 
> In case others are interested, i did the following:
> in the main dart class:
> 
> ```
>  static const platform = const MethodChannel('admob.support/simulatorID'); 
> 
>  if (Util.isIOS()) {
>       try {
>         simulatorID = await platform.invokeMethod("getSimulatorID");
>         print("Simulator id: $simulatorID");
>       } catch (e) {
>         print("Error determing simulator id: $e");
>       }
>     }
> ```
> 
> In IOS AppDelegate.h
> 
> ```
>  #include <GoogleMobileAds/GADRequest.h>
> 
> 
> - (BOOL)application:(UIApplication *)application
> didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
> 
> // Simulator ID support
> FlutterViewController* controller = (FlutterViewController*)self.window.rootViewController;
> FlutterMethodChannel* simulatorIDChannel = [FlutterMethodChannel
>             methodChannelWithName:@"admob.support/simulatorID"
>             binaryMessenger:controller];
> 
> [simulatorIDChannel setMethodCallHandler:^(FlutterMethodCall* call, FlutterResult result) {
>     if ([@"getSimulatorID" isEqualToString:call.method]) {
>         NSLog(@"Simulator Id = %@", kGADSimulatorID);
>         return result( [NSString stringWithFormat: @"%@", kGADSimulatorID] );
>     } else {
>         result(FlutterMethodNotImplemented);
>     }
> }];
> 
>  [GeneratedPluginRegistrant registerWithRegistry:self];
>  // Override point for customization after application launch.
>  return [super application:application didFinishLaunchingWithOptions:launchOptions];
> ```
> 
> }

Hey Sam I'm stuck wit this exact same issue with google_mobile_ads: ^0.12.1+1 plugin.
Do you have anymore insights or improvements/alternatives to your solution?
Thank you.

**Comment by samlotti** [comment]
Hi,

Try just setting the test id for simulator to  "Simulator".  I don't believe it ever changed and must be a constant for the admob code.  

-Sam
