### ISSUE TITLE
Android ListView.builder scroll doesn't end smoothly

### ISSUE THREAD

**Issue by VadimOsovsky** [flutter/flutter#41060]
## Steps to Reproduce

Build a list with a lot of items and fling the list with a good amount of velocity, at the end it will stop abruptly (like snapping). Oddly enough ListView.separated doesn't have this problem, it stops smoothly.

**Comment by escamoteur** [comment]
On which platform did you observe this?
Could you please provide source code or a small repro project?
Please add the output of flutter doctor

**Comment by VadimOsovsky** [comment]
@escamoteur, it happens with ClampingScrollPhysics. it's not specific to a repo, you can even see it in the gallery app, though it's hard to notice since there aren't big lists in the app, later I'll provide you with examples and flutter doctor.

**Comment by VadimOsovsky** [comment]
@escamoteur sorry for the late response, here's what I was talking about, it's not app or device specific, I experience this on multiple devices.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39897981/71344006-7ce36c00-2572-11ea-9bc3-4839fddc045a.gif)

**Comment by Gofive** [comment]
@VladyslavBondarenko hi, had this problem solved in release:1.18?

**Comment by VladyslavBondarenko** [comment]
@Gofive no, this label means "Occurs in 1.18".
I can see the difference in scrolling with native android apps, but I can't see the difference between `ListView.builder`, `ListView.separated` and `ListView`.

<details>
 <summary>code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: new ListView.builder(
            itemCount: 500,
            itemBuilder: (BuildContext context, int index) {
              return new Text(index.toString());
            }
        ),

//        body: ListView.separated(
//          separatorBuilder: (context, index) => Divider(
//            color: Colors.black,
//          ),
//          itemCount: 500,
//          itemBuilder: (BuildContext context, int index) {
//            return new Text(index.toString());
//          },
//        ),
      
//      body: ListView(
//        children: List.generate(500, (index) => Text(index.toString())),
//      ),
      ),
    );
  }
}
```

</details>

**Comment by Gofive** [comment]
@VladyslavBondarenko You can compare these two code snippets.

`import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: new ListView.builder(
            itemCount: 1000,
            itemBuilder: (BuildContext context, int index) {
              return new Text(index.toString());
            }
        ),

      //  body: ListView.separated(
      //    separatorBuilder: (context, index) => Divider(
      //      color: Colors.transparent,
      //    ),
      //    itemCount: 1000,
      //    itemBuilder: (BuildContext context, int index) {
      //      return new Text(index.toString());
      //    },
      //  ),
      ),
    );
  }
}`
They look the them, but you can see the difference when the scrolling is stopping. ListView.builder  seems stopped unnatural.

**Comment by Gofive** [comment]
`import 'package:flutter/material.dart';`

**Comment by Gofive** [comment]
You can also find this problem on CustomScrollView.

**Comment by darshankawar** [comment]
@VadimOsovsky 
I verified using your code sample on latest stable and master, but didn't notice the scroll ending abruptly. To me, the scroll was smooth.


https://user-images.githubusercontent.com/67046386/105988883-545b6900-60c6-11eb-94ae-e4a8340aaf73.mp4



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (5 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • SM A260G (mobile)      • 5200763ebcfa861f • android-arm • Android 8.1.0
      (API 27)
    • emulator-5554 (mobile) • emulator-5554    • android-x86 • Android 4.1.2
      (API 16) (emulator)

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 1.26.0-13.0.pre.177, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-13.0.pre.177 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 2eeeba9c09 (29 hours ago), 2021-01-25 20:52:30 -0800
    • Engine revision 6e391c5942
    • Dart version 2.12.0 (build 2.12.0-257.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • SM A260G (mobile)      • 5200763ebcfa861f • android-arm    • Android 8.1.0
      (API 27)
    • emulator-5554 (mobile) • emulator-5554    • android-x86    • Android 4.1.2
      (API 16) (emulator)
    • macOS (desktop)        • macos            • darwin-x64     • Mac OS X
      10.15.4 19E2269 darwin-x64
    • Chrome (web)           • chrome           • web-javascript • Google Chrome
      88.0.4324.96

! Doctor found issues in 1 category.

```

</details>

I am not sure if this is still an issue or latest behavior is expected. Can you confirm from your end using latest Flutter version ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by nt4f04uNd** [comment]
this should be fixed with https://github.com/flutter/flutter/pull/77497
