### ISSUE TITLE
Various gradle headaches

### ISSUE THREAD

**Issue by mwk24** [flutter/flutter#41066]
Sorry this is a bit vague, but it's intentionally so....

It seems like every month or so, gradle starts throwing off some new and complicated looking error. Often seems to be related to the version of flutter, android SDK, gradle, google services, kotlin etc etc, and/or the mismatch between versions. 

It just feels like an under-polished area of the flutter experience.

**Comment by escamoteur** [comment]
Can you post your error message here?
Also please add the output of flutter doctor

**Comment by mwk24** [comment]
I got it working after 4 hours or so of piecing together tips from various google searches. This is a general comment, not a specific issue - simply to say that the gradle build process seems fragile when upgrading various element of the app/framework/libraries etc. 

I would say over the last year, I've had around 10 different error messages related to this overall issue. One suggestion would be to include "build tips" with each flutter release, so people can make sure all their versions and settings are up-to-date.

**Comment by escamoteur** [comment]
Could you please still provide us with more information so that we can improve it?
What did you change? 
What problems did you have.

As a general Tipp if sich problems occur after an update, create an empty project and copy your files into it.

**Comment by mwk24** [comment]
Sounds good. I will make a list of everything I can remember.

**Comment by mwk24** [comment]
Similar class of issue: https://github.com/flutter/flutter/issues/37699

**Comment by escamoteur** [comment]
@mwk24 but #37699 is an iOS bug.

**Comment by mwk24** [comment]
Yes, I know. But it is a "build headache". I apologize, perhaps Issues is not the correct forum for what is a more general product suggestion. Either way, I would like to add that flutter is my favorite dev/design experience of all time.

**Comment by escamoteur** [comment]
Thanks
@csells

**Comment by jonahwilliams** [comment]
As is, this isn't really an actionable bug. If there are problems you are having with Gradle, it would be better to file specific issues (or better yet, find the existing ones and upvote them).
