### ISSUE TITLE
Selecting Email Account from google_sign_in during Flutter integration testing

### ISSUE THREAD

**Issue by thevzurd** [flutter/flutter#41063]
I was trying to test sign-in to my home screen for my flutter app. I am using the google-signin ( https://pub.dev/packages/google_sign_in) package from Flutter to perform login and authentication. So once the login button is pressed, a popup appears asking the user to select the user account. At that point, I am unable to control the tap as this dialog screen is generated by the plugin. How do I implement selection of the user account in this case ?

```
        test('Test Login', () async {
      final Timeline timeline = await driver.traceAction(() async {
        await driver.tap(find.byValueKey('GoogleLogin'));
        await driver.tap(find.text('myemail@gmail.com')); // This will not work !!!
      });

      TimelineSummary.summarize(timeline)
        ..writeSummaryToFile('home_scroll_perf', pretty: true)
        ..writeTimelineToFile('home_scroll_perf', pretty: true);
    });
```

In my opinion, this could be a problem when testing with any third party plugin. Please help.
https://stackoverflow.com/questions/58052343/selecting-email-account-from-google-sign-in-during-flutter-integration-testing

**Comment by escamoteur** [comment]
Sorry, this isn't a support site. I m sure you will get help at stackoverflow
