### ISSUE TITLE
support raw_keyboard_window

### ISSUE THREAD

**Issue by hayhv** [flutter/flutter#41072]
The flutter engine on Windows OS current use android keyboard map
`#static constexpr char kAndroidKeyMap[] = "android";`
Need support keyboard map for Windows OS like `raw_keyboard_linux`, `raw_keyboard_macos`

**Comment by janmoppel** [comment]
Hello @hayhv !

Thank you for posting an issue.
This may be also related to the #31945

**Comment by franciscojma86** [comment]
Closing as this is a duplicate of https://github.com/flutter/flutter/issues/37710
