### ISSUE TITLE
Column show TextField error

### ISSUE THREAD

**Issue by jinyuanqing** [flutter/flutter#41070]
`RenderBox was not laid out: RenderEditable#cce25 NEEDS-LAYOUT NEEDS-PAINT`

**Comment by janmoppel** [comment]
Hello @jinyuanqing !

Thank you for posting an issue.
Can you please also provide additional information, such as an output of the `flutter doctor -v` command and full text of the error?

Also, it would be very helpful if you could create a self-contained repository, so that your issue could be easily reproduced.

Thank you.

**Comment by jinyuanqing** [comment]
Here is the flutter doctor:

C:\Users\Administrator>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.356], locale zh-CN)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.5)
[√] VS Code (version 1.38.1)
[√] VS Code, 64-bit edition (version 1.38.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
that is ok!


Here is the code:
```
  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    //显示输入框
                    children: <Widget>[
                      Container(
                         
                        width: 300, //必须指定宽度,才能显示textfidld
                        child: TextField(
                          autofocus: true,
                          decoration: InputDecoration(
                              labelText: "usrname",
                              hintText: "username",
                              prefixIcon: Icon(Icons.person)),
                        ),
                      ),
```

if no:   Container and  width: 300,  have a error:
The following assertion was thrown while dispatching notifications for FocusNode:
Assertion failed: org-dartlang-app:///packages/flutter_web/src/rendering/box.dart:1689:12
ssert(h
"RenderBox was not laid out: RenderEditable#cde46 NEEDS-LAYOUT NEEDS-PAINT"

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

**Comment by jinyuanqing** [comment]
my project is flutter_web

**Comment by jinyuanqing** [comment]
And the input box can not enter text or Numbers, letters, etc

**Comment by TahaTesser** [comment]
Hi @jinyuanqing 
Not able to reproduce error with your code sample on latest `dev` channel on mobile or web

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-8.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-8.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision e0c63cd35e (6 days ago), 2020-04-23 22:29:01 -0400
    • Engine revision d2ec21221e
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      81.0.4044.129
• No issues found!
```

</details>

if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
