### ISSUE TITLE
how  achieve Like  Android TextView android:ellipsize="marquee" Such a function？

### ISSUE THREAD

**Issue by dev-zl** [flutter/flutter#41071]
android code:
```
<TextView
    android:singleLine="true"
    android:ellipsize="marquee"
    android:text="Still remember you said that the home is the only castle with the rice sweet river continue to run, smiling childhood dream I know"
    android:background="#ed3a37"
    android:textSize="30sp"
    android:textColor="#dadc4c"
    android:padding="10dp"
    android:focusableInTouchMode="true"
    android:marqueeRepeatLimit="marquee_forever"
    android:focusable="true"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content" />
```

**Comment by dev-zl** [comment]
flutter Would you consider supporting in [Text overflow]

**Comment by dev-zl** [comment]
Although I have implemented this feature

Would consider supporting in [Text overflow]?

**Comment by janmoppel** [comment]
Hello @dev-zl !

Thank you for posting.
Your question seems to be a good fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) as well. Flutter has a very active and helpful community there, so feel free to post it there too.

It also seems like similar question was already raised here: #40712.

Thank you.

**Comment by dev-zl** [comment]
> Hello @dev-zl !
> 
> Thank you for posting.
> Your question seems to be a good fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) as well. Flutter has a very active and helpful community there, so feel free to post it there too.
> 
> It also seems like similar question was already raised here: #40712.
> 
> Thank you.

Many thanks

**Comment by VladyslavBondarenko** [comment]
@dev-zl 
As workaround you can use 
```
SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Text(
          "Long text Long text Long text Long text Long text Long text Long text Long text Long text ",
        ),
      )
```

**Comment by Waheed388** [comment]
Simply use [Marquee](https://pub.dev/packages/marquee) plugin.
