### ISSUE TITLE
Latest Flutter master channel(1.10.6-pre.29) update won't working with new project

### ISSUE THREAD

**Issue by Yash-Aervadiya** [flutter/flutter#41077]
## Steps to Reproduce

1. `flutter channel master`
2. `flutter upgrade --force`
3. `flutter create flutter_demo_firebase_auth`
4. `cd flutter_demo_firebase_auth`
5. `flutter run`

## Logs

```
The current Dart SDK version is 2.6.0-dev.1.0.flutter-7c1821c4aa.       
                                                                        
Because every version of flutter from sdk depends on sky_engine any from sdk which requires SDK version >=1.11.0 <2.0.0, flutter from sdk is forbidden.
So, because flutter_demo_firebase_auth depends on flutter any from sdk, version solving failed.
Running "flutter pub get" in flutter_demo_firebase_auth...              
pub get failed (1)
```

```
[✓] Flutter (Channel master, v1.10.6-pre.29, on Linux, locale en_IN)
    • Flutter version 1.10.6-pre.29 at /home/drdeath/YASH/Weapons/flutter
    • Framework revision 919cc97f6a (2 days ago), 2019-09-20 14:57:05 -0700
    • Engine revision 99092a0436
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 7c1821c4aa)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /home/drdeath/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /home/drdeath/YASH/Weapons/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /home/drdeath/YASH/Weapons/android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 75.0.3770.142
    • Server • web    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by escamoteur** [comment]
Could you please post your pubspec. Yaml?

**Comment by Yash-Aervadiya** [comment]
name: 
description: An app built using Flutter for web
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  percent_indicator: "^2.1.1"
  url_launcher: ^5.1.3
  firebase: any
  provider: any
  googleapis_auth: ^0.2.3+5


  flutter:
    sdk: flutter

dependencies_overrides:
  provider:
    git:
      url: https://github.com/kevmoo/provider
      ref: flutter_web

  firebase:
    git:
      url: https://github.com/FirebaseExtended/firebase-dart

 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

**Comment by Yash-Aervadiya** [comment]
name: flutter_demo_firebase_auth
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

**Comment by escamoteur** [comment]
Did this work before or is this your first try with Flutter?

**Comment by janmoppel** [comment]
Hello @Yash-Aervadiya !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
