### ISSUE TITLE
 gesture event lost

### ISSUE THREAD

**Issue by wuyugege** [flutter/flutter#41073]
now i use flutter dev version 1.10.5
when i click on the screen, the first click lost, i must click twice

**Comment by eitguide** [comment]
I have the same issue.

**Comment by eitguide** [comment]
> I have the same issue.

Solution: I fixed it by check out latest stable channel

**Comment by janmoppel** [comment]
Hello @wuyugege !

Thank you for posting.
Can you please check, whether solution proposed by @eitguide works for you?

Thank you.

**Comment by wuyugege** [comment]
@eitguide you mean v1.9.1+hotfix.2?

**Comment by escamoteur** [comment]
I guess so. Also you are not on the latest master, so please upgrade and try again.
You say it was working before 1.10.5?

**Comment by wuyugege** [comment]
@escamoteur i tried 1.10.4, also has this issue. v1.9.1+hotfix.2 does not has this issue, but i cannot turn to  the latest stable version, because version version under dev-1.10.4 has this issue : [https://github.com/flutter/flutter/issues/37699](#37699), so  i'm stuck now..

**Comment by escamoteur** [comment]
@Hixie we have catch 22 problem here. What can we do?

**Comment by eitguide** [comment]
I use v1.9.1+hotfix.2-stable

**Comment by eitguide** [comment]
> @eitguide you mean v1.9.1+hotfix.2?

Yup, I checkd out to this channel to resolve issue.

**Comment by escamoteur** [comment]
@wuyugege 1.10.6 should have the problem #37699, fixed. can you give that a try please?

**Comment by wuyugege** [comment]
@escamoteur yes , i switched to Channel master, v1.10.6-pre.29, this issue and [https://github.com/flutter/flutter/issues/37699](#37699) are solved, but i encounter another question:[https://github.com/flutter/flutter/issues/41104](#41104)

**Comment by goderbauer** [comment]
This bug has been marked as today, but there are no steps in here to reproduce the problem. A printout of `flutter doctor -v` would be helpful. Also, are you running on iOS or Android? Does this happen with any flutter app or only in specific circumstances?

**Comment by escamoteur** [comment]
@goderbauer I marked it as today because this user is stuck between two versions one with the problem stable and  and master that works but has another problem.

**Comment by goderbauer** [comment]
I just ran flutter_gallery on the latest master (2c8813c86cb5366ba66e8b018ec7540ab9c6c86c) on an iPhone XR and was unable to reproduce this. The first click on the screen is recognizes as expected.

@wuyugege Does this happen for any Flutter app? Or only specific ones? If it is the latter, you'll have to provide us with a runnable code snippet that reproduces the problem.

I think we should take the TODAY label of this issue. In its current state it isn't really blocking releases.

**Comment by escamoteur** [comment]
@goderbauer the iPhone XR was running iOS 13? Did you see debug output?

**Comment by goderbauer** [comment]
It was running 12.3.1 - the issue makes no mention of iOS 13. Is that required to reproduce?

**Comment by escamoteur** [comment]
@goderbauer #37699 talks about ios13

**Comment by wuyugege** [comment]
@escamoteur @escamoteur  thanks for your reply, this issue has solved on the latest master version
