### ISSUE TITLE
VM snapshot invalid and could not be inferred from settings.  

### ISSUE THREAD

**Issue by jnaval04** [flutter/flutter#41081]
So after trying `flutter run --release`, I am getting a strange error on release mode:

```
E/flutter: [ERROR:flutter/runtime/dart_vm_data.cc(19)] VM snapshot invalid and could not be inferred from settings.
    [ERROR:flutter/runtime/dart_vm.cc(245)] Could not setup VM data to bootstrap the VM from.
    [ERROR:flutter/runtime/dart_vm_lifecycle.cc(89)] Could not create Dart VM instance.
A/flutter: [FATAL:flutter/shell/common/shell.cc(209)] Check failed: vm. Must be able to initialize the VM.
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 16450 (iplylabs.spokes), pid 16450 (iplylabs.spokes)
```

I am not sure what this is, but our application works fine on debug mode. I've tried both `stable` and `master` channel to no avail. Google search yields almost nothing useful. So I have tried everything and hence posted here. 

This all started when I move to comply with 64bit compliance in Playstore since I cannot go and upload our app anymore. It appears Flutter doesn't support x86 architecture, so I dropped the 'x86' requirement in ndk abiFilters. That worked fine, until I decided to test the release apk and make sure I won't embarrassed myself again, so I did `flutter run --release` and I am getting this error. Our app crashes just as soon as its starts dropping the error log I mentioned here.

I definitely need help as we are trying close our release schedule but this is blocking us. 

## Logs

```
flutter run --release
```

```
[✓] Flutter (Channel dev, v1.10.5, on Mac OS X 10.14.5 18F203, locale en-PH)
    • Flutter version 1.10.5 at /Users/jnaval/Workspace/FlutterWorkspace/flutter
    • Framework revision 3cf88fed6d (4 days ago), 2019-09-18 23:09:41 -0400
    • Engine revision 33ad6757e8
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 cb80ea7ba9)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/jnaval/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
```

**Comment by janmoppel** [comment]
Hello @jnaval04 !

Thank you for posting an issue.
Seems like a similar problem, as discussed here: #40770

**Comment by escamoteur** [comment]
Just to make this clear, are you trying to run the release on a real device or an emulator?
Release on emulator is not supported.

**Comment by escamoteur** [comment]
I will close this issue. Please upvote the linked one as it seems to be a double.

**Comment by wingtob** [comment]
I met the same problem too. I fixed it as follows:
![image](https://user-images.githubusercontent.com/66667668/88391730-5548d080-cded-11ea-9270-b49fd171404e.png)
1. run `flutter build ios --release` in the terminal
2. open the Runner.xcworkspace in the Xcode
3. click Runner->Edit Scheme, then select the `Release` in Build Configuration

In a word, if you build the release flutter framework, then you must select release Build Configuration in the Xcode.

**Comment by kustraslawomir** [comment]
Same on android.

**Comment by kustraslawomir** [comment]
2021-02-03 16:25:27.671 1029-1029/pl.ler.app E/flutter: [ERROR:flutter/runtime/dart_vm_data.cc(18)] VM snapshot invalid and could not be inferred from settings.
2021-02-03 16:25:27.671 1029-1029/pl.ler.app E/flutter: [ERROR:flutter/runtime/dart_vm.cc(249)] Could not setup VM data to bootstrap the VM from.
2021-02-03 16:25:27.671 1029-1029/pl.ler.app E/flutter: [ERROR:flutter/runtime/dart_vm_lifecycle.cc(84)] Could not create Dart VM instance.
2021-02-03 16:25:27.671 1029-1029/pl.ler.app A/flutter: [FATAL:flutter/shell/common/shell.cc(265)] Check failed: vm. Must be able to initialize the VM.
2021-02-03 16:25:27.671 1029-1029/pl.ler.app A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 1029 (pl.ler.app), pid 1029 (pl.ler.app)
