### ISSUE TITLE
how to draw this shape

### ISSUE THREAD

**Issue by Shubham-8197** [flutter/flutter#41084]
hello I want to draw this shape using canvas I tried many times but I failed to draw perfect this shape 

![aaa](https://user-images.githubusercontent.com/55377064/65415178-da044000-de12-11e9-91b2-014b74d84acd.png)

if anyone knows how to draw this shape using canvas then please help mi

**Comment by escamoteur** [comment]
Please ask questions like this on stackoverflow. Thanks.
