### ISSUE TITLE
Advanced HTTP Client

### ISSUE THREAD

**Issue by amreniouinnovent** [flutter/flutter#41091]
## Use case

Dio or Copper library is not good enough for flutter developers
For example, retry feature or queue manager is not exist in Dio library

## Proposal

Same like Android team they made Volley HTTP CLient I think Flutter Team Should Consider making an advanced HTTP Client for Flutter developers.

**Comment by VladyslavBondarenko** [comment]
Hi @amreniouinnovent 
You can use [http](https://pub.dev/packages/http) from Dart.
If you have proposals to the plugin, please write to [the repository](https://github.com/dart-lang/http/issues)
Closing the issue
If you disagree please write in the comments and I will reopen it.
Thank you

**Comment by amreniouinnovent** [comment]
@VladyslavBondarenko Can at least I get support how could I make a queue manager like a volley in Android?

**Comment by darshankawar** [comment]
@amreniouinnovent 
Is this still a valid issue or have you found solution on this ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
