### ISSUE TITLE
draw canvas in flutter

### ISSUE THREAD

**Issue by Shubham-8197** [flutter/flutter#41097]
https://stackoverflow.com/questions/58059853/how-to-draw-custom-canvas-in-flutter

**Comment by BondarenkoStas** [comment]
@Shubham-8197 This is a SO question, it's clearly about the implementation, and doesn't seem to be anything wrong with flutter itself. I will close it, please comment if you won't receive any help on SO or in another place in several days, I will reopen it again.

But as far as I know, you don't need to use `new` while creating a rect, paint or color.
