### ISSUE TITLE
[device_info] Add firebase test lab indicator

### ISSUE THREAD

**Issue by Raigen** [flutter/flutter#41099]
## Use case
Firebase Analytics is reporting a lot of events from the pre launch reports of the play store console. The [Firebase Test Lab Documentation](https://firebase.google.com/docs/test-lab/android/android-studio#modify_instrumented_test_behavior_for) describes how to figure out if the app is running on a test lab device in java. An indicator in flutter for test lab devices would be very helpful, just like the indicator for emulator.

## Proposal
Add an indicator for firebase test lab devices to the `AndroidDeviceInfo` of `device_info` package.

**Comment by stuartmorgan** [comment]
Closing as `device_info` is deprecated in favor of [`device_info_plus`](https://pub.dev/packages/device_info_plus).
