### ISSUE TITLE
Do not validate SDK when building appbundle

### ISSUE THREAD

**Issue by dotdoom** [flutter/flutter#41098]
Similar to #28076, it should be possible to let Gradle download Android SDK packages as explained in https://developer.android.com/studio/intro/update#download-with-gradle, instead of requiring an existing Android SDK to be installed.

## Steps to Reproduce

Running on CI:

1. Download Flutter SDK **only**, per instructions at https://flutter.dev/docs/get-started/install
1. Clone an existing Flutter application from GitHub
1. Set `ANDROID_SDK_ROOT` and copy accepted licenses hashes from developer workstation into `$ANDROID_SDK_ROOT/licenses/`
1. Run `flutter build appbundle --debug` within the cloned application directory

## Logs

Without an Android SDK:

```shell
$ flutter build appbundle --debug
Android SDK file not found: adb.
Try re-installing or updating your Android SDK.
```

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v1.9.1+hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.2 at /home/dotdoom/pkg/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
```

**Comment by dnfield** [comment]
I have a patch almost ready for this.
