### ISSUE TITLE
Read VM service URI from file instead of scraping console

### ISSUE THREAD

**Issue by bkonyi** [flutter/flutter#41106]
Now that https://github.com/dart-lang/sdk/issues/38418 has been resolved, making it possible to dump the VM service URI to a file, we should start migrating away from scraping the console output for the Observatory message in all of our tools and infrastructure. This should also make it easier to remove usages of `--disable-service-auth-codes` and `--disable-service-origin-check` (https://github.com/dart-lang/sdk/issues/38527).

Assigning to @jonahwilliams to start with updating flutter_tools to utilize the `--write-service-info` VM flag.

**Comment by jonahwilliams** [comment]
cc @blasten

**Comment by bkonyi** [comment]
I've made a similar change in the VM's testing infrastructure to remove `--disable-service-auth-codes` in [this CL](https://dart.googlesource.com/sdk/+/7e4058e3a5c38ed1280230084162d28782c8334d)

**Comment by zanderso** [comment]
This is unlikely to be possible on all of the platforms we support (e.g. iOS). I'm going to close this, but if this is the right approach on a particular platform, we can open a new issue.
