### ISSUE TITLE
onCameraIdle not works in googlemap ios

### ISSUE THREAD

**Issue by SilvereNef** [flutter/flutter#41107]
Hello everybody.
I write an app with plugin google_maps_flutter.

And I have a problem with the event "onCameraIdle".

On Android, when map is stopped, the event is being called but on ios the event is not called.
The event "onCameraMove" is called on that 2 platforms.

It is normal or the event is in developpement yet ?

Thanks a lot for your response

**Comment by SilvereNef** [comment]
Nobody couldn't help me ?

**Comment by DoubleHub** [comment]
I have the same problem. This is bad >:(

**Comment by SilvereNef** [comment]
DoubleHub, after a lot of research, I don't found a true solution.
But I found a circumvention (comment is French :-)) :

```

// Timer utilisee uniquement sur ios pour palier au defaut d'event quand la carte arrete de bouger.
    Timer mapStopped;

// Widget
   GoogleMap(  
                    onLongPress: _onLongPress,
                    mapType: _typeMap,
                    markers: Set<Marker>.of(_markers.values),
                    polylines: Set<Polyline>.of(_polyline.values),
                    initialCameraPosition: _initCameraPosition,
                    onMapCreated: (GoogleMapController controller) 
                    {
                        _controller.complete(controller);
                    }, 
                    onCameraMove: _onCameraMoove,
                    onCameraIdle: _getAddressFromLatLng,
                ),


/// 
    /// Méthode appelée à chaque fois que la caméra de la carte Google bouge.
    /// Récupère et stocke la position gps de la caméra si l'on se trouve dans le placement de point sur la carte.
    /// 
    void _onCameraMoove(CameraPosition cameraPosition)
    {
      if (_placeOnMap)
      {
        _onCameraStopPosition = cameraPosition.target;

        // Pour palier au manque du plugin google_map_flutter sur ios qui ne genere pas d'event quand la carte arrete de bouger.
        // La mise en place d'un timer (compte a rebour) est obligatoire pour que l'adresse s'autoremplisse
        if (Platform.isIOS)
        {
          // Si le timer n'est pas null, il faut le stopper.
          if(mapStopped != null)
            mapStopped.cancel();

          // Instanciation du compte a rebours qui, arrive a 0, executera la methode en parametre de callback 
          mapStopped = new Timer(new Duration(milliseconds: 500), () => _getAddressFromLatLng());
        }        
      }
    }

```

The method onCameraMoove delete and instanciate a timer when user moove map. 
Each time camera moove, the position of center get on the variable.
When the timer duration finish he execute the method callback.
Method "getAddressFromLatLng" get the address to the previous variable latlng.

I hope that help you.

**Comment by DoubleHub** [comment]
I see... it's an hacky workaround but it works :) Hope to have official support for this tho

**Comment by SilvereNef** [comment]
Yes, It works, I saw that the plugin google_maps_flutter continue to evolate but I thnk their priority is not ios.

Official support will be good for other problem too.

Good development :-)

**Comment by DoubleHub** [comment]
I implemented it like this:

`
onCameraIdle: _fetchVenuesAroundCenter,
onCameraMove: (position) {
	// Update camera position
   setState(() => _cameraPosition = position);

   // Because onCameraIdle doesn't work on iOS
   // I need to setup a timer to handle the idling detection myself
   if (Platform.isIOS) {
   	iosMapStopped?.cancel();
    iosMapStopped = Timer(const Duration(milliseconds: 500), _fetchVenuesAroundCenter);
   }
}
`

Thanks for the help

**Comment by DoubleHub** [comment]
I implemented it like this

```dart
onCameraIdle: _fetchVenuesAroundCenter,
onCameraMove: (position) {
	// Update camera position
   setState(() => _cameraPosition = position);

   // Because onCameraIdle doesn't work on iOS
   // I need to setup a timer to handle the idling detection myself
   if (Platform.isIOS) {
   	iosMapStopped?.cancel();
    iosMapStopped = Timer(const Duration(milliseconds: 500), _fetchVenuesAroundCenter);
   }
}
```

Thanks for the help

**Comment by cyanglaz** [comment]
This should be fixed by https://github.com/flutter/plugins/pull/2746. I'm closing the issue. If anyone finds it is not fixed, please ping me and I'll reopen the issue and investigate.
