### ISSUE TITLE
printed logs does not show on the terminal

### ISSUE THREAD

**Issue by wuyugege** [flutter/flutter#41104]
my flutter version is : Flutter (Channel master, v1.10.6-pre.29, on Mac OS X 10.14.6 18G87, locale zh-Hans-CN)

the printed logs does not show on the terminal

**Comment by BondarenkoStas** [comment]
@wuyugege Please provide more details. On VSCode terminal, or Android Studio, or any other system terminal? Logs after running a flutter command with `-v`? Or you mean `print()` or `debugPrint()`?

**Comment by stx** [comment]
Same problem here. I opened https://github.com/flutter/flutter/issues/41133 with a lot more info.

**Comment by christopherfujino** [comment]
@wuyugege thank you for reporting this. I am closing this issue in favor of #41133 as it has more information, please follow there for updates (any more details you can provide about your error case would be very helpful!).
