### ISSUE TITLE
Is there a good example of how to share code between Mobile Apps and Web??

### ISSUE THREAD

**Issue by betosalvador** [flutter/flutter#41110]
Hello, guys

I'm search for a good tool to develop to Web and Mobile.

A friend of my recomended me to learn NativeScript/Angular, because with that tools is possible to write the services, models and controllers only one time and create specific views for Mobile and Web platform, sharing 100% the business logic code.

But I thing that nativescript is not so hyped as flutter and maybe flutter could be more used in the next days, so I'm searching for this type os project (sharing logic between Mobile and Web) in flutter, but I'm not sure if this is really possible. 

I satw something about BLOC pattern, but I am not sure is this is the correct solution for this type of project, or if is possible to write logic code only one time and specfic "views" for Mobile and Web in flutter.

Can anybody help me in this issue.

Thanks in advance (and sorry about my english, I'm not fluent yet)

**Comment by VladyslavBondarenko** [comment]
Hi @betosalvador 
Yes, Flutter allows this.
Take a look for example at this [get started web with Flutter](https://flutter.dev/docs/get-started/web)
Thank you
