### ISSUE TITLE
Camera plugin (audio enabled) generate corrupt video (on some Android versions)

### ISSUE THREAD

**Issue by DomGIS** [flutter/flutter#41113]
Hi,
The mp4 file is scramble/corrupted on Android 8.1 when audio is enabled (and only on this case)

The plugin works fine on Android 9 with audio enabled.

> I/MediaRecorderJNI( 2312): stop
> I/MediaRecorderJNI( 2312): native_reset
> V/Surface ( 2312): sf_framedrop debug : 0x4f4c, game : false, logging : 0
> 
> I/ExoPlayerImpl( 2312): Init 93fafa1 [ExoPlayerLib/2.9.6] [j7xelte, SM-J710F, samsung, 27]
> V/Surface ( 2312): sf_framedrop debug : 0x4f4c, game : false, logging : 0
> E/LoadTask( 2312): Unexpected exception loading stream
> E/LoadTask( 2312): java.lang.IllegalStateException: Top bit not zero: -1814389386

Flutter version 1.7.8+hotfix.4
plugin camera: 0.5.4+2

I downloaded the local video file. The video player just confirm the corrupt state of the video file (so the video player is not important here).

**Comment by BondarenkoStas** [comment]
@DomGIS is it the same using current stable version?

**Comment by DomGIS** [comment]
Same issue with Flutter 1.9.1+hotfix.2

**Comment by igorkurochka** [comment]
Same problem. Any solutions or workarounds yet?

**Comment by TahaTesser** [comment]
Hi @DomGIS 
Are you still experiencing this issue with latest stable versions?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @DomGIS
