### ISSUE TITLE
Resample input events due to irregular events delivery or VSYNC and input frequency mismatch

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#41118]
Scrolling is janky on Android OnePlus 7 Pro and Pixel 4 (60/90Hz VSYNC, 120Hz input) due to irregular input events delivery and frequency mismatch. Similar issues have also been discovered on Fuchsia (https://github.com/flutter/flutter/issues/49353).

We need to resample the input events in Flutter framework to solve this across platforms.

Please see https://github.com/flutter/flutter/issues/31086#issuecomment-533881798 for more details.

**Comment by liyuqian** [comment]
@cbracken : shall we get one Android OnePlus 7 Pro to test it?

**Comment by bonnyfone** [comment]
@liyuqian some clarifications:
- does it jank only when running at 90Hz or also at 60Hz?
- Android 10 or 9?

thanks!

**Comment by volskaya** [comment]
@bonnyfone It happens at 60hz also, tho everything is buttery smooth, while screen recording at 60. Both android 10 and 9.

**Comment by liyuqian** [comment]
I've confirmed that it's janky on both 60Hz and 90Hz mode, and on both Pixel 4 and Android OnePlus 7 Pro. In all those cases, Flutter got ~120Hz touch input events.

As the input events are issued at a higher frequency, it's also more likely to receive them in an irregular pattern, and some frame may receive 1 event, some may receive 2 events, and some may receive 3 events, which makes the scroll look janky. (Unlike the iPhone X/Xs, Pixel 4 and OnePlus 7 Pro don't have missing frames because the input is at 120Hz instead of iPhone X's 60Hz.)

Moreover, even if the events are delivered with a perfectly regular pattern, if the VSYNC frequency mismatches input frequency, the jank would still happen. For example, if VSYNC is at 90Hz, and the input is at 120Hz, then half frames will scroll by 1 input event, and half frames would scroll by 2 input events, even if everything is perfectly regular.

After discussing with the Android engineers, we discovered that Android OS can actually resamples the input event to match the VSYNC frequency as long as [requestUnbufferedDispatch](https://developer.android.com/reference/android/view/View.html#requestUnbufferedDispatch(android.view.MotionEvent)) is not called. (Note the blue warning message of that API's side effects: `increased latency, jittery scrolls and inability to take advantage of system resampling`.) This was an issue that Android has to solve back for Nexus 9 which has 60Hz VSYNC and 90Hz input.

However, Flutter added `requestUnbufferedDispatch` back in 2015 by https://github.com/flutter/engine/commit/7ca2e4fb10aa45ceb417b154cac7534acc32a2ce#diff-cba77c3975dcf22d9b57421b957bb189R185 to improve the performance.

I've confirmed that if we just removed `requestUnbufferedDispatch` from that commit, Flutter's performance would significantly degrade from 60Hz to 30Hz, even if both VSYNC and input are at 60Hz. From the trace, I can see one frame always handling 2 input events, and the next frame is starved and skipped.

Fortunately, if we apply the [SmoothPointerDataDispatcher](https://github.com/flutter/engine/pull/12385/files#diff-c22215a25f4d115f9a037d39dd25778aR136) to Android, such starving issue would be solved, and we'll get smooth 60Hz or 90Hz frames with the matching resampled input events. That makes the scroll smooth again for Pixel4 and Android OnePlus 7 Pro.

Therefore, my proposal is to remove `requestUnbufferedDispatch` call, and apply `SmoothPointerDataDispatcher` to Android. @Hixie @cbracken @chinmaygarde @abarth : please review if this approach sounds good to you.

@kf6gpe @tvolkert , please also be aware of this issue as its sister issue about iPhone X/Xs received a lot of attentions. As 90Hz Android devices (Pixel 4, Android OnePlus 7 Pro) become more popular, I'd expect this issue to have more impact.

**Comment by liyuqian** [comment]
Discussed with @Hixie a while ago and reached to the conclusion that we should make [SmoothPointerDataDispatcher][1] or its equivalence to work on all Flutter platforms (e.g., Android, iOS, Fuchsia, etc.) so Flutter's smoothness will be less platform dependent. That may bring our work back to the framework level (in Dart) similar to our first attempt in https://github.com/flutter/flutter/pull/36616 .

[1]: https://github.com/flutter/engine/pull/12385/files#diff-c22215a25f4d115f9a037d39dd25778aR136

**Comment by kf6gpe** [comment]
@liyuqian @jmagman @xster Do we have a relative sense of priority for this in terms of the performance work we're doing (asking since it's been upvoted to `customer: crowd` status.

**Comment by liyuqian** [comment]
@dreveman and I have will have a meeting on April 6th if not earlier to go through a plan on this. It should have a relative high priority as Fuchsia also sees this as a big problem.

**Comment by kf6gpe** [comment]
@liyuqian, what was the outcome of your meeting with @dreveman?

**Comment by liyuqian** [comment]
@dreveman and I have planned to fix this issue in ~2 months. Set the milestone to June to reflex that.

**Comment by kf6gpe** [comment]
@liyuqian Is this still on track for June, or should we adjust the milestone here?

**Comment by liyuqian** [comment]
Just chatted with @dreveman and we decided to adjust the milestone to July so we'll have more time for code reviews.

**Comment by kf6gpe** [comment]
@liyuqian Is @CareF's commit here the only one we need to close this, or should we slip the milestone one more month? Thanks!

**Comment by CareF** [comment]
@kf6gpe #60558 is going to be a fix, but it's still pending. Mine is more like a preparation for the test framework to support testing the performance of the solution, which is used in #61998 (still draft because it's going to test #60558

**Comment by liyuqian** [comment]
Yes, we need to extend the milestone for one more month. Will talk to @dreveman soon to verify if we can land the fix soon.
