### ISSUE TITLE
[local_auth] - Unhandled Exception: PlatformException(no_fragment_activity

### ISSUE THREAD

**Issue by DeividWillyan** [flutter/flutter#41119]
An error was encountered when the fingerprint validation method is called on android devices.

**Error:**
```
E/flutter (13796): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null)
E/flutter (13796): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (13796): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (13796): <asynchronous suspension>
E/flutter (13796): #2      LocalAuthentication.authenticateWithBiometrics (package:local_auth/local_auth.dart:89:27)
E/flutter (13796): <asynchronous suspension>
E/flutter (13796): #3      FingerService.verify (package:projeto2/service/finger.service.dart:14:31)
E/flutter (13796): <asynchronous suspension>
E/flutter (13796): #4      _LoginPageState._finger (package:projeto2/pages/login.page.dart:193:36)
E/flutter (13796): <asynchronous suspension>
E/flutter (13796): #5      _LoginPageState._body.<anonymous closure> (package:projeto2/pages/login.page.dart:123:21)
E/flutter (13796): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
E/flutter (13796): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
E/flutter (13796): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (13796): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (13796): #10     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
E/flutter (13796): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (13796): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (13796): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (13796): #14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (13796): #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (13796): #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (13796): #17     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (13796): #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (13796): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (13796): #20     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter (13796): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
```

**Solution:**
- In : android/app/src/main/kotlin/../project/**MainActivity.kt**, alter to:

```
import android.os.Bundle

import io.flutter.app.FlutterFragmentActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}
```
in gradle.properties file:
```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by snaeji** [comment]
This solution is not perfect since it causes other plugins to fail. For example the audio_service plugin crashes when getting context.
https://github.com/ryanheise/audio_service/issues/87

**Comment by rostopira** [comment]
Why it's required in the first place? Can't we just use Flutter popup instead of fragment? What's the point of android x dependency after all? For a single API use?

**Comment by snaeji** [comment]
There also seem to be issues with some other packages using this method. This issue refers to issues with getting intent.

https://github.com/flutter/flutter/issues/42843

**Comment by xster** [comment]
The Flutter plugins APIs currently don't support FragmentActivities by default (see reasoning in https://github.com/flutter/flutter/issues/43921). If plugins opt to assume that the Android code hosting the Flutter UI uses fragments, the user needs to fulfill that assumption manually at this moment. See the plugin instructions (specifically https://github.com/flutter/plugins/tree/master/packages/local_auth#android-integration)

**Comment by siva563** [comment]
I tried this stil same issue.

**Comment by NarHakobyan** [comment]
same here

**Comment by aanalmehta-sa** [comment]
I am still getting the same error. 
**GeneratedPluginRegistrant** class method **registerWith** wants **FlutterEngine** object.
Did anyone find the solution?

**Comment by VladyslavBondarenko** [comment]
Try to have such MainActivity.kt

```
package com.example.bug

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```

**Comment by abhilashahyd** [comment]
@VladyslavBondarenko 
I am getting the same error even after trying the MainActivity fix suggested here.
Below is the code I am using in my widget
 final LocalAuthentication locauth = LocalAuthentication();

  try {
          _canCheckBiometrics = await locauth.canCheckBiometrics;
          print(_canCheckBiometrics);
          if (_canCheckBiometrics) {
            _availableBiometrics = await locauth.getAvailableBiometrics();
            print(_availableBiometrics);
            bool authenticated = await locauth.authenticateWithBiometrics(
                localizedReason: 'Scan your fingerprint to authenticate',
                useErrorDialogs: true,
                stickyAuth: true);
            print(authenticated);
          }
        } on PlatformException catch (e) {
          print(e);
        }

The log which I get in console is as follows:
D/FlutterView(20276): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@e60e674
D/DecorView(20276): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@16847e3[MainActivity]
I/flutter (20276): true
I/flutter (20276): [BiometricType.fingerprint]
I/flutter (20276): PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null)

**Comment by VladyslavBondarenko** [comment]
@abhilashahyd 

is MainActivity used in your AndroidManifest.xml?

you can have
```
<activity
            android:name=".MainActivity"
...
```
and this MainActivity.kt file https://github.com/flutter/flutter/issues/41119#issuecomment-625128400

or you can have 
```
<activity 
            android:name="io.flutter.embedding.android.FlutterFragmentActivity"
...
```
and then you don't even need to have MainActivity.kt file

**Comment by abhilashahyd** [comment]
@VladyslavBondarenko
MainActivity is being used in AndroidManifest.xml as shown by you,
<activity 
 android:name=".MainActivity"
...... </activity>

**Comment by jjvillavicencio** [comment]
Hello, start an application with Flutter 1.17 and when you replace FlutterActivity in the MainActivity with FlutterFragmentActivity, the application does not load the other plugins when compiling.

How should FlutterFragmentActivity be implemented in Flutter 1.17?

> New Flutter MainActivity.kt file
```
package com.package.xxxx

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
```

**Comment by abhilashahyd** [comment]
@jjvillavicencio @VladyslavBondarenko
I upgraded to Flutter 1.17 and used FlutterActivity instead of FlutterFragmentActivity.
LocalAuthentication for Fingerprint worked for me with no other changes.

Thank you!

**Comment by TerraDCF** [comment]
If someone is using java instead of kotlin, this is the MainActivity.java of @VladyslavBondarenko code:

``` 
import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterFragmentActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.GeneratedPluginRegistrant;


public class MainActivity extends FlutterFragmentActivity {

    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```

**Comment by nirranthea** [comment]
> Hello, start an application with Flutter 1.17 and when you replace FlutterActivity in the MainActivity with FlutterFragmentActivity, the application does not load the other plugins when compiling.
> 
> How should FlutterFragmentActivity be implemented in Flutter 1.17?
> 
> > New Flutter MainActivity.kt file
> 
> ```
> package com.package.xxxx
> 
> import io.flutter.embedding.android.FlutterActivity
> 
> class MainActivity: FlutterActivity() {
> }
> ```

Hi I have same question, did you solve it ?

**Comment by jjvillavicencio** [comment]
> > Hello, start an application with Flutter 1.17 and when you replace FlutterActivity in the MainActivity with FlutterFragmentActivity, the application does not load the other plugins when compiling.
> > How should FlutterFragmentActivity be implemented in Flutter 1.17?
> > > New Flutter MainActivity.kt file
> > 
> > 
> > ```
> > package com.package.xxxx
> > 
> > import io.flutter.embedding.android.FlutterActivity
> > 
> > class MainActivity: FlutterActivity() {
> > }
> > ```
> 
> Hi I have same question, did you solve it ?
> 
> > @jjvillavicencio @VladyslavBondarenko
> > I upgraded to Flutter 1.17 and used FlutterActivity instead of FlutterFragmentActivity.
> > LocalAuthentication for Fingerprint worked for me with no other changes.
> > Thank you!
> 
> Hello, I am using flutter 1.17,
> when FlutterFragmentActivity used I got error
> `Unhandled Exception: MissingPluginException(No implementation found for method getAvailableBiometrics on channel plugins.flutter.io/local_auth)`
> so other plugin got same error
> 
> when FlutterActivity used I got error
> `PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null)`
> 
> can you tell me what I am missing ?

@nirranthea  I solved it by implementing the following in the file MainActivity.kt

```
package xx.xxx.xxxx

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```

**Comment by nirranthea** [comment]
> @nirranthea I solved it by implementing the following in the file MainActivity.kt
> 
> ```
> package xx.xxx.xxxx
> 
> import androidx.annotation.NonNull;
> import io.flutter.embedding.android.FlutterFragmentActivity
> import io.flutter.embedding.engine.FlutterEngine
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterFragmentActivity() {
>     override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
>         GeneratedPluginRegistrant.registerWith(flutterEngine);
>     }
> }
> ```
it worked. thanks 👍

**Comment by akifarhan** [comment]
This is what i did to solve this issue

Change `MainActivity.kt` as below
```
package com.[your.package]

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```

However, after changing this `MainActivity.kt`, I also faced some other issue with the `Theme.AppCompat`. Check this out  https://gist.github.com/akifarhan/f70a2c777651f2ea61a15eb92a5939c1 for the solution.

**Comment by Virenvkj** [comment]
Add the following dependency to the dependencies in your **App Level build.gradle** file.

`dependencies{    
    api "androidx.core:core:1.1.0-aplha03"
}`

**Comment by chirayu-joshi** [comment]
I solved this issue by:

1. Changing `android/app/src/main/res/values/styles.xml`

override the line `<style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">` with `<style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">`

2. Changing `android/app/src/main/kotlin/MainActivity.kt`
```
package xxx.xxxxx.xxxx

import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}
```

**Comment by uriel2707** [comment]
I solved this issue:

 - Changing `android/app/src/main/kotlin/MainActivity.kt`
```
    package ....
   
    import androidx.annotation.NonNull;
    import io.flutter.embedding.android.FlutterFragmentActivity
    import io.flutter.embedding.engine.FlutterEngine
    import io.flutter.plugins.GeneratedPluginRegistrant
    
    class MainActivity: FlutterFragmentActivity() {
        override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
            GeneratedPluginRegistrant.registerWith(flutterEngine);
        }
    }
```

 - Enable SplashScreenDrawable in AndroidManifest `android/app/src/main/AndroidManifest.xml`
```
<meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />
```
[https://stackoverflow.com/a/66663047/6251481](https://stackoverflow.com/a/66663047/6251481)
