### ISSUE TITLE
Failed to extract manifest from APK: ProcessException: Permission denied

### ISSUE THREAD

**Issue by dedycode** [flutter/flutter#41111]
I develop flutter on ubuntu 18.04 lts 64 bit
when i try to run always show error :
```
Launching lib/main.dart on SC 02H in debug mode...
Failed to extract manifest from APK: ProcessException: Permission denied
  Command: /home/dedycode/Master/Programming/SDK/Sdk/build-tools/29.0.2/aapt dump xmltree /home/dedycode/Master/Programming/Flutter/latihan/flutter_hello_world/build/app/outputs/apk/app.apk AndroidManifest.xml.
No application found for TargetPlatform.android_arm64.
Is your project missing an android/app/src/main/AndroidManifest.xml?
Consider running "flutter create ." to create one.
Exited (sigterm)
```
try in visual studio code and android studio same error

flutter doctor result haven't problem
```
dedycode@dedycode:~$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.2 at
      /home/dedycode/Master/Programming/Flutter/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/dedycode/Master/Programming/SDK/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/dedycode/Master/Programming/SDK/Sdk
    • Java binary at:
      /home/dedycode/Master/Programming/SDK/android-studio-ide-191.5791312-linux
      /android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at
      /home/dedycode/Master/Programming/SDK/android-studio-ide-191.5791312-linux
      /android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • SC 02H • fd6ca2bd • android-arm64 • Android 7.0 (API 24)

• No issues found!
```
solution from my friend share https://android-er.blogspot.com/2014/07/setup-51-androidrules-for-android-sdk.html?m=1&fbclid=IwAR2lf9oiPzLihMCMi6lO7y4_GbX8P5v_rFKRga2wIMlis999Flq-b-mUOqg still not working

**Comment by dedycode** [comment]
up

**Comment by chitgyi** [comment]
Same issue :cry:  You need to access permission for aapt. Following command, it works for me
`sudo chmod a+x /home/dedycode/Master/Programming/SDK/Sdk/build-tools/29.0.2/aapt`

**Comment by zyllus17** [comment]
You need to change Android SDK from 29 to 25.

How to solve-

**Delete the Emulator you are using.**

1.  Press Shift Twice and type SDK Manager.
2.  Unselect Android 10.0(Q) API Level 29 and select Android 5.1(Lolipop) API level 22.
(You must have Internet Connection to download.)
3.  Press Apply and Ok.

It should fix it! If this still doesn't fix it, follow along.

4.  Press Shift Twice and type Project Structure(File).
5.  In Project Structure choose Project and select Project SDK from the Drop down list select Android 29.0 or 22.0 whichever you see.
6.  Then go to Platform Settings and choose SDKs and select Build Target from the Drop down list select Android API 22.0.
7.  Close Android Studio and Restart.

This should fix the error.

**Comment by mahatodebashish** [comment]
> You need to change Android SDK from 29 to 25.
> 
> How to solve-
> 
> **Delete the Emulator you are using.**
> 
> 1. Press Shift Twice and type SDK Manager.
> 2. Unselect Android 10.0(Q) API Level 29 and select Android 5.1(Lolipop) API level 22.
>    (You must have Internet Connection to download.)
> 3. Press Apply and Ok.
> 
> It should fix it! If this still doesn't fix it, follow along.
> 
> 1. Press Shift Twice and type Project Structure(File).
> 2. In Project Structure choose Project and select Project SDK from the Drop down list select Android 29.0 or 22.0 whichever you see.
> 3. Then go to Platform Settings and choose SDKs and select Build Target from the Drop down list select Android API 22.0.
> 4. Close Android Studio and Restart.
> 
> This should fix the error.

Thaanks .. worked

**Comment by joy2012bd** [comment]
I am facing same issue on Windows. Tried above methods, not worked.
