### ISSUE TITLE
Error 'module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1'

### ISSUE THREAD

**Issue by SebAubin** [flutter/flutter#41121]
Hi, i'm having trouble compiling my app since the Xcode updated to 11. I've tried upgrading the Swift language version to 5 for my project but it's still showing this error. 

```
 === BUILD TARGET Pods-Runner OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/<user>/Documents/git/<project_path>/MasterKeyAuthViewController.swift:14:8: error: module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /Users/<user>/Documents/git/<project_path>/build/ios/Debug-iphoneos/Runner.swiftmodule/arm64.swiftmodule
    import Runner
```

Am I missing something? Thanks

## Logs
flutter doctor -v:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G84, locale fr-CA)
    • Flutter version 1.9.1+hotfix.2 at /Users/<user>/Documents/git/flutter
    • Framework revision 2d2a1ffec9 (il y a 2 semaines), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/<user>/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/<user>/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.0.beta.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/<user>/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android
      Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Pixel 3 • 8AAX0P4B3                                • android-arm64 • Android 9 (API 28)
    • iPhone  • <id> • ios           • iOS 12.4.1

• No issues found!
```

**Comment by abhit9l** [comment]
facing the same issue while using Razorpay sdk for flutter:

`Xcode's output:
↳
    /Users/abhishek/Desktop/Development/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.1.1/ios/Classes/RazorpayDelegate.swift:2:8: error: module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /Users/abhishek/AndroidStudioProjects/go_hive/go_hive/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64.swiftmodule
    import Razorpay
           ^
    /Users/abhishek/Desktop/Development/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.1.1/ios/Classes/RazorpayDelegate.swift:2:8: error: module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /Users/abhishek/AndroidStudioProjects/go_hive/go_hive/ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64.swiftmodule
    import Razorpay
           ^`

**Comment by brux88** [comment]
the same problem

**Comment by jmagman** [comment]
@SebAubin Why are you trying to `import Runner` from the Runner app?  Did you have a framework or library named Runner you were trying to use?

Can we get a sample app that reproduces this?

**Comment by jmagman** [comment]
I think we need a reproduction case for this.  Are one of your plugins declaring in their podspec that they only support `5.0.1`?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
