### ISSUE TITLE
flutter pub upgrade

### ISSUE THREAD

**Issue by AhmedAlaa96** [flutter/flutter#41124]
I'm trying to upgrade dependencies in darts 
but always get :
Could not resolve URL "https://pub.dartlang.org".
pub upgrade failed (69) -- attempting retry 1 in 1 seconds...

I have manual proxy to connect to my network

**Comment by escamoteur** [comment]
Does it work without the proxy?
Can you please add the output of flutter doctor here?

**Comment by AhmedAlaa96** [comment]
I cannot work without proxy 
that's my flutter doctor
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.239], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[!] VS Code (version 1.38.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

**Comment by escamoteur** [comment]
@jonahwilliams I saw this also in another issue. Do we have a problem with proxy connections?

**Comment by JosephineAkello** [comment]
@AhmedAlaa96 for this I think this is just a network problem because you are trying to fetch dependencies from  ["https://pub.dartlang.org".](url)  and its not able get them. You'll consider configuring your proxy settings
