### ISSUE TITLE
Using /  in the MaterialApp routes property.

### ISSUE THREAD

**Issue by officer47p** [flutter/flutter#41139]
Hey everybody!
I was working around named routes and I figured out this error when I use "/" in my routes name,
Here is my code:

```import 'package:flutter/material.dart';
import 'package:flash_chat/screens/welcome_screen.dart';
import 'package:flash_chat/screens/login_screen.dart';
import 'package:flash_chat/screens/registration_screen.dart';
import 'package:flash_chat/screens/chat_screen.dart';

void main() => runApp(FlashChat());

class FlashChat extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        textTheme: TextTheme(
          body1: TextStyle(color: Colors.black54),
        ),
      ),
      initialRoute: "/welcome",
      routes: {
        "/welcome": (context) => WelcomeScreen(),
        "/login": (context) => LoginScreen(),
        "/registration": (context) => RegistrationScreen(),
        "/chat": (context) => ChatScreen(),
      },
    );
  }
}
```
And here is the output:
```I/flutter (32744): The following message was thrown:
I/flutter (32744): Could not navigate to initial route.
I/flutter (32744): The requested route name was: "/welcome"
I/flutter (32744): The following routes were therefore attempted:
I/flutter (32744):  * /
I/flutter (32744):  * /welcome
I/flutter (32744): This resulted in the following objects:
I/flutter (32744):  * null
I/flutter (32744):  * MaterialPageRoute<dynamic>(RouteSettings("/welcome", null), animation: null)
I/flutter (32744): One or more of those objects was null, and therefore the initial route specified will be ignored and
I/flutter (32744): "/" will be used instead.
I/flutter (32744): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (32744): Another exception was thrown: Could not find a generator for route RouteSettings("/", null) in the _WidgetsAppState.
```
Now, as I realized, when you are using named routes that start with "/"(like "/welcome"), you need to have a route with the name "/".
I mean, the above code throws an error and won't work.
To fix it, you need to have a named route called "/", for your home screen or whatever.
Just keep in mind when you use / in your routes, flutter first checks that if there is any route called "/" in the routes or not, if there is, it works fine, but if it doesn't find it, it throws an error.

I'm asking @flutter team to mention this feature or problem in the documentation.

Thanks a lot and sorry about my English :D

**Comment by escamoteur** [comment]
Thanks a lot bringing this to our attention.

**Comment by kasvith** [comment]
saved my day

**Comment by darshankawar** [comment]
Hi @officer47p,
I tried to replicate this issue on `latest dev (1.20.0-0.0.pre`) and didn't see the error. 

<details>
<summary>code sample</summary>

```
void main() => runApp(Demo());

class Demo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Test',
      initialRoute: "/welcome",
      routes: {
        '/welcome': (context) => WelcomeScreen(),
        '/second': (context) => SecondHome(),
      },
    );
  }
}

class WelcomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Home'),
      ),
      body: new Center(
        child: RaisedButton(
          onPressed: () {
            Navigator.pushNamed(context, '/second');
          },
          child: Text('Second Home'),
        ),
      ),
    );
  }
}

class SecondHome extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Second Home'),
      ),
      body: new Center(
        child: RaisedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: Text('Go Back'),
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>log</summary>

```

Performing hot restart...
Syncing files to device SM A260G...
Restarted application in 2,190ms.
D/mali_winsys(18055): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x960]-format:1
D/mali_winsys(18055): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x888]-format:1
E/BpSurfaceComposerClient(18055): Failed to transact (-1)
E/BpSurfaceComposerClient(18055): Failed to transact (-1)
W/libEGL  (18055): EGLNativeWindowType 0xd12f2808 disconnect failed
W/libEGL  (18055): EGLNativeWindowType 0xd12f2008 disconnect failed
```

</details>

I didn't check if the `api doc` is updated yet, but atleast the error is gone :-)

Can you please confirm if you still experience this error on latest Flutter version (eg: dev, master) ?

**Comment by darshankawar** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by MrDeeKey** [comment]
> Hey everybody!
> I was working around named routes and I figured out this error when I use "/" in my routes name,
> Here is my code:
> 
> ```
> import 'package:flash_chat/screens/welcome_screen.dart';
> import 'package:flash_chat/screens/login_screen.dart';
> import 'package:flash_chat/screens/registration_screen.dart';
> import 'package:flash_chat/screens/chat_screen.dart';
> 
> void main() => runApp(FlashChat());
> 
> class FlashChat extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       theme: ThemeData.dark().copyWith(
>         textTheme: TextTheme(
>           body1: TextStyle(color: Colors.black54),
>         ),
>       ),
>       initialRoute: "/welcome",
>       routes: {
>         "/welcome": (context) => WelcomeScreen(),
>         "/login": (context) => LoginScreen(),
>         "/registration": (context) => RegistrationScreen(),
>         "/chat": (context) => ChatScreen(),
>       },
>     );
>   }
> }
> ```
> 
> And here is the output:
> 
> ```
> I/flutter (32744): Could not navigate to initial route.
> I/flutter (32744): The requested route name was: "/welcome"
> I/flutter (32744): The following routes were therefore attempted:
> I/flutter (32744):  * /
> I/flutter (32744):  * /welcome
> I/flutter (32744): This resulted in the following objects:
> I/flutter (32744):  * null
> I/flutter (32744):  * MaterialPageRoute<dynamic>(RouteSettings("/welcome", null), animation: null)
> I/flutter (32744): One or more of those objects was null, and therefore the initial route specified will be ignored and
> I/flutter (32744): "/" will be used instead.
> I/flutter (32744): ════════════════════════════════════════════════════════════════════════════════════════════════════
> I/flutter (32744): Another exception was thrown: Could not find a generator for route RouteSettings("/", null) in the _WidgetsAppState.
> ```
> 
> Now, as I realized, when you are using named routes that start with "/"(like "/welcome"), you need to have a route with the name "/".
> I mean, the above code throws an error and won't work.
> To fix it, you need to have a named route called "/", for your home screen or whatever.
> Just keep in mind when you use / in your routes, flutter first checks that if there is any route called "/" in the routes or not, if there is, it works fine, but if it doesn't find it, it throws an error.
> 
> I'm asking @flutter team to mention this feature or problem in the documentation.
> 
> Thanks a lot and sorry about my English :D

Define "home" parameter and it will fix this "issue"
```
MaterialApp(
                ...
                  initialRoute: Constants.SPLASH,
                  home: const SizedBox.shrink(),
                ...
```
