### ISSUE TITLE
how to aply Sobel effect in image?

### ISSUE THREAD

**Issue by fabianogadenz** [flutter/flutter#41135]
Hello, I would like to know how I can add a Sobel effect to images in Dart, to later use in my application.

**Comment by escamoteur** [comment]
Please ask questions like this on stackoverflow.

**Comment by fabianogadenz** [comment]
https://pt.stackoverflow.com/questions/412084/como-aplicar-o-filtro-de-sobel-no-dart-flutter question resolved.
