### ISSUE TITLE
Glyph picking incorrect for CJK [Tracking issue]

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#41138]
A multitude of issues have surfaced related to Flutter choosing the wrong versions of glyphs for various CJK languages. This issue is to track them and hopefully see if there is a common thread to these issues. Many of these bugs are in iOS only, which may point to changes or problems with CoreText.

The following bugs are possibly related: 

https://github.com/flutter/flutter/issues/36527 [iOS]App in simplified Chinese. After using the app for a period of time, it may appear that the font is disordered, which may be big or small
https://github.com/flutter/flutter/issues/40184 Font fallback is misbehaving on iOS 13 for certain glyphs
https://github.com/flutter/flutter/issues/40246 Android Nexus5 Text 'ja' Locale is not working

**Comment by escamoteur** [comment]
I guess this here too
https://github.com/flutter/flutter/issues/40823#issuecomment-533944101
I tried to reproduce on Android with latest master where it does not happen.

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/12426 has landed, which should fix a significant part of this bug.

**Comment by escamoteur** [comment]
That means it's already in master?

**Comment by GaryQian** [comment]
As of now, I believe it is in master.

**Comment by GaryQian** [comment]
All but #40184 (pending verification of fix) have been closed, so I will close this tracking issue now!
