### ISSUE TITLE
Consider doing plugin symlinking in Dart

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#41146]
Currently the iOS Podfile we create from a template has logic that symlinks all of the plugin packages from the pub cache into the project folder, so that the checked-in plugin-related files using them will have project-relative paths rather than absolute paths (which wouldn't work for shared development). The macOS plugin tooling duplicates that Podfile almost exactly, including that logic.

While thinking about possible interim ways of making Windows and Linux plugin handling less manual while we figure out the full solutions, I realized that it would be really useful to have the same thing there too; that may not be true long term, but I suspect for at least Linux it will.

Given that, it would be nice to pull the symlink code into the Flutter tool, where any platform could easily use it. That would also mean less logic in the Podfile (Ruby), and more in Dart which everyone on the team is familiar with.

This would be a non-breaking change, other than the potential annoyance of a new file to ignore. Even that could be avoided by putting it inside the existing symlink folder on iOS, which is already ignored.

**Comment by amirh** [comment]
Not sure I fully follow, can you add an example folder/symlink structure?

**Comment by stuartmorgan** [comment]
Sure. First, [here](https://github.com/flutter/flutter/blob/d5c5ac62adfb4b3681f79b994a10c8056bd5f5ab/packages/flutter_tools/templates/cocoapods/Podfile-ios-objc#L39) is the code in question. We actually have three copies of this logic: one in the iOS ObjC podfile, one in the iOS Swift podfile, and one in the macOS podfile (the macOS puts the `.symlink` folder at a different location, but is otherwise the same.)

Here's an example of what it generates in `.symlinks/plugins`:

```
$ ls .symlinks/plugins
path_provider -> /Users/<username>/.pub-cache/hosted/pub.dartlang.org/path_provider-1.2.0
shared_preferences -> /Users/<username>/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.3+1
url_launcher -> /Users/<username>/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.0.3
```

I'm suggesting that instead of N copies of this logic in Ruby (replicated permanently into every project via these files when the Podfile is first added), and then potentially very similar code in other languages in Linux and/or Windows, we just have one Dart copy that's part of `flutter_tools`. We'd just need to use a different folder name for the Dart version to avoid collisions with existing projects.

**Comment by stuartmorgan** [comment]
Since the Ruby code is now consolidated to a helper that lives in the framework, the incremental benefit here would be minimal at best; closing.
