### ISSUE TITLE
Improve message for the RenderFlex Overflow error

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#41149]
The following code will produce a RenderFlex Overflow error:
```dart
import 'package:flutter/material.dart';

class ColumnOverflow extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('RenderFlex OverFlow 2'),
        ),
        body: Container(
          width: 400.0,
          child: Row(
            children: [
              Icon(Icons.message),
              // Resolution: Wrap the Column below in an Expanded widget.
              Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text("Title", style: Theme.of(context).textTheme.display1),
                  Text(
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed"
                      " do eiusmod tempor incididunt ut labore et dolore magna "
                      "aliqua. Ut enim ad minim veniam, quis nostrud "
                      "exercitation ullamco laboris nisi ut aliquip ex ea "
                      "commodo consequat."),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
```
To fix the error, the Column needs to be wrapped in an `Expanded` or `Flexible`. 
 
The error message for the RenderFlex Overflow error identifies `Container` as the ancestor of the error-causing widget, which is not straightforward. It didn't help a study participant to identify Column being the widget he needed to wrap in an Expanded.
```
User-created ancestor of the error-causing widget was: Container
```

Can we make the message say it is the `Column` widget that caused the overflow because its width is unconstraint by default? 

Cc: @jacob314 @chunhtai

**Comment by InMatrix** [comment]
Full message:
```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 1145 pixels on the right.

User-created ancestor of the error-causing widget was: 
  Container file:///Users/..../Development/flutter_projects/flutter_error_studies/lib/renderflex_overflow_error2.dart:11:15
The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#e6daf relayoutBoundary=up1 OVERFLOWING
...  parentData: offset=Offset(0.0, 100.0); id=_ScaffoldSlot.body (can use size)
...  constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=796.0)
...  size: Size(414.0, 58.0)
...  direction: horizontal
...  mainAxisAlignment: start
...  mainAxisSize: max
...  crossAxisAlignment: center
...  textDirection: ltr
...  verticalDirection: down
```

**Comment by InMatrix** [comment]
My questions are:
1. Why do we call out "the *ancestor* of the error-causing widget" instead of the error-causing widget itself? 
2. Why is the Row the error-causing widget instead of of the Column in this example? The fix required applying constraints to the width of the Column.

**Comment by chunhtai** [comment]
This is a bug. there is a defect in the code i wrote that skips the current element and starts with the ancestor.

**Comment by InMatrix** [comment]
I understand it's Okay to have an unconstrained Column in other cases, but isn't it the unconstrained Column that caused the error in the example I posted it? 

Maybe determining whether the child widget or the parent widget is at fault is difficult. How about we don't use the language "the error-causing widget is ..." Instead, we describe the constraints violation such as "The error occurred, because the Column has an an infinite width, but its parent Row has a width of 400."

**Comment by chunhtai** [comment]
I think it depends on how would you treat the error message. The other way to think about it is Row need to be 1145 pixels longer in width because it cannot contain its children. If you think it this way, it is the row that causes the issue.
Our framework reports row instead of column because it crashes when it try to render flex. The column renders fine.

**Comment by InMatrix** [comment]
I discussed with @chunhtai offline. The main constraint we have is the context of the error is limited to the rendering layer, so the code for composing the error message doesn't have a global view of the problem. 

We discussed two approaches to better identifying widgets involved in this error:

1. We could add placeholders for the widget of the RenderFlex and its constraint-violating descendent to the error summary, and then fill in the widget names when the error report comes through the widget layer. For example, we could have the following templated-string as the error summary: "*A RenderFlex of {widget_name} overflowed by 1145 pixels on the right. It's likely to be caused by {culprit_widget_name}.*" "{widget_name}" will be replaced by "Row" and "{culprit_widget_name}" will be replaced by "Column".

2. Alternatively, we can collect error data from the rendering layer and the widget layer and send them all to the IDE for composing the actual error report. At this point, the IDE should have a global view of what's going on. In fact, the IDE probably already knows everything it needs to know from the inspector data to compose a user-friendly message (at least the summary of the error). 

@chunhtai is working out a technical design of the first approach. @jacob314 might have some thoughts on the feasibility of the second approach.

**Comment by Hixie** [comment]
Whatever we do, we need to keep in mind that the rendering layer cannot know of the existence of the widget layer (and indeed might be used without the widget layer -- you can create that render tree directly without any widgets, and still get the same error).

We should not say anything about the user-created anything if the widget that failed is user-created.

> Instead, we describe the constraints violation such as "The error occurred, because the Column has an an infinite width, but its parent Row has a width of 400."

The column doesn't have infinite width (if it did, we would say that; that'd be a different error). It's just that the sum of all the widgets in the row is wider than the row's maxWidth constraint.

In this particular case, it's because the Text widget wasn't given a maximum width so it got very wide, which forced the Column to be wide. It wasn't given a maxWidth because the Column was not marked as Expanded. But the problem could also have just been that the Row was too narrow. Or that the Icon was too wide. Or that the font size was wrong. There's really no way for the code to figure it out with any confidence, IMHO.

**Comment by InMatrix** [comment]
Yeah, we talked about rendering layer being used without the widget layer, and I understand the intent of having those concepts compartmentalized. I was thinking about the possibility of adding additional error report processing logic at/near the end of the rendering pipeline, so information from different layers can be aggregated. @chunhtai told me this line "User-created ancestor of the error-causing widget was: Container" already does something like that.

**Comment by markusaksli-nc** [comment]
Hi @InMatrix 
Is this issue still relevant? The error message seems to have been changed when testing on the latest master `1.22.0-2.0.pre.59`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-2.0.pre.59, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-2.0.pre.59 at C:\Development\flutter_master
    • Framework revision be7c7faee6 (7 hours ago), 2020-08-24 22:31:02 -0400
    • Engine revision 8107b36c7b
    • Dart version 2.10.0 (build 2.10.0-56.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```
</details>



<details>
 <summary>Logs</summary>

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 1082 pixels on the right.

The relevant error-causing widget was: 
  Row file:///C:/Users/marku/Desktop/triage/master/lib/main.dart:15:18
The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#060d3 relayoutBoundary=up2 OVERFLOWING
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=392.7, 0.0<=h<=657.5)
...  size: Size(392.7, 56.0)
...  direction: horizontal
...  mainAxisAlignment: start
...  mainAxisSize: max
...  crossAxisAlignment: center
...  textDirection: ltr
...  verticalDirection: down
...  textBaseline: alphabetic
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

**Comment by InMatrix** [comment]
Thanks for the ping. Further improving this message will need some design work. I'm fine with closing it for now.

**Comment by markusaksli-nc** [comment]
Alright, closing this for now then
