### ISSUE TITLE
The deploy_gallery-macos test is failing on Cirrus due to Cocoapods upgrade

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#41144]
Before: [link](https://cirrus-ci.com/task/6093746858360832?command=install_cocoapods#L1)
Right now: [link](https://cirrus-ci.com/task/6332861109501952?command=install_cocoapods#L0)

Cocoapods is upgraded from 1.7.5 to 1.8.0 during VM provisioning, which breaks the recent builds.

**Comment by digiter** [comment]
@fkorotkov Hi Fedor, is it possible to fix it on Cirrus side? Or what actions do you suggest to fix it on Flutter side?

**Comment by fkorotkov** [comment]
See #41145 🙌

**Comment by christopherfujino** [comment]
@digiter what about Flutter users?

**Comment by digiter** [comment]
> @digiter what about Flutter users?

Filed #41209 to track that.
