### ISSUE TITLE
Printing plugin freeze the app on iOS 13

### ISSUE THREAD

**Issue by DavBfr** [flutter/flutter#41148]
My plugin stopped working on iOS 13, because of threading issues. It's not flutter's fault, just iOS that cannot print on a printer using a background thread.

https://github.com/DavBfr/dart_pdf/issues/153

In iOS 12, the print dialog is not displayed on the main thread. I can then lock it, call some flutter code using channel messages which unlock the print thread and allow it to process the dart data.

In iOS 13, the print dialog is displayed on the main thread and the lock I used totally blocks all the incoming flutter messages, which hangs the application.

A way to fix that would be to dispatch flutter messages in a background thread, not on the main UI thread.

Until that, the printing plugin cannot work: https://pub.dev/packages/printing

**Comment by Davletvm** [comment]
So sorry ! Guys . how can i implement print to printer on Windows 10 ?

**Comment by DavBfr** [comment]
@Davletvm you can take a look at this: https://github.com/DavBfr/dart_pdf/issues/9

**Comment by jmagman** [comment]
@DavBfr If your plugin needs to call an API on the main thread, it's up to that code to dispatch to the main thread.  Once you receive the method channel message, your platform code I believe should be able to run on whatever thread it needs to (maybe around [here](https://github.com/DavBfr/dart_pdf/blob/master/printing/ios/Classes/PrintJob.swift#L58)?  I didn't debug it).

Closing.

**Comment by DavBfr** [comment]
@jmagman actually the iOS print api can run only on the main thread and is blocking. I'm unable to receive any events from Flutter during the print process.

**Comment by jmagman** [comment]
Ah, I understand.  You would like to be able to control the queue on which the channel messages are processed, and make it something other than the main queue.

**Comment by DavBfr** [comment]
Yes. The Android API is generally happy with threads and events, but iOS not so much.

**Comment by gaaclarke** [comment]
You can get around this by using [Dart FFI](https://dart.dev/guides/libraries/c-interop).  I have an example of it [here](https://github.com/gaaclarke/MessagingTiming/blob/c5545bb1bc37ae4fb9c0744de49ad46d8ac4c406/lib/MessagingTiming.dart#L23).

It let's you call any C function from Dart's thread.  From there you can dispatch to any thread you wish, including your background thread or main thread or whatever.
