### ISSUE TITLE
flutterweb application could not be displayed in the official version 77 of Google browse

### ISSUE THREAD

**Issue by jinyuanqing** [flutter/flutter#41155]
It started to run normally and the program was not closed.After about one day, flutterweb application could not be displayed in the official version 77 of Google browser.
error information:
```
hed asset graph completed, took 322ms
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.1s
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 322ms
[INFO]
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.1s
[INFO]
[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 3ms
[INFO]
[INFO] Registering build targets...
[INFO] Starting initial build...
[INFO] Starting resource servers...
[INFO] Serving DevTools at http://127.0.0.1:58632
[INFO] Serving `web` on http://127.0.0.1:58622
[INFO] About to build [web]...
[INFO] Running build...
[INFO] Running build completed, took 292ms
```

**Comment by jinyuanqing** [comment]
[INFO] Running build...
[INFO] Running build completed, took 292ms
[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 375ms
[INFO] Succeeded after 676ms with 0 outputs (0 actions)
[INFO] ------------------------------------------------------------------------
[INFO] Debug service listening on ws://127.0.0.1:58657/FvsKqUgndZo=
Unhandled error detected in the injected client.js script.

You can disable this script in webdev by passing --no-injected-client if it
is preventing your app from loading, but note that this will also prevent
all debugging and hot reload/restart functionality from working.

The original error is below, please file an issue at
https://github.com/dart-lang/webdev/issues/new and attach this output:

NoSuchMethodError: method not found: 'call$0' on null
TypeError: Cannot read property 'call$0' of undefined
    at http://127.0.0.1:58622/dwds/src/injected/client.js:26055:35
    at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:58622/dwds/src/injected/client.js:3110:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:58622/dwds/src/injected/client.js:11704:12)
    at Object._asyncStartSync (http://127.0.0.1:58622/dwds/src/injected/client.js:3075:20)
    at main__closure3.$call$body$main__closure (http://127.0.0.1:58622/dwds/src/injected/client.js:26063:16)
    at main__closure3.call$1 (http://127.0.0.1:58622/dwds/src/injected/client.js:25993:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://127.0.0.1:58622/dwds/src/injected/client.js:3393:16)
    at _CustomZone.runUnary$2$2 (http://127.0.0.1:58622/dwds/src/injected/client.js:13083:182)
    at _CustomZone.runUnaryGuarded$1$2 (http://127.0.0.1:58622/dwds/src/injected/client.js:13011:14)
    at _ControllerSubscription._sendData$1 (http://127.0.0.1:58622/dwds/src/injected/client.js:12564:19)
    at _DelayedData.perform$1 (http://127.0.0.1:58622/dwds/src/injected/client.js:12771:85)

**Comment by ACChe** [comment]
The same

**Comment by jinyuanqing** [comment]
hello.i make it.you need find project_root ,then delete folder name is .dart_tool.congratulation you

> 
> 
> The same

**Comment by ACChe** [comment]
> hello.i make it.you need find project_root ,then delete folder name is .dart_tool.congratulation you
> 
> > The same

Let me check it, thanks your quick reply.

**Comment by ACChe** [comment]
I just found '.dart_tool' file, should I delete it either?

**Comment by jinyuanqing** [comment]
After deleting, you can run it again. Look forward to your successful reply

**Comment by ACChe** [comment]
Not work!

**Comment by jinyuanqing** [comment]
你可以加我qq 2838386460

**Comment by janmoppel** [comment]
Hello @jinyuanqing!

Glad that you were able to find the solution!
Closing this issue, as it has been solved.
