### ISSUE TITLE
barrierDismissible Invalid

### ISSUE THREAD

**Issue by Akun97** [flutter/flutter#41154]
When I use the `showDialog` method, `barrierDismissible` is set to **true**, and clicking on the area outside the pop-up window will not pop up.
![image](https://user-images.githubusercontent.com/41559812/65476585-fc9b6500-deb5-11e9-8f4c-1a9138606be2.png)

**Comment by janmoppel** [comment]
Hello @Akun97 !

Thank you for posting.
Can you please provide more information on the error? It would be very helpful if you could create a self-contained repository, so that your issue could be easily reproduced.

Thank you.

**Comment by janmoppel** [comment]
Hello @Akun97 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
