### ISSUE TITLE
flutter_web TextField can't write num or text

### ISSUE THREAD

**Issue by jinyuanqing** [flutter/flutter#41159]
flutter 1.9.1,显示没有问题.就是无法输入字符,数字,字母 (**Google translate**: Flutter 1.9.1, shows no problem. It is impossible to input characters, numbers, letters.)

[**flutter_web**] There is no problem with the display. Characters, Numbers, letters cannot be entered.
```dart
Container(
  width: 300,
  child: TextField(
    autofocus: true,
    keyboardType: TextInputType.number,
    decoration: InputDecoration(
        labelText: "密码",
        hintText: "密码",
        prefixIcon: Icon(Icons.person)),
  ),
),
```

**Comment by janmoppel** [comment]
Hello @jinyuanqing !

Thank you for posting an issue.
Can you please also post the `flutter doctor -v` command output?

Your question might be a good fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) as well. Flutter has a very active and helpful community there, so feel free to post it there too.

Thank you.

**Comment by jinyuanqing** [comment]
Microsoft Windows [版本 10.0.18362.356]
(c) 2019 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.356], locale zh-CN)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.38.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by nturgut** [comment]
Which browser is the error encountered in?

**Comment by jinyuanqing** [comment]
is google chrome77

**Comment by jonahwilliams** [comment]
@jinyuanqing can you confirm that you're using the unforked web workflow documented at https://flutter.dev/web ?

**Comment by janmoppel** [comment]
Hello @jinyuanqing !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
