### ISSUE TITLE
PageView inside a FlexisbleSpaceBar doesn't keep its state.

### ISSUE THREAD

**Issue by njovy** [flutter/flutter#41157]
## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return <Widget>[
              SliverAppBar(
                expandedHeight: 200,
                flexibleSpace: FlexibleSpaceBar(
                  centerTitle: false,
                  title: Text("TEST"),
                  background: PageView(
                    children: <Widget>[
                      Center(child: Text("1")),
                      Center(child: Text("2")),
                    ],
                  ),
                ),
              ),
            ];
          },
          body: Container(),
        ),
      ),
    );
  }
}
```
Above is a minimal code snippet that can reproduce this bug
1.  Scroll horizontally to scroll to page 2
3. Scroll vertically to collapse AppBar. This will re-draw PageView.
4. The page inside a PageView is back to 1.

I'm trying to use this UI but it doesn't keep PageView's state. Is there any way that I can keep this state in this view hierarchy? Thank you in advance.

**Comment by janmoppel** [comment]
Hello @njovy !

Thank you for posting.
Your question seems to be a good fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) as well. Flutter has a very active and helpful community there, so feel free to post it there too.

Can you please also attach the `flutter doctor -v` command output?

Thank you.

**Comment by njovy** [comment]
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.4 18E226, locale en-KR)
    • Flutter version 1.9.1+hotfix.2 at /Users/captainpark/Library/Flutter/sdk
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/captainpark/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6527
```
@janmoppel Sorry I forgot to attach it!

**Comment by AlanGrey** [comment]
> ## Steps to Reproduce
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatefulWidget {
>   @override
>   State<StatefulWidget> createState() => _MyAppState();
> }
> 
> class _MyAppState extends State<MyApp> {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: Scaffold(
>         body: NestedScrollView(
>           headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
>             return <Widget>[
>               SliverAppBar(
>                 expandedHeight: 200,
>                 flexibleSpace: FlexibleSpaceBar(
>                   centerTitle: false,
>                   title: Text("TEST"),
>                   background: PageView(
>                     children: <Widget>[
>                       Center(child: Text("1")),
>                       Center(child: Text("2")),
>                     ],
>                   ),
>                 ),
>               ),
>             ];
>           },
>           body: Container(),
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> Above is a minimal code snippet that can reproduce this bug
> 
> 1. Scroll horizontally to scroll to page 2
> 2. Scroll vertically to collapse AppBar. This will re-draw PageView.
> 3. The page inside a PageView is back to 1.
> 
> I'm trying to use this UI but it doesn't keep PageView's state. Is there any way that I can keep this state in this view hierarchy? Thank you in advance.


I have this problem too, and it will be Obvious Caton when I quickly expand；Probably why the interface rebuilds the rendering.
If there's a solution, can you let me know ?

Thank you.

**Comment by RafaelRaimund0** [comment]
I am facing this same issue, everytime I collapse my SliverAppBar, the widget inside flexibleSpace loses it's state. Is there a workaround for this?

thanks

**Comment by njovy** [comment]
@RafaelRaimund0 When I posted this I wasn't familiar with Flutter widget rendering and state. You can have a PageController and reuse that controller to PageView to keep its position.

**Comment by RafaelRaimund0** [comment]
oh, nice. Thank you
