### ISSUE TITLE
在xcode 升级到11后,ios升级到13的时候会报下面的这个错误 (Google translate: After upgrading xcode to 11, ios will report the following error when upgrading to 13.)

### ISSUE THREAD

**Issue by romance-wm** [flutter/flutter#41158]
```
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    fatal error: lipo: -extract armv7 specified but fat file: /Users/momeng/Documents/flutter_project/law-book-test/build/ios/Debug-iphoneos/Runner.app/Frameworks/shared_preferences.framework/shared_preferences does not contain that architecture
    Failed to extract armv7 for /Users/momeng/Documents/flutter_project/law-book-test/build/ios/Debug-iphoneos/Runner.app/Frameworks/shared_preferences.framework/shared_preferences. Running lipo -info:
    Architectures in the fat file: /Users/momeng/Documents/flutter_project/law-book-test/build/ios/Debug-iphoneos/Runner.app/Frameworks/shared_preferences.framework/shared_preferences are: arm64
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build systemnote: Planning buildnote: Constructing build description
Could not build the precompiled application for the device.
```

**Comment by iusn** [comment]
Please use English Thank you

**Comment by romance-wm** [comment]
After upgrading xcode to 11, ios will report the following error when upgrading to 13

2019-09-24 14:35:29.392 ios-deploy[1966:17941] [ !! ] Error 0xe800007f: Device doesn't support wireless sync. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)
Could not install build/ios/iphoneos/Runner.app on 00008020-00063C9A0198003A.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on momeng的iPhone.

**Comment by janmoppel** [comment]
Hello @romance-wm !

Thank you for posting an issue.
We've translated this issue's title into English using Google Translate. If you're comfortable writing in English, please check the translation and update it if necessary.

Can you please also provide an output of the `flutter doctor -v` command?

Thank you.

**Comment by Fongim** [comment]
I also encountered this problem when I switch iPhone device, and solved by deleting the "flutter-project-path/build/" and "flutter-project-path/ios/DerivedData/" directory.

**Comment by iusn** [comment]
> I also encountered this problem when I switch iPhone device, and solved by deleting the "flutter-project-path/build/" and "flutter-project-path/ios/DerivedData/" directory.

Hi
i can't find 
flutter-project-path/ios/DerivedData/

**Comment by Fongim** [comment]
> > I also encountered this problem when I switch iPhone device, and solved by deleting the "flutter-project-path/build/" and "flutter-project-path/ios/DerivedData/" directory.
> 
> Hi
> i can't find
> flutter-project-path/ios/DerivedData/

Check if it is set to 'Relative' in Xcode -> Preferences -> Locations -> Derived Datas. If it is 'Defalut', you can view the directory path indicated under the option, and delete the project-related DerivedData in this directory. I am also not sure if this operation really works to solve this issue, just delete the cache.

<img width="597" alt="Screenshot2019-11-1414 35 39" src="https://user-images.githubusercontent.com/20736775/68832520-1e61dd00-06ec-11ea-8c95-002fbca27254.png">

**Comment by VladyslavBondarenko** [comment]
Similar to https://github.com/flutter/flutter/issues/22749
@romance-wm I hope you've solved the issue, closing,
comment please if it's not so and I'll reopen it.
Thank you
