### ISSUE TITLE
Firebase storage: user does not have permission to access this object while downloading files

### ISSUE THREAD

**Issue by shivapht** [flutter/flutter#41168]
## Steps to Reproduce

This is my FirebaseOptions and the app.
```
app = await FirebaseApp.configure(
      name: "myapp",
      options: FirebaseOptions(
        googleAppID: Platform.isAndroid
            ? "1:.....a25e"
            : "1:.....a25e",
        apiKey: ".....Af8A",
        projectID: "myapp",
      )
    );
    storage = FirebaseStorage(
        app: app, 
        storageBucket: "gs://myapp.appspot.com/",
      );
My storage rules look like below

service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read: if request.auth != null;
      allow write: if request.auth.uid == 'xyz@abc.com';
    }
  }
}
```
The question I have is how do I pass the logged in user to FirebaseApp.configure or FirebaseStorage?
If I remove the request.auth != null in the allow read then it works fine.

The line of code I am using to download the file is below

StorageMetadata metadata = await storage.ref().child(filename).getMetadata(); 

I don't want to make my files public like some solutions have proposed which is highly insecure.

## Logs

```
E/StorageException( 8961): StorageException has occurred.
E/StorageException( 8961): User does not have permission to access this object.
E/StorageException( 8961):  Code: -13021 HttpResult: 403
E/StorageException( 8961): {  "error": {    "code": 403,    "message": "Permission denied. Could not perform this operation"  }}
```

**Comment by shivapht** [comment]
Figured it out. Removing the FirebaseApp.configure worked.

**Comment by kroikie** [comment]
@shivapht

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1075. Any further collaboration will be done there.
