### ISSUE TITLE
flutter 集成到Android 原生项目中 编译慢了许多 (Google translate: Flutter integrated into Android native projects Compiled a lot slower)

### ISSUE THREAD

**Issue by Juneor** [flutter/flutter#41162]
flutter 集成到Android 原生项目中 编译慢了许多 (**Google translate:** Flutter integrated into Android native projects Compiled a lot slower)

**Comment by janmoppel** [comment]
Hello @Juneor !

Thank you for posting.
We've translated this issue's description into English using Google Translate. If you're comfortable writing in English, please check the translation and update it if necessary.

Can you please provide the `flutter doctor -v` command output too?

Also, it would be very helpful if you could create a self-contained repository, so that this behaviour could be easily reproduced.

Thank you.

**Comment by Juneor** [comment]
Microsoft Windows [版本 10.0.18362.356]
(c) 2019 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.356], locale zh-CN)
    • Flutter version 1.9.1+hotfix.2 at F:\Android\flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at F:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = F:\Android\sdk
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA 2019.1.2
    • Flutter plugin version 39.0.2
    • Dart plugin version 191.8423

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

C:\Users\Administrator>

**Comment by blasten** [comment]
Compilation time depends on the size of the app you are building. Is the issue when building release, debug or all?  Does it build at the end?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
