### ISSUE TITLE
One project for Flutter app and Flutter module

### ISSUE THREAD

**Issue by askarsyzdykov** [flutter/flutter#41176]
I created Flutter project via Android Studio that includes directory 'android'. Now, I want to use the project as module, for building 'aar' file, also I need run app as Flutter project. So I added module section in pubspec.yaml, but when I run 'flutter build aar' in a terminal, it show an error:

> The build process for Android has changed, and the current project configuration is no longer valid. Please consult
  https://github.com/flutter/flutter/wiki/Upgrading-Flutter-projects-to-build-with-gradle
for details on how to upgrade the project.

If I rename 'android' then 'flutter build aar' works fine. But it's bad approach.

```
[✓] Flutter (Channel master, v1.10.6-pre.35, on Mac OS X 10.14.6 18G95, locale en-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2018.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

```

**Comment by jmagman** [comment]
I don't think a flutter project existing as both a module and app are currently supported.
Out of curiosity, why do you want it as an app and module?  Or are you trying to one-time convert it from a project to a module?

**Comment by askarsyzdykov** [comment]
@jmagman 
I'm developing an standalone app, that also must be a module of other app (aka SDK)

**Comment by jmagman** [comment]
> @jmagman
> I'm developing an standalone app, that also must be a module of other app (aka SDK)

Can your stand-alone app be a single-Flutter view version of an add-to-app host that imports your Flutter module?  That's all a flutter created app is, basically.

**Comment by jmagman** [comment]
Closing this as not a supported configuration.  There's lots of places in the tool that drop into one case or the other depending on the presence of `.android` and `.ios` directories.
