### ISSUE TITLE
gradlew.bat error firebase

### ISSUE THREAD

**Issue by tejasbs44** [flutter/flutter#41174]
I have issues with a classpath `com.google.gms:google-services:4.3.0`. 
When I added it to the dependencies in `android/build.gradle` to get the Firebase Authentication and Google Sign-in working, this classpath started to tell me some things are deprecated and returned the error below:

```
* Error running Gradle:
ProcessException: Process "C:\Users\QSERVERS\Desktop\FlutterApps\FlutterGrocery-ShoppingAppUI\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.


* Where:
Build file 'C:\Users\QSERVERS\Desktop\FlutterApps\FlutterGrocery-ShoppingAppUI\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 52s
  Command: C:\Users\QSERVERS\Desktop\FlutterApps\FlutterGrocery-ShoppingAppUI\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.
```

**Comment by janmoppel** [comment]
Hello @tejasbs44 !

Thank you for posting an issue.
Seems like this problem has been reported already here: #38163. The solution was also found: https://github.com/flutter/flutter/issues/38163#issuecomment-520429066
Lowering the `google-services` version from the `4.3.0` to `4.2.0` should help. 

Closing this issue. If proposed solution won't work for you, please, feel free to open a new issue.

Thank you.

**Comment by kroikie** [comment]
@tejasbs44

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/328. Any further collaboration will be done there.

**Comment by iam-human** [comment]
Ok , hello guys, i've lowered it, its working , but raises new problem , it fire-store error and ect .. so ? how to solve it ?
