### ISSUE TITLE
Error，when I Get dependencies for flutter web,my sdk version is flutter_windows_v1.9.1+hotfix.2-stable.

### ISSUE THREAD

**Issue by Juneor** [flutter/flutter#41183]
```
F:\Android\flutter\bin\flutter.bat --no-color packages get
Running "flutter pub get" in flutter_note...                    
Because flutter_note depends on flutter_web any which doesn't exist (could not find package flutter_web at https://pub.dartlang.org), version solving failed.

```

**Comment by BondarenkoStas** [comment]
@Juneor which exactly `flutter_note` you using? There is no such in standard flutter packages, but I found a couple of implementations.

**Comment by janmoppel** [comment]
Hello @Juneor !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
