### ISSUE TITLE
iOS push notification NOT working. Important. Firebase_messaging, iOS 13

### ISSUE THREAD

**Issue by khainhero** [flutter/flutter#41180]
Push notification does not seem to work on iOS 13 device nor on my iOS 12.4.1 device on stable 1.9.1.
Seems to be 2 separate issues as well. 

1) in Flutter Stable 1.9.1, push notifications do not appear on my iOS 12.4.1 device, when the always worked before on older flutter versions.
2) iOS 13 device does not receive push notifications at all

Some reading available from oneSignal
https://onesignal.com/blog/ios-13-introduces-4-breaking-changes-to-notifications/

**I updated my device OS(personal) version to 13, cannot further test without downgrading it back to 12.4.1.** and I do not have a spare iPhone available.

_Thank you_

Also for other users, can you please input our own issue related to the mentioned. 
Things such as current physical device iOS software version and flutter channel along with its version number. so we can compile a list of where in flutter and iOS(versions) things just stopped working.

Push notification is and should be very **### critical** part of a persons or companies application when used right. I hope we can address the issues and come up with a solution.

**Comment by janmoppel** [comment]
Hello @khainhero !

Thank you for posting an issue.
Can you please provide the `flutter doctor -v` command output as well? 
Also, it would be very helpful if you could create a self-contained repository, so that your issue could be easily reproduced.

This ticket might be related to your problem as well: #28196. Can you please check, whether solutions proposed in that thread work for you?

Thank you.

**Comment by khainhero** [comment]
Hey @janmoppel 
I was going to post this issue while ago but I left it alone as I thought this would be a priority fix. Just wondering, are notifications working for anyones iOS device using flutter stable 1.9.1?

The #28196 issue, I know that issue its an old one which im sure has been fixed for a while now.

My real problem is, I do not even see the notification in my notification center on my iPhone device. No alert noise, no visual notification feed, no badge. On my cloud function, it says it has sent the notification with success: 
```
{ results: [ { messageId: '0:1569320516749370%c296d48f********' } ],
  canonicalRegistrationTokenCount: 0,
  failureCount: 0,
  successCount: 1,
  multicastId: 71085841453******** }
```
**flutter doctor -v summary:**
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/****/Desktop/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/****/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • ****'s iPhone • 2bcdab4c5e287a5691432b70c5d083e815dce368 • ios • iOS 13.0

• No issues found!
```

**Comment by billy124** [comment]
My app is able to get an IOS Token Firebase push notification token, however, none of the messages sent via Firebase are being  received on the device. 

I also have an IOS 13 device


```dart
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by stonekase** [comment]
I am also experiencing this same problem.my application depends on firebase push notifications for 
it's functionality.
All flutter channels tried dont receive firebase push- messages on ios 13.

flutter  doctor Result 
==================
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.6-pre.39, on Mac OS X 10.14.6 18G95, locale en-NG)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by stonekase** [comment]
> Hello @khainhero !
> 
> Thank you for posting an issue.
> Can you please provide the `flutter doctor -v` command output as well?
> Also, it would be very helpful if you could create a self-contained repository, so that your issue could be easily reproduced.
> 
> This ticket might be related to your problem as well: #28196. Can you please check, whether solutions proposed in that thread work for you?
> 
> Thank you.

they are not related

**Comment by divan** [comment]
Not sure, if it's related, but after upgrading to iOS 13 I also stuck for a couple of hours with a lack of push notifications on the device. I thought it's something with my changes to code, but I had another iOS device with iOS 12, which confirmed that code is fine.

The issue resolved suddenly on its own just after disconnecting iPhone from Mac – I suddenly started receiving push notifications for my app.

Sorry for useless input, but maybe more people had the same experience without reporting.

**Comment by khainhero** [comment]
> Not sure, if it's related, but after upgrading to iOS 13 I also stuck for a couple of hours with a lack of push notifications on the device. I thought it's something with my changes to code, but I had another iOS device with iOS 12, which confirmed that code is fine.
> 
> The issue resolved suddenly on its own just after disconnecting iPhone from Mac – I suddenly started receiving push notifications for my app.
> 
> Sorry for useless input, but maybe more people had the same experience without reporting.

Hey @divan 

That is very interesting, are you using firebase_messaging plugin? what version if so?

Can you post your flutter doctor -v summary here

to confirm, your notifications are working now for both iOS 13 and 12?

Thanks for the input

**Comment by stonekase** [comment]
> > Not sure, if it's related, but after upgrading to iOS 13 I also stuck for a couple of hours with a lack of push notifications on the device. I thought it's something with my changes to code, but I had another iOS device with iOS 12, which confirmed that code is fine.
> > The issue resolved suddenly on its own just after disconnecting iPhone from Mac – I suddenly started receiving push notifications for my app.
> > Sorry for useless input, but maybe more people had the same experience without reporting.
> 
> Hey @divan
> 
> That is very interesting, are you using firebase_messaging plugin? what version if so?
> 
> Can you post your flutter doctor -v summary here
> 
> to confirm, your notifications are working now for both iOS 13 and 12?
> 
> Thanks for the input

I do receive the push notificat when my app is in the background but the  data partnever comes through.

**Comment by divan** [comment]
@khainhero yes, correct - I have it working both on iOS 13.1 and iOS 12.
I use latest `firebase_messaging` version at this moment - 5.1.6.

Attaching <details>
<summary>my `flutter doctor` output</summary>
<pre>$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.6-pre.29, on Mac OS X 10.14.6 18G95, locale en-ES)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio (version 3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
</pre>
</details

**Comment by stonekase** [comment]
> @khainhero yes, correct - I have it working both on iOS 13.1 and iOS 12.
> I use latest `firebase_messaging` version at this moment - 5.1.6.
> 
> Attaching
> 
> my `flutter doctor` output

hi Divan, Please can you be kind enough to create a sample of your working implementation of firebase messaging for the above mentioned scenario and be kind to share a link to the snippet here . just for my sanity as i cannot get it to capture sent data.
Secondly you are using the flutter master branch which is not advised for production(Though i am currently on it , so far it works). Many Thanks in advance.

**Comment by divan** [comment]
@stonekase I'm not sure I undestand "sample of your working implementation of firebase messaging" part? I'm just using a plugin in the most default way possible.

As for the master branch – yeah, I know, it's just stable/dev have issues with iOS13 devices now, only master works fine for me.

**Comment by ThinkDigitalSoftware** [comment]
I'm having an issue and I'm on a newer master I believe. 
[✓] Flutter (Channel master, v1.10.6-pre.69, on Mac OS X 10.15 19A573a, locale en-US)

**Comment by jawad89** [comment]
I am not able to receive push notifications in iOS, whether they are sent via the Firebase console or via our Azure Hub. The notifications badge appears on the device when the app is in the background, but when the app is in the foreground, the notifications are not received.

By removing the **Background Fetch** and **Remote notifications** from the background modes, allows app to receive the notification event, but it is not able to parse the message due to this error: **add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.**
On adding **Background Fetch** and **Remote notifications** to the Plist, the app stops giving any sort of indication that the notification are being received.

![Screenshot 2019-09-27 at 3 21 59 PM](https://user-images.githubusercontent.com/7666210/65762848-6e381500-e13b-11e9-91c2-f45055c87d10.png)

Flutter doctor -v summary

[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F132, locale en-GB)
    • Flutter version 1.9.1+hotfix.2 at /users/jawwadhassan/Documents/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jawwadhassan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Mac’s iPhone • d982ff3b1c2b0942aa59ec348e7e0a1457e7c244 • ios • iOS 12.4.1

• No issues found!

**Comment by opringle** [comment]
experiencing the same issue.

Flutter doctor -v summary

[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-CA)
    • Flutter version 1.9.1+hotfix.2 at /Users/opringle/development/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/opringle/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/opringle/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

**Comment by HuKhong** [comment]
Don't forget to call the configure function. (even if you do not intent to handle the message)
(i took me a few days to figure out this reason)

_firebaseMessaging.configure(
       onMessage: (Map<String, dynamic> message) async {
           //print("onMessage: $message");
       },
       onBackgroundMessage: (Map<String, dynamic> message) async {
          //print("onBackgroundMessage: $message");
       },
       onLaunch: (Map<String, dynamic> message) async {
         //print("onLaunch: $message");
       },
       onResume: (Map<String, dynamic> message) async {
         //print("onResume: $message");
       },
    );

**Comment by opringle** [comment]
Solved my problem! I needed to add the line `_firebaseMessaging.requestNotificationPermissions();`. This is only required on IOS devices and mentioned towards the end of the [installation instructions](https://pub.dev/packages/firebase_messaging).

**Comment by sanathe06** [comment]
> Solved my problem! I needed to add the line `_firebaseMessaging.requestNotificationPermissions();`. This is only required on IOS devices and mentioned towards the end of the [installation instructions](https://pub.dev/packages/firebase_messaging).

Could you please share the result of "flutter doctor".

**Comment by khainhero** [comment]
Okay. So I solved my issue. 
At first I created a new Flutter project, created new certificates and provisioning profile as well as push notification key(iOS xcode stuff). 
The notifications worked as expected on the newly created pet project.

I also have an iPad Pro with 12.4 iOS version. 

On the pet project, notifications works on both my iPad Pro(12.4) and iPhone SE (13.1).

As I did not want to migrate my old project onto the new one, i further investigated.

I did not have the following code in my project:

```
    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print("onMessage: $message");
        _showItemDialog(message);
      },
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch: $message");
        _navigateToItemDetail(message);
      },
      onResume: (Map<String, dynamic> message) async {
        print("onResume: $message");
        _navigateToItemDetail(message);
      },
    );
```
Weird part is, my app was getting notifications in its notification tray when I did not have that piece of code. When i upgraded to new stable version of flutter thats when things stopped working. 

I was going to add this code into my app later on, did so today and configured the onLaunch(gets different Map Object depending on if you are on your on iOS or android device).

Here is my flutter doctor for my recent testings:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.6, on Mac OS X 10.14.6 18G95, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!
```

I hope this can help others out

**Comment by stonekase** [comment]
Just for anyone interested, it seems the only issue i was facing with the push notification was the fact that it doesnt log in on the terminal which made me think it doesnt come through.

Using a widget (Text-widget) to output messages in the notification onMessage displayed the data in the widget.See images below.

base) omojos-MacBook-Pro:aiki_ng_flutter_app ash$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.7-pre.109, on Mac OS X 10.14.6 18G95, locale en-NG)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

**### Therefore the only issue is with the print to the terminal .**

<img width="757" alt="Screenshot 2019-10-02 at 10 23 36 AM" src="https://user-images.githubusercontent.com/5037778/66033296-e36e6600-e4fe-11e9-918d-2983eda638f3.png">
<img width="413" alt="Screenshot 2019-10-02 at 10 24 20 AM" src="https://user-images.githubusercontent.com/5037778/66033299-e5d0c000-e4fe-11e9-910b-9a073804cf67.png">

**Comment by dopefaceee** [comment]
yup same here, it's not working on iOS 13. I have to use ios 12.4 then trigger with dialog like @stonekase did to show onMessage working or not. any news about this?

**Comment by Cascoid** [comment]
Also having this exact same issue. No sign of a notification but the device registers fine to the firebase database.

Not sure if this is a flutter issue or firebase_messaging package issue. Would be great to get any updates from anyone who finds workarounds.

**Comment by billy124** [comment]
Anyone having this issue - please check out this answer: https://stackoverflow.com/questions/58300407/flutter-push-notification-not-displaying-on-ios/58340253#58340253

**Comment by kroikie** [comment]
@khainhero

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1041. Any further collaboration will be done there.

**Comment by xellDart** [comment]
same error

**Comment by KhayyamA47** [comment]
Same error

**Comment by rignaneseleo** [comment]
same error here. any workaround?

**Comment by ayman3000** [comment]
I think the problem is in the last firebase_messaging plugin, After 3 days of not receiving push notifications on iOS devices, I used firebase_messaging version 5.1.6...and it finally works perfectly.

**Comment by docbohanh** [comment]
> I think the problem is in the last firebase_messaging plugin, After 3 days of not receiving push notifications on iOS devices, I used firebase_messaging version 5.1.6...and it finally works perfectly.

It also works for me 😍

**Comment by vtnb** [comment]
in AppDelegate.swift
`import FirebaseMessaging`

`func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    Messaging.messaging().apnsToken = deviceToken
}`

It work for me.

**Comment by docbohanh** [comment]
in AppDelegate.swift
`import FirebaseMessaging`
```
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    Messaging.messaging().apnsToken = deviceToken
}
```
It work for me.

**Comment by callumclift** [comment]
@ayman3000 how did you manage to use 5.1.6? Whenever I put it into my pubspec the oldest version it pulls in is 5.1.8

**Comment by mikesun23** [comment]
my problem is that 'onResume' and 'onLaunch' not working, i.e if app is running foreground, it can receive notifications. while doesn't work when running background and terminated. 

I used firebase_messaging ^5.1.6, the new version 6 doesn't work for all cases.

I created APN certs, and auth key, uploaded to Firebase Cloud Messaging section.

in Xcode, I selected 'Background fetch' and 'Remote Notifications' and 'Background Processing'.

I have this snippet in 'AppDelegate.m':
if (@available(iOS 10.0, *)) {
      [UNUserNotificationCenter currentNotificationCenter].delegate = 
                   (id<UNUserNotificationCenterDelegate>) self;
    }

I have FCM config code in my app:
fcm.configure(
  onMessage: (Map<String, dynamic> message) async {...}
  onLaunch: (Map<String, dynamic> message) async {...}
  onResume: (Map<String, dynamic> message) async {...}
)

clean, rebuild so many times. for Android everything works like a charm. but ios....

anyone?

**Comment by YonatanAmitzur** [comment]
i need to finally understand - there is no way to get onBackgroundMessage to work in IOS ?

**Comment by sunnyseeds** [comment]
Same problem here. Working when iOS app is in foreground and not working background. Both push from server and from firebase console. When I tap app to put it back in foreground, it then prints to console the push that was received while it was in background.

**Comment by YonatanAmitzur** [comment]
did any one got it to work for ios background push ???

**Comment by khainhero** [comment]
> my problem is that 'onResume' and 'onLaunch' not working, i.e if app is running foreground, it can receive notifications. while doesn't work when running background and terminated.
> 
> I used firebase_messaging ^5.1.6, the new version 6 doesn't work for all cases.
> 
> I created APN certs, and auth key, uploaded to Firebase Cloud Messaging section.
> 
> in Xcode, I selected 'Background fetch' and 'Remote Notifications' and 'Background Processing'.
> 
> I have this snippet in 'AppDelegate.m':
> if (@available(iOS 10.0, *)) {
> [UNUserNotificationCenter currentNotificationCenter].delegate =
> (id) self;
> }
> 
> I have FCM config code in my app:
> fcm.configure(
> onMessage: (Map<String, dynamic> message) async {...}
> onLaunch: (Map<String, dynamic> message) async {...}
> onResume: (Map<String, dynamic> message) async {...}
> )
> 
> clean, rebuild so many times. for Android everything works like a charm. but ios....
> 
> anyone?

I think null is being caught but not handled when using onLaunch and onResume for iOS.

example:  I have for onLaunch the following sample code:
```
if(message['data']['something'] == "something"){ //for Android
 //do something
}
if(message['something'] == "something"){ //for iOS
 //do something
}
```

Will not work.. because `['data']['something']` is null if your on iOS.. which i guess goes unhandled

the code works fine on Android though

to make it work, I have to check for platform(if its Android or iOS) in the onResume and onLaunch. Then if its iOS, we should only check the `if statement` for iOS message Map

my fix:

```
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch: $message");
        Platform.isAndroid ? 
        handleAndroidNavigation(message)
         : handleIosNavigation(message);
      },
      onResume: (Map<String, dynamic> message) async {
        print("onResume: $message");
        Platform.isAndroid ? 
        handleAndroidNavigation(message)
         : handleIosNavigation(message);
      },
```

thanks

**Comment by YonatanAmitzur** [comment]
so i got it to work for iOS background push, FLUTTER FIREBASE MESSAGING PLUGIN DOES SUPPORT IT !!!!!!!!!!!  (just make sure you add to payload contentAvailable:true)
and i got the background notification into to the onResume handler in flutter (when the iOS app is in background just like the background handler - while the background handler works only for android)

but there is a problem and the problem is if you want to handle background push on iOS when the app is killed (not running in background) - and for that case, as i understand i need to implement push using pushKit - there is a flutter plugin for that 

plugin:
https://pub.dev/packages/flutter_voip_push_notification

and you can integrate with firebase
see link below:

https://stackoverflow.com/questions/37326450/does-firebase-cloud-messaging-support-voip-pushkit-services

**Comment by LOG-TAG** [comment]
@YonatanAmitzur this is the right wayto send contentAvailable true payload ?? system tray failed get notification in simulator 12.4 
<img width="995" alt="Screenshot 2020-02-12 at 11 14 04 PM" src="https://user-images.githubusercontent.com/1190344/74361718-6e386900-4ded-11ea-9166-e75c2bdeaa95.png">

**Comment by YonatanAmitzur** [comment]
@LOG-TAG, i am using nodejs server with firebase messaging admin so in that environment i use contentAvailable:true, but node just translate it to the original way which is  content-available and the value is 1

**Comment by LOG-TAG** [comment]
@YonatanAmitzur  can you share the payload structure for ios? are able to get image-rich notifications via node js ?

**Comment by ManKeomorakort** [comment]
> so i got it to work for iOS background push, FLUTTER FIREBASE MESSAGING PLUGIN DOES SUPPORT IT !!!!!!!!!!! (just make sure you add to payload contentAvailable:true or content-available:1 AND onBackgroundMessage: Platform.isIOS ? null : myBackgroundMessageHandler)
> and i got the background notification into to the onResume handler in flutter (when the iOS app is in background just like the background handler - while the background handler works only for android)
> 
> ON ANDROID THERE ARE NO PROBLEMS!!!!!
> 
> from here until the end of this post i relate only to IOS!!!
> 
> NOTE FOR IOS CASE:
> in the case of background push for some it invoke the onResume handler and some times onBackgroundMessage (even onBackgroundMessage: Platform.isIOS ? null : myBackgroundMessageHandler), BUT IT WORKS !!!
> 
> ISSUES ON IOS:
> ISSUE 1 : the problem is if you want to handle background push on iOS when the app is killed (not running in background) - and for that case, you need to send push without contentAvailable:true or content-available:1 (apple assume that if you force killed the app you dont want to get silent push)
> 
> ISSUE 2 : i found out that for flutter the plugins for
> firebase_messaging and flutter_local_notifications have some issues (on ios only) when used in the same project
> 
> When use both in the same project for ios the onResume dont work,
> for my situation it did not matter because i use silent notification (contentAvailable:true)
> that means that when the app is in the foreground i get onMessage (then i use local notification) and when the app is in the background is get onResume or onBackgroundMessage (then i use local notification)
> 
> if the app is killed i send regular push (not silent - without contentAvailable:true) - in this case the push pop up and it is not local notification then i get the onLunch if the user tap on the notification
> 
> THAT IS ALL :)

Your solution work well

**Comment by dgana** [comment]
Thanks! your solution works for me @YonatanAmitzur

**Comment by campioncino** [comment]
How can I handle the background notification on iOS when the app is running in Background?
