### ISSUE TITLE
use webview_flutter error

### ISSUE THREAD

**Issue by gitzhangliang** [flutter/flutter#41185]
use webview_flutter can not open pdf file. it is no response

**Comment by BondarenkoStas** [comment]
@gitzhangliang How exactly you are trying to open it? Can you please share a reproducible code example? are there any logs when you run it with -v?
Please provide your webview_flutter version and your flutter doctor -v output.

**Comment by gitzhangliang** [comment]
return WebView(
          initialUrl: 'https://files.alicdn.com/tpsservice/b3b75f788cd433e2a7f9fe9a56880410.pdf',
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController webViewController) {
            _controller.complete(webViewController);
          },

I only replace initialUrl for official example. use webview_flutter  i can open image、html、txt  **file,**
but can't open **pdf** file
this is my webview_flutter version     webview_flutter: ^0.3.14+1


Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.17763.737], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.2)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by deandreamatias** [comment]
Please change this name to 
[webview_flutter] Can't open online pdf file

**Comment by VladyslavBondarenko** [comment]
Please follow up on https://github.com/flutter/flutter/issues/48245, closing current issue as duplicate
