### ISSUE TITLE
webview_flutter Unable to create JsDialog without an Activity

### ISSUE THREAD

**Issue by bineanzhou** [flutter/flutter#41186]
```
public final class WebViewFactory extends PlatformViewFactory {
  private final BinaryMessenger messenger;
  private final View containerView;

  WebViewFactory(BinaryMessenger messenger, View containerView) {
    super(StandardMessageCodec.INSTANCE);
    this.messenger = messenger;
    this.containerView = containerView;
  }

  @SuppressWarnings("unchecked")
  @Override
  public PlatformView create(Context context, int id, Object args) {
    Map<String, Object> params = (Map<String, Object>) args;
//    return new FlutterWebView(context, messenger, id, params, containerView);
    return new FlutterWebView(containerView.getContext(), messenger, id, params, containerView);
  }
}
```

**Comment by BondarenkoStas** [comment]
@bineanzhou Please provide your flutter doctor -v output and webview_flutter version.
May be connected to #34853.

**Comment by bineanzhou** [comment]
my ext 
https://github.com/bineanzhou/webview_flutter_ext

**Comment by bineanzhou** [comment]
> @bineanzhou Please provide your flutter doctor -v output and webview_flutter version.
> May be connected to #34853.

my ext
https://github.com/bineanzhou/webview_flutter_ext

**Comment by TahaTesser** [comment]
Hi @bineanzhou 

To better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem

Thank you

**Comment by TahaTesser** [comment]
Hi @bineanzhou 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
