### ISSUE TITLE
Issue with flutter webview : platform_view_layer.cc(38)] Trying to embed a platform view but the PaintContext does not support embedding

### ISSUE THREAD

**Issue by sohitEngg** [flutter/flutter#41193]
There are only a few places where flutter troubles with UI differences between android and iOS. Here below is the one.

I am trying to render an HTML into WebView which consists of css stylesheet link with url as per below:

```
"<html><head><link type="text/css" rel="stylesheet" href="https://<domain_url>.com/css/main.css"></head><body><p>Some text with HTML tags</body></html>"
```

This is working excellent in Android and webview rendering everything in place but in iOS I am facing below issue in console.
```
[VERBOSE-2:platform_view_layer.cc(38)] Trying to embed a platform view but the PaintContext does not support embedding
```
As per the standard guidelines I already had added below lines in info.plist.
```
<key>io.flutter.embedded_views_preview</key>
	<string>yes</string> .    [also tried with boolean value </true>]
```

& 

```
<key>NSAppTransportSecurity</key>
    <dict>
       <key>NSAllowsArbitraryLoads</key>
       <true/>
       <key>NSAllowsArbitraryLoadsInWebContent</key>
       <true/>
    </dict>
```

But this did not make any help. Same error.

Please have a look on the web view code as per below and let me know if there is any chance to resolve this problem.

```
WebView(
              initialUrl: '',
              onPageFinished: (some) async {
                if (some != "about:blank") {
                  setState(() {
                    _isLoading = false;
                  });
                }
              },
              javascriptMode: JavascriptMode.unrestricted,
              onWebViewCreated: (WebViewController webViewController) {
                _webViewController = webViewController;
                _loadHtmlFromString(widget.data);
              },
```

````
void _loadHtmlFromString(String data) {
    _webViewController.loadUrl(Uri.dataFromString(data,
            mimeType: 'text/html', encoding: Encoding.getByName('utf-8'))
        .toString());
  }
```

Any help or comment would be highly appreciated.

**Comment by BondarenkoStas** [comment]
Just to gather here some of those ios differences in platform view: #26893, #39616, #33568.

**Comment by iapicca** [comment]
Hi @sohitEngg 
if the issue persist with the latest stable version of flutter
could you please provide your updated `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @sohitEngg 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
