### ISSUE TITLE
[web]: <describe issue here>

### ISSUE THREAD

**Issue by dngwu** [flutter/flutter#41192]
Hello I'm having a hard time setting Flutter up on my computer. I would like assistance and will be open to screen sharing. Please help me get the android tool chain and connect devices. Please and thanks 

![help](https://user-images.githubusercontent.com/55747853/65512832-a7ecef80-de9f-11e9-9170-a7a5f3f187a3.PNG)

**Comment by BondarenkoStas** [comment]
@dngwu This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
