### ISSUE TITLE
exit(0) in dart crashes engine

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4119]
Run this with flutter:

``` dart
import 'dart:io';
void main() {
  exit(0);
}
```

I've seen this crash with signal 6 and signal 11.

**Comment by chinmaygarde** [comment]
What is meant to happen here? Obviously, not crash but even if the engine successfully cleans up after itself, applications are not meant to return from `UIApplicationMain` on iOS.

**Comment by Hixie** [comment]
Is there no way to quit an app on iOS?

**Comment by chinmaygarde** [comment]
Pressing the home button only backgrounds the application. When the user force quits it by swiping it away, the application dies with a 0xDEADFA11 exception (there are other exceptional cases too). The application may not die on its own.

**Comment by Hixie** [comment]
The use case here is running a benchmark on the device. On Android, we send an intent, it launches the app, the app does its benchmark, dumps the result to the log, and quits.

**Comment by Hixie** [comment]
I believe we found a workaround to this (just leave it running, IIRC).
