### ISSUE TITLE
Add OnEmpty Widget to ListView.builder()

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#41191]
## Use case

When using `ListView.builder()` you can provide an `itemBuilder` and `itemCount`.
But what if `itemCount` is zero(when the list is empty)? Usually a different `Widget` would be shown if a collection is empty.

## Proposal

I'd propose a small enhancement to the `ListView.builder()` .

Provide an extra property let's say 'onEmptyWidget'.
This `Widget` would be shown when the list has no elements.
This also eliminates the boilerplate check for `myList.IsEmpty` (or `itemCount == 0`), this would be handled by the builder for us.

This would however change the return type of the builder to `Widget` instead of `ListView`.

**Comment by JAicewizard** [comment]
It could return a ListView with one item right?
Or am I missing something(likely)

**Comment by navaronbracke** [comment]
Well, I meant to give developers an option to specify their own custom Widget, lets say you have some fancy 'EmptyListWidget', then you could pass this in.

**Comment by QuentinSc** [comment]
+1000

**Comment by darshithedpara** [comment]
Any updates on this?

**Comment by HansMuller** [comment]
Sorry to have let this drop and @QuentinSc - thanks for the enthusiasm. It does seem like a reasonable feature to add and a reasonably small feature at that.

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by darrenaustin** [comment]
While I understand the desire to have this handled more directly by the framework, adding an emptyListWidget parameter to `ListView.builder()` just doesn't work very well. As `ListView.builder()` is a constructor we can't change its return type to `Widget`. It must return a `ListView`. 

Therefore the best we can do with this would be to have it return a list of one item (the emptyListWidget parameter). This is not great, as the user can still scroll (or overscroll) this UI, and it doesn't give you a lot of control of the layout of the item. I made an attempt at adding an `emptyListWidget` parameter to the builder method in this PR: #56350 in case you would like to play with this yourself. 

The better solution is for the app to just swap out the ListView at build time with
whatever UI they need for the empty list state. While this may be considered boilerplate, it is only a single line more than what you would need if we added this param to the builder method:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(EmptyListApp());
}

class EmptyListApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.from(colorScheme: ColorScheme.light()),
      home: EmptyListTest(),
    );
  }
}

class EmptyListTest extends StatefulWidget {
  @override
  _EmptyListTestState createState() => _EmptyListTestState();
}

class _EmptyListTestState extends State<EmptyListTest> {
  int itemCount = 20;

  void _toggleListContents() {
    setState(() {
      itemCount = itemCount == 0 ? 20 : 0;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Empty List Test')),
      body: itemCount > 0
        ? ListView.builder(
            itemCount: itemCount,
            itemBuilder: (BuildContext context, int index) {
              return ListTile(
                title: Text('Item ${index + 1}'),
              );
            },
          )
        : Center(child: const Text('No items')),
      floatingActionButton: FloatingActionButton(
        onPressed: _toggleListContents,
        child: Icon(Icons.refresh),
      ),
    );
  }
}
```

I have just created a PR that will update the docs for `ListView` that gives this example of how to handle this: #56394

**Comment by vasilich6107** [comment]
Hi, @darrenaustin 
There is another case - when you render the list from backend with pull to refresh. Currently you need to return another ListView with “empty data” element to make pull to refresh work on empty list.

**Comment by archit-aggarwal** [comment]
This is a genuine problem which I have faced 2-3 times now. I usually forget to add validation condition for Empty List which gives error in List View Builder Class. If there can be internal validation for the empty list, then it will reduce debugging time.

**Comment by s2c52** [comment]
maybe return SizedBox();

**Comment by aditikumar-png** [comment]
or else can use 
return count==0 ? Center(child:Text("No data")): ListView.builder

**Comment by Nelynx09** [comment]
Hi, @vasilich6107 
for the "pull to refresh" case
I solved the case by using normal Listview which let you add children directly
Hope this help.

```
itemCount > 0
                        ? ListView.builder(
                            itemCount: itemCount,
                            itemBuilder: (BuildContext context, int index) {
                              return ListTile(
                                title: Text('Item ${index + 1}'),
                              );
                            },
                          )
                        : ListView(
                            children: [Center(child: const Text('No items'))],
                          ),
```

**Comment by navaronbracke** [comment]
Since https://github.com/flutter/flutter/pull/56394 added better docs to `ListView`, I'm going to close this issue.

I wasn't very familiar with the framework at the time of writing.
Looking back to my original proposal, I feel it's not _how_ you'd be implementing this while following the style within the framework.
The new documentation is the way to go and should be preferred.
Regarding the pull-to-refresh issue mentioned here, that should be trivial to fix on your own.

**Comment by vasilich6107** [comment]
@darrenaustin @navaronbracke 

the proposed approach does not cover the case when developer will need a employ list data with ability to PullToRefresh.
What is the reason behind dealing with ternary operator and booting the code with if/else rather than adding one callback?
