### ISSUE TITLE
iOS 13 Support Multiple Windows - Config Error

### ISSUE THREAD

**Issue by AppleEducate** [flutter/flutter#41204]
Found this issue and wanted to document for anyone else facing the same.

## Steps to Reproduce

If you toggle "supports multiple windows" in Xcode and hit configure it will add the following to your `Info.plist`.

```
<key>UIApplicationSceneManifest</key>
<dict>
	<key>UIApplicationSupportsMultipleScenes</key>
	<true/>
</dict>
```

If this exists then your application will be black and have to errors.

Remove this and you will be back to normal!

**Comment by rwbr** [comment]
Is there any way to implement multi-window-support on iOS with Flutter yet?
