### ISSUE TITLE
TextFields don't meet minimum accessibility height (48 px) with default style (just 43)

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#41200]
Internal: b/141526836

Minimum a11y height requirements as per Material is 48dp whereas default style gives a height of 43.

**Comment by jkurtw** [comment]
b/141526836

**Comment by bcurley2314** [comment]
this might be caused by the root issue of 41101#

**Comment by justinmc** [comment]
I talked to Hans about this. Will start digging into it in the next day or two.
