### ISSUE TITLE
No output in debug console with physical device

### ISSUE THREAD

**Issue by Taco55** [flutter/flutter#41214]
The debug console in VS code does not display output using a physical device with Flutter 1.10.5 in combination with macOS Catalina beta 5 en Xcode 11.0. 

The only information provided is:

Running "flutter pub get" in client...                              0,7s
Launching lib/main_staging.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXXXXXXXX
Xcode build done.                                           43,5s
Checking for advertised Dart observatories...
Checking for available port on com.example.example._dartobservatory._tcp.local
Checking for authentication code for com.example.example._dartobservatory._tcp.local

Since I do have output when using the simulator I was wondering what might be wrong.

---------------------------
Dart Code extension: 3.4.1
Flutter extension: 3.4.1 (not activated)
VS Code: 1.38.1
Dart SDK: Ver: 2.6.0-edge.cb80ea7ba9124fd42a34c1d021232113e20d21b1
Flutter SDK: Ver: 1.10.5

---------------------
Flutter doctor:
[✓] Flutter (Channel dev, v1.10.5, on Mac OS X 10.15 19A558d, locale nl-NL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)

**Comment by jmagman** [comment]
@christopherfujino Are we tracking this somewhere?

**Comment by christopherfujino** [comment]
@Taco55 can you provide the verbose doctor output, via `flutter doctor -v`. If your device has iOS13, then this is a duplicate of https://github.com/flutter/flutter/issues/41133

**Comment by Taco55** [comment]
Yes, it is the same issue. Since it is already tracked I will close this issue.
