### ISSUE TITLE
icons not show on ios (web)

### ISSUE THREAD

**Issue by mahmoudsalah37** [flutter/flutter#41218]
![70658878_969441630071656_1026617790720638976_n](https://user-images.githubusercontent.com/31797198/65544169-8b64ad80-dec7-11e9-8fc3-087bbe0fab4b.jpg)
work with android and chrome(win 10)

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.10.2-pre.40, on Microsoft Windows [Version 10.0.17134.1006], locale en-US)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[√] Chrome - develop for the web
[√] Android Studio (version 3.3)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.38.1)
[√] Connected device (2 available)

! Doctor found issues in 1 category.
PS E:\QUALITY 2\iso_flutter> flutter doctor -v
[√] Flutter (Channel unknown, v1.10.2-pre.40, on Microsoft Windows [Version 10.0.17134.1006], locale en-US)
    • Flutter version 1.10.2-pre.40 at C:\flutter\flutter
    • Framework revision b4ab5cfe79 (8 days ago), 2019-09-16 20:34:25 -0700
    • Engine revision 7ea9884ab0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\flutter\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\flutter\sdk
    • Java binary at: C:\flutter\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Android Studio (version 3.5)
    • Android Studio at C:\flutter\android-studio
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\Mahmoud salah eldin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132
    • Server • web    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by timtraversy** [comment]
Hey! I believe this is a duplicate of https://github.com/flutter/flutter/issues/40501. The fix was added to the engine a week ago in version 1.10.5, you just need to upgrade Flutter to at least that version.

**Comment by escamoteur** [comment]
Is this picture flutter Web on a mobile browser?

**Comment by timtraversy** [comment]
Pretty sure it's mobile Safari.

**Comment by twpochuan** [comment]
Same issue here.
I've tested different flutter web demos on different iOS 13 devices. All of them having the same problem despite their browers. However, it was fine on iOS 12.

**Comment by jonahwilliams** [comment]
cc @hterkelsen. Is it possible that our browser detection isn't working on newer iOS devices?

**Comment by mahmoudsalah37** [comment]
> Is this picture flutter Web on a mobile browser?

yes real device

**Comment by mahmoudsalah37** [comment]
> Same issue here.
> I've tested different flutter web demos on different iOS 13 devices. All of them having the same problem despite their browers. However, it was fine on iOS 12.

yes this phone ios 13

**Comment by nturgut** [comment]
Can you run flutter on profile or release mode? Such as:

flutter run -d web --profile

**Comment by mahmoudsalah37** [comment]
> flutter run -d web --profile

 flutter run -d web --profile
Launching lib\main.dart on Server in profile mode...
lib\main.dart is being served at http://localhost:51188/
Building application for the web...                                18.1s

👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻
Warning: Flutter's support for building web applications is highly experimental.
For more information see https://github.com/flutter/flutter/issues/34082.
👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻

🔥  To hot restart (and rebuild state), press "R".
For a more detailed help message, press "h". To quit, press "q".

**Comment by AppleEducate** [comment]
are there any updates or temporary workarounds?

**Comment by nturgut** [comment]
This is a safari issue. I managed to produce it both: Safari on IOS13 device and Safari on Mac.

<img width="1673" alt="Screen Shot 2019-10-02 at 9 35 53 AM" src="https://user-images.githubusercontent.com/50856934/66063810-0269f980-e4f9-11e9-9af7-d383f9f104d5.png">

**Comment by AppleEducate** [comment]
Does the new update to safari require something other than a font manifest now?

**Comment by rxlabz** [comment]
Curiously, switching to Safari "responsive mode" seems to enable the Roboto font, but not the Material icons...🤷‍♂️

**Comment by AppleEducate** [comment]
Very weird 🧐

**Comment by nturgut** [comment]
/cc @hterkelsen The solution you suggested works.

As a temporary work around, one can remove webkit from this check:

https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/text/font_collection.dart#L121

Meanwhile I will investigate in which Safari versions might also cause problem.

**Comment by AppleEducate** [comment]
OK perfect! Thank you

**Comment by rlechetaudemy** [comment]
font_awesome_flutter plugins works well in Chrome too, but not in Safari.

**Comment by nturgut** [comment]
The PR is in.

**Comment by AppleEducate** [comment]
Thank you!!

**Comment by HiroshiHorie** [comment]
I don't know why it doesn't seem to be fixed... 🥺
I'm using master channel.

**Comment by nturgut** [comment]
Hi, 

Last engine roll is [8 hours ago](https://github.com/flutter/flutter/commits/master
), so [the fix PR ](https://github.com/flutter/engine/pull/12801) is only in flutter/engine repository now. It will probably roll it to flutter in a few hours.

One alternative is you can sync the [engine](https://github.com/flutter/engine) and run local engine:

flutter run -d headless-server --local-engine=host_debug_unopt  --web-port=8080

**Comment by AppleEducate** [comment]
Really appreciate the fast fix! Thanks again guys 🚀
