### ISSUE TITLE
flutter gallery crashes on launch in profile on ios 32-bit device

### ISSUE THREAD

**Issue by aam** [flutter/flutter#41228]
https://github.com/flutter/flutter/pull/41213 reverted two engine rolls that were related to the failure

cc @gaaclarke

**Comment by aam** [comment]
cc @rmacnak-google

**Comment by aam** [comment]
Seems to have been introduced in https://dart-review.googlesource.com/c/sdk/+/117683

**Comment by aam** [comment]
Is not reverting cleanly unfortunately

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/118661 with revert

**Comment by goderbauer** [comment]
Is this the same as https://github.com/flutter/flutter/issues/41010 that just got closed? Or is this a separate issue?

**Comment by aam** [comment]
This is separate issue from #41010

**Comment by aam** [comment]
Ryan was able to reproduce similar (looking) issue in standalone dart sdk as well.

**Comment by aam** [comment]
Revert landed, this now needs to be rolled to flutter engine as part of dart sdk roll.
