### ISSUE TITLE
Use CocoaPods version 1.8.1 in devicelab

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#41221]
Currently devicelab uses 1.7.5.  Switch it to latest 1.8.1.

See
https://github.com/flutter/flutter/pull/41145
https://github.com/flutter/flutter/issues/41144

**Comment by jmagman** [comment]
@digiter

**Comment by christopherfujino** [comment]
On the flip side, what about catching upstream regressions sooner? They can always `sudo gem install cocoapods` again, right?

**Comment by jmagman** [comment]
> On the flip side, what about catching upstream regressions sooner? They can always `sudo gem install cocoapods` again, right?

Could, though then we would miss issues requiring a minimum version bump in the tool.  Creating two `deploy_gallery-macos` tests with the minimum and the latest seems like overkill.  The current pegging to 1.7.5 seems like the worst of all worlds, though.

**Comment by christopherfujino** [comment]
> The current pegging to 1.7.5 seems like the worst of all worlds, though.

Agreed :)

**Comment by jmagman** [comment]
Okay, let's keep it on latest then.

**Comment by digiter** [comment]
Out of curiosity, why don't we use the Cocoapods repo in here? https://flutter-mirrors.googlesource.com

**Comment by jmagman** [comment]
> Out of curiosity, why don't we use the Cocoapods repo in here? https://flutter-mirrors.googlesource.com

I didn't know that existed, and I'm not sure what it's for.  It looks a few months out of date.  I bet @christopherfujino knows?

**Comment by christopherfujino** [comment]
I created that when I thought I was gonna pre-building cocoapods to distribute with the flutter tool, before I realized it was a ruby app and that shipping the files onto another machine probably wouldn't work.
