### ISSUE TITLE
Flutter Create template has 2 XCode issues

### ISSUE THREAD

**Issue by awhitford** [flutter/flutter#41223]
I noticed that a fresh Flutter app created with **Flutter 1.9.1+hotfix.2** yields 2 issues when loading the `ios/Runner.xcworkspace` in XCode:
1. Under **Runner Workspace**, it says **Conversion to Swift 5 is available**.
   * This seems to be addressed by issue https://github.com/flutter/flutter/issues/40400
2. Under **Runner project**, it says **Update to recommended settings**
   * Specifically, it mentions **Remove Unnecessary Build Files**.
<img width="996" alt="Screen Shot 2019-09-24 at 1 20 35 PM" src="https://user-images.githubusercontent.com/123887/65549439-63c71280-ded2-11e9-8881-f747261fe882.png">

**Comment by jmagman** [comment]
This was fixed as of https://github.com/flutter/flutter/pull/38724.
