### ISSUE TITLE
Update required minimum Xcode version

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#41231]
> Starting March 27, 2019, all iOS apps submitted to the App Store will need to be built with Xcode 10.2 using the iOS 12.1 SDK or later. 

Up Xcode minimum version check to 10.2.  This will also allow the templates to default to Swift 5.

See https://github.com/flutter/flutter/issues/40400.

**Comment by jmagman** [comment]
Blocked by https://github.com/flutter/flutter/issues/39921.

**Comment by jmagman** [comment]
@dnfield Does this need to be 10.3 for bitcode support?

**Comment by dnfield** [comment]
10.2 should be good enough but we may as well go to 10.3

**Comment by awhitford** [comment]
Will this address the *iOS Deployment Target* value too?  Because it seems to be unspecified or defaults to 8.0 which seems very old now.

**Comment by dnfield** [comment]
@awhitford no, that's the lowest iOS we support.  This is relared to infra we test on

**Comment by digiter** [comment]
Mac machines in devicelab are using Xcode 11.0 now.
