### ISSUE TITLE
Flutter run -d Chrome is frozen in "Building app for the web.."

### ISSUE THREAD

**Issue by NeroAlfonso** [flutter/flutter#41248]
1. When I try to launch my application (flutter run -d chrome) in web version, the console freezes in "Building app for the web ...". I waited for a few hours and it stayed that way.
![pa1](https://user-images.githubusercontent.com/30022632/65567395-1e333580-df24-11e9-80ac-4c695e572351.jpg)
2. adjunct my flutter doctor
![pa2](https://user-images.githubusercontent.com/30022632/65567490-75390a80-df24-11e9-82f0-c5481afc3977.jpg)

**Comment by escamoteur** [comment]
Hi, thanks for reporting. Could you please try if this also happens if you switch to master channel?

**Comment by NeroAlfonso** [comment]
> Hi, thanks for reporting. Could you please try if this also happens if you switch to master channel?

#### i tried change channel to master and this is the output

`PS C:\Users\nerio> flutter channel
Flutter channels:
  beta
  dev
* master
  stable
PS C:\Users\nerio> flutter upgrade
Upgrading Flutter from C:\Users\nerio\flutter...
From https://github.com/flutter/flutter
   48ce60824..7bf9aea25  master     -> origin/master
Checking out files:  34% (138/395)
Checking out files:  35% (139/395)
Checking out files:  36% (143/395)
Checking out files:  37% (147/395)
Checking out files:  38% (151/395)
Checking out files:  39% (155/395)
Checking out files:  40% (158/395)
Checking out files:  41% (162/395)
Checking out files:  42% (166/395)
Checking out files:  43% (170/395)
Checking out files:  44% (174/395)
Checking out files:  45% (178/395)
Checking out files:  46% (182/395)
Checking out files:  47% (186/395)
Checking out files:  48% (190/395)
Checking out files:  49% (194/395)
Checking out files:  50% (198/395)
Checking out files:  51% (202/395)
Checking out files:  52% (206/395)
Checking out files:  53% (210/395)
Checking out files:  54% (214/395)
Checking out files:  55% (218/395)
Checking out files:  56% (222/395)
Checking out files:  57% (226/395)
Checking out files:  58% (230/395)
Checking out files:  59% (234/395)
Checking out files:  60% (237/395)
Checking out files:  61% (241/395)
Checking out files:  62% (245/395)
Checking out files:  63% (249/395)
Checking out files:  64% (253/395)
Checking out files:  65% (257/395)
Checking out files:  66% (261/395)
Checking out files:  67% (265/395)
Checking out files:  68% (269/395)
Checking out files:  69% (273/395)
Checking out files:  70% (277/395)
Checking out files:  71% (281/395)
Checking out files:  72% (285/395)
Checking out files:  73% (289/395)
Checking out files:  74% (293/395)
Checking out files:  75% (297/395)
Checking out files:  76% (301/395)
Checking out files:  77% (305/395)
Checking out files:  78% (309/395)
Checking out files:  79% (313/395)
Checking out files:  80% (316/395)
Checking out files:  81% (320/395)
Checking out files:  82% (324/395)
Checking out files:  83% (328/395)
Checking out files:  84% (332/395)
Checking out files:  85% (336/395)
Checking out files:  86% (340/395)
Checking out files:  87% (344/395)
Checking out files:  88% (348/395)
Checking out files:  89% (352/395)
Checking out files:  90% (356/395)
Checking out files:  91% (360/395)
Checking out files:  91% (361/395)
Checking out files:  92% (364/395)
Checking out files:  93% (368/395)
Checking out files:  94% (372/395)
Checking out files:  95% (376/395)
Checking out files:  96% (380/395)
Checking out files:  97% (384/395)
Checking out files:  98% (388/395)
Checking out files:  99% (392/395)
Checking out files: 100% (395/395)
Checking out files: 100% (395/395), done.
Updating 3cf88fed6..7bf9aea25
 .../AppIcon.appiconset/app_icon_1024.png           | Bin 0 -> 46993 bytes
 .../AppIcon.appiconset/app_icon_128.png            | Bin 0 -> 3276 bytes
 .../AppIcon.appiconset/app_icon_16.png             | Bin 0 -> 1429 bytes
 .../AppIcon.appiconset/app_icon_256.png            | Bin 0 -> 5933 bytes
 .../AppIcon.appiconset/app_icon_32.png             | Bin 0 -> 1243 bytes
 .../AppIcon.appiconset/app_icon_512.png            | Bin 0 -> 14800 bytes
 .../AppIcon.appiconset/app_icon_64.png             | Bin 0 -> 1874 bytes
 395 files changed, 6802 insertions(+), 2941 deletions(-)
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 63949eb0fd982b27adc218364805913380af7411...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...

Upgrading engine...
Downloading Android Maven dependencies...
Failed to download the Android dependencies
Downloading Android Maven dependencies...                           2,7s
Downloading android-arm-profile/windows-x64 tools...                6,6s
Downloading android-arm-release/windows-x64 tools...                5,4s
Downloading android-arm64-profile/windows-x64 tools...              8,0s
Downloading android-arm64-release/windows-x64 tools...              6,9s
Downloading android-x86 tools...                                   82,3s
Downloading android-x64 tools...                                   82,4s
Downloading android-arm tools...                                   43,1s
Downloading android-arm-profile tools...                           20,6s
Downloading android-arm-release tools...                           16,3s
Downloading android-arm64 tools...                                 40,4s
Downloading android-arm64-profile tools...                         21,8s
Downloading android-arm64-release tools...                         22,5s
Downloading package sky_engine...                                   4,5s
Downloading common tools...                                        43,0s
Downloading common tools...                                        48,5s
Downloading windows-x64 tools...                                   86,3s

Flutter 1.10.6-pre.61 â€¢ channel master â€¢ https://github.com/flutter/flutter.git
Framework â€¢ revision 7bf9aea254 (7 hours ago) â€¢ 2019-09-25 00:37:12 -0700
Engine â€¢ revision 63949eb0fd
Tools â€¢ Dart 2.6.0 (build 2.6.0-dev.2.0 69b5681546)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[âˆš] Flutter (Channel master, v1.10.6-pre.61, on Microsoft Windows [VersiÃƒÂ³n 6.1.7601], locale es-VE)
[âˆš] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[âˆš] Chrome - develop for the web
[!] Android Studio (version 3.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[âˆš] VS Code (version 1.38.1)
[âˆš] Connected device (2 available)

! Doctor found issues in 1 category.
PS C:\Users\nerio> cd .\workspace\flut_web_demo
PS C:\Users\nerio\workspace\flut_web_demo> flutter run -d chrome
Downloading Web SDK...                                             17,7s
Running "flutter pub get" in flut_web_demo...                       0,8s
Launching lib\main.dart on Chrome in debug mode...
Building application for the web...
Throwing away cached asset graph due to Dart SDK update.
^C¨Desea terminar el trabajo por lotes (S/N)? S
PS C:\Users\nerio\workspace\flut_web_demo> flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Building application for the web...`

#### browser output
![pa1](https://user-images.githubusercontent.com/30022632/65612209-e529ae00-df81-11e9-829d-e336e5a15692.png)

**Comment by escamoteur** [comment]
This is in Safari, right?

Could you show us the code of you App.
The error suggests that you are missing a resource.

**Comment by NeroAlfonso** [comment]
this is Chrome (Versión 77.0.3865.90 (Build oficial) (64 bits))
the app code is the default demo from a new project 
#### main.dart
`import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

**Comment by jonahwilliams** [comment]
Tentatively marking as a duplicate of https://github.com/flutter/flutter/issues/40876

**Comment by escamoteur** [comment]
@jonahwilliams shouldn't #40876 be solved in master? Also the error is different.

**Comment by jonahwilliams** [comment]
No,the issue was re-opened due to a rollback of the dart sdk. But you're right, there is no error message

**Comment by NeroAlfonso** [comment]
@escamoteur the platform is Win7 Ultimate SP1 64 bits

**Comment by TheJulianJES** [comment]
I know that it's probably a different issue, but maybe it's still helpful:
I initally tried to build my andorid/iOS app for web without changing/removing any libraries - just to see how things would go and it was also stuck in "Building app for the web". I needed to remove some (unsupported libraries) and then run ``flutter clean``. After then running ``flutter run -d Chrome`` again, it worked fine.

**Comment by escamoteur** [comment]
@NeroAlfonso can you please post your pubspec.yaml?

**Comment by BioApfelsaft** [comment]
Same problem here (with Windows 10)

For me it looks like the reason for the problem is kaspersky.

When Kaspersky is active, `flutter run` results in an empty website.

```
flutter run -d chrome -v
[  +12 ms] executing: [P:\_dev\tools\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +73 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] cc3ca9a916cb1da851a1f36432154a534787da99
[        ] executing: [P:\_dev\tools\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +75 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.10.5-63-gcc3ca9a91
[   +4 ms] executing: [P:\_dev\tools\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +62 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [P:\_dev\tools\flutter\] git ls-remote --get-url origin
[  +60 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter
[  +81 ms] executing: [P:\_dev\tools\flutter\] git rev-parse --abbrev-ref HEAD
[  +60 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +54 ms] executing: C:\Users\Matze\scoop\apps\android-sdk\current\platform-tools\adb.exe devices -l
[  +21 ms] Exit code 0 from: C:\Users\Matze\scoop\apps\android-sdk\current\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
[   +9 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +130 ms] Launching lib\main.dart on Chrome in debug mode...
[   +1 ms] Building application for the web...
[+6547 ms] Starting daemon...
[  +98 ms] Initializing inputs
[   +5 ms] Reading cached asset graph...
[ +101 ms] Reading cached asset graph completed, took 100ms

[ +158 ms] Checking for updates since last build...
[ +323 ms] Checking for updates since last build completed, took 323ms

[   +4 ms] Initializing inputs
[   +1 ms] Reading cached asset graph...
[        ] Reading cached asset graph completed, took 100ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 323ms
[ +100 ms] Serving DevTools at http://127.0.0.1:51052

[ +662 ms] About to build [web]...
[   +3 ms] Running build...
[  +91 ms] Running build completed, took 38ms

[   +1 ms] Caching finalized dependency graph...
[   +3 ms] Caching finalized dependency graph completed, took 66ms

[        ] Succeeded after 107ms with 0 outputs (0 actions)
```

Chrome DevTools
![html](https://user-images.githubusercontent.com/7527849/65629692-159a3800-dfd4-11e9-9064-a881e6b29dad.png)

![js](https://user-images.githubusercontent.com/7527849/65629724-28ad0800-dfd4-11e9-9ff0-9830450c4747.png)
See the red rect. Maybe this is the reason. Kaspersky injects a script in every website for some reason.


When Kaspersky is disabled everything works fine:
```
flutter run -d chrome -v
[  +12 ms] executing: [P:\_dev\tools\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +74 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] cc3ca9a916cb1da851a1f36432154a534787da99
[        ] executing: [P:\_dev\tools\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +71 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.10.5-63-gcc3ca9a91
[   +4 ms] executing: [P:\_dev\tools\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +59 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [P:\_dev\tools\flutter\] git ls-remote --get-url origin
[  +61 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter
[  +80 ms] executing: [P:\_dev\tools\flutter\] git rev-parse --abbrev-ref HEAD
[  +60 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[  +56 ms] executing: C:\Users\Matze\scoop\apps\android-sdk\current\platform-tools\adb.exe devices -l
[  +21 ms] Exit code 0 from: C:\Users\Matze\scoop\apps\android-sdk\current\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
[   +8 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +121 ms] Launching lib\main.dart on Chrome in debug mode...
[   +2 ms] Building application for the web...
[+6295 ms] Starting daemon...
[ +101 ms] Initializing inputs
[   +4 ms] Reading cached asset graph...
[ +100 ms] Reading cached asset graph completed, took 99ms

[ +160 ms] Checking for updates since last build...
[ +317 ms] Checking for updates since last build completed, took 317ms

[   +4 ms] Initializing inputs
[   +1 ms] Reading cached asset graph...
[        ] Reading cached asset graph completed, took 99ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 317ms
[ +111 ms] Serving DevTools at http://127.0.0.1:51329

[ +757 ms] About to build [web]...
[   +5 ms] Running build...
[   +1 ms] Running build completed, took 38ms

[        ] Caching finalized dependency graph...
[   +1 ms] Caching finalized dependency graph completed, took 65ms

[        ] Succeeded after 108ms with 0 outputs (0 actions)

[+4782 ms] Failed to load asset at path: packages/build_web_compilers/src/dev_compiler/dart_sdk.js.

                    Status code: 404

                    Headers:
                    {
                      "date": "Wed, 25 Sep 2019 18:25:19 GMT",
                      "content-length": "9",
                      "x-frame-options": "SAMEORIGIN",
                      "content-type": "text/plain; charset=utf-8",
                      "x-xss-protection": "1; mode=block",
                      "x-content-type-options": "nosniff",
                      "server": "dart:io with Shelf",
                      "via": "1.1 shelf_proxy"
                    }

                    Content:
                    Not Found

[ +189 ms] Debug service listening on ws://127.0.0.1:51398/J8k_Sikj5yY=

[  +14 ms] Building application for the web... (completed in 12.8s)
[   +1 ms] 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻
[   +1 ms] Warning: Flutter's support for building web applications is highly experimental.
[        ] For more information see https://github.com/flutter/flutter/issues/34082.
[        ] 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻
[   +1 ms] 🔥  To hot restart (and rebuild state), press "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +8 ms] Debug service listening on ws://127.0.0.1:51398/J8k_Sikj5yY=
```

Additional observations:
`flutter run -d chrome --release` works if Kaspersky is enabled.

Test environment:

```
flutter doctor -v
[√] Flutter (Channel master, v1.10.6-pre.63, on Microsoft Windows [Version 10.0.17134.1006], locale en-GB)
    • Flutter version 1.10.6-pre.63 at P:\_dev\tools\flutter
    • Framework revision cc3ca9a916 (3 hours ago), 2019-09-25 10:57:58 -0400
    • Engine revision 63949eb0fd
    • Dart version 2.6.0 (build 2.6.0-dev.2.0 69b5681546)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Matze\scoop\apps\android-sdk\current
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Matze\scoop\apps\android-sdk\current
    • Java binary at: C:\Users\Matze\scoop\apps\android-studio\current\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\Matze\scoop\apps\android-studio\current
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\Matze\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

• No issues found!
```
App: Unchanged project created with `flutter create`

@NeroAlfonso Are you using Kaspersky ?

**Comment by NeroAlfonso** [comment]
@TheJulianJES tried it (flutter clean) but not works
@escamoteur my pubspect.yaml
```
name: flutter_web_demo_ii
description: A new Flutter project.
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
```
@BioApfelsaft tried it with "flutter run -d chrome --release" and works!
i use Karspersky in my station this must be the problem!
```
PS C:\Users\nerio\workspace\flutter_web_demo_ii> flutter run -d chrome --release
Downloading Web SDK...                                             15,6s
Launching lib\main.dart on Chrome in release mode...
Building application for the web...                                22,8s
👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻
Warning: Flutter's support for building web applications is highly experimental.
For more information see https://github.com/flutter/flutter/issues/34082.
👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻
🔥  To hot restart (and rebuild state), press "R".
For a more detailed help message, press "h". To quit, press "q".
```
![pa2](https://user-images.githubusercontent.com/30022632/65637690-a4965880-dfb2-11e9-951b-f4f4f1cc9f64.png)
thank you very much to all for help me!

**Comment by guyilherme** [comment]
Hello people.
I also use Kaspersky and just put its localhost as exclusion from Web Antivirus scanning and as a trusted URL.
![image](https://user-images.githubusercontent.com/5491604/71764934-1e50b300-2ecd-11ea-839d-a54ad9098a61.png)

**Comment by Mateis** [comment]
> 
> 
> Hello people.
> I also use Kaspersky and just put its localhost as exclusion from Web Antivirus scanning and as a trusted URL.
> ![image](https://user-images.githubusercontent.com/5491604/71764934-1e50b300-2ecd-11ea-839d-a54ad9098a61.png)

Thanks! Does this create security risks?
