### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by moz1q1** [flutter/flutter#41246]
flutter
Downloading Dart SDK from Flutter engine b863200c37df4ed378042de11c4e9ff34e4e58c9...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     18      0 --:--:-- --:--:-- --:--:--    18
[/Users/ziqimo/Downloads/flutter_macos_v1.0.0-stable/bin/cache/dart-sdk-darwin-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/ziqimo/Downloads/flutter_macos_v1.0.0-stable/bin/cache/dart-sdk-darwin-x64.zip or
        /Users/ziqimo/Downloads/flutter_macos_v1.0.0-stable/bin/cache/dart-sdk-darwin-x64.zip.zip, and cannot find /Users/ziqimo/Downloads/flutter_macos_v1.0.0-stable/bin/cache/dart-sdk-darwin-x64.zip.ZIP, period.

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md

**Comment by iapicca** [comment]
Hi @moz1q1 
are you still experiencing this issue with the latest version of Flutter?
If  so please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a minimal code sample to reproduce the problem
thank you

**Comment by moz1q1** [comment]
thinks ，I resolve problem when I delete flttuer and re-download

**Comment by iapicca** [comment]
Hi @moz1q1 
I'm glad you solved the problem,
thank you for letting me know
