### ISSUE TITLE
Not able to make flutter build apk --release in MacOS X

### ISSUE THREAD

**Issue by Jumpbotron** [flutter/flutter#41243]
I want to export the apk in release mode of my flutter app the problem is that when I try i finally get the following issue, that don't let me create it. It's curious since i can create the APK in --debug and it works great. 
 
flutter build apk
You are building a fat APK that
includes binaries for android-arm,
android-arm64.
If you are deploying the app to the
Play Store, it's recommended to use app
bundles or split the APK to reduce the
APK size.
    To generate an app bundle, run:
        flutter build appbundle
        --target-platform
        android-arm,android-arm64
        Learn more on:
        https://developer.android.com/g
        uide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk
        --target-platform
        android-arm,android-arm64
        --split-per-abi
        Learn more on:
        https://developer.android.com/s
        tudio/build/configure-apk-split
        s#configure-abi-split
Initializing gradle...                                              4.0s
Resolving dependencies...                                          17.3s
Running Gradle task 'assembleRelease'..                                       registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Running Gradle task 'assembleRelease'..                                       registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Running Gradle task 'assembleRelease'..                                       registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Running Gradle task 'assembleRelease'..                                                                
Running Gradle task 'assembleRelease'..                                       FAILURE: Build failed with an exception.
Running Gradle task 'assembleRelease'..                                                                
Running Gradle task 'assembleRelease'..                                       * What went wrong:       
Running Gradle task 'assembleRelease'..                                       Execution failed for task ':app:validateSigningRelease'.
Running Gradle task 'assembleRelease'..                                       > Keystore file '/Users/jumpbotron/Documents/programming/projects/safer/android/app/ââ¨Usersâ©/â¨jumpbotronâ©/â¨Documentsâ©/key.jks' not found for signing config 'release'.
Running Gradle task 'assembleRelease'..                                                                
Running Gradle task 'assembleRelease'..                                       * Try:                   
Running Gradle task 'assembleRelease'..                                       Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Running Gradle task 'assembleRelease'..                                                                
Running Gradle task 'assembleRelease'..                                       * Get more help at https://help.gradle.org
Running Gradle task 'assembleRelease'..                                                                
Running Gradle task 'assembleRelease'..                                       BUILD FAILED in 7s       
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                       8.0s
Gradle task assembleRelease failed with
exit code 1

Thank you very much 
* I have seem that  apparently there is a problem at the key.jks route (it has some weird symbols), even though everything is fine at the file

**Comment by escamoteur** [comment]
This is the reason
````
Running Gradle task 'assembleRelease'.. > Keystore file '/Users/jumpbotron/Documents/programming/projects/safer/android/app/ââ¨Usersâ©/â¨jumpbotronâ©/â¨Documentsâ©/key.jks' not found for signing config 'release'.
```
it seems you haven't created a release keystore.
See https://flutter.dev/docs/deployment/android
