### ISSUE TITLE
Hot reload is not working,

### ISSUE THREAD

**Issue by Bibin101** [flutter/flutter#41249]
I have the standard starting flutter app here. but when i change the color do make any other changes and press hot reload icon, it Reloaded 0 of 468 libraries in 369ms. but nothing changes in my physical device . I am reviewing the changes with a physical device.
![Screenshot (76)](https://user-images.githubusercontent.com/55642853/65567464-1d2af400-df76-11e9-8c68-7a58310b2a14.png)

This is my flutter doctor review 
![Screenshot (77)](https://user-images.githubusercontent.com/55642853/65567498-359b0e80-df76-11e9-9b34-a0983ea98aad.png)

**Comment by escamoteur** [comment]
Hi,
thanks for reporting. Could you please paste your full debug log here ?
Btw the green circular icon with the arrow does no hot reload but a hot restart of you app. Normally the hot reload should be triggered the moment you save the file. (You did save the file, right?)

**Comment by Bibin101** [comment]
I have set the hot reload on save, Ctrl + s. It says reloaded 0 libraries when i have changed some properties . I am confused . it works when i restart it though.

**Comment by escamoteur** [comment]
could you please paste the output of `flutter doctor`here

**Comment by Bibin101** [comment]
#DFDFDF

**Comment by Bibin101** [comment]
I have pasted the output of flutter doctor above

**Comment by escamoteur** [comment]
Oh sorry I missed that. Better to paste it as text.
Could you please try on the master channel?

**Comment by Bibin101** [comment]
what is a master channel?? sorry I am a newbie..

**Comment by escamoteur** [comment]
call `flutter channel master`
then do a `flutter upgrade`

**Comment by Bibin101** [comment]
It shows the follow error...

PS H:\flutter\lado> flutter channel master
Switching to flutter channel 'master'...
git: From https://github.com/flutter/flutter
git:    3932ffb1c..3cf88fed6  dev             -> origin/dev
git:    5a3a46ada..7bf9aea25  master          -> origin/master
git:  * [new branch]          refactor        -> origin/refactor
git:  * [new branch]          revert-40634-goldenTriageBenchmark -> origin/revert-40634-goldenTriageBenchmark
git:  * [new branch]          revert-40726-roll_branch -> origin/revert-40726-roll_branch
git:  * [new branch]          revert-40995-revert-40925-androidx_default -> origin/revert-40995-revert-40925-androidx_default
git:  + 20e59316b...2d2a1ffec stable          -> origin/stable  (forced update)
git:    2d2a1ffec..1ced75cc2  v1.9.1-hotfixes -> origin/v1.9.1-hotfixes
git:  * [new branch]          verbose-put     -> origin/verbose-put
git:  * [new tag]             v1.10.1         -> v1.10.1
git:  * [new tag]             v1.10.5         -> v1.10.5
git:  * [new tag]             v1.10.2         -> v1.10.2
git:  * [new tag]             v1.10.3         -> v1.10.3
git:  * [new tag]             v1.10.4         -> v1.10.4

**Comment by Bibin101** [comment]
Did it switch to master channel?

**Comment by escamoteur** [comment]
yep, now do a flutter upgrade

**Comment by Bibin101** [comment]
ok. will get back to you...

**Comment by JosephineAkello** [comment]
@Bibin101  I think for this,hot-reload problem, you will have to do a full restart. there are instances when you have to do a full restart after making changes to your app, as much as hot-reload causes all widgets to rebuild, there are cases you have to do a full restart to see the updated change in your device.
To get more of this check this article [https://medium.com/podiihq/understanding-hot-reload-in-flutter-2dc28b317036](url) and the official flutter docs [https://flutter.dev/docs/development/tools/hot-reload](url)

**Comment by escamoteur** [comment]
@JosephineAkello I don't think so if it already fails if he changes a color.

**Comment by janmoppel** [comment]
Hello @Bibin101 !

Without additional information, we are unfortunately not sure how to proceed on this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
