### ISSUE TITLE
how set stack from bottom listview.builder

### ISSUE THREAD

**Issue by mehdidavarpanah66** [flutter/flutter#41252]
new ListView.builder(
controller: _scrollController,
               reverse: true,
               shrinkWrap: true,
                itemCount: chatList.length
                  ,itemBuilder: (BuildContext context,int index){

                   return new Container(
                    margin: const EdgeInsets.only(bottom: 8,left: 8,right: 8),
                    child:  Bubble(
                      style: chatList[index].sender==my_username
                      ?styleMe
                      :styleSomebody,
                      child:  new Column(

                        children: <Widget>[
                          new Container(
                            margin: const EdgeInsets.only(bottom: 8),
                            child: new Text(chatList[index].msg,style: TextStyle(fontSize: 16)),
                          ),
                          new Container(
                            child: new Text(chatList[index].date+" "+chatList[index].time,style: TextStyle(color:  Colors.grey,fontSize: 10),),
                          ),
                        ],
                      )
                    ),
                  );
              }
              )

**Comment by escamoteur** [comment]
Please ask questions like that on stackoverflow. We are not able to give individual support. Thanks for your understanding.

**Comment by leogh73** [comment]
> Please ask questions like that on stackoverflow. We are not able to give individual support. Thanks for your understanding.

Nobody replies on StackOverflow. The only replies I ever got there were 4 days after I asked the question and the answer was useless. I never ask questions on SO, it's a waste of time.

**Comment by escamoteur** [comment]
@leogh73 That's wrong. The Flutter Team just published a statistic on how good Flutter Questions get answers on SO.
This repository is not for individual support but for bugs and feature proposals.
also there are other channels to get help on Discord, Slack or Reddit.
