### ISSUE TITLE
Stable v1.9.1+hotfix.2 flutter implant iOS project

### ISSUE THREAD

**Issue by fankfank** [flutter/flutter#41250]
Stable v1.9.1+hotfix.2 flutter implant iOS project does not generate Development Pods dir when execute pod install in pods ?

**Comment by escamoteur** [comment]
Hi,

do I understand this right, you are trying to add a Flutter view into a native ios App?

could you please try if this bug also appears if you switch to master? Thanks

**Comment by fankfank** [comment]
As you said, I have already tried it. master is the same as stable， 
what should I do？Thanks！

**Comment by escamoteur** [comment]
Could you please add your log with the error message?

**Comment by fankfank** [comment]
I can not see any error msg, just not generate Development Pods dir when execute pod install in pods, sry ...

**Comment by escamoteur** [comment]
Could you please add the output of flutter doctor here?

**Comment by fankfank** [comment]
Sure,
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.4 18E227, locale
    zh-Hans-CN)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
[✓] Connected device (2 available)

**Comment by fankfank** [comment]
I have already tried it, switch to latest master. also not work.

**Comment by escamoteur** [comment]
Please also upgrade xcode

**Comment by liulishuo** [comment]
me too.  any solution?

**Comment by jmagman** [comment]
Can you elaborate on the actual problem you are seeing and give reproducible steps?  You run `flutter build ios` then open Runner.xcworkspace.  You try to build and get linker errors because the plugin frameworks are missing?

**Comment by jmagman** [comment]
Also, you must be on the master channel to use add-to-app since it's still in preview.  See https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#intro

**Comment by fankfank** [comment]
> Please also upgrade xcode

I have already tried it, also not work.

**Comment by fankfank** [comment]
> Also, you must be on the master channel to use add-to-app since it's still in preview. See https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#intro

yeah, Just follow this step, this is the project, thanks
https://github.com/fankfank/FlutterTest.git

**Comment by fankfank** [comment]
Stable v1.9.1+hotfix.5 still does not generate Development Pods dir when execute pod install in pods

**Comment by fankfank** [comment]
> @fankfank Can you elaborate on the actual problem you are seeing and give reproducible steps? You run `flutter build ios` then open Runner.xcworkspace. You try to build and get linker errors because the plugin frameworks are missing?

https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#intro

yeah, Just follow this step, this is the test project, thanks
https://github.com/fankfank/FlutterTest.git

**Comment by fankfank** [comment]
Stable v1.9.1+hotfix.5 still does not generate Development Pods dir when execute pod install in pods

**Comment by escamoteur** [comment]
@fankfank as @jmagman told you you have to be on master channel. you are still on the stable channel with v1.9.1+hotfix.5.
Please switch to the master channel by

`flutter channel master`

followed by

`flutter upgrade`

Thanks

**Comment by Sunbreak** [comment]
@fankfank A project with `Github Action` may help

**Comment by fankfank** [comment]
> @fankfank as @jmagman told you you have to be on master channel. you are still on the stable channel with v1.9.1+hotfix.5.
> Please switch to the master channel by
> 
> `flutter channel master`
> 
> followed by
> 
> `flutter upgrade`
> 
> Thanks

Flutter 1.10.15-pre.251 • channel master •, I have already tried it, also not work...

**Comment by fankfank** [comment]
> me too. any solution?

解决了没兄弟？

**Comment by jmagman** [comment]
@fankfank Your Podfile needs to be upgraded.  See https://github.com/flutter/flutter/wiki/Upgrading-Flutter-added-to-existing-iOS-Xcode-project.
Yours:
```ruby
target 'FlutterTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlutterTest

end

flutter_application_path = 'my_flutter'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
```
https://github.com/fankfank/FlutterTest/blob/master/Podfile

It should look something like this: 
```ruby
flutter_application_path = 'my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterTest' do
  install_all_flutter_pods(flutter_application_path)
end
```
More details: https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#add-your-flutter-app-to-your-podfile

**Comment by fankfank** [comment]
> ```ruby
> flutter_application_path = 'my_flutter'
> load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
> 
> target 'FlutterTest' do
>   install_all_flutter_pods(flutter_application_path)
> end
> ```

Ok, thank you very much
