### ISSUE TITLE
Device using Qualcomm Adreno 308 - last update - black screen (build/release apk)

### ISSUE THREAD

**Issue by MohamedSayed95** [flutter/flutter#41268]
please make sure it's working at least
took me 4 hours to figure out it's engine/skia bug

even stable channel has same bug

**Comment by escamoteur** [comment]
I'm sorry but we would need a bit more information what bug you are talking about.
Does it also happen on master?

**Comment by MohamedSayed95** [comment]
yes, it does
the problem is, app shows a black screen and elements exist when i touch my textField widget keypad shows up

i built new flutter project with default counter example.. same

so, after 4 hours of digging i switched back to 1.7.8-hotfixes

**Comment by escamoteur** [comment]
So it works on 1.7.8-hotfixes?

Could you please elaborate whar the bug exactly is and why you think its an engine bug?
Does this happen on Android and iOS?
Thanks

**Comment by escamoteur** [comment]
I still would like to get some more details about this. Did you find out it's not a Flutter bug?

**Comment by MohamedSayed95** [comment]
That is what i'm talking about - on Samsung J6+
And for other modern phone some widgets, not loading and gets phone hang-up

`https://drive.google.com/file/d/1Dp1zMTdPMe30O4tAPZsfyUdkhN6YKLbC/view?usp=sharing`

**Comment by escamoteur** [comment]
@MohamedSayed95 why did you close the issue?
Is it fixed with the latest stable or with master? 
You are the first to report this, so I want to make sure I understand it correctly. 
Does this happen with all Apps?

**Comment by MohamedSayed95** [comment]
> Does this happen with all Apps?
Correct, even on default flutter app
but i'm not the first one to report this, i saw some reports to same issue.. like this one
[#36130](https://github.com/flutter/flutter/issues/36130)
