### ISSUE TITLE
how set focus to last item in listview.builder

### ISSUE THREAD

**Issue by mehdidavarpanah66** [flutter/flutter#41265]

**Comment by mehdidavarpanah66** [comment]
i have a chat app but list view after set state focus on first item and i want focus on last item like telegram or other messengers

**Comment by sma** [comment]
This is a question best ask on [stackoverflow](https://stackoverflow.com/questions/49153087/listview-scrolling-to-widget). You probably also want to reverse the list view so that the first item is displayed at the bottom of the list.

**Comment by escamoteur** [comment]
Hi,

please ask such questions on stackoverflow. We are not able to provide indiviudal support here, thanks

**Comment by dbspoudel** [comment]
This will probably help you :) 
https://stackoverflow.com/questions/58304754/focus-the-bottom-of-a-listview-flutter
