### ISSUE TITLE
Update "Developing packages & plugins" docs

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#41267]
As https://github.com/flutter/flutter/issues/33302 seems to be fixed, the command in the [docs](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#publishing-packages) should be updated to reflect the changes.

**Comment by Zazo032** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
Unfortunately this didn't make it into the Flutter 1.9 stable build, so we have to wait a bit before updating the docs. Assigning to self to make sure we get this updated eventually.

**Comment by Hixie** [comment]
@mit-mit Can you set a target milestone that represents a conservative estimate of when this will land? Thanks!

**Comment by mit-mit** [comment]
Actually, the fix is in stable as of 1.12, and looks like docs were already updated in https://github.com/flutter/website/commit/5e622ab109f5a8b3306cc8a5f7336f43678ec768#diff-feae4e9de41c43216737d205e4c1dc9c, so closing
