### ISSUE TITLE
Support google/oboe

### ISSUE THREAD

**Issue by rg4real** [flutter/flutter#41266]
Google released a C++ library to fix audio issue with Android. It's great and promising:
https://github.com/google/oboe

If flutter would integrate it into a library it would become a go-to option to work with audio apps.

And overall it's would be a great integration. Your thoughts?

I would love to help in any way, but I need guidance. Last time I've touched C++ was 10 years ago in university. Good times! :)

**Comment by escamoteur** [comment]
Hi, this is a job to be done in a package. 
If you want to give it a shot,  I recommend to join https://groups.google.com/forum/#!forum/dart-ffi
I fear we can't help with C++ questions bus Google is your friend :-)
