### ISSUE TITLE
The following assertion was thrown building Home(dirty, state: _HomeState#505a6): Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by deepikahr** [flutter/flutter#41261]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by escamoteur** [comment]
Hi,

please provide us the output of `flutter doctor` and give us more context. Show us please the full error message and your code.
Otherwise we cannot help you.

**Comment by janmoppel** [comment]
Hello @deepikahr !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
