### ISSUE TITLE
collapsing toolbar gets confused by android overscroll behavior

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4126]
![flutter_02](https://cloud.githubusercontent.com/assets/11857803/15486235/0eb89cb8-20f9-11e6-8eb2-245a69250032.png)

**Comment by sethladd** [comment]
We may want to consider just showing a list of options here, without the collapsing list functionality. Would it be more impressive to see a list of components, demos, etc?

**Comment by eseidelGoogle** [comment]
Or without the overscroll having timed out https://github.com/flutter/flutter/issues/4127

![flutter_04](https://cloud.githubusercontent.com/assets/11857803/15486273/57b54592-20f9-11e6-868b-083c1a897951.png)
