### ISSUE TITLE
当Container包含platform view时，圆角不生效 (Fillet does not take effect when Container contains platform view)

### ISSUE THREAD

**Issue by Lillls** [flutter/flutter#41275]
当Container包含platform view时，圆角不生效
(Google translate) Fillet does not take effect when Container contains platform view

**Comment by BondarenkoStas** [comment]
@Lillls Can you please explain in more details what exactly the issue is? Please provide your flutter doctor -v, and some reproducible code example.

**Comment by BondarenkoStas** [comment]
Duplicate of #41280
