### ISSUE TITLE
Android overscrolls timeout?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4127]
I'm not sure if this is expected behavior or not, but if you hold a view overscrolled the overscroll indicator will eventually timeout?  (From https://github.com/flutter/flutter/issues/4126):

![flutter_02](https://cloud.githubusercontent.com/assets/11857803/15486260/43578e02-20f9-11e6-94d6-f3bbfcbb5af3.png)

**Comment by HansMuller** [comment]
This is an Android (not Material) feature and the Android overscroll indicators definitely do timeout. So yew, we should too.

**Comment by eseidelGoogle** [comment]
OK.  Closing.

**Comment by HansMuller** [comment]
What I meant was: yes this is a bug. Flutter overscroll indicators should time out, just like native Android overscroll indicators do.
