### ISSUE TITLE
[web]: Crash report sent (report ID: bbf8269f10f666ed)

### ISSUE THREAD

**Issue by gowtham980** [flutter/flutter#41274]
Describe your issue and include the command you're running, flutter_web version, browser version

**Comment by BondarenkoStas** [comment]
@gowtham980 Unfortunately, this report does not have any actionable information - it’s not clear if this is a bug in user code, a bug in the framework, or something else entirely.
Please feel free to comment and I will re-open if you can add the relevant information.
