### ISSUE TITLE
Using HTML, assets Images not rendering in flutter-ios. How to render asset-images inside html <img src> tag in flutter without using webview?

### ISSUE THREAD

**Issue by jazzbpn** [flutter/flutter#41270]
I am using HTML/CSS to create PDF views. So, In some cases we need render images from the local asset-folder. When we try to render the file from assets folder image is not displaying. How to resolve this issue?

[Full question at stackoverflow](https://stackoverflow.com/questions/57956232/assets-images-not-rendering-in-flutter-ios-how-to-render-local-asset-images-ins)

**Comment by myusoof** [comment]
Any update on this. Can we render the assets images in html via webview?

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .

**Comment by KanybekMomukeyev** [comment]
Any update?
