### ISSUE TITLE
INFO: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'

### ISSUE THREAD

**Issue by navidanchitrali** [flutter/flutter#41283]
Here is the build info: 
```
INFO: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app
```

```
NO ANALYZE ISSUE
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.356], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!
```

**Comment by navidanchitrali** [comment]
Anybody help Please?

**Comment by BondarenkoStas** [comment]
@navidanchitrali I saw you commented in #1431. What is your gradle version?

**Comment by navidanchitrali** [comment]
@BondarenkoStas  Dear my gradle version is 5.4.1

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip


and build.gradle is:
buildscript {
    ext.kotlin_version = '1.2.71'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50"
        classpath 'com.google.gms:google-services:4.3.2'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by navidanchitrali** [comment]
@BondarenkoStas Thanks

**Comment by navidanchitrali** [comment]
@BondarenkoStas Thanks

**Comment by jonahwilliams** [comment]
flutter.gradle does not use this api, so it might be an issue with a particular gradle plugin. I don't really think we're equipped to debug this from the provided info. Try running Gradle with `use -Pandroid.debug.obsoleteApi=true on the command line to display more information.` to figure thisout
