### ISSUE TITLE
Potential bug with Provider in Flutter

### ISSUE THREAD

**Issue by zeromaro** [flutter/flutter#41289]
Hello,
I'm facing extremely weird issue. On `debug` it works fine, on `release` it doesn't.
I'm using Provider.

I have class A, which is Stateful. Inside initState I have a call `Provider.of<UserStore>(context, listen: false).getUser();`

Inside `getUser` I've some state changes. What's interesting, I'm printing in `build()` method. 

If I'm running in `debug` mode, I can see multiple prints - state changes properly.
If I'm running in `release` mode, I can see only one print - which was the first one.

`notifyListeners` is getting triggered both times, however Widget tree gets rebuilt only in `debug` build.

I'm using Flutter `Channel dev, v1.10.5`.

**Comment by BondarenkoStas** [comment]
@zeromaro Can you please provide a small self-contained app that demonstrates the issue?

**Comment by zeromaro** [comment]
Good call, sorry. New project works well. 

Any suggestions, what might be wrong here or how should I debug release build? As nothing gets changed besides adding `--release` tag to command line `flutter run -d <device_id>`

**Comment by escamoteur** [comment]
Please upgrade to latest master you are some build behind

**Comment by zeromaro** [comment]
Dang, missed it. Now I'm on `Flutter 1.10.6-pre.63 • channel master`. Unfortunately problem is still there. `debug` is working flawlessly, `release` no. All I need to do is to debug `notifyListeners()` method because from `print` statements I see it gets called but nothing gets notified. I tried wrapping it to `try catch` block but it doesn't fail.

Any ideas how could I get inside `notifyListeners()`? Or any other suggestions?

**Comment by escamoteur** [comment]
But if debug is working, why can't set breakpoints?

**Comment by escamoteur** [comment]
I guess we need to see more code. Could you please try to reproduce this in a small sample project?

**Comment by zeromaro** [comment]
That's the whole mystery. `debug` build is working fine, but when I build `release` build, it doesn't. I'm now trying to play around and understand why is that. Because as much as I searched, there is no way to debug `release` build. Therefore I'm using... `print`ing statements to identify what where goes wrong. But I cannot do anything with `notifyListeners()` as it's void..

**Comment by escamoteur** [comment]
You could even add print statements in inside notifyListeners
But I recommend create a new project and try to reproduce it.
The  share the project with us.

**Comment by goderbauer** [comment]
If this is a bug with Providers: https://github.com/rrousselGit/provider may be a better place to file that.

**Comment by zeromaro** [comment]
@escamoteur , I'm trying but it seems it just.. works on new project.

@goderbauer , I'm not sure what's actually wrong. As I can't reproduce it anyhow on new project.

I'm off to bed now as it's quite late over here. I'll record video tomorrow so you guys could see I'm not faking it. Super bizarre. I've nearly ripped all my hair off already

**Comment by zeromaro** [comment]
Reproduced!

https://github.com/zeromaro/flutter-provider-bug

**Comment by escamoteur** [comment]
Will the next days in Crete speaking at a Flutter conference. But I will look into it afterwards if it isn't solved

**Comment by kunit1** [comment]
@zeromaro 
I don't think this is a bug. You are calling an async function provided by provider in the initState. That's not allowed. See the FAQ in the Provider repo read me. 

Try placing the call in a microtask. Take a look at the Provider FAQ.

**Comment by zeromaro** [comment]
@kunit1 , that doesn't explain why it works well in `debug` but doesn't in `release` builds, does it?

**Comment by apoorvpandey0** [comment]
Hi, I'm facing the same issue, its wierd!
DEBUG mode everything works perfect, but in release mode provider is not updating data as it should!
