### ISSUE TITLE
I am facing difficulty when I am running the application

### ISSUE THREAD

**Issue by SAITARUN55** [flutter/flutter#41282]
```
Oops; flutter has exited unexpectedly: "Exit code 1 from: C:\Users\Public\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1".
Crash report sent (report ID: eb48ce7d3058819b)
Crash report written to D:\Flutter\DevFest-19-App\Aritra\DevFest-19-App\flutter_04.log;
```

**Comment by BondarenkoStas** [comment]
@SAITARUN55 Please provide your ```flutter doctor -v``` and the log (`flutter_04.log`).

**Comment by janmoppel** [comment]
Hello @SAITARUN55 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
