### ISSUE TITLE
How to set drawer width different as Web and Mobile.

### ISSUE THREAD

**Issue by Parmendrakumar** [flutter/flutter#41287]
body: DrawerUserController(
            screenIndex: drawerIndex,
            drawerWidth: MediaQuery.of(context).size.width * 0.75,
            animationController: (AnimationController animationController) {
              sliderAnimationController = animationController;
            },

Currently I am using above code but 0.75 is looking very odd in Web its looking cool in Mobile.

I want to  set for Mobile 0.75 and for Web 0.25

How to do that

**Comment by BasedMusa** [comment]
You could just check if the platform is web, like so:

`MediaQuery.of(context).size.width * (isWeb ? 0.25 : 0.75)`

**NOTE:** Flutter has no variable by the name of `isWeb`

You can still check platform using these two ways, none of these currently support how to check for web, this needs to be updated so I've filed an issue [here](https://github.com/flutter/flutter/issues/41311).

```Dart
import 'dart:io';

bool isWeb = Platform.isIOS;
//isWeb = Platform.isAndroid;
//isWeb = Platform.isIOS;
//isWeb = Platform.isFuchsia;
//isWeb = Platform.isWindows;
//isWeb = Platform.isLinux;
//isWeb = Platform.isMacOS;
```
**OR**
```Dart
import 'package:flutter/foundation.dart';

bool isWeb = defaultTargetPlatform == TargetPlatform.iOS;
//isWeb = Platform.android;
//isWeb = Platform.fuchsia;
```

**Comment by BasedMusa** [comment]
You can use this.

```
import 'package:flutter/foundation.dart';

MediaQuery.of(context).size.width * (kIsWeb ? 0.25 : 0.75)
```
