### ISSUE TITLE
Images Flashing

### ISSUE THREAD

**Issue by PedroTheRealOne** [flutter/flutter#41294]
In my App, I use a lot of NetworkImages and Streambuilder's, and my images keep blinking when I navigate through the app.

**There is a way that my images keep loaded?**

I don't want to use `FadeInImage` .

I have tried:

- Replace the Image Provider to one that uses Cache (CachedNetworkImage); 
- Use `AutomaticKeepAliveClientMixin`

[Sample video](https://www.youtube.com/watch?v=u5D4rZAgAxQ&feature=youtu.be)

Component code:
```dart
class _RankingPageState extends State<RankingPage>
    with AutomaticKeepAliveClientMixin {
...

Container(
 width: MediaQuery.of(context).size.width,
 margin: EdgeInsets.fromLTRB(
   widget.spaceBetweenPages,
   widget.marginTopBottom,
   widget.spaceBetweenPages,
   widget.marginTopBottom,
 ),
 decoration: BoxDecoration(
   color: Colors.white,
   borderRadius:
       BorderRadius.all(Radius.circular(20)),
       boxShadow: widget.boxShadow ?? [],
       image: DecorationImage(
         fit: BoxFit.cover,
         image: AdvancedNetworkImage(
             item.picture ?? "",
             useDiskCache: true),
       ),
     ),
   ),
```

**Comment by escamoteur** [comment]
In this code you are using AdvancedNetworkImage which is not part of the framework.
Normally NetworkImage caches automatically.
But it depends on the number and size of images.

**Comment by escamoteur** [comment]
One thing that comes to mind when you write StreamBuilder. Do they all have initialData set?
Otherwise you will always see one empty frame.

**Comment by PedroTheRealOne** [comment]
> One thing that comes to mind when you write StreamBuilder. Do they all have initialData set?
> Otherwise you will always see one empty frame.

I set in all my streambuilder's initialData, and i kinda know what is happening.
My streambuilder is rebuilding every time when i navigate through the app. There is anything i can do, to stop this?

**Comment by escamoteur** [comment]
I would need to see more code.
Can you reproduce it in a small demo project.

**Comment by DuQuanzhong** [comment]
Widget _buildFloatingActionButton() {
    if (!state.isShowFloatBtn) {
      return null;
    } else {
      if (state.scrollController.offset <= 700) {
        return null;
      }
      return Container(
        height: 40,
        width: 40,
        child: new FloatingActionButton(
            heroTag: '11111',
            backgroundColor: Color.fromARGB(130, 0, 0, 0),
            child: Container(
              height: 30,
              child: Image.asset('assets/up_to_top_icon.png'),
            ),
            onPressed: () {
              state.scrollController.animateTo(0.0, duration: new Duration(milliseconds: 10), curve: Curves.linear);
            }),
      );
    }
  }


I have the same problem.
The list view scrolls from the bottom to the top and the image flashes.

**Comment by rodydavis** [comment]
This did not used to be an issue but now it is. I see it more aggressively on flutter web.

**Comment by TahaTesser** [comment]
There no reproducible code sample to better address the issue, one that is incomplete 

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
