### ISSUE TITLE
3rd party native library for Flutter package

### ISSUE THREAD

**Issue by durduman** [flutter/flutter#41292]
If I need to create a [flutter package][1] for an existing library OR pod I am interested in some clarifications:

In the case of a new package for a **library (.framework)** ... will I add this in the `Pods/Development Pods/hello/Classes/` location? I suppose not in the Runner project since the code to implement the channels and extra native implementation is in that location, as mentioned in the flutter package documentation.

In the case of a new package for a **pod** ... I suppose I add the new pod in the podfile and then should I run pod update? or? 

Some additional resources I have gone through and maybe missed something:

[This medium article][2] that prompts me to a [git repo][3].

[This stack answer][4] which is very android oriented.

  [1]: https://flutter.dev/docs/development/packages-and-plugins/developing-packages
  [2]: https://blog.solutelabs.com/integrating-third-party-native-sdks-in-flutter-df418829dcf7
  [3]: https://github.com/solutelabs/Flutchat?source=post_page-----df418829dcf7----------------------
  [4]: https://stackoverflow.com/questions/50020347/calling-native-libraries-in-flutter-using-platform-channels

**Comment by jmagman** [comment]
You mean there's an existing non-Flutter library and you want to create a Flutter plugin that wraps the same calls?  In that case you would make a Flutter plugin with `flutter create -t plugin` as described here https://docs.flutter.dev/development/packages-and-plugins/developing-packages#step-1-create-the-package-1.  Your native iOS files wrapping the library go in `ios/Classes` as that doc says.

An `example` directory is created at the top level which is a Flutter app that uses the plugin.  You would `flutter run` it like a normal app to debug the dart side, hot reload, etc.  To debug the native side you can `run` at least once, or the simplified `flutter build ios --config-only` to set it up, and then open the Xcode project at `ios/Runner.xcworkspace` and set breakpoints.  
https://docs.flutter.dev/development/packages-and-plugins/developing-packages#step-2c-add-ios-platform-code-swifthm

Do not manually edit anything in `Pods`, or run `pod install`, or do anything with CocoaPods.  Just pretend the `example` project is a normal Flutter project using your plugin.

If you need examples, check out the plugins that Flutter maintains: https://github.com/flutter/plugins/tree/main/packages

Is there something that could have been added to https://docs.flutter.dev/development/packages-and-plugins/developing-packages to make this clearer?
