### ISSUE TITLE
h5 page lose focus in the webview when flutter brings up the keyboard.

### ISSUE THREAD

**Issue by leebin17** [flutter/flutter#41293]
## Steps to Reproduce

I'm developing an app with plugin `webview_flutter`. 

The problem is that when I click the **INPUT box** in the h5 page, Flutter brings up the keyboard.
At this moment, h5 page just loses the focus at the **INPUT box** which I just clicked!
And I need to click the input again to focus and input characters.

I used:
`Flutter 19.1 hotfix.2`
`webview_flutter: ^0.3.14+1`

This is My Code:
--------------------------------------------------------------------------------------

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';      


class DetailWeb4Page extends StatefulWidget {
  DetailWeb4Page({Key key}) : super(key: key);
  _DetailWeb4PageState createState() => _DetailWeb4PageState();
}

class _DetailWeb4PageState extends State<DetailWeb4Page> {

  WebViewController _controller;      
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title:Text("title"),
        ),
        body:WebView(
          onWebViewCreated: (controller){
            _controller = controller;
          },
          initialUrl: "http://www.jbb8888.cn/register/channel/4/t/39814ec9c5219045a884c9dfa8555bb2",
          javascriptMode: JavascriptMode.unrestricted,
          navigationDelegate: (NavigationRequest request) {},
          javascriptChannels: <JavascriptChannel>[].toSet(),
          onPageFinished: (url){},
        )
      );
  }  
}
```

--------------------------------------------------------------------------------------

When I use the `flutter_webview_plugin` in my app, it just works fine.
But I need the function of the `webview_flutter` that downloads file.
So I use the `webview_flutter` rather than `flutter_webview_plugin`.

Please help me with that. thx a lot.

**Comment by leebin17** [comment]
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.38.1)
[√] Connected device (1 available)

**Comment by leebin17** [comment]
**log**
`
D:\MobileDev\Projects\FlutterLearn\my_flutter_app_01>flutter run
Launching lib\main.dart on MIX 2 in debug mode...
Initializing gradle...                                              1.5s
Resolving dependencies...                                           6.5s
Running Gradle task 'assembleDebug'...                             20.3s
Built build\app\outputs\apk\debug\app-debug.apk.
Syncing files to device MIX 2...                                 2,668ms (!)

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on MIX 2 is available at: http://127.0.0.1:53415/MdUvJ1whuG0=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
I/zygote64(14533): Do partial code cache collection, code=61KB, data=44KB
I/zygote64(14533): After code cache collection, code=61KB, data=44KB
I/zygote64(14533): Increasing code cache capacity to 256KB
W/ResourceType(14533): No package identifier when getting name for resource number 0x00000000
I/chatty  (14533): uid=10118(u0_a118) com.example.my_flutter_app_01 identical 2 lines
W/ResourceType(14533): No package identifier when getting name for resource number 0x00000000
W/cr_ChildProcLH(14533): Create a new ChildConnectionAllocator with package name = com.google.android.webview, sandboxed = true
I/cr_BrowserStartup(14533): Initializing chromium process, singleProcess=false
D/EgretLoader(14533): EgretLoader(Context context)
D/EgretLoader(14533): The context is not activity
W/cr_media(14533): Requires BLUETOOTH permission
D/NetworkSecurityConfig(14533): No Network Security Config specified, using platform default
W/ContentCatcher(14533): Failed to notify a WebView
W/VideoCapabilities(14533): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14533): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14533): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14533): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14533): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14533): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14533): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(14533): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(14533): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(14533): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(14533): Unsupported mime video/divx
W/VideoCapabilities(14533): Unsupported mime video/divx311
W/VideoCapabilities(14533): Unsupported mime video/divx4
W/AudioCapabilities(14533): Unsupported mime audio/dsd
W/AudioCapabilities(14533): Unsupported mime audio/dts
W/AudioCapabilities(14533): Unsupported mime audio/32KADPCM
W/VideoCapabilities(14533): Unsupported mime video/mp4v-esdp
I/VideoCapabilities(14533): Unsupported profile 4 for video/mp4v-es
I/chromium(14533): [INFO:CONSOLE(17)] "A parser-blocking, cross site (i.e. different eTLD+1) script, https://c.cnzz.com/core.php?web_id=1273486993&t=z, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: https://s13.cnzz.com/z_stat.php?id=1273486993&web_id=1273486993 (17)
I/chromium(14533): [INFO:CONSOLE(17)] "A parser-blocking, cross site (i.e. different eTLD+1) script, https://c.cnzz.com/core.php?web_id=1273486993&t=z, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: https://s13.cnzz.com/z_stat.php?id=1273486993&web_id=1273486993 (17)
I/flutter (14533): 可见
W/ContentCatcher(14533): Failed to notify a WebView
W/ResourceType(14533): No package identifier when getting name for resource number 0x00000000
I/Adreno  (14533): DequeueBuffer: dequeueBuffer failed
I/Adreno  (14533): DequeueBuffer: dequeueBuffer failed
I/Adreno  (14533): DequeueBuffer: dequeueBuffer failed
W/OpenGLRenderer(14533): swapBuffers encountered EGL error 12301 on 0x7669cab0c0, halting rendering...
W/ContentCatcher(14533): Failed to notify a WebView
I/zygote64(14533): Do full code cache collection, code=124KB, data=91KB
I/zygote64(14533): After code cache collection, code=111KB, data=64KB
I/zygote64(14533): Do partial code cache collection, code=122KB, data=92KB
I/zygote64(14533): After code cache collection, code=122KB, data=92KB
I/zygote64(14533): Increasing code cache capacity to 512KB
`

**Comment by janmoppel** [comment]
Hello @leebin17 !

Thank you for posting an issue.
Can you please also attach the full output of the `flutter doctor -v` output?

Also, it seems that similar problems have been already reported and discussed here: #35867 and #39451.

Thank you.

**Comment by leebin17** [comment]
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.9.1+hotfix.2 at D:\MobileDev\flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (1 available)
    • MIX 2 • c99f8dfe • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by leebin17** [comment]
@janmoppel Thank you for your attention.  And I've posted the output of  ' flutter doctor -v' .
And I still can't figure it out.

**Comment by leebin17** [comment]
this is the log when I clicked the input for the first time.
> 
W/ContentCatcher( 9203): Failed to notify a WebView
W/ResourceType( 9203): No package identifier when getting name for resource number 0x00000000
I/Adreno  ( 9203): DequeueBuffer: dequeueBuffer failed
I/Adreno  ( 9203): DequeueBuffer: dequeueBuffer failed
I/Adreno  ( 9203): DequeueBuffer: dequeueBuffer failed
W/ContentCatcher( 9203): Failed to notify a WebView
W/OpenGLRenderer( 9203): swapBuffers encountered EGL error 12301 on 0x76696d5440, halting rendering...

**Comment by leebin17** [comment]
I think this is the right log.

W/IInputConnectionWrapper( 9203): getTextBeforeCursor on inactive InputConnection
E/IInputConnectionWrapper( 9203): imm serving different input connection with ime service owns
W/IInputConnectionWrapper( 9203): commitText on inactive InputConnection

**Comment by VladyslavBondarenko** [comment]
Tried with flutter dev v1.15.3, webview_flutter: ^0.3.19+8, Android 8 emulator - couldn't reproduce

<details>
 <summary>with such code</summary>

```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MaterialApp(home: DetailWeb4Page()));


class DetailWeb4Page extends StatefulWidget {
  DetailWeb4Page({Key key}) : super(key: key);
  _DetailWeb4PageState createState() => _DetailWeb4PageState();
}

class _DetailWeb4PageState extends State<DetailWeb4Page> {

  WebViewController _controller;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title:Text("title"),
        ),
        body:WebView(
          onWebViewCreated: (controller){
            _controller = controller;
          },
          initialUrl: "https://translate.google.com/",
          javascriptMode: JavascriptMode.unrestricted,
          navigationDelegate: (NavigationRequest request) {},
          javascriptChannels: <JavascriptChannel>[].toSet(),
          onPageFinished: (url){},
        )
    );
  }
}
```

</details>

@leebin17 
Closing
Please comment if you are experiencing the issue with the last stable or another last version of flutter and the plugin and I'll reopen it
Thank you
