### ISSUE TITLE
Removing guava dependency from the google_sign_in plugin 

### ISSUE THREAD

**Issue by bsr203** [flutter/flutter#41296]
After adding few of google provided packages, my app hit the 64k function limit and being a non android developer, things are getting harder as I have to tweak the build system. Some of the dependencies are heavy, but unavoidable like
google play services
google map
firebase auth, ..

after spending some time analyzing the APK, I realized the culprit is google_sign_in plugin , which add guava to the mix (adds 15k methods).  I think google_sign_in only uses very little of this library as seen in [these](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java#L23) imports

As far as I see, google_sign_in is the only plugin uses guava. Please remove guava dependency.

EDIT: 
I made an attempt to remove the references.
i see couple of imports, which may need some understanding of the platform to convert.
```
import com.google.common.util.concurrent.ListenableFuture;
import com.google.common.util.concurrent.SettableFuture;
```
prior art
https://github.com/flutter/plugins/pull/346
https://github.com/flutter/flutter/issues/13991

**Comment by escamoteur** [comment]
If *guava* is the culprit for the increase of functions IMHO we should reopen the referenced PR because a lot of people use and / will use google_sign_in  an run into such dex problems

**Comment by iapicca** [comment]
Hi @bsr203 
I see there's an open [issue](https://github.com/flutter/flutter/issues/13991) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
