### ISSUE TITLE
[google_maps_flutter] Add synchronous way to set padding

### ISSUE THREAD

**Issue by tzvc** [flutter/flutter#41298]
Hi there,

I'm trying to create a map with a responsive UI around it. To do that, when the UI layout change, I modify the padding of the map to reflect the changes.

This works great except if for example I want the map to stay centered on a point because if shift when the padding/change.

My first though was, I can just listen when the padding happened and manually recenter the map. However, as there is no synchronous way to set the map padding, it's hard to know when the change actually happened. (The only way I found to make it work is to listen to `addPostFrameCallback` and trigger the recenter here but this is very hacky).

I believe this usecase is pretty common on all map application where content depends on the current viewport.

Would it be possible to add a synchronous way to set padding on the map, via the `GoogleMapController` for example?

Cheers!

**Comment by escamoteur** [comment]
May I ask which padding you are referring to?

**Comment by theochampion** [comment]
@escamoteur The padding to be set on the map via the `padding` parameter on the `GoogleMap`class https://pub.dev/documentation/google_maps_flutter/latest/google_maps_flutter/GoogleMap/padding.html

**Comment by escamoteur** [comment]
Why not just wrap the map in a normal Padding?

**Comment by RyanRamchandar** [comment]
@escamoteur I believe the padding referred to here is within the Map itself, ie. to pad the Google logo, location and compass icons etc.

https://developers.google.com/maps/documentation/android-sdk/map#map_padding

**Comment by stuartmorgan** [comment]
Platform channels are inherently asynchronous (and proposals for synchronous calls all have issues with potential deadlocks, so there's no plan to implement them) so there's no way to implement this request.

Given that, closing.
