### ISSUE TITLE
Monitor dependency resolution failure rates

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#41309]
It would be useful to monitor dependency resolution failure rates following so issues like https://github.com/flutter/flutter/issues/41308 are surfaced.

This will generally be noisy, but I believe spikes should be meaningful.

**Comment by zanderso** [comment]
We track analytics for 'version solving failed' messages from pub here:

https://github.com/flutter/flutter/blob/48d5fcabbd805a622b74af2d2671ff0c845abdcd/packages/flutter_tools/lib/src/dart/pub.dart#L284
