### ISSUE TITLE
Debugging through USB on physical iPhone often gets HttpException (when phone and desktop are connected to same wifi network)

### ISSUE THREAD

**Issue by wliumelb** [flutter/flutter#41301]
When start debugging on my iPhone (connected to the computer through USB), I regularly get this error message: 
`Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1041/5cHcFx711Kk=/ws`

The error message shows up when running `flutter run` or with the debugging tool of VS code.
```
> edwin$ flutter run
> Launching lib/main.dart on Wenchao Liu’s iPhone in debug mode...
> Automatically signing iOS for device deployment using specified development team in Xcode project: 3S867Y73K3
> Running Xcode build...                                                  
>                                                    
>  ├─Assembling Flutter resources...                           6.8s
>  └─Compiling, linking and signing...                         4.6s
> Xcode build done.                                           74.4s
> Configuring the default Firebase app...                                 
> 6.8.1 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
> Configured the default Firebase app __FIRAPP_DEFAULT.                   
> 6.8.1 - [Firebase/Analytics][I-ACS023007] Analytics v.60101000 started  
> 6.8.1 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
> Installing and launching...                                        15.7s
> Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1041/5cHcFx711Kk=/ws
```
Despite the error, the app starts like normal, only the debugger stopped working (hot reloading too).

I have identified that this issue is wifi-related. To be clear, I did not attempt wireless debugging and the phone and desktop are always connected through the same USB cable. I tested under the following scenarios:

1. iPhone on wifi, desktop on same wifi - the problem often occurs(but not always)
2. iPhone on wifi, desktop on different wifi from the same router (2.4GHz and 5GHz networks) - same as above
3. iPhone on cellular data, desktop on wifi - never any issue
4. iPhone on wifi, desktop on a separate wifi network - never any issue 
5. iPhone on wifi, desktop disconnected from wifi - never any issue
6. iPhone on wifi, desktop disconnected from wifi, start the debugger, then reconnect to wifi - often get a slightly different error message when doing a hot reload: `Could not update files on device: HttpException: , uri = http://127.0.0.1:1033/CX2EYMGiynw=/`

Unplugging and replugging the phone sometimes (not always) solve the problem for a short period of time.

**Comment by janmoppel** [comment]
Hello @wliumelb !

Thank you for posting an issue.
Can you please also attach the `flutter doctor -v` command output?

Thank you.

**Comment by wliumelb** [comment]
Hi @janmoppel 

Here is the output.

> [✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-AU)
>     • Flutter version 1.9.1+hotfix.2 at /Users/edwin/development/flutter
>     • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/edwin/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.0)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.0, Build version 11A420a
>     • CocoaPods version 1.7.5
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 39.0.3
>     • Dart plugin version 191.8423
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] VS Code (version 1.38.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.4.1
> 
> [✓] Connected device (1 available)
>     • Wenchao Liu’s iPhone • aceee8140c056e8ecb8ee4de3d244454f7c492dc • ios • iOS 12.4.1
> 
> • No issues found!

Also, this issue is probably not related to firebase. I just started a new project with `flutter create` and got the same error.

**Comment by z234009184** [comment]
the same

**Comment by ctenuta** [comment]
Same here...

I think I will go back to native development. This problem is making me waste a lot of time!

**Comment by quetool** [comment]
I can confirm this issue happens when connected on the same wifi network. I debuggued all day with my Mac connected on my 5.8Ghz network and the iPhone connected on the 2.4Ghz one and no problema at all

**Comment by quetool** [comment]
I upgraded to `1.12.13+hotfix.7` and this is still an issue

**Comment by wliumelb** [comment]
This has not happened for a while. Guess it is somehow fixed already.
