### ISSUE TITLE
Disable analytics when running daemon from within our tools

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4132]
In daemon_client.dart, line 19, we run "flutter_tools daemon", which appears to be sending an analytics ping. Since this is an internal command, I don't think we're interested in tracking when our tools themselves run daemon.

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
It's somewhat interesting to know the usage of the tools from IDEs.

**Comment by sethladd** [comment]
The `daemon` tool is only used by IDEs?

**Comment by devoncarew** [comment]
Yup, it's what IDEs use to get device add/remove notifications.

**Comment by devoncarew** [comment]
Closing this as I don't think it hurts to track it.

**Comment by sethladd** [comment]
Would we know the difference between a human running `flx` and a tool/script ? Perhaps humans never run `flx` so we can reasonably assume a tool is driving it.

Leaving the report of `flx` means when we want to know the top commands our users are running, we'll have to filter out `flx`. That might be possible in the analytics UI.

**Comment by devoncarew** [comment]
We're sending in a `--suppress-analytics` arg to calls to `flx` from tooling (from the xcode script) now. Any place where we're not we should add that arg - we shouldn't need to do any filtering of the analytics data.

**Comment by sethladd** [comment]
Ah, I see. This is specifically about `daemon`, not the policy of sending pings from within tools. Gotcha. Thanks!
