### ISSUE TITLE
[web] run Flutter engine web tests in DDC mode too

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#41322]
We currently only run engine tests in dart2js mode. Therefore we are unable to catch DDC bugs as early as we should. One example is https://github.com/flutter/flutter/issues/40876, which ended up getting the "TODAY" label.

To catch such bugs early, we should run [engine Web tests](https://github.com/flutter/engine/tree/master/lib/web_ui/test) in DDC, _in addition_ to dart2js.

**Comment by godofredoc** [comment]
In the next couple of weeks we're adding support for windows and linux VMs to the devicelab would that help with this task?

**Comment by godofredoc** [comment]
@yjbanov is this something we still want to do?
