### ISSUE TITLE
Flutter Web should not hard-code `devicePixelRatio` to `1.0`

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#41328]
Since we hard-code `devicePixelRatio` to `1.0`, this prevents us from loading higher-resolution images. This can cause images to look pixelated on higher-resolution devices.

@ferhatb @yjbanov do you remember why we hard-coded it to `1.0`?

**Comment by yjbanov** [comment]
It was because for us browser == device, and we treat 1 CSS pixel as 1 framework pixel. However, this should only affect the framework, not the engine. In the engine we _are_ aware of the actual ratio. For example, `BitmapCanvas` uses it to allocate canvases such that they are not pixelated. Can we use the same strategy for images?

**Comment by hterkelsen** [comment]
The image loading code is in the framework. See: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/image_resolution.dart#L241

For `AssetImage`, the framework selects which asset variant to load based on the `devicePixelRatio` reported by `MediaQuery`. The framework should already be operating on logical pixels anyways, and only using `devicePixelRatio` when it needs sub-pixel perfect rendering (I think the framework also asks for it when rendering the cursor while text editing). I think we should provide the correct `devicePixelRatio` to the framework, and also remove the step in `BitmapCanvas` where we scale the canvas by the actual `devicePixelRatio`, since the framework is supposed to do that scaling for us.

**Comment by yjbanov** [comment]
Makes sense. Do you expect that it will affect how we set transforms and sizes in CSS properties on the DOM elements? Trying to estimate how much work this would be.

**Comment by yjbanov** [comment]
Another possibility (discussed at triage) is to flow this code through the engine so that as far as the developer is concerned the ratio is still 1.0, but when we're looking for the image multiplier we use a different value.

**Comment by hterkelsen** [comment]
I quickly experimented with not hard-coding the `devicePixelRatio` to `1.0` and it will be more work than initially expected to fix. I tried to allow the [`RenderView`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/view.dart#L139) to scale the root canvas, but this will only work in a single-canvas backend since when we create arbitrary canvases for pictures, we have already applied the transform to the top-level `<div>`.

**Comment by rxlabz** [comment]
Can this issue explain different results when calling the `path.contains(offset)` method on retina and not retina displays  ?

**Comment by hterkelsen** [comment]
@rxlabz perhaps. IIRC in order to get `path.contains` we create a new canvas, run the path in it, and see if the point is contained by the path. It's possible that we aren't scaling the canvas before drawing the path.

**Comment by rxlabz** [comment]
Thanks @hterkelsen , I found the web engine [`path.contains` method](https://github.com/flutter/engine/blob/fad38e252f0748d49471bf2e09a2eb74ea04ce0b/lib/web_ui/lib/src/ui/canvas.dart#L1641), which seems to rely on `Context2D.isPointInPath( offset )`. I'll try to dig deeper to understand if|how the hard-coded `devicePixelRatio` could lead to incorrect results.

I took me a lot of time to understand this bug. I use path.contains for hitTesting a non-rectangular `CustomPainter` and noticed incorrect "hit areas" on some screens. I finally found an easy workaround by manually scaling the offset with `html.window.devicePixelRatio`, but I hope it could be avoided.

**Comment by ferhatb** [comment]
Notes: /cc @hterkelsen 
As far as the framework is concerned:
- PointerEventConverter converts all offsets back to logical before using in framework.
- MediaQuery reads ui devicepixelratio and then is used for image resolution
- scroll physics adjusts based on physical ratio
- _updateSystemChrome() uses physical pixels as well for top/bottom overlay offsets.

On the engine side:
- we are already multiplying physicalX/Y of pointer events with ui.window.devicePixelRatio.
- canvas/layer/surface and init need updates
