### ISSUE TITLE
video_player crashes when I switch video url.

### ISSUE THREAD

**Issue by PreviousTlx** [flutter/flutter#41337]
## Code
```dart
  _playViedo(String url) async{
    _controller =
        VideoPlayerController.network(url);
    videoPlayerListener = () `{`
      if (videoController != null && videoController.value.size != null) {
        // Refreshing the state to update video player with the correct ratio.
        if (mounted) setState(() {});
        videoController.removeListener(videoPlayerListener);
        if (videoController.value.hasError) {
          print(_controller.value.errorDescription);
        }
      }
    };
    _controller.addListener(videoPlayerListener);
    if (_controller.value.hasError) {
      print(_controller.value.errorDescription);
    }
    await _controller.initialize();
    final VideoPlayerController oldController = videoController;
    if (mounted) {
      setState(() {
        videoController = _controller;
      });
    }
    await _controller.play();
    await oldController?.pause();
  }
```
```error:Once you have called dispose()```

**Comment by janmoppel** [comment]
Hello @PreviousTlx !

Thank you for posting the issue.
Can you please also provide more information, such as an output of the `flutter doctor -v` command and a full stacktrace of the error (if there is more information on the error)?

Your question might be a good fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) as well. Flutter has a very active and helpful community there, so feel free to post it there too.

Thank you.

**Comment by PreviousTlx** [comment]
Hello @janmoppel 
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale
    yue-Hant-CN)
    • Flutter version 1.7.8+hotfix.3 at
      /Users/tanglinxing/Android_tools/flutterDev/flutter
    • Framework revision b712a172f9 (3 months ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tanglinxing/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.2

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

Error:-------------------------------------------------------------------------------------------
I/flutter ( 2866): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 2866): The following assertion was thrown building Container(bg: BoxDecoration(color: Color(0xff000000)),
I/flutter ( 2866): constraints: BoxConstraints(0.0<=w<=Infinity, h=210.0)):
I/flutter ( 2866): A VideoPlayerController was used after being disposed.
I/flutter ( 2866): Once you have called dispose() on a VideoPlayerController, it can no longer be used.
I/flutter ( 2866): 
I/flutter ( 2866): When the exception was thrown, this was the stack:
I/flutter ( 2866): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:105:9)
I/flutter ( 2866): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:111:6)
I/flutter ( 2866): #2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:166:12)
I/flutter ( 2866): #3      _VideoPlayerState.deactivate (package:video_player/video_player.dart:496:23)
I/flutter ( 2866): #4      StatefulElement.deactivate (package:flutter/src/widgets/framework.dart:4100:12)
I/flutter ( 2866): #5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1755:13)
I/flutter ( 2866): #6      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5080:14)
I/flutter ( 2866): #7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1757:13)
I/flutter ( 2866): #8      _InactiveElements.add (package:flutter/src/widgets/framework.dart:1766:7)
I/flutter ( 2866): #9      Element.deactivateChild (package:flutter/src/widgets/framework.dart:3120:29)
I/flutter ( 2866): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2884:7)
I/flutter ( 2866): #11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 2866): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 2866): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 2866): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #19     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
I/flutter ( 2866): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 2866): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #25     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
I/flutter ( 2866): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #27     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4817:32)
I/flutter ( 2866): #28     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5208:17)
I/flutter ( 2866): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #30     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4817:32)
I/flutter ( 2866): #31     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5208:17)
I/flutter ( 2866): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #35     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter ( 2866): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 2866): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #41     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
I/flutter ( 2866): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #45     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter ( 2866): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #49     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter ( 2866): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #51     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4817:32)
I/flutter ( 2866): #52     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5208:17)
I/flutter ( 2866): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #56     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 2866): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #60     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter ( 2866): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #64     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 2866): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 2866): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #70     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
I/flutter ( 2866): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #72     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 2866): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #76     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 2866): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #80     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 2866): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #84     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter ( 2866): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #88     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter ( 2866): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #92     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 2866): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #96     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 2866): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 2866): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 2866): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 2866): #100    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
I/flutter ( 2866): #101    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter ( 2866): #102    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter ( 2866): #103    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter ( 2866): #104    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter ( 2866): #105    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter ( 2866): #109    _invoke (dart:ui/hooks.dart:236:10)
I/flutter ( 2866): #110    _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter ( 2866): (elided 3 frames from package dart:async)
I/flutter ( 2866): ════════════════════════════════════════════════════════════════════════════════════════════════════

If i  use  await oldController?.dispose(),I get this error;

**Comment by PreviousTlx** [comment]
Hello @janmoppel 
  If i am not use dispose, this error would be cause after i reload 15-20 times:

W/GrallocMapperPassthrough( 3219): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough( 3219): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough( 3219): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough( 3219): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough( 3219): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough( 3219): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough( 3219): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough( 3219): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough( 3219): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough( 3219): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough( 3219): buffer descriptor with invalid usage bits 0x2000
E/AudioTrack( 3219): AudioFlinger could not create track, status: -12
E/AudioTrack-JNI( 3219): Error -12 initializing AudioTrack
E/android.media.AudioTrack( 3219): Error code -20 when initializing AudioTrack.
E/ExoPlayerImplInternal( 3219): Playback error.
E/ExoPlayerImplInternal( 3219): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 70880)
E/ExoPlayerImplInternal( 3219): 	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:646)
E/ExoPlayerImplInternal( 3219): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1355)
E/ExoPlayerImplInternal( 3219): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
E/ExoPlayerImplInternal( 3219): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal( 3219): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal( 3219): 	at android.os.Handler.dispatchMessage(Handler.java:104)
E/ExoPlayerImplInternal( 3219): 	at android.os.Looper.loop(Looper.java:166)
E/ExoPlayerImplInternal( 3219): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal( 3219): Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 70880)
E/ExoPlayerImplInternal( 3219): 	at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:1128)
E/ExoPlayerImplInternal( 3219): 	at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:532)
E/ExoPlayerImplInternal( 3219): 	at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:593)
E/ExoPlayerImplInternal( 3219): 	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:640)
E/ExoPlayerImplInternal( 3219): 	... 7 more

**Comment by TahaTesser** [comment]
Hi @PreviousTlx 
Are you still experiencing this issue with latest stable?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @PreviousTlx 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
