### ISSUE TITLE
Flutter Web fails if user has activated Kaspersky 

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#41336]
Hi,

I open this issue because yesterday two people reported there problems with Flutter Web lies in their activated Kaspersky.

https://github.com/flutter/flutter/issues/41248

I think we should add an hint on this on the typical error message because more users will hit this.

Cheers
Thomas

**Comment by jonahwilliams** [comment]
I think I could mitigate this by updating the status when we're trying to connect, and also giving it a seems slow notification.

**Comment by yjbanov** [comment]
Can you please try again? #41347 has a better explanation for what might be going on.

**Comment by escamoteur** [comment]
@yjbanov I can't because I don't have Kaperski installed. I only saw several users have issues with it that's why I filed a independent issue for it. But I can ask them to try again.

**Comment by yjbanov** [comment]
@escamoteur Asking those users to try again would definitely help. I'll add the `waiting for customer response` label so it auto-closes if we don't hear back from them.

**Comment by escamoteur** [comment]
@yjbanov In this case we are not waiting for more information, the issue is not really fixed so I don't wan't it to be closed

**Comment by escamoteur** [comment]
@yjbanov Sorry mixed up this issue with another one with Kaperski problems

**Comment by jonahwilliams** [comment]
This is unlikely to be fixed, either in the near or long term. Ultimately if a user is running 3rd party anti-virus software that blocks the functionality of the flutter tool, then either:

1) The user does not trust the flutter tool, at which point they shouldn't be using it all - regardless of changes we make to work around the antivirus.
2) The user does trust the flutter tool, at which point they should use whitelist/exclusion functionality built into most antivirus software.


Of course, we will try to work within the bounds set by a Platform's standard security measures, such as ensuring executables are signed correctly to work with macOS Catalina. We cannot reasonably adjust our tooling to work with all 3rd party security systems.

**Comment by jonny7737** [comment]
> This is unlikely to be fixed, either in the near or long term. Ultimately if a user is running 3rd party anti-virus software that blocks the functionality of the flutter tool, then either:
> 
> 1. The user does not trust the flutter tool, at which point they shouldn't be using it all - regardless of changes we make to work around the antivirus.
> 2. The user does trust the flutter tool, at which point they should use whitelist/exclusion functionality built into most antivirus software.
> 
> Of course, we will try to work within the bounds set by a Platform's standard security measures, such as ensuring executables are signed correctly to work with macOS Catalina. We cannot reasonably adjust our tooling to work with all 3rd party security systems.

Please provide a link to the whitelist requirements.

**Comment by glofru** [comment]
I had the same problem and I actually solved with [this](https://github.com/flutter/flutter/issues/40515#issuecomment-726878465).
