### ISSUE TITLE
'TextEditingController' filter English letter when  input Chinese on iOS

### ISSUE THREAD

**Issue by mm-public-tx** [flutter/flutter#41344]
## Steps to Reproduce

When I input Chinese on iOS, the English letter will be placed in `textField` firstly. After I select 
Chinese keyboard, the Chinese character will be placed.

I use `TextEditingController` to listen `texChange`. I get notification when English letter change or Chinese character change, but I just want to be notified when Chinese character change.

I tried the code to avoid getting notification:
```dart
    if (_controller.value.composing.start != _controller.value.composing.end) {
      return;
    }
```

But I got notification still when I typed the first English letter.

Code:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _text;

  void _textChange(String text) {
    setState(() {
      _text = text;
    });
  }

  var _controller = TextEditingController();
  _listener() {
    if (_controller.value.composing.start != _controller.value.composing.end) {
      return;
    }
    _textChange(_controller.text);
    print("xxxxx ${_controller.text}");
  }

  @override
  void initState() {
    _controller.addListener(_listener);
    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    var textField = TextField(controller: _controller,);
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            textField,
            Text(
              '$_text',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
    );
  }
}
```
![gifhome_448x960_12s](https://user-images.githubusercontent.com/51780582/65658090-d19d4680-e058-11e9-85d9-d5dd31415ffa.gif)

```

[✓] Flutter (Channel wechat-beta, v1.9.1+hotfix.4-pre.10, on Mac OS X 10.14.5 18F203, locale en-CN)
    • Flutter version 1.9.1+hotfix.4-pre.10 at /Applications/sdks/flutter_plus_macos_v1.2.1-stable
    • Framework revision 72dfecb17c (2 days ago), 2019-09-24 10:58:06 +0800
    • Engine revision 09ca1075b2
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/garry/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/garry/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

```

**Comment by janmoppel** [comment]
Hello @mm-public-tx !

Thank you for posting an issue.
Your question might be also a good fit for the [StackOverflow](https://stackoverflow.com/tags/flutter). Flutter has a very active and helpful community there, so feel free to post it there too.

**Comment by mm-public-tx** [comment]
> Hello @mm-public-tx !
> 
> Thank you for posting an issue.
> Your question might be also a good fit for the [StackOverflow](https://stackoverflow.com/tags/flutter). Flutter has a very active and helpful community there, so feel free to post it there too.

I think it may be a bug.
When type ”a“ with pinyin IME, flutter received ”TextInputClient.updateEditingState“ twice. 
The first method call mislead me, because the composingExtend composingBase are -1, I will consider it is a letter "a" typed with English IME.

![image](https://user-images.githubusercontent.com/51780582/65673982-66ff0180-e07e-11e9-8ba9-1b74f684ca22.png)
![image](https://user-images.githubusercontent.com/51780582/65673987-69615b80-e07e-11e9-82dd-5005e3eda9af.png)

**Comment by escamoteur** [comment]
Could you please try it on latest master? There were some fixes connected to Chinese characters

**Comment by mm-public-tx** [comment]
> Could you please try it on latest master? There were some fixes connected to Chinese characters

which commit  fix it？

**Comment by escamoteur** [comment]
Don't know just switch to master and run an upgrade

**Comment by mm-public-tx** [comment]
> Don't know just switch to master and run an upgrade
My app need a stable flutter branch

**Comment by mm-public-tx** [comment]
@escamoteur The code of master is not working, I still get notifications when the first letter is typed with Pinyin IME.

**Comment by justinmc** [comment]
@GaryQian Do you know how this is supposed to work?  When entering pinyin, should only the committed text and not composing text be sent to the TextEditingController listener?

**Comment by GaryQian** [comment]
This is an interesting question, since some languages have much longer and fully legible composing regions, which would make sense to sent the composing region as a change. For example, should an english word send every letter typed while the word is "composing" for autocorrect? In this case, I believe the answer is yes. However, in other languages such as Chinese, pinying is not exactly a readable format and is not part of the text itself, but rather an intermediary representation. Here, we can argue that this should not count as a change in the actual text. Even then, there is Korean, where many complete hangul glyphs can be formed before being committed. If composing region was not sent, for Hangul, the only time the callback would be triggered would frequently be after entire sentences or paragraphs are typed.

It doesn't seem like we are able to make a blanket change to only trigger `textChange` on commit of text as that would break it for many other languages.

For now, A good bet may be to manually filter the calls to detect if it is a pinying call or a chinese character call. I can look further into this behavior to see if there is a reasonable solution to resolve all languages or not.

**Comment by justinmc** [comment]
Sounds good to me.

@mm-public-tx  If you try to work around this, it might be helpful to know that you can get the composing region from the controller like this:

```dart
TextRange composingRange = textEditingController.value.composing;
```

You could then do something like ignore changes if `composingRange.isCollapsed` isn't true.

**Comment by mm-public-tx** [comment]
@justinmc  

> Sounds good to me.
> 
> @mm-public-tx If you try to work around this, it might be helpful to know that you can get the composing region from the controller like this:
> 
> ```dart
> TextRange composingRange = textEditingController.value.composing;
> ```
> 
> You could then do something like ignore changes if `composingRange.isCollapsed` isn't true.

I tried, but it does not work. "de" is a composing text but `composingRange.isCollapsed` isn't true.
<img width="1321" alt="Jietu20191005-170706" src="https://user-images.githubusercontent.com/51780582/66252813-9b677180-e792-11e9-97e2-910f482e351b.png">

I tried `_controller.value.composing.start != _controller.value.composing.end`. but I can not filter the first letter of a composing text. eg, 'f' is the first letter of a composing text.

![Jietu20191005-171556](https://user-images.githubusercontent.com/51780582/66252945-e2a23200-e793-11e9-853a-4d143e2174f1.jpg)


Also, I tried the solution composing `composingRange.isCollapsed` and `_controller.value.composing.start != _controller.value.composing.end`. It did not work.

Maybe something goes wrong?

**Comment by justinmc** [comment]
Here is what I see:

```dart
print('justin change ${_controller.text} | ${composingRange.isCollapsed}');

```

```
flutter: justin change  | true
flutter: justin change n | true
flutter: justin change n | false
flutter: justin change ni | false
flutter: justin change ni | false
flutter: justin change 你 | false
flutter: justin change 你 | false
flutter: justin change 你 | true
flutter: justin change 你h | true
flutter: justin change 你h | false
flutter: justin change 你ha | false
flutter: justin change 你ha | false
flutter: justin change 你hao | false
flutter: justin change 你hao | false
flutter: justin change 你好 | false
flutter: justin change 你好 | false
flutter: justin change 你好 | true
```

Maybe you could filter out calls where `isCollapsed` is false and where the text is different from the previous call?  I'm not sure if this would work in all cases, but maybe it's a start.  Hopefully we can actually fix the root problem at some point.

**Comment by The-five-stooges** [comment]
face this issue too, ios origin IME have this problem

**Comment by zoeyfan** [comment]
@mm-public-tx have you been able to follow Justin's suggestion above? Will this be a viable workaround?

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 15a28159bc (9 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS desktop • macos                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!

``` 

</details>

**Comment by violinday** [comment]
We also face this problem, is there an official solution?
