### ISSUE TITLE
TimePicker AM/PM column layout can overflow

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4134]
![time_picker_overflow](https://cloud.githubusercontent.com/assets/1377460/15486892/a42bf1a6-20fd-11e6-9336-da62d047701b.png)

**Comment by Hixie** [comment]
cc @yjbanov in case you want to fix this since you were in the code recently.

**Comment by TahaTesser** [comment]
This issue is not reproducible in new gallery 
https://gallery.flutter.dev/#/demo/pickers 

If you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
