### ISSUE TITLE
CupertinoActivityIndicator animation is incorrect

### ISSUE THREAD

**Issue by boylenssen** [flutter/flutter#41345]
![rotation_incorrect](https://user-images.githubusercontent.com/5054262/65658533-75223300-e028-11e9-9465-fdf63ef2007d.gif)

The CupertinoActivityIndicator() widget is rotating clockwise, which is ok, but it should look like a rotating bar that is fading out behind it. Attached is a gif which shows the incorrect animation.

Please compare it with the official one: https://developer.apple.com/design/human-interface-guidelines/ios/controls/progress-indicators/

**Comment by janmoppel** [comment]
Hello @boylenssen !

Thank you for posting.
Can you please also provide an output of the `flutter doctor -v` command?

Thank you.

**Comment by boylenssen** [comment]
@janmoppel yes of course, here it is:

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-NL)
    • Flutter version 1.9.1+hotfix.2 at /Users/Boy/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Boy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.0.beta.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available
```

**Comment by escamoteur** [comment]
Also if I see it correct the original bars have rounded corners

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by boylenssen** [comment]
Incorrectly closed! The point that @escamoteur addressed has been fixed, but the spinner is still rotating the wrong way
![rotating_wrong](https://user-images.githubusercontent.com/5054262/66218410-693e0d00-e6c9-11e9-9634-8d505412c570.gif)

**Comment by LongCatIsLooong** [comment]
@boylenssen my apologies! I didn't interpret the issue correctly. You're right `UIActivityIndicatorView` does look different. The sketch file from https://developer.apple.com/design/resources/ is giving the wrong color and gradient :disappointed:

**Comment by boylenssen** [comment]
@LongCatIsLooong no problem :)

This looks perfect, thanks!
