### ISSUE TITLE
Can I use "flutter attach" and "flutter logs" at once

### ISSUE THREAD

**Issue by xpwmaosldk** [flutter/flutter#41357]
Hi

I have one problem with using `flutter attach`

When I attach device using `flutter attach`, I can't see logs :(

So I use attach menu in VSCODE and terminal command `flutter logs`

Can I use `flutter attach` and `flutter logs` at once?

**Comment by janmoppel** [comment]
Hello @xpwmaosldk !

Thank you for posting.
Can you please also attach the `flutter doctor -v` command output?

Your question seems to be a good fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) as well. Flutter has a very active and helpful community there, so feel free to post it there too.

Thank you.

**Comment by xpwmaosldk** [comment]
> [✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale
    en-KR)
    • Flutter version 1.9.1+hotfix.2 at /Users/ylabs/Documents/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ylabs/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/ylabs/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • SM N950N • ce081718402f68870d7e • android-arm64 • Android 9 (API 28)

Here my output 
thank you for your advice !

**Comment by escamoteur** [comment]
@jonahwilliams can he?

**Comment by ThinkDigitalSoftware** [comment]
I think this is a bug for the flutter team because otherwise, what can we do with flutter attach if not to simulate having launched it from the IDE?

**Comment by yprihodko** [comment]
bash: `flutter logs & flutter attach`
This will output the logs and provide hot reload at the same time.

**Comment by taz1208** [comment]
Not working :(
`flutter logs & flutter attach`is only output logs 
but `flutter attach & flutter logs`is can input some attach cmd..
However `flutter attach & flutter logs` show this message `suspended (tty input)  flutter attach` when I any key pressed

**Comment by zanderso** [comment]
Shouldn't `flutter attach` be echoing logs? /cc @blasten

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
