### ISSUE TITLE
Add a lowercase option to TextInputField.textCapitalization

### ISSUE THREAD

**Issue by ricardobrg** [flutter/flutter#41368]
The TextInputChannel makes possible the automatic capitalization of TextInputFields through TextCapitalization property. There are 4 possible values for this property: [CHARACTERS, WORDS, SETENCES, NONE](https://github.com/flutter/engine/blob/dce8a34048e9e0eff0fd43b125bf395db8766a2d/shell/platform/android/io/flutter/embedding/engine/systemchannels/TextInputChannel.java#L397-L419).

This property is used in platform specific codes ([Android](https://github.com/flutter/engine/blob/efb7bf434f2c993dc0f44a83fa13efcda127526a/shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java#L175-L181),[iOS](https://github.com/flutter/engine/blob/d1c71e5206bd9546f4ff64b7336c4e74e3f4ccfd/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L33-L43)) and there is no option for lowercase text.

**Comment by hanneskuettner** [comment]
It seems to me like the enum values are matched 1:1 to the native input type flags / values. For Android that is [`TYPE_TEXT_FLAG_CAP_*`](https://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_FLAG_CAP_CHARACTERS) and for iOS [`UITextAutocapitalizationType`](https://developer.apple.com/documentation/uikit/uitextautocapitalizationtype). 

According to the docs these only serve as a hint to the system keyboard on what capitalization strategy to follow. This behavior can still be overridden by the user by using the shift key, if they wish to. It does not ensure that resulting text is actually in the desired capitalization.

This aligns with what the [`TextCapitalization`](https://api.flutter.dev/flutter/services/TextCapitalization-class.html) docs describe. The capitalization defaults to `none` which is described as defaulting to the lower case keyboard in the docs.

As such I think this is not a new feature but already sufficiently represented in the framework. Anything I overlooked?

**Comment by ricardobrg** [comment]
@hanneskuettner that's correct. What I mean is that an option for lowercase input could be added in the framework even if there's none in the specific platforms. Treating this input fields with .toLowerCase, for example, in dart code. I don't know if it would be better implemented in the framework or extending the TextField or TextFormField class...

**Comment by Hixie** [comment]
The TextCapitalization enum is about what the IME keyboard should default to. There's already a lowercase version, `TextCapitalization.none`.  The setting isn't about forcing a particular input (unless the IME implements it that way). If you want to force a particular input, that should be done by post-processing the input after the user has entered the text.
