### ISSUE TITLE
Firebase google sign-in crashes on production mode

### ISSUE THREAD

**Issue by Lynxgsm** [flutter/flutter#41362]
Hello everyone, i've used flutter packages like: 
- firebase_auth: ^0.11.1+8
- google_sign_in: 4.0.4

to (well) sign-in into Google using **Firebase**. In development mode, the app runs well and get authenticated, but in production mode, the app crashes when the Google sign-in popup displays. I've also set the SHA certificates.

Can you guess what the problem is? Thanks in advance!

**Comment by janmoppel** [comment]
Hello @Lynxgsm !

Thank you for posting an issue.
Can you please provide an additional information, such as:
1. the `flutter doctor -v` command output;
2. the full stacktrace of the error.

Thank you.

**Comment by Lynxgsm** [comment]
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X
    10.14.6 18G95, locale en-GB)
    • Flutter version 1.9.1+hotfix.2 at
      /Users/Shared/lib/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06
      18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/etech/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • SM G960F • 22a0b7086c0d7ece • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by Lynxgsm** [comment]
I've got no stacktrace because the app crashes on google signin on release mode.

**Comment by escamoteur** [comment]
you don't get any output? Could you please also try to check in android logcat?

**Comment by escamoteur** [comment]
Also could you create a minimal project and see it it stil happens?
Check your pubspec.lock that you are really using the latest versions of the plugins.

**Comment by kroikie** [comment]
@Lynxgsm

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/327. Any further collaboration will be done there.
