### ISSUE TITLE
Use system boringssl on iOS

### ISSUE THREAD

**Issue by wangying3426** [flutter/flutter#41363]
Can we use system libboringssl.dylib to reduce Flutter.framework size on iOS?

**Comment by escamoteur** [comment]
Why do you think this woud reduce the framework size?

**Comment by stuartmorgan** [comment]
See https://boringssl.googlesource.com/boringssl/

There is no API or ABI stability guarantee, which means that depending on a dylib of BoringSSL that we don't control would be disastrous. That's explicitly not how it's intended to be used.
