### ISSUE TITLE
DatePicker could animate the Month label's color

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4136]
This does not appear to be a feature of the Material Design spec ...

Fading the Month title as it's dragged away from the center of the PageableList seems like a nice flourish.

**Comment by Hixie** [comment]
cc @yjbanov in case you are interested in doing this. Should be relatively easy.

**Comment by timsneath** [comment]
It seems unlikely that we're going to address this in the foreseeable future.

**Comment by HansMuller** [comment]
A significant update to the date/time picker widgets is underway per https://material.io/components/pickers/; we hope to land it in January/Februrary of 2020.

I'm going to close this issue, since we're planning to (just) build what's in the spec.

CC @darrenaustin
