### ISSUE TITLE
[Web] Navigation and window href

### ISSUE THREAD

**Issue by jamesblasco** [flutter/flutter#41375]
## Problem

Hi, I am testing a web app with flutter and the url doesn't change as expected when pushing a route from navigation. 

By default the url doesn't change from https://<..>/#/ but sometimes it also appears the name of  a new route like https://<..>/#/dashboard.

<img width="526" alt="Captura de pantalla 2019-09-26 a las 16 17 34" src="https://user-images.githubusercontent.com/19904063/65696249-2ea8f480-e079-11e9-91fb-ec6f8ba4718f.png">

 Using the native chrome navigation for going forward and back doesn't work either as expected. 

### Proposal
I have been testing my self an example of how I would do it.
1. If you are in the route /page1 your url would look like  https://<..>/#/page1
2. If you are in the route /page2 your url would look like  https://<..>/#/page2
3. If you change routes it updates the url

![ezgif-4-29054d4381e5](https://user-images.githubusercontent.com/19904063/65697184-ca873000-e07a-11e9-8722-7c7205f7c4da.gif)

```dart


import 'dart:html' as html;

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
            initialRoute: '/page1',
            onGenerateRoute: (settings)  {
               html.window.history.pushState(null, settings.name, '#' + settings.name);
               print(html.window.location.href);
               switch(settings.name) {
                 case '/page1': return MaterialPageRoute(builder: (_) => Page1());
                 case '/page2': return MaterialPageRoute(builder: (_) => Page2());
               }
               return MaterialPageRoute(builder: (_) => Page1());
            },
            title: 'History test'
    );
  }
}


class Page1 extends StatelessWidget
{
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      backgroundColor: Colors.green,
      appBar: AppBar(title: Text('Page 1'),),
      body: Center(
        child: FlatButton(
          child: Text('Go to page 2'),
          onPressed: () => {
              Navigator.of(context).pushNamed('/page2')
          },
        ),
      ),
    );
  }

}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.red,
      appBar: AppBar(title: Text('Page 2'), leading: Container(),),
      body: Center(
        child: FlatButton(
          child: Text('Go back'),
          onPressed: ()  {
            if(Navigator.of(context).canPop()) {
              Navigator.pop(context);
              html.window.history.pushState(null, null, '#' + '/page1');
            } else {Navigator.pushReplacementNamed(context, '/page1');}
          },
        ),
      ),
      
    );
  }

}
```

(the example doesn't work with the navigation native buttons for pushing back and forward.  )

**Comment by BondarenkoStas** [comment]
@jamesblasco Please provide your flutter doctor -v output.

**Comment by jamesblasco** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.7-pre.23, on Mac OS X 10.14.6 18G95, locale es-ES)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (4 available)

• No issues found!

**Comment by AppleEducate** [comment]
I was able to work with the forward and back buttons and even use deep linking by using the routes: {} builder on MaterialApp. You cannot use onGenerateRoute

I also dynamically add more routes for all the posts so i can have shareable links to my website:

```dart

class Router {
  static Map<String, WidgetBuilder> routes(BlogState state) {
    return {
      HomeScreen.routeName: (_) => HomeScreen(),
      AboutScreen.routeName: (_) => AboutScreen(),
      PrivacyPolicy.routeName: (_) => PrivacyPolicy(),
      AppsScreen.routeName: (_) => AppsScreen(),
      BlogScreen.routeName: (_) => BlogScreen(),
      ProjectsScreen.routeName: (_) => ProjectsScreen(),
      if (state is PostsReady) ...{
        for (var post in state.posts) ...{
          "/blog/${post.documentId}": (_) => PostDetails(
              id: post.documentId,
              post: FbPost.fromJson(json.decode(json.encode(post.data)))),
        },
      }
    };
  }
}
```

This also updates the href, and this is not needed. 
```
html.window.history.pushState(null, settings.name, '#' + settings.name);
print(html.window.location.href);
```

**Comment by mdebbar** [comment]
@jamesblasco I took a look at your example and I was able to figure out what's happening. 

In `onGenerateRoute()`, you are receiving `settings` which correctly contains the route name. But you are not passing it to `MaterialPageRoute()`. Because of this, the generated route has no idea what its name should be, so it doesn't update the url.

To see the URL updated correctly, you could modify your code like this:
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      initialRoute: '/page1',
      onGenerateRoute: (settings)  {
          switch(settings.name) {
            case '/page1': return MaterialPageRoute(settings: settings, builder: (_) => Page1());
            case '/page2': return MaterialPageRoute(settings: settings, builder: (_) => Page2());
          }
          return MaterialPageRoute(settings: settings, builder: (_) => Page1());
      },
      title: 'History test'
    );
  }
}
```

That being said, there's an issue you pointed out that still needs to be fixed in the framework. When a nameless route is pushed, we are not clearing the route name in the browser address bar. I'm gonna send a PR soon to fix it.

Hope this helps!

**Comment by AppleEducate** [comment]
Please check out my example. This will do exactly what you want with dynamic and named routes 👍🏼 https://github.com/AppleEducate/flutter_routing

**Comment by jamesblasco** [comment]
I will take a look! Thankks
