### ISSUE TITLE
 Failed assertion: line 2800 pos 15: 'baselineType != null': is not true.

### ISSUE THREAD

**Issue by DavidMGT** [flutter/flutter#41373]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by DavidMGT** [comment]
code
 import 'package:flutter/material.dart';
import 'package:flutter_david/common/style/boss_style.dart';
import 'package:flutter_david/model/currency.dart';
import 'package:flutter_david/utils/util.dart';

class PickCurrency extends StatefulWidget {
  var selected_currency;
  var callback;

  PickCurrency({this.selected_currency, this.callback});

  @override
  State<StatefulWidget> createState() {
    return _PickCurrencyState(
        selected_currency: selected_currency, callback: callback);
  }
}

class _PickCurrencyState extends State<PickCurrency> {
  var selected_currency;
  var callback;

  _PickCurrencyState({this.selected_currency, this.callback});

  @override
  Widget build(BuildContext context) {
    return Row(children: <Widget>[
      PopupMenuButton<Currency>(
        child: Padding(
          padding: EdgeInsets.only(
            left: 10,
          ),
          child: Center(child: Text(selected_currency.title)),
        ),
        onSelected: _select,
        itemBuilder: (BuildContext context) {
          // ignore: dead_code
          return enum_currencylist.map((Currency choice) {
            return PopupMenuItem<Currency>(
              value: choice,
              textStyle: TextStyle(color: BossColors.primaryBlueColor),
              child: Text(choice.title),
            );
          }).toList();
        },
      ),
      Icon(
        Icons.arrow_drop_down,
        color: Colors.white,
      )
    ]);
  }

  void _select(Currency value) {
    setState(() {
      selected_currency = value;
      callback(value);
    });
  }
}

**Comment by AbdurrahmanElrayes** [comment]
you have to set
 
> textBaseline

for each of your popupMenuItem or generally in your theme

`textStyle: TextStyle(textBaseline: TextBaseline.alphabetic)`

**Comment by sciobotaru** [comment]
had the same issue and this was the fix. thanks

**Comment by TahaTesser** [comment]
Hi @DavidMGT 
Please check the above [solution comment](https://github.com/flutter/flutter/issues/41373#issuecomment-546554373)
If you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
