### ISSUE TITLE
initState method is not called on state when returning via navigator pop

### ISSUE THREAD

**Issue by stevebeard** [flutter/flutter#41377]
According to the docs of State.initState this method is
> Called when this object is inserted into the tree.

And the docs for State.deactivate:
> Called when this object is removed from the tree.

Therefore I would expect that initState should be called after my stateful widget is deactivated (removed from the tree) once it is returned. However my experience is that initState is not called for the first view in a navigator even though deactivate has been called on this object.

This is a problem as I would expect to perform actions such as closing resources and removing listeners on deactivate (as my view is no longer present), but without the initState callback I am unable to re-open/reregister listeners etc.

## Steps to Reproduce

Below is an example main.dart file to expose the issue I am seeing. This is based upon the navigation example (https://flutter.dev/docs/cookbook/navigation/navigation-basics)

**main.dart**

```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Navigation Basics',
    home: FirstRoute(),
  ));
}

class FirstRoute extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _FirstRouteState();
  }
}

class _FirstRouteState extends State<FirstRoute> {
  @override
  void initState() {
    super.initState();
    print("FirstRoute: initState");
  }

  @override
  void deactivate() {
    print("FirstRoute: deactivate");
    super.deactivate();
  }

  @override
  void dispose() {
    print("FirstRoute: dispose");
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Route'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('Open route'),
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => SecondRoute()),
            );
          },
        ),
      ),
    );
  }
}

class SecondRoute extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _SecondRouteState();
  }
}

class _SecondRouteState extends State<SecondRoute> {
  @override
  void initState() {
    super.initState();
    print("SecondRoute: initState");
  }

  @override
  void deactivate() {
    print("SecondRoute: deactivate");
    super.deactivate();
  }

  @override
  void dispose() {
    print("SecondRoute: dispose");
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Route"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```

1. Run the app
2. Press the "Open route" button
3. Press the "Close route" button
4. Examine debug logs and note that initState is never called on FirstRoute after deactivate

## Logs

```
I/flutter (15277): FirstRoute: initState
I/flutter (15277): SecondRoute: initState
I/flutter (15277): FirstRoute: deactivate
I/flutter (15277): FirstRoute: deactivate
I/flutter (15277): SecondRoute: deactivate
I/flutter (15277): SecondRoute: dispose
```

flutter analyze
```
Analyzing test_state...                                                 
No issues found! (ran in 1.0s)
```

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.9.1+hotfix.2 at /home/steve/Flutter/Sdk/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/steve/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /home/steve/Android/Sdk
    • Java binary at: /home/steve/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/steve/android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /home/steve/Applications/IntelliJ IDEA
    • Flutter plugin version 37.1.3
    • Dart plugin version 191.7830

[✓] VS Code (version 1.38.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Nexus 6 • ZX1G429WDC • android-arm • Android 7.1.1 (API 25)

• No issues found!
```

**Comment by stevebeard** [comment]
Since creating this issue I have found that the Future returned from Navigator.push can be used to execute logic when returning to a page. As this resolves the main concern I had over the handling of state for pages within a navigator I am happy to close this issue. 

I do still feel that the docs for State.deactivate are a little confusing/misleading, at least for the case that I have outlined. I suspect that State.deactivate is just not suitable for what I was trying to achieve.

**Comment by lizbrownwood** [comment]
Hi Steve, can you please explain your solution a bit more? I have the same problem.

**Comment by stevebeard** [comment]
Hi Liz,

I am no longer actively doing flutter development, however I will do my best to clarify.

When using Flutter Navigator.push to change from page A to page B, I had previously expected page A to be disposed and page B to be initialized (initState called). This would allow me to perform clean up on page A (close any connections, streams etc.) and to initialize state for page B (open connections, streams etc.). The misconception here is that page A is not disposed. It is kept in the navigator history/stack to facilitate returning via Navigator.pop. Interestingly deactivate is called on page A.

When returning to page A via Navigator.pop page B is disposed of (fully removed from the tree), so clean up can be performed (via overriding the dispose method). However initState is not called on page A. My understanding is that page A was not considered removed from the tree due to being part of the Navigator stack (it may have even still been visible - e.g a popup dialog).

I have later found that an effective method of handling state when returning to a page via the Navigator can be achieved by utilizing the future that is returned from the Navigator.push methods. This future will be executed when the navigator pops back to this page, and can contain an optional payload which is populated by the caller of Navigator.pop.

I suggest having a look at the documentation for Navigator. https://api.flutter.dev/flutter/widgets/Navigator-class.html. There is a small section named "Routes can return a value" which gives an example of how to get the value returned from Navigator.push. If the value is not of interest, then you could instead perform some action in the future to effectively perform the desired state initialization.

**Comment by pedromassangocode** [comment]
Hi @stevebeard 
I tried your code with the latest `master` channel and bellow is my output:

```
I/flutter ( 8476): FirstRoute: initState
I/flutter ( 8476): SecondRoute: initState
I/flutter ( 8476): SecondRoute: deactivate
I/flutter ( 8476): SecondRoute: dispose
```

[`initState`](https://api.flutter.dev/flutter/widgets/State/initState.html) is supposed to run only once, that is when the State object is inserted into the tree. Not sure what should be improved into the docs, so please for anyone having the same issue, please open a new one describing what exactly should be improved into the docs to avoid misunderstanding.
Thank you

**Comment by jdeltoft** [comment]
Thanks @stevebeard !  I had one other interesting learning on this.  When I was pop'ing to go back to a screen that screen had text fields (login screen).  I realized that I needed to unfocus the text field to dismiss the keyboard, which I actually just did on the press of the "login" button instead.  But thanks for this sharing!!  I will keep this in the back of my head.
