### ISSUE TITLE
Add hintOverflow option for hint in inputDecoration

### ISSUE THREAD

**Issue by marinat** [flutter/flutter#41371]
I'm using textfiled with Input decoration in appbar of my application. By default, if I add suffix icon in input decoration, ellipsis not very suitable for long words:
![device-2019-09-26-154932](https://user-images.githubusercontent.com/978076/65689401-af65f180-e075-11e9-8d49-8253aea18898.png)
even suffix icon will be in Visibility with visible option = false.

Hot fix: I manually changed overflow option for hint in input_decorator.dart:2066 to fade and got nice result:
![device-2019-09-26-155857](https://user-images.githubusercontent.com/978076/65689936-a9244500-e076-11e9-99a3-7eafb01e6f26.png)

**Comment by escamoteur** [comment]
I'm not clear what your proposal is, because you could achieve the look that you want by using the InputDecoration

**Comment by marinat** [comment]
@escamoteur I already use InputDecoration and ask to add new option hintOverflow in it.

**Comment by escamoteur** [comment]
You mean cou can set it for the input text but not for the hint?

**Comment by marinat** [comment]
Here code from input_decorator.dart how hint creates:
`final Widget hint = decoration.hintText == null ? null : AnimatedOpacity(

      opacity: (isEmpty && !_hasInlineLabel) ? 1.0 : 0.0,
      duration: _kTransitionDuration,
      curve: _kTransitionCurve,
      child: Text(
        decoration.hintText,
        style: hintStyle,
        overflow: TextOverflow.ellipsis,
        textAlign: textAlign,
        maxLines: decoration.hintMaxLines,
      ),
    );`

I want to swap overflow: TextOverflow.ellipsis on something like overflow: decoration.hintOverflow

If needed I can do pull request.

**Comment by marinat** [comment]
Sorry, reached the desired behavior by adding isVisible condition in project code:
`suffixIcon: isVisible ? null : IconButton(`
