### ISSUE TITLE
DatePicker could hide the page back/fowards arrows during a horizontal drag

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4138]
This is not a feature of the Material Design spec...

Dragging the month title to the left or right positions it below the back/forwards arrows. It might be nicer to hide the arrows during a drag gesture.

![date_picker](https://cloud.githubusercontent.com/assets/1377460/15487137/9dc4647c-20ff-11e6-95fd-66f3a63dbda1.png)

**Comment by Hixie** [comment]
cc @yjbanov in case you're interested in working on this one too.

**Comment by mjohnsullivan** [comment]
With #5267 animating the chevrons to semi transparent, should we just make them completely transparent for the drag gesture?

**Comment by HansMuller** [comment]
Fading the chevrons out during the drag sounds reasonable to me.

**Comment by mjohnsullivan** [comment]
Fixed the #19422
