### ISSUE TITLE
how does flutter doctor determine if there is a device, specifically on iOS?

### ISSUE THREAD

**Issue by rbucker** [flutter/flutter#41381]
## Steps to Reproduce

This is an information request so that I might be able to infer or determine why my configuration does not work. I have posted an issue separately for the specific issue but maybe this is a better approach.

## Logs

- does xcode need to be running when running ```flutter doctor```?
- does itunes need to be running when running ```flutter doctor```?
- if there is a 2012 MBA and a 2019 MBA with USB-A and USB-C respectively is there any code in flutter that is effected? I do not know if flutter monitors which USB controller or device. I get different behaviors from Android devices on the same two laptops.

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/rbucker/dev/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rbucker/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by rbucker** [comment]
I have determined that there is a file ```lockdownd``` and it seems that the chmod is 0700 and that might not work. Someone suggested changing it to 0705 so that the "user" can read it.

Then I found the util ```ideviceinfo``` that pulls plenty of data from the phone. I did post a bug as there was at least one data request that had a bad param.  Flutter is supposed to call this function to retrieve it's configuration but I have not been able to confirm it yet. Yet ```flutter doctor``` still returns the NO DEVICES AVAIL.. response.

**Comment by rbucker** [comment]
I have also found idevice_id.  The PROBLEM here is that if you do a ```flutter doctor -v --bug-report``` then open the zipfile... and grep the files for ```idevice_id``` you'll eventually find the file but the path either may not resolve or the program does not produce the correct results. This is in conflict with the ```brew``` installation of ```libimobiledevice```. That project puts the ```idevice_id``` in ```/usr/local/bin```

**Comment by rbucker** [comment]
nudge

**Comment by christopherfujino** [comment]
`flutter doctor` depends on neither Xcode nor iTunes be open. Device discovery is done via `idevice_id`, but not we use our own binary that we distribute with the flutter tool. It is located in `flutter/bin/cache/artifacts/libimobiledevice/idevice_id`.

**Comment by jmagman** [comment]
Does @christopherfujino's response answer your question?  You didn't describe the issue you were seeing, just "my configuration does not work".

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
