### ISSUE TITLE
DART should allow you to check if null is > 0

### ISSUE THREAD

**Issue by jdeltoft** [flutter/flutter#41380]
Sometimes I want to use the null operator on my inherited data to avoid using it if it's null.  So I'll do something like this:

`      
if ((SessionInfo.of(context).myCommissionData == null) ||
       (SessionInfo.of(context).myCommissionData.length == 0)) {
... 
}
`

But is there a better way to do something like this:

`
if (SessionInfo.of(context).myCommissionData?.length > 0) {
...
}
`

This complains, since you can't compare "null" to zero with > .

**Comment by stuartmorgan** [comment]
This would be a request for https://github.com/dart-lang/language, not Flutter.

(What you're asking for is contrary to the goal of type safety, so I suspect it's not something the Dart team would implement. But the repository above would be the place to request/discuss that.)
