### ISSUE TITLE
Scrolling List's bottom sheet is probably modal, should dim rest of screen

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4139]
Open Gallery, go into components, lists. Tap the menu icon in the upper right to open the bottom sheet.

I think the bottom sheet is modal. If so, the [spec](https://www.google.com/design/spec/components/bottom-sheets.html#bottom-sheets-modal-bottom-sheets) says "When a modal bottom sheet slides into the screen, the rest of the screen dims, giving focus to the bottom sheet."

**Comment by HansMuller** [comment]
The list configuration bottom sheet is currently a "persistent bottom sheet" which is not supposed to be modal.
https://www.google.com/design/spec/components/bottom-sheets.html#bottom-sheets-persistent-bottom-sheets

There may be a better way to present the options for this demo.  The idea was to let the user see the effect of reconfiguring the list in situ.

**Comment by sethladd** [comment]
Ah, OK. Thanks for the clarification!
