### ISSUE TITLE
Regression in image_list_jit_reported_duration

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#41392]
Starting at https://github.com/flutter/flutter/pull/41222, the "image_list_jit_reported_duration" benchmark regressed (baseline 1.5s, actual 6.6s).

@jonahwilliams

**Comment by jonahwilliams** [comment]
_highly_ unlikely, given that this code only runs in profile/release web builds.

**Comment by goderbauer** [comment]
@aam You recently switched that benchmark to use HTTPS, right? Could that be the cause?

**Comment by goderbauer** [comment]
Oddly enough, the HTTP commit (https://github.com/flutter/flutter/commit/4f3199f864beeab64c07a9de439a8ec82dd61060) is right after the commit on which the regression started according to our Dashboard.

**Comment by goderbauer** [comment]
In the repository the HTTPS commit actually came before Jonah's commit. The dashboard is showing them in the wrong order because of https://github.com/flutter/cocoon/issues/420. The actual culprit is https://github.com/flutter/flutter/pull/39124.

**Comment by aam** [comment]
Yeah, regression was as expected due to switch from http to https.
I tried rebasing the benchmarks, but somehow it just hangs at "Calculating autoupdate..."

**Comment by goderbauer** [comment]
I am taking the TODAY label off then since this doesn't need to block anything. I am currently also unable to rebase the benchmark, though.

**Comment by tvolkert** [comment]
I've re-baselined the benchmarks.   Closing.  Re-open if necessary.
