### ISSUE TITLE
Support launching devtools from the flutter tool

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#41407]
This could be done via an additional keycode command, like `K`. The logic to launch devtools is fairly straightforward. For example, see the following code in dwds:

https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/servers/devtools.dart

**Comment by jonahwilliams** [comment]
cc @jacob314 @zanderso

**Comment by zanderso** [comment]
I think it would be good for the tool to delegate as much as possible (spinning up the server, launching the browser, etc.) to the devtools package(s). In that case calls like `serveDevTools()` and `launchDevTools()` from [here](https://github.com/flutter/devtools/blob/master/packages/devtools_server/lib/src/server.dart#L459) look promising.

It looks like we first need to get `package:devtools_server` bumped far enough forward to pick up all the calls. This is probably the right time in the release cycle to update dependencies like this.

**Comment by zanderso** [comment]
> It looks like we first need to get package:devtools_server bumped far enough forward to pick up all the calls.

Oh, it looks like a version of `devtools_server` that includes `launchDevTools()` hasn't been published yet if I'm reading things right. (https://github.com/flutter/devtools/pull/1365). @DanTup @devoncarew

**Comment by DanTup** [comment]
Looks like that change landed 28 days ago, and the last release (0.1.13) was 11 Dec, so I would expect that change to be in there. It is possible to launch DevTools from earlier versions, but it had to be done over the VM service (whereas now it can be done via stdin).

I presume the server would only be spun up once the user asks for it (and not at startup)? Otherwise, we should be sure to skip it when running in `--machine` mode, since IDEs might spawn their own copy (and having multiple copies of DevTools try to register the same VM services would likely cause issues).

**Comment by zanderso** [comment]
I'm only seeing 0.1.12 on pub: https://pub.dev/packages/devtools_server

**Comment by zanderso** [comment]
> I presume the server would only be spun up once the user asks for it (and not at startup)?

That's right, e.g. when pressing a key at the command line hot reload prompt.

**Comment by DanTup** [comment]
Oops sorrry, I was looking at https://pub.dev/packages/devtools/versions and didn't realise the server didn't get the same last update.

@jacob314 @kenzieschmoll FYI (I think @devoncarew will also want this for https://github.com/flutter/flutter-intellij/issues/3503). If there's a DevTools release coming soon, it'd be good to include the server.

**Comment by zanderso** [comment]
@DanTup it looks like you're listed as an uploader for devtools_server. Is all that is missing here pushing 0.1.13 to pub?

**Comment by DanTup** [comment]
When a new server is published, then `devtools` needs to also be updated to reference that version and be published. I don't have access to that account to publish anymore; @jacob314 may be the best person to ask about releases.

**Comment by zanderso** [comment]
This is done in https://github.com/flutter/flutter/pull/53902
