### ISSUE TITLE
In tests, setMockMethodCallHandler interferes with text state

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#41413]
Calls to `SystemChannels.textInput.setMockMethodCallHandler` cause the test to be in a weird state where subsequent calls to `enterText`, even in other tests in the same file, will fail with this error:

```
Tried to use TestTextInput with no keyboard attached. You must use WidgetTester.showKeyboard() first.
```

Here is a simple test file that reproduces the failure:

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('text field respects keyboardAppearance from theme', (WidgetTester tester) async {
    final List<MethodCall> log = <MethodCall>[];
    SystemChannels.textInput.setMockMethodCallHandler((MethodCall methodCall) async {
      log.add(methodCall);
    });

    await tester.pumpWidget(
      const CupertinoApp(
        theme: CupertinoThemeData(
          brightness: Brightness.dark,
        ),
        home: Center(
          child: CupertinoTextField(),
        ),
      ),
    );

    await tester.enterText(find.byType(CupertinoTextField), 'asdf');
  });
}
```
It seems like there is some cleanup that needs to happen.  The [docs state](https://master-api.flutter.dev/flutter/services/MethodChannel/setMockMethodCallHandler.html) that passing null to the same call will unassign the callback, but that doesn't fix the problem.

I found this bug while working on https://github.com/flutter/flutter/pull/41326.  Adding a test that used `enterText` passed or failed depending on where in the file I put it.  This is a dangerous bug that could cause tricky phantom test failures in the future.

**Comment by markusaksli-nc** [comment]
The referenced error no longer occours and the test passes when `tester.testTextInput.register();` is added.

Can we close this @justinmc?

**Comment by justinmc** [comment]
Sounds good, thanks for checking.  I'm glad this is fixed somehow.
