### ISSUE TITLE
Discussion: Order between mouse event calls (onEnter and onExit)

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#41420]
The [current algorithm](https://github.com/flutter/flutter/blob/26465f4c657bc5e3bdbcf3b0b399e6e41622a185/packages/flutter/lib/src/gestures/mouse_tracking.dart#L225) of `MouseTracker.sendMouseNotifications` doesn't really guarantee an order between events (more specifically, the order between `onEnter` and `onExit` calls) that is clear or reasonable enough, which has caused some counter-intuitive cases (such as #40000).

To evaluate an alternative algorithm, the following aspects might be considered:
1. The order between the same kind of events from a layer and those from its descendant.
1. The order between the same kind of events from a layer and those from its sibling or the descendant thereof.
1. The order between `onEnter` and `onExit` from different layers.
1. Performance.

I would like an algorithm that meets the following criteria (for each pointer):
1. The tree is walked only once. Walking the tree is expensive.
1. A parent always calls `onEnter` before its descendants, and calls `onExit` after its descendants. The idea is that, since parents always contain their descendants, as a pointer moves in, it always enters the parent before the descendants, and exit the parent after the descendants.
1. All `onExit`s are called before `onEnter`s. This is to fix #40000, but honestly this is stricter than necessary, and may not produce the most intuitive result in cases of overlapping sibling layers.
1. All `onHover`s are called after `onEnter`s.

To consider criteria 2, notice that in the traversing order or `Layer.findAnnotations` (visual order from front to back), a layer is always visually behind its descendants. Therefore we can extend criteria 2 into: 

2*. `onEnter`s are always called in reversed visual order, while `onExit`s are always called in visual order.

By combining 2* and 3, we can come up with the following algorithm:
1. Walk the tree and find the list of annotations that contains the target pointer in visual order, `thisAnnotations` (an empty list if the pointer is disconnected).
1. Let `prevAnnotations` be the similar list during the last frame.
1. The list of annotations to call `onExit` on is `prevAnnotations.toSet() - thisAnnotations.toSet()`. Call each of them in order.
1. The list of annotations to call `onEnter` on is `thisAnnotations.toSet() - prevAnnotations.toSet()`. Call each of them in reversed order.
1. The list of annotations to call `onHover` on is `thisAnnotations`. Call each of them in reversed order.

**Comment by dkwingsmt** [comment]
+cc @gspencergoog @CarlosZ
@mehmetf Does it look like compatible with the way Web works?
Also maybe interested @goderbauer

**Comment by mehmetf** [comment]
I think you meant @ferhatb :-)

**Comment by dkwingsmt** [comment]
@mehmetf Oops :) My apology

**Comment by gspencergoog** [comment]
This seems pretty reasonable to me.

**Comment by goderbauer** [comment]
Sounds good.

**Comment by ferhatb** [comment]
@dkwingsmt Fine for web as well.

**Comment by dkwingsmt** [comment]
This has been implemented in #42031
