### ISSUE TITLE
最新版本运行异常

### ISSUE THREAD

**Issue by litaoyuan** [flutter/flutter#41436]
litaoyuandeMacBook-Air:lty_study_flutter litaoyuan$ flutter run
 
Launching lib/main.dart on MX5 in debug mode...
Initializing gradle...                                              3.3s
Resolving dependencies...                                          43.1s
                                                                        
Compiler message:                                                       
../../flutter/packages/flutter/lib/src/widgets/framework.dart:3675:12: Error: The getter 'r_debugLifecycleState' isn't defined for the class 'Element'.
 - 'Element' is from 'package:flutter/src/widgets/framework.dart' ('../../flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'r_debugLifecycleState'.
    assert(r_debugLifecycleState != _ElementLifecycle.defunct);         
           ^^^^^^^^^^^^^^^^^^^^^                                        
Exception: Errors during snapshot creation: null                        
#0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart:218:7)
<asynchronous suspension>                                               
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:510:27)
<asynchronous suspension>                                               
#2      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:476:35)
#3      new Future.sync (dart:async/future.dart:224:31)                 
#4      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:476:21)
<asynchronous suspension>                                               
<asynchronous suspension>                                               
#6      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:414:36)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#8      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:395:28)
#9      buildWithAssemble (package:flutter_tools/src/bundle.dart:167:48)
#10     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#11     buildWithAssemble (package:flutter_tools/src/bundle.dart:146:31)
#12     BundleBuilder.build (package:flutter_tools/src/bundle.dart:85:13)
#13     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#14     BundleBuilder.build (package:flutter_tools/src/bundle.dart:58:21)
#15     BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:119:25)
#16     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#17     BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:90:42)
#18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:535:18)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)                    
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)             
#22     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:522:5)   
#26     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#27     _rootRun (dart:async/zone.dart:1124:13)                         
#28     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#29     _CustomZone.runGuarded (dart:async/zone.dart:923:7)             
#30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)       
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)   
#33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
                                                                        
Failed to build bundle.                                                 
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/litaoyuan/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 749
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildDebugArm64'.         
> Process 'command '/Users/litaoyuan/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 22s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        23.9s
Gradle task assembleDebug failed with exit code 1
litaoyuandeMacBook-Air:lty_study_flutter litaoyuan$ flutter --version
Flutter 1.10.7-pre.23 • channel master • https://github.com/flutter/flutter.git
Framework • revision e0247442d0 (19 hours ago) • 2019-09-26 02:49:41 -0400
Engine • revision 3713ecf107
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 c6a14f4459)

**Comment by stuartmorgan** [comment]
> Framework • revision e024744 (19 hours ago) • 2019-09-26 02:49:41 -0400

From that exact version:
https://github.com/flutter/flutter/blob/e0247442d019516a534b66b4f5a8c47c1e2c0a3d/packages/flutter/lib/src/widgets/framework.dart#L3675
There's no `r`. You appear to have a local modification to that file.

**Comment by litaoyuan** [comment]
Thank you. Solved. Closed issues
