### ISSUE TITLE
[web]: flutter run freezes after building with a syntax error

### ISSUE THREAD

**Issue by davidcavazos** [flutter/flutter#41433]
In VS Code 1.38 with the Flutter plugin installed.

When folllowing [Write your first app - Step 4: Creating an infinite scrolling ListView](https://flutter.dev/docs/get-started/codelab#step-4-create-an-infinite-scrolling-listview), I saved at step 2 after adding `_buildSuggestions` and ran `flutter run -d chrome`. That gave me an (expected) error that `_buildRow` is not defined:

```
> flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Building application for the web...                                10.8s
Error compiling dartdevc module:flutter_hello|lib/main.ddc.js           

packages/flutter_hello/main.dart:43:18: Error: The method '_buildRow' isn't defined for the class 'RandomWordsState'.
 - 'RandomWordsState' is from 'package:flutter_hello/main.dart' ('packages/flutter_hello/main.dart').
Try correcting the name to the name of an existing method, or defining a method named '_buildRow'.
          return _buildRow(_suggestions[index]);
                 ^^^^^^^^^


                                                                        
                                                                        
AssetNotFoundException: flutter_hello|lib/main.ddc.js                   
Failed after 279ms                                                      
Attempting to connect to browser instance..                             
(This is taking an unexpectedly long time.)       ⣯
```

Then, I add the `_buildRow` method described in step 3, save and nothing happens; it's still doing the loading animation. Pressing `R` also does nothing, so I have to kill the process and run `flutter run -d chrome` again. After that, the app works like expected.

**Comment by jonahwilliams** [comment]
Had to revert PR, will reland shortly
