### ISSUE TITLE
Sizing to accommodate keyboard when keyboard is closed.

### ISSUE THREAD

**Issue by gskinner** [flutter/flutter#41438]
## Steps to Reproduce
Tested app via TestFlight on new iPhone 11 Pro running iOS 13.1.

On startup, the app was sized as though the keyboard was open, even though it was not, and no text field was focused. Issue persisted through:

1. Tapping a text field, inputting a value and closing the keyboard.
2. Proceeding to other views, including ones with no inputs.
3. Quitting and restarting the app.
4. Uninstalling and reinstalling the app.
5. Overwriting the TestFlight install with a debug build.

![IMG_1C833DB2D3B3-1](https://user-images.githubusercontent.com/157128/65735658-66259a00-e095-11e9-9ae6-83d3c7c17755.jpeg)

Strangely, the fifth or sixth time the sizing returned to normal. I _believe_ it was after closing the keyboard, though I'm not totally certain.

It now appears to be resolved (I haven't been able to reproduce since), but I thought I should report it in case it's the symptom of a larger issue with the new phones or the new OS.

Have never seen this issue previously (or since) with plenty of testing on other devices.

## Logs

Unable to repro now, so can't produce logs relevant to the issue.

[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-CA)
    • Flutter version 1.9.1+hotfix.2 at /Users/grant/Documents/Flutter/_SDKs/stable
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/grant/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPad Pro (12.9-inch) (3rd generation) • 5E9BCAA9-2766-4007-A202-5EF6C3D0F5C3 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

**Comment by escamoteur** [comment]
@tvolkert what are we doing with reports like this?

**Comment by tvolkert** [comment]
@gskinner can you delete code from you app that's unrelated to reproducing this bug, until you get to a minimal reproducible case, then post the same code that reproduces this issue?

Thanks!

**Comment by tvolkert** [comment]
Closing, as there's no actionable info here.
