### ISSUE TITLE
Slider demo: Bottom line flashes a few pixels when finger hits line

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4145]
Go into Gallery, Sliders. Place finger on bottom line. Notice how the little black markers on the line (only a few pixels wide) flash from white to black.

You can tap the bottom line over and over to see the effect. It happens on every tap.

**Comment by abarth** [comment]
Odd.  I must have messed up the beginning of the interpolation.

**Comment by sethladd** [comment]
Super subtle. Our designers have good eyes :)  (noticed during a review)
