### ISSUE TITLE
I need to capture picture of video

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#41458]
I need to capture the current picture of video . or can i capture picture of one widget  no matter what type of it child is ( webview, video, or something else)

**Comment by escamoteur** [comment]
Please ask questions like this on stackoverflow as we can't give individual support here.

**Comment by wanjm** [comment]
I think this is a new futrue instead of one question;

**Comment by escamoteur** [comment]
Ah, you mean capturing a single picture out of a video.
You can save the content of a Widget using a RepaintBoundery see “Export your widget to image with flutter” von Parth Jansari https://link.medium.com/U4DoB9NAv0
But I m not sure if it will work with a VideoView. 
Perhaps give it a try. If not we reopen this here. 
If it works it would be awesome if you could post a self answered question on stackoverflow

**Comment by VladyslavBondarenko** [comment]
Hi @wanjm 
given the last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by wanjm** [comment]
RepaintBoundery doesn't work for video_player
