### ISSUE TITLE
webview_flutter scroller doesn't work！my flutter project mix web and many picture.

### ISSUE THREAD

**Issue by v7lin** [flutter/flutter#41457]
## Logs

```
```

```
```

**Comment by escamoteur** [comment]
Sorry, with so view information we can't help you.
What do you mean with doesn't work?
Does this happen on Android and iOS?
A short video of the problem can be helpful.
Please also add the output of flutter doctor here.

**Comment by v7lin** [comment]
flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G87, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.1.4)
[!] VS Code (version 1.38.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)
```

**Comment by v7lin** [comment]
webview_flutter example: https://github.com/v7lin/bug-report/blob/master/1AFB043A46C3D53DEF2F541AAB26DE6A.mp4
my flutter project: https://github.com/v7lin/bug-report/blob/master/CBEED9C4C3DC2ADFB6C74405A90D2F54.mp4

**Comment by v7lin** [comment]
```
VM
name	vm@ws://127.0.0.1:63962/Hpb87GCxav4=/ws
version	2.5.0 (Fri Sep 6 20:10:36 2019 +0200) on "android_arm64"
embedder	Flutter
started at	2019-09-29 11:45:22.413
uptime	0:21:53.630000
refreshed at	2019-09-29 12:07:16.045
pid	10234
peak memory	552.8MB
current memory	509.6MB
native zone memory	0B
native heap memory	unavailable
native heap allocation count	unavailable
```

**Comment by v7lin** [comment]
DevTools -> Memory -> Snapshot
```
Size | Count | Accumulator | Class
-- | -- | -- | --
27,511k | 79 | 159 | Image
3,469k | 20,187 | 44,568 | DiagnosticsProperty
1,870k | 10,883 | 24,368 | ObjectFlagProperty
1,156k | 6,167 | 13,381 | FlagProperty
1,122k | 6,528 | 15,088 | EnumProperty
1,095k | 371 | 28,376 | EngineLayer
954k | 79 | 158 | Codec
871k | 2,231 | 11,658 | SemanticsConfiguration
746k | 4,343 | 9,554 | DoubleProperty
435k | 2,533 | 5,820 | ColorProperty
401k | 204 | 623 | Paragraph
395k | 2,534 | 7,912 | SingleChildRenderObjectElement
288k | 3,692 | 8,590 | DiagnosticableTreeNode
273k | 1,591 | 3,591 | StringProperty
263k | 1,873 | 5,634 | StatelessElement


```

**Comment by escamoteur** [comment]
Could you please elaborate what exactly doesn't work?

**Comment by v7lin** [comment]
> Could you please elaborate what exactly doesn't work?

webview scroller is disable

**Comment by escamoteur** [comment]
You mean you can't scroll the content of the web_view at all?
Have you tried different versions of web_view?

**Comment by escamoteur** [comment]
Does this happen on iOS and Android?

**Comment by v7lin** [comment]
i have try 
```
webview_flutter: ^0.3.14+1
```
it works well in webview_flutter example, but in my flutter project, the scrollbar is disable.

**Comment by v7lin** [comment]
> Does this happen on iOS and Android?

Android

**Comment by v7lin** [comment]
I think it's related hybrid development. webview_flutter just providers a sample example.

**Comment by cmengler** [comment]
@v7lin This may be related to the gesture arena re-work since 1.7.8 that affects `PlatformViews` (e.g. WebView) in scrollable widgets -- more details and workaround can be found here if this helps.

- https://stackoverflow.com/questions/57069716/scrolling-priority-when-combining-pageview-with-webview-in-flutter-1-7-8/57150906#57150906
- https://github.com/flutter/flutter/issues/35394
- https://github.com/flutter/flutter/issues/35394

**Comment by v7lin** [comment]
我仅使用Webview，并没有使用 PageView

--- translate by fanyi.baidu.com ---

I only use WebView, not pageview

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/41592

**Comment by iapicca** [comment]
Hi @v7lin 
are you still experiencing the issue?
Thank you
https://github.com/flutter/flutter/issues/29555#issuecomment-573722051

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
