### ISSUE TITLE
Is there away to access an asset from Android's gradle file?

### ISSUE THREAD

**Issue by moga111** [flutter/flutter#41451]
We have a config json file that is located under assets. Under iOS "AppDelegate.swift" I was able to locate and load the json as explained in the official flutter documentation. The Android solution though is not useful if I want to read the json during the build using gradle, not from a java file.

Basically `assets/config.json` contains keys that are build type specific, and I can't determine the path of this resource file to load it from gradle. Is there anyway to determine the full path of this  `assets/config.json`?

Thank you!

**Comment by escamoteur** [comment]
Please ask questions like this on stackoverflow as we can't give individual support here.
