### ISSUE TITLE
Flutter downloads (and uses?) old Android SDK build tools

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#41462]
If only latest Android SDK build tools are installed (currently 29.0.2), Flutter will force the download of an old version (28.0.3) to run/build an app (both debug and release modes).

[![Screenshot](https://i.imgur.com/FZxeNYz.png)](https://imgur.com/a/dC9DfCL)

## Steps to Reproduce

1. Remove all build tools versions
2. Install only latest build tools version (currently, 29.0.2)
3. `flutter run`

## Flutter Doctor

```
[√] Flutter (Channel master, v1.10.7-pre.53, on Microsoft Windows [VersiÃ³n 10.0.18362.356], locale es-ES)
    • Flutter version 1.10.7-pre.53 at C:\src\flutter
    • Framework revision f11c34109c (77 minutes ago), 2019-09-27 10:46:45 +0200
    • Engine revision 18bc0b2596
    • Dart version 2.6.0 (build 2.6.0-dev.3.0 403c4af720)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Cristian\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Pixel 3 XL • 89PY09NNV • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by escamoteur** [comment]
Is this a problem for you?
@jonahwilliams is there a reason for this?

**Comment by Zazo032** [comment]
Not really, just noticed it while freeing space on my computer, because as I specified SDK version 29, I expected Flutter to use it to build the app, but instead it redownloaded version 28. Now that version 29 is out and stable, I think Flutter should target it.

**Comment by escamoteur** [comment]
Thanks for bringing this to our attention

**Comment by budioktaviyan** [comment]
I have same problem. I only need build tools `29.0.2` instead of using `28.0.3`
So, any update about this issue ? when the flutter team target this build tools to `29.0.2`

**Comment by escamoteur** [comment]
@jonahwilliams do you know anything about the plan on this?

**Comment by solokingjec** [comment]
This is not a very good thing. I use a machine with small but efficient ssd storage so I deleted old android platforms so save space. When I started building, flutter downloaded the platforms again...

**Comment by MaikuB** [comment]
Appear to have come across this problem as well. Had a plugin using Cirrus CI to build the example apps as part of the CI process I've setup. The apps and plugin have the compile and target SDK version set to 29. Builds end up failing with the same error.

**Comment by AttSee** [comment]
I have  same problem.

**Comment by vincentderidder** [comment]
Same issue here. Any news on this?

**Comment by jonahwilliams** [comment]
Gradle will download whatever build tools it requires - Flutter does not request these. I can't really provide any insight into why they are being downloaded, but it is possible some transitive dependency requires them for some reason.

**Comment by fkorotkov** [comment]
@joaoatgoogle might be because of https://github.com/flutter/flutter/blob/4d404da6dfd70a029489ed09a84d05c72d8c3387/packages/flutter_tools/templates/plugin/android-java.tmpl/build.gradle.tmpl#L25

**Comment by jonahwilliams** [comment]
Thats a template file though, it is only meant to be a default. If plugins are compiling against 28, you'll need to download that tool regardless

**Comment by andy-g** [comment]
@jonahwilliams is there any easy way to find out which plugins are targeting which sdk? I'd like to determine which plugin is forcing the download of the old android sdk as it's slowing down my CI build, and I may be able to bump that plugin version etc.

**Comment by murthyghadiyaram** [comment]
Installed the stable version of flutter today. I'm still facing this issue

**Comment by bartekpacia** [comment]
For future readers: see [my comment in a different issue](https://github.com/flutter/flutter/issues/63533#issuecomment-2027851231)
