### ISSUE TITLE
DropDownMenu Not working 

### ISSUE THREAD

**Issue by Fa-d** [flutter/flutter#41467]
Launching lib\main.dart on SM J400F in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
D/SurfaceView(13739): surfaceChanged (720,1280) 1 #8 io.flutter.view.FlutterView{a2dd350 VFE...... ......ID 0,0-720,1280}
I/Choreographer(13739): Skipped 60 frames!  The application may be doing too much work on its main thread.
D/ViewRootImpl@5a2e54d[MainActivity](13739): Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x3 surface={true 3463778304} changed=false
I/OpenGLRenderer(13739): Davey! duration=1105ms; Flags=1, IntendedVsync=159104021867666, Vsync=159105021867626, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=159105036585452, AnimationStart=159105036692913, PerformTraversalsStart=159105036706029, DrawStart=159105054829606, SyncQueued=159105062495759, SyncStart=159105062752298, IssueDrawCommandsStart=159105063469490, SwapBuffers=159105126071221, FrameCompleted=159105128030029, DequeueBufferDuration=3745000, QueueBufferDuration=845000, 
Syncing files to device SM J400F...
D/ViewRootImpl@5a2e54d[MainActivity](13739): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(13739): prepareNavigationBarInfo() DecorView@267487f[MainActivity]
D/InputMethodManager(13739): getNavigationBarColor() -855310
D/InputMethodManager(13739): prepareNavigationBarInfo() DecorView@267487f[MainActivity]
D/InputMethodManager(13739): getNavigationBarColor() -855310
V/InputMethodManager(13739): Starting input: tba=com.faddy.go.alert_test ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(13739): startInputInner - Id : 0
I/InputMethodManager(13739): startInputInner - mService.startInputOrWindowGainedFocus
D/ViewRootImpl@5a2e54d[MainActivity](13739): MSG_RESIZED_REPORT: frame=[0,0][720,1280] ci=[0,41][0,0] vi=[0,41][0,0] or=1
D/InputTransport(13739): Input channel constructed: fd=90
D/InputMethodManager(13739): prepareNavigationBarInfo() DecorView@267487f[MainActivity]
D/InputMethodManager(13739): getNavigationBarColor() -855310
V/InputMethodManager(13739): Starting input: tba=com.faddy.go.alert_test ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(13739): startInputInner - Id : 0
I/flutter (13739): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13739): The following assertion was thrown building MyApp(dirty, state: _MyAppState#d2f77):
I/flutter (13739): 'package:flutter/src/material/dropdown.dart': Failed assertion: line 620 pos 15: 'items == null ||
I/flutter (13739): items.isEmpty || value == null || items.where((DropdownMenuItem<T> item) => item.value ==
I/flutter (13739): value).length == 1': is not true.
I/flutter (13739): 
I/flutter (13739): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (13739): more information in this error message to help you determine and fix the underlying cause.
I/flutter (13739): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (13739):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (13739): 
I/flutter (13739): When the exception was thrown, this was the stack:
I/flutter (13739): #2      new DropdownButton (package:flutter/src/material/dropdown.dart:620:15)
I/flutter (13739): #3      _MyAppState.build (package:alert_test/main.dart:43:20)
I/flutter (13739): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
I/flutter (13739): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
I/flutter (13739): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (13739): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (13739): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
I/flutter (13739): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (13739): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (13739): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (13739): #12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:998:16)
I/flutter (13739): #13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:969:5)
I/flutter (13739): #14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:915:17)
I/flutter (13739): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2328:19)
I/flutter (13739): #16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:914:13)
I/flutter (13739): #17     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:795:7)
I/flutter (13739): #18     runApp (package:flutter/src/widgets/binding.dart:845:7)
I/flutter (13739): #19     main (package:alert_test/main.dart:3:16)
I/flutter (13739): #20     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229:25)
I/flutter (13739): #25     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221:5)
I/flutter (13739): #26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
I/flutter (13739): #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter (13739): (elided 6 frames from class _AssertionError and package dart:async)
I/flutter (13739): 
I/flutter (13739): ════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building MyApp(dirty, state: _MyAppState#d2f77):
'package:flutter/src/material/dropdown.dart': Failed assertion: line 620 pos 15: 'items == null || items.isEmpty || value == null || items.where((DropdownMenuItem<T> item) => item.value == value).length == 1': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      new DropdownButton (package:flutter/src/material/dropdown.dart:620:15)
#3      _MyAppState.build (package:alert_test/main.dart:43:20)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 0
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 1
D/ViewRootImpl@5a2e54d[MainActivity](13739): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(13739): prepareNavigationBarInfo() DecorView@267487f[MainActivity]
D/InputMethodManager(13739): getNavigationBarColor() -855310
D/ViewRootImpl@5a2e54d[MainActivity](13739): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(13739): prepareNavigationBarInfo() DecorView@267487f[MainActivity]
D/InputMethodManager(13739): getNavigationBarColor() -855310
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 0
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 1
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 0
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 1
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 0
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 1
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 0
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 1
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 0
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 1
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 0
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 1
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 0
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 1
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 0
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 1
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 0
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 1
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 0
D/ViewRootImpl@5a2e54d[MainActivity](13739): ViewPostIme pointer 1
D/InputMethodManager(13739): prepareNavigationBarInfo() DecorView@267487f[MainActivity]
D/InputMethodManager(13739): getNavigationBarColor() -855310
V/InputMethodManager(13739): Starting input: tba=com.faddy.go.alert_test ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(13739): startInputInner - Id : 0
I/InputMethodManager(13739): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(13739): Input channel constructed: fd=93
D/InputTransport(13739): Input channel destroyed: fd=90
D/ViewRootImpl@5a2e54d[MainActivity](13739): stopped(true) old=false
D/SurfaceView(13739): windowStopped(true) false io.flutter.view.FlutterView{a2dd350 VFE...... ........ 0,0-720,1280} of ViewRootImpl@5a2e54d[MainActivity]
D/SurfaceView(13739): show() Surface(name=SurfaceView - com.faddy.go.alert_test/com.faddy.go.alert_test.MainActivity@a2dd350@0[13739])/@0xbc58949 io.flutter.view.FlutterView{a2dd350 VFE...... ........ 0,0-720,1280}
D/SurfaceView(13739): surfaceDestroyed callback.size 1 #1 io.flutter.view.FlutterView{a2dd350 VFE...... ........ 0,0-720,1280}
W/libEGL  (13739): EGLNativeWindowType 0xce699808 disconnect failed
D/SurfaceView(13739): destroy() Surface(name=SurfaceView - com.faddy.go.alert_test/com.faddy.go.alert_test.MainActivity@a2dd350@0[13739])/@0xbc58949 io.flutter.view.FlutterView{a2dd350 VFE...... ........ 0,0-720,1280}
D/ViewRootImpl@5a2e54d[MainActivity](13739): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(13739): prepareNavigationBarInfo() DecorView@267487f[MainActivity]
D/InputMethodManager(13739): getNavigationBarColor() -855310
D/SurfaceView(13739): onWindowVisibilityChanged(8) false io.flutter.view.FlutterView{a2dd350 VFE...... ........ 0,0-720,1280} of ViewRootImpl@5a2e54d[MainActivity]
W/libEGL  (13739): EGLNativeWindowType 0xce751008 disconnect failed
D/OpenGLRenderer(13739): eglDestroySurface = 0xe4a06420, 0xce751000
D/ViewRootImpl@5a2e54d[MainActivity](13739): Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x5 surface={false 0} changed=false

**Comment by escamoteur** [comment]
Hi, please ask such questions on stackoverflow. We can't give individual support here.

Looking at the failed exception my guess would be that the value you pass to value is not a member of the items collection.
