### ISSUE TITLE
any option for bitmap in flutter 

### ISSUE THREAD

**Issue by Shubham-8197** [flutter/flutter#41460]
hello, guys, I want to create the bitmap in flutter but I think currently there is no method like bitmap in the flutter. 
Here is my android code if anyone knows how to create it with flutter then please help mi.

`public static Bitmap RotateBitmap(Bitmap source, float angle) {
        Matrix matrix = new Matrix();
        matrix.postRotate(angle);

        return Bitmap.createBitmap(source, 0, 0, source.getWidth(), source.getHeight(), matrix, true);
    }`
**this is method for Rotate created bitmap**

  getFrameSwatchUrl = "https://www.arttoframe.com/products/frames/SwatchSmall/" + framecode + "/" + framewidth + ".jpg?is_https_site=1"; 
_this is a network image_

`URL url = new URL(getFrameSwatchUrl);
bitmap2 = BitmapFactory.decodeStream((InputStream) url.getContent( ));  //SetData from URL
rotated_bitmap_right = RotateBitmap(bitmap2, 90);   //this is rotatedBitmap`

Paint wallpaint = new Paint();

 `Bitmap bitTop = Bitmap.createBitmap((int) frame_area_width, (int)frame_area_height,Bitmap.Config.ALPHA_8);
  Shader shader_top = new BitmapShader(rotated_bitmap_180, Shader.TileMode.REPEAT, Shader.TileMode.REPEAT);
wallpaint.setShader(shader_top);
Canvas canvas_top = new Canvas(bitTop);`

`canvas_top.drawPath(wallpath1, wallpaint);
 canvas.drawBitmap(bitTop, 0, 0, wallpaint);`
this is my some logic code in android and I'll run perfectly but now I want to do this in flutter please help mi for creating that.

**Comment by escamoteur** [comment]
Please ask questions like this on stackoverflow. We can't give individual support here.

**Comment by escamoteur** [comment]
Check out Dart:ui.Image
