### ISSUE TITLE
[google_maps_flutter] Support for containsLocation() - Check if coordinate is within a Polygon

### ISSUE THREAD

**Issue by joknjokn** [flutter/flutter#41466]
Hi

I have a set of polygons covering different areas of a GoogleMap.

How can I check if a given coordinate is within a polygon?

I believe some GoogleMaps api's have a containsLocation() to do this, but I can't find it for google_maps_flutter.

Is it available? Will it be implemented?

Or does someone have an alternative way of doing this in Flutter?

Thanks

**Comment by escamoteur** [comment]
Hi, if the native Google maps api contains this function please make a feature request issue to add it to the Flutter package.
Is best to ask questions like this on stackoverflow as we can't give individual support here

**Comment by KohlsAdrian** [comment]
I have created a package from the original Google Maps Utils for Android of the most used 3 classes, MathUtil, SphericalUtil and PolyUtil

https://github.com/KohlsAdrian/google_maps_utils/issues/1

I am trying to find the solution for this issue, can't fix the original code to dart, as dart related compiler issue (double data type calculation issue, maybe)

If someone could help me, my package is still the best progress for implementing google maps utils for Flutter
