### ISSUE TITLE
Gallery, Slider: Zero-end of continuous slider should be an empty circle

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4146]
The zero-end of the slider looks like it should be an empty circle.

https://www.google.com/design/spec/components/sliders.html#sliders-continuous-slider

From the spec:

![components_sliders_continuous1](https://cloud.githubusercontent.com/assets/5479/15488381/9af3e122-210a-11e6-8c63-be79efad76c2.png)

From the app:

![screenshot_20160523-172042](https://cloud.githubusercontent.com/assets/5479/15488402/c3237d1a-210a-11e6-9e10-fa1d16ceaf50.png)

**Comment by abarth** [comment]
Is this from a design review?  I didn't do that because none of the other material implementations I found did that.

**Comment by sethladd** [comment]
Yup, from a review with material designers.
