### ISSUE TITLE
expose addApplicationDelegate for macOS

### ISSUE THREAD

**Issue by lesnitsky** [flutter/flutter#41471]
[addApplicationDelegate](https://github.com/flutter/engine/blob/9c00c26c8fe85915d9cbeb88560678fc44fe7752/shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h#L296) is available in iOS framework, but it is missing in macOS

**Comment by stuartmorgan** [comment]
This isn't there only because it hasn't been wired up. This should be a fairly straightforward change if someone wants to add it soon (there's a lot of higher-priority work for desktop at the moment, so I'm not sure when we'll get to this).

**Comment by cbenhagen** [comment]
This is the last puzzle piece needed to finish the `firebase_messaging` plugin for macOS. @lesnitsky did you wire this up yourself in your project? I am a bit scared of hacking this into the engine but will do with some guidance from @stuartmorgan unless there is someone else already working on this.

**Comment by cbenhagen** [comment]
I was a bit quick, `firebase_messaging` would also need[ lifecycle delegation](https://github.com/flutter/flutter/issues/30735).

**Comment by lesnitsky** [comment]
@cbenhagen no, never had a chance and left the AppDelegate code up to plugin users to add

**Comment by stuartmorgan** [comment]
@cbenhagen What guidance are you looking for specifically? The macOS plugin API is heavily modeled on the iOS API (including sharing a non-trivial amount of it directly), so there's an existing example to work from.

**Comment by MaikuB** [comment]
> This is the last puzzle piece needed to finish the firebase_messaging plugin for macOS

A note that on iOS that here's related issue I raised a while back that got resolved to allow the multiple plugins to receive [`UNUserNotificationCenterDelegate`](https://github.com/flutter/flutter/issues/22099) calls. Similar work could be done on macOS and I believe it's also missing as well. Let me know if I should file a separate issue on this

**Comment by Salakar** [comment]
Small addition to this one, `publish` is also missing on MacOS implementation of `FlutterPluginRegistrar`, e.g. `[registrar publish:pluginInstance];`, without this [`detachFromEngineForRegistrar:`](https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h#L228-L238) is supposedly not called unless the plugin instance has been published.

iOS implementation of `publish`: https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Headers/FlutterPlugin.h#L323-L335

**Comment by cbenhagen** [comment]
@Salakar Can we change the description and title to something like "Merge FlutterPluginMacOS.h and FlutterPluginRegistrarMacOS.h with the iOS FlutterPlugin.h, sharing all but the platform-specific methods"  to match the comments in the header files?

Or should a new issue be created for this?

**Comment by stuartmorgan** [comment]
Merging the heaters is an implementation detail that should be largely irrelevant to anyone but people working on the engine. Wiring up application state delegation in macOS will be platform specific since the application classes aren't the same.

**Comment by cbenhagen** [comment]
Oh, I thought the intention was to not only merge the headers but also the implementations where possible. But I might have overestimated how much code could be shared between the two platforms.

**Comment by csells** [comment]
This issue is blocking some auth work we're doing for desktop in FlutterFire

**Comment by amorenew** [comment]
@stuartmorgan Any update here? it blocks google sign in for macos

**Comment by AuriDeimantasDev** [comment]
Any updates on this one?

**Comment by cybex-dev** [comment]
Any update on this?

**Comment by stuartmorgan** [comment]
It's now possible (on `master`) to register for [a subset of notifications](https://github.com/flutter/engine/blob/main/shell/platform/darwin/macos/framework/Headers/FlutterAppLifecycleDelegate.h#L5) (including core app lifecycle) via the new `addApplicationDelegate:` method on `FlutterPluginRegistrar`. The PR linked just above will also add `openURLs:`. I'm going to close this as fixed when that lands, but please file issues (and/or send PRs; adding new methods now that the plumbing is in place should be very straightforward) for any delegate methods that you need that aren't present yet.
