### ISSUE TITLE
RawKeyboardListener documentation inconsistency for focusNode field

### ISSUE THREAD

**Issue by bleroux** [flutter/flutter#41475]
On RawKeyboardListener document page :
https://api.flutter.dev/flutter/widgets/RawKeyboardListener-class.html
'**focusNode**' field is marked **@required** in the constructor and field documentation states the following :
'focusNode : An **optional** focus node to use as the focus node for this widget. [...]'.

Looking at 'raw_keyboard_listener.dart' commit history, this was introduced in last commit :

Last commit :
  /// {@macro flutter.widgets.Focus.focusNode}
  final FocusNode focusNode;

Previous code :
  /// Controls whether this widget has keyboard focus.
  final FocusNode focusNode;

**Comment by escamoteur** [comment]
Thanks for reporting
