### ISSUE TITLE
Gallery, Icons: show icons with approved Opacities (instead of slider)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4147]
Suggestion from design review: Instead of a slider, we can show icons at approved opacity levels:

From the spec (https://www.google.com/design/spec/style/icons.html) :

![screen shot 2016-05-23 at 5 37 16 pm](https://cloud.githubusercontent.com/assets/5479/15488617/06f6ec00-210d-11e6-8c76-8fe523f28879.png)

The design reviewer wanted to help our developers by not letting them think they can use any opacity with these icons.

**Comment by eseidelGoogle** [comment]
@HansMuller says we can punt this from our first release.  The screen in question is:
![flutter_01](https://cloud.githubusercontent.com/assets/11857803/16124693/d4c6c0d4-33a4-11e6-9765-5940ebc7efd0.png)
We could just make that a determinate slider.

https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/icons_demo.dart#L136
