### ISSUE TITLE
Cocoon agent needs to check attached iOS device in a new way

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#41488]
Currently Cocoon agent relies on `idevice_id` that found in $PATH env var to check an iOS device is connected.

As Flutter ships iOS tools with it now, we'd better stop installing the iOS tools manually, and let Cocoon agent checks attached iOS device in a new way.

Option 1: Call `flutter devices`.
Option 2: Utilize the following wrapper script from @christopherfujino:
```
#!/bin/bash
# run-ios-dependency.sh

names=(libimobiledevice libplist ios-deploy ideviceinstaller openssl usbmuxd)
FLUTTER_PATH="$HOME/git/flutter"
LIB_PATH=''
for name in ${names[@]}; do
  LIB_PATH="$FLUTTER_PATH/bin/cache/artifacts/$name:$LIB_PATH"
done

DYLD_LIBRARY_PATH=$LIB_PATH "$@"
```

**Comment by godofredoc** [comment]
@digiter any plans to fix this bug?

**Comment by christopherfujino** [comment]
Here's an example of using option 1 in the devicelab https://github.com/flutter/flutter/pull/59907

**Comment by digiter** [comment]
Not sure about the best way, LUCI still uses `idevice_id` in bot_config.py to populate dimensions for iPhones.

**Comment by christopherfujino** [comment]
> Not sure about the best way, LUCI still uses `idevice_id` in bot_config.py to populate dimensions for iPhone testbeds.

I highly recommend calling `flutter devices --machine` in case future changes to either the flutter tool, ios, or libimobiledevice regress this behavior.

**Comment by godofredoc** [comment]
Obsolete now that devicelab is migrated to luci.
