### ISSUE TITLE
iOS AOT builds are seg faulting on latest dart roll

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#41484]
Devicelab logs:

```
stdout: Xcode's output:
stdout: ↳
stdout:     Building AOT snapshot in release mode (ios-release)...          
stdout: 
stdout: 
stdout:     ===== CRASH =====
stdout: 
stdout:     si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x10db00000
stdout: 
stdout:     Dart snapshot generator failed with exit code -6
stdout: 
stdout:     Building App.framework for arm64...
stdout:     Building AOT snapshot in release mode (ios-release)...             24.4s
stdout:     Built to build/aot/.
stdout:     Snapshotting (DarwinArch.armv7) exited with non-zero exit code: -6
stdout:     Snapshotting (DarwinArch.arm64) exited with non-zero exit code: 0
stdout:     cp: build/aot/App.framework: No such file or directory
stdout:     error: cannot parse the debug map for 'build/aot/App.framework/App': No such file or directory
stdout:     Failed to generate debug symbols (dSYM) file for build/aot/App.framework/App.
stdout:     note: Using new build systemnote: Planning buildnote: Constructing build description
stdout: 
2019-09-27
```

This was caused by the roll in https://github.com/flutter/flutter/pull/41455. I've turned off the autoroller in the meantime

**Comment by jonahwilliams** [comment]
cc @a-siva

**Comment by sjindel-google** [comment]
This looks related to a similar crash we are seeing on our CQ: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8901152311988080096/+/steps/test_results/0/logs/tests_that_began_failing__logs_/0

**Comment by sjindel-google** [comment]
https://github.com/dart-lang/sdk/issues/38617

**Comment by sjindel-google** [comment]
It was caused by https://dart-review.googlesource.com/c/sdk/+/118702, reverting in https://dart-review.googlesource.com/c/sdk/+/119149.

**Comment by christopherfujino** [comment]
I'm hitting this at ToT, past Jonah's engine revert https://cirrus-ci.com/task/6108200513830912?command=test_all#L29

**Comment by sjindel-google** [comment]
The source was https://dart-review.googlesource.com/c/sdk/+/118702 which I think was older than that roll?

**Comment by jonahwilliams** [comment]
This actually came in with https://github.com/flutter/engine/commit/ce6ab8ce25fa4d06c27a8043b7be2a970f133d21

**Comment by a-siva** [comment]
A new roll of Dart has landed into Flutter engine that has reverted https://dart-review.googlesource.com/c/sdk/+/118702

**Comment by goderbauer** [comment]
@a-siva based on your last comment: Can this be closed or the TODAY label be removed?

**Comment by jonahwilliams** [comment]
I've re-enabled the engine roller, we should wait until the affected bots are finished (but probably)

**Comment by jonahwilliams** [comment]
Latest dart rolled succeeded, closing
