### ISSUE TITLE
`flutter build apk` should default to --release

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4148]
If `build apk` is the front-end for how we expect command line flutter users to interact with `flutter` during the release process, it should probably default to --release and the fact that it also can build --debug as part of `flutter run` or other debug workflows then becomes a detail.

It's also possible that we should have a `flutter release` or some other front-end command for the publish process?  Thoughts @devoncarew

**Comment by devoncarew** [comment]
+1. It - and `flutter build aot` - should default to `--release`.
