### ISSUE TITLE
Missing assets in APK

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#41487]
Steps to repro:

1. edit pubspec.yaml
```yaml
flutter:
  assets:
    - icon/
```
2. Run `flutter build apk`
3. Add/Delete files in `icon/`
4.  Run `flutter build apk`
5. Result: None of the files changed in (3) are in the APK.

The issue is that the Flutter Gradle plugin invalidates the output of the `flutter build bundle` task if `pubspec.yaml` or any `.dart` file changed (In debug mode). In this case, the assets point to a directory.

The workaround is to run `flutter clean` or `./android/gradlew clean`.  Yet, one more reason why folks run `flutter clean`.

**Comment by zanderso** [comment]
@jonahwilliams to lump in with the issues that assemble should help with.

**Comment by jonahwilliams** [comment]
The updated build_bundle includes a depfile that should have all assets within it.

**Comment by jonahwilliams** [comment]
Closing as fixed by above
