### ISSUE TITLE
* Error running Gradle: ProcessException: Process "/***/android/gradlew" exited abnormally 

### ISSUE THREAD

**Issue by Gebrilo** [flutter/flutter#41492]
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}


def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "co.geboo.flash_chat"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0-alpha4'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha4'
    implementation 'androidx.multidex:multidex:2.0.0'
    implementation 'com.google.firebase:firebase-analytics:17.2.0'
}
apply plugin: 'com.google.gms.google-services'



```
----------------------------------------------------------------------------------------------------------
```
* Error running Gradle:
ProcessException: Process "C:\Users\abdo1\AndroidStudioProjects\flash-chat-flutter\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\abdo1\AndroidStudioProjects\flash-chat-flutter\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
  Command: C:\Users\abdo1\AndroidStudioProjects\flash-chat-flutter\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.
```
--------------------------------------------------------------
so its happen to me in any project when i open build.gradle file the GradleException cannot resolve 
![issues1](https://user-images.githubusercontent.com/47781710/65791486-1d87e280-e162-11e9-9ce2-ed1f20b9c47a.png)

**Comment by BondarenkoStas** [comment]
@Gebrilo Can you please try to add 
```
dependencies {
    classpath 'com.google.gms:google-services:4.2.0'
    // ...
}
```
to your build.gradle? As in https://developers.google.com/android/guides/google-services-plugin.
Also I think `classpath 'com.android.tools.build:gradle:3.2.1'` as in https://pub.dev/packages/firebase_crashlytics. I think the documentation for some of firebase plugins is missing the instruction.
(be sure to use google-services:4.2.0 as proposed in https://github.com/flutter/flutter/issues/38163#issuecomment-520429066).

**Comment by Gebrilo** [comment]
thank you ^_^  it all about google-services 
i change it to google-services:4.2.0 as you said and it work with me .

**Comment by kroikie** [comment]
@Gebrilo

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1034. Any further collaboration will be done there.

**Comment by Isonomic** [comment]
Hey guys I would like to show you how I fixed this without having to downgrade anything. It was actually upgrading packages that solved it. I mean I would like to have newer as opposed to older versions of everything. So here is how I fixed the error without dropping the gms services from 4.3.2 to 4.2.0. I will provide a screen shot of the error before, the success screen after and the the 3 things that need to be changed and "UPGRADED" not downgraded. So in Adroid/build.gradle, so project level build.gradle, not the app level, under dependancies upgrade to this......... classpath 'com.android.tools.build:gradle:3.5.0'  In the same project level build.gradle at the top under build scripts, upgrade Kotlin to this.......    ext.kotlin_version = '1.3.50'   Then under android/gradle/wrapper/gradle-wrapper.properties,  change only this line and keep the .zip, so just replace the number to this...............distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip     completely restart your app and Success!!! Upgrading over downgrading. Here are the before and after errors and the two files to fix the three upgrades

**Comment by Isonomic** [comment]
Here are the screen shots for the above mentioned fix
![Screenshot (129)](https://user-images.githubusercontent.com/37713396/69246444-f5b36a80-0b65-11ea-932a-ced2c37fc21a.png)
![Screenshot (130)](https://user-images.githubusercontent.com/37713396/69246445-f5b36a80-0b65-11ea-866b-35b9e784d052.png)
![Screenshot (131)](https://user-images.githubusercontent.com/37713396/69246446-f64c0100-0b65-11ea-82d2-449056b67205.png)
![Screenshot (128)](https://user-images.githubusercontent.com/37713396/69246447-f64c0100-0b65-11ea-8f7a-5361d9556564.png)

**Comment by OliveiraEmanoel** [comment]
Great!! It is working. Tks

**Comment by ruggero95** [comment]
> Hey guys I would like to show you how I fixed this without having to downgrade anything. It was actually upgrading packages that solved it. I mean I would like to have newer as opposed to older versions of everything. So here is how I fixed the error without dropping the gms services from 4.3.2 to 4.2.0. I will provide a screen shot of the error before, the success screen after and the the 3 things that need to be changed and "UPGRADED" not downgraded. First DO NOT downgrade from 4.3.2 to 4.2.0 like the other solutions say. Stay at 4.3.2. So in Adroid/build.gradle, so project level build.gradle, not the app level, under dependancies upgrade to this......... classpath 'com.android.tools.build:gradle:3.5.0' In the same project level build.gradle at the top under build scripts, upgrade Kotlin to this....... ext.kotlin_version = '1.3.50' Then under android/gradle/wrapper/gradle-wrapper.properties, change only this line and keep the .zip, so just replace the number to this...............distributionUrl=https://services.gradle.org/distributions/gradle-5.6.2-all.zip completely restart your app and Success!!! Upgrading over downgrading. Here are the before and after errors and the two files to fix the three upgrades

Man you are the best! Works like a charm! Thanks

**Comment by MisterioRee** [comment]
![image](https://user-images.githubusercontent.com/18234947/69314659-1fe05780-0c4e-11ea-9332-95e4665ac0e5.png)


![image](https://user-images.githubusercontent.com/18234947/69314693-3c7c8f80-0c4e-11ea-90b1-73a888e87eaf.png)

-------------------------------------------------------------------

**It's Working perfect:**
[File Name] --> Android/build.gradle
`buildscript {
    ext.kotlin_version = '1.2.71'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.2.0'
    }
}`

[File Name] Android/gradle/wrapper/gradle-wrapper.properties

#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip

**Comment by kiimpg** [comment]
> 
> 
> Here are the screen shots for the above mentioned fix
> ![Screenshot (129)](https://user-images.githubusercontent.com/37713396/69246444-f5b36a80-0b65-11ea-932a-ced2c37fc21a.png)
> ![Screenshot (130)](https://user-images.githubusercontent.com/37713396/69246445-f5b36a80-0b65-11ea-866b-35b9e784d052.png)
> ![Screenshot (131)](https://user-images.githubusercontent.com/37713396/69246446-f64c0100-0b65-11ea-82d2-449056b67205.png)
> ![Screenshot (128)](https://user-images.githubusercontent.com/37713396/69246447-f64c0100-0b65-11ea-8f7a-5361d9556564.png)

Please use this  solution to upgate the packages. It work perfectly

**Comment by harshitlakhani777** [comment]
> @Gebrilo Can you please try to add
> 
> ```
> dependencies {
>     classpath 'com.google.gms:google-services:4.2.0'
>     // ...
> }
> ```
> 
> to your build.gradle? As in https://developers.google.com/android/guides/google-services-plugin.
> Also I think `classpath 'com.android.tools.build:gradle:3.2.1'` as in https://pub.dev/packages/firebase_crashlytics. I think the documentation for some of firebase plugins is missing the instruction.
> (be sure to use google-services:4.2.0 as proposed in [#38163 (comment)](https://github.com/flutter/flutter/issues/38163#issuecomment-520429066)).



> @Gebrilo Can you please try to add
> 
> ```
> dependencies {
>     classpath 'com.google.gms:google-services:4.2.0'
>     // ...
> }
> ```
> 
> to your build.gradle? As in https://developers.google.com/android/guides/google-services-plugin.
> Also I think `classpath 'com.android.tools.build:gradle:3.2.1'` as in https://pub.dev/packages/firebase_crashlytics. I think the documentation for some of firebase plugins is missing the instruction.
> (be sure to use google-services:4.2.0 as proposed in [#38163 (comment)](https://github.com/flutter/flutter/issues/38163#issuecomment-520429066)).

Thank You! it worked

**Comment by IT-zakriabilal** [comment]
> Hey guys I would like to show you how I fixed this without having to downgrade anything. It was actually upgrading packages that solved it. I mean I would like to have newer as opposed to older versions of everything. So here is how I fixed the error without dropping the gms services from 4.3.2 to 4.2.0. I will provide a screen shot of the error before, the success screen after and the the 3 things that need to be changed and "UPGRADED" not downgraded. First DO NOT downgrade from 4.3.2 to 4.2.0 like the other solutions say. Stay at 4.3.2. So in Adroid/build.gradle, so project level build.gradle, not the app level, under dependancies upgrade to this......... classpath 'com.android.tools.build:gradle:3.5.0' In the same project level build.gradle at the top under build scripts, upgrade Kotlin to this....... ext.kotlin_version = '1.3.50' Then under android/gradle/wrapper/gradle-wrapper.properties, change only this line and keep the .zip, so just replace the number to this...............distributionUrl=https://services.gradle.org/distributions/gradle-5.6.2-all.zip completely restart your app and Success!!! Upgrading over downgrading. Here are the before and after errors and the two files to fix the three upgrades

Thank you  its working :).

**Comment by kirushanthy** [comment]
* Error running Gradle:
ProcessException: Process exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\Users\acer\AndroidStudioProjects\flutter_app-master\flutter_app\android\settings.gradle' line: 15

* What went wrong:
A problem occurred evaluating settings 'android'.
> Could not read script 'C:\Users\acer\flutter\flutter\packages\flutter_tools\gradle\app_plugin_loader.gradle' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
  Command: C:\Users\acer\AndroidStudioProjects\flutter_app-master\flutter_app\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.


this is my error can you help to solve

**Comment by flutterq2** [comment]
All possible working solution added [[Solved] Gradle failure A problem occurred evaluating project ‘:app’](https://fluttercorner.com/gradle-failure-a-problem-occurred-evaluating-project-app/)
