### ISSUE TITLE
How can I reduce the amount of items displayed on the screen?

### ISSUE THREAD

**Issue by cristianfb1989** [flutter/flutter#41497]
Hi, could somebody help me with this? Thank you
https://stackoverflow.com/questions/58139751/how-can-i-reduce-the-amount-of-items-displayed-on-the-screen

**Comment by BondarenkoStas** [comment]
@cristianfb1989 There is no such feature in flutter itself, but there are workarounds. Please check #23865. https://stackoverflow.com/a/53984215 is mentioned there, maybe it will help.

**Comment by cristianfb1989** [comment]
Thx @BondarenkoStas
