### ISSUE TITLE
Consider implementing "Accessibility Headings" API hook for Android

### ISSUE THREAD

**Issue by vick08** [flutter/flutter#41494]
Semantics(header:true) is currently mapped to UIAccessibilityTraitHeader on iOS, https://developer.apple.com/documentation/uikit/uiaccessibilitytraitheader?language=objc.
Android Accessibility framework provides a similar affordance called "accessibility heading", https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo.html#setHeading(boolean).
This is a feature request to implement corresponding semantics for Android to bring parity support for accessibility headings on both platforms.

/CC goderbauer

**Comment by Hixie** [comment]
We should try to get this done by early Q1.

**Comment by Hixie** [comment]
Status: we have a fix ready to go, but we first need to write an integration test on the framework side to go with it.
