### ISSUE TITLE
Separate out build vs browser reload times for flutter_web metrics

### ISSUE THREAD

**Issue by jakemac53** [flutter/flutter#41502]
## Use case

We would like to separate out the browser load times from the build times during hot restarts in the wild so we can properly prioritize which things to optimize first.

## Proposal

Break down the overall hot restart metrics into build time vs restart time.

The hot restart service extension method can be used as a proxy for restart time for now - it doesn't return until we are done loading all the new modules in the browser.

We can look at breaking these up into smaller pieces later as well.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/41545
