### ISSUE TITLE
Have TextInputType.datetime use UIKeyboardType.numbersAndPunctuation on iOS

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter#41508]
We are implementing the new [text input date picker for Material design](https://material.io/components/pickers/#mobile-pickers) which just uses a text input field for the user to enter the date. We set the `keyboardType` parameter on the `TextField` to `TextInputType.datetime` to bring up a keyboard appropriate for entering a date. On Android this works well. On iOS however, it just brings up the default keyboard. This works, but it requires the user to switch to numeric mode on the default keyboard to enter the date.

From the iOS docs, it looks like they support a default keyboard that comes up in numeric mode: `UIKeyboardType.numbersAndPunctuation`. Can we switch the Flutter implementation of `TextInputType.datetime` to use this on iOS? This would seem to be a closer match and give the user a better experience.

**Comment by goderbauer** [comment]
Looks like `TextInputType.datetime` is just missing in the iOS TextPlugin and should be added to the mapping here: https://github.com/flutter/engine/blob/27955f24772d11d11fb9b3d578cdc88de4ac917c/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L14

**Comment by LongCatIsLooong** [comment]
It looks like we don't have https://developer.apple.com/documentation/uikit/uikeyboardtype/namephonepad either. Many autofill hints don't work on iOS unless the keyboard is set to `UIKeyboardType.namePhonePad`.
