### ISSUE TITLE
 listView is now showing on page [New to Flutter]

### ISSUE THREAD

**Issue by saadalti** [flutter/flutter#41518]
Hello I'm totally new to Dart lang.
I think my code needs to put the ListTile in a widget?

I'm using MaterialPageRoute for navigating to a new page with built in ListTile in Listview 

The error on line 78 and 82 
 

My issue error line is on : 82 Below Repo.
`   builder: (BuildContext context, AsyncSnapshot snapshot){`
Thanks in advance!
Repo : [https://github.com/saadalti/Flutter-Drawer/blob/saadalti-patch-1/lib/pages/home_page.dart](https://github.com/saadalti/Flutter-Drawer/blob/saadalti-patch-1/lib/pages/home_page.dart)

**Comment by sarimk80** [comment]
Try setting the shrinkwrap to true

https://stackoverflow.com/questions/54007073/what-does-the-shrink-wrap-property-do-in-flutter

and the repo is change there is no 

`builder: (BuildContext context, AsyncSnapshot snapshot){`

**Comment by saadalti** [comment]
> Try setting the shrinkwrap to true
> 
> https://stackoverflow.com/questions/54007073/what-does-the-shrink-wrap-property-do-in-flutter
> 
> and the repo is change there is no
> 
> `builder: (BuildContext context, AsyncSnapshot snapshot){`

Sorry New to Github, I fixed the link.
I'll check your solution if it will work.

**Comment by saadalti** [comment]
> > Try setting the shrinkwrap to true
> > https://stackoverflow.com/questions/54007073/what-does-the-shrink-wrap-property-do-in-flutter
> > and the repo is change there is no
> > `builder: (BuildContext context, AsyncSnapshot snapshot){`
> 
> Sorry New to Github, I fixed the link.
> I'll check your solution if it will work.

Didn't work I'll define more about the error in the real post.

**Comment by escamoteur** [comment]
Please ask questions like this on stackoverflow as we can't give individual support here.
