### ISSUE TITLE
ListTile constructor parameters not exposed as properties

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#41513]
This came up in a UX study. When the participant was inspecting a ListTile, the inspector won't show any of its properties (see screenshot below). The framework seemed to be not exposing them as properties. The Flutter version was 1.9.1-hotfix2.

![image](https://user-images.githubusercontent.com/348942/65803754-6a54c480-e134-11e9-82eb-8af6b728f8e3.png)

**Comment by Hixie** [comment]
cc @goderbauer @jacob314 

We have a lint to ensure these are included. We should turn that lint on and fix all the issues. Michael was saying there's about 500 issues flagged by the lint currently.

**Comment by jacob314** [comment]
@pq if you can get an even partly broken version of the quick fix for that lint working it will make fixing all 500 cases much faster.

**Comment by goderbauer** [comment]
A somewhat automated way of fixing this would be awesome. I started fixing it manually for a couple of instances just to see what it is like and it is tedious...

**Comment by escamoteur** [comment]
Thanks for the reporting. Please add the output of flutter doctor here.

**Comment by pq** [comment]
@jacob314, @goderbauer: tracking a quick-fix in https://github.com/dart-lang/sdk/issues/38633.  Please add any implementation notes as they occur to you.  Thanks!
