### ISSUE TITLE
ios/.generated contains 150mb of data

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4151]
Not entirely sure what's in there, but my tiny demo app was 70mb compressed as a zip, until I realized that all of it's space was used by ios/.generated.  Once I removed ios/.generated it was 600k compressed.

Maybe we should move .generated into the `build` folder or something more obviously temporary?

**Comment by abarth** [comment]
I'm working on improving this as part of refactoring how the Xcode build works.

**Comment by chinmaygarde** [comment]
We can put the `.generated` folder anywhere really. All that the project needs to complete the build is the `Local.xcodeproject` that the tools fill in it.

**Comment by eseidelGoogle** [comment]
@chinmaygarde is this fixed now with all the moving and shaking of where xcode files go?

**Comment by abarth** [comment]
I don't believe so.

**Comment by tvolkert** [comment]
#4275 will clean things up a bit here.

**Comment by Hixie** [comment]
Is this still an issue?

**Comment by chinmaygarde** [comment]
We place artifacts in build/ now. It is in .gitignore but there is still
extra stuff I. The users directory.

**Comment by Hixie** [comment]
We should decide what we're doing about this, if anything, in the milestone 3 timeframe.

**Comment by chinmaygarde** [comment]
> Maybe we should move .generated into the build folder or something more obviously temporary?

The temporary files are now in `build/`. This is also where we put build artifacts for Android, FLX archives etc..
