### ISSUE TITLE
something with the constructors parameter passing.

### ISSUE THREAD

**Issue by Fa-d** [flutter/flutter#41517]
Performing hot reload...
Syncing files to device Android SDK built for x86...
Reloaded 1 of 469 libraries in 651ms.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building MyApp(dirty, state: _MyAppState#d8d99):
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 269 pos 10: 'data != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

User-created ancestor of the error-causing widget was: 
  MaterialApp file:///C:/Users/ERROR/Desktop/Practice/alert_test/lib/main.dart:5:23
When the exception was thrown, this was the stack: 
#2      new Text (package:flutter/src/widgets/text.dart:269:10)
#3      _MyAppState.build (package:alert_test/main.dart:47:25)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)

**Comment by escamoteur** [comment]
Please ask questions like this on stackoverflow as we can't give individual support here.

The error message is pretty clear, you passed a null value to the data parameter of Text
