### ISSUE TITLE
Include dart_library.js in the flutter_web_sdk

### ISSUE THREAD

**Issue by chingjun** [flutter/flutter#41510]
Internal: b/141771712

We need to include this file in the flutter_web_sdk for internal usage.

https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/lib/js/legacy/dart_library.js

**Comment by pedromassangocode** [comment]
Is this still a valid issue today?

**Comment by chingjun** [comment]
This is no longer needed. I'm closing this issue. Thanks.
