### ISSUE TITLE
How to know if a string Text will be displayed in a new line？

### ISSUE THREAD

**Issue by zhanghaigang666** [flutter/flutter#41536]
Excuse me, how can I know that a string will be wrapped after being rendered by Text, because I have to do some custom functions, need to know whether the string exceeds the width of a line, what should I do? I see the API did not find a way?

**Comment by escamoteur** [comment]
Hi, please ask questions like this on stackoverflow as we can't give individual support here.

**Comment by dev-zl** [comment]
@zhanghaigang666   I know

**Comment by dev-zl** [comment]
@zhanghaigang666  use TextPainter 

`
bool judgeTitleTextMarquee(double parentWidth) {
    final textPainter = TextPainter(
      textDirection: TextDirection.ltr,
      text: TextSpan(
        text: title,
        style: titleStyle,
      ),
    );
    textPainter.layout();
    var textWidth = textPainter.width;
    if (textWidth > parentWidth) {
      return true;
    }
    return false;
  }
`

**Comment by VladyslavBondarenko** [comment]
Given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
