### ISSUE TITLE
Google maps showing on blank for some seconds and then closing the app only on APK

### ISSUE THREAD

**Issue by Jumpbotron** [flutter/flutter#41533]
I am actually facing an issue with google maps flutter. the thing is that everything looks just fine when I use the flutter run command. But, when I install the app on any device with a signed APK file the app apparently crashes when starting the google maps. I have been fighting towards this but I wasn't able find a solution.

App with Flutter run 
![1](https://user-images.githubusercontent.com/24376974/65811864-c0e9ef00-e184-11e9-8aaf-b64c4801630e.gif)

App with signed APK
![2](https://user-images.githubusercontent.com/24376974/65811884-00b0d680-e185-11e9-84c6-8fa50509a7f7.gif)

**Comment by escamoteur** [comment]
Please add the output of flutter doctor here.
Also show us the code where you create the map

**Comment by Jumpbotron** [comment]
> Please add the output of flutter doctor here.
^[[CDoctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.7-pre.51, on Mac OS X 10.14.6 18G95, locale en-PE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

• No issues found!

> Also show us the code where you create the map

`import 'dart:async';

import 'package:flutter/material.dart';

import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:location/location.dart';
import 'package:safer/arguements/MarkerDetailsA.dart';
import 'package:safer/behaviors/hiddenScrollBehavior.dart';
import 'package:safer/functionalities/saferDay.dart';
import 'package:safer/pages/markerAdd.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_datetime_picker/flutter_datetime_picker.dart';
import 'package:safer/pages/markerDetails.dart';


class ScreenArguments {
  final LatLng _markerposition;
  ScreenArguments(this._markerposition);
}

class MapPage extends StatefulWidget{
  @override
  State<StatefulWidget> createState() {
    return _MapPageState();
  }

}

class _MapPageState extends State<MapPage> with AutomaticKeepAliveClientMixin<MapPage>{
    void _handleRadioValueChange(int value) {
    setState(() {
      _currtime = value;
      _markers.clear();

    });
    print(_currtime);
  }
    
    
    @override
    bool get wantKeepAlive => true;
  var today = new DateTime.now();


  int _todaySaferDay = null;


  //Markers Update
  Timer markers_timer;
  Firestore firestore = Firestore.instance;

  //MAP SETUP
  Set<Marker> _markers = {};
  GoogleMapController mapController;
  CameraPosition _initialPosition = CameraPosition(target: LatLng(-12.0244094, -76.9874568), zoom: 12);
  LatLng _lastMapPosition = LatLng(-12.078227, -77.055827);
  Location location = new Location();

  //Top-Action-Button
  Icon _iconRecordBtn = Icon(Icons.add_location, color: Colors.white,);
  Text _phraseRecordBtn = Text('  I N C I D E N T E  ', style: TextStyle(color: Colors.white),);
  VoidCallback _actionBtn = null;
  
  //Marker 4 Adding Preview
  bool _markerShow = false;
  BitmapDescriptor pointer = BitmapDescriptor.defaultMarker;

  //Filters

  bool _filterButton = true;
  bool _filterMenu = false;
  int _currtime = 0;
  
  void requestPermission(String permission) async{
      switch(permission){
        case 'location':
        Map<PermissionGroup, PermissionStatus> permissions = await PermissionHandler().requestPermissions([PermissionGroup.location]);
        break;
      }
  }


  @override
  void initState() {
    _todaySaferDay = SaferDay(
    DateTime.utc(2019,DateTime.august, 14),
    DateTime.utc(today.year,today.month,today.day)
  ).getSaferDay();
    markers_timer = Timer.periodic(Duration(seconds: 1), (Timer t) => _updateMarkers(_markerShow));
    _actionBtn = ()=>{_markerPreview()};
    requestPermission('location');
      location.onLocationChanged().listen((location) async {
      _initialPosition = CameraPosition(target: LatLng(location.latitude, location.longitude),zoom: 10);
    
   });
    
    super.initState();

  }
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Scaffold( 
    body:
    Stack(
      children: <Widget>[
            GoogleMap(    
              mapType: MapType.normal,
              initialCameraPosition: _initialPosition,
              myLocationEnabled: true,
              onMapCreated: _onMapCreated,
              markers: _markers,
              onCameraMove: _onCameraMove,
            ),
            Positioned(
            top: 5,
            right: 56,
            left: 53,
            child: 
            FlatButton(
              shape: RoundedRectangleBorder(borderRadius: new BorderRadius.circular(30.0)),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                _iconRecordBtn,
                _phraseRecordBtn
              ],),
              color: Colors.red,
              onPressed: _actionBtn,
            ),
            ),
            
            Visibility(
            visible: _markerShow,
            child:
            Align(
              alignment: Alignment.center,
              child: 
              Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                Icon(Icons.location_on,size:50,color: Colors.red,),
                Text('Arrastra el mapa',style: TextStyle(fontSize: 12),),
                Padding(padding: EdgeInsets.all(10),)
              ],)
            ),
            ),
            Visibility(
            visible: _markerShow,
            child:
            Align(
              alignment: Alignment.bottomLeft,
              child: 
              Align(
              alignment:Alignment.bottomCenter,
              child:
              Padding(
                padding:EdgeInsets.only(bottom: 15),
                child:
              FloatingActionButton(
              tooltip: 'Cancelar',
              backgroundColor: Colors.transparent,
              child: 
                Icon(Icons.cancel, color: Colors.white,size: 60,),
              onPressed: _normalPreview,
              
              
            ),
              )
              ),
            ),
            ),
            Visibility(
            visible: _filterButton,
            child:
            Positioned(
            top: 50,
            right: 56,
            left: 53,
            child: 
            FlatButton(
              shape: RoundedRectangleBorder(borderRadius: new BorderRadius.circular(30.0)),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                Icon(Icons.sort,color: Colors.white,),
                Text('  FILTRAR  RESULTADOS ', style: TextStyle(color: Colors.white))
              ],),
              color: Colors.blue,
              onPressed: (){
                setState(() {
                _filterMenu = true;
                });
              },
            ),
            ),
            ),
            Visibility(
              visible: _filterMenu,
              
              child: 
              Wrap(children: <Widget>[
                Container(
                  width: double.infinity,
                color: Colors.white,
                child: 
                 Column(
                  children: <Widget>[
                  Padding(
                  padding: EdgeInsets.only(right: 20,left: 20,top: 5),
                  child:
                  Align(
                    alignment:Alignment.topLeft,
                    child:
                  Text(
                  "Filtrar resultados",
                  style: TextStyle(fontSize: 25,fontWeight: FontWeight.bold),
                  
                  ),   
                  ),
                  ),
                 
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: <Widget>[
            new Radio(
                          value: 0,
                          groupValue: _currtime,
                          onChanged: _handleRadioValueChange,
                        ),
                        new Text(
                          '+30',
                          style: new TextStyle(fontSize: 16.0),
                        ),
                        
                         new Radio(
                          value: 1,
                          groupValue: _currtime,
                          onChanged: _handleRadioValueChange,
                        ),
                        
                        new Text(
                          '7 días',
                          style: new TextStyle(fontSize: 16.0),
                        ),         
                        new Radio(
                          value: 2,
                          groupValue: _currtime,
                          onChanged: _handleRadioValueChange,
                        ),
                        new Text(
                          'Hoy',
                          style: new TextStyle(fontSize: 16.0),
                        ),
                        Padding(
                          padding: EdgeInsets.all(10),
                        )
                  ],),
                  
                         
                            
                            Padding(padding: EdgeInsets.all(2),),
               
          
                  FlatButton(
                    child: Text("cerrar"),
                    onPressed: (){
                          setState(() {
                               _filterMenu = false;
                          });
                      
                    },
                  )
                       
                        
                ],),
                
                ),
              
              ]
              
              ),
              

            
            )],
    ),
  
    );

  }

  void _onCameraMove(CameraPosition position) {
    _lastMapPosition = position.target;
  }

  _onMapCreated(GoogleMapController controller){
    setState(() {
    this.mapController = controller;
    });
  }

  _normalPreview(){
    setState(() {
    _iconRecordBtn = Icon(Icons.add_location, color: Colors.white,);
    _phraseRecordBtn = Text('  I N C I D E N T E  ', style: TextStyle(color: Colors.white),);
    _markerShow = false;
    _filterButton = true;
    _actionBtn = (){
      _markerPreview();
      
    };
    });
     
  }

  _markerPreview(){
    setState(() {   
       _iconRecordBtn = Icon(Icons.check, color: Colors.white,);
       _phraseRecordBtn = Text('  R E P O R T A R  ', style: TextStyle(color: Colors.white),);
       _markerShow = true;
       _filterButton = false;
       _actionBtn = (){
      Navigator.push(context, MaterialPageRoute(builder: (context)=>MarkerAddPage(_lastMapPosition)));
      _normalPreview();

       };
    });

  }

 


  void _updateMarkers(bool function) async{
    
      if(function){
        setState(() {
          _markers.clear();
        }); 
      }else{
      _markers.clear();
      QuerySnapshot querySnapshot = await Firestore.instance.collection('locations').getDocuments();
      var list = querySnapshot.documents;
      list.forEach((document){
          String title = document.data['name'];
          String user = document.data['user'];
          String descripcion = document.data['descripcion'];
          String date = document.data['fecha'];
          String time = document.data['hora'];
          String commentDoc = document.data['comments_Id'];
          int _saferDayMarker = document.data['saferDay'];
          var latitude = document.data['latitude'];
          var longitude = document.data['longitude'];
           if(_currtime == 1){
            if(_saferDayMarker > _todaySaferDay-7){
              setState(() {
                final int markerCount = _markers.length;
                _markers.add(
                new Marker(
                  markerId: MarkerId(markerCount.toString()),
                position: LatLng(latitude, longitude),
                icon: BitmapDescriptor.defaultMarker,
                infoWindow: InfoWindow(
                  title: title,
                  snippet: "Por: " + user,
                  onTap: ()=> Navigator.of(context).pushNamed(
                    '/markerDetails',arguments: MarkerDetailsA(
                    title,descripcion,user,date,time,document.documentID,latitude,longitude,commentDoc
                  ))
                )
              )
                );
              });
            }
            
          }else if(_currtime == 2){
              if(_saferDayMarker == _todaySaferDay){
                setState(() {
                final int markerCount = _markers.length;
                _markers.add(
                new Marker(
                  markerId: MarkerId(markerCount.toString()),
                position: LatLng(latitude, longitude),
                icon: BitmapDescriptor.defaultMarker,
                infoWindow: InfoWindow(
                  title: title,
                  snippet: "Por: " + user,
                  onTap: ()=> Navigator.of(context).pushNamed(
                    '/markerDetails',arguments: MarkerDetailsA(
                    title,descripcion,user,date,time,document.documentID,latitude,longitude,commentDoc
                  ))
                )
              )
                );
              });
              }
          } else{
               setState(() {
                final int markerCount = _markers.length;
                _markers.add(
                new Marker(
                  markerId: MarkerId(markerCount.toString()),
                position: LatLng(latitude, longitude),
                icon: BitmapDescriptor.defaultMarker,
                infoWindow: InfoWindow(
                  title: title,
                  snippet: "Por: " + user,
                  onTap: ()=> Navigator.of(context).pushNamed(
                    '/markerDetails',arguments: MarkerDetailsA(
                    title,descripcion,user,date,time,document.documentID,latitude,longitude,commentDoc
                  ))
                )
              )
                );
              });
          }
      
          
          
     
        });
      }
  }

}

Thank U for the help

**Comment by escamoteur** [comment]
Hi,
don't you have any error messages in the debug pane?
Or try to check in logcat?

I just wanted to reproduce it but there are too many components from you involved.
Please try to make s a simple version without Firestore that you can share with us.
We can not debug you whole App.

**Comment by janmoppel** [comment]
Hello @Jumpbotron !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
