### ISSUE TITLE
[google_maps_flutter] Markers from asset sizing problem

### ISSUE THREAD

**Issue by theochampion** [flutter/flutter#41539]
Hi there,

I'm building a series of markers from local image assets (.png, 128x128px) using the following code

```dart
final ImageConfiguration imageConfiguration = 
    createLocalImageConfiguration(context, size: Size(100, 100));
BitmapDescriptor bmd = 
    BitmapDescriptor.fromAssetImage(imageConfiguration, 'assets/marker_10.png')
```

from what I understand, the markers should be rendered at 100x100px (virtual pixels?) according to the device pixel ratio.

But in my case, that doesn't appear to work as they end up being rendered 10 times bigger on my IOS device than on my Android.

Am I missing something here ? :)

Cheers!

**Comment by escamoteur** [comment]
Could please tell me what version of flutter_map you have?
And please add the output of flutter doctor here

**Comment by theochampion** [comment]
@escamoteur I'm using the latest version of google_maps_flutter (`^0.5.21+6`)

`flutter doctor -v`

```bash
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F132, locale en-AU)
    • Flutter version 1.9.1+hotfix.2 at /Users/theo/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/theo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • ONEPLUS A5010 • 57dd18b2 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by giancarlopro** [comment]
I believe it's because flutter `BitmapDescriptor.fromAssetImage` ignores `size` attribute and uses only `devicePixelRatio` as we see [here](https://github.com/flutter/plugins/blob/2d1c16e5c8b510f1a80ad98f71cb6f7e491f4b87/packages/google_maps_flutter/lib/src/bitmap.dart#L62,L78)

To properly resize you must define resolution-aware assets, as pointed [here](https://flutter.dev/docs/development/ui/assets-and-images#declaring-resolution-aware-image-assets)

**Comment by VladyslavBondarenko** [comment]
Hi @theochampion 
given the last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
