### ISSUE TITLE
TabBar does not preserve order after the state updates

### ISSUE THREAD

**Issue by SwissCheese5** [flutter/flutter#41535]
![2019-09-28_12-18-39](https://user-images.githubusercontent.com/7407478/65814422-24f2ce80-e1ea-11e9-84f3-5065a121ee19.gif)

In the gif, you can see that the date tabs keep changing every time the state updates. This seems to be a bug. I don't think the tabs sort the list before using it.

```dart
                    Center(
                      child: Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 15.0),
                        child: TabBar(
                          controller: _tabController,
                          indicatorSize: TabBarIndicatorSize.tab,
                          labelColor: Theme.of(context).primaryColor,
                          unselectedLabelColor: Color(0xFFEEEEEE),
                          isScrollable: true,
                          indicator: MD2Indicator(
                              indicatorHeight: 3,
                              indicatorColor: Theme.of(context).primaryColor,
                              indicatorSize: MD2IndicatorSize.normal),
                          tabs: _calendarro.selectedDates
                              .map((date) => Tab(
                                      child: Text(
                                    "${DateFormat('MMM').format(date)}-${DateFormat('E').format(date)}\n${date.day}",
                                    textAlign: TextAlign.center,
                                    style: TextStyle(fontSize: 12),
                                  )))
                              .toList(),
                        ),
                      ),
                    ),
```
_calendarro.selectedDates is unchanged during tab navigation.

flutter doctor -v:
```
[√] Flutter (Channel beta, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.10022], locale en-US)
    • Flutter version 1.9.1+hotfix.2 at C:\flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\saad4\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\saad4\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\saad4\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.4
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5215

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by escamoteur** [comment]
Does it behave the same if you disable scrolling to the tabs?

**Comment by SwissCheese5** [comment]
@escamoteur It behaves the same when isScrollable is set to false:
![2019-09-28_15-03-26](https://user-images.githubusercontent.com/7407478/65816171-2da2cf00-e201-11e9-9287-697fd756ec17.gif)

**Comment by escamoteur** [comment]
Is this an Android Emulator?
Which android version?
Could you please try with latest master channel version?

**Comment by stuartmorgan** [comment]
> I don't think the tabs sort the list before using it.

Lists are intrinsically ordered; it uses them in the order they are provided. If you want them sorted to a specific order, you need to sort the list yourself.

Your issue is almost certainly that `_calendarro.selectedDates` is either an unordered collection type, or whatever is populating it is unordered, either of which would be a bug in your code rather than TabBar.

**Comment by escamoteur** [comment]
@stuartmorgan he wrote that the list does not change while switching the tabs.

**Comment by stuartmorgan** [comment]
There's no indication in the report or the provided code that it *is* a list, rather than an unordered collection. Or that it's a stable variable rather than a getter that may not have a predictably ordered return value the way it's implemented.

It is much, much more likely that `_calendarro.selectedDates[...].toList()` isn't making what @SwissCheese5 thinks it's making than that `TabBar` is, say, accidentally calling `shuffle()` on `tabs`, so I think it's useful to clearly establish what that code is doing.

**Comment by SwissCheese5** [comment]
@stuartmorgan makes a good point which is why i'm investigating this further. I'll post the results in another comment for other people who google the same issue to find.

**Comment by SwissCheese5** [comment]
It seems
```dart
                          tabs: List.of(_calendarro.selectedDates..sort())
                              .map((date) => Tab(
                                      child: Text(
                                    "${DateFormat('MMM').format(date)}-${DateFormat('E').format(date)}\n${date.day}",
                                    textAlign: TextAlign.center,
                                    style: TextStyle(fontSize: 12),
                                  )))
                              .toList(),
```
Fixed the problem. It seems calendarro.selectedDates does something differently despite being a regular List<DateTime> object.
