### ISSUE TITLE
Status of desktop? How can I help?

### ISSUE THREAD

**Issue by 11azars** [flutter/flutter#41531]
Hi there! I've been playing with writing a SQL (PostgreSQL ATM) client using the current desktop embedder for Linux. Obviously, there are rough edges that need worked out... I would like to help if possible, and am wondering where to find info to get started/what the goals for desktop are/what the status of current efforts are?

Some of the stuff I noticed was:
- lack of a good API (AFAIK) for window resize/control within dart
- keyboard shortcuts require wrapping a Widget in something to handle inputs (current stuff works fine, but is gross when you need shortcuts that tie into a nested view, and the view cannot share the scope).
- lack of general copy/paste support sucks... I have been playing with something along the lines of sharing a focusNode that would allow me to determine if I can read/write text when someone presses the shortcut.

Sorry for the poor formatting here... it's a bit late here, and I only had a minute.
Thanks!!!

**Comment by 11azars** [comment]
If any of the above is something I can help address, I would be more than happy to give it a shot (granted someone can point me in the right direction).

**Comment by escamoteur** [comment]
Join the contributor Discord and ask in channel hackers - desktop
https://github.com/flutter/flutter/wiki/Chat

**Comment by stuartmorgan** [comment]
> and am wondering where to find info to get started/what the goals for desktop are/what the status of current efforts are

The issue tracker is also a good starting point for both goals and current status; desktop-related work is collected under the `a: desktop` label.
