### ISSUE TITLE
How can I use connectivity plugin to check entire app that has connection?

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#41532]
In demo of connectivity plugin works fine. But I need to check connectivity always and warn user that they lost the connection if there is no connection or signal at all.  I thing I can use provider plugin to accomplish this but I don't know how or where to start. 

If the user inside app and suddenly they lost connection I need to warn them. How can I use connectivity plugin to check entire app that has connection?

**Comment by vash72** [comment]
example, in MyApp open a "listener" for connectivity changes

```
  subscription = Connectivity().onConnectivityChanged.listen((ConnectivityResult result) {
    // Got a new connectivity status!
    // if "lost connectivity" -> do something
  })
```

:) next time maybe try stackoverflow

**Comment by escamoteur** [comment]
Please ask questions like this on stackoverflow as we can't give individual support here.
