### ISSUE TITLE
[WEB]  Failed to load asset at path: packages/build_web_compilers/src/dev_compiler/dart_sdk.js.

### ISSUE THREAD

**Issue by RD211** [flutter/flutter#41546]
With the recent master and dev branch updates my flutter website doesn't work.
When i build it it shows me this error:
Failed to load asset at path: packages/build_web_compilers/src/dev_compiler/dart_sdk.js.

                     Status code: 404

                     Headers:
                     {
                       "date": "Sat, 28 Sep 2019 18:57:46 GMT",
                       "content-length": "9",
                       "x-frame-options": "SAMEORIGIN",
                       "content-type": "text/plain; charset=utf-8",
                       "x-xss-protection": "1; mode=block",
                       "x-content-type-options": "nosniff",
                       "server": "dart:io with Shelf",
                       "via": "1.1 shelf_proxy"
                     }

                     Content:
                     Not Found

And the webpage that is opened is a blank white screen.
Will this be fixed or am i doing something wrong?

**Comment by escamoteur** [comment]
Hi, are sure you are on the latest master version? Always do a flutter clean when upgrading.
Please post the output of flutter doctor here.

**Comment by RD211** [comment]
I did a flutter clean and the error doesn't go away, i am on v1.10.7-pre.72
and i have the same error on dev too.

The flutter doctor -v output:

[√] Flutter (Channel master, v1.10.7-pre.72, on Microsoft Windows [Version 10.0.18990.1], locale en-US)
    • Flutter version 1.10.7-pre.72 at C:\Users\David\Desktop\flutter
    • Framework revision 0223565fd5 (3 hours ago), 2019-09-28 08:55:47 -0700
    • Engine revision 5b952f286f
    • Dart version 2.6.0 (build 2.6.0-dev.3.0 6ff8d2199d)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\David\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\David\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

• No issues found!

**Comment by jonahwilliams** [comment]
Duplicate of https://github.com/flutter/flutter/issues/40151
