### ISSUE TITLE
widget RichText font size problem

### ISSUE THREAD

**Issue by mudi256** [flutter/flutter#41549]
when mobile font size changes "RichText" not take the size, like "Text"
below is my code snippet for better understanding.
```
RichText(
                                  text: TextSpan(
                                    text: DateFormat('dd MMM kk:mm').format(
                                        DateTime.fromMillisecondsSinceEpoch(
                                            int.parse(document['timestamp']))),
                                    style: TextStyle(
                                        color: greyColor,
                                        fontStyle: FontStyle.italic),
                                    children: []
                                  ),
                                ),
```
<img width="682" alt="Screenshot 2019-09-29 at 5 47 27 AM" src="https://user-images.githubusercontent.com/36504724/65824125-b7dc4900-e27c-11e9-88b2-9d69c9e24c77.png">
 widget

**Comment by BondarenkoStas** [comment]
@mudi256 By any case, did you test it with different emulators or physical devices? Is it always like that or there is a concrete device?

**Comment by mudi256** [comment]
> @mudi256 By any case, did you test it with different emulators or physical devices? Is it always like that or there is a concrete device?

yeah i tested on different devices, did you test it by yourself?

**Comment by escamoteur** [comment]
Please add the output of flutter - v here.
Does this happen on Android and iOS?

**Comment by mudi256** [comment]
> Please add the output of flutter - v here.
> Does this happen on Android and iOS?
on both android and ios. Further here v for flutter version
<img width="682" alt="Screenshot 2019-09-29 at 5 47 27 AM" src="https://user-images.githubusercontent.com/36504724/65840869-53ca8b00-e337-11e9-9843-d13188d869fb.png">

**Comment by escamoteur** [comment]
I'm not 100% sure what you mean by *when mobile font size changes* do you mean you change the font size in the phones settings?
Could you try it on the latest master channel please?

**Comment by mudi256** [comment]
> I'm not 100% sure what you mean by _when mobile font size changes_ do you mean you change the font size in the phones settings?
> Could you try it on the latest master channel please?

yes change font size in phone settings. Not try master channel yet. 
further did i need to move from stable to master?

**Comment by escamoteur** [comment]
It's a try. Just do a `flutter channel master`, `flutter upgrade` and `flutter clean`

**Comment by mudi256** [comment]
> It's a try. Just do a `flutter channel master`, `flutter upgrade` and `flutter clean`
ok

**Comment by goderbauer** [comment]
What's the expected behavior here? What's the observed one?

Also please post a complete code snippet that we can copy and run to see the problem.

**Comment by mudi256** [comment]
Show two widgets in app, then increase your mobile font size from mobile settings, then open the app app, you will see "RichText" widget font size still smaller as compare to "Text" widget.
1) Using Text
2)Using RichText

**below is code snippet**
Column(
      children: <Widget>[
        Text("Hello Using Text Widget"),
        RichText(
          text: TextSpan(
              text: "Hello Using RichText Widget",
               style: TextStyle(
                 color: Colors.black
               )
          ),
        ),
      ],
    );
**below is Output before changing the font size from mobile setting**

![Screenshot_20191003-094049](https://user-images.githubusercontent.com/36504724/66100068-ed599d00-e5c2-11e9-98b2-ca00c561d354.jpg)
**increasing the font size from mobile setting**

![Screenshot_20191003-093912_Settings](https://user-images.githubusercontent.com/36504724/66100094-fa768c00-e5c2-11e9-855d-4de57b0d2548.jpg)

**Output after increasing the font size**

![Screenshot_20191003-094012](https://user-images.githubusercontent.com/36504724/66100122-06624e00-e5c3-11e9-9767-68b494bed96b.jpg)

**Comment by mudi256** [comment]
Any update?

**Comment by escamoteur** [comment]
@goderbauer we have now screenshots

**Comment by escamoteur** [comment]
@mudi256 unfortunately I can not tell, you how fast we can solve this. Have you tried to debug I to the framework? Its pretty good document and not hard to understand.
If you can pinpoint the root of the problem it will speed up fixing.

**Comment by fullmers** [comment]
I was having this issue as well. I tried to solve it by setting 
```
RichText(
textScaleFactor: MediaQuery.of(context).textScaleFactor,
text: ...
)
```

This did not solve the issue, which I found surprising. So, hopefully that helps with your debugging.

**Comment by Benqstanley** [comment]
I found a workaround that worked in my project using the following: 

`class ScalableTextSpan extends TextSpan {
  const ScalableTextSpan._internal({
    String text,
    List<InlineSpan> children,
    TextStyle style,
    GestureRecognizer recognizer,
    String semanticsLabel,
  }) : super(
          style: style,
          text: text,
          children: children,
          recognizer: recognizer,
          semanticsLabel: semanticsLabel,
        );

  factory ScalableTextSpan(
    BuildContext context, {
    String text,
    List<InlineSpan> children,
    TextStyle style,
    GestureRecognizer recognizer,
    String semanticsLabel,
  }) {
    double fontSize;
    style = style ?? DefaultTextStyle.of(context).style;
    //The default fontSize is 14.0
    fontSize = style.fontSize ?? 14.0;
    return ScalableTextSpan._internal(
      style: style.copyWith(
          fontSize: fontSize * MediaQuery.of(context).textScaleFactor),
      text: text,
      children: children,
      recognizer: recognizer,
      semanticsLabel: semanticsLabel,
    );
  }
}`

Then just use this ScalableTextSpan instead of TextSpan inside of your RichText

**Comment by mudi256** [comment]
> @escamoteur
> I was having this issue as well. I tried to solve it by setting
> 
> ```
> RichText(
> textScaleFactor: MediaQuery.of(context).textScaleFactor,
> text: ...
> )
> ```
> 
> This did not solve the issue, which I found surprising. So, hopefully that helps with your debugging.

this worked
