### ISSUE TITLE
flutter web how to use package and plugin? 

### ISSUE THREAD

**Issue by qiuguian** [flutter/flutter#41556]
Skipping compiling  xx_web_entrypoint.dart with ddc because some of tis transitive libraries have sdk dependencies that not supported on this platform

**Comment by GaspardMerten** [comment]
Do you import dart:io?

**Comment by escamoteur** [comment]
Not clear what you you want to know? Please provide more information.
Please also add the output of flutter doctor - v here.

**Comment by qiuguian** [comment]
Thank you for response! 
If pacakes or plugin  don't support the web, how do skip these compilations when compiling the web。

![WechatIMG73](https://user-images.githubusercontent.com/7962840/65845165-a756cc00-e36b-11e9-9fe4-e41c2299b9a2.jpeg)

**Comment by jonahwilliams** [comment]
The underlying issue is covered in https://github.com/flutter/flutter/issues/39998. The TLDR is that there is currently no way to do so. Longer-term TBD
