### ISSUE TITLE
Error: Error when reading '../../bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot': No such file or directory

### ISSUE THREAD

**Issue by ny8080** [flutter/flutter#41552]
This problem occurred when I ran my app. Who knows how to solve it?

**Comment by escamoteur** [comment]
Please add the output of flutter doctor - v here.
Does this happen while building or after start up?
Please add your full log output here.

**Comment by ranashreyas** [comment]
I have this exact same issue.

Here is my flutter doctor -v output:

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/frogman/Desktop/Shreyas/Programming/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/frogman/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Redmi Note 6 Pro • 96969c9 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by escamoteur** [comment]
@ranashreyas 

- Does this happen while building or after start up?
- Please add your full log output here.
- Does this happen with a newly created project?

**Comment by mycodingbuddy23** [comment]
I'm having this same issue and it happens every time I stop using Flutter for some period of time. I know that's very vague, but I don't know the specific timeframe.  The only way I've been able to solve it is by cleaning the git repo: 

- git clean -xfd
- git stash save --keep-index
- git stash drop
- git pull
- flutter doctor

**Comment by escamoteur** [comment]
Please upgrade all to the latest release on stable which is hotfix-5, thanks

@mycodingbuddy23 could you please add your `flutter doctor -v` output here?

**Comment by mycodingbuddy23** [comment]
I actually discovered my issue and it actually had nothing to do with my Flutter configuration.

 iCloud had actually deleted the pub.dart.snapshot locally and had left a shadow version behind. Because of this, Flutter could not access it!

**Comment by Alecinvader** [comment]
> I actually discovered my issue and it actually had nothing to do with my Flutter configuration.
> 
> iCloud had actually deleted the pub.dart.snapshot locally and had left a shadow version behind. Because of this, Flutter could not access it!

Did you download it again or what did you do to fix the local version, I am having the same issue.

**Comment by mycodingbuddy23** [comment]
I just followed the path to the file and downloaded it. I'm not exactly sure how the iCloud service chooses which files to not keep locally but I have not had issues since downloading it manually.

**Comment by hugomvsv** [comment]
where is situated the directory?

**Comment by joaoraffs** [comment]
you can delete the `cache` folder inside `bin` and it may help you

**Comment by agehua** [comment]
I am a beginner using Fluttter. In my case, fixed this issue by changing :
**apply plugin: 'com.android.library'**  to
**apply plugin: 'com.android.application'**

**Comment by DeepaPradeepa** [comment]
> @ranashreyas
> 
> * Does this happen while building or after start up?
> * Please add your full log output here.
> * Does this happen with a newly created project?

While building

**Comment by Zheng7426** [comment]
> I actually discovered my issue and it actually had nothing to do with my Flutter configuration.
> 
> iCloud had actually deleted the pub.dart.snapshot locally and had left a shadow version behind. Because of this, Flutter could not access it!

How did you fix this issue mate?
