### ISSUE TITLE
Allow Object, Object List and Map set get

### ISSUE THREAD

**Issue by contactlutforrahman** [flutter/flutter#41555]
Please allow the plugin to set and get object, object list and map.

**Comment by escamoteur** [comment]
Hi, which package are you talking about? Please explain in detail what you want.

**Comment by contactlutforrahman** [comment]
I'm talking about https://pub.dev/packages/shared_preferences

Please allow the plugin to set and get object, object list and map.

**Comment by escamoteur** [comment]
How should this go? Objects need to be serialized to store them which is not possible to generalise without reflection.
You cannot dump a Dart object into a byte array.

**Comment by stuartmorgan** [comment]
As there's been no clarification on what exactly this would be expected to do, closing.
