### ISSUE TITLE
Open url in web browser in iOS

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4156]
In Android, I can use an Intent to open a link in a browser. There needs to be an equivalent mechanism in the iOS build.

In practice, I think there should be a platform-independent way to do this. It's unpleasant to have to build a switch statement for all supported platforms.

**Comment by chinmaygarde** [comment]
On iOS, this is just a simple call to [`-[UIApplication openURL:]`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/#//apple_ref/occ/instm/UIApplication/openURL:). About the platform independence, what do you think a good interface name is? Can wire it up for both and put the interface in https://github.com/flutter/engine/tree/master/sky/services/platform

**Comment by jimbeveridge** [comment]
`openUrl()` is fine with me.

**Comment by eseidelGoogle** [comment]
I just re-read customer:fast's design document for their MVP.  They mention the ability to send an email as feedback from the app.  I'm assuming this bug would cover being able to open a `mailto:` link?  (I'm guessing a mailto: with this api would be easier than trying to solve https://github.com/flutter/flutter/issues/133.)

**Comment by eseidelGoogle** [comment]
I don't think @collinjackson is actively working on this.  @chinmaygarde would you be able to add this?

**Comment by chinmaygarde** [comment]
Sure.

**Comment by chinmaygarde** [comment]
`uri_launcher.mojom` now has both iOS and Android backend. You may use the same without platform specific guards. We should discourage use of activity.mojom. I believe everything it does is already implemented by flutter:platform in a platform agnostic manner.

**Comment by eseidelGoogle** [comment]
I'm not able to find any of this in our docs at http://docs.flutter.io/, should I be?  I'm interested in showing a customer how to use this. Do I just need to wait for #4584?

**Comment by chinmaygarde** [comment]
An example of using this is https://gist.github.com/chinmaygarde/d778498418e30825d687147b79d070eb.
