### ISSUE TITLE
[image_picker] GIF loses animation

### ISSUE THREAD

**Issue by ozzy1873** [flutter/flutter#41568]
## Steps to Reproduce

Update to image_picker version 0.6.1+4 and open a GIF file. The image loses animation.
Version 0.6.0+17 retains the animation.

```
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.356], locale en-US)
    • Flutter version 1.9.1+hotfix.2 at c:\src\flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\john\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Pixel 3 • 8B8X15F76 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by ozzy1873** [comment]
This suddenly started working after updating gradle, setting the min SDK level to 29, and rebuilding.
Closing.

**Comment by ozzy1873** [comment]
I have to reopen this. This behavior is random. Sometimes GIFs work normally, sometimes they do not. The animation can break by simply rebuilding and reinstalling the app on a phone with no code changes. Once you have a build that works, it continues to work through multiple installs -- just don't rebuild or you risk losing the animation again.

**Comment by BondarenkoStas** [comment]
@ozzy1873 do you encounter it only with one particular app? Is there a way to isolate a small self-contained app that demonstrates the problem (at least randomly)?

**Comment by ozzy1873** [comment]
I'm only working on one app. I'll try to duplicate the problem, but it will be difficult to find time for a while.

**Comment by cyanglaz** [comment]
@ozzy1873 Did you get a chance to isolate a small app for us to reproduce the issue?
Also, do you think it is related to this update? https://github.com/flutter/plugins/pull/1896

**Comment by ozzy1873** [comment]
Sorry, I haven't been able to create an app that reproduces the issue. I upgraded all the referenced plugins in my app to the latest versions, including image_picker, and the animation is working. That doesn't mean it won't break the next time I upgrade, but it's working right now. It could be related to [https://github.com/flutter/plugins/pull/1896](url). It is behaving like it has been changed from a GIF to a different format like jpg or png. Do you have a suggestion for how I might test that?

**Comment by cyanglaz** [comment]
@ozzy1873 I took a deeper look at flutter/plugins#1896 and it doesn't seem to touch any gif code. Since you couldn't reproduce the issue and this issue hasn't gotten a lot of thumbs-ups, do you think it could be some weird state that your machine was in which picked up a wrong version of the plugin?

If the issue occurs again, you can try to capture the production steps and other details, then post them here so we can further investigate.

**Comment by cyanglaz** [comment]
I'm removing the regression label since it is not reproducible anymore.

**Comment by Minituff** [comment]
@ozzy1873  Can you please post your flutter code for picking and displaying the gif?

**Comment by ozzy1873** [comment]
I can no longer reproduce this problem after updating all plugins and flutter to the latest versions. I'll close this and enter another ticket if it recurs. Thanks!
