### ISSUE TITLE
No keyboard input in iOS sumulator.

### ISSUE THREAD

**Issue by AntSwift** [flutter/flutter#41562]
I am unable to interact with a `CupertinoAlertDialog` when using the iOS simulator (android emulator is fine). I do get a cursor in the `CupertinoTextField` but there is no input from the physical keyboard and no software keyboard is displayed.

I have tried the Keyboard options in the Hardware menu to no avail.

## Steps to Reproduce

Run the following sample app, click the button.

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: BrokenDialogPage(),
    );
  }
}

class BrokenDialogPage extends StatefulWidget {
  BrokenDialogPage({Key key}) : super(key: key);

  @override
  _BrokenDialogPageState createState() => _BrokenDialogPageState();
}

class _BrokenDialogPageState extends State<BrokenDialogPage> {
  // One TextEditingController for each form input:
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Broken iOS Dialog"),
      ),
      body: Container(
        child: Padding(
          padding: const EdgeInsets.symmetric(
            vertical: 8.0,
            horizontal: 32.0,
          ),
          child: Column(
            children: [
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: Builder(
                  builder: (context) {
                    return RaisedButton(
                      onPressed: () {
                        showDialog<bool>(
                          context: context,
                          builder: (context) {
                            return CupertinoAlertDialog(
                              title: Text('Broken Dialog'),
                              content: Card(
                                color: Colors.transparent,
                                elevation: 0.0,
                                child: Column(
                                  children: <Widget>[
                                    CupertinoTextField(
                                      placeholder: "Enter a value.",
                                    ),
                                  ],
                                ),
                              ),
                              actions: <Widget>[
                                CupertinoDialogAction(
                                  isDefaultAction: true,
                                  child: Text("Yes"),
                                ),
                                CupertinoDialogAction(
                                  child: Text("No"),
                                )
                              ],
                            );
                          },
                        );
                      },
                      child: Text('Submit'),
                    );
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

## Logs

[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale
    en-GB)
    • Flutter version 1.9.1+hotfix.2 at /Users/anthonyswift/Library/Flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/anthonyswift/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        •
      android-x86 • Android 9 (API 28) (emulator)
    • iPhone 11 Pro Max         • 688E704F-25B2-4394-8693-B26F279CC9B8 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!

**Comment by escamoteur** [comment]
Hi, could you please try it with the beta channel?
Which I ios version are you using?
Does it work on a physical device?

**Comment by AntSwift** [comment]
The issue is present in the beta channel using iOS 13.0 (17A577a).

I will test on a physical device later today and get back to you. This would make testing a problem but would at least be workable.

**Comment by escamoteur** [comment]
I would also recommend to switch to ios 13.1
Have you tried if master is different?

**Comment by AntSwift** [comment]
I have tested on iOS 7 and it works correctly.

I'm still waiting for an activation key from Apple to test on really device.

**Comment by iapicca** [comment]
Hi @AntSwift 
if the issue persist with the latest stable version of flutter
could you please provide your updated `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
