### ISSUE TITLE
BottomNaviagation onTap open DFPAdBanner click url

### ISSUE THREAD

**Issue by besho** [flutter/flutter#41571]
I have a big issue that my app has BottomNaviagation and once i tapped on any item and the current Widget has DFPAdBanner under the BottomNaviagation, the new Widget open and the click url of ads opened. this issue happened on iOS devices only. 

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by BondarenkoStas** [comment]
@besho On which iOS did you test it? Please provide your `flutter doctor -v`, and a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by besho** [comment]
Thank you BondarenkoStas.

I used the default BottomNavigationBar. Also i used this library "https://pub.dev/packages/flutter_google_ad_manager" to use DFPBanner on my App. on each widget item, i have DFPBanner below the content of the widget. when i tap on any bottomNavigation tap, and the AdBanner partially appear and partially under the bottomNaviagtion, the Ad 's click url opened.

I tried to use cutom library for BottomNavigationBar but the same issue. Also i tried to add buttons on Row as BottomNavigationBar and i got same issue.

Below are the flutter doctor output:-
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G84, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/Developer/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/Sarmady/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Users/Sarmady/Documents/Xcodes/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (2 available)
    • iPhone • 57cd6af531045db3609d24a92f5bc375e0ac048d • ios • iOS 12.3.1
    • iPhone 6         • FD909885-CB4E-4B5C-AE71-304AC3ED9475     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!

**Comment by besho** [comment]
![70477382_511504772749182_8272576336057335808_n](https://user-images.githubusercontent.com/4993354/65835648-2f47c200-e2e9-11e9-9e85-1613b49d9bbf.jpg)

**Comment by besho** [comment]
I attached a screenshot of my BottomNavigationBar and as you see part of DFPBanner appears on the screen. if i select the second,third or fourth tab, i got the issue

**Comment by goderbauer** [comment]
This may be an issue with the package you're using. Maybe file an issue at https://github.com/ko2ic/flutter_google_ad_manager for it?

**Comment by iapicca** [comment]
Hi @besho 
if the issue persist with the latest stable version of flutter
could you please provide your updated `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @besho 
if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
