### ISSUE TITLE
Drag Target onWillReject method

### ISSUE THREAD

**Issue by mngkvn** [flutter/flutter#41581]
## Use case
Changing the background color `onWillAccept` method will only change the background
color if the draggable that's being dragged has the correct value. 

If the draggable doesn't have the correct value, it will not change the background color.

### Start
![start](https://user-images.githubusercontent.com/16860484/65838311-876dcc80-e2c7-11e9-9868-0ee1375f926f.png)

### Correct `onWillAccept` Hover
![hover](https://user-images.githubusercontent.com/16860484/65838345-c1d76980-e2c7-11e9-9b04-936a7242118d.png)

### Invalid Data Hover
![no effect](https://user-images.githubusercontent.com/16860484/65838362-f5b28f00-e2c7-11e9-864f-506e43500823.png)

As seen in the third picture, the gray background color did not apply because it was not the expected data being dragged into it. 

I wanted to add a default hover background color change effect on all my drag targets that
do not rely on the value it's accepting or an `onWillReject` method to add the effect.

## Proposal
Add an `onWillReject` method.

**Comment by pedromassangocode** [comment]
Hi @mngkvn 
I believe the [onLeave](https://api.flutter.dev/flutter/widgets/DragTarget/onLeave.html) callback may work for this use case (I haven't tried it though).
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by mngkvn** [comment]
I paused my project for a bit but i already tried your suggestion before and it didn't work.


Sent from my iPhone

On Mar 12, 2021, at 8:08 AM, Pedro Massango ***@***.***> wrote:

﻿

Closed #41581<https://github.com/flutter/flutter/issues/41581>.
