### ISSUE TITLE
[cloud_firestore] How to run Transaction update on a field inside array of the document 

### ISSUE THREAD

**Issue by bbvDeveloper** [flutter/flutter#41582]
I know I can do this on the top level field of the document. But I'm trying to run a transaction update on a field inside of the array of the document. 

My 'quiz' document is structured:

```
{
  title: '123',
  questions: [
    {
      title: 'question1',
      answers: [
        {
          title: 'answer1',
          votes: 0
        }
      ]
    }
  ]
}
```

And here is the code that I'm working with:

```dart
    final DocumentReference postRef = Firestore.instance.document('quizes/' + id);
    Firestore.instance.runTransaction((Transaction tx) async {
      DocumentSnapshot postSnapshot = await tx.get(postRef);
      if (postSnapshot.exists) {
        await tx.update(postRef, <String, dynamic>{'questions[0].answers[0].votes': postSnapshot.data['questions'][0]["answers"][0]["votes"] + 1});
      }
    }); 
```

**Comment by janmoppel** [comment]
Hello @bbvDeveloper !

Thank you for posting.

However, your question seems to be a better fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) than here. Flutter has a very active and helpful community there, so feel free to post it there.

Also, see other support options here: https://flutter.dev/community

Closing this ticket, as this is not an issue report.

**Comment by kroikie** [comment]
@bbvDeveloper

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/324. Any further collaboration will be done there.
