### ISSUE TITLE
APK updates are not "sticky"

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4158]
## Repro
1. Run your app with "Run" from Atom (it works)
2. Change some text in your app
3. Run from Atom again (it works)
4. Kill the app on Android.
5. Restart it from Android.
6. You'll see the text from number 1 again.
7. Uninstall the app from the device
8. Reinstall with flutter run.
9. Still shows the old text from number 1.

jsimmons explained that step 3 downloaded an updated .flx file to the device in the tmp directory and ran that file. This tmp file is not removed by step 7.

It appears that the .flx file is sometimes being used when it is old (step 9) and sometimes not being used when it should be (step 6).
## Recommendation

Jason recommended doing `flutter build apk` and then installing that. Perhaps as an initial fix, this procedure needs to be documented and this command needs to Atom as a Full Rebuild command (@devoncarew)

As a longer term fix, this process needs to be more predictable and reliable.

**Comment by Hixie** [comment]
I haven't seen this in a long time, so I'm going to close this as resolved. Please reopen if you still see it.
