### ISSUE TITLE
Firestore Calculations not working

### ISSUE THREAD

**Issue by ThomasValois** [flutter/flutter#41597]
### Objective
I've got a Firestore app that logs items and their value in a document. I want to return the "Value" field of all those documents and calculate the total value of all of them (add them up).

### Issue
When I use the below line of code, it just prints the values one by one (see screenshot attached). I've also attached a screenshot of my Firestore structure. I've tried using sum and sum2 but both return the same result.

```
 var getValueSTRING = documentSnapshot['Value'];
 var one = int.parse(getValueSTRING);
 var sum = [values].reduce((curr, next) => curr + next);
 var sum2 = list2.fold(0, (curr, next) => curr + next);
 print(sum); 
```
### Results Produced

```
Reloaded 3 of 579 libraries in 446ms.
I/flutter ( 3161): [100]
I/flutter ( 3161): [200]
```

![Firetore Structure](https://user-images.githubusercontent.com/47246858/65860819-f0eee900-e362-11e9-88a8-f45e1dbe9a69.png)

**Comment by BondarenkoStas** [comment]
@ThomasValois Please provide your `flutter doctor -v` output and specify which version of cloud_firestore you use.

**Comment by ThomasValois** [comment]
Apologies I had completely forgotten! My development details are below:

### Pubspec

- `firebase_core: 0.4.0+9`
- `firebase_analytics: 5.0.1`
- `cloud_firestore: 0.12.9+3`

### Channel
- Master channel

### Flutter Doctor

```
Try the new cross-platform PowerShell https://aka.ms/pscore6
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\tvalois\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by kroikie** [comment]
@ThomasValois

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1198. Any further collaboration will be done there.
