### ISSUE TITLE
Webview scrollbar is appearing at random place when is pushed into navigator on iOS

### ISSUE THREAD

**Issue by Jasphere-Appsploration** [flutter/flutter#41592]
## Steps to Reproduce

1. Run the app with dart script as provided in https://gist.github.com/Jasphere-Appsploration/2666e31b20581c2fb8c7c95be6567cb9
2. Tap on the button "Go to next screen"
3. Scroll the webview when it is loaded
4. The scrollbar will appear at random X position across the screen.

Note: This behaviour only happens on iOS devices with iOS version 13.1 (I do not have the chance to try on iOS 13)

```
[✓] Flutter (Channel master, v1.10.7-pre.77, on Mac OS X 10.14.6 18G103, locale en-MY)
    • Flutter version 1.10.7-pre.77 at /Users/jaspherelee/Desktop/Application/flutter
    • Framework revision 69af9adeac (8 hours ago), 2019-09-29 13:01:33 -0700
    • Engine revision 5b952f286f
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 6ff8d2199d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jaspherelee/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (2 available)
    • SM G960F • 2208229a21017ece                         • android-arm64 • Android 8.0.0 (API 26)
    • iPhone   • 54450a47f970529a18dbd35d22e5c558f062b51d • ios           • iOS 13.1

• No issues found!
```

**Comment by Jasphere-Appsploration** [comment]
Update: The issue seems only happen in notched iOS device. Tested on iPhone 6S and iPhone 8 both do not have this issue.

Update 2: Add in the screen capture for the issue 

![webview_scrollbar](https://user-images.githubusercontent.com/25500437/65849017-33242480-e37b-11e9-97b5-171c350f8f32.gif)

**Comment by najeira** [comment]
Since it also occurred in the Twitter app, there is a possibility of iOS trouble instead of Flutter.

**Comment by Jasphere-Appsploration** [comment]
Any update on this? There are some fixes I need for the webview but the newer release have this scrollbar issue and I can't release my app!

**Comment by geniusmart** [comment]
I also found this question

<img width="370" alt="1111111" src="https://user-images.githubusercontent.com/7712056/66726549-9da18e00-ee6c-11e9-94d8-a484ab8e0a94.png">

**Comment by Jasphere-Appsploration** [comment]
@janmoppel  Any update on this?

**Comment by ZhangDubhe** [comment]
Any update on this?

**Comment by ixuesen** [comment]
我也出现了这个问题

**Comment by Poplipo** [comment]
We found a workaround by implementing a custom PageRoute with a different animation: 

```
class FadeAnimationMaterialPageRoute<T> extends MaterialPageRoute<T> {
  FadeAnimationMaterialPageRoute({
    @required WidgetBuilder builder,    
  }) : super(builder: builder,);

  @override
  Widget buildTransitions(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {    
    return FadeUpwardsPageTransitionsBuilder().buildTransitions(this, context, animation, secondaryAnimation, child);    
  }
}
```

If you use this class instead of `MaterialPageRoute` in `Navigator.push`, you don't get the randomly positioned scrollbar.

**Comment by SpiciedCrab** [comment]
The same question, while the WebView is not the first page of the app, the scrollBar will appear at the random place.
So the Demo app works correctly, but if we change the first page and add a button to navigate to the WebView, the problem appears.

**Comment by Jasphere-Appsploration** [comment]
> class FadeAnimationMaterialPageRoute<T> extends MaterialPageRoute<T> {
>   FadeAnimationMaterialPageRoute({
>     @required WidgetBuilder builder,    
>   }) : super(builder: builder,);
> 
>   @override
>   Widget buildTransitions(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {    
>     return FadeUpwardsPageTransitionsBuilder().buildTransitions(this, context, animation, secondaryAnimation, child);    
>   }
> }

I tried but the edge swipe to back gesture stop working when using this page route class.

**Comment by vurvn** [comment]
i got the same this issue. It looks pretty weird.

**Comment by cj1128** [comment]
Any update? We really need a fix or a workaround.

**Comment by jaweii** [comment]
Same here.

**Comment by petermnt** [comment]
We were running into the problem and we managed to 'fix' it by wrapping the `WebView` into a `ClipRect`. A `Translate` with a non-zero offset also fixed it.
I hope this information is helpful for finding a fix.

**Comment by Serlight** [comment]
any update on this？

**Comment by Jasphere-Appsploration** [comment]
> We were running into the problem and we managed to 'fix' it by wrapping the `WebView` into a `ClipRect`. A `Translate` with a non-zero offset also fixed it.
> I hope this information is helpful for finding a fix.

Nope I tried but I can't get the scrollbar to appear at the correct place.
@cyanglaz This will be fixed in June 2020? Thats another half year ahead, and our app cannot release just because of this!

**Comment by zhpoo** [comment]
any update on this？

**Comment by pizzalbj** [comment]
You can fix it by using PopupRoute, bug will lose some features of MaterialPageRoute.
[https://github.com/pizzalbj/flutter_demo_new/blob/master/lib/custom_route.dart](url)
use PopRoute to test your code

**Comment by allonli** [comment]
The hero to solve the problem, but pr has not been closed.
  
```
webview_flutter:
    git:
      url: git://github.com/cyanglaz/plugins.git
      path: packages/webview_flutter
      ref: webview_scrollbar_issue
```

**Comment by SournVisal** [comment]
**ClipRect(
  child: Align(
                alignment: Alignment.bottomRight,
                child: WebView(
                  initialUrl: widget.url,
                  javascriptMode: JavascriptMode.unrestricted,
                  onPageFinished: (_) {
                    setState(() {
                      isLoading = false;
                    });
                  },
                  
                ),
              ),
            ),**

This one work for me. and hope work for others too.

**Comment by ashamp** [comment]
just delay the load to fix this


    import 'package:flutter/cupertino.dart';
    import 'package:flutter/material.dart';
    import 'package:webview_flutter/webview_flutter.dart';

    class WebViewPage extends StatefulWidget {
      final String url;
      final String title;

      WebViewPage(this.url, this.title);

      @override
      State<StatefulWidget> createState() => new WebViewPageState();
    }

    class WebViewPageState extends State<WebViewPage> {
      String url;

      @override
      void initState() {
        super.initState();
        Future.delayed(const Duration(milliseconds: 500), () {
          setState(() {
            url = widget.url;
          });
        });
      }

      @override
      Widget build(BuildContext context) {
        Widget view = Container();
        if (url != null) {
          view = WebView(
            initialUrl: widget.url,
            javascriptMode: JavascriptMode.unrestricted,
            onPageFinished: (_) {},
          );
        }
        return Scaffold(
          appBar: AppBar(),
          body: view,
        );
      }
    }

**Comment by GermanHernandez91** [comment]
Any update on this? I tried everything you wrote but it doesn't work.

**Comment by cyanglaz** [comment]
This is fixed with https://github.com/flutter/plugins/pull/2343.
Please try webview_flutter in 0.3.19+4.
If you see some issue with the SafeArea after applying the patch, you can add a SafeArea widget around the WebView widget.

**Comment by gilescm** [comment]
[This](https://github.com/flutter/flutter/issues/41592#issuecomment-573261075) worked for me, thank you!
