### ISSUE TITLE
image_picker first time not working .

### ISSUE THREAD

**Issue by nguyenlinhnttu** [flutter/flutter#41598]
## Steps to Reproduce

1. I use image_picker: ^0.6.1+4 but problem in first time request permission i have accepted, but image picker not work i can't open gallery/camera
2. But i close app and reopen:  image_picker work normal.
3. Don't have error in logcat.

My Code please have a look.
```
  var file = await ImagePicker.pickImage(
      source: source,
    );
    if (file != null) {
      var croppedFile = await Navigator.push(
          context, SlideLeftRoute(page: CropAvatarScreen(file)));
      setState(() {
        _croppedImageFile = croppedFile;
        _avatarType = AvatarType.other;
      });
    }
```

**Comment by SvenSchoene** [comment]
We are facing the exact same issue.  

Looking at the logs I get the following error:

```
FileSystemException: Cannot open file, path = '/storage/emulated/0/Download/feature_wheel_opt.png'
      // (OS Error: Permission denied, errno = 13)
```

Glad we're not the only ones.

**Comment by iapicca** [comment]
Hi  @nguyenlinhnttu  and @SvenSchoene 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by Hixie** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by emadd** [comment]
Seeing this very issue.  It seems to only happen when you use the plugin for the first time and have been prompted to allow access to the camera/photo library.  Even though you approve the request, the dialog to select media or take a photo never appears until you try again.

Plugin version 0.6.2+3

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

**Comment by sulaysumaria** [comment]
Still happening

Plugin version: 0.6.3

flutter doctor:
```
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)
```

**Comment by MechMel** [comment]
I'm also experiencing this issue.
Plugin version: 0.6.3+4

flutter doctor:
`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.657], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.42.1)
[√] Connected device (1 available)

• No issues found!`

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by dmvvilela** [comment]
I have this problem but only on release installing the apk.. How could i log the error then???

**Comment by mointhedev** [comment]
Same issue. Has anybody found any solutions?

**Comment by yannainghtun-mk** [comment]
Same issue.
https://github.com/flutter/flutter/issues/74779

**Comment by intellect4all** [comment]
I am facing same issues, I don't know how to solve it
