### ISSUE TITLE
ideviceinfo returned an error:

### ISSUE THREAD

**Issue by mirantvolansys** [flutter/flutter#41593]
`ERROR: Could not connect to lockdownd, error code -17.`

Due to it, I could not run my application on a simulator or emulator.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.7-pre.78, on Mac OS X 10.14.6 18G95, locale
    en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
[✓] Android Studio (version 3.5)
[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Exception: ideviceinfo returned an error:
      ERROR: Could not connect to lockdownd, error code -17


! Doctor found issues in 1 category.
```

**Comment by janmoppel** [comment]
Hello @mirantvolansys !

Thank you for posting an issue.
Your problem has been already discussed in these threads: #37236, #36789.
 
Closing this issue, as solutions were proposed in different discussions. However, if they won't work for you, please feel free to open a new issue.

Thank you.

**Comment by monitork** [comment]
Check ..... Maybe you plugging a device.
You not trust your compute connect. 
Then it show error. 
Maybe you check on simulator. It work fine.
