### ISSUE TITLE
DraggableScrollableSheet with dynamic height

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#41599]
## Use case

When using a `DraggableScrollableSheet` with dynamic content, there's no way to set the `maxChildSize` parameter to the height of the `builder`'s content.
* If the data shown inside the widget is short, setting `maxChildSize` to `1.0` will show too much blank space when scrolled to the top.
* If the data shown inside the widget is long, setting `maxChildSize` to `0.5` will not show all the content inside the sheet.

## Proposal

Add a boolean parameter which:
* If `false`, the behavior will remain unchanged.
* If `true`, ignores the `maxChildSize` (could also assert/warn) and sets the max size of the widget to the extent of the content.
  * If there's a lot of content, the result will be the same as setting `maxChildSize` to `1.0`.
  * If there isn't too much content, the max size of the sheet will be the size of the content inside the sheet.

The behavior will be something similar to the `Column`'s `mainAxisSize` parameter when set to `MainAxisSize.min`.

cc/ @dnfield

**Comment by dnfield** [comment]
I believe you should be able to achieve this today using a notification listener, right?

**Comment by amitkot** [comment]
@dnfield 
I see how you can get the scroll position using the notification listener but how would you use it to _limit_ the size of the bottom sheet to that of the actual content, like setting `MainAxisSize.min` does for `Column`?

**Comment by dnfield** [comment]
Making this easier is probably a good idea.  I would expect though that this is achievable using a notification listener and maybe a layout builder of some sort.

**Comment by amitkot** [comment]
@dnfield 
This issue has resurfaced for a new feature I am implementing.

I have a ListView that sometimes fits the screen. If it fits - I want the bottom sheet to match it's size. Otherwise, I want it to be 0.8 of the full screen size and scrollable.

I tried following your suggestion with using a LayoutBuilder and a NotificationListener<DraggableScrollableNotification>.

The direction I was considering was querying the constraints provided by the LayoutBuilder and if the height is sufficient - returning a ListView directly (with shrinkWrap set to true).
If the height is insufficient - wrap the ListView with a DraggableScrollableNotification.

While implementing the two flows is easy, the problem I ran into was determining if the ListView can fit the height constraint provided by the LayoutBuilder.

Is there a way I can query the ListView for its expanded height? Would you suggest a different direction?

Thanks!

**Comment by bhaskar-nair2** [comment]
I have a similar issue where the `maxChildSize` is set to `min((allMoves.length, 1)` where `allMoves` is a variable from provider.
I can see the `allMoves` List update but the `maxChildSize` does not update. 

Would love to have a way to fit whatever content the `DraggableScrollableSheet`  has automatically

**Comment by MiguelSOliveira** [comment]
Having this same problem. Any workaround ? I don't really understand the solutions above.

**Comment by yacineblr** [comment]
I have the same need. Any news?

**Comment by LeLunZ** [comment]
Any news?

**Comment by BStudio-Sasha** [comment]
Any news?

**Comment by LeLunZ** [comment]
I have found a workaround :) 

Container -> DraggableScrollableSheet

Now, because we can’t change the DraggableScrollableSheet we change the container size. 

If your DraggableScrollableSheet size depends on dynamic child widgets, you can implement a NotificationListener or some kind of Notifier structure. (PublishSubject, BehaviourSubject etc.)
Then in the child we can get its size. With this site we notify the upper layers, and change the container size (which Wraps around DraggableScrollableSheet) accordingly.

**Comment by xitrum2306** [comment]
The same issue so Any update?

**Comment by sabetAI** [comment]
Jesus it's been almost two years...

**Comment by ziqq** [comment]
Any news?

**Comment by chimon2000** [comment]
Would definitely be good to get an update on this issue @eseidel

**Comment by harkairt** [comment]
Jumping in to raise visibility, this feature would be much appreciated in our app as well :)

**Comment by bartekpacia** [comment]
I also need this feature.

**Comment by GyuriMajercsik** [comment]
This would be really useful.

**Comment by VKBobyr** [comment]
I know this is a bit of a code dump, but I was able to achieve this by measuring the size of the child, calculating how big it is compared to the rest of the screen, and setting the size of the Draggable sheet.

Warning: very hacky
```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

Future<void> showAesDraggableBottomSheet({
  required BuildContext context,
  required AesDraggableBottomSheet sheet,
}) {
  return showModalBottomSheet(
    context: context,
    isScrollControlled: true,
    backgroundColor: Colors.transparent,
    builder: (c) => sheet,
  );
}

class AesDraggableBottomSheet extends HookWidget {
  final Widget child;
  final double childHeightPercentage;
  final EdgeInsets padding;
  final Color bgColor;

  AesDraggableBottomSheet({
    required this.child,
    this.childHeightPercentage = 1,
    this.bgColor = Colors.white,
    this.padding = const EdgeInsets.only(
      top: 25,
      left: 15,
      right: 15,
    ),
  });

  @override
  Widget build(BuildContext context) {
    final height = useState(0.0);

    Widget makeDismissable({required Widget child}) => GestureDetector(
          behavior: HitTestBehavior.opaque,
          onTap: () => Navigator.of(context).pop(),
          child: GestureDetector(
            child: child,
            onTap: () {},
          ),
        );

    // used to measure child height
    final _child = SingleChildScrollView(
      child: MeasuredWidget(
        onCalculateSize: (v) => height.value = v!.height,
        child: child,
      ),
    );

    // calculate the proportion
    final maxSize = useMemoized(
      () => ((height.value + 50) / MediaQuery.of(context).size.height)
          .clamp(.1, .9),
      [height.value],
    );

    // for some reason initSize can't equal max size for very long widgets
    final initSize = maxSize * (childHeightPercentage - .0001);

    print("$maxSize $initSize");

    // render the child to get its height
    if (height.value == 0) {
      return _child;
    }

    // use the height to generate a bottom sheet
    return makeDismissable(
      child: DraggableScrollableSheet(
        maxChildSize: maxSize,
        minChildSize: initSize,
        initialChildSize: initSize,
        builder: (context, controller) {
          return Material(
            borderRadius: BorderRadius.circular(20),
            color: bgColor,
            child: ListView(
              padding: EdgeInsets.all(10),
              controller: controller,
              children: [_child],
            ),
          );
        },
      ),
    );
  }
}

class MeasuredWidget extends StatefulWidget {
  final Function(Size? size) onCalculateSize;
  final Widget child;

  const MeasuredWidget({
    Key? key,
    required this.onCalculateSize,
    required this.child,
  }) : super(key: key);

  @override
  _MeasuredWidgetState createState() => _MeasuredWidgetState();
}

class _MeasuredWidgetState extends State<MeasuredWidget> {
  final key = GlobalKey();

  @override
  initState() {
    //calling the getHeight Function after the Layout is Rendered
    WidgetsBinding.instance?.addPostFrameCallback((_) => getHeight());

    super.initState();
  }

  void getHeight() {
    final size = key.currentContext?.size;
    widget.onCalculateSize(size);
  }

  @override
  Widget build(BuildContext context) {
    return _MeasuredWidgetContent(
      key: key,
      child: widget.child,
    );
  }
}

class _MeasuredWidgetContent extends HookWidget {
  final Widget child;
  const _MeasuredWidgetContent({
    Key? key,
    required this.child,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return child;
  }
}
```

**Comment by hypesystem** [comment]
Just bumping this as it still seems relevant and like a nice feature :smile:

**Comment by caseycrogers** [comment]
> Just bumping this as it still seems relevant and like a nice feature 😄

I'll work on this this month and try to get a PR in soon! (it's related to my other PR https://github.com/flutter/flutter/pull/84394).

**Comment by MilesAdamson** [comment]
Are there any good workarounds for making the bottom sheet open to 80% of screen height, with a list view inside?

**Comment by caseycrogers** [comment]
Hey all, the PR is in! However, to clarify, this is what has changed: before there was a bug that made the sheet ignore any changes to it's inputs. With this PR, if you change any of the relevant parameters, the sheet will update to reflect the changes. For example, to dynamically size your sheet, you can get the height of the contents you wish to display inside of the sheet and then rebuild the sheet with `maxChildSize` set to be the exact height of your content.

This change should go into effect on branch stable in the next quarterly flutter release.
