### ISSUE TITLE
I have an issue when using firebase in my flutter app

### ISSUE THREAD

**Issue by Achintha444** [flutter/flutter#41595]
It throws the following error after I followed the exact instructions in the Firebase instructions.
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
* Error running Gradle:
ProcessException: Process "D:\ACA Folder\Flutter Basics\google_demo_4\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\ACA Folder\Flutter Basics\google_demo_4\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
  Command: D:\ACA Folder\Flutter Basics\google_demo_4\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.
Exited (sigterm)
```

**Comment by janmoppel** [comment]
Hello @Achintha444 !

Thank you for posting an issue.

Can you please provide additional information such as:
1) link to the instructions you mention;
2) the output of the same command you ran, but with a `--stacktrace` option;
3) the `flutter doctor -v` command output?

Your issue might be also related to the one here: #41350

Thank you.

**Comment by sarbagyastha** [comment]
`* Where:
Build file 'D:\ACA Folder\Flutter Basics\google_demo_4\android\app\build.gradle' line: 24`

This line suggests to look at line no. 24 of app-level build.gradle file.

**Comment by JosephineAkello** [comment]
@Achintha444 also, you could provide the steps on how the error came about, what did you add/ install to reproduce the error for proper follow up on what exactly happened. Otherwise, check line 24 of   
**app-level build.gradle file.** 
`Where: Build file 'D:\ACA Folder\Flutter Basics\google_demo_4\android\app\build.gradle' line: 24`  as stated by @sarbagyastha to see what went wrong.

**Comment by BondarenkoStas** [comment]
@Achintha444 it look very similar to https://github.com/flutter/flutter/issues/41492#issuecomment-536112970, can you please try and report if that will help?

**Comment by Achintha444** [comment]
> @Achintha444 it look very similar to [#41492 (comment)](https://github.com/flutter/flutter/issues/41492#issuecomment-536112970), can you please try and report if that will help?

Thank you @BondarenkoStas and everyone

I was trying to integrate firebase and google_sign_in packages to my app, after i changed my gradel files (both app/ and project) then this error poped up.

After I changed these lines,

```
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.41"
   }
```
and selecting Use androidx.* artifacts when creating a new project, solved my issue.

**Comment by touhidsunny** [comment]
in your project_name/android/build.gradle directory

Change the google services version:

```
dependencies {
    classpath 'com.android.tools.build:gradle:3.2.1'
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    classpath "com.google.gms:google-services:4.2.0"
}
```
