### ISSUE TITLE
[in_app_purchase] First run app products not purchased

### ISSUE THREAD

**Issue by strangerxx** [flutter/flutter#41600]
## Steps to Reproduce
I have implemented in-app purchases for example app and have added a non-consumable product in the Play Console. In first run on emulators products not purchased, but press Shift+R  products purchased.
![flutter_01](https://user-images.githubusercontent.com/985449/65869579-2eb83580-e394-11e9-8811-8246f39c0a0c.png)
![flutter_02](https://user-images.githubusercontent.com/985449/65869581-2f50cc00-e394-11e9-92da-c4e2010eb575.png)

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale ru_RU.UTF-8)
    • Flutter version 1.9.1+hotfix.2 at /home/icestranger/apps/flutter
    • Framework revision 2d2a1ffec9 (3 недели назад), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/icestranger/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/icestranger/apps/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/icestranger/apps/android-studio
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5540.11
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by strangerxx** [comment]
Problem in first run await _connection.queryPastPurchases() return empty list, but after few seconds return NOT empty list.

**Comment by sravanyakatta** [comment]
I am also facing the same issue in iOS. Implemented the same process of adding non-consumable product in the appstore connect and was able to buy it in sandbox environment.

But when trying to retrieve the purchased products, I am not receiving any product from queryPastPurchases().

**Comment by kondasoft** [comment]
Same issue here on iOS

**Comment by ilyasKerbal** [comment]
@kondasoft I am facing the same issue when I tape the buy button, the purchases list updates.

**Comment by tjviking** [comment]
we have same issues on IOS and sometimes on Android, empty list returned, after refresh it fetches real data - no exceptions, just empty list

**Comment by ilyasKerbal** [comment]
@tjviking The issue seems to take more time. I highly recommend you use the unofficial plugin and change it later. https://pub.dev/packages/flutter_inapp_purchase

**Comment by cielo** [comment]
@strangerxx Were you getting this problem in emulator or in a real device?

**Comment by strangerxx** [comment]
@cielo In emulator and in real device

**Comment by ilyasKerbal** [comment]
> @strangerxx Were you getting this problem in emulator or in a real device?

I have a production app on IOS with the same problem.

**Comment by cyanglaz** [comment]
@strangerxx Do you still have issues on Android? I just tried with the latest plugin it works on Android. (Haven't tried on iOS yet)
If anyone finds the issue still exist with the latest plugin, please share a sample `main.dart` with minimum code to reproduce the issue. It will speed up the debugging process.

**Comment by strangerxx** [comment]
@cyanglaz I use other plugin. I try and write

**Comment by alvinkonda** [comment]
I swtiched to https://pub.dev/packages/revenuecat and so far so good. I got accepted at iOS at first time.

**Comment by cyanglaz** [comment]
@sravanyakatta @alvinkonda @ilyasKerbal Do you guys still face the issue? Would you mind sharing a sample `main.dart` to reproduce the issue?

**Comment by cyanglaz** [comment]
@alvinkonda @strangerxx Ah okay! Thanks for letting us know!

**Comment by strangerxx** [comment]
> @alvinkonda @strangerxx Ah okay! Thanks for letting us know!

Yes, fix the issue. Thanks.

**Comment by alvinkonda** [comment]
the issue is not fixed, i just switched to a third party for my IAP.

**Comment by strangerxx** [comment]
@alvinkonda Sorry, I did not write to you. Fixed comment.
