### ISSUE TITLE
android_alarm_manager issue

### ISSUE THREAD

**Issue by Mallika-Tung** [flutter/flutter#41608]
I am getting these issue in flutter application.

```
E/AlarmService(  682): Fatal: failed to find callback
D/ActivityThread(  682): SVC-Calling onStartCommand: io.flutter.plugins.androidalarmmanager.AlarmService@dbcdd52, flags=0, startId=1
I/AlarmService(  682): AlarmService has not yet started.
```
My code is 
```
import 'dart:isolate';
import 'package:flutter/material.dart';
import 'package:toast/toast.dart';
import 'package:android_alarm_manager/android_alarm_manager.dart';




void printHello() {
  final DateTime now = new DateTime.now();
  final int isolateId = Isolate.current.hashCode;
  print("HELLOW HELLOW----");
 // print("[$now] Hello, world! isolate=${isolateId}
    //  function='$printHello'");
  print("[$now] Hello, world! isolate=${isolateId} function='$printHello'");
  }

void main() async {
  final int helloAlarmID = 0;
  await AndroidAlarmManager.initialize();
  runApp(MaterialApp(home: Application()));
}

class Application extends StatelessWidget {
  @override
  Widget build(BuildContext context) {

    print("Callback called");
    return Scaffold(
      body: Container(
        child: Center(
          child: RaisedButton(
            child: Text('Hello'),
            onPressed: () {
              runAlarm(context);
            },
          ),
        ),
      ),
    );
  }
  void runAlarm(BuildContext context) {
    AndroidAlarmManager.periodic(
      Duration(seconds: 4),
      0,
      printHello,
      wakeup: true,
    ).then((val) {
      print('alartCalled $val');
      Toast.show("Toast plugin app", context, duration: Toast.LENGTH_SHORT, gravity:  Toast.BOTTOM);
    });
  }

  static void alarmTest() {
    print("test");
  }
}

```

**Comment by BondarenkoStas** [comment]
@Mallika-Tung On which device/emulator do you run it? What the command? Which version of android_alarm_manager? Please provide your flutter doctor -v output.

**Comment by Mallika-Tung** [comment]
android@android:~/Documents/Mallika_Flutter_project/Charge_To_Go/charge2go$ flutter doctor -v output
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_IN)
    • Flutter version 1.7.8+hotfix.4 at /home/android/Documents/flutter
    • Framework revision 20e59316b8 (2 months ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/android/Documents/AndroidStudio/sdk
    • Android NDK at /home/android/Documents/AndroidStudio/sdk/ndk-bundle
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /snap/android-studio/78/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/78/android-studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Android Studio (version 3.2)
    • Android Studio at /home/android/Documents/ajit_jswl/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Redmi 5 • 35ca07997ce5 • android-arm64 • Android 7.1.2 (API 25)
============================================
E/AlarmService(13104): Fatal: failed to find callback
I/AlarmService(13104): AlarmService has not yet started.

**Comment by BondarenkoStas** [comment]
@Mallika-Tung On which device/emulator do you run it? What the command? Which version of android_alarm_manager?

**Comment by Mallika-Tung** [comment]
Hi..
I am using MI note 5 pro
alerm manager version is      android_alarm_manager: ^0.4.4
I want to trigger the alerm manager code by button click.

**Comment by stuartmorgan** [comment]
Closing as `android_alarm_manager` is deprecated in favor of [`android_alarm_manager_plus`](https://pub.dev/packages/android_alarm_manager_plus).
