### ISSUE TITLE
[google_maps_flutter] inside Stack requires double-tab to drag/zoom etc.

### ISSUE THREAD

**Issue by overgaardmorten** [flutter/flutter#41616]
When using [google_maps_flutter] inside Stack with other widgets on top of the Map you have to tap twice on Google Map to be able to drag/zoom etc. 

Steps to reproduce:
1) Create Stack with google Map and one positioned button
2) Click button
3) Drag anywhere in Google map just after clicking button -> no dragging occurs. You will have to double-tap on Google map to drag.

Flutter Doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.6, on Mac OS X 10.14.6 18G95, locale en-DK)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[!] VS Code (version 1.38.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

**Comment by iapicca** [comment]
Hi @overgaardmorten 
could you please provide your `flutter run --verbose` and 
a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
