### ISSUE TITLE
[web] Uncaught TypeError: J.b6(...).Bx is not a function

### ISSUE THREAD

**Issue by jkmosa01** [flutter/flutter#41614]
## Steps to Reproduce
I can run the application in debug mode, and I can build the application successfully. However, when I try to run the built application, I get two errors:
Uncaught TypeError: J.b6(...).Bx is not a function
Uncaught TypeError: Cannot read property '$3' of null

I am using the following packages:
  intl: ^0.16.0
  js: ^0.6.1+1

```
flutter doctor -v
[✓] Flutter (Channel master, v1.10.7-pre.78, on Mac OS X 10.14.4 18E226, locale
    en-US)
    • Flutter version 1.10.7-pre.78 at
      ~/Desktop/Developing/Flutter/flutter
    • Framework revision 839fdbd2ed (11 hours ago), 2019-09-29 21:32:06 -0700
    • Engine revision 5b952f286f
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 6ff8d2199d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at ~/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: ~/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at ~/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android
      Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at ~/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270

[✓] Connected device (3 available)
    • macOS  • macOS  • darwin-x64     • Mac OS X 10.14.4 18E226
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by jonahwilliams** [comment]
Please include an example that reproduces the issue (see https://stackoverflow.com/help/minimal-reproducible-example for some guidance on how to create one).

**Comment by Ahmadre** [comment]
Same issue here! On my side the error is produced by line: 37535 in main.dart.js by ```t1 = element.style;``` in following function:

```js
setElementStyle$3: function(element, $name, value) {
      var t1;
      if (value == null)
        element.style.removeProperty($name);
      else {
        t1 = element.style;
        C.CssStyleDeclaration_methods._setPropertyHelper$3(t1, (t1 && C.CssStyleDeclaration_methods)._browserPropertyName$1(t1, $name), value, null);
      }
    },
```

I can't build a release or profile build! No builds are working now! on every branch: dev & master!

**Comment by jkmosa01** [comment]
Hi, I have figured out what was causing my problem.
I was accessing localStorage through package:js, and had the following code:
```
@JS()
library storage;

import 'package:js/js.dart';

external Storage get localStorage;

@JS()
class Storage {
  external dynamic getItem(String key);
  external void setItem(String key, dynamic item);
  external void removeItem(String key);
  external void clear();
}
```

This was causing errors when I built the app in release mode for web, but no errors when it was in debug mode. After changing the code to what it is below, I had no more errors. 
```
@JS("localStorage")
library storage;

import 'package:js/js.dart';

@JS("getItem")
external dynamic getItem(String key);
@JS("setItem")
external void setItem(String key, dynamic item);
```

**Comment by natebosch** [comment]
We should definitely explore why it worked in DDC.

It looks like you may be missing an `@JS()` annotation on the `external Storage get localStorage;`. Does adding that solve the problem with the original pattern?

**Comment by natebosch** [comment]
I'm not able to reproduce the failure with dart2js and the `localStorage` example... Does anyone have a minimal consistent repro?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by yjbanov** [comment]
Speaking of `localStorage`, we just added Web support to the [shared_preferences](https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences_web) plugin, which uses `localStorage` on the Web. Your feedback would be most welcome.
