### ISSUE TITLE
[image_picker] Report Permissions Status

### ISSUE THREAD

**Issue by raphFlash** [flutter/flutter#41615]
## Use case

The image_picker plugin handle very well the process of asking the permission to take a photo or choose from gallery but if the user refuse the permission, there no way to know that. Without additional code, the user could think that the app is unresponsive of broken.
It would be nice to know if the user refused a permission to show him some information or redirect to the settings.
I know there are others plugins that can do that but i think every app that use this plugin should handle the case of a refusal, so this should be included in this plugin.

## Proposal

A method to know the status of the permission (don't know / approved / refused)
A method to redirect the user to the settings

**Comment by escamoteur** [comment]
Even an Exception if it was denied would be fine.

**Comment by JayM96** [comment]
Why flutter image picker doesn't require android permissions for capturing gallery or camera photos. While it requires permissions for iOS part?

**Comment by darshankawar** [comment]
Verified this issue using [latest](https://pub.dev/packages/image_picker/install) `image_picker` plugin version on Android and iOS and noticed that, after denying permission, the app shows message on screen, as expected.

<img width="340" alt="Screenshot 2021-02-10 at 6 11 17 PM" src="https://user-images.githubusercontent.com/67046386/107511384-6ca1ac80-6bcb-11eb-96ca-06e696801ca2.png">
<img width="344" alt="Screenshot 2021-02-10 at 6 11 26 PM" src="https://user-images.githubusercontent.com/67046386/107511391-6e6b7000-6bcb-11eb-86b2-920430a2a06e.png">

<img width="337" alt="Screenshot 2021-02-10 at 6 02 07 PM" src="https://user-images.githubusercontent.com/67046386/107511411-76c3ab00-6bcb-11eb-93c9-1d392fa3ecdd.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64, locale
    en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • SM G975F (mobile)          • RZ8M802WY0X                          • android-arm64 •
      Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.

```

</details>

I believe this message is enough to know the status of the permission and indicates what the user need to do.
Closing this as fixed. If anybody disagrees, write in comments and I'll reopen it.
