### ISSUE TITLE
[iOS 13] how to set preferredStatusBarStyle dark content in dark mode?

### ISSUE THREAD

**Issue by jukqaz** [flutter/flutter#41611]
I can't apply set statusbar color with material app's brightness after iOS 13 updated.

how to set preferredStatusBarStyle dark content in dark mode?

**Comment by jukqaz** [comment]
[✓] Flutter (Channel dev, v1.10.6, on Mac OS X 10.15 19A573a, locale en-KR)
    • Flutter version 1.10.6 at /Users/hammyeongho/Dev/tools/flutter
    • Framework revision cc3ca9a916 (5 days ago), 2019-09-25 10:57:58 -0400
    • Engine revision 63949eb0fd
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 69b5681546)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/hammyeongho/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A419c
    • CocoaPods version 1.8.0.beta.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPhone Xs • 8F2740FE-0FA4-4A71-9D18-76F887E7C57E • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

**Comment by HansMuller** [comment]
It would help if you could provide  a small self-contained app that demonstrates the problem (it sounds like this is a regression?). Note also: https://gist.github.com/ is a useful way to share the code.

**Comment by jukqaz** [comment]
https://gist.github.com/cdd4b8addab5262de8b88af4dbce7869.git

**Comment by jukqaz** [comment]
[https://drive.google.com/open?id=1rJOle2ogKzbsaCZ9Hx-6iRL3ac-MQM-z](url)
i want to set dark content in status bar, when material app set brightness light

**Comment by LongCatIsLooong** [comment]
This seems to be a dup of https://github.com/flutter/flutter/issues/41067.

**Comment by FineTillYouCameAlong** [comment]
Did you figure this out?

**Comment by CoderCqb** [comment]
I also encountered the same problem as you. The official Flutter version is Flutter 1.12.13 + hotfix.8. • Channel stable does not adapt to iOS13 Dark Mode. If you want to change the color of the status bar in Dark mode on iOS13, you need to wait until the Flutter page is loaded and rendered, and then go to the iOS native bridge through the MethodChannel to modify it. It is OK. Listen in the main.dart file: if (Platform .isIOS) {
    WidgetsBinding.instance.addPostFrameCallback (_setupStatusBarStyle);
    }, The initial initialization setting needs to add a 1.0 second delay operation in iOS native, set in the delay function, if (@available (iOS 13.0, *)) {
                                   [UIApplication sharedApplication] .statusBarStyle = UIStatusBarStyleDarkContent;
                                } else {
                                   [UIApplication sharedApplication] .statusBarStyle = UIStatusBarStyleDefault;
                                } And then in Flutter
You can set the color of the status bar arbitrarily through the MethodChannel during the project operation.
