### ISSUE TITLE
Android 10 - Permission Denied

### ISSUE THREAD

**Issue by malikdoksoz** [flutter/flutter#41613]
**I gave all the permissions. [READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE] But I get an error viewing the photo from the gallery.**

My Build gradle.
compileSdkVersion 29
targetSdkVersion 29

`
════════ Exception caught by image resource service ════════════════════════════
The following FileSystemException was thrown resolving an image codec:
Cannot open file, path = '/storage/emulated/0/DCIM/Camera/IMG_20190930_174210.jpg' (OS Error: Permission denied, errno = 13)

When the exception was thrown, this was the stack
#0      _File.open.<anonymous closure>  (dart:io/file_impl.dart:364:9)
(elided 13 frames from package dart:async)
Path: /storage/emulated/0/DCIM/Camera/IMG_20190930_174210.jpg`

`[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G103, locale
    tr-TR)
    • Flutter version 1.9.1+hotfix.2 at /Dosyalar/flutter_src/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/malikdoksoz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 10
      (API 29) (emulator)

• No issues found!`

<img width="1184" alt="Ekran Resmi 2019-09-30 18 06 39" src="https://user-images.githubusercontent.com/26676061/65891755-bfe7d600-e3ad-11e9-8724-90d508625ce6.png">

**Comment by malikdoksoz** [comment]
I solved the problem by changing the version. **targetSdkVersion 28**

**Comment by moovida** [comment]
I am not sure why this has been closed. It seems that from version 10 of Android, using target platform > 28 there are issues accessing the storage even if all permissions have been granted. 
Is there an explanation for this?

**Comment by kw2019ltd** [comment]
yes same issue with andriod 10 ,

E/flutter (32365): FileSystemException: Directory listing failed, path = '/storage/emulated/0/Download/' (OS Error: Permission denied, errno = 13)

**Comment by kw2019ltd** [comment]
https://developer.android.com/about/versions/10/behavior-changes-10
