### ISSUE TITLE
Add support for custom http connections to NetworkImage

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4162]
https connections made with oauth2 require special behavior:
- They require a custom "Authorization" header.
- They require the client to get a new Access Token every so often, as indicated by this example:

```
   HTTP/1.1 401 Unauthorized
   WWW-Authenticate: Bearer realm="example",
                     error="invalid_token",
                     error_description="The access token expired"
```

There appears to be no way to plumb through either of these.

One solution is to pass in a factory to create the `HttpClient`. This factory could also set the required headers in `HttpClientRequest`.

**Comment by Hixie** [comment]
You can provide your own HttpClient now.
