### ISSUE TITLE
Cache size for NetworkImage is unbounded

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4163]
Need a way to control the caching behavior of NetworkImage.

Closely related to https://github.com/flutter/flutter/issues/3568.

**Comment by Hixie** [comment]
There's no cache specific to NetworkImage. The regular image asset cache is capped at 1000 entries. There's a specific bug about making it respond to memory pressure, #3006.

I'm closing this since it seems unactionable.
