### ISSUE TITLE
[web] Support form field auto-fill

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#41634]
Browsers have a form auto-fill feature that works with DOM input elements. We should make it work with Flutter text fields.

**Comment by GregorySech** [comment]
Related to https://github.com/flutter/flutter/issues/13015

**Comment by nturgut** [comment]
Main part of the implementation is completed in this PR: https://github.com/flutter/engine/pull/17986

**Comment by nturgut** [comment]
Autofill can be used in most browsers (Names in Firefox and Credit card information in Safari needs more investigation)

I'll create other issues for remaining tasks:

- Looks like Safari needs label attributes for payment information to autofill. Add those. Safari also uses different than the standard web autofill hints, add a map for them.
- Firefox uses fname/lname for setting name, but chrome uses name field. Make name field work in a way easier for developers to use (now they have to add and if/else)
- Integration tests: Add form submit after flutter/flutter#55613 is resolved (which will provide an action which will send all the key-values of autofill fields back to the engine). Currently the developers can collect all the fields on flutter side and send a http post request. However the mapping of RequestData to hints web expects needs to be done manual
