### ISSUE TITLE
[web] Support various keyboard types

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#41635]
Flutter's text fields have input types that control what type of keyboard shows up when the field receives focus. E.g. text, number, phone, email, date, etc.

**Comment by escamoteur** [comment]
How should that be supported in a normal browser on a desktop?

**Comment by mdebbar** [comment]
@escamoteur this will probably have no effect on desktop browsers. This issue is specifically about supporting different types of virtual keyboards on mobile browsers (e.g. numeric keyboard, plain text keyboard, email keyboard, date picker, etc).
