### ISSUE TITLE
Expose JavaScriptObject from dart:js

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#41649]
As a follow up to https://github.com/flutter/flutter/issues/35588, we need to expose one more class from `dart:js` - `JavaScriptObject`. That's defined is a private dart: library; that library will need to be added to the Flutter SDK as well (and land upstream in dart-lang/sdk, then in flutter/engine, then in here as a test verifying the behavior).

**Comment by yjbanov** [comment]
@devoncarew Should we change the milestone to October/November and assign someone?

**Comment by devoncarew** [comment]
It's in progress (https://dart-review.googlesource.com/c/sdk/+/121462), but will take a few CLs to various repos.

**Comment by MichealReed** [comment]
@devoncarew seems web_audio was missed when html and js were added. Would you like me to open a new issue to cover?
