### ISSUE TITLE
[google_sign_in] A new version of the Google Sign-In iOS SDK is available

### ISSUE THREAD

**Issue by lookfirst** [flutter/flutter#41663]
`A new version of the Google Sign-In iOS SDK is available: https://developers.google.com/identity/sign-in/ios/release`

Seeing that in the console output. Using 4.0.7, which seems to be the latest on pub, even though it is says 4.0.9 in github. =(

**Comment by lookfirst** [comment]
@collinjackson

**Comment by escamoteur** [comment]
You have to differentiate between the version of the google SDK and the version of the flutter plugin.
I guess the Flutter team just haven't updated the flutter plugin to the latest version of the SDK.

Is this a problem at the moment for you?

**Comment by lookfirst** [comment]
@escamoteur I don't know if it is a problem or not and it doesn't really matter, it is a notice that was placed there for a reason. I don't even know what version was bundled with the 4.0.7 version of google_sign_in.

Does using an older version of the SDK prevent Google Sign In from working or expose us to a security hole?

**Comment by escamoteur** [comment]
No Idea honestly, best to ask this at the new  home for Firestore at https://github.com/FirebaseExtended/flutterfire and link this issue to it. Thanks

**Comment by lookfirst** [comment]
The problem is in google_sign_in, not in firebase. Please reopen.

**Comment by lookfirst** [comment]
https://github.com/flutter/plugins/blob/master/packages/google_sign_in/ios/google_sign_in.podspec#L18

**Comment by escamoteur** [comment]
Ah, sorry you are right.

**Comment by lookfirst** [comment]
Maybe someone can also explain why 4.0.8 and 4.0.9 isn't published to pub.

**Comment by jmagman** [comment]
This is being fixed in https://github.com/flutter/plugins/pull/2127.

**Comment by lookfirst** [comment]
@jmagman Great, thanks for a helpful response. Closing.
