### ISSUE TITLE
flutter logs includes W/ActivityManager lines but they're often not interesting

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4166]
I don't want to see stuff like:

```
W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=2906, uid=10085 that is not exported from uid 10065
```

**Comment by mit-mit** [comment]
Just hit this as a new Flutter user. It's very confusing when you see these errors the first time ever you run a Flutter app, as it leads you to think you have done something wrong, or the system is not working.

**Comment by sethladd** [comment]
Agreed. Thanks for the feedback here. Patches welcome! :)
