### ISSUE TITLE
Auto completion issue android studio.

### ISSUE THREAD

**Issue by VrajGohil** [flutter/flutter#41661]
## Steps to Reproduce

In android studio, auto completion while writing the code deletes some portion of code and puts some stray brackets, which causes error. So i undo one step and rewrite that particular line again.
Steps to reproduce:
1. ... type `Color: Colors.w`
2. ...press tab
3. ...messes up the code

## Logs

```
```

```
```

```
```

**Comment by janmoppel** [comment]
Hello @VrajGohil !

Thank you for posting.
Can you please attach the `flutter doctor -v` command output?

**Comment by VrajGohil** [comment]
╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


[√] Flutter (Channel master, v1.10.3-pre.39, on Microsoft Windows [Version 10.0.17134.1006], locale en-GB)
    • Flutter version 1.10.3-pre.39 at D:\flutter
    • Framework revision 0ef89bb969 (2 weeks ago), 2019-09-14 15:34:29 -0700
    • Engine revision 00c8941dae
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 a554c8be6b)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Vraj\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\Vraj\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] VS Code, 64-bit edition (version 1.28.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

**Comment by escamoteur** [comment]
Hi,

this is a problem of the Android Studio plugin. please File this issue here https://github.com/flutter/flutter-intellij
