### ISSUE TITLE
missing AssetImage after navigating using Hero

### ISSUE THREAD

**Issue by nbros** [flutter/flutter#41677]
I have a main page and a search page, each with a ListView containing Heroes that contain ImageAssets.
When filtering the search page so that it doesn't show the image and navigating back to the main page, the main page is missing all images that were not displayed on the search page.
In DevTools, for each missing image I see that the underlying RenderImage says "NEEDS-REPAINT" but it does not repaint, unless I scroll away and then back to this image.

```
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.387], locale fr-FR)
    • Flutter version 1.9.1+hotfix.2 at C:\dev\flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\dev\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\dev\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

```

**Comment by escamoteur** [comment]
Hi, thanks for reporting.

Have you tried if it works with the latest master channel?

Could you create a minimal repro project that shows this behaviour? This would make it much easier to look for the problem.

Thanks

**Comment by nbros** [comment]
Hello,

It works on the master channel.

Thanks
