### ISSUE TITLE
Disabling Multi-Touch/Drag with Gesture Detector

### ISSUE THREAD

**Issue by saxophonix** [flutter/flutter#41672]
Hi there,

Im currently building a Slider widget which multiple handle and am currently implementing the Gesture Detector. I am having an issue where if you touch the screen with a second finger it will be recognised by the detector which is what I am trying to disable. I understand there is a function in the Listener class which allows you to specify a device (using details.device) but is there a way to achieve this using the Gesture Detector class?

Cheers

**Comment by saxophonix** [comment]
Currently looking into different implementers for the Gesture Detector but if anyone could point me in the right direction that would be great - thanks.

**Comment by janmoppel** [comment]
Hello @saxophonix !

Thank you for posting.
Your question might be a better fit for the [StackOverflow](https://stackoverflow.com/tags/flutter). Flutter has a very active and helpful community there, so feel free to post it there too.

Also, see other support options here: https://flutter.dev/community

**Comment by escamoteur** [comment]
I agree with @janmoppel please ask on stackoverflow.

I leave this open because we may add this to the documentation and cookbook

**Comment by saxophonix** [comment]
Done, will leave the link here incase anyone comes across this with the same problem.

https://stackoverflow.com/q/58182007/12147590

**Comment by iapicca** [comment]
Hi @saxophonix 
given that you marked your SO question as [answered](https://stackoverflow.com/a/58307669)
I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
