### ISSUE TITLE
path_provider getLibraryDirectory() should be supported on Android

### ISSUE THREAD

**Issue by Al4han** [flutter/flutter#41685]
Maybe update the API reference to be explicit about not supporting this method on Android?

Could have saved me many hours debugging working code.

**Comment by BondarenkoStas** [comment]
will just reference it here #41683 to keep the context

**Comment by Al4han** [comment]
Well the problem isn't that the returned path changed, but that this method is not implemented for Android, while the documentation does not warn you.

From the [pub changelog-tab](https://pub.dev/packages/path_provider#-changelog-tab-):

> 1.3.0 
Added iOS-only support for getLibraryDirectory.

While the [API reference description says](https://pub.dev/documentation/path_provider/latest/path_provider/getLibraryDirectory.html):

> Path to the directory where application can store files that are persistent, backed up, and not visible to the user, such as sqlite.db.

For example the [API reference for getExternalStorageDirectory](https://pub.dev/documentation/path_provider/latest/path_provider/getExternalStorageDirectory.html) acknowledges:

> ... this functionality is only available on Android.

**Comment by valconetti** [comment]
This issue can be closed, since this method can't be supported on Android, and the [API reference description already mentions this](https://pub.dev/documentation/path_provider/latest/path_provider/getLibraryDirectory.html):

> On Android, this function throws an UnsupportedError as no equivalent path exists.

**Comment by amirh** [comment]
Closing per @valconetti comment above
