### ISSUE TITLE
path_provider getExternalStorageDirectory on android

### ISSUE THREAD

**Issue by aliyazdi75** [flutter/flutter#41683]
In the `path_provider 0.4.0`, `getExternalStorageDirectory()` on Android returned `/storage/emulated/0/` and we could access this path and directories but in the last version `path_provider 1.3.0`, `getExternalStorageDirectory()` on Android returns `/storage/emulated/0/Android/data/com.tarafdari.news/files`.

How can we access to `/storage/emulated/0/` path or `Download` directory path?

**Comment by BondarenkoStas** [comment]
The same issue #35783.

**Comment by vyalikvo2** [comment]
You can use a Third-party package ext_storage.
https://pub.dev/packages/ext_storage/versions

Code:
`await ExtStorage.getExternalStorageDirectory();`

returns **storage/emulated/0/**

P.S.
Sometimes you will have plugin compile error:
```
* What went wrong:
A problem occurred evaluating project ':ext_storage'.
> Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSetKt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
```
When you see this compile error you should change plugin build kotlin_version to version what you have in your Android Studio 
(also you need to update kotlin)
**Tools -> Kotlin -> Configure Kotlin Plugin Udpates**
I have this string there
"Current kotlin plugin version: 1.3.72-release-Studio4.0-5"
That means I have 1.3.72 kotlin version

At your **PLUGIN build.gradle file:**
change ext.kotlin_version parameter at `Flutter Plugins / ext_storage-v1.0.3  / android / build.gradle` file

```
buildscript {
    ext.kotlin_version = '1.3.72' // change to your current kotlin version
    repositories {
      ...
    }
    dependencies {
        ...
    }
}
```
