### ISSUE TITLE
too many ways to jank my project

### ISSUE THREAD

**Issue by rbucker** [flutter/flutter#41689]
## Steps to Reproduce

My ```flutter create myproject``` works great. But my project that I started developing for Android on a linux machine does not work on a mac for iPhone. I have been reading every post I can and I find all sorts of conflicting details.

So what I'm asking... Let's say I have one project, let's call it ALPHA and it works on android and does not work on mac.  So I create project BETA on mac and it does.  

NOW THE QUESTION.... what artifacts from ALPHA can I copy to BETA so that it works reliably?

OR... what s the real XCode, Android Studio, Flutter project configuration(s)?

Q: when do I need to add ENV['SWIFT_VERSION'] and which version should I be using?

Q: why is there a post_install version of the same?

Q: when uncomment the ios version flag and which version is ideal?

Q: the compiler warning from cocoa about the xcode flags that seem to override the podfile (debug, release, profile) that is described as CUSTOM?

Q: there seem to be other SDK tools that are not installed... which ones really matter?

MORE IMPORTANTLY... how do I set my project baseline so that it compiles and runs without tweaking?

## Logs

n/a

**Comment by BondarenkoStas** [comment]
@jonahwilliams Can you please help?

**Comment by escamoteur** [comment]
Could you please add the output of flutter doctor - v from you Linux and your Mac flutter Installation.

**Comment by jonahwilliams** [comment]
There are artifacts that do not work cross platform. These should be hidden via the .gitignore and not shared.

**Comment by rbucker** [comment]
@jonahwilliams .gitignore has nothing to do with gradle or not to gradle and similar tools.

**Comment by stuartmorgan** [comment]
The bug system is not a good place for discussion of a lot of different questions at once (many of which are unrelated).

You should not be copying a whole project between macOS and Linux, or sharing a directory between them in a dual-boot or VM setup, which is what Jonah was saying. You should instead use version control, and check out one copy on your macOS machine, and one on your Linux machine.

If you do that, then things should work fine building that project on different machines. If you try that and it's not working, please file one or more new bugs with specific issues, including detailed information about the steps you are doing and the errors you are seeing.

For general Q&A-style support, please use one of the more general-purpose communities listed at flutter.dev/communities.

**Comment by rbucker** [comment]
@stuartmorgan I COMPLETELY disagree with your interpretation. He said nothing of the sort. Neither did I. I am sharing my project thru git. And frankly, in a separate issue, it was recommended that I use beta or MASTER channel code. How is flutter ready production if that's the recommendation? How do I change my customer's mind that flutter is not ready for production.

ALSO there is nothing wrong with my question. I'm giving examples in the form of a question about topics that might be asked in separate issues, however, all are related to mac, iphone and cross architecture... the main selling points.

but feel free to close it. this is GREAT

**Comment by escamoteur** [comment]
@rbucker just to let you know the latest hotfix that was on beta is now the new stable. I only proposed trying master to see if it makes a difference to you.
You didn't post the 'flutter doctor' output from your Linux machine.

**Comment by rbucker** [comment]
generally speaking the out of the box experience has left a lot to be desired. In a conversation with the project owner we came to the same result. There are clearly some people who have been hovering in this area and I imagine they have success. I have different expectations from my tools. And now we are really going off topic.
