### ISSUE TITLE
Shadow can't be drawn over ListView/PageView

### ISSUE THREAD

**Issue by HerrNiklasRaab** [flutter/flutter#41690]
## Use case

The Problem is, that BoxShadows can't be drawn over a ListView or PageView. The screenshot below is describing my problem perfectly. The blue and the white cards, have shadows, but these shadows are getting clipped by the horizontal ListView below. After hours of research, it seems, that there is no way to allow the shadows to overflow the ListView.

## Proposal

Please add a Setting or a Widget, which allows thes shadows to overflow the ListView/PageView.

![image](https://user-images.githubusercontent.com/28401593/65964880-06950900-e45e-11e9-922a-b35a08771be2.png)

**Comment by escamoteur** [comment]
You could fake it I guess by placing the Card inside a lightly transparent slightly bigger container.

**Comment by HerrNiklasRaab** [comment]
@escamoteur Sorry but I couldn't follow your suggestion. Could you add a little code example?

**Comment by escamoteur** [comment]
Something like

```Dart
          Stack(children:[
            PageView(children: <Widget>[],),
            Positioned(child: Container(
              color: Colors.white10,   // try with different colors (don't know if Colors.transparent can have a shadow on it)
              padding: EdgeInsets.all(4.0),
              child: Card(elevation: 5,)
            ),)
          ]),
```

I used a Stack to place the card above you could also use a Dialog the idea is to create a transparent/almost transparent border around the card for the Shadow to fall on.  By playing with the Padding you can move the Container inside to match the shadow.
I have no idea if this works but that's the way I would try.

For more on this stackoverflow is the right place

**Comment by escamoteur** [comment]
If you are currently using a Dialog, give the Stack a try it might work with that.

**Comment by TahaTesser** [comment]
Hi @HerrNiklasRaab 
Please use the solution provided in this [comment](https://github.com/flutter/flutter/issues/41690#issuecomment-537151215)

if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
