### ISSUE TITLE
[web]: Selection in multiline text fields doesn't work 

### ISSUE THREAD

**Issue by sroddy** [flutter/flutter#41701]
When using a multiline Text field, the underlying `<textarea>` is rendered correctly but the text inside it doesn't wrap properly. for this reason text selection is completely off and looks broken.

I found out that a good way to mitigate the issue is to remove the `..whiteSpace = 'pre'` setting.
This doesn't entirely solve issues when the text overflows and needs to be scrolled, but at least works decently on an "average" scenario, until https://github.com/flutter/flutter/issues/32213 is fixed properly.

I'm wondering what was the rationale for the setting of the `whiteSpace` property. Perhaps it made sense when it was used just with one-liner `<input>` elements?

**Comment by sroddy** [comment]
cc @nturgut @yjbanov who worked on that file

**Comment by nturgut** [comment]
Solution depends on issue: #33523

**Comment by nturgut** [comment]
This page covers all engine contribution related information: https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment You can skip the Android, IOS and Desktop related steps.
Flutter engine build tools for web ([felt](https://github.com/flutter/engine/blob/master/lib/web_ui/dev/README.md)) only work on Mac and Linux for now.

**Comment by sroddy** [comment]
Thanks a lot for the clarifications.

I can confirm that al least on Chrome for Mac removing ..whiteSpace = 'pre' makes the text fields working decently, as long as they don't start scrolling.

@nturgut are you aware of any particular reason why it needed to be specified and relying on the default value was not sufficient? If there is none, I suggest to just get rid of it.

**Comment by sroddy** [comment]
@nturgut I was reviewing this issue and I think I might not have been clear enough about the issue.
The problem is that using pre, text is not wrapped, for this reason dragging the mouse or moving up/down with the keyboard with shift pressed in order to select text doesn't work.

I'm attaching here a screenshot of the text field, with the background color of the text area set to red, and color of the text in white, so you can better understand the problem :)

This is when you use `white-space: pre`
<img width="552" alt="Schermata 2019-10-17 alle 03 38 04" src="https://user-images.githubusercontent.com/729934/66970992-c05fbc80-f08f-11e9-8eb5-72a7cb9100fb.png">

This is when you use instead `white-space: pre-wrap`
<img width="558" alt="Schermata 2019-10-17 alle 03 41 03" src="https://user-images.githubusercontent.com/729934/66971097-2d735200-f090-11e9-882f-96e84c37aeec.png">

please note that w.r.t. to what I was writing before, you actually need to set `pre-wrap` and not remove the `white-space` property entirely because otherwise the text won't overlap 100%.

Another thing that I've noticed is that at least on Chrome Mac the text selection inside the text-area is still visible. I managed to fix it by adding the following snipped to the style sheet.

```
textarea::selection {
    color: transparent;
}
```

Before:
<img width="158" alt="Schermata 2019-10-17 alle 03 54 53" src="https://user-images.githubusercontent.com/729934/66971610-35cc8c80-f092-11e9-9059-943fc49b4693.png">

After:
<img width="117" alt="Schermata 2019-10-17 alle 03 55 30" src="https://user-images.githubusercontent.com/729934/66971601-2e0ce800-f092-11e9-9a17-3e7b25aac6a2.png">

**Comment by nturgut** [comment]
Hi Stefano,

Thanks for the suggestion and the explanations!

For the second part. @mdebbar also noticed it a couple weeks ago and sent a fix: https://github.com/flutter/engine/pull/12710 Are you in the latest version of repository for the engine?

For the first part: Let's change the [pre](https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/text_editing/text_editing.dart#L19). Do you want to send a PR to the engine?

I can also do that. Let us know.

Best,

**Comment by sroddy** [comment]
Thanks a lot for the second part, you are right, I was not on the latest commit.

For the first, please go ahead and fix it, I'm not really confident with the engine :)

Keep up the great work, it's really appreciated!
