### ISSUE TITLE
uncommenting the assets part in the pubspec.yaml file leaves mismatching indentation

### ISSUE THREAD

**Issue by zahash** [flutter/flutter#41703]
The default pubspec.yaml file contains these lines.

  \# To add assets to your application, add an assets section, like this:
  \# assets:
  \#  - images/a_dot_burr.jpeg
  \#  - images/a_dot_ham.jpeg

But when uncommenting with (ctrl + /), there is an indentation mismatch on the lines
"- images/a_dot_burr.jpeg" and
"- images/a_dot_ham.jpeg"

That is, there is only one space before the '-' instead of two

**Comment by aykejriw** [comment]
@zahash  I would like to work on this issue.
