### ISSUE TITLE
Handle errors from the font system better

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4170]
The engine dumps messages about failing to find font files.
We should:
- [ ] Fix whatever problem is causing these to come up in the first place
- [ ] Route the messages to Dart framework code to do something with
- [ ] Do something with these messages in the framework
- [ ] Silence the engine

**Comment by Hixie** [comment]
Things we've seen, for people searching bugs:
`Shell: Do not know weight for: TeXGyreSchola (BoldItalic)`
`[INFO:SkFontMgr_android.cpp(160)] Requested font file /system/fonts/NanumGothic.ttf does not exist or cannot be opened.`

**Comment by gspencergoog** [comment]
Well, here's the source of one of those.  I'm not sure how to redirect it/silence it yet.

```c++
src/third_party/skia/src/ports/SkFontHost_FreeType.cpp:1760:            SkDEBUGF(("Do not know weight for: %s (%s) \n", face->family_name, psFontInfo.weight));
```

**Comment by mravn-google** [comment]
This issue currently blocks local testing of changes to the `flutter.py` chromium bot recipe. The `flutter_tools` test suite fails when running
```
build/scripts/tools/run_recipe.py flutter/flutter slavename=slave2-c3 mastername=client.flutter buildername=Linux buildnumber=4900
```
in `~/chrome_infra` as described [here](https://github.com/flutter/flutter/blob/master/dev/bots/README.md#editing-a-recipe).

Not sure how to install the font in question.

```
00:17 +381 -4: test/commands/test_test.dart: flutter test should report a nice error when a Ticker is left running [E]
  Expected: match '══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════'
    Actual: 'Shell: Do not know weight for: TeXGyreSchola (BoldItalic) '
  Full output:
  - - - -----8<----- - - -
  00:00 +0: - Does flutter_test catch leaking tickers?
  Shell: Do not know weight for: TeXGyreSchola (BoldItalic) 
  ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
  The following message was thrown:
  An animation is still running even after the widget tree was disposed.
  
  There was one transient callback left. The stack trace for when it was registered is as follows:
  ── callback 2 ──
  #0      new _FrameCallbackEntry.<anonymous closure> (package:flutter/src/scheduler/binding.dart:88:33)
```

**Comment by goderbauer** [comment]
I've silenced these warnings in Skia a while ago as part of the work to remove obscure font formats. According to a skia dev there is no value in exposing these to a developer that's not working on Skia's font system.
