### ISSUE TITLE
[camera] Add Windows support

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#41709]
Since laptops commonly have cameras built in, this would be potentially useful.

~Blocked on #38601~

**Comment by StevenGodfrey** [comment]
Camera support would also be useful for tablet PCs that have back facing cameras.

**Comment by cvphat4796** [comment]
Any updates ?

**Comment by atj393** [comment]
Has anyone used OpenCV and C++ to try to access the camera in Windows Desktop?

**Comment by anandsubbu007** [comment]
any update?
