### ISSUE TITLE
[path_provider] Add Windows support

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#41715]
Assigning to @csells who has an-progress implementation to be hosted in FDE (which would move to flutter/plugins once Windows plugin APIs and tooling are stable). Once that lands we can link to it here and then leave this open to track moving it once we're ready to host Windows plugins.

**Comment by stuartmorgan** [comment]
This has been [implemented in FDE](https://github.com/google/flutter-desktop-embedding/tree/master/plugins/flutter_plugins/path_provider_fde). Per above, leaving open to track moving it.

**Comment by MostHated** [comment]
Any update on this? I didn't realize it wasn't working for Windows until I was closing in on the tail end of my application I have been working on. If not are there any working alternatives that anyone may be aware of that work for Windows that I might be able to use for the time being?

**Comment by stuartmorgan** [comment]
> Any update on this?

It's blocked on getting Windows test infrastructure set up for flutter/plugins (then a rewrite in Dart, but that should be simple).

> If not are there any working alternatives that anyone may be aware of that work for Windows that I might be able to use for the time being?

See the link in my earlier comment.

**Comment by technolion** [comment]
I provided two PRs to support retrieving a user's Downloads directory on Windows. This call is already supported for macOS.

https://github.com/google/flutter-desktop-embedding/pull/765 (has to land first)
https://github.com/flutter/plugins/pull/2849
