### ISSUE TITLE
[connectivity] Add Windows support

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#41712]
The API is currently pretty mobile-centric, so we'd need to evaluate whether we want to move toward a more generic API as part of adding desktop support.

**Comment by Sunbreak** [comment]
FYI: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#important-note

> As of January 2021, we are no longer accepting non-critical PRs for plugins for which there is a corresponding Flutter Community Plus Plugin, as we hope in time to be able to transition users to those versions of the plugins. If you have a PR for something other than a critical issue (crashes, build failures, null safety, etc.) for any of the following plugins, we encourage you to submit it there instead:

**Comment by stuartmorgan** [comment]
Closing as `connectivity` is deprecated in favor of [`connectivity_plus`](https://pub.dev/packages/connectivity_plus).
