### ISSUE TITLE
[shared_preferences] Add macOS support

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#41718]
This is [already implemented in FDE](https://github.com/google/flutter-desktop-embedding/tree/master/plugins/flutter_plugins/shared_preferences_fde), and should be moving shortly.

**Comment by goldenplan** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':shared_preferences:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':shared_preferences:debugCompileClasspath'.
   > Could not resolve project :shared_preferences_macos.
     Required by:
         project :shared_preferences
      > Unable to find a matching configuration of project :shared_preferences_macos:
          - None of the consumable configurations have attributes.
   > Could not resolve project :shared_preferences_web.
     Required by:
         project :shared_preferences
      > Unable to find a matching configuration of project :shared_preferences_web:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by franciscojma86** [comment]
@goldenplan This issue is about porting the macOS plugin to the flutter repo. For errors on the plugin please file another issue with a copy of the results on `flutter doctor -v`.

Please try and  delete your Podfile.lock file, and update your Flutter version. Also make sure you are using `shared_preferences: ^0.5.6`
