### ISSUE TITLE
[path_provider] Add Linux support

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#41716]
This is a common plugin, so we should support it on desktop. We'll need to decide on what conventions we want to use for Linux for some of the app-specific paths, since there's not necessarily an OS standard.

**Comment by stuartmorgan** [comment]
Blocked on https://github.com/flutter/flutter/issues/55327 for Linux. Once that's done we can do this as a Dart-only "plugin" (see WIP PR above)

**Comment by TimWhiting** [comment]
@stuartmorgan This can be closed now :)
