### ISSUE TITLE
[shared_preferences] Add Windows support

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#41719]
Assigning to @csells who has an-progress implementation to be hosted in FDE (which would move to flutter/plugins once Windows plugin APIs and tooling are stable). Once that lands we can link to it here and then leave this open to track moving it once we're ready to host Windows plugins.

**Comment by stuartmorgan** [comment]
For anyone interested in trying this out now, https://github.com/flutter/plugins/pull/2631 is a working implementation, it's mostly just waiting on some tooling support for tests in the flutter/plugins repository.

**Comment by dranc** [comment]
Hello,
How can we test it ? I tried to add the following dependecy to my pubspec file but it does not work. :(

> shared_preferences_windows:  
>     git:  
>       url: git://github.com/franciscojma86/plugins.git  
>       path: packages/shared_preferences  
>       ref: shared

**Comment by technolion** [comment]
Great news @stuartmorgan ! I tried to use it like this:
```
  shared_preferences:
    git:
      url: https://github.com/franciscojma86/plugins.git
      path: packages/shared_preferences/shared_preferences
      ref: shared
```
Bit it then gives this error:

```
flutter pub get
Error on line 34, column 11: Invalid description in the "shared_preferences" pubspec on the "shared_preferences_windows" dependency: "../shared_preferences_windows" is a relative path, but this isn't a local pubspec.
   ╷
34 │     path: ../shared_preferences_windows
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
Running "flutter pub get" in skp-client...
```

Is it even possible to include a federated plugin from a forked repository like that?

**Comment by TheOneWithTheBraid** [comment]
Is there anyone working on? It's been some time now...

**Comment by liudonghua123** [comment]
I would like to vote up this wanted feature. 😃

**Comment by stuartmorgan** [comment]
@liudonghua123 You are welcome to do so (which [is not done by commenting](https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-comments-to-bugs)), but this is blocked by https://github.com/flutter/flutter/issues/56143 as I've already said in the PR.
