### ISSUE TITLE
[package_info] Implement Linux support

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#41729]
We'll need to decide how to embed the necessary information into the Runner (or supporting data) for the plugin to query.

**Comment by handicraftsman** [comment]
I think this should be provided by application developer on linux, possibly while generating/building the project. Mostly because you cannot get that info for sure - on linux applications have various ways of distribution: through classical dpkg or rpm, or using snape, flatpak, appimage, etc.

**Comment by hpoul** [comment]
I have worked around this by using `--dart-define=` during `flutter --build` and use String.fromEnvironment, when `package_info` is not available on that platform..

Maybe this could be an easy way for linux/windows/web implementations by letting the build tool set FLUTTER_VERSION_NAME, *_VERSION_CODE, *_PACKAGE constants? Technically this is not really "package_info"  but rather compile info and it would require a change to build tools, not just the plugin..

**Comment by stuartmorgan** [comment]
I imagine the most straightforward solution here would be to have the Linux build create a simple (JSON, or just key/value) file from pubspec.yaml info, and include that in `data/` as part of the bundle step. Then the plugin can be a pure Dart implementation that reads it.

That addresses the fact that there's no single way to include this information on Linux (at the cost of very minor duplication with some packaging formats).

**Comment by azubieta** [comment]
Hello folk!

I would like to add flutter support to appimage-builder (a tool for packaging applications as AppImages).  This should be a simple task, I just need to know how to compile a flutter application for GNU/Linux and install the resulting binaries into a custom prefix. 

I have created this issue https://github.com/AppImageCrafters/appimage-builder/issues/70 to gather some information. It would be great if you could shine in an comment how I could achieve this.

Thanks

**Comment by stuartmorgan** [comment]
@azubieta Please don't ask questions on random unrelated issues. You can tag in your own issue tracker with specific questions and I can help.

**Comment by Ephenodrom** [comment]
Any news on this as Linux is now available in the stable channel ?

**Comment by nilsreichardt** [comment]
> Any news on this as Linux is now available in the stable channel ?

@Ephenodrom You can use the [package_info_plus](https://pub.dev/packages/package_info_plus) package (written by the Flutter Community). It supports Android, iOS, Web, Windows, macOS & Linux :)

**Comment by stuartmorgan** [comment]
Closing as `package_info` is deprecated in favor of [`package_info_plus`](https://pub.dev/packages/package_info_plus).
