### ISSUE TITLE
[url_launcher] Add desktop support

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#41721]
Filing this a consolidate bug for all three desktop platform since [there are already FDE implementations for all three](https://github.com/google/flutter-desktop-embedding/tree/master/plugins/flutter_plugins/url_launcher_fde). This bug is to track moving them over to flutter/plugins as each platform's plugin tooling and APIs stabilize:
- [x] macOS
- [x] Windows
- [x] Linux

**Comment by stuartmorgan** [comment]
Assigning myself for macOS since that will be ready to move very soon.

**Comment by hrpath** [comment]
Is there some consideration for this ticket. 
It's coming really important as support for inline webview will take some times so it means there's no way for an application to start a browser. Thank you !

**Comment by stuartmorgan** [comment]
Blocked on https://github.com/flutter/flutter/issues/55327 for Linux. Once that's done we can easily do this as a Dart-only "plugin".

**Comment by stuartmorgan** [comment]
The first Dart-only Linux plugin (`path_provider`+`path_provider_linux`) is landed and published, so doing the Linux version of `url_launcher` should be straightforward; it just needs to do [this](https://github.com/google/flutter-desktop-embedding/blob/master/plugins/flutter_plugins/url_launcher_fde/linux/url_launcher_plugin.cc#L93) using Dart's `Process`.

**Comment by robert-ancell** [comment]
> The first Dart-only Linux plugin (`path_provider`+`path_provider_linux`) is landed and published, so doing the Linux version of `url_launcher` should be straightforward; it just needs to do [this](https://github.com/google/flutter-desktop-embedding/blob/master/plugins/flutter_plugins/url_launcher_fde/linux/url_launcher_plugin.cc#L93) using Dart's `Process`.

This may actually be more reliable/simpler with the GTK shell to implement in C++ with [g_app_info_launch_default_for_uri()](https://developer.gnome.org/gio/stable/GAppInfo.html#g-app-info-launch-default-for-uri).

**Comment by stuartmorgan** [comment]
Ah, good to know. It looks like there's also `g_app_info_get_default_for_uri_scheme` as a reliable way to implement `canLaunch`, which we currently don't have.

This seems like a good candidate for a Dart-with-FFI-to-system-library "plugin" then.

**Comment by robert-ancell** [comment]
I actually linked in the wrong API call there, that's the low level API but we should use [`gtk_show_uri_on_window()`](https://developer.gnome.org/gtk3/stable/gtk3-Filesystem-utilities.html#gtk-show-uri-on-window). That can connect the window to the app (though I don't know how many apps make use of it). We can still use `g_app_info_get_default_for_uri_scheme` for `canLaunch`. So it would have to be a full plugin and not use FFI.

**Comment by stuartmorgan** [comment]
> That can connect the window to the app

I'm not sure we want that; the behavior on all the other platforms is that it fully switches to that application.

**Comment by robert-ancell** [comment]
> > That can connect the window to the app
> 
> I'm not sure we want that; the behavior on all the other platforms is that it fully switches to that application.

I don't mean it embeds the window, but it passes the window as part of the launch context. I think the intention is for this information to be provided to the window manager to help with focus stealing and window placement.

**Comment by stuartmorgan** [comment]
Ah, okay. Sounds like we should do GTK port in FDE then, and move it once we're ready to call the interface stable.

**Comment by stuartmorgan** [comment]
@robert-ancell Do you want to open a PR to move url_launcher_fde's Linux implementation to flutter/plugins now that the interfaces and tooling are stable?
