### ISSUE TITLE
[package_info] Implement macOS support

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#41727]
This will be trivial, since all the information is available via NSBundle.

We could use the existing iOS implementation as-is, but since we're going primarily Swift for macOS, and it's actually easier to duplicate this code than extract it to another pod to share, we should just write a new macOS implementation in Swift.

**Comment by donnkii** [comment]
Is this being worked on

**Comment by hpoul** [comment]
fwiw, if you need it, it's trivial to add macos support on your own.. i've basically [copied the ios implementation into macos](https://github.com/authpass/package_info_macos/blob/master/macos/Classes/PackageInfoMacosPlugin.swift), feel free to try my repo, just add to your pubspec:

```
  package_info: ^0.4.0+13
  package_info_macos:
    git:
      url: https://github.com/authpass/package_info_macos.git
```

**Comment by stuartmorgan** [comment]
@donnkii I'm not aware of anyone working on it an the moment.

@hpoul Is there reason you are hosting it locally instead of contributing an implementation to flutter/plugins?

**Comment by hpoul** [comment]
@stuartmorgan mainly because it's just a straight copy of the ios code transformed to swift.. wasn't sure if it's really the best solution to have 1:1 duplicated code between ios/macos? thought maybe somebody comes up with a way to share the code between the two platforms :-) the original description sounded like there was some plan of creating a separate pod.. if it saves anyone work i can create a PR for flutter/plugins - would this require a plugin platform interface, or simply the `macos` implementation into `package_info`?

**Comment by stuartmorgan** [comment]
> @stuartmorgan mainly because it's just a straight copy of the ios code transformed to swift.

That's exactly the desired outcome for this plugin, per the end of my initial comment.

> thought maybe somebody comes up with a way to share the code between the two platforms :-)

We have a way to do this (using symlinks; see [firebase_core](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core) for an example)). I don't think there's much need for it for a plugin this simple, but on the other hand we do want to have one flutter/plugin plugin implemented using that technique, so I suppose this could be it.

> the original description sounded like there was some plan of creating a separate pod.

At the time that was the only approach I was aware of for sharing code between macOS and iOS plugins, and as I said in the original description for this plugin doing that would have actually been more work than a Swift copy, and given that we *shouldn't* make a pod.

> if it saves anyone work i can create a PR for flutter/plugins - would this require a plugin platform interface, or simply the `macos` implementation into `package_info`?

If you want to make this the symlink example—which, looking at the remaining plugins, this may be the last obvious candidate for where the implementations will be identical, so is probably the right approch—it would go into package_info as-is.

**Comment by hpoul** [comment]
fyi i've now created a PR https://github.com/flutter/plugins/pull/2618 - i don't really understand the build failures though. For me e2e tests work and i'm also now using it in my app already:

```
  package_info:
    git:
      url: https://github.com/hpoul/plugins.git
      ref: package_info_macos
      path: packages/package_info
```

**Comment by stuartmorgan** [comment]
@hpoul Awesome, thanks! I'll try to help get that through the review process.
