### ISSUE TITLE
[shared_preferences] Add Linux support

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#41720]
This is a common plugin, so we should support it on desktop. We'll need to decide on what conventions we want to use for Linux for the location, since there's not necessarily an OS standard.

For the actual storage, JSON is probably the easiest option to minimize dependencies (vs. something like SQLite).

**Comment by robert-ancell** [comment]
The standard place for this is specified in the [XDG Base Directory specification](https://www.freedesktop.org/wiki/Specifications/basedir-spec/). Simply, it's in ~/.config/<appname> or use the environment variable $XDG_DATA_HOME/<appname> if specified.

**Comment by stuartmorgan** [comment]
Blocked on https://github.com/flutter/flutter/issues/55327. Once that's done we can do this as a Dart-only "plugin" using almost identical Dart code to the Windows version that has a pending PR.

**Comment by stuartmorgan** [comment]
The blocking bug is resolved, and a Dart-only `path_provider_linux` landed. Implementing this would just involve combining the JSON code from [the Windows PR](https://github.com/flutter/plugins/pull/2631) with the location lookup using XDG as in `path_provider_linux`.
