### ISSUE TITLE
[package_info] Implement Windows support

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#41728]
I'm not familiar with how Windows application metadata is managed, but this will presumably require some changes at the Runner level to make sure the necessary information is available in the binary.

**Comment by rekire** [comment]
How can I help with this? I know a bit about the pe headers etc.

**Comment by stuartmorgan** [comment]
This should be very straightforward now; VERSIONINFO was added to the template to support `path_provider_windows`, and there's existing code there to extract some of it, so almost everything needed for this now already exists.

Implementing `package_info_windows` should just involve extracting and restructuring [that `path_provider_windows` code] into a new plugin. (Once it's published we can actually remove all of that code from `path_provider_windows` and have it just depend on `package_info_windows`.)

I'm happy to review patches for that. If you're interested in doing this, the basic roadmap (since there's not a good overview document for how to bring up a new federated plugin implementation yet) is:
- Make a PR that just implements/tests `package_info_windows`.
  - This PR shouldn't change `package_info` at all.
  - It will need to do use the same conditional import stubbing that `path_provider_windows` currently does.
- Get that reviewed/landed/published
- Make another PR for `package_info` that endorses the now-published `package_info_windows`, including doing the manual Dart registration (again, like `path_provider`).
- Get that reviewed/landed/published

**Comment by rekire** [comment]
I think I need to go one step back, since I have no experience with testing of c++ code. I need find some samples and learn that first. But I'm interested in that topic, I will look what I can do.

**Comment by stuartmorgan** [comment]
There won't be any C++ code involved here; the code to read VERSIONINFO via Dart FFI calls to Win32 APIs is already written (per my link above). You can look at path_provider_windows to see what the unit and integration testing look like for a plugin like this.

**Comment by stuartmorgan** [comment]
> However I added that Windows plugin as dependency of the main plugin. I'm not sure if that is the right way to implement this.

It is currently the only way to implement a Dart-only plugin (which is why my outline above includes "including doing the manual Dart registration").

> I guess that will include transitive dependencies which are only relevant on Windows.

Yes, unfortunately. See https://github.com/flutter/flutter/issues/67402, for instance.

> Should I open a preview PR for you to check my changes?

As described in the outline above, there need to be two separate PRs.

**Comment by stuartmorgan** [comment]
Closing as `package_info` is deprecated in favor of [`package_info_plus`](https://pub.dev/packages/package_info_plus).
