### ISSUE TITLE
[web]: Web plugins not implemented

### ISSUE THREAD

**Issue by davidcavazos** [flutter/flutter#41734]
When following the guide [Developing plugin packages](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#developing-plugin-packages), there is no implementation for a `web` plugin.

I created a project via the command:

```sh
flutter create --template=plugin -i swift -a kotlin hello
```

Running the app actually works, but it displays the platform version as "Unknown".

```sh
cd hello/example
flutter run -d chrome
```

There are `android` and `ios` directories for platform-specific code, but there is no `web` directory.

When looking at the `example/lib/main.dart` file, on the `initPlatformState()` function, the `try-catch` is not raising an `PlatformException` or `MissingPluginException` or any exception. It's just failing silently (?) and the actual `setState()` function is never called. If I change the plugin implementation to not use `_channel.invokeMethod` and return a hard-coded value, it works.

I would expect a `web` directory showing how to write a platform-specific function in Dart, or maybe Javascript/Typescript showing the Chrome version. Something showing how to call a third party Javascript library would be very useful.

**Comment by davidcavazos** [comment]
```
> flutter doctor -v
[✓] Flutter (Channel master, v1.10.7-pre.99, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.10.7-pre.99 at /Users/dcavazos/local/flutter
    • Framework revision 2de1e4f4a1 (17 hours ago), 2019-09-30 22:05:53 -0400
    • Engine revision 4981512815
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 692230b484)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dcavazos/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6262.58

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] VS Code (version 1.28.0)
    • VS Code at /Users/dcavazos/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Chrome          • chrome          • web-javascript • Google Chrome 77.0.3865.90
    • Headless Server • headless-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by cyanglaz** [comment]
if I understand the request correctly, this issue is about asking a default web setup when creating a plugin using `flutter create -t plugin`.
The `--platforms` flag was introduced in `flutter create` so adding web in a plugin is simple now. It is also documented here: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#add-support-for-platforms-in-an-existing-plugin-project

Closing the issue.
