### ISSUE TITLE
decodeImageFromDataPipe() doesn't throw if given bad data

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4173]
I'm looking at `_UrlFetcher.loadImage()`.

I was reading data from an oauth2 protected url, so it was returning a `302 Moved` error pointing to `https://login.corp.google.com/`. This meant that the data received by `decodeImageFromDataPipe()` was just an HTML page instead of an image. I expected that `decodeImageFromDataPipe()` should have thrown an exception that could be processed by `_UrlFetcher.loadImage()`, but instead was returning `null`, which caused the `ImageInfo` constructor to assert instead. The failure information and the response from the web server were lost, making the problem hard to debug.

### flutter doctor

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /media/jimbe/mojossd/sysui/src/third_party/flutter
    • Framework revision 5b8677d15d (4 days ago), engine revision 7fab0c350b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/home/jimbe/Android/Sdk
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-122278751-122271652)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

**Comment by abarth** [comment]
Should be fixed by https://github.com/flutter/flutter/pull/4118
