### ISSUE TITLE
"hashValues" should use "identical" instead of ==

### ISSUE THREAD

**Issue by MarcelGarus** [flutter/flutter#41739]
Currently, the implementation of `dart:ui`'s `hashValues` function compares the passed in object with `_hashEnd`, like this:

```dart
if (arg03 != _hashEnd) {
  result = _Jenkins.combine(result, arg03);
  …
}
```

Let's say you have a class like the following:

```dart
class EqualToEverything {
  bool operator ==(Object other) => true;
  int get hashCode => 42;
}
```

Of course, that's a bad implementation of the `==` operator. 😄 I'm just saying that an implementation of `hashValues` that compares the arguments to `_hashEnd` using a flipped comparison (`_hashEnd == arg03`) wouldn't have any disadvantages compared to the current implementation but does behave more deterministic with regard to this one special case.

**Comment by ds84182** [comment]
Another (and faster) alternative is to use `identical` for the comparisons.

**Comment by jonahwilliams** [comment]
I think that `identical` and `==` should have the same  performance for primitive types? I guess one way to check would be to look at the generated code

**Comment by escamoteur** [comment]
@jonahwilliams Wouldn't this better filed at the Dart repo? or is `dart:UI` only flutter? I don't think this qualifies as an `engine` topic, does it?

**Comment by jonahwilliams** [comment]
hashValues is implemented in dart:ui which is I'm the engine

**Comment by jonahwilliams** [comment]
dart:ui no longer uses HashValues, closing as obsolete
