### ISSUE TITLE
Observatory's timeline tracing is not working properly

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#41746]
1. "Refresh" button is not working reliably. Usually, I have to refresh the web page multiple times to get the trace refreshed and loaded.
2. "Save" button does not work at all. It shows "Cannot save an empty timeline" even if there's a 
 non-empty timeline trace. See also b/141889413

How to reproduce: (1) `flutter run` in flutter_gallery; (2) open the observatory URL, go to timeline, check all boxes, and touch the phone to generate some trace events; (3) click "Refresh"; (4) click "Save"

This makes performance debugging very inconvenient as we can no longer save and share traces.

**Comment by liyuqian** [comment]
CC @flar @devoncarew @sivachandra

**Comment by jonahwilliams** [comment]
I think this is why all of the devicelab performance tests stopped working...

**Comment by devoncarew** [comment]
@kenzieschmoll @jacob314 - is the same workflow supported in DevTools?

**Comment by jason-simmons** [comment]
This started with https://github.com/dart-lang/sdk/commit/68dede011e81de04ffc826f42732b8ce620bc52d

@bkonyi

**Comment by kenzieschmoll** [comment]
This same workflow is supported in DevTools. In the current state we support a frame based timeline, but will support a timeline not broken down by frames in the future.

**Comment by bkonyi** [comment]
I'll take a look today. There was a pretty major refactor in the timeline code, so I wouldn't be surprised if something was missed / broken.
