### ISSUE TITLE
When the picture is larger than 3m, flutter cannot display the picture.

### ISSUE THREAD

**Issue by jicg** [flutter/flutter#41749]
When the picture is larger than 3m, flutter cannot display the picture.
图片地址：https://xianyan.hellowcloud.com/assert/files/2019October/1569978960591485666.jpg
``` dart
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
          child: Column(
        children: <Widget>[
          Image.network(
            "https://xianyan.hellowcloud.com/assert/files/2019October/1569978960591485666.jpg",
            fit: BoxFit.fitWidth,
          ),
        ],
      )),
    );
  }
}
```
I can't modify the size of the network picture. How can I make the picture display normally?

**Comment by jicg** [comment]
I am working on Android mobile phone.

**Comment by bernaferrari** [comment]
Possibly related: https://github.com/flutter/flutter/issues/40613

**Comment by BondarenkoStas** [comment]
@jicg Please provide your flutter doctor -v output.

**Comment by jicg** [comment]
```
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.17134.1006], locale zh-CN)
    • Flutter version 1.9.1+hotfix.2 at D:\App\flutter
    • Framework revision 2d2a1ffec9 (4 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\App\AndroidSdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • ANDROID_HOME = D:\App\AndroidSdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • MI PLAY • 49e7b9d20301 • android-arm64 • Android 8.1.0 (API 27)
    • PDA     • 890218090836 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.

```

**Comment by jicg** [comment]
```
Image.network(
   "https://xianyan.hellowcloud.com/assert/files/2019October/1569978960591485666.jpg",
   fit: BoxFit.fill,
   width: 200,height: 400,
),
```
Nor can it be displayed

**Comment by qylshy** [comment]
Is there any progress on this issue? I also meet this problem.
eg.  Image.file('xxx') but my pic file is about 13m. I try small pic file it's ok

**Comment by friebetill** [comment]
I also have the problem, but it only occurs with older or less powerful devices.

**Comment by dnfield** [comment]
Images this big should probably be scaled down using the `cacheHeight` and `cacheWidth` parameters (or just using `ResizeImage` directly). You're going to run into memory issues trying to render, e.g., an image that is 12 or 13x the height of your screen at full resolution on a lower end device.

**Comment by TahaTesser** [comment]
@dnfield  Do you think this is the correct place to add this? https://flutter.dev/docs/development/ui/assets-and-images#android. I could create PR for loading large image assets in this section

**Comment by dnfield** [comment]
That sounds good to me

**Comment by chinmaygarde** [comment]
From engine triage: Images this big have a high likelihood of making the device run out of device memory. @dnfield s suggestion is spot on and I think we already do this now in the engine (capped to the screen size perhaps). Closing this as WAI.
