### ISSUE TITLE
Target of URI doesn't exist package

### ISSUE THREAD

**Issue by VNAPNIC** [flutter/flutter#41756]
Target of URI doesn't exist: package:flutter_webrtc/webrtc.dart
![Untitled1](https://user-images.githubusercontent.com/7553452/66016961-013dca00-e503-11e9-854a-73bbcba41fe7.png)
![Capture2](https://user-images.githubusercontent.com/7553452/66016982-1b77a800-e503-11e9-8aaf-389da36a2902.PNG)

**Comment by pouledodue** [comment]
is the package present in your SOMEWHERE/flutter/.pub-cache/hosted/pub.dartlang.org/ dir?

**Comment by Zazo032** [comment]
Try running `flutter packages get`. If not working, in Android Studio, go to `File > Invalidate Caches / Restart > Invalidate and Restart`. That usually fixes this kind of issues for me.

**Comment by BondarenkoStas** [comment]
@VNAPNIC right, try running `flutter packages get`, or run `flutter packages upgrade`.
There's some chance that their pub cache is corrupted, in which case you may want to either delete `~/.pub-cache/hosted/pub.dartlang.org/` and re-run `flutter packages get`, or try running `flutter packages pub cache repair`.

**Comment by VNAPNIC** [comment]
Tks U.
I tried deleting ~/.pub-cache/hosted/pub.dartlang.org/  and it ran

**Comment by escamoteur** [comment]
Great to here, I close the issue then.
