### ISSUE TITLE
TextField autocorrect=false bug

### ISSUE THREAD

**Issue by kevinengel** [flutter/flutter#41758]
Filing new bug to draw attention to:

https://github.com/flutter/flutter/issues/22828#issuecomment-520174825

Flutter is not setting the necessary InputType flags when autocorrect is set to false.

**Comment by HansMuller** [comment]
CC @LongCatIsLooong, @justinmc - we need to get https://github.com/flutter/flutter/issues/22828 sorted on both iOS and Andrdoid.

**Comment by justinmc** [comment]
I'm on this.  Looks like Android has the `TYPE_TEXT_FLAG_NO_SUGGESTIONS` but iOS does not have something similar.  I'll discuss in the other issue.
