### ISSUE TITLE
[web]: Useless logs in Safari

### ISSUE THREAD

**Issue by rostopira** [flutter/flutter#41764]
I'm receiving multiple `Unhandled Promise Rejection: Error`
It's totally useless and I can't debug anything
![image](https://user-images.githubusercontent.com/16724952/66030961-22a2b400-e50b-11e9-9d34-97c7df0f26d7.png)

**Comment by rostopira** [comment]
It's even worse on Firefox
![image](https://user-images.githubusercontent.com/16724952/66203603-6df6c700-e6b1-11e9-99a2-13a461bcaca3.png)

**Comment by yjbanov** [comment]
How do you run the app? Is it in debug, profile, or release mode?

**Comment by rostopira** [comment]
@yjbanov debug, using `flutter run -d headless`

**Comment by rostopira** [comment]
I've created different issue with minimal code to reproduce here: https://github.com/dart-lang/sdk/issues/38787
Mysterious error without description as well
Dart bug, not Flutter, I guess?

**Comment by yjbanov** [comment]
Ah, afaik, debug mode does not yet work in Safari and Firefox. To debug in those browsers you can compile in profile or release mode and step through the code using sourcemaps (although we've seen Firefox sometimes fail to download sourcemaps).

**Comment by yjbanov** [comment]
I put a flutter label on the Dart SDK issue. Let's track it there.
