### ISSUE TITLE
when ever i try to run with firebase

### ISSUE THREAD

**Issue by chinu999** [flutter/flutter#41769]
```
* Error running Gradle:
ProcessException: Process "C:\Users\Suravi\AndroidStudioProjects\flutsdhtf\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Suravi\AndroidStudioProjects\flutsdhtf\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: C:\Users\Suravi\AndroidStudioProjects\flutsdhtf\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.
```

**Comment by Zazo032** [comment]
Could you post the output of `flutter doctor -v`?
Also, which Firebase plugins and versions are you using?
Does it build correctly without them?
Did you migrate your app to AndroidX?

**Comment by BondarenkoStas** [comment]
@chinu999 The issue appeared a lot of times already, can you please take a look into https://github.com/flutter/flutter/issues/41492#issuecomment-536112970 and report if that will help?

**Comment by chinu999** [comment]
> Could you post the output of `flutter doctor -v`?
> Also, which Firebase plugins and versions are you using?
> Does it build correctly without them?
> Did you migrate your app to AndroidX?

i again transfer my project and rebuild with androidX

and flutter doctor v-
D:\Softwares\Android Studio\Flutter\Projects\fireservices>flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.30], locale en-IN)
    • Flutter version 1.9.1+hotfix.2 at D:\Softwares\Android Studio\Flutter\flutter
    • Framework revision 2d2a1ffec9 (4 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Chinu\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.38.1)
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (A
PI 28) (emulator)

• No issues found!

**Comment by BondarenkoStas** [comment]
@chinu999 Please check the comment above

**Comment by chinu999** [comment]
> @chinu999 Please check the comment above

Thanks bro i solved it because of thank you so much .i am sorry for late replay due to heavy rain i am facing net connection problem.but anyway thaks.
the problem is in 
 dependencies {
    classpath 'com.google.gms:google-services:4.3.2'
    // ...
}
i changed to
dependencies {
    classpath 'com.google.gms:google-services:4.2.0'
    // ...
}
