### ISSUE TITLE
ShaderMask with ListView child

### ISSUE THREAD

**Issue by vitor-gyant** [flutter/flutter#41768]
I've updated Flutter to 1.10.7-pre.78 and it seems that ShaderMask has suffered some change that created a strange behaviour.

This is the what happens when ShaderMask child is a ListView:

![IMG_A67A9E2AE752-1](https://user-images.githubusercontent.com/45602144/66034148-98ede900-e500-11e9-8376-da5159ee411a.jpeg)

Wrapping the ListView in a Container with a valid color field solves the issue.

![IMG_E2A0A8F77A9F-1](https://user-images.githubusercontent.com/45602144/66034147-98ede900-e500-11e9-82f7-d6e46f62c0b3.jpeg)

Any idea ?

**Comment by BondarenkoStas** [comment]
@vitor-gyant can you please provide some self-contained app to reproduce the issue? Also, specify on which device/emulator you test it.

**Comment by vitor-gyant** [comment]
@BondarenkoStas Here is the sample app which reproduces the issue. Make sure to execute: `flutter create .` to recreate the project files.

[shader_mask_list_view.zip](https://github.com/flutter/flutter/files/3681324/shader_mask_list_view.zip)

I've done some more testing and wrapping the ShaderMask child in a Material widget or a Container with a color seems to solve the issue.

**Comment by jason-simmons** [comment]
I ran the attached app using the current Flutter master branch on a couple of Android devices (Nexus 5X, Moto G4).  The ListView was rendered with fading applied to the bottom, which seemed as expected.

How does the example app look in your environment?  Does the bug happen everywhere, or does it only affect some devices?

**Comment by vitor-gyant** [comment]
@jason-simmons Just updated to the latest master version and it is solved now. It could be related with another issue I've also reported that seems to be fixed by #41743. 

Closing this now. Thanks for the support.
