### ISSUE TITLE
Black a Screen In android 9 UI "One UI 1.0" 

### ISSUE THREAD

**Issue by AymanMubark** [flutter/flutter#41772]
My app works fine in android 4.2.2 but  in android 9 UI "One UI 1.0"  phone  Samsung galaxy j 4 pluse debug mode get this exception
The GPU does not support this version of OpenGL ES, try an older version
the app when I press in button location its work  but all element, not showing 

Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.17763.737], locale en-US)
    • Flutter version 1.9.1+hotfix.2 at C:\flutter
    • Framework revision 2d2a1ffec9 (4 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

**Comment by escamoteur** [comment]
Hi,

I'm sorry to hear that. I'm pretty sure this is fixed on the beta and master channels if you want to give that a try.
I'm sorry that I can't say when it will be in stable.

related https://github.com/flutter/flutter/issues/40150

**Comment by AymanMubark** [comment]
how can I know what channel im using and how can switch between them

**Comment by escamoteur** [comment]
Please see https://github.com/flutter/flutter/wiki/Flutter-build-release-channels
After changing do a `flutter upgrade`

**Comment by luisdiaz14** [comment]
Any news on this matter?
I am facing the same issue.

Thanks in advance.

**Comment by uchedotphp** [comment]
Fixed.
Solution: check the flutter channel you are on and switch to master.. using: 
to check your channel:  flutter channel
to switch channel: flutter channel master

after that run this: flutter upgrade
