### ISSUE TITLE
Failed to fetch music file thumbnail image for a specific song

### ISSUE THREAD

**Issue by mdarifmustafa** [flutter/flutter#41779]
I am first fetching all songs details available on my android device like filePath, imageArtwork, duration, title etc.,

if the value of imageArtwork is not null, then I am trying to load the music thumbnail image art file,

```
  _loadThumbnailImage(final int id) {
    File file = new File(_albumArtThumbnailPathValue);
    if (file.existsSync()) {
      try {
        _albumArtImage = Image.file(file, key: Key(id.toString()), fit: BoxFit.cover);
      } catch (error) {
        print("image thumbnail load error is: $error");
        _albumArtImage = null;
      }
    }
  }
```

it is working fine with every music thumbnail image, but just not working with one music file, which I have attached [here.](https://ufile.io/6r2e9z76)

and just because of this music file, that particular song tile is looking distorted and here I am unable to find that has the image loaded successfully or not.

## Logs

Error is:

```E/flutter (22171): [ERROR:flutter/lib/ui/painting/image_decoder.cc(242)] Could not decompress image.

════════ Exception caught by image resource service ════════════════════════════════════════════════
The following _Exception was thrown resolving an image frame:
Exception: operation failed

When the exception was thrown, this was the stack: 
#0      MultiFrameImageStreamCompleter._decodeNextFrameAndSchedule (package:flutter/src/painting/image_stream.dart:680:20)
<asynchronous suspension>
#1      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:644:7)
#10     FileImage._loadAsync (package:flutter/src/painting/image_provider.dart)
<asynchronous suspension>
...
Path: /storage/emulated/0/Android/data/com.android.providers.media/albumthumbs/1570014563446
════════════════════════════════════════════════════════════════════════════════════════════════════
```

flutter doctor

```Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.17134.1009], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.38.1)
[√] Connected device (1 available)

• No issues found!
```

So, there's nothing to check that the image is successfully loaded, because the variable is showing not null but because of internally crash and being already handled then and there, I am unable to know that the image loading has been crashed. 

please help.

**Comment by ketanm** [comment]
@mdarifmustafa - Can you check image format of that art work? Also, can you open that image in any other program (Chrome or Photos)?

**Comment by mdarifmustafa** [comment]
> @mdarifmustafa - Can you check image format of that art work? Also, can you open that image in any other program (Chrome or Photos)?

@ketanm Yes by using another widget testing program, I am able to open the song thumbnail image.

**Comment by ketanm** [comment]
@mdarifmustafa  - thanks for checking. This is good information. In your original post you have put link to mp4, can you link to image?

Also, on your end check image format details by doing `file image.png` on working vs non-working styles. 

Lastly, there is `.hotfix.4` version on stable, if you can update flutter and check if this was fixed or not.

**Comment by dnfield** [comment]
Please avoid using third party file sharing services, particularly if they request a login to download your content. You can attach files to the issue.

The file you're trying to load as an image appears to be an mp3.  That's not a supported format for image display.

I'm going to close this as not-reproducible.  Please feel free to update the bug if you have more details to share or an image that won't render.

**Comment by mohammadne** [comment]
so how do we should get an audio file cover art ?

**Comment by mohammadne** [comment]
@dnfield any update about this ?
is it possible to get metadata of mp3 file ?
