### ISSUE TITLE
Enable optionals (non-nullable..) on lib/src only

### ISSUE THREAD

**Issue by ollydixon** [flutter/flutter#41774]
On large projects we are really missing` optionals (?) and @NonNullable`. It's actually the main reason for our crashes from models. Almost all other frameworks have this for mobile development now, TS, Swift, Kotlin.

We are aware that this feature exists in Flutter but enabling it causes issues with 3rd party libraries and Flutter Widgets.

As the title would it be possible to have optionals expirimental feature on ONLY your own lib/src files?

**Comment by escamoteur** [comment]
@ollydixon Sorry to disappoint you but currently the Dart-Lang team is still working on these or have you seen this inside the Flutter framework?

**Comment by ollydixon** [comment]
@escamoteur I'm aware of all of that, but the problem is 3rd parties will never be supported fully. 
Some libraries have not been updated in years which is way locational directory support is required like it is on other Flutter expiriments.

**Comment by escamoteur** [comment]
No that's not the only problem. As far as I know nullables are just finished yet.

**Comment by ollydixon** [comment]
@escamoteur they work fine if you have the flag on. If directory isolation was on for expirimentals that is all we need.

**Comment by ollydixon** [comment]
Doing this: 
<img width="215" alt="Screenshot 2019-10-02 at 16 14 43" src="https://user-images.githubusercontent.com/6940726/66051798-cc943780-e52f-11e9-8f18-1cf27beeb921.png">

Is super lame for a modern langauge...

**Comment by escamoteur** [comment]
You should develop with c for some time 😏
Best to ask at the Dart repository.

**Comment by jonahwilliams** [comment]
The development of NNBD with incremental migration is tracked here:

https://github.com/dart-lang/language/issues/110

As soon as it is available in the dart language, they'll be available to Flutter - and we'll likewise start updating the flutter SDK to use them

**Comment by ollydixon** [comment]
@jonahwilliams thanks, is there any reason why we are calling this "non-nullables" instead of the correct name of optionals?

**Comment by jonahwilliams** [comment]
You'd have to ask a language designer :man_shrugging:

**Comment by VladyslavBondarenko** [comment]
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
