### ISSUE TITLE
Exited (sigterm). Lost connection to device: SocketException: OS Error: Operation timed out, errno = 60

### ISSUE THREAD

**Issue by TheKashe** [flutter/flutter#41778]
I'm repeatedly getting Exited (sigterm) error when trying to debug the application on my device (iPhone) through VSC. One moment it works, the next it fails, with no sensible change to my system. Sometimes restarting VSC and killall dart, killall iproxy helps, most of the time I need to reboot to get it to work again (and sometimes even that doesn't work). usbmuxd has been updated to supposedly fixed version.

I'm quite sure it's just a stupid hardcoded timeout somewhere in the stack and the solution is as simple as increasing the timeout const, but where!?

    Launching lib/main.dart on xxxxx's iPhone in debug mode...
    Automatically signing iOS for device deployment using specified development team in Xcode project: 9Z2E3PCTD6
    Xcode build done.                                           90.5s
    Exited (sigterm)

## Steps to Reproduce

I suppose this could be my system specific, so I don't know how to reproduce on other machines.

## Logs

Full log is too long for comment, [providing just the critical part](https://gist.github.com/tvolkert/c99b4260379c437688261fd5f69c7646)

    [✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.13.6 17G3025,
        locale en-SI)
        • Flutter version 1.9.1+hotfix.2 at
          /Volumes/DataHD/MacOs/xxxxxx/Developer/flutter
        • Framework revision 2d2a1ffec9 (4 weeks ago), 2019-09-06 18:39:49 -0700
        • Engine revision b863200c37
        • Dart version 2.5.0

     
    [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
        • Android SDK at /Users/xxxxxx/Library/Android/sdk
        • Android NDK location not configured (optional; useful for native profiling
          support)
        • Platform android-29, build-tools 29.0.1
        • Java binary at: /Applications/Android
          Studio.app/Contents/jre/jdk/Contents/Home/bin/java
        • Java version OpenJDK Runtime Environment (build
          1.8.0_202-release-1483-b49-5587405)
        • All Android licenses accepted.

    [✓] Xcode - develop for iOS and macOS (Xcode 10.1)
        • Xcode at /Applications/Xcode.app/Contents/Developer
        • Xcode 10.1, Build version 10B61
        • CocoaPods version 1.7.5

    [✓] Android Studio (version 3.5)
        • Android Studio at /Applications/Android Studio.app/Contents
        • Flutter plugin version 39.0.3
        • Dart plugin version 191.8423
        • Java version OpenJDK Runtime Environment (build
          1.8.0_202-release-1483-b49-5587405)

    [✓] IntelliJ IDEA Community Edition (version 2019.1.3)
        • IntelliJ at /Applications/IntelliJ IDEA CE.app
        • Flutter plugin version 37.1.3
        • Dart plugin version 191.7830

    [✓] VS Code (version 1.38.1)
        • VS Code at /Applications/Visual Studio Code.app/Contents
        • Flutter extension version 3.5.1

    [✓] Connected device (1 available)
        • xxxxxx's iPhone • 6e17b7d8fe5061131b05a3564cf3b041e3fb3a86 • ios • iOS
          12.4.1

    • No issues found!

**Comment by tvolkert** [comment]
@TheKashe when this happens does the app successfully launch?

Without more concrete actionable reproduction info, I'm afraid there's no way we can investigate this.

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of 'flutter doctor -v'  please.
