### ISSUE TITLE
Possibility to use system ca store (including user installed)

### ISSUE THREAD

**Issue by stefan01** [flutter/flutter#41781]
Is it by any means possible to use the platform dependent system ca store? I am developing a flutter application, where I need to trust user installed ca certificates.
As far as I see, the dart http client has it's own trusted certificates and there is no possibility to use the system installed, is that correct? If yes it would probably mean, I would need to write all http related stuff native.

**Comment by stefan01** [comment]
I still haven't gotten an answer (over a week now). I need this for a project. If this isn't possible at the moment I will continue writting that parts native.

**Comment by kf6gpe** [comment]
This should be filed over in the https://github.com/dart-lang/sdk repo --- the HTTP client is part of Dart, not flutter.

**Comment by abianche** [comment]
@stefan01 did you manage to get the system/user certificates to work in Flutter? Or do you perhaps know a plugin that handles this out of the box?

**Comment by stefan01** [comment]
Sadly in the end I didn't use the dart http client for http calls which relied on the user ca store and instead implemented all http calls native :/

**Comment by abianche** [comment]
@stefan01 thanks for the reply. Basically if I go native, the support is out of the box right? Did you do it for both android and iOS?

**Comment by stefan01** [comment]
Sadly it also doesn't work directly out of the box. On Android you need to configure the network security configuration.
This is the one I used:
```
<network-security-config>
    <base-config>
        <trust-anchors>
            <!-- Trust preinstalled CAs -->
            <certificates src="system" />
            <!-- Additionally trust user added CAs -->
            <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>
```

On iOS I'm not 100% sure how it worked. I think it worked out of the box but it can't be tested on the emulator.
