### ISSUE TITLE
ListView + PageView scrolling issue

### ISSUE THREAD

**Issue by vitor-gyant** [flutter/flutter#41784]
I've switched to flutter master branch (1.10.7-pre.78) and I've noticed that one of the ListView components was having a strange behaviour when swiping through a PageView which was a child of the list view. During the swipe the list view scroll position changes as the page view was not there and then gets back to the correct position.

This is the sample app where the issue occurs. 

[list_view_page_view.zip](https://github.com/flutter/flutter/files/3681951/list_view_page_view.zip)

I was able to track down to this snippet:

```
return Opacity(
	opacity: _opacity,
	child: Transform.scale(
	scale: _scale,
	child: child,
	));
```

Removing the opacity widget solves the issue but I have no clue why. Maybe related with the offscreen step required by the Opacity widget for values > 0 .. < 1

**Comment by jason-simmons** [comment]
If it's a recent issue involving an `Opacity` widget, then it's likely to be due to https://github.com/flutter/flutter/issues/41394.

The change that caused that bug has been reverted in the engine.  Try running your app with the latest build from the Flutter master branch.

**Comment by vitor-gyant** [comment]
@jason-simmons Confirmed. Thanks.
