### ISSUE TITLE
How to use torch in camera plugin?

### ISSUE THREAD

**Issue by IngMarFlo** [flutter/flutter#41785]
I have an application to read barcodes and qr codes, therefore, I want to turn on / off the torch but the camera plug-in doesn't have that function, how can I do that?. Try the lamp and torch plug-in, but it doesn't work because the camera is in use for the other plug-in.

**Comment by mikerockett** [comment]
A [PR](https://github.com/flutter/plugins/pull/1969) exists for this, as well as [an issue](https://github.com/flutter/flutter/issues/31225) discussing the future of the plugin (needs to be reworked).

You could always extract the camera plugin from [the camera directory](https://github.com/NeKoFu/plugins/tree/camera_torch/packages/camera) in the forked repo (PR) – torch mode works using the alwaysOn flash mode, or you could use [my temporary repo](https://gitlab.com/mikerockett/flutter-camera) and call flashOn/flashOff on the Camera Controller.

**Comment by malikdoksoz** [comment]
> A [PR](https://github.com/flutter/plugins/pull/1969) exists for this, as well as [an issue](https://github.com/flutter/flutter/issues/31225) discussing the future of the plugin (needs to be reworked).
> 
> You could always extract the camera plugin from [the camera directory](https://github.com/NeKoFu/plugins/tree/camera_torch/packages/camera) in the forked repo (PR) – torch mode works using the alwaysOn flash mode, or you could use [my temporary repo](https://gitlab.com/mikerockett/flutter-camera) and call flashOn/flashOff on the Camera Controller.

Are you constantly updating the temporary repository?

**Comment by mikerockett** [comment]
@malikdoksoz I was going to update my repository with the updates in the forked repo, however I decided not to due to the capture-timing issues brought up in the PR discussion. For the purposes of the OP getting torch mode, I suggested my repo as an alternative.

As an aside, that repo only exists as a stop-gap, until such time as the PR is feature complete and merged, or work on the new camera (per #31225) is complete.

**Comment by iapicca** [comment]
Hi @IngMarFlo 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/31225)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
