### ISSUE TITLE
Problem !!! While running a simple Fire base Storage Program in Flutter

### ISSUE THREAD

**Issue by navidanchitrali** [flutter/flutter#41790]
## Steps to Reproduce

1. ...I have a problem in running a simple Firebase storage program, There is no error in the UI but The program does not write to the Firebase. Anybody help please?

HERE IS THE OUTPUT AFTER RUNNING THE PROGRAM..
`
Launching lib\main.dart on Android SDK built for x86 in debug mode... Initializing gradle... Resolving dependencies... Running Gradle task 'assembleDebug'... Built build\app\outputs\apk\debug\app-debug.apk. I/ffffflutter_ap(24392): NativeAlloc concurrent copying GC freed 2088(184KB) AllocSpace objects, 0(0B) LOS objects, 51% free, 1427KB/2963KB, paused 931us total 356.053ms I/FA (24392): App measurement is starting up, version: 16250 I/FA (24392): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE I/FA (24392): To enable faster debug mode event logging run: I/FA (24392): adb shell setprop debug.firebase.analytics.app com.navidan.fffffffflutter_app Syncing files to device Android SDK built for x86... I/FA (24392): Tag Manager is not found and thus will not be used D/EGL_emulation(24392): eglMakeCurrent: 0xebda10c0: ver 2 0 (tinfo 0xf5f893a0) D/eglCodecCommon(24392): setVertexArrayObject: set vao to 0 (0) 1 0 I/OpenGLRenderer(24392): Davey! duration=2611ms; Flags=1, IntendedVsync=38869152824505, Vsync=38869152824505, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=38869168902080, AnimationStart=38869169044980, PerformTraversalsStart=38869169169080, DrawStart=38871550239980, SyncQueued=38871553662780, SyncStart=38871558985480, IssueDrawCommandsStart=38871559589780, SwapBuffers=38871702428080, FrameCompleted=38871770011880, DequeueBufferDuration=38871000, QueueBufferDuration=384000, I/Choreographer(24392): Skipped 156 frames! The application may be doing too much work on its main thread. I/ffffflutter_ap(24392): Background young concurrent copying GC freed 11520(747KB) AllocSpace objects, 6(200KB) LOS objects, 25% free, 2193KB/2963KB, paused 1.881ms total 627.150ms D/eglCodecCommon(24392): setVertexArrayObject: set vao to 0 (0) 1 0 D/EGL_emulation(24392): eglMakeCurrent: 0xf5f7ef80: ver 2 0 (tinfo 0xebd925b0) D/eglCodecCommon(24392): setVertexArrayObject: set vao to 0 (0) 7 0 W/ffffflutter_ap(24392): Unsupported class loader I/DynamiteModule(24392): Considering local module com.google.android.gms.flags:3 and remote module com.google.android.gms.flags:3 I/DynamiteModule(24392): Selected local version of com.google.android.gms.flags D/NetworkSecurityConfig(24392): No Network Security Config specified, using platform default I/ffffflutter_ap(24392): Background concurrent copying GC freed 11619(608KB) AllocSpace objects, 11(340KB) LOS objects, 49% free, 1769KB/3538KB, paused 955us total 138.149ms
`
THANKS IN ADVANCE
2. ...
![Capture](https://user-images.githubusercontent.com/48487470/66063910-c7e67800-e55d-11e9-927e-ebf5ccee86f9.PNG)

**Comment by BondarenkoStas** [comment]
@navidanchitrali Please provide your flutter doctor -v output. Can you provide a self-contained app that demonstrates the problem?
For future, please try not to post screenshots of code/logs, to not make people to transcribe from it while some info is needed to be copied. And please don't paste all the log in one line, it makes it much harder to read.

**Comment by navidanchitrali** [comment]
@BondarenkoStas ok, i will remember it, thanks

**Comment by navidanchitrali** [comment]
@BondarenkoStas 

C:\Users\hnawe\dartproject\google_map_app>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.356], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!

**Comment by navidanchitrali** [comment]
@BondarenkoStas  Can you provide a self-contained app that demonstrates the problem?

i don't get it ?

**Comment by navidanchitrali** [comment]
@BondarenkoStas C:\Users\hnawe\dartproject\fffffffflutter_app>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.356], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!

**Comment by BondarenkoStas** [comment]
I meant can you provide some code example where the problem occurs?

**Comment by navidanchitrali** [comment]
@BondarenkoStas 

import 'package:flutter/material.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:firebase_database/ui/firebase_animated_list.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
   final FirebaseDatabase database = FirebaseDatabase.instance;
  final GlobalKey<FormState> formKey = GlobalKey<FormState>();
  DatabaseReference databaseReference;
  int _counter = 0;

  void _incrementCounter() {
    database.reference().child("messge").set({
       "firstname" : "Ahil",
      "lastname" : "Ali",
      "age" : 1
    });
    setState(() {
      _counter++;
    });
  }
//

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(

          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

**Comment by kroikie** [comment]
@navidanchitrali

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1073. Any further collaboration will be done there.
