### ISSUE TITLE
flutter generate needs better error handling

### ISSUE THREAD

**Issue by szotp** [flutter/flutter#41808]
At the moment there is basically zero error handling when doing `flutter generate`. 

1. If something goes wrong during `flutter generate` you will just see: `Code generation failed`

2. If the same thing goes wrong during `flutter run` you will see: `Code generation failed, build may have compile errors.`

3. If something goes wrong during hot reload session, a directory called error_cache will be created with stack trace - thats actually pretty nice.

Suggestion: include stack trace from error_cache in other cases, and pass through logger messages.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/42209
