### ISSUE TITLE
"Unable to launch DevTools. This is not Dart application."

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#41817]
The command I'm using to run the app:
`flutter run -d chrome --web-port=8080 --no-web-browser-launch`

I open `localhost:8080` on Chrome and click the Dart Debug Extension. But it shows this dialog:

![image](https://user-images.githubusercontent.com/1278212/66078791-8fbc4680-e517-11e9-85ae-462f3e97361f.png)

The only way to fix it is to kill `flutter run` and run it again for few times.

I'm filing this issue in the Flutter repo but I'm not sure if the problem in the flutter tool, the Dart Debug Extension, or DDC. Please let me know how I can get more helpful information (logs, etc).

**Comment by mdebbar** [comment]
Ok, I have a theory. There are many network requests for ddc modules and some SSE urls that take a while to finish. I think I might be clicking on the Dart Debug Extension too early sometimes.

The problem is that there's no indication on the page to signal whether the app is ready to be connected or not.

**Comment by yjbanov** [comment]
@mdebbar promises more details.

**Comment by mdebbar** [comment]
I confirmed that my theory is right. Now the feature request is to show some visual feedback when the app is ready. I created a separate issue for it: https://github.com/flutter/flutter/issues/42662
