### ISSUE TITLE
Tooltips specification and behaviors

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4182]
From a design review:

* After the tooltip is triggered (using a 150ms fade in with the material deceleration curve), keep tooltip displayed for as long as the user is holding the tap.
* After the user lifts the tap, keep the tooltip visible for 1.5 seconds
* After 1.5s, fade out the tooltip at 150ms, using the material acceleration curve.
* Condition: if the user lifts the tap and interacts with the UI before the 1.5s timer has been fulfilled, the tooltip would dismiss immediately upon that interaction be fading out over 150ms using the material acceleration curve. That way the tooltip isn't in the way when they're trying to do something else.
* Condition: Lifting and then tapping the tooltip during this 1.5s delay will simply dismiss the tooltip using the same 150ms animation. Tapping anywhere else on the screen will simultaneously dismiss the tooltip AND trigger the action that was tapped.

**Comment by abarth** [comment]
We need to add a global route to the PointerRouter to implement the first condition.  @Hixie thinks we should dispatch to these global routes after dispatching to the per-id pointer routes.
