### ISSUE TITLE
Android Studio/Flutter unit test 'debug' bug

### ISSUE THREAD

**Issue by efoertsch** [flutter/flutter#41823]
## Steps to Reproduce

1. Create an Future method
2. Create unit test to call future along lines below
3. Execute unit test via 'debug'
4. Make change to test such that output should change
5. Execute unit test via 'debug'

I am using Android Studio 3.5 and Flutter plugin V40.0.2. 

I created a unit test to test a http call. For kicks I put in a print statement to see what was being returned.

    void main()   {
      test("Get current.json", () {
        Repository repository = Repository();
        repository.getCurrentJson().then(expectAsync1((regions) {
          print(regions.toJson().toString());
          expect(regions.regions.length, 2);
        }));
      });

I click the 'debug'icon, the test is executed, and I see the Json printed  in the console. 

{initialRegion: NewEngland, regions: [{dates: [2019-10-02, 2019-10-03, 2019-10-04, 2019-10-05, 2019-10-06, 2019-10-07, 2019-10-08], name: NewEngland, printDates: [Wednesday 
...

I then comment out the print statement:

    void main()   {
      test("Get current.json", () {
        Repository repository = Repository();
        repository.getCurrentJson().then(expectAsync1((regions) {
    //          print(regions.toJson().toString());
          expect(regions.regions.length, 2);
        }));
      });

When I click the debug icon I *STILL* see the print results on the console!

If I click the 'run' icon, the test then runs correctly with no print statement appearing in the log.

Any changes to the unit test are not 'picked up' when executing via 'debug' unless I execute the code first in 'run' mode.

```
 flutter doctor -v
[✓] Flutter (Channel beta, v1.9.1+hotfix.4, on Mac OS X 10.13.6 17G8030, locale en-US)
    • Flutter version 1.9.1+hotfix.4 at /Users/ericfoertsch/Flutter SDK/flutter
    • Framework revision cc949a8e8b (5 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ericfoertsch/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
        pod setup

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • moto e5 play • ZY323KXS9W • android-arm • Android 8.0.0 (API 26)

! Doctor found issues in 2 categories.
```

**Comment by BondarenkoStas** [comment]
@efoertsch Thank you, it's interesting! Can you please try is it specifically for Android Studio? Is behavior the same if you run debug from command line, not through the studio button?

**Comment by janmoppel** [comment]
Hello @efoertsch !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
