### ISSUE TITLE
[image_picker] Support the v2 Android embedder plugins API

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#41839]

**Comment by mklim** [comment]
I talked to @cyanglaz about starting this one, but apparently this is blocked on Lifecycle.

**Comment by amirh** [comment]
This seems to be blocked on a missing hook for `onActivitySaveInstanceState`, this isn't provided by Lifecycle. Probably makes sense to add a listener in `ActivityPluginBinding`?
@matthew-carroll

**Comment by matthew-carroll** [comment]
Saving state opens a big can of worms. How is image picker utilizing it?

We have a very large and ambiguous existing issue with saving state in Flutter. I have concerns about exposing such a method to plugins when we have no good answer for dealing with Flutter asynchronous communication that prevents saving Dart data.

**Comment by xster** [comment]
Is this one still blocked?

**Comment by xster** [comment]
https://github.com/flutter/flutter/issues/45883 could be a case of the v1 only plugin misbehaving in v2 embedders
