### ISSUE TITLE
[google_maps_flutter] Support the v2 Android embedder plugins API

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#41837]

**Comment by cyanglaz** [comment]
current blocked since the plugin is using lifecycle callbacks. Waiting for https://github.com/flutter/plugins/pull/2168 to be merged and published.

**Comment by amirh** [comment]
The maps plugin needs to forward multiple Activity lifecycle events MapView, it seems like with the new embedder this needs to be a mix of events from the FlutterEngine's lifecycle object, and ActivityPluginBinding listeners (which we need to extend), the calls it needs are:

 * `mapView.onCreate(savedInstanceState)` - how do I get the savedInstanceState with the v2 embedding?
*   `mapView.onSaveInstanceState(outState)` - missing in the current v2 API
 * `mapView.onStart()`, `mapView.onResume()`, `mapView.onPause()`, `mapView.onStop()`, `mapView.onDestroy()` - can get these through the lifecycle object, though with current v2 API I'd have to track the activity attachment state provided to ActivityAware and have the plugin mix the activity attachment and the lifecycle state (also see discussion in https://github.com/flutter/engine/pull/9049#issuecomment-543294165 )

@matthew-carroll

**Comment by xster** [comment]
Do we still need anything for this plugin @matthew-carroll @amirh?

**Comment by xster** [comment]
Adding @matthew-carroll since you're working on this

**Comment by cyanglaz** [comment]
there is an example migration PR that we can refer to while working this. And migrating google_maps to support v2 should be not blocked anymore.
https://github.com/flutter/plugins/pull/2294/files
