### ISSUE TITLE
[google_sign_in] Support the v2 Android embedder plugins API

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#41838]
Internal: b/147364422

**Comment by cyanglaz** [comment]
current blocked since the plugin is using lifecycle callbacks. Waiting for https://github.com/flutter/plugins/pull/2168 to be merged and published.

**Comment by amirh** [comment]
Was the issue here onActivityResult?
I believe this is available through the ActivityPluginBinding

**Comment by xster** [comment]
It appears this one is unblocked now. @cyanglaz can you attempt this again?

**Comment by xster** [comment]
Assigning to @matthew-carroll since you're working on this

**Comment by stuartmorgan** [comment]
Fixed by the PR above; closing.
