### ISSUE TITLE
flutter command: "the active Flutter" warning can be confusing

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4184]
```
cd /builds/dev/smoke/flutter/bin/examples/flutter_gallery; flutter test test/smoke_test.dart
Warning - the active Flutter is not the one from the current directory:
  active Flutter   : /builds/dev/flutter
  current directory: /builds/dev/smoke
```

In this case what the warning meant was that the `flutter` command found on my PATH wasn't the one from the directory that contained the example I was running.

Referring to 'the active Flutter' is a bit opaque. Maybe 'flutter command' would be clearer.

**Comment by devoncarew** [comment]
@HansMuller, totally open to work-smithing! The code lives here https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/runner/flutter_command_runner.dart#L280, and the same terminology is used a little further below.

**Comment by Hixie** [comment]
Just ran into this with customer leafy. We definitely need to make this message clearer. It should explain what the problem is, how to fix it, and why we care.

**Comment by eseidelGoogle** [comment]
Seems like we could also provide devs way to fix this.  Like "run `flutter create` or `flutter upgrade` on your project to switch to the flutter in your path" or some-such.
