### ISSUE TITLE
[firebase_performance] Support the v2 Android embedder plugins API

### ISSUE THREAD

**Issue by bparrishMines** [flutter/flutter#41858]

**Comment by bparrishMines** [comment]
dup

**Comment by kroikie** [comment]
@bparrishMines

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/321. Any further collaboration will be done there.

**Comment by kroikie** [comment]
To avoid confusing with project https://github.com/flutter/flutter/projects/59 this issue will remain open here till resolved.
