### ISSUE TITLE
macOS catalina is leaking processes

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#41854]
We're not exactly sure when this started happening, because the processes need to build up significantly before it causes test failures. Locally @gspencergoog, @christopherfujino, and I observed dozens of dart processes and hundreds of iproxy processes. killall with no exit code didn't work, but once we had manually killed them the tasks started passing again.

**Comment by christopherfujino** [comment]
So I think this is a confluence of factors. I think we leak `iproxy` and `idevicesyslog` processes anyway (when I checked on this macbook, pre-catalina, no device connected, I had around 15 open processes of both). For some reason on the Catalina bots this is exacerbated and we end up running out of file descriptors (and perhaps other issues?).

I would suggest (to myself) to investigate not leaking `iproxy` and `idevicesyslog`.
