### ISSUE TITLE
[video_player] Support the v2 Android embedder plugins API

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#41850]

**Comment by mklim** [comment]
@matthew-carroll I talked about this with @cyanglaz offline, it sounds like this is (was?) blocked on a missing [`Registrar#lookupKeyForAsset`](https://github.com/flutter/engine/blob/647a8524b0d722a4a2ce976adb5ed9c981e61b82/shell/platform/android/io/flutter/app/FlutterPluginRegistry.java#L144-L146) from the new embedding. Do you know if that issue has been resolved?

**Comment by matthew-carroll** [comment]
@mklim you can find that method here:
https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/view/FlutterMain.java#L107

`FlutterMain` is still a terrible place for it, and we should move it, but it shouldn't be a blocker at this point. Please let me know if there is anything deeper to this issue.

**Comment by mklim** [comment]
SGTM, thanks @matthew-carroll!
