### ISSUE TITLE
Password text fields shouldn't be multi-line

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#41853]
### Current behavior

Flutter allows obscured text fields to be multi-line, but it prevents new lines from being added to the text.

### Motivation

Passwords are typically entered in single-line fields. It doesn't make sense to have a password field with multiple lines.

Another reason is that the web supports obscuring text only on single-line text fields (aka [`<input type="password">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password)).

### Proposed change

Throw if `EditableText.obscureText` is true and `EditableText.maxLines` is greater than 1.

**Comment by justinmc** [comment]
I agree, thanks for pointing this out.  Let's do it. https://github.com/flutter/flutter/pull/42470

**Comment by justinmc** [comment]
It was pointed out that this could be made a compile-time assertion if we were ok with a bigger breaking change (something like TextField.obscure).  Something to keep in mind if this is reworked in the future.

**Comment by Gaubee** [comment]
I think whether the password box is multi-line text, it should be free.
Just as "obscure" itself does not mean "password".
For example, I am in a public place, like a coffee shop. I pasted my blockchain private key in a text box. This is usually very long text. We often use textarea to accept input.
At this time, the hacker may recognize the text on my screen through the webcam, thereby stealing my blockchain identity.

**Comment by justinmc** [comment]
@Gaubee thanks for posting a counterpoint.  I think that on the web, it's not possible to have an obscured textarea.  Is that right?

It looks like currently in Flutter, if the text in a single-line obscured TextField is longer than the TextField, it will scroll horizontally.  You could always use that for something like a long private key input.

**Comment by Gaubee** [comment]
@justinmc 
Your experience is correct, but experience is based on what happened in the past.
We cannot guarantee that it will still be unused in the future.

When I want to enter the private key. If it's a single line of text, I can't make sure that what I paste is the correct length. For example, what if I accidentally paste it twice?
I just gave an example. I hope Flutter gets better and inspires creativity for developers.

**Comment by justinmc** [comment]
Ok I see.  If you're inspired to build this, it could definitely make a good Pub package.  Otherwise if you think this could potentially be part of Flutter itself, you could create a separate issue (feel free to tag me in it).  Then we can wait and see if it receives interest from other people, and if so, maybe add it to Flutter.

**Comment by FilipeAG** [comment]
the problem is that if i try to use a text field (obscure) that occupies the entire space of a container using Expands: true and max Lines: null, it will not work, only the text without obscure now.. :/
