### ISSUE TITLE
Material Switch: BoxDecoration Background Image Fails to Render

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#4185]
## Steps to Reproduce

Please tell us what you were doing and what went wrong.

I attempted to use a backgroundImage for the boxDecoration of a Material Switch.
```
`ImageResource image=DefaultAssetBundle.of(context).loadImage('assets/discover_active_icon.png');`

`Widget discoveryToggle = new Switch(
      inactiveThumbDecoration: new BoxDecoration(
        backgroundColor: Colors.indigo[400],
        shape: BoxShape.circle,
        boxShadow: kElevationToShadow[1],
        backgroundImage: new BackgroundImage(
          image: image,
          fit: ImageFit.contain)));`
```
The image successfully loaded (was specified in assets under flutter.yaml) , but failed to render on the switch.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/dayang/Flutter
    • Framework revision 5460e94488 (3 weeks ago), engine revision 76d5cf230a

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/dayang/Library/Android/sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3, Build version 7D175
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2

**Comment by abarth** [comment]
Thanks for the report.  I'll take a look.

**Comment by abarth** [comment]
I have a fix.  Writing test now.

**Comment by fluttercorner** [comment]
[How to set Background Image to Scaffold in Flutter](https://fluttercorner.com/how-to-set-background-image-to-scaffold-in-flutte/)
