### ISSUE TITLE
flutter_tools doctor_test.dart is sensitive to terminal width

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#41863]
From the `flutter/packages/flutter_tools/` directory, if I run:

```bash
../../bin/cache/dart-sdk/bin/pub run test test/commands.shard/hermetic/doctor_test.dart
```
from a terminal with `COLUMNS=80`, I get failures in the "doctor with fake validators validate non-verbose output format for run with crash" and "doctor with fake validators validate non-verbose output format for run with an async crash" tests, both complaining about the way that the Flutter Doctor output is line-wrapped:

>             Expected: ... or message below is  ...
>               Actual: ... or message\n      be ...

If I make my terminal window larger (e.g. `COLUMNS=238`) or pipe output to a file, the test succeeds.

(I'm running from the master branch as of commit 8c6d60bcf on a Linux x64 system.)

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/42015
