### ISSUE TITLE
flutter build bundle only one bundle can exist at a time

### ISSUE THREAD

**Issue by Drakirus** [flutter/flutter#41861]
Split of https://github.com/flutter/flutter/issues/41352#issuecomment-537709454
I make heavy uses of `build bundle` and have found out an issue that appears on `Flutter 1.10.7-pre.123 ` and leads to the "could not resolve the kernel binary" error.
This issue appears when using the `--asset-dir` flag. 

flutter version:
```log
Flutter 1.10.7-pre.123 • channel master • http://github.com/flutter/flutter
Framework • revision bedf46d06e (6 minutes ago) • 2019-10-02 15:21:45 -0700
Engine • revision aa8fcbb652
Tools • Dart 2.6.0 (build 2.6.0-dev.4.0 98b286de21)
``` 

Steps to reproduce:
```sh
$ flutter build bundle --asset-dir /tmp/test
$ tree /tmp/test # looks good
/tmp/test
├── AssetManifest.json
├── FontManifest.json
├── isolate_snapshot_data
├── kernel_blob.bin
├── LICENSE
├── packages
│   └── cupertino_icons
│       └── assets
│           └── CupertinoIcons.ttf
└── vm_snapshot_data
$ flutter build bundle --asset-dir /tmp/test2
$ tree /tmp/test2 # also looks good
/tmp/test2
├── AssetManifest.json
├── FontManifest.json
├── isolate_snapshot_data
├── kernel_blob.bin
├── LICENSE
├── packages
│   └── cupertino_icons
│       └── assets
│           └── CupertinoIcons.ttf
└── vm_snapshot_data
# BUT
$ tree /tmp/test # gets deleted
/tmp/test
└── packages
    └── cupertino_icons
        └── assets
```
Pinging @jonahwilliams as I think it is related to tooling.

**Comment by jonahwilliams** [comment]
The default behavior of assemble is to clean outputs from old builds automatically, provided it thinks they are the same build. In this case, changing the output directory should likely qualify as a "different build" so they should not be deleted. It should be straightforward to update the rules so that output-dir is treated as an input
