### ISSUE TITLE
[firebase_crashlytics] Support the v2 Android embedder plugins API

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#41870]

**Comment by kroikie** [comment]
@amirh

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/316. Any further collaboration will be done there.

**Comment by kroikie** [comment]
To avoid confusing with project https://github.com/flutter/flutter/projects/59 this issue will remain open here till resolved.

**Comment by gaaclarke** [comment]
I upgraded crashlytics but it can't be committed because the tests don't work.
Related issue: https://github.com/flutter/flutter/issues/44142
Related code: https://github.com/gaaclarke/flutterfire/commit/42960058487a7ebb43731bd3cbf44bd9d051930d
