### ISSUE TITLE
[firebase_ml_vision] Support the v2 Android embedder plugins API

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#41875]
https://github.com/FirebaseExtended/flutterfire/pull/275

**Comment by kroikie** [comment]
@amirh

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/309. Any further collaboration will be done there.

**Comment by kroikie** [comment]
To avoid confusing with project https://github.com/flutter/flutter/projects/59 this issue will remain open here till resolved.

**Comment by xster** [comment]
This is in the ready to review column. Can we link the PR from here so we can help with the review?
