### ISSUE TITLE
[firebase_in_app_messaging] Support the v2 Android embedder plugins API

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#41873]

**Comment by kroikie** [comment]
@amirh

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/313. Any further collaboration will be done there.

**Comment by kroikie** [comment]
To avoid confusing with project https://github.com/flutter/flutter/projects/59 this issue will remain open here till resolved.

**Comment by gaaclarke** [comment]
https://github.com/gaaclarke/flutterfire/pull/new/in-app-messaging . I got this one mostly updated, just haven't been able to get step 14 working, running the tests.
