### ISSUE TITLE
[firebase_dynamic_links] Support the v2 Android embedder plugins API

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#41872]
https://github.com/FirebaseExtended/flutterfire/pull/1372

**Comment by kroikie** [comment]
@amirh

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/314. Any further collaboration will be done there.

**Comment by kroikie** [comment]
To avoid confusing with project https://github.com/flutter/flutter/projects/59 this issue will remain open here till resolved.
