### ISSUE TITLE
Change terminology around Flex

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4189]
From the point of view of the Flex implementation, there's children with fixed sizes, and children that are flexible and whose sizes need to be established.

But from the point of view of Flex users, the definitions don't make sense. The "fixed" children are the ones that can have any size they want, and the "flexible" children are the ones that get given a fixed size.

I've had multiple people say sentences along the lines of "oh, I have to use Flexible so that they get a fixed size" to me while I've been helping them.

**Comment by abarth** [comment]
Closing as duplicated of #5169
