### ISSUE TITLE
Flutter Widget still received event when show native view controller.

### ISSUE THREAD

**Issue by eitguide** [flutter/flutter#41890]
1. I have a main page, in this page I call native method to show native controller (UIViewController)
2. In my View Controller and have  a button have the same location with button show native controller in main page.
3. When I click button on native view controller then event onTap of button in main page still call.

**Comment by BondarenkoStas** [comment]
@eitguide Please provide your flutter doctor -v output. 
Also, please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by eitguide** [comment]
My flutter doctor log
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F132, locale en-VN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by eitguide** [comment]
I created demo project to produce this issue:
https://github.com/eitguide/PresentNativeControllerFlutterIssue

**Comment by eitguide** [comment]
I resolved issue by change some code in AppDelegate but i don't it working :)))
```swift
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    
    let flutterViewController = self.window.rootViewController as! FlutterViewController
    let nativeChannel = FlutterMethodChannel.init(name: "nghianv/present_controller_native", binaryMessenger: flutterViewController.binaryMessenger)
    

    nativeChannel.setMethodCallHandler { [weak self] (methodCall, result) in
        guard let self = self else { return }
        if(methodCall.method == "presentController") {
            let testViewController = TestViewController()
            self.window.rootViewController?.present(testViewController, animated: true, completion: nil)
            result(nil)
        }
    }

    
    let navigationVC = UINavigationController(rootViewController: flutterViewController)
    navigationVC.isNavigationBarHidden = true
    window.rootViewController = navigationVC
    window.makeKeyAndVisible()
    
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```

**Comment by darshankawar** [comment]
Hi @eitguide,
Is this still a valid issue ?
I tried to replicate the code sample you shared above, but getting below error related to `MethodChannel`:

`[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method presentController on channel nghianv/present_controller_native)`

If issue still persists, can you provide a complete minimal code sample ?
Thanks.

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
