### ISSUE TITLE
[google_maps] iOS 13 Google Maps

### ISSUE THREAD

**Issue by Stewioie** [flutter/flutter#41899]
I use 0.5.21+7

When I open maps on iOS 13 device

I got the following error and crash:

2019-10-03 11:35:38.415560+0200 Runner[30496:190271] ((null)) was false: Reached the max number of texture atlases, can not allocate more.

**Comment by BondarenkoStas** [comment]
@Stewioie it's the error form maps-platform, not from google_maps_flutter, so probably related to the implementation. 
Please provide your flutter doctor -v output.
Do you encounter it only while using iOS13 device?
Can you come up with some code example which reproduces the error?

**Comment by Stewioie** [comment]
I downgraded the SDK from 3.4 to 2.7 and works.

You were right. Nothing with flutter package.
