### ISSUE TITLE
Can't run flutter app, sends crash report while initializing gradle

### ISSUE THREAD

**Issue by quentgar** [flutter/flutter#41902]
I recently added the firebase_database plugin to my flutter application but I directly run into a problem while trying to launch the app on my device.
![image](https://user-images.githubusercontent.com/56115920/66121661-fdcb4100-e5dd-11e9-96a6-9cef4cac59e4.png)

As a consequence I tried running the flutter doctor command and I receive messages concerning my android sdk installation.
![image](https://user-images.githubusercontent.com/56115920/66121761-3c60fb80-e5de-11e9-9af0-4339c20f89e6.png)
![image](https://user-images.githubusercontent.com/56115920/66121835-5e5a7e00-e5de-11e9-9bfd-4c229478a077.png)
However I can't upgrade my android sdk version because of a problem concerning the java.se.ee module.
I tried many of the solutions that were proposed on forums like downgrading my java version to 8 instead of 12 but none of them worked for me.

**Comment by BondarenkoStas** [comment]
@quentgar Please do not include screenshots of code, this prevents it from being copied.
Do you have path to your sdk set correctly? 
Can you please paste the log generated (flutter_04.log)?

**Comment by quentgar** [comment]
Thanks for the advice. Here the log generated.
[flutter_04.log](https://github.com/flutter/flutter/files/3687451/flutter_04.log)

**Comment by escamoteur** [comment]
double of https://github.com/flutter/flutter/issues/31116
