### ISSUE TITLE
google_sign_in does not work when building an appbundle (ApiException: 10)

### ISSUE THREAD

**Issue by Simpler1** [flutter/flutter#41909]
## Steps to Reproduce

1. Clone https://github.com/flutter/plugins.git
2. [Generate debug key](https://developers.google.com/android/guides/client-auth)
3. Create a Firebase project on the [Firebase site](https://console.firebase.google.com/)
4. Add Android app to Firebase site
5. Enter SHA1 debug key on the Firebase site
6. Verify that your [email is entered on the Firebase site](https://github.com/flutter/flutter/issues/33303)
7. Enable the Google as a Sign-in Method on the Firebase site under Authentication
8. Download the `google-services.json` file and put it in the `android/app/` directory
10. Update `applicationId `in `android/app/build.gradle`
9. Build the flutter app using **`flutter build appbundle --debug`**
10. Test the **app.abb** file on the Firebase site under Test Lab using Robo Test

The following error will be generated by the `signIn()` method:

**PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)**

This problem only occurs when building an appbundle (and does not occur when building an apk) and it only occurs for new users who have not previously logged into the application successfully.  

## Logs

[log.zip](https://github.com/flutter/flutter/files/3686823/log.zip)

```
$ flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.17763.740], locale en-US)
    • Flutter version 1.9.1+hotfix.4 at C:\Programs\flutter
    • Framework revision cc949a8e8b (6 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\user1\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\user1\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\user1\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by veenatic82** [comment]
facing the same issue as well. With offline installation using buildtool works

**Comment by veenatic82** [comment]
Found this answer in stackoverflow which seems to work for me. https://stackoverflow.com/a/53663789/11602890

**Comment by TahaTesser** [comment]
Hi @Simpler1 
Check out this [comment](https://github.com/flutter/flutter/issues/41909#issuecomment-548931910) above 
if you're still experiencing this issue with latest stable channel
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
please write in the comments and I will reopen it 
Thank you
