### ISSUE TITLE
microbenchmarks_stock_build_iteration regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#41919]
First occurred at 8c6d60bcfd71db2cd98d337d8466f9142919b7a2.

**Comment by Hixie** [comment]
I'm bisecting.

**Comment by jason-simmons** [comment]
Did a bisect - looks like this started at https://github.com/flutter/flutter/commit/4512a1c1b72d36c67ebe1f0748d0e589b3057ed0

**Comment by Hixie** [comment]
That certainly makes more sense, but then why does the devicelab graph so clearly suggest otherwise? o_O

**Comment by jason-simmons** [comment]
The devicelab graphs are missing a few commits between https://github.com/flutter/flutter/commit/0af2a84cbbb69c8a3ea33a389b9e893e6de8ef4d and https://github.com/flutter/flutter/commit/8c6d60bcfd71db2cd98d337d8466f9142919b7a2

**Comment by Hixie** [comment]
but they're not missing 4512a1c, which is just after 8c6d60b. Or is the order on devicelab wrong?

**Comment by Hixie** [comment]
woah, devicelab's commits aren't at all the same as what's in git

**Comment by Hixie** [comment]
ok let's deal with the devicelab problem separately, and leave this issue to be the regression

cc @gspencergoog

**Comment by Hixie** [comment]
devicelab issue is https://github.com/flutter/cocoon/issues/420
