### ISSUE TITLE
cloning flutter projects problems

### ISSUE THREAD

**Issue by goondeal** [flutter/flutter#41912]

**Comment by goondeal** [comment]
Has anyone ever cloned flutter_architecture_samples => "https://github.com/brianegan/flutter_architecture_samples" and was able finally to go through it and his mind still fine ??? 

please tell me how, the "package get" fails due to versions incompatibility of git and the driver, I tried switching to "channel dev" as a solution from a closed issue about the same problem but did not work also

**Comment by BondarenkoStas** [comment]
@goondeal It's not a flutter repo, and I think the problems are in particular example you trying to run. What exactly are you doing? Please provide your flutter doctor -v output. What is the fail log?
Also, I would advise you to post it to StackOverflow as well as help there may come faster.

**Comment by janmoppel** [comment]
Hello @goondeal !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
