### ISSUE TITLE
Tabs and scrolling demo can crash - null.scrollTo()

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4193]
This occurred while swiping repeatedly and rapidly in one direction.

```
Running lib/main.dart on Nexus 5...
--------- beginning of main
Observatory listening on http://127.0.0.1:48446
Diagnostic server listening on http://127.0.0.1:57845
Application running.
Type "h" or F1 for help, "r" or F5 to restart the app, and "q", F10, or ctrl-c to quit.
W/ActivityManager: Unable to start service Intent { cmp=com.google.android.gms/.phenotype.service.PhenotypeCommitChimeraService (has extras) } U=0: not found
E/flutter : [ERROR:dart_error.cc(17)] Unhandled exception:
E/flutter : The null object does not have a method 'scrollTo'.
E/flutter : 
E/flutter : NoSuchMethodError: method not found: 'scrollTo'
E/flutter : Receiver: null
E/flutter : Arguments: [0.0]
E/flutter : #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
E/flutter : #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
E/flutter : #2      TabsDemoState.build.<anonymous closure>.<anonymous closure> (/builds/dev/flutter/examples/flutter_gallery/lib/demo/tabs_demo.dart:46)
E/flutter : #3      State.setState (package:flutter/src/widgets/framework.dart:419)
E/flutter : #4      TabsDemoState.build.<anonymous closure> (/builds/dev/flutter/examples/flutter_gallery/lib/demo/tabs_demo.dart:44)
E/flutter : #5      TabBarSelectionState.value=.<anonymous closure> (package:flutter/src/material/tabs.dart:599)
E/flutter : #6      _RootZone.runUnary (dart:async/zone.dart:1204)
E/flutter : #7      _FutureListener.handleValue (dart:async/future_impl.dart:131)
E/flutter : #8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
E/flutter : #9      _Future._propagateToListeners (dart:async/future_impl.dart:667)
E/flutter : #10     _Future._completeWithValue (dart:async/future_impl.dart:477)
E/flutter : #11     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
E/flutter : #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter : #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```

**Comment by HansMuller** [comment]
In this case, when the app is notified that the selected tab has changed the Scrollable that corresponded to the newly selected TabBarView has been discarded. So its GlobalKey's currentState is null.

The source of this problem appears to be that the TabBarSelection onChanged() only callback runs when the animation between TabBarView's (between the old and newly selected tab) has completed, and the TabBarViews are materialized and discarded as needed.  The TabBarViews are implemented with a PageableList and only two tab pages (for taps on a tab) or three tab pages (for TabBarView left/right drags) are materialized by the PageableList at any time. It looks like it's posisble for the PageableList to be rebuilt more than once before the onChanged callback runs.

**Comment by eseidelGoogle** [comment]
Similar to https://github.com/flutter/flutter/issues/4195, customer leafy worked around by skipping the test.

**Comment by zoechi** [comment]
I can't reproduce #4195 Do you think this is still an issue?

**Comment by HansMuller** [comment]
Unfortunately this bug corresponds to versions of the tabs implementation and the tabs demo that no longer exist. I can no longer reproduce the crash and code path that was failing is gone. I'm going to close this issue. It's a shame that it has taken so long!
