### ISSUE TITLE
Windows testing capacity is too low (Windows pre-commit tests disabled on cirrus)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#41941]
We currently have tests disabled on Windows because scheduling shards takes too long.

**Comment by christopherfujino** [comment]
Is this the new normal? It's definitely happened more than once that the windows tools_test caught errors in my code.

**Comment by Hixie** [comment]
My goal (see https://github.com/flutter/flutter/pull/41880) is to try to run most of the tests when they're relevant, though some shards on macos and windows, e.g. web_tests-windows, only run for rolls, changes to dev/, and post-commit.

It's not the new normal; once we can figure out how to increase our capacity we will turn all these back on.

The overarching goal is that a PR should be able to get a red/green result and be ready to land within 30 or so minutes of being uploaded, ideally a lot less. Doing this will require reducing the time to schedule the tasks, and rebalancing the shards so that no one shard takes much longer than the others.

**Comment by godofredoc** [comment]
All the windows tests are enabled and running on LUCI.
