### ISSUE TITLE
macOS testing capacity is too low (macOS pre-commit tests disabled on cirrus)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#41940]
We currently have tests disabled on macOS because scheduling shards takes too long.

**Comment by dnfield** [comment]
We have a bug open with Chrome infra about this  - but it's not publicly visible.

**Comment by fkorotkov** [comment]
Is it implying that "scheduling shards **on Cirrus** takes too long"? There was an alert yesterday for 50 minutes 26 seconds that scheduling exceeded 30 minutes but overall p99 is under 5 minutes with daily p99 from 29 to 76 seconds.

**Comment by dnfield** [comment]
We disabled nearly all of our mac presubmits because we'd routuinely run into scheduling issues - PRs would sometimes take over an hour to schedule, and sometimes even when they were scheduling they'd face issues like git timeouts. We also were using compute credits for macs on presubmits to try to get scheduling better, but even with that we were burning through them pretty quickly as our commit volume went up.

This bug is generally about increasing our mac capacity so we can re-enable tests and continue to add more.

**Comment by fkorotkov** [comment]
Got it. So it's related to the early August events when there was a quick 2x increase in usage resulted in #37880. I was just worried that this issue was referring an ongoing issue that I was not aware of. 🙌

**Comment by Hixie** [comment]
I think one problem here (and in https://github.com/flutter/flutter/issues/41941 for Windows) is just that there's a limit to the number of concurrent tasks so even if they all get scheduled immediately, they still don't all actually run immediately. Other problems are that sometimes the runs fail then get rerun, which adds to the actual time it takes to "really" get started.

For example consider https://cirrus-ci.com/task/5406603418796032, which ran with compute credits. It spent 10 minutes on the first run which failed (no idea if we were charged for that run but the failure was during the clone so out of our control), then took another 13 minutes or so to get scheduled again. So that's 23 minutes before the test really got under way. 

The Windows bots aren't running with compute credits, so the situation is correspondingly worse. For example consider https://cirrus-ci.com/task/6544684591087616 which took over 1h45m to start. Of the 11 shards on that PR, 9 took more than 15 minutes to get started (one had a similar cloning failure as above; the times for the long shards were roughly 15m, 15m, 30m, 45m, 50m, 1h10m, 1h35m, 1h45m, and 1h45m to start, the longest one to end took 2h15m to reach a result, of which 10m was setup and 20m testing).

On Linux it's less of an issue because the bots seem to all run in parallel; the 17 shards on Linux all started within about 20 minutes or so, without compute credits.

I'm not familiar with the costs and whether it would be practical to use compute credits for PRs for Windows (or whether it's really affordable for us to do it for Macs). We would like to dramatically increase our testing, the 41 or so shards we have today could easily be multiplied by two (for example we'd like to run lots of community tests, all the plugin's tests, run the analyzer on all the packages in pub, etc).

Anyway, this bug is tracking the fact that we have some mac tests turned off in some cases so that we don't run all 41 shards in all PRs.

**Comment by godofredoc** [comment]
All the windows tests are now enabled and running on LUCI.
