### ISSUE TITLE
Validate that the incremental_compiler improves the Flutter for Web workflow

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#41951]
This is currently blocked on implementing the prototype for integration of the dev_compiler with the incremental compiler. Once that is done, we should via some opt-in allow enabling or disabling the incremental compiler to validate that it improves performance of hot reload for the web.

there may be other benefits to adopting it, such as if we can improve browser reload speed by adopting the "legacy" module format, and allowing updating .packages on the fly.

Update: This has been implemented under a config flag, but still needs to be enabled by implementing some missing functionality (dwds and plugins)

**Comment by yjbanov** [comment]
@jonahwilliams Should we assign a milestone for this issue?

**Comment by jonahwilliams** [comment]
Updated

**Comment by jonahwilliams** [comment]
Update target milestone to Q1

**Comment by jonahwilliams** [comment]
Update: plugin support is complete, awaiting full dwds integration
