### ISSUE TITLE
Tabs widget does not accept drag events during the snap transition

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#4195]
## Steps to Reproduce

In the gallery app's "Tab" demo, drag half-way between two tabs and release. The tab widget will snap to the closest tab with an animated transition. During that transition the tab widget will not accept any drag gestures. You have to wait for the animation to complete. This is easy to reproduce in slow animation mode. The behavior is not consistent, you may need to try several times to see it, but it doesn't take long to reproduce.

## Flutter Doctor
```
[✓] Flutter (on Mac OS, channel unknown)
    • Flutter at /Users/yjbanov/code/flutter/flutter
    • Framework revision 43dd9450af (3 months ago), engine revision 7fab0c350b

[✓] Android toolchain - develop for Android devices (Android SDK 22.0.1)
    • Android SDK at /Users/yjbanov/code/android-sdk-macosx
    • Platform android-22, build-tools 22.0.1
    • Java(TM) SE Runtime Environment (build 1.8.0_65-b17)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```
/cc @HansMuller

**Comment by devoncarew** [comment]
Just FYI, above, your framework reversion says its 3 months old.

**Comment by yjbanov** [comment]
@devoncarew It seems `flutter doctor` gets the date recorded in the git commit metadata. If you rebase an old commit on top of the latest it will still show the old date. The commit that I'm rebased on top of is:

```
commit 4aa894984ffd21527a388543009a947818e45749
Author: Adam Barth <abarth@chromium.org>
Date:   Wed May 25 10:23:01 2016 -0700
```

**Comment by eseidelGoogle** [comment]
This was causing a test to break, but customer: leafy worked around it by ignoring the test. :(

**Comment by zoechi** [comment]
I can't reproduce.
