### ISSUE TITLE
Flutter Gallery links to code don't load

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#41953]
I tried looking at the code for a few widgets and the page it displays is blank

**Comment by BondarenkoStas** [comment]
@ThinkDigitalSoftware Please specify which links. Do you mean `API docs` links in https://flutter.github.io/samples/gallery/ or ther is something else?

**Comment by ThinkDigitalSoftware** [comment]
Sorry about that. Yes. I don't know exactly which links since they don't load the corresponding page. I forgot where it used to link to, but I assume it's the api links.

**Comment by ThinkDigitalSoftware** [comment]
Yes, it's API documentation. 
![Screenshot_20191004-114145](https://user-images.githubusercontent.com/23037821/66231726-06824c80-e69c-11e9-8fc1-5b610c133540.jpg)
![Screenshot_20191004-114141](https://user-images.githubusercontent.com/23037821/66231728-06824c80-e69c-11e9-8e73-c07763a8eddd.jpg)

**Comment by pedromassangocode** [comment]
Closing as this seems to be working as expected on the latest version of the Flutter Gallery app.

<img width="220" height="500" src="https://user-images.githubusercontent.com/67424416/92724452-8ca21b00-f362-11ea-9851-ede66b7b9352.png">
