### ISSUE TITLE
Auto-increment build number found in pubspec.yaml

### ISSUE THREAD

**Issue by Levi-Lesches** [flutter/flutter#41955]
## Use case
When publishing an app to an app store (notoriously Apple's App Store), including an up-to-date build number is critical to being able to upload. Otherwise you will need to rebuild the app, which can take several minutes. 

## Proposal
Automatically update the build number in `pubspec.yaml` on any call to `flutter build` (or maybe just the main ones since I remember hearing somewhere `flutter build bundle` and `flutter build aot` are used internally...)

So if my `pubspec.yaml` showed `version: 2.0.0+1`, then running `flutter build ios` would change it to: `version 2.0.0+2`. 

This is a feature that almost everyone automates already, so I figure built-in support is probably the way to go. And this might have to be in the next *major* version of Flutter to avoid incrementing the value twice (once by Flutter and once by the user's script), although AFAIK that's not really an issue.

**Comment by escamoteur** [comment]
How should the build tool know which is the next version number you want?

Shouldn't this be the responsibility of your build system? I don't like if flutter build changes my pubspec file.
I would propose that pubspec.yaml get's an option pre/post build script entry.

**Comment by Levi-Lesches** [comment]
I don't think anyone should be automatically incrementing the version number, just the _build number_. So basically the number after the plus. This is supposed to be incremented after every build, or else Apple and Firebase (and maybe Google) will freak out. So it's standard convention to increment by one on every build.

**Comment by rnagella** [comment]
Since flutter is capable of reading and setting the build name and build number from pubspec.yaml file, having a command `flutter version` with following option is very useful.
1. We don't have to maintain separate iOS and Android build number and build name (since making any code changes lead to both platform submission/ internal identity)
2. Source of truth in our source control when the build name/build number changes.

~~~
flutter version --major  1.0.0  -> 2.0.0
flutter version --minor  1.0.0  -> 1.1.0
flutter version --patch  1.0.0  -> 1.0.1
flutter version --build_number 1.0.0+1 -> 1.0.0+2
~~~

**Comment by Levi-Lesches** [comment]
On the iOS side, I seem to have passively noticed (don't have enough time to confirm) that running `flutter build ios` does in fact increment the build number by one. Again, haven't directly observed this, just noticed that I haven't actually had to do it manually in a while. Android, on the other hand, still keeps the version number the same though -- and it can get annoying compiling an apk, only to have to increment the build number and recompile. 

> Source of truth in our source control

I totally agree, and I think this source should be the `version` field of the `pubspec.yaml` file. I believe for Android it already is, and I _believe_ for iOS it is in fact used by `flutter build ios` (If you haven't noticed, I don't compile often for iOS myself). 

What I think can help optimize the process would be for a command, either `flutter packages` or something else, to read the `version` field from `pubspec.yaml` and replace the version numbers in the platform-specific code. This can be run by `flutter build`, and should keep things nice and neat, while making it very clear to users when platform-specific folders will change (so you know which commands are going to make you have to commit which folders).

**Comment by rnagella** [comment]
`flutter build ios does in fact increment the build number by one.` - It won't increment automatically, it reads what ever value in `pubspec.yaml` file and sets it to `ios/flutter_export_environment.sh`, which then get written to `Info.plist` file

**Comment by rnagella** [comment]
`I don't think anyone should be automatically incrementing the version number` - You are right, the CI/CD might not take a decision on when to increment patch/minor/major(Although, you can tell when to increment based on a flag commit pushed to development/master branch).
As mentioned and you agree with me as well, It would be nice to have shorthand commands to modify the patch/minor/major build name and to have a source of truth in the `pubspec.yaml` file

**Comment by Levi-Lesches** [comment]
>  It won't increment automatically, it reads what ever value in `pubspec.yaml` file and sets it to `ios/flutter_export_environment.sh`, which then get written to `Info.plist` file

Actually, I think it does. Like I said I ran the build command several times without touching the `pubspec.yaml`, and the build number goes up, without changing the `pubspec`. Either way, I use a separate Mac for building so I can't check right this moment whether that's true or not. I just know I haven't touched the `pubspec` on my Mac like ever. 

> Although, you can tell when to increment based on a flag commit pushed to development/master branch

That's an interesting idea, I wonder if that should become standard convention. The only exception I would say is sometimes new branches are made specifically to do code cleanup which shouldn't change the version. 

> a source of truth in the pubspec.yaml file

If there really is a disconnect between iOS version and `pubspec`, then we really do need to consolidate the versioning system, especially if web and desktop support are coming.

**Comment by anondev32** [comment]
Is there any update on this? I did for now used the CI_PIPLINE_ID with GitLab CI, but this actually can lead to some very strange behaviours where the build number is something like 97011242 which is not very good imho. If you use a tool like fastlane, there is a script that increments the build number on ios but not on android.

**Comment by lynn** [comment]
I use this bash script to bump the build number and tag it:

```bash
#!/bin/bash
set -e

# Find and increment the version number.
perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/$1.($2+1)/e' client/pubspec.yaml

# Commit and tag this change.
version=`grep 'version: ' client/pubspec.yaml | sed 's/version: //'`
git commit -m "Bump version to $version" client/pubspec.yaml
git tag $version
```

**Comment by jmagman** [comment]
I don't think Flutter should be int the business of auto-incrementing the build number.  Every project will have different logic for when this should be bumped (CD system, deployed to QA, deployed to internal dogfooding, deployed via MDM, published to App store), and Flutter doesn't have any hooks to know when your iOS app has been published to the App Store and therefore should be bumped.

Xcode has a lot more insight into these hooks via archiving, validation, and publishing, and even it won't don't automatically touch your build number.
https://developer.apple.com/library/archive/qa/qa1827/_index.html

**Comment by Levi-Lesches** [comment]
The build number is fine to play around with though, it is meant to be changed every time the project is built, and if it isn't, the project will most likely have to be rebuilt anyway. I do think that there should be an option to disable it though.

**Comment by jmagman** [comment]
> it is meant to be changed every time the project is built, and if it isn't, the project will most likely have to be rebuilt anyway

That's a fine way to use it, but that's not how everyone does.
On my Catalina machine, Xcode's bundle version is 15712.  Safari's is 15608.4.9.1.3.  Calculator is 213.2.  These are likely incremented when there's an internal build system-built version of the app, not every time an individual developer builds it (or it would be in the hundreds of millions probably), which is the `flutter build` equivalent you suggest.  What if you have multiple team members locally bumping versions on every `flutter build`?  What does it mean that one is lower than the other?  Which version should be preferred on merge conflicts?  Every product has their own workflow for incrementing it and what incrementing it actually should imply and which dot version should be bumped, or if there should be any dots.  And it gets more complicated if you have a project containing a macOS and iOS version of the app sharing a back-end framework, say, and you want to increment each one separately.

So automatic--maybe not.  @rnagella has a suggestion for still manually requiring it, but making it easier, which was also suggested in https://github.com/flutter/flutter/issues/10086#issuecomment-301473217.  It could be incorporated into https://github.com/flutter/flutter/issues/10403 on publish ("Your build number is 123, would you like to increment it?")

**Comment by Levi-Lesches** [comment]
> Calculator is 213.2

Yeah, that doesn't include the build number. Versioning in Dart works like `major`.`minor`.`patch`+`build` -- so like 1.0.1+4, where `4` would be the build number. There's almost always a build number that can be harmlessly incremented.

**Comment by jmagman** [comment]
> > Calculator is 213.2
> 
> Yeah, that doesn't include the build number. Versioning in Dart works like `major`.`minor`.`patch`+`build` -- so like 1.0.1+4, where `4` would be the build number. There's almost always a build number that can be harmlessly incremented.

On iOS and macOS Flutter maps the build name (in your example 1.0.1) to CFBundleShortVersionString and the build number (in your example 4) to CFBundleVersion.  I was looking at CFBundleVersion for the number I cited for various macOS apps, since you requested build number be bumped.  It seems like someone took pub versioning and tried to mash it into Apple's version keys, and it didn't shake out into the same concepts at all... It's caused us a good amount of continuing trouble, actually.

Anyway I don't mean to rabbit hole this issue, I realize you are asking for automatic versioning on all platforms, not just iOS.  😃

**Comment by escamoteur** [comment]
What would help is a possibilty to define a custom prebuild/postbuild script in pubspec. This way this can be done the way one likes it to be done.

**Comment by lukepighetti** [comment]
I've been putting together a little deploy script, it's not finished, but maybe it's helpful to someone

```
# Generate icons
flutter pub run flutter_launcher_icons:main

# Bump build number
perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/$1.($2+1)/e' pubspec.yaml

# Build iOS
flutter build iOS
```

**Comment by syonip** [comment]
@lukepighetti Thanks for the bump script, I noticed that I need to bump the version numbers both before and after the "+" in order to pacify both app stores, so I modified it a bit:
```
perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.($2+1).$3.($4+1)/e' pubspec.yaml
```

**Comment by jonahwilliams** [comment]
Based on @jmagman s response above, I'm going to close this issue as it does not seem like a good idea for Flutter to automate.

**Comment by ad-on-is** [comment]
If anyone is interested, I've written a small go-tool, which allows bumping the version from within the CLI. It can also easily be used in git-hooks.

Check it out here: https://gitlab.com/ad-on-is/pubumgo

**Comment by mindthefish** [comment]
> If anyone is interested, I've written a small go-tool, which allows bumping the version from the cli. It can also easily be used in git-hooks.
> 
> Check it out here: https://gitlab.com/ad-on-is/pubumgo

Thanks a lot. This is in fact very helpful!

**Comment by Jiropole** [comment]
I'm not a fan of automating version # changes, but I do like to pin build #'s to git. Here's my script for this.

```
BUILD_NUMBER=`git rev-list --all|wc -l|xargs`

printf "What would you like to build?\n"
select platform in "Android App Bundle" "Android APK" "iOS"; do
  echo "Preparing build #$BUILD_NUMBER"
  case $platform in
      "Android App Bundle" ) flutter build appbundle --build-number $BUILD_NUMBER; break;;
      "Android APK" ) flutter build apk --build-number $BUILD_NUMBER; break;;
      "iOS" ) flutter build ios --build-number $BUILD_NUMBER; break;;
  esac
done
```

**Comment by vamsi575kg** [comment]
> @lukepighetti Thanks for the bump script, I noticed that I need to bump the version numbers both before and after the "+" in order to pacify both app stores, so I modified it a bit:
> 
> ```
> perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.($2+1).$3.($4+1)/e' pubspec.yaml
> ```

@syonip Can you provide the perl command to update the pubspec.yaml version with the external input of version no and build no. 
i would be asking for version and build input from user via a shell script and want to update yaml with the captured inputs

**Comment by banool** [comment]
To make this even easier, I recommend putting this in your pre-commit-hook:

`.git/hooks/pre-commit`:
```
#!/bin/bash

perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.($2+1).$3.($4+1)/e' pubspec.yaml
git add pubspec.yaml
```

Don't forget to make it exectuable:
```
chmod +x .git/hooks/pre-commit
```

**Comment by jubinjacob19** [comment]
> > @lukepighetti Thanks for the bump script, I noticed that I need to bump the version numbers both before and after the "+" in order to pacify both app stores, so I modified it a bit:
> > ```
> > perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.($2+1).$3.($4+1)/e' pubspec.yaml
> > ```
> 
> @syonip Can you provide the perl command to update the pubspec.yaml version with the external input of version no and build no.
> i would be asking for version and build input from user via a shell script and want to update yaml with the captured inputs

@vamsi575kg 
You can use the following script which accepts the version as an argument
To increment, run it without any argument. 
To set a fixed version, run it using the version as the argument (e.g sh update_version.sh 1.0.0+15 )
`#!/bin/bash
set -e

if [ -z "$1" ]
then
  # Find and increment the version number if no argument passed
  perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/$1.($2+1)/e' pubspec.yaml
else
  # Set version as the argument passed
  sed -i '' "s/^version.*/version: $1/g" pubspec.yaml
fi

`

**Comment by jubinjacob19** [comment]
> > @lukepighetti Thanks for the bump script, I noticed that I need to bump the version numbers both before and after the "+" in order to pacify both app stores, so I modified it a bit:
> > ```
> > perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.($2+1).$3.($4+1)/e' pubspec.yaml
> > ```
> 
> @syonip Can you provide the perl command to update the pubspec.yaml version with the external input of version no and build no.
> i would be asking for version and build input from user via a shell script and want to update yaml with the captured inputs

@vamsi575kg  You can use the following script
`#!/bin/bash
set -e
if [ -z "$1" ]
then
  # Find and increment the version number if no argument passed
  perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/$1.($2+1)/e' pubspec.yaml
else
  # Set version as the argument passed
  sed -i '' "s/^version.*/version: $1/g" pubspec.yaml
fi`

**Comment by noveleven** [comment]
It is appropriate to use git tags as the version name. **version: tag number + incremented commit number**.

``` 
#!/bin/sh
TAG=`git describe --tags`
export TAG
perl -i -pe 's/^(version:)(\s*)((\d+\.)+\d+)(\+)(\d+)$/$1.$2.$ENV{TAG}.$5.($6+1)/e' pubspec.yaml
git add pubspec.yaml
