### ISSUE TITLE
Add sample of widget containing `gestureDetector` in its documentation 

### ISSUE THREAD

**Issue by pashute** [flutter/flutter#41962]
In the [documentation for the gestureDetector](https://github.com/flutter/flutter/blob/2d2a1ffec9/packages/flutter/lib/src/widgets/gesture_detector.dart#L151) Please add another sample with a widget containing a gestureDetector as a child with no children. 

Change the title of the original sample to something like "Sample code of a colored box wrapped in the `gestureDetector` widget"  and the remark inside to reflect that. Something like: 

    // Sample code of a colored box wrapped in gestureDetector 
    // which changes its color when tapped upon. 

The second sample's heading should be something like: "Sample code of a colored box containing a `gestureDetector` widget....

Or just add the "deubg" icon to the [documentation page](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html) on api.flutter.dev so that I can do it myself. 

Or do both... (add debug capability to the doc page, and also add the second sample)

**Comment by luizfranca** [comment]
@pashute, @BondarenkoStas, @goderbauer I added a proposal documentation for this issue here [#43786](https://github.com/flutter/flutter/pull/43786)
