### ISSUE TITLE
Flutter Post request with headers and body not working properly ? 

### ISSUE THREAD

**Issue by JayM96** [flutter/flutter#41964]
```
D/SharedPreferencesImpl( 9900): Time required to fsync /data/user/0/com.example.firebase_demo/shared_prefs/com.google.android.gms.measurement.prefs.xml: [<1: 0, <2: 0, <4: 0, <8: 1, <16: 0, <32: 0, <64: 0, <128: 0, <256: 0, <512: 0, <1024: 0, <2048: 0, <4096: 1, <8192: 0, <16384: 0, >=16384: 0]
I/flutter ( 9900): 404
I/flutter ( 9900): final error : jaym {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
```
Code : 
```
fetchDataFromServer() async {
    var body = {
      'per_page': 5,
      'since': 0,
    };
    var headers = {
      'content-type': 'application/json'
    };

    try {
      var response = await 
      var response = await http.post("https://api.github.com/users",headers:headers,body: json.encode(body));
      print(response.statusCode);

      if (response.statusCode == 200) {
        print("body : ${response.body}");
        print("json : ${json.decode(response.body)}");
      } else{
        print("final error : jaym " +response.body);
      }
    } catch (error) {
      print("error : ${error}");
      print("error : ${error.toString()}");
    }
  }
```
@zoechi  I don't find any issue in my code. I have already checked many forums. Suggest a hint if possible.

Thanks.

**Comment by superciccio** [comment]
hi,

you don't need  `json.encode(body)`

just pass the body

**Comment by JayM96** [comment]
> hi,
> 
> you don't need `json.encode(body)`
> 
> just pass the body

But, It says " type 'int' is not a subtype of type 'String' in type cast".

**Comment by superciccio** [comment]
var body = {
'per_page': '5',
'since': '0',
};

you know what field is int and what is not. you can do the conversion on the server side

**Comment by JayM96** [comment]
> var body = {
> 'per_page': '5',
> 'since': '0',
> };
> 
> you know what field is int and what is not. you can do the conversion on the server side

If i am doing you suggest still it gives me error code 404 with error "{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}"

**Comment by superciccio** [comment]
wrong url, https://api.github.com/user not users
you need also to authenticate

**Comment by JayM96** [comment]
@superciccio i don't want particular user. I want the list of user. So this is the correct url for my requirements.

**Comment by superciccio** [comment]
post is not allowed, get is.
:)

**Comment by escamoteur** [comment]
Please ask such questions on [stackoverflow](stackoverflow.com) , because we unfortunately not able to give individual development support here. 
This place is only for reporting bugs or suggesting new features.

**Comment by nanophp** [comment]
> Please ask such questions on [stackoverflow](stackoverflow.com) , because we unfortunately not able to give individual development support here.
> This place is only for reporting bugs or suggesting new features.

every newcomer facing the kind of problems. That's why It needs some documentation or FAQ pages for newcomers. It is not mature framework and people need more support. I don't mind @JayM96 and others use the GitHub repos as StackOverflow. This is a real problem day by day developers facing. It is not a type of question for example: "I need a create auth system but I don't know how to create it and so on.".

**Comment by Blekercm** [comment]
The same problem happened to me, in the Postman everything ok, but in flutter it was the error two days of loss that I could finally solve here I leave the example and it is ok in flutter

`import 'dart:convert';
import 'package:http/http.dart' as http;

Future<dynamic> suscribeAdd(String name, String email) async {
var client = http.Client();
try {
  var url = "http://localhost:2200/suscribe";
  var headers = {'Content-Type': 'application/json; charset=UTF-8'};
  var body = {'name': name, 'email': email};

  var response =
      await client.post(url, headers: headers, body: json.encode(body));
  return response.body;
} catch (error) {
  return null;
}`

**Comment by Blekercm** [comment]
The same problem happened to me, in the Postman everything ok, but in flutter it was the error two days of loss that I could finally solve here I leave the example and it is ok in flutter

import 'dart:convert';
import 'package:http/http.dart' as http;

Future suscribeAdd(String name, String email) async {
var client = http.Client();
try {
var url = "http://localhost:2200/suscribe";
var headers = {'Content-Type': 'application/json; charset=UTF-8'};
var body = {'name': name, 'email': email};

var response =
await client.post(url, headers: headers, body: json.encode(body));
return response.body;
} catch (error) {
return null;
}
