### ISSUE TITLE
Android Studio: Gradle update wrecks Android app

### ISSUE THREAD

**Issue by ksilz** [flutter/flutter#41973]
## Motivation

A brand-new Flutter app breaks when doing the suggested Gradle update in Android Studio &mdash; you can't run the Android app anymore afterward. 

I see at least four solutions:

1. Flutter somehow prevents Android Studio from suggesting the Gradle update.
1. A future Flutter release updates Gradle in the generated Android app so that Android Studio doesn't suggest a Gradle update anymore.
1. A future Flutter release changes Gradle in the generated Android app in such a way that that it survives the Android Studio Gradle update intact.
1. No changes are made in Flutter, but a big fat warning to **not** do the Gradle update in Android Studio is passed on to all Flutter developers.

## Steps to Reproduce

My Flutter version is v1.9.1+hotfix.4 on macOS 10.14.6, and I use Android Studio 3.5.1.

- Create a new Flutter project from the terminal with `flutter create --org "com.betterprojectsfaster.blog.flutter.intro" --androidx flutter_intro_3` 
- Change into the `flutter_intro_3` directory.
- Start app on Android emulator in the terminal: `flutter run -d "Android SDK built for x86"`
- The app works.
- Open the Android project in the `android` project folder in Android Studio.
- Run the app in the Android emulator with the green _Run app_ button in the toolbar.
- The app works.
- Check out the notification in the bottom right that urges you to update Gradle:

![Android Studio update notice](https://user-images.githubusercontent.com/1061209/66201121-7394e280-e69a-11e9-9d40-84b40dff26e3.png)

- Click on the _update_ link in the notice to see the full message:

![Android Studio update details](https://user-images.githubusercontent.com/1061209/66201164-8c9d9380-e69a-11e9-8f18-001034a6b476.png)

- Push the _Update_ button. 
- The update process runs but fails with an error:

![Android Studio update error](https://user-images.githubusercontent.com/1061209/66201268-df774b00-e69a-11e9-9165-dd2b2cd7cb9f.png)

- Run the app in the Android emulator again with the green "Run app" button in the toolbar again.
- The app doesn't work, and a configuration window with an error shows instead:

![Android Studio config error](https://user-images.githubusercontent.com/1061209/66201436-472d9600-e69b-11e9-9e6e-abbf8b7f4efd.png)

- Run the Android app again in the terminal: `flutter run -d "Android SDK built for x86"`
- The app fails to start with this error message:

```
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              0.6s
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "/Users/karsten/workspaces/me/services/better-projects-faster/test/flutter_intro_3/android/gradlew" exited abnormally:

> Configure project :app
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
  Command: /Users/karsten/workspaces/me/services/better-projects-faster/test/flutter_intro_3/android/gradlew app:properties


Please review your Gradle project setup in the android/ folder.
```

Here's my Flutter Doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale en-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by tb2761** [comment]
Look at your error message in Android Studio and read it carefully, because it says exactly what to do. You have to update your kotlin plugin to Version 1.3.10 and everything will works fine.

**Comment by ksilz** [comment]
@tb2761 You're right! In hindsight it is obvious, but when I read "plug-ins", I thought of IDE plug-ins.

So for my understanding:

- The Flutter-generated code uses both old Gradle and Kotlin versions.
- The Gradle update process in Android Studio updates Gradle first, but not Kotlin, and makes that fatal pitstop which threw me off.

Correct?

**Comment by tb2761** [comment]
First, flutter uses the newest version when the flutter version was tested. So yes now their can be a newer one.
Second, Android Studio use the gradle plugin you define or the newest one when no version is defined and show you a suggestion to update kotlin-gradle plugin, the gradle version and the kotlin version.
But you have to manually update the depencenies which placed in android/build.gradle
