### ISSUE TITLE
Emoji not rendering

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#41970]
When using a emoji inside a `Text`/`RichText`/`TextSpan` using a physical Android 10 device (Google Pixel 3 XL), compiled using Flutter's latest master release on Windows, the emoji doesn't render properly.

Also, when using it inside an app, when the `Text` with emoji is inside an `StatefulWidget` and it is updated, the emoji is rendered correctly (couldn't reproduce behavior with minimum sample app).

## Steps to Reproduce

1. Run sample app
2. Emoji is not rendered correctly

The first emoji is from Window's Emoji picker, the second one from Emojipedia

**Target Platform:** Android
**Target OS version/browser:** 10
**Devices:** Pixel 3 XL

## Sample app

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(TestWidget());
}

class TestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: <Widget>[
              Text('✈'),
              Text('✈️'),
            ],
          ),
        ),
      ),
    );
  }
}
```

## Flutter doctor

```
[√] Flutter (Channel master, v1.10.11-pre.3, on Microsoft Windows [VersiÃ³n 10.0.18362.387], locale es-ES)
    • Flutter version 1.10.11-pre.3 at C:\src\flutter
    • Framework revision dc03c44321 (42 minutes ago), 2019-10-04 04:01:43 -0400
    • Engine revision 759d3dba25
    • Dart version 2.6.0 (build 2.6.0-dev.5.0 7a7dcd1ed9)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Cristian\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Pixel 3 XL • 89PY09NNV • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by GaryQian** [comment]
Since it has been a while and we have landed font loading fixes in the meantime, can you confirm you are still seeing this? @Zazo032 Thanks!

**Comment by Zazo032** [comment]
Seems to be fixed, I'll close this. I faced a different issue with emoji rendering, but I'll open a separate issue to track it.

**Comment by GaryQian** [comment]
FYI, this may be related: https://github.com/flutter/flutter/issues/45947

**Comment by Zazo032** [comment]
It was a different one, on iOS, a `Text` with a plane taking off emoji was changed with a fire emoji, it's weird but I could only reproduce it once.
