### ISSUE TITLE
[Web] : Problem with Dio package in flutter web

### ISSUE THREAD

**Issue by DisIsGAndhi** [flutter/flutter#41977]
We have started with the Flutter web project. This project is working on mobile application when we run on web dio is giving the following error. 

 ```
Error ::: DioError [DioErrorType.RESPONSE]: XMLHttpRequest error.
Stacktrace ::: package:build_web_compilers/src/dev_compiler/dart_sdk.js 3992:11   throw_
package:dio/src/dio.dart 848:13

```

Flutter version :

```
[✓] Flutter (Channel master, v1.10.7-pre.23, on Linux, locale en_IN)
    • Flutter version 1.10.7-pre.23 at /home/ag-purplle/Downloads/flutter
    • Framework revision e0247442d0 (8 days ago), 2019-09-26 02:49:41 -0400
    • Engine revision 3713ecf107
    • Dart version 2.6.0 (build 2.6.0-dev.2.0 c6a14f4459)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/ag-purplle/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/ag-purplle/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/ag-purplle/Downloads/android-studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132
    • Server • web    • web-javascript • Flutter Tools

• No issues found!

```
Dio dependency version

`dio: ^3.0.3
`

**Comment by jonahwilliams** [comment]
This should probably be filled on https://github.com/flutterchina/dio. There is nothing in this stacktrace to indicate a flutter failure

**Comment by jkurtw** [comment]
I just noticed this note at https://github.com/flutterchina/dio:
"In order to support Flutter Web, v3.x was heavily refactored, so it was not compatible with version 3.x See here for a detailed list of updates."

Maybe there is a newer version you need to use?

**Comment by jkurtw** [comment]
Oh, I see 3.0.3 is the latest: https://github.com/flutterchina/dio/blob/master/dio/CHANGELOG.md

**Comment by jkurtw** [comment]
I'm able repro with Dio's simple example:
```
import 'package:dio/dio.dart';
void getHttp() async {
  try {
    Response response = await Dio().get("http://www.google.com");
    print(response);
  } catch (e) {
    print(e);
  }
}
```

In Chrome's developer console, I also see: 
`Access to XMLHttpRequest at 'http://www.google.com/' from origin 'http://localhost:49901' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I wonder if this is a problem when running locally.

**Comment by jkurtw** [comment]
Tried hosting on Firebase and Chrome / Safari are still not happy with it. 

@DisIsGAndhi please file an issue against Dio and reopen this if you believe Flutter needs to fix something here.

**Comment by jonahwilliams** [comment]
See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS for more information on why this doesn't work

**Comment by softmarshmallow** [comment]
this seems to be dio's internal problem. even `get` for google.com does not work. and i also checked my server's cors settings twice to allow all, yet wont work

**Comment by namchuai** [comment]
I have the same issue with dio v3.0.9. Gonna try again with http package and let you guys know the result later.

**Comment by namchuai** [comment]
FYI, adding support CORS from my server solved this issue. [http package](https://pub.dev/packages/http) give the same error.

More information:
My server is using Django and I need to follow this setting: https://stackoverflow.com/a/38162454/4700001

Hope it helps.

**Comment by softmarshmallow** [comment]
there is surely something magic going on back deep down dio or http package. both tested with same server, one with vue, one with flutter, both deployed.
only flutter's cors will get blocked. (and more fun part is, it not all blockes every route, but some specific routes. no rules i've found for this.)

**Comment by softmarshmallow** [comment]
+ also tested by postwomen, postman, insomnia. all same enviroment. (not local server, a remote server.)
driving me crazy.,.,.,.

**Comment by pengzhenkun** [comment]
I also encountered similar problems

**Comment by softmarshmallow** [comment]
@jkurtw please reopen this issue

**Comment by btphan95** [comment]
Disabling CORS policy on Chrome is a temporary solution. It's just frustrating that you have to manually call it before starting Chrome every. single. time.
https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

**Comment by chitgoks** [comment]
> this seems to be dio's internal problem. even `get` for google.com does not work. and i also checked my server's cors settings twice to allow all, yet wont work

agree. tested mine and it works if accessed from a different front end url using ajax. but it needs the properties to have the cookies written to browser.

```
xhrFields: {
         withCredentials: true
    },
    crossDomain: true,
```

so using dio and http, nothing happens, this looks more of a lib issue.

**Comment by arjun-c-369** [comment]
insert the below code completely on the .php file you are calling , right after the `<?php` line (ist line).

`if (isset($_SERVER['HTTP_ORIGIN'])) {
    // should do a check here to match $_SERVER['HTTP_ORIGIN'] to a
    // whitelist of safe domains
    header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
    header('Access-Control-Allow-Credentials: true');
    header('Access-Control-Max-Age: 86400');    // cache for 1 day
}
// Access-Control headers are received during OPTIONS requests
if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {

    if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD']))
        header("Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS");         

    if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']))
        header("Access-Control-Allow-Headers: {$_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']}");

}

header('Access-Control-Allow-Origin: *');

header('Access-Control-Allow-Methods: GET, POST');

header("Access-Control-Allow-Headers: X-Requested-With");`

**Comment by satyajitghana** [comment]
any working solution for this ?
i'm using http and dio package, but i get CORS issue even with GET on https://google.com/

**Comment by flutterq2** [comment]
All Possible Working Solution Added [[Solved] Error getting sensor data: DioError [DioErrorType.RESPONSE]: XMLHttpRequest error.](https://fluttercorner.com/error-getting-sensor-data-dioerror-dioerrortype-response-xmlhttprequest-error/)
