### ISSUE TITLE
Unable to build ios - project.pbxproj empty "The project ‘Runner’ is damaged and cannot be opened due to a parse error"

### ISSUE THREAD

**Issue by bytelyus** [flutter/flutter#41987]
Hi there, mates... I am having this issue suddenly by the face... I was working fine this morning, but when i got back from lunch, I am finding this funny error message when building for ios ... Can't even open module with the command 'Open iOS module in Xcode' which normally fixed many of my problems... :( 

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color build ios --simulator

## exception

ProcessException: ProcessException: Process "/usr/bin/xcodebuild" exited abnormally:
2019-10-04 18:15:08.021 xcodebuild[2016:19630] Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.}
xcodebuild: error: Unable to read project 'Runner.xcodeproj'.
	Reason: The project ‘Runner’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.

Path: /Users/xxx/IdeaProjects/master_gest/ios/Runner.xcodeproj
  Command: /usr/bin/xcodebuild -list

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:270:36)
<asynchronous suspension>
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:279:70)
<asynchronous suspension>
#3      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:84:43)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale es-ES)
    • Flutter version 1.9.1+hotfix.4 at /Users/xxx/develop/flutter
    • Framework revision cc949a8e8b (7 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 32.0.2
    • Dart plugin version 183.4588.61

[✓] Connected device (2 available)
    • SM G920F          • 0715f799560b3e36                     • android-arm64 • Android 7.0 (API 24)
    • iPhone 11 Pro Max • C3508206-9750-45CA-9142-ECBDB2F6D924 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!
```

**Comment by jmagman** [comment]
Can it be opened in Xcode?  If so, does Xcode change any files to repair it?  Can you share that diff with us if there is a change?

**Comment by bytelyus** [comment]
Hi jmagman... No ... It can't be opened with open in Xcode comand... 

Same error occurs

**Comment by jmagman** [comment]
Can you attach the `/Users/xxx/IdeaProjects/master_gest/ios/Runner.xcodeproj` bundle or put it on GitHub so I can look?

**Comment by bytelyus** [comment]
Sure .. is it fine if i zip the Runner folder inside ios folder? ... or is it just the Runner.xcoderproj file??

**Comment by bytelyus** [comment]
[Runner.xcworkspace.zip](https://github.com/flutter/flutter/files/3691646/Runner.xcworkspace.zip)

I think this is it ... let me know if you need something else...

**Comment by jmagman** [comment]
It's complaining about the xcodeproj.  Can we get that instead?

**Comment by bytelyus** [comment]
[Runner.xcodeproj.zip](https://github.com/flutter/flutter/files/3691660/Runner.xcodeproj.zip)

ooppsss... sorry about that

**Comment by jmagman** [comment]
The `project.pbxproj` (the guts of the Xcode project logic) is completely empty.  

1. Did running some `flutter` command did this?  I've never seen a similar report.  
1. Could something else on your system have deleted the contents of that file?
1. Can you restore it from source control?

**Comment by bytelyus** [comment]
I did a flutter upgrade this morning. But it was working fine after that ... 

I have no idea how could that happened ... 

Ok... i just copied that file from another project (similar but not the same one!) and its seems working again ... 

Let me work with it this weekend and see if everything is ok now ....

Thanks very much!! Best wishes, Miguel ... Great Job!!  <3 flutter

**Comment by jmagman** [comment]
I'm going to close since it doesn't seem like a `flutter` command caused this.  Please file a new issue and reference this one if you see it happen again.

**Comment by HarshaiOS1** [comment]
right Click on Runner.xcodeproj and select "Show Package content". Open project.pbxproj and see if there any merge conflicts(search for >>>>/<<<<). Stange how conflict is not being caught by flutter.

**Comment by jmagman** [comment]
@HarshaiOS1 Flutter doesn't instantiate any source control in your project.  That's up to you as a developer.  In any case, this issue was tracking an empty project file, not one with merge conflicts.
