### ISSUE TITLE
Am using flutter firebase_notification and when i add onBackgroungMessage it says that its unknown parameter kindy help on that

### ISSUE THREAD

**Issue by alvinotienokelly** [flutter/flutter#41981]

**Comment by BondarenkoStas** [comment]
@alvinotienokelly sorry but what is onBackgroungMessage? can you provide a code example?

**Comment by alvinotienokelly** [comment]
> 
> 
> @alvinotienokelly sorry but what is onBackgroungMessage? can you provide a code example?

 _firebaseMessaging.configure(
       onMessage: (Map<String, dynamic> message) async {
         print("onMessage: $message");
         _showItemDialog(message);
       },
       onBackgroundMessage: myBackgroundMessageHandler,
       onLaunch: (Map<String, dynamic> message) async {
         print("onLaunch: $message");
         _navigateToItemDetail(message);
       },
       onResume: (Map<String, dynamic> message) async {
         print("onResume: $message");
         _navigateToItemDetail(message);
       },
     );

**Comment by BondarenkoStas** [comment]
@alvinotienokelly what the version of firebase_messaging do you use and which device do you use to test? did you follow the https://pub.dev/packages/firebase_messaging#optionally-handle-background-messages guide? background messaging is enabled from September 5 v5.1.5, and only for android.

**Comment by janmoppel** [comment]
Hello @alvinotienokelly !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
