### ISSUE TITLE
The standard codec does not handle empty strings or vectors

### ISSUE THREAD

**Issue by rokob** [flutter/flutter#41993]
I am not sure if this is by design but it seems like a bug. The standard codec will assert here:

https://github.com/flutter/engine/blob/7d90779bb66f2c63444ee41b61c2d9a1c7b389ca/shell/platform/common/cpp/client_wrapper/byte_stream_wrappers.h#L82

if you try to write an empty vector:

https://github.com/flutter/engine/blob/7d90779bb66f2c63444ee41b61c2d9a1c7b389ca/shell/platform/common/cpp/client_wrapper/standard_codec.cc#L266,L267

or an empty string:

https://github.com/flutter/engine/blob/7d90779bb66f2c63444ee41b61c2d9a1c7b389ca/shell/platform/common/cpp/client_wrapper/standard_codec.cc#L175,L182

@stuartmorgan

**Comment by stuartmorgan** [comment]
It's a bug. I think the assert should stay in the buffer, to catch accidental attempts to write zero bytes, but we should check for zero length and not call `WriteBytes` in that case at these call sites.

We should also make sure to add zero-length arrays and strings to the serialization and deserialization unit tests.

/cc @franciscojma86

**Comment by rokob** [comment]
https://github.com/flutter/engine/pull/12974

**Comment by stuartmorgan** [comment]
This was fixed by the PR above, it just didn't get auto-closed.
