### ISSUE TITLE
we need some feedback that the observatory is up and available to connect to

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#42]
From https://github.com/flutter/tools/issues/110

The CLI VM prints out Observatory listening on http://127.0.0.1:8989 when run w/ the observatory enabled. Perhaps the flutter runtime should to the same?

It looks like the VM doesn't print on startup if you use the default port of 8181. And parsing stdout for a token isn't the most reliable way of doing things.

We could change the flutter start command to not return until the process is up and running on android. Then we'd know, when that completes, that the observatory is ready to connect to.

**Comment by sethladd** [comment]
cc @devoncarew still needed?

**Comment by devoncarew** [comment]
Yup -

**Comment by eseidelGoogle** [comment]
We print this now.
