### ISSUE TITLE
[web] Route name doesn't work well when there are nested Navigators

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#42009]
See @goderbauer's [comment](https://github.com/flutter/flutter/pull/41996#issuecomment-538526854):

> If you have a root navigator and a nested navigator B. If you navigate to a different page within B, the URL bar will only show the route within B. It doesn't show the route within the root navigator anymore to get to the page that contained the nested navigator.

**Comment by Hixie** [comment]
@goderbauer Will this be handled by the router refactor?

**Comment by chunhtai** [comment]
The current navigator2.0 plans to fix this issue, but the detail solution is still missing. I am writing a new design document aim to fix this issue

**Comment by pedromassangocode** [comment]
Is this still a valid issue? The Navigator 2.0 is now on master.

**Comment by chunhtai** [comment]
I think this is no longer an issue that the navigator now takes in a flag to decide whether it will report route name. In the nested navigators scenario, you can decide which navigator will report and which will not.

**Comment by GP4cK** [comment]
@chunhtai are you talking about `reportsRouteUpdateToEngine`?

**Comment by chunhtai** [comment]
@GP4cK Correct.
