### ISSUE TITLE
ensure that --profile and --release are not available for ios simulators

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#4200]
We should fail with an error when flutter run is run with `--profile` or `--release` with a simulator.

@tvolkert @chinmaygarde

**Comment by rmacnak-google** [comment]
Why? Precompilation should work for the 64-bit simulators.

**Comment by abarth** [comment]
@rmacnak-google There isn't a use case for release builds on simulators because simulators aren't used by end users.

**Comment by eseidelGoogle** [comment]
@rmacnak-google the goal is just to simplify the offering.  Certainly AOT on simulators is possible, but simulators are already slow for other reasons, so offering only awesome-development-mode there just removes variables. :)
