### ISSUE TITLE
problem with path provider

### ISSUE THREAD

**Issue by Hamidrezana** [flutter/flutter#42005]
Hi,
I'm using path_provider to create database.
Every thing is ok on android but I got [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider) on ios.
what is the problem?
tnx

**Comment by escamoteur** [comment]
Thanks for reporting!

Could you please add the output of `flutter doctor .v` here?

**Comment by Hamidrezana** [comment]
@escamoteur 
Thanks for reply.
Hear is output of flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.12.6 16G29, locale
    en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

 
[✓] Xcode - develop for iOS and macOS (Xcode 9.0)
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

I test for android on Arch linux, So I do not need android on macOS.

**Comment by Hamidrezana** [comment]
I finally add
`GeneratedPluginRegistrant.register(with: self)`
in AppDelegate.swift before `return` and now it's ok.

**Comment by escamoteur** [comment]
I reopen this because this should not be necessary. Great that you found a work around.

**Comment by jmagman** [comment]
Calling `GeneratedPluginRegistrant.register(with: self)` is necessary, and is present in the generated AppDelegate.swift and in the [add-to-app](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#add-your-flutter-app-to-your-podfile) instructions

**Comment by escamoteur** [comment]
Ah, it wasn't clear to me that this is a mixed project

**Comment by jmagman** [comment]
> Ah, it wasn't clear to me that this is a mixed project

I don't know if it is, but I believe it's required in the default `flutter create` case as well.

**Comment by escamoteur** [comment]
Nope, I use it in my full Flutter apps and I just do do as in the readme described like

```Dart
Directory tempDir = await getTemporaryDirectory();
String tempPath = tempDir.path;

Directory appDocDir = await getApplicationDocumentsDirectory();
String appDocPath = appDocDir.path;
```

if it's needed in a mixed project I don't know
