### ISSUE TITLE
OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0

### ISSUE THREAD

**Issue by lucaszanella** [flutter/flutter#42012]
```
Downloading Dart SDK from Flutter engine 7d90779bb66f2c63444ee41b61c2d9a1c7b389ca...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 23  259M   23 61.7M    0     0  8294k      0  0:00:32  0:00:07  0:00:25 8730k
curl: (56) OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra/flutter/7d90779bb66f2c63444ee41b61c2d9a1c7b389ca/dart-sdk-linux-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china


```

I get these errors a lot and I'm not in China. There should be an automatic retry as this completely breaks my docker build script because I have to stay close to the computer and rebuild in case it fails. And it fails a LOT!

**Comment by christopherfujino** [comment]
@lucaszanella does this only happen in doctor? could you provide the output of `flutter doctor -v`?

**Comment by jonahwilliams** [comment]
I recommend downloading the prebuilts from the flutter.dev website or a mirrors, since this doesn't rely on using the tool logic to download things on demand

**Comment by christopherfujino** [comment]
This will also be addressed by https://github.com/flutter/flutter/pull/50731
