### ISSUE TITLE
Run engine unit tests on Windows presubmit checks

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#42024]
Although we build all unit tests on Windows, we only run very few of them (and we ran none of them before https://github.com/flutter/engine/pull/12423).

We need some very brave person to [enable all unit tests on Windows](https://github.com/flutter/engine/blob/master/.cirrus.yml#L118), and lead us to fix all the Windows unit tests failures.

**Comment by liyuqian** [comment]
CC @chunhtai @franciscojma86 @chinmaygarde @cbracken

**Comment by chunhtai** [comment]
I seems like we can just enable all now, I remembered it will crash for some dependency error but it might have changed

**Comment by liyuqian** [comment]
From the [log](https://cirrus-ci.com/task/6042270691753984), it `shell_unittests` and `fml_unittests` don't seem to be running?

**Comment by liyuqian** [comment]
I see https://github.com/flutter/flutter/issues/36295 so `shell_unittests` is expected to be not running.

However, I don't quite understand why `fml_unittests` doesn't seem to be running. I can see `c:\flutter\engine\src\out\host_debug_unopt\fml_unittests.exe --gtest_filter="-*TimeSensitiveTest*" --gtest_shuffle --gtest_repeat=2` in the log, but there's no `FileTest`... CC @chinmaygarde

**Comment by chinmaygarde** [comment]
Besides the AtomicWriteTest which is [disabled on Windows](https://github.com/flutter/engine/blob/c2f1b09e6aae990da8033ce19d3dee01d9135c40/fml/file_unittest.cc#L230), the other file tests should be running. May I see the logs?

**Comment by chunhtai** [comment]
will take a look

**Comment by liyuqian** [comment]
@chinmaygarde : here's the raw log https://api.cirrus-ci.com/v1/task/6042270691753984/logs/test_host.log

**Comment by chunhtai** [comment]
When I ran it directly using
```
c:\flutter\engine\src\out\host_debug_unopt\fml_unittests.exe --gtest_filter="-*TimeSensitiveTest*" --gtest_shuffle --gtest_repeat=2
```
it does run the tests without problem. However, it seems to run 0 tests when using the python run_tests.py script

This seems to happen in linux as well
https://cirrus-ci.com/task/4714447200845824?command=test_host#L80

I will keep investigating

**Comment by chunhtai** [comment]
change reverted, fml test suite failed luci
