### ISSUE TITLE
Let shell instead of the whole process own the persistent cache

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#42023]
This will make the management of different cache strategies (e.g., read-only, SkSL, path, etc.), and the related unit tests much easier.

**Comment by liyuqian** [comment]
See also https://github.com/flutter/flutter/issues/50613

**Comment by liyuqian** [comment]
Remove myself from the assignment as I'm not actively working on this. Will reassign myself once I get some time to work on it.

**Comment by jonahwilliams** [comment]
Closing as obsolete
