### ISSUE TITLE
release build failing due to Firestore Core androidx incompatibility

### ISSUE THREAD

**Issue by bij0y** [flutter/flutter#42041]
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.3.4\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Debug build is fine
release build is failing

**Comment by kroikie** [comment]
@bij0y

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/306. Any further collaboration will be done there.
