### ISSUE TITLE
How to retrive single bloc data through root level inheritedWidget

### ISSUE THREAD

**Issue by mrutyunjayagiri** [flutter/flutter#42045]
I have a root widget as inheritedWidget and it's data as an instance of a bloc manager(All Blocs Instances). My problem is how to get those data to my widgets from inside the individual bloc through inheritedWidget.
Sample of my code
```
runApp(Provider(
    data: mainManager,
    child: MyApp(),
  ));

class Provider extends InheritedWidget {
  final MainManager data;
  Provider({Key key, Widget child, this.data}) : super(key: key, child: child);

  static MainManager of(BuildContext context) {
    return (context.inheritFromWidgetOfExactType(Provider) as Provider).data;
  }
  @override
  bool updateShouldNotify(InheritedWidget oldWidget) {
    return true;
  }
}

class MainManager{
  AuthenticationBloc _authenticationBloc;
  LoginBloc _loginBloc;
}
AuthenticationBloc  {
UserData userData......
}
======
MyHomeScreen extends StatelessWidget {
@override
  Widget build(BuildContext context) {
    final AuthModel _authData = Provider.of(context).userData;

    print(_authData.authId);
Return Container();
}
}
```

**Comment by BondarenkoStas** [comment]
@mrutyunjayagiri This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
