### ISSUE TITLE
git flutter package get issue

### ISSUE THREAD

**Issue by kimi14314** [flutter/flutter#42044]
running git package get and had the following error.

Git error. Command: git rev-list --max-count=1 projectname                 
fatal: ambiguous argument 'projectname': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:                   
'git <command> [<revision>...] -- [<file>...]'    

Anyone has any idea? Is it a git setup problem?

**Comment by ja2375** [comment]
Not sure what you are trying to achieve here but you have to use the command `flutter packages get`, which is a git repo manager itself. Git command doesn't know how to get flutter packages.
