### ISSUE TITLE
release build failing due to Cloud Firestore Androidx incompatibility

### ISSUE THREAD

**Issue by bij0y** [flutter/flutter#42040]
I'm getting
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.9.13+1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

The debug build is fine
but release build is failing.

I tried every solution I got here.
minSdkVersion, compileSdkVersion everything

**Comment by kroikie** [comment]
@bij0y

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/307. Any further collaboration will be done there.
