### ISSUE TITLE
release build failing due to Firestore Messaging androidx incompatibility

### ISSUE THREAD

**Issue by bij0y** [flutter/flutter#42042]
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-4.0.0+4\android\src\main\java\io\flutter\plugins\firebasemessaging\FlutterFirebaseInstanceIDService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

debug build is working fine
release is failing

**Comment by kroikie** [comment]
@bij0y

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/305. Any further collaboration will be done there.
