### ISSUE TITLE
[web]: Currently there is no way to tell if it is web, ios or android.

### ISSUE THREAD

**Issue by brianschardt** [flutter/flutter#42050]
In order to get the device you can do something like this

``` 
import 'dart:io' show Platform;

if (Platform.isAndroid) {
  // Android-specific code
} else if (Platform.isIOS) {
  // iOS-specific code
} 
```

In flutter web you cannot use import 'dart:io' show Platform;
as you will get this error
```
Skipping compiling t|lib/main_web_entrypoint.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

t|lib/routes/login.dart
```

Please add web support

**Comment by AppleEducate** [comment]
You can check if you are on the web by:
```dart
import 'package:flutter/foundation.dart';

if (kIsWeb) {

} else {

}
```

**Comment by BondarenkoStas** [comment]
@brianegan the constant is here https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/constants.dart#L49
Closing the issue.

**Comment by xpat** [comment]
@rodydavis I'm wondering if I can get some help using a geolocation api (e.g., [weather](https://openweathermap.org/current)) now that I've integrated kIsWeb into my code. Once my program detects that I'm using the web, I am using a geolocation web api and a geolocation package (that's only for Android and iOs, still).  I'm using the http.dart package and can access the geolocation from a scratch file using the following code:  

`import 'dart:io';import 'dart:io';
import 'package:http/http.dart';

void main() {
  performTasks();
}

void performTasks() async {
  task1();
//  String task2result = await task2();
print(task2());
getData();
//  task3(task2result);
}

void getData() async {
  Response response = await get ('https://samples.openweathermap.org/data/2.5/weather?lat=35&lon=139&appid=b6907d289e10d714a6e88b30761fae22');
  print(response.body);
}`

I've managed to integrate if kIsWeb into a weather app and print out my latitude and longitude to the console, but I can't get it to print out the json weather api data in the console.  I thought this might be of interest to others; I'm following an on-line tutorial ([lesson 13 in the Complete Flutter Development Bootcamp using Dart](https://github.com/londonappbrewery/Flutter-Course-Resources#section-13-clima---powering-your-flutter-app-with-live-weather-web-data) recommended on the bottom of [the Codelabs page](https://flutter.dev/docs/codelabs)). I've been helped [by this thread](https://github.com/Baseflow/flutter-geolocator/issues/392).

**Comment by rodydavis** [comment]
Do you have a CORS issue?

**Comment by xpat** [comment]
@rodydavis.  Thanks for getting back to me. Maybe it's a CORS issue, but I'm not sure how to debug it.  I'm working in Android Studio. I keep cutting and pasting my code haphazardly.  Essentially I am trying to graft kIsWeb and the geolocation api (@JS navigator.geolocation.getCurrentPosition... success(pos)) onto a Flutter tutorial that is made only for Android and iOS, that uses a package that doesn't yet include web.  The code I pasted above works within Android Studio as a stand-alone dart file.  That code does return the JSON data that I'm trying to get but which I can't get in the Flutter project using the main.dart file as the entry point.
