### ISSUE TITLE
Hot reload throws error when SingleTickerProviderStateMixin is used

### ISSUE THREAD

**Issue by fayaz07** [flutter/flutter#42054]
I have a screen with some anim, I have used **SingleTickerProviderStateMixin**, when I reload the screen it throws an error as follows.

```
E/flutter ( 7919): [ERROR:flutter/shell/common/shell.cc(178)] Dart Error: Unhandled exception:
E/flutter ( 7919): _SplashState is a SingleTickerProviderStateMixin but multiple tickers were created.
E/flutter ( 7919): A SingleTickerProviderStateMixin can only be used as a TickerProvider once. If a State is used for multiple AnimationController objects, or if it is passed to other objects and those objects might use it more than one time in total, then instead of mixing in a SingleTickerProviderStateMixin, use a regular TickerProviderStateMixin.
E/flutter ( 7919): #0      SingleTickerProviderStateMixin.createTicker.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:85:7)
E/flutter ( 7919): #1      SingleTickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:92:6)
E/flutter ( 7919): #2      new AnimationController (package:flutter/src/animation/animation_controller.dart:245:21)
E/flutter ( 7919): #3      _SplashState.startScrollAnimation.<anonymous closure> (package:zomato_clone/ui/splash.dart:51:30)
E/flutter ( 7919): #4      _RootZone.run (dart:async/zone.dart:1374:54)
E/flutter ( 7919): #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:161:18)
E/flutter ( 7919): #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:648:39)
E/flutter ( 7919): #7      Future._propagateToListeners (dart:async/future_impl.dart:704:37)
E/flutter ( 7919): #8      Future._complete (dart:async/future_impl.dart:512:7)
E/flutter ( 7919): #9      new Future.delayed.<anonymous closure> (dart:async/future.dart:313:16)
E/flutter ( 7919): #10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter ( 7919): #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter ( 7919): #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter ( 7919): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by frankzang** [comment]
Did you try to use TickerProviderStateMixin instead of SingleTickerProviderStateMixin?

**Comment by fayaz07** [comment]
I knew TickerProviderStateMixin will solve the issue, but on hot reload the framework must consider SingleTickerProviderStateMixin too

**Comment by MHShetty** [comment]
Could you please share your code?

There's a good amount of chance that you had instantiated your `AnimationController` in the **build method** along with the `vsync` param, which caused the new `AnimationController` to create another `Ticker` with the `SingleTickerProviderStateMixin` (A `TickerProvider` that is used by `AnimationController` to create a `Ticker` and in this case to safely create just one `Ticker` for your `StatefulWidget`) on hot reload/re-build.

### Make sure that you declare the `AnimationController` as a class member variable of that `StatefulWidget` and initialize it while overriding the `initState()` method of your `StatefulWidget`.

**Comment by flutterfromscratch** [comment]
In my case, using a `AnimatedSize` with vsync set to `this` was enough to trigger this error with a SingleTickerProviderStateMixin

**Comment by flukejones** [comment]
> In my case, using a `AnimatedSize` with vsync set to `this` was enough to trigger this error with a SingleTickerProviderStateMixin

I can confirm `vsync: this` appears to cause this on last master release.

**Comment by pedromassangocode** [comment]
Hi @fayaz07 
Can you confirm that you still facing this issue? If yes, then please provide your `flutter doctor -v`, `flutter run -v` and a minimal reproducible code sample.
Thank you

**Comment by fayaz07** [comment]
Hi @pedromassango 
yeah sure, I will check it and revert back
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by cyberpwnn** [comment]
```dart
class _ShelfPanelState extends State<ShelfPanel>
    with SingleTickerProviderStateMixin {
```

```
[        ] I/flutter ( 7905): [FATAL]: _ShelfPanelState is a SingleTickerProviderStateMixin but multiple tickers were created.
```

(caught with try/catch)
