### ISSUE TITLE
Web test server doesn't support https

### ISSUE THREAD

**Issue by galki** [flutter/flutter#42057]
Running `flutter run -d chrome` opens the app in `http://localhost:[RANDOM PORT]` but the lack of SSL makes it impossible to connect to Firebase. Can we get CLI flags to:

- make the server use https
- specify a hostname other than localhost

**Comment by galki** [comment]
I realized that [firebase serve](https://firebase.google.com/docs/web/setup#test-locally) works fine with just http.

**Comment by jonahwilliams** [comment]
You can also change the hostname with `--web-hostname` and the port with `--web-port`
