### ISSUE TITLE
Dart Regex is inconsistent with certain characters

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#42052]
When trying to write a validation Regex, I stumbled upon an issue where the pattern is inconsistent. 

The Regex in question is `RegExp(r"^[a-zA-ZÀ-ÖØ-öø-ÿ-'. ]{1,50}$")`
This Regex incorrectly labels * + , ( and ) as correct input. 

However when doing
`var regex = RegExp("^[a-zA-ZÀ-ÖØ-öø-ÿ-'. ]{1,50}$");` in say a browser console running on Javascript, the * + , ( and ) are labeled as incorrect. Which is to be expected, as both are not within the range of unicode characters that are allowed.
I assumed Dart Regexes were based of the Javascript impl, so they should yield the same result?

## Steps to Reproduce

Create  a variable `RegExp regex = RegExp(r"^[a-zA-ZÀ-ÖØ-öø-ÿ-'. ]{1,50}$");`
Test the variable against values like ( ) + , and so fort. Do the exact same on a Javascript console(e.g. a browser console). Compare the 2 for inconsistencies.

Target Platform: Windows 10
Target OS version: 10.0.18362

**Comment by BondarenkoStas** [comment]
@navaronbracke RegExp is in the dart:core lib, which is just used by flutter. I would advise you to file the issue to https://github.com/dart-lang/sdk/issues and paste the link to it here for tracking.

**Comment by navaronbracke** [comment]
@BondarenkoStas I think I found what was causing it. Nothing Dart related though, a typo in my Regex combined with thinking 'Since it works in the JS console it's a bug'. 
Rewrote my Regex to the following `RegExp(r"^([\p{Letter}\s]|['-]){1,50}$",unicode: true)` and it works like a charm! Typo's right? 

Closing the issue since it's fixed now.
