### ISSUE TITLE
update_dart_sdk.sh: line 82: unzip: command not found

### ISSUE THREAD

**Issue by sinmrinal** [flutter/flutter#42059]
(system- arch linux)

1. switched to dev channel and enabled web.

2. it  starts downloading dart sdk

3. error:

flutter/bin/internal/update_dart_sdk.sh: line 82: unzip: command not found

It appears that the downloaded file is corrupt

(same error using flutter upgrade)

**Comment by BondarenkoStas** [comment]
@sinmrinal unzip is a requirement for flutter in linux, and it seems it's not available on your computer. You can check here https://flutter.dev/docs/get-started/install/linux. 
Please install it and reply if it works.

**Comment by sinmrinal** [comment]
installing unzip did the job. command- 

`$ sudo pacman -S unzip`  (for arch linux)

Thanks @BondarenkoStas
