### ISSUE TITLE
Where is the example?

### ISSUE THREAD

**Issue by David263** [flutter/flutter#42062]
I came here from https://github.com/flutter/samples/tree/master/isolate_example, which says, "If you run into an issue with the sample itself, please file an issue in the main Flutter repo."

My issue is that I can't find the example of isolates, which I'd like to see.  I came here from the "isolates example link" at https://dart.dev/guides/language/language-tour#isolates . Documentation could be a bit clearer for newcomers.

**Comment by nnttoo** [comment]
I'm also a newcomers, I see examples in:
https://github.com/flutter/samples/blob/master/isolate_example/lib/page_three.dart
in line 86

**Comment by BondarenkoStas** [comment]
@David263 the whose repo is the example, do you search for something specific?

**Comment by janmoppel** [comment]
Hello @David263 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
