### ISSUE TITLE
[web]: pixelated images & icons on Firefox on Windows

### ISSUE THREAD

**Issue by deckerst** [flutter/flutter#42066]
On Firefox on Windows 10, I see that images (`NetworkImage`, `AssetImage`, even `Icon`) appear pixelated. For example, an avatar displayed via:
```dart
      CircleAvatar(
        backgroundColor: Colors.white,
        backgroundImage: NetworkImage(url),
        radius: radius,
      )
```
looks pixelated on Firefox on Windows 10:
![win10-firefox](https://user-images.githubusercontent.com/13898333/66263264-8c340280-e82a-11e9-8b35-75c6ce3508fd.png)

But it looks fine on Chrome on Windows 10, or any browser (Chrome / Firefox) on MacOS:
![win10-chrome](https://user-images.githubusercontent.com/13898333/66263272-ab329480-e82a-11e9-8cb9-9e179cf96fc5.png)

For reference, the original image here is:
![girl](https://user-images.githubusercontent.com/13898333/66263273-b38acf80-e82a-11e9-9fec-1704123ce685.png)

Maybe it's related to https://github.com/flutter/flutter/issues/41328 but that ticket seems to discuss device dependent properties, while here it depends on browser & OS.

```
flutter doctor -v
[√] Flutter (Channel dev, v1.10.12, on Microsoft Windows [Version 10.0.18362.388], locale en-GB)
    • Flutter version 1.10.12 at C:\flutter
    • Framework revision 0e605cc4dd (35 hours ago), 2019-10-04 07:52:15 -0700
    • Engine revision 759d3dba25
    • Dart version 2.6.0 (build 2.6.0-dev.5.0 7a7dcd1ed9)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\tibo\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • Chrome          • chrome          • web-javascript • Google Chrome 77.0.3865.90
    • Headless Server • headless-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by ferhatb** [comment]
@deckerst , closing this issue since we now use <img> tags to render and don't rely on canvas. Please reopen if you still see issue.
