### ISSUE TITLE
Why my new Flutter project runs on kotlin and swift? 

### ISSUE THREAD

**Issue by Medrov** [flutter/flutter#42060]
My new project runs on kotlin and swift, but i want to run project on java and objective-c, i want to switch this setting. My version of Android Studio is 3.4.1. And I didn't chose kotlin and swift variation. How can i reach this goal.

**Comment by coolidm** [comment]
Flutter switched the default languages to kotlin and swift but there is a command line switch -i or --ios-language and -a or --android-language

To update an existing project you should be able to delete the ios and android directories and run 
flutter create -i objc -a java

**Comment by Medrov** [comment]
@coolidm
