### ISSUE TITLE
Limiting the planning on Google Maps

### ISSUE THREAD

**Issue by Jumpbotron** [flutter/flutter#42061]
I'm currently making a google maps based flutter app that just shows a specific area in my city. how can i achieve this with Google Maps Flutter? Does anyone knows how can this be made in a concrete or alternative way?

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
