### ISSUE TITLE
Password Input field

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4206]
https://www.google.com/design/spec/components/text-fields.html#text-fields-required-fields

customer: fast has an example of this in their mocks.  Unclear if they'll actually end up using it (since phones often have shared UI for password entry instead of per-app), but since it's in MD we should have it.  If they do need it, we'll need it soon.

FYI @mpcomplete @HansMuller

**Comment by mpcomplete** [comment]
Is this about the visibility icon? We have support for password entry fields otherwise.

**Comment by eseidelGoogle** [comment]
I see we already have an example:
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/text_field_demo.dart#L104

So OK, I think we can close this.  We can do the visibility icon later.
