### ISSUE TITLE
I/chatty identical 1 line

### ISSUE THREAD

**Issue by sohedul** [flutter/flutter#42068]
Syncing files to device Redmi 6...
D/GraphicBuffer(32042): register, handle(0x9afa73c0) (w:720 h:1344 s:736 f:0x1 u:b00)
I/zygote  (32042): Do partial code cache collection, code=29KB, data=29KB
I/zygote  (32042): After code cache collection, code=29KB, data=29KB
I/zygote  (32042): Increasing code cache capacity to 128KB
D/GraphicBuffer(32042): register, handle(0x7d6aee00) (w:720 h:1344 s:736 f:0x1 u:b00)

I/chatty   (32042): uid=10239(com.example.my_ap) identical 1 line

**Comment by BondarenkoStas** [comment]
@sohedul what is the issue? your terminal hid an identical line (log added almost simultaneously with the previous one) to avoid duplications.

**Comment by janmoppel** [comment]
Hello @sohedul !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.

**Comment by josediegopassos** [comment]
I am facing the same problem ... even the application gets to hang.
