### ISSUE TITLE
url launcher not working iOS devices

### ISSUE THREAD

**Issue by amee13bit** [flutter/flutter#42077]
@FlutterIssues 
@fluttergithubbot 

implemented url launcher..works fine in android..but not able to run on ios..returns below error when tapping button
```
flutter: Another exception was thrown: NoSuchMethodError: The method 'openUrl' was called on null.
  url_launcher: ^5.1.4

detailed error log 

> ════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The method 'openUrl' was called on null.
Receiver: null
Tried calling: openUrl("https://convoy.co.in/about.html#aboutus")

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _SettingsScreenState.build.<anonymous closure> (package:convoy/screens/settings/SettingsScreen.dart:204:24)
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#7776b
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(84.0, 465.5)
  finalLocalPosition: Offset(84.0, 29.5)
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════


flutter doctor 
```

ameeralis-MacBook-Pro:convoy_flutter_app ameerali$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.13.6 17G8030,
    locale en-IN)
    • Flutter version 1.9.1+hotfix.2 at /Applications/flutter
    • Framework revision 2d2a1ffec9 (4 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ameerali/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

**Comment by BondarenkoStas** [comment]
@amee13bit Please provide your flutter doctor -v output, and provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by amee13bit** [comment]
> @amee13bit Please provide your flutter doctor -v output, and provide a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.


ameeralis-MacBook-Pro:convoy_flutter_app ameerali$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.13.6 17G8030,
    locale en-IN)
    • Flutter version 1.9.1+hotfix.2 at /Applications/flutter
    • Framework revision 2d2a1ffec9 (4 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ameerali/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

**Comment by BondarenkoStas** [comment]
@amee13bit but any clues how to reproduce it? Please provide a reproducible example

**Comment by amee13bit** [comment]
> @amee13bit but any clues how to reproduce it? Please provide a reproducible example

I was doing settings section of an app..with links to about page(web) and app share and other webpages

**Comment by BondarenkoStas** [comment]
@amee13bit is the link https://convoy.co.in/about.html#aboutus correct? I can't open it. Does it work with any other link?

**Comment by amee13bit** [comment]
> @amee13bit is the link https://convoy.co.in/about.html#aboutus correct? I can't open it. Does it work with any other link?
link is not live yet ...but in android link goes to the browser even though the link is not live

**Comment by git-xbits** [comment]
Same problem. Works in one project, another have the issue..

**Comment by joedonchev** [comment]
The phone call worked on Android, but it didn't work on iOS.
Finally, i removed the spaces from the phone string:
before: +00 0000 0000
after: +0000000000
And then, worked on both Android and iOS.
Please, make it clear on the project page, so that others won't waste time like me.

**Comment by nicolasdupere** [comment]
Me everything is working on a real device. Ios and Android.

**Comment by VladyslavBondarenko** [comment]
@amee13bit 
I hope you've solved the problem, I don't have that error with flutter master 1.15.21-pre.36, url_launcher 5.4.2 and iOS 13.3 simulator.
Closing the issue.
If you disagree please write in the comments and I will reopen it.
Thank you
