### ISSUE TITLE
Add a `Shader` to invert it's child widget 

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#42078]
## Use case

Especially in the context of Dark mode the inversion of Icons or Grey-Scale images get't more and more important.
Currently it seems that there is no way in Flutter to invert such an image.

## Proposal

Add a new `Shader`that can be used with `ShaderMask` that's inverts its child.

**Comment by magillus** [comment]
Quick thought:
We would use kind of Color matrix, color inversion would be one of the predefined matrices. There could be colorblind/high contrast matrices also.
```
  R  G  B  A W
R 1 0 0 0 0
G 0 1 0 0 0
B 0 0 1 0 0
A 0 0 0 1 0
W 0 0 0 0 1
```
Something like this: https://docs.microsoft.com/en-us/dotnet/api/system.drawing.imaging.colormatrix?view=netframework-4.8

**Comment by escamoteur** [comment]
I just found the ColorFiltered class which allows exactly such operations.
I m not clear if it is as performant as a Shader though

**Comment by escamoteur** [comment]
According to @Hixie if your system has a GPU the filtering is done on it.
So I close this issue
