### ISSUE TITLE
Detect changes to /android/app/build.gradle so release signatures work without "flutter clean"

### ISSUE THREAD

**Issue by krolaw** [flutter/flutter#42071]
As per #29975, it's not documented in [Preparing an Android app for release](https://flutter.dev/docs/deployment/android), that you must "flutter clean" to include the release signature (as required by google play).

I'd prefer flutter build detect the change in ./android/app/build.gradle and update accordingly, which would reduce confusion and save adding an extra step to the docs.

Thanks.

**Comment by jonahwilliams** [comment]
You do not need to `flutter clean` when uploading an APK. Changes to build.gradle will be picked up by gradle
