### ISSUE TITLE
Sentry Error

### ISSUE THREAD

**Issue by fightingLT** [flutter/flutter#42073]
fileName: stack_trace.dart,

methodName: _absolutePathForCrashReport

errorLocation:  lineno:67,  

reason: when frame.uri.pathSegments is null , will got an error, because  .last or .first can not be used on null.

**Comment by ketanm** [comment]
@fightingLT - There not sufficient information for someone to help you. Please provide relevant code, `flutter doctor -v` output and stack trace.
Also, last line clearly states that URI is set to null value.

**Comment by fightingLT** [comment]
> @fightingLT - There not sufficient information for someone to help you. Please provide relevant code, `flutter doctor -v` output and stack trace.
> Also, last line clearly states that URI is set to null value.

this is errorLog:
unparsed in {userId: , app_version: 0.0.26, errorLog: #0 _ImmutableList.get:last (dart:core-patch/array.dart:207)
stack_trace.dart in _absolutePathForCrashReport at line 67
stack_trace.dart in encodeStackTraceFrame at line 45
Called from: iterable.dart in MappedListIterable.elementAt
stack_trace.dart in encodeStackTrace at line 35
sentry.dart in Event.toJson at line 416
sentry.dart in SentryClient.capture at line 196
Called from: <asynchronous suspension>
sentry.dart in SentryClient.captureException at line 233
util.dart in reportErrorToSentry at line 1286
Called from: <asynchronous suspension>
splash_screen.dart in _SplashPageState.startTimer.<fn> at line 83
Called from: <asynchronous suspension>
global_user_info_bloc.dart in GlobalUserInfoBloc.executeOnLoginCallback.<fn> at line 30
Called from: growable_array.dart in _GrowableList.forEach
global_user_info_bloc.dart in GlobalUserInfoBloc.executeOnLoginCallback at line 30
main.dart in _BBState.build.<fn> at line 167
bloc_builder.dart in BlocBuilder.build at line 87
bloc_builder.dart in _BlocBuilderBaseState.build at line 147
framework.dart in StatefulElement.build at line 4047
framework.dart in ComponentElement.performRebuild at line 3941
framework.dart in Element.rebuild at line 3738
framework.dart in BuildOwner.buildScope at line 2348
binding.dart in WidgetsBinding.drawFrame at line 760
binding.dart in RendererBinding._handlePersistentFrameCallback at line 280
binding.dart in SchedulerBinding._invokeFrameCallback at line 1033
binding.dart in SchedulerBinding.handleDrawFrame at line 975
binding.dart in SchedulerBinding._handleDrawFrame at line 891

And i had fixed it by fork senty

**Comment by Hixie** [comment]
As @ketanm says, we also need the code that is causing the problem. Without a reproducible demo app we are unable to really make significant progress in addressing this issue.
