### ISSUE TITLE
ListView should be able to select start position

### ISSUE THREAD

**Issue by hasen6** [flutter/flutter#42074]
## Use case

I am using `ListView` with a list of dates and the data comes with the last entry as the latest entry but when creating a list I want the most recent entry to be at the top of the list. `ListView` includes the option to reverse the list which is _almost_ fine, except that for some reason the list then starts scrolled to the bottom?

So whatever I select I don't get the latest date at the top of the list where it should be.

## Proposal

We should be able to select scroll start position, or at least, the default start position should be at the top regardless of whether the list is reversed or not.

There are workarounds but are awkward, such as running the `List` in reverse:

```
ListView.builder(
  itemCount: feed.length,
  itemBuilder: (context, index) {
    return ListTile(title: feed[feed.length - 1 -index]);
  },
);
```

**Comment by goderbauer** [comment]
You could also just use `feed.reversed`. I don't think this needs to be a framework feature. You can just re-arrange the data in your model to fit your needs.

**Comment by hasen6** [comment]
@goderbauer  That doesn't make any sense at all. The Listview already has a `reverse` option, why doesn't it have an option to select the start position? It makes no sense without it.

It's easy to say 'just reverse your data', but in practise it doesn't work well - I tried it. Since everything is backwards it can cause issues when you're using the feed in it's non reversed position everywhere else, and when the List is complex with a lot of calculations going on with it. If it's just a basic list with nothing much going it, and the same List is not used elsewhere it may be fine but otherwise it's not.

A start select position goes hand in hand with the `reverse` option for the listview - no point in having one without the other. If you're supposed to reverse your feed then why have the `reverse` option in the Listview in the first place...

**Comment by hasen6** [comment]
I tried `feed.reversed`, it reverses it but now deleting items and the buttons in the list all point to the wrong place. The code in my original post is better but none are very practical. Really need to be able to select scroll start position which goes hand in hand with the `reverse` option in `ListView` anyway.
