### ISSUE TITLE
How to run Android app with Maven in Flutter?

### ISSUE THREAD

**Issue by Medrov** [flutter/flutter#42083]
I have flutter project, there is android directory. And I want to use some libarary, but in order to reach this goal i have to use maven in android directory. Honestly i don't how to use maven, my task is create pom.xml, in which i can add dependcies. If anything this link to library. How can i reach my goal?

**Comment by BondarenkoStas** [comment]
will just leave it here for reference purposes https://stackoverflow.com/questions/58254707/how-to-run-android-app-with-maven-in-flutter.
