### ISSUE TITLE
Get List of all documents in a collection with firestone and flutter.

### ISSUE THREAD

**Issue by Hardeepsingh980** [flutter/flutter#42080]
Hello, I am new to flutter. I was trying to create an application where i need the list of all the documents in a collection of the firestone database.

I used  :- 

```
List<DocumentReference> userList;
_getAllUsers() async {
    QuerySnapshot querySnapshot =
        await Firestore.instance.collection("users").getDocuments();
    userList = querySnapshot.documents.cast<DocumentReference>();
    return userList;
  }

  @override
  void initState() {
    super.initState();
    userList = _getAllUsers();

  }
```

but i am getting a weird error saying :- 
`I/flutter (15163): Another exception was thrown: type 'Future<dynamic>' is not a subtype of type 'List<DocumentReference>'`

Please tell me what should i do.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
