### ISSUE TITLE
Customizeble cupertino thumb_painter color

### ISSUE THREAD

**Issue by alectogeek** [flutter/flutter#42088]
## Use case
I wanted to customize cupertino slider thumb color but discovered that the cupertino thumb painter color is hardcoded instead of using SliderThemeData or something like that.

## Proposal

Could you make it customizable, please?

**Comment by alectogeek** [comment]
![image](https://user-images.githubusercontent.com/18165303/66415331-079cdc00-ea04-11e9-87e4-9ea2db1c7afc.png)

**Comment by luizfranca** [comment]
Hi, I propose in [#42563](https://github.com/flutter/flutter/pull/42563) a solution to this issue by exposing the thumbColor to the user. I initially started adding the thumb color to the CupertinoTheme, but I didn't know if that was appropriated, so instead I just allow the user to pass a color, and if none are given I default to CupertinoColors.white, that is the current only possible color.

@LongCatIsLooong  in the [Tree hygiene guidelines](https://github.com/flutter/flutter/wiki/Tree-hygiene#who-to-have-review-your-code), I was instructed to tag @xster on this PR. But I am unable to request reviews this repo.

Thanks!
