### ISSUE TITLE
Cannot Resolve symbol 'Properties'

### ISSUE THREAD

**Issue by sagar90k** [flutter/flutter#42085]
Hi Team,

I am trying out few things in Flutter.I have updated Android studio today to 3.5.1.I was able to use my git code and run my app in device.I tried to configure app for firebase and added lines as per firebase instructions.Firebase said my app is communicating with firebase .I ran the app once again and it started to throw this error.I believe this error is related to gradle but not sure how to make this work.

**I can see below error:**

**settings.gradle highlights Properties and File in red color saying cannot resolve symbol 'Properties'**
```
include ':app'

def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}
```
***build.gradle*
```
buildscript {
    ext.kotlin_version = '1.2.71'
    repositories {
        google()
        mavenCentral()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        //classpath 'com.google.gms:google-services:4.3.2'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
**gradle-wrapper.properties**
#Fri Jun 23 08:50:38 CEST 2017
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip
```
**Flutter info**
```
Flutter 1.9.1+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cc949a8e8b (9 days ago) • 2019-09-27 15:04:59 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
```
**Android version:**
3.5.1

**Comment by BondarenkoStas** [comment]
@sagar90k Which firebase plugin do you use?
Please try to change maven to 
```
  maven {
    url 'https://maven.fabric.io/public'
  }
```
as it's said in https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_crashlytics.
Also, I'm afraid there will be error with google-services. If it will be, try to change the version as per this comment https://github.com/flutter/flutter/issues/38163#issuecomment-520429066.

**Comment by sagar90k** [comment]
Thanks for the reply!

Meanwhile I cloned my project from git once again and ran it .App was launched in device.
This cloned project doesnt have anything to do with firebase.When I open the settings.gradle, it highlights same thing 'Properties' and 'File' in red color in settings.gradle file.
Next, I stopped main.dart and once again ran  the main.dart and it still built the apk and ran successfully. Weird behaviour.

Now I dont have anything related to firebase in project , here is my content.

**build.gradle*
buildscript {
    ext.kotlin_version = '1.2.71'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}


**gradle-wrapper.properties**
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip

**Next thing I did is I invalidated cache and restarted just to check if everything works fine after restart and it worked all great**

Now if i want to follow steps for firebase once again then I think I will run into same problem again.Can anyone tell like what is causing this problem?Or what should be the best practice here so as to remove that red colored Properties and File in settings.gradle?

**Comment by BondarenkoStas** [comment]
@sagar90k I may be wrong, but I think it was absence of maven (not mavenCentral). Please try again following the instruction and keeping google-services v4.2.0. But anyway, what the firebase plugin you use?

**Comment by sagar90k** [comment]
Meanwhile i have just added firebase json and updated the given lines in gradle files as per firebase page.I deliberately used 4.3.1 instead of 4.3.2 for google services.It still worked and app was launched.We can close this for now.Thanks for the help!
