### ISSUE TITLE
Transactions not working after update

### ISSUE THREAD

**Issue by rizjohn** [flutter/flutter#42097]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by rizjohn** [comment]
when you wrap get,set,deete in a transaction it no longer changer firestore data

**Comment by janmoppel** [comment]
Hello @rizjohn !

Thank you for posting an issue.
Can you please provide more information, such as:
1) Example code to reproduce the issue;
2) `flutter doctor -v` command output.

Thank you.

**Comment by kroikie** [comment]
@rizjohn

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1196. Any further collaboration will be done there.
