### ISSUE TITLE
Cocoon push-status-to-github is failing

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#42092]
/cc @tvolkert @Hixie @keyonghan @godofredoc @digiter 

https://flutter-dashboard.appspot.com/api/push-build-status-to-github is failing on some type conversion. Because the tree is currently red, this means the statuses won't get updated to github.

This is particularly bad for autorollers right now...

**Comment by dnfield** [comment]
Strangely, it seems to not fail right now, but was definitely failing earlier in the weekend/Friday.

**Comment by jonahwilliams** [comment]
It only works on a red tree

**Comment by dnfield** [comment]
I didn't put TODAY because this isn't reallya  release blocker/bad build creator, but this should be considered a high priority infra issue for sure.

**Comment by jonahwilliams** [comment]
This was caused by an invalid data store entry. For now, the fix was to delete this  entity. Long-term, the  dart backend must be resilient to bad data.
