### ISSUE TITLE
type 'Future<dynamic>' is not a subtype of type 'Widget'

### ISSUE THREAD

**Issue by cqllzp** [flutter/flutter#42109]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by BondarenkoStas** [comment]
Unfortunately, this report does not have any actionable information - it’s not clear if this is a bug in user code, a bug in the framework, or something else entirely.
Please feel free to comment and I will re-open if you can add the following information:
The version of Flutter you’re using
The output of flutter doctor -v
The full exception you see
A minimal reproduction that leads to this exception.

**Comment by Gharmi** [comment]
Flutter 1.12.13+hotfix.5
• Engine revision 2994f7e1e6
• Dart version 2.7.0

type 'Future<dynamic>' is not a subtype of type '() => void'
The relevant error-causing widget was
    DetailBox
