### ISSUE TITLE
Record video without preview

### ISSUE THREAD

**Issue by chethanprabhakar** [flutter/flutter#42105]
Hi,

i am trying to create a video recording feature using camera plugin. I just want to record and save video, without playback as it is recording. Is it possible to suggest how to go about it?

Thanks
Chethan

**Comment by BondarenkoStas** [comment]
@chethanprabhakar This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
