### ISSUE TITLE
My application crash when I receive IOS notification and the app is open...

### ISSUE THREAD

**Issue by nefus8** [flutter/flutter#42113]
Hello ! I installed firebase_messaging in my flutter app and I don't know why, when I receive a notification on my physical device (iPhone Xs). The app crash with the error:

NoSuchMethodError: The method '[]' was called on null. 
Receiver: null
Tried calling: []("title")

But what I don't understand is that on the iOS simulator, it works perfectly fine and on all android devices, it works fine too. I don't have any null method or things like that... 

What's strenge is that when the app is not open on current page, (so when it's open in background or closed) it works perfectly fine and I receive the notifications...

I can't show you the logs of my physical device because I'm on windows and I use a virtual Mac os machine to build on iOS and I only can have the log of the simulator, but can't connect my real phone. If you need to, I can give you the simulator logs... I use Testflight to test my app on my physical device,

Here is my initState method:

```
static final FirebaseMessaging firebaseMessaging = FirebaseMessaging();
  StreamSubscription iosSubscription;

  @override
  void initState() {
    if (Platform.isIOS) {
      iosSubscription = firebaseMessaging.onIosSettingsRegistered.listen((data) {
        // save the token  OR subscribe to a topic here
      });

      firebaseMessaging.requestNotificationPermissions(IosNotificationSettings());
    }

    super.initState();

    firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async{
        print("onMessage: $message");
        if (Platform.isAndroid){
          showDialog(
            context: context,
            builder: (BuildContext context) {
              // return object of type Dialog
              return AlertDialog(
                backgroundColor: Colors.orangeAccent,
                title: Center(child: new Text(message['notification']['title'], style: TextStyle(color: Colors.white, fontSize: 25.0, fontWeight: FontWeight.bold),)),
                content: new Text(message['notification']['body'], style: TextStyle(color: Colors.white),),
                actions: <Widget>[
                  // usually buttons at the bottom of the dialog
                  new FlatButton(
                    child: new Text(allTranslations.text("OptPageDialog3"), style: TextStyle(color: Colors.white, fontSize: 20,),),
                    onPressed: () {
                      Navigator.of(context).pop();
                    },
                  ),
                ],
              );
            },
          );
        }
      },
      onLaunch: (Map<String, dynamic> message) async{
        print("onLaunch: $message");
      },
      onResume: (Map<String, dynamic> message) async{
        print("onResume: $message");

      },
    );
}
```

Does anyone has the same problem ?

**Comment by Fernandomr88** [comment]
There's a problem with onMessage at iOS since flutter 1.7.4 as it seems.

Check it out at
https://github.com/flutter/flutter/issues/36201

**Comment by nefus8** [comment]
Yeah, I saw that post, but it's not exactly like my error I believe... Because they say their notifications arrived but can't show in the background or foreground. For me, it's only when the app is open and it's not that it doesn't show up, it's just that it crashes and the app stops. They also talk about the Local Notification Plugin that may cause the error, but I'm not using it...

**Comment by kroikie** [comment]
@nefus8

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1040. Any further collaboration will be done there.
