### ISSUE TITLE
Flutter Localizations intl version

### ISSUE THREAD

**Issue by malikdoksoz** [flutter/flutter#42112]
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale
    tr-TR)
    • Flutter version 1.9.1+hotfix.4 at /Dosyalar/flutter_src/flutter
    • Framework revision cc949a8e8b (10 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/malikdoksoz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • SM N910C • 4100cf49f20512e9 • android-arm • Android 6.0.1 (API 23)

• No issues found!

**pubspec.yaml**

```
flutter_localizations:
    sdk: flutter

   intl: ^0.16.0 
```

**Running "flutter pub get" in flutterappexample...                   
Because flutterappexample depends on flutter_localizations any from sdk which depends on intl 0.15.8, intl 0.15.8 is required.

So, because flutterappexample depends on intl ^0.16.0, version solving failed.**
```

**Comment by BondarenkoStas** [comment]
Hm, flutter_localizations depends on intl 0.16.0 https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/pubspec.yaml. 
@malikdoksoz Can you try to run `flutter pub get` without having intl in flutterappexample dependency? May be it will update the package as it's needed.

**Comment by malikdoksoz** [comment]
> Hm, flutter_localizations depends on intl 0.16.0 https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/pubspec.yaml.
> But upgrade was done in v1.10.3 which is not in stable yet. I think you will need to use 0.15.8 or switch to dev/master branch.

I fixed with this dependency_overrides

```
dependency_overrides:
  intl: ^0.16.0
```

**Comment by Tayeb-Ali** [comment]
i have this issue but i need solution 
without update to 16 .
any help  plesss 

[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.6 at /home/ppain/development/flutter
    • Framework revision 18cd7a3601 (5 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

**Comment by ahernandez-developer** [comment]
that means you alredy have installed the package, because other package need as dependency, just import it. 
import 'package:intl/intl.dart';

**Comment by olintosergio** [comment]
> > Hm, flutter_localizations depende da int 0.16.0 https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/pubspec.yaml . 
> > Mas a atualização foi feita na v1.10.3, que ainda não está estável. Eu acho que você precisará usar 0.15.8 ou mudar para o ramo dev / master.
> 
> Corrigi com este dependency_overrides
> 
> ```
> dependency_overrides:
>   intl: ^0.16.0
> ```

Serviu para mim

**Comment by iNVISIBLExtanx** [comment]
when i try to override dependency, it do not show any error but when i try to run main.dart, it gives the following error, 

> Running Gradle task 'assembleDebug'...
> ../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/gradient_app_bar-0.1.3/lib/gradient_app_bar.dart:407:57: Error: No named parameter with the name 'nullOk'.
>     final ScaffoldState scaffold = Scaffold.of(context, nullOk: true);
>                                                         ^^^^^^
> ../../snap/flutter/common/flutter/packages/flutter/lib/src/material/scaffold.dart:1944:24: Context: Found this candidate, but the arguments don't match.
>   static ScaffoldState of(BuildContext context) {
>                        ^^
> ../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/gradient_app_bar-0.1.3/lib/gradient_app_bar.dart:636:20: Error: The method 'ancestorRenderObjectOfType' isn't defined for the class 'BuildContext'.
>  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/framework.dart').
> Try correcting the name to the name of an existing method, or defining a method named 'ancestorRenderObjectOfType'.
>     return context.ancestorRenderObjectOfType(
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script '/home/invisible/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991
> 
> * What went wrong:
> Execution failed for task ':app:compileFlutterBuildDebug'.
> > Process 'command '/home/invisible/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 21s
> Exception: Gradle task assembleDebug failed with exit code 1

my pubspec.yaml looks like this 

```
name: (myAppName)
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  flutter_form_builder: ^4.2.0
  table_calendar: ^2.3.3


  gradient_app_bar: ^0.1.3
  flutter_slidable: "^0.5.3"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

dependency_overrides:
  intl: ^0.16.0
```

can someone help me with this please. thank you very much
