### ISSUE TITLE
Real device detected as an emulator

### ISSUE THREAD

**Issue by athilams** [flutter/flutter#42110]
My physical device (Samsung J5 - SM G570M) is detected as an emulator, and therefore I cannot run in release mode. Everything else seems to run fine. 

## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

• No issues found!
```
```

**Comment by jmagman** [comment]
What is the output of `flutter doctor -v`?

**Comment by janmoppel** [comment]
Hello @athilams !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
