### ISSUE TITLE
No jni folder inside flutter-debug.aar

### ISSUE THREAD

**Issue by manueljpeixoto** [flutter/flutter#42111]
So I developing an sdk in flutter, and until the commit  d230234d67454c72ad16dc357e53bf8a50550671 on master I was able to do,
flutter create -t  module --org xxx native_sdk 
then run,
./gradlew assemDebug inside of native_sdk/.android, 
and the aar contained the jni and assets, also the flutter.jar was inside libs folder.

![Screenshot 2019-10-07 at 17 10 33](https://user-images.githubusercontent.com/34069553/66328940-7b1bec00-e925-11e9-9bba-aa35dcc52c8e.png)

but after that commit my flutter-debug.aar file doesn't have the jni folder or the flutter.jar inside libs. 

![Screenshot 2019-10-07 at 17 12 24](https://user-images.githubusercontent.com/34069553/66329029-a999c700-e925-11e9-937f-b902e0890b48.png)

I still can build the aar like I want in the Stable channel but there were lots of changes on the flutter.gradle file so I'm a little lost to understand what caused these changes.
```
[✓] Flutter (Channel master, v1.10.13-pre.12, on Mac OS X 10.14.5 18F132, locale en-PT)
    • Flutter version 1.10.13-pre.12 at /Users/manuelpeixoto/flutter
    • Framework revision 682e6383ac (18 hours ago), 2019-10-06 14:39:16 -0700
    • Engine revision 7d90779bb6
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 d6c6d12ebf)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/manuelpeixoto/Library/Android/sdk/
    • Android NDK at /Users/manuelpeixoto/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/manuelpeixoto/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Andre’s iPhone • cc1d6d81d55d69f29f44bd536782d0ee54226971 • ios • iOS 12.4.1

• No issues found!
```

**Comment by manueljpeixoto** [comment]
I was inspecting again the flutter.gradle and the method addFlutterDependencies adds the maven repo http://download.flutter.io/  then it adds libflutter.so by 
```
addApiDependencies(project, buildType.name,
                    "io.flutter:${arch}_$flutterBuildMode:1.0.0-$engineVersion")
```
but the depency in my case **io.flutter:armeabi_v7a_profile:1.0.0-819b0cae0c23ecaf84d5ff6dd0548e21587cf8b2**  is not present in the maven repository

**Comment by blasten** [comment]
@manueljpeixoto I'm able to download some of the artifacts: http://download.flutter.io/io/flutter/armeabi_v7a_profile/1.0.0-819b0cae0c23ecaf84d5ff6dd0548e21587cf8b2/armeabi_v7a_profile-1.0.0-819b0cae0c23ecaf84d5ff6dd0548e21587cf8b2.pom

Did you add the repository:  http://download.flutter.io/ ?
