### ISSUE TITLE
Flutter UI builder

### ISSUE THREAD

**Issue by Attacker-x** [flutter/flutter#42123]
When is the ui builder coming, coding the ui is waste of time and its nightmare with messy nested components! 

## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by BondarenkoStas** [comment]
@Attacker-x It's not on the current roadmap. Related #17548

**Comment by MelbourneDeveloper** [comment]
@BondarenkoStas can we get some official thoughts on this? It may be obvious to the maintainers of Flutter why this is not a high priority, but for outsiders, this is a major consideration. 

A visual editor doesn't need to be complete to be useful. It just helps someone go from knowing nothing, to being able to achieve basic layouts, and also gives people on the team some ability to modify layouts without knowing Dart. 

Currently, if I want to build a Flutter app, I have to invest a lot of time memorizing widget structures or copy/pasting code from other samples. A visual editor would cut down the learning curve to some extent.

If this isn't on the roadmap, will it be? If not, why not?
