### ISSUE TITLE
FontFamily doesn't apply to textTheme.title

### ISSUE THREAD

**Issue by vr19860507** [flutter/flutter#42135]
If we set fontFamily in the ThemeData constructor, then fontFamily doesn't apply to textTheme.title

This code doesn't work correctly!
```
MaterialApp(
  title: 'title',
  theme: ThemeData(
    fontFamily: 'FontFamily1',
    textTheme: TextTheme(
      title: TextStyle(fontFamily: 'FontFamily2'),
    ),
  )
);
```

**The problem is in the ThemeData constructor in the next lines.**
```
if (fontFamily != null) {
      textTheme = textTheme.apply(fontFamily: fontFamily);
      primaryTextTheme = primaryTextTheme.apply(fontFamily: fontFamily);
      accentTextTheme = accentTextTheme.apply(fontFamily: fontFamily);
    }
```
It overrides fontFamily values for title, body1 and other properties in textTheme, primaryTextTheme and accentTextTheme.

**Comment by HansMuller** [comment]
CC @darrenaustin
