### ISSUE TITLE
Incorrect index when prepending widget in listview

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#42142]
## Steps to Reproduce

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'List playground',
      home: TestPage(),
    );
  }
}

class TestPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  List<int> items = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]; //init list of items
  void _addItem({bool append}) {
    var now = DateTime.now().millisecondsSinceEpoch;
    if (append) {
      items.add(now);
    } else {
      items.insert(0, now);
    }
    setState(() {
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: ListView.custom(
          reverse: false,
          childrenDelegate: SliverChildListDelegate(
            List<Widget>.from(items.map((item) => _buildItem(item, items.indexOf(item))))
          ),
        ),
      ),
      bottomNavigationBar: BottomAppBar(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            FlatButton(
              onPressed: () => _addItem(append: true),
              child: Text('Append item'),
            ),
            FlatButton(
              onPressed: () => _addItem(append: false),
              child: Text('Prepend item'),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildItem(int data, int index) {
    return TestProxy(
      key: ValueKey(data),
      child: Container(
        height: 80.0,
        padding: EdgeInsets.all(16.0),
        decoration: BoxDecoration(
          border: Border(bottom: BorderSide()),
        ),
        child: Center(
          child: Text("index: $index . . . $data"),
        ),
      ),
    );
  }
}

class TestProxy extends StatefulWidget {
  final Widget child;

  const TestProxy({Key key, this.child}) : super(key: key);

  @override
  _TestProxyState createState() => _TestProxyState();
}

class _TestProxyState extends State<TestProxy> with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  void initState(){
    super.initState();
    print("");
    //print("Rebuild for ${widget.key.toString()}");
    print("");
  }

  @override
  Widget build(BuildContext context){
    super.build(context);
    return widget.child;
  }
}
```

1. scroll all the way to the end of list
2. click prepend item
3. scroll back to beginning, the item that prepended is not visible, which it should

**Comment by khainhero** [comment]
same issue here

for number 

> 2) click prepend item

prepend multiple times to see the issue on hand easily(more than once at least).

Flutter doctor -v :

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.4 at /Users/fa****/Desktop/flutter
    • Framework revision cc949a8e8b (10 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/fa****/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 • 8F32A367-AE35-489B-94DA-A*********** • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!
```

**Comment by chunhtai** [comment]
It looks like when a new element insert into front everything got shifted by one index. That bump a new element that is previously invisible into view. That newly created element with 0 layout offset which make the scrollable think the newly created element is the begin of list, which messes things up.
We should either give a more reasonable scroll offset or make RenderSliver better detect offset and self correct.

**Comment by imtoori** [comment]
Any news on this?
It's a really bad bug imho

**Comment by flightwonder** [comment]
for the widget you are trying to display in the list view just wrap the state with a keepalive. 

for example

class _Post extends State<Post>  with AutomaticKeepAliveClientMixin{


and dont forget to implement the keep alive above the build like so and add the super.build in widget.

 get wantKeepAlive => true;     <------- add this bruv
  @override
  Widget build(BuildContext context) {
super.build(context);    <---- add this too!

return Container()
}

hopefully that works.

**Comment by polobbgg** [comment]
> for the widget you are trying to display in the list view just wrap the state with a keepalive.
> 
> for example
> 
> class _Post extends State with AutomaticKeepAliveClientMixin{
> 
> and dont forget to implement the keep alive above the build like so and add the super.build in widget.
> 
> get wantKeepAlive => true; <------- add this bruv
> @override
> Widget build(BuildContext context) {
> super.build(context); <---- add this too!
> 
> return Container()
> }
> 
> hopefully that works.

This worked for me, but since I am now keeping alive images and videos, will there be an impact on memory?

**Comment by flightwonder** [comment]
it mostly does, in this case you would just paginate the data and load images/videos in bundles of groups. for example load 10 images then when the user scrolls past the bottom, load another 10 from the list.

**Comment by imtoori** [comment]
Actually that doesn't solve the problem
When I add an item in a portion of the custom listview that is not visible in the viewport the listview brakes

**Comment by chunhtai** [comment]
there is a pr open waiting for review https://github.com/flutter/flutter/pull/42703 which should fix this issue

**Comment by imtoori** [comment]
I tried to rebuild my app using your branch and it actually fixes the problem :)

Looking forward to seeing it merged

**Comment by chunhtai** [comment]
Original pr causes an internal test failure

**Comment by jensencelestial** [comment]
On which Flutter SDK version is this fix available?

**Comment by chunhtai** [comment]
It should be in latest stable 1.17.2

**Comment by jensencelestial** [comment]
Thanks!

**Comment by sabinbajracharya** [comment]
@chunhtai  I am on Flutter 1.17.2 • channel stable and dart Dart 2.8.3 and still when I remove the top item from the list all the items below it are disposed and the state is lost.
#21023
