### ISSUE TITLE
If the 'flutter' tool is actually a symlink, we still complain that it doesn't match the package flutter

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4214]
We have a report that if you call the flutter tool via a symlink, we get confused about what the real path to the tool is.

**Comment by eseidelGoogle** [comment]
This is blocking development for customer:leafy.  We can revert @devoncarew's change to unblock them, but it's probably just missing an abspath call.

**Comment by abarth** [comment]
Which change caused the trouble?  The person who reported the symlink issue sent us a fix for it.  https://github.com/flutter/flutter/commit/a24e90305ff9347219cf289d3f6c5ea89f7d418c
