### ISSUE TITLE
ListView.builder jumps on scroll up

### ISSUE THREAD

**Issue by brettfingo** [flutter/flutter#42159]
## Steps to Reproduce
For a ListView.builder, if the builder returns a Widget that changes size over its lifetime, then scrolling up in the list causes the list to jump.

1. Use a builder function in ListView.builder that changes height over its lifetime. For example, a Future builder that returns an empty Container while waiting for data and then resizes to an unknown size when the future has completed.
2. Scroll down in the list view for a while so a lot of items at the top are off screen and re-collected.
3. Scroll up slowly.
4. Notice that when new widgets are added on top and the future completes, the whole list jumps instead of scrolling smoothly.

**Target Platform:** iOS and Android
**Target OS version/browser:** all mobile OSs
**Devices:** emulator/simulator and physical devices.

## Logs

```
```

```
Analyzing list_view_scroll_bug...
No issues found! (ran in 1.6s)
```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F132, locale
    en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/brettcollins/development/flutter
    • Framework revision 2d2a1ffec9 (4 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/brettcollins/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] Connected device (2 available)
    • iPhone 5s • AD86C030-C41C-4517-9A8E-9776E73ED28C • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • iPhone Xʀ • 4B41034C-53D6-4D7E-B54B-B333F14CEAB5 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

Here is the example code:
```
@override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: ListView.builder(
        itemCount: _list.length,
        itemBuilder: (_, index) {
          return FutureBuilder<int>(
            future: Future.delayed(Duration(milliseconds: 200), () {
              return 1;
            }),
            builder: (context, snapshot) {
              return snapshot.hasData
                  ? Container(height: 50, child: Text(_list[index].toString()))
                  : Container();
            },
          );
        },
      ),
    );
  }
```

And here is the full file:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<int> _list = List.generate(200, (i) => i);

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: ListView.builder(
        itemCount: _list.length,
        itemBuilder: (_, index) {
          return FutureBuilder<int>(
            future: Future.delayed(Duration(milliseconds: 200), () {
              return 1;
            }),
            builder: (context, snapshot) {
              return snapshot.hasData
                  ? Container(height: 50, child: Text(_list[index].toString()))
                  : Container();
            },
          );
        },
      ),
    );
  }
}
```

![ListViewBuilderScrollBug](https://user-images.githubusercontent.com/47990899/66351450-700b9080-e912-11e9-9cba-7b4ed14fbc23.gif)

**Comment by khainhero** [comment]
in the listview builder, the children are disposed when not in view. When you scroll back up, it engaged a future causing this issue

one fix can be, to return a `StatefulWidget` with `AutomaticKeepAliveClientMixin` with the `wantKeepAlive` flag set to `true`. To also have your future from the initstate from that Statefulwidget

if your scenario is of the following: Adding new futures to end of the list and not re-ordering the list(i.e sorting, inserting into specific indexes..which causes shift of indexes)
then this following solution can be helpful:

https://github.com/flutter/flutter/issues/21023#issuecomment-510950338

doesnt require the AutomaticKeepAlive

As long as your data you load is added to the back of the list(Example: `_myList.add(data)`)

hope that helps out

**Comment by brettfingo** [comment]
If I have `wantKeepAlive` set to true, will the widgets be cleaned up when the ListView.builder is removed from the Widget tree? Also will this require too much memory if the ListView has thousands of children? Or is there a way to make sure we don't negatively impact performance with `AutomaticKeepAliveClientMixin`?

**Comment by mikhail-tokarev** [comment]
Hi, @brettfingo 
besides the closed issue quoted above (thanks @khainhero)
I see there's an issue currently open https://github.com/flutter/flutter/issues/42142.
I'm closing this as duplicate, please follow up on the linked issue.

**Comment by khainhero** [comment]
> If I have `wantKeepAlive` set to true, will the widgets be cleaned up when the ListView.builder is removed from the Widget tree? Also will this require too much memory if the ListView has thousands of children? Or is there a way to make sure we don't negatively impact performance with `AutomaticKeepAliveClientMixin`?

Yes, memory will be the issue. I only use AutomaticKeepAlive for certain widgets.

I hope that the issue mihail-tokarev has linked will be fixed. That can fix a lot of problems for us in the future.

**For now:**

normally for the futures, you should batch request the futures and add their objects into the list. Then use the listview builder to build the list to display the objects. 

if your end goal is to make calls to API for data from a backend, that would be better for you. Less overhead by requesting for example 20 objects compared to 1 by 1 requests on demand. When user scrolls to near end of the list of 20 objects, you can request another 20 objects from the API and add those to the List. This way you can put the backend calls out of the UI. (Pagination with a scroll controller)
