### ISSUE TITLE
Test and fix all iOS build modes

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#4216]
After the recent restructuring of the ios XCode project structure, several iOS build modes are failing.  Make sure they all work:

- [x] simulator, debug runtime, local engine, run via XCode
- [x] simulator, debug runtime, local engine, run via `flutter install` and `flutter run`
- [x] simulator, debug runtime, release engine, run via XCode
- [x] simulator, debug runtime, release engine, run `flutter install` and `flutter run`
- [x] device, debug runtime, local engine, run via XCode
- [x] device, debug runtime, local engine, run via `flutter install` and `flutter run`
- [x] device, debug runtime, release engine, run via XCode
- [x] device, debug runtime, release engine, run via `flutter install` and `flutter run`
- [x] device, profile runtime, local engine, run via XCode
- [x] device, profile runtime, local engine, run via `flutter install` and `flutter run`
- [x] device, profile runtime, release engine, run via XCode
- [x] device, profile runtime, release engine, run via `flutter install` and `flutter run`
- [x] device, release runtime, local engine, run via XCode
- [x] device, release runtime, local engine, run via `flutter install` and `flutter run`
- [x] device, release runtime, release engine, run via XCode
- [x] device, release runtime, release engine, run via `flutter install` and `flutter run`

**Comment by tvolkert** [comment]
@chinmaygarde and I are both working on this today :-)

**Comment by Hixie** [comment]
You forgot host, headless debug runtime, local and release engines, run via `flutter test`.

**Comment by tvolkert** [comment]
Several PRs already submitted towards this:
#4190 
#4191 
flutter/engine#2707
#4199 
#4208 
flutter/engine#2714
flutter/engine#2715

**Comment by chinmaygarde** [comment]
The device-targeted local-engine builds initiated by Xcode are now fine. Those harnesses are not able to target simulators ATM. Working on that now.

**Comment by eseidelGoogle** [comment]
Will we be testing these in any sort of automated fashion?  Can we simplify this list in any way?

**Comment by abarth** [comment]
> Can we simplify this list in any way?

We could aim to make the local and release engine configurations more similar.  They're more similar on Android than they are on iOS.  We could also remove either the `flutter run` or the Xcode entry point.

**Comment by Hixie** [comment]
How are they different on Mac?

**Comment by abarth** [comment]
`flutter run` uses `xcodebuild` to trigger Xcode to perform a build.  It then uses the various `idevice` commands to manipulate the device.  From Xcode, there's a button that performs the build and then Xcode itself manipulates the device.

**Comment by Hixie** [comment]
Sorry, I meant what is the difference between local and release configurations.

**Comment by abarth** [comment]
The difference is whether the binary artifacts are from the cloud or from a local build of the engine.

**Comment by chinmaygarde** [comment]
> Will we be testing these in any sort of automated fashion?

We can build each variant using `flutter build ios --runtime-mode <mode> <--simulator> <--no-codesign>` on a bot to make sure there are no build breaks. I am not too sure about actual devices. For local engine builds, we are the primary users. So breaks there should be caught early.

> Can we simplify this list in any way?

We can probably get rid of being able to launch an example directly from Xcode without any tooling support. AFAIK, I am the only user of this approach. I like being able to work on the engine by itself. But I guess I can be flexible in the workflow I use.

> We could also remove ... or the Xcode entry point.

Right now, the Xcode entry point is the only way to get to the debugger. So we should still keep it around till we figure out an alternative. Or did you mean the launch from Xcode directly? If so, yes, we can do that. We would still need some kind of an Xcode project though.

> what is the difference between local and release configurations.

Local iOS builds put their build artifacts in the out directory in a structure that is similar to the bucket that gets uploaded to cloud storage. You can then specify `--local-engine out/ios_debug_unopt` and have the tool use the local assets. The release configurations download these artifacts from the engine.version SHA.

**Comment by abarth** [comment]
I was thinking we might go the other way and drive all the builds from Xcode.  The idea would be that you'd "connect" to a running Flutter app to debug it or update its code.  That's similar to how the web inspector works with WebView-based apps.

**Comment by abarth** [comment]
Hum...  Maybe that's going too far.  The command line based builds are helpful to simply the workflow for new developers.
