### ISSUE TITLE
Add support for ClipOp with Canvas.clipPath

### ISSUE THREAD

**Issue by jkurtw** [flutter/flutter#42168]

**Comment by jkurtw** [comment]
This is to enable Lottie to Flare conversion for an asset needed by `customer: dream (g3)`

**Comment by luigi-rosso** [comment]
I prototyped this locally with a custom engine with these changes:
https://github.com/luigi-rosso/engine/commit/e5350bd43cec65cdf35bf84b03f713680d8dc223

And a custom Flutter with these changes:
https://github.com/luigi-rosso/flutter/commit/28aade41bd26dda289b0405b4ba4078c717b07e7

This was enough to do a custom mobile build and test that I could use both difference and intersection clipping with Canvas.clipPath.

This doesn't address Flutter Web. I see that there's a bunch of new (since I last contributed) work done to abstract the canvas into different backings for the web. I see the web side has both a Context2d canvas and a CanvasKit one. Seems like these are works in progress. Should I attempt to patch those up too before submitting?

**Comment by jkurtw** [comment]
Without further work, would this break web or just not work on web?

**Comment by luigi-rosso** [comment]
I'm not sure. I suspect I'll need to make similar changes to the function signatures for the various clipPath methods (recording_canvas.dart, web_ui/lib/src/engine/compositor/canvas.dart, and web_ui/lib/src/ui/canvas.dart).

I haven't been able to confirm it yet as the web build seems hang:

```
$ flutter run -d chrome --local-engine-src-path=/Users/luigirosso/Projects/engine/src --local-engine=host_debug_unopt
Launching lib/main.dart on Chrome in debug mode...
Throwing away cached asset graph due to Dart SDK update.
Rescheduling failed request...
Rescheduling failed request...
Rescheduling failed request...
Rescheduling failed request...
Rescheduling failed request...
Rescheduling failed request...
Rescheduling failed request...
Rescheduling failed request...
Building application for the web...                                    ⢿
```

I'm attaching the verbose build log below. Looks like a few things are failing/hanging but I don't see any details. Is there some other log file generated by the web build?
[web_build_verbose.log](https://github.com/flutter/flutter/files/3700263/web_build_verbose.log)

**Comment by ferhatb** [comment]
Can you convert the clipping path instead during the conversion instead of adding runtime support. Don't know how we can support this on the web without expensive runtime.

**Comment by luigi-rosso** [comment]
Hmmm...we could try with an evenOdd fillRule.

We could compose the clipping path by making a new path that first contains a rectangle with the dimensions of the canvas itself, and then the path itself on it as a hole. 

Try changing the difference to true/false here:
https://codepen.io/cirrus82/pen/oNNXxZP?&editable=true#anon-signup

If the clip path is composed of multiple paths (with a nonzero rule) then I think multiple clip operations have to be generated, combining each of the subpaths with the screen rectangle into individual new paths.

I can do some tests directly in Flutter to see if we can employ the same technique to mitigate needing the clipOp. I assume there'll be some performance implications as Skia can probably make assumptions when they know the entire op is a subtraction. It also means we'll need to limit the bounds for the difference to the size of the artboard, but that's probably ok.

**Comment by luigi-rosso** [comment]
I'm really close to having this working. I'll keep the issue open until I can get the full round trip working in Flutter... There are some caveats but I think this'll solve the issue fairly well without needing to touch the main Flutter codebase.

**Comment by luigi-rosso** [comment]
We can close this as thanks to @ferhatb's recommendation we came up with a workaround described above. This is working in Flutter with ```flare_flutter: ^1.6.0``` 

Thanks again!

**Comment by jkurtw** [comment]
w00t
