### ISSUE TITLE
Page https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment has perhaps stale information

### ISSUE THREAD

**Issue by filmil** [flutter/flutter#42183]
In Step 12 on https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment instructs to install `install-build-deps-linux-desktop.sh`.  This, however, does not exist.

I'm checking the project out for the first time so unsure if the script is supposed to exist or not.

**Comment by stuartmorgan** [comment]
The file [does exist](https://github.com/flutter/engine/tree/master/build). Note that the path listed in the instructions for that script is not the same as the path for the other scripts.

If you don't have it and are looking at the correct path, your engine repository `clone` failed in some way.
