### ISSUE TITLE
 Non-fatal exceptions are not reported until the next application restart.

### ISSUE THREAD

**Issue by PartnerDevRel** [flutter/flutter#42202]
We have a partner who is developing mobile apps using Flutter and Firebase, and currently use the firebase_crashlytics plugin.

In Flutter uncaught exceptions do not crash or kill the app so we are limited to reporting all issues as non-fatal. These non-fatal exceptions are not reported until the next application restart. This means we get reports of errors very late and in some cases it is possible that errors will never be reported as the SDK only keeps a finite collection to be sent upon app restart. We need reliable error reporting and we would like to continue to use Firebase for this purpose.

In the long term can you look into this problem and consider supporting Flutter as a first class use case?

In the short term is it possible to add an API that would allow to configure sending non-fatal errors immediate or at a regular interval?

**Comment by kroikie** [comment]
What the developer is seeing is correct, Crashlytics only submits reports on app start up.

The Crashlytics team is aware of the need to better support frameworks like Flutter. Work is on going to provide more APIs for frameworks to customize how exceptions are treated.

Non fatals being lost would be an issue for all Crashlytics apps not just Flutter so I have called out that one specifically in my feature request to the Crashlytics team.

**Comment by kroikie** [comment]
@PartnerDevRel

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1138. Any further collaboration will be done there.
