### ISSUE TITLE
Fuchsia test failures show up as infra failures rather than as step exceptions

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#42208]
We should update the analysis done in the recipe so that a step goes red instead of the build going purple - e.g. I would have expected https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia/1003 to have a red step.

**Comment by godofredoc** [comment]
This is fixed. Now "result for fuchsia_unittests" or "display builds" will show individual red steps instead of the task failing with infrastructure failure.

![image](https://user-images.githubusercontent.com/54371434/79890429-53b5d980-83b4-11ea-9dd4-ac9efc8c60de.png)
