### ISSUE TITLE
Android application fails to build if project is not named "app"

### ISSUE THREAD

**Issue by 420884853** [flutter/flutter#42214]
flutter_tools/gradle/flutter.gradle line 654
Project appProject = project.rootProject.findProject(':app')
assert appProject != null
"APP_xxx" in the my project , no 'app'。

**Comment by 420884853** [comment]
flutter version 1.10.13

**Comment by mikhail-tokarev** [comment]
hi, @420884853 
can you please post a self contained app on github to better address the issue,
thank you

**Comment by ultrapro** [comment]
after flutter upgraded, my project got the the following error:

FAILURE: Build failed with an exception.

* Where:
Script '/Users/username/opensource/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 654

* What went wrong:
A problem occurred configuring root project 'android'.
> A problem occurred configuring project ':flutter'.
   > Failed to notify project evaluation listener.
      > assert appProject != null
               |          |
               null       false

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 0s
Cause: assert appProject != null
       |          |
       null       false

**Comment by ultrapro** [comment]
> * flutter

Flutter 1.10.7 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e70236e36c (8 days ago) • 2019-10-02 09:32:30 -0700
Engine • revision 9e6314d348
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 1103600280)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.15 19A582a, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.1)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

**Comment by 420884853** [comment]
@mikhail-tokarev 
https://github.com/420884853/flutterIssues

**Comment by BernardGatt** [comment]
Same issue on `Flutter (Channel master, v1.10.15-pre.60, on Mac OS X 10.15 19A583, locale en-MT)`

**Comment by kassadin** [comment]
Same issue.
https://github.com/flutter/flutter/blob/3fea2838df051e99b2f72127a7d950287e522d0b/packages/flutter_tools/gradle/flutter.gradle#L660

The main project should not be hardcoded as 'app'

**Comment by jp1017** [comment]
1. Create New flutter module
2. compare the diffrence between the new flutter module with you project
3. update you project from the new flutter module
4. you will see, the new flutter module has app dir.

**Comment by alankley** [comment]
there seems to be agreement with kassad's comment that flutter.gradle should not be assuming that :app is being used.  I had renamed my Android application module to something different. Renaming it back to app solved the problem for me.

**Comment by heqingbao** [comment]
@kassadin is right
But it is worth mentioning that the old version is no problem. 
v1.10.0
flutter/packages/flutter_tools/gradle/flutter.gradle
```gradle
String mainModuleName = "app"
try {
 String tmpModuleName = project.rootProject.ext.mainModuleName
 if (tmpModuleName != null && !tmpModuleName.empty) {
     mainModuleName = tmpModuleName
 }
} catch (Exception e) {
}
// Only include configurations that exist in parent project.
Task mergeAssets = project.tasks.findByPath(":${mainModuleName}:merge${variant.name.capitalize()}Assets")
if (mergeAssets) {
 mergeAssets.dependsOn(copyFlutterAssetsTask)
}
```
So, temporary solution, you can modify the code corresponding to flutter to adapt to your own environment.

**Comment by praveenb** [comment]
I get same issue, after changing master channel and Flutter upgrade.
fixed it by editing flutter.gradle  file as below 

```
Project appProject = project.rootProject.findProject(':app')
if (appProject == null) {
	appProject = project.rootProject.findProject(':myApp')
}
assert appProject != null
```

Also faced mergeAssets null issue, fixed it as per @heqingbao reply.
```
Task mergeAssets = project.tasks.findByPath(":${mainModuleName}:merge${variant.name.capitalize()}Assets")
if (mergeAssets) {
 mergeAssets.dependsOn(copyFlutterAssetsTask)
}
```

Hope it helps.

**Comment by AlvinScrp** [comment]
Flutter --version :  1.12.13+hotfix.6-pre.1
In my AndroidStudio ,I have two application project. 
one is ":app" ,and another is ":flutterShellapp".
when i run  ":flutterShellapp"  after change flutter module code.  but the changes never take effect.

so  like @praveenb do. 
I Just copy the option for   ":flutterShellapp", and use both two. 
it's works for me !

             // Flutter module included as a subproject in add to app.
            def appModuleName=":app"
            Project appProject = project.rootProject.findProject(appModuleName)
            assert appProject != null
            appProject.afterEvaluate {
                assert appProject.android != null
                appProject.android.applicationVariants.all { appProjectVariant ->   
                    if (buildModeFor(appProjectVariant.buildType) != variantBuildMode) {
                        return
                    }
                    Task mergeAssets = project
                        .tasks
                        .findByPath("${appModuleName}:merge${appProjectVariant.name.capitalize()}Assets")
                    assert mergeAssets
                    mergeAssets.dependsOn(copyFlutterAssetsTask)
                }
            }

            def fAppModuleName=":flutterShellapp"
            Project fAppProject = project.rootProject.findProject(fAppModuleName)
            assert fAppProject != null
            fAppProject.afterEvaluate {
                assert fAppProject.android != null
                fAppProject.android.applicationVariants.all { fAppProjectVariant ->   
                    if (buildModeFor(fAppProjectVariant.buildType) != variantBuildMode) {
                        return
                    }
                    Task mergeAssets = project
                        .tasks
                        .findByPath("${fAppModuleName}:merge${fAppProjectVariant.name.capitalize()}Assets")
                    assert mergeAssets
                    mergeAssets.dependsOn(copyFlutterAssetsTask)
                }
            }

**Comment by vivchar** [comment]
Any update? Could you fix this? We need ability to use different app module names. In our project we have two app modules.

**Comment by AnisovAleksey** [comment]
Looks like without fixing this issue you can't integrate flutter into existing project, please fix it

**Comment by nateshmbhat** [comment]
im having the same issue.

I have multiple flutter modules setup .

When i run "flutter build aar" , it gives me this error :

* Where:

```
Initialization script '/Users/nateshmbhat/Apps/flutter/packages/flutter_tools/gradle/aar_init_script.gradle' line: 147

* What went wrong:
Failed to notify build listener.
> assert moduleProject != null
         |             |
         null          false

```

**Comment by YunanChen** [comment]
Is there any update? I get same issue

**Comment by nateshmbhat** [comment]
I think this error happens when u create a flutter module or plug in or any package other than a normal "Flutter app" project.

So when u build ur application, in recent versions which support web, u need to create a Flutter app project.

**Comment by nateshmbhat** [comment]
If you still wish to have a sub module or package, u can create it inside the Flutter app project. And build only those sub modules or package by running flutter build inside those folders.

**Comment by nateshmbhat** [comment]
This error needs a proper error message. The above message is confusing to many people.

**Comment by Alifyz** [comment]
Well, I had the same issue but I was able to figure it out that my module app which is created by the default was renamed to "presentation."

To fix that, I had to tell flutter gradle tools that my host app entry point is in fact "presentation", so I added the following line in gradle.properties of my main Android application. 

`flutter.hostAppProjectName=presentation`

**Comment by brandnewx** [comment]
I can confirm setting the project name of :app module will make Flutter groovy script go crazy because it can't find the module.

`project(':app').name = 'Your-Project-Name'`

That above line if removed will fix several Gradle errors.

**Comment by XuanTung95** [comment]
Duplicate #28605 #54930

Same as @Alifyz comment, I confirm can solve the issue by adding 

> flutter.hostAppProjectName=project_name

to Android host's gradle.properties file

As described in the doc [flutter-module](https://flutter.dev/docs/development/add-to-app/android/project-setup#add-the-flutter-module-as-a-dependency)
>  Tip: By default, the host app provides the :app Gradle project. To change the name of this project, set flutter.hostAppProjectName in the Flutter module’s gradle.properties file. Finally, include this project in the host app’s settings.gradle file mentioned below.

It said set flutter.hostAppProjectName in module’s gradle.properties. Should it be 'host's gradle.properties ' instead of 'module’s gradle.properties'?

**Comment by maheshmnj** [comment]
Looks like this behavior has changed, now you no longer needs to name as "app" 

https://github.com/flutter/flutter/blob/922eea8763d0c9a997d9a927b42c16cb29467465/packages/flutter_tools/gradle/flutter.gradle#L1028

Can anyone confirm on the latest master channel, if you are still experiencing the issue?
