### ISSUE TITLE
WebSocketException: Connection to 'http://localhost:xxxx' was not upgraded to websocket

### ISSUE THREAD

**Issue by ntajxyooj** [flutter/flutter#42210]
WebSocketException: WebSocketException: Connection to 'http://localhost:52878/devtools/page/3F11102A786CB8FD0DBE906ECA8E62B7#' was not upgraded to websocket

```
#0      _WebSocketImpl.connect.<anonymous closure>.error (dart:_http/websocket_impl.dart:1052:9)
#1      _WebSocketImpl.connect.<anonymous closure> (dart:_http/websocket_impl.dart:1061:14)
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#8      Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by janmoppel** [comment]
Hello @ntajxyooj !

Thank you for posting an issue.
This problem was previously reported and discussed here: #11444. Can you please check whether solutions proposed there work for you? 

Also, can you please post the `flutter doctor -v` command output?

Thank you.

**Comment by janmoppel** [comment]
Hello @ntajxyooj !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.

**Comment by envy13** [comment]
still facing this issue ? anyyy one got solution ?? 
WebSocketException: Connection to 'http://52.57.112.216:6001/chats/5#' was not upgraded to websocket
