### ISSUE TITLE
Flutter command line cannot be used with multiple instances.

### ISSUE THREAD

**Issue by PratikMMohite** [flutter/flutter#42225]
When i tried to run two flutter projects at a time the lock has been set to command line and only one project started running.then it displays message as "Waiting for another flutter command to release the startup lock..." .When the one project takes a long time to build app the next project can't out from waiting state. 

simple you can get this result using:
1)open two cmd
2)run on both flutter doctor
3)one get in this state
```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18990.1],
    locale en-US)
    • Flutter version 1.9.1+hotfix.4 at D:\software\flutter
    • Framework revision cc949a8e8b (11 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Pratik\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\Pratik\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • Redmi 4 • 4d78c0c57cf4 • android-arm64 • Android 7.1.2 (API 25)

• No issues found!
```

**Comment by BondarenkoStas** [comment]
@PratikMMohite The tool is not supposed to support multithreading. But if you still want it, you can have another flutter on your laptop (just copy the folder and specify extra path to run from it) and execute both of them simultaneously.

**Comment by PratikMMohite** [comment]
even I use flutter --help two times on different command lines it also shows the same message
`C:\User\administrator>flutter --help
Waiting for another flutter command to release the startup lock...
Manage your Flutter app development.
`
