### ISSUE TITLE
mDNS lookup failed, attempting fallback to reading device log

### ISSUE THREAD

**Issue by felixyin** [flutter/flutter#42222]
[ +108 ms] success
[        ] (lldb)     safequit
[ +107 ms] Process 267 detached
[  +53 ms] Application launched on the device. Waiting for observatory port.
[   +2 ms] Checking for advertised Dart observatories...

flutter问题可真多，bug量估计创新纪录了。提个小建议：能否不要急着扩展类库组件、新特性，先把bug解决差不多吧！！
(google translate)
The flutter problem is really much, and the bug count is an innovative record. A small suggestion: Can you not rush to extend the library components, new features, first solve the bug almost! !

我的情况是可以运行，但是hotreload不能工作：
[+5014 ms] mDNS lookup failed, attempting fallback to reading device log.
[        ] Waiting for observatory port.

**Comment by felixyin** [comment]
flutter --version
Flutter 1.9.1+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cc949a8e8b (11 days ago) • 2019-09-27 15:04:59 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

**Comment by felixyin** [comment]
➜  shuichan_app git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G84, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.4 at /Users/fy/tools/flutter
    • Framework revision cc949a8e8b (11 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/fy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/fy/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6262.58

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • iPhone • 55a7454b0af851ec72fb276cc45d3130f53d9817 • ios • iOS 13.1.2

• No issues found!

**Comment by CarGuo** [comment]
It work correct under the latest stable version v1.9.1+hotfix.4 . 

<img width="616" alt="image" src="https://user-images.githubusercontent.com/10770362/66386944-8e968800-e9f5-11e9-8637-54df3b92ddef.png">

<img width="584" alt="image" src="https://user-images.githubusercontent.com/10770362/66386697-35c6ef80-e9f5-11e9-9058-26e32c001679.png">

**Comment by mikhail-tokarev** [comment]
Hi, @felixyin 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it

**Comment by felixyin** [comment]
I\ am\ trying\ to,\ wait\ a\ moment

**Comment by felixyin** [comment]
after flutter upgrade:
Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: XMXKKWB4BQ
Running Xcode build...
Xcode build done.                                           11.6s
Could not find the built application bundle at build/ios/iphoneos/Runner.app.
Error launching application on iPhone.

**Comment by felixyin** [comment]
f**k,

**Comment by felixyin** [comment]
i deploy ios to app store, what way?
i use xcode change the project name，难道就不行了？

**Comment by BondarenkoStas** [comment]
> i deploy ios to app store, what way?
> i use xcode change the project name，难道就不行了？

I just trapped on https://stackoverflow.com/a/58050017, but no idea if it's actually possible to change the name and this is a bug

**Comment by felixyin** [comment]
you can close the issue，rename to Runner that's works well.

**Comment by elliott-io** [comment]
My name has been set to Runner and I'm having the same issue.

**Comment by elliott-io** [comment]
Any idea what to do here? 

I still have this issue when trying to debug iOS (iPhone XS attached via USB) using VS Code.

```
[  +87 ms] Application launched on the device. Waiting for observatory port.
[   +4 ms] Checking for advertised Dart observatories...
[+5016 ms] No pointer records found.
[   +3 ms] mDNS lookup failed, attempting fallback to reading device log.
[        ] Waiting for observatory port.
```

Output from `flutter doctor -v`

```

[✓] Flutter (Channel master, v1.12.5-pre.14, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.12.5-pre.14 at /Users/username/Documents/dev/flutter
    • Framework revision 6e10719dc5 (3 hours ago), 2019-11-18 17:23:30 -0800
    • Engine revision 9832bc8f2e
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/username/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone • [id] • ios • iOS 13.1.3

• No issues found!
```

**Comment by arnemolland** [comment]
@elliott-io Do you have a specific network environment? I'm getting this issue when using the guest network at the office, but it works just fine otherwise.

**Comment by eemelianov** [comment]
i had the same issue, the problem was MacOS firewall. In firewall-settings you can choose to block all incoming connections (not the stealth mode). Everything works fine after disabling.

**Comment by synapp009** [comment]
had issue with 

> @elliott-io Do you have a specific network environment? I'm getting this issue when using the guest network at the office, but it works just fine otherwise.

was related to wlan environment in a public cafè. connected with hotspot of my iphone solved the issue.

**Comment by SFA16SCM63A** [comment]
When I connected my iPhone to wifi, then It started working. For some reason, it was not working when my iPhone connected to carrier's internet

**Comment by alexgarciaju** [comment]
Im having the same issue, always waiting for the observatory port on any iOS device.

```
[  +87 ms] Application launched on the device. Waiting for observatory port.
[   +3 ms] Checking for advertised Dart observatories...
[+5027 ms] No pointer records found.
[   +3 ms] mDNS lookup failed, attempting fallback to reading device log.
[        ] Waiting for observatory port.
```

and there's my `flutter doctor` logs:

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-ES)
    • Flutter version 1.12.13+hotfix.5 at /Users/alex/Documents/flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/alex/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone • cb08e67bf810e983f7a8034301b88e356c7bb988 • ios • iOS 13.3

• No issues found!
```

**Comment by jmagman** [comment]
mDNS lookup failure can happen for a few reasons.  See history in https://github.com/flutter/flutter/issues/41085.  There's a meta-bug at https://github.com/flutter/flutter/issues/46705 that might help you track down what's fixed and what's not.  Closing since we have this issue covered by other issues.
