### ISSUE TITLE
release hotfix version of 1.9.1 with dart 2.5.1

### ISSUE THREAD

**Issue by ethael** [flutter/flutter#42226]
Current latest stable and also beta is v1.9.1+hotfix.4 and is using dart 2.5.0
Dart 2.5.0 has a bug, that was fixed in 2.5.1 (https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#251---2019-09-27)

I am encountering this problem in several of my apps. 
Please release new hotfix version with dart 2.5.1

Temporary workaround:
flutter-sdk has dart-sdk embedded. it is located in {flutter-sdk-dir}/bin/cache/dart-sdk. I have removed sdk 2.5.0 and replaced with manually downloaded 2.5.1. that resolved my issues. however, Dart analysis window refresh button in IDE didn't work, but manual clicking on every reported error in the list made the error finally disappear and flutter build apk went fine too.

**Comment by mikhail-tokarev** [comment]
Hi @ethael ,
Dart version will be updated in the future Flutter version
thank you for the solution you proposed.
I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it

**Comment by ethael** [comment]
Well, unfortunately I disagree. Is it that hard to at least upgrade dart in flutter beta channel and release as another beta before you'll release beta based on 1.10? Because current state is unusable. No stable nor beta available with fix incorporated

**Comment by ethael** [comment]
@mikhail-tokarev ignore?

**Comment by iapicca** [comment]
Hi @ethael,
if you decide to upgrade to a Dart version ahead of the one
used in the stable version you may consider to [upgrade](https://flutter.dev/docs/development/tools/sdk/upgrading#selecting-a-specific-version) to  Dev Channel and a use a Dev [SDK](https://flutter.dev/docs/development/tools/sdk/releases)
you can run in your terminal :
```
flutter channel dev
flutter version 1.10.14
flutter upgrade
```
please let me know if this approach solves your issue.
Thank you

**Comment by ethael** [comment]
@iapicca thanks a lot for the advise. this is probably not feasible for most of the people dealing with this problem. I can not use dev channel. I need all of the stability of stable channel. I only need this bug to be fixed, because it prevents project to be even built.

dart 2.5.1 version itself is only a hotfix of 2.5.0 with no aditional changes. so it should be drop-in replacement for 2.5.0 in current 1.9.1+hotfix.4 without any other work/change to be done in flutter itself.

**Comment by MartinHlavna** [comment]
Well, this issue basically means that production applications affected by this issue can't upgrade to current stable without applying ethael's workaround as they probably cannot (nor should) rely on dev channel.

**Comment by ethael** [comment]
Ok. Looks like you ignored the request for v1.9 hotfix as there is a beta release of v1.10 already out. Thats quite unfortunate for us. Closing the ticket.
