### ISSUE TITLE
[web]Any Websocket solution for flutter_web? 

### ISSUE THREAD

**Issue by greatGregLiu** [flutter/flutter#42228]
flutter doctor -v
[✓] Flutter (Channel dev, v1.10.13, on Mac OS X 10.13.6)
    • Flutter version 1.10.13 at /Users/gregliu/Downloads/flutter
    • Framework revision 97e00b2288 (21 hours ago), 2019-10-07 08:11:45 -0700
    • Engine revision 7d90779bb6
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 d6c6d12ebf)

I tried these 2 packages. 
https://pub.dev/packages/websocket
https://pub.dev/packages/web_socket_channel

websocket issue:
https://github.com/truongsinh/dart-websocket/issues/1
Skipping compiling nb|lib/main_web_entrypoint.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:
main.dart

web_socket_channel issue:
https://github.com/dart-lang/web_socket_channel/issues/81
Launching lib/main.dart on iPhone 8 Plus in debug mode...

Compiler message:
../../../.pub-cache/hosted/pub.flutter-io.cn/web_socket_channel-1.0.15/lib/html.dart:8:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../../../.pub-cache/hosted/pub.flutter-io.cn/web_socket_channel-1.0.15/lib/html.dart:21:9: Error: Type 'WebSocket' not found.
  final WebSocket _webSocket;
        ^^^^^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/web_socket_channel-1.0.15/lib/html.dart:21:9: Error: 'WebSocket' isn't a type.
  final WebSocket _webSocket;
        ^^^^^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/web_socket_channel-1.0.15/lib/html.dart:67:14: Error: The method 'WebSocket' isn't defined for the class 'HtmlWebSocketChannel'.
 - 'HtmlWebSocketChannel' is from 'package:web_socket_channel/html.dart' ('../../../.pub-cache/hosted/pub.flutter-io.cn/web_socket_channel-1.0.15/lib/html.dart').
Try correcting the name to the name of an existing method, or defining a method named 'WebSocket'.
      : this(WebSocket(url.toString(), protocols)
             ^^^^^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/web_socket_channel-1.0.15/lib/html.dart:74:34: Error: The getter 'WebSocket' isn't defined for the class 'HtmlWebSocketChannel'.
 - 'HtmlWebSocketChannel' is from 'package:web_socket_channel/html.dart' ('../../../.pub-cache/hosted/pub.flutter-io.cn/web_socket_channel-1.0.15/lib/html.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WebSocket'.
    if (_webSocket.readyState == WebSocket.OPEN) {
                                 ^^^^^^^^^
../../../Downloads/flutter/packages/flutter/lib/src/painting/_network_image_web.dart:56:12: Error: Method not found: 'webOnlyInstantiateImageCodecFromUrl'.
    return ui.webOnlyInstantiateImageCodecFromUrl(resolved); // ignore: undefined_function
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:532:37)
#2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#3      asFileUri (package:vm/kernel_front_end.dart:531:22)
#4      writeDepfile (package:vm/kernel_front_end.dart:718:21)
#5      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

Compiler failed on /Users/gregliu/data/flutter/nb/lib/main.dart
Error launching application on iPhone 8 Plus.

They both are not working for flutter web. Any solution for websocket for flutter web? Thanks

**Comment by jonahwilliams** [comment]
I'm not sure about `package:websocket`, but that compiler error has been fixed on the latest master so you might want to try it again

**Comment by greatGregLiu** [comment]
Thanks.  They work after I switch to the latest master branch. Appreciate it
