### ISSUE TITLE
If the same set of code is playing different Apk

### ISSUE THREAD

**Issue by Tumbler0809** [flutter/flutter#42224]
My needs are as follows:

Write a set of code, how to generate two package names for APK in Flutter

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
