### ISSUE TITLE
flutter_web flutter create . error

### ISSUE THREAD

**Issue by xiebanglong** [flutter/flutter#42223]
![image](https://user-images.githubusercontent.com/44019629/66387876-7aec2100-e9f7-11e9-9afc-e6b234dce996.png)

**Comment by BondarenkoStas** [comment]
@xiebanglong Please don't post code/logs in the form of screenshots, it prevents them from being copied.
Why would you want to create a project in the same folder? Please try to do it `flutter create <projectname>` so it will be created in the specified folder.

**Comment by xiebanglong** [comment]
because i want use flutter_web, so i use flutter create . ,but I didn't succeed

**Comment by xiebanglong** [comment]
> @xiebanglong Please don't post code/logs in the form of screenshots, it prevents them from being copied.
> Why would you want to create a project in the same folder? Please try to do it `flutter create <projectname>` so it will be created in the specified folder.

because i want use flutter_web, so i use flutter create . ,but I didn't succeed

**Comment by jonahwilliams** [comment]
If you created your flutter app with an --org, you need to use that some org to add web support

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
