### ISSUE TITLE
AssetBundle.needsBuild(..) ignores deleted wildcard directories.

### ISSUE THREAD

**Issue by cskau-g** [flutter/flutter#42230]
[asset.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/asset.dart)'s `needsBuild(..) {..}` returns whether an `AssetBundle` needs to be (re)built given a corresponding manifest.
Its approach is to check the existence and modified timestamp on the manifest and its directories.
However, when checking the directories (`_wildcardDirectories`) it checks if `modified` returns null, in which case it skips the directory.
For [`MemoryFileSystem`](https://github.com/google/file.dart/blob/master/packages/file/lib/src/backends/memory/memory_file_stat.dart#L19-L25) this unfortunately means that if a "wildcard dir" is deleted, `needsBuild` will simply ignore it and will likely return false.

I believe this is a bug as any major changes to the filesystem should likely indicate that the `AssetBundle` needs rebuilding?

**Comment by mikhail-tokarev** [comment]
Hi @cskau-g 
can you please provide your `flutter doctor -v`,
also if you could post a self contained app on github 
it'd help to better address the issue,
thank you

**Comment by cskau-g** [comment]
Sorry, I have none of the above.
I'm gardening Dart's [flutter-engine-linux](https://ci.chromium.org/p/dart/builders/ci.sandbox/flutter-engine-linux) build bot, and noticed [this issue](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8900184260662664320/+/steps/flutter_test_tool_coverage/0/stdout) which is caused by a test failure in [`asset_bundle_test.dart`](https://chromium.googlesource.com/external/github.com/flutter/flutter/+/refs/heads/master/packages/flutter_tools/test/general.shard/asset_bundle_test.dart#132):
```
 02:15 +256 ~4 -1: test/general.shard/asset_bundle_test.dart: AssetBundle.build handle removal of wildcard directories [E]                                                                              
   Expected: <true>
     Actual: <false>
```

I'm not sure this is strictly related, but after a bit of digging through the code, it seems one possible way that test could fail.
I don't currently have a flutter check out to test it on, but it's possible running that test file could reproduce the error.

**Comment by jonahwilliams** [comment]
This test has been fairly stable for the last several months. I originally wrote it so I will look into it more

**Comment by cskau-g** [comment]
Thanks for looking into it, Jonah.
But just to be clear, I meant for this issue to track the possible bug in AssetBundle, and not the test flakiness itself - I am in fact not sure the flakiness is caused by this issue. I just happened to discover one after looking into the other.

I was hoping one of you folks would be able to sanity check my logic above and tell if the current implementation is buggy?
