### ISSUE TITLE
Google Sign In / Firebase Auth & Refresh Token for Google APIs

### ISSUE THREAD

**Issue by nealdyrkacz** [flutter/flutter#42238]
I have been trying to figure out how to proceed to call Google Calendar API from a Firebase Cloud function.

Currently the Flutter App is using the Google Sign In plugin to authenticate and authorize a user ( and it adds the Google Calendar scope ).  A firebase user is then created/updated off of these credentials.

The issue is the Google Sign In is not returning a **Refresh Token**,  only Access Token and an Id Token.

` final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    final GoogleSignInAuthentication googleAuth =
        await googleUser.authentication;

    final AuthCredential credential = GoogleAuthProvider.getCredential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );
    final FirebaseUser user = await _auth.signInWithCredential(credential);`

The goal is to have a **scheduled** Cloud Function in Firebase that will run and access Google Calendar events for ALL users in the system using the Node.js Client for Google APIs.  

Have hit sort of a dead end with out having that refresh token, since accessing the google apis, needs to check the refresh token.  Since this is happening in the background in a cloud function we can not redirect to a confirmation screen for the user.

**Comment by nealdyrkacz** [comment]
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/nealdyrkacz/Documents/DEVELOPMENT/flutter
    • Framework revision 2d2a1ffec9 (5 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nealdyrkacz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[!] Connected device
    ! No devices available

**Comment by kroikie** [comment]
@nealdyrkacz

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1079. Any further collaboration will be done there.

**Comment by Aayushshah196** [comment]
Can anyone tell me why this code does not work?
Thanks in advance


 //firebase authentication
  final FirebaseAuth _auth = FirebaseAuth.instance;
  //Google sign in instance;
  final GoogleSignIn _googleSignIn = new GoogleSignIn();

  Future<FirebaseUser> _signIn() async {
    final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    final GoogleSignInAuthentication googleAuth = await googleUser.authentication;
    final AuthCredential credential = GoogleAuthProvider.getCredential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );
    
    final FirebaseUser user = await _auth.signInWithCredential(credential);
    print("signed in " + user.displayName);
    return user;
  }

**Comment by hudson-dev** [comment]
Any updates?

**Comment by BoonJunTan** [comment]
Any updates on this as I also required to have the refresh token
