### ISSUE TITLE
Fuchsia tests should retry on initial failure

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#42242]
There have been at least two Fuchsia failures in the last day that failed due to network connectivity issues.  The Fuchsia bots should retry (preferably the package serving requests, or perhaps the whole test) after an initial failure.

/cc @godofredoc @keyonghan @digiter

**Comment by godofredoc** [comment]
Should we try to find out the cause for the network problems before adding retries? Any links to logs that I can take a look at?

**Comment by dnfield** [comment]
https://chromium-swarm.appspot.com/task?id=47c534daef2ea210

https://chromium-swarm.appspot.com/task?id=47c4c2ff6ba48b10

Are two examples

**Comment by godofredoc** [comment]
I replaced some of the network cables, hopefully it was just a bad cable.

Going forward we'll need the serial output to triage paving problems. Are there any plans to collect those logs?

**Comment by godofredoc** [comment]
I haven't seen the network problem anymore. Please reopen if you find it again.
