### ISSUE TITLE
Navigator.pushReplacementNamed does not update address bar

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#42255]
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.14-pre.15, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2019.2)
[✓] VS Code (version 1.38.1)
[✓] Connected device (4 available)
```

This commit shows where I'm working the navigator logic: https://github.com/flutter/devtools/pull/1144/commits/2759f5918a9b9d450ae27eafc727d0aa77106870

popAndPushNamed does update the address bar with the new route, but pushReplacementNamed does not.

**Comment by mdebbar** [comment]
We are not handling the replacement of routes in the web engine (see [code here](https://github.com/flutter/engine/blob/414ad38662515526cfc7aa368fe7e024a500575d/lib/web_ui/lib/src/engine/window.dart#L154-L161)).

Thanks for filing the issue, I'll have a PR ready soon.
