### ISSUE TITLE
Arrow keys cause unwanted focus traversal when a text field is active

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#42259]
Shortcuts introduced in [this PR](https://github.com/flutter/flutter/pull/40186) allow the user to switch between text fields, buttons, etc. using the keyboard. The PR has been reverted in https://github.com/flutter/flutter/pull/41945, so I'm pointing my local repo to the commit immediately preceding the revert ([#780bddcca](https://github.com/flutter/flutter/tree/780bddcca57d9773b48ee8657b3aef995ed9595b)).

### Current (problematic) behavior
When a text field is being edited, clicking any arrow key will move the focus to another element on the page.

I tested this using the gallery app running on:
* Flutter web on Chrome.
* Native flutter on Android Simulator.

### Desired behavior
On desktop web, arrow keys shouldn't escape the text field.

AI(@gspencergoog): On native desktop, we need to figure out what the expected behavior is for single-line and multi-line text fields.

**Comment by yjbanov** [comment]
@gspencergoog Since you are assigned, should we put this in a more specific milestone? October or November perhaps?

**Comment by gspencergoog** [comment]
Set to October.  I'm think I'm going to just disable arrow key focus navigation for text fields altogether.
