### ISSUE TITLE
No logs output from iphone device

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4225]
I'm not seeing anything in the logs output, when trying to see what went wrong with my iPhone.

I'm trying to run Step 5 of the codelab on my iPhone. The app boots but I can't send and receive messages. I'm trying to figure out what's going on:

```
~/tmp/firechat-flutter/step_5[master*] $ flutter -d i logs
Showing iPhone logs:

```

Should I see anything in the logs output?

Meanwhile, I can use Xcode's "view device logs" and I see lots of interesting output, such as:

```
May 26 15:29:31 iPhone Runner[324] <Notice>: [ERROR:dynamic_service_definition.cc(39)] Could not open the service dylib.
May 26 15:29:31 iPhone Runner[324] <Notice>: [ERROR:FlutterDynamicServiceLoader.mm(61)] Could not load dynamic service for 'firebase::Firebase'
May 26 15:29:49 iPhone syslog_relay[133] <Notice>: syslog_relay read 51 total bytes: 
```

**Comment by sethladd** [comment]
cc @devoncarew @chinmaygarde

**Comment by sethladd** [comment]
This was explained to me a bit. The `flutter logs` command is really intended to provide logs from Dart code running in Flutter. The `logs` command is filtering just for statements that came from flutter's code itself.

To see all the log statements, a developer needs to use platform-specific methods (such as `adb logcat`).

**Comment by chinmaygarde** [comment]
This has been fixed in https://github.com/chinmaygarde/flutter/commit/9782d97faacbafa1a8b4511d8109cb1a1a2e11b3#diff-4e6a9727ba10772d640b597dbdd61d03R424

![screen shot 2016-06-16 at 11 46 08 am](https://cloud.githubusercontent.com/assets/44085/16129044/0d7a6422-33b8-11e6-83be-71047a991a76.png)

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1027. Any further collaboration will be done there.
