### ISSUE TITLE
SharedPreferences should provide tryGet...() getters

### ISSUE THREAD

**Issue by magnus-lpa** [flutter/flutter#42262]
When attempting to read a value from `SharedPreferences`, an exception is thrown if the value exists but is the wrong data type. This makes it cumbersome to fall back to a default value and resume execution when reading multiple values after each other, since even if you wrap the whole thing in a try-catch block, if one value fails the ones after it will not be read.

## Use case

The code below will result in `type 'double' is not a subtype of type 'int'`.  

    SharedPreferences p = await SharedPreferences.getInstance();
    p.setDouble('mynumber', 0.0);

    try{
      int i = p.getInt('mynumber') ?? 0; // <-- Will throw an exception
      String s = p.getString('mystring') ?? ''; // <-- Will not be executed
      bool b = p.getBool('mybool') ?? false; // <-- Will not be executed
    }
    catch(e){
      // Not all preferences were read, but I have no idea which ones were and which ones were not.
    }

## Proposal

There should be a way to fall back to a default value without throwing an exception if the read fails (for example if the value exists but is another type).

    int i = p.tryGetInt('mynumber', 0);
    String s = p.tryGetString('mystring', '');
    bool b = p.tryGetBool('mybool', false);

or

    int i = p.tryGetInt('mynumber') ?? 0;
    String s = p.tryGetString('mystring') ?? '';
    bool b = p.tryGetBool('mybool') ?? false;

**Comment by stuartmorgan** [comment]
If you don't know the data type of your stored data (it's not clear to me what the scenario where that would happen is), you can use `get`.

If in your particular case you are doing this so often that you would find a wrapper useful, you could certainly write your own using the existing method; this isn't something that we would add as it would add complexity to the API and make it easy to hide actual bugs.
