### ISSUE TITLE
Could not load dynamic service on iPhone

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4226]
Log output from iPhone:

```
May 26 15:29:31 iPhone Runner[324] <Notice>: [ERROR:dynamic_service_definition.cc(39)] Could not open the service dylib.
May 26 15:29:31 iPhone Runner[324] <Notice>: [ERROR:FlutterDynamicServiceLoader.mm(61)] Could not load dynamic service for 'firebase::Firebase'
May 26 15:29:49 iPhone syslog_relay[133] <Notice>: syslog_relay read 51 total bytes: 
```

I have more logs if they are useful. Not sure where the cut-off is.

**Comment by sethladd** [comment]
cc @collinjackson is this a common enough error that we should look for? The app does boot up, and I can try to send a message, but after I tap the Send icon, nothing happens on the device.

**Comment by sethladd** [comment]
cc @chinmaygarde

**Comment by collinjackson** [comment]
I can repro this as well

**Comment by collinjackson** [comment]
Once I made a fat binary, I was getting an error 

```
mapped executable file has no team identifier in its signature: /private/var/containers/Bundle/Application/C10931CA-4815-4DBA-B061-08ED266A13A0/Runner.app/Frameworks/libFirebase.dylib
```

Chinmay said this is a known issue with third-party services on iOS devices so I'm assigning to him

**Comment by chinmaygarde** [comment]
The fix for this issue is to codesign the individual dylibs before application packaging using the following build phase. I am going to work on it after [fixing all variants](https://github.com/flutter/flutter/issues/4216) to account for the `flutter tool` initiated AOTC builds.

```
/usr/bin/codesign
  --force
  --sign ${EXPANDED_CODE_SIGN_IDENTITY}
  --preserve-metadata=identifier,entitlements
  --timestamp=none
  <path/to/dylib>
```

**Comment by chinmaygarde** [comment]
@collinjackson The code signing step should be done done now. Mojo SDK has been updated in the meantime though. So the pub packages will need to be updated.

**Comment by eseidelGoogle** [comment]
This is resolved now, correct?  @chinmaygarde

**Comment by chinmaygarde** [comment]
Yeah

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1026. Any further collaboration will be done there.
