### ISSUE TITLE
Linux plugin Makefiles should not reference unpack command

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#42271]
This was an experimental hack to unblock the initial tooling working. It does not not know how to handle AOT variants of the engine, and dependencies on it must be removed to support AOT builds.

Possibly this should call assemble or depend on some depfile written by the main Makefile?

**Comment by stuartmorgan** [comment]
I don't have it fully swapped in at the moment, but I think I was leaning toward having a populated Flutter cache (i.e., flutter/ephemeral, not the to-level cache) as a required parameter, with the app makefile passing that and enduring the correct ordering.

(Not necessarily the final approach still, but incremental improvement and consistent with Windows.)

**Comment by jonahwilliams** [comment]
Yeah that sounds like a reasonable approach as well. For context this came up because I accidentally broke the Linux testbed when doing some of the AOT wiring

**Comment by stuartmorgan** [comment]
This was fixed in https://github.com/google/flutter-desktop-embedding/pull/591
