### ISSUE TITLE
Linux desktop shell needs to pass --aot-shared-library-name in release/profile mode

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#42274]
Abandoned change to do so for linux is here: https://github.com/flutter/engine/pull/12796/files

This will allow the tool to provide AOT artifacts for Linux desktop builds.

**Comment by stuartmorgan** [comment]
This should be closed in favor of #50778, right?

**Comment by jonahwilliams** [comment]
Yes (to this and the other one). With that change we'll still need to make a small update in the shells, but it should be fairly different
