### ISSUE TITLE
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by flaviobritto** [flutter/flutter#42283]
```
 Flutter (Channel dev, v1.10.12, on Microsoft Windows [versÃ£o 10.0.18362.388], locale pt-BR)
    • Flutter version 1.10.12 at d:\src\flutter
    • Framework revision 0e605cc4dd (4 days ago), 2019-10-04 07:52:15 -0700
    • Engine revision 759d3dba25
    • Dart version 2.6.0 (build 2.6.0-dev.5.0 7a7dcd1ed9)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\samad\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.38.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!


```

**Comment by Natreve** [comment]
What is the exception that is thrown?

**Comment by flaviobritto** [comment]
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Natreve <notifications@github.com>
Enviado: Tuesday, October 8, 2019 10:07:49 PM
Para: flutter/flutter <flutter@noreply.github.com>
Cc: flaviobritto <samadhi_pessoal@outlook.com>; Author <author@noreply.github.com>
Assunto: Re: [flutter/flutter] throws an exception (#42283)


What is the exception that is thrown?

**Comment by flaviobritto** [comment]
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'

**Comment by jonahwilliams** [comment]
@flaviobritto this sounds like a TypeError in your code. Unless the stacktrace is coming from flutter line, which is unlikely.

**Comment by Natreve** [comment]
@flaviobritto it is HAS @jonahwilliams  say a TypeError in your code, you will have to share the code you've written in order for us to see why you encountered the error.

**Comment by flaviobritto** [comment]
Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Natreve <notifications@github.com>
Enviado: Wednesday, October 9, 2019 1:48:29 AM
Para: flutter/flutter <flutter@noreply.github.com>
Cc: flaviobritto <samadhi_pessoal@outlook.com>; Mention <mention@noreply.github.com>
Assunto: Re: [flutter/flutter] throws an exception (#42283)


@flaviobritto<https://github.com/flaviobritto> it is HAS @jonahwilliams<https://github.com/jonahwilliams> say a TypeError in your code, you will have to share the code you've written in order for us to see why you encountered the error.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
