### ISSUE TITLE
[macOS] Desktop shell needs devicelab testing

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#42281]
This should cover the same suite of smoke tests we currently run on iOS/Android. For starters this should at least include:

* [X] Compilation succeeds from the template without errors
* [x] https://github.com/flutter/flutter/pull/45264
* [x] https://github.com/flutter/flutter/pull/110606 platform channels work
* [x] https://github.com/flutter/flutter/pull/110606 basic driver interaction
* [ ] https://github.com/flutter/flutter/issues/109633

**Comment by godofredoc** [comment]
@jonahwilliams are these new tests or some of the current devicelab tests running on a different environment?

**Comment by jonahwilliams** [comment]
I would recommend taking the existing tests and benchmarks are running them on a macOS shell.

**Comment by godofredoc** [comment]
@jonahwilliams can we close this bug now that tests are running?

**Comment by jonahwilliams** [comment]
No, we need much more test coverage and benchmarks. This test won't catch regressions like https://github.com/flutter/flutter/issues/45258 for example

**Comment by godofredoc** [comment]
@stuartmorgan @gspencergoog should we close this bug?

**Comment by stuartmorgan** [comment]
@cbracken would know the current state, but I believe this is still valid. IIRC only the first two items in that list were covered last I had looked into it.

**Comment by cbracken** [comment]
That is correct; this still needs doing.

**Comment by cbracken** [comment]
Related: https://github.com/flutter/flutter/pull/45264
