### ISSUE TITLE
Thai Language, Backspace bug in TextField

### ISSUE THREAD

**Issue by phornsak-t** [flutter/flutter#42282]
- Thai Language, Backspace bug in TextField 
- iOS 13.1.2 
- No problem with Android

![1](https://user-images.githubusercontent.com/47691766/66450858-3d81a500-ea84-11e9-898c-0b46ff55da69.png)
![2](https://user-images.githubusercontent.com/47691766/66450863-3e1a3b80-ea84-11e9-9f6d-49dc5e99297c.png)

**Comment by phornsak-t** [comment]
Backspace bug, Thai Language

![1](https://user-images.githubusercontent.com/47691766/66450746-dc59d180-ea83-11e9-852b-ca1fe6fd4d80.png)
![2](https://user-images.githubusercontent.com/47691766/66450747-dc59d180-ea83-11e9-9963-5bdf92ab2c24.png)

**Comment by iapicca** [comment]
Hi @phornsak-t,
if I understand correctly 
you are experiencing issue with the behavior of textfield 
only on iOS, correct?
Could you please provide your `flutter doctor -v`,
thank you

**Comment by phornsak-t** [comment]
- Error on iOS 13.1.2
- No problem with Android

[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A583, locale
    en-US)
    • Flutter version 1.9.1+hotfix.4 at /Users/encom/Documents/Developer/flutter
    • Framework revision cc949a8e8b (12 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/encom/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.3

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • iPhone 11 • 396255B9-0496-49FC-AB08-031CF693673C • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

**Comment by iapicca** [comment]
Thank you @phornsak-t

**Comment by HelloCore** [comment]
Could you try using channel `master` to see if the issue still exists?
You can change the channel by using command.
```
flutter channel master
flutter upgrade
```
https://github.com/flutter/engine/pull/11807

**Comment by phornsak-t** [comment]
Thank You, Flutter Team.
