### ISSUE TITLE
simple_animation_perf_iphonexs gpu_percentage regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#42296]
simple_animation_perf_iphonexs gpu_percentage regressed (~2x) as of https://github.com/flutter/flutter/pull/42200.

**Comment by Hixie** [comment]
cc @cbracken

**Comment by liyuqian** [comment]
Thanks @LongCatIsLooong for investigating this issue! It seems that the number has gone back to normal by itself when we unplug and replug the iPhone Xs. Maybe there's something strange going on with the OS that we don't quite understand.

**Comment by chinmaygarde** [comment]
@liyuqian Can you file an issue that says this stuff is flaky?

**Comment by liyuqian** [comment]
Filed https://github.com/flutter/flutter/issues/42374
