### ISSUE TITLE
Considering an expectation-setting message when running `flutter logs`

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4230]
Running `flutter logs` seems to only show log statements that come directly from flutter. It's not clear what expectations I should have about that command. Is it showing me everything? What did it whitelist? Blacklist? How do I see everything?

I've run into a few occasions where `flutter logs` returned nothing, but platform-specific logs showed me actionable crashes. I now don't know when I should use `flutter logs`. Is it just for application debugging?

One strawman is to print something at the top of the output of `flutter logs`, like: "Showing logs from only the Flutter application code. To see all the logs from the device, use flutter logs --verbose"

**Comment by sethladd** [comment]
cc @devoncarew thoughts?

**Comment by devoncarew** [comment]
If you're referring to https://github.com/flutter/flutter/issues/4225, I think we should be printing messages that are useful to the user for that application run. So that would include a native crash at app start, messages logged from the engine, flutter lib, and user code. Some of the info can be hard to get, and hard to get w/o getting a lot of other low signal-to-noise log data.

> One strawman is to print something at the top of the output of

Our app startup is verbose enough :)

**Comment by sethladd** [comment]
How about we start by clarifying what `flutter logs --help` says?

Right now, we see:

```
~/tmp/firechat-flutter[master*] $ flutter logs --help
Show log output for running Flutter apps.
```

Which is a bit vague. What does "log output" mean?

How about this:

```
~/tmp/firechat-flutter[master*] $ flutter logs --help
Show log output from the Flutter app itself. Use -v to see all log output from the Flutter process.
```

**Comment by Hixie** [comment]
I mean, we should make `flutter logs` show all output from the Flutter process.

**Comment by Hixie** [comment]
e.g. see #6756.

I'm going to close this because I think people's expectations today are correct, the tool is just not correctly fulfilling those expectations.
