### ISSUE TITLE
No devices found with name or id matching 'web'

### ISSUE THREAD

**Issue by kendji** [flutter/flutter#42308]
Web death that occurs in various channels.

"No devices found with name or id matching 'web'"

It occurred 
- [√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.116], locale ja-JP)
- [√] Flutter (Channel master, v1.10.6-pre.33, on Microsoft Windows [Version 10.0.18362.116], locale ja-JP)
- [√] Flutter (Channel dev, v1.10.14, on Microsoft Windows [Version 10.0.18362.116], locale ja-JP)

A "flutter build web --release" command is alright to deploy on a dev channel.
I didn't try to deploy(create) other channels.

The IDE is below.
![image](https://user-images.githubusercontent.com/5791736/66457700-f1e2f180-eaab-11e9-9bac-92f4dd6b8bf4.png)

**Comment by iapicca** [comment]
Hi @kendji 
can you please describe the issue in detail.
Also could you provide your `flutter doctor -v`
thank you

**Comment by kendji** [comment]
ok.
I'll show you the result right away.

**Comment by kendji** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.10.14, on Microsoft Windows [Version 10.0.18362.116], locale ja-JP)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2018.2)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] VS Code, 64-bit edition (version 1.38.1)
[√] Connected device (2 available)

• No issues found!

Actually, I updated the flutter plug-in for Androidstudio.
Then, “Server (web)” was changed to “Headless Server (web)” and it became possible to debug.
It seems that was the case.
Please let everyone know.
thank you.
