### ISSUE TITLE
Add visibility options on the hero transition

### ISSUE THREAD

**Issue by liuyingshan** [flutter/flutter#42300]
## Use case
If you transition for route 1 to route 2, the hero in route 1 is always hidden both during and after the transition.
![62250219-344bcc00-b3a1-11e9-916b-4f1d13b7815a](https://user-images.githubusercontent.com/9331948/66450231-52613700-ea8a-11e9-85d5-7e1e5c676b06.gif)

## Proposal
Add visibility options to allow the hero to be hidden/visible both during and after the transition.

## Related Pull Requests
https://github.com/flutter/flutter/pull/37341

**Comment by iapicca** [comment]
Hi @liuyingshan 
I see the issue you referenced to is still open.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
