### ISSUE TITLE
idevice_id cannot run on catalina

### ISSUE THREAD

**Issue by AndrewBreyen** [flutter/flutter#42302]
## Steps to Reproduce

Run flutter doctor on macOS Catalina. I get the screenshot attatched.

## Logs
[flutter_02.log](https://github.com/flutter/flutter/files/3705522/flutter_02.log)
[foo.zip](https://github.com/flutter/flutter/files/3705527/foo.zip)

```
Andrews-MacBook-Pro:Downloads abreyen$ flutter doctor -v
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
 
Oops; flutter has exited unexpectedly.
Crash report written to /Users/abreyen/Downloads/flutter_05.log;
please let us know at https://github.com/flutter/flutter/issues.

```
<img width="488" alt="Screen Shot 2019-10-08 at 10 54 11 PM" src="https://user-images.githubusercontent.com/7895581/66450545-9159a300-ea1e-11e9-8976-acbc5524ffb7.png">

**Comment by wangpengwen** [comment]
When you're developing in **_Catalina_**, you can fix it by
**`sudo xattr -d com.apple.quarantine /PATH_TO_YOUR_FLUTTER_HOME/bin/cache/artifacts/libimobiledevice/idevice_id`**

`sudo xattr -d com.apple.quarantine /PATH_TO_YOUR_FLUTTER_HOME/bin/cache/artifacts/libimobiledevice/ideviceinfo`

`sudo xattr -d com.apple.quarantine /PATH_TO_YOUR_FLUTTER_HOME/bin/cache/artifacts/usbmuxd/iproxy
`

... (if there's more to come)

**Comment by iapicca** [comment]
Hi @AndrewBreyen  
is the proposed resolution working for you?

**Comment by AndrewBreyen** [comment]
I still get 
`xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Doctor summary (to see all details, run flutter doctor -v):
 
Oops; flutter has exited unexpectedly.
Crash report written to /Users/abreyen/flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.`

[flutter_03.log](https://github.com/flutter/flutter/files/3708351/flutter_03.log)

**Comment by jonahwilliams** [comment]
cc @christopherfujino

**Comment by AndrewBreyen** [comment]
Update: maybe I should read the instructions: I installed xcrun with `xcode-select --install` and was able to run `flutter doctor` successfully.

**Comment by krozett** [comment]
Adding to https://github.com/flutter/flutter/issues/42302#issuecomment-539852516:
I also had to run this command on `bin/cache/artifacts/libimobiledevice/idevicesyslog` when running on a real iOS device.

**Comment by winwisely99** [comment]
@christopherfujino  Is there a specific issue i should watch for this. I need to be on master due to working on Flutter Desktop.

**Comment by christopherfujino** [comment]
@winwisely99 I just created https://github.com/flutter/flutter/issues/44372. Note, that the libimobiledevice binaries should actually be signed and notarized, as those are not build/versioned as part of the engine, however, the Dart SDK and engine binaries are not guaranteed to be signed/notarized on the framework master channel.

**Comment by macrisguncay** [comment]
what happens if I hit on the move to trash.? how I can restore it. o generate other.

**Comment by remoteportal** [comment]
> When you're developing on **_Catalina_**, you can fix it by
> **`sudo xattr -d com.apple.quarantine /PATH_TO_YOUR_FLUTTER_HOME/bin/cache/artifacts/libimobiledevice/idevice_id`**
> 
> `sudo xattr -d com.apple.quarantine /PATH_TO_YOUR_FLUTTER_HOME/bin/cache/artifacts/libimobiledevice/ideviceinfo`
> 
> `sudo xattr -d com.apple.quarantine /PATH_TO_YOUR_FLUTTER_HOME/bin/cache/artifacts/usbmuxd/iproxy `
> 
> ... (if there's more to come)

Doesn't work.  On Catalina I get:
No such xattr: com.apple.quarantine

**Comment by olivier-manomano** [comment]
Once you got the error message, go to System Preferences -> Security & Privacy -> General, and allow "idevice_id". Run `flutter doctor` again, you should now have the option to open idevice_id anyway. At least it worked for me.

**Comment by duzenko** [comment]
Why do we need to meddle with xattr? This needs to be fixed on the flutter side, not ours.

**Comment by beyta** [comment]
> When you're developing on **_Catalina_**, you can fix it by
> **`sudo xattr -d com.apple.quarantine /PATH_TO_YOUR_FLUTTER_HOME/bin/cache/artifacts/libimobiledevice/idevice_id`**
> 
> `sudo xattr -d com.apple.quarantine /PATH_TO_YOUR_FLUTTER_HOME/bin/cache/artifacts/libimobiledevice/ideviceinfo`
> 
> `sudo xattr -d com.apple.quarantine /PATH_TO_YOUR_FLUTTER_HOME/bin/cache/artifacts/usbmuxd/iproxy `
> 
> ... (if there's more to come)

Hi.. it works... Thanks

**Comment by MakingHistoryAgain** [comment]
This website will help: https://medium.com/@alexandrosbaramilis/setting-up-flutter-on-macos-catalina-d023df8845ae

Briefly:
For "idevice_id" error:
sudo xattr -d com.apple.quarantine /Users/Your_User/Your_Dev_Folder/flutter/bin/cache/artifacts/libimobiledevice/idevice_id
For "ideviceinfo" error:
sudo xattr -d com.apple.quarantine /Users/Your_User/Your_Dev_Folder/flutter/bin/cache/artifacts/libimobiledevice/ideviceinfo
For "idevicesyslog" error:
sudo xattr -d com.apple.quarantine /Users/Your_User/Your_Dev_Folder/flutter/bin/cache/artifacts/libimobiledevice/idevicesyslog
For "iproxy" error:
sudo xattr -d com.apple.quarantine /Users/Your_User/Your_Dev_Folder/flutter/bin/cache/artifacts/usbmuxd/iproxy

**Comment by richburdon** [comment]
After 15 years of pain swears will NEVER use Google tools again because they NEVER "just work".

Tries Flutter...

"Getting started" doesn't work. Fails before even getting started.

AND YOU'RE CLOSING THE ISSUE BY POINTING DEVS -- ON THE WORLD'S MOST POPULAR DEV PLATFORM -- TO A THIRD PARTY MEDIUM POST THAT REQUIRES OBSCURE SUDO-LEVEL OS CHANGES?

**Comment by YogeshSinghNegi** [comment]
Hi All,

I have just started to work with Flutter. I am using Catalina MacOS and I too faced similar error saying - **_“idevice_id” cannot be opened because the developer cannot be verified.`_**

My solution is just going to the **"System Preferences"** and under **"Security & Privacy"** you will find something needs your permission to allow to run. As Flutter is not downloaded from a trusted source which is App Store it always will be requiring your permission to run the app.

Please give this a try and let me know if you have a better solution.

Happy Coding!!!

**Comment by niglz** [comment]
> Hi All,
> 
> I have just started to work with Flutter. I am using Catalina MacOS and I too faced similar error saying - **_“idevice_id” cannot be opened because the developer cannot be verified.`_**
> 
> My solution is just going to the **"System Preferences"** and under **"Security & Privacy"** you will find something needs your permission to allow to run. As Flutter is not downloaded from a trusted source which is App Store it always will be requiring your permission to run the app.
> 
> Please give this a try and let me know if you have a better solution.
> 
> Happy Coding!!!


It does't show the an option to allow idevice_id in my settings. It should be in the section "General" right?

**Comment by DevPianist** [comment]
> Once you got the error message, go to System Preferences -> Security & Privacy -> General, and allow "idevice_id". Run `flutter doctor` again, you should now have the option to open idevice_id anyway. At least it worked for me.

Hi, it works!! :)

**Comment by YogeshSinghNegi** [comment]
> > Hi All,
> > I have just started to work with Flutter. I am using Catalina MacOS and I too faced similar error saying - **_“idevice_id” cannot be opened because the developer cannot be verified.`_**
> > My solution is just going to the **"System Preferences"** and under **"Security & Privacy"** you will find something needs your permission to allow to run. As Flutter is not downloaded from a trusted source which is App Store it always will be requiring your permission to run the app.
> > Please give this a try and let me know if you have a better solution.
> > Happy Coding!!!
> 
> It does't show the an option to allow idevice_id in my settings. It should be in the section "General" right?

Try deleting the Flutter folder and download again from the flutter.io website and unzip it.

**Comment by knight2010** [comment]
> > When you're developing on **_Catalina_**, you can fix it by
> > **`sudo xattr -d com.apple.quarantine /PATH_TO_YOUR_FLUTTER_HOME/bin/cache/artifacts/libimobiledevice/idevice_id`**
> > `sudo xattr -d com.apple.quarantine /PATH_TO_YOUR_FLUTTER_HOME/bin/cache/artifacts/libimobiledevice/ideviceinfo`
> > `sudo xattr -d com.apple.quarantine /PATH_TO_YOUR_FLUTTER_HOME/bin/cache/artifacts/usbmuxd/iproxy `
> > ... (if there's more to come)
> 
> Doesn't work. On Catalina I get:
> No such xattr: com.apple.quarantine
> 
> When is this going to be fixed? How can anyone develop on Mac with a real device?

Useful

**Comment by daoibrahim** [comment]
Works like a charm. Thanks
