### ISSUE TITLE
url_launcher not launching WhatsApp on iOS

### ISSUE THREAD

**Issue by abhinavc** [flutter/flutter#42311]
Hi,
I'm using `url_launcher 5.1.3` in my Flutter app. The following code works fine on Android - but not on iOS

```
    String url = "whatsapp://send?text=< .... >";
    if (await canLaunch(whatsApp)) launch(whatsApp) 
```

For iOS, I made the following changes
    - `(Info.plist)` Added `whatsapp` to `LSApplicationQueriesSchemes`
    - Changed `launch` call to `launch(whatsApp, forceSafariVC: false)` 

However, it doesn't seem to work. Don't know what else to try. Can someone please help / give new ideas to try out.

Thanks 
Abhinav.

**Comment by iapicca** [comment]
Hi @abhinavc 
can you please provide your `flutter doctor -v`?
Also if you could post a self contained app on github
It would help to better address the issue,
thank you

**Comment by abhinavc** [comment]
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale en-IN)
    • Flutter version 1.9.1+hotfix.4 at /Users/abhinav/lib/flutter
    • Framework revision cc949a8e8b (11 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/abhinav/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Abhinav Chaturvedi’s iPhone • fff2d1f407df444032732921b0926630249f1d29 • ios • iOS 13.1.2

• No issues found!

```

**Comment by abhinavc** [comment]
I'll need some time to make a small test-app. Had made and tested a full app on Android. 
Encountered this issue when compiling and testing the same on iOS

**Comment by iapicca** [comment]
Thank you for your effort @abhinavc

**Comment by abhinavc** [comment]
Hi @iapicca,

For now, it looks like it's my bad. The unit test case I wrote worked fine on iOS. 

I think the problem is with the deep-link I send with the WhatsApp message.
Configured and built it for Android - but not for iOS. That could be the problem. 

Let me fix that issue and then re-try. Will keep the unit test case around - just in case. 

Thanks 
Abhinav.

**Comment by iapicca** [comment]
@abhinavc given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by andersonmendesdev** [comment]
Unfortunately this problem still exists, on android it opens whatsapp with text, but on ios nothing happens, I have no physical device iphone to test and see if any errors appear on the console, but in production I do not have the expected result, already does I've been having this problem for a long time. If you could test, I'm leaving a repository link with the app created next to a whats url to open on the device.

I had already mentioned this error in another issue but no one answered.
[https://github.com/flutter/flutter/issues/28885](url)

url_launcher: ^5.2.7

Repository with example: [https://github.com/andersonmendesdev/sendwhats](url)

Info.plist

    <key>LSApplicationQueriesSchemes</key>
    <array>
        <string>youtube</string>
        <string>whatsapp</string>
        <string>instagram</string>
        <string>fb</string>
        <string>tel</string>
            <string>mailto</string>
    </array>

Flutter doctor -v

    [✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale pt-BR)
        • Flutter version 1.9.1+hotfix.6 at /Users/gendo/development/flutter
        • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
        • Engine revision b863200c37
        • Dart version 2.5.0

    
    [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
        • Android SDK at /Users/gendo/Library/Android/sdk
        • Android NDK location not configured (optional; useful for native profiling support)
        • Platform android-29, build-tools 29.0.2
        • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
        • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
        • All Android licenses accepted.

    [✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
        • Xcode at /Applications/Xcode.app/Contents/Developer
        • Xcode 11.2.1, Build version 11B53
        • CocoaPods version 1.8.4

    [✓] Android Studio (version 3.5)
        • Android Studio at /Applications/Android Studio.app/Contents
        • Flutter plugin version 41.1.2
        • Dart plugin version 191.8593
        • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

    [✓] VS Code (version 1.40.2)
        • VS Code at /Applications/Visual Studio Code.app/Contents
        • Flutter extension version 3.6.0

    [✓] Connected device (1 available)
        • D6543 • BY900EJXHY • android-arm • Android 6.0.1 (API 23)

    • No issues found!

**Comment by chhota89** [comment]
After adding the LSApplicationCategoryType it's working for me

```
<key>LSApplicationCategoryType</key>
 <string></string>
<key>LSApplicationQueriesSchemes</key>
<array>
        <string>whatsapp</string>
</array>
```

Add this inside the info.plist file

**Comment by davicg** [comment]
> After adding the LSApplicationCategoryType it's working for me
> 
> ```
> <key>LSApplicationCategoryType</key>
>  <string></string>
> <key>LSApplicationQueriesSchemes</key>
> <array>
>         <string>whatsapp</string>
> </array>
> ```
> 
> Add this inside the info.plist file

This fixed the problem here! Thanks!

**Comment by lucas-sesti** [comment]
> > After adding the LSApplicationCategoryType it's working for me
> > ```
> > <key>LSApplicationCategoryType</key>
> >  <string></string>
> > <key>LSApplicationQueriesSchemes</key>
> > <array>
> >         <string>whatsapp</string>
> > </array>
> > ```
> > 
> > 
> > Add this inside the info.plist file
> 
> This fixed the problem here! Thanks!

Yeahh!! This fixed my problem too! Thanks a lot !!

**Comment by iapicca** [comment]
Hi @abhinavc 
I see you are using an old version of flutter
please run `flutter upgrade --force`
if the issue persists please open a dedicated issue
providing your updated`flutter doctor -v` , 
your `flutter run --verbose`, 
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you
