### ISSUE TITLE
Flutter app with Apple Watch app

### ISSUE THREAD

**Issue by keke-dandois** [flutter/flutter#42317]
I created a flutter app with an accompanying apple watch app. The watch app is not written in flutter and is added as an extra target in the Runner project.
When I run both the app and the apple watch app from xcode they work fine.

When I try to run the app from Intellij I get following error:
error: unable to resolve product type 'com.apple.product-type.watchkit2-extension' for platform 'iphonesimulator'.

Steps to reproduce:
1. create flutter app
2. add apple watch target through xcode.

**Comment by iapicca** [comment]
Hi @keke-dandois 
I see there's an [issue](https://github.com/flutter/flutter/issues/20392) addressing the case you described.
Please follow up on this [issue](https://github.com/flutter/flutter/issues/16092),
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by keke-dandois** [comment]
@iapicca the issue seems to be closed and the other issue doesn't seem to address this exact problem.
