### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY

### ISSUE THREAD

**Issue by jayangaL** [flutter/flutter#42312]
## Steps to Reproduce

1. I/flutter (14743): FormField<List<dynamic>>-[LabeledGlobalKey<FormFieldState<dynamic>>#21c98](dependencies:
I/flutter (14743): [_FormScope], state: FormFieldState<List<dynamic>>#76a29):
I/flutter (14743): 'package:flutter/src/services/text_input.dart': Failed assertion: line 385 pos 15: 'inputType !=
I/flutter (14743): null': is not true.
I/flutter (14743): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (14743): more information in this error message to help you determine and fix the underlying cause.
I/flutter (14743): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (14743):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (14743): User-created ancestor of the error-causing widget was:
I/flutter (14743):   SizedBox

2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by iapicca** [comment]
Hi @jayangaL 
can you please describe the issue in detail
and provide your `flutter doctor -v`
thank you

**Comment by jayangaL** [comment]
This issue happens when i try to run flutter form builder example on my external device that i have connected. As you can see issue is on debug console(other packages runs fine it's just the form builder package)

And here is flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.9.1+hotfix.4 at C:\src\flutter
    • Framework revision cc949a8e8b (11 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\User\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\User\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[!] Connected device
    • Device 4203fa1fd6e49100 is offline.

! Doctor found issues in 1 category.

**Comment by iapicca** [comment]
@jayangaL if you could also post 
a self contained app on github
it would help to reproduce the issue,
thank you

**Comment by jayangaL** [comment]
I guess i don't want to go that far to solve simple issue.
thank you.

**Comment by iapicca** [comment]
@jayangaL 
I'd be glad to help,
but without any code or steps to reproduce issue
there isn't just enough information to tackle the problem.

I an error see in your initial post that **might**  be due to the code itself
```
I/flutter (14743): FormField<List>-[LabeledGlobalKey<FormFieldState>#21c98](dependencies:
I/flutter (14743): [_FormScope], state: FormFieldState<List>#76a29):
I/flutter (14743): 'package:flutter/src/services/text_input.dart': Failed assertion: line 385 pos 15: 'inputType !=
I/flutter (14743): null': is not true.
```
You are also mentioning a 3rd party package in your following answer
(form builder package?), that might be the source of the issue.

To proceed we need more details.
Thank you

**Comment by jayangaL** [comment]
I solve it by getting an earlier version of 3rd party library that i am using. 
thank you
