### ISSUE TITLE
[Firebase AdMob] | Example app does not run | PlatformException(load_failed_ad, cannot reload a failed ad, id=555755095, null)

### ISSUE THREAD

**Issue by pinkeshAubergine** [flutter/flutter#42316]
The main problem is that even Test ads are not showing up with 
`    FirebaseAdMob.instance.initialize(appId: FirebaseAdMob.testAppId);`
` adUnitId: BannerAd.testAdUnitId,`

## Steps to Reproduce

1. Clone the example app.
2. Sample APP ID added like this 
`   
 <meta-data
      android:name="com.google.android.gms.ads.APPLICATION_ID"
      android:value="ca-app-pub-3940256099942544~3347511713"/>`

3. Added test device ID like this
`const String testDevice = 'B5BD02099B12769D58DBD05B64D1DFAF';`

I am running on a Physical device. Below is information for that

**Target Platform:** Android (I have not tested in iOS yet)
**Target OS version/browser:** Android 9
**Devices:** Xiomi MI A1

## Logs

**This logs appears when App is loaded.**

![Screenshot 2019-10-09 at 2 25 17 PM](https://user-images.githubusercontent.com/56068831/66466619-a4ad5280-eaa0-11e9-9ec5-ea289a791af5.png)

14:17:39.786 35 info flutter.tools E/chromium( 9945): [ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -107

14:17:40.076 37 info flutter.tools W/Ads     ( 9945): Not retrying to fetch app settings

14:17:43.529 38 info flutter.tools V/FA      ( 9945): Inactivity, disconnecting from the service

14:17:50.219 40 info flutter.tools I/Ads     ( 9945): Ad failed to load : 0

14:17:50.245 41 info flutter.tools I/flutter ( 9945): BannerAd event MobileAdEvent.failedToLoad

**And this appears on click of show banner**

![Screenshot 2019-10-09 at 2 26 04 PM](https://user-images.githubusercontent.com/56068831/66466709-c6a6d500-eaa0-11e9-8e17-3fd91936cabc.png)

E/flutter ( 9945): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(load_failed_ad, cannot reload a failed ad, id=602615785, null)
E/flutter ( 9945): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 9945): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter ( 9945): <asynchronous suspension>
E/flutter ( 9945): #2      _invokeBooleanMethod (package:firebase_admob/firebase_admob.dart:523:61)
E/flutter ( 9945): <asynchronous suspension>
E/flutter ( 9945): #3      BannerAd.load (package:firebase_admob/firebase_admob.dart:278:12)
E/flutter ( 9945): #4      _MyAppState.build.<anonymous closure> (package:firebase_admob_example/main.dart:94:27)
E/flutter ( 9945): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
E/flutter ( 9945): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
E/flutter ( 9945): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 9945): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter ( 9945): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter ( 9945): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter ( 9945): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter ( 9945): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter ( 9945): #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 9945): #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 9945): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 9945): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 9945): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 9945): #18     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 9945): #19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 9945): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 9945): #21     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter ( 9945): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)

### Flutter doctor

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.1 18B75, locale en-GB)
    • Flutter version 1.9.1+hotfix.4 at /Users/PinkeshDarji/Data/Development/flutter
    • Framework revision cc949a8e8b (11 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/PinkeshDarji/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode10.1.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.5

[!] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.33.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Mi A1 • 0096804d0804 • android-arm64 • Android 9 (API 28)

```

**Comment by iapicca** [comment]
> ## Steps to Reproduce
> 1. Clone the example app.

Hi @pinkeshAubergine 
can you please provide the link to the example app to clone,
it would help to reproduce the issue,
thank you

**Comment by pinkeshAubergine** [comment]
From here https://github.com/FirebaseExtended/flutterfire/tree/master/packages
I am running this https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob

**Comment by kroikie** [comment]
@pinkeshAubergine

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1164. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by pinkeshAubergine** [comment]
Closing this issue. There was a problem at my end. Ads were not loading because my company's internet had restricted it. It started working as I switched to another internet connection with no restrictions.

**Comment by liuchaotclc** [comment]
I face the same problem with my Huawei phone.Whatever through 4G or wifi.But it run right on my iphone

**Comment by DeckyApp** [comment]
saya mengalami masalah yg sama seperti ini. bagaimana memperbaikinya ?
Exception has occurred. PlatformException (PlatformException(load_failed_ad, cannot reload a failed ad, id=212037702, null))

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by waqaraliu** [comment]
If any one still having trouble, then change the package name in your MainActivity file. because manifest and main activity should have same package names. like com.abc.admob
