### ISSUE TITLE
type '_InternalLinkedHashMap<String, String>' is not a subtype of type 'int' of 'index'

### ISSUE THREAD

**Issue by SALMONEMMANUEL** [flutter/flutter#42321]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by iapicca** [comment]
Hi @SALMONEMMANUEL
can you please describe the issue?
Also, to better address the issue, would be helpful
if you could provide your flutter doctor -v
and self contained app on github
or the steps to reproduce it.
Thank you

**Comment by janmoppel** [comment]
Hello @SALMONEMMANUEL !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

P.S. Could everyone who still experience the same problem please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
