### ISSUE TITLE
Flutter_google_map plugin issue

### ISSUE THREAD

**Issue by mahmooooud** [flutter/flutter#42326]
last version from flutter SDK have a problem in window with google map by using flutter_google_map plugin and it crash while open it

**Comment by iapicca** [comment]
Hi @mahmooooud 
can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by mahmooooud** [comment]
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.356], locale en-US)
    • Flutter version 1.2.1 at C:\flutter
    • Framework revision 8661d8aecd (8 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\mahmo\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2
    • Flutter plugin version 31.3.2
    • Dart plugin version 182.3569.4

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\mahmo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • Redmi Note 7 • 192.168.0.16:5555 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by mahmooooud** [comment]
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;
import 'package:anamehani2/UI/Loader.dart';
import 'package:anamehani2/UI/WorkInfoStep.dart';
import 'package:anamehani2/functions/Translations.dart';
import 'package:flutter/rendering.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:geocoder/geocoder.dart';
import 'package:geocoder/model.dart';
import 'dart:async';
import 'package:geolocator/geolocator.dart';
import 'package:flutter/material.dart';
import 'package:image_picker_saver/image_picker_saver.dart';
import 'package:location/location.dart';


class UserAddress extends StatefulWidget {
  double currentLat,currentLong;
  UserAddress(this.currentLat,this.currentLong);
  @override
  _UserAddressState createState() => _UserAddressState();
}

class _UserAddressState extends State<UserAddress> {
  var filePath = '';
  File _image;
  static GlobalKey screen = new GlobalKey();
  var currentLocation = LocationData;

  var location = new Location();

  void test()async{
    location.onLocationChanged().listen((LocationData currentLocation) {
      print("Current Lag  ${currentLocation.latitude}");
      print("Current long ${currentLocation.longitude}");
    });
  }
  double latHuss;
  double longHuss;
  String address = ' ';
  Geolocator geolocator = Geolocator();
  Completer<GoogleMapController> _controller = Completer();
  double latC = 30.0598508;
  double longC = 31.3537609;

  static double lat = 31.0598508;
  static double long = 32.3537609;
  Position userLocation;
//  CameraPosition _kGooglePlex = CameraPosition (
//    target: LatLng(widget.currentLat, widget.currentLong),
//
//    zoom: 14.4746,
//  );
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    if (!mounted) return;

    setState(() {
      latHuss = widget.currentLat;
      longHuss = widget.currentLong;
    });
    location.onLocationChanged().listen((LocationData currentLocation) {

        lat = currentLocation.latitude;
        long = currentLocation.longitude;
        print('laaaaat ${lat}');
        print('looooong ${long}');

      print("Current Lag  ${currentLocation.latitude}");
      print("Current long ${currentLocation.longitude}");

    });
    print("jfffosafifasji ${widget.currentLat}");
    print("jfffosafifasji ${widget.currentLong}");

    getLocation(widget.currentLat,widget.currentLong).then((res){
      setState(() {
        address = res[0].addressLine;
        print('aaaaaaaaaaaaaaaaa   ${address}');
        data.add (res[0].addressLine);
        data.add(lat.toString());
        data.add(long.toString());
      });
//
    });


  }

  Future<void> _goToNewYork() async {

    GoogleMapController controller = await _controller.future;
    print("${latHuss}wsffff");
    print("${longHuss}wsffff");
    controller.animateCamera(CameraUpdate.newLatLngZoom(LatLng(latHuss,longHuss ), 16.8));


  }
  var loato ;
  var longo ;
  bool cameraMoveStop = false;
  bool loader = false;
  List<String> data = new List();
  CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(lat,long),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {

    return Scaffold(

        body: Stack(
          children: <Widget>[
            Container(
                color: Colors.white,
                child: GoogleMap(
                  myLocationButtonEnabled: true,
//                  myLocationEnabled: true,
//                  compassEnabled: true,
//              onCameraMove: (val){
//                print(val.target.latitude);
//              },

                  mapType: MapType.normal,
                  initialCameraPosition: CameraPosition(target: LatLng(widget.currentLat, widget.currentLong),zoom: 16.8,),
                  onMapCreated: (GoogleMapController controller) {
                    _controller.complete(controller);
                  },
                  onCameraIdle: (){
                    print('idle');
                    cameraMoveStop = true;
                    print(cameraMoveStop);
                    print('loooootooo  ${loato}');
                    print('longoooo ${longo}');


                      loato = widget.currentLat;
                      longo = widget.currentLong;


                    getLocation(loato,longo).then((res){

                          print('resss ${res[0].addressLine}    ${res[1].addressLine}');
                        address = res[0].addressLine;
                        data.add (res[0].addressLine);
                        data.add(lat.toString());
                        data.add(long.toString());


                    });
                  },
                  onCameraMoveStarted: (){
                    print('start');
//                    cameraMoveStop = false;
                    print(cameraMoveStop);

                  },
                  onCameraMove: (postion){
                    print('ssss   ${postion.target}');
                    if(cameraMoveStop) {
                      print('stooped at ${postion.target}');

                        setState(() {
                          loato = postion.target.latitude;
                          longo = postion.target.longitude;
                          widget.currentLat = postion.target.latitude;
                          widget.currentLong = postion.target.longitude;
                        });


                    }
                  },

                  polylines: Set <Polyline>.of(
                    <Polyline>[

                    ]
                  ),
                  markers: Set<Marker>.of(
                    <Marker>[
                      Marker(
                          draggable: true,
                          markerId: MarkerId("1"),
                          position: LatLng(widget.currentLat, widget.currentLong),
                          icon: BitmapDescriptor.fromAsset("image/mmm_33.png"),
                          infoWindow: const InfoWindow(
                            title: "Ana",
                          )
                      )
                    ],
                  ),

                ),
              ),
      Positioned(
        bottom: 0.0,
        child: Container(
          decoration: BoxDecoration(
            color: Color.fromRGBO(242, 242, 246, 1.0),
            boxShadow: [BoxShadow(
              color: Colors.grey,
              blurRadius: 5.0,
            ),]
          ),

          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height/4,
          child: Column(
            children: <Widget>[
              Container(
                margin:Translations.of(context).currentLanguage.toString().contains('ar') ?  EdgeInsets.only(right: 15.0,top: 10.0): EdgeInsets.only(left: 15.0,top: 10.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[

                    Container(
                           child: Text('${Translations.of(context).text('Address')}',style: TextStyle(color: Color.fromRGBO(0, 54, 107, 1.0),fontWeight: FontWeight.bold,fontSize: 15.0),),
                        ),
                    Container(
                      margin: EdgeInsets.only(left: 5.0,right: 5.0),
                      width: MediaQuery.of(context).size.width/1.4,

                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          Container(
//                                margin: EdgeInsets.only(top: 10.0,left: 15.0,right: 15.0),
                                 child:Text(address.length > 65 ? '${address.substring(0,65)}....': '${address}' ,style: TextStyle(color: Colors.black,fontWeight: FontWeight.bold,fontSize: 15.0),),
                              ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
//                Align(
//                  alignment: Alignment.bottomCenter,
//                  heightFactor: 1.9,
//                  child: new Container(
//                    width: MediaQuery.of(context).size.width,
//                    margin: EdgeInsets.only(top: 0,right: 15.0,left: 15),
//                    decoration: new BoxDecoration(
//                        color: Color.fromRGBO(0, 54, 107, 1.0), //new Color.fromRGBO(255, 0, 0, 0.0),
//                        borderRadius: new BorderRadius.all(Radius.circular(10.0))
//                    ),
//                    alignment: Alignment.bottomCenter,
//                    child: Container(
//                      margin: EdgeInsets.only(left: 10.0,right: 10.0),
//                      width: MediaQuery.of(context).size.width,
//                      alignment: Alignment.bottomCenter,
//                      decoration: new BoxDecoration(
//                        //color: Colors.pink,
//                        //color: Color.fromRGBO(0, 54, 107, 1.0), //new Color.fromRGBO(255, 0, 0, 0.0),
//                          borderRadius: new BorderRadius.all(Radius.circular(10))
//                      ),
//                      child: new FlatButton(
////                    highlightColor: Color.fromRGBO(0, 54, 107, 1.0),
////                    splashColor: Color.fromRGBO(0, 54, 107, 1.0),
//                          onPressed: ()=> Navigator.pop(context, "${address}:${lat}:${long}") ,
//                          child: new Text(Translations.of(context).text("SaveAddress"),style: TextStyle(color: Colors.white,fontWeight: FontWeight.bold),)),
//                    ),
//                  ),
//                ),

            ],
          ),
        ),
      ),
      Positioned(
        bottom: 0.0,
        left: 10.0,
        right: 10.0,
        child: new Container(
          width: MediaQuery.of(context).size.width,
          margin: EdgeInsets.only(top: 0,right: 15.0,left: 15,bottom: 10.0),
          decoration: new BoxDecoration(
              color: Color.fromRGBO(0, 54, 107, 1.0), //new Color.fromRGBO(255, 0, 0, 0.0),
              borderRadius: new BorderRadius.all(Radius.circular(10.0))
          ),
          alignment: Alignment.bottomCenter,
          child: Container(
            margin: EdgeInsets.only(left: 10.0,right: 10.0),
            width: MediaQuery.of(context).size.width,
            alignment: Alignment.bottomCenter,
            decoration: new BoxDecoration(
              //color: Colors.pink,
              //color: Color.fromRGBO(0, 54, 107, 1.0), //new Color.fromRGBO(255, 0, 0, 0.0),
                borderRadius: new BorderRadius.all(Radius.circular(10))
            ),
            child: new FlatButton(
//                    highlightColor: Color.fromRGBO(0, 54, 107, 1.0),
//                    splashColor: Color.fromRGBO(0, 54, 107, 1.0),
                onPressed: ()=> Navigator.pop(context, "${address}:${lat}:${long}") ,
                child: new Text(Translations.of(context).text("SaveAddress"),style: TextStyle(color: Colors.white,fontWeight: FontWeight.bold),)),
          ),
        ),
      ),
      Positioned(
        bottom: MediaQuery.of(context).size.height/4 + 15,
        left: MediaQuery.of(context).size.width/1.18,
//        right: MediaQuery.of(context).size.width/1.28,

        child:
            Container(
              width: 40.0,
              decoration: BoxDecoration(borderRadius: BorderRadius.all(Radius.circular(20.0))),
              alignment: Alignment.topRight,
              child: RawMaterialButton(
                elevation: 40.0,
                splashColor: Color.fromRGBO(242, 242, 246, 1.0),
                highlightColor: Color.fromRGBO(242, 242, 246, 1.0),
                //shape: CircleBorder(),
                child: Container(
                  decoration: BoxDecoration(
//                    color: Colors.white,
                    boxShadow: [
                      BoxShadow(
                        color: Colors.grey.withOpacity(.3),
                        blurRadius: 4.0,
                        spreadRadius: 5.0
                      ),
                    ],
                    borderRadius: BorderRadius.all(Radius.circular(40.0))

                  ),
                  child: Image.asset('image/compass.png',fit: BoxFit.fill,),
                ),
                shape: CircleBorder(),
                onPressed: () { _goToNewYork();},
                //fillColor: Colors.blue,
              ),
            ),
      ),
          ],
        ),

//        floatingActionButton: new Column(
//          crossAxisAlignment: CrossAxisAlignment.end,
//          mainAxisAlignment: MainAxisAlignment.end,
//          children: <Widget>[
//            RawMaterialButton(
//              child: CircleAvatar(
//                child: Icon(Icons.save,size: 40.0,color: Colors.white),
//                radius: 30.0,
//                backgroundColor: Color.fromRGBO(0, 54, 107, 1.0),
//              ),
//              onPressed: ()=> Navigator.pop(context, "${address}:${lat}:${long}") ,
//            ),
////            SizedBox(height: 10.0,),
////            RawMaterialButton(
////              //shape: CircleBorder(),
////              child: CircleAvatar(
////                child: Icon(Icons.location_on,size: 40.0,color: Colors.white,),
////                radius: 30.0,
////                backgroundColor: Color.fromRGBO(0, 54, 107, 1.0),
////              ),
////              onPressed: () =>  _kLake,
////              //fillColor: Colors.blue,
////            ),
//
//          Container(
//            margin: EdgeInsets.only(left: 10.0,right: 10.0),
//            color: Colors.white,
//            width: MediaQuery.of(context).size.width,
//            height: 100.0,
//            alignment: Alignment.center,
//            child: Text('${address}',style: TextStyle(color: Colors.blue,fontWeight: FontWeight.bold,fontSize: 30.0),),
//          ),
//          ],
//        )

    );

  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(CameraPosition(target: LatLng(widget.currentLat, widget.currentLong),zoom: 16.8,)));
  }
  Future<List<Address>> getLocation(var lat,var long)  async {
    print('function  ${lat}  ${long}');
    final coordinates = new Coordinates(lat, long);
    var addresses = await Geocoder.local.findAddressesFromCoordinates(coordinates);
    var first = addresses.first;
    print("adddresss  ${first.featureName} : ${first.addressLine}");
    return addresses;
  }

//  Future<Position> _getLocation() async {
//    var currentLocation;
//    try {
//      currentLocation = await geolocator.getCurrentPosition(
//          desiredAccuracy: LocationAccuracy.best);
//    } catch (e) {
//      currentLocation = null;
//    }
//    return currentLocation;
//  }


}

**Comment by iapicca** [comment]
Thank you @mahmooooud 
did you run `flutter upgrade`?

**Comment by mahmooooud** [comment]
yes

**Comment by VladyslavBondarenko** [comment]
Hi @mahmooooud 
This issue seems to not be actionable, closing.
I hope it's fixed. But if you are experiencing it with the last versions of flutter and google_maps_flutter plugin, please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) together with `flutter run --verbose` and I'll reopen it.
Thank you
