### ISSUE TITLE
https://stackoverflow.com/questions/tagged/flutter?sort=frequent

### ISSUE THREAD

**Issue by SALMONEMMANUEL** [flutter/flutter#42322]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by iapicca** [comment]
Hi @SALMONEMMANUEL 
can you please describe the issue?
Also, to better address the issue, would be helpful
if you could provide your `flutter doctor -v`post 
and self contained app on github
or the steps to reproduce it.
Thank you

**Comment by stuartmorgan** [comment]
Closing since this appears to have been opened by mistake.
