### ISSUE TITLE
 FlutterDriver.screenShot() produces black image on Fuchsia

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#42337]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=37367. Conversation should occur there.

cc @zanderso

**Comment by kf6gpe** [comment]
cc @iskakaushik too.

**Comment by kf6gpe** [comment]
This is becoming increasingly important for Fuchsia; assigning the critical label so we can look for a volunteer to take it at this week's triage.

**Comment by zanderso** [comment]
If the vmservice/FlutterDriver connection is successfully set up, there probably isn't a driver/tooling issue here, but cc'ing @blasten just in case something comes up.

**Comment by Hixie** [comment]
Currently blocked behind higher-priority Fuchsia work.

**Comment by iskakaushik** [comment]
I took a brief look at this yesterday, this looks like a problem with the `rasterizer`. There is a simple repro for this once https://github.com/flutter/flutter/pull/44227 lands.

1. Run any Flutter app on Fuchsia and get the `observatory url` from the logs. Lets call the observatory port `TARGET_PORT`.
2. Pick an unused port on the host device as the `HOST_PORT` and run `fx ssh -L $HOST_PORT:localhost:$TARGET_PORT root@$(fx get-device-addr)`
3. Run `flutter screenshot --observatory-uri=http://127.0.0.1:$HOST_PORT/ --type=rasterizer -o /tmp/screenshot_dump.png`, you will see a completely transparent image in the `screenshot_dump.png` file.

@zanderso this looks like a real issue in the engine specific to the Fuchsia embedding.

**Comment by zanderso** [comment]
What failed without https://github.com/flutter/flutter/pull/44227? If the flutter tool has a Fuchisa SDK in the artifact cache (`flutter precache --fuchsia`), then `findTargetDevice()` should have been able to find the Fuchsia device.

**Comment by iskakaushik** [comment]
I did this without `flutter precache --fuchsia` during my first attempt. I just tried after precaching and it still gives me: `No supported devices connected.`. Not exactly sure what is going on.

**Comment by zanderso** [comment]
Removing the tool label since this was determined to be in the rasterizer.
