### ISSUE TITLE
Method for accessing screenshots from flutter driver tests on host

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#42338]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=37573. Conversation should occur there.

cc @zanderso and @iskakaushik

**Comment by zanderso** [comment]
It's unclear what the request is for here. Does screenshotting not work at all? Does it not work from `flutter driver`? Or is this an artifact of Fuchsia running the driver on the device alongside the app under test? The first two are actionable by Flutter, but the third is probably not.
