### ISSUE TITLE
Can't run app from Atom on OSX -- Could not find an option named 'checked'

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#4233]
## Steps to Reproduce

Deploy app from atom on Mac to an iOS device:

`flutter run --checked --debug-port=16240 --start-paused --device-id a1b07916f5d38432c3e4dde4a427b14a23ee16ab • flutter logs
app/ • checked mode • debug`

produces the error

`Could not find an option named "checked".`

## Flutter Doctor
  
[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/djshuckerow/.flutter
    • Framework revision 646b5350d1 (19 hours ago), engine revision 7fab0c350b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/djshuckerow/Library/Android/sdk
    • Platform android-N, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3, Build version 7D175

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2

**Comment by devoncarew** [comment]
@DaveShuckerow, can you check for plugin updates in atom? There should be a new version of the plugin, that will not try and send in `--checked` when launching flutter apps. After the update you'll want to re-start atom to make sure it applied cleanly.

**Comment by DaveShuckerow** [comment]
Updating the dartlang plugin resolved this issue.

**Comment by devoncarew** [comment]
Great! Closing...
