### ISSUE TITLE
Grab handles for ReorderableListView items

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#42330]
Demonstrate how to add "grab" handles to ReorderableListView items and custom widgets. 

The ["pick up and move"](https://material.io/design/interaction/gestures.html#types-of-gestures) section of the Material Design spec indicates that a long-press-drag-release gesture can be used to move items. ReorderableListView supports moving items within a list with that gesture.

Sometimes it's useful to include a visual affordance that shows that an item can be moved, and optionally highlights while the item is being moved.  Such an affordance is often referred to as a "grab handle". It would helpful if the documentation demonstrated how to do include a grab handle in each reorderable list view item. It might also be useful to provide a utility grab handle widget.

**Comment by darrenaustin** [comment]
Hey folks, we are ramping up a design to try to address this and other issues with `ReorderableListView`. We are tracking it with #66080 and in a [design doc](https://docs.google.com/document/d/1JzNtMQ-jnPnSHEBoi6IO0x2qMMylwhvRslEDcmqiwSs/edit#heading=h.pub7jnop54q0). Feedback welcome.

**Comment by justinmc** [comment]
It seems to me like this can be closed as completed. I see a duplicate issue (https://github.com/flutter/flutter/issues/63709) that was completed, and the first example [in the docs](https://api.flutter.dev/flutter/material/ReorderableListView-class.html) shows something that looks like grab handles to me.

Feel free to reopen if I'm wrong.
