### ISSUE TITLE
Android NDK check misconfigured

### ISSUE THREAD

**Issue by rashedmyt** [flutter/flutter#42341]
From what I can understand by looking at the code [here](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_sdk.dart#L134), we are checking for `ndk-bundle`, but the NDK is present in `ndk/<version>` directory. Hence when we run `flutter doctor -v`, we are always getting `Android NDK location not configured (optional; useful for native profiling support)`.

**Comment by rashedmyt** [comment]
Digging more into the code, It is mentioned [here](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_sdk.dart#L149) that only linux and macOS are supported. So I guess it's just a windows thing.

**Comment by rashedmyt** [comment]
Flutter fails to locate NDK on macOS too due to missing gcc binary in the specified folder..

**Comment by jonahwilliams** [comment]
Flutter no longer requires the NDK (hasn't for a while actually), so the checks have been removed.
