### ISSUE TITLE
Remove Gradle afterEvaluate block to include lifecycle dependencies

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#42348]
As part of migrating the plugins, we've needed to add in a Gradle afterEvaluate block that includes some extra libraries in cases where we're on older versions of Flutter and they're not exposed by the engine: https://gist.github.com/blasten/78e97b1d97a736d7e8dcc3f520cea3f0.

We've chosen to do this instead of including them in just plain old `dependencies` because plugins really shouldn't be specifying these dependencies themselves. We're only including them at all to prevent compile failures on older Flutter versions.

Once the missing dependency fix rolls to Flutter stable we should remove them.

**Comment by mklim** [comment]
This is now unblocked. See also flutter/flutter#47153.

**Comment by xster** [comment]
Closing this. #47153 will track the remaining work.
