### ISSUE TITLE
Flutter SDK tools dart files are with problem? (master channel)

### ISSUE THREAD

**Issue by lucaszanella** [flutter/flutter#42356]
I'm getting the following error in the SDK files after trying to compile my project. I redownloaded and rebuilt the entire tools but I still get it.
```

               Compiler message:                                            
    [   +1 ms] ../../development/flutter/packages/flutter/lib/src/semantics/semantics.dart:3627:45: Error: Getter not found: 'isLink'.
    [        ]   bool get isLink => _hasFlag(SemanticsFlag.isLink);         
    [        ]                                             ^^^^^^           
    [        ] ../../development/flutter/packages/flutter/lib/src/semantics/semantics.dart:3629:28: Error: Getter not found: 'isLink'.
    [        ]     _setFlag(SemanticsFlag.isLink, value);                   
    [        ]                            ^^^^^^                            
    [  +96 ms] Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
    [        ] Exception: Errors during snapshot creation: null             
    build failed.  
```

It looks like something in the SDK is wrong. How can this be possible?

I'm running like this:

    flutter --local-engine-src-path ../engine/src --local-engine=host_debug_unopt run

I'm on the **master** channel (because I need to run into desktop)

**Comment by jonahwilliams** [comment]
It looks like your local engine build flutter/engine and framework + tool flutter/flutter are out of sync:   You're using an engine from when after `SemanticsFlag.isLink` was added, but a framework/tool from before it rolled into the framework.

**Comment by lucaszanella** [comment]
both the flutter tool and SDK are dockerized, how can this be possible? 

```
FROM ubuntu:bionic

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y         \
      autoconf                 \
      build-essential          \
      ccache                   \
      checkinstall             \
      cmake                    \
      curl                     \
      gdb                      \
      git                      \
      golang                   \
      libbz2-dev               \
      libc6-dev                \
      libgdbm-dev              \
      libgles2-mesa-dev        \
      libglib2.0-dev           \
      libncursesw5-dev         \
      libreadline-gplv2-dev    \
      libsdl-dev               \
      libsdl2-dev              \
      libsqlite3-dev           \
      libssl-dev               \
      libtool                  \
      locales                  \
      man                      \
      ninja-build              \
      python-pip               \
      python2.7                \
      python2.7-dev            \
      ssh                      \
      texinfo                  \
      tk-dev                   \
      unzip                    \
      wget                     \
      valgrind


# Fix locale.
RUN rm -rf /var/lib/apt/lists/*
RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

WORKDIR /home/dev
ENV PATH="/home/dev/depot_tools:${PATH}"

RUN git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

#needed by some step
RUN apt-get install -y libx11-dev

RUN git config --global user.email "me@lucaszanella.com" && git config --global user.name "Lucas Zanella"

RUN wget --progress=bar:force -O flutter.tar.xz https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.9.1+hotfix.4-stable.tar.xz \
    && mkdir development && cd development && tar xf ../flutter.tar.xz \
    && export PATH="$PATH:/home/dev/development/flutter/bin/"

ENV PATH="/home/dev/development/flutter/bin/:${PATH}"

RUN flutter config --enable-linux-desktop \
    && flutter channel master 

RUN apt-get update && apt-get install -y clang rsync

RUN flutter doctor
```

**Comment by lucaszanella** [comment]
Ok now I get it. The master channel must have been updated, rigth? I was compiling this yesterday and it worked. Is there a way to rool to a previous commit of the master channel?

**Comment by lucaszanella** [comment]
@jonahwilliams I can't checkout the engine because I'm working on a branch that I want to pull request to the engine in the future. What I need is to use the same master channel I was using yesterday. It isn't clear how to use an specific master channel

**Comment by jonahwilliams** [comment]
unless you ran `flutter upgrade` the branch in flutter/flutter didn't change. If you did, you'll need to use git to return to whatever sha you were at.

**Comment by jonahwilliams** [comment]
It sounds like you might have pulled in a newer engine though?

**Comment by lucaszanella** [comment]
Please take a look if possible: https://github.com/lucaszanella/flutter-engine/tree/flutter_video_merge

I didnt update this engine. I was using it perfectly until I rebuilt flutter's docker. Before, when this docker was being built and the command flutter channel master ran, it said I was 1 commit behind. Now it does not comment this. Is it possible the master channel changed?

**Comment by jonahwilliams** [comment]
You need to ensure that you're using compatible engines and frameworks. In this case, you need to either update flutter/flutter to a newer version or roll back flutter/engine to an older version.

**Comment by royabhijit** [comment]
How to get it resolved can anyone please let me know?

**Comment by leadpresence** [comment]
What I have noticed about this error that really resolve it is its caused by certain plugins..so we should be mindful of plugins we include as they should be compatible with our flutter and dart updates...For me the Firebase 7.1.3 caused the error ..once i commented all classes using its classes my app runs ..how ever i have to find the most compatible plugins

**Comment by Zaid101** [comment]
I had this after downloading a newer flutter sdk, fixed it by starting a new project and copying the code from the old one, not a proper fix but it worked for me.
