### ISSUE TITLE
flutter analyze doesn't report issues in dart:ui

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4235]
For example I recently discovered that dart:ui isn't using @override, but I've never seen any script complain about that (the travis script in the engine repo doesn't turn on lints, in particular).

**Comment by Hixie** [comment]
It also doesn't report the count of missing dartdocs from dart:ui, which is related.

cc @pq

**Comment by pq** [comment]
Right.  I looked at this a bit yesterday and I see the issue(s).  I've got a few ideas and will run them by you next week.

**Comment by sethladd** [comment]
This sounds very useful to the Flutter team, but probably not critical for our users (they aren't going to analyze dart:ui directly, I would imagine). Moving to M3, but feel free to put it back.

**Comment by Hixie** [comment]
I'm going to close this. In practice we run the analyzer on the engine side separately, because that's when we need it. If we want to change the options that that side uses we could do so.
