### ISSUE TITLE
"dart:dart" trace events aren't present in AOT  traces on some configurations

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#42358]
https://b.corp.google.com/issues/140985776. Discussion should occur there, please.

/cc @a-siva , who I believe is looking into this at present.

**Comment by cbracken** [comment]
The fix for this landed in https://dart-review.googlesource.com/c/sdk/+/122081.

**Comment by cbracken** [comment]
Looks like the latest global integration roll was to 419f5d594afca0f66fd55e696c62e8bd107535da which includes this commit. Closing as fixed.
