### ISSUE TITLE
problem with adding a package dependency to ann app

### ISSUE THREAD

**Issue by haim986** [flutter/flutter#42357]
hi
i have problem with Adding a package dependency to an app
my dependencies at pubspec.yaml is:
![sp1](https://user-images.githubusercontent.com/50995371/66518326-9afe0c00-eaed-11e9-8491-5b96c6e36e29.PNG)
my android studio code of packages is:
![sp2](https://user-images.githubusercontent.com/50995371/66518340-aa7d5500-eaed-11e9-9858-05d2d146d1fb.PNG)
also i packages get and update packages and it didnt help for me
the error message is:
error: Target of URI doesn't exist: 'css_colors/css_colors.dart'.
try creating the file referenced by the uri or try using a url for a file that does exist

thanx for help

**Comment by BondarenkoStas** [comment]
@haim986 did you do `flutter packages get` and restarting the IDE after adding the dependency?
And please do not include screenshots of code/logs, it prevents them from being copied.

**Comment by haim986** [comment]
> @haim986 did you do `flutter packages get` and restarting the IDE after adding the dependency?
> And please do not include screenshots of code/logs, it prevents them from being copied.
i just posted the images because maybe i did somthing worng
yes i did fluttr package get  and it didnt help for me

**Comment by BondarenkoStas** [comment]
don't get me wrong, I meant that text version is always better. It's just hard to understand what is on that screenshot. Please try to add it in this way:
```
dependencies:
  css_colors: ^1.0.2
```
and run flutter packages get and restart IDE.

**Comment by haim986** [comment]
thank you my friend
