### ISSUE TITLE
Update docs web site atomically to avoid transient 404s

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#4236]
OverlayState link in the Overlay docs points to : http://docs.flutter.io/flutter/material/OverlayState-class.html which is a 404.

**Comment by apwilson** [comment]
Overlay link is here: http://docs.flutter.io/flutter/material/Overlay-class.html

**Comment by apwilson** [comment]
Oh wait... it worked this time...

**Comment by apwilson** [comment]
Intermittent 404s?

**Comment by abarth** [comment]
Yeah, we don't update the web site atomically yet.

**Comment by sethladd** [comment]
Working on it now :)

**Comment by sethladd** [comment]
This should be happening now. Big props to @jason-simmons for the DNS help.

We're producing a doc set on every merge into master from Travis.
