### ISSUE TITLE
Our iOS GPU percentage measurement seems to be flaky

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#42374]
See https://github.com/flutter/flutter/issues/42296 for more details.

**Comment by chinmaygarde** [comment]
@Hixie Is there a separate label for tracking benchmark flakiness or should I just add it to the general tag.

**Comment by Hixie** [comment]
just `team: flakes`

**Comment by Hixie** [comment]
These tests have been disabled entirely.

**Comment by Hixie** [comment]
Maybe we should just delete these tests?

**Comment by liyuqian** [comment]
@Hixie : this is our only performance test on energy. Instead of deleting the test, do you think that we should invest more on fixing the measurement tool so we won't accidentally regress the optimization that Jim made (see https://github.com/flutter/flutter/issues/31865#issuecomment-566268237)? Please check this proposal https://docs.google.com/document/d/1y9fEwySoFT1psh7YW-H4MvsZi0e8ZgZIDWAkJP8tAm4/edit#heading=h.uegn5e1ogt54
