### ISSUE TITLE
any flutter command  not working

### ISSUE THREAD

**Issue by bianxiang** [flutter/flutter#42389]
![image](https://user-images.githubusercontent.com/16380379/66536033-3a52eb80-eb4e-11e9-9f34-56947e320728.png)

**Comment by mattermoran** [comment]
This was happening to me when I had a VPN on.  Try disabling any vpn software if you have any

**Comment by bianxiang** [comment]
> Hello @bianxiang !
> 
> Thank you for posting.
> Can you please check whether the solution proposed by @mattermoran works for you?

it does not work！

**Comment by iapicca** [comment]
Hi @bianxiang 
you might wan to try following this possible [solution](https://github.com/flutter/flutter/issues/14866#issuecomment-549282198)
thank you

**Comment by iapicca** [comment]
Hi @bianxiang 
I see you opened a similar [issue](https://github.com/flutter/flutter/issues/40734)
Please follow up there.
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
