### ISSUE TITLE
Test framework doesn't flush Timer.run() callbacks

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4238]
It looks like when we idle(), and during asyncBarrier(), we should actually be elapsing by zero duration, so that `Timer.run()` timers get a chance to run too.

**Comment by zoeyfan** [comment]
@Hixie I am triaging our bug database, and found this from 2017. Are we still planning to do anything? Can we close this now?

**Comment by Hixie** [comment]
@zoeyfan have we fixed it? if not, it seems like it'd still be relevant...

**Comment by Hixie** [comment]
Turns out I fixed this a month before I filed this bug. https://github.com/flutter/flutter/pull/9332
