### ISSUE TITLE
Crash on Xcode 11.1

### ISSUE THREAD

**Issue by premtemp1** [flutter/flutter#42380]
Hello,
  I just upgraded Xcode to 11.1 and. my app crashes with following error:

2019-10-09 20:52:16.569622-0400 Runner[11435:99091] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23baa1ee __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50864b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23ba9f68 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff25614de9 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UIKitCore                           0x00007fff4757a29f -[UIApplication _createStatusBarWithRequestedStyle:orientation:hidden:] + 255
	5   UIKitCore                           0x00007fff4757a742 -[UIApplication statusBar] + 24
	6   Foundation                          0x00007fff2563de07 -[NSObject(NSKeyValueCoding) valueForKey:] + 317
	7   Runner                              0x000000010880238b -[FlutterStatusbarcolorPlugin handleMethodCall:result:] + 955
	8   Flutter                             0x00000001091284fd Flutter + 550141
	9   Flutter                             0x00000001090c1ec0 Flutter + 130752
	10  Flutter                             0x00000001090c5780 Flutter + 145280
	11  Flutter                             0x0000000109122db3 Flutter + 527795
	12  Flutter                             0x00000001090d43f1 Flutter + 205809
	13  Flutter                             0x00000001090d9742 Flutter + 227138
	14  CoreFoundation                      0x00007fff23b0d994 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	15  CoreFoundation                      0x00007fff23b0d682 __CFRunLoopDoTimer + 1026
	16  CoreFoundation                      0x00007fff23b0ccda __CFRunLoopDoTimers + 266
	17  CoreFoundation                      0x00007fff23b07a4e __CFRunLoopRun + 2238
	18  CoreFoundation                      0x00007fff23b06e66 CFRunLoopRunSpecific + 438
	19  GraphicsServices                    0x00007fff38346bb0 GSEventRunModal + 65
	20  UIKitCore                           0x00007fff47578dd0 UIApplicationMain + 1621
	21  Runner                              0x000000010859a640 main + 112
	22  libdyld.dylib                       0x00007fff516ecd29 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

lutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.9.1+hotfix.4 at /Users/prem/flutter
    • Framework revision cc949a8e8b (12 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/prem/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/prem/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.39.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • iPhone 11 • 45282F83-FA12-412D-BBDE-62F5B5ADDF6B • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1
      (simulator)

• No issues found!

**Comment by stuartmorgan** [comment]
> `7 Runner 0x000000010880238b -[FlutterStatusbarcolorPlugin handleMethodCall:result:] + 955`

The failing call is coming from a third-party plugin:
https://pub.dev/packages/flutter_statusbarcolor
You'll need to report it to the plugin maintainers.

Closing as this isn't a bug in Flutter code.

**Comment by premtemp1** [comment]
Thank you.

**Comment by enzoftware** [comment]
It solved upgrading status bar to 0.2.2 -> `flutter_statusbarcolor: 0.2.2`
