### ISSUE TITLE
LengthLimitingTextInputFormatter not work as expect

### ISSUE THREAD

**Issue by CodeEagle** [flutter/flutter#42388]
![image](https://user-images.githubusercontent.com/2311352/66535559-8bfa7680-eb4c-11e9-9c99-67356681ff13.png)

string "👪asdfdsaaa"'s length is treat as 11 in swift utf16,
but [Line 174](https://github.com/flutter/flutter/blob/387f885481cd8441237680de0cfcd0802c0af48c/packages/flutter/lib/src/services/text_formatter.dart#L174)
`newValue.text.runes.length` is only 10

**Comment by goderbauer** [comment]
That is currently working as expected due to how dart implements strings. It's a documented limitation, see https://master-api.flutter.dev/flutter/material/TextField/maxLength.html.
