### ISSUE TITLE
 The soft keyboard does not work when the system's Security Keyboard settings are turned on.

### ISSUE THREAD

**Issue by asjqkkkk** [flutter/flutter#42386]
## Steps to Reproduce

I have met this problem yestoday.

# Problem description

## 1.When I enter the password into TextFormField with the  **obscureText** property

![not_work](https://user-images.githubusercontent.com/30992818/66533840-f0b2d280-eb46-11e9-8155-02c2002aa6eb.gif)

## 2.then I found my phone's keyboard Settings

![secure_open](https://user-images.githubusercontent.com/30992818/66534712-a4b55d00-eb49-11e9-8b98-ea1b963b4ea4.jpeg)

## 3.after I close the  Security Keyboard

![secure_close](https://user-images.githubusercontent.com/30992818/66534481-ea255a80-eb48-11e9-8914-e2d8601bf06a.jpeg)

## 4.It works!

![work](https://user-images.githubusercontent.com/30992818/66534492-f0b3d200-eb48-11e9-9cf8-6eac11971a14.gif)

# Environment

## Phone
These are my phone parameters

![Screenshot_2019-10-10-10-31-46-085_com android se](https://user-images.githubusercontent.com/30992818/66534607-51dba580-eb49-11e9-84dd-f3d68e554842.png)

## Flutter

```
[✓] Flutter (Channel unknown, v1.9.7, on Mac OS X 10.15 19A583, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 10.3)
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
        pod setup
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)
```

# Logs

No abnormality

**Comment by markusaksli-nc** [comment]
Hi @asjqkkkk 
We cannot reproduce this issue so we are going to close it as probably fixed since you originally experienced this on is a year old at this point. If you still experience it on the latest master or dev, let me know and I'll reopen.
Thank you
