### ISSUE TITLE
Plugin: Network status

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#424]
Mobile platforms expose APIs for network status. For example: connected or not-connected. Exposing these APIs to Flutter will help developers build offline-capable apps and apps that can deal with transient network connectivity.

**Comment by Hixie** [comment]
We believe this now exists. Please reopen if it does not. Please open a new bug if it is insufficient.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/plugins/tree/master/packages/connectivity
