### ISSUE TITLE
SharedPreferences should have better singleton instantiation

### ISSUE THREAD

**Issue by magnuswikhog** [flutter/flutter#42407]
As discussed in [this StackOverflow question](https://stackoverflow.com/questions/58293815/sharedpreferences-not-getting-stored-between-calls), the `getInstance()` method in the `SharedPreferences` plugin is not reliable when called from both a microtask and regular code. The problem seems to be that `_instance == null` will be true until  ` await _getSharedPreferencesMap();` has returned, and therefor it's possible to get two different instances from this singleton factory.

    static Future<SharedPreferences> getInstance() async {
      if (_instance == null) {
        final Map<String, Object> preferencesMap =
            await _getSharedPreferencesMap();
        _instance = SharedPreferences._(preferencesMap);
      }
      return _instance;
    }

## Steps to Reproduce

	@override
	void initState() {
	  initAsync();
	  super.initState();
	}

	initAsync() async {
	  scheduleMicrotask(() async {
	    print("microtask: START ");
	    TestClass microtask = await TestClass.getInstance("microtask");
	    print("microtask: FINISH (instance: ${microtask.hashCode})");
	  });

	  print("initAsync_1: START");
	  TestClass initAsync_1 = await TestClass.getInstance("initAsync_1");
	  print("initAsync_1: FINISH (instance: ${initAsync_1.hashCode})");

	  Future.delayed(Duration(seconds: 3)).then((_) async {
	    print("initAsync_2: START");
	    TestClass initAsync_2 = await TestClass.getInstance("initAsync_2");
	    print("initAsync_2: FINISH (instance: ${initAsync_2.hashCode})");
	  });
	}

	class TestClass {
	  static TestClass _instance;
	  static Future<TestClass> getInstance(String call) async {
	    if (_instance == null) {
	      print("$call: without instance before");
	      await Future.delayed(Duration(seconds: 3));
	      _instance = TestClass();
	      print("$call: without instance after");
	    } else {
	      print("$call: with instance");
	    }
	    return _instance;
	  }
	}

## Logs

	initAsync_1: START
	initAsync_1: without instance before
	microtask: START 
	microtask: without instance before
	initAsync_1: without instance after
	initAsync_1: FINISH (instance: 674207757)
	microtask: without instance after
	microtask: FINISH (instance: 1059788553)
	initAsync_2: START
	initAsync_2: with instance
	initAsync_2: FINISH (instance: 1059788553)

## Possible solution

One possible solution would be to use a `Completer`:

    static Future<SharedPreferences> getInstance() async {
        if( _initialization != null && !_initialization.isCompleted ) {
            await _initialization.future;
        }

        if (_instance == null) {
            _initialization = Completer<void>();
            
            try {
                final Map<String, Object> preferencesMap =
                await _getSharedPreferencesMap();
                _instance = SharedPreferences._(preferencesMap);
            }
            finally{
                _initialization.complete();
            }
        }

        return _instance;
    }

**Comment by sanekyy** [comment]
This issue still actual and can produce more than 1 instance:(

**Comment by gslender** [comment]
By "this" I mean cases where data stored is not able to be read moments later in the app. There is definitely some challenges around the async nature and even using reload() seems to have no improvement in ensuring the data is kept. I'm always using await with setString but for some unexplained reason, there are cases when getString followed after a setString results in the value not being stored !?

**Comment by gslender** [comment]
I've raised an issue #128368 that speaks to the issue I'm having, of which this issue here seems to be related

**Comment by stuartmorgan** [comment]
> This issue still actual and can produce more than 1 instance:(

It turns out that this was fixed years ago (slightly before this issue was filed, in fact), but regressed during the NNBD transition.

**Comment by stuartmorgan** [comment]
> even using reload() seems to have no improvement in ensuring the data is kept

If calling `reload()` before reading doesn't help, then your case is unrelated to this one. This could cause there to be different instances of the Dart-side cache, but the purpose of `reload()` is to update that cache with the current native state.
