### ISSUE TITLE
Flutter Web Firebase Error 

### ISSUE THREAD

**Issue by alunmvs** [flutter/flutter#42408]
I want to use firebase on my flutter web project, but when I try to run the project there is an error occurred : 
```
> AssetNotFoundException: firebase|lib/src/app.ddc.js
> Error compiling dartdevc module:firebase|lib/src/app.ddc.js
> 
> packages/firebase/src/utils.dart:133:5: Error: Method not found: 'promiseToFuture'.
>     promiseToFuture(thenable);
>     ^^^^^^^^^^^^^^^
```
## Flutter doctor
```
> [✓] Flutter (Channel master, v1.10.15-pre.42, on Mac OS X 10.14.5 18F132, locale en)
>     • Flutter version 1.10.15-pre.42 at ....../dev/flutter
>     • Framework revision 480342899e (4 hours ago), 2019-10-09 18:58:27 -0700
>     • Engine revision e693192167
>     • Dart version 2.6.0 (build 2.6.0-dev.0.0 41d13f0ffe)
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/alun/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.0)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.0, Build version 11A420a
>     • CocoaPods version 1.7.5
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 3.4)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 39.0.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [✓] VS Code (version 1.39.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.5.1
> 
> [✓] Connected device (2 available)
>     • Chrome          • chrome          • web-javascript • Google Chrome 77.0.3865.90
>     • Headless Server • headless-server • web-javascript • Flutter Tools
> 
> • No issues found!
```
I'm using: `firebase: ^5.0.0`

I just import firebase on main.dart, and that error occurred.

someone had idea what's the problem?

**Comment by danielwilliamson** [comment]
I have have this error and have tracked the offending [auto commit](https://github.com/flutter/flutter/pull/42363)

**Comment by obshksw** [comment]
I'm not using firebase and it fails in my project also since this morning on 1.10.15. Rollbacking to 1.10.14 works.

```
Error compiling dartdevc module:live_app|lib/util/webrtc/webrtc_web.ddc.js

packages/live_app/util/webrtc/webrtc_web.dart:75:12: Error: Method not found: 'promiseToFuture'.
    return promiseToFuture(enumerateDevices());
           ^^^^^^^^^^^^^^^
packages/live_app/util/webrtc/webrtc_web.dart:79:30: Error: Method not found: 'promiseToFuture'.
    Future<dynamic> future = promiseToFuture(getDisplayMedia({}));
                             ^^^^^^^^^^^^^^^
```

**Comment by kronemaster** [comment]
Same here. Just upgraded flutter and got this message on run:

`AssetNotFoundException: firebase|lib/src/app.ddc.js
Error compiling dartdevc module:firebase|lib/src/app.ddc.js

packages/firebase/src/utils.dart:133:5: Error: Method not found: 'promiseToFuture'.
    promiseToFuture(thenable);
    ^^^^^^^^^^^^^^^



Failed after 3.9s`

**Comment by kronemaster** [comment]
Same here. Just upgraded flutter and got this message on run:

> AssetNotFoundException: firebase|lib/src/app.ddc.js
Error compiling dartdevc module:firebase|lib/src/app.ddc.js

>packages/firebase/src/utils.dart:133:5: Error: Method not found: 'promiseToFuture'.
promiseToFuture(thenable);
^^^^^^^^^^^^^^^

>Failed after 3.9s

**Comment by alunmvs** [comment]
> I'm not using firebase and it fails in my project also since this morning on 1.10.15. Rollbacking to 1.10.14 works.
> 
> ```
> @JS("navigator.mediaDevices.enumerateDevices")
> external dynamic enumerateDevices();
> 
> @JS("navigator.mediaDevices.getDisplayMedia")
> external dynamic getDisplayMedia(dynamic constraints);
> 
> Error compiling dartdevc module:live_app|lib/util/webrtc/webrtc_web.ddc.js
> 
> packages/live_app/util/webrtc/webrtc_web.dart:75:12: Error: Method not found: 'promiseToFuture'.
>     return promiseToFuture(enumerateDevices());
>            ^^^^^^^^^^^^^^^
> packages/live_app/util/webrtc/webrtc_web.dart:79:30: Error: Method not found: 'promiseToFuture'.
>     Future<dynamic> future = promiseToFuture(getDisplayMedia({}));
>                              ^^^^^^^^^^^^^^^
> ```

thanks bro.. it's work after rolling back to v1.10.14..

**Comment by danielwilliamson** [comment]
@alunmvs I don't think this ticket should be closed as the underlying issue is still there.

**Comment by muhleder** [comment]
Root issue is here https://github.com/dart-lang/sdk/issues/38805

**Comment by kroikie** [comment]
@alunmvs

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/310. Any further collaboration will be done there.
