### ISSUE TITLE
Split Paint into two, one for drawing and one for compositing

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4240]
Right now there's a few properties on Paint used with saveLayer, and the rest are used when drawing, and (except maybe transferMode?) none are used for both. It would save us time marshaling data around and would simplify the documentation if we were to instead split this class in two.

**Comment by Hixie** [comment]
With further study, I think the above description is wrong. However, maybe we should have a class for saveLayer() that only includes the stuff used by saveLayer, and a separate one for the places that actually use everything on paint.

**Comment by Hixie** [comment]
@abarth You may have an opinion on this one.

**Comment by abarth** [comment]
I think the current approach has actually worked out pretty well.  IMHO, we should stick with it.
