### ISSUE TITLE
I can't run flutter doctor -v, need help?

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#42418]
Yesterday upgrade my MacBook Pro to macOS Catalina. It was okay and wasn't any problem. But to day I get an error as shown below.

I can't run flutter doctor -v, need help?

```
Last login: Thu Oct 10 13:43:26 on ttys000
niyazitoros@Niyazi-MBP ~ % chsh -s /bin/zsh
\Changing shell for niyazitoros.
Password for niyazitoros: 
chsh: no changes made
niyazitoros@Niyazi-MBP ~ % flutter doctor -v
zsh: command not found: flutter
niyazitoros@Niyazi-MBP ~ % 
```

**Comment by edisonlsm** [comment]
I had the same issue yesterday. You changed the default bash to zsh, which means the ~/.bash_profile does not work anymore and the PATH is not loaded.

I fixed it here by copying the bash_profile to a new file named `.zshenv` and reloading zsh.

**Comment by BondarenkoStas** [comment]
@NTMS2017 @edisonlsm is right, please add your `export PATH=$PATH:/Users/xxx/flutter/bin` or whatever path you have to your `~/.zshrc`, run `source ~/.zshrc` and then reopen terminal.

**Comment by NTMS2017** [comment]
@edisonlsm and @BondarenkoStas Thanks, it is working now.
