### ISSUE TITLE
Issue from website page 在Flutter中构建布局

### ISSUE THREAD

**Issue by santa0000** [flutter/flutter#42416]
From URL: https://flutterchina.club/tutorials/layout/

the link for main.dart is unvailable (https://raw.githubusercontent.com/flutter/website/master/_includes/code/layout/lakes/main.dart)

**Comment by BondarenkoStas** [comment]
@santa0000 thank you for report! I believehttps://github.com/flutter/website/blob/master/examples/layout/lakes/step2/lib/main.dart is supposed to be there.

**Comment by santa0000** [comment]
thanks

**Comment by BondarenkoStas** [comment]
@santa0000 Apparently we can't fix the link, please file it to https://github.com/flutterchina/website/issues.
