### ISSUE TITLE
lldb high cpu on mac.

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#42423]
## Steps to Reproduce

![image](https://user-images.githubusercontent.com/6405390/66565635-870de500-eb95-11e9-9c44-0d6b74335d8c.png)

I have see the high cpu problem when I left computer locked and come back after dining.

The terminal is running `flutter run --debug -d [iOS simulator]`(which means it can hot reload by `r`) before I leave.

I meet this twice in these 2 days.

Not sure what cause this cpu hight result.

I have see one message that it may related to plugin of VSCode's, but not sure about how to verify it.

**Target Platform:** iOS
**Target OS version/browser:** iOS13.1
**Devices:** Xcode11.1's  iPhone 11 Pro Max(Simulator)

Run `flutter analyze`, and show infos as bellow:
```
info * Unused import: ...
info * The value of the field '...' isn't used
info * This function has a return type of '...', but doesn't end with a return statement
info * The declaration '...' isn't referenced
info * Unnecessary cast
info * This class (or a class which this class inherits from) is marked as '@immutable', but
          one or more of its instance fields are not final
```

Running `flutter doctor -v`:

```
[✓] Flutter (Channel beta, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-CN)
    • Flutter version 1.9.1+hotfix.4 at /Users/jerryzhou/Documents/code/flutter/sdk/flutter
    • Framework revision cc949a8e8b (13 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jerryzhou/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✗] Cannot determine if IntelliJ is installed
    ✗ Directory listing failed

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • iPhone 11 Pro Max • 4543F274-DE8D-45CC-8600-EA889708FB37 • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
```

**Comment by psbarrales** [comment]
Same issue here!.
It's replicated four time and using all CPU

**Comment by a43mrk** [comment]
same problem here :(

**Comment by jonahwilliams** [comment]
lldb is the debugger spawned by Xcode when running an iOS application, and not a part of the Flutter or Dart tooling. It's not clear from this issue whether this is anything to do with Flutter.

**Comment by jerryzhoujw** [comment]
so it's lldb's issue ?

**Comment by iYadavVaibhav** [comment]
same problem. Everything else is stuck because of this. Anyone found any workaround? Thanks.

**Comment by jerryzhoujw** [comment]
@iYadavVaibhav  Kill the thread when you meet this.

**Comment by iYadavVaibhav** [comment]
Yes, this worked out. Also because of this multiple dart process were running. You might need to do `killall dart`. Please check for `ps -ef | grep dart`.

**Comment by chinmaygarde** [comment]
LLDB is the native debugger that is launched by Xcode. Flutter does not directly launch or have control over the lifecycle of this program. Because of this, I don't think this issue is actionable.
