### ISSUE TITLE
Alaramservice not import in Application class

### ISSUE THREAD

**Issue by jyothishkm** [flutter/flutter#42426]

**Comment by BondarenkoStas** [comment]
@jyothishkm please explain in more details. Also provide your `flutter doctor -v output` and some code example to reproduce the issue if possible.

**Comment by jyothishkm** [comment]
I want to develope alaram app in flutter. I gone through the flutter doc. "https://pub.dev/packages/android_alarm_manager#-readme-tab-" 
 `public class Application extends FlutterApplication implements PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    AlarmService.setPluginRegistrant(this);
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}`

In the above class AlarmService is not importing.
I added android_alarm_manager: ^0.4.1+6 dependency in pubspec.yaml 
>

**Comment by BondarenkoStas** [comment]
did you do `flutter pub update` and restart the IDE?

**Comment by jyothishkm** [comment]
yes i did.

Thanks & Regards,
Jyothish K M

**Comment by BugsBunnyBR** [comment]
@jyothishkm 
did runnning `flutter pub update` solved your issue?

If not, try to use this [class](https://github.com/flutter/plugins/blob/master/packages/android_alarm_manager/example/android/app/src/main/java/io/flutter/plugins/androidalarmmanagerexample/Application.java) as your Application and add the needed imports.
If you create/open your project as a flutter project on Android Studio the lines may be in red, but if you open the android project only in Android Studio, it should recognize the imports properly.

**Comment by TahaTesser** [comment]
Hi @jyothishkm 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
