### ISSUE TITLE
Unable to pass target aspectRatio to instantiateImageCodec

### ISSUE THREAD

**Issue by BharathMG** [flutter/flutter#42432]
## Use case

When displaying images from network with unknown size, we have no way to calculate `targetWidth` and `targetHeight` to be able to pass as parameters to `instantiateImageCodec` in `painting.dart` to scale the images.

## Proposal

It will be really great if we could just pass the desired aspect ratio with image bytes just like we currently pass `targetWidth` and `targetHeight` in `instantiateImageCodec`.

**Comment by BondarenkoStas** [comment]
@BharathMG instantiateImageCodec is a part of dart:ui, I would advise you to file the issue to https://github.com/dart-lang/sdk/issues and paste the link to it here.

**Comment by BharathMG** [comment]
@BondarenkoStas Thanks! I just posted this in dart sdk github. https://github.com/dart-lang/sdk/issues/38827

**Comment by BondarenkoStas** [comment]
Omg I confused that dart:ui is actually in the flutter repo, my bad.

**Comment by a-siva** [comment]
I have closed the Dart side issue.

**Comment by darshankawar** [comment]
@BharathMG 
Is this still a valid issue ?
If so, Can you check [this](https://stackoverflow.com/questions/63063906/flutter-resize-network-image) solution and see if it works for you ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
