### ISSUE TITLE
Prevent app rebuilt after onResume

### ISSUE THREAD

**Issue by thaitanloi365** [flutter/flutter#42436]
Hello, I'm Loi. I had an issue with my app. The app always rebuilt after onResume, please see my video attached. My expected behavior that the app should persist current states. Please help.

https://streamable.com/kuzkn

**Target Platform: iOS 13.2
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale
    en-VN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.39.0)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

```

**Comment by BondarenkoStas** [comment]
@thaitanloi365 if you can come up with a minimum code example that reproduces the issue, it will be helpful.

**Comment by thaitanloi365** [comment]
@BondarenkoStas , Thanks for your quick response. I just found a cause of this issue. It related to GlobalKey<ScaffoldState>.
