### ISSUE TITLE
Possible regression in backdrop_filter_perf__timeline_summary90th_percentile_frame_build_time_millis

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#42440]
Looks noisy, but trends up at https://github.com/flutter/engine/pull/13058 with some spikes previously at https://github.com/flutter/flutter/pull/41879, which I don't think is the issue.

**Comment by LongCatIsLooong** [comment]
The numbers have gone back to normal since https://github.com/flutter/flutter/commit/166fd5975d09f001a46a844f03ac769050c55a08. Closing in order to resume the roll.
