### ISSUE TITLE
[webview_flutter] iOS can not open target _blank links and links inside iframes

### ISSUE THREAD

**Issue by rodruiz** [flutter/flutter#42448]
This [PR](https://github.com/flutter/plugins/pull/2067) will fix this issue.

Thanks!

**Comment by TahaTesser** [comment]
Hi @rodruiz 
Since this [PR](https://github.com/flutter/plugins/pull/2500) from this [comment](https://github.com/flutter/plugins/pull/2067#issuecomment-582689991)
I feel safe to close this issue
If you disagree please write in the comments and I will reopen it. 
Thank you
