### ISSUE TITLE
Shard Mac & Windows Cirrus jobs so execution time is limited to 15 mins.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#42457]
At a failure rate of about 12% (4 of 32 builds) over a single days worth of commits, timeouts on Mac and Windows seem to be one of the causes of infra flakiness.

Failing jobs for reference:
* https://cirrus-ci.com/task/5350427847032832 Windows
* https://cirrus-ci.com/task/4679275218731008 Mac 
* https://cirrus-ci.com/task/6043112589230080 Mac
* https://cirrus-ci.com/task/5075727627583488 Windows

**Comment by chinmaygarde** [comment]
@Hixie says he has a WIP patch that limits time to 15 mins but the limit on Windows is 1 hours and on the Mac it seems to be 45 mins. As long as we are below that threshold, we should be fine.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/41880 is part of this work

**Comment by Hixie** [comment]
That said, that PR won't fix any of the problems you ran into. The problems in all four cases were not the timeouts: in all four cases, something hung. These are not infrastructure failures, they are bugs.

https://cirrus-ci.com/task/5350427847032832: pub hung for nearly an hour with no progress, then the shard timed out.
https://cirrus-ci.com/task/4679275218731008: progress stopped being made loading tests, and so all tests starting taking the max time (12 minutes apparently) then timing out, until the entire shard got timed out.
https://cirrus-ci.com/task/6043112589230080: same
https://cirrus-ci.com/task/5075727627583488: all progress stopped while compiling the tests, after about an hour of waiting for them to compile, the shard timed out.

**Comment by Hixie** [comment]
I got this down to ~30 minutes. I don't think we can get to ~15 minutes without dramatically increasing the likelihood of flakes.
