### ISSUE TITLE
Flutter run crashes when deploying to iOS device

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#4245]
## Steps to Reproduce

Using the versions of the software below, `flutter run` to deploy to an iOS device (I'm using an iPhone 6s running iOS v9.3)
## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/djshuckerow/.flutter
    • Framework revision 646b5350d1 (23 hours ago), engine revision 7fab0c350b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/djshuckerow/Library/Android/sdk
    • Platform android-N, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3, Build version 7D175

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
## Logs and Crash Reports

[....] Waiting for iOS device to be connected
[....] Using N71mAP 'First's iPhone' (a1b07916f5d38432c3e4dde4a427b14a23ee16ab).
------ Install phase ------
[  0%] Found N71mAP 'First's iPhone' (a1b07916f5d38432c3e4dde4a427b14a23ee16ab) connected through USB, beginning install
[  5%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/META-INF/ to device
[  5%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/META-INF/com.apple.ZipMetadata.plist to device
[  6%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/_CodeSignature/ to device
[  6%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/_CodeSignature/CodeResources to device
[  7%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon29x29@2x.png to device
[  7%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon29x29@2x~ipad.png to device
[  8%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon29x29@3x.png to device
[  8%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon29x29~ipad.png to device
[  9%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon40x40@2x.png to device
[ 10%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon40x40@2x~ipad.png to device
[ 10%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon40x40@3x.png to device
[ 11%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon40x40~ipad.png to device
[ 11%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon60x60@2x.png to device
[ 12%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon60x60@3x.png to device
[ 12%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon76x76@2x~ipad.png to device
[ 13%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon76x76~ipad.png to device
[ 14%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/AppIcon83.5x83.5@2x~ipad.png to device
[ 14%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/embedded.mobileprovision to device
[ 15%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/ to device
[ 16%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/Flutter.framework/ to device
[ 16%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/Flutter.framework/_CodeSignature/ to device
[ 17%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/Flutter.framework/_CodeSignature/CodeResources to device
[ 18%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter to device
[ 35%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/Flutter.framework/icudtl.dat to device
[ 38%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/Flutter.framework/Info.plist to device
[ 39%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/ to device
[ 40%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/_CodeSignature/ to device
[ 40%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/_CodeSignature/CodeResources to device
[ 41%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/app.flx to device
[ 42%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/FlutterApplication to device
[ 43%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/FlutterApplication.framework/Info.plist to device
[ 44%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/Frameworks/libGoogleSignIn.dylib to device
[ 45%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/Info.plist to device
[ 46%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/LaunchScreen.storyboardc/ to device
[ 46%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib to device
[ 47%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/LaunchScreen.storyboardc/Info.plist to device
[ 47%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib to device
[ 48%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/PkgInfo to device
[ 48%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/Runner to device
[ 49%] Copying appdir/ios/.generated/build/Release-iphoneos/Runner.app/ServiceDefinitions.json to device
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 65%] InstallingEmbeddedProfile
[ 70%] VerifyingApplication
[ 75%] CreatingContainer
[ 80%] InstallingApplication
[ 85%] PostflightingApplication
[ 90%] SandboxingApplication
[ 95%] GeneratingApplicationMap
[100%] Installed package ios/.generated/build/Release-iphoneos/Runner.app
------ Debug phase ------
Starting debug of N71mAP 'First's iPhone' (a1b07916f5d38432c3e4dde4a427b14a23ee16ab) connected through USB...
[  0%] Looking up developer disk image
[ 95%] Developer disk image mounted successfully
## [100%] Connecting to remote debug server

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python/lldb/**init**.py", line 98, in <module>
    import six
ImportError: No module named six
(lldb) command source -s 0 '/tmp/fruitstrap-lldb-prep-cmds-a1b07916f5d38432c3e4dde4a427b14a23ee16ab'
Executing commands in '/tmp/fruitstrap-lldb-prep-cmds-a1b07916f5d38432c3e4dde4a427b14a23ee16ab'.
(lldb)     platform select remote-ios --sysroot '/Users/djshuckerow/Library/Developer/Xcode/iOS DeviceSupport/9.3.2 (13F69)/Symbols'
  Platform: remote-ios
 Connected: no
  SDK Path: "/Users/djshuckerow/Library/Developer/Xcode/iOS DeviceSupport/9.3.2 (13F69)/Symbols"
(lldb)     target create "appdir/ios/.generated/build/Release-iphoneos/Runner.app"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Current executable set to 'appdir/ios/.generated/build/Release-iphoneos/Runner.app' (arm64).
(lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/81470E90-2EC5-4AD5-8E24-37F315162BB3/Runner.app"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
error: python failed attempting to evaluate 'fruitstrap_device_app="/private/var/containers/Bundle/Application/81470E90-2EC5-4AD5-8E24-37F315162BB3/Runner.app"'

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by abarth** [comment]
See https://github.com/flutter/flutter/issues/4269 where we think the issue is due to a homebrew install of python being in the user's path and that confusing Apple's python code.

**Comment by DaveShuckerow** [comment]
Removing the brew python works as a workaround to the issue, but I wouldn't mark this as closed until there's a proper fix.

**Comment by eseidelGoogle** [comment]
Presumably the fix is to clear the PATH from the environment before invoking any xcode commands.

Others have hit this or related, btw:
https://github.com/dropbox/dropbox-sdk-python/issues/62
https://github.com/pypa/pip/issues/3165

**Comment by abarth** [comment]
Yeah, I suspect people usually run Xcode from the app launcher, which probably has a different environment than they use in their shell.

**Comment by eseidelGoogle** [comment]
Correct.  If this theory holds `xcodebuild` should fail similarly from the command line.

**Comment by cbracken** [comment]
Added a doctor check in #7807

**Comment by miketraverso** [comment]
Has anyone run into the immediate crash using TestFlight? I'm able to deploy successfully to device via debugging. Deploying via TestFlight causes an immediate crash. Bitcode is set to NO. Tried setting Optimization Level to None too. Any ideas? Doesn't even cause a crash log on the device.

**Comment by cbracken** [comment]
Updated the fix and eliminated the doctor check in #19281.
