### ISSUE TITLE
Chip delete button tap target is too small.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#42455]
Now that `InkResponse` has a focus node in it, the delete button has a separate semantics node, which causes it to appear in the `examples/flutter_gallery/accessibility_test.dart` search for nodes to measure, and it's coming up as too small: it's 18x18 instead of 48x48, since the tap target is only the delete icon itself.

Fixing this will probably require wrapping the delete icon in a larger gesture detector above the `InkResponse`.

**Comment by jonahwilliams** [comment]
IIRC, the delete chip icon isn't spec'd for touch devices.

**Comment by gspencergoog** [comment]
That's correct, so we'll probably just have to fix our accessibility tests to ignore chips with a delete icon.

In the mean time, I've temporarily skipped the `chip_demo` accessibility test.

**Comment by Hixie** [comment]
Skipping just certain chips will be tricky given the current semantics-based implementation, because there's really nothing about the chip delete buttons that is recognizable in the semantics tree...

**Comment by jonahwilliams** [comment]
We could put a semantics tag like "noTouchSpec" or something on the semantics node, and then teach the tap target inspector to skip over those

**Comment by Hixie** [comment]
yeah but that seems like such a weird thing to do to that API

**Comment by jonahwilliams** [comment]
Yeah, its basically like programming a skip into the test. Of course, the underlying issue remains - the chip delete buttons are unusable on touch devices 😞

**Comment by Hixie** [comment]
I suppose another option is to make the hit test region bigger than the chip so that it's accessible...

**Comment by gspencergoog** [comment]
So, I've been looking at this again recently, and it appears that the current implementation gets around this issue by not using an `InkWell` at all for the delete button, and thus avoiding having a focus node.

This seems wrong too, since then the semantics don't mark the delete button as focusable.
