### ISSUE TITLE
AnimatedIcons class needs more icons

### ISSUE THREAD

**Issue by dfmiller** [flutter/flutter#42461]
Fourteen icons are not enough, especially since many of them are just the reverse animation of each other.

Specifically, I need add_close which would animate a plus symbol to an X.

**Comment by willlarche** [comment]
cc: @willlarche

**Comment by aryzhov** [comment]
Also, please add expand/collapse icon (v / ^).

**Comment by allanwolski** [comment]
I need add_close too.

**Comment by AresVampire** [comment]
I need too

**Comment by joeyda3rd** [comment]
I also need add_close. Seems like a pretty basic and easy one to implement. Any progress on this?

**Comment by willlarche** [comment]
Sad to say we do not have any plans for more animated icons. Consider lookin at https://rive.app/ for animations. There's a community of people who donate their designs. It may have what you're looking for. Or if you make it and post it, someone else could use it someday.

**Comment by joeyda3rd** [comment]
@willlarche Any possibility of getting a general purpose tool and documentation from vitool? Something we can use to generate the AnimatediconData so we can submit them? Any thoughts on a workaround or are you just planning on leaving it as-is?

**Comment by willlarche** [comment]
I'm not aware of any plans to do so, no. @amirh is there anything you can recommend back from the original project 3 years ago?

**Comment by charlee** [comment]
if the simple transition between the two icons is enough `simple_animated_icon` package might be useful
