### ISSUE TITLE
LUCI failure to stat a file in the fuchsia build

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#42468]
```FAILED: flutter_aot_runner_far.manifest flutter_aot_runner.far 
python ../../flutter/tools/fuchsia/gen_package.py --pm-bin /b/s/w/ir/cache/builder/src/fuchsia/sdk/linux/tools/pm --package-dir /b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/flutter_aot_runner_far --signing-key /b/s/w/ir/cache/builder/src/flutter/tools/fuchsia/development.key --far-name flutter_aot_runner
stat : no such file or directory
Traceback (most recent call last):
  File "../../flutter/tools/fuchsia/gen_package.py", line 103, in <module>
    sys.exit(main())
  File "../../flutter/tools/fuchsia/gen_package.py", line 94, in main
    subprocess.check_call(pm_command_base + ['build'])
  File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
```

We've seen this once so far. We should investigate if it happens again.

https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia/1074

cc: @chinmaygarde , @dnfield

**Comment by dnfield** [comment]
I saw this when I was working on build/recipe changes and thought I fixed it, but it's flaky and I guess I just got unlucky that the flake didn't happen after some change.

**Comment by dnfield** [comment]
I very strongly suspect at this point that we're not truncating the manifest before generating it.

See gen_package.py line 31

**Comment by dnfield** [comment]
@jason-simmons says he can reproduce this locally by having an entry in the manifest like `file=\n`.

**Comment by jason-simmons** [comment]
Another potential clue: This run of `gen_package.py` failed with an `invalid character '\x00' after top-level value` error:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8899421159877314256/+/steps/build_fuchsia_debug_x64_flutter_shell_platform_fuchsia_flutter:flutter_jit_runner_flutter_shell_platform_fuchsia_flutter:flutter_aot_runner_flutter_shell_platform_fuchsia_dart_runner:dart_jit_runner_flutter_shell_platform_fuchsia_dart:kernel_compiler_flutter_shell_platform_fuchsia_flutter:flutter_runner_tests/0/stdout

The content of the manifest in the log dump looks normal though.

**Comment by jason-simmons** [comment]
This was fixed by https://github.com/flutter/engine/pull/13341
