### ISSUE TITLE
Adding to app without Cocoapods is causing signing problems on XCode 11.1

### ISSUE THREAD

**Issue by BernardGatt** [flutter/flutter#42463]
I've been following the effort around Add2App and recently there were some developments around embedding flutter without cocoapods see: https://github.com/flutter/flutter/issues/36968#issuecomment-533357802

With flutter on master and XCode 11 I was able to embed flutter in a separate app (not Runner) using the above steps and was able to successfully load the flutter app on a device.

After upgrading to XCode 11.1 I started getting issues about signing. Mainly
`Recovery Suggestion: Install claimed to have succeeded, but application could not be found on device. bundleId = com.test.app`

**Comment by jmagman** [comment]
> I've been following the effort around Add2App and recently there were some developments around embedding flutter without cocoapods see: [#36968 (comment)](https://github.com/flutter/flutter/issues/36968#issuecomment-533357802)
> 
> With flutter on master and XCode 11 I was able to embed flutter in a separate app (not Runner) using the above steps and was able to successfully load the flutter app on a device.

Whoa, that's awesome!  I think you're one of the first to try that.

> After upgrading to XCode 11.1 I started getting issues about signing. Mainly
> `Recovery Suggestion: Install claimed to have succeeded, but application could not be found on device. bundleId = com.test.app`

I just upgraded to 11.1, let me try.
Can we get the output of `flutter doctor -v`?

**Comment by BernardGatt** [comment]
```
[✓] Flutter (Channel master, v1.10.15-pre.60, on Mac OS X 10.15 19A583, locale en-MT)
    • Flutter version 1.10.15-pre.60 at /Users/bernard/Development/flutter
    • Framework revision 6a63ef7d81 (2 hours ago), 2019-10-10 13:49:43 -0400
    • Engine revision 0b6aa5e320
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 48e93d3d3b)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/bernard/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available
```

**Comment by arctouch-matheusromao** [comment]
Whoa!

Are the steps in (#36968 (comment))[https://github.com/flutter/flutter/issues/36968#issuecomment-533357802] what we have to do to release an iOS app with a flutter module? 

I just posted #42458 saying that we are having problems to generate a build in release.

**Comment by BernardGatt** [comment]
Those steps are required if you want to embed flutter into an existing app without having to use cocoapods. My end goal (after figuring this out) is to actually bundle flutter into another framework which provides an easy to use swift interface.

The issue you're having should be related to the framework (Flutter or App) not being bundled which is a bit weird since you're using cocoapods, but it could be related to the framework not being signed and bundled.

**Comment by jmagman** [comment]
> Are the steps in [#36968 (comment)](https://github.com/flutter/flutter/issues/36968#issuecomment-533357802) what we have to do to release an iOS app with a flutter module?

Getting the tools to do all those steps automatically is a goal for the next quarter.  That would allow one developer with the flutter environment set up to generate all necessary frameworks/libraries, embed in the host app, then be usable (though not editable) by other developers on the team that do not have `flutter` or CocoaPods installed.

So no, it's not necessary.  You should be able to release an iOS app with a flutter module without those instructions if everyone on the team has `flutter` installed, and the host app is using CocoaPods.

> I just posted #42458 saying that we are having problems to generate a build in release.

I just commented in that issue, let's discuss there.

**Comment by BernardGatt** [comment]
Did you manage to replicate the issue @jmagman? Is there anything else I can try from my end?

**Comment by BernardGatt** [comment]
After looking at the device log I narrowed it down to the fact that all the exported Pod frameworks are missing the Info.plist file. Once I created the Info.plist file in each framework (with the correct CFBundleName & CFBundleExecutable) the app was able to be installed and run successfully on the device.

While going down this rabbit hole I noticed that even when building flutter using the --no-simulator flag it embeds a x86_64 into the Flutter.framework. For testing we should be fine but eventually when bundling for the app store we will have issues.

I'll post an updated build script later this eve.

**Comment by BernardGatt** [comment]
Running the below script as a build step within your project should generate the proper frameworks but as I mentioned above, without embedding an Info.plist you'll get the ```Install claimed to have succeeded, but application could not be found on device.``` error.

Since we're extracting the frameworks from Cocoapods the only way I see around this is to generate an Info.plist together with the plugin frameworks.

```sh
FrameworkDir=$PROJECT_DIR/Frameworks

cd ../your-flutter-project
flutter clean

flutter build ios --debug --no-simulator

cp -R .ios/Flutter/engine/Flutter.framework $FrameworkDir
cp -R .ios/Flutter/App.framework $FrameworkDir

mv build/ios/Debug-iphoneos/**/*.framework $FrameworkDir
cd $FrameworkDir
rm -rf Pods.build/ Debug-iphoneos/ XCBuildData/ Pods_Runner.framework
```

**Comment by BernardGatt** [comment]
To avoid having to rebuild every time you test on device / simulator, I updated the script to start using the new xcframeworks feature in XCode 11.

```sh
FrameworksDir=$PWD/Flutter

flutter clean

# Build for release
flutter build ios --release --no-simulator

# Copy release flutter frameworks in dependencies directory
cp -R .ios/Flutter/engine/Flutter.framework $FrameworksDir
cp -R .ios/Flutter/App.framework $FrameworksDir

# Build for debug
flutter build ios --debug --simulator --no-codesign

# Move release plugins into dependencies directory
mv build/ios/Release-iphoneos/**/*.framework $FrameworksDir

# Move debug plugins into dependencies directory
mkdir $FrameworksDir/debug
mv build/ios/Debug-iphonesimulator/**/*.framework $FrameworksDir/debug

# Copy debug flutter frameworks in dependencies directory
cp -R .ios/Flutter/engine/Flutter.framework $FrameworksDir/debug
cp -R .ios/Flutter/App.framework $FrameworksDir/debug

# Clean up
cd $FrameworksDir
rm -rf Pods.build/ Debug-iphoneos/ XCBuildData/ Pods_Runner.framework

# Removing extra architectures from flutter frameworks
lipo -remove x86_64 $FrameworksDir/Flutter.framework/Flutter -o $FrameworksDir/Flutter.framework/Flutter
lipo -remove armv7 $FrameworksDir/debug/Flutter.framework/Flutter -o $FrameworksDir/debug/Flutter.framework/Flutter
lipo -remove arm64 $FrameworksDir/debug/Flutter.framework/Flutter -o $FrameworksDir/debug/Flutter.framework/Flutter

# Create xcframeworks of all dependencies
xcodebuild -create-xcframework -framework $FrameworksDir/debug/Flutter.framework -framework $FrameworksDir/Flutter.framework -output $FrameworksDir/Flutter.xcframework
xcodebuild -create-xcframework -framework $FrameworksDir/debug/App.framework -framework $FrameworksDir/App.framework -output $FrameworksDir/App.xcframework
xcodebuild -create-xcframework -framework $FrameworksDir/debug/FlutterPluginRegistrant.framework -framework $FrameworksDir/FlutterPluginRegistrant.framework -output $FrameworksDir/FlutterPluginRegistrant.xcframework

# Add any flutter plugins below
xcodebuild -create-xcframework -framework $FrameworksDir/debug/shared_preferences.framework -framework $FrameworksDir/shared_preferences.framework -output $FrameworksDir/shared_preferences.xcframework
```

**Comment by jmagman** [comment]
> To avoid having to rebuild every time you test on device / simulator, I updated the script to start using the new xcframeworks feature in XCode 11.

Some of my experimentation with this a few months ago:
https://github.com/jmagman/flutter/blob/assemble-framework/packages/flutter_tools/lib/src/commands/build_framework.dart#L173

**Comment by jmagman** [comment]
> After looking at the device log I narrowed it down to the fact that all the exported Pod frameworks are missing the Info.plist file.

Hm I'm not seeing that, there are Info.plists in the App.framework, Flutter.framework, and al the exported plugin pod frameworks:
```
$ cd .ios/Pods/
$ xcrun xcodebuild -alltargets -sdk iphoneos -configuration Release ONLY_ACTIVE_ARCH=NO SYMROOT="${HOME}/Desktop/flutter_module_frameworks"
$ plutil -p  ${HOME}/Desktop/flutter_module_frameworks/path_provider.framework/Info.plist
{
  "BuildMachineOSBuild" => "18G87"
  "CFBundleDevelopmentRegion" => "en"
  "CFBundleExecutable" => "path_provider"
  "CFBundleIdentifier" => "org.cocoapods.path-provider"
  "CFBundleInfoDictionaryVersion" => "6.0"
  "CFBundleName" => "path_provider"
  "CFBundlePackageType" => "FMWK"
  "CFBundleShortVersionString" => "0.0.1"
  "CFBundleSignature" => "????"
  "CFBundleSupportedPlatforms" => [
    0 => "iPhoneOS"
  ]
  "CFBundleVersion" => "1"
  "DTCompiler" => "com.apple.compilers.llvm.clang.1_0"
  "DTPlatformBuild" => "17A566"
  "DTPlatformName" => "iphoneos"
  "DTPlatformVersion" => "13.0"
  "DTSDKBuild" => "17A566"
  "DTSDKName" => "iphoneos13.0"
  "DTXcode" => "1100"
  "DTXcodeBuild" => "11A419c"
  "MinimumOSVersion" => "8.0"
  "UIDeviceFamily" => [
    0 => 1
    1 => 2
  ]
}
```

**Comment by jmagman** [comment]
My .ios/Podfile:
```ruby
platform :ios, '8.0'

flutter_application_path = '../'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

use_frameworks!

target 'Runner' do
  install_flutter_engine_pod
  install_flutter_plugin_pods flutter_application_path
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Aggregate targets do not have a headers build phase.
    if target.respond_to?('headers_build_phase')
      target.headers_build_phase.files.each do |file|
        # Make headers public so they can be imported by the host application.
        file.settings = { 'ATTRIBUTES' => ['Public'] }
      end
    end
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true
```

@BernardGatt 
1. What is
```
$ cat .ios/Podfile
```
2. What exact `xcrun xcodebuild -alltargets` commands are you running to get the plugin frameworks?
3. What is
```
find $PWD/Flutter -name "Info.plist"
```

**Comment by BernardGatt** [comment]
> Hm I'm not seeing that, there are Info.plists in the App.framework, Flutter.framework, and all the exported plugin pod frameworks:

I just re-ran the command and you're right. The Info.plist is included in the `Release` config as well. Not sure exactly why that issue happened in the first place (this was one of the first things I did since upgraded to Catalina ...  could be related). But for some weird reason the Info.plist was not present in the Release config.

**Comment by jmagman** [comment]
So with the original script (ignoring your xcframework changes) are you still seeing the code signing issues?

**Comment by BernardGatt** [comment]
Haven't tested with the original script but it should work now, that was the only issue I had after upgrading.

**Comment by BernardGatt** [comment]
> > To avoid having to rebuild every time you test on device / simulator, I updated the script to start using the new xcframeworks feature in XCode 11.
> 
> Some of my experimentation with this a few months ago:
> https://github.com/jmagman/flutter/blob/assemble-framework/packages/flutter_tools/lib/src/commands/build_framework.dart#L173

I'll definitely check this out.

FYI i'm embedding everything (flutter, app, plugins) into one .framework file and distributing it via a pod. Apart from having to sign the internal frameworks in the app (which is understandable) everything works fine.

**Comment by jmagman** [comment]
> FYI i'm embedding everything (flutter, app, plugins) into one .framework file and distributing it via a pod. Apart from having to sign the internal frameworks in the app (which is understandable) everything works fine.

Great to hear!  How are you combining it into one .framework?

When I do https://github.com/flutter/flutter/issues/36968 I will include a xcframework flag for the simulator/real device use-case.

Going to close this since the Info.plist issue seems resolved.  Thanks for all your investigation and experimentation!

**Comment by BernardGatt** [comment]
> Great to hear! How are you combining it into one .framework?
Technically the dependencies (flutter, app, plugins) are still dependencies within this framework but it makes it a lot easier for the end user to integrate my framework (which is just 1 pod)

> When I do #36968 I will include a xcframework flag for the simulator/real device use-case.
🏅

**Comment by jmagman** [comment]
> Technically the dependencies (flutter, app, plugins) are still dependencies within this framework but it makes it a lot easier for the end user to integrate my framework (which is just 1 pod)

Gotcha, thanks for the info.
