### ISSUE TITLE
Tool crash in setupPodfile, missing directory flutter/packages/flutter_tools/templates/cocoapods

### ISSUE THREAD

**Issue by martidoke** [flutter/flutter#42477]
I'm using Android Studio and when I try to run my code, I get an error in the console stating Flutter has quit unexpectedly.

**Comment by jonahwilliams** [comment]
Can you post that error? (and if it is working, flutter doctor)

**Comment by martidoke** [comment]
Flutter Doctor:

/Users/martidoke/Developer/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/martidoke/Developer/flutter
    • Framework revision 2d2a1ffec9 (5 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/martidoke/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
Process finished with exit code 0

Error:

/Users/martidoke/Developer/flutter/bin/flutter --no-color packages get
Running "flutter pub get" in xylophone-flutter...                   0.9s

Sending crash report to Google.
Oops; flutter has exited unexpectedly.
Crash report sent (report ID: 0723dfaa3fe85e71)
Crash report written to /Users/martidoke/AndroidStudioProjects/xylophone-flutter/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
Process finished with exit code 1

Note- I have tried running pod setup for cocoapods and nothing happens.

**Comment by jonahwilliams** [comment]
We need the contents of

```
Crash report written to /Users/martidoke/AndroidStudioProjects/xylophone-flutter/flutter_01.log
```

**Comment by martidoke** [comment]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color packages get

## exception

FileSystemException: FileSystemException: Cannot copy file to '/Users/martidoke/AndroidStudioProjects/xylophone-flutter/ios/Podfile', path = '/Users/martidoke/Developer/flutter/packages/flutter_tools/templates/cocoapods/Podfile-ios-objc' (OS Error: No such file or directory, errno = 2)

```
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.copySync (dart:io/file_impl.dart:348:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      CocoaPods.setupPodfile (package:flutter_tools/src/macos/cocoapods.dart:211:23)
#4      injectPlugins (package:flutter_tools/src/plugins.dart:374:17)
<asynchronous suspension>
#5      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:213:11)
<asynchronous suspension>
#6      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:129:23)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#17     PackagesGetCommand.usageValues (package:flutter_tools/src/commands/packages.dart)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#24     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#25     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/martidoke/Developer/flutter
    • Framework revision 2d2a1ffec9 (5 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/martidoke/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by jonahwilliams** [comment]
Thank you!

**Comment by jmagman** [comment]
Does `/Users/martidoke/Developer/flutter/packages/flutter_tools/templates/cocoapods/Podfile-ios-objc` exist?

**Comment by martidoke** [comment]
No. I was able to address the two flutter doctor issues, however.

**Comment by jmagman** [comment]
Does `/Users/martidoke/Developer/flutter/packages/flutter_tools/templates/cocoapods/` exist?  
If not, does `/Users/martidoke/Developer/flutter/packages/flutter_tools/templates/` exist?  etc. Where up the directory tree does it start existing?

**Comment by martidoke** [comment]
/Users/martidoke/Developer/flutter/packages/flutter_tools/templates/ is where it ends

**Comment by jmagman** [comment]
Hm, that file exists for me when I check out v1.9.1+hotfix.2.  Not sure how your install could have become corrupted.

Can we get:
```
ls -la /Users/martidoke/Developer/flutter/packages/flutter_tools/templates/
```

> Note- I have tried running pod setup for cocoapods and nothing happens.

You may be hitting https://github.com/flutter/flutter/issues/41253.

**Comment by martidoke** [comment]
I was originally having a difficult time getting cocoapods 1.8.0 to initialize so I did follow along with #41253 to get it up and running. 

This is what I get when I run the command above.

`Martis-MacBook-Pro:~ martidoke$ ls -la /Users/martidoke/Developer/flutter/packages/flutter_tools/templates/
total 16
drwxr-xr-x@  8 martidoke  staff   256 Oct 10 15:46 .
drwxr-xr-x@ 22 martidoke  staff   704 Oct 10 19:02 ..
-rw-r--r--@  1 martidoke  staff  6148 Oct 10 19:02 .DS_Store
drwxr-xr-x@ 17 martidoke  staff   544 Sep 22 10:17 app
drwxr-xr-x@  3 martidoke  staff    96 Sep 22 10:17 driver
drwxr-xr-x@  6 martidoke  staff   192 Oct 10 15:47 module
drwxr-xr-x@ 12 martidoke  staff   384 Sep 22 10:17 package
drwxr-xr-x@ 18 martidoke  staff   576 Sep 22 10:17 plugin`

**Comment by jmagman** [comment]
So weird, you are only missing the `cocoapods` directory.  Is it possible you accidentally deleted that directory in the process of working with https://github.com/flutter/flutter/issues/41253?

**Comment by martidoke** [comment]
I could have but I do not recall digging that deep into my directory tree. Would there be a workaround to get all the files that would have been in the cocoapods directory?

**Comment by jmagman** [comment]
I'm concerned you lost that directory, but I'm not sure how.  We'll see if we hit more reports of this.
```shell
cd /Users/martidoke/Developer/flutter/
git checkout v1.9.1+hotfix.2 -- packages/flutter_tools/templates/cocoapods
```
Please let us know if this reoccurs.

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
