### ISSUE TITLE
Platform brightness in IOS

### ISSUE THREAD

**Issue by vy0592** [flutter/flutter#42473]
MediaQuery.of(context).brightness is still returning Brightness.light when dark appearance is selected in system display & brightness settings. 

The system is IOS 13.1

**Comment by LongCatIsLooong** [comment]
Could you paste the output of `flutter doctor -v` here?

**Comment by TheJulianJES** [comment]
I think you need platformBrightness?

**Comment by vy0592** [comment]
> I think you need platformBrightness?

Sorry that was a typo. I meant MediaQuery.of(context).platformBrightness

**Comment by TheJulianJES** [comment]
Can you post the output of ``flutter doctor -v``?

**Comment by vy0592** [comment]
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G87, locale
    en-US)
    • Flutter version 1.9.1+hotfix.4 at /Users/yuezhu/downloads/flutter
    • Framework revision cc949a8e8b (2 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[!] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Users/yuezhu/Downloads/Xcode-beta.app/Contents/Developer
    • Xcode 11.0, Build version 11M336w
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
        pod setup

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).

[✓] Connected device (1 available)
    • Tea’s iPhone • d0512fed2740e9ea41ba180667faa85b1538892c • ios • iOS 13.1

! Doctor found issues in 3 categories.

Development is usually not done on this machine though

**Comment by LongCatIsLooong** [comment]
Hmm the relevant changes should be there since v1.9.0. I tested on iOS 13.2 simulator and it was working for me:
```dart
import 'package:flutter/cupertino.dart';

void main() {
  runApp(
    CupertinoApp(
      home: Builder(builder: (BuildContext context) {
        print(MediaQuery.of(context).platformBrightness);
        return SizedBox();
      }),
    ),
    );
} 
```
Could you either post a minimal repro, or try this code snippet in your setup and see if it gives the correct `Brightness`?

**Comment by TheJulianJES** [comment]
Was just doing doing the same - it's also working on a physical iOS 13.2 + 13.1.2 (iPhone X) for me.
But also in the simulator for iOS 13.1 using ``Flutter version 1.9.1+hotfix.4``.

**Comment by vy0592** [comment]
Oh the 1.91 version is not the development version I used

The development version I used is below: 
[✓] Flutter (Channel google3, vnull, on Linux, locale en_US.UTF-8)
    • Flutter version null at //third_party/dart/flutter
    • Framework revision 1946fc4da0 (7 days ago), 2019-10-07T00:00:00.000
    • Engine revision 1d62160fdb
    • Dart version d6c6d12ebf

**Comment by LongCatIsLooong** [comment]
The issue is resolved offline.
