### ISSUE TITLE
Flutter : Flutter Emulator Can't open Camera.

### ISSUE THREAD

**Issue by zgramming** [flutter/flutter#42488]
I'm trying test my App with Emulator Device. I'm already use 3 different Emulator (Nexus,Google Pixel 2 and Flutter_emulator:5554).
![emulator](https://user-images.githubusercontent.com/38829404/66616997-52357880-ebfd-11e9-9647-4430ddd2d5a2.gif)
 If open camera at Nexus and Google Pixel,it's working fine. But every try open camera in Flutter_emulator , camera crash with pop up **Camera Keeps Stopping**.
In Console Message, not show me any Error.

**Comment by orestesgaolin** [comment]
You can't access camera on the iOS simulator. See explanation [here](https://stackoverflow.com/questions/25486080/how-to-access-ios-simulator-camera).
