### ISSUE TITLE
Navigator - add access to route stack

### ISSUE THREAD

**Issue by hlemcke** [flutter/flutter#42493]
To be able to reuse already opened pages, access to the Navigator stack would be helpful. For example:

int depth = peek( String namedRoute ); // Returns -1 if 'namedRoute' not in stack. Returns [0..n] if found

boolean found = remove( String namedRoute ); // 'true' if found and removed from stack

Method 'remove' would help in reusing routes. The removed route can be pushed again.

**Comment by goderbauer** [comment]
You will be able to manage the route stack yourself with the new Navigator/Router proposed in https://flutter.dev/go/navigator-with-router.

**Comment by goderbauer** [comment]
If you need this you can now use the routing API.
