### ISSUE TITLE
API to assist with "pull down to refresh" pattern

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#425]
Mobile apps today have a common pattern: the user pulls down to refresh the current page's contents. We could look to expose an API (or at least, an example) that can help developers implement this pattern.

**Comment by HansMuller** [comment]
http://www.google.com/design/spec/patterns/swipe-to-refresh.html

> Swipe to refresh is a swipe gesture available at the beginning of lists, grid lists, and card collections where the most recent content appears (Index 0).

> Typically, this gesture is available at the top of content collections, but it can also be at the bottom (for example, in chat applications).

**Comment by sethladd** [comment]
I think we can close this. @HansMuller is adding pull-to-refresh in https://github.com/flutter/flutter/issues/1595
