### ISSUE TITLE
RichText Support RelativeSize TextSpan

### ISSUE THREAD

**Issue by v7lin** [flutter/flutter#42500]

**Comment by goderbauer** [comment]
Please provide additional details in the body of the issue as indicated by the template. I am going to close this.

**Comment by v7lin** [comment]
我需要Flutter SelectionText支持类似Android的RelativeSizeSpan、AlignmentSpan、LeadingMarginSpan、SuperscriptSpan、SubscriptSpan等丰富的Span来更好的解析Html

--- translate by google ---

I need Flutter SelectionText to support Android-like RelativeSizeSpan, AlignmentSpan, LeadingMarginSpan, SuperscriptSpan, SubscriptSpan and other rich Span to convert Html.
