### ISSUE TITLE
Stuck at gradlew.bat(app:properties)

### ISSUE THREAD

**Issue by imuzairali** [flutter/flutter#42505]
First, my system was stucking on initializing graddle on (flutter run) then I used (flutter run -v) for running the application now my process is stucking in bwtlew.bat I have no idea what to do with this. Please help

**Comment by BondarenkoStas** [comment]
Please try `flutter clean`. Where exactly it stucks, what's the output?

**Comment by imuzairali** [comment]
Actually it takes too much time while running this (flutter run) command. On this command the output I get is normal but time is the problem which it takes too much. And when I run (flutter run -v ), it doesn't take that much time on (initializing graddle) but then getting stuck on bwtlew.bat

**Comment by jonahwilliams** [comment]
This bug as filled is not actionable, so I'm closing it. We always need full logs and flutter doctor -v. In this case, gradle might have been downloading files slowly, but it is impossible to tell
