### ISSUE TITLE
Image doesn't show when the picture is too big

### ISSUE THREAD

**Issue by qylshy** [flutter/flutter#42517]
## Steps to Reproduce

1.  Image widget to display a local picture file doesn't show , this picture is about 13m
the device info:  model is Che1-CL20, android version 4.4.4, RAM 2.0G
flutter version: Flutter (Channel beta, v1.7.8+hotfix.3)

the pic file load success but doesn't draw on the screen,  maybe the pic is too large?  flutter limit the pic size ?

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs
no any error log

```
```

```
```

```
```

**Comment by BondarenkoStas** [comment]
@qylshy I think it's a duplication of https://github.com/flutter/flutter/issues/41749. If you disagree, please comment and I will re-open the issue.
