### ISSUE TITLE
flutter upgrade stuck

### ISSUE THREAD

**Issue by RainSnowSnow** [flutter/flutter#42516]
problem
PS D:\flutter\vedioapp> flutter upgrade
Upgrading Flutter from D:\flutter\flutter_windows_v1.5.4-hotfix.2-stable\flutter...

why  is it keeping this

**Comment by jmagman** [comment]
What is the issue you are seeing?  How is the upgrade failing?

**Comment by RainSnowSnow** [comment]
When I execute flutter upgrade, the program will remain: "Upgrading Flutter from D:\flutter\flutter_windows_v1.5.4-hotfix.2-stable\flutter..."

**Comment by jonahwilliams** [comment]
Its not really clear from looking at this whether there is actually a bug here or if it is just taking a long time to download. We should consider what diagnostics could help us accurately diagnose a problem with this script

**Comment by AndreKelvin** [comment]
am having the same problem, any solving yet?
