### ISSUE TITLE
MainActivity.kt: (1, 9): Package name must be a '.'-separated identifier list

### ISSUE THREAD

**Issue by adityakmr7** [flutter/flutter#42519]
After running `flutter upgrade ` I created fresh new project. Project is created fine. But when i run the app I get this error see the log.

I used to Android studio to create flutter project.

## Error Logs

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
e: C:\Users\adity\Desktop\flutter-app\todoye\android\app\src\main\kotlin\in\aditya\todoye\MainActivity.kt: (1, 9): Package name must be a '.'-separated identifier list

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 27s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

# Result `flutter doctor -v  `

```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.418], locale en-IN)
    • Flutter version 1.9.1+hotfix.4 at C:\Users\adity\Desktop\flutter
    • Framework revision cc949a8e8b (2 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\adity\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.39.1)
    • VS Code at C:\Users\adity\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by ened** [comment]
@adityakmr7 hi! 
How did you create the project, please - what was the exact command?
Can you please share the contents of `MainActivity.kt` here?

**Comment by adityakmr7** [comment]
I did not know the content of  `MainActivity.kt`.  I opened  `android-studio` and selected `create new flutter project `. It did create the project but while running on an emulator I got this issue.

**Comment by hargange** [comment]
I have recently verified that it is assuming the domain to be .com only, since @adityakmr7 has a .in one, the error appeared. In my case it is .co.in domain. I got same error. When I changed it to .com it worked. My question is this an enforcement to use .com domain or this is a bug?

**Comment by BondarenkoStas** [comment]
@adityakmr7 what the company domain did you use? As @hargange mentioned, the error will pop up while using built in kotlin keywords (if you included kotlin support), as described in https://github.com/flutter/flutter/issues/16521.

**Comment by adityakmr7** [comment]
I use .in domain. and looks like this is problem with android studio. although it works fine in vscode.

**Comment by chetan2469** [comment]
do not put .in as domain, use any keyword like .dev .abc .com

**Comment by hargange** [comment]
as a work around, with reference to guidelines given on oracle website, I
have used package name in_.co.mydomain.package and it works without any
issues.

**Comment by gim-** [comment]
This happens because `in`, `is`, and `as` are keywords in Kotlin. The right solution is to declare package name like this in a source file:
```kotlin
package `in`.co.mydomain.package
```
Just wrap a keyword in backticks so that compiler knows it should be interpreted as a name instead of a keyword.

**Comment by positrix** [comment]
changing my package name from in.mydomain.package to in_.mydomain.package worked for me. Does anyone know whether this kind of naming works on app stores?

**Comment by savik19** [comment]
Tried a lot but didn't got any solution..

e: C:\Users\DELL\Desktop\savi\projects\fun\android\app\src\main\kotlin\com\example\fun\MainActivity.kt: (1, 21): Package name must be a '.'-separated identifier list

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
