### ISSUE TITLE
report ID: 042cf63ab8227fe6

### ISSUE THREAD

**Issue by Mojeeb2Alshoaibi** [flutter/flutter#42525]
## Steps to Reproduce

1. ...i'm run the intellij IDE Editor and download flutter and dart plugin but when I execute flutter command in cmd there is problem appear 
2.the proplem is : flutter has exited unexpectedly.
Crash report sent (report ID: be7f8a9dcc0713ac)
Crash report written to C:\flutter\flutter_04.log;
3. ...

## Logs

```
```

```
```

**Comment by ketanm** [comment]
Hi @Mojeeb2Alshoaibi 

People here don't have access to those reports. It will be useful if you share the actual log that was written or try to debug yourself. Your message shows log is at - C:\flutter\flutter_04.log

Also if it is not a flutter issue then post it ton StackOverflow for better response.

Ketan

**Comment by Mojeeb2Alshoaibi** [comment]
Ok !
thanks

في 6:35 pm جمعة 11‏/10‏/2019، كتب ketanm <notifications@github.com>:

**Comment by jmagman** [comment]
Also please include the output of `flutter doctor -v`.

**Comment by Mojeeb2Alshoaibi** [comment]
i solves this proplem yet !
the problem was in the sdk folder !
it's not uploaded correctly!

في 9:27 pm جمعة 11‏/10‏/2019، كتب Jenn Magder <notifications@github.com>:
