### ISSUE TITLE
CupertinoTimerPicker layout issues on iOS when using as widget

### ISSUE THREAD

**Issue by ro6520wa** [flutter/flutter#42520]
The CupertinoTimerPicker gives me layout issues on iOS when using it as a Widget. Some numbers don't display correctly and some are not in-line with the others. Only happens on iOS, both 12 and 13. Also happens in Simulator and on a real device. It looks completely fine on Android though. There are no apparent layout issues being logged. The widget is nested inside an Expanded widget, which itself is nested inside a Column.
<img width="365" alt="Screenshot 2019-10-11 at 12 35 45" src="https://user-images.githubusercontent.com/23655929/66645593-2da0c700-ec24-11e9-82a6-f9993dedb80c.png">

**Comment by LongCatIsLooong** [comment]
This is a dup of https://github.com/flutter/flutter/issues/36112. Please see the last comment in that issue for the earliest version that has the fix.
