### ISSUE TITLE
macOS Catalina giving OS Error: Permission denied, errno = 13 when <pub get>

### ISSUE THREAD

**Issue by truonghoangduy** [flutter/flutter#42532]
[flutter_02.log](https://github.com/flutter/flutter/files/3718546/flutter_02.log)

**Comment by jmagman** [comment]
FileSystemException: FileSystemException: Cannot open file, path = '<path>/flutter/clone/flaguru/.flutter-plugins' (OS Error: Permission denied, errno = 13)

**Comment by jmagman** [comment]
Does your user have permissions to edit that file?
```
$ ls -la /Users/hoangduy/Desktop/University/CNTT 192A/flutter/clone/flaguru/.flutter-plugins
```

**Comment by truonghoangduy** [comment]
I did a video how to fix it hope it will help some are new with flutter like me.
Go Flutter !!!
Link : https://www.youtube.com/watch?v=L98Y0UT8wuQ

**Comment by truonghoangduy** [comment]
I did a video how to fix it hope it will help some are new with flutter like me.
Go Flutter !!!
Link : https://www.youtube.com/watch?v=L98Y0UT8wuQ&feature=youtu.be&fbclid=IwAR3rVC_8wNMwSh8K8xNKnde5HqtaljRFsNsnBbXT5qL1LREb_qsmEu1Xgro

**Comment by jmagman** [comment]
That should have been fixed with https://github.com/flutter/flutter/issues/36714.

What's the output of `flutter doctor -v`?

**Comment by boyfox** [comment]
In output will be Http errors, can't download from pub repo. I changed pub repo server:
`export PUB_HOSTED_URL=https://pub.flutter-io.cn`
then works fine

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
