### ISSUE TITLE
flutter/engine Java files should be formatted

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#42534]
We run  [clang-format](https://github.com/flutter/engine/blob/master/ci/format.sh) on the engine already, but it looks like we're ignoring .java files. If we ran https://github.com/google/google-java-format on the engine during this step too we'd get consistency with the Java code like in the other languages in the engine and fix minor issues like unnecessary imports. We already do this in the plugins repo with [flutter_plugin_tools](https://github.com/flutter/plugin_tools/blob/master/lib/src/format_command.dart#L101-L107).

See also flutter/engine#13082.

/cc @dnfield @matthew-carroll

**Comment by mklim** [comment]
@cbracken just hit another snag related to this, it should theoretically be trivial to add in next to our existing `clang` linting so I'm going to give it a go.

**Comment by cbracken** [comment]
For issue searchability, the snag I hit is that we don't currently lint for unused imports.

**Comment by mklim** [comment]
Fixed by flutter/engine#16500 and flutter/engine#16501.
