### ISSUE TITLE
Cupertino Picker is blank/empty in Flutter Gallery example app on iPhone X running iOS 13.1.2 with Dark Mode settings.

### ISSUE THREAD

**Issue by d4manek** [flutter/flutter#42539]
Steps to reproduce:

1. On the iPhone, launch the Settings application, select Display & Brightness and choose Dark for the appearance.
2. Run the Flutter Gallery example application on an iPhone X with iOS 13.1.2.
3. Click on the Cupertino icon.
4. Click on the Pickers list item.
5. Click on any of the picker controls (e.g., Date and Time).
6. Notice that the picker comes up blank/empty.

My guess is that Dark mode is causing the picker to display white text on a white background, thus making it invisible. See attached screenshot.

![IMG_DEF882BBE2D5-1](https://user-images.githubusercontent.com/17515596/66674565-7060a000-ec20-11e9-9260-68683526af36.jpeg)

[flutter] flutter doctor -v
[✓] Flutter (Channel beta, v1.9.1+hotfix.4, on Mac OS X 10.15 19A583, locale en-US)
    • Flutter version 1.9.1+hotfix.4 at /Users/xxxxxxxx/Development/flutter
    • Framework revision cc949a8e8b (2 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxxxxxxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
exit code 0

**Comment by LongCatIsLooong** [comment]
Thanks for reporting this! This is a dup of https://github.com/flutter/flutter/issues/39685. Currently it's being blocked by https://github.com/flutter/flutter/issues/41654.
