### ISSUE TITLE
mac 10.15 系统下 无法打开“analysis_server.dart.snapshot”，因为无法验证开发者。("analysis_server.dart.snapshot" cannot be opened under mac 10.15 system because the developer could not be verified.)

### ISSUE THREAD

**Issue by wangyuuuu** [flutter/flutter#42562]
<img width="757" alt="截屏2019-10-12上午11 06 07" src="https://user-images.githubusercontent.com/10682137/66693905-96e61000-ece0-11e9-874a-a9a9c5e1a1b7.png">
 
运行Get dependencies时候

**Comment by BondarenkoStas** [comment]
@wangyuuuu It seems the same as https://github.com/flutter/flutter/issues/36714. The workaround  would be to disable Gatekeeper from the command-line with `sudo spctl --master-disable`. But before please provide you flutter doctor -v output.

**Comment by janmoppel** [comment]
Hello @wangyuuuu !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.

**Comment by qimingnan** [comment]
@wangyuuuu 
![image](https://user-images.githubusercontent.com/9545890/70974283-5e98ee80-20e2-11ea-896c-215d834dee03.png)
https://juejin.im/post/5dccd4186fb9a02b717ed3df这个链接，
