### ISSUE TITLE
flutter listview has low performance in flutter web,  low to 20fps only

### ISSUE THREAD

**Issue by 461882111zzy** [flutter/flutter#42568]
listview has low performance in flutter web,  low to 20fps only, when it runs in Android system Browser.

**Comment by BondarenkoStas** [comment]
@461882111zzy Please provide your flutter doctor -v output, your browser version, and the code example you run to test it.

**Comment by 461882111zzy** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.115, on Mac OS X 10.14.6
    18G95, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK 
    version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.39.1)
[✓] Connected device (3 available)

Browser version:
QQ Browser 9.7.1

Code:
   ListView(children: <Widget>[
      Image.network(src),
       Image.network(src),
        Image.network(src),
         Image.network(src),
          Image.network(src),
          ...
    ],);

**Comment by nt4f04uNd** [comment]
This problem might not be related to flutter, but to images itself if they are not compressed or have too big resolution

**Comment by lionoggo** [comment]
Actually, I think it has low performance in Android. Compared with Android native, we can clearly feel that the sliding is not smooth, why gpu thread cost a lot of time to render?

![image](https://user-images.githubusercontent.com/5570323/66885556-3a982e80-f007-11e9-808f-25328bffeb12.png)

**Comment by 461882111zzy** [comment]
Actually, The fps can reach to 40,  testing in both iphone6 , and Android Chrome browser.
But, the sliding is smooth when it uses DivElement, instead of ListView.

**Comment by LucasFoulonMongai** [comment]
The problem seems to be coming from `Image.network`.
It's slowing down the page a lot.

**Comment by ferhatb** [comment]
@461882111zzy Your project was using old package:flutter_web. Please move your project to use flutter (see http://flutter.dev/web). Steps: Change your pubspec.yaml , list your assets there (move assets under lib recommended). Rename your imports from flutter_web to package:flutter. Change Image.asset(...) urls. /examples/flutter_gallery is a great sample to look at.

We just landed image rendering speedup in master that should resolve your issue regarding resize speed as well. Make sure you test speed using flutter run -d chrome --release.

We ran your project to test but please reopen if you still see an issue on a particular device/version.
