### ISSUE TITLE
Flutter google maps is not working on iOS 13

### ISSUE THREAD

**Issue by ThebaultLouis** [flutter/flutter#42575]
Hello,

I have released my app on the App Store. But Google maps is not working for devices on iOS 13. It just a blank screen with no sign of Google. 
I am using `google_maps_flutter: ^0.5.19`.
In other devices (android or iOS on a version less than 13) the app is working well.

**Target Platform:** IOS
**devices:** physical devices on iOS 13

**Comment by zilijonas** [comment]
Please try these steps:
1. Go to `ios/` and run `pod update` - this will update GoogleMaps to the latest version.
2. Open your `pubspec.yaml` and try to change Google Maps dependency to `google_maps_flutter: ^0.5.21+7`.

**Comment by zilijonas** [comment]
> Hello,
> 
> I have released my app on the App Store. But Google maps is not working for devices on iOS 13. It just a blank screen with no sign of Google.
> I am using `google_maps_flutter: ^0.5.19`.
> In other devices (android or iOS on a version less than 13) the app is working well.
> 
> **Target Platform:** IOS
> **devices:** physical devices on iOS 13

Please try these steps:
1. Go to `ios/` and run `pod update` - this will update GoogleMaps to the latest version.
2. Open your `pubspec.yaml` and try to change Google Maps dependency to `google_maps_flutter: ^0.5.21+7`.
