### ISSUE TITLE
CircleAvatar jpeg图片无法显示为圆形 (CircleAvatar jpeg image cannot be displayed as a circle)

### ISSUE THREAD

**Issue by lpxiana** [flutter/flutter#42571]
```dart
CircleAvatar(
    child: Image.asset('lib/images/none.jpeg'),
    radius: 32.0,
),
```
他应该是个圆形，但是却显示了方形
(google translate)
He should be a circle, but it shows a square

**Comment by BondarenkoStas** [comment]
@lpxiana Please provide your flutter doctor -v output. does it display it in original form or doesn't display at all? Are there any errors when you run it with --verbose?

**Comment by Ranjit32** [comment]
Instead of this:

CircleAvatar(
    child: Image.asset('lib/images/none.jpeg'),
    radius: 32.0,
),
Use this:

CircleAvatar(
   backgroundImage: AssetImage('lib/images/none.jpeg'),
    
),

**Comment by BondarenkoStas** [comment]
https://api.flutter.dev/flutter/material/CircleAvatar-class.html
