### ISSUE TITLE
Execution failed for task ':app:compileFlutterBuildDebugX86'.

### ISSUE THREAD

**Issue by RainSnowSnow** [flutter/flutter#42573]
![image](https://user-images.githubusercontent.com/23568119/66699133-a08a6a80-ed16-11e9-94c5-b8e7689c4dc4.png)
what is problem?

**Comment by BondarenkoStas** [comment]
@RainSnowSnow do you a solid reason to stay with v1.5.4 or you may upgrade to the current stable? So far it's hard to guess what's the problem if it's such an old version.

**Comment by irfan203** [comment]
facing the same issue

**Comment by nhanquach** [comment]
I have the same issue too, after running
```flutter clean```
to remove the previous build, everything starts working again.

**Comment by RainSnowSnow** [comment]
thank you

**Comment by irfan203** [comment]
> I have the same issue too, after running
> `flutter clean`
> to remove the previous build, everything starts working again.

it doesnt work for me

**Comment by nhanquach** [comment]
> it doesnt work for me

I would love to help but I am no expert so may be if you can post the steps to reproduce the issue, it will be easier for everyone.

P/S: Did you run ```flutter clean``` while standing in your flutter app directory?

**Comment by BondarenkoStas** [comment]
@irfan203 Please provide your flutter doctor -v output.

**Comment by mrhmamun** [comment]
In my case i just upgraded my plugins & solved!

**Comment by bendywue** [comment]
Getting this problem
![Screen Shot 2020-02-02 at 3 18 22 PM](https://user-images.githubusercontent.com/59795528/73614695-73b4d880-45cf-11ea-8b35-5c73bd340bba.png)

any ideas?

**Comment by riyasyash** [comment]
@bendywue You have to run the command inside the Flutter project directory

**Comment by anushagarg-10** [comment]
> @bendywue You have to run the command inside the Flutter project directory

what does this mean?
