### ISSUE TITLE
RefreshIndicator missing stroke width?

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#42570]
`RefreshIndicator` doesn't have `strokeWidth` parameter, that `RefreshProgressIndicator`, which is used inside it, does

**Comment by vasilich6107** [comment]
@HansMuller @BondarenkoStas 
Hi. The PR for this issue is approved and waiting to be merged. Are there any issues that blocks the PR from merging?

**Comment by Piinks** [comment]
Hi @vasilich6107, I've updated the PR to hopefully get some progress here. :)

**Comment by AyushBherwani1998** [comment]
@Piinks can I send a new PR if no is working on this issue?

**Comment by Piinks** [comment]
> @Piinks can I send a new PR if no is working on this issue?

Sure thing! Feel free to ping me on it. :)

**Comment by AyushBherwani1998** [comment]
@Piinks I have sent a PR. Looking forward for your reviews.
