### ISSUE TITLE
Cupertino ShareIcon does not look very "Cupertino"

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#42587]
Internal: b/142328889

See share icon on Flutter vs iOS:

![image](https://user-images.githubusercontent.com/6687929/66705364-87fc5f00-ecda-11e9-89de-3f59011c102b.png)

The native iOS share icon has a smaller square with more rounded corners and a larger opening for the emerging arrow.

**Comment by HansMuller** [comment]
CC @willlarche

**Comment by willlarche** [comment]
I believe this was maybe changed recently. I'll begin the process of updating the icon with the artists first.

**Comment by willlarche** [comment]
Is this verified in all apps using the built-in share icon? No one else has identified it.

**Comment by chickenblood** [comment]
The Flutter Cupertino icon is here, Will https://github.com/flutter/cupertino_icons/blob/master/map.png. It's clearly different from the iOS native one.

**Comment by chickenblood** [comment]
Unless you meant native iOS apps using the built-in icon, in which case I can confirm the following apps off-the bat:
Photos
Notes
Apple Maps
Safari
Music
...etc ...etc
Even many of the Google iOS apps have a more similar icon, i.e. Maps, Search, News.

**Comment by xster** [comment]
I'm gonna merge into https://github.com/flutter/flutter/issues/19632
