### ISSUE TITLE
Why is MainAxisAlignment not aware of widget visibility?

### ISSUE THREAD

**Issue by FineTillYouCameAlong** [flutter/flutter#42581]
Say I have a widget like this:
```
Column(
  mainAxisAlignment: MainAxisAlignment.spaceAround,
  children: [
    Container(color: Colors.red, height: 80),
    Container(color: Colors.red, height: 80),
    Visibility(visible: false, child: Container(color: Colors.red, height: 80),),
    Container(color: Colors.red, height: 80),
  ]
)
```
the spacing between the widgets is not even because whatever aligns the elements in the column is not aware of one of the items being invisible.
[Screenshot of the problem](https://imgur.com/zKqBQZe)

It would be nice if this were fixed so I don't have to build the column items separately.

**Comment by TahaTesser** [comment]
Closing in favor other issue with more activity 
duplicate of [#56423](https://github.com/flutter/flutter/issues/56423)
