### ISSUE TITLE
flutter doctor is not realizing flutter.jar has been deleted

### ISSUE THREAD

**Issue by febs** [flutter/flutter#42583]
## Steps to Reproduce
Using Flutter in Linux.
1. Delete 
  $FLUTTER_SDK/bin/cache/artifacts/engine/android-arm/flutter.jar
2. Realize nothing will ever build again
3. Run flutter doctor hoping to fix the problem
4. See that flutter doctor is very happy nevertheless.

How to rebuild flutter.jar by the way? flutter upgrade won't work either.
Thankx,

**Comment by BondarenkoStas** [comment]
@febs did you try to delete whole cache folder? When you start to build something it recreated while `Downloading android-arm tools...`. 
btw, I tried it on mac, an apk was build with no errors without that flutter.jar.

**Comment by janmoppel** [comment]
Hello @febs !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
