### ISSUE TITLE
Flutter Crash  Report Cant Create App

### ISSUE THREAD

**Issue by RIPYTT** [flutter/flutter#42592]
https://github.com/flutter/flutter/issues/34543#issuecomment-541353781
[flutter_01.log](https://github.com/flutter/flutter/files/3721070/flutter_01.log)
![Annotation 2019-10-13 001437](https://user-images.githubusercontent.com/51709861/66706671-262a0c80-ed4f-11e9-83c7-f77c771690da.png)
These Folder only Created

**Comment by stuartmorgan** [comment]
According to your linked comment you have local changes to your flutter checkout; you seem to have modified your checkout to be in a bad state. We can't support configurations where you have modified the flutter tool.

The specific crash here indicates that your create.dart and supporting code it's older than the templates.

You need to stash or revert your changes and update again.
