### ISSUE TITLE
API to register, run, manage background tasks (e.g. background refresh)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#426]
Mobile platforms have a way for developers to register a task to run in the background. For example, performing syncing/refreshing operations.

This is a request for APIs and examples that show how to perform certain tasks like refreshing/syncing in the background.

**Comment by eseidelGoogle** [comment]
Seems very related to https://github.com/flutter/flutter/issues/3671.

**Comment by mit-mit** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/3671

**Comment by KVManpreetam** [comment]
> Closing in favor of #3671
Dear Micheal , We are early adopters of Flutter , we are using it for our IoT based apps. Part of our development we need to run a background job in the device to synchronise the data  from local storage to cloud for specific intervals . We didn't find the any libraries to support the background process in Flutter.
Please help us.

Regards
Preeetham
www.Indriyn.com
India

**Comment by eseidelGoogle** [comment]
Please see #3671 and https://github.com/flutter/flutter/issues/24278.  Would love to understand what your outstanding needs are.

https://pub.dartlang.org/packages/android_alarm_manager or https://pub.dartlang.org/packages/background_fetch may also be of help.
