### ISSUE TITLE
Use CupertinoNavigationBar after,middle not shown

### ISSUE THREAD

**Issue by WitheredSkull** [flutter/flutter#42607]
```dart
CupertinoNavigationBar(
          automaticallyImplyMiddle: true,
          automaticallyImplyLeading: true,
          middle: Text(
            title() != null ? title() : "",
            style: TextStyle(color: APP.AssetsColor.COLOR_PRIMARY),
          ),
          previousPageTitle: title(),
          trailing: Row(
            children: _getAppbarActions(),
          ),
        );
```

**Comment by janmoppel** [comment]
Hello @WitheredSkull !

Thank you for posting.
Can you please clarify, what is not shown on the navigation bar: the middle (page title) or icons?

Also, can you please provide the `flutter doctor -v` command output?

**Comment by janmoppel** [comment]
Hello @WitheredSkull !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
