### ISSUE TITLE
Validator doesn't work after TextEditController.clear() 

### ISSUE THREAD

**Issue by dafinoer** [flutter/flutter#42604]
I have  1 button for save and 1 button for clean. When I tap button `clear`, validator doesn't show message..

```dart
 Padding(
              padding: const EdgeInsets.symmetric(vertical: 16.0),
              child: TextFormField(
                controller: _editQTY,
                decoration: InputDecoration(
                  filled: false,
                  border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(10.0)),
                  labelText: 'Quantity',
                ),
                validator: (value) {
                  if(value.isEmpty){
                    return 'Please fill form';
                  }
                  return null;
                },
              ),
            ),
```

this is method `onTapClear()`
```dart
void onTapClear() {
    _editNSN.clear();
    _editSerial.clear();
    _editBatch.clear();
    _editQTY.clear();
    _editCardNo.clear();
    _editDate.clear();
    _editNote.clear();
}
```

this is method `save`
```dart
void onTapSave(){
 if(_keyForm.currentState.validate()){
   ....
}
}
```

**Comment by janmoppel** [comment]
Hello @dafinoer !

Thank you for posting an issue.
Can you please also provide the `flutter doctor -v` command output?

**Comment by janmoppel** [comment]
Hello @dafinoer !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
