### ISSUE TITLE
then is called before Navigator.push 

### ISSUE THREAD

**Issue by talhazzani** [flutter/flutter#42618]
## Steps to Reproduce

I'm trying to navigate to another screen then returning value from that screen and show it in the UI by using `setState`. However, I couldn't do so. So, while debugging I found out that `then` is called before the push function which is weird,

Here is a snippet from my code :
```dart
/// this the text filed I'm trying to bend the value to
TextFormField(
                        decoration: InputDecoration(
                          labelText: 'Address',
                        ),
                        initialValue: address,
                        enabled: false,
                        maxLines: 3,
                      ),
                    ),
                    SizedBox(
                        width: 20,
                        child: Material(
                          elevation: 4.0,
                          shape: CircleBorder(),
                          color: Colors.transparent,
                          child: GestureDetector(
                              onTap: () {


//// here is the weird part 
        //// then this 2                         Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                            builder: (context) =>
                                                GoogleMapsScreen()))
       this is called 1 >>>>>                            .then((onValue) {
                                  setState(() {
                                    this.address = onValue;

                                  });
                                });

```

Target OS is IOS
**iphone X:**

## Flutter doctor:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-SA)
    • Flutter version 1.9.1+hotfix.2 at /Users/turkialhazzani/Downloads/flutter
    • Framework revision 2d2a1ffec9 (5 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/turkialhazzani/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • turki’s iPhone • df074c0fef50b0d8730170634a5878a411ce1019 • ios • iOS 12.3.1

! Doctor found issues in 1 category.

```

**Comment by diego-lipinski-de-castro** [comment]
Here is how you can achieve what you need the right way
```
GestureDetector(
                    onTap: () async {
                      _address = await Navigator.of(context).push(
                          MaterialPageRoute(
                              builder: (context) => GoogleMapsScreen()));

                        setState(() {
                            this.address = _address;
                        });
                    },
                  )
```

**Comment by janmoppel** [comment]
Hello @talhazzani !

Thank you for posting an issue.
Can you please check whether the solution proposed by @diego-lipinski-de-castro works for you?

**Comment by talhazzani** [comment]
Hey @janmoppel  , @diego-lipinski-de-castro solution's worked to for getting the value but setState didn't update the UI,

Anyway can someone explained why" then " ran before the " push " method, I honestly think this s bug in flutter and must be addressed  

Any thoughts?

**Comment by diego-lipinski-de-castro** [comment]
That could be a thing, im not sure hows that supposed to work, i have never seen anyone do it that way, you can look at stackoverflow or something, maybe it happens when the push and the route builder are chained, to be honest im not even sure how the await works in this case, i just know it works lol

**Comment by talhazzani** [comment]
lol no issue @diego-lipinski-de-castro thank you for the help though

if anyone facing the same issue here is how I fixed it , 

used @diego-lipinski-de-castro suggestion to use await and async instead of .then.

For updating the UI , I added  controller for the form  

`  var txt = TextEditingController();
`
then just updating it ,

Here is snippet of the fixed code;

 

`   


           TextFormField(
                            decoration: InputDecoration(
                              labelText: 'Address',
                            ),
                            controller: txt,
                            enabled: false,
                            maxLines: 3,
                          ),
                        ),
                        SizedBox(
                            width: 20,
                            child: Material(
                              elevation: 4.0,
                              shape: CircleBorder(),
                              color: Colors.transparent,
                              child: GestureDetector(
                                  onTap: () async {
                                    var _address = await Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                            builder: (context) =>
                                                GoogleMapsScreen()));
                                    setState(() {
                                      this.address = _address;
                                      txt.text = _address;
                                    });
`
