### ISSUE TITLE
Latest Flutter Release (1.10.7): Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113

### ISSUE THREAD

**Issue by GrahamDi** [flutter/flutter#42610]
Hi,

I am getting the above failure when trying to load my app in debug mode onto an Huawei P Smart. I can neither side load the app nor install it by attaching directly. Prior to this Flutter release both methods were working fine and I used them daily.

The build works perfectly on the Android Emulator.
`• Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)`

I also notice that the debug .apk size is now around 25% smaller - was 42.5mb, now 33,7mb. This is pretty significant and makes me wonder what went missing :-) 
Anyway here is the VSCode Debug console output, `flutter doctor -v` output and an extract from `build.gradle` which has addressed this kind of issue previously.

### Debug Console:
```
Launching lib\main.dart on FIG LX1 in debug mode...
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.4\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.3.8\android\src\main\java\com\flutter_webview_plugin\WebviewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.1.6\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Built build\app\outputs\apk\debug\app-debug.apk.
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install F:\My_AppDev_Projects\sailor_boy\build\app\outputs\apk\app.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
Error launching application on FIG LX1.
Exited (sigterm)
```

### Flutter doctor -v:
```
flutter doctor -v
[√] Flutter (Channel beta, v1.10.7, on Microsoft Windows [Version 10.0.18999.1], locale en-GB)
    • Flutter version 1.10.7 at C:\flutter
    • Framework revision e70236e36c (11 days ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.4.0 1103600280)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at D:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.39.1)
    • VS Code at C:\Users\dicki\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • FIG LX1 • HBEDU18117010246 • android-arm64 • Android 9 (API 28)

• No issues found!
```

### <project>app/build.gradle - android block, default config:
```
        ndk {
                abiFilters 'armeabi-v7a', 'x86', 'armeabi'
        }
```

Hope you can help.

Thanks...

**Comment by amreniouinnovent** [comment]
@GrahamDi Could you add apk analyze from Android studio and expand jniLib and libs folder?

**Comment by GrahamDi** [comment]
Hi,
I don't see the folders you mention. Please advise where I should look. Here is the screen shot of what I see after running apk analyzer. There are no folders further down the view.
![Apk Analyzer](https://user-images.githubusercontent.com/32131440/66716544-236efc00-edcf-11e9-9f71-d6d15d93e082.jpg)

**Comment by amreniouinnovent** [comment]
@GrahamDi the lib folder is there on the screenshot second folder
do you get the issue on Huawei and the emulator both?

**Comment by GrahamDi** [comment]
@amreniouinnovent The emulator works fine with this build but when I transfer the apk file to the Huawei (via dropbox) or connect the Huawei directly and build for it, it fails to install ... with the message I show above when it is directly connected. I haven't tried adb logcat yet. Would that give more detail?

The screen shot with 'lib' folder fully expanded is below:

![Image 4](https://user-images.githubusercontent.com/32131440/66716736-9aa58f80-edd1-11e9-8885-872382ea716d.jpg)

Thanks for your assistance.

**Comment by amreniouinnovent** [comment]
@GrahamDi Huawei is 64bit while the emulator is 32bit
Either your run on Huawei or you make an apk from build menu whuch includes 64 and 32 bit flutter.so file

**Comment by GrahamDi** [comment]
@amreniouinnovent 

Ok, but my point is that this was ALL working perfectly until the upgrade of Flutter to 1.10.7...I have made NO other build changes or anything that could effect the build from outside.

Before the upgrade, I simply chose the flutter debug green arrow in VSCode and when the apk was built I could use it immediately on both the emulator AND my Huawei. Now I can't. Something has changed because of the new Flutter version.

Ok, so having said that, how do I now choose to build for my 64 bit Huawei or the emulator. Specifically, what gradle.build file changes do I need to make? Anything else?

Again thanks for your help but I reiterate...I was able to use the SAME apk on the emulator and my Huawei (and my Android Tab 7, and my Lenovo 10inch)...something has changed, man. Believe me.

**Comment by amreniouinnovent** [comment]
@GrahamDi I upgrade too and the app started but just stuck on the pre-app launcher activity
I think the new beta release has an issue

**Comment by GrahamDi** [comment]
Ok, cool. Thanks man. I am now out for dinner so will get back into it
tomorrow. Will chat again Cheers.

Krgrds, Graham

+27 84 798 6450

**Comment by amreniouinnovent** [comment]
@GrahamDi I switched to stable but I think new beta has an issue

**Comment by GrahamDi** [comment]
@amreniouinnovent I switched back to stable v1.9.1+hotfix.4 but no joy. The apk is back to the larger size it was and now will install on the device (although it takes a long while now) but crashes on opening it. Will have to check with adb logcat I guess. Think I'm gonna leave it for now and just use the emulator. Thanks for your help though.

**Comment by janmoppel** [comment]
Hello @GrahamDi !

Thank you for posting an issue.
It seems that similar behaviour was previously reported in these threads: #31579, #35166.

Can you please check, does any of the proposed solutions there work for you?

**Comment by GrahamDi** [comment]
@janmoppel Hi Jan, I had looked at those threads before posting. I don't use flavors in my app (yet) and  I have been using the build.gradle and gradle.properties for some months now. 

As I said previously, all was working just fine until I decided to upgrade to 1.10.7...and now I don't seem to be able to go back to a working version. It probably means I will have to create release versions to run on my device....which is a pain. So will have to stick with the emulator. Just means my other friends can't test the app with me. :-(

**Comment by amreniouinnovent** [comment]
@GrahamDi to help @janmoppel to support you
first, make flutter clean and build a new apk
then post here apk analyze with lib folder expanded here

**Comment by GrahamDi** [comment]
@janmoppel here is the information suggested by @amreniouinnovent . I also include flutter doctor -v. As I said above in this stable version of Flutter the apk builds and installs on my device but crashes on opening....which has happened before (months ago) but was fixed by the build.gradle ndk entry I show below. 
### Flutter doctor -v:
`flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18999.1], locale en-GB)
    • Flutter version 1.9.1+hotfix.4 at C:\flutter
    • Framework revision cc949a8e8b (2 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at D:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)        
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.39.1)
    • VS Code at C:\Users\dicki\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • FIG LX1                              • HBEDU18117010246 • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!`

### build.gradle ndk:
`        ndk {
            abiFilters 'armeabi-v7a', 'x86', 'armeabi'
        }
`

### APK Analyzer:
![2019-10-14](https://user-images.githubusercontent.com/32131440/66750736-832bdc80-ee8d-11e9-9c34-d775e0a748de.png)

**Comment by GrahamDi** [comment]
@janmoppel @amreniouinnovent 
I have found the reason why the app crashes on opening by running adb logcat. This gave me the following messages that relate to the crash:

> 10-14 10:42:17.424 18848 18848 E AndroidRuntime: FATAL EXCEPTION: main
10-14 10:42:17.424 18848 18848 E AndroidRuntime: Process: com.geedee.sailorboy, PID: 18848
10-14 10:42:17.424 18848 18848 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.geedee.sailorboy/com.geedee.sailorboy.MainActivity}: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization

This relates to a `WidgetsFlutterBinding.ensureInitialized();` statement that I inserted into main.dart (obviously in the wrong place) on recommendation from a Flutter error message that came up during my recent development work. I can't remember what the error was now unfortunately. Anyway, I have commented out the above statement and I can now run the app on my Huawei.

Please note the following though:

1. I cannot build for the Huawei directly whilst it is attached - I get the 'no matching abis' message. I can however, copy the apk to the device an install it normally there.
2. This is not the problem that I raised this  issue for. That was (and still is) that when building with Flutter v1.10.7 I got a much smaller apk and that apk would not install on my device but would run in the emulator. Yet nothing else had changed other than the upgrade, build.gradle and other configs were all the same as before the upgrade.

Anyway, I will now stay with the stable version of Flutter and continue my development and testing now that I can use my device again. Thanks for your assistance.

**Comment by amreniouinnovent** [comment]
@GrahamDi when you launch by Flutter it assumes it as 64bit mode while there is no flutter.so c++ file in arm 64 v8a folder
But when the apk launch standalone it uses 32bit instead of 64bit mode so it works on Huawei arm v8a
The question is do flutter use 64bit on debugging mode for a specific reason or it can convert mode to 32bit if armv8a is empty? @janmoppel

**Comment by GrahamDi** [comment]
@amreniouinnovent   Ah, ok. That makes sense. Let's see what Jan's response is.

**Comment by darshankawar** [comment]
@GrahamDi 
Is this still a valid issue using latest Flutter version ?

**Comment by GrahamDi** [comment]
@darshankawar  Thanks for the follow up. No, this is no longer an issue for me. Guess I should have closed it. Will do so now.
