### ISSUE TITLE
device_info - Instance of 'Future<dynamic>'

### ISSUE THREAD

**Issue by irperera** [flutter/flutter#42622]
Hey everyone,

i create a device.dart with

`class DeviceInfo {
  static final DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
  String deviceId;

  Future getDeviceInfo() async {
    try {
      if (Platform.isIOS) {
        IosDeviceInfo iosInfo = await deviceInfo.iosInfo;
        deviceId = iosInfo.identifierForVendor;
      } else if (Platform.isAndroid) {
        AndroidDeviceInfo androidInfo = await deviceInfo.androidInfo;
        deviceId = androidInfo.androidId;
      }
    } on PlatformException {}
    return deviceId;
  }
}`

and I call it from my main.dart with 
`final _deviceId = DeviceInfo().getDeviceInfo().toString();`

I get a deviceId = Instance of 'Future<dynamic>'

can someone help me fix this?

**Comment by diego-lipinski-de-castro** [comment]
you forgot the await keyword

```
final _deviceId = await DeviceInfo().getDeviceInfo().toString();
```

**Comment by nt4f04uNd** [comment]
This is a question for stackoverflow and about dart async/await basics, not flutter

**Comment by lwhile** [comment]
```dart
final _deviceId = (await DeviceInfo().getDeviceInfo()).toString();
```

**Comment by itachi0071998** [comment]
but we can use await only in async function right?
If I want to call this in statefulwidget then?

**Comment by nt4f04uNd** [comment]
@itachi0071998 
I don't know exactly where you want to call this, but here's example of calling async function in initState().
Again, this is not related to the package itself and it's a question for the StackOverflow, that has been asked a [million times](https://www.google.com/search?q=flutter+async+initstate&oq=flutter+async+initstate&aqs=chrome..69i57j0l2j69i64.3683j0j7&sourceid=chrome&ie=UTF-8) already.
```dart
class _SettingsRouteState extends State<SettingsRoute> {
  bool _devMode = false;
  String _appVersion = "";

  @override
  void initState() {
    super.initState();
    _fetch();
  }

  Future<void> _fetch() async {
    // Fetch dev mode
    _devMode = await Prefs.developerModeBool.getPref();
    _appVersion = (await PackageInfo.fromPlatform()).version;
    if (mounted) {
      setState(() {});
    }
  }
}
```
