### ISSUE TITLE
Image component does not render after using RenderRepaintBoundary truncation component(only occasionally)

### ISSUE THREAD

**Issue by xssxxssx** [flutter/flutter#42624]
```dart
RepaintBoundary(
          key: _boundaryKey,
          child: Material(
            child: Container(
              width: 220,
              height: 270.0,
              decoration: BoxDecoration(
                color: Color(0xFFF9F9F9)
              ),
              child: Center(
                child: Container(
                  width: 190,
                  height: 240.0,
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(6.0),
                    boxShadow: [
                      BoxShadow(color: Color(0xFFE9E9E9), offset: Offset(0, 0),
                        blurRadius: 5,
                      )
                    ]
                  ),
                  child: Column(
                    children: <Widget>[
                      Container(
                        width: 150.0,
                        height: 150.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(6.0),
                          image: DecorationImage(
                            image: MemoryImage(
                              widget.productBytes
                            )
                          )
                        ),
                        /* child: Center(
                          child:  /* Image.network(
                            widget.goodsData['productBigImage'],
                            width: 150.0,
                            height: 150.0,
                          ) *//* Image.memory(
                            widget.productBytes,
                            width: 150.0,
                            height: 150.0,
                          ) */
                        ), */
                      ),...
```
When cutting components：
```dart
    RenderRepaintBoundary boundary = _boundaryKey.currentContext.findRenderObject();
    ui.Image image = await boundary.toImage(pixelRatio: 4.0);
    ByteData byteData = await image.toByteData(format: ImageByteFormat.png);
    Uint8List pngBytes = byteData.buffer.asUint8List();
```
The cut out image sometimes does not display the Widget Image;

## flutter doctor -v:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.17134.1069], locale zh-CN)
    • Flutter version 1.9.1+hotfix.4 at D:\flutter
    • Framework revision cc949a8e8b (2 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\XS\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_SDK_ROOT = C:\Users\XS\AppData\Local\Android\Sdk
    • Java binary at: D:\Program Files\android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at D:\Program Files\android
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

• No issues found!
```

Normal：
![微信图片_20191014124431](https://user-images.githubusercontent.com/26585408/66729823-75bc2580-ee80-11e9-93a7-43ccd7f7f319.png)

Unusual：
![微信图片_20191014124437](https://user-images.githubusercontent.com/26585408/66729829-7ce33380-ee80-11e9-80c2-fe84ceec9f8f.png)

**Comment by janmoppel** [comment]
Hello @xssxxssx !

Thank you for posting an issue.
Can you please provide the full `flutter doctor -v` command output?

Also, we've translated this issue's description into English using Google Translate. If you're comfortable writing in English, please check the translation and update it if necessary.

Thank you.

**Comment by goderbauer** [comment]
Can you please also post some runnable code that reproduces the issue?

**Comment by xssxxssx** [comment]
flutter doctor -v：
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.17134.1069], locale zh-CN)
    • Flutter version 1.9.1+hotfix.5 at D:\flutter
    • Framework revision 1aedbb1835 (4 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\XS\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_SDK_ROOT = C:\Users\XS\AppData\Local\Android\Sdk
    • Java binary at: D:\Program Files\android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at D:\Program Files\android
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • SM G9250 • 05157df5656f3214 • android-arm64 • Android 7.0 (API 24)

• No issues found!

**Comment by justForL** [comment]
@xssxxssx bro,did you find out the way to fix this bug?
