### ISSUE TITLE
RadioListTile Theme Property for selected

### ISSUE THREAD

**Issue by workerbee22** [flutter/flutter#42621]
When using **RadioListTile** it uses a radio Button. But **activeColor** property doc for this widget says uses the Theme **accentColor** property by default. Which I think is true.

But if you use **controlAffinity** property of **RadioListTile** to put radio button to right side, then the color of the selected item in the list follows the **RadioButton** **activeColor** property which defaults to the theme **toggleableActiveColor** property.

Expected behaviour, both widgets **RadioListTile** and **RadioButton** to use the same consistent theme property when no color is provided.

**Comment by janmoppel** [comment]
Hello @workerbee22 !

Thank you for posting an issue.
Can you please also provide the `flutter doctor -v` output?

**Comment by workerbee22** [comment]
```
flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale en-AU)
    • Flutter version 1.9.1+hotfix.4 at /Users/gamma/Documents/flutter
    • Framework revision cc949a8e8b (2 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gamma/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/gamma/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 3.5 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • Nexus 6P                  • CVH7N15A17000241 • android-arm64 • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 10 (API 29) (emulator)

• No issues found!
gamma (master *) flutterio_2018 $ 
```

**Comment by AyushBherwani1998** [comment]
> When using **RadioListTile** it uses a radio Button. But **activeColor** property doc for this widget says uses the Theme **accentColor** property by default. Which I think is true.
>

The doc surely mentions that the `activeColor` defaults to `Theme.accentColor`  which is not true, since only `ListTileTheme.selectedColor` is defaulted to the `Theme.accentColor` but `activeColor` for the `Radio` is never defaulted to `Theme.accentColor`.

https://github.com/flutter/flutter/blob/b041144f833e05cf463b8887fa12efdec9493488/packages/flutter/lib/src/material/radio_list_tile.dart#L436

https://github.com/flutter/flutter/blob/b041144f833e05cf463b8887fa12efdec9493488/packages/flutter/lib/src/material/radio_list_tile.dart#L419

>But if you use controlAffinity property of RadioListTile to put radio button to right side, then the color of the selected item in the list follows the RadioButton activeColor property which defaults to the theme toggleableActiveColor property.
>

Going through the source code, the `controlAffinity` won't matter here to change the `activeColor`, since the `ListTileTheme.selectedColor` doesn't apply on `Radio`.


The issue has reproducibile steps [here](https://gist.github.com/AyushBherwani1998/12483b8b9fffc2de063f17e82ae75739).

##### SS

<img src = "https://user-images.githubusercontent.com/34301187/84908974-c43a5780-b0d2-11ea-9581-d023278e8402.png" width=200>

**Comment by AyushBherwani1998** [comment]
@shihaohong I would like to work on this issue, can we make the `activeColor` default to `Theme.accentColor` when creatingn a `Radio` since the doc mentions, `activeColor` [defaults to accent color of the current Theme](https://api.flutter.dev/flutter/material/RadioListTile/activeColor.html) ?

**Comment by shihaohong** [comment]
Based on the name of the properties, I would imagine that [`toggleableActiveColor`](https://master-api.flutter.dev/flutter/material/ThemeData/toggleableActiveColor.html) would make the most sense as the default. Also, it sounds like this will likely be a breaking change, so it might be worth [familiarizing yourself with the policy](https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes).

@HansMuller might know more about the history of the different color parameters and which one we should really default to or if we should just keep it as-is and update the API docs.

**Comment by AyushBherwani1998** [comment]
@shihaohong Sure, till then I'll go through the breaking change policy.

**Comment by AyushBherwani1998** [comment]
@shihaohong I went through the breaking change policy, and I agree, we can change the `ListTileTheme.selectedColor` to `toggleableActiveColor` to have a consist Theme ` because, if `activeColor` is not null, then it is used for `selectedColor` instead of `accentColor`.

**Comment by AyushBherwani1998** [comment]
@shihaohong should I create a design document for proposing the change, or wait for the take from @HansMuller on the solution?

**Comment by HansMuller** [comment]
Sorry about the delay, I'll review this today!

**Comment by shihaohong** [comment]
I'm going to assign Hans for now just so that there is a reminder for him to provide some feedback when his week starts

**Comment by HansMuller** [comment]
@shihaohong OK, that worked :-).

This issue depends on the theme's accent color, which is becoming obsolete: https://docs.google.com/document/d/1kzIOQN4QYfVsc5lMZgy_A-FWGXBAJBMySGqZqsJytcE/edit#heading=h.2hl3s1i2nq6o

RadioButton and RadioListTile currently do not conform to the patterns described in the "Theme System Updates" document - [flutter.dev/go/material-theme-system-updates](https://flutter.dev/go/material-theme-system-updates). Migrating them will require breaking changes, as Shi Hao pointed out, and will likely require us to update test repo and internal applications. So although this fixing this issue might seem straightforward on the surface, it's likely to be difficult.

**Comment by shihaohong** [comment]
From Hans' outline, it seems like it will be a multi-step breaking change that would also require a Googler to fix issues that surface in internal applications. That being said, I see two options: 

1) Go through the breaking change process and update RadioListTile to properly use `toggleableActiveColor` over `accentColor`, which would reduce some strain on the bigger breaking change. This would require a Googler to be involved since internal repos would need to be fixed to conform to the breaking change.
2) Make this fix as part of the wider theme updates mentioned in flutter.dev/go/material-theme-system-updates, which would be a larger-scale breaking change.

**Comment by AyushBherwani1998** [comment]
I know since this won't priority but if the team decides to go with the first option in the future, I'll be more than happy to contribute if any external contribution required :)

**Comment by huycozy** [comment]
Hi @workerbee22 
There are changes in the usage of theme colors for `accentColor` and `toggleableActiveColor`:

- https://github.com/flutter/flutter/blob/e6300da2c39ff230d943eeccb80ba3ccfa1e3759/packages/flutter/lib/src/material/theme_data.dart#L372-L378

- https://github.com/flutter/flutter/blob/e6300da2c39ff230d943eeccb80ba3ccfa1e3759/packages/flutter/lib/src/material/theme_data.dart#L420-L426

Also, when using `controlAffinity`, `RadioListTile` keeps using color that is defined in ThemeData, please see in demo and sample code below:

<details>
<summary>Demo</summary>

![Screenshot 2022-11-03 at 18 57 57](https://user-images.githubusercontent.com/104349824/199716302-72ecfc89-71b7-4073-a87a-52c70d18c341.png)

</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Application';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      theme: ThemeData(
        accentColor: Colors.red,
        toggleableActiveColor: Colors.green,
        colorScheme: const ColorScheme.light(secondary: Colors.yellow),
      ),
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const MyStatefulWidget(),
      ),
    );
  }
}

/// stateful widget that the main application instantiates
class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

enum Fruit { apple, banana }

/// private State class that goes with MyStatefulWidget
class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  Fruit? _fruit = Fruit.apple;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        children: <Widget>[
          RadioListTile<Fruit>(
            // activeColor: Colors.red,
            controlAffinity: ListTileControlAffinity.trailing,
            title: const Text('Apple'),
            value: Fruit.apple,
            groupValue: _fruit,
            onChanged: (Fruit? value) {
              setState(() {
                _fruit = value;
              });
            },
          ),
          RadioListTile<Fruit>(
            // activeColor: Colors.red,
            title: const Text('Banana'),
            value: Fruit.banana,
            groupValue: _fruit,
            onChanged: (Fruit? value) {
              setState(() {
                _fruit = value;
              });
            },
          ),
        ],
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0 22A380 darwin-x64, locale en-VN)
    • Flutter version 3.3.7 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (27 hours ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.5.0-12.0.pre.93, on macOS 13.0 22A380 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-12.0.pre.93 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 92a66683a1 (6 hours ago), 2022-11-02 16:50:38 -0400
    • Engine revision 840a7b3462
    • Dart version 2.19.0 (build 2.19.0-364.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

Please retry and confirm again. Thanks!
