### ISSUE TITLE
Disable turbo boost on dashboard box

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#4262]
I've noticed that the analysis benchmarks tend to be a bit faster after they haven't run for a while, but then are consistently about 12% slower for the following commits.

<img width="488" alt="screen shot 2016-05-27 at 10 40 03 pm" src="https://cloud.githubusercontent.com/assets/1269969/15627495/cfb32696-249a-11e6-824f-98135a4ab161.png">

I suspect that the mac mini is enabling turbo boost for that first run after a long quiet period and then disabling it for subsequent runs. We should probably disable turbo boost for the dashboard box. The best source I could find for doing that was here: https://github.com/nanoant/DisableTurboBoost.kext.

@yjbanov

**Comment by yjbanov** [comment]
This is a non-trivial customization that will be hard to maintain (e.g. when we add/change build boxes we'll have to remember how to configure it correctly). I'm surprised that multiple runs of the benchmark doesn't solve this problem already.

**Comment by devoncarew** [comment]
> This is a non-trivial customization that will be hard to maintain

No arguments here, but I do want to get reliable analysis numbers for the graphs. There are probably a few ways to get that, including having an analysis/benchmarking box with turbo boost disabled. Many of the comments that I found - for why people were trying to disable turbo boost - were benchmarking related.

> I'm surprised that multiple runs of the benchmark doesn't solve this problem already.

Turbo boost is probably active for the first run, so that gets taken as the fastest number.

Let's keep this issue open so that we're aware of the issue.

**Comment by eseidelGoogle** [comment]
Its not uncommon for perf frameworks to discard extremes or first n runs
explicitly.

**Comment by Hixie** [comment]
@devoncarew Should we close this given you landed https://github.com/flutter/dashboard_box/pull/79 and @yjbanov gave a reason to be skeptical about actually changing the hardware configuration?

**Comment by devoncarew** [comment]
sgtm
