### ISSUE TITLE
Use Websocket client to connect to a HTTP server

### ISSUE THREAD

**Issue by rogerioo** [flutter/flutter#42623]
Hey Guys,

I'm having a really tough time using [WebSocket Channel](https://flutter.dev/docs/cookbook/networking/web-sockets) because I need to connect to my Express server, that runs in HTTP protocol. The server has a websocket inside of him that is ready to be used by a client, but the [WebSocket Channel](https://flutter.dev/docs/cookbook/networking/web-sockets) only allows me to use a connection that's running in ws/wss protocol. And I can't change my server communication protocol because there are some endpoints that I need to use to build my flutter app.

Does anyone knows a dependency that I can use that really works with Flutter? Because I've tried a few of Dart dependencies and none of them work, only [WebSocket Channel](https://flutter.dev/docs/cookbook/networking/web-sockets). 

Or any suggestions that I may pursue to achieve this connection? 

Thank you very much in advanced,

Rogério Júnior.

**Comment by janmoppel** [comment]
Hello @rogerioo !

Thank you for posting.
Your question seems to be a good fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) as well. Flutter has a very active and helpful community there, so feel free to post it there too.

Also, see other support options here: https://flutter.dev/community

**Comment by rogerioo** [comment]
Thanks @janmoppel ! I'll post there as well

**Comment by cfguimaraes** [comment]
So, this can be closed.
