### ISSUE TITLE
bitcode is not available in release mode

### ISSUE THREAD

**Issue by spWang** [flutter/flutter#42636]
I can use bitcode in debug mode, but the bitcode is not available in release mode.
Command "flutter build ios --debug" is working for bitcode, but command ""flutter build ios "is not working for bitcode

**Comment by jmagman** [comment]
@dnfield

**Comment by dnfield** [comment]
Could you provide some more details?  What version of flutter, what's the output of `flutter doctor -v`, what's the output of `flutter build ios -v`?

**Comment by spWang** [comment]
@dnfield 

**this is the output of`flutter doctor -v `:**
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.5 18F132, locale
    zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.4 at /Users/hb/development/flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/hb/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Redmi 6 Pro • 172.16.205.201:5555                  • android-arm64 • Android 9 (API
      28)
    • iPhone Xʀ   • A2F0FEA6-AD44-4230-BF84-7D8729A6830F • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!

**when I close bitcode,**
the output of `flutter build ios -v` is too long, so I put the log in [https://github.com/spWang/flutter_app_demo/blob/master/build_log.txt](url). I create a new flutter project, and excute these cammand:`flutter clean`  `flutter packages get`  `flutter build ios -v`，then I get the log.  you can rapid positioning with the keyword 'not contain bitcode'.
thankyou!

**Comment by dnfield** [comment]
This version of Flutter doesn't include bitcode.  You'll need to upgrade to the current beta, dev, or master channel.

A very rough way to check this is to check the size of the `Flutter` binary in the `Flutter.framework` folder for the release artifact - if it's not 100s of megabytes, it doesn't have bitcode.
