### ISSUE TITLE
 Pages are the same depth in the element tree

### ISSUE THREAD

**Issue by baij930312** [flutter/flutter#42639]
## Steps to Reproduce

```dart
class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: <Widget>[
          RaisedButton(
            onPressed: () {
              Navigator.of(context).push(MaterialPageRoute(builder: (_) {
                return Page2();
              }));
            },
          )
        ],
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: <Widget>[
          RaisedButton(
            onPressed: () {},
          )
        ],
      ),
    );
  }
}
```
1. Create page1 and page2 
2. Page1 push page2
 
<img width="398" alt="屏幕快照 2019-10-14 下午5 38 43" src="https://user-images.githubusercontent.com/38178903/66742494-55a15c00-eeaa-11e9-84d9-6309844d2eb3.png">

Should page2 be a child of page1?

**Comment by goderbauer** [comment]
No, page2 is pushed on the Navigator, which is part of the MaterialApp. It becomes a child of the Overlay managed by that Navigator.

**Comment by baij930312** [comment]
> No, page2 is pushed on the Navigator, which is part of the MaterialApp. It becomes a child of the Overlay managed by that Navigator.

If an inheritedWidget  is shared by multiple pages, it must be placed on top of the MaterialApp. 
is it?
