### ISSUE TITLE
[webview_flutter]:background makes webview empty

### ISSUE THREAD

**Issue by hdi1szh** [flutter/flutter#42644]
First Page which includes a webView -> push to Second Page which also includes a webView -> turn to background  ->turn to foreground -> then pop to First Page,but First page is empty.

[1571047670003923.mp4.zip](https://github.com/flutter/flutter/files/3723946/1571047670003923.mp4.zip)

**Comment by kwongfung** [comment]
There are two view for the one WebView : FlutterPlatformView and FlutterOverlayView. After your operate logic, the FlutterPlatformView has been pop but the FlutterOverlayView hasn't.

**Comment by hdi1szh** [comment]
Dear，
  What should I do to deal with the case? Or this is bug from WebView?
 
Thanks a lot.




------------------ 原始邮件 ------------------
发件人: "Gavin Wang"<notifications@github.com>;
发送时间: 2019年10月14日(星期一) 晚上6:51
收件人: "flutter/flutter"<flutter@noreply.github.com>;
抄送: "黄定师"<252899816@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [flutter/flutter] [webview_flutter]:background makes webviewempty (#42644)




There are two view for the one WebView : FlutterPlatformView and FlutterOverlayView. After your operate logic, the FlutterPlatformView has been pop but the FlutterOverlayView hasn't.

**Comment by hdi1szh** [comment]
Dear，
  thanks a lot for your reply.


  What should I do to deal with the case? Or this is bug from WebView?
 
Thanks a lot.





------------------ 原始邮件 ------------------
发件人: "Gavin Wang"<notifications@github.com>;
发送时间: 2019年10月14日(星期一) 晚上6:51
收件人: "flutter/flutter"<flutter@noreply.github.com>;
抄送: "黄定师"<252899816@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [flutter/flutter] [webview_flutter]:background makes webviewempty (#42644)




There are two view for the one WebView : FlutterPlatformView and FlutterOverlayView. After your operate logic, the FlutterPlatformView has been pop but the FlutterOverlayView hasn't.

**Comment by BondarenkoStas** [comment]
@hdi1szh Can you provide the code of your push_test? Please paste here your flutter doctor -v output.

**Comment by hdi1szh** [comment]
hello                                 Stanislav,               
      
 
      the code of main.dart:
import 'package:flutter/material.dart';
import 'package:push_test/second_page.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("First page"),
      ),
      body: Center(
        // child: Container(height: 200,child: UiKitView(viewType: "com.flutter_to_native_test_textview"))
        child: Container(
            height: 200, child: WebView(initialUrl: "https://www.baidu.com")),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.of(context)
              .push(MaterialPageRoute(builder: (context) => Second_Page()));
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}


 

the code of second_page.dart:
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class Second_Page extends StatefulWidget {
  Second_Page({Key key}) : super(key: key);

  _Second_PageState createState() => _Second_PageState();
}

class _Second_PageState extends State<Second_Page> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second page"),
      ),
      body: Center(
        child: Container(
            height: 200, child: WebView(initialUrl: "https://www.baidu.com")),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.of(context).pop();
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}




flutter doctor -v output:





------------------ 原始邮件 ------------------
                                                            发件人:                                   "Stanislav Bondarenko"<notifications@github.com>;             
                                                   发送时间:                                   2019年10月15日(星期二) 凌晨2:39             
                                                   收件人:                                   "flutter/flutter"<flutter@noreply.github.com>;                                  
                                                               抄送:                                           "黄定师"<252899816@qq.com>;"Mention"<mention@noreply.github.com>;                                          
                                                                           主题:                                                   Re: [flutter/flutter] [webview_flutter]:background makes webviewempty (#42644)                     
                 
                                      
                 
                 
                                              @hdi1szh                                          Can you provide the code of your push_test? Please paste here your flutter doctor -v output.

**Comment by kwongfung** [comment]
maybe you should try flutter dev channel.

**Comment by red282** [comment]
This might be the same issue. #36437

**Comment by BondarenkoStas** [comment]
Thank you @red282, I think it's the same. I'm going to close this one to avoid duplication, please follow and upvote #36437. @hdi1szh Thank you for the report!
