### ISSUE TITLE
Invalid response status code

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#42645]
```
 Future<Response<dynamic>> login(String userName, String password) async {
    Map requestParams = {
      "password": password,
      "email": userName,
    };
    Response<dynamic> response =
        await _httpClient.post("auth/login", data: json.encode(requestParams));

    return Future.value(response);
  }
```
my status code is 8xx,flutter throws an exception:   `Invalid response status code!`

i found some code throw it in the code of "http_parser.dart" in the Flutter SDK.
```
if (_statusCode < 100 || _statusCode > 599) { throw new HttpException("Invalid response status code"); }
```
But I want to use the customed  HTTP statusCode  between 200 and 800, such as 801,
How can i do for that!

**Comment by stuartmorgan** [comment]
That file is part of the Dart SDK, not Flutter, so you'd need to file [a Dart issue](https://github.com/dart-lang/sdk/issues).

(However, your status code is violating the HTTP spec, so it will likely be closed.)
