### ISSUE TITLE
Flutter 1.0 will come?

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#4265]

**Comment by abarth** [comment]
We're not aiming for a specific date.  You can track the Flutter 1.0 milestone <https://github.com/flutter/flutter/milestones/Flutter%201.0> to get a sense for what we'd like to accomplish before 1.0.  GitHub says we're 39% of the way there, but I'd take that number with a big grain of salt.  :)

**Comment by tain335** [comment]
Can finish Android or IOS Flutter 1.0 first? Just like React Native. That should make more developers involved in the project.

**Comment by abarth** [comment]
Developers should feel welcome and encouraged to get involved in the project regardless of the quality bar we'd like to hit for 1.0.
