### ISSUE TITLE
Flutter 1.9: D/skia    ( 5106): Shader compilation error

### ISSUE THREAD

**Issue by Boussarhane** [flutter/flutter#42659]
I've created a simple Flutter 1.9.1+hotfix.4 application (Flutter Demo App) using Android Studio 3.5.1. After adding successfully a new virtual device (Nexus 6) and tried to run my app (on Win10 pro 64bits), I got this error:
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Syncing files to device Android SDK built for x86...
D/skia    ( 5106): Shader compilation error
D/skia    ( 5106): ------------------------
D/skia    ( 5106): Errors:
D/skia    ( 5106): 
D/skia    ( 5106): Shader compilation error
D/skia    ( 5106): ------------------------
D/skia    ( 5106): Errors:
D/skia    ( 5106): 
D/skia    ( 5106): Shader compilation error
D/skia    ( 5106): ------------------------
D/skia    ( 5106): Errors:
D/skia    ( 5106): 
D/skia    ( 5106): Shader compilation error
D/skia    ( 5106): ------------------------
D/skia    ( 5106): Errors:
D/skia    ( 5106): 
D/EGL_emulation( 5106): eglMakeCurrent: 0xec5ed840: ver 3 1 (tinfo 0xec593810)
D/skia    ( 5106): Shader compilation error
D/skia    ( 5106): ------------------------
D/skia    ( 5106): Errors:
D/skia    ( 5106): 
D/skia    ( 5106): Shader compilation error
D/skia    ( 5106): ------------------------
D/skia    ( 5106): Errors:
D/skia    ( 5106): 
D/skia    ( 5106): Shader compilation error
D/skia    ( 5106): ------------------------
D/skia    ( 5106): Errors:
D/skia    ( 5106): 
```
But the application SHOWS!!

## Steps to Reproduce

1. I added a new virtual device (Nexus 6 using Android Pie)
2. I ran the application....Then  this error occurred

## Flutter Doctor
```
C:\Users\Mehdi>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [version 10.0.18362.418], locale fr-FR)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.38.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 3 categories.
```

**Comment by BondarenkoStas** [comment]
@Boussarhane do you mean that application works as normal despite the error?

**Comment by Boussarhane** [comment]
Yes it works. but i dont want to see these errors I can't see what's going on in the console

**Comment by guyzoum77** [comment]
![13](https://user-images.githubusercontent.com/48268288/71170236-a76fb500-2252-11ea-91bc-7588fb6b4847.PNG)
 i have the same error in my console so i dont' want to see this error. so help me to find something

**Comment by MichalMisiaszek** [comment]
I have exactly the same error after a recent Futter upgrade.

**Comment by FranciscoDevPy** [comment]
Hola a todos!!
Yo he usado el comando flutter clean y los errores han desaparecido
Hi everyone I have used the command flutter clean
and the mistakes are gone, this is worked for me
My Computer:
Windows 10 Pro 64Bits
VSCode

**Comment by liyuqian** [comment]
Can someone please confirm if this is still an issue on master branch Flutter that has a version newer than https://github.com/flutter/flutter/commit/8c0b43bda4e5ff29d399f06ce1c0e1027268d6b5 ?

Those error messages have gone for me. See https://github.com/flutter/flutter/issues/39828#issuecomment-612279427 for more details.

**Comment by FranciscoDevPy** [comment]
> Can someone please confirm if this is still an issue on master branch Flutter that has a version newer than [8c0b43b](https://github.com/flutter/flutter/commit/8c0b43bda4e5ff29d399f06ce1c0e1027268d6b5) ?
> 
> Those error messages have gone for me. See [#39828 (comment)](https://github.com/flutter/flutter/issues/39828#issuecomment-612279427) for more details.

I have this version and the problem still continues.
With the flutter clean command it is solved, I imagine it must be a cache problem or something like that.
 This command is mostly used when our project is showing debug error or running related error.

`Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (11 days ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2`

**Comment by eneskucukoglu** [comment]
Thanks Francisco flutter clean helped me rgaerds from Istanbul Turkey and where or how did you learn flutter?

**Comment by viralbhadeshiya** [comment]
Maybe following technique works:
If you are using android studio there are one test folder. In that folder if you click on auto solve option it create one class what is causing error. In my case it was myapp() and it is solved. maybe it works.
Let me know if it works.
