### ISSUE TITLE
CPU usage is getting higher when Web application is loaded in a chrome Tab.

### ISSUE THREAD

**Issue by GowthamF** [flutter/flutter#42654]
I have a Flutter Web application. Based on the requirements it got bigger in size with many widgets. When I launch the site in the browser CPU usage is increasing drastically. When change the tab it goes down. You can view it from this URL-https://visabymasters-79ead.firebaseapp.com/#/ 
Steps to reproduce
1.Open the link in the chrome.
2.Open the Task Manager and check the CPU usage.
3.Open another New Tab and check the CPU usage. 

Source file-https://bitbucket.org/gowthamf/visabymasters_hybrid/src/master/

**Comment by yjbanov** [comment]
There's a lot of DOM churn happening on every frame. One suggestion is to use `RepaintBoundary` around animating content, so that the rest of the page does not update on every frame. For the UI like yours you should only see canvas repaints, and no DOM manipulation (e.g. `removeChild`).

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
