### ISSUE TITLE
Scaffold resizeToAvoidBottomInset in App2App scenario

### ISSUE THREAD

**Issue by vitor-gyant** [flutter/flutter#42653]
When FlutterViewController has custom padding (does not match screen dimensions) the behaviour of the Scaffold seems to be incorrect. So, the goal is that Scaffold resizes automatically when the keyboard appears (MediaQuery viewInsets changes). This works correctly when the FlutterViewController fits the screen but when I give it a bottom padding the Scaffold still resizes without considering the "correct" area hidden by the keyboard which is now less than the normal scenario.

Is this behaviour intended ? Any suggestion ?

BR,

**Comment by vitor-gyant** [comment]
@BondarenkoStas @HansMuller  Is there any recommendation to workaround this issue ?

**Comment by pedromassangocode** [comment]
Hi @vitor-gyant 
Are you still facing this issue? If yes, can you please provide your `flutter doctor -v` your `flutter run -v` and a minimal reproducible sample code? if the code is too big you can create a sample project, push it to GitHub and share the link here.

Thank you

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
