### ISSUE TITLE
[webview_flutter] : Keyboard is opening but not closing

### ISSUE THREAD

**Issue by anthonycic** [flutter/flutter#42650]
Hi everyone,

All is in the title.

I know there is issues about keyboard.
Mine works fine, but when i click on the enter key, or when i click around the keydoard, it doesn't close...

Have you the same issue ? And could you help me ?

Thanks in advance

**Comment by BondarenkoStas** [comment]
@anthonycic Please provide your flutter doctor -v output. Is it reproducible on both android/ios device/simulator? Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by anthonycic** [comment]
Ok sorry i forgot to put it...

I have the problem on iOS and Android.

Here is the code (i use exactly the same used in the pluggin, with the same configuration) : 

```

class _WebViewExampleState extends State<WebViewFlutter> {
  final Completer<WebViewController> _controller =
  Completer<WebViewController>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Builder(builder: (BuildContext context) {
        return WebView(
          initialUrl: 'https://www.google.com',
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController webViewController) {
            _controller.complete(webViewController);
          },
        );
      }),
    );
  }

```

And here is my flutter doctor : 

[√] Flutter (Channel unknown, v1.9.1+hotfix.3, on Microsoft Windows [version 10.0.18362.418], locale fr-FR)
    • Flutter version 1.9.1+hotfix.3 at C:\src\flutter
    • Framework revision a72edc2706 (3 weeks ago), 2019-09-25 15:41:01 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\src\Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\src\Android
    • Java binary at: C:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\antho\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • B1 820 • 52339457969 • android-x86 • Android 5.0 (API 21)

• No issues found!

**Comment by deandreamatias** [comment]
This issue seems the same as #36478. If this is the case, it would be ideal to close one of the two

**Comment by BondarenkoStas** [comment]
Thank you @deandreamatias ! Closing it to avoid duplication, @anthonycic please follow it there.
