### ISSUE TITLE
[android-embedding] Tool cannot find the plugin main class

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#42661]
In some cases, a plugin's directory structure might not match the Java package. For example, the [cloud function](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_functions/pubspec.yaml#L9) plugin.

As a result, the tool would have to find the plugin's main class in any location under the `android/src/main` directory.

**Comment by amirh** [comment]
I'd say that this is a plugin bug and that the tool shouldn't allow building it...

cc @jonahwilliams

**Comment by jonahwilliams** [comment]
Did the old plugin structure intentionally support this?
  - If so, it doesn't necessarily make sense that we'd want the new structure too.
  - If not, we should be consistent

This seems similar to the changes we needed to make to some ios plugins that don't follow objective-c naming conventions.

It should be possible to update the offending plugins right?

**Comment by amirh** [comment]
I don't know if that was intentional, but I doubt. @collinjackson maybe you have some more ancient context?

It is possible to update offending plugins, I guess it technically is a breaking change to the Java API, I wish we had a way to estimate how many plugins have this issue.

**Comment by collinjackson** [comment]
I don't think it was intentional. I'd prefer if plugins were forced to conform to the correct directory naming. Although it would be a breaking change, it seems like a worthwhile one.

**Comment by xster** [comment]
What's the follow up here? Show an error in flutter_tools or in pub publish?

**Comment by xster** [comment]
@blasten you moved this to the done column. Did you mean to close this bug too?

**Comment by blasten** [comment]
As per https://github.com/flutter/flutter/issues/42661#issuecomment-541885505, there's no more work left here.
