### ISSUE TITLE
macos release mode is way slower than debug

### ISSUE THREAD

**Issue by lesnitsky** [flutter/flutter#42664]
```
[✓] Flutter (Channel master, v1.10.15-pre.95, on Mac OS X 10.14.5 18F132, locale en-BY)
    • Flutter version 1.10.15-pre.95 at /Users/lesnitsky/w/google/flutter
    • Framework revision 9423a01204 (16 hours ago), 2019-10-13 18:41:22 -0700
    • Engine revision eed171ff35
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 965b8cb1d8)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/lesnitsky/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/lesnitsky/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/lesnitsky/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (3 available)
    • macOS           • macOS           • darwin-x64     • Mac OS X 10.14.5 18F132
    • Chrome          • chrome          • web-javascript • Google Chrome 77.0.3865.90
    • Headless Server • headless-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by jonahwilliams** [comment]
@lesnitsky you've provided almost no details here for us to go off of. Could you take another pass at this issue and include things like the code that is slow, any performance measurements, et cetera? Thanks!

**Comment by lesnitsky** [comment]
@jonahwilliams is there a way to profile the app in release mode? bc it's really hard to tell which parts of code are slow... app isn't that trivial, it uses local angle-dart server, communicates with backend via WS, re-renders UI constantly

**Comment by lesnitsky** [comment]
probably should rephrase... is there an option to profile the app running in AOT. I can always use `Stopwatch()`, but this might be not the best approach (dev tools are much more convenient)

**Comment by jonahwilliams** [comment]
`--profile` will run in AOT mode but with the observatory attached for profiling

**Comment by mraleph** [comment]
@lesnitsky how did you discover that the app is slower? e.g. does UI look sluggish? are certain actions taking longer time? Did you compare debug and release builds on the same device or did you run debug build in the simulator and release build on the device?

Do you do any sort of crypto or number crunching in your application?

**Comment by lesnitsky** [comment]
UI looks very sluggish in release mode. _any_ action (ui interaction) takes
longer. I don't have any crypto stuff or heavy number calculations. The
most common operations are json parsing and req/res to/from angel-dart
server running as the part of the same app (not in isolate)
I was testing the send build on the same device
I'll get back with more details on this issue after I'll have a chance to
profile the app running in AOT

P. S. possible suspects:
- angel-dart (I don't see such a degraded performance in other apps I build
which don't use this library)
- home-grown json db

**Comment by lesnitsky** [comment]
@mraleph this turned out to be a misuse of https://pub.dev/packages/flutter_emoji `EmojiParser` constructor. I thought it is a singleton, so wasn't afraid of creating a new instance each time which lead to redundant json parse.

The funny thing is that debug mode is way more performant than profile. 

[This](https://github.com/petehouston/flutter-emoji/blob/master/lib/flutter_emoji.dart#L59) and json parse were taking much longer in profile mode vs debug
