### ISSUE TITLE
If a hero animation is triggered, then scrolled off-screen, the Hero widget will not return when navigating back.

### ISSUE THREAD

**Issue by SmashHighlights** [flutter/flutter#42674]
This bug occurs on the stable build v1.9.1+hotfix.4.
I have since rolled back to v1.7.8+hotfix.4 which does not have this bug.

Here is a video comparison to showcase the Hero animation bug:
https://youtu.be/7NdJPUqKnJo

I'll try to explain the bug simply. 
Suppose you have a Hero widget on two pages, Page A and Page B.
You start on Page A and you trigger a page transition to Page B, then the Hero widget will animate to its new position on Page B.
Whilst on Page B, if the Hero widget is removed from cache (perhaps by scrolling it off-screen), then if you navigate back to Page A the Hero widget will be missing.

**Comment by LongCatIsLooong** [comment]
This looks like a dup of https://github.com/flutter/flutter/issues/40239. The bug is fixed on v1.10.4.

**Comment by SmashHighlights** [comment]
Thank you for letting me know @LongCatIsLooong

**Comment by aleksandar-radivojevic** [comment]
When this is going to be fixed in stable channel?? Please guys
