### ISSUE TITLE
Calling WidgetsFlutterBinding.ensureInitialized() and GoogleSignIn.signInSilently() in different zones causes crash

### ISSUE THREAD

**Issue by kinex** [flutter/flutter#42682]
To fix #39620 I had to add a call to `WidgetsFlutterBinding.ensureInitialized()` to the beginning of the `main` function like this:

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // initialize app settings and Crashlytics here + load strings
  .
  .
  .
  await runZoned<Future<void>>(() async {
    runApp(MyApp());
  }, onError: (e, s) {
    // report error to Crashlytics here
  });
}
```
This resulted another issue: if I called `GoogleSignIn.signInSilently` once, after that any new call to `GoogleSignIn.signInSilently` or `GoogleSignIn.signIn` caused crash:
```
I/flutter (21816): PlatformException(sign_in_required, com.google.android.gms.common.api.ApiException: 4: 4: , null)
[38;5;244mI/flutter (21816): #0      StandardMethodCodec.decodeEnvelope[39;49m
[38;5;244mI/flutter (21816): #1      MethodChannel.invokeMethod[39;49m
I/flutter (21816): <asynchronous suspension>
[38;5;244mI/flutter (21816): #2      MethodChannel.invokeMapMethod[39;49m
I/flutter (21816): <asynchronous suspension>
[38;5;248mI/flutter (21816): #3      GoogleSignIn._callMethod[39;49m
I/flutter (21816): <asynchronous suspension>
[38;5;248mI/flutter (21816): #4      GoogleSignIn._addMethodCall[39;49m
[38;5;248mI/flutter (21816): #5      GoogleSignIn.signInSilently[39;49m
[38;5;248mI/flutter (21816): #6      _signInWithGoogleAsync[39;49m
I/flutter (21816): <asynchronous suspension>
[38;5;248mI/flutter (21816): #7      signInWithGoogleAsync.<anonymous closure>[39;49m
[38;5;248mI/flutter (21816): #8      Pool.withResource[39;49m
I/flutter (21816): <asynchronous suspension>
I/flutter (21816): #9      signInWithGoogleAs
I/flutter (21816): main
```
Finally I found a workaround: moving the call to `WidgetsFlutterBinding.ensureInitialized()` inside the `runZoned` prevents the crash:
```dart
void main() async {
  await runZoned<Future<void>>(() async {
    WidgetsFlutterBinding.ensureInitialized();
  
    // initialize app settings and Crashlytics here + load strings
    .
    .
    .
    runApp(MyApp());
  }, onError: (e, s) {
    // report error to Crashlytics here
  });
}
```
I think this should be fixed or at least documented why is this happening and how to avoid it. As a side note, the same code works in stable channel v1.9.1 hotfix.4  (without call to `WidgetsFlutterBinding.ensureInitialized()`).

```
[√] Flutter (Channel beta, v1.10.7, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.39.1)
[√] Connected device (1 available)

• No issues found!
```

**Comment by Hixie** [comment]
This is strange. I wouldn't expect anything here to be using zones in a way that is affected here...

**Comment by dotdoom** [comment]
@Hixie I wonder if this could be somehow interfering with PlatformException not being caught by FlutterError.onError (#34107) and getting propagated into a wrong zone somehow, leaving the original MethodChannel sender waiting infinitely for a response.

That error handling with channels is still a mystery to me, so I may be completely out of grip here, so treat with a grain of salt.

**Comment by pedromassangocode** [comment]
Hi @kinex 
Are you still facing this issue? If yes, can you please provide your `flutter doctor -v` your `flutter run -v` and a minimal reproducible sample code? if the code is too big you can create a sample project, push it to GitHub and share the link here.

Thank you

**Comment by kinex** [comment]
I tested this case again with Flutter 1.20.3, all the latest plugins installed (+ `runZoned` replaced with `runZonedGuarded`) and I cannot reproduce the issue anymore. So I guess this has been fixed as a side effect of some other changes/fixes.

**Comment by pedromassangocode** [comment]
Hi @kinex 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
