### ISSUE TITLE
Conflicts of library for Reachability in iOS

### ISSUE THREAD

**Issue by eleomilagrosa** [flutter/flutter#42707]
Just add this 2 in pubspec.yaml
then run the app in iOS

pusher_websocket_flutter: ^0.1.1
connectivity: ^0.4.4+1

When you combine this 2 library your app wont work anymore in iOS.
because of the library "Reachability"

![image](https://user-images.githubusercontent.com/15756318/66801148-a5376480-ef4a-11e9-8f72-b09f9ff04052.png)

Please give suggestions how to fix this situations or bugs.

When I remove the connectivity library it will work as expected

**Comment by janmoppel** [comment]
Hello @eleomilagrosa !

Thank you for posting an issue.
Can you please also add the `flutter doctor -v` command output?

**Comment by eleomilagrosa** [comment]
![image](https://user-images.githubusercontent.com/15756318/66810008-010ce800-ef61-11e9-9602-61d2cf2046fc.png)

sorry for this, I can only get a screenshot.

**Comment by genert** [comment]
Same issue here....

The library "pusher_websocket_flutter" uses "PusherSwift" that uses "ashleymills/Reachability.swif" (https://cocoapods.org/pods/ReachabilitySwift). The "connectivity" uses "Reachability" (https://cocoapods.org/pods/Reachability).

It appears that both libraries use different native libraries but it seems that their symbols match hence the crash?

I wonder if there is a way around that...

@jmagman Have you ever encountered such error?

@eleomilagrosa Any updates? Did you figure it out?

**Comment by genert** [comment]
![Screenshot 2019-11-26 at 16 09 40](https://user-images.githubusercontent.com/1218788/69640529-2a905780-1067-11ea-9412-e20f42b68a1c.png)

```
➜  ios git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.15 19A583, locale en-GB)
    • Flutter version 1.10.7 at /Users/genertorg/flutter
    • Framework revision e70236e36c (8 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/genertorg/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6262.58

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone • 9581bfd8064d6254aaa4c9bccbf2b8055a9a1c83 • ios • iOS 13.1.3

! Doctor found issues in 1 category.
```

**Comment by jmagman** [comment]
> The library "pusher_websocket_flutter" uses "PusherSwift" that uses "ashleymills/Reachability.swif" (https://cocoapods.org/pods/ReachabilitySwift). The "connectivity" uses "Reachability" (https://cocoapods.org/pods/Reachability).
> 
> It appears that both libraries use different native libraries but it seems that their symbols match hence the crash?

@genert That makes sense! [Symbols must be uniquely named within a project](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html#//apple_ref/doc/uid/TP40011210-CH10-SW4).  Frameworks should each have their own unique three-letter prefix, but of course there are only so many letter combinations (and neither the Flutter framework nor first-party Flutter plugins follow this guideline, to my great chagrin).  There's not much as an app developer you can do about this, except encourage those plugin authors to change to different prefixes.  I don't see a feature in CocoaPods to let you re-prefix symbols between different pods in your Podfile, though that would be [a good feature request](https://github.com/CocoaPods/CocoaPods/issues/new).

However, even without the crash, it's unfortunate to embed two frameworks with identical functionality.  If the symbols really are identical and the plugins do the same thing, you could be sneaky and tell CocoaPods in your Podfile to only use one?
```ruby
  plugin_pods.each do |name, path|
    next if name == 'ReachabilitySwift'
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
```
I didn't test this, and if anywhere system imports `<ReachabilitySwift/Reachability.h>` then this won't work.
Let me know how it goes, but I don't think there's anything Flutter proper can do about this.  It's an unfortunate interaction between those two plugins and how CocoaPod's dependency resolution works (though you would have the same problem with any dependency manager, including Swift package manager)

**Comment by wawoon** [comment]
I got the same error trying to use these libraries together.

`graphql_flutter 3.0.0`(which uses `connectivity 0.4.8`) 
`pusher_websocket_flutter: ^0.1.1`

I tried this code, but it doesn't change the result.
```
plugin_pods.each do |name, path|
    next if name == 'ReachabilitySwift'
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
```

![スクリーンショット 2020-02-25 21 37 59](https://user-images.githubusercontent.com/36811303/75248247-2961f880-5817-11ea-93de-85a56de3c378.png)

**Comment by jmagman** [comment]
@wawoon You are hitting https://github.com/flutter/flutter/issues/49504.

**Comment by LtotheWT** [comment]
have any of you found the solution ?

**Comment by chinloyal** [comment]
I am also having this same issue. Why is this issue closed? There seems to be no solution

**Comment by jmagman** [comment]
@chingjun 
> I don't think there's anything Flutter proper can do about this. It's an unfortunate interaction between those two plugins and how CocoaPod's dependency resolution works (though you would have the same problem with any dependency manager, including Swift package manager)

**Comment by chingjun** [comment]
@jmagman I think you meant to at @chinloyal

**Comment by jmagman** [comment]
Sorry, apologies!

**Comment by ezhamkarim** [comment]
> I am also having this same issue. Why is this issue closed? There seems to be no solution

Right now the better solution is Installing [connectivityswift](https://pub.dev/packages/connectivityswift) with [flutter_pusher_client](https://pub.dartlang.org/packages/flutter_pusher_client). The connecitivity swift package will not generating `Reachability` files and it works same as the `connectivity` package
