### ISSUE TITLE
Light/Dark launch background depending on the current theme

### ISSUE THREAD

**Issue by nbros** [flutter/flutter#42710]
## Use case
`Flutter create` automatically creates a pure-white launch background for Android (in `android\app\src\main\res\drawable\launch_background.xml`, with a `@android:color/white` drawable).

## Proposal
Instead, it could use the `?android:attr/colorBackground` theme attribute to have a launch background that depends on the current light or dark theme.

cf https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#launch_screens

**Comment by nt4f04uNd** [comment]
Startup process should do the same for system nav bar, because now it launches totally depending on system theme, see #39614

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by bean5** [comment]
Chrome should do this as well for new tabs. I get blinded at night whenever I'm browsing. And it doesn't have to be new tabs. Any new tab while loading seems to default to a blinding white.

**Comment by bean5** [comment]
w00t! I really didn't like my fancy flutter apps blinding people in dark mode. So awesome!

**Comment by xster** [comment]
Thanks for your fix @younghwan
