### ISSUE TITLE
IOS 13 device is not identified by flutter because idevice_id not present in cache

### ISSUE THREAD

**Issue by TharinduNM** [flutter/flutter#42714]
I'm using an iPhone 8 with IOS 13. The `flutter devices` command does not identify my iPhone after I upgraded my MacBook Pro to macOS 10.15 Catalina. 

I tested with both android devices and iPhones.

- Android devices are still identified with no issue.
- Xcode identifies my iPhone. 
- iPhone 8 with IOS 13 was not recognized by flutter.
- iPhone 7 with IOS 12 was not recognized by flutter.

**Target Platform:** 
**Target OS version/browser:** macOS 10.15 Catalina, flutter v1.9.1+hotfix.4
**Devices:** iPhone 8 with IOS 13, iPhone 7 with IOS 12

Output from `flutter doctor --verbose`

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A583, locale
    en-LK)
    • Flutter version 1.9.1+hotfix.4 at
      /Users/tharindu/Documents/Development/flutter
    • Framework revision cc949a8e8b (2 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tharindu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[!] Connected device
    ! No devices available

```

**Comment by christopherfujino** [comment]
Hmm, this is very strange. What could be causing this is Gatekeeper blocking the binary `idevice_id` that we ship with the flutter tool from querying for installed devices. We shouldn't be blocked for v1.9.1+hotfix.4 as we codesigned and notarized those binaries...

Could you copy and paste the output of the command:

```
codesign -vvv /Users/tharindu/Documents/Development/flutter/bin/cache/artifacts/libimobiledevice/idevice_id
spctl -vvv --assess /Users/tharindu/Documents/Development/flutter/bin/cache/artifacts/libimobiledevice/idevice_id
```

This should verify that the binary is signed and notarized. The expected output should be:

```
~/git/flutter$ codesign -vvv bin/cache/artifacts/libimobiledevice/idevice_id
bin/cache/artifacts/libimobiledevice/idevice_id: valid on disk
bin/cache/artifacts/libimobiledevice/idevice_id: satisfies its Designated Requirement
~/git/flutter$ spctl -vvv --assess bin/cache/artifacts/libimobiledevice/idevice_id
bin/cache/artifacts/libimobiledevice/idevice_id: rejected (the code is valid but does not seem to be an app)
origin=Developer ID Application: FLUTTER.IO LLC (S8QB4VV633)
```

Even though `spctl` says it's rejected, it should run if the code is valid. Thanks.

**Comment by casino0313** [comment]
<img width="969" alt="Screenshot 2019-10-18 at 14 28 27" src="https://user-images.githubusercontent.com/11918169/67071063-2fcecc80-f1b4-11e9-8c16-47bd7bda5ba4.png">

Similer problem.  

iOS 12 on iPhone 6 plus was not recognized by flutter.
iOS 13 on iPhone 7 was not recognized by flutter.

flutter doctor --verbose same result as @TharinduNM 

[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A602, locale en-HK)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[!] Connected device
    ! No devices available

**Comment by TharinduNM** [comment]
@christopherfujino Running the given commands gives the below output

```
/Users/tharindu/Documents/Development/flutter/bin/cache/artifacts/libimobiledevice/idevice_id: No such file or directory

/Users/tharindu/Documents/Development/flutter/bin/cache/artifacts/libimobiledevice/idevice_id: accepted
override=security disabled
```

Seems like the idevice_id is not installed properly.

**Comment by christopherfujino** [comment]
@TharinduNM @casino0313 Oh wow, so you actually don't have the binaries. The tool should download those binaries already, providing that your `flutter/bin/cache/*.stamp` file doesn't match your `flutter/bin/internal/*.version` file. Could you also compare your stamp file (if you have it) to your version file, e.g.

```
cat path/to/flutter/bin/cache/libimobiledevice.stamp
cat path/to/flutter/bin/internal/libimobiledevice.version
```

Thank you so much!

**Comment by TharinduNM** [comment]
@christopherfujino The results look identical. Please see below. 

```
.stamp  :  6150fcd888a0ee8a69dd47328509ee608c2e02dc%
.version : 6150fcd888a0ee8a69dd47328509ee608c2e02dc
```

Thank you!

**Comment by casino0313** [comment]
.stamp  :  6150fcd888a0ee8a69dd47328509ee608c2e02dc
.version :  6150fcd888a0ee8a69dd47328509ee608c2e02dc

looks like the same but different of change line symbol, i guess
<img width="974" alt="Screenshot 2019-10-21 at 12 02 28" src="https://user-images.githubusercontent.com/11918169/67175991-c7256100-f3fa-11e9-830a-632acb5badeb.png">

**Comment by casino0313** [comment]
I have check flutter/bin/cache/*.stamp file and flutter/bin/internal/*.version file
Same file name all match with content, but there are some different files between flutter/bin/cache/*.stamp and flutter/bin/internal/*.version

<img width="991" alt="Screenshot 2019-10-21 at 12 19 31" src="https://user-images.githubusercontent.com/11918169/67176655-90047f00-f3fd-11e9-906f-93a461cffba5.png">

**Comment by TharinduNM** [comment]
@christopherfujino Is there a way around this?

**Comment by orourkedd** [comment]
I'm having the exact same issue.  I deleted flutter and downloaded a fresh copy from https://flutter.dev/docs/get-started/install/macos.  When I ran `flutter doctor`, I got this popup:

<img width="421" alt="screenshot" src="https://user-images.githubusercontent.com/2280571/67218215-d399c180-f3da-11e9-9795-eb1434896a1b.png">

**Comment by orourkedd** [comment]
I found a workaround by:

1. Navigating to: /path/to/flutter/bin/cache/artifacts/libimobiledevice
2. Right clicking on each binary in the folder (idevice_id, ideviceinfo, idevicename, idevicescreenshot, idevicesyslog) and clicking "Open".  I then explicitly allow execution of this binary.  It will do nothing but running it give macOS the chance to whitelist it.
3. Do the same as above for the one binary (iproxy) in this folder: /path/to/flutter/bin/cache/artifacts/usbmuxd

After this, `flutter doctor` yields the correct results and I can run my flutter app on my iphone from android studio.

**Comment by christopherfujino** [comment]
@TharinduNM I would imagine that if you blow away your entire cache `rm -rf flutter/bin/cache` and then run `flutter doctor -v`, the tool should repopulate the cache, download idevice_id, and everything should be good. I'm stumped as to why you would have the stamp file but not the cache artifact, though.

@orourkedd that is actually a different issue, https://github.com/flutter/flutter/issues/42969

**Comment by casino0313** [comment]
@christopherfujino Thanks.  The problem fix after rm -rf flutter/bin/cache and then run flutter doctor -v.

**Comment by TharinduNM** [comment]
@christopherfujino Thank you. `-rf flutter/bin/cache` and then `flutter doctor -v` fixed the issue

**Comment by TharinduNM** [comment]
Closing the issue because the above comment fixed the issue

**Comment by Almorisson** [comment]
> @TharinduNM I would imagine that if you blow away your entire cache `rm -rf flutter/bin/cache` and then run `flutter doctor -v`, the tool should repopulate the cache, download idevice_id, and everything should be good. I'm stumped as to why you would have the stamp file but not the cache artifact, though.
> 
> @orourkedd that is actually a different issue, #42969

Thanks @christopherfujino ! You solution is quite simple and very efficient.

**Comment by sparda-65** [comment]
> * Navigating to: /path/to/flutter/bin/cache/artifacts/libimobiledevice
> * Right clicking on each binary in the folder (idevice_id, ideviceinfo, idevicename, idevicescreenshot, idevicesyslog) and clicking "Open".  I then explicitly allow execution of this binary.  It will do nothing but running it give macOS the chance to whitelist it.
> * Do the same as above for the one binary (iproxy) in this folder: /path/to/flutter/bin/cache/artifacts/usbmuxd

This steps work for me:

Navigating to: /path/to/flutter/bin/cache/artifacts/libimobiledevice
Right clicking on each binary in the folder (idevice_id, ideviceinfo, idevicename, idevicescreenshot, idevicesyslog) and clicking "Open". I then explicitly allow execution of this binary. It will do nothing but running it give macOS the chance to whitelist it.
Do the same as above for the one binary (iproxy) in this folder: /path/to/flutter/bin/cache/artifacts/usbmuxd

and run flutter doctor

**Comment by aliParsl** [comment]
> I found a workaround:
> 
>     1. Completely reinstall flutter from: https://flutter.dev/docs/get-started/install/macos.
> 
>     2. Navigating to: /path/to/flutter/bin/cache/artifacts/libimobiledevice
> 
>     3. Right clicking on each binary in the folder (idevice_id, ideviceinfo, idevicename, idevicescreenshot, idevicesyslog) and clicking "Open".  I then explicitly allow execution of this binary.  It will do nothing but running it give macOS the chance to whitelist it.
> 
>     4. Do the same as above for the one binary (iproxy) in this folder: /path/to/flutter/bin/cache/artifacts/usbmuxd
> 
> 
> After this, `flutter doctor` yields the correct results and I can run my flutter app on my iphone from android studio.

This worked. Definitely a permissions issue. Would be great if Flutter Doctor could point that out

**Comment by wanghuajian620** [comment]
Use Xcode
