### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by XingXiaoWu** [flutter/flutter#42725]
environment：MacOS 10.15   Xcode11

![image](https://user-images.githubusercontent.com/22769131/66814077-93fd5080-ef68-11e9-8a62-0a4286953138.png)

When I use Xcode to run,build failed
![image](https://user-images.githubusercontent.com/22769131/66814008-716b3780-ef68-11e9-8a91-809606399150.png)

I tried to solve it in the following way, but failed
----------------------------------------------------
First：
Look at https://github.com/flutter/flutter/issues/40146
But a friend told me that it has been fixed.
----------------------------------------------------
Second:
Using legacy build system
![image](https://user-images.githubusercontent.com/22769131/66814442-2dc4fd80-ef69-11e9-99b3-fed2a71cac53.png)
But it make other error,I can't solve it
![image](https://user-images.githubusercontent.com/22769131/66814528-50efad00-ef69-11e9-9ff8-4dc2dd3b6cc4.png)

----------------------------------------------------
Third：
Check this button，It build success!
![image](https://user-images.githubusercontent.com/22769131/66814741-b5ab0780-ef69-11e9-8ef9-8de08a2840ea.png)
But can't load any page, white screen, and the console has some output

————————————————————————
How to fix it?

**Comment by XingXiaoWu** [comment]
I have been working for a day and finally know how to do it.
1.update cocoapods version >1.6.0
2. cd your ios workspace path
```
pod update
```

**Comment by CaiChenghan** [comment]
I have the same error

**Comment by yuanjunxiao** [comment]
thank you，Build Phases->run Script->run Script only when installing.  Solved the problem

**Comment by alnaughty** [comment]
I solved mine via checking on my flutter bin and it seems like ICloud deleted my .pubcache so I downloaded it and everything worked well again.

**Comment by TahaAli07** [comment]
Moved from v1.9.1+hotfix.6 to v1.11.0 .

To change flutter version to 1.11.0 just run

`flutter version v1.11.0`

This fixed this issue for me , tried all other other highly voted solutions but none worked.
