### ISSUE TITLE
contenteditable for webview_flutter

### ISSUE THREAD

**Issue by perekoo** [flutter/flutter#42721]
For an application I need a document that is able to record and display any type (text, audio, video, HTML, maybe PDF) that the user enters or inserts. Unfortunately the attribute "contenteditable" is apparently not supported by the webview_flutter plugin (^0.3.14+1). Is there a chance that this will happen in the foreseeable future?

**Comment by stuartmorgan** [comment]
Closing as out of scope; the content supported by system web views is a function of the system webview APIs, not the plugin that wraps them.
