### ISSUE TITLE
upgrade the version of intl of flutter_location package of stable branch to 0.16.0

### ISSUE THREAD

**Issue by Cyycl** [flutter/flutter#42720]
## Use case

I used a package that relies on the 0.16.0 version of intl, but the version of intl of flutter_location package of stable branch must be 0.15.8, so there is a conflict.

## Proposal

upgrade the version of intl of flutter_location package of stable branch to 0.16.0.

Looking forward to your reply ~~

**Comment by Zazo032** [comment]
Version `0.16.0` will eventually arrive to `stable` branch, most likely in next release in around 1 month, you can try using `beta` or `dev` channels meanwhile.
