### ISSUE TITLE
HttpException: Failed to parse header value [HttpOnly]

### ISSUE THREAD

**Issue by StarOfLife** [flutter/flutter#42727]
this is my Response Header 
```
Connection: keep-alive
Content-Type: application/xhtml+xml;charset=UTF-8
Date: Tue, 15 Oct 2019 02:35:03 GMT
Server: nginx
Set-Cookie: HttpOnly
Set-Cookie: Secure
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN
```
when I use dio to set cookie,it will throw the error:HttpException: Failed to parse header value [HttpOnly].
is it a bug in _Cookie.fromSetCookieValue ?
```
_name = _validateName(parseName());
    if (done() || _name.length == 0) {
      throw new HttpException("Failed to parse header value [$s]");
    }
```
my header[set-cookie]'s value have not '=';so when it running parseName(),the done() will return true;

**Comment by TahaTesser** [comment]
Hi @StarOfLife 
if you're still experiencing this problem with latest stable, please create a new issue and provide the
information required in the template.
Thank you
