### ISSUE TITLE
add an app restart command as a service protocol extension

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#4272]
For the edit/refresh work, we'll need an app restart command, likely exposed as a service protocol extension. This would be exposed as something like `ext.flutter.restartApp` or `ext.flutter.restartIsolate`. It would work similarly to the android `flutter refresh` command, which keeps the flutter process running, terminates the current isolate, and starts up a new isolate with the updated app. 

The command could assume that the original way that it loaded its sources still works as a way to load any newly changed sources (that some other mechanism would have updated any changed sources). The iOS simulator - since it already loads the dart sources from the host filesystem - is a good way to test out the initial implementation.

Some of the `flutter refresh` implementation:
- https://github.com/flutter/engine/blob/master/sky/shell/platform/android/org/domokit/sky/shell/SkyActivity.java#L149
- https://github.com/flutter/engine/blob/master/sky/shell/platform/android/io/flutter/view/FlutterView.java#L445
- https://github.com/flutter/engine/blob/b6ad88501f8f712c4181811c05d37afcf8d52168/sky/shell/ui/engine.cc#L232
- https://github.com/flutter/engine/blob/b6ad88501f8f712c4181811c05d37afcf8d52168/sky/shell/ui/engine.cc#L159

/cc @chinmaygarde

**Comment by sethladd** [comment]
@johnmccutchan @devoncarew is this still required? Maybe we did it?

**Comment by devoncarew** [comment]
We'll need a way to re-start an isolate w/ the updated source code - a service protocol command to invoke. I think https://github.com/dart-lang/sdk/issues/26903 is tracking that work.

**Comment by sethladd** [comment]
Cool, thanks for the update and link!

**Comment by Hixie** [comment]
This is done right?
