### ISSUE TITLE
Flutter Video player subtitle

### ISSUE THREAD

**Issue by kakarott32** [flutter/flutter#42737]
I'm using flutter, it's awesome 
But I have problem with video player, subtitle doesn't work!!
Why?? 

EDIT:
G:\app\alphacima\android>flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.418], locale ar-IQ)
    • Flutter version 1.9.1+hotfix.4 at C:\src\flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\bashi\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.38.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • PAR LX1M • B5M5T18A18000091 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by BondarenkoStas** [comment]
@kakarott32 please provide your flutter doctor -v output. What is wrong exactly? Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by kakarott32** [comment]
> 
> 
> @kakarott32 please provide your flutter doctor -v output. What is wrong exactly? Please provide a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

subtitle with video like (srt, vrr, ass, etc...)
dosn`t work with video player

**Comment by stuartmorgan** [comment]
The plugin has subtitle support now; this issue doesn't have enough detail to evaluate what specific subtitle variant is being requested.

Given that; closing. If there's a specific example that doesn't work, please file a new issue with details, including a reproducible test case.
