### ISSUE TITLE
[WebView] Video renders poorly (lags)

### ISSUE THREAD

**Issue by alereisan** [flutter/flutter#42734]
A 1080p .mp4 video played within the webview_flutter plugin is rendering poorly. The same URL with the videoplayer renders perfectly in the device's Chrome Browser.

I tested webview_flutter and also flutter_webview_plugin, but both result in the above experience. I think this is a problem with flutter itself.

**Comment by janmoppel** [comment]
Hello @alereisan !

Thank you for posting an issue.
Can you please also attach the `flutter doctor -v` command?

**Comment by alereisan** [comment]
@janmoppel Flutter Doctor Output:

[✓] Flutter (Channel beta, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95,
    locale de-CH)
    • Flutter version 1.9.1+hotfix.4 at
      /Volumes/MacExternalInaffect/flutter-sdk/flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59
      -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.0.1)
    • Android SDK at /Volumes/MacExternalInaffect/android-sdk/
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-29, build-tools 29.0.0.1
    • ANDROID_HOME = /Volumes/MacExternalInaffect/android-sdk/
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.39.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • V3 • 192.168.1.17:5555 • android-arm64 • Android 7.1.2 (API 25)

• No issues found!

**Comment by tuncay98** [comment]
Hi, I also have such an issue. Did you find any solution?

**Comment by alereisan** [comment]
@tuncay98 yes, unfortunately this is a older Android WebView issue and you will not get around it. I tried as good as everything. If you want to play videos in the Browser in high quality, you need to go for "Chrome Custom Tabs" or build a PWA.

**Comment by iapicca** [comment]
Hi @alereisan 
you are referring to a 3rd party plugin [flutter_webview_plugin](https://pub.dev/packages/flutter_webview_plugin),
you might want to open an issue on the dedicated [github](https://github.com/fluttercommunity/flutter_webview_plugin/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by jockebq** [comment]
I have the same issue, I have tried using `flutter_webview_plugin` and also `webview_flutter`, both returns the same result. Playing a 1080p video in the webview app will stutter and not play smoothly at all. This is on an Amlogic TV Box which has enough performance to handle a 4K video in a video player. Why do I get this bad video performance?
