### ISSUE TITLE
instantiateImageCodec pic ratio not correct

### ISSUE THREAD

**Issue by qylshy** [flutter/flutter#42730]
## Steps to Reproduce

```dart
Container(
        width: 80,
        height: 80,
        decoration: BoxDecoration(
          color: Color(0xFFF9F9FA),
          borderRadius: BorderRadius.circular(4),
          image: DecorationImage(image:MyImageFile(File('/storage/emulated/0/Android/data/com.flutter.example/cache/head/1571111865638.jpg'),),
              fit: BoxFit.cover)
        ),
      )
```

`MyImageFile.dart`:
```dart
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'dart:ui' as ui show instantiateImageCodec, Codec;


class MyImageFile extends FileImage {

  MyImageFile(File file) : super(file);


  @override
  ImageStreamCompleter load(FileImage key) {
    return MultiFrameImageStreamCompleter(
      codec: _loadAsync(key),
      scale: key.scale,
      informationCollector: () sync* {
        yield ErrorDescription('Path: ${file?.path}');
      },
    );
  }

  Future<ui.Codec> _loadAsync(FileImage key) async {
    assert(key == this);

    final Uint8List bytes = await file.readAsBytes();
    if (bytes.lengthInBytes == 0)
      return null;

    return await ui.instantiateImageCodec(bytes, targetHeight: 400);


    //return await ui.instantiateImageCodec(bytes, targetWidth: 4032, targetHeight: 1960);

    //return await PaintingBinding.instance.instantiateImageCodec(bytes);
  }
}

```

```dart
Future<Codec> instantiateImageCodec(Uint8List list, {
  int targetWidth,
  int targetHeight,
})
```

this method I just change this use targetWidth to decrease the gallery picture memory。
but I got an incorrect result， the Image ratio not original

my pic size [4032 * 1960]

if I use `ui.instantiateImageCodec(bytes)`
the result is ok 
![image](https://user-images.githubusercontent.com/5379447/66816753-30295680-ef6d-11e9-84d4-3cfe1e4b3d5a.png)

if I use `ui.instantiateImageCodec(bytes, targetWidth: 400)`

![image](https://user-images.githubusercontent.com/5379447/66816922-7c749680-ef6d-11e9-960f-fa7c9eefe6b0.png)

then I try print the the size:
```dart
ui.instantiateImageCodec(bytes, targetWidth: 400)
       .then((codec){
      codec
          .getNextFrame()
          .then(
              (frameInfo) {
            print("instantiated: ${frameInfo.image}");
          });
    });
```
the result: 

> I/flutter: instantiated: [400×194]

```dart
ui.instantiateImageCodec(bytes)
       .then((codec){
      codec
          .getNextFrame()
          .then(
              (frameInfo) {
            print("instantiated: ${frameInfo.image}");
          });
    });
```
the result:

> I/flutter: instantiated: [1960×4032]

I think the width and height has exchanged. the exif info ignore if set targetWidth?

how to resolve this problem?

**Target Platform:**android
**Target OS version/browser:** Flutter (Channel beta, v1.7.8+hotfix.3
**Devices:** SM-G9650

**Comment by janmoppel** [comment]
Hello @qylshy !

Thank you for posting an issue.
Can you please also attach the `flutter doctor -v` command output?

**Comment by qylshy** [comment]
> Hello @qylshy !
> 
> Thank you for posting an issue.
> Can you please also attach the `flutter doctor -v` command output?

[✓] Flutter (Channel beta, v1.7.8+hotfix.3, on Mac OS X 10.14 18A391, locale
    zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.3 at
      /Users/qiuyunlong/Desktop/work/flutter/flutter
    • Framework revision b712a172f9 (3 months ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/qiuyunlong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/qiuyunlong/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✗] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy

[!] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] IntelliJ IDEA Community Edition (version 2018.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • SM G9650 • 2350c218c80d7ece • android-arm64 • Android 9 (API 28)

! Doctor found issues in 5 categories.

**Comment by qylshy** [comment]
@janmoppel 
[✓] Flutter (Channel beta, v1.7.8+hotfix.3, on Mac OS X 10.14 18A391, locale
    zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.3 at
      /Users/qiuyunlong/Desktop/work/flutter/flutter
    • Framework revision b712a172f9 (3 months ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/qiuyunlong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/qiuyunlong/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✗] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy

[!] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] IntelliJ IDEA Community Edition (version 2018.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • SM G9650 • 2350c218c80d7ece • android-arm64 • Android 9 (API 28)

! Doctor found issues in 5 categories.

**Comment by iapicca** [comment]
Hi @qylshy 
could you please run 
`
 flutter channel stable
`
`
 flutter upgrade
`
If the issue persist please provide your updated  `flutter doctor -v` 
thank you

**Comment by qylshy** [comment]
> Hi @qylshy
> could you please run
> `flutter channel stable`
> `flutter upgrade`
> If the issue persist please provide your updated `flutter doctor -v`
> thank you

fixed ,thanks

**Comment by iapicca** [comment]
Hi @qylshy 
I'm glad you fixed the issue,
thank you for letting me know
