### ISSUE TITLE
How to add different border radius for tabs in flutter? 

### ISSUE THREAD

**Issue by chethangowda08** [flutter/flutter#42742]
List<Tab> tabList1 = [
    new Tab(
      child: Text(
        "car",
      ),
    ),
    new Tab(
      child: Padding(
        padding:EdgeInsets.symmetric(horizontal:13),
        child: Text(
          "bike",
        ),
      ),
    ),
  ];
 TabController _tabController1;
 // int _index;
  int _length = 2 ;
  @override
  void initState() {
    super.initState();
    _tabController1 = new TabController(length: _length, vsync: this);
    _index = 0;
    _tabController = new TabController(vsync: this, length: tabList.length);
    _index = 0;
    setState(() {
      _tabController = new TabController(vsync: this, length: tabList.length);
      this._index = _index;
      _tabController1 = new TabController(vsync: this, length: tabList1.length);
      this._index = _index;
      print("index");

      print(_index);
    });
  }
Container(
                            width: 320 / 360 * screenWidth,
                            height: 40 / 720 * screenHeight,
                            margin: EdgeInsets.only(
                                left: 20 / 360 * screenWidth,
                                top: 40 / 720 * screenHeight,
                                right: 20 / 360 * screenWidth),
                            decoration: BoxDecoration(
                              color: NeutralColors.ice_blue,
                              border: Border.all(
                                color: NeutralColors.ice_blue,
                                width: 1,
                              ),
                              borderRadius: BorderRadius.all(Radius.circular(5)),
                            ),
                           
                              child: Row(
                                children: <Widget>[
                                  Container(
                                    child: TabBar(
                                      controller: _tabController1,
                                      indicatorColor: Colors.transparent,
                                      indicator: _index == 1

                                          ? BoxDecoration(
                                        color: NeutralColors.purpleish_blue,
                                        border: Border.all(
                                          color: NeutralColors.purpleish_blue,
                                          width: 1,
                                        ),

                                        borderRadius: BorderRadius.only(

                                            topLeft: Radius.circular(5),
                                            bottomLeft: Radius.circular(5)),
                                      )
                                          : BoxDecoration(
                                        color: NeutralColors.purpleish_blue,
                                        border: Border.all(
                                          color: NeutralColors.purpleish_blue,
                                          width: 1,
                                        ),
                                        borderRadius: BorderRadius.only(
                                          topRight: Radius.circular(5),
                                          bottomRight: Radius.circular(5),
                                        ),
                                      ),
                                      labelColor: Colors.white,
                                      unselectedLabelColor: NeutralColors.blue_grey,
                                      indicatorSize: TabBarIndicatorSize.tab,
                                      tabs: tabList1,
                                      indicatorPadding: EdgeInsets.only(
                                          left: 5.0 / 360 * screenWidth,
                                          right: 5.0 / 360 * screenWidth),
                                      isScrollable: true,
                                      unselectedLabelStyle: TextStyle(
                                        fontSize: 14 / 720 * screenHeight,
                                        fontFamily: "IBMPlexSans-Medium",
                                        fontWeight: FontWeight.w400,
                                      ),
                                      labelStyle: TextStyle(
                                        fontSize: 14 / 720 * screenHeight,
                                        fontFamily: "IBMPlexSans-Medium",
                                        fontWeight: FontWeight.w500,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
