### ISSUE TITLE
[shared_preferences] 'shared_preferences/SharedPreferencesPlugin.h' file not found

### ISSUE THREAD

**Issue by aliyvz** [flutter/flutter#42745]
![image](https://user-images.githubusercontent.com/16401544/66830964-5942ea80-ef5f-11e9-9c7e-6d900b554875.png)

I tried other solutions, but I still can't solve this error in xcode. 
debugging also works, but not in the archive.

**Comment by BondarenkoStas** [comment]
similar to #https://github.com/flutter/flutter/issues/15409

**Comment by jmagman** [comment]
1.  What's the output of `flutter doctor -v`?
1. Can you confirm you have Runner.xcworkspace open and not Runner.xcproject?
1. Does `flutter build ios` work?  What about `flutter build ios --debug`?
1. Can you expand on what "debugging also works, but not in the archive" means?

**Comment by aliyvz** [comment]
Solved. Problem is project type, I changed "Runner.xcproject" to "Runner.xcworkspace".
Thanks @jmagman

**Comment by elliott-io** [comment]
I'm having this same problem. None of the previous comments are working.

**Comment by janshair** [comment]
Same problem. Runner.xcworkspace not working either
