### ISSUE TITLE
Status bar looks glitchy when navigating through contrasting screens

### ISSUE THREAD

**Issue by earyzhe** [flutter/flutter#42757]
When switching between screens with contrasting colors the status bar transition looks sketchy

![ezgif com-gif-maker](https://user-images.githubusercontent.com/26453863/66841902-a24c6c00-ef6a-11e9-9254-392f96af00e9.gif)

**Comment by nt4f04uNd** [comment]
This is working as expected, I think. If you want your status bar to be particular color instead of being transparent, consider [this bunch of code](https://stackoverflow.com/a/51013116/9710294).

**Comment by nt4f04uNd** [comment]
@earyzhe If this doesn't give you what you want, you can wrap your page, that you push to, wrap with a `Stack` like this:

```dart
Stack(
   children: <Widget>[
      Container(
          height: MediaQuery.of(context).size.height,
          width: MediaQuery.of(context).size.width,
          color: Colors.white, // any color that you want
       ),
       
       // Here put your route
   ]
)
```
Haven't tested this code, but I think you will catch the idea

**Comment by earyzhe** [comment]
The "Safe Area" widget was giving this effect. All sorted now after removing. My bad; thanks for the tip.
