### ISSUE TITLE
`flutter test` host binaries should compile with dart asserts enabled

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4276]
@a-siva asked me today for us to turn on dart asserts in our hosted `flutter test` pre-compiled binaries.  He says there are a ton of things they would catch and as long as we compile with `-O2` or above they should be relatively fast.

Hopefully I got that right. :)  Please correct me if I'm wrong.

@abarth @chinmaygarde or @jason-simmons are probably the best folks to wire this up.  He mentioned @zanderso would know the right flags if we need help.

Thanks!

**Comment by zanderso** [comment]
The GN flag is `dart_debug`:

https://github.com/dart-lang/sdk/blob/master/runtime/BUILD.gn#L13

At the moment this sets -O1, but we can bump it to -O2 if needed.

**Comment by eseidelGoogle** [comment]
I believe the patch would be to set that arg in this else:
https://github.com/flutter/engine/blob/master/sky/tools/gn#L66

@zanderso or @jason-simmons would you be willing to write the patch to do so?

**Comment by eseidelGoogle** [comment]
@jason-simmons looked at this afternoon.  dart_debug defines DEBUG, however our current `flutter test` host binaries are built optimized with NDEBUG defined.  So we'd either have to swap our `flutter test` configuration over to using unoptimized (debug) builds or we'd have to create separate "release" vs. "debug" configurations for `flutter test` (host) binaries.  Neither sound ideal.  Since we're going to rejigger all our testing in a few weeks after merging with the dartlang/sdk repository, lets punt on this for now.  FYI @johnmccutchan

**Comment by Hixie** [comment]
We're using unopt for our host builds now, so this is now something we should be able to do.

**Comment by a-siva** [comment]
This is being tracked in https://github.com/dart-lang/sdk/issues/29458 and hence closing this.
