### ISSUE TITLE
[web][Chrome][mobile] text editing state is transfered between fields

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#42769]
On Chrome on Android, when switching between a text area and an input box (these are the dom elements used in the web engine) the editing state transfers.

1. Write aaaaa to a text area
2. write bbbb to an input
3. return back to the same text area from (1). Write cccc

the text will look like bbbbaaaccc (the text from the input will appear partially here).

Same results was not observed on Chrome Desktop and Safari Mobile.

**Comment by mdebbar** [comment]
Turns out this is a bug in Chrome on Android. I filed a Chromium issue [here](https://crbug.com/1014974).

**Comment by mdebbar** [comment]
This is no longer reproducible.
