### ISSUE TITLE
flutter_gallery__back_button_memory diff-median regression.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#42763]
Noisy, so it's hard to tell the culprit commit.  May be #42031.

**Comment by jason-simmons** [comment]
This test is primarily intended to detect whether we are failing to release major resources (the engine, the Dart VM, large Skia objects) after an app is suspended.  Small changes in the (end memory - start memory) diff typically are not meaningful.

**Comment by Hixie** [comment]
This doesn't look significant.
