### ISSUE TITLE
Implement `Picture.toImage`, `Scene.toImage` in CanvasKit

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#42767]
We should implement `Scene.toImage` and `Picture.toImage` in the CanvasKit backend.

See also https://github.com/flutter/flutter/issues/49857 for HTML backend.

**Comment by hterkelsen** [comment]
It's definitely doable with the CanvasKit backend. Is there a use-case where `Scene.toImage` is needed today? It'll help me prioritize

**Comment by yjbanov** [comment]
I don't think it's high priority. In mobile Flutter it is used for screenshotting, but for web we will not use `toImage` for screenshot tests as we need to be able to screenshot non-CanvasKit back-end as well, so that use-case is out.

**Comment by jonahwilliams** [comment]
There are some tricks which use toImage to cache an expensive to render scene. For example, a rotating shape with a shadow.

**Comment by yjbanov** [comment]
> There are some tricks which use toImage to cache an expensive to render scene

That we could support in the HTML backend, as long as the app does not attempt to read the pixels. What we could do is treat the HTML DOM we generate as an "image" and composite it accordingly. Having said that, this usage of `toImage` makes me think that perhaps the `RepaintBoundary`/`addRetained` API is too brittle and we should fix that instead of relying on app-side code reading back pixels from the engine.

**Comment by deakjahn** [comment]
The important part is to stress that this is *not merely about somebody wanting to take a spanshot of a widget*. Right now there is simply no way to get hold of the byte data behind an `ui.Image`. None, nada, zilch. Neither in DomCanvas nor in CanvasKit. On both platforms, `toByteData()` is completely dead. This makes *any picture manipulation* completely impossible (even something as simple as resizing a picture because, well, that [doesn't work,](https://github.com/flutter/flutter/issues/57659) either). Or save an image, for instance. Or upload it, for instance.

It's quite understandable if you're less interested in DomCanvas (it *could* be done using the HTML5 canvas and `toBlob()` but quite a few steps are required so it might not worth it) but CanvasKit needs both feature parity and support for something as simple as this.

**Comment by deakjahn** [comment]
Please, consider the following changes:

`bitmap_canvas.dart`:

    String toDataUrl() {
      final dummy = _canvasPool.context; //!!!
      return _canvasPool.toDataUrl();
    }

Debug would also get away with an assert. This call creates the underlying `_canvas` if not yet done.

**Comment by deakjahn** [comment]
@kf6gpe As mentioned in the [other half of this issue](https://github.com/flutter/flutter/issues/49857), I have the fix for this bug.

**Comment by tomk9** [comment]
I have error `LayerScene.toImage not implemented.` from https://github.com/flutter/engine/blob/94b23abaae1f1e9c1937c2f2dc41146b7f9d37ad/lib/web_ui/lib/src/engine/compositor/layer_scene_builder.dart#L19
@deakjahn can your PR cover also this case?

**Comment by deakjahn** [comment]
I don't know. Can you create a very simple test code to repro it?

**Comment by tomk9** [comment]
```dart
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  GlobalKey globalKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: RepaintBoundary(
          key: globalKey,
          child: Container(
            height: 300,
            width: 300,
            color: Colors.red,
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _getImage,
        child: Icon(Icons.image),
      ),
    );
  }

  void _getImage() async {
    RenderRepaintBoundary boundary =
        globalKey.currentContext.findRenderObject();
    ui.Image image = await boundary.toImage();
    ByteData byteData = await image.toByteData(format: ui.ImageByteFormat.png);
    Uint8List pngBytes = byteData.buffer.asUint8List();
    print(pngBytes);
  }
}
```

**Comment by deakjahn** [comment]
@tomk9 At first glance it seems probable. However, there are sweeping changes in the engine these days and weeks, meaning that the engine itself is much of a moving target. This already made my PR to miss the automated tests. Until that's sorted out in the first place (I don't know how, I tried to contact the Google devs to get some info aboput how to proceed), I can't see the chance of adding any new changes. I'll try to look into it in my local source files, however. If I can solve it locally, there still is a chance to get it accepted. :-)

**Comment by yjbanov** [comment]
`Picture.toImage` and `Image.toByteData` have been implemented. Only `Scene.toImage` remains. I'm going to drop the priority of this.

**Comment by goncalo-palma-3r** [comment]
@yjbanov  since this has been deprioritized I have to ask - with `RepaintBoundary.toImage()` is it possible to change the implementation from relying on `Scene` to rely on`Picture` or `Image`?

**Comment by SwissCheese5** [comment]
This is currently preventing widget to image conversion and preventing cropping packages from working properly.

**Comment by yjbanov** [comment]
This has been implemented as of https://github.com/flutter/engine/pull/22085.
