### ISSUE TITLE
FittedBox.scaleDown can scale up the container used

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#42776]
Internal: b/142592677

Not sure if this is intentional, but it was unexpected from a usage standpoint (there are workarounds, so this is not critical).

With FittedBox widget removed:

![image](https://user-images.githubusercontent.com/6687929/66856786-cbed9f00-ef3a-11e9-80eb-a396c4bc574c.png)

With FittedBox widget:

![image](https://user-images.githubusercontent.com/6687929/66856799-d314ad00-ef3a-11e9-9c27-2cbf8a47776f.png)

Expected that using FittedBox.scaleDown would not increase the container size.

Full repro code:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: Scaffold(
        appBar: AppBar(title: Text('FittedBox test')),
        body: Container(
          color: Colors.red,
          child: Row(
            children: [
              Expanded(
                child: FittedBox(
                  fit: BoxFit.scaleDown,
                  child: Text('Leading'),
                ),
              ),
              Text('trailing'),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by shadowdogg** [comment]
I too have this issue, can't fix with alignment either as the widget is still using up space and pushes everything else, it seems to be wanting to center it

**Comment by PixelToast** [comment]
This happens because RenderFittedBox always attempts to preserve the aspect ratio of its child.

Preserving the aspect ratio works fine when both axes have tight constraints, but acts weirdly when one is unbounded while using FittedBox.scaleDown.

If anyone is interested in what the workaround looks like: https://dartpad.dartlang.org/a46beefac8ca33cbc2fb0dd4e61c02d0
