### ISSUE TITLE
Implement text field bouncing fix on the Web

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#42772]
https://github.com/flutter/flutter/pull/38573 was implemented in mobile Flutter, but on the Web we fail the 'has correct maxScrollExtent' test in `rendering/editable_test.dart`. We should fix it.

/cc @nturgut @mdebbar

**Comment by pedromassangocode** [comment]
Still valid since the test case mentioned is still being skipped on Web tests.

https://github.com/flutter/flutter/blob/6c1a29e54c412d244256d9a23e7c1f0a76e2f0e1/packages/flutter/test/rendering/editable_test.dart#L699-L740

**Comment by darrenaustin** [comment]
This appears to have been fixed, as I was able to reenable the test with #87700. Please reopen if you don't think this has been addressed.
