### ISSUE TITLE
[canvaskit]: support custom image decoding and caching

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#42789]
https://github.com/flutter/flutter/pull/41415 adds support for custom image decode size in order to reduce image cache memory usage.

We should support this on Web as well.

**Comment by GaryQian** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
CanvasKit should be ready for this now. The HTML renderer is architecturally incompatible with this concept. I'm categorizing this as a feature request for CanvasKit.

**Comment by yjbanov** [comment]
We're tracking this here now: https://github.com/flutter/flutter/issues/73120
