### ISSUE TITLE
Super-weird system bottom nav bar color reset when route comes from down

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#42795]
On some moment when I use `SlideTransition` and route comes from `Offset(0.0, 1.0)` to `Offset.zero)` this super strange bug appears. On this [video](https://youtu.be/b66w3cWwC3c) I manually change y-offset so you can see what is happening. 
This is happening only for one specific route, and I cant actually figure out, what triggers it. Full code of route is [here](https://github.com/nt4f04uNd/sweyer/blob/master/lib/routes/playerRoute.dart)

This is how I create route transition
https://github.com/nt4f04uNd/sweyer/blob/master/lib/components/route_transitions.dart

The problem disappears when I add `FadeTransition` between `TurnableSlideTransition`s

flutter doctor -v
```shell
[√] Flutter (Channel unknown, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.418], locale ru-RU)
    • Flutter version 1.7.8+hotfix.4 at C:\dev\src\flutter
    • Framework revision 20e59316b8 (3 months ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc1)
    • Android SDK at C:\Users\danya\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc1
    • ANDROID_HOME = C:\Users\danya\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed      instructions.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.39.1)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by BondarenkoStas** [comment]
@nt4f04uNd Please provide your flutter doctor -v output.

**Comment by nt4f04uNd** [comment]
@BondarenkoStas I am away from my PC right now, so for you can check out #40523, where I have provided doctor output. 

I will post the relevant output as soon as I come home.

**Comment by nt4f04uNd** [comment]
@BondarenkoStas done

**Comment by nt4f04uNd** [comment]
Fixed with https://github.com/flutter/flutter/issues/40590#issuecomment-601093769
