### ISSUE TITLE
Plugin: Media gallery access

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#428]
Mobile platforms provide APIs to access the media (photos, videos) on a device.

**Comment by mit-mit** [comment]
@collinjackson I think this is https://github.com/flutter/image_picker?

**Comment by collinjackson** [comment]
Yes

**Comment by collinjackson** [comment]
I think this actually M2 because the codelab phones don't have cameras, so the media gallery is the only way to get a photo into the app. However, I think it's basically done.

/cc @LarkAscending

**Comment by eseidelGoogle** [comment]
Sounds like we have something sufficient for M2 here, can close this and open additional bugs for more features.
