### ISSUE TITLE
Cirrus jobs are flaky because of Chrome crashes in golden tests.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#42804]
A sample failing run [is linked here](https://api.cirrus-ci.com/v1/task/6000216603361280/logs/test_web_engine.log?).

The error:
```
  Inconsistency detected by ld.so: dl-tls.c: 493: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
```

It looks like Chrome attempted to make an OpenGL call on a wrong thread (or a headless environment) and could not obtain the TLS slot for the thread specific OpenGL dispatch table.

`package:test` does use headless Chrome which may be a clue.

**Comment by Hixie** [comment]
We haven't seen this recently, and the log is 404, so this isn't really actionable any more.
