### ISSUE TITLE
`flutter` tool needs to verify the identity of servers from which it obtains data

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4280]
Need to validate that `flutter` tool is verifying the identity of GCS, etc.

This came up in security review.  FYI @abarth @devoncarew

**Comment by eseidelGoogle** [comment]
The attack scenario would be a network attacker posing as google cloud storage servers to give compromised binaries to `flutter`-using developers.

**Comment by Hixie** [comment]
Oh this specifically is referring to the `flutter` tool validating the identity of the servers it pulls data from.

Yes, we definitely should do that. We should also make sure we have a test that verifies that we do that correctly over time.

**Comment by Hixie** [comment]
Since this is a security vulnerability that applies to all users, leaving in m3.

**Comment by Hixie** [comment]
I checked all the places I could find where we download sensitive materials and all of them use code paths that (a) use the host certificate store, (b) catch expired certificates, and (c) complain about self-signed certificates.
