### ISSUE TITLE
Include a WebView in a Listview with other widgets

### ISSUE THREAD

**Issue by DenisDanis** [flutter/flutter#42803]
I have the follow code

`ListView(`
      `children: <Widget>[
        Text("Something"),
        WebView(
          initialUrl: "https://es.lipsum.com/",
        ),
        Text("Something")
      ],
    );`

but i can't put the webview, I know if wrap in container and set a custom height works, but I need dynamic height

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
