### ISSUE TITLE
Running a Flutter app from Atom plug-in fails

### ISSUE THREAD

**Issue by yyoon** [flutter/flutter#4281]
## Steps to Reproduce

* Create a new Flutter app with `flutter create`.
* Open the app folder within Atom
* Press the Run button on the Atom Flutter package toolbar.

It seems to me that the Atom plugin is providing `--checked` option by default, but the option was removed from the `flutter run` command recently. I'm using the atom-flutter v0.2.2.

## Flutter Doctor

```
youngseokyoon sample-app (flutter-test)$ flutter doctor
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /usr/local/google/home/youngseokyoon/Programming/flutter
    • Framework revision 646b5350d1 (5 days ago), engine revision 7fab0c350b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/home/youngseokyoon/Android/Sdk
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-122278751-122271652)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

## Logs and Crash Reports

(at the bottom panel of Atom editor)
```
flutter run --checked --debug-port=16255 --start-paused --device-id HT4BVWV00023 • flutter logs
sample-app/ • checked mode • debug
Could not find an option named "checked".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
exited with code 64
```

**Comment by devoncarew** [comment]
@yyoon, there should be an update available for the `dartlang` plugin, if you check for that from the atom UI. That new version of the plugin will not try and send in the `--checked` cli option. Can you update and verify that that solves the issue? Thanks for the report!

**Comment by yyoon** [comment]
I did already have the latest version of dartlang package, so I just restarted the Atom editor and it solved my problem. I probably should have tried that before submitting this issue. Thanks for the prompt response. :smile:
