### ISSUE TITLE
 When I create a new project, I will report the following error

### ISSUE THREAD

**Issue by hua407035000** [flutter/flutter#42812]
Could not find an option named "androidx". Run 'flutter -h' (or 'flutter   -h') for available flutter commands and options.

SDK是1.5.4_hotfix-2

如果我用SDK1.7.8就能成功新建项目，用SDK154就不行
请各位大佬指点一下这要怎么解决
(google translate)
If I can successfully create a new project with SDK1.7.8, I can't use SDK1.5.4.
Please tell me how to solve this problem.

**Comment by spWang** [comment]
升级版本解决，现在最新是：
Flutter 1.9.1+hotfix.4 • channel stable • git@github.com:flutter/flutter.git
Framework • revision cc949a8e8b (3 weeks ago) • 2019-09-27 15:04:59 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

**Comment by BondarenkoStas** [comment]
@hua407035000 Can you specify what's the problem? Do you have difficulties with migrating to AndroidX?

**Comment by weiweiabc109** [comment]
me too, upgrading...

**Comment by hua407035000** [comment]
131/5000  
Is this

I'm an android developer

I'm using android studio version 3.5

My computer has two versions of the flutter Sdk

One is 1.7.8 and the other is 1.5.4

I created an empty project with SDK 1.7.8 without any problems

This error is reported when I create with 1.5.4.

**Comment by iapicca** [comment]
Hi @hua407035000 
given your last message I understand that thee issue
doesn't occur when using a more recent version of Flutter.
Please run
`flutter channel stable`flutter upgrade
to 

 I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you"

**Comment by iapicca** [comment]
Hi @hua407035000
given your last message I understand that thee issue
doesn't occur when using a more recent version of Flutter.
Please run
`flutter channel stable`
`flutter upgrade`
to be sure you are using the latest stable version of Flutter

I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by cbfg5210** [comment]
检查一下有没配置了sdk路径:
![TIM图片20191230161012](https://user-images.githubusercontent.com/12880545/71573496-2b615100-2b1f-11ea-8a42-b555298e68bd.png)

**Comment by iapicca** [comment]
Hi @hua407035000 
could you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter clean`
`flutter pub cache repair`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem.

Please refrain from posting pictures if not necessary.

Thank you

**Comment by zayngdev** [comment]
Basically, if you run 
`flutter channel stable, `
`flutter upgrade`
it should would, just test on my machine with flutter stable version 1.12.13+hotfix.5

**Comment by dnfield** [comment]
Flutter version 1.5.4 did not have an androidx option.  You need to upgrade your version of Flutter if you want to use that option.  It was first introduced in 1.7.1: https://github.com/flutter/flutter/commit/d0e45a2369e9b7603c5d8ca33280128fba01de38
