### ISSUE TITLE
GestureDetector is not trigger onDoubleTap but onTap at the first time.

### ISSUE THREAD

**Issue by SugyoIn-LBSTech** [flutter/flutter#42817]
## Steps to Reproduce

```
@override
Widget build(BuildContext context) {
  _CardRegisterPageState cardRegisterPageState =
      _CardRegisterPageState.of(context);

  print('Widget build');

  return Align(
    alignment: Alignment.topCenter,
    child: GestureDetector(
      behavior: HitTestBehavior.opaque,
      onTap: () {
        cardRegisterPageState.setState(() {
          print('tap');
        });
      },
      onDoubleTap: () {
        cardRegisterPageState.setState(() {
          print('double tap');
        });
      },
      child: Text(
        'PLEASE TAP OR DOUBLE TAP',
        style: Theme.of(context).textTheme.display1,
        textAlign: TextAlign.center,
      ),
    ),
  );
}
```

From above code. When I double tap the widget. GestureDetector is not trigger onDoubleTap but onTap at the first time. After then onDoubleTap is triggered well at double tapping. All the HitTestBehaviors are occur same result. Is there something I wrong?

**Target Platform: Android**
**Target OS version/browser: Android 9.0**
**Devices: Samsung Galaxy S8+ (SM-G955N))**

### flutter run --verbose
```
[+32258 ms] D/ViewRootImpl@903fb8a[MainActivity]( 6430): ViewPostIme pointer 0
[  +39 ms] D/ViewRootImpl@903fb8a[MainActivity]( 6430): ViewPostIme pointer 1
[  +80 ms] D/ViewRootImpl@903fb8a[MainActivity]( 6430): ViewPostIme pointer 0
[  +50 ms] D/ViewRootImpl@903fb8a[MainActivity]( 6430): ViewPostIme pointer 1
[ +331 ms] I/flutter ( 6430): tap
[  +70 ms] I/flutter ( 6430): Widget build
[+10316 ms] D/ViewRootImpl@903fb8a[MainActivity]( 6430): ViewPostIme pointer 0
[  +29 ms] D/ViewRootImpl@903fb8a[MainActivity]( 6430): ViewPostIme pointer 1
[  +72 ms] D/ViewRootImpl@903fb8a[MainActivity]( 6430): ViewPostIme pointer 0
[  +45 ms] D/ViewRootImpl@903fb8a[MainActivity]( 6430): ViewPostIme pointer 1
[  +11 ms] I/flutter ( 6430): double tap
[  +68 ms] I/flutter ( 6430): Widget build
[+7458 ms] D/ViewRootImpl@903fb8a[MainActivity]( 6430): ViewPostIme pointer 0
[  +51 ms] D/ViewRootImpl@903fb8a[MainActivity]( 6430): ViewPostIme pointer 1
[  +56 ms] D/ViewRootImpl@903fb8a[MainActivity]( 6430): ViewPostIme pointer 0
[  +38 ms] D/ViewRootImpl@903fb8a[MainActivity]( 6430): ViewPostIme pointer 1
[   +6 ms] I/flutter ( 6430): double tap
[  +46 ms] I/flutter ( 6430): Widget build
```

### flutter analyze
```
   info - Avoid empty statements - lib\component\loading_progress.dart:39:5 - empty_statements
   info - Dead code - lib\component\loading_progress.dart:39:5 - dead_code
   info - Dead code - lib\component\poi_list.dart:48:18 - dead_code
   info - The exception variable 'e' isn't used, so the 'catch' clause can be removed - lib\data\interest_place_data.dart:97:31 - unused_catch_clause
   info - The declaration '_System' isn't referenced - lib\page\config_page.dart:268:7 - unused_element
   info - The declaration '_About' isn't referenced - lib\page\config_page.dart:335:7 - unused_element
   info - The value of the local variable 'entranceGuide' isn't used - lib\page\ray_detect_page.dart:148:26 - unused_local_variable
   info - Dead code - lib\page\search_history_page.dart:39:16 - dead_code

```

### flutter doctor -v
```
[√] Flutter (Channel master, v1.10.7-pre.109, on Microsoft Windows [Version 10.0.18362.418], locale ko-KR)
    • Flutter version 1.10.7-pre.109 at C:\Users\LBSTECH\flutter
    • Framework revision 056f7244ef (2 weeks ago), 2019-10-01 18:09:24 -0400
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.4.0 1103600280)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\LBSTECH\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.39.1)
    • VS Code at C:\Users\LBSTECH\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (3 available)
    • SM G955N        • ce0317136be4803b0c • android-arm64  • Android 9 (API 28)
    • Chrome          • chrome             • web-javascript • Google Chrome 77.0.3865.120
    • Headless Server • headless-server    • web-javascript • Flutter Tools

• No issues found!

```

**Comment by iapicca** [comment]
Hi @SugyoIn-LBSTech 
the issue seems to be solved
[code sample](https://dartpad.dev/0392e1a021a77ff144ca4f4a3ebd0f01)
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by nogegon** [comment]
Hi,
I face the same issue.
Since the problem is on the "first" double tap, in the code sample, make sure you have: 
 bool _hasDoubleTap = true;

Then, if I take the code sample, put it into VS code and run it on a real device, I still get the error that the Double Tap is not detected, I get onTap instead (green color instead of yellow).
It works OK in the AVD.

Here is my flutter doctor -v output:

[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.17.4 at c:\src\flutter
    • Framework revision 1ad9baa8b9 (4 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\replaced\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\replaced\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\replaced\AppData\Local\Programs\Microsoft VS Code
    • Flutter version 1.17.4 at c:\src\flutter
    • Framework revision 1ad9baa8b9 (4 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\replaced\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\replaced\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\replaced\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (2 available)
    • E2333                        • YT911B44R3    • android-arm64 • Android 6.0.1 (API 23)
    • Android SDK built for x86 64 • emulator-5554 • android-x64   • Android 5.0.2 (API 21) (emulator)

• No issues found!

**Comment by iapicca** [comment]
<details>
  <summary>logs</summary>

```bash

```

</details>


<details>
  <summary>doctor</summary>

```console

```

</details>
