### ISSUE TITLE
TextField Issue: input some content, switch the input language and input something, then click delete, all of the second language content will be deleted at one time 

### ISSUE THREAD

**Issue by usagiGong** [flutter/flutter#42824]
In the Android device, use the native keyboard to input English, then switch Chinese and input Chinese, click the delete button, all Chinese will be deleted together, instead of deleting a single character.

**Comment by TahaTesser** [comment]
Hi @usagiGong 
i wasn't able to reproduce this issue on latest `dev`
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment]
@usagiGong 
I can't reproduce it with Redmi Note 7 (Android 9) Gboard with `dev v1.18.0-8.0.pre`.
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of 'flutter doctor -v'  please.
