### ISSUE TITLE
SelectableText not compatibility flutter for web

### ISSUE THREAD

**Issue by bingoogolapple** [flutter/flutter#42823]
* I build GitHub Pages and Mobile App using the flutter for web，but I've found SelectableText Widget not compatibility web.
```dart
import 'package:bga_issue_blog/page/blog_detail_page.dart';
import 'package:bga_issue_blog/utils/route_util.dart';
import 'package:flutter/material.dart';

class IssueItem extends StatelessWidget {
  const IssueItem({Key key, this.issue}) : super(key: key);

  final issue;

  @override
  Widget build(BuildContext context) {
    return Container(
      child: ListTile(
        title: GestureDetector(
          child: SelectableText(issue['title']),
          onTap: () => RouteUtil.routeWithFadeTransition(context, BlogDetailPage(number: issue['number'])),
        ),
        trailing: SelectableText(DateTime.tryParse(issue['created_at']).toString().substring(0, "yyyy-MM-dd HH:mm".length)),
      ),
      decoration: BoxDecoration(
        border: Border(bottom: BorderSide(color: Color.fromARGB(255, 238, 238, 238))),
      ),
    );
  }
}
```
* Does not behave properly in the browser
![image](https://user-images.githubusercontent.com/8949716/66898010-d8e9bb80-f02a-11e9-90fa-7688d2363212.png)
* It works fine on the phone
![image](https://user-images.githubusercontent.com/8949716/66897908-97591080-f02a-11e9-888a-97251d4130da.png)
* [Source Code](https://github.com/bingoogolapple/bga_issue_blog)
* [PreView](http://issues.bingoogolapple.cn)

**Comment by BondarenkoStas** [comment]
@bingoogolapple Thank you for the report and example. I'm going to close the issue in favour of #40663 to avoid duplication. Please follow it there and upvote.
