### ISSUE TITLE
[regression] Button text color is no more set according to ThemeData.brightness value

### ISSUE THREAD

**Issue by bleroux** [flutter/flutter#42838]
## Description

Since https://github.com/flutter/flutter/pull/39627, Material Button text color is black when setting ThemeData.brightness to dark or light (when using ButtonTextTheme.normal)

According to  ButtonTextTheme.normal documentation, '
'Button text is black or white depending on [ThemeData.brightness].'

Since https://github.com/flutter/flutter/pull/39627 , buttonTheme colorScheme is set to 'ColorScheme.light()' by default and not according to ThemeData.brightness

## Steps to Reproduce

Sample code :

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        brightness: Brightness.light,
        buttonTheme: ButtonThemeData(textTheme: ButtonTextTheme.normal),
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: FlatButton(
        color: Colors.blue,
        child: Text('Button'),
        onPressed: () => print('Button pressed'),
      ),
    );
  }
}
```

This renders :
![image](https://user-images.githubusercontent.com/840911/66908648-b98f6600-f00b-11e9-91b4-a8029ba81e55.png)

When setting brightness to dark ('brightness: Brightness.dark)' it renders the same :
![image](https://user-images.githubusercontent.com/840911/66908834-0d9a4a80-f00c-11e9-946a-b7b9beef27e1.png)
In this last case, the text color should be white

**Target Platform:** Android
**Target OS version/browser:**
**Devices:** emulator and physical devices

## Logs

[✓] Flutter (Channel master, v1.10.15-pre.137, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.10.15-pre.137 at /home/bruno/flutter
    • Framework revision b9817b4f59 (il y a 9 heures), 2019-10-15 17:36:34 -0700
    • Engine revision 540fc977bb
    • Dart version 2.6.0 (build 2.6.0-dev.7.0 70a7ef3f58)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /home/bruno/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /home/bruno/Produits/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 8.0.0
    • GNU Make 4.2.1

[✓] Android Studio (version 3.4)
    • Android Studio at /home/bruno/Produits/android-studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.39.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • SNE LX1 • HYF0219508003668 • android-arm64 • Android 9 (API 28)
    • Linux   • Linux            • linux-x64     • Linux

• No issues found!

**Comment by bleroux** [comment]
Screenshots **before** https://github.com/flutter/flutter/pull/39627 :

- brightness: Brightness.light : 
![image](https://user-images.githubusercontent.com/840911/66917927-96ba7d00-f01e-11e9-866d-4825f58702a9.png)


- brightness: Brightness.dark :
![image](https://user-images.githubusercontent.com/840911/66917853-768abe00-f01e-11e9-89c9-214ae415855d.png)

**Comment by shihaohong** [comment]
I took a quick look at this and it seems that it gets relatively complicated since ButtonTheme's colorScheme takes priority over ThemeData's colorScheme. Since https://github.com/flutter/flutter/pull/39627 defaults ButtonTheme.colorScheme to ColorScheme.light(), ThemeData's colorScheme will never be looked at. 

Overall, I think the real fix would require a breaking change at the very least. I'll revert the PR for now to prevent this regression
