### ISSUE TITLE
SelectableText Selected Text

### ISSUE THREAD

**Issue by glennmichaelmejias** [flutter/flutter#42837]
How to get the selected text from SelectableText when users start selecting text or without pressing the copy button?

**Comment by brylie** [comment]
This might be facilitated by supporting an `onSelectionChange` method on the `SelectableText` class. That way, users could hook into this event, and other functionality could be built on top.

This API would also be consistent with or even based on the same code from, the Flutter RenderEditable class

https://api.flutter.dev/flutter/rendering/SelectionChangedHandler.html

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.

**Comment by brylie** [comment]
@BondarenkoStas could this be considered as a feature request? I.e. there doesn't seem to be a SelectionChanged handler for the `SelectableText` class.

**Comment by rymasc** [comment]
is anyone working on this? If not I'm happy to pick it up and see if I can add it.

**Comment by a-oboh** [comment]
> is anyone working on this? If not I'm happy to pick it up and see if I can add it.

Are you still working on this?

**Comment by rymasc** [comment]
@a-oboh  Sorry for the delayed response. I've been spending time researching how the flutter framework works in my free time to get this done so I haven't made much progress on this issue. If you're well versed in flutter you will likely be able to get this done quicker than I would.
