### ISSUE TITLE
[web] Messed up alignments in release build

### ISSUE THREAD

**Issue by ja2375** [flutter/flutter#42835]
I am developing a big application for the web, and everything works just fine in debug mode. But when i build it in release mode, every alignment (`CrossAxisAlignment`) is wrongly set to CrossAxisAlignment.start by default.

Not only Rows are affected, but also `Tooltip`s. See screenshot:
![image](https://user-images.githubusercontent.com/3824182/66911411-bd71b700-f010-11e9-8988-aa3accddfd53.png)

I tested this with various Flutter channels and this always happens. Attaching `flutter doctor -v` output below:
```
[✓] Flutter (Channel master, v1.10.15-pre.137, on Mac OS X 10.14.6 18G103, locale es-ES)
    • Flutter version 1.10.15-pre.137 at /Users/ja2375/flutter
    • Framework revision b9817b4f59 (10 hours ago), 2019-10-15 17:36:34 -0700
    • Engine revision 540fc977bb
    • Dart version 2.6.0 (build 2.6.0-dev.7.0 70a7ef3f58)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/ja2375/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • Chrome          • chrome          • web-javascript • Google Chrome 77.0.3865.120
    • Headless Server • headless-server • web-javascript • Flutter Tools

• No issues found
```
NOTE: This only happens in flutter for web in release mode (`flutter run -d chrome --release`)

**Comment by theshivamlko** [comment]
can u share your code or project. I also made project in  FlutterWeb , I got responsive issue only.

**Comment by ja2375** [comment]
I cannot share the project as it is company internal, sorry.

**Comment by ferhatb** [comment]
Are you able to repro in flutter_gallery example on master ?

**Comment by ja2375** [comment]
Interestingly enough, this only seems to happen in desktop browsers. I tested it in chrome for mac and chrome for windows and it happens. But then i test it on Chrome on Android 10 and it does not seem to happen:
![image](https://user-images.githubusercontent.com/3824182/66993053-37667680-f0cb-11e9-92c8-361c13e2d5d0.png)

**Comment by ferhatb** [comment]
So the engine either renders text as a <p> or inside <canvas>, could you please check which one by looking at elements in dom and doing a search for the text, if nothing shows up it's canvas. I'm suspecting either cssreset not doing things properly or we have a bug in text measurement where state is leaking.

**Comment by ja2375** [comment]
If i understood you, i just looked up in the dom for the word "Menú" which is having this wrong position as you saw on images, but i saw nothing out of place.

I used chrome dev tools to do the search. Here is a screenshot:
![Screenshot](https://user-images.githubusercontent.com/3824182/67039525-d453fe80-f121-11e9-8dbe-68164191056a.png)

Is this what you meant me to do? Is there anything else i can try to help you?

Thanks for the help!

**Comment by ja2375** [comment]
I managed to solve this. I had an uncaught exception in my code that was throwing in rendering.dart, but it wasn't affecting the behavior of the app, as it worked perfectly well despite of that exception.

It has been quite hard to see that exception was causing this issue, because i didn't really know where that exception was being thrown from. But i finally found it, fixed it and now everything is correctly aligned in the release build.

I still don't know why this rendering exception was only affection the release build, and only on desktop browsers...

**Comment by ferhatb** [comment]
@ja2375 , thx for tracking this down to exception. closing this issue.
