### ISSUE TITLE
Flutter Hot reload/restart issue in stable, after flutter upgrade in master for Flutter Desktop

### ISSUE THREAD

**Issue by theshivamlko** [flutter/flutter#42834]
I am a Flutter Developer working on mobile Apps, recently worked on FlutterWeb from master channel ,everything worked. Then  after I upgrade for windows setup ,many existing mobile apps Hot Reload and Hot Restart issue is coming.
After *Hot Restart* and  code is not updated in UI, console prints 
`Error 105 received from application: Isolate must be runnable`

After *Hot Reload*, UI is hanged and code is not updated in UI, console prints .
`An isolate is paused; interface might not update.`
I had to *Hot Restart* with same error above

## Steps to Reproduce
 

1. Upgraded Flutter Channel Master, 
2. Installed Windows SDK as mentioned by Flutter
 

**Target Platform: Mobile ** 
**Target OS version/browser: Android 9**
**Devices:OnePlus 3T**

## Logs

```
```

```
```

**flutter doctor -v**   // stable
```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.17763.805], locale en-US)
    • Flutter version 1.9.1+hotfix.4 at C:\Users\Navoki\flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Navoki\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Navoki\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.2
    • Flutter plugin version 40.1.1
    • Dart plugin version 191.8423

[√] VS Code (version 1.39.0)
    • VS Code at C:\Users\Navoki\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (2 available)
    • ONEPLUS A3003 • ec6202af        • android-arm64 • Android 9 (API 28)
    • ONEPLUS A3003 • 10.5.49.13:5555 • android-arm64 • Android 9 (API 28)

• No issues found!

```
**flutter doctor -v**   // master

**Comment by BondarenkoStas** [comment]
Thank you for the report @theshivamlko ! I'm going to close it in favour of https://github.com/flutter/flutter/issues/34954. Please follow it there and upvote.
CC @jonahwilliams still in v1.9.1+hotfix.4.
