### ISSUE TITLE
[local_auth] Cant get intent from FlutterFragmentActivity so cant use local_auth above 0.4.0+1

### ISSUE THREAD

**Issue by Olifemus** [flutter/flutter#42843]
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4)
• Flutter version 1.9.1+hotfix.4
• Framework revision cc949a8 (3 weeks ago), 2019-09-27 15:04:59 -0700
• Engine revision b863200c37
• Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.2
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.1, Build version 11A1027
• CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 40.2.2
• Dart plugin version 191.8423
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)

• No issues found!
```

**Comment by Olifemus** [comment]
[✓] Flutter (Channel stable, v1.9.1+hotfix.4)
    • Flutter version 1.9.1+hotfix.4
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)

• No issues found!

**Comment by snaeji** [comment]
https://github.com/ryanheise/audio_service/issues/87

**Comment by snaeji** [comment]
@Olifemus can you give an example of some packages that are incompatible?

**Comment by Olifemus** [comment]
@snaeji   i use native pushes that can launch my app with some arguments and try to get it from intent

**Comment by stuartmorgan** [comment]
Is this still an issue? If so, can you provide more detail, such as a minimal sample of what's not working? I'm not clear from just the title what the problem you're reporting is.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by snaeji** [comment]
I think this is not a problem any more :)

At least i'm using FlutterFragmentActivity and audio_service without a problem.
