### ISSUE TITLE
The text font does not look right

### ISSUE THREAD

**Issue by zw1924** [flutter/flutter#42848]
![C3C65778F603223B5E2DDBA8C287CCBE](https://user-images.githubusercontent.com/54323514/66929171-24b95680-f065-11e9-9388-25e27e5ed9e9.jpg)

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15
    19A582a, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK
    version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
[✓] VS Code (version 1.39.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
