### ISSUE TITLE
Output of "flutter run" when using firebase_admob is very spammy

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#42849]
Moving this from https://github.com/Dart-Code/Dart-Code/issues/1980, since it affects using `flutter run` as well as editors.

If you use the `firebase_admob` package and then run with `flutter run` (repro instructions [here](https://github.com/Dart-Code/Dart-Code/issues/1980#issuecomment-529995655)) the output spews a lot of stuff repeatedly:

![image](https://user-images.githubusercontent.com/379339/64467655-159fca00-d0f1-11e9-8eb8-1cc023c85461.png)

Flutter does filter the logcat output, but it includes anything that has the process ID of the app (even if you're not running with `-v`). In this case that seems very excessive, but I don't know if the fix should be for Flutter to filter better, or for the plugin not to do whatever is causing this.

**Comment by dmdeklerk** [comment]
Very similar issue is experienced on our end. 
Debug Console receives a continues stream of these on an on and on.

```
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 1
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 2
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 1
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 2
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 1
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 2
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 1
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 2
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 1
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 2
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 1
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 2
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 1
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 2
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 1
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 2
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 1
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 2
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 1
D/BufferQueueProducer(14383): [SurfaceTexture-0-14383-0](this:0x7065ebb000,id:0,api:1,p:411,c:14383) cancelBuffer: slot 2
```

**Comment by sjghose** [comment]
Makes it impossible to do any debugging with Test ads. Ads slow down scroll behavior considerably so it's important to tweak the number of ads. Extremely chatty logs with lots of redundant logging. Would appreciate if we could turn this level of logging off.
D/AudioManager(24376): getStreamVolume isRestricted mode = 0
D/AudioManager(24376): getStreamVolume isRestricted mode = 0
D/AudioManager(24376): getStreamVolume isRestricted mode = 0
D/AudioManager(24376): getStreamVolume isRestricted mode = 0
D/AudioManager(24376): getStreamVolume isRestricted mode = 0
D/AudioManager(24376): getStreamVolume isRestricted mode = 0
D/AudioManager(24376): getStreamVolume isRestricted mode = 0
D/AudioManager(24376): getStreamVolume isRestricted mode = 0
I/s.headline_new(24376): Background concurrent copying GC freed 601831(24MB) AllocSpace objects, 0(0B) LOS objects, 36% free, 42MB/66MB, paused 130us total 141.334ms
D/AudioManager(24376): getStreamVolume isRestricted mode = 0
D/AudioManager(24376): getStreamVolume isRestricted mode = 0
D/AudioManager(24376): getStreamVolume isRestricted mode = 0
D/AudioManager(24376): getStreamVolume isRestricted mode = 0
D/AudioManager(24376): getStreamVolume isRestricted mode = 0

**Comment by erperejildo** [comment]
after 5 months do we have any update about this?

**Comment by DanTup** [comment]
@jonahwilliams this is tagged admob, though @devoncarew suggested this may be better handled in the tool (for example with some ability for the editor to opt-in to verbose output or not).

I'm not sure if filtering out *all* of the logcat output might remove too much (for example if the user calls `print`?), so it might require some understanding of the specific lines?

**Comment by jonahwilliams** [comment]
`E` is considered an error, so filtering out this sort of message has the potential to hide very serious problems. I would consider hiding more logs  a bandaid approach for firebase_admob

**Comment by DanTup** [comment]
FWIW, the next version of VS Code (not Dart-Code, but the editor itself) includes a filter in the Debug Console that might make this a little less painful (for VS Code users).

<img width="1421" alt="Screenshot 2020-08-24 at 13 15 45" src="https://user-images.githubusercontent.com/1078012/91043775-17b5ae00-e60c-11ea-926c-150511ec77cf.png">
<img width="1399" alt="Screenshot 2020-08-24 at 13 15 56" src="https://user-images.githubusercontent.com/1078012/91043778-197f7180-e60c-11ea-8aa3-e2666c3e57e6.png">

**Comment by stuartmorgan** [comment]
Closing, as `firebase_admob` is [now deprecated](https://pub.dev/packages/firebase_admob/versions/0.11.0+2).

**Comment by erperejildo** [comment]
I get the same spam messages with google_ads
