### ISSUE TITLE
Release build crashes when app contains static extensions (experimental)

### ISSUE THREAD

**Issue by filipproch** [flutter/flutter#42845]
I am using Dart static extensions - I know they are experimental - and it seems to work alright in debug mode. Great job on that, it's amazing!!! 

When trying to build the app for release tho, it crashes (see below).

## Steps to Reproduce

1. Have the latest SDK from `master`
2. Define an extension function in code
3. `flutter build apk --release`
4. Crashes after while

## Logs

```
```

Unhandled exception:
type 'Extension' is not a subtype of type 'Member' in type cast
#0      _TreeShakerPass2.visitLibrary.<anonymous closure> (package:vm/transformations/type_flow/transformer.dart:933:42)
#1      ListMixin._filter (dart:collection/list.dart:307:15)
#2      ListMixin.removeWhere (dart:collection/list.dart:295:5)
#3      _TreeShakerPass2.visitLibrary (package:vm/transformations/type_flow/transformer.dart:926:28)
#4      Library.accept (package:kernel/ast.dart:521:38)
#5      transformList (package:kernel/ast.dart:6912:27)
#6      Component.transformChildren (package:kernel/ast.dart:6740:5)
#7      _TreeShakerPass2.transform (package:vm/transformations/type_flow/transformer.dart:918:15)
#8      TreeShaker.transformComponent (package:vm/transformations/type_flow/transformer.dart:368:12)
#9      transformComponent (package:vm/transformations/type_flow/transformer.dart:80:47)
#10     _runGlobalTransformations (package:vm/kernel_front_end.dart:379:5)
<asynchronous suspension>
#11     compileToKernel (package:vm/kernel_front_end.dart:304:11)
<asynchronous suspension>
#12     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:438:54)
#13     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#14     _rootRun (dart:async/zone.dart:1120:38)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#21     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#22     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#23     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Compiler terminated unexpectedly.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/filip/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 768

* What went wrong:
Execution failed for task ':app:compileFlutterBuildReleaseArm'.
> Process 'command '/Users/filip/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 59s

```
```

[✓] Flutter (Channel master, v1.10.15-pre.137, on Mac OS X 10.15 19A583, locale en-US)
    • Flutter version 1.10.15-pre.137 at /Users/filip/development/flutter
    • Framework revision b9817b4f59 (14 hours ago), 2019-10-15 17:36:34 -0700
    • Engine revision 540fc977bb
    • Dart version 2.6.0 (build 2.6.0-dev.7.0 70a7ef3f58)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/filip/development/android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/filip/development/android
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 40.1.4
    • Dart plugin version 192.6817.14

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (4 available)
    • iPhone 8        • 5B61F207-34FD-4B8B-AAE1-8DE09331FA7D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
    • macOS           • macOS                                • darwin-x64     • Mac OS X 10.15 19A583
    • Chrome          • chrome                               • web-javascript • Google Chrome 77.0.3865.120
    • Headless Server • headless-server                      • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```
```

**Comment by alexmarkov** [comment]
[The fix](https://github.com/dart-lang/sdk/commit/c19adc635542004d2c2cdac55b447e7175391bf8) landed in Dart SDK. Hopefully it will be rolled to Flutter soon.

**Comment by creativecreatorormaybenot** [comment]
@alexmarkov What Dart SDK version would that be or where can I check that?

**Comment by alexmarkov** [comment]
The fix was rolled into Flutter master (bleeding edge) in https://github.com/flutter/flutter/pull/43017. 

@creativecreatorormaybenot The fix is currently in the master branch (bleeding edge) of Dart SDK. You can watch for the merge request issue (linked above) to check if this fix is going to be merged into dev branch and included into the next stable release of Dart SDK.
