### ISSUE TITLE
flutter+IOS, TextField in IOS 13, can not select chinese character into editBox? but,only ios or flutter is OK. WHY?

### ISSUE THREAD

**Issue by CoderNeilz** [flutter/flutter#42841]
flutter+IOS, TextField in IOS 13, can not select chinese character into editBox? but,only ios or flutter is OK. WHY?

**Comment by BondarenkoStas** [comment]
@CoderNeilz please provide your flutter doctor -v output. Do you get any error into stack trace?

**Comment by rockingdice** [comment]
Did you create a TextEditController instance inside a build method?

**Comment by CoderNeilz** [comment]
> Did you create a TextEditController instance inside a build method?

yes, this is my code. i think it is correct, but ... when it add to ios project ,it failed

`TextField(
              autocorrect: false,
              focusNode: focusNode,
              autofocus: true,
              controller: textEditingController,
              style: TextStyle(
                fontSize: 14,
              ),
              decoration: InputDecoration(
                border: InputBorder.none,
                isDense: true,
                prefixIcon: Container(
                  height: 38,
                  width: 38,
                  child: Padding(
                    padding: const EdgeInsetsDirectional.fromSTEB(0, 9, 0, 9),
                    child: SvgImageButton(
                      assetName: 'xxx.svg',
                      width: 20,
                      height: 20,
                    ),
                  ),
                ),
                suffixIcon: textEditingController.text.isNotEmpty
                    ? SvgImageButton(
                        padding:
                            const EdgeInsetsDirectional.fromSTEB(0, 9, 0, 9),
                        assetName: 'xxx.svg',
                        width: 20,
                        height: 20,
                        onTap: onClearSearchTap,
                      )
                    : null,
                hintMaxLines: 1,
                hintText: ' search file',
                filled: false,
                //fillColor: Color(0xFFF8F8F8),
              ),
              onChanged: onSearchTap,
            )`

**Comment by rockingdice** [comment]
@CoderNeilz 
Your code doesn't include the build function.
You can try to create the textEditingController in the state of its parent widget and use it in your TextField. Don't create the controller inside the build method. It will lead to some issues.
You can check https://github.com/flutter/flutter/issues/40833 too.

**Comment by CoderNeilz** [comment]
> @CoderNeilz
> Your code doesn't include the build function.
> You can try to create the textEditingController in the state of its parent widget and use it in your TextField. Don't create the controller inside the build method. It will lead to some issues.
> You can check #40833 too.

![image](https://user-images.githubusercontent.com/12480357/66984344-1a429f80-f0ed-11e9-9802-ab238262f058.png)
i dont create textEditingController in build method .

**Comment by CoderNeilz** [comment]
> @CoderNeilz please provide your flutter doctor -v output. Do you get any error into stack trace?

wanxxxeng-MB:QQPlayerFlutter wanxxxeng$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.5 18F203, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.4 at /Users/wanxxxeng/flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/wanxxxeng/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,.oa.com,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (2 available)
    • vivo X7             • csssxxx146                   • android-arm64 • Android 5.1.1 (API 22)
    • “rxxxx”的 iPhone • xxxxxx • ios           • iOS 13.0

• No issues found!

**Comment by CoderNeilz** [comment]
a third library report (hook ios keyboard) make this issue
