### ISSUE TITLE
Make material dialog padding from screen borders customizable

### ISSUE THREAD

**Issue by marinat** [flutter/flutter#42852]
https://stackoverflow.com/questions/53913192/flutter-change-the-width-of-an-alertdialog
Now I have to copy the whole class dialog.dart. It would be helpful to have a custom parameter for padding according to first answer in that post.

**Comment by Hixie** [comment]
My understanding is that these defaults come from the material design specification. Please don't hesitate to copy the class to make custom versions if the intent is not to match the material design language spec.
