### ISSUE TITLE
Crash rates 3x in 1.10.7 in the beta channel reported over 1.9.1+hotfix.4

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#42850]
Subject pretty much sums it up --- I don't see obvious culprits yet in the crash logs.

/cc @zanderso can someone on the tools team please investigate?

**Comment by zanderso** [comment]
As discussed offline, the crash rate is still below our threshold, and there are no new/unexpected crashes, so I'll go ahead and close this in favor of the issues we already have filed.
