### ISSUE TITLE
How to set SnackBar's Text font size using ThemeData?

### ISSUE THREAD

**Issue by DmitrySikorsky** [flutter/flutter#42851]
Hi, thank you for your work!

As I can see here: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/snack_bar.dart#L286

`textTheme.subhead` should work, but it doesn't. How can I specify font size of the SnackBar using global ThemeData? (I know, that I can do that directly inside the SnackBar, but I want to have unified approach for all the texts in the app.)

Thanks!

**Comment by Amitpatil215** [comment]
@DmitrySikorsky  Following example shows how we could specify font size of the SnackBar using global ThemeData

We have contentTextStyle property for SnackBarThemeData()
```Dart
contentTextStyle: TextStyle(fontSize: 20)
```

<details>
<summary>Example</summary>


```Dart
MaterialApp(
      theme: ThemeData(
        snackBarTheme: SnackBarThemeData(
          backgroundColor: Colors.amber,
          contentTextStyle: TextStyle(fontSize: 20), //Refer This
        ),
        primarySwatch: Colors.blue,
      ),
      home: MyApp(),
    );
```

</details>

@HansMuller as of now we can close this issue.

**Comment by Piinks** [comment]
Looks like this has been fixed, closing!
