### ISSUE TITLE
Dart analyzer doesn't imply return type from switch statements

### ISSUE THREAD

**Issue by Blaxou** [flutter/flutter#42865]
## Steps to Reproduce

1. Have a function returning an `enum`, `ContentType` here (should also work with any `object` though I didn't test)
2. Inside the function simply put a `switch .. case` block returning the specific type
3. The analyzer should now tell you that `This function has a return type of 'ContentType', but doesn't end with a return statement.` even though it does end every time with one.

![Annotation 2019-10-16 212018](https://user-images.githubusercontent.com/25441359/66951914-c340ba00-f05b-11e9-8ffc-699c381a309b.png)

I don't think this info is needed as in this case it returns the correct type in every case and every case is treated (as the analyzer didn't warn me about one enum not treated)

*Note :* Adding a `return` statement after the `switch` statement does make the analyzer happy but _it shouldn't be necessary_ 

**Target Platform:** Android
**Target OS version/browser:**  Android 10
**Devices:** Emulator

## Logs

```
No logs as it's a Dart Analysis Server bug
```

```
Analyzing File-Manager...

   info - This function has a return type of 'ContentType', but doesn't end with a return statement -
          lib\core\fs\datatypes\parsedFile.dart:110:10 - missing_return

1 issue found. (ran in 1.8s)
```

```
[√] Flutter (Channel dev, v1.10.14, on Microsoft Windows [Version 10.0.18362.418], locale en-CH)
    • Flutter version 1.10.14 at C:\Users\myname\Developer\Frameworks\flutter
    • Framework revision 1946fc4da0 (9 days ago), 2019-10-07 15:23:31 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.5.0 d6c6d12ebf)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\myname\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = C:\Users\myname\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by stuartmorgan** [comment]
Your `switch` is not exhaustive, so the warning is correct. See https://github.com/dart-lang/sdk/issues/37498
