### ISSUE TITLE
webview_flutter fails to build with it's minimally required flutter sdk

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#42860]
From https://github.com/flutter/plugins/pull/2196#issuecomment-542593441

@mklim :

> looks like that method rolled in v1.8.1. flutter/flutter@763ce63, flutter/engine#9206, which is below the latest stable. The problem here looks like the plugin is set to require something lower than the latest stable in its pubspec.yaml, 1.6.7. The other plugins only needed that version so it looks like I probably bumped it and missed that this broke on that version.

**Comment by mklim** [comment]
There's some secondary failure here where `PlatformView` is also missing the `onFlutterViewAttached` method on stable. Looking into it.

**Comment by mklim** [comment]
The `onFlutterViewAttached` callbacks didn't roll until `v1.10.9`, and stable is `v1.9.1`. I'm going to revert the migration instead of bumping the Flutter SDK version since that means that it's incompatible with stable.
