### ISSUE TITLE
Regression on smoke_catalina_* benchmarks

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#42871]
smoke_catalina_hot_mode_dev_cycle_ios__benchmark hotReloadMillisecondsToFrameAfterChange
smoke_catalina_hot_mode_dev_cycle_ios__benchmark hotRestartMillisecondsToFrame
smoke_catalina_start_up_ios timeToFirstFrameMicros
smoke_catalina_start_up_ios timeToFirstFrameRasterizedMicros

They all started at https://github.com/flutter/flutter/commit/a665393a0d5ebb591a502b28689d19ca1f5ed8be

**Comment by digiter** [comment]
@keyonghan

**Comment by keyonghan** [comment]
@godofredoc was helping check this issue yesterday, and didn't seem to find any related cause. Will sync with him today.

**Comment by godofredoc** [comment]
I think I know what could be affecting this metric, when we moved the phones we place them in a different orientation and rotation may not be locked down. @digiter @keyonghan if you are already at the office can you please try to disable rotation and lock the phones on portrait mode?

**Comment by keyonghan** [comment]
That's possible! Just locked the ios one on portrait mode. The android phone has already been locked. @franciscojma86 Please retry and let us know. Thanks.

**Comment by franciscojma86** [comment]
Ran this benchmark on device lab with red and green commits, all yielding similar results even after factory-resetting the phone.
We are not really sure how the device lab migration could affect this benchmark, but it's when the problem started. The infra team is working on IP address issues and will try running the tests again to see if anything changes.

For now it's safe to remove the TODAY label and re-baseline the benchmark

**Comment by franciscojma86** [comment]
Results from running tests
```
Commit | hotReloadMillisecondsToFrameAfterChange | hotReloadMillisecondsToFrame | hotRestartMillisecondsToFrame

HEAD (1982a5c3ec4e8bed39b90d536002c7597c127036) | 571 | 418 | 1,236
357d02c87b75d74382db212812e85a5d7d93dd7f | 538 | 415 | 1,215
HEAD (1982a5c3ec4e8bed39b90d536002c7597c127036) After phone reset | 498 | 422 | 1,193
```

**Comment by godofredoc** [comment]
Regression data is not showing up in the dashboard anymore.
