### ISSUE TITLE
AnimatedList initState() don't called when widget recreated

### ISSUE THREAD

**Issue by IvanOnishchenko** [flutter/flutter#42889]
I need AnimatedList and DragAndDropList simultaneously.

I copied DragAndDropList files from github to my project, and in build method  _DragAndDropListState class change  ListView to  AnimatedList.

When I start drag item I get error: RangeError (index): Invalid value: Not in range 0..6, inclusive: 7

I found that it happens because we set itemsCount in initState method AnimatedListState class:
```
@override
  void initState() {
    super.initState();
    _itemsCount = widget.initialItemCount;
  }
```
But initState() called only on first run, and when we  start drag item and recreate AnimatedList with new initialItemCount it goes using old _itemsCount.

I changed  _itemsCount to widget.initialItemCount and it work well (Also delte const word before AnimatedList constructor and final word before initialItemCount).

But it doesn't allow update Anim,atedList in future.

Also better use one multifunctional List then several but it is not bug, it is feature request  )

**Comment by goderbauer** [comment]
You need to also implement `didUpdateWidget` to respond to a changing widget configuration.
