### ISSUE TITLE
Overflow on channel: flutter/platform on web app with plugins

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#42880]
The url_launcher example app throws the following exception when compiled for web when clicking on any button. 

The rest of the app works, but the following exception is always thrown:

```
Overflow on channel: flutter/platform.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
```

(I noticed this same issue while working in another plugin, so it doesn't seem to be related to the url_launcher plugin in particular)

## Steps to Reproduce

1. Grab the [url_launcher example app](https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher/example).
2. Modify its pubspec to add a dependency on the url_launcher_web plugin:
  ```
  url_launcher: ^5.1.4
  url_launcher_web:
    git:
      url: git://github.com/flutter/plugins.git
      path: packages/url_launcher/url_launcher_web
   ```
3. Execute `flutter create .` on it, to add the missing `web` pieces.
4. Run `flutter run -d chrome` and wait for the browser to pop up
5. Open the development console, and click any button, the exception should show up.

**Target Platform:** Web (any?)
**Target OS version/browser:** Any
**Devices:** Any

### flutter run -d chrome --verbose

```
[+1164 ms] Debug service listening on ws://127.0.0.1:35447/ZYSaqFDQDic=

[  +12 ms] Attempting to connect to browser instance.. (completed in 3.7s)
[   +1 ms] 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 
[        ] Warning: Flutter's support for building web applications is highly experimental.
[        ] For more information see https://github.com/flutter/flutter/issues/34082.
[        ] 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 
[        ] 🔥  To hot restart (and rebuild state), press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +5 ms] Debug service listening on ws://127.0.0.1:35447/ZYSaqFDQDic=
[+16889 ms] ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
[        ] The following StateError was thrown during a platform message response callback:
[   +8 ms] Bad state: Future already completed
[        ] When the exception was thrown, this was the stack:
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 3995:11    throw_
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 37848:62   complete
[        ] package:flutter/src/services/binding.dart 177:18                    <fn>
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 134581:15  [_onDropItem]
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 134520:36  [_dropOverflowItems]
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 134507:55  push
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 134589:31  push
[        ] package:flutter_web_plugins/src/plugin_registry.dart 84:27          handlePlatformMessage
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 42367:34   runBody
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 42395:7    _async
[        ] package:flutter_web_plugins/src/plugin_registry.dart 76:37          handlePlatformMessage
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 160565:17  sendPlatformMessage
[        ] package:flutter/src/services/binding.dart 175:15                    [_sendPlatformMessage]
[        ] package:flutter/src/services/binding.dart 221:12                    send
[        ] package:flutter/src/services/platform_channel.dart 314:51           invokeMethod
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 42367:34   runBody
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 42395:7    _async
[        ] package:flutter/src/services/platform_channel.dart 312:28           invokeMethod
[        ] package:flutter/src/services/platform_channel.dart 446:3            [invokeMethod]
[        ] package:flutter/src/services/platform_channel.dart 429:36           invokeMethod$
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 42367:34   runBody
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 42395:7    _async
[        ] package:flutter/src/services/platform_channel.dart 427:28           invokeMethod
[  +35 ms] package:flutter/src/services/system_sound.dart 23:35                play
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 42367:34   runBody
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 42395:7    _async
[        ] package:flutter/src/services/system_sound.dart 22:27                play
[        ] package:flutter/src/material/feedback.dart 98:28                    forTap
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 42367:34   runBody
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 42395:7    _async
[        ] package:flutter/src/material/feedback.dart 93:29                    forTap
[        ] package:flutter/src/material/ink_well.dart 700:33                   [_handleTap]
[        ] package:flutter/src/material/ink_well.dart 783:36                   <fn>
[        ] package:flutter/src/gestures/recognizer.dart 182:24                 invokeCallback
[        ] package:flutter/src/gestures/tap.dart 486:47                        handleTapUp
[        ] package:flutter/src/gestures/tap.dart 264:5                         [_checkUp]
[        ] package:flutter/src/gestures/tap.dart 236:7                         acceptGesture
[        ] package:flutter/src/gestures/arena.dart 156:12                      sweep
[        ] package:flutter/src/gestures/binding.dart 222:20                    handleEvent
[        ] package:flutter/src/gestures/binding.dart 198:14                    dispatchEvent
[        ] package:flutter/src/gestures/binding.dart 156:7                     [_handlePointerEvent]
[        ] package:flutter/src/gestures/binding.dart 102:7                     [_flushPointerEventQueue]
[        ] package:flutter/src/gestures/binding.dart 86:32                     [_handlePointerDataPacket]
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 145367:9   [_onPointerData]
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 145580:26  <fn>
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 145516:11  <fn>
[        ] ════════════════════════════════════════════════════════════════════════════════════════════════════
```

### flutter analyze

(After removing `test` and `test_driver` dirs)

```
Analyzing url_launcher_app...                                           

   info • Unused import: 'dart:ui' • lib/generated_plugin_registrant.dart:4:8 • unused_import

1 issue found. (ran in 1.3s)
```

### flutter doctor -v

```
[✓] Flutter (Channel master, v1.9.6-pre.740, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.6-pre.740 at /path/to/flutter
    • Framework revision fbbc4fa868 (3 hours ago), 2019-10-16 17:17:06 -0400
    • Engine revision bb78551a0a
    • Dart version 2.6.0 (build 2.6.0-dev.8.0 ed1e0e199e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /path/to/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-stable, build-tools 29.0.1
    • Java binary at: /path/to/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /path/to/android-studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.38.1)
    • VS Code at /path/to/code
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • Chrome          • chrome          • web-javascript • Google Chrome 77.0.3865.120
    • Headless Server • headless-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by ditman** [comment]
@hterkelsen took a quick look and it seems that a callback to `handlePlatformMessage` may be being called twice?

Also:

> it looks like the `binaryMessenger` in the framework has the same bug
> it will call the callback twice because it's also doing `finally { callback(response); }`

**Comment by ditman** [comment]
cc/ @gaaclarke maybe you have more context on this one?

**Comment by gaaclarke** [comment]
Hi, yes I can provide more context.  That message should only be showing up if you are using a debug build, on master that should be the case.

You can consider it a warning an not actually an error.  This is happening because we are sending lifecycle messages on the platform channel before the engine is running, thus the overflow.  It is not erroneous.  That's why I had to pull it back into debug builds until we can think of a better way to communicate this behaviour.  =)

**Comment by ditman** [comment]
Ah yes, indeed I'm using a debug build. 

Thanks for the clarification!

**Comment by ditman** [comment]
However @gaaclarke, the error is thrown after each click and not just when the engine is starting. How come?

**Comment by gaaclarke** [comment]
> However @gaaclarke, the error is thrown after each click and not just when the engine is starting. How come?

Is the overflow on channel "flutter/platform"?  That sounds like an error that we are continually communicating on that channel.  The engine is running when this happening?  I can't say for sure that it is erroneous.  Let me check with @yjbanov.

**Comment by gaaclarke** [comment]
I'm sorry yesterday I spoke too soon.  My brain was fried at the end of the day.  `flutter/platform` is the channel used for communicating to things like the platform plugin.  (I was thinking `flutter/lifecycle` which happens under normal execution like I previously mentioned).

By default channels have a buffer size of 1.  If you are seeing this message, you are talking to an engine that is not running, or you are sending messages faster than they can be processed (which is impossible in the iOS situation, it might be different for web, I'm not familiar with it).

**Comment by hterkelsen** [comment]
Here is the bug as I see it:

- The framework sends a platform call for the `SystemSound#playSound` method, which causes a `Completer` to be initialized and a `callback` is passed to the platform-side which completes the `Completer` with the result of the platform call:

from [here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/binding.dart#L175):
```dart
    ui.window.sendPlatformMessage(channel, message, (ByteData reply) {
      try {
        completer.complete(reply);
      }
      ...
```

- On the platform side, we currently forward any unhandled platform calls to the plugin platform call handler, which then pushes any unrecognized platform calls to the channel buffer. _However_, in addition to buffering the call, it also passes `null` to the `callback` as a signal that the call was unrecognized:

Notice the `callback(null)` in the `finally` clause below. This code is from the [plugin message handler](https://github.com/flutter/flutter/blob/master/packages/flutter_web_plugins/lib/src/plugin_registry.dart#L75), but the exact same code is in the [framework platform handler](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/binding.dart#L190):

```dart
  @override
  Future<void> handlePlatformMessage(String channel, ByteData data,
      ui.PlatformMessageResponseCallback callback) async {
    ByteData response;
    try {
      final MessageHandler handler = _handlers[channel];
      if (handler != null) {
        response = await handler(data);
      } else {
        ui.channelBuffers.push(channel, data, callback);
      }
    } catch (exception, stack) {
      ...
    } finally {
      callback(response);
    }
  }
```

- Later, we get another call to `SystemSound.playSound`, and do the same thing again. Only this time, since we have filled the buffer for the `SystemSound` channel, we drain the buffer by calling the buffered callback with `null`.

From [`ChannelBuffers`](https://github.com/flutter/engine/blob/7c13f62234029dfad94fe14994e4af4e665065f2/lib/web_ui/lib/src/ui/channel_buffers.dart#L127):

```dart
  void _onDropItem(_StoredMessage message) {
    message.callback(null);
  }
```

- This is when the crash happens. _We already called `callback(null)` on that callback!_ The `Completer` associated with that callback has already completed with `null`, but now we are calling `completer.complete` again, which is invalid if the `Completer` has already completed.

Since the framework-side `BinaryMessenger` also has the `finally { callback(response); }` logic, I believe the same bug would occur if the platform-side were to send unhandled messages to the framework side (i.e., the `callback` would be called twice).

**Comment by hterkelsen** [comment]
@gaaclarke What do you think we should do about double-calling the `callback`?

**Comment by yjbanov** [comment]
@gaaclarke friendly ping. We will fix the missing handler issue in the Web engine. However, it will mask the other issue with double-completing the future. Would you like to use this issue to fix that? Or should we open a new issue?

**Comment by gaaclarke** [comment]
Sorry, would you believe me if I told you I was thinking about it the past 6 days?  (you shouldn't)

> we currently forward any unhandled platform calls to the plugin platform call handler, which then pushes any unrecognized platform calls to the channel buffer. _However_, in addition to buffering the call, it also passes `null` to the `callback` as a signal that the call was unrecognized

Yep, this appears erroneous.  The intention is only to call the callback when the message is handled, or discarded.  I can try to repro this in a unit test.

> This is when the crash happens.

You are getting a crash?  That info was missing from the original report.

Thanks for the find.  Fixing it is at the front of my todo list.

**Comment by ditman** [comment]
I don't see this anymore, thanks @gaaclarke!

**Comment by phamnhuvu-dev** [comment]
I still often see this error on the web.
I trying to master, dev, beta with the latest version.
```
channel_buffers.dart:144 Overflow on channel: flutter/platform.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
```

**Comment by gaaclarke** [comment]
@phamnhuvu-dev that isn't necessarily an error (depends on the semantics of the channel).  I'd file another bug is reproduction steps.

**Comment by janardhanmupparaju** [comment]
I am trying to develop web application with geolocation and webcam using flutter but getting this error. any one can you please help me

The following StateError was thrown during a platform message response callback:

Bad state: Future already completed

When the exception was thrown, this was the stack:

dart-sdk/lib/internal/js_dev_runtime/private/ddc_runtime/errors.dart 195:49 throw

dart-sdk/lib/async/future_impl.dart 42:79 complete

packages/flutter/src/services/binding.dart 176:18

dart-sdk/lib/async/zone.dart 1374:10 runUnaryGuarded

lib/_engine/engine/window.dart 331:23

lib/_engine/engine/window.dart 488:17

dart-sdk/lib/async/zone.dart 1439:54 runUnary

dart-sdk/lib/async/future_impl.dart 141:18 handleValue

dart-sdk/lib/async/future_impl.dart 682:44 handleValueCallback

dart-sdk/lib/async/future_impl.dart 711:32
_propagateToListeners

dart-sdk/lib/async/future_impl.dart 516:7 [_complete]

dart-sdk/lib/async/future.dart 315:15

dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 50:19 internalCallback

═════════════════════════════════════════════════════════════════════════════════════════════════
═══

**Comment by PandaGeek1024** [comment]
The same here, Im converting my app to web and this error(?) pops up every time when I push another page and every click on the buttons in the new page triggers this error.
