### ISSUE TITLE
The mobile terminal of flutter web does not support other browsers except Google browser to upload files. After clicking the upload button, a window will pop up to select pictures. After selecting files, there is no follow-up. What's the problem?

### ISSUE THREAD

**Issue by Thathy916** [flutter/flutter#42888]
The mobile terminal of flutter web does not support other browsers except Google browser to upload files. After clicking the upload button, a window will pop up to select pictures. After selecting files, there is no follow-up. What's the problem?

**Comment by yjbanov** [comment]
Do you have a small app that shows this problem?

**Comment by Thathy916** [comment]
> Do you have a small app that shows this problem?

In my repository called multipart_file_upload, there is a flutter web project that you can clone and run in Google browser. Then you can click the FloatActionButton, pop up a file picker box, select a few files, and then click the OK button. Several files are selected in the page.Sometimes when I refresh the page for the first time, I click the button to pop up the selection box, select the file, and the listener does not work, which always happens after the first page refresh. The problem of mobile browser is more serious. Except Google browser, no other browser can monitor the selected file.Whats the matter?

**Comment by yjbanov** [comment]
We are working on adding Web support to https://pub.dev/packages/image_picker, which will work on all browsers. If you are implementing your own method for uploading multi-part files, check out StackOverflow.
