### ISSUE TITLE
flutter command not found

### ISSUE THREAD

**Issue by CaiChenghan** [flutter/flutter#42893]
flutter command not found **every time** when I opened a new terminal window.
It‘s works well when I command `source ~/.bash_profile`
- Mac 10.15
- Flutter v1.9.1+hotfix.4

![image](https://user-images.githubusercontent.com/9568389/66975089-e9a03d00-f0cf-11e9-88f1-376b0ec33446.png)

**Comment by stuartmorgan** [comment]
Per [the setup instructions](https://flutter.dev/docs/get-started/install/macos#update-your-path) you need to use `.zshrc` to configure your path on 10.15 since the default shell changed.

**Comment by CaiChenghan** [comment]
thank you

**Comment by ankitkumar333111** [comment]
Step 1- Go to the directory where you have your flutter SDK and copy path upto bin folder and run the below command
        export PATH=[DIRECTORY_PATH]/flutter/bin:$PATH
        For Example->  export PATH=/home/abhi/Downloads
        /flutter_linux_v1.7.8+hotfix.4-stable/flutter/bin:$PATH
Step 2- Now Check for your bash file
        nano ~/.bash_profile

If Still get an error you can follow- https://hotflutter.blogspot.com/2019/11/flutter-command-not-found.html

**Comment by Khosro-Awhadi** [comment]
hi every one, 
i do have the same problem. i have copied the Flutter and add the path to the environmental Variable. 
when i look for the path i see the folder. but when i want to run Flutter. it says flutter not found. 
![Screenshot 2020-03-26 at 12 38 03](https://user-images.githubusercontent.com/56594681/77642877-a7243b80-6f5e-11ea-923c-d6b0462ff2c7.png)

**Comment by gondar00** [comment]
For zsh users, 
`export PATH=$PATH:~/Downloads/flutter/bin`

if the folder the SDK resides in is `Downloads` else replace with the correct folder path

and start a fresh window

**Comment by Khosro-Awhadi** [comment]
@gondar00 you see, the SDK path is already set correctly. Still can not find the flutter, easy way would be the use of {which flutter} command.
