### ISSUE TITLE
iOS 13 TextField() crash

### ISSUE THREAD

**Issue by Mentina** [flutter/flutter#42897]
Add Flutter to  existing iOS app (iOS 13.0)
Input completed with keyboard
crash occurred

**Comment by BondarenkoStas** [comment]
@Mentina please paste here your flutter doctor -v output and the log. Stack trace would be very useful.

**Comment by Mentina** [comment]
> @Mentina please paste here your flutter doctor -v output and the log. Stack trace would be very useful.

Thanks. I have solved this problem by upgrading flutter.
