### ISSUE TITLE
API to trigger/manage vibration feedback

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#429]
Mobile platforms have a way to vibrate as a feedback mechanism.

**Comment by sethladd** [comment]
We might have this.

https://domokit.github.io/docs/sky/services/UserFeedback-class.html

**Comment by abarth** [comment]
Yeah, we have support for the "named" types of haptic feedback.  There's another layer we can expose that will let you program your own bespoke feedback.

**Comment by mit-mit** [comment]
@sethladd isn't this there now? Can we close this bug? https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/haptic_feedback.dart

**Comment by sethladd** [comment]
I don't know what APIs are available for vibration, and if the existing haptic API covers the capabilities. But, good to know that there's at least a start!

(e.g. can I do a vibration pattern with this API? what else can/can't I do? I haven't done my research here, just thinking of questions)

**Comment by mit-mit** [comment]
The current API is super simple, but I'm still going to close this bug as it isn't really actionable. I'm sure we will get good, detailed requests later from customers that can provide more scenario details.
