### ISSUE TITLE
In App Purchase: Allow subscription upgrade or downgrade

### ISSUE THREAD

**Issue by verscph** [flutter/flutter#42903]
Hi, 

I was wondering whether subscription upgrades, by passing the product IDs for the current subscription and the future (upgraded or downgraded) subscription to the BillingFlowParams, are already supported in https://pub.dev/packages/in_app_purchase?

More context: 

- Android: https://developer.android.com/google/play/billing/billing_subscriptions#Allow-upgrade
- iOS: https://medium.com/revenuecat-blog/ios-subscription-groups-explained-8c5b8325d4ab

Tx for your input,
Philip

**Comment by PabloEBenavides** [comment]
This is very important, i'm also needing it for my app, thanks for the help

**Comment by dannycortesv** [comment]
Please wee need this, it is a very important feature, thanks for the support

**Comment by idoamram** [comment]
+1

**Comment by rahulraj64** [comment]
I already made a feature request for this
https://github.com/flutter/flutter/issues/32395

**Comment by Hixie** [comment]
Closing as duplicate as @rahulraj64 pointed out.
