### ISSUE TITLE
Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast

### ISSUE THREAD

**Issue by DBSumation** [flutter/flutter#42913]
error: 
```
E/flutter ( 8973): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast
```

```
class Stocks {  final String symbol;
final String news;
final String splits;
final String chart;
stocks.fromJSON(Map<String, dynamic> jsonMap) :
news = jsonMap ['news'], 
splits =jsonMap ['split'],
chart =jsonMap ['chart'],
symbol = jsonMap['symbol'];
}
```
![image](https://user-images.githubusercontent.com/37802537/66993687-00c43800-f09a-11e9-83e1-1cbbd3ba6a9a.png)

Snippet of the json results:

> {"AAPL":{"chart":[],"splits":[],"news":[{"datetime":1571050800000,"headline":"Top Apple Executives Sold Millions of Dollars of

**Comment by nt4f04uNd** [comment]
I guess you have mistaken with case of your `stocks.fromJSON`. If you want to create a named constructor, you have to write like this `Stocks.fromJSON`

**Comment by BondarenkoStas** [comment]
thank you @nt4f04uNd !
@DBSumation This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but related to implementation. Closing, as this is not an issue report. See https://flutter.dev/community for support options.

**Comment by DBSumation** [comment]
Added to Stack [overflow](https://stackoverflow.com/questions/58576464/flutter-retrieve-a-list-of-stocks-stats-and-quotes-from-iex-json-api) 
https://stackoverflow.com/questions/58576464/flutter-retrieve-a-list-of-stocks-stats-and-quotes-from-iex-json-api 
Still have the same issue. 
logs:
=====

> I/OpenGLRenderer( 5233): Initialized EGL, version 1.4
D/OpenGLRenderer( 5233): Swap behavior 1
D/        ( 5233): HostConnection::get() New Host Connection established 0xd04d2c40, tid 5284
D/EGL_emulation( 5233): eglCreateContext: 0xe2fb71e0: maj 2 min 0 rcv 2
D/EGL_emulation( 5233): eglMakeCurrent: 0xe2fb71e0: ver 2 0 (tinfo 0xd057ed80)
D/        ( 5233): HostConnection::get() New Host Connection established 0xd04d28c0, tid 5272
D/EGL_emulation( 5233): eglCreateContext: 0xe2fb8380: maj 2 min 0 rcv 2
Syncing files to device Android SDK built for x86...
D/EGL_emulation( 5233): eglMakeCurrent: 0xe2fb8380: ver 2 0 (tinfo 0xd057e9e0)
I/Choreographer( 5233): Skipped 343 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 5233): eglMakeCurrent: 0xe2fb8380: ver 2 0 (tinfo 0xd057e9e0)
D/EGL_emulation( 5233): eglMakeCurrent: 0xe2fb71e0: ver 2 0 (tinfo 0xd057ed80)
E/flutter ( 5233): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast
E/flutter ( 5233): #0      getStocks.<anonymous closure> (package:montly_paying_funds_stocks/repository/stocks_repository.dart:20:31)
E/flutter ( 5233): #1      _ExpandStream._handleData (dart:async/stream_pipe.dart:248:23)
E/flutter ( 5233): #2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
E/flutter ( 5233): #3      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 5233): #4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 5233): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 5233): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 5233): #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 5233): #8      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
E/flutter ( 5233): #9      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
E/flutter ( 5233): #10     _JsonStringDecoderSink.close (dart:convert-patch/convert_patch.dart:1489:11)
E/flutter ( 5233): #11     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:80:18)
E/flutter ( 5233): #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
E/flutter ( 5233): #13     _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 5233): #14     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 5233): #15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 5233): #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
E/flutter ( 5233): #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
E/flutter ( 5233): #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
E/flutter ( 5233): #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
E/flutter ( 5233): #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
E/flutter ( 5233): #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:249:11)
E/flutter ( 5233): #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:300:20)
E/flutter ( 5233): #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:80:18)
E/flutter ( 5233): #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
E/flutter ( 5233): #25     _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 5233): #26     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 5233): #27     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 5233): #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
E/flutter ( 5233): #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
E/flutter ( 5233): #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
E/flutter ( 5233): #31     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
E/flutter ( 5233): #32     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
E/flutter ( 5233): #33     _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 5233): #34     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 5233): #35     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 5233): #36     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
E/flutter ( 5233): #37     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
E/flutter ( 5233): #38     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
E/flutter ( 5233): #39     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
E/flutter ( 5233): #40     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
E/flutter ( 5233): #41     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:62:11)
E/flutter ( 5233): #42     _FilterSink.close (dart:io/data_transformer.dart:637:11)
E/flutter ( 5233): #43     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:80:18)
E/flutter ( 5233): #44     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
E/flutter ( 5233): #45     _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 5233): #46     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 5233): #47     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 5233): #48     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
E/flutter ( 5233): #49     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
E/flutter ( 5233): #50     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:28

**Comment by eswarvarma-dev** [comment]
_CastError (type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast)

class CategoriesModel{
    int category_id;
    String cat_name;
    String cat_slug;
    int cat_sorting;
    int created_by;
    String created_at;
    int status;
    var Image_path;
    int total;
   
   CategoriesModel(this.category_id,this.cat_name,this.cat_slug,this.cat_sorting,this.created_by,
   this.created_at,this.status,this.Image_path,this.total);


    CategoriesModel.fromJson(Map<String, dynamic> json)
     :
         category_id = json['category_id'],
        cat_name = json['cat_name'].toString(),
        cat_slug = json['cat_slug'].toString(),
        cat_sorting = json['cat_sorting'],
        total = json['total'],
        Image_path = json['Image_path'],
        created_by = json['created_by'],
        created_at = json['created_at'].toString(),
        status = json['status'];
       
   }

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.

**Comment by muktaahammed** [comment]
I/flutter (11485): Error is here NoSuchMethodError: Class '_InternalLinkedHashMap<String, dynamic>' has no instance getter 'body'.
I/flutter (11485): Receiver: _LinkedHashMap len:4
I/flutter (11485): Tried calling: body
E/flutter (11485): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The getter 'iterator' was called on null.
E/flutter (11485): Receiver: null
E/flutter (11485): Tried calling: iterator

**Comment by burakgrds** [comment]
E/flutter ( 2171): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: Class '_InternalLinkedHashMap<String, dynamic>' has no instance method 'map' with matching arguments.
E/flutter ( 2171): Receiver: _LinkedHashMap len:4
E/flutter ( 2171): Tried calling: map<Home>(Closure: (dynamic) => Home)
E/flutter ( 2171): Found: map<K2, V2>((K, V) => MapEntry<K2, V2>) => Map<K2, V2>
E/flutter ( 2171): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)

**Comment by exeptionerror** [comment]
[[Solved] Unhandled Exception: InternalLinkedHashMap‘ is not a subtype of type ‘List
](https://fluttercorner.com/unhandled-exception-internallinkedhashmapstring-dynamic-is-not-a-subtype-of/)
