### ISSUE TITLE
Can fontFamily be set to multiple values? Just like CSS font-family.

### ISSUE THREAD

**Issue by zbs-ha** [flutter/flutter#42915]
## code snippets
```
MaterialApp(
  title: 'Custom Fonts',
  // Set Raleway as the default app font.
  theme: ThemeData(fontFamily: 'Raleway'),
  home: MyHomePage(),
);
```

## my expectation
- Can `fontFamily` be set to multiple values? Just like CSS ` font-family`

**Comment by MostafaKhalile** [comment]
Yes You Could add multiple fonts by adding Them in 'pubspec.yaml' File Just Like That :
You Should First Create assets/fonts directory and add your fonts files right there 
and add them in "pubspec.yaml" File
 fonts:
    - family: GELIGHT
      fonts:
        - asset: assets/fonts/GELIGHT.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
          weight: 700
and 
to Use Them for Every Text Widget add them like that  style: TextStyle(FontFamily:"Roboto")

**Comment by keshava19** [comment]
When you mean by CSS font-family, do you mean by fallback font-family when the defined one is missing ?
If that's the case it would be not necessary IMO, as the font files will be always be present.
If not for fallback, what is the use case ?

**Comment by zbs-ha** [comment]
For this case: `“hello,  你好!”`
I want different languages ​​to use different fonts.
```
Text(
    'hello, 你好!',
    style: TextStyle(fontFamily: 'Montserrat', fontFamilyFallback: ['FangSong']),
)
```
The above works fine, but I want to set it globally.

**Comment by keshava19** [comment]
You mean that in the same text if there are different languages present then the font used should be different for each of them ?
And in the above case which font will be used can you explain ?

**Comment by zbs-ha** [comment]
For "hello", font Montserrat will be used, but for "你好", font Montserrat will become invalid and then font FangSong will be a fallback.
@keshava19

**Comment by MostafaKhalile** [comment]
@zbs-ha  
You Should use RichText Widget Like This 
`RichText(
  text: TextSpan(
    text: 'Hello ',
    style:TextStyle(fontFamily:'Montserrat'),
    children: <TextSpan>[
      TextSpan(text: '你好', style: TextStyle(fontFamily:'Montserrat ,fontFamilyFallback:'FangSong '),
    ],
  ),
)`


and you should add your font files to assets and 

> pubspec.yaml

as I Mentioned [here](https://github.com/flutter/flutter/issues/42915#issuecomment-543199159)

**Comment by zbs-ha** [comment]
This is a good idea, but I want to set it globally in the app, just like the [font-family](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) attribute of css.
@MostafaKhalile

**Comment by MostafaKhalile** [comment]
`MaterialApp(
theme: ThemeData(
                fontFamily: 'Montserrat',)
)`

So it will be the global font family

**Comment by zbs-ha** [comment]
Thank you very much, but what if I want to set a  fallback font  globally?
You can refer to  the [font-family](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) of css below：
> The `font-family` property specifies a list of fonts, from highest priority to lowest. Font selection **does not** simply stop at the first font in the list that is on the user's system. Rather, font selection is done **one character at a time**, so that if an available font does not have a glyph for a needed character, the latter fonts are tried. (However, this doesn't work in Internet Explorer 6 or earlier.) When a font is only available in some styles, variants, or sizes, those properties may also influence which font family is chosen.

@MostafaKhalile

**Comment by MostafaKhalile** [comment]
it is not supported yet put it should be added by [This](https://github.com/flutter/flutter/pull/25585)

**Comment by Hixie** [comment]
You can put fontFamilyFallbacks on a DefaultTextStyle anywhere.
