### ISSUE TITLE
Build APK Flutter crash report

### ISSUE THREAD

**Issue by dibusiness** [flutter/flutter#42912]
## command

flutter --no-color build apk

## exception

ProcessException: ProcessException: Permission denied
  Command: /Users/MyAccount/Desktop/app_build_final-customer_app/android/gradlew -v

```
#0      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:265:37)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:329:24)
<asynchronous suspension>
#2      GradleUtils.getExecutable (package:flutter_tools/src/android/gradle.dart:45:33)
<asynchronous suspension>
#3      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:735:44)
<asynchronous suspension>
#4      buildGradleProject (package:flutter_tools/src/android/gradle.dart:575:14)
<asynchronous suspension>
#5      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:101:11)
<asynchronous suspension>
#6      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:99:26)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:553:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.15 19A602, locale en-SA)
    • Flutter version 1.10.7 at /Users/salehaleid/development/flutter
    • Framework revision e70236e36c (2 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/salehaleid/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/salehaleid/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8580
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • AF2BC150-D08F-4662-B154-4C2850D300F5 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!
```

**Comment by BondarenkoStas** [comment]
@dibusiness can you check the permission to your android sdk? It seems very similar to #41526. Please check if https://github.com/flutter/flutter/issues/41526#issuecomment-540626754 will work.

**Comment by dibusiness** [comment]
/Users/[MyAccount]/.pub-cache/hosted/pub.dartlang.org/intro_slider-1.2.3/android/src/main/java/com/dfa/introslider/IntroSliderPlugin.java:3: error: package io.flutter.plugin.common does not exist
import io.flutter.plugin.common.MethodCall;                             
                               ^                                        
/Users/[MyAccount]/.pub-cache/hosted/pub.dartlang.org/intro_slider-1.2.3/android/src/main/java/com/dfa/introslider/IntroSliderPlugin.java:4: error: package io.flutter.plugin.common does not exist
import io.flutter.plugin.common.MethodChannel;                          
                               ^                                        
/Users/[MyAccount]/.pub-cache/hosted/pub.dartlang.org/intro_slider-1.2.3/android/src/main/java/com/dfa/introslider/IntroSliderPlugin.java:5: error: package io.flutter.plugin.common.MethodChannel does not exist
import io.flutter.plugin.common.MethodChannel.MethodCallHandler;        
                                             ^                          
/Users/[MyAccount]/.pub-cache/hosted/pub.dartlang.org/intro_slider-1.2.3/android/src/main/java/com/dfa/introslider/IntroSliderPlugin.java:6: error: package io.flutter.plugin.common.MethodChannel does not exist
import io.flutter.plugin.common.MethodChannel.Result;                   
                                             ^                          
/Users/[MyAccount]/.pub-cache/hosted/pub.dartlang.org/intro_slider-1.2.3/android/src/main/java/com/dfa/introslider/IntroSliderPlugin.java:7: error: package io.flutter.plugin.common.PluginRegistry does not exist
import io.flutter.plugin.common.PluginRegistry.Registrar;               
                                              ^                         
/Users/[MyAccount]/.pub-cache/hosted/pub.dartlang.org/intro_slider-1.2.3/android/src/main/java/com/dfa/introslider/IntroSliderPlugin.java:10: error: cannot find symbol
public class IntroSliderPlugin implements MethodCallHandler {           
                                          ^                             
  symbol: class MethodCallHandler                                       
/Users/[MyAccount]/.pub-cache/hosted/pub.dartlang.org/intro_slider-1.2.3/android/src/main/java/com/dfa/introslider/IntroSliderPlugin.java:12: error: cannot find symbol
  public static void registerWith(Registrar registrar) {                
                                  ^                                     
  symbol:   class Registrar                                             
  location: class IntroSliderPlugin                                     
/Users/[MyAccount]/.pub-cache/hosted/pub.dartlang.org/intro_slider-1.2.3/android/src/main/java/com/dfa/introslider/IntroSliderPlugin.java:18: error: cannot find symbol
  public void onMethodCall(MethodCall call, Result result) {            
                           ^                                            
  symbol:   class MethodCall                                            
  location: class IntroSliderPlugin                                     
/Users/[MyAccount]/.pub-cache/hosted/pub.dartlang.org/intro_slider-1.2.3/android/src/main/java/com/dfa/introslider/IntroSliderPlugin.java:18: error: cannot find symbol
  public void onMethodCall(MethodCall call, Result result) {            
                                            ^                           
  symbol:   class Result                                                
  location: class IntroSliderPlugin                                     
/Users/[MyAccount]/.pub-cache/hosted/pub.dartlang.org/intro_slider-1.2.3/android/src/main/java/com/dfa/introslider/IntroSliderPlugin.java:13: error: cannot find symbol
    final MethodChannel channel = new MethodChannel(registrar.messenger(), "intro_slider");
          ^                                                             
  symbol:   class MethodChannel                                         
  location: class IntroSliderPlugin                                     
/Users/[MyAccount]/.pub-cache/hosted/pub.dartlang.org/intro_slider-1.2.3/android/src/main/java/com/dfa/introslider/IntroSliderPlugin.java:13: error: cannot find symbol
    final MethodChannel channel = new MethodChannel(registrar.messenger(), "intro_slider");
                                      ^                                 
  symbol:   class MethodChannel                                         
  location: class IntroSliderPlugin                                     
/Users/salehaleid/.pub-cache/hosted/pub.dartlang.org/intro_slider-1.2.3/android/src/main/java/com/dfa/introslider/IntroSliderPlugin.java:17: error: method does not override or implement a method from a supertype
  @Override                                                             
  ^                                                                     
12 errors                                                               
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':intro_slider:compileDebugJavaWithJavac'.    
> Compilation failed; see the compiler error output for details.        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 2s                                                      
:intro_slider:compileDebugJavaWithJavac FAILED                          
10 actionable tasks: 1 executed, 9 up-to-date                           
         *********************************************************      
WARNING: This version of path_provider will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

**Comment by BondarenkoStas** [comment]
All the errors are related to intro_slider, which is a third party plugin. Please paste your pubspec.yaml. If you use intro_slider-1.2.3, is there a reason to use not 2.2.8?

**Comment by Hixie** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
