### ISSUE TITLE
xcode11 Archive and remind a error "IPA processing failed"

### ISSUE THREAD

**Issue by fero2004** [flutter/flutter#42917]
![3251C86D-113C-44B9-A599-2EDDF4D10C1E](https://user-images.githubusercontent.com/5326843/66998540-04da6f00-f107-11e9-82d1-72a1edefa8b8.png)

And I Found the log 
![8E08E8C1-6659-4DB2-B762-991C4B528164](https://user-images.githubusercontent.com/5326843/66998680-42d79300-f107-11e9-8ad5-bc739581d8b8.png)

it seems like Flutter.framework include x86_64

My project is swift mixed flutter

**Comment by Darren-chenchen** [comment]
https://www.darrenblog.cn/#/detail/5dbf9a8a7bb725236692b6d4

**Comment by EvenerV** [comment]
> https://www.darrenblog.cn/#/detail/5dbf9a8a7bb725236692b6d4

When you remove the x86 from Flutter.framework and rebuild the project, it will generate a new Flutter.framework contains x86.

**Comment by EvenerV** [comment]
Try to use the **Xocde 10** to archive the project. 
I'm trying this way too. If I have some good news, I will share for you.

**Comment by fero2004** [comment]
I found the way to solve this problem

1.
![D575F056-0733-4BAE-AE92-EEFFDA6A8D53](https://user-images.githubusercontent.com/5326843/69617521-4ac61380-1073-11ea-89a2-bada3abd8117.png)

2.cd your architecture floder like this 

/Users/luozugen/Library/Developer/Xcode/Archives/2019-10-17/Portal 2019-10-17, 11.06 AM.xcarchive/Products/Applications/Utrack.app/Frameworks/Flutter.framework

3.lipo -remove x86_64 Flutter -o Flutter

4.back to 'organizer window' to do next

**Comment by jmagman** [comment]
Did you running `flutter build ios` on the command line before archiving?
https://flutter.dev/docs/deployment/ios#create-a-build-archive

Looks like some form of https://github.com/flutter/flutter/issues/37850.  Hopefully this was fixed by https://github.com/flutter/flutter/pull/42029.  If you're still seeing this, can we get the output of `flutter doctor -v`?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
