### ISSUE TITLE
Set TimeZone in Flutter

### ISSUE THREAD

**Issue by hemanthStack** [flutter/flutter#42920]
Hi, I used to convert UTC time to TimeZone time like this in Android Java now in flutter how can I achieve.
```dart
public static String getTimeFullDateStr(Date date, String timeZone) {
    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("h:mma, MMM dd, yyyy", Locale.US);
    TimeZone tz = null;
    if (timeZone.equalsIgnoreCase("")) {
        tz = TimeZone.getTimeZone("US/Pacific");
    } else {
        tz = TimeZone.getTimeZone(timeZone);
    }
    simpleDateFormat.setTimeZone(tz);
    String formattedDate = simpleDateFormat.format(date);
    formattedDate = formattedDate.replace("AM", "am").replace("PM", "pm");
    return formattedDate;
}
```

**Comment by janmoppel** [comment]
Hello @hemanthStack !

Thank you for posting.
Your question seems to be a better fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) than here as this is not an issue report. Flutter has a very active and helpful community there, so feel free to post it there too.

Also, see other support options here: https://flutter.dev/community

Closing this thread, as this is not an issue report.
