### ISSUE TITLE
when body of email has a link then url_launcher removes second query parameter.

### ISSUE THREAD

**Issue by dhanrajvermaRepo** [flutter/flutter#42926]
I am creating a mail using url_launcher. The body of the email has a link with multiple query parameters. The problem is that only first query param is there and all other query params are removed.

> Example:-
`mailto:?subject=wynk%20music&body=http://myLocalHost/posts/redirect/?post_id=id1&user_id=id2`
But body which appear in mail body =http://myLocalHost/posts/redirect/?post_id=id1

**Comment by stuartmorgan** [comment]
You need to encode the entire body as a query parameter using the relevant `Url` API, so that special characters within it are escaped. As you have written the URL there, `user_id` is a query parameter of the mailto, fire to lack of competent encoding, which is presumably not what you want.

**Comment by dhanrajvermaRepo** [comment]
> You need to encode the entire body as a query parameter using the relevant `Url` API, so that special characters within it are escaped. As you have written the URL there, `user_id` is a query parameter of the mailto, due to lack of competent encoding, which is presumably not what you want.

I did not get what you suggesting. Could you please give some example or something.

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/issues/42279#issuecomment-544039320
