### ISSUE TITLE
[plugins] Start tagging semantic versions

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#42934]
The version tags should take the form `package-name-v<major>.<minor>.<patch>`, and presumably `package-name-v0.<major>.<minor>+<patch>` if they're below 1.0.0 to match pub.

It would be ideal if this could be handled by our CI somehow. We've already struggled to remember to increment the pubspec consistently, I think remembering to create and push git tags is going to be even more error prone. Could be some Cirrus script that tags commits on master correctly if the pubspec has been changed? The script itself sounds easy enough to write, but I don't know if it's a great idea to give our CI the ability to push tags. Is there even an already existing Github bot for this we could pull in, or maybe we could write our own?

/cc @csells @amirh @collinjackson

**Comment by csells** [comment]
You can also use an optional 'v' in your version, e.g. package-name-<major>.<minor>.<patch> and package-name-v<major>.<minor>.<patch> both work. And yes, the leading 0 on the version for pre-1.0 versions.

**Comment by csells** [comment]
@Hixie has spoken and the guidance on the version tags must include the leading 'v':

Must be able to get from the version number on pub.dev to source code on GitHub via matching version tag in 'v<major>.<minor>.<subversion>' format (same as pub.dev format via a leading 'v'). In the case that the repo has multiple plugins, the version tags should take the form 'package-name-v<major>.<minor>.<subversion>'.

**Comment by mklim** [comment]
I'm considering creating a CLI tool to publish flutter/plugins packages to pub and tag them simultaneously.

Pros:
- Would automatically start tagging stuff as we publish and resolve this issue.
- While I'm writing it I could also trivially take care of some outstanding items from flutter/flutter#27258, like panicking and bailing if there are ignored files at all in the directory.
- By definition should keep the tag and the pub release number consistent, since it will be publishing at the same time as it tags.

Cons:
- There will be a maintenance burden of maintaining the script. Risk of feature creep into it.
- Abstraction over `pub publish` is a potential source of failure. Will need to make sure the tool stays up to date with `pub publish`, users of the tool will need to understand the tool instead of just `pub publish` itself.

I'm leaning towards this as the best pragmatic option right now. The other ones I've thought of are:

1. Require everyone to manually remember to create the correctly formatted tag and push it every time they publish to pub. This has no maintenance burden at all but is going to be extremely error prone and impractical going forward. We already forget to publish at all some of the time, I think adding one more step is going to be difficult.
2. Create some automated bot that pushes tags instead of wrapping `pub publish` and runs through CI. There's a steeper maintenance and investment cost here to creating something with all the right permissions that's going to work correctly. Once working this would be nicer to some extent since it would automatically run, but risks getting out of sync with pub.
3. It's occurred to me that this could all be a feature request for pub itself, too. `pub publish` knows the git repo and the version and should be able to push a well formatted tag. Maybe pub would be open to adding this functionality into `publish` directly? I'll ask and see.

**Comment by mklim** [comment]
We have a tool for this merged now, but the latest versions should still be tagged, and we should update our contributing guide to point towards the tool.

**Comment by mklim** [comment]
Updated CONTRIBUTING.md with information about the tool. I also pushed the most recent tag and release for everything in flutter/plugins. This should be fixed now.
