### ISSUE TITLE
user login

### ISSUE THREAD

**Issue by engmms** [flutter/flutter#42939]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by engmms** [comment]
the Error ::
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building SettingScreen(dirty, dependencies: [MediaQuery, _InheritedTheme, _LocalizationsScope-[GlobalKey#102d1], InheritedProvider<WishListModel>], state: SettingScreenState#181f3):
Failed assertion: boolean expression must not be null


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

User-created ancestor of the error-causing widget was:
  Consumer<UserModel> file:///D:/2-Part_Two/15-FLUTTER_Complete_Folder/Full_projects/Khamsat/source/lib/screens/user.dart:21:16
When the exception was thrown, this was the stack:
#0      SettingScreenState.build (package:fstore/screens/settings.dart:79:50)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
Failed assertion: boolean expression must not be null
User-created ancestor of the error-causing widget was:
  Consumer<UserModel> file:///D:/2-Part_Two/15-FLUTTER_Complete_Folder/Full_projects/Khamsat/source/lib/screens/user.dart:21:16
════════════════════════════════════════════════════════════════════════════════════════════════════
D/FirebaseAuth(27475): Notifying id token listeners about user ( aK8ajBlnOaR5rdZh4OPSazuvaLH2 ).
D/FirebaseAuth(27475): Notifying auth state listeners about user ( aK8ajBlnOaR5rdZh4OPSazuvaLH2 ).


`import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'login.dart';
import 'settings.dart';
import '../models/user.dart';
import 'package:firebase_auth/firebase_auth.dart';

class UserScreen extends StatefulWidget {
  @override
  _UserScreenState createState() => _UserScreenState();
}

class _UserScreenState extends State<UserScreen> {
  final _auth = FirebaseAuth.instance;
  @override
  Widget build(BuildContext context) {
    final userModel = Provider.of<UserModel>(context);

    return ListenableProvider.value(
        value: userModel,
        child: Consumer<UserModel>(builder: (context, value, child) {

          if (value.user != null) {
            return SettingScreen(
              user: value.user,
              onLogout: () async {
                userModel.logout();
                _auth.signOut();
              },
            );
          }
          return LoginScreen();
        }));
  }
}
`

**Comment by jonahwilliams** [comment]
The stack trace indicates that somewhere in `package:fstore/screens/settings.dart:79:50` you are treating a null value as a boolean. This is not a problem in flutter, but in your own code
