### ISSUE TITLE
For a flutter web device, When performing a hot reload, the flutter tool reports progress events for a hot restart (Performing hot restart…)

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#42938]
For a flutter web device, When performing a hot reload, the flutter tool reports progress events for a hot restart (`Performing hot restart…`).

As we have separate buttons and user actions for hot reload and hot restart, it would be nice to have the text returned from the flutter tool match what the user action was.

cc @jonahwilliams

**Comment by jonahwilliams** [comment]
I'll fix that as a part of https://github.com/flutter/flutter/pull/42931
