### ISSUE TITLE
Unable to build iOS app after modifying pubspec.yaml and running flutter pub get

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#42956]
Error Message: `'Flutter/Flutter.h' file not found`

Steps to reproduce:
 1) Create an add 2 app scenario
 1) Edit the module's pubspec.yaml to include a new asset
 1) Inside of the module run `flutter build bundle`
 1) Go back to your xcode project and build and run, notice that the Flutter headers are no longer able to be found.

You can fix this broken state by going back to your host app and running `pod install`.

It would be nice if we could automatically fix this erroneous state or communicate back to users that they need to run `pod install` again.

**Comment by gaaclarke** [comment]
cc @jmagman

**Comment by gaaclarke** [comment]
I've just verified that calling `flutter build bundle` from the commandline isn't necessary, just editing the pubspec.yaml is enough to create the problem.

```
[   +7 ms] [✓] Flutter (Channel master, v1.10.15-pre.136, on Mac OS X 10.14.6 18G95, locale en-US)
[        ]     • Flutter version 1.10.15-pre.136 at /Users/aaclarke/dev/flutter
[        ]     • Framework revision 357d02c87b (2 days ago), 2019-10-15 15:33:55 -0700
[        ]     • Engine revision 540fc977bb
[        ]     • Dart version 2.6.0 (build 2.6.0-dev.7.0 70a7ef3f58)
```

**Comment by jmagman** [comment]
`flutter pub get` seems to the be command removing the directory `.ios/engine` after pubspec.yaml is modified.

**Comment by jmagman** [comment]
Simplified reproduction steps:
```
$ flutter create -t module test_module_pubspec
$ cd test_module_pubspec
$ flutter build ios
$ ls -la  .ios/Flutter/engine/
total 8
drwxr-xr-x   4 m  primarygroup  128 Nov  4 16:53 .
drwxr-xr-x  10 m  primarygroup  320 Nov  4 16:53 ..
drwxr-xr-x   8 m  primarygroup  256 Nov  4 16:53 Flutter.framework
-rw-r--r--   1 m  primarygroup  758 Nov  4 16:53 Flutter.podspec
$ open pubspec.yaml
```
Increment `version:`
```
$ flutter pub get
$ ls -la  .ios/Flutter/engine/
ls: .ios/Flutter/engine/: No such file or directory
```

**Comment by jmagman** [comment]
When the pubspec changes, the ephemeral directory is deleted and re-created from the template:
https://github.com/flutter/flutter/blob/175b37247dc171cbe4dce7b52b8517cfdae346a8/packages/flutter_tools/lib/src/project.dart#L450

**Comment by jmagman** [comment]
That framework isn't present when the module is first created, either.  

Whenever the pubspec changes, this will reproduce.  The workaround is to:
1. Run `flutter build ios` in the _module_.
1. Run `pod install` in the _host_.

**Comment by jonahwilliams** [comment]
The simple approach would be to repopulate the framework in `.ios/Flutter/engine/` based on whatever existed there previously (perhaps by leaving a record of what mode before deleting it).

However, these is still the fact that building the module project seems to depend on the last build command run. There should be a better way to do this, though it might require changes in how the module project is generated.

**Comment by jonahwilliams** [comment]
(I'm also not sure if that fixes having to run pod install)

**Comment by jmagman** [comment]
> However, these is still the fact that building the module project seems to depend on the last build command run. There should be a better way to do this, though it might require changes in how the module project is generated.

The framework is only copied during `pod install` so the plugins have something to link against before `xcode_backend` script is run, which copies the version of the engine based on the Xcode run's `$(CONFIGURATION)` build setting (Debug, Profile, Release)
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/bin/xcode_backend.sh#L65

So it shouldn't matter what the last build command was because the current configuration is what will be copied and embedded into the app.

**Comment by jonahwilliams** [comment]
> So it shouldn't matter what the last build command was because the current configuration is what will be copied and embedded into the app.

Good to know. In that case it sounds like we could always copy the debug framework when recreating the ephemeral directory and this would "just work"?

**Comment by jmagman** [comment]
> > So it shouldn't matter what the last build command was because the current configuration is what will be copied and embedded into the app.
> 
> Good to know. In that case it sounds like we could always copy the debug framework when recreating the ephemeral directory and this would "just work"?

It should, see my PR at https://github.com/flutter/flutter/pull/37450.  That test didn't pass though and I got distracted with the Xcode rename problem.
