### ISSUE TITLE
[Discussion] Should Android plugins get the FlutterEngine object?

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#42959]
With the v2 embedder API plugins have direct access to the [FlutterEngine](https://github.com/flutter/engine/blob/ba872d50a7e20be55cc81308539f990f126eec93/shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java) object through the [FlutterPluginBinding](https://github.com/flutter/engine/blob/ba872d50a7e20be55cc81308539f990f126eec93/shell/platform/android/io/flutter/embedding/engine/plugins/FlutterPlugin.java#L117).

The `FlutterEngine` class exposes some objects/method that I'm not sure we want to expose to plugins:

- `FlutterEngine#destroy` - do we want plugins to be able to call this?
- The [PlatformViewsController](https://github.com/flutter/engine/blob/ba872d50a7e20be55cc81308539f990f126eec93/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java) - which includes methods which are meant for interaction with other engine/embedding components, not plugins (attachToView, detachToView, attachToAccessibilityBridge, ...). All plugins need is that PlatformViewRegistry (which is what they are handed in the v1 embedding)
- All the system channel objects (`AccessibilityChannel`, `KeyEventChannel`, `TextInputChannel`, etc...) - do we want plugins to be able to do things like `flutterEngine.getTextInputChannel().updateEditingState(...)` ?

Would it make sense to consider providing a subset of the things exposed through FlutterEngine in FlutterPluginBinding?

@matthew-carroll @mklim

**Comment by matthew-carroll** [comment]
I think it's difficult to say what plugins will want to do in the future, so I'd prefer to give them more control over less control. It wouldn't surprise me if plugins send a message over a system channel. For example, maybe a plugin is emulating some key events or text input.

I think if we introduce a subset of behavior then we will get recurring requests to extend that subset. Eventually the API we provide will cover at least most of what FlutterEngine already exposes and then we've got 2 surfaces to maintain, simply for the purpose of forcibly preventing a few method calls that a plugin should know better than to touch, anyway.

**Comment by amirh** [comment]
> I think it's difficult to say what plugins will want to do in the future, so I'd prefer to give them more control over less control.

+1 to that, especially when it comes to more control over the platform which is what plugins are meant to deal with.

My main concern is about how "public" these Java APIs are, e.g for the PlatformViewsController object while technically methods like `attachToView` are part of the public API without this object exposed they are very unlikely to be used, and we're kind of more ok with making "breaking changes" to them assuming the only client is the embedding. It only hit me today that we're exposing this object to plugins and it makes me more scared of future refactorings we may want to do there.

**Comment by matthew-carroll** [comment]
Ideally we would use package private to deal with that, but unfortunately our package scheme is probably too spread out to facilitate getting `getPlatformViewsController()` into a single package.

**Comment by gaaclarke** [comment]
If I may, it just isn't a question about what powers we want to provide plugins, but do we want to give ourselves the ability to control what is sent to the plugins?

An API where plugins aren't talking directly to the FlutterEngine is a better design from the perspective of our ability to control that interface and to make sure it makes the most sense for plugin developers, which is a very different use case from clients of FlutterEngine.

**Comment by gaaclarke** [comment]
More concretely this would be my recommendation:
![flutter-plugin-engine](https://user-images.githubusercontent.com/30870216/67123574-900a4200-f1a5-11e9-9326-26764e7edb2f.png)

**Comment by xster** [comment]
I think we fixed this one. Please reopen if not correct.
