### ISSUE TITLE
Default AndroidManifest should include "smallestScreenSize" in "android:configChanges"

### ISSUE THREAD

**Issue by arisha84** [flutter/flutter#42963]
=====STEPS TO REPRODUCE=====

1. Install a Flutter app from Playstore.
2. Launch the app on Chromebook
3. Resize the app and observe that the app restarts

**Comment by arisha84** [comment]
Update: I've added smallestScreenSize to the AndroidManifest android:configChanges part 
and it looks like it solved the problem.

**Comment by jonahwilliams** [comment]
Maybe we should add that setting to our android manifest template (if it isn't already)

**Comment by jonahwilliams** [comment]
Update: it isn't in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/android.tmpl/app/src/main/AndroidManifest.xml.tmpl#L16
