### ISSUE TITLE
Crash report sent (report ID: 6cd53307b2f3fbf3)

### ISSUE THREAD

**Issue by radyoof** [flutter/flutter#42961]
Android studio apk produce bu eror

Sending crash report to Google.

Crash report sent (report ID: 6cd53307b2f3fbf3)
Oops; flutter has exited unexpectedly.
Crash report written to C:\Nexthour Mobile App Flutter Files\flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.
Process finished with exit code 1I

**Comment by radyoof** [comment]
flutter log_4

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color build apk

## exception

ProcessException: ProcessException: Process "C:\Nexthour Mobile App Flutter Files\android\gradlew.bat" exited abnormally:
Downloading https://services.gradle.org/distributions/gradle-3.10.2-all.zip


Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle-dn.com/distributions/gradle-3.10.2-all.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: C:\Nexthour Mobile App Flutter Files\android\gradlew.bat -v

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:300:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:281:37)
<asynchronous suspension>
#3      buildGradleProject (package:flutter_tools/src/android/gradle.dart:484:31)
<asynchronous suspension>
#4      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#5      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:79:11)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [SÃ¼rÃ¼m 6.1.7601], locale tr-TR)
    • Flutter version 1.9.1+hotfix.4 at C:\src\flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\BUGLEM\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8580
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.39.1)
    • VS Code at C:\Users\BUGLEM\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by ketanm** [comment]
@radyoof - this is not appear to be Flutter related issue, please post at StackOverflow to get answer on gradle config.

**Comment by BondarenkoStas** [comment]
@radyoof It may be the one which was fixed on 1.10.2 #37526. Failed download may be connected to a range of issues, sometimes it's just the network fail. It will be good if you try to run on beta or dev to see the result.

Also you may try to download https://services.gradle.org/distributions/gradle-3.10.2-all.zip manually and save it under ~/.gradle/wrapper/dists/gradle-3.10.2-all/xxx
Check https://stackoverflow.com/questions/31405947/how-to-setup-gradle-2-2-1-all-zip-manually for more.

**Comment by mhkazemi1990** [comment]
Hi 

> Android studio apk produce bu eror
> 
> Sending crash report to Google.
> 
> Crash report sent (report ID: 6cd53307b2f3fbf3)
> Oops; flutter has exited unexpectedly.
> Crash report written to C:\Nexthour Mobile App Flutter Files\flutter_04.log;
> please let us know at https://github.com/flutter/flutter/issues.
> Process finished with exit code 1I
Hi ,
I need very critical NextHour Mobile app version . I have purchased about 1 month ago Web version but now I see few days ago released Mobile version .
Can you please send me this Mobile Version of NextHour to me ?
My email address is : mhkazemi28@gmail.com 
Please understand me that I need very critical this app .
Best Regards and I'm waiting your as soon as possible reply and action 
Thanks

**Comment by radyoof** [comment]
Send me email next hour install video, purchase code
I send to you ios, andorid, web next hour ok

**Comment by mhkazemi1990** [comment]
Hi friend,
Why you need that’s ? 
Please send me files of mobile version please 
Thanks again 



Sent from myMail for iOS


Saturday, October 19, 2019, 11:52 +0330 from notifications@github.com  <notifications@github.com>:

**Comment by BondarenkoStas** [comment]
@mhkazemi1990 did you try to build it on beta channel?
And in general, did you managed to fix the issue?

**Comment by radyoof** [comment]
no :(

**Comment by iapicca** [comment]
Hi @radyoof 

for what I can observe so far the issue you are describing depends from 
either a lack of connectivity or a third party service

<details>
  <summary>**Error**</summary>

> Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle-dn.com/distributions/gradle-3.10.2-all.zip
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
> 	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
> 	at org.gradle.wrapper.Download.download(Download.java:44)
> 	at org.gradle.wrapper.Install$1.call(Install.java:61)
> 	at org.gradle.wrapper.Install$1.call(Install.java:48)
> 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
> 	at org.gradle.wrapper.Install.createDist(Install.java:48)
> 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
> 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
>   Command: C:\Nexthour Mobile App Flutter Files\android\gradlew.bat -v
</details>

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it

**Comment by radyoof** [comment]
10 $
