### ISSUE TITLE
Get image current User firestore 

### ISSUE THREAD

**Issue by SilasPaes** [flutter/flutter#42973]
Hi, I have this code:
```
new StreamBuilder(
  stream: Firestore.instance.collection("contents").snapshots(),
  builder: (context, snapshot) {
    if (!snapshot.hasData) return const Text('Loading...');
    return new ListView.builder(
      itemCount: snapshot.data.documents.length,
      padding: const EdgeInsets.only(top: 10.0),
      itemExtent: 25.0,
      itemBuilder: (context, index) {
        DocumentSnapshot ds = snapshot.data.documents[index];
        return new Text(" ${ds['url']} ${ds['title']}");
      }
    );
  }
),
```
Where I get the fields of another users right? 
and me return an card with data (name, age,..) of another users, then I would like show data of currentuser in card together with data another users....
example of card:
Name (another user, using ds[name])
age (another user, using ds[age])
image (another user, using ds[image])
image (current user, ?

thanks
how do I do?

**Comment by BondarenkoStas** [comment]
@SilasPaes This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
