### ISSUE TITLE
Android Studio 3.5.1 issue

### ISSUE THREAD

**Issue by NuaimanAshiq** [flutter/flutter#42989]
Hello All,
 Yesterday I updated my Android Studio to version 3.5.1. 
Ever since I am having trouble loading Flutter Projects.
Please Help :) 
![1](https://user-images.githubusercontent.com/40488562/67068095-b7bdc380-f12d-11e9-98e2-e194913aedae.PNG)
![2](https://user-images.githubusercontent.com/40488562/67068097-b8565a00-f12d-11e9-9253-92807b222188.PNG)

**Comment by smark91** [comment]
Seems you just need to fill the Flutter SDK path in the second text field

**Comment by nuaiman-ashiq** [comment]
I tried doing it. Each time I close setting window it changes to becoming blank again.

**Comment by smark91** [comment]
Try renaming this folder with Android Studio closed and reopen it `C:\Users\<your_usarname>\.AndroidStudio3.5`.
It must ask you starting config like a first installation.

**Comment by VladyslavBondarenko** [comment]
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
