### ISSUE TITLE
Failed assertion: line 2328 pos 12: '!_debugLocked'

### ISSUE THREAD

**Issue by DragonTotem** [flutter/flutter#42980]

**Comment by BondarenkoStas** [comment]
Hi @DragonTotem, we need a lot more to go on than this, as per the new issue template. What were you doing at the time? Is there some repro code? What version of Flutter are you using (flutter doctor -v)? Thanks!

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
