### ISSUE TITLE
Jank when scrolling large static content with Flutter Web

### ISSUE THREAD

**Issue by roman-petrov** [flutter/flutter#42987]
## Details

We are building a Flutter Web component for our production app and we need an ability to scroll over large static content built with many Flutter widgets. We are trying to reach 60 FPS scroll even on some low-end devices and in theory I think that is definitely possible with static bitmap scrolling/repainting on GPU.

Actually we tried several ways to implement such scroll and reached the best FPS when we build just one single root element and place it inside `ListView`.

But when we use Flutter this way scrolling is janky until first scroll to end. After that scrolling hits 60 FPS and the performance seems to be perfect.

This problem can be easily seen in this minimal example: 
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: Scaffold(
          body: ListView(
            children: <Widget>[
              Column(
                children: <Widget>[
                  for (int y = 0; y < 1000; y++)
                    Row(
                      children: <Widget>[
                        for (int x = 0; x < 30; x++)
                          Container(
                            width: 50,
                            height: 22,
                            padding: EdgeInsets.all(4),
                            child: Text('$y, $x'),
                          ),
                      ],
                    )
                ],
              ),
            ],
          ),
        ),
      );
}
```
I made a screen recording of the issue and got large file so I uploaded to `imgpile.com`: 

<https://imgpile.com/i/1av7WF>

Looking on this video I assume that Flutter Web performs painting and builds cache on HTML `canvas` element during first scroll.

I made some research to try to build image cache in single pass and found a dirty workaround: wrap large widget into `RepaintBoundary` render it scaled down to fit into the screen, then display it as is:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class BitmapCache extends StatelessWidget {
  BitmapCache({@required this.child});

  final Widget child;

  @override
  Widget build(BuildContext context) => FutureBuilder<double>(
        future: Future<double>.value(1),
        builder: (BuildContext context, AsyncSnapshot<double> snapshot) =>
            Transform.scale(
          scale: snapshot.hasData ? snapshot.data : 0.0001,
          alignment: Alignment.topLeft,
          child: RepaintBoundary(child: child),
        ),
      );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: Scaffold(
          body: ListView(
            children: <Widget>[
              BitmapCache(
                child: Column(
                  children: <Widget>[
                    for (int y = 0; y < 1000; y++)
                      Row(
                        children: <Widget>[
                          for (int x = 0; x < 30; x++)
                            Container(
                              width: 50,
                              height: 22,
                              padding: EdgeInsets.all(4),
                              child: Text('$y, $x'),
                            ),
                        ],
                      )
                  ],
                ),
              ),
            ],
          ),
        ),
      );
}
```
Here is a screen recording for this tricky workaround on `imgpile.com`: 

<https://imgpile.com/i/1avUIi> 

Using this workaround we hit 60 FPS (some FPS is lost in screen recording due to active screen recording), but it is not suitable for our production scenarios.

There are also a couple of Flutter issues I found that might be somehow connected to this:

[#32662](https://github.com/flutter/flutter/issues/32662)
[#32338](https://github.com/flutter/flutter/issues/32338)

So my questions are:
- Is there some legal way in Flutter to render some static widget tree to off-screen image and then use it in scroll container? 
- Or is it possible to have programmatic control over caching strategy in `ListView` or other scrollable widgets?

I suppose that having ability to pre-cache scroll content might be useful for other platforms too: maybe we can get low CPU usage and good performance during scroll if we just scroll a bitmap on GPU.

Sorry for such long content:  I just tried to give maximum information I have for this issue :)

## System information

We use Flutter `master` channel with rolling strategy to Flutter commits, but I suppose this should not make sense.

**Target Platform:** Windows 10
**Target OS version/browser:** Chrome (Version 77.0.3865.120 (Official Build) (64-bit))
**Devices:** Desktop computer

![system_information](https://user-images.githubusercontent.com/18419515/67064765-6c7ad380-f174-11e9-8990-c7eddb14f761.png)

## Logs

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.10.15-pre.151, on Microsoft Windows [Version 10.0.17134.950], locale ru-RU)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio CommunityВ 2019 16.3.0)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.39.2)
[√] Connected device (3 available)

• No issues found!

**Comment by yjbanov** [comment]
Curious why you need a `Column` in addition to a `ListView`. Both are vertical lists of widgets. Can you try using `ListView.builder` and put `Row`s directly in it as children? `ListView.builder` lazily renders its children so there's less to render per frame.

**Comment by roman-petrov** [comment]
We used `Column` in the provided example just as result of many experiments, not by design. Actually we tried many approaches to reach 60 FPS scroll when having `ListView` rows with many children. 

`ListView.builder` with `Row`s lazily built on scroll is good approach for large content: it has fast first-render time but in our case it not reaches 60 FPS during scroll and increases CPU usage.

The best scrolling performance I see in Flutter is scrolling a static image so I try to reach the same performance with large content by forcing Flutter engine to pre-render it into a memory bitmap 

In Web something similar might be implemented using CSS [transform](https://developer.mozilla.org/en-US/docs/Web/CSS/transform) or a new [will-change](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change) attributes.

**Comment by yjbanov** [comment]
We'll take a look. Thanks for the minimal example! We definitely use CSS transforms for positioning layers. We currently do not have will-change in the Web version. Flutter mobile deduces this property automatically and raster caches appropriately. We could do the same on the web by setting will-change after deducing it from layer behavior.

**Comment by roman-petrov** [comment]
Thanks, Yegor. We will follow Flutter & Flutter Web milestones to see how how we can improve scrolling performance.

**Comment by solid-software** [comment]
We have couple more examples that might be relevant for this ticket for performance improvements, let us know if we need to provide code examples or separate issue should be created:

https://test-54431.firebaseapp.com/#/
https://test2-f9f6d.firebaseapp.com/#/

**Comment by nemoryoliver** [comment]
Here's my deployed web app with the scrolling issue on mobile as well. https://thebluer.app

**Comment by rafazafar** [comment]
Here's my deployed web app with the scrolling issue on mobile as well. https://hnd.zafar.dev

**Comment by stuz5000** [comment]
Did you try setting the debug flag to false?
(See above)

**Comment by Garciconx** [comment]
vertical Pageview on free mode may help meanwhile

**Comment by dhakadv06** [comment]
Any workarounds for time being?? 

Had to change the whole design just because of janky scroll
Here's the website  
https://portfolio-20f42.web.app/

**Comment by epiphanatic** [comment]
Here's my deployed web app with the scrolling issue on mobile as well: https://axion.amnion.space

**Comment by Garciconx** [comment]
> Here's my deployed web app with the scrolling issue on mobile as well: https://axion.amnion.space

good performance, did you do that with the pageview?

**Comment by solid-software** [comment]
There is also an ability to run using skia/canvaskit: https://github.com/flutter/flutter_web/blob/master/docs/canvaskit.md

`flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true`

It's still experimental feature but in our experience it works faster.

**Comment by AseemWangoo** [comment]
How I temporarily fixed (good old Hit and Trial):

1. Identify the widgets, consuming memory....(Use Dev Tools, Browser Tools etc)

2. Wrap the widget with RepaintBoundary..e.g If let's say, you got 10 widgets, then wrap 1 widget and follow step 3..

3. Test again, until the scrolling was at least good enough (if not upto the mark)...Then follow step 2.

**Comment by jodinathan** [comment]
> How I temporarily fixed (good old Hit and Trial):
> 
> 1. Identify the widgets, consuming memory....(Use Dev Tools, Browser Tools etc)
> 2. Wrap the widget with RepaintBoundary..e.g If let's say, you got 10 widgets, then wrap 1 widget and follow step 3..
> 3. Test again, until the scrolling was at least good enough (if not upto the mark)...Then follow step 2.

Can you repro both cases?
One with the jank behavior and another one with the RepaintBoundary you used.
Would be very nice for people to study

**Comment by liyuqian** [comment]
@yjbanov : I wonder if the web benchmarks `bench_card_infinite_scroll` and `bench_simple_lazy_text_scroll` capture this kind of scrolling use case? My biggest concern is the feedback that normal use of `ListView` that lazily builds 1000 children/rows where each child has its own raster cache is not as performant as a giant RepaintBoundary that raster caches all 1000 children together. We probably should make the normal use fast enough on web so mobile and web Flutter won't have two different styles to achieve the best performance.

**Comment by max202021** [comment]
Try using Custom Scroll Physics . below is Sample code.

```
import 'dart:math';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _controller = ScrollController();

  final List<int> pages = List.generate(40, (index) => index);

  ScrollPhysics _physics;

  @override
  void initState() {
    super.initState();

    _controller.addListener(() {
      if (_controller.position.haveDimensions && _physics == null) {
        setState(() {
          var dimension = _controller.position.maxScrollExtent * 20000;
          _physics = CustomScrollPhysics(itemDimension: dimension);
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: ListView.builder(
          itemBuilder: (context, index) {
            return ListTile(
              title: Text('row $index'),
            );
          },
        ),
      ),
    );
  }

  Color get randomColor =>
      Color((Random().nextDouble() * 0xFFFFFF).toInt() << 0).withOpacity(1.0);
}

class CustomScrollPhysics extends ScrollPhysics {
  final double itemDimension;

  CustomScrollPhysics({this.itemDimension, ScrollPhysics parent})
      : super(parent: parent);

  @override
  CustomScrollPhysics applyTo(ScrollPhysics ancestor) {
    return CustomScrollPhysics(
        itemDimension: itemDimension, parent: buildParent(ancestor));
  }

  double _getPage(ScrollPosition position) {
    return position.pixels / itemDimension;
  }

  double _getPixels(double page) {
    return page * itemDimension;
  }

  double _getTargetPixels(
      ScrollPosition position, Tolerance tolerance, double velocity) {
    double page = _getPage(position);
    if (velocity < -tolerance.velocity) {
      page -= 0.5;
    } else if (velocity > tolerance.velocity) {
      page += 0.5;
    }
    return _getPixels(page.roundToDouble());
  }

  @override
  Simulation createBallisticSimulation(
      ScrollMetrics position, double velocity) {
    // If we're out of range and not headed back in range, defer to the parent
    // ballistics, which should put us back in range at a page boundary.
    if ((velocity <= 0.0 && position.pixels <= position.minScrollExtent) ||
        (velocity >= 0.0 && position.pixels >= position.maxScrollExtent))
      return super.createBallisticSimulation(position, velocity);
    final Tolerance tolerance = this.tolerance;
    final double target = _getTargetPixels(position, tolerance, velocity);
    if (target != position.pixels)
      return ScrollSpringSimulation(spring, position.pixels, target, velocity,
          tolerance: tolerance);
    return null;
  }

  @override
  bool get allowImplicitScrolling => false;
}

```

**Comment by max202021** [comment]
![localhost_53881_#_ - Google Chrome 2020-03-29 18-43-30](https://user-images.githubusercontent.com/57527948/77850062-a35a1880-71ed-11ea-980a-312b9f8462b5.gif)
Result of Custom ScrollPhysics

**Comment by dhakadv06** [comment]
@max202021  You are my hero 
Thank you soo much

**Comment by hossam-hani** [comment]
> ![localhost_53881_#_ - Google Chrome 2020-03-29 18-43-30](https://user-images.githubusercontent.com/57527948/77850062-a35a1880-71ed-11ea-980a-312b9f8462b5.gif)
> Result of Custom ScrollPhysics

work for me but when i'm scroll very fast i see some lag  , thanks man <3 , can you explain what is problem ?

**Comment by max202021** [comment]
@hossam-hani This example is for infinite list. If your list is finite then I would suggest using singlechildScrollView. I have seen some improvement using it.

**Comment by yjbanov** [comment]
I am able to reproduce the issue using the sample provided in the original post. The sample generates a large picture (by putting 1000 rows in a `Column`). When you scroll you have a clip sliding along this picture causing frequent repaints. Since the picture is huge, those repaints are very expensive.

The issue is easily fixable by supplying each row via the `itemBuilder` to `ListView.builder`. This is what we generally recommend that apps do. Flutter is optimized for lazy rendering. However, I still think this is a good case for us to optimize for. While an optimized app is unlikely to generate static pictures that are 50 times bigger than the clip area, there are plenty of cases where pictures are 3-5 times bigger than the clip area. We should be efficient in those cases.

One option I'm testing right now is to prune drawing operations that fall outside the clip area. We'll need to be smarter about predicting how the clip changes over time so we do not repaint on every frame, but I'm optimistic.

**Comment by roman-petrov** [comment]
@yjbanov , thank you for the update. 

I would like to provide a bit more information about our production case and hope it will be helpful.

Actually, our production case is to build a large (but finite on both directions) data-grid widget similar to Excel sheet. Our widget is responsive and scrollalble in both directions. Scrollable area maximum width is ~1600px, maximum height might be very large, but still limited like 10000px.

Our primary goal is to achieve maximum scrolling performance and we are ok if first frame rendering takes much time, even 3-5 seconds is ok in some corner cases on low-end machines.

We tried many approaches to achive 60 FPS scroll in our case, including `itemBuilder` with `ListView.builder`. But when we use such lazy rendering we get scroll performance about 20-30 FPS even on our high-end development machines.

So we decided to try to force Flutter to render and pre-cache in memory entire scrollable area and not to rebuild anything during scrolling.

**Comment by jasonspick** [comment]
I've noticed when the cursor is not over the list while scrolling, this is not an issue. Maybe there is a relationship between the hover and scroll?

**Comment by aungsatpo** [comment]
Does anyone encounter Facebook in-app browser on iOS closes when you scroll down a web app written in flutter?

**Comment by max202021** [comment]
Since this is closed. How can I get the latest build which includes this. I have following version
Flutter 1.12.13+hotfix.6 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 18cd7a3601 (4 months ago) • 2019-12-11 06:35:39 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

**Comment by roman-petrov** [comment]
@max202021, you have to wait for next stable build. Or you can use Flutter from master branch (still you have to wait engine roll to happen today or tomorrow).

**Comment by Garciconx** [comment]
> Since this is closed. How can I get the latest build which includes this. I have following version
> Flutter 1.12.13+hotfix.6 • channel beta • https://github.com/flutter/flutter.git
> Framework • revision [18cd7a3](https://github.com/flutter/flutter/commit/18cd7a3601bcffb36fdf2f679f763b5e827c2e8e) (4 months ago) • 2019-12-11 06:35:39 -0800
> Engine • revision 2994f7e1e6
> Tools • Dart 2.7.0

Flutter channel master
Flutter upgrade

**Comment by jodinathan** [comment]
is there an issue for when this will be applied to the flutter web gallery?
I would like to test it asap once it gets a fix

**Comment by max202021** [comment]
Thanks @roman-petrov  and @Garciconx . Eagerly waiting for this as this will be a game changer if works.

**Comment by yjbanov** [comment]
The change has landed on master. I'll appreciate any feedback from real world apps. Our own benchmarks are showing significant improvement:

<img width="569" alt="Screen Shot 2020-04-17 at 9 57 56 AM" src="https://user-images.githubusercontent.com/211513/79595242-57cfb780-8093-11ea-8b17-af90c147633d.png">

Of course, benchmarks is one thing, real apps is another :)

**Comment by harikrishnan-neibre** [comment]
There is significant improvement in the scrolling.. I have tested it with the new build..a sample app is available in the following link

http://neibre.herokuapp.com/#/

Hope to see more optimisations in future for a production build

**Comment by oliver92** [comment]
Awesome! When will this be available in the beta channel? Im just wondering because i want to start working on a web version of an app and a timeline with this fix in mind would be nice :)

**Comment by roman-petrov** [comment]
Yegor, thank you for all your work!  

I tested latest updates and see the difference in scrolling performance using `ListView` with a single `Column` child. Before we had a "major" jank when scrolling first time. After this update we are getting some "minor" jank during every scroll and still not hitting 60 fps.

Actually, in our scenario we use a custom scrollbar to provide desktop experience and this might be a different case. 

I found another `Flutter` issue which might be more relevant to our case https://github.com/flutter/flutter/issues/52207, and we already implemented a proposed solution https://github.com/flutter/flutter/issues/22314#issuecomment-615308850 (we found and implemented it several months ago). 

We already delivered our application component to production and have about 40-50 fps scrolling on high end machines so we are still looking for improvements in `Flutter` related to desktop scrollbar support.

**Comment by srihari-pasupula189** [comment]
In Desktop.It is working fine but in android,it is still lagging.This is the sample site which is under development https://autozang-marketing-web.web.app/#/

**Comment by apps-transround** [comment]
My experience comes from a real world problem but I simplified the code just to demonstrate that

- A border in a container can slow down scrolling in Flutter web 

The problem is similar for [ScrollView](https://github.com/flutter/flutter/issues/56257#issuecomment-636849223) and  #ListView

I've tested it in debug and release mode on Chrome desktop and mobile.
By removing border: Border(left: BorderSide(color: Colors.green)), the speed goes up to normal.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    WebScrollTest(),
  );
}

class WebScrollTest extends StatelessWidget {
  final int rowCount = 30;
  final int columnCount = 30;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
            appBar: AppBar(
              title: Text('Two-way scroll'),
            ),
            body: ListView(children: <Widget>[
              ...List.generate(
                rowCount,
                (int i) => SingleChildScrollView(
                  scrollDirection: Axis.horizontal,
                  child: Row(children: [
                    ...List.generate(
                      columnCount,
                      (int j) => Container(
                        width: 100,
                        height: 80,
                        child: contentCellBuilder(j, i),
                      ),
                    ),
                  ]),
                ),
              ),
            ])));
  }

  Widget contentCellBuilder(int i, int j) {
    return Container(
        decoration: BoxDecoration(
// by removing this border, FPS goes up to normal
          border: Border(
            left: BorderSide(color: Colors.green),
          ),
//
        ),
        child: Text('Dummy cell content: $i - $j'));
  }
}

```

C:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel master, 1.19.0-2.0.pre.195, on Microsoft Windows [Version 10.0.17134.885], locale en-GB)
• Flutter version 1.19.0-2.0.pre.195 at C:\flutter
• Framework revision 42c4c30 (3 days ago), 2020-05-29 12:53:01 -0400
• Engine revision c19459ab7d
• Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
• Android SDK at C:/Android/android-sdk
• Platform android-29, build-tools 28.0.3
• ANDROID_HOME = C:/Android/android-sdk
• Java binary at: C:\Android\android-studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
• Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
• Android Studio at C:\Android\android-studio
• Flutter plugin version 46.0.2
• Dart plugin version 193.7361
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
• Web Server • web-server • web-javascript • Flutter Tools
• Chrome • chrome • web-javascript • Google Chrome 83.0.4103.61

! Doctor found issues in 1 category.

**Comment by shadowdogg** [comment]
This is really bad on mobile though? Why is this closed?

**Comment by liyuqian** [comment]
This is closed because https://github.com/flutter/engine/pull/17621 fixed the "Jank when scrolling large static content with Flutter Web" issue here. If you have some other scrolling issue that's not related to Flutter for Web, but to Flutter on mobile/Android/iOS, please file a new issue and we can track the progress there.

**Comment by syfulin** [comment]
@nemoryoliver 
> Here's my deployed web app with the scrolling issue on mobile as well. https://thebluer.app

Sounds like you've fixed the scrolling issue? Share your experience?

**Comment by AbhideepChakravarty** [comment]
On flutter web, when I use ImageIcon, the performance drops drastically for the scroll. Without IconImage, it feels 90% ok. Running on Android Chrome, in deployed mode in production. 

D:\Eclatian\Code\restaurants>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.26.0-2.0.pre.275, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.52.0)
[√] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by mrmayurgithub** [comment]
Any update ? I'm still facing lag issues in mobile browser and in sometime on my pc too.
