### ISSUE TITLE
The flutter.jar dependency is still android.support, is there anyway to upgrade to androidX

### ISSUE THREAD

**Issue by zhangcongmin** [flutter/flutter#42994]
I import a flutter module into my Native Project, and I create flutter module with AndroidX，cause My Native Project use androidx.
but when I run app, it crashed . Error log is: incompility android.arch.lifecycle.Lifecycle，I know this error is cause by the support library and androidx library 
but I can not resolve。Can anyone has a solution?
Here are my flutter module configurations.
![image](https://user-images.githubusercontent.com/8501196/67076425-b4731800-f1bf-11e9-9678-01da9d2b52f3.png)
![image](https://user-images.githubusercontent.com/8501196/67076471-c81e7e80-f1bf-11e9-95bb-c8201ecdf67e.png)

![image](https://user-images.githubusercontent.com/8501196/67076501-d8cef480-f1bf-11e9-9bd1-98a8f9065fbb.png)

but I check the source of FlutterEngine.class. it is still support library.
![image](https://user-images.githubusercontent.com/8501196/67076605-0c118380-f1c0-11e9-9b5b-ddb6673d3a37.png)

**Comment by zhangcongmin** [comment]
@

**Comment by kf6gpe** [comment]
AndroidX should be fully supported as of the latest stable release. See, for example, https://flutter.dev/docs/development/androidx-migration. If you still have problems, try reaching out to one of the channels at https://flutter.dev/support. Thanks for using Flutter!

**Comment by oth-libs** [comment]
Any solution to this? @zhangcongmin
