### ISSUE TITLE
Unable to load asset / cached image

### ISSUE THREAD

**Issue by Chatenaisien** [flutter/flutter#42998]
Hi Flutter community !

My App have a button to share images loaded from internet. The code is working fine on iOS.
But on Android, the first attempt never works. rootBundle throws an Exception(Unable to load asset).
The rootBundle only find the cached file after a hot restart. So release versions never work :(
==> If I re Run the app, the problem vanish until the next uninstall and reinstall of the app.

I'm using the flutter-cache-manager and esys-flutter-share packages.
And I tried Flutter Clean. Flutter Upgrade. on dev/beta/master channels.

```
shareMedia(int index) async {

    var file = await DefaultCacheManager().getSingleFile(imageLink);

    final ByteData bytes = await rootBundle.load(file.path);
    await Share.file('Hi !!', 'image.png', bytes.buffer.asUint8List(), 'image/png');
  } 
```

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.14.6 18G95, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (3 available)
• No issues found!
```

Any ideas ?

Thanks a lot ! 🙏

**Comment by memtopia** [comment]
I had same problem, change channel to stable will solved.

**Comment by TahaTesser** [comment]
Hi @Chatenaisien 
Please check this [comment](https://github.com/flutter/flutter/issues/42998#issuecomment-552274785) for solution

if you're still experiencing this problem, please create a new issue and provide the information required in the template.
Thank you
