### ISSUE TITLE
add a flag to `flutter start` to configure the observatory

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#43]
From https://github.com/flutter/tools/issues/111

Two things we'd want to do:

have it start the VM with the --pause_isolates_on_start=true flag
start it up listening on a specific port
The pause isolates flag will let us set breakpoints on isolates before they start running. Otherwise we'll miss breakpoints early in the app's lifecycle.

**Comment by sethladd** [comment]
cc @devoncarew still needed?

**Comment by devoncarew** [comment]
Yeah, this will let us setup breakpoints before the app starts running. It'll be important for a good UX.

**Comment by devoncarew** [comment]
This is covered in more specifics by other issues, and is largely (completely?) implemented.
