### ISSUE TITLE
Plugin: Bluetooth / BLE

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#430]
Mobile platforms offer APIs to connect and communicate with Bluetooth.

**Comment by a14n** [comment]
yes please! Especially [Bluetooth Low Energy](http://developer.android.com/guide/topics/connectivity/bluetooth-le.html)

**Comment by sethladd** [comment]
:) I personally want to connect it to an Arduino with BTLE.

**Comment by a14n** [comment]
I received a _Xiaomi Mi Band Pulse_ today and I can't wait to get my datas back (the official _Mi Fit_ app has really to many authorisations needed)

**Comment by mit-mit** [comment]
@pauldemarco is working on a bluetooth plugin here: https://github.com/pauldemarco/flutter_blue

**Comment by sethladd** [comment]
FlutterBlue is looking pretty good! I wonder if we can close this issue?

**Comment by mit-mit** [comment]
My understanding is that FlutterBlue is still Android-only, so not sure we can close this yet.

**Comment by Hixie** [comment]
Moving to next milestone since this is not a priority plugin.

**Comment by rednoah** [comment]
Out-of-the-box bluetooth support would be appreciated. My team decided to go with React Native because Flutter Blue doesn't work on iOS yet. I would have loved to go with Flutter though.

**Comment by BerkOFF** [comment]
Also looking for this to be implemented OOB as I'm working on app which needs to work with BTLE sensors data

**Comment by al-ec** [comment]
Still waiting for someone to implement iOS functionality with Flutter Blue :(

I want to use Flutter SO BAD!

**Comment by pauldemarco** [comment]
FlutterBlue now supports iOS :+1:

**Comment by mit-mit** [comment]
Amazing news @pauldemarco! I'm tentatively going to close this now that [`flutter_blue`](https://pub.dartlang.org/packages/flutter_blue) supports both iOS and Android.

**Comment by mit-mit** [comment]
@pauldemarco have you considered writing a small post about how flutter_blue came to be? I noticed the plugin is quite interesting, also from an implementation point of view with it's use of protobuf for the channel communication.

**Comment by realcarlos** [comment]
How to use flutter_blue to print a string with a bluetooth printer?

**Comment by eugenelet** [comment]
Is there any example on the transmission of data with other devices using this plugin?

**Comment by martyglaubitz** [comment]
Is there any non-low-energy Bluetooth Lib? I am working on a project which uses RFCOMM sockets and that's not in the realm of BLE

**Comment by mit-mit** [comment]
I'm now aware of such a post. We did look a bit a protobuf for the transport, but were a bit worried about it being space inefficient, but we did not do a full investigation.

**Comment by shinayser** [comment]
Why is this issue closed? FlutterBlue communicates with BLE but not Bluetooth Classic.

**Comment by yasasmi** [comment]
hi I have  Add flutter_Blue to my flutter app and now I can connect My MI band 5 with the app but I still can't access data from the MI Band how can I do that? 
it will be really helpful if anyone can help me with this matter. Thank you!
