### ISSUE TITLE
How to return a value inside a builder?

### ISSUE THREAD

**Issue by AnuragVadd** [flutter/flutter#43003]
My application has a `PageView.builder` which displays pages based on dates(ex: initial page will be set to DateTime.now()) and when the user swipes left or right, it will change the page and the displayed date accordingly.

I also have a calendar and i want it to let the user jump to a page which they select in the calendar. The selected date is present inside a builder here :

```
 selectedDayBuilder: (context, date, _) { //need to return date
//          var value = MonthPageViewExample(date);
          return FadeTransition(
            opacity: Tween(begin: 0.0, end: 1.0).animate(_animationController),
            child: Container(
              margin: const EdgeInsets.all(4.0),
              padding: const EdgeInsets.only(top: 5.0, left: 6.0),
              color: Colors.deepOrange[300],
              width: 100,
              height: 100,
              child: Text(
                  '${date.day}',
                  style: TextStyle().copyWith(fontSize: 16.0),
                ),
                ),
          );
        },
```
I want to use the date as a parameter which will be passed on the `PageView.builder` and then the page with the selected date will be displayed on the screen.

Could i get some suggestion on how i can store the date value inside a parameter (perhaps) so that i can pass it to the `PageView.builder`?

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
