### ISSUE TITLE
No Device detected Issue

### ISSUE THREAD

**Issue by ashok-shawacademy** [flutter/flutter#43002]
I tried Connecting my Iphone and debug , but Flutter throws "No devices found" error.

The Phone is detected in the Xcode though. I was able build and run the code via Xcode but Not via flutter

**Comment by catalsdevelop** [comment]
Do you install some tools used by ios-deploy. see https://github.com/flutter/flutter/issues/24219#issuecomment-440356210

**Comment by jonahwilliams** [comment]
@catalsdevelop that is very much out of date

**Comment by ashok-shawacademy** [comment]
ios-deploy was installed yet I had the issue

**Comment by ashok-shawacademy** [comment]
Seems like I have clicked "Move to Bin" or "Move to trash" when prompted with screen mentioned on #42302 . Fixed it by reinstalling and following the steps mentioned in #42302
