### ISSUE TITLE
I try to connect the app with firebase but there is an error message :  I/flutter (30904): Error: PlatformException(error, FirebaseApp with name [DEFAULT] doesn't exist. , null) and i added apply plugin: 'com.google.gms.google-services'  

### ISSUE THREAD

**Issue by Zizu098** [flutter/flutter#43009]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by BondarenkoStas** [comment]
@Zizu098 please file the issue to https://github.com/FirebaseExtended/flutterfire/issues and close it here.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
