### ISSUE TITLE
[Plugin] Google Maps position problem on iOS

### ISSUE THREAD

**Issue by frasza** [flutter/flutter#43010]
Trying to configure Google Maps widget where I have pin with some infoWindow opening when clicking on it.

All good if I have the location zoomed somehow. But in case, I don't have any zoom on the map, it causes some map position issues. 
For instance, when I place the marker more at the top and click on it, the map jumps down and grey area shows at the top. Like said, only happens when not zoomed and on iOS (Android works good).

I took the code from official example and modified it just for the markers.

<img src="https://user-images.githubusercontent.com/22049682/67108059-f6a35600-f1cd-11e9-97c1-064ae79c1313.png" width=400>

Any ideas?

**Comment by VladyslavBondarenko** [comment]
Hi @frasza 
Does it persist with the last google_maps_flutter and the last flutter version (stable or master)?

**Comment by TahaTesser** [comment]
Hi @frasza 
if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
