### ISSUE TITLE
Re-enable `system_debug_ios`, output logging during driver tests for devices running iOS 13+

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#43029]
We should re-enable the `system_debug_ios` devicelab test once https://github.com/flutter/flutter/issues/41133 is resolved. I commented the test out in https://github.com/flutter/flutter/pull/43026.

**Comment by christopherfujino** [comment]
I believe this is still blocked by `flutter drive` not having logs on iOS 13+, is that right @jmagman?

**Comment by godofredoc** [comment]
Do we still want to enable this test?

**Comment by jmagman** [comment]
I think it's been deleted and last I tried I couldn't get it to work https://github.com/flutter/flutter/pull/68756#discussion_r510491997.

**Comment by godofredoc** [comment]
Closing it as the test was deleted.
