### ISSUE TITLE
Enable GL in iOS simulator for tests

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#43028]
Right now we don't have any real coverage of our GL rendering pipeline on iOS. Flutter for simulator forcibly uses the software backend for Skia, so we don't exercise any of our context management code in tests.

The primary reason for this (as I understand it) is to have better performance for developers writing Flutter applications and testing on simulator.

The iOS simulator doesn't have h/w accelerated GL (and even if it did, the GPU is different to mobile so it's largely irrelevant), but even with a software-backed implementation we can test our context management code which I believe adds a lot of value.

**Comment by dingyq** [comment]
face same question, looking forward to the solution

**Comment by jmagman** [comment]
The iOS OpenGL backend was removed https://github.com/flutter/engine/pull/34913
