### ISSUE TITLE
How to change icon from DropdownButtonFormField?

### ISSUE THREAD

**Issue by RenanDelfanti** [flutter/flutter#43025]
On DropdownButton I have icon property, but in DropdownButtonFormField no.
How to do this?

**Comment by CoreyCole** [comment]
Looking [here](https://medium.com/flutteropen/flutter-widgets-13-dropdownbutton-d21e9c226f04), you may need to use `DropdownMenuItem`:
```dart
DropdownButton _itemDown() => DropdownButton<String>(
        items: [
          DropdownMenuItem(
            value: "1",
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Icon(Icons.build),
                SizedBox(width: 10),
                Text(
                  "build",
                ),
              ],
            ),
          ),
          DropdownMenuItem(
            value: "2",
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Icon(Icons.settings),
                SizedBox(width: 10),
                Text(
                  "Setting",
                ),
              ],
            ),
          ),
        ],
        onChanged: (value) {
          setState(() {
            _value = value;
          });
        },
        value: _value,
        isExpanded: true,
      );
```
![icon drop down example](https://miro.medium.com/max/4320/0*dD6Jd6OwL_GYfSzn)


Can you expand more on your use case? Your question is a little vague. Why do you need a form field?

**Comment by RenanDelfanti** [comment]
CoreyCore sorry for vague question!
I need to change this icon on DropdownButtonFormField 
![68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f343332302f302a6444364a64364f774c5f475966537a6e](https://user-images.githubusercontent.com/8375899/67133589-e1d1bd00-f1e3-11e9-94ea-5f1a3515e90f.png)

**Comment by CoreyCole** [comment]
It looks like it should be possible with the DropdownButton, like you said icon is an instance field: https://chromium.googlesource.com/external/github.com/flutter/flutter/+/master/packages/flutter/lib/src/material/dropdown.dart#853

It might not be possible yet with the DropdownButtonFormField. There are other params that are not yet plumbed into the FormField version (itemHeight) see here https://github.com/flutter/flutter/issues/43021

**Comment by RenanDelfanti** [comment]
Latest stable fix this issue
