### ISSUE TITLE
Qiscus SDK

### ISSUE THREAD

**Issue by FbertM** [flutter/flutter#43047]
I am new in using flutter. and I want to add library Qiscus in my apps. but i can't find that packages in the flutter. can you help me with this 

## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by stuartmorgan** [comment]
Wrapping a third-party SDK is something that would be best done in a community plugin, not Flutter. Try some of the community resources at flutter.dev/community for help building, or finding someone to build, a new plugin using an existing SDK.

Closing as this isn't something that would be done in Flutter itself.

**Comment by adicatur** [comment]
Hi @FbertM We just released alpha version for Qiscus chat SDK flutter, you can check plugin here
https://pub.dev/packages/qiscus_chat_sdk

and also for the further docs you can see this link :https://documentation.qiscus.com/chat-sdk-flutter/introduction

please don't hesitate to give any issue or feedback

Regards
