### ISSUE TITLE
Flutter web: Got an XMLHttpRequest error while trying to connect to a url

### ISSUE THREAD

**Issue by aneeshjose** [flutter/flutter#43046]
I am encountering an error XMLHttpRequest error while trying to connect to a localhost as well as an external url. Is there any way to solve this?

## Steps to Reproduce
```
void checkState() async {
    print("CTC");
    var url = "https://us-central1-xxxx.cloudfunctions.net/index";
    try {
      var respX = await http.get(url);
      print("response Arrived ${respX.statusCode}");
    } catch (err) {
      print("error arrived as $err");
    }
  }
```

**Target Platform:web**
**Target OS version/browser:Chrome browser**

Cloud function implementation :

```
/**
 * Responds to any HTTP request.
 *
 * @param {!express:Request} req HTTP request context.
 * @param {!express:Response} res HTTP response context.
 */
exports.helloWorld = (req, res) => {
  let message = req.query.message || req.body.message || 'Hello World!';
  res.status(200).send(({"hello":"world2"}).toString());
};
```

**Comment by casaucao** [comment]
Same issue here. I tried with 'dio' and 'http' packages. Same result.

**Comment by aneeshjose** [comment]
> Same issue here. I tried with 'dio' and 'http' packages. Same result.

I have seen a repo in github. The API he is using is not throwing any error either with http or dio. I pasted my API's url there. Then the same error happens again. Is that a problem with our serverside implementations?

**Comment by jonahwilliams** [comment]
You cannot make an http request to arbitrary domains in a web browser. Generally, if it isn't a same-origin request, you'll need to configure CORS or work around the issue in another way (see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

I'm closing the issue because this is unrelated to Flutter, Dart, or anything else on this repo.

**Comment by casaucao** [comment]
@jonahwilliams was right. A possible (?) workaround would be a CORS proxy. @aneeshjose check this link:

[https://gist.github.com/jimmywarting/ac1be6ea0297c16c477e17f8fbe51347](https://gist.github.com/jimmywarting/ac1be6ea0297c16c477e17f8fbe51347)

**Comment by exeptionerror** [comment]
All Possible Solution added [[Solved] IN Flutter Web getting ‘XMLHttpRequest’ error while making HTTP call](https://fluttercorner.com/flutter-web-getting-xmlhttprequest-error-while-making-http-call/)
