### ISSUE TITLE
The getter 'cutButtonLabel' was called on null

### ISSUE THREAD

**Issue by renanyoy** [flutter/flutter#43050]
when trying to paste on iOS simulator, using material library

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following NoSuchMethodError was thrown building _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#8b81f](dirty, dependencies: [MediaQuery, _LocalizationsScope-[GlobalKey#0f48a]], state: _OverlayEntryState#b55de):
The getter 'cutButtonLabel' was called on null.
Receiver: null
Tried calling: cutButtonLabel
```

I think it happens only since last flutter upgrade, and it was working before

<img width="559" alt="Screenshot 2019-10-19 at 08 20 45" src="https://user-images.githubusercontent.com/259671/67138918-80910480-f24a-11e9-9b0d-31f8576ab900.png">

<img width="559" alt="Screenshot 2019-10-19 at 08 20 26" src="https://user-images.githubusercontent.com/259671/67138913-7838c980-f24a-11e9-899c-27ebb19b117d.png">

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A583, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.39.1)
[✓] Connected device (2 available)
```

**Comment by flbaue** [comment]
@iapicca I created a simple example app here: https://github.com/flbaue/flutter_issue_43050

Just start the app and double tap on the text field at the center.

**Comment by flbaue** [comment]
please reopen, as I provided an example

**Comment by I-am-original** [comment]
Have the same issue in my app. so it is still valid

**Comment by GENL** [comment]
Same problem.

**Comment by GENL** [comment]
Same problem when trying selecting text or double typing TextFormField and TextField. The problem occurs since I upgrade flutter to the last release on Master.

**Comment by GENL** [comment]
```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.15-pre.384, on Microsoft Windows [version 10.0.18362.30], locale fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
[√] VS Code (version 1.39.2)
[√] Connected device (3 available)

• No issues found!```

**Comment by GENL** [comment]
I found a solution here: https://github.com/flutter/flutter/issues/22624#issuecomment-540807500

Just add it:
```localizationsDelegates: [
              ...
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
              GlobalCupertinoLocalizations.delegate,
              DefaultCupertinoLocalizations.delegate
]```,

**Comment by GENL** [comment]
I found a solution here: #22624 (comment)

Just add it:
localizationsDelegates: [
              ...
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
              GlobalCupertinoLocalizations.delegate,
              DefaultCupertinoLocalizations.delegate
],

**Comment by GENL** [comment]
I found a solution here: #22624 (comment)

Just add it:
```dart
localizationsDelegates: [
...
GlobalMaterialLocalizations.delegate,
GlobalWidgetsLocalizations.delegate,
GlobalCupertinoLocalizations.delegate,
DefaultCupertinoLocalizations.delegate
],
```

**Comment by StephanCassel** [comment]
This happens on all TextFields when you long tap or double tap the field. 
Only iOS. Stable v1.9.1+hotfix.6 Channel

The getter 'cutButtonLabel' was called on null.

Ii works if language is English. For example if Norwegian is selected it crashes. 
 
Serious Show Stopper.


[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale en-NO)
    • Flutter version 1.9.1+hotfix.6 at /Users/stephan/development/flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/stephan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

**Comment by GENL** [comment]
> I found a solution here: #22624 (comment)
> 
> Just add it:
> 
> ```dart
> localizationsDelegates: [
>   ...
>   GlobalMaterialLocalizations.delegate,
>   GlobalWidgetsLocalizations.delegate,
>   GlobalCupertinoLocalizations.delegate,
>   DefaultCupertinoLocalizations.delegate
> ],
> ```

If adding it on the materialApp doesn't work, try switching on master and then add it one's more. This could work.

**Comment by I-am-original** [comment]
Hey guys. Any update on possible fix of this issue? Thanks

**Comment by ChristofferSkog21st** [comment]
Noticing the same issue with Swedish language when trying to long tap in a `TextFormField` after you've misspelled something and want to go back to fix it for example.

**Comment by StephanCassel** [comment]
I understad that they are trying to solve it.

This fix the problem for the moment:

MaterialApp(....
....
ThemeData(
        **platform: TargetPlatform.android,**

**Comment by xamantra** [comment]
The bug happens when I long press or double tap a text field.
Only happens on iOS too.

So I tried adding (cupertino localizations delegate):
```dart
localizationsDelegates: [
  ...
  GlobalCupertinoLocalizations.delegate,
  DefaultCupertinoLocalizations.delegate
],
```

It works!

Thumbs up @GENL

**Comment by StephanCassel** [comment]
Thanks xamantra 
It did the trick!

**Comment by jetobe95** [comment]
> The bug happens when I long press or double tap a text field.
> Only happens on iOS too.
> 
> So I tried adding (cupertino localizations delegate):
> 
> ```dart
> localizationsDelegates: [
>   ...
>   GlobalCupertinoLocalizations.delegate,
>   DefaultCupertinoLocalizations.delegate
> ],
> ```
> 
> It works!
> 
> Thumbs up @GENL

**Comment by mikgross** [comment]
> I found a solution here: #22624 (comment)
> 
> Just add it:
> 
> ```dart
> localizationsDelegates: [
>   ...
>   GlobalMaterialLocalizations.delegate,
>   GlobalWidgetsLocalizations.delegate,
>   GlobalCupertinoLocalizations.delegate,
>   DefaultCupertinoLocalizations.delegate
> ],
> ```

Really helpful!

**Comment by TahaTesser** [comment]
I can reproduce the issue and https://github.com/flutter/flutter/issues/43050#issuecomment-555121801 solutions works to fix the issue 

<details> 
<summary>Code Sample</summary> 

``` 
``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 15a28159bc (8 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • SM M305F      • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS desktop • macos            • darwin-x64     • Mac OS X 10.15.5
      19F101
    • Web Server    • web-server       • web-javascript • Flutter Tools
    • Chrome        • chrome           • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!
``` 

</details>

**Comment by younss** [comment]
confirm adding 
```
GlobalCupertinoLocalizations.delegate,
DefaultCupertinoLocalizations.delegate
```
works fine

**Comment by gmendozah** [comment]
> ```dart
> localizationsDelegates: [
>   ...
>   GlobalMaterialLocalizations.delegate,
>   GlobalWidgetsLocalizations.delegate,
>   GlobalCupertinoLocalizations.delegate,
>   DefaultCupertinoLocalizations.delegate
> ],
> ```

This worked fine, Thank you! 🙌

**Comment by investisocial** [comment]
> ```dart
> ```dart
> localizationsDelegates: [
>   ...
>   GlobalMaterialLocalizations.delegate,
>   GlobalWidgetsLocalizations.delegate,
>   GlobalCupertinoLocalizations.delegate,
>   DefaultCupertinoLocalizations.delegate
> ],
> ```
> 
> 
> 
> This worked fine, Thank you! 🙌
> ```

This worked for me too, but don't forget to firstly add 'cupertino' libraries importing.

**Comment by Galti** [comment]
Why this issue is still open?

**Comment by xster** [comment]
@InMatrix or @goderbauer might have some thought. The error message is indeed not very clear. Would be nice to have some way of leading users to https://flutter.dev/docs/development/accessibility-and-localization/internationalization for these types of issues.

**Comment by InMatrix** [comment]
@xster What information would be useful to provide in the error message if we can rewrite it anyway we want? Specifically, do we consider adding this piece of code a solution or a workaround:
```dart
localizationsDelegates: [
  ...
  GlobalMaterialLocalizations.delegate,
  GlobalWidgetsLocalizations.delegate,
  GlobalCupertinoLocalizations.delegate,
  DefaultCupertinoLocalizations.delegate
],
```

**Comment by goderbauer** [comment]
https://github.com/flutter/flutter/pull/68807 makes sure that we throw a more descriptive exception in case we can't find the localizations (for this particular use case and anywhere else in the framework where we look up localizations).

**Comment by MohsenHaydari** [comment]
yesterday i try to localization in iphone , and 
` GlobalCupertinoLocalizations.delegate,
 DefaultWidgetsLocalizations.delegate`
not working for me in "ps" Locale and get `The getter 'cutButtonLabel' was called on null` error,
i try change to master , and dev chanel , but not working,
and finaly i use this for any not supported CupertinoLocalization

`
class NotSupportedCupertinoLocalizationsDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const NotSupportedCupertinoLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => true;

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      DefaultCupertinoLocalizations.load(Locale('en'));// any locale you want and CupertinoLocalizations suported

  @override
  bool shouldReload(NotSupportedCupertinoLocalizationsDelegate old) => false;

  @override
  String toString() => 'DefaultCupertinoLocalizations.delegate(en_US)';
}
`
and in localizationsDelegates
`
localizationsDelegates: [
          .... // material, yourlocalization and Whatever you need
         NotSupportedCupertinoLocalizationsDelegate()
        ],
`
