### ISSUE TITLE
[Question] Are there any hooks to customize flutter build behaviour?

### ISSUE THREAD

**Issue by hanabi1224** [flutter/flutter#43059]
e.g.  Run script to generate protobuf / grpc before normal build

**Comment by janmoppel** [comment]
Hello @hanabi1224 !

Your question seems to be a better fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) as it is not an issue report. Flutter has a very active and helpful community there, so feel free to post it there too.

Also, see other support options here: https://flutter.dev/community

Closing this issue, as it is not a problem report.

Thank you.
