### ISSUE TITLE
[proposal] distinguish between custom and built-in class by color in IDE

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#43051]
## Use case
as i titled, distingishing by color between them, it better to make flutter app

**Comment by GregorySech** [comment]
Intellij and Android Studio already support this.

**Comment by wikiworld** [comment]
> Intellij and Android Studio already support this.

![주석 2019-10-19 180719](https://user-images.githubusercontent.com/52195693/67141116-5b78b200-f29b-11e9-813d-22fac900c5ba.png)

where?

**Comment by GregorySech** [comment]
Sorry I thought you were talking about the file color.

**Comment by maheshmnj** [comment]
Please file the issue in the respective repositories. 
- https://github.com/flutter/flutter-intellij
- https://github.com/Dart-Code/Flutter

closing this issue as invalid, if you disagree feel free to write back.
