### ISSUE TITLE
Material App Error

### ISSUE THREAD

**Issue by anchliyatushar** [flutter/flutter#43052]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by minh98** [comment]
screenshot, console log ... or something else ?

**Comment by iapicca** [comment]
Hi @anchliyatushar 
can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you
