### ISSUE TITLE
Add Stale

### ISSUE THREAD

**Issue by lsaudon** [flutter/flutter#43062]
# Proposal
Add [Stale](https://github.com/marketplace/stale) for clean issues.

**Comment by stuartmorgan** [comment]
Many old issues are perfectly valid; requiring people to periodically comment on every issue to keep it open would create a ton of notification spam.

That kind of bot might make sense for a project with a goal of closing all issues in a set timeframe, but per [this page](https://github.com/flutter/flutter/wiki/Issue-hygiene) that's deliberately not how Flutter operates.
