### ISSUE TITLE
SelectableText not compatible with desktop

### ISSUE THREAD

**Issue by Tokenyet** [flutter/flutter#43060]
```
[√] Flutter (Channel unknown, v1.10.12, on Microsoft Windows [Version 10.0.18362.388], locale zh-TW)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code, 64-bit edition (version 1.38.1)
[!] Connected device
! No devices available
```

I saw a compatibility problem with web, I'm not sure If It's same, so I made a new post here, and according to [SelectableText is not working in go-flutter #285](https://github.com/go-flutter-desktop/go-flutter/issues/285), It's not exposed the text selection value with the embedder. There is a workaround by commenting out this [section](https://github.com/flutter/flutter/blob/e7ffac2d67203ff3e57a01f762fb5374955d14cd/packages/flutter/lib/src/widgets/editable_text.dart#L1385-L1387) as @Drakirus said.

**Comment by stuartmorgan** [comment]
@Tokenyet The issue you referenced says this is fixed now; are you still seeing an issue?

**Comment by Tokenyet** [comment]
@stuartmorgan , Sorry, It's fixed! I'll close It.
