### ISSUE TITLE
[FR] Add event callback on open or close dropdown (DropdownButton & DropdownButtonFormField)

### ISSUE THREAD

**Issue by samuelg123** [flutter/flutter#43061]
## Use case

I want to differentiate between item (on DropdownMenuItem list) TextStyle and selected item (on DropdownButton) TextStyle. Currently it's not possible because we don't know whether the dropdown is opened or not. 

## Proposal
Please add event callback on open or close dropdown (DropdownButton & DropdownButtonFormField)

Maybe something like this:
```dart
DropdownButtonFormField<String>(
   onDropdownOpened: (bool isOpened){

   },
   ...
)
```

Thank you.

**Comment by AyushBherwani1998** [comment]
@samuelg123 There is a property `selectedItemBuilder` which you can use to achieve your desired ouput. Check [here](https://api.flutter.dev/flutter/material/DropdownButton/selectedItemBuilder.html)

**Comment by TahaTesser** [comment]
> I want to differentiate between item (on DropdownMenuItem list) TextStyle and selected item (on DropdownButton) TextStyle. Currently it's not possible because we don't know whether the dropdown is opened or not.'

A stated above, `selectedItemBuilder` is what you need. Closing
