### ISSUE TITLE
flutter run -d chrome still stuck on attempting to connect to the browser instance (Pop-Os 64)

### ISSUE THREAD

**Issue by Subfly** [flutter/flutter#43074]
subfly@pop-os:~/Documents/Flutter Projects/subfly$ flutter run -d chrome -v
[  +15 ms] executing: [/home/subfly/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +34 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1c535de7e0714253c3d71ef8af07b1ea27e2e586
[        ] executing: [/home/subfly/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +13 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.10.14-186-g1c535de7e
[   +7 ms] executing: [/home/subfly/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/subfly/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +44 ms] executing: [/home/subfly/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +91 ms] executing: /home/subfly/Android/Sdk/platform-tools/adb devices -l
[  +10 ms] Exit code 0 from: /home/subfly/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +38 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +131 ms] Generating /home/subfly/Documents/Flutter Projects/subfly/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +106 ms] Launching lib/main.dart on Chrome in debug mode...
[        ] Building application for the web...
[+11601 ms] Daemon is already running.
[ +157 ms] Serving DevTools at http://127.0.0.1:33601

[ +434 ms] About to build [web]...
[   +3 ms] Running build...
[  +51 ms] Running build completed, took 13ms

[        ] Caching finalized dependency graph...
[        ] Caching finalized dependency graph completed, took 45ms

[        ] Succeeded after 60ms with 0 outputs (0 actions)

[   +7 ms] Building application for the web... (completed in 12.3s)
[        ] Attempting to connect to browser instance..
^X^Z
[2]+  Stopped                 flutter run -d chrome -v

***************************************************************************************************************
subfly@pop-os:~/Documents/Flutter Projects/subfly$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.186, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Chrome - develop for the web
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)
*****************************************************************************************************************

flutter run -d chrome still stuck on connecting chrome, and still a window appears and disappear. Please solve this issue, this is my second time that  I opened this issue.

**Comment by Subfly** [comment]
IMPORTANT NOTE

Switched to Deepin Linux 64 bit and everything works perfectly. This might be an issue for Ubuntu 19.04 based linux systems.

**Comment by jonahwilliams** [comment]
What is the commit hash (`flutter doctor -v`) of the stuck browser? There was a bug on master that was fixed recently. Does this continue to happen if you update?

**Comment by Subfly** [comment]
I don't know if it has ever worked on debian based Deepin distros but yesterday when I oppenned the issue, it was not working on Ubuntu based PopOs distro. Maybe it is a system related issue rather than Flutter itself.

**Comment by jonahwilliams** [comment]
> I don't know if it has ever worked on debian based Deepin distros but yesterday when I oppenned the issue, it was not working on Ubuntu based PopOs distro

But what version what is it not working on - without this information I have no idea if this is a new issue or whether you need to update.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by dennougorilla** [comment]
I had the same issue it was because I forgot to add the main function void main() => runApp(MyApp());

**Comment by theindianappguy** [comment]
I resolved it by moving my main in lib directly rather than another folder inside it
