### ISSUE TITLE
Can't print log or debug messages on Mac during flutter run

### ISSUE THREAD

**Issue by abhinavc** [flutter/flutter#43071]
Hi, 
When compiling for Android on Android Studio, I could use print() to write debugging messages. 
However, print() does not seem to print anything on the console if I compile for iOS on a Mac using `flutter run`

I tried `import dart:developer as developer` and then `developer.log(...)`. But that didn't work either. 

So, how does one print debug messages on Mac? Do I use Android Studio? Or Xcode?

Thanks
Abhinav.

**Comment by virskor** [comment]
🙋‍♂️

**Comment by EugenePisotsky** [comment]
I have the same problem after one of the last updates

**Comment by Jasphere-Appsploration** [comment]
Same issue here. If I run using Android Studio, the connection to the device will be lost and cannot get any message back. But if I run the app using Runner.workspace through XCode, the message can be printed.

**Comment by abhinavc** [comment]
Seems this is related to #41133 and #40448. Something has changed in iOS 13 - which is what I have on my iPhone.

**Comment by iapicca** [comment]
Hi @abhinavc 
Please follow up on that issues you linked,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
