### ISSUE TITLE
flutter does not found cocoapods in vscode debug mode 

### ISSUE THREAD

**Issue by heyask** [flutter/flutter#43079]
## Steps to Reproduce

1. in macOS Catalina
2. install flutter, rbenv and ```sudo gem install cocoapods```
2. install vscode, vscode plugins that flutter, dart
3. launch flutter app via vscode debug. this is my ```launch.json```
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Flutter",
      "request": "launch",
      "type": "dart"
    }
  ]
}
```
4. it shows error like below in DEBUG CONSOLE tab.
```
Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install:
  sudo gem install cocoapods
```
5. I looked up below issue. but nothing is solved.
https://github.com/flutter/flutter/issues/14630
6. there is no problem run flutter with ```$ flutter run``` command in terminal. error shows only when I run flutter in vscode debug mode. 
7. this is ```$ which pod```
```
/Users/username/.rbenv/shims/pod
```
## Logs

```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install:
  sudo gem install cocoapods
```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A602, locale ko-US)
    • Flutter version 1.9.1+hotfix.5 at /Users/sunriv/flutter
    • Framework revision 1aedbb1835 (3 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sunriv/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • A4252026-95DB-48BD-9E3F-16DA7B69AD7E • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!
```

**Comment by heyask** [comment]
I resolved this issue by following.

remove rbenv cocoapods 
```
gem uninstall cocoapods
rbenv rehash
```

install cocoapods using homebrew
```brew install cocoapods```

**Comment by vervorm** [comment]
hi,

I'm also having trouble setting up Flutter.
> flutter run 

does work, debug doesn't work from vscode

I tried all solutions regarding cocoapods
but I keep getting this error when I do pods setup

> $ pod setup
>
>/Users/myname/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:289:in 'find_spec_for_exe': can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)
>
>from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:308:in 'activate_bin_path'
>
> from /usr/local/bin/pod:23:in '\<main>'


I'm on Mac Catalina
Can somebody help me out

**Comment by heyask** [comment]
@vervorm Did you tried my solution?

> I resolved this issue by following.
> 
> remove rbenv cocoapods
> 
> ```
> sudo gem uninstall cocoapods
> rbenv rehash
> ```
> 
> install cocoapods using homebrew
> 
> ```
> brew install cocoapods
> ```

I think there is some problems $PATH or something with cocoapods installed by rbenv. I don't know what it is exactly.

**Comment by calleufuzi** [comment]
@heyask this solution works for me, ty

**Comment by absksingm** [comment]
I uninstalled and installed the Flutter extension. It's working for me.

**Comment by f3z0** [comment]
Don't forget to restart vscode.

**Comment by carlleeswanson** [comment]
@sbesnard Can you please explain exactly where to find the 'Settings/Path Variables' in VS Code that you referred to? 
I've searched through the settings but can't find anything that corresponds to either "Path Variables" or to COCOAPOD.

**Comment by netgfx** [comment]
Still have this issue 
```
Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

Exception: CocoaPods not installed or not in valid state.
```

Flutter doctor all fine
```
[✓] Flutter (Channel dev, 1.27.0-4.0.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-GR)
    • Flutter version 1.27.0-4.0.pre at /Users/mixalisdobekidis/SDK/flutter
    • Framework revision f8cd24de95 (3 days ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/NO_NAME_SSD/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
 ```
 
 `gem which cocoapods`
 
 `/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods.rb`

`which pod`

`/usr/local/bin/pod`

Not sure what else I can check/do really I have also linked homebrew

Installed and uninstalled the VSCode plugin multiple times. 

What is weird is if I remove cocoapods from `/Library/Ruby/Gems/2.6.0/gems` it breaks on the flutter doctor as well, but the Ruby version is installed on `/usr/local/opt/ruby/bin/Ruby` But not sure how to change that `2.6.0` reference.
My `.bashrc contains `export PATH="/usr/local/lib/ruby/gems/3.0.0/bin:$PATH"`

**Comment by robertBadamshin** [comment]
I had the same problem, and the problem was in default shell environment. My default shell was bash, but after switching to zsh it worked. My steps:
1) sudo gem uninstall cocoapods
2) then switching default shell https://www.howtogeek.com/444596/how-to-change-the-default-shell-to-bash-in-macos-catalina/
3) reload computer and consider default shell is zsh
4) run brew install cocoapods
5) run visual studio and consider default shell is zsh, if not, select it. Tab Console, then click dropdown list, "select default profile" and select zsh.
6) put in terminal "pod --version", if works, all good
7) try to run build with visual studio button. If some problems, maybe you need to reload visual studio or computer.
