### ISSUE TITLE
Load dependencies saperately on web and Mobile

### ISSUE THREAD

**Issue by praharshbhatt** [flutter/flutter#43077]
## Use case
I want to start a project with a single code base for web and Mobile.

This will mean many plugins will not be supported on both sides like Firebase, image_picker, url_launcher.

I have seen tutorials on how to get Firebase working on Flutter web, but none address how to make the same project run on Mobile as well.

## Proposal
Till there is no official support for a single plugin for Firebase for mobile and web, and many other plugins, we would love to selectively load the dependencies in pubspec.yaml (and import them) for web and Mobile separately.

**Comment by muhleder** [comment]
You can use conditional imports.

```
import 'none.dart'
if (dart.library.js) 'web.dart'
if (dart.library.io) 'mobile.dart'
as firebaseService;
```

I'm using a firebaseService as an adapter around the web and mobile firebase plugins, since the types that each use eg DocumentSnapshots are not compatible.

**Comment by praharshbhatt** [comment]
> You can use conditional imports.
> 
> ```
> import 'none.dart'
> if (dart.library.js) 'web.dart'
> if (dart.library.io) 'mobile.dart'
> as firebaseService;
> ```
> 
> I'm using a firebaseService as an adapter around the web and mobile firebase plugins, since the types that each use eg DocumentSnapshots are not compatible.

Is there any sample project available? Or can you link one?

**Comment by muhleder** [comment]
Not that I know of, I can show you the interface I'm using, which I guess would go in none.dart in my example, and then you would have to implement that interface for web and mobile.

```
import 'dart:async';
import 'package:rxdart/subjects.dart';

abstract class FirebaseServiceInterface {
  dynamic app;
  Completer<dynamic> storage;
  Completer ready;
  dynamic currentUser();
  signInWithEmailAndPassword(String email, String password) {}
  createUserWithEmailAndPassword(String email, String password) {}
  Subject authStateSubject;
  PublishSubject<MyDocumentChange> documentChangesSubjectFactory(String name);
  Future<void> add(String name, String id,  Map<String, dynamic> data);
  Future<void> update(String name, String id, Map<String, dynamic> data);
  Future<List<MyDocumentSnapshot>> getWhere(String name, Map<String, String> conditions);
  Future<Map<String, dynamic>> get(String name, String id);

  onClose() {
    authStateSubject.close();
  }
}

class  MyDocumentChange {
  final String documentID;
  String type;
  Map<String, dynamic> data;
  MyDocumentChange(this.documentID, this.type, this.data);
}

class  MyDocumentSnapshot {
  final String documentID;
  Map<String, dynamic> data;
  MyDocumentSnapshot(this.documentID, this.data);
}
```

**Comment by praharshbhatt** [comment]
I was able to run the same codebase in both without any conditional dependencies declaration.

I just declared all the dependencies that I needed in pubspec and [used the global boolean
kIsWeb](https://stackoverflow.com/a/57965689/6559381)
to check if the project was compiled for web.

For the web, I followed [this tutorial](https://levelup.gitconnected.com/using-firebase-in-flutter-web-4b99952180aa) to get firebase running

**Comment by VladyslavBondarenko** [comment]
Hi @praharshbhatt 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by motorahul** [comment]
i tried to used firebase for mobile and web.
in case of mobile  mobile authentication  perfectly , but for web i did not receive any otp

**Comment by praharshbhatt** [comment]
> i tried to used firebase for mobile and web.
> in case of mobile mobile authentication perfectly , but for web i did not receive any otp

I don't think you'll be able to use phone auth on web.
Why not try Google/Email authentication?
