### ISSUE TITLE
App doesn't have an internet access on Samsung phones

### ISSUE THREAD

**Issue by tadashimelo1** [flutter/flutter#43072]
I have this flutter project that sends data to a web server, the app works fine on every other device apart from Samsung phones, the app seems not to be connecting to the internet on  Samsung phones. I don't know if anyone else has experienced such issue.

**Comment by janmoppel** [comment]
Hello @tadashimelo1 !

Thank you for posting an error message here.
Can you please also provide additional information such as:
1) some example code that demonstrates the issue (e.g. self-contained repository);
2) steps to reproduce the issue;
3) an output of the `flutter doctor -v` command?

Thank you.
