### ISSUE TITLE
Error in Firebase step in codelab

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4307]
Scroll down to Step 4, which says this:
In your Atom workspace, create a new Resources folder under the ios folder in your Flutter project. Move the GoogleService-Info.plist file into the ios folder. 

This is not quite correct. Replace `the ios folder` with `the new ios/Resources folder`.

Now it should read:
In your Atom workspace, create a new Resources folder under the ios folder in your Flutter project. Move the GoogleService-Info.plist file into the new ios/Resources folder.

**Comment by collinjackson** [comment]
good catch, thanks. I've updated the Google Doc, assigning to qchong to publish.

**Comment by qchong** [comment]
Fixed in the doc source. The refreshed codelab instructions are published [here](https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..%2Findex#11).
