### ISSUE TITLE
On macOS Catalina the flutter doctor -v zsh: permission denied error

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#43082]
After downloading flutter_macos_v1.9.1+hotfix.5-stable.zip today I can't run flutter doctor -v. I am keep getting zsh: permission denied. 

After I install macOS Catalina the installed version flutter_macos_v1.9.1+hotfix.4-stable worked perfect.

Can anyone tell me how to correct the issues?

**My .zshrc config:**
```
export PATH="$PATH:/usr/local/opt/unzip/bin"
export PATH="$PATH:/Users/myname/flutter/bin"
export PATH="$PATH:/Users/myname/.pub-cache⁩/bin"
export PATH="$PATH:/Users/myname/flutter⁩/bin/cache/dart-sdk/"
```

**Tried-1:**
```
niyazitoros@Niyazi-MBP ~ % flutter doctor -v
zsh: permission denied: flutter
```

**Tried-2:**
```
MBP ~ % export PATH="$PATH:/Users/niyazitoros/flutter/bin"
MBP ~ % echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin:/usr/local/opt/curl/bin:/usr/local/opt/unzip/bin:/Users/myname/flutter/bin:/Users/myname/.pub-cache⁩/bin:/Users/myname/flutter⁩/bin/cache/dart-sdk/:/Users/myname/flutter/bin
MBP ~ % which flutter
flutter not found
```

**Comment by janmoppel** [comment]
Hello @NTMS2017 !

Thank you for posting the issue.
There was a similar problem reported before here: #19860. Can you check please, does any of the proposed solutions work for you?

**Comment by NTMS2017** [comment]
Hi, @janmoppel my flutter isn't in sudo chown -R [user]:root /opt/flutter. I format my mac and clean install catalina and the rest. now I am facing this problem shown below


```
“gen_snapshot” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.
Safari downloaded this file yesterday at 14:36.

niyazitoros@Niyazi-MBP ~ % flutter doctor -v
[!] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A602, locale en-CY)
    • Flutter version 1.9.1+hotfix.5 at /Users/niyazitoros/flutter
    • Framework revision 1aedbb1835 (5 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/niyazitoros/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available
```

**Comment by NTMS2017** [comment]
OPk I found the solution in here https://github.com/flutter/flutter/issues/36114,

Steps:
**1) flutter doctor -v** (I got the error as: “gen_snapshot” can’t be opened because Apple cannot check it for malicious software.)

**2) sudo spctl --master-disable**
**3) flutter doctor -v** (No error)
**4) sudo spctl --master-enable**
**5)  flutter doctor -v** (No error)

**Comment by timendez** [comment]
The steps don't work for me, I get the same errors

**Comment by iapicca** [comment]
Hi @timendez 
please open a new issue 
providing some or all the information 
indicated in the template, 
thank you

**Comment by edwin-alvarez** [comment]
This was several months ago, but today I faced the same issues, I copied the flutter folder into Mac's Shared user folder, then, my daughter has having issues opening(running) flutter. in order to fix the issues, I did with chmod and give her read-write access for all flutter files under Flutter Shared's user folder

**Comment by zzj0402** [comment]
```
flutter-1.17.5-stable % flutter doctor -v          
zsh: permission denied: flutter
```

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by davidAg9** [comment]
sometimes you might have mistakenly downloaded the windows version of flutter

**Comment by randytia29** [comment]
thanks, David, it really helpful. LOL for all of us

> sometimes you might have mistakenly downloaded the windows version of flutter

Thanks, David, it really helpful. Sometimes it was just a simple of double-check on what that we click. Nice

**Comment by xieyezi** [comment]
@davidAg9 ohhhhhh,fuck!

**Comment by dcchristopher** [comment]
> Ok I found the solution in here #36114,
> 
> Steps:
> **1) flutter doctor -v** (I got the error as: “gen_snapshot” can’t be opened because Apple cannot check it for malicious software.)
> 
> **2) sudo spctl --master-disable**
> **3) flutter doctor -v** (No error)
> **4) sudo spctl --master-enable**
> **5) flutter doctor -v** (No error)

It works for a bit but then I get that error again doing other things (flutter create, etc.) ... :(

**Comment by aiyub007** [comment]
@davidAg9  Life saver comment 💯

**Comment by kirmizi8** [comment]
If you added the path and sure that you have downloaded the correct os files and still get the error:

 - Go to flutter folder
 - Empty folder
 - Open terminal and go to the flutter folder
 - git clone https://github.com/flutter/flutter.git -b stable
