### ISSUE TITLE
Can't build app

### ISSUE THREAD

**Issue by duongbnno1111** [flutter/flutter#43087]
I can't build app: 
* Error running Gradle:
ProcessException: Process "E:\App\i_am_rich\android\gradlew.bat" exited      
abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\App\i_am_rich\android\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Could not open cp_proj remapped class cache for
   di1ovajg50qte31k2y0dno8wu
   (C:\Users\duong\.gradle\caches\4.10.2\scripts-remapped\build_2y3ijk4zmcz4e   0j4ogrb15h4q\di1ovajg50qte31k2y0dno8wu\cp_proj70b1361a260e0ceb212a59c45f68   0ebd).
      > Could not open cp_proj generic class cache for build file
      'E:\App\i_am_rich\android\app\build.gradle'
      (C:\Users\duong\.gradle\caches\4.10.2\scripts\di1ovajg50qte31k2y0dno8wu      \cp_proj\cp_proj70b1361a260e0ceb212a59c45f680ebd).
         > Unexpected lock protocol found in lock file. Expected 3, found 0. 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or      
--debug option to get more log output. Run with --scan to get full insights. 

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
  Command: E:\App\i_am_rich\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.

It's happen when power cut.

## Logs
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version
    10.0.18362.418], locale en-US)
    • Flutter version 1.9.1+hotfix.5 at E:\flutter
    • Framework revision 1aedbb1835 (3 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version
    29.0.2)
    • Android SDK at E:\Android\SDK
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = E:\Android\SDK
    • Java binary at: E:\Android\Android Studios\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[!] Android Studio (version 3.5)
    • Android Studio at E:\Android\Android Studios
    X Flutter plugin not installed; this adds Flutter specific functionality.    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b03)

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\duong\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • SM J500H • 34ebf4cb • android-arm • Android 6.0.1 (API 23)

**Comment by iapicca** [comment]
Hi @duongbnno1111 
It would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by janmoppel** [comment]
Hello @duongbnno1111 !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.

**Comment by chinkysight** [comment]
Same issue here :(
