### ISSUE TITLE
Arrows in codelab should scroll, not change sections

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4308]
The arrow keys and the page up/page down keys in the codelab have been reassigned to navigate the hierarchy. For those of us who are used to scrolling around with the keyboard, this is a big misfeature. Every time I accidentally hit an arrow key, I lose my place in the codelab step and have to go looking for it. To look for it, I try to use page up and page down, which starts the whole process all over again. Please remove this feature.

**Comment by Hixie** [comment]
We don't have a codelab anymore so I'm closing this. When we create a new codelab we will investigate this kind of thing afresh.
