### ISSUE TITLE
Double test failure got marked as yellow, not red

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#43096]
flutter/flutter commit 6a99a8d (jonahwi) devicelab test android_semantics_integration_test (https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci82YTk5YThkOWU0ZGE1ZGQ0ODNhMzQ4NDdhODBiYTk4ZWI1ZmNjOThhDAsSBFRhc2sYgICQlPGi3AsM) failed twice (see the logs), but has a yellow square on the console.

**Comment by digiter** [comment]
Triage: Please reopen this if the new dashboard has this issue.
