### ISSUE TITLE
[build_dashboard] fetchCommitStatuses takes in a range

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#43098]
Right now, it loads the latest 100 commits. The backend will have to be updated to allow for this.

**Comment by keyonghan** [comment]
Removing myself as commented in: https://github.com/flutter/cocoon/pull/622#discussion_r366558647

**Comment by CaseyHillers** [comment]
https://github.com/flutter/cocoon/pull/617 updates the retrieval code for Tasks to be configurable for how many tasks we want to load as different actions require different amounts of endpoints.
