### ISSUE TITLE
Convert model usage to protos

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#43104]
v1 dashboard uses model classes that have been hand written for moving data around.

Both the backend and frontend will need to be updated to use protos. Currently, the frontend for v2 is using protos where it can with the help of some adapters.

**Comment by godofredoc** [comment]
Is this complete @CaseyHillers @keyonghan ?

**Comment by CaseyHillers** [comment]
No. The blocker is there's no straight forward way to use protos with the Dart datastore library, so we're still maintaining two different data models.

**Comment by CaseyHillers** [comment]
@keyonghan since everything is Dart, should we deprecate the protos and use the models in the frontend?

**Comment by keyonghan** [comment]
What is the context we chose protos for frontend models?

**Comment by CaseyHillers** [comment]
I made a prototype of this in https://github.com/flutter/cocoon/pull/1105. It isn't feasible to have one model class used across all of Cocoon. Instead, we need to maintain one "Datastore" class that imports `gcloud` which only the backend uses. Flutter does not support `dart:mirrors` which `package:gcloud` relies on.

We could update the Datastore models to do json serialization matching the protos to move the adapter code out of app_flutter, but I don't see any wins there.

**Comment by godofredoc** [comment]
@CaseyHillers if this isn't feasible should we close this bug?

**Comment by CaseyHillers** [comment]
The major blocker here is what the future of `dart:mirrors` is. If `package:appengine` migrates to generated code instead of reflections for the datastore entities, then we'll get this for free.

I'll close this out as there's no open action items for flutter
