### ISSUE TITLE
Store commit message in proto

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#43107]

**Comment by digiter** [comment]
Triage: what's needed in this bug?

**Comment by CaseyHillers** [comment]
Update the [commit proto](https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/model/proto/internal/commit.proto) to have a field that contains the commit message. This will need to be updated in the commit model first.

This makes it easier for people to refer to changes in the dashboard and not need to cross reference with GitHub.
