### ISSUE TITLE
Indentation error in codelab

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4310]
Go to the *Animate your app* section.
Scroll down to *Dispose the animation*.
The code looks like this:
```dart
void dispose() {
  for (ChatMessage message in _messages)
    message.animationController.dispose();
    super.dispose();
}
```

The line reading `super.dispose()` should be outdented one level.

**Comment by a14n** [comment]
dup of #4215

**Comment by qchong** [comment]
Fixed in the doc source. The refreshed codelab instructions are [here](https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..%2Findex#10).
