### ISSUE TITLE
Fake datastore query returns wrong result when using filter

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#43101]
cocoon/app_dart/lib/src/update_agent_health.dart
cocoon/app_dart/test/request_handlers/update_agent_health_test.dart

For fake datastore, when querying agent with filter like below, it gives records in model, even no record exists based on the filter condition:

final Query<Agent> query = datastore.db.query<Agent>()
      ..filter('agentId =', agentId);
    final List<Agent> agents = await query.run().toList();
    assert(agents.length == 1);
    final Agent agent = agents.single;

For comparison, lookup function works well:

final Key key = datastore.db.emptyKey.append(Agent, id: agentId);
    final Agent agent = await datastore.db.lookupValue<Agent>(key, orElse: () {
      throw BadRequestException('Invalid agent ID: $agentId');
      });

To test:
In Update_agent_health_test.dart: 
    put 'AgentID': 'test1' in tester.requestData, but put 'test' in db. 
    expect*agent.agentId, 'test') gives the wrong answer for "filter", and correct answer for "lookup"

**Comment by godofredoc** [comment]
@keyonghan @CaseyHillers is this still relevant?

**Comment by CaseyHillers** [comment]
I can't find the PR, but this was fixed to run filters in the fake datastore.
