### ISSUE TITLE
Capitalization error in codelab

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4311]
- Go to the Step named *Set Up Your Flutter Environment*
- Scroll down to *Configure Atom for Flutter development*.
- In Step 4 it says, "set the FLUTTER_ROOT field"
- It should say "set the flutter_root field"

**Comment by qchong** [comment]
Fixed in the doc source. The refreshed codelab instructions are published [here](https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..%2Findex#1).
