### ISSUE TITLE
Scroll on android WebView not working Well, and LongPress not firing properly

### ISSUE THREAD

**Issue by Flucadetena** [flutter/flutter#43119]
Hi, I'm trying to capture the "LongPressGesture" on the WebView. I've already achieve the desire result using a GestureDetector as parent of my WebView and it works well on IOS. But when I tried on Android it didn't fire. The Gesture Detector will get all the events but not the LongPress.

I enabled "debugPrintGestureArenaDiagnostics" to see the gestures going to the arena, and apparently on Android, the WebView uses the LongPress to scroll or something like that.

The scroll experience on android is terrible, it doesn't react to touches well and it fails to response a lot of times.

If tested on device and emulator:

ANDROID:
Nexus 6p
OS Version => 8.1.0
Pixel 2
OS Version => API 28

IOS:
IPHONE XR
OS Version => 12.2

If tested with the Gesture Detector and with the property gestureRecognizers of the WebView. The results are these:

---------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------
---------------------  CONCLUSIONS ---------------------
---------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------

IOS -
 1.- WebView interaction is fine, scrolls well and behaves as expected.
 2.- gestureRecognizers property on the WebView won't fire on LongPress.
 3.- A GestureDetector as parent of the WebView will absorb and fire the LongPress as expected (This is the goal).

 ANDROID -
 1.- It doesn't behave as expected, the scroll is very wrong, it doesn't react to the tocuhes with fluidity or precision
 2.- gestureRecognizers property on the WebView will fire onLongPress, but not well, very inconsistently
 3.- A GestureDetector as parent of the WebView WONT absorb nor fire onLongPress, it will with all the other Gestures

---------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------
--------------------- TESTS IN BOTH ANDROID AND IOS ---------------------
---------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------------
--------------------- TEST 1 WITH THE  gestureRecognizers IN THE WEBVIEW ---------------------
---------------------------------------------------------------------------------------------------------

WebView(
    initialUrl: url,
    javascriptMode: JavascriptMode.unrestricted,
    onWebViewCreated: (WebViewController webController) =>
        _completer.complete(webController),
    gestureRecognizers: Set()
    ..add(Factory<LongPressGestureRecognizer>(() {
        return LongPressGestureRecognizer()
        ..onLongPressStart = (LongPressStartDetails details) {
            print('START');
        }
        ..onLongPressMoveUpdate = (LongPressMoveUpdateDetails details) {
            print('UPDATE');
        }
        ..onLongPressUp = () {
            print('UP');
        }
        ..onLongPressEnd = (LongPressEndDetails details) {
            print('END');
        }
        ..onLongPress = () {
            print('longpress generic');
        };
    }))),

LOGS FROM WEBVIEW ON IOS WITH LONGPRESS INSIDE THE WEBVIEW AND WITHOUT THE "gestureRecognizers" SET WITH THE LONG PRESS
    => It scrolls fine
    => It doesn't fire the events of long press

Launching lib/main.dart on iPhone Xʀ 12.2 in debug mode...
Xcode build done.                                           130,1s

--------------------- WEBVIEW OPENED ---------------------

flutter: Gesture arena 2    ❙ ★ Opening new gesture arena.
flutter: Gesture arena 2    ❙ Adding: Instance of '_CombiningGestureArenaMember'
flutter: Gesture arena 2    ❙ Closing with 1 member.
flutter: Gesture arena 2    ❙ Default winner: Instance of '_CombiningGestureArenaMember'
flutter: Gesture arena 3    ❙ ★ Opening new gesture arena.
flutter: Gesture arena 3    ❙ Adding: Instance of '_CombiningGestureArenaMember'
flutter: Gesture arena 3    ❙ Closing with 1 member.
flutter: Gesture arena 3    ❙ Default winner: Instance of '_CombiningGestureArenaMember'
flutter: Gesture arena 4    ❙ ★ Opening new gesture arena.
flutter: Gesture arena 4    ❙ Adding: Instance of '_CombiningGestureArenaMember'
flutter: Gesture arena 4    ❙ Closing with 1 member.
flutter: Gesture arena 4    ❙ Default winner: Instance of '_CombiningGestureArenaMember'
flutter: Gesture arena 5    ❙ ★ Opening new gesture arena.
flutter: Gesture arena 5    ❙ Adding: Instance of '_CombiningGestureArenaMember'
flutter: Gesture arena 5    ❙ Closing with 1 member.
flutter: Gesture arena 5    ❙ Default winner: Instance of '_CombiningGestureArenaMember'

LOGS FROM WEBVIEW ON ANDORID WITHOUT THE "gestureRecognizers" SET WITH THE LONG PRESS
    => It doesn't scroll well, some times ignores the finguer and it doesn't stop when you tocuh the screen and it is scrolling (check the video)

Launching lib/main.dart on Nexus 6P in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.

--------------------- WEBVIEW OPENED ------------------------------------------

I/WebViewFactory( 2287): Loading com.android.chrome version 76.0.3809.111 (code 380911137)
I/cr_LibraryLoader( 2287): Time to load native libraries: 4 ms (timestamps 6612-6616)
I/chromium( 2287): [INFO:library_loader_hooks.cc(51)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader( 2287): Expected native library version number "76.0.3809.111", actual native library version number "76.0.3809.111"
W/cr_ChildProcLH( 2287): Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
I/cr_BrowserStartup( 2287): Initializing chromium process, singleProcess=false
W/ResourceType( 2287): Failure getting entry for 0x7f130532 (t=18 e=1330) (error -2147483647)
W/es.bymeapp.beta( 2287): type=1400 audit(0.0:281): avc: denied { read } for name="vmstat" dev="proc" ino=4026548020 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc:s0 tclass=file permissive=0
W/cr_media( 2287): Requires BLUETOOTH permission
W/VideoCapabilities( 2287): Unrecognized profile 2130706433 for video/avc
I/VideoCapabilities( 2287): Unsupported profile 4 for video/mp4v-es
I/zygote64( 2287): Do full code cache collection, code=250KB, data=164KB
I/zygote64( 2287): After code cache collection, code=223KB, data=122KB
I/chromium( 2287): [INFO:CONSOLE(1)] "Translating from: en", source: https://cdn.shopify.com/s/files/1/0302/4437/t/3/assets/layout.theme.js?2864530 (1)
I/chromium( 2287): [INFO:CONSOLE(1)] "Geolocation: es", source: https://cdn.shopify.com/s/files/1/0302/4437/t/3/assets/layout.theme.js?2864530 (1)
I/zygote64( 2287): Do partial code cache collection, code=248KB, data=152KB
I/zygote64( 2287): After code cache collection, code=248KB, data=152KB
I/zygote64( 2287): Increasing code cache capacity to 1024KB

------------------------------------------- SCROLLING ON THE WEBVIEW------------------------------

I/flutter ( 2287): Gesture arena 6    ❙ ★ Opening new gesture arena.
I/flutter ( 2287): Gesture arena 6    ❙ Adding: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 6    ❙ Adding: LongPressGestureRecognizer#0d077(debugOwner: GestureDetector, state: ready)
I/flutter ( 2287): Gesture arena 6    ❙ Closing with 2 members.
I/flutter ( 2287): Gesture arena 6    ❙ Rejecting: LongPressGestureRecognizer#0d077(debugOwner: GestureDetector, state: possible)
I/flutter ( 2287): Gesture arena 6    ❙ Default winner: Instance of '_CombiningGestureArenaMember'
I/zygote64( 2287): Compiler allocated 6MB to compile void android.view.ViewRootImpl.performTraversals()
I/flutter ( 2287): Gesture arena 7    ❙ ★ Opening new gesture arena.
I/flutter ( 2287): Gesture arena 7    ❙ Adding: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 7    ❙ Adding: LongPressGestureRecognizer#0d077(debugOwner: GestureDetector, state: ready)
I/flutter ( 2287): Gesture arena 7    ❙ Closing with 2 members.
I/flutter ( 2287): Gesture arena 7    ❙ Rejecting: LongPressGestureRecognizer#0d077(debugOwner: GestureDetector, state: possible)
I/flutter ( 2287): Gesture arena 7    ❙ Default winner: Instance of '_CombiningGestureArenaMember'

LOGS FROM WEBVIEW ON ANDORID WITH LONGPRESS INSIDE THE WEBVIEW
    => It doesn't scroll well.
    => Only sometimes fires LongPressStart
    => Only fires LongPressMoveUpdate when scrolling, not after an actual longpress and moving the finger.
    => Never Fires the LongPressEnd.

Restarted application in 1.781ms.

-------------------------------------------WEBVIEW OPENED ------------------------------------------

I/chromium( 2287): [INFO:CONSOLE(1)] "Translating from: en", source: https://cdn.shopify.com/s/files/1/0302/4437/t/3/assets/layout.theme.js?2864530 (1)
I/chromium( 2287): [INFO:CONSOLE(1)] "Geolocation: es", source: https://cdn.shopify.com/s/files/1/0302/4437/t/3/assets/layout.theme.js?2864530 (1)

------------------------------------------- SCROLLING ON THE WEBVIEW------------------------------

I/flutter ( 2287): Gesture arena 3    ❙ ★ Opening new gesture arena.
I/flutter ( 2287): Gesture arena 3    ❙ Adding: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 3    ❙ Adding: LongPressGestureRecognizer#78f52(debugOwner: GestureDetector, state: ready)
I/flutter ( 2287): Gesture arena 3    ❙ Closing with 2 members.
I/flutter ( 2287): Gesture arena 3    ❙ Rejecting: LongPressGestureRecognizer#78f52(debugOwner: GestureDetector, state: possible)
I/flutter ( 2287): Gesture arena 3    ❙ Default winner: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 4    ❙ ★ Opening new gesture arena.
I/flutter ( 2287): Gesture arena 4    ❙ Adding: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 4    ❙ Adding: LongPressGestureRecognizer#78f52(debugOwner: GestureDetector, state: ready)
I/flutter ( 2287): Gesture arena 4    ❙ Closing with 2 members.
I/flutter ( 2287): Gesture arena 4    ❙ Rejecting: LongPressGestureRecognizer#78f52(debugOwner: GestureDetector, state: possible)
I/flutter ( 2287): Gesture arena 4    ❙ Default winner: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 5    ❙ ★ Opening new gesture arena.
I/flutter ( 2287): Gesture arena 5    ❙ Adding: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 5    ❙ Adding: LongPressGestureRecognizer#78f52(debugOwner: GestureDetector, state: ready)
I/flutter ( 2287): Gesture arena 5    ❙ Closing with 2 members.
I/flutter ( 2287): Gesture arena 5    ❙ Accepting: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 5    ❙ Self-declared winner: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): START
I/flutter ( 2287): longpress generic
I/flutter ( 2287): Gesture arena 6    ❙ ★ Opening new gesture arena.
I/flutter ( 2287): Gesture arena 6    ❙ Adding: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 6    ❙ Adding: LongPressGestureRecognizer#78f52(debugOwner: GestureDetector, state: ready)
I/flutter ( 2287): Gesture arena 6    ❙ Closing with 2 members.
I/flutter ( 2287): UPDATE
I/chatty  ( 2287): uid=10252(es.bymeapp.beta) Thread-6 identical 4 lines
I/flutter ( 2287): UPDATE
I/flutter ( 2287): Gesture arena 6    ❙ Rejecting: LongPressGestureRecognizer#78f52(debugOwner: GestureDetector, state: possible)
I/flutter ( 2287): Gesture arena 6    ❙ Default winner: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 7    ❙ ★ Opening new gesture arena.
I/flutter ( 2287): Gesture arena 7    ❙ Adding: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 7    ❙ Adding: LongPressGestureRecognizer#78f52(debugOwner: GestureDetector, state: ready)
I/flutter ( 2287): Gesture arena 7    ❙ Closing with 2 members.
I/flutter ( 2287): UPDATE
I/flutter ( 2287): UPDATE
I/chatty  ( 2287): uid=10252(es.bymeapp.beta) Thread-6 identical 2 lines
I/flutter ( 2287): UPDATE
I/flutter ( 2287): Gesture arena 7    ❙ Accepting: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 7    ❙ Self-declared winner: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): START
I/flutter ( 2287): longpress generic
I/flutter ( 2287): Gesture arena 8    ❙ ★ Opening new gesture arena.
I/flutter ( 2287): Gesture arena 8    ❙ Adding: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 8    ❙ Adding: LongPressGestureRecognizer#78f52(debugOwner: GestureDetector, state: ready)
I/flutter ( 2287): Gesture arena 8    ❙ Closing with 2 members.
I/flutter ( 2287): UPDATE
I/flutter ( 2287): Gesture arena 8    ❙ Accepting: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 8    ❙ Self-declared winner: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): START
I/flutter ( 2287): longpress generic

---------------------------------------------------------------------------------------------------------
-------------------------------- TEST 2 WITH THE GESTURE DETECTOR -------------------------------
---------------------------------------------------------------------------------------------------------

 GestureDetector(
    onLongPressStart: (LongPressStartDetails details) => print('STARTS'),
    onLongPressMoveUpdate: (LongPressMoveUpdateDetails details) => print('MOVE UPDATED'),
    onLongPressEnd: (LongPressEndDetails details) => print('END'),
    child: WebView(
    initialUrl: url,
    javascriptMode: JavascriptMode.unrestricted,
    onWebViewCreated: (WebViewController webController) =>
        _completer.complete(webController),
    ),
),

LOGS FROM WEBVIEW ON IOS WITH LONGPRESS EVENTS ON THE GESTURE RECOGNIZER
    => It scrolls fine
    => It fires and absorbs the event, locking the scoll.

Launching lib/main.dart on iPhone Xʀ 12.2 in debug mode...
Xcode build done.                                           28,6s

-------------------------------------------WEBVIEW OPENED ------------------------------------------

------------------------------------------- SCROLLING ON THE WEBVIEW------------------------------

flutter: Gesture arena 2    ❙ ★ Opening new gesture arena.
flutter: Gesture arena 2    ❙ Adding: Instance of '_CombiningGestureArenaMember'
flutter: Gesture arena 2    ❙ Adding: LongPressGestureRecognizer#0bb23(debugOwner: GestureDetector, state: ready)
flutter: Gesture arena 2    ❙ Closing with 2 members.
flutter: Gesture arena 2    ❙ Rejecting: LongPressGestureRecognizer#0bb23(debugOwner: GestureDetector, state: possible)
flutter: Gesture arena 2    ❙ Default winner: Instance of '_CombiningGestureArenaMember'
flutter: Gesture arena 3    ❙ ★ Opening new gesture arena.
flutter: Gesture arena 3    ❙ Adding: Instance of '_CombiningGestureArenaMember'
flutter: Gesture arena 3    ❙ Adding: LongPressGestureRecognizer#0bb23(debugOwner: GestureDetector, state: ready)
flutter: Gesture arena 3    ❙ Closing with 2 members.
flutter: Gesture arena 3    ❙ Rejecting: LongPressGestureRecognizer#0bb23(debugOwner: GestureDetector, state: possible)
flutter: Gesture arena 3    ❙ Default winner: Instance of '_CombiningGestureArenaMember'
flutter: Gesture arena 4    ❙ ★ Opening new gesture arena.
flutter: Gesture arena 4    ❙ Adding: Instance of '_CombiningGestureArenaMember'
flutter: Gesture arena 4    ❙ Adding: LongPressGestureRecognizer#0bb23(debugOwner: GestureDetector, state: ready)
flutter: Gesture arena 4    ❙ Closing with 2 members.
flutter: Gesture arena 4    ❙ Accepting: LongPressGestureRecognizer#0bb23(debugOwner: GestureDetector, state: possible)
flutter: Gesture arena 4    ❙ Self-declared winner: LongPressGestureRecognizer#0bb23(debugOwner: GestureDetector, state: possible)

------------------------------------------- LONGPRESS ON THE WEBVIEW-----------------------------

flutter: STARTS
flutter: MOVE UPDATED
flutter: MOVE UPDATED
flutter: MOVE UPDATED
flutter: MOVE UPDATED
flutter: MOVE UPDATED
flutter: MOVE UPDATED
flutter: MOVE UPDATED
flutter: MOVE UPDATED
flutter: MOVE UPDATED
flutter: MOVE UPDATED
flutter: END
flutter: STARTS
flutter: MOVE UPDATED
flutter: MOVE UPDATED
flutter: MOVE UPDATED
flutter: END

LOGS FROM WEBVIEW ON ANDROID WITH LONGPRESS EVENTS ON THE GESTURE RECOGNIZER
    => It DOES NOT scroll well
    => It DOES NOT  fire, NOR absorbs the event, NOT locking the scoll.
    => After first LongPress it scrolls even worst, apparently.
    => The gesture recognizer will absorb all events BUT the LongPress

Restarted application in 1.787ms.

-------------------------------------------WEBVIEW OPENED ------------------------------------------

I/zygote64( 2287): Compiler allocated 4MB to compile void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int)
I/chromium( 2287): [INFO:CONSOLE(1)] "Translating from: en", source: https://cdn.shopify.com/s/files/1/0302/4437/t/3/assets/layout.theme.js?2864530 (1)
I/chromium( 2287): [INFO:CONSOLE(1)] "Geolocation: es", source: https://cdn.shopify.com/s/files/1/0302/4437/t/3/assets/layout.theme.js?2864530 (1)

------------------------------------------- SCROLLING ON THE WEBVIEW------------------------------

I/flutter ( 2287): Gesture arena 3    ❙ ★ Opening new gesture arena.
I/flutter ( 2287): Gesture arena 3    ❙ Adding: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 3    ❙ Adding: LongPressGestureRecognizer#b234d(debugOwner: GestureDetector, state: ready)
I/flutter ( 2287): Gesture arena 3    ❙ Adding: LongPressGestureRecognizer#30637(debugOwner: GestureDetector, state: ready)
I/flutter ( 2287): Gesture arena 3    ❙ Closing with 3 members.
I/flutter ( 2287): Gesture arena 3    ❙ Rejecting: LongPressGestureRecognizer#b234d(debugOwner: GestureDetector, state: possible)
I/flutter ( 2287): Gesture arena 3    ❙ Rejecting: LongPressGestureRecognizer#30637(debugOwner: GestureDetector, state: possible)
I/flutter ( 2287): Gesture arena 3    ❙ Default winner: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 9    ❙ ★ Opening new gesture arena.
I/flutter ( 2287): Gesture arena 9    ❙ Adding: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 9    ❙ Adding: LongPressGestureRecognizer#b234d(debugOwner: GestureDetector, state: ready)
I/flutter ( 2287): Gesture arena 9    ❙ Adding: LongPressGestureRecognizer#30637(debugOwner: GestureDetector, state: ready)
I/flutter ( 2287): Gesture arena 9    ❙ Closing with 3 members.
I/flutter ( 2287): Gesture arena 9    ❙ Accepting: LongPressGestureRecognizer#b234d(debugOwner: GestureDetector, state: possible)
I/flutter ( 2287): Gesture arena 9    ❙ Self-declared winner: LongPressGestureRecognizer#b234d(debugOwner: GestureDetector, state: possible)

------------------------------ IF YOU SCROLL FAST => it doesn't react well and print a diferent log: -----

I/flutter ( 2287): Gesture arena 52   ❙ ★ Opening new gesture arena.
I/flutter ( 2287): Gesture arena 52   ❙ Adding: Instance of '_CombiningGestureArenaMember'
I/flutter ( 2287): Gesture arena 52   ❙ Adding: LongPressGestureRecognizer#b234d(debugOwner: GestureDetector, state: ready)
I/flutter ( 2287): Gesture arena 52   ❙ Adding: LongPressGestureRecognizer#30637(debugOwner: GestureDetector, state: ready)
I/flutter ( 2287): Gesture arena 52   ❙ Closing with 3 members.
I/flutter ( 2287): Gesture arena 52   ❙ Rejecting: LongPressGestureRecognizer#30637(debugOwner: GestureDetector, state: possible)
I/flutter ( 2287): Gesture arena 52   ❙ Rejecting: LongPressGestureRecognizer#b234d(debugOwner: GestureDetector, state: possible)
I/flutter ( 2287): Gesture arena 52   ❙ Sweeping with 1 member.
I/flutter ( 2287): Gesture arena 52   ❙ Winner: Instance of '_CombiningGestureArenaMember'

-------------------------------- FLUTTER DOCTOR --------------------------------
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A602, locale es-ES)
    • Flutter version 1.9.1+hotfix.5 at /Users/fer/flutter
    • Framework revision 1aedbb1835 (3 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc1)
    • Android SDK at /Users/fer/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc1
    • ANDROID_HOME = /Users/fer/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode 2.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • iPhone Xʀ 12.2 • B2E1F1C9-5A0F-4072-A13F-3EDF3713F499 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

**Comment by iapicca** [comment]
Hi @Flucadetena 
I see there are open issues addressing the case you described:
- [scrolling 1](https://github.com/flutter/flutter/issues/35394 )
- [scrolling 2](https://github.com/flutter/flutter/issues/40666)
- [gestures](https://github.com/flutter/flutter/issues/36304)
Please follow up on those issues,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by Flucadetena** [comment]
Thanks Francecsco for taking the time. I do disagree as I think that the problem may be related but it's other than thoes you listed. In my case scrolling doesn't work well at all. And in Ios after a longpress it becomes very bad. It is not related with other widgets or a webview inside a pageview. Today I tasted on an iPhone X and the scroll bar of the web would appear in the middle of the screen.

I was making a huge effort to move the hole app of our startup to flutter in a month for the Websummit, but seeing how bad the webview is I've decided to wait until it becomes usable, as it is the corner stone of our app. I'm ver sad about it as I was loving Flutter, and hope this gets fixed so I can come back to it.

If i can give more details or help in any way please let me now.

**Comment by shoaibomar** [comment]
The web view currently filters long press, as text selection doesn't work : https://github.com/flutter/flutter/issues/24585,

To fix scrolling problems you just have to comment out the line of code that filters the long press, but then you will end up with a text selection dialog that does nothing.
