### ISSUE TITLE
The agent should be able to automatically update itself

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#43125]
For example, it could be a simple script that knows how to use CIPD and authenticate against the backend. Then it just gets downloaded by CIPD and used for each test run.

That way, we won't have as hard a time re-imaging the machines.

As an extreme version of this, the whole machine should be running LUCI, but we could do the CIPD part as an intermediate step.

**Comment by CaseyHillers** [comment]
This will be obsolete after the devicelab migration to LUCI is complete.
