### ISSUE TITLE
Logs should get uploaded to GCS instead of Datastore

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#43124]
We could upload separate log files this way (e.g. cocoon, logcat, etc.).  We could also potentially upload recordings of the run.

**Comment by keyonghan** [comment]
This should avoid gRPC quota error (happens when multiple people getting log at the same time) after being implemented.

**Comment by dnfield** [comment]
We could also look at using logdog - /cc @riannucci who might know if that's feasible at this point.

**Comment by riannucci** [comment]
yes that should be feasible; what's generating the logs, and in what context is it running?

**Comment by dnfield** [comment]
We have a set of physical machines running in our devicelab - currently, they upload log chunks to datastore.  We'd like to be able to just send the chunks to logdog instead and get all the logging goodness it does.

**Comment by riannucci** [comment]
So these run within the context of a recipe?

**Comment by dnfield** [comment]
No - they are run by a home-grown system that is not part of LUCI at all.

**Comment by riannucci** [comment]
I don't believe we have the ability to support this use case at the time. You could theoretically stand up your own logdog instance though.

**Comment by dnfield** [comment]
Looks like there are instructions at https://github.com/luci/luci-go/tree/master/logdog

It's not 100% clear to me whether that's more or less work for us.  I suspect logdog has worked out a lot of gotchas that we'd face, but it also means maintaining an instance of a service we don't really own.  Will defer to @godofredoc on that one.

**Comment by godofredoc** [comment]
This will be obsolete after DeviceLab tests start running on LUCI. LUCI uses a temporary chroot to run tests and deletes everything after the task completes.

@digiter please close this bug when migration is complete.
