### ISSUE TITLE
Cocoon agent should use a service account instead of an API key

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#43123]
We should generate a service account key, and use that to get an oauth token to make requests.

/cc @tvolkert

**Comment by godofredoc** [comment]
@CaseyHillers do you know how much effort would this require?

**Comment by CaseyHillers** [comment]
The LUCI devicelab tasks use short lived service account tokens.

There's only one cocoon agent left before we delete the cocoon agent. After the windows migration to LUCI is complete, we can mark this obsolete.

**Comment by godofredoc** [comment]
This is complete now we can use gcloud tokens to access cocoon apis.
