### ISSUE TITLE
Instructions are out of order for setting up the codelab

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4312]
On the page for *Set Up Your Flutter Environment*, Step 2 says, "The first time your run the flutter command, it will download its dependencies and compile itself. Subsequent runs should be much faster." Then the user is prompted to update the environment, which has nothing to do with what they were just told.

Then, in Step 3, the instructions say to run `flutter doctor`. It says, "Run the flutter doctor command to see if there are any dependencies you need to install to complete the setup."

This is inconsistent. The instructions from Step 2 should be moved to Step 3, because doing that installation is the primary purpose of running `flutter doctor` in Step 3. The existing instructions about  "see if there are any dependencies you need to install" are also not quite right. Flutter will install most dependencies. There *may* be additional dependencies that the user needs to take care of.

**Comment by qchong** [comment]
Fixed in the doc source. The refreshed codelab instructions are published [here](https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..%2Findex#1).
