### ISSUE TITLE
Devicelab agent leaks iproxy processes

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#43132]
Looking at one of the Mac buildbots, I see 232 instances of iproxy running on the machine, dating back since the last reboot. They all appear to be zombies that have picked up `init` as their PPID.

**Comment by godofredoc** [comment]
This is obsolete, we haven't seen any leaked iproxy processes recently.

**Comment by christopherfujino** [comment]
for reference this was closed in https://github.com/flutter/flutter/pull/42026
