### ISSUE TITLE
Dart high memory when open VS Code (macos)

### ISSUE THREAD

**Issue by git-maspaad** [flutter/flutter#43139]
Hi, I'm getting slow when I open vs code that has installed Flutter plugins.
I look memory size of dart, consumed : 1,05 GB

Details :
```
cwd
/
txt
/Users/macosx/flutter-1.10.4/bin/cache/dart-sdk/bin/dart
txt
/Users/macosx/flutter-1.10.4/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
txt
/Users/macosx/flutter-1.10.4/bin/cache/dart-sdk/bin/snapshots/kernel-service.dart.snapshot
txt
/usr/lib/dyld
txt
/private/var/db/dyld/dyld_shared_cache_x86_64
0
->0x6615e580cac70bb5
1
->0x6615e580cac71515
2
->0x6615e580cac707cd
3
->0x6615e580cac759a5
4
->0x6615e580cac75a65
5
count=0, state=0xa
6
->0x6615e580cac785e5
7
->0x6615e580cac75b25
10
->0x6615e580cac758e5
11
->0x6615e580cac78525
12
->0x6615e580cac786a5
13
->0x6615e580cac78465
37
/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar
```

and here the picture. Please fix it, if there are some bugs. Thank you.
![Screen Shot 2019-10-21 at 09 26 07](https://user-images.githubusercontent.com/33727072/67172258-d7324600-f3e4-11e9-90da-fe8202b70713.png)

**Comment by janmoppel** [comment]
Hello @git-maspaad !

Thank you for posting an issue.
Can you please provide the `flutter doctor -v` command output?
Does this happen in general for VScode or for a certain Flutter project?

Also, it would be really helpful if you could attach your Mac technical information (processor, memory etc). Just in case, there is a problem with a certain hardware.

**Comment by git-maspaad** [comment]
> Hello @git-maspaad !
> 
> Thank you for posting an issue.
> Can you please provide the `flutter doctor -v` command output?
> Does this happen in general for VScode or for a certain Flutter project?
> 
> Also, it would be really helpful if you could attach your Mac technical information (processor, memory etc). Just in case, there is a problem with a certain hardware.

![Screen Shot 2019-10-29 at 11 19 35](https://user-images.githubusercontent.com/33727072/67737517-0fb5cd80-fa3e-11e9-9ac8-bcc84a0f43f8.png)

**Comment by DanTup** [comment]
@git-maspaad how big is your project? (for ex. number of Dart files in the folders open in VS Code)

Can you post the full output of running `code --status` in a terminal when your memory usage is this high?

**Comment by MichelDiz** [comment]
I have also been experiencing this. Even after closing VSCode, there was an instance of Dart running for hours. I had to use HTOP a few times to force the stop.

**Comment by DanTup** [comment]
@MichelDiz if you see that again, could you try to get the command line of the process that's still running? There are several Dart processes spawned that it could be (for ex. the analysis server, the Flutter daemon, a `flutter run` process etc). Please open an issue in [Dart-Code](https://github.com/Dart-Code/Dart-Code) as leaked processes are probably a bug there and is different to high memory usage.
