### ISSUE TITLE
Improved dashboard view

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#43133]
Forked from flutter/cocoon#199.

@yjbanov wrote:
I think we need a new dashboard view entirely. The current view does not scale at all. Ideally the view would surface the most important signals first, and let the less important ones go off-screen. These signals would be per-commit and therefore there wouldn't be any a priori sort order of tasks for all commits on the screen.

**Comment by godofredoc** [comment]
Casey can you please take a look at this bug and update/close?

**Comment by digiter** [comment]
Triage: the new dashboard has already sorts the failed tasks first.
