### ISSUE TITLE
Ability to run some tests pre-commit via GitHub webhook

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#43134]
Minimal amount of tests.  Initial guess as to which ones:

- [ ] hot reload on Android
- [ ] hot reload on iOS

.. that may be all we need 😄

**Comment by eseidelGoogle** [comment]
This is covering pre-commit testing, correct?  Is this bug still valid/useful?

**Comment by tvolkert** [comment]
We now have what this bug was meant to cover - closing.
