### ISSUE TITLE
Simplify the whole cocoon environment

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#43146]
It would be easier for people like me to drop in and make quick fixes and get out again if there were no dependencies for building the dashboard other than Dart.

In particular, I'd rather not have to learn AppEngine, Go, Angular, and Cocoon just to change a few tiles or fix a few benchmarks. It should be possible to test the UI on your local workstation (e.g. by having it hosted from a Dart app running the Web server). I don't really mind how complicated the multiplexing to multiple devices is, so long as I can test a single device locally and make sure it all works.

If this was fixed I could fix most of the other bugs that I just filed in my spare time while waiting for Travis. :-)

**Comment by digiter** [comment]
Triage: we have removed the Go backend.
