### ISSUE TITLE
UI improvements for dashboard

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#43140]
The following improvements would be a great help to using the dashboard:

- [ ] When a commit doesn't have data, show that commit (just with no data). That way we can tell when we've stopped receiving data.

- [ ] The benchmark history panel should be `position: fixed; top: 0; left: 0; right: 0` (and when it's present, some padding should be added to the main body so that it doesn't overlap the top graphs). This would make going through lots of benchmarks adjusting them MUCH easier.

- [ ] A placeholder for the benchmark history panel should survive when we're switching from one to another (so that we can completely stop the bouncing effect).

- [ ] Show the goal/baseline as soon as the benchmark history panel is up, before downloading the data itself, so that that can be updated more quickly. (We're now taking literally multiple seconds to download the 100+KB of data for each benchmark when the graph is shown.) The goal/baseline should already be locally available.

- [ ] When you click "Update", it should clear the server cache and update the local graph. (The local graph can be updated from the data that's already been downloaded, no need to actually fetch the whole page again from the server.)

- [ ] Don't reload the whole page when updating the graphs, just download the new data and inline replace the graphs. The whole-page reload is making it hard to maintain one's place when updating lots of graphs.

**Comment by godofredoc** [comment]
Casey can you please take a look at this bug and update/close?

**Comment by CaseyHillers** [comment]
Additional feedback given from team members in October:

- [ ] Better authentication UI
- [ ] Readable text displayed over benchmark data
- [ ] Trend lines
- [ ] Enlarge a chart further
- [ ] Check older records (more than now)
- [ ] Notifications of when issues arise
- [ ] Move the time window
- [ ] Show commits that caused regressions
- [ ] Link benchmarks to Github issues, tracking filed regressions made easier

I am unassigning so anyone can feel free to pick up rewriting the performance dashboard in Flutter.

**Comment by digiter** [comment]
Triage: closing since the recent improvements seem to have satisfy the requirements.
