### ISSUE TITLE
Make TimePickerDialog and DatePickerDialog public

### ISSUE THREAD

**Issue by agordeev** [flutter/flutter#43158]
## Use case

I want to create a platform independent date picker and time picker widget for my app. On iOS it should slide up from bottom, just like a standard `UIDatePicker`. On Android it should pop up, just like when you call `showTimePicker(..)` or `showDatePicker(..)`.
It'd be great if I could create an abstract widget `TimePicker`:

```dart
/// Abstract picker. 
/// It'd be great in a concrete implementation on Android platform could use `TimePickerDialog`.
abstract class TimePicker extends StatefulWidget {
  final TimeOfDay initialTime

  const TimeSelectorScreen({Key key, @required this.initialTime})
      : assert(initialTime != null),
        super(key: key);
}
```
and two concrete implementations for both platforms: `CupertinoTimePicker` and `MaterialTimePicker`. This way I can be sure that the screen presenting a picker doesn't care about the platform the app is running on: I can operate the absract `TimePicker` widget.
But, unfortunately, we can't use `_TimePickerDialog` and `_DatePickerDialog` because they are marked as private. The only way to use them is to call `showTimePicker(..)` or `showDatePicker(..)`.

## Proposal

I suggest to make [`_TimePickerDialog`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/time_picker.dart) and [`_DatePickerDialog`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/date_picker.dart) public, so users can use them in custom widgets.

Any thoughts?

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by duzenko** [comment]
I need this for a simpler thing: the date dialog exactly what `showDatePicker` does but with round corners

**Comment by TahaTesser** [comment]
DatePicker is now possible to use without a dialog, for Time Picker, please see https://github.com/flutter/flutter/issues/76053
