### ISSUE TITLE
cached_network_image behave differently under io.flutter.embedding and io.flutter.view.

### ISSUE THREAD

**Issue by pouloghost** [flutter/flutter#43156]
```
[✓] Flutter (Channel unknown, v1.7.8+hotfix.4, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.4 at /Users/gt/tools/flutter
    • Framework revision 20e59316b8 (3 months ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0
```
We have a page with pull to zoom effect. Zooming is done by setting widget height. The header image is loaded using `cached_network_image`.
When using engine encapsulation under package `io.flutter.view`, everything's normal.
When using  `io.flutter.embedding` the image blinks (quickly changing between `shown` and `hidden` status) while scrolling the page. 

issue on cached_network_image https://github.com/renefloor/flutter_cached_network_image/issues/274

**Comment by janmoppel** [comment]
Hello @pouloghost !

Thank you for posting an issue.
Can you please also provide additional information such as an output of the `flutter doctor -v` command and minimal steps to reproduce this issue (code example)?

**Comment by pouloghost** [comment]
flutter doctor is

**Comment by xster** [comment]
@pouloghost, a more complete reproduction example would be helpful for us to find the root problem. 

cc @matthew-carroll if anything jumps out

**Comment by matthew-carroll** [comment]
@pouloghost it looks like your framework version is about 3 months old. Would you mind trying to reproduce your issue on the master branch with the latest commit?

**Comment by pouloghost** [comment]
> @pouloghost it looks like your framework version is about 3 months old. Would you mind trying to reproduce your issue on the master branch with the latest commit?

We have found a workaround, and we'll upgrade flutter to 1.9.1 by the end of  December, will try to reproduce then.

**Comment by xster** [comment]
Please try again on the newest Android engine from 1.12 where we shipped io.flutter.embedding to stable. Feel free to re-open this issue if the problem is still occurring.
