### ISSUE TITLE
webOnlyScheduleFrameCallback must be initialized first

### ISSUE THREAD

**Issue by michealchow** [flutter/flutter#43167]
I got this error message from my Chrome console when i tried to host the web application from Firebase. However, everything works fine on debug mode.
Step to reproduce:
1. create a flutter project with `flutter create`
2. build a web release application with  `flutter build web`
3. copy the build files into my firebase hosting folder
4. run `firebase deploy`

My Flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel master, v1.10.15-pre.151, on Mac OS X 10.14.6 18G87, locale en-HK)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 10.3)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.5)
> [✓] VS Code (version 1.39.2)
> [✓] Connected device (2 available)
> 
> • No issues found!

**Comment by iapicca** [comment]
Hi @michealchow 
can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by arpit-it** [comment]
I am too getting the same error 
```
s_helper.dart:1340 Uncaught Exception: webOnlyScheduleFrameCallback must be initialized first.
    at Object.d (https://website.firebaseapp.com/main.dart.js:578:3)
    at uI.ds (https://website.firebaseapp.com/main.dart.js:30556:9)
    at Dl.ds (https://website.firebaseapp.com/main.dart.js:21372:7)
    at Dl.th (https://website.firebaseapp.com/main.dart.js:21368:57)
    at Object.eval (eval at Kc (https://scancity-website.firebaseapp.com/main.dart.js:710:8), <anonymous>:1:53)
    at Dl.c9 (https://website.firebaseapp.com/main.dart.js:23282:29)
    at Dl.xk (https://website.firebaseapp.com/main.dart.js:15638:3)
    at https://website.firebaseapp.com/main.dart.js:6494:307
    at Hu.a (https://website.firebaseapp.com/main.dart.js:1356:71)
    at Hu.$2 (https://website.firebaseapp.com/main.dart.js:11964:23)
```

I tried both commands `flutter build web` and `webdev build`

Here is `flutter doctor -v` output
`[✓] Flutter (Channel dev, v1.10.15, on Mac OS X 10.14.6 18G95, locale en-IN)
    • Flutter version 1.10.15 at /Users/development/flutter
    • Framework revision fbabb264e0 (9 days ago), 2019-11-02 01:36:07 +0300
    • Engine revision 8ea19b1c76
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.87
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.` 

My `pubspec.yaml` is:

`
name: flutter_website
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.7.2
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
`

Please suggest if I am doing something wrong from my side or is it a bug.

**Comment by ansarizafar** [comment]
I am getting the same error after upgrading Flutter to latest version on master channel today. Is there any solution?

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by sharathgt** [comment]
I'm having the same issue, if anybody has overcome this issue, please suggest it here...

`[√] Flutter (Channel dev, 1.18.0-10.0.pre, on Microsoft Windows [Version 10.0.17763.1158], locale en-IN)
    • Flutter version 1.18.0-10.0.pre at C:\src\flutter
    • Framework revision 9b7b9d795e (22 hours ago), 2020-05-05 12:09:51 -0700
    • Engine revision 33d2367950
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Program Files (x86)\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.129

• No issues found!
`
