### ISSUE TITLE
[web] platformViewRegistry not defined in dart:ui

### ISSUE THREAD

**Issue by ja2375** [flutter/flutter#43166]
I need to create an `HtmlElementView` to render multiple GIF images on a page so that they get animated (`Image.asset` does not animate GIFs as of now on web).

When i `import dart:ui as ui` and call `ui.platformViewRegistry.registerViewFactory`, Android Studio will always complain. It says "The name 'platformViewRegistry' is being referenced with prefix 'ui' but it isn't defined in any of the libraries imported".

When i try to compile the project, it compiles just fine with no errors, and also the `HtmlElementView` works as well. But Android Studio keeps showing that error even thought it compiled and worked. And this error makes hot restart not work for example, as well as other bugs i noticed.

Here is the code i'm using to create a `GifRenderer` widget:
```
import 'dart:html';
import 'package:flutter/material.dart';
import 'dart:ui' as ui;

class GifRenderer extends StatelessWidget {
  String src;
  int width, height;
  GifRenderer({
    @required this.src,
    this.width,
    this.height,
  });

  @override
  Widget build(BuildContext context) {
    ui.platformViewRegistry.registerViewFactory(     // The error is thrown here
      "Gif Renderer", (int viewId) {
        ImageElement element = ImageElement()
          ..src = '/assets/$src'
          ..style.border = "none";
        if(height != null)
          element.height = height;
        if(width != null)
          element.width = width;
        return element;
      },
    );

    return Container(
      height: double.tryParse(height.toString()),
      width: double.tryParse(width.toString()),
      child: HtmlElementView(
        viewType: "Gif Renderer",
      ),
    );
  }
}
```
This code works fine when i use it to create only 1 `GifRenderer` widget. The problem is that i need to render more than one GIF at a time on the same page (route), and when i create 2 `GifRenderer` widgets, one next to the other in a `Stack`, the second one is rendered over the first one. I mean, they both get created but the first one has the src of the second one and the second has its src set correctly.

- First GifRenderer widget -> Second widget's src
- Second GifRenderer widget -> second widget src

I think this error can be related to AS reporting `platformViewRegistry` not defined, because i have never had this problem before with `StatelessWidget`s. But not sure at all.

**Comment by iapicca** [comment]
Hi @ja2375 
can you please provide your `flutter doctor -v`
and  the error you mentioned

>     ui.platformViewRegistry.registerViewFactory(     // The error is thrown here
>       "Gif Renderer", (int viewId) {

thank you

**Comment by ja2375** [comment]
Sure, here it is:
```
$ flutter doctor -v
[✓] Flutter (Channel master, v1.10.15-pre.186, on Mac OS X 10.14.6 18G103,
    locale es-ES)
    • Flutter version 1.10.15-pre.186 at /Users/ja2375/flutter
    • Framework revision 1c535de7e0 (3 days ago), 2019-10-18 16:40:42 -0700
    • Engine revision 8aefcd8575
    • Dart version 2.6.0 (build 2.6.0-dev.8.0 a61c775db8)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/ja2375/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 77.0.3865.120
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```
And here is a screenshot of the error:
![image](https://user-images.githubusercontent.com/3824182/67201570-dad6c480-f406-11e9-9584-0b3c126ee510.png)

**Comment by iapicca** [comment]
Hi again @ja2375 
I see there's an open issue addressing the case you described.

[platformViewRegistry missing in import dart.ui](https://github.com/flutter/flutter/issues/41563)

Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by ja2375** [comment]
Ok thanks! I will follow that issue.
