### ISSUE TITLE
End of DumpStackTrace

### ISSUE THREAD

**Issue by prczhb** [flutter/flutter#43165]
PS C:\Windows\system32> flutter
Building flutter tool...
Running pub upgrade...
c:\b\s\w\ir\k\src\third_party\dart\runtime\vm\compiler\frontend\kernel_translation_helper.cc: 1938: error: Unexpected tag 80 (AsyncForInStatement) in ?, expected expression
version=2.5.0 (Fri Sep 6 20:10:36 2019 +0200) on "windows_x64"
thread=9968, isolate=vm-service(000001DDCB809F30)
  pc 0x00007ff69140f3fb fp 0x00000034821fc630 Unknown symbol
-- End of DumpStackTrace
Error (-1073740791): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
c:\b\s\w\ir\k\src\third_party\dart\runtime\vm\compiler\frontend\kernel_translation_helper.cc: 1938: error: Unexpected tag 80 (AsyncForInStatement) in ?, expected expression
version=2.5.0 (Fri Sep 6 20:10:36 2019 +0200) on "windows_x64"
thread=7916, isolate=vm-service(000001B459B35ED0)
  pc 0x00007ff69140f3fb fp 0x000000add53fc970 Unknown symbol
-- End of DumpStackTrace
Error (-1073740791): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)

Running the code today, the problem came up for no reason
I don't know what happened

No flutter order can be carried out
No flutter order can be carried out
No flutter order can be carried out
No flutter order can be carried out
No flutter order can be carried out

The only solution may be that I need to remove the flutter completely from the site, And then download it again

**Comment by iapicca** [comment]
Hi @prczhb 
can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by prczhb** [comment]
None of the flutter's instructions will do run,

However, I found the reason, my hard disk is out of order. I checked the hard disk error, fixed it, and now it is ok

Thank you for your help 

But could you be a little smarter about such situations, like suggesting possible problems?

Thanks again for your help 

😭😭😭😭😭😭😭😭😭😭
