### ISSUE TITLE
My flutter app can't run (A problem occurred evaluating project ':app'. > ASCII)

### ISSUE THREAD

**Issue by NeroAlfonso** [flutter/flutter#43177]
Im tried run my flutter app with firebase_auth, google_sign_in, firebase_storage, cloud_firestore but can't execute. Did adjunct the error and pubspec.
My OS is Windows7.

**flutter run -d MYSMARTPHONE --verbose:**
`[  +35 ms] executing: [C:\Users\nerio\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +52 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1c535de7e0714253c3d71ef8af07b1ea27e2e586
[        ] executing: [C:\Users\nerio\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +43 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.10.14-186-g1c535de7e
[  +10 ms] executing: [C:\Users\nerio\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\Users\nerio\flutter\] git ls-remote --get-url origin
[  +19 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +64 ms] executing: [C:\Users\nerio\flutter\] git rev-parse --abbrev-ref HEAD
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +165 ms] executing: C:\Users\nerio\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +15 ms] Exit code 0 from: C:\Users\nerio\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           4689cefa               device product:j2y18lteub model:SM_J250M device:j2y18lte transport_id:16
[  +28 ms] C:\Users\nerio\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4689cefa shell getprop
[ +180 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +49 ms] Found plugin cloud_firestore at C:\Users\nerio\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.9.13+1\
[  +16 ms] Found plugin firebase_auth at C:\Users\nerio\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.9.0\
[   +3 ms] Found plugin firebase_core at C:\Users\nerio\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.3.4\
[   +3 ms] Found plugin firebase_storage at C:\Users\nerio\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-2.1.1+2\
[  +22 ms] Found plugin google_sign_in at C:\Users\nerio\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.0.7\
[ +116 ms] Found plugin cloud_firestore at C:\Users\nerio\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.9.13+1\
[   +9 ms] Found plugin firebase_auth at C:\Users\nerio\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.9.0\
[   +2 ms] Found plugin firebase_core at C:\Users\nerio\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.3.4\
[   +2 ms] Found plugin firebase_storage at C:\Users\nerio\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-2.1.1+2\
[   +7 ms] Found plugin google_sign_in at C:\Users\nerio\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.0.7\
[  +89 ms] Generating
C:\Users\nerio\workspace\curso_de_flutter_avanzado_en_platzi\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +41 ms] ro.hardware = qcom
[  +87 ms] Launching lib\main.dart on SM J250M in debug mode...
[  +19 ms] Initializing gradle...
[   +1 ms] gradle.properties already sets `android.enableR8`
[   +6 ms] Using gradle from C:\Users\nerio\workspace\curso_de_flutter_avanzado_en_platzi\android\gradlew.bat.
[   +9 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +334 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_152-release"
           OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
           OpenJDK 64-Bit Server VM (build 25.152-b06, mixed mode)
[   +5 ms] executing: C:\Users\nerio\workspace\curso_de_flutter_avanzado_en_platzi\android\gradlew.bat -v
[ +616 ms]
           ------------------------------------------------------------
           Gradle 5.6.2
           ------------------------------------------------------------

           Build time:   2019-09-05 16:13:54 UTC
           Revision:     55a5e53d855db8fc7b0e494412fc624051a8e781

           Kotlin:       1.3.41
           Groovy:       2.5.4
           Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
           JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b06)
           OS:           Windows 7 6.1 amd64
[  +10 ms] Initializing gradle... (completed in 1,0s)
[   +1 ms] Resolving dependencies...
[        ] executing: [C:\Users\nerio\workspace\curso_de_flutter_avanzado_en_platzi\android\]
C:\Users\nerio\workspace\curso_de_flutter_avanzado_en_platzi\android\gradlew.bat app:properties
[+1873 ms]
           FAILURE: Build failed with an exception.

           * Where:
           Build file 'C:\Users\nerio\workspace\curso_de_flutter_avanzado_en_platzi\android\app\build.gradle' line: 24

           * What went wrong:
           A problem occurred evaluating project ':app'.
           > ASCII

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
           --scan to get full insights.

           * Get more help at https://help.gradle.org

           BUILD FAILED in 1s
[   +6 ms] Resolving dependencies... (completed in 1,9s)
[   +5 ms] * Error running Gradle:
           ProcessException: Process exited abnormally:

           FAILURE: Build failed with an exception.

           * Where:
           Build file 'C:\Users\nerio\workspace\curso_de_flutter_avanzado_en_platzi\android\app\build.gradle' line: 24

           * What went wrong:
           A problem occurred evaluating project ':app'.
           > ASCII

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
           --scan to get
           full insights.

           * Get more help at https://help.gradle.org

           BUILD FAILED in 1s
             Command: C:\Users\nerio\workspace\curso_de_flutter_avanzado_en_platzi\android\gradlew.bat app:properties

[   +5 ms] "flutter run" took 3.775ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:263:7)
<asynchronous suspension>
#2      GradleUtils.getAppProject (package:flutter_tools/src/android/gradle.dart:55:46)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:143:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:168:23)
<asynchronous suspension>
#5      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:47:32)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:360:56)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:259:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:492:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:557:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#27     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#28     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#29     IosProject.isSwift (package:flutter_tools/src/project.dart)
#30     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#36     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#37     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#41     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#44     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)`

**pubspec.yaml:**
`name: platzi_trips_app
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  generic_bloc_provider: ^1.0.9
  firebase_auth:
  google_sign_in:
  firebase_storage: ^2.1.0
  cloud_firestore: ^0.9.13
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/img/people.jpg
    - assets/img/ann.jpg
    - assets/img/girl.jpg
    - assets/img/mountain.jpeg
    - assets/img/beach.jpeg
    - assets/img/beach_palm.jpeg
    - assets/img/mountain_stars.jpeg
    - assets/img/sunset.jpeg
    - assets/img/river.jpeg

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf`

**Comment by NeroAlfonso** [comment]
Changed my build.gradle classpath
to 'com.google.gms:google-services:4.3.0' to 'com.google.gms:google-services:4.2.0' 
and followed this 
https://github.com/flutter/flutter/issues/35976#issuecomment-526158363
solved.

**Comment by mrkobby** [comment]
I had the problem same. I think if you use the versions of these dependencies it work should.

```
PATH: <project-folder>/android/build.gradle

dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:4.0.1'
    }
```

**Comment by ScholliYT** [comment]
@mrkobby for me also a newer version worked fine:

PATH: <project-folder>/android/build.gradle

```
dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:4.2.0'
}
```
