### ISSUE TITLE
Build gradle

### ISSUE THREAD

**Issue by KanwarpartapSinghBimrah** [flutter/flutter#43175]
Hello Please see the screenshot and let me know how to fix and sort out these issues and how to install if I do follow the wrong path.
![Screenshot (27)](https://user-images.githubusercontent.com/39325207/67208333-f8218800-f432-11e9-99bf-27add9901419.png)

CMD errors

```
C:\Users\Joban>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18362.418], locale en-US)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.5)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by miquelbeltran** [comment]
Hey @KanwarpartapSinghBimrah did you do what the log suggests?

``` 
Android licenses not accepted.  To resolve this, run: flutter doctor --android-license
```

**Comment by KanwarpartapSinghBimrah** [comment]
@miquelbeltran I know but wanna future solution before it.

**Comment by iapicca** [comment]
Hi @KanwarpartapSinghBimrah 
are you still experiencing the issue after accepting Android's licence?
(thank you @miquelbeltran)
If so can you please describe the issue in detail
and provide your updated `flutter doctor -v`
thank you

**Comment by KanwarpartapSinghBimrah** [comment]
Everything is fine but when copy-paste some code from github it provide some errors and Also I got same problem in build.gradle file. See above

**Comment by iapicca** [comment]
Hi again @KanwarpartapSinghBimrah  
does the problem described above persist
after trying the proposed solution?

**Comment by KanwarpartapSinghBimrah** [comment]
@iapicca hi

yes again I got an error which already persists in the screenshot above

**Comment by iapicca** [comment]
Hi again @KanwarpartapSinghBimrah 
can you please provide your  update `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Please refrain 
from posting pictures if not necessary.
Thank you

**Comment by KanwarpartapSinghBimrah** [comment]
Please @iapicca You can see the screenshot. It was clicked by me in sequences. 4 screenshot serial wise


![Screenshot (30)](https://user-images.githubusercontent.com/39325207/67392720-b02f6c00-f5be-11e9-85ef-4ffa96c7119c.png)
![Screenshot (31)](https://user-images.githubusercontent.com/39325207/67392721-b02f6c00-f5be-11e9-8d0e-886ef6138dab.png)
![Screenshot (32)](https://user-images.githubusercontent.com/39325207/67392722-b0c80280-f5be-11e9-81d7-26a41dd8007e.png)
![Screenshot (33)](https://user-images.githubusercontent.com/39325207/67392723-b0c80280-f5be-11e9-8cd2-8ae915ed173c.png)

**Comment by iapicca** [comment]
Hi again @KanwarpartapSinghBimrah 
**please refrain from posting pictures**
could you please post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by KanwarpartapSinghBimrah** [comment]
Please let me know now what I can do

**Comment by iapicca** [comment]
If the issue is the installation itself
I'd recommend a fresh install following our [documentaion](https://flutter.dev/docs/get-started/install).
If with a fresh install the problem still persist would be helpful 
if you could post a self contained app on github.
Thank you

**Comment by KanwarpartapSinghBimrah** [comment]
okay thank I will do that again. If I got an error I will let you know. But I think now should not be.

**Comment by iapicca** [comment]
Hi @KanwarpartapSinghBimrah 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
