### ISSUE TITLE
drawer issue with RTL language 

### ISSUE THREAD

**Issue by CalmAndCoDe** [flutter/flutter#43172]
hello, im developing an app with flutter and it supports for multiple languages and some of them are RTL languages. i already did the localization part but i have some issue with the drawer and endDrawer bcz in RTL languages it should be opened from the Right-to-left and i tried to add an if/else condition on scaffold to add drawer or endDrawer based on language. it works well with LTR languages but when i change the language to RTL it opens just from Left-to-right. even the hot restart didn't worked. and it can only be solved by rebuilding the enire app again and its not a solution.
Thanks.

**Comment by MostafaKhalile** [comment]
I Had a Start Kit [Here](https://github.com/MostafaKhalile/Internationalization-Flutter-app-RTL-languages) Witch Could Help

**Comment by HansMuller** [comment]
The drawer should automatically open on the right for RTL locales. You can see this in the "Navigation drawer" examples/flutter_gallery demo if you configure the app with "Force RTL".

If this isn't working for you please provide the output of `flutter doctor` and a small self-contained app that demonstrates the problem. Note also: https://gist.github.com/ is a useful way to share the code.

**Comment by CalmAndCoDe** [comment]
@HansMuller thanks for your response i realized that i did a mistake in code, i had set the endDrawer manually for RTL langauges and its normally will open from left-to-right on RTL languages.
and there wasn't any issue with framework itself.
Thanks.

**Comment by CalmAndCoDe** [comment]
@MostafaKhalile thanks for commenting but i solved.

**Comment by MostafaKhalile** [comment]
@CalmAndCoDe  Never Mind Bro You are Welcome

**Comment by fly-qp** [comment]
> @MostafaKhalile thanks for commenting but i solved it.

How did you solve it?
