### ISSUE TITLE
Missing documentation for pubspec.yaml "builders" / `flutter generate`

### ISSUE THREAD

**Issue by cubuspl42** [flutter/flutter#43176]
Flutter, on the stable channel, supports a "builders" key in the `pubspec.yaml` file which is an alternative to declaring a `build_runner` dependency manually. It also ships with a command that autogenerates all the necessary files: `flutter generate`.

I learnt about this here: https://github.com/rrousselGit/functional_widget/blob/master/README.md

I couldn't find any documentation on these features. Are they actually supported and stable?

**Comment by jmagman** [comment]
\cc @jonahwilliams

**Comment by samandmoore** [comment]
There's a wiki page here: https://github.com/flutter/flutter/wiki/Code-generation-in-Flutter#generating-code-on-hot-reload

but it's not really robust and it just barely covers things enough for someone to guess at how to do things correctly.

**Comment by radeksvarz** [comment]
The wiki page describes the way to write own builders, but following https://github.com/flutter/flutter/wiki/Code-generation-in-Flutter#writing-your-own-builders , i.e. creating file build.yaml and builders.dart within the app, the custom builder is not run.

 Flutter (Channel master, 1.19.0-2.0.pre.73, on Microsoft Windows [Version 10.0.18362.836]

**Comment by jonahwilliams** [comment]
Obsolete by #61508, was some more context on the removal of flutter generate. Specifically, I recommend using pub run build_runner instead, as this will have the best workflow going forward.
