### ISSUE TITLE
Report reasons for flutter driver test failure in test log

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43185]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=37575. Conversation should occur there.

cc @iskakaushik, @zanderso as it seems to be tooling related.

**Comment by zanderso** [comment]
This sounds like an artifact of Fuchsia choosing to run the Flutter driver on the device alongside the app under test. The solution here is to run the driver on the host instead. I will close this as not being actionable, but feel free to re-open the issue if I am mistaken. Thanks!
