### ISSUE TITLE
Webview incorrectly sized on some hardware.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43182]
Internal: b/143426936

Mirror issue for https://b.corp.google.com/issues/142699417. cc @chinmaygarde, to whom the issue is assigned at Google.

**Comment by chinmaygarde** [comment]
This issue was patched in https://github.com/flutter/engine/pull/13193. A roll past https://github.com/flutter/engine/commit/c92613bc491ed902c686e307221958d200ac747b need to happen before cvarvara@ can verify.

**Comment by kf6gpe** [comment]
This is waiting for a roll. Meanwhile, the customer has escalated this to a P0, so I'm adjusting the severity here accordingly.

**Comment by mehmetf** [comment]
We should close this if it is fixed in the repo. Let's not keep issues open pending on rolls (That's what internal buganizer bugs are for).
