### ISSUE TITLE
Flutter content doesn't repaint automatically when a webview is on the screen

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43181]
Internal: b/143427193

Mirror issue for https://b.corp.google.com/issues/142778720. Conversation should occur there.

**Comment by kf6gpe** [comment]
cc @amirh, to whom the Googler tracking issue is assigned.

**Comment by kf6gpe** [comment]
Google issue assigned this to @chinmaygarde ; keeping both he and @amirh on the issue here

**Comment by chinmaygarde** [comment]
@kf6gpe I am not ready to work on this yet as I have to figure out b/143529469 first.

**Comment by kf6gpe** [comment]
Sounds good! Thanks for the update. Removing you from the assignees.

**Comment by chinmaygarde** [comment]
Thanks. I'll let you know when I am pick this back up. I see I am still assigned on the internal issue. What's the playbook on sync-ing assignees?

**Comment by mklim** [comment]
This appears to be fixed.
