### ISSUE TITLE
Flutter AOT builds crashing on some Fuchsia hardware

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43184]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=39188. Conversation should occur there. cc @cbracken, to whom the Fuchsia issue is assigned. Also cc @iskakaushik

**Comment by iskakaushik** [comment]
removing the critical label as this doesn't block any customer workflows.

**Comment by timsneath** [comment]
Touching issue for triage purposes

**Comment by kf6gpe** [comment]
Closed upstream issue.
