### ISSUE TITLE
[web]: Flutter URL opens incorrectly in VS Code.

### ISSUE THREAD

**Issue by davidcavazos** [flutter/flutter#43199]
When I run *any* application, it shows the following message that Flutter for web is experimental as expected.

```
Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web.
```

When I do a `[Cmd+click]` on the URL in the VS Code terminal to open it, it parses the URL as [https://flutter.dev/web.](https://flutter.dev/web.) (note the dot `.` at the end, instead of the correct [https://flutter.dev/web](https://flutter.dev/web) without the dot), which shows a 404 page not found. In other terminals such as iTerm2, this is not an issue.

VS Code terminal:
![image](https://user-images.githubusercontent.com/2309379/67236420-1a4ce300-f3fe-11e9-9f77-9b01199c786e.png)

iTerm2:
![image](https://user-images.githubusercontent.com/2309379/67236581-613ad880-f3fe-11e9-9d67-b7ef050ce157.png)

Other terminals might also have this issue when parsing URLs, so it might be worthwhile either dropping the dot `.` at the end, or redirecting to the correct page.

<details><summary><code>flutter doctor -v</code></summary><p><code><pre>
[✓] Flutter (Channel master, v1.10.15-pre.188, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.10.15-pre.188 at /Users/dcavazos/local/flutter
    • Framework revision 584ee10c68 (4 hours ago), 2019-10-21 07:49:28 -0700
    • Engine revision 8aefcd8575
    • Dart version 2.6.0 (build 2.6.0-dev.8.0 a61c775db8)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dcavazos/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Flutter requires a minimum Xcode version of 10.2.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.8.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6262.58

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 77.0.3865.120
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
</pre></code></p></details>

**Comment by jonahwilliams** [comment]
We should probably just print the URL without a period.
