### ISSUE TITLE
ShellTest.ReportTimingsIsCalled is flaky.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#43192]
Sample failing run https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8898964393069106672/+/steps/Host_Tests_for_host_debug_unopt/0/stdout

**Comment by chinmaygarde** [comment]
cc @liyuqian

**Comment by liyuqian** [comment]
I can't reproduce any failure locally:
```
Repeating all tests (iteration 775) . . .

Note: Google Test filter = ShellTest.ReportTimingsIsCalled
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ShellTest
[ RUN      ] ShellTest.ReportTimingsIsCalled

```

Maybe the `run_test.py` is swallowing some other error messages?

**Comment by chinmaygarde** [comment]
More failed runs. These were successive so the flakiness is pretty consistent. @liyuqian This also happens on a Mac, were you trying to reproduce on a Mac workstation?

* https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine/2765
* https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine/2766
* https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine/2768

**Comment by liyuqian** [comment]
I reproduced the segmentation fault on Mac. It first started to happen after commit https://github.com/flutter/engine/commit/8b9761940b

@gw280 : can you please try run the test locally before and after your commit on a Mac to double check that my observation is correct? The segmentation fault can be easily reproduced by
1. Run `./out/host_debug_unopt/shell_unittests --gtest_filter='ShellTest.ReportTimingsIsCalled' --gtest_repeat=-1` on a Mac command line terminal
2. Scroll the terminal up and down while the test is running and printing out logs.

If it's confirmed, we can meet to figure out what's happening there.

**Comment by goderbauer** [comment]
This test is still disabled: https://github.com/flutter/engine/blob/d03582d183b1e4ab7fb82607366471f46a97f2e0/shell/common/shell_unittests.cc#L363

Any updates?

**Comment by chinmaygarde** [comment]
None. This work is blocked behind customer:dream P0s.

**Comment by dnfield** [comment]
I'm fairly confident this has the same problem as https://github.com/flutter/flutter/issues/81580 - the report timings callback sometimes gets called a second time, over-writing the initial vector of timings that we capture, causing a failure.  I'm going to re-enable it with the same PR that fixes that bug.
