### ISSUE TITLE
Redesign snackbar API to not use routes

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#432]
I think snack bars should be a feature of a Scaffold. They probably shouldn't use routes at all.

According to the specs -- https://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-specs -- they should not time out while another route (e.g. a dialog) is over them, they should reset their timeout when their parent route resumes being the current route, they should be displayed consecutively in time, etc.

**Comment by HansMuller** [comment]
This sounds correct to me. Perhaps non-modal bottom sheets should also just be a scaffold feature?

**Comment by Hixie** [comment]
Well, they need a StateRoute so that they can react to the back button (I don't think snack bars should react to the back button). But beyond that, maybe.
