### ISSUE TITLE
Reset KVMs/Make keyboard work - post devicelab migration

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#43209]
For this one, @godofredoc could you please specify instructions?

**Comment by godofredoc** [comment]
You'll need to follow these steps:

1.- This requires to create labels for all the kvm cables and unplug them from the kvm
2.- After everything is disconnected we need to plug the power cable and turn the kvm on.
3.- Connect the keyboard and mouse
4.- Connect the first kvm cable, click the kvm button to activate the current machine.
5.- Validate it works and continue with the process.

**Comment by keyonghan** [comment]
Thanks for the detailed info. Will try in a later time.

**Comment by godofredoc** [comment]
There are two root causes for this issue:

1. A usb3 - usb2 compatibility issue with the kvm.
2. New macs do not support analog output on the hdmi

1.- can be solved by connecting a usb 2 extension cable between the machine and kvm.
2.- We need to replace the second kvm with an hdmi one.

Order everything and should be here by 10/25 ready to get it installed

**Comment by godofredoc** [comment]
We replaced one bottom row, we still need to re-wire three more rows

**Comment by godofredoc** [comment]
This is complete.
