### ISSUE TITLE
[Chip] Splash on chip with delete icon is not clipped

### ISSUE THREAD

**Issue by perclasson** [flutter/flutter#43215]
The splash on chips with delete icon should be clipped to the shape of the ship. Right now it is outside of the chip, see screenshot:
![Simulator Screen Shot - iPhone 11 Pro - 2019-10-21 at 14 22 23](https://user-images.githubusercontent.com/1770678/67244496-ab2bba80-f40e-11e9-8ebb-3824799c7a97.png)

Steps to reproduce
-------------------
1. Go to flutter_gallery under Chips and delete a chip 
2. The icon ripple is not clipped to the shape of the chip

**Comment by TahaTesser** [comment]
Hi @perclasson 
There doesn't seem to be any splash with delete icon 
Do you think this issue is still valid?
Thank you

**Comment by perclasson** [comment]
Yes, it looks like this issue is fixed on master. I'll close it.
