### ISSUE TITLE
Text selection highlight doesn't reach the top of the text on iOS

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4321]
On an iPhone 6S.

![dc50310b-b5d0-48a7-92de-88d60e5f3c6d](https://cloud.githubusercontent.com/assets/5479/15751510/39bd50a4-289f-11e6-8257-fe1bae8cf457.PNG)

**Comment by sethladd** [comment]
cc @mpcomplete

**Comment by abarth** [comment]
We're supposed to replace the height with a constant multiple of the font size called the "selection height".  If you look in the C++ code, you can see how this is supposed to work.

**Comment by sethladd** [comment]
We look pretty good here!

![screen shot 2016-06-08 at 1 23 48 pm](https://cloud.githubusercontent.com/assets/5479/15909682/41e03a26-2d7c-11e6-81d0-f857e5feaf70.png)

I think we can close. :)
