### ISSUE TITLE
D/libGLESv2(17044): STS_GLApi : DTS, ODTC are not allowed for Package : com.ktz.places_app

### ISSUE THREAD

**Issue by kothanzaw** [flutter/flutter#43232]
When i try to debug on my Samsung J7 Prime (new phone) 
I face with this error..

<details>
  <summary>ERROR</summary>
  
Launching lib\main.dart on SM G610F in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device SM G610F...
D/libGLESv2(17044): STS_GLApi : DTS, ODTC are not allowed for Package : com.ktz.places_app

</details>

<details>
  <summary>flutter doctor -v</summary>

Microsoft Windows [Version 10.0.17763.805]
(c) 2018 Microsoft Corporation. All rights reserved.

D:\Projects\Flutter\places_app>flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.17763.805], locale en-US)
    • Flutter version 1.9.1+hotfix.5 at C:\flutter
    • Framework revision 1aedbb1835 (4 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • SM G610F • 5200e5a3c099451b • android-arm • Android 8.1.0 (API 27)

• No issues found!

</details>

**Comment by iapicca** [comment]
Hi @kothanzaw 
on what OS are you debugging?
(linux issue](https://github.com/flutter/flutter/issues/27359))
([Samsung J7 issue](https://github.com/flutter/flutter/issues/35322))

**Comment by kothanzaw** [comment]
window 10

**Comment by aryalg** [comment]
Location is turned off on your phone! Turn on location. Worked for me.

**Comment by iapicca** [comment]
Hi @kothanzaw 
are you experiencing the issue with the latest stable version of flutter?
If so could you please provide your `flutter build --verbose`
thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
