### ISSUE TITLE
flutter doctor error

### ISSUE THREAD

**Issue by wangshiyang** [flutter/flutter#43237]
![image](https://user-images.githubusercontent.com/1273242/67258844-20f25d80-f4c5-11e9-9619-2c9d8858a41a.png)
![image](https://user-images.githubusercontent.com/1273242/67258851-2bacf280-f4c5-11e9-8f49-862f9d03b7c7.png)

**Comment by iapicca** [comment]
Hi @wangshiyang 
can you please describe the issue in detail,
your `flutter doctor -v` looks fine.
Please refrain 
from posting pictures if not necessary.
thank you

**Comment by wangshiyang** [comment]
> Hi @wangshiyang
> can you please describe the issue in detail,
> your `flutter doctor -v` looks fine.
> Please refrain
> from posting pictures if not necessary.
> thank you
![image](https://user-images.githubusercontent.com/1273242/67552651-0ecf2400-f73e-11e9-8d68-064cdf0529c5.png)

**Comment by iapicca** [comment]
Hi again @wangshiyang 
once again, you flutter doctor doesn't show any problem;
could you please describe in dept the issue you are experiencing?
Please DO NOT pictures if not necessary.
Thank you

**Comment by janmoppel** [comment]
Hello @wangshiyang !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
