### ISSUE TITLE
i can't migrate to androidX

### ISSUE THREAD

**Issue by CristhianFonseca** [flutter/flutter#43234]
## I tried with several methods to migrate my application to AndroidX and I can't do it.
My application stops after trying it.

I try Android Studio and Vscode, following the documentation, and I can't solve this.

**Comment by luffynas** [comment]
Hi @CristhianFonseca please show your error

**Comment by iapicca** [comment]
Hi @CristhianFonseca 
can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by CristhianFonseca** [comment]
![image](https://user-images.githubusercontent.com/33918486/67308639-0e295a00-f4c0-11e9-9373-56d47f3ebb2d.png)

**Comment by CristhianFonseca** [comment]
@luffynas no error comes out, only the application stops

**Comment by CristhianFonseca** [comment]
> Hi @CristhianFonseca please show your error

no error comes out, only the application stops

**Comment by CristhianFonseca** [comment]
I give up this error. I will create a new project from the console

**Comment by CristhianFonseca** [comment]
> Hi @CristhianFonseca
> can you please provide your `flutter doctor -v`?
> Also, to better address the issue, would be helpful
> if you could post a self contained app on github
> or the steps to reproduce it.
> Thank you

https://github.com/CristhianFonseca/errorAndroidXFlutter

**Comment by luffynas** [comment]
add several line in your **gradle.properties**
```
android.enableJetifier=true
android.useAndroidX=true
```

**Comment by iapicca** [comment]
Hi again @CristhianFonseca 
does the proposed [solution ](https://github.com/flutter/flutter/issues/43234#issuecomment-545331706)fix the issue?
(thank you @luffynas )
Please refrain 
from posting pictures if not necessary.
Thank you

**Comment by CristhianFonseca** [comment]
Hi @iapicca 
no, I had to create a new project from console with tag --androidx

**Comment by BondarenkoStas** [comment]
@CristhianFonseca I tried your app https://github.com/CristhianFonseca/errorAndroidXFlutter, after adding 
```
android.enableJetifier=true
android.useAndroidX=true
```
it works just fine. What the issue did you have or have now?

**Comment by CristhianFonseca** [comment]
> @CristhianFonseca I tried your app https://github.com/CristhianFonseca/errorAndroidXFlutter, after adding
> 
> ```
> android.enableJetifier=true
> android.useAndroidX=true
> ```
> 
> it works just fine. What the issue did you have or have now?

I also know this, but it didn't help me
