### ISSUE TITLE
How to play a global dialog?

### ISSUE THREAD

**Issue by Tumbler0809** [flutter/flutter#43233]
I am sending a network request in initState(). I need to pop up the window after the network request is completed, but there is no Context.

**Comment by Tumbler0809** [comment]
Upgraded popup

**Comment by jp1017** [comment]
```
WidgetsBinding.instance.addPostFrameCallback((call){
                                      //请求数据，此处会有context
                                    });
```

**Comment by BondarenkoStas** [comment]
Thank you @jp1017 !
@Tumbler0809 This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
