### ISSUE TITLE
Could not get unknown property 'android' for project ':video_player' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by sunqihui222** [flutter/flutter#43247]
## Steps to Reproduce

When running the latest source code, an error appears as follows:
```
* Error running Gradle:
ProcessException: Process "D:\flutter_gitProject\image_picker\example\android\gradlew.bat" exited abnormally:

> Configure project :app
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
         *********************************************************
WARNING: This version of image_picker will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************


FAILURE: Build failed with an exception.

* Where:
Script 'E:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 653

* What went wrong:
A problem occurred configuring project ':video_player'.
> Could not get unknown property 'android' for project ':video_player' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: D:\flutter_gitProject\image_picker\example\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.
```

```
```

```
```

**Comment by janmoppel** [comment]
Hello @sunqihui222 !

Thank you for posting an issue.
Your problem seems like the one discussed here: #24389. Can you please check, whether proposed solution there works for you?

**Comment by sunqihui222** [comment]
this my pubspec.lock Data:  
video_player:
    dependency: "direct main"
    description:
      name: video_player
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.10.1+5"
but,now 

How can I find that file and delete it

**Comment by blasten** [comment]
Which version of the Flutter tool are you using?  
Please paste the content of `flutter doctor` and the content of `pubspec.yaml`

**Comment by sunqihui222** [comment]
Thank you. The problem has been solved

**Comment by sidkhore1002** [comment]
what  is the solution ?

**Comment by dpkswn4** [comment]
**How I solved my Problem by following below method:**

remove the problem making package from 
`/.pub-cache/hosted/pub.dartlang.org`

Run `flutter pub get`

reatart your IDE

**Comment by apm-dev** [comment]
I had this problem with :path_provider & aapt2-proto and fix it in this way:

in ***project-folder/gradle/wrapper/gradle-wrapper.properties***

change this:

    distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip
to this:

    distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip

and then in ***project-folder/buil.gradle***

change this:

    classpath 'com.android.tools.build:gradle:3.5.0'

to this:

    classpath 'com.android.tools.build:gradle:4.1.1'
and then run this command

    flutter clean
build or run your project, good luck.

**Comment by larry-noriega** [comment]
1. main.dart remove unused imports or just comment as:
`//import 'dart:typed_data';`
2. app/build.gradle replace old symbols as new versions one like this:

**Comment by sunqihui222** [comment]
1、clean the "Cache\hosted\pub.flutter-io.cn" data;
2、video_player：x.x.x
3、pub get
