### ISSUE TITLE
libflutter.so not found in APK for armeabi-v7a

### ISSUE THREAD

**Issue by sujithTSR** [flutter/flutter#43248]
I've tried adding a flutter project to an existing android project. I have followed the steps as described [here](https://medium.com/flutter-community/flutter-lifecycle-for-android-and-ios-developers-8f532307e0c7).

Issue: 
  It was successfully integrated. The problem is, the generated armeabi-v7a APK doesn't have a libflutter.so file. 
Tried with Flutter version 1.5.4 and 1.9.1 
The problem persists. 

Similar Problem: [StackOverflow](https://stackoverflow.com/questions/58499210/adding-flutter-to-existing-apps-libflutter-so-missing-in-the-apk-for-armeabi-v)
**Target Platform:** Android 

`flutter analyze`
No issues found! (ran in 2.1s)

`flutter doctor -v`
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.5 18F203, locale en-IN)
    • Flutter version 1.9.1+hotfix.4 at /Users/sujith_tsr/flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sujith_tsr/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8580
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @sujithTSR 
I'm rounding up yours and other, very recent similar issues
to [this one](https://github.com/flutter/flutter/issues/43252),
please follow up there.
Thank you
