### ISSUE TITLE
VMServiceObjectLoadError

### ISSUE THREAD

**Issue by YuzuWang** [flutter/flutter#43253]
Launching lib/main.dart on iPhone 5s in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           12.7s
Error connecting to the service protocol: Instance of 'VMServiceObjectLoadError'

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.6 18G87, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)
```

**Comment by BondarenkoStas** [comment]
@YuzuWang Does it work in this way with ony project or with the particular one?
Can you please provide the log while running it with --verbose flag?

**Comment by YuzuWang** [comment]
Sorry, I forgot to reply. I reinstalled flutter, now there is no problem.

**Comment by alisidhu** [comment]
@c0h1b4 have your issue fixed? kindly let me know how to do it?

**Comment by c0h1b4** [comment]
I don't have this issue.
