### ISSUE TITLE
Flutter unable to resolve androidx reference

### ISSUE THREAD

**Issue by Silfalion** [flutter/flutter#43250]
Fiddling with the platform specific part on flutter. At some point I needed the JobIntentService library. Problem is the project refuses to resolve the android.core import.

Neither androidx nor the library support libraries work, I tried:

-Updating both gradle(plugin included) and kotlin
-Updating flutter
-Uninstall and reinstall android studio
-Modify the build.gradle file, was carefully to do it with the app one not the project’s
-Opened the project with “Edit in android studio” function, everything resolved but the moment I go back to the flutter project, the same error remains
-Deleting .idea/
-Flutter clean
-Migrating to Androidx
-Create the project with flutter commands
-Change SDK versions

Tried everything and still the same problem.
When I do alt-enter on the heritage class and choose import the support library, it tells me that gradle failed to sync

**Comment by Silfalion** [comment]
One solution I found is to add each library manually into the Android module from the project structure menu, but this is a very inelegant solution.

Any idea on how to make it do that automatically again?

**Comment by Silfalion** [comment]
Tried it on another PC and still the same

**Comment by iapicca** [comment]
Hi @Silfalion  
are you still experiencing the issue with the latest stable or above?
Thank you

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
