### ISSUE TITLE
webview not working in flutter web

### ISSUE THREAD

**Issue by devndra** [flutter/flutter#43255]
I am using a web view for showing HTML files but webview not working. Please provide me solutions.

**Comment by BondarenkoStas** [comment]
@devndra please provide more details: flutter doctor -v output, which webview_flutter version you use. What do you mean by not working, are there any errors/warnings/crashes?

**Comment by muhleder** [comment]
webview_flutter doesn't have web platform support yet, but you can use HtmlElementView on the web platform. Some examples of usage in the PR https://github.com/flutter/flutter/pull/37819

**Comment by BondarenkoStas** [comment]
Thank you @muhleder !
