### ISSUE TITLE
can't resolve 'dart:ui' not found exception

### ISSUE THREAD

**Issue by Nandhini-Ravichandran** [flutter/flutter#43258]
In flutter driver testing can't use material.dart, ui.dart, rendering.dart, flutter_test.dart packages.

When using these packages throws below exception
```
Installing build\app\outputs\apk\app.apk...                         3.4s
I/flutter ( 8340): Observatory listening on http://127.0.0.1:40434/61QAXdFDAmQ=/
/D:/flutter/flutter/packages/flutter_test/lib/src/accessibility.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
/D:/flutter/flutter/packages/flutter_test/lib/src/binding.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
/D:/flutter/flutter/packages/flutter_test/lib/src/matchers.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
/D:/flutter/flutter/packages/flutter_test/lib/src/matchers.dart:9:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
/D:/flutter/flutter/packages/flutter_test/lib/src/test_pointer.dart:12:1: Error: Not found: 'dart:ui'
export 'dart:ui' show Offset;
^
/D:/flutter/flutter/packages/flutter_test/lib/src/window.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' hide window;
       ^
/D:/flutter/flutter/packages/flutter/lib/src/rendering/box.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show lerpDouble;
       ^
/D:/flutter/flutter/packages/flutter/lib/src/rendering/debug_overflow_indicator.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
/D:/flutter/flutter/packages/flutter/lib/src/rendering/editable.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show TextBox, lerpDouble;
       ^
/D:/flutter/flutter/packages/flutter/lib/src/rendering/error.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show Paragraph, ParagraphBuilder, ParagraphConstraints, ParagraphStyle, TextStyle
```

**Comment by Nandhini-Ravichandran** [comment]
Installing build\app\outputs\apk\app.apk...                         3.4s
I/flutter ( 8340): Observatory listening on http://127.0.0.1:40434/61QAXdFDAmQ=/
/D:/flutter/flutter/packages/flutter_test/lib/src/accessibility.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
/D:/flutter/flutter/packages/flutter_test/lib/src/binding.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
/D:/flutter/flutter/packages/flutter_test/lib/src/matchers.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
/D:/flutter/flutter/packages/flutter_test/lib/src/matchers.dart:9:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
/D:/flutter/flutter/packages/flutter_test/lib/src/test_pointer.dart:12:1: Error: Not found: 'dart:ui'
export 'dart:ui' show Offset;
^
/D:/flutter/flutter/packages/flutter_test/lib/src/window.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' hide window;
       ^
/D:/flutter/flutter/packages/flutter/lib/src/rendering/box.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show lerpDouble;
       ^
/D:/flutter/flutter/packages/flutter/lib/src/rendering/debug_overflow_indicator.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
/D:/flutter/flutter/packages/flutter/lib/src/rendering/editable.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show TextBox, lerpDouble;
       ^
/D:/flutter/flutter/packages/flutter/lib/src/rendering/error.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show Paragraph, ParagraphBuilder, ParagraphConstraints, ParagraphStyle, TextStyle;

**Comment by BondarenkoStas** [comment]
@Nandhini-Ravichandran You cannot run code that depends on dart:ui even transitively, such as Flutter, on the standalone dart VM.
Please check #27826.

**Comment by Nandhini-Ravichandran** [comment]
@BondarenkoStas  my code need material.dart package, any other way use material.dart package inside a flutter_driver test file?

**Comment by BondarenkoStas** [comment]
I don't know, maybe you can try to modify it do don't use anything that uses dart:ui. But better would be to not use material.dart there.
