### ISSUE TITLE
Provide a "flutter shutdown" command to shut down resident deamons

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#4325]
Which would kill any pending/daemon Flutter-related processes, including:
- All `flutter` commands
- `adb` server
- `adb`-equivalent for iOS (dunno what that is)
- All simulators/emulators
- things that I'm forgetting

This would be useful in test environments and for resetting your dev environment when things just go out of sync.

/cc @devoncarew

**Comment by tvolkert** [comment]
`flutter shutdown`?  "cleanup" could be confused with cleaning build artifacts.

**Comment by yjbanov** [comment]
Good point. Perhaps such command should also clean up build artifacts?

**Comment by Hixie** [comment]
We have `flutter build clean` for the build artifacts.

**Comment by yjbanov** [comment]
Judging by lack of reactions, there's not enough interest from users.
