### ISSUE TITLE
ios-deploy: Unable to locate DeviceSupport directory

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4326]
## Steps to Reproduce

I was attempting to `flutter run` with xcode 7.2.something and I would see

```
Starting debug of iPhone 5s (GSM) 'drewwarren’s iPhone' (4127c6ffa53f153512916da5fe2a3afac8d23798) connected through USB...
2016-06-02 11:17:59.787 ios-deploy[4022:2958268] [ !! ] Unable to locate DeviceSupport directory. This probably means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!
Could not install ios/.generated/build/Release-iphoneos/Runner.app on 4127c6ffa53f153512916da5fe2a3afac8d23798.
Error running application on drewwarren’s iPhone.
```

This says I might not have Xcode installed, but I did. `flutter doctor` made everything look okay for Xcode.

When I was in this state if I attempted to open `FlutterApplication.xcodeproj` in Xcode and click the play button I would see `Could not find Developer Disk Image`.

**Comment by smrtsmrf** [comment]
I get the same issue, but I'm using the latest version of XCode. When I try to run it in XCode, I get a white screen on my device and this in XCode.
<img width="1512" alt="screen shot 2017-06-09 at 4 35 29 pm" src="https://user-images.githubusercontent.com/17756776/26997287-90de69f2-4d35-11e7-9c27-512be8a3cb34.png">

**Comment by cbracken** [comment]
@smrtsmrf can you check whether you're using Xcode 8.3.3? If so, it appears Xcode has changed the format it uses for the iOS `DeviceSupport` directory which is causing `ios-deploy` (one of our dependencies for launching iOS apps on devices) to get confused.

Upstream `ios-deploy` issue is: phonegap/ios-deploy#292

We can see what's in the iOS device support dir via:
```
ls "$(xcrun --sdk iphoneos --show-sdk-platform-path)/DeviceSupport"
```
With Xcode 8.3.3, I see:
```
drwxrwxr-x   4 cbracken  eng  136  2 Feb 07:27 10.0/
drwxrwxr-x   4 cbracken  eng  136  2 Feb 07:29 10.1/
drwxrwxr-x   4 cbracken  eng  136  2 Feb 07:26 10.2/
drwxrwxr-x   4 cbracken  eng  136 26 Apr 19:26 10.3.1 (14E8301)/
drwxrwxr-x   4 cbracken  eng  136  2 Feb 07:26 8.0/
drwxrwxr-x   4 cbracken  eng  136  2 Feb 07:28 8.1/
drwxrwxr-x   4 cbracken  eng  136 10 May 22:21 8.2/
drwxrwxr-x   4 cbracken  eng  136  2 Feb 07:27 8.3/
drwxrwxr-x   4 cbracken  eng  136  2 Feb 07:28 8.4/
drwxrwxr-x   4 cbracken  eng  136  2 Feb 07:27 9.0/
drwxrwxr-x   4 cbracken  eng  136  2 Feb 07:26 9.1/
drwxrwxr-x   4 cbracken  eng  136  2 Feb 07:28 9.2/
drwxrwxr-x   4 cbracken  eng  136  2 Feb 07:28 9.3/
```

Looks like a quick hacky fix is:
```
cd "$(xcrun --sdk iphoneos --show-sdk-platform-path)/DeviceSupport"
ln -s 10.3.1\ \(14E8301\) 10.3
```
If you installed Xcode via the App Store (in which case, these files will all be owned by root), you may get a permission denied error and may need to run `ln` as root:
```
sudo ln -s 10.3.1\ \(14E8301\) 10.3
```

**Comment by smrtsmrf** [comment]
@cbracken thanks, that did the trick. 👍

**Comment by cbracken** [comment]
Thanks for confirming! Will keep this issue open for reference until a fix goes into ios-deploy.

**Comment by davorpeic** [comment]
Thanks @cbracken your solution fixed my 10.3.3 even I added particular subversion. There is more talk about this on ios-deploy repo https://github.com/phonegap/ios-deploy/issues/292

dp

**Comment by sethladd** [comment]
We might want to bump up the priority of this fix. The workaround has 12 thumbs up, and the workaround is still required. Maybe our tool can just make the symlink? Or, print out a link to this bug?

**Comment by cbracken** [comment]
@sethladd We can't autogen the symlink since it requires root privileges but we can definitely output the one-line command to do it. I'll land a doctor check (and run it at build time as well) that outputs this.

**Comment by cbracken** [comment]
ios-deploy 1.9.2 was released today and includes a fix for this issue. I've added a doctor check to bump to that version.

**Comment by blackdynamo** [comment]
I am still having this issue in 1.9.2 with Xcode 9.0.1.

I have also tried using the solution to add the symlinks but doesn't seem to work for me.

```
------ Debug phase ------
Starting debug of 38813d6fae7464bb3f099582ea78ce53955e8632 (N66mAP, iPhone 6s Plus, iphoneos, arm64) a.k.a. 'iPhone' connected through USB...
[  0%] Looking up developer disk image
[ 95%] Developer disk image mounted successfully
2017-10-30 16:25:46.621 ios-deploy[44705:5930783] [ !! ] Unable to locate DeviceSupport directory with suffix 'Symbols'. This probably means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!```

**Comment by blackdynamo** [comment]
Just as a follow up, if you are having this issue, the files are probably missing from this path:

```
~/Library/Developer/Xcode/iOS\ DeviceSupport/
```

If that is the case, which fixed things for me, make sure your phone is attached to your mac and open xcode. The files will automatically appear and things should work.

**Comment by sam-parks** [comment]
I'm using XCode 11.3.1 and I'm still getting this issue. I checked this path: 

~~~
/Library/Developer/Xcode/iOS\ DeviceSupport/
~~~

But the files were there. What else could be causing this issue?

**Comment by nwainwri** [comment]
> I'm using XCode 11.3.1 and I'm still getting this issue. I checked this path:
> 
> ```
> /Library/Developer/Xcode/iOS\ DeviceSupport/
> ```
> 
> But the files were there. What else could be causing this issue?

Same XCode, also having the same issue. Files are also there.

How does one fix this issue?

**Comment by vHanda** [comment]
I 

> > I'm using XCode 11.3.1 and I'm still getting this issue. I checked this path:
> > ```
> > /Library/Developer/Xcode/iOS\ DeviceSupport/
> > ```
> > 
> > 
> > But the files were there. What else could be causing this issue?
> 
> Same XCode, also having the same issue. Files are also there.
> 
> How does one fix this issue?

I encountered the same issue and managed to fix it by updating to the latest version of ios-deploy - https://github.com/ios-control/ios-deploy
