### ISSUE TITLE
Crash report sent (report ID: 2a2e1c25f0135048), Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by Kerimkullov** [flutter/flutter#43260]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by BondarenkoStas** [comment]
@Kerimkullov Unfortunately, this report does not have any actionable information.
Please feel free to comment and I will re-open if you can add the following information:
The version of Flutter you’re using
The output of flutter doctor -v
The full exception you see
A minimal reproduction that leads to this exception.

**Comment by liu12151407** [comment]
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17134.1069], locale zh-CN)
    • Flutter version 1.9.1+hotfix.6 at D:\Flutter\sdk\flutter
    • Framework revision 68587a0916 (6 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: D:\Android\AS\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Android\AS
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] Connected device
    ! No devices available

**Comment by BondarenkoStas** [comment]
@liu12151407 what is the issue that you have? It will be better if you file in as a new one, because the current one gives no information.
