### ISSUE TITLE
Flutter run picks wrong xcode schema when used with different build flavors

### ISSUE THREAD

**Issue by fl0cke** [flutter/flutter#43272]
## Steps to Reproduce

I have a project with two app flavors/schemes (`full `and `demo`) that apply different bundle identifiers and signing configurations. Everything is setup correctly as far as i can tell with my XCode builds working flawlessly. However, the flutter tool seems to pick the wrong schema/build configuration for some steps of the build process, regardless of the flavor that i specify. This results in the following problems:

- It uses the same signing configuration for both flavors, even though should be different.
- It assumes the wrong bundle identifier, which leads to a connection failure of the observatory with the following message:.

> Failed to establish a debug connection with 750209f8c8db628f995925c4efb785b15d0027e2 using mdns: Exception: Did not find a observatory port advertised for com.example.app.demo.

I noticed that the configuration that is picked up by flutter is the one that is set as the default one 
for command line builds in XCode. So this might be the issue here, that the flutter tools simply rely on the default configuration instead of the one that is specified in the custom schema.

## Flutter doctor output

```
[✓] Flutter (Channel master, v1.10.7-pre.109, on Mac OS X 10.14.5 18F132, locale en-DE)
    • Flutter version 1.10.7-pre.109 at /Users/bob/Flutter
    • Framework revision 056f7244ef (3 weeks ago), 2019-10-01 18:09:24 -0400
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/bob/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • iPhone X        • 641DD28A-C709-4641-BA78-C54AE05443AC     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!

```

**Comment by jmagman** [comment]
I think you're hitting https://github.com/flutter/flutter/issues/15567.  There's an outstanding fix at https://github.com/flutter/flutter/pull/42964.
