### ISSUE TITLE
Regression in microbenchmarks_iosMatrixUtils_affine_transformRect_iteration

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43276]
Looks like it started with https://github.com/flutter/flutter/pull/42953.

**Comment by kf6gpe** [comment]
Examining in triage; we think this may be noise due to the device lab changeover. Removing the TODAY label for now.

**Comment by liyuqian** [comment]
Closing as the regression is gone. (See also https://github.com/flutter/flutter/issues/41986#issuecomment-549584542)
