### ISSUE TITLE
Add deprecation warnings to old embedding

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#43298]
Add deprecation warnings to old embedding

**Comment by xster** [comment]
I don't know if you already have this in mind but we should mark everything in https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/plugin/common/PluginRegistry.java as deprecated as well and make sure they point to an equivalent in the new embedding APIs to help people migrate.

**Comment by xster** [comment]
we mentioned offline that we should likely do this for the next release after phase 1

**Comment by dnfield** [comment]
Posted in PR - we need to migrate all 1p plugins before relanding this, so that they can build cleanly with `-Werror`.
