### ISSUE TITLE
Missing examples in documentation [androidx-migration]

### ISSUE THREAD

**Issue by elmariocarlos** [flutter/flutter#43294]
Hello, I have been preparing several flutter projects from a Release Management perspective, and just noticed recently the AndroidX Migration flutter page is changed at : https://flutter.dev/docs/development/androidx-migration#im-having-issues-migrating-to-androidx

I welcome the added feature of including _--androidx_ in the **create** options and is working OK.

However, the documentation page in the "How do I know if my project is using AndroidX?" section, is no longer indicating the appropriate settings in the **android/app/build.gradle**, specifically:

- Package for **testInstrumentationRunner** to be _"androidx.test.runner.AndroidJUnitRunner"_. 
- Dependencies for **androidTestImplementation** to be _'androidx.test:runner:1.1.1'_ and 'androidx.test.espresso:espresso-core:3.1.1' (at minimum)

It would be great to add them to the documentation page, so just in case someone is looking to verify the project is properly AndroidX migrated, they have all the approprioate examples.

Thanks in advance for the support!

![image](https://user-images.githubusercontent.com/38416166/67339795-83f9e980-f4f1-11e9-8f3b-0984e67d3248.png)

**Comment by blasten** [comment]
Thanks for the feedback -- you are right. However, verifying that app is correctly migrated to AndroidX is a little more complex.

**Comment by elmariocarlos** [comment]
> Thanks for the feedback -- you are right. However, verifying that app is correctly migrated to AndroidX is a little more complex.

I understand; but at least the prior instructions in the document that are now missing, should be a minimum as the app could stop running if the gradle version is upgraded, right?

**Comment by Hixie** [comment]
@blasten Is this bug actionable? (i.e. should we actually do something here?)

**Comment by blasten** [comment]
@Hixie Yep. I think it's worth adding this to the docs.

**Comment by elmariocarlos** [comment]
Great news @blasten @Hixie , will we on the lookout when it's complete :) Have a great new year!
