### ISSUE TITLE
Possible compatibility issue with Firebase

### ISSUE THREAD

**Issue by markjoseultra** [flutter/flutter#43304]
I tried creating a new flutter project, I follow the console instructions to add firebase but it is giving me this error, my other projects are still working fine, I tried looking for answers in stackoverflow and github and none of the answers worked, 
I revert back to the old version 
classpath 'com.google.gms:google-services:4.2.0' it works
tried informing firebase support and referred me to this thread.
below is the error I'm getting

Launching lib\main.dart on SM G950F in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "D:\Backup\Documents\flutter_Projects\fl_agrinic\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Backup\Documents\flutter_Projects\fl_agrinic\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Command: D:\Backup\Documents\flutter_Projects\fl_agrinic\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by iapicca** [comment]
Hi @markjoseultra 
Could you please provide your `flutter doctor -v`
and your your `flutter run --verbose`/`flutter build --verbose`?
Thank you

**Comment by janmoppel** [comment]
Hello @markjoseultra !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
