### ISSUE TITLE
document flutter's -d argument more in flutter help

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#4330]
When you have two or more devices connected, flutter run needs you select which one you want to deploy to. This requires copy-pasting the device identifier. "flutter run" could check an environment variable to see which device to deploy to if more than one are connected.

**Comment by eseidelGoogle** [comment]
You can give partial (case-insensitive) identifiers too (if that helps).

For example, I commonly use -d i and -d n to differentiate from my iDevice vs. my Nexus device.

**Comment by collinjackson** [comment]
That is good enough for my purposes, but it isn't discoverable; maybe let's document the -d command more in "flutter help"?

**Comment by sethladd** [comment]
Thanks!
