### ISSUE TITLE
Resolve "stuck" modifier flags

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#43309]
Under the current implementation, the engine detects whether a modifier key (control, caps, command) is pressed by overriding `flagsChanged:NSEvent`. The `event` parameter holds a `modifierFlags` field with the value of all the currently pressed modifier keys. If the user releases all pressed modifiers, that field will be 0. The embedder keeps a state of the previously pressed modifiers, and compares it with the new value, determining if a new modifier key was pressed or release. This logic breaks if a user press and holds two modifier keys in another window, selects the flutter window, and releases one of them. That event will be considered a "down" event instead of "up". 

This raises the question of whether this could be solved from the framework side. Instead of the framework relying on receiving all the key events and storing them, it could make use of the "modifierFlags" field that is passed as a key event as a fallback. 

The embedder should still send the `flagsChanged:` event since that's the only way to get notified if a user presses a modifier key while on the app.

@gspencergoog @stuartmorgan

**Comment by gspencergoog** [comment]
I think this is fixed.
