### ISSUE TITLE
PointerDownEvent is null on handleTapDown

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#43310]
The PointerDownEvent is sometimes coming as null when chips are tapped:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/gestures/tap.dart#L452-L459

Internal bug is b/143126092.

This might be client's own Chip implementation (not our own Material implementation). Repro instructions can be found in the internal bug.

**Comment by mehmetf** [comment]
Updates from internal bug: The component is using `FlatButton`. The button is removed once user taps on it. We are guessing that it could be the cause where the button state is disposed before handleTapDown gets called.

**Comment by mehmetf** [comment]
Delaying the removal of the button via:

```dart
onTap: () => Future.delayed(Duration(milliseconds: 100)).then((_) {
   // remove button
});
```

did not work.

**Comment by darrenaustin** [comment]
I tried to reproduce this with just a simple test with the FlatButton as you described above:

```dart
import 'package:flutter/material.dart';

void main() => runApp(PointerDownTestApp());

class PointerDownTestApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.from(colorScheme: const ColorScheme.light()),
      home: PointerDownTestPage(),
    );
  }
}

class PointerDownTestPage extends StatefulWidget {

  @override
  _PointerDownTestPageState createState() => _PointerDownTestPageState();
}

class _PointerDownTestPageState extends State<PointerDownTestPage> {

  bool _buttonShown = true;

  void _hideButton() {
    setState(() {
      _buttonShown = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Pointer Down Test'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            if (_buttonShown) FlatButton(
              child: const Text('Remove me!'),
              onPressed: _hideButton,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            _buttonShown = true;
          });
        },
        child: Icon(Icons.add),
      ),
    );
  }
}
```

And it didn't have an issue. I also tried wrapping the button in a `GestureDetector` and it didn't have an issue. So it must be something specific about how the button is being used in the app.  If we could get a distilled repo case that would be helpful.

**Comment by dkwingsmt** [comment]
Update: I've found out the cause and a consistent test. I'm figuring out the best way to fix the code.
