### ISSUE TITLE
Is possible to develop flutter application on a web page?

### ISSUE THREAD

**Issue by xrr2016** [flutter/flutter#43313]
not need to install the runtime environment locally，just an idea，after all, installing the local running environment is a matter of trouble and error.

**Comment by stuartmorgan** [comment]
Flutter requires native tools (Gradle, Xcode, etc.). Theoretically someone could run a remote build service integrated with a cloud IDE and some kind of remote emulator solution for testing, but it would be a major undertaking, and outside the scope of the Flutter project.
