### ISSUE TITLE
Chinese texts in copy paste toolbar don't align to center and get clipped when using large fontsize

### ISSUE THREAD

**Issue by yuzhihang** [flutter/flutter#43326]
1. texts doesn't align to vertical center
![image](https://user-images.githubusercontent.com/16217662/67367748-b4508f00-f5a8-11e9-86c8-feaf15086e6b.png)

2. clipped when setting system font size to large enough in Display  setting.
to reproduce this
2.1 in iphoneX use largest size
2.2 in iphone 7, 2 level  larger than default size.
![image](https://user-images.githubusercontent.com/16217662/67367843-e6fa8780-f5a8-11e9-9c31-d31b5b5c99bb.png)

system: iOS 12.x & 13.x

**Comment by iapicca** [comment]
Hi @yuzhihang 
I see there are several issue similar to the case you described:

https://github.com/flutter/flutter/issues/42715
https://github.com/flutter/flutter/issues/40248
https://github.com/flutter/flutter/issues/40118

Please follow up on those issues,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by yuzhihang** [comment]
i am not sure it is the same issue with 42715,40248 and 40118 or not.
the three issues are about l10n and textfield.
-----------
I remove the localization code and use default l10n setting only.
then i set font size to largest, english words get clipped ,too:
![image](https://user-images.githubusercontent.com/16217662/67555708-6a041500-f744-11e9-8efb-651daa099faf.png)
flutter doctor:
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale en-CN)

ios 12.4, iphonex

**Comment by GaryQian** [comment]
This should be fixed by #44029

Can you please verify it fixes it in your specific case as it is slightly different than the others mentioned?

You can try the fix by using the master channel `flutter channel master` and `flutter upgrade`.

Thanks!
