### ISSUE TITLE
Flutter google maps plugin doesn't work for android less than 21

### ISSUE THREAD

**Issue by AymanMubark** [flutter/flutter#43323]
Flutter google maps plugin doesn't work for android less than 21
```
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18362.175], locale en-US)
    • Flutter version 1.9.1+hotfix.5 at C:\flutter
    • Framework revision 1aedbb1835 (6 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Ayman\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8580
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\Ayman\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • JKM LX2 • 2DR4C19417000073 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @AymanMubark 
can you please provide your `flutter run --verbose`/`flutter build --verbose`,
also to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by AymanMubark** [comment]
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:location/location.dart';
import 'package:monjid/Models/TempData.dart';
import 'package:monjid/Services/LocationServices.dart';
import 'package:monjid/components/buttons.dart';
import 'package:monjid/theme/constant.dart';

class SelectLocationPage extends StatefulWidget {
  SelectLocationPage({Key key}) : super(key: key);

  _SelectLocationPageState createState() => _SelectLocationPageState();
}

class _SelectLocationPageState extends State<SelectLocationPage> {
  CameraPosition _initialPosition =
      CameraPosition(target: LatLng(15.5018319, 32.4325073), zoom: 7.0);
  bool _loading = false;

  Completer<GoogleMapController> mapController = Completer();

  var location = new Location();

  LocationData currentLocation;
  Future<LocationData> _getLocation() async {
    try {
      currentLocation = await location.getLocation();
    } catch (e) {
      print(e);
      currentLocation = null;
    }
    return currentLocation;
  }

  Set<Marker> markers = new Set<Marker>();
  Marker marker;
  @override
  void initState() {
    super.initState();
    _getLocation().then((location) {
      marker = new Marker(
        markerId: MarkerId(location.latitude.toString()),
        position: LatLng(location.latitude, location.longitude),
        draggable: true,
      );
      setState(() {
        markers.add(marker);
      });
    });
  }

  void _updatePosition(CameraPosition _position) {
    markers.remove(marker);
    marker = Marker(
      markerId: MarkerId('marker_2'),
      position: LatLng(_position.target.latitude, _position.target.longitude),
      draggable: true,
    );
    markers.add(marker);
    setState(() {});
  }

  void _onMapCreated(GoogleMapController controller) {
    mapController.complete(controller);
  }

  MapType _defaultMapType = MapType.normal;

  void _changeMapType() {
    setState(() {
      _defaultMapType = _defaultMapType == MapType.normal
          ? MapType.satellite
          : MapType.normal;
    });
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Directionality(
        textDirection: TextDirection.rtl,
        child: Scaffold(
            appBar: AppBar(
              title: Text('الخريطة'),
            ),
            body: Stack(children: <Widget>[
              GoogleMap(
                mapType: _defaultMapType,
                myLocationEnabled: true,
                onMapCreated: _onMapCreated,
                initialCameraPosition: _initialPosition,
                markers: markers,
                onCameraMove: (po) => _updatePosition(po),
              ),
              Container(
                margin: EdgeInsets.only(top: 80, right: 10),
                alignment: Alignment.topRight,
                child: Column(children: <Widget>[
                  FloatingActionButton(
                      child: Icon(Icons.layers),
                      elevation: 5,
                      backgroundColor: Colors.teal[200],
                      onPressed: () {
                        _changeMapType();
                      }),
                ]),
              ),
            ]),
            bottomNavigationBar: (_loading)
                ? FlatButton(
                    child: CircularProgressIndicator(
                      valueColor: AlwaysStoppedAnimation<Color>(appColor),
                    ),
                    onPressed: () {},
                  )
                : bottomNavigationBarButton(
                    title: 'اختيار الموقع',
                    icon: FontAwesomeIcons.mapMarked,
                    onPressed: () async {
                      setState(() {
                        _loading = true;
                      });
                      String formattedAddress = "";
                      getPlace(marker.position.latitude,
                              marker.position.longitude)
                          .then((result) {
                        if (result.isNotEmpty) if (result[0]
                            .toString()
                            .isNotEmpty) if (result["results"][0]
                                ["formatted_address"]
                            .toString()
                            .isNotEmpty) {
                          formattedAddress += result["results"][0]
                                  ["formatted_address"]
                              .toString();
                        }
                        order.address = formattedAddress;
                        order.orderLat = marker.position.latitude;
                        order.orderLong = marker.position.longitude;
                        setState(() {
                          _loading = false;
                        });
                        Navigator.pushNamed(context, '/orderConfirm');
                      }).catchError((onError) {
                        setState(() {
                          _loading = false;
                        });
                      });
                    })),
      ),
    );
  }
}

**Comment by AymanMubark** [comment]
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.monjid"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
apply plugin: 'com.google.gms.google-services'

**Comment by AymanMubark** [comment]
E/PlatformViewsController( 5046): Trying to use platform views with API 19, required API level is: 20
E/flutter ( 5046): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, An attempt was made to use platform views on a version of Android that platform views does not support., null)

**Comment by Gperez88** [comment]
same issues :(

**Comment by Gperez88** [comment]
> ```
> E/PlatformViewsController( 5046): Trying to use platform views with API 19, required API level is: 20
> E/flutter ( 5046): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, An attempt was made to use platform views on a version of Android that platform views does not support., null)
> ```

Same issues :(

**Comment by jagiro** [comment]
Related with https://github.com/flutter/flutter/issues/23728
