### ISSUE TITLE
Full stack-trace for unhandled exceptions?

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#43331]
## Error log example
```
Performing hot reload...
Syncing files to device LGM G600L...

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Builder(dirty):
The getter 'length' was called on null.
Receiver: null
Tried calling: length

User-created ancestor of the error-causing widget was: 
  Stack file:///D:/dev/pavement/lib/util/modelPage.dart:78:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _parseJson (dart:convert-patch/convert_patch.dart:28:28)
#2      JsonDecoder.convert (dart:convert/json.dart:493:36)
#3      JsonCodec.decode (dart:convert/json.dart:151:41)
#4      jsonDecode (dart:convert/json.dart:94:10)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 66 of 1169 libraries in 1,754ms.
```

It's impossible to see where the exception actually takes place.

AFAIR it used to print at least more stack lines than this a few months ago?

## Logs

```
D:\dev\pavement>flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.17134.1006], locale en-GB)
    • Flutter version 1.9.1+hotfix.5 at C:\tools\flutter
    • Framework revision 1aedbb1835 (6 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at c:\tools\Android-SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = c:\tools\Android-SDK
    • Java binary at: C:\tools\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\tools\android-studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] VS Code, 32-bit edition (version 1.37.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • LGM G600L • LGMG600Lf8469764 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by remoteportal** [comment]
It's useless without the full stack!

**Comment by boyan01** [comment]
It looks like the relevant options are available in the Android Studio plugin.

![image](https://user-images.githubusercontent.com/17426470/69418677-26f28d00-0d56-11ea-8567-8e03c5e908dd.png)

**Comment by duzenko** [comment]
No, that option has nothing to do with this issue

**Comment by remoteportal** [comment]
Languages & Frameworks > Flutter > General > Enable verbose logging

did NOT help, either

**Comment by couturmi** [comment]
I was able to show the full stacktrace for these cases by doing the opposite of what @boyan01 suggested.
Deselect the "Show structured errors" checkbox and it will show the full stacktrace instead of cutting it off at 5 lines.

**Comment by fred3m** [comment]
A comment on the above solution. I was running an app and had to stop and restart it after deselecting `Show structured errors` in order for it to start displaying the full stack trace.

**Comment by darshankawar** [comment]
Hi @duzenko,
Is this a valid issue ?
If so, can you check above comments and solutions and see if they work for you ?
Thanks.

**Comment by duzenko** [comment]
I will when I get around to your mobile app next time

**Comment by zoechi** [comment]
Seems to be an IDE integration issue. I have no problem getting the full stack trace when I use `flutter run` in a terminal.
In Emacs and Flutter devtools I only get the 5 lines as in the original post.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
