### ISSUE TITLE
My app stuck on splash screen (IOS 13 device) 

### ISSUE THREAD

**Issue by 2013abdullah1** [flutter/flutter#43337]
when I use firebase in my app not working
My app stuck on splash screen (IOS 13 device) after updating to xcode 11 without showing any error in logs !!.

flutter run 
```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                           3.1s
 └─Compiling, linking and signing...                        10.3s
Xcode build done.                                           21.3s
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'getString' was called on null.
Receiver: null                                                          
Tried calling: getString("token")                                       
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)    
#1      main (package:daleel_med/main.dart:36:32)                       
<asynchronous suspension>                                               
#2      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
#3      _rootRun (dart:async/zone.dart:1124:13)                         
#4      _CustomZone.run (dart:async/zone.dart:1021:19)                  
#5      _runZoned (dart:async/zone.dart:1516:10)                        
#6      runZoned (dart:async/zone.dart:1500:12)                         
#7      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)    
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
flutter: Overflow on channel: flutter/lifecycle.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
flutter: Overflow on channel: flutter/lifecycle.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Syncing files to device iPhone 11 Pro Max...                     1,982ms

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild
state), press "R".
An Observatory debugger and profiler on iPhone 11 Pro Max is available at:
http://127.0.0.1:57804/hHgJzSpsqAg=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press
"q".
```

**Comment by BondarenkoStas** [comment]
@2013abdullah1 please provide your flutter doctor -v output, is it hotfix-5?

Will just leave it here from https://github.com/flutter/flutter/issues/43325 for other who will check
> in flutter 1.7.1 ,ios 12
> it is work same code!

**Comment by gaaclarke** [comment]
It sounds like you are calling `getString` on null inside your main method (probably before `runApp` has been called).  Check out `daleel_med/main.dart:36:32`

This is causing an exception what makes it so `runApp` isn't called.  You can do a few things:
1) fix the exception
2) put a try-block in your main before RunApp
3) move init logic until after RunApp

**Comment by 2013abdullah1** [comment]
flutter doctor -v 
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.14.6 18G103, locale en-SA)
    • Flutter version 1.10.14 at /Users/macc/Downloads/delef/flutter
    • Framework revision 1946fc4da0 (2 weeks ago), 2019-10-07 15:23:31 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/macc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone • 7620fc00872d3f22f96367c • ios • iOS 13.1.3

• No issues found!

**Comment by 2013abdullah1** [comment]
> when I use firebase in my app not working
> My app stuck on splash screen (IOS 13 device) after updating to xcode 11 without showing any error in logs !!.
> 
> flutter run
> 
> ```
> Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
> Running Xcode build...                                                  
>                                                    
>  ├─Assembling Flutter resources...                           3.1s
>  └─Compiling, linking and signing...                        10.3s
> Xcode build done.                                           21.3s
> [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'getString' was called on null.
> Receiver: null                                                          
> Tried calling: getString("token")                                       
> #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)    
> #1      main (package:daleel_med/main.dart:36:32)                       
> <asynchronous suspension>                                               
> #2      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
> #3      _rootRun (dart:async/zone.dart:1124:13)                         
> #4      _CustomZone.run (dart:async/zone.dart:1021:19)                  
> #5      _runZoned (dart:async/zone.dart:1516:10)                        
> #6      runZoned (dart:async/zone.dart:1500:12)                         
> #7      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)    
> #8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
> #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
> flutter: Overflow on channel: flutter/lifecycle.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
> flutter: Overflow on channel: flutter/lifecycle.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
> Syncing files to device iPhone 11 Pro Max...                     1,982ms
> 
> 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild
> state), press "R".
> An Observatory debugger and profiler on iPhone 11 Pro Max is available at:
> http://127.0.0.1:57804/hHgJzSpsqAg=/
> For a more detailed help message, press "h". To detach, press "d"; to quit, press
> "q".
> ```

**Comment by babang1da** [comment]
same problem!
