### ISSUE TITLE
AnimatedContainer  error:bottom overflowed

### ISSUE THREAD

**Issue by 34678** [flutter/flutter#43341]
i want to code a sticker keyboard with animation
but when i use AnimatedContainer,i encounter a problem.
the problem is overflow.
pls help me
here is my code
or is there any other way to code a keyboard like animation.
 ```
  AnimatedContainer(
              duration: Duration(milliseconds: 20000),
              curve: Curves.linear,
              height: widget.showStickerKeyBoad ? 300 : 0,
              child: 
              
                Column(
                children: <Widget>[
                  styleWidget(),
                  packageListWidget(),
                  
                      EmotionList(
                          handleSendEmotion: this.handleSendMessage)
                ],
              )),
```
here is the bug
![unknown](https://user-images.githubusercontent.com/23259141/67395644-ee398980-f5d8-11e9-9e38-4a4ab692fe8a.png)

**Comment by VladyslavBondarenko** [comment]
Closing since probably solved and long time without an answer

**Comment by omidraha** [comment]
Related SO links:

https://stackoverflow.com/questions/59337058/how-to-avoid-bottom-overflowed-while-animation-flutter

https://stackoverflow.com/questions/53768384/flutter-animate-change-on-height-when-child-of-container-renders/53841499
