### ISSUE TITLE
video_player package set volume not maintained in Android after a phone call

### ISSUE THREAD

**Issue by CLucera** [flutter/flutter#43346]
**Video volume changes after receiving a call.**

Basically I have a `VideoPlayer` widget that loads a video by URL, on my application I create a Stateful widget, and in the initState method, I assign the controller variable and start the video.

everything works fine, but if I receive a call the audio starts his playback at the current volume set by the system at the same moment I'm back to my application after closing the phone call.

the issue doesn't happen if I change application via menu or simply put the application in the background with the home button.

## Steps to reproduce: 
use this widget in a sample application (android) while the video is reproducing call yourself from another phone, close the call and the Audio should start

pubspec.yaml should include [video_player package](https://pub.dev/packages/video_player) **version used:** ^0.10.0+4

```Dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class VideoTest extends StatefulWidget {
  @override
  _VideoTestState createState() => _VideoTestState();
}

class _VideoTestState extends State<VideoTest> {
  VideoPlayerController _controller;
  
  @override
  void initState() {
    _controller = VideoPlayerController.network("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4");

    if (_controller != null) {
      _controller.setVolume(0.0);
      _controller.initialize().then((_) {
        setState(() {
          _controller.play();
          _controller.setLooping(true);
        });
      });
    }
    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return VideoPlayer(_controller);
  }
}
```

## Other useful info:
**Smartphone:** Huawei P30 pro 
**Android version:** 9.0
**Flutter doctor:** (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Versione 10.0.18362.418], locale it-IT)
    • Flutter version 1.9.1+hotfix.5 at C:\flutter
    • Framework revision 1aedbb1835 (6 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

**Comment by maheshmnj** [comment]
Hi @CLucera,
Thanks for filing the issue I can confirm using the latest version of the plugin ```video_player: ^2.1.6``` the audio remains at the same level before and after the call . I have tested this on the latest stable version of flutter.
I would request you to upgrade to the latest version and verify the Issue.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.2.2 at /Users/mahesh/Documents/flutter
    • Framework revision d79295af24 (11 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
</details>

Thank you.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
