### ISSUE TITLE
Disable keyboard gifs and animated images

### ISSUE THREAD

**Issue by ederluca** [flutter/flutter#43340]
Good Morning

I am creating a chat using the flutter inside my mobile application and I noticed that when I click on textfield the keyboard brings up the default emoji options that work very well in the application but when I select a gif or some animated emoji I get the following appname messages doenst's support image insertion here.

I would like to know if it is possible to hide these keyboard options or enable some feature that support these images can help me?

I am using Flutter SDK version 1.9.1 + hotfix.5
![WhatsApp Image 2019-10-23 at 09 55 50](https://user-images.githubusercontent.com/51955855/67394910-62dddb00-f57b-11e9-982a-4cd0b374752a.jpeg)

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by RuedigerMoeller** [comment]
the issue addresses input of animated gifs from the keyboard, currently emojis only can be added. this is a severe issue as its not possible to build a chat with nowadays must-have features.

**Comment by skpatrat** [comment]
Any updates on this? 
I want to either remove the option to select images and GIFs from the keyboard or implement them in the app. 
I have not explored native plugins for this, is there any solution that way?

**Comment by iapicca** [comment]
@skpatrat @RuedigerMoeller 
this issue is closed (from almost an year) and therefore not actively worked on
please follow this [indication](https://github.com/flutter/flutter/issues/43340#issuecomment-554410864)

> Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v' please.
> All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by skpatrat** [comment]
> @skpatrat @RuedigerMoeller
> this issue is closed (from almost an year) and therefore not actively worked on
> please follow this [indication](https://github.com/flutter/flutter/issues/43340#issuecomment-554410864)
> 
> > Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v' please.
> > All system setups can be slightly different so its always better to open new issues and reference related issues.

I have raised a new issue as a feature request: https://github.com/flutter/flutter/issues/67857
