### ISSUE TITLE
Performance regression in image_list_jit_reported_duration

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43355]
Started with engine roll https://github.com/flutter/flutter/pull/43308. Pretty strong signal on the dashboard.

**Comment by gaaclarke** [comment]
<img width="255" alt="Screen Shot 2019-10-23 at 2 22 56 PM" src="https://user-images.githubusercontent.com/30870216/67435356-cb8b7e80-f5a0-11e9-8fef-19fa7567d649.png">

It seems to have gone back down as of https://github.com/flutter/flutter/commit/50112f3cdce6342926273575dedc2b03b21a7a33.
