### ISSUE TITLE
Regression in complex_layout_semantics_perfinitialSemanticsTreeCreation

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43354]
Noisy; may have started with engine roll https://github.com/flutter/flutter/commit/37521710aa2f3af0f105bafcb27d7e49c40278e3.

**Comment by gaaclarke** [comment]
<img width="255" alt="Screen Shot 2019-10-23 at 2 29 24 PM" src="https://user-images.githubusercontent.com/30870216/67435716-992e5100-f5a1-11e9-95f9-44d23f568a8b.png">
Results for roughly 10/18 - 10/23

**Comment by gaaclarke** [comment]
This benchmark is all over the place, I'm not sure I'd say it was a regression and I'm not sure what the best thing to do about it is.

**Comment by LongCatIsLooong** [comment]
Doesn't look like a regression. Closing to unblock the roll.
