### ISSUE TITLE
Use a common PluginPlatformInterfaceMixin in federated plugins

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#43368]
The platform interfaces for federated plugins include some logic other than the interface definition (see https://github.com/flutter/plugins/pull/2230).

We would like to move the common code to a reusable place such that a federated plugin platform interface looks like:

```dart
class UrlLauncherPlatform with PluginPlatformInterfaceMixin {

// The only thing we have here is the interface definition in the form of throwing methods, e.g:

  Future<bool> canLaunch(String url) {
    throw UnimplementedError('canLaunch() has not been implemented.');
  }

}
```

Note that this means removing the static instance from the platform interface, and instead keeping some central map of platform implementations.

Platform implementation activation will look something like:

```dart
// We may be able to do more useful things than having a public static instance, but
// this is out of scope for current discussion.
PluginImplementations pluginImplementations = PluginImplementations.instance;
pluginImplementations.set(UrlLauncherPlatform, WindowsUrlLauncherPlatform());
```

cc @collinjackson @hterkelsen @stuartmorgan @franciscojma86

**Comment by collinjackson** [comment]
I posted my proposal for a common base interface in #2326.

**Comment by hterkelsen** [comment]
I like the implementation in https://github.com/flutter/plugins/pull/2326. I think we should have a package in `flutter/plugins` called `plugin_platform_interface` or something like that, and have all of our federated plugins use it.

**Comment by collinjackson** [comment]
I am happy with the name `plugin_platform_interface` as a first-party package.

Keeping it semantically versioned separately will allow us to iterate on the API rapidly independently of SDK releases.

An argument that could be made for making it minimal/composable and having the name be something specific like the verify_extends. But it seems like a good dumping ground for other plugin federation related functionality...

**Comment by fzyzcjy** [comment]
Hi I wonder the current status of this issue? It sounds very useful! Thanks

**Comment by stuartmorgan** [comment]
Closing as obsolete given https://github.com/flutter/plugins/pull/2348
