### ISSUE TITLE
[plugin_tools] Format in flutter/plugins does not work

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#43364]
Running `pub global run flutter_plugin_tools format` in the `flutterfire` directory throws the following exception at me:

```
Unhandled exception:
Invalid argument(s): join(null, "gcloud-service-key.json"): part 0 was null, but part 1 was not.
#0      _validateArgList (package:path/src/context.dart:1087:5)
#1      Context.join (package:path/src/context.dart:231:5)
#2      join (package:path/path.dart:269:13)
#3      new FirebaseTestLabCommand (package:flutter_plugin_tools/src/firebase_test_lab_command.dart:26:13)
#4      main (package:flutter_plugin_tools/src/main.dart:47:22)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

I could not find anything about it at https://github.com/flutter/plugin_tools.

I am trying to run it on Windows and tried to create a `HOME` environment variable, however, I was unsuccessful in trying to resolve the `null` value:

https://github.com/flutter/plugin_tools/blob/d472dc384961eba1648ddf342e19989dd6c4c852/lib/src/firebase_test_lab_command.dart#L26

**Comment by collinjackson** [comment]
That is really strange, I wonder why it's running the firebase-test-lab command instead of format.

I don't have Windows set up for development so it's hard for me to test. If you do figure out a fix I'm happy to review a PR.

In the meantime using the format patch commands from the CI failures may be a good way to get your tests to pass.

**Comment by creativecreatorormaybenot** [comment]
@collinjackson Oh wow, I just realized what that message means. I did not understand that one is supposed to copy the whole remainder of the output - that is why I could not get it to work, hence, I assumed you meant `pub global activate flutter_plugin_tools && pub global run flutter_plugin_tools format` before.

For future reference: Git Bash or some other bash terminal is needed for this on Windows.

**Comment by timsneath** [comment]
Are we good to close this issue now, @creativecreatorormaybenot?

**Comment by creativecreatorormaybenot** [comment]
@timsneath No, exact same error with:

```
Activated flutter_plugin_tools 0.0.32+4.
```

**Comment by timsneath** [comment]
Thanks for the clarification!

**Comment by stuartmorgan** [comment]
We're no longer maintaining these tools for repos other than flutter/plugins and flutter/packages, so closing.

**Comment by creativecreatorormaybenot** [comment]
@stuartmorgan That *sounds* like it makes sense but it does not. If you look at the original issue, it is about `flutter/plugins`. I will adjust the title to reflect today's situation.

**Comment by stuartmorgan** [comment]
Looks like we probably just need a fallback value so that building the default argument is non-fatal.

**Comment by stuartmorgan** [comment]
This was fixed when the tool was migrated to null safety.
