### ISSUE TITLE
Firebase Mojo bindings are broken

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4337]
The new bindings for Mojo landed, meaning that the bindings for Firebase that are checked in no longer work with the latest version of the Dart Mojo bindings used on branch `master`. The bindings for Firebase need to be regenerated.

**Comment by collinjackson** [comment]
I should have a fix for this today

**Comment by collinjackson** [comment]
Should work on iOS simulator and Android -- please give it a try. I've updated codelab branch to point to flutter master.

**Comment by collinjackson** [comment]
By the way, you'll need to update your AndroidManifest.xml to set com.google.android.gms.version to 9080000. I'll update the codelab instructions.

```
	<meta-data android:name="com.google.android.gms.version" android:value="9080000" />
```

**Comment by collinjackson** [comment]
https://github.com/flutter/firechat-flutter/pull/7

**Comment by kroikie** [comment]
@jimbeveridge

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1024. Any further collaboration will be done there.
