### ISSUE TITLE
Firebase bindings needs to be tested as part of a Flutter release

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4338]
The latest release of Flutter broke the [Firebase code](https://github.com/flutter/firebase) because the Mojo bindings changed. In the future, it would be good if we could be warned of this problem before users discover it.

**Comment by sethladd** [comment]
We aren't working on the older instantiation of the firebase bindings, so going to close this. When they come back to life, we'll definitely want testing.

**Comment by kroikie** [comment]
@jimbeveridge

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1023. Any further collaboration will be done there.
