### ISSUE TITLE
Dynamically changing scroll direction of pageview builder

### ISSUE THREAD

**Issue by sasalx** [flutter/flutter#43380]
Hello. I am simply trying to change the scroll direction of the pageview builder dynamically. However, when I do that, the center point of each image fixes up which result in seeing one part of two images.

## Steps to Reproduce

1. Create a simple PageView.builder that takes images inside.
2. Add a button or some widget that changes the scroll direction of PageView.builder from Axis.vertical to Axis.horizontal or vice versa.
3. Change the scroll direction and try to scroll across images.

### Code Example

```dart
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Container(
          padding: EdgeInsets.all(0),
          child: Stack(
            children: <Widget>[
              PageView.builder(
                itemCount: images.length,
                itemBuilder: (BuildContext context, int index) {
                  return Image.network(images[index], fit: BoxFit.cover);
                },
                scrollDirection: _slider ? Axis.vertical : Axis.horizontal,
              ),
              Positioned(
                bottom: 0.0,
                child: switcher(), // change _slider bool value
              ),
            ],
          ),
        ),
      ),
    );
  }
```

### Images

- Vertical to horizontal: https://i.ibb.co/Rg7NdvQ/1.png
- Horizontal to vertical: https://i.ibb.co/w0CSDp3/2.png
- Used image 1: https://i.ibb.co/LnqTrmZ/photo-1518133910546-b6c2fb7d79e3-ixlib-rb-1-2.jpg
- Used image 2: https://i.ibb.co/VxVsDyJ/photo-1486825586573-7131f7991bdd-ixlib-rb-1-2.jpg

## Logs

```
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18362.418], locale en-GB)
    • Flutter version 1.9.1+hotfix.5 at E:\Code\flutter
    • Framework revision 1aedbb1835 (6 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at E:\Code\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: E:\Code\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at E:\Code\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

**Comment by iapicca** [comment]
Hi @sasalx 
does this code represent the issue you are describing?


<details>
  <summary>Code</summary>



```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

const List<String> images =[
  'https://i.ibb.co/LnqTrmZ/photo-1518133910546-b6c2fb7d79e3-ixlib-rb-1-2.jpg', 
  'https://i.ibb.co/VxVsDyJ/photo-1486825586573-7131f7991bdd-ixlib-rb-1-2.jpg'];

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  static bool _slider = true;

  @override
  Widget build(BuildContext context)=>Scaffold(
    body: Center(
      child: PageView.builder(
      scrollDirection: _slider ? Axis.vertical : Axis.horizontal,
      itemCount: images.length,
      itemBuilder: (BuildContext context, int index)=>
        Image.network(images[index], fit: BoxFit.cover),), 
    ),
    floatingActionButton: FloatingActionButton(
      onPressed: ()=> setState(()=> _slider = _slider ? false : true,)
    ),
  );
}
```

</details>

**Comment by sasalx** [comment]
Hello @iapicca ,

Yes that code example is sufficient and thanks to it I discovered something.

- To experience the bug with `scrollDirection: _slider ? Axis.vertical : Axis.horizontal,` setting, you actually need **at least** 3 images in the array.
- For the `scrollDirection: _slider ? Axis.horizontal : Axis.vertical,` setting, 2 images are sufficient.

I believe this happens because how scroll calculates the shape of the items to give "per item per scroll" effect.

**Comment by iapicca** [comment]
Hi @sasalx 
you are indeed correct 
I've updated the [sample code](https://gist.github.com/iapicca/008b307d71f9027ee813079dd93d6d34)

**Comment by meghead** [comment]
Any new insights into this issue?

**Comment by kcoder666** [comment]
FYI, this bug still exists in the current Flutter version. There was already a workaround proposed by @jimlywu in #16481, however, using screen size is not generic enough. You can use the solution to measure widget size from https://stackoverflow.com/a/60868972/9724114 to apply the correct viewport size. The full solution code should be as follows:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

const List<String> images = [
  'https://i.ibb.co/LnqTrmZ/photo-1518133910546-b6c2fb7d79e3-ixlib-rb-1-2.jpg',
  'https://i.ibb.co/VxVsDyJ/photo-1486825586573-7131f7991bdd-ixlib-rb-1-2.jpg'
];

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  PageController _pageController = PageController(initialPage: 0);
  static bool _slider = true;

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Center(
          child: MeasureSize(
            onChange: (size) {
              _widgetSize = size;
            },
            child: PageView.builder(
              scrollDirection: _slider ? Axis.vertical : Axis.horizontal,
              itemCount: images.length,
              itemBuilder: (BuildContext context, int index) =>
                  Image.network(images[index], fit: BoxFit.cover),
            ),
            pageController: _pageController,
          ),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () => setState(() {
            _slider = _slider ? false : true;
            // Recalculate viewport dimension
            _pageController.position.applyViewportDimension(
                direction == Axis.vertical
                    ? _widgetSize.height
                    : _widgetSize.width);
          }),
        ),
      );
}
```

**Comment by sasalx** [comment]
@kcoder666 Just tested the code. Works suprisingly well for `scrollDirection: _slider ? Axis.vertical : Axis.horizontal,` but unfortunetly the bug still persist on `scrollDirection: _slider ? Axis.horizontal : Axis.vertical,` setting.

**Comment by kcoder666** [comment]
> @kcoder666 Just tested the code. Works suprisingly well for `scrollDirection: _slider ? Axis.vertical : Axis.horizontal,` but unfortunetly the bug still persist on `scrollDirection: _slider ? Axis.horizontal : Axis.vertical,` setting. Can you also check it on your side, just to be sure?

If you change `_slider` meaning in `scrollDirection`, you need to do the same in `applyViewportDimension()` as well. So in `onPressed`, it should be changed to `_slider ? _pageViewSize.width : _pageViewSize.height` for it to work properly.

By the way, I'm waiting for the PR of @goderbauer to be merged so we don't need the workaround anymore.

**Comment by sasalx** [comment]
That makes sense, I missed that part. As you mentioned, @goderbauer can solve the problem entirerly so I hope they will merge it soon.
