### ISSUE TITLE
Menubar plugin for macOS

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#43386]
Port the FDE implementation to flutter/plugins

**Comment by stuartmorgan** [comment]
Why? That was not my plan for this plugin; I'd like to understand why the change here. (Feel free to follow up directly with me if that's easier.)

**Comment by stuartmorgan** [comment]
Also, any more formal/long-lived version of a menu bar API (plugin or built-in) should change to use, or at least be consistent with, the framework action and shortcut APIs before being published.

**Comment by franciscojma86** [comment]
Discussed offline, there's more discussion to be had about this plugin so will close for now and re-open once a conclusion has been reached.
