### ISSUE TITLE
Runner.app/Frameworks/Flutter.framework/Flutter: Permission denied

### ISSUE THREAD

**Issue by mengzhidaren** [flutter/flutter#43393]
<details>
  <summary>original</summary>
  
```
更新到1.9.1+hotfix.6版本发现打包时还是出现这样的问题,
我以经把 bete  dev stable master 全都试过了都不行,
能优先修复一下这个bug吗，现在app无法打包

```

</details>

Update to version 1.9.1 + hotfix.6 and find that there is still such a problem when packaging.
I've tried all the bet dev stable masters, but I can't.
Can you fix this bug first? Now the app can't be packaged.

**Comment by mengzhidaren** [comment]
mkdir -p /Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks
rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/Alamofire/Alamofire.framework" "/Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks"
building file list ... done
Alamofire.framework/
Alamofire.framework/Alamofire
Alamofire.framework/Info.plist

sent 2152909 bytes  received 70 bytes  4305958.00 bytes/sec
total size is 2152410  speedup is 1.00
Code Signing /Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks/Alamofire.framework with Identity Apple Development: 273518021@qq.com (7664TW5L3S)
/usr/bin/codesign --force --sign B78C015C2719D491149E701767392E4375E5DD41  --preserve-metadata=identifier,entitlements '/Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks/Alamofire.framework'
rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/CryptoSwift/CryptoSwift.framework" "/Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks"
building file list ... done
CryptoSwift.framework/
CryptoSwift.framework/CryptoSwift
CryptoSwift.framework/Info.plist

sent 886865 bytes  received 70 bytes  1773870.00 bytes/sec
total size is 886514  speedup is 1.00
Code Signing /Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks/CryptoSwift.framework with Identity Apple Development: 273518021@qq.com (7664TW5L3S)
/usr/bin/codesign --force --sign B78C015C2719D491149E701767392E4375E5DD41  --preserve-metadata=identifier,entitlements '/Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks/CryptoSwift.framework'
rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/FMDB/FMDB.framework" "/Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks"
building file list ... done
FMDB.framework/
FMDB.framework/FMDB
FMDB.framework/Info.plist

sent 178856 bytes  received 70 bytes  357852.00 bytes/sec
total size is 178607  speedup is 1.00
Code Signing /Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks/FMDB.framework with Identity Apple Development: 273518021@qq.com (7664TW5L3S)
/usr/bin/codesign --force --sign B78C015C2719D491149E701767392E4375E5DD41  --preserve-metadata=identifier,entitlements '/Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks/FMDB.framework'
rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/FSPagerView/FSPagerView.framework" "/Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks"
building file list ... done
FSPagerView.framework/
FSPagerView.framework/FSPagerView
FSPagerView.framework/Info.plist

sent 461872 bytes  received 70 bytes  923884.00 bytes/sec
total size is 461573  speedup is 1.00
Code Signing /Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks/FSPagerView.framework with Identity Apple Development: 273518021@qq.com (7664TW5L3S)
/usr/bin/codesign --force --sign B78C015C2719D491149E701767392E4375E5DD41  --preserve-metadata=identifier,entitlements '/Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks/FSPagerView.framework'
rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/meice1/Desktop/meicet/Meice_Rent/MeiceRent/Pods/../../../meicetFlutter/.ios/Flutter/engine/Flutter.framework" "/Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks"
building file list ... done
Flutter.framework/
Flutter.framework/Flutter
Flutter.framework/Info.plist
Flutter.framework/icudtl.dat
Flutter.framework/_CodeSignature/
Flutter.framework/_CodeSignature/CodeResources

sent 39620755 bytes  received 120 bytes  79241750.00 bytes/sec
total size is 39615525  speedup is 1.00
Stripped /Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks/Flutter.framework/Flutter of architectures: x86_64 armv7
Code Signing /Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks/Flutter.framework with Identity Apple Development: 273518021@qq.com (7664TW5L3S)
/usr/bin/codesign --force --sign B78C015C2719D491149E701767392E4375E5DD41  --preserve-metadata=identifier,entitlements '/Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks/Flutter.framework'
/Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks/Flutter.framework: replacing existing signature
/Users/meice1/Library/Developer/Xcode/DerivedData/MeiceRent-ayonrqahtwggvebtyckzgxbtoszq/Build/Products/Release-iphoneos/MeiceRent.app/Frameworks/Flutter.framework: Permission denied

**Comment by iapicca** [comment]
Hi @mengzhidaren 
does this [solution ](https://github.com/flutter/flutter/issues/40146)solve the issue you are describing?

**Comment by mengzhidaren** [comment]
@iapicca 
I have solved this problem, but there are other problems. Let me solve them slowly.
