### ISSUE TITLE
Failed to send crash report due to a network error: SocketException: Failed host lookup: 'clients2.google.com' (OS Error: 。 , errno = 11001)

### ISSUE THREAD

**Issue by limin1314** [flutter/flutter#43397]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by limin1314** [comment]
flutter.log
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk

## exception

FileSystemException: FileSystemException: readSync failed, path = 'G:\flutter_browser\build\app\outputs\apk\release\app-release.apk' (OS Error: 操作成功完成。
, errno = 0)

```
#0      _RandomAccessFile.readSync (dart:io/file_impl.dart:761:7)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:560:23)
#2      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:95:62)
#3      _calculateSha (package:flutter_tools/src/android/gradle.dart:619:32)
#4      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:765:34)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#14     runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart)
#15     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#16     _rootRunUnary (dart:async/zone.dart:1132:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#21     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#22     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

**Comment by limin1314** [comment]
G:\flutter_browser>flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18362.175], locale zh-CN)
    • Flutter version 1.9.1+hotfix.5 at G:\AndroidBrowser\branches\flutter
    • Framework revision 1aedbb1835 (6 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at E:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = E:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by iapicca** [comment]
Hi @limin1314 
I'm not sure that google translator is really helping me out here:
```
FileSystemException: FileSystemException: readSync failed, path = 'G:\flutter_browser\build\app\outputs\apk\release\app-release.apk' (OS Error: 操作成功完成。
, errno = 0)
```
translates to 
```
FileSystemException: FileSystemException: readSync failed, path = 'G:\flutter_browser\build\app\outputs\apk\release\app-release.apk' (OS Error: **The operation completed successfully.**。
, errno = 0)
```
is that correct?

Could you please provide your `flutter run --verbose`/`flutter build --verbose` ?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
