### ISSUE TITLE
Framework Error

### ISSUE THREAD

**Issue by faizahmad** [flutter/flutter#43405]
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause. In either case, please report this assertion by filing a bug on GitHub:

**Comment by iapicca** [comment]
Hi @faizahmad 
can you please describe the issue in detail
and provide your `flutter doctor -v`
thank you

**Comment by janmoppel** [comment]
Hello @faizahmad !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
