### ISSUE TITLE
Gradle failure may have been because of AndroidX incompatibilities

### ISSUE THREAD

**Issue by parthdomadiay23** [flutter/flutter#43413]
Warning: io.flutter.embedding.android.FlutterFragment: can't find referenced method 'void setArguments(android.os.Bundle)' in program class io.flutter.embedding.android.FlutterFragment
Warning: io.flutter.embedding.android.FlutterFragment: can't find referenced method 'androidx.fragment.app.FragmentActivity getActivity()' in program class io.flutter.embedding.android.FlutterFragment
Warning: io.flutter.embedding.android.FlutterFragment: can't find referenced method 'android.os.Bundle getArguments()' in program class io.flutter.embedding.android.FlutterFragment
Warning: io.flutter.embedding.android.FlutterFragment$1: can't find referenced method 'androidx.fragment.app.FragmentActivity getActivity()' in program class io.flutter.embedding.android.FlutterFragment
Warning: io.flutter.embedding.android.FlutterFragment$CachedEngineFragmentBuilder: can't find referenced method 'void setArguments(android.os.Bundle)' in program class 
io.flutter.embedding.android.FlutterFragment
Warning: io.flutter.embedding.android.FlutterFragment$NewEngineFragmentBuilder: can't find referenced method 'void setArguments(android.os.Bundle)' in program class io.flutter.embedding.android.FlutterFragment
Warning: io.flutter.embedding.android.FlutterView: can't find referenced method 'android.graphics.Insets getSystemGestureInsets()' in library class android.view.WindowInsets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.embedding.android.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.embedding.engine.FlutterEngineAndroidLifecycle: can't find referenced method 'void markState(androidx.lifecycle.Lifecycle$State)' in program class io.flutter.embedding.engine.FlutterEngineAndroidLifecycle
Warning: io.flutter.view.FlutterView: can't find referenced method 'android.graphics.Insets getSystemGestureInsets()' in library class android.view.WindowInsets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets
Warning: io.flutter.view.FlutterView: can't find referenced class android.graphics.Insets

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 37s
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                        99.3s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task bundleRelease failed with exit code 1

**Comment by iapicca** [comment]
Hi @parthdomadiay23 
could you please provide your `flutter doctor -v`
and your `flutter run --verbose` / `flutter build --verbose`.
Thank you

**Comment by parthdomadiay23** [comment]
parth@DESKTOP-31BA039 MINGW64 ~/Desktop/AndroidX/flutter_app/flutter_app
$ flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18362.418], locale en-IN)
    • Flutter version 1.9.1+hotfix.5 at C:\Flutter\flutter
    • Framework revision 1aedbb1835 (7 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\parth\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\parth\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.



parth@DESKTOP-31BA039 MINGW64 ~/Desktop/AndroidX/flutter_app/flutter_app
$ flutter run --verbose
[  +33 ms] executing: [C:\Flutter\flutter\] git log -n 1 --pretty=format:%H
[  +87 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 1aedbb1835bd6eb44550293d57d4d124f19901f0
[        ] executing: [C:\Flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +108 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +9 ms] v1.9.1+hotfix.5-0-g1aedbb183
[  +21 ms] executing: [C:\Flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +70 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] origin/stable
[   +2 ms] executing: [C:\Flutter\flutter\] git ls-remote --get-url origin
[  +81 ms] Exit code 0 from: git ls-remote --get-url origin
[  +19 ms] https://github.com/flutter/flutter.git
[ +164 ms] executing: [C:\Flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +61 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +224 ms] executing: C:\Users\parth\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +55 ms] Exit code 0 from: C:\Users\parth\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +2 ms] List of devices attached
[  +42 ms] No supported devices connected.
[  +24 ms] "flutter run" took 401ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:281:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:465:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main (file:///C:/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


parth@DESKTOP-31BA039 MINGW64 ~/Desktop/AndroidX/flutter_app/flutter_app
$ flutter build --verbose
[  +31 ms] executing: [C:\Flutter\flutter\] git log -n 1 --pretty=format:%H
[  +82 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] 1aedbb1835bd6eb44550293d57d4d124f19901f0
[   +1 ms] executing: [C:\Flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +116 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +3 ms] v1.9.1+hotfix.5-0-g1aedbb183
[  +21 ms] executing: [C:\Flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +102 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[  +17 ms] origin/stable
[   +2 ms] executing: [C:\Flutter\flutter\] git ls-remote --get-url origin
[  +50 ms] Exit code 0 from: git ls-remote --get-url origin
[   +7 ms] https://github.com/flutter/flutter.git
Missing subcommand for "flutter build".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

**Comment by iapicca** [comment]
Hi again @parthdomadiay23 
could you please run it when a device or an emulator is connected
thank you
