### ISSUE TITLE
url_launcher WebViewActivity.java uses or overrides a deprecated API.  Note: Recompile with -Xlint:deprecation for details.

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#43412]
Note: /home/cirrus/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.2.3/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

flutter doctor -v
[✓] Flutter (Channel unknown, v1.9.1+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.5 at /home/cirrus/sdks/flutter
    • Framework revision 1aedbb1835 (4 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /opt/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /opt/android-sdk-linux
    • ANDROID_SDK_ROOT = /opt/android-sdk-linux
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

**Comment by iapicca** [comment]
Hi @kw2019ltd
I'm not sure about what exactly is the issue you are experiencing,
I might have missed it, but I don't see any error:
could you be more specific.
Would be useful if you could post
the output of flutter build --verbose.
Thank you

https://github.com/flutter/flutter/issues/43410

**Comment by hemanthStack** [comment]
I'm getting this error when building APK

```/Users/apple/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:137: warning: [unchecked] unchecked cast
      return (List<String>) stream.readObject();
                                             ^
  required: List<String>
  found:    Object
/Users/apple/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:182: warning: [unchecked] unchecked method invocation: constructor <init> in class ArrayList is applied to given types
          List<String> listValue = new ArrayList<>((Set) value);
                                   ^
  required: Collection<? extends E>
  found: Set
  where E is a type-variable:
    E extends Object declared in class ArrayList
/Users/apple/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:182: warning: [unchecked] unchecked conversion
          List<String> listValue = new ArrayList<>((Set) value);
                                                   ^
  required: Collection<? extends E>
  found:    Set
  where E is a type-variable:
    E extends Object declared in class ArrayList
/Users/apple/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.4/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java:182: warning: [unchecked] unchecked conversion
          List<String> listValue = new ArrayList<>((Set) value);
                                   ^
  required: List<String>
  found:    ArrayList
4 warnings
Note: /Users/apple/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.2.3/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
``` 

Last sections you can check about the error

**Comment by kw2019ltd** [comment]
iam getting this while build apk

Note: /home/cirrus/.pub-cache/hosted/
pub.dartlang.org/url_launcher-5.2.4/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java
uses or overrides a deprecated API.


flutter doctor -v
[✓] Flutter (Channel unknown, v1.9.1+hotfix.5, on Linux, locale en_US.UTF-8)
• Flutter version 1.9.1+hotfix.5 at /home/cirrus/sdks/flutter
• Framework revision 1aedbb1835 (7 days ago), 2019-10-17 08:37:27 -0700
• Engine revision b863200c37
• Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version
29.0.2)
• Android SDK at /opt/android-sdk-linux
• Android NDK location not configured (optional; useful for native
profiling support)
• Platform android-29, build-tools 29.0.2
• ANDROID_HOME = /opt/android-sdk-linux
• ANDROID_SDK_ROOT = /opt/android-sdk-linux
• Java binary at: /usr/bin/java
• Java version OpenJDK Runtime Environment (build
1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
• All Android licenses accepted.

[!] Android Studio (not installed)
• Android Studio not found; download from
https://developer.android.com/studio/index.html
(or visit https://flutter.dev/setup/#android-setup for detailed
instructions).

[!] Connected device
! No devices available

**Comment by kw2019ltd** [comment]
hi getting below warn while building apk

Note: /home/cirrus/.pub-cache/hosted/
pub.dartlang.org/url_launcher-5.2.4/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java
uses or overrides a deprecated API.

 flutter doctor -v
[✓] Flutter (Channel unknown, v1.9.1+hotfix.5, on Linux, locale en_US.UTF-8)
• Flutter version 1.9.1+hotfix.5 at /home/cirrus/sdks/flutter
• Framework revision 1aedbb1835 (7 days ago), 2019-10-17 08:37:27 -0700
• Engine revision b863200c37
• Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version
29.0.2)
• Android SDK at /opt/android-sdk-linux
• Android NDK location not configured (optional; useful for native
profiling support)
• Platform android-29, build-tools 29.0.2
• ANDROID_HOME = /opt/android-sdk-linux
• ANDROID_SDK_ROOT = /opt/android-sdk-linux
• Java binary at: /usr/bin/java
• Java version OpenJDK Runtime Environment (build
1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
• All Android licenses accepted.

[!] Android Studio (not installed)
• Android Studio not found; download from
https://developer.android.com/studio/index.html
(or visit https://flutter.dev/setup/#android-setup for detailed
instructions).

[!] Connected device
! No devices available

**Comment by yakubpashask** [comment]
hey is there any update on this issue?

**Comment by TahaTesser** [comment]
Hi @kw2019ltd  @yakubpashask 
Are you still experiencing this isuse?
If so,  to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
