### ISSUE TITLE
 Flutter Performance Overlay on Fuchsia is not working

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43427]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=39534; conversation should occur there.

/cc @iskakaushik

**Comment by kf6gpe** [comment]
Per this week's Flutter->Fuchsia sync; @iskakaushik will try to repro this in the next couple of weeks.

**Comment by kf6gpe** [comment]
I think we should fix this soon-ish, but there are higher priority issues, so I'm downgrading this.

**Comment by apwilson** [comment]
I think this is probably obsolete.
