### ISSUE TITLE
Plugin: Network state

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4342]
Is there a way to check and monitor network connectivity in flutter? I'd love to show a warning message if we can reliably identify the user has no connectivity.

**Comment by Hixie** [comment]
"no connectivity" is very hard to define. If I'm on a subway and have a 10 Mbits connection every 5 minutes for 30 seconds, is that "no connectivity"? What about if I'm connected to a wifi network with DNS, but most packets are blocked silently? What about if I'm on a network with 90% packet loss?

I think https://github.com/flutter/flutter/issues/1051 presents a more effective long-term solution, but it's not on our near-term roadmap.

**Comment by sethladd** [comment]
However, couldn't the developer ask "do I have a link light?". I should be able to tell if I _definitely_ have no network access if I have zero "up" network interfaces.

Agreed that if I have at least one link light, that I can't assume that it means I have connectivity.

But, the absence of link lights should tell me "there's no way I have connectivity".

**Comment by eseidelGoogle** [comment]
Android:
https://developer.android.com/reference/android/net/ConnectivityManager.html
and iOS:
https://developer.apple.com/library/tvos/documentation/SystemConfiguration/Reference/SCNetworkReachabilityRef/index.html#//apple_ref/doc/uid/TP40007260
It seems reasonable to ask for a x-platform wrapper around these two.  We don't have one currently.

**Comment by abarth** [comment]
We should probably switch customer: fast over to FlutterView so that they can integrate with whatever platform services they like without needing us to turn a crank for them.

**Comment by Hixie** [comment]
@sethladd My point is that having the app work differently when there's no network (briefly) is suboptimal UI. Better to just buffer up sends, provide what cached data we have, and show an indicator that we want more data but are having trouble getting it. It's fine for apps to talk straight to the OS to find this information, but flutter's API IMHO shouldn't support that model natively, we can do better.

**Comment by sethladd** [comment]
React Native API: https://facebook.github.io/react-native/docs/netinfo.html

A plugin for Xamarin: https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/Connectivity

(There is no out-of-the-box Xamarin API for x-plat network connectivity. There is an [Android API](https://developer.xamarin.com/recipes/android/networking/networkinfo/detect_network_connection/) and an [iOS API](https://developer.xamarin.com/recipes/ios/network/reachability/detect_if_network_is_available/).)

**Comment by mehmetf** [comment]
We have this already: https://pub.dartlang.org/packages/connectivity I will tentatively close this.

**Comment by sethladd** [comment]
thanks!
