### ISSUE TITLE
Is there any way to use SkImageFilters::MatrixConvolution on an Image?

### ISSUE THREAD

**Issue by JinHoSo** [flutter/flutter#43429]
Is there any way to use SkImageFilters::MatrixConvolution on an Image?

**Comment by BondarenkoStas** [comment]
@JinHoSo I believe there is no. I think it may be considered as a feature request, please upvote https://github.com/flutter/flutter/issues/37919.

**Comment by JinHoSo** [comment]
@BondarenkoStas Thanks!
