### ISSUE TITLE
How to forbid drawer of scaffold to show by gesture

### ISSUE THREAD

**Issue by onewkl** [flutter/flutter#43423]
In some case,I don`t want the drawer show when user swipe from the edge,is there any solution?

**Comment by HansMuller** [comment]
CC @shihaohong - did we provide away to disable the swipe-to-open drawer gesture?

**Comment by shihaohong** [comment]
No, not yet. Here is the original issue for it: https://github.com/flutter/flutter/issues/31127

Please add a thumbs up there, as we track priority by the number of 👍 emojis on our GitHub issues! I'll close this issue for now

**Comment by onewkl** [comment]
> No, not yet. Here is the original issue for it: #31127
> 
> Please add a thumbs up there, as we track priority by the number of 👍 emojis on our GitHub issues! I'll close this issue for now

thx for your reply

**Comment by nelsonalexandrino** [comment]
can you try to put drawerEdgeDragWidth: 0 on you Scaffold

Scaffold(
**drawerEdgeDragWidth: 0,**
drawer: Container(width: 100),
body: Container(),
);

please let me know if this will work for you.
