### ISSUE TITLE
package:flutter/src/widgets/media_query.dart': Failed assertion: line 689 pos 12: 'context != I/flutter (30667): null': is not true.

### ISSUE THREAD

**Issue by Picdafi** [flutter/flutter#43430]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
