### ISSUE TITLE
Getting Status Code 400 and Errno = 111/113 when using http.get on local network

### ISSUE THREAD

**Issue by Tsubanee** [flutter/flutter#43441]
Every time I try to get the response from 192.168.0.5/api/device/state I obtain "Bad Request" with error numbers described by flutter as 111 or 113.

My code for making a connection : 

```
  Future<Map<String, String>> getAirSensorStatus() async {
    print("Getting Air Sensor");

    http.Response response =
        await http.get('http://192.168.0.5/api/device/state');
        print("Status code  " + "${response.statusCode}");
        print("After status code printing");
        print(response.headers);

    try {
      if (response.statusCode != 200 && response.statusCode != 201) {
        print("Something went wrong. Status not 200 and not 201 for AirSensor");
        print(response.reasonPhrase);
        print(response.body);
        return null;
      }
      final responseData = json.decode(response.body);
      print(responseData);
      return responseData;
    } catch (error) {
      print(error);
      return null;
    }
  }
```

I have 
```
<uses-permission android:name="android.permission.INTERNET"/>
```
set in manifests.

I can access the address I'm requesting in every browser I use; on desktop, and real device and on emulator. I have also tried Bash's Curl, which also does work correctly.

Any idea what causes this?

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.

**Comment by bawantha** [comment]
why did you close this ???
