### ISSUE TITLE
text_field_test.dart force-press handling leaks state between tests.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#43445]
If you run the test "tap on non-force-press-supported devices work (iOS)" in `material/text_field_test.dart`, twice in a row (i.e. just duplicate the `testWidgets` block), it will fail the second time with:

```
The following TestFailure object was thrown running a test:
  Expected: TextSelection:<TextSelection(baseOffset: 8, extentOffset: 8, affinity:
TextAffinity.downstream, isDirectional: false)>
  Actual: TextSelection:<TextSelection(baseOffset: -1, extentOffset: -1, affinity:
TextAffinity.downstream, isDirectional: false)>
```
indicating to me that there is some global state somewhere that isn't being reset between tests.

(I looked into it a bit with no luck, but I didn't want to be distracted from what I was working on, so I decided to file this issue instead and add a TODO).

**Comment by gspencergoog** [comment]
Also, the same thing is also happening in `selectable_text_test.dart` (unsurprisingly: it mostly has duplicate tests with text field). The test there is called the same thing.

**Comment by justinmc** [comment]
I couldn't repro this in text_field_test or selectable_text_test. I tried both adding the extra test to the existing ones and deleting everything except the two duplicate tests, but neither failed. @gspencergoog I will plan to close this issue unless you say otherwise.
