### ISSUE TITLE
Calculate FrameTiming::kRasterFinish correctly in Fuchsia

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#43453]
In Fuchsia, the rasterization doesn't finish when `Rasterizer::DoDraw` finishes. Future work is needed to adapt the timestamp for Fuchsia to capture `SceneUpdateContext::ExecutePaintTasks`.

See https://github.com/flutter/engine/commit/9f088c65ee69b85616ce6e2e586dc52e7de2e0cd#diff-e81d85a84b4999177209791f247205d4R176

**Comment by liyuqian** [comment]
CC @nathanrogersgoogle @fmeawad @mikejurka

**Comment by mikejurka** [comment]
CC @amott9
