### ISSUE TITLE
Android Studio 3.5 + Flutter 1.9 causes crash when viewing Flutter source code

### ISSUE THREAD

**Issue by AweiLoveAndroid** [flutter/flutter#43469]
When I click `ctrl` and mouse left-button, to see the source,but it doesn't work and crashes.
So I close the Android Studio and restart my project,but nothing to do,I can't to see source.
What's the problem?

My Flutter version like this:

```
C:\Users\Administrator>flutter doctor -v
[√] Flutter (Channel @u, v1.10.15-pre.186, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.10.15-pre.186 at E:\develop\flutter
    • Framework revision 1c535de7e0 (6 days ago), 2019-10-18 16:40:42 -0700
    • Engine revision 8aefcd8575
    • Dart version 2.6.0 (build 2.6.0-dev.8.0 a61c775db8)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\develop\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\develop\sdk
    • Java binary at: E:\develop\android-studio-ide-191.5791312_AS3.5\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at E:\develop\android-studio-ide-191.5791312_AS3.5
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 77.0.3865.90
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```

And I wait for 30 minutes,nothing to do, but I just see this  like the following screenshots:

![screenshots](https://user-images.githubusercontent.com/27602662/67537059-66ed3280-f70c-11e9-808d-77e8ed8eb4b0.PNG)

Who can help me?

**Comment by iapicca** [comment]
Hi @AweiLoveAndroid 
I understand that the issue is related to Android Studio rather than Flutter
am I correct?

Regardless, I recommend to make a fresh install following this [documentation](https://flutter.dev/docs/get-started/editor)
Thank you

**Comment by AweiLoveAndroid** [comment]
@iapicca  Thanks.I unInstall Android Studio and redownload Flutter,but nothing to do.So the newest version of Flutter is a trouble.And now I download `stable` version, it's work OK.

**Comment by AweiLoveAndroid** [comment]
But the trouble has happened today.When I want to see the source codes, but I find source codes had changed to my custom codes, so what's this problem?

This is my screenshots. So what shall I do now?

![ScreenShots](https://user-images.githubusercontent.com/27602662/69844852-ea201c00-12a8-11ea-937b-48b549cf96b1.png)


I use `Android Studio 3.5` and `Flutter  v1.9.1+hotfix.6 stable` and  `Dart version 2.5.0`.
How to solve this problem?Help me please!
I'm so worry about it.Thanks.

**Comment by AweiLoveAndroid** [comment]
Now I uninstall `Android Studio 3.5` and install the old version `Android Studio 3.4`,  it's OK now. It's amazing.Wow!As you know the `Android Studio 3.5` version doesn't support `Flutter 1.9` well.

**Comment by csells** [comment]
@devoncarew fyi

**Comment by csells** [comment]
@AweiLoveAndroid do you still have this problem when using Flutter 1.12? Have you updated to the latest version of the Flutter plugin for Android Studio?

**Comment by AweiLoveAndroid** [comment]
@csells I use Flutter 1.12,so no problems now.Thanks.
