### ISSUE TITLE
exception thrown when using slider

### ISSUE THREAD

**Issue by gitaaron** [flutter/flutter#43468]
## Steps to Reproduce

1. Click slider via simulator and start dragging.

Target Platform:iOS
Target OS version/browser:12.4
Devices:iPhone 5s simulator

## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2154 pos 12: 'attached': is not
flutter: true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2154:12)
flutter: #3      RenderBox.globalToLocal (package:flutter/src/rendering/box.dart:2244:31)
flutter: #4      _RenderSlider._getValueFromGlobalPosition (package:flutter/src/material/slider.dart:941:36)
flutter: #5      _RenderSlider._startInteraction (package:flutter/src/material/slider.dart:962:27)
flutter: #6      _RenderSlider._handleDragStart (package:flutter/src/material/slider.dart:993:54)
flutter: #7      DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:364:45)
flutter: #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
flutter: #9      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:364:7)
flutter: #10     DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:298:7)
flutter: #11     _CombiningGestureArenaMember.acceptGesture (package:flutter/src/gestures/team.dart:41:13)
flutter: #12     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:250:25)
flutter: #13     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:231:31)
flutter: (elided 12 frames from class _AssertionError and package dart:async)
flutter:
flutter: Handler: "onStart"
flutter: Recognizer:
flutter:   HorizontalDragGestureRecognizer#12ef2
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-CA)
    • Flutter version 1.7.8+hotfix.4 at /Users/asurty/Package/flutter/flutter
    • Framework revision 20e59316b8 (3 months ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/asurty/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/asurty/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone 5s • D2B8A424-C038-404C-931F-BE44F12425EB • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @gitaaron 
could you please run 
`
 flutter channel stable
`
`
 flutter upgrade
`
and provide your updated `flutter doctor -v`.

To better address the issue, would be helpful
if you could post your your `flutter run --verbose` as well.
Thank you

**Comment by HansMuller** [comment]
CC @clocksmith - seems to be a RangeSlider issue.

**Comment by gitaaron** [comment]
Hi @iapicca it is actually very hard to reproduce but I figured I would report it anyway as that what it said to do in the trace.

But anyway here is my flutter doctor -v after an upgrade on the stable channel -

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale en-CA)
    • Flutter version 1.9.1+hotfix.6 at /Users/asurty/Package/flutter/flutter
    • Framework revision 68587a0916 (7 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/asurty/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/asurty/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone 8 • 05F56DB1-2A67-4B87-89FD-CB44D7C2BBB7 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!

Thanks!

**Comment by eseidelGoogle** [comment]
I'm not sure we can easily take action on this without a reproduction.  Hans suggests its from RangeSlider, but it would be super helpful to have an example you're able to trigger it in.  Without that, I think it's probably better to just close this until we get more reports.

Thank you for reaching out!

**Comment by gitaaron** [comment]
Thanks for looking into it, Eric!
