### ISSUE TITLE
A way to bring a minimized flutter app to foreground 

### ISSUE THREAD

**Issue by MajedDH** [flutter/flutter#43478]
Is there a way in Flutter to get the application to show itself or to "maximize" itself when it receives a call in the background? the docs say nothing about this. it's just the AppLifecycleState. I don't want to detect where the app is. I want to bring the app to the foreground.

**Comment by iapicca** [comment]
I see you opened a Stackoverflow [question](https://stackoverflow.com/questions/58534450/a-way-to-get-a-minimized-app-to-foreground-in-flutter); 
that is correct approach since this platform is not met for assistance on personal code.
You may also see https://flutter.dev/community for resources for asking questions like this.
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by MajedDH** [comment]
Thank you for your fast response @iapicca. I know, Github is not a platform for personal code. I'm sorry for any inconvenience. But I'm not requesting help with my code actually. 
I've searched a lot and found nothing. And since the documentation contains nothing about this, I thought maybe this should be some kind of a feature request from the flutter team on GitHub, or at least it would be a documentation request ( Maybe? ). 

I've seen issue #4623, I know that even before I opened the issue here. That's just listening to the state of the app.  What I want is actually changing the state of the app by bringing it to the foreground/background.

Thanks.

**Comment by AteqEjaz** [comment]
Yes, finding solution for the same - Want to bring my app foreground based on server data i'm running background job for updating user location, Read the documentation but nothing explains how to bring Flutter app to foreground even if mobile screen is off or my flutter app is in background :)?

**Comment by Hixie** [comment]
This isn't really a Flutter question. You'd do the same for your app as you would for any other app on the platform you're targeting.

**Comment by MajedDH** [comment]
Just in case someone pass through here I've written the result on my small research as an answer to my question on stackoverlfow.

https://stackoverflow.com/a/61377769/2065215

And I've made a simple plugin that works on android only that can do just that: 

https://pub.dev/packages/bringtoforeground

**Comment by moho12n** [comment]
Thank you Majed for this cool plugin, the solution is not working on android 10

**Comment by MajedDH** [comment]
@moho12n Android 10 added new conditions to run Activities from services.

I don't know yet how to do it 
If I solved it I'll put it here
