### ISSUE TITLE
Test Firebase wrapper in a CI-like system

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4347]
With the codelab being a popular first entry point for Flutter, we might want to look at how to test our Firebase wrapper in a CI system. Maybe even put it on the dashboard?

**Comment by sethladd** [comment]
cc @collinjackson

**Comment by sethladd** [comment]
Closing for now.

**Comment by collinjackson** [comment]
@mit-mit @jakobr-google are looking at integration tests for plugins

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1022. Any further collaboration will be done there.
