### ISSUE TITLE
[connectivity] checkConnectivity() as list

### ISSUE THREAD

**Issue by Nico04** [flutter/flutter#43488]
## Use case
Some Android phones allows to be connected to mobile data and wifi network at the same time, thus the return value of checkConnectivity() is not accurate, it will return ConnectivityResult.mobile.

## Proposal
The return value of checkConnectivity() should be a List<ConnectivityResult> (as it is in Xamarin.Forms).

**Comment by stuartmorgan** [comment]
Closing as `connectivity` is deprecated in favor of [`connectivity_plus`](https://pub.dev/packages/connectivity_plus).
