### ISSUE TITLE
CryptoJS.AES.encrypt(plainText,key,{ iv: CryptoJS.enc.Hex.parse(iv) });

### ISSUE THREAD

**Issue by eswarvarma-dev** [flutter/flutter#43487]

**Comment by MaherKSantina** [comment]
@eswarvarma-dev any details on this?

**Comment by BondarenkoStas** [comment]
@eswarvarma-dev Please describe the issue you have, otherwise it gives no information.

**Comment by eswarvarma-dev** [comment]
hello, actually i am converting string to aes128 bit by cbc mode of pkcs5 in base64 bit

**Comment by BondarenkoStas** [comment]
@eswarvarma-dev please describe what's the issue?

**Comment by eswarvarma-dev** [comment]
i want to encrypt the data aes128bit, cbc mode, pkcs5, base64bit

i want to convert all my registration fields to encrypted data and send to service but i dont know how to do it. i am trying with some plugins of hash_password and some types but i am getting different bit length i dont know is there is any chance of converting.. actually i have wrote code from angular side. its working fine but i dont know from flutter can you help me in this 

i am attaching my angular code of encryting class file
[angular encryption.txt](https://github.com/flutter/flutter/files/3804059/angular.encryption.txt)

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
