### ISSUE TITLE
Emojis wont render when using font size greater than 85

### ISSUE THREAD

**Issue by proghjy** [flutter/flutter#43498]
When the font size is 85
<img width="603" alt="스크린샷 2019-10-25 오후 6 35 26" src="https://user-images.githubusercontent.com/3823239/67564812-6bd6d400-f756-11e9-8b57-17f78f285daa.png">

When the font size is 86
<img width="551" alt="스크린샷 2019-10-25 오후 6 36 21" src="https://user-images.githubusercontent.com/3823239/67564813-6bd6d400-f756-11e9-8b6b-e75fa39885e6.png">

Below is the SwiftUI test screen.
<img width="662" alt="스크린샷 2019-10-25 오후 6 43 06" src="https://user-images.githubusercontent.com/3823239/67565193-66c65480-f757-11e9-98de-4f10639ebbed.png">

@BondarenkoStas my `flutter doctor -v`
```terminal
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B68f, locale ko-KR)
    • Flutter version 1.9.1+hotfix.6 at /Users/paulhan/Development/flutter
    • Framework revision 68587a0916 (7 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/paulhan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (3 available)
    • SM G977N                  • R3CM70E8SKZ                          • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554                        • android-x86   • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max         • BB2E8C8D-C687-4265-8685-1E19A5D3A8FF • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!
```

**Comment by BondarenkoStas** [comment]
@proghjy please provide your flutter doctor -v output

**Comment by BondarenkoStas** [comment]
@proghjy Thank you for the report! Interesting bug. I tried with v1.9.1+hotfix.5, it run any emoji size for android, but not any greater than 128 for ios.

<img width="1125" alt="Screenshot at Oct 25 15-44-27" src="https://user-images.githubusercontent.com/18336802/67572207-6ec5ca80-f73e-11e9-94a8-0ed0a6f97d51.png">

**Comment by GaryQian** [comment]
Initial thoughts:

Is this limited to emojis? If some regular glyphs or icons are set to a massive font size, would it also disappear? If so, it would point towards something to do with maximum width/height bounds.

The way we process large fonts is that we load the glyph at fontsize 14, and then apply a scaling factor to draw it. This allows us to only read the font once for any sized font, and greatly improves performance for things like changing font sizes. This system should be able to handle arbitrarily large glyphs since we can essentially scale infinitely.

**Comment by jason-simmons** [comment]
This looks similar to https://github.com/flutter/flutter/issues/21707 and https://github.com/flutter/flutter/issues/16386.  In the past we've seen cases where some code paths used to render color bitmap fonts yielded errors when a particular size or transform was applied.

I haven't noticed this class of issue recently on Android, but Skia might act differently on iOS.

**Comment by jason-simmons** [comment]
Does the rendering error only happen on specific devices or OS versions?

I tried some emoji rendering examples (including the sample code from https://github.com/flutter/flutter/issues/21707 and https://github.com/flutter/flutter/issues/16386) using the current Flutter master on devices running iOS 9 and iOS 12.  So far I haven't seen any problems.

**Comment by GaryQian** [comment]
@proghjy We have currently been unable to repro, can you confirm you still see this?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
