### ISSUE TITLE
Text selection highlight doesn't reach down to bottom of font (on Android)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4349]
(Notice how the highlighting on Android has some padding above and below the text. Looks like Flutter's highlighting doesn't have the same padding.)

Flutter:  (notice how the bottoms of the j's aren't covered by the highlight)

![screenshot_20160603-093124](https://cloud.githubusercontent.com/assets/5479/15785801/12544052-296e-11e6-9984-447f457e55b2.png)

Android:

![screenshot_20160603-093101](https://cloud.githubusercontent.com/assets/5479/15785803/14c55ad8-296e-11e6-9be9-884c70281c3d.png)

**Comment by sethladd** [comment]
cc @mpcomplete

**Comment by abarth** [comment]
Related to https://github.com/flutter/flutter/issues/4321

**Comment by sethladd** [comment]
We reach down to the bottom of the text now, but we don't include any bottom padding.

![screen shot 2016-06-08 at 1 19 23 pm](https://cloud.githubusercontent.com/assets/5479/15909544/a6b2fd4a-2d7b-11e6-97d8-9590771dbf14.png)

**Comment by sethladd** [comment]
I looked at other iOS apps with text selection. Looks like the highlighting only extends to the bottom of the text, but no bottom padding on iOS:

![screen shot 2016-06-08 at 1 28 26 pm](https://cloud.githubusercontent.com/assets/5479/15909819/e7d99a58-2d7c-11e6-9e7c-f642d7c4bf45.png)

Since our text selection highlights to the bottom of the word, I think we can close this.

Thanks for the help in tweaking this!

**Comment by eseidelGoogle** [comment]
Selection used to be a very platform specific behavior on the web.  We may
end up having to implement different styles between iOS and Android as
well, not sure.  Certainly will end up wanting to test on both.

http://stackoverflow.com/questions/18939025/nsattributedstring-highlight-background-color-shows-between-lines-ugly
is an example of someone with a windows background/preference trying to get
the windows (don't fill between lines) effect on Mac (desktop).  I'm not
able to find a better comparison, although blogs about this stuff used to
exist somewhere. :D
