### ISSUE TITLE
`flutter` tool crash rate > 2.5%

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43503]
As of 1.10.14, the crash rate is 2.9%.

**Comment by zanderso** [comment]
There have been ~250 commits to master since 1.10.14 dev. Also, I believe several of the web crashers have been fixed on master, so we will probably get more actionable crash reports following the next dev release.

**Comment by zanderso** [comment]
Subsequent dev crash rates are down. Closing in favor of issues for specific crashes.
