### ISSUE TITLE
[local_auth] localizations are incorrect for Face authentication on pixel 4 [0.6.0]

### ISSUE THREAD

**Issue by bbedward** [flutter/flutter#43507]
Using flutter 1.9.1 and local_auth 0.6.0 the localized strings for face authentication are not correct, as demonstrated in the screenshot.

![screenshot_20191025-115234](https://user-images.githubusercontent.com/550752/67586079-cc4a1f00-f71e-11e9-851c-f1fbfdc12b9e.png)

**Comment by BondarenkoStas** [comment]
@bbedward by localization you mean fingerprint text instead of face authentication text?

**Comment by bbedward** [comment]
@BondarenkoStas yes that's correct, both the "Fingerprint authentication" and the "touch sensor" strings don't apply when using face authentication. It would be the same for Iris authentication on devices that support that.

**Comment by pythoneer** [comment]
@bbedward i wanted to reproduce your problem but i did not even manage to get the screen to pop up – my available biometrics are empty on the pixel 4 :/ I have enabled face unlock on the device. Is there anything else i need to consider? I have face unlock in other apps like lockwise from mozilla, so i think its basically enabled on the device itself to be used.

**Comment by stuartmorgan** [comment]
This was fixed in https://github.com/flutter/plugins/pull/2489
