### ISSUE TITLE
[share] (iOS) No preview of shared element in linkedIn share

### ISSUE THREAD

**Issue by Jokernight** [flutter/flutter#43502]
Hello,

On iOS, when you share a link via linkedIn App, you have the following behavior :  
![IMG_0015](https://user-images.githubusercontent.com/14136977/67574336-8602b900-f73a-11e9-8af8-c7f5d08b9ffa.PNG)

With the same code, here is the behavior with Android : 
![Screenshot_2019-10-25-15-18-41-323_com linkedin android](https://user-images.githubusercontent.com/14136977/67574515-e4c83280-f73a-11e9-90a0-f21020a39abf.png)

You can see that there is no preview of the shared article.

I don't know if it's a flutter issue or a linkedIn issue though.

Thanks by advance

**Comment by iapicca** [comment]
Hi @Jokernight 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by Jokernight** [comment]
Hi @iapicca ,

Sorry for the response time.
Here is my `flutter doctor -v` : 

`[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.5 18F132, locale
    fr-BE)
    • Flutter version 1.9.1+hotfix.6 at
      /Users/dev/Desktop/Projects/flutter/flutter
    • Framework revision 68587a0916 (6 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7141.49

[✓] Connected device (1 available)
    • iPhone de IPM • 00008020-0013151214EA002E • ios • iOS 12.4.1

• No issues found!`

Unfortunately I can't do a `flutter run --verbose` since I use flavors in iOS, it doesn't take the Scheme and end up in error.

Concerning the steps to reproduce : 

Pre-requisites : Have LinkedIn App installed on the phone and enable the share via LinkedIn

- We are on a WebView
- I click on a share button which goes to a link that my app intercept via RegEx
- I build the share object with information in my previous link
- I call Share.share()
- I choose the linkedIn and then you have the previous behavior.

To give you more details about the link here is an example of the share button link and the code to build the share object and then share it.

Example Link : 
https://www.dhnet.be/partage?title=La+Belgique+très+loin+dans+le+classement+des+pays+les+plus+sûrs%3A+"Vu+la+taille+de+notre+pays%2C+nous+sommes+défavorisés"&url=https%3A%2F%2Fwww.dhnet.be%2Factu%2Fbelgique%2Fvoyager-en-securite-la-belgique-absente-du-top-50-des-pays-les-plus-surs-5db805f8d8ad58388722ac5f

(This link lead to a 404 not found since it's intercepted by the app and prevent the navigation in order to avoid this 404)

Here is the function to launch the share plugin : 
`
void shareTool(url) {
    var regexUrl = new RegExp("url=(https?.+\$)");
    var regexTitle = new RegExp("title=(.*)&");
    String title = "";
    String urlText = "";
    if(regexTitle.allMatches(url).length > 0){
      title = Uri.decodeQueryComponent(regexTitle.allMatches(url).first.group(1));
    }
    if(regexUrl.allMatches(url).length > 0) {
      urlText = Uri.decodeFull(regexUrl.allMatches(url).first.group(1));
    }
    if(urlText != "") {
      if(title == ""){
        Share.share(urlText,subject: "");
      } else {
        Share.share(title+" - "+urlText,subject: title);
      }
    } else {
      print("nothing found");
    }
  }
`
So with this function and the example link I will share "title - url".

Thanks by advance !

**Comment by Jokernight** [comment]
Up ?

**Comment by iapicca** [comment]
Hi @Jokernight 
are you experiencing the issue with the latest stable version of flutter
and the latest version of share plugin?
Thank you

**Comment by Jokernight** [comment]
Hi @iapicca,

Sorry for the time of answer, I have just tested with the last stable version of flutter (1.12.13+hotfix.8) and the last version of share plugin (0.6.3+6) and I still have the same issue on iOS.

Thanks.

**Comment by Pathtek** [comment]
Hello guys, I ran into a similar issue on linkedIn with Share package where preview didn't render the card with metadata, instead it was publishing a link shortened (really ugly).
I will explain what I did and I hope this will help you.

First I forked flutter plugins: https://github.com/flutter/plugins

Then I opened file plugins/packages/share/ios/Classes/FLTSharePlugin.m

I edited the file like this:

```
@property(readonly, nonatomic, copy) NSURL *text;

- (instancetype)initWithSubject:(NSString *)subject text:(NSURL *)text NS_DESIGNATED_INITIALIZER;
```
```
- (instancetype)initWithSubject:(NSString *)subject text:(NSURL *)text {
  self = [super init];
  if (self) {
    _subject = subject;
    _text = text;
  }
  return self;
}
```
```
+ (void)share:(NSString *)shareText
           subject:(NSString *)subject
    withController:(UIViewController *)controller
          atSource:(CGRect)origin {
  NSURL *url = [NSURL URLWithString:[shareText stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]];
  ShareData *data = [[ShareData alloc] initWithSubject:subject text:url];
  UIActivityViewController *activityViewController =
      [[UIActivityViewController alloc] initWithActivityItems:@[ data ] applicationActivities:nil];
  activityViewController.popoverPresentationController.sourceView = controller.view;
  if (!CGRectIsEmpty(origin)) {
    activityViewController.popoverPresentationController.sourceRect = origin;
  }
  [controller presentViewController:activityViewController animated:YES completion:nil];
}
```
UIActivityViewController will now know that you're giving it a URL and not just Text

Commit the changes and push it to your forked project

Add to your dependencies in file pubspec.yaml:
```
share:
    git:
      url: git://github.com/Your_Company/plugins.git
      path: packages/share
```
execute flutter pub get and pod install and now this should display your preview on linkedIn sharing !
Hope this will fix your issue !
