### ISSUE TITLE
Did not infer the type of T

### ISSUE THREAD

**Issue by incker** [flutter/flutter#43506]
Hello, I think if Dart is a compiled language, this code have to work

    import 'dart:async';
    import 'dart:convert';
    
    void main() {
      Future<String> queryOne() async {
        return "{\"test\":true}";
      }
    
      Future<String> queryTwo() async {
        return "[1,2,3]";
      }
    
      T parseJson<T>(String resp) {
        const json = const JsonCodec();
        return json.decode(resp);
      }
    
      // THIS IS COMPILING
      Future<Map<String, dynamic>> isCompiningOk() {
        return queryOne().then(parseJson);
      };
    
      // THIS IS NOT
      queryOne().then(parseJson).then((Map<String, dynamic> onValue) {
        return 1;
      });
    
    }

**Comment by stuartmorgan** [comment]
Issues with Dart itself should be filed at https://github.com/dart-lang rather than in the Flutter repository.
