### ISSUE TITLE
Explore removing the Expat dependency

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#43517]
Expat is used by Skia for parsing font manifests on Android exclusively.  In the latest build it takes up about 65kb uncompressed (https://storage.googleapis.com/flutter_infra/flutter/5a4bd0de69fbceb36ccecfcbf8c81dc8d94ea949/android-arm64-release/sizes/index.html).

We should verify that it's not getting bundled into non-Android builds (I believe it's not but it's been a while since I've checked). We should also explore whether we could slim this down - i.e. by using a different XML parsing implementation that may be smaller, or by using JNI to get the data instead.  Relevant part of Skia is: https://github.com/google/skia/blob/master/src/ports/SkFontMgr_android_parser.cpp - some BUILD info would have to change as well to make this work in Skia.

Related bug: https://github.com/flutter/flutter/issues/40220

This would have the added benefit of resolving the expat portion of https://github.com/flutter/flutter/issues/39532

/cc @xster @chinmaygarde @matthew-carroll @mklim @jason-simmons

**Comment by chinmaygarde** [comment]
I can confirm that this dependency is only necessary and used on Android. It'd also be helpful if the compressed size saving were listed in this bug. Not all dependencies compress the same and it'd be helpful to gather both numbers so that the relative priorities of binary size reduction efforts can be determined more easily.

**Comment by dnfield** [comment]
Based on a very rough experiment (removing expat from the includes in Skia and ripping /commenting out all code that refers to exports from it), it saves almost 50kb compressed.

**Comment by dnfield** [comment]
(that's for arm64)

**Comment by dnfield** [comment]
Also a bit concerning: https://github.com/aosp-mirror/platform_frameworks_base/blob/master/data/fonts/fonts.xml#L3-L9

This warning has been around for a while, and the API that was going to resolve it was removed. Probably worth checking with the Android team about what the recommended path is.

**Comment by dnfield** [comment]
It seems like https://developer.android.com/ndk/reference/group/font#asystemfontiterator_open would be a preferable approach (and would require no XML parsing), but not clear to me what API/NDK version it was added in...

**Comment by dnfield** [comment]
Ugh.  Added in API 29 (Q). Implementation is here: https://github.com/aosp-mirror/platform_frameworks_base/blob/master/native/android/system_fonts.cpp

**Comment by dnfield** [comment]
Filed https://bugs.chromium.org/p/skia/issues/detail?id=9575

**Comment by chinmaygarde** [comment]
@dnfield Given that we are only using the dependency where necessary and there are no other alternatives[1], there doesn't seem to be anything actionable w.r.t this issue. Can this be closed?

[1] Unless you are still exploring slimmer alternatives. I am not sure we want to be in the business of writing XML parsers on our own TBH.

**Comment by dnfield** [comment]
I don't think we need this bug anymore.  There might be a slimmer XML library available but that would probably be something to explore in Skia.
