### ISSUE TITLE
Platform Exception

### ISSUE THREAD

**Issue by sandeepinigithub** [flutter/flutter#43514]
I/flutter (15360): Error signing in: PlatformException(sign_in_required, com.google.android.gms.common.api.ApiException: 4: 4: , null)

**Comment by sandeepinigithub** [comment]
![PlatformException](https://user-images.githubusercontent.com/46392691/67593498-e36d2900-f77f-11e9-841c-9114baed7405.JPG)

**Comment by BondarenkoStas** [comment]
Duplicate of #36041
