### ISSUE TITLE
how to fit one of Tab bar's tab to its child(for example an icon)

### ISSUE THREAD

**Issue by emmabahte** [flutter/flutter#43516]
Hi
how can I reduce one of Tabbar's tab to its child?
for example, here I want to reduce tab's width to icon's width
![Screenshot_1572026627](https://user-images.githubusercontent.com/50495316/67593578-50c48e00-f76f-11e9-98d1-acd38a089f17.png)

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
