### ISSUE TITLE
Animated Diagrams for AnimatedList & SliverAnimatedList

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#43521]
https://github.com/flutter/flutter/pull/42485 re-landed SliverAnimatedList. It also added sample apps for SliverAnimatedList and AnimatedList. Now that these changes have landed, it would be nice to plug these sample apps into the diagram generator in assets-for-api-docs to include visual samples. :)

**Comment by Piinks** [comment]
@brianegan Are you interested in adding this to your next batch? :)

**Comment by pedromassangocode** [comment]
Hi @Piinks 
Are you talking about those interactive app in the API docs of the classes you mentioned above? I yes, can we close this issue as fixed?

### AnimatedList
https://api.flutter.dev/flutter/widgets/AnimatedList-class.html


<img width="500" alt="Screen Shot 2020-09-10 at 15 05 54" src="https://user-images.githubusercontent.com/67424416/92742068-2d023a80-f377-11ea-8bf6-37b09f32ee1b.png">

### SliverAnimatedList
https://api.flutter.dev/flutter/widgets/SliverAnimatedList-class.html

<img width="500" alt="Screen Shot 2020-09-10 at 15 09 35" src="https://user-images.githubusercontent.com/67424416/92742593-b0239080-f377-11ea-8460-05fb00bdba4f.png">

**Comment by Piinks** [comment]
Awesome! Yes, thank you!
