### ISSUE TITLE
[web]: Generate a sitemap.xml from named routes at compile time

### ISSUE THREAD

**Issue by AppleEducate** [flutter/flutter#43523]
## Use case

Since there are not static pages in the the folder the google search crawler does not properly index the flutter web site. 

## Proposal

SInce we name the named routes ahead of time when you run `flutter build web` there could be a sitemap.xml generated at compile time copied to the build folder.

Docs: https://support.google.com/webmasters/answer/183668?hl=en

**Comment by jonahwilliams** [comment]
We don't actually know the names routes at compile time - they have to be determined by executing your code. This of course leads to all sorts of issues like environmental differences or generally halting problem style complexity.

**Comment by AppleEducate** [comment]
Makes sense. I thought the routes could be parsed. But if that’s the case, is there anything that could be done in the build process?

**Comment by AppleEducate** [comment]
Or do you think this should be a plugin suited well for a build runner? I think the second is a better option.

**Comment by jonahwilliams** [comment]
build_runner seems like a good fit - I could imagine taking some config file or annotated dart code and generating both a MaterialApp route map and a sitemap.xml or similar.

**Comment by AppleEducate** [comment]
Yeah exactly! Alright cool, I’ve been looking at doing a build runner package. I’ll see what I can come up with!

**Comment by yjbanov** [comment]
Looks like this will be a separate package, so closing.

**Comment by Prajwal-Koirala** [comment]
> Looks like this will be a separate package, so closing.

what package?/

**Comment by alonhh** [comment]
Whats the best way to archive this?

**Comment by Gene-Dana** [comment]
Hi from 2021 ! Did this ever get built?
