### ISSUE TITLE
Dartpad examples for SliverAppBar & FlexibleSpaceBar (#42250) 

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#43522]
https://github.com/flutter/flutter/pull/42250 will introduce new features for SliverAppBar and FlexibleSpaceBar. The change already includes sample apps for both classes. It would be nice to plug these sample apps into the diagram generator in assets-for-api-docs to include visual samples. :)

This will need the change to have landed before the visuals can be generated.

**Comment by Piinks** [comment]
@brianegan Are you interested in adding this to your next batch? :)

**Comment by pedromassangocode** [comment]
Is this still a valid issue?

**Comment by Piinks** [comment]
> Is this still a valid issue?

`Tis! Thanks! 

Just checked, the FlexibleSpaceBar class has a dartpad sample, but the scroll physics are wrong to illustrate the feature. they should be `BouncingScrollPhysics(parent: AlwaysScrollableScrollPhysics())`
https://api.flutter.dev/flutter/material/FlexibleSpaceBar-class.html

For the SliverAppBar class, there are no dartpad samples yet.
https://api.flutter.dev/flutter/material/SliverAppBar-class.html

**Comment by Alabhya268** [comment]
Hi @Piinks , I can write dartpad sample for SilverAppBar, how can i contribute to dartpad sample?

**Comment by Piinks** [comment]
Hi @Alabhya268, you are most welcome to! Please read our contributor guide first: https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md
Once you are ready to create your pull request, you can add sample code inline with the classes, like this dartpad sample here: https://github.com/flutter/flutter/blob/b6c56fdeafc0aa5436842205c1426b6716d5ab7e/packages/flutter/lib/src/widgets/sliver_fill.dart#L206

**Comment by Alabhya268** [comment]
> > Is this still a valid issue?
> 
> `Tis! Thanks!
> 
> Just checked, the FlexibleSpaceBar class has a dartpad sample, but the scroll physics are wrong to illustrate the feature. they should be `BouncingScrollPhysics(parent: AlwaysScrollableScrollPhysics())`
> https://api.flutter.dev/flutter/material/FlexibleSpaceBar-class.html
> 
> For the SliverAppBar class, there are no dartpad samples yet.
> https://api.flutter.dev/flutter/material/SliverAppBar-class.html

@Piinks I've opened a PR to add dartpad example for SliverAppBar , Please have a look .

**Comment by Abhishek01039** [comment]
@Piinks. I guess now this issue should be closed.

**Comment by pedromassangocode** [comment]
Closing this as fixed by https://github.com/flutter/flutter/pull/70382. Thanks!
