### ISSUE TITLE
Does flutter need to clean up crash logs at some point?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4353]
A customer just got this:
`
Jun  3 11:04:37 iPhone ReportCrash[1161] <Warning>: Report of type '109(109_Runner)' not saved because the limit of 25 logs has been reached
`
If iOS stops saving logs after some point due to us re-using the name runner, that seems bad.  Maybe `flutter` should do something to help here?

@chinmaygarde @tvolkert

**Comment by tvolkert** [comment]
A quick Google search turns up that the only way to force the removal of crash reports is for the user to manually do it in Xcode or by [syncing their device using iTunes](http://stackoverflow.com/questions/13869038/how-can-i-delete-ios-crash-reporter-logs-off-the-device)...

**Comment by Hixie** [comment]
@cbracken says we should look into what other frameworks do (e.g. Xcode itself). It would make sense to match platform conventions.

**Comment by jmagman** [comment]
The Runner rename part of this should be fixed with https://github.com/flutter/flutter/issues/41793, applications won't all be named Runner.  However if the same app crashes 25 times they'll have the same problem.

**Comment by Hixie** [comment]
Closing because this has not proved to be an issue with much customer need in practice, and it's not really a Flutter issue.
