### ISSUE TITLE
Transparent BottomNavigationBar

### ISSUE THREAD

**Issue by WilkerOliveira** [flutter/flutter#43537]
Hi,

I have to set my BottomNavigationBar transparent. Is there a way to do this?

That is what I am trying to do.

<img width="579" alt="Screen Shot 2019-10-25 at 18 15 51" src="https://user-images.githubusercontent.com/34557278/67605122-d0dcfa80-f753-11e9-987f-aaff7ecc9618.png">

Thanks in advance.

**Comment by jamesdixon** [comment]
You can do something like...

```dart
BottomNavigationBar(
          backgroundColor: Colors.black.withOpacity(0.5),
);
```

**Comment by WilkerOliveira** [comment]
> You can do something like...
> 
> ```dart
> BottomNavigationBar(
>           backgroundColor: Colors.black.withOpacity(0.5),
> );
> ```

Thanks @jamesdixon, but it doesn't work, I already tried it.

I only got this effect using this code (https://stackoverflow.com/questions/54366982/transparent-bottom-navigation-bar-in-flutter)

``` 
Stack(
        children: <Widget>[
          Container(
            width: MediaQuery.of(context).size.width,
            height: MediaQuery.of(context).size.height,
            decoration: BoxDecoration(
                image: DecorationImage(
                    fit: BoxFit.fill,
                    image: NetworkImage(
                        "https://images.freeimages.com/images/large-previews/e4a/surf-3-1378236.jpg"))),
            child: SingleChildScrollView(
              child: Column(
                children: listWidget,
              ),
            ),
          ),
          Align(
              alignment: Alignment.bottomCenter,
              child: Theme(
                  data: Theme.of(context)
                      .copyWith(canvasColor: Colors.transparent),
                  child: BottomNavigationBar(
                    backgroundColor: Color(0xff0c1241).withOpacity(0.8),
                    elevation: 1.0,
                    selectedItemColor: Colors.blue,
                    unselectedItemColor: Colors.yellow,
                    currentIndex: _selectedIndex,
                    onTap: _onItemTapped,
                    items: [
                      BottomNavigationBarItem(
                          icon: Icon(Icons.home), title: Text('Home')),
                      BottomNavigationBarItem(
                          icon: Icon(Icons.home), title: Text('Home')),
                      BottomNavigationBarItem(
                          icon: Icon(Icons.home), title: Text('Home'))
                    ],
                  ))),
        ],
      ), 
```

**Comment by jamesdixon** [comment]
I'm not sure why it's not working for you as I tried it in my own app and it works as expected 🤷🏼‍♂️

**Comment by jamesdixon** [comment]
@WilkerOliveira 
![image](https://user-images.githubusercontent.com/110114/67625487-194ff300-f7fc-11e9-924b-54a71fcbeec8.png)

**Comment by WilkerOliveira** [comment]
> @WilkerOliveira
> ![image](https://user-images.githubusercontent.com/110114/67625487-194ff300-f7fc-11e9-924b-54a71fcbeec8.png)

@jamesdixon Did you try to put something behind BottomNavigationBar and make sure you could see it?

I think the BottomNavigationBar will hide it.

**Comment by LondonITGeek** [comment]
Setting the elevation to zero on the bottomNavbar will remove the "shadow"
