### ISSUE TITLE
shared preferences get values of old android app

### ISSUE THREAD

**Issue by LasseRosenow** [flutter/flutter#43539]
I have a old android app and right now I'm rewriting it in flutter. On my old app I have some important data stored in shared preferences, but if I install my new flutter app ontop of the old android app, the shared preferences plugin says that there aren't any keys.

Is there any way to get my old preferences?

## Steps to Reproduce

1. Create a shared preference key and value inside a old classic android app
2. install a new flutter app with the same package name and a higher version code on top of the old app
3. list all keys with the shared preferences plugin

**Target Platform:** Android
**Devices:** Android Phone

**Comment by awanishraj** [comment]
Hi @lazylazyllama, did you find a solution to this issue?

**Comment by lazylazyllama** [comment]
> Hi @lazylazyllama, did you find a solution to this issue?

No :(

**Comment by stuartmorgan** [comment]
Closing as resolved, as there's now the ability to remove the prefix that used to be internally appended to all keys, as documented in the readme of the latest version.
