### ISSUE TITLE
CupertinoDynamicColor extending Color is confusing

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#43533]
`CupertinoDynamicColor` should not extend `Color`. More generally we should treat `Color` as a sealed class. Instead, it should either wrap or generate a `Color` object. There are several non-obvious gotchas associated with extending `Color`:

* Setting `CupertinoDynamicColor` to a `Paint` and reading it back will silently change the type. This applies to anything else that takes and returns a `Color` (you need to know the implementation to really know).
* In order to interpret `Paint.color` correctly the engine must convert it (there's currently a bug in the Web engine because it assumed `Color` was not extended; the fix is [smelly](https://github.com/flutter/engine/pull/13359)).

More generally, when you pass `CupertinoDynamicColor` as a `Color` to anything then read it back, it immediately becomes unsafe code, as it requires a runtime downcast from `Color`, which may or may not succeed (e.g. it will succeed in the `BoxDecoration` case, but not in the `Paint` case, or when you pipe it through `Color.lerp`). However, if all we do is turn `CupertinoDynamicColor` to a `Color` in the end, then a `CupertinoDynamicColor.toColor` would suffice and the intent would be much clearer in code.

This also has a global performance impact as it makes `Color` a virtual class. For example, `color.value` requires dynamic dispatch. In the future, when Dart gains unboxed types, we won't be able to unbox `Color` because of unknown object size.

I realize that changing type hierarchy is a breaking change, but I think in this case it's worth it.

/cc @LongCatIsLooong @ferhatb

**Comment by yjbanov** [comment]
I think a combination of union types (https://github.com/dart-lang/language/issues/145) and sealed classes (https://github.com/dart-lang/language/issues/11 but at the language level) would have prevented this issue. This is how:

* **Sealed classes**: the `Color` class would be marked as `sealed` and therefore `CupertinoDynamicColor` would not have been able to extend it in the first place.
* **Union types**: one of the requirements for introducing `CupertinoDynamicColor` was to not break existing API. This means that Cupertino classes that used to take `Color` should continue to be able to take `Color`. Union types would allow us to change the signature from `Color` to `Color | CupertinoDynamicColor`. The implementation would switch on the type and implement the appropriate logic.

Other classes that are in danger to being broken in this way but luckily haven't been broken yet:

* `Path` - the engine maintains private fields in this class, and extending it will break the engine in an obscure way.
* `Rect`, `RRect`, `Radius`, `Offset`, `Size` - these classes are in the same category as `Color`. In other languages these would be "data classes" (Kotlin), structs (Rust, C), or final classes (Java).

This is similar to `String`, `int`, `bool`, and `double` classes from `dart:core`, for which the Dart runtime has intrinsics. To do that the languages seals them in the language spec itself. We'd like to implement similar intrinsics for some of our `dart:ui` classes but can't.

/cc @leafpetersen

**Comment by HansMuller** [comment]
ColorSwatch, which has been around for years and is the basis for MaterialColor, also extends Color.

Maybe it's not ColorSwatch or CupertinoDynamicColor that's broken, but Paint.color.

**Comment by yjbanov** [comment]
In that case `ColorSwatch` and `MaterialColor` are confusing too (and probably would also fail if we had a similar test to the one we have for cupertino). Although they actually do not override anything from `Color` (`CupertinoDynamicColor` does), so I'm not sure why they need to extend `Color` at all. They just end up sharing the problem of not surviving transformations, such as `lerp` or `Paint.color`.

I think this would be my preferred class hierarchy:

```dart
sealed class Color;

abstract class ThemeColor {
  Color toColor();
}

class ColorSwatch implements ThemeColor;
class MaterialColor extends ColorSwatch;
class CupertinoDynamicColor implements ThemeColor;
```

Whenever you want to pass a `ThemeColor` to the engine (via `dart:ui`) you first call `toColor`. On the engine side we want to be able to assume things about object representations defined in `dart:ui`.

However, with `ColorSwatch` and `MaterialColor` in the mix, I realize this would be a much more breaking change.

**Comment by yjbanov** [comment]
Chatted with @HansMuller in person. Looks like changing this will make things more painful on the framework side. So instead, we'll create a specialized private class inside the engine for `Color`, which won't be extensible in the framework, and use that instead.

It doesn't solve the issue with color transformations, but it should be enough for making engine-side optimizations without introducing correctness bugs.
