### ISSUE TITLE
Flutter requires Android SDK 28 and the Android BuildTools 28.0.3, but my laptop installed version 29? is that okay?

### ISSUE THREAD

**Issue by fritssasia** [flutter/flutter#43536]
###Flutter doctor

```
[!]  Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/fritssasia/Apps/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        "/home/fritssasia/Apps/sdk/tools/bin/sdkmanager" "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.dev/setup/#android-setup for detailed instructions.
    • All Android licenses accepted.
```

**Comment by josonchen** [comment]
1)   Android Studio --  SDK Manager -- SDK Platforms  -- pie
2)  Android Studio  --  SDK Manager -- SDK Tools --show Package Details--28.0.3

![Flutter requires Android SDK 28 and the Android BuildTools 28 0 3](https://user-images.githubusercontent.com/924845/78034266-130d0680-739a-11ea-94da-21f7578cd467.png)

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community
