### ISSUE TITLE
Create a plugin for loading iOS assets

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#43549]
Create a plugin specifically for loading iOS assets in Flutter.

**Comment by matthew-carroll** [comment]
CC @xster @blasten

**Comment by gaaclarke** [comment]
https://github.com/gaaclarke/native_images . I wrote the plugin for iOS here.  It does what we want and we just need to decide if it is the best packaging.

**Comment by xster** [comment]
Once it's in flutter/plugins, add reference to it in https://github.com/flutter/website/blob/staging-add-to-app-do-not-delete-until-2020/src/docs/development/add-to-app/ios/add-flutter-screen.md and https://github.com/flutter/website/blob/master/src/docs/development/ui/assets-and-images.md

**Comment by xster** [comment]
This is at https://github.com/flutter/plugins/tree/master/packages/ios_platform_images now.
