### ISSUE TITLE
Better error message for flutter --version crash: xcrun: error: invalid active developer path

### ISSUE THREAD

**Issue by Supremvanam** [flutter/flutter#43565]
```
Suprems-MacBook-Pro:~ supremvanam$ flutter --version
xcrun: error: invalid active developer path (/Applications/Xcode.app/Contents/Developer), missing xcrun at: /Applications/Xcode.app/Contents/Developer/usr/bin/xcrun

Oops; flutter has exited unexpectedly.
Crash report written to /Users/supremvanam/flutter_12.log;
please let us know at https://github.com/flutter/flutter/issues.
Suprems-MacBook-Pro:~ supremvanam$ 
```

**Comment by Supremvanam** [comment]
I have tried "xcode-select --install", but it didn't help.

Reference:
https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa

**Comment by cbenhagen** [comment]
If you are not prompted to install the Command Line Tools with `xcode-select --install` you can download them from here: https://developer.apple.com/download/more/. Make sure you restart your terminal after installing them.

**Comment by BondarenkoStas** [comment]
@Supremvanam please provide your flutter doctor -v output.
https://github.com/flutter/flutter/issues/43280#issuecomment-545612806
try with following it with `brew update`

**Comment by jmagman** [comment]
Did you run:
```
sudo xcodebuild -runFirstLaunch
```
https://flutter.dev/docs/get-started/install/macos#install-xcode

We should catch this crash and suggest that command.  Can you paste /Users/supremvanam/flutter_12.log so we can see the exact stack?

**Comment by jmagman** [comment]
This issue is tracking giving a better error message from the tool.
