### ISSUE TITLE
`flutter run --debug` crashes on iOS devices

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4357]
This is some sort of Dart-roll/DBC regression I think.

```
cd flutter/examples/flutter_gallery
flutter run --debug
```

`flutter run --release` works fine.

@chinmaygarde

**Comment by chinmaygarde** [comment]
@eseidel Its because of the hardcoded `--release` flag in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/bin/xcode_backend.sh#L53. Fixing.

**Comment by eseidelGoogle** [comment]
Here is a crash log:
https://gist.github.com/eseidelGoogle/8d1cdb5c5778ba892194c26a0f8c6bde

**Comment by eseidelGoogle** [comment]
@chinmaygarde looks like that line is specific to AOT?

**Comment by chinmaygarde** [comment]
Ok. I was fixing profile mode. Thought this was the same issue. Looking at this too.

**Comment by abarth** [comment]
Looks like @chinmaygarde fixed this.
