### ISSUE TITLE
Make Default behaviour of "There are multiple heroes that share the same tag within a subtree." not to break the app.

### ISSUE THREAD

**Issue by anjrew** [flutter/flutter#43587]
## Use case
When there are multiple heroes that share the same tag within a subtree, the screen goes white making the app unusable.

## Proposal

Make the default behaviour ignore the heroes in the case of multiple heroes that share the same tag within a subtree.

**Comment by goderbauer** [comment]
That would make it very easy to introduce unintended bugs.
