### ISSUE TITLE
Need a way to discover FlutterViews on iOS devices

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4358]
For android @jason-simmons created a `flutter discover` command which can connect to running android apps with FlutterViews (similar to how Chrome's inspector can connect to apps on android running WebView's).  This allows authors to build and install their apps (using flutter) with whatever tools they like and yet still be able to connect and use flutter's tooling with their already-built app.

This is important for integrating with Google's internal build systems as well as whatever other build systems others might chose to use to build their app.

https://github.com/flutter/flutter/commit/00c7734c8ba983564be97b5ad8fc2abcc8de65f5

FYI @tvolkert

**Comment by Hixie** [comment]
This could help build #5043.

**Comment by xster** [comment]
Sounds like this will be fixed with https://github.com/flutter/packages/pull/7 and `flutter attach`

**Comment by jmagman** [comment]
@xster Is this done then?

**Comment by xster** [comment]
Yes, flutter attach is now available and also integrated in IDEs.
