### ISSUE TITLE
Make Flutter Gallery integration tests work on iPhone

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#4359]
Today we are able to successfully run the following integration test on physical Android devices and on iOS Simulator, but not on a physical iPhone:

```sh
cd examples/flutter_gallery
flutter drive -t test_driver/transitions_perf.dart
```

This is a prerequisite for https://github.com/flutter/flutter/issues/1600

**Comment by sethladd** [comment]
Are we blocked on https://github.com/flutter/flutter/issues/4418 and/or something else? Can we list the blocker issues in this issue's description?

**Comment by chinmaygarde** [comment]
Fixed in https://github.com/flutter/flutter/pull/4575

**Comment by yjbanov** [comment]
@chinmaygarde github tip: if you say "Fixes #ISSUE_NUMBER" anywhere in your PR number, then github will automatically close the issue for you
