### ISSUE TITLE
Building using VS2019 causes error - Angle needs to be updated.

### ISSUE THREAD

**Issue by napana** [flutter/flutter#43592]
It is necassary to update flutter engine DEPS with Angle commit at least bf4268a3963ba5a559a73c8ca442988c3a0dd445 to allow building flutter on Windows using VS2019.

![image](https://user-images.githubusercontent.com/57046101/67634074-d6ebec00-f8b7-11e9-91de-3181fa5d148f.png)

[Angle Commit "Fix misc VS2019 bool conversion warnings"](https://github.com/google/angle/commit/bf4268a3963ba5a559a73c8ca442988c3a0dd445#diff-3c3addc27516fde4f5a960487cd2ea58)

[VS2019 c4800](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4800?view=vs-2019)

**Comment by darshankawar** [comment]
@napana 
Is this still a valid issue using latest Flutter version ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
