### ISSUE TITLE
something with the build.gradle on the android app module (flutter)

### ISSUE THREAD

**Issue by ElsaiedSamaka** [flutter/flutter#43593]
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "E:\FlutterApps\flash-chat-flutter\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\FlutterApps\flash-chat-flutter\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 59s
  Command: E:\FlutterApps\flash-chat-flutter\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.
```

**Comment by ElsaiedSamaka** [comment]
![Captur3e](https://user-images.githubusercontent.com/53364768/67635349-b11e1180-f8ce-11e9-8e5c-6bdd125142ed.PNG)
![Capture1](https://user-images.githubusercontent.com/53364768/67635351-b3806b80-f8ce-11e9-885c-bdd123fa99f6.PNG)
![Capture2](https://user-images.githubusercontent.com/53364768/67635353-b54a2f00-f8ce-11e9-9a67-3a9bbe75bc3a.PNG)

**Comment by lunaticcoding** [comment]
Hello @ElsaiedSamaka,
please paste your flutter doctor -v output. :) 

Also I see that you already have a few Screens in your lib folder. Does this mean that the app was working correctly until you made some changes? Or is this your first build (for this project)?

**Comment by BondarenkoStas** [comment]
@ElsaiedSamaka please check https://github.com/flutter/flutter/issues/41492#issuecomment-536112970.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
