### ISSUE TITLE
[google_sign_in] How to verify the identity of the user on server?

### ISSUE THREAD

**Issue by NimishDavid** [flutter/flutter#43596]
I am using REST api for authentication in my Flutter project. The google_sign_in package authenticates the user in my app, but how do I communicate this to my server? Does it return something like a token?

**Comment by SBNTT** [comment]
```dart
final account = await googleSignIn.signIn();
final auth = await account?.authentication;
final token = auth.idToken;

if (token == null) {
  // error
}

// send token to your backend
```

To check the token on your backend:
[https://developers.google.com/identity/sign-in/web/backend-auth](url)

**Comment by NimishDavid** [comment]
> minimal example
> 
> ```dart
> final account = await googleSignIn.signIn();
> final auth = await account?.authentication;
> final token = auth.idToken;
> 
> if (token == null) {
>   // error
> }
> 
> // send token to your backend
> ```
> 
> To check the token on your backend:
> [https://developers.google.com/identity/sign-in/web/backend-auth](url)

Thanks alot!

**Comment by BondarenkoStas** [comment]
Thanks @NimishDavid ! Now I think it's safe to close the issue.
