### ISSUE TITLE
Can’t create multiple tables for one data base on Sqflite 

### ISSUE THREAD

**Issue by LeoJuanZ** [flutter/flutter#43606]
Hi, first of all, im from Venezuela so the variables in my program are on spanish, sorry for that, i have this problem that i want to do a data base on Sqflite where i need multiple tables, but i don’t understand how to make the tables for a same data base, i’ve searched many tutorials and all that i found it’s how to make one data base with one table, i know that’s because Sqlite don’t let you make more than one instance at the same time.

For what i’ve tried so far, im developing an app register for sponsors, employes, reports and other things that manage a organization, i need one table for each process (not only those, theres plenty more tables) that will be registered on the app, but the syntax that im using won’t let me make more tables than one, or at least i don’t know how, here’s my dart [project.](https://mega.nz/#!zoh2WSCT!XMcaVsgGG6mMhWXxSsNGrH5c8mAfFIyWzQY_iwJ_eEs)

this is the code im handling to make the data base:

```
class ClientDatabaseProvider{
ClientDatabaseProvider._();

static final ClientDatabaseProvider db = ClientDatabaseProvider._();
Database _database;

Future get database async {
if(_database != null) return _database;
_database = await getDatabaseInstanace();
return _database;
}

Future getDatabaseInstanace() async {
Directory directory = await getApplicationDocumentsDirectory();
String path = join(directory.path, “Patrocinante.db”);
return await openDatabase(path, version: 1,
onCreate: (Database db, int version) async {
await db.execute(“CREATE TABLE Patrocinante (”
“id integer primary key,”
“name TEXT,”
“phone TEXT,”
“tipoindustria TEXT,”
“nit TEXT,”
“aliado TEXT,”
“direccion TEXT,”
“pais TEXT,”
“estado TEXT,”
“ciudad TEXT,”
“codigopostal TEXT,”
“email TEXT,”
“paginaweb TEXT,”
“bolsaempleo TEXT,”
“referido TEXT,”
“masinfo TEXT,”
“exterior TEXT,”
“phone2 TEXT”
“)”);
});
}
```

And i want to create another table like this:

```
db.execute(“CREATE TABLE Usuario (”
“id integer primary key,”
“username TEXT,”
“password TEXT,”
“nivel TEXT,”
“)”);
});
}
```

And also have the posibility to add another tables, or it is viable to just put all attributes of all tables into one big table of the data base? because i don’t seem much of a solution, another way could be to link my already [created data base on SqLite](https://mega.nz/#!HxAyVAib!I1H774tP5lwwLs6vXG7gV_nSbRnutDlfzJtNpkoG5kM) but in that case, how can i make the code so it ressemble this app af it is, connecting with the already created data base?

**Comment by SBNTT** [comment]
Try to add 

```dart
db.execute(“CREATE TABLE Usuario (”
“id integer primary key,”
“username TEXT,”
“password TEXT,”
“nivel TEXT,”
“)”);
});
}
```

just after the `await db.execute(“CREATE TABLE Patrocinante ()` statement
Sqlite databases can have multiple tables

**Comment by BondarenkoStas** [comment]
Thank you @SBNTT ! @LeoJuanZ Sqflite is a third-party plugin, not a Flutter project. If the answer won't help please consider to ask it on StackOverflow on in https://github.com/tekartik/sqflite/issues. Closing the issue and thank you for understanding.

**Comment by AgutuSam** [comment]
Hi.
I needed to create more than just multiple tables; but multiple database. I have since developed a dart package; [sqlite_at_runtime](https://pub.dev/packages/sqlite_at_runtime) that stretches to as far as creating all these entities at run time.

Below is an example code that creates three tables with similar attributes.
`await Sqlartime.tableCreate(['sample1','sample2','sample3'],['name TEXT','age INTEGER','temp REAL']);`

**Comment by amina04** [comment]
please can you explain more how create a database with many tables

**Comment by AgutuSam** [comment]
@amina04 ; the sqlite_at_runtime package allows you to create not only multiple databases, but multiple tables too... but as you are based over one DB multiple tables, this here creates a DB named mydb `Sqlartime.addNewDB('mydb', 'optional');` the code takes in 2 parameters, one: the name of the database, and two: an optional note to identify it from other DBs (the process takes in date and time to the last second, so one can opt to identify a database by its time stamp)

you can go ahead to open any DB by calling the openDB function, for example, `await Sqlartime.openDb('mydb');` opens "**mydb**" if it does exist

this code here; `await Sqlartime.tableCreate(['sample1','sample2','sample3'],['name TEXT','age INTEGER','temp REAL']);` same as the one I shared above, creates three tables( sample1, sample2 and sample3) in the open DB, with three columns each (name of type TEXT,age of type INTEGER and temp of type REAL), you can ofcourse call to the function at different intervals if you are dealing with tables of different structures, supplying their unique structure at each call, say `await Sqlartime.tableCreate(['sample1'],['name TEXT','age INTEGER','temp REAL']);` then `await Sqlartime.tableCreate(['sample2'],['firstName TEXT','staffID TEXT','prefs TEXT']);`

hope this helps!!!

**Comment by amina04** [comment]
> @amina04 ; the sqlite_at_runtime package allows you to create not only multiple databases, but multiple tables too... but as you are based over one DB multiple tables, this here creates a DB named mydb
> `await Sqlartime.addNewDB('mydb', 'optional');`
> 
> the code takes in 2 parameters:
> 
> 1. the name of the database
> 2. an optional note to identify it from other DBs (the process takes in date and time to the last second, so one can opt to identify a database by its time stamp)
> 
> you can go ahead to open any DB by calling the openDB function, for example,
> `await Sqlartime.openDb('mydb');`
> opens "**mydb**" if it does exist
> 
> this code here;
> `await Sqlartime.tableCreate(['sample1','sample2','sample3'],['name TEXT','age INTEGER','temp REAL']);`
> same as the one I shared above, creates three tables( **sample1**, **sample2** and **sample3**) in the open DB, with three columns each (**name** of type TEXT, **age** of type INTEGER and **temp** of type REAL),
> **NB remember to seperate the columnName and the dataType with a space, and have the type in full caps**
> 
> you can of course call to the function at different intervals if you are dealing with tables of different structures, supplying their unique structure at each call, say
> `await Sqlartime.tableCreate(['sample1'],['name TEXT','age INTEGER','temp REAL']);`
> then `await Sqlartime.tableCreate(['sample2'],['firstName TEXT','staffID TEXT','prefs TEXT']);`
> 
> hope this helps!!!

Sir I just wanna to asked you if i can do to all the tables do this functions(CRUD i mean for each table i create his own functions)   and also if i can separate the code like for each table i make their functions(CRUD) in other class or i must do all these in one class because i have 6 tables and if i do that in one class it will be complicate and thank you

**Comment by AgutuSam** [comment]
@amina04 well, you see, as long as you know what database you are working on, u can create any table anywhere. If you have created more than one database, as the plugin allows, you can use this: `await Sqlartime.closeDyn();` to close any open database,
use this: `await Sqlartime.openDb(String dbName);` to open your preferred database, 
then simply run the CRUD on the open database, any where in any class in any file.

all there is to be sure of, is to know what database is open, and in your case, using just one single database, you can with all comfort execute the CRUD without necessarily closing the database, as long as it hasn't been closed. If not sure though, it doesn't hurt to close any open one, then open your specified one and then run the CRUD.

...again, hope this helps!
