### ISSUE TITLE
Small, white border around date picker's header on Android

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4360]
Android:  (it's more visible on the device itself)

![screenshot_20160603-121437](https://cloud.githubusercontent.com/assets/5479/15790335/ab0a26ce-2985-11e6-8a47-ba4e8506d408.png)

iOS:

![img_0022](https://cloud.githubusercontent.com/assets/5479/15790338/b2eaefcc-2985-11e6-952d-9fffdcdfb599.PNG)

**Comment by sethladd** [comment]
cc @abarth

**Comment by abarth** [comment]
The fix is probably to restructure how we paint dialogs to not paint white behind the title.

**Comment by zoechi** [comment]
Can't reproduce

![image](https://user-images.githubusercontent.com/405837/50522605-1a28d300-0acc-11e9-86ec-9e105999df96.png)
