### ISSUE TITLE
Locale is returning en_ if country code is empty string

### ISSUE THREAD

**Issue by IchordeDionysos** [flutter/flutter#43607]
## Steps to Reproduce

1. Create two locales `one = Locale("en")` and `two = Locale("en", "")`
2. Log both
3. See that one is `"en"` and two is `"en_"`

## Additional Info and thoughts

This happens on an iOS simulator with the default locale.

I did some research and in this code: https://github.com/flutter/engine/blob/master/lib/ui/window.dart#L511
There should be an additional check if the `scriptCode` or the `_countryCode ` is an empty string because `"en_"` is not a valid `Unicode BCP47 Locale Identifier`

**Comment by jmagman** [comment]
> I did some research and in this code: https://github.com/flutter/engine/blob/master/lib/ui/window.dart#L511
> There should be an additional check if the `scriptCode` or the `_countryCode ` is an empty string because `"en_"` is not a valid `Unicode BCP47 Locale Identifier`

Thanks for the investigation!  [Pull requests](https://github.com/flutter/engine/compare) are always welcome, if you are interested. 
 See https://github.com/flutter/engine/blob/master/CONTRIBUTING.md.

**Comment by GaryQian** [comment]
Historically, empty string as country code is valid, so adding an assert there is not correct. However, what we can do is check for empty string in the toString to not produce the extra underscore.

**Comment by GaryQian** [comment]
This was a quick change, so I made https://github.com/flutter/engine/pull/17280
