### ISSUE TITLE
camera photo issue

### ISSUE THREAD

**Issue by haneensaadeh1994** [flutter/flutter#43604]
The image rotated 90 degrees after taken from the camera

`var  image = await ImagePicker.pickImage(
          source: ImageSource.camera, maxHeight: 700,maxWidth: 700,);`

**Comment by SBNTT** [comment]
#35334

**Comment by BondarenkoStas** [comment]
Thank you @SBNTT ! Closing the issue to avoid duplication, please upvote the referenced issue.
