### ISSUE TITLE
How to create v2 Android embedder plugins

### ISSUE THREAD

**Issue by v7lin** [flutter/flutter#43613]
i can't find any docs about this!

**Comment by anticafe** [comment]
Me too. These days I saw many PR in Flutter repo to migrate to Android embedding v2 but there is no documentation yet.

**Comment by v7lin** [comment]
@anticafe 

```
flutter config --enable-android-embedding-v2 
```

**Comment by BondarenkoStas** [comment]
Don't know if that helps, that the only thing I found https://github.com/flutter/flutter/wiki/Experimental:-Create-Flutter-Plugin

**Comment by kf6gpe** [comment]
See https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration, please. I'm closing this, as it's a support request, and support requests are better directed to the channels at https://flutter.dev/support. Thanks for trying Flutter!
