### ISSUE TITLE
"Could not update files on device: OS Error: Connection reset by peer, errno = 54" iOS9 and iOS13 at least

### ISSUE THREAD

**Issue by haidizhilei** [flutter/flutter#43617]
when I run flutter application on my iOS device,the project report an error with " Could not update files on device: OS Error: Connection reset by peer, errno = 54"

**Comment by BondarenkoStas** [comment]
@haidizhilei please paste your flutter doctor -v output, and specify which device you use. Do you receive the error while running it from Xcode?
I think it's the same as https://github.com/flutter/flutter/issues/41085.

**Comment by haidizhilei** [comment]
this is info when  I run 'flutter doctor -v'
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.5 18F132, locale
    zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/richard/Flutter/flutter
    • Framework revision 68587a0916 (6 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/richard/Library/Android/sdk
    • Android NDK at /Users/richard/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/richard/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.8.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.7)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

I don`t receve the error while running it from Xcode

**Comment by BondarenkoStas** [comment]
> I don`t receve the error while running it from Xcode

You didn't say what the device you use (is it with ios13), and if that works on other devices. If yes, then I will ask to close the issue to avoid duplication, and upvote and follow #41085 for resolution.

**Comment by haidizhilei** [comment]
I use iOS9.2 and iOS13.1.3 ，is the same error😂😂




| |
刁爱国
|
|
邮箱：diaoaiguo@126.com
|

签名由 网易邮箱大师 定制

On 10/29/2019 20:10, Stanislav Bondarenko wrote:

I don`t receve the error while running it from Xcode

You didn't say what the device you use (is it with ios13), and if that works on other devices. If yes, then I will ask to close the issue to avoid duplication, and upvote and follow #41085 for resolution.

**Comment by haidizhilei** [comment]
Are you the member of the flutter team？




| |
刁爱国
|
|
邮箱：diaoaiguo@126.com
|

签名由 网易邮箱大师 定制

On 10/29/2019 20:12, HDSwiftCache wrote:
I use iOS9.2 and iOS13.1.3 ，is the same error😂😂




| |
刁爱国
|
|
邮箱：diaoaiguo@126.com
|

签名由 网易邮箱大师 定制

On 10/29/2019 20:10, Stanislav Bondarenko wrote:

I don`t receve the error while running it from Xcode

You didn't say what the device you use (is it with ios13), and if that works on other devices. If yes, then I will ask to close the issue to avoid duplication, and upvote and follow #41085 for resolution.

**Comment by BondarenkoStas** [comment]
Ok, let's it stay, there it was only about iOS13.
No, I'm just doing initial triage here.

**Comment by haidizhilei** [comment]
👌 thank you




| |
刁爱国
|
|
邮箱：diaoaiguo@126.com
|

签名由 网易邮箱大师 定制

On 10/29/2019 20:30, Stanislav Bondarenko wrote:

Ok, let's it stay, there it was only about iOS13.
No, I'm just doing initial triage here.

**Comment by ykws** [comment]
@haidizhilei Hi, stable channel has the same error, too.
Switching to the dev channel solved the issue.

```
$ flutter channel dev
$ flutter upgrade
```

https://flutter.dev/docs/development/tools/sdk/upgrading

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.12.0, on Mac OS X 10.14.6 18G95, locale en-JP)
```

**Comment by jmagman** [comment]
This may have been mitigated by https://github.com/flutter/flutter/pull/41406.  Can you upgrade to the current stable version of Flutter and confirm it is no longer reproducing?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
