### ISSUE TITLE
Crash when a text start with a space in Hebrew localization

### ISSUE THREAD

**Issue by LeonidVeremchuk** [flutter/flutter#43616]
## Steps to Reproduce:
```
  Text(" שלום")
```
**Target Platform:** Android / iOS 

## Logs

No logs. App close with **"Lost connection"** message.

Workaround:  use **trim();** on the text data.

P.S. The same problem with TextField

**Comment by BondarenkoStas** [comment]
Oh right, didn't pay attention that hebrew is right to left. @LeonidVeremchuk please try it on master or dev, the fix went to v1.10.6

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
