### ISSUE TITLE
Error During Pre cache

### ISSUE THREAD

**Issue by AbishekSitaula** [flutter/flutter#43615]
![image](https://user-images.githubusercontent.com/18596638/67663140-ef7a0600-f98c-11e9-9fe4-9ce1a37069e6.png)

What can be done?

**Comment by BondarenkoStas** [comment]
@AbishekSitaula what flutter version, what dart version do you use and what is your OS version? If it's Catalina then maybe you can update your dart version to at least https://github.com/dart-lang/sdk/commit/ec2d06d4b9f4f0accad2b4aa841499e8e93cd70b

**Comment by AbishekSitaula** [comment]
How do i update Dart?

**Comment by BondarenkoStas** [comment]
@AbishekSitaula I think dart comes already in the flutter engine, which is 2.5.0 for stable. You can try flutter beta channel as it uses dart 2.6.0 which possibly contains the fix.

**Comment by AbishekSitaula** [comment]
Where can i get the Flutter Beta?

**Comment by BondarenkoStas** [comment]
https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
