### ISSUE TITLE
iOS not syncing to the firebase database

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4361]
_From @spierce7 on June 3, 2016 19:31_

Following the code lab [here](https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..%2Findex#0), I'm encountering issues with ios saving and syncing from the firebase database. Android seems to be working fine.

Linking to the provided firebase database seems to work fine, but when I try to change the bundle identifier and provide the `GoogleService-Info.plist` from my firebase account that's when I encounter issues. I've successfully changed the android package, and linked to the database without issues.

Not quite sure where to look from here.

_Copied from original issue: flutter/firebase#8_

**Comment by sethladd** [comment]
Thanks for the report. May we have some more info?

* What is the output of `flutter doctor` ?
* Are you trying an ios device or simulator?

**Comment by jimbeveridge** [comment]
When you did your `git clone` flutter to the Mac, did you include `-b codelab`? The Firebase part of the codelab will currently not run from `HEAD` on `master` on `github/flutter/flutter`.

**Comment by spierce7** [comment]
@sethladd ios simulator.
```
flutter doctor
[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/spierce7/frameworks/flutter
    • Framework revision 646b5350d1 (8 days ago), engine revision 7fab0c350b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/spierce7/Android/sdk
    • Platform android-N, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.7.0_80-b15)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

@jimbeveridge I'm running the latest released from `flutter upgrade`. I also don't think what you are saying matches with my experience. When I build step_5 after running `git clone https://github.com/flutter/firechat-flutter.git`, everything works fine on an android device, and the ios simulator. The issue only comes in when I try to move to my own firebase account. Android continues to work, while ios doesn't save or retrieve new messages.

**Comment by spierce7** [comment]
Upon re-reading my original post, I don't think I was as clear as I could have been.

1. If I checkout step_5 from `https://github.com/flutter/firechat-flutter.git` and run it, everything works on Android and iOS just fine.
2. When I create my own firebase database, change the Android package / `google-services.json`, and also change the Bundle identifier / `GoogleService-Info.plist` for ios, Android continues to work, while iOS no longer saves or retrieves from the database.

Given that when I change nothing from step_5 of the codelab, everything works fine, it's likely I'm just doing something I shouldn't be on the ios side. Full disclosure: I'm an Android dev, not iOS.

**Comment by jimbeveridge** [comment]
@spierce7  The version of Flutter you are running is old enough to sidestep the current problems of HEAD on master, but it's still not the version we ask you to run with the codelab. However, from your latest description, it doesn't sound like it's causing a problem.

Yesterday I reported a bug that the instructions for where to put GoogleService-Info.plist are wrong. Maybe that's the problem?
See https://github.com/flutter/flutter/issues/4307

**Comment by spierce7** [comment]
@jimbeveridge the `GoogleService-Info.plist` is in the `./ios/Resources/` folder. I think that's correct.

**Comment by jimbeveridge** [comment]
I recommend you copy your files one at a time over the sample files and try running the sample after each. Eventually one will break the sample. You should also check the log for errors, if you haven't already.

**Comment by spierce7** [comment]
@jimbeveridge to be clear, at this point, I'm using a clone of step_5 from the code lab. All I'm doing is I change the bundle identifier in the info.plist and I give it the new `GoogleService-Info.plist` and it stops working.

Is there a step missing, like I need to enable push notifications for ios or something like that? Should I not be changing the bundle identifier?

**Comment by jimbeveridge** [comment]
Earlier you said, "change the Android package / google-services.json". Do you mean you manually edited it, or do you mean you replaced the entire file with the version you downloaded from the Firebase site? The identifier in `Info.plist` must match the identifier you provided to Firebase to create `GoogleService-Info.plist`. If they are mismatched, then it will fail.

For reference, on https://codelabs.developers.google.com/codelabs/flutter/index.html#11, scroll down to **Add platform-specific Firebase configuration information**, and then to **iOS**.

**Comment by spierce7** [comment]
I replaced it with the `GoogleService-Info.plist` file that firebase provided to me.

**Comment by jimbeveridge** [comment]
I think I've found the problem. I repeated the steps you described. It runs fine in the emulator. It doesn't connect to Firebase if I run it on a real device (an iPhone in my case). There's also a second problem that flutter crashes if you try and run the Flutter app on a real device from within Atom. Bugs https://github.com/flutter/flutter/issues/4404 and https://github.com/flutter/flutter/issues/4226 have been filed.

Thank you for your patience working our way through this.

**Comment by spierce7** [comment]
You are able to move the chat application to your own firebase database, and it works successfully on the ios emulator? I haven't tested on a real device, but when I make the changes, it won't work on my ios simulator.

**Comment by jimbeveridge** [comment]
@collinjackson   Yes, I pulled down the codelab repo, updated Info.plist, updated GogoleService-Info.plist, and clicked Run. Worked fine. FWIW, I have my simulator set to an iPhone 6s. I'll check and see if there's any additional debug info that might help.

**Comment by spierce7** [comment]
Hmmm, sounds like your getting it to work better than me. Did you have to set up anything in regards to the bundle identifier besides telling firebase that your app uses that bundle identifier?

**Comment by Hixie** [comment]
If we're still using Firebase by milestone 3, then we should fix this. Otherwise it is probably obsolete.

**Comment by sethladd** [comment]
I think we can close this. We deprecated the previous codelab and the code supporting the codelab.

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1021. Any further collaboration will be done there.
