### ISSUE TITLE
Exception caught by widgets library

### ISSUE THREAD

**Issue by leemuljadi** [flutter/flutter#43627]
Hi, I'm using the StreamProvider package to listen for user authentication and read from Firestore.
But when I call the log out method it shows error message as below:

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building ProfileScreen(dirty, dependencies: [MediaQuery, InheritedProvider<FirebaseUser>]):
The getter 'email' was called on null.
Receiver: null
Tried calling: email

User-created ancestor of the error-causing widget was: 
  SafeArea file:///C:/Users/bluesky/AndroidStudioProjects/xxx/lib/navigation.dart:143:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ProfileScreen.build (package:xxx/screens/profile_screen.dart:30:39)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4009:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

```
How do I checked where is the 'email' getter? and how can I not call the getter method while sign out the user?

**Comment by BondarenkoStas** [comment]
@leemuljadi try to run it with with --verbose flag to see the full stacktrace to find at which point email was called.
This is a question better suited for StackOverflow, since it seems to be related to implementation and third-party package. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.

**Comment by leemuljadi** [comment]
Okay thanks, @BondarenkoStas !
Btw to use `--verbose` flag should I just type `flutter run--verbose` in the terminal?

**Comment by BondarenkoStas** [comment]
yes, `flutter run --verbose` or just `flutter run -v`

**Comment by leemuljadi** [comment]
cool, thanks @BondarenkoStas !
