### ISSUE TITLE
Auto update play/store

### ISSUE THREAD

**Issue by Mythar** [flutter/flutter#43622]
Hello, i know that is probably not the bedst place to ask this..
I have an (flutter) app in both google play and apple store, when i release a new version, apps are not updated automatically on devices nor are users notified of the new release.
What am i missing ?

**Comment by BondarenkoStas** [comment]
@Mythar sorry to say but yes, this is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
