### ISSUE TITLE
defaultTargetPlatform on web thinks it's Android

### ISSUE THREAD

**Issue by andermoran** [flutter/flutter#43633]
`defaultTargetPlatform` returns `TargetPlatform.android` for web builds.

Ran using `flutter run -d chrome`.

Tested on macOS Google Chrome.
**Flutter** version 1.9.1+hotfix.6
**Google Chrome** version 77.0.3865.120

**Comment by jmagman** [comment]
You can see some a related issue here: https://github.com/flutter/flutter/issues/36126
Here's a workaround: https://github.com/flutter/flutter/pull/36135

**Comment by jonahwilliams** [comment]
We don't have a real implementation of defaultTargetPlatform on the web. It would need to be implemented here:

https://github.com/flutter/flutter/blob/7442eeafe52e7fc9510ef73af45ef8183732732d/packages/flutter/lib/src/foundation/_platform_web.dart#L8

**Comment by jonahwilliams** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
`defaultTargetPlatform` is a different dimension from `Platform` and `kIsWeb`. `defaultTargetPlatform` dictates platform idioms, such as scroll physics, over-scroll effect, back gestures, etc. We should fully implement this on the Web.

**Comment by eseidelGoogle** [comment]
This makes gallery.flutter.dev look wrong on iOS devices (with the wrong overflow physics).

**Comment by ferhatb** [comment]
@clocksmith : engine fixes are in, please close issue once you deploy latest gallery.
