### ISSUE TITLE
Cant "build apk" after use aar from Flutter 1.9 with "flutter build aar"

### ISSUE THREAD

**Issue by cedear** [flutter/flutter#43634]
this is my flutter。
![image](https://user-images.githubusercontent.com/25534150/67691756-1579c780-f9da-11e9-986b-86e5a8d4de89.png)
after "flutter build aar", i put aar into my own Android project, and "build apk", then [it](url) happened:

Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.

then, i think its my android project‘s problem, it doesnt support Java 8, then use retrolambda to let my android project support java, but when i run "build apk" in android studio again, it still has problem like this:
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file. 

Isn't Java 8 in my project working?

**Comment by jmagman** [comment]
\cc @blasten

**Comment by blasten** [comment]
Could you clarify what you meant by adding the AAR to the app and then running `flutter build apk`?

AARs are meant to be added to a host app in add to app scenarios.

**Comment by cedear** [comment]
> Could you clarify what you meant by adding the AAR to the app and then running `flutter build apk`?
> 
> AARs are meant to be added to a host app in add to app scenarios.

I generated AAR through "flitter build AAR" in flitter 1.9, Add it to my Maven repository.and Import into my android project, then used "build APK" in Android project, and then the above problems occurred.

**Comment by huycozy** [comment]
Hi @cedear, are you still facing this issue on the latest version of flutter stable `3.0.5`?

If you are, kindly provide the output of `flutter doctor -v` as well as a complete minimal reproducible code sample so that we can investigate this. In this case, please upload your project to a Github repository so that we can easily clone and try reproducing the issue.

Thank you!
