### ISSUE TITLE
Package : url_launcher, issue to build on Xcode 

### ISSUE THREAD

**Issue by Liliana99** [flutter/flutter#43659]
Hi,

I have an app on flutter , at the moment to open on Xcode , shows this error with the url_launcher.
```
error: /Volumes/Extra/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.1.2/ios/Classes/UrlLauncherPlugin.h: No such file or directory (in target 'url_launcher' from project 'Pods')
```
Could you please help me  to solve this?

Thanks,

**Comment by jmagman** [comment]
Can you confirm you are opening Runner.xcworkspace and NOT Runner.xcodeproj?
https://github.com/flutter/flutter/issues/10770

**Comment by Liliana99** [comment]
![Captura de pantalla 2019-10-29 a las 7 39 10](https://user-images.githubusercontent.com/18160916/67743540-42040280-fa1f-11e9-9113-525b2e1315f3.png)

Yes I can .

I've attached the pic here.

**Comment by jmagman** [comment]
Does `/Volumes/Extra/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.1.2/ios/Classes/UrlLauncherPlugin.h` actually exist?  Did you run `flutter pub get` or `flutter build ios` or `flutter run` before you launched it in Xcode?  Looks like the pub package is missing?  Are there any `url_launcher` directories in `/Volumes/Extra/flutter/.pub-cache/hosted/pub.dartlang.org/`?

**Comment by jmagman** [comment]
Also can we get `flutter doctor -v`

**Comment by Liliana99** [comment]
Hi jmagman,

Thanks to help.

Ok to answer the question -->> Does /Volumes/Extra/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.1.2/ios/Classes/UrlLauncherPlugin.h actually exist? .......Yes .
You can see on the pic , this is on VSCode, 
![scope_myApp_flutter2](https://user-images.githubusercontent.com/18160916/67810510-03ac2900-fa9b-11e9-91d2-f646e9531377.jpg)

Let me explain something... This is an project that I 've download from github, then firstly I opened on VScode, there I had run flutter doctor -v.

After I've done updatr cocoapods because the doctor says that .Then I close vscode and I open the project from the file myApp/IOS/ Runner .xworkspace the Xcode open the project and shows the error I previously attached .!!

I don't know how to fix that on Xcode, because on VsCode I've been able it works..

Thanks again for you help!!

**Comment by Liliana99** [comment]
Hi jmagman,

Firtsly  I want to  say "Thanks for your help.." because your question  "Did you run flutter build ios ??" it was the clue to solve this issue!!

Yes ,  all I have  to do was that...... to run flutter ios from terminal on VsCode (previosuly I did  run flutter pub get)

It works on Xcode and  Android,

Thanks again!!
