### ISSUE TITLE
[sensors] Having problem with Flutter Sensors package

### ISSUE THREAD

**Issue by officer47p** [flutter/flutter#43653]
Hey Everybody,
I have created an app in flutter which uses Sensors package in it and it has 2 routes and a websocket connection. I'm getting ip address of the websocket server from the user in the first page and pass it to the second page which I will connnect to the websocket server and run the Sensors listener and calling setState in every change that happens in sensors.
The problem is, whenever I call Navigator.pop(context) (or just close the route) the listener is still giving data and calls my listener callback even though the route is disposed from the widget tree. I tried to call setState() when ever the widget is mounted by adding an if(this.mounted) and it fixed the setState calling when the widget is disposed, but when I added a print statement to the listener I realized that the listener is still calling my callback and it's not closed.

My question is haw can I close the Stream (more specificly the sensors listener) when I dispose a widget or destroy the route ?
I appreciated any help or suggestion from you.
Thanks

**Comment by markfili** [comment]
did you try saving the StreamSubscription that the `listen` method returns and then using `streamSubscription.cancel()` in `onDispose`?

**Comment by officer47p** [comment]
Fixed the issue, hadn't called `streamSubscription.cancel()`.
Closing the issue now.
