### ISSUE TITLE
[Local_auth] Problems identifying "FEATURE_FACE" on Samsung phone

### ISSUE THREAD

**Issue by SebAubin** [flutter/flutter#43650]
Hi! I have a problem with the plugin Local_auth. On a Samsung's device, like my S8+, I have enabled the face recognition biometric. The problem with it is that in my flutter app the local_auth plugin with the call: `localAuth.getAvailableBiometrics()` keeps detecting "fingerprint" instead of "face". I have identified the problem.. 

In the LocalAuthPlugin.java line 103-110:

```
if (Build.VERSION.SDK_INT >= 29) {
          if (packageManager.hasSystemFeature(PackageManager.FEATURE_FACE)) {
            biometrics.add("face");
          }
          if (packageManager.hasSystemFeature(PackageManager.FEATURE_IRIS)) {
            biometrics.add("iris");
          }
        }
```

Actually, this is not a problem because this feature is really available for the API level 29. My problem is that Samsung added the face recognition their devices running on api 28 (in my case) so the face recognition cannot be added in the available biometrics.

Do you have a way to detect for the samsung's devices?

Thanks!

## Logs

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A583, locale fr-CA)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by progid** [comment]
To reproduce the error, just print all available biometric types on Xiaomi Redmi 4 Pro or Xiaomi Redmi 3S with touchId

**Comment by Niccolohui** [comment]
I have same issue too, have you fixed it?

**Comment by Alishgiri** [comment]
Same issue here!

**Comment by stuartmorgan** [comment]
Closing as obsolete; the current Android APIs do not distinguish individual biometrics.
