### ISSUE TITLE
CupertinoPicker has no way to set the initial selected item

### ISSUE THREAD

**Issue by chickenblood** [flutter/flutter#43660]
## Use case

CupertinoPicker has no way to set the initial selected item.

https://api.flutter.dev/flutter/cupertino/CupertinoPicker-class.html

I have a picker where the user can change the radius for a map search from a list of options:
"1 mile",
"2 miles",
"5 miles"
"10 miles"
"Everywhere"

When I present this sheet, I want the currently set search radius (e.g. "5 miles") to be initially selected. Instead, "1 mile" is always selected by default.

Worked around by using a CupertinoActionSheet (and setting the isDefaultAction parameter CupertinoActionSheetAction to true for the initial selection). This works okay, but a picker would look more appealing for this use case from my POV.

## Proposal

Add a selectedIndex parameter to CupertinoPicker.

**Comment by LongCatIsLooong** [comment]
You should be able to specify a `CupertinoPicker`'s initial item in its controller. See https://api.flutter.dev/flutter/cupertino/CupertinoPicker/scrollController.html.
Maybe it's worth adding to the API documentation.

**Comment by chickenblood** [comment]
I had to read this twice. Is this seriously the best API we can come up with?

**Comment by LongCatIsLooong** [comment]
The API looks reasonable to me, having a controller as the source of truth is a pretty common pattern among widgets that respond to user interactions. Of course we're open to suggestions, do you mind explaining why you prefer adding `selectedIndex` over the current `CupertinoPicker` API?

**Comment by chickenblood** [comment]
To me a good API is intuitive, i.e how would The develop expect this thing to work and consistent with other similar examples, so the developer gets more and more confident as they use more and more components in the library.

In this case, what is not intuitive IMO is that I can set state like the content (children) directly on the object itself, but then the selected item in the content somehow has to be done by some special controller object. The inconsistent part here, is that other widgets like BottomNavigationBar (for example) set this vital piece of information as a direct parameter of their own constructor.

**Comment by chickenblood** [comment]
OK, I think a broader discussion is warranted, but not in this forum, regarding good API design and hiding implementation details, but I appreciate your response and the flexibility that this particularly design affords may one day be useful to me. Cheers!
