### ISSUE TITLE
Engine workstation setup instructions are out of date.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#43671]
The Wiki page on [setting up the workstation for Engine development](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment) has instructions to run the following scripts:

* `//build/install-build-deps-android.sh`
* `//build/install-build-deps.sh`
* `//flutter/build/install-build-deps-linux-desktop.sh`

These scripts were originally inherited from Chromium and contain instructions that are now really out-of-date. Most dependencies listed in those scripts are either not necessary or not available on the latest versions on the popular Linux distros. These scripts ought to be re-written from script by attempting builds in a clean room environment (a Docker image should be fine).

**Comment by dnfield** [comment]
Can we just remove them?

**Comment by stuartmorgan** [comment]
> //flutter/build/install-build-deps-linux-desktop.sh

This one isn't inherited from Chromium, it just follows the general structure that was already in place. It shouldn't be out of date.

**Comment by dnfield** [comment]
It seems like any of these scripts will be prone to bitrotting, and will likely end up with the same sort of branching logic for N distros of Linux/versions of macOS/Windows/VisualStudio/etc.

IME, when a pre-req is missing, it becomes pretty clear pretty quickly how to install it - usually with something printed on the console like "You're missing package whatever, try running `apt-get install ...`".

**Comment by stuartmorgan** [comment]
I don't know how many of the dependencies are actually needed vs just being cruft from Chromium, but [this list] is ~60 packages. Even if there are good error messages for all of them, having to find those one error message at a time would make setup a nightmare.

**Comment by dnfield** [comment]
Ahh fair enough.

**Comment by deakjahn** [comment]
`install-build-deps.sh`now emits more than a dozen error messages about unlocatable packages. Finally,

    sudo apt-get install pkg-config

was the only one I needed to start the compilation without any more errors.

**Comment by deakjahn** [comment]
I'd be more than willing to offer my two descriptions in https://github.com/flutter/flutter/issues/28720 as unified, self-contained instructions, not pointing out to other documentations that need to be cherry-picked to see what's relevant in them. As far as I know, I think, these two are now up-to-date and work as described, I have numerous attempts and, finally, successes behind those (Stuart will remember :-) ).

**Comment by stuartmorgan** [comment]
> was the only one I needed

We're now using a sysroot for Linux builds, which means that the script mostly shouldn't be needed any more; this was discussed at some point in Discord, but not captured here.

**Comment by cbracken** [comment]
I just did set up a brand new (non-Google) desktop using the instructions in the wiki and didn't run across any issues. FWIW I never trust shell scripts that install dependencies on my machine, so typically I just read them and manually install what I need. In this case the only things I needed were covered in the wiki (pkg-config and the gtk dev dependencies).

@chinmaygarde @stuartmorgan @dnfield do you know if our bots or any other infra relies on the shell scripts? It seems better to just cover the install steps explicitly in the wiki, as we do today. For people on non-debian-derived distros, the explicit instructions give them better breadcrumbs as to what they need to install. If we're not using these, I'll delete them.

**Comment by chinmaygarde** [comment]
> do you know if our bots or any other infra relies on the shell scripts...

I don't think so.

I agree that running scripts that install dependencies on the machine is dodgy (especially when said scripts also try to guess the dependencies based on host distro).

Per Stuart's last comment, it seems like we shouldn't need these scripts. Let's try to remove them and instead document the specific dependencies that are needed so that developers can set them up themselves.

**Comment by deakjahn** [comment]
As I mentioned in my linked description,

    sudo apt install pkg-config

was the only one that I actually needed. I can't vouch for nothing else needed in any scenario, of course, but I successfully compiled the source and used it to send a PR with that.

**Comment by stuartmorgan** [comment]
> Per Stuart's last comment, it seems like we shouldn't need these scripts.

I have no idea if that's true for `install-build-deps-android.sh`; I wouldn't bet on it though.

**Comment by dnfield** [comment]
the install-build-deps script was removed because it is not maintained and fails in many environments. 

The expectation is that if you are missing dependencies, the build errors will be clear enough to work through and figure out. install-build-deps may or may not work to help you with that, but we don't want to treat it as a "supported" piece of setup, because no one maintains it (outside of random contributions from someone setting up a new environment once every few months or years :)

**Comment by Sunbreak** [comment]
Test on engine of Flutter 3.0.2, i.e. commit https://github.com/flutter/engine/commit/f15f824b57476e369b5e656f53d4c431c5b04b9a

- Clean installed Ubuntu 20.04 LTS (Official image on TencentCloud)
- `gclient sync`
- `./flutter/tools/gn --unoptimized && autoninja -C out/host_debug_unopt` success
- `./flutter/tools/gn --android --unoptimized --android-cpu arm64 && autoninja -C out/android_debug_unopt_arm64` success

**Comment by zanderso** [comment]
I have updated the wiki to remove reference to these scripts from the environment setup page.
