### ISSUE TITLE
Provide presubmit test number automatically

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#43672]
Currently, the engine-to-framework roller gets the test number manually from a [Skia repo config file](https://skia.googlesource.com/buildbot/+/refs/heads/master/autoroll/config/flutter-engine-flutter.json#23), and makes sure that at least that number of tests would pass before merging a commit.

That's because the GitHub API could show all tests as green and completed while actually some tests still didn't get started by Cirrus.

Currently, that number is a little hard to maintain. It would be nicer to have a mechanism to easily update that number within the flutter/flutter repo.

An easy way would be to simply add a text file with that number in it, and let the Skia auto-roller read that file.

A better (but probably more involved) way is to have a script to parse `.cirrus.yml` and generate that number automatically. Then Skia would call that script to get the number. With that, people don't have to manually update that number when a test is newly added to Cirrus.

**Comment by liyuqian** [comment]
@gspencergoog @dnfield @digiter : how easy and reliable do you think that we can write a script to parse `.cirrus.yml` and output the number of tests?

**Comment by gspencergoog** [comment]
Could you query the Cirrus web API and ask it how many tests there are total?

E.g. whatever the API is that generates this page must have a list of tests:
https://cirrus-ci.com/build/flutter/flutter/98bc378d6f6b767fd9609ebc5a5ad9aefc3918de

**Comment by liyuqian** [comment]
@gspencergoog : those tests could have a latency before showing up, and that's why we added the test number check initially.

**Comment by digiter** [comment]
I calculated our usage via Cirrus GraphQL API (https://cirrus-ci.org/api/) in the past. It can fetch the status of tests on a latest commit, but sometime unreliable due to network / server error.

**Comment by gspencergoog** [comment]
Also, isn't it kind of fragile to be checking GitHub for a minimum number of tests instead of specific tests, since some of GitHub checks could be failing (like the "CLA" or "codecov" status check) and prevent the roller from running, or let it submit when the "codecov" is green but another code test is failing?

**Comment by gspencergoog** [comment]
FWIW, in response to the original question, I think it is pretty fragile to be parsing the `cirrus.yaml` file:  Every time Cirrus adds a new feature, or maybe when we restructure the file, we'd have to update the parsing.

**Comment by liyuqian** [comment]
The end goal is to make sure that the auto-roller doesn't merge the commit when Cirrus still has a test that didn't start yet. I'm happy to accept different proposals if that could be done without a minimum passing test number check.

**Comment by dnfield** [comment]
It would probably be best if the autoroller could query the GitHub API to make sure all status/checks are green and completed.

Parsing an individual provider's status (or adding queries for individual provider's API endpoints) is likely to break/change over time.

**Comment by liyuqian** [comment]
@dnfield : the roller does query GitHub API to make sure all status/checks are green and completed. However, GitHub API could show you all tests as green and completed while actually some tests still didn't get started by Cirrus.

**Comment by liyuqian** [comment]
@digiter : do you have an example of using GraphQL to query the number of Cirrus tests given a commit?

**Comment by digiter** [comment]
We can simplify this query, the length of the tasks list is the number of tasks executed given a commit.
```
  cirrusQuery = `
    query ($cursor: String!, $first: Int, $owner: String!, $name: String!) {
      githubRepository(owner: $owner, name: $name) {
        builds(after:$cursor, first:$first) { # Fetch first X of builds after cursor
          pageInfo {
            startCursor
            endCursor
            hasPreviousPage
            hasNextPage
          }
          edges {
            cursor
            node {
              id
              branch
              changeIdInRepo
              changeMessageTitle
              pullRequest
              changeTimestamp
              buildCreatedTimestamp
              status
              tasks {
                id
                buildId
                repositoryId
                name
                status # e.g. EXECUTING, CREATED, COMPLETED
                statusTimestamp
                creationTimestamp
                scheduledTimestamp
                executingTimestamp
                finalStatusTimestamp
                durationInSeconds
                labels
                uniqueLabels
                useComputeCredits
                transaction {
                  timestamp
                  microCreditsAmount
                  creditsAmount
                }
              }
            }
          }
        }
      }
    }
  `
```

**Comment by Hixie** [comment]
As far as I can tell querying Cirrus alone is insufficient since we have other sources of tasks (e.g. clabot, WIP bot, flutter-build, eventually LUCI, TAP...).

https://github.com/flutter/flutter/pull/43681 is a WIP in providing a script that computes this number, FWIW.

**Comment by liyuqian** [comment]
Additionally, I've verified that Cirrus GraphQL API also won't return a full list of tasks initially, hence it doesn't fix our problem that Github API won't always tell us the correct number of tests.

Specifically, I used
```
    query($owner: String!, $name: String!, $SHA: String!) {
      searchBuilds(repositoryOwner: $owner, repositoryName: $name, SHA: $SHA) {
        id
        branch
        changeMessageTitle
        tasks {
          id
          name
        }
      }
    }
```
to query my test commit https://github.com/flutter/flutter/commit/4cc8893682b5611cbab85800d5b030ee53d5c300 . It initially returned 32 tasks. A while later, it returned 48 tasks.

BTW, the final number of tests that Github API should return is 99. It's 2*48 + 3: each Cirrus task is counted twice, and there are 3 non-Cirrus tests (CLA, WIP, flutter-build). So far, I found Ian's solution https://github.com/flutter/flutter/pull/43681 to be the most reliable one.

@rmistry: can we check the Github API's test number after each merge, and send a warning email to the engine rotation if such number mismatches the one that's either hard-coded or provided by a script? That way we can quickly know that something is missing.

**Comment by rmistry** [comment]
borenet@ and I looked into the code and emailing at that time is difficult the way things are structured. But I could put a comment in the PR saying that this was merged with different num of checks than what was returned by the script. And maybe mention (@) the sheriff.

Somewhat related, in the autoroller we have pretty much implemented a github commit-queue now, this is messy and makes the autoroller code much more complicated than it should be. Does anybody know if there is a github app or a way within cirrus (or something else) than tells it to automatically merge a PR once there is approval and all checks pass? if we could activate that feature selectively for roll PRs then it would make the autoroller much more saner.

Also, I remember hearing something about eventually moving these bots to swarming (I have been remembering this wrong), any updates on that?

**Comment by rmistry** [comment]
> But I could put a comment in the PR saying that this was merged with different num of checks than what was returned by the script. And maybe mention (@) the sheriff.

I take this back, I cannot find a clean way of doing this either because of the messy structure I mentioned in the previous comment.
Easiest option is to make the autoroller log an error and then I'll add an entry for what the Skia trooper should do when that happens (contact the flutter rotation sheriff).

**Comment by liyuqian** [comment]
That also sounds good to me as it shouldn't happen very frequently.

**Comment by liyuqian** [comment]
@rmistry, for earlier questions:

1. https://github.com/palantir/bulldozer seems to be a promising Github app for auto-merge. To use it, it seems that we need to list all test/check names in a yaml. @tvolkert @Hixie : what's your take on using this app? I desperately needed it so I don't need to monitor flutter-build all day.

2. @dnfield is trying to migrate our tests to LUCI. I'm not aware of any swarm work though.

**Comment by rmistry** [comment]
> @rmistry, for earlier questions:
> 
> 1. https://github.com/palantir/bulldozer seems to be a promising Github app for auto-merge. To use it, it seems that we need to list all test/check names in a yaml. @tvolkert @Hixie : what's your take on using this app? I desperately needed it so I don't need to monitor flutter-build all day.

If flutter.git and engine.git started using this app, it would greatly simplify the autoroller code and make the whole rolling mechanism much more sane.

> 2. @dnfield is trying to migrate our tests to LUCI. I'm not aware of any swarm work though.

**Comment by Hixie** [comment]
We can just implement our own, it wouldn't be difficult. We already have code to go through PRs and so on, we just need to add additional checks for how to land PRs. (We cannot use third party code that has commit access, for security reasons.)

**Comment by dnfield** [comment]
We could just have a cron job that runs, looks for pull requests that 

- have the label
- are approved
- have passed all status checks

and then merges.  We have an account that has the right access.

**Comment by liyuqian** [comment]
Created https://github.com/flutter/flutter/issues/44007 to track the auto-merge separately. @dnfield @Hixie @goderbauer : shall we form a work force to make this happen ASAP in Q4? Personally I think the time it can save me from checking flutter-build in Q4 would be far greater than the time to be invested to make it happen. CC @GaryQian , @jonahwilliams , @gspencergoog who I think might also be checking flutter-build a lot and would like to have an auto-merge option.

**Comment by digiter** [comment]
For Cirrus, how about adding a "catch all" task that depends on all other tasks? So that when the "catch all" task finishes, we know all the tasks have executed.

**Comment by liyuqian** [comment]
@digiter : that sounds good to me. What test are you going to run in that "catch all" task? Checking the number of tests that have passed?

**Comment by digiter** [comment]
It's a no-op task, as it depends on all other tasks, it will be executed at the end of everything.

**Comment by jonahwilliams** [comment]
Keep in mind that task scheduling has been observed to take on the order of minutes, even for simple tasks

**Comment by dnfield** [comment]
I think the concern isn't so much about task scheduling as the slight delay between opening a pull request and Cirrus (or any CI provider) updating the status of that PR.  There's a window there wher esomething trying to do a status check on a PR will see it as all green, when in fact it has not even started CI.

**Comment by dnfield** [comment]
Flutter-build for example only updates once every minute or two on a cron job.

**Comment by Hixie** [comment]
This is mostly moot now right? I'm going to close it.
