### ISSUE TITLE
Flutter Gallery Benchmark Regressions

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#43688]
`flutter_gallery__back_button_memory` `end-max` and `flutter_gallery__back_button_memory` `diff-median` regressed significantly after https://github.com/flutter/flutter/pull/43643
<img width="261" alt="Screen Shot 2019-10-28 at 6 46 37 PM" src="https://user-images.githubusercontent.com/44085/67730785-527e9380-f9b3-11e9-9f22-373b736e042c.png">
<img width="264" alt="Screen Shot 2019-10-28 at 6 46 47 PM" src="https://user-images.githubusercontent.com/44085/67730786-527e9380-f9b3-11e9-8f8b-70098a9d5577.png">

**Comment by blasten** [comment]
ughh that's not good

**Comment by blasten** [comment]
I will keep this issue open, but remove the "Today" label.

**Comment by blasten** [comment]
cc @matthew-carroll, @xster.

**Comment by xster** [comment]
Is this reproducible locally? I'm kinda hoping that it's still https://github.com/flutter/flutter/issues/36898 (since the gallery presumably uses plugins and the shim)

**Comment by jason-simmons** [comment]
This can be reproduced locally:
* Run Gallery on Android with the new embedding
* Run `adb shell dumpsys meminfo io.flutter.demo.gallery` and check the graphics memory usage and the total usage.
* Run the Shrine demo, scroll through the images, and run `adb shell dumpsys meminfo io.flutter.demo.gallery` again.  Note the increase in memory usage.
* Press the back button a few times until the app is suspended.
* Run `adb shell dumpsys meminfo io.flutter.demo.gallery` again.  There will be no change.

It looks like the new embedding is not destroying the engine and releasing its resources when the activity is destroyed.

**Comment by chinmaygarde** [comment]
The commit has been reverted and the benchmarks are back to their previous levels. Can this be closed?

**Comment by xster** [comment]
we'd want to fix the source of the regression in the engine and migrate again.

**Comment by jason-simmons** [comment]
`FlutterActivity.shouldDestroyEngineWithHost` returns false unless it is overridden by a flag in the activity's intent:
    https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java#L677

So the new embedding by default will retain the engine when the activity is destroyed.  The old embedding would destroy the engine by default.

@matthew-carroll

**Comment by xster** [comment]
Thanks for doing the digging Jason!

If the activity/fragment made the engine, it should kill the engine when it's gone I think.
