### ISSUE TITLE
Drawer on docs.flutter.io doesn't look right

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#4369]
1. Go to http://docs.flutter.io/flutter/widgets/Widget-class.html
2. Narrow your window until the page changes format and a hotdog menu appears on the upper left corner.
3. Click the hotdog menu.

The drawer is transparent and hard to read.  It looks like we're missing some CSS somewhere.

/cc @qchong

**Comment by abarth** [comment]
Looks like `.sidebar-offcanvas-left` is overriding the background color to be `inherit` rather than white.

**Comment by abarth** [comment]
Bug does not manifest on api.dartlang.org.

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by abarth** [comment]
The version on api.dartlang.org also has some additional padding, so we might be missing some other styles as well.

**Comment by sethladd** [comment]
Good catch, thanks!

**Comment by abarth** [comment]
Elliott found it.  I just filed the bug.  :)

**Comment by sethladd** [comment]
I doubt we'll get to this for M2, unfortunately.

For anyone listening, we'd love the help here :)

**Comment by Hixie** [comment]
Looks like this is fixed.
