### ISSUE TITLE
Must be able to initialize the ICU context. Tried: /data/user/0/xxx/app_flutter/flutter_shared/icudtl.dat

### ISSUE THREAD

**Issue by cedear** [flutter/flutter#43705]
This is my development environment
![image](https://user-images.githubusercontent.com/25534150/67747573-fe7fb780-fa63-11e9-860e-83e64f5a3bef.png)
my flutter android build tool is  com.android.tools.build:gradle:3.2.1
my android studio build tool is 'com.android.tools.build:gradle:3.0.1'

and this is my code
```
public class xxxxActivity extends FlutterFragmentActivity {
    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        FlutterMain.startInitialization(getApplicationContext());
        super.onCreate(savedInstanceState);
        setContentView(R.layout.xxxxxxx);
        FlutterView mFlutterView = Flutter.createView(this, getLifecycle(), "xxxxx");
        FrameLayout.LayoutParams mParams = new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT, FrameLayout.LayoutParams.MATCH_PARENT);
        addContentView(mFlutterView, mParams);
    }
}
```
When I enter the xxxxActivity page，My app crashed This is the error message.
```
> flutter: [FATAL:flutter/fml/icu_util.cc(92)] Check failed: context->IsValid(). Must be able to initialize the ICU context. Tried: /data/user/0/xxxxx/app_flutter/flutter_shared/icudtl.dat
```

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
