### ISSUE TITLE
Task 'assembleAarRelease' not found in root project 'android_generated'. Some candidates are: 'assembleRelease'.

### ISSUE THREAD

**Issue by jianzhongli** [flutter/flutter#43704]
## Steps to Reproduce

By following instructions [here](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps), I created a flutter module with `flutter create -t module`, and run

```
$ cd some/path/my_flutter
$ flutter build aar
```

The output is:
```
Initializing gradle...                                              0.4s
Resolving dependencies...                                           2.2s
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    0.6s
Configuration on demand is an incubating feature.


FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleAarRelease' not found in root project 'android_generated'. Some candidates are: 'assembleRelease'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 473ms


Gradle task assembleAarRelease failed with exit code 0.
```

**Target Platform:**
**Target OS version/browser:**
**Devices:**

flutter doctor information:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.137, on Mac OS X 10.14.4 18E2034, locale en-CN)
```

**Comment by prasant10050** [comment]
I am facing this issue during android release build

**Comment by BondarenkoStas** [comment]
@jianzhongli can you please provide a full log while running it with --verbose flag?

**Comment by jianzhongli** [comment]
> @jianzhongli can you please provide a full log while running it with --verbose flag?

@BondarenkoStas  Sure, please have a look on this [gist](https://gist.github.com/jianzhongli/eb806ab1c1620b36ff27ff56158cf6e4).

**Comment by xster** [comment]
cc @blasten, anything we need to look at here?

**Comment by blasten** [comment]
I'm unable to repro this issue. Are you still able to repro this problem if you flutter upgrade?

**Comment by jianzhongli** [comment]
> I'm unable to repro this issue. Are you still able to repro this problem if you flutter upgrade?

Yes, the problem still exists.

Reproduce steps:
```bash
flutter create -t module my_flutter
cd my_flutter
flutter build aar
```

Flutter version:
```txt
Flutter 1.10.17-pre.70 • channel master • https://github.com/flutter/flutter
Framework • revision 01f4f1ac55 (10 hours ago) • 2019-11-12 18:25:53 -0800
Engine • revision 31cd2dfca2
Tools • Dart 2.7.0
```

**Comment by tarek360** [comment]
I got the same error, any update on this?

**Comment by blasten** [comment]
Could you re-run the command with the -v flag and paste the output here?

**Comment by tarek360** [comment]
Sure, I will do!
FYI, it works successfully with another Mac machine. I'm trying to figure out what is different between both machines.
Do you think the `flutter build aar` command needs for some permission to access some files on my machine.
Also I'd know where the `android_generated` project?

**Comment by tarek360** [comment]
@blasten 
here is the output of the three commands:
`flutter create -t module --org com.example my_flutter`
`cd my_flutter`
`flutter build aar`

```
tarek: ~/dev
flutter create -t module --org com.example my_flutter
Creating project my_flutter... androidx: true
my_flutter/test/widget_test.dart (created)
my_flutter/my_flutter.iml (created)
my_flutter/.gitignore (created)
my_flutter/.metadata (created)
my_flutter/pubspec.yaml (created)
my_flutter/README.md (created)
my_flutter/lib/main.dart (created)
my_flutter/my_flutter_android.iml (created)
my_flutter/.idea/libraries/Flutter_for_Android.xml (created)
my_flutter/.idea/libraries/Dart_SDK.xml (created)
my_flutter/.idea/modules.xml (created)
my_flutter/.idea/workspace.xml (created)
Running "flutter pub get" in my_flutter...                          6.5s
Wrote 12 files.

All done!
Your module code is in my_flutter/lib/main.dart.

tarek: ~/dev
cd my_flutter

tarek: ~/dev/my_flutter
flutter build aar -v
[  +22 ms] executing: [/Users/tarek/dev/flutter/sdk/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +34 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] 4944622b5d8e7a8ee5dbf658b0d0e8ab94b8efd3
[        ] executing: [/Users/tarek/dev/flutter/sdk/] git describe --match
v*.*.* --first-parent --long --tags
[  +11 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.13.2-0-g4944622b5
[   +8 ms] executing: [/Users/tarek/dev/flutter/sdk/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/Users/tarek/dev/flutter/sdk/] git ls-remote --get-url
origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +52 ms] executing: [/Users/tarek/dev/flutter/sdk/] git rev-parse
--abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[   +5 ms] executing: sw_vers -productName
[  +14 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.14.6
[        ] executing: sw_vers -buildVersion
[  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 18G103
[  +24 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[   +6 ms] Artifact Instance of 'MaterialFonts' is not required, skipping
update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[   +5 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[ +118 ms] Generating
/Users/tarek/dev/my_flutter/.android/Flutter/src/main/java/io/flutter/plugins/G
eneratedPluginRegistrant.java
[  +36 ms] Running Gradle task 'assembleAarDebug'...
[   +1 ms] gradle.properties already sets `android.enableR8`
[   +1 ms] Using gradle from /Users/tarek/dev/my_flutter/.android/gradlew.
[        ] /Users/tarek/dev/my_flutter/.android/gradlew mode: 33261 rwxr-xr-x.
[  +13 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android
Studio.app/Contents/Info.plist
[   +9 ms] Exit code 0 from: /usr/bin/plutil -convert json -o -
/Applications/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android
    Studio","JVMOptions":{"MainClass":"com.intellij.idea.Main","ClassPath":"$APP_PAC
    KAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:$
    APP_PACKAGE\/Contents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_
    PACKAGE\/Contents\/lib\/log4j.jar:$APP_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_
    PACKAGE\/Contents\/lib\/jna.jar","JVMVersion":"1.8*,1.8+","Properties":{"idea.ho
    me.path":"$APP_PACKAGE\/Contents","idea.executable":"studio","idea.platform.pref
    ix":"AndroidStudio","idea.paths.selector":"AndroidStudio3.5"},"WorkingDirectory"
    :"$APP_PACKAGE\/Contents\/bin"},"LSArchitecturePriority":["x86_64"],"CFBundleVer
sion":"AI-191.8026.42.35.6010548","CFBundleDevelopmentRegion":"English","CFBundl
eDocumentTypes":[{"CFBundleTypeExtensions":["ipr"],"CFBundleTypeName":"Android
Studio Project
File","CFBundleTypeIconFile":"studio.icns","CFBundleTypeRole":"Editor"},{"CFBund
leTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"LSTypeIsPackage":false,"
CFBundleTypeName":"All
documents","CFBundleTypeRole":"Editor"}],"NSSupportsAutomaticGraphicsSwitching":
true,"CFBundlePackageType":"APPL","CFBundleIconFile":"studio.icns","NSHighResolu
tionCapable":true,"CFBundleShortVersionString":"3.5","CFBundleInfoDictionaryVers
ion":"6.0","CFBundleExecutable":"studio","LSRequiresNativeExecution":"YES","CFBu
ndleURLTypes":[{"CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"],"CF
BundleTypeRole":"Editor"}],"CFBundleIdentifier":"com.google.android.studio","LSA
pplicationCategoryType":"public.app-category.developer-tools","CFBundleSignature
":"????","LSMinimumSystemVersion":"10.8","CFBundleGetInfoString":"Android Studio
3.5, build AI-191.8026.42.35.6010548. Copyright JetBrains s.r.o., (c)
2000-2019"}
[   +4 ms] executing: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[  +62 ms] Exit code 0 from: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_202-release"
OpenJDK Runtime Environment (build
1.8.0_202-release-1483-b49-5587405)
OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
[   +2 ms] executing: [/Users/tarek/dev/my_flutter/.android/]
/Users/tarek/dev/my_flutter/.android/gradlew
-I=/Users/tarek/dev/flutter/sdk/packages/flutter_tools/gradle/aar_init_script.g
radle -Pflutter-root=/Users/tarek/dev/flutter/sdk
-Poutput-dir=/Users/tarek/dev/my_flutter/build/host -Pis-plugin=false
-PbuildNumber=1.0 -Ptarget-platform=android-arm,android-arm64,android-x64
assembleAarDebug
[ +621 ms] Configuration on demand is an incubating feature.


FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleAarDebug' not found in root project
'android_generated'. Some candidates are: 'assembleDebug'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with
--stacktrace option to get the stack trace. Run with --info
or --debug option to get more log output. Run with --scan to
get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 482ms
[  +11 ms] Running Gradle task 'assembleAarDebug'... (completed in 0.7s)
[   +1 ms] Configuration on demand is an incubating feature.

[        ]
FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleAarDebug' not found in root project
'android_generated'. Some candidates are: 'assembleDebug'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with
--stacktrace option to get the stack trace. Run with --info or --debug option to
get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 482ms

[   +6 ms] "flutter aar" took 1,020ms.
Gradle task assembleAarDebug failed with exit code 0.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleAar (package:flutter_tools/src/android/gradle.dart:569:5)
#2      _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:74:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#6      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:33:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:292:13)
#11     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:74:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#16     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:682:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#19     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#20     _rootRunUnary (dart:async/zone.dart:1134:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#23     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:682:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#26     Future._asyncComplete.<anonymous closure>
(dart:async/future_impl.dart:556:7)
#27     _rootRun (dart:async/zone.dart:1126:13)
#28     _CustomZone.run (dart:async/zone.dart:1023:19)
#29     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#30     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:965:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#33     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
#34     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by pengzhenkun** [comment]
I got the same error, any update on this?

**Comment by blasten** [comment]
maybe the fix is to run the task :flutter:assembleAarDebug instead of just :assembleAarDebug.  Can someone confirm that this fixes the problem?  To try, cd into the .android directory then run `./gradlew  :flutter:assembleAarDebug`

**Comment by blasten** [comment]
maybe the fix is to run the task :flutter:assembleAarDebug instead of just :assembleAarDebug.  Can someone confirm that this fixes the problem?  To try, cd into the .android directory then run `./gradlew -I=<path-to-flutter-SDK>/packages/flutter_tools/gradle/aar_init_script.g
radle -Pflutter-root=<path-to-flutter-SDK> -Poutput-dir=<path-to-module>/build/host -Pis-plugin=false -PbuildNumber=1.0 -Ptarget-platform=android-arm,android-arm64,android-x64
:flutter:assembleAarDebug`.

**Comment by tarek360** [comment]
For me I found that command wants to access something but it seems like my MacBook doesn't allow because it works when I use `sudo` command. I hope if someone here tell me what is thing in that Flutter command need to a higher level of the user privilege!!

**Comment by pengzhenkun** [comment]
Problem has been solved, thank you very much tarek360

**Comment by Deeplightened** [comment]
Got the same problem here, and `sudo` is not a good solution as created build file have root ownership and therefore cannot be deleted by a non-sudo `flutter clean` (without talking about the risk of launching this type of command with superuser privileges...)

**Comment by Deeplightened** [comment]
My `flutter doctor` if it can help : 

`
[✓] Flutter (Channel master, v1.15.4-pre.117, on Mac OS X 10.14.4 18E226, locale fr-FR)
    • Flutter version 1.15.4-pre.117 at /Users/huriez/Library/flutter
    • Framework revision d030296a97 (il y a 7 jours), 2020-02-20 01:51:15 -0800
    • Engine revision f2f8c342be
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 0f141be8bd)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/huriez/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/huriez/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2018.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 8.0.0 (API 26) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X 10.14.4 18E226
    • Chrome                    • chrome        • web-javascript • Google Chrome 80.0.3987.122
    • Web Server                • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
`

**Comment by jmagman** [comment]
> maybe the fix is to run the task :flutter:assembleAarDebug instead of just :assembleAarDebug. Can someone confirm that this fixes the problem? To try, cd into the .android directory then run `./gradlew -I=<path-to-flutter-SDK>/packages/flutter_tools/gradle/aar_init_script.g radle -Pflutter-root=<path-to-flutter-SDK> -Poutput-dir=<path-to-module>/build/host -Pis-plugin=false -PbuildNumber=1.0 -Ptarget-platform=android-arm,android-arm64,android-x64 :flutter:assembleAarDebug`.

Never got this information...

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Comment by feiyuu** [comment]
我也碰到这个问题了，怎么都解决不了

**Comment by mornville** [comment]
> Problem has been solved, thank you very much tarek360

What'd you do?

**Comment by lynnscode** [comment]
I got the same error
FAILURE: Build failed with an exception.
* What went wrong:
Task 'assembleAarDebug' not found in root project 'android_generated'. Some candidates are: 'assembleDebug'.

**Comment by bulgarian-beast** [comment]
I have finally solve this error:

You have to check, one by one each versions of your dependencies in your pubspec.yaml.
During one week I got stuck bcs my version of path_provider package wasn't the latest.

**Comment by jims57** [comment]
> Got the same problem here, and `sudo` is not a good solution as created build file have root ownership and therefore cannot be deleted by a non-sudo `flutter clean` (without talking about the risk of launching this type of command with superuser privileges...)

I fixed this problem, by running. BTW, you can run: ** xattr -cr .** if simulator doesn't run well.
![image](https://user-images.githubusercontent.com/1920873/88635297-14510480-d0ea-11ea-9d2f-03cba7a01b15.png)

**Comment by johnmelodyme** [comment]
Is the same problem with this: [I actually solve it this way] please do give feedback

Change classpath 
```
'com.android.tools.build:gradle:3.4.2'
``` 
to 
```
classpath 'com.android.tools.build:gradle:4.0.0'
```
to avoid bugs. Reference [Google-Gradle-Android-Build-tool](https://developer.android.com/studio/releases/gradle-plugin)

exception = ```Exception: Gradle task assembleDebug failed with exit code 1```

[Download Gradle Here](https://services.gradle.org/distributions/)

for ClassBuild gradle 

the Exception raised 
```
* What went wrong:                                                      
A problem occurred evaluating project ':app'.                           
> Failed to apply plugin [id 'com.android.internal.version-check']      
   > Minimum supported Gradle version is 6.1.1. Current version is 5.6.2. If using the gradle wrapper, try editing the distributionUrl in /Users/johnmelodyme/Documents/PROJECTS/monjo/monjo/Monjo_Client/monjo/android/gradle/wrapper/gradle-wrapper.properties to gradle-6.1.1-all.zip
```

this exception can be solved easily by going to ```../app/gradle/wrapper/gradlle-wrapper.properties``` and changed the current version of gradle
```
distributionUrl=https\://services.gradle.org/distributions/[your_current_version_of_gradle].zip
```

to 

```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
```

<br />

**Comment by OstAlex** [comment]
If you set 'org.gradle.configureondemand=true' in 'gradle.properties'，please change to false.
It wil be worked !

**Comment by abdelkha** [comment]
any up-to-date solutions? I'm stuck with this error for quite some time! 
I also get **pub upgrade failed (1; no message)** when I try **Pub get**  or **pub upgrade** for any **pubspec.yaml**

**Comment by karianpour** [comment]
> Is the same problem with this: [I actually solve it this way] please do give feedback
> 
> Change classpath
> 
> ```
> 'com.android.tools.build:gradle:3.4.2'
> ```
> 
> to
> 
> ```
> classpath 'com.android.tools.build:gradle:4.0.0'
> ```
> 
> to avoid bugs. Reference [Google-Gradle-Android-Build-tool](https://developer.android.com/studio/releases/gradle-plugin)
> 
> exception = `Exception: Gradle task assembleDebug failed with exit code 1`
> 
> [Download Gradle Here](https://services.gradle.org/distributions/)
> 
> for ClassBuild gradle
> 
> the Exception raised
> 
> ```
> * What went wrong:                                                      
> A problem occurred evaluating project ':app'.                           
> > Failed to apply plugin [id 'com.android.internal.version-check']      
>    > Minimum supported Gradle version is 6.1.1. Current version is 5.6.2. If using the gradle wrapper, try editing the distributionUrl in /Users/johnmelodyme/Documents/PROJECTS/monjo/monjo/Monjo_Client/monjo/android/gradle/wrapper/gradle-wrapper.properties to gradle-6.1.1-all.zip
> ```
> 
> this exception can be solved easily by going to `../app/gradle/wrapper/gradlle-wrapper.properties` and changed the current version of gradle
> 
> ```
> distributionUrl=https\://services.gradle.org/distributions/[your_current_version_of_gradle].zip
> ```
> 
> to
> 
> ```
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
> ```

changing to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip` solved my problem.

**Comment by FaheemuddinKhan** [comment]
Delete the .gradle folder inside the android folder ie android>.gradle

In the project build.gradle file, upgrade ur class path appropriately based on the blog in the link above, e.g i upgraded to classpath 'com.android.tools.build:gradle:4.0.1'

Upgrade the distribution url too. Its in android>gradle>gradle-wrapper.properties file appropriately. e.g i upgraded it to distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip 

You can invalidate caches and restart your android studio. Make sure you have a good internet connection because it will download the new gradle files.

**Comment by JackJonson** [comment]
The dependent plugins in the project were not migrated to androidx, I solve this problem by migrating one of the plugin to AndroidX.

**Comment by Iftiaz-Ahmed** [comment]
This is how I solved my one!

- Deleted the dependency from pubspec.yaml (in my case it was **flutter_facebook_auth: ^3.5.0**)
- Commented out the codes related to the **flutter_facebook_auth** 
- run `flutter clean` 
- Deleted `pubspec.lock` file
- run `flutter pub get`

Then run the app.

Let me know if this solves your problem.
