### ISSUE TITLE
How to simulate dark mode or bright mode in Xcode simulator? I've tried that changing the mode directly in general settings doesn't work, but in IOS native code, Xcode provides a button to simulate the dark mode switch, so how to solve the problem?

### ISSUE THREAD

**Issue by ahai0831** [flutter/flutter#43700]
How to simulate dark mode or bright mode in Xcode simulator? I've tried that changing the mode directly in general settings doesn't work, but in IOS native code, Xcode provides a button to simulate the dark mode switch, so how to solve the problem?

![image](https://user-images.githubusercontent.com/29880468/67743700-64ffd800-fa5a-11e9-93a8-61cae71b20bf.png)

**Comment by kerberjg** [comment]
On the top of the "Developer" settings, in the Settings app in the iOS Simulator you have a "Dark Appearance" switch

![image](https://user-images.githubusercontent.com/16939117/68996962-3e86cd00-08a1-11ea-98bf-fd666e3658dc.png)

**Comment by VladyslavBondarenko** [comment]
Given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
