### ISSUE TITLE
showDialog barrierColor and SafeArea setup ability

### ISSUE THREAD

**Issue by lumenier1** [flutter/flutter#43718]
## Use case

Ability to set overlay color for Dialog also to disable SafeArea for rendering dialog box in full screen mode.

## Proposal

Add few default options to showDialog function:

 - barrierColor: Color
 - safeArea: bool

**Comment by devinsays** [comment]
We've duplicated the [showDialog](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/dialog.dart#L693-L732) as a workaround, but would be really nice to have `barrierColor` exposed.
