### ISSUE TITLE
Check if screen orientation is locked

### ISSUE THREAD

**Issue by andreiafurbeis** [flutter/flutter#43712]
Hi everyone, do you know if there is a way to check if the device rotation has been disabled by the user? 
I tried to search but I can't deal with it

Thanks,
Andrea

**Comment by Romna2208** [comment]
I'm quite interested in detecting this too. Is there a way to do that now?

**Comment by ricardoboss** [comment]
Could be hard to implement since "iOS does not expose an API for you to check if orientation lock is enabled" - @PixelToast on Discord

https://stackoverflow.com/a/5410880
