### ISSUE TITLE
can't compile my app in android studio (OS Error: No such host is known. , errno = 11001)

### ISSUE THREAD

**Issue by Meschack** [flutter/flutter#43714]
i can't compile my app in android studio

**Comment by Meschack** [comment]
OS Error: No such host is known.
, errno = 11001)

**Comment by BondarenkoStas** [comment]
@Meschack please provide the full log, and you flutter doctor -v output.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
