### ISSUE TITLE
Please support `LogicalKeyboardKey.select` for selecting a focussed widget

### ISSUE THREAD

**Issue by sma** [flutter/flutter#43719]
I want to support Android TV with DPAD (cursor keys). Changing the focussed widget works, but selecting it does not. 

It seems, the framework reacts to `LogicalKeyboardKey.enter` (I checked with the Android simulator) but not LogicalKeyboardKey.select` which is emitted by the DPAD (I checked with a real TV).

**Comment by BondarenkoStas** [comment]
@sma I may be wrong, but it's emitted by the DPAD, did you try LogicalKeyboardKey.gameButtonSelect?

**Comment by sma** [comment]
To clarify, I'd like all standard widgets to react to that key so that you can control a normal Flutter app with the TV remote. Right now, `MaterialButton` (and the `InkResponse` that seems to be used to implement touch and focus control) does not react to the DPAD's select button.

**Comment by sma** [comment]
I dug deeper into the SDK and I think a workaround might be to wrap the whole app with

```
Shortcuts(
  shortcuts: {
    LogicalKeySet(LogicalKeyboardKey.select): const Intent(ActivateAction.key),
  },
  child: ...
)
```

which is I widget new to me which I just found in a unit test. I can test this tomorrow when I'm back in the office.

I think, I also found the default list of shortcuts [here](https://github.com/flutter/flutter/blob/38f2d276850c1f204ceda4195bed7abd69f73ff7/packages/flutter/lib/src/widgets/app.dart#L1050).

**Comment by ralphhermes** [comment]
@sma I had the same problem on my Nvidia Shield Android TV and your solution works like a charm. Thank you

**Comment by sabinbajracharya** [comment]
Does this still work? I get "too many positional arguments: 0 expected, but 1 found." as Intent class has no arguments.

**Comment by sma** [comment]
I haven't checked, but you're right, the API has changed. My guess would be that it is now:
```
LogicalKeySet(LogicalKeyboardKey.select): const ActivateIntent(),
```

**Comment by sabinbajracharya** [comment]
I also tired using "ActivateIntent" that but it still did not work for me.
If I manually trigger the key code through adb then the item is selected:
Eg:
`adb shell input keyevent 23` where `23` is `KEYCODE_DPAD_CENTER`
or
`adb shell input keyevent 66` where `66` is `KEYCODE_ENTER `
Both works.

But, pressing "OK" button on the remote does not work even though it fires the `keycode 23` which I verified through the log.
Do you have any suggestion?

**Comment by sma** [comment]
Unfortunately, I cannot help.

We abandoned the idea to use Flutter to create an Android TV app (mainly because text input didn't work at all in mid 2019, haven't checked since then).

**Comment by sabinbajracharya** [comment]
@sma So what do you use? Leanback or React Native for TV? I am currently using Leanback and you really have to fight the framework and sometimes modify the framework itself to get desired behavior.

**Comment by arsenioo** [comment]
This is the working solution for this case: https://stackoverflow.com/a/64545416

But I think that such common case as LogicalKeyboardKey.select should be supported by flutter out of the box just to not reinvent the wheel by each of Android TV (and similar) developers :)

**Comment by daniel-mf** [comment]
None of the workarounds seems to be working now.

**Comment by daniel-mf** [comment]
Tested in a physical TV and it works just fine!

**Comment by devius** [comment]
Select is still not working with IR Remote

**Comment by devius** [comment]
> I want to support Android TV with DPAD (cursor keys). Changing the focussed widget works, but selecting it does not.
> 
> It seems, the framework reacts to `LogicalKeyboardKey.enter` (I checked with the Android simulator) but not LogicalKeyboardKey.select` which is emitted by the DPAD (I checked with a real TV).

Have you find the solution?
I almost finished my application when IR Remote problem occured.
Months of work wasted.
Please help if you can.

**Comment by devius** [comment]
> 

adb shell input dpad keyevent 23 is working, but my IR Remote [Center Key] is not working.
I have tested with RawKeyboardInput and key is working, it shows that Select key is pressed.

Can you help me?

**Comment by devius** [comment]
`════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#1373a(logicalKey: LogicalKeyboardKey#0050c(keyId: "0x10000050c", keyLabel: "Select", debugName: "Select"), physicalKey: PhysicalKeyboardKey#700e4(usbHidUsage: "0x000700e4", debugName: "Control Right"), repeat: false) and its data: RawKeyEventDataAndroid#59c45(flags: 8, codePoint: 0, plainCodePoint: 0, keyCode: 23, scanCode: 97, metaState: 0)
'package:flutter/src/services/raw_keyboard.dart':
package:flutter/…/services/raw_keyboard.dart:1
Failed assertion: line 688 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'`

**Comment by goderbauer** [comment]
Looks like this is available now: https://master-api.flutter.dev/flutter/services/LogicalKeyboardKey/select-constant.html
