### ISSUE TITLE
适配 (adaptation)

### ISSUE THREAD

**Issue by lczsf** [flutter/flutter#43711]
From URL: https://www.flutterchina.club/get-started/install.md

**Comment by BondarenkoStas** [comment]
@lczsf please specify what's the issue?

**Comment by iapicca** [comment]
"Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues."
