### ISSUE TITLE
Failed to establish a debug connection with XXX using mdns: Exception: Did not find a observatory port advertised for $(BUNDLE_IDENTIFIER).

### ISSUE THREAD

**Issue by christian-muertz** [flutter/flutter#43715]
Seems like the flutter tools are struggeling when the bundle identifier is not static!

```
Failed to establish a debug connection with XXX using mdns: Exception: Did not find a observatory port advertised for $(BUNDLE_IDENTIFIER).
```

## Flutter Doctor

```
▶ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.384, on Mac OS X 10.14.6 18G103, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.1)
[✓] Connected device (2 available)

• No issues found!

```

**Comment by christian-muertz** [comment]
```
▶ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.384, on Mac OS X 10.14.6 18G103, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.1)
[✓] Connected device (2 available)

• No issues found!

```

Yes its fixed thx :D

**Comment by agordeev** [comment]
I'm getting the same error with Flutter 1.9.1+hotfix.5 and on iOS 12 device:

```
[  +74 ms] Application launched on the device. Waiting for observatory port.
[   +4 ms] Checking for advertised Dart observatories...
[ +765 ms] Configuring the default Firebase app...
[+4260 ms] Failed to establish a debug connection with c9eb71d88bd18b050788392ce164d6fbfa6f6f7c using mdns: Exception: Did not find a observatory port advertised for com.example.app.
[   +4 ms] mDNS lookup failed, attempting fallback to reading device log.
[        ] Waiting for observatory port.
```

**Comment by thief1010** [comment]
> 我在Flutter 1.9.1 + hotfix.5和iOS 12设备上遇到相同的错误：
> 
> ```
> [  +74 ms] Application launched on the device. Waiting for observatory port.
> [   +4 ms] Checking for advertised Dart observatories...
> [ +765 ms] Configuring the default Firebase app...
> [+4260 ms] Failed to establish a debug connection with c9eb71d88bd18b050788392ce164d6fbfa6f6f7c using mdns: Exception: Did not find a observatory port advertised for com.example.app.
> [   +4 ms] mDNS lookup failed, attempting fallback to reading device log.
> [        ] Waiting for observatory port.
> ```

could you please tell me  if you solved this problem?

**Comment by fryette** [comment]
@thief1010 experienced same issue with 1.9.1+hotfix6 and ios 13

**Comment by zxl777** [comment]
flutter clean
worked for me!

**Comment by TheFedex87** [comment]
@fryette @thief1010 same problem for me. Did you find any solution?

**Comment by fryette** [comment]
@TheFedex87 clean and rebuild helped.
can build on both 1.9.1 and beta channel

**Comment by TheFedex87** [comment]
I already tried to clean and rebuild several times without success
