### ISSUE TITLE
Parts of browser window animate vertically instead of horizontally

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43732]
Issue is https://b.corp.google.com/issues/143464703. Conversation should occur there, please.

cc @chinmaygarde, who's aware of the issue at Google.

**Comment by chinmaygarde** [comment]
Fixed in https://github.com/flutter/engine/pull/13405

**Comment by chinmaygarde** [comment]
This has been patched. A roll past https://github.com/flutter/engine/commit/e3aff2c9821802b2af001e344d0bc393f914790f is necessary for verification.
