### ISSUE TITLE
creating a flutter project (PRODUCT_BUNDLE_IDENTIFIER = {{macosIdentifier}})

### ISSUE THREAD

**Issue by amir037** [flutter/flutter#43734]
hi so im trying to creat a flutter project but in my vs code output this is the error i get:
```
Sending crash report to Google.
Crash report sent (report ID: 8405d4cd44d79065)
Oops; flutter has exited unexpectedly.
Crash report written to D:\Xfiles\amir6\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
exit code 1.
and this is the log file .
```
[flutter_01.log](https://github.com/flutter/flutter/files/3784776/flutter_01.log)

## command
```
flutter --no-color create --template app --description A new Flutter application. --org flutterapp flutter_app
```
## exception
```
TemplateException: Value was missing for variable tag: macosIdentifier. (11:29)
PRODUCT_BUNDLE_IDENTIFIER = {{macosIdentifier}}
                            ^
```

```
#0      Renderer.visitVariable (package:mustache/src/renderer.dart:101:9)
#1      VariableNode.accept (package:mustache/src/node.dart:45:43)
#2      Renderer.render.<anonymous closure> (package:mustache/src/renderer.dart:58:30)
#3      List.forEach (dart:core-patch/growable_array.dart:283:8)
#4      Renderer.render (package:mustache/src/renderer.dart:58:13)
#5      Template.render (package:mustache/src/template.dart:40:14)
#6      Template.renderString (package:mustache/src/template.dart:33:5)
#7      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:172:77)
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#9      Template.render (package:flutter_tools/src/template.dart:124:24)
#10     CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:623:21)
#11     CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:546:23)
<asynchronous suspension>
#12     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:397:37)
<asynchronous suspension>
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#21     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.15063], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\flutter
    • Framework revision 68587a0916 (7 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at F:\androidsdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = F:\androidsdk
    • Java binary at: F:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at F:\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at F:\IntelliJ IDEA 2019.2.1
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

when i go to the folder of the project i dont see the pubspec.yaml file please help me.

**Comment by BondarenkoStas** [comment]
@amir037 Please check https://github.com/flutter/flutter/issues/43431, it's exactly the same issue and possibly it may help.

**Comment by jmagman** [comment]
\cc @stuartmorgan

**Comment by stuartmorgan** [comment]
I'm still at a loss to explain how people are hitting this. The file containing that line *does not exist* in 1.9.1.

Do you have a file at `C:\flutter\packages\flutter_tools\templates\app\macos.tmpl\Runner\Configs\AppInfo.xcconfig.tmpl`? If so, what does `git log C:\flutter\packages\flutter_tools\templates\app\macos.tmpl\Runner\Configs\AppInfo.xcconfig.tmpl` show?

**Comment by amir037** [comment]
i can see that file .but about your second question:  
commit 68587a0916366e9512a78df22c44163d041dd5f3 (HEAD -> stable, tag: v1.9.1+hotfix.6, origin/stable)
Author: LongCatIsLooong <31859944+LongCatIsLooong@users.noreply.github.com>
Date:   Fri Sep 13 19:46:58 2019 -0700

    V1.9.1 hotfix

    This fixes the issue described in https://github.com/flutter/flutter/issues/40239:

    * Restore offstage and ticker mode after hero pop and the from hero is null (#40306)

commit 1aedbb1835bd6eb44550293d57d4d124f19901f0 (tag: v1.9.1+hotfix.5)
Author: Zachary Anderson <zanderso@users.noreply.github.com>
Date:   Thu Oct 17 08:37:27 2019 -0700

    V1.9.1 hotfixes (#42863)

    * refactor cocoapods validator to detect broken install (#38560)
    * Skip pod initialization if version >= 1.8.0. (#41491)

commit cc949a8e8b9cf394b9290a8e80f87af3e207dce5 (tag: v1.9.1+hotfix.4)
Author: Todd Volkert <tvolkert@users.noreply.github.com>
Date:   Fri Sep 27 15:04:59 2019 -0700

    V1.9.1 hotfixes (#41504)

    * [flutter_tools] Report iOS mDNS lookup failures to analytics (#41384)
    * [flutter_tools] Adds tests of mdns analytics events (#41410)
    * [flutter_tool] Add analytics events for ios-mdns fallback success/failure (#41482)
    * roll ideviceinstaller, libimobiledevice, libplist, openssl & usbmuxd to signed versions (#41411)

commit a72edc27064c2cbfbbae17ea1695333e1b3d9595 (tag: v1.9.1+hotfix.3)

**Comment by stuartmorgan** [comment]
That doesn't make sense either; none of those commits touch that file. That just looks like a generic `git log` on the branch.

Does `git status` in C:\flutter show a clean tree with no untracked files?

**Comment by amir037** [comment]
no it has some untracked files listed.
On branch stable
Your branch is up to date with 'origin/stable'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        dev/automated_tests/flutter_test/print_correct_local_widget_expectation.txt
        dev/automated_tests/flutter_test/print_correct_local_widget_test.dart
        dev/automated_tests/test_smoke_test/pending_timer_fail_test.dart
        dev/benchmarks/macrobenchmarks/lib/src/simple_animation.dart
        dev/benchmarks/macrobenchmarks/test_driver/simple_animation_perf.dart
        dev/benchmarks/macrobenchmarks/test_driver/simple_animation_perf_test.dart
        dev/bots/accept_android_sdk_licenses.sh
        dev/bots/debug_smoke_ftl.sh
        dev/bots/test/bot_test.dart
        dev/bots/test/sdk_directory_has_space_test.dart
        dev/bots/test/test_test.dart
        dev/devicelab/bin/tasks/backdrop_filter_perf_ios__timeline_summary.dart
        dev/devicelab/bin/tasks/gradle_non_android_plugin_test.dart
        dev/devicelab/bin/tasks/gradle_r8_test.dart
        dev/devicelab/bin/tasks/plugin_lint_mac.dart
        dev/devicelab/bin/tasks/simple_animation_perf_iphonexs.dart
        dev/devicelab/bin/tasks/smoke_catalina_hot_mode_dev_cycle_ios__benchmark.dart
        dev/devicelab/bin/tasks/smoke_catalina_start_up_ios.dart
        dev/integration_tests/abstract_method_smoke_test/
        dev/integration_tests/android_embedding_2/
        dev/integration_tests/android_embedding_v2_smoke_test/
        dev/integration_tests/android_host_app_v2_embedding/
        dev/integration_tests/android_module_host_with_custom_build_v2_embedding/
        dev/integration_tests/android_semantics_testing/lib/src/tests/popup_constants.dart
        dev/integration_tests/android_semantics_testing/lib/src/tests/popup_page.dart
        dev/integration_tests/channels/ios/Runner.xcworkspace/xcshareddata/
        dev/integration_tests/ios_host_app_swift/
        dev/integration_tests/module_host_with_custom_build_v2_embedding/
        dev/integration_tests/release_smoke_test/android/app/src/androidTest/
        dev/integration_tests/release_smoke_test/ios/Podfile
        dev/integration_tests/release_smoke_test/test_adapter/
        dev/integration_tests/web_compile_tests/
        dev/manual_tests/ios/Runner.xcworkspace/xcshareddata/
        dev/manual_tests/macos/
        dev/snippets/config/skeletons/dartpad-application.html
        dev/snippets/config/templates/stateful_widget_scaffold_center.tmpl
        dev/snippets/config/templates/stateful_widget_scaffold_center_freeform_state.tmpl
        dev/snippets/config/templates/stateless_widget_scaffold_center.tmpl
        examples/flutter_view/ios/Runner.xcworkspace/xcshareddata/
        packages/flutter/lib/src/cupertino/interface_level.dart
        packages/flutter/lib/src/material/button_bar_theme.dart
        packages/flutter/lib/src/material/elevation_overlay.dart
        packages/flutter/lib/src/services/raw_keyboard_web.dart
        packages/flutter/lib/src/widgets/inherited_theme.dart
        packages/flutter/lib/src/widgets/tween_animation_builder.dart
        packages/flutter/test/cupertino/colors_test.dart
        packages/flutter/test/foundation/collections_test.dart
        packages/flutter/test/foundation/observer_list_test.dart
        packages/flutter/test/material/button_bar_theme_test.dart
        packages/flutter/test/material/inherited_theme_test.dart
        packages/flutter/test/painting/strut_style_test.dart
        packages/flutter/test/painting/system_fonts_test.dart
        packages/flutter/test/rendering/editable_gesture_test.dart
        packages/flutter/test/rendering/layer_annotations_test.dart
        packages/flutter/test/rendering/sliver_persistent_header_test.dart
        packages/flutter/test/services/channel_buffers_test.dart
        packages/flutter/test/widgets/binding_attach_root_widget_test.dart
        packages/flutter/test/widgets/binding_frame_scheduling_test.dart
        packages/flutter/test/widgets/html_element_view_test.dart
        packages/flutter/test/widgets/image_data.dart
        packages/flutter/test/widgets/inherited_theme_test.dart
        packages/flutter/test/widgets/run_app_async_test.dart
        packages/flutter/test/widgets/tween_animation_builder_test.dart
        packages/flutter_driver/lib/src/common/wait.dart
        packages/flutter_driver/lib/src/extension/wait_conditions.dart
        packages/flutter_driver/test/src/wait_test.dart
        packages/flutter_localizations/lib/src/l10n/cupertino_en_NZ.arb
        packages/flutter_localizations/lib/src/l10n/material_en_NZ.arb
        packages/flutter_test/lib/src/_binding_io.dart
        packages/flutter_test/lib/src/_binding_web.dart
        packages/flutter_test/lib/src/_goldens_io.dart
        packages/flutter_test/lib/src/_goldens_web.dart
        packages/flutter_test/lib/src/event_simulation.dart
        packages/flutter_test/test/accessibility_window_test.dart
        packages/flutter_test/test/event_simulation_test.dart
        packages/flutter_tools/bin/macos_assemble.sh
        packages/flutter_tools/gradle/flutter_proguard_rules.pro
        packages/flutter_tools/gradle/resolve_dependencies.gradle
        packages/flutter_tools/lib/src/android/android_builder.dart
        packages/flutter_tools/lib/src/base/signals.dart
        packages/flutter_tools/lib/src/build_system/depfile.dart
        packages/flutter_tools/lib/src/build_system/targets/web.dart
        packages/flutter_tools/lib/src/desktop_device.dart
        packages/flutter_tools/lib/src/platform_plugins.dart
        packages/flutter_tools/templates/app/android.tmpl/.gitignore
        packages/flutter_tools/templates/app/ios.tmpl/.gitignore
        packages/flutter_tools/templates/app/macos.tmpl/
        packages/flutter_tools/templates/module/android/library_new_embedding/
        packages/flutter_tools/templates/plugin/macos.tmpl/
        packages/flutter_tools/test/commands.shard/
        packages/flutter_tools/test/general.shard/base/signals_test.dart
        packages/flutter_tools/test/general.shard/build_runner/build_script_test.dart
        packages/flutter_tools/test/general.shard/build_system/depfile_test.dart
        packages/flutter_tools/test/general.shard/build_system/targets/web_test.dart
        packages/flutter_tools/test/general.shard/bundle_shim_test.dart
        packages/flutter_tools/test/general.shard/commands/build_apk_test.dart
        packages/flutter_tools/test/general.shard/commands/build_appbundle_test.dart
        packages/flutter_tools/test/general.shard/dart/sdk_validation_test.dart
        packages/flutter_tools/test/general.shard/desktop_device_test.dart
        packages/flutter_tools/test/general.shard/plugin_parsing_test.dart
        packages/flutter_tools/test/general.shard/plugins_test.dart
        packages/flutter_tools/test/general.shard/web/asset_server_test.dart
        packages/flutter_tools/test/general.shard/web/chrome_test.dart
        packages/flutter_tools/test/src/fake_process_manager.dart
        packages/flutter_tools/test/src/io.dart
        packages/flutter_tools/test/src/throwing_pub.dart
        packages/flutter_web_plugins/

nothing added to commit but untracked files present (use "git add" to track)

**Comment by stuartmorgan** [comment]
> packages/flutter_tools/templates/plugin/macos.tmpl/

This is the problem; you should not have this directory at all. How exactly did you install Flutter? And had you previously installed a different version like master or dev?

**Comment by stuartmorgan** [comment]
The fix for your issue, by the way, is to remove all the untracked files (or at the very least the ones in `templates`).

**Comment by amir037** [comment]
i downloaded the sdk zip and copied its flutter  folder to my hard drive(c)

**Comment by stuartmorgan** [comment]
Did you previously have a different version installed?

**Comment by amir037** [comment]
so thanks every body i just turned on my computer and it worked .but then i have the gradle build problem .which im gonna try and figure out

**Comment by jokonugr** [comment]
> > packages/flutter_tools/templates/app/macos.tmpl/
> 
> This is the problem; you should not have this directory at all. How exactly did you install Flutter? And had you previously installed a different version like master or dev?

I have removed the folder and it fixed mined

**Comment by stuartmorgan** [comment]
For anyone still seeing this with a Flutter tree that is supposed to be on the latest version of stable (1.12): it is still the case that this error indicates that different parts of your Flutter tree are at different versions, but the comments above about how the `macos.tmpl` directory should not exist are now out of date. That directory should now exist on stable, and this error indicates that at least some Dart code in your tree was not actually updated correctly to v1.12+.

`git status` in the Flutter tree is still a useful tool for looking for issues, as anything other than a clean Flutter checkout is likely the problem.

**Comment by yogeshpeculiar** [comment]
> 
> 
> > packages/flutter_tools/templates/app/macos.tmpl/
> 
> This is the problem; you should not have this directory at all. How exactly did you install Flutter? And had you previously installed a different version like master or dev?

this worked for me !!!!
