### ISSUE TITLE
Pesto: FAB doesn't do anything

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4373]

**Comment by mpcomplete** [comment]
@sethladd Does the Pesto FAB have a purpose? The other demos don't do anything with it, and there's no spec for it.

**Comment by eseidelGoogle** [comment]
@HansMuller says many of the buttons in these demos aren't intended to do anything.  We might want to do something here, but lets punt this from this milestone.

**Comment by Hixie** [comment]
We should at least pop up a snackbar saying it's just a demo.

**Comment by dragostis** [comment]
Fixed in #5687.
