### ISSUE TITLE
Cocoon v2 dashboard fails if you go to `http` instead of `https`

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#43737]
Seems like we just need to redirect people to https if they try http.  Lots of CORS errors in the console because it's trying to hit `https://...` from `http://...`.

Alternatively we could make the request just use the current http scheme, but the redirect would be better.

@CaseyHillers

**Comment by CaseyHillers** [comment]
Fixed with https://github.com/flutter/cocoon/pull/522
