### ISSUE TITLE
/api/public/get-status: connect failed with timeout

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#43743]
Hit this when running /api/migrate-checklist (still in development). It queries recent checklist records in datastore, copies over to bigquery, and then updates statuses of those records in datastore.

2019-10-29 19:13:33.474662Z GET 500 30114 ms /api/public/get-status
  30113 ms Error: Uncaught error in request handler: connect failed with timeout
  #0      RedisCacheProvider._createContext (package:neat_cache/src/providers/redis.dart:68:7)
  <asynchronous suspension>
  #1      RedisCacheProvider._getContext (package:neat_cache/src/providers/redis.dart:80:16)
  #2      RedisCacheProvider._withRedis (package:neat_cache/src/providers/redis.dart:113:23)
  <asynchronous suspension>
  #3      RedisCacheProvider.get (package:neat_cache/src/providers/redis.dart:145:40)
  #4      _Entry.get (package:neat_cache/neat_cache.dart:163:38)
  <asynchronous suspension>
  #5      CacheRequestHandler.get (package:cocoon_service/src/request_handling/cache_request_handler.dart:46:71)
  <asynchronous suspension>
  #6      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:28)
  <asynchronous suspension>
  #7      _rootRun (dart:async/zone.dart:1124:13)
  #8      _CustomZone.run (dart:async/zone.dart:1021:19)
  #9      _runZoned (dart:async/zone.dart:1516:10)
  #10     runZoned (dart:async/zone.dart:1463:12)
  #11     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)

**Comment by keyonghan** [comment]
I guess this is related to what you have been doing. Please let me know if not.

**Comment by CaseyHillers** [comment]
Is this from local development, or is it on AppEngine @keyonghan ?

**Comment by keyonghan** [comment]
This issue should have been hit before I ran my APi actually. It may be related to your updated api /get-status.
It is in my local env.

**Comment by CaseyHillers** [comment]
Currently `bin/server.dart` is set up to always use a Redis cache. We need to include a flag of some sorts when running `dart bin/server.dart` to use an in memory cache instead of a redis cache.

https://github.com/flutter/cocoon/blob/master/app_dart/bin/server.dart#L26
```
    final Cache<Uint8List> cache = localDevelopment ? await cacheService.inMemoryCache(256) : await cacheService.redisCache();
```

This would fix the issue

**Comment by keyonghan** [comment]
The issue doesn't seem to reproduce. Closing for now.

**Comment by iskakaushik** [comment]
I'm seeing this again on ToT. I'd like to propose setting some flag.
