### ISSUE TITLE
ListView with focussable ListTiles should scroll focussed widgets into viewport

### ISSUE THREAD

**Issue by sma** [flutter/flutter#43757]
I'm writing (or at least trying to write) an Android TV app which can be controlled by a DPAD (a.k.a. TV remote). I can focus buttons and `ListTile`s inside of `ListView`s just fine but focussed widgets don't stay in the viewport and I have no way to scroll the list. I think, the same problem exists for desktop apps, too.

The focussed widget should automatically stay visible – even if the widget isn't a `ListTile` and hasn't an `onTap` callback. For desktop apps, it would also be nice to use paging keys to page through the list and use Pos1 and End keys to jump to the start and to the end of the list.

Right now, I don't see an easy way (read an available API) to track the focus state of `ListTile`s and/or make a `ScrollController` scroll a widget into view. I'd have to somehow compute the widget's render box's pixel offset and then use that offset with `animateTo` and some local key, I guess.

**Comment by sma** [comment]
This workaround somewhat does what I want, but probably because I don't understand enough about the inner workings for the focus handling stuff, it sometimes fails and doesn't work at all if there are focussable widgets below the list:
```
Focus(
  onKey: (FocusNode focusNode, key) {
    if (key is RawKeyDownEvent) return false;

    final tileFocusNode = focusNode.descendants.firstWhere((f) => f.hasFocus, orElse: () => null);
    if (tileFocusNode == null) return false;

    final position = Scrollable.of(tileFocusNode.context)?.position;
    if (position == null) return false;
    assert(position.axis == Axis.vertical);

    final listRect = focusNode.rect;
    final tileRect = tileFocusNode.rect;

    if (key.logicalKey == LogicalKeyboardKey.arrowUp) {
      final up = tileRect.top - listRect.top;
      if (up < 0) {
        position.jumpTo(position.pixels + up);
      }
    }
    if (key.logicalKey == LogicalKeyboardKey.arrowDown) {
      final down = tileRect.bottom - listRect.bottom;
      if (down > 0) {
        position.jumpTo(position.pixels + down);
      }
    }
    return false;
  },
  child: ListView(...)
}
```

**Comment by gspencergoog** [comment]
@sma, I think I fixed this with https://github.com/flutter/flutter/pull/44965 (already committed to master), but can you please test and see that it does what you want?

**Comment by sma** [comment]
I will gladly do so, but not before the weekend…

**Comment by gspencergoog** [comment]
@sma, thank you!  Anytime that's convenient for you is fine.
