### ISSUE TITLE
An error causes the application to crash due to a space at first

### ISSUE THREAD

**Issue by Shlaayl** [flutter/flutter#43755]
## Steps to Reproduce

There is an error that causes my application crash without any exception. The cause of the error is Text and Textfield when you type in English a space and then type one or two characters. This error exists in a version flutter 1.9.1+hotfix6 and flutter 1.9.1+hotfix5

`Text(' error')`

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by jason-simmons** [comment]
This should be fixed on the master branch - see https://github.com/flutter/flutter/issues/39553

**Comment by Shlaayl** [comment]
> This should be fixed on the master branch - see #39553

yes it is same problem

**Comment by BondarenkoStas** [comment]
@Shlaayl so it's not an issue anymore and can be closed, the fix is in v1.10.6 which is included to dev and beta, and will eventually be in stable.
Or I misunderstood you?

**Comment by Shlaayl** [comment]
thank you

**Comment by Shlaayl** [comment]
> @Shlaayl so it's not an issue anymore and can be closed, the fix is in v1.10.6 which is included to dev and beta, and will eventually be in stable.
> Or I misunderstood you?

thank you
