### ISSUE TITLE
Re-enable --gen-bytecode in gen_snapshot once crashes are resolved.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#43751]
The are currently several issues with the gen-bytecode option that required disabling it entirely. Until these are fixed and verified to work in google3, we probably shouldn't turn it back on.

See google3 issue: b/43536147 and b/143399169

cc @alexmarkov

**Comment by alexmarkov** [comment]
Fixes for both issues rolled into Flutter.
