### ISSUE TITLE
Can I use touch input with virtual keyboard for a flutter web app?

### ISSUE THREAD

**Issue by jdeltoft** [flutter/flutter#43768]
I tried to force open the virtual keyboard with this:

```
  @override
  void initState() {
    SystemChannels.textInput.invokeMethod('TextInput.show');
    super.initState();
  }
```

and this works in a tablet phone app to force open the on screen keyboard, but for the same app running in chrome I couldn't bring open the virtual keyboard to type.  I want to use flutter with a touch screen.

**Comment by BondarenkoStas** [comment]
@jdeltoft I saw your post, will just paste it here in case help there will come faster https://stackoverflow.com/q/58616644/12268368.

**Comment by yjbanov** [comment]
StackOverflow is a good place to discuss this.
