### ISSUE TITLE
Notify package maintainers of breaking changes

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#43777]
## Use case
Many many developers are frustrated by breaking changes in new updates. This is nothing new or surprising and this is not the Flutter team's fault. I understand this is standard development, especially when using a non-stable channel. However, these breaking changes are going to be breaking even on stable, so a notification ahead of time allows devs to account for upcoming changes so that  devs' experience with Flutter, (SDK and community packages) is a stable one.
I know there's an excellent[ google groups mailing list](https://groups.google.com/forum/#!forum/flutter-announce) that announces breaking changes, but I found that group by accident, so I'm sure there are many many other package maintainers who don't know about it. Second, it's not filtered, so it can be difficult for many in our community to read every change and inspect their libraries to make sure it won't affect them.

## Proposal
I have no idea how things work on the inside, but it seems to me like this COULD be a viable solution for packages hosted on pub.dev.

1. Since Google has access to all the source code on pub.dev, it's not a complicated matter to access this for scanning purposes. These packages can be indexed ahead of time when they're uploaded to see what Flutter classes or libraries are being used. (The dart analyzer does similar work to this when offering suggestions etc).
   a. This can also be limited to Verified Publishers to encourage verification and cut down on wasting resources on unmaintained packages.
2. Maintainers can be notified of breaking changes in `master` so they can have enough time to test and release a version for package users running on the `master` channel.
Some devs are firm believers in only supporting the stable version of Flutter, which, although noble, means that those of us who run on the bleeding edge for reasons like important bug fixes, new features necessary to development, etc, can continue to develop.
3. Better advertise the ability to release 2 different "latest" package versions. Such as is done [here](https://pub.dev/packages/cached_network_image#-readme-tab-)
4. Fix the Verified Publisher showing up as Unidentified on [dev releases.](https://pub.dev/packages/cached_network_image/versions/2.0.0-rc)

**Comment by darshankawar** [comment]
I think this might belong to https://github.com/dart-lang/pub/issues or https://github.com/dart-lang/pub-dev/issues.
Hence, closing as such. If anybody disagrees, please write in comments and I'll reopen it.
