### ISSUE TITLE
Determine if Metal needs an off-screen surface

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#43789]
On OpenGL, we use an off-screen rendering surface to improve the performance of BackdropFilters.  However, this seems to come at a penalty of extra CPU/GPU usage overall (https://github.com/flutter/flutter/issues/31865#issuecomment-545162763 and following comments).

Metal doesn't (yet?) use an off-screen surface. We should determine if using one on the Metal backend causes the same increase in CPU/GPU usage, and what impact (if any) not using it has on backdrop filters.

/cc @chinmaygarde @flar @liyuqian

**Comment by chinmaygarde** [comment]
The answer is no. But it is not all good news though. A potential render buffer readback requires disable a [CAMetalLayer optimization](https://github.com/flutter/engine/pull/13643).

The general fix (that helps both OpenGL and Metal) it to perform a render to texture on the subhierarchy that requires a renderbuffer readback.

**Comment by flar** [comment]
In the case of BackdropFilter, the entire background behind the BDF needs to be used as input to the filter. Can that be accomplished under Metal without performing a "renderbuffer readback"?

If it can't, then if we have a BDF, then the subhierarchy that would need the render to texture is the entire tree.

**Comment by chinmaygarde** [comment]
> Can that be accomplished under Metal without performing a "renderbuffer readback"?

No. A readback is necessary in Metal just like when using OpenGL.

> If it can't, then if we have a BDF, then the subhierarchy that would need the render to texture is the entire tree.

Right, or, disable the write-only optimization on the `CAMetalLayer` by setting `framebufferOnly` to `NO`. Either way, the most performant way of doing this is to only render to texture when there is a BDF in the scene and fallback to onscreen rendering otherwise.
