### ISSUE TITLE
TextSelection could misbehave inside a Nested Overlay

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#43787]
The following code can show a couple of problems with the TextSelection on Android.

```dart
import 'package:flutter/material.dart';

class TextSelectionHomePage extends StatefulWidget {
  _TextSelectionHomePageSate createState() => _TextSelectionHomePageSate();
}

class _TextSelectionHomePageSate extends State<TextSelectionHomePage> {

  TextEditingController _controller;
  @override
  void initState() {
    _controller = TextEditingController(
      text: "This is a test that shows some odd behavior with Text Selection!"
    );

    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    Overlay overlay = Overlay(
      initialEntries: [
        OverlayEntry(
          builder: (context) => Center(
              child: TextField(controller: _controller),
          )
        )
      ],
    );

    return Scaffold(
        body: Container(
          color: Colors.grey,
          child: Center(
              child: Container(
                  color: Colors.red,
                  width: 300,
                  height: 600,
                  child: overlay
              )
          ),
        )
    );
  }
}
```

A nested overlay could be desirable for certain reasons, but the TextSelection on Android doesn't do very well with it.
If the overlay's width isn't as wide as what the TextSelection toolbar needs, an overflow can be seen. Also, as you move the cursor around while changing the selection size, the toolbar moves around on the screen as well, which feels weird. Finally, if a ClipRect is placed around the nested overlay, then the Toolbar gets cut off.

Could the TextSelection just use the navigator's overlay instead of the nearest overlay in the tree?

Here is a screenshot of the behavior I'm seeing.

![text_selection_overlay](https://user-images.githubusercontent.com/40898687/67822474-e8d7b580-fa96-11e9-92f9-43d2217ed6c7.png)

**Comment by dannyvalentesonos** [comment]
At the very least, if the toolbar could remain aligned with the overlay it is inside, that would be a huge improvement. The size of the overlay being too small is something a developer would need to avoid I guess, although maybe using an OverflowBox or something could potentially help with that too.

**Comment by dannyvalentesonos** [comment]
Another, much bigger issue found with this, is that tapping on the buttons in the toolbar doesn't register a tap at all, so the toolbar is completely useless.

I also wonder if #42774 could be related to this.

/cc @justinmc

**Comment by dannyvalentesonos** [comment]
@justinmc My original patch proposed in #42774 actually fixes this bug!

**Comment by dannyvalentesonos** [comment]
The following patch fixes the problem. It however, does not fix #42774.

`lib/src/widgets/text_selection.dart` patch

```
--- a/packages/flutter/lib/src/widgets/text_selection.dart	2019-09-22 10:17:46.000000000 -0400
+++ b/packages/flutter/lib/src/widgets/text_selection.dart	2019-10-09 10:14:13.000000000 -0400
@@ -283,12 +283,12 @@
        assert(handlesVisible != null),
        _handlesVisible = handlesVisible,
        _value = value {
-    final OverlayState overlay = Overlay.of(context);
-    assert(overlay != null,
+    _overlay = Overlay.of(context, debugRequiredFor: debugRequiredFor);
+    assert(_overlay != null,
       'No Overlay widget exists above $context.\n'
       'Usually the Navigator created by WidgetsApp provides the overlay. Perhaps your '
       'app content was created above the Navigator with the WidgetsApp builder parameter.');
-    _toolbarController = AnimationController(duration: fadeDuration, vsync: overlay);
+    _toolbarController = AnimationController(duration: fadeDuration, vsync: _overlay);
   }
 
   /// The context in which the selection handles should appear.
@@ -361,6 +361,9 @@
 
   TextEditingValue _value;
 
+  /// The Overlay on which the toolbar and handles will be displayed
+  OverlayState _overlay;
+
   /// A pair of handles. If this is non-null, there are always 2, though the
   /// second is hidden when the selection is collapsed.
   List<OverlayEntry> _handles;
@@ -410,7 +413,7 @@
 
 
 
-    Overlay.of(context, debugRequiredFor: debugRequiredFor).insertAll(_handles);
+    _overlay.insertAll(_handles);
   }
 
   /// Destroys the handles by removing them from overlay.
@@ -426,7 +429,7 @@
   void showToolbar() {
     assert(_toolbar == null);
     _toolbar = OverlayEntry(builder: _buildToolbar);
-    Overlay.of(context, debugRequiredFor: debugRequiredFor).insert(_toolbar);
+    _overlay.insert(_toolbar);
     _toolbarController.forward(from: 0.0);
   }
 
@@ -528,8 +531,8 @@
         renderObject.getEndpointsForSelection(_selection);
 
     final Rect editingRegion = Rect.fromPoints(
-      renderObject.localToGlobal(Offset.zero),
-      renderObject.localToGlobal(renderObject.size.bottomRight(Offset.zero)),
+      renderObject.localToGlobal(Offset.zero, ancestor: _overlay.context?.findRenderObject()),
+      renderObject.localToGlobal(renderObject.size.bottomRight(Offset.zero), ancestor: _overlay.context?.findRenderObject()),
     );
 
     final bool isMultiline = endpoints.last.point.dy - endpoints.first.point.dy >
```

**Comment by dannyvalentesonos** [comment]
The patch fixes the alignment issue and the touch issues. It does not fix the overflow issue.

**Comment by dannyvalentesonos** [comment]
Another patch is needed for the Material text selection code, as it uses the screen size for laying out the toolbar.

`lib/src/material/text_selection.dart` patch

```
--- a/packages/flutter/lib/src/material/text_selection.dart	2019-11-01 13:46:10.000000000 -0400
+++ b/packages/flutter/lib/src/material/text_selection.dart	2019-11-01 13:42:34.000000000 -0400
@@ -162,11 +162,13 @@
         : startTextSelectionPoint.point.dy + _kToolbarHeight + _kToolbarContentDistanceBelow;
     final Offset preciseMidpoint = Offset(position.dx, y);
 
+    // get the Overlay's render box
+    RenderBox overlayBox = Overlay.of(context).context?.findRenderObject();
     return ConstrainedBox(
       constraints: BoxConstraints.tight(globalEditableRegion.size),
       child: CustomSingleChildLayout(
         delegate: _TextSelectionToolbarLayout(
-          MediaQuery.of(context).size,
+          overlayBox.size,
           globalEditableRegion,
           preciseMidpoint,
         ),

```

**Comment by dannyvalentesonos** [comment]
I have created another separate bug for the Overflow issue, because it also happens without a nested overlay, when the device has the Large Display setting turned on.

The bug is #44005.

**Comment by Hixie** [comment]
It sounds like the problem is that the toolbar is going outside its overlay, in which case the hit testing is expected not to work, since the hits would only get to the toolbar if they're first inside the overlay.

Seems like we probably just want to always use the outermost overlay ("rootmost" maybe) when displaying a toolbar. That would be consistent with the Android platform's behaviour of having the toolbar be a floating window.

**Comment by dannyvalentesonos** [comment]
@Hixie  Yes, if I try to do the type of thing I'm trying to accomplish, but in native Android, the toolbar would float around outside of the equivalent parent view. So I think that your idea is also a suitable one to handle this, as it would be consistent with expectations there. Are there any plans to do some kind of overflow menu to fix #44005 and a magnifying lens effect for text selection?

**Comment by Hixie** [comment]
The "plan" is for us to fix all our bugs, especially fidelity bugs like that one. The question is more one of timeline, and that is much harder to predict...

**Comment by justinmc** [comment]
The text selection overflow problem is being tracked in https://github.com/flutter/flutter/issues/35826, and someone has opened a pull request in progress for the overflow menu in https://github.com/flutter/flutter/pull/39624.  I think that overflow problem is probably the most embarrassing bug on my radar right now, so I hope we can finish a fix for it soon.

The magnifying glass effect is being tracked in https://github.com/flutter/flutter/issues/9507.  It lost a bit of steam when Apple removed it from iOS13, but we should still implement it for Android.

**Comment by dannyvalentesonos** [comment]
I've got a working solution to using the root overlay. We'll update our PR in the coming days/weeks.

**Comment by shihchanghsiungsonos** [comment]
I have updated the PR "ef94e59b6" to commit Danny's solution.

From the original PR, I tried to revert the change in "packages/flutter/lib/src/material/text_selection.dart", but I might have deleted the file instead. Can't find a way to revert the deletion. Need help on that and review the new changes. Thanks!

**Comment by shihchanghsiungsonos** [comment]
Okay. i have got everything in the PR back on track now. Please review the PR to using the root overlay. Thanks!

https://github.com/flutter/flutter/pull/44018

**Comment by dannyvalentesonos** [comment]
@justinmc @Hixie  Have you taken a look at the PR #44018?

**Comment by justinmc** [comment]
Just submitting a review, sorry for the delay!
