### ISSUE TITLE
CanvasKit backend should support RichText

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#43782]
The CanvasKit backend assumes `drawParagraph` is getting plain text, and crashes when it gets rich text.

**Comment by moulikcipherX** [comment]
Hi @hterkelsen, How can I proceed with this issue?

**Comment by hterkelsen** [comment]
This is mostly supported now: need support for custom font family names, though.

**Comment by hterkelsen** [comment]
Custom font family names landed very recently. When there is a CanvasKit release that includes the change, we can start using it and close this bug

**Comment by hterkelsen** [comment]
Fixed in https://github.com/flutter/engine/pull/16504
