### ISSUE TITLE
Ios release build sticks on launch screen and gives - 425: error: unreachable code

### ISSUE THREAD

**Issue by CarsonC01** [flutter/flutter#43794]
Hi,
I have an error, whenever I run my Flutter Ios app in release rather than debug it crashes (which means I can't get it onto the the app store). It all works fine and is well tested in debug.
Here is the error I receive:

> 2019-10-30 11:32:50.399125+0800 Runner[1326:423364] Metal API Validation Enabled
../../third_party/dart/runtime/vm/exceptions.cc: 425: error: unreachable code

I'd really appreciate any help with the solving this, as I'm completely stuck
Thanks

**Comment by jonahwilliams** [comment]
Please include the output of `flutter doctor -v`

**Comment by CarsonC01** [comment]
Sure Jonah, here it is...

> [✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.14.6 18G95, locale en-ID)
    • Flutter version 1.10.7 at /Users/carsoncarbery/development/tools/flutter
    • Framework revision e70236e36c (4 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/carsoncarbery/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 183.5912.23
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 8.1.0 (API 27) (emulator)
    • Carson                    • ade4d6708fd6a36d87ce3cc2d2c078371a423e2e • ios         • iOS 13.1.3
    • iPhone 8                  • D56A4505-1B43-4AFA-9FA7-E60C5F6669CE     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

**Comment by BondarenkoStas** [comment]
@CarsonC01 I suspect it may be the same as https://github.com/dart-lang/sdk/issues/38700 which was fixed on dart 2.6.0-dev.8.0. Can you please try running on master channel? It uses 2.6.0-dev.8.2 which should include the fix (it that's the same issue)

**Comment by CarsonC01** [comment]
Hi, thanks for the help, this does indeed look like the same error. One of the first things I did when receiving this error was to do a flutter upgrade, but that still leaves me on dart 2.6.0-dev.8.0. 
I'm a little new to this, can you let me know how to run this on the master channel that you suggest?

**Comment by CarsonC01** [comment]
Hi, many thanks this solved the issue. I am a little new to this, so would like to ask should I switch my channel back to Beta and then just put it on Master when I need to release to the app store? Just asking for the general advice I guess. Thanks again.

**Comment by jonahwilliams** [comment]
In general I recommend sticking to the stable branches unless you absolutely need a feature from the latest releases.

Depending on your patience, you might wait for the next dev release (several days) which should have the fix, and switch from beta to dev.
