### ISSUE TITLE
My app is not retrieving values from Jason and no error is generated 

### ISSUE THREAD

**Issue by DBSumation** [flutter/flutter#43796]
My app is not retrieving values from Jason and no error is generated 

=========

Class Stock.dart 
==========
        `import 'dart:convert';

        Stocks stocksFromJson(String str) => Stocks.fromJson(json.decode(str));

        String stocksToJson(Stocks data) => json.encode(data.toJson());

        class Stocks {
          String symbol;
          String companyName;
          String primaryExchange;
          String calculationPrice;
          int open;
          int openTime;
          double close;
          int closeTime;
          double high;
          double low;
          double latestPrice;
          String latestSource;
          String latestTime;
          int latestUpdate;
          int latestVolume;
          dynamic iexRealtimePrice;
          dynamic iexRealtimeSize;
          dynamic iexLastUpdated;
          double delayedPrice;
          int delayedPriceTime;
          double extendedPrice;
          double extendedChange;
          double extendedChangePercent;
          int extendedPriceTime;
          double previousClose;
          int previousVolume;
          int change;
          double changePercent;
          int volume;
          dynamic iexMarketPercent;
          dynamic iexVolume;
          int avgTotalVolume;
          dynamic iexBidPrice;
          dynamic iexBidSize;
          dynamic iexAskPrice;
          dynamic iexAskSize;
          int marketCap;
          double peRatio;
          double week52High;
          int week52Low;
          double ytdChange;
          int lastTradeTime;
          bool isUsMarketOpen;

          Stocks({
            this.symbol,
            this.companyName,
            this.primaryExchange,
            this.calculationPrice,
            this.open,
            this.openTime,
            this.close,
            this.closeTime,
            this.high,
            this.low,
            this.latestPrice,
            this.latestSource,
            this.latestTime,
            this.latestUpdate,
            this.latestVolume,
            this.iexRealtimePrice,
            this.iexRealtimeSize,
            this.iexLastUpdated,
            this.delayedPrice,
            this.delayedPriceTime,
            this.extendedPrice,
            this.extendedChange,
            this.extendedChangePercent,
            this.extendedPriceTime,
            this.previousClose,
            this.previousVolume,
            this.change,
            this.changePercent,
            this.volume,
            this.iexMarketPercent,
            this.iexVolume,
            this.avgTotalVolume,
            this.iexBidPrice,
            this.iexBidSize,
            this.iexAskPrice,
            this.iexAskSize,
            this.marketCap,
            this.peRatio,
            this.week52High,
            this.week52Low,
            this.ytdChange,
            this.lastTradeTime,
            this.isUsMarketOpen,
          });

          factory Stocks.fromJson(Map<String, dynamic> json) => Stocks(
            symbol: json["symbol"],
            companyName: json["companyName"],
            primaryExchange: json["primaryExchange"],
            calculationPrice: json["calculationPrice"],
            open: json["open"],
            openTime: json["openTime"],
            close: json["close"].toDouble(),
            closeTime: json["closeTime"],
            high: json["high"].toDouble(),
            low: json["low"].toDouble(),
            latestPrice: json["latestPrice"].toDouble(),
            latestSource: json["latestSource"],
            latestTime: json["latestTime"],
            latestUpdate: json["latestUpdate"],
            latestVolume: json["latestVolume"],
            iexRealtimePrice: json["iexRealtimePrice"],
            iexRealtimeSize: json["iexRealtimeSize"],
            iexLastUpdated: json["iexLastUpdated"],
            delayedPrice: json["delayedPrice"].toDouble(),
            delayedPriceTime: json["delayedPriceTime"],
            extendedPrice: json["extendedPrice"].toDouble(),
            extendedChange: json["extendedChange"].toDouble(),
            extendedChangePercent: json["extendedChangePercent"].toDouble(),
            extendedPriceTime: json["extendedPriceTime"],
            previousClose: json["previousClose"].toDouble(),
            previousVolume: json["previousVolume"],
            change: json["change"],
            changePercent: json["changePercent"].toDouble(),
            volume: json["volume"],
            iexMarketPercent: json["iexMarketPercent"],
            iexVolume: json["iexVolume"],
            avgTotalVolume: json["avgTotalVolume"],
            iexBidPrice: json["iexBidPrice"],
            iexBidSize: json["iexBidSize"],
            iexAskPrice: json["iexAskPrice"],
            iexAskSize: json["iexAskSize"],
            marketCap: json["marketCap"],
            peRatio: json["peRatio"].toDouble(),
            week52High: json["week52High"].toDouble(),
            week52Low: json["week52Low"],
            ytdChange: json["ytdChange"].toDouble(),
            lastTradeTime: json["lastTradeTime"],
            isUsMarketOpen: json["isUSMarketOpen"],
          );

          Map<String, dynamic> toJson() => {
            "symbol": symbol,
            "companyName": companyName,
            "primaryExchange": primaryExchange,
            "calculationPrice": calculationPrice,
            "open": open,
            "openTime": openTime,
            "close": close,
            "closeTime": closeTime,
            "high": high,
            "low": low,
            "latestPrice": latestPrice,
            "latestSource": latestSource,
            "latestTime": latestTime,
            "latestUpdate": latestUpdate,
            "latestVolume": latestVolume,
            "iexRealtimePrice": iexRealtimePrice,
            "iexRealtimeSize": iexRealtimeSize,
            "iexLastUpdated": iexLastUpdated,
            "delayedPrice": delayedPrice,
            "delayedPriceTime": delayedPriceTime,
            "extendedPrice": extendedPrice,
            "extendedChange": extendedChange,
            "extendedChangePercent": extendedChangePercent,
            "extendedPriceTime": extendedPriceTime,
            "previousClose": previousClose,
            "previousVolume": previousVolume,
            "change": change,
            "changePercent": changePercent,
            "volume": volume,
            "iexMarketPercent": iexMarketPercent,
            "iexVolume": iexVolume,
            "avgTotalVolume": avgTotalVolume,
            "iexBidPrice": iexBidPrice,
            "iexBidSize": iexBidSize,
            "iexAskPrice": iexAskPrice,
            "iexAskSize": iexAskSize,
            "marketCap": marketCap,
            "peRatio": peRatio,
            "week52High": week52High,
            "week52Low": week52Low,
            "ytdChange": ytdChange,
            "lastTradeTime": lastTradeTime,
            "isUSMarketOpen": isUsMarketOpen,
          };
        }`

Stock_reposiroty.dart 
==============
      `import 'package:http/http.dart' as http;
      import 'dart:convert';
      import '../models/stocks.dart';

      Future<Map<String,dynamic>> getStocks() async {

       // final String url = 'https://cloud.iexapis.com/stable/stock/market/batch?symbols=aapl,fb&types=quote&token=';
      //  final client = new http.Client();
       // final streamedRest = await client.send(
          //  http.Request('get', Uri.parse(url))

        const url = 'https://cloud.iexapis.com/stable/stock/market/batch? 
        symbols=aapl,fb&types=quote&token=';
        final response = await http.get(url);
        final decodedResponse = json.decode(response.body).keys();
        final data = Stocks.fromJson(decodedResponse);

        //http.Response response = await http.get(Uri, headers: {"Accept": "application/json"});
        //print(jsonDecode(response.body).keys());
        return jsonDecode(response.body).keys();`

> Running the app does not generate any results 

![image](https://user-images.githubusercontent.com/37802537/67827358-23951a00-faa6-11e9-97be-d170f165e2af.png)

log:
======

> Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
I/OpenGLRenderer( 4854): Initialized EGL, version 1.4
D/OpenGLRenderer( 4854): Swap behavior 1
D/        ( 4854): HostConnection::get() New Host Connection established 0xdc20bf00, tid 4881
D/EGL_emulation( 4854): eglCreateContext: 0xe3d47760: maj 2 min 0 rcv 2
D/EGL_emulation( 4854): eglMakeCurrent: 0xe3d47760: ver 2 0 (tinfo 0xc6b24a30)
D/        ( 4854): HostConnection::get() New Host Connection established 0xc6b386c0, tid 4874
D/EGL_emulation( 4854): eglCreateContext: 0xdc27d780: maj 2 min 0 rcv 2
D/EGL_emulation( 4854): eglMakeCurrent: 0xdc27d780: ver 2 0 (tinfo 0xc6b24dc0)
Syncing files to device Android SDK built for x86...
I/Choreographer( 4854): Skipped 279 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 4854): eglMakeCurrent: 0xe3d47760: ver 2 0 (tinfo 0xc6b24a30)
I/OpenGLRenderer( 4854): Davey! duration=6180ms; Flags=1, IntendedVsync=596431275408, Vsync=601081275222, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=601083214976, AnimationStart=601083253387, PerformTraversalsStart=601083255696, DrawStart=601096302305, SyncQueued=601333900000, SyncStart=601335418694, IssueDrawCommandsStart=601335535183, SwapBuffers=602308827762, FrameCompleted=602612881859, DequeueBufferDuration=66828000, QueueBufferDuration=276000, 
D/EGL_emulation( 4854): eglMakeCurrent: 0xdc27d780: ver 2 0 (tinfo 0xc6b24dc0)

**Comment by ThinkDigitalSoftware** [comment]
Have you asked this in a support forum? Also, if this is an actual sdk error, this would be a Dart error and not a Flutter one.

**Comment by superciccio** [comment]
@DBSumation you need to pass the token, it cannot be empty
is a get url and if you try it in the browser you see an error

**Comment by DBSumation** [comment]
> @DBSumation you need to pass the token, it cannot be empty
> is a get url and if you try it in the browser you see an error

The token was removed for security since it private but it works  

> {"AAPL":{"quote":{"symbol":"AAPL","companyName":"Apple, Inc.","primaryExchange":"NASDAQ","calculationPrice":"close","open":null,"openTime":null,"close":null,"closeTime":null,"high":null,"low":null,"latestPrice":243.29,"latestSource":"Close","latestTime":"October 29, 2019","latestUpdate":1572379200437,"latestVolume":null,"iexRealtimePrice":0,"iexRealtimeSize":0,"iexLastUpdated":0,"delayedPrice":null,"delayedPriceTime":null,"extendedPrice":null,"extendedChange":null,"extendedChangePercent":null,"extendedPriceTime":null,"previousClose":249.05,"previousVolume":24143241,"change":-5.76,"changePercent":-0.02313,"volume":null,"iexMarketPercent":null,"iexVolume":0,"avgTotalVolume":26888064,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":1099471302200,"peRatio":20.57,"week52High":249.75,"week52Low":142,"ytdChange":0.51746,"lastTradeTime":1572379201593,"isUSMarketOpen":false}},"FB":{"quote":{"symbol":"FB","companyName":"Facebook, Inc.","primaryExchange":"NASDAQ","calculationPrice":"close","open":null,"openTime":null,"close":null,"closeTime":null,"high":null,"low":null,"latestPrice":189.31,"latestSource":"Close","latestTime":"October 29, 2019","latestUpdate":1572379200548,"latestVolume":null,"iexRealtimePrice":0,"iexRealtimeSize":0,"iexLastUpdated":0,"delayedPrice":null,"delayedPriceTime":null,"extendedPrice":null,"extendedChange":null,"extendedChangePercent":null,"extendedPriceTime":null,"previousClose":189.4,"previousVolume":13657866,"change":-0.09,"changePercent":-0.00048,"volume":null,"iexMarketPercent":null,"iexVolume":0,"avgTotalVolume":13113772,"iexBidPrice":0,"iexBidSize":0,"iexAskPrice":0,"iexAskSize":0,"marketCap":540091465100,"peRatio":31.85,"week52High":208.66,"week52Low":123.02,"ytdChange":0.39478800000000003,"lastTradeTime":1572379201588,"isUSMarketOpen":false}}}

**Comment by superciccio** [comment]
well if you do have a response, the only failure point is the way you map it :)

**Comment by DBSumation** [comment]
> Have you asked this in a support forum? Also, if this is an actual sdk error, this would be a Dart error and not a Flutter one.

Can you provide the  "Support forum" url?  if this is the one https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/flutter-dev no luck there...

**Comment by escamoteur** [comment]
Please ask such questions on [stackoverflow](stackoverflow.com) , because we unfortunately not able to give individual development support here. 
This place is only for reporting bugs or suggesting new features.
