### ISSUE TITLE
[flutter][ios] flutter run fails when running on iOS with import/include build errors

### ISSUE THREAD

**Issue by sujithv28** [flutter/flutter#43799]
For some reason, with a fresh install of `flutter` on Mac OS Catalina with Xcode 11.1 installed (nothing is beta), I can't get `flutter run` working for iOS. I tried it with a fresh project on both the `stable` channel and the `beta` channel with no luck.

Interestingly enough, this succeeds and is able to work on an android simulator. Both Catalina and Xcode are downloaded and installed from the mac appstore. I've also tried this but it was not my issue: https://github.com/flutter/flutter/issues/24428

## Steps to Reproduce
1. `flutter create testapp`
2. `cd testapp`
3. `flutter clean`
4. `flutter run`

I also tried things like `flutter precache` etc but nothing worked.

**Target Platform:** iOS
**Target OS version/browser:**
**Devices:** Simulator iPhone 11 Pro

## Logs

**Note:** the logs were too long to fit so I attached it to a text file.
[logs.txt](https://github.com/flutter/flutter/files/3787140/logs.txt)

```
Analyzing testapp...
No issues found! (ran in 3.3s)
```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.9.1+hotfix.6 at /Users/sujith/Developer/flutter
    • Framework revision 68587a0916 (7 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sujith/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • iPhone 11 Pro • 01C8D785-5C73-4EF3-AEAA-B96F3B336D91 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!
```

**Comment by jmagman** [comment]
I wasn't able to reproduce on v1.9.1+hotfix.6.
From the attached logs:
```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk/usr/include/module.modulemap:1:8: error: redefinition of module 'AppleTextureEncoder'
               module AppleTextureEncoder [system] [extern_c] {
                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/module.modulemap:1:8: note: previously defined here
               module AppleTextureEncoder [system] [extern_c] {
```
Hm, why are modules being imported from both the iPhoneSimulator13.1 SDK _and_ MacOSX10.15?

**Comment by sujithv28** [comment]
Good point, I actually just saw that as well and noticed that I the following line in my `.bash_profile`:

```
export CPATH="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include"
```

This was messing things up and removing it seemed to fix Flutter for me! Thanks a lot for helping me catch that @jmagman!

**Comment by josiahkhoo** [comment]
Hi, it appears that I'm facing the same issue as @sujithv28. I'm on Mac OS Catalina 10.15.2 and Xcode 11.3, I'm using zsh instead of bash and did not have the additional line mentioned above in @sujithv28's bash profile. Any idea how I can fix this?

**Comment by jmagman** [comment]
@josiahkhoo Can you file a new issue with your logs?  Please confirm you're able to build a new iOS app created in Xcode without Flutter to rule out Xcode setup issues.
