### ISSUE TITLE
[web] How to start a 'normal' Chrome instance? Chrome extensions are needed for development.

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#43809]
Some use-cases need extensions for development (e.g. the MetaMask extension injects a web3 object into every page).

Is there a way to start the 'normal' Chrome instance with flutter run -d chrome?

**Comment by modulovalue** [comment]
I found a temporary fix:

The relevant lines for this are here: https://github.com/flutter/flutter/blob/450a72488d6252168ec1628750d292ef7c87c317/packages/flutter_tools/lib/src/web/chrome.dart#L96-L112
To rebuild the flutter tool see here https://stackoverflow.com/questions/44487204/alternative-methods-for-rebuilding-flutter-tools

**Comment by yjbanov** [comment]
We have two options of running an app without automatically starting Chrome for you:

- `flutter run -d web-server` will run a plain server for you to open in your own browser.
- `flutter run -d chrome --no-web-browser-launch` will run in debug mode and requires Dart debug extension (@jonahwilliams might have more details).

/cc @sfshaza2 - this might be a good thing to document

**Comment by modulovalue** [comment]
> flutter run -d web-server will run a plain server for you to open in your own browser.

> Performing hot restart...                                           0,9s
Recompile complete. Page requires refresh.

That's quite inconvenient as the user has to manually refresh the page on each change and is forced to set a custom port if he doesn't want to also copy the url on each build. Speed during development is of utmost importance to me and this is not optimal.

> flutter run -d chrome --no-web-browser-launch

I did not manage to get that to work. All I get from the Dart Debug Extension is "Unable to launch DevTools. This is not Dart application.".

**Comment by tomasdev** [comment]
Just copy the URL and paste it in your regular Chrome window -- much more efficient.

**Comment by tarekbazine** [comment]
@tomasdev I am not sure how you see this efficient ( I might miss something here ), since when you open the link in another Chrome instance you won't be able to use the dev-tools because the debugger is attached to the opened Chrome ...

**Comment by davelewicki** [comment]
1) @modulovalue - that's a great fix.  Easy enough to do (and git stash/pop when upgrading flutter).   -- thanks! 
2) the default of a fresh chrome profile every time breaks using Android Studio launch along w/ local storage.    Would be great to see a less 'temporary' fix by allowing an option to set the profile
