### ISSUE TITLE
TabBarView issue

### ISSUE THREAD

**Issue by aabanaag** [flutter/flutter#43807]
## Steps to Reproduce

1. Create tabbarview with 3 tabs (A, B, C)
2. From initial tab, tap the last one. (e.g from A to directly to C)

The bug causes an issue on tabB being rendered despite the selectedTab was set to tabC. 

![bug](https://user-images.githubusercontent.com/2245822/67848388-8a1a4680-fb3f-11e9-90ff-7d2b15263ffb.gif)

**Target Platform: iOS**
**Target OS version/browser: iOS/Android**
**Devices: iPhone XS Max emulator**

## Logs

```
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A602, locale en-PH)
    • Flutter version 1.9.1+hotfix.6 at /Users/aabanaag/Documents/framework/flutter
    • Framework revision 68587a0916 (7 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/aabanaag/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 93077220-9D0F-4AF2-A5C4-5EF99059D40B • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!
```

**Comment by aabanaag** [comment]
I couldn't find an exact issue related to this one but if its a duplicate to an existing issue kindly let me know and I'll close this. thanks!

**Comment by wilburt** [comment]
Please, can you provide a small reproducible code?

**Comment by aabanaag** [comment]
Sure. I'll attach it here in a while.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
