### ISSUE TITLE
[iOS] Scaffold resizes when you come from an app with the keyboard open

### ISSUE THREAD

**Issue by jamesblasco** [flutter/flutter#43804]
This problem occurs whenever the keyboard is raised in other apps and return to the app

## Steps to Reproduce
Open an app like messages and tap in a field, when the keyboard is on the screen, slide back to your app. The flutter app will resize weirdly for a moment. 

Demo with gallery app
<img src="https://user-images.githubusercontent.com/19904063/67842395-608afc00-fafa-11e9-8f15-bbf2faa5436f.gif" height="300">

**Target Platform:** iOS
**Target OS version/browser:** 12/13
**Devices:** Simulator/iPhone X

```
[✓] Flutter (Channel master, v1.10.15-pre.205, on Mac OS X 10.15 19A602, locale es-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (4 available)
```

**Comment by jamesblasco** [comment]
The workaround to avoid this is: in your Scaffold, set resizeToAvoidBottomInset property to false.
It desactives the resize of the scaffold when the keyboard pop ups. You should be careful in the scaffolds where you want to use the keyboard

**Comment by sroddy** [comment]
I think this is the real cause of this other observed issue:
https://github.com/flutter/flutter/issues/41679

**Comment by ChinaFishNews** [comment]
> The workaround to avoid this is: in your Scaffold, set resizeToAvoidBottomInset property to false.
> It desactives the resize of the scaffold when the keyboard pop ups. You should be careful in the scaffolds where you want to use the keyboard

Resolved, thanks

This problem occurs whenever the keyboard is raised  in other apps and  return to the app

**Comment by jamesblasco** [comment]
This is fixed at [16270](https://github.com/flutter/engine/pull/16270)

**Comment by athornz** [comment]
I'm running an app from the latest Flutter dev branch and still seeing this issue.
