### ISSUE TITLE
How I use my customized engine to build an android flutter apk with aot mode by command or in android studio?

### ISSUE THREAD

**Issue by ping996** [flutter/flutter#43803]
How I use my customed engine(I have add some logic to engine and compile engine with android_release_arm64 and host_release) to build an android flutter apk with aot mode by command or in android studio?

**Comment by kf6gpe** [comment]
This would be a good thing to add to the engine repo documentation.

**Comment by jonahwilliams** [comment]
You can build with the flutter tools' local-engine flags. Documentation is on the flutter CLI.
