### ISSUE TITLE
How to achieve ListView smooth scrolling in Flutter

### ISSUE THREAD

**Issue by dimiril** [flutter/flutter#43808]
I have created a list view with network images and when I am trying to scroll the listview it's scrolling is not smooths it feels like jerking. For caching I have used cached_network_image: any, this library itself working fine but listview is not getting scrolled smooth.

**Comment by Zazo032** [comment]
Could you provide a minimum code sample to reproduce the issue? Are you using a `profile`/`release` build to test performance? Could you also provide the output of `flutter doctor -v`?

**Comment by dimiril** [comment]
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [version 10.0.18362.418], locale fr-FR)
    • Flutter version 1.9.1+hotfix.6 at C:\Users\zoom\flutter
    • Framework revision 68587a0916 (7 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\zoom\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6527

[!] Connected device
    ! No devices available

**Comment by dimiril** [comment]
@override
  Widget build(BuildContext context) {
    Size media = MediaQuery.of(context).size;
    return ListView.builder(
          shrinkWrap: true,
          physics: NeverScrollableScrollPhysics(),
          itemCount: names.length + 1,
          itemBuilder: (BuildContext context, index) {
            if (index == names.length) {
              return _buildProgressIndicator();
            } else {
              return InkWell(
      onTap: () {
        Navigator.push(
          context,
          SlideTopRoute(page: ShowPost(data: datax)),
        );
      },
      child: Container(
        width: media.width,
        padding: EdgeInsets.only(
            top: 10.0, right: 15.0, left: 15.0, bottom: 0.0),
        constraints: BoxConstraints(
            minHeight: 100.0),
        decoration: BoxDecoration(
          color: Color(0xffffffff),
          border: Border(
            bottom: BorderSide(
              color: Color(0xfff7f7f7),
              width: 10.0,
              style: BorderStyle.solid,
            ),
          ),
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            Container(
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: <Widget>[
                  Material(
                    color: Color(0xffffffff),
                    child: Row(
                      children: <Widget>[
                        Container(
                          width: 45,
                          height: 45,
                          decoration: BoxDecoration(
                            shape: BoxShape.circle,
                            image: DecorationImage(
                              fit: BoxFit.cover,
                              image: NetworkImage(widget.avatar),
                            ),
                          ),
                        ),
                        SizedBox(
                          width: 10,
                        ),
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: <Widget>[
                            Material(
                              color: Color(0xffffffff),
                              child: Text(widget.userName,
                                  style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      fontSize: 12,
                                      color: Color(0xFF404040))),
                            ),
                            SizedBox(
                              height: 3,
                            ),
                            Material(
                              color: Color(0xffffffff),
                              child: Text(widget.userGroup,
                                  style: TextStyle(
                                      fontWeight: FontWeight.normal,
                                      fontSize: 11,
                                      color: Color(0xff999999))),
                            )
                          ],
                        ),
                      ],
                    ),
                  ),
                  GestureDetector(
                    onTap: () {
                      if (isSelected) {
                        setState(() {
                          isSelected = false;
                          Fluttertoast.showToast(msg: "");
                        });
                      } else {
                        setState(() {
                          isSelected = true;
                          Fluttertoast.showToast(msg: "");
                        });
                      }
                    },
                    child: Material(
                      color: isSelected ? Color(0xfff38181) : Color(0xffffffff),
                      child: Container(
                        padding: EdgeInsets.only(
                            top: 2.0,
                            right: 15.0,
                            bottom: 2.0,
                            left: 15.0),
                        decoration: BoxDecoration(
                            borderRadius:
                            BorderRadius.all(Radius.circular(5.0)),
                            border: Border.all(
                                width: 1,
                                style: BorderStyle.solid,
                                color: Color(0xfff38181))),
                        child: Text("FOLLOW",
                            style: TextStyle(
                                fontWeight: FontWeight.normal,
                                fontSize: 12,
                                color: isSelected ? Color(0xffffffff) : Color(0xfff38181))),
                      ),
                    ),
                  )
                ],
              ),
            ),
            Container(
              padding: EdgeInsets.only(top: 5, bottom: 5),
              child: Text(widget.text,
                style: TextStyle(
                  color: Color(0xff000000),
                  fontSize: 15,
                ),
              ),
            ),
            widget.img.length > 0
                ? Container(
              height: double.parse(widget.heightContainer),
              child:
              PosteImages(postId: widget.id, type: ''),
            )
                : Container(),
            Container(
              child: Text(widget.date,
                style: TextStyle(
                    color: Color(0xFFb4b4b4),
                    fontSize: 11),
              ),
            ),
            Divider(
              height: 1,
              color: Color(0xfff1f1f1),
            ),
            Container(
              margin: EdgeInsets.fromLTRB(0, 10, 0, 10),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: <Widget>[
                  Row(
                    children: <Widget>[
                      Icon(IconData(0xeac3, fontFamily: "LineIcons"),
                          size: 16, color: Color(0xFF646464)),
                      SizedBox(
                        width: 10.0,
                      ),
                      Text(widget.view,
                        style: TextStyle(
                            fontSize: 12,
                            color: Color(0xffa4a4a4)),
                      ),
                    ],
                  ),
                  Row(
                    children: <Widget>[
                      InkWell(
                        child: Row(
                          children: <Widget>[
                            Icon(IconData(0xeaba, fontFamily: "LineIcons"),
                                size: 18, color: Color(0xFF86c580)),
                            SizedBox(
                              width: 10.0,
                            ),
                            Text(widget.share,
                              style: TextStyle(
                                  fontSize: 12,
                                  color: Color(0xffa4a4a4)),
                            ),
                          ],
                        ),
                        onTap: () {
                          final RenderBox box = context.findRenderObject();
                          Share.share('share',
                              sharePositionOrigin:
                              box.localToGlobal(Offset.zero) &
                              box.size);
                        },
                      ),
                    ],
                  ),
                  Row(
                    children: <Widget>[
                      Icon(IconData(0xe99a, fontFamily: "LineIcons"),
                          size: 16, color: Color(0xFF646464)),
                      SizedBox(
                        width: 10.0,
                      ),
                      Text(widget.reply,
                        style: TextStyle(
                            fontSize: 12,
                            color: Color(0xffa4a4a4)),
                      ),
                    ],
                  ),
                ],
              ),
            )
          ],
        ),
      ),

    );
            }
          },
controller: _scrollController
        );
  }

**Comment by goderbauer** [comment]
@dimiril  Is all of that code really required to reproduce the issue? Can you reduce it further?

**Comment by dimiril** [comment]
How to reduce the code

**Comment by dimiril** [comment]
?

**Comment by dimiril** [comment]
up

**Comment by BondarenkoStas** [comment]
Delete everything which doesn't influence scrolling process, basically to try to find the part of code which causes the jerk scrolling or at which point it becomes so.

**Comment by VladyslavBondarenko** [comment]
@dimiril 
is it still an issue?
if yes, provide at least complete reproducible code sample

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by rakeshbishnoi457** [comment]
I'm using listview.builder for showing images from the list, every other thing are working fine but when banner ads with 5 item gap load filter inside that listview a half sec lag comes, does anyone know that how to fix, please if anyone knows
