### ISSUE TITLE
[postmortem][devicelab] Add redundancy for every test bed config

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#43818]
There are a few devicelab test bed configs that have a single test bed. We need add redundancy at least two test beds per config.

This is to avoid situations when a single failing test bed prevents the validation of PRs per days.

**Comment by digiter** [comment]
Currently we have 4 configs that needs redundancy, do we want to cover all of them?

**Comment by godofredoc** [comment]
Yes, ideally we should have at least two of each combination.

**Comment by digiter** [comment]
This is blocked by not having enough physical space.

**Comment by godofredoc** [comment]
Closing as obsolete.
