### ISSUE TITLE
[postmortem][devicelab] Alert when more than 20% of capacity per config is red

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#43821]
Alert when a given test bed combination has more than 20% of the capacity red. This is to prevent blocking PRs validation because there are no test beds to run a given test.

**Comment by godofredoc** [comment]
Expanding monarch alerts to cover this use case

**Comment by godofredoc** [comment]
@keyonghan to work on this next week.

**Comment by keyonghan** [comment]
This has been implemented and validated. Closing.
