### ISSUE TITLE
[postmortem] Create dev environment

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#43822]
Create a devicelab dev environment with one test bed per configuration. This is because we use the production test beds to experiment and we don't clean up properly.

This will also help to develop and test changes without affecting the devicelab production environment. Furthermore this will enable us to have releases of the infrastructure.

**Comment by digiter** [comment]
We need more physical lab space and network space. Also different configurations of each host/device.

**Comment by godofredoc** [comment]
We still need a windows test bed and an ios32 test bed we can close this bug after.

**Comment by godofredoc** [comment]
@godofredoc to move some linux, mac and windows to the staging pool.

**Comment by CaseyHillers** [comment]
\cc @whesse

Any update on this? The Dart EngProd team would like to experiment with HHH builds before scheduling on prod.

**Comment by godofredoc** [comment]
No updates yet, although there are several requests for setting this up. I'll be moving the bots with an ETA 06/18

**Comment by godofredoc** [comment]
2 mac, 2 win and 2 linux bots have been added to staging: https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=pool%3Aluci.flutter.staging&k=pool&s=id

**Comment by godofredoc** [comment]
We will find out what is missing as the dart team starts using the staging environment.

**Comment by keyonghan** [comment]
Next step: add a couple of builders to run.
