### ISSUE TITLE
Limit dartanalyzer warnings during new checks.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43835]
Action item from postmortem123362 (Flutter-Fuchsia rolls failed for 20 days). 

Provide limits to the new warnings dartanalyzer may provide during integration of new checks  --- we need a way to block analyzer warnings in google3; Fuchsia needs a dartanalyzer-silencing mechanism for new warnings. This also requires support from the Fuchsia team.

/cc @cbracken (who owns the issue in the postmortem) and @iskakaushik.

**Comment by pedromassangocode** [comment]
Does this still a valid issue?

**Comment by cbracken** [comment]
I think we can close this.
