### ISSUE TITLE
Make flutter tool work with Fuchsia for new projects

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43836]
Action item from postmortem123362 (Flutter-Fuchsia rolls failed for 20 days).

Originally assigned to @Hixie; I suspect this is better in @zanderso's court to delegate, and likely of interest to @jonahwilliams as well. 

We want to eliminate other means by which Fuchsia can create and build applications. Likely part of the solution to https://github.com/flutter/flutter/issues/43834.

**Comment by zanderso** [comment]
@kf6gpe It would be good to get some more details about what the requirements are here and/or what the desired workflow is. Could you also share the postmortem with me. Thank!

**Comment by kf6gpe** [comment]
I'll add you to the (presently inside Google) doc for the postmortem.

My understanding is that there's cases where the Fuchsia team is creating
Flutter apps, and relying on our internal build rules to build them --- it
would be better to enable `flutter` tool use for them for these cases.

cc @iskakaushik, who may have more details.
Ray Rischpater, KF6GPE | kf6gpe.org | @kf6gpe
<http://www.twitter.com/kf6gpe>

**Comment by iskakaushik** [comment]
The idea here is to support the following workflows on Fuchsia.

## Create a Flutter Application

`flutter create --fuchsia` would create a simple demo application that the users can use as a starting point to create Flutter applications on Fuchsia. This should initialize it with a template content manifest, that indicates the application uri. The users should be able to specify the kind of flutter runner they wish to use as well. (JIT/AOT + DEBUG/PROFILE/RELEASE)

## Running an Application

`flutter run -d fuchsia` or some equivalent should be able to detect a connected Fuchsia device, package the application and run it using the runners provided by the engine.

## Building an Application

`flutter build` should build the application far file. This might have to bundle the AOT runner as well.

I'm happy to go into further detail on any of these or file individual bugs for them if you prefer.

Similar issue: https://github.com/flutter/flutter/issues/43834

**Comment by zanderso** [comment]
The tool should support creating e.g. a .cmx file in `flutter create` for a Fuchsia app that will allow `flutter build fuchsia` to work, but I think the tool is probably not the right choice to create a new in-tree app. I'm going to reduce this to `severe: new feature` since I don't think anything is going to be blocked on this as stated.

**Comment by zanderso** [comment]
See also https://github.com/flutter/flutter/issues/31142

**Comment by chaselatta** [comment]
Tracking via fxbug.dev/61331
