### ISSUE TITLE
Remove GN build rule dependencies in Fuchsia

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43834]
Action item from postmortem123362 (Flutter-Fuchsia rolls failed for 20 days). 

cc @iskakaushik, who owns the item on the postmortem.

**Comment by iskakaushik** [comment]
`flutter_app.gni` ([source](https://fuchsia.googlesource.com/topaz/+/master/runtime/flutter_runner/flutter_app.gni)) is the current way to build flutter apps on Fuchsia. Ideally we would use Flutter tool to build apps in the Fuchsia tree. This lets us remove both `flutter_app` and `dart_app` gni rules from the Fuchsia tree.

**Comment by iskakaushik** [comment]
x-ref: https://github.com/flutter/flutter/issues/43836

**Comment by zanderso** [comment]
`flutter_app.gni` and `dart_app.gni` have features that would be difficult to replicate in the flutter tool, and which are probably out of scope for the flutter tool.

Additionally, this would require the Fuchsia build to inject different implementations of a few components into the flutter tool as is done for internal builds. I would very much prefer to avoid propagating that model.

I think we should try to zero in a bit more on what the problem we're solving here is, and avoid jumping to a solution.

**Comment by Hixie** [comment]
I was looking at this recently and I really don't understand why Fuchsia needs any build rules at all for Flutter. It seems like components should specify their need for Fuchsia in their CMX manifest. Or are the build rules just for driving the `flutter build` tool to compile the code? In which case it seems like that shouldn't be something Flutter needs to deal with at all, it's just a Fuchsia tree implementation detail?

**Comment by zanderso** [comment]
> Or are the build rules just for driving the flutter build tool to compile the code? In which case it seems like that shouldn't be something Flutter needs to deal with at all, it's just a Fuchsia tree implementation detail?

The Fuchsia build of Flutter apps is driven by the GN rules in `flutter_app.gni`, and doesn't go through the `flutter` tool with one exception. It uses an entry point in the Flutter tool for bundling assets: [bin/fuchsia_asset_builder.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/bin/fuchsia_asset_builder.dart)

This issue could be about one of two things:
1. Re-write `flutter_app.gni` to delegate to the `flutter` tool for everything, not just asset bundling.
2. Shift `flutter_app.gni` to be more self-contained, and move it back to the Fuchsia tree. That is, eliminate the dependency on `fuchsia_asset_builder.dart`.

I think (1) is not the right approach for reasons stated above. (2) seems more tractable since `fuchsia_asset_builder.dart` is not a big script.

**Comment by Hixie** [comment]
Can you elaborate on why the `flutter` tool isn't the right way to build for Fuchsia? Do you just mean for in-tree apps? I'm not sure I follow.

**Comment by zanderso** [comment]
Yeah, I mean just for in-tree apps. The in-tree build rules can do some fancy things that we may or may not want the `flutter` tool to do, for example packaging multiple flutter and dart "components" into the same Fuchsia package.

**Comment by Hixie** [comment]
IMHO we should consider each of those things and decide whether they're really valuable or not; for those that aren't we should just stop doing them in the fuchsia tree and for those that are we should support them in the tool (and likely on all platforms).

**Comment by iskakaushik** [comment]
Current behavior is that the Fuchsia tree no longer depends on the engine sources, so we should delete the unused rules from the engine sources. The rules still exist in the topaz tree and deviate slightly from what we get if we use `flutter build` for a Fuchsia app. I will document these ways so we can make a decision to either move them to the tool or if we should deprecate/delete them from the Fuchsia tree. I will report back with my findings here.

Given that there is no longer a source dependency on the flutter/engine repo in the Fuchsia tree, I will remove the "customer critical" label from the issue. If you disagree, please add it back.

**Comment by iskakaushik** [comment]
There is an internal proposal about structuring the dependencies between flutter/dart/fuchsia. The agreement reached there will have impact on this project: go/flutter-on-fuchsia-stable-rolls. I will be pushing the milestone of this and un-assigning myself as its unclear if I will be the one working on this.

**Comment by zanderso** [comment]
Closing as obsolete.
