### ISSUE TITLE
Define scalation/communication path for broken rolls

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43839]
Action item from postmortem123362 (Flutter-Fuchsia rolls failed for 20 days).

Update TPM handbook and define escalation path for broken rolls, including when and how to escalate to leads and how to communicate roll breakages to Google customers.

**Comment by dnfield** [comment]
Flutter/Fuchsia rolls don't work the way they did when this bug was opened. Closing as obsolete.
