### ISSUE TITLE
Establish earlier testing in Flutter, Fuchsia trees to catch breaking changes

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43831]
Action item from postmortem123362 (Flutter-Fuchsia rolls failed for 20 days); identify avenues for presubmit tests across Flutter and Fuchsia to detect breaking changes before they occur. Needs work on both the Fuchsia and Flutter teams.

cc @Hixie, to whom the item is assigned to delegate, and @iskakaushik for the Fuchsia components specifically.

**Comment by iskakaushik** [comment]
duplicate of https://github.com/flutter/flutter/issues/44826
