### ISSUE TITLE
GestureDetector: ScaleUpdateDetails should also contain a delta since scale is a superset of pan.

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#43833]
If you define both `onPanUpdate` and `onScaleUpdate` you get this error:

    Incorrect GestureDetector arguments.
    I/flutter ( 3574): Having both a pan gesture recognizer and a scale gesture recognizer is redundant; scale is a superset of pan. Just use the scale gesture recognizer.

But how? `onPanUpdate` tells you `dx` and `dy` from the last position. While `onScaleUpdate` tells you `focalPoint` and `localFocalPoint` with no initial position. There's no easy way to convert between them.

Or am I missing something?

Frankly, if `onScaleUpdate` is a superset of `onPanUpdate` it should contain at least the exact same fields as `onPanUpdate`.

**Comment by goderbauer** [comment]
I believe the assert is not super-honest. There are some things that onPanUpdate provides that's not available from the onScaleUpdate. We should fix that.

/cc @justinmc FYI since you were working on a pan demo.

**Comment by justinmc** [comment]
Yeah I ran into this as well!  What I did was to save `details.focalPoint` in onScaleStart, and then in onScaleUpdate I compare my saved value with the new `details.focalPoint` and then update the saved value.

That error message above made me think that there was a good reason for excluding dx/dy and my workaround is what we're intended to do. Now that I think about though, I don't know why we don't just include dx/dy as well.  I'm on board with that if no one knows of a good reason not to.

**Comment by neckaros** [comment]
That would be super useful to move things inside a custompaint!

**Comment by markusaksli-nc** [comment]
Labeling this as a proposal to add dx/dy to onScaleUpdate rather than adding a workaround example to the docs https://github.com/flutter/flutter/issues/43833#issuecomment-548505252

**Comment by esDotDev** [comment]
This is even more odd as Scale seems to swallow MouseWheel events now, which really have no relation to panning;

**Comment by sanjade** [comment]
Any update regarding this?

**Comment by FalconBFR** [comment]
Any update or workarounds? Thanks!

**Comment by kartik1225** [comment]
Any update?
