### ISSUE TITLE
Clean up ownership model of IOSGLContext/PlatformViewIOS

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#43849]
Right now the ownership graph between IOSGLContext, PlatformViewIOS and FlutterView doesn't make a huge amount of sense. IOSGLContext currently manages two platform GL contexts (EAGLContext), one for resources and one for onscreen. Because the resource context is long-lived, tying the onscreen context to the lifetime of the resource context doesn't make a huge amount of sense.

The proposal here is to restructure it so that IOSGLContext maps to a single EAGLContext object, and we hold multiple IOSGLContexts for different requirements. The "resource" IOSGLContext would be owned by the PlatformViewIOS, and the "onscreen" IOSGLContext by the FlutterView. Tying the lifetime of the onscreen context to the FlutterView would make more sense from a lifetime perspective.

**Comment by zw1924** [comment]
There are now situations that can cause crashes between page jumps, depending on the context of the GL. I look forward to such a plan

**Comment by jmagman** [comment]
@dnfield Looks like this should be closed post-impeller.
