### ISSUE TITLE
Run the Scenario App on physical iOS devices in CI 

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#43852]
Currently the [Scenario App](https://github.com/flutter/engine/tree/master/testing/scenario_app) only runs on iOS simulators in CI.

We should run it on physical devices as well.

cc @dnfield @cyanglaz

**Comment by dnfield** [comment]
I had started working on this at one point The main challenge is code signing in LUCI. We can't have a "logged in Xcode", so we'll have to set up some good way to manually do it.

**Comment by godofredoc** [comment]
Obsolete. Please reopen if has not been addressed or still needed.
