### ISSUE TITLE
TextField  obscureText:true  Nine key input method

### ISSUE THREAD

**Issue by guangyingmodao** [flutter/flutter#43874]
When I use the nine key input method, I input a letter, press again when it becomes a spot, the spot may change back to a letter, sometimes it will not become a letter, but the input method is still at this spot, so the letter is actually changing, but it is displayed as a spot, there is no change.

**Comment by guangyingmodao** [comment]
#43889

**Comment by BondarenkoStas** [comment]
@guangyingmodao Can you clarify once again about the issue, do you mean that while quick typing letters are changing, but cursor doesn't move afterwards?
In which way obscureText:true is related? Maybe you can provide a code example and it will be easier to understand if you have screen recording?

**Comment by guangyingmodao** [comment]
Please refer to&nbsp;#43889&nbsp;for screen recording.
Because I set obscurtext to true,the letters became the spots so that I couldn't see the change of the last spot.
when we click the letters quickly by using the nine key&nbsp;keyboard and the letter has become the spot, sometimes clicking button still change the letter of the last spot ,even the spot change back to the letter.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Stanislav Bondarenko"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月31日(星期四) 晚上10:49
收件人:&nbsp;"flutter/flutter"<flutter@noreply.github.com&gt;;
抄送:&nbsp;"fallen leaves"<1481250633@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [flutter/flutter] TextField  obscureText:true  Nine key input method (#43874)




@guangyingmodao Can you clarify once again about the issue, do you mean that while quick typing letters are changing, but cursor doesn't move afterwards?
 In which way obscureText:true is related? Maybe you can provide a code example and it will be easier to understand if you have screen recording?

**Comment by TahaTesser** [comment]
Hi @guangyingmodao 
Are you still experiencing the issue with latest stable?
if yes,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
