### ISSUE TITLE
Blank white screen on launching my flutter app on iOS (After Archive)

### ISSUE THREAD

**Issue by mdzafar3194** [flutter/flutter#43875]
@zoechi, 
Hi i am newbie, into flutter, trying to generate an ipa file to share for testing. i am able to generate ipa file but, after installing, It shows Blank white screen 
Any help would be appreciated,
Thanks..

**Comment by YWD** [comment]
Have you run 'flutter build ios' command in terminal?

**Comment by mdzafar3194** [comment]
> Have you run 'flutter build ios' command in terminal?

When i try to run this command it gives me error like "flutter command not found"

**Comment by YWD** [comment]
https://stackoverflow.com/questions/50652071/flutter-command-not-found, maybe this will help you.

**Comment by mdzafar3194** [comment]
> Have you run 'flutter build ios' command in termina

**Comment by mdzafar3194** [comment]
> Have you run 'flutter build ios' command in terminal?

After running this command it is generating `Runner.app` file 
But, how can i get .ipa file

**Comment by mdzafar3194** [comment]
> https://stackoverflow.com/questions/50652071/flutter-command-not-found, maybe this will help you.

Have you run 'flutter build ios' command in terminal?

After running this command it is generating Runner.app file
But, how can i get .ipa file

Please help me out

**Comment by YWD** [comment]
you still need use xCode to generate a .ipa file.

**Comment by mdzafar3194** [comment]
> you still need use xCode to generate a .ipa file.

Okay, let me check and update you if i face the same issue

**Comment by mdzafar3194** [comment]
@YWD 
Thanks a lott.. you saved my life
