### ISSUE TITLE
Cleanup `flutter analyze` command defaults.

### ISSUE THREAD

**Issue by pq** [flutter/flutter#4387]
As discussed in https://github.com/flutter/flutter/pull/4348, the defaults for `flutter analyze` would benefit from some (re)consideration.

@Hixie proposes:

> Maybe the right behavior is to have everything default off, and if you specify none, we use --current-package?

On the surface this sounds right to me.

@devoncarew ?

**Comment by devoncarew** [comment]
```
Usage: flutter analyze [arguments]
-h, --help                      Print this usage information.
    --[no-]flutter-repo         Include all the examples and tests from the Flutter repository.
    --[no-]current-directory    Include all the Dart files in the current directory, if any.
                                (defaults to on)

    --[no-]current-package      Include the lib/main.dart file from the current directory, if any.
                                (defaults to on)

    --[no-]dartdocs             List every public member that is lacking documentation (only examines files in the Flutter repository).
    --[no-]preamble             Display the number of files that will be analyzed.
                                (defaults to on)

    --[no-]congratulate         Show output even when there are no errors, warnings, hints, or lints.
                                (defaults to on)

    --watch                     Run analysis continuously, watching the filesystem for changes.
    --[no-]pub                  Whether to run "pub get" before executing this command.
                                (defaults to on)
```

I wonder if we could eliminate some of these options entirely, and simplify the matrix of possibilities a bit?

**Comment by pq** [comment]
>     --[no-]current-directory    Include all the Dart files in the current directory, if any.
                                (defaults to on)

Maybe this can be removed given that we should get the equivalent like so:

`flutter analyze .`

(Bonus points for being shorter than `flutter analyze --current-directory` :smile: )

**Comment by Hixie** [comment]
Closing in favour of https://github.com/flutter/flutter/issues/7274
