### ISSUE TITLE
'textSelectionHandleColor' doesn't work for iOS whereas 'textSelectionColor' works for both platforms

### ISSUE THREAD

**Issue by Pavel-Sulimau** [flutter/flutter#43887]
## Steps to Reproduce

1. Create an app with this code:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        textSelectionColor: Colors.green,
        textSelectionHandleColor: Colors.greenAccent,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('textSelectionHandleColor'),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Center(
            child: TextField(),
          ),
        ),
      ),
    );
  }
}
```
2. Run it iOS and Android platforms, type some text and make the text selected.
3. Take a look at the color of the text selection handles.
4. Android uses both 'textSelectionColor' and 'textSelectionHandleColor' theme's values, whereas iOS ignores the latter. 

<img width="241" alt="Screen Shot 2019-10-31 at 09 26 03" src="https://user-images.githubusercontent.com/8143332/67925083-5b45b400-fbc3-11e9-8f82-3cf59cdf6b28.png">
<img width="224" alt="Screen Shot 2019-10-31 at 09 22 50" src="https://user-images.githubusercontent.com/8143332/67925084-5d0f7780-fbc3-11e9-9483-846e5d5060cf.png">

**Target Platform:** iOS
**Devices:** Simulator (iPhone 11 - 13.1), iPhone 8 - 13.1.3

## Logs

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A602, locale en-BY)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (2 available)

• No issues found!
```

## I dug into the sources of flutter a bit and saw the following:

material 'text_selection.dart' uses the theme's value
```
painter: _TextSelectionHandlePainter(
      color: Theme.of(context).textSelectionHandleColor
),
```
whereas cupertino 'text_selection.dart' has the hardcoded color value
```
final Paint paint = Paint()
    ..color = _kHandlesColor
    ..strokeWidth = 2.0;
```

**Shouldn't the text selection handles on iOS be affected by 'textSelectionHandleColor' value?**

**Comment by HansMuller** [comment]
In this case the TextField's adaptation for iOS is intended to be faithful to the native look and feel for the text selection, rather than to the Material theme. Maybe we need a way to override that.

CC @LongCatIsLooong

**Comment by Pavel-Sulimau** [comment]
If it's intended to be faithful to iOS, I would expect that either both of the mentioned properties work or both don't. I would also suggest making this behavior more explicit by putting a corresponding comment on the color/colors.

**Comment by TahaTesser** [comment]
<details> 
<summary>Code Sample</summary> 

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData(
          cursorColor: Colors.red,
          textSelectionHandleColor: Colors.red,
          textSelectionColor: Colors.red.withOpacity(0.4)),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(),
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.17.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • Taha’s iPhone • 00008020-001059882212002E            • ios • iOS 13.6
    • iPhone 11     • 7863E29F-EEE8-499E-BB28-6B111B76E3EE • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale
    en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision f25bd9c55c (2 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 13.6
    • iPhone 11 (mobile)     • 7863E29F-EEE8-499E-BB28-6B111B76E3EE • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

**Comment by vanlooverenkoen** [comment]
I can see that @LongCatIsLooong has added the follow line on 8/10/2020
```
painter: _TextSelectionHandlePainter(CupertinoTheme.of(context).primaryColor),
```
I tried to over write it like this. but it didn't work
```
CupertinoTheme(
        data: CupertinoThemeData(
          primaryColor: Colors.green,
        ),
        child: TextField()
)
```

**Comment by adeolaex** [comment]
@vanlooverenkoen Try setting the `cupertinoOverrideTheme` over at the `ThemeData` in the MaterialApp widget.

For example

````
// Root class called by the runApp() method.

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        textSelectionColor: Colors.green,
        brightness: Brightness.light,
        cupertinoOverrideTheme: CupertinoThemeData(
          primaryColor: Colors.green,
        ),
      ),
      home: App(),
    );
  }
}

````

For some reason, IOS ignores the Material defined values.

**Comment by GaryQian** [comment]
cc @justinmc Did you want to take a look at this? This doesn't look like it needs much code changes, but more of a policy decision on whether to set the textSelectionHandleColor in the Cupertino theme derivation of Material theme.

**Comment by justinmc** [comment]
@darrenaustin I believe you were working on TextSelectionTheme, did you have any opinion on how iOS should use those settings?

I think I'm leaning towards iOS-style text selection using only Cupertino theme values.  That would mean updating it so that textSelectionColor has no effect on iOS.  iOS text selection is mostly defined in cupertino/text_selection.dart, which doesn't have access to the Material library's theming.  I'm not sure how we handle this kind of theming for other platforms, though.

**Comment by AyushBherwani1998** [comment]
@justinmc I think that would be a better option. Said that, the ThemeData.textSelectionColor is already deprecated and `TextSelectionThemeData.selectionColor` is not taken into consideration by iOS. Currently, it's really inconvenient because text selection color doesn't depend on the `CupertinoTheme`, and cursor color depends on `CupertinoTheme`.  I just had a hard time figure out what was going on and why `ThemeData` values were not taken into consideration.

Said that, we should file another issue for improving the docs to mention this behavior. Happy to file and raise a PR, if we are on same page.

**Comment by darrenaustin** [comment]
I don't have a strong opinion on whether we should allow the material theme settings should apply to textfields on iOS, but we should be consistent. It looks like two of the `TextSelectionThemeData` parameters (`cursorColor` and `selectionColor`) are used on Cupertino text fields, while the `selectionHandleColor` is not. I would lean toward turning them all off for Cupertino, but I seem to recall someone raised an issue a while back that they couldn't change the colors on iOS, so people may need this.

I am not that familiar with how the text selection handles are implemented for Cupertino. Would it be hard to have them use the material theme data for this to be consistent?

**Comment by justinmc** [comment]
I think it would be hard for CupertinoTextField, because CupertinoTextField can't access the Material theme.

@AyushBherwani1998 I'm on board with just updating the docs if you're still able to write a pull request.

**Comment by AyushBherwani1998** [comment]
@justinmc I'll send a PR soon to update docs.

**Comment by mkiisoft** [comment]
ant updates about this? The issue continues over iOS on version 2.2.3

**Comment by justinmc** [comment]
It looks like this should have been closed with https://github.com/flutter/flutter/pull/75967.
