### ISSUE TITLE
Failed to build flutter project: ProcessException exited abnormally

### ISSUE THREAD

**Issue by skyridertk** [flutter/flutter#43892]
I've been trying to run my flutter project but it's failing.  The command:

 

    flutter run

The output coming out after I run the command is:

    * Error running Gradle:
    ProcessException: Process "MY_DIR\android\gradlew.bat" exited abnormally:
    Starting a Gradle Daemon (subsequent builds will be faster)
    
    > Configure project :app
    WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
    It will be removed at the end of 2019.
    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
    To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to
    display more information.
    WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with
    'variantOutput.getProcessResourcesProvider()'.
    It will be removed at the end of 2019.
    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
    To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command
    line to display more information.
      Command: \MY_DIR_\android\gradlew.bat app:properties
    
    
    Please review your Gradle project setup in the android/ folder.

I did try re-downloading all packages using this

    flutter pub pub cache repair

It did redownload all the packages required by my project, but still, the issue persists.
That's android/build.gradle

    def localProperties = new Properties()
    def localPropertiesFile = rootProject.file('local.properties')
    if (localPropertiesFile.exists()) {
        localPropertiesFile.withReader('UTF-8') { reader ->
            localProperties.load(reader)
        }
    }
    
    def flutterRoot = localProperties.getProperty('flutter.sdk')
    if (flutterRoot == null) {
        throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
    }
    
    def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
    if (flutterVersionCode == null) {
        flutterVersionCode = '1'
    }
    
    def flutterVersionName = localProperties.getProperty('flutter.versionName')
    if (flutterVersionName == null) {
        flutterVersionName = '1.0'
    }
    
    apply plugin: 'com.android.application'
    apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
    
    android {
        compileSdkVersion 28
    
        lintOptions {
            disable 'InvalidPackage'
        }
    
        defaultConfig {
            // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
            applicationId "flutter.example.com.test_flutter_app"
            minSdkVersion 21
            multiDexEnabled true
            targetSdkVersion 28
            versionCode flutterVersionCode.toInteger()
            versionName flutterVersionName
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }
    
        buildTypes {
            release {
                // TODO: Add your own signing config for the release build.
                // Signing with the debug keys for now, so `flutter run --release` works.
                signingConfig signingConfigs.debug
            }
        }
    }
    
    flutter {
        source '../..'
    }
    
    dependencies {
        testImplementation 'junit:junit:4.12'
        androidTestImplementation 'com.android.support.test:runner:1.0.2'
        androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    }

That's project/build.gradle

    buildscript {
        repositories {
            google()
            jcenter()
        }
    
        dependencies {
            classpath 'com.android.tools.build:gradle:3.5.0'
        }
    }
    
    allprojects {
        repositories {
            google()
            jcenter()
        }
    }
    
    rootProject.buildDir = '../build'
    subprojects {
        project.buildDir = "${rootProject.buildDir}/${project.name}"
    }
    subprojects {
        project.evaluationDependsOn(':app')
    }
    
    task clean(type: Delete) {
        delete rootProject.buildDir
    }
    

My specs

    {Windows 10 1809 64bit, vscode, gradle 5.4.1, Flutter version 1.9.1+hotfix.4 }

**Comment by BondarenkoStas** [comment]
@skyridertk did issues should be already fixed, https://github.com/flutter/flutter/issues/26544#issuecomment-539827470.
As workaround to don't use master channel can you please try to lower your dependencies as in https://github.com/flutter/flutter/issues/28713#issuecomment-546662092?

**Comment by skyridertk** [comment]
I degraded to gradle version 4.10.1 and gradle plugin 3.2,1. The issue got resolved
