### ISSUE TITLE
[web]: can't import 'dart:ffi'

### ISSUE THREAD

**Issue by jmarkel44** [flutter/flutter#43898]
Describe your issue and include the command you're running, flutter_web version, browser version

**Comment by jmarkel44** [comment]
```
C:\Users\jmarkel\AndroidStudioProjects\audacy_on_tap>flutter build web
Compiling lib\main.dart for the Web...                                 |
...Exception: lib/choose_lights.dart:10:8:
Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
Error: Compilation failed.


Failed to compile application for the Web.
```                    

Though the import works fine when just using dart:

```
C:\Users\jmarkel\AndroidStudioProjects\audacy_on_tap>dart hello.dart
Hello, World!

C:\Users\jmarkel\AndroidStudioProjects\audacy_on_tap>cat hello.dart
import 'dart:ffi';

void main() {
    print("Hello, World!");
    return;
}
```
```
C:\flutter\flutter>flutter --version
Flutter 1.10.14 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 1946fc4da0 (3 weeks ago) • 2019-10-07 15:23:31 -0700
Engine • revision 1d62160fdb
Tools • Dart 2.6.0 (build 2.6.0-dev.5.0 d6c6d12ebf)
```

**Comment by jonahwilliams** [comment]
You can't use FFI on the web, if that is what you are trying to do?

**Comment by jmarkel44** [comment]
Yes, that was the goal.

We are attempting to create a web application on an embedded device.
Certain actions from the ui must trigger actions to other processes running
on the target. What are some options to achieve this?

Thanks

**Comment by yjbanov** [comment]
Currently on the web the recommended way to interop with the browser is to create a plugin and use `package:js` to access JavaScript. It is unclear what `dart:ffi` would do on the Web.

**Comment by akashkarli** [comment]
Running on web logs
 
Launching lib\main.dart on Web Server in debug mode...
Syncing files to device Web Server...
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/majascan-0.3.7/lib/majascan.dart:2:8:
Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
Failed to compile application.

what should i do ?

**Comment by lukepighetti** [comment]
So I have no idea if this is possible or not. Is it possible for dart:ffi to target to wasm?

**Comment by cedvdb** [comment]
> Is it possible for dart:ffi to target to wasm?

I would like to know too. This would make cpp libraries usable on all platforms wouldn't it ?
