### ISSUE TITLE
Google Map - Custom view as a marker

### ISSUE THREAD

**Issue by sathish76** [flutter/flutter#43900]
## Custom view as a marker.

> **Plugin: google_maps_flutter 0.5.21+8**

In native Android, iOS and react-native. we can have custom view as markers in google map.
I hope this feature is not available currently so, requesting this feature in flutter!

## References.
[https://github.com/react-native-community/react-native-maps#rendering-a-marker-with-a-custom-view](url)
[https://waleedsarwar.com/posts/2016-03-03-custom-markers-google-maps/](url)

**Comment by esDotDev** [comment]
This is vital for any app doing deep maps integration. Being able to compose custom popups on marker tap is a core feature.

**Comment by TahaTesser** [comment]
Duplicate of [#24213](https://github.com/flutter/flutter/issues/24213)
