### ISSUE TITLE
Flutter Gallery transitions perf test is broken

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#4390]
## Steps to Reproduce

```
flutter drive --debug --trace-startup -t test_driver/transitions_perf.dart
```

## Flutter Doctor

â€¢â€¢â€¢ flutter doctor â€¢â€¢â€¢
Executing: /Users/demouser/flutter_dashboard/flutter/bin/flutter doctor
[âœ“] Flutter (on Mac OS, channel unknown)
    â€¢ Flutter at /Users/demouser/flutter_dashboard/flutter
    â€¢ Framework revision 6c96e1a320 (19 minutes ago), engine revision a943c732d5

[âœ“] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    â€¢ Android SDK at /Users/demouser/Library/Android/sdk
    â€¢ Platform android-23, build-tools 23.0.2
    â€¢ Java(TM) SE Runtime Environment (build 1.8.0_74-b02)

[-] iOS toolchain - develop for iOS devices (Xcode 7.2.1)
    â€¢ XCode at /Applications/Xcode.app/Contents/Developer
    â€¢ Xcode 7.2.1, Build version 7C1002
    x Brew not installed; use this to install tools for iOS device development.
      Download brew at http://brew.sh/.

[x] Atom - a lightweight development environment for Flutter
    x Atom not installed; download at https://atom.io.

## Logs and Crash Reports

https://pantheon.corp.google.com/m/cloudstorage/b/flutter-dashboard/o/6c96e1a320726d51297d204d9be5ffa2407a5700/output.txt

/cc @HansMuller

**Comment by sethladd** [comment]
Our dashboard bot is broken. @mpcomplete is this something you can help take a look at? Thanks!

**Comment by yjbanov** [comment]
I'm suspecting the [list of demos](https://github.com/flutter/flutter/blob/1d516f0e94c4a65280ae35f3a8fc37931021ca18/examples/flutter_gallery/test_driver/transitions_perf_test.dart#L17) in the test went out-of-sync after the pesto demo was added.

**Comment by mpcomplete** [comment]
Should be fixed. Reopen if this fails again.

**Comment by sethladd** [comment]
Thanks Matt!
