### ISSUE TITLE
 Incorrect Flutter window size on some hardware

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43906]
Mirror issue for https://b.corp.google.com/issues/143529469.

/cc @chinmaygarde, who was working on this at one point, and can likely resume when he returns.

**Comment by chinmaygarde** [comment]
This has been patched in https://github.com/flutter/engine/pull/13708

**Comment by chinmaygarde** [comment]
This issue has been re-opened internally and is my current focus. Detailed investigation of this is described in go/flutter-newman-cast-dpr.

**Comment by chinmaygarde** [comment]
cc @kf6gpe for bugjuggling.

**Comment by chinmaygarde** [comment]
Not sure why a commit in @iskakaushik s tree made GitHub automatically close this issue.

**Comment by chinmaygarde** [comment]
Patched in https://github.com/flutter/engine/pull/13850.

**Comment by chinmaygarde** [comment]
This has been verified on the internal target.
