### ISSUE TITLE
Capture analytics event from failure to initialize incremental compiler in build runner

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#43914]
This would also need to track the StackTrace (top 20 frames or so) and operating system. The message would be sent as an info.log with the format in https://dart-review.googlesource.com/c/sdk/+/123001/7/pkg/front_end/lib/src/api_unstable/modular_incremental_compilation.dart#252

FYI @jakemac53

**Comment by jakemac53** [comment]
Thanks! Regarding `info.log` is that a flutter tool log level and not a build_runner one? We might upgrade these to warnings if they aren't already but it likely wouldn't matter if warnings/infos from build_runner are treated the same. 

Also note that these logs will be preceded by the standard build_runner log message boilerplate so something like `[INFO] build_web_compilers:ddc on package:foo/main.module:`

**Comment by jonahwilliams** [comment]
I think I mixed up my logging APIs, we might not show these logs by default from build_runner, but we're definitely capturing them

**Comment by jakemac53** [comment]
cc @jensjoha @johnniwinther @vsmenon for fyi as well

**Comment by zanderso** [comment]
@jonahwilliams what is the status of this issue?

**Comment by jonahwilliams** [comment]
I didn't end up getting to this last quarter - it will be made obsolete (from Flutter's perspective) with https://github.com/flutter/flutter/pull/50365

**Comment by zanderso** [comment]
Should we close this?

**Comment by jakemac53** [comment]
If it isn't planned then yes we should close it :)
