### ISSUE TITLE
[web]: Flutter Unsupported in Flutter_Web Tech Preview

### ISSUE THREAD

**Issue by ThomasValois** [flutter/flutter#43917]
### Issue

I've recently tried building a flutter web project. I tried running the `flutter packages pub global run webdev build` command but get the below error message. The end goal is to get it deployed to Firestore Hosting and was told I had to build it using that command before I can do so. 

If you need me to send anything else just let me know.

### Error

- `You have a dependency on flutter which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details`
- `pub finished with exit code 78`

### Tried

- `Flutter channel master`
-` Flutter upgrade`
- `Flutter doctor `

### pubspec.yaml

```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: 1.7.2
  build_web_compilers: 2.7.1

flutter:
  uses-material-design: true

```

### Flutter Doctor
```

[√] Flutter (Channel master, v1.10.15-pre.354, on Microsoft Windows [Version 10.0.19002.1002], locale en-GB)
    • Flutter version 1.10.15-pre.354 at C:\Android\flutter
    • Framework revision f798cb6d29 (20 minutes ago), 2019-10-31 11:59:45 -0700
    • Engine revision b16eab6aff
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 d50c158d42)

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Android\
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Android
    • ANDROID_SDK_ROOT = C:\Android\sdk
    • Java binary at: C:\Android\openjdk\bin\java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\THOMAS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.
```0.3904.70
    • Web Server • web-server • web-javascript • Flutter Tools

**Comment by jonahwilliams** [comment]
You'll need to follow the official instructions at https://flutter.dev/web.

The webdev tool isn't used now the flutter web is merged back into flutter.

**Comment by ThomasValois** [comment]
Hi Jonah, the flutter.dev website doesn't provide much explanation on how to use flutter web. I now understand that it has merged with Flutter but how do I compile this into an HTML format so that I can upload it to Firestore Hosting? Thanks.

**Comment by jonahwilliams** [comment]
Did you read https://flutter.dev/docs/get-started/web?

**Comment by ThomasValois** [comment]
I did, do you know where the output HTML file is stored? I went to **Build/web/index.html** but then get presented with this 
![image](https://user-images.githubusercontent.com/47246858/67989450-c8d8fb00-fc2a-11e9-8a1f-f42e2b7a132b.png)
