### ISSUE TITLE
BottomNavigationBar should respect applyElevationOverlayColor

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#43912]
I would like to replicate https://github.com/flutter/flutter/issues/40122 and https://github.com/flutter/flutter/pull/41864,but for BottomNavigationBar.

It is currently a pain to set-up a BottomNavigationBar correctly because it doesn't respect the `ColorScheme` colors or the overlay changes from elevation. It would be good if `colorScheme.surface` directly affected it, like it happens in native Android.

**Comment by iapicca** [comment]
Hi @bernaferrari 
Please allow me to understand your issue,
did the merged pull request you linked didn't solve the problem?
Or are you proposing something else?
Thank you

**Comment by bernaferrari** [comment]
You merged a PR for the BottomAppBar, not the BottomNavigationBar. Therefore, the BottomNavigationBar still needs to be updated.
