### ISSUE TITLE
Failed to build iOS app in Android Studio only

### ISSUE THREAD

**Issue by diphuda** [flutter/flutter#43911]
It builds successfully when I use VSCode. But it fails to build if I use Android Studio. Using OSX Catalina, Xcode version 11. I am a beginner. Didn't find this specific solution anywhere. `flutter doctor` shows no issue. Please check the attached screenshot.

<img width="750" alt="Screen Shot 2019-10-31 at 3 04 04 AM" src="https://user-images.githubusercontent.com/46551841/67971312-c67c9e00-fc36-11e9-9b1c-bb9ef2a5fb0e.png">

**Comment by iapicca** [comment]
Hi @diphuda 
can you please provide  your `flutter doctor -v` and
 your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Please refrain 
from posting pictures if not necessary.
Thank you

**Comment by jmagman** [comment]
Have you tried `flutter run --verbose` from the command line?  Or is the failure only in Android Studio?

> Using OSX Catalina, Xcode version 11

Does it build from Xcode?
```
open ios/Runner.xcworkspace
```
In Xcode
Product > Build

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
