### ISSUE TITLE
[fuchsia] We are packaging so files including debug symbols in the flutter runner far files

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#43926]
we want /dist/

```
./arch/arm64/lib/libfdio.so
./arch/arm64/dist/libfdio.so
```

The `lib/` one includes debug symbols, you can link against either. But the `dist/` version is intended for packaging

**Comment by jamesr** [comment]
@iskakaushik it looks like libc.so is still there. you only need ld.so.1 from sysroot_dist_lib

**Comment by jamesr** [comment]
Also libzircon.so, you don't need to package that.  The version in sysroot_lib is just debug symbols

**Comment by iskakaushik** [comment]
I will leave this issue open and fix this after I get the Flutter -> Fuchsia roll going again.

**Comment by jamesr** [comment]
@iskakaushik https://github.com/flutter/engine/blob/master/tools/fuchsia/common_libs.gni still lists the debug symbols for libc:

https://github.com/flutter/engine/blob/master/tools/fuchsia/common_libs.gni#L46

and the vDSO (aka libzircon):

https://github.com/flutter/engine/blob/master/tools/fuchsia/common_libs.gni#L41

libc functionality is provided as part of ld.so.1, which is in the dist/ folder and already packaged.

the vDSO is provided at runtime by the system and doesn't need to be packaged.  Do you want to fix those as well as part of this issue, or file a new one?

**Comment by iskakaushik** [comment]
Hi @jamesr , I left this open to fix this.

**Comment by jamesr** [comment]
Ah ok great - just wanted to confirm that those weren't forgotten.

**Comment by jamesr** [comment]
@iskakaushik we're still seeing debug symbols for libc.so and libzircon.so in the Flutter production package, which is causing us pressing space issues.  I can provide more context offline.  Can we get those removed?
