### ISSUE TITLE
flutter daemon tested against devices

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#4392]
We need to test the `flutter daemon` commands against devices (real devices or emulators). It uses some different code paths from the cli for starting and restarting apps. We should test app.start, app.restart, and app.stop.

**Comment by Hixie** [comment]
@devoncarew Do we have any devicelab tests that do this yet?

**Comment by devoncarew** [comment]
No, not that I'm aware of.

**Comment by godofredoc** [comment]
@devoncarew can you please add more context? not sure what you are referring to as flutter deamon.

**Comment by godofredoc** [comment]
Closing as obsolete. Please reopen if this is still necessary.
