### ISSUE TITLE
Camera Flash On and Off

### ISSUE THREAD

**Issue by awhitford** [flutter/flutter#43924]
I'm interested in using the Camera flash as a silent alert.  I need a method to turn the flash on and off.  Can that please be added to the Camera plugin?

**Comment by iapicca** [comment]
"Hi …...
I see there's an open [issue ](https://github.com/flutter/flutter/issues/31225)addressing the case you described.
There's even an open [pull request](https://github.com/flutter/plugins/pull/1969)
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
