### ISSUE TITLE
Request to document how Flutter performs layouts

### ISSUE THREAD

**Issue by qchong** [flutter/flutter#4393]
Provide documentation per user request:
"Guidelines for various common layouts would help a noob like me. E.g. when to use Table vs Column/Row vs Grid, or how to use Flex and padding inside Column/Row to achieve a certain look."

**Comment by sethladd** [comment]
Objective:

- Introduce developers to how Flutter thinks about layouts
- Overview of the provided layout primitives
- Explains how layout relates to widgets and material (where does this fit in the overall picture)
- Link to our layout-related classes in our API docs
- Links to example layouts used in the gallery demo

A follow-on doc could teach the developer how to do their own custom layouts.

**Comment by sethladd** [comment]
From https://github.com/flutter/flutter/issues/6960

The docs for these widgets try to explain the conceptual model behind the layout instead of helping the reader solve their problems.

The specific problem that people have is getting one of the children to fill the available space (i.e., they need help discovering Flexible).

**Comment by sethladd** [comment]
See also https://github.com/flutter/flutter/issues/7068

**Comment by sethladd** [comment]
Some notes from an offline conversation:

IMHO we need a expample-heavy tutorial that takes you from the Center widget to CustomMultiChildLayout. 

At the outset such a document would need to explain how a Scaffold's home widget is treated, i.e. that it's only as big as it needs to be and if you want to fill the available space you need to do this:

new SizedBox.expand(child: myAppHome)

Once that little whirlpool is out of the way, there are quite a few widgets to explain:

- The simplest layout widgets. I'm guessing they're used the most often. There are other widgets that are used along with them, like Flexible (with Row and Column), and Positioned (with Stack).
Center
SizedBox
Align
Padding
Row
Column
Flow
Stack
Container
FittedBox

- There's also these three. They're all vital glue widgets and the last one is particularly important to layout.
Builder
StatefulBuilder
LayoutBuilder

- Most of the rest of the layout widgets. It's important for developers to realize that if they're creating some inordinately complex tree of layout widgets, they might be better off using one of the two Custom layouts at the end.

ConstrainedBox
FractionallySizedBox
OverflowBox
SizedOverflowBox
IndexedStack
FractionalTranslation
RotatedBox
AspectRatio
IntrinsicWidth
IntrinsicHeight
Baseline
CustomGrid
FixedColumnCountGrid
MaxTileWidthGrid
CustomSingleChildLayout
CustsomMultiChildLayout

The scrolling widgets can be viewed as another category of layout widgets. There's a fair amount of complexity here and the scrolling APIs are about to get a major overhaul (Ian).

There are also a set of widgets that animate layouts, and of course we want people to get comfortable using those too

**Comment by sethladd** [comment]
More comments from a current Flutter developer, that seem to be related to layouts:

How constraints interact is a tricky concept. I think the docs could use some concrete examples, and lots of images (and perhaps an interactive constraints exploration tool). Tighten, tightFor, loosen — these are all new concepts to most UI developers. 

The flutter.io constraints introduction has a lot of description about how constraints technically work, but could use more documentation about how to work with and debug constraints. For example, the intro notes that “many of the boxes in Flutter, especially those that just take a single child, will pass their constraint on to their children”, and “Some boxes loosen the constraints”, and “others vary based on the constraints they are given”. A new developer may interpret this intro as “constraints work in a lot of different ways — look at the Flutter source code to figure out what is actually going on.” One thing that may help is a table with all the commonly used widgets and a description of how their constraints work — something to help navigate the world of constraints, and to help debug.

**Comment by Sfshaza** [comment]
I've published [Building Layouts in Flutter](https://flutter.io/tutorials/layout/). 

Closing this bug.

**Comment by sethladd** [comment]
Thanks!
