### ISSUE TITLE
[firebase_core] Support firebase_core on the web.

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#43940]
The `firebase_core` plugin should work on the web.

**Comment by hterkelsen** [comment]
PR out for adding platform interface: https://github.com/FirebaseExtended/flutterfire/pull/1324

**Comment by IchordeDionysos** [comment]
Is the support for the other Firebase SDKs also planned?

**Comment by prujohn** [comment]
Good to see this on the roadmap. 

In the interim, I've been using the js wrapper lib https://pub.dev/packages/firebase to interact with firebase services for database, storage, and authentication (to google).  I've also been able to publish flutter web apps to firebase hosting via cli commands.

**Comment by hterkelsen** [comment]
PR is out for migrating to the platform interface: https://github.com/FirebaseExtended/flutterfire/pull/1472

**Comment by collinjackson** [comment]
@hterkelsen can we close this issue? 

Support was added in https://github.com/FirebaseExtended/flutterfire/pull/1324 and https://github.com/FirebaseExtended/flutterfire/pull/1472

**Comment by hterkelsen** [comment]
I have one more PR to write, which adds `firebase_core_web`
