### ISSUE TITLE
when I buid --debug,it work, but,when I build --release,it  fail.

### ISSUE THREAD

**Issue by qiuguian** [flutter/flutter#43953]
![image](https://user-images.githubusercontent.com/7962840/68000186-04f77480-fc9a-11e9-9336-80c92a907d2d.png)

![image](https://user-images.githubusercontent.com/7962840/68000165-ef824a80-fc99-11e9-8652-00f93454ef51.png)

**Comment by qiuguian** [comment]
please help me to make it right?

**Comment by kassadin** [comment]
Seems to be a version compatibility issue

> Upgrade com.android.tools.build:gradle to v3.2.1 or later.
> Upgrade compileSdkVersion to 28 or later.
> Update your app to use Jetpack (AndroidX)

**Comment by qiuguian** [comment]
good job! Thank you
