### ISSUE TITLE
why flutter to build apk take a lot time?

### ISSUE THREAD

**Issue by qiuguian** [flutter/flutter#43951]
why flutter to build apk take a lot time?

**Comment by qiuguian** [comment]
take more time to build than before

**Comment by jonahwilliams** [comment]
Are you building a fat APK? that will include three different ABIs so those take a lot of time to build. If you're only using it locally and not distributing to an app store, you could only build the single ABI you are using: `flutter build apk --target-platform=android-arm64`

**Comment by qiuguian** [comment]
if distribute to an app store ,using:flutter build apk --target-platform android-arm,android-arm64?
