### ISSUE TITLE
[in_app_purchase] Crash in in_app_purchase 0.2.2+2

### ISSUE THREAD

**Issue by NikitaZhelonkin** [flutter/flutter#43969]
In play billing api appeared new error code `SERVICE_TIMEOUT = -3;`
Got a crash while parsing enum with that code

```
Invalid argument(s): `-3` is not one of the supported values: -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8
_$enumDecode.<fn> (enum_converters.g.dart:28)
Iterable.singleWhere (iterable.dart:625)
._$enumDecode (enum_converters.g.dart:27)
BillingResponseConverter.fromJson (enum_converters.dart:18)
._$PurchasesResultWrapperFromJson (purchase_wrapper.g.dart:36)
new PurchasesResultWrapper.fromJson (purchase_wrapper.dart:108)
BillingClient.queryPurchases (billing_client_wrapper.dart:174)
GooglePlayConnection.queryPastPurchases (google_play_connection.dart:86)
```

**Comment by NikitaZhelonkin** [comment]
I created PR to fix this https://github.com/flutter/plugins/pull/2248

**Comment by TahaTesser** [comment]
hI @NikitaZhelonkin 
Are you still experiencing this issue with latest stable?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by NikitaZhelonkin** [comment]
I see in repository that you didn't fix it. It means that it still actual. I made a PR with fix long time ago.
The issue happens because you don't handle '-3' response code that appeared recently

**Comment by sowens-csd** [comment]
I just saw the same issue after submitting a Flutter app to the play store. Play Store validation apparently sends the -3 code and in_app_purchase plugin doesn't handle it. See the Android docs here for reference: https://developer.android.com/reference/com/android/billingclient/api/BillingClient.BillingResponseCode#service_timeout

Pretty sure the problem is in lib/src/billing_client_wrappers/billing_client_wrapper.dart, the `BillingResponse` enum should include -3 and doesn't. Here's the current definition. 

```dart
enum BillingResponse {
  // WARNING: Changes to this class need to be reflected in our generated code.
  // Run `flutter packages pub run build_runner watch` to rebuild and watch for
  // further changes.
  @JsonValue(-2)
  featureNotSupported,

  @JsonValue(-1)
  serviceDisconnected,

  @JsonValue(0)
  ok,

  @JsonValue(1)
  userCanceled,

  @JsonValue(2)
  serviceUnavailable,

  @JsonValue(3)
  billingUnavailable,

  @JsonValue(4)
  itemUnavailable,

  @JsonValue(5)
  developerError,

  @JsonValue(6)
  error,

  @JsonValue(7)
  itemAlreadyOwned,

  @JsonValue(8)
  itemNotOwned,
}
```

**Comment by jumper423** [comment]
Duplicate of #65237
