### ISSUE TITLE
Flutter doctor not recognizing "IntelliJ IDEA 2.app" on mac OSX

### ISSUE THREAD

**Issue by hhkk** [flutter/flutter#43964]
Subject: Flutter doctor not recognizing IntelliJ on mac OSX

Question: why does flutter doctor not show anything about IntelliJ on mac OSX, despite my being able to launch and debug even the Android emulator? 

(I'm pretty sure it worked at some point in the last few weeks)

Thanks!

~/recipes_app>flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.368, on Mac OS X 10.14.6 18G87, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.0)
[✓] Connected device (3 available)

• No issues found!
~/recipes_app>

**Comment by iapicca** [comment]
Hi @hhkk 
can you please provide your `flutter doctor -v`?
Did you try with a fresh installation following the [documentation](https://flutter.dev/docs/get-started/install/macos)?
Thank you

**Comment by jmagman** [comment]
Where is IntelliJ installed?

I see it on my machine:
```
$ flutter doctor  
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.382, on Mac OS X 10.14.6 18G87, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
[✓] VS Code (version 1.39.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by hhkk** [comment]
In /Applications/IntelliJ IDEA 2.app

i wonder if installing flutter again would help.

~/utd/a191020FlutterRecipe/recipes_app>flutter -v doctor
[✓] Flutter (Channel master, v1.10.15-pre.368, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.10.15-pre.368 at /Users/hkon/dev/flutter
    • Framework revision 3cd8c3142c (23 hours ago), 2019-10-31 19:35:52 -0700
    • Engine revision 8ea19b1c76
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/hkon/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.87
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
~/utd/a191020FlutterRecipe/recipes_app>

**Comment by jmagman** [comment]
@hhkk Did you mean to close this?  If so, how did you fix it?

**Comment by hhkk** [comment]
I did not mean to close.  It is still an issue for me.   How to unclose?

Thanks

**Comment by christopherfujino** [comment]
@hhkk we discover installations of IntelliJ by checking for the following app names:

```
  817   static final Map<String, String> _dirNameToId = <String, String>{
  818   ⎸ 'IntelliJ IDEA.app': 'IntelliJIdea',
  819   ⎸ 'IntelliJ IDEA Ultimate.app': 'IntelliJIdea',
  820   ⎸ 'IntelliJ IDEA CE.app': 'IdeaIC',
  821   };
```

Thus it is not detecting `IntelliJ IDEA 2.app`. This should be fixed, but if you are still in this broken state, renaming the app to `IntelliJ IDEA.app` is a workaround.
