### ISSUE TITLE
Android flutter webview “location.replace” doesn't work

### ISSUE THREAD

**Issue by liuguoping981** [flutter/flutter#43962]
## Steps to Reproduce

Here is our Html pages A --> B --> C.  

We use 'window.location.replace' to replace Page-B with Page-C, so that when we press back on page-C , it will back to Page-A. 

For the plugin 'webview_flutter', it will back to Page-B, not Page-A.
That is not what we want. 

But for the plugin ''flutter_webview_plugin" [https://github.com/fluttercommunity/flutter_webview_plugin](url), everything is OK.

So we wondered what is wrong, and find a similiar topic here:

https://stackoverflow.com/questions/14333620/android-webview-location-replace-doesnt-work

After check the code of flutter_webview_plugin , We did some test. 

This is the original code of webview_flutter:
```
private boolean shouldOverrideUrlLoading(WebView view, String url) {
    if (!hasNavigationDelegate) {
      return false;
    }
    Log.w(
        TAG,
        "Using a navigationDelegate with an old webview implementation, pages with frames or iframes will not work");
    notifyOnNavigationRequest(url, null, view, true);
    return true;
  }
```
And this is the modified code:

```
private boolean shouldOverrideUrlLoading(WebView view, String url) {
    if (!hasNavigationDelegate) {
      return false;
    }
    
    if(url.contails("your patterns")){
	    Log.w(
	        TAG,
	        "Using a navigationDelegate with an old webview implementation, pages with frames or iframes will not work");
	    notifyOnNavigationRequest(url, null, view, true);
	    return true;
    }
    return false;
  }
```
Now, the PageC can back to PageA directly.

So we think the function #shouldOvershouldOverrideUrlLoading() should be fixed.

Please check the code below and fixed the issue.
https://github.com/fluttercommunity/flutter_webview_plugin/blob/master/android/src/main/java/com/flutter_webview_plugin/BrowserClient.java

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G84, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.2 at /Users/liuguoping981/development/flutter_1.9.1_stable
    • Framework revision 2d2a1ffec9 (8 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/liuguoping981/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/liuguoping981/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode_v10.3.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.7)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1
```

**Comment by iapicca** [comment]
Hi @liuguoping981 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/32414)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by liuguoping981** [comment]
@iapicca I think that is not the same issue. 

current  issue is a bug for the official plugin 'webview_flutter', not the other plugins.

We think the plugin 'webview_flutter' may be make some fault when handling the interface [https://developer.android.com/reference/android/webkit/WebViewClient#shouldOverrideUrlLoading(android.webkit.WebView,%20android.webkit.WebResourceRequest)](url)  of android webview. 

```
Give the host application a chance to take control when a URL is about to be loaded in the current WebView. If a WebViewClient is not provided, by default WebView will ask Activity Manager to choose the proper handler for the URL. If a WebViewClient is provided, returning true causes the current WebView to abort loading the URL, while returning false causes the WebView to continue loading the URL as usual.
```
