### ISSUE TITLE
Flutter [web] image.network work in web but not in mobile

### ISSUE THREAD

**Issue by ricky2151** [flutter/flutter#43966]
## Steps to Reproduce

1. I made a new flutter_web project by (https://flutter.dev/docs/get-started/web)
2. I added the image file to the assets folder
3. Then I create an asset.image widget with the url of the image
The following code snippet:
new Image.asset ("images / appbar / logo.png"),
4. After I change from `Image.asset` to `Image.network`, images can appear.

If so, then I can't make one code that can be compiled directly to the web & mobile. Is there a solution so I can make one code for mobile & web at the same time?

**Target Platform: Web**
**Target OS version/browser: Chrome**
**Devices: Windows 10**

## Logs

```
```

```
```

```
```

**Comment by iapicca** [comment]
hi @ricky2151 
I'm not sure to understand the issue;
following the [documentation ](https://flutter.dev/docs/cookbook/images/network-image#complete-example) `Image.network` works just fine on mobile,
can you be more specific?
thank you

**Comment by ricky2151** [comment]
Yes, image.network works well on mobile. However, image.network on mobile is only used to load images from the internet. Whereas what I'm concerned about is how to load images from ASSETS.

On mobile flutter, the way to load images from assets is with Image.asset. But on the web flutter, the way to load images from assets is by image.network (https://github.com/flutter/flutter/issues/33659)

So if this is true, then the code used on mobile to load assets is different from the code used on the web. Then is there a solution so that the code used remains the same?

**Comment by iapicca** [comment]
Hi again @ricky2151 
thank you for the clarification,
could you please provide your `flutter doctor -v`,
thank you

**Comment by cbenhagen** [comment]
@ricky2151 `Image.network` and `Image.asset` work as expected for me. Please update to the current beta channel and retry. If it does not work, please provide a full example and the output of `flutter doctor -v`.

**Comment by CXZ7720** [comment]
Hello.
I have exactly same problem.

I made my assets folder at project root directory and added it to `pubspec.yaml` too.
I used `Asset.Image('assets/images/domain.png')` to show `png` formatted image in my webpage, but flutter can't find where it is.
```
Error while trying to load an asset: Failed to load asset at "assets/images/domain.png" (404)
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞══════
The following assertion was thrown resolving an image codec:
Unable to load asset: assets/images/domain.png
``` 
I changed my code to `Asset.network('assets/images/domain.png)` and moved assets folder into `www` folder. Then, it works perfectly.

Here is my `flutter doctor -v` result.
```
D:\DEV>flutter doctor -v
[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [Version 10.0.18363.628], locale ko-KR)
    • Flutter version 1.14.6 at C:\src\flutter
    • Framework revision fabeb2a16f (9 days ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\kygha\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.2
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\kygha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.130
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by formatCvt** [comment]
@iapicca looks like related to this https://github.com/flutter/flutter/issues/46945

**Comment by Iampato** [comment]
After reading official docs on the matter here:
https://flutter.dev/docs/development/platform-integration/web-images
I tried the doing normal http get with cors origin it did not work, So i opted for the final option use htmlElements
```
class CustomImage extends StatelessWidget {
  final String imageUrl;

  const CustomImage({Key key, this.imageUrl}) : super(key: key);

  Widget build(BuildContext context) {
    ui.platformViewRegistry.registerViewFactory(
      imageUrl,
      (int viewId) => ImageElement()..src = imageUrl,
    );
    return HtmlElementView(
      viewType: imageUrl,
    );
  }
}

```

**Comment by yousefmasry4** [comment]
just add  **cors.json** in web folder
```
[
  {
    "origin": ["*"],
    "method": ["GET"],
    "maxAgeSeconds": 3600
  }
]
```
