### ISSUE TITLE
camera example doesn't support landscape

### ISSUE THREAD

**Issue by syonip** [flutter/flutter#43960]
When rotating the phone to landscape mode, the camera preview doesn't behave correctly.
The preview still has portrait proportions, but pointing the phone up or down moves the preview sideways, and vice versa.

Tested on an Android device.

**Comment by iapicca** [comment]
Hi @syonip 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/39669)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
