### ISSUE TITLE
Hint to the user that name prefixes can be used with -d

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4396]
In the flutter CLI tool, `-d` is the way to specify which device to use. We have a great little feature that lets a user use a _prefix_ with either the ID or the name when specifying the device.

We could make this more discoverable if the `-d` option's help text mentioned the prefix.

For example, today we say:

`-d, --device-id       Target device id.`

We could instead say:

`-d, --device-id       Target device id or name. Prefixes allowed.`

**Comment by devoncarew** [comment]
dup of https://github.com/flutter/flutter/issues/4330
