### ISSUE TITLE
Is there any way to change the row line color of DataTable?

### ISSUE THREAD

**Issue by YRlp98** [flutter/flutter#43975]
I'm using DataTable in my recent app and I need to change the color of the row line or make it invisible (i mean I don't want to my table shows any row line)

If anyone knows please help! thanks

**Comment by skaran921** [comment]
yes its possible i have done it.
for this you want to done some changes in flutter data_table.dart fille
for more details. 
i attached modified flutter data_table.dart file check zip file.
replace your flutter data_table file with the attached data_table file
[dataTable.zip](https://github.com/flutter/flutter/files/3901161/dataTable.zip)

**Comment by YRlp98** [comment]
> yes its possible i have done it.
> for this you want to done some changes in flutter data_table.dart fille
> for more details.
> i attached modified flutter data_table.dart file check zip file.
> replace your flutter data_table file with the attached data_table file
> [dataTable.zip](https://github.com/flutter/flutter/files/3901161/dataTable.zip)

Thanks.
Also, it is possible to change it via overriding the dividerColor.

**Comment by skaran921** [comment]
i don't try

**Comment by VladyslavBondarenko** [comment]
Closing since solved
