### ISSUE TITLE
Receive data from external app sharing [ios]

### ISSUE THREAD

**Issue by DarlyLi** [flutter/flutter#43971]
I tried to receive the content Shared by the external app in my flutter app. I found the Android solution on the website of flutter, but I haven't found the ios one yet. Could you please tell me how can I implement this function on the ios? thanks

**Comment by iapicca** [comment]
HI @DarlyLi 
can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by jmagman** [comment]
@DarlyLi What kind of content are you trying to consume with your app?

Do you mean a sharing extension?
https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Share.html

Or do you mean creating a custom scheme to open a URL with your app? https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app?language=objc

**Comment by DarlyLi** [comment]
谢谢，我找到了实现方法
https://github.com/KasemJaffer/receive_sharing_intent/tree/master/example

**Comment by DarlyLi** [comment]
Thank you, I found the implementation method.
https://github.com/KasemJaffer/receive_sharing_intent/tree/master/example
