### ISSUE TITLE
[WEB] Image widget color painting is not working

### ISSUE THREAD

**Issue by Xadovsk** [flutter/flutter#43984]
When I import an image on flutter and use the color attribute, it's color doesn't change. It works fine on Android and IOS but not on web.
Steps to reproduce:
1 - import an image using Image widget.
2 - set the color of the image
3 - run app on chrome `flutter run -d chrome`

tools version : 
```
Flutter 1.10.15-pre.309 • channel master • https://github.com/flutter/flutter
Framework • revision 5f6ca6838e (3 days ago) • 2019-10-29 12:23:16 -0700
Engine • revision 419f5d594a
Tools • Dart 2.6.0 (build 2.6.0-dev.8.2 e1fce75301)
```
Sample code:
```
import 'package:flutter/material.dart';
void main() {
  runApp(App());
}
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Image.network(
      'https://www.stickpng.com/assets/images/580b585b2edbce24c47b2717.png',
      color: Colors.orange,
    );
  }
}
```
expected:
<img width="384" alt="Screen Shot 2019-11-01 at 11 14 46" src="https://user-images.githubusercontent.com/56688906/68030844-2146e180-fc99-11e9-80cc-175566718695.png">
reality:
<img width="1199" alt="Screen Shot 2019-11-01 at 11 15 29" src="https://user-images.githubusercontent.com/56688906/68030845-2146e180-fc99-11e9-93e3-267dac83d379.png">

**Comment by tolstenko** [comment]
This the same problem is described at https://github.com/flutter/flutter/issues/33316 but this one is showing the screenshots.
Do we have a workaround for this? Maybe getting the raw pixels, painting them one by one and then showing the image? idk

**Comment by hahafather007** [comment]
Same problem, hope it be solved quickly.

**Comment by hahafather007** [comment]
Any progress?

**Comment by gskinner-shared** [comment]
Fixed? https://github.com/flutter/flutter/issues/56071

**Comment by iapicca** [comment]
Hi @Xadovsk 
I see there's an open [issue](https://github.com/flutter/flutter/issues/33316#issuecomment-653476040) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
