### ISSUE TITLE
[ios][release] GeneratedPluginRegistrant.m Module not found

### ISSUE THREAD

**Issue by nguyenhuutinh** [flutter/flutter#43986]
Hi,
I can run `flutter build ios`, even can work with debug mode on devices
But when I want to release to store, Xcode cannot compile code.
Error: Module xxx not found
I delete it and got same error with the second module

Do you know why?

I use the latest version of Flutter and Xcode

Thanks

**Comment by nguyenhuutinh** [comment]
<img width="1071" alt="Screenshot 2019-11-01 at 10 42 34 PM" src="https://user-images.githubusercontent.com/4114159/68032565-eb394a00-fcf8-11e9-89a6-7efed0b752b0.png">

**Comment by nguyenhuutinh** [comment]
my fault
https://github.com/flutter/flutter/issues/41033

**Comment by Sayed-Samy** [comment]
Did you find a solution ?

**Comment by pratik-perpetualny** [comment]
I am also looking for a solution.

**Comment by fliermanrw** [comment]
I would also like to know what solved the problem. I have the following error:

``` 
ios/Runner/GeneratedPluginRegistrant.m:10:9: Module 'location' not found
```
(and every next module when deleting location)

**Comment by ehosseini** [comment]
I have got the same issue.

**Comment by Kenoshen** [comment]
+1 same issue

**Comment by DavideBicego** [comment]
Opening the project with Runner.xcworkspace doesn't work for me!
Did anyone found a solution?

**Comment by Kenoshen** [comment]
On top of trying the xcworkspace trick, previously, I had tried deleting the Podsfile.lock, cleaning the project, changing the Podsfile min version to 9, or something like that.  So it is possible some combination of those things plus the xcworkspace thing is the actual solution.

**Comment by MrCreeper1008** [comment]
Nothing worked for me.

**Comment by jaredanderton** [comment]
This was the only thing that worked for me: 

`rm ios/Podfile && flutter build ios`

I think I had ran `pod init` manually, prior to ever building the app from Flutter.  Because of that my Podfile was missing the commands to pull in all the other pods. I only noticed the issue after I added a package to my pubspec.yaml, that actually required using a platform channel.

**Comment by cmonney** [comment]
@jaredanderton thanks. It worked for me too

**Comment by JasMich** [comment]
I fixed
 * close Xcode
 * uncommenting `//platform :ios, '9.0'`
 * ```shell
cd ./ios/
pod install
flutter clean # cancel by ctrl+c i hangs up
```
 * open `ios/Runner.xcworkspace`

**Comment by LeoPote** [comment]
> I fixed it the following way:
> 
> * close Xcode
> * uncomment `#platform :ios, '9.0'`
> 
> ```shell
> cd ./ios/
> pod install
> flutter clean # cancel by ctrl+c i hangs up
> ```
> 
> * open `ios/Runner.xcworkspace`

This worked for me too...

**Comment by akvilibrium** [comment]
> I may have found the answer from this comment:
> 
> [#21989 (comment)](https://github.com/flutter/flutter/issues/21989#issuecomment-513286777)
> 
> Seems like by opening up the project by double clicking `Runner.xcworkspace` instead of `Runner.xcodeproj` xcode can finally figure out where everything is. Even though you can still debug in an emulator and on a connected phone from the `.xcodeproj` file...
> 
> Seems strange that it would fix it. But I'm happy to have an Archived build now.

Really thank you! It works well for me!
// it requires `pod install` from terminal btw

**Comment by rushabhshah065** [comment]
None of the above works for me!
I have done many work through but did not find anything!
<img width="1079" alt="Screen Shot 2020-03-30 at 6 36 03 PM" src="https://user-images.githubusercontent.com/48256486/77915569-55a8e300-72b5-11ea-8373-8e9d6ad6b7cf.png">

**Comment by IamStupidMan** [comment]
> None of the above works for me!
> I have done many work through but did not find anything!
> <img alt="Screen Shot 2020-03-30 at 6 36 03 PM" width="1079" src="https://user-images.githubusercontent.com/48256486/77915569-55a8e300-72b5-11ea-8373-8e9d6ad6b7cf.png">
Did you resolve this issue?

**Comment by yazinsai** [comment]
For me, it turned out the issue was that I was opening `ios/.xcodeproj` instead of `ios/Runner.xcworkspace`.

Opening `ios/Runner.xcworkspace` worked!

**Comment by davidgalarza** [comment]
Any update I'm facing the same issue, I'm sure that  I open the ios/Runner.xcworkspace

**Comment by TheOneWithTheBraid** [comment]
@davidgalarza did you try https://github.com/flutter/flutter/issues/43986#issuecomment-583020657 ?

**Comment by davidgalarza** [comment]
@TheOneWithTheBraid Yes I tried It but did't work

**Comment by parvshkhan** [comment]
> None of the above works for me!
> I have done many work through but did not find anything!
> <img alt="Screen Shot 2020-03-30 at 6 36 03 PM" width="1079" src="https://user-images.githubusercontent.com/48256486/77915569-55a8e300-72b5-11ea-8373-8e9d6ad6b7cf.png">
> Did you resolve this issue?

Any solution

**Comment by HerrNiklasRaab** [comment]
@IamStupidMan @parvshkhan I am stuck with exactly the same, did you found a solution to this? I will pay you a beer :D

**Comment by HerrNiklasRaab** [comment]
@IamStupidMan @parvshkhan @rushabhshah065 

I figured it out for me.

If you have this problem with cloud_firestore and you are using configurations, I am 100% this will fix the issue.

I had multiple xcode configurations and in the scheme there was the wrong configuration associated with the scheme. In my case I needed to change it from Release to Release-development. Also make sure that alle the configurations on the left column are the once you created. 

![image](https://user-images.githubusercontent.com/28401593/80252867-81cb4000-8678-11ea-800d-b7838afaf212.png)

This are my configurations:
![image](https://user-images.githubusercontent.com/28401593/80253129-faca9780-8678-11ea-86e1-a5629173acff.png)

**Comment by ZionPi** [comment]
> @TheOneWithTheBraid Yes I tried It but did't work

Same here.Still get `Module 'connectivity' not found`.By the way, run `flutter build ios` and run button in AnroidStudio can install the app, but Open `Runner.xcworkspace` cannot work.

**Comment by izht** [comment]
For me, my Podfile specify ios version as `platform :ios, '11.0'` and it work perfectly when run both on emulator and real device. but it does't work for `flutter build ios` nor xcode archive

After a week of headache, finally I able to fixed it by match an ios target in the deployment info here 

![image](https://user-images.githubusercontent.com/3109773/80622840-8ecea180-8a73-11ea-9740-bf23f7cb99c5.png)

**Comment by phodonou** [comment]
> @IamStupidMan @parvshkhan @rushabhshah065
> 
> I figured it out for me.
> 
> If you have this problem with cloud_firestore and you are using configurations, I am 100% this will fix the issue.
> 
> I had multiple xcode configurations and in the scheme there was the wrong configuration associated with the scheme. In my case I needed to change it from Release to Release-development. Also make sure that alle the configurations on the left column are the once you created.
> 
> ![image](https://user-images.githubusercontent.com/28401593/80252867-81cb4000-8678-11ea-800d-b7838afaf212.png)
> 
> This are my configurations:
> ![image](https://user-images.githubusercontent.com/28401593/80253129-faca9780-8678-11ea-86e1-a5629173acff.png)

This works for me. If you're using different configurations, make sure you do this.

**Comment by jawad12345A** [comment]
I am also facing this issue

**Comment by jawad12345A** [comment]
I am also getting this error . Does anyone know about it? 


[!] A license was specified in podspec `audioplayers` but the file does not exist - /Users/apple/Desktop/flutter_mp3/courses_app/ios/.symlinks/plugins/audioplayers/LICENSE.md

[!] Unable to read the license file `../LICENSE.md` for the spec `audioplayers (0.0.1)`

[!] Unable to read the license file `../LICENSE.md` for the spec `audioplayers (0.0.1)`

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

**Comment by phodonou** [comment]
Did you choose the target as `Runner` in xcode?

**Comment by phodonou** [comment]
Also, are you building in different flavors?

**Comment by jawad12345A** [comment]
Yes i choose target as runner

**Comment by nickgrahamfox** [comment]
> For me, it turned out the issue was that I was opening `ios/Runner.xcodeproj` instead of `ios/Runner.xcworkspace`.
> 
> Opening `ios/Runner.xcworkspace` worked!

The above fixed my issue as well.  Thank you!

**Comment by ericaig** [comment]
> For me, it turned out the issue was that I was opening `ios/Runner.xcodeproj` instead of `ios/Runner.xcworkspace`.
> 
> Opening `ios/Runner.xcworkspace` worked!

As it turned out, I was doing the same thing 🤦🏽‍♂️  -.... was super used doing running `npx cap open ios` on Ionic

**Comment by chris-makaio** [comment]
It seems most of you found a solution here. I did not, but the deployment target issue made me check all of the pod targets. Although I've iOS 13 in the pod file, although I've set iOS 13 as deployment target like... everywhere ... every single pod framework / target still showed iOS 8, iOS 9 or iOS 11.
So I shift-selected all of them and changed the deployment target to iOS 13: 
<img width="792" alt="Bildschirmfoto 2020-10-01 um 00 49 01" src="https://user-images.githubusercontent.com/26594889/94747724-f0c36800-037f-11eb-9e89-4d8942acc495.png">

Phew, back in business

**Comment by MuhammadFaizan980** [comment]
ok, here is what worked for me:

1. run `flutter clean`
2. delete `pod` file and `pod file.lock`
3. delete `Pods` directory
4. run `flutter run`
Previously I installed pod dependencies using `pod install` but installing with `flutter run` is what fixed the issue

**Comment by hirakchhatbar** [comment]
> For me, it turned out the issue was that I was opening `ios/Runner.xcodeproj` instead of `ios/Runner.xcworkspace`.
> 
> Opening `ios/Runner.xcworkspace` worked!

And I thought only google android is wierd!

**Comment by dinury-unitalks** [comment]
> For me, it turned out the issue was that I was opening `ios/Runner.xcodeproj` instead of `ios/Runner.xcworkspace`.
> 
> Opening `ios/Runner.xcworkspace` worked!

Finally after trying every possible solution this actually helped

**Comment by FickleLife** [comment]
> @IamStupidMan @parvshkhan @rushabhshah065
> 
> I figured it out for me.
> 
> If you have this problem with cloud_firestore and you are using configurations, I am 100% this will fix the issue.
> 
> I had multiple xcode configurations and in the scheme there was the wrong configuration associated with the scheme. In my case I needed to change it from Release to Release-development. Also make sure that alle the configurations on the left column are the once you created.
> 
> ![image](https://user-images.githubusercontent.com/28401593/80252867-81cb4000-8678-11ea-800d-b7838afaf212.png)
> 
> This are my configurations:
> ![image](https://user-images.githubusercontent.com/28401593/80253129-faca9780-8678-11ea-86e1-a5629173acff.png)

Is there anyway to specify the configuration from the command line? after a `flutter clean` it defaults to `release`, which breaks the build. Ideally I can defined this at the command line, or it can default to `release-prod`.

**Comment by ondev** [comment]
rm ios/Podfile
rm ios/Podfile.lock
rm -rf ios/Pods
rm -rf ios/Runner.xcworkspace
flutter clean
flutter build ios

work for me.

**Comment by ethdevss** [comment]
@izht 

Awesome !!
it is very helpful for me.

Thank you!!!

**Comment by tolik85** [comment]
> For me, my Podfile specify ios version as `platform :ios, '11.0'` and it work perfectly when run both on emulator and real device. but it does't work for `flutter build ios` nor xcode archive
> 
> After a week of headache, finally I able to fixed it by match an ios target in the deployment info here
> 
> ![image](https://user-images.githubusercontent.com/3109773/80622840-8ecea180-8a73-11ea-9740-bf23f7cb99c5.png)

OMG! How did you find it???

**Comment by nimi0112** [comment]
> @IamStupidMan @parvshkhan @rushabhshah065
> 
> I figured it out for me.
> 
> If you have this problem with cloud_firestore and you are using configurations, I am 100% this will fix the issue.
> 
> I had multiple xcode configurations and in the scheme there was the wrong configuration associated with the scheme. In my case I needed to change it from Release to Release-development. Also make sure that alle the configurations on the left column are the once you created.
> 
> ![image](https://user-images.githubusercontent.com/28401593/80252867-81cb4000-8678-11ea-800d-b7838afaf212.png)
> 
> This are my configurations:
> ![image](https://user-images.githubusercontent.com/28401593/80253129-faca9780-8678-11ea-86e1-a5629173acff.png)

Thanks you, I have set that field to prod in my config ❤️

**Comment by kcbaruri** [comment]
I am experiencing the same problem and no one from above is working.

**Comment by ehcpdeveloper** [comment]
Solved following way:
Open XCode project settings, ios target version: 12 (same as in podfile)
(it was not 12)
rebuild. ok.
