### ISSUE TITLE
Flutter Web: pinch and zoom not recognized

### ISSUE THREAD

**Issue by khari998** [flutter/flutter#43983]
This is not an error that is produced by a log. I am currently using a Macbook Pro and I can pinch and zoom on any chrome website with my trackpad. I am currently not able to do this when loading a Flutter Web application. Is there any way to enable this? Applications deployed to web should have this enabled by default.

**Comment by yjbanov** [comment]
This is duplicate of https://github.com/flutter/flutter/issues/23604
