### ISSUE TITLE
Does webview_flutter support post method?

### ISSUE THREAD

**Issue by eco4ndly** [flutter/flutter#43992]
I am not able to find any api to post data with url.

I have a situation where I need to post data to load a url

Does this library support post data?

**Comment by iapicca** [comment]
Hi @eco4ndly 
I see there's an open issue addressing the [case ](https://github.com/flutter/flutter/issues/29930)you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by eco4ndly** [comment]
Thanks @iapicca
