### ISSUE TITLE
Pesto recipe page on iOS

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4399]
- [x] black bar across the top
- [x] shadow on image seems to start on the image, instead of behind it (?)  (notice the white bar that fades into the shadow across the top and sides of the image)
- [ ] I can pull down the text block and expose a black background under the image

![b110b7b4-179c-4e4c-82d9-80f6c17a3ce5](https://cloud.githubusercontent.com/assets/5479/15839631/2d4834da-2bf9-11e6-945f-e14cf861a21f.PNG)

**Comment by sethladd** [comment]
cc @mpcomplete

**Comment by chinmaygarde** [comment]
I don't understand what is iOS specific about this issue.

**Comment by cbracken** [comment]
There've been some behavioural changes to Pesto since this was filed -- specifically, we no longer do a stretch overscroll on iOS. Is this still an issue?

**Comment by sethladd** [comment]
Closing for now.
