### ISSUE TITLE
flutter run linker error: framework not found Flutter

### ISSUE THREAD

**Issue by Wesley1993** [flutter/flutter#43996]
## Steps to Reproduce

1. tool:Xcode 11.2 ;system:mac os 10.15.1
2. after 'flutter run',output:'
Xcode's output:
    ld: framework not found Flutter
    clang: error: linker command failed with exit code 1 (use -v to see
    invocation)
    note: Using new build system
    note: Planning build
    note: Constructing build description'

## Logs

```
```

![image](https://user-images.githubusercontent.com/24308685/68044227-dd43f300-fd11-11e9-83fd-e3e6abfbc202.png)

**Comment by jmagman** [comment]
Can we get logs from `flutter run --verbose`?

**Comment by Wesley1993** [comment]
![image](https://user-images.githubusercontent.com/24308685/68065155-d2b04a80-fd5f-11e9-8f70-f6041f672eab.png)

**Comment by jmagman** [comment]
That screenshot cut off the actual error.  Can we get the full log?
Is this an [add-to-app module](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) by any chance?

**Comment by ZacharyEilers** [comment]
I've having this same issue

**Comment by Wesley1993** [comment]
I se























i solve this problem by reinstalling Flutter.

**Comment by Wesley1993** [comment]
i solve this problem by reinstalling Flutter.

**Comment by ZacharyEilers** [comment]
Ahhh. I'll try that.

**Comment by ZacharyEilers** [comment]
How did you uninstall flutter?
Just delete the flutter folder where you installed it?

**Comment by jmagman** [comment]
Closing, sounds like this isn't reproducing anymore.
