### ISSUE TITLE
GpuThreadMerger.LeaseExtension and GpuThreadMerger.IsNotOnRasterizingThread are flakey

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#44002]
Example output: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8898032904990989376/+/steps/Host_Tests_for_host_debug_unopt/0/stdout?format=raw

I tried to repro this multiple times locally and I think I got it once.  It might happen less frequently if a debugger is attached.

Related PR: https://github.com/flutter/engine/pull/13480

I disabled the tests for now, we should bisect to figure it when they became flakey.

**Comment by amirh** [comment]
@iskakaushik

**Comment by goderbauer** [comment]
@iskakaushik Are you still looking at this flake?

**Comment by iskakaushik** [comment]
This has been fixed :-)
