### ISSUE TITLE
Pesto bar reappears with full-sized logo + word when returning from recipe page

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4400]
* scroll down to Garlic bok choy
* Tap the image
* Tap the back button icon in upper left

Expected:

![img_0034](https://cloud.githubusercontent.com/assets/5479/15840127/a2630f4e-2bfc-11e6-8d58-2bac010f0464.PNG)

Actual:

![img_0035](https://cloud.githubusercontent.com/assets/5479/15840130/a93f66e6-2bfc-11e6-8fcb-2e5b2025eea0.PNG)

**Comment by sethladd** [comment]
cc @mpcomplete

**Comment by eseidelGoogle** [comment]
Note in the image, that the app bar is too large, and is missing a shadow.

**Comment by sethladd** [comment]
We think this is fixed. Yay!
