### ISSUE TITLE
Create our own Github auto-merge bot

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#44007]
See https://github.com/flutter/flutter/issues/43672#issuecomment-548514885 and https://github.com/flutter/flutter/issues/43672#issuecomment-548541093 on why we need it.

See https://github.com/flutter/flutter/issues/43672#issuecomment-548541907 why we can't use third-party apps, and we need to create our own.

See https://github.com/flutter/flutter/issues/43672#issuecomment-548549811 for some implementation details.

**Comment by liyuqian** [comment]
@dnfield @Hixie : while I understand we can't use 3rd-party app directly, can we reuse some of their source code (e.g., fork their repo, or run their code in our own server)? It doesn't seem to be optimal to reinventing the wheels, and the other solution may already have spent a lot of time and engineers to figure out some corner cases that we haven't realized now.

**Comment by dnfield** [comment]
I have no strong opinions there.

On the one hand, writing our own for this doesn't seem all that difficult - we already have a lot of things in place based on the bot we already own.  We could write it in Dart and it could be something more of the team feels comfortable with.

On the other, an existing solution may be less work - as long as it doesn't have bugs or handle some case weirdly we don't like, and is written in a language no one on the team feels very comfortable maintaining.

**Comment by Hixie** [comment]
We're talking about a few dozen lines of code here at most, it's really not worth the hassle of using another language and figuring out licensing. It would take less time to just write the code.

**Comment by liyuqian** [comment]
Oh, I didn't realize that it's "a few dozen lines of code here at most" easy. So I guess that it can be done just in a few (or just one) hours? I'm very excited to see it happen. Please put me on reviewer or cc for that PR.

**Comment by dnfield** [comment]
I have a nearly working prototype for this.

**Comment by rmistry** [comment]
(+1000 to this issue and the discussion)
I am assuming that this auto-merge bot will be eventually activated for both flutter.git and engine.git.

**Comment by dnfield** [comment]
Yes.  I have a pull open in cocoon that would address this.  Going to write some tests for it today

**Comment by CaseyHillers** [comment]
Duplicate of https://github.com/flutter/flutter/issues/43113

**Comment by Hixie** [comment]
https://github.com/flutter/cocoon/pull/507

**Comment by liyuqian** [comment]
Fixed by https://github.com/flutter/cocoon/pull/507

**Comment by rmistry** [comment]
Is this up and running? have we seen it in action?

**Comment by liyuqian** [comment]
@rmistry : I tried it yesterday and filed an issue https://github.com/flutter/flutter/issues/45357 which is swiftly fixed by Dan today. I haven't done new experiments with it yet so I'm not sure whether there's other issue or not.

**Comment by CaseyHillers** [comment]
You can query `https://flutter-dashboard.appspot.com/api/check-waiting-pull-requests` manually, but right now the cron job is not on. Tree needs to be green and a PR with the waiting for tree to go green needs to be open.

**Comment by rmistry** [comment]
I'm going to wait a week or 2 before trying it out on the rollers (hopefully it lands a few in the meanwhile)
