### ISSUE TITLE
Add pixel 4 to our device lab

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#44006]
To use it for 90Hz rendering test and other tests that rely on higher Android API level.

**Comment by godofredoc** [comment]
@liyuqian do you know how much we want to expand testing on x64?

**Comment by liyuqian** [comment]
@goderbauer : did you mean arm64? For now I think just 1 pixel 4 would be enough.

**Comment by godofredoc** [comment]
Obsolete
