### ISSUE TITLE
flutter/plugins and FirebaseExtended/flutterfire should have a single source of truth for CI scripts

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#44000]
Right now CI scripts are duplicated, requiring the same change to be applied twice on both repos e.g:
https://github.com/flutter/plugins/pull/2250 and https://github.com/FirebaseExtended/flutterfire/pull/1349

We should have a single source of truth for the common scripts.

**Comment by amirh** [comment]
cc @collinjackson

**Comment by stuartmorgan** [comment]
Closing as obsolete since Flutterfire isn't using the same CI or tooling anymore.
