### ISSUE TITLE
Persist the memory profile timeline

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#44013]
As discussed with @terrylucas and @cobblest earlier, we'd like to persist the memory profile timeline (total usage without components breakdown is sufficient) for automated performance benchmarks (e.g., complex_layout_scroll_perf__memory in https://flutter-dashboard.appspot.com/benchmarks.html). It seems that DevTools can provide such a tool without too much work.

Specifically, it would be nice to have a command line tool so we can:
1. Start that tool in command line
2. Start a Flutter driver test (e.g., `flutter drive test_driver/scroll_perf.dar` inside `flutter/dev/benchmarks/complex_layout`)
3. Stop the tool when the driver test finishes
4. The tool exports a json file that represents the memory timeline between step 1 and 3.

Related issue: https://github.com/flutter/flutter/issues/40406

**Comment by liyuqian** [comment]
As discussed in today's meeting with @terrylucas and @cobblest , we're most interested in the total memory (not just the Dart VM memory) usage. We'd like such data to have a granularity of 1 second (i.e., polling adb every 1 second), or higher if the tool (e.g., adb) supports.

Next 2 weeks will be busy for Flutter for Web, and we'll resume our work and meeting on 11/19.

**Comment by terrylucas** [comment]
Can we resume meetings on Nov. 26 (the following week)?

**Comment by liyuqian** [comment]
Sure, moved the meeting.

**Comment by liyuqian** [comment]
Meeting update on 11/26/2019: Jonah has written https://github.com/flutter/flutter/pull/45568. That PR should be able to land soon. Before that, Terry could cherry-pick that PR and start working on this. We're expected to have some prototype that we can try out in 2 weeks! See Terry's [doc](https://docs.google.com/document/d/1sI7ASNI5V-b_dpqNq1djY-4c-PRBNQGF9flLoqTyWRU/edit?ts=5ddd77c4#heading=h.b4oo9c7fb362) for more details.

**Comment by liyuqian** [comment]
@terrylucas : any update?

**Comment by liyuqian** [comment]
CC @potatoker : this is one of our effort to improve the automated memory measurement tool.

**Comment by terrylucas** [comment]
The functionality has been added to DevTools see [PR](https://github.com/flutter/devtools/pull/1553)
- Collecting ADB memory statistics (Android only).
- Viewing ADB and Dart VM Heap statistics.
- Exporting the data to a JSON file.

Two switches have been added to DevTools CLI (server) see [PR](https://github.com/flutter/devtools/pull/1628)

The below command will launch a CLI that collects all memory profiling data and stores the data in the JSON file `~/Downloads/memory_log.json`:

_Enlisted in DevTools https://github.com/flutter/devtools.git</br>cd devtools/packages_

`> dart devtools/bin//devtools.dart  --vm-uri VM_Auth_URI --profile-memory fileName --verbose`

**VM_Auth_URI** - token displayed in flutter run e.g., `http://127.0.0.1:37141/m6a1twmdRpI=/`
**fileName** - file to store statistics e.g., `/usr/local/google/home/terry/Downloads/memory_log.json`

The format of the JSON file is:
```
{
   "samples": {
     "version": 1,
     "dartDevToolsScreen": "memory"
     "data": [
      {
        "timestamp":1581540967479,
        "rss":211419136,
        "capacity":50956576,
        "used":41384952,
        "external":166176,
        "gc":false,
        "adb_memoryInfo":{
          "Realtime":450147758,
          "Java Heap":7416,
          "Native Heap":41712,
          "Code":12644,
          "Stack":52,
          "Graphics":0,
          "Private Other":94420,
          "System":6178,
          "Total":162422
        }
      },
    ]
  }
}
```

**Comment by terrylucas** [comment]
Two files are required _packages/devtools/bin/devtools.dart_ and _packages/devtools/pubspec.yaml_

You can either jump to **1. Enlisted** section to enlist in the DevTools repository https://github.com/flutter/devtools.git or jump to **2. Minimum** to copy two files from the repository's master branch.

Any problems or changes you'd like ping me.
Also, have a Dart package available (devtools_shared) if you want to open and decode the JSON payload in Dart code.

Terry.


**1. Enlisted**
One time setup:
```
> mkdir ~/devtools
> cd ~/devtools
> git clone https://github.com/flutter/devtools.git
> cd packages/devtools
> pub get
```

Once enlisted/setup then this command will work:

`> dart ~/devtools/packages/devtools/bin/devtools.dart --vm-uri VM_URI --profile_memory JSON_FILENAME --verbose`

**VM_URI** observatory URL displayed when you run flutter run on the application you want to collect memory statistics on e.g.,

`> flutter run`
An Observatory debugger and profiler ... available at: **http://127.0.0.1:44417/gUQ8O3FVTJ4=/**

**JSON_FILENAME** path and name of the JSON file to store the memory statistics

**Note:** --verbose is optional it displays the timestamp of the collected sample as well as Dart Heap capacity,  ADB total memory and if a GC occured e.g.,

```
Collected Sample: [06:00:03.000] capacity=59861240, ADB MemoryInfo total=165960
Collected Sample: [06:00:03.000] capacity=62108944, ADB MemoryInfo total=165960 [GC]
Collected Sample: [06:00:04.000] capacity=83043880, ADB MemoryInfo total=193098
Collected Sample: [06:00:04.000] capacity=83043880, ADB MemoryInfo total=197894
Collected Sample: [06:00:04.000] capacity=91689440, ADB MemoryInfo total=197894 [GC]
```

**2. Minimum**
Copy two files packages/devtools/bin/devtools.dart and packages/devtools/pubspec.yaml from the master branch of DevTools github to a directory e.g.,

```
> mkdir ~./test_devtools
> cd ~/test_devtools
```

[packages/devtools/pubspec.yaml](https://raw.githubusercontent.com/flutter/devtools/master/packages/devtools/pubspec.yaml
)
Then right-click on the file's content and select "Save As ..." and save to your newly created directory.

[packages/devtools/bin/devtools.dart](https://raw.githubusercontent.com/flutter/devtools/master/packages/devtools/bin/devtools.dart)
Again, right-click on the file's content to save to your directory.

Then back your terminal session

[In directory ~/test_devtools one time setup]

`> pub get`

After that this command will work:

`> dart ~/test_devtools/dartdevtools.dart --vm-uri VM_URI --profile_memory JSON_FILENAME --verbose`

**VM_URI** observatory URL displayed when you run flutter run on the application you want to collect memory statistics on e.g.,

`> flutter run`
An Observatory debugger and profiler ... available at: **http://127.0.0.1:44417/gUQ8O3FVTJ4=/**


**JSON_FILENAME** path and name of the JSON file to store the memory statistics

**Note:** --verbose is optional it displays the timestamp of the collected sample as well as Dart Heap capacity,  ADB total memory and if a GC occured e.g.,

```
Collected Sample: [06:00:03.000] capacity=59861240, ADB MemoryInfo total=165960
Collected Sample: [06:00:03.000] capacity=62108944, ADB MemoryInfo total=165960 [GC]
Collected Sample: [06:00:04.000] capacity=83043880, ADB MemoryInfo total=193098
Collected Sample: [06:00:04.000] capacity=83043880, ADB MemoryInfo total=197894
Collected Sample: [06:00:04.000] capacity=91689440, ADB MemoryInfo total=197894 [GC]
```

**Comment by terrylucas** [comment]
Here's a [doc](https://docs.google.com/document/d/104Qa1nHL8Juhdx7hDw_2Qvcm5AislWJNvTSCCkRbZQ4/edit?usp=sharing) on how to use the command line DevTools to collect the memory statistics to a JSON file

**Comment by terrylucas** [comment]
Yuqian any news on using this tool?

**Comment by liyuqian** [comment]
I just shared this tool with @dnfield and we were discussing an experiment of "max memory" metric using this tool to see if our current granularity (1 data point / second, right?) is good enough. Will keep you posted on the progress.

**Comment by zanderso** [comment]
Re-opening for revert https://github.com/flutter/flutter/pull/56445

**Comment by zanderso** [comment]
@liyuqian What's the status of this issue?

**Comment by liyuqian** [comment]
https://github.com/flutter/flutter/pull/57340 and https://github.com/flutter/flutter/pull/57704 re-landed the perf test. Closing this issue.
