### ISSUE TITLE
[web] pointer_signal_resolver error

### ISSUE THREAD

**Issue by hhkk** [flutter/flutter#44037]
~/utd/a191020FlutterRecipe/recipes_app>flutter run -d chrome 
Launching lib/main.dart on Chrome in debug mode...
Building application for the web...                                14.1s
Attempting to connect to browser instance..                         4.5s

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
For a more detailed help message, press "h". To quit, press "q".
Debug service listening on ws://127.0.0.1:52386/EjKME3FVeJI=
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while dispatching a pointer event:
Assertion failed:
org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
_currentEvent == null || _currentEvent == event
is not true

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 194:49      throw_
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3        assertFailed
package:flutter/src/gestures/pointer_signal_resolver.dart 32:59                           register
package:flutter/src/widgets/scrollable.dart 549:55                                        [_receivedPointerSignal]
package:flutter/src/rendering/proxy_box.dart 2574:14                                      handleEvent
package:flutter/src/gestures/binding.dart 198:14                                          dispatchEvent
package:flutter/src/gestures/binding.dart 156:7                                           [_handlePointerEvent]
package:flutter/src/gestures/binding.dart 102:7                                           [_flushPointerEventQueue]
package:flutter/src/gestures/binding.dart 86:32                                           [_handlePointerDataPacket]
package:build_web_compilers/lib/_engine/engine/pointer_binding.dart 89:15                 [_onPointerData]
package:build_web_compilers/lib/_engine/engine/pointer_binding.dart 277:7                 <fn>
package:build_web_compilers/lib/_engine/engine/pointer_binding.dart 573:56                <fn>
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall

Event:
PointerScrollEvent#74f2a(position: Offset(554.0, 725.0), timeStamp: 0:00:17.357674, pointer: 0,
kind: mouse, device: -1, down: false, scrollDelta: Offset(12.0, 154.0))
Target:
RenderPointerListener#29574 relayoutBoundary=up6
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12

Application finished.
~/utd/a191020FlutterRecipe/recipes_app>

**Comment by Furqankhanzada** [comment]
@hhkk is it due to `CachedNetworkImage` ? cos i am facing same error on chrome and i think its due to `CachedNetworkImage` cos it's just showing loading not rendering image.

**Comment by iapicca** [comment]
Hi @hhkk 
can you please describe the issue in detail
and provide your `flutter doctor -v`
thank you

**Comment by rishisinghal** [comment]
Hi,

I am also facing the same issue in Flutter web when I am scrolling the page horizontally to the right and then back left. 

**Exception Raised**
````
════════ Exception caught by gesture library ═════════════════
The following assertion was thrown while dispatching a pointer event:
Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
_currentEvent == null || _currentEvent == event
is not true

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 194:49      throw_
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3        assertFailed
package:flutter/src/gestures/pointer_signal_resolver.dart 32:59                           register
package:flutter/src/widgets/scrollable.dart 549:55                                        [_receivedPointerSignal]
package:flutter/src/rendering/proxy_box.dart 2572:14                                      handleEvent
...
Event: PointerScrollEvent#c2a2e(position: Offset(939.0, 622.0), timeStamp: 0:00:56.391125, pointer: 0, kind: mouse, device: -1, down: false, scrollDelta: Offset(-3.0, 1.0))
  position: Offset(939.0, 622.0)
  scrollDelta: Offset(-3.0, 1.0)
Target: RenderPointerListener#a1f0b
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=531.8, h=799.0)
  size: Size(531.8, 799.0)
  behavior: deferToChild
  listeners: signal
````

**Sample Code**
````
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (BuildContext context, int index) {
                  return Container(
                      child: Column(
                    children: <Widget>[
                      SingleChildScrollView(
                        scrollDirection: Axis.horizontal,
                        child: _buildRowList(),
                      ),
                    ],
                  ));
                },
                childCount: 1,
              ),
            ),
````

**Flutter Doctor o/p **
````
$ flutter doctor -v
[✓] Flutter (Channel master, v1.10.15-pre.239, on Mac OS X 10.14.6 18G103, locale en-IN)
    • Flutter version 1.10.15-pre.239 at /Users/rishisinghal/work/flutter 2
    • Framework revision 598cdf2171 (12 days ago), 2019-10-24 12:17:06 -0400
    • Engine revision 2abf1101b4
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 081c01e89a)

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/rishisinghal/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/rishisinghal/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.6.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.87
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
````

**Comment by hhkk** [comment]
> Hi @hhkk
> can you please describe the issue in detail
> and provide your `flutter doctor -v`
> thank you

I'm afraid I don't know how to make the relevant parts of the project available but the whole project is here https://github.com/hhkk/191020recipes_app   I am just following the tutorial here 
https://medium.com/@michael.krol
and have made it to here
https://medium.com/@michael.krol/simple-recipes-app-made-in-flutter-list-view-283ef85f91e7
with some tweaks of my own that I think should be irrelevant to this problem. 

Thank you 
Henry

**Comment by hhkk** [comment]
sorry I keep hitting "close and comment" when I just mean "comment"

**Comment by gustavovitor** [comment]
Same issue here..

**Comment by khari998** [comment]
Im getting is exact same issue. No idea what is causing it.

**Comment by deisold** [comment]
I'm on master and getting the same error during scrolling when using a TextField with keyboardType = TextInputType.multiline.

Flutter 1.12.3-pre.48 • channel master • https://github.com/flutter/flutter.git
Framework • revision 802bd5514f (12 hours ago) • 2019-11-17 11:11:51 -0500
Engine • revision 4da0645df1
Tools • Dart 2.7.0

**Comment by khari998** [comment]
I have a TextField but my keyboard type is not set

**Comment by dheerajsarwaiya** [comment]
I was having the same issue but able to resolve it by doing two things
1st. Adding ScrollController
```
ScrollController _scrollController;

@override
  void initState() {
    super.initState();
    _scrollController = ScrollController();
}

```
2nd. Attaching the controller to ListView builder
```
 return ListView.builder(
      controller: _scrollController,
      itemCount: length,
      itemBuilder: (BuildContext context, int index) {
                 return MYWIDHTE();
}
```

**Comment by Skquark** [comment]
I'm stuck on this error too, with my web app crashing as I switch tabs and scroll with mouse, but it's oddly intermittent.  In my scenario, I've got my Slivers with a TabView, the Tab content is standard CustomScrollView with normal stuff inside (but not SliverList). On the Web debug, when you switch between tabs, it halts with that error message and usually continues working when resuming.  I cannot drag with the mouse to scroll or swipe either, thought that was supported on web.  That error also sometimes comes up when just scrolling down with mouse wheel, but doesn't halt then.
I could give more details if it helps, but seems like a general bug in the Web implementation since it works on mobile.  This issue is the last thing keeping me from deploying to website, hope there's an easy fix.. On the dev channel, btw.

**Comment by jonataslaw** [comment]
This error remain on 1.13.0.

**Comment by willvlad** [comment]
Having the same error. 
[✓] Flutter (Channel master, v1.13.2-pre.23, on Mac OS X 10.14.6 18G1012, locale en-GB)
    • Flutter version 1.13.2-pre.23 
    • Framework revision 7a7e2bb247 (4 days ago), 2019-12-12 17:03:01 -0800
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

**Comment by mamirix** [comment]
Having the same problem using SingleChildScrollView and ExpansionPanelList as a child.

flutter] flutter doctor -v
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale en-SA)
    • Flutter version 1.12.13+hotfix.6 at /Users/mea/dev/flutter/flutter
    • Framework revision 18cd7a3601 (2 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/mea/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
exit code 0

**Comment by dhakadv06** [comment]
Facing same issue

**Comment by advancedtw** [comment]
same problem but on `fde macos`. it happens for any scrollable widget. I have so far tried `SingleChildScrollView`, normal `ListView` and `ListView.builder`. the problem only happens when i reverse scroll the list.  so when the items are being displayed and i scroll following the main axis everything is fine when I back up then I get the assertion failed error.
@iapicca  ping

**Comment by mdebbar** [comment]
This is next on my queue after I'm done with https://github.com/flutter/flutter/issues/47440.

**Comment by mdebbar** [comment]
Update: opened a [PR](https://github.com/flutter/flutter/pull/48149) to fix this issue.

It turns out, this problem is not specific to web. It's more visible on web because that's where people commonly use wheel scrolling.
