### ISSUE TITLE
Codelab: Disclaimer for end of step 6, unable to run Firebase on iOS device

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4404]
Currently, and especially on the codelab branch, we're unable to make step 6 work on an iOS device.

We suggest adding a disclaimer to the codelab there that says something like "Known issue: unable to run on iOS device. Please use the iOS simulator to run this part of the codelab."

Blocked on https://github.com/flutter/flutter/issues/4226

**Comment by sethladd** [comment]
cc @qchong

**Comment by qchong** [comment]
Added a note in the codelab to indicate that there's a known issue where the code in unable to connect to Firebase on iOS devices. Refreshed codelab page is [here](https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..%2Findex#11).
