### ISSUE TITLE
DatePicker handles firstDate incorrectly, does not let respective day be selected

### ISSUE THREAD

**Issue by sceee** [flutter/flutter#44045]
## Steps to Reproduce
1. Set `myInitialDate` to a Date representing 2019-11-03 15:00:00.000
2. Set `earliestDateToBePicked to a Date representing 2019-11-02 14:41:20.807952
3. Set `latestDateToBePicked` to a Date representing 2019-11-03 23:59:59.000
4. Use a DatePicker that is set up with the following code
```
    final DateTime picked = await showDatePicker(
      context: context,
      initialDate: _myInitialDate,
      firstDate: earliestDateToBePicked,
      lastDate: latestDateToBePicked,
    );
```
5. Execute the code, opens the DatePicker
6. In the DatePicker (both on iOS and Android), todays day (Saturday, 2019-11-02) cannot be selected even though it is set as firstDate:
![Screenshot_20191102-124449](https://user-images.githubusercontent.com/11340487/68070469-05ae0a80-fd6f-11e9-9d4e-f7738186533a.png)

Additional information I noticed when playing around with other dates for the three input values:
If you set initialDate to the same value as firstDate (2019-11-02 14:41:20.807952), the DatePicker opens with todays date selected. But if you then select tomorrows day, todays day gets disabled immediately.

**Target Platform:** Android and iOS (Built on Windows / mac)
**Target OS version/browser:** It seems like all, definitely tested and reproduced on Android: 7, 9, iOS: 13
**Devices:** Many different, does occurr on simulator as well as on physical devices

## Logs

```
I did not want to attach all my logs (since there is a lot of custom loggin inside) but nothing is logged at this specific location when executing showDatePicker, therefore I did not attach logs.
```

```
Analyzing App...
No issues found! (ran in 51.8s)
```

```
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18362.418], locale de-DE)
    • Flutter version 1.9.1+hotfix.5 at O:\Tools\flutter
    • Framework revision 1aedbb1835 (2 weeks ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at O:\Libraries\androidsdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = O:\Libraries\androidsdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\.....\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • STH100 2 • 1163801706 • android-arm64 • Android 6.0.1 (API 23)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @sceee 
I believe it's possible you are referring to a 3rd party plugin,
if so please open an issue on the related github page.

If you are not referring to a 3rd party plugin,
could you please post a self contained app on github
or provide the steps to reproduce it.
Thank you

**Comment by sceee** [comment]
Hi @iapicca ,

I am referring to this Material library function: https://api.flutter.dev/flutter/material/showDatePicker.html

I just use it as explained above in the steps to reproduce (just set the dates accordingly).

Do you still need a self contained example app?

**Comment by iapicca** [comment]
Hi again @sceee 
I believe this [code ](https://gist.github.com/iapicca/b1f6b1ced820d21d2049e91f2bab9bb0)represent the situation you described.
thank you for the clarification

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by darrenaustin** [comment]
This looks like a problem with the `firstDate` having a time associated with it. The previous Date Picker would just compare these parameters with the grid values which don't have a time of 0:00:00. When that is compared to `firstDate` with a non-zero time it will be before the first date and wont' let you select it. 

There was a recent redesign of the Material Date Picker. It ignores the times when comparing the dates, so it should fix this problem. See #50546 for more details.
