### ISSUE TITLE
image Url preview form widget i need.

### ISSUE THREAD

**Issue by wikiworld** [flutter/flutter#44044]
![주석 2019-11-02 204118](https://user-images.githubusercontent.com/52195693/68070575-9f97a680-fdb3-11e9-96e1-423f44a756e6.png)
image Url preview form  widget i need.

**Comment by iapicca** [comment]
Hi @wikiworld 
can you please describe the issue in detail
and provide your `flutter doctor -v`.
Please refrain 
from posting pictures if not necessary.
thank you

**Comment by wikiworld** [comment]
> Hi @wikiworld
> can you please describe the issue in detail
> and provide your `flutter doctor -v`.
> Please refrain
> from posting pictures if not necessary.
> thank you

hard to manage with form widget about Url preview

**Comment by iapicca** [comment]
Hi again @wikiworld 
can you please describe the issue
thank you
