### ISSUE TITLE
flutter download should not include .pub-cache

### ISSUE THREAD

**Issue by JAicewizard** [flutter/flutter#44062]
## Use case

The .pub-cache should be located in ~/.pub-cache (or macos/windows equivalent) not in {instal_dir}/.pub-cache according to [`the documentation`](https://dart.dev/tools/pub/cmd/pub-cache) for pub.

## Proposal
Remove ./.pub-cache from the installed package, also considder removing other caches since 1) they should be in the user directory and 2) they shouldnt be in the installed package. According to  the [install-guide](https://flutter.dev/docs/get-started/install/linux) they should be downloaded afterwards and only if needed.

**Comment by Sameerkash** [comment]
@TahaTesser  I would like to work on this, can I please get some guidance?

**Comment by goderbauer** [comment]
We include the pub cache in the download like that to make sure everything works out of the box without the need to download more stuff on first run.
