### ISSUE TITLE
Flutter Google Map Crashes on first open in IOS

### ISSUE THREAD

**Issue by abumoallim** [flutter/flutter#44064]
I have a google map on the very first page of my application after the splash screen. When I run the app for the first time and a very new build, it crashes with this error on IOS: PlatformException(create_failed, can't create a view on a headless engine, null).

This is my google Map code and the crash happens only in IOS for the first time when the app is installed.

``GoogleMap(
            myLocationEnabled: false,
            myLocationButtonEnabled: false,
            zoomGesturesEnabled: true,
            scrollGesturesEnabled: true,
            rotateGesturesEnabled: false,
            tiltGesturesEnabled: false,
            onMapCreated: _onMapCreated,
            initialCameraPosition: CameraPosition(
              target: _location,
              zoom: 12,
              /* tilt: 50.0,
                      bearing: 45.0,*/
            ),
            mapType: _currentMapType,
            markers: Set<Marker>.of(markers.values),
            onCameraMove: _onCameraMove,
            onCameraIdle: _onCameraIdle,
          )``

I am following up on this issue on GitHub : https://github.com/flutter/flutter/issues/36310 but it is not having a proper solution. Can anyone please help me with this?

**Comment by iapicca** [comment]
Hi @abumoallim 
can you please provide your `flutter doctor -v` 
and `flutter build --verbose`,
also to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
