### ISSUE TITLE
If SelectableText set a height value,Text will scroll when crossing the border

### ISSUE THREAD

**Issue by rs5173** [flutter/flutter#44069]
For example

```
SelectableText(
      "SelectableText",
       style: TextStyle(
       fontSize: 16,
             height: 2,
      ),
),

```

It's a bug or a feature?

**Comment by iapicca** [comment]
Hi @rs5173 
I'm quite sure that the behavior you are describing is a bug 
or it's even related to the height parameter.
Does this [code ](https://gist.github.com/iapicca/b6f8dd25f9fcd7dcfef690ba540702d7)represent the situation you are describing?
Thank you

**Comment by rs5173** [comment]
Yes.This bug will happen when the height value is greater than the default value.

**Comment by rs5173** [comment]
Flutter version is v1.9.1+hotfix.2

**Comment by iapicca** [comment]
Hi again @rs5173 
as mentioned before the behavior you are describing matches the definition of  [SelectableText](https://api.flutter.dev/flutter/material/SelectableText-class.html) 
```
The SelectableText widget displays a string of text with a single style. 
The string might break across multiple lines 
or might all be displayed on the same line depending on the layout constraints.
```
If you are proposing an implementation of a different behavior
could you please can you please explain in details.
Thank you

**Comment by HansMuller** [comment]
CC @chunhtai

**Comment by Hixie** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
