### ISSUE TITLE
a11y focus problem with DropdownMenuItems and BottomNavigationBar

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#44077]
Internal: b/143551289

With a widget tree like:

```
Scaffold
  Navigator --> DropdownButton ...
  BottomNavigationBar
```

Open the dropdown's popup and navigate between the DropdownMenuItems.

Expected behavior: Screenreader linear navigation should take you between the DropdownMenuItems only. You should not be able to escape the popup while it is open (except maybe for the dismiss background area).

Actual behavior: The BottomNavigationBar items are reachable while the popup is open. It's like it treats the BottomNavigationBarItems as being in the same navigation plane(?) as DropdownMenuItems.

Issue is present on both iOS and Android.

Repro case:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String value = 'foo';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Navigator(
          onGenerateRoute: (_) => MaterialPageRoute(builder: bodyBuilder),
        ),
        bottomNavigationBar: SafeArea(
            child: BottomNavigationBar(
          items: ['1', '2', '3']
              .map((item) => BottomNavigationBarItem(
                  icon: Icon(Icons.home), title: Text(item)))
              .toList(),
        )),
      ),
    );
  }

  Widget bodyBuilder(BuildContext context) => SafeArea(
        child: Center(
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              DropdownButton(
                value: value,
                items: [
                  DropdownMenuItem(
                    value: 'foo',
                    child: Text('Foo'),
                  ),
                  DropdownMenuItem(
                    value: 'bar',
                    child: Text('Bar'),
                  ),
                  DropdownMenuItem(
                    value: 'baz',
                    child: Text('Baz'),
                  ),
                ],
                onChanged: (String value) {
                  setState(() {
                    this.value = value;
                  });
                },
              ),
              MaterialButton(
                child: Text('Reset'),
                onPressed: () {
                  setState(() {
                    this.value = 'foo';
                  });
                },
              ),
            ],
          ),
        ),
      );
}

```

**Comment by rymotion** [comment]
@mehmetf The possible issue here is that technically `BottomNavigationBar` and the dropdown menu are on the same route and looking into line 929 in `dropdown.dart` the issue is that we are essentially inserting a Semantics widgets into the widget tree meaning that the your menu and its children are now in the tree with your bottom `NavigationBar` what you need to do is remove that bottom `NavigationBar` from the Semantic tree changing your example to something more suitable. Possibly like an earlier issue (I'll add the link if I can find it on my end) swap out the Scaffold for a Stack

**Comment by darshankawar** [comment]
Issue is replicable on latest dev channel. With accessibility ON and when dropdown menu items are displayed, slide to navigate between menu items which takes control to bottom navigation bar items after last menu item.

![44077](https://user-images.githubusercontent.com/67046386/87142857-c8692780-c2c2-11ea-9546-6c774302b5ec.png)
