### ISSUE TITLE
What is the issue in having native flutter map widget ?

### ISSUE THREAD

**Issue by dgandhi17** [flutter/flutter#44073]
## Use case
Native flutter widget for google map

## Proposal
Rather than creating plugin and fixing hundreds bugs for both iOS and Android platforms and modifying API's as an when android's or iOS map api changes. It will be better to create native flutter widget. it should take the same time it takes to create plugin and have bugs and fixes

**Comment by igoriuz** [comment]
I think they're already started with writing the maps sdk to native dart code: https://issuetracker.google.com/issues/140415468

**Comment by dgandhi17** [comment]
@igoriuz  I saw the comments looks like that is js interlop for web google map, here I am suggesting flutter map widget like Text, Button etc... UI controls

**Comment by stuartmorgan** [comment]
Building and maintaining an entire from-scratch copy of the Google Maps SDK is out of scope for the Flutter project. I suggest anyone interested in such an SDK file that as a request with the Google Maps team, as they would be the right group for such a project.
