### ISSUE TITLE
CupertinoSliverRefreshControl overlaps the system bar

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#44078]
Internal: b/143582720

CupertinoSliverRefreshControl doesn't use a SafeArea widget, and overlaps the system bar on iPhone X (and by 4px on iPhone 7).

Using SliverSafeArea causes the refresh control not to appear at all when pulling down.
This can be reproduced by updating the demo to remove CupertinoNavigationBar, and wrap the CupertinoSliverRefreshControl in a SliverSafeArea.

**Comment by LongCatIsLooong** [comment]
That sounds like a unusual use case. Could you put the `Scrollable` in a `SafeArea` instead?

**Comment by xster** [comment]
No longer reproducible and it seems to work as desired.
