### ISSUE TITLE
[ANDROID-X] Update Gradle and Kotlin version !!

### ISSUE THREAD

**Issue by RsPlayer** [flutter/flutter#44074]
Why does flutter still uses an outdated Gradle and kotlin version for AndroidX template? It doesn't work anymore  with firebase and many other services now.

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/28805

**Comment by jmagman** [comment]
\cc @blasten

**Comment by blasten** [comment]
The tool uses the latest Kotlin version `1.3.50` and Gradle `5.6.2` released on Sep 2019.   Maybe you are using an old version of Flutter?

**Comment by RsPlayer** [comment]
I just did `flutter upgrade`  and created new project, still `ext.kotlin_version = '1.2.71'`

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by RsPlayer** [comment]
@blasten its seems that you're talking about the `master` channel. I use the `stable` version.
https://github.com/flutter/flutter/blob/stable/packages/flutter_tools/templates/app/android-kotlin.tmpl/build.gradle, I think it hasn't bee merged yet to stable.

**Comment by RsPlayer** [comment]
fixed by setting
`ext.kotlin_version = '1.3.50'`
`classpath 'com.android.tools.build:gradle:3.3.2'`

and `minSdkVersion 21`
