### ISSUE TITLE
Pesto: Scrolling the app bar should smoothly scale the logo

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4407]
On iOS and Android, as I scroll the list of recipes in pesto, I see the app bar's logo image move and then pop from logo+title to just logo.

We should look for a way to smoothly scale the logo+title as the user scrolls. A good example of smoothly scaling would be the "Flutter gallery" title on the home screen of the gallery.

To see the scaling in action, see https://polymerelements.github.io/app-layout/templates/pesto/#/home and narrow your browser window. Then, scroll up and down. You'll see the pesto logo scaling in and out as the list of recipes is scrolled up and down.

**Comment by sethladd** [comment]
cc @mpcomplete

**Comment by Hixie** [comment]
I filed this as https://github.com/flutter/flutter/issues/4377 the other day but yours is better.

**Comment by sethladd** [comment]
Ah, thanks for de-duping!

**Comment by sethladd** [comment]
I noticed that in the latest builds, there's still a snapping resize with the logo when it transitions from logo+wordmark to just logo.

**Comment by sethladd** [comment]
Just tried a new build of Pesto and we're still seeing the janking logo and we scroll up and down. It's almost like it's popping into various sizes. Like some sort of quantum electron levels, it can only be in well-defined states, not in-between :)
