### ISSUE TITLE
Mixing in DiagnosticableMixin doesn't mean you implement Diagnosticable

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#44088]
The docs say "A mixin class that provides the implementation for Diagnosticable.", which makes it sound like if you mix it in to your class, you now implement Diagnosticable. However, this doesn't seem to be the case. Maybe we should say it's a mixin "on Diagnosticable"?

cc @jacob314

**Comment by goderbauer** [comment]
The mixin was removed in https://github.com/flutter/flutter/pull/58635. Closing.
