### ISSUE TITLE
Your administrator requires you to set a passcode on this device to access this account. Please set a passcode and try again.

### ISSUE THREAD

**Issue by MunishThakur** [flutter/flutter#44081]
Using flutter code when I tries to login via Google Sign in on my iOS device, I get following error:

> Your administrator requires you to set a passcode on this device to access this account. Please set a passcode and try again.

While on other apps it does not mandate to have passcode on iphone for logging using google

[More Detail here with snapshot](https://stackoverflow.com/questions/58661676/flutter-ios-app-needs-passcode-for-google-sign-in)

**Comment by iapicca** [comment]
Hi @MunishThakur 
you have done correctly asking this question on StackOverflow.
This platform is not met for assistance on personal code.
Please see https://flutter.dev/community for resources for asking questions like this
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by MunishThakur** [comment]
I believe this is flutter [package google_sign_in](https://pub.dev/packages/google_sign_in) issue, I tried Google signin using swift native code and it worked while the same email giving me passcode error.

Something is definitely wrong here.
