### ISSUE TITLE
Flutter not creating the local.properties file on any package's android/ folder.

### ISSUE THREAD

**Issue by mocomaco** [flutter/flutter#44092]
## Steps to Reproduce

Runing packages get goes without any problem, but when building the application for release
with flutter build apk, I get the error:

> FAILURE: Build failed with an exception.
> * What went wrong:
> A problem occurred configuring root project '<package_name>'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

This gets fixed by manually adding the local.properties file with the path to the android  sdk and flutter sdk, but this wasn't necessary before. And I need to do this with every package in the folder pub.dartlang.org.

 I just updated to the version v1.10.15-pre.384, so maybe it is related to the update.

My android sdk is correctly installed and flutter is set up with it.

I also tried flutter packages pub cache repair with no luck.

**Comment by mocomaco** [comment]
I switched to stable and everything works fine now.

**Comment by iapicca** [comment]
Hi @mocomaco 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by mflesh1** [comment]
I am also receiving a similar error when running:

`flutter build apk --no-shrink  --target-platform android-arm`

The error is:

```
* What went wrong:
A problem occurred configuring root project 'firebase_analytics'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/mflesh1/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-5.0.11/android/local.properties'.
```
Flutter version info:
```
Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (3 weeks ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2
```

My android sdk is correctly installed and flutter is set up with it.
