### ISSUE TITLE
Pesto: Scrolling a recipe up should also move the menu icons up

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4410]
Open gallery, then pesto, then tap a recipe (e.g. bacon sprouts). Scroll the recipe up, to hide the image.

Expected: the menu icons and shadow are moved off the screen. When the user pulls down just a little bit, an opaque menu bar appears. A great example of this is the Google Play Movies app. Tap into a specific movie from your library, and slowly scroll up and down.

Actual: The menu items, and shadow, are still visible and over the recipe text.

![e21c5cc3-90a7-4b39-be61-1f03ccb52694](https://cloud.githubusercontent.com/assets/5479/15841403/f222ccd2-2c05-11e6-8d10-03b1aa6269ed.PNG)

**Comment by eseidelGoogle** [comment]
Note in the image, the problems are the gap at the top of the shadow region as well as the gradient on the sides.

**Comment by sethladd** [comment]
Looks pretty good!

* No more shadow
* We move the back and dot icons up when the menu contents are scrolled up
