### ISSUE TITLE
Add TextField color to TextTheme 

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#44100]
There does not seem to exist a working solution for TextField styling globally via app theme.
TextField uses the subhead style for its text but so do some other widgets (specifically Text's).
I would like to see a separate color theme option for TextFields only.

![Screenshot_20191104-131554](https://user-images.githubusercontent.com/1481807/68117173-42136f00-ff05-11e9-8f69-3b0e8d2997bc.png)

**Comment by Hixie** [comment]
In general this is driven from the guidelines of the material design spec. We're a bit reluctant to diverge too much from that spec, because then it becomes harder for us to maintain and harder to explain how material maps to Flutter's library.
