### ISSUE TITLE
Getting "Cannot find a class with the main method." in VSCode when clicking Debug > Start debugging

### ISSUE THREAD

**Issue by JosephG3001** [flutter/flutter#44103]
I'm suddenly receiving the error "Cannot find a class with the main method." in visual studio code when trying to debug my flutter app.  It's been working fine for weeks and nothing has changed apart from installing regular updates to Visual Studio code.  The error states it's from "Debugger for Java extension".

![image](https://user-images.githubusercontent.com/18268304/68120107-746c9e80-fefc-11e9-91f8-47f966463ba8.png)

Any ideas how to resolve?

**Comment by iapicca** [comment]
Hi @JosephG3001 
can you please provide 
a self contained app on github
or the steps to reproduce it.
Also your flutter doctor is not entirely readable,
can you post it again?
Please refrain from posting pictures if not necessary.
Thank you

**Comment by JosephG3001** [comment]
Looks like clicking debug > start debugging in VSCode's main menu causes this error, however; I can right click the main.dart file itself and click debug from there.  Not sure why doing it from the main menu bar suddenly stopped working for me.

Closing the issue.

**Comment by corymalcolmtaylor** [comment]
I   get the same problem trying to run the code in this tutorial: https://flutter.dev/docs/development/platform-integration/platform-channels#example-java
The git repo is here: https://github.com/flutter/flutter/tree/master/examples/platform_channel
flutter doctor -v 
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-CA)
    • Flutter version 1.9.1+hotfix.6 at /Volumes/macex/flutter
    • Framework revision 68587a0916 (8 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Volumes/macex/androidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by jvmonjo** [comment]
In case someone else is facing this issue, I fix it by deleting this file:

```
.vscode/launch.json
```

**Comment by Calvin-Ho** [comment]
> 
> 
> In case someone else is facing this issue, I fix it by deleting this file:
> 
> ```
> .vscode/launch.json
> ```

Thank you, this solved my problem!

**Comment by jbcarta** [comment]
Thank you!! solve my problem too!!

**Comment by Tarxan-jpg** [comment]
> In case someone else is facing this issue, I fix it by deleting this file:
> 
> ```
> .vscode/launch.json
> ```

Where can I find this file? I'm new to Java

**Comment by ThinhTesting** [comment]
i can't find this file, where can i find

**Comment by corymalcolmtaylor** [comment]
In the root of your VS Code project.  On some systems .vscode is a hidden folder.
