### ISSUE TITLE
Flutter can't detect iPhone 

### ISSUE THREAD

**Issue by eswarvarma-dev** [flutter/flutter#44105]
Flutter can't detect iPhone 6s,iPhones 6s Plus in iMac. but it is connecting to Xcode

**Comment by iapicca** [comment]
Hi @eswarvarma-dev 
can you please provide your `flutter doctor -v`?
Thank you

**Comment by eswarvarma-dev** [comment]
i have downgrade my system from catalina to mojave its working fine now. Thank you for your response.

**Comment by iapicca** [comment]
Hi again @eswarvarma-dev 
I'm glad to hear that you solved it
thank you for letting me know

**Comment by eswarvarma-dev** [comment]
ok thank you.

**Comment by eswarvarma-dev** [comment]
but for catalina doesn't support
