### ISSUE TITLE
Pesto: scrolling the main recipes list is < 60fps

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4411]
On Android and iOS, built with `--release`.

![screenshot_20160606-172201](https://cloud.githubusercontent.com/assets/5479/15842201/d12b398c-2c0b-11e6-980e-0034b4285cbe.png)

![d47e9030-57c5-4ba6-8ef5-8744e8a1bd60](https://cloud.githubusercontent.com/assets/5479/15842203/d81e3b22-2c0b-11e6-9737-67a6a700d0aa.PNG)

**Comment by sethladd** [comment]
cc @abarth

**Comment by abarth** [comment]
```dart
        body: new Block(
          padding: new EdgeInsets.only(top: _kAppBarHeight + statusBarHeight),
          children: <Widget>[
            new Padding(
              padding: const EdgeInsets.all(8.0),
              child: new MaxTileWidthGrid(
                maxTileWidth: 500.0,
                children: recipes.map(
```

This should probably be a `ScrollableGrid`.

**Comment by abarth** [comment]
Looks like `ScrollableGrid` is missing padding, which is needed here.

**Comment by sethladd** [comment]
cc @mpcomplete

**Comment by abarth** [comment]
I believe I made this go fast.
