### ISSUE TITLE
[web] what are differences between flutter run and simple http server of web build

### ISSUE THREAD

**Issue by jdeltoft** [flutter/flutter#44111]
I'm currently developing a flutter UI for a touch panel, and the app works great if I use "flutter run -d chrome".  If I run it though from a simple http server I get what look like minification lookup failures?  Here is how I'm starting a simple server:

`python3 -m http.server 8000
`
from the 'build/web' path.  Here is how I'm doing the web build:

`flutter build web`

when I run it this way, I get a failure like this:

![image](https://user-images.githubusercontent.com/4506303/68133940-f0f48280-fee6-11e9-9467-88433a2ed5b4.png)

So my first question is, why would running this with "flutter run -d chrome" work better?  What's different about the build that way?

My next question, is there some better way to get failure logs from a web UI?  From the console I see this:

![image](https://user-images.githubusercontent.com/4506303/68134039-1f725d80-fee7-11e9-838d-4077ef004cfe.png)

Here is my flutter info:

```
JustinMac:audacy_on_tap jeltoft$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.10.15-pre.352, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.10.15-pre.352 at /Users/jeltoft/flutter/flutter
    • Framework revision 01d55074af (4 days ago), 2019-10-31 10:10:25 -0500
    • Engine revision b16eab6aff
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 d50c158d42)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jeltoft/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.70
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by jonahwilliams** [comment]
By default `flutter run` builds in debug mode, while `flutter build` runs in release mode. It looks like your app probably has a bug in it - if you run in release mode `flutter run --release/--profile` you should be able to see what is crashing with source maps.

**Comment by jdeltoft** [comment]
Ok, thanks for the info.  Sure enough, if I run in --release or --profile modes I get the crash.

So with "flutter run --profile -d chrome" I get this:

![image](https://user-images.githubusercontent.com/4506303/68160144-b73c6f80-ff18-11e9-9e1b-49bdf298d0ba.png)

let me see if anyone else has seen this.   One thing I would mention is that this same code base worked up to the point of 1.10.2.  I think 1.10.3 was the first time it started failing.

**Comment by jonahwilliams** [comment]
Is there a console stacktrace with more information?

**Comment by jdeltoft** [comment]
Ah, found it.  Thanks for the help.  So my issue is with using plugins (again).  What confused me in this case though.  Why does it run in debug mode but not release mode?  

https://pub.dev/packages/percent_indicator

This was the current cause of my issues.  I've already implemented this in a static non animated stack way of containers to show the progress bar.  But I'm also thinking there is one more plugin later in my app killing me (carousel) which will be harder to work around.  

Any idea why these run in debug mode?

**Comment by jonahwilliams** [comment]
I'm not familiar with the plugin so I can't say. Is there more of a stack trace in the console that we could look at?

**Comment by jdeltoft** [comment]
@jonahwilliams Thanks for asking.  So the plot thickens here a bit.  I'm sorry to have suspected that plugin a bit blindly.  What it looks like is this.  When I was using that plugin, I was using some Inherited Widget "getters" from my main.dart.  By removing my calls in a few places to the percent indicator plugin (I was using it as a progress bar in my setup screens) I *ALSO* removed a few calls to using inherited data.  

So, my true issue is this I think:

* I can run in --debug mode for some odd reason
* when I run in --profile or --release, I get this error you see above
* my app is now crashing at a screen further down the line but that's how I learned it's because of use of inherited widget data through a "getter"

Here is the failure console for another example of this same overall failure:

![image](https://user-images.githubusercontent.com/4506303/68207784-5010d080-ff95-11e9-841c-366d62781a61.png)

Here is are some code snippets that show how I'm using inherited widget data:

![image](https://user-images.githubusercontent.com/4506303/68207881-9108e500-ff95-11e9-8bbd-da07d5ee4b4d.png)

and then to get this failure (again, ONLY in release/profile mode) the code does this:

![image](https://user-images.githubusercontent.com/4506303/68207958-bdbcfc80-ff95-11e9-9e7d-c59454be476e.png)

So my first question is why does this work in --debug mode?  And then I'm wondering, am I using inherited widget incorrectly somehow?  SessionInfo() in the above case is being placed at the root of my main app like this:

![image](https://user-images.githubusercontent.com/4506303/68208100-0d032d00-ff96-11e9-99ed-9b4354e23254.png)

I started using this paradigm for my data when I watched this video many months ago and it's been working very well for me in apps.  

https://www.youtube.com/watch?v=Zbm3hjPjQMk

@iapicca thanks for marking this 
@filiph thanks for the youtube!  Love your videos!!!

**Comment by jdeltoft** [comment]
One other clue to mention again here.  From my colleague's testing, this did not fail until flutter 1.10.3.  with 1.10.2 down to 1.9.x this same code base worked I believe.

**Comment by jdeltoft** [comment]
I'll try to make a very simple example today some time that demonstrates this failure with just one or two dart files.  If it's just any time you use inherited then this shouldn't be hard

**Comment by jdeltoft** [comment]
Ok, I've narrowed down to where the issue is a bit more.  The issue appears to be when I use inherited widgets in a util.dart file that's in a sub directory such as util/util.dart.  If I move the exact same util function into main.dart, then it works.  It also works if I make a util.dart at the main level instead of one level down.

Attached are the simplest files I could make to recreate this failure.

- lib/pagetwo.dart
- lib/main.dart
- lib/launchpad.dart
- lib/util/util.dart
- pubspec.yaml

This is in a zip file and you should be able to reproduce the failure then by putting this in an example flutter app, doing the "flutter create ." to build web. And then use:

`flutter run --profile -d chrome
`

This failure is caused by the use of this function in util/util.dart:

![image](https://user-images.githubusercontent.com/4506303/68395908-3e1a6380-0136-11ea-8bdf-99d27d35a7ac.png)

and if I move that util function completely as is into main.dart then I do not get the crash anymore.  

This is the console log of the crash you should see:

![image](https://user-images.githubusercontent.com/4506303/68396036-77eb6a00-0136-11ea-8c9a-1c5d34692616.png)

So is this failure somehow a minification issue with path names and dart files being in sub directories??  

[simple_failure_reproduction.tar.gz](https://github.com/flutter/flutter/files/3820037/simple_failure_reproduction.tar.gz)

**Comment by jdeltoft** [comment]
@jonahwilliams @iapicca Just FYI, I updated this with a very simple example for you to reproduce the failure on your setup.

**Comment by jdeltoft** [comment]
@jonahwilliams Here is a screen shot of my full (non stripped down as above) app failing.  Again, it failing at the time of using inherited data from main.dart.  What's crazy still, it worked in 1.10.2, it works in debug mode and if I run on any AVD or real hardware, but it just fails here in flutter web release mode.  

![image](https://user-images.githubusercontent.com/4506303/68422350-a5034100-0165-11ea-8acb-b4d9ff6cf281.png)

The other crazy thing is that I seem to have no issue accessing the same inherited data (SessionInfo.of(context)) from the parent "screen" (stateful widget) above the one that crashes.  So I found I can pass it down to this screen as a parameter!

**Comment by jdeltoft** [comment]
So back to the original question, what's the difference between:

`flutter run --profile -d chrome
`
and 

`flutter run --debug -d chrome
`
The first one fails, the second one doesn't.  And I looked at main.dart.js and it's 100% identical in both cases.  

Attached here is the main.dart.js file that calls to 

`C.JSNull_methods.get$data(H.interceptedTypeCast(context.inheritFromWidgetOfExactType$1(C.Type__TapInfo_G37), "$is_TapInfo0"));
`
[main.dart.js.zip](https://github.com/flutter/flutter/files/3821778/main.dart.js.zip)

**Comment by jdeltoft** [comment]
Ok, narrowing in, reviewing the generated js code. The first commit id (plus or minus 3) I see that failed is e045ef29691ea9f2ef3eafe3176f8d1da8a3a5fa.  

This one passed: 7fb085ee04f87a527634ed2da8c7d2909eb2d209

**Comment by vsmenon** [comment]
@jdeltoft - with `--debug` it's using a very different compilation path.  Note, the actual file might have a different name.  You can look at what's loaded in the browser.

@sigmundch - any ideas?

**Comment by jdeltoft** [comment]
@jonahwilliams Just FYI, this was the first commit that fails for me.  

b2f38396f41cac707284c46d1ade7ae650fb3cad

Looks like it was reverted once and relanded here?  Any ideas if this was a major shift that could cause my problems? I haven't looked into the changes yet.

**Comment by sigmundch** [comment]
mmm - no ideas on my end, yet. As @yjbanov mentions, it appears that dart2js believes some values to always be null, so it generates those calls like `JSNull_methods.*`.

@jdeltoft one clue that might be useful to look into is how does the main.dart.js contents differ before and after b2f3839 - maybe that would clue us into whether dart2js is getting the same input or if some flags are different somehow.

**Comment by expl0r3rgu1** [comment]
I have the same exact problem here. When running in debug mode everything works fine. When I run it hosting the page or anything you already did it says there is no function called: 
`get$data`

**Comment by yjbanov** [comment]
@vsmenon @sigmundch I'm labeling this as a Dart issue if you don't mind. As of right now I can see two possibilities:

* There's a bug in the compiler: in this case the fix is also in the compiler
* The bug is in the Dart code: in this case the stack trace should be better (e.g. if it's NSM due to `null` the message should say exactly what's `null`), i.e. the fix is still in the compiler

**Comment by jdeltoft** [comment]
> @vsmenon @sigmundch I'm labeling this as a Dart issue if you don't mind. As of right now I can see two possibilities:
> 
> * There's a bug in the compiler: in this case the fix is also in the compiler
> * The bug is in the Dart code: in this case the stack trace should be better (e.g. if it's NSM due to `null` the message should say exactly what's `null`), i.e. the fix is still in the compiler

Thanks for the update.  Just as a reminder I point to the exact dart2js update from a flutter commit above and also have a simple flutter program with just two files that shows the failure.

**Comment by jonahwilliams** [comment]
This is probably related to 04 optimizations, turning them down might reveal a better error message

**Comment by vsmenon** [comment]
@jdeltoft - would you mind sharing the Dart code for `buildLightRow` in your screenshot example?

It does appear that the compiler believes you're indexing into a list (or similar collection) that is always null.  Note, one difference between debug and non-debug modes is that the former runs asserts and the latter doesn't.  So, you would see that exact error - release mode only - if you had something like:

```dart
void main() {
  List l;
  assert(() {
    l = [ 'hello' ];
  }());
  print(l[0]);
}
```

**Comment by yjbanov** [comment]
@vsmenon is there a way to disable assertions in DDC? Our tools should support debugging such errors in user code. Perhaps we should offer this mode in debug builds.

**Comment by vsmenon** [comment]
```
@vsmenon is there a way to disable assertions in DDC? Our tools should support debugging such errors in user code. Perhaps we should offer this mode in debug builds.
```

I don't think so.  You can open a request on Dart.  

That said, should also try this at default optimization level (O1) in Dart2JS.

**Comment by jonahwilliams** [comment]
@yjbanov could you open a PR to expose the optimization level as a command line flag? Its currently defined here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_system/targets/web.dart#L27

**Comment by jdeltoft** [comment]
> @jdeltoft - would you mind sharing the Dart code for `buildLightRow` in your screenshot example?
> 
> It does appear that the compiler believes you're indexing into a list (or similar collection) that is always null. Note, one difference between debug and non-debug modes is that the former runs asserts and the latter doesn't. So, you would see that exact error - release mode only - if you had something like:
> 
> ```dart
> void main() {
>   List l;
>   assert(() {
>     l = [ 'hello' ];
>   }());
>   print(l[0]);
> }
> ```

@vsmenon  Sure!  Thanks for asking.  Here is that function.  The SessionInfo.of() is my use of inherited widgets in main.  This has been how I've been dealing with data I want to be shared across the app's pages.  Not sure if you saw the zip I attached.  It reproduces this issue and shows all the details of how I was using inherited widgets.  

![image](https://user-images.githubusercontent.com/4506303/69448450-2ccc7c00-0d1e-11ea-9c12-b52cc744c562.png)

**Comment by jdeltoft** [comment]
Just a heads up, I just upgraded to the latest flutter, and retested.  Issue is still there, but now the "red screen of death" is just a blank white screen?  I ran with "flutter run -d chrome --profile" 

![image](https://user-images.githubusercontent.com/4506303/69448954-53d77d80-0d1f-11ea-96ba-307195e83b3c.png)

![image](https://user-images.githubusercontent.com/4506303/69448989-66ea4d80-0d1f-11ea-8823-9b8f71d8d023.png)

**Comment by jdeltoft** [comment]
@vsmenon @yjbanov Hi, is there a way for me to use the latest dart2js with optimizations turned lower?  Then I could see if there was a particular level that creates the failure?  

Is there any other help I can give here?  I have shared the full source (2 files) to reproduce the failure 100% above, not sure what more I can do.

**Comment by sigmundch** [comment]
I took a deeper look and it appears the issue here is the same as #44600 

It appears that there are some libraries imported by two different URIs: a relative import and a package import. When a file is imported via different URIs, we are required to treat them as separate libraries. So code like this gives surprising answers:

```dart
import 'package:foo/a.dart' as a1;
import 'a.dart' as a2; // same file as above

main() {
 print(a1.A() is a2.A); // prints false;
}
```

The code that is producing errors is code that contains casts like `as _TapInfo`, which then dart2js optimizes because it knows the cast will fail.

Because of common patterns of how flutter main lives in `lib/`, all of our tools have logic to convert `lib/main.dart` into `package:my_package/main.dart`. I wonder if that broke during b2f3839 

@jonahwilliams - I am hoping that your fix for the other issue will also address this one.

**Comment by jdeltoft** [comment]
@jonahwilliams Unfortunately, this is still crashing for me.  I just upgraded to the latest master flutter and I get this with the demo files I attached on this issue above.  I'll attach them here again:

![image](https://user-images.githubusercontent.com/4506303/70177929-e45b7980-16a0-11ea-9fb3-15eae7f06ab1.png)

![image](https://user-images.githubusercontent.com/4506303/70177962-f89f7680-16a0-11ea-8a4f-6c3eae31f27e.png)

**Comment by jdeltoft** [comment]
Here's that same tar file with the lib/ folder (4 dart files total).  Let me know if I can somehow change the way I do my imports to work around this?

[simple_failure_reproduction.tar.gz](https://github.com/flutter/flutter/files/3923794/simple_failure_reproduction.tar.gz)

Here is where I am in flutter:

![image](https://user-images.githubusercontent.com/4506303/70178404-d8bc8280-16a1-11ea-9607-f469dcd5cbc4.png)

**Comment by jdeltoft** [comment]
@jonahwilliams let me know if I should make a new issue or do you re-open this one?

**Comment by sigmundch** [comment]
@jdeltoft - when I was playing with your example earlier, I was able to work around the issue by changing the imports as follows:
* rename `main.dart` to `main2.dart`
* create `main.dart` that only has these contents:
```dart
export 'package:my_package/main2.dart';
```
* change all other relative imports from `main.dart` to `main2.dart`.

Basically this ensures that anyone seeing the contents of `main2.dart` will see it imported via a `package` URI. Let us know if that works for you.

Obviously we don't want you to have to use the workaround and we should figure out why @jonahwilliams change wasn't enough to fix your example.

**Comment by jonahwilliams** [comment]
Reopening the issue for now, since I only checked what I thought was a duplicate I didn't do any further verification here. I'll make sure I can repro this and take another look

**Comment by jdeltoft** [comment]
@sigmundch Ok, I tried that work around and it worked but there are a few new concerns:

- after some time, my whole web page stops taking all click input, but I know it's still running as I have a 15 min timer that starts a screen saver animation and that animation worked perfectly still
- I'm unable to run my app now with that work around on an AVD tablet even if I point android studio run to main2.dart.  (Not a big deal, but was going to try this to debug the input)
- I'm unable to run in chrome in --debug mode.  I can only run in --profile or --release 

Here is the error I get when the input times out:

![image](https://user-images.githubusercontent.com/4506303/70239886-c853e880-1731-11ea-8631-a4d0490522ae.png)

The instant that happens, all input ability stops.  

![image](https://user-images.githubusercontent.com/4506303/70239976-f6392d00-1731-11ea-9136-589c4e9e60a3.png)

**Comment by jdeltoft** [comment]
So I looked at all my dispose calls up to this point, it's nothing there.  I printed out when those are happening and it's not near the failure.  

I also noticed that when I get this failure, if I move my mouse pointer around the screen, then this failure count increases.  A still shot doesn't do it justice, but hopefully you understand my point.  I'm not aware of anything I'm doing special to work with mouse pointer location, but something is definitely happening with that which is this error.  


![image](https://user-images.githubusercontent.com/4506303/70242990-66967d00-1737-11ea-9917-1af122db47c5.png)

**Comment by jdeltoft** [comment]
Ok, sorry for the noise here.  I believe this was broken and now fixed in flutter release.  I just did another flutter upgraded, and I'm using your workaround for now still @sigmundch and now my app works great for long periods of time.

Here is where my head is now:

![image](https://user-images.githubusercontent.com/4506303/70266607-71b2d280-1762-11ea-829d-4473ad6b0f41.png)

**Comment by vsmenon** [comment]
Thanks for confirming.  I just checked your tarball.  It appears to work for me in flutter dev and master channels (release/profile/debug) as well.

**Comment by vsmenon** [comment]
BTW - I didn't have to use a workaround either.  At least, not with the tarball.

**Comment by jdeltoft** [comment]
@vsmenon Agreed!  I didn't actually notice that until just now.  I saw that other new hang problem, saw it was fixed by a flutter upgrade, and didn't undo the temporary work around yet.  Now I just did and indeed it's working without any work around.  Thanks again everyone for the fantastic help!
