### ISSUE TITLE
Default flutter doctor to --verbose

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#44124]
## Use case

Though the GitHub issue template says to paste the output of `flutter doctor --verbose`, many people miss those instructions and just paste the output of `flutter doctor`.  `--verbose` gives more information and doesn't take any more time to run.

## Proposal

Default `flutter doctor` to `--verbose`.  Support `--no-verbose` if we can think of a use-case for that.

## Alternative

Remove `--verbose` flag and only ever show the verbose version.

**Comment by jmagman** [comment]
@zanderso @jonahwilliams @dnfield Thoughts on this proposal?

**Comment by dnfield** [comment]
/cc @Hixie @tvolkert 

I agree this can add latency when trying to get a good bug report. I'm not entirely sure what the difference would be like for a Flutter user (i.e. a developer who is not a framework/tool/engine developer).  So basically: this would be good for the team, would it be good (or at least not bad) for users?

For reference, here's the difference for me running this locally:

```text
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel reattach_text_input, v1.10.15-pre.365, on Mac OS X 10.14.6 18G103, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Chrome - develop for the web
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[!] IntelliJ IDEA Community Edition (version 2019.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.39.2)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

verbose:

```text
[✓] Flutter (Channel reattach_text_input, v1.10.15-pre.365, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.10.15-pre.365 at /Users/dnfield/src/flutter/flutter
    • Framework revision d4ad315c45 (2 hours ago), 2019-11-04 10:01:04 -0800
    • Engine revision 4b76fadbf4
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 d50c158d42)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dnfield/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/dnfield/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B44
    • CocoaPods version 1.7.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.87
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

**Comment by dnfield** [comment]
Maybe we could have a `flutter doctor --compact` for users that still want to see less detail.

**Comment by jonahwilliams** [comment]
I think one issue is that doctor is doing double-duty as both a local diagnostic tool and a bug report helper.

Maybe there should be a separate flutter bugreport command that includes this information, along with whatever else we need, like the crash reports.

**Comment by jmagman** [comment]
> I think one issue is that doctor is doing double-duty as both a local diagnostic tool and a bug report helper.

`--verbose` seems more helpful in either scenario.  The difference in output doesn't seem like enough to make a non-verbose worth it.

> Maybe there should be a separate flutter bugreport command that includes this information, along with whatever else we need, like the crash reports.

I just proposed something similar here: https://github.com/flutter/flutter/issues/44126

**Comment by jmagman** [comment]
To be updated on the website:
[_get-sdk.md](https://github.com/flutter/website/blob/master/src/docs/get-started/install/_get-sdk.md#run-flutter-doctor)
[android.md](https://github.com/flutter/website/blob/master/src/docs/deployment/android.md#create-a-keystore)

**Comment by tvolkert** [comment]
fwiw, verbose _used_ to be the default, and we changed it to avoid overloading users with info they didn't care about.  iirc @mit-mit had opinions on this at the time.

**Comment by Hixie** [comment]
Before changing this please look at the history to see if the reasons that made us pick this design have changed.

The number of people filing bugs is dwarfed by the number of people using `flutter doctor` when _not_ filing bugs.

**Comment by mit-mit** [comment]
We rely on having developers run doctor during their intial setup. We found that many developers are interested in developing for a single platform, and get overwhelmed with the detailed doctor feedback for other platforms they have no interest in developing for (at least during their initial time with Flutter).

I would not recommend making this change with our current design, especially now that we are adding many more _potential_ platforms. It would be worth considering if doctor overall should test for just general issues, and somehow we would have the developer tell us which platforms they are developing for (either specifically, or indirectly by looking at what they pass to flutter create). cc @csells

**Comment by csells** [comment]
we've gone back and forth on this. our current plan is to NOT use --verbose as the default but to update the `flutter doctor` output to be more friendly, i.e. to give it a better 'bedside manner' if you will : )

Essentially, instead of turning it into a game of checkmarks, we make it clear that you only need to do certainly things IF you are targeting the platform in question. This in combination with real setup apps should hopefully make this problem much less of a problem.

**Comment by dnfield** [comment]
So maybe Jonah's suggestion of something like `flutter bugreport` would be helpful here instead of overloading`flutter doctor` for both guidance for new users as well as bug reports for developers.

**Comment by tvolkert** [comment]
Having a proper `flutter bugreport` would be very useful, since we could stuff other info into it beyond the output of doctor.

See also https://github.com/flutter/flutter/issues/1657 https://github.com/flutter/flutter/issues/11402

**Comment by jmagman** [comment]
It looks like the `--verbose` flag [was added January 2018](https://github.com/flutter/flutter/pull/14173) with discussion [here](https://github.com/flutter/flutter/issues/12767).

> Essentially, instead of turning it into a game of checkmarks, we make it clear that you only need to do certainly things IF you are targeting the platform in question. This in combination with real setup apps should hopefully make this problem much less of a problem.

I guess "develop for Android devices" "develop for iOS and macOS" "develop for the web" [headers](https://github.com/flutter/flutter/commit/7ae6f7f3914ede056ff75e435130ffc7e0483083) aren't sufficient to indicate which sections are relevant to which platform, maybe it's too busy looking?  
```
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dnfield/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/dnfield/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B44
    • CocoaPods version 1.7.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
```

The tool isn't set up to be extensible to arbitrary platforms (yet).  Closing in favor of https://github.com/flutter/flutter/issues/1657 and https://github.com/flutter/flutter/issues/44126.

**Comment by csells** [comment]
"Android toolchain - develop for Android devices"

isn't as clear as

"Android tooling - ONLY NEEDED if targeting Android devices"

Would love feedback from @InMatrix on this.

**Comment by InMatrix** [comment]
> "Android tooling - ONLY NEEDED if targeting Android devices"

This looks like a useful clarification. 

Regarding the original bug, I think having a separate `flutter bugreport` command sounds really useful.
