### ISSUE TITLE
Tool error output should include a proposed GitHub issue template

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#44126]
## Proposal

Anywhere the tool says "please let us know at https://github.com/flutter/flutter/issues" it could also print a proposed GitHub issue template that includes:
- Proposed title (example: error text, location of crash)
- The actual output of `flutter doctor -v`
- Last x flutter commands run
- First x number of useful lines from the crash stack trace
- Plugins w/ versions
- Useful info from the pubspec.yaml
- Other useful things we can think of

**Comment by zanderso** [comment]
This sounds great!
