### ISSUE TITLE
TextField's InkWell effect stays infinitely after quick focus & and unfocus gestures

### ISSUE THREAD

**Issue by Pavel-Sulimau** [flutter/flutter#44129]
## Steps to Reproduce

1. Create an app with this code:

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("TextField's focusing"),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              Expanded(
                child: TextField(
                  expands: true,
                  maxLines: null,
                  decoration: InputDecoration(
                    border: OutlineInputBorder(),
                  ),
                ),
              ),
              SizedBox(height: 8.0),
              Expanded(
                child: TextField(
                  expands: true,
                  maxLines: null,
                  decoration: InputDecoration(
                    border: OutlineInputBorder(),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

2. Run the app on a physical device (iOS or Android).
3. Use two fingers to quickly change focus from the first text input to the second and then back to the first one.
4. Observe the behavior of the tap animations (InkWell animation's effect is being shown infinitely).

**Demo from Google Pixel 3 (Android 10):**
<img src="https://user-images.githubusercontent.com/8143332/68154681-1a4df680-ff59-11e9-85da-5727d49afd1b.gif" width="300" height="600">

**Demo from iPhone 8 (iOS 13.1):**
<img src="https://user-images.githubusercontent.com/8143332/68154696-20dc6e00-ff59-11e9-8c2a-caf99c83f226.gif" width="300" height="600">

## Logs

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A602, locale en-BY)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by vurvn** [comment]
this work for me 

`MaterialApp(
      theme: ThemeData(
        splashColor: Colors.transparent
      ),
      home: Scaffold(),
      )
);
`

**Comment by Pavel-Sulimau** [comment]
> this work for me
> 
> `MaterialApp( theme: ThemeData( splashColor: Colors.transparent ), home: Scaffold(), ) ); `

Correct me, if I'm wrong, but it doesn't fix the issue with the animation, it just disables the animation effect at all.

**Comment by Pavel-Sulimau** [comment]
> this work for me
> 
> `MaterialApp( theme: ThemeData( splashColor: Colors.transparent ), home: Scaffold(), ) ); `

Correct me, if I'm wrong, but it doesn't fix the issue with the animation, it just disables the animation effect at all.

**Comment by TahaTesser** [comment]
Hi @Pavel-Sulimau 
Looks like there is inkwell effect in `TextFeild`
if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
