### ISSUE TITLE
Add a dither parameter to dart:ui's Paint class

### ISSUE THREAD

**Issue by jkurtw** [flutter/flutter#44134]
> Gradients currently have a lot of color banding on all devices, and it looks very weird when using the pulse animation too. A solution is to make the gradients opaque, and to use dithered gradients with Skia. Dithered gradients aren't currently exposed, so adding a dither parameter to dart:ui's Paint class would be nice. We'd be able to manually draw our gradients with a CustomPainter.

b/143897620

**Comment by Hixie** [comment]
We should just make our gradients look good, I don't think we should add specific controls like this.
