### ISSUE TITLE
Assigning RenderBox.size calls intrinsic sizing functions re-entrantly

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#4413]
... confusing code that uses TextPainter because TextPainter's intrinsic sizing is destructive.

See https://github.com/flutter/flutter/pull/4391

**Comment by Hixie** [comment]
I'm going to close this. We've worked around this in the one place we've run into it, and the asserts are hugely valuable so I'd rather not change them. If you think we should do something here don't hesitate to reopen it.
