### ISSUE TITLE
Upgraded Plugin's tests don't work

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#44142]
I updated the [crashlytics plugin](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_crashlytics) according to the [wiki article](https://github.com/flutter/flutter/wiki/Experimental:-Create-Flutter-Plugin) but the 14th step doesn't work (code can be found [here](https://github.com/gaaclarke/flutterfire/commit/42960058487a7ebb43731bd3cbf44bd9d051930d)).

The error is:
```bash
$ ./gradlew app:connectedAndroidTest -Ptarget=`pwd`/../../test/firebase_crashlytics_e2e.dart
...
com.android.builder.testing.ConnectedDevice > No tests found.[POCOPHONE F1 - 9] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
```

@bparrishMines Reported seeing the same issue when upgrading other Plugins.

**Comment by bparrishMines** [comment]
@gaaclarke Has this been resolved?

**Comment by gaaclarke** [comment]
Yes!  I don't recall what fixed it but I know we updated the wiki to include the change that should avoid it.

One thing that helped debug it was using a different phone.  The Pocophone was not printing out the error for some reason.  I think I eventually got a decent error on a Huawei.

**Comment by myriky** [comment]
0.1.3+3 version doesn't support v2 plugin. any updates?
