### ISSUE TITLE
Support ShaderMask on web

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#44152]
I discovered in the [CupertinoContextMenu PR](https://github.com/flutter/flutter/pull/43918) that Flutter Web does not support the ShaderMask widget right now.  Running tests that created this widget caused assertion unimplemented errors for `pushShaderMask`.  See a [Cirrus run](https://cirrus-ci.com/task/6603101473079296).

We should implement support for ShaderMask and remove the conditional `skipTest: isBrowser` in [context_menu_test.dart](https://github.com/flutter/flutter/blob/50b87dc6c342141800fc991c6f094a9a60614cdf/packages/flutter/test/cupertino/context_menu_test.dart#L130).

**Comment by eyjiang** [comment]
Hi! Could I try taking this task? Thanks!

**Comment by justinmc** [comment]
@eyjiang Yeah please do!  Sorry for the delayed response.

@yjbanov Do you have any more context for implementing ShaderMask on web?

**Comment by diegoveloper** [comment]
Check this sample I created: https://dartpad.dev/5536c9d19d9ea15874416dc4835ba06d  , it works fine in mobile.
If you check this condition ` child: true ? ShaderMask`  to false it will work.

**Comment by yjbanov** [comment]
Sorry for late response. TBH I've no idea what shader mask does, so I cannot provide much context. I imagine the change would be similar to https://github.com/flutter/engine/commit/33813929e3cdb663900978d2586aee09459d4dcf. For the CanvasKit backend it's likely a matter of forwarding the right method call. For the HTML backend the trick is to find the HTML/canvas equivalent of this effect.

**Comment by Dibitybopty** [comment]
Anything new on supporting ShaderMask for Web? Looks like a great widget to use.

**Comment by BrutalCoding** [comment]
Still broken as of now with the latest beta. Getting the following error 'Another exception was thrown: PersistedOffset: is in an unexpected state.' when using the ShaderMask() widget. The properties my widget has are just the shaderCallback and a child. Returning null or a LinearGradient in the shaderCallback makes no difference for the error.

Flutter (Channel beta, v1.17.0-3.4.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.0-3.4.pre at /Users/danielbreedeveld/Development/Tools/flutter
    • Framework revision e6b34c2b5c (2 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

**Comment by pravnviji** [comment]
I'm new to flutter development. is ShaderMask is supported in 1.19.0-4.2.pre- channel beta ?

**Comment by justinmc** [comment]
ShaderMask is not supported on web yet, but it is supported on other platforms.  If someone adds support on web, this issue will be updated.

**Comment by geriby23** [comment]
I'm trying to add ImageShader to Shader mask but seems non of its BlendModes are working on the web. So does ShaderMask works in the web now?

**Comment by justinmc** [comment]
No support for ShaderMask has been added in the web yet.

**Comment by Niggelgame** [comment]
I would love to see this Widget supported by web!

**Comment by melwinlobo18** [comment]
Please add this feature to flutter web soon. Shimmer which is a great package for mobile to show loading screen doesn't support the web because of this issue.

**Comment by yasinarik** [comment]
I wanted to use an opacity mask to have my child widget to **fade out to transparent** from the left and right sides.

I can't use `ShaderMask` on `Flutter Web`. What else can I use? Very urgent situation.

**Comment by tomasbaran** [comment]
it's on the second page of most popular issues. Shouldn't it have `customer:crowd` tag?

**Comment by syedassadullahshah** [comment]
Shader mask causing unimplemented error. Is it me only or flutter still doesnt support shaderMask for web.

**Comment by ferhatb** [comment]
@diegoveloper , thanks for patience on this issue. We have a fix, tested with your DartPad sample. It should land shortly in master. Great sample btw.

**Comment by mzdm** [comment]
@ferhatb Nice! I wonder whether it will make https://github.com/hnvn/flutter_shimmer/issues/25 shimmer package workable (on web)?

**Comment by Niggelgame** [comment]
> @ferhatb Nice! I wonder whether it will make https://github.com/hnvn/flutter_shimmer/issues/25 shimmer package workable (on web)?

Probably, since the only problem there was ShaderMask

**Comment by justinmc** [comment]
Closing this as it seems from https://github.com/flutter/flutter/issues/52967#issuecomment-785506069 and @ferhatb's comment above that ShaderMask is now supported on web.  Let me know if that's not right!

**Comment by arvind-iyer-2001** [comment]
I'm still facing errors with ShaderMasks on Flutter Web Builds. Has any fix arrived for this now? It seems to work fine on Emulators and Physical Devices but not on the Web~. Even Windows Desktop Flutter App seems to work.

**Comment by ferhatb** [comment]
@arvind-iyer-2001 please file a new issue with a small sample to reproduce.

**Comment by vargascarlitos** [comment]
It does not work for me for web applications
 

pd. In my work they only let me use the stable branch :(


```
Container(
                        color: background_light_3,
                        height: 8,
                        child: ShaderMask(
                          blendMode: BlendMode.srcATop,
                          shaderCallback: (rect) {
                            return gradient.createShader(rect);
                          },
                          child: LinearProgressIndicator(
                            value: value,
                            minHeight: 8,
                            backgroundColor: Colors.transparent,
                            valueColor: AlwaysStoppedAnimation<Color>(background_light),
                          ),
                        ),
                      ),
```



```
`Flutter 2.0.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1d9032c7e1 (hace 4 días) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)
`
```



- [══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
js_primitives.dart:30 The following UnimplementedError was thrown during a scheduler callback:
js_primitives.dart:30 UnimplementedError
js_primitives.dart:30 
js_primitives.dart:30 When the exception was thrown, this was the stack:
js_primitives.dart:30 dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
js_primitives.dart:30 lib/_engine/engine/html/scene_builder.dart 231:5                              pushShaderMask
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 2261:34                          addToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 891:12                           [_addToSceneWithRetainedRendering]
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1515:50                          addChildrenToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 2431:12                          addToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 891:12                           [_addToSceneWithRetainedRendering]
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1515:50                          addChildrenToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1620:12                          addToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 891:12                           [_addToSceneWithRetainedRendering]
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1515:50                          addChildrenToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1620:12                          addToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 891:12                           [_addToSceneWithRetainedRendering]
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1515:50                          addChildrenToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1620:12                          addToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 891:12                           [_addToSceneWithRetainedRendering]
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1515:50                          addChildrenToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1723:12                          addToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 891:12                           [_addToSceneWithRetainedRendering]
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1515:50                          addChildrenToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1620:12                          addToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 891:12                           [_addToSceneWithRetainedRendering]
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1515:50                          addChildrenToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 2431:12                          addToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 891:12                           [_addToSceneWithRetainedRendering]
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1515:50                          addChildrenToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1620:12                          addToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 891:12                           [_addToSceneWithRetainedRendering]
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1515:50                          addChildrenToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1620:12                          addToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 891:12                           [_addToSceneWithRetainedRendering]
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1515:50                          addChildrenToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 2073:12                          addToScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 1299:12                          buildScene
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 4918:48                          compositeFrame
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 6164:25                          drawFrame
js_primitives.dart:30 packages/flutter/src/widgets/widget_span.dart.js 51658:15                     drawFrame
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 6124:12                          [_handlePersistentFrameCallback]
js_primitives.dart:30 packages/flutter/src/scheduler/binding.dart.js 776:9                          [_invokeFrameCallback]
js_primitives.dart:30 packages/flutter/src/scheduler/binding.dart.js 744:37                         handleDrawFrame
js_primitives.dart:30 packages/flutter/src/scheduler/binding.dart.js 699:12                         [_handleDrawFrame]
js_primitives.dart:30 lib/_engine/engine/platform_dispatcher.dart 896:13                            invoke
js_primitives.dart:30 lib/_engine/engine/platform_dispatcher.dart 145:5                             invokeOnDrawFrame
js_primitives.dart:30 lib/_engine/engine.dart 259:45                                                <fn>
js_primitives.dart:30 ════════════════════════════════════════════════════════════════════════════════════════════════════
2js_primitives.dart:30 Another exception was thrown: UnimplementedError
5805js_primitives.dart:30 Another exception was thrown: PersistedPhysicalShape: is in an unexpected state. ]

**Comment by Ahmadre** [comment]
> @diegoveloper , thanks for patience on this issue. We have a fix, tested with your DartPad sample. It should land shortly in master. Great sample btw.

Thank you guys soo much :)) it works also in beta channel

**Comment by Ahmadre** [comment]
Is there any plan to have this on the stable channel?

**Comment by renanmgs** [comment]
Any update?
In some mobile resolutions is doesn't seem to work.

Desktop:
![image](https://user-images.githubusercontent.com/30127127/119740538-79849c00-be5a-11eb-845f-48a0e1b3738d.png)

Pixel 2:
![image](https://user-images.githubusercontent.com/30127127/119740577-8608f480-be5a-11eb-92a1-c3efd4ed7505.png)

Iphone:
![image](https://user-images.githubusercontent.com/30127127/119740613-95883d80-be5a-11eb-94cc-2660cabd553b.png)


On my physical device don't work too.

**Comment by renanmgs** [comment]
> Closing this as it seems from [#52967 (comment)](https://github.com/flutter/flutter/issues/52967#issuecomment-785506069) and @ferhatb's comment above that ShaderMask is now supported on web. Let me know if that's not right!

Appears to be not working as expected in some mobile browsers.

**Comment by justinmc** [comment]
@renanmgs Can you open a new issue with instructions to reproduce and tag me and @ferhatb?

**Comment by renanmgs** [comment]
@justinmc  Its very simple, just an image with a LinearGradient from black to transparent. In some mobile browsers the gradient don't work. Its reproducible in chrome in the Device Toolbar. Some Mobile aspects the gradient work as expected, in others (like Pixel 2) don't. In every mobile browser that i tested physically does not work as well.

But i can open in a new issue if you really want.

**Comment by justinmc** [comment]
Yes please if you have time!  That way this bug will get triaged and someone will look at it.
