### ISSUE TITLE
[url_launcher] ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by kevin-lr** [flutter/flutter#44154]
When I archive the binary file for App Store today, the following issues occurs :

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
maybe,I use https://github.com/flutter/plugins/tree/master/packages/url_launcher and is causing this.
How can I solve?
my plugins:
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^2.0.7
  flutter_swiper: ^1.1.4
  flutter_screenutil: ^0.6.0
  url_launcher: ^5.2.5
  flutter_easyrefresh: ^2.0.4
  provider: ^3.0.0+1
  fluro: ^1.4.0
  shared_preferences: ^0.5.1
  flutter_spinkit: ^3.1.0
  flutter_cupertino_date_picker: ^1.0.8
  amap_base_location: 0.4.0+2
  city_pickers: ^0.1.23
  image_picker: ^0.6.0+17
  flutter_downloader: ^1.1.9
  path_provider: ^1.1.0
  permission_handler: ^3.0.0
  open_file: ^2.0.1+2
  install_plugin: ^2.0.1
  package_info: ^0.4.0+2
  fake_wechat: ^0.3.3
  get_ip: ^0.3.0
  common_utils: ^1.1.3
  barcode_scan: ^1.0.0
  image: ^2.0.7
  path: ^1.6.2
  fake_path_provider: ^0.1.3
  jpush_flutter: ^0.1.0
  image_cropper: ^1.0.2
  qr_flutter: ^3.0.1
  flutter_alipay: ^0.1.2
  flutter_full_pdf_viewer: ^1.0.6

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/39470

**Comment by ianloic** [comment]
I don’t think I’m relevant to this issue

**Comment by jmagman** [comment]
Not sure which plugin is causing this.  https://github.com/flutter/plugins/pull/2127/files fixes google_sign_in, but the originator isn't using that plugin.
\cc @collinjackson

**Comment by kevin-lr** [comment]
> Hi @ianloic
> can you please provide your `flutter doctor -v`
> and your `flutter run --verbose`?
> Thank you
> 
> #39470

macs-MacBook-Pro:bcb_cust mac$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A583, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.4 at /Users/mac/flutter/fsdk/flutter
    • Framework revision cc949a8e8b (6 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/mac/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 40.1.1
    • Dart plugin version 191.8423

[✓] Connected device (1 available)
    • DE106 • 192.168.31.190:5555 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
 flutter run --verbose     result:
[+3907 ms] DevFS: Sync finished
[   +2 ms] Syncing files to device DE106... (completed in 6,453ms, longer than expected)
[   +1 ms] Synced 19.8MB.
[   +2 ms] Sending to VM service: _flutter.listViews({})
[   +9 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x77eca50a20, isolate:
{type: @Isolate, fixedId: true, id: isolates/1566674928836355, name: main.dart$main-1566674928836355, number:
1566674928836355}}]}
[        ] <- accept
[        ] Connected to _flutterView/0x77eca50a20.
[   +2 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on DE106 is available at: http://127.0.0.1:64312/SDXJ--DzX3k=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+15738 ms] I/zygote64(21186): Do partial code cache collection, code=30KB, data=24KB
[   +3 ms] I/zygote64(21186): After code cache collection, code=30KB, data=24KB
[        ] I/zygote64(21186): Increasing code cache capacity to 128KB

**Comment by kevin-lr** [comment]
i find out it's fake_wechat 0.3.3

**Comment by nemoryoliver** [comment]
> i find out it's fake_wechat 0.3.3

How'd you find it out? I want to find on mine too.
