### ISSUE TITLE
http link not opening in android 9 after giving security permission also.It shows Cleartext HTTP traffic not permitted

### ISSUE THREAD

**Issue by Mallika-Tung** [flutter/flutter#44162]
http link not opening in android 9 after giving security permission also.It shows Cleartext HTTP traffic not permitted

**Comment by iapicca** [comment]
Hi @Mallika-Tung 
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`.
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
