### ISSUE TITLE
Flutter Web Not Working On Chrome

### ISSUE THREAD

**Issue by Bruskyer** [flutter/flutter#44168]
When run flutter web on vs code I get error(Unable to connect to Chrome debug port: 56044
SocketException: OS Error: The remote computer refused the network connection.
, errno = 1225, address = localhost, port = 56051) and chrome tab appear empty no localhost and port in addres bar! please can you share any solution for this issue? or there is a way to change or set custom localhost and port ?
-But normally app is working on emulator as fine without error!
-flutter doctor does not detect any issue!
-no proxies and my device connect to the internet etc.
Thanks

**Comment by jeffsui** [comment]
So do I. have you upgrade to lastest flutter？ what's your flutter version？

**Comment by iapicca** [comment]
Hi @Bruskyer 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by Bruskyer** [comment]
PS C:\TestMVC\mytest> flutter doctor -v
[√] Flutter (Channel master, v1.10.15-pre.404, on Microsoft Windows [Version 10.0.17763.379], locale en-US)
    • Flutter version 1.10.15-pre.404 at C:\src\flutter
    • Framework revision 9093cf15f6 (27 hours ago), 2019-11-04 22:30:16 -0500
    • Engine revision 7b968ff95f
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\VEYSI.YIGIT\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\VEYSI.YIGIT\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] VS Code, 64-bit edition (version 1.38.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.87
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
PS C:\TestMVC\mytest> flutter run --verbose
[  +41 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +204 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 9093cf15f631b354c0fae4d726a8638b308a5e31
[        ] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +203 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.10.14-404-g9093cf15f6
[   +7 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +163 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[ +150 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +210 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[ +174 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +141 ms] executing: C:\Users\VEYSI.YIGIT\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +110 ms] Exit code 0 from: C:\Users\VEYSI.YIGIT\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +12 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +89 ms] Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.87
[   +2 ms] Web Server • web-server • web-javascript • Flutter Tools
[  +10 ms] "flutter run" took 539ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:287:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:532:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:457:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:222:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by iapicca** [comment]
thank you @Bruskyer for providing your logs

**Comment by jonahwilliams** [comment]
> [  +12 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag,

You need to specify -d chrome.

The socketException might be firewall related. If you don't have the permissions to connect to a local webserver you won't be able to run Chrome, though I'm not sure what specifically would be causing it

**Comment by Bruskyer** [comment]
ok  thanks alot for your replies.
there is forcepoint one endpoint and CheckPoint Endpoint Security on my pc!
is there any way to set proxy setting and connect to local server through these apps?
Thanks

**Comment by johnpryan** [comment]
The Flutter tools choose the port that the server is running on (typically between 50k-60k in my experience). You might be able to configure your security software to allow you to use a range of TCP ports.

**Comment by jonahwilliams** [comment]
You specify the port value with --web-port too

**Comment by Bruskyer** [comment]
@jonahwilliams @johnpryan 
I hope this will solve my issue. 
Thanks a lot

**Comment by rohan12patil** [comment]
try using 
flutter run -d web
This has worked for me. 
![flutter run web](https://user-images.githubusercontent.com/5665470/71163303-cf6f1080-2272-11ea-9003-82dc717f693c.png)
