### ISSUE TITLE
Tooltip is under my finger on Tooltips Controls page in Gallery

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4416]
Repro:
Long press the telephone handset on the Tooltip page in the Gallery.
Notice in the photo below that the tooltip is underneath the phone icon. This position is usually covered up by your finger. A tooltip above the phone icon would be better.

![img_3394](https://cloud.githubusercontent.com/assets/7953123/15866956/d8daa1ba-2c95-11e6-93d3-43918d943650.JPG)

**Comment by abarth** [comment]
Yes, I agree with you, but the spec says to prefer putting the tooltip below the button and we confirmed that was the behavior the design team wants.
