### ISSUE TITLE
Cannot switch from STABLE to MASTER channel

### ISSUE THREAD

**Issue by CodePhilanthropist** [flutter/flutter#44165]
Hello, I'm having a problem switching from stable channel to master channel. Any help would be appreciated.

Switching to flutter channel 'master'...
git: error: The following untracked working tree files would be overwritten by checkout:
git:    bin/internal/libzip.version
git:    dev/automated_tests/flutter_test/print_correct_local_widget_expectation.txt
git:    dev/automated_tests/flutter_test/print_correct_local_widget_test.dart
git:    dev/automated_tests/test_smoke_test/pending_timer_fail_test.dart
git:    dev/benchmarks/macrobenchmarks/lib/src/simple_animation.dart
git:    dev/benchmarks/macrobenchmarks/test_driver/simple_animation_perf.dart
git:    dev/benchmarks/macrobenchmarks/test_driver/simple_animation_perf_test.dart
git:    dev/bots/accept_android_sdk_licenses.sh
git:    dev/bots/debug_smoke_ftl.sh
git:    dev/bots/test/bot_test.dart
git:    dev/bots/test/sdk_directory_has_space_test.dart
git:    dev/bots/test/test_test.dart
git:    dev/ci/docker_linux/Gemfile
git:    dev/ci/mac/Gemfile
git:    dev/devicelab/bin/tasks/backdrop_filter_perf_ios__timeline_summary.dart
git:    dev/devicelab/bin/tasks/gradle_non_android_plugin_test.dart
git:    dev/devicelab/bin/tasks/gradle_r8_test.dart
git:    dev/devicelab/bin/tasks/plugin_lint_mac.dart
git:    dev/devicelab/bin/tasks/simple_animation_perf_iphonexs.dart
git:    dev/devicelab/bin/tasks/smoke_catalina_hot_mode_dev_cycle_ios__benchmark.dart
git:    dev/devicelab/bin/tasks/smoke_catalina_start_up_ios.dart
git:    dev/integration_tests/abstract_method_smoke_test/android/app/build.gradle
git:    dev/integration_tests/abstract_method_smoke_test/android/app/src/debug/AndroidManifest.xml
git:    dev/integration_tests/abstract_method_smoke_test/android/app/src/main/AndroidManifest.xml
git:    dev/integration_tests/abstract_method_smoke_test/android/app/src/main/kotlin/com/example/abstract_method_smoke_test/MainActivity.kt
git:    dev/integration_tests/abstract_method_smoke_test/android/app/src/main/res/drawable/launch_background.xml
git:    dev/integration_tests/abstract_method_smoke_test/android/app/src/main/res/values/styles.xml
git:    dev/integration_tests/abstract_method_smoke_test/android/app/src/profile/AndroidManifest.xml
git:    dev/integration_tests/abstract_method_smoke_test/android/build.gradle
git:    dev/integration_tests/abstract_method_smoke_test/android/gradle.properties
git:    dev/integration_tests/abstract_method_smoke_test/android/gradle/wrapper/gradle-wrapper.properties
git:    dev/integration_tests/abstract_method_smoke_test/android/settings.gradle
git:    dev/integration_tests/abstract_method_smoke_test/lib/main.dart
git:    dev/integration_tests/abstract_method_smoke_test/pubspec.yaml
git:    dev/integration_tests/android_embedding_v2_smoke_test/.gitignore
git:    dev/integration_tests/android_embedding_v2_smoke_test/.metadata
git:    dev/integration_tests/android_embedding_v2_smoke_test/README.md
git:    dev/integration_tests/android_embedding_v2_smoke_test/android/.gitignore
git:    dev/integration_tests/android_embedding_v2_smoke_test/android/app/build.gradle
git:    dev/integration_tests/android_embedding_v2_smoke_test/android/app/src/debug/AndroidManifest.xml
git:    dev/integration_tests/android_embedding_v2_smoke_test/android/app/src/main/AndroidManifest.xml
git:    dev/integration_tests/android_embedding_v2_smoke_test/android/app/src/main/kotlin/com/example/android_embedding_v2_smoke_test/MainActivity.kt
git:    dev/integration_tests/android_embedding_v2_smoke_test/android/app/src/main/res/drawable/launch_background.xml
git:    dev/integration_tests/android_embedding_v2_smoke_test/android/app/src/main/res/values/styles.xml
git:    dev/integration_tests/android_embedding_v2_smoke_test/android/app/src/profile/AndroidManifest.xml
git:    dev/integration_tests/android_embedding_v2_smoke_test/android/build.gradle
git:    dev/integration_tests/android_embedding_v2_smoke_test/android/gradle.properties
git:    dev/integration_tests/android_embedding_v2_smoke_test/android/gradle/wrapper/gradle-wrapper.properties
git:    dev/integration_tests/android_embedding_v2_smoke_test/android/settings.gradle
git:    dev/integration_tests/android_embedding_v2_smoke_test/android/settings_aar.gradle
git:    dev/integration_tests/android_embedding_v2_smoke_test/lib/main.dart
git:    dev/integration_tests/android_embedding_v2_smoke_test/pubspec.yaml
git:    dev/integration_tests/android_host_app_v2_embedding/README.md
git:    dev/integration_tests/android_host_app_v2_embedding/app/build.gradle
git:    dev/integration_tests/android_host_app_v2_embedding/app/src/main/AndroidManifest.xml
git:    dev/integra
git: Aborting
Switching channels failed with error code 1.

**Comment by igoriuz** [comment]
Did you try to use `-- force` as parameter?

**Comment by iapicca** [comment]
Hi @CodePhilanthropist 
did the solution proposed by @igoriuz worked?
Thank you

**Comment by elliott-io** [comment]
`flutter channel master --force` returns an error of "Too many arguments."

**Comment by iapicca** [comment]
hi @elliott-io 
I believe @igoriuz  meant `flutter update-packages --force-upgrade`, 
but I'm not sure that it would solve the problem, but trying doesn't cost anything.
@CodePhilanthropist are you still experiencing the issue?
thank you all

**Comment by Hixie** [comment]
I don't know what is going on in your local checkout but it seems you have gotten git into a very confused state. I would run `git clean -xffd` (backup any changes you want first) or, just delete the Flutter directory and reinstall.

**Comment by marcinOz** [comment]
I had the same problem and actually just adding `sudo` helped. 
So `sudo flutter channel master` maybe will work for you.

**Comment by MahdiGharooni** [comment]
I had the same problem and finally I soled it. This error means you have **changes on flutter SDK**.
You should go to flutter SDK directory, for example mine : C:\src\flutter 
then you can realize you have **git** in this directory and `git status` shows you, there are some changes, and because of these changes you cant switch your channel or even upgrade your flutter.
so by `git add .` and `git stash`  your changes ignored and you can switch to another channel.

**Comment by araafat3** [comment]
I had the same problem
and solved it by move flutter from branch with 3 GB free space 
to another branch with 8 GB free space

**Comment by vilsonfreitaspacheco** [comment]
I had this same problem, resolved by reversing changes in the flutter branch
  "git reset --hard HEAD"

**Comment by UmairWarriach** [comment]
> I had the same problem and finally I soled it. This error means you have **changes on flutter SDK**.
> You should go to flutter SDK directory, for example mine : C:\src\flutter
> then you can realize you have **git** in this directory and `git status` shows you, there are some changes, and because of these changes you cant switch your channel or even upgrade your flutter.
> so by `git add .` and `git stash` your changes ignored and you can switch to another channel.

I was switching from master to stable (This works for me) Thanks.
