### ISSUE TITLE
"llvm-rs-cc" is missing

### ISSUE THREAD

**Issue by Ehiremengold** [flutter/flutter#44179]
while run the main dart file from the android studio sdk
![Capture1](https://user-images.githubusercontent.com/47524476/68208073-3ebfc800-ff85-11e9-99e2-0c645c94cc8f.PNG)

this while running flutter doctor -v
![Capture2](https://user-images.githubusercontent.com/47524476/68208126-5bf49680-ff85-11e9-94a4-14f0ed360360.PNG)

**Comment by iapicca** [comment]
Hi @Ehiremengold 
you might want to take a look to this possible [solution](https://stackoverflow.com/questions/52732366/llvm-rs-cc-is-missing-android-studio)

**Comment by iapicca** [comment]
Hi @Ehiremengold 
does this [solution ](https://stackoverflow.com/questions/52732366/llvm-rs-cc-is-missing-android-studio)solve your issue?
thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
