### ISSUE TITLE
built_value and built_value generator have circular dependencies causing Flutter -> Fuchsia roll to fail

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#44188]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=40784. This might just be a simple fix; but looking at the build_value and built_value_generator projects its not clear to me how to correctly translate this circular dependency to gn would be.

cc @zanderso , named on the Google bug. Also cc @iskakaushik as FYI.

**Comment by zanderso** [comment]
On the fuchsia.dev issue @davidmorgan indicates that this can be resolved by bumping the built_value pulled by flutter_tool to version 7.0.0. @jonahwilliams can you note here the chain by which the tool is depending on built_value to help @kf6gpe and/or @davidmorgan file issues in the right places to upgrade.

**Comment by davidmorgan** [comment]
If you can force the versions of `built_value` and `built_value_generator` to `7.0.0` that will work, no updates are needed to other packages. The version change to `7.0.0` is purely about the `built_value_generator`->`built_value` dependency having a too high upper bound in `6.7.0`.

**Comment by jonahwilliams** [comment]
We're getting built_value through dwds, I just checked and the latest published version does not yet depend on 7.0: https://pub.dev/packages/dwds

**Comment by jonahwilliams** [comment]
cc @grouma

**Comment by grouma** [comment]
cc @matanlurey 

We need to rev `package:build_daemon`, `package:build_runner` and `package:code_builder`. There is a circular dependency from `package:code_builder` to `package:build_runner` so I'm not sure what the process is for increasing the `package:built_value` version.

**Comment by Hixie** [comment]
In principle whenever Flutter rolls we should simultaneously roll all our package dependencies to the same versions as the versions we have pinned, because that's the only supported configuration for Flutter. I'm not really sure how plausible that is though.

**Comment by iskakaushik** [comment]
I am removing the "customer critical" label, since we have a workaround. @grouma , @matanlurey are you able to come up with a process to remove the circular dependency? Given that in the absence of this we currently hard code built_value as a special case in the Fuchsia code base.

**Comment by grouma** [comment]
This should now be addressed.

We published a new version of `package:build_daemon` and `package:code_builder` which both support `package:built_value` `^7.0.0`.

**Comment by MrBirb** [comment]
fwiw dwds uses v8.3.0 now

**Comment by darshankawar** [comment]
Based on https://github.com/flutter/flutter/issues/44188#issuecomment-554114686 and https://github.com/flutter/flutter/issues/44188#issuecomment-1273738778, I feel safe to close this as solved. If this isn't correct, please write in comments and I'll reopen it.
