### ISSUE TITLE
Set custom size for your golden files

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#44185]
I want to set a custom size for my golden files. To simulate a "real" device with 1080x1920, portrait, landscape, ...

https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter#creating-a-new-golden-file-test

Placing a RepaintBoundry will decrease the resolution. But how can I set my own custom resolution for a golden file?

**Comment by Piinks** [comment]
Hi @vanlooverenkoen!
You can put a `SizedBox` around the `RepaintBoundary` to specify a custom size.

**Comment by goderbauer** [comment]
@vanlooverenkoen Did that answer your question?

**Comment by vanlooverenkoen** [comment]
No this does not work. This is my code


```
  testWidgets('test App Use', (tester) async {
    await tester.pumpWidget(SizedBox(height: 1920, width: 1080, child: RepaintBoundary(child: MyApp())));
     await tester.pumpAndSettle();
    expect(find.byType(MyApp), findsOneWidget);
    await expectLater(
      find.byType(type),
      matchesGoldenFile('img/$snapshotName.png'),
    );
  });
```

**Comment by Piinks** [comment]
Hey @vanlooverenkoen, thanks for providing more info!

> I can't use RepaintBoundary because there is not one repaintboundary in my widget tree

I am not sure what you mean here.

Have you tried without a `RepaintBoundary`? Typically, golden file testing is used to check individual components of your UI, rather than the entire composition. By passing in your entire app, there may be unexpected behavior, or a few extra steps to get the desired result. I would also try adding a `Center` widget, which has been successful in other tricky golden file tests that seek custom sizes. For example, this one from #42484, which has 
`Center` -> `SizedBox` -> `RepaintBoundary` 
to set the desired size:

```dart
await tester.pumpWidget(Center(
  child: SizedBox.fromSize(
    size: rect.size,
    child: RepaintBoundary(
      key: painterKey,
      child: CustomPaint(
        painter: GradientPainter(shader, rect) // or MyApp()
      ),
    ),
  ),
));
      await expectLater(find.byKey(painterKey), matchesGoldenFile(goldenName));
```

Let me know how this works out for you. 🙂

**Comment by vanlooverenkoen** [comment]
No that did not work. Can't figure it out

**Comment by vanlooverenkoen** [comment]
`tester.binding.window.physicalSizeTestValue = Size(828, 1792);` can be used to set a custom size. But it does not match a real iPhone 11. the size is a lot smaller. @Piinks

**Comment by Piinks** [comment]
> `tester.binding.window.physicalSizeTestValue = Size(828, 1792);` can be used to set a custom size. But it does not match a real iPhone 11. the size is a lot smaller. @Piinks

I don't think we have plans right now to support golden file testing for device-specific screen specifications. Golden files are intended to generically validate that the application is drawing what is expected.

**Comment by vanlooverenkoen** [comment]
And what if I expect it would draw something if the size is bigger the 900px?

**Comment by markusaksli-nc** [comment]
Since this is not desirable or feasible for Flutter I'm going to close this issue for now.

**Comment by vanlooverenkoen** [comment]
Why is it not desirable or feasible? 

I think it would make sense to create screenshots tests that actually look like your device screen. To prevent regression issues

**Comment by markusaksli-nc** [comment]
As mentioned before, golden files are not meant for device-specific testing of your entire app screen. Physical device screenshot validation sounds like either an entirely new feature or something better suited as a plugin.

**Comment by Piinks** [comment]
This package may have the features you are looking for: https://pub.dev/packages/golden_toolkit :)

**Comment by vanlooverenkoen** [comment]
:o @Piinks yes indeed. Thanks for taking an extra look
