### ISSUE TITLE
Running or debuging very slow after upgrade to last version 1.9.1+hotfix.6

### ISSUE THREAD

**Issue by traderdata** [flutter/flutter#44190]
After I upgraded to this version (stable branch) I can't run my project anymore. Evrything got really slow.

Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (8 weeks ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 11.1)
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

Thanks

**Comment by jmagman** [comment]
What platform is it slow on?  What part of it is slow?

**Comment by traderdata** [comment]
I am running on a MAC, android.
Whenever I try to run or debug my app it takes TOOO long to do it and
sometimes nothing happens. If I . return to flutter 1.7.8, everything is ok.

Thanks

Em ter., 5 de nov. de 2019 às 15:16, Jenn Magder <notifications@github.com>
escreveu:

**Comment by jmagman** [comment]
Can we get the output of `flutter build --verbose` to see where it's slow?

**Comment by traderdata** [comment]
I will send you, but besides the fact that is really slow, we have a bigger
problem. It seems that this version 1.9.1 has a problem with Samsung J6
devices, which is wdidely used in Brazil. It seems that this issue was
fixed on dev, but dev brought some other issues. Any idea of when this
issue is going to be fixed in 1.9.1?

Thanks

Em ter., 5 de nov. de 2019 às 19:05, Jenn Magder <notifications@github.com>
escreveu:

**Comment by traderdata** [comment]
The bug I am mentioning is #37155

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by amani27** [comment]
I'm facing this problem after upgrading to latest stable version 1.20.4 
Earlier I was using Flutter 1.12.13+hotfix.5 and debug/run speed was good enough.
I am using a Windows 10 machine 
> flutter doctor -v produces the following output
`[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.20.4 at D:\flutter
    • Framework revision fba99f6cf9 (8 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\amani\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\amani\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\amani\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
PS C:\Users\amani\Documents\AppifyLab Flutter Projects\al-mp-flutter-foodserviceapp> flutter doctor -v
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.20.4 at D:\flutter
    • Framework revision fba99f6cf9 (8 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\amani\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\amani\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\amani\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!`

**Comment by amani27** [comment]
I'm facing this problem after upgrading to latest stable version 1.20.4
Earlier I was using Flutter 1.12.13+hotfix.5 and debug/run speed was good enough.
I am using a Windows 10 machine.
Running flutter doctor -v yields the following output
`
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.20.4 at D:\flutter
    • Framework revision fba99f6cf9 (8 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\amani\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\amani\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\amani\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
`

**Comment by iapicca** [comment]
@amani27 
I believe the case you are describing should be addressed in a separate issue
