### ISSUE TITLE
!_debugLocked is not true.

### ISSUE THREAD

**Issue by akshat102** [flutter/flutter#44202]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by iapicca** [comment]
Hi @akshat102 
can you please describe the issue in detail
and provide your `flutter doctor -v`
thank you

**Comment by akshat102** [comment]
> Hi @akshat102
> can you please describe the issue in detail
> and provide your `flutter doctor -v`
> thank you

[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18362.418], locale en-IN)
    • Flutter version 1.9.1+hotfix.5 at C:\flutter
    • Framework revision 1aedbb1835 (3 weeks ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\aknit\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Redmi Note 5 Pro • 92ec6a26 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by akshat102** [comment]
> Hi @akshat102
> can you please describe the issue in detail
> and provide your `flutter doctor -v`
> thank you

[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18362.418], locale en-IN)
    • Flutter version 1.9.1+hotfix.5 at C:\flutter
    • Framework revision 1aedbb1835 (3 weeks ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\aknit\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Redmi Note 5 Pro • 92ec6a26 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by iapicca** [comment]
Hi again @akshat102
can you please describe the issue in detail
thank you for providing your flutter doctor -v

**Comment by akshat102** [comment]
> Hi again @akshat102
> can you please describe the issue in detail
> thank you for providing your flutter doctor -v

Built build\app\outputs\apk\debug\app-debug.apk.
Syncing files to device Redmi Note 5 Pro...
E/flutter (13677): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: setState() or markNeedsBuild() called during build.
E/flutter (13677): This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
E/flutter (13677): The widget on which setState() or markNeedsBuild() was called was:
E/flutter (13677):   Overlay-[LabeledGlobalKey<OverlayState>#deefe]
E/flutter (13677): The widget which was currently being built when the offending call was made was:
E/flutter (13677):   Builder
E/flutter (13677): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3687:11)
E/flutter (13677): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3702:6)
E/flutter (13677): #2      State.setState (package:flutter/src/widgets/framework.dart:1161:14)
E/flutter (13677): #3      OverlayState.insertAll (package:flutter/src/widgets/overlay.dart:346:5)
E/flutter (13677): #4      OverlayRoute.install (package:flutter/src/widgets/routes.dart:43:24)
E/flutter (13677): #5      TransitionRoute.install (package:flutter/src/widgets/routes.dart:180:11)
E/flutter (13677): #6      ModalRoute.install (package:flutter/src/widgets/routes.dart:907:11)
E/flutter (13677): #7      NavigatorState.pushReplacement (package:flutter/src/widgets/navigator.dart:1854:14)
E/flutter (13677): #8      _LoadingScreenState.getLocation (package:clima/screens/loading_screen.dart:26:27)
E/flutter (13677): #9      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
E/flutter (13677): #10     _LoadingScreenState.getLocation (package:clima/screens/loading_screen.dart:24:19)
E/flutter (13677): #11     _LoadingScreenState.initState (package:clima/screens/loading_screen.dart:21:5)
E/flutter (13677): #12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
E/flutter (13677): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (13677): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (13677): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (13677): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (13677): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (13677): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (13677): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (13677): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (13677): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter (13677): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (13677): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (13677): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (13677): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (13677): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (13677): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (13677): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (13677): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (13677): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (13677): #31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (13677): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (13677): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (13677): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter (13677): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (13677): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (13677): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (13677): #38     Ele

**Comment by akshat102** [comment]
> Hi again @akshat102
> can you please describe the issue in detail
> thank you for providing your flutter doctor -v

and the error.............................................




The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#5e6d3](dirty, state: NavigatorState#52363(tickers: tracking 2 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2247 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

User-created ancestor of the error-causing widget was: 
  MaterialApp file:///C:/Users/aknit/AndroidStudioProjects/stack_skills/Clima-Flutter-master/lib/main.dart:11:12
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:2247:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by akshat102** [comment]
what happened??

**Comment by iapicca** [comment]
Hi @akshat102 
without looking at the code, this error

`E/flutter (13677): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: setState() or markNeedsBuild() called during build.`

suggest me that you are using set state in the build function of a widget
before "return", please don't build your logic inside the build function.

would be really helpful if you could provide
a minimal code sample to reproduce the problem
thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
