### ISSUE TITLE
Flutter 1.7.8 with catalina Support

### ISSUE THREAD

**Issue by traderdata** [flutter/flutter#44204]
Hi guys,

Can you please tell me if Catalina works with flutter 1.7.8? I had issues with 1.9.6 so I had to rollback to 1.7.8. But with catalina I can't build for release. I saw some issues around the same problem, but  it was marked as solved and I don't know if the was pushed back to this version.

Thanks

**Comment by jmagman** [comment]
There is no plan to hotfix Catalina support to 1.7.8.  Closing.
https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#will-a-particular-bug-fix-be-provided-in-a-hotfix-release

Out of curiosity, what 1.9.1 issue were you hitting?
