### ISSUE TITLE
Battery plugin example doesn't build

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#44207]
Our example apps should build on flutter master.

```
$ flutter run -d A
Running "flutter pub get" in example...                             3.1s
The plugin `battery` requires your app to be migrated to the Android embedding v2. Follow the steps on
https://flutter.dev/go/android-project-migration and re-run this command.
```

I'm not sure why CI isn't catching this.

**Comment by collinjackson** [comment]
Looks like a fix for this is pending: https://github.com/flutter/flutter/pull/44210

**Comment by TahaTesser** [comment]
Hi @collinjackson 
Given the pending PR is merged
 I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it.
 Thank you
