### ISSUE TITLE
Documentation spelling mistake

### ISSUE THREAD

**Issue by duncwillz** [flutter/flutter#44206]
Kindly verify and correct spelling mistake. Cheers! (InitialValue)
<img width="675" alt="Screenshot 2019-11-05 at 7 44 41 PM" src="https://user-images.githubusercontent.com/20598862/68240444-d57f9980-0004-11ea-9865-2a6a4784749e.png">

**Comment by shihaohong** [comment]
I believe this has been fixed with https://github.com/flutter/flutter/pull/44076. I'll close this issue for now, but re-open if it I'm mistaken!
