### ISSUE TITLE
Moving cocoon task logs from datastore to GCS

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#44219]
Cocoon task logs are being saved to datastore as log chunks. Whenever people view log by calling /api/get-log, cocoon backend queries all log chunks belonging to that commit & task, and append them together to frontend.

When people view logs at the same time, gRPC quota error may be hit. This happens more frequently especially after we increased testbed capacity.

Moving logs to GCS should solve this issue.

**Comment by CaseyHillers** [comment]
Is this a duplicate of https://github.com/flutter/flutter/issues/43124?

**Comment by keyonghan** [comment]
> Is this a duplicate of #43124?

You are right. Closing this one. Thanks.
