### ISSUE TITLE
Deflake and re-enable module_test

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#44216]
module_test was turned off on mac with https://github.com/flutter/flutter/pull/43375.

**Comment by jmagman** [comment]
module_test_ios was flaking due to the pubspec being modified in the future sometimes, somehow.
```
[module_test_ios] [STDOUT] Executing: /private/tmp/flutter sdk/bin/flutter build ios --no-codesign in /var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/flutter_module_test.PCYYnC/hello
[module_test_ios] [STDOUT] stderr: Warning: File "/private/var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/flutter_module_test.PCYYnC/hello/pubspec.yaml" was created in the future. Optimizations that rely on comparing time stamps will be unreliable. Check your system clock for accuracy.
[module_test_ios] [STDOUT] stderr: The timestamp was: 2019-11-04 15:47:32.000
[module_test_ios] [STDOUT] stderr: The time now is: 2019-11-04 15:43:17.832054
```

That modification time difference was exposing a real bug at https://github.com/flutter/flutter/issues/42956, and fixing that bug allowed us to turn back on module_test_ios.  https://github.com/flutter/flutter/issues/37525

Could the pubspec modification time drift be exposing some bug here, too?

**Comment by Hixie** [comment]
These seem to be enabled now.
