### ISSUE TITLE
Warning: pubspec.yaml was created in the future. Optimizations that rely on comparing time stamps will be unreliable.

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#44218]
Some CI tests are emitting logs indicating the pubspec.yaml was created in the future.

```
[module_test_ios] [STDOUT] stdout:     Warning: File "/private/var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/flutter_module_test.I3puyS/hello/pubspec.yaml" was created in the future. Optimizations that rely on comparing time stamps will be unreliable. Check your system clock for accuracy.
[module_test_ios] [STDOUT] stdout:     The timestamp was: 2019-11-05 14:12:05.000
[module_test_ios] [STDOUT] stdout:     The time now is: 2019-11-05 14:08:26.425318
```
This issue seems to be intermittent, which can manifest as flakiness.  Timestamp differences can be as much as 4+ minutes.

## Logs

https://cirrus-ci.com/task/5800186642694144?command=main#L222
[log.txt](https://github.com/flutter/flutter/files/3811578/log.txt)

**Comment by godofredoc** [comment]
@fkorotkov would you mind taking a look? it is a timezone related issue?

**Comment by DiegoCatalano** [comment]
@jmagman copy the content in the another file, save as pubspec.yaml and delete the old pubspec file.

**Comment by godofredoc** [comment]
@jmagman is this still happening or it was a one off problem?

**Comment by jmagman** [comment]
@godofredoc Has been happening for awhile, and @Hixie tried to track it down with https://github.com/flutter/flutter/pull/42491.  I'm not sure if it's still happening because I haven't been paying attention, but I don't know why it would be fixed.

**Comment by DanTup** [comment]
I'm seeing this today when running hot_reload_test locally on my MacBook (in UK):

```
       <=stderr=  Warning: File "/private/var/folders/b1/ftm2whhj4mb3_c4nfjhq23z00000gn/T/flutter_hot_reload_test.Cmpyfl/pubspec.yaml" was created in the future. Optimizations that rely on comparing time stamps will be unreliable. Check your system clock for accuracy.
       <=stderr=  The timestamp was: 2020-04-22 11:43:04.000
       <=stderr=  The time now is: 2020-04-22 11:42:59.410781
```

My clock is set to sync:

<img width="564" alt="Screenshot 2020-04-22 at 11 44 44" src="https://user-images.githubusercontent.com/1078012/79972987-b085c280-848e-11ea-95e5-16d286083978.png">

I've seen it quite a lot this morning (though I don't think it's happening on every run), so if there's anything extra I can do to debug, let me know!

**Comment by jmagman** [comment]
@DanTup does the "time now" comment at least match your machine time? Just checking in case we have to deal with time warps.

**Comment by DanTup** [comment]
```
 0s <=stderr=             The timestamp was: 2020-04-22 18:06:44.000
       <=stderr=             The time now is: 2020-04-22 18:06:39.357460
```

At the time this appeared on my screen, the clock in the system preferences showed 18:06:39. So it timestamp if gives for the pubspec modification looks bad.

**Comment by DanTup** [comment]
Here's an example with the output of `stat` on the file too:

```
    0s <=stderr=  [        ] Warning: File "/private/var/folders/b1/ftm2whhj4mb3_c4nfjhq23z00000gn/T/flutter_hot_reload_test.cVbIHL/pubspec.yaml" was created in the future. Optimizations that rely on comparing time stamps will be unreliable. Check your system clock for accuracy.
       <=stderr=             The timestamp was: 2020-04-22 18:10:02.000
       <=stderr=             The time now is: 2020-04-22 18:09:56.924980
✓ hot reload works without error
```

```
stat /private/var/folders/b1/ftm2whhj4mb3_c4nfjhq23z00000gn/T/flutter_hot_reload_test.cVbIHL/pubspec.yaml   
16777221 7322276 -rw-r--r-- 1 danny staff 0 114 "Apr 22 18:10:02 2020" "Apr 22 18:10:02 2020" "Apr 22 18:09:52 2020" "Apr 22 18:09:52 2020" 4096 8 0 /private/var/folders/b1/ftm2whhj4mb3_c4nfjhq23z00000gn/T/flutter_hot_reload_test.cVbIHL/pubspec.yaml

stat -s /private/var/folders/b1/ftm2whhj4mb3_c4nfjhq23z00000gn/T/flutter_hot_reload_test.cVbIHL/pubspec.yaml
st_dev=16777221 st_ino=7322276 st_mode=0100644 st_nlink=1 st_uid=501 st_gid=20 st_rdev=0 st_size=114 st_atime=1587575402 st_mtime=1587575402 st_ctime=1587575392 st_birthtime=1587575392 st_blksize=4096 st_blocks=8 st_flags=0
```

**Comment by DanTup** [comment]
Wait - what is this?

https://github.com/flutter/flutter/blob/58811028a4896222ff85acec842d664f878fefe9/packages/flutter_tools/test/integration.shard/test_utils.dart#L23-L26

**Comment by DanTup** [comment]
Ok, weirdly the PR that added that (#48932 - FYI @jonahwilliams) was only created in January, which is before I saw this, but after this issue was opened 🤷‍♂️

**Comment by jonahwilliams** [comment]
Hopefully no outside of our own integration tests is depending on our test_utils library :)

**Comment by MeshkaniMohammad** [comment]
Same problem here. 
How to solve it?

**Comment by godofredoc** [comment]
Closing as obsolete.
