### ISSUE TITLE
Flutter tool should allow passing environment variables for web

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#44226]
This will enable users to use the CanvasKit backend on Flutter Web without needing a custom Flutter Engine build.

@jonahwilliams recommended this since it is more general than a specific flag to enable CanvasKit

**Comment by jmagman** [comment]
I just did something like this for Xcode build settings.
https://github.com/flutter/flutter/pull/43553

**Comment by CaseyHillers** [comment]
Is this done with https://github.com/flutter/flutter/pull/44083 landed?

**Comment by hterkelsen** [comment]
Yes!
