### ISSUE TITLE
Add tests for reflection based plugin registration on Android

### ISSUE THREAD

**Issue by xster** [flutter/flutter#44237]
Add tests for https://github.com/flutter/engine/pull/13698

**Comment by matthew-carroll** [comment]
@xster I never made it to this ticket, so FYI that someone should take care of this. Maybe @GaryQian or @jason-simmons

**Comment by goderbauer** [comment]
(triage) @xster Can you please assign this bug to somebody who is working on it or remove it from the march milestone. All bugs in milestones with a month should be assigned to people actively working on it.

**Comment by jonahwilliams** [comment]
Clearly we didn't need to do this
