### ISSUE TITLE
[video_player] await seekTo(Duration(seconds: 0)), and play(),The audio started playing again, but video still didn't start playing again

### ISSUE THREAD

**Issue by fantasy525** [flutter/flutter#44255]
## Steps to Reproduce

1. When the video ended, I invoke:
```
await _videoPlayerController. seekTo (Duration (seconds: 0));
_videoPlayerController. play ();
```
2. then The audio started playing again, but video still didn't start playing again,It stops at the last frame

**Target Platform:** IOS
**Target OS version/browser:** ios 12.4
**Devices:** iphone X

**flutter version** 1.7.8-hotfix4
**video_player** ^0.10.2+5

## Logs

```
```

```
```

```
```

**Comment by iapicca** [comment]
Hi @fantasy525 
could you please run 
`flutter channel stable`
`flutter upgrade`

If the issue still persist,
could you please provide your updated `flutter doctor -v`
and your `flutter run --verbose` as well.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by pascal-reuse** [comment]
Facing same issue. @iapicca: Could you solve this issue somehow?
