### ISSUE TITLE
How to open dark mode in Cupertino??

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#44273]
Tried wrapping inside a Theme with Brightness.dark but there is no effect..

How to make it work?

**Comment by LongCatIsLooong** [comment]
Yes `CupertinoThemeData(brightness: Brightness.dark)` is one way to enable dark mode. If you're using Cupertino widgets and `CupertinoTheme`, they are using dynamic colors by default and thus will change color automatically when you switch to dark mode if you didn't override their colors. The [`CupertinoDynamicColor`](https://master-api.flutter.dev/flutter/cupertino/CupertinoDynamicColor-class.html) class has a brief intro of supporting iOS 13 dark mode. Please let me know if it doesn't for you or you have any feedback regarding the API!

**Comment by jinfagang** [comment]
I haven't override color.

I just set CupertinoThemeData above my CupertinoTabBar widget

My whole app is inside CupertinoTabBar with 4 tabs switch between them.

But wrap that CupertinoTabBar doesn't make it's child CupertinoScaffold change color to dark.

**Comment by jinfagang** [comment]
How to set a value to make it change color globally for all CupertinoScaffold page?

**Comment by LongCatIsLooong** [comment]
`CupertinoPageScaffold.backgroundColor` defaults to [`CupertinoThemeData.scaffoldBackgroundColor`](https://master-api.flutter.dev/flutter/cupertino/CupertinoThemeData/scaffoldBackgroundColor.html), if you didn't give it a non-null value: https://api.flutter.dev/flutter/cupertino/CupertinoPageScaffold/backgroundColor.html 

Could you provide your `flutter doctor -v` and a minimal code sample to reproduce the problem, if it still doesn't work?

**Comment by jinfagang** [comment]
@LongCatIsLooong  I am not wrapping CupertinoThemeData for every CupertinoScaffold page.

I simply wrapped the root widget which CupertinoTabScaffold. I thought they can inherit from root? But actually all child cupertino doesn't change.

So, how to make them change globally?

**Comment by LongCatIsLooong** [comment]
`CupertinoPageScaffold` (or `CupertinoTabScaffold`) will look up the closest ancestor `CupertinoTheme`, you don't have to wrap everyone of them with a theme.

**Comment by parth22** [comment]
the date format in ios 13 look like 
![Image from iOS](https://user-images.githubusercontent.com/13308845/68367336-8ac46580-015b-11ea-8aa1-2890874a8fd2.png)

but when we apply widgets it's different
![Screen Shot 2019-11-07 at 12 39 31](https://user-images.githubusercontent.com/13308845/68367412-b47d8c80-015b-11ea-849b-4d3088f8379d.png)

My flutter doctor output:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.13.6 17G65, locale
    en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by jinfagang** [comment]
@parth22  Hi, how did u implement this modal style (previous page goes back and new page pop up with pushing first page down)?

**Comment by jinfagang** [comment]
@LongCatIsLooong  I am simplely using master branch flutter, upgrade yesterday.

**Comment by parth22** [comment]
> @parth22 Hi, how did u implement this modal style (previous page goes back and new page pop up with pushing first page down)?
> 
> I mean, 2 pages stack each other style?

no i'm using this widget for my start date and end date selection in one screen as a bottomsheet.

**Comment by jinfagang** [comment]
@LongCatIsLooong  Here is my code:


```
@override
  Widget build(BuildContext context) {
    return WillPopScope(
        // Prevent swipe popping of this page. Use explicit exit buttons only.
        onWillPop: () => Future<bool>.value(true),
        child: DefaultTextStyle(
          style: gDefaultTextStyleCupertino,
          child: CupertinoTheme(
            data: CupertinoThemeData(
              brightness: Brightness.dark,
            ),
            child: CupertinoTabScaffold(
              backgroundColor: Colors.black,
              tabBar: CupertinoTabBar(
                backgroundColor: globalNavBlackColor,
                border: Border(),
                onTap: (i) {
                  switch (i) {
                    case 0:
                      globalVoicePlayer.playClickSound1();
                      break;
                    case 1:
                      globalVoicePlayer.playClickSound2();
                      break;
                    default:
                      globalVoicePlayer.playClickSound1();
                      break;
                  }
                },
                activeColor: globalMainChatColor,
                items: <BottomNavigationBarItem>[
                  BottomNavigationBarItem(
                    icon: Icon(
                      Ionicons.getIconData("ios-chatbubbles"),
                      size: 22.0,
                    ),
                    // title: Text(
                    //   '聊天',
                    //   style: TextStyle(
                    //     fontFamily: gDefaultFontName,
                    //   ),
                    // ),
                  ),
                  BottomNavigationBarItem(
                    // icon: Icon(CupertinoIcons.profile_circled),
                    icon: Icon(
                      MyFlutterApp.comment_inv,
                      size: 21.0,
                    ),
                    // title: Text(
                    //   '72h聊',
                    //   style: TextStyle(
                    //     fontFamily: gDefaultFontName,
                    //   ),
                    // ),
                  ),
                  BottomNavigationBarItem(
                    // icon: Icon(CupertinoIcons.profile_circled),
                    icon: Icon(
                      MyFlutterApp.user_1,
                      size: 19.0,
                    ),
                    // title: Text(
                    //   '好友',
                    //   style: TextStyle(
                    //     fontFamily: gDefaultFontName,
                    //   ),
                    // ),
                  ),
                  BottomNavigationBarItem(
                    icon: Icon(
                      FontAwesome5.getIconData("fire",
                          weight: IconWeight.Solid),
                      size: 21.0,
                    ),
                    // title: Text(
                    //   'HotTrend',
                    //   style: TextStyle(
                    //     fontFamily: gDefaultFontName,
                    //   ),
                    // ),
                  ),
                  BottomNavigationBarItem(
                    icon: Icon(
                      MyFlutterApp.search,
                      size: 20.0,
                    ),
                    // title: Text(
                    //   'Explore',
                    //   style: TextStyle(
                    //     fontFamily: gDefaultFontName,
                    //   ),
                    // ),
                  ),
                  BottomNavigationBarItem(
                    icon: Icon(
                      MyFlutterApp.cog_1,
                      size: 21.0,
                    ),
                    // title: Text(
                    //   'Settings',
                    //   style: TextStyle(
                    //     fontFamily: gDefaultFontName,
                    //   ),
                    // ),
                  ),
                ],
              ),
              tabBuilder: (BuildContext context, int index) {
                // assert(index >= 0 && index <= 5);
                switch (index) {
                  case 0:
                    return CupertinoTabView(
                      builder: (BuildContext context) => TabPage1(),
                      defaultTitle: '$appName',
                    );
                    break;
                  case 3:
                    return CupertinoTabView(
                      builder: (BuildContext context) => HotTrendPage(),
                      defaultTitle: '$appName',
                    );
                    break;
                  case 1:
                    return CupertinoTabView(
                      builder: (BuildContext context) => TabPage6(),
                      defaultTitle: '72小时',
                    );
                    break;
                  case 2:
                    return CupertinoTabView(
                      builder: (BuildContext context) => TabPage2(),
                      defaultTitle: 'Contacts',
                    );
                    break;
                  case 4:
                    return CupertinoTabView(
                      builder: (BuildContext context) => TabPage3(),
                      defaultTitle: 'Expore',
                    );
                    break;
                  case 5:
                    return CupertinoTabView(
                      builder: (BuildContext context) => TabPage4(),
                      defaultTitle: 'Me',
                    );
                    break;
                }
                return null;
              },
            ),
          ),
        ));
```

Every CupertinoScaffold inside this tab.....

**Comment by jinfagang** [comment]
Is that because I am using a CupertinoTabView wrapped CupertinoScaffold?

**Comment by LongCatIsLooong** [comment]
@jinfagang you set the `CupertinoTabScaffold.backgroundColor` to `Colors.black`. Remove the `backgroundColor: Colors.black,` line to let the theme take control.

```
            child: CupertinoTabScaffold(
              backgroundColor: Colors.black,
              tabBar: CupertinoTabBar(
```

@parth22 this looks like a totally different issue. Could you create a new issue for it? https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=BUG.md&title=

**Comment by parth22** [comment]
@LongCatIsLooong thanks for reply i created new issue for now.
[#44412](https://github.com/flutter/flutter/issues/44412)

**Comment by jinfagang** [comment]
@LongCatIsLooong  Thanks for you reply. I have make all Tab child apply dark theme now.

However, when navigate a push to child page from Tab's child, the theme can not inherit from it's parent. Should I wrap a themedata in the end for all child of Tab's?

**Comment by LongCatIsLooong** [comment]
Yes new routes do not inherit from the widget that pushed them. You could either wrap them manually in a theme, or use an [`InheritedThme`](https://master-api.flutter.dev/flutter/widgets/InheritedTheme-class.html).

**Comment by jinfagang** [comment]
@LongCatIsLooong  Just wonder, since if we apply a dar theme then definitely we want all pages in dark, why not let pushed child page automactically inherit from page pushed them? Otherwise all child page should wrap a theme which is seems superfluous.
