### ISSUE TITLE
[in_app_purchase on] Can't subscribe to purchased event iOS

### ISSUE THREAD

**Issue by solokingjec** [flutter/flutter#44270]
Am using the latest version of in_app_purchase plugin with the latest stable flutter.
I can make purchases successfully (non consumable) but I can't subscribe to the purchased event on iOS. On android its okay. I can also Restore the purchase so its going through but the call back is not fired.

**Comment by iapicca** [comment]
Hi @solokingjec 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by solokingjec** [comment]
<img width="737" alt="Screenshot 2019-11-06 at 17 32 08" src="https://user-images.githubusercontent.com/6312641/68306887-69ac3800-00bb-11ea-928f-398f7aa905e5.png">
<img width="442" alt="Screenshot 2019-11-06 at 17 33 18" src="https://user-images.githubusercontent.com/6312641/68306974-8c3e5100-00bb-11ea-8721-141fa3cfe487.png">

**Comment by solokingjec** [comment]
@iapicca I can allow you via anydesk to my machine

**Comment by iapicca** [comment]
> @iapicca I can allow you via anydesk to my machine

I can't do that.
Thank you for your posting your `flutter doctor -v`

**Comment by solokingjec** [comment]
<img width="525" alt="Screenshot 2019-11-06 at 18 18 03" src="https://user-images.githubusercontent.com/6312641/68310928-dfb39d80-00c1-11ea-90bf-c5a7403a81c7.png">
<img width="451" alt="Screenshot 2019-11-06 at 18 18 21" src="https://user-images.githubusercontent.com/6312641/68310937-e3472480-00c1-11ea-9451-58cd34b88add.png">
<img width="737" alt="Screenshot 2019-11-06 at 17 32 08" src="https://user-images.githubusercontent.com/6312641/68310977-ed692300-00c1-11ea-8a8c-f8573f8ccde0.png">
<img width="442" alt="Screenshot 2019-11-06 at 17 33 18" src="https://user-images.githubusercontent.com/6312641/68310980-ee01b980-00c1-11ea-8a41-289af478a3a0.png">
<img width="533" alt="Screenshot 2019-11-06 at 18 17 00" src="https://user-images.githubusercontent.com/6312641/68310983-ee9a5000-00c1-11ea-978d-4694046cae9f.png">
<img width="569" alt="Screenshot 2019-11-06 at 18 17 16" src="https://user-images.githubusercontent.com/6312641/68310986-ef32e680-00c1-11ea-8a01-dada4721a1b0.png">
<img width="546" alt="Screenshot 2019-11-06 at 18 17 34" src="https://user-images.githubusercontent.com/6312641/68310988-efcb7d00-00c1-11ea-8000-951a860a13b3.png">

**Comment by solokingjec** [comment]
Did you find out why it behaves like this?

**Comment by solokingjec** [comment]
@iapicca have you been able to reproduce that issue.

**Comment by solokingjec** [comment]
Is this issue detected yet?

**Comment by mcagrigoktas** [comment]
Same issue only on iOS

**Comment by y-sihyeon** [comment]
Same issue only on iOS, too.

**Comment by stuartmorgan** [comment]
Screenshots of code make it extremely difficult to reproduce issues, since someone has to retype the entire program.

If this is still an issue in the current version of the plugin, which has changed significantly, please file a new issue and include a minimal reproduction case (as code, not images).
