### ISSUE TITLE
Document the new pubspec platforms schema and link to it in the pub tool

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#44287]
- [ ] Documentation should either go in the wiki, or [flutter.dev](https://flutter.dev/docs/development/packages-and-plugins/developing-packages).
- [ ] It should also be referred to from the pub tool warning here (this warning has been found to be confusing without further documentation of the new schema).

**Comment by jonasfj** [comment]
@mklim, @iskakaushik, are we happy using the link:
`https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin`

Then I can land that in the `pub` tool, and it can be updated later. A long as we agree that the new plugin format should be documented somewhere on that page, below the "Developing plugin packages" headline.

**Comment by mklim** [comment]
@jonasfj I think that makes sense to me, thanks for landing it. Linking to flutter.dev is preferable to the wiki for user facing information.

**Comment by jonasfj** [comment]
Didn't land it yet, but I'll start pushing the buttons.

**Comment by iskakaushik** [comment]
Thanks @jonasfj !

**Comment by amirh** [comment]
Done in https://github.com/flutter/website/pull/3303
