### ISSUE TITLE
Verify federated pubspec fields

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#44288]
We need to double check that the new pubspec fields introduced in https://flutter.dev/go/federated-plugins (see pubspec bits in [SUMMARY OF PROPOSED CHANGES](https://docs.google.com/document/d/1LD7QjmzJZLCopUrFAAE98wOUQpjmguyGTN2wd_89Srs/preview#heading=h.afnnwfq5shaj)) are not breaking. Adding them should be no-ops right now.

**Comment by cyanglaz** [comment]
Verified! I am closing the issue.

**Comment by amirh** [comment]
It seems like the implements field makes the tool to fail.
