### ISSUE TITLE
Hello_Services sample not working with Atom

### ISSUE THREAD

**Issue by qchong** [flutter/flutter#4429]
## Steps to Reproduce

1. Added the [hello_services](https://github.com/flutter/flutter/tree/master/examples/hello_services) sample project to Atom.
2. When I try to run, it shows the error "No application found for TargetPlatform.android_arm.
Is your project missing an android/AndroidManifest.xml?".

## Flutter Doctor

[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/quddusc/flutter
    • Framework revision 5af67e1592 (52 minutes ago), engine revision 034ae44419

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0-preview)
    • Android SDK at /usr/local/google/home/quddusc/Android/Sdk
    • Platform android-N, build-tools 24.0.0-preview
    • OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.2
    • dartlang plugin version 0.6.24

## Logs and Crash Reports

No application found for TargetPlatform.android_arm.
Is your project missing an android/AndroidManifest.xml?
exited with code 1

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by devoncarew** [comment]
It looks like `flutter_tools` requires the file android/AndroidManifest.xml to exist, and the hello_services project has it at android/app/src/main/AndroidManifest.xml.

**Comment by abarth** [comment]
Yeah, `hello_services` is a demo of a separate workflow from the Atom / flutter-tool workflow.  I'm working to integrate the two, but they aren't integrated yet.

The README.md file in `hello_serves` explains how to build and run the example.

**Comment by collinjackson** [comment]
For the codelab, we'd like the devs to start with a hello_services style project so that they can add sign-in and Firebase. This bug will prevent them from working in Atom in the earlier steps.

**Comment by devoncarew** [comment]
I ran through the readme.md to get a sense of what the hello_services workflow looks like, and what it would take to drive that style of project from flutter run. Here are some notes and issues I ran into:

- we need to be able to locate gradle (via an existing PATH or user configuration)
- the gradle script that I had installed (in my copy of Android Studio) did not have its executable bit set
- when I ran `gradle wrapper`, the generated `gradlew` script did not have its executable bit set
- the project's gradle config specifies version 2.10 - I have 2.2.1 installed
- the project's android/app/build.gradle file specifies android sdk v22/22.0.1, I have v23/23.0.2 installed
- we need to inject or verify if the flutter.sdk value exists in local.properties
- the apk gets built into android/app/build/outputs/apk/app-debug.apk
- installing the app via adb worked
- you need to pass the activity id into `flutter refresh` - we could instead recognize the project type and look in a different place for the android manifest file

**Comment by abarth** [comment]
This works on iOS now.  @devoncarew is going to look at the Android aspects of this issue.
