### ISSUE TITLE
issue in creating and running the first_app example

### ISSUE THREAD

**Issue by hussaind52** [flutter/flutter#44294]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform: Andriod
**Target OS version/browser: 
**Devices: Pixel 2

## Logs

[flutter_03.log](https://github.com/flutter/flutter/files/3816511/flutter_03.log)

```
```

```
```

```
```

**Comment by iapicca** [comment]
Hi @hussaind52 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/40517)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.

Also, please don't forget to accept the` Android licenses`
```
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Andriod
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
```

Thank you

**Comment by osunkoyadavid** [comment]
Accepted the licenses

**Comment by osunkoyadavid** [comment]
Still giving the error in cmd and vscode

**Comment by osunkoyadavid** [comment]
flutter cmd i meant
