### ISSUE TITLE
[PR placeholder] Share plugin: not positioned correctly on iPad after rotation

### ISSUE THREAD

**Issue by aanelson** [flutter/flutter#44293]
## Steps to Reproduce

1. Open Share example on iPad
2. Tap share
3. rotate device

**Target Platform: ios**
**Target OS version/browser: 12/13 tested would guess all**
**Devices: ipad**

## Logs

[✓] Flutter (Channel unknown, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/aaronelson/Library/flutter
    • Framework revision 2d2a1ffec9 (9 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/aaronelson/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPad Pro (9.7-inch) • D80CDFAC-A4BB-48FE-956D-7AE517DB54B7 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0
      (simulator)

• No issues found!

**Comment by iapicca** [comment]
Hi @aanelson 
could you pleasea minimal code sample to reproduce the problem,
thank you

**Comment by aanelson** [comment]
https://github.com/flutter/plugins/tree/master/packages/share

**Comment by stuartmorgan** [comment]
Closing, as share is now deprecated in favor of [share_plus](https://pub.dev/packages/share_plus).
