### ISSUE TITLE
Refactor our viewport logic into a new RenderObject subclass hierarchy

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4430]
Rather than use RenderBox for viewports, we should invent a new render object protocol that is used for lazy viewporting and scrolling.

This protocol would have:
- Inputs: main axis, main axis start offset, main axis end offset, cross-axis dimension
- Outputs: main axis layout size, main axis offset consumed, paint phase (top, header, content)
- Intrinsics: In some cases, we will need a way to enable intrinsic dimensions to propagate through (e.g. popup menus), but this is super expensive, so we should have a way to turn it on or off.

**Comment by abarth** [comment]
Started experimenting in https://github.com/abarth/flutter/tree/viewported

**Comment by abarth** [comment]
inputs: min/max of start/end offset, main axis, cross axis extent, anchor
outputs: main axis extent, start/end offset

**Comment by abarth** [comment]
This is now RenderViewport2.
