### ISSUE TITLE
Hard Coded Color Values for Material Date Picker

### ISSUE THREAD

**Issue by baylessj** [flutter/flutter#44316]
The Date Picker widget displayed with the `showDatePicker` function hard-codes the header text color values, making them impossible to fully customize in an application.

The relevant lines are here:  https://github.com/flutter/flutter/blob/369860bcf61d5516cf6e7f8bae653e05b2e5f174/packages/flutter/lib/src/material/date_picker.dart#L83-L92

It is possible to get the colors to match with the theme color, but it is not possible to set the text colors to a value besides the two possible for light and dark themes.

## Steps to Reproduce

**Target Platform:** Android
**Target OS version/browser:** Android 8.0
**Devices:** Samsung Galaxy S7

## Logs

```
➜ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.5 at /home/bayle/flutter
    • Framework revision 1aedbb1835 (3 weeks ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/bayle/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/bayle/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Android Studio (version 3.5)
    • Android Studio at /home/bayle/Documents/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • SM G930P • 6337a09d • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

**Comment by baylessj** [comment]
I'd be fine with creating a PR for this, but I'm not entirely confident on what the best plan would be for making this better. Would it be alright to use the `accentTextTheme` in the case of the light theme, and the `primaryTextTheme` in the case of the dark theme? I'm thinking that would still make the default look be readable without removing the user's ability to modify the text colors themselves.

**Comment by Hixie** [comment]
Date pickers have a whole theme system now.
