### ISSUE TITLE
Pass --write-service-info to every Android Dart isolate

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#44325]
Pass --write-service-info to every Android Dart isolate

Value should be "service_info.json"

**Comment by xster** [comment]
Can you add a bit more background for the reasoning?

**Comment by matthew-carroll** [comment]
@blasten would you mind providing that background?

**Comment by xster** [comment]
Is this for the attach?

**Comment by blasten** [comment]
Yep — this is to discover the observatory Uri.

**Comment by matthew-carroll** [comment]
Looks like we're going a different route to solve this problem. I'm going to close this issue.
