### ISSUE TITLE
[embedding] Upgrading Pre 1.12 Android Projects cause previous project bogs down

### ISSUE THREAD

**Issue by ZionPi** [flutter/flutter#44323]
I upgrade flutter to latest version, and reference share preferences in `pub spec.yaml` like,

> shared_preferences: ^0.5.3+4

debugger complains and l follow the link [Upgrading pre 1.12 Android projects](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)  from the logs.
 
My previously channel was written guided by [Add an Android platform-specific implementation using Java](https://flutter.dev/docs/development/platform-integration/platform-channels) ,and the code part is:

```
 new MethodChannel(getFlutterView(), CHANNEL).setMethodCallHandler(
                new MethodCallHandler() {
                    @Override
                    public void onMethodCall(MethodCall call, Result result) {
                        // Note: this method is invoked on the main thread.
                        // TODO
                    }
                });
```
since package`import io.flutter.app.FlutterActivity` is different from `import io.flutter.embedding.android.FlutterActivity;`,the first parameter `getFlutterView()`that was passed to `MethodChannel ` stops working. 
so I changed it from `getFlutterView()` to `this.flutterEngine!!.dartExecutor`,not sure if this is the correct way to initialize `MethodChannel`.
Also changed the way to `GeneratedPluginRegistrant` by overriding this method: 
```
 override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }

``` 
And  a part of the  log output :

```
[+1356 ms] D/FlutterActivityAndFragmentDelegate(17253): Setting up FlutterEngine.
[   +3 ms] D/FlutterActivityAndFragmentDelegate(17253): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
[ +179 ms] W/FlutterEngine(17253): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@49c3e94) but could not find and invoke the
GeneratedPluginRegistrant.
[   +1 ms] D/FlutterActivityAndFragmentDelegate(17253): Attaching FlutterEngine to the Activity that owns this Fragment.

```

**Comment by ZionPi** [comment]
Reverse operation suggested by  this [Upgrading pre 1.12 Android projects Wiki ](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) and `flutter clean`、 `flutter run` again solved the problem.

**Comment by 985211yygg** [comment]
@ZionPi  so ,how to  initialize MethodChannel ?

**Comment by ZionPi** [comment]
@985211yygg have you ever check [this](https://flutter.dev/docs/development/platform-integration/platform-channels) page ? `Step 3a: Add an Android platform-specific implementation using Java` tells you on how to ` initialize MethodChannel `.
