### ISSUE TITLE
After enabling web support… iOS simulators disappeared

### ISSUE THREAD

**Issue by CherukuriSiva** [flutter/flutter#44326]
I have followed below url and enabled web for my flutter application.

https://flutter.dev/docs/get-started/web

flutter channel master

flutter config --enable-web

flutter create .

flutter run -d chrome

flutter build web

Everything went well and I am able to launch my application on Web. However, after enabling web my ios simulators not appearing in devices list.

flutter devices 2 connected devices:

Chrome • chrome • web-javascript • Google Chrome 80.0.3955.4 dev

Web Server • web-server • web-javascript • Flutter Tools

flutter --version
Flutter 1.10.15-pre.424 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 289b4588f4 (21 hours ago) • 2019-11-06 02:51:17 -0500
Engine • revision 9726b4cb99
Tools • Dart 2.7.0

dart --version
Dart VM version: 2.6.0 (Thu Oct 24 17:52:22 2019 +0200) on "macos_x64"

**Comment by jonahwilliams** [comment]
I can't reproduce the issue:

```
jonahwilliams-macbookpro2:flutter jonahwilliams$ open -a Simulator.app
jonahwilliams-macbookpro2:flutter jonahwilliams$ flutter devices
Building flutter tool...
4 connected devices:

iPhone 11 Pro Max • 647BA2F4-7EA5-4846-B29B-35B6B4D2136D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
macOS             • macOS                                • darwin-x64     • Mac OS X 10.14.6 18G87
Chrome            • chrome                               • web-javascript • Google Chrome 78.0.3904.87
Web Server        • web-server                           • web-javascript • Flutter Tools
```

**Comment by yjbanov** [comment]
@CherukuriSiva, can you please try again on the latest Flutter?

**Comment by CherukuriSiva** [comment]
I did flutter upgrade. Still same. 

Siva-MacBook-Pro:f_groceries siva$ **flutter upgrade**
Upgrading Flutter from /Users/siva/Documents/development/flutter...
Updating fbabb264e..e7073f9a1
 .../lib/i18n/{stocks_en.arb => stocks_en_US.arb}   |    0
 .../lib/i18n/{stocks_es.arb => stocks_es_ES.arb}   |    0
 .../projectName.podspec.tmpl                       |    0
 347 files changed, 12913 insertions(+), 4228 deletions(-)
Building flutter tool...

Upgrading engine...
Downloading Android Maven dependencies...                           0.8s

Flutter 1.10.16-pre.113 • channel master • https://github.com/flutter/flutter.git
Framework • revision e7073f9a1f (4 hours ago) • 2019-11-09 17:08:53 -0800
Engine • revision 31cd2dfca2
Tools • Dart 2.7.0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.16-pre.113, on Mac OS X 10.13.6 17G65, locale en-AE)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 9.4.1)
    ✗ Flutter requires a minimum Xcode version of 10.2.0.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.3)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

Sivas-MacBook-Pro:f_groceries siva$ **flutter devices**
**2 connected devices:**

Chrome     • chrome     • web-javascript • Google Chrome 80.0.3955.4 dev
Web Server • web-server • web-javascript • Flutter Tools

I am using Channel Master.
Siva-MacBook-Pro:f_groceries siva$ **flutter channel**
**Flutter channels:**
  beta
  dev
* master
  stable

**Comment by yjbanov** [comment]
I think the issue might be this:

```
[!] Xcode - develop for iOS and macOS (Xcode 9.4.1)
✗ Flutter requires a minimum Xcode version of 10.2.0.
Download the latest version or update via the Mac App Store.
```

**Comment by yjbanov** [comment]
Would you mind upgrading your Xcode and trying again?

**Comment by CherukuriSiva** [comment]
Fixed.

I have updated my MacOS to Catalina and updated XCode to 11.2. Now the issue is fixed and I am able to see all devices.
