### ISSUE TITLE
[android] Kernel version used in flutter different with dependency in yaml file  of flutter tools 

### ISSUE THREAD

**Issue by ckdgit** [flutter/flutter#44329]
Question: Why is the kernel version used in the flutter SDK inconsistent with the kernel version in the yaml file in the flutter tools?

kernel    package:kernel/binary/ast_from_binary.dart  **readComponent()** throw error because version != Tag.BinaryFormatVersion, version = 29 , Tag.BinaryFormatVersion = 25
```
   int version = readUint32();
    if (version != Tag.BinaryFormatVersion) {
      throw InvalidKernelVersionError(version);
    }
```

flutter doctor :
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.13.6 17G2208, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

```

**Comment by iapicca** [comment]
Hi @ckdgit
could you please provide your `flutter run --verbose`/`flutter build --verbose` ?
Thank you

**Comment by ckdgit** [comment]
@iapicca 

The output log of flutter run --verbose is too big. Which piece of content do you need, I will post it below.
The problem is that I tried to use the kernel library in the flutter tools to convert the generated dill file into a Component object during the build process of the flutter tools. The exception is in the code above.

**Comment by iapicca** [comment]
Hi again @ckdgit 
is the exception you are referring to the `flutter doctor -v` output?
```
[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
```
if so did you follow the indication provided ?
thank you

**Comment by ckdgit** [comment]
Hi, thanks for you help!
yeah, I did, but I just use it to build Android App package.So it doesn't work for me. At present, I don't need to create IOS project, so this is not the problem I need to focus on now.

Back to the problem I mentioned at the beginning, this problem occurred when I went to debug flutter tools, and I found this exception. I don't know whether this is a problem or whether the team of flutter specifically did it. 
In addition, I generated another snapshot file, in which I modified the dependent kernel version to the corresponding one of dill file, which solved the problem, it works.

Can you analyze it for me,

**Comment by jonahwilliams** [comment]
Flutter uses whatever kernel version that the corresponding dart engine uses. The flutter_tools dependency on kernel is transitive via the analyzer, and unrelated to the build process
