### ISSUE TITLE
MouseRegion cannot work in ios device

### ISSUE THREAD

**Issue by ptrdu** [flutter/flutter#44330]
flutter version: v1.9.1+hotfix.6
device: iso 13, ios 12.6
problem:
The MouseRegion demo cannot work in the above devices.

[The demo](https://api.flutter.dev/flutter/widgets/MouseRegion-class.html#widgets.MouseRegion.1)

**Comment by iapicca** [comment]
Hi @ptrdu 
are you using a wireless mouse connected to your iPhone?
thank you

**Comment by ptrdu** [comment]
hello, thanks for answer. I run the demo in mac and iPhone 7 without other
devices, but neither work.

Francecsco Iapicca <notifications@github.com> 于2019年11月7日周四 下午7:17写道：

**Comment by iapicca** [comment]
Hi @ptrdu 
I apologize for the confusion,
the question I meant to ask was:
how are you connecting the mouse to your iPhone?
thank you

**Comment by ptrdu** [comment]
Hi, I test the demo without mouse, just tap and move in the screen. The
MouseRegion can only listen mouse event ?

Francecsco Iapicca <notifications@github.com> 于2019年11月7日周四 下午7:37写道：

**Comment by iapicca** [comment]
Hi @ptrdu 
you are correct, [MouseRegion](https://api.flutter.dev/flutter/widgets/MouseRegion-class.html) tracks the movements of a connected mouse,
I've tested on flutter web and works just fine.
You might want to take a look at the [Listener ](https://api.flutter.dev/flutter/widgets/Listener-class.html)class.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by ptrdu** [comment]
Thanks!

Francecsco Iapicca <notifications@github.com> 于2019年11月7日周四 下午7:56写道：
