### ISSUE TITLE
TextField overflow

### ISSUE THREAD

**Issue by aHalyk** [flutter/flutter#44333]
While using Textfields if you add text to the text field while someone is typing it resets the location the text is being entered to the very left of the text field. Not only that but it resets the out of bounds indicator for the Textfield when pushing the rest of the text ahead of the typing position, this causes text to be stuck into the text field forever.

## Usecase that provoked this: 
Attempting to insert a '-' into the string inside of a textfield controller as the typing occurs to produce a date format like this "yyyy-mm-dd" with the user only having access to digits.

## Textfield code
```dart
new TextField(
                      controller: dOBController,
                      keyboardType: TextInputType.numberWithOptions(decimal: false),
                      inputFormatters: [WhitelistingTextInputFormatter.digitsOnly],
                      onChanged: (text) {
                        print("Hit");
                        if(text.length == 4)
                        dOBController.text += "-";
                      },
                      decoration: new InputDecoration(
                        hintText: "Date of birth",
                      ),
                    ),
```

**Comment by janmoppel** [comment]
Hello @aHalyk !

Thank you for posting an issue.
Can you please also provide the `flutter doctor -v` command output?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
