### ISSUE TITLE
IndexedStack built only for widgets with the corresponding index

### ISSUE THREAD

**Issue by sh-ogawa** [flutter/flutter#44332]
## Use case

Now, All widgets specified as children of `IndexedStack` are built every time the index is changed.

```dart
Widget build(BuildContext context) {
  return IndexedStack(
    index: _index,
    children: [widget1(), widget2(), widet3()],
  );
}
```

So I have implemented the following to prevent all widgets from being built, but this is a very strange implementation.

```dart
List<Widget> _stack;
initState() {
  _stack = [widget1(), widget2(), widget3()]
}

Widget build(BuildContext context) {
  if (_index == 0) _stack[_index] = widget1();
  if (_index == 1) _stack[_index] = widget2();
  if (_index == 2) _stack[_index] = widget3();

  return IndexedStack(
    index: _index,
    children: _stack ,
  );
}

```

## Proposal

Maybe IndexedStack is built with MultiChildRenderObjectElement#update method.
I think the update method builds all the children's widgets, so can't be overridden for IndexedStack?

**Comment by iapicca** [comment]
Hi @sh-ogawa 
I'm not sure to I got it right,
are  you proposing to change in  `IndexedStack`
`updateRenderObject` from `RenderIndexedStack`
to `MultiChildRenderObjectElement`,
is that correct?

**Comment by sh-ogawa** [comment]
Hi @iapicca 

> are you proposing to change in IndexedStack
Yes, it is.

> updateRenderObject from RenderIndexedStack to MultiChildRenderObjectElement, is that correct?

When updating IndexedStack index, MultiChildRenderObjectElement#update is executed first to update the state using setState method.
After that, since IndexedStack#updateRenderObject is executed, it seems that all children are regenerated.

My suggestion to own update control in IndexedStack was wrong.

The correct suggestion is that we want the controller to be able to change the index like PageView.

**Comment by iapicca** [comment]
Thank you for the clarification @sh-ogawa

**Comment by tbm98** [comment]
If you set all of children is const then It work fine. but Widget must have a const constructor :(

**Comment by sh-ogawa** [comment]
One of the motivations for using IndexedStack is that you want to do something on the next page based on the screen set on the previous page.
In this case, there is no const qualifier.

**Comment by derekedelaney** [comment]
I have another scenario where this is an issue. If one of the widgets in my stack has a `ListTile` with a selectedTileColor. That color is persistent in the other widgets in the stack. Here is a DartPad with the example: https://dartpad.dev/f52f76eda42e8cae39aac949d9c0ba63?null_safety=true

**Comment by banderberg** [comment]
> If you set all of children is const then It work fine. but Widget must have a const constructor :(

Not on my app.  My stack widgets are all const and they all build every time index changes.

**Comment by banderberg** [comment]
> One of the motivations for using IndexedStack is that you want to do something on the next page based on the screen set on the previous page. In this case, there is no const qualifier.

Another motivation is using a bottom navigation bar

**Comment by Luard** [comment]
Is there any solution regarding this issue?

As a workaround you can generate the "stack" list of widgets on the fly. I'm using it for a Bottom Navigator.

For example, I'm using the `_screensStacked` with empty widgets (Containers) to prevent other widgets to be builded at the begining:
```dart
  static List<Widget> _screensStacked = <Widget>[
    const HomePage(), // This is the first one and is required for me.
    Container(), // Container used as an empty widget, use whatever here.
  ];
```
and then I have the valid list of widgets that will be used to replace `Containers` from `_screensStacked` on the fly depending on index value:
```dart
  static final List<Widget> _screensToBuild = <Widget>[ // This is the correct list of pages for the bottom navigator
    const HomePage(),
    const MyProfilePage()
  ];
```
Then, the `_screensStacked` can be recreated depending on the index like this:
```dart
if (_screensStacked.elementAt(index).runtimeType == Container) {
      _screensStacked[index] = _screensToBuild.elementAt(index);
}
```
So, only the index widget will be builded and the widget won't be rebuilded when index change again, so it keeps its states.

I'm using BLoC so this is how my `IndexStack` looks like:
```dart
body: BlocConsumer<BottomNavigationBarCubit, int>(
          listener: (context, state) {
            if (_screensStacked.elementAt(state).runtimeType == Container) {
              _screensStacked[state] = _screensToBuild.elementAt(state);
            }
          },
          builder: (context, state) {
            return IndexedStack(
              index: state,
              children: _screensStacked,
            );
          },
        ),
```

**Comment by goderbauer** [comment]
The `IndexedStack` is meant to size itself to the largest widget (even if that one is not visible). To do that, it has to build all of them. People here seem to be using IndexedStack for something else. I'd suggest filing a new issue describing that use case and then we can look for the right solution.
