### ISSUE TITLE
Rendering an AppBar changes the UI status bar style on iOS (dark mode)

### ISSUE THREAD

**Issue by vargavince91** [flutter/flutter#44347]
With iOS 13, users can toggle Dark Mode. One thing changing depending on the dark mode settings is the color of the icons in the status bar: network, WiFi, time, battery, etc. When the dark mode is enabled, the status bar icons are white, otherwise, they are black.

As I didn't want to drop everything I worked on, I wanted to temporarily force the `UIStatusBarStyle` to `UIStatusBarStyleDarkContent`. First I thought it worked, but then I noticed, that after being on some screens of the app, the icons toggled back to white.

After plenty of debugging, I could isolate the issue and I found a very strange behavior from Flutter. **Whenever an app bar is rendered, it messes up the status bar style on iOS: it changes the icons' color back to white, making it barely visible.**

The phone's in dark mode. I set the status bar style to dark in the `ios/Runner/Info.plist`:

```
<key>UIStatusBarStyle</key>
<string>UIStatusBarStyleDarkContent</string>
```

When the app starts, the UI status bar style gets the right color from the `Info.plist`: the icons and texts in the status bar are black. Notice that the first widget that my app renders does not have an app bar.

Then, I navigate to the next widget: a scaffold with an app bar. As you navigate there, the icons change colors and they are now white. When you go back, they remain white. Changing the `AppBar` parameters didn't help.

[**Repository with reproduction steps 🔗**](https://github.com/vargavince91/flutter_issue_44347)

<details>
  <summary>flutter doctor</summary>

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.10.7 at /Users/vince/development/flutter
    • Framework revision e70236e36c (5 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/vince/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.0.beta.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • White 6s • afb9d2343354cdcb2a7a0b0cf98b1f009357b48a • ios • iOS 13.1.1

! Doctor found issues in 1 category.
```

</details>

**Comment by LongCatIsLooong** [comment]
Thanks for the bug report and the repro code! This bug is currently being tracked here: https://github.com/flutter/flutter/issues/41067
