### ISSUE TITLE
Why use the module template when combining existing native project with flutter code?

### ISSUE THREAD

**Issue by durduman** [flutter/flutter#44349]
When integrating flutter into an already existing project (iOS) there are [these steps to follow][1].

But as an alternative we can also use:

`flutter create`

instead of:

`flutter create`**`-t module`**

and just add the classes, pods and what not from your original project in to the runner project that was create in the *ios* subfolder.

Why would creating a template module (-t module) and adding that module in the iOS project be the prefered way?

  [1]: https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

**Comment by xster** [comment]
@jmagman might correct me. Theoretically, flutter create should just be a strict superset of flutter create -t module (with flutter create having a more fleshed out iOS xcode project wrapper that you can tweak and own). 

But in implementation, there might be slight differences that we haven't fully tested against with the rest of the add-to-app flow. 

We should merge them one day once the https://github.com/flutter/flutter/issues/37910 cleanup is done.

**Comment by jmagman** [comment]
@durduman You could choose to organize your application in the way you describe.

Some apps are complex enough pre-Flutter that that migration overhead is too large.  For other apps, `flutter` is a small corner of the feature-set, and developers don't want to rearrange everything to match flutter's opinionated directory hierarchy.  Other developers want to [embed Flutter binaries](https://github.com/flutter/flutter/issues/36968) without requiring everyone on their large team to have `flutter` tooling installed.

**Comment by jmagman** [comment]
Essentially: You have the option of either add-to-Flutter or add-to-existing-app.  You should choose whatever is best for your project, app, and team.

There's a nod to some of this reasoning in https://flutter.dev/docs/development/add-to-app#add-to-app.

@xster is there more documentation to track here?

**Comment by xster** [comment]
There are likely minor technical differences with misaligned behaviors currently but I think we should probably not point out those differences if we erase those differences in behavior via https://github.com/flutter/flutter/issues/37910

**Comment by jmagman** [comment]
@durduman Essentially: you should do whatever is best for your project.  Add-to-app and add-to-Flutter are both supported.  If you can get away with having a full Flutter app, go for it!  If you need a more incremental approach, you can explore add-to-app.
Closing.
