### ISSUE TITLE
Proper font fallback mechanism for flutter_tester

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#44358]
Internal: b/144037028

Create an app with a Text widget which is assigned the "GoogleSans" font and that can contain multiple scripts. When running the app this is not an issue, as Flutter automatically falls back to another font for glyphs that it doesn't find in GoogleSans (for example, Arabic characters). However, this doesn't happen in widget tests, where those characters are missing instead.

We manually loaded an arabic font to flutter_tester. When we set an Arabic font in the widget's TextStyle, and this didn't change the behavior when running the app (I could still see both English and Arabic, though with the different font). However, tests now only displayed the Arabic, and were missing the Latin characters.

This leads me to believe that font fallbacks (per glyph) are either broken or missing in tests.

This is critical because it is blocking i18n and multi-language tests.

**Comment by jason-simmons** [comment]
What environment is the test running in?  If the text style's fonts can not handle a character, then the engine's text subsystem will fall back to a font manager that uses the host platform's font service.  But if that service is unavailable or isn't configured with any usable fonts, then fallback will fail.

`TextStyle` now supports explicitly naming fallback fonts through the `fontFamilyFallback` list.  Emebedding the fonts into the test and specifying `fontFamilyFallback` should be more reliable than using the host platform's fonts.

**Comment by mehmetf** [comment]
Just so I understand:

Let's say I bundled font families A, B and C in my app and tests. I have a Text widget that contains a multi-script text and specifies a single font family: A.

For each glyph, the engine will look at whether it can be rendered with A, if not, it does *not* fall back to B or C. Rather, it will fall back to the platform's font service. On Android, it might pick up some other font D. On linux host (flutter_tester), it might not find anything so fallback fails.

If we know that the text can be rendered via A or B, the only way to make the engine (anywhere) fall back to B is to specify B in the fontFamilyFallback.

Is this accurate?

**Comment by jason-simmons** [comment]
Yes, that's right
