### ISSUE TITLE
Hero transitionOnUserGestures: element is missing after double back gesture

### ISSUE THREAD

**Issue by radroot1** [flutter/flutter#44350]
Here's example https://gist.github.com/skabber/8dbf7cdee1431b13d8b87d8ff9075fa3
![untitled22](https://user-images.githubusercontent.com/38936506/68400872-2ec90380-0192-11ea-8d4e-98959983e56b.gif)
Flutter doctor
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
[✓] VS Code (version 1.35.1)
[✓] Connected device (2 available)

upd:

harder to encounter in iOS, but still possible 
![Untitled111](https://user-images.githubusercontent.com/38936506/68402117-41443c80-0194-11ea-9bb5-8d85582131e9.gif)

**Comment by TahaTesser** [comment]
Hi  @radroot1 
I tried to reproduce your issue but it works fine on iOS 
I used sample code https://gist.github.com/skabber/8dbf7cdee1431b13d8b87d8ff9075fa3

if you're still experiencing this problem with version of Flutter, please create a new issue and provide the information required in
the template.
Thank you
