### ISSUE TITLE
Unable to handel  PlatformException (PlatformException(ERROR_INVALID_VERIFICATION_CODE, The sms verification code used to create the phone auth credential is invalid. Please resend the verification code sms and be sure use the verification code provided by the user., null))

### ISSUE THREAD

**Issue by pawanyadav1589** [flutter/flutter#44364]
PlatformException (PlatformException(ERROR_INVALID_VERIFICATION_CODE, The sms verification code used to create the phone auth credential is invalid. Please resend the verification code sms and be sure use the verification code provided by the user., null))

**Comment by janmoppel** [comment]
Hello @pawanyadav1589 !

Thank you for posting an error message here.
Can you please also provide additional information such as an output of the `flutter doctor -v` command and minimal steps to reproduce this issue?
Thank you.

**Comment by pawanyadav1589** [comment]
thanks @janmoppel for the response . issue is resolved .

**Comment by shaharhn** [comment]
How did you resolve this problem ?
