### ISSUE TITLE
The "DriverOffset" class isn't being exported.

### ISSUE THREAD

**Issue by weixfeng** [flutter/flutter#44367]
Several APIs in the "driver.dart" file (living in "package:flutter_driver/flutter_driver.dart") have the return type of "DriverOffset", but the "DriverOffset" class isn't being exported in the "flutter_driver.dart" file.

export 'src/driver/driver.dart' show
  find,
  CommonFinders,
  EvaluatorFunction,
  FlutterDriver,
  TimelineStream;

So as a result, callers are not able to reference the "DriverOffset" class directly when calling those APIs in the "driver.dart" file (e.g. Future<DriverOffset> getCenter(SerializableFinder finder, { Duration timeout })).  The current workaround is to add the import statement below:

import 'package:flutter_driver/src/driver/driver.dart';

**Comment by iapicca** [comment]
Hi @weixfeng 
if I understand correctly 
you are suggesting to expose the `driver.dart` differently,
but I'm not sure what your proposal is;
could you please provide more details
thank you

**Comment by weixfeng** [comment]
Currently, it doesn't seem possible if I want to do something like below:

SerializableFinder testButton  =  find.text('My  Test Button');
driver.waitFor(testButton);
DriverOffset centerPoint = await driver.getCenter(testButton);

The line above is problematic because the "DriverOffset" type isn't available.  The getCenter() is a public API, whose return type is "Future<DriverOffset>", so the "DriverOffset" type should be also public:-).

**Comment by jonahwilliams** [comment]
DriverOffset has been exported for at least 7 months: https://github.com/flutter/flutter/blame/c5527dc8c49beb1998500dd968a7e8dfd963e169/packages/flutter_driver/lib/flutter_driver.dart#L30

Closing as fixed
