### ISSUE TITLE
Pesto: motion for the recipe going full screen

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4436]
https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B14F_FSUCc01UlJKVG9BVVFuMHM/GoodTransition_ClearDo-v3.webm

Looks like a few things are happening:
- Splash of ink across the image when tapped
- menu icon animates into a back icon
- recipe image and ingredients text grows to full screen
- the edit FAB animates out
- the favorite FAB animates in
- the app bar is pushed up and out

**Comment by sethladd** [comment]
cc @mpcomplete

**Comment by eseidelGoogle** [comment]
This needs a closer look.  Possibly should be punted from the first release as we have for other hero transition bugs (e.g. https://github.com/flutter/flutter/issues/4442)

**Comment by sethladd** [comment]
We've hidden Pesto.
