### ISSUE TITLE
App Store Connect Operation Error ERROR ITMS-90534: "Invalid Toolchain"

### ISSUE THREAD

**Issue by git-xbits** [flutter/flutter#44378]
Hi guys, I'm facing a problem with archive and upload files to Apple. I'ts archiving normally, but when XCode try upload the app, throw this exception:

> App Store Connect Operation Error
> ERROR ITMS-90534: "Invalid Toolchain. Your app was built with an unsupported version of Xcode or SDK. If you plan to submit this build to the App Store, make sure you are using the GM version of Xcode 10.1 and the SDK for iOS 12.1 and watchOS 5.1, Xcode 7.1 and the SDK for tvOS 9, or Xcode 6 and the SDK for macOS 10.9 or later. If you are using an Xcode beta version to test your app, make sure you are using the latest supported version. For more information about supported beta versions, view the App Store Connect What's New page (https://developer.apple.com/app-store-connect/whats-new/)."

Flutter doctor -v

>  [✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale pt-BR)
>     • Flutter version 1.9.1+hotfix.6 at /Users/phelipepalte/SDK/flutter
>     • Framework revision 68587a0916 (8 weeks ago), 2019-09-13 19:46:58 -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/phelipepalte/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.2)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.2, Build version 11B52
>     • CocoaPods version 1.8.4
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 41.0.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] Connected device (1 available)
>     • Carlos’s iPhone • bef6b1ebd20cee987a63e40bd3269c87027c959b • ios • iOS 12.4.3
> 
> • No issues found!

xcodebuild -showsdks

> iOS SDKs:
> 	iOS 13.2                      	-sdk iphoneos13.2
> 
> iOS Simulator SDKs:
> 	Simulator - iOS 13.2          	-sdk iphonesimulator13.2
> 
> macOS SDKs:
> 	DriverKit 19.0                	-sdk driverkit.macosx19.0
> 	macOS 10.15                   	-sdk macosx10.15
> 
> tvOS SDKs:
> 	tvOS 13.2                     	-sdk appletvos13.2
> 
> tvOS Simulator SDKs:
> 	Simulator - tvOS 13.2         	-sdk appletvsimulator13.2
> 
> watchOS SDKs:
> 	watchOS 6.1                   	-sdk watchos6.1
> 
> watchOS Simulator SDKs:
> 	Simulator - watchOS 6.1       	-sdk watchsimulator6.1

I already tried change IOS SDK version in Runner Project > Build Settings > Signing, change Right menu > Project Format, but nothing changes.

**Comment by lalo-vergel** [comment]
Same issue here. Two days ago I uploaded a build of the same app, no settings changed, to app store connect without issue. Now I can't. [I read here about a possible solution](https://stackoverflow.com/questions/44323009/cant-submit-apps-to-appstore-error-itms-90534-invalid-toolchain), I changed it to xcode 10 and tried, then to 11, but it didn't work. 

Under the error there is a warning asking to install xcode 11.2.1 or newer, but that version isn't even available as an update yet.

**Comment by owenkealey** [comment]
Same issue here.

**Comment by sergiomartell** [comment]
Also having the same problem.  With the warning to update to a version of Xcode not available yet.

**Comment by chenxianqi** [comment]
Apple：we have deprecated Xcode 11.2

**Comment by chenxianqi** [comment]
Please uninstall Xcode, And download new version 11.2.1 install https://download.developer.apple.com/Developer_Tools/Xcode_11.2.1_GM_Seed/Xcode_11.2.1_GM_Seed.xip

**Comment by git-xbits** [comment]
Downloading the beta to check out if resolve the problem.

**Comment by git-xbits** [comment]
Beta version resolve my problem. I'm closing now this Issue.

**Comment by OmarMahmoud120** [comment]
I have the same issue and cant switch to beta company roles

**Comment by trangiangnam** [comment]
I have same issue and cannot submit this application now.

**Comment by nikhiljha** [comment]
Can someone rehost the xip on Google Drive? Either Apple's download server is a potato or they have really bad peering with my ISP because I'm getting < 1 Mb/s.

**Comment by sandorjayko** [comment]
https://icetutor.com/question/app-store-app-uploading-failed-with-error-itms-90534-and-warning-itms-90703/

**Comment by tewshi** [comment]
I have two versions of Xcode, due to last year's rapid updates, 11.3 beta (11C24b) kept failing during upload, I used Version 11.2.1 (11B53) to upload and it was successful

**Comment by tewshi** [comment]
Xcode 11.3.1 11C504 (release) is now available, I'll get it today and try to see if it fixes the issue.
