### ISSUE TITLE
Get Fuchsia devices (NUCs) as a part of device lab

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#44374]
The scope of this issue is to have some NUCs be part of the device lab and be paved with the SDK that is downloaded as using `flutter precache --fuchsia`.

This will unblock us to run device lab tests as part of framework builds.

Context: Getting tests up and running as part of flutter tree is critical to having smooth rolls in GI.

cc: @godofredoc , @zanderso , @gw280

**Comment by godofredoc** [comment]
@iskakaushik what do you think about adding a recipe to run fuchsia devicelab tests using luci.flutter.tests pool? We would like to start moving some devicelab capacity to luci to start running tests on presubmit.

This is the list of things needed on the cocoon agent side:

- Add  FucshiaDeviceDeviceDiscovery and FuchsiaDevice in [adb.dart](inhttps://github.com/flutter/cocoon/blob/master/agent/lib/src/adb.dart#L85) file.
- Refactor [Run command to support the new device](https://github.com/flutter/cocoon/blob/master/agent/lib/src/commands/run.dart)
- Adapt existing tests or create new ones

Create a luci recipe that performs the following steps:

- Checks out flutter/cocoon
- Pave the fuchsia device
- Execute the test, e.g dart bin/agent.dart run -r HEAD -t analyzer_benchmark

A few extra things to consider:

- Tests collecting performance data will need to update the metrics back to flutter dashboard
- Capacity, how many tests are we planning to run and the duration of the test

**Comment by iskakaushik** [comment]
@godofredoc , thanks for the details. Un-assigning myself as I'm not sure if I will have cycles by the time this has to be done. Will talk to @kf6gpe and figure out the right owner for this.
