### ISSUE TITLE
Flutter tool fails on update_dart_sdk.sh

### ISSUE THREAD

**Issue by mjohnsullivan** [flutter/flutter#44376]
When running flutter command line tool on ChromeOS Linux shell, the following error is thrown:

/usr/local/flutter/bin/internal/update_dart_sdk.sh: line 24: [: b863200c37df4ed378042de11c4e9ff34e4e58c9: unary operator expected 

The line in the bash script is:

if [ ! -f "$ENGINE_STAMP" ] || [ "$ENGINE_VERSION" != `cat "$ENGINE_STAMP"` ]; then

**Comment by christopherfujino** [comment]
@mjohnsullivan is this only on ChromeOS? If you still have access to this setup, could you share the output of `flutter doctor -v` (and maybe `uname -a`)?

**Comment by christopherfujino** [comment]
Closing this as non-reproducable. If you have a reproducable example, feel free to re-open!
