### ISSUE TITLE
Flutter mac engine binaries should be codesigned on master branch

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#44372]
Currently, flutter macOS engine binaries are manually codesigned and notarized with Apple prior to each dev release. This issue is to track the process of automating this process for each Flutter engine commit (and thus making ensuring every framework commit on master has signed/notarized binaries).

**Comment by godofredoc** [comment]
We can start with moving the release branch bots to chrome internal and build from there.

**Comment by godofredoc** [comment]
We are tracking the signing of binaries on release candidate branches. Closing as obsolete.
