### ISSUE TITLE
Hot restart after compilation error leads to confusing compiler state

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#44384]
After hot restarting with a syntax error in a library, subsequent hot restarts will not pick up changes to the same library until the file is edited and changed via a hot reload.

a.dart
```
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class WidgetA extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(width: 10, height: 10, color: Colors.blue);
  }
}
```

main.dart
```
import 'package:flutter/material.dart';

import 'a.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return WidgetA();
  }
}
```

To reproduce:

Introduce a syntax error in `a.dart`, for example inserting a stray `;` above the class declaration of `WidgetA`. Save and perform a hot restart, this should show a compilation error:

```
lib/a.dart:3:2: Error: Unexpected token ';'.                            
;;                                                                      
 ^    
```

Now update `a.dart` to remove the syntax error and hot restart again. Then edit the container color to be Colors.red and perform a third hot restart. Observe that the color has not updated.

cc @HansMuller

**Comment by HansMuller** [comment]
Thanks for creating this issue; I've been bumping into the bug quite a bit!

**Comment by jonahwilliams** [comment]
cc @aam 

I did some more investigation, and the tool doesn't send any information about which libraries should be invalidated by a hot restart, all we do is re-issue a compile request to the frontend_server. It is possible we should be providing this information (though we never have) and that there is some sort of caching issue in the incremental compiler itself.

**Comment by jonahwilliams** [comment]
EDIT: I am confusing compile and recompile, still investigating

**Comment by jonahwilliams** [comment]
We do correctly send the libraries that need to be updated to the frontend server. For example, from a hot restart after a compiler error that does nothing:

```
[   +8 ms] Scanned through 454 files in 7ms
[        ] Syncing files to device iPhone 11 Pro Max...
[        ] Scanning asset files
[        ] <- reset
[        ] Compiling dart to kernel with 1 updated files
[        ] <- recompile package:hello_world/main.dart cdfc0c10-f93b-4790-8e61-9f4fa9caf0ae
[        ] package:hello_world/a.dart
[        ] <- cdfc0c10-f93b-4790-8e61-9f4fa9caf0ae

```

**Comment by jason-simmons** [comment]
This started when the incremental serializer was enabled in the frontend server: https://github.com/dart-lang/sdk/commit/8796723b82121fda380485d727c691defeba8846

@jensjoha

**Comment by jensjoha** [comment]
Oops. Fixed with https://dart-review.googlesource.com/c/sdk/+/124684/.

**Comment by jonahwilliams** [comment]
I believe this has rolled into flutter/flutter, marking as fixed. Thanks @jensjoha !
