### ISSUE TITLE
Flutter web throwing assertion from engine/surface/scene_builder.dart

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#44383]
```
Another exception was thrown: NoSuchMethodError: '<Unexpected Null Value>'
Another exception was thrown: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/scene_builder.dart:227:12
Another exception was thrown: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/scene_builder.dart:227:12
...

```

Originally filed in https://github.com/flutter/devtools/issues/1313. This is all the information that is printed in the console. May be related to https://github.com/flutter/flutter/issues/43931.

`flutter --version`:
```
Flutter 1.10.11-pre.488 • channel master • git@github.com:kenzieschmoll/flutter.git
Framework • revision cc9e9ce2ce (49 minutes ago) • 2019-11-07 14:06:07 -0800
Engine • revision c448d39d53
Tools • Dart 2.7.0
```

**Comment by taharushain** [comment]
My flutter project was working fine until recently, I upgraded it today and it's not working anymore :( Do we have a solution for this.

**Comment by roberto198907** [comment]
I am having problems with Flutter Web as well, my project was working correctly, after the upgrade it is not working more. I changed to Beta branch and Master, but for both don´t work.
![Screen Shot 2020-02-10 at 16 17 32](https://user-images.githubusercontent.com/48741699/74195476-e7cf2c00-4c20-11ea-8932-728bd829624a.png)

**Comment by roberto198907** [comment]
> My flutter project was working fine until recently, I upgraded it today and it's not working anymore :( Do we have a solution for this.

I had the same problem when I upgraded. I did not have further details about the error, so I started to test every part of the app, I found the last error oldSurface.isActive || oldSurface.isPendingUpdate was on a LinearGradient to a Container, I removed it and everything worked like before.

**Comment by ferhatb** [comment]
@ taharushain , @robertodevs , do you have a small reproducable example ?

**Comment by taharushain** [comment]
@ferhatb I don't have a reproducible example but by branches were messed up somehow, I did a clean setup and enabled Web after which it was working.

**Comment by markusaksli-nc** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
