### ISSUE TITLE
Flutter web STILL does not close Chrome properly on quit.

### ISSUE THREAD

**Issue by khari998** [flutter/flutter#44389]
I previously opened this issue here https://github.com/flutter/flutter/issues/43486

The fix seemed as if it was working when it was originally addressed. However, this is not the case. The issue is better than before because Chrome windows do not pile up endlessly in my dock. However,
even when using Ctrl + C in the terminal, I am getting these extra chrome windows that won't go away EVEN ON RESTART.

<img width="289" alt="Screen Shot 2019-11-07 at 7 05 48 PM" src="https://user-images.githubusercontent.com/40578958/68438284-a5193600-0191-11ea-9f8f-faa8032c4f34.png">

When looking closer at this, it seems as though it has something to do with keeping a maximum of 2 chrome windows in the dock. When quitting flutter web after there are two chrome windows, the behavior observed in the dock seems to be one chrome window disappearing before being replaced with another one. This keeps two chrome windows in the dock no matter how many times Flutter is web is closed. This is much better than endless chrome windows... But there should be 0 ghost chrome windows in the dock. Not 2. Even after restarting, the two chrome windows are still there.

I am running Mac OS Catalina 10.15.1 and Chrome 78.0.3904.97

Please eliminate all ghost chrome windows from sticking around after closing flutter web.

**Comment by jonahwilliams** [comment]
Does `ps aux | grep chrome` actually show multiple running chrome processes? I believe that section of the dock is only showing recently opened programs.

**Comment by khari998** [comment]
Hah. You would be correct. Must be a new Catalina feature. Never thought my OS would mimic a recent dev bug lol. I'm closing this. Flutter closes properly.
