### ISSUE TITLE
some services don't work without android:debuggable in the android manifest

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#4438]
In order to do things like discover active flutter apps on a device, the app has to have been built and run with `android:debuggable="true"` set in the android manifest. We probably want this setting on for debug/profile builds, and off for release builds.

Some options:
- set `android:debuggable="true"` for our generated flutter project. Warn the user (or fail the build) if they try and create a release version of the app with this flag present
- set `android:debuggable="true"` for our generated flutter project. Process the android manifest when creating a release build, stripping out (or toggling) the debuggable setting.

**Comment by eseidelGoogle** [comment]
See also https://github.com/flutter/flutter/issues/2138

**Comment by Hixie** [comment]
Does this happen automatically these days with Gradle?

**Comment by Hixie** [comment]
We don't seem to set this at all now?

cc @jonahwilliams

**Comment by jonahwilliams** [comment]
According to https://stackoverflow.com/questions/32687046/which-gradle-file-to-use-to-set-the-application-as-debuggable/32687308 , debuggable:true is the default for Gradle projects.

**Comment by jonahwilliams** [comment]
If I'm understanding the purpose of this bug correctly, this is fixed by virtue of using Gradle?

**Comment by jonahwilliams** [comment]
Closing as fixed
