### ISSUE TITLE
Refactor Dockerfile to improve efficiency

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#44394]
Our linux `Dockerfile` is not optimized. We can consolidate many of the steps to decrease overall image size, and also move some of the cirrus setup steps (in particular installing the skia gold tool) into the `Dockerfile` to speed up test runs.

**Comment by christopherfujino** [comment]
This is currently being blocked by https://github.com/flutter/flutter/issues/45351

**Comment by digiter** [comment]
Is this actionable now?

**Comment by christopherfujino** [comment]
Yes it is!

**Comment by godofredoc** [comment]
@christopherfujino is this obsolete now?

**Comment by christopherfujino** [comment]
yep
