### ISSUE TITLE
[google_maps_flutter] Polish issues

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#44390]
- [x] Some missing DartDocs:
-  MapCreatedCallback: google_map.dart:7:1
-  GoogleMap: google_map.dart:17:1
-  createState: google_map.dart:182:3
-  fromList: location.dart:98:3
-  init: controller.dart:17:3
-  toMap: camera.dart:54:3
-  fromMap: camera.dart:61:3
- [ ] (Blocked) this should be taken out of preview status after platform views are also taken out of developer's preview.

**Comment by bparrishMines** [comment]
Closing since https://github.com/flutter/plugins/pull/2303

**Comment by mklim** [comment]
Unfortunately this is still blocked on platform views being taken out of developer preview before it's totally resolved, so I'm reopening it. There isn't anything left to do here on the plugin itself though until the feature moves out of developer preview, so I've cleared the assignees for now.
