### ISSUE TITLE
Request to regen API docs

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#444]
Flutter appears to be on 0.0.20 (https://github.com/flutter/flutter/blob/master/packages/flutter/pubspec.yaml)

but the docs are for 0.0.14

https://domokit.github.io/docs/sky/

Thanks!

**Comment by abarth** [comment]
Will do.

**Comment by abarth** [comment]
Done.  Should show up on the site in a couple minutes.

**Comment by abarth** [comment]
... and its live.

**Comment by sethladd** [comment]
Thanks!
