### ISSUE TITLE
[url_launcher] Polish issues

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#44404]
- [ ] Needs more unit tests.
- [ ] `url_launcher_platform_interface` is missing some DartDoc.

**Comment by mklim** [comment]
@csells I improved one of the unit test cases that wasn't that robust, but in general the testing here already looked pretty good. Was there a particular code path that you saw that was missing coverage that you thought should be tested?

**Comment by csells** [comment]
When I measured it via 'flutter test --coverage', the unit test coverage for url_launcher was 65%. Are their scenarios that we're not testing?

**Comment by mklim** [comment]
@csells thanks, for letting me know about `flutter test --coverage`, I can see the issue now. There's some if/else checks inside the functions that the unit tests aren't hitting, I'll clean that up.
