### ISSUE TITLE
[flutter_driver_extension] doesn't allow keyboard "VirtualView node must not be the root node."

### ISSUE THREAD

**Issue by maheshmnj** [flutter/flutter#44409]
I had a working flutter project but suddenly the textfield stopped working,the problem is when I tap on the textfield the keyboard is in focus but I am unable to add text in it, neither the virtual keyboard pops up.I have tried running the same application on different flutter environment on ubuntu and also tried running this project on real android device but the issue exists.
you can take a look at the[ minimal flutter project here having the issue ](https://github.com/maheshmnj/flutter-textfield-issue) I have removed few dart files from it but the issue still exists.

heres a gif of the issue when I tap the textfield the virtual keyboard doesnt pop up neither can I type from my physical keyboard,however it allows copy/paste text into the textfield.
   
![Peek 2019-11-08 07-40](https://user-images.githubusercontent.com/31410839/68444561-3bcf0c80-01fd-11ea-8735-8e20f6c0c36d.gif)

heres the output of ```flutter doctor -v```
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.9.1+hotfix.4 at /home/al004/flutter_linux_v1.7.8+hotfix.4-stable/flutter
    • Framework revision cc949a8e8b (6 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/al004/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/al004/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/al004/android-studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8580
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

please do let me know if you need some additional info thanks in advance !

**Comment by iapicca** [comment]
Hi @maheshmnj 
I tested your app and I get this error:
`E/AccessibilityBridge( 1104): VirtualView node must not be the root node.`
while a simplified implementation of you `LoginPage`
works as intended

<details>
  <summary>sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  //  https://github.com/maheshmnj/flutter-textfield-issue => class LoginPage 

  @override
  Widget build(BuildContext context) => Scaffold(
    body: Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        Text("TextField / TextFormField not working",style: TextStyle(fontSize: 20),),
        TextField(),
        Container(
          height: 20,
        ),
        TextFormField(),
      ],
    ),
  );
}
```

</details>

It might be related to `package:flutter_driver/driver_extension.dart`
thank you for providing the sample code, it helps a lot

**Comment by taduvai35** [comment]
it is working in now,when i had removed flutter_driver extension.dart package

**Comment by maheshmnj** [comment]
Thankbyou

> Hi @maheshmnj
> I tested your app and I get this error:
> `E/AccessibilityBridge( 1104): VirtualView node must not be the root node.`
> while a simplified implementation of you `LoginPage`
> works as intended
> 
> sample
> It might be related to `package:flutter_driver/driver_extension.dart`
> thank you for providing the sample code, it helps a lot

Yes it works now after removing flutter_driver extension from main.dart thank you very much

**Comment by goderbauer** [comment]
In order to allow you to enter text from a test, the FlutterDriverExtension disables the keyboard and connects directly to the test.

You should not call `enableFlutterDriverExtension` from the main entry point of the app that you use for development and that you ship! Instead, create a separate entry point for driver tests that calls this method and then runs your app. For an example look at how we use flutter driver in the flutter_gallery:

* main entry point used outside of Flutter Driver tests: https://github.com/flutter/flutter/blob/6c4b38b7070ec3536e3192de49a09addfd305dac/examples/flutter_gallery/lib/main_publish.dart

* entry point for a driver test: https://github.com/flutter/flutter/blob/6c4b38b7070ec3536e3192de49a09addfd305dac/examples/flutter_gallery/test_driver/scroll_perf.dart
