### ISSUE TITLE
[video_player] Polish issues

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#44405]
- [ ] Missing DartDocs:
-  DurationRange: video_player.dart:17:1
-  startFraction: video_player.dart:23:3
-  endFraction: video_player.dart:27:3
-  VideoFormat: video_player.dart:35:1
-  initialized: video_player.dart:90:3
-  hasError: video_player.dart:91:3
-  aspectRatio: video_player.dart:92:3
-  copyWith: video_player.dart:94:3
-  DataSourceType: video_player.dart:133:1
-  textureId: video_player.dart:194:3
-  initialize: video_player.dart:197:3
-  dispose: video_player.dart:289:3
-  play: video_player.dart:308:3
-  setLooping: video_player.dart:313:3
-  pause: video_player.dart:318:3
-  seekTo: video_player.dart:387:3
-  createState: video_player.dart:458:3
-  VideoProgressColors: video_player.dart:506:1
-  createState: video_player.dart:599:3
- [ ] Needs more test coverage.
- [ ] example/README should be deleted.

**Comment by cyanglaz** [comment]
Assigning to @mklim after offline discussion. I can take it back if I have more free cycles next week.
