### ISSUE TITLE
Shrine: app bar is redraw when item grows to fullscreen

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4441]
Taking a look at https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B14F_FSUCc01emlGOWRnRkpMOVk/GoodTransition_QuickDo-v4.webm

On iOS build of gallery, it looks like the app bar flashes when I tap an item to go fullscreen. You can see the text "SHRINE" flash.

For a slow-mo video of the behavior, see https://drive.google.com/a/google.com/file/d/0B-w2rH1ryIJdVVF4SE5RRkJGVEE/view?usp=sharing

Protip: when viewing that slow-mo video, use playback controls to play it back at .5 speed. The effect is very noticable then.

**Comment by sethladd** [comment]
It looks like, when we tap on an item picture, we create a new app bar and start animating that up. Looking at the video from the material spec, it appears we should only be animating the image itself. The app bar stays in place and no new app bar is created.

**Comment by Hixie** [comment]
Yeah we need an iris wipe effect or some such.

**Comment by Hixie** [comment]
Oh actually I see from the first video you posted that there's a defined effect we're supposed to do involving moving the card up.

**Comment by HansMuller** [comment]
In the video the product card's text fades out as the card  moves/expands and then the card's new content fades in.  At the same time drawer button morphs into a non-standard back button. There's much to do here.

**Comment by eseidelGoogle** [comment]
Related to https://github.com/flutter/flutter/issues/4442, @HansMuller recommends punting this from the first gallery release.

**Comment by sethladd** [comment]
The gallery has this fixed. The app bar is not hero'd when an item transitions up.
