### ISSUE TITLE
io.flutter.embedding.android.FlutterActivity mode under 7.0 black screen

### ISSUE THREAD

**Issue by RootKatherine** [flutter/flutter#44416]
Flutter 1.9.1+hotfix.7-pre.1 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision e7527a1906 (3 weeks ago) • 2019-10-16 16:34:57 +0800
Engine • revision b863200c37
Tools • Dart 2.5.0

**Comment by RootKatherine** [comment]
android system below 7.1 ,use  io.flutter.embedding.android.FlutterActivity mode change page ,Activity trigger onstop resulting FlutterTextureView or FlutterSurfaceView happen destroy,then the page open black screen

**Comment by iapicca** [comment]
Hi @RootKatherine 
can you please provide your `flutter doctor -v` 
and `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by RootKatherine** [comment]
flutter doctor -v :

**Comment by RootKatherine** [comment]
flutter activty->A

**Comment by iapicca** [comment]
Hi again 
thank you for providing your flutter doctor
could you please provide also 
your `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thanks again

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
