### ISSUE TITLE
[Future already completed] Using xcode to achive ios IPA,always show error!!!

### ISSUE THREAD

**Issue by bianxiang** [flutter/flutter#44411]
Building AOT snapshot in release mode (ios-release)...          
Building App.framework for arm64...
Building AOT snapshot in release mode (ios-release)...             46.5s
Built to build/aot/.
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:39:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:523:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:878:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:885:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:906:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Failed to package /Users/bianxiang/swapwallet-app.
Command /bin/sh failed with exit code 255

**Comment by iapicca** [comment]
Hi @bianxiang 
I see that you described similar issues [[1](https://github.com/flutter/flutter/issues/42389), [2](https://github.com/flutter/flutter/issues/40734)]

you might wan to try following this possible [solution](https://github.com/flutter/flutter/issues/14866#issuecomment-549282198)
thank you

**Comment by iapicca** [comment]
Hi @bianxiang 
I see you opened a similar [issue](https://github.com/flutter/flutter/issues/42389)
Please follow up there.
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
