### ISSUE TITLE
 Custom android control Horizontal and vertical screen switching on some phones

### ISSUE THREAD

**Issue by webyouling** [flutter/flutter#44424]
W/PlatformViewsController(25585): Creating a virtual display of size: [1440, 2880] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1440, 720].
 W/OpenGLRenderer(25585):swapBuffers encountered EGL error 12301 on 0x6728ae80, halting rendering...
W/ContentCatcher(25585): Failed to notify a WebView
D/AndroidRuntime(25585): Shutting down VM
E/AndroidRuntime(25585): FATAL EXCEPTION: main
E/AndroidRuntime(25585): Process: com.xvideos.downlaod, PID: 25585
E/AndroidRuntime(25585): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.DisplayAdjustments android.view.Display.getDisplayAdjustments()' on a null object reference
E/AndroidRuntime(25585): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1760)
E/AndroidRuntime(25585): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1505)
E/AndroidRuntime(25585): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7353)
E/AndroidRuntime(25585): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1100)
E/AndroidRuntime(25585): 	at android.view.Choreographer.doCallbacks(Choreographer.java:895)
E/AndroidRuntime(25585): 	at android.view.Choreographer.doFrame(Choreographer.java:826)
E/AndroidRuntime(25585): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1086)
E/AndroidRuntime(25585): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(25585): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(25585): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(25585): 	at android.app.ActivityThread.main(ActivityThread.java:6864)
E/AndroidRuntime(25585): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25585): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(25585): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
