### ISSUE TITLE
SystemChrome.setPreferredOrientations does not force the device to the given orientation.

### ISSUE THREAD

**Issue by kanthi0802** [flutter/flutter#44420]
Below is the flutter doctor summary.

^C[✓] Flutter (Channel master, v1.10.16-pre.88, on Mac OS X 10.14.1 18B75, locale en-GB)
⣽Apples-MacBook-Pro:~ kanthis$ flutter doctor -v
[✓] Flutter (Channel master, v1.10.16-pre.88, on Mac OS X 10.14.1 18B75, locale en-GB)
    • Flutter version 1.10.16-pre.88 at /Users/kanthis/Documents/Flutter/flutter
    • Framework revision ff95b14ad8 (13 minutes ago), 2019-11-07 23:14:17 -0500
    • Engine revision 7ed9c9fc58
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kanthis/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Flutter requires a minimum Xcode version of 10.2.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.6.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 78.0.3904.87
    • Web Server                • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

**Comment by iapicca** [comment]
Hi @kanthi0802 
could you provide a a minimal code sample 
to reproduce the problem
thank you

**Comment by iapicca** [comment]
Hi @kanthi0802 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/40745)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
