### ISSUE TITLE
iOS app crashes when camera is streaming images

### ISSUE THREAD

**Issue by rsfarias** [flutter/flutter#44436]
iOS app is being terminated when camera streams images after a few seconds. I'm using the [camera](https://pub.dev/packages/camera) plugin, up to date. 

This problem occurred after I cherry-picked [9769754](https://github.com/flutter/flutter/commit/9769754d2) to fix a severe [black screen bug](https://github.com/flutter/flutter/issues/37155). I also tried to use the current beta, and the problem also occurs. 

Stable channel is fine, no crashes.

## Steps to Reproduce

1. Download the [example app](https://github.com/flutter/plugins/tree/master/packages/camera/example) from the camera plugin.
2. Create the following function in main.dart:
```
void _startStreamingImages() {
    controller.startImageStream((CameraImage image) {
      print('Got image... It will crash in a few seconds.');
    });
}
```
3. Call the function above after initializing the controller (line 205):
```
try {
      await controller.initialize();
      _startStreamingImages();
    } on CameraException catch (e) {
      _showCameraException(e);
}
```
4. Run the app and tap on the camera icon on the bottom left to start the camera.

**Target Platform:** iOS
Android seems to not crash.

## Logs

When run in VS Code, the app just crashes without an explanation, but when run in Xcode we get an error message "Terminated due to memory issue". 

```
[        ] Updating files
[ +354 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone de Rafael... (completed in 3,129ms, longer than expected)
[   +1 ms] Synced 0.8MB.
[   +2 ms] Sending to VM service: _flutter.listViews({})
[   +5 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x10382ea20, isolate: {type: @Isolate, fixedId: true, id:
isolates/2382924456970743, name: main.dart$main-2382924456970743, number: 2382924456970743}}]}
[   +1 ms] <- accept
[        ] Connected to _flutterView/0x10382ea20.
[   +4 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[        ] An Observatory debugger and profiler on iPhone de Rafael is available at: http://127.0.0.1:1112/2qM_6d78MMc=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+67235 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device
(file:///private/var/mobile/Containers/Data/Application/3C38DC63-3607-4510-B793-36A7E93E0F3A/tmp/examplengw0kp/example/)
[        ] Sending to VM service: _deleteDevFS({fsName: example})
[ +257 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +4 ms] "flutter run" took 119,432ms.
```

```
| => flutter analyze
Analyzing example...                                                    
No issues found! (ran in 6.6s)
```

```
| => flutter doctor -v
[✓] Flutter (Channel unknown, v1.9.1+hotfix.7-pre.1, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.9.1+hotfix.7-pre.1 at /Users/rfarias/marklii/dev/tools/flutter
    • Framework revision 2f4d8032ee (2 months ago), 2019-08-29 19:12:41 -0400
    • Engine revision 9a17d8e451
    • Dart version 2.5.0 (build 2.5.0-dev.3.0 35382f9b14)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rfarias/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone de Rafael • 89145d765c207c1177e7c84d57620d60d9d93cac • ios • iOS 11.2.1

• No issues found!
```

**Comment by Harshdeep4295** [comment]
Hi, @rsfarias Issue Resolved Yet? If you are using to scan something, try to use low Resolution, it works fine on IOS, for android you can use High resolution. Also, If you are using any dependence or ML kit with streaming, then surely put some delay for 500 milliseconds in case of android as some dependencies take time to load. As per the things I worked on.

**Comment by SubashManian** [comment]
Hi @Harshdeep4295 thanks for the solution.

But i'm using ML Kit for Bar Code scanning won't run iPhone 8 device while set it max resolution. if i set resolution to medium at the time it work's fine but can't able to scan the lower quality bar code in printed copies.

While i set it to max resolution for android it takes the resolution automatically based on the device configuration. but it's not work on iOS it leads to crash in iPhone 6, 7, 7 Plus, 6s, 6s plus, 8, 8 Plus

**Comment by aditya21** [comment]
I am facing same issue. Any solution?

**Comment by Harshdeep4295** [comment]
@aditya21 sorry for the delay.. the thing is you can run max resolution on iPhone 6,7, it actually doesn't work, add delay for some millisecond, and use low resolution... since app was crashing on iphone 6,7 for max resolution, so using low is what worked out for me.

**Comment by aditya21** [comment]
@Harshdeep4295 Thank you for the reply. Is there any way to catch this exception? so that I can prevent it from crashing and change the camera quality.

**Comment by Harshdeep4295** [comment]
Hi @aditya21, the app is crashing, or is it ending the process? in my case, I was scanning barcodes and move ahead, so the process was breaking. 
just try to encapsulate the process inside the try-catch I guess you might get the error there. or you can use **didHaveMemoryPressure** for getting memory leaks or pressure.

if you are just detecting, as soon as you get the first barcode just stop streaming, check for your condition and move ahead if your condition satisfies else restart stream, this particular case I used for iPhone 6 devices as continuous stream causes a crash for iPhone 6.

**Comment by sikandernoori** [comment]
Any Resolution for this Issue ?

IOS App crashes if ResolutionPreset is set to max on iPhone6,7, and 8.

Only ResolutionPreset low and medium works.

**Comment by Harshdeep4295** [comment]
Hi @sikandernoori , I dont think things have changed much. But what you can do is use ResolutionPreset.Medium for the below devices or you can check for how to reduce the frame rate in this case. As the main issue, I reached out to is that on low-end apple devices the frame rate is high as compared to what the device memory can handle... The way I did was, I took a snap every second and check whether what I was scanning is present there or not. Hope that can help you out as a workaround.

**Comment by sikandernoori** [comment]
Can't do both, 

In my case I've to perform OCR on live camera stream. 

With medium Quality OCR result is not so great and capturing image after 1 second will kill the purpose of App.

**Comment by roby2409** [comment]
yesss your problem same to me, camera plugin in flutter doesn't work on high resolution  for ocr

**Comment by renanyoy** [comment]
any update ?
