### ISSUE TITLE
Running vs Code debug on Ios (physical and emulator) crash on hot reload because of libusbmuxd 

### ISSUE THREAD

**Issue by arnaudelub** [flutter/flutter#44432]
As asked by @christopherfujino on [#35102](https://github.com/flutter/flutter/issues/35102) i'm opening a new issue

### Steps to Reproduce
Install libusbmuxd ca24570 or later
Do F5 to run VSCode debugger
### Logs

Message from Debug Console:

`Lost connection to device.
Exited (sigterm)`

This is the report from google crashlytics:

```
Fallo: io.flutter.1.ui
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000d1400050d8f
dart::Function::QualifiedName(dart::Object::NameVisibility) const
```

Flutter doctor -v:

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.6 18G95, locale ca-ES)
• Flutter version 1.9.1+hotfix.5 at /Users/arnaud/dev/flutter
• Framework revision 1aedbb1 (3 weeks ago), 2019-10-17 08:37:27 -0700
• Engine revision b863200c37
• Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
• Android SDK at /Users/arnaud/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.0
• ANDROID_HOME = /Users/arnaud/Library/Android/sdk
• Java binary at: /Users/arnaud/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 10.2.1, Build version 10E1001
• CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
• Android Studio at /Users/arnaud/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android Studio.app/Contents
• Flutter plugin version 36.1.1
• Dart plugin version 183.6270
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.6.0

[✓] Connected device (1 available)
• iPhone 8 Plus • 7D564F73-A954-4523-9CE4-2DA70AEE17F5 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @BadTasTe- 
could you please provide your `flutter run --verbose`
thank you

**Comment by BadTasTe-** [comment]
This is only happening when i'm running Vs code debug so the hot reload is performed on saving a file, (not by hitting the "R" key). Flutter run is actually working correctly.
So unless you know how to change the launch.json on vscode to add the verbosity on the debug mode, i  won't be able to reproduce this bug and having verbosity on.
Thank you

**Comment by iapicca** [comment]
Thank you for your answer @BadTasTe-

**Comment by DanTup** [comment]
> So unless you know how to change the launch.json on vscode to add the verbosity on the debug mode, i won't be able to reproduce this bug and having verbosity on.

If you run the **Dart: Capture Logs** command and tick only the **Flutter Run** option, it'll automatically enable verbose mode during the log capture. You can also add `args: ["-v"]` to your launch.json configuration to get verbose output without capturing logs.

**Comment by jmagman** [comment]
Are you still able to reproduce?  Is your app actually just crashing?  If so, can we get the crash log?

Window > Devices and Simulators > your device > View Device Logs.  Find the one matching the timestamp.

**Comment by arnaudelub** [comment]
Hi, i'll try to reproduce this bug and i'll give you the crash log.
Thanks

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
