### ISSUE TITLE
Unable to select image in iOS12.3 system landscape mode

### ISSUE THREAD

**Issue by zj126921** [flutter/flutter#44430]
Hey, in the ios12.3 system phone horizontal screen state, using image_picker: ^ 0.6.1 + 10 encountered problems when getting images from the album, enter the image directory in the album without displaying any images. The album interface is black, but I can quit the album. There is no error log.

**Comment by iapicca** [comment]
Hi @zj126921 
`flutter doctor -v` and 
a minimal code sample to reproduce the problem
thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
