### ISSUE TITLE
webview_flutter build ios fail 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by mofada** [flutter/flutter#44435]
After I run `flutter upgrade`, I tried to run ios but it build failed.

## Error log
```
Xcode's output:
↳
    In file included from /Users/fada/Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.15+1/ios/Classes/WebViewFlutterPlugin.m:5:
    /Users/fada/Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.15+1/ios/Classes/WebViewFlutterPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    1 warning and 3 errors generated.
    In file included from /Users/fada/Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.15+1/ios/Classes/FlutterWebView.m:5:
    /Users/fada/Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.15+1/ios/Classes/FlutterWebView.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/fada/Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.15+1/ios/Classes/FLTWKNavigationDelegate.m:5:
    /Users/fada/Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.15+1/ios/Classes/FLTWKNavigationDelegate.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description
```

## flutter doctor -v
```
fadadeiMac:~ fada$ flutter doctor -v
[✓] Flutter (Channel master, v1.10.16-pre.88, on Mac OS X 10.14.6 18G95, locale
    zh-Hans-CN)
    • Flutter version 1.10.16-pre.88 at /Users/fada/Library/flutter
    • Framework revision ff95b14ad8 (8 hours ago), 2019-11-07 23:14:17 -0500
    • Engine revision 7ed9c9fc58
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/fada/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/fada/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8580
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.7830
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • 发达的 iPhone • 9100d7b48c2681fccbf90fb6888ed04d25fe46e5 • ios        • iOS
      12.2
    • macOS      • macOS                                    • darwin-x64 • Mac
      OS X 10.14.6 18G95
```

**Comment by mofada** [comment]
Tried `flutter clean`, deleted `flutter/bin/cache`, delete `/ios/flutter`, no effect

**Comment by mofada** [comment]
```
Xcode's output:
↳
    In file included from /Users/fada/Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.15+1/ios/Classes/JavaScriptChannelHandler.m:5:
    /Users/fada/Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.15+1/ios/Classes/JavaScriptChannelHandler.h:12:40: error: expected a type
    - (instancetype)initWithMethodChannel:(FlutterMethodChannel*)methodChannel
                                           ^
    /Users/fada/Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.15+1/ios/Classes/JavaScriptChannelHandler.m:8:3: error: unknown type name 'FlutterMethodChannel'
      FlutterMethodChannel* _methodChannel;
      ^
    /Users/fada/Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.15+1/ios/Classes/JavaScriptChannelHandler.m:12:40: error: expected a type
    - (instancetype)initWithMethodChannel:(FlutterMethodChannel*)methodChannel
                                           ^
    /Users/fada/Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.15+1/ios/Classes/JavaScriptChannelHandler.m:29:17: warning: unused variable 'arguments' [-Wunused-variable]
      NSDictionary* arguments = @{
                    ^
    1 warning and 3 errors generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description
```

**Comment by iapicca** [comment]
Hi @mofada 
you might want to take a look at this possible [solution](https://github.com/flutter/flutter/issues/24428)
let me know if it worked for you
thank you

**Comment by mofada** [comment]
I feel like a plugin problem, you see the error message above, the one behind

**Comment by mofada** [comment]
I downgraded webview flutter to 0.3.14 and he is normal.

**Comment by iapicca** [comment]
Hi @mofada 
I'm glad that you found a work around,
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by braysonjohn148** [comment]
Am also getting the same error while running my app on IOS...help please
![Screenshot 2020-03-10 at 11 17 25](https://user-images.githubusercontent.com/41685357/76293349-f19c8b80-62c1-11ea-918a-d698163b6782.png)

**Comment by Leafyyuki** [comment]
I got the same issue today, I tried reinstall pod and this solution https://github.com/flutter/flutter/issues/24428, not worked for me.
I found some files missing in the folder "ios/Flutter/Flutter.framework", and the files in Flutter.framework could not be updated any more. So I tried the following steps, it worked for me.
```
1. create a new flutter project and run
2. copy the following new files in " ios/Flutter" into my old project
 - flutter_export_environment.sh
 - Flutter.framework
 - Flutter.podspec
3. flutter clean
4. flutter run
```

**Comment by darshankawar** [comment]
Hi @mofada are you still experiencing this issue on latest Flutter and `webview_flutter` plugin versions ?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by MehmetAtabey** [comment]
I have the same issue. How did you guys solve it ?  There is no any solution in any topic about this.

**Comment by iapicca** [comment]
@MehmetAtabey 
I recommend to open a new issue providing 
your `flutter doctor -v`, 
your `flutter build ios -v` 
and a minimal reproducible code sample

**Comment by mofada** [comment]
@darshankawar Oh, sorry, flutter has written less recently. I haven’t upgraded since I downgraded to 0.3.14, so I haven’t encountered this problem anymore.

**Comment by MehmetAtabey** [comment]
I just solved this issue from this topic : https://github.com/flutter/flutter/issues/15152#issuecomment-371124783
but I need to do it same process over and over again for my every build. And this is realy annoying.

**Comment by KumarHalder** [comment]
The above techniques did not work for me. 
What worked for me -> 

Go to the file location where it says the error. For example mine says->
` Documents/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/ios/Classes/FLTCookieManager.h:5:9:
    fatal error: 'Flutter.h' file not found
    #import <Flutter.h>`

Go to  "Documents/flutter/.pub-cache/hosted/pub.dartlang.org" and delete "webview_flutter-1.0.7" folder. 

Then run following command in project folder. 
`flutter pub get`

**Comment by bdezso** [comment]
> The above techniques did not work for me.
> What worked for me ->
> 
> Go to the file location where it says the error. For example mine says->
> ` Documents/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/ios/Classes/FLTCookieManager.h:5:9: fatal error: 'Flutter.h' file not found #import <Flutter.h>`
> 
> Go to "Documents/flutter/.pub-cache/hosted/pub.dartlang.org" and delete "webview_flutter-1.0.7" folder.
> 
> Then run following command in project folder.
> `flutter pub get`

It's worked for me, thanks.

**Comment by MrVipinVijayan** [comment]
Nothing worked for me.

**Comment by Sagar-Chhapara** [comment]
After upgrading project to flutter v2 if you get that error then you need to override webview_flutter to latest

**add below lines in pubspec.yaml**
```
dependency_overrides: 
  webview_flutter: 2.0.4
```
**And add **flutter_additional_ios_build_settings(target)** line in podfile**
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
   " "
   " "
   " "
```

**Comment by galangajisusanto** [comment]
> After upgrading project to flutter v2 if you get that error then you need to override webview_flutter to latest
> 
> **add below lines in pubspec.yaml**
> 
> ```
> dependency_overrides: 
>   webview_flutter: 2.0.4
> ```
> 
> **And add **flutter_additional_ios_build_settings(target)** line in podfile**
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>    " "
>    " "
>    " "
> ```

it's worked for me, thanks
