### ISSUE TITLE
Add support for CSP in Flutter for web

### ISSUE THREAD

**Issue by billy1380** [flutter/flutter#44439]
## Steps to Reproduce

1. Build a flutter app using flutter build web
2. Create a firefox plugin that loads the index.html into a popup

**Target Platform:**
Web
**Target OS version/browser:**
Firefox/Linux

## Logs

```
EvalError: call to Function() blocked by CSP in main.dart.js
```

```
Analyzing num_flutter_app...                                            

   info • Avoid using web-only libraries outside Flutter web plugin packages • lib/helper/web/uihelper.dart:1:1 •
          avoid_web_libraries_in_flutter
   info • The value of the field '_query' isn't used • lib/page/lookupformpage.dart:34:10 • unused_field
  error • Undefined name 'KeywordLookupPage' • lib/page/lookupformpage.dart:381:22 • undefined_identifier

3 issues found. (ran in 2.3s)
```

```
[✓] Flutter (Channel master, v1.10.16-pre.67, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.10.16-pre.67 at /home/billy1380/git/flutter-linux/flutter
    • Framework revision e3742b6e41 (33 hours ago), 2019-11-06 23:13:17 -0500
    • Engine revision c448d39d53
    • Dart version 2.7.0

⣽Error 1 retrieving device properties for ro.product.cpu.abi:
error: insufficient permissions for device: user in plugdev group; are your udev rules wrong?
See [http://developer.android.com/tools/device.html] for more information


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/billy1380/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/billy1380/android-sdk-linux
    • ANDROID_SDK_ROOT = /home/billy1380/android-sdk-linux
    • Java binary at: /home/billy1380/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 9.0.0
    • GNU Make 4.2.1

[✓] Android Studio (version 3.5)
    • Android Studio at /home/billy1380/Downloads/android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.6.0

[✓] Connected device (4 available)
    • 891Y036PE  • 891Y036PE  • android-arm    • Android null (API null)
    • Linux      • Linux      • linux-x64      • Linux
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.70
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

```

**Comment by iapicca** [comment]
Hi @billy1380 
given the error  `error • Undefined name 'KeywordLookupPage' • lib/page/lookupformpage.dart:381:22 • undefined_identifier`
would be useful if you could provide a minimal code sample to reproduce the problem
thank you

**Comment by billy1380** [comment]
@iapicca 

No worries... if there is any chance that it is something within the project causing the error as opposed to a framework issue I might be worth me checking whether I can create a new flutter project and wrap it with an extension manifest etc. to see if that causes the same error.

I will post a repo link here shortly.

**Comment by billy1380** [comment]
@iapicca 
Pushed basic/starter flutter project to https://github.com/billy1380/flutter_firefox_extension
The same error still happens.

The extension is in the extension folder: no need to build it. Just install the the manifest.json into firefox in about:debugging#/runtime/this-firefox.

To see the error:
1.  "Inspect" the extension after installing it
2. Click on the flutter icon in the toolbar

The popup should fail to load and you should see the error in the console.

Many thanks for taking a look.

**Comment by jonahwilliams** [comment]
`dart2js` supports building code in CPS mode:

```
dart2js -h -v
...
  --csp
    Disable dynamic generation of code in the generated output. This is
    necessary to satisfy CSP restrictions (see http://www.w3.org/TR/CSP/).
```

It sounds like this might be necessary for building an extension on firefox. Its not exposed currently, but you could hack it into the local version of the flutter tool here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_system/targets/web.dart#L134 and then rebuild the snapshot with `rm bin/cache/flutter_tools.*`

At any rate, we could probably add that as an option to `build web`
