### ISSUE TITLE
Issue from website page 起步: 体验

### ISSUE THREAD

**Issue by fumengdegithub** [flutter/flutter#44433]
Downloading ios-release tools 是怎么回事？
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
这些都配置了，但是Downloading ios-release tools  一直这样, ios 无法运行起来

**Comment by iapicca** [comment]
Hi @fumengdegithub 
can you please describe the issue in detail
and provide your `flutter doctor -v`
thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
