### ISSUE TITLE
Future<bool> - Undefined name 'context'.

### ISSUE THREAD

**Issue by artudtu** [flutter/flutter#44446]
I am trying to write a Future<bool> for WillPopScope and I am getting an Undefined name error for 'context'

I am new to flutter and coding and tried researching google why this is happening and can't find the answer. Is there anyone that can help me with this?

```
Future<bool> _onBackPressed() {
    return showDialog(
      context: context, // The second 'context' on this line is causing the error.
      builder: (context) => AlertDialog(
        title: Text("text"),
        actions: <Widget>[
          FlatButton(
            child: Text("more text"),
            onPressed: () => Navigator.pop(context, false),
          )
        ],
      ),
    );
  }
```
![image](https://user-images.githubusercontent.com/57537007/68491529-089a7680-0219-11ea-9b7a-6b151e1e2b5d.png)

**Comment by joaovictorpsantos** [comment]
@artudtu , In this case, you must get the context by parameter, for example:

![image](https://user-images.githubusercontent.com/31141391/68495953-07287880-0230-11ea-878c-492548f4d558.png)

**Comment by mannprerak2** [comment]
@joaovictorpsantos any idea why context at Navivator.pop isn't marked as red but showDialog context is ?

**Comment by mannprerak2** [comment]
@artudtu just do this
```
onWillPopScope: () {
 return onBackPressed(context);
}
```

**Comment by artudtu** [comment]
Thank you. That fixed the error. However, the app is still not working as desired. I guess I will study more and come back to this. Thank you everyone that responded!
