### ISSUE TITLE
flutter_driver timeout is limited at 30s

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter#44442]
I want to test my app, it must call some api and take about 1 minute but flutter_driver set max of timeout is 30s, I can't test my app . :(

**Comment by nknezevicpr** [comment]
You can override test timeout. Test timeout is optional parameter, check test() method. Here's an example: 

**test('test_description',  () async  {
  // your_test_code
  }, timeout: Timeout(Duration(seconds: 300)));**

**Comment by tbm98** [comment]
oh my bad.
it worked. thank you !
