### ISSUE TITLE
CupertinoDarkTheme text under container does not change color

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#44443]
I am using a dark theme for CupertinoScaffold, the navbar and navbar text work well change color.

And the container changes color to black when dark theme on, but the text doesn't change color according to theme change:

![image](https://user-images.githubusercontent.com/21303438/68484077-9dcc5800-0277-11ea-8afe-da0b9ae70c2a.png)

As you can see, it keeps black when dark theme on, is that a bug or text doesn't support dynamic color? Or am I misusing it?

**Comment by janmoppel** [comment]
Hello @jinfagang !

Thank you for posting an issue.
Can you please also post your `flutter doctor -v` command output?

Your question seems to be a good fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) as well. Flutter has a very active and helpful community there, so feel free to post it there too.

Also, see other support options here: https://flutter.dev/community

**Comment by HansMuller** [comment]
CC @LongCatIsLooong
