### ISSUE TITLE
First-party plugins should use e2e plugin for integration testing

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#44450]
Right now some first-party plugins are using the Flutter driver extension, e.g. Google Maps:

https://github.com/flutter/plugins/blob/abb77340fcff49cffd1e48985e87fd7b4eaf5b84/packages/google_maps_flutter/example/test_driver/google_maps_test.dart

We should upgrade all of them to use e2e plugin for Dart integration tests.

**Comment by cyanglaz** [comment]
Push the milestone back as it is not as high priority.

**Comment by CoreyCole** [comment]
@collinjackson are there any plugins with e2e tests that are more extensive? The google maps test you linked doesn't give much of an example to work off of. I'm interested in learning more about e2e testing using the flutter driver so I can use it in my project. Once I'm more comfortable with it, I could be interested in making some e2e tests for the first party plugins.

**Comment by cyanglaz** [comment]
I think this is done. Closing the issue.
