### ISSUE TITLE
`flutter build web` exports nothing

### ISSUE THREAD

**Issue by rocboronat** [flutter/flutter#44453]
An application that works fine on debug when running `flutter run -d chrome`, doesn't work on release when running `flutter build web`. When compiling the release version, it just says:

```
C:\Projects\theproject>flutter build web
Compiling lib\main.dart for the Web...                              1,9s

C:\Projects\theproject>
```

And that's it. Inside /web I just have the `index.html` file, that points to a `main.dart.js` that doesn't exist.

**Comment by jonahwilliams** [comment]
Please include the output of `flutter doctor -v` and verbose logs from `flutter build web -v` to help us diagnose the issue, thanks!

**Comment by adityadroid** [comment]
> An application that works fine on debug when running `flutter run -d chrome`, doesn't work on release when running `flutter build web`. When compiling the release version, it just says:
> 
> ```
> C:\Projects\theproject>flutter build web
> Compiling lib\main.dart for the Web...                              1,9s
> 
> C:\Projects\theproject>
> ```
> 
> And that's it. Inside /web I just have the `index.html` file, that points to a `main.dart.js` that doesn't exist.

I think you're checking `<project-dir>/web` . The output will be inside the `<project-dir>/build/web` folder. Check [this](https://flutter.dev/docs/get-started/web#generate-a-release-build)

**Comment by rocboronat** [comment]
Full of shame. I couldn't see further than the `/web` folder, that it's obviously something like the `/android` or the '/ios' folder. Thanks a lot, @adityadroid, and sorry for wasting your time, @jonahwilliams :)

**Comment by jonahwilliams** [comment]
Don't worry about it! :)
