### ISSUE TITLE
Shrine: opening and closing an item spikes dart, gpu

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4445]
On Android, with `--release`.

Open gallery, shrine, tap an item's image. Then tap the back icon in the upper right. Repeat.

Notice the spikes that occur:

![screenshot_20160607-174836](https://cloud.githubusercontent.com/assets/5479/15879344/4d89acc6-2cd8-11e6-9e1a-d34533fc30d4.png)

**Comment by eseidelGoogle** [comment]
This is likely the same as https://github.com/flutter/flutter/issues/4501?

**Comment by abarth** [comment]
After https://github.com/flutter/flutter/pull/5015, the transition is smooth except for a hitch at the end.

**Comment by abarth** [comment]
(sorry, at the beginning)
