### ISSUE TITLE
Enable apk_invalidation_test on Windows

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#44455]
This test demonstrates that https://github.com/flutter/flutter/issues/16604 is likely fixed for Android.

**Comment by filiph** [comment]
Hi, I'm removing the `a: annoyance` tag, at least for now. I try to reserve that tag only for the most widespread, frequently seen issues (see [definition](https://github.com/flutter/flutter/wiki/Triage#labels)).
