### ISSUE TITLE
Implement Contextual Action Bar (and ActionMode) in material design libraries.

### ISSUE THREAD

**Issue by bobajeff** [flutter/flutter#44464]
## Use case
I want to be able to declare a Contextual Action Bar that replaces the AppBar (in a smooth animation) when I'm selecting items in a List or Grid like described in here: https://material.io/components/app-bars-top/#contextual-action-bar

> ### Contextual action bar 
> 
> **Usage**
> A top app bar can transform into a contextual action bar to provide contextual actions to selected items. For example, upon user selection of photos...
> 
> A top app bar can transform into a contextual action bar to provide contextual actions to selected items. For example, upon user selection of photos from a gallery, the top app bar transforms to a contextual app bar with actions related to the selected photos.
> 
> When a top app bar transforms into a contextual action bar, the following changes occur:
> 
> - The bar color changes
> - Navigation icon is replaced with a close icon
> - Top app bar title text converts to contextual action bar text
> - Top app bar actions are replaced with contextual actions
> 
> Upon closing, the contextual action bar transforms back into a top app bar.
>  ![topappbars-behavior-transformation](https://user-images.githubusercontent.com/8573364/68504790-6afc7280-022b-11ea-80c8-a0fb856b26b9.gif)
> Top app bar transforming into a contextual action bar
> 

## Proposal
There should be a function to trigger the action mode (replacing the app bar with it). Somethings like `startActionMode()` described here:
https://developer.android.com/guide/topics/ui/menus#CAB

It should be made as it's own Widget and be a property of the Scaffold class (like the AppBar):
```dart

int _selected;

Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(
      title: const Text('Sample Code'),
    ),
    contextualActionBar: ContextualActionBar(
      selectedCount: _selected,
      actions: <Widget>[
        IconButton(
          icon: const Icon(Icons.delete),
          onPressed: () { deleteSelectedItems() },
        ),
      ],
    ),
    body: Center(
      child: Text('Hello World')
    ),
  );
}
```

**Comment by De-Morgan** [comment]
You can use this workaround package for now.
https://pub.dev/packages/contextualactionbar

**Comment by Piinks** [comment]
Closing as there is a published package for this feature.
Contextual Action Bar is also no longer part of the material specification, so we are unlikely to add it.
