### ISSUE TITLE
Have the FontLoader tell the PaintingBinding _systemFonts to notify its listeners

### ISSUE THREAD

**Issue by clocksmith** [flutter/flutter#44460]
This will result in so the RenderParagraphs repainting with the new font. It can be triggered by calling:

PaintingBinding.instance.handleSystemMessage({'type': 'fontsChange'});

May just need to add that after awaiting FontLoader.load

**Comment by chunhtai** [comment]
@clocksmith do you have a code example that i can test if my fix works?

**Comment by johnsonmh** [comment]
Here's a reproducible code sample:

The below app only works on the _first build_ when you uncomment the `PaintingBinding` line. 
```dart
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;

Future<ByteData> fetchFont() async {
  final response = await http.get(
      'https://raw.githubusercontent.com/google/fonts/master/ofl/montserrat/Montserrat-Light.ttf');

  if (response.statusCode == 200) {
    return ByteData.view(response.bodyBytes.buffer);

  } else {
    // If that call was not successful, throw an error.
    throw Exception('Failed to load font');
  }
}

void main() {
  var fontLoader = FontLoader('Montserrat');
  fontLoader.addFont(fetchFont());
  fontLoader.load().then((_) {
//    PaintingBinding.instance.handleSystemMessage({'type': 'fontsChange'});
  });

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Custom Fonts',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Custom Fonts')),
      body: Center(
        child: Text(
          'Montserrat is displayed here',
          style: TextStyle(fontFamily: 'Montserrat'),
        ),
      ),
    );
  }
}
```

**Comment by johnsonmh** [comment]
Also, I think there's something funny going on with web. When I try the above example on web with longer text and the `PaintingBinding.instance.handleSystemMessage({'type': 'fontsChange'})` line uncommented, it doesn't quite work on web. 

![Screen Shot 2019-12-02 at 3 53 28 PM](https://user-images.githubusercontent.com/4229329/69994543-14c5db00-151c-11ea-97fd-4343babc851b.png)


I don't think it's rebuilding quite right. Although as soon as I resize the window by any amount, it rebuilds and looks correct.

**Comment by chunhtai** [comment]
@johnsonmh the web issue you mentioned above is a separate issue. I file this bug https://github.com/flutter/flutter/issues/47236
We can continue the discussion there. For this issue, let's focus on the FontLoader should notify PaintingBinding.
