### ISSUE TITLE
Reduce commit rows shown in dashboard

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#44478]
It may sound reasonable to reduce number of commit rows from 100 to 50 on dashboard. On one hand, people may be interested in latest commit results; on the other hand, this shall cut query results half, which will help relieve datastore quota limitation burden.

An alternative is to provide an option, like a button, showing 100 rows once clicked. Otherwise, we show 50 rows by default.

**Comment by jonahwilliams** [comment]
Pagination seems like a reasonable solution

**Comment by keyonghan** [comment]
@CaseyHillers Do you mind help with the frontend side? Let me know if you need me to do anything from backend side.

**Comment by keyonghan** [comment]
cc @godofredoc @digiter

**Comment by CaseyHillers** [comment]
https://flutter.dev/go/build-dashboard-v2

This works perfectly as its one of the items I was going to tackle in the coming weeks.

Related issue for the backend: https://github.com/flutter/flutter/issues/43098

**Comment by CaseyHillers** [comment]
@keyonghan I am going to remove myself from this for now as the backend needs to be updated to handle this. Let me know if there's anything on the frontend that needs to be done for this.

Another change for this could just be reducing the commits down to 50 for now, and then working on https://github.com/flutter/flutter/issues/43098

**Comment by keyonghan** [comment]
Closing this issue as commented: https://github.com/flutter/cocoon/pull/622#discussion_r366558647

I think we can wait for https://github.com/flutter/flutter/issues/43098 to be fixed, without reducing the commits to 50 as a temporal solution.
