### ISSUE TITLE
Generate API docs for package:mojo_services

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#445]
Services exposed by mojoms are legit capabilities and functionality exposed by Flutter. When we generate API docs for Flutter, can we also include capabilities offered by mojoms (such as "sensors") ?

This would be a big help when learning what Flutter can do.

Thanks!

**Comment by abarth** [comment]
A bunch of these end up in http://domokit.github.io/docs/sky/services/services-library.html becaues we re-export them, but it might make more sense to generate docs for the mojom libraries themselves.

**Comment by sethladd** [comment]
Thanks! I was specifically looking for Sensor. Should that be in /services , too?

**Comment by abarth** [comment]
It's not re-exported by package:flutter/services.dart, which is why it isn't in that dartdoc.  Instead, you can just use it directly.  We need to generate docs for package:mojo_services, which contains the code for it.

**Comment by sethladd** [comment]
Ah ha, thanks for explaining! I can retitle this issue.

**Comment by abarth** [comment]
https://www.dartdocs.org/documentation/sky_services/0.0.70/ has the docs for sky_services.

**Comment by eseidelGoogle** [comment]
Is mojo_services currently maintained by flutter or the mojo project?  If I wanted to complete this bug, would that mean adding dartdocs to .mojom files, or presumably the .dart wrappers we've built around the mojoms?  Maybe this bug should be deferred past the hackathon and https://github.com/flutter/flutter/issues/1455 is sufficient for now?

**Comment by abarth** [comment]
>  Is mojo_services currently maintained by flutter or the mojo project?

It's maintained by mojo.git.

> If I wanted to complete this bug, would that mean adding dartdocs to .mojom files, or presumably the .dart wrappers we've built around the mojoms?

I think a good first step would be to publish the docs without any additional dartdoc, just to show the contents of the package.

I'm not sure what end-goal is here.  mojo_services contains a large number of interfaces that don't have any implementation in stand-alone Flutter.  We might want to curate docs specifically for those interfaces that are relevant in stand-alone Flutter.

**Comment by sethladd** [comment]
End goal is to provide complete API docs for all services available, out of the box, from Flutter. Perhaps just generating docs for sky_services is sufficient? Not sure if mojo_services adds any services that are available from Flutter but not otherwise documents by sky_services.

If mojo_services doesn't uniquely provide services exposed by Flutter, then we can close this.

Thanks!

**Comment by sethladd** [comment]
Sounds like documenting mojo_services doesn't buy us much, as what really matters for Flutter developers is sky_services which is documented here: https://www.dartdocs.org/documentation/sky_services/0.0.99/

Please reopen if mojo_services provides services useful to developers, not otherwise exposed anywhere else. Thanks!
