### ISSUE TITLE
'flutter run' failing to sign apk

### ISSUE THREAD

**Issue by stemuk** [flutter/flutter#4450]
When I try to execute 'flutter run' I get [this](https://lh3.googleusercontent.com/--kYpCiqb5zs/V1dDPPPU1NI/AAAAAAAAAEo/M9rMeRJgzr08zUIn8XYLwKie8Nmva5HXQCLcB/s1600/Screenshot%2Bfrom%2B2016-06-07%2B23-53-53.png) output.
To work aroud/fix it, I already tried to sign the gererated app.apk via jarsigner and then install it manually, and I tried to generate a new debug.keychain in the .android folder, but nothing really helped to overcome this problem.
@abarth already [suggested](https://groups.google.com/forum/#!topic/flutter-dev/vmiqxduS25s) to pass "-sigalg MD5withRSA -digestalg SHA1" to jarsigner which resulted in [this](https://lh3.googleusercontent.com/-xj05vUhEc_w/V1g0N3DmKvI/AAAAAAAAAE8/yjFhgSZHnDgdVhknb8zsF0FucXvgzTB3QCLcB/s1600/Screenshot%2Bfrom%2B2016-06-08%2B17-04-39.png) output. 

Unfortunately, the results were the same, even a manual apk installation aborted. 
Although I only have little experience in this area, is It possible to pass in a different keychain directly into the 'flutter run' build process? jarsigner may be a workaround but is rather inconvenient to use permanently.

**Comment by abarth** [comment]
Do you know what version of the JDK and Android you're using?  I've been testing with JDK 1.8.0_92.

**Comment by stemuk** [comment]
'java -version' puts out 1.8.0_91, would it make any difference to swich from oracle to openjdk?

**Comment by abarth** [comment]
I don't think its worth trying openjdk.  I suspect something else is going on.

Can you build and run the hello_services sample https://github.com/flutter/flutter/tree/master/examples/hello_services ?

**Comment by stemuk** [comment]
No, I am developing on Ubuntu. Apart from that, I tried multiple projects, sample projects and some of my own but they all lead to the same issue.

**Comment by abarth** [comment]
It sounds like there is some configuration issue with your machine.  For example, if you use Android Studio to create an example project (i.e., a stock Android project, not one with Flutter), do you encounter the same problem?

**Comment by stemuk** [comment]
Just tried it out multiple times, however, I still get an error (probably) related to my 'flutter run' issue:
>Error:Execution failed for task ':app:validateExternalOverrideSigning'.
Keystore file /home/stefanmuke/Desktop/android-animation-gestures-demo-master/~ not found for signing config 'externalOverride'. 

So you are probably right, it is a configuration issue, but sadly I am still not able to fix it. Do you have a clue what the misconfiguration might be?

**Comment by flojug** [comment]
I had the same issue on Debian.
jdk1.8.0_11
adt-bundle-linux-x86_64-20140321
=> INSTALL_PARSE_FAILED_NO_CERTIFICATES 

this is what I have done:

- edit ~/flutter/packages/flutter_tools/lib/src/commands/build_apk.dart

- add sigalg et digestalg to jarsigner (as suggested in http://stackoverflow.com/questions/2914105/android-what-is-install-parse-failed-no-certificates-error)

  void sign(File keystore, String keystorePassword, String keyAlias, String keyPassword, File outputApk) {
    assert(_jarsigner != null);
    runCheckedSync(<String>[_jarsigner.path,
      '-keystore', keystore.path,
      '-storepass', keystorePassword,
      '-keypass', keyPassword,
      '-sigalg', 'MD5withRSA',
      '-digestalg', 'SHA1',
      outputApk.path,
      keyAlias,
    ]);
  }

- remove /home/florent/DEV/flutter/bin/cache/flutter_tools.snapshot

- and run again
$ flutter build clean
$ flutter -v run

**Comment by eseidelGoogle** [comment]
FYI @danrubel

**Comment by eseidelGoogle** [comment]
@Hixie you were reporting issues on ubuntu last night, was this one of them?

**Comment by Hixie** [comment]
I never got this far. I got stuck on building the engine.

**Comment by mit-mit** [comment]
Closing as historical. Signing works now with the new gradle-based build (create new template files with `flutter create`), and the signing steps listed here: https://flutter.io/android-release/#signing-the-app
