### ISSUE TITLE
flutter build apk --release --target-platform=android-arm apk not working and normal app file size too large

### ISSUE THREAD

**Issue by undamatlamanikanta** [flutter/flutter#44505]
flutter build apk --release --target-platform=android-arm and android-arm64 release build is successful then arm64 apk installed and working fine in my devices but arm apk installed not working in my device app closing error occur please help me as soon as possible

**Comment by iapicca** [comment]
Hi @undamatlamanikanta 
I'm not sure to understand correctly,
you app works properly in debug mode,
but the generated apk doesn't work, am I correct?
Did you use `flutter build apk --split-per-abi` as described in the [documentation](https://flutter.dev/docs/deployment/android#build-an-apk)?
Could you please provide your `flutter doctor -v` 
and `flutter build apk --split-per-abi --verbose`?
thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
