### ISSUE TITLE
Shared preferences error

### ISSUE THREAD

**Issue by godlessturtle** [flutter/flutter#44508]
i've just upgraded my shared preferences version, then unable to run project, even i deleted 
`development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.4+3/` folder

```
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET shared_preferences OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from /Users/ikra/development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.4+3/ios/Classes/SharedPreferencesPlugin.m:5:
    /Users/ikra/development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.4+3/ios/Classes/SharedPreferencesPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone 6.
```

**Comment by iapicca** [comment]
Hi @godlessturtle 
I felt a sort of [dejavu](https://github.com/flutter/flutter/issues/44339#issuecomment-551073243),
I'm assuming that the downgrade didn't go well, 
if your flutter doctor [changed](https://github.com/flutter/flutter/issues/44339), please post the updated one.

Could you please post your `flutter build --verbose`,
thank you

**Comment by godlessturtle** [comment]
i have built with my old podfile, works for now

**Comment by iapicca** [comment]
Hi again @godlessturtle 
I'm glad that you solved it;
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
