### ISSUE TITLE
Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

### ISSUE THREAD

**Issue by a497500306** [flutter/flutter#44509]
*** -[FlutterEngine platformViewsController]: message sent to deallocated instance 0x6000003c5370

**Comment by iapicca** [comment]
Hi @a497500306 
could you please provide your `flutter doctor -v` and `flutter run --verbose`
together with a minimal code sample to reproduce the problem
thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
