### ISSUE TITLE
Generate AOT snapshot documentation out of date

### ISSUE THREAD

**Issue by jld3103** [flutter/flutter#44518]
The [documentation](https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedding-in-AOT-Mode#generating-the-aot-snapshot) about generating an AOT snapshot seems to be out of date.

When I use exactly what is documented there I get this:
```
Setting VM flags failed: Unrecognized flags: packages, sim-use-hardfp, use-integer-division
```
When I remove these flags I get this:
```
WARNING: app-aot-blobs snapshots have been deprecated and support for generating them will be removed soon. Please use the app-aot-elf or app-aot-assembly snapshot kinds in conjunction with the portable ELF loader from //runtime/bin:elf_loader if necessary. See http://dartbug.com/38764 for more details.
```

Since blobs are deprecated I wanted to use elf or assembly instead, but there is documentation on how to to that. I figured it out myself, but there is no documentation about using the elf or assembly file with the engine.

**Comment by calvin2021y** [comment]
Why close it without comment ?  the document still not updated.

app-not-assembly is only for ios?
