### ISSUE TITLE
High images RAM consumption

### ISSUE THREAD

**Issue by alectogeek** [flutter/flutter#44510]
I'm working on an app (mainly for iOS) that contains ListView.builder with lots of pictures (about 64 pictures, 7.7 Mb size in total on disk) and I have a huge performance problem on devices with 1 Gb RAM and lower. I tried to decrease imageCache _maximumSizeBytes to 30 Mb and now the app works better in terms of smoothness but it's bad workaround because now pictures are uploaded from the cache and it leads to freezes in pictures appearing in the list.

I'm sure I'm facing the same problem as in #13242. Any suggestions/ideas?

## Flutter doctor

```
[✓] Flutter (Channel master, v1.10.16-pre.88, on Mac OS X 10.14.6 18G103, locale en-RU)
    • Flutter version 1.10.16-pre.88 at /Users/alectogeek/Documents/Programs/flutter
    • Framework revision ff95b14ad8 (30 hours ago), 2019-11-07 23:14:17 -0500
    • Engine revision 7ed9c9fc58
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/alectogeek/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by alectogeek** [comment]
related #32156

**Comment by iapicca** [comment]
Hi @alectogeek 
does this [solution](https://github.com/flutter/flutter/issues/32143#issuecomment-544303867) work for you?
Thank you

https://github.com/flutter/flutter/issues/32156

**Comment by alectogeek** [comment]
Hi @iapicca! Thanks for the answer. No, I need to show almost the whole image, so I need to cache the whole image as well. Moreover, I use CachedNetworkImage absolutely everywhere and this package doesn't support cacheHeight/cacheWidth parametres. But.. is it normal that decoded image takes 10+ times more space in RAM than it took being encoded in local storage?

**Comment by iapicca** [comment]
Hi again @alectogeek 
the high ram consumption is a known situation
as you can see from the cases listed in this [issue](https://github.com/flutter/flutter/issues/32156),
thank you for your contribution

**Comment by alectogeek** [comment]
Thanks for answer @iapicca. Is there any "forecast" of when it will be solved? Can I help somehow?

**Comment by alectogeek** [comment]
Is there any news?

**Comment by dnfield** [comment]
I think I have a fix for this, assuming it's similiar to the issue in #32143 (where rapid scrolling makes it particularly bad).

If you're worried that images are taking up a lot of memory statically, that's a different bug than what I'm thinking though.
