### ISSUE TITLE
Webview makes my phone unresponse after turning off screen

### ISSUE THREAD

**Issue by brvinodh** [flutter/flutter#44520]
## Steps to Reproduce

Im using Android 10, oneplus7 pro phone(upgraded to android 10 recently). 
When I create a very basic flutter app using webview and debug/install release on mobile. 
I get to see the application with the URL loaded on mobile. However when i turn off screen/lock phone with the app still running/foreground. 

My phone hangs with different types of behaviours
a. On pressing turn on/lock screen button(power button), the camera pops up/out (face recognition unlock)  but display is still blank, after waiting for 1 min or so the phone display is shown back. 
b. Camera pops up/in I believe internally it gets unlocked, howeer display is still blank, phone then restarts. 

1.  Android 10 phone, (one plus 7 pro)
2. .Create a very basic webview app ex: 
    ```
     return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: WebView(initialUrl: "https://www.google.com",),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
   ```
3. Deploy the app on phone

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

flutter run --verbose
I believe may not be releavant
```
[ +641 ms] I/chromium( 4302): [INFO:CONSOLE(0)] "A cookie associated with a resource at http://google.com/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver
cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at
https://www.chromestatus.com/feature/5633521622188032.", source: https://www.google.com/search?source=hp&ei=Yw3HXfvcLYfUvgTaz6CACg&q=hello+world+are+youvrunn (0)
[+3253 ms] W/IInputConnectionWrapper( 4302): requestCursorAnchorInfo on inactive InputConnection
[  +25 ms] W/IInputConnectionWrapper( 4302): getTextBeforeCursor on inactive InputConnection
[   +3 ms] W/IInputConnectionWrapper( 4302): getSelectedText on inactive InputConnection
[   +7 ms] W/IInputConnectionWrapper( 4302): getTextAfterCursor on inactive InputConnection
[   +1 ms] W/IInputConnectionWrapper( 4302): requestCursorAnchorInfo on inactive InputConnection
[ +388 ms] E/InputMethodManager( 4302): b/117267690: Failed to get fallback IMM with expected displayId=4 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{ca464e0 VFEDHVC........ID 0,0-1440,1641}
[ +136 ms] V/ViewRootImpl( 4302): The specified message queue synchronization  barrier token has not been posted or has already been removed
```

```
```

flutter doctor -v
[√] Flutter (Channel dev, v1.10.15, on Microsoft Windows [Version 10.0.17134.1069], locale en-US)
    • Flutter version 1.10.15 at C:\Data\flutter\flutter
    • Framework revision fbabb264e0 (8 days ago), 2019-11-02 01:36:07 +0300
    • Engine revision 8ea19b1c76
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\vinodh\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\vinodh\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\vinodh\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\vinodh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • GM1911 • bd4bb5d2 • android-arm64 • Android 10 (API 29)
```
```

**Comment by iapicca** [comment]
Hi @brvinodh 
could you please provide  your `flutter run --verbose`
performing the action that "hung" the phone
thank you

**Comment by brvinodh** [comment]
Hi @iapicca , 

Sorry, I had missed to add statement "flutter run --verbose" command in the above issue, however the last few lines of the flutter logs i had updated in the issue, same has been pasted below. 

```
 +641 ms] I/chromium( 4302): [INFO:CONSOLE(0)] "A cookie associated with a resource at http://google.com/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver
cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at
https://www.chromestatus.com/feature/5633521622188032.", source: https://www.google.com/search?source=hp&ei=Yw3HXfvcLYfUvgTaz6CACg&q=hello+world+are+youvrunn (0)
[+3253 ms] W/IInputConnectionWrapper( 4302): requestCursorAnchorInfo on inactive InputConnection
[  +25 ms] W/IInputConnectionWrapper( 4302): getTextBeforeCursor on inactive InputConnection
[   +3 ms] W/IInputConnectionWrapper( 4302): getSelectedText on inactive InputConnection
[   +7 ms] W/IInputConnectionWrapper( 4302): getTextAfterCursor on inactive InputConnection
[   +1 ms] W/IInputConnectionWrapper( 4302): requestCursorAnchorInfo on inactive InputConnection
[ +388 ms] E/InputMethodManager( 4302): b/117267690: Failed to get fallback IMM with expected displayId=4 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{ca464e0 VFEDHVC........ID 0,0-1440,1641}
[ +136 ms] V/ViewRootImpl( 4302): The specified message queue synchronization  barrier token has not been posted or has already been removed
```

Also wanted to highlight that the Phone does not hang when the App is being used; but when i have opened a flutter app which contains a webview and turn off the screen, [or switch to other apps (phone dialer, messager, etc)] . The phone hangs up after some time. 

Please find the 
[sourceCode.zip](https://github.com/flutter/flutter/files/3831914/sourceCode.zip) source code which contains a simple webview

Also wanted to highlight that the flutter verbose does not give me any logs when the phone screen is off/or its in background. 

Thank you.

**Comment by iapicca** [comment]
Hi @brvinodh 
thank you for  providing these information

**Comment by Pijulin** [comment]
@iapicca @iapicca same issue on MIUI 11 which based on Android 10

**Comment by brvinodh** [comment]
Hi @iapicca , Just checking if we have an update.. Thanks

**Comment by iapicca** [comment]
Hi @brvinodh @Pijulin 
are you experiencing the issue with the last stable version of flutter and webview plugin?
thank you

**Comment by brvinodh** [comment]
Sure let me check and revert back on this.

**Comment by darshankawar** [comment]
Hi @brvinodh, can you please confirm if you are still experiencing this issue on latest Flutter version and `webview_flutter` plugin ?
I tried to replicate this issue on Android 10 but didn't see any issue.

**Comment by bitk0der** [comment]
Same here, some phones just hangs with opened webview (sometimes after 1 minute, sometimes afte 1 hour), only reboot can solve the issue, example phone with issue: Xiaomi Redmi 3 (fresh hard reset with all updates).

**Comment by santhosh-mobile-dev** [comment]
Same problem in Android 10, Oneplus 7 Pro phone

**Comment by ycv005** [comment]
Using Flutter 3.0 & latest webview plugin, still I am facing this when I hit lock button then unlock the screen, 
Could this be pick up in fast pace- @darshankawar @kf6gpe @iapicca

**Comment by batoul-alani** [comment]
any update for this problem?? 
I faced the same and I try to find a solution

**Comment by darshankawar** [comment]
Revisiting this issue, I ran the webview_flutter plugin example in S10 device using latest stable, played around by turning off the screen, lock button and resuming but it works properly as expected. @brvinodh Is there a way for you to re-run your sceanario with latest plugin example and stable to check if the behavior still persists or not ?
