### ISSUE TITLE
flutter_test update deps

### ISSUE THREAD

**Issue by boskokg** [flutter/flutter#44523]
## Steps to Reproduce

Because every version of flutter_test from sdk depends on quiver 2.0.5 and xxx depends on quiver ^2.1.2+1, flutter_test from sdk is forbidden.

Same is for image plugin.

## Logs

```
```

```
```

**Comment by awhitford** [comment]
A project seems unable to specify a [quiver](https://pub.dev/packages/quiver#-changelog-tab-) version newer than 2.0.5.  Doing so yields an error message:

> Because every version of flutter_test from sdk depends on quiver 2.0.5 and _PROJECT_ depends on quiver ^2.1.2+1, flutter_test from sdk is forbidden.
> So, because _PROJECT_ depends on flutter_test any from sdk, version solving failed.
