### ISSUE TITLE
[Web] Scrolling produces error message

### ISSUE THREAD

**Issue by khari998** [flutter/flutter#44524]
The structure of my application has a SingleChildScrollView produced within a container. My flutter application seems to be working just fine, however, when I scroll I get the following error:

The following assertion was thrown while dispatching a pointer event:
Assertion failed:
org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
_currentEvent == null || _currentEvent == event
is not true

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 194:49      throw_
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3        assertFailed
package:flutter/src/gestures/pointer_signal_resolver.dart 32:59                           register
package:flutter/src/widgets/scrollable.dart 549:55                                        [_receivedPointerSignal]
package:flutter/src/rendering/proxy_box.dart 2574:14                                      handleEvent
package:flutter/src/gestures/binding.dart 198:14                                          dispatchEvent
package:flutter/src/gestures/binding.dart 156:7                                           [_handlePointerEvent]
package:flutter/src/gestures/binding.dart 102:7                                           [_flushPointerEventQueue]
package:flutter/src/gestures/binding.dart 86:32                                           [_handlePointerDataPacket]
package:build_web_compilers/lib/_engine/engine/pointer_binding.dart 89:15                 [_onPointerData]
package:build_web_compilers/lib/_engine/engine/pointer_binding.dart 277:7                 <fn>
package:build_web_compilers/lib/_engine/engine/pointer_binding.dart 573:56                <fn>
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall

Event:
PointerScrollEvent#a33a3(position: Offset(677.0, 775.0), timeStamp: 2:14:14.301219, pointer: 0,
kind: mouse, device: -1, down: false, scrollDelta: Offset(-0.0, 3.0))
Target:
RenderPointerListener#7c96e relayoutBoundary=up5
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12

Even thought I get this error when scrolling through my webpage, nothing seems to be breaking in my actual application. There is no stack trace to specify where this bug is originating from. My flutter doctor and verbose are below.

flutter doctor -v                
[✓] Flutter (Channel master, v1.10.16-pre.80, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.10.16-pre.80 at /Users/Khari/Documents/Dev_Projects/flutter
    • Framework revision 62b7ce306d (2 days ago), 2019-11-07 15:21:45 -0800
    • Engine revision c448d39d53
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/Khari/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/Khari/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/Khari/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.97
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

flutter run --verbose            
[  +25 ms] executing: [/Users/Khari/Documents/Dev_Projects/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +37 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 62b7ce306d53086644746dcb952059858cdf64dc
[        ] executing: [/Users/Khari/Documents/Dev_Projects/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +26 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.10.15-80-g62b7ce306
[   +7 ms] executing: [/Users/Khari/Documents/Dev_Projects/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/Khari/Documents/Dev_Projects/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +50 ms] executing: [/Users/Khari/Documents/Dev_Projects/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +6 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.1
[        ] executing: sw_vers -buildVersion
[  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19B88
[  +29 ms] executing: /usr/bin/xcode-select --print-path
[   +7 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +149 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +3 ms] Xcode 11.2
           Build version 11B52
[  +63 ms] executing: /Users/Khari/Library/Android/sdk/platform-tools/adb devices -l
[   +6 ms] Exit code 0 from: /Users/Khari/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +14 ms] executing: /Users/Khari/Documents/Dev_Projects/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +60 ms] /usr/bin/xcrun simctl list --json devices
[ +129 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +46 ms] Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.97
[   +1 ms] Web Server • web-server • web-javascript • Flutter Tools
[  +12 ms] "flutter run" took 584ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:288:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:531:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:456:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:222:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main (file:///Users/Khari/Documents/Dev_Projects/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by iapicca** [comment]
Hi @khari998 
I see that you are having an error on `pointer_signal_resolver`
there's an open [issue](https://github.com/flutter/flutter/issues/44037 ) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
