### ISSUE TITLE
[google_sign_in] Concurrent operations detected - on restart

### ISSUE THREAD

**Issue by p30arena** [flutter/flutter#44538]
I'm using **google_sign_in 4.0.11**, and calling **signInSilently** method.
When I restart the app, the mentioned method throws an error:

```
googleSignIn.signInSilently();
```

```
W/GooglePlayServicesUtil(10082): Google Play services out of date.  Requires 12451000 but found 11743470
E/MethodChannel#plugins.flutter.io/google_sign_in(10082): Failed to handle method call
E/MethodChannel#plugins.flutter.io/google_sign_in(10082): java.lang.IllegalStateException: Concurrent operations detected: signInSilently, signInSilently
E/MethodChannel#plugins.flutter.io/google_sign_in(10082): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.checkAndSetPendingOperation(GoogleSignInPlugin.java:201)
E/MethodChannel#plugins.flutter.io/google_sign_in(10082): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.checkAndSetPendingOperation(GoogleSignInPlugin.java:196)
E/MethodChannel#plugins.flutter.io/google_sign_in(10082): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.signInSilently(GoogleSignInPlugin.java:264)
E/MethodChannel#plugins.flutter.io/google_sign_in(10082): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin.onMethodCall(GoogleSignInPlugin.java:73)
E/MethodChannel#plugins.flutter.io/google_sign_in(10082): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#plugins.flutter.io/google_sign_in(10082): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/google_sign_in(10082): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:645)
E/MethodChannel#plugins.flutter.io/google_sign_in(10082): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/google_sign_in(10082): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#plugins.flutter.io/google_sign_in(10082): 	at android.os.Looper.loop(Looper.java:135)
E/MethodChannel#plugins.flutter.io/google_sign_in(10082): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E/MethodChannel#plugins.flutter.io/google_sign_in(10082): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/google_sign_in(10082): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/MethodChannel#plugins.flutter.io/google_sign_in(10082): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by p30arena** [comment]
The problem is that the onComplete is never executed

```
        task.addOnCompleteListener(new OnCompleteListener<GoogleSignInAccount>() {
          @Override
          public void onComplete(Task<GoogleSignInAccount> task) {
            onSignInResult(task);
          }
        });
```

**Comment by iapicca** [comment]
Hi @p30arena 
could you provide your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by p30arena** [comment]
> Hi @p30arena
> could you provide your `flutter run --verbose`?
> Also, to better address the issue, would be helpful
> if you could post a minimal code sample to reproduce the problem
> Thank you

Hi @iapicca 
I've spent enough time debugging the plugin's code,
and I'm sure that the signInSilently's Task does not Complete neither Fails nor Cancels on Emulator.
I think we need a **timeout** for executing these tasks,
or we should let the dart code avoid the concurrency of tasks.

I've put a timeout on the dart side, but as you know it has no effect on the "pendingOperation" variable on the native side.

**Comment by someoneNameGrey** [comment]
> `Google Play services out of date.  Requires 12451000 but found 11743470`
Update your emulator Google Play Service to solve this.
[Solution Here in StackOverflow](https://stackoverflow.com/a/44614316/5033470)

**Comment by iapicca** [comment]
Hi @p30arena
did the solution proposed by @someoneNameGrey worked for you?
thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by tomavelev** [comment]
I've encountered similar error message today. Just sharing it - if it is of use for anybody.

The problem on my case was I didn't have the Sign in with Google in the Firebase Authentication settings.

**Comment by iapicca** [comment]
@tomavelev 
this issue was closed more than a year ago
I recommend to open a new issue providing your `flutter doctor -v`, 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **_without 3rd party plugins_**
