### ISSUE TITLE
--debug run on iOS device should also turn on checked mode

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4454]
We should probably show a "slow mode" banner when running in debug (aka interpreter) mode on iOS device. We don't want developers to forget they chose debug mode.

Turns out that "checked mode" is not turned on when I run `flutter -d i run` (which should default to --debug and checked mode).

**Comment by sethladd** [comment]
cc @Hixie

**Comment by Hixie** [comment]
If we're not showing it, then that means asserts aren't enabled, so that's a bug in debug mode.

**Comment by sethladd** [comment]
Confirmed that `--debug` for iOS device is not the same as "checked mode".

**Comment by sethladd** [comment]
cc @tvolkert @chinmaygarde

**Comment by chinmaygarde** [comment]
This was fixed in https://github.com/chinmaygarde/flutter/commit/9782d97faacbafa1a8b4511d8109cb1a1a2e11b3#diff-4e6a9727ba10772d640b597dbdd61d03R209
