### ISSUE TITLE
Unable to sign into the Flutter dashboard

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#44548]
I wanted to check a failed task today but wasn't able to sign in. I tried both the "Sign In" button on the root page as well on the `build.html` page. In both cases the sign-in flow looks successful but my session remains signed out and I'm unable to see the devicelab logs.

/cc @godofredoc

**Comment by CaseyHillers** [comment]
I believe this was fixed with https://github.com/flutter/cocoon/pull/615

Feel free to reopen if you're still experiencing this issue.
