### ISSUE TITLE
NoSuchMethodError: method not found: 'aD' on null when releasing a web

### ISSUE THREAD

**Issue by rocboronat** [flutter/flutter#44540]
Feel free to check it online at http://fewlaps.com/xtra/weather. A small thing to check the weather in my neighborhood. You're welcome, by the way! ☕️🍻

## Steps to Reproduce

Just run some code as a web project. It happens on debug and on release. It doesn't happen on Android or iOS targets.

**Target Platform:** Web
**Target OS version/browser:** Windows 10 with Chrome 78.0.3904.97 64 bits but also tried on Chromes running on Android and iOS
**Devices:** It seems that it happens on all devices

## Logs

The output of `flutter run -d chrome -verbose` (to run it on the web but verbose) is...
`Could not find an option with short name "-e".`

Whoops. And `flutter run -verbose` runs on the phone and the issue doesn't happen.
If I run on the web but without verbose, another strange thing happens. Probably is related to the main issue...
`Another exception was thrown: NoSuchMethodError: 'toStringAsFixed'`

The out of `flutter analyze`:
`No issues found! (ran in 2.2s)`

The out of `flutter doctor -v`:
```bash
[√] Flutter (Channel dev, v1.10.15, on Microsoft Windows [VersiÃ³n 10.0.18362.418], locale es-ES)
    • Flutter version 1.10.15 at D:\Dev\Flutter\SDK
    • Framework revision fbabb264e0 (8 days ago), 2019-11-02 01:36:07 +0300
    • Engine revision 8ea19b1c76
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Dev\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Dev\Android\SDK
    • Java binary at: C:\Applications\Android Studio 3.4.2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Applications\Android Studio 3.4.2
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Applications\IntelliJ CE 2019.2
    • Flutter plugin version 41.0.4
    • Dart plugin version 192.7402

[√] Connected device (3 available)
    • SM G960F   • 229c33be26017ece • android-arm64  • Android 9 (API 28)
    • Chrome     • chrome           • web-javascript • Google Chrome 78.0.3904.97
    • Web Server • web-server       • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
Hi @rocboronat 
could you please provide your full `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by rocboronat** [comment]
Hi team! It was my fault! I was calling `toStringAsFixed()` on a null variable that later had a value. The problem there is that the web was showing `method not found: 'aD' on null` while the var was actually named `tempMin`.

The code with the issue: Text('${tempMin.toStringAsFixed(1)}'),
The fixed code: Text('${tempMin != null ? tempMin.toStringAsFixed(1) : ""}'),

Feel free to close this issue, or change its name to focus on that var name that was another one.

**Comment by iapicca** [comment]
Hi @rocboronat 
I'm glad that you fixed the issue,
thank you for letting me know

**Comment by rocboronat** [comment]
Hey @iapicca, please, reopen the issue. The message `method not found: 'aD' on null` had no connection with the issue I fixed. It seems that something there is actually calling `aD` on a null object.
