### ISSUE TITLE
Pinned sliver dynamic height

### ISSUE THREAD

**Issue by nikitadol** [flutter/flutter#44557]
`SliverPersistentHeader` has the functionality I need, but it requires height (`minExtent` and `maxExtent`) - how do I make a sliver so that it behaves the same as `SliverPersistentHeader (pinned: true, ...)` and it does not need to set the height?

**Comment by iapicca** [comment]
Hi @nikitadol 
I'm not sure to understand
what behavior would you like to achieve from the`SliverPersistentHeader`;
here is an [example ](https://gist.github.com/iapicca/c281e431f80c33dde95072c17f6ef2d2)of both current behaviors (`pinned `and `floating`).
Can you please explain more in details?
Thank you

**Comment by nikitadol** [comment]
@iapicca In the implementation of SliverPersistentHeaderDelegate, you must explicitly specify the height. By design, I have a widget that I have to pin when scrolling. But with the current implementation, I have to calculate the height and set to this delegate. I just want to be able to pin any widget without passing height to the delegate.

**Comment by lukepighetti** [comment]
@nikitadol did you ever get anywhere with this? I'm looking for the exact same thing. Basically a SliverToBoxAdapter that can be `pinned` or `floating`

**Comment by nikitadol** [comment]
@lukepighetti 
Sorry, but not. I calculate the height

**Comment by lukepighetti** [comment]
@nikitadol It is possible to do but I don't have enough experience with the sliver API to knock this out. It looks like it would be trivial for someone with experience, someone like @Hixie 

```

class _SliverPinnedBoxAdapter extends SingleChildRenderObjectWidget {
  const _SliverPinnedBoxAdapter({
    Key key,
    Widget child,
    this.pinned = true,
  }) : super(key: key, child: child);

  final bool pinned;

  @override
  RenderObject createRenderObject(BuildContext context) =>
      _RenderSliverPinnedBoxAdapter(pinned: pinned);
}

class _RenderSliverPinnedBoxAdapter extends RenderSliverSingleBoxAdapter {
  _RenderSliverPinnedBoxAdapter({RenderBox child, @required this.pinned})
      : super(child: child);

  /// If true, [success] should stay pinned at the top of the list,
  /// [success] but move back into it's original position when scrolling down
  ///
  /// If false, [success] should move out of the list, [FAILING] but move back into it's original position
  /// when scrolling down
  ///
  /// [FAILING] You should be able to place a `pinned = false` sliver above a `pinned = true` sliver
  /// and have them never overlap
  ///
  /// [FAILING] Should not react to overscrolling on iOS
  final bool pinned;
  // double lastUpwardScrollOffset = 0;

  double previousScrollOffset = 0;
  double ratchetingScrollDistance = 0;

  @override
  void performLayout() {
    child.layout(constraints.asBoxConstraints(), parentUsesSize: true);
    double childExtent = child.size.height;
    final double paintedChildSize =
        calculatePaintOffset(constraints, from: 0.0, to: childExtent);
    final double cacheExtent =
        calculateCacheOffset(constraints, from: 0.0, to: childExtent);

    assert(paintedChildSize.isFinite);
    assert(paintedChildSize >= 0.0);

    final dy = previousScrollOffset - constraints.scrollOffset;
    previousScrollOffset = constraints.scrollOffset;

    ratchetingScrollDistance =
        (ratchetingScrollDistance + dy).clamp(0.0, childExtent);

    if (pinned) {
      print(ratchetingScrollDistance);
    }

    geometry = SliverGeometry(
      scrollExtent: childExtent,
      paintExtent: paintedChildSize,
      cacheExtent: cacheExtent,
      maxPaintExtent: childExtent,
      hitTestExtent: paintedChildSize,
      hasVisualOverflow: childExtent > constraints.remainingPaintExtent ||
          constraints.scrollOffset > 0.0,
      paintOrigin: pinned
          ? constraints.scrollOffset
          : max(
              0,
              constraints.scrollOffset - childExtent + ratchetingScrollDistance,
            ),
      visible: true,
    );

    setChildParentData(child, constraints, geometry);
  }
}

```


```
CustomScrollView(
  slivers: <Widget>[
    _SliverPinnedBoxAdapter(
      pinned: false,
      child: SizedBox(
        height: 50,
        child: Placeholder(),
      ),
    ),
    _SliverPinnedBoxAdapter(
      pinned: true,
      child: SizedBox(
        height: 200,
        child: Placeholder(),
      ),
    ),

    /// Filler
    SliverList(
      delegate: SliverChildListDelegate(children),
    ),
  ],
)

```


![ezgif-7-56e9156ec2fd](https://user-images.githubusercontent.com/666539/75818236-7fc6be00-5d66-11ea-963f-ca6fce1221f7.gif)

**Comment by YeungKC** [comment]
@lukepighetti 
Thank you very much, but if I scroll to viewport height, I got the error.

The following assertion was thrown during performLayout():
SliverGeometry has a paintOffset that exceeds the remainingPaintExtent from the constraints.

The render object whose geometry violates the constraints is the following: RenderSliverPinnedBoxAdapter#09635 relayoutBoundary=up1
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 808.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.reverse, scrollOffset: 826.6, remainingPaintExtent: 812.0, crossAxisExtent: 375.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 812.0, remainingCacheExtent: 1312.0, cacheOrigin: -250.0)
...  geometry: SliverGeometry(scrollExtent: 114.0, paintExtent: 0.0, paintOrigin: 826.6, maxPaintExtent: 114.0, hasVisualOverflow: true)
...    scrollExtent: 114.0
...    paintExtent: 0.0
...    paintOrigin: 826.6
...    maxPaintExtent: 114.0
...    hasVisualOverflow: true
The remainingPaintExtent is 812.0, but the paintOrigin + paintExtent is 826.6.
The paintOrigin and paintExtent must cause the child sliver to paint within the viewport, and so cannot exceed the remainingPaintExtent.

**Comment by lukepighetti** [comment]
My comment has incomplete code. If you find a solution please share it. Reread my comment. Thanks and good luck.

**Comment by YeungKC** [comment]
@lukepighetti 
Hi, I find a solutino, it is dont use setChildParentData, it can change SliverPhysicalParentData.paintOffset, and paintOrigin: constraints.overlap.

**Comment by lukepighetti** [comment]
Can you please paste a working example?

**Comment by YeungKC** [comment]
@lukepighetti 
Just no log output, ui is no diff.

**Comment by YeungKC** [comment]
@lukepighetti 
Hi, I maked a demo:
https://codepen.io/yeungkc/pen/RwrNqmm?__cf_chl_jschl_tk__=62f4b0e26552095942956b930f41802e31aa6244-1591377589-0-AYJnO_xNNvg8T-QXPrxhJ6XrZPP3PmvxybgEBdm9LJGb5tXG-SEUuh4q2xmtWRluTSt9D9t8dcKL76EsN3vs3jPeZIFM640HzNt34D3OIX_Jpx3rEDxWzFCA2n6EDa75pgywu3G99WZkyZ9TqfpzAJnBX6NPDyFmhErTbGCA9auDMjUUyiF2dm-cMl07q6P950dOV61SMeEIVT6uk94ImiY26OealuE4oFXZzVGzWo1jLpvj7OurE25PmBnEfy2NZad4SY5KpBm2d2Q9OCpGmmBV0_FmH-1kmHKuG62vZTCNaR3TO_SBZzTZYIbhWPLiCB2u-Aw5fA1IoA9I7w6psg3aLHf2wJqEFaz5a2IaLQzo

**Comment by RobinLbt** [comment]
@YeungKC Thank you the demo is very useful.
Any idea how to modify your custom sliver with floating instead of pinned ?
My Flutter knowledge isn't that great

**Comment by Kavantix** [comment]
Just added this widget to [sliver_tools](https://pub.dev/packages/sliver_tools)

**Comment by krmao** [comment]
yes, I want SliverPersistentHeaderDelegate from maxHeight to minHeight, not min to max, I don't know how to do this.
I want change pinned height by scroll.
if SliverToBoxAdapter can pinned, I can use ValueListenableBuilder to change.
But PreferredSize can not use ValueListenableBuilder. @iapicca

**Comment by aarajput** [comment]
I have created **SliverStickyHeader** widget, you can pass child with dynamic height. It pinned and floating and you don't need to pass height.
You can view its result in below video.

https://gist.github.com/aarajput/d4fb5b0651d1a0d3f383596fb267ffde


https://user-images.githubusercontent.com/16102514/196989530-2e0e039e-0baf-4cd5-a324-0f13e0408931.mp4

**Comment by VaporGraphic** [comment]
> I have created **SliverStickyHeader** widget, you can pass child with dynamic height. It pinned and floating and you don't need to pass height. You can view its result in below video.
> 
> https://gist.github.com/aarajput/d4fb5b0651d1a0d3f383596fb267ffde
> 
>  screen_recording.mp4

YOU ARE A GENIUS! The best answer 🤗

1 year ago I was looking for this, but I wasn't able to find an answer. You should make this a package at pub.dev

P.s. How did you learn to do that?

**Comment by Piinks** [comment]
I think this issue is covered by https://github.com/flutter/flutter/issues/18345, which has more upvotes so I am going to close this to consolidate with that issue. Thanks for all the discussion here, it looks like there are some packages listed above that support this as well. We're looking into what would be required to do this right, whether it live in the SliverPersistentHeader API or elsewhere. Please follow up in https://github.com/flutter/flutter/issues/18345. Thanks!
