### ISSUE TITLE
Second run of `flutter run --release` for iOS is just as long as the first

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4455]
I wonder if there's anything we can do to speed up the second run of `flutter run --release` when nothing has changed.  (if not, feel free to close) Maybe we're compiling each time?

A `--release` run takes 54s for the gallery. I admit that I don't expect developers to be running `--release` builds over and over without changing a line of code. But if there's real low hanging fruit on checking if nothing has changed, that might be pretty cool.

```
^C~/Code/flutter/examples/flutter_gallery[master*] $ time flutter -d i run --release
Running lib/main.dart on iPhone...
Application running.
Type "h" or F1 for help, "r" or F5 to restart the app, and "q", F10, or ctrl-c to quit.
^C
real    0m54.268s
user    0m30.068s
sys 0m9.105s
~/Code/flutter/examples/flutter_gallery[master*] $ time flutter -d i run --release
Running lib/main.dart on iPhone...
Application running.
Type "h" or F1 for help, "r" or F5 to restart the app, and "q", F10, or ctrl-c to quit.
^C
real    0m54.252s
user    0m31.632s
sys 0m9.620s
```

**Comment by abarth** [comment]
Yes, but not for a while.  What we can do is have the `gen_snapshot` tool output a list of all the inputs it used in a `.d` file, which we can then use to decide whether any of those files have changed and therefore whether we need to invoke `gen_snapshot` the next time.

**Comment by Hixie** [comment]
This has become a more general problem, so duping to https://github.com/flutter/flutter/issues/7673
