### ISSUE TITLE
Expand the "implementers" section of the api.flutter.dev docs to show 2nd level implementers

### ISSUE THREAD

**Issue by chonghorizons** [flutter/flutter#44554]
## Use case

When reading the api docs, it shows the implementers. But some (very important) implementers have implementers of their own. This makes it hard to read the docs to figure out these "2nd level" implementers.

Specific case: 
I was looking for ways to define the `ShapeDecoration`'s `shape` property. `shape` requires a `ShapeBorder`.

`ShapeBorder` shows these implementers if I don't want to build an instance by myself:
``` 
 Implementers
 BeveledRectangleBorder, BoxBorder, CircleBorder, ContinuousRectangleBorder, InputBorder, RoundedRectangleBorder, StadiumBorder
```

But, an important and commonly useful one is `Border`, which is 2 levels down.
> Object >  ShapeBorder > BoxBorder > Border

## Proposal

In the API docs, below `Impementers`, show `2nd-level Implementers` which are 2 levels of inheritance down.

That is, show this:

```
Implementers
BeveledRectangleBorder, BoxBorder, CircleBorder, ContinuousRectangleBorder, InputBorder, RoundedRectangleBorder, StadiumBorder

2nd Level Implementers
Border, BorderDirectional, OutlineInputBorder, UnderlineInputBorder
```

This can be done programatically and cheaply (i.e., not by hand). Just loop over the Implementers and find their sub-implementers.

Currently, it seems like some of these 2nd level implementers are described manually(human-generated) at the top of the class description in the api docs or as example code.

**Comment by goderbauer** [comment]
This is controlled by dartdoc (https://github.com/dart-lang/dartdoc). Can you file the feature request over there?
