### ISSUE TITLE
[shared_preferences] v0.5.4 warning: FlutterPluginBinding has been deprecated

### ISSUE THREAD

**Issue by godlessturtle** [flutter/flutter#44569]
im facing that issue when i run the` flutter build apk --release` command

```
Running Gradle task 'assembleRelease'...                                                                                                                                                                                          Note: /Users/ikra/development/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.5.6+3/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                                                               
Note: Some input files use or override a deprecated API.                                                           
Note: Recompile with -Xlint:deprecation for details.                                                               
Note: /Users/ikra/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_share_file-1.1.4+1/android/src/main/java/com/example/fluttersharefile/FlutterShareFilePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: Some input files use or override a deprecated API.                                                           
Note: Recompile with -Xlint:deprecation for details.                                                               
Note: /Users/ikra/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_qr_reader-1.0.3/android/src/main/java/me/hetian/flutter_qr_reader/factorys/QrReaderFactory.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: /Users/ikra/development/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+10/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                                                               
Note: /Users/ikra/development/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-3.3.0/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                                                               
Note: /Users/ikra/development/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.3+1/android/src/main/java/io/flutter/plugins/share/SharePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                                                               
/Users/ikra/development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.4+3/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());                   
                        ^                                                                                          
1 warning                                                                                                          
Note: Some input files use or override a deprecated API.                                                           
Note: Recompile with -Xlint:deprecation for details.                                                               
Running Gradle task 'assembleRelease'...                        (T(This is taking an unexpectedly long time.)       ⡿^C
Ikra-iMac:dijital-acentem-latest ikra$ 
```

```
Ikra-iMac:dijital-acentem-latest ikra$ flutter doctor --verbose
[✓] Flutter (Channel master, v1.10.16-pre.111, on Mac OS X 10.14.4 18E226, locale tr-TR)
    • Flutter version 1.10.16-pre.111 at /Users/ikra/development/flutter
    • Framework revision c1920c4c03 (2 days ago), 2019-11-08 23:36:17 -0500
    • Engine revision e0b9a2bb23
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ikra/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/ikra/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 39.0.4
    • Dart plugin version 192.6527

[✓] Connected device (2 available)
    • iPhone 6 • F0DF8E3D-65AE-4E51-824E-C95F073CBC16 • ios        • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • macOS    • macOS                                • darwin-x64 • Mac OS X 10.14.4 18E226


```

**Comment by iapicca** [comment]
Hi again @godlessturtle,
please ignore this warning for now 
the situation has being addressed as you can read from this [comment](https://github.com/flutter/flutter/issues/44070#issuecomment-549947493).
I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by godlessturtle** [comment]
i have to get build for android, i can not build the app. any idea?

**Comment by jmagman** [comment]
This should be a warning and not prevent the app from being built.  Are you seeing errors somewhere?

**Comment by godlessturtle** [comment]
it tries to generate .aar file, can not get apk or bundle

**Comment by marcelser** [comment]
same error also on newest 0.5.6

**Comment by I-am-original** [comment]
Looks like this plugin need to be updated.

**Comment by abhi21x** [comment]
still not resolved in 0.5.6

**Comment by andre-bahia** [comment]
same error also on newest 0.5.6 with version flutter 1.12.13+hotfix.5

**Comment by jonsamwell** [comment]
Please fix

**Comment by Basher7** [comment]
**still have same issue in latest version**

> Note: D:\Development\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.3+5\android\src\main\java\io\flutter\plugins\share\SharePlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> D:\Development\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
>     setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
>                         ^
> 1 warning

**Comment by hassaan-prog** [comment]
does anyone know how to fix it???
unable to do any thing in the app, because as soon as i try get any response the app crashes.

**Comment by I-am-original** [comment]
I have checked out on flutter v1.12.13+hotfix.5 and cleared all caches. after that - I build app with warnings but it is working.

**Comment by iapicca** [comment]
Hi all
please not this [answer](https://github.com/flutter/flutter/issues/44070#issuecomment-549947493)
this deprecation message is quote "deliberate and temporary."
thank you

**Comment by lvilcapumas7** [comment]
same error 0.5.6 and flutter version 1.12.13+hotfix.5 (stable)

**Comment by s-j-a** [comment]
see the solution from Kyle-Mendes [here](https://github.com/mogol/flutter_secure_storage/issues/49)
I still get a warning, but app seems to work OK

**Comment by ah3eyy** [comment]
> **still have same issue in latest version**
> 
> ```dart
> Note: D:\Development\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.3+5\android\src\main\java\io\flutter\plugins\share\SharePlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> D:\Development\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
>     setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
>                         ^
> 1 warning
> ```

Still getting this warning .would like an update if changes comes up

**Comment by iLolz** [comment]
Anyone solved that?

**Comment by iapicca** [comment]
Hi all,
as mentioned above the warning (not error)
are "deliberate and temporary."

Please read this [answer](https://github.com/flutter/flutter/issues/44070#issuecomment-549947493) 

I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by Eduardo1517** [comment]
same error 0.5.6 and flutter version 1.12.13+hotfix.5 (stable).

[deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated.

**Comment by H91011** [comment]
same error 
 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.13.6-pre.38, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

also I get sick from android. I just develop my app but I can't.
