### ISSUE TITLE
[google_maps_flutter] version 0.5.21+10 not available on pub.dev

### ISSUE THREAD

**Issue by MichalTorma** [flutter/flutter#44575]
Hi there, just a minor issue here. The newest version of google_maps_flutter is not available on pub.dev.

**Comment by iapicca** [comment]
Hi @MichalTorma 
I'm not sure to understand,
`google_maps_flutter` `0.5.21+8`
seems to be at [available](https://pub.dev/packages/google_maps_flutter)
can you please describe the issue in details?
thank you


![image](https://user-images.githubusercontent.com/45637986/68598092-ce460900-04a6-11ea-99fa-545689967f08.png)

**Comment by MichalTorma** [comment]
oh sorry for the misleading title, I meant that in git repo there is already 0.5.21+10 [released](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/CHANGELOG.md) and 0.5.21+8 is the latest available in pub.dev.

**Comment by jmagman** [comment]
@iskakaushik

**Comment by iapicca** [comment]
Hi @MichalTorma 
thank you for the clarification

**Comment by jmagman** [comment]
Pending pubspec bump at https://github.com/flutter/plugins/pull/2267.

**Comment by jmagman** [comment]
0.5.21+10 has been published to pub.  Thanks!
