### ISSUE TITLE
Measure analyzer footprint in the wild

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4457]
We want to collect measurements of analyzer's footprint (memory) in the wild. We want to know if there is a systemic issue when running and supporting the Atom plugin.

There's a lot we can do after we start measuring the number.  (correlate with size of project? uptime?) But let's get the number measured and reported first.

Once we're collecting the info, we can put it on the dashboard.

**Comment by sethladd** [comment]
Might help with https://github.com/flutter/flutter/issues/4384

**Comment by Hixie** [comment]
Given that we've not done anything with this in 16 months, is there any value in continuing to track this bug?

**Comment by Hixie** [comment]
Since nobody responded, I'm going to take that as a no.
