### ISSUE TITLE
update package:meta to 1.1.8 (to get `@nonVirtual`)

### ISSUE THREAD

**Issue by pq** [flutter/flutter#44578]
We recently added a `@nonVirtual` annotation (https://github.com/dart-lang/sdk/issues/34378) to `package:meta` which will allow us to do things like mark `toString()` in `Diagnosticable`s as non-overrideable (https://github.com/dart-lang/linter/issues/1492) and disallow overloading operator `==` and `hashCode` in widget classes (https://github.com/flutter/flutter/issues/1220).  

To take advantage,  we need to update Flutter's meta package dependency.  Unfortunately, `flutter update-packages --force-upgrade` is failing for me (https://github.com/flutter/flutter/issues/44477).

If that's not an easy fix, could someone with better luck update `meta`?

Thanks!

/cc @jonahwilliams @tvolkert

**Comment by jonahwilliams** [comment]
I'll take a look today

**Comment by pq** [comment]
Thanks!

**Comment by tvolkert** [comment]
https://github.com/flutter/flutter/issues/36511

**Comment by pq** [comment]
Thanks again @jonahwilliams!
