### ISSUE TITLE
Shrine: top-right price on homescreen is missing background color, too close to app bar

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4458]
From the spec:

![screen shot 2016-06-08 at 11 02 49 am](https://cloud.githubusercontent.com/assets/5479/15905151/aec1f2d8-2d68-11e6-820e-faecd93cb4eb.png)

From the polymer implementation:

![screen shot 2016-06-08 at 11 00 06 am](https://cloud.githubusercontent.com/assets/5479/15905161/b3c3c39c-2d68-11e6-9ff0-3f904cd57a21.png)

Gallery:

![screen shot 2016-06-08 at 11 04 16 am](https://cloud.githubusercontent.com/assets/5479/15905175/c3ac48ba-2d68-11e6-945f-1533c69ba088.png)

(notice that the price should have a pink-salmon background color, and has more padding from the bottom of the app bar)

**Comment by HansMuller** [comment]
The real problem here isn't the location of the price. It's that the app bar (wrong background color) should  be rendered at elevation 0, with a one pixel border at the bottom.

The price is highlighted when the item ends up in the shopping cart.
