### ISSUE TITLE
MacOs Catalina flutter build release error: "Bad CPU type in executable"

### ISSUE THREAD

**Issue by alexayub** [flutter/flutter#44597]
## Steps to Reproduce

1. Update Mac Os to Catalina version
2. Run "flutter build apk --release" on your project folder

## Logs
ProcessException: Bad CPU type in executable                            
  Command: /Users/alexayub/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot --causal_async_stacks --deterministic --snapshot_kind=app-aot-elf --elf=/Users/alexayub/GurgelMix/app-lojadomecanico/build/app/intermediates/flutter/release/android-arm/app.so --strip --no-sim-use-hardfp --no-use-integer-division /Users/alexayub/GurgelMix/app-lojadomecanico/build/app/intermediates/flutter/release/android-arm/app.dill
#0      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:142:27)
<asynchronous suspension>                                               
#1      GenSnapshot.run (package:flutter_tools/src/base/build.dart:75:12)
#2      AOTSnapshotter.build.<anonymous closure> (package:flutter_tools/src/base/build.dart:211:27)
#3      AOTSnapshotter._timedStep (package:flutter_tools/src/base/build.dart:344:33)
<asynchronous suspension>                                               
#4      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:210:13)
<asynchronous suspension>                                               
#5      BuildAotCommand.runCommand (package:flutter_tools/src/commands/build_aot.dart:149:56)
<asynchronous suspension>                                               
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>                                               
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>                                               
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>                                               
#9      _rootRun (dart:async/zone.dart:1124:13)                         
#10     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#11     _runZoned (dart:async/zone.dart:1516:10)                        
#12     runZoned (dart:async/zone.dart:1463:12)                         
#13     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>                                               
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>                                               
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>                                               
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>                                               
#18     _rootRun (dart:async/zone.dart:1124:13)                         
#19     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#20     _runZoned (dart:async/zone.dart:1516:10)                        
#21     runZoned (dart:async/zone.dart:1463:12)                         
#22     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>                                               
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>                                               
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#25     new Future.sync (dart:async/future.dart:224:31)                 
#26     CommandRunner.run (package:args/command_runner.dart:112:14)     
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>                                               
#29     _rootRun (dart:async/zone.dart:1124:13)                         
#30     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#31     _runZoned (dart:async/zone.dart:1516:10)                        
#32     runZoned (dart:async/zone.dart:1500:12)                         
#33     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>                                               
#34     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>                                               
#35     _rootRun (dart:async/zone.dart:1124:13)                         
#36     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#37     _runZoned (dart:async/zone.dart:1516:10)                        
#38     runZoned (dart:async/zone.dart:1463:12)                         
#39     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>                                               
#40     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>                                               
#41     run (package:flutter_tools/runner.dart:51:10)                   
#42     main (package:flutter_tools/executable.dart:62:9)               
<asynchronous suspension>                                               
#43     main (file:///Users/alexayub/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#44     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```
```

[!] Flutter (Channel unknown, v1.7.8+hotfix.4, on Mac OS X 10.15.1 19B88, locale en-BR)
    • Flutter version 1.7.8+hotfix.4 at /Users/alexayub/flutter
    • Framework revision 20e59316b8 (4 months ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alexayub/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.8.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X 10.15.1 19B88
    • web                       • web           • web-javascript • Google Chrome 78.0.3904.87 

! Doctor found issues in 1 category.

```
```

**Comment by jmagman** [comment]
Looks like https://github.com/flutter/flutter/issues/22598.
@christopherfujino Do you know which commit this should be fixed in?  Some of those commits look iOS-specific, but this is for android.

**Comment by christopherfujino** [comment]
@alexayub using flutter on macOS Catalina is supported on v1.9.1 (the latest stable release) and later. More details here https://github.com/flutter/flutter/wiki/Release-Notes-Flutter-1.9.1.

**Comment by leecommamichael** [comment]
We just got this with new-to-Flutter devs installing 1.22.2 freshly on their machines. The error went away when they accepted Android licenses.

**Comment by jmagman** [comment]
@leecommamichael Can you file a new issue and completely fill out the template?  This was closed in November 2019, may have a different cause.
