### ISSUE TITLE
Can you provide a command to generate aar? (including the generated aar of third-party plugins)

### ISSUE THREAD

**Issue by cedear** [flutter/flutter#44590]
I created a flutter module with the command "flutter create -t module xxx" and referenced the third-party plugin flutter_boost, and I want to generate an aar for my Android project using this module, but why do I use "flutter build aar" The aar generated by the command does not contain the aar of flutter_boost. Why does the official not provide a command to generate aar for all jar packages. it very important to hybird app.

**Comment by xster** [comment]
I'm not sure I understood the question. Are you saying that the maven repo doesn't contain other distinct AARs for each of the plugin dependencies?

This was a recent issue fixed in https://github.com/flutter/flutter/issues/43919.

**Comment by Hixie** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
