### ISSUE TITLE
[web] 'flutter build web' and 'flutter run' have different behavior related to type resolution

### ISSUE THREAD

**Issue by aryzhov** [flutter/flutter#44600]
This issue is specific to __flutter web__.

# Summary

There are two ways to reference a file when importing from a local package: `import "abc.dart"` and `import "package:my_package/abc.dart"`. As I found out, a class declared in `abc.dart` and referenced from different files using the two different ways results in two types that are not equivalent, where the `is` operator returns `false`. That happens only if the app is built using `flutter build web`. When running in debug mode using `flutter run -d chrome` the app behaves correctly.

# To reproduce

1. Make sure you're on master branch of Flutter.
1. Create a new Flutter project.
2. Copy-paste `main.dart`, `model.dart`, `util.dart` into your project lib directory.
3. Replace `my_package` with the name of your package in `main.dart` and `util.dart`.
4. Run the command: `flutter run -d chrome`. A Chrome window will open with `true` printed in the center.
5. Run the command `flutter build web`. 
6. Run the command `http-server build/web -o`. A Chrome window will open with `false` printed in the center.

# Sources

## main.dart
```dart
import 'package:flutter/material.dart';
import 'package:my_package/util.dart';
import 'model.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bug Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {

    final m1 = createModel();

    final isModel = m1 is MyModel;

    return Scaffold(
      appBar: AppBar(
        title: Text('Bug Demo'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              "If the displayed value is 'false' then it's a bug",
            ),
            Text(
              '$isModel',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
    );
  }
}
```

## model.dart
```dart
class MyModel {
}
```

## util.dart
```dart
import 'package:my_package/model.dart';

Object createModel() {
  return new MyModel();
}
```

# Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.248, on Mac OS X 10.14.6 18G95, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by sigmundch** [comment]
since main.dart is in the `lib` folder, both the dev and production compilers should treat the entrypoint as if they were given the URI `package:my_package/main.dart`. That appears to be true when using DDC (given the `true` message when debugging). 

When you launch dart2js from the command line, it also appears to make that normalization, so I was expecting it to work. I wonder if there is an issue in how dart2js in being invoked via webdev/build_runner.

/cc @jakemac53 - WDYT?

**Comment by jakemac53** [comment]
I believe that `flutter build web` directly invokes dart2js and doesn't go through build_runner - cc @jonahwilliams for confirmation (its possible this has changed).

**Comment by jakemac53** [comment]
Fwiw in build_runner we would invoke dart2js with a `package:` path for anything under lib, see https://github.com/dart-lang/build/blob/master/build_web_compilers/lib/src/dart2js_bootstrap.dart#L62

**Comment by jonahwilliams** [comment]
Yes this is correct, we're just invoking dart2js directly. @jakemac53 that is for the entrypoint URI, correct? I wonder why that would change type resolution

**Comment by jonahwilliams** [comment]
At any rate, I can try that and see if it fixes the issue

**Comment by jakemac53** [comment]
The uris within the entrypoint are resolved relative to the uri for the entrypoint itself - so if the entrypoing is `lib/main.dart` and it sees a relative import to `foo.dart` then the uri for `foo.dart` will be just `lib/foo.dart` and not `package:blah/foo.dart`.

**Comment by jakemac53** [comment]
Fwiw I believe the dart VM automatically rewrites the entrypoint uri to a `package:` uri equivalent if possible so regular flutter projects wouldn't see this difference. It sounds like dart2js doesn't do that.

**Comment by jonahwilliams** [comment]
Additionally, the frontend_server will complain, but do the mapping automatically. We already have code in the tool to do this so it should be a quick fix, but the behavior is surprising

**Comment by sigmundch** [comment]
> The import uri within the entrypoint are resolved relative to the uri for the entrypoint itself - so if the entrypoint is lib/main.dart and it sees a relative import to foo.dart then the uri for foo.dart will be just lib/foo.dart and not package:blah/foo.dart (and these are not equivalent libraries since they are identified by their uri).

Precisely: in Dart two libraries are considered different if they are imported via different URIs. So if you have in the same program both `package:blah/foo.dart` and `/path/to/the/same/foo.dart`, even if they are the same file, they are treated as if they are different. That then causes confusing errors like the one reported above.

> Fwiw I believe the dart VM automatically rewrites the entrypoint uri to a package: uri equivalent if possible so regular flutter projects wouldn't see this difference. It sounds like dart2js doesn't do that.

Actually, the logic is in the CFE and dart2js sometimes does it too. Because this issue is common, the common front-end has some logic to reverse the entrypoint if it can tell that it is in the `lib` folder of a library. I'm not sure why in your case it didn't. Maybe it couldn't find the .packages file in a standard location? Maybe the CFE doesn't do it if you give it an absolute path (I haven't looked at the logic to be honest)

**Comment by sigmundch** [comment]
> Additionally, the frontend_server will complain, but do the mapping automatically. 

Right - I'm surprised why it didn't map it automatically in this case :-/
