### ISSUE TITLE
Platform views enabled by default

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#44602]
Now that we've landed some of the crucial engine fixes for platform views in flutter/flutter@20169f0d2f6b4b4e8d9d943704b5fe034a225db4, we can start testing enabling platform views by default.

Step one is adding a platform view to the Gallery example app and checking to see if any of the benchmarks regress. If they do we'll need to go back and apply fixes to PlatformViews code to try and fix the regression, then repeat.

/cc @cyanglaz @amirh

**Comment by Sunbreak** [comment]
As https://github.com/flutter/engine/pull/20671, https://github.com/flutter/engine/pull/22275 and https://github.com/flutter/engine/pull/22372 landed, shall we close this issue?

**Comment by cyanglaz** [comment]
@Sunbreak Yes!
