### ISSUE TITLE
Cannot use trackpad 'back' gesture with Flutter for Web

### ISSUE THREAD

**Issue by owenmech** [flutter/flutter#44607]
Chrome typically allows users to go back by sliding two fingers to the right. This shortcut does not work on sites built with Flutter, making it necessary to click the back button within chrome to go back a page. 
I assume this is something to do with Flutter capturing gestures?

**Comment by iapicca** [comment]
Hi @owenmech 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/23604
)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
