### ISSUE TITLE
Crash during process teardown in fml_unittests.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#44614]
This [appears to be flaky](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8897169462936755296/+/steps/Host_Tests_for_host_debug_unopt/0/stdout).

**Comment by chinmaygarde** [comment]
This happened again today. Investigating.

**Comment by goderbauer** [comment]
Closing as https://github.com/flutter/engine/pull/13921 mentions that this is fixed.

**Comment by chinmaygarde** [comment]
That PR was closed. Not landed.
