### ISSUE TITLE
Remove RenderSliverFillViewport since it has no widget

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#44612]
We seem to have deprecated the render object without leaving a widget in place to use it. We should just remove it.

History: https://github.com/flutter/flutter/pull/37024

**Comment by Hixie** [comment]
cc @goderbauer @LongCatIsLooong

**Comment by goderbauer** [comment]
Yes, that sounds good.

**Comment by Hixie** [comment]
(We may want to make sure https://github.com/flutter/flutter/issues/39060 is solved first.)

**Comment by TheBiirb** [comment]
@Hixie I believe the PR was reverted, which means RenderSliverFillViewport is not deprecated anymore. Right?

**Comment by Hixie** [comment]
RenderSliverFillViewport is not currently marked deprecated. It seems weird that we don't have a widget for it though.

**Comment by goderbauer** [comment]
It also appears to have a widget `SliverFillViewport`, which uses the RenderObject internally. I am going to close this one.

**Comment by LongCatIsLooong** [comment]
My first attempt got reverted because of a benchmark regressed: https://github.com/flutter/flutter/issues/39060. Had to take a different approach that keeps using `RenderSliverFillViewport`
