### ISSUE TITLE
Shrine: text color in OS status bar is very hard to read

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4461]
![screen shot 2016-06-08 at 11 04 16 am](https://cloud.githubusercontent.com/assets/5479/15905398/98b35f30-2d69-11e6-83c2-cb20bac8077e.png)

Notice how we can't see the wifi status, etc.

I think we need to turn the text color black in the OS bar at the very top.

**Comment by eseidelGoogle** [comment]
@abarth says the change here is to make the AppBar control the color of the status bar.  @tvolkert added the ability to change the status bar color recently.

**Comment by tvolkert** [comment]
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/system_chrome.dart#L101

Example usage: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/title.dart#L47
