### ISSUE TITLE
Add an `onPageCancelled` callback to PageView widget

### ISSUE THREAD

**Issue by yanchaow90** [flutter/flutter#44623]
Hi, 
Our app implemented a photo frame UI using Flutter's PageController and PageView. The UI shows user one photo at a time and allow user to swipe to previous/next photo. 

We want to have an animationEndCallback() in PageController which is called after pointer up event and swipe animation is finished so that we can fire a swipe cancel event at that point. 

The swipe cancel event indicates after user points up and animation is finished, the current photo isn't changed to previous or next photo. For instance, if the user swipes but then slowly moves his finger back bringing the current photo back to its place, a swipe cancel event should be fired. if the user jiggles the photo back and forth by dragging left and right, it should fire a swipe finish event when photo is changed and swipe cancel event when photo is not changed. 

We cannot detect the swipe cancel event from pointer up event because we don't know whether the widget code will animate the photo to next one or current one at the point of finger_up event. 

Could you please add this for us?

Many thanks

**Comment by mehmetf** [comment]
To give more color to this:

The ultimate request is to be able to detect when the user started a gesture (swipe or scroll) to switch a Page but then didn't and the current page snapped back into place. Customer:Dream would like to have a way of detecting that the user "did not" switch the page.

Currently there's a callback:

```dart
ValueChanged<int> onPageChanged,
```
on PageView. Ideally, we should have another callback:

```dart
VoidCallback onPageChangeCancelled,
```
which gets called *once* after the user gesture completes and the "current page" snaps back into place.

**Comment by yanchaow90** [comment]
Hi,
Can I work on this myself?
My current solution is:
1. In [ScrollSpringSimulation](https://github.com/flutter/flutter/blob/a46d1791fc79ba9fa52cb6b502e747c427846609/packages/flutter/lib/src/physics/spring_simulation.dart#L127), add a `isScrollCancelled` flag to indicate if this simulation simulates scroll cancel animation.
2. In [PageScrollPhysics.createBallisticSimulation()](https://github.com/flutter/flutter/blob/a46d1791fc79ba9fa52cb6b502e747c427846609/packages/flutter/lib/src/widgets/page_view.dart#L503), create ScrollSpringSimulation with isScrollCancelled = true if `velocity >= -tolerance.velocity && velocity <= -tolerance.velocity`. (Need to refactor _getTargetPixels())
3. In [ScrollPositionWithSingleContext.goBallistic()](https://github.com/flutter/flutter/blob/57a93419b4d3f952733583cca3ae436c38670509/packages/flutter/lib/src/widgets/scroll_position_with_single_context.dart#L147), fire a **ScrollCancelledNotification** if `simulation.isScrollCancelled == true` 
4. In [_PageViewState.build() onNotification](https://github.com/flutter/flutter/blob/57a93419b4d3f952733583cca3ae436c38670509/packages/flutter/lib/src/widgets/page_view.dart#L807), capture the **ScrollCancelledNotification** and call **onPageScrollCancelled** callback

Let me know if my solution makes sense.

Thanks

**Comment by yanchaow90** [comment]
Don't need this anymore since I find a workaround

**Comment by sirawatGG** [comment]
It's surprised me that Pageview doesn't have this as default.
@yanchaow90 Could you share the workaround please
