### ISSUE TITLE
Poor file watching system.

### ISSUE THREAD

**Issue by jonataslaw** [flutter/flutter#44627]
My team decided to migrate an app that has millions of downloads to Flutter. The app has a simple Screenshot detection system: It listens for changes in MediaStore and displays a screenshot alert to warn the other print user.

However, Flutter does not yet have an efficient file watcher system.
The Dart team has a plugin that can hear file changes:
https://github.com/dart-lang/watcher

However, the current path_provider plugin makes no mention of MediaStore, preventing the creation of a package that does this and the functionality in the application.

So we decided to follow the same steps we took with React Native, create a security screen
https://medium.com/@jonaskuiler/creating-a-security-screen-on-ios-and-android-in-react-native-97703092e2de

However, this is not possible either. It would be possible to control flags on the native android side, creating this in active code, however, there is nothing that can do the same on the iOS side.
Cross platform technologies like RN, Xamarin and etc have mechanism for this, only Flutter has to do that.
This prevents larger applications from migrating to Flutter.

**Comment by stuartmorgan** [comment]
> However, the current path_provider plugin makes no mention of MediaStore, preventing the creation of a package that does this and the functionality in the application.

It's not clear to me what the feature request for path_provider is exactly here. What directory, specifically, are you looking for an accessor for?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
