### ISSUE TITLE
Lint error with CustomScrollView

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#44621]
**This doesn't happen in ListView, just CustomScrollView.**
--
Lint warns me I should add `const` to the expression:
```dart
const list = ["a", "b", "c"];
return CustomScrollView(
    slivers: <Widget>[
        for (var key in list) ...[
            SliverPadding(padding: EdgeInsets.all(4)),
        ],
    ],
);
```

<img  src="https://user-images.githubusercontent.com/351125/68630490-5556a980-04c6-11ea-900e-e469235cce32.png"  width="400"></img>

But if I add it, I get compiler errors (basically 'for' is not supported in const):
```
Compiler message:
[...]
lib/screen_color_blindness.dart:110:47: Error: Not a constant expression.
                itemsList(values[key], color, itemWidth),
                                              ^^^^^^^^^
lib/screen_color_blindness.dart:110:17: Error: Method invocation is not a constant expression.
                itemsList(values[key], color, itemWidth),
                ^^^^^^^^^
lib/screen_color_blindness.dart:108:15: Error: 'for' is not supported in constant expressions.
              for (var key in values.keys) ...[
              ^^^
```

So.. there is a problem with the linter. It should work in CustomScrollView the same was as ListView regarding const (i.e. don't ask me to add const when I can't!).

This is the same issue as https://github.com/flutter/flutter/issues/44286, which was abruptly closed as a mistake and I can't re-open.

**Comment by iapicca** [comment]
Hi @bernaferrari 
I apologize, I missed your answer on the closed issue.
Moreover in my [answer](https://github.com/flutter/flutter/issues/44286#issuecomment-550998729) I misunderstood the issue;
if you want to remove the warning, please try changing in your `pubspec.yaml` the sdk,
if you are using the latest stable version the following would be sufficient:

```
environment:
  sdk: ">=2.5.0 <3.0.0"
```

[screenshot ](https://user-images.githubusercontent.com/45637986/68672451-4f120d00-055a-11ea-8ba3-75f206a181a9.png)

Please let me know if this solution fix the issue.
thank you

**Comment by bernaferrari** [comment]
That's weird. I'm using `sdk: ">=2.6.0-dev.1.0.flutter-d6c6d12ebf <3.0.0"` which is almost the latest thing. 
![image](https://user-images.githubusercontent.com/351125/68688486-91811d00-054d-11ea-819d-b03ffa857d3b.png)

**Comment by srawlins** [comment]
I'm a little concerned about the `sdk: ">=2.6.0-dev.1.0.flutter-d6c6d12ebf <3.0.0"` string. What if you use `sdk: ">= 2.6.0 <3.0.0"`? I' also concerned by what appears to be a &ge; character. I'm fairly certain that is not recognized. Use `>=`.

**Comment by bernaferrari** [comment]
Exactly the same. 2.6.0 wasn't stable when this issue was opened and the version I used guaranteed you were using the last available version, to avoid the "hey, did you try this in the last dev version instead of stable?" scenario.

**Comment by iapicca** [comment]
Hi @bernaferrari 
with the latest stable version you can set you pubspec as follow
```
environment:
  sdk: ">=2.7.0 <3.0.0"
```
does this solves the issue?
Thank you

**Comment by bernaferrari** [comment]
This has been fixed.
