### ISSUE TITLE
TextField Widget labelText position

### ISSUE THREAD

**Issue by vikeychen** [flutter/flutter#44642]
## Steps to Reproduce
Just create a `TextField` Widget, set label, and when set filled to true and fillColor. The `labelText` position is not right

**Target Platform:**
Flutter 1.10.15 • channel dev
**Target OS version/browser:**
android 9
**Devices:**
Redmi 7A

Below is a textfield which one has set fillcolor and one not

![IMG_20191112_114556](https://user-images.githubusercontent.com/3364975/68640253-1cf4b100-0542-11ea-8ae1-419ddf637515.jpg)
![IMG_20191112_114535](https://user-images.githubusercontent.com/3364975/68640255-1cf4b100-0542-11ea-883b-e675d1bb73d1.jpg)

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/40444

**Comment by HansMuller** [comment]
@iapicca - Not sure what the #40444 reference was supposed to indicate. This doesn't appear to be a duplicate issue.

**Comment by iapicca** [comment]
@HansMuller - I've pasted the wrong issue :/

**Comment by TahaTesser** [comment]
Hi @vikeychen 
Looks like filled `TextField` match material guidelines 

### Fluter TextField 
![flutter_04](https://user-images.githubusercontent.com/48603081/81185727-950ed180-8fcf-11ea-89cd-f9326744fc81.png)

###  [ Material Guidline  Label text](https://material.io/components/text-fields#anatomy)
<img width="319" alt="Screenshot 2020-05-06 at 7 25 22 PM" src="https://user-images.githubusercontent.com/48603081/81185756-9dffa300-8fcf-11ea-9b51-7231af384df6.png">

if you disagree please write in the comments and I will reopen it
Thank you

**Comment by vikeychen** [comment]
I mean when set filled will influence widget position, The position will not right.

> Hi @vikeychen
> Looks like filled `TextField` match material guidelines
> 
> ### Fluter TextField
> ![flutter_04](https://user-images.githubusercontent.com/48603081/81185727-950ed180-8fcf-11ea-89cd-f9326744fc81.png)
> 
> ### [ Material Guidline Label text](https://material.io/components/text-fields#anatomy)
> <img alt="Screenshot 2020-05-06 at 7 25 22 PM" width="319" src="https://user-images.githubusercontent.com/48603081/81185756-9dffa300-8fcf-11ea-9b51-7231af384df6.png">
> 
> if you disagree please write in the comments and I will reopen it
> Thank you

I mean when set filled will influence widget position, The position will not right.

**Comment by TahaTesser** [comment]
Hi @vikeychen 
Can you please provide sample code sample to better address the issue
Thank you
