### ISSUE TITLE
AutoSizeText or TextPainter expansion

### ISSUE THREAD

**Issue by DarrylDJohnson** [flutter/flutter#44662]
Only one solution for an AutoSizeText widget exists, and it is not a very good one. Can the Flutter Devs please add this widget to the next update? 

If not, a very simple alternative solution would be improving the TextPainter. I'm using it to calculate the space it takes up. There's just one huge problem. The getters for height and width have little if not anything to do with the TextPaint as a whole. I'm not even sure what those values relate to? Maybe the height for the tallest word and the width for the widest word. If the TextPainter could return an accurate height and width, the AutoSizeText widget could be easily created.

**Comment by goderbauer** [comment]
Could you explain what an AutoSizeText widget would do?
