### ISSUE TITLE
HARD migration from java/xml to dart/flutter

### ISSUE THREAD

**Issue by SupinePandora43** [flutter/flutter#44667]
Documentation needs page with migration from xml to flutter, showed on simple components, and they analogs in flutter.

like

java/xml | dart/flutter
--- | ---
`LinearLayout` | `Row`, `Column`
`TextView` | `Text`

**Comment by kf6gpe** [comment]
We've currently got https://flutter.dev/docs/get-started/flutter-for/android-devs to discuss transitioning for Android developers. Closing this issue for now.
