### ISSUE TITLE
Could not find an option named "depfile".  

### ISSUE THREAD

**Issue by 592357390** [flutter/flutter#44670]
when i build my project with Android studio，i got this error ：
Could not find an option named "depfile".

**Comment by iapicca** [comment]
Hi @592357390 
could you please provide your updated  `flutter doctor -v`
and your  `flutter build --verbose` ?
Thank you

**Comment by phoelapyae69** [comment]
I got the same issue
`Launching lib/main.dart on SM A705F in debug mode...
Initializing gradle...                                              0.9s
Resolving dependencies...                                           2.5s
Could not find an option named "depfile".                               
                                                                        
Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/usr/local/Cellar/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 776
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildDebug'.              
> Process 'command '/usr/local/Cellar/flutter/bin/flutter'' finished with non-zero exit value 64
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1s                                                      
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         2.6s
Gradle task assembleDebug failed with exit code 1`
Help me please

**Comment by iapicca** [comment]
Hi @phoelapyae69 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by kf6gpe** [comment]
I'm going to close this issue summarily as we've asked participants for a minimal repro & `flutter doctor` output a few times. If it's still an issue, please reopen with a minimal repro and `flutter doctor` output. Thanks!
