### ISSUE TITLE
[text] Chinese fonts are not vertically-aligned on Android

### ISSUE THREAD

**Issue by baij930312** [flutter/flutter#44688]
```
Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              '中文',
            ),
            Text(
              'ABCD',
            ),
            Text(
              '中文ABCD',
            ),
          ],
        ),
```
android:
![Screenshot_20191112_185643_com example asd](https://user-images.githubusercontent.com/38178903/68666567-1c2e4000-057f-11ea-88a2-998f033e5653.jpg)

ios is fine:
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-12 at 19 06 35](https://user-images.githubusercontent.com/38178903/68666859-a5de0d80-057f-11ea-8daf-f88bb4aaa528.png)

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/imac/flutter
    • Framework revision 68587a0916 (8 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/imac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

```
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • EML AL00 • CLB7N18C14009706 • android-arm64 • Android 9 (API 28)

• No issues found!


```

**Comment by yintaibing** [comment]
Facing same issue for a long time...
Actually, in 2 cases(Chinese chars + English chars, only English chars), I found the text's vertical position would be different

**Comment by ozyl** [comment]
The same problem.Is there a solution?

**Comment by Liuzhiyang94** [comment]
so.. any updates?

**Comment by hhkkyy** [comment]
Same problem.

**Comment by yintaibing** [comment]
Set a specific `height` of `TextStyle` may help. In my case, 1.25 is good. And use a global `TextTheme` is recommended(the `body` attr).

**Comment by GaryQian** [comment]
Since the 3 blocks of text are separately laid out, they are only aligned after their internal layout. The chinese font and english font have different heights. When the framework is trying to align the separate widgets, it does not have detailed knowledge of the font metrics and instead just works with the rough size and baseline dimensions of the text. We could be misreporting the baseline or possibly, the framework is just aligning everything by the top edge, which would absolutely cause misalignment.

Here are some suggestions to work around this for now as we look into this further:

- Use a single text widget. Try Text.rich which allows multiple TextSpans to create a complex paragraph. A single paragraph will be able to properly align text of multiple sizes.
- Try StrutStyle. StrutStyle allows minimum text heights and can also be used to force differently sized text to same height.
- Manually adjust to get things to align with existing properties such as height.

**Comment by Liuzhiyang94** [comment]
> Since the 3 blocks of text are separately laid out, they are only aligned after their internal layout. The chinese font and english font have different heights. When the framework is trying to align the separate widgets, it does not have detailed knowledge of the font metrics and instead just works with the rough size and baseline dimensions of the text. We could be misreporting the baseline or possibly, the framework is just aligning everything by the top edge, which would absolutely cause misalignment.
> 
> Here are some suggestions to work around this for now as we look into this further:
> 
> * Use a single text widget. Try Text.rich which allows multiple TextSpans to create a complex paragraph. A single paragraph will be able to properly align text of multiple sizes.
> * Try StrutStyle. StrutStyle allows minimum text heights and can also be used to force differently sized text to same height.
> * Manually adjust to get things to align with existing properties such as height.

But how to deal with this case .  `测试test1234`. By now they are not center align in a line. Should i split these into 3 `TextSpan` which contains chinese/english/num ?

**Comment by i-show** [comment]
Same problem.

**Comment by darshankawar** [comment]
Verified this on latest master and stable and see the text aligned properly.

![44688](https://user-images.githubusercontent.com/67046386/100098233-c5db2900-2e83-11eb-89db-82ba6371bade.png)

Tested on Android 8.1.0 device.

<details>
<summary>master and stable flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (11 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm • Android 8.1.0 (API 27)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86 • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!

[✓] Flutter (Channel master, 1.24.0-8.0.pre.356, on Mac OS X 10.15.4 19E2269 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.50.1)
[✓] Connected device (6 available)

```

</details>

I am going ahead and closing this as fixed. If you disagree or think this should be kept open, please write in comments and I'll reopen.
Thanks.

**Comment by lyf571321556** [comment]
so.. any updates? still  not vertically-aligned on Android
![image](https://user-images.githubusercontent.com/2295872/113824939-f24c6d80-97b2-11eb-998d-89b4fdcb5b62.png)

 flutter doctor -v
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on Mac OS X 10.15.5 19F101
    darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.1.0-12.2.pre at /Users/liuyanfeng/Library/flutter
    • Framework revision 5bedb7b1d5 (3 weeks ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by GaryQian** [comment]
@lyf571321556 The problem you are reporting is actually a different problem than the problem reported in this issue. This issue specifically deals with misalignment between multiple text widgets.

Can you please file an issue for the different issue you are reporting here where the single chinese text has higher ascent form baseline than descent? Thank you!

**Comment by lyf571321556** [comment]
> @lyf571321556 The problem you are reporting is actually a different problem than the problem reported in this issue. This issue specifically deals with misalignment between multiple text widgets.
> 
> Can you please file an issue for the different issue you are reporting here where the single chinese text has higher ascent form baseline than descent? Thank you!

#79931

**Comment by rockingdice** [comment]
> Verified this on latest master and stable and see the text aligned properly.
> 
> ![44688](https://user-images.githubusercontent.com/67046386/100098233-c5db2900-2e83-11eb-89db-82ba6371bade.png)
> 
> Tested on Android 8.1.0 device.
> 
> master and stable flutter doctor -v
> I am going ahead and closing this as fixed. If you disagree or think this should be kept open, please write in comments and I'll reopen.
> Thanks.

So how do you test this case? Can you provide any codes?
I'm still having the same issue on the latest stable channel.

I'm using separate `Text` widgets since they cannot be in one TextSpan. They are in different columns but with same vertical offsets, imagine it's a `Table` like widget.
They are not aligned vertically.
![image](https://user-images.githubusercontent.com/3458134/118075966-b2952900-b3e3-11eb-8735-54b2ed09e6d3.png)

I think this issue is not fixed at all - why cannot they be aligned by default, instead we have to do extra work to fix it? I think it's engine related issue and the users should not pay extra attension to different languages when using `Text` or other text widgets.

Please reopen this issue and fix it.

**Comment by GaryQian** [comment]
@rockingdice Your use case should be implemented as: 
```
Text.rich(
  TextSpan(
    children: <TextSpan>[
      TextSpan(text: '中文', style: TextStyle(...)),
      TextSpan(text: ' Lvl.7', style: TextStyle(...)),
    ]
  )
)
```

**Comment by chinmaygarde** [comment]
@GaryQian Did you mean to open the issue?
