### ISSUE TITLE
iOS Crash for running new Flutter project

### ISSUE THREAD

**Issue by JohannesMilke** [flutter/flutter#44686]
I get the following error for running a brand new 'flutter create' project on my iOS simulator.

Running on iOS Simulator Xs - 12.4 

```Launching lib/main.dart on iPhone Xs in debug mode...
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                           6.0s
 └─Compiling, linking and signing...                        11.3s
Xcode build done.                                           19.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    2019-11-12 11:43:05.182 ibtoold[63428:6074856] DEBUG: Added to environment:
    {
        TMPDIR =
        "/var/folders/pc/_wcgpdj137l4w2b5pnrqhnvw0000gn/T/D7C02B26-93DE-4D49-802
        B-422A6B3C8297";
    }
    objc[63443]: task_threads failed (result 0x10000003)

    Command CompileAssetCatalog failed with a nonzero exit code
    note: Using new build systemnote: Planning buildnote: Constructing build
    descriptionwarning: Capabilities for Signing & Capabilities may not function
    correctly because its entitlements use a placeholder team ID. To resolve
    this, select a development team in the Runner editor. (in target 'Runner'
    from project 'Runner')

Could not build the application for the simulator.
Error launching application on iPhone Xs.
```

**Flutter doctor**

```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale
    en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by jmagman** [comment]
This looks like a Xcode bug.  https://stackoverflow.com/questions/52489500/command-compileassetcatalog-failed-with-a-nonzero-exit-code

Try deleting DerivedData (instructions in the SO post) and running again.

**Comment by JohannesMilke** [comment]
It still doesn't work if i delete the derivedData while xcode is closed. @jmagman Even if I run **Build Clean** (both CMD+SHIFT+K and CMD+ALT+SHIFT+K) it still crashes with the same error

`Command CompileAssetCatalog failed with a nonzero exit code`

**Comment by jmagman** [comment]
Did you edit your assets catalog?

**Comment by JohannesMilke** [comment]
@jmagman I don't now how I should have edit it. So i don't think so. On android everything is fine though.

**Comment by jmagman** [comment]
Can you share an app that reproduces the issue?

**Comment by JohannesMilke** [comment]
Alright i solved the issue by deleting XCode on my computer and reinstall it completely.
Before i had version XCode 11 and now XCode 11.21.

**Comment by TrigonaMinima** [comment]
This helped me: Go to Xcode preferences -> accounts and sign in to your Apple account (or any other account listed there). After running the project again, it worked fine.
