### ISSUE TITLE
Renaming our firebase project to FlutterFire

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4469]
To match the common pattern of `<PlatformOrLanguage>Fire`, as per the Firebase team.

**Comment by sethladd** [comment]
FYI @collinjackson

**Comment by sethladd** [comment]
Repo has been renamed: https://github.com/flutter/flutterfire

Now to update the pubspec, readme, etc...

**Comment by sethladd** [comment]
We may also want to rename the library itself. Right now, the library name is `firebase`.

**Comment by collinjackson** [comment]
I agree that we should rename the library itself. we'll be doing a codelab update to add a Google Sign-In step and I think we can make that change at the same time.

**Comment by sethladd** [comment]
Cool, thanks. Reassigned over to you.

**Comment by sethladd** [comment]
We'll get back to this, and as we do, this will naturally fix itself.

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1020. Any further collaboration will be done there.
