### ISSUE TITLE
Flutter - The following assertion was thrown building MyApp(dirty): Expected a value of type 'MaterialColor', but got one of type 'Color'

### ISSUE THREAD

**Issue by lucasellery** [flutter/flutter#44696]
Font manifest does not exist at `assets/FontManifest.json` – ignoring.
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building MyApp(dirty):
Expected a value of type 'MaterialColor', but got one of type 'Color'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was:
MyApp org-dartlang-app:///packages/doglife/main.dart:4:23

When the exception was thrown, this was the stack:
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 194:49      throw_
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 43:3        castError
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 424:10  cast
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/classes.dart 520:14     check_C
package:doglife/main.dart 13:14                                                           build
package:flutter/src/widgets/framework.dart 4026:28                                        build
package:flutter/src/widgets/framework.dart 3958:15                                        performRebuild
package:flutter/src/widgets/framework.dart 3755:5                                         rebuild
package:flutter/src/widgets/framework.dart 3941:5                                         [_firstBuild]
package:flutter/src/widgets/framework.dart 3936:5                                         mount
package:flutter/src/widgets/framework.dart 3109:13                                        inflateWidget
package:flutter/src/widgets/framework.dart 2903:12                                        updateChild
package:flutter/src/widgets/binding.dart 1028:16                                          [_rebuild]
package:flutter/src/widgets/binding.dart 999:5                                            mount
package:flutter/src/widgets/binding.dart 942:16                                           <fn>
package:flutter/src/widgets/framework.dart 2327:19                                        buildScope
package:flutter/src/widgets/binding.dart 941:12                                           attachToRenderTree
package:flutter/src/widgets/binding.dart 818:24                                           attachRootWidget
package:flutter/src/widgets/binding.dart 804:7                                            <fn>
package:dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19           internalCallback

**Comment by iapicca** [comment]
Hi @lucasellery 
could you please provide your updated  `flutter doctor -v`
and your `flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
