### ISSUE TITLE
Allow for continuous, repeating Performances, without 'paused frames'

### ISSUE THREAD

**Issue by jestelle** [flutter/flutter#447]
I'm working on an update to the CircularProgressIndicator to bring it in line with the Material Design spec (you can see the reasonably correct, although still not perfect Polymer implementation here: https://elements.polymer-project.org/elements/paper-spinner?view=demo:demo/index.html&active=paper-spinner)

This activity indicator will spin indefinitely until it's hidden or stopped.

While I haven't verified it, it appears in my current implementation there may be a 'paused frame' each time my performance is restarted.  By 'paused frame', I mean something different from a dropped frame, but rather a frame where the animation just stops progressing for a frame – when the performance is started again.

So what I'd like, is the ability to specify a number of iterations (which could be infinite) for a Performance, so that I can expect the animation to be perfectly smooth between the end state of one iteration and the start state of the next.

@Hixie and I discussed this a bit and may be able to provide more context

Below is some sample code of what I'm currently doing (I can point you at the full code if that is helpful).  Ideally I'd replace the 'Performance' with some new class... 'ContinuousPerformance'... or maybe I'd just use a Performance with a new argument 'iterations'?  And I'd be able to remove my status listener that restarts the Performance.

Please let me know if you need any more detail.

    _performance = new Performance(duration: new Duration(milliseconds: _kTotalDuration));

    _strokeHeadProgress = new AnimatedValue<double>(0.0, end: 1.0,
        curve: new Interval(0.0, 0.5, curve: Curves.fastOutSlowIn));

    _strokeTailProgress = new AnimatedValue<double>(0.0, end: 1.0,
            curve: new Interval(0.5, 1.0, curve: Curves.fastOutSlowIn));

    _circleRotation = new AnimatedValue<double>(0.0, end: 0.85, curve: Curves.linear);

    _stepIndex = 0;

    _performance.addStatusListener((PerformanceStatus status) {
      if (status == PerformanceStatus.completed) {
        _stepIndex++;
        if (_stepIndex >= 5) _stepIndex = 0;
        _restartAnimation();
      }
    });
    _performance.play();

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/454 adds a `repeat` function to `Performance`

**Comment by jestelle** [comment]
Thanks for adding this repeat capability @abarth 

Unfortunately I can't achieve the behavior I want using this yet, or at least I don't see how to.

This issue is that what is rendered in my animation actually changes on each repetition of the performance.  This is because most of the animation exactly repeats itself every period, but the whole thing has to be rotated step-wise with each repetition.

You can see how I do that with my code snippet and the _stepIndex variable above.
I use that variable at paint time, to adjust where I start drawing things, effectively rotating based on that index.

Would it be possible to add a PerformanceStatus event that is fired after each repeated repetition?
Or can you help me find a better way? :D  Thanks!

**Comment by Hixie** [comment]
Just multiply all your periods out, and use that as the period of one
complete cycle.

So for example if you did something every 2 seconds and something every 3
seconds, you'd set the period to 6 seconds, and then do the first thing 3
times over that 6 seconds, and the second thing 2 times over that 6 seconds.

**Comment by abarth** [comment]
You could also trigger _stepIndex each time you saw the progress of the animation go down.

**Comment by jestelle** [comment]
@Hixie I considered that, but I don't see any obvious mechanism to do it.

In theory I could start two simultaneously running performances, one with a duration of 2s, the other with a duration of 3s, and have them each repeat.  (aside:  if I started them at the same time, could I be confident they would be in perfect sync?)

But my Widget build uses a BuilderTransition, which can only take a single performance as an argument.  So I didn't see how to do that with multiple performances without a bunch of hackery.


@abarth I'll try that.  I think that should work – but I might still argue for an event that could be listened for, as it seems like that might be clearer.

cc @pingpongboss since we had discussed some of these things a while back

**Comment by Hixie** [comment]
Wherever you use the performance value, where the performance has a period of 6 seconds:
* if you wanted the value of a performance with period 2 seconds:
  * take the value, multiply it by three, then subtract the truncated value.
* if you wanted the value of a performance with period 3 seconds:
  * take the value, multiply it by two, then subtract the truncated value.

As in:

```dart
   // "peformance.view" is 0..1 over 6 seconds
   double value = performance.value * 3.0;
   value -= value.truncateToDouble();
   // here "value" is 0..1 over 2 seconds
```

**Comment by jestelle** [comment]
Good idea @Hixie 
That would work, but I don't ever actually use the performance.value directly.
I use AnimatedValue's passed into the BuilderTransition.
I could always write my own replacement for BuildTransition that does this sort of thing, which might be reasonable if we expect what I'm trying to do to be uncommon.  


I tried @abarth 's approach, which seems to work pretty well, but I did it by hacking into performance.dart to trigger an event that I can listen to.  Which probably has some consequences other places such that it's not a good general solution.

I'm having trouble finding where in my code I get the complete stream of progress updates, and I can modify the 'state' of my component.  I may need to understand better how it's appropriate handle the state of components, particularly as they're animating.

**Comment by Hixie** [comment]
You could wrap your animation values in adapters that do the multiplication for you (untested code ahead):

```dart
class AnimatedValueAdapter {
  AnimatedValueAdapter(this.value, this.factor);
  AnimatedValue value;
  int factor;
  void setProgress(double t, AnimationDirection direction) {
    t = t * factor;
    t -= t.truncateToDouble();
    value.setProgress(t, direction);
  }
}
```

Then if your animated value is called `x`, pass a `new AnimatedValueAdapter(x, 3)` where you're passing in `x` today (and similar for the one you multiply by two).

Eventually this will be much easier, see https://github.com/flutter/flutter/issues/215.

**Comment by jestelle** [comment]
Ooh I like that.  I may try something like that and I'll let you know how it fares.

And I'll watch #215 closely and look forward to new hotness

**Comment by pingpongboss** [comment]
@Hixie Glad to hear improvements are coming. I'm not in love with the current suggestions - they feel hacky and unreadable.

Just want to throw in my 2c. During my limited experience with Flutter, I also felt constrained by the one Performance per BuilderTransition pattern. In more complicated animations with multiple AnimatedValues, it felt roundabout to have to convert all the different delays and durations into percentages of the Performance. And in Josh's example where multiple AnimatedValues of different durations are infinitely repeating, you'd have to do some funky least-common-multiple math to arrive at a Performance duration that makes sense. For example, a 11-duration repeating AnimatedValue and a 13-duration repeating AnimatedValue needs to be hosted in a 143-duration repeating Performance.

**Comment by abarth** [comment]
You can always nest BuilderTransition, but we can also make a builder transition that takes multiple performances.
