### ISSUE TITLE
Expose Clientchannel constructor in Dart gRPC to support UNIX domain sockets

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#44714]
https://b.corp.google.com/issues/143528277. 

cc @a-siva -- can you help route? Should I open a parallel issue in the dart-lang repository for this issue?

**Comment by Hixie** [comment]
Looks like we are blocked until the Dart team implements this then we'll have to expose something in our embedding API.

**Comment by chinmaygarde** [comment]
> expose something in our embedding API.

Can you clarify this? It is not clear how this affects the engine or the embedder API.

**Comment by Hixie** [comment]
Not sure, that was a note taken during our triage meeting. cc @cbracken, do you recall what that was about? If there's nothing for us to add (and it's all in gRPC exclusively) then we can close this.

**Comment by Hixie** [comment]
Sounds like this is not something we need to do anything about in Flutter itself.
