### ISSUE TITLE
gen_localizations.dart: inexplicable diffs, no intl package license headers found

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#44728]
On a fresh branch sync'd with master the gen_localizations command produces changes, even though the "packages/flutter_localizations/lib/src/l10n/*.arb" files haven't changed in a while:
```dart
flutter update-packages
dart dev/tools/localization/gen_localizations.dart --overwrite
```

This currently fails the analyzer test (on my machine) because it can't find headers in the intl package sources:
```
(cd ~/github/flutter; dart --enable-asserts ./dev/bots/analyze.dart)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
License headers cannot be found at the beginning of the following files.

/usr/local/google/home/hansmuller/github/flutter/packages/flutter_tools/.dart_tool/pub/deps/debug/intl/lib/date_symbol_data_http_request.dart
/usr/local/google/home/hansmuller/github/flutter/packages/flutter_tools/.dart_tool/pub/deps/debug/intl/lib/intl.dart
/usr/local/google/home/hansmuller/github/flutter/packages/flutter_tools/.dart_tool/pub/deps/debug/intl/lib/date_symbol_data_local.dart
....
```
I'm running Dart 2.7 etc.
```
flutter --version
Flutter 1.10.17-pre.60 • channel master • git@github.com:flutter/flutter.git
Framework • revision 99055c754a (79 minutes ago) • 2019-11-12 08:04:48 -0800
Engine • revision 31cd2dfca2
Tools • Dart 2.7.0
```

**Comment by jmagman** [comment]
@gspencergoog Is this fixed by https://github.com/flutter/flutter/pull/44736?

**Comment by gspencergoog** [comment]
Well, it depends on what you mean by "fixed".  It fixes the build.  It doesn't shed any light on *why* we have inexplicable diffs, which remain inexplicable.

**Comment by HansMuller** [comment]
This may be the remedy: https://github.com/flutter/flutter/pull/44743

**Comment by jmagman** [comment]
@shihaohong's PR beat my question by mere seconds.

> Well, it depends on what you mean by "fixed". It fixes the build. It doesn't shed any light on _why_ we have inexplicable diffs, which remain inexplicable.

🤔 Existential.

**Comment by shihaohong** [comment]
Huge shoutout to @yjbanov for uncovering the mystery :)
