### ISSUE TITLE
[android_alarm_manager] Android alarm manager does not fire

### ISSUE THREAD

**Issue by EdSabino** [flutter/flutter#44730]
I follow the example on the package and try to make it work, i do:

```
void printHello() {
    print('something');
}|
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  print(await AndroidAlarmManager.initialize());
  ...
  runApp(AmoGo());
  print(await AndroidAlarmManager.oneShot(const Duration(seconds: 5), 0, printHello));
}
```
then i initiate the app, and 'something' is never printed, theres is no error, not even in the adb shell of the phone, nothing goes wrong, but the callback is not called.
ps: the example works on the phone, i dont know why.

## My output

```
Launching lib/main.dart on ASUS X00QD in debug mode...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
I/AlarmService(23935): Starting AlarmService...
I/RingtoneManager(23935): no .ape files
I/flutter (23935): true
I/FileSource(23935): fd=100 (/data/data/delivery.amo.go/cache/sound2333147592499013834pool), offset=0, length=34987
I/OMXClient(23935): IOmx service obtained
W/ExtendedACodec(23935): Failed to get extension for extradata parameter
I/RingtoneManager(23935): no .ape files
I/AlarmService(23935): AlarmService started!
I/flutter (23935): true
```

the flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.16, on Mac OS X 10.14.6 18G95, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.37.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by behzadcym** [comment]
I have the same problem
Any Suggestions?

**Comment by AlbertKamau** [comment]
What version of physical phone are you using. Its the opposite for me. I can get the output on the console but it doesnt work on my physical device

**Comment by TahaTesser** [comment]
Hi @EdSabino 
Are you still experiencing this issue with latest stable?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @EdSabino 
Could everyone who still has this problem please file a new issue with the exact descriptions
what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference
related issues.
Thank you
