### ISSUE TITLE
ScrollingDataTable

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4473]

**Comment by Hixie** [comment]
This is about making a lazy scrolling version of PaginatedDataTable. My plan was to have a DataColumnWithWidth class or some such, in which you give the pixel width, so that we never use intrinsic anything. (Probably wouldn't use DataTable, or even maybe Table.)

**Comment by Hixie** [comment]
When we do this, the API for the data should be the same as PaginatedDataTable.

**Comment by Piinks** [comment]
https://github.com/flutter/flutter/issues/87370 is the main issue we have been using to track this feature, I am going to close this to dedupe. The design doc is linked there as well.
