### ISSUE TITLE
just a warning...

### ISSUE THREAD

**Issue by jdeltoft** [flutter/flutter#44735]
Note: /Users/jeltoft/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+10/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by jmagman** [comment]
Duplicate of https://github.com/flutter/flutter/issues/28772.
