### ISSUE TITLE
Documentation: wrong link to new embedding in Add Flutter to extisting apps wiki

### ISSUE THREAD

**Issue by bDev10** [flutter/flutter#44767]
Actual [Add Flutter to extisting apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) wiki documentation has wrong link in [Flutter's new Android embedding](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#flutters-new-android-embedding) chapter.
The link "the pages dedicated to the new embedding" points to not existing page: https://github.com/flutter/flutter/wiki/Experimental:-Adding-Flutter-to-Android

**Comment by jmagman** [comment]
@xster Looks like you deleted that wiki page on November 6 with commit 7bf62f4a8f78afcc909a8dd111b4b6bccea4c6f7.  Can you update the link?

**Comment by xster** [comment]
Doh, editing the title changes the permalink. Edited the reference (and left a new link in the previous permalink for when we move everything to flutter.dev).
