### ISSUE TITLE
flutter run --release error, Android resource linking failed, resource android:attr/fontVariationSettings and android:attr/ttcIndex not found

### ISSUE THREAD

**Issue by pmagnuson** [flutter/flutter#44760]
`flutter run --debug` works fine.  `flutter run --release` fails to build.

```
flutter run --release
 
Launching lib/main.dart on Pixel 3 XL in release mode...
Note: /Users/phil/bin/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+10/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':path_provider:verifyReleaseResources'.      
> 1 exception was raised by workers:                                    
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/phil/Documents/flutter/geku/build/path_provider/intermediates/res/merged/release/values/values.xml:236: error: resource android:attr/fontVariationSettings not found.
  /Users/phil/Documents/flutter/geku/build/path_provider/intermediates/res/merged/release/values/values.xml:237: error: resource android:attr/ttcIndex not found.
  error: failed linking references.                                     
                         
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 52s                                                     
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      53.9s
Gradle task assembleRelease failed with exit code 1
```

Most of the online guidance suggests this is related to the AndoidX migration.  I have performed those steps in the Android Studio.  I have also performed a `flutter upgrade`, `Android Studio upgrade`, `flutter pub upgrade`.

```
flutter doctor -v
[✓] Flutter (Channel master, v1.10.17-pre.61, on Mac OS X 10.14.6 18G1012, locale en-US)
    • Flutter version 1.10.17-pre.61 at /Users/phil/bin/flutter
    • Framework revision d39e2bb776 (3 hours ago), 2019-11-12 10:27:58 -0800
    • Engine revision 31cd2dfca2
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/phil/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • Pixel 3 XL • 95EY1A3GC • android-arm64 • Android 10 (API 29)

• No issues found!
```

also now getting the warning listed in https://github.com/flutter/flutter/issues/28155

Any pointers appreciated.

**Comment by pmagnuson** [comment]
in pursuit of fixing this, I discovered that my system was on the `flutter channel master`.  I have changed to `flutter channel stable`.

At this point, `flutter run -v --debug` against a physical device (Pixel 3) fails.  The last part of the output is 

```
[  +99 ms] > Task :app:processDebugManifest
[+1303 ms] > Task :app:processDebugResources
[ +496 ms] > Task :app:compileDebugJavaWithJavac
[        ] > Task :app:compileDebugSources
[        ] > Task :app:validateSigningDebug
[  +91 ms] > Task :app:signingConfigWriterDebug FAILED
[        ]          *********************************************************
[        ] WARNING: This version of package_info will break your Android build if it or its dependencies aren't compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[        ]          *********************************************************
[        ] 60 actionable tasks: 55 executed, 5 up-to-date
[ +393 ms] Running Gradle task 'assembleDebug'... (completed in 22.2s)
[   +3 ms] "flutter run" took 51,922ms.
```

I have been through all the AndroidX migration steps multiple times.  Android Studio indicates there is no dependency on AndroidX.  `No Usages Found in the Project.`

I have tried modifying the package_info dependency to use `package_info: ^0.4.0+10` , `+3` and `+5` without any improvement.  

I was able to do the following without error, 

```
flutter create new_project
cd new_project
flutter run --debug
flutter run --release
```

so I assume there is something wrong with my dependencies and or gradle definitions.  This all worked before my last `flutter upgrade`.

I was also able to add the `package_info` dependency to the new_project and run successfully.  

I think this is something internal to my project definition.  Closing this issue until I have better info.

**Comment by pmagnuson** [comment]
closing.

**Comment by crazygo** [comment]
If your compile sdk is 28, you can 
1. remove all your packages and add someone to check if release works
2. check you all dependencies, if their android compile version is 28
3. make ture the proguard-rules is right

`
-keep class com.google.firebase.** { *; }

#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class com.twitter.**  { *; }`

**Comment by alexda12** [comment]
This issue outstanding since I upgraded to 1.12.13

https://github.com/flutter/flutter/issues/46881

**Comment by sarinupreti** [comment]
+ 1

**Comment by sarinupreti** [comment]
same here . getting the issue in 1.12.13

**Comment by dblqt** [comment]
I just migrated one of my projects to androidX and had the same issue. 
```
flutter run --debug
```
works, but
```
flutter run --release
```
does not.
What did the trick for me was running:
```
flutter run --release --verbose
```
the output then showed me which package was the actual source of the above error.
Changing its compileSdkVersion to 28 fixed the issue.

I found the cached package source under:
```
{path to flutter}\.pub-cache
```
I hope this useful for someone coming after me.

I wonder why debug works but release fails.

**Comment by chitgoks** [comment]
This is a painful problem and hard to pinpoint the cause because it does not point out the specifics.

**Comment by AdilTechDart** [comment]
From Android Studio goto > Tools > Flutter > Open for Editing in Android Studio 
After that, You will see all dependencies like this
![image](https://user-images.githubusercontent.com/37257868/71769276-d7040a00-2f40-11ea-8029-5c483819a37b.png)
Now open every "build.gradle" file and if you see "compileSdkVersion 27" in any file change it to 28 
:)

**Comment by JePoste** [comment]
> From Android Studio goto > Tools > Flutter > Open for Editing in Android Studio
> After that, You will see all dependencies like this
> ![image](https://user-images.githubusercontent.com/37257868/71769276-d7040a00-2f40-11ea-8029-5c483819a37b.png)
> Now open every "build.gradle" file and if you see "compileSdkVersion 27" in any file change it to 28
> :)

Or just use Cmd+Shift+R (Ctrl+Shif+R on Windows) if you are using Android Studio to open the deep search/replace window.
Fill the first field with "compileSdkVersion 27" and the second one with "compileSdkVersion 28" then hit "Replace All" (or "Replace" if you want to have a quick check on each matching occurence) :)

**Comment by kashifgrocerkey** [comment]
yes this solution works for me. In gradle script i find path_provider-0.4.1 is using compileSdkVersion 27, changed it to 28 fix my issue

**Comment by 1pavanb** [comment]
perfect 👌

**Comment by 1pavanb** [comment]
> From Android Studio goto > Tools > Flutter > Open for Editing in Android Studio
> After that, You will see all dependencies like this
> ![image](https://user-images.githubusercontent.com/37257868/71769276-d7040a00-2f40-11ea-8029-5c483819a37b.png)
> Now open every "build.gradle" file and if you see "compileSdkVersion 27" in any file change it to 28
> :)

perfect 👌

**Comment by krupeshxebia** [comment]
> From Android Studio goto > Tools > Flutter > Open for Editing in Android Studio
> After that, You will see all dependencies like this
> ![image](https://user-images.githubusercontent.com/37257868/71769276-d7040a00-2f40-11ea-8029-5c483819a37b.png)
> Now open every "build.gradle" file and if you see "compileSdkVersion 27" in any file change it to 28
> :)

Worked like Charm 💯
