### ISSUE TITLE
[elided hardware] GPU thread exceeds frame time at seemingly random time intervals

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#44775]
https://b.corp.google.com/issues/115499688. Conversation should occur there.

/cc @liyuqian.

**Comment by cbracken** [comment]
@liyuqian can you add a milestone to this?

**Comment by liyuqian** [comment]
@cbracken : sure, thanks for the remind!

**Comment by liyuqian** [comment]
We've confirmed that this is not a Flutter issue as it also happens on native Android without Flutter, and this is hardware/GPU specific. Closing this.
