### ISSUE TITLE
download_goldctl.sh should exit if any sub-command fails

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#44785]
## Use case
If a command, like cloning depot_tools, fails, exit the test.
```
ulimit -S -n 2048
./dev/bots/download_goldctl.sh
Cloning into './depot_tools'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
./dev/bots/download_goldctl.sh: line 4: cd: depot_tools: No such file or directory
./dev/bots/download_goldctl.sh: line 6: ./cipd: No such file or directory

Exit status: 127
```
https://cirrus-ci.com/task/5949937388355584?command=main#L0

## Proposal

Add `set -e` or move to a dart file and check the error codes.

**Comment by jmagman** [comment]
\cc @Piinks

**Comment by godofredoc** [comment]
\cc @Piinks are we still using this script?

**Comment by Piinks** [comment]
I believe so. This script is executed in the Cirrus builds.

**Comment by godofredoc** [comment]
Golds functionality was removed from cirrus and changes requested in this bug are not needed anymore.
