### ISSUE TITLE
Poor error message with setters.

### ISSUE THREAD

**Issue by hasen6** [flutter/flutter#44798]
I created a class:

```
class Test {
  int range = 1000;

  set setRng(int val) => range = val;

  get getRng => range;
}
```

If I type `test.setRng` the setter is underlined RED and it throws the error `The getter 'setRng' isn't defined for the class 'Test'.` This is a very poor error message since all it's missing is the value it needs to be set at, the setter is _certainly_ defined for the class. Adding `= 100` on the end makes the error disappear completely.

**Comment by goderbauer** [comment]
This sound like a problem with dart in general and not specific to flutter. Dart issues should be raised at https://github.com/dart-lang/sdk/issues/new/choose.
