### ISSUE TITLE
Any video player has severe image aliasing compared to the native player

### ISSUE THREAD

**Issue by hjc22** [flutter/flutter#44793]
Any video player has severe image aliasing compared to the native player

native:
![image](https://user-images.githubusercontent.com/17647420/68730365-7d99f180-0607-11ea-9217-88900599135b.png)

flutter:
![image](https://user-images.githubusercontent.com/17647420/68730396-92768500-0607-11ea-9a2a-303007e11dc2.png)

**Comment by iapicca** [comment]
Hi @hjc22 
could you please provide your updated  `flutter doctor -v` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by hjc22** [comment]
[✓] Flutter (Channel unknown, v1.11.0, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by hjc22** [comment]
> 很遗憾，如果没有其他信息，我们不确定如何解决此问题。因此，我们暂时不愿意关闭此错误。如果您有更多关于我们的信息，请不要犹豫，对该错误进行评论；我们将立即重新打开它！
> 感谢您的贡献。
> 
> 能否每个仍然存在此问题的人都请提交一个新的问题，并提供确切的描述，发生的情况以及日志和“ flutter doctor -v”的输出。
> 所有系统设置都可能略有不同，因此打开新问题和参考相关问题总是比较好的。

[✓] Flutter (Channel unknown, v1.11.0, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by hjc22** [comment]
I use platformview to play the video, and platformview uses the sufaceview form to render, the effect is the same as the original, and the video has no sawtooth. However, if you choose TextureView as the rendering mode, the video will be heavily jagged, just like the flutter rendering.

**Comment by iapicca** [comment]
Hi @hjc22 
are you experiencing the issue with the latest stable version of flutter?
thank you

**Comment by hjc22** [comment]
At present, I have tried the latest version. The video texture is still not clear, and the sawtooth is serious. IOS and Android are both

**Comment by kaisa695275735** [comment]
we find this issue too. this  seems like that the external_texture doesn't open the anti-aliasing.

**Comment by RblSb** [comment]
Related to #55696

**Comment by maheshmnj** [comment]
Hi @hjc22, I would recommend you and everyone who is facing this issue to try the latest plugin```video_player: ^2.0.8``` and if the issue still persists please provide the exact steps to reproduce the issue along with a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and ```flutter doctor -v``` to better investigate the issue. 
The [code sample provided here](https://github.com/flutter/flutter/issues/44793#issuecomment-613876971) doesn't seem to work and throws exception. 
> [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel imagealiastest)

Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
