### ISSUE TITLE
[web]: icons are rendered with vertical offset on Firefox

### ISSUE THREAD

**Issue by deckerst** [flutter/flutter#44803]
The `Icon` widget seems to be rendered with a small vertical offset at the top when displayed on Firefox.

For example:
```dart
            child: Stack(
              children: [
                Container(width: 24, height: 24, color: Colors.lightGreen),
                Icon(Icons.send, size: 24),
              ],
            ),
```

is correctly rendered on Chrome:
![Screenshot_20191113-174312_Chrome](https://user-images.githubusercontent.com/13898333/68747640-4bf04d00-063e-11ea-9ac3-72a88d976af8.jpg)

but is misaligned on Firefox (tried on Mac OS X 10.15 and Android):
![Screenshot_20191113-174330_Firefox](https://user-images.githubusercontent.com/13898333/68747627-45fa6c00-063e-11ea-96b2-1f35c498ab34.jpg)

flutter doctor -v:
```
[✓] Flutter (Channel dev, v1.10.16, on Mac OS X 10.15.1 19B88, locale en-KR)
    • Flutter version 1.10.16 at /Users/thibaultdeckers/projects/flutter
    • Framework revision 798e4272a2 (6 days ago), 2019-11-06 21:04:17 -0500
    • Engine revision 34a40cfbfd
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/thibaultdeckers/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Users/thibaultdeckers/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/thibaultdeckers/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (3 available)
    • iPhone 11  • 3373C512-23C6-42EC-8BA6-F79DC1ADE884 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
    • Chrome     • chrome                               • web-javascript • Google Chrome 78.0.3904.97
    • Web Server • web-server                           • web-javascript • Flutter Tools

• No issues found!
```

**Comment by ferhatb** [comment]
Material font has higher line height in firefox. Since you are restricting Container height, it is being cut off. Please use:
Container(width: 24, height:24, color: Colors.lightGreen, 
                  child: Icon(Icons.send, size: 24))

**Comment by deckerst** [comment]
@ferhatb thank you for the explanation, but I don't think this issue should be closed.

The workaround you mention yields on Firefox exactly the same result as the image I included before. Actually, the convoluted Stack + Container was just an example to easily see the issue, but the offset is also a problem in core Widgets like `IconButton`.

Code:
```dart
            IconButton(
              icon: Icon(Icons.send),
              onPressed: () {},
            )
```

on Chrome (mouse hovering shows the highlight):
<img width="113" alt="chrome" src="https://user-images.githubusercontent.com/13898333/69306903-6b096300-0c6c-11ea-83c6-65626383bd4c.png">

on Firefox (mouse hovering shows the highlight):
<img width="113" alt="ff" src="https://user-images.githubusercontent.com/13898333/69306912-7066ad80-0c6c-11ea-89b1-2a37e078c0d1.png">

The icon is not in the center of its own highlight.

**Comment by ferhatb** [comment]
Thanks for reopening the issue, i assumed it was due to small container height since increasing it aligns it correctly. IconButton should definitely work correctly across browsers. We'll take a look at it again and see why Firefox is reporting 28.5 pixel height instead of 24px on all other browsers.

**Comment by deckerst** [comment]
I cannot reopen the issue, as it wasn't closed by me.
