### ISSUE TITLE
Share_preferences web support using localStorage

### ISSUE THREAD

**Issue by sondresorbye0111** [flutter/flutter#44809]
Share_preferences web support using localStorage

**Comment by RohithKilaparthi** [comment]
Looking for the same. Please look into the issue

**Comment by undamatlamanikanta** [comment]
same issue

**Comment by jonataslaw** [comment]
SharedPreferences is a native mobile plugin.
If you want cross-platform storage, Hive would be a better solution as it is dart-written and has full web support.

**Comment by sondresorbye0111** [comment]
@jonataslaw that works 👍 thx

**Comment by iapicca** [comment]
Hi @sondresorbye0111 
can you please describe your proposal more extensively
thank you

**Comment by jonataslaw** [comment]
> Olá @ sondresorbye0111,
> você pode descrever sua proposta mais amplamente
> obrigado
> 
> @RohithKilaparthi @undamatlamanikanta,
> por favor considere que [shared_preferences](https://pub.dev/packages/shared_preferences) não se destina a trabalhar para a web
> 
> ```
> Wraps NSUserDefaults (on iOS) and SharedPreferences (on Android), 
> providing a persistent store for simple data.
> ```

Hi iapicca, I believe this topic can already be closed based on the author's answer above yours.
