### ISSUE TITLE
Text inside column overlapping in iOS

### ISSUE THREAD

**Issue by lintov7** [flutter/flutter#44800]
Below code is working fine in android but in iOS the text inside column are overlapping.

## Steps to Reproduce
```
Scaffold(body: Column( 
  mainAxisAlignment: MainAxisAlignment.center,
  children: <Widget>[
    Icon(Icons.star, size: 50),
    Container(
      width: 100,
      height: 100,
      color:Colors.red
    ),
    Icon(Icons.star, size: 50),
    Icon(Icons.star, size: 50),
    Text("Hello"),
    Text("Hello 123"),
    Text("Hello cat"),
  ],
));`
```

Does the problem occur on emulator/simulator as well as on physical devices?
Yes both in simulator and physical device

**Target Platform: iOS**
**Device: iPhone 11 pro max simulator running iOS 13.0,
 iPhone X running 13.1.3**

## Logs

<img width="645" alt="flutter-doctor" src="https://user-images.githubusercontent.com/16393683/68744431-a081d100-061a-11ea-9466-fc0e45187303.png">

![issue](https://user-images.githubusercontent.com/16393683/68744774-62d17800-061b-11ea-89ee-064419660f48.png)

**Comment by dommi10** [comment]
you can try to wrap your texts widgets inside a column like this : 
Column(
mainAxisAlignment: MainAxisAlignment.center,
children: [
Icon(Icons.star, size: 50),
Container(
width: 100,
height: 100,
color:Colors.red
),
Icon(Icons.star, size: 50),
Icon(Icons.star, size: 50),

Column(
mainAxisAlignment: MainAxisAlignment.center,
children: [
Text("Hello"),
Text("Hello 123"),
Text("Hello cat"),
],
),
],
);

May be it can fix that

**Comment by lintov7** [comment]
@dommi10 It is still not working.
I think the issue is in scaffold. When I replace it it working. But I am not getting the material theme.

**Comment by iapicca** [comment]
Hi @lintov7 
it might be a currupted flutter installation
can you please follow this [steps](https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted)?
let me know if it solves the issue
thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by Parker-Bergen** [comment]
I am having the same issue as @dommi10. The android version looks fine, but on ios the text is overlapping. This also happens when the text needs to wrap, and instead of going down to a line below, it will stay on the same level and overlap. I have temporarily used sized boxes to fix the spacing. I have tried the steps to clear the possible flutter corruption, but it did nothing to solve the issue. Please let me know any extra information that I can provide to help solve the issue.
