### ISSUE TITLE
CSON parser

### ISSUE THREAD

**Issue by ehhc** [flutter/flutter#44810]
Hi together,
i want to use CSON files in a flutter/dart project (due to interoperability with legacy code). 
Unfortunately, i cannot find a CSON parser for dart. There only seem to be some for JS and CoffeeScript. Does anybody knows about a CSON parser for Dart/flutter?

Writing a parser myself seems to be challenging considering that there don’t even seems to be a formal specification of the file format (I also asked about that in the corresponding github repo https://github.com/groupon/cson-parser/issues/26#issuecomment-553380623) :( 
Do you have any ideas what to do?

Thanks in advance

**Comment by jonahwilliams** [comment]
This doesn't have anything to do with the Flutter framework. Without a spec I suspect that no-one will be able to write a Dart parser for it, and that would be the responsibility of groupon/cson-parser to fix

**Comment by ehhc** [comment]
Thanks for your response. I feared to hear such an answer. I just hoped that somebody would come up with a library or something i just haven't found yet.
Thanks anyway @jonahwilliams
