### ISSUE TITLE
Migrate dart runner tests from Topaz to engine tree 

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#44822]
This includes `goodbye_dart_test`, `hello_world_dart_test` and there is also a dart test to ensure profiling can be done `dart_inspect/basic_benchmarks.tspec`, these will be useful to have in the engine tree.

**Comment by iskakaushik** [comment]
These should be run in both AOT and JIT mode.

**Comment by chaselatta** [comment]
tracking via fxbug.dev/61330
