### ISSUE TITLE
Have a simple driver test that runs on Fuchsia NUCs

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#44826]
This is currently blocked on https://github.com/flutter/flutter/issues/44374, https://github.com/flutter/flutter/issues/44819 and https://github.com/flutter/flutter/issues/42337

**Comment by iskakaushik** [comment]
I will keep this open until the driver tests are reenabled.

**Comment by godofredoc** [comment]
All the blocking bugs have been fixed and the test is now running continuously.
