### ISSUE TITLE
Prompted to approve ideviceid when running flutter doctor on Catalina

### ISSUE THREAD

**Issue by poitch** [flutter/flutter#44828]
## Steps to Reproduce

1. Download stable from flutter.dev
2. Unzip content to ~/development
3. Add ~/development/flutter/bin to PATH
4. Run flutter doctor
5. Get security prompt that ideviceid isn't an approve application.

@christopherfujino @tvolkert

**Comment by jmagman** [comment]
Duplicate of https://github.com/flutter/flutter/issues/42969.

**Comment by christopherfujino** [comment]
A temporary workaround to this would be to wipe out the cache, then call `flutter doctor` to repopulate it:

```
rm -rf ~/development/flutter/bin/cache
flutter doctor
```
