### ISSUE TITLE
[Image_picker] Constant fields should be private (Breaking change)

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#44823]
The constant in https://github.com/flutter/plugins/blob/master/packages/image_picker/lib/image_picker.dart#L11-L15 were meant to be private.

Although it is an easy fix, it is a breaking change nonetheless.

**Comment by pedromassangocode** [comment]
Hi @cyanglaz 
What are those constants? I've checked the source and I just found the `platform` static field, is he the one that must be private?

https://github.com/flutter/plugins/blob/3e547d9a808c35ea81b32bb225cfac1098607672/packages/image_picker/image_picker/lib/image_picker.dart#L29-L30

**Comment by pedromassangocode** [comment]
[triage-team]

Without additional information, I am therefore reluctantly going to close this bug for now. Please feel free to reopen if necessary.
