### ISSUE TITLE
[FlutterView setAccessibilityElements:]: message sent to deallocated instance 0x7fc899cca8c0

### ISSUE THREAD

**Issue by heng0808** [flutter/flutter#44824]
## Steps to Reproduce
I use FlutterBoost to write my ios app.Use the guide of `Add to exist App`.When stack of Navigatecontroller has many flutter VC And NatvieVC,and pop these VC,the app will crash,
this is Log:

`[FlutterView setAccessibilityElements:]: message sent to deallocated instance 0x7fc899cca8c0`

**Comment by iapicca** [comment]
Hi @SirHeng 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem.

If the issue you are experiencing is related to [flutter_boost ](https://pub.dev/packages/flutter_boost)
please consider opening an issue in the dedicated [github](https://github.com/alibaba/flutter_boost/issues)

Thank you

**Comment by gl-lei** [comment]
I have the same crash. My iOS Flutter Demo is very simple, this is my iOS code:

```objc
#import "ViewController.h"
#import "AppDelegate.h"
@import Flutter;

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
}

- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
    FlutterEngine *flutterEngine = [(AppDelegate *)[UIApplication sharedApplication].delegate flutterEngine];
    FlutterViewController *flutterVC = [[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil];
    [self presentViewController:flutterVC animated:YES completion:nil];
}

@end
```
And the dart code
```dart
 @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RaisedButton(
              onPressed: () => SystemNavigator.pop(),
              child: Text('Back To Native Page'),
            ),
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
```
Here the carsh log:
[crash.log](https://github.com/flutter/flutter/files/3855557/crash.log)

**Comment by iapicca** [comment]
Hi @gl-lei
thank you for the information you have provided

**Comment by YXYCareFree** [comment]
same crash

**Comment by darshankawar** [comment]
@heng0808 
Is this still a valid issue using latest Flutter version ?
If so, can you provide latest `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
