### ISSUE TITLE
Create a global language toggle on the website.

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#44846]
Create a global language toggle on the website.

Website guides include code samples for alternative languages: Obj-C/Swift and Java/Kotlin.

This ticket is to provide a global language selection when viewing the website such that all code samples the viewer sees are in the desired langugae.

**Comment by matthew-carroll** [comment]
CC @sfshaza2 @xster

**Comment by xster** [comment]
also cc @gaaclarke 

there was some usage of the <details> tag in https://github.com/flutter/website/blame/staging-add-to-app-do-not-delete-until-2020/src/docs/development/add-to-app/ios/add-flutter-screen.md#L191 but it doesn't seem to work when deployed to firebase

**Comment by xster** [comment]
We figured something out so closing this
