### ISSUE TITLE
Scrollbar should be draggable (and should be always displayed)

### ISSUE THREAD

**Issue by omarbelkhodja** [flutter/flutter#44840]
## Use case
In standard websites, when the content is bigger than the display area, scrollbars are displayed, and stay always displayed. There is already a feature request for having always displayed scrollbars (#28836). The subject of this feature request is that the scrollbar must be draggable using the mouse (this is not the case for the current scrollbar).

## Proposal
Make the scrollbars draggable using the mouse.

**Comment by ThinkDigitalSoftware** [comment]
And mobile. I would like to show the scrollbar until the widget is scrolled in order to indicate that it's scrollable

**Comment by jdeltoft** [comment]
> /cc @HansMuller @gspencergoog this seems to be a general desktop issue, not web-specific.

Yes, I think this is a general desktop/laptop issue.  I am working on making our flutter app replace our current website, and one of the engineers was concerned that sometimes people have laptops without knowing how to use their scrolling "gestures" on the trackpad.  And don't of course have a mouse with a scrollwheel all the time either.  So having an always on scroll bar for when kIsWeb is true would be WONDERFUL!

**Comment by tvolkert** [comment]
FYI @mikepyts @gladimdim @kunit1 (from dup'd bug https://github.com/flutter/flutter/issues/45897)

**Comment by tvolkert** [comment]
FYI, there is an `isAlwaysShown` parameter to `Scrollbar`.

**Comment by carloshwa** [comment]
> FYI, there is an `isAlwaysShown` parameter to `Scrollbar`.

I have this parameter set to `true` (and have a `ScrollController` set on `Scrollbar` and my `ListView`), but the scrollbar doesn't show until the user interacts with the list first. Once the user interacts with the list, however, the scrollbar shows and stays showing.

**Comment by jdeltoft** [comment]
https://stackoverflow.com/a/62160668/559525 helped me on this.

**Comment by okamototomoyuki1988** [comment]
I was able to implement a constant display of the Scroll bar. However, you cannot drag it with the mouse.
https://pub.dev/packages/flutter_web_scrollbar
I tried using this plugin, but it doesn't work properly.

**Comment by Piinks** [comment]
Hi @omarbelkhodja I am going to de-dupe the 2 issues you describe above.

For interactive scrollbars, follow https://github.com/flutter/flutter/issues/31753

For persistent visibility of scrollbars, follow https://github.com/flutter/flutter/issues/40107

Thank you for your contribution! :)
