### ISSUE TITLE
Prompt for sign in when making authenticated requests if not signed in

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#44854]
When clicking task square to view logs, if we didn't sign in yet, it gives error 'not sign in'.
It would be handy if it redirects to the sign-in page for such cases.

**Comment by keyonghan** [comment]
@CaseyHillers Could you please help take a look? Not sure if this has been implemented in v2.

**Comment by keyonghan** [comment]
cc @godofredoc

**Comment by CaseyHillers** [comment]
Since v1 just shows the error in the console, this was prioritized after launching v2.
