### ISSUE TITLE
New Android embedding does not support dart-flags extra

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#44855]
This is used to provide additional flags to the dart vm, subject to a whitelist in switches.cc

https://github.com/flutter/engine/blob/6f40beed77ef5d80c77a75913f506aa3c141b3e7/shell/platform/android/io/flutter/app/FlutterActivityDelegate.java#L324

**Comment by jonahwilliams** [comment]
cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@jonahwilliams are you using a version of the engine that includes this commit?

https://github.com/flutter/engine/blame/master/shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java#L179

**Comment by jonahwilliams** [comment]
Yes - for more context, the tool expects to be able to pass flags via an intent:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L590

**Comment by matthew-carroll** [comment]
Hm, I'm not sure why that's not working. Here is the execution order that should be taking place:

FlutterActivity instructs its delegate to initialize in `onCreate()`:

https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java#L418

The delegate instructs FlutterActivity to produce VM args:

https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java#L227

The FlutterActivity creates the arg list from its Intent:

https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java#L668
https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/engine/FlutterShellArgs.java#L66

The delegate creates a FlutterEngine, passing those args, which are sent into `ensureInitializationComplete()`:

https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java#L184

Is there anything about the particular place that you're trying to use these flags that would interfere with that execution order?

**Comment by jonahwilliams** [comment]
There is no parsing of `dart-flags` from the intent though

**Comment by matthew-carroll** [comment]
Ah, I see, there is explicitly an argument called "dart-flags" which may contain an arbitrary number of additional flags.  It looks like that was added only 5 months ago, which was long after I replicated that logic in the new embedding.

FYI @bkonyi if you happen make any adjustments to the arguments coming into Flutter on Android, it would be great if you could make the same adjustments to the new embedding, or you're welcome to file a ticket against me and I can take care of it.

I'll go ahead and get this behavior implemented in the new embedding.

**Comment by jonahwilliams** [comment]
Thanks very much @matthew-carroll !

**Comment by bkonyi** [comment]
> Ah, I see, there is explicitly an argument called "dart-flags" which may contain an arbitrary number of additional flags. It looks like that was added only 5 months ago, which was long after I replicated that logic in the new embedding.
> 
> FYI @bkonyi if you happen make any adjustments to the arguments coming into Flutter on Android, it would be great if you could make the same adjustments to the new embedding, or you're welcome to file a ticket against me and I can take care of it.
> 
> I'll go ahead and get this behavior implemented in the new embedding.

Sorry about that! I doubt that this code will be touched any time soon since the whitelist is in C++, but I'll be sure to let you know or make the equivalent changes myself.

**Comment by xster** [comment]
This is done now right?

**Comment by matthew-carroll** [comment]
Yep, done. Closing.
