### ISSUE TITLE
Odd formatter behavior when coupled with a specific IME from Huawei

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#44869]
See [b/144323703](http://b/144323703).

I can only input 3 digits. When trying to input the 4th digit, I observed that the formatEditUpdate was called 3 times. In the last formatEditUpdate call, the 4th character was deleted.

We also noticed that the run console displays these complains when trying to put the 4th character:
W/IInputConnectionWrapper(28600): getTextAfterCursor on inactive InputConnection and
W/IInputConnectionWrapper(28600): getTextBeforeCursor on inactive InputConnection

Checked multiple devices, the problem does not happen in Xiaomi, Nexus 5, and Nexus 6. The only device that failes currently is Huawei Mate 20 Pro.

After looking into this further, the problem seems to be the IME, not the phone. When we use GBoard instead of the bundled Huawei IME, the problem does not occur.

The problem always happens the first time typing a character would cause a text modification. For SG phone numbers, the 4th digit also introduces an extra space. For IN numbers, it is the fifth digit.

The text formatter with the issue seems to be ignoring a rule saying text can only be modified on a collapsed `composing` range (services/text_formatter.dart?l=13), so it is possible that this IME is sending a non-collapsed range, and our modification is interfering.

**Comment by cbracken** [comment]
My understanding is that flutter/engine#13951 is a partial fix to this issue.

**Comment by GaryQian** [comment]
I dont think this is fully fixed yet, still seeing some suboptimal behavior when typing. I am now able to type the full number, but some presses do not register and requires pressing multiple times to register.

**Comment by GaryQian** [comment]
Fixed by https://github.com/flutter/flutter/pull/49406
