### ISSUE TITLE
[Web] Hyperlink right click options

### ISSUE THREAD

**Issue by khari998** [flutter/flutter#44865]
Currently if we want to link to a route or a new url with an onTap, there is no way to right click and get access to the same controls chrome provides with other hyperlinks 

i.e. 
Open Link in New Tab
Open Link in New Window
Save Link As
... etc

Please make this possible

**Comment by MatanLjubas** [comment]
I'm just curious why this would be considered a new feature in a website? As per the @yjbanov 's P5 label

**Comment by khari998** [comment]
Sweet thanks for adding this. I will check it out
