### ISSUE TITLE
PageTransition is incorrect when first push a CupertinoPageRoute

### ISSUE THREAD

**Issue by Vadaski** [flutter/flutter#44864]
When you push a CupertinoPageRoute for the first time, the page transition animation will lack the shrink animation. This problem only occurs when using CupertinoPageRoute.
     
![2019-11-14 08 46 31](https://user-images.githubusercontent.com/23734225/68817408-931d2300-06bc-11ea-880a-61911c63bbde.gif)

Look carefully at the top text and you will find that the animation is a bit different.

You can reproduce this problem with this code.

``` dart
class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Title'),
        ),
        body: Center(
          child: FlatButton(
              onPressed: () {
                Navigator.of(context)
                    .push(CupertinoPageRoute(builder: (context) => Home()));
              },
              child: Text('push')),
        ));
  }
}

```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G87, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.0)
[!] Connected device
    ! No devices available
```

**Comment by Vadaski** [comment]
The Cupertino route animation is a combination of three animations. It seems that we lacked _secondaryPositionAnimation when we first navigated.

``` dart
  CupertinoPageTransition({
    Key key,
    @required Animation<double> primaryRouteAnimation,
    @required Animation<double> secondaryRouteAnimation,
    @required this.child,
    @required bool linearTransition,
  }) : assert(linearTransition != null),
       _primaryPositionAnimation =
           (linearTransition
             ? primaryRouteAnimation
             : CurvedAnimation(
                 parent: primaryRouteAnimation,
                 curve: Curves.linearToEaseOut,
                 reverseCurve: Curves.easeInToLinear,
               )
           ).drive(_kRightMiddleTween),
       _secondaryPositionAnimation =
           (linearTransition
             ? secondaryRouteAnimation
             : CurvedAnimation(
                 parent: secondaryRouteAnimation,
                 curve: Curves.linearToEaseOut,
                 reverseCurve: Curves.easeInToLinear,
               )
           ).drive(_kMiddleLeftTween),
       _primaryShadowAnimation =
           (linearTransition
             ? primaryRouteAnimation
             : CurvedAnimation(
                 parent: primaryRouteAnimation,
                 curve: Curves.linearToEaseOut,
               )
           ).drive(_kGradientShadowTween),
       super(key: key);
```

**Comment by Vadaski** [comment]
I followed the code that was executed during the routing process and found that when `TransitionRoute<T>` calls `_updateSecondaryAnimation`, we need to determine `nextRoute.canTransitionFrom(this)`，if `nextRoute.canTransitionFrom(this)` return false ,`final Animation<double> current = _secondaryAnimation.parent;` and `_secondaryAnimation.parent = newAnimation;`、` current.dispose();`will not be executed. This will cause the value of _secondaryPositionAnimation to not change when the first route is navigated.

``` dart
  void _updateSecondaryAnimation(Route<dynamic> nextRoute) {
    if (nextRoute is TransitionRoute<dynamic> && canTransitionTo(nextRoute) && nextRoute.canTransitionFrom(this)) {
      final Animation<double> current = _secondaryAnimation.parent;
      if (current != null) {
        if (current is TrainHoppingAnimation) {
          TrainHoppingAnimation newAnimation;
          newAnimation = TrainHoppingAnimation(
            current.currentTrain,
            nextRoute._animation,
            onSwitchedTrain: () {
              assert(_secondaryAnimation.parent == newAnimation);
              assert(newAnimation.currentTrain == nextRoute._animation);
              _secondaryAnimation.parent = newAnimation.currentTrain;
              newAnimation.dispose();
            },
          );
          _secondaryAnimation.parent = newAnimation;
          current.dispose();
        } else {
          _secondaryAnimation.parent = TrainHoppingAnimation(current, nextRoute._animation);
        }
      } else {
        _secondaryAnimation.parent = nextRoute._animation;
      }
    } else {
      _secondaryAnimation.parent = kAlwaysDismissedAnimation;
    }
  }

```

**Comment by Vadaski** [comment]
The real cause of this problem is that `CupertinoPageRoute` overrides the `canTransitionFrom` method.

``` dart
@override
  bool canTransitionFrom(TransitionRoute<dynamic> previousRoute) {
    return previousRoute is CupertinoPageRoute;
  }
```

If we use MaterialApp, the default route for the first page is MaterialPageRoute，this method will return false.If our second route is CupertinoPageRoute, then this method will cause _secondaryAnimation not to be created.

I think if the previousRoute is a MaterialPageRoute we should also return true.

``` dart
@override
  bool canTransitionFrom(TransitionRoute<dynamic> previousRoute) {
    return previousRoute is MaterialPageRoute || previousRoute is CupertinoPageRoute;
  }
```

**Comment by AlexVincent525** [comment]
The same behavior will be triggered by `push` too. Then you are trying to `push` a `CupertinoPageRoute`, the secondary animation won't start, but `pushNamed` will do.

**Comment by luckysmg** [comment]
I found that if you use CupertinoApp instead of MetarialApp,and push with a CupertinoPageRoute,the anim is correct

**Comment by Vadaski** [comment]
Yes,because of CupertinoApp use CupertinoPageRoute as default route, canTransitionFrom will return true. So we can get secondaryAnimation correctly.

**Comment by HansMuller** [comment]
CC @LongCatIsLooong

**Comment by Vadaski** [comment]
Hi @LongCatIsLooong ,could you confirm it? If possible, I want to send a pull request ;)

**Comment by LongCatIsLooong** [comment]
@Vadaski thank you for looking into this! Pull requests are always welcome. But you might want to find a different approach than https://github.com/flutter/flutter/issues/44864#issuecomment-553684161, as in theory the Cupertino library shouldn't know about the Material library (i.e. we shouldn't import `MaterialPageRoute` in `flutter/lib/src/cupertino/route.dart`).

**Comment by Vadaski** [comment]
No problem! I just checked the `canTransitionFrom` method. Only one usages in all places.
![Useages of canTransitionFrom in All Places](https://user-images.githubusercontent.com/23734225/69507695-5bd92c80-0f6e-11ea-9531-5c77fc4a7178.png)
I didn't find out why `CupertinoPageRoute` needs to override this method. If we push the `CupertinoPageRoute` after pushing the `MaterialPageRoute` or other routes, it will cause the method to return false. But we should not return false, the animation of `CupertinoPageRoute` should be consistent.
I have verified that this problem can also be solved if we remove the `canTransitionFrom` method overridden in `CupertinoPageRoute`.And we don't need to import the `MaterialPageRoute` as well.  what do you think ?
@LongCatIsLooong

**Comment by LongCatIsLooong** [comment]
@Vadaski yeah that sounds reasonable and worked well when I tried it too!

**Comment by AlexVincent525** [comment]
> I have verified that this problem can also be solved if we remove the `canTransitionFrom` method overridden in `CupertinoPageRoute`.And we don't need to import the `MaterialPageRoute` as well.
@Vadaski So as the `canTransitionFrom` method has useless override, should `MaterialPageRoute` does the same thing? Using `MaterialPageRoute` when pushing route will still check if the previous route is `MaterialPageRoute` or `CupertinoPageRoute`, and it can be removed too.
@LongCatIsLooong I have another question about the `MaterialPageRoute`, when using it on the iOS platform, it will use default page transition which is `CupertinoPageTransition`. Does it make sense with cupertino transition in material page route? Or it's by design?

**Comment by LongCatIsLooong** [comment]
@AlexVincent525 I consulted @xster, the answer is yes it's by design. You can override the transition in your `Theme` if you wish to.

**Comment by AlexVincent525** [comment]
@LongCatIsLooong Back to the issue, do you think that `MaterialPageRoute` should remove `canTransitionFrom` override too? To make them more consistent, it will build transition when previous page route is a `PageRoute`.
![image](https://user-images.githubusercontent.com/15884415/69597555-513b9780-1041-11ea-82d4-6e92093fd481.png)

**Comment by Vadaski** [comment]
[](https://github.com/flutter/flutter/issues/44864#issuecomment-558420493)
Agree, I checked `canTransitionTo`’s Comment. 
![canTransitionTo](https://user-images.githubusercontent.com/23734225/69597128-db82fc00-103f-11ea-8440-4a69a260902f.png)
It only change secondaryAnimation to control transition animation.
Material style transition use `FadeUpwardsPageTransitionsBuilder(),`,Cupertino style transition use `CupertinoPageTransitionsBuilder()`.
``` dart
class PageTransitionsTheme extends Diagnosticable {
...
  static const Map<TargetPlatform, PageTransitionsBuilder> _defaultBuilders = <TargetPlatform, PageTransitionsBuilder>{
    TargetPlatform.android: FadeUpwardsPageTransitionsBuilder(),
    TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
  };
...
```
We both agree that the `canTransitionFrom` method overridden in `CupertinoPageRoute` should be removed. So,We only need to check `FadeUpwardsPageTransitionsBuilder`.
``` dart
class FadeUpwardsPageTransitionsBuilder extends PageTransitionsBuilder {
  /// Construct a [FadeUpwardsPageTransitionsBuilder].
  const FadeUpwardsPageTransitionsBuilder();

  @override
  Widget buildTransitions<T>(
    PageRoute<T> route,
    BuildContext context,
    Animation<double> animation,
    Animation<double> secondaryAnimation,
    Widget child,
  ) {
    return _FadeUpwardsPageTransition(routeAnimation: animation, child: child);
  }
}
```
Looks like `FadeUpwardsPageTransitionsBuilder` doesn't using `secondaryAnimation`. So `canTransitionFrom` has no effect on `MaterialPageRoute`.
But I find another transition builder using `secondaryAnimation`.
``` dart
// This transition is intended to match the default for Android P.
class _OpenUpwardsPageTransition extends StatelessWidget {
  const _OpenUpwardsPageTransition({
    Key key,
    this.animation,
    this.secondaryAnimation,
    this.child,
  }) : super(key: key);
```
This pageTransition is used to adapt Android P, but this class is not used anywhere. Maybe it will be added to MaterialPageRoute in a future version. So, I don't recommend removing `canTransitionFrom` from MaterialPageRoute.
@AlexVincent525

**Comment by AlexVincent525** [comment]
@Vadaski Since you mentioned the transition to adapt Android P, there's a new transition for Android 10 https://github.com/flutter/flutter/commit/547b86a91fbd4192b4719ce42c125bfa6814d23c . If there're any plans to link those transition to adapt different type of android platform, I think it might be done with this issue.

**Comment by Vadaski** [comment]
> @LongCatIsLooong Back to the issue, do you think that `MaterialPageRoute` should remove `canTransitionFrom` override too? To make them more consistent, it will build transition when previous page route is a `PageRoute`.
> ![image](https://user-images.githubusercontent.com/15884415/69597555-513b9780-1041-11ea-82d4-6e92093fd481.png)

Is the real meaning of overriding `canTransitionFrom` to ensure that the incoming Route is a `PageRoute`？We should figure this out. @AlexVincent525 @LongCatIsLooong

**Comment by Vadaski** [comment]
``` dart
void _updateSecondaryAnimation(Route<dynamic> nextRoute) {
    if (nextRoute is TransitionRoute<dynamic> && canTransitionTo(nextRoute) && nextRoute.canTransitionFrom(this)) {
```
We have judged in _updateSecondaryAnimation. So We don't need to repeat judgment. @AlexVicent525

**Comment by LongCatIsLooong** [comment]
> @LongCatIsLooong Back to the issue, do you think that MaterialPageRoute should remove canTransitionFrom override too? To make them more consistent, it will build transition when previous page route is a PageRoute.

Harmless as it seems, the change could break someone's existing code, also I'm a bit reluctant to change something that's working without consulting the author, /cc @xster.

**Comment by AlexVincent525** [comment]
And the PR is here #45647 , thx for @Vadaski first find it out and investigate it. ❤️

**Comment by Vadaski** [comment]
I found it's little bit tricky to write widget test in this case. Because of flutter_test uses a fake clock, I can't get the intermediate state when push a route. I also can't provide a controller that drives the animation, any suggestions? @LongCatIsLooong

**Comment by Vadaski** [comment]
There is another thing that I am more confused about.  pages_test.dart in cupertino doesn't import material library. This means I cannot use MaterialApp, and for this case I cannot reproduce the necessary conditions for the issue. This issue occurs only when using MaterialApp or if the previous route is not a cupertino page route.

![pages_test.dart](https://user-images.githubusercontent.com/23734225/69726582-d1562000-115b-11ea-8370-f6b6ed13c5db.png)

@LongCatIsLooong

**Comment by LongCatIsLooong** [comment]
You could use `tester.pump` to advance the clock like so: 
https://github.com/flutter/flutter/blob/e4b809b7c8d90f0b4419290bba163ed0dfcb9475/packages/flutter/test/material/page_test.dart#L70-L147

line 91 triggers the animation and line 92 advances the clock.

**Comment by AlexVincent525** [comment]
@LongCatIsLooong Me and @Vadaski discussed it before, to ensure this issue was resolved, push with CupertinoPageRoute is required, and the CupertinoPageRoute is what we are actually going to test. Use target platform doesn't push through the CupertinoPageRoute, but the CupertinoPageTransition.

**Comment by LongCatIsLooong** [comment]
@AlexVincent525 will something like this work?
```dart
  testWidgets(
    'On iOS, a MaterialPageRoute should slide out with CupertinoPageTransition'
    'when a compatible PageRoute is pushed on top of it',
    (WidgetTester tester) async {
      // Regression test for https://github.com/flutter/flutter/issues/44864.
      await tester.pumpWidget(
        MaterialApp(
          theme: ThemeData(platform: TargetPlatform.iOS),
          home: Scaffold(
            appBar: AppBar(title: const Text('Title')),
          ),
        ),
      );

      final Offset titleInitialTopLeft = tester.getTopLeft(find.text('Title'));

      tester.state<NavigatorState>(find.byType(Navigator)).push<void>(
        CupertinoPageRoute<void>(builder: (BuildContext context) => const Placeholder()),
      );

      await tester.pump();
      await tester.pump(const Duration(milliseconds: 150));

      final Offset titleTransientTopLeft = tester.getTopLeft(find.text('Title'));

      // Title of the first route slides to the left.
      expect(titleInitialTopLeft.dy, equals(titleTransientTopLeft.dy));
      expect(titleInitialTopLeft.dx, greaterThan(titleTransientTopLeft.dx));
  });
```

**Comment by AlexVincent525** [comment]
@LongCatIsLooong Yes that definitely work. I wrote some tests few hours ago that seems simillar to your test.
```
testWidgets(
      'test CupertinoPageRoute canTransitionFrom with TargetPlatform.android',
      (WidgetTester tester) async {
    await tester.pumpWidget(
      MaterialApp(
        theme: ThemeData(platform: TargetPlatform.android),
        home: const Material(child: Text('Page 1')),
      ),
    );

    final Offset widget1TopLeft = tester.getTopLeft(find.text('Page 1'));

    tester.state<NavigatorState>(find.byType(Navigator)).push(
      CupertinoPageRoute(
        builder: (BuildContext context) {
          return const Material(
            child: Text('Page 2'),
          );
        },
      ),
    );
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 1));

    Offset widget2TopLeft = tester.getTopLeft(find.text('Page 2'));

    // iOS transition is horizontal only.
    expect(widget1TopLeft.dy, equals(widget2TopLeft.dy));
    // Page 1 is above page 2 mid-transition.
    expect(widget1TopLeft.dx, lessThan(widget2TopLeft.dx));

    await tester.pump(const Duration(milliseconds: 300 + 1));

    tester.state<NavigatorState>(find.byType(Navigator)).pop();
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 1));

    widget2TopLeft = tester.getTopLeft(find.text('Page 2'));

    expect(widget1TopLeft.dx, lessThan(widget2TopLeft.dx));
  });
```
Pump twice with the start and the end of transition duration can confirm that title always on the left.

But what makes us confused is whether we should import cupertino in material's tests or import material in cupertino's tests, because both `MaterialApp` and `CupertinoPageRoute` are required.

**Comment by LongCatIsLooong** [comment]
Ah gotcha. The test should preferably be a Material test because Material as a design language [knows about Cupertino](https://material.io/design/platform-guidance/cross-platform-adaptation.html#cross-platform-guidelines),  and it's pretty common to import things from Cupertino in a Material source file.

**Comment by Vadaski** [comment]
It seems all my problems have been solved, thanks @LongCatIsLooong and AlexVincent525 !

**Comment by gabdsg** [comment]
Is this merged on channel stable?

**Comment by AlexVincent525** [comment]
> Is this merged on channel stable?

It might be included in next stable, but yes it has been merged, on master.

**Comment by benjaminhorner** [comment]
@AlexVincent525 are you sure? Because I still see this behavior on Android with the latest update on `master`…
