### ISSUE TITLE
 Xcode11.2.1 COCOAPODS: 1.8.4 archive Cannot load third party plugins

### ISSUE THREAD

**Issue by lovachen** [flutter/flutter#44871]
Flutter run is no problem, can run
But when the archive package is compiled, it is wrong, the plugin cannot be loaded.
'xxxxx/xxxxxPlugin.h' file not found

```
flutter run 是没有问题的，能运行
但是archive打包编译的时候就错误了，无法加载插件
'xxxxx/xxxxxPlugin.h' file not found
```

**Comment by YellowDoing** [comment]
archive打包前 先命令行执行flutter build ios --release ，然后再打包

**Comment by lovachen** [comment]
一样的，试过了，后来手动在xcode里面添加pods文才可以编译打包。

**Comment by iapicca** [comment]
Hi @lovachen 
could you please provide your updated  `flutter doctor -v`
and your `flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by jmagman** [comment]
What are the steps to reproduce compiling with archive?  Are you running flutter run?  From Xcode? If so, are you running Runner.xcworkspace?
复制归档文件有哪些步骤？ 你在扑扑吗？ 来自Xcode？ 如果是这样，您是否正在运行Runner.xcworkspace？

**Comment by anhmax600** [comment]
i have a same problem in here , i use video_player , everything work good but i can not archive when i build ios release . 
In Xcode at GeneratedPluginRegistrant.m file i have  error 'video_player/VideoPlayerPlugin.h' file not found.
do you have a solution for this @iapicca ?

**Comment by YellowDoing** [comment]
try pod install again

**Comment by anhmax600** [comment]
> try pod install again

yes @YellowDoing  I try many time but it's still not work still have error plugin file not found

**Comment by jmagman** [comment]
@anhmax600 Can you confirm you have Runner.xcworkspace open and not Runner.xcodeproj?

**Comment by anhmax600** [comment]
@YellowDoing @jmagman  yes my bad , I open xcode by visual studio , it's always open xcodeproj . Thanks u a lot , you save my day

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
