### ISSUE TITLE
DropdownButton raise "The getter 'itemHeights' was called on null" when locale/language changed.

### ISSUE THREAD

**Issue by narumishi** [flutter/flutter#44877]
I'm setting MaterialApp's locale property to switch the app's language. DropdownButton will raise exception when change languange inside the `onChanged` callback of DropdownButton. But it works well if change language outside DropDownButton, like inside callback of GestureDetector, RaisedButton, Switch... 

The same character(also widget size) is larger in Chinese/Japanese locale then in English.
## Exception
`_dropdownRoute.itemHeights[index] = size.height` raised "**The getter 'itemHeights' was called on null**" inside [`_DropdownButtonState._handleTap()`](https://github.com/flutter/flutter/blob/09b31a4d0d3a37e89472d773d48f7517e4c6577d/packages/flutter/lib/src/material/dropdown.dart#L1146)
```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during performLayout():
The getter 'itemHeights' was called on null.
Receiver: null
Tried calling: itemHeights

The relevant error-causing widget was: 
  MaterialApp file:///D:/Projects/AndroidStudioProjects/chaldea/lib/main.dart:20:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _DropdownButtonState._handleTap.<anonymous closure> (package:flutter/src/material/dropdown.dart:1146:26)
#2      _RenderMenuItem.performLayout (package:flutter/src/material/dropdown.dart:617:5)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#4      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
...
```
the full exception output on [gist](https://gist.github.com/narumishi/000d69196eba5d2d13e15d9b968dfe47#file-log_exception-log)

It seems _MenuItem.onLayout is called after _dropdownRoute is popped, but it should not be called? Just simply wrap the statement with non-null check, it seems everything ok.
```dart
if (_dropdownRoute != null) {
  _dropdownRoute.itemHeights[index] = size.height;
}
```

## Steps to Reproduce
1. `main.dart` full code on [gist](https://gist.github.com/narumishi/000d69196eba5d2d13e15d9b968dfe47#file-main-dart)
```dart
class _MyAppState extends State<MyApp> {
  String _languageCode = kLanguages.keys.first;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      locale: Locale(_languageCode),
      //...
      body: Builder(
        builder:(context)=>Scaffold(
          body: 
              // inside body
              DropdownButton(
                value: _languageCode,
                items: kLanguages.keys
                    .map((code) => DropdownMenuItem(
                        value: code, child: Text(kLanguages[code])))
                    .toList(),
                onChanged: (code) => setState(() => _languageCode = code),
              ),
        ))
    );
  }
}
```
1.  `i18n.dart` is generated by Android Studio plugin [**Flutter i18n**(v1.14-192)](https://plugins.jetbrains.com/plugin/10128-flutter-i18n), you could check the code on gist [i18n.dart](https://gist.github.com/narumishi/000d69196eba5d2d13e15d9b968dfe47#file-i18n-dart)

## flutter doctor -v
<details><summary>Flutter version 1.13.3-pre.85</summary>
<pre><code>[√] Flutter (Channel master, v1.13.3-pre.85, on Microsoft Windows [Version 10.0.18363.535], locale zh-CN)
    • Flutter version 1.13.3-pre.85 at D:\Projects\sdk\flutter
    • Framework revision bd25f70c66 (7 days ago), 2019-12-19 09:45:02 -0800
    • Engine revision 0f90e6546b
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Projects\sdk\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Users\narumi\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\192.6071332\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Users\narumi\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\192.6071332
    • Flutter plugin version 42.2.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\narumi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
</code></pre>
</details>

**Comment by iapicca** [comment]
Hi @narumishi 
are you referring to [this ](https://pub.dev/packages/i18n)3rd party plugin?
thank you

**Comment by narumishi** [comment]
@iapicca it's a Jetbrain plugin http://plugins.jetbrains.com/plugin/10128-flutter-i18n.
The dart file `i18n.dart` is generated by the plugin when arb files changed. 
Only `i18n.dart` is included in project and only some flutter basic packages are refferred, no third-party dart packages. You can check the code on gist (https://gist.github.com/narumishi/000d69196eba5d2d13e15d9b968dfe47).

```dart
// i18n.dart
// only these three basic package are reffered.
import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
// more codes...
```

**Comment by iapicca** [comment]
thank you for your answer @narumishi

**Comment by creativecreatorormaybenot** [comment]
I have this same issue with Hindi as well because the characters used in that language are larger than English ones. @narumishi Could you potentially remove a bit of the stuff from your original comment, like make it more concise? For me at least it is very hard to read through that much text - I think the issue is more likely to be tackled when the problem description is more concise.

**Comment by co-in** [comment]
I have this same issue. Raised error on https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/dropdown.dart#L1146
_dropdownRoute is null

My trasample https://github.com/co-in/flutter_rx

**Comment by altafkhan8719** [comment]
I am Also getting same error on language change,  i am not using any third party plugin.

NoSuchMethodError: The getter 'itemHeights' was called on null.
I/flutter ( 3896): Receiver: null
I/flutter ( 3896): Tried calling: itemHeights
I/flutter ( 3896): [2020-01-13 18:25:44.770883 | ConsoleHandler | INFO]
I/flutter ( 3896): [2020-01-13 18:25:44.770999 | ConsoleHandler | INFO] ------- STACK TRACE -------
I/flutter ( 3896): [2020-01-13 18:25:44.776267 | ConsoleHandler | INFO] #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter ( 3896): [2020-01-13 18:25:44.776677 | ConsoleHandler | INFO] #1      _DropdownButtonState._handleTap.<anonymous closure> (package:flutter/src/material/dropdown.dart:1149:26)
I/flutter ( 3896): [2020-01-13 18:25:44.776848 | ConsoleHandler | INFO] #2      _RenderMenuItem.performLayout (package:flutter/src/material/dropdown.dart:619:5)
I/flutter ( 3896): [2020-01-13 18:25:44.776981 | ConsoleHandler | INFO] #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.777127 | ConsoleHandler | INFO] #4      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter ( 3896): [2020-01-13 18:25:44.777261 | ConsoleHandler | INFO] #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.777477 | ConsoleHandler | INFO] #6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.777650 | ConsoleHandler | INFO] #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.777778 | ConsoleHandler | INFO] #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.777905 | ConsoleHandler | INFO] #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.778034 | ConsoleHandler | INFO] #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.778178 | ConsoleHandler | INFO] #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.778415 | ConsoleHandler | INFO] #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.778550 | ConsoleHandler | INFO] #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.778723 | ConsoleHandler | INFO] #14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.778862 | ConsoleHandler | INFO] #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.778984 | ConsoleHandler | INFO] #16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.779168 | ConsoleHandler | INFO] #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.779291 | ConsoleHandler | INFO] #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.779411 | ConsoleHandler | INFO] #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.779531 | ConsoleHandler | INFO] #20     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:205:17)
I/flutter ( 3896): [2020-01-13 18:25:44.779651 | ConsoleHandler | INFO] #21     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:238:19)
I/flutter ( 3896): [2020-01-13 18:25:44.779819 | ConsoleHandler | INFO] #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.780005 | ConsoleHandler | INFO] #23     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:134:11)
I/flutter ( 3896): [2020-01-13 18:25:44.780131 | ConsoleHandler | INFO] #24     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:373:11)
I/flutter ( 3896): [2020-01-13 18:25:44.780252 | ConsoleHandler | INFO] #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.780371 | ConsoleHandler | INFO] #26     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:410:13)
I/flutter ( 3896): [2020-01-13 18:25:44.780491 | ConsoleHandler | INFO] #27     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1700:12)
I/flutter ( 3896): [2020-01-13 18:25:44.780610 | ConsoleHandler | INFO] #28     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1663:20)
I/flutter ( 3896): [2020-01-13 18:25:44.780732 | ConsoleHandler | INFO] #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.780890 | ConsoleHandler | INFO] #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.781015 | ConsoleHandler | INFO] #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.781134 | ConsoleHandler | INFO] #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.781255 | ConsoleHandler | INFO] #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.781426 | ConsoleHandler | INFO] #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.781547 | ConsoleHandler | INFO] #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.781667 | ConsoleHandler | INFO] #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.781790 | ConsoleHandler | INFO] #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.782133 | ConsoleHandler | INFO] #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.782360 | ConsoleHandler | INFO] #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.782577 | ConsoleHandler | INFO] #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.782704 | ConsoleHandler | INFO] #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.782826 | ConsoleHandler | INFO] #42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.782945 | ConsoleHandler | INFO] #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.783186 | ConsoleHandler | INFO] #44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.783315 | ConsoleHandler | INFO] #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.783495 | ConsoleHandler | INFO] #46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.783685 | ConsoleHandler | INFO] #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.783858 | ConsoleHandler | INFO] #48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.783999 | ConsoleHandler | INFO] #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.784167 | ConsoleHandler | INFO] #50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.784405 | ConsoleHandler | INFO] #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.784556 | ConsoleHandler | INFO] #52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.784698 | ConsoleHandler | INFO] #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.784854 | ConsoleHandler | INFO] #54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.785004 | ConsoleHandler | INFO] #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.785188 | ConsoleHandler | INFO] #56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 3896): [2020-01-13 18:25:44.785499 | ConsoleHandler | INFO] #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 3896): [2020-01-13 18:25:44.785638 | ConsoleHandler | INFO] #58     RenderCustomSingleChildLayoutBox.performLayout (package:flutter/src/rendering/shifted_box.dart:1123:13)
I/flutter ( 3896): [2020-01-13 18:25:44.785767 | ConsoleHandler | INFO] #59     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
I/flutter ( 3896): [2020-01-13 18:25:44.785901 | ConsoleHandler | INFO] #60     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
I/flutter ( 3896): [2020-01-13 18:25:44.786034 | ConsoleHandler | INFO] #61     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
I/flutter ( 3896): [2020-01-13 18:25:44.786171 | ConsoleHandler | INFO] #62     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
I/flutter ( 3896): [2020-01-13 18:25:44.786490 | ConsoleHandler | INFO] #63     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter ( 3896): [2020-01-13 18:25:44.786637 | ConsoleHandler | INFO] #64     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter ( 3896): [2020-01-13 18:25:44.786762 | ConsoleHandler | INFO] #65     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter ( 3896): [2020-01-13 18:25:44.786891 | ConsoleHandler | INFO] #66     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
I/flutter ( 3896): [2020-01-13 18:25:44.787017 | ConsoleHandler | INFO] #67     _rootRun (dart:async/zone.dart:1126:13)
I/flutter ( 3896): [2020-01-13 18:25:44.787211 | ConsoleHandler | INFO] #68     _CustomZone.run (dart:async/zone.dart:1023:19)
I/flutter ( 3896): [2020-01-13 18:25:44.787334 | ConsoleHandler | INFO] #69     _CustomZone.runGuarded (dart:async/zone.dart:925:7)     
I/flutter ( 3896): [2020-01-13 18:25:44.787503 | ConsoleHandler | INFO] #70     _invoke (dart:ui/hooks.dart:259:10)
I/flutter ( 3896): [2020-01-13 18:25:44.787630 | ConsoleHandler | INFO] #71     _drawFrame (dart:ui/hooks.dart:217:3)

**Comment by creativecreatorormaybenot** [comment]
@altafkhan8719 Could you please post that stack trace to a [Gist](https://gist.github.com/) and edit your comment to link to it instead? It makes this issue hard to read through 😕

**Comment by udayvharihar** [comment]
Even I'm facing this issue, just scroll on DropDownButton list and click on outside the list.

Stack Trace :
` .   I/flutter ( 7263): Setup localization lazily!
I/flutter ( 7263): Current state: NavigatorState#ed116(tickers: tracking 5 tickers)
I/flutter ( 7263): Current state: NavigatorState#ed116(tickers: tracking 5 tickers)
I/flutter ( 7263): REPORT :::true
I/flutter ( 7263): [2020-01-23 11:11:28.889218 |  | INFO] Displaying error: NoSuchMethodError: The getter 'itemHeights' was called on null.
I/flutter ( 7263): Receiver: null
I/flutter ( 7263): Tried calling: itemHeights
I/flutter ( 7263): Stack Trace:
I/flutter ( 7263): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter ( 7263): #1      _DropdownButtonState._handleTap.<anonymous closure> (package:flutter/src/material/dropdown.dart:1149:26)
I/flutter ( 7263): #2      _RenderMenuItem.performLayout (package:flutter/src/material/dropdown.dart:619:5)
I/flutter ( 7263): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 7263): #4      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter ( 7263): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 7263): #6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 7263): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter ( 7263): #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 7263): #9      RenderObject.layout (package:flutter/src/render
I/flutter ( 7263): 2020-01-23 11:11:28.889218 .INFO: Displaying error: NoSuchMethodError: The getter 'itemHeights' was called on null.
I/flutter ( 7263): Receiver: null
I/flutter ( 7263): Tried calling: itemHeights`

**Comment by dpedrinha** [comment]
Same problem here. And I'm also facing this problem #49599 since flutter update.

**Comment by iapicca** [comment]
Hi @narumishi 
the [intelliJ plugin ](https://plugins.jetbrains.com/plugin/10128-flutter-i18n) appear to be deprecated

> THIS IS NOW DEPRECATED. PLEASE GIVE A TRY TO:
> 
> https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl
> https://plugins.jetbrains.com/plugin/13666-flutter-intl
> And CLI / Dart lib tool: https://pub.dev/packages/intl_utils

let me know if you are experiencing issues w/ the suggested plugins
thank you

**Comment by miguelpruivo** [comment]
Hi, I'm also experiencing the same issue when setting the app language dynamically (modifying a root stream that sets the `Locale`).

The `DropdownButton` seems to throw this error despite not showing any issue on the layout itself. I'm not using any IntelliJ plugin, just the i10l accordingly to Flutter docs on VS Code.

**Comment by kalismeras61** [comment]
Same issue when language dynamically change.

**Comment by shihaohong** [comment]
I managed to create a smaller test case [in this gist](https://gist.github.com/shihaohong/14e8990fc6e8b52fcb7f8ff3bda8ecb7), but basically what's happening is that while the previous _DropdownRoute is animating away (it has already popped), a performLayout had been called on the route that is disappearing. 

This was happening when the locale is being updated because a change in locale triggers a markNeedsLayout() call on the leaving dropdown menu. A similar thing can happen by wrapping the Navigator in a MediaQuery and changing the textScaleFactor, triggering markNeedsLayout() in the dropdown menu.

**Comment by shihaohong** [comment]
The fix is complete, it’ll be merged into ‘master’ soon

**Comment by mustafa96m** [comment]
I'm facing the same issue with _DropdownButton_ and _Localization_ although I found a very-dirty/hacky way to overcome the issue momentarily.. as I updated the framework to Flutter 1.12.13+hotfix.8 

```dart
 Future.delayed(const Duration(milliseconds: 300), (){
        /// Change your locale..
 });
```

**Comment by iassal** [comment]
@shihaohong, any chance we can get a hotfix for this? We added a couple of dropdowns in our application and we are seeing some occurrences in logs.

**Comment by shihaohong** [comment]
Please see https://github.com/flutter/flutter/wiki/Release-process#applying-emergency-fixes for our release process -- We generally do not apply hotfixes unless they are a security issue or there is some issue that completely breaks Flutter
