### ISSUE TITLE
error when trying to run on an iOS device

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#4489]
The output from `flutter run`:

```
Running lib/main.dart on Devon's iPad...
Unzipping Xcode project to local directory...
Xcode project created in /Users/devoncarew/projects/flutter/sample_app/ios/.
2016-06-09 08:55:13.157 ios-deploy[25132:1547338] [ !! ] Error 0xe8000087: ·¸Œuˇˇ AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
Could not install ios/.generated/build/Release-iphoneos/Runner.app on 2f9f0d179145b7e0c329d08a8153472f5e643045.
Error running application on Devon's iPad.
```

And a screenshot from XCode:

<img width="413" alt="screen shot 2016-06-09 at 8 57 28 am" src="https://cloud.githubusercontent.com/assets/1269969/15936529/38ef39ea-2e20-11e6-9582-d7c91bc55030.png">
os

**Comment by devoncarew** [comment]
This is for a newly created project using the source on master (Framework revision 4e3e40a174 (10 minutes ago), engine revision 034ae44419).

**Comment by abarth** [comment]
Looks like you're trying to build for armv7.  We currently only support arm64.  What version of the iPad are you using?

**Comment by devoncarew** [comment]
Ah, an older one. It's not with me right now, but armv7 makes sense. I'll close this and open one about failing with a clearer error message.
