### ISSUE TITLE
flutter webview_flutter  Stack child widget touch Event Pierce through -- iOS

### ISSUE THREAD

**Issue by dkluhack** [flutter/flutter#44897]
```dart
Stack(
              children: <Widget>[
                WebView(
                  javascriptChannels: <JavascriptChannel>[
                    Js_exc_Flutter_getCoordinate(),
                    Js_exc_Flutter_getFeatureUrls(),
                    Js_exc_Flutter_getArea(),
                    Js_exc_Flutter_getPerimeter(),
                    Js_exc_Flutter_getDrawBox()
                  ].toSet(),
                  initialUrl: Api.mapSever,
                  javascriptMode: JavascriptMode.unrestricted,
                  onWebViewCreated: (WebViewController controller) {
                    this.controller = controller;
                  },

                  onPageFinished: (String url) {
                    Flutter_exc_Js_switchBaseMap(1);
                    getCurrentLocal();
                  },
                ),
  ....
```

**Comment by dkluhack** [comment]
iOS

**Comment by janmoppel** [comment]
Hello @dkluhack !

Thank you for posting an issue.
Can you please also provide additional information such as an output of the `flutter doctor -v` command and more information on the issue (what is wrong exactly)?

Thank you.

**Comment by dkluhack** [comment]
flutter Stack child:InkWell(.. ,ontap(){ // meanwhile})，webview_flutter JavascriptChannel(.., onMessageReceived: (JavascriptMessage message) { //meanwhile})

**Comment by dkluhack** [comment]
> Hello @dkluhack !
> 
> Thank you for posting an issue.
> Can you please also provide additional information such as an output of the `flutter doctor -v` command and more information on the issue (what is wrong exactly)?
> 
> Thank you.

flutter Stack child: webview_flutter JavascriptChannel(.., onMessageReceived: (JavascriptMessage message) { //meanwhile}), InkWell(.. ,ontap(){ // meanwhile})

**Comment by TahaTesser** [comment]
Hi @dkluhack 
Are you still experiencing this issue?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @dkluhack 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
