### ISSUE TITLE
Exception Caught By widgets library

### ISSUE THREAD

**Issue by damanjeetkaurchadha** [flutter/flutter#44894]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
════════ Exception Caught By widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building StatefulBuilder(dirty, state: _StatefulBuilderState#4abab):
'package:flutter/src/material/dropdown.dart': Failed assertion: line 608 pos 15: 'items == null || items.isEmpty || value == null || items.where((DropdownMenuItem<T> item) => item.value == value).length == 1': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      new DropdownButton (package:flutter/src/material/dropdown.dart:608:15)
#3      _LotState.overlay_Dialog.<anonymous closure>.<anonymous closure> (package:flutter_app/lot.dart:801:49)
#4      _StatefulBuilderState.build (package:flutter/src/widgets/basic.dart:6504:48)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
```

```
```

```
```

**Comment by janmoppel** [comment]
Hello @damanjeetkaurchadha !

Thank you for posting an issue.
Can you please also provide additional information such as an output of the `flutter doctor -v` command and minimal steps to reproduce this issue?

Thank you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
