### ISSUE TITLE
Dart create too many request when Open ,Create Flutter Project

### ISSUE THREAD

**Issue by vikasgupta4190** [flutter/flutter#44895]
When I create any flutter project or open any project android studio stuck and dart run too many command . Can you please help me to solve this issue.

![image](https://user-images.githubusercontent.com/17292049/68836999-a989a580-06e1-11ea-8850-90be27ad4d75.png)

**Comment by iapicca** [comment]
Hi @vikasgupta4190 
could you please provide your updated  `flutter doctor -v`
and the steps to reproduce the issue?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
