### ISSUE TITLE
[TextField] buildCounter shouldn't return a widget when set on Null and maxLength set

### ISSUE THREAD

**Issue by AlexVincent525** [flutter/flutter#44909]
## Steps to Reproduce

1. Create a `TextField` with `maxLength` set.
2. Set `buildCounter` to `(_, {currentLength, maxLength, isFocused}) => null`.
3. It'll increase the size of the `_Decorator` inside the `TextField`.

Codes like:
```
TextField(
  decoration: InputDecoration(
    border: InputBorder.none,
    contentPadding: EdgeInsets.zero,
    hintText: "请输入您的身份证号码",
  ),
  keyboardType: TextInputType.number,
  maxLength: 18,
  buildCounter: (_, {currentLength, maxLength, isFocused}) => null,
)
```

Screenshots:
![image](https://user-images.githubusercontent.com/15884415/68858474-1459d180-0720-11ea-8772-206d317ddf9f.png)

![image](https://user-images.githubusercontent.com/15884415/68858478-17ed5880-0720-11ea-8515-ee651fb6fce2.png)

**Target Platform: ALL**
**Target OS version/browser: NOT FULLY TESTED**
**Devices: NOT FULLY TESTED**

## Logs
`flutter doctor`:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)
```

**Comment by AlexVincent525** [comment]
And it might related to #18067 .

**Comment by AlexVincent525** [comment]
With `SizedBox` fixed height, still not working.
![image](https://user-images.githubusercontent.com/15884415/68858986-43247780-0721-11ea-9640-d163330528d1.png)

**Comment by iapicca** [comment]
Hi @AlexVincent525 
if I understand correctly with `NULL buildCounter in TextField is not actually NULL`
you mean that the you wish to remove the space taken by the `counter` when set on `null`
am I correct?
thank you

**Comment by AlexVincent525** [comment]
@iapicca That looks great! :smile: Thx for correcting this. It should take no spaces when set to null.

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
Most may already know this, but for the record you can always pass null for (or just exclude) the buildCounter parameter, and it won't render anything:

```dart
TextField(
  buildCounter: null
)
```

<img width="458" alt="Screen Shot 2019-11-15 at 8 07 49 AM" src="https://user-images.githubusercontent.com/389558/68957727-7d246680-077f-11ea-8c3f-60220db36b4e.png">

Most build methods in Flutter currently assert when they return null.  We should probably update buildCounter to do that too, and then explain clearly in the assertion and in the documentation that you should pass `null` for the whole parameter.

However, it should also be possible to render an empty buildCounter based on the its function parameters, like currentLength.  Right now even if you return an empty Container, there is still some space occupied:

```dart
TextField(
  buildCounter: (_, {currentLength, maxLength, isFocused}) => Container(),
)
```

<img width="430" alt="Screen Shot 2019-11-15 at 8 08 11 AM" src="https://user-images.githubusercontent.com/389558/68957961-fae87200-077f-11ea-8c17-b6b5e8fde8d7.png">

So I see three things to do here:

  1. Assert if buildCounter returns null.
  1. Be clear in the docs about all of this.
  1. Investigate why returning something with zero height from buildCounter still occupies some height.

**Comment by AlexVincent525** [comment]
@justinmc I think set buildCounter to null means not to build, and make the builder return null means build nothing. But whatever it means, they should have the same behavior. Is that okay for you?

**Comment by AlexVincent525** [comment]
@justinmc As I tested just now, give `buildCounter` a `null` doesn't take any effect, the counter still appear.
```
TextField(
  decoration: InputDecoration(
    border: InputBorder.none,
    contentPadding: EdgeInsets.zero,
    hintText: "请输入绑定手机号",
    hintStyle: textStyle,
  ),
  keyboardType: TextInputType.phone,
  maxLength: 11,
  buildCounter: null,
)
```
![image](https://user-images.githubusercontent.com/15884415/69020978-4786b400-09f1-11ea-983e-364ad639baf1.png)

**Comment by justinmc** [comment]
@AlexVincent525 You're right, thanks for the example!  For now you can pass an empty Container or a SizedBox.shrink to decoration.counter to get rid of the counter, but it will probably still occupy some height.  I agree that we need to look into this.

**Comment by AlexVincent525** [comment]
@justinmc The most annoying part is the height actually :( , in a form page that everything aligned properly this one just broken everything.

**Comment by AlexVincent525** [comment]
Is there any updates? 🌞

**Comment by HansMuller** [comment]
@AlexVincent525 There probably will not be an update this week, because of the holidays.

**Comment by AlexVincent525** [comment]
@HansMuller That's fine cause it's not the top priority, and hope you guys enjoy your holiday :heart:

**Comment by AlexVincent525** [comment]
As I continued investigate, I found that the size of the gap which is appeared when `counter` was set to `null` comes from the `subtextGap`.

https://github.com/flutter/flutter/blob/84a1de5c74eb9f7e550c6da776c5b621d5b581f6/packages/flutter/lib/src/material/input_decorator.dart#L617

With it's height set to `8.0`, the gap's height is exactly the same value. I tried to comment it out and the gap disappeared. So I think there must be some condition were used which shouldn't use to build the `subtextGap`. I'll try to dig into this tomorrow.

**Comment by AlexVincent525** [comment]
By added logs to methods related to `subtextGap`, the judgement of `counter == null` seems **always be `false`** whether `counter` was set to `null`.
![image](https://user-images.githubusercontent.com/15884415/69770650-dc916600-11c4-11ea-801a-b558a9a48a67.png)
![image](https://user-images.githubusercontent.com/15884415/69770536-54ab5c00-11c4-11ea-9f5a-523674ff2f5a.png)
![image](https://user-images.githubusercontent.com/15884415/69770617-ac49c780-11c4-11ea-96a8-951287ce59c4.png)

**Comment by AlexVincent525** [comment]
And finally I think this judgement makes the counter not disappeared. PR is preparing.
https://github.com/flutter/flutter/blob/714650d7e495e39a8d4c0ca2ec71452dd9de6da1/packages/flutter/lib/src/material/text_field.dart#L758-L773

**Comment by AlexVincent525** [comment]
@justinmc Is there any description about `subtextGap`? There're still cases such as set `counter` in `decoration` to `SizedBox.shrink()` which is another render method, and it's related to the `subtextGap`.

**Comment by AlexVincent525** [comment]
Is there any updates? 🌞

**Comment by AlexVincent525** [comment]
cc @xster

**Comment by justinmc** [comment]
PR is under review and in progress, sorry for the delay!

**Comment by AlexVincent525** [comment]
That's okay, but what I do care about is should `counter` behave the same?

**Comment by justinmc** [comment]
Oh sorry, I see what you mean about `counter` now.

My first thought is to leave the `counter` behavior the same.  If someone wants to remove the subtextGap then they can just pass null for `counter`.  I think this is in line with Flutter's usual behavior.  What do you think?

**Comment by AlexVincent525** [comment]
I can't come out with a more proper solution for now, I'll open a new issue if there's still any problem. Thx for helping me finish this. :+1:

**Comment by justinmc** [comment]
I just merged https://github.com/flutter/flutter/pull/45749 so I'll go ahead and close this 🎉
