### ISSUE TITLE
every flutter app seems jank on my android devices

### ISSUE THREAD

**Issue by lawliet467** [flutter/flutter#44901]
I experience the janky ui on my any Android device.(Xiaomi 6，Xiaomi 8，Huawei p30，), but some other devices run well.
no matter scroll, switch tab or other simple interaction, the app is lower 60 fps.
I tested some flutter app, including offical flutter app, they all lead to the same experience.

please tell me what's the problem with this situation.is it flutter not compatible with some android device? 

here's the preview
https://drive.google.com/open?id=1StG18kxAMqaJ98lEGBw0--j1U4tV6FQz

my updated `flutter doctor -v`

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale
    zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/jason/Downloads/flutter
    • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jason/Library/Android/sdk
    • Android NDK at /Users/jason/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is
        different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see
        https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • MI 6 • e96002b7 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.

**Comment by iapicca** [comment]
Hi @lawliet467 
could you please provide your updated  `flutter doctor -v`
and a minimal code sample to reproduce the problem?
Thank you

**Comment by lawliet467** [comment]
> Hi @lawliet467
> could you please provide your updated `flutter doctor -v`
> and a minimal code sample to reproduce the problem?
> Thank you

I dont't have a flutter project., even I install any other flutter apps, it happens always.

**Comment by iapicca** [comment]
Hi again @lawliet467 
I'm not sure to understand,
how are you experiencing this issue without a Flutter project.
Can you please describe the issue more in dept?
thank you

**Comment by lawliet467** [comment]
it means that some my android devices are in the same janky experience which installed the offical flutter example apps.



---Original---

**Comment by iapicca** [comment]
Hi @lawliet467 
without additional information this issue is not actionable;
unfortunately "janky" (quote) is not a sufficient description.
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
