### ISSUE TITLE
Flutter Offline Docs

### ISSUE THREAD

**Issue by MuhmdHsn313** [flutter/flutter#44900]
Hello.
Can I download flutter documentation offline? 
Thanks

**Comment by janmoppel** [comment]
Hello @MuhmdHsn313 !

Thank you for posting an issue.
 
It seems like there was a similar behaviour reported before: #18723
 
As similar question was asked and answered before, closing this thread for now. If proposed solutions won't work for you, please feel free to re-open the issue.
 
Thank you.

**Comment by jamesmashaka** [comment]
Hellow!
How should i get offline documentation for flutter
