### ISSUE TITLE
Document/sample for a single codebase that is different on iOS and Android

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4491]
Flutter allows developers to build UIs that are mostly identical across iOS and Android, yet differ in important ways. Flutter doesn't force developers to build a single uniform UI if they don't want to.

This is a common question from our initial partner discussions, so we might want to document and show strategies for using Flutter in ways that give developers extreme code reuse and yet tweak for individual platforms.

e.g. we could:
- Ensure the FAQ correctly answers this question ("Can I make two UIs that are mostly similar but differ slightly?" and "Can't I use OEM date picker on iOS?")
- Ensure we have a good article on the website explaining the strategy and examples. Probably back that with sample code somewhere.

**Comment by Hixie** [comment]
Does the memechat video address this sufficiently?

**Comment by sethladd** [comment]
Great call! Yes, probably.

Before we close this out, @emshack @efortuna can you link to that codebase?

**Comment by efortuna** [comment]
Yup. Here's the video: https://www.youtube.com/watch?v=w2TcYP8qiRI
And here's the repo: https://github.com/efortuna/memechat

**Comment by sethladd** [comment]
Thanks! It's a great example of a single codebase that is tweaked for iOS and Android.
