### ISSUE TITLE
[devicelab] Print the hostname at the beginning of task execution

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#44924]
Having the hostname printed at the beginning of task execution will help triage flakiness problems. Currently when a task fails it runs again automatically selecting a random machine making it very difficult to find out which machine ran the failing task.

**Comment by godofredoc** [comment]
Keyong can you please take a look?

**Comment by keyonghan** [comment]
Now all agents have been synchronized to save Agent ID.
