### ISSUE TITLE
KeyboardVisibilityPlugin - simple name is already defined

### ISSUE THREAD

**Issue by shariful2011** [flutter/flutter#44927]
This is my flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.17763.864], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.40.1)
[√] Connected device (1 available)

I am getting following error:
project\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:8: error: a type with the same simple name is already defined by the single-type-import of KeyboardVisibilityPlugin
import com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin;
^
1 error

This issue is also in stackoverflow @ [https://stackoverflow.com/questions/58857690/keyboardvisibilityplugin-simple-name-is-already-defined](url)

My project was running fine until I add intl package for DateFormat require on my project. I used following plugins, removed intl package:

  search_widget: ^0.1.0
  animated_text_kit: ^1.3.0
  shimmer: ^1.0.0
  http: ^0.12.0+2
  font_awesome_flutter: ^8.4.0
  flutter_form_builder: ^3.2.7
  flushbar: ^1.7.0
  shared_preferences: ^0.5.3+1
  path_provider: ^1.1.0
  eva_icons_flutter: ^2.0.0
  circular_check_box: ^0.0.2
  sqflite: ^1.1.5
  rxdart: ^0.22.0
  archive: ^2.0.10
  location: ^2.3.5
  image_picker: ^0.6.0+15
  geolocator: ^5.0.1
  webview_flutter: ^0.3.10
  jaguar: ^2.4.36
  jaguar_flutter_asset: ^2.2.0
  data_connection_checker: ^0.3.4
  spinner_input: ^0.1.2

**Comment by iapicca** [comment]
Hi @shariful2011 
I see there's a StackOverflow [question ](https://stackoverflow.com/questions/58857690/keyboardvisibilityplugin-simple-name-is-already-defined)about your issue, 
you might want to try the proposed solution.

Regardless, from your logs the error appears to be related 
to the 3rd Party plugin [keyboard_visibility](https://pub.dev/packages/keyboard_visibility),
if the SO solution doesn't prove effective 
you might want to open an issue in the dedicated [github](https://github.com/adee42/flutter_keyboard_visibility/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
