### ISSUE TITLE
Safari View Status Bar color

### ISSUE THREAD

**Issue by KCWebmaster** [flutter/flutter#44928]
The color of the safari status bar text cant be seen well. For at least safari on ios 12.4.2 Iphone 6
When launching a website using launch_url the time, battery, network status cannot be seen due to the white text and light gray bar color.

**Comment by iapicca** [comment]
Hi @KCWebmaster 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose` or `flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
