### ISSUE TITLE
Exception caught by widgets library !!!

### ISSUE THREAD

**Issue by BashBB** [flutter/flutter#44926]
I really need help here please,

I'm trying to debug my app but I'm getting this error;

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building ProductItem(dirty):
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 285 pos 10: 'data != null'

```

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

![Screen Shot 2019-11-14 at 10 18 13 PM](https://user-images.githubusercontent.com/57771284/68889291-b207cd80-072d-11ea-8493-19b6d9212431.png)

**Comment by vallicgrr** [comment]
Share your code that you're having the problem with. You likely passed a nulled value to your widget. @BashBB

**Comment by iapicca** [comment]
Hi @BashBB 
it appears to be some error in the code, but to be sure
could you please provide your updated  `flutter doctor -v`
and a minimal code sample to reproduce the problem
Thank you

**Comment by BashBB** [comment]
Thanks a lot for your help guys;

Below is the flutter doctor -v;
`[✓] Flutter (Channel dev, v1.12.2, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.12.2 at /Users/bash/Development/flutter
    • Framework revision 6de6267942 (2 days ago), 2019-11-13 14:37:20 -0800
    • Engine revision b358dc58fb
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/bash/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 1ACE83D1-84D9-4BB5-983B-EB35CA563CE9 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!

______________________________________________________________________________________________________

`  @override
  Widget build(BuildContext context) {
    final productsData = Provider.of<Products>(context);
    final products = showFavs ? productsData.favoriteItems : productsData.items;
    return GridView.builder(
      padding: const EdgeInsets.all(10.0),
      itemCount: products.length,
      itemBuilder: (ctx, i) => ChangeNotifierProvider.value(
        //builder: (c) => products[i],
        value: products[i],
        child: ProductItem(
            // products[i].id,
            // products[i].title,
            // products[i].imageUrl,
            ),
      ),
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        childAspectRatio: 3 / 2,
        crossAxisSpacing: 10,
        mainAxisSpacing: 10,
      ),
    );
  }
}

____________________________________________________________________________________________________

I hope this can help in finding the solution for this issue.

Thanks again for your generous help and support!

**Comment by vallicgrr** [comment]
@BashBB Can you show where you define / set ProductItem?

**Comment by BashBB** [comment]
Thanks for your reply,
I'm trying to learn and I really do need your generous help.

`class ProductItem extends StatelessWidget {
  // final String id;
  // final String title;
  // final String imageUrl;

  // ProductItem(this.id,this.title,this.imageUrl);



Hope that this answer your question.

**Comment by iapicca** [comment]
Hi @BashBB 
I suspect there might be something wrong with the code rather than flutter itself;
could you please post your full `flutter run --verbose`?
If you put a breakpoint in `ProductItem` what value do you have?
thank you
