### ISSUE TITLE
[fuchsia] JIT `--no-link-platform` causes crashes in flutter apps

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#44925]
This was uncovered by https://github.com/flutter/flutter/pull/44920#discussion_r346462657

More context at: https://github.com/flutter/flutter/issues/44724

This needs to be fixed ASAP.

**Comment by Hixie** [comment]
Putting in December milestone since it says "needs to be fixed ASAP" in the description.

**Comment by gw280** [comment]
Merged in #47242
