### ISSUE TITLE
Allow using dart:indexed_db in flutter apps

### ISSUE THREAD

**Issue by simc** [flutter/flutter#44937]
The dart analyzer fails with the following message when I try to import `dart:indexed_db`:

```
Target of URI doesn't exist: 'dart:indexed_db'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.
```

The package compiles without errors and can use the `dart:indexed_db` library just fine but the error message from the analyzer (and possible pana penalty) is still a problem.

### Steps to Reproduce
import `dart:indexed_db` in a flutter app or package

### flutter doctor -v
```
Flutter (Channel master, v1.11.1-pre.57, on Mac OS X 10.14.5 18F132, locale en-DE)
    • Flutter version 1.11.1-pre.57 at /Users/simon/flutter
    • Framework revision eae05c7daf (36 minutes ago), 2019-11-14 13:19:40 -0800
    • Engine revision 7d6e376d83
    • Dart version 2.7.0
```

**Comment by iapicca** [comment]
Hi @leisim 
thank you for your contribution
(hive is the best)

**Comment by leisim** [comment]
@goderbauer Is this more work than just "flipping a switch"? Is there something I can help with?

**Comment by leisim** [comment]
@iapicca Anything I can help with?

**Comment by PavelPZ** [comment]
The same problem, how I can solve it? Using 1.13.6-pre.44

**Comment by PavelPZ** [comment]
Any news @iapicca? It is blocking error for me. Is any chance for fixing this or is it possible to estimate time for solution?

Try pls this:
1. run ```flutter create test_app```
2. open created ```test_app``` folder in vs code
3. in lib/main.dart file insert ```import 'dart:indexeddb';``` into the first line (there is no problem to import other files, e.g. ```import 'dart:html';```)
4. after that, no running and debugging app is possible`

Thanks a lot for help.

**Comment by Levi-Lesches** [comment]
Is there a reason `indexed_db` is blocked on Flutter in the first place? 

I'm trying to get some internal DB working for my Flutter app and with the mess of plugins I just want to do conditional imports and be done with it, but that seems to not be an option.

**Comment by AsteriskZuo** [comment]
I had the same problem, right? Does anybody know how to do that?

**Comment by Levi-Lesches** [comment]
I personally use `package:idb_shim`. 

It has an API that pretty much exactly matches the indexed_db api, but has implementations for every platform. All you need to do is provide it with a different `IdbFactory` depending on the platform. 

On mobile: 
```dart
import "package:idb_shim/idb_shim.dart";
import "package:idb_shim/idb_io.dart";
import "package:path_provider/path_provider.dart";

/// Provides access to an IndexedDB implementation. 
/// 
/// The mobile implementation is based on a .json file.
Future<IdbFactory> get idbFactory async => getIdbFactoryPersistent(
	(await getApplicationDocumentsDirectory()).path
);
```

On web: 
```dart
import "package:idb_shim/idb_shim.dart";
import "package:idb_shim/idb_browser.dart";

/// Provides access to an IndexedDB implementation. 
/// 
/// The browser has an implementation built-in. 
Future<IdbFactory> get idbFactory async => idbFactoryBrowser;
```

To coordinate it all, simply include these lines to import the correct `IdbFactory`: 
```dart
import "idb_factory_stub.dart"
	if (dart.library.io) "idb_factory_io.dart"
	if (dart.library.html) "idb_factory_web.dart";

Future<Database> getDatabase async => (await idbFactory).open(/* initialization logic here */);
```

This approach does work once set up, and with a mobile implementation as well, may be simpler than a native `indexed_db`.

**Comment by AsteriskZuo** [comment]
ref: https://www.gitmemory.com/issue/flutter/flutter/44937/570559644    
 
According to what is said above, the reason has been found.

**Comment by Levi-Lesches** [comment]
Isn't that just a link to the above comment? It just says the `indexed_bd` is blocked on Flutter, but not why, or if it can be put back.

**Comment by JaredEzz** [comment]
+1. Still hoping to use indexed_db in Flutter Web apps.

**Comment by Jordan-Nelson** [comment]
Is there a specific reason this isn't supported? Is this as simple as adding `dart:indexed_db` to the copy of the Dart SDK used for analysis as was done in #12435 for `dart:html`, `dart:js`, & `dart:js_util`? If so, are you open to contributions?

CC: @devoncarew

**Comment by tomasweigenast** [comment]
Still waiting for this lol

**Comment by MarcoPellicciottaOSF** [comment]
Adding a comment here because since web browser supports this, all other platforms can easily support. Please provide a solution, since adding more and more packages makes the app grow in complexity. Using standard core libraries should be preferred.

**Comment by jonahwilliams** [comment]
indexed_db was only ever available in flutter_web applications, it does not work in flutter as we did not ship an indexed_db implementation in the engine. We have no plans to do so in the future.
