### ISSUE TITLE
Getting error in Flutter Share only on iPad

### ISSUE THREAD

**Issue by saeedjassani** [flutter/flutter#44962]
When using the Share plugin on iPad, I am getting the following error:

```
    "<ShareData: 0x60000091e620>"
)
        Probably at least one of the constraints in the following list is one you don't want.
        Try this:
                (1) look at each constraint and try to figure out which you don't expect;
                (2) find the code that added the unwanted constraint or constraints and fix it.
(
    "<NSLayoutConstraint:0x600002a935c0 LPLinkView:0x7fbcd8e1e970.leading == UILayoutGuide:0x600003010700'UIViewLayoutMarginsGuide'.leading   (active)>",
    "<NSLayoutConstraint:0x600002a926c0 H:[LPLinkView:0x7fbcd8e1e970]-(59)-|   (active, names: '|':_UIActivityContentTitleView:0x7fbcd66fa360 )>",
    "<NSLayoutConstraint:0x600002a868f0 H:|-(0)-[_UIActivityContentTitleView:0x7fbcd66fa360]   (active, names: '|':_UINavigationBarContentView:0x7fbcd8e20880 )>",
    "<NSLayoutConstraint:0x600002a86b70 _UIActivityContentTitleView:0x7fbcd66fa360.trailing == _UINavigationBarContentView:0x7fbcd8e20880.trailing   (active)>",
    "<NSLayoutConstraint:0x600002a87110 'UIView-Encapsulated-Layout-Width' _UINavigationBarContentView:0x7fbcd8e20880.width == 0   (active)>",
    "<NSLayoutConstraint:0x600002a93de0 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x600003010700'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIActivityContentTitleView:0x7fbcd66fa360 )>"
)

Will attempt to recover by breaking constraint
<NSLayoutConstraint:0x600002a935c0 LPLinkView:0x7fbcd8e1e970.leading == UILayoutGuide:0x600003010700'UIViewLayoutMarginsGuide'.leading   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

Sharing functionality is working fine in Android as well as iPhones. Getting the above error in iPad only.

Flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.17-pre.77, on Mac OS X 10.15.1 19B88, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.29.1)
[✓] Connected device (1 available)

• No issues found!
```

Any help will be greatly appreciated, thanks!

**Comment by iapicca** [comment]
Hi @saeedjassani 
could you please provide a minimal code sample to reproduce the problem
Thank you

**Comment by saeedjassani** [comment]
Code to reproduce:

`Share.share('check out my website https://example.com');`

**Comment by agreensh** [comment]
Looking at the code for the share plugin, I see this

`if (!CGRectIsEmpty(origin)) {
    activityViewController.popoverPresentationController.sourceRect = origin;
  }`

so unless the caller supplies a 'sharePositionOrigin' rect, this will fail on an iPad (as on iPad the 'popoverPresentationController.sourceRect' **has** to be supplied).

Simple workaround should be to pass in a sharePositionOrigin' rect.

**Comment by saeedjassani** [comment]
Thanks for you comment @agreensh . I don't have any experience of iOS development. Can you suggest any work-around for me which which help me solve the issue?

**Comment by agreensh** [comment]
> Thanks for you comment @agreensh . I don't have any experience of iOS development. Can you suggest any work-around for me which which help me solve the issue?

I have... in your Dart code, pass the `sharePositionOrigin` parameter with non-zero rect to Share.share(...).

**Comment by sensuikan1973** [comment]
I have the same problem.

## Cause
https://github.com/flutter/plugins/blob/8380988745e4bfe6c8d547272b4fe1c3193514be/packages/share/ios/Classes/SharePlugin.m#L102-L105

```SharePlugin.m
  if (!CGRectIsEmpty(origin)) {
    activityViewController.popoverPresentationController.sourceRect = origin;
  }
  [controller presentViewController:activityViewController animated:YES completion:nil];
```

In iPad, Action Sheet always shows as popover.
So, if I do not pass `sharePositionOrigin`, this error occurs

## Workaround
for example, I expressly pass `sharePositionOrigin` like this.
```dart
Share.share(
  'foo',
  sharePositionOrigin: Rect.fromCenter(center: Offset(100, 100), width: 100, height: 100),
)
```

**Comment by bowenchin** [comment]
I am facing the same issues too. The share sheet refuses to pop up on iPad, but works fine on iPhone.

**Comment by agreensh** [comment]
Have you used the workaround?

**Comment by bowenchin** [comment]
Yes I have used the workaround and now the Share sheet shows up on the iPad, however, it's not an ideal long term solution.

**Comment by karmazinkd** [comment]
> 
> 
> I have the same problem.
> ## Cause
> 
> https://github.com/flutter/plugins/blob/8380988745e4bfe6c8d547272b4fe1c3193514be/packages/share/ios/Classes/SharePlugin.m#L102-L105
> 
> ```
>   if (!CGRectIsEmpty(origin)) {
>     activityViewController.popoverPresentationController.sourceRect = origin;
>   }
>   [controller presentViewController:activityViewController animated:YES completion:nil];
> ```
> 
> In iPad, ActionSheet always shows as popover.
> So, if I do not pass `sharePositionOrigin`, this error occurs. i think.
> ## Workaround
> 
> I expressly pass `sharePositionOrigin` like this.
> 
> ```dart
> await Share.share(
>   'foo',
>   sharePositionOrigin: Rect.fromCenter(center: Offset(100, 100), width: 100, height: 100),
> )
> ```
> 
> if I attatch workaround to only `iPad`, use deviceinfo plugin. like this.
> 
> ```dart
> Future<bool> _isIpad() async {
>   final iosInfo = await DeviceInfoPlugin().iosInfo;
>   return iosInfo.name.toLowerCase().contains('ipad');
> }
> ```
> 
> But this behavior is not ideal...

Thank you. With this workaround, it doesn't crash which is great.
But here is one thing: it shows this pop-up dialog.
![image](https://user-images.githubusercontent.com/15160049/75918261-162cd980-5e64-11ea-97af-195ff8c36e9f.png)

but when you tap on 'Edit Actions' it throws the same exception in the log (doesn't crash though):

```
Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002e16e40 V:|-(15)-[UILabel:0x7fb9c0443b40]   (active, names: '|':UITableViewCellContentView:0x7fb9c04437e0 )>",
    "<NSLayoutConstraint:0x600002e17840 V:[UILabel:0x7fb9c0443b40]-(15)-|   (active, names: '|':UITableViewCellContentView:0x7fb9c04437e0 )>",
    "<NSLayoutConstraint:0x600002e14870 UILabel:0x7fb9c0443b40.height >= 22   (active)>",
    "<NSLayoutConstraint:0x600002e276b0 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fb9c04437e0.height == 44   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002e14870 UILabel:0x7fb9c0443b40.height >= 22   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

iPad Pro (3-gen) simulator.
iOS 13.3

**Comment by iapicca** [comment]
Hi @saeedjassani 
I see there's an open [issue](https://github.com/flutter/flutter/issues/19152) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
