### ISSUE TITLE
font icon not rendered in chrome

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#44972]
MacBook-Pro:~ admin$ flutter --version
Flutter 1.12.1-pre.62 • channel master • git@github.com:flutter/flutter.git
Framework • revision 851d6996e7 (6 hours ago) • 2019-11-14 17:14:26 -0800
Engine • revision 77c3512ec8
Tools • Dart 2.7.0
![image](https://user-images.githubusercontent.com/2295872/68923843-3bfd7800-07ba-11ea-913c-faf67f552d08.png)

![image](https://user-images.githubusercontent.com/2295872/68923853-40c22c00-07ba-11ea-8310-59f236db0c0b.png)

**Comment by iapicca** [comment]
Hi @lyf571321556 
could you please provide your updated  `flutter doctor -v`
and describe the issue more in details?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by lyf571321556** [comment]
==> flutter doctor -v
[✓] Flutter (Channel master, v1.11.1-pre.50, on Mac OS X 10.15.1 19B88, locale
    zh-Hans-CN)
    • Flutter version 1.11.1-pre.50 at /Users/liuyanfeng/Library/flutter
    • Framework revision 3d65c21a97 (2 days ago), 2019-11-14 10:29:17 -0500
    • Engine revision 7d6e376d83
    • Dart version 2.7.0


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/liuyanfeng/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/liuyanfeng/Library/Android/sdk
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.7402

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.97
    • Web Server • web-server • web-javascript • Flutter Tools

dart code :
 ListTile(
                  leading: new Icon(Icons.language,
                      color: index == currentPageIndex
                          ? Theme.of(context).primaryColor
                          : null),
                  trailing: Icon(Icons.keyboard_arrow_right),
                  title: Text("Language"),
                )
ui in chrome:
![截屏2019-11-1613 55 57](https://user-images.githubusercontent.com/2295872/68988878-59dde200-0879-11ea-89ec-2e666241c53d.png)

**Comment by yjbanov** [comment]
What command do you use to run the app? Please also provide command-line arguments.

**Comment by yjbanov** [comment]
It would be useful for us to have the console log in Chrome DevTools and the command you ran to launch the app.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
