### ISSUE TITLE
Precompiled runtime requires a precompiled snapshot

### ISSUE THREAD

**Issue by kelciej** [flutter/flutter#44973]
## Steps to Reproduce

1. Crash:
Precompiled runtime requires a precompiled snapshot 
![image](https://user-images.githubusercontent.com/19542871/68922855-c42e4e00-07b7-11ea-834f-3d6d28a1e04b.png)
2. Flutter app is a module in the main project. 
3. Where can I find the precompiled snapshot ?

**Target Platform:Android
**Target OS version/browser:** android 9
**Devices:**vivoS1

**Comment by iapicca** [comment]
Hi @kelciej 
could you please describe the issue more in details
and provide your `flutter doctor -v`
together with your full `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
