### ISSUE TITLE
flutter run (and build) should fail with a descriptive message when targeted iOS armv7 devices

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#4498]
See https://github.com/flutter/flutter/issues/4489

**Comment by cbracken** [comment]
FYI #7913 limits target architecture to `arm64` so `armv7` builds should no longer happen by default.

Leaving open since we should still catch this in `xcode_backend.sh` and bail out with a useful error message. Suggestion:
```
Error: Flutter does not currently support armv7 builds.
In your Xcode project's Build Settings tab, set 'Architectures' to 'arm64'
```

**Comment by eseidelGoogle** [comment]
See also https://github.com/flutter/flutter/issues/2089 which is about just adding support for armv7.

**Comment by eseidelGoogle** [comment]
I think we can just close this and do #2089 instead (which I expect us to do in M3)?  Please re-open if you believe this is urgently needed for M2.
