### ISSUE TITLE
[quick_actions] Support shortcut pinning?

### ISSUE THREAD

**Issue by langemeijer** [flutter/flutter#44987]
Android supports 'Pinned shortcuts' https://developer.android.com/guide/topics/ui/shortcuts.html

These are similar to app icons on the launcher home screen except that they can be managed by the application itself.

This can be implemented by using the android [ShortcutManager class](https://developer.android.com/reference/android/content/pm/ShortcutManager) in the `requestPinShortcut` and `getPinnedShortcuts` methods.

Other parts of this same API is also used by the quick_actions plugin. From a technical perspective it would make sense to have the quick_actions plugin handle the pinned shortcuts as well, except that on a functional level, it more closely resembles functionality like the flutter_dynamic_icon plugin. If this pinned shortcuts would be implemented in quick_actions, this would mean that quick_actions is partially android-specific and that is not a good thing.

I'm happy to do any work on this, but I'd like someone to tell me what the best way would be to implement this.

**Comment by stuartmorgan** [comment]
Given that this is conceptually very different from what is provided by the quick_actions plugin, a new special-purpose (third-party) plugin, rather than substantially expanding the scope of quick_actions, seems like the best path forward for this functionality.
