### ISSUE TITLE
Color of TaskDescription Bar not changing according to darkTheme and themeMode properties

### ISSUE THREAD

**Issue by fribeau** [flutter/flutter#44991]
## Steps to Reproduce

I have a ```MaterialApp``` widget and I am using `theme`, `darkTheme` and `themeMode` properties to style it (I am changing the `themeMode` property dynamically with `Provider`).

If I set the `themeMode` to `ThemeMode.dark` the TaskDescription bar is using the `primaryColor` of the `theme` property and not the one of the `darkTheme` as I would expect.

Examples:
[https://imgur.com/a/BrxxsK8](https://imgur.com/a/BrxxsK8)

This is the relevant part of my code:

```
Consumer<AppSettings>(
    builder: (context, appSettings, _) => MaterialApp(
        themeMode: appSettings.themeMode,
        theme: ThemeData(
            primaryColor: Colors.red,
            accentColor: Colors.orangeAccent.shade400,
            brightness: Brightness.light,
        ),
        darkTheme: ThemeData(
            primaryColor: Colors.blueGrey.shade600,
            accentColor: Colors.orangeAccent.shade400,
            brightness: Brightness.dark,
        ),
    ),
)
```

For the moment I have bypassed the problem by doing this:

```
Consumer<AppSettings>(
    builder: (context, appSettings, _) => MaterialApp(
        themeMode: appSettings.themeMode,
        theme: ThemeData(
            primaryColor: appSettings.themeMode != ThemeMode.dark
                                     ? Colors.red
                                     : Colors.blueGrey.shade600,
            accentColor: Colors.orangeAccent.shade400,
            brightness: Brightness.light,
        ),
        darkTheme: ThemeData(
            primaryColor: Colors.blueGrey.shade600,
            accentColor: Colors.orangeAccent.shade400,
            brightness: Brightness.dark,
        ),
    ),
)
```

**Target Platform:** Android
**Target OS version/browser:** Android 9.0
**Devices:** LG G6

## Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.17-pre.61, on Linux, locale fr_FR.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (3 available)

• No issues found!
```

```
```

**Comment by fribeau** [comment]
I have not finish the issue. Sorry. I pressed the button accidentally.

**Comment by HansMuller** [comment]
@fribeau no problem, let us know when the issue's description is complete.

**Comment by fribeau** [comment]
@HansMuller, thank you for your comprehension. I have finished to edit the issue.

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by TahaTesser** [comment]
Hi @fribeau 
Are you still experiencing with issue with latest `stable` channel?
if yes, can you please provide your `flutter doctor -v`?
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
