### ISSUE TITLE
Make it possible for customers to create an APK w/o building with Ninja in flutter/engine

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#45]

**Comment by eseidelGoogle** [comment]
@jason-simmons said he'd take a look.

**Comment by eseidelGoogle** [comment]
Filed https://github.com/flutter/flutter/issues/391 about iOS.

**Comment by abarth** [comment]
The `flutter apk` command can do this now.

**Comment by pietergreyling** [comment]
Since https://github.com/flutter/flutter/issues/124 is also closed, do we have a pointer to where "flutter apk" is documented?

**Comment by abarth** [comment]
> do we have a pointer to where "flutter apk" is documented?

It's in the "Building a standalone APK" section of http://flutter.io/getting-started/
