### ISSUE TITLE
Ability to animate DraggableScrollableSheet

### ISSUE THREAD

**Issue by filiph** [flutter/flutter#45009]
## Use case

Draggable bottom sheets are relatively new UI metaphors, and users might need a little nudge to understand what they're supposed to do. Otherwise all that content in the bottom sheet will never be seen.

What I'd like to do is to make the `DraggableScrollableSheet` child "jump" up and down to get the user's attention, and to show the fact there's more content there. Alternatively, I want to start the screen with the sheet half open, and then immediately (but slowly) slide it down.

`DraggableScrollableActuator` currently has a single method, [`reset`](https://api.flutter.dev/flutter/widgets/DraggableScrollableActuator-class.html#static-methods). This helps for immediate resetting to default place, but not for communicating things to the user. If there is any other way to programmatically animate the child size of the `DraggableScrollableSheet`, I haven't found it.

This has been [asked for on StackOverflow](https://stackoverflow.com/questions/56820661/flutter-draggablescrollablesheet-how-to-expand-collapse-programmatically), and the answer says:

> I needed this for myself. [...] I ended up copying the DraggableScrollableSheet and adjusting it to my need.

Similar (but not identical) feature requests:

* https://github.com/flutter/flutter/issues/34242 asks for a controller so that a scroll in the body can "spill" into the sheet
* https://github.com/flutter/flutter/issues/41599 is asking for an equivalent of `MainAxisSize.min` (but has "dynamic height" in title so could be confused with this).

## Proposal

`DraggableScrollableActuator` gets a new method: `animateTo`. This method forwards its arguments to the `DraggableScrollableSheet`'s controller. 

Expected use:

```dart
DraggableScrollableActuator.animateTo(
    0.1,
    duration: const Duration(milliseconds: 200),
    curve: Curves.easeInOut,
);
```

Other solutions would work, too. E.g. having `controller` as a parameter to `DraggableScrollableSheet` itself would be my preferred (but maybe too "low level"?).

```dart
DraggableScrollableSheet(
  initialChildSize: 0.1,
  minChildSize: 0.1,
  controller: myController,
  builder: (context, controller) {
    // ...
  },
);
```

**Comment by filiph** [comment]
FWIW, [here's the controller API](https://github.com/akshathjain/sliding_up_panel#using-the-panelcontroller) of the very similar `SlidingUpPanel` in `package:sliding_up_panel`.

|  Methods  | Description |
|-----------|-------------|
|`open()`| Opens the sliding panel fully (i.e. to the  `maxHeight`) |
|`close()`| Closes the sliding panel to its collapsed state (i.e. to the  `minHeight`) |
|`hide()`| Hides the sliding panel (i.e. is invisible) |
|`show()`| Shows the sliding panel in its collapsed state (i.e. "un-hide" the sliding panel) |
|`setPanelPosition(double value)`| Sets the panel position (without animation). The value must between 0.0 and 1.0 where 0.0 is fully collapsed and 1.0 is completely open. |
|`animatePanelToPosition(double value)`| Animates the panel position to the value. The value must between 0.0 and 1.0 where 0.0 is fully collapsed and 1.0 is completely open. |
|`getPanelPosition()`| Gets the current panel position. Returns the % offset from collapsed state to the open state as a decimal between 0.0 and 1.0 where 0.0 is fully collapsed and 1.0 is full open. |
|`isPanelAnimating()`| Returns whether or not the panel is currently animating. |
|`isPanelOpen()`| Returns whether or not the panel is open. |
|`isPanelClosed()`| Returns whether or not the panel is collapsed.|
|`isPanelShown()`| Returns whether or not the panel is shown/hidden.|

**Comment by dnfield** [comment]
I don't think we should let people provide the controller for DraggableScrollableSheet - it's a bit delicate and it was intentionally hidden away to avoid exposing weirdness/traps in the API.

I'm not really opposed to adding these methods to the actuator (/cc @HansMuller who may have more thoughts on that though). I suspect at one point I was assuming this could have been otherwise handled by just wrapping the whole thing in an `AnimatedBuilder` to drive the `initialChildHeight`, but I can see that may not be correct (e.g. `reset` would then go "back" to the wrong height).

**Comment by knightsforce** [comment]
I want to respond to the appearance of the keyboard.
Since inside DraggableScrollableSheet I have a text box.
But at the moment I can’t do it.
You must provide the ability to control the widget.
And the developer himself will decide whether he needs it or not.

**Comment by digitalkaoz** [comment]
@dnfield here is your proposal implemented (but it doesnt work and i dont why, i can see the `animation.value` is correctly changed, but it doesnt affect the sheet)

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class BottomSheet extends StatefulWidget {
  final Widget Function(Function) childBuilder;
  final double min;
  final double max;

  const BottomSheet({
    Key key,
    @required this.childBuilder,
    this.min: 0.25,
    this.max: 0.8,
  }) : super(key: key);

  @override
  _BottomSheetState createState() => _BottomSheetState();
}

class _BottomSheetState extends State<BottomSheet>
    with SingleTickerProviderStateMixin {
  AnimationController animationController;
  Animation animation;

  @override
  void initState() {
    super.initState();
    animationController = AnimationController(vsync: this);
    animation =
        Tween(begin: widget.min, end: widget.max).animate(animationController);
  }

  _toggle() {
    if (animationController.value == widget.max) {
      animationController.animateTo(widget.min,
          duration: Duration(milliseconds: 200), curve: Curves.bounceOut);
    } else {
      animationController.animateTo(widget.max,
          duration: Duration(milliseconds: 200), curve: Curves.bounceIn);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: animation,
      child: _sheet(animation),
      builder: (BuildContext context, Widget child) {
        //print(animation.value); // height is correct applied
        print((child as DraggableScrollableSheet).initialChildSize); //but here its always the same
        return _sheet(animation); //we would need to modify child here i guess
      },
    );
  }

  Widget _sheet(Animation animation) {
    return DraggableScrollableSheet(
      initialChildSize: animation.value,
      minChildSize: animation.value,
      maxChildSize: widget.max,
      builder: (BuildContext context, ScrollController scrollController) =>
          SingleChildScrollView(
              controller: scrollController,
              child: Column(
                children: <Widget>[
                  GestureDetector(
                    onTap: _toggle,
                    child: Container(
                      color: Colors.white.withAlpha(50),
                      width: double.infinity,
                      child: Chip(
                        label: Text('Expand'),
                        labelStyle: TextStyle(color: Colors.white),
                      ),
                    ),
                  ),
                  Container(
                    height: 400,
                    color: Colors.red,
                  ),
                ],
              )),
    );
  }
}
```

thats to much fraction for a simple task like `expand` or `collapse`.

Is there any easier solution to open/close the `DraggableScrollableSheet` manually?

**Comment by srombs** [comment]
I have been able to get animation of the sheet by plugging into the DraggableScrollableActuator reset method and using an AnimationController / Tween to control what value the current extent will be. It has been working out decently so far.

**Comment by rohnsht** [comment]
Can anybody write the full code to reset DraggableScrollableSheet using DraggableScrollableActuator because  DraggableScrollableAcutator.reset(context) is not working for me at all.

Thanks

**Comment by srombs** [comment]
@rohnsht The docs says it notifies a decendent widget of type DraggableScrollSheet to reset itself. https://api.flutter.dev/flutter/widgets/DraggableScrollableActuator-class.html

So put the actuator above the sheet and use the sheet's context in the reset static method. I left out a list widget in the sheet's builder for brevity sake.




```
@override
  Widget build(BuildContext context) {
  	return DraggableAnimatedScrollableActuator(
        child: DraggableAnimatedScrollableSheet(
        	minChildSize: 0.1,
          	maxChildSize: 1.0,
          	initialChildSize: 0.5,
          	builder: (sheetContext, scrollController) {
          		// call this when a user taps etc.
          		DraggableAnimatedScrollableActuator.reset(sheetContext);
          	}
        ),
    ),
 );
}
```

**Comment by IAmSarthakVerma** [comment]
Hello Guys, I have this code :

`              DraggableScrollableActuator(
                child: DraggableScrollableSheet(
                  builder: (context, scrollController) {
                    return SingleChildScrollView(
                      controller: scrollController,
                      child: Container(
                        height: screenHeight * 1,
                        decoration: BoxDecoration(
                            borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(kRadius),
                                topRight: Radius.circular(kRadius)),
                            color: kBGCard),
                      ),
                    );
                  },
                  initialChildSize: 0.3,
                  maxChildSize: 1,
                  minChildSize: 0.3,
                ),
              ),
`
Can anyone tell me how can I change the postion(what the user does by dragging) of this DraggableScrollableSheet widget programmatically ?

**Comment by Sun3** [comment]
Any updates on this feature?

Thank you.

**Comment by Xgamefactory** [comment]
must have a feature.  untill package:sliding_up_panel

**Comment by rodriigovieira** [comment]
@srombs could you share the code you used for your implementation? I managed to make the DraggableScrollableActuator to work using the code you provided, but the animation is not decent and I can only scroll back to the initial position, not being able to both slide it up and down.

**Comment by Sun3** [comment]
@rodriigovieira I created a sample project that you can look at [Draggable Snappable](https://github.com/JediPixels/draggable_snappable), in the future, the snapping animation can be improved.

**Comment by giorgio79** [comment]
Also, in the Google Maps app itself, the bottom DraggableScrollable also slides the Google Maps container above it. So they are sliding together. Any plans for sg like this?

**Comment by MalteMagnussen** [comment]
Currently trying to make a DraggableScrollableSheet so that if someone taps it, it extends fully, with an animation of it opening, as if you had dragged it.
And so that if you tap it, it closes again, with the animation as if you had dragged it closed. 

Is there any way to do this?

**Comment by SilversDCODE** [comment]
Below code is work for me, please try :

```
import 'package:flutter/material.dart';

void main() {
  runApp(Pad());
}

class Pad extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bottom Sheet guide',
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {

  bool dragableSheetPopUpController = false;
  double dragableSheetInitialSize = 0.1;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Stack(
        children: [
          Center(child: Text('Body'),),

          GestureDetector( //this GestureDetector use for tapping a Container that expanded
            onTap: () {
              dragableSheetPopUpController = false;
              print('Pop-up = $dragableSheetPopUpController');
              setState(() {
                dragableSheetInitialSize = 0.1;  
              });
            },
            child: Container(
              child: dragableSheetPopUpController == false ? // check status of Pop-up
                GestureDetector(
                  onTap: () {
                    dragableSheetPopUpController = true;
                    print('Pop-up = $dragableSheetPopUpController');
                    setState(() {
                      dragableSheetInitialSize = 1.0;
                    });
                  },
                  child: DragableScrollableSheet(dragableSheetInitialSize),
                )
                : DragableScrollableSheet(dragableSheetInitialSize),
            ),
          ),
        ]
      ),
          
    );
  }
}


class DragableScrollableSheet extends StatelessWidget {

  final double dragableSheetInitialSize;
  DragableScrollableSheet(this.dragableSheetInitialSize);

  @override
  Widget build(BuildContext context) {
    return DraggableScrollableSheet(
        minChildSize: 0.1,
        maxChildSize: 1.0,
        initialChildSize: dragableSheetInitialSize,
        builder: (context, scrollController) {
          return Padding(
            padding: const EdgeInsets.all(2.0),
            child: Container(
              height: 10.0,
              decoration: BoxDecoration(
                  borderRadius: BorderRadius.all(Radius.circular(10.0)),
                  color: Colors.green),
              child: ListView(
                controller: scrollController,
                children: [
                  Container(
                    padding: EdgeInsets.all(20.0),
                    alignment: Alignment.center,
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceAround,
                      mainAxisSize: MainAxisSize.min,
                      children: [
                      Icon(Icons.ac_unit),
                      SizedBox(width: 10.0,),
                      Text('Show Dragable Scrollable Sheet'),
                    ],),
                    ),
                  ListTile(leading: Icon(Icons.ac_unit), title: Text('List 1'),),
                  ListTile(leading: Icon(Icons.ac_unit), title: Text('List 2'),),
                  ListTile(leading: Icon(Icons.ac_unit), title: Text('List 3'),),
                  ListTile(leading: Icon(Icons.ac_unit), title: Text('List 4'),),
                  ListTile(leading: Icon(Icons.ac_unit), title: Text('List 5'),),
                  ListTile(leading: Icon(Icons.ac_unit), title: Text('List 6'),),
                  ListTile(leading: Icon(Icons.ac_unit), title: Text('List 7'),),
                  ListTile(leading: Icon(Icons.ac_unit), title: Text('List 8'),),
                  ListTile(leading: Icon(Icons.ac_unit), title: Text('List 9'),),
                  ListTile(leading: Icon(Icons.ac_unit), title: Text('List 10'),),
                  ListTile(leading: Icon(Icons.ac_unit), title: Text('List 11'),),
                  ListTile(leading: Icon(Icons.ac_unit), title: Text('List 12'),),
                  
                ],
              ),
            ),
          );
        });
  }
}
```

**Comment by caseycrogers** [comment]
Hey all, @Alexays and I have created a proposal (see [doc](https://docs.google.com/document/d/15A3q1QrcvEU82uG4heTCKV230depmaJZTIP5rEz7V8g/edit?usp=sharing&resourcekey=0-q-TH-9-LVmygnp6Ku4xKIg)) to address this issue! There were enough options to consider that we want feedback on our proposal before creating a PR. If you're interested, please comment on the doc linked above!
