### ISSUE TITLE
Missing frame budget when heroing in Grid demo in Gallery

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4501]
(on iOS and Android)

Open Gallery, Components, Grid. Tap to open a picture. Then tap back.

Expected: 60fps when we "hero" up an image into full screen and "reverse hero" when we shrink back the image into the grid layout.

Actual: I see spikes in the Engine chart and the rasterizer chart. Those spikes appear when I tap into, and tap back, the images in the grid.

![6c6e1cbf-bc2e-4728-80e5-b4d8c2413add](https://cloud.githubusercontent.com/assets/5479/15944839/406348fa-2e44-11e6-8440-0ee45e92b18a.PNG)

![screenshot_20160609-131800](https://cloud.githubusercontent.com/assets/5479/15944942/d0829eae-2e44-11e6-9f67-110fda450ab7.png)

**Comment by eseidelGoogle** [comment]
FYI @abarth, we'll need to trace and find out.

**Comment by mpcomplete** [comment]
Happens with Pesto demo too.

**Comment by sethladd** [comment]
Still seeing on iOS, but mostly when I tap "back" and shrinking an image on my iPhone 6S.

The spikes below are generated when I tap "back" into the grid list.

![114bf8ed-43ba-4b26-9308-4d452e5d1aca](https://cloud.githubusercontent.com/assets/5479/16969095/84a7a356-4dc7-11e6-88ce-1ca026d0ab42.PNG)

**Comment by sethladd** [comment]
Traces (of just me tapping "back" to de-hero back into the grid display)

[dart-timeline-2016-6-19.json.zip](https://github.com/flutter/flutter/files/372611/dart-timeline-2016-6-19.json.zip)

and another:

[dart-timeline-2016-6-19-2.json.zip](https://github.com/flutter/flutter/files/372612/dart-timeline-2016-6-19-2.json.zip)

This looks like the missed frame:

![screen shot 2016-07-19 at 4 01 25 pm](https://cloud.githubusercontent.com/assets/5479/16969491/16841cc6-4dca-11e6-939a-8356af7e3a3d.png)

**Comment by eseidelGoogle** [comment]
@abarth says this is the same as https://github.com/flutter/flutter/issues/5007 which is related/same as https://github.com/flutter/flutter/issues/3805

**Comment by abarth** [comment]
This is fixed by async image decoding.  The chart now oscillates between being at zero and at 60 Hz, which is just showing us whether we're in low or high latency mode.
