### ISSUE TITLE
Remove FLUTTER_DEVICELAB_XCODE_PROVISIONING_CONFIG

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#45016]
The environment variable FLUTTER_DEVICELAB_XCODE_PROVISIONING_CONFIG is no longer needed after https://github.com/flutter/flutter/pull/43553/. The provisioning config can be provided by the following env vars instead:

- FLUTTER_XCODE_CODE_SIGN_STYLE=Manual
- FLUTTER_XCODE_DEVELOPMENT_TEAM=<team>
- FLUTTER_XCODE_PROVISIONING_PROFILE_SPECIFIER=<profile>

/cc @jmagman

**Comment by jmagman** [comment]
Is issue to remove the code path from the tool?

**Comment by digiter** [comment]
Remove the code path from the tool. FLUTTER_DEVICELAB_XCODE_PROVISIONING_CONFIG is not in use.
