### ISSUE TITLE
Problem with ad-hoc export for iOS version

### ISSUE THREAD

**Issue by SAAVY-ware** [flutter/flutter#45028]
I wrote an app with flutter and it is running on my iPhone in debug mode. Now i want to send it to my employer, So i've create an ad-hoc version of my app and create a "Diawi" link. After that i did check the app on my device and the app is installed on my device but not working and keep crashing after tap on the app icon.

My app icon was a round icon and i did change it to square.

Here i found when checking windows->devices :

Exception Type: EXC_BAD_ACCESS (SIGKILL - CODESIGNING)

Exception Subtype: UNKNOWN_0x32 at 0x00000001046c1c80

.

.

.

Termination Reason: Namespace CODESIGNING, Code 0x2

Triggered by Thread: 13

Is it possible that it's related to creating a bad provisioning profile?

Is there anyone faced this problem?

Any help would be appreciated.

**Comment by iapicca** [comment]
Hi @SAAVY-ware 
it's possible that the error you are describing isn't related to flutter;
could you please provide your updated  `flutter doctor -v`
and your `flutter build --verbose` ?
Thank you

**Comment by jmagman** [comment]
Your app may be using an API that requires an entitlement it doesn't have.  A sample app that reproduces the issue may help (though of course we can't test your provisioning profile).  If you open Console and select your device, and reproduce the issue, sometimes there are interesting security logs right before the crash that say exactly what's going on.

You can also try creating a new app in Xcode without any Flutter bits and try to ad-hoc sign.  If that doesn't work, this is some signing issue that `flutter` probably can't do much about...

**Comment by dabing1022** [comment]
Same here. But a little different, I build a  in-house ipa by in-house cert. After tap the app icon, it crashed.

```shell
Exception Type:  EXC_BAD_ACCESS (SIGKILL - CODESIGNING)
Exception Subtype: UNKNOWN_0x32 at 0x000000010b801980
VM Region Info: 0x10b801980 is in 0x10b800000-0x10b880000;  bytes after start: 6528  bytes before end: 517759
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      VM_ALLOCATE            000000010b780000-000000010b800000 [  512K] r--/rwx SM=PRV  
--->  VM_ALLOCATE            000000010b800000-000000010b880000 [  512K] r-x/rwx SM=COW  
      VM_ALLOCATE            000000010b880000-000000010ba80000 [ 2048K] rw-/rwx SM=PRV  

Termination Reason: Namespace CODESIGNING, Code 0x2
Triggered by Thread:  28
```

**Comment by Pirensen** [comment]
Same with me, only AD-HOC occured

**Comment by SAAVY-ware** [comment]
> Hi @SAAVY-ware
> it's possible that the error you are describing isn't related to flutter;
> could you please provide your updated `flutter doctor -v`
> and your `flutter build --verbose` ?
> Thank you

Thank you for your response and sorry for my absence.
Not working...

**Comment by iapicca** [comment]
Hi @SAAVY-ware @Pirensen @dabing1022 
as @jmagman  pointed out...

> Your app may be using an API that requires an entitlement it doesn't have. A sample app that reproduces the issue may help (though of course we can't test your provisioning profile). If you open Console and select your device, and reproduce the issue, sometimes there are interesting security logs right before the crash that say exactly what's going on.
> 
> You can also try creating a new app in Xcode without any Flutter bits and try to ad-hoc sign. If that doesn't work, this is some signing issue that `flutter` probably can't do much about...

can you please double check that you your  `ad-hoc sign` works w/o flutter?
Also would be helpful  a minimal code sample to reproduce the problem
thank you

**Comment by mraleph** [comment]
Since DBC deprecation running debug builds of Flutter applications is only supported via `flutter run` or Xcode. Distributing debug builds is not supported. You need to build release build for that following the instructions in the [documentation](https://flutter.dev/docs/deployment/ios). Most notably you need to run `flutter build ios` (or `flutter build ios --release`) to configure your Xcode workspace to produce release build.

**Comment by dabing1022** [comment]
> Since DBC deprecation running debug builds of Flutter applications is only supported via flutter run or Xcode. Distributing debug builds is not supported. You need to build release build for that following the instructions in the documentation. Most notably you need to run flutter build ios (or flutter build ios --release) to configure your Xcode workspace to produce release build.

OK. Thanks.

**Comment by pragadeeshNIS** [comment]
HI guys, 
I am getting this error 

`0x16d4cb000 handle_install: Installation failed: Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.7Vyir3/extracted/Payload/Runner.app : 0xe8008017 (A signed resource has been added, modified, or deleted.)" UserInfo={LibMISErrorNumber=-402620393, LegacyErrorString=ApplicationVerificationFailed, SourceFileLine=183, FunctionName=+[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:], NSLocalizedDescription=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.7Vyir3/extracted/Payload/Runner.app : 0xe8008017 (A signed resource has been added, modified, or deleted.)}
`

May i know why ??

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by SAAVY-ware** [comment]
> Since DBC deprecation running debug builds of Flutter applications is only supported via `flutter run` or Xcode. Distributing debug builds is not supported. You need to build release build for that following the instructions in the [documentation](https://flutter.dev/docs/deployment/ios). Most notably you need to run `flutter build ios` (or `flutter build ios --release`) to configure your Xcode workspace to produce release build.

This is the answer 👌🏻💐
