### ISSUE TITLE
Add button on camera menu for dismiss camera

### ISSUE THREAD

**Issue by cevichero** [flutter/flutter#45023]
Hello, hello,

Is it possible to add a button on camera menu for dismiss camera ?
I want users to be able to return to the home page without having to scan.

Thank you.

**Comment by valconetti** [comment]
Hi @cevichero,
There is a function `dispose()` for this, which you can call on the `CameraController` class. You can call this function in your own app in `main.dart`. As an `onPressed` for a button, for instance. An example of how you can implement this:
```
Future<void> disposeCamera() async {
     if (controller != null) {
      await controller.dispose();
    }
 }
```

If you developed a camera view in a different page, you can also dispose of the `CameraController` in the `dispose()` of your `StatefulWidget`.
