### ISSUE TITLE
androidX is not detected in my flutter project 

### ISSUE THREAD

**Issue by vanchaucoder** [flutter/flutter#45022]
hi, im trying to learn flutter using firebase and image_picker: ^0.6.1+11. Im just learning  to upload image from my phone camera or gallery to firebase. I ran into a problem when i run my app. the error is listed below. the gradle.properties does contain android.useAndroidX=true
android.enableJetifier=true which i added manually.  would someone kindly advice me to fix this issue. im using intellij idea IDE. thank in advance

The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1

**Comment by AmaldevAD** [comment]
update android/gradle.properties  with following code

org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true

**Comment by vanchaucoder** [comment]
I enableR8 to be true but have this error

* What went wrong:                                                      
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  The number of method references in a .dex file cannot exceed 64K.     
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

to solve the problem i click the the link and added this in the  app/build.gradle file and it work for me at least
android {
    defaultConfig {
        ...
        minSdkVersion 15 
        targetSdkVersion 28
        multiDexEnabled true
    }
    ...
}

dependencies {
  implementation 'com.android.support:multidex:1.0.3'
}
