### ISSUE TITLE
Document how to connect Flutter code to native APIs with hello_services example

### ISSUE THREAD

**Issue by ScottPierce** [flutter/flutter#4503]
Has any thought been put into flutter around integrating with already existing android and ios applications, or is flutter intended to be an all or nothing solution? I've seen you can add native android and ios code, but I don't know how easy it'd be to take an already existing application and have flutter work along side it.

**Comment by abarth** [comment]
Yes, https://github.com/flutter/flutter/tree/master/examples/hello_services shows an example of how to do this.  You can use FlutterView to incorporate Flutter into an existing app, either as an android.view.View (on Android) or a UIViewController (on iOS).

**Comment by spierce7** [comment]
So you'd have to end up using pub as your build system for both android and ios in that case?

**Comment by abarth** [comment]
In the hello_services example, the iOS app is built using Xcode and the Android app is build using either gradle or Android Studio.  In neither case is `pub` used as a build system.

**Comment by sethladd** [comment]
cc @qchong
