### ISSUE TITLE
I have issues compiling my flutter app for iOS after integrating Google maps flutter plugin 

### ISSUE THREAD

**Issue by Profmax001** [flutter/flutter#45033]
== Building for iOS ==

== /usr/local/bin/flutter build ios --debug --no-codesign ==
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.example.airtasker for device (ios)...
Running pod install...                                             11.8s
Running Xcode build...                                          
Xcode build done.                                           36.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.21+8/ios/Classes/GoogleMapMarkerController.m:192:38: warning: values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead [-Wformat]

**Comment by iapicca** [comment]
Hi @Profmax001 
could you please provide your updated  `flutter doctor -v`
and your  `flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by jmagman** [comment]
You just included a compilation warning, not the build error.  We'll need the `flutter build ios --debug --no-codesign --verbose` logs.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
