### ISSUE TITLE
Flutter doctor crashed, Unexpected tag 69 (ForStatement) at AndroidStudio._allLinuxOrWindows._hasStudioAt

### ISSUE THREAD

**Issue by AhmedAlaa96** [flutter/flutter#45038]
**I install flutter in my ubuntu 18.10 and it's working okey and suddenly stop working and give me this error when i was using flutter doctor**

## command

flutter doctor

## exception

_CompileTimeError: error: Unexpected tag 69 (ForStatement) in _ListBase&Object&ListMixin@3220832.any, expected expression

```
#0      AndroidStudio._allLinuxOrWindows._hasStudioAt (package:flutter_tools/src/android/android_studio.dart:222:22)
#1      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:238:46)
#2      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:170:40)
#3      AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:20:55)
#4      _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:63:35)
#5      Doctor.validators (package:flutter_tools/src/doctor.dart:132:46)
#6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:139:39)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:211:41)
<asynchronous suspension>
#8      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by iapicca** [comment]
Hi @AhmedAlaa96 
are you running  `flutter doctor -v`
from your flutter console?
Thank you

**Comment by AhmedAlaa96** [comment]
Hi @iapicca 
I'm using android studio terminal then give me this error so I try  **flutter doctor** on ubuntu terminal 
Didn't work either but, after closing the project in android studio and close android studio and try again it worked but i want why that's happens this is not the first time can you help me with that
Thank you

**Comment by jmagman** [comment]
> after closing the project in android studio and close android studio and try again it worked

If it's working now, can we get the output of `flutter doctor -v`?  That will tell us what version you're on so we can try to track it down.

**Comment by AhmedAlaa96** [comment]
@jmagman I run **flutter doctor -v** and that's what i get:
`[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.6 at /home/ahmed-alaa/Android Studio/flutter/flutter
    • Framework revision 68587a0916 (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/ahmed-alaa/Android Studio/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/ahmed-alaa/Android Studio/android-studio-ide-191.5977832-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/ahmed-alaa/Android Studio/android-studio-ide-191.5977832-linux/android-studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)`

**Comment by mraleph** [comment]
This error happens when kernel binary (in this case flutter tool snapshot) has a structure unexpected by the VM. 

The root cause varies: might have been a bug in the CFE or version skew between kernel binary and the VM. 

I think given the age of the issue (and the fact that it went away) we would not be able to track it down to the root cause.
