### ISSUE TITLE
SelectableText doesn't support passing in minLines

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#45043]
Internally b/144379369

SelectableText doesn't support passing in minLines.

Replacing a Text widget with a SelectableText widget causes it to not limit the number of lines to 1 if the text only fits in a single line unlike the Text widget.  SelectableText uses the EditableText widget but doesn't expose the minLines so there is no way to pass minLines as 1.

**Comment by eyjiang** [comment]
Hello! Could I try working on an implementation for this issue?

**Comment by Inconnu08** [comment]
@eyjiang hey sorry I already have a PR ready.

**Comment by shihaohong** [comment]
https://github.com/flutter/flutter/pull/50750 fixes this, so I'm closing the issue.
