### ISSUE TITLE
Documentation for the flutter application communicating with native android and ios code?

### ISSUE THREAD

**Issue by spierce7** [flutter/flutter#4504]
I was taking a look at the source for https://github.com/flutter/flutterfire, and it's obvious that the ios and android code are communicating with the flutter code. I remember the first flutter talk I watched a year or so back at dart summit referred to flutter communicating through some sort of event bus, but I can't seem to find any information about this.

Is there any formal documentation around this that I'm just not seeing? If not, what would be the best way for me to explore and understand what's going on here?

**Comment by abarth** [comment]
https://github.com/flutter/flutter/tree/master/examples/hello_services shows how to hook into the event bus from Dart, Java, and Objective-C.

**Comment by spierce7** [comment]
awesome. Thanks!
