### ISSUE TITLE
[google_maps_flutter] onTap Polygon field not working

### ISSUE THREAD

**Issue by TheoSitnikow** [flutter/flutter#45040]
Hi,

The onTap method is not triggered for Polygon object.
Perhaps I made a mistake but when I try with marker it works.
```
lib: google_maps_flutter 0.5.21+11
platform: Android
ide: Android Studio Windows
device: Samsung S8
```

## code:
```dart
    final Polygon polygon = Polygon(
        polygonId: polygonId,
        fillColor: Colors.transparent,
        strokeColor: Colors.red,
        points: points,
        onTap: () {
          GlobalState().pushEvent(OnParcelleClicked(id));
        });
```

**Comment by janmoppel** [comment]
Hello @TheoSitnikow !

Thank you for posting an issue.
Can you please also attach the `flutter doctor -v` command output?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by darkangel00016** [comment]
In te current version, you have to use the parameter "consumeTapEvents" to work.
