### ISSUE TITLE
Flutter with VR 360 image or video viewer

### ISSUE THREAD

**Issue by abddi** [flutter/flutter#45042]
Hey guys recently i've been searching for a Flutter VR image or video viewer from a specific libraries but unfortunately i could not find anything related to that, what just found the ARcore library and it's not gonna work for me and my team because our client do not have time to wait.
We've switched all of our work structures to flutter because it's Flexible, Fast, Great, Lovely and we just Love it and we hope if there will be something for VR in the near future. 
We have until Jan/2020 to finish the project so we are switching to React and it's libraries to do it because they have mostly everything set for these types of projects.
VR is the future and with Flutter it's gonna be amazing & We know you are working on it guys & We are waiting for this on heat.
Just Release it.

**Comment by iapicca** [comment]
Hi @abddi 
there are 3rd party plugins for AR on [pub.dev]( https://pub.dev/),
please remember that flutter is powered by [skia ](https://skia.org/) which is a 2D engine.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by AdilTOLA** [comment]
Hi @abddi 
check this widget  panorama 0.0.2 (https://pub.dev/packages/panorama)

**Comment by harpreetseera** [comment]
Hi @abddi  you can check thi spackage created by me for 360 images view with gesture controls and rotation features: [imageview360](https://pub.dev/packages/imageview360)
