### ISSUE TITLE
Migrate the e2e tests away from example apps

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#45047]
Internal: b/144571135

Some e2e tests are part of example/test/* directory even though they have no dependency on the example app.

@collinjackson mentioned these need to be migrated to the test/* directory of the plugin. This is an issue for tracking that.

I am not actually sure how many of these are tests. For instance, https://github.com/flutter/plugins/blob/master/packages/share/example/test_driver/test/share_e2e_test.dart seems to be the only file there but is not a test.

**Comment by stuartmorgan** [comment]
I'm not aware of any way of running integration tests for plugins other than in an app; a plugin can't be run with driver. So while they may not use the example app's UI, they do rely on the example app.
