### ISSUE TITLE
Confusing comment for ComponentElement

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4505]
In `framework.dart`, the class level comment for `ComponentElement` says:
```
/// Base class for the instantiation of [StatelessWidget], [StatefulWidget],
/// and [_ProxyWidget] widgets.
```
The exact meaning of this is difficult to grok. `ComponentElement` is not a base class for any of those other classes, so that's not it. Based on the related comment above `Element` that `Elements are the instantiations of Widget configurations`, I think you have a particular meaning in mind for the word instantiation, but it's hard to infer from context.

**Comment by abarth** [comment]
Yeah, I've got a branch where I'm working on the documentation for framework.dart.  There are lots of parts that need improvement, including this one.
