### ISSUE TITLE
Issue from website page Flutter Widget框架概述 (Google translate: Issue from website page Flutter Widget framework overview)

### ISSUE THREAD

**Issue by AndrewXiao** [flutter/flutter#45057]
From URL: https://www.flutterchina.club/widgets-intro.md

"Stack： 取代线性布局 (译者语：和Android中的LinearLayout相似)" 这句 (Google translate: **"Stack: replace linear layout (translator's language: similar to LinearLayout in Android)"**)

这里翻译有误，应该是和Android中的FrameLayout相似吧？(Google translate: **The translation here is wrong, should it be similar to FrameLayout in Android?**)

**Comment by BskyRui** [comment]
This url was 404 not found! Maybe you can try use English to let other people understand your questions.

**Comment by janmoppel** [comment]
Hello @AndrewXiao !

Thank you for posting an issue.
We've translated this issue's description into English using Google Translate. If you're comfortable writing in English, please check the translation and update it if necessary.

The link you provided, shows the 404 error. Can you please check once again and attach the working link?

Thank you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
