### ISSUE TITLE
FlutterView.onResume does not seem to work

### ISSUE THREAD

**Issue by AsturaPhoenix** [flutter/flutter#4506]
## Steps to Reproduce

In [hello_services](https://github.com/flutter/flutter/tree/master/examples/hello_services) or a similar project, pause an activity by pressing the home key or power button on an Android device.

* If the home key was pressed, resume the app by using recent apps or re-launching the app.
 * Expected: app resumes.
 * Actual: the flutter view is black.
* If the power button was pressed, press it again and unlock the device.
 * Expected: app resumes.
 * Actual: the flutter view looks okay, but does not update visually when it should (i.e. after setState calls).

## Flutter Doctor

    [✓] Flutter (on Linux, channel master)
        • Flutter at /usr/local/google/home/rosswang/flutter
        • Framework revision ffde6777fc (2 hours ago), engine revision 034ae44419

    [✓] Android toolchain - develop for Android devices (Android SDK 23.0.1)
        • Android SDK at /usr/local/google/home/rosswang/Android/Sdk
        • Platform android-23, build-tools 23.0.1
        • OpenJDK Runtime Environment (build 1.8.0-google-v7-122278751-122271652)

    [✓] Atom - a lightweight development environment for Flutter
        • flutter plugin version 0.2.2
        • dartlang plugin version 0.6.21

## Logs and Crash Reports

Please attach any relevent logs or crash reports.

On normal startup:

    06-09 15:19:41.067 21405-21442/com.example.flutter D/mali_winsys: new_window_surface returns 0x3000,  [1440x2196]-format:1
                                                                      
                                                                      [ 06-09 15:19:41.067 21405:21442 D/         ]
                                                                      ro.exynos.dss isEnabled: 0
    06-09 15:19:41.077 21405-21405/com.example.flutter W/art: Attempt to remove non-JNI local reference, dumping thread
    06-09 15:19:41.087 21405-21405/com.example.flutter W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
    06-09 15:19:41.097 21405-21405/com.example.flutter D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
    06-09 15:19:41.117 21405-21405/com.example.flutter I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@cfb16e9 time:731768306

On resume:

    06-09 15:17:40.007 21405-21405/com.example.flutter V/ActivityThread: updateVisibility : ActivityRecord{8e39e9b token=android.os.BinderProxy@1b0b243 {com.example.flutter/com.example.flutter.ExampleActivity}} show : false
    06-09 15:17:45.987 21405-21442/com.example.flutter D/mali_winsys: new_window_surface returns 0x3000,  [1440x2196]-format:1
                                                                      
                                                                      [ 06-09 15:17:45.987 21405:21442 D/         ]
                                                                      ro.exynos.dss isEnabled: 0
    06-09 15:17:45.997 21405-21405/com.example.flutter W/art: Attempt to remove non-JNI local reference, dumping thread
    06-09 15:17:46.007 21405-21450/com.example.flutter D/mali_winsys: new_window_surface returns 0x3000,  [1440x2560]-format:1
    06-09 15:17:46.027 21405-21405/com.example.flutter I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1b0b243 time:731653216

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by AsturaPhoenix** [comment]
This also affects cases where a full-screen activity pre-empts the app, like an account picker or a Google Play permissions request.

**Comment by abarth** [comment]
Thanks for the report.  We'd had several people encounter this issue but we haven't been able to work out a reliable way to reproduce it.  I suspect we're missing some signal from Android to resume drawing the app.

**Comment by collinjackson** [comment]
I have been able to consistently reproduce this.

To get the black screen.

Open the hello_services example. Replace onGetLocation with the following:
```
        String url = "http://www.example.com";
        Intent i = new Intent(Intent.ACTION_VIEW);
        i.setData(Uri.parse(url));
        startActivity(i);
        return "";
```

When you using the back button to return from the browser, the FlutterView is black.

**Comment by collinjackson** [comment]
I also have a repro case for the app looking ok but being "frozen" (not responding to setState calls) when using Google Sign-In. I'm not sure if they're related.
