### ISSUE TITLE
Problems with using IndexedStack and WebViewScaffold

### ISSUE THREAD

**Issue by wooooooak** [flutter/flutter#45061]
## Steps to Reproduce

1. When current selected widget(index 1) is WebView, if I try to switch to another widget(index 0), WebView will not disappear.
2. It seem like Webview is always on top.

![image](https://user-images.githubusercontent.com/18481078/69008325-7a4a9100-098c-11ea-97e7-785baa72f4fb.png)

WebView.dart
```dart
class WebViewPage extends StatefulWidget {
  @override
  _WebViewPageState createState() => _WebViewPageState();
}

class _WebViewPageState extends State<WebViewPage> {

  @override
  void dispose() {
    super.dispose();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: EdgeInsets.only(top: 30, bottom: 30),
        child: WebviewScaffold(
          url: 'https://google.com',
          withJavascript: true,
          hidden: true,
          initialChild: Center(
            child: CircularProgressIndicator(),
          ),
        ),
      ),
    );
  }
}

```

**Target Platform:** Android, iOS
**Target OS version/browser:** All
**Devices:** All

```
```

```
```

```
```

**Comment by janmoppel** [comment]
Hello @wooooooak !

Thank you for posting an issue.
Can you please also attach the `flutter doctor -v` command output?

**Comment by wooooooak** [comment]
@janmoppel 

Here is output.
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale ko-KR)
    • Flutter version 1.9.1+hotfix.6 at /Users/wooooooak/flutter
    • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/wooooooak/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)

**Comment by iapicca** [comment]
Hi @wooooooak 
I noticed that you are using a 3rd party plugin [flutter_webview_plugin](https://pub.dev/packages/flutter_webview_plugin), you may want to open an issue in the dedicatted [github](https://github.com/fluttercommunity/flutter_webview_plugin/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by harshkumarkhatri** [comment]
@wooooooak Have you found a fix for this?

**Comment by wooooooak** [comment]
@harshkumarkhatri no.
