### ISSUE TITLE
[google_sign_in] Weird transparent overlay animation when google sign in button pressed

### ISSUE THREAD

**Issue by opalr** [flutter/flutter#45065]
If you watch the screen on the top right in this video a few seconds in, you will notice that when the google sign in button is pressed, a dark overlay appears on the screen.

https://youtu.be/OlcYP6UXlm8?t=3129

I have the same result on my app when using a google sign in button. Has anyone found a way to fix this?

**Comment by janmoppel** [comment]
Hello @opalr !

Thank you for posting an issue.
Can you please also post the `flutter doctor -v` command output and minimal steps on how to reproduce it?

Thank you.

**Comment by opalr** [comment]
Steps to reproduce:
Clone this repo: https://github.com/tensor-programming/firebase_auth_example_stream
Use command _flutter run_ to open the app. When you press the "sign in with Google" button, you will notice the weird dark transparent overlay appear. It should let you select a google account to sign in with. After selecting the account, the overlay continues with a weird animation as it exits the screen from top to bottom. 

You will see an error in the code at the signInWithGoogle() function but this is not related to the weird animation. It just happens because the firebase account this repo is connected to is not set up correctly due to recent updates to the requirements.

Output of flutter doctor -v:
> [√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
>     • Flutter version 1.9.1+hotfix.6 at E:\Programs\flutter
>     • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at E:\Programs\Android-SDK
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • ANDROID_HOME = E:\Programs\Android-SDK
>     • Java binary at: E:\Programs\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.5)
>     • Android Studio at E:\Programs\Android\Android Studio
>     • Flutter plugin version 41.0.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> 
> [√] Connected device (1 available)
>     • SM G960U • 354130535a483098 • android-arm64 • Android 9 (API 28)
> 
> • No issues found!

**Comment by iapicca** [comment]
Hi @opalr 
are you still experiencing this issue with the latest stable version of flutter?
thank you

**Comment by opalr** [comment]
@iapicca Yes, I have the same issue when using the latest stable version (Flutter 1.12.13+hotfix.5)

**Comment by opalr** [comment]
This is a video of the bug: https://youtu.be/vf9WVvdb5q4

I'm using Flutter 1.12.13+hotfix.8 • channel stable. The dark overlay appears when the code below runs. I'm also attaching my pubspec.yaml, android/build.gradle, and android/app/build.gradle.

**Code Causing Dark Overlay (from google_sign_in-4.1.4/lib/google_sign_in.dart):**
``` 
  /// Starts the interactive sign-in process.
  ///
  /// Returned Future resolves to an instance of [GoogleSignInAccount] for a
  /// successful sign in or `null` in case sign in process was aborted.
  ///
  /// Authentication process is triggered only if there is no currently signed in
  /// user (that is when `currentUser == null`), otherwise this method returns
  /// a Future which resolves to the same user instance.
  ///
  /// Re-authentication can be triggered only after [signOut] or [disconnect].
  Future<GoogleSignInAccount> signIn() {
    final Future<GoogleSignInAccount> result =
        _addMethodCall(GoogleSignInPlatform.instance.signIn, canSkipCall: false);
    bool isCanceled(dynamic error) =>
        error is PlatformException && error.code == kSignInCanceledError;
    return result.catchError((dynamic _) => null, test: isCanceled);
  }

  /// Marks current user as being in the signed out state.
  Future<GoogleSignInAccount> signOut() =>
      _addMethodCall(GoogleSignInPlatform.instance.signOut);

  /// Disconnects the current user from the app and revokes previous
  /// authentication.
  Future<GoogleSignInAccount> disconnect() =>
      _addMethodCall(GoogleSignInPlatform.instance.disconnect);
}
```

**pubspec.yaml:**
```
name: crystal
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.11.0+1
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+2
  google_sign_in: ^4.1.4
  flutter_auth_buttons: ^0.6.0
  http: ^0.12.0+2
  oauth2: ^1.4.0
  flake_uuid: ^0.1.3
  uni_links: ^0.2.0
  url_launcher: ^5.1.2
  cloud_functions: ^0.4.1+6
  webview_flutter: ^0.3.19+8
  provider: ^4.0.4
  syncfusion_flutter_charts: ^17.4.51

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
   - assets/

  fonts:
    - family: product-sans
      fonts:
        - asset: fonts/Product-Sans-Bold.ttf
```

**android/build.gradle:**
```
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'

        classpath 'com.google.gms:google-services:4.3.3'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**android/app/build.gradle:**
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}


android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "tech.crystalco.crystal"
        minSdkVersion 16
        targetSdkVersion 28
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile file(keystoreProperties['storeFile'])
           storePassword keystoreProperties['storePassword']
       }
   }
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    implementation 'com.google.firebase:firebase-auth:19.3.0'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:multidex:1.0.3'
}

apply plugin: 'com.google.gms.google-services'
```

**Comment by kabirnayeem99** [comment]
Experiencing the same issue.

**Comment by iapicca** [comment]
Hi @opalr
testing [google_sign_in](https://pub.dev/packages/google_sign_in) [example app](https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in/example)
with the latest master and `google_sign_in 4.5.1`

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.21.0-6.0.pre.37, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.37 at /Users/nevercode/development/flutter_master
    • Framework revision 35e7005184 (2 days ago), 2020-07-25 09:44:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

the issue seems to me being just a delay of the "sign_in widget" appearance
that expose the grey overlay for longer than desirable

Thank you

**Comment by raveesh08** [comment]
Hi I too faced the issue... but for me it was showing like modal dialog background. 
It seems it's trying to prompt for user to select Gmail accounts and at the same time it's dismissing the dialog automatically... I think it's better if they allow developers to pass progress indicator for Google signin plugin

**Comment by opalr** [comment]
> **The issue was resolved after I set a background color in the new screen.**

Where did you set the background color? I think I misunderstand how you fixed it.

**Comment by hallelk** [comment]
i have the same issue. anything new on this front?

**Comment by joaovperin** [comment]
Facing the same issue... Any news?

**Comment by fcidvidal** [comment]
I have the same issue, has anybody fix it ?

**Comment by rohanjsh** [comment]
Just a call to google services I guess. As far as my app was concerned if the user tries to sign in from the existing account this issue seems to appear.
We can always disable the UI for that matter of time and show a circular progress indicator. 
This worked for me in a production use case. 
Though I hope if someone digs deep into this issue.

**Comment by huycozy** [comment]
I'm checking this issue on the latest plugin version `google_sign_in: ^6.1.0`. Instead of showing an indistinct flickering overlay like OP's video, it shows a grayer background along with a Google sign-in dialog to select an account:

<details>
<summary>Demo video</summary>

https://user-images.githubusercontent.com/104349824/235132990-8b4f0430-0c0d-4af5-a936-f3747ad1851e.mov
</details>

It may appear in a case that I haven't seen anyone mention here. 
@opalr Can you please try on the latest plugin version and confirm if it's fixed?
