### ISSUE TITLE
CupertinoStackPageTranstition support like iOS 13.2 does?

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#45062]
Does there anyway using iOS 13.2 modaling way like this:

![image](https://user-images.githubusercontent.com/21303438/69008681-42d9e580-0988-11ea-9409-d2f54ffb9773.png)

Does it supported already? If so, how to enabel it? if not, any workaround implement this since it's really a nice feature.

**Comment by tb2761** [comment]
#43041 Here is a list of the upcoming widgets for ios. It contains this widget, but in the actual beta or stable version it's not implemented yet.

**Comment by LongCatIsLooong** [comment]
Thanks for reporting this issue! The new presentation style is on our radar and there're multiple open issues for it, including https://github.com/flutter/flutter/issues/42560 and #43041.
