### ISSUE TITLE
Add previews for CupertinoIcons in the API docs like material Icons have

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#45097]
On the material icons there are previews of each icon:

https://api.flutter.dev/flutter/material/Icons-class.html

However the same is not the case for the Cupertino icons:

https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html

I don't know if there's a technical reason for this - it'd be nice to support if possible. In VS Code we use a regex to find these icon previews for Material and swap them out with images that will work there (so you have in-editor previews), but this also fails for Cupertino. If there were previous on the page, we could probably do the same thing there (raised at https://github.com/Dart-Code/Dart-Code/issues/638#issuecomment-555022586).

**Comment by xster** [comment]
There's no good reason. I just haven't made the CSS to break out all the icons into images. We should definitely do this.

**Comment by jmagman** [comment]
A user survey response requested this, and also pointed out that the README at https://github.com/flutter/cupertino_icons doesn't have the constants.

**Comment by guidezpl** [comment]
@xster I'm doing some work around icons at the moment, and we have the font available now, so I could fix this issue. Are you using a script (like `dev/tools/update_icons.dart`) to generate cupertino's `icons.dart`?

**Comment by xster** [comment]
Thanks for looking at it. It's https://github.com/xster/framework7-icons/blob/master/build/generate.py#L71

**Comment by DanTup** [comment]
Awesome! I've added support for this to VS Code for the next version. Thanks!

![Screenshot 2021-01-14 at 12 15 20](https://user-images.githubusercontent.com/1078012/104589722-33286080-5662-11eb-98f5-d85390d3f4de.png)
