### ISSUE TITLE
No images  and print not working on iOS

### ISSUE THREAD

**Issue by losedMemory** [flutter/flutter#45091]
When I use Flutter channel dev , print() not working ,images can be displayed;
But when I use Flutter channel master, images can't be display, print can work
It‘s run on  iOS 13.2.2  iPhone 8 (real device)

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure
you trust this source!
Downloading android-arm-profile/darwin-x64 tools...                14.1s
Downloading android-arm-release/darwin-x64 tools...                15.5s
Downloading android-arm64-profile/darwin-x64 tools...               4.4s
Downloading android-arm64-release/darwin-x64 tools...               9.4s
Downloading android-x64-profile/darwin-x64 tools...                12.4s
Downloading android-x64-release/darwin-x64 tools...                 3.2s
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.12.2, on Mac OS X 10.14.5 18F132, locale
    zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
------------------------------------------------
[✓] Flutter (Channel master, v1.12.3-pre.49, on Mac OS X 10.14.5 18F132, locale
    zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
 I need your help.

**Comment by iapicca** [comment]
Hi @losedMemory 
could you please provide a minimal code sample to reproduce the problem
thank you

https://github.com/flutter/flutter/issues/45032

**Comment by losedMemory** [comment]
sorry,there’s no problem now

> Hi @losedMemory
> could you please provide a minimal code sample to reproduce the problem
> thank you
> 
> #45032

**Comment by iapicca** [comment]
Hi @losedMemory 
I'm glad you found a workaround,
thank you for letting me know
