### ISSUE TITLE
Add `versions.json` and add a g3_release ref to flutter/fuchsia package

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#45099]
Mirror issue for https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=41494, which notes:

As part of rewriting the flutter/dart rollers on fuchsia we need to identify the version that is already rolled into google3. The easiest way to do this is adding a ref tag to the current version on g3.

The fuchsia roller then will read the tag from cipd packages instead of trying to read from google3 or any other source.

Additionally the fuchsia roller needs to know which version of dart and skia should be rolled along the flutter/fuchsia package. The easiest way to do this is to add a versions.json file to the cipd package itself.

/cc @cbracken @iskakaushik

**Comment by godofredoc** [comment]
This is obsolete, we are rolling based on the on the versions.json included with the g3 cipd packages.
