### ISSUE TITLE
Codelab should be formatted with Atom

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4509]
It would be nice if the code was indented using the rules that users are most likely to use.

The codelab appears to be formatted using Flutter's indent rules instead of Atom's autoformat rules. This means the code gets reformatted the first time you save it in Atom, which makes you wonder if you did something wrong when the code shifts all around after you change a comment in the code.

**Comment by sethladd** [comment]
Thanks for the feedback! I would agree that user-facing code like the codelab's code should be formatted with the tools that are readily available to our users.

The Flutter formatting rules apply to the code in the flutter repo, but as far as I understand, those rules are not mandated for a user's app.

**Comment by sethladd** [comment]
@collinjackson @qchong thoughts?

**Comment by abarth** [comment]
I don't think the dartfmt formatting is of sufficient quality for us to use it in code samples.

**Comment by sethladd** [comment]
The user experience is pretty jarring here. When you make a change and Save in Atom, all the code gets reformatted.

We could teach Atom to completely disable "format on save" for all Flutter projects (even if the user has that option enabled)?

**Comment by abarth** [comment]
Is "format on save" enabled by default in Atom?  That's not how Atom behaves for me and I don't believe I've changed this setting.

**Comment by sethladd** [comment]
Discussing this offline, we agree this is a usability issue. The ultimate solution is to have an automated formatter that works with Flutter code. I'm going to close this issue in favor of #2025.

You may want to open an issue with the Atom plugin to control "format on save" on a per-project basis. That way, a user could disable "format on save" for their flutter project, and leave it on for other non-flutter Dart projects. One could even imagine saving that preference into a file that is source-controlled. https://github.com/dart-atom/dartlang/issues

**Comment by devoncarew** [comment]
> Is "format on save" enabled by default in Atom?

No, it's opt-in. Having formatting be controllable on a per-project basis makes sense.

**Comment by sethladd** [comment]
https://github.com/dart-atom/dartlang/issues/798
