### ISSUE TITLE
hot_mode_dev_cycle regression at dart roll fdb9d19826..d6b0a27665

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#45109]
Benchmark measures ~1,200ms before the Dart roll, and ~1,300ms after.

/cc @a-siva @bkonyi

**Comment by tvolkert** [comment]
Started happening at https://github.com/flutter/flutter/commit/35043cbbe39b579587e1671143ed500ee1f0d347

**Comment by bkonyi** [comment]
https://github.com/flutter/engine/pull/13883 contained a change to some hot reload behavior.

**Comment by a-siva** [comment]
The regression is related to this change https://dart-review.googlesource.com/c/sdk/+/123692
which is a correctness change. Previously we had undefined behavior (potentially crashes) when fields that are initialized or have a value that does not conform to the field's static type.

**Comment by tvolkert** [comment]
I've asked @a-siva to see if the correctness change had any room for optimization.  Otherwise, I'll re-baseline the benchmark.

**Comment by a-siva** [comment]
The correctness check iterates over the heap looking for instances and static fields and does a check for each of them, at this point I don't see an optimization path short of disabling the checks.
I would recommend re-baslining the benchmark.

**Comment by jonahwilliams** [comment]
Most hot reloads do not actually modify static fields. If we could communicate this was the case though the incremental dill or similar artifact, then presumably this check could be skipped?

**Comment by Hixie** [comment]
1200ms is WAY more than acceptable for a hot reload... I thought we had it down to the ~200ms range.

**Comment by tvolkert** [comment]
I thought so too, yet the benchmark data is pretty stable going back 2 months.  @jonahwilliams hadn't you gotten hot reload down to blazing fast speeds?  Is this benchmark not accurately reflecting that?

**Comment by jonahwilliams** [comment]
See https://docs.google.com/document/d/18M3NI-I4qE45W0DDwjMGvh4mKu5o6EOQimzcDie5kV8/edit for some discussion a while back.

> hadn't you gotten hot reload down to blazing fast speeds

1 second _is blazing fast_ compared to the 3 seconds this benchmark used to take. You might be thinking of the "Support for hot reload in 150ms" document, but that was specifically about the fastest possible reload using the simulator. The changes there eventually made themselves into the overall hot reload tooling improvements in the document posted above.

> Is this benchmark not accurately reflecting that?

The benchmark is a slow host + slow device. You'll get dramatically different times if you use a fast host + slow device, or fast host + fast device. Hot reload performance has always had extremely wide variance based on host machine speed, filesystem perform, what is invalidated, and connected device performance.

**Comment by jonahwilliams** [comment]
This is also the second regression in the benchmark, the first was the change to move const evaluation into kernel. I don't have a link to the issue from the time.

**Comment by a-siva** [comment]
> Most hot reloads do not actually modify static fields. If we could communicate this was the case though the incremental dill or similar artifact, then presumably this check could be skipped?

True if the front end processed this and indicated that the checks could be skipped it would help. Adding @johnniwinther and @jensjoha for their comments.

**Comment by tvolkert** [comment]
I don't think this should block dev releases given the critical fixes that Fuchsia and Stadia are waiting on, so removing the TODAY label.

**Comment by tvolkert** [comment]
> True if the front end processed this and indicated that the checks could be skipped it would help. Adding @johnniwinther and @jensjoha for their comments.

ping @johnniwinther and @jensjoha

@a-siva can we revert the offending commit in the Dart VM in the meantime, then re-apply with a fix that doesn't regress performance?

**Comment by rmacnak-google** [comment]
This is within the expected range.

**Comment by tvolkert** [comment]
> This is within the expected range.

Only because the metric has been re-baselined after this bug was opened.  It was out of the expected range, which is what caused this issue to be opened. 🙁

**Comment by jonahwilliams** [comment]
FWIW, I've just added a suite of macOS target platform (hot_mode_dev_cycle_macos_target__benchmark) hot reload benchmarks to the suite. Its too late to see how the change affected them, but in the future it should give us more insight into setups with different performance characteristics.

**Comment by rmacnak-google** [comment]
At 100ms regression is within the expected range of effects of the change, which is required for correctness.

**Comment by jensjoha** [comment]
> > Most hot reloads do not actually modify static fields. If we could communicate this was the case though the incremental dill or similar artifact, then presumably this check could be skipped?
> 
> True if the front end processed this and indicated that the checks could be skipped it would help. Adding @johnniwinther and @jensjoha for their comments.

We don't really have any such information available.
