### ISSUE TITLE
Enable device observatory discovery on Fuchsia 

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#45103]
/cc @iskakaushik, @jkurtw, @chingjun @gw280, @blasten.

**Comment by jonahwilliams** [comment]
As far as I know, this already works with code that myself and @zanderso wrote last year. Can you describe in more details what this issue is about, or link to another bug?

**Comment by blasten** [comment]
Indeed, https://github.com/flutter/flutter/pull/48472 is testing this flow. Can we close this bug?

**Comment by kf6gpe** [comment]
Definitely. Closing.
