### ISSUE TITLE
Reify Fuchsia build modes with our build types 

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#45106]
Fucsia defines build modes as ([AOT,JIT] x [release/debug/profile]; Flutter has only release/debug/profile. Need to determine which we support and why.

/cc @iskakaushik, @jkurtw, @chingjun @gw280, @blasten.

**Comment by jonahwilliams** [comment]
debug = jit debug
profile = aot release
release = aot release
release_jit =  jit release (already exists for x86)
profile_jit = jit profile (does not exist)

**Comment by kf6gpe** [comment]
cc @iskakaushik @a-siva What's been done here recently? Have a question from a Googler on status. Thanks!
