### ISSUE TITLE
Unhealthy Catalina bot caused start_up_time regression

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#45112]
![6A1PYnxBbUs](https://user-images.githubusercontent.com/15253456/69079637-4d7b9580-09ef-11ea-9b83-5f5f3200faee.png)

It looks like this may not be tied to a particular commit, but rather hardware issues in the lab...

/cc @keyonghan (onduty for devicelab)

**Comment by tvolkert** [comment]
Reasons I think this might be a bot issue are (a) non-Catalina iOS start up times haven't regressed, and (b) the spikes in the numbers indicate flakiness in the benchmark.

**Comment by godofredoc** [comment]
@tvolkert do you know if that benchmark is including the time to download artifacts from the internet?

**Comment by tvolkert** [comment]
No, it doesn't - the test run is here:

https://github.com/flutter/flutter/blob/81f6ba84b9449ecd3ecdab8b6ab1c6aaba151b48/dev/devicelab/lib/tasks/perf_tests.dart#L75-L79

Which uses the `StartupTest` task, which in turn gets its data from the `start_up_info.json` file:

https://github.com/flutter/flutter/blob/81f6ba84b9449ecd3ecdab8b6ab1c6aaba151b48/dev/devicelab/lib/tasks/perf_tests.dart#L158-L165

That file is obtained from the Dart VM service, which only starts gathering data once the VM is started.

**Comment by keyonghan** [comment]
Restarted both agent and device. Not values went back to normal in latest commit.

**Comment by tvolkert** [comment]
Great!  I'm removing the TODAY label, but keeping this issue open because we should have a health status check that would have detected whatever was causing this on the bot side.

**Comment by godofredoc** [comment]
This is caused by "idevicesyslog" and "usbmuxd -launchd" keeping a lot of files open and consuming memory and cpu resources.

A workaround is to find out the processes for "idevicesyslog" and "usbmuxd" and kill the processes.

**Comment by godofredoc** [comment]
@tvolkert @Hixie @jonahwilliams who is the correct person to look at this? seems like it takes ~15 days for the benchmarks to start failing, if this is not a problem from the product point of view we can start killing the processes regularly from infra.

**Comment by tvolkert** [comment]
So is the issue that the Flutter tool spawns `idevicesyslog` processes that stay resident after the tool exits?  I didn't think the tool spawned any `usbmuxd` processes, but maybe I'm wrong...

If that's the case (we know that we spawned them), then we could explicitly kill those processes when the tool exits.

/cc @zanderso

**Comment by zanderso** [comment]
The tool does try to kill `idevicesyslog` here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/devices.dart#L665, but maybe it needs to send something more forceful than the default SIGTERM.

`usbmuxd` should also be killed here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/devices.dart#L479, but may have the same issue.

It looks like we fail to call `dispose()` on the `Device` when the resident runner is in benchmark mode, when the tool is killed by a signal, and when we throw a tool exit. If the child processes aren't automatically cleaned up on Catalina when the parent tool process exits in one of these cases, then the child processes could be leaked.

**Comment by digiter** [comment]
Triage: looks normal for the past few weeks.
