### ISSUE TITLE
iOS App Store submission rejection - Non-public API usage of _kCTFontOpticalSizeAttribute in Skia

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#45129]
Flutter placeholder issue for underlying bug in Skia -- https://bugs.chromium.org/p/skia/issues/detail?id=9657

> ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/Flutter.framework/Flutter: _kCTFontOpticalSizeAttribute.

**Comment by tvolkert** [comment]
@bungeman @reed-at-google -- this is blocking Flutter releases and internal Google customers -- we're hoping for a revert ASAP.

**Comment by jmagman** [comment]
Added to the [Bad Build wiki page](https://github.com/flutter/flutter/wiki/Bad-Builds#v1123---present).

**Comment by timsneath** [comment]
For anyone outside of Google hitting this, the workaround is to switch to an older build, such as those currently in dev, beta or stable channels. We [don't recommend publishing apps based on the master build](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels), since it has only been through basic testing.

**Comment by jmagman** [comment]
Introduced in dev channel build v1.12.3.  Downgrading to v1.12.2 or using the beta channel should work.

**Comment by elliott-io** [comment]
I have to be honest, these sorts of issues are really making me regret using Flutter. There are fixes on the master channel for Google Signin integration, but then there are also huge bugs on master like this where I can't submit my code to Apple. 

Dev channel v1.12.4, I can no longer build for iOS. Reverting to dev 1.12.2 and building gives a different error. 

Any time I would have gained building a single, cross-platform UI over the past 2 months has been lost (many times over) to compatibility issues and bugs like this. Every update seems to break something. It's really frustrating.

Any suggestions?

**Comment by tvolkert** [comment]
Elliott commented (since deleted):

> Dev channel v1.12.4, I can no longer build for iOS. Reverting to dev 1.12.2 and building gives a different error.

Elliott, if you're watching this bug, can you point me to the associated issues?  I want to make sure that they're on the radar for the next stable release.

Regarding your broader point about there being different issues on every channel, our current [release process](https://github.com/flutter/flutter/wiki/Release-process) is basically: (1) roll continually from master to dev, thus creating a series of candidates for beta, (2) ~once a month, pick the best (least bad) of those candidates to promote to beta, and (3) ~once a quarter, pick the best (least bad) beta build to promote to stable.  The project has outgrown this process, and we're actively working to switch to a process that better matches our project's maturity.  I sympathize with your pain, and I apologize for the inconvenience -- just know we're working to make it better.

**Comment by tvolkert** [comment]
Fixed upstream in Skia by https://skia.googlesource.com/skia/+/e678b79c489dcc98ce64643d2791c7f5b5835379

**Comment by tvolkert** [comment]
Fix has rolled into flutter/engine in https://github.com/flutter/engine/commit/2d35b4ec1f04f19d801f94bc694a553214bf003a.

Next up: rolling into flutter/flutter

**Comment by tvolkert** [comment]
The fix is now on master (as of https://github.com/flutter/flutter/commit/868578b150763f962f8270c0c51ac5d866596457), so marking this as fixed.  It should be on the dev channel in the next day or so.

**Comment by EliasDeuss** [comment]
@tvolkert This is still going on in the master branch.

**Comment by EliasDeuss** [comment]
```
Dear Developer,

We identified one or more issues with a recent delivery for your app, "Runner" 0.0.1 (9). Please correct the following issues, then upload again.

ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/Flutter.framework/Flutter: _kCTFontOpticalSizeAttribute. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.12.12-pre.3, on Mac OS X 10.15.1 19B88, locale en-US)
```

**Comment by chinmaygarde** [comment]
I verified that the symbol is not being used by the Flutter engine. Currently, the master branch is on [980f14e](http://github.com/flutter/flutter/tree/980f14e0c5c4979de63d1b1f568ed536706de2ad) which points to the engine at [b6b54f](https://github.com/flutter/engine/tree/b6b54fd60631a3828c2e2c9b079b5d1d2d8c8c37) which points to Skia at [c3ff97a](https://github.com/google/skia/tree/c3ff97a98b74554854b5822797c6b7b431f4d8d2) and the [translation unit in Skia](https://github.com/google/skia/blob/c3ff97a98b74554854b5822797c6b7b431f4d8d2/src/ports/SkFontHost_mac.cpp) that previously referenced the private symbol no longer does so.

For good measure, I downloaded the Flutter engine for iOS and attempted to look for that in symbol in the list of referenced symbols via `nm -u ./bin/cache/artifacts/engine/ios-release/Flutter.framework/Flutter` and [could not find that symbol](https://gist.github.com/chinmaygarde/dd179bb260bfe39aa180fc4d10ab3719) in the list.

What Git revision are you on (`git rev-parse HEAD `)? Did you build your Flutter application anew after checking out that revision? Can you try the `nm` invocation and see if that symbol appears in list dumped?

**Comment by dnfield** [comment]
@EliasDeuss you are on what should be a good commit. `v1.12.12-pre.3` is engine hash `b6b54fd606`, framework hash 980f14e0c5.  

Can you verify that a _clean_ build of your app is bad?  Also, in the future, can you include the output of `flutter doctor -v`?

**Comment by chinmaygarde** [comment]
> Can you verify that a clean build of your app is bad?

I thought the tooling did an implicit clean build when the artifacts changed. Is that not the case or do you suspect a bug in that? If there is a bug with previous build artifacts surviving in the presence of newer variants, we can confirm that by getting the list of symbols from the `Flutter.framework/Flutter` binary in the packaged application bundle instead of looking for the same in the `./bin/cache/artifacts` directory.

**Comment by dnfield** [comment]
There are a lot of things that could have gone wrong.  App didn't get rebuilt after updating artifacts, user selected older build of app even though app was rebuilt, some bug in the tooling failed to recognize build was dirty and failed to rebuild, rebuild failed completely but user selected old asset...

**Comment by dnfield** [comment]
Going to re-open this while we verify.  Will try to reproduce locally as well.

**Comment by dnfield** [comment]
We've submitted an app to TestFlight from Master to see if it is getting this error.  I'm reasonably confident the app we submitted does not use this symbol.  Will update this bug again when we get the reply from Apple.

**Comment by dnfield** [comment]
Verified with this is not happening on master.

@EliasDeuss let us know if this is still happening with a clean build.
