### ISSUE TITLE
Gallery: State Flutter's status and link to our website

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4512]
We should state the status Flutter is in (tech preview) in the Gallery app, as well as link to our website (triggering an intent to open a browser?).

This way, if someone builds and deploys the gallery, users that stumble across it will know what they are looking at.

One idea is to add this info to the drawer of the Gallery.

"Flutter is an early-stage, open-source project to help developers build high-performance, high-fidelity, mobile apps for iOS and Android from a single codebase. This gallery is a preview of Flutter's many widgets, behaviors, animations, layouts, and more. Learn more about Flutter at https://flutter.io. To see the source code for this app, please visit https://github.com/flutter/flutter/tree/master/examples/flutter_gallery"

**Comment by sethladd** [comment]
cc @mpcomplete @HansMuller

**Comment by sethladd** [comment]
cc @tvolkert who is waiting for this :)

**Comment by tvolkert** [comment]
Add an "about" dialog to the pull-out drawer?

**Comment by Hixie** [comment]
I'm working on the about dialog.

**Comment by Hixie** [comment]
This could also address https://github.com/flutter/flutter/issues/4584

**Comment by HansMuller** [comment]
I agree. Will plug this hole today :-)

**Comment by chinmaygarde** [comment]
@HansMuller: Ping. An example of connecting to the URI launcher https://gist.github.com/chinmaygarde/d778498418e30825d687147b79d070eb.
