### ISSUE TITLE
Engine should still notify framework to draw frame if frame is scheduled when lifecycle state paused

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#45131]
Framework might call [scheduleForcedFrame](https://github.com/flutter/flutter/blob/7e1920b81779429789aefccd4ccb0d7f3ccbf510/packages/flutter/lib/src/scheduler/binding.dart#L802) when the engine is in pause or detached state. In this case, engine will drop the schedule frame request without calling back framework to draw the rendering tree. This become problematic because framework is waiting frame to be scheduled and blocking any future schedule frame which results in no future frame will ever be drawn.

One use case is rotating screen when app is in the background. Framework will like to update the rendering tree before the app is actually brought into the front.

Currently, we work around this issue by adding a check in scheduleforcedframe to abort if the frame is not enabled which makes it essentially the same as scheduleframe.

**Comment by chunhtai** [comment]
cc @cbracken @xster

**Comment by xster** [comment]
The technical change described was to stop letting engine stop the animator when snooping on the lifecycle channel. Instead, the frame scheduling should be controlled from the framework side via SchedulerBinding.handleAppLifecycleStateChanged. 

Rather, the engine should stop outgoing frames from the framework side from turning into GPU instructions when the app is in the background rather than stopping incoming frames from being scheduled. 

Discussed between @chunhtai, @Hixie, @gaaclarke, @cbracken

**Comment by gaaclarke** [comment]
As part of https://github.com/flutter/engine/pull/13908 I'm introducing a thread-safe way to determine if you are currently backgrounded.  We could use that same mechanism to prevent something like [Shell::OnAnimatorDraw](https://github.com/gaaclarke/engine/blob/a5680f9388ebcef6012c446c5226a79a5ab8000c/shell/common/shell.cc#L898:L898) or Rasterizer::Draw from executing when we are backgrounded.

**Comment by tvolkert** [comment]
@gaaclarke @chunhtai did flutter/engine#13908 unblock work on this?

**Comment by gaaclarke** [comment]
I think so.  I'd like to chat with @chunhtai to make sure we get the right fix when they become available.  Can you ping me when you get back?

**Comment by Hixie** [comment]
This should simplify the engine, right? It just removes all the logic in the engine regarding whether it's a good time to schedule a frame or not, and lets the framework be entirely in charge of that problem. (The framework is already doing that work.)

**Comment by chunhtai** [comment]
It has been a while, but I'm back @gaaclarke  :)

**Comment by ColdPaleLight** [comment]
> As part of [flutter/engine#13908](https://github.com/flutter/engine/pull/13908) I'm introducing a thread-safe way to determine if you are currently backgrounded. We could use that same mechanism to prevent something like [Shell::OnAnimatorDraw](https://github.com/gaaclarke/engine/blob/a5680f9388ebcef6012c446c5226a79a5ab8000c/shell/common/shell.cc#L898:L898) or Rasterizer::Draw from executing when we are backgrounded.

We are already doing this work in https://github.com/flutter/engine/pull/28383

**Comment by ColdPaleLight** [comment]
I think it makes sense to simplify frame scheduling at the engine. In addition to removing logic in `Engine::HandleLifecyclePlatformMessage`, we also need to remove the control logic for Animator in `Engine::OnOutputSurfaceCreated` and `Engine::OnOutputSurfaceDestroyed`. I filed a PR to try do this https://github.com/flutter/engine/pull/30969

**Comment by ColdPaleLight** [comment]
fixed by https://github.com/flutter/engine/pull/30969
