### ISSUE TITLE
Desktop application is using a random locale.

### ISSUE THREAD

**Issue by rami-a** [flutter/flutter#45152]
## Steps to Reproduce
* Application is utilizing i18n with support for a variety of locales
* Build and launch application for macOS
* Observe incorrect locale is being used.
  * It was immediately obvious from the tooltip for a back button

**Target Platform:** macOS
**Target OS version/browser:** 10.14.6
**Devices:** Macbook Pro

## Logs

```
[✓] Flutter (Channel master, v1.11.1-pre.49, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.11.1-pre.49 at /Users/*/Development/flutter
    • Framework revision c90d64b619 (5 days ago), 2019-11-14 01:16:17 -0500
    • Engine revision 7c2a4ec97f
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/*/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-stable, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (4 available)
    • iPhone 11 Pro • E2273D43-1E56-4FB7-9C72-873055388DE9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
    • macOS         • macOS                                • darwin-x64     • Mac OS X 10.14.6 18G87
    • Chrome        • chrome                               • web-javascript • Google Chrome 78.0.3904.108
    • Web Server    • web-server                           • web-javascript • Flutter Tools
```

**Comment by rami-a** [comment]
cc @stuartmorgan

**Comment by stuartmorgan** [comment]
We're not calling the (new?) API to set the locale in any of the desktop embeddings currently.

**Comment by rami-a** [comment]
Appears to not be a "random" locale, but instead the first one listed in our `supportedLocales` list

**Comment by aliyazdi75** [comment]
@stuartmorgan I have same issue https://github.com/flutter/flutter/issues/52403 on linux but it returns null.

**Comment by stuartmorgan** [comment]
This is already marked as an issue for all three desktop platforms. None are passing locale information.

**Comment by aliyazdi75** [comment]
Sorry, I've just wanted to mention issue here.

**Comment by HidenoriMatsubayashi** [comment]
Has there been any progress?

I don't know if there is ways that can detect the dynamic locale setting change in each desktops (Linux/Windows/macOS), but I think that it is relatively easy to set the locale once when launch the app.

If there is no problem with the implementation that sets default locale setting at starting an app, I could support this issue.

**Comment by stuartmorgan** [comment]
> If there is no problem with the implementation that sets default locale setting at starting an app, I could support this issue.

Starting with just setting it on launch is fine. For systems where we get notifications about changes, we can add that later; it would leverage the code written for setting it at launch.

**Comment by stuartmorgan** [comment]
All three desktop embeddings are sending initial locale information now.
