### ISSUE TITLE
in_app_purchase works with gradle 6, fails on gradle 5 with  Task :in_app_purchase:javaPreCompileDebug FAILED

### ISSUE THREAD

**Issue by rgisi** [flutter/flutter#45167]
Hi everybody. 
This issue is (probably) solved for me, but I thougt you should know (and maybe write it into some guideline somewhere):

When I tried compiling using gradle 5.4.1 (or 5.1.1, same story), compilation in debug or release mode gave me the following error: 
```
> Task :in_app_purchase:javaPreCompileDebug FAILED
[...]
<warning about breaking builds without AndroidX compatibility>
[...]
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
[...]
```

Everything seems to be working fine with gradle 6.0.1 after setting:
```distributionUrl = https\://services.gradle.org/distributions/gradle-6.0.1-all.zip```
in the gradle-wrapper.properties file.

Not sure if you know about this - I didn't, and had quite a bit of work figuring it out.
Hope this helps somebody else. ;-)

**Comment by iapicca** [comment]
Hi @rgisi 
thank you for your contribution

**Comment by blasten** [comment]
This is controlled in the app, and Flutter now defaults to `6.7`, so this can probably be closed.
