### ISSUE TITLE
Webview_flutter File Download not working

### ISSUE THREAD

**Issue by premy** [flutter/flutter#45163]
File download not working in Webview_flutter (from Flutter Team). In fact, also not working in webview plugin (from the flutter community).
What should we do to implement this funcionality?

**Comment by iapicca** [comment]
Hi @premy 
this is the [webview_flutter](https://pub.dev/packages/webview_flutter) first party plugin,
could you please provide your updated  `flutter doctor -v`
and a minimal code sample to reproduce the problem?
Thank you

**Comment by walsha2** [comment]
@iapicca `webview_flutter` has the same issue. As described here: https://github.com/flutter/flutter/issues/39321

I believe this issue is a duplicate, but in general this is a needed capability and is currently not present.

**Comment by iapicca** [comment]
Hi @premy 
as @walsha2 pointed out (thank you)
there's an open issue addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
