### ISSUE TITLE
[web] Blank Page, No Errors

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#45176]
## Problem

I am trying to run my Flutter app using `flutter run -d chrome`, however, neither that nor `flutter run -d chrome --release` or `flutter build web` produce any visible output for me, i.e. I only see a **blank page** in Chrome.

### `flutter run -d chrome`

`flutter run -d chrome -v` produces [this output (only including the end of the logs because the build process looks just fine)](https://gist.github.com/creativecreatorormaybenot/f73d69740dd600a5e4d1d9ca79c63a9c) in the logs.

### `flutter run --release -d chrome`

The error lead me to https://github.com/flutter/flutter/issues/40151, but running `flutter run --release -d chrome` also just shows a blank page in Chrome and [this is the log](https://gist.github.com/creativecreatorormaybenot/8072054dc128d06a1df8934c6321569a).

The only error I can see is in the Chrome developer console:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:53975/favicon.ico
```

## Other

As I mentioned at the beginning, I also tried `flutter build web` and running the `index.html` file generated by that and that produces a blank page as well. I can, however, see errors in the Chrome console:

```
Access to XMLHttpRequest at '~/build/web/assets/FontManifest.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
avv @ html_dart2js.dart:17408
async_patch.dart:694 Uncaught Failed to load asset at "assets/FontManifest.json" (0)
    at Object.f (~/build/web/main.dart.js:1841:3)
    at ~/build/web/main.dart.js:20082:15
    at ahs.a (~/build/web/main.dart.js:2854:71)
    at ahs.$2 (~/build/web/main.dart.js:25697:23)
    at agQ.$2 (~/build/web/main.dart.js:25692:25)
    at adN.a8v (~/build/web/main.dart.js:26602:44)
    at adN.a8u (~/build/web/main.dart.js:26604:33)
    at oT.a4S (~/build/web/main.dart.js:25870:46)
    at a9E.$0 (~/build/web/main.dart.js:26009:7)
    at Object.oU (~/build/web/main.dart.js:2969:82)
main.dart.js:31178 Uncaught TypeError: Cannot read property '$3' of null
    at Pm.qa (main.dart.js:31178)
    at SP.Fr (keyboard.dart:86)
    at SQ.$1 (keyboard.dart:42)
    at aCk (js_helper.dart:2017)
    at js_helper.dart:2049
main.dart.js:31178 Uncaught TypeError: Cannot read property '$3' of null
    at Pm.qa (main.dart.js:31178)
    at SP.Fr (keyboard.dart:86)
    at SR.$1 (keyboard.dart:47)
    at aCk (js_helper.dart:2017)
    at js_helper.dart:2049
```

---

How can I further debug this?

**Comment by jonahwilliams** [comment]
How are you running `flutter build web`? You should be able to spin up a local web server with something like `python -m SimpleHTTPServer` in the build/web directory. Opening the file directly won't work.

Is there anything unusual about your project? Or does this reproduce for you on the `flutter create` example?

Also, please include `flutter doctor -v`

**Comment by creativecreatorormaybenot** [comment]
@jonahwilliams Right, I forgot `flutter doctor -v`. I will also try on the example.

### `flutter doctor -v`

```
[√] Flutter (Channel master, v1.12.4-pre.8, on Microsoft Windows [Version 10], locale en-US)
    • Flutter version 1.12.4-pre.8 at flutterRoot
    • Framework revision 439d798712 (22 hours ago), 2019-11-18 11:33:42 -0800
    • Engine revision 5fb7eb753b
    • Dart version 2.7.0

[√] Chrome - develop for the web
    • Chrome at chromeRoot

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools
```

### `flutter create`

The reason I did not include this initially is because I want to get Flutter Web working for the project I have and was asking for further debugging options because of this.

The project created by `flutter create` runs fine - as well - and is not blank. It shows the example app.

**Comment by jonahwilliams** [comment]
You could try switching to the experimental compiler. It might be able to give you a better error message if there is a compilation issue:

`flutter config --enable-web-incremental-compiler`

And then `flutter run -d chrome` as normal.

**Comment by creativecreatorormaybenot** [comment]
@jonahwilliams I tried running the incremental compiler, but there is a file system error. I was not able to find anything on it:

```
FileSystemException(uri=flutter%5Cbin%5Ccache%5Cflutter_web_sdk%5Ckernel%5Cflutter_ddc_sdk.dill; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      ProcessedOptions.loadSdkSummaryBytes (package:front_end/src/base/processed_options.dart:146:43)
#2      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:175:52)
<asynchronous suspension>
#3      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#4      new Future.sync (dart:async/future.dart:224:31)
#5      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1465:12)
#10     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#11     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:151:20)
#12     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:58:46)
#13     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:428:59)
```

**Comment by jonahwilliams** [comment]
Okay, I'll have to take a look at that later. Does this issue reproduce on the example app if you add your pubspec.yaml contents? Or could you put together a separate example that reproduces the issue?

**Comment by creativecreatorormaybenot** [comment]
@jonahwilliams 

## Example App

The incremental compiler has the error everywhere.

I tried incrementally copying the contents of my `pubspec.yaml` to the example app to see at what point I would see a blank page and this is the result:  
I remembered that I am executing a lot of logic before even calling `runApp` in my `main.dart` and I decided to try to see what happens when I remove that code and try to add it back incrementally: suprise 🎉 it worked (I got an `UnimplementedError` from plugins, but that is what I should be expecting I guess) and it was correctly displayed in Chrome 🙌 

The killer was awaiting `SharedPreferences` before `runApp`. 

### Not seeing errors before `runApp`

I think this issue is obsolete as I will now be able to try and fix everything broken in my app in web with actual error reporting 👍   
I found https://github.com/flutter/flutter/issues/41878 and https://github.com/flutter/flutter/issues/41671 - this issue is a duplicate now.
