### ISSUE TITLE
Better way to deal with the status bar

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#4518]
If you don't want your content to be drawn under the status bar, you have to manually add padding to all your widgets to leave empty space there. It ends up looking like:

```
final double statusBarHeight = MediaQuery.of(context).padding.top;
return new Padding(
      padding: new EdgeInsets.only(top: statusBarHeight),
      child: content
);
```

This is a tedious, especially if you have multiple routes. It would be nice if the framework had an option for automatically reserving space for the status bar for you. Barring that, a widget that knows the status bar height would be good, e.g.:

```
return new SkipStatusBar(child: content);
```

**Comment by Hixie** [comment]
The scaffold should take care of this for you already.

**Comment by Hixie** [comment]
Closing since Scaffold does this as far as I can tell.

**Comment by TheMarsGuy** [comment]
How does the Scaffold achieve this? Is there something we have to do with Scaffold to achieve it.

I have content inside the body of scaffold, but it still appears underneath the status bar. What am I missing?

Thanks.

**Comment by pavel-ismailov** [comment]
You need use `AppBar` to make `Scaffold` take care about it. Without `AppBar` it's working.
If you are using `AppBar` - you can use `primary` parameter to control it. 

That will be UNDER status bar
```
return new Scaffold(
    primary: true,
    appBar: new AppBar(),
);
```

That will be UNDER status bar also (because `primary = true` by default)
```
return new Scaffold(
    appBar: new AppBar(),
);
```

That will be OVERLAY status bar
```
return new Scaffold(
    primary: false,
    appBar: new AppBar(),
);
```

That will be OVERLAY status bar also (because `primary` not works without AppBar)
```
return new Scaffold(
    primary: true / false,
    body: ...,
);
```

**Comment by mkieres** [comment]
I might be wrong, but I think that for what you're trying to achieve the `SafeArea` widget would work best. As per the [docs](https://docs.flutter.io/flutter/widgets/SafeArea-class.html):

> For example, this will indent the child by enough to avoid the status bar at the top of the screen.
>
> It will also indent the child by the amount necessary to avoid The Notch on the iPhone X, or other similar creative physical features of the display.

As an example, you could refer to the flutter gallery app. Flutter guys are using it on the [home page](https://github.com/flutter/flutter/blob/87351bd9583682146675e5c17eb6fee19bf42d85/examples/flutter_gallery/lib/gallery/home.dart#L330)

**Comment by Abgaryan** [comment]
also, you could set empty AppBar as  

```
return new Scaffold(
    primary: false,
    appBar:  EmptyAppBar (),
    body: ...
);
```

```
class  EmptyAppBar  extends StatelessWidget implements PreferredSizeWidget {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
  @override
  Size get preferredSize => Size(0.0,0.0);
}```

**Comment by ch-muhammad-adil** [comment]
@Abgaryan Solution is working great. I have came across with a scenario where i wanted to draw content under status bar. 

<img width="416" alt="screenshot 2018-12-15 at 1 57 19 pm" src="https://user-images.githubusercontent.com/8264639/50041114-5cd0c100-0071-11e9-95d5-1d4fc99b3db0.png">

**Comment by mbikt** [comment]
@Abgaryan solution is great, but to restore status bar color, as follow

```
class EmptyAppBar  extends StatelessWidget implements PreferredSizeWidget {
  static const double _defaultElevation = 4.0;
  @override
  Widget build(BuildContext context) {
    final ThemeData themeData = Theme.of(context);
    final AppBarTheme appBarTheme = AppBarTheme.of(context);
    final Brightness brightness = appBarTheme.brightness
        ?? themeData.primaryColorBrightness;
    final SystemUiOverlayStyle overlayStyle = brightness == Brightness.dark
        ? SystemUiOverlayStyle.light
        : SystemUiOverlayStyle.dark;

    return Semantics(
      container: true,
      child: AnnotatedRegion<SystemUiOverlayStyle>(
        value: overlayStyle,
        child: Material(
          color: appBarTheme.color
              ?? themeData.primaryColor,
          elevation: appBarTheme.elevation
              ?? _defaultElevation,
          child: Semantics(
            explicitChildNodes: true,
            child: Container(),
          ),
        ),
      ),
    );
  }
  @override
  Size get preferredSize => Size(0.0,0.0);
}
```
