### ISSUE TITLE
Plugins shouldn't set their own gradle-wrapper.properties

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#45185]
This file is only used once per build. I'm not completely sure what happens when a plugin sets their own, but I think it's probably ignored in favor of whatever is set in the host app. 

Just to be clear a file like this in `example/android/gradle` is expected since that's controlling the example app, it's files in `android/gradle` that are likely ignored.

At a glance it looks like these are the plugins with this issue:

- [ ] in_app_purchase
- [ ] shared_preferences
- [ ] video_player
- [ ] flutter_plugin_android_lifecycle

/cc @kroikie @blasten

**Comment by blasten** [comment]
This is required for running `flutter build aar` on a plugin. We don't build aar this way yet, but if we want in future, then we will need this file.

**Comment by mklim** [comment]
@blasten that logically makes sense to me but I'm not seeing that behavior. I tried spot checking `flutter build apk` with `--config-build-plugin-as-aar` in a plugin that doesn't have this now (connectivity) and it appeared to work fine.

**Comment by blasten** [comment]
It doesn't call `build aar`.  The tool uses the app's Gradle wrapper and then it executes the `./gradlew` command on the plugin directly from the flutter `build apk` invocation.

**Comment by mklim** [comment]
Ah, okay. Thanks for the clarification.

Should we be tracking trying to get the plugins AAR compatible in general? I tried testing this with a plugin that should be "working" and had to copy over a `local/properties` first, and then the build started failing because it couldn't find an `'assembleAarProfile'` task in the root project. Not sure what to do there so I left it. Is that something we should be actively supporting?

**Comment by ened** [comment]
@blasten is `flutter build aar` meant as a way for developers to create artifacts that can be uploaded to maven repositories, for example?

If so, could that `flutter build aar` task create the required wrapper & grade files on demand then? We could add those generated build files to the default .gitignore even.

I’m saying this because most people will probably refer to flutter plugins via pub?

**Comment by kroikie** [comment]
Having the `gradle.properties` in the plugin risks having different versions of gradle defined for the plugin and the app which can cause build failures if non common gradle features are used between the plugin and the app.

**Comment by iapicca** [comment]
please consider that `gradlew` in `.gitignore` 
often results is version inconsistency when building w/ CI/CD
[example](https://docs.codemagic.io/troubleshooting/common-issues/#version-inconsistency-between-local-and-codemagic)

**Comment by bartekpacia** [comment]
So, 3 years later, what's the _official way_ to deal with `gradle-wrapper.properties` 😃? 

I see that some older plugins have `android/gradle/gradle-wrapper.properties` directory, but when I generated a basic plugin myself (Flutter v3.0.0), that directory was not present.

**Comment by stuartmorgan** [comment]
This has been removed everywhere, closing.
