### ISSUE TITLE
[android] Platform code from transitive plugin dependencies isn't linked into the build

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#45188]
For example: consider plugin `maps` which depends on plugin `network`.  Both plugins contain platform code (e.g. an `android/`) directory.  However, if an app depends on `maps`, the build will fail because `network` isn't visible to  `maps` during the build.  

`.flutter-plugins` will list all the pub transitive dependencies, however these aren't surfaced via Gradle since the app project will depend on each of these plugins directly.

cc @xster, @amirh.

**Comment by blasten** [comment]
Is this something we want to support though? It means that the platform code has versioning implication.

**Comment by amirh** [comment]
> Is this something we want to support though? It means that the platform code has versioning implication.

Can you elaborate?
