### ISSUE TITLE
Flutter tools incorrectly identified ChromeCast devices as Fuchsia devices and tried to SSH to them

### ISSUE THREAD

**Issue by chingjun** [flutter/flutter#45191]
Internal bug: b/144765202

**Comment by zanderso** [comment]
The Flutter tool delegates to the Fuchsia SDK's dev_finder for device identification, so the fix for this might need to be in dev_finder.

**Comment by zanderso** [comment]
This might also have been addressed by placing Fuchsia support behind a `flutter config` flag. /cc @jonahwilliams to confirm.

**Comment by jonahwilliams** [comment]
From the linked bug it appears that the issue was dev_finder picking up random mDNS not limited to _fuchsia._udp. That has since been fixed, closing
