### ISSUE TITLE
Back button only goes back on top-level navigator

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#452]
If you have nested navigators, the back button should probably navigate the most-recently navigated one, or something. Right now it only controls the outermost one.

Then again, that way lies crazy (q.v. back button and nested iframes on the Web).

**Comment by eseidelGoogle** [comment]
I'm not sure if this is still an issue we need to track @HansMuller?

**Comment by HansMuller** [comment]
I assume that we're referring to the Android system back button. The Scaffold's back button does refer to whatever navigator contains the scaffold.

Android may exit the application if you tap the system back button. So in the nested navigator case tapping the scaffold's back button might do something harmless but in the same situation hitting the system back button will exit the app.  That's probably not ideal.

**Comment by Hixie** [comment]
Closing because we've had no demand for this.
