### ISSUE TITLE
TextTheme constructor should be public (and we should also have a copyWith constructor)

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#4520]
When writing the Pesto app, I needed to specify a whole suite of TextStyles for the app. Currently the only way to do this is to pass a custom TextStyle to every new Text widget. Our DefaultTextStyle widget doesn't help, because it can only change a single style.

Instead, it would be useful to be able to override the Theme's TextTheme with custom TextStyles.

**Comment by Hixie** [comment]
You could just provide your own Inherited widget that stores the styles.

**Comment by mpcomplete** [comment]
Storage is not the issue. It should be easy to substitute a custom set of text styling as part of a theme.

**Comment by Hixie** [comment]
Oh are you basically just saying you want to be able to provide TextTheme objects other than the black and white versions?

**Comment by mpcomplete** [comment]
Right. (And a TextTheme.copyWith() constructor to replace styles piecemeal would help too.)

**Comment by Hixie** [comment]
Aaaah. Yeah, we should totally support that. That should be easy.

**Comment by HansMuller** [comment]
I think it would be worth thinking about how we expose TextStyles via inherited widgets in general. For example the style for tab labels is essentially `Theme.of(context).primaryTextTheme.body2`. The style for button labels is `ButtonTheme.of(context).textTheme`. The style for the first line in a list item is `Theme.of(context).primaryTextTheme.subhead`.  The style used by Text objects is the value of `DefaultTextStyle.of(context).style. This is all apt to be somewhat confusing for someone who wants to override the color or some aspect of the font for all or a subset of the text in their application.

The fact that a text style color override should reflect the theme's overall lightness or darkness complicates matters further.

**Comment by Hixie** [comment]
This is done now.
