### ISSUE TITLE
Provide host binaries for arm64 devices

### ISSUE THREAD

**Issue by snoberyman** [flutter/flutter#45216]
I want to develop flutter apps on my Chromebook with arm64 processor. But I am having a problem when installing the latest flutter sdk Linux version.
The error is: `can not execute binary file: exec format error` so apparently the sdk version is x86-64 and not for arm architecture.

So is there a version for arm64? How to install flutter sdk on Linux with arm64? Am I missing something here?

**Comment by thomasmarkiewicz** [comment]
I would love to do the same on a PineBook Pro

**Comment by jonahwilliams** [comment]
We do not currently provide tool binaries for arm64 host systems

**Comment by christopherfujino** [comment]
This should be supported now. We don't upload prebuilt archives to the website, but if you clone the repo from linux arm64 and then run the `./flutter/bin/flutter` script, it should download the necessary binaries.
