### ISSUE TITLE
Issue from website page Flutter文档

### ISSUE THREAD

**Issue by DaquanZhou** [flutter/flutter#45219]
From URL: https://www.flutterchina.club/docs.md

> 您好, 我按照官方集成到原生 iOS 项目中, 可以用真机正常跑起来, 但是 archive 确报错? 在文档中并没有看到相关集成到原生 iOS 项目的打包文档. 希望能指点一下! 项目急着上线!

Hello, I am officially integrated into the native iOS project, you can run it with the real machine, but the archive does report an error? The package does not see the packaged documentation integrated into the native iOS project. Hope to give pointers! On the line!

**Comment by DaquanZhou** [comment]
Hello, I integrate into the native iOS project according to the official document, and can run normally with the real machine, but the archive does report an error? I don't see the package document related to the native iOS project in the document. I hope you can help me ! Thanks!

**Comment by iapicca** [comment]
Hi @DaquanZhou 
could you please provide your updated  `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Hi @DaquanZhou 
I'm not sure to understand your question, 
are you looking for this [documentation](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps)?
thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
