### ISSUE TITLE
Review project setup page for iOS add-to-app

### ISSUE THREAD

**Issue by xster** [flutter/flutter#45224]
Extracting from https://github.com/flutter/flutter/issues/32862

See also https://github.com/flutter/flutter/issues/21851

- [x] the .iOS or iOS host projects allow both building of modules and of apps. Explain it.
- [ ] define and consistently use the same terminology when referring to different pieces of an add-to-app multi-part project
- [x] Show a possible folder organization of the platform and flutter projects for visualization
- [ ] ~Talk about make-host-app-editable and when it should be used~
- [x] You must run flutter pub get in the Flutter module when changing pubspec
- [ ] Document how to run the flutter module in debug/profile/release (see #34371)
- [ ] Make it clear that we don't build x86/64 AOT/.so/.frameworks
- [x] Add instructions for prebuilt ios-framework (https://github.com/flutter/flutter/issues/36968#issuecomment-533357802)
- [x] Document when flutter packages get + pod install in the host iOS project need to be run again.
- [x] Specify minimum OS version
- [ ] Add IDE module creation instructions.
- [ ] (for option A) how to run debug/profile/release mode for iOS. 
- [ ] for option A is if your teammate checks out the project, they likely need to run flutter packages get / pod install before running too.
 -[ ] explain the reasoning to help user guide their choice for integration method A or B.

Add to https://github.com/flutter/website/blob/staging-add-to-app-do-not-delete-until-2020/src/docs/development/add-to-app/ios/project-setup.md

**Comment by jmagman** [comment]
> Talk about make-host-app-editable and when it should be used

Do we want to document this?  I can't think of any good use-cases for it...

**Comment by xster** [comment]
Try just creating a flutter module via AS and see if it works

**Comment by xster** [comment]
Just thought: I think we still need to point to https://github.com/flutter/flutter/wiki/Upgrading-Flutter-added-to-existing-iOS-Xcode-project from the new website page.

**Comment by xster** [comment]
I think the only things left on this one is documenting (for option A) how to run debug/profile/release mode for iOS. 

Another thing that might be worth mentioning for option A is if your teammate checks out the project, they likely need to run flutter packages get / pod install before running too.

**Comment by jmagman** [comment]
More: https://github.com/flutter/website/pull/3390

**Comment by xster** [comment]
Another user feedback: describe a bit the why in the A/B choice as well in terms of pros and cons depending on the pre-existing circumstances.

**Comment by kf6gpe** [comment]
Adding platform: ios, as this appears to be mostly iOS work so that this is triaged to a team. If it applies to android, too, please add the appropriate label.

**Comment by xster** [comment]
Closing this one now. Tracking individual documentation issues per bug as needed.
