### ISSUE TITLE
Review add-to-app Android usage page

### ISSUE THREAD

**Issue by xster** [flutter/flutter#45220]
Extracting from https://github.com/flutter/flutter/issues/32863

- [x] Make sure every instruction has both languages per platform
- [ ] Describe DartEntrypoint pathToBundle, dartEntrypointFunctionName, DartCallback
- [ ] Explain the need for vm:entry-point 
- [ ] Talk about pushing platform channel messages to Flutter before showing the view vs launching an entrypoint vs launching a route
- [ ] Document the implications of FlutterEngine ownership by the app vs by the activity, onSaveInstanceState etc
- [ ] Point existing add-to-app users to flutter.dev/go/android-project-migration for Android embedding migration.
- [x] Remember to mention that if you don't keep your own FlutterEngine, you lose the VM service connection from flutter attach after you kill your activity/VC #24813
- [ ] Specify why to create a FlutterEngine earlier
- [ ] Review all classes with redundant names like FlutterActivity and make sure the full import path is specified
- [ ] Describe how to specify different entrypoint/route with FlutterEngine

**Comment by goderbauer** [comment]
(triage) @xster Can you please assign this bug to somebody who is working on it or remove it from the march milestone. All bugs in milestones with a month should be assigned to people actively working on it.

**Comment by xster** [comment]
Closing this issue for now. Track individual documentation issues as needed.
