### ISSUE TITLE
flutter_gallery transition_perf tests are extremely flaky

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#45229]
![qD47vrLNEpX](https://user-images.githubusercontent.com/15253456/69208312-fddcbd00-0b07-11ea-975d-849371887cc9.png) ![hZrBPVZq0u6](https://user-images.githubusercontent.com/15253456/69208320-01704400-0b08-11ea-863a-071069081d27.png)

**Comment by godofredoc** [comment]
These tests are not flaking anymore:

https://screenshot.googleplex.com/t8fJ4emM6cQ
