### ISSUE TITLE
Flutter creates a new project even when it does not follow the project name conditions

### ISSUE THREAD

**Issue by AnuragVadd** [flutter/flutter#45233]
When i create a new flutter project, incase I give it a name which does not follow the conditions (i.e. contains capital letter, exceeded character limit, etc.) it seems to be creating a project regardless in the destination folder. 
![Capture](https://user-images.githubusercontent.com/38868279/69210638-716ee080-0b81-11ea-808a-44e43e2c0109.PNG)

in the above picture, the first two projects exceeded the character limit and the third project is within the 30 character limit rule.

**Comment by jmagman** [comment]
1. Did you get a failure message in those cases?  
1. Can we get your exact reproduction steps?  I tried with a really long name and it failed, but didn't create the directory.
1. What's the output of `flutter doctor -v`?

**Comment by AnuragVadd** [comment]
> 1. Did you get a failure message in those cases?

- Yes i did get the error message when i created the invalid projects.

> 2. Can we get your exact reproduction steps?  I tried with a really long name and it failed, but didn't create the directory.

- Hm... I have tried to create a new project with a long name and this time it did not create it. 

> 3. What's the output of `flutter doctor -v`?

[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at E:\flutter
    • Framework revision 68587a0916 (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Praneeth1\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Praneeth1\AppData\Local\Android\Sdk
    • Java binary at: E:\android studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
```
[√] Android Studio (version 3.5)
    • Android Studio at E:\android studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at E:\IntelliJ IDEA Community Edition 2019.2.2
    • Flutter plugin version 41.1.4
    • Dart plugin version 192.7402

[!] VS Code (version 1.38.1)
    • VS Code at C:\Users\Praneeth1\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • SM G950F • ce0118218af134390c • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
Process finished with exit code 0
```
