### ISSUE TITLE
[web] Images appear on top of other widgets

### ISSUE THREAD

**Issue by owenmech** [flutter/flutter#45234]
## Steps to Reproduce

When an image (via assets, memory, etc) is in the Widget tree, it appears above elements of the layout that should be on top of it. This occurs if the image is earlier on a `Stack,` or even in the `BoxDecoration` of a parent `Container.`

The following code builds a `Container` with `color: Colors.black` inside of a larger `Container` with a `DecorationImage`, which should render a black box inside an image.

```
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Container(
          height: 200.0,
          width: 200.0,
          decoration: BoxDecoration(
            image: DecorationImage(image: AssetImage(
              "assets/clouds.png",
            ))
          ),
          child: Center(
            child: Container(
              height: 50.0,
              width: 50.0,
              color: Colors.black,
            ),
          ),
          ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

### On Android, the build behaves as expected, showing:

![image](https://user-images.githubusercontent.com/31045445/69214106-e2c77880-0b1a-11ea-92b8-caa3fe7bbcd7.png)

### On web (debug or deployed), however, the build shows:

![cloudtest](https://user-images.githubusercontent.com/31045445/69214233-3043e580-0b1b-11ea-9d1d-536eafdefebd.PNG)

# Logs

## flutter analyze

```
Analyzing image_issue...
No issues found! (ran in 15.0s)
```

## flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.12.3-pre.49, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.
[√] Chrome - develop for the web
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code, 64-bit edition (version 1.28.2)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by GowthamF** [comment]
It occurs in new Flutter SDK version. 
When I tried it on old version which is v.1.10.6, It was working fine. 
![image](https://user-images.githubusercontent.com/40605124/69223281-4ca24b00-0b38-11ea-9bbd-1a5488e3ef66.png)

**Comment by iapicca** [comment]
Hi @owenmech 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/44845)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
