### ISSUE TITLE
 local_auth: ^0.6.0+1 works fail 

### ISSUE THREAD

**Issue by suchul** [flutter/flutter#45230]
It works well in older versions(0.4.1) but it doesn't work in newer versions

```
 bool isAuthorized = false;
      try {
        isAuthorized = await _localAuthentication.authenticateWithBiometrics(
          localizedReason: "test",
          useErrorDialogs: true,
          stickyAuth: true,
        );
      } on PlatformException catch (e) {
        print(e);
      }

print(e);
PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null)
```

Please check this issue

**Comment by iapicca** [comment]
Hi @suchul 
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by suchul** [comment]
Hi Francecsco lapida

Thank you for your support
I will send you a sample app for this issue

pubspec.yml ==> local_auth: ^0.6.0+1

if you run this app, you can see the problem

And
pubspec.yml ==> local_auth: ^0.4.0+1.

if you modify the code and run it, it works fine.

this app was created as a flutter application

Please check you this issue

Thanks
sckang

 test_local_auth.zip
<https://drive.google.com/file/d/1VLvcwQXfxKTQuShV_jWxVjCx9Oy-vt3J/view?usp=drive_web>


2019년 11월 20일 (수) 오후 7:20, Francecsco Iapicca <notifications@github.com>님이
작성:

**Comment by suchul** [comment]
It works well in older versions(0.4.1) but it doesn't work in newer versions

pubspec.yml ==> local_auth: ^0.6.0+1

if you run this app, you can see the problem

And
pubspec.yml ==> local_auth: ^0.4.0+1.

if you modify the code and run it, it works fine.

this app was created as a flutter application

Please check you this issue

Thanks
sckang

 test_local_auth.zip
<https://drive.google.com/file/d/1VLvcwQXfxKTQuShV_jWxVjCx9Oy-vt3J/view?usp=drive_web>

**Comment by viztushar** [comment]
base on the error you have to change your `MainActivity`

~~~dart
public class MainActivity extends FlutterActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}
~~~

`to` 

~~~dart
public class MainActivity extends FlutterFragmentActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}
~~~

**Comment by iapicca** [comment]
Hi @suchul 
are you still experiencing this issue with the latest version of Flutter?
thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by siva563** [comment]
@suchul  did you got any solution for this issue. I am facing same issue. could you please let me know if you fixed.

@VladyslavBondarenko  I am facing same issue.

**Comment by suchul** [comment]
Hi i am reserved this issue
below comment

base on the error you have to change your MainActivity

public class MainActivity extends FlutterActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}

to

public class MainActivity extends FlutterFragmentActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}

—

2020년 1월 23일 (목) 오후 2:54, Galaba <notifications@github.com>님이 작성:

**Comment by siva563** [comment]
@suchul 

I changed As you suggested. but I am getting below Error:

app\src\main\kotlin\com\example\ntta_mobile_app\MainActivity.kt:8:27: error: expecting a top level declaration
public class MainActivity extends FlutterFragmentActivity {
                          ^
app\src\main\kotlin\com\example\ntta_mobile_app\MainActivity.kt:8:35: error: expecting a top level declaration          
public class MainActivity extends FlutterFragmentActivity {
                                  ^
app\src\main\kotlin\com\example\ntta_mobile_app\MainActivity.kt:8:59: error: expecting a top level declaration     
public class MainActivity extends FlutterFragmentActivity {
                                                          ^
app\src\main\kotlin\com\example\ntta_mobile_app\MainActivity.kt:8:59: error: function declaration must have a name
public class MainActivity extends FlutterFragmentActivity {
                                                          ^
app\src\main\kotlin\com\example\ntta_mobile_app\MainActivity.kt:10:52: error: expecting an element
  protected void onCreate(Bundle savedInstanceState) {
                                                   ^
app\src\main\kotlin\com\example\ntta_mobile_app\MainActivity.kt:9:4: error: unresolved reference: override
  @override
   ^
app\src\main\kotlin\com\example\ntta_mobile_app\MainActivity.kt:10:3: error: unresolved reference: protected       
  protected void onCreate(Bundle savedInstanceState) {
  ^
app\src\main\kotlin\com\example\ntta_mobile_app\MainActivity.kt:10:18: error: unresolved reference: onCreate
  protected void onCreate(Bundle savedInstanceState) {
                 ^
app\src\main\kotlin\com\example\ntta_mobile_app\MainActivity.kt:10:27: error: unresolved reference: Bundle
  protected void onCreate(Bundle savedInstanceState) {
                          ^
app\src\main\kotlin\com\example\ntta_mobile_app\MainActivity.kt:11:5: error: no supertypes are accessible in this context
    super.onCreate(savedInstanceState);
    ^
app\src\main\kotlin\com\example\ntta_mobile_app\MainActivity.kt:11:20: error: unresolved reference: savedInstanceState  
    super.onCreate(savedInstanceState);
                   ^
app\src\main\kotlin\com\example\ntta_mobile_app\MainActivity.kt:12:44: error: 'this' is not defined in this context     
    GeneratedPluginRegistrant.registerWith(this);
                                           ^

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with 
--scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by siva563** [comment]
@dnfield Could you please look into it above issue.

**Comment by VladyslavBondarenko** [comment]
@suchul 
Mentioned code - java-code, wasn't you proposed to convert it to kotlin?

This main file in kotlin should look like:

```
package com.example.yourpackagename

import android.os.Bundle

import io.flutter.app.FlutterFragmentActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(this)
    }
}
```

**Comment by siva563** [comment]
@VladyslavBondarenko  where should add this code I mean Which file? I am not able to find any  MainActivity.Java file

**Comment by VladyslavBondarenko** [comment]
@suchul 
In your `app\src\main\kotlin\com\example\ntta_mobile_app\MainActivity.kt`

**Comment by VladyslavBondarenko** [comment]
@suchul 
Also if you have `Type mismatch: required PluginRegistry, Found:  MainActivity` on `registerWith(this)`, try https://github.com/FirebaseExtended/flutterfire/issues/1684#issuecomment-567982881

**Comment by dnfield** [comment]
I think @mklim @matthew-carroll  or @blasten would know what's going on better here

**Comment by matthew-carroll** [comment]
I've read through this read but it's not clear to me if a problem still exists, and if it does, what the particular problem is. There was a recommendation to change from `FlutterActivity` to `FlutterFragmentActivity`. Did that solve the original problem in this issue? Most of the comments after that appear to be confusion around Java vs Kotlin implementations...

**Comment by bmth4ever** [comment]
@viztushar @VladyslavBondarenko I just created a new project using `-a java` flag (cause I don't want kotlin).
Here's the default `MainActivity.java`:
```
package com.example.tired;

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }
}
```
I can't make this work by importing `import io.flutter.app.FlutterFragmentActivity` And changing `FlutterActivity` to `FlutterFragmentActivity`. Can you help please?

**Comment by Theo6890** [comment]
> **Edit: Got it working by the following `MainActivity.java`:**
> 
> ```
> import io.flutter.embedding.android.FlutterFragmentActivity;
> import io.flutter.embedding.engine.FlutterEngine;
> import io.flutter.plugins.GeneratedPluginRegistrant;
> 
> import android.os.Build;
> import android.view.ViewTreeObserver;
> import android.view.WindowManager;
> 
> public class MainActivity extends FlutterFragmentActivity {
>   @Override
>   public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
>     GeneratedPluginRegistrant.registerWith(flutterEngine);
>   }
> }
> ```

**Same for Kotlin :** 
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterFragmentActivity;
import io.flutter.embedding.engine.FlutterEngine;

import io.flutter.plugins.GeneratedPluginRegistrant

import android.os.Build;
import android.view.ViewTreeObserver;
import android.view.WindowManager;

class MainActivity : FlutterFragmentActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
