### ISSUE TITLE
add-to-app to stable channel

### ISSUE THREAD

**Issue by santiihoyos** [flutter/flutter#45244]
Hi,
We are using add-to-app in our app. This feature is only available in master branch...
Are there any plans to pass add-to-app to stable branch soon?

cheers :)

**Comment by iapicca** [comment]
Hi @santiihoyos 
you can find Flutter's road map [here](https://github.com/flutter/flutter/wiki/Roadmap)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
