### ISSUE TITLE
tile bar widget is broken

### ISSUE THREAD

**Issue by wikiworld** [flutter/flutter#45247]
![주석 2019-11-20 192330](https://user-images.githubusercontent.com/52195693/69230796-44472000-0bcb-11ea-8b30-48e9978d9b6b.png)

damn

**Comment by iapicca** [comment]
Hi @wikiworld 
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
could you please provide your updated  `flutter doctor -v`
and  a minimal code sample to reproduce the problem?
Please refrain from posting pictures if not necessary.
Thank you

**Comment by predatorx7** [comment]
From the screenshot, it's clear that RenderFlex overflow is caused by a failed assertion (boolean != null) maybe because `product.isFavorite` == null.
Either initialize `isFravorite` in your Product ChangeNotifier to false or use the expression `(product?.isFavorite ?? false)` on line 39.
