### ISSUE TITLE
* What went wrong: A problem occurred evaluating project ':app'. > ASCII

### ISSUE THREAD

**Issue by Isonomic** [flutter/flutter#45254]
I am reopening this to show a fix that worked for me. This issues was closed as if it worked for everyone but did not for me and possibly others. Where else can I post this solution to help others??  
 I noticed the solution was to downgraded google services.gms from 4.3.2 to 4.2.0 which did not work for me and even if it did I dont like downgrading.This fix is an upgrade to newer versions and it works like a charm. I will attach screen shot of before with error and after changing these 3 lines with a succesful build and upgrading instead of downgrading. Please leave this open as the problem is not resolved when building a new flutter app with new firebase for android.  So instead, keep the 4.3.2. DO NOT DOWNGRADE TO 4.2.0. Then In the android/build.gradle (project level, not app level) upgrade these two lines............    ext.kotlin_version = '1.3.50' in build script and .................        classpath 'com.android.tools.build:gradle:3.5.0' in dependancies.  then in android/gradle/wrapper/gradle-wrapper.properties  change the version to this  distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip     it works for me on every new project that fails out of the gate for whatever reason.  

![Screenshot (128)](https://user-images.githubusercontent.com/37713396/69247161-33fd5980-0b67-11ea-933d-02554df309ad.png)
![Screenshot (129)](https://user-images.githubusercontent.com/37713396/69247162-33fd5980-0b67-11ea-9cc9-dd3043e3fe0a.png)
![Screenshot (130)](https://user-images.githubusercontent.com/37713396/69247164-33fd5980-0b67-11ea-964d-c9de8e4c040d.png)
![Screenshot (131)](https://user-images.githubusercontent.com/37713396/69247166-3495f000-0b67-11ea-85d4-b7782a73a21a.png)

**Comment by iapicca** [comment]
Hi @Isonomic 
You mentioned a closed issue, can you please link it_
Also could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose` or `flutter build --verbose` ?
To better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem.
Please refrain from posting pictures if not necessary.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
