### ISSUE TITLE
Add VideoProgressIndicator direction right to left or left to right  

### ISSUE THREAD

**Issue by Ahmedtaha123** [flutter/flutter#45252]
i used Arabic local and direction is right to left
and VideoProgressIndicator direction started normal 
from right to left but when i pressed to make video step forward 
it go to skip back
like this
                                                                                 pressed here
                                                                         >>>>>>>>>>
..........................................................................................................................
it took me to here
               >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
..........................................................................................................................
 
but when i change to English
                                                                         pressed here
>>>>>>>>>>
..........................................................................................................................
it took me to here
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
..........................................................................................................................
 as you see in English default direction is left to right it work good
but in language like Arabic direction is right to left not work good 
i hope you work in this in future 
and if you wanna me record video to you to show how it work no problem
thank you

**Comment by iapicca** [comment]
Hi @Ahmedtaha123 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
