### ISSUE TITLE
Silent gradlew crash when flutterVersion is larger than 32bit integer

### ISSUE THREAD

**Issue by Mike278** [flutter/flutter#45256]
After changing some CI config, builds started failing with the following error:

```
Initializing gradle...                                              0.5s
Resolving dependencies...                                               
* Error running Gradle:
ProcessException: Process "/home/code/my_flutter_app/android/gradlew" exited abnormally:

  Command: /home/code/my_flutter_app/android/gradlew app:properties


Please review your Gradle project setup in the android/ folder.
```

Manually running that gradle task (`cd android && ./gradlew app:properties`) started to print some output, but then exited with no error message.

It was only after opening the `android` directory in Android Studio that I finally saw an error message: `ERROR: For input string: "20191119142208"`. This is the `flutter.versionCode=20191119142208` from the `local.properties` file, which is then converted to an int in build.gradle: 
```
defaultConfig {
    versionCode flutterVersionCode.toInteger()
    ...
}
```
Changing the version code to something that fits in a 32-bit integer fixes the issue. Googling only found results relating to #23777 and #34324 so I figured I'd open an issue to help future googlers.

## Steps to Reproduce

1. Open `android/local.properties` 
2. Add `flutter.versionCode=20191119142208`
3. Run `flutter build apk`

`flutter doctor -v`:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_CA.UTF-8)
    • Flutter version 1.9.1+hotfix.6 at /*****/Flutter/flutter
    • Framework revision 68587a0916 (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /*****/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /*****/Android/Sdk
    • ANDROID_SDK_ROOT = /*****/Android/Sdk
    • Java binary at: /*****/AndroidStudio/ch-0/183.5692245/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /*****/AndroidStudio/ch-0/183.5692245
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /*****/IDEA-U/ch-0/192.5728.98
    • Flutter plugin version 39.0.4
    • Dart plugin version 192.7402

[✓] Connected device (1 available)
    • SM T510 • android-arm • Android 9 (API 28)

• No issues found!
```

**Comment by jmagman** [comment]
Did you see the log when you ran with the verbose `-v` flag?
Ideally the tool would surface this for you.

**Comment by Mike278** [comment]
Nope - even running the gradle command with -v didn’t show the ERROR: For input string: "20191119142208". The only thing that showed it was Android Studio.
