### ISSUE TITLE
Desktop apps no longer draw more than one frame.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#45258]
As of a32fc986f, desktop applications no longer respond to any keyboard or mouse events, basically bricking them.  I only tested this on macOS, but suspect all desktop platforms have a similar problem.

Will attempt to bisect today.

**Comment by gspencergoog** [comment]
Actually it turns out that the problem is not that keyboard and mouse don't work, but that it's not drawing anything past the initial screen. When I click on buttons, I get debug messages printed to the console, but the display never changes.

I've bisected this to the change 99324105da695ed55d322a039cf5349a7b2ab45b, which seems to be the root cause.

**Comment by gspencergoog** [comment]
cc @chunhtai

**Comment by jonahwilliams** [comment]
Another case that https://github.com/flutter/flutter/issues/42281 would have helped

**Comment by clarkezone** [comment]
This is also happening on windows.. blocking my hackathon

**Comment by mohamedmansour** [comment]
@gspencergoog  after I reverted that commit, I verified it is working again for me!
