### ISSUE TITLE
Device lab needs to support desktop host constraints.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#45266]
In https://github.com/flutter/flutter/pull/45264, we added a desktop macOS-specific test, but the only way to specify the devicelab host constraints was to say `"mac/ios"` or any of the other host types that include "mac".

We're going to have a similar problem with Windows and Linux: we need a way to specify constraints that just includes the host and not also the type of the attached device in the `manifest.yaml`:

```yaml
...
    required_agent_capabilities: ["mac"]
...
    required_agent_capabilities: ["windows"]
...
    required_agent_capabilities: ["linux"]
...
```

**Comment by godofredoc** [comment]
This is done, now you can specify "windows", "linux" or "mac" in the test capabilities and will pick the next available machine.
