### ISSUE TITLE
flutter build bundle crash - Deletion failed, flutter_assets directory is not empty

### ISSUE THREAD

**Issue by beezerbt** [flutter/flutter#45265]
hi

I was rebuilding my Flutter application and I got the below...so i did as it is asking me, so here goes below the contents of my file (please see below).
I am new to Flutter so just following instructions...**don't shoot the messenger**.

I am using:
Android Studio 3.5.2
Build #AI-191.8026.42.35.5977832, built on October 30, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Herewith the file content:**
------------------------------------------------------------------------------------------------------------
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build bundle --target C:\repo\flutter_start_again\lib\main.dart --target-platform android-arm --filesystem-scheme org-dartlang-root --track-widget-creation --depfile C:\repo\flutter_start_again\build\app\intermediates\flutter\debug\android-arm/snapshot_blob.bin.d --asset-dir C:\repo\flutter_start_again\build\app\intermediates\flutter\debug\android-arm/flutter_assets --debug

## exception

FileSystemException: FileSystemException: Deletion failed, path = 'C:\repo\flutter_start_again\build\app\intermediates\flutter\debug\android-arm/flutter_assets' (OS Error: The directory is not empty.
, errno = 145)

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:206:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:464:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      writeBundle (package:flutter_tools/src/bundle.dart:181:15)
<asynchronous suspension>
#4      assemble (package:flutter_tools/src/bundle.dart:172:9)
<asynchronous suspension>
#5      BundleBuilder.build (package:flutter_tools/src/bundle.dart:115:11)
<asynchronous suspension>
#6      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:119:25)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#16     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#25     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CommandRunner.run (package:args/command_runner.dart:112:14)
#28     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1500:12)
#34     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#41     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#42     run (package:flutter_tools/runner.dart:50:10)
#43     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#44     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17134.81], locale en-GB)
    • Flutter version 1.9.1+hotfix.6 at C:\software\flutter
    • Framework revision 68587a0916 (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\kambiz\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Community Edition (version 2016.3)
    • IntelliJ at C:\FDriveKambiz\IntelliJ IDEA Community Edition 2016.3
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[✓] Connected device (1 available)
    • SM A105FN • RF8M51P9SPZ • android-arm • Android 9 (API 28)

! Doctor found issues in 2 categories.
```
=====================================================

**Comment by mhmoudsabry** [comment]
me too

`Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build bundle 
--target E:\mhmoud\react\khaled_flutter\apps\khaled_flutter_beta_3\lib\main.dart --target-platform android-arm --filesystem-scheme org-dartlang-root --track-widget-creation --depfile E:\mhmoud\react\khaled_flutter\apps\khaled_flutter_beta_3\build\app\intermediates\flutter\debug\android-arm/snapshot_blob.bin.d --asset-dir E:\mhmoud\react\khaled_flutter\apps\khaled_flutter_beta_3\build\app\intermediates\flutter\debug\android-arm/flutter_assets --debug

## exception

FileSystemException: FileSystemException: Deletion failed, path = 'E:\mhmoud\react\khaled_flutter\apps\khaled_flutter_beta_3\build\app\intermediates\flutter\debug\android-arm/flutter_assets' (OS Error: The directory is not empty.
, errno = 145)

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:206:7)

#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:464:47)
#2   
   ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)

#3      writeBundle (package:flutter_tools/src/bundle.dart:181:15)
<asynchronous suspension>

#4      assemble (package:flutter_tools/src/bundle.dart:172:9)
<asynchronous suspension>

#5      BundleBuilder.build (package:flutter_tools/src/bundle.dart:115:11)
<asynchronous suspension>

#6      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:119:25)
<asynchronous suspension>

#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
<asynchronous suspension>

#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>

#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>

#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)

#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)

#14     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>

#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)

#16     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>

#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>

#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>

#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)

#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)

#23     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>

#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>

#25     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)

#26     new Future.sync (dart:async/future.dart:224:31)

#27     CommandRunner.run (package:args/command_runner.dart:112:14)
#28     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)

#29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>

#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)

#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1500:12)

#34     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>

#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>

#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)

#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)

#40     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>

#41     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>

#42     run (package:flutter_tools/runner.dart:50:10)

#43     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>

#44     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)

#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)

#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 6.1.7601], locale ar-EG)
    • Flutter version 1.9.1+hotfix.6 at E:\mhmoud\react\khaled_flutter\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\El Shamel Tech\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.5)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code, 64-bit edition
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • SM G532F • 4200a15ed4dd9427 • android-arm • Android 6.0.1 (API 23)

! Doctor found issues in 1 category.
```
`

**Comment by mhmoudsabry** [comment]
> me too
> 
> `Flutter crash report; please file at https://github.com/flutter/flutter/issues.
> 
> ## command
> flutter build bundle
> --target E:\mhmoud\react\khaled_flutter\apps\khaled_flutter_beta_3\lib\main.dart --target-platform android-arm --filesystem-scheme org-dartlang-root --track-widget-creation --depfile E:\mhmoud\react\khaled_flutter\apps\khaled_flutter_beta_3\build\app\intermediates\flutter\debug\android-arm/snapshot_blob.bin.d --asset-dir E:\mhmoud\react\khaled_flutter\apps\khaled_flutter_beta_3\build\app\intermediates\flutter\debug\android-arm/flutter_assets --debug
> 
> ## exception
> FileSystemException: FileSystemException: Deletion failed, path = 'E:\mhmoud\react\khaled_flutter\apps\khaled_flutter_beta_3\build\app\intermediates\flutter\debug\android-arm/flutter_assets' (OS Error: The directory is not empty.
> , errno = 145)
> 
> ```
> #0      _Directory._deleteSync (dart:io/directory_impl.dart:206:7)
> 
> #1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:464:47)
> #2   
>    ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
> 
> #3      writeBundle (package:flutter_tools/src/bundle.dart:181:15)
> <asynchronous suspension>
> 
> #4      assemble (package:flutter_tools/src/bundle.dart:172:9)
> <asynchronous suspension>
> 
> #5      BundleBuilder.build (package:flutter_tools/src/bundle.dart:115:11)
> <asynchronous suspension>
> 
> #6      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:119:25)
> <asynchronous suspension>
> 
> #7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
> <asynchronous suspension>
> 
> #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
> <asynchronous suspension>
> 
> #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
> <asynchronous suspension>
> 
> #10     _rootRun (dart:async/zone.dart:1124:13)
> #11     _CustomZone.run (dart:async/zone.dart:1021:19)
> 
> #12     _runZoned (dart:async/zone.dart:1516:10)
> #13     runZoned (dart:async/zone.dart:1463:12)
> 
> #14     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
> <asynchronous suspension>
> 
> #15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
> 
> #16     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
> <asynchronous suspension>
> 
> #17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
> <asynchronous suspension>
> 
> #18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
> <asynchronous suspension>
> 
> #19     _rootRun (dart:async/zone.dart:1124:13)
> #20     _CustomZone.run (dart:async/zone.dart:1021:19)
> 
> #21     _runZoned (dart:async/zone.dart:1516:10)
> #22     runZoned (dart:async/zone.dart:1463:12)
> 
> #23     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
> <asynchronous suspension>
> 
> #24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
> <asynchronous suspension>
> 
> #25     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
> 
> #26     new Future.sync (dart:async/future.dart:224:31)
> 
> #27     CommandRunner.run (package:args/command_runner.dart:112:14)
> #28     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
> 
> #29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
> <asynchronous suspension>
> 
> #30     _rootRun (dart:async/zone.dart:1124:13)
> #31     _CustomZone.run (dart:async/zone.dart:1021:19)
> 
> #32     _runZoned (dart:async/zone.dart:1516:10)
> #33     runZoned (dart:async/zone.dart:1500:12)
> 
> #34     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
> <asynchronous suspension>
> 
> #35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
> <asynchronous suspension>
> 
> #36     _rootRun (dart:async/zone.dart:1124:13)
> #37     _CustomZone.run (dart:async/zone.dart:1021:19)
> 
> #38     _runZoned (dart:async/zone.dart:1516:10)
> #39     runZoned (dart:async/zone.dart:1463:12)
> 
> #40     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
> <asynchronous suspension>
> 
> #41     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
> <asynchronous suspension>
> 
> #42     run (package:flutter_tools/runner.dart:50:10)
> 
> #43     main (package:flutter_tools/executable.dart:65:9)
> <asynchronous suspension>
> 
> #44     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
> 
> #45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
> 
> #46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
> ```
> 
> ## flutter doctor
> ```
> [✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 6.1.7601], locale ar-EG)
>     • Flutter version 1.9.1+hotfix.6 at E:\mhmoud\react\khaled_flutter\flutter
>     • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at C:\Users\El Shamel Tech\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at E:\Program Files\Android\Android Studio
>     • Flutter plugin version 41.1.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> 
> [✓] VS Code, 64-bit edition
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 2.21.1
> 
> [✓] Connected device (1 available)
>     • SM G532F • 4200a15ed4dd9427 • android-arm • Android 6.0.1 (API 23)
> 
> ! Doctor found issues in 1 category.
> ```
> 
> `

we need to delete build directory before building to solve this issue
any real solution

**Comment by jonahwilliams** [comment]
Closing as obsolete, since build bundle is no longer used
