### ISSUE TITLE
Out of memory when playing video and performing <elided>

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#45261]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=41783.

**Comment by cbracken** [comment]
This is being worked on by a combination of Fuchsia people and co-ordinated on the Flutter side by @cbracken.

**Comment by Hixie** [comment]
Just spoke to @cbracken, this is still being worked on.

**Comment by Hixie** [comment]
@cbracken any updates?

**Comment by cbracken** [comment]
No longer seeing this issue (also no longer assigned to Flutter).
