### ISSUE TITLE
[luci] Upload framework coverage?

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#45271]
Per discussion at https://github.com/flutter/infra/pull/71#issuecomment-556240160, LUCI isn't uploading framework coverage data currently. Is it really needed?

/cc @goderbauer @dnfield @Hixie

**Comment by Hixie** [comment]
It is, see https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter.

**Comment by digiter** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/31615
