### ISSUE TITLE
[build_dashboard] Text cannot be copied

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#45275]

**Comment by digiter** [comment]
Triage: this is a Flutter web bug?

**Comment by CaseyHillers** [comment]
Correct. @cbracken updated some of the dashboard widgets to use `SelectableText` to make it work when the web engine gets that functionality.

**Comment by CaseyHillers** [comment]
This is working on Chrome now, closing. Any widgets that we want copyable can just be made as selectable text.
