### ISSUE TITLE
Desktop Embedding should be aware of AppLifeCycleState

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#45270]
https://api.flutter.dev/flutter/dart-ui/AppLifecycleState-class.html

Currently, the majority of desktop embedding that go through embedder.h does not send AppLifeCycleState message to framework. That means the state is always null. This was ok because framework always enables the frame scheduling if it receives unknown state.

However, with the introducing of detached state, the engine will default to detached state and framework will disable the frame until engine become active. This become a problem because the desktop embedding does not send AppLifeCycleState.resumed message to framework, which causes the framework think engine is never going to be active.

**Comment by chunhtai** [comment]
cc @gspencergoog @jonahwilliams @xster

**Comment by stuartmorgan** [comment]
At the risk of beinga broken record: we need to make sure that regardless of what we do with the desktop embeddings here, the default behavior of using the embedding API should *not* change if at all possible. It's a public API, and it's not supposed to have significant behavioral breaking changes.

We should have embedder.h/cc default to solve behavior that's consistent with how it used to work, then add an opt-in for more detailed lifecycle events if desired.

**Comment by chunhtai** [comment]
One thing we can do is always sends inactive/Resumed lifecycle message to framework when embedder.h FlutterEngineInitialize.

This might cause problem when the addtoapp extends the work toword desktop, but we this should be enough for now
