### ISSUE TITLE
drive-examples should handle new e2e test locations gracefully

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#45283]
We should be able to put plugin integration tests in a single consistent location (test/*_e2e.dart) and have CI run it. Right now our iOS CI is confused because it isn't expecting tests at that location.

https://github.com/FirebaseExtended/flutterfire/runs/310481522

**Comment by timsneath** [comment]
Touching issue for triage purposes.

**Comment by stuartmorgan** [comment]
We've standardized on a location matching current `integration_test` docs, so closing at obsolete.
