### ISSUE TITLE
[firebase_analytics] Support firebase_analytics on web.

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#45289]
We should implement `firebase_analytics` in Flutter for Web.

**Comment by girubhai** [comment]
What is the deadline ? is there any pub in beta ?

**Comment by AndroidNils** [comment]
Any updates?

**Comment by jlubeck** [comment]
How can we help with this?

**Comment by 24601** [comment]
It seems the PR for the platform interface was merged, is this item simply not been moved in status or is there something outstanding yet to it being functional?

**Comment by ditman** [comment]
@tugorez, do you want to give this a shot?

**Comment by tugorez** [comment]
Sure thing!

**Comment by ditman** [comment]
_(I just sent @tugorez a heap of documentation he needs to take a look at before he starts work on this issue!)_

**Comment by tugorez** [comment]
TODO: 
- [ ] Wire the platform interface (in progress...)
- [ ] Add initial implementation for firebase_analytics_web (in progress...)
- [ ] Wire the web implementation
- [ ] Update the firebase_analytics README.md to indicate we now support web
- [ ] Update the firebase_analytics example

**Comment by ditman** [comment]
This has been published. People should be able to use this by depending both in the core plugin (firebase_analytics) and firebase_analytics_web

https://pub.dev/packages/firebase_analytics_web

It'll be endorsed once we fix the missing `ios` directory in the plugin.

**Comment by ditman** [comment]
Tagged and published `firebase_analytics 5.0.16`
