### ISSUE TITLE
[build_dashboard] No legend for the grid

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#45280]
The old build dashboard has a ? button that shows a legend for what the different grid items mean.  I don't see any equivalent on the new build dashboard.

**Comment by CaseyHillers** [comment]
The legend statuses were moved to help clear some of the clutter. The status for a color is still accessible by clicking on a task and hovering over it's icon (see below)

![Click a Task box then it's icon will have a tooltip of the status of the task](https://user-images.githubusercontent.com/2148558/76572425-45040a80-6477-11ea-820b-e85b56d1a849.png)

James, do you think this is okay? We could also surface this information via the overlay and just have some text at the top that says:
`Status: In Progress` or whatever the status of the task is.
