### ISSUE TITLE
google_map_flutter for iOS has higher elevation.

### ISSUE THREAD

**Issue by farry19** [flutter/flutter#45281]
## Steps to Reproduce

1. On iOS add GoogleMaps widget in stack.
2. Add another overlay, e.g. AnimatedBuilder

**Target Platform:** iOS
**Target OS version/browser:** 9.0
**Devices:** iPhone 7.0

## Logs

```
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.15.1 19B88, locale en-PK)
    • Flutter version 1.10.7 at /Users/farry/development/flutter
    • Framework revision e70236e36c (7 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/farry/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.4886.3

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • Farrukh’s iPhone • ba892969dc83d48598c02bbe138f72b288abbdb8 • ios • iOS 13.1.3

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
Hi @farry19 
what behavior did you experience?
Wrong placement in the `Stack` ?
thank you for providing your `flutter doctor -v` 
and the steps to reproduce the problem

**Comment by farry19** [comment]
I was able to embed package into iOS while adding some keys into plist.info and when it appears, all the other overlays in stack went back to the maps layer:

![image](https://user-images.githubusercontent.com/1573511/69342207-d8c58700-0c8c-11ea-9023-76a1973d8b02.png)

Then i wrapped both the map widget and the underlaying into material and set the higher elevation to overlaying cards but the result is like in attached image.

**Comment by iapicca** [comment]
Hi @farry19 
that is clearer than 100 words,
thank you

**Comment by farry19** [comment]
Sorry for my understandings and posts, but I was following this tutorial:

[https://youtu.be/CjhXyY_92xU](url)

everything is working fine except the overlay cards for locations in IOS.

**Comment by iapicca** [comment]
Hi @farry19 
I'm glad that you fixed the issue,
thank you for letting me know

**Comment by farry19** [comment]
> Hi @farry19
> I'm glad that you fixed the issue,
> thank you for letting me know

I didn't confirm you that i have fixed the issue, i rather updated you that i was following this tutorial and on iOS i have the issue.

**Comment by VladyslavBondarenko** [comment]
Hi @farry19 
I checked [this code](https://github.com/rajayogan/flutter-googlemapeffects) from the link under the mentioned video and I can't see described issue, cards are shown above the map.
I tried with flutter master v1.15.19-pre.17, iOS 13.3 (emulator) and google_maps_flutter 0.5.24+1.
Are you still experiencing this?

**Comment by TahaTesser** [comment]
Hi @farry19 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
