### ISSUE TITLE
[google_maps_flutter] Support google_maps_flutter on web

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#45292]
We should add web support for `google_maps_flutter`

**Comment by zoeyfan** [comment]
Should this be moved to flutter/plugins?

**Comment by ditman** [comment]
@zoeyfan sorry, I've just seen your comment here (x_x).

We have a `Flutter Web Plugins` that we created in flutter/flutter (because there's plugins on flutter/plugins but also FirebaseExtended/flutterfire). This seemed like a nice, visible place to hold this tickets.

**Comment by cylyl** [comment]
@ditman will you create "google_maps_flutter_platform_interface " and "google_maps_flutter_web" dir soon?

**Comment by ditman** [comment]
@cylyl I caused some breakage in the `connectivity` plugin while I was adding a web version, but as soon as I'm done with that and a couple high priority issues, I'll get back to this.

**Comment by Sammius** [comment]
We are waiting and hope!

**Comment by cylyl** [comment]
> We are waiting and hope!

don't wait, build it...
https://github.com/cylyl/plugins/tree/google_maps_flutter_web

**Comment by satvikpendem** [comment]
Could this be done by checking the platform and rendering either the webview of Google Maps when on web, or the native Flutter version when on mobile/desktop? Rather than reimplementing Google Maps onto web when it already is a web app. This might break the WASM Skia renderer for Flutter Web though, I'm not sure if the WASM renderer can display web views well.

**Comment by ditman** [comment]
@satvikpendem check @cylyl's code, he's building the web version as we speak, using the JS version for web. The core plugin will be migrated to a "platform interface" (that @cylyl also helped write) so the same plugin code works across all platforms. Pretty exciting stuff! :)

**Comment by maceip** [comment]
@cylyl i'm new to federated flutter plugins. I'm trying to get your fork to work using google_maps_flutter_web, and google_maps_flutter_platform_interface. What's the primer for getting this to work across web, ios, and android? Do I just include google_maps_flutter in my pubspec.yaml; platform checks happen behind the scenes and it just works? Do I need to do anything differently with this plugin now as the caller?

**Comment by ditman** [comment]
@maceip @cylyl is busy and can't keep working on the Google Maps plugin in the near future. I took over all his code and consolidated it in a new branch, here:

https://github.com/ditman/plugins/commits/gmaps-web

The latest commit of that branch is adapting the "example" app of the standard google_maps_flutter package to work on web. It renders a map and does some things, but it's still buggy.

_Contributions welcome ;)_

**Comment by ramioooz** [comment]
I found this plugin, I think it can get the job done for now for those who want google maps on both mobile and the web :
[flutter_google_maps ](https://pub.dev/packages/flutter_google_maps)

I will give it a try, and I will keep an eye on the issue.
Thank you

**Comment by tomrozb** [comment]
@ditman is map for web something you have high in your priorities? Look's like currently there's no good plugin for this. Most of the plugins can show the map, but some vital operations are still not supported

**Comment by ditman** [comment]
@tomrozb maps is my next plugin, but before I need to finish image_picker (and help finish firebase_analytics and maybe realtime database).

**Comment by ramioooz** [comment]
😥 Man, this is taking way longer than it should...

hey @ditman,
I can see that you have this task assigned to you, If you are so busy, why not consider having some of your colleges work with you on it.
This task holds a **significant value** for the framework, It should be considered as a **top priority**.
please give it a push forward, you are almost there,,,,

My regards,
Rami

**Comment by ditman** [comment]
I appreciate the prioritization advice @ramioooz! I've hidden your comment because now prioritization happens via labels on issues (This is a very recent change!)

As you can see, this issue is labeled P3 and customer: crowd. **It's being worked on!** no need to ping the issue, it won't be forgotten!

**Comment by gabrielgarciagava** [comment]
@ditman I just starred your fork, this is an awesome job you are working on. I already tested it locally, and it is pretty nice :)
I would like to know if there is any kind of estimates to have it "ready to integrate".

**Comment by ditman** [comment]
@gabrielgarciagava thanks! I don't have a very good estimate yet; I'm still adding some missing initialization features, and the fork is missing a lot of documentation and tests; it's going to be a few weeks at least until it's ready for PR, plus then whatever changes need to happen on the PR phase :)

**Comment by jfreeland** [comment]
> https://github.com/ditman/plugins/commits/gmaps-web
> 
> _Contributions welcome ;)_

I had to add a podspec to https://github.com/ditman/plugins/tree/gmaps-web/packages/google_maps_flutter/google_maps_flutter_web as ios/google_maps_flutter_web.podspec to build for iOS but it works great so far across platforms. Nice!!

**Comment by ditman** [comment]
@jfreeland yes! We still need a "noop" podspec for ios, thanks for reminding me!

**Comment by lzzy12** [comment]
Any ETA on this?

**Comment by ditman** [comment]
I've posted a PR with the first draft of the plugin, if anybody wants to take a look, there's instructions in how to integrate it into your flutter web apps in the PR!

Feel free to post comments/problems in the PR as well.

**Comment by ditman** [comment]
google_maps_flutter_web 0.1.0 has been published!

https://pub.dev/packages/google_maps_flutter_web

Note that the package is still not *endorsed*, so you'll have to depend both on `google_maps_flutter` and `google_maps_flutter_web` on your pubspecs.

See the README for installation instructions/configuration/caveats/known issues.

**Comment by tolotrasamuel** [comment]
I just tested it I get this error :  Assertion failed: file:///C:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter_web-0.1.0/lib/src/google_maps_flutter_web.dart:268:12
mapId != null
"buildView needs a `_webOnlyMapCreationId` in its creationParams to prevent widget reloads in web."

**Comment by ditman** [comment]
@tolotrasamuel please ensure that you're using the latest version of the google_maps_flutter package (`^0.5.30`) on your pubspec.
