### ISSUE TITLE
[firebase_dynamic_links] Add web support

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#45298]
We should add web support for `firebase_dynamic_links`

**Comment by AndroidNils** [comment]
+1

**Comment by AndroidNils** [comment]
Can somebody add this to project 69? https://github.com/flutter/flutter/projects/69

**Comment by MoAliGatch** [comment]
We need this feature ASAP!

**Comment by stuartmorgan** [comment]
Closing as Firebase issues are now tracked in the FlutterFire repository.
