### ISSUE TITLE
[firebase_messaging] Add web support

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#45300]
We should implement web support for `firebase_messaging`

**Comment by YohanWadia** [comment]
Hey! Sorry just wanted to know if I am missing out on something... Or Firebase Messaging for WEB isnt ready? I've searched every where but cant seem to get an example/package/ etc etc... Where could I keep track of this feature & its release?

**Comment by cbenhagen** [comment]
Just subscribe to this issue to get notified when it is implemented.

**Comment by YohanWadia** [comment]
Hey guys just checking in... Cause this is an important feature...
What are my other options to make the same code base run with firebase_messaging for notifications... when I run it on the web?
Ios & Android are perfect... but what else could i do for the same effect of receiving a notification via firebase messaging for the web?

**Comment by TobiasHeidingsfeld** [comment]
Super important for me too. This would be awesome to have working

**Comment by YohanWadia** [comment]
> Super important for me too. This would be awesome to have working

@TobiasHeidingsfeld ... the funny thing is that, I fail to imagine of how developers are doing real crossplatform development for the web + Firebase without actually running into this problem! So either no one is really using firebase properly... or no one is really using flutter for the web!! But its absolutely a no brainer to know how important this is and we're the only few guys over here!  ;-)

**Comment by abhinavsingh** [comment]
jFYI, gave it a try on using `dev` channel and error seems to be related to unsupported `Platform._operatingSystem` as `dart:io` doesn't seem to work well within javascript environments.

```
errors.dart:164 Uncaught (in promise) Error: Unsupported operation: Platform._operatingSystem
    at Object.throw_ [as throw] (errors.dart:213)
    at Function._operatingSystem (io_patch.dart:244)
    at Function.get operatingSystem [as operatingSystem] (platform_impl.dart:58)
    at get _operatingSystem (platform.dart:71)
    at Function.desc.get [as _operatingSystem] (operations.dart:796)
    at Function.get operatingSystem [as operatingSystem] (platform.dart:95)
    at LocalPlatform.get operatingSystem [as operatingSystem] (local_platform.dart:21)
    at LocalPlatform.get isIOS [as isIOS] (platform.dart:44)
    at firebase_messaging.FirebaseMessaging.private.requestNotificationPermissions (firebase_messaging.dart:84)
```

**Comment by cyanglaz** [comment]
@kroikie Should we move this to the flutterfire repo?

**Comment by mzimbres** [comment]
Where can I follow the progress with this issue? Thanks.

**Comment by cbenhagen** [comment]
@mzimbres you can follow this issue: https://github.com/FirebaseExtended/flutterfire/discussions/1653. There is also a PR: https://github.com/FirebaseExtended/flutterfire/pull/1989. But no one had time to review it so far so it got a bit stale.

**Comment by Vinzent03** [comment]
@cbenhagen Did I miss something or did you mention an issue for mac os support in a web support discussion?

**Comment by cbenhagen** [comment]
🙈 Oh, my bad. Sorry for the noise.

**Comment by limdor** [comment]
What is the status on this issue? Any estimations when this might be implemented? Are there any workarounds possible for the moment?

**Comment by Vinzent03** [comment]
Take at look at the roadmap. https://github.com/FirebaseExtended/flutterfire/issues/2582#issuecomment-734318141

**Comment by KSLiquid** [comment]
The notifications themselfes work, but there is a known limitation that background notifications can only be handled in Javascript, not in dart.
(source: https://firebase.flutter.dev/docs/messaging/usage)
Is there any Issue which tracks that?
thanks!

**Comment by balvinderz** [comment]
this can be closed as firebase_messaging is supported on web now @ditman @hterkelsen

**Comment by ditman** [comment]
> this can be closed now as firebase_messaging is supported on web now @ditman @hterkelsen
> https://pub.dev/packages/firebase_messaging/versions/9.0.0

Thanks for the note @balvinderz! This is great news!

Closing this ticket.
