### ISSUE TITLE
There are main.dart and main2.dart files in the lib directory. When I open the android project, the main.dart file is executed. How can I modify it to execute the main function in main2.dart?

### ISSUE THREAD

**Issue by Aaron009** [flutter/flutter#45312]
Such as the title？

@iapicca 

I will describe some of the details.

There are two files in the lib directory.

main.dart

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Text('Execute the code in the file `main.dart`'),
    );
  }
}
```

main2.dart

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Text('Execute the code in the file `main2.dart`'),
    );
  }
}
```

If I want to debug the `main2.dart` file, I just need to select `debug main2.dart`.
However, when I open the android project debugging, how to start from `main2.dart` instead of `main.dart`.

**Comment by iapicca** [comment]
Hi @Aaron009 
I'm not sure to understand the question,
could you please provide your updated  `flutter doctor -v`
and a minimal code sample to reproduce the problem?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
