### ISSUE TITLE
Flutter Unhandled exception:  FormatException: Unterminated string (at line 2, character 24)   "name": "PullToDismis

### ISSUE THREAD

**Issue by photoplyr** [flutter/flutter#45316]
## Steps to Reproduce

I installed flutter on my Mac mini running Catalina all the commands yield the same result

## Logs

Unhandled exception:
FormatException: Unterminated string (at line 2, character 24)
  "name": "PullToDismis
                       ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:505:9)
#2      _parseJson (dart:convert-patch/convert_patch.dart:32:10)
#3      JsonDecoder.convert (dart:convert/json.dart:495:36)
#4      JsonCodec.decode (dart:convert/json.dart:153:41)
#5      new Config (package:flutter_tools/src/base/config.dart:14:41)
#6      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:84:21)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:100:41)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:88:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:117:32)
#11     Config.instance (package:flutter_tools/src/base/config.dart:18:41)
#12     new _DefaultUsage.<anonymous closure> (package:flutter_tools/src/reporting/usage.dart:212:25)
#13     WhereIterator.moveNext (dart:_internal/iterable.dart:442:11)
#14     MappedIterator.moveNext (dart:_internal/iterable.dart:394:19)
#15     Iterable.join (dart:core/iterable.dart:364:19)
#16     new _DefaultUsage (package:flutter_tools/src/reporting/usage.dart:215:10)
#17     new Usage (package:flutter_tools/src/reporting/usage.dart:79:9)
#18     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:119:20)
#19     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:100:41)
#20     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
#21     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:88:20)
#22     AppContext.get (package:flutter_tools/src/base/context.dart:117:32)
#23     Usage.instance (package:flutter_tools/src/reporting/usage.dart:85:40)
#24     flutterUsage (package:flutter_tools/src/reporting/usage.dart:69:33)
#25     _handleToolError (package:flutter_tools/runner.dart:123:5)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:77:13)
#27     _rootRunBinary (dart:async/zone.dart:1150:13)
#28     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#29     runZoned.<anonymous closure> (dart:async/zone.dart:1481:21)
#30     _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#31     Future._propagateToListeners (dart:async/future_impl.dart:630:16)
#32     Future._completeError (dart:async/future_impl.dart:532:5)
#33     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#34     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1126:13)
#36     _CustomZone.run (dart:async/zone.dart:1023:19)
#37     _runZoned (dart:async/zone.dart:1518:10)
#38     runZoned (dart:async/zone.dart:1502:12)
#39     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#40     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#41     _rootRun (dart:async/zone.dart:1126:13)
#42     _CustomZone.run (dart:async/zone.dart:1023:19)
#43     _runZoned (dart:async/zone.dart:1518:10)
#44     runZoned (dart:async/zone.dart:1465:12)
#45     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#46     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
#47     run (package:flutter_tools/runner.dart:50:10)
#48     main (package:flutter_tools/executable.dart:65:9)
#49     main (file:///Users/troysimon/development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#50     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by jonahwilliams** [comment]
You should be able to work around this issue by deleting the file `.flutter_settings` located in $HOME directory.

**Comment by sana-git1998** [comment]
I am working on windows and i don't know where is  the file .flutter_settings Plzz  i have same issue i don't what i can do
