### ISSUE TITLE
Failed to build iOS app ** BUILD FAILED **

### ISSUE THREAD

**Issue by Zeeshan0201** [flutter/flutter#45321]
flutter run --verbose logs :- 

```
clang: error: linker command failed with exit code 1 (use -v to see invocation)
                        Showing first 200 notices only
                        Showing first 200 errors only
                    
                    
[ +992 ms] Could not build the application for the simulator.
[   +2 ms] Error launching application on iPhone X.
[   +7 ms] "flutter run" took 56,063ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:477:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#20     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**flutter doctor -v**   

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G87, locale en-IN)
    • Flutter version 1.9.1+hotfix.6 at /Users/btlmac/www/flutter
    • Framework revision 68587a0916 (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/btlmac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/btlmac/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • Lenovo X3a40 • 5453f602                             • android-arm64 • Android 6.0.1 (API 23)
    • iPhone X     • A70C38B1-AE7B-4EF5-B570-8872C81C147B • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @Zeeshan0201 
I see in you logs the error
`[ +992 ms] Could not build the application for the simulator.`
could you please provide your  `flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by Zeeshan0201** [comment]
@iapicca

**Comment by Zeeshan0201** [comment]
@ianloic _**flutter build --verbose :-**_

> [  +27 ms] executing: [/Users/mac/www/flutter/] git log -n 1 --pretty=format:%H
> [  +45 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
> [        ] 68587a0916366e9512a78df22c44163d041dd5f3
> [        ] executing: [/Users/btlmac/www/flutter/] git describe --match v*.*.* --first-parent --long --tags
> [  +10 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
> [        ] v1.9.1+hotfix.6-0-g68587a091
> [   +9 ms] executing: [/Users/btlmac/www/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
> [  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [        ] origin/stable
> [        ] executing: [/Users/btlmac/www/flutter/] git ls-remote --get-url origin
> [  +10 ms] Exit code 0 from: git ls-remote --get-url origin
> [   +1 ms] https://github.com/flutter/flutter.git

**Comment by Zeeshan0201** [comment]
@ianloic _**flutter build --verbose :-**_

> [  +27 ms] executing: [/Users/mac/www/flutter/] git log -n 1 --pretty=format:%H
> [  +45 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
> [        ] 68587a0916366e9512a78df22c44163d041dd5f3
> [        ] executing: [/Users/mac/www/flutter/] git describe --match v*.*.* --first-parent --long --tags
> [  +10 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
> [        ] v1.9.1+hotfix.6-0-g68587a091
> [   +9 ms] executing: [/Users/mac/www/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
> [  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [        ] origin/stable
> [        ] executing: [/Users/mac/www/flutter/] git ls-remote --get-url origin
> [  +10 ms] Exit code 0 from: git ls-remote --get-url origin
> [   +1 ms] https://github.com/flutter/flutter.git

**Comment by iapicca** [comment]
Hi @Zeeshan0201 
can you please check if this [solution](https://github.com/flutter/flutter/issues/18305#issuecomment-395937372) works for you?
thank you

**Comment by Zeeshan0201** [comment]
@iapicca okay,checking

**Comment by Zeeshan0201** [comment]
@iapicca I did the deployment targets the same 11.2 of All project file and the pods project, but still getting the same errors...

**Comment by Zeeshan0201** [comment]
@iapicca my iOS related build issue solved in project after adding a Swift Pods library...
id anyone is getting the same issue please check this for further information,
`https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios`
 Thanks.

**Comment by Zeeshan0201** [comment]
@iapicca my iOS related build issue solved in the project after adding a Swift Pods library...
id anyone is getting the same issue please check this for further information,
https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios
Thanks.

**Comment by Zeeshan0201** [comment]
@iapicca my iOS related build issue solved in the project after adding a Swift Pods library...
if anyone is getting the same issue please check this for further information,
https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios
Thanks.
