### ISSUE TITLE
 'package:flutter/src/scheduler/binding.dart': Failed assertion: line 325 pos 12: 'state != null': is I/flutter (15890): not true.

### ISSUE THREAD

**Issue by zhanghepeng** [flutter/flutter#45328]
PS D:\Code\flutter\project\jd> flutter doctor
Waiting for another flutter command to release the startup lock...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.12.6-pre.13, on Microsoft Windows [Version 10.0.18362.476], locale zh-CN)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] VS Code (version 1.40.1)
[√] Connected device (3 available)

• No issues found!
PS D:\Code\flutter\project\jd> flutter run
Launching lib\main.dart on M6 Note in debug mode...
I/flutter (15890): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter (15890): The following assertion was thrown during a platform message callback:
I/flutter (15890): 'package:flutter/src/scheduler/binding.dart': Failed assertion: line 325 pos 12: 'state != null': is
I/flutter (15890): not true.
I/flutter (15890): 
I/flutter (15890): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (15890): more information in this error message to help you determine and fix the underlying cause.
I/flutter (15890): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (15890):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (15890):
I/flutter (15890): When the exception was thrown, this was the stack:
I/flutter (15890): #2      SchedulerBinding.handleAppLifecycleStateChanged (package:flutter/src/scheduler/binding.dart:325:12)
I/flutter (15890): #3      WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:543:11)
I/flutter (15890): #4      SchedulerBinding._handleLifecycleMessage (package:flutter/src/scheduler/binding.dart:341:5)
I/flutter (15890): #5      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
I/flutter (15890): #6      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
I/flutter (15890): #7      _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
I/flutter (15890): #11     _invoke3 (dart:ui/hooks.dart:302:10)
I/flutter (15890): #12     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)
I/flutter (15890): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (15890): ════════════════════════════════════════════════════════════════════════════════════════════════════
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        51.3s
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                         8.7s
Syncing files to device M6 Note...                                      
 7,637ms (!)

�🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on M6 Note is available at: http://127.0.0.1:56627/-BBxfBmLOBU=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

**Comment by iapicca** [comment]
Hi @zhanghepeng 
the error in your logs 
```
I/flutter (15890): 'package:flutter/src/scheduler/binding.dart': Failed assertion: line 325 pos 12: 'state != null': is
I/flutter (15890): not true.
```
suggests that there might be a problem with your code,
could you please provide a minimal code sample to reproduce the problem
Thank you

**Comment by zhanghepeng** [comment]
> Hi @zhanghepeng
> the error in your logs
> 
> ```
> I/flutter (15890): 'package:flutter/src/scheduler/binding.dart': Failed assertion: line 325 pos 12: 'state != null': is
> I/flutter (15890): not true.
> ```
> 
> suggests that there might be a problem with your code,
> could you please provide a minimal code sample to reproduce the problem
> Thank you

Hi @iapicca Thankyou
I think it should be the problem caused by the environment configuration after I upgrade. But when I use flutter create test to create a new project, the error still exists. I reconfigured the flutter to try. thank you very much.
