### ISSUE TITLE
The problem of CPU usage rate?

### ISSUE THREAD

**Issue by beydeng** [flutter/flutter#45322]
As I run my Flutter App,the CPU usage rate is Over 50%.
The Main problems is io.flutter.1.gpu.

**Comment by iapicca** [comment]
Hi @beydeng 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by Hixie** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
