### ISSUE TITLE
Questions about picture resources

### ISSUE THREAD

**Issue by mengzhidaren** [flutter/flutter#45326]
```
官方文档的不是很明白;
声明分辨率相关的图片 assets 时 
在 文件夹里创建的2.0x和3.0x文件夹逻辑问题 
```
Official documents are not very clear;
When declaring resolution dependent image assets
Logical problems with 2.0x and 3.0x folders created in folders

…/images/heart.png
…/images/1.5x/heart.png
…/images/2.0x/heart.png
…/images/3.0x/heart.png

```
第一个问题是： 现在有4个不同倍数的图片
默认是的1.0x的图片资源， 那么我能否只放入 3.0x的 heart.png 资源图片
目前我测试好像是不行，这里必须放入1.0x的图片吗 
第二个问题是： 如果增加了iphone目录,是在同级目录下提供 2倍图和 3倍图吗
```
The first question is: now there are four different multiple images
The default is the 1.0x picture resource of, so can I only put in the 3.0x heart.png resource picture
At present, it seems that I can't test it. Do I have to put a 1.0x picture here
The second question is: if the iPhone directory is added, do you provide 2-fold and 3-fold graphs in the same level directory

…/images/iphone/heart.png
…/images/iphone/2.0x/heart.png
…/images/iphone/3.0x/heart.png
…/images/ipad/heart.png
…/images/ipad/2.0x/heart.png
…/images/ipad/3.0x/heart.png

`第三个问题是：  必须在pubspec.yaml里面注册2倍图和 3倍图吗`

The third question is: must you register 2-fold and 3-fold graphs in pubspec.yaml

 - assets/images/iphone/2.0x/
 - assets/images/iphone/3.0x/

**Comment by iapicca** [comment]
Hi @mengzhidaren 
I'm not sure which documentation you are referring to,
is it one of these? [ [1](https://flutter.dev/docs/development/ui/assets-and-images), [2](https://flutter.dev/docs/development/ui/assets-and-images) ]
thank you

**Comment by mengzhidaren** [comment]
@iapicca    Thank you for your answer
