### ISSUE TITLE
[flutter_test] Because hello_world depends on flutter_test any from sdk which depends on test_api 0.2.5, test_api

### ISSUE THREAD

**Issue by kossa** [flutter/flutter#45335]
Hello,

After clone the flutter/flutter, when I try to execute : `flutter run` in hello_world folder I get this error :

![image](https://user-images.githubusercontent.com/1175584/69330955-3a1d3400-0c54-11ea-9842-7c5e51381e24.png)

By the way : `flutter doctor` 

![image](https://user-images.githubusercontent.com/1175584/69330864-10640d00-0c54-11ea-954e-bf4ed6678762.png)

**Comment by iapicca** [comment]
Hi @kossa 
could you please provide your `flutter run --verbose`?
Thank you

**Comment by kossa** [comment]
flutter run --verbose        


[  +26 ms] executing: [/Users/mac/development/flutter/] git log -n 1 --pretty=format:%H
[  +45 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 68587a0916366e9512a78df22c44163d041dd5f3
[        ] executing: [/Users/mac/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +14 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.9.1+hotfix.6-0-g68587a091
[   +9 ms] executing: [/Users/mac/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/mac/development/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +56 ms] executing: [/Users/mac/development/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +173 ms] executing: /Users/mac/Library/Android/sdk/platform-tools/adb devices -l
[  +13 ms] Exit code 0 from: /Users/mac/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5556          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:2
[  +21 ms] executing: /Users/mac/development/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +56 ms] /Users/mac/Library/Android/sdk/platform-tools/adb -s emulator-5556 shell getprop
[  +49 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +20 ms] Running "flutter pub get" in hello_world...
[   +6 ms] Using /Users/mac/development/flutter/.pub-cache for the pub cache.
[   +1 ms] executing: [/Users/mac/code/github-project/flutter/examples/hello_world/]
/Users/mac/development/flutter/bin/cache/dart-sdk/bin/pub --verbose get --no-precompile
[  +99 ms] FINE: Pub 2.5.0
[  +82 ms] MSG : Resolving dependencies...
[   +9 ms] SLVR: fact: hello_world is 0.0.0
[   +4 ms] SLVR: derived: hello_world
[  +26 ms] SLVR: fact: hello_world depends on vector_math 2.0.8
[        ] SLVR: fact: hello_world depends on collection 1.14.11
[        ] SLVR: fact: hello_world depends on flutter any from sdk
[        ] SLVR: fact: hello_world depends on typed_data 1.1.6
[        ] SLVR: fact: hello_world depends on meta 1.1.8
[        ] SLVR: fact: hello_world depends on quiver 2.0.5
[        ] SLVR: fact: hello_world depends on async 2.4.0
[        ] SLVR: fact: hello_world depends on args 1.5.2
[        ] SLVR: fact: hello_world depends on petitparser 2.4.0
[        ] SLVR: fact: hello_world depends on crypto 2.1.3
[        ] SLVR: fact: hello_world depends on charcode 1.1.2
[        ] SLVR: fact: hello_world depends on matcher 0.12.6
[        ] SLVR: fact: hello_world depends on xml 3.5.0
[        ] SLVR: fact: hello_world depends on stack_trace 1.9.3
[        ] SLVR: fact: hello_world depends on convert 2.1.1
[        ] SLVR: fact: hello_world depends on archive 2.0.11
[        ] SLVR: fact: hello_world depends on flutter_test any from sdk
[        ] SLVR: fact: hello_world depends on pedantic 1.8.0+1
[        ] SLVR: fact: hello_world depends on term_glyph 1.1.0
[        ] SLVR: fact: hello_world depends on stream_channel 2.0.0
[        ] SLVR: fact: hello_world depends on boolean_selector 1.0.5
[        ] SLVR: fact: hello_world depends on path 1.6.4
[        ] SLVR: fact: hello_world depends on image 2.1.4
[        ] SLVR: fact: hello_world depends on test_api 0.2.11
[        ] SLVR: fact: hello_world depends on source_span 1.5.5
[        ] SLVR: fact: hello_world depends on string_scanner 1.0.5
[        ] SLVR:   selecting hello_world
[        ] SLVR:   derived: string_scanner 1.0.5
[        ] SLVR:   derived: source_span 1.5.5
[        ] SLVR:   derived: test_api 0.2.11
[        ] SLVR:   derived: image 2.1.4
[        ] SLVR:   derived: path 1.6.4
[        ] SLVR:   derived: boolean_selector 1.0.5
[        ] SLVR:   derived: stream_channel 2.0.0
[        ] SLVR:   derived: term_glyph 1.1.0
[        ] SLVR:   derived: pedantic 1.8.0+1
[        ] SLVR:   derived: flutter_test any from sdk
[        ] SLVR:   derived: archive 2.0.11
[        ] SLVR:   derived: convert 2.1.1
[        ] SLVR:   derived: stack_trace 1.9.3
[        ] SLVR:   derived: xml 3.5.0
[        ] SLVR:   derived: matcher 0.12.6
[        ] SLVR:   derived: charcode 1.1.2
[        ] SLVR:   derived: crypto 2.1.3
[        ] SLVR:   derived: petitparser 2.4.0
[        ] SLVR:   derived: args 1.5.2
[        ] SLVR:   derived: async 2.4.0
[        ] SLVR:   derived: quiver 2.0.5
[        ] SLVR:   derived: meta 1.1.8
[        ] SLVR:   derived: typed_data 1.1.6
[        ] SLVR:   derived: flutter any from sdk
[        ] SLVR:   derived: collection 1.14.11
[        ] SLVR:   derived: vector_math 2.0.8
[   +4 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/test_api.
[  +29 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/test_api
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: macos
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: AF4C8C0C-E1D3-4970-AF67-3F1FE50A7BF4
[        ]     | X-Pub-Environment: flutter_cli:verify:run
[        ]     | X-Pub-Reason: dev
[        ]     | user-agent: Dart pub 2.5.0
[+1476 ms] IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/test_api
[        ]     | took 0:00:01.475474
[        ]     | transfer-encoding: chunked
[        ]     | date: Thu, 21 Nov 2019 12:00:56 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[  +40 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/image.
[        ] IO  : HTTP GET https://pub.dartlang.org/api/packages/image
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: macos
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: AF4C8C0C-E1D3-4970-AF67-3F1FE50A7BF4
[        ]     | X-Pub-Environment: flutter_cli:verify:run
[        ]     | X-Pub-Reason: dev
[        ]     | user-agent: Dart pub 2.5.0
[ +386 ms] IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/image
[        ]     | took 0:00:00.387367
[        ]     | transfer-encoding: chunked
[        ]     | date: Thu, 21 Nov 2019 12:00:57 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[  +18 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/matcher.
[        ] IO  : HTTP GET https://pub.dartlang.org/api/packages/matcher
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: macos
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: AF4C8C0C-E1D3-4970-AF67-3F1FE50A7BF4
[        ]     | X-Pub-Environment: flutter_cli:verify:run
[        ]     | X-Pub-Reason: dev
[        ]     | user-agent: Dart pub 2.5.0
[ +237 ms] IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/matcher
[        ]     | took 0:00:00.238293
[        ]     | transfer-encoding: chunked
[        ]     | date: Thu, 21 Nov 2019 12:00:57 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[  +90 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/quiver.
[        ] IO  : HTTP GET https://pub.dartlang.org/api/packages/quiver
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: macos
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: AF4C8C0C-E1D3-4970-AF67-3F1FE50A7BF4
[        ]     | X-Pub-Environment: flutter_cli:verify:run
[        ]     | X-Pub-Reason: dev
[        ]     | user-agent: Dart pub 2.5.0
[ +343 ms] IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/quiver
[        ]     | took 0:00:00.344444
[        ]     | transfer-encoding: chunked
[        ]     | date: Thu, 21 Nov 2019 12:00:57 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[   +9 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/meta.
[        ] IO  : HTTP GET https://pub.dartlang.org/api/packages/meta
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: macos
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: AF4C8C0C-E1D3-4970-AF67-3F1FE50A7BF4
[        ]     | X-Pub-Environment: flutter_cli:verify:run
[        ]     | X-Pub-Reason: direct
[        ]     | user-agent: Dart pub 2.5.0
[ +211 ms] IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/meta
[        ]     | took 0:00:00.211955
[        ]     | transfer-encoding: chunked
[        ]     | date: Thu, 21 Nov 2019 12:00:58 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[  +26 ms] SLVR:   fact: string_scanner 1.0.5 depends on charcode ^1.1.0
[        ] SLVR:   fact: string_scanner 1.0.5 depends on source_span ^1.4.0
[        ] SLVR:   fact: string_scanner 1.0.5 depends on meta ^1.1.0
[        ] SLVR:     selecting string_scanner 1.0.5
[   +4 ms] SLVR:     fact: source_span 1.5.5 depends on charcode ^1.0.0
[        ] SLVR:     fact: source_span 1.5.5 depends on term_glyph ^1.0.0
[        ] SLVR:     fact: source_span 1.5.5 depends on path ^1.2.0
[        ] SLVR:       selecting source_span 1.5.5
[  +16 ms] SLVR:       fact: test_api >=0.2.5 depends on async ^2.0.0
[        ] SLVR:       fact: every version of test_api depends on boolean_selector ^1.0.0
[        ] SLVR:       fact: every version of test_api depends on collection ^1.8.0
[        ] SLVR:       fact: test_api >=0.2.10 depends on matcher >=0.12.6 <0.12.7
[        ] SLVR:       fact: every version of test_api depends on meta ^1.1.5
[        ] SLVR:       fact: every version of test_api depends on path ^1.2.0
[        ] SLVR:       fact: test_api >=0.2.2 depends on pedantic ^1.0.0
[        ] SLVR:       fact: every version of test_api depends on source_span ^1.4.0
[        ] SLVR:       fact: every version of test_api depends on stack_trace ^1.9.0
[        ] SLVR:       fact: test_api >=0.2.4 depends on stream_channel >=1.7.0 <3.0.0
[        ] SLVR:       fact: test_api >=0.2.5 depends on string_scanner ^1.0.0
[        ] SLVR:       fact: every version of test_api depends on term_glyph ^1.0.0
[        ] SLVR:         selecting test_api 0.2.11
[   +5 ms] SLVR:         fact: image >=2.0.4 depends on archive >=1.0.16 <3.0.0
[        ] SLVR:         fact: image >=2.0.6 depends on xml ^3.2.5
[        ] SLVR:           selecting image 2.1.4
[   +4 ms] SLVR:             selecting path 1.6.4
[   +4 ms] SLVR:             fact: boolean_selector 1.0.5 depends on source_span ^1.0.0
[        ] SLVR:             fact: boolean_selector 1.0.5 depends on string_scanner >=0.1.1 <2.0.0
[        ] SLVR:               selecting boolean_selector 1.0.5
[   +4 ms] SLVR:               fact: stream_channel 2.0.0 depends on async >=1.11.0 <3.0.0
[        ] SLVR:                 selecting stream_channel 2.0.0
[   +2 ms] SLVR:                   selecting term_glyph 1.1.0
[   +2 ms] SLVR:                     selecting pedantic 1.8.0+1
[   +6 ms] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on quiver 2.1.2+1
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on async 2.4.0
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on collection 1.14.11
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on typed_data 1.1.6
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on meta 1.1.7
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on charcode 1.1.2
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on matcher 0.12.5
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on stack_trace 1.9.3
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on pedantic 1.8.0+1
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on term_glyph 1.1.0
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on stream_channel 2.0.0
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on path 1.6.4
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on flutter any from sdk
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on boolean_selector 1.0.5
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on test_api 0.2.5
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on source_span 1.5.5
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on vector_math 2.0.8
[        ] SLVR:                     fact: flutter_test 0.0.0 from sdk depends on string_scanner 1.0.5
[        ] SLVR:                     derived: not flutter_test 0.0.0 from sdk
[   +6 ms] SLVR:                     fact: every version of flutter_test from sdk depends on async 2.4.0
[        ] SLVR:                     fact: every version of flutter_test from sdk depends on boolean_selector 1.0.5
[        ] SLVR:                     fact: every version of flutter_test from sdk depends on charcode 1.1.2
[        ] SLVR:                     fact: every version of flutter_test from sdk depends on collection 1.14.11
[        ] SLVR:                     fact: every version of flutter_test from sdk depends on flutter any from sdk
[   +1 ms] SLVR:                     fact: every version of flutter_test from sdk depends on matcher 0.12.5
[        ] SLVR:                     fact: every version of flutter_test from sdk depends on meta 1.1.7
[        ] SLVR:                     fact: every version of flutter_test from sdk depends on path 1.6.4
[        ] SLVR:                     fact: every version of flutter_test from sdk depends on pedantic 1.8.0+1
[        ] SLVR:                     fact: every version of flutter_test from sdk depends on quiver 2.1.2+1
[        ] SLVR:                     fact: every version of flutter_test from sdk depends on source_span 1.5.5
[        ] SLVR:                     fact: every version of flutter_test from sdk depends on stack_trace 1.9.3
[        ] SLVR:                     fact: every version of flutter_test from sdk depends on stream_channel 2.0.0
[        ] SLVR:                     fact: every version of flutter_test from sdk depends on string_scanner 1.0.5
[        ] SLVR:                     fact: every version of flutter_test from sdk depends on term_glyph 1.1.0
[        ] SLVR:                     fact: every version of flutter_test from sdk depends on test_api 0.2.5
[        ] SLVR:                     fact: every version of flutter_test from sdk depends on typed_data 1.1.6
[        ] SLVR:                     fact: every version of flutter_test from sdk depends on vector_math 2.0.8
[        ] SLVR:                     conflict: every version of flutter_test from sdk depends on test_api 0.2.5
[   +1 ms] SLVR:                     ! flutter_test any from sdk is satisfied by flutter_test any from sdk
[        ] SLVR:                     ! which is caused by "hello_world depends on flutter_test any from sdk"
[        ] SLVR:                     ! thus: test_api 0.2.5 is required
[        ] SLVR:                     ! not test_api 0.2.5 is satisfied by test_api 0.2.11
[        ] SLVR:                     ! which is caused by "hello_world depends on test_api 0.2.11"
[        ] SLVR:                     ! thus: version solving failed
[   +1 ms] SLVR: Version solving took 0:00:03.018028 seconds.
[        ]     | Tried 1 solutions.
[   +1 ms] FINE: Resolving dependencies finished (3.024s).
[  +13 ms] ERR : Because hello_world depends on flutter_test any from sdk which depends on test_api 0.2.5, test_api
0.2.5 is required.
[        ]     | So, because hello_world depends on test_api 0.2.11, version solving failed.
[        ] FINE: Exception type: SolveFailure
[  +18 ms] FINE: package:pub/src/solver/version_solver.dart 308:5   VersionSolver._resolveConflict
[        ]     | package:pub/src/solver/version_solver.dart 131:27  VersionSolver._propagate
[        ]     | package:pub/src/solver/version_solver.dart 96:9    VersionSolver.solve
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                         Future.catchError
[        ]     | package:pub/src/utils.dart 109:52                  captureErrors.<fn>
[        ]     | package:stack_trace                                Chain.capture
[        ]     | package:pub/src/utils.dart 122:11                  captureErrors
[        ]     | package:pub/src/command_runner.dart 171:13         PubCommandRunner.runCommand
[  +24 ms] Running "flutter pub get" in hello_world... (completed in 3.3s)
[   +1 ms] "flutter run" took 3,631ms.
pub get failed (1)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      pub (package:flutter_tools/src/dart/pub.dart:174:5)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:106:13)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:474:13)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CommandRunner.run (package:args/command_runner.dart:112:14)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1500:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:50:10)
#39     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#40     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by iapicca** [comment]
Hi @kossa 
sorry I just noticed the error before,
could you please complete the Xcode installation as suggest
in your` flutter doctor -v`?
thank you

**Comment by kossa** [comment]
So I cannot use only android emulator ?

**Comment by iapicca** [comment]
@kossa sure you can

**Comment by jonahwilliams** [comment]
This is not broken in the version you've shared, which means that you've either modified the example's pubspec or are using a different version of flutter to run the example (not the same SDK). Neither use case is supported.
