### ISSUE TITLE
ImagePicker: ImageSource should support both Camera+Gallery

### ISSUE THREAD

**Issue by fralways** [flutter/flutter#45332]
## Use case

Most apps nowadays require picker to handle both camera and gallery within the same picker. Common use case is when user wants to add a profile image. He is 99% of the time unsure what image to select so he usually tries to take a few selfies and if that doesn't work he falls back to gallery. That being said this image picker would require him to select first camera source, then tries to take selfie couple of times, he fails and then he needs to quit that, and start again as a gallery. This is time consuming and very bad experience for the user.

## Proposal

ImageSource should support another option, let's call it "both", which will support both camera and gallery source within the same picker. The looks should be same/similar to as it is selected gallery source, but first grid cell should be camera which should be either static or dynamic. If it's static then we should be able to style that cell, and if it's dynamic then it should show real time camera feed. After clicking on that cell we should be either presented with fullscreen camera or it should take photo right away. Best would be that everything is customizable since use cases differ.

**Comment by lucasmaffazioli** [comment]
This is the default behavior of every app. You want to post a picture you can either select from your phone or take a pic in the spot. This feature is essential.

**Comment by stuartmorgan** [comment]
The UI shown by image_picker is native UI; if you want different UI you would need to either file a feature request against the OS developer, or build your own custom UI in Flutter.

Is the UI you are describing available as a system component on either iOS or Android?

**Comment by fralways** [comment]
I will close this since it's outdated at this point. If any1 else feels there's need for this feel free to open a new ticket.
