### ISSUE TITLE
[in_app_purchase] Restore Purchase Feature 

### ISSUE THREAD

**Issue by mhd-barikhan** [flutter/flutter#45333]
we need to add restore purchase feature to this plugin.

**Comment by phatwerk** [comment]
Isn't it already available?
I believe its a matter of how you introduce it in your app.

You can call queryPastPurchases on-demand or once your app is initialized and update accordingly the content of your app.

**Comment by minhvuongrbs** [comment]
If you are running on IOS, just call `SKPaymentQueueWrapper().restoreTransactions()` from `store_kit_wrappers`. 
With Android, it seems like doesn't support it. Can get past purchases and check if hasn't => trigger update subscription for customers

**Comment by luiscruzurvenue** [comment]
Any news on this feature?

**Comment by poqueque** [comment]
> If you are running on IOS, just call `SKPaymentQueueWrapper().restoreTransactions()` from `store_kit_wrappers`.

@minhvuongrbs Did you manage to make it work? I call `SKPaymentQueueWrapper().restoreTransactions()` but the `SKTransactionObserverWrapper.paymentQueueRestoreCompletedTransactionsFinished` is called but `shouldAddStorePayment` is not called. 
How can this be tested with Sandbox purchases? Is there any implementation sample?

**Comment by uzumaki258** [comment]
New features to acquire and retain subscribers.
On November 1, 2020, account hold and subscription restore will become mandatory. Subscription pause and resubscribe will also be enabled for all apps.

image
For more detail please check it:
https://android-developers.googleblog.com/2020/06/new-features-to-acquire-and-retain-subscribers.html
 Can we have this Feature with Flutter?

**Comment by erperejildo** [comment]
Any update?

**Comment by uzumaki258** [comment]
7 days left. I hope Google will give more time for app using Flutter.

**Comment by danReynolds** [comment]
So what happened? are people's apps just getting rejected now?

**Comment by uzumaki258** [comment]
I think we have to use server-side verify to do this.

**Comment by erperejildo** [comment]
> I think we have to use server-side verify to do this.

I use Firebase for my app

**Comment by danReynolds** [comment]
> > I think we have to use server-side verify to do this.
> 
> I use Firebase for my app

Right, but we have to use cloud functions to handle it. I worked on it today and used a pub/sub function to read subscription publish events and write those to cloud firestore as needed. Happy to discuss more if interested.

**Comment by uzumaki258** [comment]
> > > I think we have to use server-side verify to do this.
> > 
> > 
> > I use Firebase for my app
> 
> Right, but we have to use cloud functions to handle it. I worked on it today and used a pub/sub function to read subscription publish events and write those to cloud firestore as needed. Happy to discuss more if interested.

Make sure you have to background service to query subscription have been renewed recently.

**Comment by erperejildo** [comment]
> > > I think we have to use server-side verify to do this.
> > 
> > 
> > I use Firebase for my app
> 
> Right, but we have to use cloud functions to handle it. I worked on it today and used a pub/sub function to read subscription publish events and write those to cloud firestore as needed. Happy to discuss more if interested.

Thanks but I think that having Flutter, Firebase, Google Play in-app purchases... with Google, they should provide a specific tutorial for this if having the server-side verification is the way to go. They can't leave us without documentation here

**Comment by danReynolds** [comment]
> > > > I think we have to use server-side verify to do this.
> 
> > > 
> 
> > > 
> 
> > > I use Firebase for my app
> 
> > 
> 
> > Right, but we have to use cloud functions to handle it. I worked on it today and used a pub/sub function to read subscription publish events and write those to cloud firestore as needed. Happy to discuss more if interested.
> 
> 
> 
> Thanks but I think that having Flutter, Firebase, Google Play in-app purchases... with Google, they should provide a specific tutorial for this if having the server-side verification is the way to go. They can't leave us without documentation here

There's docs but it isn't in tutorial format, you need to combine some stuff. I can write up a blog post going through the steps, will get back to you

**Comment by thruthesky** [comment]
> > > > > I think we have to use server-side verify to do this.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I use Firebase for my app
> > 
> > 
> > > 
> > 
> > 
> > > Right, but we have to use cloud functions to handle it. I worked on it today and used a pub/sub function to read subscription publish events and write those to cloud firestore as needed. Happy to discuss more if interested.
> > 
> > 
> > Thanks but I think that having Flutter, Firebase, Google Play in-app purchases... with Google, they should provide a specific tutorial for this if having the server-side verification is the way to go. They can't leave us without documentation here
> 
> There's docs but it isn't in tutorial format, you need to combine some stuff. I can write up a blog post going through the steps, will get back to you

Oh, please. That will help a lot of flutter developers.

**Comment by uzumaki258** [comment]
> > > > > I think we have to use server-side verify to do this.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I use Firebase for my app
> > 
> > 
> > > 
> > 
> > 
> > > Right, but we have to use cloud functions to handle it. I worked on it today and used a pub/sub function to read subscription publish events and write those to cloud firestore as needed. Happy to discuss more if interested.
> > 
> > 
> > Thanks but I think that having Flutter, Firebase, Google Play in-app purchases... with Google, they should provide a specific tutorial for this if having the server-side verification is the way to go. They can't leave us without documentation here
> 
> There's docs but it isn't in tutorial format, you need to combine some stuff. I can write up a blog post going through the steps, will get back to you

I am waiting for that. Thank for your help

**Comment by aribanigar034** [comment]
Ok

**Comment by danReynolds** [comment]
Hey all, been busy lately so didn't get to writing anything up until today. [Here's a quick](https://danreynolds.ca/tech/2020/12/02/Flutter-Google-Billing/), it defers to the docs on some things so let me know if you need more details on anything in particular. I can elaborate further in the future when I get more time. Hope this helps out somewhat at least!
