### ISSUE TITLE
webview_flutter: Setting the request header 'cookie' doesn't work

### ISSUE THREAD

**Issue by rbocobo** [flutter/flutter#45341]
I'm trying to set the header 'cookie' through the loadUrl method of webViewController. It doesn't work, but it does work for other headers. Am I missing something? Do I have to enable cookies somewhere?

`onWebViewCreated: (WebViewController webViewController) {
          Map<String, String> header = {'Cookie': '$sessionid'};
          Uri url = Uri.parse('https://target.website.com/Welcome.do');
           webViewController.loadUrl(url.toString(),
              headers: header);
          _controller.complete(webViewController);
        }`

**Comment by TahaTesser** [comment]
Hi @rbocobo 
Are you still experiencing this issue with latest stable?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @rbocobo 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
