### ISSUE TITLE
webview_flutter: Input Keyboard not showing - IOS 

### ISSUE THREAD

**Issue by NicoAlani** [flutter/flutter#45344]
We encontered a problem in IOS, we have tested many webview packages from https://pub.dev/ (like [https://pub.dev/packages/webview_flutter](https://pub.dev/packages/webview_flutter) and https://pub.dev/packages/flutter_webview_plugin and https://pub.dev/packages/flutter_inappbrowser) and all the solutions ends with the same result. When the innapp website opens, it loads perfectly, but when you interact with an input, the keyboard doesn't seems show up, it occurs in all the inputs from all the pages.

Thanks in advance!.

[IMAGE ](https://imgur.com/a/H4KImYy) of the error

The error log output is:

 Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing `NSAutoresizingMaskLayoutConstraints` that you don't understand, refer to the documentation for the `UIView property translatesAutoresizingMaskIntoConstraints) (    "<NSAutoresizingMaskLayoutConstraint:0x6040004826c0 h=-&- v=-&- UIToolbar:0x7fcec747c950.width == _UIInputViewContent:0x7fcec74aede0.width   (active)>",    "<NSAutoresizingMaskLayoutConstraint:0x600000487440 h=--& v=--& _UIInputViewContent:0x7fcec74aede0.width == 0   (active)>",    "<NSLayoutConstraint:0x6000004839d0 H:|-(0)-[_UIButtonBarStackView:0x7fcec74bfd40]   (active, names: '|':_UIToolbarContentView:0x7fcec743d460 )>",    "<NSLayoutConstraint:0x600000483a70 _UIButtonBarStackView:0x7fcec74bfd40.trailing == _UIToolbarContentView:0x7fcec743d460.trailing + 8   (active)>",    "<NSLayoutConstraint:0x6000004845b0 _UIToolbarContentView:0x7fcec743d460.trailing == UIToolbar:0x7fcec747c950.trailing   (active)>",    "<NSLayoutConstraint:0x60000009f1d0 H:|-(0)-[_UIToolbarContentView:0x7fcec743d460]   (active, names: '|':UIToolbar:0x7fcec747c950 )>",    "<NSLayoutConstraint:0x604000480730 H:|-(>=5)-[_UIModernBarButton:0x7fcec75b34b0]   (active, names: '|':_UIButtonBarButton:0x7fcec75b2e40 )>",    "<NSLayoutConstraint:0x604000480780 H:[_UIModernBarButton:0x7fcec75b34b0]-(>=5)-|   (active, names: '|':_UIButtonBarButton:0x7fcec75b2e40 )>",    "<NSLayoutConstraint:0x604000481310 H:|-(8)-[_UIModernBarButton:0x7fcec75b4060'Done']   (active, names: '|':_UIButtonBarButton:0x7fcec75b39d0 )>",    "<NSLayoutConstraint:0x604000481360 H:[_UIModernBarButton:0x7fcec75b4060'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x7fcec75b39d0 )>",`

**Comment by iapicca** [comment]
Hi @NicoAlani 
please consider that 
[flutter_webview_plugin](https://pub.dev/packages/flutter_webview_plugin) [ [github](https://github.com/fluttercommunity/flutter_webview_plugin/issues) ] and [flutter_inappbrowser](https://pub.dev/packages/flutter_inappbrowser) [ [github](https://github.com/pichillilorenzo/flutter_inappbrowser/issues) ]
are 3rd party plugins and you might want to open an issue on the respective github page.

For the [webview_flutter](https://pub.dev/packages/webview_flutter)
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by pichillilorenzo** [comment]
@NicoAlani I released the new version **2.0.1** of [flutter_inappwebview](https://github.com/pichillilorenzo/flutter_inappwebview) (**flutter_inappwebview** is the new name of the old **flutter_inappbrowser**) with a lot of new events, options and methods! You try it and let me know. 
However, as @iapicca said, open an issue to the corresponding github issue page!

**Comment by fedotxxl** [comment]
Hello. I had the same problem with the simulator. The following - https://stackoverflow.com/a/30142114/716027 - helped me

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
