### ISSUE TITLE
I have a problem with android studio while running flutter apps??

### ISSUE THREAD

**Issue by OmarBakry-eg** [flutter/flutter#45340]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> Failed to obtain compression information for entry

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Picked up _JAVA_OPTIONS: -Xmx256M
Finished with error: Gradle task assembleDebug failed with exit code 1
 
<< or >> 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> Java heap space 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Picked up _JAVA_OPTIONS: -Xmx256M
Finished with error: Gradle task assembleDebug failed with exit code 1
===================
I Need any help because I don't know what should i do right now  even after searching i didn't find anything useful to solve this problem!!?

**Comment by iapicca** [comment]
Hi @OmarBakry-eg 
could you please provide your updated  `flutter doctor -v`
and your `flutter build --verbose` ?
Thank you

**Comment by Hixie** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by AlusineFix** [comment]
Since this started showing when i upgraded my flutter, the Sqflite app data does not persist whenever i close and restart, I don't really know whats causing this...... Kindly assist me.

Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/alusine/.var/app/com.google.AndroidStudio/cache
