### ISSUE TITLE
webview_flutter compile error: Lint found errors because webView.setWebContentsDebuggingEnabled

### ISSUE THREAD

**Issue by lavnFan** [flutter/flutter#45342]
when include webview_flutter, compile error:

* What went wrong:
Execution failed for task ':webview_flutter:lint'.
> Lint found errors in the project; aborting build.
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

webview_flutter 0.3.15+1/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java:253: Error: Call requires API level 19 (current min is 16): android.webkit.WebView#setWebContentsDebuggingEnabled [NewApi]
            webView.setWebContentsDebuggingEnabled(debuggingEnabled);
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

how can I compile when my min is 16?

**Comment by iapicca** [comment]
Hi @lavnFan 
could you please provide your updated  `flutter doctor -v`
and your `flutter build --verbose` ?
Thank you

**Comment by lavnFan** [comment]
flutter docker -v:
![image](https://user-images.githubusercontent.com/10785365/69346313-89dc1980-0cad-11ea-97a3-12811e389ab2.png)

cause:
in android wenview_flutter, it seems not judge api level to use?
![image](https://user-images.githubusercontent.com/10785365/69346357-982a3580-0cad-11ea-8f96-bce326b7556f.png)

**Comment by lavnFan** [comment]
> Hi @lavnFan
> could you please provide your updated `flutter doctor -v`
> and your `flutter build --verbose` ?
> Thank you

flutter docker -v:
![image](https://user-images.githubusercontent.com/10785365/69346461-c576e380-0cad-11ea-9669-da765d80b44c.png)


cause:
in android wenview_flutter, it seems not judge api level to use?
![image](https://user-images.githubusercontent.com/10785365/69346483-ce67b500-0cad-11ea-9fb2-2c692ab1af07.png)

**Comment by lavnFan** [comment]
> Hi @lavnFan
> could you please provide your updated `flutter doctor -v`
> and your `flutter build --verbose` ?
> Thank you

if I want to use webview_flutter, and fix the compile error, I'm afraind to hava to use the webview_flutter local and add api level judge, like this:
![image](https://user-images.githubusercontent.com/10785365/69390951-233a1880-0d0c-11ea-9b4b-6274c9da7fda.png)
![image](https://user-images.githubusercontent.com/10785365/69390966-2f25da80-0d0c-11ea-8362-4cd09dd54a4c.png)

hope this can merge request to the repo, so that I can use just include in yaml.

**Comment by amrox** [comment]
I am seeing this on the latest release at time of writing - 0.3.19+3.

The minSdkVersion in my app is 21, but it seems like the plugin is building with 16.

Also setting `abortOnError false` in my project doesn't work.

I'm not too familiar with Flutter. I'm just trying to build a project that I inherited.

**Comment by DarkKnight1005** [comment]
I have the same issue, however my minSdkVersion is 21

**Comment by DarkKnight1005** [comment]
I have figured out how to solve this problem. 
go to the path: <Your Flutter Location >\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.22+1\android\build.gradle then you will see: 
`android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 16 <-- Change it to 21
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }

    dependencies {
        implementation 'androidx.annotation:annotation:1.0.0'
        implementation 'androidx.webkit:webkit:1.0.0'
    }
}
`
You have to change minSdkVersion to 21. And build it again, build will be successful if you do not have any other issues.

**Comment by lavnFan** [comment]
> I have figured out how to solve this problem.
> go to the path: .pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.22+1\android\build.gradle then you will see:
> `android {
> compileSdkVersion 28
> 
> ```
> defaultConfig {
>     minSdkVersion 16 <-- Change it to 21
>     testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
> }
> lintOptions {
>     disable 'InvalidPackage'
> }
> 
> dependencies {
>     implementation 'androidx.annotation:annotation:1.0.0'
>     implementation 'androidx.webkit:webkit:1.0.0'
> }
> ```
> 
> }
> `
> You have to change minSdkVersion to 21. And build it again, build will be successful if you do not have any other issues.

if your app is over API 21(Android 5.0), you can change the minSdkVersion easily.
but if consider **below Android 5.0**, it's not wiser modification. then you can **refer to my modification for api level judge upon the third and fourth floor.**

**Comment by darshankawar** [comment]
Hi @lavnFan, can you please confirm if you are still experiencing this issue on latest `Flutter channel (eg: dev)` and with latest version of `webview_flutter` ?

**Comment by vahidlazio** [comment]
@darshankawar Yes, and also it's not really "stable" to use dev channel in your CI.

**Comment by vahidlazio** [comment]
This is not really a way to go but we ended up disabling the lint for the webview submodule like following:
`startParameter.excludedTaskNames += ':webview_flutter:lintDebug' `

having this line in settings.gradle file of the host project, disables the lintDebug task on your webview_flutter dependency so your CI wouldn't be blocked.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
