### ISSUE TITLE
Sub-mirrors, a pseudo Mirrors solution for flutter (Mirrors + static addition)

### ISSUE THREAD

**Issue by icatalud** [flutter/flutter#45359]
**Update:** Alternative to issue [language#701](https://github.com/dart-lang/language/issues/701) (it's the same idea)

It's possible to see that Issue #1150 has huge popularity. Essentially many consumers of Flutter are not happy by not being able to control using or not the mirrors library. I believe the impact of enabling mirrors should be quantified with examples so that consumers can be convinced that it is too costly to enable it (I certainly believe it is too costly).

A solution that could allow to give users some control is to create a Sub-mirrors package where the classes that need to be mirrored can be manually added to a list, so that the compiler knows that those classes cannot be tree-shaked (assume all methods are being called) and should be fully considered. For example:

```dart
import ‘dart:submirrors’ show mirrorClass, invoke

mirrorClass(A);

Class A { foo() }
Class B extends A { }

A a = A();
invoke(a, 'foo');
a = B();
invoke(a, 'foo');    /// exception, type B was not loaded in the submirrors list
```

**Comment by icatalud** [comment]
@eernstg wrote:

> This is a trade-off. Given that reflectable allows you to specify things like @GlobalQuantifyCapability(r"^dart.core.List", reflector), which means that every subtype of List will support the reflective capabilities specified for reflector, there is no way you could generate code that would be able to fulfill that promise for subtypes of List declared in an arbitrary library of the "current program" unless you allow the code generator to run in the context of the client library (that defines what "the program" is). So you wouldn't publish *.reflectable.dart files, because they won't contain the code for the whole program, only for code reachable from your package.

I'm sorry, I went ahead the discussion and didn't read all the posts before posting. It seemed simpler, than what it actually is. Can you close this issue please?

**Comment by icatalud** [comment]
@stevenroose, @kasp1, @jmendeth

Could explain your mirrors use case in a simple way? Would a solution like this one suffice for your use case? This solution implies that you have to explicitly tell Dart the specific classes where you want reflection on. The object where reflection would be invoked needs to be exactly of the same class, it cannot be an interface, a child class or a super-class (see the example above).

**Comment by jmendeth** [comment]
Hi! In my case I don't really need to use mirrors, I just wanted to learn more about the VM and was looking for a way to disable the tree shaking. (It was painful, but I got it working) But thank you anyways :)

**Comment by Hixie** [comment]
This is somewhat out of scope for Flutter, we're following Dart's lead here.
