### ISSUE TITLE
This is impossible to get stacktrace of gesture exception

### ISSUE THREAD

**Issue by DenisovAV** [flutter/flutter#45358]
When an error occurs at execution of GestureRecognizer.invokeCallback, FlutterError.reportError calls _WidgetInspectorService._reportError istead of overriden FlutterError.onError. Impossible to log this error by own logger.

`onTap:  () {
          throw Exception("sdfdfdf");
        }`

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following _Exception was thrown while handling a gesture:
Exception: sdfdfdf

When the exception was thrown, this was the stack: 
#0      SavedSearchesList._buildSavedSearch.<anonymous closure> (package:epm_ingm_b2b/src/ui/widget/saved_search/ss_list.dart:49:11)
#1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
#2      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#8f3b4
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(157.7, 435.0)
  finalLocalPosition: Offset(157.7, 39.4)
  button: 1
  sent tap down

instead of my implementation of ErrorHandler

**Comment by iapicca** [comment]
Hi @DenisovAV 
I'm not sure this issue is intended as 
a bug report for `GestureRecognizer.invokeCallback` 
or a proposal.
Can you help me to clarify
thank you

**Comment by DenisovAV** [comment]
Hi, @iapicca 
Thank you for your answer. I've found an already created issue with the same question.
This is #44440 
Will watch it and waiting for an answer
