### ISSUE TITLE
Calculator demo should be ridiculously good looking

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#4535]

**Comment by abarth** [comment]
![](https://lh5.googleusercontent.com/-emmXGqQ-AP0/V14IHbd321I/AAAAAAAASTs/KZkCEiIzfSsbdCeJ_DTayi9RunTcMdwZQCL0B/w500-h213-no/2016-06-12.png)

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/4740, https://github.com/flutter/flutter/issues/4741

**Comment by Hixie** [comment]
@abarth If you want to do this we would accept patches. However, we're not going to track this any more.
