### ISSUE TITLE
flutter app doesn't run and end with this issue: Finished with error: ProcessException: Process "C:\Users\Suliman Ashrafi\AndroidStudioProjects\flutter_appv\android\gradlew.bat" exited abnormally:

### ISSUE THREAD

**Issue by sulimantnh** [flutter/flutter#45363]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by jmagman** [comment]
There isn't enough information to investigate the issue.
Please fill out the template with the command you were running, how you reproduced, the output of `flutter doctor -v`, the full output of the error, etc.

**Comment by Hixie** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
