### ISSUE TITLE
TextAlign.justify is not working

### ISSUE THREAD

**Issue by Cyer** [flutter/flutter#45375]
## Steps to Reproduce

use widget like :

```
Text(
  'Flutter是谷歌的移动UI框架，可以快速在iOS和Android上构建高质量的原生用户界面。 Flutter可以与现有的代码一起工作。在全世界，Flutter正在被越来越多的开发者和组织使用，并且Flutter是完全免费、开源的。',
  textAlign: TextAlign.justify,
)
```

![WechatIMG344](https://user-images.githubusercontent.com/24714116/69392696-d2c5b980-0d11-11ea-8fba-0db765304a31.jpeg)

## Logs
```
[✓] Flutter (Channel master, v1.12.6-pre.13, on Mac OS X 10.15 19A603, locale zh-Hans-CN)
    • Flutter version 1.12.6-pre.13 at /Users/caigou/development/flutter
    • Framework revision 0b502b1f8b (23 hours ago), 2019-11-20 22:11:51 -0500
    • Engine revision 7a77e3625d
    • Dart version 2.7.0

```

**Comment by iapicca** [comment]
Hi @Cyer 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/39755)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
