### ISSUE TITLE
When IOS ends the process, clicking the notification fails to communicate with the flutter

### ISSUE THREAD

**Issue by ws4349893** [flutter/flutter#45374]
In IOS ,I tried to delay communication, but it didn't work.

**Comment by iapicca** [comment]
Hi @ws4349893 
could you please describe the issue in details and
provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by Hixie** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
