### ISSUE TITLE
mega_gallery__refresh_time benchmark is failing

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#4537]
This benchmark times out after 7 minutes.

## Steps to Reproduce

```
dart dev/tools/mega_gallery.dart
flutter run -d 030c24e9d0212bbb --resident --benchmark
```

## Logs and Crash Reports

https://pantheon.corp.google.com/m/cloudstorage/b/flutter-dashboard/o/1a3adae101152a2d2ce07906700726d16c8c8775/output.txt

/cc @devoncarew

**Comment by devoncarew** [comment]
I can run `flutter run --benchmark` on the mega_gallery app locally and it completes. Perhaps there's an intermittent problem with it, or a race condition w/ the restart notification?

**Comment by yjbanov** [comment]
Forcing another build at the same revision to see if it's intermittent.

**Comment by yjbanov** [comment]
It succeeded on a second try. Let's keep an eye on it. If it's flaky we need to know why and fix it.
