### ISSUE TITLE
DraggableScrollableSheet doesn't dispatch ScrollNotification correctly.

### ISSUE THREAD

**Issue by itome** [flutter/flutter#45378]
DraggableScrollableSheet doesn't dispatch `UserScrollNotification` and `ScrollUpdateNotification` when scrolling without filling up its container.

Related PR -> #45083 

## Steps to Reproduce

1. Layout DraggableScrollableSheet.
2. Fling it little without filling up its container (without scrolling its content).

Also, this test case should be fixed like below.
https://github.com/flutter/flutter/blob/2dce8d14264ec857f4ff8e5a9b50eabb0fcd2a11/packages/flutter/test/widgets/draggable_scrollable_sheet_test.dart#L282

```dart
      final List<Type> types = <Type>[
        ScrollStartNotification,
        UserScrollNotification,
        ...List<Type>.filled(5, ScrollUpdateNotification),
        ScrollEndNotification,
        UserScrollNotification,
      ];
```

**Comment by iapicca** [comment]
Hi @itome 
I see the PR has been been merged,
are you still experiencing the issue with the latest stable or above?
Thank you

**Comment by itome** [comment]
Sorry, I forgot to close.
