### ISSUE TITLE
[image_picker] cash in Android 10

### ISSUE THREAD

**Issue by cv0cv0** [flutter/flutter#45377]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:27 flg=0x1 }} to activity {com.chuangding.shop/com.chuangding.shop.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

**Comment by iapicca** [comment]
Hi @cv0cv0 
could you please describe the issue in details 
and provide your updated  `flutter doctor -v`
and your `flutter run --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by cv0cv0** [comment]
@iapicca Thank you very much for your answer. This issue may have been resolved. I changed targetSdkVersion to 28 and probably also ran flutter clean; then I changed targetSdkVersion back to 29 and it still works. So I can't figure out where the problem is.

非常感谢你的回答。这个问题可能已经解决。我更改 targetSdkVersion 为 28，可能还运行过 flutter clean；然后我把 targetSdkVersion 改回 29，依然正常运行。所以我也搞不明白问题出在哪了。
