### ISSUE TITLE
 Issue from website page Getting Started: Setting up the Flutter development environment on macOS Running flutter run compile error

### ISSUE THREAD

**Issue by qinrunhao** [flutter/flutter#45383]
<details>
  <summary>logs</summary>

```
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/hyd/Documents/flutter/.pub-cache/git/localauthx-4792cf538cc25cb4a6cb7
    02bc16fc4596c92994c/ios/Classes/LocalauthxPlugin.m:8:17: warning: cannot
    find interface declaration for 'FLTLocalauthxPlugin'; did you mean
    'LocalauthxPlugin'?
    @implementation FLTLocalauthxPlugin {
                    ^
    In file included from
    /Users/hyd/Documents/flutter/.pub-cache/git/localauthx-4792cf538cc25cb4a6cb7
    02bc16fc4596c92994c/ios/Classes/LocalauthxPlugin.m:6:
    /Users/hyd/Documents/flutter/.pub-cache/git/localauthx-4792cf538cc25cb4a6cb7
    02bc16fc4596c92994c/ios/Classes/LocalauthxPlugin.h:3:12: note:
    'LocalauthxPlugin' declared here
    @interface LocalauthxPlugin : NSObject<FlutterPlugin>
               ^
    /Users/hyd/Documents/flutter/.pub-cache/git/localauthx-4792cf538cc25cb4a6cb7
    02bc16fc4596c92994c/ios/Classes/LocalauthxPlugin.m:16:3: error: unknown type
    name 'FLTLocalAuthPlugin'; did you mean 'FLTLocalauthxPlugin'?
      FLTLocalAuthPlugin *instance = [[FLTLocalauthxPlugin alloc] init];
      ^~~~~~~~~~~~~~~~~~
      FLTLocalauthxPlugin
    /Users/hyd/Documents/flutter/.pub-cache/git/localauthx-4792cf538cc25cb4a6cb7
    02bc16fc4596c92994c/ios/Classes/LocalauthxPlugin.m:8:17: note:
    'FLTLocalauthxPlugin' declared here
    @implementation FLTLocalauthxPlugin {
                    ^
    /Users/hyd/Documents/flutter/.pub-cache/git/localauthx-4792cf538cc25cb4a6cb7
    02bc16fc4596c92994c/ios/Classes/LocalauthxPlugin.m:16:56: error: no known
    class method for selector 'alloc'
      FLTLocalAuthPlugin *instance = [[FLTLocalauthxPlugin alloc] init];
                                                           ^~~~~
    /Users/hyd/Documents/flutter/.pub-cache/git/localauthx-4792cf538cc25cb4a6cb7
    02bc16fc4596c92994c/ios/Classes/LocalauthxPlugin.m:17:36: warning:
    incompatible pointer types sending 'FLTLocalauthxPlugin *' to parameter of
    type 'NSObject<FlutterPlugin> * _Nonnull' [-Wincompatible-pointer-types]
      [registrar addMethodCallDelegate:instance channel:channel];
                                       ^~~~~~~~
    In module 'Flutter' imported from
    /Users/hyd/Documents/flutter/.pub-cache/git/localauthx-4792cf538cc25cb4a6cb7
    02bc16fc4596c92994c/ios/Classes/LocalauthxPlugin.h:1:
    /Users/hyd/Documents/hopeszapp/ios/Pods/../.symlinks/flutter/ios/Flutter.fra
    mework/Headers/FlutterPlugin.h:294:57: note: passing argument to parameter
    'delegate' here
    - (void)addMethodCallDelegate:(NSObject<FlutterPlugin>*)delegate
                                                            ^
    /Users/hyd/Documents/flutter/.pub-cache/git/localauthx-4792cf538cc25cb4a6cb7
    02bc16fc4596c92994c/ios/Classes/LocalauthxPlugin.m:18:37: warning:
    incompatible pointer types sending 'FLTLocalauthxPlugin *' to parameter of
    type 'NSObject<FlutterPlugin> * _Nonnull' [-Wincompatible-pointer-types]
      [registrar addApplicationDelegate:instance];
                                        ^~~~~~~~
    In module 'Flutter' imported from
    /Users/hyd/Documents/flutter/.pub-cache/git/localauthx-4792cf538cc25cb4a6cb7
    02bc16fc4596c92994c/ios/Classes/LocalauthxPlugin.h:1:
    /Users/hyd/Documents/hopeszapp/ios/Pods/../.symlinks/flutter/ios/Flutter.fra
    mework/Headers/FlutterPlugin.h:302:58: note: passing argument to parameter
    'delegate' here
    - (void)addApplicationDelegate:(NSObject<FlutterPlugin>*)delegate;
                                                             ^
    /Users/hyd/Documents/flutter/.pub-cache/git/localauthx-4792cf538cc25cb4a6cb7
    02bc16fc4596c92994c/ios/Classes/LocalauthxPlugin.m:117:33: warning: block
    implicitly retains 'self'; explicitly mention 'self' to indicate this is
    intended behavior [-Wimplicit-retain-self]
                                    lastCallArgs = arguments;
                                    ^
                                    self->
    /Users/hyd/Documents/flutter/.pub-cache/git/localauthx-4792cf538cc25cb4a6cb7
    02bc16fc4596c92994c/ios/Classes/LocalauthxPlugin.m:118:33: warning: block
    implicitly retains 'self'; explicitly mention 'self' to indicate this is
    intended behavior [-Wimplicit-retain-self]
                                    lastResult = result;
                                    ^
                                    self->
    /Users/hyd/Documents/flutter/.pub-cache/git/localauthx-4792cf538cc25cb4a6cb7
    02bc16fc4596c92994c/ios/Classes/LocalauthxPlugin.m:8:17: error: class
    'FLTLocalauthxPlugin' defined without specifying a base class
    [-Werror,-Wobjc-root-class]
    @implementation FLTLocalauthxPlugin {
                    ^
    /Users/hyd/Documents/flutter/.pub-cache/git/localauthx-4792cf538cc25cb4a6cb7
    02bc16fc4596c92994c/ios/Classes/LocalauthxPlugin.m:8:36: note: add a super
    class to fix this problem
    @implementation FLTLocalauthxPlugin {
                                       ^
                                        : NSObject 
    5 warnings and 3 errors generated.
```

</details>

Could not build the application for the simulator.
Error launching application on iPhone XR.

**Comment by iapicca** [comment]
Hi @qinrunhao 
could you please provide your updated  `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by qinrunhao** [comment]
Hi @iapicca
`flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14 18A391, locale
    zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/hyd/Documents/flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/hyd/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/hyd/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone XR • B944DE4F-E3C6-44C5-A048-B1AC85219C4A • ios • iOS 12.1
      (simulator)

• No issues found!`
Android is working,ios is reporting errors.
I created a minimal code with 'flutter create myapp' without any problems.
Thank you very much

**Comment by qinrunhao** [comment]
@iapicca What should I do!

**Comment by qinrunhao** [comment]
@iapicca I create a minimal code with 'flutter create myapp' to reproduce the problem. Only change the file 'pubspec.yaml' like: 
`name: hopeszapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+20191001

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.5.2
  rxdart: ^0.19.0
  flutter_swiper: ^1.1.3
  url_launcher: ^5.0.2
  fluro: ^1.3.4
  connectivity: ^0.4.3+4
  dio: ^2.1.0
  shared_preferences: ^0.5.2
  image_picker: ^0.5.0
  flutter_spinkit: ^3.1.0
  fluttertoast: ^3.1.3
  permission_handler: ^3.0.2
  open_file: ^2.0.1+2
  path_provider: ^1.1.0
  flutter_html_textview: ^0.2.5
  charts_flutter: ^0.6.0
  flutter_markdown: ^0.2.0
  flutter_date_pickers: ^0.0.3
  date_format: ^1.0.6
  lpinyin: ^1.0.7
  webview_flutter: ^0.3.9+1
  scannerx:
    git: http://192.168.1.193/hope/scannerx.git
  hopetake:
    git: http://192.168.1.193/hope/hopetake.git
  localauthx:
    git: http://192.168.1.193/hope/localauthx.git
  flutter_localizations:
    sdk: flutter
  json_annotation: ^2.0.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_splash_screen: ^0.1.0
  flutter_string_encryption: ^0.3.1
  device_info: ^0.4.0+2
  mqtt_client: ^5.5.3
  flutter_local_notifications: ^0.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - resources/
#    - assets/fonts/
#  fonts:
#    - family: PingFang
#      fonts:
#        - asset: assets/fonts/PingFang Regular.ttf
#        - asset: assets/fonts/PingFang Medium.ttf
#        - asset: assets/fonts/PingFang Bold.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages`
