### ISSUE TITLE
A get method to current route with arguments (if any) in NavigatorState class.

### ISSUE THREAD

**Issue by Faiyyaz** [flutter/flutter#45389]
Hi, Need a get method to current route with arguments (if any) in NavigatorState class. Valid use case of this maybe while receiving a notification we want to check user in on which screen and want to compare arguments to decide whether to show the notification or not. 

Syntax for the required method 

```
Route<dynamic> get currentRoute() { 
            return _navigator != null && _navigator._history.last; 
}
```

This method is tried and tested. It works fine but i need to change it in NavigatorState class to use it so if it can be shipped with sdk it will be helpful.

**Comment by iapicca** [comment]
Hi @Faiyyaz 
please take a look to the answers in this stackoverflow [question](https://stackoverflow.com/questions/46483949/how-to-get-current-route-path-in-flutter),
also consider that some work is in progress for [Navigator 2.0](flutter.dev/go/navigator-with-router).
Does this solve the issue?
thank you

**Comment by Faiyyaz** [comment]
@iapicca No. None of the answers on that post match my requirements. Some of them returns just the current route name but i need to get the arguments passed too.

And some methods just give me that the route isCurrent or not

**Comment by Faiyyaz** [comment]
Hey what is the status on this issue.

Actually i have this use case again for building chat in my app

**Comment by Faiyyaz** [comment]
Changes to the method as per flutter v1.17 release 

```
Route<dynamic> get currentRoute { 
            return _navigator != null && _navigator._history.last.route; 
}
```

**Comment by goderbauer** [comment]
@chunhtai

**Comment by goderbauer** [comment]
You should be able to just do `ModalRoute.of(context)` and look at the arguments in the settings there.
