### ISSUE TITLE
Can't apply custom fonts and insert images

### ISSUE THREAD

**Issue by gustavo440** [flutter/flutter#45393]
After downloading fonts and mapping them in the pubspec file, they wouldn't display on my app, still no errors popped up

**Comment by iapicca** [comment]
Hi @gustavo440 
could you please provide your updated  `flutter doctor -v`,
your `pubspec.yaml` and a minimal code sample to reproduce the problem?
Thank you

**Comment by gustavo440** [comment]
**Flutter Doctor**
`[flutter] flutter doctor -v
[✓] Flutter (Channel dev, v1.12.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.5 at /home/gustavo.alves/flutter
    • Framework revision 2c7af1e24e (2 days ago), 2019-11-20 12:18:44 -0800
    • Engine revision 176f563296
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/gustavo.alves/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /snap/android-studio/81/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/81/android-studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
exit code 0`

**pubspec.yaml**
`name: expense_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  flutter_masked_text: ^0.8.0
  
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/waiting.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
`

And here is the sample code:
`import 'package:expense_app/widgets/add_transaction_form.dart';
import 'package:flutter/material.dart';
import 'dart:math';

import './models/transaction.dart';
import './widgets/chart.dart';
import './widgets/transaction_list.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        fontFamily: 'Roboto',
      ),
      title: 'Sample App',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Sample App'),
      ),
      body: Center(
        child: 
          Text('Should be in Roboto Regular'),
      ),
    );
  }
}
`

**Comment by iapicca** [comment]
Hi @gustavo440 
just tested on the latest master and seems to work just fine both on mobile and web
[sample code](https://gist.github.com/iapicca/b074b25da875aefe7642a83c8fa7bd6b) 
![Capture](https://user-images.githubusercontent.com/45637986/69433013-77acba80-0d43-11ea-950e-3989fb00bd1e.PNG)
can you please double check your folder asset 
thank you

**Comment by gustavo440** [comment]
I know it sounds stupid, but I'm really stuck on this. Can you please take a look at my repo and tell me what I'm doing wrong?

https://github.com/gustavo440/flutter_sample_app.git

**Comment by gustavo440** [comment]
Hey @iapicca, I've just found out that cleaning and reloading my flutter project solved it. In the end there was nothing wrong with my code.

Thank you very much for all the help :smiley:

**Comment by iapicca** [comment]
Hi @gustavo440 
I'm glad to hear that,
thank you for letting me know
