### ISSUE TITLE
Crash on iOS Device With GrGLGpuRTCommandBuffer::begin() 

### ISSUE THREAD

**Issue by zw1924** [flutter/flutter#45390]
![image](https://user-images.githubusercontent.com/54323514/69411817-a6795f80-0d48-11ea-8c3d-31ac66f3e8ba.png)

Flutter 1.9.1+hotfix.6 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (10 weeks ago) • 2019-09-13 19:46:58
-0700
Engine • revision b863200c37
Tools • Dart 2.5.0

**Comment by iapicca** [comment]
Hi @zw1924 
could you please describe the issue more in detail
and  provide your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by zw1924** [comment]
eh, This is a problem that occurs on the customer's device. There is a certain probability of triggering.

**Comment by iapicca** [comment]
Hi @zw1924 
could you please post a minimal code sample to reproduce the problem?
For example would be helpful to know `pubspec.yaml`
thank you

possibly related to
https://github.com/flutter/flutter/issues/34509 and 
https://github.com/flutter/flutter/issues/41620# (w/ [workaround](https://github.com/flutter/flutter/issues/41620#issuecomment-538386422))

**Comment by Hixie** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
