### ISSUE TITLE
[Question] - flutter build ios - it is not documented what it does and why it is needed

### ISSUE THREAD

**Issue by jherencia** [flutter/flutter#45400]
I'm following these steps (https://flutter.dev/docs/deployment/ios) to build my application in iOS and it says:

1. First run flutter build ios
2. Run archive in XCode, which runs `/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build` which runs flutter build aot

Why is `flutter build ios` needed? Why is not included in `xcode_backend.sh`?

**Comment by jmagman** [comment]
`flutter build ios` can take various parameters, then calls into Xcode's command line tools, among other things.  You can see exactly what it does if you run with the -v flag, if you're curious.  `xcode_backend.sh` is called during a Xcode script build phase, and it calls into Flutter to compile the dart bits, and is run whenever the Xcode project is built.  So if you're already in Xcode, it wouldn't make sense for the build phase to call `flutter build ios` to reentrantly call into Xcode's command line tools.

```
$ flutter build ios -h
Build an iOS application bundle (Mac OS X host only).

Usage: flutter build ios [arguments]
-h, --help                  Print this usage information.
    --debug                 Build a debug version of your app (default mode).
    --profile               Build a version of your app specialized for performance profiling.
    --release               Build a release version of your app.
-t, --target=<path>         The main entry-point file of the application, as run on the device.
                            If the --target option is omitted, but a file name is provided on the command line, then that is used instead.
                            (defaults to "lib/main.dart")

    --flavor                Build a custom app flavor as defined by platform-specific build setup.
                            Supports the use of product flavors in Android Gradle scripts, and the use of custom Xcode schemes.

    --[no-]pub              Whether to run "flutter pub get" before executing this command.
                            (defaults to on)

    --build-number          An identifier used as an internal version number.
                            Each build must have a unique identifier to differentiate it from previous builds.
                            It is used to determine whether one build is more recent than another, with higher numbers indicating more recent build.
                            On Android it is used as 'versionCode'.
                            On Xcode builds it is used as 'CFBundleVersion'

    --build-name=<x.y.z>    A "x.y.z" string used as the version number shown to users.
                            For each new version of your app, you will provide a version number to differentiate it from previous versions.
                            On Android it is used as 'versionName'.
                            On Xcode builds it is used as 'CFBundleShortVersionString'

    --[no-]simulator        Build for the iOS simulator instead of the device.
    --[no-]codesign         Codesign the application bundle (only available on device builds).
                            (defaults to on)

```
I use `flutter build ios` when I'm not running in Xcode, but I want to see build issues or to examine the app bundle without actually running anything.  It's the build-only version of `flutter run`, or like running Xcode > Product > Build instead of Xcode > Product > Run.

Are you hitting any issues, or are you just curious?

**Comment by jherencia** [comment]
I was trying to reproduce this issue (https://github.com/flutter/flutter/issues/18342) with the latest stable version (v1.9.1+hotfix.6). I was not able to reproduce it, so I tried to check if I was following the steps correctly and I had doubts on why it was needed to run `flutter build` before running `XCode archive`.

I haven't seen any documentation (or if it exists it is not easy to find it) of what it does and why it is needed. I want to contribute in that issue, but I think for those like me who want to help there is a gap in the documentation to understand how flutter tools work.

To understand more context:
- I've read this (and its sublevels): https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md
- I've been able to build and debug my own flutter bin

**Comment by jmagman** [comment]
I don't think we have plans to document more about the internal guts of what Flutter is doing here, other than the help text that already exists.  You are welcome to [set up Flutter tooling and step through it](https://github.com/flutter/flutter/wiki/The-flutter-tool), and look through the source control blames for interesting pull requests and issues.
