### ISSUE TITLE
[cocoon] Port go dev server to dart

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#45410]
The Go AppEngine backend had a nice development server that made it easy to develop locally. We should consider adding similar functionality to the Dart code.

[X] Document how to run `bin/server.dart` locally (https://github.com/flutter/cocoon/pull/621)
[ ] Use `FakeDatastore` and in memory cache when passed flag `--development`
[X] Add proxy capability to interact with production data
[ ] Call `app_flutter` with `flutter run` for hot reload capability with local backend

**Comment by digiter** [comment]
Triage: /cc @keyonghan

**Comment by godofredoc** [comment]
Closing as fixed. app_dart has been fully migrated to dart.
