### ISSUE TITLE
[Asset load] Unable to RELOAD asset after first start for a while or first hot reload

### ISSUE THREAD

**Issue by AlexVincent525** [flutter/flutter#45426]
### This issues happened on specific emulator.

[pubspec.yaml](https://github.com/openjmu/OpenJMU/blob/master/pubspec.yaml)

[Case 1]
1. Run main.
2. Just wait for a while, try to push to another page.
3. `Unable to load asset` occurs.

[Case 2]
1. Run main.
2. Hot restart.
3. `Unable to load asset` occurs.

When this issue happen, any assets cannot be loaded and displayed with an error log.

**Target Platform: Android Emulator ([Nox Emulator](https://www.yeshen.com/))**
**Target OS version/browser: NOT SPECIFIC**
**Devices: Emulator**

## Logs
Error logs:
```
Performing hot restart...
Syncing files to device ******...
Restarted application in 3,058ms.
I/flutter (10655): ══╡ EXCEPTION CAUGHT BY SVG ╞═══════════════════════════════════════════════════════════════════════
I/flutter (10655): The following assertion was thrown resolving a single-frame picture stream:
I/flutter (10655): Unable to load asset: images/splash_page_logo.svg
I/flutter (10655): 
I/flutter (10655): When the exception was thrown, this was the stack:
I/flutter (10655): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
I/flutter (10655): <asynchronous suspension>
I/flutter (10655): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
I/flutter (10655): <asynchronous suspension>
I/flutter (10655): #2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:162:56)
I/flutter (10655): #3      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
I/flutter (10655): #4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:162:27)
......
```

`flutter doctor -v`
```
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18363.476], locale zh-CN)
    • Flutter version 1.9.1+hotfix.6 at J:\Android\flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at J:\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = J:\Android\SDK
    • Java binary at: J:\IDEs\apps\AndroidStudio\ch-0\191.5900203\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at J:\IDEs\apps\AndroidStudio\ch-0\191.5900203
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at J:\IDEs\apps\IDEA-U\ch-0\192.6817.14
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • google Pixel 2 • 127.0.0.1:62025 • android-x86 • Android 7.1.2 (API 25)
```

**Comment by Abdusin** [comment]
open 'pubspec.yaml' in your project and add assets path
example : 
```
name: example1
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - images/a_dot_burr.jpeg
   - images/a_dot_ham.jpeg

```
images file must be in under your project

**Comment by AlexVincent525** [comment]
@Abdusin Please read my issue carefully before you comment. My assets all loaded normally at first but failed after those cases.

**Comment by Abdusin** [comment]
@AlexVincent525 could u add your pubspec.yaml file

**Comment by AlexVincent525** [comment]
@Abdusin https://github.com/openjmu/OpenJMU/blob/master/pubspec.yaml

**Comment by iapicca** [comment]
Hi @AlexVincent525 
I've noticed that your link point at what looks like priduction code,
could you please post a minimal code sample to reproduce the problem
Thank you

**Comment by AlexVincent525** [comment]
@iapicca Hi, this issue happened with the specific emulator, you may create a new flutter project and it'll still happen.

**Comment by iapicca** [comment]
Hi @AlexVincent525 
thanks for the clarification.
I'm not there's much that Flutter Team can do to fix a 3rd party emulator,
but I'd like to make a step back:
I understand that the reasons for your choice of said emulator is the 
alleged incompatibility between AMD and the official Android Emulator,
are you sure that this is still the case? 
You might want to look at this [documentation](https://android-developers.googleblog.com/2018/07/android-emulator-amd-processor-hyper-v.html).
Thank you

**Comment by AlexVincent525** [comment]
@iapicca I'll try this ASAP and go back to you.

**Comment by iapicca** [comment]
Thank you @AlexVincent525

**Comment by AlexVincent525** [comment]
@iapicca Using Hyper-V supported official AVD works fine, so do you think this issue should be continue? Anyway I'll bring this issue to the Nox team.

**Comment by iapicca** [comment]
Hi @AlexVincent525 
I'm glad that you fixed the problem
thank you for letting me know
