### ISSUE TITLE
[In-App-Purchase] [iOS] When the app opens, it doesn't give old incomplete purchases to consume/process.

### ISSUE THREAD

**Issue by DeanPack** [flutter/flutter#45425]
According to the documentation, you want to initialize the stream listener first thing in your app because when it starts you get a list of purchase details sent to the purchase listener that need to be processed and marked as consumed. Because this happens, it makes it so users can't purchase more of that consumable. The apple store simply returns that the consumable has already been purchased and will be refunded for free. 

To follow the documentation, I put my subscription listener at the very top of the main function. I have to do some weird things to make sure the transactions are run properly, because I need the users Id to validate the receipts on our firebase server, and the user isn't signed in yet at the top of main.

While debugging in Xcode, I see firebase analytics capturing the old purchase events and not sending them because they recognize them as duplicates. but the purchaseUpdates listener doesn't capture any of these. Here is the output in Xcode
<img width="583" alt="Screen Shot 2019-11-22 at 2 41 06 PM" src="https://user-images.githubusercontent.com/32622006/69462474-54c7d980-0d36-11ea-8ce4-39001aa19387.png">

The code I use for initializing the transaction listener is here.
```
void main() {
  WidgetsFlutterBinding.ensureInitialized();
    List<dynamic> purchaseDetails = List<dynamic>();
    Stream _purchaseUpdates = InAppPurchaseConnection.instance.purchaseUpdatedStream;
    _purchasesSubscription = _purchaseUpdates.listen((purchases) {
      for(int i = 0; i < purchases.length; i++) {
        print(purchases.status);
        print(purchases.purchaseID);
      }
      purchaseDetails.addAll(purchases);
    });
    try{
    StreamingSharedPreferences.instance.then((value){
    });
    // set up Sentry to catch Flutter errors
    FlutterError.onError = (FlutterErrorDetails details) {
      if (SentryHelper.isInDebugMode()) {
        FlutterError.dumpErrorToConsole(details);
      } else {
        Zone.current.handleUncaughtError(details.exception, details.stack);
      }
    };
    } catch(e) {
      var state = AppState.getDefault()
        .rebuild((b) => b..message = "in catch " + e.toString());
      runHallo(state, '/login');
    }
    FirebaseAuth auth = FirebaseAuth.instance;
    Future.wait([auth.currentUser(), loadState()])
        .timeout(Duration(seconds: 5)).then((futures) {
        try{ 
          FirebaseUser user = futures[0];
          AppState appState = futures[1];
          var isLoggedIn = user != null;
          var isAppStateLoggedIn = appState.isAuthenticated();
          var message =
              (isLoggedIn ? "user is logged in," : "user is not logged in,") +
                  (isAppStateLoggedIn
                      ? "appState.isAuthenticated()=true"
                      : "appState.isAuthenticated()=false");
          var state = appState.rebuild((b) => b..message = message);
          if (isLoggedIn) {
            message += [
              (appState.auth.userId == user.uid).toString(),
              appState.getAuthUser()?.needsSetup()?.toString() ?? "false"
            ].join(', ');
          }
          if (user != null &&
              appState.auth.userId == user.uid &&
              !appState.getAuthUser().needsSetup()) {
                _setupIAP(purchaseDetails);
                _purchasesSubscription.cancel();
                _purchasesSubscription = _purchaseUpdates.listen((purchases) {
                  _setupIAP(purchases);
                });
            runHallo(state, '/home');
          } else {
            var state = appState.rebuild((b) => b..message = message);
            runHallo(state, '/login');
          }
        } catch (e) {
          var state = AppState.getDefault()
              .rebuild((b) => b..message = "in catch " + e.toString());
          runHallo(state, '/login');
        }
    });
}
```

I don't get any print statements from within the flutter app.

**Comment by iapicca** [comment]
Hi @DeanPack 
could you please provide your updated  `flutter doctor -v`?
Thank you

**Comment by DeanPack** [comment]
Here you are. I look forward to hearing back soon, this is a huge blocker.

<img width="674" alt="Screen Shot 2019-11-25 at 8 11 11 AM" src="https://user-images.githubusercontent.com/32622006/69552196-4a3a5980-0f5b-11ea-849d-2ae6bcd1397f.png">

**Comment by dennis-tra** [comment]
I've already posted this at #39635, but this issue seems more suitable.

I want to persist a consumable product on my server like so:
1. user purchases a consumable product
2. `purchaseUpdatedStream` emits a `PurchaseDetails` object
3. send `serverVerificationData` to my server, verify the receipt and save the consumable product for this user
4. call `completePurchase` with the above `PurchaseDetails` object

However if step 3 fails I won't call `completePurchase` and I need a way to retry the server verification. Now two things could solve the situation:
1. The user tries to purchase the item again -> This leads to a dialogue where it says "Cancel"/"Buy" and when the user presses "Buy" an alert comes up that says that the item will be restored for free. When the "Cancel"/"Buy" dialogue comes up there is one new `PurchaseDetails` object emitted in the `purchaseUpdatedStream`(state pending). After confirming the second dialogue there is no new item emitted.
   Another interesting fact: The pending `PurchaseDetails` object contains `serverVerificationData` which contains information about the previous failed purchase (validated with https://github.com/voltrue2/in-app-purchase) - so in theory there might be a way to access the data again.
2. According to the documentation of `purchaseUpdatedStream`:
   > If a purchase is not completed ([completePurchase] is not called on the purchase object) from the last app session. Purchase updates will happen when a new app session starts instead.
   
   So actually the user does not need to try to purchase the item again, but with the next app session a new `PurchaseDetails` object should be emitted. Unfortunately this is not the case as @DeanPack has also pointed out.

Tested on iOS with an iPhone 6 and an old iOS 11.4.1.

**Comment by DeanPack** [comment]
I haven't come up with a workaround. 98.5% of our users are android users, so we are just eating the problem on the ios users.

**Comment by DeanPack** [comment]
As long as the user doesn't get into this state, we don't have a problem. As far as I know, there are only about a dozen users who have this issue, it is very frustrating that Flutter hasn't fixed this issue yet though.

**Comment by cielo** [comment]
I am using flutter `v1.12.13+hotfix.5` with `in_app_purchase` version `0.2.2` and I am not seeing this problem in iOS. If I restart the app, my listener does listen all pending purchases that have not been completed fine, and I can attempt to complete them.

**Still**, it would be tremendously helpful if `in_app_purchase` supports `SKPaymentQueue.transactions` method. That way, developers can utilize it to check any pending transactions in iOS and complete them. Perhaps, have more control in how to process them.

This would be better than having to rely on a stream which no one knows (based on constant # of issues that are getting created related to this stream) when the stream gets initialized & no one can really pinpoint how early it has to be initialized other than saying "it needs to happen before everything!".

More importantly, just relying on stream can actually create unintended DDOS-like effect. For instance, if users continue to re-purchase the already purchased consumable product when the transaction cannot be completed for some reason (bug in an app or remote server outage), # of pending transactions will continue to pile up from one to dozens. And, every time the app restarts, all these pending transactions will show up on the stream and will start hammering the backend server. 

Imagine hundreds of thousands of pending purchases piling up across all user bases which will show up on stream every time user starts the app. It will not be pretty when these pending transactions continue to hit backend server.

**Comment by dennis-tra** [comment]
Hi @cielo 

> I am using flutter v1.12.13+hotfix.5 with in_app_purchase version 0.2.2 and I am not seeing this problem in iOS. If I restart the app, my listener does listen all pending purchases that have not been completed fine, and I can attempt to complete them.

That's cool, so it's a problem on my side and I'm able to resolve it myself. Could you elaborate at which point you're attaching the listener?

Another thing. I'm just testing in the sandbox environment. Do you know if it makes a differnece in regards to "re-emitting" the purchases compared to the production environment?

> Still, it would be tremendously helpful if in_app_purchase supports SKPaymentQueue.transactions method (apple doc link). That way, developers can utilize it to check any pending transactions in iOS and complete them. Perhaps, have more control in how to process them.

Totally agreed.

**Comment by cielo** [comment]
@dennis-tra 
Sure. 

I have a store service class with a `initialize` method like below.

```dart
class StoreService {
    StreamSubscription<List<PurchaseDetails>> purchaseDetailsSubscription;

    initialize(){
        purchaseDetailsSubscription =
        InAppPurchaseConnection.instance.purchaseUpdatedStream.listen((_purchaseDetailsList) {
            print("Received purchaseDetailsList event with size ${_purchaseDetailsList.length}");
            ....
        });
    }
   ...(other methods)
}
```

My `main.dart` looks something likes this in simplified form.
````dart
void main() async {
    WidgetsFlutterBinding.ensureInitialized();
    runApp(new MyApp.custom());
}

class MyApp extends StatelessWidget {
    StoreService storeService;
    MyApp(this.storeService);
    factory MyApp.custom() {
        StoreService ss = StoreService()..initialize();
        return MyApp(ss);
    }
    @override
    Widget build(BuildContext context) {
        ....
    }
}
````

You can see that `StoreService.initialize` gets called first before `MyApp` instance is fully built.  When I run this in my real hardware device through **xcode**, I can see `"Received purchaseDetailsList event with size 1"` msg generated if there exists any pending purchase message, in addition to Firebase Analytics messages that OP @DeanPack talked about in his first post.

Do note that I am using **xcode** to read the log message. I don't recall exactly but if I used `visual studio code` with my real hardware device to run the app, I don't think I saw above log getting printed on the terminal making me to believe that onlistener is not receiving pending messages, while it actually did. I am not 100% sure but pending purchase messages might get processed way before visual studio code fully attaches log listener to the display log messages on the terminal.

In either case, running above code on real device with **xcode** or in **visual studio code**  both guarantee that pending purchases messages get delivered when the device starts the app.

I hope this helps with your case.

**Comment by dennis-tra** [comment]
Awesome, thanks @cielo for taking the time for this thorough answer. Right now I'm attaching the listener in parallel to the build process of the `MyApp` instance. I'll give your way a try and also check if running the App with XCode makes a difference :+1:

**Comment by alectogeek** [comment]
I've faced a similar problem on iOS. When I start listening to the stream I get old non-consumable purchases though I've called completePurchase() method for them. Is there any solution?

**Comment by DeanPack** [comment]
@dennis-tra How did your testing go? I've updated my packages and I'm still seeing the same issue as before.

**Comment by dennis-tra** [comment]
Hi @DeanPack,

> [...] I'm still seeing the same issue as before.

Same here. I tried to subscribe to the purchase stream in the `main` function and the `initialState` of my `MainApp` class. I didn’t get any incomplete purchases for either attempt - while the Firebase analytics plugin is detecting duplicate purchase entries. Also running the Code with XCode as @cielo suggested didn’t help for me :( So I’m still looking for a solution. 

<details>
  <summary>Flutter doctor:</summary>
  
  ```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.13.7-pre.24, on Mac OS X 10.14.6 18G2022, locale en-DE)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2018.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
  ```
</details>

**Comment by Navil** [comment]
Any updates on this issue ?

**Comment by DeanPack** [comment]
I worked around it by querying past purchases when they open up our in app store. The documentation says this won't work for apple, but fortunately that is a lie, it will give you failed purchases. The work around was a great find, but I think this issue should still be fixed.

**Comment by dg76** [comment]
Hi!

I have the problem that my auto-renewable subscription just stops, probably because I cannot see and confirm the renewed transaction. Maybe due to the problem described here, that one does not get all uncompleted transactions on startup.

I can see that in the file app_store_connection.dart the observer uses a StreamController.broadcast():

`    _observer = _TransactionObserver(StreamController.broadcast());`

However "StreamController.broadcast()" says

> Broadcast streams do not buffer events when there is no listener.

I.e. purchase transactions can be lost if they are delivered before a listener has been attached. So wouldn't it be better to just use

`    _observer = _TransactionObserver(StreamController());`

because

> The controller buffers all incoming events until a subscriber is registered

 and so no transactions would be lost?

**Comment by Vardiak** [comment]
Hi, any news concerning this issue ? It's quite a big problem for us...

**Comment by sowens-csd** [comment]
> Do note that I am using **xcode** to read the log message. I don't recall exactly but if I used `visual studio code` with my real hardware device to run the app, I don't think I saw above log getting printed on the terminal making me to believe that onlistener is not receiving pending messages, while it actually did. I am not 100% sure but pending purchase messages might get processed way before visual studio code fully attaches log listener to the display log messages on the terminal.
> 
> In either case, running above code on real device with **xcode** or in **visual studio code** both guarantee that pending purchases messages get delivered when the device starts the app.
> 
> I hope this helps with your case.

I was having this problem and did not see the same behaviour in Visual Studio Code as in Xcode. When run from Xcode I correctly received the pending purchases on app start. When run from VSCode I did not receive them. I'm going to stick with Xcode for testing in-app purchasing for now. The original purchase behaviour (against Sandbox) also seemed different and more correct when run from Xcode.

**Comment by leonardoj-cit** [comment]
> I worked around it by querying past purchases when they open up our in app store. The documentation says this won't work for apple, but fortunately that is a lie, it will give you failed purchases. The work around was a great find, but I think this issue should still be fixed.

How did you make this? @DeanPack

**Comment by newrecord82** [comment]
Any updates on this issue ?

**Comment by newrecord82** [comment]
```dart
Future<void> reloadTransactions() async {
    if (Platform.isIOS) {
      SKPaymentQueueWrapper wrapper = SKPaymentQueueWrapper();
      List<SKPaymentTransactionWrapper> transactions = await wrapper.transactions();
      transactions.forEach((transaction) {
        if (transaction.transactionState ==
            SKPaymentTransactionStateWrapper.purchased) {
          wrapper.finishTransaction(transaction);
        }
      });
    }
  }
```
