### ISSUE TITLE
CullRect does not cull children if they are disjoint from parent cull rect

### ISSUE THREAD

**Issue by arbreng** [flutter/flutter#45437]
Discovered while wiring up tests for https://github.com/flutter/engine/pull/13986

If one creates nested ClipRects in a structure like so:

`TopClip(MiddleClip(child))`

with dimensions like this

```
----------------------
|  top_clip          |
|                ------ |--------------------------------
|               |        |                middle_clip   |
----------------------                       -----------|------------------------
                |                                |             |     child               |
                ----------------------------------------------------------------
```

Then, child will still be rendered even though it is not within the intersection of top_clip and middle_clip.

 Should we do  `context->cull_rect.intersect(child_paint_bounds); set_paint_bounds(context->cull_rect);` inside of ClipRectLayer::Preroll to fix this?

**Comment by iapicca** [comment]
Hi @arbreng 
could you please provide your updated  `flutter doctor -v`
and  a minimal code sample to reproduce the problem?
Thank you

**Comment by markusaksli-nc** [comment]
Do you have a minimal repro case for this?

**Comment by jonahwilliams** [comment]
Closing as obsolete
