### ISSUE TITLE
Make iOS CPU/GPU measurement tool work for Xcode 11+ and iOS 13+

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#45435]
Such [tool](https://github.com/flutter/packages/tree/master/packages/gauge) is essential for us to track and improve the Fluter power/energy usage. (Search for "percentage" on https://flutter-dashboard.appspot.com/benchmarks.html.) For example, it provides us clear metrics on how to solve the following issue that's blocking one of our very important customers: https://github.com/flutter/flutter/issues/31865.

Unfortunately, that tool currently relies on [TraceUtility] which doesn't work properly on Xcode 11. Moreover, we've seen some flakiness: https://github.com/flutter/flutter/issues/45194

It would be nice if we can either improve [TraceUtility], or create our own version of that tool, to parse Instrument trace documents reliably with Xcode 11. That way, we'll
1. unblock the infra team to upgrade all our Macs to Xcode 11, and reduce the maintenance cost
2. reduce test flakiness and make the whole team happier
3. enlighten our customers by providing better and more reliable power usage metrics for improvements.

EDIT: we recently also found that [TraceUtility] doesn't work well with iOS 12.4 even if Xcode is still in 10.3. As a workaround, we've switched the iOS version to 12.3 to keep the test working.

[TraceUtility]: https://github.com/Qusic/TraceUtility

**Comment by dnfield** [comment]
We're going to have this issue every time we want to upgrade Xcode.  The utility we're using is relying on private API that can change at any time.

I wonder if we could utilize something like https://github.com/rickytan/GPUUtilization?

**Comment by dnfield** [comment]
My other suggestion _also_ uses private APIs though so..  *shrug*

**Comment by gaaclarke** [comment]
Some resources talking about extracting the data:
- [An implementation for extracting info](https://github.com/jlfwong/speedscope/blob/bdd9301c59f29c105762b6460d731438c670d705/src/import/instruments.ts#L421)
- [A stackoverflow article about extracting the info](https://stackoverflow.com/questions/16737621/trying-to-read-a-xcode-instruments-trace-file-what-is-the-file-format-of-a-tr)

**Comment by gaaclarke** [comment]
I considered the option where we created our own Instruments template and wrote the data to disk in a format of our choosing.  I don't think that will work because it looks like the templates you are able to create rely on dtrace which isn't going to give us the time profiler data we'd like for example.
https://medium.com/appspector/building-custom-instruments-package-9d84fd9339b6

**Comment by liyuqian** [comment]
Discussed with @gaaclarke yesterday, and here's the summary:

1. We'll try to see if there's a non-hacky way of creating our own instruments template to capture the CPU/GPU percentages without relying on any private APIs.
2. If 1. is proved to be impossible, then we'll try to come up with a patch for https://github.com/Qusic/TraceUtility to support parsing Xcode 11 trace.
3. If 2. turns out to be too costly, we may find a way to change the `instruments` binary so it can output the result in a format defined by us, so we can easily parse it.

**Comment by bitsydarel** [comment]
Is it possible to make this cpu/gpu data available in dart ?
Would be amazing for testing.

**Comment by gaaclarke** [comment]
@bitsydarel Did you check out https://flutter.dev/docs/development/tools/devtools/overview?  You should file a feature request issue if there is something specific you need.

**Comment by bitsydarel** [comment]
Hi @gaaclarke , already filed an issue https://github.com/flutter/devtools/issues/1395

What I meant with my question is :
Currently the devtools data is only available in the browser.

I would like to query this data from code. This will allow me to create tests like:
Check memory usage at the start of a test and after the end of test. To verify leak for example or widget memory consumption.

**Comment by gaaclarke** [comment]
@bitsydarel Thanks, it's not an unreasonable request.  It is tangental to this actual issue so I'm going to delete these comments and further discussion can happen on the feature request issue.

**Comment by gaaclarke** [comment]
@liyuqian Can you be more specific about doesn't work with Xcode 11 and TraceUtility?  I just ran it and I get output.  There isn't an obvious error to me.

**Comment by liyuqian** [comment]
@gaaclarke : with Xcode 11, TraceUtility does still run successfully but it no longer outputs the CPU percentage, and therefore [gauge][1] failed to parse the CPU usage. To reproduce the error, try the `pub global run gauge ioscpugpu new` command following the instruction of [gauge][1]. On the other hand, if I open the trace with instruments UI (instead of using TraceUtility), I can still see the CPU usage there so I think it's a parsing issue.

Moreover, @digiter , @godofredoc and I just found this morning that TraceUtility would fail to run with iOS 12.4 even if Xcode is still in 10.3. That failure seems to be irrelevant to [gauge][1].

[1]: https://github.com/flutter/packages/tree/master/packages/gauge

**Comment by gaaclarke** [comment]
Error output:
```bash
$ pub global run gauge ioscpugpu parse ~/dev/readprofile/SampleTimeProfile.trace
TraceUtility output:
...
GPU measurements:



CPU measurements:
 Runner (17039) 0 ms
Runner 0x1055c 0 ms
Runner <Call stack limit reached> 0 ms
Runner main 0 ms


Unhandled exception:
Exception: No valid measurements found.
#0      IosTraceParser._average (package:gauge/parser.dart:114:7)
#1      IosTraceParser._computeGpuPercent (package:gauge/parser.dart:72:12)
#2      IosTraceParser.parseCpuGpu (package:gauge/parser.dart:63:25)
#3      IosCpuGpuParse.run (package:gauge/commands/ioscpugpu/parse.dart:35:10)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#5      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#6      new Future.sync (dart:async/future.dart:224:31)
#7      CommandRunner.run (package:args/command_runner.dart:112:14)
#8      main (file:///Users/aaclarke/.pub-cache/hosted/pub.dartlang.org/gauge-0.1.5/bin/gauge.dart:15:10)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by liyuqian** [comment]
@gaaclarke : yes, that's exactly the error message that I've seen on Xcode 11. BTW, have you done a successful run with Xcode 10.3? (I'd like confirm that you have both a negative example and a positive example with work with.)

**Comment by gaaclarke** [comment]
@liyuqian do you have an example successful output handy?  Maybe from the server?  Testing with 10.3 is non-trivial.

**Comment by liyuqian** [comment]
@gaaclarke : sure, the following is an example successful log that I extracted from the devicelab log https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahFmbHV0dGVyLWRhc2hib2FyZHJYCxIJQ2hlY2tsaXN0IjhmbHV0dGVyL2ZsdXR0ZXIvYmE3M2NmYzE0OTlmNzNhYmVkNGJhNzZkYzBhZGI5NmMxOTZiNDc3NAwLEgRUYXNrGICA0KmMytwJDA
```
Executing: pub global run gauge ioscpugpu new -w cb313701092c54ffa70395793c5fdb2fd0e6b56e -l 10000 in /Users/flutter/.cocoon/flutter/dev/benchmarks/macrobenchmarks/build
2019-12-16T13:42:54.375848: Hostname: Platform.localHostname
stdout: Running instruments on iOS device cb313701092c54ffa70395793c5fdb2fd0e6b56e for 10000ms
2019-12-16T13:43:09.122315: Hostname: Platform.localHostname
stdout: Parsing /Users/flutter/.cocoon/flutter/dev/benchmarks/macrobenchmarks/build/instrumentscli0.trace
2019-12-16T13:43:11.983654: Hostname: Platform.localHostname
stdout: gpu: 8.6%, cpu: 13.342857142857142%
stdout: The result has been written into result.json
2019-12-16T13:43:11.990616: Hostname: Platform.localHostname
"pub" exit code: 0
2019-12-16T13:43:11.992654: Hostname: Platform.localHostname
```

To work on this, I think it's probably best to have two Mac machines, one running Xcode 10.3, and another running Xcode 11. CC @godofredoc to see if we can borrow a Mac mini from devicelab, or if @cbracken can approve another Mac Mini purchase.

**Comment by godofredoc** [comment]
I think there are two macs in the lab that you can borrow if needed. CC @digiter to confirm

**Comment by digiter** [comment]
Yes, we do have extra macs, ping me to get them.

**Comment by gaaclarke** [comment]
This seems to be the problem:

Gauge assumes that Instruments is running with "com.apple.xray.instrument-type.activity" for CPU activity and "com.apple.dt.coreanimation-fps" for GPU activity.  I'm not certain how gauge is specifying that.  It may have been that it assumed some sort of default setup.

---

For the GPU you can see that TraceUtility prints out things like this [here](https://github.com/Qusic/TraceUtility/blob/a7fb3c30a08c25637b9de58f01ff7d2c158f6db2/TraceUtility/main.m#L158
):
```
Instrument: Core Animation FPS (com.apple.dt.coreanimation-fps)
Run #2: Run 2
00:00.000.000  0 FPS 25.0% GPU
00:00.000.566 25 FPS  2.0% GPU
00:01.013.119 17 FPS  0.0% GPU
00:02.026.096 30 FPS  2.0% GPU
00:03.044.161  8 FPS  0.0% GPU
00:04.070.020  3 FPS  0.0% GPU
00:05.080.349 18 FPS  0.0% GPU
00:06.104.045 17 FPS  0.0% GPU
```

Which is parsed by gauge [here](https://github.com/flutter/packages/blob/4413ccfd40ff62686714a571eb2c408b0d384e61/packages/gauge/lib/parser.dart#L52).

This should still work assuming that instruments is run with the correct probe.

---

For CPU, TraceUtility is just printing out data associated with a sample without any introspection into what that data is [here](https://github.com/Qusic/TraceUtility/blob/a7fb3c30a08c25637b9de58f01ff7d2c158f6db2/TraceUtility/main.m#L211).  gauge is looking for something to show up in those lines in the form of `d.d%` which it interprets as cpu usage for that process [here](https://github.com/flutter/packages/blob/4413ccfd40ff62686714a571eb2c408b0d384e61/packages/gauge/lib/parser.dart#L79)

When TraceUtility I get output that looks like this:
```
00:00.000.000, 207.15 ms, Runner (17618), n/a, 17618, mobile, n/a, 8.46 \u00b5s, 1, 1, 80.18 KiB, 48.00 KiB, 16.00 KiB, 416.00 KiB, arm64, No, Yes, No, 0, No, 0 Bytes, 0 Bytes, 0 Bytes, 0 Bytes, No, 
```

You'll notice none of the items are in the form of a percentage number which trips up gauge.  That and the default probes are probably the root issues.

**Comment by liyuqian** [comment]
@gaaclarke : Thank you for the investigation! `gauge` uses [CpuGpuTemplate.tracetemplate](https://github.com/flutter/packages/blob/master/packages/gauge/lib/commands/ioscpugpu/new.dart#L36) to specify that instruments should record both CPU and GPU usages. The template is downloaded through [CIPD](https://github.com/flutter/packages/blob/master/packages/gauge/lib/commands/base.dart#L74).

With Xcode 10.3, `TraceUtility` would generate lines like the following for the CPU usage:
```
00:00.477.632, 1.55 s, Runner (2209), n/a, 2209, mobile, 23.7%, 39.02 min, 16, 146, 144.59 MiB, 128.25 MiB, 74.45 MiB, 7.39 MiB, arm64, No, Yes, No, 558,156, No, 0 Byte
```

In general, I agree with your conclusion that `TraceUtility` has a special treatment with GPU usages, but not CPU usages. That's probably why it no longer generates CPU usages without any error messages in Xcode 11.

**Comment by gaaclarke** [comment]
notes here: https://paste.googleplex.com/6444771222487040

I also noticed that the CPU samples aren't incrementing, it is printing the same time over and over again, like so:
```
00:00.000.000, 207.15 ms, Runner (17618), n/a, 17618, mobile, n/a, 8.46 \u00b5s, 1, 1, 80.18 KiB, 48.00 KiB, 16.00 KiB, 416.00 KiB, arm64, No, Yes, No, 0, No, 0 Bytes, 0 Bytes, 0 Bytes, 0 Bytes, No, 
00:00.000.000, 207.15 ms, Runner (17618), n/a, 17618, mobile, n/a, 8.46 \u00b5s, 1, 1, 80.18 KiB, 48.00 KiB, 16.00 KiB, 416.00 KiB, arm64, No, Yes, No, 0, No, 0 Bytes, 0 Bytes, 0 Bytes, 0 Bytes, No, 
00:00.000.000, 207.15 ms, Runner (17618), n/a, 17618, mobile, n/a, 8.46 \u00b5s, 1, 1, 80.18 KiB, 48.00 KiB, 16.00 KiB, 416.00 KiB, arm64, No, Yes, No, 0, No, 0 Bytes, 0 Bytes, 0 Bytes, 0 Bytes, No, 
00:00.000.000, 207.15 ms, Runner (17618), n/a, 17618, mobile, n/a, 8.46 \u00b5s, 1, 1, 80.18 KiB, 48.00 KiB, 16.00 KiB, 416.00 KiB, arm64, No, Yes, No, 0, No, 0 Bytes, 0 Bytes, 0 Bytes, 0 Bytes, No, 
00:00.000.000, 207.15 ms, Runner (17618), n/a, 17618, mobile, n/a, 8.46 \u00b5s, 1, 1, 80.18 KiB, 48.00 KiB, 16.00 KiB, 416.00 KiB, arm64, No, Yes, No, 0, No, 0 Bytes, 0 Bytes, 0 Bytes, 0 Bytes, No, 
00:00.000.000, 207.15 ms, Runner (17618), n/a, 17618, mobile, n/a, 8.46 \u00b5s, 1, 1, 80.18 KiB, 48.00 KiB, 16.00 KiB, 416.00 KiB, arm64, No, Yes, No, 0, No, 0 Bytes, 0 Bytes, 0 Bytes, 0 Bytes, No, 
00:00.000.000, 207.15 ms, Runner (17618), n/a, 17618, mobile, n/a, 8.46 \u00b5s, 1, 1, 80.18 KiB, 48.00 KiB, 16.00 KiB, 416.00 KiB, arm64, No, Yes, No, 0, No, 0 Bytes, 0 Bytes, 0 Bytes, 0 Bytes, No, 
00:00.000.000, 207.15 ms, Runner (17618), n/a, 17618, mobile, n/a, 8.46 \u00b5s, 1, 1, 80.18 KiB, 48.00 KiB, 16.00 KiB, 416.00 KiB, arm64, No, Yes, No, 0, No, 0 Bytes, 0 Bytes, 0 Bytes, 0 Bytes, No, 
00:00.000.000, 207.15 ms, Runner (17618), n/a, 17618, mobile, n/a, 8.46 \u00b5s, 1, 1, 80.18 KiB, 48.00 KiB, 16.00 KiB, 416.00 KiB, arm64, No, Yes, No, 0, No, 0 Bytes, 0 Bytes, 0 Bytes, 0 Bytes, No, 
00:00.000.000, 207.15 ms, Runner (17618), n/a, 17618, mobile, n/a, 8.46 \u00b5s, 1, 1, 80.18 KiB, 48.00 KiB, 16.00 KiB, 416.00 KiB, arm64, No, Yes, No, 0, No, 0 Bytes, 0 Bytes, 0 Bytes, 0 Bytes, No, 
00:00.000.000, 207.15 ms, Runner (17618), n/a, 17618, mobile, n/a, 8.46 \u00b5s, 1, 1, 80.18 KiB, 48.00 KiB, 16.00 KiB, 416.00 KiB, arm64, No, Yes, No, 0, No, 0 Bytes, 0 Bytes, 0 Bytes, 0 Bytes, No, 
```

**Comment by gaaclarke** [comment]
Got a feature request started for a more stable solution:

feedback filed: https://feedbackassistant.apple.com/feedback/7566306
ADRT filed: https://docs.google.com/document/d/14lYMwp_ED-2WRMjwEcnfot4raF0Wl3vy2y5HX8M_LzI/edit#

**Comment by jmagman** [comment]
Can we flip this around and use e2e or some other runner to leverage XCTest?  `measureWithMetrics:options:block:` is new in Xcode 11.  Test results can be parsed with the `xcresulttool` shipped with Xcode.

https://developer.apple.com/documentation/xctest/xctestcase/3194265-measurewithmetrics?language=objc

**Comment by gaaclarke** [comment]
@jmagman Nice, looks promising.  I'll play around with it later today, just wish it had graphics support.

**Comment by jmagman** [comment]
> @jmagman Nice, looks promising. I'll play around with it later today, just wish it had graphics support.

There's some reference to OpenGL frame capture in Run options, and it's referenced in the Metal capture tooling docs (which incidentally [has CLI support](https://developer.apple.com/documentation/metal/frame_capture_debugging_tools/capturing_metal_commands_programmatically)) but I'm not familiar with it.

<img width="1072" alt="Screen Shot 2020-02-06 at 12 20 19 PM" src="https://user-images.githubusercontent.com/682784/73975474-3efc9600-48db-11ea-9a98-68553ac0354c.png">
 https://developer.apple.com/documentation/metal/frame_capture_debugging_tools/enabling_frame_capture?language=objc

**Comment by gaaclarke** [comment]
Frame capture is going to give you the commands and attachments for rendering a single frame.  What we've used in the past is an ongoing fps counter.  I see people at least mentioning you might be able to implement your own fps counter with a hook to the display link (https://stackoverflow.com/questions/26888434/how-many-ways-to-calculate-the-fps-frames-per-second-of-an-ios-app-programmati)

**Comment by gaaclarke** [comment]
Alternatively we can just stop relying on Apple.  DevTools has things like cpu and gpu tracking, we might just want to invest in using those.

**Comment by dnfield** [comment]
I think at this point we need to disable this test.  We cannot safely expect the devices to not update, and we should not be further delaying getting the devicelab hosts on the same version of Xcode.

It's a valuable test and we should work to reenable it as expediently as possible. But it seems to be causing more problems that. It is solving right now.

**Comment by dnfield** [comment]
I have disabled these tests in https://github.com/flutter/flutter/pull/50367

We can re-enable when we are in a more stable state with them.  Right now they are repeatedly resulting in tree closures, and each time it happens someone has to manually verify that it was the flaky failure, try again, and hope for the best.

We also want to be able to upgrade the devicelab to a consistent version of Xcode/iOS across the board.

**Comment by digiter** [comment]
We'd like the devicelab to catch up the latest Xcode/iOS, which is Xcode 11.x and iOS 13.x currently.

**Comment by yusunan** [comment]
@gaaclarke Hey Gaaclarke  our team also using TraceUtility to get the performance for iOS device.
And for CPU TraceUtility using a private API setDocumentInspectionTime to move the index which is not work for Xcode 11.This is root cause for CPU,If you have any workaround for this issue, Could you share it for us.

**Comment by Itaybre** [comment]
Xcode 12 is bringing a tool to export traces to xml, so no more tricks will be needed when it is released

**Comment by gaaclarke** [comment]
@Itaybre Is there a link available for more information yet?

**Comment by Itaybre** [comment]
@gaaclarke you can see it here: https://developer.apple.com/documentation/xcode-release-notes/xcode-12-beta-release-notes
You will need a developer account to download the beta

**Comment by jmagman** [comment]
```

xctrace(1)                BSD General Commands Manual               xctrace(1)

NAME
     xctrace -- Record, import and export Instruments .trace files.

SYNOPSIS
     xctrace [command [options]]

     xctrace help [command]

     xctrace record [--output path] [--append-run] [--template path | name]
             [--device name | UDID] [--time-limit time [ms|s|m|h]]
             [--all-processes | --attach pid | name | --launch command [arguments]]
             [--target-stdin - | file] [--target-stdout - | file]
             [--env VAR=value] [--package file]


     xctrace import [--input file] [--output path] [--template path | name]
             [--package file]

     xctrace export [--input file] [--output path]
             [--toc | --xpath expression]

     xctrace list [devices | templates]

DESCRIPTION
     xctrace is used to record new Instruments.app .trace files using the
     specified recording template.  It also allows for converting supported
     converting files of supported input types  into .trace files and export-
     ing data from .trace files to parseable formats like xml.

     Available commands and their options:

     help        General help or help specific to command argument

     record      Perform a new recording on the specified device and target
                 with the given template. Resulting .trace file can be viewed
                 in Instruments.app or exported using xctrace.  Recording can
                 target all processes, attach to an existing process or launch
                 a new one.

                 --output path     Save the trace to the specified path.  A
                                   path to an existing trace file can be used
                                   if --append-run is specified. In this case
                                   the provided template will be ignored and
                                   the template in the existing trace will be
                                   used.  If the passed path is a directory, a
                                   uniquely named file will be created in it.
                                   If the path contains the extension .trace,
                                   a new trace will be created with that name
                                   at the specified path or working directory.

                 --append-run      Allows to target an existing trace file.
                                   Specifying it causes new run to be
                                   appended. New run is recorded with the tem-
                                   plate that this existing trace file was
                                   initially recorded with.

                 --template path | name
                                   Records using given trace template name or
                                   path. If name is specified, template needs
                                   to be either bundled with an installed
                                   Instruments Package or located in the
                                   Application Support directory for Instru-
                                   ments. To retrieve available templates, run
                                   xctrace list templates.

                 --device name | UDID
                                   Record on a device with the given name or
                                   UDID. If not specified, then local device
                                   is chosen for the recording.  To get list
                                   of available devices, run xctrace list
                                   devices.

                 --time-limit time [ms|s|m|h]
                                   Limits the recording to the specified time
                                   period. Example: "--time-limit 5s" or
                                   "--time-limit 1m"

                 --all-processes   Record all processes running on the system.

                 --attach pid | name
                                   Attach and record running process with the
                                   given name or pid.

                 --launch -- command [arguments]
                                   Launch and record process with the given
                                   name or path and provided arguments list.
                                   This option should be passed as the last
                                   one in the xctrace command invocation.

                 --package file    Install the given Instruments Package tem-
                                   porarily for the duration of a command.

                 --target-stdin - | file
                                   Redirects standard input stream of a
                                   launched process in case if target device
                                   is set to the local Mac.  Can be pointing
                                   to a file or be specified as - , which
                                   causes standard input of xctrace to be
                                   passed into the standard input of a target
                                   process.

                 --target-stdout - | file
                                   Redirects standard output stream of a
                                   launched process.  Can be pointing to a
                                   file or be specified as - , which causes
                                   standard output of a target process to be
                                   to be redirected into the standard output
                                   of xctrace.

                 --env VAR=value   Sets environment variable for a launched
                                   process. Example: "--env PATH=/tmp"


     import      If the specified file is of a support input format, imports
                 the file into an Instruments .trace file using the specified
                 template. This file can later be viewed using Instruments.app
                 or exported by using xctrace export command.

                 --input file      Import data from a supported file format at
                                   the given path.

                 --output path     Save the trace to the specified path.
                                   Existing trace files cannot be targeted.
                                   If the passed path is a directory, a
                                   uniquely named file will be created in it.
                                   If the path contains the extension .trace,
                                   a new trace will be created with that name
                                   at the specified path or working directory.

                 --template path | name
                                   Imported using given trace template name or
                                   path. Only data that is needed by Instru-
                                   ments contained in the template will be
                                   imported. If name is specified, template
                                   needs to be either bundled with an
                                   installed Instruments Package or located in
                                   the Application Support directory for
                                   Instruments. To retrieve available tem-
                                   plates, run xctrace list templates.

                 --package file    Install the given Instruments Package tem-
                                   porarily for the duration of a command.

     export      Perform a new recording on the specified device and target
                 with the given template. Resulting .trace file can be viewed
                 in Instruments.app or exported using xctrace.  Recording can
                 target all processes, attach to an existing process or launch
                 a new one.

                 --input file      Export data from .trace file at the given
                                   path.

                 --output path     Save output of the export operation to the
                                   given path. If not specified, then textual
                                   output is being written to the xctrace
                                   standard output.

                 --toc             Export the table of contents of a trace
                                   file. This will contain overview of content
                                   and exportable entities from the given
                                   trace file.

                 --xpath expression
                                   Perform given XPath query on the table of
                                   contents to select entities to export from
                                   the given trace file. Selected entities
                                   will be present in the export command out-
                                   put.

     list devices
                 Lists all of non-host devices that can be used as a target
                 for a new recording.

     list templates
                 Lists all of templates that are known to These include
                 Instruments.app bundled templates, templates from installed
                 Instruments Packages and custom templates installed into
                 Application Support directory for Instruments.app.

SEE ALSO
     Instruments.app may be used to perform trace recordings in a graphical
     environment and may also be used to open trace documents created by
     xctrace.

EXAMPLES
     import --input system_logs.logarchive --template 'Custom.template'

     import --input ktrace001.trace --template 'Custom.template' --package
     '/tmp/PackageToLoad.instrdst' --output system.trace

     export --input input.trace --toc

     export --input input.trace --xpath
     '/trace-toc/run[@number="1"]/data/table[@schema="my-table-schema"]'

     record --template 'Time Profiler' --all-processes --time-limit 5s

     record --template 'Time Profiler' --device-name Chad's iPhone --attach
     'Trailblazer'

     record --template 'Time Profiler' --target-stdout - --launch -- /tmp/tool
     arg1 arg2

macOS                            May. 4, 2020                            macOS

```

**Comment by gaaclarke** [comment]
I had a feature request open for this.  They never responded but... you're welcome 😁

**Comment by Itaybre** [comment]
I had to create my own parser after TraceUtility broke (now public [here](https://github.com/Itaybre/Trace2JSON)), but it is much better to have native support

**Comment by kf6gpe** [comment]
As I understand it, still blocked on https://github.com/flutter/flutter/issues/45435.

**Comment by chinmaygarde** [comment]
> As I understand it, still blocked on #45435.

That is this issue :D Did you mean to link to something else?

**Comment by liyuqian** [comment]
https://github.com/flutter/flutter/pull/63124 has verified that our CPU/GPU measurement tool is working again and our devicelab started recording valid CPU/GPU percentages since the merge of that PR.

**Comment by liyuqian** [comment]
For the record, the actual fix of this issue happened in https://github.com/flutter/flutter/issues/58803, https://github.com/flutter/engine/pull/18087, https://github.com/flutter/engine/pull/18516, https://github.com/flutter/engine/pull/18752. As we've now had them for iOS, our next step is to add them for Android (https://github.com/flutter/flutter/issues/61567).
