### ISSUE TITLE
[plugins] Switch analysis rules

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#45440]
We're currently using an outdated fork of the Flutter framework's rules in flutter/plugins. Not only is it mostly deprecated, but a lot of the rules there don't really make sense for plugins to follow since it's for the Framework specifically. It probably makes mores sense for our Dart code to match whatever the typical analysis rules would be for a Flutter app.

https://pub.dev/packages/pedantic exists as a common bar for basic Dart lints according to _Effective Dart_. That's a better standard for us and as a bonus we can relatively easily stay updated over time.

In addition to that we also want to enforce `public_member_api_docs` going forward. We've spent a decent amount of time going back and adding these after the fact and it would be better to just require them in initial PRs. (See https://github.com/flutter/flutter/projects/66).

I'm going to land the change in a few phases.

- [x] Land the new linter rules with custom `analysis_options.yaml` per package with extra `ignore`s for anything that they're failing and is non-trivial to fix. This way the new rules can land in a single self-contained PR that's relatively quick to review.
- [ ] Incrementally go through each package with ignores in their `analysis_options.yaml` and fix the failing rules, then remove the exclusion.

**Comment by mklim** [comment]
Now that the linter rules have been landed, addressing this is pretty straightforward (if time consuming). I think it would be a good issue for somebody looking to contribute to the plugins.

1. Delete `analysis_options.yaml` in the package's subdirectory.
2. Run `pub global run tuneup`.
3. Fix any errors. `public_member_api_docs` failures can be ignored if they're just on the widgets in the example app (`// ignore_for_file: public_member_api_docs`). In some rare cases `unawaited_futures` are deliberate and should be ignored as well. Reference the [Flutter style guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#documentation-dartdocs-javadocs-etc) for how to write good documentation.

**Comment by mklim** [comment]
Pretty much all that's left now is adding a lot of missing documentation.

- [ ] camera (public_member_api_docs)
- [ ] in_app_purchase (public_member_api_docs)
- [ ] google_sign_in (public_member_api_docs, unawaited_futures)
- [ ] google_sign_in_platform_interface (public_member_api_docs, unused_element, unawaited_futures)
- [ ] video_player_platform_interface (public_member_api_docs, unawaited_futures)
- [ ] e2e_macos (public_member_api_docs, unawaited_futures)

**Comment by ditman** [comment]
@mklim FYI, I've removed the latest entries from the CUSTOM_ANALYSIS_PLUGINS list in the incremental_build.sh in [this PR](https://github.com/flutter/plugins/pull/3238/files#diff-18055a1781ae532688503a01a10af4965f5bd8c3cd95d14e2c2d4a79f0ac3cf6).

The list is now empty (but I haven't removed the feature for allowing custom analysis files.)

**Comment by mklim** [comment]
Sounds like this is fixed then, thanks!
