### ISSUE TITLE
New Android embedding is only enabled on master

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#45453]
`hostonly_devicelab_tests` are failing _only in non-master branches_ on Cirrus with the following error.

```
[module_test] [STDOUT] stderr: /private/var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/flutter_module_test.vOxl3v/hello_host_app/app/src/main/java/io/flutter/add2app/MainActivity.java:11: error: incompatible types: FlutterEngine cannot be converted to PluginRegistry
[module_test] [STDOUT] stderr:     GeneratedPluginRegistrant.registerWith(flutterEngine);
[module_test] [STDOUT] stderr:    
```

For example: https://cirrus-ci.com/task/4684340952301568

**Comment by xster** [comment]
cc @blasten, not sure if there's anything to do there since the state of the code at tip of tree is very different now, but it looks like this registration is using a new embedding with old plugins directly without shim

**Comment by tvolkert** [comment]
This is failing on beta channel with `v1.12.13+hotfix.1`, which is very new.

https://cirrus-ci.com/task/6300811973361664

@blasten @matthew-carroll thoughts?

**Comment by matthew-carroll** [comment]
The following leads me to believe that the flutter tool is generating the wrong version of the plugin registrant:

```
[module_test] [STDOUT] stderr: C:\Users\ContainerAdministrator\AppData\Local\Temp\flutter_module_test.884c5db6-1601-11ea-aad5-8bd5e2fead93\hello\.android\Flutter\src\main\java\io\flutter\facade\Flutter.java:98: error: incompatible types: FlutterPluginRegistry cannot be converted to FlutterEngine
[module_test] [STDOUT] stderr:         GeneratedPluginRegistrant.registerWith(flutterView.getPluginRegistry());
[module_test] [STDOUT] stderr:                                                                             ^
```

Given that the project is referencing a `flutterView`, I think it should be using the old registrant version, but it appears to be using the new registrant version.

@blasten

**Comment by blasten** [comment]
The Android embedding is enabled on the master branch only ☹️. 
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/features.dart#L148-L156

**Comment by matthew-carroll** [comment]
@blasten can you patch that to allow us to roll to other channels?

**Comment by tvolkert** [comment]
That would explain it!

That's definitely something we should fix ASAP since we want the new embedding enabled in our next stable release.  Marking as a release blocker, which means I'll gladly accept cherry-pick of tested PRs 🙂

**Comment by tvolkert** [comment]
This has been cherry-picked in `v1.12.13+hotfix.2`, so removing the release blocker label.
