### ISSUE TITLE
ERROR: _debugCurrentBuildTarget == context': is not true.

### ISSUE THREAD

**Issue by kohinoor98** [flutter/flutter#45451]
My code: https://github.com/kohinoor98/xchanger

flutter doctor -v :
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18363.476], locale en-IN)
    • Flutter version 1.9.1+hotfix.6 at D:\Android\flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\kohin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: D:\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\Android
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.40.1)
    • VS Code at C:\Users\kohin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • GM1911 • 13c97f9d • android-arm64 • Android 10 (API 29)

• No issues found!

ERROR that I am facing:
E/flutter ( 9121): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2332 pos 20: '_debugCurrentBuildTarget == context': is not true.
E/flutter ( 9121): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter ( 9121): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 9121): #2      BuildOwner.buildScope.<anonymous closure> (package:flutter/src/widgets/framework.dart:2332:20)
E/flutter ( 9121): #3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2336:12)
E/flutter ( 9121): #4      RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:914:13)
E/flutter ( 9121): #5      WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:795:7)
E/flutter ( 9121): #6      runApp (package:flutter/src/widgets/binding.dart:845:7)
E/flutter ( 9121): #7      main (package:xchanger/main.dart:3:16)
E/flutter ( 9121): #8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229:25)
E/flutter ( 9121): #9      _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 9121): #10     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 9121): #11     _runZoned (dart:async/zone.dart:1516:10)
E/flutter ( 9121): #12     runZoned (dart:async/zone.dart:1500:12)
E/flutter ( 9121): #13     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221:5)
E/flutter ( 9121): #14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter ( 9121): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter ( 9121):
D/OpScreenModeManager( 9121): setRefreshRate token android.os.BinderProxy@37f7b35 rate 1 mCurrentRate 0
D/OpScreenModeManager( 9121): updateScenario fullScreen 1
W/Gralloc3( 9121): mapper 3.x is not supported
D/        ( 9121): Successfully load libgui-plugin.so, this=0x7549d71050
I/OpenGLRenderer( 9121): Davey! duration=2482ms; Flags=1, IntendedVsync=682545106993897, Vsync=682545106993897, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=682545107037075, AnimationStart=682545107098325, PerformTraversalsStart=682545107101137, DrawStart=682547562062751, SyncQueued=682547563233480, SyncStart=682547563441188, IssueDrawCommandsStart=682547563796292, SwapBuffers=682547588311032, FrameCompleted=682547590085615, DequeueBufferDuration=4201000, QueueBufferDuration=1514000,
W/Choreographer( 9121): Already have a pending vsync event.  There should only be one at a time.
I/Choreographer( 9121): Skipped 226 frames!  The application may be doing too much work on its main thread.
D/OnePlusJankManager( 9121):  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = com.example.xchanger/com.example.xchanger.MainActivity--- jank level = 3
E/FlutterFcmService( 9121): Fatal: failed to find callback

After going through all the posts related to this topic i thought it was the dependencies. But then I commented them and tried debugging still the same error persists.
Then I reinstalled flutter, nothing happened.

Please HELP.

To duplicate simply clone my project and flutter run

**Comment by iapicca** [comment]
Hi @kohinoor98 
the link you posted is not accessible
could post a minimal code sample to reproduce the problem?
Thank you

**Comment by kohinoor98** [comment]
I found the error, there was some issue with the main.dart it was not working properly...
