### ISSUE TITLE
I use this package (https://pub.dev/packages/blue_thermal_printer) and it is working but it show unknown characters with Arabic Lang any help please

### ISSUE THREAD

**Issue by aceead** [flutter/flutter#45465]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by jonahwilliams** [comment]
Please file an issue on that package's github repo instead of Flutter: https://github.com/kakzaki/blue_thermal_printer

**Comment by aceead** [comment]
Already I did it but no response I hope some one help me with this issue
