### ISSUE TITLE
MediaType is missing in http package

### ISSUE THREAD

**Issue by azamsharp** [flutter/flutter#45471]
There is no such thing as MediaType in the following code. It does not exist. 

var uri = Uri.parse("http://pub.dartlang.org/packages/create");
var request = new http.MultipartRequest("POST", uri);
request.fields['user'] = 'nweiz@google.com';
request.files.add(new http.MultipartFile.fromPath(
    'package',
    'build/package.tar.gz',
    contentType: new MediaType('application', 'x-tar'));
var response = await request.send();
if (response.statusCode == 200) print('Uploaded!');

**Comment by jonahwilliams** [comment]
Please file an issue in the http package repo: https://github.com/dart-lang/http/issues

**Comment by kairliyev** [comment]
import 'package:http_parser/http_parser.dart';
