### ISSUE TITLE
Server Client Local

### ISSUE THREAD

**Issue by nio74** [flutter/flutter#45477]
In your opinion, is it possible to create a local server and then read the data on the mobile in the same local network all written in flutter?

**Comment by iapicca** [comment]
Hi @nio74 
if you are looking for a backend in Dart
you might be interested in [shelf](https://pub.dev/packages/shelf);
without endorsing any solution I feel to mention a couple of popular 3rd party frameworks
(in alphabetical order) [angel](https://angel-dart.dev/) and [aqueduct](https://aqueduct.io/).

I also want to stress that the aforementioned packages and frameworks
have nothing to do with flutter except sharing the same programming language (Dart)
and some (if not most) of [Dart Packages](https://pub.dev/).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
