### ISSUE TITLE
Stuck at syncing files to device Android SDK

### ISSUE THREAD

**Issue by azamsharp** [flutter/flutter#45473]
When running apps on simulator, Flutter apps are stuck and saying: 

`Stuck at syncing files to device Android SDK`

This is a performance bug in either the build system in Flutter or failing to connect internally with the emulator. Happens in both VS Code and Android Studio.

**Comment by iapicca** [comment]
Hi @azamsharp 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by hawkinsjb1** [comment]
This happens to me on a regular and device and has been an intermittent issue since I started Flutter development. We need a hard-restart option that can override this 'reload' state as I don't believe this is a simple issue that can be fixed permanently and not eventually re-surface.

**Comment by alokkumax** [comment]
what is the damn. soln?????

**Comment by alokkumax** [comment]
what is the solution?

**Comment by ThySidane** [comment]
I am getting the same problem. For more info., go to this link:
https://stackoverflow.com/questions/59955690/flutters-main-dart-file-gets-stuck-at-syncing-files-to-device-android-sdk-buil

**Comment by giaur500** [comment]
Debug not working at all. Why this issue is closed? What additional info required?

**Comment by alokkumax** [comment]
Delete some recent android studio caches and restart and recheck your code.
Hope it Helps!!

**Comment by giaur500** [comment]
Nope. Now I'm pretty sure that in my case, it's only broken on kernel 5.5. On kernel 5.4 it works fine so far, which is really strange. Please reopen this issue and make some investigation, it's really strange.

Of course, I can provide any additional info if required, let me know what is required for investigation. I have no idea how is it related to kernel and as I can read, some poeple on Windows have this issue too. 

With native Android Java/Kotilin, debug works just fine on 5.5. kernel, so I'm really confused.

**Comment by TheAifam5** [comment]
Please reopen the issue. Freshly installed Flutter with VSCode on ArchLinux with 5.5 kernel and is stuck on "Syncing files to device".

**Comment by giaur500** [comment]
That's not only single issue. On 5.5 more things are broken, refactoring with Android Studio hangs too

**Comment by zencubic** [comment]
I can confirm that since kernel 5.5 the above mentioned problems occur

**Comment by giaur500** [comment]
@zencubic are you able to refactor (rename for example) with Android Studio Flutter project? It hangs on 5.5 in my case, on 5.4 it works fine

**Comment by zencubic** [comment]
Refactoring doesn't work, IntelliSense doesn't work and also Syntax highliting has some major problems

**Comment by giaur500** [comment]
Ok, so exactly the same as in my case. Please open this bug again then

**Comment by zencubic** [comment]
Maybe this issue is related: #49185

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by giaur500** [comment]
@iapicca such issue bas been linked here: https://github.com/flutter/flutter/issues/49185

**Comment by 2shrestha22** [comment]
I am having same issue after upgrading Arch Linux kernel 5.5.2-arch1-1. What should I do?

**Comment by giaur500** [comment]
Downgrade kernel to 5.4

**Comment by jonataslaw** [comment]
I did tests on my machine and got the following report:
This problem definitely occurs with the 5.5 kernel. Downgrading to the 5.4 kernel solves the problem in all cases.
I believed it to be a problem with archlinux and flutter binaries, however, I installed other distros with the latest kernel and got crashes in the same way. Zen Kernel also experiences the same problem. The solution is to downgrade for now, or use the LTS kernel that works well with Flutter in all cases, I even think this is information that should be on the wiki.

**Comment by giaur500** [comment]
@jonataslaw I have no idea what is `LTS kernel`, but all 5.5 versions I tried don't work. That does not make any sense to try to look problems in kernel, FLutter should be fixed.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by giaur500** [comment]
@iapicca why are you asking the same again and again? New issue has been linked above

**Comment by iapicca** [comment]
Hi @giaur500 
my apologise I've missed the link

**Comment by c3n7** [comment]
I'm experiencing the same issue after updating my Manjaro installation.
- Kernel Version:
    ```
    Currently running: 5.5.2-1-MANJARO (linux55)
    The following kernels are installed in your system:
       * linux54
       * linux55
    ```
- Flutter:
    ```
    [✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_GB.UTF-8)
        • Flutter version 1.12.13+hotfix.8 at /home/timo/.programs/flutter
        • Framework revision 0b8abb4724 (8 days ago), 2020-02-11 11:44:36 -0800
        • Engine revision e1e6ced81d
        • Dart version 2.7.0

    [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
        • Android SDK at /home/timo/Android/Sdk
        • Android NDK location not configured (optional; useful for native profiling support)
        • Platform android-29, build-tools 29.0.2
        • Java binary at: /home/timo/.programs/android-studio/jre/bin/java
        • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
        • All Android licenses accepted.
    
    [✓] Android Studio (version 3.5)
        • Android Studio at /home/timo/.programs/android-studio
        • Flutter plugin version 43.0.1
        • Dart plugin version 191.8593
        • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    
    [✓] Connected device (1 available)
        • TECNO F1 • 034621595Q100024 • android-arm • Android 8.1.0 (API 27)
    
    • No issues found!
    ```

**Comment by pauek** [comment]
It happened to me because I had special characters in the path of the Flutter project (in my case an 'ñ'). I removed the characters and the syncing problem was gone.
