### ISSUE TITLE
Flutter web never starts with a custom entry-point

### ISSUE THREAD

**Issue by g123k** [flutter/flutter#45476]
Hello,

If I use the default entry-point (`lib/main.dart`), everything will run perfectly well on a Flutter web project.

However, if I launch the same project with a custom entry point it will be stuck to the `Attempting to connect to browser instance` step.

An example:
```flutter run -d chrome -t lib/my_main.dart 
Launching lib/my_main.dart on Chrome in debug mode...
Building application for the web...                                12.5s
Attempting to connect to browser instance..
```

I am currently using the 'master' repo (`
Flutter (Channel master, v1.12.11-pre.10, on Mac OS X 10.14.6 18G1012, locale en-FR)
`)

Hope you can fix it 👍

**Comment by jonahwilliams** [comment]
I cannot reproduce this on master FWIW. Please include the output of `flutter doctor -v` and an example to reproduce it

**Comment by GAM3RG33K** [comment]
try running the same with flutter CLI.

If you can run with the CLI then there's already an issue with filed for that.

**Comment by g123k** [comment]
Hi,

I think I've found the problem.
If the entrypoint file is called `main.dart`, it will always work.

Now duplicate this file and give it another name, it won't work.

In verbose mode, there is no relevant log:

`
[+6955 ms] Starting daemon...
[ +177 ms] Initializing inputs
[  +10 ms] Reading cached asset graph...
[ +237 ms] Reading cached asset graph completed, took 235ms

[ +279 ms] Checking for updates since last build...
[ +929 ms] Checking for updates since last build completed, took 929ms

[   +8 ms] Initializing inputs
[   +2 ms] Reading cached asset graph...
[        ] Reading cached asset graph completed, took 235ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 929ms
[+1232 ms] About to build [web]...
[   +3 ms] Running build...
[ +987 ms] 1.0s elapsed, 17/20 actions completed.
[ +791 ms] Running build completed, took 1.6s

[        ] Caching finalized dependency graph...
[   +3 ms] Caching finalized dependency graph completed, took 164ms

[   +6 ms] Succeeded after 1.8s with 24 outputs (26 actions)

[   +9 ms] Building application for the web... (completed in 11.8s)
[        ] Attempting to connect to browser instance..

`

**Comment by jonahwilliams** [comment]
This is still working fine for me - you still haven't provided flutter doctor results so I have no idea whether this might be platform specific or from an older version flutter. Please file a new issue with the requested details
