### ISSUE TITLE
Show application version information in the about dialog

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4547]
On iOS I would love access to the build number and version number. For android we would want version name and version number. Is there a way to access this in dart through flutter?

**Comment by abarth** [comment]
Not currently, but we could add it.

**Comment by eseidelGoogle** [comment]
To be specific, would you want this number pulled from your pubspec.yaml version? From somewhere else (like your version control system)?  Do you care?
https://www.dartlang.org/tools/pub/pubspec.html

**Comment by drewwarren** [comment]
AndroidManifest.xml and Info.plist.

**Comment by eseidelGoogle** [comment]
Spoke with @abarth just now.  Current thinking is that we should help you build this inside your app, following the hello_services model only on iOS to begin with, but with eventual plans to move this (and likely many other pieces) out into separate "plugins".  This functionality doesn't belong in the flutter/engine itself, but does make sense as a plugin (similar to how package:google_login works today, but with a different underlying inter thread communication model).

**Comment by eseidelGoogle** [comment]
Jason is laying the groundwork for this.

**Comment by Hixie** [comment]
When this is built, we should wire the AboutDialog logic up to it so that it shows the version number automatically.

**Comment by eseidelGoogle** [comment]
Drew built his own using the HostMessage system.  We don't currently have a mechanism for redistributing flutter "plugins" externally.  Once we do we could bundle up drew's code.  It's about 5 lines of Objective-C (plus a little boilerplate) and another 3 lines of Dart. :)

**Comment by zoechi** [comment]
Does https://github.com/flutter/plugins/blob/master/packages/package_info/lib/package_info.dart provide that information?

**Comment by Hixie** [comment]
It seem so!

**Comment by acidjazz** [comment]
@zoechi @Hixie should we keep this open? that package worked perfectly for me, maybe just reference it in the docs? or should this be built-in ?

**Comment by LRNZ09** [comment]
This seems to be related: https://github.com/flutter/flutter/pull/16934

**Comment by zoechi** [comment]
#26037 somewhat related

**Comment by amanv8060** [comment]
can this be closed in favor of the package_info_plus package?

**Comment by chinmaygarde** [comment]
Removing the engine tag. Though it seems like we can close this as plugins ought to be able handle this use case. There isn't a generic way to do this across platforms.

**Comment by darshankawar** [comment]
Closing based on above comment and also the fact there are are community packages which mostly must be offering this feature. If anyone disagrees, write in comments or file a new issue for better tracking.
