### ISSUE TITLE
Bitcode is not supported in release mode of stable version

### ISSUE THREAD

**Issue by spWang** [flutter/flutter#45480]
In release mode, bitcode is not available for the stable version. The beta version can be used, but there is a problem that the sub thread calls the UI thread, which coursed crash sometimes. The dev version is available, but this version is not stable and dare not be used in production. Can the stable version support bitcode as soon as possible
@dnfield 
Besides, my version is the latest. and have no problem with 'flutter doctor -v'.
Below is the support of bitcode from different channels
![image](https://user-images.githubusercontent.com/16267211/69489013-84e5b880-0ead-11ea-8984-ff4226835cbb.png)

**Comment by dnfield** [comment]
At the time of the last stable relesae, bitcode was not ready for production (it was, in fact, intentionally committed to the tree at a point _after_ the stable branch would be cut, to give us a chance to find and fix more issues it might have triggered - and we did find and fix some bad ones with it :)).  

The crash on the UI thread _probably_ exists on dev too - @gaaclarke  is in the process of fixing a seriuos bug there.  I hope we're tracking that for the next stable.

You can read more about our release process here: https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

We're also actively working to make the release process better to address exactly this kind of scenario (where we have a set of unacceptable bugs on each channel and no best way to handle it /cc @tvolkert @Hixie). As it happens, the specific issues mentioned here are probably going to be resolved sooner than later - but dealing with this more wholistically is something that Todd or Ian can probably address further.

**Comment by dnfield** [comment]
And as far as a work around for now - you can disable bitcode in your app for the time being and still ship it -  but we do intend to get bitcode support into stable.

**Comment by spWang** [comment]
oh, For some other reasons, it's very difficult for us to close bitcode and release production, so we hope that the you can support bitcode in the stable channel a little faster. This year's year-end award of our full Fletter team is based on bitcode. Thank you very much!

**Comment by filiph** [comment]
Hi, I'm removing the `a: annoyance` tag. Not that I think this issue isn't annoying. I just try to reserve that tag only for issues with existing stable features (see [definition](https://github.com/flutter/flutter/wiki/Triage#labels)). The feature at hand is not yet in stable.

**Comment by dnfield** [comment]
There's no action to take on this bug - the next stable channel release will contain this functionality.
