### ISSUE TITLE
Flutter plugin video_player package error in smart box TV.

### ISSUE THREAD

**Issue by ptrkst** [flutter/flutter#45489]
**Hi everybody.
How to fix this error** https://drive.google.com/file/d/1TWqNpQ0BKKEYqahLGXb-go2SJ1pIJiXn/view?usp=sharing  **in a smart tv box?**

**Thanks.**

**Comment by iapicca** [comment]
Hi @ptrkst 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by ptrkst** [comment]
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Versione 10.0.17763.864], locale it-IT)
    • Flutter version 1.9.1+hotfix.6 at C:\flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\patri\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.1)
    • VS Code at C:\Users\patri\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0
**FLUTTER DOCTOR -V**


[√] Connected device (1 available)
    • Mi A2 Lite • 6bde6a3d0305 • android-arm64 • Android 9 (API 28)

• No issues found!


**MAIN.DART**
import 'package:chewie_tutorial/chewie_list_item.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: ChewieListItem(
          videoPlayerController: VideoPlayerController.network(
            'https://yviistreamer.kernel.online/hls/samuele.m3u8',
          ),
        ),
      ),
    );
  }
}



**CHEWIE_LIST_ITEM.DART**
import 'package:chewie/chewie.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class ChewieListItem extends StatefulWidget {
  // This will contain the URL/asset path which we want to play
  final VideoPlayerController videoPlayerController;
  final bool looping;

  ChewieListItem({
    @required this.videoPlayerController,
    this.looping,
    Key key,
  }) : super(key: key);

  @override
  _ChewieListItemState createState() => _ChewieListItemState();
}

class _ChewieListItemState extends State<ChewieListItem> {
  ChewieController _chewieController;

  @override
  void initState() {
    super.initState();
    // Wrapper on top of the videoPlayerController
    _chewieController = ChewieController(
      videoPlayerController: widget.videoPlayerController,
      aspectRatio: 16 / 9,
      // Prepare the video to be played and display the first frame
      autoInitialize: true,
      looping: widget.looping,
      // Errors can occur for example when trying to play a video
      // from a non-existent URL
      errorBuilder: (context, errorMessage) {
        return Center(
          child: Text(
            errorMessage,
            style: TextStyle(color: Colors.white),
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Chewie(
        controller: _chewieController,
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    // IMPORTANT to dispose of all the used resources
    widget.videoPlayerController.dispose();
    _chewieController.dispose();
  }
}

**Comment by iapicca** [comment]
Hi @ptrkst 
I see that you are also using a 3rd party [plugin](https://pub.dev/packages/chewie)
are you experiencing the same issue using only [video_player](https://pub.dev/packages/video_player)?
Is the smart box TV running android  (which version)?
thank you

**Comment by ptrkst** [comment]
The TV smart box runs Android. The plugin used is chewie based on video_player.

**chewie** https://pub.dev/packages/chewie

**Comment by iapicca** [comment]
Hi @ptrkst 
please consider opening an issue in the dedicated [github](https://github.com/brianegan/chewie/issues)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
