### ISSUE TITLE
[local_auth] getAvailableBiometrics does not return "enrolled" biometrics, it returns present hardware on Android

### ISSUE THREAD

**Issue by erdemyerebasmaz** [flutter/flutter#45497]
Hello Flutter Team,
## Use case
I'd like to enable biometrics authentication on Android if there's enrolled biometrics. As I see it, there's no way to know if there's enrolled biometrics unless you call authenticate method and catch  NotEnrolled exception on Android.
```
/// Indicates the user has not enrolled any fingerprints on the device.
const String notEnrolled = 'NotEnrolled';
```
I'm assuming enrolled means that the hardware is present and there's at least one configured fingerprint on device according to this comment.

Although, getAvailableBiometrics method is described as:
```
  /// Returns a list of enrolled biometrics
  ///
  /// Returns a [Future] List<BiometricType> with the following possibilities:
  /// - BiometricType.face
  /// - BiometricType.fingerprint
  /// - BiometricType.iris (not yet implemented)
```
current getAvailableBiometrics returns the list of present hardware on the device, not enrolled biometrics.

```
if (Build.VERSION.SDK_INT >= 23) {
   if (packageManager.hasSystemFeature(PackageManager.FEATURE_FINGERPRINT)) {
    biometrics.add("fingerprint");
   }
}
```
![image](https://user-images.githubusercontent.com/4012752/69498358-3f9aa880-0ef8-11ea-9941-80d302802dcf.png)

## Proposal

As a workaround, I encapsulated the part where we populate _ArrayList<String> biometrics_ with
```
                        ⋮
final BiometricManager biometricManager = BiometricManager.from(activity);
if(biometricManager.canAuthenticate() == BiometricManager.BIOMETRIC_SUCCESS) {
                        ⋮
}
                        ⋮
```
It serves it purpose well as a workaround but I believe this can result in a false list of biometrics where the device has both fingerprint and face features and only one of them is enrolled.

It would be really great if you could provide a more comprehensive solution to this problem so it returns enrolled biometrics accurately compared to my workaround.

**Comment by ben04** [comment]
I'm facing the same problem, a solution would be great!

**Comment by lzhuor** [comment]
Facing the same problems.

**Comment by us3soap** [comment]
Same problems

**Comment by evelyne24** [comment]
The fact this is missing creates a really bad user experience. Since all devices nowadays have biometrics, it feels like a high priority bug to fix.

**Comment by stuartmorgan** [comment]
Marking as a bug, rather than a feature request, since it's inconsistent with the iOS implementation.

**Comment by Dohmanlechx** [comment]
I don't mean to be rude, but how come this still is not fixed yet? This is a serious issue, giving the user bad UX while asked to use biometrics when they even haven't enrolled any biometrics in their phones (by that case it's most likely they even don't know about that). We never had these issues until newer versions.

**Comment by blasten** [comment]
@bparrishMines would you mind taking a look?

**Comment by stuartmorgan** [comment]
https://github.com/flutter/plugins/pull/3763#issuecomment-815033841 has a summary of where I had gotten to when investigating this; tl;dr is that we should, as part of fixing this, rewrite on the new Android APIs and update the Dart API surface to reflect the change to categories of auth types rather than specific auth modes.

**Comment by mxa0079** [comment]
Hello Flutter Community, 

We are also facing this issue. Sometimes a user will have fingerprint and face biometrics hardware but will have only one of them enrolled and the plugin will try to use that one- resulting in a crash. 

Other times the user will not have any of them enrolled and the plugin will try to use them nonetheless, also resulting on a crash. 

How can we help to accelerate a solution to this issue? This is our highest priority and highest frequency bug. 

Please help!

**Comment by stuartmorgan** [comment]
> How can we help to accelerate a solution to this issue?

Anyone interested in submitting a PR that implements what I described in the comment I linked to above is welcome to do so.

**Comment by mxa0079** [comment]
Thanks @stuartmorgan - could we get a commitment to get a timely review of the PR if we do so? Will it get accepted without tests?

**Comment by stuartmorgan** [comment]
> could we get a commitment to get a timely review of the PR if we do so?

I can make an effort to prioritize a review; I can't specifically commit to how exactly it will balance against other priorities.

> Will it get accepted without tests?

No, the contribution guide is very clear about the testing requirements for PRs.

**Comment by mxa0079** [comment]
Hello @stuartmorgan - thanks for your reply.

Unfortunately, we can´t afford to assign anyone to work on this right away since the team is purely focused on meeting regulatory requirements to meet a government deadline. Especially without having a guarantee from Google that it will be reviewed in a timely manner.

The issue has been open for almost two years, has lots of comments and upvotes, affects any Android device that has two biometric and fingerprint hardware, and the proposed workaround does not solve the underlying issue. What else is needed to raise the priority of this issue to something above P3?


Community - please help upvoting this issue and post if this is relevant to you.

**Comment by stuartmorgan** [comment]
> The issue has been open for almost two years, has lots of comments and upvotes

Many issues have been open for several years, and many have lots of comments an upvotes. This isn't even in the top 250 issue by votes, to provide some context. We understand that people want this fixed, and we do too, but the same is true of all of those other issues as well. We are prioritizing across a *very* large workload. We, like you, are engineering-resource constrained.

> What else is needed to raise the priority of this issue to something above P3?

Flutter's escalation policy for issues is described here: https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed

**Comment by doc-rj-celltrak** [comment]
Slight correction @mxa0079 -- this impacts any Android device with *any* biometrics support, not just those with two (or more) types of biometrics.

**Comment by fransboumans** [comment]
Any updates on this? Still facing this problem in 1.1.9. Using a device supporting both finger and face. None of them is set and when running canCheckBuimetric and isDeviceSupported they both return true. When running getAvailableBiometrics it returns BiometricType.fingerprint and face. Even when running authenticate inside a try-catch it does crash. Console gives the error Unhandled Exception: PlatformException(NotEnrolled, No biometrics enrolled on this device.

**Comment by darwin-morocho** [comment]
> Any updates on this? Still facing this problem in 1.1.9. Using a device supporting both finger and face. None of them is set and when running `canCheckBiometric` and `isDeviceSupported` they both return `true`. When running `getAvailableBiometrics` it returns `BiometricType.fingerprint` and `BiometricType.face`. Even when running `authenticate` inside a try-catch it still crashes. Console gives the error `Unhandled Exception: PlatformException(NotEnrolled, No biometrics enrolled on this device., null, null)`.

This PR https://github.com/flutter/plugins/pull/4682 should fix this.  Now with this PR canCheckBiometrics returns false on Android if device has the biometric hardware but doesn't have any biometric enrolled.

**Comment by MingSern** [comment]
Any solution for this? Really need the `enrolled` biometric value

**Comment by vigdora** [comment]
any update on this?
