### ISSUE TITLE
my flutter is crashing

### ISSUE THREAD

**Issue by taend** [flutter/flutter#45495]
C:\Users\ok\Desktop\try\hello>flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling
software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                                 |
Oops; flutter has exited unexpectedly.          Sending crash report to Google.
Crash report sent (report ID: 7c356d2319e6ecd1)
Initializing gradle...                                                                                                 \Crash report written to C:\Users\ok\Desktop\try\hello\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by jonahwilliams** [comment]
@taend we need the contents of flutter_02.log to help

**Comment by Hixie** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
