### ISSUE TITLE
The getter 'cutButtonLabel' was called on null. Stable Channel

### ISSUE THREAD

**Issue by StephanCassel** [flutter/flutter#45493]
This happens on all TextFields when you long tap or double tap the field. 
Only iOS. Stable v1.9.1+hotfix.6 Channel

The getter 'cutButtonLabel' was called on null.

As previous mentioned it works if language is English. For example if Norwegian is selected it crashes. 
 
Serious Show Stopper.

![12257](https://user-images.githubusercontent.com/5372762/69497236-eff9b400-0eda-11ea-9c26-7a3ec09e48f5.jpg)

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale en-NO)
    • Flutter version 1.9.1+hotfix.6 at /Users/stephan/development/flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/stephan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

**Comment by StephanCassel** [comment]
**platform: TargetPlatform.android** seems to fix the problem. 
First sign of this very problem can be seen in 2018. 
I hope this problem can be solved soon.
Thanks in advanced.

**Comment by iapicca** [comment]
Hi @StephanCassel 
Please follow up on this [issue](https://github.com/flutter/flutter/issues/43050),
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
