### ISSUE TITLE
Flutter Packages are not getting properly

### ISSUE THREAD

**Issue by jamiethain** [flutter/flutter#45509]
After it working on Windows 10 and VS Code, I now have one package that says the URI: is unavailable. 

This is documented in issue 17565 quite heavily. The one thing I can add is that a reboot, and restart fixed it. While the problem existed that the package is NOT in the typeahead.  

The package would actually run if you told Visual studio to "ignore the errors" 

Wherever visual studio is keeping this must be defective in someway. 

Jamie

**Comment by iapicca** [comment]
Hi @jamiethain 
the [issue ](https://github.com/flutter/flutter/issues/17565)you mentioned contains a proposed [solution](https://github.com/flutter/flutter/issues/17565#issuecomment-406562574),
could you please check if works for you?
Thank you

**Comment by jamiethain** [comment]
Well those all look to be on a Mac it was when i moved from my Mac to work
on my PC because it's much faster. Fresh install had the issue.

Reboot fixed it spent 5 hours on it.

Jamie

**Comment by iapicca** [comment]
Hi @jamiethain 
I'm glad that you solved the issue
thank you for letting me know

**Comment by jamiethain** [comment]
Yikes. Not fixed but likely a problem with VS Code but closed.

**Comment by iapicca** [comment]
Hi @jamiethain 
my apologize, I misunderstood your answer.
If you are still experiencing this issue with the latest version of Flutter
please provide your updated `flutter doctor -v` and the error log
thank you

**Comment by jamiethain** [comment]
What I was stating is somewhere the .vscode cache seems to become corrupt, and a reboot fixes it. I am not sure where to look for the problem, and I remember flutter doctor from the day, as I did flutter doctor, + flutter clean, flutter upgrade and eventually the reboot makes it go away. 

it is what it is as far as I am concerned you can keep it closed, as I have done two upgrades of visual studio.  I will reopen if I can make it do it again.

**Comment by DanTup** [comment]
FWIW, there's nothing cached in VS Code here. A reboot shouldn't do anything different from just closing/re-openeding VS Code (or even just running the **Reload Window** command).

The issue in #17565 seems like an old issue where running `flutter packages get` didn't cause the analysis server to re-read the packages. This was fixed a while ago, so I suspect this is different.

If you can reproduce this, please let me know (and include a clear description of what you did, whether the package was added to the `.packages` file, and whether restarting VS Code without rebooting solved it). Thanks!

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
