### ISSUE TITLE
Support FontLoader API in the CanvasKit backend

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#45507]
@hterkelsen from https://github.com/flutter/engine/pull/13999#issuecomment-557845419

> Yes, CanvasKit does have a different font loader, but unfortunately the only FontMgr API that CanvasKit exposes requires us to initialize the FontMgr with all of the fonts downloaded into buffers. I think rather than trying to support this in CanvasKit currently (which would require us to cache all of the downloaded fonts so we can recreate the FontMgr when we get a new font), we should get a better FontMgr API from CanvasKit.

This issue tracks adding support for loading fonts in the CanvasKit backend

**Comment by hterkelsen** [comment]
This was fixed in this PR: https://github.com/flutter/engine/pull/16504
