### ISSUE TITLE
Huawei mate 20 Pro selects pictures from the gallery and submits them to flash back

### ISSUE THREAD

**Issue by hgwx** [flutter/flutter#45514]
Huawei mate 20 Pro selects pictures from the gallery and submits them to flash back

**Comment by iapicca** [comment]
Hi @hgwx 
can you please describe the issue in detail
and provide your `flutter doctor -v` and 
a minimal code sample to reproduce the problem?
thank you

**Comment by Hixie** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
