### ISSUE TITLE
Can I use Material deisgn 2.0 in Flutter?

### ISSUE THREAD

**Issue by nullptrjzz** [flutter/flutter#45516]
Hi, I wonder that whether flutter supports Material Design 2.0. Material Design 2.0 looks better than 1.0 and Google has applied it to many of its apps or web pages. I also want to use it in my apps but Flutter seems to support MD1.0 only, and I think there is a need to implement MD 2.0 in Flutter with official support.

Thanks.

**Comment by iapicca** [comment]
Hi @nullptrjzz 
I believe [Material Components widgets](https://flutter.dev/docs/development/ui/widgets/material) 
already implements the `Material Design guidelines` ;
could you please elaborate what features you find missing?
thank you

**Comment by nullptrjzz** [comment]
Ok. Let's take the TabBar widget for example, `Google Play Store` (which uses Material Design 2.0) uses `TabIndicator` with rounded corners but Flutter's `TabIndicator` doesn't. (Material Design 2.0 makes widgets look more rounded.)

**Comment by Zazo032** [comment]
> Ok. Let's take the TabBar widget for example, `Google Play Store` (which uses Material Design 2.0) uses `TabIndicator` with rounded corners but Flutter's `TabIndicator` doesn't. (Material Design 2.0 makes widgets look more rounded.)

That's Google's own implementation of Material Design Theming for its apps, not Material Design 2.0

**Comment by HansMuller** [comment]
@Zazo032 - thanks, that's correct. Flutter implements the current spec (aka "Material 2"), so tabs are supposed to match https://material.io/components/tabs

That said, if there are components that don't match the current spec, we'd like to hear about it.

**Comment by nullptrjzz** [comment]
Thanks a lot. I will goint to try implementing what I want.
