### ISSUE TITLE
How to display an arbitrary screen by passing parameters at startup

### ISSUE THREAD

**Issue by sh-ogawa** [flutter/flutter#45517]
I want to display any screen by tapping the push notification.

When the app is running and in the background, it can be done by using a package "get_it".

I can't figure out how to display an arbitrary screen when a tap notification is tapped when the app is not running.
Now the normal boot process runs and displays the first screen.
If there is a way to start the Flutter app by passing parameters, can you run something different from the normal boot process? I think.

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
