### ISSUE TITLE
MaterialApp.builder introducing strange context issues

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#45512]
I'm trying to use MaterialApp.builder() to wrap all my views, in an enclosing 'RootView' widget, which contains the Scaffold. 

So, looks something like this: 
````
MaterialApp(
   builder: (context, route) {
     return RootView(child: route);
   },
   home: Page1(),
)

class RootView extends StatelessWidget {
  final Widget child;

  const RootView({Key key, this.child}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      drawer: Container(width: 200, color: Colors.red),
      body: child,
    );
  }
}

````

When I do this, I get some weird behavior in my Scaffold.

1. The default "leading" icon for the drawer, throws an `No Overlay widget found.` error. Screenshot: http://treefortress.com/shared/qemu-system-i386_2019-11-24_16-22-11.png

2. When trying to call showBottomSheet(), I get an error `The method 'addLocalHistoryEntry' was called on null.`, this seems to be because the ModelRoute.of() call inside Scaffold, is returning null. 

What gives? 

If I omit builder, and do the exact same thing inside Home, everything works as expected. 

So this works fine:
````
MaterialApp(
   home: RootView(child: Page1()),
)
````
This does not:
````
MaterialApp(
   builder: (context, route) => RootView(child: route),
   home: Page1(),
)
````

As I understand the builder usage, these should be functionally equivalent?? 

Wrapping everything in Home is not a real solution, as I want a persistent Scaffold, AppBar and Drawer, with only the body of the scaffold changing each time a new page is pushed to the Navigator. 

UPDATE
I've found 2 workaround that get the job done.
1. Using the MaterialApp.onGeneratedRoute method, and wrapping the RootView there
2. When pushing a new route, wrap the RootView there:
````
Navigator.of(context).push(
    MaterialPageRoute(builder: (context) => RootView(child: Page2())),
);
````

**Comment by iapicca** [comment]
Hi  @esDotDev 

given your last update

> UPDATE
> I've found 2 workaround that get the job done.
> 
> 1. Using the MaterialApp.onGeneratedRoute method, and wrapping the RootView there
> 2. When pushing a new route, wrap the RootView there:
> 
> ```
> Navigator.of(context).push(
>     MaterialPageRoute(builder: (context) => RootView(child: Page2())),
> );
> ```

 I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by esDotDev** [comment]
Hey, no I don't feel like this should be closed, as the workaround should not be necessary, and something is still broken with builder(). I would love to have some clarification around what is happening, and why builder does not work in this case.

**Comment by esDotDev** [comment]
I don't understand closing this. It's a clear bug in the API. You'd think you'd at least want to track it?

**Comment by darshankawar** [comment]
Issue # 1 and 2 are replicable on latest dev channel.

**Comment by esDotDev** [comment]
Now that I understand Material App better, I'm not sure this is a bug. The child returned by builder is the navigator object itself, not the child route. This means that you can't use Builder in this way, you can not inject anything between MaterialApp and Navigator, like I'm trying to do with Scaffold.

**Comment by deepak786** [comment]
> Now that I understand Material App better, I'm not sure this is a bug. The child returned by builder is the navigator object itself, not the child route. This means that you can't use Builder in this way, you can not inject anything between MaterialApp and Navigator, like I'm trying to do with Scaffold.

@esDotDev I don't understand your point here. 
If I try to provide the leading by myself or set the automaticallyImplyLeading to false in the app bar then there is no error.
```
 AppBar(automaticallyImplyLeading: false),
```

Also if I use Column or ListView as root widget of Scaffold Body then that also not working.
