### ISSUE TITLE
Shake gesture testing in flutter driver

### ISSUE THREAD

**Issue by pradarttana-sharechat** [flutter/flutter#45523]
The app where I am testing needs shake gesture. 

please add a shake gesture in flutter driver to test it. 

flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.5 18F203, locale en-IN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Community Edition (version 2019.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by iapicca** [comment]
Hi @pradarttana-sharechat 
I believe it's already  possible 
to mock an `AccelerometerEvent` for the [sensors](https://pub.dev/packages/sensors) package,
did you try this solution?
thank you

**Comment by Hixie** [comment]
Can you elaborate on what you mean by "shake gesture" and how you are recognizing it?
