### ISSUE TITLE
[maps] Unhandled Exception: MissingPluginException Flutter (Channel dev, v1.12.11)

### ISSUE THREAD

**Issue by pamir72** [flutter/flutter#45522]
When I start build my app on Android (even example from google_maps_flutter plugin) I get:

E/flutter ( 9819): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method map#update on channel plugins.flutter.io/google_maps_0)
E/flutter ( 9819): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter ( 9819): <asynchronous suspension>
E/flutter ( 9819): #1      GoogleMapController._updateMapOptions (package:google_maps_flutter/src/controller.dart:96:19)
E/flutter ( 9819): #2      _GoogleMapState._updateOptions (package:google_maps_flutter/src/google_map.dart:256:16)
E/flutter ( 9819): <asynchronous suspension>
E/flutter ( 9819): #3      _GoogleMapState.didUpdateWidget (package:google_maps_flutter/src/google_map.dart:241:5)
E/flutter ( 9819): #4      StatefulElement.update (package:flutter/src/widgets/framework.dart:4396:58)
E/flutter ( 9819): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 9819): #6      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
E/flutter ( 9819): #7      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
E/flutter ( 9819): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
......

E/flutter (12481): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter (12481): #39     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
E/flutter (12481): #40     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
E/flutter (12481): #41     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
E/flutter (12481): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter (12481): #43     SingleChildRenderObjectElement.update (package:flutter/s
**✓ Built build/app/outputs/apk/debug/app-debug.apk.
Syncing files to device AOSP on IA Emulator...**

----------
google_maps_flutter 0.5.21+12

[✓] Flutter (Channel dev, v1.12.11, on Mac OS X 10.15.1 19B88, locale ru-RU)
    • Flutter version 1.12.11 at /Users/pavelmiheev/Flutter
    • Framework revision f40dbf8ca0 (2 days ago), 2019-11-23 01:02:54 -0500
    • Engine revision d1cac77d5a
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/pavelmiheev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

-----------

To reproduce the  issue simply run example from google_maps_flutter plugin

**Comment by iapicca** [comment]
Hi @pamir72 
could you please provide a minimal code sample to reproduce the problem?
Thank you

**Comment by pamir72** [comment]
@iapicca 
Please use official example from google_maps_flutter plugin

**Comment by pamir72** [comment]
Clarification: This issue constantly appears on the emulator. On a real device there are no such issues

**Comment by spitfire55** [comment]
Any updates on this? There are now numerous issues on this issue tracker related to a MissingPluginException error taken that depend on the Google Maps controller (update, animate, etc.), and all of these issues have received zero feedback or advice.

**Comment by darshankawar** [comment]
There's similar open issue describing this case, https://github.com/flutter/flutter/issues/43785
Closing this in favor of 43785.
