### ISSUE TITLE
Crash in WidgetsApp.basicLocaleListResolution when android system in special locale

### ISSUE THREAD

**Issue by singun-lxd** [flutter/flutter#45525]
I've found a flutter framework crash, it is about the locale resolution. If I change the devices into Uno locale (may be you can find this locale in Samsung devices), the flutter app crash when started.
The code with this problem is in package:flutter:widgets/app.dart, WidgetsApp.basicLocaleListResolution, line 919:
```
...
      final Locale userLocale = preferredLocales[localeIndex];
      // Look for perfect match.
      if (allSupportedLocales.containsKey('${userLocale.languageCode}_${userLocale.scriptCode}_${userLocale.countryCode}')) {
        return userLocale;
      }
...
```
the variable userLocale may be null, nullpointer exception occurred  in the if statement.

I've solve the problem by rewrite a LocaleListResolution function. please fix this in the future flutter version, thanks.

## Steps to Reproduce

1. Change system language to Und
2. Start flutter application
3. crash...

**Target Platform:** Android
**Target OS version/browser:** All
**Devices:** All can change system language to Und

## Logs

**the log is 2month ago but this problem still exist in the latest flutter version**

09-23 03:48:15.519  1739  1755 I flutter : ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
09-23 03:48:15.519  1739  1755 I flutter : The following NoSuchMethodError was thrown building ScrollConfiguration(behavior:
09-23 03:48:15.519  1739  1755 I flutter : _MaterialScrollBehavior):
09-23 03:48:15.519  1739  1755 I flutter : The getter 'languageCode' was called on null.
09-23 03:48:15.519  1739  1755 I flutter : Receiver: null
09-23 03:48:15.519  1739  1755 I flutter : Tried calling: languageCode
09-23 03:48:15.519  1739  1755 I flutter : 
09-23 03:48:15.519  1739  1755 I flutter : Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
09-23 03:48:15.519  1739  1755 I flutter : be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.
09-23 03:48:15.519  1739  1755 I flutter : 
09-23 03:48:15.519  1739  1755 I flutter : When the exception was thrown, this was the stack:
09-23 03:48:15.519  1739  1755 I flutter : #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
09-23 03:48:15.519  1739  1755 I flutter : #1      _WidgetsAppState.basicLocaleListResolution (package:flutter/src/widgets/app.dart:921:57)
09-23 03:48:15.519  1739  1755 I flutter : #2      _WidgetsAppState._resolveLocales (package:flutter/src/widgets/app.dart:844:12)
09-23 03:48:15.519  1739  1755 I flutter : #3      _WidgetsAppState.initState (package:flutter/src/widgets/app.dart:714:15)
09-23 03:48:15.519  1739  1755 I flutter : #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
09-23 03:48:15.519  1739  1755 I flutter : #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
09-23 03:48:15.519  1739  1755 I flutter : #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
09-23 03:48:15.519  1739  1755 I flutter : #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
09-23 03:48:15.519  1739  1755 I flutter : #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
09-23 03:48:15.519  1739  1755 I flutter : #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
09-23 03:48:15.519  1739  1755 I flutter : #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
09-23 03:48:15.519  1739  1755 I flutter : #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
09-23 03:48:15.519  1739  1755 I flutter : #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
09-23 03:48:15.519  1739  1755 I flutter : #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
09-23 03:48:15.519  1739  1755 I flutter : #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
09-23 03:48:15.519  1739  1755 I flutter : #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
09-23 03:48:15.519  1739  1755 I flutter : #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
09-23 03:48:15.519  1739  1755 I flutter : #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
09-23 03:48:15.519  1739  1755 I flutter : #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
09-23 03:48:15.519  1739  1755 I flutter : #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
09-23 03:48:15.519  1739  1755 I flutter : #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
09-23 03:48:15.519  1739  1755 I flutter : #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
09-23 03:48:15.519  1739  1755 I flutter : #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
09-23 03:48:15.519  1739  1755 I flutter : #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
09-23 03:48:15.519  1739  1755 I flutter : #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
09-23 03:48:15.519  1739  1755 I flutter : #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
09-23 03:48:15.519  1739  1755 I flutter : #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
09-23 03:48:15.519  1739  1755 I flutter : #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
09-23 03:48:15.519  1739  1755 I flutter : #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
09-23 03:48:15.519  1739  1755 I flutter : #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
09-23 03:48:15.519  1739  1755 I flutter : #30     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
09-23 03:48:15.519  1739  1755 I flutter : #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
09-23 03:48:15.519  1739  1755 I flutter : #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
09-23 03:48:15.519  1739  1755 I flutter : #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
09-23 03:48:15.519  1739  1755 I flutter : #34     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:998:16)
09-23 03:48:15.519  1739  1755 I flutter : #35     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:969:5)
09-23 03:48:15.519  1739  1755 I flutter : #36     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:915:17)
09-23 03:48:15.519  1739  1755 I flutter : #37     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2328:19)
09-23 03:48:15.519  1739  1755 I flutter : #38     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:914:13)
09-23 03:48:15.519  1739  1755 I flutter : #39     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:795:7)
09-23 03:48:15.519  1739  1755 I flutter : #40     runApp (package:flutter/src/widgets/binding.dart:845:7)
09-23 03:48:15.519  1739  1755 I flutter : #41     main (package:heiwala/main.dart:13:3)
09-23 03:48:15.519  1739  1755 I flutter : #51     _mainInit (package:heiwala/main.dart)
09-23 03:48:15.519  1739  1755 I flutter : #61     MainInit.sync (package:heiwala/modules/global/main_init.dart)
09-23 03:48:15.519  1739  1755 I flutter : #71     AndroidAlarmManager.initialize (package:android_alarm_manager/android_alarm_manager.dart)
09-23 03:48:15.519  1739  1755 I flutter : #81     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
09-23 03:48:15.519  1739  1755 I flutter : (elided 50 frames from package dart:async and package dart:async-patch)

```
```

```
```

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/singun/Library/Flutter/sdk
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/singun/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/singun/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

```
```

**Comment by iapicca** [comment]
Hi @singun-lxd 
could you please post a minimal code sample or the steps to reproduce the problem?
Thank you

**Comment by singun-lxd** [comment]
> Hi @singun-lxd
> could you please post a minimal code sample or the steps to reproduce the problem?
> Thank you

Hi @iapicca We found it crash in every demo project, e.g. create a new project from Android Studio.
It can be reproduced when using a genymotion emulator and change system language to Uno.
Unfortunately, you may not find Uno language in new version of  genymotion system image, we test in our mac with an old image installed.

**Comment by pedromassangocode** [comment]
Hi @singun-lxd 
Are you still facing this issue? If yes, please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by singun-lxd** [comment]
@pedromassangocode no, I cannot reproduce this issue

**Comment by pedromassangocode** [comment]
Hi @singun-lxd 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
