### ISSUE TITLE
Error connecting to the service protocol: HttpException:

### ISSUE THREAD

**Issue by qiuguian** [flutter/flutter#45520]
![image](https://user-images.githubusercontent.com/7962840/69508803-b6c05300-0f71-11ea-8744-b3ae7c97e161.png)

**Comment by iapicca** [comment]
Hi @qiuguian 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose` or `flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem.
Please refrain from posting pictures if not necessary.
Thank you
