### ISSUE TITLE
[image_picker] MI6 After taking a photo, the image will be rotated 90 degrees to the right

### ISSUE THREAD

**Issue by DearBo7** [flutter/flutter#45529]
After taking a photo, the image will be rotated 90 degrees to the right.

image_picker: ^0.6.2+1

```dart
File image = await ImagePicker.pickImage(source: ImageSource.camera);
await image.copy(copyPath);

File compressImage = await FlutterImageCompress.compressAndGetFile(
          image.path, newPath,
          minWidth: 640,
          minHeight: 640,
          quality: 90);
// The image and compressImage image orientations are the same.
```
![Photo](https://user-images.githubusercontent.com/29586966/69524878-facb4c00-0fa1-11ea-9d49-d6be93c4a8f4.png)

![CompressImage  File](https://user-images.githubusercontent.com/29586966/69524940-0f0f4900-0fa2-11ea-9b5b-e300b43d9843.png)

[√] Flutter (Channel beta, v1.11.0, on Microsoft Windows [Version 10.0.18362.418], locale zh-CN)
    • Flutter version 1.11.0 at D:\android\sdk\flutter
    • Framework revision 856a90e67c (2 weeks ago), 2019-11-08 18:00:01 -0800
    • Engine revision af04338413
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\android\sdk\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: A:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at A:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • MI 6 • d8086ba8 • android-arm64 • Android 9 (API 28)

**Comment by iapicca** [comment]
Hi @DearBo7 
as mentioned your recent [issue](https://github.com/flutter/flutter/issues/45227) 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/35334)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
