### ISSUE TITLE
Using a navigation context inside a tabview leads to a `NoSuchMethodError: The getter 'focusScopeNode' was called on null`

### ISSUE THREAD

**Issue by anfelor** [flutter/flutter#45539]
## Steps to Reproduce

1. Open the flutter app under https://gist.github.com/anfelor/a83ba83f4e15653b6ec877148925fd60
2. Start the app
3. Intially the left tab is open. Click on the right one.
4. Notice how the bug vanishes when we remove the `ownNavigationContext` from the middle tab.

**Target Platform:** Android
**Target OS version/browser:** Android 10
**Devices:** Only physical device was tested

## Logs

```
[+5708 ms] E/flutter (16899): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'focusScopeNode' was called on null.
[        ] E/flutter (16899): Receiver: null
[        ] E/flutter (16899): Tried calling: focusScopeNode
[        ] E/flutter (16899): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
[        ] E/flutter (16899): #1      Route.didPush.<anonymous closure> (package:flutter/src/widgets/navigator.dart:139:17)
[        ] E/flutter (16899): #2      _rootRunUnary (dart:async/zone.dart:1134:38)
[        ] E/flutter (16899): #3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
[        ] E/flutter (16899): #4      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
[        ] E/flutter (16899): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
[        ] E/flutter (16899): #6      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
[        ] E/flutter (16899): #7      Future._completeWithValue (dart:async/future_impl.dart:524:5)
[        ] E/flutter (16899): #8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
[        ] E/flutter (16899): #9      _rootRun (dart:async/zone.dart:1126:13)
[        ] E/flutter (16899): #10     _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] E/flutter (16899): #11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
[        ] E/flutter (16899): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
[        ] E/flutter (16899): #13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
[        ] E/flutter (16899): #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
[        ] E/flutter (16899): 
[ +219 ms] E/flutter (16899): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'focusScopeNode' was called on null.
[        ] E/flutter (16899): Receiver: null
[        ] E/flutter (16899): Tried calling: focusScopeNode
[        ] E/flutter (16899): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
[        ] E/flutter (16899): #1      Route.didPush.<anonymous closure> (package:flutter/src/widgets/navigator.dart:139:17)
[        ] E/flutter (16899): #2      _rootRunUnary (dart:async/zone.dart:1134:38)
[        ] E/flutter (16899): #3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
[        ] E/flutter (16899): #4      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
[        ] E/flutter (16899): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
[        ] E/flutter (16899): #6      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
[        ] E/flutter (16899): #7      Future._completeWithValue (dart:async/future_impl.dart:524:5)
[        ] E/flutter (16899): #8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
[        ] E/flutter (16899): #9      _rootRun (dart:async/zone.dart:1126:13)
[        ] E/flutter (16899): #10     _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] E/flutter (16899): #11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
[        ] E/flutter (16899): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
[        ] E/flutter (16899): #13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
[        ] E/flutter (16899): #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
[        ] E/flutter (16899): 
```

```
Analyzing flutter_bug...                                                
No issues found! (ran in 2.1s)
```

```
[✓] Flutter (Channel master, v1.12.8-pre.17, on Linux, locale de_DE.utf8)
    • Flutter version 1.12.8-pre.17 at /home/anton/.local/bin/flutter
    • Framework revision 4c64b715d9 (3 days ago), 2019-11-21 22:12:24 -0800
    • Engine revision 7e68097cc1
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/anton/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/anton/.local/bin/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 3.5)
    • Android Studio at /home/anton/.local/bin/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.6.0

[✓] Connected device (3 available)
    • HD1903     • 7d6b23ca   • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome     • web-javascript • Chromium 78.0.3904.108 Built on Ubuntu , running on Ubuntu 19.04
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

Possibly connected to https://github.com/flutter/flutter/issues/42829

**Comment by iapicca** [comment]
Hi @anfelor 
I'm not sure that it's the right implementation of [TabBarView](https://flutter.dev/docs/catalog/samples/TabBarView),
the sample on the documentation might not be up-to-date
I wrote a [sample code](https://gist.github.com/iapicca/21a14022a99d1f394678721ccfb1e51f) for you, is this the behaviou you expected?
thank you

**Comment by anfelor** [comment]
@iapicca I followed the approach outlined in the [cookbook](https://flutter.dev/docs/cookbook/design/tabs). I tried your code sample but it shows the same error when I give each tab its own navigation context. If I don't do that it doesn't show the behavior I expected, because I want the tab bar to stay visible when I `Navigator.push()` another route in a tab.

**Comment by Blaxou** [comment]
I confirm, I'm facing the same issue whilst using different Navigators for each tabs, so it seems it is due to the Navigators ?

**Comment by dudizimber** [comment]
I'm really not sure if it will help, I didn't open your code, but I had the same issue and I solved using 
`Navigator.of(context, rootNavigator: true)..pop()..pop();`

**Comment by softronaut** [comment]
I have same issue and before 1.12 update I didn't face anything like this.

@dudizimber your solution is worked by the way, it navigates now but throws error which can't be handled by putting `Navigator` method inside `try/catch` and that's not good for Crashlytics.

**Comment by LudySu** [comment]
I am facing the same `Navigator` crash and my sample code is much simpler. As you can see the code below, if a dialog is dismissed immediately (by pressing `To crash` button) it causes this crash; while if there's some delay in between (by pressing `Not crash` button), there's no crash. Tested on Android 9/iOS 13 simulators.

My observations are:

1. With Flutter `v1.9.1` stable release, there's no crash
2. After upgraded to `v1.12.13` stable release, crash occurs

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: <Widget>[
            Text('Click the first button to reproduce the crash'),
            RaisedButton(child: Text('To crash'), onPressed: () {_onButtonPressed(false, context);}),
            RaisedButton(child: Text('Not crash'), onPressed: () {_onButtonPressed(true, context);})
          ],
        ),
      ),
    );
  }

  void _onButtonPressed(bool withDelay, BuildContext context) async {
    showDialog(
      context: context,
      builder: (BuildContext buildContext) {
        return SimpleDialog(
          title: Center(child: Text('In progress')),
          children: <Widget>[Center(child: CircularProgressIndicator())],
        );
      });

    // Some backend API calls supposed to be here
    if (withDelay) {
      await Future.delayed(Duration(milliseconds: 500)); // With this line it won't crash, even 1ms delay is enough
    }

    Navigator.of(context, rootNavigator: true).pop();
  }
}
```

So my question is, is it OK to dismiss a dialog immediately after it is shown?

**Comment by basnetjiten** [comment]
I was facing a similar problem and I noticed that removing async from the onPressed() method solved the problems. I am using flutter 1.12.13 hotfix 5.

**Comment by LudySu** [comment]
@basnetjiten Thanks for sharing! That's interesting... I tried it's true, but I have some async backend API calls inside my `onPressed()`, so not practical to me.

I won't be able to notice this if it wasn't for unit-test. In real life there's always some delay with backend calls so no crash would be ever visible; but in a unit-test case I wrote, the mocking backend API  throws an exception immediately, hence seeing this issue.

**Comment by basnetjiten** [comment]
> @basnetjiten Thanks for sharing! That's interesting... I tried it's true, but I have some async backend API calls inside my `onPressed()`, so not practical to me.
> 
> I won't be able to notice this if it wasn't for unit-test. In real life there's always some delay with backend calls so no crash would be ever visible; but in a unit-test case I wrote, the mocking backend API throws an exception immediately, hence seeing this issue.

I will better write the standalone method or Bloc which does the work asynchronously ;)

**Comment by gspencergoog** [comment]
@LudySu  Wouldn't adding an await to the example do what you want?:

```dart
  void _onButtonPressed(BuildContext context) async {
    // Add await before showDialog.
    await showDialog(
      context: context,
      builder: (BuildContext buildContext) {
        return SimpleDialog(
          title: Center(child: Text('In progress')),
          children: <Widget>[Center(child: CircularProgressIndicator())],
        );
      },
    );
    Navigator.of(context, rootNavigator: true).pop();
  }
```
I'm unable to get a crash to happen (on master), but the dialog also doesn't come up when I push the "To crash" button (and does briefly when I push the other one).

I think the problem is that you're popping the root route before the `showDialog` can push its own route. If you delay (or await), then the root navigator is still there when the dialog's route gets pushed, so the route you end up popping is the dialog's route.

**Comment by LudySu** [comment]
> @LudySu Wouldn't adding an await to the example do what you want?:
> 
> ```dart
>   void _onButtonPressed(BuildContext context) async {
>     // Add await before showDialog.
>     await showDialog(
>       context: context,
>       builder: (BuildContext buildContext) {
>         return SimpleDialog(
>           title: Center(child: Text('In progress')),
>           children: <Widget>[Center(child: CircularProgressIndicator())],
>         );
>       },
>     );
>     Navigator.of(context, rootNavigator: true).pop();
>   }
> ```
> 
> I'm unable to get a crash to happen (on master), but the dialog also doesn't come up when I push the "To crash" button (and does briefly when I push the other one).
> 
> I think the problem is that you're popping the root route before the `showDialog` can push its own route. If you delay (or await), then the root navigator is still there when the dialog's route gets pushed, so the route you end up popping is the dialog's route.

@gspencergoog Thanks for your insight, this is exactly what it is happening. I almost forgot that the `showDialog` method actually returns a `Future`. With `await showDialog()`, the sample code I gave above does not crash any more.
