### ISSUE TITLE
Detect when app comes to foreground

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4553]
If the user minimized my app I want to detect when it comes back to the foreground and refresh the data. Does flutter provide a way to be notified when my application comes to the foreground?

**Comment by abarth** [comment]
Looks like the WidgetsBindingObserver gets a didChangeAppLifecycleState callback, which should contain this information.  Looks like the work here is:

 * [ ] Make this easy to hook into from the widget tree (e.g., with an inherited widget for the state).
 * [ ] Verify that this works on iOS.

**Comment by chinmaygarde** [comment]
I can verify that the lifecycle callbacks are correctly hooked up on iOS.

**Comment by abarth** [comment]
This was already all wired up.  I've added an example showing how to listen for lifecycle events:

https://github.com/flutter/flutter/pull/4623

The specific state you want to listen for is `AppLifecycleState. resumed `:

http://docs.flutter.io/flutter/dart-ui/AppLifecycleState-class.html

**Comment by g-balas** [comment]
Strangely, the callback didChangeAppLifecycleState is executed if the flutter container (activity or viewcontroller) is not visible. It does not really detect if the app itself is on the background, but the container. 

This makes a big difference while showing other activity / viewcontroller from native platform.

**Comment by jamesdixon** [comment]
@g-balas ran into this myself. I was attempting to trigger biometric authentication when the app is resumed. As you noted, I saw that the app state was changing to inactive/paused when the FaceID prompt popped up and then the state would then again change when the FaceID prompt was dismissed. It doesn't seem that these events are at all hooked into the actual application lifecycle events. 

@abarth thoughts on this?

**Comment by kgrigorian** [comment]
> @g-balas ran into this myself. I was attempting to trigger biometric authentication when the app is resumed. As you noted, I saw that the app state was changing to inactive/paused when the FaceID prompt popped up and then the state would then again change when the FaceID prompt was dismissed. It doesn't seem that these events are at all hooked into the actual application lifecycle events.
> 
> @abarth thoughts on this?

did u manage to solve the issue? if yes, how?
I am also having a problem that FaceID triggers app lifecycle and currently it's not possible to differentiate faceid and foreground.

**Comment by azizainunnajib** [comment]
yeah, i need an explanation of this behavior. i dont get any clue bout this.

**Comment by azizainunnajib** [comment]
> Strangely, the callback didChangeAppLifecycleState is executed if the flutter container (activity or viewcontroller) is not visible. It does not really detect if the app itself is on the background, but the container.
> 
> This makes a big difference while showing other activity / viewcontroller from native platform.
> Everything is correctly described in the documentation, but this conversation could be misleading.

do you solve it? or you wanna try to put the callback in run app(), it's the highest function in flutter right? hope you already had solution for this so you can tell me the solution..

**Comment by ajinasokan** [comment]
I was bit by this issue recently. Turns out Flutter engine reports both container view events and app lifecycle events. I made a small plugin that sends only app's events(background/foreground) to fix this. Check it out here: https://github.com/ajinasokan/flutter_fgbg
