### ISSUE TITLE
Serialize Float32 and Float64 in flutter 

### ISSUE THREAD

**Issue by guruprakash119** [flutter/flutter#45535]
## Steps to Reproduce

1. ...Im developing a Dapp  with flutter on EOSIO blockchain, but my action on blockchain was not getting called by flutter app,i was getting the error unknown type: float32/float64 
then i saw the issue was related to Eosdart package flutter created to connect to EOS blockcahin,They have not given  support for float types(float32/flaot64).

This problem is really troubling me so much,as i'm using any float Argument in the contract,then not a single action is getting called from flutter app.

2. ..I tried sloving the problem by using C++ method,for converting string to float but there im not getting data precision,everytime  i use the conversion 0.00001 is getting minus.
SO please fix this issue.Please add serialize support for float types.

## Logs

```
E/flutter ( 6542): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Unknown type: float32
E/flutter ( 6542): #0      getType (package:eosdart/src/serialize.dart:1149:3)
E/flutter ( 6542): #1      getTypesFromAbi.<anonymous closure> (package:eosdart/src/serialize.dart:1194:20)
E/flutter ( 6542): #2      CastMap.forEach.<anonymous closure> (dart:_internal/cast.dart:286:8)
E/flutter ( 6542): #3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 6542): #4      CastMap.forEach (dart:_internal/cast.dart:285:13)
E/flutter ( 6542): #5      getTypesFromAbi (package:eosdart/src/serialize.dart:1189:9)
E/flutter ( 6542): #6      EOSClient._getContract (package:eosdart/src/client.dart:275:17)
E/flutter ( 6542): <asynchronous suspension>
E/flutter ( 6542): #7      EOSClient._serializeActions (package:eosdart/src/client.dart:299:33)
E/flutter ( 6542): <asynchronous suspension>
E/flutter ( 6542): #8      EOSClient.getRequiredKeys (package:eosdart/src/client.dart:203:17)
E/flutter ( 6542): <asynchronous suspension>
```

```
```

```
```

**Comment by iapicca** [comment]
Hi @guruprakash119
I see you opened a [question ](https://stackoverflow.com/questions/58993800/flutter-app-throwing-exception-unknown-type-float32-or-float64-while-calling-a)in StackOverflow,
I think this is the best course of action to answer your question.

Regardless you might want to take a look to dart's [typed_data](https://api.dart.dev/stable/2.6.1/dart-typed_data/dart-typed_data-library.html) library.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by guruprakash119** [comment]
Hey @iapicca
I agree this is not related to flutter but its related to flutter Package Eosdart which is part of flutter, and if u go through this Eosdart package you will find the problem there,and also there's is  a issue created for that but nothing progress is there this is why  i posted on flutter issue.i want this problem to get solve .
