### ISSUE TITLE
[web]: impossible to scroll by mouse dragging gesture (regression?)

### ISSUE THREAD

**Issue by roman-petrov** [flutter/flutter#45548]
We reference Flutter master branch in our Flutter Web project and recently after upgrading Flutter to latest `master/HEAD` I got an issue.

After some research I found that it seems to be a functional regression in Flutter for Web introduced in commit
314eb3bae37f9daf68a3bd9a2d8c870c7771e6b6 on `Nov, 21`.

I created a minimal example which can help to reproduce the issue:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: Scaffold(
          body: Container(
            width: 500,
            height: 500,
            color: Colors.grey,
            child: SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                  width: 1000,
                  height: 1000,
                  decoration: BoxDecoration(
                    gradient: RadialGradient(colors: [
                      Colors.green,
                      Colors.blue,
                      Colors.orange,
                      Colors.pink
                    ]),
                  ),
                  margin: EdgeInsets.all(250),
                ),
              ),
            ),
          ),
        ),
      );
}
```

The issue seems to be available only in Flutter for Web, on my mobile Android device everything works as expected.

In this example built for Web with Flutter `master/HEAD` it is not possible to scroll underlying rectangle by mouse dragging - just nothing happens.

But everything works fine in the example built with Flutter `master` earlier than earlier than 314eb3bae37f9daf68a3bd9a2d8c870c7771e6b6.

**Target Platform:** Web
**Target OS version/browser:** Chrome/Firefox
**Devices:** Browser

# Flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.12.12-pre.3, on Microsoft Windows [Version 10.0.17134.1130], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] VS Code (version 1.40.1)
[√] Connected device (2 available)

• No issues found!

**Comment by iapicca** [comment]
Hi @roman-petrov 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/45510)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by roman-petrov** [comment]
@iapicca, thank you. I will follow the issue you mentioned. My fault, i did't found this issue before opening this one..
