### ISSUE TITLE
stdin.readLineSync doesn't work with flutter_driver

### ISSUE THREAD

**Issue by dcnt** [flutter/flutter#45545]
In some cases user input is needed in integration testing. But it's impossible to enter any string using **stdin.readLineSync()**.  Pressing Enter doesn't finish string input.

## Steps to Reproduce

1. create a new flutter project: 
`flutter create demo`
2. create an integration test with the following test:
```
import 'dart:io';
...
test('dummy test', () async {
        stdout.writeln('Enter something');
        final response = stdin.readLineSync();
        print('You entered $response');
});
```
3. run the test, e.g. 
`flutter driver -t test_driver\demo.dart`

4. when it comes to entering a string in terminal try to enter it.
This blocks test execution, all entered chars are displayed but hitting Enter key just moves the cursor to next line and doesn't work as an input termination.

**Target Platform:** iOS, Android
**Target OS version/browser:** Windows, macOS
**Devices:** any

## Logs

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale en-UA)
    • Flutter version 1.9.1+hotfix.6 at /Users/xxxxxx/Downloads/flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xxxxxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • SM G930F • 9xxxxxxxxxxxx0 • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

**Comment by elgsylvain85** [comment]
Hello, 

I'm facing the same problem. Any feedback from someone please?
For the moment, I  **open the same project with Eclipse IDE and Dart Tools so the Input works correctly** but because I am not feeling Eclipse for Flutter Dev, I cameback after.

regards,
elgsylvain85

**Comment by TahaTesser** [comment]
Hi @dcnt  @elgsylvain85 
Flutter team `We're moving away from flutter_driver in favour of extending flutter_test to work on devices` 
https://github.com/flutter/flutter/issues/7474#issuecomment-558882182
https://stackoverflow.com/questions/57933204/flutter-driver-test-coverage-report/59739989#59739989

Closing, if. If you disagree, please write in the comments and I will reopen it.
Thank you
