### ISSUE TITLE
Put a infinity scroll on PageView.builder

### ISSUE THREAD

**Issue by cristianfb1989** [flutter/flutter#45553]
What I'm looking for is to apply an infinite scroll to a PageView.builder, but the itemCount has an immovable number of items. It's so that when I get to the last item, then it shows me the first item.

Thx you!

```
import 'package:flutter/material.dart';

class SliderScroll extends StatefulWidget {
  @override
  _SliderScrollState createState() => _SliderScrollState();
}

class _SliderScrollState extends State<SliderScroll> {
  PageController pageController;
  @override
  void initState() {
    super.initState();
    pageController =
        PageController(initialPage: 1, viewportFraction: 0.8, keepPage: false);
  }

  @override
  Widget build(BuildContext context) {
    Widget local() {}

    List<Widget> itemsLocales = [
      local(),
      local(),
      local(),
    ];

    imageSlider(int index) {
      return AnimatedBuilder(
        animation: pageController,
        builder: (context, widget) {
          double value = 1;
          if (pageController.position.haveDimensions) {
            value = pageController.page - index;
            value = (1 - (value.abs() * 0.3)).clamp(0.0, 1.0);
          }
          return Center(
            child: Padding(
              padding: const EdgeInsets.only(top: 125.0),
              child: SizedBox(
                height: Curves.easeInOut.transform(value) * 300,
                width: Curves.easeInOut.transform(value) * 300,
                child: widget,
              ),
            ),
          );
        },
        child: Container(
          margin: EdgeInsets.all(2),
          child: itemsLocales[index],
        ),
      );
    }

    return Container(
      child: PageView.builder(
        controller: pageController,
        itemCount: itemsLocales.length,
        itemBuilder: (context, position) {
          return imageSlider(position);
        },
      ),
    );
  }
}

```

**Comment by iapicca** [comment]
Hi @cristianfb1989 
I'm not sure that this is what you are trying to achieve,
but you might want to take a look at this [code ](https://gist.github.com/iapicca/8c9075a0896138df116715ea36186506) I wrote for you.
Does this solution fix your issue?
thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
