### ISSUE TITLE
#4549 broke the transition test

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#4555]
#4549 broke the transition test. The file `transition_perf_test.dart` transitively imports `dart:ui`, which is not supported by the standalone Dart VM.

[LOG FILE](https://pantheon.corp.google.com/m/cloudstorage/b/flutter-dashboard/o/d8c52527cc98003bc01b3c5bf7fd65655b2bd889/output.txt)

/cc @HansMuller

**Comment by HansMuller** [comment]
```  
Failed to load "/Users/demouser/flutter_dashboard/flutter/examples/flutter_gallery/test_driver/transitions_perf_test.dart":
  Unable to spawn isolate: The built-in library 'dart:ui' is not available on the stand-alone VM.
  'package:flutter/src/material/app.dart': error: line 15 pos 1: library handler failed
  export 'dart:ui' show Locale;
  ^
```

**Comment by HansMuller** [comment]
Apparently the problem is that transitions_perf_test.dart depends on package:flutter_gallery/gallery/item.dart which ends up pulling in material/app.dart. And that depends on dart:ui.  Which isn't available on the standalone VM.

**Comment by yjbanov** [comment]
I wonder if using configurable imports we can provide a fake version of `dart:ui` on the standalone VM. It would allow importing it and provide all necessary types, but it would throw if anything attempted to call anything.

@floitschG WDTY?

**Comment by HansMuller** [comment]
I can refactor the code that's being imported to eliminate the implicit dart:ui dependency. Doing so will leave what is now just a list of unrealized widgets in two separate files; the result will be harder to update/read.
