### ISSUE TITLE
Devicelab cocoon process 'ci' hang - multiple `ci` processes exist

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#45550]
Linux1 and Mac2 used to work well.

I have been working on saving task logs to GCS, and after some development work (deployed in linux1 and mac2), these two agents started hitting this issue: the cocoon process hanged daily with multiple `ci` processes existing.

In Linux1:

flutter@flutter-devicelab-linux-1:~$ ps -ef | grep dart
flutter  23478     1  0 Nov22 ?        00:06:11 dart bin/agent.dart ci -c config.yaml
flutter  30566 23478  0 Nov22 ?        00:00:00 dart bin/agent.dart ci -c config.yaml
flutter  30567 23478  0 Nov22 ?        00:00:00 dart bin/agent.dart ci -c config.yaml

In ~/agent.log

2019-11-22T20:57:04.321572: WARN Failed to turn off screen: ProcessException: OS error message was a not a utf8 string.
  Command: /home/flutter/Android/Sdk/platform-tools/adb devices -l

2019-11-22T20:57:05.322094: INFO Executing: ps -ef -u flutter
ERROR: ProcessException: mand.run
  Command: /usr/bin/ps -ef -u flutter

In Mac2:

flutter-devicelab-mac-2:~ flutter$ ps -ef | grep dart
  501 24450 59823   0 Fri06PM ??         0:00.00 dart bin/agent.dart ci -c config.yaml
  501 59823     1         0 Fri11AM ??         3:31.91 dart bin/agent.dart ci -c config.yaml

In ~/agent.log

2019-11-22T18:18:01.857396: INFO Executing: idevice_id -l
2019-11-22T18:18:02.873939: INFO Executing: ps -ef -u flutter
ERROR: ProcessException: Too many open files
  Command: /usr/sbin/lsof -p 138
#0      startProcess (package:cocoon_agent/src/utils.dart:285:18)
<asynchronous suspension>
#1      eval (package:cocoon_agent/src/utils.dart:350:13)
<asynchronous suspension>
#2      _listProcessesPosix (package:cocoon_agent/src/list_processes.dart:51:15)

**Comment by godofredoc** [comment]
This was most likely caused by gsutil with multithreading. We haven't seen this issue anymore.
