### ISSUE TITLE
PageView snapping no longer working

### ISSUE THREAD

**Issue by athornz** [flutter/flutter#45566]
PageView snapping no longer works in dev (1.12.11), and always bounces back to the first page.

It's working in beta 1.11.0.

I've narrowed the commit that caused the issue to: https://github.com/flutter/flutter/commit/851d6996e7cedf767de7464e02a21e493a6f18e5

## Steps to Reproduce

Try to use a PageView widget with pageSnapping set to true.

**Target Platform:** iOS and Android
**Target OS version/browser:** any
**Devices:** any

**Comment by LongCatIsLooong** [comment]
Close in favor of https://github.com/flutter/flutter/issues/45096
