### ISSUE TITLE
[dashboard] Grid horizontal scrolling not working on linux

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#45569]
Horizontal scrolling of the build matrix does not work on chrome and linux.

**Comment by CaseyHillers** [comment]
framework issue filed at https://github.com/flutter/flutter/issues/45510

**Comment by CaseyHillers** [comment]
Since this is fixed in the engine, I am going to close this. Feel free to reopen.

There is an issue tracking scrollbar support for the dashboard at https://github.com/flutter/flutter/issues/45273
