### ISSUE TITLE
Run post commit CQ tests on LUCI as part of pre-commit

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#45562]
Currently this is achieved by adding "CQ+1" label to the PR. We wish to make it the default behavior for all the pull requests.

Requirements:
1. All pull requests should run the post commit tests as part of precommit. Since these have some Fuchsia tests and iOS tests that are not run as precommits.
2. No longer have the label CQ+1 as all tests are CQ+1.

cc: @cbracken , @dnfield

**Comment by dnfield** [comment]
The only reason I had it this way was for capacity purposes.  We could change this pretty easily if we'r enot worried about capacity anymore.

**Comment by iskakaushik** [comment]
@dnfield lets change it. If capacity becomes a bottleneck we can revert back to the old behavior.

**Comment by iskakaushik** [comment]
@dnfield assigning it to you. It would be great if you can add me to the CL -- i'd like to know how this stuff is configured.

**Comment by dnfield** [comment]
It's likely I won't be able to get to this until later in December or early January.  If that doesn't work we may want to find someone else.

**Comment by dnfield** [comment]
I believe @godofredoc is working on this - see https://github.com/flutter/cocoon/pull/572

**Comment by iskakaushik** [comment]
Woohooo!! Thanks @godofredoc !!

**Comment by godofredoc** [comment]
This will require a little bit more work. I fixed a NPE but still need to work on the pubsub topic.

**Comment by digiter** [comment]
I'm adding the capacity to enable running pre-commit tests.
