### ISSUE TITLE
[google_sign_web] error compiling for iOS

### ISSUE THREAD

**Issue by arctouch-felipefontes** [flutter/flutter#45571]
## Steps to Reproduce

1. add the plugin google_sign_in_web
2. try to compile for ios

**Target Platform:** IOS
**Target OS version/browser:** MacOS 10.14.6
**Devices:** iOS Simulator 8

## Logs

```
```

```
```

```
```

**Comment by iapicca** [comment]
Hi @arctouch-felipefontes 
are you using both [google_sign_in  ](https://pub.dev/packages/google_sign_in)and [google_sign_in_web](https://pub.dev/packages/google_sign_in_web) in your project?

> Remember that for web plugins you need to depend both on the "native" version that provides the Dart interface that you'll use in your app), and the "web" version, that provides the implementation of the plugin for the web platform.

could you please provide your updated  `flutter doctor -v`
and your `flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by arctouch-felipefontes** [comment]
Yes i'm using both plugins. i'am able to login in web so everything looks ok, i have a project that started in android & iOS, but i'm trying to have them as web app to using the bloc that I already have only changing the UI.

I didn't put the code sample because i just remove the package  google_sign_in_web: ^0.8.0 from the pubspeck and ios can build fine.

Here is a project that i'm using to test it. i remove the google key to be able to share it.
https://drive.google.com/file/d/1L4OfPfZJYo8nzS-xjp47NyDjf-ZY2Ug2/view?usp=sharing

Here is the ```flutter doctor -v.```
[✓] Flutter (Channel dev, v1.12.12, on Mac OS X 10.14.6 18G103, locale en-BR)
    • Flutter version 1.12.12 at /users/felipefontes/development/flutter
    • Framework revision bae92c32e5 (28 hours ago), 2019-11-24 22:29:28 -0800
    • Engine revision b6b54fd606
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/felipefontes/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```flutter build ios --verbose```
[  +21 ms] executing: pod --version
[ +910 ms] 1.8.4
[   +4 ms] Running pod install...
[ +703 ms] Running pod install... (completed in 0.7s)
[   +1 ms] CocoaPods' output:
           ↳
[        ]       Preparing
           
               Analyzing dependencies
           
               Inspecting targets to integrate
                 Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
           
               Fetching external sources
               -> Fetching podspec for `Flutter` from `Flutter`
               -> Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
               -> Fetching podspec for `google_sign_in_web` from `.symlinks/plugins/google_sign_in_web/ios`
               [!] No podspec found for `google_sign_in_web` in `.symlinks/plugins/google_sign_in_web/ios`
           
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:901:in `fetch_external_source'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:880:in `block (2 levels) in fetch_external_sources'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `each'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `block in fetch_external_sources'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:878:in `fetch_external_sources'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
               /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
               /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
               /usr/local/bin/pod:22:in `load'
               /usr/local/bin/pod:22:in `<main>'
           
[   +8 ms] Error output from CocoaPods:
           ↳
[        ] 
               [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See
               `https://guides.cocoapods.org/syntax/podfile.html#platform`.
           
[  +14 ms] "flutter ios" took 14,376ms.
Error running pod install

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      CocoaPods._runPodInstall (package:flutter_tools/src/macos/cocoapods.dart:326:7)
<asynchronous suspension>
#2      CocoaPods.processPods (package:flutter_tools/src/macos/cocoapods.dart:145:15)
<asynchronous suspension>
#3      processPodsIfNeeded (package:flutter_tools/src/macos/cocoapod_utils.dart:36:46)
<asynchronous suspension>
#4      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:357:9)
<asynchronous suspension>
#5      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:80:43)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by iapicca** [comment]
thank you for providing those information @arctouch-felipefontes

**Comment by arctouch-felipefontes** [comment]
I was trying to add labels, but this is my first report in an issue. i don't know if i don't have permissions or I just don't know how to do it.

Anyway thanks for helping me. let me know if you need anything.

**Comment by arctouch-felipefontes** [comment]
Hey @ditman and @mklim can you guys help me?. i downloaded the google_sign_in example and did this
1- flutter config --enable-web
2- added the plugin google_sign_in_web
2- flutter create .
3- flutter build web (build ok)
4- flutter build ios and happens the same as above.
```[!] No podspec found for `google_sign_in_web` in `.symlinks/plugins/google_sign_in_web/ios` ```


```
Building io.flutter.plugins.googleSignInExample for device (ios-release)...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Signing iOS app for device deployment using developer identity: "iPhone Developer: Felipe Santos (BNDJ94Z7BP)"
Running pod install...                                              0.8s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A google_sign_in_web
      - Flutter
      - google_sign_in

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
    -> Fetching podspec for `google_sign_in_web` from `.symlinks/plugins/google_sign_in_web/ios`
    [!] No podspec found for `google_sign_in_web` in `.symlinks/plugins/google_sign_in_web/ios`

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:901:in `fetch_external_source'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:880:in `block (2 levels) in fetch_external_sources'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `block in fetch_external_sources'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:878:in `fetch_external_sources'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install```

**Comment by ditman** [comment]
Hey @arctouch-felipefontes, I've just seen this notification!

Thanks for the No podspec found for `google_sign_in_web` in `.symlinks/plugins/google_sign_in_web/ios` error message, I'll take a look!

**Comment by ditman** [comment]
I'm looking at our other web plugin, and indeed it contains a [podspec file](https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher_web/ios/url_launcher_web.podspec). I'll add this to the google_sign_in plugin to try to unblock this ASAP! (Currently I'm not setup to build iOS :/)

**Comment by ditman** [comment]
This got auto-closed when I landed the patch, sorry!

@arctouch-felipefontes please let me know if the above helps!

**Comment by arctouch-felipefontes** [comment]
It' worked thanks man. saved my life.
