### ISSUE TITLE
Material should have a non-animating constructor

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#45577]
Currently, the `Material` widget animates all changes to any of its properties. For some use cases it would be cool to turn those implicit animations off (e.g. when the animation is actually driven from the outside, see https://github.com/flutter/packages/pull/30/files#r349369211).

**Comment by HansMuller** [comment]
A Material widget that does not implicitly animate properties could build a relatively simple widget tree. That would be helpful in cases where the app doesn't want the animation, or is doing it's own animation at a higher level.

**Comment by goderbauer** [comment]
Workaround: You can currently achieve a non-animating material by setting its duration property to Duration.zero.

However, as Hans pointed out, we could probably build a simpler widget tree in that case since setting the Duration to zero still builds all the implicit animation cruft.

**Comment by micimize** [comment]
One way we could expose this in a backwards-compatible way is by adding an `animated (default true)` that just toggles the use of `_MaterialInterior`:
```dart
    return widget.animated
        ? _MaterialInterior(
            curve: Curves.fastOutSlowIn,
            duration: widget.animationDuration,
            shape: shape,
            borderOnForeground: widget.borderOnForeground,
            clipBehavior: widget.clipBehavior,
            elevation: widget.elevation,
            color: backgroundColor,
            shadowColor: widget.shadowColor,
            child: contents,
          )
        : PhysicalShape(
            child: _ShapeBorderPaint(
              child: contents,
              shape: shape,
              borderOnForeground: widget.borderOnForeground,
            ),
            clipper: ShapeBorderClipper(
              shape: shape,
              textDirection: Directionality.of(context),
            ),
            clipBehavior: widget.clipBehavior,
            elevation: widget.elevation,
            color: ElevationOverlay.applyOverlay(
                context, backgroundColor, widget.elevation),
            shadowColor: widget.shadowColor,
          );
```
Another option would be to make another widget `MotionlessMaterial`, which notably could be done in userland fairly easily

**Comment by Hixie** [comment]
Another solution is just to set a Key on the widget when you replace it, that'll cause the old one to be thrown away and a new one created without animating.

Given that there are numerous solutions, I'm going to close this bug.
