### ISSUE TITLE
[macos] Caps lock doesn't report a key up event

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#45574]
We are able to detect a key press on caps lock by using the `flagsChanged:` method, which is only called when the key is pressed (which effectively changes the modifier flag). This might be an OS limitation, but there doesn't seem to be a Cocoa tool to achieve this. I've seen other solutions mentioned like [CGEventTap](https://developer.apple.com/documentation/coregraphics/1455445-cgeventtapenable?language=objc) or [IOHIDManager](https://developer.apple.com/documentation/iokit/iohidmanager_h?language=objc) but they capture events outside of the application scope, resulting in more complex window focus management.

**Comment by gspencergoog** [comment]
@franciscojma86 does this work now that the other modifier issues are fixed?

**Comment by gspencergoog** [comment]
With the new key event system, this issue is resolved.
