### ISSUE TITLE
Add handling of maps in `Form` and `FormField`

### ISSUE THREAD

**Issue by hlemcke** [flutter/flutter#45609]
I need to manipulate nested maps from an application server like an invoice with multiple lines in it.

This map should be provided as a `dataObject` to a `Form`. It contains all `initialData` for any type of input field. Then the `FormField` only needs a `path` to access the right value within the map.

Example:
``` Dart
Map<String, dynamic> jsonData;
Form( dataObject: jsonData, ...
  child: Column( children: [
    TextFormField( path: 'root.node2', ... // no initialData (uses jsonData[root][node2] instead)
```

Invoking `save()` on form state will put all current values from the input fields into the map which was given to the form at the path given to the form field. If the map does not yet contain that key then it will be added.

Example:
``` Dart
Map<String, dynamic> jsonData = {};  // Empty map => no initial data
Form( dataObject: jsonData, ...
  child: Column( children: [
    TextFormField( path: 'root.node2', ... // empty text field
);
```

User enters some text "Nice Feature" into the text input field.

``` 
Form.save(); // obtain and use FormState to save e.g. through a GlobalKey
print( jsonData[root][node2] ); // will output "Nice Feature"
```

This feature requires access to nested maps. To determine the right node in the map, a string is used. The string is a path which parts are separated by dots (similar to Java bean access).

This methods allow path access to maps.
It still requires support for lists with builders.

```
dynamic readJson(Map<String, dynamic> json, String path) {
	List<String> keys = path.split("\.");
	dynamic value = json;
	for (int i = 0; i < keys.length; i++) {
		if (value == null) return null;
		try {
			if (value is List) {
				// --- json element is a list [...]
				value = _readJsonFromList(value, keys[i]);
			} else {
				// --- json element is a value or an object {}
				value = value[keys[i]];
			}
		} catch (e) {
			print("path=$path i=$i value=$value -> " + e.toString());
		}
	}
	return value;
}

dynamic _readJsonFromList(List<dynamic> list, String key) {
	dynamic result;

	if (key.contains(":")) {
		// --- path element is key:value. List elements must be objects {}
		List<dynamic> keyValue = key.split(":");
		String k = keyValue[0];
		String v = keyValue[1];
		Map<String, dynamic> entry;
		// --- Scan objects in list
		for (int i = 0; i < list.length; i++) {
			entry = list[i];
			if (entry[k].toString() == v) {
				return entry;
			}
		}
	} else {
		// --- path element is the integer index
		int j = int.parse(key);
		return list[j];
	}
	return null;
}

///
/// Writes the given 'value' at 'path' into the given 'json' map.
/// If 'path' does not yet exist in the map, it will be created.
///
Map<String, dynamic> writeJson(Map<String, dynamic> json, String path, dynamic value) {
	List<String> keys = path.split("\.");
	Map<String, dynamic> map = {keys[keys.length - 1]: value};
	for (int i = keys.length - 2; i >= 0; i--) {
		map = {keys[i]: map};
	}
	if (json == null) {
		return map;
	}
	json.addAll(map);
	return json;
}
```

**Comment by iapicca** [comment]
Hi @hlemcke 
I'm not sure to understand the use case for this feature request,
how is different from decoding `json `and programmatically create 
a `FormField` each `key value pair` ?
thank you

**Comment by hlemcke** [comment]
This solution provides two advantages:

a) reduction of boilerplate code with enhanced readability
  - `initialValue` replaced by providing the map to the form
  - save() puts modified value directly into map (no need for additional code in `onChange()`

b) option to enhance other input widgets with this functionality
  - boolean, date, time, rating, ... can all be enhanced to use this same functionality

Accessing the map entries with the given path allows central handling of (even nested) null values. If the map structure changes, only one string (the path) at the input widget must be adapted.

**Comment by Hixie** [comment]
@hlemcke It's not clear to us what bug or problem you are reporting, or how we should update Flutter to address you problem. Can you clarify?

**Comment by hlemcke** [comment]
We are evaluating Flutter as a web frontend for extensive data manipulation supported by a mobile app. Most data are structured (nested) objects like an invoice with a sender, a receiver and many lines. This data is available as nested json like (I left out all the quotes):

``` json
Map<String, dynamic> invoiceData = { dueDate: 2019-11-27, currency: USD, tax: 123.45, total: 456.78,
  receiver: { name: ACME, zip: 12345, vat: true }
  lines: [
    { pos: 1, service: sometext, netAmount: 10.42 }
    { pos: 2, service: another, netAmount: 11.56 } ] }
```

To edit such data, I would like to be able to develop forms like:

``` dart
Form( dataObject: invoiceData, child: Column( children: [
  CheckboxListTile( title: 'VAT', path: 'receiver.vat' ),
  FormTextField( labelText: 'Receiver', path: 'receiver.name' ),
  DateInputField( labelText: 'Due Date', path: 'dueDate' ),
  ListTile( 'title: 'Currency', leading: Radio( path: 'currency' )), // Radio belongs to group 'currency'
````

Expected Results:

1. Unification of input fields
2. Dramatic reduction of boilerplate code
3. Central handling (under the hood) to provide an initial value and to update (save) a modified value

Requirements:

1. A `Form` must accept map data as a `Map<String,dynamic>`
2. all input fields automatically attach to a `Form` ancestor (register)
3. if they have a form ancestor then they use its map for initialValue and update that value on save(). 4. The value in the map is identified by a `path`.

Anyway, all types of input fields should still be usable standalone without a `Form` ancestor.

Maybe there is another easy solution to this requirement and you could hint me to some examples how to combine or attach input fields (slider, checkbox, switch, date picker, time picker, ...) to a `FormField` like a `TextFormField` does.

**Comment by iapicca** [comment]
closing as [requested](https://github.com/flutter/flutter/issues/46073#issue-532621790) by the author
