### ISSUE TITLE
Integrate enable/disable into FormState and FormField

### ISSUE THREAD

**Issue by hlemcke** [flutter/flutter#45606]
# Use case

I suggest to integrate `enable()` and `disable()` into `FormState` ( `setEnable(bool)` would do the same thing). Invoking `enable()` at `FormState` should invoke `enable()` in all registered `FormField`s. Same with `disable()`. This would just extend the already existing functionality for validate(), reset() and save().

Also supply `isEnabled()` to check current form state.

See #45604 "Remove attribute readOnly in TextField"

Reason
This would ease data manipulation handling and provide a clean way for all type of inputs.

**Comment by Hixie** [comment]
Flutter uses a functional style rather than an imperative style, generally speaking. I'm not sure this proposal really matches the design of the rest of the framework. I would recommend filing a new issue that describes the use case more clearly rather than suggesting the solution.
