### ISSUE TITLE
Remove attribute readOnly in TextField and TextFormField

### ISSUE THREAD

**Issue by hlemcke** [flutter/flutter#45604]
I suggest to remove attribute `readOnly` in `TextField` and `TextFormField`.

Removing this attribute would mean:
- text will always be selectable
- text will be editable when editable is true
- text will not be editable when editable is false. If the developer wants to change the text appearance (e.g. rendering text in grey) then he may attach a proper Decoration.

Since this may break already existing functionality it could be necessary to add a new widget like `InputText` which can be used standalone or within a form.

See #45606 "Integrate enable/disable into FormState and FormField"

Reason: 
This change will allow easier handling of input data for all type of input fields (use enabled in all of them).

The distinction between readOnly and enabled is a relic of old ages when there was only a keyboard to enter data with its tab key to jump from one field to the next one and to any actions. Nowadays we have mice and touch screens for direct access to actions without the need to "tab" through all input fields. Therefore this separation no longer makes sense.

**Comment by awhitford** [comment]
I would prefer being able to select text from a `readOnly` field.

**Comment by flutterq** [comment]
Step By Step Guide to [How to disable text edit field in flutter ?](https://flutterq.com/wp-admin/post.php?post=243&action=edit)

**Comment by Hixie** [comment]
I think we have to support this to honor the expectations of desktop platforms. You can definitely just not use it though. :-)
