### ISSUE TITLE
bug in video_player plugin playing mp3

### ISSUE THREAD

**Issue by arcticfox1919** [flutter/flutter#45601]
```
    _audioController =
    VideoPlayerController.network("xxxxx.mp3")
      ..setLooping(true)
      ..setVolume(0.5)
      ..initialize().then((_) {
        _audioController.play();
      });
```

When I used the `video_player` plugin to play mp3 audio, I did not succeed on IOS and did not give any hints, but it was fine on Android

**Comment by arcticfox1919** [comment]
```
dependencies:
  video_player: ^0.10.3+3
```

**Comment by iapicca** [comment]
Hi @arcticfox1919 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Thank you

**Comment by arcticfox1919** [comment]
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/bruceying/develop/flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/bruceying/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • sheng的 iPhone • 7590ded783ec9f44ebfd5b0963b4d172c761c456 • ios • iOS 12.0

• No issues found!

**Comment by arcticfox1919** [comment]
`flutter run --verbose` Too many logs
[logs](https://www.swisstransfer.com/d/9cab863a-81f0-4672-895f-ba91da354cd3)

**Comment by arcticfox1919** [comment]
>  _audioController =
    VideoPlayerController.network("xxxxx.mp3")
      ..setLooping(true)
      ..setVolume(0.5)
      ..initialize().then((_) {
        _audioController.play();
      });

I have debugged, the `initialize` method does not return, and the `play` method is not called

**Comment by iapicca** [comment]
Hi again @arcticfox1919 
I apologize, I didn't recognize the duplicate before asking you further info,
please follow up on that [issue](https://github.com/flutter/flutter/issues/39845).

I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
