### ISSUE TITLE
[url_launcher / dart:js] flutter doesn't work on iOS

### ISSUE THREAD

**Issue by zhangruiyu** [flutter/flutter#45600]
flutter web cannot open app store.I want to open app store through H5 page

**Comment by iapicca** [comment]
Hi @zhangruiyu 
[webview support for web](https://github.com/flutter/flutter/issues/45295) is on the work,
please follow up on the linked issue.

I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by zhangruiyu** [comment]
I don't think my question can be expressed clearly. At present, I want to jump to other external pages in the pages I write with flutter web. It's OK in PC and Android browsers, but I can't jump in IOS

**Comment by zhangruiyu** [comment]
> Hi @zhangruiyu
> [webview support for web](https://github.com/flutter/flutter/issues/45295) is on the work,
> please follow up on the linked issue.
> 
> I'm closing the current one as duplicate.
> If you disagree please write in the comments
> and I will reopen it.
> Thank you

I don't think my question can be expressed clearly. At present, I want to jump to other external pages in the pages I write with flutter web. It's OK in PC and Android browsers, but I can't jump in IOS

**Comment by iapicca** [comment]
Hi again @zhangruiyu 
could you please provide your updated  `flutter doctor -v`
and a minimal code sample to reproduce the problem?
Thank you

**Comment by zhangruiyu** [comment]
> Hi again @zhangruiyu
> could you please provide your updated `flutter doctor -v`
> and a minimal code sample to reproduce the problem?
> Thank you

[✓] Flutter (Channel master, v1.12.5-pre.44, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
    • Flutter version 1.12.5-pre.44 at /Users/zhangruiyu/tools/flutter_master/flutter
    • Framework revision fb5e49082b (7 days ago), 2019-11-19 23:14:25 -0800
    • Engine revision 176f563296
    • Dart version 2.7.0
sample :
 static openAppStore(){
    openUrl("https://itunes.apple.com/cn/app/id1478599499");  
  }
  
  static openUrl(String url) {
    context.callMethod("open", [url]);
    launch(url);
  }

But neither of the following two methods can open app store on IOS

**Comment by zhangruiyu** [comment]
I think there's something wrong with the way I use it

**Comment by zhangruiyu** [comment]
windows.open放在ios的safari浏览器上不支持

**Comment by zhangruiyu** [comment]
Windows.open is not supported in safari on ios

**Comment by shashwatadi** [comment]
Any reason for closing this @zhangruiyu ? What is the work-around ?
