### ISSUE TITLE
[Material] adding a Dash icon to Icons

### ISSUE THREAD

**Issue by hawkbee1** [flutter/flutter#45614]
Dash the plushie, is becoming famous while touring NY and I thought it may be the time to ask Santa Claus for a new Icon: a Dash icon

Of course a package can provide such an icon but Dash place is in flutter nest.

**Comment by HansMuller** [comment]
CC @willlarche

**Comment by sfshaza2** [comment]
I heartily endorse this proposal.

**Comment by anticafe** [comment]
While working on my project, has 2 button Increase and Decrease, I notice there is no Dash icon yet. Thus vote up for adding this icon.
