### ISSUE TITLE
Expose color parameter to CloseButton

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#45612]
The widget `CloseButton` doesn't allow to set the `color` parameter of the icon. `BackButton`, does. We should allow to override that parameter on `CloseButton` too.

## Flutter doctor

```
[√] Flutter (Channel master, v1.12.14-pre.11, on Microsoft Windows [VersiÃ³n 10.0.18363.476], locale es-ES)
    • Flutter version 1.12.14-pre.11 at C:\src\flutter
    • Framework revision 92b0ceaaa6 (7 hours ago), 2019-11-26 01:19:51 -0500
    • Engine revision 05f8c8b24b
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Cristian\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Pixel 3 XL • 89PY09NNV • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @Zazo032 
[CloseButton ](https://api.flutter.dev/flutter/material/CloseButton-class.html) is essentially an [IconButton](https://api.flutter.dev/flutter/material/IconButton-class.html) 
that can be easily customized to accommodate your needs,
does this solution fix the issue?
thank you

**Comment by Zazo032** [comment]
`CloseButton` can't be easily customized because it only accepts `key` as a parameter, nothing else: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/back_button.dart#L130

`BackButton` allows passing custom `color` and `onPressed` parameters: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/back_button.dart#L76

`CloseButton` should even be moved to a separate file (`close_button.dart`), not the same as `BackButton` (`back_button.dart`).
