### ISSUE TITLE
Cirrus should try to merge in tip of tree master during setup

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#45626]
Currently on pre-submit, Cirrus runs the test suite on feature branches as-is, rather than trying to rebase on upstream master ToT first, then running the tests. Since most contributors believe it works like the latter, let's just do it. If there is a merge conflict, just abort and run as is--github will force the developer to resolve the conflict anyway.

**Caveat** once this runs, there could be subsequent merges to upstream that conflict/break the code in the PR.

Use case:

```
D     Merge C to master, post-submit tests fail because the Bar implementation doesn't match Foo API
|\
|  C  Create implementation of Foo called Bar, pre-submit tests pass
|  |
B  |  Upstream change to API of interface Foo
| /
A     Create interface Foo
```

In the above example, with the current setup, opening a PR with commit C branching off of commit A will pass fine on CI, even though upstream the interface of Foo changed and once merging the branch to master, CI will fail post-submit.

**Comment by digiter** [comment]
Is it about the auto merger?

**Comment by christopherfujino** [comment]
> Is it about the auto merger?

Not sure what you mean by "auto merger". I'll update the OP to try to clarify.

**Comment by christopherfujino** [comment]
Here's an [example PR](https://github.com/flutter/flutter/pull/52717) that passed [pre-submit](https://github.com/flutter/flutter/pull/52717/checks) but failed [post-submit](https://github.com/flutter/flutter/runs/517236554)

**Comment by godofredoc** [comment]
Obsolete. The autosubmit rebases to ToT before merging.

**Comment by christopherfujino** [comment]
This was specifically about pre-submit tests, however that is now being tracked in the luci bug: https://github.com/flutter/flutter/issues/68668
