### ISSUE TITLE
Create Hot-Deploy

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#45629]
## Use case

When want to deploy my code in a device, real or AVD, for debugging, it takes around 2 minutes to compile the Android .apk, install it, and be ready to run, debug, hot-reload and etc. It's really annoying to have to wait 2 minutes every time I just want to start debugging something.

Yes, most of the times I leave an AVD open with the code, and most times I just need to click the "Debug" button when I start my day, but some days I need to see the code in an actual device, or I need to restart my PC, and then I need to go back and forth. So in those days, it's really annoying to wait 2 minutes at a time waiting for everything to be ready.

To be fair, it's 2 minutes in my laptop, but it's around 1 minute on my PC, I wonder if the Flutter team has statistics on this, 95 percentile build time and etc. Even if it was 45s seconds, I think there's room for improvement, and improvement is Flutter's second name.

## Proposal

There are two situations where we want to run/debug our code in a device:

1. For simple daily programming.
2. For deployment on the field for testing.

Daily programming is the vast majority of the times we want to deploy our code, and my proposition will focus on it.

My idea is to create a new way of deploying our apps, Hot-Deploy.

Hot-Deploy will work very similarly as `flutter attach`. Once we click `Hot-Deploy`, flutter will check if the device already has the APK installed, if yes, it just starts the App and does a Hot-Restart, synchronizing all the files, and then we are ready to start coding. If the App is not installed, the Hot-Deploy falls back to a simple Run/Debug.

Of course this won't be good enough for deployment, since as soon as we close the App all our code is gone, but for this there will be always the regular Run/Debug, where the code is actually installed with the new APK.

I believe this will be a much quicker way  to start coding, without the need to compile any APKs, run lengthily SHA calculations (#29562) and etc. Besides, this should be rather quick to develop, as `flutter attach` behaves in a very similar way.

I named it Hot-Deploy, but it could also be Hot-Run and Hot-Debug as well.

**Comment by jonahwilliams** [comment]
@feinstein please try out https://github.com/flutter/flutter/pull/45431. It only requires the APK to be built a single time (until plugins/flutter version/java code is changed).

**Comment by feinstein** [comment]
How can I test it?

**Comment by jonahwilliams** [comment]
You can either wait for it to land and switch to master to try it, or checkout that commit and `flutter run --fast-start`

**Comment by feinstein** [comment]
Thanks @jonahwilliams, I will wait for it then.

**Comment by jonahwilliams** [comment]
Closed via https://github.com/flutter/flutter/pull/45431
