### ISSUE TITLE
Heroes ignore child changes while animating

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#4563]
I have a widget that is the destination of a MaterialPageRoute transition. It uses Heroes, like so:

```
  final ColorTween _color = new ColorTween(
    begin: Colors.blue[500],
    end: Colors.red[500]
  );

  @override
  Widget build(BuildContext context) {
    Color c = _color.evaluate(config.animation);
    return new Hero(
      tag: config.recipe.imagePath,
      child: new DecoratedBox(
        decoration: new BoxDecoration(
          backgroundColor: c
        )
      )
    );
  }
```

While the MaterialPageRoute is animating, the Hero is doing its thing, and none of the changes to its child hierarchy apply. The color snaps from blue to red as soon as the MaterialPageRoute animation completes.

If I change the Hero to a Container, the color animation works.

**Comment by HansMuller** [comment]
The test case Hero doesn't look like it should animate during the hero's flight, since the animation doesn't cause the Hero's child to rebuild.

I've verified that Hero animations do continue throughout the Hero's flight if the Hero's child is listening to an Animation.  Something like this:
```
  new Hero(
    tag: myHeroTag,
    child: new AnimatedBuilder(
      animation: myAnimation,
      builder: (BuildContext context, Widget child) {
        return new Icon(
          Icons.android,
          color: Color.lerp(Colors.blue[400], Colors.red[400], myAnimation.value),
        );
      },
    ),
  ),
```
