### ISSUE TITLE
Add AppBarTheme.centerTitle property

### ISSUE THREAD

**Issue by gabrielbtc** [flutter/flutter#45639]
## Use case
I want to set:
**centerTitle: _false_ or _true_**

Globally to my **appBar**.

## Proposal
At the **appBarTheme** in **"main.dart"** file can be a good place to set it.
`appBarTheme: AppBarTheme( centerTitle: true / false )`

--

Thanks for making Flutter awesome!

**Comment by Tom1380** [comment]
I was just going to ask this too, it would be great.

**Comment by gabrielintang** [comment]
yep it would be great...

**Comment by Tom1380** [comment]
It just seems like such an obvious choice

**Comment by AyushBherwani1998** [comment]
@shihaohong, I would like to work on this issue.

We can introduce a new property `centerTitle` in the `AppBarTheme` and inside `AppBar` we can modify [`_getEffectiveCenterTitle`](https://github.com/flutter/flutter/blob/478d4c9c1ad5d8324c59e78db5ab73e5b41ecacd/packages/flutter/lib/src/material/app_bar.dart#L431) function, where we can check whether the `theme.appBarTheme.centerTitle` is null or not. If not null, we can return the value.  Checking the `theme.appBarTheme.centerTitle` after  checking the `centerTitle` property of the `AppBar` will allow users to override the value of `centerTitle` from `AppBarTheme`.

**Comment by shihaohong** [comment]
Sounds good!

**Comment by AyushBherwani1998** [comment]
@shihaohong I have submitted a PR. Looking forward to reviews :)

**Comment by Tom1380** [comment]
Thanks a lot @AyushBherwani1998!
