### ISSUE TITLE
Offstage Navigators steal focus from an onstage Navigator

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#45634]
On initial launch of our app, a route on an offstage navigator requests focus. This causes focus traversal to happen on a widget tree that's offscreen, which is very confusing.

Minimal reproduction:

```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets("offstage nav focus", (tester) async {
    Widget _childNavRouteBuilder(BuildContext context, _, __) {
      return Text('foobar');
    }

    Route<void> _childNavRoute(RouteSettings settings) {
      return PageRouteBuilder(
        pageBuilder: _childNavRouteBuilder,
      );
    }

    final topLevelNav = GlobalKey<NavigatorState>();
    final navA = GlobalKey<NavigatorState>();
    final navB = GlobalKey<NavigatorState>();
    final navC = GlobalKey<NavigatorState>();

    await tester.pumpWidget(Directionality(
      textDirection: TextDirection.ltr,
      child: Navigator(
        key: topLevelNav,
        onGenerateRoute: (settings) {
          return PageRouteBuilder(
            pageBuilder: (context, _, __) {
              return Stack(
                children: <Widget>[
                  Offstage(
                    child: Navigator(key: navA, onGenerateRoute: _childNavRoute),
                  ),
                  Offstage(
                    offstage: false,
                    child: Navigator(key: navB, onGenerateRoute: _childNavRoute),
                  ),
                  Offstage(
                    child: Navigator(key: navC, onGenerateRoute: _childNavRoute),
                  ),
                ],
              );
            },
          );
        },
      ),
    ));

    await tester.pumpAndSettle();

    expect(topLevelNav.currentState.focusScopeNode.hasFocus, isTrue);
    expect(navA.currentState.focusScopeNode.hasFocus, isFalse);
    expect(navB.currentState.focusScopeNode.hasFocus, isTrue); // Actual: false
    expect(navC.currentState.focusScopeNode.hasFocus, isFalse); // Actual: true
  });
}
```

cc @gspencergoog

**Comment by gspencergoog** [comment]
Thanks so much for the test case!

**Comment by gspencergoog** [comment]
Actually, @ds84182 after talking this over with @Hixie, I'm going to recommend that instead of walking the tree to find things (which is O(n) bad), you can instead set the Navigator's focus scope to not autofocus, which should have the effect you're looking for.  Your test would then be something like this:

```dart
  testWidgets('route autofocus can be controlled with settings', (WidgetTester tester) async {
    Widget _childNavRouteBuilder(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation) {
      return const Focus(debugLabel: 'Nav Child', child: Text('foobar'));
    }

    Route<void> _childNavRoute(RouteSettings settings, {bool offstage = true}) {
      return PageRouteBuilder<void>(
        settings: settings.copyWith(autofocus: !offstage),
        pageBuilder: _childNavRouteBuilder,
      );
    }

    final GlobalKey<NavigatorState> topLevelNav = GlobalKey<NavigatorState>(debugLabel: 'Top Level');
    final GlobalKey<NavigatorState> navA = GlobalKey<NavigatorState>(debugLabel: 'navA');
    final GlobalKey<NavigatorState> navB = GlobalKey<NavigatorState>(debugLabel: 'navB');
    final GlobalKey<NavigatorState> navC = GlobalKey<NavigatorState>(debugLabel: 'navC');

    await tester.pumpWidget(
      Directionality(
        textDirection: TextDirection.ltr,
        child: Navigator(
          key: topLevelNav,
          onGenerateRoute: (RouteSettings settings) {
            return PageRouteBuilder<void>(
              pageBuilder: (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation) {
                return Stack(
                  children: <Widget>[
                    Offstage(
                      child: Navigator(key: navA, onGenerateRoute: _childNavRoute),
                    ),
                    Offstage(
                      offstage: false,
                      child: Navigator(key: navB, onGenerateRoute: (RouteSettings settings) => _childNavRoute(settings, offstage: false)),
                    ),
                    Offstage(
                      child: Navigator(key: navC, onGenerateRoute: _childNavRoute),
                    ),
                  ],
                );
              },
            );
          },
        ),
      ),
    );

    await tester.pumpAndSettle();

    expect(topLevelNav.currentState.focusScopeNode.hasFocus, isTrue);
    expect(navA.currentState.focusScopeNode.hasFocus, isFalse);
    expect(navB.currentState.focusScopeNode.hasFocus, isTrue);
    expect(navC.currentState.focusScopeNode.hasFocus, isFalse);
  });
```

I've updated the PR (#45655) to add an `autofocus` to `RouteSettings` so you can control whether or not the focus occurs.

**Comment by gspencergoog** [comment]
I'd also like to point out that `Offstage` widgets are not supposed to be inactive: they still run their animations, and still can be focused.  That behavior is WAI, so perhaps you're using them for something that they weren't meant for?

**Comment by ds84182** [comment]
In particular, we're using `Offstage` to implement "navigator switching". We have our single top level navigator (for dialogs and some pages) and our three secondary navigators (for some other pages). You can see a layout like this in a native Android app if you look at YouTube. YouTube has top level navigation (opening the account dialog) as well as nested navigation using a BottomNavigationBar. For both, the bottom nav elements switch between navigators, all with their own navigation stacks, and the stacks are maintained for offscreen navigators.

Adding autofocus to the route settings does not help in this situation, as there is no way to update route settings for all routes pushed on a specific navigator, and all of these navigators have initial routes. Instead, would it be possible to deny focus requests from a specific subtree by wrapping it in a FocusNode that vetos focus requests from child FocusNodes? That would give us a more general solution for this issue, although I feel that it's an easy one to hit if you're dealing with multiple navigators.

**Comment by gspencergoog** [comment]
Setting `autofocus` on the route to false prevents the route from requesting focus when pushed.

But you're saying you don't have control over the creation of the routes, and so can't supply them with a `RouteSettings` that has `autofocus` set to false?

It is possible to do what you're asking for already: setting the `canRequestFocus` to false on a `FocusScopeNode` will prevent its children from requesting focus.  The `NavigatorState` (returned from `Navigator.of()`) has its own `focusScopeNode`, but because of the creation order, you might need to wrap the Navigator in your own `FocusScope` to have it be non-focusable from the beginning.

It's possible we need to add a parameter to the `Navigator` constructor that lets you supply a `FocusScopeNode` to be used by the Navigator to get around the inconvenience of having to make your own.

**Comment by Hixie** [comment]
`Offstage` can be used to do what you're describing, but only in conjunction with a bunch of other widgets including TickerMode, FocusScope, etc. See `tab_scafford.dart` in the `cupertino` package.

**Comment by ds84182** [comment]
Would it be possible to abstract out much of what `tab_scaffold.dart` does outside of the `cupertino` package? I think having a unified way of getting this right is useful, especially when some new behavior needs to be introduced.

**Comment by ds84182** [comment]
@gspencergoog So I tried canRequestFocus (the documentation still says that it doesn't affect children requesting focus), and I ran into a bug where the parent's canRequestFocus status was being propagated into the child's _canRequestFocus field, essentially bricking focus for an entire widget subtree.

Essentially the lines like:
```dart
      focusNode.skipTraversal = widget.skipTraversal ?? focusNode.skipTraversal;
      focusNode.canRequestFocus = widget.canRequestFocus ?? focusNode.canRequestFocus;
```
in `focus_scope.dart` cause the internal `_canRequestFocus` field to inherit the parent's value (which is false) instead of keeping the current value. This is due to `canRequestFocus` doing more than just returning the value of the field.

Changing these to `if (widget.canRequestFocus != null) focusNode.canRequestFocus = widget.canRequestFocus;` fixes the issue, but for right now switching between navigators makes all their focus nodes unfocusable.

**Comment by Hixie** [comment]
The relevant parts of `tab_scaffold.dart` are about 10 lines of code, I don't think there's much value in factoring it out.

**Comment by gspencergoog** [comment]
Whoa.  Thanks for reporting that @ds84182 .  I'll build a separate PR to fix it.

**Comment by gspencergoog** [comment]
OK, the fix PR is https://github.com/flutter/flutter/issues/46168.  Does that fix your issue?  If so, I'll probably revert the other change (#45655).

**Comment by ds84182** [comment]
Yes, we're now able to disable focus on our offstage navigators. Only other thing is making entire modal routes unfocusable when another route is open above it, assuming focus traversal is allowed to escape FocusScopes, but that can be a different issue

**Comment by gspencergoog** [comment]
Focus is not able to escape a FocusScope via keyboard traversal.  It can escape via mouse click, but modal routes typically cover the route above, so that's rarely an issue.

**Comment by ds84182** [comment]
For Flutter's builtin directional traversal, yes. You might also hit it with an auto-focusing widget being created on the route below the current route. I'll make a new issue for this, since #46168 allows us to control when our offstage navigators gain focus (which fixes this issue).
