### ISSUE TITLE
[recipes] Split flutter recipes to its own repo

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#45630]
Currently flutter recipes are using buildbot structure sharing folders with many other projects. It will be cleaner to have a repository for flutter recipes only and moving common modules to recipes-py.

Tasks that need to be completed:

- [x] Create recipes project in flutter.googlesource.com.
- [x] Make a copy of the flutter recipes to the new project.
- [x] Add recipe bundler
- [x] Add auto rollers for the recipes.
- [x] Start using the new recipes in flutter infra.
- [x] Delete flutter recipes from chromium project.
- [x] Delete copied modules from flutter recipes(goma, yaml), import chromium recipes and use modules from source. 
- [x] Add unit tests.
- [x] Add owners file.
- [x] Update docs.

**Comment by dnfield** [comment]
@riannucci has told me this isn't super hard, but requires setting up an auto-roller into the repo we want it to live in.

**Comment by digiter** [comment]
It'd nice if the recipe live within the repository, for example, make framework recipe live in flutter/flutter repo. This will prevent breakage from repo and recipe mismatch.

**Comment by godofredoc** [comment]
**Bundler process**
Summary:
We are adding a new builder that will create cipd packages in flutter/recipe_bundles.

Once the recipes are moved to flutter.googlesource.com/recipes we are creating a bundler based on the chromium bundler recipe. This only requires adding a reference to the cipd package containing the recipe-bundler and passing parameters to the new cipd locations. 

The recipes-bundler build will be triggered by every change flutter.googlesource.com/recipes and will move its ref-tag to "refs/for/master" ensuring we will always be running the latest version of the recipes.

After we have some cipd packages we will change the recipes reference https://github.com/flutter/infra/blob/master/config/main.star#L198 to point to flutter/recipe_bundles. 

** Recipe branching **

Instead of copying recipes at a given point in time we can tag a specific CIPD package at branching time. Release branch recipes will be using those tags to get the recipes instead of the "refs/for/master" tag.

PROS: We don't have to manually create copies of recipes.
CONS: We won't be able to patch the recipes.

**Comment by christopherfujino** [comment]
This overall sounds great. What will we do if we need to patch the recipe (for example, [here](https://chromium.googlesource.com/chromium/tools/build/+/b1b426094b097be42e0c548b78625debc050ca7e) I needed to patch the recipe because Xcode was updated and it broke ruby)? Build a one-off CIPD package manually and tag it accordingly?

**Comment by godofredoc** [comment]
That will need to get fixed with a refactoring of the recipes. Ideally without a huge refactoring we should be able to describe builders without having to modify recipes and or builder configurations.

Specs can be used for that purpose:

https://fuchsia.googlesource.com/infra/recipes/+/master/recipe_modules/spec

Then the specs can live within the repo under test.

**Comment by christopherfujino** [comment]
> That will need to get fixed with a refactoring of the recipes. Ideally without a huge refactoring we should be able to describe builders without having to modify recipes and or builder configurations.

Understood. Should that refactor be a blocker to moving the release branches over to the flutter.googlesource.com recipes?

**Comment by godofredoc** [comment]
> > That will need to get fixed with a refactoring of the recipes. Ideally without a huge refactoring we should be able to describe builders without having to modify recipes and or builder configurations.
> 
> Understood. Should that refactor be a blocker to moving the release branches over to the flutter.googlesource.com recipes?

I'd say more like a follow up. The real reason for this PR is because chromium would like to remove some of the dependencies we added before the end of today and that will break our recipes.

Additionally the refactoring of recipes will require a lot of design and effort to complete. After this PR and a couple of follow ups on flutter.googlesource.com we will be in the same state as we were on the chromium repo but with more flexibility.

**Comment by christopherfujino** [comment]
Ok, makes sense. I guess what I should say then, is that the refactor should be a blocker to using the CIPD packages for beta and stable builders, right?

**Comment by godofredoc** [comment]
Yes, that sounds reasonable.

**Comment by stuartmorgan** [comment]
What's the process for editing now? https://github.com/flutter/flutter/blob/master/dev/bots/README.md#editing-a-recipe still describes the old method. I have a change that missed the cutoff that I'm trying to move over; I adjusted for path differences in the instructions and was able to create a CL, but I get a 403 trying to upload it, so apparently that's not quite right.

**Comment by godofredoc** [comment]
@stuartmorgan I adjusted the permissions of the repo, can you please try to push again? please let me know if it works.

The process should be the same but using flutter.googlesource.com instead of chromium. I'll update the readme for editing the recipe on Monday.

**Comment by stuartmorgan** [comment]
That worked, thanks.
