### ISSUE TITLE
Stop letting image_cache increase its max bytes size

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#45643]
Internal: b/147479267

PR https://github.com/flutter/flutter/pull/19352 introduced the ability for loading images to increase the max byte size of the image_cache if the image is too large.  Increasing the image_cache size should be a setting decided by the developer.

Originally this was an issue since it would cause flutter to get in a loop of loading and throwing out images continuously.  The removal of this shouldn't reintroduce that problem.

**Comment by Hixie** [comment]
I took a guess as to the target milestone, feel free to adjust.

**Comment by gaaclarke** [comment]
@cbracken Can you elucidate this issue?  The premise of the issue is becoming important to the PR review process.

**Comment by dnfield** [comment]
I suspect that throwing an error when the image itself exceeds the max cache size is the right thing to do.  In particular, we have a strange corner case where if you fill the cache and then just repeatedly try to add a very large image, it will keep growing the cache and let you start caching more smaller images.

However, I think this is also an API break - code that used to work will now fail with an error.  In the proposed PR, the test actually emits an error that the test framework ignores, which I think is probably a bug in the test framework.

**Comment by cbracken** [comment]
This change was reverted in #46629.

**Comment by gaaclarke** [comment]
https://github.com/flutter/flutter/pull/47387 fixed the issue.
