### ISSUE TITLE
setState not work with snackbar ??not rerendering  unless if hideCurrentSnackBar and showSnackBar again

### ISSUE THREAD

**Issue by mhmoudsabry** [flutter/flutter#45640]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by dnfield** [comment]
Thanks for filing an issue.  Unfortunately, in its current state, this issue doesn't really have any actionable content.  Please consider adding the steps to reproduce this issue and the expected behavior.

**Comment by mhmoudsabry** [comment]
this code showing snackbar  calling setState mehtod 
setState not changing snackbar showing in realtime just changing the value
so if you call snackbar again you will see the new value


```
 bool isGreen = false;
  void snackbarTest() {
    _key.currentState.showSnackBar(SnackBar(
      content: Row(
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          InkWell(
            onTap: () {
              setState(() {
                isGreen = !isGreen;
              });
            },
            child: Container(
              height: 40,
              width: 50,
              color: isGreen ? Colors.green : Colors.red,
            ),
          ),
          InkWell(
            onTap: () {
              setState(() {
                isGreen = !isGreen;
              });
            },
            child: Container(
              height: 40,
              width: 50,
              color: isGreen ? Colors.red : Colors.green,
            ),
          ),
        ],
      ),
    ));
  }

```
 this is the snackbar will shown and if you click on it no thing change
![1](https://user-images.githubusercontent.com/46267043/69882060-a1cc2280-12d7-11ea-8c65-d8c10aade3a7.png)

if snackbar closed and you show it again you will have the new value 
![2](https://user-images.githubusercontent.com/46267043/69882107-c7f1c280-12d7-11ea-9671-215a52598407.png)

**Comment by mhmoudsabry** [comment]
@dnfield

**Comment by dnfield** [comment]
From your code it's not clear what widget state is getting the setState call.  You're likely calling it too low in the tree

**Comment by mhmoudsabry** [comment]
solved by the define which state should setState
 
`  bool isGreen = false;
    var controller;
  void snackbarTest() {
      controller=_key.currentState.showSnackBar(SnackBar(
      content: Row(
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          InkWell(
            onTap: () {
              setState(() {
                isGreen = !isGreen;
              });
            },
            child: Container(
              height: 40,
              width: 50,
              color: isGreen ? Colors.green : Colors.red,
            ),
          ),
          InkWell(
            onTap: () {
              setState(() {
                isGreen = !isGreen;
              });
            },
            child: Container(
              height: 40,
              width: 50,
              color: isGreen ? Colors.red : Colors.green,
            ),
          ),
        ],
      ),
    ));
    
  }
  changeColor(){
    controller.setState((){
      isGreen = !isGreen;
    });
  }`
