### ISSUE TITLE
simple_animation_perf_iphonexs measures GPU usage outside of app

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#45641]
The `simple_animation_perf_iphonexs` benchmark uses instruments to capture CPU and GPU usage.  Recently, a severe regression was noted and appeared to be due to a modal shown by the OS asking to upgrade the iOS version.  Presumably, this could happen because that causes a full screen overlay of transparency over the animation we're measuring - more work on the GPU seems to make sense.  

Ideally, our benchmark would be immune to such things.  That said, I'm not sure there's a fix for this.  We might want to come up with a strategy for keeping the version of iOS on the device up to date to avoid the modal window.

/cc @jmagman @digiter @godofredoc @liyuqian @Hixie

**Comment by dnfield** [comment]
For reference: the regression started at https://github.com/flutter/flutter/commit/e766ae740ef55d52627e90bc88fa55d8f4fc44b7 and ended at https://github.com/flutter/flutter/commit/e1512b4dd749b489e0be0acf8ebe7972c3b85f34 - neither commit should have impacted GPU performance or usage.  However, before https://github.com/flutter/flutter/commit/e1512b4dd749b489e0be0acf8ebe7972c3b85f34 was tested, I dismissed the modal asking to update iOS.

**Comment by liyuqian** [comment]
Right, we've seen this before: https://github.com/flutter/flutter/issues/42671

The overlay is not just a problem for simple_animation_perf_iphonexs. It could potentially affect all our performance metrics. The simple_animation_perf_iphonexs is just unfortunately (or fortunately) very sensitive to that overlay so we'll always notice it.

My last discussion with @chinmaygarde seems to be that we should always quickly upgrade the iOS version so this overlay would not show up again until the next iOS upgrade. I don't know if there's a way to disable it without upgrading iOS.

**Comment by Hixie** [comment]
Maybe we could include this in the health check? e.g. show a black screen, full-bleed, and then take a screenshot. Is anything other than black visible? then there's something wrong.

**Comment by dnfield** [comment]
It may be easier to do just the screen shot and and make it visible somewhere in the dashboard - or just outright do a recording of the whole test and upload that.   We wouldn't have to fail a test based on that and deal with any flakiness from it, but we could more quickly observe something like this (in this particular case, I had to make a couple separate trips to the lab to figure out which actual device was being used).

**Comment by chinmaygarde** [comment]
Have we considered putting all devices in Airplane Mode? Not sure why these require access to the network. IIRC, unlike disabling just the WiFi (iOS turns it back on after a few hours), that should be a sticky way of keeping the device from looking for upgrades.

**Comment by dnfield** [comment]
Apparently devices need internet to run apps (perhaps for cert validation).  Enabling airplane mode has resulted in errors reported in the linked bug.

**Comment by digiter** [comment]
In addition to the comment above, one of my observation is iPhone asks internet on the app first run. I also think it's for verifying the development certificate.

**Comment by amorenew** [comment]
@dnfield I wonder if this is related but in Android, while toggling airplane on then off any flutter app restarts
https://github.com/flutter/flutter/issues/49057

**Comment by dnfield** [comment]
This is a bug about internal infra so probably not related :)

**Comment by godofredoc** [comment]
Closing as fixed, we are now dismissing all the system dialogs before running tasks.
