### ISSUE TITLE
[url_launcher] grey screen after return from a launched app

### ISSUE THREAD

**Issue by EliasDeuss** [flutter/flutter#45656]
After launching to another app 

```
await launch('youtube://www.youtube.com/watch?v=' + id,
            forceSafariVC: false);
```

and when you come back the screen is just grey
![IMG_0905](https://user-images.githubusercontent.com/13773566/69684444-8c53c000-106d-11ea-816d-2fc5770ecd50.png)

**Comment by helinanever** [comment]
Hi @EliasDeuss 

Could you please provide more information and` flutter doctor -v` and code simple to reproduce the issue. 

Thank you.
