### ISSUE TITLE
SliderThemeData and all the other themeData does not support colorScheme

### ISSUE THREAD

**Issue by bitsydarel** [flutter/flutter#45661]
## Steps to Reproduce

Specify the colorScheme for your app using
ThemeData.from method.

The slider does not obey the specified colorScheme.

**Comment by helinanever** [comment]
Hi @bitsydarel,

Does it answer your question?
https://stackoverflow.com/questions/55461293/how-to-change-slider-label-colour-in-flutter

Thank you.

**Comment by bitsydarel** [comment]
Not really, this is feature request.

Because i should not have to specify the slider theme again if i have already specified the colorScheme.

ColorScheme should be propagated to all the other themes.

**Comment by HansMuller** [comment]
CC  @darrenaustin @clocksmith 

Sliders should respect the Theme's colorScheme and the slider's color parameters should explain how they depend on  the colorScheme _and_ the SliderTheme. You shouldn't to do anything beyond configure your app theme's colorScheme.

**Comment by bitsydarel** [comment]
Any update on this issue ?

Can someone confirm why it’s tagged as stackoverflow ?

**Comment by clocksmith** [comment]
It looks like Slider (and RangeSlider) does use the ColorScheme. Can you please provide an example of something that does not work as you expect?

**Comment by bitsydarel** [comment]
RaisedButton I tried yesterday.
I will try to see if the sliders in the latest flutter release use the colorscheme

**Comment by bitsydarel** [comment]
@clocksmith correct slider's currently using the colorscheme primary property.

I'm about to close this issue, but following [material guideline](https://material.io/components/sliders/#specs), the slider should use the secondary color and not the primary, should i close this one and create a new one or ?

**Comment by clocksmith** [comment]
@bitsydarel The correct color for track and thumb is primary. The example that uses secondary on the material guideline link is for a custom themed slider.
