### ISSUE TITLE
Text in a Column ignores its textAlign attribute

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#4566]
I'm creating a column with text like so:

```
                        new Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              new Text('foo',
                                  style: theme.primaryTextTheme.body1,
                                  textAlign: TextAlign.left),
                              new Text('barbazbop',
                                  style: theme.primaryTextTheme.body1,
                                  textAlign: TextAlign.left),
                              new Text('fizzbuzz',
                                  style: theme.primaryTextTheme.caption,
                                  textAlign: TextAlign.left)
                            ])
```

however, the strings all line up differently.  

To get them to line up on the left side of the column, I had to set crossAxisAlignment on the column.

Is it possible to set the default crossAxisAlignment on Column such that the textAlign property of child textViews can be respected?

**Comment by Hixie** [comment]
It's easier to understand what's going on if you put the text in a container with a background.

The simplest solution is to use a Block instead of a Column.

**Comment by eseidelGoogle** [comment]
@Hixie would the "Debug drawing" checkbox in Atom also have shown the issue?
<img width="299" alt="screen shot 2016-06-14 at 5 52 30 pm" src="https://cloud.githubusercontent.com/assets/11857803/16064743/d78cf6d2-3258-11e6-8082-4f42214818d7.png">

**Comment by Hixie** [comment]
Yes, but only if you know what you're looking for. The Container demonstrates it in a better way because it becomes more obvious that the text alignment is aligning the text inside a box that's as wide as the text.

**Comment by Hixie** [comment]
Not sure what we can do to make this clearer, so I'm going to close this for now. If you have any concrete ideas for how to make this more intuitive, please don't hesitate to file a new bug.

**Comment by vlows** [comment]
I just wrapped the Text in to a Row with a Spacer()

           Row(
                  children: <Widget>[
                    Text("Highlights",
                        textAlign: TextAlign.left,
                        style: TextStyle(fontSize: 20)),
                    Spacer()
                  ],
                )

**Comment by hasen6** [comment]
This was posted in 2016 but still doesn't seem to work properly.  Clearly the text should be aligned in accordance with the width of the outer `Container`:

```
Container(
  width: 200,
  child: Column(
    children: <Widget>[
      Text('One', textAlign: TextAlign.left),
      Text('Two', textAlign: TextAlign.right),
    ],
  ),
),
```

Putting a `Container` with a width setting around each individual `Text` widget seems to make much less sense since the width is already defined by the outer `Container`.

**Comment by eseidelGoogle** [comment]
@RedBrogdon I wonder if flutter pad would be useful for easily replyign to these sorts of bugs with an example? :)

**Comment by hasen6** [comment]
What exactly is Flutter pad?

**Comment by eseidelGoogle** [comment]
We've experimented with adding Flutter support to DartPad now that we have some basic Flutter for web support.  Informally we joke about such as being a "flutter pad".

**Comment by RedBrogdon** [comment]
https://dartpad.dev/embed-flutter.html?id=34c7fa6377fe6ecc28bc3d479e3e2a56

Did someone say "Flutter in DartPad?"

@hasen6, I know that what you're seeing might seem counterintuitive at first (especially if you're used to a UI system that doesn't work the same way), but it makes sense given the way Flutter's columns and rows lay things out.

We've got a whole codelab that uses the new features in DartPad to show how the properties on Rows and Columns work, if you're interested:

https://flutter.dev/docs/codelabs/layout-basics

There's a survey at the bottom, if you have any additional feedback!

**Comment by hasen6** [comment]
@eseidelGoogle Ok I was gonna say. That would be great though, since languages like Javascript have that that are used in many frameworks. All it would need would be to cope with basic layouts, no need for animations or custom painting or whatever.

It would be especially useful for Flutter since as you RedBrogdon says the ui is counterintuitive. So many questions on stackoverflow with things like how to remove all the built in padding around every widget, when is TextAlign not ignored, or how to get everything lined up as you want it etc.

@RedBrogdon I'll check out the codelab on layout anyway, I didn't know about that. Although it doesn't seem to mention the word `textalign` anywhere so not sure if it clears up the issue in this thread.

**Comment by hasen6** [comment]
@RedBrogdon Ok no problem.

**Comment by 4limsyed** [comment]
Hi guys i think the best bet in this situation would be using this approach.

    ....................................................................................
        child: Container(
          width: MediaQuery.of(context).size.width,
          child: Column(
            
            children: [
              Text("Lets Get Started?",textAlign: TextAlign.center,),
              Text("Lets Get Started?",style: Theme.of(context).textTheme.headline1,textAlign: TextAlign.center,),
            ],
          ),
        ),

...........................................................................................

**Comment by CarltonBranch** [comment]
> width: MediaQuery.of(context).size.width,
>       child: Column(

I think you'll find that if you try to align to start or remove the textAlign value that nothing changes.

**Comment by CarltonBranch** [comment]
> Hi guys i think the best bet in this situation would be using this approach.
> 
> ```
> ....................................................................................
>     child: Container(
>       width: MediaQuery.of(context).size.width,
>       child: Column(
>         
>         children: [
>           Text("Lets Get Started?",textAlign: TextAlign.center,),
>           Text("Lets Get Started?",style: Theme.of(context).textTheme.headline1,textAlign: TextAlign.center,),
>         ],
>       ),
>     ),
> ```
> 
> ...........................................................................................

I think you'll find that if you try to align to start or remove the textAlign value that nothing changes.

**Comment by exeptionerror** [comment]
All Possible working solution added [[Solved] textAlign not working flutter](https://fluttercorner.com/textalign-not-working-flutter/)
