### ISSUE TITLE
Add onPrimaryVariant property to colorScheme

### ISSUE THREAD

**Issue by bitsydarel** [flutter/flutter#45660]
## Use case
I want to specify the color of the text that's displayed on element that has the primaryVariant color.

## Proposal

Add the onPrimaryVariant property to the colorScheme class.

Right now you can only specify the color of the text that's displayed on a widget with color [primary](https://api.flutter.dev/flutter/material/ColorScheme/primary.html), using the [onPrimary](https://api.flutter.dev/flutter/material/ColorScheme/onPrimary.html) but not for the [primaryVariant](https://api.flutter.dev/flutter/material/ColorScheme/primaryVariant.html)

**Comment by HansMuller** [comment]
https://api.flutter.dev/flutter/material/ColorScheme/primaryVariant.html

**Comment by bitsydarel** [comment]
@HansMuller yes but there's no way to specify the text color or opacity for the color primaryVariant.
Re-editing the proposal to make it clear.

**Comment by HansMuller** [comment]
@bitsydarel Aha, now I see what you mean. Individual components that use the primaryVariant (or any colorScheme color) will configure the color's opacity based on the component's state and other factors. 

Is there are specific component whose text color you're trying to configure?

**Comment by bitsydarel** [comment]
yes, the appbar and some other UI component, for example if i create my theme colors using the following [tool](https://material.io/resources/color/).

The tool ACCESSIBILITY section allow me to see the best text color to use for each color variant i have (light, dark).

I would like to specify them in my colorScheme.
Also since this cannot be specified the framework derive the text color from the specified brightness, which is not ideal for customization.

**Comment by HansMuller** [comment]
We're actively working on making _all_ of the material components base their default color configurations on the theme's colorScheme.  AppBar has not been updated yet. Will keep you posted about progress.

CC @darrenaustin

**Comment by Albert221** [comment]
`primaryVariant` is deprecated now, I think we can close this issue

**Comment by HansMuller** [comment]
Thanks for the heads-up. Closing this.
