### ISSUE TITLE
Crash when i create view controller

### ISSUE THREAD

**Issue by GuoZhiQiang** [flutter/flutter#45674]
Interrupt message failure:: Bad file descriptor
../../third_party/dart/runtime/bin/eventhandler_macos.cc: 197: error: Interrupt message failure. Wrote -1 bytes.

**Comment by helinanever** [comment]
Hi @GuoZhiQiang ,

Could you, please, provide more details, steps to reproduce and `flutter doctor -v`?

Thank you.

**Comment by GuoZhiQiang** [comment]
1. I use `flutter build ios` command to get an `outcome` of flutter. 
2. Then i integrate this `outcome` to my iOS project and run the project in `Debug` Build Configuration( which is the default behavior of Xcode).
3. Create a `ViewController` and then release it . Recreate it again, the project crashed.

------------------------------
When i run the project in `release` Build Configuration everything is ok.

**Comment by iapicca** [comment]
Hi @GuoZhiQiang could you please run 
`
 flutter channel stable
`
`
 flutter upgrade
`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
