### ISSUE TITLE
Flutter gallery items aren't indented any more

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4568]
@HansMuller

**Comment by abarth** [comment]
Any more context about what this bug is?  I'd like to fix it, but it's a bit mysterious.

**Comment by eseidelGoogle** [comment]
I suspect he's referring to the main screen, which Hans just rewrote to use lists/subheaders this afternoon.  Still not indented, but I believe that is now correct behavior?

**Comment by HansMuller** [comment]
I'm about to land https://github.com/flutter/flutter/pull/4861 which makes the gallery home page a simple list. Flutter ListItems are padded by 16 on the left and right, per the spec, https://material.google.com/components/lists.html#lists-specs

**Comment by HansMuller** [comment]
I believe that the gallery home page is now consistent with https://material.google.com/components/subheaders.html#subheaders-list-subheaders
