### ISSUE TITLE
Error when running app

### ISSUE THREAD

**Issue by GottfriedCP** [flutter/flutter#45681]
I just installed Flutter (Flutter SDK, Android Studio / SDK, etc) according to the official guide. But each time I ran the [demo app](https://flutter.dev/docs/get-started/codelab) (by `flutter run`), this error message popped up:

```
Launching lib\main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...                                              1.2s
Resolving dependencies...

* Error running Gradle:
ProcessException: Process "C:\src\startup_namer\android\gradlew.bat" exited abnormally:

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings


FAILURE: Build failed with an exception.

* Where:
Build file 'C:\src\startup_namer\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSetKt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
  Command: C:\src\startup_namer\android\gradlew.bat app:properties


Please review your Gradle project setup in the android/ folder.
```

I can't find the solution anywhere.

Output from `flutter doctor` is Ok.

```
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\src\flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.1)
    • VS Code at C:\Users\User Name\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by emadgh8** [comment]
Try downgrading your gradle version and try running the app again: 
step 1: go to android/.gradle and delete the version folder i guess you have 6.0.1
step 2: go to android/gradle/wrapper/gradle-wrapper.properties open the properties file and change the distribution URL from https\://services.gradle.org/distributions/gradle-6.0.1-all.zip to https\://services.gradle.org/distributions/gradle-5.6.1-all.zip

**Comment by iapicca** [comment]
Hi @GottfriedCP 
sorry I don't understand, did downgrading solved your issue?
thank you

**Comment by emadgh8** [comment]
hey @iapicca i suggested to @GottfriedCP to downgrade his gradle version i suppose that will solve his issue hopefully, still waiting for him to confirm that his saw my comment and tried the solution.

**Comment by GottfriedCP** [comment]
Thanks for your quick responses. I kept on trying by running `flutter run` and it magically worked, without doing anything else.

```
Launching lib\main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device Android SDK built for x86 64...
```

**Comment by emadgh8** [comment]
@GottfriedCP great that's good to know, best of luck

**Comment by mikeCalvir** [comment]
I have a very similar issue to this. I have recently returned to a project I hadn't touched for a couple of months (on MacOS 10.15), and have been wanting to fix an Android launch screen image scaling issue for some devices. 

I stupidly clicked on "yes" to a whole series of upgrades (flutter, Android Studio, dart plugin, kotlin plugins and possibly others) which has resulted in a build error I can't get past:

* What went wrong:                                                      
A problem occurred evaluating project ':app'.                           
> Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSetKt

This is a gradle error. My flutter doctor is all fine. The iOS version builds and runs fine. 

I tried the comment above about downgrading gradle from 6.1.1 to 5.6.1, but then I get a complaint that 6.1.1 is the minimum accepted version.

Every time I find someone reporting this error on StackOverflow or GitHub, the solution is always a variant of "the problem magically disappeared on its own". In my case though it seems I am not deserving of the same magic :)

All I wanted to do was try and fix a launch screen, and now I am trapped in this kind of hell where I can't even build the Android version of the project :)
I am hoping there is a kind soul reading this who can help put me out of my misery.

**Comment by mikeCalvir** [comment]
(Btw apologies if I should create a new issue for this instead of adding a comment here?)

**Comment by CenaAshoori** [comment]
> 
> 
> (Btw apologies if I should create a new issue for this instead of adding a comment here?)

i hope u solve it with this solution 
 actually i try different version of gradle and my problem solved . it funny but yeah this is my solution 

**step 1 :**
go to this dir
**>>  project_dir/android/gradle/wrapper/**
open **gradle-wrapper.properties**

and try diff version of gradle. 
![image](https://user-images.githubusercontent.com/52758031/87833890-3488f400-c89e-11ea-8356-de2f8d886c59.png)

actually it's not possible to try all the version .
try those version that are near to which version that already have .
sorry about my language 😄 

and this is the same issue:
https://github.com/flutter/flutter/issues/41492
