### ISSUE TITLE
DrawerHeader introduces asymmetric alignment

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#4569]
https://github.com/flutter/flutter/blob/bacd3d2cb0694454da72efd0a37a249d26c8b609/packages/flutter/lib/src/material/drawer_header.dart

The bounds on the Positioned() element are placed in a way that it's impossible to go to the end of the drawer.

**Comment by eseidelGoogle** [comment]
@DaveShuckerow worked around by looking at the source code and accommodating for the constants. :(

**Comment by Hixie** [comment]
This is fixed now, as far as I can tell from looking at the code.
