### ISSUE TITLE
[documentation] [video_player] how play local audio 

### ISSUE THREAD

**Issue by ChristianKleineidam** [flutter/flutter#45691]
I currently develop an alarm app and I want to play alarm sounds. 
There are various independent packages but they don't seem like they support all platforms and support the ability to play the sound in AudioManager.STREAM_ALARM loudness on Android.

While I looked at playing the audio I looked at video_player. Given that it's build on ExoPlayer and ExoPlayer can also play mp3's there's hope that video_player can play mp3s. Unfortunately, the documentation isn't clear about whether it can. If it can't it should be explicit about that.

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/23794
https://github.com/flutter/flutter/issues/38480

**Comment by TahaTesser** [comment]
Hi @ChristianKleineidam 
please check this [comment](https://github.com/flutter/flutter/issues/38480#issuecomment-570458759)

`The video_player plugin is not designed for audio file playback, so this is working as intended.`

If you disagree please write in the comments and I will reopen it. 
Thank you
