### ISSUE TITLE
PlatformView is not deallocated correctly on iOS

### ISSUE THREAD

**Issue by shorben07** [flutter/flutter#45697]
## Steps to Reproduce

1. Clone project https://github.com/shorben07/platform_view_leak
2. Build and run from Android Studio to iOS Simulator
3. Open Xcode Project. Build and run to iOS Simulator
4. Switch between tabs. Tab `1` has a platform view inside. Tab `2` does not

Actual result:

`MyFlutterView` is not deallocated. `MyFlutterView deinit` is not printed to the console (Only `MyFlutterPlatformView deinit`)

Expected result:
MyFlutterView is deallocated. `MyFlutterView deinit` is printed to the console 

**Target Platform:** iOS
**Target OS version/browser:** all
**Devices:** all

flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.5 18F132, locale en-UA)
    • Flutter version 1.9.1+hotfix.6 at /Users/shorben/Documents/Projects/flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/shorben/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/shorben/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPad mini 2 SS • 82d8d6a764e4c765a4a9f93fb835db4c15bfab6d • ios • iOS 12.4.3

• No issues found!

```
```

**Comment by shorben07** [comment]
I can reproduce the issue on the latest dev channel as well
```
 flutter doctor -v
[✓] Flutter (Channel dev, v1.12.15, on Mac OS X 10.14.5 18F132, locale en-UA)
    • Flutter version 1.12.15 at /Users/shorben/Documents/Projects/flutter
    • Framework revision 459c7fb884 (2 days ago), 2019-11-26 17:04:51 +0000
    • Engine revision e136d637a8
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/shorben/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/shorben/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • iPad mini 2 SS • 82d8d6a764e4c765a4a9f93fb835db4c15bfab6d • ios • iOS 12.4.3
    • iPhone 5s      • 688BC58B-AEAD-422C-91A7-FAF40E0F08B6     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by DCrow** [comment]
Any progress on this issue?

**Comment by HePingLaoSan** [comment]
Same Issue, platformview has not triggerred dealloc method

**Comment by gw280** [comment]
I tested this locally using the latest git branches of flutter and engine and see the following:

```2020-07-06 14:21:52.202218-0700 Runner[33855:344051] flutter: Observatory listening on http://127.0.0.1:52087/AXxTkmhc2z0=/
MyFlutterPlatformView deinit
MyFlutterView deinit
MyFlutterPlatformView deinit
MyFlutterView deinit```

I think we can close this.
