### ISSUE TITLE
Flutter Gold is not receiving image uploads

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#45699]
@kjlubick has reported that the Gold dashboard has stopped uploading data.

For example, [this test](https://flutter-gold.skia.org/search?fdiffmax=-1&fref=false&frgbamax=255&frgbamin=0&head=true&include=false&limit=50&master=false&match=name&metric=combined&neg=false&new_clstore=true&offset=0&pos=true&query=name%3Dcupertino.activityIndicator.paused.dark%26source_type%3Dflutter&sort=desc&unt=true) has not seen new uploads in 1 week, since https://github.com/flutter/flutter/commit/ce8e2bb7cf15bf42bf0bb9dfabada2c9483aa354
 **--> landed 11/20**

A new version of `goldctl` was rolled to CIPD at the same time: https://chromium-review.googlesource.com/c/infra/infra/+/1924621
**--> rolled 11/20**
Which included changes to `goldctl` from https://skia-review.googlesource.com/c/buildbot/+/253698

#### Other possibly related changes:
- Another goldctl change & roll to cipd (After the one mentioned above)
  - https://skia-review.googlesource.com/c/buildbot/+/256018 
  - https://chromium-review.googlesource.com/c/infra/infra/+/1933027 
    - **--> rolled 11/26**
- Open PR to enable tryjobs #44474 
  - Noticed yesterday that the golden file changes from #45304 did not appear for triage
  - They instead showed up in the tryjob results of #44474
  - Was disregarded at the time as the tryjob picking up the change before the other change was properly triaged, may not be the case.
- Open PR to test using Gold for Flutter Web #45530
  - does not use tryjobs

**Comment by Piinks** [comment]
cc/ @goderbauer FYI. The current pre-submit checks do not use `goldctl`, so changes to golden files won't slip by during this outage. 

@kjlubick I will see about getting debug information from image uploads to help identify what is going on.

**Comment by Piinks** [comment]
https://bugs.chromium.org/p/skia/issues/detail?id=9679 has been filed to set up an alert system to detect this better in the future.

**Comment by kjlubick** [comment]
I'll check if it's goldctl's bug or not - chrome-gpu is still operating fine, but I don't know if they auto-roll

**Comment by kjlubick** [comment]
I think I identified the bug - goldctl was passing itself something invalid during `imgtest init` (or possibly `imgtest add`). Fix incoming.

As with any good cascading failure, the flutter tests didn't realize the exit code was non-zero, so that would be a helpful follow-up investigation.

**Comment by Piinks** [comment]
Thanks! 🙂 
Our post-submit tests don't throw for a non-zero exit code right now since landing a change or a new test returns a non-zero exit code from the `imgtest`. Is that right? We use `passfail` mode, so using the exit code in that way would turn the tree red for every change. Of course, once tryjobs are up and running we'll be able to triage ahead of time so I think that distinguishing between what kind of non-zero exit code it is won't be an issue.

**Comment by kjlubick** [comment]
Do you run `imgtest init` before you run your tests or just `imgtest add`?  If `imgtest init` gives you a non-zero error code, make lots of noise because that means goldctl "herped it's derp" on the inputs.

**Comment by Piinks** [comment]
Ah! We do. I will add a check for the exit code there in `init`.

**Comment by kjlubick** [comment]
goldctl fix is live in CIPD; alert is going live on Gold's side to catch things like this a lot quicker

**Comment by Piinks** [comment]
Verified this is resolved. :)
