### ISSUE TITLE
TextField - Cursor position does not respect text alignment in certain situations.

### ISSUE THREAD

**Issue by arctouch-rafaelsouza** [flutter/flutter#45706]
## Steps to Reproduce

1. Add a TextField with textAlign set to `TextAlign.center`
2. Run the app.
3. Type something on the first line of the TextField
4. Press return/enter twice to go to the third line.
5. Type something on the third line.
6. Go back to the second line and type anything. The cursor position goes to the beginning of the line, but the text is correctly aligned.

![Flutter Issue - Cursor position](https://user-images.githubusercontent.com/47757867/69733705-88c34600-110c-11ea-9ad4-83809e290bdd.gif)

**Target Platform:** Android / iOS
**Target OS version/browser:** Android 9.0 / Android 7.0 / iOS 13.0
**Devices:** Samsung S9+ (Physical) / Samsung S6 Edge (Physical) / iPhone 11 Pro Max (Simulator)

## Sample Code

https://gist.github.com/arctouch-rafaelsouza/d443ac1fd1cfdd68925028707bfe8488

## Logs

Not adding the results of `flutter run --verbose` as it wouldn't help, as there are no exceptions.

```
Analyzing flutter-tests...                                              
No issues found! (ran in 3.4s)
```
```
[✓] Flutter (Channel master, v1.12.15-pre.29, on Mac OS X 10.14.6 18G1012, locale en-US)
    • Flutter version 1.12.15-pre.29 at /Users/rafaelsouza/Projects/Library/flutter
    • Framework revision 84a1de5c74 (2 hours ago), 2019-11-27 07:40:51 -0500
    • Engine revision fad1b23c42
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rafaelsouza/Library/Developer/Xamarin/android-sdk-macosx
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/rafaelsouza/Library/Developer/Xamarin/android-sdk-macosx
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • SM G925I • 0816086471e80704 • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

Probably related to issue https://github.com/flutter/flutter/issues/39826

**Comment by nturgut** [comment]
Thanks for reporting the issue. We are working on the fix.

Duplicate for: https://github.com/flutter/flutter/issues/39826

**Comment by arctouch-matheusromao** [comment]
Hey @nturgut, just to be sure, https://github.com/flutter/flutter/issues/39826 depends on https://github.com/flutter/flutter/issues/33523, which seems to be a web-related issue. When #33523 fix lands, will the mobile part be fixed as well?

**Comment by nturgut** [comment]
Unfortunately, after #33523 is fixed, we still need to make more changes to get #39826 fixed.

**Comment by arctouch-matheusromao** [comment]
Can we then track everything for mobile on #39826?
