### ISSUE TITLE
DropDown should honour incoming maxwidth constraint

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#4570]
With a dropdown that includes a very long item, the dropdown extends off the edge of the drawer to the end of the screen, this makes the material dropdown icon invisible.

I can illustrate the bug offline if you need further clarification.

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by eseidelGoogle** [comment]
@DaveShuckerow worked around this by setting a character limit on the dropdown itself.

**Comment by Hixie** [comment]
Dupe of https://github.com/flutter/flutter/issues/9211.
