### ISSUE TITLE
Adding a custom image to a Switch thumb (or any thing that requires a Decoration) is pretty nutty right now.

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#4571]
Adding a custom thumb decorator to the switch thumb is pretty rough, as per our hangouts conversation.

**Comment by eseidelGoogle** [comment]
I suspect much of this is the fact that we haven't written an example of using an image in a switch for the flutter gallery.  Once we do that, we'd feel the pain ourselves.

**Comment by Hixie** [comment]
I would love to do this but to test it I need some assets for a switch to put in the gallery demo.

**Comment by eseidelGoogle** [comment]
@Hixie I'd just pick an icon from our icons:
http://docs.flutter.io/flutter/material/Icons-class.html

You could toggle between reclined and unreclined airline seats, or car vs bike, or any number of fun combinations from that set. :)
