### ISSUE TITLE
type 'Color' is not a subtype of type 'MaterialColor'

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter#45737]
## Steps to Reproduce

The app is very plain:
1.  I have in my lib:
 a directory 'design' with 2 files: 
one for creating custom colours (4 colours): 
https://gist.github.com/benedicte69/068be86a18353579465fecc49e0c374b
one for creating an instance of the theme data (3 colours):
https://gist.github.com/benedicte69/9c146a5aea32b4a06a6f1fc58991b2db
and the main dart (basic flutter app) in the lib where 3 colours are used
https://gist.github.com/benedicte69/d728d64363655b0ed8012188e54ce793

2. The rendering is ok but when running the app once the adb.exe start-server this error occurs 4 times and slow the assemble debug

 [        ] I/flutter (15836): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[        ] I/flutter (15836): The following assertion was thrown building MyApp(dirty):
[        ] I/flutter (15836): type 'Color' is not a subtype of type 'MaterialColor'

here the full run:
https://gist.github.com/benedicte69/66ad1f7873045833089ea6792ca0d8b7

## Logs
flutter run --verbose
https://gist.github.com/benedicte69/5735ed0a36937621a06c31eab0ed52b6

the doctor -v : 
https://gist.github.com/benedicte69/d58e97ecc025542eaa309a456af64010

Run `flutter analyze` and attach any output of that command below:
Analyzing f_color...
No issues found! (ran in 2.1s)

Thanks for providing me with more information in this error message to help me determine and fix the underlying cause.
Yours

**Comment by iapicca** [comment]
Hi @benedicte69 
I've "squeezed" your code in one file and the issue doesn't occur
<details>
  <summary>sample</summary>

```
import 'package:flutter/material.dart';

const Color cPrimary = Color(0xFFCBFFC0);
const Color cPrimaryLight = Color(0xFFFFFFF3);
const Color cAccentColor = Color(0xFFF4C0FF);
const Color cTextBlack = Color(0xFF000000);

ThemeData get appThemeData => ThemeData(
  primaryColor: cPrimary,
  primaryColorLight: cPrimaryLight,
  accentColor: cAccentColor,
);

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
      title: 'Flutter Demo',
      theme: appThemeData,
      home: MyHomePage(),
    );
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static int _counter = 0;

  void _incrementCounter() =>setState(() => _counter++);

  @override
  Widget build(BuildContext context) => Scaffold(
    backgroundColor: cPrimaryLight,
    body: Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Text(
            'You have pushed the button this many times:',
          ),
          Text(
            '$_counter',
            style: Theme.of(context).textTheme.display1,
          ),
        ],
      ),
    ),
    floatingActionButton: FloatingActionButton(
      onPressed: _incrementCounter,
      tooltip: 'Increment',
      child: Icon(Icons.add),
    ),
  );
}
```

</details>
am I missing something or this solves the issue?
thank you

**Comment by benedicte69** [comment]
Thanks a lot @iapicca ,

I did not expect such a nice and quick answer. I could meanwhile sort this problem adding color: Color(0xFFCBFFC0) to the return MaterialApp 
But your code is quite better and more efficient: **ThemeData get appThemeData => ThemeData!** so great so good! I adopt it of course! Step by step, hopefully, I will end up being able to fully customize a flutter app ...
Now in both cases, even if the app runs,  I have unfortunately new exception about routes... another matter.

Many thanks for your help, hoping it does work also on ios,
Yours

**Comment by iapicca** [comment]
Hi @benedicte69 
I'm glad that you solved the problem,
if you have general questions  please see https://flutter.dev/community for resources

thank you for your kind words
