### ISSUE TITLE
Write a test to verify that we're still optimizing offscreen surface away if the BackdropFilterLayer is beneath some Layer that calls saveLayer

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#45731]
To verify the great work in https://github.com/flutter/engine/pull/13976 , and make sure no one will accidentally break the optimization in the future.

**Comment by liyuqian** [comment]
@flar : I think that this issue can be closed by one of your PR?

**Comment by flar** [comment]
Fixed by https://github.com/flutter/flutter/pull/46924
