### ISSUE TITLE
FlutterActivityLaunchConfigs is not public ;

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#45747]
FlutterActivityLaunchConfigs is not public ;

```
FlutterActivity.NewEngineIntentBuilder builder = FlutterActivity.withNewEngine();
builder.initialRoute("recorder");
builder.backgroundMode(FlutterActivityLaunchConfigs.BackgroundMode.transparent);
```
so I can't use it;

flutter doctor -v
[✓] Flutter (Channel dev, v1.12.15, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.12.15 at /opt/google/flutter
    • Framework revision 459c7fb884 (33 hours ago), 2019-11-26 17:04:51 +0000
    • Engine revision e136d637a8
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /opt/google/android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /opt/google/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • COL AL10 • VBJDU18725002458 • android-arm64 • Android 9 (API 28)

**Comment by iapicca** [comment]
Hi @wanjm 
are you submitting this issue as proposal ?
thank you

**Comment by wanjm** [comment]
yes, I think it should be public , otherwise how i can use builder.backgroundMode(FlutterActivityLaunchConfigs.BackgroundMode.transparent);

**Comment by wozhizhizhi** [comment]
FlutterActivityLaunchConfigs is not public
how i can use?

**Comment by xster** [comment]
See the instructions at https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen. Looks like the snippet is now 

```java
startActivity(
  FlutterActivity
    .withCachedEngine("my_engine_id")
    .backgroundMode(FlutterActivity.BackgroundMode.transparent)
    .build(context)
);
```

Please re-open the bug if that doesn't resolve the issue.

**Comment by wozhizhizhi** [comment]
Weird FlutterActivity.BackgroundMode.transparent not found

**Comment by xster** [comment]
Indeed, it's not public, and our https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen guide is wrong. We should fix it.

**Comment by matthew-carroll** [comment]
I opened a PR with a fix here:
https://github.com/flutter/engine/pull/14673

**Comment by mayparadise** [comment]
[How to register plugins and set transparent in FlutterFragment at V1.12.13 #47710
](url) 
temporary wroks for me  
thanks GEiki
`Intent intent = FlutterActivity.withNewEngine().initialRoute('route').build(activity);
intent.putExtra("background_mode","transparent");
activity.startActivity(intent);`

**Comment by xster** [comment]
Fixed in https://github.com/flutter/engine/pull/14673
