### ISSUE TITLE
`showCupertinoDialog` should support `barrierDismissible`

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#45744]
Internal: https://b.corp.google.com/issues/145094605

In `showCupertinoDialog` it is not supported to enabled to dismiss the dialog on outside tap. It seems that this might be the normal iOS behaviour, but I couldn't find any documentation that it is not allowed to support it.

**Comment by fryette** [comment]
add to your builder next code

` builder: (context) {
          return WillPopScope(
              onWillPop: () =>false
child: your_child
              }`

**Comment by alectogeek** [comment]
We realy need this feature!

**Comment by LongCatIsLooong** [comment]
I couldn't find anything that says this is not allowed, but from https://developer.apple.com/design/human-interface-guidelines/ios/views/alerts/ it shouldn't be encouraged either, as `barrierDismissible = true` makes it a lot easier for users to dismiss something important by mistake:

> __Minimize alerts__. Alerts disrupt the user experience and should only be used in important situations like confirming purchases and destructive actions (such as deletions), or notifying people about problems. The infrequency of alerts helps ensure that people take them seriously. Ensure that each alert offers critical information and useful choices.

Sounds reasonable to add the parameter but set the default to false.

**Comment by tottomotto** [comment]
@nataliesampsell ,can you please share your thoughts on this. 
I Implemented the change (defaulting to false) and I can make a PR if it's ok.

**Comment by xster** [comment]
Making it configurable (but defaulted to false) seems reasonable to me.
