### ISSUE TITLE
[scrolling] ListView slow to "jumpTo" when has many widgets

### ISSUE THREAD

**Issue by 229106948** [flutter/flutter#45751]
> jumpTo反应有些迟钝，等1s才会执行滚动到顶部操作

The jumpTo reaction is a bit sluggish, and waits for 1s to perform the scroll to the top operation.

**Comment by iapicca** [comment]
Hi @229106948 
does this code represent the issue you are describing?
<details>
  <summary>Click to expand!</summary>

```
import "package:flutter/material.dart";
import 'dart:math';

Random get _rng => Random();
double get _random => _rng.nextInt(999).toDouble();

void main()=> runApp(new MaterialApp(home: MyApp(),),);

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  static PageController _controller;

  @override
  void initState() {
    super.initState();
    _controller = PageController();
  }

  @override
  void dispose() {
    _controller.dispose();
    _controller = null;
    super.dispose();
  }

  static double get _randomPosition => (_widgets.length-(_controller.page+_random)).abs();
  static void get _jump => _controller.jumpTo(_randomPosition);
  static final List<Widget> _widgets =  <Widget>[for (int i = 0; i<1000; ++i) Center(child: Text(i.toString(),),),]; 
//List<Widget>.generate(1000, (i)=> Center(child: Text(i.toString(),),),),
  @override
  Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(
     title:  Text(_widgets.length.toString()),
    ),
    body: PageView(
      controller: _controller,
      children: _widgets,
    ),
    floatingActionButton: FloatingActionButton(
      onPressed: ()=> _jump,
      child: Icon(Icons.fast_forward),
    ),
  );
}
```

</details>
could you please provide your  `flutter doctor -v`?
thank you

**Comment by 229106948** [comment]
1.9.1+hotfix.4

**Comment by 229106948** [comment]
I use the ListView.builder,I Loaded 1000 datas,when scroll to bottom ,I click a button to scroll to top ,it respose 1 or 2 seconds to scroll

**Comment by iapicca** [comment]
Hi again @229106948 
could you please provide a minimal code sample to reproduce the problem
Thank you

**Comment by 229106948** [comment]
Stack(
              children: <Widget>[
                ListView.builder(
                  itemBuilder: (context, index) {
                    print("$index");
                    return Container(
                      alignment: Alignment.center,
                      color: Colors.white,
                      width:adWidth ,
                      height: 100,
                      child: Text("滚动$index",style: TextStyle(
                        fontSize: 15,
                        decoration: TextDecoration.none,
                      ),),
                    );
                  },
                  itemCount: 1000,
                  shrinkWrap: true,
                  padding: EdgeInsets.all(0),
                ),
                GestureDetector(onTap:(){
                  scrollController.jumpTo(0);
                  //scrollController.animateTo(scrollController.position.minScrollExtent, duration: Duration(milliseconds: 1000), curve: Curves.easeIn);
                },child: Align(
                  alignment: Alignment.bottomRight,
                  child: Padding(
                    padding: EdgeInsets.only(bottom: 10, right: 10),
                    child: Image.asset(
                      "images/jddj_top.png",
                      width: 40,
                      height: 40,
                    ),
                  ),
                ),),
                GestureDetector(onTap:(){
                  double offset=100*1000.toDouble();
                  scrollController.animateTo(offset, duration: Duration(milliseconds: 1000), curve: Curves.easeInCubic);
                },child: Align(
                  alignment: Alignment.bottomLeft,
                  child: Padding(
                    padding: EdgeInsets.only(bottom: 10, right: 10),
                    child: Image.asset(
                      "images/top.png",
                      width: 40,
                      height: 40,
                    ),
                  ),
                ),)
              ],
          )

**Comment by 229106948** [comment]
Stack(
              children: <Widget>[
                ListView.builder(
                  itemBuilder: (context, index) {
                    print("$index");
                    return Container(
                      alignment: Alignment.center,
                      color: Colors.white,
                      width:adWidth ,
                      height: 100,
                      child: Text("滚动$index",style: TextStyle(
                        fontSize: 15,
                        decoration: TextDecoration.none,
                      ),),
                    );
                  },
                  itemCount: 1000,
                  shrinkWrap: true,
                  padding: EdgeInsets.all(0),
                ),
                GestureDetector(onTap:(){
                  scrollController.jumpTo(0);
                },child: Align(
                  alignment: Alignment.bottomRight,
                  child: Padding(
                    padding: EdgeInsets.only(bottom: 10, right: 10),
                    child: Image.asset(
                      "images/top.png",
                      width: 40,
                      height: 40,
                    ),
                  ),
                ),)
              ],
          )

**Comment by iapicca** [comment]
Hi @229106948 
I'm indeed experiencing the issue you are describing
with this code 

<details>
  <summary>code sample</summary>

```
import "package:flutter/material.dart";

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: HomePage(),
      );
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  
  static ScrollController _controller;

  @override
  void initState() {
    _controller = ScrollController();
    super.initState();
  }

  @override
  void dispose() {
    _controller?.dispose();
    _controller  = null;
    super.dispose();
  }

  static final List<Widget> _widgets =  <Widget>[for (int i = 0; i<1000; ++i) Center(child: Text(i.toString(),),),]; 

  @override
  Widget build(BuildContext context) => Scaffold(
    body: ListView(
      controller: _controller,
      children: _widgets,
    ),
    floatingActionButton: FloatingActionButton(
      onPressed: ()=> _controller.jumpTo(0),
      child: Icon(Icons.arrow_upward),
    ),
  );
}
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.19013.1122], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\src\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\iapic\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.40.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • Pixel 3a • 965AY0WP5C • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details>

thank you for the information you provided

**Comment by 229106948** [comment]
but ,if I directly use the Listview ,it will load very slowly,Probaby it will load three and more seconds,This will reduce the user experience.

**Comment by VladyslavBondarenko** [comment]
@229106948 
please follow up on https://github.com/flutter/flutter/issues/24791,
I'm closing the current one as duplicate,
If you disagree please write in the comments and I will reopen it
