### ISSUE TITLE
cached_network_image errors.dart import error

### ISSUE THREAD

**Issue by hagyao520** [flutter/flutter#45757]
After updating the version, the dart call cached network image reports an error. I didn't use it, just import

**Comment by iapicca** [comment]
Hi @hagyao520 
could you please provide your updated  `flutter doctor -v`,
your `flutter run --verbose` and a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
