### ISSUE TITLE
App-level Build.gradle file shows error that Cannot resolve Symbol "GradleException"  in every Flutter Project either its new or old , edited or non edited

### ISSUE THREAD

**Issue by kamalkant56** [flutter/flutter#45764]
**OS :- Windows 10 home 64bit
IDE:- Android Studio version 3.5
Flutter version :- 1.9. 1 +hotflix .6
Gradle version :- 6.0.1**

Error which I am facing.

![image](https://user-images.githubusercontent.com/58288647/69789538-c399ac80-11e6-11ea-92fe-96457a577eaa.png)

 in **App level build.gradle file**. I am getting an error ~ **cannot resolve symbo**l "**GradleException**''. 
![image](https://user-images.githubusercontent.com/58288647/69790076-c8ab2b80-11e7-11ea-9bec-f8703c658e4a.png)
 I have checked the google but I am unable to solve my problem.  I had tried almost everything like  1 **Invalidate Chaches/restart**
![image](https://user-images.githubusercontent.com/58288647/69789644-f6dc3b80-11e6-11ea-8364-93f84d7c9367.png)

2. Changes some setting in  File --> **Project Structure**
      a. **Project**  
![image](https://user-images.githubusercontent.com/58288647/69789820-4cb0e380-11e7-11ea-90b6-861b466bff65.png)
     
      b. 
![image](https://user-images.githubusercontent.com/58288647/69789893-6ce0a280-11e7-11ea-8bc8-bb8cf08d2760.png)
 c. 
![image](https://user-images.githubusercontent.com/58288647/69789907-7538dd80-11e7-11ea-8a52-7b9cea2f99ee.png)

But nothing worked for me.....

one more thing I have noticed that I am facing similar in error in almost every project either it's new or old. whenever I open Android's app-level Build.gradle file. its automatically showing the error that " cannot resolve symbol GradleException"

**Comment by kamalkant56** [comment]
Solution for:-

OS:- Windows 10 Home 64bit

IDE :- Android Studio 3.5

Flutter version 1.9.5 hotflix 6

Gradle version 6.0.1



1. If you are getting property error e.g. Cannot Resolve symbol "Property" go to File => Project Structure => below the "Project Settings " select project and then change the Project SDK from NO SDK to Android API 28 ( whatever the stable one).



2. If you are getting GradleException error e.g. Cannot Resolve symbol "GradleException"

simple change the name form GradleException ( "  text ") to FileNotFoundException ( "  text ")

**Comment by iapicca** [comment]
Hi @kamalkant56 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by RishiKumar158** [comment]
is that safe to changing name from  GradleException ( " text ") to FileNotFoundException ( " text ") ???

**Comment by RishiKumar158** [comment]
because i did the same thing but i am thinking it is correct way or not
if any body knows correct way tell me

**Comment by zyllus17** [comment]
I too have the same problem. It can be fixed as of now by following these steps 

https://github.com/flutter/flutter/issues/29608#issuecomment-578383592

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by radeksvarz** [comment]
> 2. If you are getting **GradleException error** e.g. **Cannot Resolve symbol "GradleException"**
>    simple **change the name** form **GradleException** ( "  text ") to **FileNotFoundException** ( "  text ")

Does not resolve the issue. Neither using only **Exception** (...

Win 10 H 64b
IDE: AS 3.6
Flutter v:  1.18.0-9.0.pre.122
Gradle: --- I do not know
