### ISSUE TITLE
Create the Flutter project using Android Studio,Why can't use capital letters for the project name？

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#45762]
Create the Flutter project using Android Studio. Why not use capital letters for the project name？

**Comment by iapicca** [comment]
Hi @gionchat 
I believe your question was answered [here](https://github.com/flutter/flutter-intellij/issues/1009#issuecomment-300514763).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
