### ISSUE TITLE
[local_auth] Phone preferred auth is face but print fingerprint. authenticateWithBiometrics failed

### ISSUE THREAD

**Issue by ivanooi** [flutter/flutter#45775]
```
      List<BiometricType> availableBiometrics = await _auth.getAvailableBiometrics();
      print( availableBiometrics );

     Phone preferred auth is Face ID.
     but getAvailableBiometrics return fingerprint.
     
      isAuthenticated =
      await _auth.authenticateWithBiometrics(
          localizedReason: 'Please authenticate to show account balance');
      
      failed. nothing popup. it works with version 0.5 
```

another question :
should getAvailableBiometrics return the whole available biometrics list?
instead of only the preferred biometric. 
Thanks 

![image](https://user-images.githubusercontent.com/15061028/69806485-e98e7380-121d-11ea-97ac-e51ad391a130.png)

![image](https://user-images.githubusercontent.com/15061028/69806155-302f9e00-121d-11ea-994f-875c81590d56.png)

![image](https://user-images.githubusercontent.com/15061028/69805936-b992a080-121c-11ea-868c-80b60fd21008.png)

![image](https://user-images.githubusercontent.com/15061028/69805951-c4e5cc00-121c-11ea-82d2-8aa28c11c89e.png)

**Comment by iapicca** [comment]
Hi @ivanooi 
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem

Please refrain from posting pictures if not necessary.

Thank you

**Comment by ivanooi** [comment]
Thanks for the reply : 

this is the sample source code : 
[https://drive.google.com/open?id=1A-68SDLc8jjQ_GwcR7e-m6ZulSDAsA3b](url)


`flutter doctor -v

[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.13.6 17G2208, locale en-MY)
    • Flutter version 1.9.1+hotfix.5 at /Applications/Ivan/Flutter
    • Framework revision 1aedbb1835 (6 weeks ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ivanooi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Applications/Ivan/IntelliJ IDEA CE.app
    • Flutter plugin version 41.1.4
    • Dart plugin version 192.7761

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.


flutter run --verbose

[  +17 ms] executing: [/Applications/Ivan/Flutter/] git log -n 1
--pretty=format:%H
[  +51 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 1aedbb1835bd6eb44550293d57d4d124f19901f0
[        ] executing: [/Applications/Ivan/Flutter/] git describe --match v*.*.*
--first-parent --long --tags
[  +17 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.9.1+hotfix.5-0-g1aedbb1835
[  +10 ms] executing: [/Applications/Ivan/Flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Applications/Ivan/Flutter/] git ls-remote --get-url
origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +56 ms] executing: [/Applications/Ivan/Flutter/] git rev-parse --abbrev-ref
HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +70 ms] "flutter run" took 76ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

#0      FlutterCommand.validateCommand
(package:flutter_tools/src/runner/flutter_command.dart:568:9)
<asynchronous suspension>
#1      RunCommand.validateCommand
(package:flutter_tools/src/commands/run.dart:278:19)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:465:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#10     FlutterCommand.run
(package:flutter_tools/src/runner/flutter_command.dart:397:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure>
(package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main
(file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dar
t:8:3)
#40     _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:172:12)

`

**Comment by johnrocks-a11y** [comment]
Encountered the same issue 

Flutter Doctor
```
➜ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.16.4-pre.33, on Mac OS X 10.15.3 19D76, locale en-SG)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
[!] VS Code (version 1.43.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

**Comment by lzhuor** [comment]
Encountered the same issue on Samsung N9760 (Note 10+). 

Flutter Doctor
```
➜ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.16.4-pre.33, on Mac OS X 10.15.3 19D76, locale en-SG)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
[!] VS Code (version 1.43.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

**Comment by lzhuor** [comment]
@ivanooi . I think found the issue. I think in Android, regardless of its Fingerprint or Face Detection, it will use Fingerprint API even if it's doing face detection.

What you can do is to pass `androidAuthStrings` to override the default messages.

For example:
```dart
const ANDROID_AUTH_MESSAGES = AndroidAuthMessages(
    signInTitle: 'Biometric Authentication', fingerprintHint: '');

    // ...

await localAuth.authenticateWithBiometrics(
        sensitiveTransaction: false,
        localizedReason: '',
        androidAuthStrings: ANDROID_AUTH_MESSAGES);
```

**Comment by ivanooi** [comment]
great! thanks for the reply! I will try that. thanks again

**Comment by eddiesTime** [comment]
Is there any new developement regarding the behavior on Android? I've been playing around with a motorola one action which supports face unlock and finger print. When both scans are activated the device with default to finger print scan. Only if the finger print scan is deactivated via removing the finger print, the face unlock feature will be used.

Unfortunately, I did not find a setting to set one as preference for biometric authentication.

Does anyone with a different device, e.g., Samsung, experience a similiar behavior?

**Comment by TahaTesser** [comment]
<details>
<summary>code sample</summary>

```dart
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:local_auth/local_auth.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final LocalAuthentication auth = LocalAuthentication();
  bool _canCheckBiometrics;
  List<BiometricType> _availableBiometrics;
  String _authorized = 'Not Authorized';
  bool _isAuthenticating = false;

  Future<void> _checkBiometrics() async {
    bool canCheckBiometrics;
    try {
      canCheckBiometrics = await auth.canCheckBiometrics;
    } on PlatformException catch (e) {
      print(e);
    }
    if (!mounted) return;

    setState(() {
      _canCheckBiometrics = canCheckBiometrics;
    });
  }

  Future<void> _getAvailableBiometrics() async {
    List<BiometricType> availableBiometrics;
    try {
      availableBiometrics = await auth.getAvailableBiometrics();
    } on PlatformException catch (e) {
      print(e);
    }
    if (!mounted) return;

    setState(() {
      _availableBiometrics = availableBiometrics;
    });
  }

  Future<void> _authenticate() async {
    bool authenticated = false;
    try {
      setState(() {
        _isAuthenticating = true;
        _authorized = 'Authenticating';
      });
      authenticated = await auth.authenticateWithBiometrics(
          localizedReason: 'Scan your fingerprint to authenticate',
          useErrorDialogs: true,
          stickyAuth: true);
      setState(() {
        _isAuthenticating = false;
        _authorized = 'Authenticating';
      });
    } on PlatformException catch (e) {
      print(e);
    }
    if (!mounted) return;

    final String message = authenticated ? 'Authorized' : 'Not Authorized';
    setState(() {
      _authorized = message;
    });
  }

  void _cancelAuthentication() {
    auth.stopAuthentication();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      appBar: AppBar(
        title: const Text('Plugin example app'),
      ),
      body: ConstrainedBox(
          constraints: const BoxConstraints.expand(),
          child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: <Widget>[
                Text('Can check biometrics: $_canCheckBiometrics\n'),
                RaisedButton(
                  child: const Text('Check biometrics'),
                  onPressed: _checkBiometrics,
                ),
                Text('Available biometrics: $_availableBiometrics\n'),
                RaisedButton(
                  child: const Text('Get available biometrics'),
                  onPressed: _getAvailableBiometrics,
                ),
                Text('Current State: $_authorized\n'),
                RaisedButton(
                  child: Text(_isAuthenticating ? 'Cancel' : 'Authenticate'),
                  onPressed:
                      _isAuthenticating ? _cancelAuthentication : _authenticate,
                )
              ])),
    ));
  }
}
```
</details>
<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.402, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.402 at /Users/tahatesser/Code/flutter_master
    • Framework revision 2a188eeca3 (10 hours ago), 2021-01-17 19:27:00 -0800
    • Engine revision 609036f2bf
    • Dart version 2.12.0 (build 2.12.0-236.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>

**Comment by gj2569355373** [comment]
> Is there any new developement regarding the behavior on Android? I've been playing around with a motorola one action which supports face unlock and finger print. When both scans are activated the device with default to finger print scan. Only if the finger print scan is deactivated via removing the finger print, the face unlock feature will be used.
> 
> Unfortunately, I did not find a setting to set one as preference for biometric authentication.
> 
> Does anyone with a different device, e.g., Samsung, experience a similiar behavior?

Huawei also has this problem. Do you have a good way to choose the identification method？thanks

**Comment by huynguyennovem** [comment]
> Is there any new developement regarding the behavior on Android? I've been playing around with a motorola one action which supports face unlock and finger print. When both scans are activated the device with default to finger print scan. Only if the finger print scan is deactivated via removing the finger print, the face unlock feature will be used.
> 
> Unfortunately, I did not find a setting to set one as preference for biometric authentication.
> 
> Does anyone with a different device, e.g., Samsung, experience a similiar behavior?

I've tried to remove finger print, but it still required to Setup again. It does not invoke to authen by FaceID. How did you do to do this?

**Comment by umaqs** [comment]
I have a similar issue on Galaxy S10.

case: both face and fingerprint registered 
 - `authenticate()` shows both options to choose from.
 - `getAvailableBiometrics()` returns `[BiometricType.fingerprint]`
 
case: only face registered 
 - `authenticate()` shows face recognition prompt.
 - `getAvailableBiometrics()` still returns `[BiometricType.fingerprint]`

**Comment by fryette** [comment]
Any news on it?
Now impossible to make face id auth on Samsung devices

**Comment by thomaskellough** [comment]
I'm also having this issue with Samsung Galaxy A10s. I have Face ID registered and Fingerprint Registered and when I run `await localAuthentication.getAvailableBiometrics();` I get only an list of one item, `BiometricType.fingerprint`.

How can I get local_auth to register faceID on samsung devices?

**Comment by rockerhieu** [comment]
I'm also having this issue with Samsung S9.

**Comment by Kasperror** [comment]
Is anyone working on the fix rn or is it Android's internal policy not to use face for anything other than unlocking the screen thus unfixable?

**Comment by adminant** [comment]
I'm having the same issue with Samsung A10 and Android 10. FaceID is registered, but unavailable in local_auth

**Comment by hasinadevelop** [comment]
je me posait cette question, est ce qu'on a aussi ces problème si on utilise android natif par exemple sans utliser flutter et local_auth?

**Comment by swiftymf** [comment]
Has there been any progress on this issue? 
In the app we're writing, we want to be specific to the user when offering to set up biometrics by saying something like "Enable Face Recognition". However we are seeing unexpected behavior depending on which Android device we use. For example:
`Samsung Galaxy S20` has face and fingerprint, but in `getAvailableBiometrics` it only returns fingerprint regardless of what is setup in the device settings.
`Google Pixel 3a` has only fingerprint and returns fingerprint regardless of it being setup in device settings, rather than returning nothing or an error.
`Moto g7` has face only for unlocking the device and fingerprint for everything but returns both as options (should only be fingerprint), also regardless of what is setup in device settings.
It would be ideal for `getAvailableBiometrics` to either return an empty list if nothing is setup on the device or return an error similar to how `LocalAuthentication.authenicate` returns an error “NotEnabled”

**Comment by ruhulrahat** [comment]
Using `local_auth 2.1.2`.  Not getting face detection prompt, only fingerprint option showing. 
`getAvailableBiometrics()` returns `weak` and `strong` when both fingerprint and face is enrolled on device.
`getAvailableBiometrics()` returns empty list when only face is enrolled on device.

**Comment by stuartmorgan** [comment]
Closing as obsolete; we're now using the modern API, which doesn't operate in terms of specific biometrics, only string and weak. Which specific biometric is used is up to the device, and can't be controlled by the calling application.
