### ISSUE TITLE
'Flutter build bundlle' does not update local.properties 'flutter.versionCode'

### ISSUE THREAD

**Issue by TannerYoung** [flutter/flutter#45774]
## Steps to Reproduce

1. Create flutter project
2. bump pubspec.yaml version: 1.0.0+2
3. Perform steps at https://flutter.dev/docs/deployment/android
4. run `flutter build bundle`
5. local.properties version code is not updated
6. run `flutter build apk`
7. local.properties version code is updated.

**Target Platform:** android
**Target OS version/browser:** 23+
**Devices:** irrelevant

## Logs

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.424, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android
    devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To
      resolve this, run: flutter doctor
      --android-licenses
[✓] Chrome - develop for the web
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds
      Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart
      specific functionality.
[!] IntelliJ IDEA Community Edition (version
    2019.1)
    ✗ Flutter plugin not installed; this adds
      Flutter specific functionality.
[✓] IntelliJ IDEA Community Edition (version
    2018.3)
[✓] IntelliJ IDEA Community Edition (version
    2019.2)
[✓] Connected device (2 available)

! Doctor found issues in 3 categories.

```

**Comment by iapicca** [comment]
Hi @TannerYoung 
I see you are using an outdate version of `master` channel
could you please run 
`
 flutter channel <YOUR CHANNEL>
`
`
 flutter upgrade
`
If the issue persist please provide your updated `flutter doctor -v` 
thank you

**Comment by TannerYoung** [comment]
It appears I read the documentation wrong and should have been running `flutter build appbundle` instead of `flutter build bundle`.
