### ISSUE TITLE
camera app crashing when i use in multiple tabs

### ISSUE THREAD

**Issue by janardhanmupparaju** [flutter/flutter#45773]
i am using camera in TabBarView(i have 5 tabs and i am using camera in 2 tabs).when i move one tab to another app is crashing and giving below one in console.

<details>
  <summary>logs</summary>

```
I/CameraDeviceState(24272): Legacy camera service transitioning to state CAPTURING
E/BufferQueueProducer(24272): [SurfaceTexture-1-24272-25] queueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(24272): [SurfaceTexture-1-24272-25] cancelBuffer: BufferQueue has been abandoned
I/chatty  (24272): uid=10079(com.example.cameraappwithtabs) Binder:24272_4 identical 6 lines
E/BufferQueueProducer(24272): [SurfaceTexture-1-24272-25] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(24272): [SurfaceTexture-1-24272-25] connect: BufferQueue has been abandoned
E/BufferQueueProducer(24272): [SurfaceTexture-1-24272-25] setMaxDequeuedBufferCount: BufferQueue has been abandoned
W/Binder:24272_4(24272): type=1400 audit(0.0:142272): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=2208 scontext=u:r:untrusted_app:s0:c79,c256,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
E/libc    (24272): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (24272): Access denied finding property "persist.vendor.camera.privapp.list"
W/meraappwithtabs(24272): type=1400 audit(0.0:142273): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=2208 scontext=u:r:untrusted_app:s0:c79,c256,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
I/CameraManager(24272): Using legacy camera HAL.
W/Thread-42(24272): type=1400 audit(0.0:142274): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=2216 scontext=u:r:untrusted_app:s0:c79,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/libc    (24272): Access denied finding property "vendor.camera.hal1.packagelist"
E/libc    (24272): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (24272): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (24272): Access denied finding property "persist.vendor.camera.privapp.list"
I/CameraManager(24272): Using legacy camera HAL.
E/libc    (24272): Access denied finding property "vendor.camera.hal1.packagelist"
E/Camera  (24272): Error 2
I/RequestThread-1(24272): Flushing all pending requests.
E/RequestQueue(24272): cancel failed: no repeating request exists.
I/CameraDeviceState(24272): Legacy camera service transitioning to state ERROR
E/libc    (24272): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (24272): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (24272): Access denied finding property "vendor.camera.aux.packagelist"
D/AndroidRuntime(24272): Shutting down VM
E/AndroidRuntime(24272): FATAL EXCEPTION: main
E/AndroidRuntime(24272): Process: com.example.cameraappwithtabs, PID: 24272
E/AndroidRuntime(24272): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference
E/AndroidRuntime(24272):        at io.flutter.plugins.camera.Camera.startPreview(Camera.java:424)
E/AndroidRuntime(24272):        at io.flutter.plugins.camera.Camera$2.onOpened(Camera.java:160)
E/AndroidRuntime(24272):        at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:149)
E/AndroidRuntime(24272):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(24272):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(24272):        at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(24272):        at android.app.ActivityThread.main(ActivityThread.java:6810)
E/AndroidRuntime(24272):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24272):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(24272):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
I/Process (24272): Sending signal. PID: 24272 SIG: 9
Lost connection to device.
```

</details>

if you want i will share one sample app.

**Comment by iapicca** [comment]
Hi @janardhanmupparaju 
could you please provide your updated  `flutter doctor -v`
and a minimal code sample to reproduce the problem?
Thank you

**Comment by janardhanmupparaju** [comment]
[✓] Flutter (Channel master, v1.10.15-pre.252, on Mac OS X 10.14.6 18G1012, locale en-IN)
    • Flutter version 1.10.15-pre.252 at /opt/apps/flutter
    • Framework revision 903ebd714d (5 weeks ago), 2019-10-24 21:35:14 -0700
    • Engine revision 8d6b74aee6
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 1bd6e20d76)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/janardhan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 3BA08FB5-9466-49BE-905D-EFF0AD0691D3 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)





 This is sample app:


[CameraAppwithTabs.zip](https://github.com/flutter/flutter/files/3904010/CameraAppwithTabs.zip)

note: In this file i given lib folder and yaml file only can please add to sample app and test it.

**Comment by TahaTesser** [comment]
Hi @janardhanmupparaju 
Are you still experiencing this issue with latest stable?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by TahaTesser** [comment]
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
