### ISSUE TITLE
I have a issue of syntax with Aqueduct and Postgres. And I didn't find the solution.

### ISSUE THREAD

**Issue by lucasellery** [flutter/flutter#45779]
aqueduct db upgrade --connect postgres://read:read@localhost:5432/reads
-- Aqueduct CLI Version: 3.2.1
-- Aqueduct project version: 3.2.1
-- Updating to version 1 on new database...
    PostgreSQL connecting, read@localhost:5432/reads.
    Initializating database...
        CREATE TABLE _aqueduct_version_pgsql (versionNumber INT NOT NULL UNIQUE,dateOfUpgrade TIMESTAMP NOT NULL)
    Applying migration version 1...
        CREATE TABLE _Read (id BIGSERIAL PRIMARY KEY,title TEXT NOT NULL UNIQUE,author TEXT NOT NULL,year INT NOT NULL)
    Seeding data from migration version 1...
*** There was an issue. Reason: syntax error at end of input. Table: null Column: null

**Comment by iapicca** [comment]
Hi @lucasellery 
you might want to open the issue on [aqueduct](https://github.com/stablekernel/aqueduct/issues)'s github.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
