### ISSUE TITLE
[Android]: Flutter crashes after release (Android)

### ISSUE THREAD

**Issue by Ahmadre** [flutter/flutter#45781]
## Steps to Reproduce

1. Run ```flutter build appbundle --target-platform android-arm64,android-arm --release --build-name=$1 --build-number=$2```
2. Upload your app to the Google Play Store (Production!!!)
3. Download it
4. Open it!

It will crash directly after Splashscreen and open the keyboard and the keyboard will stay!!!

**Target Platform: Android / iOS**
**Target OS version/browser: Android 5 >= Android 10**
**Devices: Huawei P30, Other Android devices**

## Logs

```
rebar@Rebars-MacBook-Pro atemwegsliga % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.12.12-pre.3, on Mac OS X 10.15.1 19B88, locale de-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @Ahmadre 
are you experiencing the issue also with other channels?
Thank you

**Comment by Ahmadre** [comment]
Hi @iapicca

I already located the error. Some android devices behave different, then others who function stable. I found the Bug and will fix it. It's all ok with the android release build ❤️ Sorry for taking your time 🙌🏼
