### ISSUE TITLE
My flutter app does not run!

### ISSUE THREAD

**Issue by marioallaa** [flutter/flutter#45780]
### I cannot run or build any flutter app

![image](https://user-images.githubusercontent.com/36368155/69815588-edf36600-11f6-11ea-87a2-f52157791d43.png)

## 
I even created a new app, i just ran the code without making any changes to it and it gives me the same thing.. 

![image](https://user-images.githubusercontent.com/36368155/69815773-56424780-11f7-11ea-8c36-ee3ac555375f.png) 

##
I have had flutter running previously on my machine, i stopped using flutter for like 2 months and now it does not build and run any app.. 

```
Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts,       
consider enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Initializing gradle...
(This is taking an unexpectedly long time.)       \
Sending crash report to Google.
Initializing gradle...
Crash report sent (report ID: 6d91bad9874e629a)
Initializing gradle...
(This is taking an unexpectedly long time.)       |Oops; flutter has exited unexpectedly.      
(This is taking an unexpectedly long time.)
Crash report written to C:\Users\me\code\mark\app\mark\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
(This is taking an unexpectedly long time.)       /
```

**Comment by iapicca** [comment]
Hi @marioallaa 
have you tried following the instruction in the logs?
```
Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts,       
consider enabling software rendering with "--enable-software-rendering".
```
I see from the pictures that some log has been generated, could please attach it?

Please refrain from posting pictures if not necessary.

thank you

**Comment by marioallaa** [comment]
> 
> 

> ```
> Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts,       
> consider enabling software rendering with "--enable-software-rendering".
> ```

it worked when i ran `flutter run --enable-software-rendering` 

### Thank YOU!

**Comment by irenejohn997** [comment]
My flutter app is not running,is showing "error in opening zip file"

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by irenejohn997** [comment]
![IMG-20200203-WA0017](https://user-images.githubusercontent.com/41710028/73974177-2ebcd900-4924-11ea-9586-475847bfd097.jpg)

**Comment by irenejohn997** [comment]
Above is the error i get when i run flutter.

**Comment by irenejohn997** [comment]
This was the outcome,when i ran flutter doctor
![Screenshot (20)](https://user-images.githubusercontent.com/41710028/73974932-99224900-4925-11ea-8cf7-cee2fc66c3c7.png)

**Comment by Bilal-Akkil** [comment]
i have the exact same problem please help me

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
