### ISSUE TITLE
NoSuchMethodError: The method 'fold' was called on null.

### ISSUE THREAD

**Issue by IgnacioCentola** [flutter/flutter#45783]
When running a simple unit test, I´m getting the error mentioned on the title with the following log:

> NoSuchMethodError: The method 'fold' was called on null.
Receiver: null
Tried calling: fold<int>(0, Closure: (int, dynamic) => int)
dart:core                                                                               Object.noSuchMethod
package:equatable/src/equatable_utils.dart 4:19                                         mapPropsToHashCode
package:equatable/src/equatable.dart 35:46                                              Equatable.hashCode
package:dartz/src/either.dart 94:36                                                     Right.hashCode
dart:collection                                                                         _CompactLinkedHashSet.contains
package:matcher/src/pretty_print.dart 28:14                                             prettyPrint._prettyPrint
package:matcher/src/pretty_print.dart 119:22                                            prettyPrint
package:matcher/src/description.dart 49:11                                              StringDescription.addDescriptionOf
package:test_api                                                                        expect
package:flutter_test/src/widget_tester.dart 234:3                                       expect
test\features\number_trivia\domain\use_cases\get_concrete_number_trivia_test.dart 33:7  main.<fn>

Entity classes:

```
class NumberTrivia extends Equatable {
  final String text;
  final int number;

  NumberTrivia({
    @required this.text,
    @required this.number,
  });

  @override
  // TODO: implement props
  List<Object> get props => null;
}
```

```
abstract class Failure extends Equatable {
  Failure([List properties = const<dynamic>[]]);
}
```

This is my use case class, the `Either` class corresponds to the `dartz` package:

```
class GetConcreteNumberTrivia {
  final NumberTriviaRespository repository;

  GetConcreteNumberTrivia(this.repository);

  Future<Either<Failure, NumberTrivia>> execute({@required int number}) async {
    return await repository.getConcreteNumberTrivia(number);
  }
}
```
My repository:

```
abstract class NumberTriviaRespository {
  Future<Either<Failure, NumberTrivia>> getConcreteNumberTrivia(int number);
  Future<Either<Failure, NumberTrivia>> getRandomNumberTrivia();
}
```
And my test, the `Right` class you see corresponds to the `dartz` package:

```
class MockNumberTriviaRepository extends Mock
    implements NumberTriviaRespository {}

void main() {
  GetConcreteNumberTrivia useCase;
  MockNumberTriviaRepository mockNumberTriviaRepository;


  setUp(() {
    mockNumberTriviaRepository = MockNumberTriviaRepository();
    useCase = GetConcreteNumberTrivia(mockNumberTriviaRepository);
  });

  final tNumber = 1;
  final tNumberTrivia = NumberTrivia(number: tNumber, text: 'test');
  test(
    'should get trivia from the repository',
    () async {
      //arrange
      when(mockNumberTriviaRepository.getConcreteNumberTrivia(any))
      .thenAnswer((_) async => Right(tNumberTrivia));
      //act
      final result = await useCase.execute(number: tNumber);
      //assert
      expect(result, Right(tNumber));
      verify(mockNumberTriviaRepository.getConcreteNumberTrivia(tNumber));
      verifyNoMoreInteractions(mockNumberTriviaRepository);
    },
  );
}
```

The error jumps in the `expect(result, Right(tNumber));` line, and I have no idea what to do with this method `fold`, all I know is that it´s in the `dartz` package. I´ve searched through docs and nothing, I don´t know what I´m doing wrong.

Anyone know how to fix it? Much appreciated!

**Comment by prayatna** [comment]
@IgnacioCentola were you able to fix this issue? I am facing the same problem

**Comment by IgnacioCentola** [comment]
> 
> 
> @IgnacioCentola were you able to fix this issue? I am facing the same problem

Yes, the issue lies in this line :
`List<Object> get props => null;`

When using Equatable, you must pass a list with the properties you define in your class`s contructor with the `props` propertie, as follows:
`List<Object> get props => [text, number];`
