### ISSUE TITLE
Reorderable List View – Dragging Background Color

### ISSUE THREAD

**Issue by skylerknight** [flutter/flutter#45799]
Flutters built-in ReorderableListView could seriously use an option for a custom background color when  being dragged. Seems like a pretty simple addition, just an optional widget property called draggingBackground or something.

**Comment by kenthinson** [comment]
I'm curious if you mean the background of the list view or the moving item or both?
If you mean the background of the list view it's transparent, so a workaround show in the picture is to wrap it in a colored container.

As far as the background of the in movement item I'm not sure...

![IMG_33C0C29F8217-1](https://user-images.githubusercontent.com/2245494/69855664-99310900-1251-11ea-910a-fd3abd0ae4c2.jpeg)

**Comment by skylerknight** [comment]
Good question. I'm actually referring to the moving item. I've built a couple of apps using the ReorderableListView and pretty satisfied with the way it works. Though I've noticed that there are times when a separate color for the moving item needs to be set, but can't be done. Because the onLongPress event is occupied when using the reorderable list view, it's difficult to use setState to set a custom color when a list item is being dragged. I've found myself modifying the ReorderableListView widget to add a "draggingColor" property several times.

It would be nice to have the option for a custom color for the moving item.

I hope this makes sense.

**Comment by kenthinson** [comment]
@skylerknight makes perfect sense! I’m surprised it can’t be changed to be honest. Have you considered submitting a pull request as you’ve already modified it several times?

**Comment by henriquel1997** [comment]
+1 for this feature, would really like to do this without modifying the ReorderableListView widget

**Comment by Hensohimself** [comment]
For a work around you can wrap your ReordableListView in a Theme, creating a ThemeData and give a your needed background as the canvasColor. 

return Theme(
      data: ThemeData(
        canvasColor: Colors.red
        ),
      child: ReorderableListView(
       //and so on..

**Comment by Gabriel-Mbugua** [comment]
> For a work around you can wrap your ReordableListView in a Theme, creating a ThemeData and give it your needed background as the canvasColor.
> 
> return Theme(
> data: ThemeData(
> canvasColor: Colors.transparent
> ),
> child: ReorderableListView(
> //and so on..

This actually worked for me. You'll still get a shadow but it's much better than having the white background.

**Comment by rtanyildizi** [comment]
> For a work around you can wrap your ReordableListView in a Theme, creating a ThemeData and give it your needed background as the canvasColor.
> 
> return Theme(
> data: ThemeData(
> canvasColor: Colors.transparent
> ),
> child: ReorderableListView(
> //and so on..

If you go to the Reorda

> > For a work around you can wrap your ReordableListView in a Theme, creating a ThemeData and give it your needed background as the canvasColor.
> > return Theme(
> > data: ThemeData(
> > canvasColor: Colors.transparent
> > ),
> > child: ReorderableListView(
> > //and so on..
> 
> This actually worked for me. You'll still get a shadow but it's much better than having the white background.

If you open ReorderableListView library you will find a code blog that the elevetion of the Metarial object defined as 6.0 like below;

----- reorderable_list.dart library ----------------

 feedback: Container(
          alignment: Alignment.topLeft,
          // These constraints will limit the cross axis of the drawn widget.
          constraints: constraints,
          child: Material(
            elevation: 6.0, // change elevation to 0.0 and then the ugly shadow disappears completely
            child: toWrapWithSemantics,
          ),
        ),
        .....

-----------------------------------------------------
It perfectly worked for me but I don't know if it's harmful to change the library files. Overall it's just elevetion

**Comment by magpiedigital** [comment]
> It perfectly worked for me but I don't know if it's harmful to change the library files. Overall it's just elevation.

It's a bad idea to change library files. Instead, just copy the code and rename the class.

**Comment by keane032** [comment]
how i can chage the font color of item inside list?

**Comment by THTServe** [comment]
Removing the elevation has the disadvantage of making it less obvious when the longpress has kicked in and the element is ready to be dragged.  If this is done then the suggestion above re changing the internal font colour on longpress would be nice.  Another option (not very elegant but not seeming to cause a problem)is to set the elevation really high.  E.g. lower elevations have darker shadow.  `elevation: 40.0` was a nice compromise for me.

**Comment by eldroan** [comment]
This would be really nice to have, currently having copypasted reorderablelistview with just an elevation change and wrapped it in a Theme to set the canvas transparent is really hacky. On the bright side at least it can be done...

**Comment by luizeduardotj** [comment]
In my case would be a great fix, since in my case, the design created a custom shadow for our Design System. Should been possible pass the elevation for the ReorderableList widget.

**Comment by WieFel** [comment]
My workaround without copying the entire file `reorderable_list.dart` is to additionally add `shadowColor: Colors.transparent` to the wrapping theme. If you want some light shadow, you can try `Colors.grey.withOpacity(0.1)` or similar.
```dart
Theme(
  data: Theme.of(context).copyWith(
    canvasColor: Colors.transparent,
    shadowColor: Colors.transparent,
  ),
  child: ReorderableListView(
    ...
  ),
)
```

**Comment by luizeduardotj** [comment]
> My workaround without copying the entire file `reorderable_list.dart` is to additionally add `shadowColor: Colors.transparent` to the wrapping theme. If you want some light shadow, you can try `Colors.grey.withOpacity(0.1)` or similar.
> 
> ```dart
> Theme(
>   data: Theme.of(context).copyWith(
>     canvasColor: Colors.transparent,
>     shadowColor: Colors.transparent,
>   ),
>   child: ReorderableListView(
>     ...
>   ),
> )
> ```

This workaround is great. Thank for shared!

**Comment by abhi-shek2000** [comment]
> For a work around you can wrap your ReordableListView in a Theme, creating a ThemeData and give it your needed background as the canvasColor.
> 
> return Theme(
> data: ThemeData(
> canvasColor: Colors.transparent
> ),
> child: ReorderableListView(
> //and so on..

Thanks a lot, shadow is much better than white background

**Comment by noxasch** [comment]
Another workaround is to wrap ListItem in Material widget

```
```
