### ISSUE TITLE
Experiencing the following issues with google maps plugin

### ISSUE THREAD

**Issue by rguntha** [flutter/flutter#45795]
Version: google_maps_flutter: ^0.5.21+12

Exceptions:
1. Unhandled Exception: MissingPluginException(No implementation found for method **map#update** on channel plugins.flutter.io/google_maps_0)

2. Unhandled Exception: MissingPluginException(No implementation found for method **markers#update** on channel plugins.flutter.io/google_maps_0)

3. Unhandled Exception: MissingPluginException(No implementation found for method **polygons#update** on channel plugins.flutter.io/google_maps_0)

4. Unhandled Exception: MissingPluginException(No implementation found for method **polylines#update** on channel plugins.flutter.io/google_maps_0)

5. Unhandled Exception: MissingPluginException(No implementation found for method **circles#update** on channel plugins.flutter.io/google_maps_0)

Flutter Doctor:
PS C:\Code\MultiHazardTracker\MHTFlutter\mht_flutter> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.12.15-pre.28, on Microsoft Windows [Version 10.0.16299.248], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.40.2)
[√] Connected device (1 available)

• No issues found!

**Comment by iapicca** [comment]
Hi @rguntha 
could you please provide your `flutter run --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by rguntha** [comment]
Hi @iapicca 
Please find the attached file containing the flutter verbose output.
The map is working fine, just that these exceptions keep coming in the logs.

I am attaching the minimal code, to give an idea how I am using the map. I think I am just using it in the normal way..

 ```
Widget build(BuildContext context) {
    return Scaffold(
        appBar: WidgetRepo.getAppBar(
            (!widget.isPending) ? 'View Landslides' : 'View Pending Landslides',
            context),
        drawer: AppDrawer(),
        body: GoogleMap(
                markers: mapHazardEventMarkers,
                mapType: MapType.hybrid,
                initialCameraPosition: currentCameraPosition,
                gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
                new Factory<OneSequenceGestureRecognizer>(
                    () => new EagerGestureRecognizer(),
                ),
                ].toSet(),
                onMapCreated: (GoogleMapController controller) {
                    if (!_completer.isCompleted) {
                        _completer.complete(controller);
                    }
                    this.controller = controller;
                }
            )
    },

```
[flutter_verbose.txt](https://github.com/flutter/flutter/files/3904830/flutter_verbose.txt)

**Comment by iapicca** [comment]
Thank you @rguntha

**Comment by spitfire55** [comment]
Any updates on this? There are now numerous issues on this issue tracker related to a MissingPluginException error taken that depend on the Google Maps controller (update, animate, etc.), and all of these issues have received zero feedback or advice.

**Comment by darshankawar** [comment]
@rguntha 
Is this still an issue using plugin's [latest](https://pub.dev/packages/google_maps_flutter/install) version ?
If so, can you provide a reproducible code sample that shows this log ?

**Comment by rguntha** [comment]
@darshankawar 
I am not experiencing the issue now. Thanks

**Comment by darshankawar** [comment]
Closing this based on above comment.
