### ISSUE TITLE
Optimize unneeded rebuild when pushing overlay/navigator opaque content

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#45797]
Internal: b/146212303

Related to: #11655 

Currently, there's an optimization performed by Navigator/Overlay such that when a full-screen opaque content is placed _above_ another content, the content behind will stop painting.

It is useful, but at the same time there's an irony:
The act of flagging the previously visible widget tree as no longer needing to be painted forces the entire associated widget tree to rebuild.

From my understanding, this is caused by a change in the depth of the associated widget tree during the transition. This, therefore, cause the widget tree to be deactivated and reactivated for a frame, which calls build/didChangeDependencies on everything. 

It is suboptimal, especially considering the widget tree is actually no longer visible.

My theory is that is should be possible to fix this inconvenience by a change on this line https://github.com/flutter/flutter/blob/d345a3b303ce041846ff895eb49a104bef133c4b/packages/flutter/lib/src/widgets/overlay.dart#L461 by changing it from:

```dart
_Theatre(
  onstage: Stack(
    fit: StackFit.expand,
    children: onstageChildren.reversed.toList(growable: false),
  ),
  offstage: offstageChildren,
);
```
to:
```dart
_Theatre(
  // somehow make _RenderTheatre fill the gap of the missing Stack
  onstage: onstageChildren.reversed.toList(growable: false),
  offstage: offstageChildren,
);
```

This should remove the reparenting, which should no longer unnecessarily rebuild the no longer visible widget tree.

**Comment by SBDavid** [comment]
> This is working as intended. In general, you should assume that all widgets can rebuild at any time, that they don't is mostly just an optimisation.
> 
> In particular, routes will rebuild because their navigator state has changed so they might need to update how they draw back buttons and the like.

I fix the "rebuild" problem by adding a key to Overlay build function.

First I add a GlobalKey to `OverlayEntry` class. For example `_key2`. This key will be used in `TickerMode`, the purpose is to give a Key to overlay offstage elements. 
```dart
class OverlayEntry {

  OverlayState _overlay;
  final GlobalKey<_OverlayEntryState> _key = GlobalKey<_OverlayEntryState>();

  final GlobalKey _key2 = GlobalKey();
}
```

And the next step is add `_key2` to build function.

```dart
class OverlayState extends State<Overlay> with TickerProviderStateMixin {
@override
  Widget build(BuildContext context) {
    final List<Widget> onstageChildren = <Widget>[];
    final List<Widget> offstageChildren = <Widget>[];
    bool onstage = true;
    print("overlay build");
    for (int i = _entries.length - 1; i >= 0; i -= 1) {

      final OverlayEntry entry = _entries[i];
      if (onstage) {
        print("onstage ${entry._key}");
        onstageChildren.add(_OverlayEntry(entry));
        if (entry.opaque)
          onstage = false;
      } else if (entry.maintainState) {
        offstageChildren.add(TickerMode(key: entry._key2, enabled: false, child: _OverlayEntry(entry)));
        print("offstage ${entry._key}");
      } else {
        print("!maintainState ${entry._key}");
      }
    }
    return _Theatre(
      onstage: Stack(
        fit: StackFit.expand,
        children: onstageChildren.reversed.toList(growable: false),
      ),
      offstage: offstageChildren,
    );
  }

}
```

And then Flutter diff algorithm will know how to update offstage element properly, other than just inflateWidget. The inflateWidget method will reload images which were used in offstage elements, thus cause serious performance issue.

**Comment by jkurtw** [comment]
b/146212303

**Comment by liyuqian** [comment]
Is the code in https://github.com/flutter/flutter/issues/11655#issue-250890695 also a reproduction for the issue here? If this issue has a significant performance impact, maybe it's nice to write a Flutter driver test (https://flutter.dev/docs/cookbook/testing/integration/profiling) so we can have some metrics to track.

**Comment by goderbauer** [comment]
There's a fix out for review: https://github.com/flutter/flutter/pull/48900.

**Comment by goderbauer** [comment]
As documented in the PR, this change had a positive affect on some of our transition benchmarks: https://github.com/flutter/flutter/pull/48900#issuecomment-577297920. 

Thanks for the suggestion!
