### ISSUE TITLE
flutter build shows a wrong bundle identifier

### ISSUE THREAD

**Issue by shouichi** [flutter/flutter#45790]
`flutter build` shows a wrong bundle identifier when there are multiple schemes. 

We have `dev` and `prod` schemes and change the bundle identifier based on scheme (`com.example.app.dev` for `dev` and `com.example.app` for `prod`). When we build ios app `flutter build ios` always shows `com.example.app.dev` regardless of flavor.

This is because flutter looks up the bundle identifier from pbxproj using regex and it always uses the first match. (To be precise, flutter also looks up Info.plist before pbxproj but it uses pbxproj when the bundle identifier in Info.plist contains `$`.)

https://github.com/flutter/flutter/blob/d345a3b303ce041846ff895eb49a104bef133c4b/packages/flutter_tools/lib/src/project.dart#L400

## Steps to Reproduce

1. Add schemes (e.g., `dev` and `prod`) to ios project.
2. Change bundle identifier based on scheme.
3. Build ios app specifying flavor (e.g., flutter build ios --flavor prod).

**Target Platform:** ios
**Target OS version/browser:**
**Devices:**

## Logs

```
$ flutter build ios --flavor dev
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.example.app.dev for device (ios-release)...
$ flutter build ios --flavor prod
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.example.app.dev for device (ios-release)...
```

```
[✓] Flutter (Channel unknown, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G87, locale en-JP)
    • Flutter version 1.9.1+hotfix.6 at /Users/shouichi/local/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/shouichi/local/android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/shouichi/local/android
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0
```

**Comment by at-toannguyen3** [comment]
I have the same issue!
Do we have an update on this?

**Comment by jmagman** [comment]
This should be fixed in https://github.com/flutter/flutter/pull/47993 (uses the `PRODUCT_BUNDLE_IDENTIFIER ` build setting, only falls back to the project file search when Xcode isn't installed), which is in v1.13.7, on the dev channel.

Please let us know if that's still not working for you and we can keep investigating at https://github.com/flutter/flutter/issues/35163.

**Comment by Kiruel** [comment]
This is issue is still there. On `v1.15.19-pre.17`.
