### ISSUE TITLE
[iOS] Create FlutterViewControllers at same time will result in crash.

### ISSUE THREAD

**Issue by MrLittleStrong** [flutter/flutter#45802]
## Steps to Reproduce

While Adding Flutter to existing App, I found it's easy to crash when some  FlutterViewControllers launch at same time.
```

- (void)handleButtonAction {
    FlutterViewController *controller = [[FlutterViewController alloc]init];
    FlutterViewController *controller1 = [[FlutterViewController alloc]init];
    FlutterViewController *controller3 = [[FlutterViewController alloc]init];
    FlutterViewController *controller4 = [[FlutterViewController alloc]init];
    FlutterViewController *controller5 = [[FlutterViewController alloc]init];
    FlutterViewController *controller6 = [[FlutterViewController alloc]init];
    FlutterViewController *controller7 = [[FlutterViewController alloc]init];

    [controller setInitialRoute:@"loginCenter"];
    [controller.view setBackgroundColor:[UIColor clearColor]];
    controller.modalPresentationStyle = UIModalPresentationOverCurrentContext;
    controller.viewOpaque = NO;
    self.modalPresentationStyle = UIModalPresentationCurrentContext;

    controller.hidesBottomBarWhenPushed = YES;
    [self presentViewController:controller animated:NO completion:nil];
}
```
As I triggered the method above, it will crash in FlutterViewController's ```viewWillAppear```method. 
Guess engine over-released some resources.
This is a particular situation while I didn't really write like this. However, I'm working on a hybrid app. When launching this app, in some cases, similar situation will happen . 

**Target Platform:** iOS
**Target OS version/browser:** all
**Devices:** all

## Logs

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale zh-Hans)
    • Flutter version 1.9.1+hotfix.6 at /Users/gzh/dev/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gzh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 6C179851-5A92-42B6-84A8-1176EABA62D4 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

```

**Comment by iapicca** [comment]
Hi @MrLittleStrong 
could you please provide your `flutter run --verbose`  ?
Thank you

**Comment by MrLittleStrong** [comment]
> Hi @MrLittleStrong
> could you please provide your `flutter run --verbose` ?
> Thank you

this command seems too long to paste. 
[flutter_run_verbose.txt](https://github.com/flutter/flutter/files/3905010/flutter_run_verbose.txt)

**Comment by chinmaygarde** [comment]
From the example, it is not clear if you built with or without ARC. If you built with ARC, it could be that the error is in engine teardown instead of creation. A symbolicated stack trace would be useful too.

**Comment by TahaTesser** [comment]
Hi @MrLittleStrong 
Can you please details asked above https://github.com/flutter/flutter/issues/45802#issuecomment-643550162
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
