### ISSUE TITLE
Is there a way to get current route?

### ISSUE THREAD

**Issue by furaiev** [flutter/flutter#45812]
Is it possible to check the current route without State?

I have some kind of interceptor - when a user gets 403 Status Code he is redirected to Login page. In case user catches 2 or more 403 status codes in the row he is redirected to Login as many times as many 403 he got.
For redirection I use a GlobalKey
```
AppKeys.navigatorKey.currentState.pushNamedAndRemoveUntil(
      Routes.login,
      (Route<Object> route) => false,
    );
```
How can I prevent a multiply redirection? I'd like to add a condition `currentRoute != Routes.login`.

**Comment by iapicca** [comment]
Hi @furaiev 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/45389)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by furaiev** [comment]
Hi @iapicca 
I hope that my case could be resolved without new methods. Getting the current route is an option.
