### ISSUE TITLE
你项目里example 里的flutter platform_channel_swift 打不开 (Google translate: Flutter platform_channel_swift in your project example won't open)

### ISSUE THREAD

**Issue by weiwensangsang** [flutter/flutter#45813]
自己试试就知道了。(**Google translate:** Just try it for yourself.)

**Comment by weiwensangsang** [comment]
不用了，项目已删。flutter用不起。

**Comment by janmoppel** [comment]
Hello @weiwensangsang !

Thank you for posting an issue.
We've translated this issue's description into English using Google Translate. If you're comfortable writing in English, please check the translation and update it if necessary.

Did you run it using the tool commands or from the Xcode itself? Also, can you please attach your `flutter doctor -v` command output?

**Comment by weiwensangsang** [comment]
@janmoppel  Thanks but no bother. I use flutter to deveop my clock app. But flutter can not get the status of battery. So I use methodchannel to use native api. But when I get the demo from flutter/example/platform_channel_swift, it just broken.  I am pretty sure the reason is the update of dependence two days ago broken something so i can not run  the demo from flutter. 
I delete my code and swicth to swiftui.
I just too tired to use the new tools likes flutter. 
I just can not believe that the demo from your project can not run. It seems like that you still have a lot bugs to fix. Maybe when you fix the 5000 issue I will back.

**Comment by weiwensangsang** [comment]
Next year I will back to try.
It seems like Flutter is just not ready.

**Comment by dnfield** [comment]
This issue is not actionable in its current state. There is no reproducible code in it, or even an error message or version of Flutter attached.

You could consider looking at the example app in the https://github.com/flutter/plugins/tree/master/packages/battery - this shows how to use platform channels to get battery info.
