### ISSUE TITLE
[navigator] fails w/ error "Failed assertion: '!_debugLocked': is not true."

### ISSUE THREAD

**Issue by Aneesh1990** [flutter/flutter#45822]
on button press Navigator.pushNamed(context, '/addStaff')

Navigation is not working in entire app.

**Comment by iapicca** [comment]
Hi @Aneesh1990 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose` (relative to the "press button" event)?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
