### ISSUE TITLE
Request to change Class *EdgeInsects* to MarginInsects or PaddingInsect

### ISSUE THREAD

**Issue by KelvnPere** [flutter/flutter#45824]
Coming from a Web Development or Android Development background, using the Margin or Padding Property can be very confusing in Flutter. The Class Name EdgeInsects doesn't make you think of Margin or Padding. In another words, the naming convention used is not consistent with what is used in Web or Android. Correct me if am wrong.

So this is what I am suggesting, I know refactoring the Class Name can be a huge work. Can an alternative be included. Like can i decide to either use margin: EdgeInsect or margin:MarginEdgeInsect. This would make understanding and thinking of positioning of elements much better.

**Comment by shyndman** [comment]
🐛

**Comment by goderbauer** [comment]
This would be too breaking at this point without providing much value.
