### ISSUE TITLE
[web]: invalid member on null: "_get"

### ISSUE THREAD

**Issue by Arpit1496** [flutter/flutter#45827]
when running my flutter project using flutter run -d chrome , the chrome opens the app with title and scaffold  but shows the "invalid member on null : _get error" in body part. The app had all material widgets and 1 http request.

**Comment by iapicca** [comment]
Hi @Arpit1496 
could you please provide your  `flutter doctor -v`
and a minimal code sample to reproduce the problem?
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
