### ISSUE TITLE
[web]: Unable to set HTML 5 data attribute for "Text" widget

### ISSUE THREAD

**Issue by sudip4036** [flutter/flutter#45828]
Unable to set HTML 5 data attribute for "Text" widget. 
children: <Widget>[
                         Text(
                              'This is text class',  
                              **//'data-cq-component' : "title",**
                          )

**Comment by iapicca** [comment]
Hi @sudip4036 
could you please provide your `flutter doctor -v`
and  a minimal code sample to reproduce the problem?
Thank you

**Comment by sudip4036** [comment]
**flutter doctor response:**
C:\McD\flutterProject\sampleweb>flutter doctor -v
Checking Dart SDK version...
Flutter requires PowerShell 5.0 or newer.
See https://flutter.dev/docs/get-started/install/windows for more.
Building flutter tool...
Running pub upgrade...
[√] Flutter (Channel dev, v1.12.15, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.12.15 at C:\Softwere\flutter\beta\flutter
    • Framework revision 459c7fb884 (6 days ago), 2019-11-26 17:04:51 +0000
    • Engine revision e136d637a8
    • Dart version 2.7.0

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] VS Code (version 1.40.2)
    • VS Code at C:\Users\sdas14\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
Code : Please refer line number 55. I am unable to provide "data-*" attribute
[main.dart.txt](https://github.com/flutter/flutter/files/3914026/main.dart.txt)

**Comment by iapicca** [comment]
Thank you for providing your flutter doctor,
could you explain more in dept what issue you are experiencing?
thank you

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/41563

**Comment by iapicca** [comment]
Hi @sudip4036 
I don't see in the [documentation ](https://flutter.dev/docs/development/ui/widgets/text)
any reference to the date attribute you are trying to set;
if I'm missing something could you please link the reference to me?
Is it yours a proposal for an implementation of that attribute with `Text` widget?
thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by aniketambore** [comment]
Yo!, So the question is how can we set the js attribute declared in the<script>tag in index.html . From our flutter code / dart file .

**Comment by aniketambore** [comment]
![Screenshot (343)](https://user-images.githubusercontent.com/52826253/94131026-12ea5100-fe7b-11ea-84f9-cd46626ef04f.png)

---
The above picture is my updated index.html . I am trying to implement the payment gateway in flutter web.
Everything is working fine the payment gateway is also implemented . But my question is how can we set the value of the defined attributes of the **var options** map .
Like suppose if I want to change the value of **amount** how can it me updated everytime from the dart code?

**Comment by aniketambore** [comment]
**ui_fake.dart**
```
import 'dart:ui' as ui;

// ignore: camel_case_types
class platformViewRegistry {
  static registerViewFactory(String viewId, dynamic cb) {
    ui.platformViewRegistry.registerViewFactory(viewId, cb);
  }
}
```
---

**razorpay_web.dart**
```
import 'package:flutter/material.dart';
import 'dart:html';
import 'dart:ui' as ui;
import 'ui_fake.dart' if (dart.library.html) 'dart:ui' as ui;

class RazorPayWeb extends StatelessWidget {
  @override
  Widget build(BuildContext context) {

    //register view factory
    ui.platformViewRegistry.registerViewFactory("rzp-html",(int viewId) {
      IFrameElement element=IFrameElement();
      //Event Listener
      window.onMessage.forEach((element) {
        print('---------------------------Event Received in callback: ${element.data}');
        if(element.data=='MODAL_CLOSED'){
          Navigator.pop(context);
        }else if(element.data=='SUCCESS'){
          print('PAYMENT SUCCESSFULL!!!!!!!');
        }
      });

    element.requestFullscreen();
    //element.src='assets/html/payment.html';
    element.style.border = 'none';
    return element;
  });

    return Scaffold(
        body: Builder(builder: (BuildContext context) {
          return Container(
            child: HtmlElementView(viewType: 'rzp-html'),
          );
        }));
  }
}
```

---

**main.dart**
```
import 'package:flutter/material.dart';
import 'package:razorpay_flutter/razorpay_flutter.dart';
import 'package:flutter/services.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:razorpay_payment_with_flutter/WebImplementation/razorpay_web.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: RazorPayWeb(),
    );
  }
}
```

**Comment by aniketambore** [comment]
@iapicca Now you can open the issue.

**Comment by iapicca** [comment]
@aniketambore 

please follow the indication in my last [message](https://github.com/flutter/flutter/issues/45828#issuecomment-569266510)

> Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
> All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by aniketambore** [comment]
OKAY
