### ISSUE TITLE
video_player on Linux Desktop throws exception

### ISSUE THREAD

**Issue by venkata-subbarao** [flutter/flutter#45834]
Hello,

I am pretty new to Flutter framework. Tried running video_player example(https://github.com/flutter/plugins/tree/master/packages/video_player/video_player)  for Linux platform. I am getting the following error.

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel flutter.io/videoPlayer)

Any suggestion would help.

Thanks,
Subbarao

**Comment by stuartmorgan** [comment]
Duplicate of #39091
