### ISSUE TITLE
AlertDialog with listview when appears above another AlertDialog lags scrolling

### ISSUE THREAD

**Issue by basnetjiten** [flutter/flutter#45838]
To reproduce this bug. Simply call a dialog box with button and on Clicking the button create Another AlertDialog with listView. This listView is very laggy. I think the problem is due to DialogBox under another DialogBox.

**Comment by iapicca** [comment]
Hi @basnetjiten 
does this [code ](https://gist.github.com/iapicca/d6aad95be2936ce6121c16621bcfcfd3)represent the issue you are describing?
Could you please provide your `flutter doctor -v`?
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
