### ISSUE TITLE
[theme] 'buttonColor' should depend from 'colorScheme'

### ISSUE THREAD

**Issue by bitsydarel** [flutter/flutter#45849]
## Steps to Reproduce
1- Create a material app widget
2- provide it a theme with a colorscheme
3- specify the home as a raisedbutton with a onPressed callback so that it's wont be disable.

**Target Platform:**
All
**Target OS version/browser:**
All
**Devices:**
All

As far as i understand, RaisedButton it's the material **Contained Button**, so the color of the button should be the primary color.

RaisedButton color is dependent on the ThemeData.buttonColor, ThemeData.buttonColor is equal to primarySwatch[600] which is not defined when using colorScheme , this [line](https://github.com/flutter/flutter/blob/b9a56b9f48462d897101284f5f57b8568ef683c6/packages/flutter/lib/src/material/theme_data.dart#L334) cause problem.

code to reproduce:
```dart
MaterialApp(
      theme: ThemeData.from(
        colorScheme: ColorScheme.light(),
      ),
      home: Center(child: RaisedButton(onPressed: () {})),
    )
```

 there's many places in theme_data that are dependent on the primarySwatch field, which cause nightmares between us and our designers.

**Comment by alikamal1** [comment]
do you want to override the default button color? if so, you can set `buttonColor` to the color you want
```dart
MaterialApp(
      theme: ThemeData.from(
        colorScheme: ColorScheme.light(),
        buttonColor:  Colors.blue  // specify the color 
      ),
      home: Center(child: RaisedButton(onPressed: () {})),
    )
```

**Comment by bitsydarel** [comment]
Unfortunately I’m not looking for a workaround, this is a bug because this should be done by the framework when creating a theme with colorScheme.

**Comment by bitsydarel** [comment]
@alikamal1 also ThemeData.from does not accept any other parameters. The workaround would be to use the copyWith

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by bitsydarel** [comment]
Any news on that issue ?
i think this should be labeled as fidelity because it's does not meet the [material guideline](https://material.io/components/buttons/#contained-button)

**Comment by HansMuller** [comment]
@bitsydarel it's been a long time since you opened this issue and I apologize for the lack of activity. If you're still interested in the topic, there's a wide-ranging proposal for updating the button widgets and their themes in #54776. The new proposal does bind the default button colors to the overall theme's ColorSchme, per the Material Design spec.
