### ISSUE TITLE
Add an example to Gallery of using new open url service

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4584]
Added as part of https://github.com/flutter/flutter/issues/4156, it's now possible to ask the system (iOS/Android) to open a URL.

Seems there must be something we could use this in in the Gallery as an example?
@mpcomplete @HansMuller?

@chinmaygarde can explain how if it's not obvious.

**Comment by HansMuller** [comment]
We could display some stock quotes using URLs like:

`http://finance.google.com/finance/info?client=b&q=NASDAQ:GOOGL`

A demo that loaded a quotes for a few symbols and allowed you to enter more would be very easy to put together.

**Comment by eseidelGoogle** [comment]
@HansMuller talked in person.  This bug is about simply clicking a link, we already have various demos which show pulling data from a URL.

This came up again this morning because a customer asked how to open a link from flutter.

**Comment by chinmaygarde** [comment]
https://gist.github.com/chinmaygarde/d778498418e30825d687147b79d070eb shows how to connect to the URI launcher and launching an example.

**Comment by HansMuller** [comment]
NICE. I will expose the UriLauncher service in the same we've exposed other Mojo services in Flutter.

I think we're going to want to use the term URL instead of URI. Ask @Hixie about that.
