### ISSUE TITLE
ListView item not updated while using future

### ISSUE THREAD

**Issue by mrSingh007** [flutter/flutter#45843]
ListView items are not updated in statefull widget.

## Steps to Reproduce

main.dart:
```
main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  @override
  build(context) {
    return MaterialApp(
        home: Scaffold(
            appBar: AppBar(
              title: Text('Easy List'),
            ),
            body: StatefullWidgetDemo()));
  }
}
```
and contactlist.dart:
```
import 'package:flutter/material.dart';
class StatefullWidgetDemo extends StatefulWidget {
  @override
  _StatefulWidgetDemoState createState() {
    return new _StatefulWidgetDemoState();
  }
}
class _StatefulWidgetDemoState extends State<StatefullWidgetDemo> {
  List<Text> ls = [];
  @override
  initState() {
    super.initState();
    new Future<String>.delayed(
            new Duration(seconds: 5), () => 'test')
        .then((String value) {
      setState(() {
        ls.add(Text(value)); //<<------- this 'test' value not rendered
      });
    });
  }
  @override
  build(context) {
    return ListView(children:  ls);
  }

}
```
**Target Platform: Android /Mac
**Devices: Nexus s5 (API 26)

## Logs / Error
No any error/log

**Comment by kenthinson** [comment]
I believe your problem is because you are trying to manage the state at the widget level. Eg List of Text widget. Instead of the data level. Eg String. If you use a List of string instead and a builder widget the builder will rebuild when the List of string is updated.

**Comment by mrSingh007** [comment]
Thanks, Sorry about misunderstanding,... This issue can be closed.

**Comment by iapicca** [comment]
Hi @mrSingh007 
I'm glad the issue is solved 
thank you for letting me know 

(thanks @kenthinson)
