### ISSUE TITLE
appbar collapse hides view content on un-collapse

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#4585]
I have an appbar with an expandedHeight, collapsedHeight and minimumHeight, and whenever I scroll down and collapse the appbar, when I scroll up and uncollapse it, the top part of my view is hidden by the appbar.

**Comment by HansMuller** [comment]
Using a flexible appbar is still a bit clunky.  The code that expands and collapses the appbar assumes that you've set the scrollables (top) padding to:

`new EdgeInsets.only(top: yourAppBarHeight + statusBarHeight)`

where statusBarHeight is 

`final double statusBarHeight = MediaQuery.of(context).padding.top`

If you're already setting things up that way and there's still a layout problem, could you send a test case?

**Comment by Hixie** [comment]
I believe this is no longer an issue in the new world. Please reopen if I misunderstood.
