### ISSUE TITLE
Flutter Desktop: MouseRegion localPosition bug.

### ISSUE THREAD

**Issue by kenthinson** [flutter/flutter#45858]
<del>Am I correct this is a bug? Or am I jus not understanding the description text correctly. </del>

EDIT:
An Update to this. I have found that Listener onPointerMove does in fact return two different values. So I believe this is in fact a bug with Mouse Region. 

## Steps to Reproduce
Create a mouse region. Expection position and localPosition to return a different value based on description text.

position:
Coordinate of the position of the pointer, in logical pixels in the global coordinate space

localPosition:
The [position] transformed into the event receiver's local coordinate system according to [transform].
```
MouseRegion(
        onHover: (event){
          setState(() {
            //Debug
            print("Position: " + event.position.dy.toString() + " Local Position: " + event.localPosition.dy.toString());
          });

        },
```

Actual output is the same for both.
```
flutter: Position: 297.07738681102364 Local Position: 297.07738681102364
flutter: Position: 284.7076464074803 Local Position: 284.7076464074803
flutter: Position: 274.447605670385 Local Position: 274.447605670385
flutter: Position: 264.7361999671916 Local Position: 264.7361999671916
flutter: Position: 261.16724423118984 Local Position: 261.16724423118984
flutter: Position: 259.34600215988627 Local Position: 259.34600215988627
flutter: Position: 258.71252665682414 Local Position: 258.71252665682414
flutter: Position: 258.71252665682414 Local Position: 258.71252665682414
flutter: Position: 258.71252665682414 Local Position: 258.71252665682414
```

**Target Platform:**
Flutter Desktop Mac OS X 10.15

EDIT:
Example of inconsistent offset.
**Listener onPointerMove localPosition**
![vlcsnap-2019-12-01-06h16m07s872](https://user-images.githubusercontent.com/2245494/69913802-76922200-1402-11ea-9e40-afdbd671070b.jpg)

**MouseRegion onHover localPosition**
![vlcsnap-2019-12-01-06h15m52s930](https://user-images.githubusercontent.com/2245494/69913816-a3463980-1402-11ea-92e6-0566e948f7f5.jpg)

The localPosition transform seems to not be happening. Visible by the offset of the AppBar height.

flutter doctor -v
[✓] Flutter (Channel beta, v1.11.0, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.11.0 at /Users/kent/Developer/flutter
    • Framework revision 856a90e67c (3 weeks ago), 2019-11-08 18:00:01 -0800
    • Engine revision af04338413
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kent/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by iapicca** [comment]
Hi @kenthinson 
could you please provide your updated  `flutter doctor -v` ?
Thank you

**Comment by kenthinson** [comment]
@iapicca added sorry.

**Comment by bleroux** [comment]
@iapicca You added the label 'platform-windows', looks like you wanted to select 'platform-mac', no ?

**Comment by dkwingsmt** [comment]
Yes, your understanding is correct and it's indeed a bug as described in https://github.com/flutter/flutter/issues/33675. We haven't had the opportunity to implement it due to various reasons. I'll close it in favor of that one.
