### ISSUE TITLE
Create a linter rule that warns if people add a constructor to StatefulWidgets

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#45868]
From reading through StackOverflow, Flutter users make a common mistake: they write:

```dart
class MyStateful extends StatefulWidget {
  const MyStateful({Key key, this.props}): super(key: key);

  final int props;

  MyStatefulState createState() {
    return MyStatefulState(props);
  }
}

class MyStatefulState extends State<MyStateful> {
  MyStatefulState(this.props);

  int props;

  @override
  Widget build(BuildContext context) {
    return Text('$props');
  }
}
```

when they should instead do:

```dart
class MyStateful extends StatefulWidget {
  const MyStateful({Key key, this.props}): super(key: key);

  final int props;

  MyStatefulState createState() => MyStatefulState();
}

class MyStatefulState extends State<MyStateful> {
  Widget build(BuildContext context) {
    return Text('${widget.props}');
  }
}
```

This causes issues.

For example, this SO question is one of the most popular ones:
https://stackoverflow.com/questions/50818770/passing-data-to-a-stateful-widget/50818870#50818870

It is also regular for people to ask why `State` doesn't get updated in that situation, like https://stackoverflow.com/questions/59130099/how-does-the-stateful-vs-stateless-distinction-affect-when-widgets-will-be-rebu

A linter rule like `no_state_constructor` that warns if there's a custom constructor on `State` should help people solve this issue naturally.

**Comment by devoncarew** [comment]
cc @pq, @a14n

**Comment by pq** [comment]
This is now implemented in a new lint `no_logic_in_create_state`:  https://github.com/dart-lang/linter/pull/1877 and will be available in the next linter release (`0.1.106`).

**Comment by HansMuller** [comment]
NICE

**Comment by pq** [comment]
As of https://github.com/dart-lang/sdk/commit/c0dfdb27e77bc7f6ddd35d93f5f4e2104210a69e, this is in the Dart SDK; as of https://github.com/dart-lang/sdk/commit/d9570f907e8bd13166ee9a215c229ad130bb152a, there's a quick-fix to automate corrections.

Once it makes it's way into the Flutter SDK, I'd love any feedback. 👍

**Comment by dnfield** [comment]
Closing this as fixed
