### ISSUE TITLE
ChildView crash in MojoShell when embedding a "heavy" app

### ISSUE THREAD

**Issue by pylaligand** [flutter/flutter#4586]
## Steps to Reproduce
- Create an app that uses a lot of resources
- Embed that app in another app via ChildView
- CRASH

No such issue when embedding another app with a very light UI.
## Flutter Doctor

$ flutter doctor
[✓] Flutter (on Mac OS, channel unknown)
    • Flutter at /Users/pylaligand/Work/turquoise/sysui/src/third_party/flutter
    • Framework revision 7e8274e24f (17 hours ago), engine revision 93e9328662

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.26
## Logs and Crash Reports

```
[0616/164730:FATAL:view_registry.cc(562)] Check failed: false.
```

(https://github.com/domokit/mojo/blob/dec9013739bd49292096072912197341fa056795/services/ui/view_manager/view_registry.cc#L562)

Note that this used to work when synced to Flutter at 0d21e69b1dd88db7f0c50de81bfba703e7905cc8. Here's the diff:
flutter/flutter@7e8274e Update engine.version (#4580)
flutter/flutter@5766cda Define LayoutWidgetBuilder in terms of BoxConstraints instead of Size (#4578)
flutter/flutter@661740d updates from previous review (#4577)
flutter/flutter@fc2dbde Remove unused consts in floating action button code (#4574)
flutter/flutter@e2299fd Remove unused consts in floating action button code. FAB segue animation is done in scaffold and the consts are there.
flutter/flutter@fc47909 send application files to the observatory's devfs (#4572)
flutter/flutter@3ee2f6f Fix the switch to match the Material Design spec.

/cc @abarth

**Comment by abarth** [comment]
`view_registry.cc` is part of Mozart, so we should /cc @j9brown

**Comment by j9brown** [comment]
Ah, you hit an unimplemented case during view transfer.  Is this blocking you?

**Comment by pylaligand** [comment]
I've neutralized the code path that leads to this error locally, and this is a part of the codebase I'm pretty much the only one using right now. So, not P0 but probably P1.

**Comment by j9brown** [comment]
+Michael Jurka <mikejurka@google.com>

It's basically a race.  If you add a view then quickly remove it, and
re-add it somewhere else before the view has had a chance to transfer its
token then we hit this unimplemented case.  This is probably something Mike
Jurka could fix pretty easily.  It's even marked with a TODO in the code.

Jeff.

**Comment by mikejurka** [comment]
Filed bug here: https://github.com/domokit/mojo/issues/801

**Comment by Hixie** [comment]
I believe mojoshell is no longer a thing and this is probably obsolete.

**Comment by mikejurka** [comment]
It was fixed in Mozart in https://github.com/domokit/mojo/commit/a264fc69c1e682eb642ac1c29dc891b33d04a9e6
