### ISSUE TITLE
Can Flutter use devTools in profile mode?

### ISSUE THREAD

**Issue by 2534290808** [flutter/flutter#45879]
Can Flutter use devTools in profile mode?

**Comment by iapicca** [comment]
Hi @2534290808 
you might want to look at the docs for [profiling](https://flutter.dev/docs/perf/rendering/ui-performance)
thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
