### ISSUE TITLE
local_auth: ^0.6.1 useErrorDialogs support multi language

### ISSUE THREAD

**Issue by suchul** [flutter/flutter#45871]
Hi
I need to support the AndroidGoToSettingsDescription function in useErrorDialogs but I need multilingual support.

How can I handle this problem?

please check this issue.

**Comment by iapicca** [comment]
Hi @suchul 
could you explain the issue more in details?
You mention in the title [local_auth](https://pub.dev/packages/local_auth),
but if you are looking for internationalization options you might want to look at this [docs](https://flutter.dev/docs/development/accessibility-and-localization/internationalization).
thank you

**Comment by suchul** [comment]
Hi

I attatched screen shot

I found that character in your code

I would like to use the features contained in this phrase externally

I want to use this character for multi language supported

currently only English support

String get androidGoToSettingsDescription => Intl.message(
    'Fingerprint is not set up on your device. Go to '
    '\'Settings > Security\' to add your fingerprint.',
    desc: 'Message advising the user to go to the settings and configure '
        'fingerprint on their device. It shows in a dialog on Android side.');


Thank you.

2019년 12월 2일 (월) 오후 9:01, Francecsco Iapicca <notifications@github.com>님이
작성:

**Comment by iapicca** [comment]
> Hi I attatched screen shot I found that character in your code I would like to use the features contained in this phrase externally I want to use this character for multi language supported currently only English support

Hi again @suchul 
I don't see any attachment, could you try sharing it again please?
I apologize, but I'm not sure to understand your question;
if you are looking for solutions for internationalization with flutter
you might want to take a look to this [documentation](https://flutter.dev/docs/development/accessibility-and-localization/internationalization).
thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
