### ISSUE TITLE
[camera]resolution and ratio

### ISSUE THREAD

**Issue by wcyDreamer** [flutter/flutter#45872]
there are only 5 enum selections.and we can not customize the size of picture which i take.
i want to get a pic with low's 320*240 (4:3) and high quality.but i can not make it. Why the resolution and aspect ratio should be bound together, how to set them separately and take photos of various quality with specific aspect ratio

**Comment by iapicca** [comment]
Hi @wcyDreamer 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/45665)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
