### ISSUE TITLE
How to preserve scroll position for SliverLists when you navigate to and from a page

### ISSUE THREAD

**Issue by fremfi** [flutter/flutter#45873]
I tried adding a pagestorage key to the page, but it didn't work, maybe i'm doing it wrong.
thanks.

**Comment by iapicca** [comment]
Hi @fremfi 
could you please provide your `flutter doctor -v`
and a minimal code sample to reproduce the problem?
Thank you

**Comment by fremfi** [comment]
Hey, decided i'll just use indexedstack. thanks
