### ISSUE TITLE
[image_picker] aar or framework cannot be used after packaging

### ISSUE THREAD

**Issue by caoyunxiao** [flutter/flutter#45883]
aar or framework cannot be used after packaging

**Comment by iapicca** [comment]
Hi @caoyunxiao 
could you please deescribe the issue more in details 
and  provide your `flutter doctor -v` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by caoyunxiao** [comment]
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.13.6 17G7024,
    locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/caoyunxiao/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

**Comment by iapicca** [comment]
Hi again @caoyunxiao 
Thank you  for providing your flutter doctor -v ?
Could you could you please describe the issue more in details 
and post a minimal code sample to reproduce the problem
Thank you

**Comment by caoyunxiao** [comment]
I again with a detailed description of my problem, I use the official plugin image_picker, packaged to apple framework can't use, my project is iOS native mix flutter, flutter module partly through the framework form import, in the separate flutter engineering running normal, packaging integrated into iOS native project image_picker plugin no response.

**Comment by iapicca** [comment]
Are you try to[ Add Flutter to existing apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) ?

**Comment by caoyunxiao** [comment]
I did, I just plug-in image_picker unable to work

**Comment by iapicca** [comment]
Hi again @caoyunxiao 
could you please provide your `flutter run --verbose` ?
thank you

**Comment by caoyunxiao** [comment]
[  +19 ms] executing: [/Users/caoyunxiao/flutter/] git log -n 1 --pretty=format:%H
[  +34 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] eb6877bf926e5454379e42c95d49dcd60952dc62
[        ] executing: [/Users/caoyunxiao/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +23 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.9.1+hotfix.5-1-geb6877bf9
[   +6 ms] executing: [/Users/caoyunxiao/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/v1.9.1-hotfixes
[        ] executing: [/Users/caoyunxiao/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[   +8 ms] executing: [/Users/caoyunxiao/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] v1.9.1-hotfixes
[ +156 ms] executing: /Users/caoyunxiao/Library/Android/sdk/platform-tools/adb devices -l
[   +9 ms] Exit code 0 from: /Users/caoyunxiao/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +19 ms] executing: /Users/caoyunxiao/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[ +168 ms] /usr/bin/xcrun simctl list --json devices
[ +193 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +39 ms] Found plugin flutter_boost at /Users/caoyunxiao/flutter/.pub-cache/git/flutter_boost-8adac44a26cc86ea2b9df9819b23d6edb5a54dc1/
[  +10 ms] Found plugin image_picker at /Users/caoyunxiao/flutter/.pub-cache/hosted/pub.flutter-io.cn/image_picker-0.6.2+1/
[   +1 ms] Found plugin keyboard_visibility at /Users/caoyunxiao/flutter/.pub-cache/hosted/pub.flutter-io.cn/keyboard_visibility-0.5.6/
[   +8 ms] Found plugin path_provider at /Users/caoyunxiao/flutter/.pub-cache/hosted/pub.flutter-io.cn/path_provider-1.4.0/
[   +7 ms] Found plugin shared_preferences at /Users/caoyunxiao/flutter/.pub-cache/hosted/pub.flutter-io.cn/shared_preferences-0.5.4+3/
[  +36 ms] Found plugin flutter_boost at /Users/caoyunxiao/flutter/.pub-cache/git/flutter_boost-8adac44a26cc86ea2b9df9819b23d6edb5a54dc1/
[   +6 ms] Found plugin image_picker at /Users/caoyunxiao/flutter/.pub-cache/hosted/pub.flutter-io.cn/image_picker-0.6.2+1/
[   +1 ms] Found plugin keyboard_visibility at /Users/caoyunxiao/flutter/.pub-cache/hosted/pub.flutter-io.cn/keyboard_visibility-0.5.6/
[   +3 ms] Found plugin path_provider at /Users/caoyunxiao/flutter/.pub-cache/hosted/pub.flutter-io.cn/path_provider-1.4.0/
[   +2 ms] Found plugin shared_preferences at /Users/caoyunxiao/flutter/.pub-cache/hosted/pub.flutter-io.cn/shared_preferences-0.5.4+3/
[  +40 ms] executing: [/Users/caoyunxiao/Desktop/hantalk_flutter/ios/Runner.xcodeproj/] /usr/bin/xcodebuild -project /Users/caoyunxiao/Desktop/hantalk_flutter/ios/Runner.xcodeproj -target Runner -showBuildSettings

**Comment by xster** [comment]
What did you mean specifically by 

> packaging integrated into iOS native project image_picker plugin no response.

Was there any output in the console? Is there a minimal reproduction test project or code snippet we can try?

**Comment by caoyunxiao** [comment]
The Flutter project code was packaged into a framework and integrated into the iOS native, such as image_picker.framework and flicker. framework. In this case the image_picker does not work and the console does not print anything.

**Comment by caoyunxiao** [comment]
Hello, has this problem been fixed?

**Comment by caoyunxiao** [comment]
![image](https://user-images.githubusercontent.com/15682437/71794495-bfca3700-307c-11ea-9ebb-85757be9447d.png)
I found that the package framework in iOS use, _viewController == null, so presentViewController cannot be executed.

**Comment by xster** [comment]
may be solved by https://github.com/flutter/plugins/pull/2430

**Comment by xster** [comment]
This should be fixed now in v0.6.3. Please take a look and reopen if you're still facing issues.
