### ISSUE TITLE
[cocoon] Missing Cirrus status

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#45880]
Cirrus status has been missing on dashboard for the latest commits, over 20 commits currently. I suspect this is caused by https://github.com/flutter/flutter/issues/43097 and the proper fix would be changing Cocoon to use the checks API.

/cc @keyonghan @CaseyHillers 

<img width="113" alt="missing_cirrus" src="https://user-images.githubusercontent.com/6259181/69934089-cb2ab100-1485-11ea-903f-1ef31b384721.png">

**Comment by keyonghan** [comment]
Looking

**Comment by keyonghan** [comment]
@fkorotkov Could you please advise how we shall call the new API? This is how we call it now:https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/refresh_cirrus_status.dart#L43

```
  Stream<RepositoryStatus> listStatuses(RepositorySlug slug, String ref) {
    return PaginationHelper(_github).objects(
        "GET",
        "/repos/${slug.fullName}/commits/$ref/statuses",
        RepositoryStatus.fromJSON);
  }
```

 The latest commit gives us nothing when calling api: https://api.github.com/repos/flutter/flutter/commits/b9a56b9f48462d897101284f5f57b8568ef683c6/statuses
It works before for earlier commits:
https://api.github.com/repos/flutter/flutter/commits/3d4ceaf460f164128f72707b794e060cdf6a25df/statuses

We are using Github 5.1.0 btw:
https://pub.dev/packages/github/versions/5.1.0

Thank you!

**Comment by fkorotkov** [comment]
As described in #43097 you should've switch to this API: https://developer.github.com/v3/checks/suites/#list-check-suites-for-a-specific-ref

I thought it was implemented per the issue description.

**Comment by keyonghan** [comment]
I thought simply removing our old GO scripts should be enough. Sorry for the confusion. Could you suggest how shall we call the check API? Since we are directly calling Github 'listStatuses', which calls the status API, not sure how to change to the check API from our side.

**Comment by fkorotkov** [comment]
You can list check runs for a ref by using this API: https://developer.github.com/v3/checks/runs/#list-check-runs-for-a-specific-ref

**Comment by keyonghan** [comment]
I will look into it. At the same time, anything we can do to have the cirrus status back? Sorry for the inconvenience.

**Comment by fkorotkov** [comment]
@keyonghan I've already reverted the change but it will take an hour to deploy though a regular process. Don't want to go with a forced deploy (want all tests to run).

**Comment by keyonghan** [comment]
Sure. Thanks!

**Comment by keyonghan** [comment]
Cirrus status comes back. Closing this issue.

**Comment by fkorotkov** [comment]
The revert was deployed a few minutes ago. Should we reopen #43097?

**Comment by keyonghan** [comment]
Just reopened. Thanks for checking!

**Comment by keyonghan** [comment]
@fkorotkov could you advise if the check-runs API has any output limit for a specific commit? The following gives me "total_count": 51, but it only lists 30 run details in "check_runs":
`curl -H "Accept: application/vnd.github.antiope-preview+json" https://api.github.com/repos/flutter/flutter/commits/f68cdacdd5ae701de7c8e532342f91f85d5a071f/check-runs`

**Comment by fkorotkov** [comment]
Seems you need to check `Link` header of a response to do pagination. See output with `-I` flag:

```
curl -I -H "Accept: application/vnd.github.antiope-preview+json" https://api.github.com/repos/flutter/flutter/commits/f68cdacdd5ae701de7c8e532342f91f85d5a071f/check-runs
```

**Comment by keyonghan** [comment]
Thanks Fedor! This is exactly what I am looking for.
