### ISSUE TITLE
[iOS]  Flutter stuck on some models of iPhone

### ISSUE THREAD

**Issue by Windymonkeys** [flutter/flutter#45888]
Today，My Flutter application in iOS，when load image，The app is dead，But in Android，it worked...

**Comment by iapicca** [comment]
Hi @Windymonkeys 
could you please provide your `flutter doctor -v`
and your `flutter run --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
