### ISSUE TITLE
[web] BoxDecoration of the nested containers intercepts colour properties

### ISSUE THREAD

**Issue by mikepyts** [flutter/flutter#45896]
**Pre-history:**
This is one of the issues:
#45893
#45897
#45898
 which have been found on the way to make ListView in Flutter for web scrollable with a finger on touch screen, alternative for this is scrolling a list with a mouse pointer.

**Description of the issue:**
When you have 2 Containers nested one inside another one and provide BoxDecoration with Decoration image and  Color property to another, Color property is applied to the parent container and Decoration image to the child Container

**Steps to Reproduce**
1. Create a new Flutter project
2. Copy content of the gist https://gist.github.com/mikepyts/7b63b8e5086d4606c0d25631d27d5755 to the main.dart.
3. Uncomment issue number 2
4. Correct import issues
5. Run the project
7. Observe the behavior of color and Decoration image properties in two different cases

**Expected results**
Decoration image size should be applied to the Container where BoxDecoration is applied the same as color property.

**Actual results**
No matter of the order decoration image is applied to the child container size and color property to the parent container size

![image](https://user-images.githubusercontent.com/26088845/69953840-b7716000-1502-11ea-8f76-bc33e9ac5961.png)

**Target Platform: Web**
**Target OS version/browser: MacOS Catalina, Chrome**

## Flutter doctor
```
[✓] Flutter (Channel master, v1.12.16-pre.35, on Mac OS X 10.15.1 19B88, locale en-UA)
    • Flutter version 1.12.16-pre.35 at /Users/mike/Documents/flutter_master
    • Framework revision b9a56b9f48 (2 days ago), 2019-11-29 20:40:44 -0500
    • Engine revision 8672e79af8
    • Dart version 2.7.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools
```

**Comment by iapicca** [comment]
possible duplicate https://github.com/flutter/flutter/issues/44845

**Comment by mikepyts** [comment]
@iapicca  yes, closing this, will track #44845
