### ISSUE TITLE
hello_services sample is missing build configuration files

### ISSUE THREAD

**Issue by qchong** [flutter/flutter#4590]
The sample project is missing these files which currently need to be added by hand:
- `Generated.xcconfig` file in the `ios/flutter` folder, which is needed to build and run the sample app on iOS.
- `local.properties` file in the `/android` folder, which is needed to build and run the sample app on Android.

https://github.com/flutter/flutter/tree/master/examples/hello_services/

**Comment by abarth** [comment]
Those files contain values that are specific to your environment.  In the future, the `flutter` tool should know how to manipulate them, but we won't be able to check them into the repo because they'll still be user specific.

**Comment by abarth** [comment]
We now create the iOS file automatically.  We'll need to do something similar for Android.

**Comment by sethladd** [comment]
We've made tremendous strides in our integration with platform build tools. I'm closing this optimistically.

cc @mit-mit
