### ISSUE TITLE
image_picker: ^0.6.2+1 image rotation issue

### ISSUE THREAD

**Issue by rlee1990** [flutter/flutter#45905]
It appears that on devices android and ios when using the image_picker: ^0.6.2+1 portrait images are rotated by 90 degrees. If I use version 0.6.2 it works fine.

**Comment by iapicca** [comment]
Hi @rlee1990 
could you please provide your updated  `flutter doctor -v`?
Thank you

**Comment by rlee1990** [comment]
`[√] Flutter (Channel master, v1.12.12-pre.2, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
    • Flutter version 1.12.12-pre.2 at D:\nexttech\flutter_windows_v1.5.4-hotfix.2-stable\flutter        
    • Framework revision 033b897be5 (9 days ago), 2019-11-23 04:05:54 -0500
    • Engine revision b6b54fd606
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\king3\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.1)
    • VS Code at C:\Users\king3\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (3 available)
    • SM N950U   • ce061716d1923703017e • android-arm64  • Android 9 (API 28)
    • Chrome     • chrome               • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server           • web-javascript • Flutter Tools

• No issues found!`

**Comment by rlee1990** [comment]
@iapicca Not sure what was changed in the version but going back to 0.6.2 works without an issue.

**Comment by ratinggorilla** [comment]
Even I experienced the same issue.

```
Future getImage(String source) async {
    if (source == "camera") {
      File image = await ImagePicker.pickImage(source: ImageSource.camera);
      if (image != null) {
        return image;
      }
    }
    return null;
  }

```

**Comment by ratinggorilla** [comment]
I suspect something wrong with bitmap scaling.

**Comment by pushangupta** [comment]
@iapicca 
Hey there,

I managed to work around the rotation issue by changing the following method in ImageResizer.java

```
import android.media.ExifInterface;
import android.graphics.Matrix;


String resizeImageIfNeeded(
      String imagePath,
      @Nullable Double maxWidth,
      @Nullable Double maxHeight,
      @Nullable Integer imageQuality) {
//    return imagePath;
    boolean shouldScale =
        maxWidth != null || maxHeight != null || isImageQualityValid(imageQuality);
    String[] pathParts = imagePath.split("/");
    String imageName = pathParts[pathParts.length - 1];
    File file;
    Bitmap bmp = decodeFile(imagePath);
    if (bmp == null) {
      return null;
    }

    try {
      ExifInterface exif = new ExifInterface(imagePath);
      int orientation = exif.getAttributeInt(ExifInterface.TAG_ORIENTATION, 1);
      Log.d("EXIF", "Exif: " + orientation);
      Matrix matrix = new Matrix();
      if (orientation == 6) {
        matrix.postRotate(90);
      }
      else if (orientation == 3) {
        matrix.postRotate(180);
      }
      else if (orientation == 8) {
        matrix.postRotate(270);
      }
      bmp = Bitmap.createBitmap(bmp, 0, 0, bmp.getWidth(), bmp.getHeight(), matrix, true); // rotating bitmap
      file = createImageOnExternalDirectory(imageName, bmp, 100);
      copyExif(imagePath, file.getPath());

      if (!shouldScale) {
        file = createImageOnExternalDirectory(imageName, bmp, 100);
      } else {
        file = resizedImage(bmp, maxWidth, maxHeight, imageQuality, imageName);
      }
      copyExif(imagePath, file.getPath());
      return file.getPath();
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }
```



Basically I checked the EXIF data of the image at imagePath and re-oriented the image if it was rotated. I am sure there is a better approach which fits within the plugin flow. But as a quick solution, this might help. Thanks :)

**Comment by pushangupta** [comment]
Although resizing the image takes time and is a lot of computation. I personally am avoiding resizing the image by returning the imagePath as it is
```

import android.media.ExifInterface;
import android.graphics.Matrix;


String resizeImageIfNeeded(
      String imagePath,
      @Nullable Double maxWidth,
      @Nullable Double maxHeight,
      @Nullable Integer imageQuality) {
    return imagePath;
}
```

**Comment by cyanglaz** [comment]
Fixed in https://github.com/flutter/plugins/pull/2362, closing the issue
