### ISSUE TITLE
[dashboard] app flutter is failing some analyze checks. 

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#45912]
https://github.com/flutter/cocoon/pull/553/checks?check_run_id=324120569

cd app_flutter && flutter analyze
Analyzing app_flutter...                                        

warning • The parameter 'create' is required.  • lib/build_dashboard.dart:43:12 • missing_required_param
   info • 'builder' is deprecated and shouldn't be used. will be removed in 4.0.0, use create instead • lib/build_dashboard.dart:44:7 • deprecated_member_use
warning • The parameter 'create' is required.  • test/build_dashboard_test.dart:21:15 • missing_required_param
   info • 'builder' is deprecated and shouldn't be used. will be removed in 4.0.0, use create instead • test/build_dashboard_test.dart:22:7 • deprecated_member_use
warning • The parameter 'create' is required.  • test/build_dashboard_test.dart:36:15 • missing_required_param
   info • 'builder' is deprecated and shouldn't be used. will be removed in 4.0.0, use create instead • test/build_dashboard_test.dart:37:11 • deprecated_member_use
warning • The parameter 'create' is required.  • test/build_dashboard_test.dart:54:15 • missing_required_param
   info • 'builder' is deprecated and shouldn't be used. will be removed in 4.0.0, use create instead • test/build_dashboard_test.dart:55:11 • deprecated_member_use
warning • The parameter 'create' is required.  • test/build_dashboard_test.dart:72:15 • missing_required_param
   info • 'builder' is deprecated and shouldn't be used. will be removed in 4.0.0, use create instead • test/build_dashboard_test.dart:73:11 • deprecated_member_use
warning • The parameter 'create' is required.  • test/status_grid_test.dart:40:15 • missing_required_param
   info • 'builder' is deprecated and shouldn't be used. will be removed in 4.0.0, use create instead • test/status_grid_test.dart:41:17 • deprecated_member_use

12 issues found. (ran in 18.3s)

**Comment by CaseyHillers** [comment]
Fixed https://github.com/flutter/cocoon/commit/fbbf343646c544f861bcd794f592a57d8ff2f627!
