### ISSUE TITLE
Flutter Web Printing/ PDF/ Dart IO

### ISSUE THREAD

**Issue by mayankjanmejay** [flutter/flutter#45926]
Hi I am trying to use File operations in Flutter for web. I need to make a print/ download function but the File object doesn't work.

Attempting to use Dart.io operations like file. 

**Target Platform:** Web
**Target OS version/browser:** Windows 10 , Chrome 78.0.3904.108
**Devices:** Windows 

## Flutter doctor

PS P:\OneDrive - Cognitiv Control\Work\Apps\GreenTMS-PWA> flutter doctor -v
```
[√] Flutter (Channel dev, v1.12.0, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
    • Flutter version 1.12.0 at D:\flutter
    • Framework revision 9323a623bd (3 weeks ago), 2019-11-08 21:35:17 -0500
    • Engine revision 2f69e38160
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Mayank\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.2)
    • VS Code at C:\Users\Mayank\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools
```

**Comment by rjcalifornia** [comment]
"Attempting to use Dart.io operations like file."

You cannot use/import dart:io in Flutter Web. Or are you doing something else? Could you post some sample code?

**Comment by mayankjanmejay** [comment]
Yes I am trying to use Dart.IO in flutter for web. Is there any timeline for when we will get IO functions on the web?

  final pdf = pdfImport.Document();
  num index=0;
  pdf.addPage(pdfImport.Page(
  pageFormat: PdfPageFormat.a4,
  build: (context) {
    
    return pdfImport.Column(children: <pdfImport.Widget>[
    pdfImport.Text('labor')
    ]
    );
  }
 
  
));
  laborCodes.forEach( (labor) {
    index++;
pdf.addPage(pdfImport.Page(
  pageFormat: PdfPageFormat.a4,
  build: (context) {
    
    return pdfImport.Column(children: <pdfImport.Widget>[
    pdfImport.Text(labor)
    ]
    );
  }
 
  
));
  });
  await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save());
      print('In 1');
final file = File("C:\example.pdf");
await file.writeAsBytes(pdf.save());

**Comment by yjbanov** [comment]
Unfortunately, browsers do not provide direct access to the file system. However, this could be a plugin that stores files on the server or IndexedDB, or other storage supported by the browser.
