### ISSUE TITLE
Cocoon logs do not open in browser window anymore.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#45935]
They're downloaded as an attachment instead.  This is probably a matter of headers or something?

/cc @CaseyHillers @digiter @keyonghan

**Comment by CaseyHillers** [comment]
This is intentional (https://github.com/flutter/cocoon/pull/531).

There is work on https://github.com/flutter/flutter/issues/43124 to be able to redirect to the Google Cloud Log Viewer OR download the logs.

**Comment by dnfield** [comment]
Hmm.  Seems unfortunate, but will close in favor of https://github.com/flutter/flutter/issues/43124
