### ISSUE TITLE
[android_alarm_manager] Dart alarm handler never invoked even though onReceive is invoked by Android system

### ISSUE THREAD

**Issue by eligt** [flutter/flutter#45949]
I have a setup with 2 Android activities (both inheriting from `FlutterActivity`). The first one is the main app activity which register alarms and the handler for the alarm check some condition and if the condition is true then opens the second activity.

The app entry point then does a `runApp(FutureBuilder())` to determine which `App` widget to return. When the alarm scheduled is invoked I occasionally get the error in the title:
> FlutterView.send called on a detached view, channel=plugins.flutter.io/android_alarm_manager_background

I confirmed that this error is generated as this code path is started (inside the Alarm Manager plugin itself):
```java
  public void onReceive(Context context, Intent intent) {
    AlarmService.enqueueAlarmProcessing(context, intent);
  }
```
Which leads to this call inside `AlarmService::executeDartCallbackInBackgroundIsolate`:
```java
    sBackgroundChannel.invokeMethod(
        "", new Object[] {callbackHandle, intent.getIntExtra("id", -1)}, result);
```
**Important Addendum**: I edited the title of this issue because after more testing I noticed that sometimes the Dart handler function is not called with no error being generated but I confirmed that `onReceive` **is** invoked by the system. It looks like `enqueueWork` is not working as expected as `onHandleWork` is never called.

---
## Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @eligt 
are you still experiencing the issue 
with the latest stable version of flutter
and the latest version of `android_alarm_manager`?

If so,
could you please provide your update`flutter doctor -v` ,
your `flutter run --verbose`,
your `pubspec.yaml` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @eligt 
Are you still experiencing this issue with latest stable?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @eligt 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
