### ISSUE TITLE
About flutter_webview v0.3.16 ios platform multi-instance exception？

### ISSUE THREAD

**Issue by zhanghaigang666** [flutter/flutter#45957]
## env:
```
       webview_flutter: ^0.3.16
       Flutter (Channel stable, v1.9.1+hotfix.6,on mac os x 10.14.6 18G103) 
       xcode 11.2.1
       android studio (version 3.5)
```

## problem:
         1) Use the following code to find that the andorid platform is very smooth, but the iOS version release test is stuttered.
         2) Andorid platform can keep AutomaticKeepAlive successfully, but iOS platform cannot
         3) where index = 2 webview often fails to load the webview, and often the page text is misaligned and the scroll border is invalid

```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MaterialApp(home: WebViewExample()));
class WebViewExample extends StatefulWidget {
  @override
  _WebViewExampleState createState() => _WebViewExampleState();
}

class _WebViewExampleState extends State<WebViewExample> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter WebView example'),
        actions: <Widget>[
        ],
      ),
      body: Builder(builder: (BuildContext context) {
        return ListView.separated(
          addAutomaticKeepAlives: true,
          addRepaintBoundaries: false,
          cacheExtent: 0,
          itemCount: 5,
          separatorBuilder: (BuildContext context, int index) => Divider(),
          itemBuilder: (BuildContext context, int index) {
            return getWebviewer(index);
          },
        );
      }),
    );
  }

  Widget getWebviewer(int index) {
    return Center(
      child: Container(
        width: 350,
        height: 300,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Text("number $index webview"),
            Expanded(
              child: KeepWebView(),
            ),
          ],
        ),
      ),
    );
  }

  @override
  void initState() {
    super.initState();
  }
}

class KeepWebView extends StatefulWidget {
  final String url;
  KeepWebView({Key key, this.url}) : super(key: key);

  @override
  _KeepWebViewState createState() => _KeepWebViewState();
}

class _KeepWebViewState extends State<KeepWebView> with AutomaticKeepAliveClientMixin {
  bool get wantKeepAlive => true;
  final Completer<WebViewController> controllerCompleter = Completer<WebViewController>();
  bool isFinished = false;

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);

    return WebView(
      initialUrl:
          "https://flutter.dev/",
      javascriptMode: JavascriptMode.unrestricted,
      onWebViewCreated: (WebViewController controller) {
        controllerCompleter.complete(controller);
        print("on webview created");
      },
      onPageFinished: (String url) {
        print("on webview finished");
        isFinished = true;
      },
    );
  }
}
```

**Comment by janmoppel** [comment]
Hello @zhanghaigang666 !

Thank you for posting an issue.
Can you please also add the `flutter doctor -v` command output?

**Comment by zhanghaigang666** [comment]
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale
    zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/zhanghaigang/Flutter/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/zhanghaigang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/zhanghaigang/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • UDwqewq • af8455030423f19150cf4b3f3d844b682a1c07b0 • ios • iOS 11.4

**Comment by TahaTesser** [comment]
Hi @zhanghaigang666 
Are you still experiencing this issue?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Thank you

**Comment by TahaTesser** [comment]
Hi @zhanghaigang666 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
