### ISSUE TITLE
ReorderableListView widget does not drag animation in flutter web.

### ISSUE THREAD

**Issue by birdgang82** [flutter/flutter#45958]

**Comment by janmoppel** [comment]
Hello @birdgang82 !

Thank you for posting an issue. But without any additional information required in the template (description of the problem, steps to reproduce and `flutter doctor -v` output), it is impossible to act on it. 

Also, it looks like the similar problem has been already reported: #45959. If this is similar to your issue, you can follow the discussion there. If you have different problem, please feel free to file a new ticket with all information required in the template (description of the problem, steps to reproduce and `flutter doctor -v` output).

Thank you.
