### ISSUE TITLE
Android 9: Cleartext HTTP traffic not permitted in webview_flutter

### ISSUE THREAD

**Issue by premy** [flutter/flutter#45956]
Tried the settings in the Manifest and even adding a network_security_config file (following tips for native android) but to no avail.

**Comment by iapicca** [comment]
Hi @premy 
you mentioned following the steps to enable
just to double-check do they match what is described in the answer
on this stackoverflow [question](https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted)?

Could you please provide your updated  `flutter doctor -v`
and a minimal code sample to reproduce the problem?
Thank you

**Comment by deandreamatias** [comment]
Hi @premy
Maybe this problem [#37706](https://github.com/flutter/flutter/issues/37706) helps you. Try to read the solutions and send us your comments.
Good luck

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
