### ISSUE TITLE
[web]: Support crossorigin network images

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#45955]
A widget like `Image.network(/* url */)` does not show when `url` comes from a different origin. The image bytes are downloaded from the network.

**Comment by yjbanov** [comment]
Does the image come from the same origin? CORS disallows XHR requests across origins.

**Comment by cbenhagen** [comment]
@yjbanov in my case the images do not come from the same origin. Any quick tips on how to make this work? Can we add `crossorigin="anonymous"` somehow?

**Comment by CaseyHillers** [comment]
@yjbanov yes from a different origin.

**Comment by yjbanov** [comment]
We should be able to support `crossorigin="anonymous"` in the HTML backend. We'd need to audit our codebase for things that could break due to tainting the canvas, or avoid tainting altogether (e.g. by falling back to SVG or HTML).

Supporting this in WebGL without a proper CORS handshake is trickier. We will likely need to compose the scene graph together with `<img>` tags, but doing this efficiently in the presence of multiple crossorigin images can be tricky.

**Comment by cbenhagen** [comment]
This only seems to be an issue with the CanvasKit backend. When using the html backend the same images work.

My images are in a gcs bucket where I am able to set the CORS configuration (https://cloud.google.com/storage/docs/configuring-cors).

**Comment by yjbanov** [comment]
> When using the html backend the same images work.

Yes, we recently switched to using the `<img>` tag, which supports this out-of-the-box. Heads up though, there are some known issues with this approach, and so it's not yet super-clear if we can keep it as is.

**Comment by tvolkert** [comment]
@CaseyHillers is this what's keeping the commit author avatar images from showing in https://flutter-dashboard.appspot.com/#/build?

**Comment by CaseyHillers** [comment]
@tvolkert yes. For the flutter-dashboard app's use case, the DOM implementation works.

Do you know if this would impact `http.get` for the author image bytes from GitHub? If we can get the image bytes, we could use `Image.fromBytes` to show the author image.

**Comment by tvolkert** [comment]
I imagine it would also affect `http.get`, since it would be subject to the same CORS policy.

**Comment by CaseyHillers** [comment]
@tvolkert  I was able to get this to work in the build dashboard, so i'm not sure this was a CORS issue. I was able to do an `http.get` from the build dashboard to GitHub to get the avatar bytes, then I was able to use `Image.memory` to show it. I haven't tracked down yet why the engine isn't doing this.

**Comment by Paul-cbt** [comment]
I have the same issue , is there any workarround ?

**Comment by msoham123** [comment]
Workaround for those still looking: 

Append "https://cors-anywhere.herokuapp.com/" to the src of your network image

```
String src = "https://sourceofimage.com/image.png"
Image.network("https://cors-anywhere.herokuapp.com/"+ src)
```

**Comment by yjbanov** [comment]
We have documented various options available for CORS images at https://flutter.dev/docs/development/platform-integration/web-images. There's a push to require CORS on the plain `<img>` tags as well because of Spectre, so `<img>` will stop being an effective escape hatch.

**Comment by Katekko** [comment]
> Workaround for those still looking:
> 
> Append "https://cors-anywhere.herokuapp.com/" to the src of your network image
> 
> ```
> String src = "https://sourceofimage.com/image.png"
> Image.network("https://cors-anywhere.herokuapp.com/"+ src)
> ```

You can use `https://cors.bridged.cc/` aswell

**Comment by Elemenopeee** [comment]
A workaround for those who have enabled CORS but still cannot render images ->

https://flutter.dev/docs/development/tools/web-renderers

**Comment by seunghwanly** [comment]
> > Workaround for those still looking:
> > Append "https://cors-anywhere.herokuapp.com/" to the src of your network image
> > ```
> > String src = "https://sourceofimage.com/image.png"
> > Image.network("https://cors-anywhere.herokuapp.com/"+ src)
> > ```
> 
> You can use `https://cors.bridged.cc/` aswell

`https://cors.bridged.cc/` it worked for me !

**Comment by youssefApliman** [comment]
> 
> 
> > Workaround for those still looking:
> > Append "https://cors-anywhere.herokuapp.com/" to the src of your network image
> > ```
> > String src = "https://sourceofimage.com/image.png"
> > Image.network("https://cors-anywhere.herokuapp.com/"+ src)
> > ```
> 
> You can use `https://cors.bridged.cc/` aswell

it works Done and you can use http.get()

**Comment by fabioselau077** [comment]
for build: flutter build web --release --web-renderer html
for local: flutter run --web-renderer html
