### ISSUE TITLE
`flutter devices` wrongly reports iPhone 5 simulator as unsupported

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4595]
It's the default simulator for many XCode installs.  We technically support it just fine since it's x86. :)

The only reason we don't support iPhone 5 the physical device is that we don't currently distribute an ARMv7 (32-bit) binary since Apple devices have been 64-bit-only for every iOS device since iPhone 5.
https://github.com/flutter/flutter/issues/2089

**Comment by cbracken** [comment]
Related patch #7857 for future ref.

**Comment by xster** [comment]
Tested on head. Seems to have been resolved.
