### ISSUE TITLE
Websocket handshake exception in flutter

### ISSUE THREAD

**Issue by Manoharan10** [flutter/flutter#45967]
## Steps to Reproduce

**Exception:**
WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
I/flutter (10980): CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:352))

**Error:**

wss web socket handleshake exception when connect only WSS url.ws Url working fine in androi devices.wss url working on Ios devices only

**Flutter/Android**
**All OS in android**
**Android**

## Logs

WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
I/flutter (10980): CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:352))
```
```

```
```

```
```

**Comment by janmoppel** [comment]
Hello @Manoharan10 !

Thank you for posting an issue.
It seems that this problem has been already discussed here: https://stackoverflow.com/questions/54285172/how-to-solve-flutter-certificate-verify-failed-error-while-performing-a-post-req. Can you please check, whether proposed solution works for you?

If not, then can you please provide more information that would help to debug the issue? Such as minimal code example that reproduces the unexpected behaviour and `flutter doctor -v` command output?

Than you.
