### ISSUE TITLE
App.framework get obviously larger using latest flutter version

### ISSUE THREAD

**Issue by zhouyangyng** [flutter/flutter#45960]
My last flutter version is 1.10.15, and I upgrade flutter now.

```
[✓] Flutter (Channel master, v1.12.16-pre.32, on Mac OS X 10.14.6
    18G1012, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK
    version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.40.0)
[✓] Connected device (1 available)

• No issues found!
```

When I use 'flutter build ios', the App.framework size is 36M which is only 20M before.

![image](https://user-images.githubusercontent.com/22138883/70019151-4f368300-15c3-11ea-9094-bbdb9b5f2135.png)

![image](https://user-images.githubusercontent.com/22138883/70019239-8b69e380-15c3-11ea-8e61-8d693e7a3148.png)

**Comment by jmagman** [comment]
On v1.10.15 I made a new project with a single plugin, and `ios/Flutter/App.framework` is 9.2MB after `flutter build ios`.  On v1.12.17 it's 9.1M.

Can we get more information about your app?  A minimum reproduction case app may be necessary to see what bloated between versions.

**Comment by 991518961** [comment]
the same issue for me.before updating to the latest version is 30MB and then 52MB

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
