### ISSUE TITLE
Recently, in the Flutter project, I encountered the phenomenon that some iOS phones failed to load pictures

### ISSUE THREAD

**Issue by Windymonkeys** [flutter/flutter#45961]
Recently, in the Flutter project, I encountered the phenomenon that some iOS phones failed to load pictures, but there was no problem on the Android phone. I could not solve the problem by replacing the loading method and the picture address. How can I solve it?

**Comment by janmoppel** [comment]
Hello @Windymonkeys !

Thank you for posting an issue.
Can you please provide a bit more information, if you have it? What phone models and iOS versions were used?

**Comment by jmagman** [comment]
What is the output of `flutter doctor -v`?
This may be https://github.com/flutter/flutter/issues/45098.

**Comment by timsneath** [comment]
Unfortunately there isn't enough information on this bug to reproduce the issue. Closing for now. 

If you are still experiencing this issue, you're welcome to reopen it. Please tell us exactly how to reproduce the problem you're running into. Attach a small sample that demonstrates the issue, or include the specific tool commands that reproduce the problem along with the results of running `flutter doctor -v`. 

Thank you for using Flutter!
