### ISSUE TITLE
How do I know that the transition animation is finish when push a new page

### ISSUE THREAD

**Issue by huanxsd** [flutter/flutter#45972]
## Use case

When push a new page, I load the data in initState. This resulted in stuttering during the transition animation. This problem is particularly serious on Android.

## Proposal

In react native, I can use
```
InteractionManager.runAfterInteractions (() => {
           // ... do some time-consuming operations ...
});
```

Is there a similar method in flutter. Let me know that the transition animation is finish?

**Comment by janmoppel** [comment]
Hello @huanxsd !

Thank you for posting.
Your question seems to be a good fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) as well. Flutter has a very active and helpful community there, so feel free to post it there too.

Also, see other support options here: https://flutter.dev/community

**Comment by huanxsd** [comment]
Thank you for your advice
