### ISSUE TITLE
'flutter attach' does not work on iOS

### ISSUE THREAD

**Issue by xiubojin** [flutter/flutter#45975]
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#ios

Integrate flutter module is according to the document.

The computer connects to the mobile phone, by the following steps:
Step 1: Switch folder, run `flutter attach -d device`
Step 2: Terminal keeps showing 'Waiting for a connection from Flutter on the iphone...'
Step 3: Open Xcode, run native app and navigate to the flutter view

Native app is running, terminal does not have other output. Therefore, it is unable to use the hot reload.

My flutter version is v1.9.1+hotfix.6, and master channel.

**Comment by janmoppel** [comment]
Hello @xiubojin !

Thank you for posting an issue.
Can you please also attach the `flutter doctor -v` command output?

**Comment by jmagman** [comment]
Are you on iOS 13?  Looks related to https://github.com/flutter/flutter/issues/41085.  https://github.com/flutter/flutter/pull/44150 may have fixed this and is in 1.10.16, which is in the [dev and beta channels](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels).
Does this work for you on either dev or beta?

**Comment by xiubojin** [comment]
> Hello @xiubojin !
> 
> Thank you for posting an issue.
> Can you please also attach the `flutter doctor -v` command output?

Thanks for your reply, this is the output:
`
[✓] Flutter (Channel master, v1.12.15-pre.6, on Mac OS X 10.15 19A583, locale zh-Hans-CN)
    • Flutter version 1.12.15-pre.6 at /Users/jinxiubo/Documents/flutter
    • Framework revision 92b0ceaaa6 (8 days ago), 2019-11-26 01:19:51 -0500
    • Engine revision 05f8c8b24b
    • Dart version 2.7.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • Ipohne • fca63c875621305eb94dc2adbdeb1ca5e6625d65 • ios • iOS 12.0.1

! Doctor found issues in 2 categories.
`

**Comment by xiubojin** [comment]
> Are you on iOS 13? Looks related to #41085. #44150 may have fixed this and is in 1.10.16, which is in the [dev and beta channels](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels).
> Does this work for you on either dev or beta?

Question 1: on iOS 12.
Question 2: not work.
