### ISSUE TITLE
didChangeAppLifecycleState doesn't work as expected

### ISSUE THREAD

**Issue by tony123S** [flutter/flutter#45974]
I hope I understand how `didChangeAppLifecycleState` worked correctly.

I have page A and page B . When I click the back device button from page B ( `Navigator.of(context).pop();`), I expect `didChangeAppLifecycleState` in pageA will get called, but it doesn't.

**PageA**

```
class _ABCState extends State<ABCrList> with WidgetsBindingObserver {
@override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
            ....
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      setState(() {
        print(...);
      });
    }else{
      print(state.toString());
    }
  }

....
 
```

**Comment by anotherglitchinthematrix** [comment]
This method only called when your application is sent to background or returns to foreground, like when swapping between other applications. So it's working as expected, but unfortunately not as you expected.

If you need something like that, Navigator.of(context)'s push methods returns a `Future<T>` that you can await to be popped.
```dart
onPressed: () async {
  final navigation = Navigator.of(context).push(MaterialPageRoute(builder: (_) => PageB()));
  navigation.then((_) {
    print('Popped back');
  });
}
```

**Comment by tony123S** [comment]
@anotherglitchinthematrix thanks for your answer.

Unfortunately I hit other issue after using your answer. I have opened an issue here https://github.com/flutter/flutter/issues/45988
