### ISSUE TITLE
No Android Device / Emulator found -

### ISSUE THREAD

**Issue by roysantu2002** [flutter/flutter#45994]
## Steps to Reproduce

macOS Catalina: 10.15

export ANDROID_HOME=$HOME/Library/Android/sdk

export ANDROID_SDK_ROOT=$ANDROID_HOME

export PATH="$PATH:$HOME/developer/flutter/bin"

---------

ll SDK package licenses accepted.======] 100% Computing updates...   

----------------------------
```
/Users/santuroy/Library/Android/sdk
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A583, locale

    en-IN)

    • Flutter version 1.9.1+hotfix.6 at /Users/santuroy/developer/flutter

    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700

    • Engine revision b863200c37

    • Dart version 2.5.0



[!] Android toolchain - develop for Android devices

    ! Android SDK contains licenses only.

      Your first build of an Android application will take longer than usual,

      while gradle downloads the missing components. This functionality will

      only work if the licenses in the licenses folder in ANDROID_HOME are

      valid.

      If the Android SDK has been installed to another location, set

      ANDROID_HOME to that location.

      You may also want to add it to your PATH environment variable.



      Certain features, such as `flutter emulators` and `flutter devices`, will

      not work without the currently missing SDK components.



[✓] Xcode - develop for iOS and macOS (Xcode 11.1)

    • Xcode at /Applications/Xcode.app/Contents/Developer

    • Xcode 11.1, Build version 11A1027

    • CocoaPods version 1.8.4



[✓] Android Studio (version 3.5)

    • Android Studio at /Applications/Android Studio.app/Contents

    • Flutter plugin version 41.1.2

    • Dart plugin version 191.8593

    • Java version OpenJDK Runtime Environment (build

      1.8.0_202-release-1483-b49-5587405)



[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)

    • IntelliJ at /Applications/IntelliJ IDEA.app

    ✗ Flutter plugin not installed; this adds Flutter specific functionality.

    ✗ Dart plugin not installed; this adds Dart specific functionality.

    • For information about installing plugins, see

      https://flutter.dev/intellij-setup/#installing-the-plugins



[!] VS Code (version 1.39.2)

    • VS Code at /Applications/Visual Studio Code.app/Contents

    ✗ Flutter extension not installed; install from

      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter



[!] Connected device

    ! No devices available
```
## Logs

```
```

```
```

**Comment by janmoppel** [comment]
Hello @roysantu2002 !

Thank you for posting an issue.
Did you follow the official documentation to install Flutter? Have you done all the steps described here: https://flutter.dev/docs/get-started/install/macos#android-setup?

**Comment by roysantu2002** [comment]
Hi,
I tried every possible step without any luck yet to launch android devices on Mac Catalina. It was all working fine from my Kotlin project. But after installing flutter I only see IOS simulator from the Android studio, I can create AVD successfully but unable to launch because of the Android root directory issue even after setting the same on my .zshrc file - I need support.
This would be my dream project I started my journey with Kotlin and Swift, but I realized Flutter might be the best option - but unable to proceed because of the setup issue. 
Android SDK location looks alright.


export ANDROID_HOME=$HOME/Library/Android/sdk

export ANDROID_SDK_ROOT=$ANDROID_HOME

export PATH="$PATH:$HOME/developer/flutter/bin"

-------

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A583, locale

    en-IN)

    • Flutter version 1.9.1+hotfix.6 at /Users/santuroy/developer/flutter

    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700

    • Engine revision b863200c37

    • Dart version 2.5.0




[!] Android toolchain - develop for Android devices

    ! Android SDK contains licenses only.

      Your first build of an Android application will take longer than usual,

      while gradle downloads the missing components. This functionality will

      only work if the licenses in the licenses folder in ANDROID_HOME are

      valid.

      If the Android SDK has been installed to another location, set

      ANDROID_HOME to that location.

      You may also want to add it to your PATH environment variable.




      Certain features, such as `flutter emulators` and `flutter devices`, will

      not work without the currently missing SDK components.





    On Tuesday, December 3, 2019, 10:46:43 PM GMT+5:30, Jan Moppel <notifications@github.com> wrote:  
 
 
Hello @roysantu2002 !

Thank you for posting an issue.
Did you follow the official documentation to install Flutter? Have you done all the steps described here: https://flutter.dev/docs/get-started/install/macos#android-setup?

**Comment by iapicca** [comment]
Hi @roysantu2002 

from this part of your flutter doctor

```
[!] Android toolchain - develop for Android devices

    ! Android SDK contains licenses only.
      Your first build of an Android application will take longer than usual,
      while gradle downloads the missing components. This functionality will
      only work if the licenses in the licenses folder in ANDROID_HOME are
      valid.

      If the Android SDK has been installed to another location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

      Certain features, such as `flutter emulators` and `flutter devices`, will
      not work without the currently missing SDK components.
```
clearly there0's something on the default path of the `Android SDK`,
but seems to contains only the licenses, could you double-check that?

Thank you

**Comment by roysantu2002** [comment]
I reinstalled Android Studio, and still not able to see the setup completion. 
Flutter doctor : output

Doctor summary (to see all details, run flutter doctor -v):

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A583, locale

    en-IN)

[!] Android toolchain - develop for Android devices

    ! Android SDK contains licenses only.

      Your first build of an Android application will take longer than usual,

      while gradle downloads the missing components. This functionality will

      only work if the licenses in the licenses folder in ANDROID_HOME are

      valid.

      If the Android SDK has been installed to another location, set

      ANDROID_HOME to that location.

      You may also want to add it to your PATH environment variable.




      Certain features, such as `flutter emulators` and `flutter devices`, will

      not work without the currently missing SDK components.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)

[✓] Android Studio (version 3.5)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)

    ✗ Flutter plugin not installed; this adds Flutter specific functionality.

    ✗ Dart plugin not installed; this adds Dart specific functionality.

[!] VS Code (version 1.39.2)

    ✗ Flutter extension not installed; install from

      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device

    ! No devices available


    On Wednesday, December 4, 2019, 07:31:40 PM GMT+5:30, Francecsco Iapicca <notifications@github.com> wrote:  
 
 
Hi @roysantu2002

from this part of your flutter doctor
[!] Android toolchain - develop for Android devices

    ! Android SDK contains licenses only.
      Your first build of an Android application will take longer than usual,
      while gradle downloads the missing components. This functionality will
      only work if the licenses in the licenses folder in ANDROID_HOME are
      valid.

      If the Android SDK has been installed to another location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

      Certain features, such as `flutter emulators` and `flutter devices`, will
      not work without the currently missing SDK components.

clearly there0's something on the default path of the Android SDK,
but seems to contains only the licenses, could you double-check that?

Thank you

**Comment by roysantu2002** [comment]
Hello Team,
Issue resolved. I updated the Android SDK and that resolved the issue :)

    On Wednesday, December 4, 2019, 08:03:24 PM GMT+5:30, Santu Roy <roysantu2002@yahoo.com> wrote:  
 
  I reinstalled Android Studio, and still not able to see the setup completion. 
Flutter doctor : output

Doctor summary (to see all details, run flutter doctor -v):

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A583, locale

    en-IN)

[!] Android toolchain - develop for Android devices

    ! Android SDK contains licenses only.

      Your first build of an Android application will take longer than usual,

      while gradle downloads the missing components. This functionality will

      only work if the licenses in the licenses folder in ANDROID_HOME are

      valid.

      If the Android SDK has been installed to another location, set

      ANDROID_HOME to that location.

      You may also want to add it to your PATH environment variable.




      Certain features, such as `flutter emulators` and `flutter devices`, will

      not work without the currently missing SDK components.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)

[✓] Android Studio (version 3.5)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)

    ✗ Flutter plugin not installed; this adds Flutter specific functionality.

    ✗ Dart plugin not installed; this adds Dart specific functionality.

[!] VS Code (version 1.39.2)

    ✗ Flutter extension not installed; install from

      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device

    ! No devices available


    On Wednesday, December 4, 2019, 07:31:40 PM GMT+5:30, Francecsco Iapicca <notifications@github.com> wrote:  
 
 
Hi @roysantu2002

from this part of your flutter doctor
[!] Android toolchain - develop for Android devices

    ! Android SDK contains licenses only.
      Your first build of an Android application will take longer than usual,
      while gradle downloads the missing components. This functionality will
      only work if the licenses in the licenses folder in ANDROID_HOME are
      valid.

      If the Android SDK has been installed to another location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

      Certain features, such as `flutter emulators` and `flutter devices`, will
      not work without the currently missing SDK components.

clearly there0's something on the default path of the Android SDK,
but seems to contains only the licenses, could you double-check that?

Thank you

**Comment by iapicca** [comment]
Hi @roysantu2002 
I'm glad that you fixed the issue,
thank you for letting me know
