### ISSUE TITLE
App activity is over-transformed by ~1.25

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#45991]
https://b.corp.google.com/issues/144555069.

/cc @chinmaygarde who is looking at it.

**Comment by Hixie** [comment]
Took a guess as to the target milestone.

**Comment by chinmaygarde** [comment]
Fixed in https://github.com/flutter/engine/pull/14135. Due to urgency, this may also be applied directly in cl/283392448.

cc @nichtverstehen
