### ISSUE TITLE
Desktop/embedder shells need an affordance for enabling dart profiling

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#46005]
The switch [--enable-dart-profiling](https://github.com/flutter/engine/blob/096ba6892a435a9149b0406592eab7ba866bceb8/shell/common/switches.h#L86) is used to configure the dart vm to record profiles in the vmservice. Currently this option is off by default, but is forced on via the [launch intent](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L572) for Android/iOS devices. The desktop shells lack a similar affordance, and besides passing a string value through the FlutterViewController, currently have no way to enable profiling.

For example, in the macOS window code:

```switch
let arguments = [
   "--enable-dart-profiling"
]
let project = FlutterDartProject.init()
project.engineSwitches = arguments
return FlutterViewController.init(project: project)
```

We could enable profiling by default for debug and profile builds in the desktop shells in flutter/engine. This would require a way to detect the difference between "profile" AOT and "release" AOT. I'm not sure what happens if this flag is specified in a product build without a vmservice - maybe it is a no-op? I'm also not certain why it isn't enabled by default even for Android/iOS.

EDIT: This may need to also include `--trace-systrace` and `--trace-skia`

cc @chinmaygarde @stuartmorgan

**Comment by jonahwilliams** [comment]
@kenzieschmoll

**Comment by jonahwilliams** [comment]
After manually enabling tracing, it also looks like customer:octopod is still not able to see traces

**Comment by jonahwilliams** [comment]
Possibly related: https://github.com/flutter/devtools/pull/1490

**Comment by stuartmorgan** [comment]
I think this is a special case of https://github.com/flutter/flutter/issues/60393

**Comment by stuartmorgan** [comment]
> `project.engineSwitches = arguments`

This API will be removed in https://github.com/flutter/engine/pull/21468

In the immediate term https://github.com/flutter/flutter/issues/60393#issuecomment-696940505 can be used to pass it manually on each launch, but that can also be added to `flutter_tool`'s desktop `device` code as is currently done for [Android](https://github.com/flutter/flutter/blob/66b01c1f2905f6b4f845f7283abe3e458351fe2e/packages/flutter_tools/lib/src/android/android_device.dart#L635) and [iOS](https://github.com/flutter/flutter/blob/66b01c1f2905f6b4f845f7283abe3e458351fe2e/packages/flutter_tools/lib/src/ios/devices.dart#L361)

**Comment by stuartmorgan** [comment]
> We could enable profiling by default for debug and profile builds in the desktop shells in flutter/engine. [...] I'm also not certain why it isn't enabled by default even for Android/iOS.

I found https://github.com/flutter/flutter/pull/7159 while looking for where the tool currently does this for mobile, which sounds like the answer to this question.

**Comment by jonahwilliams** [comment]
Nice! The env variable handling should definitely be added to the tool device code so these flags start working. I can take a crack at adding the windows support later this week (once the engine rolls too) @stuartmorgan

**Comment by stuartmorgan** [comment]
> I can take a crack at adding the windows support later this week (once the engine rolls too) @stuartmorgan

Great! We should be able to add it to all three desktop platforms at the same time, with shared code, since the translation to environment variables will be the same for all three.

**Comment by jonahwilliams** [comment]
Ahh, awesome - I'll keep an eye on the rolls
