### ISSUE TITLE
Flutter upgrade displays welcome message on a no-op upgrade

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#46004]
I ran `flutter channel beta` and then `flutter upgrade` and I'm now getting the first-time run message every time I run `flutter upgrade`: 

See https://gist.github.com/timsneath/ba30865e808d9feb7ad5a448256697fb for example.

**Comment by tvolkert** [comment]
Fixed by #46011

**Comment by tvolkert** [comment]
This has been cherry-picked in `v1.12.13+hotfix.2`, so removing the release blocker label.

**Comment by timsneath** [comment]
Yay! Thanks...
