### ISSUE TITLE
Make `flutter analyse` print error suggesting `flutter analyze` (spelling)

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#46009]
For the benefit of our British friends.  Something like "unrecognized command, did you mean 'flutter analyze'"?

**Comment by jonahwilliams** [comment]
See https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#spell-words-in-identifiers-and-comments-correctly

Specifically:

> Prefer US English spellings. For example, 'colorize', not 'colourise', and 'canceled', not 'cancelled'.

We already have several violations of the rule, and many are noted in https://github.com/flutter/flutter/issues/24722. We should not add to the list, either though tool APIs or the flutter framework.

**Comment by gaaclarke** [comment]
I would argue this isn't a violation of our style guide.  This isn't affecting how the code or API is written.  It doesn't hurt anyone, just helps.  At the very least we could print out "did you mean `flutter analyze`?"

**Comment by gaaclarke** [comment]
On further thought, I think you are right.  We don't want to support it.  I think we should print out an error though that is helpful since I think this won't be uncommon.

**Comment by jonahwilliams** [comment]
A general purpose typo/spelling detection sounds like it would be a useful feature to have.

**Comment by cbracken** [comment]
As someone who has historically contributed a bunch of non-US spellings to the codebase (as well as fixed a heap) I'm all for something that hints at the expected command when I fail to misspell it for the tool.

That said, agreed that I'd prefer a general typo-catcher, not something with a hardcoded list of correctly-spelt terms and their flutter equivalents ;-)

**Comment by gaaclarke** [comment]
Any accommodation may have to edit [args/command_runner](https://github.com/dart-lang/args/blob/1f76fb383c15a877f55737637e91a2a405a8c238/lib/command_runner.dart#L164).
