### ISSUE TITLE
Explore using a packaged musl instead of linking against system glibc

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#46016]
This gets us closer to having hermetic builds. For context, `flutter_tester` built on non-LUCI setups, for ex: local linux workstations, tent to not be usable on LUCI nodes. They fail with:

```
Shell: /b/s/w/itCVnE10/flutter_fuchsia_tester.WPFPGT/bin/cache/artifacts/engine/linux-x64/flutter_tester: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /b/s/w/itCVnE10/flutter_fuchsia_tester.WPFPGT/bin/cache/artifacts/engine/linux-x64/flutter_tester)
Shell: /b/s/w/itCVnE10/flutter_fuchsia_tester.WPFPGT/bin/cache/artifacts/engine/linux-x64/flutter_tester: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /b/s/w/itCVnE10/flutter_fuchsia_tester.WPFPGT/bin/cache/artifacts/engine/linux-x64/flutter_tester)
```

cc: @chinmaygarde , @jason-simmons

**Comment by rhencke** [comment]
Is this a task I could help on?

**Comment by iskakaushik** [comment]
Yes, this task hasn't been claimed by anyone yet and I do not know anyone who is actively working on it. If this interests you, I would start looking at [buildroot](https://github.com/flutter/buildroot) for references where we link to glibc and then go from there.

**Comment by rhencke** [comment]
Thank you!  I am.. one of probably three people who uses a musl-based box as my daily driver, so.. this would open up some cool possibilities. :)  I'll take a look where you recommended.

**Comment by rzr** [comment]
Hi I am jumping in this thread, looking for hints 
Are you aware of any ongoing effort to port flutter-engine to musl ?

Relate-to: https://github.com/flutter/flutter/issues/52102

**Comment by jonahwilliams** [comment]
This is not something we're planning on doing.
