### ISSUE TITLE
NestedScrollView may scroll too much

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#46028]
In working on SliverFillRemaining, discovered that it may be providing too much space the inner scrollable of a NestedScrollView. In attempting to fix, found further that the test expect this behavior, but it does not seem right.

This is rooted in `SliverFillRemaining`, in the decision path when `hasScrollBody` is true.

This is the configuration of the NestedScrollView test:

```dart
Widget build(BuildContext context) {
    return Scaffold(
      body: DefaultTabController(
        length: 4,
        child: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return <Widget>[
              SliverAppBar(
                title: Text('Nested Scroll View Tests'),
                pinned: true,
                expandedHeight: 200.0,
                forceElevated: innerBoxIsScrolled,
                bottom: const TabBar(
                  tabs: <Tab>[
                    Tab(text: 'AA'),
                    Tab(text: 'BB'),
                    Tab(text: 'CC'),
                    Tab(text: 'DD'),
                  ],
                ),
              ),
            ];
          },
          body: TabBarView(
            children: <Widget>[
              ListView(
                children: <Widget>[
                  Container(
                    height: 300.0,
                    child: const Text('aaa1'),
                  ),
                  Container(
                    height: 200.0,
                    child: const Text('aaa2'),
                  ),
                  Container(
                    height: 100.0,
                    child: const Text('aaa3'),
                  ),
                  Container(
                    height: 50.0,
                    child: const Text('aaa4'),
                  ),
                ],
              ),
              ListView(
                children: <Widget>[
                  Container(
                    height: 100.0,
                    child: const Text('bbb1'),
                  ),
                ],
              ),
              Container(
                child: const Center(child: Text('ccc1')),
              ),
              ListView(
                children: <Widget>[
                  Container(
                    height: 10000.0,
                    child: const Text('ddd1'),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
```

If you scroll to the 'b' page, there is only one item in the list view, yet it scrolls off of screen. I don't know that this should be the behavior.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/16964204/70095569-f6beb000-15d9-11ea-8dde-3efa0646d342.gif)

What will need to be tested further in any possible change to existing tests is the behavior when scrolling up/down, while in the middle fo scrolling left/right.

**Comment by roscadalexandru** [comment]
Did any one found a way to fix this behaviour and stop the body scrolling under the app bar when its not needed?

**Comment by rayfarias56** [comment]
Very happy to see others running into this problem. Expected behavior I had was that if the content wasn't big enough to scroll the body wouldn't scroll at all. This is leading to weird behavior throughout my app. It's bearable, but is there idea on how to fix this?

**Comment by Piinks** [comment]
Hey @rayfarias56, I think what may be happening here is that this sample, and the other related ones I have found are not making use of the `SliverOverlapAbsorber/SliverOverlapInjector` widgets.

The _inner_ list view is scrolling under the _outer_ app bar because it does not know that it is overlapping the nested scrollable. The overlap aid widgets should be able to address this. I have not yet been able to try it though.

There is an example in the API docs [here](https://master-api.flutter.dev/flutter/widgets/NestedScrollView-class.html).

**Comment by healer2030** [comment]
@Piinks were you able to try using the `SliverOverlapAbsorber/SliverOverlapInjector` widgets?

**Comment by Piinks** [comment]
I was! Thanks for the ping! Here is a fresh example:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return <Widget>[
              SliverOverlapAbsorber(
                handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                sliver: SliverAppBar(
                  title: const Text('Demo'),
                  pinned: true,
                  expandedHeight: 150.0,
                  forceElevated: innerBoxIsScrolled,
                ),
              ),
            ];
          },
          body: CustomScrollView(
            slivers: <Widget>[
              SliverOverlapInjector(
                handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
              ),
              SliverToBoxAdapter(
                child: Container(
                  color: Colors.amber,
                  height: 100,
                )
              ),
            ],
          )
        ),
      )
    );
  }
}
```

Using the SliverOverlap* widgets results in the correct amount of space for the inner scrollable. I am going to close this issue. I did file #49560 to see about making these widgets more discoverable. :)

**Comment by healer2030** [comment]
The `child` parameter for `SliverOverlapAbsorber` was supposedly 'deprecated after v1.10.16.' However, the stable channel does not reflect those changes.
https://github.com/flutter/flutter/blob/stable/packages/flutter/lib/src/widgets/nested_scroll_view.dart#L1336

**Comment by healer2030** [comment]
Hey @Piinks , sorry to bother you. Could you try using the `SliverOverlapAbsorber/SliverOverlapInjector` widgets with the `DefaultTabController/TabView` widgets? 
I tried to do so, but got the following error: `NestedScrollView.sliverOverlapAbsorberHandleFor must be called with a context that contains a NestedScrollView.`

**Comment by Piinks** [comment]
> Could you try using the `SliverOverlapAbsorber/SliverOverlapInjector` widgets with the `DefaultTabController/TabView` widgets?
> I tried to do so, but got the following error: `NestedScrollView.sliverOverlapAbsorberHandleFor must be called with a context that contains a NestedScrollView.`

Sure! There is an example that uses a `DefaultTabController/TabView` and the `SliverOverlapAbsorber/SliverOverlapInjector` in the api documentation for `NestedScrollView`: https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html

**Comment by nioncode** [comment]
@Piinks I'm trying to use the `SliverOverlap` widgets to prevent the `SliverAppBar` from collapsing at all when the body is not big enough to require scrolling (as you suggested to do in #12033), but it seems like this has no effect and might not be the right tool for the task.

This example uses two routes, one showing the 'bad' behavior with `NestedScrollView`, the other showing the 'good' behavior with `CustomScrollView`. If the body of the `NestedScrollView` is not big enough to require scrolling, the `SliverAppBar` should not collapse at all. Is this possible to achieve with `NestedScrollView` or only with `CustomScrollView`?

![Peek 2020-04-10 10-23](https://user-images.githubusercontent.com/3159451/78976428-70c9ed00-7b16-11ea-9e82-3f2683a782a8.gif)

Sample code:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {
        '/nested': (_) => NestedScrollViewPage(),
        '/custom': (_) => CustomScrollViewPage(),
      },
      home: Scaffold(
        body: Builder(
          builder: (context) => Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                RaisedButton(
                  child: Text('NestedScollView'),
                  onPressed: () async {
                    await Navigator.of(context).pushNamed('/nested');
                  },
                ),
                RaisedButton(
                  child: Text('CustomScollView'),
                  onPressed: () async {
                    await Navigator.of(context).pushNamed('/custom');
                  },
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class NestedScrollViewPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: NestedScrollView(
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
          return <Widget>[
            SliverOverlapAbsorber(
              handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
              sliver: SliverAppBar(
                title: const Text('NestedScrollView'),
                expandedHeight: 300,
              ),
            ),
          ];
        },
        body: Builder(builder: (context) {
          return CustomScrollView(
            slivers: <Widget>[
              SliverOverlapInjector(
                handle:
                    NestedScrollView.sliverOverlapAbsorberHandleFor(context),
              ),
              SliverToBoxAdapter(
                  child: Container(
                color: Colors.amber,
                height: 100,
              )),
            ],
          );
        }),
      ),
    );
  }
}

class CustomScrollViewPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: <Widget>[
          SliverAppBar(
            title: const Text('CustomScrollView'),
            expandedHeight: 300,
          ),
          SliverToBoxAdapter(
              child: Container(
            color: Colors.amber,
            height: 100,
          )),
        ],
      ),
    );
  }
}
```
