### ISSUE TITLE
[web][chrome/firefox] Using Clipboard API in Flutter for Web 

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#46020]
support is added for clipboard for editable text fields in Flutter for web. On the other hand the support for clipboard service is still not implemented in [Flutter for Web](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/clipboard.dart)

This is mostly because of missing browser support web APIs: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

I am adding this issue for adding support in chrome/firefox.

**Comment by SeanOThomas** [comment]
Hello! Anyone aware of a workaround? Thanks!

**Comment by nturgut** [comment]
Hi, I'll merge the fix soon. In a few days you can sync the master branch.

If copy paste for a text area is enough, for text editing, we are using a native input field so context menu works out of the box.

**Comment by nturgut** [comment]
I'll add another PR soon for copy (Clipboard.setData) functionality for browsers not covered by this change.

**Comment by SeanOThomas** [comment]
Sorry, what widget works? I'm using a Clipboard.setData on a Text widget using Flutter 1.13.8, and it's not copying.

**Comment by nturgut** [comment]
Hi Sean, which browser are you using. The [fix](https://github.com/flutter/engine/pull/15455) is in the master channel in Flutter now. (Please make sure latest engine roll [commit](https://github.com/flutter/flutter/commit/ab36346af6e6c61ab4174c753b1ec3f3260fa56a) is fetched to your local repository.

 With this fix, setData should work in Firefox and Chrome.
