### ISSUE TITLE
Overscroll glow should fade away the moment scrolling in the opposite direction starts

### ISSUE THREAD

**Issue by aghassemi** [flutter/flutter#4603]
Currently overscroll glow sticks to the finger in both directions, native Android releases the glow immediately if scrolling starts in the opposite direction.
This also has the side effect of scrolling in the opposite direction not actually starting until the glow is gone first.

**Comment by aghassemi** [comment]
Partially fixed by 94c4222f2bd59d91554062953ea899b64629a02c . Glow now fades away when scrolling in reverse starts. Content however still does not scroll in reverse util glow is gone. That part of the bug is related to the underlying "bound overscroll" that happens but is clamped to be invisible.

**Comment by abarth** [comment]
Done.
