### ISSUE TITLE
There are several ways Flutter can check for memory leaks?

### ISSUE THREAD

**Issue by Aaron009** [flutter/flutter#46050]
There are several ways Flutter can check for memory leaks?

I wrote a memory leak code.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MainApp());
}

class MainApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: TextMemoryLeak(),
    );
  }
}

class TextMemoryLeak extends StatefulWidget {
  @override
  _TextMemoryLeakState createState() => _TextMemoryLeakState();
}

class _TextMemoryLeakState extends State<TextMemoryLeak> {
  List memoryList = [];

  @override
  Widget build(BuildContext context) {
    Scaffold scaffold = Scaffold(
      appBar: AppBar(
        title: Text('test memory leaks'),
      ),
      body: Center(
        child: Text('${memoryList.length + 1}'),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.map),
        onPressed: () {
          setState(() {

          });
        },
      ),
    );

    for (var i = 0; i < 100; ++i) {
      memoryList.add(scaffold); // A memory leak has occurred
      memoryList.add('A' * 1000);
    }
    return scaffold;
  }
}
```

This is a very simple code.

Every time you click on the `floatingButton`, it will be continuously added to the` memoryList` without being removed. This is an obvious memory leak.

I once read an article about Flutter checking for memory leaks.
The principle is that the larger the memory size requested by a function, the greater the possibility of a memory leak. (I forgot where I saw it. If anyone knows, please tell me the address of this article.)
I don't like this method because the memory requested by a function is very small, but it is a memory leak and it is difficult to check.

Another way is to use weakly referenced.

The principle is this.

```javascript
var memoryList = [];
memoryList.add('111111');

var weakMap = new WeakMap()
weakMap.set(memoryList, true);

forceGC();
// According to the principle, after executing gc, 
// if the memoryList key does not exist in the 
// `WeakMap`, 
// it means that the memoryList has recovered memory normally.
```

This troubleshooting method is very enjoyable. When I create an object, I make a weak reference to it to store it. When I destroy and force the use of GC, we can check the memory leaked objects through `WeakMap`.

####  In addition to the above two methods, is there a better way for Flutter to check for memory leaks?

I used to develop a game in which a colleague wrote a piece of code with a memory leak and then left. It was too painful when I investigated later.

**Comment by iapicca** [comment]
Hi @Aaron009 
dart hasn't a `weak reference`, please check these questions [[1](https://stackoverflow.com/questions/49831543/does-dart-flutter-have-the-concept-of-weak-references), [2](https://stackoverflow.com/questions/13358018/what-is-the-dart-expando-feature-about-what-does-it-do?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)] on stackoverflow,
you might want to look into the [Expando](https://api.dartlang.org/stable/1.24.3/dart-core/Expando-class.html) class.
In general you may want to use [devtools](https://flutter.dev/docs/development/tools/devtools/memory) to find memory leaks.

Does this answer your questions?
thank you

**Comment by Aaron009** [comment]
I'm happy and sad.
**Expando** contains **weak references**, but it cannot be traversed, and it is not possible to know which keys it has by breaking points.

![1](https://user-images.githubusercontent.com/3838050/70198616-491ede80-174a-11ea-92ea-57093f2eab79.png)

Regarding tools, I can't think of a good way to check for memory leaks. I think it is very effective for developers to check if the instantiated object is recycled normally through a similar weak reference.

**Comment by Aaron009** [comment]
@iapicca 
I don't want to do tool checking because I haven't used very effective tools to check for memory leaks so far. I am a developer and have used many analysis tools, but it didn't help much.

I hope to have such a function.

In debug mode, an object is instantiated and then marked as recyclable by code. After GC was enforced, it was found that the object could not be recycled at this time, and an error or prompt was given.

**Comment by cbracken** [comment]
Hi @Aaron009, sounds like what you're looking for is a means of extracting a memory profile of Dart memory that's been allocated by your application. By connecting to the Observatory URL dumped to the command line when running an app in debug or profile mode, you can collect an [allocation profile](https://dart-lang.github.io/observatory/allocation-profile.html). Note that debug memory usage is vastly different to release and profile builds, so you'll definitely want to do this with a profile mode build.

The Flutter plugins for Android Studio and IntelliJ should provide similar mechanisms but I'll admit I'm not super familiar with the latest there. 

Since I don't thinks there's any actionable code changes I'll close this bug, but if there are specific feature or documentation requests you can think of, please let us know.

**Comment by sathishmscict** [comment]
Follow this link to get exact memory leak details : 
https://stackoverflow.com/questions/57674085/how-to-find-memory-leaks-in-flutter/62471179#62471179

**Comment by Aaron009** [comment]
@cbracken 
I recently opened a memory leak detection tool, the principle:

By using the reference as the key of the weak reference, when the GC is executed, if the reference can be recycled, it will be deleted from the weak reference.

But when I developed these tools, weird problems appeared:
![image](https://user-images.githubusercontent.com/3838050/120875313-d102d480-c5dd-11eb-8a10-20e0d9f36390.png)

Can you help me see it?

Source code：
https://github.com/Waytoon/flutter_memory_leak_check

issue address：
https://github.com/flutter/flutter/issues/83978

**Comment by jmagman** [comment]
@Aaron009 Can you file a new issue and completely fill out the template so the right team can take a look?

**Comment by Aaron009** [comment]
@jmagman 
I have submitted it,
https://github.com/flutter/flutter/issues/83978
