### ISSUE TITLE
[add-to-app] SafeArea doesn't work when background mode is transparent

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#46060]
I am adding flutter to Android with the guide https://github.com/flutter/flutter/wiki/Experimental:-Add-Flutter-Activity;

```
FlutterActivity.CachedEngineIntentBuilder builder = FlutterActivity.withCachedEngine(engName);
// builder.backgroundMode(FlutterActivityLaunchConfigs.BackgroundMode.transparent);  //1
// builder.backgroundMode(FlutterActivityLaunchConfigs.BackgroundMode.opaque);  //2
Intent intent = builder.build(activity.getApplicationContext());
activity.startActivity(intent);
```
but I found that when start the activity with  
```
builder.backgroundMode(FlutterActivityLaunchConfigs.BackgroundMode.transparent);  
```
then `SafeArea `not work anymore; 
in fact, if I comment this line, then there is always `SafeArea`;

by the way:
FlutterActivityLaunchConfigs is not public, I have to make my code belong to  package io.flutter.embedding.android;

```
[✓] Flutter (Channel beta, v1.12.13+hotfix.1, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.1 at /opt/google/flutter
    • Framework revision 5b07015393 (24 hours ago), 2019-12-03 00:12:02 -0800
    • Engine revision c1e322b685
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /opt/google/android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /opt/google/android/sdk
    • ANDROID_SDK_ROOT = /opt/google/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
```

**Comment by iapicca** [comment]
Hi @wanjm 
could you please provide a minimal code sample to reproduce the problem?
Thank you

**Comment by wanjm** [comment]
1. create one empty directory and enter in;
2. flutter create -t module --org cn.plaso -a java  flutter_module
3. use Androd Studio to create one App with basic Activity in the same dir; one app with a float button;
4. build flutter_module with  flutter build aar
5. modify build.gradle and MainActivity.xml as the guide tells;
6. set up new FlutterHelper.
```
package io.flutter.embedding.android;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;

import java.util.HashMap;

import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.android.FlutterActivityLaunchConfigs;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.FlutterEngineCache;
import io.flutter.embedding.engine.dart.DartExecutor;
import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel;

public class FlutterHelper {
    private static  FlutterHelper instance=new FlutterHelper();
    private static final String CHANNEL = "plaso_inner_module";
    private MethodChannel channel;
    private Context context;
    final String engName="my_engine_id";
    private FlutterHelper(){}
    public static FlutterHelper getInstance(){
        return instance;
    }
    public void init( Context context ){
        this.context=context;
        FlutterEngine flutterEngine = new FlutterEngine(context);

        channel=new MethodChannel(flutterEngine.getDartExecutor(), CHANNEL);
        flutterEngine
                .getDartExecutor()
                .executeDartEntrypoint(
                        DartExecutor.DartEntrypoint.createDefault()
                );
        FlutterEngineCache
                .getInstance()
                .put(engName,flutterEngine);
    }
    public void startActivity(Activity activity){
        FlutterActivity.CachedEngineIntentBuilder builder = FlutterActivity.withCachedEngine(engName);
        builder.backgroundMode(FlutterActivityLaunchConfigs.BackgroundMode.transparent);
        // builder.backgroundMode(FlutterActivityLaunchConfigs.BackgroundMode.opaque);
        Intent intent = builder.build(activity.getApplicationContext());
        activity.startActivity(intent);
    }
}
```
7. modify MainActivity.java in onCreate;
```
    FlutterHelper.getInstance().init(getApplicationContext());
    fab.setOnClickListener(new View.OnClickListener() {
      @Override
      public void onClick(View view) {
        FlutterHelper.getInstance().startActivity(MainActivity.this);
      }
    });
```

8. then you will find and the flutter  page is SafeAreaed or not is controlled by 
```
builder.backgroundMode(FlutterActivityLaunchConfigs.BackgroundMode.transparent);
```

instead of by SafeArea in dart code;

**Comment by wanjm** [comment]
by the way,  when click , there will black screen before flutter page shown; 
I fact, I am work for this problem and found SafeArea problem; 
if you have any information on how to stop it from shine, it will be thankful;

**Comment by xster** [comment]
cc @matthew-carroll for thoughts

**Comment by xster** [comment]
Removing the regression tag since I don't think the old embedding had transparency support.

**Comment by matthew-carroll** [comment]
I have verified that `SafeArea` does not respect the status bar when used with a transparent `FlutterActivity`.

The problem **isn't** caused by the XML style:

```
<item name="android:windowIsTranslucent">true</item>
```

The problem **is** caused by some effect of configuring the background mode of a `FlutterActivity`:

```
startActivity(
            FlutterActivity
                .withNewEngine()
                // The next line is the problem.
                .backgroundMode(FlutterActivityLaunchConfigs.BackgroundMode.transparent)
                .build(MainActivity.this)
        );
```

Setting the background mode does a couple things. First, it uses a `FlutterTextureView` instead of a `FlutterSurfaceView`, which internally uses a `TextureView` instead of a `SurfaceView`, and second, it enables transparency on that `TextureView`.

I haven't found the root cause yet, but I'm still looking.

**Comment by matthew-carroll** [comment]
Further investigation: When the transparency mode of `FlutterView` is set to `BackgroundMode.transparent`, the Android method `onApplyWindowInsets()` changes from reporting a top padding of `63` to a top padding of `0`. This is the technical source of the issue. But what's still unclear is the root cause of the changing insets. I haven't been able to locate any meaningful difference in code path for the transparent case vs the opaque case.

**Comment by matthew-carroll** [comment]
The root cause is the flags that are set within `FlutterActivity` in the following code:

```
private void configureWindowForTransparency() {
    BackgroundMode backgroundMode = getBackgroundMode();
    if (backgroundMode == BackgroundMode.transparent) {
      getWindow().setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));
      getWindow().setFlags(
        WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,
        WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS
      );
    }
  }
```

It looks like I added this logic when building splash screen support. I'm not sure why I did that. I'll continue to investigate this flag logic tomorrow, but if I can't find a purpose for these flags then I'll remove them and the issue will be resolved.

**Comment by matthew-carroll** [comment]
I'm not seeing any visual regression in splash screen behavior, so I'm going to remove these flags from the Android embedding.

**Comment by matthew-carroll** [comment]
FYI @xster @dnfield a number of those low level embedding logs helped to debug this issue. I wanted to point that out as an example where they come in handy.

**Comment by matthew-carroll** [comment]
Fixed here: https://github.com/flutter/engine/pull/16208

**Comment by krmao** [comment]
```
{
  "flutterSdkVersion": "1.22.4"
}
```

still not work

**Comment by iapicca** [comment]
@krmao 
this issue is closed from 11 months and it is not actively worked on
can you open a new issue providing a **_minimal reproducible code sample_** and your `flutter doctor -v`

**Comment by krmao** [comment]
@iapicca may be it's [FlutterBoost](https://github.com/alibaba/flutter_boost/issues/950) bug, not yours, thanks for the reply!

**Comment by iapicca** [comment]
> @iapicca may be it's [FlutterBoost](https://github.com/alibaba/flutter_boost/issues/950) bug, not yours, thanks for the reply!

it make sense, `flutter_boost` uses a [very old version of flutter](https://github.com/alibaba/flutter_boost#release-note)
which probably does not contain the [fix](https://github.com/flutter/flutter/issues/46060#issuecomment-583651813) for this bug
