### ISSUE TITLE
Add search bar to CupertinoNavigationBar and CupertinoSliverNavigationBar, please =)

### ISSUE THREAD

**Issue by Renesanse** [flutter/flutter#46074]
![photo_2019-12-04_15-49-09](https://user-images.githubusercontent.com/42138594/70143823-a0bb3c80-16ad-11ea-9541-1aa27dce95e8.jpg)

**Comment by xster** [comment]
Merging into #18103

I'm also assuming you meant CupertinoSliverNavigationBar only. The static CupertinoNavigationBar equivalent on iOS (non-large title nav bar) can't have a search bar inside.
