### ISSUE TITLE
Overscroll glow's growth is linear and stops too early

### ISSUE THREAD

**Issue by aghassemi** [flutter/flutter#4607]
Native glow's growth is curved. Very quick at the beginning of the swipe then slows down almost exponentially but I don't think it ever really stops growing.

**Comment by b-strauss** [comment]
I just noticed this and nearly created a new issue. :)

The Flutter glow does indeed seem to be "static". It doesn't grow. The native circle grows in size. At the end of the animation it's nearly a straight line. It also adapts to screen width.

Native | Flutter
:-:|:-:
![](http://tinyimg.io/i/1RVf9Ly.gif)  |  ![](http://tinyimg.io/i/xwh1CFG.gif)
![](http://tinyimg.io/i/7X3eSog.gif)  |  ![](http://tinyimg.io/i/gbHyG01.gif)

**Comment by abarth** [comment]
Fixed.
