### ISSUE TITLE
Provide the means for custom embedders to refresh /etc/localtime

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#46084]
https://b.corp.google.com/issues/145541732.

**Comment by kf6gpe** [comment]
cc @chinmaygarde @cbracken

**Comment by chinmaygarde** [comment]
The proposed fix was rejected after the discussion in https://github.com/flutter/engine/pull/14518#pullrequestreview-332975057.

**Comment by mehmetf** [comment]
Internal bug 145541732 has been closed.
