### ISSUE TITLE
Possible regression in complex_layout_win__compile_debug_full_compile_millis

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#46085]
First seen in https://github.com/flutter/flutter/pull/45720.

**Comment by Piinks** [comment]
The first and all following changes that regressed here are all documentations changes and refactoring for implicit-casts. 

- https://github.com/flutter/flutter/commit/3ea8c87ce92ab20718667a229861548925b3f30b
- https://github.com/flutter/flutter/commit/4956bcc2f9a1928b8562b0dda9263fb3322c0913
- https://github.com/flutter/flutter/commit/a5f9b3b036db83b864e336149d1f40b2921a5eab

I am not sure how these types of changes could have caused this. Could this be another bot issue? cc/ @godofredoc

**Comment by Piinks** [comment]
This appears to have returned to expected values after more commits landed. I am removing the today label and leaving this open to see if it jumps again.

**Comment by godofredoc** [comment]
Seems like rebooting the windows machines helped. This is probably related to gradle not releasing files and using a lot of memory and cpu.

I'll keep this open to get more details next time this happens.

**Comment by jonahwilliams** [comment]
Is this problem still occurring?

**Comment by godofredoc** [comment]
I don't see this metric anymore was it removed?

**Comment by digiter** [comment]
Triage: looks passing at the moment.
