### ISSUE TITLE
Provide a compilation option to remove print() at Release build

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#46088]
I don't want to have any logs printed on the Release version of my App, but even if I don't use `print()` in my code, an external library such as `firebase_crashlytics` can have a `print()` statement dumping my crash logs on the final user's device.

There should be a compilation flag to remove `print` statements if we want to and preferably also be able to override `print` in the same way that we can override `debugPrint`. 

PS: I understand that this would be a collaborative work between the Flutter Team and the Dart Team, as overriding `print` involves the Dart Team, as `print` isn't a Flutter Framework function, but at the same time adding a compilation flag in the `flutter` tool would be a task for the Flutter Team, so I am not 100% sure where's the correct place to open this issue.

**Comment by dnfield** [comment]
I have some doubt about this.

`print()` is really the only way to debug Dart code in release mode.  If you find a bug in your release app that you want to use print to resolve, you'll need to re-enable prints.  If your logs are getting spammed by lots of other useless prints, you're still in a bad place.

It would probably be better to open an issue in FirebaseExtended/flutterfire about that specific issue.

/cc @collinjackson @kroikie

**Comment by jonahwilliams** [comment]
We're not going to support compiling out print methods in the tooling. If you want to intercept or redirect print output, you can wrap your application in a [runZoned](https://api.dartlang.org/stable/2.6.1/dart-async/runZoned.html) call with an overriden print handler on the [ZoneSpecification](https://api.dartlang.org/stable/2.6.1/dart-async/ZoneSpecification-class.html)

**Comment by collinjackson** [comment]
@feinstein The approach that @jonahwilliams recommended should work well, but if not feel free to open an issue against firebase_crashlytics for configuring logging.

**Comment by feinstein** [comment]
@dnfield lots of libraries embed `print` calls into their code, not just the Firebase ones, in Java this is simple to resolve as SLF4 is the defacto standard for libraries, so the client code can always redirect the logger output.

I don't agree that removing `print` is a big issue for debugging release apps. If you are going to use `print` outputs for debugging release apps, then you would have to have physical access to the device anyway, so it would be easier for you to re-enable `print` or reinstall the app in debug mode. The user across the planet from me with a device printing is just wasting memory or giving hackers a peek on the inner workings of my code.

**Comment by feinstein** [comment]
@collinjackson I already did: https://github.com/FirebaseExtended/flutterfire/issues/1550

I already implemented the `runZoned` solution, after I opened this issue, it just feels a bit cumbersome (first time I found it was in the firebase_crashlytics example, which should be better documented btw) something s SLF4J in Dart would be very welcome, as IMHO it's more powerful.

**Comment by vannevar-morgan** [comment]
I wrote a script to easily toggle prints and logs to enabled / disabled for release builds, it's available here:
https://github.com/vannevar-morgan/utils/blob/master/loggle.py

I know this is not exactly what OP was asking for as it doesn't disable prints in external libraries.  If all you want to do is disable prints and logs in your own source files, try out the script it should make it really easy to toggle them on / off.

**Comment by netgfx** [comment]
I would too advocate that an option to remove print on release is the right path to take. Security wise it is very important, the solutions provided above seem counter-intuitive and bloat up the codebase for no reason.
