### ISSUE TITLE
flutter create --macos app_name finsih with error "Could not find an option named "macos"."

### ISSUE THREAD

**Issue by Maksimka101** [flutter/flutter#46093]
## Steps to Reproduce

1. flutter channel master
2. flutter upgrade
3. flutter create --macos app_name

## Logs

```
Could not find an option named "macos".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and
options.
```

flutter clean and reinstallation didn't help.

I slove this problem by downgrading flutter to v1.12.10.
```
flutter version v1.12.10
```

**Comment by stuartmorgan** [comment]
That option was removed yesterday, so you no longer need to pass it. Once the discussion in the PR above is resolved, I'll update documentation accordingly (unless the change is reverted).

**Comment by stuartmorgan** [comment]
flutter.dev/desktop and the FDE repo example app README have been updated to remove `--macos` from the instructions.
