### ISSUE TITLE
[dashboard] track IPA code size

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#4609]
As of https://github.com/flutter/dashboard_box/pull/93 we track APK. We should also track IPA size.

**Comment by eseidelGoogle** [comment]
My understanding is that an ipa is just a zipped .app + itunes artwork.  So I think what we actually want to track is zipped .app size.  Another consideration is that on iOS we may need to thin the .app first before tracking and only want to track arm64 sizes, not the x64/simulator binaries.  When we add support for arm7 (32-bit) devices, we'll want to track those too: https://github.com/flutter/flutter/issues/2089

**Comment by yjbanov** [comment]
@eseidelGoogle These are good considerations to keep in mind. I think once we start measure anything at all, we'll improve incrementally over time, just like we did with other benchmarks (started with frame build perf in `--debug` mode and over time added `--profile`, startup and transitions, getting to a fairly complete picture).

**Comment by yjbanov** [comment]
We do. Closing.
