### ISSUE TITLE
Rationalise how tool uses stderr.writeln/print/logging

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#461]
The main advantage of the logging mechanism is that it easily hooks into -v / --very-verbose to enable higher levels of logging. Once we have that, I think it makes sense to use the logging infrastructure for all messages just for code consistency, just have fatal errors go to a level that we always print out.

So I think we should go the following route in the tools:
- never use print
- never use stderr.writeln/stdout.writeln
- do all logging using the logging infrastructure
- have four levels of logging:
  - fatal errors, which are always output on stderr
  - normal messages (primarily warnings or high-important priority messages like "No analyzer warnings"), which are always output on stdout (maybe we can have a -q option to quiet them)
  - information that's output to stdout if you enable -v mode
  - verbose information that's output to stdout if you enable --very-verbose mode

**Comment by abarth** [comment]
@devoncarew might have done this already.

**Comment by devoncarew** [comment]
Yeah, this has been done. The current system is:
- `printError()` for any error that should be displayed to the user. In the CLI tool, this will go out on stderr.
- `printStatus()` for any normal message to the user. Things like `I'm analyzing...` or `3 devices available.`.
- `printTrace()` for any logging / trace info that should be displayed when the tool is run in verbose mode.
