### ISSUE TITLE
[web] Using `white-space: pre` isn't enough to prevent text from wrapping

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#46105]
In our text measurement stack, we use `white-space: pre` to prevent text from soft-wrapping. This is used for example to figure out the maximum intrinsic width.

The problem is that the text will still soft-wrap at the width of the window. In order to avoid this, we would need to set a very high width on the measurement element so it doesn't get affected by the width of the window.

Thanks @yjbanov for discovering this!

**Comment by yjbanov** [comment]
Not sure how useful it is, but I found the original code from Aug 2018 that attempts to deal with this (cl/208087676):

```dart
    _singleLineParagraphElement.style
      ..whiteSpace = 'nowrap' // force single-line (even if wider than screen)
      ..display = 'inline'; // allow the paragraph to be smaller than 100%
```

**Comment by mdebbar** [comment]
I had to remove that a while ago. You are right, `nowrap` does force single-line, but the problem is that it collapses whitespace.
![image](https://user-images.githubusercontent.com/1278212/70207286-2efbe680-16df-11ea-8944-a7f3be0192dd.png)
Source: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#Values

**Comment by pedromassangocode** [comment]
Is this still a valid issue today? Not sure how to verify if this was already fixed.

**Comment by mdebbar** [comment]
We don't use DOM elements to measure the width of text anymore. Closing as this issue isn't valid.
