### ISSUE TITLE
"flutter build aar" should take in a build number to allow version numbers other than 1.0

### ISSUE THREAD

**Issue by seanfreiburg** [flutter/flutter#46108]
## Use case

We are building flutter aars to publish to Maven to be consumed by our android application and `flutter build aar` only allows us to output it as a "1.0" version, you can confirm this by looking at the tests. 

## Proposal

BuildAarCommand should use usesBuildNumberOption() to take in a build number and use it to output to aar versions.

**Comment by jmagman** [comment]
@blasten

**Comment by blasten** [comment]
@sahandevs That makes sense.

**Comment by blasten** [comment]
@sahandevs That makes sense. Would you be willing to implement this feature? It seems pretty straightforward.

**Comment by seanfreiburg** [comment]
here is a draft PR, but i can't get it working, but I think its in the right direction https://github.com/flutter/flutter/pull/46117

**Comment by blasten** [comment]
You can pass a `-Pbuild-number` flag to Gradle here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/gradle.dart#L516. Then, read the value here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/aar_init_script.gradle#L30.  Similar to the `-Pis-plugin` flag.

**Comment by seanfreiburg** [comment]
added a PR here https://github.com/flutter/flutter/pull/46139

**Comment by xster** [comment]
Can we close this now @blasten?

**Comment by blasten** [comment]
yup
