### ISSUE TITLE
Implementing web plugin support for existing packages

### ISSUE THREAD

**Issue by bitsydarel** [flutter/flutter#46104]
## Use case
I would like to add support for web in my native plugin package without releasing a separate package.

I have seen package like http and other, use file stub and conditional if statement to support all the platform without releasing different package for web.

But for some reason the flutter team is releasing different package only for web. Is there a reason for that ?

**Comment by stuartmorgan** [comment]
[This document](https://docs.google.com/document/d/1LD7QjmzJZLCopUrFAAE98wOUQpjmguyGTN2wd_89Srs/edit?usp=drivesdk) explains the motivation for plugin federation. To ensure that it works well, the Flutter team is using it when adding new platforms to plugins.

There is no requirement to federate a plugin, or how much to do so. Division of platforms between packages, if any, is up to you.

**Comment by bitsydarel** [comment]
Is there any issue to track the discussion @stuartmorgan  ? Or is that internal ?

**Comment by stuartmorgan** [comment]
I'm not sure what discussion you're referring to, but there's a significant amount of discussion in the comments on that document.
