### ISSUE TITLE
SnackBar padding not customizable

### ISSUE THREAD

**Issue by dccruzt** [flutter/flutter#46112]
## Use case

I am using the `showSnackBar()` method from `Scaffold` class to perform a custom Toast. The layout of our widget is very similar with the default snackbar proposed by Material, with different colors, font, alignments, and also a custom margin (space outside our widget). It has to be same on left, right and bottom.

In order to have the expected result, we implement the `behavior` property, sending `SnackBarBehavior.floating` instead of `SnackBarBehavior.fixed`. Automatically we have a space outside the snackbar, the problem is that this space doesn't attend our needs and it is not customizable.

## Proposal

We think that we could have a third behavior, something like `SnackBarBehavior.custom`. With this behavior, we don't have nor internals nether externals paddings, the widget inside the `content` property would be the responsible for this definitions.

## Screenshots

This is what I got using floating behavior

![snap](https://user-images.githubusercontent.com/14850905/70181929-9dca4700-16c1-11ea-9074-b52488e05791.png)

This is what I'd like to have

<img width="817" alt="snap_figma" src="https://user-images.githubusercontent.com/14850905/70182188-1cbf7f80-16c2-11ea-8d49-c44bf16d6f3b.png">

**Comment by feinstein** [comment]
I believe this change should be easy, looking quickly at the `Snackbar`'s code I can see references to `snackBarPadding` which seems to be the inner hardcoded padding, and also for the external padding:

```dart
    if (isFloatingSnackBar) {
      snackBar = Padding(
        padding: const EdgeInsets.fromLTRB(15.0, 5.0, 15.0, 10.0),
        child: snackBar,
      );
    }
```

So it should be a matter to expose those 2 for customization on the constructor.

@HansMuller could I move forward and send a PR for this?

**Comment by dccruzt** [comment]
Yes, @feinstein 
It would be nice having these 2 paddings (internal and external) on constructor.
Thanks!

**Comment by feinstein** [comment]
I will call them margin and padding, but only if I get approval from @HansMuller.

**Comment by dccruzt** [comment]
Make sense
Thanks @feinstein !
@HansMuller could @feinstein go ahead?

**Comment by HansMuller** [comment]
Adding a (floating) SnackBar padding parameter seems like a reasonable thing to do. It looks like what @dccruzt wanted was `SnackBarBehavior.floating` with elevation = 0 and a custom padding value. If so, that really is a simple change; SGTM.

**Comment by dccruzt** [comment]
Yes @feinstein and @HansMuller 
I need a customizable margin and padding for snackbar, the solution proposed by @feinstein sounds good. You can go ahead 👍

**Comment by feinstein** [comment]
@HansMuller should I pass the `padding` values to the `SnackBar`'s contructor and it will be ignored for all other behavior values but `SnackBarBehavior.floating`?
