### ISSUE TITLE
video_player_platform_interface is missing documentation

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#46119]
As part of removing all of our analysis_options.yaml for the plugins we need to document all of the public members in `video_player_platform_interface`. See flutter/flutter#45440 for the meta issue on all of these analysis rules.

The missing classes here are:

- DataSource and its members
- VideoEvent and its members
- VideoEventType and all of its values

/cc @cbenhagen do you mind taking this one? It looks like you created the undocumented public members, so I think you'd probably have the best shot at describing these correctly. I took a look but it wasn't obvious to me what the new classes were supposed to be.

**Comment by mklim** [comment]
Also /cc @hterkelsen who landed the PR.

**Comment by cbenhagen** [comment]
Opened https://github.com/flutter/plugins/pull/2355. I am really unsure how to document the constructors of `DataSource`  and  `VideoEvent`. Just saying  they are constructing an instance feels quite useless. But I don't know much more to say about them. Good examples or ideas are very welcome.

**Comment by mklim** [comment]
Thanks again for fixing this @cbenhagen!
