### ISSUE TITLE
[cocoon] check-waiting-pull-requests sometimes thinks there are changes requested when there are not

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#46131]
See for example: 

https://github.com/flutter/flutter/pull/44474#issuecomment-561884176

https://github.com/flutter/flutter/pull/45977#issuecomment-561371949

It looks like if someone ever leaves a review other than approve at any point this might be triggering.

**Comment by godofredoc** [comment]
\cc @CaseyHillers taking too long for the bot to land changes may be related to this

**Comment by godofredoc** [comment]
obsolete. The bot is being replaced with the auto-submit app
