### ISSUE TITLE
Firebase test lab flakes

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#46132]
I've noticed some test failures that appear to be failures just in Firebase test lab. Opening this issue to track them.

- https://cirrus-ci.com/task/6441754747731968 was green, but the previous run https://cirrus-ci.com/task/5150692007739392 failed because the battery tests failed in [firebase](https://console.firebase.google.com/project/flutter-infra/testlab/histories/bh.74572d68fa0aa09d/matrices/7788266337740051626).
- The [new run](https://cirrus-ci.com/task/5047003200880640) is still in progress, but I think the red failure https://cirrus-ci.com/task/4722884810899456 in [firebase](https://console.firebase.google.com/project/flutter-infra/testlab/histories/bh.787fd1c13dcd8def/matrices/6122414830420734904) also looks like a flake.
- From the same PR there's also https://cirrus-ci.com/task/5285834764320768, pointing to https://firebase.corp.google.com/u/0/project/flutter-infra/testlab/histories/bh.fd85a82ead1f4de/matrices/6434497023973093332. [New run](https://cirrus-ci.com/task/5001748380385280) is also still in progress.

More flakes like this should be added here when they come up. I think part of the reason we may be seeing more of them now is that we just started correctly `await`ing a large portion of the e2e tests.

/cc @collinjackson

**Comment by collinjackson** [comment]
> More flakes like this should be added here when they come up. I think part of the reason we may be seeing more of them now is that we just started correctly `await`ing a large portion of the e2e tests.

I don't think this is it because the Firebase Test Lab tests don't use `flutter driver` at all.

**Comment by mklim** [comment]
> I don't think this is it because the Firebase Test Lab tests don't use `flutter driver` at all.

Oh, right. :man_facepalming: I knew this and forgot about it. In that case I have no idea why this would have spiked more recently.

**Comment by amirh** [comment]
I just hit what seems like this flake again.

It seems like the battery plugin test has "failed to run":
```
BUILD SUCCESSFUL in 25s
63 actionable tasks: 13 executed, 50 up-to-date
+---------+------------------------+--------------------+
| OUTCOME |    TEST_AXIS_VALUE     |    TEST_DETAILS    |
+---------+------------------------+--------------------+
| Failed  | flame-29-en-portrait   | Test failed to run |
| Failed  | walleye-26-en-portrait | Test failed to run |
+---------+------------------------+--------------------+
```

If I understand the logs correctly the apk was built successfully, I can't spot anything that seems related in the device logs.

test log: https://api.cirrus-ci.com/v1/task/4629668041064448/logs/main.log
device log: [link](https://00e9e64bac76853c879f28f4aeb82e86d772404f7b79b7f136-apidata.googleusercontent.com/download/storage/v1/b/flutter_firebase_testlab/o/plugins_android_test%2Fnull%2F5975743163269120%2Fflame-29-en-portrait%2Flogcat?qk=AD5uMEuZjDfCXl5UcGo4zXrlI3Nb3R8Zh6OWKHnrLIT21kJLD-jDtzCy5wNMayyNx-LdvNx6i4rx6DBS6TP1TQTGTyWdV_uAmxfWrMSvQKakk6I2JWddQ63ZfDCLXA0vazQyZNSukR8UjuKWBQo3W0k4xdml4N74T_m4NmVdnslPU9UhKcHOwVYvSyLaQvdaBhUrCn7I5YeGXzlaWrXBZ2HUiedQMLsOtaB3GpqUNoTtGrPTJoQpX-xjz6ZKFCBGnGPnIOoO0-5D8afdIQZEovnXRTwTwwIRLZPSFqxv4YDDHqYjY3zL_uijmaQtRygpAU9oHVAJImc_6zNtuU8SxQZrcj-e32MpHKcMKT7cx8atCLBzvpzKhaQurjO_l8PZ0XxAHTm7ZBf7ThRxTlHf40Guon-b4TsFYs3PgAZLO-LceraGFEpnG1DHVBhld2mCmRIM9oPhCLrb5VPBfL0xwgdL9vMnx7auIktMGipxtxskuSJjN-KjdkoA09kEsTOGESF49bp5Ii0fcxC19qcac55cwtT7wLbNYGdNly-vokECl6q7vUzlJh68ZCfKyvXoXlaOv4AT6RILDkZWChqZbps1amqeVNZ301FrIxxr8Fr8FA_0kke0Jq4NZGxpqcTYC62wzdftQxAK0llQma2SVIr5WYT_UN_haKPZynqpPo0ALob0X3_XA56t4pwa2ySL11ivCMEkBNqq19z_QNmLfOBa4sMzIJImfgcq9dIW8W86lGntxLTcW4zbQo8AXGMoXv_0evhnVuVR6avMkU33QPrU13V0FO0ZfqkWhAESBomacvGe0TNyYHbBlFfbFmZmGZ4URBY9PjO_RIkRV_Dj7TVpG2VU3EK9OUvSj0u94cjBAjF46pSm_rb3h8y2tCi5pmq-Zl1FRTqG)

**Comment by amirh** [comment]
Just hit it again, this time it's path_provider that trigged the failure:

https://api.cirrus-ci.com/v1/task/5495801791119360/logs/main.log


```
BUILD SUCCESSFUL in 31s
80 actionable tasks: 13 executed, 67 up-to-date
+---------+------------------------+--------------------+
| OUTCOME |    TEST_AXIS_VALUE     |    TEST_DETAILS    |
+---------+------------------------+--------------------+
| Failed  | flame-29-en-portrait   | Test failed to run |
| Failed  | walleye-26-en-portrait | Test failed to run |
+---------+------------------------+--------------------+
```

**Comment by amirh** [comment]
Just happened again on path_provider https://cirrus-ci.com/task/6665180725641216

@collinjackson do you know if anyone is actively looking into this?

**Comment by collinjackson** [comment]
I put up a PR at https://github.com/flutter/plugin_tools/pull/85 that might improve the situation by giving tests results a unique bucket. At the very least it will make it easier to understand what's going on.

**Comment by mklim** [comment]
Happened again with path_provider here: [Cirrus task](https://cirrus-ci.com/task/5009994483499008), [Firebase logs](https://console.developers.google.com/storage/browser/flutter_firebase_testlab/plugins_android_test/path_provider/5076372666187776/).

I double checked and the Firebase logs have some more details in them, it seems like this may be some kind of flake around signing the test APKs?

> Permission Denial: starting instrumentation ComponentInfo{io.flutter.plugins.pathproviderexample.test/androidx.test.runner.AndroidJUnitRunner} from pid=17977, uid=17977 not allowed because package io.flutter.plugins.pathproviderexample.test does not have a signature matching the target

**Comment by amirh** [comment]
"Test failed to run" just happened for the google_maps test, however the screenrecording from the test bucket shows that the test was actually running.

```
BUILD SUCCESSFUL in 24s
89 actionable tasks: 16 executed, 73 up-to-date
+---------+------------------------+--------------------+
| OUTCOME |    TEST_AXIS_VALUE     |    TEST_DETAILS    |
+---------+------------------------+--------------------+
| Failed  | flame-29-en-portrait   | Test failed to run |
| Failed  | walleye-26-en-portrait | Test failed to run |
+---------+------------------------+--------------------+

Have questions, feedback, or issues? Get support by visiting:
  https://firebase.google.com/support/

Uploading [build/app/outputs/apk/debug/app-debug.apk] to Firebase Test Lab...
Uploading [build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk] to Firebase Test Lab...
Raw results will be stored in your GCS bucket at [https://console.developers.google.com/storage/browser/flutter_firebase_testlab/plugins_android_test/google_maps_flutter/6347002871021568/]
```

https://cirrus-ci.com/task/6217629698359296


@collinjackson

**Comment by amirh** [comment]
Happened again on path_provider: https://cirrus-ci.com/task/5478051832135680?command=main#L2396

**Comment by collinjackson** [comment]
It looks to me like we're still somehow running multiple tests sharing the same GCS bucket at the same time.

There are two copies of this string in https://cirrus-ci.com/task/5478051832135680?command=main#L2205

```
Raw results will be stored in your GCS bucket at [https://console.developers.google.com/storage/browser/flutter_firebase_testlab/plugins_android_test/path_provider/4575686182567936/]
```

This `await for` might be part of the problem:
https://github.com/flutter/plugin_tools/blob/master/lib/src/firebase_test_lab_command.dart#L87

Mostly though I think we need a bucket identifier that avoids this bucket sharing between test files: https://github.com/flutter/plugin_tools/blob/master/lib/src/firebase_test_lab_command.dart#L153

Additional (less relevant) context below. I see this in the path_provider error logcat:

```
02-10 19:48:16.223: W/ActivityThread(17031): Package uses different ABI(s) than its instrumentation: package[io.flutter.plugins.pathproviderexample]: arm64-v8a, null instrumentation[io.flutter.plugins.pathproviderexample.test]: null, null
```

Later on I see this in the logs:

```
2-10 19:48:18.293: I/ActivityManager(1329): Force stopping io.flutter.plugins.pathproviderexample appid=10222 user=0: finished inst
02-10 19:48:18.293: I/ActivityManager(1329): Killing 17031:io.flutter.plugins.pathproviderexample/u0a222 (adj 0): stop io.flutter.plugins.pathproviderexample
02-10 19:48:18.302: W/Binder(1329): Outgoing transactions from this process must be FLAG_ONEWAY
02-10 19:48:18.302: W/Binder(1329): java.lang.Throwable
02-10 19:48:18.302: W/Binder(1329): 	at android.os.BinderProxy.transact(BinderProxy.java:480)
02-10 19:48:18.302: W/Binder(1329): 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
02-10 19:48:18.302: W/Binder(1329): 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
02-10 19:48:18.303: D/AndroidRuntime(16981): Shutting down VM
02-10 19:48:18.310: W/ActivityManager(1329): setHasOverlayUi called on unknown pid: 17031
02-10 19:48:18.310: I/Zygote(815): Process 17031 exited due to signal 9 (Killed)
02-10 19:48:18.329: I/AiAiMatchmaker(17170): 0 flags successfully committed
02-10 19:48:18.330: I/t_app_installe(13692): WaitForGcToComplete blocked Background on ProfileSaver for 6.613ms
02-10 19:48:18.333: I/ActivityManager(1329): Failure reporting to instrumentation watcher: comp=ComponentInfo{io.flutter.plugins.pathproviderexample.test/androidx.test.runner.AndroidJUnitRunner} results=Bundle[mParcelledData.dataSize=96]
```

**Comment by collinjackson** [comment]
Closing since we haven't seen "failed to run" in a long time. Feel free to reopen if it reoccurs.
