### ISSUE TITLE
BottomNavigationBar unselected items should use unselectedWidgetColor

### ISSUE THREAD

**Issue by MichaelPriebe** [flutter/flutter#46135]
## Use case

The only way to change this color using the apps theme is setting the text color of the `caption` style. Which is strange considering you're also setting an icon color.

## Proposal

Use `theme.unselectedWidgetColor` instead of `theme.textTheme.caption.color`

**Comment by Amitpatil215** [comment]
@Hixie  I would like to be assigned to this issue.

**Comment by Hixie** [comment]
Done. :-)
