### ISSUE TITLE
Switches are not drawing properly

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4613]
## Steps to Reproduce

1. Run the Flutter Gallery
2. Tap Components
3. Tap Selection controls
4. Tap SWITCH
5. Notice the circles are being rendered offset from their tracks.

![flutter_01](https://cloud.githubusercontent.com/assets/7953123/16160181/906ef2b2-347b-11e6-9a4a-8ffc51332073.png)

## Flutter Doctor

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /media/jimbe/mojossd/sysui/src/third_party/flutter
    • Framework revision 2de2ce35bb (18 hours ago), engine revision c69d907b49

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/home/jimbe/Android/Sdk
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-123992248-123972143)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.26
```

**Comment by abarth** [comment]
Looks like @eseidelGoogle might have broken this.

**Comment by eseidelGoogle** [comment]
I'm pretty sure this was @Hixie's change:
https://github.com/flutter/flutter/pull/4583/files#diff-fe2bb980c6207699cbf45538fe927afaL358

**Comment by eseidelGoogle** [comment]
Looks like he changed the thumb painting code and no longer uses the inset?
