### ISSUE TITLE
local_auth: ^0.6.1: On iOS device Authentication dialog is not displayed or taking some time to display

### ISSUE THREAD

**Issue by aMGLn** [flutter/flutter#46148]
The issue is that sometimes on iOS devices authentication dialog displayed, sometimes it does not, sometimes  it is taking some time to display. I could not pinpoint the case. App it self freezes and does not display the dialog but waits for an action

I have tested on example project. The issue is same.

**Target Device:** iPhone 6s Plus
**Target OS:** iOS 13.1.2

![IMG_0539](https://user-images.githubusercontent.com/18131568/70222395-fdd5f180-1784-11ea-8ace-f91d310af971.PNG)
![IMG_0538](https://user-images.githubusercontent.com/18131568/70222441-0c240d80-1785-11ea-82bf-9c4d12a29e45.PNG)

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale en-MN)
    • Flutter version 1.9.1+hotfix.6 at /Volumes/data/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/GrapecityMongolia/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • GCM Test IPhone • c41323ce4bbd7f962485618ef8376e0fd00f4c8f • ios • iOS 13.1.2

• No issues found!
```

**Comment by iapicca** [comment]
Hi @aMGLn 
could you please provide your `flutter run --verbose`?
Are you experiencing this issue in `debug` or `release`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by NickCullen** [comment]
Hi, 

I am also experiencing this issue, again on device 13.1.2 (iPhone 8). 

I don't see this on iPhone 7+ running iOS 12. 

We dispatch the authorise event upon app start and the Touch ID prompt never gets displayed but the fingerprint will actually work, it's just the prompt that's not being displayed. 
If you double tap the home button however (with an unregistered finger - so it doesn't 'complete' the authorisation) so you get the app to a state where you could potentially swipe it upwards to close... You will notice the prompt appears. 

It looks as though its 1 render frame behind / the animation doesn't play. 

I have cloned the repo. and attempted some fixes manually by wrapping the call to evaluatePolicy and its response within the main dispatch queue but didn't have any luck. 

I am not too familiar with Objective-C to help out here I'm sorry, but I am unsure if this is a Flutter / plugin issue as the plugin is working but the rendering is off. 

And this only happens on iOS 13.1.2.

**Comment by NickCullen** [comment]
It appears this is a bug with iOS 13 https://www.forbes.com/sites/kateoflahertyuk/2019/09/30/warning-as-apple-ios-13-touch-id-bug-hits-millions-of-iphone-users/#47aedc854fa4

I've tried some things within my flutter app such as calling WidgetsBinding.instance.redraw() after a 2 second timer etc. but no luck. 

In fact, the flutter app appears to be 'frozen' when this dialog prompt is invisible - for example I have the CircularProgressIndicator spinning which stops when this prompt is meant to be displayed. Therefore I don't think my 1 frame behind theory is related to the flutter rendering engine but is an issue at the native level. 

Coincidentally, I had the phone beside me with my app open waiting for the prompt to display whilst writing this... the screen is meant to turn off after a 5 minute delay and as soon as the screen dimmed I saw the prompt pop up!! 

I hope all this info helps - I'm sorry the depth of my Flutter knowledge ends here and I hope this is actually fixable by the developer :/

**Comment by NickCullen** [comment]
@iapicca any update on this? Its quite a serious issue

**Comment by iapicca** [comment]
Hi @NickCullen  
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by TahaTesser** [comment]
Hi @aMGLn  @NickCullen 
Are you still experiencing this issue on latest stable?
can you please provide your flutter doctor -v
and your flutter run --verbose?
Also, to better address the issue, would be helpful
if you could post a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by TahaTesser** [comment]
Hi @aMGLn 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
