### ISSUE TITLE
Dart Error: Can't load Kernel binary: Invalid kernel binary: Indicated size is invalid.

### ISSUE THREAD

**Issue by ZionPi** [flutter/flutter#46149]
Following the advice of @matthew-carroll [there](https://github.com/flutter/flutter/issues/44161),I've created a minimum [project](https://github.com/ZionPi/bdary.git) to reproduce this issue.
In this project , for the time being ,I only debug `android` platform which reference a third party's Cloud Message Service *.aar* library which is different from FCM and popular OneSignal.However,I cannot access the source code of *.aar*.  
To make push notification service work,I extend `io.flutter.app.FlutterApplication` and initialize third party's cloud message service 's sdk like this:

```dart
class MainApplication :io.flutter.app.FlutterApplication()  {
    override fun onCreate() {
        Log.d(TAG, "app init...")
        context = applicationContext
        instance = this
        super.onCreate()

        try {
            //initialize push server
            CloudTalk_Sdk.pushInit(context, CloudIntentService::class.java)

        } catch (e: Exception) {
            Log.e(TAG,"initialize error================>" +e.toString())
        }

    }


    companion object {
        private const val TAG = "MainApplication"
        var instance: MainApplication? = null
        var context: Context? = null
            private set
    }

}

```
and declare extended `MainApplication` and relevant service in `AndroidManifest.xml` like:

```xml
 <application
        android:name=".MainApplication"
        android:label="bdary"
        android:icon="@mipmap/ic_launcher"
        tools:replace="android:label"
        >
        <service android:name="com.example.bdary.CloudIntentService" />

        <service
            android:name="cn.com.video.star.cloudtalk.general.cloud.push.CloudPushService"
            android:exported="true"
            android:label="PushService"
            android:process=":pushservice" />

        <activity  android:name=".MainActivity" 
         ...
          >
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
```
All relevant value of  `APP_ID` 、 `APP_KEY` to make push service works correctly are provided as plaintext inside app `build.gradle` file in the [project](https://github.com/ZionPi/bdary.git) that I mentioned above.

`flutter doctor` output this:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.12.3-pre.49, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.2)
[✓] Connected device (1 available)

• No issues found!
```
It output messages below and a whole white screen for the `first time` and `Run` button becomes grey:
```
E/flutter (29649): [ERROR:flutter/shell/common/shell.cc(197)] Dart Error: Can't load Kernel binary: Invalid kernel binary: Indicated size is invalid.
E/flutter (29649): [ERROR:flutter/shell/common/engine.cc(198)] Could not prepare to run the isolate.
E/flutter (29649): [ERROR:flutter/shell/common/engine.cc(137)] Engine not prepare and launch isolate.
E/flutter (29649): [ERROR:flutter/shell/common/shell.cc(433)] Could not launch engine with configuration.
```
and wait for a few seconds ,`Run` button becomes available and  pressed it again for the `second time`,now the app works, **but** push service is killed. 
<strike>Push service can works well in `purely android project`.But when integrated inside a flutter project, it breaks down.</strike>

**Comment by ZionPi** [comment]
It seems this issue has something to do with `start a service and keep it running background all the time`.I created two android emulators ,targeting Android 8.0 and Android 9.0 separately.Push Service can live alive at Android 8.0 but killed at Android 9.0.  
For Android 8.0(Android O),it output messages like:
```
? E/System:  ******** DEPRECATED FUNCTIONALITY ********
10:36:24.978 25386-25386/? E/System:  * The implementation of the KeyFactory.RSA algorithm from
10:36:24.978 25386-25386/? E/System:  * the BC provider is deprecated in this version of Android.
10:36:24.978 25386-25386/? E/System:  * It will be removed in a future version of Android and your
10:36:24.978 25386-25386/? E/System:  * application will no longer be able to request it.  Please see
10:36:24.978 25386-25386/? E/System:  * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
10:36:24.978 25386-25386/? E/System:  * for more details.
```
and it start `push service` properly.

For Android 9.0(Android P),it outputs:
```
 D/SECURITY_MODULE: create KeyFactory instance failed.
```
According to  [Cryptography Changes in Android P](https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html),it has deprecated `Cipher.getInstance("AES/CBC/PKCS7PADDING", "BC") ` related  API to cause the failure of service.So I changed the `targetSdkVersion` to `27` which is Android 8.0.Push service killed problem solved.I have committed this change to [minimum project](https://github.com/ZionPi/bdary.git).

But,`Dart Error: Can't load Kernel binary: Invalid kernel binary: Indicated size is invalid.`still persist.

**Comment by saarthak08** [comment]
I tried `flutter clean` & it worked!!

**Comment by ZionPi** [comment]
> I tried `flutter clean` & it worked!!

**Comment by sramac2** [comment]
[Solution here](https://fantashit.com/invalid-kernel-binary-format-version/) this solution worked for me, I deleted the cache folder inside my flutter folder and when I ran flutter doctor -v dart SDK and all other required folders will be installed. This solved the issue for me after so long
