### ISSUE TITLE
textfield gets smaller after adding a content padding on ios

### ISSUE THREAD

**Issue by maheshmnj** [flutter/flutter#46141]
I am having a strange issue where on adding a **content padding** property to the textfield gets squeezed to a smaller height the same code works perfectly on android but not on ios.
I had to add it because the hint is not center aligned vertically by default if I add some content padding in any direction it gets vertically aligned.
Also notice that if the suffix icon is provided to textfield it doesnt squeeze or change its height
here is the textfield widget

```dart
TextField(
        controller: emailController,
        style: inputStyle,
        // obscureText:hint.contains("Password") ? isHidden : false,
        decoration: InputDecoration(
            contentPadding: EdgeInsets.only(left: 16),// on removing this line the issue is resolved but the hint is not vertically center aligned by default
            hintText:"Enter Password",
            hintStyle: TextStyle(
                color: Colors.black26,
                fontWeight: FontWeight.w400,
                fontSize: 14),
            suffixIcon: hint.contains("Password")
                ? IconButton(
                    onPressed: () {
                      // setState(() {
                      //   isHidden = isHidden ? false : true;
                      // });
                    },
                    icon: Icon(
                      Icons.remove_red_eye,
                      color: Colors.black54,
                    ),
                  )
                : null,
            border: OutlineInputBorder(
                borderSide: BorderSide(
              width: 3.5,
              color: Colors.black26,
            )),
            focusedBorder: OutlineInputBorder(
                borderSide: BorderSide(
              width: 2.0,
              color: Colors.black26,
            ))),
              ),
```
this is how both textfields look with and without suffix icon
![Screenshot 2019-12-05 at 9 04 07 AM](https://user-images.githubusercontent.com/31410839/70202997-816def00-1741-11ea-927a-fb4f56aa86da.png)

heres is my``` flutter doctor -v ``` output
```
✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G1012, locale en-IN)
    • Flutter version 1.9.1+hotfix.6 at /Users/almac03/Documents/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/almac03/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5
[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0
[✓] Connected device (1 available)
    • iPhone 11 Pro Max • B1D782BE-C888-47D1-9BF7-91F523DF5A68 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
• No issues found!
```

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
I tried a simplified version and couldn't reproduce it.  @maheshmnj  Can you modify this code to reproduce the bug?

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('contentPadding bug'),
        ),
        body: Center(
          child: Column(
            children: <Widget>[
              TextField(
                controller: TextEditingController(text: 'no contentPadding'),
                decoration: InputDecoration(
                  contentPadding: EdgeInsets.all(30),
                ),
              ),
              TextField(
                controller: TextEditingController(text: 'yes contentPadding'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

Here's what it looked like:

<img width="376" alt="Screen Shot 2019-12-16 at 2 26 58 PM" src="https://user-images.githubusercontent.com/389558/70948392-3e006400-2010-11ea-8e0a-f67cd032206b.png">

**Comment by maheshmnj** [comment]
> I tried a simplified version and couldn't reproduce it. @maheshmnj Can you modify this code to reproduce the bug?
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: Scaffold(
>         appBar: AppBar(
>           title: Text('contentPadding bug'),
>         ),
>         body: Center(
>           child: Column(
>             children: <Widget>[
>               TextField(
>                 controller: TextEditingController(text: 'no contentPadding'),
>                 decoration: InputDecoration(
>                   contentPadding: EdgeInsets.all(30),
>                 ),
>               ),
>               TextField(
>                 controller: TextEditingController(text: 'yes contentPadding'),
>               ),
>             ],
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> Here's what it looked like:
> 
> <img alt="Screen Shot 2019-12-16 at 2 26 58 PM" width="376" src="https://user-images.githubusercontent.com/389558/70948392-3e006400-2010-11ea-8e0a-f67cd032206b.png">

yes I couldnt reproduce it but theres something wrong with my textfield widget I am not exactly sure what is wrong but I can see that When I remove suffix icon and add content padding property the textfield gets squeezed(only on ios), can you just put in a separate file and use it in your widget tree to reproduce the issue,
```
class TextFieldWidget extends StatefulWidget {
  final String hint;
  final TextEditingController controller;
  final Key key;

  TextFieldWidget({this.controller, this.hint, this.key});

  @override
  _TextFieldWidgetState createState() => _TextFieldWidgetState();
}

class _TextFieldWidgetState extends State<TextFieldWidget> {
  bool isHidden = true;

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 46,
      child: TextField(
          key: widget.key,
          controller: widget.controller,
          style: inputStyle,
          obscureText: widget.hint.contains("Password") ? isHidden : false,
          decoration: InputDecoration(
              fillColor: Colors.red,
              // contentPadding: EdgeInsets.only(left: 16, bottom: 15),
              hintText: widget.hint,
              hintStyle: TextStyle(
                  color: Colors.black26,
                  fontWeight: FontWeight.w400,
                  fontSize: 14),
              suffixIcon: widget.hint.contains("password")
                  ? IconButton(
                      onPressed: () {
                        setState(() {
                          isHidden = isHidden ? false : true;
                        });
                      },
                      icon: Icon(
                        isHidden ? eye : eye_off,
                        color: Colors.black54,
                      ),
                    )
                  : null,
              enabledBorder: OutlineInputBorder(
                  borderSide: BorderSide(width: 0.5, color: Colors.red)),
              focusedBorder: OutlineInputBorder(
                  borderSide: BorderSide(width: 0.5, color: Colors.green)))),
    );
  }
}

```

**Comment by justinmc** [comment]
Sorry, I need a working app to test.  It looks like you have a bunch of undefined variables in your TextFieldWidget.

**Comment by maheshmnj** [comment]
can you please check this minimal working app producing the issue https://github.com/maheshmnj/textfield-issue-ios

**Comment by justinmc** [comment]
<img width="300" alt="Screen Shot 2019-12-18 at 10 29 13 AM" src="https://user-images.githubusercontent.com/389558/71113155-dec26100-2181-11ea-8759-f60a525d7898.png"> <img width="300" alt="Screen Shot 2019-12-18 at 10 33 35 AM" src="https://user-images.githubusercontent.com/389558/71113156-dec26100-2181-11ea-98d3-affa292b0cc9.png">

**Comment by maheshmnj** [comment]
> can you please check this minimal working app producing the issue https://github.com/maheshmnj/textfield-issue-ios

this code when I run as it is on the stable channel produces me this output

**with content padding**

![Screenshot 2019-12-20 at 9 16 15 AM](https://user-images.githubusercontent.com/31410839/71228933-c8471180-2309-11ea-841f-a74ff6aa0cac.png)

**without content padding**
![Screenshot 2019-12-20 at 9 23 18 AM](https://user-images.githubusercontent.com/31410839/71229101-65a24580-230a-11ea-9a3d-56d1dce80a4d.png)

**Comment by maheshmnj** [comment]
Also I was able to produce another strange issue with that textfield but I couldnt figure out a reason to that,when the text gets overflowed it gets shrinked,here's how it looks when its overflowed

not overflowed yet             |  overflowed text
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/31410839/71229579-14935100-230c-11ea-848d-2b3720dd8ee7.png)  |  ![](https://user-images.githubusercontent.com/31410839/71229267-e6f9d800-230a-11ea-9870-74e4b8dceb6e.png)

**Comment by justinmc** [comment]
Could you try again on the master and dev channels?  Hopefully this is something that has been fixed but has not made it to stable yet.

**Comment by maheshmnj** [comment]
thanks,tried it on the master channel and hopefully it works 
```
[✓] Flutter (Channel master, v1.13.4-pre.12, on Mac OS X 10.14.6 18G1012, locale en-IN)
    • Flutter version 1.13.4-pre.12 at /Users/almac03/Documents/flutter
    • Framework revision cc1c9649c4 (3 days ago), 2019-12-19 19:53:01 -0800
    • Engine revision 472197a8e9
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 8d11c1dce6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/almac03/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • CFDEA05F-EF26-4360-B83B-F40488803C63 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!
```


![Screenshot 2019-12-23 at 9 15 36 AM](https://user-images.githubusercontent.com/31410839/71334785-9631eb80-2565-11ea-824a-6ea093b56db3.png)

**Comment by maheshmnj** [comment]
I think this is solved now so closing the issue if someone feels this is not solved it feel free to drop a comment here
