### ISSUE TITLE
Keyboard Freezing on Samsung Galaxy J Max Tab - 32bit device with beta v1.12.13+hotfix.2

### ISSUE THREAD

**Issue by iampawan** [flutter/flutter#46159]
@timsneath 

## Steps to Reproduce

 

1. Open the app.
2. Start typing on any text field. 
3. After some inputs, the keyboard freezes, you can still hear the ticking sound but it freezes with the OS at least for few mins.

 The problem is happening with the Samsung Galaxy J Max tab with Android 5.1.1. Just FYI It has 32 Bit ARM-based CPUs.

I tried it with other channels. The build is working fine then. 

## Logs

```
```

```
```

[✓] Flutter (Channel beta, v1.12.13+hotfix.2, on Mac OS X 10.15.1 19B88, locale
    en-GB)
    • Flutter version 1.12.13+hotfix.2 at /Users/pawankumar/flutter
    • Framework revision 4f54e46f56 (22 hours ago), 2019-12-04 09:20:18 -0800
    • Engine revision 6955b06ced
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/pawankumar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.6 Preview.app/Contents
    • Flutter plugin version 41.2.3
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin version 41.2.3
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 41.1.4
    • Dart plugin version 192.7761

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```
```

**Comment by tvolkert** [comment]
@dnfield

**Comment by dnfield** [comment]
Tried on a Samsung Galaxy Tab S 10.5, did not reproduce.

Tried on Samsung Galaxy Tab 3 Lite, also didn't reproduce.

@iampawan the app I'm trying is just our default app from Flutter create with a text field added.  I'm selecting the text field and just typing a bunch of random letters quickly for a minute.  I'll try to track down the exact device you're on, but it'd be helpful to know if I'm just not using the right test :)

**Comment by dnfield** [comment]
Also, FWIW, the devices I'm testing are on Android 4.4.2 (API 19) and 4.2.2 (API 17).

They're both armv7/32-bit.

**Comment by dnfield** [comment]
I'm not able to track down a Galaxy Tab J Max either in our device lab, a bigger lab at Google, or on eBay :(

**Comment by iampawan** [comment]
@dnfield no problem. Give me some time. I'll go to the office tomorrow morning IST and I will grab the device and try to perform the same thing with my other apps. Right now, I don’t have the device with me But I actually tried running the same app with the different channel and it started working fine.

**Comment by dnfield** [comment]
@iampawan - it would be super helpful if you could bisect this issue since I'm not able to reproduce it.  You should be able to do something like this on beta:

```
$ git bisect bad
$ git checkout stable
$ git bisect good
```

You'll then get walked through a bunch of commits by git.  Run your app, try typing, if it freezes use `git bisect bad`, if not `git bisect good`.  Eventually you should find the commit where things went wrong (probably an engine roll).  That would help us narrow down things a bit more.  If it's an engine roll, it may also be helpful to try all the engine commits in that roll to find out which one was bad.

**Comment by iampawan** [comment]
@dnfield That's a very helpful suggestion. I'll definitely update you as soon as possible.

**Comment by tvolkert** [comment]
Note that I'm not marking this as a release blocker since we haven't been able to reproduce yet.

**Comment by iampawan** [comment]
Hi, @tvolkert @dnfield This is what I could get using the above process. 
![Screenshot 2019-12-06 at 12 33 40 PM](https://user-images.githubusercontent.com/12619420/70303120-cdde2b00-1824-11ea-999e-36d34646d39b.png)

[c382b8e990b6976f610764179f94e0416d82c057] Roll engine 3dc233f04e8e..55406841525f (5 commits) (#38756)

**Comment by iampawan** [comment]
Also, it's not happening with normal text fields but it happens when I have text fields with focus nodes and I unfocus and request focus on other text fields. It's just my assumption though. I can make a video if you need.

**Comment by tvolkert** [comment]
Thanks for your help!

So did the bisect identify c382b8e as the commit that introduced this?  If you sync to the commit before that commit (2200e58), does the problem go away?  That commit is also in `v1.9.1`, so that would mean the bug is in stable right now...

What would be very helpful is if you could write a minimal sample app whose text field demonstrates this problem, so we can all agree on the code that we're testing against.

**Comment by iampawan** [comment]
@tvolkert Actually I didn't complete it. I am doing it right now but it is taking time because with every commit I need to download the sdk again and again.

**Comment by tvolkert** [comment]
Ah, gotcha.  Thanks again!

**Comment by iampawan** [comment]
Hi @tvolkert @dnfield I found the commit


[384a44d6bdce88d5bbd63fbcccc29ee8dc32f0ba] update docs (#32545)
commit 53c7ca7d5ada715f9c2c62fb1d3e0ab115c611f9 (refs/bisect/bad)
Author: Amir Hardon <amirh@users.noreply.github.com>
Date:   Wed Nov 20 17:00:46 2019 -0800

    Allow unknown fields in pubspec plugin section (#45303)

![Screenshot 2019-12-06 at 2 03 45 PM](https://user-images.githubusercontent.com/12619420/70308559-8ca04800-1831-11ea-86ef-4a99cec66c35.png)


Also, thanks for letting me know about this helpful tool. Is there any way to not download the sdk and tooling again and again?

**Comment by iampawan** [comment]
Hi, @tvolkert @dnfield I found the commit. Also, thanks for recommending these commands. I didn't know about it.  Also, is there any way of doing this without downloading the SDK and build tools and running the app again and again.



6b66d794360bb7d3ff7bf2f6dfbcbd58516c3f20 is the first bad commit
commit 6b66d794360bb7d3ff7bf2f6dfbcbd58516c3f20
Author: Gary Qian <garyq@google.com>
Date:   Wed Nov 20 16:37:10 2019 -0800

    Track and use fallback TextAffinity for null affinity platform TextSelections. (#44622)

 .../flutter/lib/src/painting/text_painter.dart     |  9 +++--
 packages/flutter/lib/src/rendering/editable.dart   | 35 ++++++++++++++++++--
 .../flutter/lib/src/services/text_editing.dart     |  4 +--
 packages/flutter/lib/src/services/text_input.dart  |  5 ++-
 .../flutter/test/painting/text_painter_test.dart   | 38 ++++++++++++++++++++++
 packages/flutter/test/rendering/editable_test.dart | 25 ++++++++++++++
 .../flutter/test/services/text_input_test.dart     | 31 ++++++++++++++++++
 7 files changed, 139 insertions(+), 8 deletions(-)


![Screenshot 2019-12-06 at 2 29 22 PM](https://user-images.githubusercontent.com/12619420/70310097-e6eed800-1834-11ea-92dd-eaf8fbb31b9d.png)

**Comment by iampawan** [comment]
I hope it helps. Let me know if you want anything else from my side.

**Comment by dnfield** [comment]
@iampawan - just to be clear, if you checkout beta and _revert_ 6b66d79, the issue goes away right?

**Comment by iampawan** [comment]
Yes

**Comment by tvolkert** [comment]
@iampawan any luck in getting a minimal app & repro steps in the app that demonstrates the problem?

**Comment by iampawan** [comment]
@tvolkert  I was out. Working on that just right now

**Comment by tvolkert** [comment]
Thanks!

**Comment by iampawan** [comment]
Hi, @tvolkert @dnfield Pardon me for the worst code 😅I had to write to minimally reproduce it. https://gist.github.com/iampawan/efeff11154c6eba795ddf37730263968

Let me know if it works.

**Comment by iampawan** [comment]
Also, the implementation might be very poorly done by my team mate but it was working for some reason without this weird issue but today because I checked it, may be I would be able to fix it (not sure though) by trying few things in the code. But even if it has any exception or something it should give that error rather than freezing. And it should not work on other commits then. Let me know if you need any other information from my side.

**Comment by dnfield** [comment]
When I try this I can't type anything at all...

**Comment by iampawan** [comment]
That's makes sense. Because the text is setting to " " in the listener .
Actually I just posted this because it was freezing the keyboard somehow. I
thought maybe your 32 bit devices will behave the same way.

**Comment by cbracken** [comment]
@iampawan once you've got a repro that works for you on other devices but not on the device in question, please post the code and we'll give it a look. It sounds like right now it's not working for us on any device.

**Comment by cbracken** [comment]
@kf6gpe can we get this labelled with affected customers to better understand the impact here?

**Comment by dnfield** [comment]
I missed what the code was doing there - I'm still not able to reproduce the keyboard freezing on the 32 bit Samsung tablets I have access to.

**Comment by kf6gpe** [comment]
cc @timsneath, who should know which of the customers reported this.

**Comment by timsneath** [comment]
Pawan is the reporter.

**Comment by Hixie** [comment]
cc @GaryQian I took a guess and assigned this to you with a guess at the target milestone, please reassign if you're not the appropriate person. Thanks!

**Comment by GaryQian** [comment]
This was indeed introduced by https://github.com/flutter/flutter/commit/6b66d794360bb7d3ff7bf2f6dfbcbd58516c3f20

It is currently rolled back, pending a rewrite to avoid this and a few other flickering bugs this caused.

I will close this as I do not expect to reland without significant reworks.

**Comment by GaryQian** [comment]
This may require a hotfix to fix it in stable.

**Comment by GaryQian** [comment]
The following reverts are needed to hotfix this: https://github.com/flutter/flutter/pull/45698 as well as https://github.com/flutter/engine/pull/14053 engine side

**Comment by GaryQian** [comment]
cc @kf6gpe

**Comment by GaryQian** [comment]
cc @tvolkert
