### ISSUE TITLE
[google_sign_in] Support For macOS Desktop app

### ISSUE THREAD

**Issue by arctouch-felipefontes** [flutter/flutter#46157]

**Comment by stuartmorgan** [comment]
The GoogleSignIn SDK this plugin wraps isn't available for desktop, so it may not be possible to implement the same API. The API surface will need to be evaluated against a supported option like AppAuth to determine whether desktop support should be a separate plugin instead.

**Comment by arctouch-felipefontes** [comment]
@ditman can you help with this one two?

**Comment by ditman** [comment]
@arctouch-felipefontes macOS desktop development is very foreign to me, so I'm going to trust @stuartmorgan's judgement in this one (and you should too!) :)

(I looked at [AppAuth](https://appauth.io/) and it looks promising. Maybe you can try to implement a version of google_sign_in for Mac using AppAuth on a separate package, just like we did with the web version?)

**Comment by arctouch-felipefontes** [comment]
I'm sorry I didn't mean to be disrespectful. I've just think i can't contribute to the discussion because i have never did a hello world on a macOS app and also have no idea how google_sign_in is implemented. I just use it. :)
Like @ditman said.
For google sign in web. we have the google_sign_in_web package.
why no have the google_sign_in_mac package.
and he would be able to implement the interface on the core package right?

**Comment by ditman** [comment]
> could we have the google_sign_in_mac package?

Yes, that is the idea. If anybody creates a `google_sign_in_mac` (or an `arctouch_google_sign_in_mac` package 😉) that follows the `google_sign_in_platform_interface` API, then everybody could use it on their existing apps just by depending on it (similarly to how you both depend on `google_sign_in` and `google_sign_in_web`).

In the future we want to make that dependency automatic depending on the platforms your app targets, but for now it needs to be explicit.

> this way he would be able to implement the interface on the core package right?

You don't need to put the mac implementation in the core package at all, it can be any package on pub.dev (or github)

**Comment by ditman** [comment]
I think the problem that @stuartmorgan is highlighting is that the current `google_sign_in_platform_interface` API may not be well suited for a macOS version (that can't use the GoogleSignIn API directly, and needs to go through the AppAuth route)

**Comment by arctouch-felipefontes** [comment]
My english is not that good. i mean use the core interface to implement in the platform specific plugin.

About arctouch_google_sign_in_mac I would love to learn and try to do it. but i'm actually doing the web version of an app using bloc that already exists only changing the UI but i'm having some difficulties with perfomance for flutter web, specially for ListView.separated scroll. so i had the idea to switch to mac app. but in order to convince my team at arctouch. I need the login. and I have a very close deadline for the flutter web version. so I can't stop wha't i'm doing to do this. If I find some time in the weekends i will try to.

This is my first time engaging on an open source discussion. i don't know if I'm doing correctly.

I Actually have a plugin that it's finished and don't find the time to do the Readme and publish it. Flutter is motivating me in ways I couldn't imagine.

**Comment by stuartmorgan** [comment]
> For google sign in web. we have the google_sign_in_web package.
could we have the google_sign_in_mac package?

The issue here is that "Google Sign-In" is a specific API which supports mobile and web, but not desktop. Adding a macOS implementation of the plugin would therefore be fundamentally different from adding a web implementation.

It may be that the plugin's interface can be implemented via AppAuth, or there may be a fundamental mismatch that will require a completely separate auth plugin with its own API (not just a federated implementation package). That's what needs to be evaluated, per my comment above. If the former is possible that's definitely the preferred outcome.

**Comment by felixwortmann** [comment]
Since there was no action on this since 2019, I am wondering what the plans are.
Flutter for desktop is available in the stable branch now so it seems weired that it is not supported by a first party plugin.

**Comment by gazzer82** [comment]
I've just hit this brick wall on a project I'm starting, seems a real shame that google auth is not available on desktop as of yet, I am also sadly not quite at a level yet where I can tackle something like this, but wanted to add my name to the list of people who would love to see this implemented!

**Comment by tantai24495** [comment]
I used this package to get credentials (access token, idToken) 
https://pub.dev/packages/googleapis_auth
After I got the information, I use GoogleAuthProvider.credential to create OAuthCredential, then sign in with firebase
Is this helpful for anyone ?
`obtainAccessCredentialsViaUserConsent(id, scopes, client, prompt)
        .then((AccessCredentials credentials) async {
        client.close();
        final OAuthCredential credential = GoogleAuthProvider.credential(
            idToken: credentials.idToken,
            accessToken: credentials.accessToken.data
        );
        final result = await FirebaseAuth.instance.signInWithCredential(credential);
    });`

**Comment by GroovinChip** [comment]
@tantai24495 can you provide a more detailed example of your implementation? The `googleapis_auth` package is actually preventing my macos app from building.

**Comment by GroovinChip** [comment]
Anyone watching this issue may be interested in https://github.com/fluttercommunity/firebase_dart_sdk/pull/29

**Comment by joachimvalente** [comment]
I was able to use @tantai24495 's solution above 🎉  Complete relevant code:

`pubspec.yaml`:

```yaml
dependencies:
  google_sign_in: ^5.0.2
  googleapis_auth: ^1.1.0
  http: ^0.13.3
  url_launcher: ^6.0.3
```

`authentication.dart`:

```dart
import 'package:google_sign_in/google_sign_in.dart';
import 'package:googleapis_auth/auth_io.dart';
import 'package:http/http.dart';
import 'package:url_launcher/url_launcher.dart';

Future<User> signInWithGoogleMacOs(BuildContext context) async {
  final id = ClientId(
      '<CLIENT ID>',
      '<CLIENT SECRET>');
  final scopes = [
    'email',
    'https://www.googleapis.com/auth/userinfo.profile',
  ];
  final client = Client();
  final credentials = await obtainAccessCredentialsViaUserConsent(
      id, scopes, client, (String url) => launch(url));
  final oauth = GoogleAuthProvider.credential(
      idToken: credentials.idToken,
      accessToken: credentials.accessToken.data);
  return (await _auth.signInWithCredential(oauth)).user;
}
```

**Comment by felixwortmann** [comment]
> I was able to use @tantai24495 's solution above 🎉 Complete relevant code:
> 
> `pubspec.yaml`:
> 
> ```yaml
> dependencies:
>   firebase_auth: ^1.1.4
>   firebase_core: ^1.1.1
>   google_sign_in: ^5.0.2
>   googleapis_auth: ^1.1.0
>   http: ^0.13.3
>   url_launcher: ^6.0.3
> ```
> 
> `authentication.dart`:
> 
> ```dart
> import 'package:firebase_auth/firebase_auth.dart';
> import 'package:firebase_core/firebase_core.dart';
> import 'package:google_sign_in/google_sign_in.dart';
> import 'package:googleapis_auth/auth_io.dart';
> import 'package:http/http.dart';
> import 'package:url_launcher/url_launcher.dart';
> 
> Future<User> signInWithGoogleMacOs(BuildContext context) async {
>   final id = ClientId(
>       '<CLIENT ID>',
>       '<CLIENT SECRET>');
>   final scopes = [
>     'email',
>     'https://www.googleapis.com/auth/userinfo.profile',
>   ];
>   final client = Client();
>   final credentials = await obtainAccessCredentialsViaUserConsent(
>       id, scopes, client, (String url) => launch(url));
>   client.close();
>   final oauth = GoogleAuthProvider.credential(
>       idToken: credentials.idToken,
>       accessToken: credentials.accessToken.data);
>   return (await _auth.signInWithCredential(oauth)).user;
> }
> ```

I just tried it and it works. It does not seem like an elegant solution to write the code for macOS yourself. Is there a way this could be included into the main plugin?

**Comment by felixwortmann** [comment]
I do get a popup from my app where it 'wants to use confidential information stored in "com.google.iid.checkin"' from my keychain. Is that popup needed or can I remove it in some way?

**Comment by birchb** [comment]
Thank you @felixwortmann! 

It may not be always necessary, but I had to `flutter clean` and rebuild to get it to work.

I'm going to move the ID and the SECRET to a config file so that data isn't stored in my Github repository.

**Comment by britannio** [comment]
> ```dart
> credential
> ```

This works although the `obtainAccessCredentialsViaUserConsent` future doesn't complete if the sign in tab is closed before the user signs in. Is there a workaround for this issue?

**Comment by jhlabs** [comment]
@felixwortmann which client id and secret are you using? I have registered the macOS app with Firebase as iOS and I am only able to retrieve a `clientId` but no secret.

**Comment by felixwortmann** [comment]
@jhlabs I have not looked at this for some time. If I remember correctly, you do not even have to use firebase, this is just about sign in with google. The setup is basically the same as if you configure google sign in for a web app. Just register your app in the google developer console(firebase projects usually get created automatically) and do a setup like  for web. You will get the credentials you need.

**Comment by jhlabs** [comment]
@felixwortmann thanks for the quick reply. I tried also setting up the app as a web app, but then I get an error for unauthorized redirect URLs. I have whitelisted the `http://localhost` domain, but unfortunately, Flutter macOS seems to use a new random port every time I call the method and I don't know where to set this port specifically. Did you have to do any setup with whitelisting ports?

**Comment by felixwortmann** [comment]
@jhlabs 
You can set a specified port (i.e. 5000) with 

flutter run -d chrome --web-port=5000

**Comment by jhlabs** [comment]
@felixwortmann thanks this works well for running Flutter for web, but did not change to a default port for me when using the macOS version. Will dig deeper on where this port is set.

**Comment by stuartmorgan** [comment]
It would be helpful if ongoing discussion of short-term alternatives could be moved somewhere else, such as StackOverflow. This issue is tracking actually implementing `google_sign_in` (if feasible), and discussion here should be about that

**Comment by birchb** [comment]
I faced similar issues. I'm documenting them here only because others might search here and find solutions:

See [[google_sign_in] Support For macOS Desktop app #46157](https://github.com/flutter/flutter/issues/46157#issuecomment-843619264).



MacOS is sandboxed by default. Edit `Runner/DebugProfile.entitlements` to


```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.cs.allow-jit</key>
	<true/>
	<key>com.apple.security.network.server</key>
	<true/>
	<key>com.apple.security.network.client</key>
	<true/>
</dict>
</plist>
```

See https://github.com/google/flutter-desktop-embedding/issues/546#issuecomment-529290611

The trick is to add `http://localhost` as a URI redirect in the cloud console.

**Comment by stuartmorgan** [comment]
> I faced similar issues. I'm documenting them here only because others might search here and find solutions

Please read my comment just above yours. A single link from this issue to, say, a StackOverflow question with answers, comments, etc. would be still be discoverable from here, would be *more* discoverable from searches outside of the issue tracker, and would not continue sidetracking this issue with off-topic discussion.

If this continues to be an issue we may need to lock this thread to keep it on topic.

**Comment by omniiidemo** [comment]
omni mocks google 

There are already apps have login auth on Mac 
how it would be 

I installed it by mistake 

If you change 10.12 to 10,0 this is suppoort 

But I deleted 
 pod deintegrate  

I deleted the project, I can't get it back, after that I updated cocoapods 

now How do I add authentication and maps

**Comment by omniiidemo** [comment]
pod 'Firebase/Analytics'
pod 'GoogleSignIn'
google maps

**Comment by omniiidemo** [comment]
flutter.io/google_sign_in)
[        ] #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
[        ] <asynchronous suspension>
[        ] #1      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:233:5)
[        ] <asynchronous suspension>
[        ] #2      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart)
[        ] <asynchronous suspension>

**Comment by omniiidemo** [comment]
how can support login auth on Mac
inside pod file macOS

pod 'GoogleSignIn'
[!] The platform of the target Runner (macOS 10.12) is not compatible with GoogleSignIn (6.0.1), which does not support macOS.

**Comment by stuartmorgan** [comment]
@omniiidemo Please do not spam this issue with support requests; this is a tracking issue for a specific feature request. If you want help with your own code, see flutter.dev/community for other options.

**Comment by omniiidemo** [comment]
@stuartmorgan If you don't have a solution, I would like you to shut up

هذا برنامج يعمل على نظام ماك 
![Screen Shot 1442-12-17 at 4 01 00 PM](https://user-images.githubusercontent.com/73233894/127157931-473d005c-c709-4489-a793-4d2254ffc5e7.png)
This is a program that works on Mac

**Comment by ManasMalla** [comment]
@stuartmorgan I just came across this tutorial and github repo which allows signin with google on macOS apps which might help to support google sign in on mac - https://github.com/uynguyen/GoogleSignIn-MacOS

**Comment by mono0926** [comment]
Here are the steps to take until the google_sign_in package is macOS compatible.
---

It is easy to implement Google auth for macOS by using the [desktop_webview_auth](https://pub.dev/packages/desktop_webview_auth) package.

<img width="683" alt="image" src="https://user-images.githubusercontent.com/1255062/154004730-ec0802b7-6086-4f94-bfe2-e9958c38254c.png">

https://pub.dev/packages/desktop_webview_auth#usage

This is also used in [flutterfire_ui](https://pub.dev/packages/flutterfire_ui), and if you use [GoogleSignInButton](https://pub.dev/documentation/flutterfire_ui/latest/auth/GoogleSignInButton-class.html) in that package, you can support macOS without addtional code.
https://firebase.flutter.dev/docs/ui/auth/configuring-providers#google

**Comment by stuartmorgan** [comment]
[GoogleSignIn-iOS](https://github.com/google/GoogleSignIn-iOS) supports macOS as of 6.2. I took a quick look at adding macOS support to `google_sign_in_ios` by sharing the existing code with some ifdef's, and found that it's blocked on https://github.com/flutter/flutter/issues/41471

(/cc @cbracken FYI)

**Comment by dotjon0** [comment]
Any plans to get macOS support in place for google sign in? This ticket has been open for a little while now and Flutter desktop macOS support has been in GA for a while...

**Comment by stuartmorgan** [comment]
Nobody is actively working on this at the moment. Anyone interested in moving this forward is certainly welcome to contribute a fix to the blocking issue I mentioned above.

**Comment by dotjon0** [comment]
Thanks for the update @stuartmorgan. Seems odd the Firebase Team (or the Flutter team, or GCP Identify Platform team) are not picking this one up, as this makes Flutter a non starter for any SaaS vendor looking to release a macOS application with Google sign in, which is very common...

**Comment by bselwe** [comment]
We run into some limitations with @rafaelortizzableh when using [desktop_webview_auth](https://pub.dev/packages/desktop_webview_auth), mainly, the user needs to log in to their social platform, even though they may already be logged in in their preferred (default) browser. This is because the webview acts as a separate, incognito browser window.

Here's the workaround we used to get the Google authentication working in MacOS and Windows using [`url_launcher`](https://pub.dev/packages/url_launcher) with [`app_links`](https://pub.dev/packages/app_links): [Social authentication in Flutter Desktop apps](https://bselwesiuk.medium.com/social-authentication-in-flutter-desktop-apps-c8c0599e13d3).

**Comment by Knightro63** [comment]
Hi all,

I have implemented the google sign in for macos about 3 months ago and noticed this issue is still opened when updating one of my apps. The location is here https://github.com/Knightro63/google_sign_in_macos, but not sure how to submit a pull request for this. Also if someone wouldn't mind looking over it would be great thanks.

**Comment by stuartmorgan** [comment]
@Knightro63 The contribution process is documented in [the contribution guide](https://github.com/flutter/packages/blob/main/CONTRIBUTING.md). This is blocked on an engine feature though, as I noted above.

**Comment by amorenew** [comment]
the blocking issue has been marked as an easy fix since 3 years ago 🤔😅
https://github.com/flutter/flutter/issues/41471
![image](https://github.com/flutter/flutter/assets/2842459/fc79fcb7-2432-4794-bdaf-fc5c8bece1be)

**Comment by eliept1** [comment]
Hey, if I understand well this thread, there is no way to log in to a google account on flutter macOS desktop app ? I need to use gmail api on a macOS app to retrieve mails of a logged user via the gmail api, so I can't do that ? 
Thank you for your help

**Comment by stuartmorgan** [comment]
@eliept1 Nothing prevents a Flutter application developer from writing native code that uses the GoogleSignIn SDK. This issue is specifically about the `google_sign_in` plugin, and the blocking issue is specific to plugins.

**Comment by amorenew** [comment]
blocking issue is closed 😁😍
https://github.com/flutter/flutter/issues/46157#issuecomment-1131853942

**Comment by stuartmorgan** [comment]
I have a branch that adds macOS support; if anyone wants to try it out you can add the following to your pubspec.yaml:

```
dependency_overrides:
  google_sign_in_ios:
    git:
      url: https://github.com/stuartmorgan/packages.git
      ref: google-sign-in-macos
      path: packages/google_sign_in/google_sign_in_ios
```

This will require using a version of Flutter `master` that's from yesterday or later.

I haven't done a working end-to-end test yet since my initial attempt to integrate it into a test application ran into Keychain error exceptions, but it's likely that's an issue with the app's setup rather than the plugin. Feedback welcome if anyone does give it a try before I have time to return to debugging the app I was trying it in.

**Comment by ditman** [comment]
Wow, super requested feature! Congrats!
