### ISSUE TITLE
No shadows cast on a background when below a Material in a view

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#4615]
As in:
https://gist.github.com/HansMuller/7d7dd73728164adbfa8388ebfa97a493

When the background alpha goes to 1.0, the shadow cast by the above material widget becomes invisible.

**Comment by HansMuller** [comment]
I don't think this is a bug. A Material widget is only defined to cast a shadow on the Material widget below it. 

See http://docs.flutter.io/flutter/material/Material-class.html

**Comment by HansMuller** [comment]
I have been convinced that this is indeed a bug.

**Comment by Hixie** [comment]
I don't understand what this bug means.
