### ISSUE TITLE
Arabic characters are disjoint in a ListView when having multi-lang texts

### ISSUE THREAD

**Issue by omarhuss** [flutter/flutter#46156]
## Steps to Reproduce

* I was testing an app on iOS 12.4 emulator, when putting `Text`s of multiple languages inside a `ListView`, Arabic characters are disjoint after scrolling. This not only happened in the `ListView`, but in the whole application after changing its state.

* Gist to test (Please make sure you test on iOS 12.4 emulator):  https://gist.github.com/omarhuss/dd2f962235890af5ab08d2cc496cb1d2

* Important note: Apparently, this issue only happens on iOS 12.4 emulators so far.

**Target Platform:** iOS
**Target OS version/browser:** iOS 12.4
**Devices:** iPhone 5s Emulator

## Logs

There are no exceptions from the verbose logs.

flutter doctor -v

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale
    en-TR)
    • Flutter version 1.9.1+hotfix.6 at
      /Users/user/Development/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 40.0.4
    • Dart plugin version 192.6817.14

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone 5s     • 062BCF4D-5D03-4A81-ABAC-5D89385C7E0D     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

**Comment by HansMuller** [comment]
CC @GaryQian

**Comment by goderbauer** [comment]
Is this specific to emulators? Or does it also happen on real devices? What about Android?

**Comment by omarhuss** [comment]
It happened only on an iPhone 5s emulator running iOS 12.4.

I tested on an Android emulator running Android v7.1.1 and a physical iPhone running iOS 13.2.3 without issues. 

Not sure about a physical iPhone device running on 12.4 or less because I don’t have one.

**Comment by pedromassangocode** [comment]
Hi @omarhuss 
Are you still facing this issue? If yes, please provide your `flutter doctor -v`, your `flutter run --verbose`?
Thank you
