### ISSUE TITLE
Application closed

### ISSUE THREAD

**Issue by developer-hosny** [flutter/flutter#46158]
Application closed

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale en-AE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (2 available)

• No issues found! 
```

```
I/flutter (21018): 5de9230b7e51d255485680ec
F/libc    (21018): Fatal signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0 in tid 21047 (1.ui), pid 21018 (example.app)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.191030.002/5978551:userdebug/dev-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2019-12-05 19:32:28+0400
pid: 21018, tid: 21047, name: 1.ui  >>> com.example.app <<<
uid: 10141
signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
    eax ac66781e  ebx 123173a2  ecx bcaffb2c  edx 1247a8e9
    edi bcaffb20  esi 1234cf66
    ebp 10c98366  esp 10c982f2  eip e6e9520c
backtrace:
      #00 pc 0009220c  /apex/com.android.runtime/lib/bionic/libc.so (sigsetjmp+92) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
Lost connection to device.
Exited (sigterm)
```

**Comment by iapicca** [comment]
Hi @developer-hosny 
can you please provideyour `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

Possible duplicate https://github.com/flutter/flutter/issues/45903

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
