### ISSUE TITLE
Please whitelist Skia autoroll accounts as not needing approval for the "waiting for green" bot

### ISSUE THREAD

**Issue by rmistry** [flutter/flutter#46169]
The Skia autoroll accounts will upload PRs and then immediately add the "waiting for green" label.
Last time I tried this it failed because it was missing approval. Could we please skip the approval check for the Skia autoroll accounts:

* https://github.com/skia-flutter-autoroll
* https://github.com/engine-flutter-autoroll

@dnfield

**Comment by dnfield** [comment]
This should be a pretty easy fix, I won't be able to get to it until at least after interact.  /cc @godofredoc @digiter @keyonghan

**Comment by rmistry** [comment]
Friendly ping for whenever people are back from holidays.

**Comment by tvolkert** [comment]
The skia autorollers are successfully landing autoroll PRs multiple times per day - e.g. https://github.com/flutter/engine/pull/15377

It seems like approvals are not needed to land these?

**Comment by dnfield** [comment]
They're still being landed by autoroller logic instead of by cocoon.

To let cocoon land them, we need to tell cocoon which accounts don't need an approval review.
