### ISSUE TITLE
Flutter crash when exiting message recording

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#46161]
https://buganizer.corp.google.com/issues/145678675.

**Comment by kf6gpe** [comment]
cc @jason-simmons , who was looking at it last.

**Comment by jason-simmons** [comment]
Is this a duplicate of https://github.com/flutter/flutter/issues/46111?

**Comment by gaaclarke** [comment]
> Is this a duplicate of #46111?

Looks like it, they both reference the same buganizer issue: https://buganizer.corp.google.com/issues/145678675
