### ISSUE TITLE
iOS platform view cancels gesture while a new clip layer is added during the gesture.

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#46167]
We implemented the iOS platform view clipping by adding extra UIViews in between the platform view and FlutterView and perform one clip on each added UIView.
Implementation details can be found here: https://github.com/flutter/engine/pull/9075

Inevitably, this implementation will cause a gesture bug as follow:

1. Put the finger on top of the platform view and start performing a dragging gesture.

2. If an additional clip is added to the platform view during the dragging gesture(Or a clip is removed), we have to `ReconstructClipViewsChain`. It leads to the platform view to be removed from the FlutterView's and then added back.

3. This removing and adding will cause the iOS system lost the dragging gesture. Thus sends a "touch cancelled" event to dart in `- (void)touchesCancelled:(NSSet*)touches withEvent:(UIEvent*)event`.

4. Since technically, we are still dragging (we have never lifted the finger of the screen during this sequence). we should never cancel this gesture. It will sometimes lead to a very bad visual behavior depends on the implementation of the platform view.

One of the example that I reproduced is here:

![ezgif com-optimize](https://user-images.githubusercontent.com/3756895/70260988-5639ce80-1746-11ea-9fd0-d5bd5fd3049e.gif)

In the first half of the video, my finger was on the black area, AKA non platform view area. The scrolling was smooth.
After the pause, I started to touch on the white area, AKA WebView(PlatformView). When the WebView reached the top of the screen, an extra clip was added to the layer tree for the WebView, and the gesture was cancelled. After that, the scrolling looks buggy.

An example code to reproduce the issue:
```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: WebViewSample(),
      ),
    );
  }
}

class WebViewSample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(child:ListView(
      children: <Widget>[
        ConstrainedBox(
          constraints: BoxConstraints(maxHeight: 500.0),
          child: WebView(
            initialUrl: Uri.dataFromString(
              '<p>Web view sample</p>' * 1000,
            ).toString(),
          ),
        )
      ],
    ),
    color: Colors.black,);
  }
}
``` 

We might need to find a better solution to perform clipping, or find a workaround to make the gesture not being cancelled during `ReconstructClipViewsChain`.

/cc @amirh

**Comment by cyanglaz** [comment]
One of the solution is to rework the clipping mechanism for iOS platform views.

Instead of adding a UIView for each clipping, we only add one UIView for all the clipping and never remove the platform view from its parent.

However, we would need to combine all the clippings into a final clipPath. And quartz doesn't support `conic path` where most of the clip rrects in flow converts to a `conic path`.  We need to figure out the math to approximate a conic path in flow with a quad path in quartz.

**Comment by pcsosinski** [comment]
under review for cp to 1.20
