### ISSUE TITLE
flutter/engine->flutter/flutter autoroller should roll Fuchsia SDK hash to match engine

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#46173]
cc @zanderso @iskakaushik

**Comment by dnfield** [comment]
@rmistry can we have the roller update both files?

**Comment by rmistry** [comment]
Yes, I was chatting with @iskakaushik about this and pointed to the code.
If somebody files an skbug.com for this I will eventually get to it.

**Comment by iskakaushik** [comment]
Filed: https://bugs.chromium.org/p/skia/issues/detail?id=9973

**Comment by iskakaushik** [comment]
This is complete.
