### ISSUE TITLE
[web] [gallery 2.0] Most images are blurry on high-dpi screen

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#46186]
https://flutter.github.io/samples/#/ shows blurry images all over the place on a high-dpi screen. This is most visible on the flutter logo and the category headers. But also the backgrounds of the example apps.  Maybe resolution aware asset loading does not work yet on web? Just a wild guess.

/cc @johnpryan

**Comment by Zazo032** [comment]
Could also be replaced with a `FlutterLogo` widget

**Comment by johnpryan** [comment]
We *just* made an update on Friday, the new link is here: https://flutter.github.io/samples/#/

**Comment by cbenhagen** [comment]
Thanks, I updated the link in the description.

**Comment by cbenhagen** [comment]
@yjbanov I updated this issue to reflect the state of gallery v2.0. As this is one of the first things people will see when they hear about the web version I hope this can get a high priority. It's such a beautiful new design but with the blurry images it just makes a pretty bad first impression.

**Comment by ferhatb** [comment]
Fix in master
