### ISSUE TITLE
Flutter benchmarks should run on Fuchsia devices in AOT/JIT modes

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#46199]
https://flutter-dashboard.appspot.com/benchmarks.html

cc: @jimicy

**Comment by Hixie** [comment]
Benchmarks that would be especially interesting include:
* the gallery transition perf benchmarks
* the various microbenchmarks
* debug mode compilation time
* release mode total size of hello world including engine
* hot reload time

**Comment by kf6gpe** [comment]
We presently support AOT mode, and JIT on devices with sufficient memory. Closing.
