### ISSUE TITLE
[web] Disabled shadows are not rendered correctly.

### ISSUE THREAD

**Issue by chingjun** [flutter/flutter#46202]
The screenshot tests added in #45530 revealed a bug where the disabled shadow wasn't implemented correctly. A corner is being clipped.

The one of the left is the behavior on web, the one on the right is the behavior on flutter_tester.
![image](https://user-images.githubusercontent.com/1267593/70286440-0ed03400-1780-11ea-8a89-64ddfcf26567.png)

Test file: `packages/flutter/test/widgets/shadow_test.dart`

**Comment by pedromassangocode** [comment]
Is this still a valid issue?

**Comment by ferhatb** [comment]
No more skips in test. Closing.
