### ISSUE TITLE
Block older i386 iOS devices in tools

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#4621]
## Steps to Reproduce

I'm trying to run my app on devices with screens of different sizes, using the iOS emulator. It works on some iOS emulated devices, but not others. For example, when I run my app on an emulated iPhone 6S Plus, iPad Pro, or iPad Air, it runs as expected. However, when I run it on an emulated iPad Retina, or iPad 2, it returns an error. It appears it cannot install the app on these devices at all.
## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/emshack/vanadium/flutter
    • Framework revision 6d2d495369 (11 days ago), engine revision a943c732d5
[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/emshack/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
[✓] iOS toolchain - develop for iOS devices (Xcode 7.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.2.1, Build version 7C1002
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.
[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.2
    • dartlang plugin version 0.6.21
## Logs and Crash Reports

An error was encountered processing the command (domain=FBSOpenApplicationErrorDomain, code=1):
The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)
Exit code 1 from: /usr/bin/xcrun simctl launch 024F6BBF-AA2F-49E8-972E-95DD1993D763 com.yourcompany.testapp --flx=/Users/emshack/vanadium/experimental/users/emshack/EmGen/build/app.flx --dart-main=/Users/emshack/vanadium/experimental/users/emshack/EmGen/lib/main.dart --packages=/Users/emshack/vanadium/experimental/users/emshack/EmGen/.packages --enable-checked-mode --start-paused --observatory-port=16168
Error running application on iPad Retina.

**Comment by eseidelGoogle** [comment]
@tvolkert @chinmaygarde

**Comment by tvolkert** [comment]
Those older devices are i386 architecture, which we currently don't support for iOS.  We should just proactively block them up-front so we don't get cryptic errors like this.

**Comment by eseidelGoogle** [comment]
I'm confused.  Old simulators are i386?  Not x64?

**Comment by tvolkert** [comment]
The devices themselves are, and the simulators replicate/emulate it.  Xcode detects this and will actually fail to build the app when building for a specific simulator target.  Our command-line tools, however, see we're building for "simulator" (generically) and just build for arm64.  Then we run on the emulated i386, and all bets are off.

**Comment by cbracken** [comment]
Fixed by #7857.
