### ISSUE TITLE
Program just shows a white screen on device on launching with visual studio

### ISSUE THREAD

**Issue by Roy-Matero** [flutter/flutter#46219]
when I try to run a flutter application on my device from visual studio I just get this endless white screen  on my android device. when I run the same application from the command line it runs well but I can't do a hot reload 

Dart log: 
```
Dart Code extension: 3.7.0
Flutter extension: 3.7.0 (not activated)
VS Code: 1.40.2
Platform: linux
Workspace type: Flutter
Multi-root?: false
Dart SDK:
    Loc: /home/r/Development/flutter/bin/cache/dart-sdk
    Ver: 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db
Flutter SDK:
    Loc: /home/roguestar/Development/flutter
    Ver: 1.9.1+hotfix.6
HTTP_PROXY: undefined
NO_PROXY: undefined
```

```
Fri Dec 06 2019 [11:59:10 GMT+0300 (East Africa Time)] Log file started
Fri Dec 06 2019 [11:59:23 GMT+0300 (East Africa Time)] Log file ended
```

flutter doctor output:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_US.utf8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[!] Android Studio (version 3.6)
    ✗ Unable to find bundled Java version.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
Hi @Roy-Matero 
can you please provide your  `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by Roy-Matero** [comment]
Hi
Thanks very much but the problem has already been solved in in the recent
flutter update
It's now running well and I'm back to coding again

**Comment by iapicca** [comment]
Hi @Roy-Matero 
I'm glad that you fixed the problem, 
thank you for letting me know
