### ISSUE TITLE
Can cocoapods-binary work with the Pods project generated by Flutter?

### ISSUE THREAD

**Issue by tomadimitrie** [flutter/flutter#46225]
I've tried implemented it and `pod install` ran successfully. However, when building from Xcode I get many errors of files not being found like: 

`FirebaseCore/FirebaseCore.h' file not found`

**Comment by janmoppel** [comment]
Hello @tomadimitrie !

Thank you for posting.
Your question seems to be a good fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) as well. Flutter has a very active and helpful community there, so feel free to post it there too.

Also, see other support options here: https://flutter.dev/community

**Comment by jmagman** [comment]
Can you confirm you have Runner.xcworkspace open in Xcode and not Runner.xcodeproj?

**Comment by tomadimitrie** [comment]
Yup

**Comment by jmagman** [comment]
Can we get the output of `flutter doctor -v`
What plugins and versions are you using?

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore going to close it. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
