### ISSUE TITLE
Undocking keyboard in iOS prevents viewInsets.bottom to return to 0.0

### ISSUE THREAD

**Issue by petherwiklander** [flutter/flutter#46222]
I just discovered that whenever the keyboard was shown in our application, viewInsets.bottom returned 353.0, and never returned to 0.0.
I also saw that the keyboard was displayed a bit above the bottom of the screen which made me check closer for how that could appear.
Apparently it is possible to "Undock" the keyboard in iOS and place it on the users preferred height (for unknown reasons 😄) .
Docking the keyboard makes viewInsets.bottom return to 0.0 and everything works as expected. Splitting the keyboard does not cause the same problem as undocking does.

**Comment by iapicca** [comment]
Hi @petherwiklander 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by petherwiklander** [comment]
![Image 2019-12-06 at 13 40](https://user-images.githubusercontent.com/20986583/70326701-71cfd280-1835-11ea-9c87-3b9925dd24f8.JPG)

I'll get back to you with an example after simplifying it.

**Comment by iapicca** [comment]
Hi again @petherwiklander
thank you for providing your updated flutter doctor -v.

Could you please provide your `flutter run --verbose` 
relative to the event you are describing
and a minimal code sample or the steps to reproduce the problem.

Please refrain from posting pictures if not necessary.
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
