### ISSUE TITLE
[Camera Plugin] How can i change the camera plugin to follow the device orientation?

### ISSUE THREAD

**Issue by wemersonrv** [flutter/flutter#46232]
Hello.

I'm using Flutterfire plugin for firebase_ml_vision, using the default example application and fix device orientation to landscape. Here the repository i'm using: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_ml_vision/example

But when i ran the app, the camera preview not follows the orientatoin image in camera remains with portraint.

**What can i do to make camera follows the device orientation ?**

Below a link to a video capture of issue: 

https://drive.google.com/file/d/1RZBHyOhLlcr5JldYonrbOz4srd22RU8r/view

## Flutter doctor
```bash
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [versÃ£o 10.0.17763.678], locale pt-BR)
    • Flutter version 1.9.1+hotfix.6 at D:\Flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Wemerson\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Wemerson\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.2)
    • VS Code at C:\Users\Wemerson\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.0

[√] Connected device (1 available)
    • Moto G 4 • 192.168.0.100:5555 • android-arm • Android 7.0 (API 24)
```

**Comment by janmoppel** [comment]
Hello @wemersonrv !

Thank you for posting an issue.
Your question seems to be a good fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) as well. Flutter has a very active and helpful community there, so feel free to post it there too.

Also, see other support options here: https://flutter.dev/community

Thank you.
