### ISSUE TITLE
Run `flutter pub get` when running `flutter build macos`

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#46236]
This happens in the https://github.com/flutter/plugins/tree/master/packages/connectivity/example and e2e plugin (the only macos plugins so far). This might be a problem with how they are setup, or a tooling problem.

**Comment by gaaclarke** [comment]
@franciscojma86 did you mean to close this?

**Comment by franciscojma86** [comment]
No, it was confirmed by the tools team that `flutter pub get` is always run by `flutter build ios`, so it should be added to other commands. Renaming it
