### ISSUE TITLE
FlutterView buildMode Debug Fail! But release mode run successfully.

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#4624]
## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/paul/flutter-workspace/flutter
    • Framework revision 833b121664 (6 hours ago), engine revision c69d907b49

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/paul/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_65-b17)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.0.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.0.1, Build version 7A1001
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.25
## Logs and Crash Reports

I/cr.library_loader: Expected native library version number "", actual native library version number ""
E/ApkAssets: Error while loading asset assets/icudtl.dat: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
W/art: Attempt to remove local handle scope entry from IRT, ignoring
I/OpenGLRenderer: Initialized EGL, version 1.4

```
E/flutter: [ERROR:dart_error.cc(17)] Unhandled exception:
           No top-level getter 'main' declared.

           NoSuchMethodError: method not found: 'main'
           Receiver: top-level
           Arguments: [...]
           #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:178)
           #1      _getMainClosure (file:///b/build/slave/Linux_Engine/build/src/out/android_debug/gen/sky/bindings/dart_ui/natives.dart:38)
I/flutter: Could not start Observatory HTTP server:
           SocketException: Failed to create server socket (OS Error: Permission denied, errno = 13), address = 127.0.0.1, port = 0
           #0      _NativeSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:505)
           #1      _RootZone.runUnary (dart:async/zone.dart:1204)
           #2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
           #3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
           #4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
           #5      _Future._completeWithValue (dart:async/future_impl.dart:477)
           #6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
           #7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
           #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
           #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
           #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
           #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/i
E/DartVM: vm-service: Error: Unhandled exception:
          SocketException: Failed to create server socket (OS Error: Permission denied, errno = 13), address = 127.0.0.1, port = 0
          #0      _NativeSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:505)
          #1      _RootZone.runUnary (dart:async/zone.dart:1204)
          #2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
          #3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
          #4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
          #5      _Future._completeWithValue (dart:async/future_impl.dart:477)
          #6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
          #7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
          #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
          #9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
          #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by tain335** [comment]
And flutter refresh not work too. every thing doesn't change and no error print.

**Comment by eseidelGoogle** [comment]
The error message is saying that it can't find a main() function in your lib/main.dart file.

That could be due to a parse error in your lib/main.dart or one of its dependencies?

You might try running `flutter analyze` against your project and making sure it comes out clean?

**Comment by eseidelGoogle** [comment]
Also I'm curious what device this is running on?

**Comment by Hixie** [comment]
We are closing this since we don't have enough information.
