### ISSUE TITLE
Migrate url_launcher's to the new pubspec plugins schema

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#46253]
Migrate the plugin to the [new pubspec plugins schema](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms) this involves renaming objc files as we no longer have `iosPrefix`.

**Comment by stuartmorgan** [comment]
The class name is correct (other than using the wrong capitalization), it's the filename that's wrong. Removing the prefix would violate Apple guidelines and Google style, and potentially break users (who can reasonably expect to use unprefixed class names in application-level code).

During migration to the new schema the files should be renamed and the prefix folded into the iOS-specific class name. That can't be done pre-migration.

**Comment by stuartmorgan** [comment]
The above applies to #46254, #46255, #46256, and #46257 as well.

**Comment by amirh** [comment]
Thanks for the quick catch @stuartmorgan I'm turning this issue into "migrate to new schema"
