### ISSUE TITLE
Gallery: check if there's a newer version for internal distribution

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4626]
For our internal distribution of the Gallery, we can check if there's a new version. If so, we can prompt the user to update their install. This way, we prevent super duper old Galleries from living on Googlers' phones.

**Comment by eseidelGoogle** [comment]
I recommend punting this for August.  We could work around this by just releasing straight to the public stores. :)  FYI @collinjackson other internal applications are going to want this, and we may want to consider this as one of our early internal "plugins".

**Comment by collinjackson** [comment]
Prefer to release to the public stores so we can not have to manage our own update service.

**Comment by sethladd** [comment]
This was just for internal iOS distribution.

**Comment by sethladd** [comment]
Bumping from August, but if we want to do internal iOS release, we should do this.

**Comment by eseidelGoogle** [comment]
We have no intention of distributing internally at this time to my knowledge.  We have plenty of other internal apps who have paved this path for us. :)

**Comment by collinjackson** [comment]
The internal iOS version already does this and I even wrote a test for it, see https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/test/update_test.dart

Sorry I forgot to close the bug :)
