### ISSUE TITLE
AndroidX incompatibilities with Flutter v1.9.1

### ISSUE THREAD

**Issue by ayodelesalimon** [flutter/flutter#46286]
I have flutter latest SDK, but it still brings AndroidX incompatibilities when running on my device.
## Logs
Launching lib\main.dart on a GIONEE M5 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2InternalException: AAPT2 aapt2-3.2.1-4818971-windows Daemon #0: Daemon startup failed
  This should not happen under normal circumstances, please file an issue if it does.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

```
```

```
```

**Comment by iapicca** [comment]
Hi @ayodelesalimon 
can you please provide your updated  `flutter doctor -v`
and your `flutter build --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by ayodelesalimon** [comment]
My Flutter Doctor

`C:\Users\user\Documents\EGDownloads\flutter_windows_v1.9.1+hotfix.6-stable\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\Users\user\Documents\EGDownloads\flutter_windows_v1.9.1+hotfix.6-stable\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:/Users/user/AppData/Local/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:/Users/user/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.0

[√] Connected device (1 available)
    • TECNO P701 • 023111084O003268 • android-arm • Android 7.0 (API 24)

• No issues found!
Process finished with exit code 0`

**Comment by iapicca** [comment]
Hi again @ayodelesalimon 
thank you for providing you `flutter doctor -v`.

Could you please provide also your `flutter build --verbose`
and  a minimal code sample?
Thank you

**Comment by ayodelesalimon** [comment]
> Hi again @ayodelesalimon
> thank you for providing you `flutter doctor -v`.
> 
> Could you please provide also your `flutter build --verbose`
> and a minimal code sample?
> Thank you

Launching lib\main.dart on TECNO P701 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by iapicca** [comment]
Hi @ayodelesalimon 
what you posted doesn't look like a `flutter build --verbose`,
could you please try again?
Before that, please run 
`
 flutter channel stable
`
`
 flutter upgrade
`
thank you

**Comment by gawdevishal** [comment]
@ayodelesalimon 
Try Migrating your Project to androidX
https://flutter.dev/docs/development/androidx-migration

Note: Open the "android" directory inside your Flutter Project before migrating.
