### ISSUE TITLE
On the new build dashboard decorate devicelab tests that can be flaky without breaking the build

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#46283]
## Use case

I reverted https://github.com/flutter/flutter/commit/adec6977be800690d81cfc81cd07eb5037f4317f because I thought it had broken the build, but it was marked `isFlaky` in the manifest.  In the new dashboard there's no difference between failing and "flakable" (tree still open), and just failing.

## Proposal

Make these two cases visually different.

**Comment by CaseyHillers** [comment]
![image](https://user-images.githubusercontent.com/2148558/70822498-90345180-1d92-11ea-83f4-3dea74eaacf7.png)

The build dashboard shows a question mark on a task that is marked flaky. The material icons may have failed to download if there was no visual indicator for the difference in a task and a flaky task.

**Comment by jmagman** [comment]
Hm, I don't think I saw a "?" at the time, but now I do.
Can we add some "Flaky: true" text to the menu?
![Screen Shot 2019-12-17 at 11 28 11 AM](https://user-images.githubusercontent.com/682784/71027580-5def6080-20c0-11ea-967f-3d992ba0730a.png)
