### ISSUE TITLE
Animated webps with n loops actually runs n+1 loops

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#46289]
Animated webps with a specified number of loops will actually run n+1 loops.  This is 100% reproducible with the version of Flutter I am on.

## Steps to Reproduce
1. Clone this repo https://github.com/KevinTheGray/aweb_bug
2. Run the app on any device
3.  Observe the top webp loops infinitely as expected (loop count of 0 specified), the second webp incorrectly loops twice (loop count of 1 specified), the third webp incorrectly loops three times (loop count of 2 specified).

**Target Platform:** Android/iOS/macOS
**Target OS version/browser:** macOS 10.14.5 (18F132)
**Devices:**  Happens on desktop as well as any simulator/emulator and physical device

```
[✓] Flutter (Channel master, v1.12.16-pre.35, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.12.16-pre.35 at /Users/KG/Developer/Flutter/flutter
    • Framework revision b9a56b9f48 (7 days ago), 2019-11-29 20:40:44 -0500
    • Engine revision 8672e79af8
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.7.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4892.25

[!] VS Code (version 1.35.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone 5s  • 9288B215-C389-4B17-B00A-8C9303B53F4D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac OS X 10.14.5 18F132
    • Chrome     • chrome                               • web-javascript • Google Chrome 78.0.3904.108
```

**Comment by ditman** [comment]
> Run the app on any device

`flutter run -d chrome` seems to work as expected!

**Comment by ditman** [comment]
Seems related to this:

* https://github.com/flutter/flutter/issues/45246

**Comment by amirh** [comment]
The repetitionCount number is fetched from SkCodec's getRepetitionCount count:

https://github.com/flutter/engine/blob/f5250ec9b1ef54a6357a8d5ef2ad164270b727f2/lib/ui/painting/multi_frame_codec.cc#L17

The contract for `getRepetition` count is to return the number of times to repeat the animation (not including the first play): [Skia docs](https://github.com/google/skia/blob/3d1a3bb4bb1812fb04b23b3448a7574a195cd640/include/codec/SkCodec.h#L695).

According to the information in https://github.com/KevinTheGray/aweb_bug it seems like we're SkCode c is counting the first play for webps (but not for GIFs). So this seems like a bug in SkCodec for webp.

**Comment by chinmaygarde** [comment]
I tried looking at the `2-loop.webp` in Chrome on Mac (Version 78.0.3904.108) and that seemed to [loop three times as well](https://youtu.be/SLdGV7vyQC8). The report does indicate that this was not an issue in an unspecified version of Chrome. It could be that we need to update our libwebp dependency and this has been fixed upstream. The version we use 0.6.0 while the latest is 1.0.3. The build rules 1.0.3 seem significantly different though and I didn't find the roll trivial.

**Comment by chinmaygarde** [comment]
* 1.0.3 seems to exhibit the same issue as well so it is not the libwebp codec dependency.
* `webpinfo` says loop count is 2.
* Skia [treats `WEBP_FF_LOOP_COUNT`](https://github.com/google/skia/blob/3d1a3bb4bb1812fb04b23b3448a7574a195cd640/src/codec/SkWebpCodec.cpp#L223) as the repetition count.
* Treating the loop count as the repetition count [breaks Skia's documented behavior](https://github.com/google/skia/blob/3d1a3bb4bb1812fb04b23b3448a7574a195cd640/include/codec/SkCodec.h#L695) of not treating the first frame as being part of the repetition.

This looks like an issue with SkWebPCodec that is still present in Chrome. The fix is simple enough but I am not sure about the consequences for dependencies other than Flutter. We could special case WebPs in Flutter for repetition count but then Flutter would be susceptible to this breaking on us when Skia fixes the behavior.

@KevinTheGray Are you sure this works for you in Chrome as mentioned in the README in the reproducible test case? I am not able to reproduce the same. I just dragged the file into Chrome to open it.

**Comment by chinmaygarde** [comment]
This item from Blink Reviews seems to indicate that other browsers are trying to match Chrome's behavior:
* [WebP animation: Loop once more than stored loop count.](https://groups.google.com/a/chromium.org/forum/#!msg/blink-reviews/1VZrZ41UTTU/cot3BycWAgAJ)

**Comment by Hixie** [comment]
we should match the spec. if we decide that the spec is wrong, then we should get it changed.

**Comment by chinmaygarde** [comment]
> we should match the spec

Spec is fine. Just that Chrome & Flutter are not following it. Firefox seems to be doing the right thing as well. I'll author a Skia patch.

**Comment by chinmaygarde** [comment]
xref https://skia-review.googlesource.com/c/skia/+/258680

**Comment by chinmaygarde** [comment]
This has been patched and Skia commit has rolled into Flutter Engine. https://github.com/flutter/engine/pull/14321#issue-351706140 adds a test for this in the engine.
