### ISSUE TITLE
Dashboard can consider measuring APK size of `flutter create`'s output

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4629]
When measuring and tracking the size of Flutter's generated APKs, we might want to look at measuring the APK size of the output of `flutter create`. We're using the gallery now, but looking at our starter app has a few advantages:

* less optional assets
* more consistent codebase
* smaller code (so we'll see regressions in compiled size more often)

**Comment by sethladd** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
Fixed.

<img width="464" alt="screen shot 2016-09-28 at 6 11 07 pm" src="https://cloud.githubusercontent.com/assets/211513/18937644/fa5d1966-85a6-11e6-9b1a-3be6e9fda083.png">
