### ISSUE TITLE
Popping showModalBottomSheet rebuilds UI

### ISSUE THREAD

**Issue by FriendlyNeighbor** [flutter/flutter#46301]
I am showing a modal similar to Instagram's adding a comment. It's a modal that only occupies nearly half of the screen.

The "rebuild" actually happens when I tap on the field to show the soft keyboard.
Then when I tap on the area outside the modal, the "rebuild" also happens.

```
[√] Flutter (Channel unknown, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\Users\Claude\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Claude\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Claude\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • RMX1971 • 2674c2c • android-arm64 • Android 9 (API 28)
```

**Comment by iapicca** [comment]
Hi @FriendlyNeighbor 
can you please provide a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by zoeyfan** [comment]
Unfortunately there isn't enough information on this bug to reproduce the issue. Closing for now. 

If you are still experiencing this issue, you're welcome to reopen it. Please tell us exactly how to reproduce the problem you're running into. Attach a small sample that demonstrates the issue, or include the specific tool commands that reproduce the problem along with the results of running `flutter doctor -v`. 

Thank you for using Flutter!
