### ISSUE TITLE
android/ folder is required for non-android plugins

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#46304]
Applications that include non-android plugin packages (e.g a web-only plugin package) are failing to build for Android.

This regressed in https://github.com/flutter/flutter/pull/45379 and is fixed in https://github.com/flutter/flutter/pull/46282

Unfortunately there have been a few releases between the regression and the fix (as of writing v1.12.10 .. v1.13.0 all have the bug).

To make plugins work in the bad build range we're including a temporary `android/` folder in non-android plugins. Once the fix makes it to a stable release plugins can bump the minimal Flutter constraint and cleanup their no-op android folder.

Keeping this open until the fix makes it to a stable release.

@blasten @hterkelsen @ditman

**Comment by mit-mit** [comment]
I think this is fine as long as we only do this to plugins where we use the explicit platform tags to specify that the plug-in does *not* support Android. That way we can remove the folder again later.

**Comment by cyanglaz** [comment]
can we do the necessary work to close this issue now since the new stable is released?

**Comment by blasten** [comment]
@cg021 it should just be reverting https://github.com/flutter/plugins/pull/2403 and https://github.com/flutter/plugins/pull/2408, then publishing a patch in each of these plugins.

**Comment by creativecreatorormaybenot** [comment]
@blasten @cg021 @amirh I think this does not work for Android AAR's 😐 It looks like you have broken some builds with this to me because `flutter build aar` fails for any projects that use any of the changed plugins.

**Comment by blasten** [comment]
If you are on the latest stable, this issue can be solved by just running `flutter clean` and then `flutter build aar`. 

Flutter clean will delete the `.android` directory, and then `flutter build aar` will regenerate a new `.android` directory that includes an updated version of `include_flutter.groovy`.

**Comment by kw2019ltd** [comment]
flutter create project generate setting.gradle as below

include ':app'

def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
def properties = new Properties()

assert localPropertiesFile.exists()
localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

def flutterSdkPath = properties.getProperty("flutter.sdk")
assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"



pls update it with old way like
