### ISSUE TITLE
Connectivity and path_provider should use the canonical federation folder structure

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#46307]
A federated plugin in `flutter/plugins` should have a root folder, with each package as a subfolder, e.g:

```
url_launcher/url_launcher
url_launcher/url_launcher_platform_interface
url_launcher/url_launcher_web
```

cc @mklim

**Comment by franciscojma86** [comment]
`connectivity_macos` is now endorsed 🎉

**Comment by franciscojma86** [comment]
Working on endorsing `path_provider`. Steps are:
- [ ] Move all package contents to a `path_provider` package, that is a sibling of `path_provider_macos` and other platforms
- [ ] Create a `path_provider_platform_interface` and migrate the APIs
- [ ] Update the core plugin to use the platform interface
- [ ] Endorse the macos platform
