### ISSUE TITLE
'flutter run test/widget_test.dart' breakpoint debugging?

### ISSUE THREAD

**Issue by GanZhiXiong** [flutter/flutter#46323]
How do I debug breakpoints after executing the following command？
`flutter run test/widget_test.dart`

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
