### ISSUE TITLE
[web] HTML Renderer doesn't render border

### ISSUE THREAD

**Issue by andredealmei** [flutter/flutter#46339]
### Doctor
[√] Flutter (Channel master, v1.13.1-pre.59, on Microsoft Windows [versÃ£o 10.0.17763.864], locale pt-BR)
• Flutter version 1.13.1-pre.59 at C:\flutter
• Framework revision e58dc16 (8 hours ago), 2019-12-06 18:21:52 -0800
• Engine revision e7b69ced2e
• Dart version 2.7.0 (build 2.7.0-dev.2.1 a9c77229c2)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at C:\Users\usuario\AppData\Local\Android\sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.2
• Java binary at: C:\android-studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
• All Android licenses accepted.

[√] Chrome - develop for the web
• Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 4.0)
• Android Studio at C:\android-studio
X Flutter plugin not installed; this adds Flutter specific functionality.
X Dart plugin not installed; this adds Dart specific functionality.
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.40.2)
• VS Code at C:\Users\usuario\AppData\Local\Programs\Microsoft VS Code
• Flutter extension version 3.7.0

[√] Connected device (2 available)
• Chrome • chrome • web-javascript • Google Chrome 78.0.3904.108
• Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

### Code:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.green,
      appBar: AppBar(),
      body: Padding(
        padding: const EdgeInsets.all(30),
        child: ListView.separated(
          itemCount: 30,
          itemBuilder: (BuildContext context, int index) {
            return ListTile(
              title: Text('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'),
            );
          },
          separatorBuilder: (BuildContext context, int index) => const Divider(
            color: Colors.red,
          ),
        ),
      ),
    );
  }
}
```
### Issue:
Divider not render in some cases, on the exemple code  divider not render.
on canvas back end (--dart-define=FLUTTER_WEB_USE_SKIA=true) works fine

**Comment by andredealmei** [comment]
is possible to see divider if you wrap with a cointainer with  color 

` Container(
            color: Colors.blue,
            child: const Divider(
              color: Colors.red,
            ),
          ),`

**Comment by iapicca** [comment]
Hi @andredealmei 
I've tested this code
https://dartpad.dartlang.org/277fa1b7d951c479991039a5b2bc283a
with this flutter version 

<details>
  <summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel dev, v1.13.0, on Microsoft Windows [Version 10.0.19013.1122], locale en-US)
    • Flutter version 1.13.0 at C:\src\flutter
    • Framework revision 09126abb22 (5 days ago), 2019-12-03 17:43:00 -0800
    • Engine revision 6179380243
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a4d799c402)

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\iapic\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)        
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.40.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

</details>

and works just fine.

I believe the issue might be the `thickness `of the `Divider`;
does this solution solve the issue?
Thank you

**Comment by andredealmei** [comment]
but on mobile (android native), canvaskit and desktop , we dont need to set thickness  , why on web ?

**Comment by andredealmei** [comment]
u can see more on https://github.com/flutter/flutter/issues/46562

**Comment by iapicca** [comment]
Hi again @andredealmei 
thank you for the clarification

**Comment by 5hanth** [comment]
![Screenshot_20200119-183357_Chrome](https://user-images.githubusercontent.com/4287700/72681509-53265200-3aea-11ea-9195-a05ea7e92c9f.jpg)

Yes `ListView.separated(..)` on web looks weird.

**Comment by davystrong** [comment]
I have noticed a similar problem, however mine shows normally until I move my mouse over the Chrome window they disappear. However, setting a thickness also solved the problem.

**Comment by aliyazdi75** [comment]
Also `Divider.createBorderSide(context)` is not working on flutter web but in another devices already works.

**Comment by dimitris1pana** [comment]
You should increase dividers thickness
eg. Divider(thickness:2,);

**Comment by Hixie** [comment]
@dimitris1pana That's a work-around, but we need to fix Flutter so that it works without it too. :-)

**Comment by caioaletrocadock** [comment]
Same issue here. Only discovered because I tried on Android emulator and just works fine.
The workaround works too, you only need to explicity set a thickness to the Divider.
Waiting for a proper fix.

**Comment by NickNevzorov** [comment]
Same issue here on Web platform
The workaround works too, you only need to explicity set a thickness to the Divider.

**Comment by talent-apps** [comment]
Any update on this?

**Comment by rydmike** [comment]
I just wanted to add to this issue, that the default Divider() seems to work when building Flutter Web apps using CanvasKit, but when using DomCanvas, it does not always (seldom) show up, at least not if it has just been added with all default constructor values.

Here is a live example: https://rydmike.github.io/maskfilterskia/#/
built for CanvasKit using: 
`flutter run --release --dart-define=FLUTTER_WEB_USE_SKIA=true -d Chrome`
It contains three default Divider()'s and they show up nicely.

This is the exact same code and demo: https://rydmike.github.io/maskfilterdom/index.html#/
but built for DomCanvas with just default:
`flutter run --release -d Chrome`
The dividers cannot be seen.

The code for this demo can be found in this Gist:
https://gist.github.com/rydmike/78cdff7f63515a9ea18f172b8640de55

This example was actually created to demonstrate another issue (https://github.com/flutter/flutter/issues/58546), but I noticed the Divider difference on the builds and searched for a known issue and found this case. I just wanted to add that I observed different Divider behavior using CanvasKit and DomCanvas.

The above live examples were built with version `Channel master, 1.19.0-4.0.pre.24`
Results might be different with other versions

**Comment by pbakondy** [comment]
Divider visibility issue still exists with latest beta (1.25.0-8.1.pre)
Simple test based on tutorial:
https://dartpad.dev/b68c042631ce7e78bf46af61c0e05142?

**Comment by flutterq** [comment]
Step By Step Guide to [flutter - vertical divider](https://flutterq.com/wp-admin/post.php?post=251&action=edit)

**Comment by raphael-bmec-co** [comment]
Hello

Is there a time frame on this? It's on this card but it looks like there hasn't been any activity for years? https://github.com/flutter/flutter/projects/156#card-40120733

It is making many many widget unusable.

**Comment by YannBcf** [comment]
Issue still present in flutter 2.10.3

**Comment by SittiphanSittisak** [comment]
Any update?
Now I am using `Container(color: ColorStyle.mute, height: 1, child: Row()),`.
Are these same?

**Comment by SittiphanSittisak** [comment]
Any update?
Now I am using 
`Container(color: Colors.grey, height: 1, child: Row())`.
Are these same?

**Comment by huycozy** [comment]
Hi everyone, I update the issue on the latest `stable` and `master` channels; 
Updating the title as well due to the issue is related to `BorderSide`.

<details>
<summary>Demo</summary>

| HTML | Canvaskit |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/179696264-7cb9acd4-edea-4aef-a907-86a49c2c4742.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/179696278-25898af6-8771-4587-93d7-557141067e01.png">

</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.green,
      appBar: AppBar(),
      body: Padding(
        padding: const EdgeInsets.all(30),
        child: ListView.separated(
          itemCount: 30,
          itemBuilder: (BuildContext context, int index) {
            return ListTile(
              title: Text('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'),
            );
          },
          separatorBuilder: (BuildContext context, int index) => const Divider(
            color: Colors.red,
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.5 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 hours ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1718, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.1.0-0.0.pre.1718 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a1e4cfad5e (2 hours ago), 2022-07-18 21:55:40 -0400
    • Engine revision efc604ee62
    • Dart version 2.19.0 (build 2.19.0-6.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
