### ISSUE TITLE
[bottom_sheet] modal barrier color should be configurable

### ISSUE THREAD

**Issue by thethirduniverse** [flutter/flutter#46363]
## Use case

See this line: https://github.com/flutter/flutter/blob/e58dc16d7bec7199190f1408667e24e38328cc3b/packages/flutter/lib/src/material/bottom_sheet.dart#L373

This line hard-codes the modal barrier color to `Colors.black54`, which is not configerable and offers no way for users to change it.

### Simple solution:
1. Define and propagate another argument `barrierColor` just like `barrierLabel`.
2. If user provided a `barrierColor`, use that color, otherwise use `Colors.black54` as fallback.

### More proper solution
The barrier color should be a configerable part of the ThemeData (https://api.flutter.dev/flutter/material/ThemeData-class.html). That way we can avoid passing down parameters explicitly and only rely on the `context`.

**Comment by sglim** [comment]
I agree that.

**Comment by athornz** [comment]
@iapicca I think this can be closed now.

There is now a `barrierColor` property when calling `showModalBottomSheet` that allows customising the barrier color.

**Comment by iapicca** [comment]
Hi all
thank you for bringing this to my attention @athornz 

Closing
if you disagree please write in the comments and I will reopen it
Thank you
