### ISSUE TITLE
[web] shared_preferences getInstance() never finishing

### ISSUE THREAD

**Issue by jld3103** [flutter/flutter#46365]
I was trying to use the new `shared_preferences` web implementation from @yjbanov, but I didn't it to work. Calling `await SharedPreferences.getInstance()` never finishes.
(The README of shared_preferences_web states that the plugin should work like normal, but it obviously doesn't)
There already is #43943, but that is not a duplicate, because when that issue was opened no web implementation existed.

**Comment by yjbanov** [comment]
I was unable to reproduce this on a sample project.

These are my `pubspec.yaml` dependencies:

```yaml
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 0.5.4+8
  shared_preferences_web: 0.1.0
```

This is the app code (the UI is not interesting for the purposes of this test):

```dart
void main() async {
  print('>>> await SharedPreferences.getInstance()');
  final prefs = await SharedPreferences.getInstance();
  print(prefs.getString('greeting'));
  print(await prefs.setString('greeting', 'hello world ${math.Random().nextInt(10000)}'));
  print(prefs.getString('greeting'));
  runApp(MyApp());
}
```

Can you please provide the output from `flutter doctor -v`, your `pubspec.yaml` and a minimal Dart sample that reproduces this?

**Comment by jld3103** [comment]
I upgraded flutter and did a `flutter pub upgrade` and now it works. I was using `shared_preferences_web` directly from git so maybe that was the issue?

**Comment by yjbanov** [comment]
Could be
