### ISSUE TITLE
can't focus textfield in alertdialog

### ISSUE THREAD

**Issue by wrjcs** [flutter/flutter#46360]
Hello,
I have a problem when I put a textfield in alertdialog,
the textfield can't have the focuse.

```dart
showDialog(
 context: context,
barrierDismissible: true,
builder: (context) {
return AlertDialog(                            
contentPadding: EdgeInsets.fromLTRB(20, 10, 20, 10),
title: Text('客户列表'),
content: 
      Container(
        width: 600,
        height: 500,
        child: Column(
          children: <Widget>[
            TextFormField(
              autofocus: true,
                decoration: InputDecoration(
                    labelText: "Search",
                    contentPadding: EdgeInsets.all(4),
                    suffixIcon: Icon(Icons.search),
                    border: OutlineInputBorder(
                        borderRadius: BorderRadius.all(Radius.circular(5.0)))),
            ),
            
          ],
        ),),
                          );
                        });
```

**Comment by wrjcs** [comment]
this is the result of flutter -v
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [version 10.0.18362.476], locale fr-FR)
    • Flutter version 1.9.1+hotfix.6 at D:\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Users\user\AppData\Local
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Users\user\AppData\Local
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • T2lite • 192.168.1.101:5555 • android-arm64 • Android 7.1.1 (API 25)

! Doctor found issues in 2 categories.

**Comment by iapicca** [comment]
Hi @wrjcs 
does this code represent the issue you are describing?

<details>
  <summary>code sample</summary>

``` dart 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context)=> MaterialApp(
    home: HomePage(),
  );
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  TextEditingController _controller1;
  TextEditingController _controller2;
  FocusNode _node1;
  FocusNode _node2;

  @override
  void initState() {
    _node1 = FocusNode();
    _node2 = FocusNode();
    _controller1 = TextEditingController();
    _controller2 = TextEditingController();
    super.initState();
  }

  @override
  void dispose() {
    _node1.dispose();
    _node1 = null;
    _node2.dispose();
    _node2 = null;
    _controller1?.dispose();
    _controller1 = null;
    _controller2?.dispose();
    _controller2 = null;
    super.dispose();
  }

  Future<void> _showDialog(BuildContext context) => showDialog(
      context: context,
      barrierDismissible: true,
      builder: (context) => AlertDialog(                            
      contentPadding: EdgeInsets.fromLTRB(20, 10, 20, 10),
      title: Text('hello world'),
      content: Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: <Widget>[
          TextField(
            controller: _controller1,
            focusNode: _node1,
            onSubmitted: (_)=> FocusScope.of(context).requestFocus(_node2),
          ),
          TextField(
            controller: _controller2,
            focusNode: _node2,
            onSubmitted: (_)=> FocusScope.of(context).requestFocus(_node1),
          ),
        ],
  ),),),);

  @override
  Widget build(BuildContext context) => Scaffold(
    floatingActionButton: FloatingActionButton(
      onPressed: ()=> _showDialog(context),
    ));
}
```

</details>

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
