### ISSUE TITLE
Add option to change UserAgent in video_player plugin

### ISSUE THREAD

**Issue by balvinderz** [flutter/flutter#46378]
Earlier i made an android app  which plays video from m3u8 links . 
I used ExoPlayer to play m3u8 Links .
I was getting httpSourceError so i had to change User Agent in DataSourceFactory to make it work like this.

`  DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context,
                    Util.getUserAgent(context, "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_8; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Chrome/4.0.249.0 Safari/532.5"));`.
Now i was trying to make the same app in flutter and i faced the same issue but there was no option to change UserAgent in video_player plugin. Can you guys expose this User Agent Variable to video_player plugin  ?

**Comment by penniath** [comment]
"ExoPlayer" is kind of odd User-Agent value.
Maybe this feature could allow us to configure the player in order to avoid server rejections.

By the way, does anyone know which is the current User-Agent iOS version makes requests with?

**Comment by haracena** [comment]
> Earlier i made an android app which plays video from m3u8 links .
> I used ExoPlayer to play m3u8 Links .
> I was getting httpSourceError so i had to change User Agent in DataSourceFactory to make it work like this.
> 
> ` DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_8; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Chrome/4.0.249.0 Safari/532.5"));`.
> Now i was trying to make the same app in flutter and i faced the same issue but there was no option to change UserAgent in video_player plugin. Can you guys expose this User Agent Variable to video_player plugin ?

Did you find any solution for this issue?

**Comment by balvinderz** [comment]
you will have to write java/kotlin code for now .

**Comment by stuartmorgan** [comment]
This was implement recently; setting a user agent header in the request will now change the exoplayer user agent.
