### ISSUE TITLE
Excessive logging of checkUser error in Atom Editor

### ISSUE THREAD

**Issue by midoringo8823** [flutter/flutter#4638]
## Steps to Reproduce

Deploy a flutter app to my android device
## Flutter Doctor

[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/midoringo/flutter
    • Framework revision 833b121664 (3 days ago), engine revision c69d907b49

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/home/midoringo/Android/Sdk
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-123992248-123972143)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.26
## Logs and Crash Reports

The log keeps printing this: "E/ActivityManager: checkUser: useridlist=null, currentuser=0".  And I'm not able to see any useful logs

**Comment by sethladd** [comment]
We've moved on to IntelliJ
