### ISSUE TITLE
Support for Material Design "Chips"

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#464]
http://www.google.com/design/spec/components/chips.html

![Material Design Chip example](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B7WCemMG6e0VV21LOUp1OGdrRTg/components_acux_chips_chipstxticon.png)

**Comment by abarth** [comment]
Basic support in https://github.com/flutter/flutter/pull/550
