### ISSUE TITLE
Small performance optimizations

### ISSUE THREAD

**Issue by bayezid75** [flutter/flutter#46400]
I found in the Flutter SDK lines that can improve the performance a bit. They would not change the speed 10 times more, but it would help to work less the cpu and battery usage from mobiles would get better.

In found in many files something like:
`dart for(int x=0; x < mylist.length; x += 1)`

The problem here is that we're using lists with maybe much elements and the loop has to calculate everytime the size again, and again, and again...

Maybe we should use cached variables like:
`for(int n=mylist.length, x =0, x < n; x += 1)`

The datatype double is used many times, but not only for floating numbers. Use int's. They don't need so much capacity like doubles.

I don't know if it should improve the Dart-System, but would Arrays be not better as Lists? I saw many Widgets get initialized with many attributes and they get added in lists. But the size if attributes get not changed only the content.
Array are much smaller.

**Comment by iapicca** [comment]
Hi @bayezid75 
I'm not sure to understand your proposal
given an sample code

<details>
  <summary>sample code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context)=> MaterialApp(
    home: HomePage(),
  );
}

class HomePage extends StatelessWidget {
  static const List<int> myList= [1,2,3,4,5,];

  @override
  Widget build(BuildContext context) => Scaffold(
    body:ListView(
          children: <Widget>[for (int i = 0; i<myList.length; ++i) Text('$i'),],
  ),);
}
```

</details>
your assertion is that  this code

`[for (int i = 0; i<myList.length; ++i) Text('$i'),]` 
is less performance optimized than  `for(int n=mylist.length, x =0, x < n; x += 1)`, 
lets assume that you are right;

what's the difference from doing this

```dart 
  static const List<int> _list = [1,2,3,4,5,];
  static final int _listLenght = _list.length;
```
```dart 
 [for (int i = 0; i<_listLenght; ++i)  Text('$i'),]
```

also consider this possibility

`for (int i in _list) Text('$i')`

Does this possible solution answer your question?
thank you

**Comment by bayezid75** [comment]
Yeah it's the same form that I wrote. Cached Loops are much performanter as normal loops.
I saw the Flutter SDK has many loops with not cached Loops.

Here is an example for C# (because I'm C# Developer):
https://jacksondunstan.com/articles/3577

**Comment by iapicca** [comment]
Hi again @bayezid75 
clarified that what you are proposing  
is already available in Dart and Flutter
I feel safe to close this issue.

if you disagree please write in the comments and I will reopen it
Thank you

**Comment by bayezid75** [comment]
I know that you can do this via Dart.
But the Flutter SDK doesn't contains it. I found many files in the libs that use not the cached Loop.

**Comment by liyuqian** [comment]
@bayezid75 : do you have a benchmark that quantifies the performance difference between those 2 loops?

@a-siva : from Dart VM's perspective, how significant do you think the difference would be? If it's significant, we could change as many loops as possible in Flutter's codebase.

**Comment by mraleph** [comment]
> @a-siva, @mraleph : from Dart VM's perspective, how significant do you think the difference would be?

Depends on many factors. I would classify this as a micro-optimization which should only matter in a very tight loops, so I would prefer readability in this particular case. 

Two situations are possible:

-  We know the concrete type of the list (e.g. TFA inferred it for us) so we are able to fully devirtualize and inline `list.length`. In this case accessing length is just a single memory load. 

- We don't know concrete type of the list: in this case `list.length` is a call, the actual function implementing `get length` for Dart's builtin lists will be just a memory load and return (couple of instructions). 

So in the second case you will be able to reduce amount of calls in the loop, but it would only matter if the rest of the loop is very tight.  

@bayezid75 

> I don't know if it should improve the Dart-System, but would Arrays be not better as Lists? 

Dart List's are essentially arrays and not linked lists (as you might think from based on the name).

**Comment by bayezid75** [comment]
I tested it now on the website [jDoodle](https://www.jdoodle.com/execute-dart-online/) (it means lower CPU-Jobs, I know it) with the following code:

```
void main() {
  var sum = 0;
  List<int> liste = new List(30);

  var x1 = DateTime.now().millisecondsSinceEpoch;
  for(int i = 0; i < liste.length; i++)
    sum += fib(i);

  print(sum);
  var x2 = DateTime.now().millisecondsSinceEpoch;
  print(x2-x1);
  sum = 0;
  int length = liste.length;
  var x3 = DateTime.now().millisecondsSinceEpoch;
  for(int i = 0; i < length; i++)
    sum += fib(i);

  print(sum);
  var x4 = DateTime.now().millisecondsSinceEpoch;
  print(x4-x3);
}

int fib(int n){
  return n < 2 ? n : (fib(n-1) + fib(n-2));
}
```

And got these results:

> 1346268
> 16
> 1346268
> 13

You see we have a difference of 3. I tested it only with 30 elements, because the Online Compiler are not able to do more work with more elements and the fibbonacchi algorithm. Yeah I choosed this one, to show the difference by hard calculations with low count of elements.
Now imagine you have 1.000.000 elements. The difference would be enormous.

I know it would not make a gigantic difference, but when have the chance to improve the environtment a bit more then we should do this.

Dito.

**Comment by mraleph** [comment]
@bayezid75 that's not the right way to measure things, for multiple reasons. First of all you are measuring JIT performance, while Flutter applications are mostly AOT compiled. If you are measuring JIT you need to give it a chance to warm up - otherwise you will observe strange effects. Take your benchmarks, rename `main` to `main2` and add a `main` like this:

```
void main() {
  main2();
  main2();
  main2();
}
```

You will get results like this:

- for the first benchmark

```
1346268
26
1346268
13
1346268
13
1346268
14
1346268
15
1346268
19
```

- for the second benchmark

```
41666541666641790.0
21
41666541666641790.0
7
41666541666641790.0
13
41666541666641790.0
6
41666541666641790.0
6
41666541666641790.0
7
```

Suddenly the cached length is slower than uncached 😮 

(there will also be certain flakiness in the numbers)

**Comment by bayezid75** [comment]
Hm... you're right. I don't included AOT.

We can close this issue then. Thanks 👍
