### ISSUE TITLE
paste image into textfield

### ISSUE THREAD

**Issue by jibbers42** [flutter/flutter#46418]
## Use case
Specifically, to "paste" image using Bitmoji Keyboard.

According to Bitmoji:
```
Q: Why can’t I paste a Bitmoji into my messaging app?

A: Bitmoji for Gboard is compatible with any messaging app that supports pasting an image from the keyboard to the text field.

If you are unable to paste a Bitmoji into the text field, it’s likely that the messaging app you’ve selected does not support image pasting.
```
Using the Bitmoji Keyboard in Discord is a good example of what I'm after.

## Proposal
I'm not a native developer so frankly I'm not sure how this is handled in iOS and Android, but my guess is that they provide a callback you can set to handle a paste depending on content type.

I'd like to be able to provide a function to the Textfield to handle a paste event and do something with the data depending on its content type.

**Comment by ykaito21** [comment]
Being able to insert inline image into TextField is what I want too.

**Comment by ltOgt** [comment]
Related: https://github.com/flutter/flutter/issues/20796

**Comment by justinmc** [comment]
Also related: https://github.com/flutter/flutter/issues/67857

**Comment by gnprice** [comment]
Now that https://github.com/flutter/flutter/issues/20796 is done, does that cover this request? Or is there something separate to be done for this?

**Comment by jibbers42** [comment]
Possibly, when/if I get back around to this I'll reopen or create a new issue if I have trouble.
