### ISSUE TITLE
Put @required on "child" argument of Widgets that need it

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4642]
An argument X of type `Widget` in a subclass W of `Widget` is not required if:
- W is a `RenderObjectWidget`
- W's build function does not use X when X is null.
- W's build function uses X as an argument to a constructor of another `Widget` subclass, and that argument is itself not required.

In all other cases, an argument of type `Widget` in a subclass `Widget` should be required.

**Comment by Hixie** [comment]
I did all of Widgets. Still need to do material/.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/7730 https://github.com/flutter/flutter/pull/7732

**Comment by a14n** [comment]
I just notice this issue and reviewing the 2 PR I see `@required` added but no `assert(xxx !=null)`. I make a quick test with one of the Widget modified (`Title`) and it looks like `null` is not accepted (`new Title(child: null)` in my test throw an exception).

Should an `assert(xxx != null)` be added where the `@required` had been added ?

**Comment by Hixie** [comment]
In general yes but it's not a hard and fast rule. For example, `onPressed` is often @required but is allowed to be null.

**Comment by a14n** [comment]
I was mainly thinking about `child` parameter.
