### ISSUE TITLE
dart:io problem in Android VM.

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#4643]
using the dart:io package, reading a file 
```
final content = await file.readAsString(); 
```
resolves to a Future<String> instead of a String.
it works correctly on iOS, but not on Android.

**Comment by eseidelGoogle** [comment]
We'll need to try and repro and then hand off to the VM team if we can.  @johnmccutchan @jason-simmons @DaveShuckerow can point you to an internal (larger) app which demonstrates this if necessary.  Odd that it only repos on android.

@DaveShuckerow were you using --debug, --release on either?  Were these on devices or simulators?

**Comment by eseidelGoogle** [comment]
I've created an example using a modified version of @DaveShuckerow's code which does not repro for me on the iOS simulator or Genymotion emulator (Nexus 5X):
https://github.com/flutter/flutter/commit/2cea20512ccfc1843eb29f2ee47e27791da5ee35

**Comment by DaveShuckerow** [comment]
I encountered this on a physical Nexus 5X.  I believe it was in --release mode.

**Comment by eseidelGoogle** [comment]
@DaveShuckerow tried my above example on a physical Nexus 5 in both --debug and --release and it did not repro. :/

**Comment by eseidelGoogle** [comment]
Neither @DaveShuckerow or I are able to repro, closing.
