### ISSUE TITLE
Text is show incomplete when run in web app

### ISSUE THREAD

**Issue by baxiaxx** [flutter/flutter#46440]
when the Text is set maxLines,the Text cannot show all content in web app,just must set the height(TextStyle(height: 1.5)),it will work done,this is mybe need to optimize.

**Comment by iapicca** [comment]
Hi @baxiaxx 
does this code represent the issue you are describing?
<details>
  <summary>code sample</summary>

```dart 
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatelessWidget {

static const String _lorenIpsum = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec iaculis orci vel tempor dignissim. Praesent nisl neque, iaculis et euismod ut, dignissim non arcu. In vel convallis mauris, a viverra turpis. Curabitur ac erat pulvinar, mattis nisl eu, placerat risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis cursus, nisi eu molestie vulputate, libero tellus convallis purus, id cursus sapien orci at velit. Duis placerat et massa et molestie. Quisque id elit blandit, tempor nulla non, faucibus ex. Pellentesque elementum cursus neque, vitae ultricies massa molestie nec. Morbi a eros finibus, sagittis mi eget, gravida.';

@override
  Widget build(BuildContext context) => Scaffold(
    body:  Column(
      mainAxisAlignment: MainAxisAlignment.center,
      crossAxisAlignment: CrossAxisAlignment.center, 
      children: <Widget>[
        Text(_lorenIpsum,
          maxLines: 2,
          style: TextStyle(
            height: 2,
        ),),
        Container(height: 40,),
        Text(_lorenIpsum,
          maxLines: 2,
        ),
  ],),);
}
```
</details>

I'm not experiencing the issue you are describing in the latest `flutter channel dev`
could you please provide your `flutter doctor -v`?
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
