### ISSUE TITLE
Flutter ignores Dart Entrypoint when using flavors on iOS

### ISSUE THREAD

**Issue by Tahaan** [flutter/flutter#46462]
Short description:
Flutter run launches the wrong dart entrypoint under certain circumstances.

The problem occurs when having flavors with separate dart entrypoints on iOS.  It is consistently reproduceable.

## Steps to Reproduce

Sample Project: git@github.com:Tahaan/flutter-flavor-test.git

Steps to reproduce:
1. Create a Flutter app (Default template is sufficient to reproduce)
2. Add at least one Flavor with a distinct Dart EntryPoint
3. This entrypoint needs to change something visible in the app to allow you to distinguish which entry point was actually called.  In my example I just changed the color of one element when the alternative dart entrypoint was called.
4. Set up XCode to assign a distinct Bundle Identifier to this Flavor via a corresponding XCode Configuration set.
5. Launch the un-flavored version of the app - all looks OK.
6. Launch the Flavored version of the app - refer to step #3 above to see what dart entrypoint was executed regardless of what it shows in the console.
7. OBSERVE - the WRONG dart entrypoint was launched based on the app screen!
8. Hot Restart - OBSERVE - now the correct dart entrypoint is used.

Note: I have not tested all permutations, but
- Running a Configuration that sets a flavor AND a dart entry-point will demonstrate the problem.
- I did not observe this problem immediately when I created the second flavor / scheme.  From the second launch onwards it has been consistent and reproducable.

Note:  This may be related to the fact that I have two configs and only one of them specifies a flavor name, while the other uses no flavor.

**Target Platform:** iOS.  I don't seem to have this issue with Android
**Target OS version/browser:** Default not changed - Pretty sure it doesn't matter.
**Devices:** Physical iPhone 5 - but I believe this does not affect the outcome.

## Logs

`flutter run -v --flavor alt --target lib/main-alt.dart`

Shortly before the "Sync to device" there is a line that reads
`[ +8ms] <- compile package:test/main-alt.dart`

However it is launching lib/main.dart.

`Press "R" for Hot Restart - the screen changes and now the correct entry-point runs.`

`Flutter Analyze says "No issues found!"`

`Flutter Doctor says "No issues found!"`

Everything is up to date and no other versions have been tested.

```
Flutter Version: 1.12.17-pre.36
Flutter Channel: master
Dart 2.7.0
Cocoa pods version is 1.8.4
Android Studio version is 3.5.3 (#AI-191.8026.42.35.6010548 / Nov 15, 2019)
XCode version: 11.0 (11A420a)
```

------

Work-around:
- Launch the flavor and then use Hot-restart to get the correct dart entry-point to run.

Note: Even though there is a work-arround, this has serious implications because by the time it is possible to Hot Restart a lot has already happened.  I don't know what would happen in Release mode or after Archiving.

- Frequency / reproducability
1. The problem did not happen on the first launch after create the configuration with a separate entry-point.
2. Since adding the XCode scheme and flavor settings to the "alt" configuration, the problem has been easy to re-produce.
3. Going back to a run config with no flavor specified does not solve the problem - it is still reproducable.

**Comment by nicowernli** [comment]
Hi @Tahaan 
Thinking on this feels like you might have forgotten to change the build configuration for the scheme.

Could you just check this screen and see if you actually updated the build configuration to your new configuration?

<img width="871" alt="Captura de pantalla 2019-12-11 a las 13 07 15" src="https://user-images.githubusercontent.com/2279893/70620372-63a7fa80-1c17-11ea-8918-920a31ce49f2.png">

**Comment by Kiruel** [comment]
Hi @nicowernli ,

I have the same problem. I can't see 2 applications in the home (simulation iPhone 8). I have follow the "officiel" documentation [here](https://medium.com/@animeshjain/build-flavors-in-flutter-android-and-ios-with-different-firebase-projects-per-flavor-27c5c5dac10b).
But when I use 
`flutter run --target=lib/main_dev.dart --flavor dev` it launch the dev like expected,

but when i use this:
`flutter run --target=lib/main_prod.dart --flavor prod` it launch the app but with the dev environment, only when I Hot-Reload I see the data from the prod. And I don't see 2 applications in the home. Flutter override the first one.

I have check everything, the build configuration seems ok.

**Comment by Kiruel** [comment]
I found something interesting in the verbose log:
When I execute:
`flutter build ios --release --target=lib/main_dev.dart --flavor=dev --verbose`
he building should be `fr.example.dev` but we see in the logs  `fr.example`

```[ +107 ms] Building fr.example for device (ios-release)...
[  +13 ms] executing: [/Users/USER/Documents/example/ios/] /usr/bin/xcodebuild -list
[+1480 ms] Information about project "Runner":
                        Targets:
                            Runner

                        Build Configurations:
                            Debug-prod
                            Debug-dev
                            Release-prod
                            Release-dev
                            Profile-prod
                            Profile-dev

                        If no build configuration is specified and -scheme is not passed then "Release-prod" is used.

                        Schemes:
                            dev
                            prod
```

I think -scheme is not specified when we use --flavor for ios.

**Comment by Kiruel** [comment]
I find a workarround.
Simple:
Before every run use:
`flutter clean`
Then:
`flutter build ios --release --target=lib/main_dev.dart --flavor=dev --verbose`
And finaly:
`flutter run --target=lib/main_dev.dart --flavor=dev --verbose`

If you want to run the production now:
```
flutter clean
flutter build ios --release --target=lib/main_prod.dart --flavor=prod --verbose
flutter run --target=lib/main_prod.dart --flavor=prod --verbose
```

This link help me a lot https://github.com/flutter/flutter/issues/41793#issuecomment-569511351

Now I can see 2 separates build in the same phone with different name.

**Comment by jonahwilliams** [comment]
You should not have to run `flutter clean` before building. This is a huge bug in the tool if that is the case

**Comment by Kiruel** [comment]
The flutter clean is not necessary but I need to build everytime I want to run a different flavor. I pass hours to find this.
And because of this https://github.com/flutter/flutter/issues/35163 the console log is not the right build but the build is the good one. So confusing. I think if the #35163 is fix and a little documentation about flavor building will fix this problem.

What do you think @jonahwilliams ?

**Comment by jmagman** [comment]
@Tahaan This should be fixed by https://github.com/flutter/flutter/pull/56620.

@Kiruel I don't know what version of Flutter you are on, but https://github.com/flutter/flutter/pull/56620 is in 1.19.0-2.0.pre, which is available in the [beta channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels).  Would you mind trying there?  If you're still seeing this, please create a new issue and completely fill out the template, include the output of `flutter doctor -v`.
