### ISSUE TITLE
No intellisense for methods - VSCode

### ISSUE THREAD

**Issue by lukaszdebowski** [flutter/flutter#46485]
## Steps to Reproduce

1. Declare a function with some parameters in a .dart file
2. Create a class and assign that function to a field in that class
3. When trying to use this function from the class, intellisense will not work (not suggesting parameters names etc)

**Target Platform:** macOS, VSCode

Example:

```
String exampleFunction({@required String name}) {
  return name;
}

class ExampleClass {
  static const getName = exampleFunction;
}
```

If you try to use the `ExampleClass.getName()`, VSCode will not suggest that this method has a `name` parameter. Using the `exampleFunction` directly works as expected (VSCode suggests the parameter)

Flutter doctor:

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] VS Code (version 1.36.0)
[✓] Connected device (1 available)
```

**Comment by iapicca** [comment]
tested with master
<details>
  <summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel master, v1.12.16, on Microsoft Windows [Version 10.0.19013.1122], locale en-US)
    • Flutter version 1.12.16 at C:\src\flutter
    • Framework revision 37f9c54116 (12 days ago), 2019-11-27 11:33:38 -0800
    • Engine revision fad1b23c42
    • Dart version 2.7.0        

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\iapic\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.40.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

</details>
same result

![image](https://user-images.githubusercontent.com/45637986/70434601-50692380-1a8d-11ea-956d-dd0d002bae28.png)

thank you @lukaszdebowski

**Comment by jonahwilliams** [comment]
This is not related to the flutter tool or devtools (the flutter app)

**Comment by iapicca** [comment]
Hi @lukaszdebowski 
following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter) 
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/Dart-Code/Dart-Code/issues)

I apologize for not realizing sooner.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you for your understanding
