### ISSUE TITLE
flutter 1.9.1.hotfix.6 Gradle error

### ISSUE THREAD

**Issue by adetoroe787** [flutter/flutter#46507]
I am try to run my first app on flutter but i got this error. 

```bash
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "C:\Users\ZESTARLAB\Documents\fasttrack\android\gradlew.bat" exited abnormally:
Starting a Gradle Daemon, 4 busy Daemons could not be reused, use --status for details


FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type ResourceSnapshotterCacheService using GradleUserHomeScopeServices.createResourceSnapshotterCacheService().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Finished with error: Please review your Gradle project setup in the android/ folder.

BUILD FAILED in 2m 32s
  Command: C:\Users\ZESTARLAB\Documents\fasttrack\android\gradlew.bat app:properties
```

how could i resolve this?

**Comment by iapicca** [comment]
Hi @adetoroe787 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
