### ISSUE TITLE
Improve how ImageIcon does opacity

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4651]
From @abarth, regarding `ImageIcon`'s implementation of `opacity`:

> It would be much more efficient to do this with a color filter on the image.  We already have a `color` parameter on `Image` that turns into a `ColorFilter`.  We should probably upgrade that to a `ColorFilter` and use that to create the opacity.

> We did it this goofy way before because `ColorFilter` was a host object (and therefore expensive to create).  I guess we still need to add `operator==` to https://github.com/flutter/engine/blob/master/flutter/lib/ui/painting.dart#L836 ...

**Comment by abarth** [comment]
First step https://github.com/flutter/engine/pull/2769

**Comment by abarth** [comment]
This is easier than I thought.
