### ISSUE TITLE
[IOS] Google sign in crashes the flutter app

### ISSUE THREAD

**Issue by mingwugmail** [flutter/flutter#46532]
I have same problem as this one: https://groups.google.com/forum/#!topic/flutter-dev/DFRfU2Nlv4k

> Hi all,
> 
> google_sign_in 4.0.11 plugin crashes on the IOS device with the exception, but it works OK on the simulator.
> 
> PlatformException(google_sign_in, -[NSNull stringByAddingPercentEncodingWithAllowedCharacters:]: unrecognized selector sent to instance 0x38bb1978, NSInvalidArgumentException)
> 
> Example:
> 
> final GoogleSignIn _googleSignIn = GoogleSignIn();
> final googleUser = await _googleSignIn.signIn();  //Crashing here

I'm using google_sign_in 4.0.14, and IOS Simulator on iPhone 5s.

**Comment by mingwugmail** [comment]
dup of https://github.com/flutter/flutter/issues/44564

**Comment by mingwugmail** [comment]
downgrade google_sign_in to 4.0.7, working now.

**Comment by iapicca** [comment]
Hi @mingwugmail 
thank you for noticing the duplicate
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.

**Comment by buuth** [comment]
All that manipulation with downgrading are wrong. You can keep all packages up-to-date. Problem is some genius developer forgot to check null before accessing variables, so you must use
GoogleSignIn googleSignIn = GoogleSignIn(
        scopes: ['email', 'https://www.googleapis.com/auth/contacts.readonly'], 
        hostedDomain: "",
        clientId: "",);
instead of
GoogleSignIn googleSignIn = GoogleSignIn(
        scopes: ['email', 'https://www.googleapis.com/auth/contacts.readonly']);
each will lead to crash.
I lost one day of my life due to this silly bug. Hope you all doing better.

**Comment by AdnanKazi** [comment]
> All that manipulation with downgrading are wrong. You can keep all packages up-to-date. Problem is some genius developer forgot to check null before accessing variables, so you must use
> GoogleSignIn googleSignIn = GoogleSignIn(
> scopes: ['email', 'https://www.googleapis.com/auth/contacts.readonly'],
> hostedDomain: "",
> clientId: "",);
> instead of
> GoogleSignIn googleSignIn = GoogleSignIn(
> scopes: ['email', 'https://www.googleapis.com/auth/contacts.readonly']);
> each will lead to crash.
> I lost one day of my life due to this silly bug. Hope you all doing better.
> Please someone fix this simple bug, or update sample app and documentation. Thanks

Still didn't work

**Comment by duy1998** [comment]
> All that manipulation with downgrading are wrong. You can keep all packages up-to-date. Problem is some genius developer forgot to check null before accessing variables, so you must use
> GoogleSignIn googleSignIn = GoogleSignIn(
> scopes: ['email', 'https://www.googleapis.com/auth/contacts.readonly'],
> hostedDomain: "",
> clientId: "",);
> instead of
> GoogleSignIn googleSignIn = GoogleSignIn(
> scopes: ['email', 'https://www.googleapis.com/auth/contacts.readonly']);
> each will lead to crash.
> I lost one day of my life due to this silly bug. Hope you all doing better.
> Please someone fix this simple bug, or update sample app and documentation. Thanks

Thank you :)

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by cpboyd** [comment]
@iapicca I was just testing my app (built with XCode 12) on the iOS 10 simulator and it had a similar crash.

iOS 11+ works fine.

**Comment by iapicca** [comment]
@cpboyd please follow the indications [above](https://github.com/flutter/flutter/issues/46532#issuecomment-647552234)
