### ISSUE TITLE
Cannot see my device android studio

### ISSUE THREAD

**Issue by AhmedAlaa96** [flutter/flutter#46540]
I'm using flutter on windows 10 everything is great 
i ran **` flutter doctor `** :

> [√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.207], locale en-US)
>
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [√] Android Studio (version 3.5)
> [√] VS Code (version 1.40.2)
> [√] Connected device (1 available)
>
> • No issues found!

but when i'm using android studio cannot see my device or run the emulator :
![android studio](https://user-images.githubusercontent.com/17764800/70395948-c8433980-1a0c-11ea-9f64-c860616b8212.PNG)

I have a custom location for android sdk and add it to environment variables under **ANDROID_HOME**  

I used **`flutter devices`** : 
> 1 connected device:
>
> Redmi Note 7 • f65a232 • android-arm64 • Android 9 (API 28)

**what is wrong ?**

**Comment by iapicca** [comment]
Hi @AhmedAlaa96 

![image](https://user-images.githubusercontent.com/45637986/70436498-1fd7b880-1a92-11ea-87c0-3f23832d8e88.png)

from your screenshot I see the device is mounted

**Comment by itsJoKr** [comment]
@iapicca That can be an emulator that's not started from Android studio. The real connected devices for me appears on the left.


![image](https://user-images.githubusercontent.com/11093480/70450513-24a56800-1aa4-11ea-9ec4-619eb6b49eae.png)

I would say problem is that Studio didn't recognize the Flutter project or something with Flutter plugin.

**Comment by AhmedAlaa96** [comment]
@itsJoKr  I think you are right
