### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by piecubed** [flutter/flutter#46566]
I'm trying to start making a flutter app for a discord like chat server i also made, and i thought i would start with a Message widget.  My code is in `message.dart`, and the error it throws when i run the app with `flutter run` is in `run.txt`, and my main file isn't included, because it's just a stateless widget. [Source is here](https://gist.github.com/piecubed/878c4a30316cb6535c98fcdc76126f5b) (I Put it on gist.github.com because its too long for here).   I have a totally functional flutter setup, already checked with `flutter doctor`, and no problems with `flutter analyze`.  Any help would be great!

**Comment by anotherglitchinthematrix** [comment]
You're using **double.infinity** to fill the remaining space, instead of use Expanded, Align, or Positioned widgets to achieve your desired look.

**Comment by iapicca** [comment]
Hi @piecubed 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose` relative to the error?
Thank you

**Comment by piecubed** [comment]
@iapicca, output of `flutter doctor -v`:

```
$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.12.15, on Mac OS X 10.15 19A583, locale en-US)
    • Flutter version 1.12.15 at /Users/piecubed/.flutter
    • Framework revision 459c7fb884 (13 days ago), 2019-11-26 17:04:51 +0000
    • Engine revision e136d637a8
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/piecubed/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • <device> • G0W0TF038395F0NW • android-arm • Android 7.1.2 (API 25)

• No issues found!
```

[And here's the output of `flutter run --verbose`](https://gist.github.com/piecubed/878c4a30316cb6535c98fcdc76126f5b#file-verbose-txt)

**Comment by piecubed** [comment]
@anotherglitchinthematrix Thanks, will do that when the current issue is resolved!

**Comment by iapicca** [comment]
Hi again@piecubed
thank you for providing your `flutter doctor -v`
could you please provide your  `flutter run --verbose` and 
a minimal code sample or the steps to reproduce the problem.
Thank you

**Comment by piecubed** [comment]
@iapicca I did provide it, see the linked file.

**Comment by iapicca** [comment]
Hi again @piecubed 
I don't see any file or link to your logs,
could you please provide it again?
thank you

**Comment by piecubed** [comment]
Sure, it was a hyperlink. https://gist.github.com/piecubed/878c4a30316cb6535c98fcdc76126f5b#file-verbose-txt

**Comment by piecubed** [comment]
Hm, looks like I've resolved it, sorry to bother you.  I think for some reason flutter didnt like nested containers, which I used.  Thanks!
