### ISSUE TITLE
Reports of black screen when updating via Play Store

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#46570]
Follow-on to make sure everything's really fixed with https://github.com/flutter/flutter/issues/37155

The issue has been closed because the original cause of the bug was discovered and fixed - and verified to be fixed on master.

However, @Gyoko reports that users are experiencing the black screen when updating their app via Play Store to a version that was built from the current beta branch.

@Gyoko can you please give details here with the issues you're having with black screens?

Open questions:
1. What specific version did you build the updated app from?
1. Can you confirm that the _same app version_ will succeed when freshly installed on a device but fail when _updated_ from a previous version?
1. Can you include `adb logcat` output from a device exhibiting this problem?
1. Can you attach an APK demonstrating this problem, or link to the Play Store listing for this app?
1. Does this still happen only on Samsung J6+?

Can you reproduce this problem against master?  How about the current beta release (1.12.13+hotfix.3)?

Thanks!

**Comment by alexhenriquepv** [comment]
This problem was resolved on beta and dev versions. Occurring on devices with sanpdragon 425. J4, J6 and J7+. Update you flutter version.

**Comment by tvolkert** [comment]
@Gyoko any update?

**Comment by tvolkert** [comment]
In #46571 @Gyoko reported the following:

> Like I said, this is not an issue with the beta 1.12 release itself.
If I perform a clean install on a device - it will work as intended.
HOWEVER, if a user has app already installed, and the app was built using master 1.9.1. If I publish a release built with beta 1.12, and this user will try to update his master 1.9.1 app with beta 1.12, then the app will be stuck on black screen. This happens on pretty much every phone. If the user uninstalls the 1.9.1 app, and then installs beta 1.12, then the app will work as intended.
>
> Meaning that beta 1.12 is nonviable for public release, since it would present black screen for all existing users and would force them to reinstall the app.

The problem is that we've been unable to reproduce this in any apps we've tested, and this is the only report of this problem, which is why I need more actionable info in order to be able to try to diagnose this.  As such, please provide the details I asked for above in the issue summary (removing the questions you've already answered):

1. What specific version did you build the updated app from?
1. Can you confirm that the _same app version_ will succeed when freshly installed on a device but fail when _updated_ from a previous version?
1. Can you include `adb logcat` output from a device exhibiting this problem?
1. Can you attach an APK demonstrating this problem, or link to the Play Store listing for this app?

**Comment by xster** [comment]
also whether there was any crossings between APKs and AABs between the update would be useful information

**Comment by tvolkert** [comment]
Also, when you updated to 1.12, did you update to use the new embedding API?

**Comment by Xgamefactory** [comment]
> did you update to use the new embedding API?
what extra stuff we should do for this ?

**Comment by tvolkert** [comment]
I meant when you switched to using Flutter v1.12, had you also switched the app to use any of the new [`io.flutter.embedding.*` classes](https://api.flutter.dev/javadoc/)?  I'm just trying to collect data 🙂

**Comment by Hixie** [comment]
Have we received any other reports of people seeing this?

**Comment by Hixie** [comment]
We were unable to reproduce on our Gallery app, for what it's worth.
