### ISSUE TITLE
Doc request for an accessibility guide

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4657]
I am updating the FAQ and I'd love to link to a guide on accessibility.

**Comment by Hixie** [comment]
cc @goderbauer

**Comment by zoechi** [comment]
There is some https://flutter.io/docs/development/accessibility-and-localization/accessibility
but shouldn't this also discuss Semantics stuff?

**Comment by goderbauer** [comment]
Dupe of https://github.com/flutter/website/issues/2081.
