### ISSUE TITLE
Wrap Widget

### ISSUE THREAD

**Issue by maheshkumar2150** [flutter/flutter#46575]
Right now, The Wrap widget does not have any option to fit its children in a specific size. 

Wrap widget

Feature
Maximum children width and height. - The children should be maximum in the limit
Children must automatically shrink and expand according to the space available of Wrap's parent.
While expanding the maximum width and height must be maintained.

Right now, Wrap does not have features.

**Comment by goderbauer** [comment]
You can just wrap the children in a sized box to size them any way you want.
