### ISSUE TITLE
ClipPath not working with Stack and Positioned

### ISSUE THREAD

**Issue by thongdaddy** [flutter/flutter#46583]

**Comment by kbups** [comment]
Hello @thongdaddy,

I have the same problem. ClipPaths are not displayed when located in Stack > Positioned widgets hierarchy. Do you know how to fix this problem?

Thanks in advance for your reply.

Regards,

**Comment by thongvo109** [comment]
@kbups  Sorry I did change user github.  
@thongdaddy This is also my github

**Comment by RicoLiu** [comment]
> Hello @thongdaddy,
> 
> I have the same problem. ClipPaths are not displayed when located in Stack > Positioned widgets hierarchy. Do you know how to fix this problem?
> 
> Thanks in advance for your reply.
> 
> Regards,

@kbups Have you solved this issue? I have met the same issue.
