### ISSUE TITLE
Add android's Holo theme's colors in the Colors class

### ISSUE THREAD

**Issue by phanirithvij** [flutter/flutter#46581]
## Use case
The [Holo](https://android-developers.googleblog.com/2012/01/holo-everywhere.html) theme was introduced in 2012 in android v4 which added few colors with the namespace `holo_`

They are located [here](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/res/res/values/colors_holo.xml)

## Proposal

This can be made as a plugin but as they are kind of official it would be nice to have them in the `Colors` class provided by flutter. This should be easy to implement as there are only 12 colors (general purpose).

The `Colors` class follows Material Design so I understand that this proposal might get rejected.
In such a case plugin can be made.

![colors](https://user-images.githubusercontent.com/29627898/70415963-e7c97900-1a83-11ea-90be-62512e582e29.png)

[colors.zip](https://github.com/flutter/flutter/files/3938311/colors.zip)

**Comment by HansMuller** [comment]
As you pointed out, the Colors class is intended to (just) align with the Material spec, see https://material.io/design/color/the-color-system.html. This set of colors would probably best be shared with a separate package.

**Comment by bernaferrari** [comment]
I think you (or anyone else) could make it a plugin in pub - extensions are now in dart 2.6. They have been deprecated and removed over the years on Android as Material maturated. I don't see why bringing them back would have any benefit.

**Comment by phanirithvij** [comment]
As per the suggestions it seems like it's an unnecessary thing to bring these back. Closing this.
