### ISSUE TITLE
Atom: Flutter repo refactor/rename analyzer out of sync

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4659]
I ran into this when trying to refactor the entire flutter repo. My setup is a little strange in that I've got emacs buffers open on many of the affected files. Hopefully the problem can be reproduced with (just) a clone of the flutter repo.

In packages/flutter/lib/src/rendering/flex.dart, try renaming the MainAxisSize enum. This appears to do the right thing but the analyzer reports an error for every line that uses the new name.

**Comment by eseidelGoogle** [comment]
FYI @devoncarew

**Comment by devoncarew** [comment]
@pq @bwilkerson

**Comment by pq** [comment]
cc @scheglov

**Comment by scheglov** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/662a461988b5097a0e7f48628e4330aaf9447b59

**Comment by pq** [comment]
w00t! :metal:

**Comment by sethladd** [comment]
Closing because @scheglov says it's fixed :)
