### ISSUE TITLE
google_maps_flutter - not show markers and polygons

### ISSUE THREAD

**Issue by JacquesMarques** [flutter/flutter#46597]
I am trying to create an application to show a route between two points in the map. I tried the code below but it didn't work, it shows the map but it doesn't show the marks nor the polygons.
I try in emulator and in device but not working, show only the map.
Can anyone tell why this is happening? 
Follows the code I'm using to test:

<details>
  <summary>code sample</summary>

```dart
import 'package:flutter_polyline_points/flutter_polyline_points.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'dart:async';
import 'package:flutter/material.dart';

const double CAMERA_ZOOM = 13;
const double CAMERA_TILT = 0;
const double CAMERA_BEARING = 30;
const LatLng SOURCE_LOCATION = LatLng(42.7477863, -71.1699932);
const LatLng DEST_LOCATION = LatLng(42.6871386, -71.2143403);

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  Completer<GoogleMapController> _controller = Completer();// this set will hold my markers
  Set<Marker> _markers = {};// this will hold the generated polylines
  Set<Polyline> _polylines = {};// this will hold each polyline coordinate as Lat and Lng pairs
  List<LatLng> polylineCoordinates = [];// this is the key object - the PolylinePoints
  // which generates every polyline between start and finish
  PolylinePoints polylinePoints = PolylinePoints();
  String googleAPIKey = '<YOUR_API_KEY>';// for my custom icons
  BitmapDescriptor sourceIcon;
  BitmapDescriptor destinationIcon;

  @override
  void initState() {
    super.initState();
    setSourceAndDestinationIcons();
  }

  void setSourceAndDestinationIcons() async {
   sourceIcon = await BitmapDescriptor.fromAssetImage(
      ImageConfiguration(devicePixelRatio: 2.5),
      'assets/driving_pin.png');   
   destinationIcon = await BitmapDescriptor.fromAssetImage(
      ImageConfiguration(devicePixelRatio: 2.5),
      'assets/destination_map_marker.png');
  }

  @override
  Widget build(BuildContext context) {   CameraPosition initialLocation = CameraPosition(
        zoom: CAMERA_ZOOM,
        bearing: CAMERA_BEARING,
        tilt: CAMERA_TILT,
        target: SOURCE_LOCATION
    );   return GoogleMap(
        myLocationEnabled: true,
        compassEnabled: true,
        tiltGesturesEnabled: false,
        markers: _markers,
        polylines: _polylines,
        mapType: MapType.normal,
        initialCameraPosition: initialLocation,
        onMapCreated: onMapCreated
    );
  }

  void onMapCreated(GoogleMapController controller) {
    _controller.complete(controller);
    setMapPins();
    setPolylines();
  }

  void setMapPins() {   // source pin
   _markers.add(Marker(
      markerId: MarkerId('sourcePin'),
      position: SOURCE_LOCATION,
      icon: sourceIcon
   ));   // destination pin
   _markers.add(Marker(
      markerId: MarkerId('destPin'),
      position: DEST_LOCATION,
      icon: destinationIcon
   ));
  }

  setPolylines() async {   
    List<PointLatLng> result = await
        polylinePoints?.getRouteBetweenCoordinates(
          googleAPIKey,
          SOURCE_LOCATION.latitude, 
          SOURCE_LOCATION.longitude,
          DEST_LOCATION.latitude, 
          DEST_LOCATION.longitude);   

      if(result.isNotEmpty){   // loop through all PointLatLng points and convert them
      // to a list of LatLng, required by the Polyline
      result.forEach((PointLatLng point){
          polylineCoordinates.add(
            LatLng(point.latitude, point.longitude));
      });   // create a Polyline instance
      // with an id, an RGB color and the list of LatLng pairs
      Polyline polyline = Polyline(
          polylineId: PolylineId('poly'),
          color: Color.fromARGB(255, 40, 122, 198),
          points: polylineCoordinates
      );
    
      // add the constructed polyline as a set of points
      // to the polyline set, which will eventually
      // end up showing up on the map
      _polylines.add(polyline);   
    }
  }
}
```

</details>

```bash
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale pt_BR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)
```

```yaml
google_maps_flutter: 0.5.21+13
flutter_polyline_points: ^0.1.0
```

**Comment by iapicca** [comment]
Hi @JacquesMarques 
I see you are using a 3rd party plugin [flutter_polyline_points](https://pub.dev/packages/flutter_polyline_points), 
could you provide a minimal code sample
or the steps to reproduce the problem, without 3rd party packages
Thank you

**Comment by JacquesMarques** [comment]
Hi @iapicca,
This plugin is only to get the points of polygon of the route, and the problem is with markers and polygons, but follow the code without the plugin, that keeps giving the same problem:


`import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'dart:async';
import 'package:flutter/material.dart';

const double CAMERA_ZOOM = 13;
const double CAMERA_TILT = 0;
const double CAMERA_BEARING = 30;
const LatLng SOURCE_LOCATION = LatLng(42.7477863, -71.1699932);
const LatLng DEST_LOCATION = LatLng(42.6871386, -71.2143403);

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  Completer<GoogleMapController> _controller = Completer();// this set will hold my markers
  Set<Marker> _markers = {};// this will hold the generated polylines
  Set<Polyline> _polylines = {};// this will hold each polyline coordinate as Lat and Lng pairs
  List<LatLng> polylineCoordinates = [];// this is the key object - the PolylinePoints
  // which generates every polyline between start and finish
  String googleAPIKey = '<YOUR_API_KEY>';// for my custom icons
  BitmapDescriptor sourceIcon;
  BitmapDescriptor destinationIcon;

  @override
  void initState() {
    super.initState();
    setSourceAndDestinationIcons();
  }

  void setSourceAndDestinationIcons() async {
   sourceIcon = await BitmapDescriptor.fromAssetImage(
      ImageConfiguration(devicePixelRatio: 2.5),
      'assets/driving_pin.png');   
   destinationIcon = await BitmapDescriptor.fromAssetImage(
      ImageConfiguration(devicePixelRatio: 2.5),
      'assets/destination_map_marker.png');
  }

  @override
  Widget build(BuildContext context) {   CameraPosition initialLocation = CameraPosition(
        zoom: CAMERA_ZOOM,
        bearing: CAMERA_BEARING,
        tilt: CAMERA_TILT,
        target: SOURCE_LOCATION
    );   return GoogleMap(
        myLocationEnabled: true,
        compassEnabled: true,
        tiltGesturesEnabled: false,
        markers: _markers,
        polylines: _polylines,
        mapType: MapType.normal,
        initialCameraPosition: initialLocation,
        onMapCreated: onMapCreated
    );
  }

  void onMapCreated(GoogleMapController controller) {
    _controller.complete(controller);
    setMapPins();
    setPolylines();
  }

  void setMapPins() {   // source pin
   _markers.add(Marker(
      markerId: MarkerId('sourcePin'),
      position: SOURCE_LOCATION,
      icon: sourceIcon
   ));   // destination pin
   _markers.add(Marker(
      markerId: MarkerId('destPin'),
      position: DEST_LOCATION,
      icon: destinationIcon
   ));
  }

  setPolylines() async {   
    polylineCoordinates.add(LatLng(42.74807, -71.1702));
    polylineCoordinates.add(LatLng(42.74763, -71.1713));
    polylineCoordinates.add(LatLng(42.74735, -71.17198));
    polylineCoordinates.add(LatLng(42.74693, -71.17189));
    polylineCoordinates.add(LatLng(42.74632, -71.17173));
    polylineCoordinates.add(LatLng(42.7436, -71.16983));
    polylineCoordinates.add(LatLng(42.73895, -71.17657));
    polylineCoordinates.add(LatLng(42.73507, -71.20378));
    polylineCoordinates.add(LatLng(42.72207, -71.20859));
    polylineCoordinates.add(LatLng(42.6895, -71.20612));
    polylineCoordinates.add(LatLng(42.68972, -71.21146));
    polylineCoordinates.add(LatLng(42.68705, -71.21461));


    // with an id, an RGB color and the list of LatLng pairs
    Polyline polyline = Polyline(
        polylineId: PolylineId('poly'),
        color: Color.fromARGB(255, 40, 122, 198),
        points: polylineCoordinates
    );
  
    // add the constructed polyline as a set of points
    // to the polyline set, which will eventually
    // end up showing up on the map
    _polylines.add(polyline);   
  }
}
`

Thank you

**Comment by thedejifab** [comment]
@JacquesMarques have you been able to solve this? How did you solve it? I'm experiencing same issues.

**Comment by JacquesMarques** [comment]
Hi @thedejifab,

I could not fix this in time, than I use Google Maps external with url_launcher extension. But the author of this article: https://medium.com/flutter-community/implement-real-time-location-updates-on-google-maps-in-flutter-235c8a09173e 
Post a example that works in git: https://github.com/romanejaquez/flutter_routelines.git

**Comment by HappyGhostz** [comment]
@JacquesMarques 
@ iapicca
 I also encountered the problem of not displaying the mark, but through debugging I got an exception：Failed to decode image. The provided image must be a Bitmap.

**Comment by iapicca** [comment]
Hi @JacquesMarques 
are you still experiencing the issue 
with the latest stable version of flutter
and the latest version of `google_maps_flutter `?

If so,
could you please provide your updated `flutter doctor -v` ,
your `flutter run --verbose
and your `pubspec.yaml` 
Thank you

**Comment by TahaTesser** [comment]
Hi @JacquesMarques 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
