### ISSUE TITLE
Problem keyboard 

### ISSUE THREAD

**Issue by iso57** [flutter/flutter#46591]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```
When i open the keyboard in app, my custom bottom bar is hide with this..

**Comment by iso57** [comment]
I would like add that i have already test with the package keyboard_action but its not the solution because the package add a navbar with the color grey and i don't want this

**Comment by iapicca** [comment]
Hi @iso57 
I'm not sure to understand the issue
can you please provide your updated  `flutter doctor -v`
and a minimal code sample
or the steps to reproduce the problem.
Thank you
