### ISSUE TITLE
Support for Material Design "Subheaders"

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#466]
http://www.google.com/design/spec/components/subheaders.html

> Upon scrolling, subheaders remain pinned to the top of the screen until pushed on or off screen by the next subheader.

In the example below, the subheader text is blue.

![Material Design Subheader example](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsMEtuWm42b2lSRkk/components_subheaders4.png)

**Comment by levrik** [comment]
Would really like to see that in the framework. Any pointers how to achive that already at the moment? @Hixie

**Comment by Hixie** [comment]
It would probably have to be a sliver that has a list of slivers and knows about the sticky header logic, a bit like a combination of RenderSliverList, RenderSliverPadding, and RenderSliverPersistentHeader. We would definitely welcome a patch that did this. It's a little subtle though.

It's something we will do eventually but we don't expect to have this done any time soon.

**Comment by levrik** [comment]
@Hixie Can you give me a few more hints? I'm completely lost and I really don't want to move to React Native or Xamarin.

**Comment by Hixie** [comment]
I recommend starting to pull a thread starting with SliverAppBar. Follow through how it's built, and eventually you'll reach RenderSliverPersistentHeader, see how it's built (notably, how its performLayout method works to keep itself on-screen). Then, follow a thread from SliverPadding and see how RenderSliverPadding works (notably, how it wraps its child).

You want to create a RenderSliver subclass that works like a combination of those two. It would have two children, a RenderBox that ends up being the header (just like RenderSliverPersistentHeader), and a RenderSliver that it wraps (just like RenderSliverPadding). Then you have to get the performLayout method to do the maths correctly to handle both of them at the same time. You'll also have to implement the paint() method and hitTest() method to pass down the paint and hittest calls, but that part should be somewhat simpler.

A lot of this is actually documented in some detail, see the [docs for RenderSliver](https://master-docs-flutter-io.firebaseapp.com/flutter/rendering/RenderSliver-class.html), [AbstractNode](https://master-docs-flutter-io.firebaseapp.com/flutter/foundation/AbstractNode-class.html) (the super class of RenderObject), methods like [performLayout](https://master-docs-flutter-io.firebaseapp.com/flutter/rendering/RenderObject/performLayout.html) or [paint](https://master-docs-flutter-io.firebaseapp.com/flutter/rendering/RenderObject/paint.html), etc. For slivers specifically, lots of docs exist on the various properties of [SliverConstraints](https://master-docs-flutter-io.firebaseapp.com/flutter/rendering/SliverConstraints-class.html) and [SliverGeometry](https://master-docs-flutter-io.firebaseapp.com/flutter/rendering/SliverGeometry-class.html), which you'll need to implement the layout method.

I'm sorry this isn't simpler. Feel free to ask specific questions if you run into trouble.

**Comment by levrik** [comment]
@Hixie Thanks. I will give it a second try next weekend.

**Comment by voliva** [comment]
Any update on this feature? As a workaround I see there's this package https://github.com/itsJoKr/sticky_header_list that seems to do the trick

**Comment by letsar** [comment]
@voliva I created a package for sticky headers as sliver here: https://github.com/letsar/flutter_sticky_header. It takes a widget as header and a sliver as child. I hope I created it as @Hixie explained it.

Does it match your requirements?

**Comment by letsar** [comment]
Thanks @Hixie. Yes it's true for the lag 😞. Do you know how to fix this?

**Comment by Hixie** [comment]
You could create a kind of RenderObject that takes the percentage as one of the constraints. Maybe its constraints could be a class with a double (the percentage) and a `BoxConstraints` object, and its child would be a `RenderBox` to which you pass the `BoxConstraints`. If you model this render object after the `LayoutBuilder` widget and its render object, you can have the same API you have today but without the lag. It's a rather advanced use of Flutter's API, but hey, no worse than slivers, and you seemed to handle that pretty well. :-)

**Comment by letsar** [comment]
Oh great, thank you! Challenge accepted :smile:. I will give it a try after finishing the work in progress on the next feature. Maybe I'll come back to you later, once I dive in the lag issue.
By the way, thank you for your work on the Flutter SDK 👍.

**Comment by letsar** [comment]
@Hixie I worked on a solution for the scroll percentage to not lag by one frame, by following your explanation. Thanks again, your instructions were very clear 👍.

If you have time, can you tell me if it's what you had in mind?
The code is on this branch: https://github.com/letsar/flutter_sticky_header/tree/feature/2_percentage_observer

**Comment by Hixie** [comment]
Yep, that's pretty much it!

**Comment by Piinks** [comment]
>Upon scrolling, subheaders remain pinned to the top of the screen until pushed on or off screen by the next subheader.

I'm working on a `SliverGroup` project that will enable the *pinned-then-pushed* behavior described here for `SliverPersistentHeader`. I should have a doc/propsed changes ready for feedback soon.

Here's an updated link to subheaders (under anatomy) in the Material spec: https://material.io/components/lists/#anatomy 

@HansMuller Any thoughts on if there should be a stand alone material subheader widget devoted to this? Or does updating `SliverPersistentHeader` sound appropriate? I am thinking a whole other header widget will be confusing.

**Comment by HansMuller** [comment]
Updating SliverPersistentHeader's API to support subheaders sounds like a good approach to me.

**Comment by Hixie** [comment]
There are a number of packages that do this now: https://pub.dev/packages?q=sliver+header
