### ISSUE TITLE
[package_info] Add web implementation

### ISSUE THREAD

**Issue by jld3103** [flutter/flutter#46609]

**Comment by hterkelsen** [comment]
What would you like the web implementation of `package_info` to do? I can't really think of natural web implementations of these: https://pub.dev/documentation/package_info/latest/package_info/PackageInfo-class.html

**Comment by jld3103** [comment]
The most important feature is the version of the app. Maybe the version could be inserted at compile time and then be read by the plugin? All the other features don't matter for me, but should be supported in some way for completeness.

**Comment by nishp77** [comment]
Hi, I would like to ask if anyone could give me some idea on how to integrate the web part?? Like i don't no where to begin from.

**Comment by topilski** [comment]
Any updates?

**Comment by deakjahn** [comment]
@hterkelsen Easy to answer:

appName - the name of the application that's put into the Index.html TITLE tag. Maybe the description, that can be discussed, because:

packageName - might be the ˙name` entry from the `pubspec.yaml` instead.

version - `pubspec.yaml` version before the plus

buildNumber - `pubspec.yaml` version after the plus

**Comment by nishp77** [comment]
@hterkelsen I would like to ask you that within this plugin the macos implementation didn't add the package_info into another directory of it so do i leave it or follow the instruction from your medium article

**Comment by venkatd** [comment]
My use case for getting 

> @hterkelsen This one is easy to answer:
> 
> **appName** - the _name_ of the application that's placed into the `Index.html` `TITLE` tag. Maybe the _description_, that can be discussed, because:
> 
> **packageName** - might be the _name_ entry from the `pubspec.yaml` instead.
> 
> **version** - `pubspec.yaml` _version_ before the plus
> 
> **buildNumber** - `pubspec.yaml` _version_ after the plus

I agree with this mapping. We have a settings page that shows package info.

Sometimes we want to make sure the version we're running is the latest and that we aren't on a cached version. Or if a customer reports a bug, we may ask them to go to settings to pull this up for us.

Having this data available on all platforms would be helpful.

**Comment by jlubeck** [comment]
@hterkelsen having the version and build number this package on the web would be amazing.

**Comment by Wylarel** [comment]
Any updates?

**Comment by jld3103** [comment]
Looks like @balvinderz is working on it

**Comment by balvinderz** [comment]
#64644  got merged. will work on the package_info web implementation now.

**Comment by jlubeck** [comment]
Hey @balvinderz how come https://github.com/flutter/plugins/pull/3035 got closed without merge? Is there someplace else where we can keep track of progress? Thanks!

**Comment by balvinderz** [comment]
@jlubeck flutter community is taking over this package .so soon ,there will be a new package called package_info_plus with support for windows and web. You will have to wait until then .

**Comment by jlubeck** [comment]
> @jlubeck flutter community is taking over this package .so soon ,there will be a new package called package_info_plus with support for windows and web. You will have to wait until then .

Oh I see, thank you for the quick answer. Do you have any idea if there is an ETA on it? No worries if you don't :D Just curious!

**Comment by balvinderz** [comment]
@jlubeck i don't know

**Comment by venkatd** [comment]
@balvinderz is it going to be a federated plugin that adds support to web and windows or a completely different package?

**Comment by balvinderz** [comment]
Different package which support for android,ios,macos,web and windows

**Comment by balvinderz** [comment]
you can use package_info_plus now.
https://pub.dev/packages/package_info_plus

**Comment by topilski** [comment]
Hello, thank you for your work, seems to return null for version, do you have some requirements for web how it should works?

**Comment by balvinderz** [comment]
@topilski you should be on the latest master/Dev branch for the web implementation to work

**Comment by topilski** [comment]
@balvinderz 
![image](https://user-images.githubusercontent.com/4686379/95834000-115acd00-0d45-11eb-942a-44b0cbd304ed.png)

**Comment by balvinderz** [comment]
@topilski  you are on beta channel

**Comment by topilski** [comment]
Yes works, thank you!

**Comment by balvinderz** [comment]
@ditman I think this can be closed now.

**Comment by ditman** [comment]
It can! Thanks @balvinderz!

### Take a look at [package_info_plus](https://pub.dev/packages/package_info_plus), it supports web!

Closing this as done!

**Comment by Grohden** [comment]
So... `package_info_plus` doesn't work really well for web - at least for me it wasn't finding `version.json`.

I think that the best approach is generating static info at build time from `pubspec.yaml` and there's already a package for that! https://pub.dev/packages/build_pubspec

The package generates `pubspec.yaml` dart code at build time, so we're able to retrieve those infos and use them without all of those `async` `await` calls. 

Of course, these infos have to be manipulated properly (eg: split version by + to get build and version name) and they also don't reflect the _real_ platform files (eg: if you change something directly on platform files that are not generated from `pubspec.yaml`), but despite these problems I think that its a good alternative.

Note: the only prop I don't see being generated here is the `appName`, but at least for me, it's not needed - and also can be probably added in pubspect + generated

**Comment by balvinderz** [comment]
@Grohden  are you on latest master or dev branch?

**Comment by Grohden** [comment]
@balvinderz flutter?

```
Flutter 1.22.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (3 weeks ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0
```

Probably beta branch (?)

**Comment by balvinderz** [comment]
@Grohden this doesnt work in beta channel . You need to be on dev or master

**Comment by AndroidNils** [comment]
Short question: What is the difference between `package_info` and `package_info_plus`? Why did not implemented this feature for `package_info`?

**Comment by balvinderz** [comment]
> @Grohden this doesnt work in beta channel . You need to be on dev or master channel

This now works in beta branch too .

**Comment by guidezpl** [comment]
@nilsreichardt See https://github.com/flutter/flutter/issues/83277 for more context

**Comment by marceloiavenissi** [comment]
> Short question: What is the difference between `package_info` and `package_info_plus`? Why did not implemented this feature for `package_info`?

"Important: As of January 2021, the Flutter team is no longer accepting non-critical PRs for the original set of plugins in flutter/plugins, and instead they should be submitted in this project. You can read more about this announcement here. as well as in the Flutter 2 announcement blog post." - https://pub.dev/packages/package_info_plus
