### ISSUE TITLE
Autoroller failure causing too many PRs; burning CPU units at Cirrus.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#46607]
This occurred Friday night, 12/6. The engine auto-roller started creating PRs every 10-20 minutes which overwhelmed the clustered and burned through a lot of credits on your end.  Cirrus Labs:

* implemented a feature to cancel tasks once PR is closed. It should help with the crazy aggressive auto-roll but I've also followed up on Discord and hopefully it will be fixed on your side to not even retry that quickly for the same SHA.
* reimbursed addition 8000 credits since the auto-roll seems to burn through the thousands of credits.

We should make sure there's some sort of failsafe --- this burned over 6,000 CPU credits before caught.

cc @godofredoc

**Comment by tvolkert** [comment]
I'd like to get to the point where we auto-rolled every engine commit.  Will this be possible on LUCI?

**Comment by godofredoc** [comment]
Today 04/06/2021 we have rolled engine to framework 9 times with an average of 3 commit per roll(max(9), min(1)).

With LUCI this would cause a very high rate of pending tasks and we would be alerted  ~10 mins of when it starts.
