### ISSUE TITLE
[iOS] [google_maps_flutter] plugin stopped working

### ISSUE THREAD

**Issue by zmeggyesi** [flutter/flutter#46614]
Hi,

I'm trying to launch the iOS version of my app, and I'm running into a roadblock. Google Maps integration has seemingly stopped working from 2019-12-05 (when my last build was released) to 2019-12-09, without having changed a single thing in the build or the config. In fact, even the December 05 version, installed from TestFlight, has stopped working after I tried reverting there.

When a Maps widget is loaded on screen, I'm getting a deluge of BoringSSL errors, all along the lines of `TIC Read Status [21:0x0]: 1:57` (obviously, connection numbers change, but somehow the connection pointers always remain `0x0`. From time to time, I manage to catch a more verbose error in the debugger:
```
2019-12-09 18:51:35.972806+0100 Runner[19478:1766346] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C21.1:2][0x113efaf60] get output frames failed, state 8196
2019-12-09 18:51:35.979757+0100 Runner[19478:1766346] TIC Read Status [21:0x0]: 1:57
2019-12-09 18:51:35.980041+0100 Runner[19478:1766346] TIC Read Status [21:0x0]: 1:57
2019-12-09 18:51:45.731088+0100 Runner[19478:1765378] Google Maps SDK for iOS cannot connect or validate APIKey: Error Domain=com.google.HTTPStatus Code=400 "(null)" UserInfo={data=<3c48544d 4c3e0a3c 48454144 3e0a3c54 49544c45 3e426164 20526571 75657374 3c2f5449 544c453e 0a3c2f48 4541443e 0a3c424f 44592042 47434f4c 4f523d22 23464646 46464622 20544558 543d2223 30303030 3030223e 0a3c4831 3e426164 20526571 75657374 3c2f4831 3e0a3c48 323e4572 726f7220 3430303c 2f48323e 0a3c2f42 4f44593e 0a3c2f48 544d4c3e 0a>}
2019-12-09 18:51:45.731345+0100 Runner[19478:1765378] Your key may be invalid for your bundle ID: hu.skawa.dive-site-overwatch-ios
```

Despite what the error message says, I've checked and re-checked the key, its permissions, its associated bundle IDs, and everything _should be_ working. Yet, without having changed anything, it is not.

So far, I've tried upgrading to `google_maps_flutter: 0.5.21+13` (from build `+7`), as well as upgrading Flutter itself, along with the requisite cleans, to no avail. Not that it would explain why a four days old build re-installed from TestFlight would also produce the error (unless this is a Schroedinbug).

The issue presents itself in the Simulator, as well as a physical iPhone.

---

Output of Flutter Doctor:

```
[✓] Flutter (Channel beta, v1.12.13+hotfix.3, on Mac OS X 10.14.6 18G1012, locale en-GB)
    • Flutter version 1.12.13+hotfix.3 at /Users/zmeggyesi/tools/flutter
    • Framework revision 57f2df76d7 (4 days ago), 2019-12-05 21:23:21 -0800
    • Engine revision ac9391978e
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/zmeggyesi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone (2) • 9cc55aacffcf500003c8f83bd7cbcc2aeb67ae37 • ios • iOS 12.4.3

! Doctor found issues in 1 category.
```

**Comment by zmeggyesi** [comment]
Well, this is somewhat perplexing: I never had _Maps SDK for iOS_ enabled in my GCP project.

Which raises the question as to how Maps could have worked for the last four days...?

**Comment by iapicca** [comment]
Hi @zmeggyesi 
can you please provide your `flutter run --verbose`?

I see that there are newer version of the plugin `0.5.21+15`,
there are being released quite often, 
which is understandable given that it's a developer preview;
could you try if it works with the latest?

Thank you

**Comment by zmeggyesi** [comment]
Hi @iapicca 
Like I said, it's a bit perplexing, as it turns out the _root cause_ was that the iOS SDK API was never enabled on the GCP project.

On its own this wouldn't mean much, but the question then becomes "How has this ever worked?", especially in the last four days or during development during which the API was still not enabled, and maps were still being rendered.

To be fair to you, if you don't notice anything particularly alarming about this report, I would rather you focused Flutter efforts towards more severe/rewarding issues.

**Comment by jmagman** [comment]
This should be reported against the Google Maps iOS SDK https://developers.google.com/maps/documentation/ios-sdk/support
