### ISSUE TITLE
Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"

### ISSUE THREAD

**Issue by arthuryess** [flutter/flutter#46613]
Hi, I'm getting this error when building the Flutter app for iOS simulator. Here's the complete log

```bash
Launching lib/main_learner.dart on iPhone Xs in debug mode...
Running Xcode build...
Xcode build done.                                           24.1s
Failed to build iOS app
Error output from Xcode build:
↳
    2019-12-09 21:44:32.774 xcodebuild[37612:6496433]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-15508/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/Runtime/PBXTargetBuildContext.mm:759
    Details:  unexpected successful exit code from cancelled command <C0018:'CpResource Generated.xcconfig':P14>
    Object:   <PBXTargetBuildContext: 0x7fbf3a459b80>
    Method:   -createCommandInvocationRecordFromInvocation:
    Thread:   <NSThread: 0x7fbf3bc57e40>{number = 23, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2019-12-09 21:44:32.774 xcodebuild[37612:6496433]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-15508/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/Runtime/PBXTargetBuildContext.mm:759
    Details:  unexpected successful exit code from cancelled command <C0025:'CpResource Release_instructor-live.xcconfig':P14>
    Object:   <PBXTargetBuildContext: 0x7fbf3a459b80>
    Method:   -createCommandInvocationRecordFromInvocation:
    Thread:   <NSThread: 0x7fbf3bc57e40>{number = 23, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2019-12-09 21:44:32.774 xcodebuild[37612:6496433]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-15508/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/Runtime/PBXTargetBuildContext.mm:759
    Details:  unexpected successful exit code from cancelled command <C0023:'CpResource Debug_learner.xcconfig':P14>
    Object:   <PBXTargetBuildContext: 0x7fbf3a459b80>
    Method:   -createCommandInvocationRecordFromInvocation:
    Thread:   <NSThread: 0x7fbf3bc57e40>{number = 23, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2019-12-09 21:44:32.774 xcodebuild[37612:6496433]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-15508/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/Runtime/PBXTargetBuildContext.mm:759
    Details:  unexpected successful exit code from cancelled command <C0026:'CpResource Release_learner-live.xcconfig':P14>
    Object:   <PBXTargetBuildContext: 0x7fbf3a459b80>
    Method:   -createCommandInvocationRecordFromInvocation:
    Thread:   <NSThread: 0x7fbf3bc57e40>{number = 23, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **
```

```bash
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug-Learner ===
    Debug_learner.xcconfig line 2: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    Debug_learner.xcconfig line 2: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug-Learner ===
    error: /Users/arthuryessayan/FlutterProjects/mobile/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig: No such file or directory

Could not build the application for the simulator.
Error launching application on iPhone Xs.
```

Output for flutter doctor -v 

```bash
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-AM)
    • Flutter version 1.9.1+hotfix.6 at /Users/arthuryessayan/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/arthuryessayan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (3 available)
    • AOSP on IA Emulator • emulator-5554                            • android-x86 • Android 9 (API 28) (emulator)
    • Arthur’s iPhone     • 5b4664bd78df5d4cfccc682d6916bbxxxxxxxxxx • ios         • iOS 12.4.1
    • iPhone Xs           • 18659A3D-4493-47A9-A9AF-0970B35C0235     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

I also tried to move the .plist files in the "google" folder to "Runner" folder, but still no luck

<img width="720" alt="Screen Shot 2019-12-09 at 21 53 22" src="https://user-images.githubusercontent.com/4170315/70459821-6b0fbc80-1ace-11ea-8453-40bd25acbe1c.png">

**Comment by zmeggyesi** [comment]
Are you trying yo use _flavors_ in your build?

**Comment by arthuryess** [comment]
Yes, we use flavors

**Comment by zmeggyesi** [comment]
Flutters in iOS are a bit ... complicated. I won't pretend I know the answer, but you'll probably have to post the CLI command, as well as confirm whether or not you have specific build phases (to copy in the appropriate PLIST) in place in your project config.

**Comment by arthuryess** [comment]
Hey Zalan, thanks for your response. This is how the makefile looks like

==========================
build_learner_live:
	flutter build ios --release --flavor learner_live --target lib/main_learner_live.dart --build-name=1.3.0  --build-number=2974
#	flutter build ios --release --flavor learner_live --target lib/main.dart --no-codesign
    flutter build  apk --flavor learner_live --target lib/main_learner_live.dart --build-name=1.3.0  --build-number=2974


build_learner:
   flutter build ios --release --flavor learner --target lib/main_learner.dart
   flutter build  apk --flavor learner --target lib/main_learner.dart --build-name=1.3.0 --build-number=2974


build_instructor:
	flutter build ios --release --flavor instructor --target lib/main_instructor.dart
	flutter build  apk --flavor instructor --target lib/main_instructor.dart --build-name=0.18.068 --build-number=937





build_instructor_live:
	flutter build ios --release --flavor instructor_live --target lib/main_instructor_live.dart --build-name=1.3.0 --build-number=4
    flutter build  apk --flavor instructor_live --target lib/main_instructor_live.dart --build-name=0.18.066 --build-number=836





build_instructor_debug:
	flutter build ios --flavor instructor_live --target lib/main_instructor_live.dart

build_learner_beta_debug:
	flutter build ios --flavor learner_live --target lib/main_learner_live.dart
==========================

we use "build_learner", so the CLI command should be
flutter build ios --release --flavor learner --target lib/main_learner.dart

I didn't quite get what you meant by saying "as well as confirm whether or not you have specific build phases (to copy in the appropriate PLIST) in place in your project config"
but in the XCode the learner target is selected if you meant that
<img width="356" alt="Screen Shot 2019-12-09 at 22 33 24" src="https://user-images.githubusercontent.com/4170315/70462433-474f7500-1ad4-11ea-9020-ebf2630640e1.png">

**Comment by zmeggyesi** [comment]
Like I said, I won't pretend to know what's wrong, but sitting next to my colleague also struggling with flavors, we had to set up a build phase in XCode to copy the PLIST relevant to the flavor to the root directory for the rest of the build to locate it.

**Comment by arthuryess** [comment]
Hey Zalan, thanks again for your help efforts, appreciate it a lot. In the "Build Phases" of my XCode I saw a script like this, but I'm not sure whether it is relevant to copying the appropriate .plist file.

<img width="1109" alt="Screen Shot 2019-12-09 at 22 58 32" src="https://user-images.githubusercontent.com/4170315/70464339-26891e80-1ad8-11ea-82e5-746c415dc694.png">

The error basically says the following
"Release_learner.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig"
when I ran the "flutter build ios --release --flavor learner --target lib/main_learner.dart" command from the CLI

**Comment by jmagman** [comment]
Do you have custom build configurations (something other than Debug, Release)?  Note this is different from your schemes/flavors.

https://guides.cocoapods.org/syntax/podfile.html#project
> It is possible also to specify whether the build settings of your custom build configurations should be modelled after the release or the debug presets. To do so you need to specify a hash where the name of each build configuration is associated to either :release or :debug.

Your `ios/Podfile` probably has:
```
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}
```

@arthuryess What files are in Pods/Target Support Files/Pods-Runner/ ?

**Comment by arthuryess** [comment]
Hey Jenn, thanks for your response. Here's how my ios/Podfile looks like

===============================
# Uncomment this line to define a global platform for your project
 platform :ios, '9.3'

 # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }

  return pods_ary
end

target 'Runner' do
  use_frameworks!

    pod 'Fabric', '~> 1.9.0'
    pod 'Crashlytics', '~> 3.12.0'
    pod 'FacebookSDK'

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

===========================

And here is the contents of the Pods/Target Support Files/Pods-Runner/  folder
<img width="953" alt="Screen Shot 2019-12-10 at 11 56 08" src="https://user-images.githubusercontent.com/4170315/70507134-2ecb7300-1b45-11ea-99c3-3435272251e4.png">

Pods/Target Support Files/Pods-Runner/  folder indeed doesn't contain file named  "Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig" as the compiler complains

**Comment by robinjohn** [comment]
Could be related to PODs residue. Try clean up Pods and reinstall PODS step from below. 
Or better, try all steps: 


Exit Xcode or other IDE that is open for this project.

Then flutter clean to delete the build residue:
* flutter clean

**Clean up Pods: 
* pod deintegrate
* delete all pod remains files if still present - Podfile.lock, Pods, <Project>.xcworkspace
* pod install**

If you are on Mac or Ubuntu or unix variant, you also may need to ensure files are Unix fileformat:
* Install dos2unix if you don’t have and then from the project root folder, execute: 
* find . -type f -exec dos2unix {} \;

If you have any script shared from windows in other location that is run in the project:
* dos2unix <that-script-file>

Open Xcode and ensure you use the right Build Config and the right target,
Product => Clean build 

See how it goes.

**Comment by jmagman** [comment]
@arthuryess were you on a VM by any chance?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
