### ISSUE TITLE
Atom: Flutter repo refactor/rename fails to DTRT

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4661]
I changed the name of the mainAxisSize parameter in the RenderFlex class in packages/flutter/lib/src/rendering/flex.dart. 

The reference to the method in updateRenderObject in the Flex classes in updateRenderObject() packages/flutter/lib/src/widgets/basic.dart was not updated although the analyzer didn't report an error.

Restarting Atom caused the error to be reported.

**Comment by pq** [comment]
/cc @scheglov 

I *think* this has to do with changes happening outside the IDE and I hope this has been fixed, though possibly not in an SDK that's made its way to flutter.

@HansMuller : could you re-open if this is still persisting?

Thanks!
