### ISSUE TITLE
Set up screenshot driver test with the device lab.

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#46622]
We should make the test in https://github.com/flutter/flutter/pull/46620 to run only on one iPhone to avoid flakiness.

/cc @digiter

**Comment by cyanglaz** [comment]
offline discussion, we will add a new capability for this test named: `ios/gl-render-image`

**Comment by digiter** [comment]
FYI, I have added "ios/gl-render-image" capability to mac14 and enabled that agent. The setup has successfully completed a sample run of the test.

**Comment by cyanglaz** [comment]
@digiter thanks for the quick turnaround. I'mg going to close this issue now!
