### ISSUE TITLE
[web][tests] Fix skipped firefox unit tests

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#46638]
flutter web engine unit tests will be running on firefox (as an addition to chrome) with PR: https://github.com/flutter/engine/pull/14267

The following tests are not skipped on Firefox since they were failing:

test/paragraph_test.dart: predictably lays out a multi-line rich paragraph (canvas measurement)
test/paragraph_test.dart: predictably lays out a single-line rich paragraph
test/paragraph_test.dart: predictably lays out a multi-line rich paragraph 
test/paragraph_test.dart: predictably lays out a single-line rich paragraph (canvas measurement)
test/engine/semantics/semantics_helper_test.dart: MobileSemanticsEnabler Not relevant events should be forwarded to the framework
test/dom_renderer_test.dart: replaces viewport meta tags during style reset 
test/text/font_collection_test.dart: FontManager Register Asset twice with special character slash
test/text/font_collection_test.dart: FontManager Register Asset twice with exclamation mark
test/text/font_collection_test.dart: FontManager Register Asset twice with coma
test/text/font_collection_test.dart: FontManager Register Asset twice with a digit at the start of a token
test/text_test.dart: should not set fontFamily to effectiveFontFamily for spans in rich text
test/text_test.dart: adds Arial and sans-serif as fallback fonts
test/text_editing_test.dart: TextEditingElement Can read editing state correctly
test/text_editing_test.dart: TextEditingElement Re-acquires focus
test/text_editing_test.dart: TextEditingElement Multi-line mode also works
test/text_editing_test.dart: HybridTextEditing Syncs the editing state back to Flutter
test/text_editing_test.dart: HybridTextEditing Multi-line mode also works
test/compositing_test.dart: parent child lifecycle build, retain, update, and applyPaint are called the right number of times
test/compositing_test.dart: parent child lifecycle build, retain, update, and applyPaint are called the right number of times

We should either: 
(1)  fix the code to run on firefox
(2)  add unit tests methods that cover the firefox case (These might all be the locations in the code we are using  BrowserEngine.Firefox check)

**Comment by nturgut** [comment]
Remaining items:

- [ ] dom_renderer_test.dart
- [ ] semantics_helper_test.dart
- [ ] text_test.dart
- [ ] scene_builder_test.dart
- [ ] text_editing_test.dart
- [ ] path_test.dart
- [ ] semantics_test.dart
- [ ] semantics_helper_test.dart

**Comment by ditman** [comment]
https://github.com/flutter/engine/pull/55045 removes the skip from semantics and text field tests, and the only remaining skips are in the HTML renderer that is [deprecated](https://github.com/flutter/flutter/issues/145954) (so I don't think we'll reenable those tests anyways)

I'm going to mark this issue as done when the PR above lands.
