### ISSUE TITLE
macOS: setState() freezes application when called from FFI callback

### ISSUE THREAD

**Issue by ethanblake4** [flutter/flutter#46633]
I'm trying to integrate a terminal library ([libvterm](http://www.leonerd.org.uk/code/libvterm/)) into a Flutter macOS app using dart:ffi.

I have the terminal library working perfectly when running from Dart directly. It also is functional with Flutter, however:
- I provide an FFI callback function to libvterm, which calls back into Dart when something changes on the screen (damage),
- This callback contains a call to setState, which updates the text in a Dart list,
- which is then supposed to render on the screen via a ListView.builder.

However, after the call to setState the application always **freezes for up to 1 minute** (but sometimes as short as 2 seconds) before updating the screen. While it is frozen, the application still **responds to gesture events immediately (when they contain print statements)** but doesn't update anything on the screen. 

**Resizing the app window unfreezes it immediately,** so to alleviate this problem I've used the FDE window_resize plugin to jitter the size of the window by 1 pixel after the call to setState. This works, but is obviously not an ideal long-term solution.

```
[✓] Flutter (Channel master, v1.13.1-pre.59, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.13.1-pre.59 at /Users/ethanelshyeb/fluttersdk/flutter
    • Framework revision e58dc16d7b (3 days ago), 2019-12-06 18:21:52 -0800
    • Engine revision e7b69ced2e
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a9c77229c2)

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ethanelshyeb/Library/Android/sdk
    • Android NDK at /Users/ethanelshyeb/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio 3.6 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.6 Preview.app/Contents
    • Flutter plugin version 41.0.3
    • Dart plugin version 192.7402
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 41.1.5
    • Dart plugin version 193.5233.116

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 20.0.2
    • Dart plugin version 172.4343.25

[!] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.14.3 18D109
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

**Comment by stuartmorgan** [comment]
Are there other sources of events that should cause redraws? It sounds like maybe the state mutation just isn't causing a redraw for some reason.

Also, what thread are you calling back into Dart from?

**Comment by ethanblake4** [comment]
@stuartmorgan 
Yes, there are. On further investigation:
- mousing over an `InkWell` anywhere seems to unfreeze the entire application, but **only** if an InkWell has been moused over at some (any) point prior to calling setState() from FFI. When I restart the app via Hot Restart or running it again, _don't_ mouse over any InkWell, and type something to trigger the FFI callback, I instead get this error being printed on every frame where the mouse moves until the app unfreezes: 
```
════════ (145) Exception caught by gesture library ═════════════════════════════════════════════════
'package:flutter/src/gestures/mouse_tracking.dart': Failed assertion: line 388 pos 14: '(targetState == null) == (targetEvent is PointerAddedEvent)': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════
```
- Other sources of events that call setState() do **run**, but the UI remains frozen. This includes `GestureDetector`s, `RawKeyboardListener`s, and `Listener`s. All of these get triggered (although GestureDetector and Listener experience the same first-run issue as InkWells) but the UI does not update, even if setState is called, until the app unfreezes at a later point.

I believe I'm calling back into Dart from the main thread, although I don't know how to verify this.

**Comment by ethanblake4** [comment]
I solved my issue by using a Future loop instead of a persistentFrameCallback. Feel free to close or leave open as needed.
