### ISSUE TITLE
DropDownButton underline is a long way away from the text it underlines.

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#4664]
Is there a way to make it be closer in space-limited contexts such as a configuration toolbar?

**Comment by eseidelGoogle** [comment]
We also just need to check the DropDownButton pixel exactly matches the spec:
https://material.google.com/components/buttons.html#buttons-dropdown-buttons

**Comment by eseidelGoogle** [comment]
Our sizes are just wrong.

Spec:
<img width="166" alt="screen shot 2016-06-22 at 2 55 35 pm" src="https://cloud.githubusercontent.com/assets/11857803/16285236/f4a1ee58-3889-11e6-8c4d-1ffb40cf82d4.png">
Flutter:
<img width="186" alt="screen shot 2016-06-22 at 2 59 29 pm" src="https://cloud.githubusercontent.com/assets/11857803/16285238/f5127916-3889-11e6-8e4b-566a8f71f214.png">

@HansMuller could you take this?

**Comment by Hixie** [comment]
The size of the arrow might be something I broke with the icon changes.

The underline is because _kBottomBorderHeight is set to 2.0. That looks intentional. I don't know where we got that from. The spec seems to use a hairline (0.0). Fixing the underline width might be as simple as replacing that 2.0 with 0.0.

**Comment by HansMuller** [comment]
I agree that the underline's size and position and the arrow's size don't match the spec. Will fix.

**Comment by eseidelGoogle** [comment]
I wrote a half-patch yesterday.  In case it's useful:
```
diff --git a/packages/flutter/lib/src/material/drop_down.dart b/packages/flutter/lib/src/material/drop_down.dart
index 6ea5a91..185570a 100644
--- a/packages/flutter/lib/src/material/drop_down.dart
+++ b/packages/flutter/lib/src/material/drop_down.dart
@@ -21,7 +21,7 @@ const double _kMenuItemHeight = 48.0;
 const EdgeInsets _kMenuVerticalPadding = const EdgeInsets.symmetric(vertical: 8.0);
 const EdgeInsets _kMenuHorizontalPadding = const EdgeInsets.symmetric(horizontal: 4.0);
 const double _kBaselineOffsetFromBottom = 20.0;
-const double _kBottomBorderHeight = 2.0;
+const double _kBottomBorderHeight = 1.0;
 const Border _kDropDownUnderline = const Border(bottom: const BorderSide(color: const Color(0xFFBDBDBD), width: _kBottomBorderHeight));
 
 class _DropDownMenuPainter extends CustomPainter {
@@ -324,7 +324,6 @@ class DropDownMenuItem<T> extends StatelessWidget {
   Widget build(BuildContext context) {
     return new Container(
       height: _kMenuItemHeight,
-      padding: const EdgeInsets.symmetric(horizontal: 8.0),
       child: new Baseline(
         baselineType: TextBaseline.alphabetic,
         baseline: _kMenuItemHeight - _kBaselineOffsetFromBottom,
```

**Comment by Hixie** [comment]
Pretty sure that should 0.0, not 1.0.

**Comment by impratik** [comment]
> How to remove the underline from DropDownButton ?
 Hi , Wrap your DropDownButton widget with DropdownButtonHideUnderline Widget to remove underline from DropDownButton .

**Comment by a7me63azzab** [comment]
@impratik  thanks

**Comment by temirfe** [comment]
> DropdownButtonHideUnderline

через ж*пу

**Comment by victornett** [comment]
> > How to remove the underline from DropDownButton ?
> > Hi , Wrap your DropDownButton widget with DropdownButtonHideUnderline Widget to remove underline from DropDownButton .

ty 🗡

**Comment by chirmac** [comment]
> > How to remove the underline from DropDownButton ?
> > Hi , Wrap your DropDownButton widget with DropdownButtonHideUnderline Widget to remove underline from DropDownButton .

Thank you so much

**Comment by IvanTanaka** [comment]
How to change the underline width from DropDownButton?

**Comment by josmarpav** [comment]
> How to remove the underline from DropDownButton ?

You could also modify theunderline 'property of DropdownButton by passing it an empty container.

`underline: Container (),`
