### ISSUE TITLE
Step by step setting up flutter and pub mirrors in china using Windows Operating System

### ISSUE THREAD

**Issue by zuherabud** [flutter/flutter#46641]
The Flutter team has a guide on how to setup flutter and pub mirrors but they used linux and macOS as an example i dont see any more details regarding Windows OS which is used by majority i guess please help with the step by step set up of the mirrors in Windows OS

**Comment by zuherabud** [comment]
The Flutter team has a guide on how to setup flutter and pub mirrors but they used linux and macOS as an example i dont see any more details regarding Windows OS which is used by majority i guess please help with the step by step set up of the mirrors

**Comment by iapicca** [comment]
Hi @zuherabud 
does this documentation solve the problem?
thank you

**Comment by zuherabud** [comment]
i have read the docs none of them has a guide on how to set up environment vars to let android studio fetch dependencies from mirror sites
thank you

**Comment by iapicca** [comment]
Hi again @zuherabud 
as stated in the docs, you may what to start 
downloading the latest stable version 
as 10th December 2019 this is the link from the docs linked above
https://storage.flutter-io.cn/flutter_infra/releases/stable/windows/flutter_windows_v1.9.1+hotfix.6-stable.zip

After that you may follow this [documentation ](https://flutter.dev/docs/get-started/install/windows) specific to windows installation, 
skipping `Get the Flutter SDK` that in your case should be done with the previous [link ](https://flutter.dev/community/china)I've provided you.

In what part of the setting are you experiencing difficulties?
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by xiaoas** [comment]
@zuherabud Hi, I was facing the same issue. I came up with this solution: 

in powershell, do:
```shell 
setx PUB_HOSTED_URL "https://pub.flutter-io.cn"
setx FLUTTER_STORAGE_BASE_URL "https://storage.flutter-io.cn"
```
Hope this helps. Regards.

**Comment by gujianxing** [comment]
> @zuherabud Hi, I was facing the same issue. I came up with this solution:
> 
> in powershell, do:
> 
> ```shell
> setx PUB_HOSTED_URL "https://pub.flutter-io.cn"
> setx FLUTTER_STORAGE_BASE_URL "https://storage.flutter-io.cn"
> ```
> 
> Hope this helps. Regards.

How can i back to default config ?

**Comment by venkatraj** [comment]
@gujianxing 
I'm beginner. I misspelled a package and after some search I came to this 'solution'.
After realizing my mistake I can't go back to original settings.
It really messed up things and even after reinstalling flutter, it isn't fixing anything. I couldn't create new projects, because pub get failed of wrong URL.

To answer your question:
Go to environment variables and delete the PUB_HOSTED_URL and FLUTTER_STORAGE_BASE_URL

**Comment by gujianxing** [comment]
> @gujianxing
> I'm beginner. I misspelled a package and after some search I came to this 'solution'.
> After realizing my mistake I can't go back to original settings.
> It really messed up things and even after reinstalling flutter, it isn't fixing anything. I couldn't create new projects, because pub get failed of wrong URL.
> 
> To answer your question:
> Go to environment variables and delete the PUB_HOSTED_URL and FLUTTER_STORAGE_BASE_URL

Thanks for your reply, I have resolved the problem. As your description.

**Comment by neobug** [comment]
> > @gujianxing
> > I'm beginner. I misspelled a package and after some search I came to this 'solution'.
> > After realizing my mistake I can't go back to original settings.
> > It really messed up things and even after reinstalling flutter, it isn't fixing anything. I couldn't create new projects, because pub get failed of wrong URL.
> > To answer your question:
> > Go to environment variables and delete the PUB_HOSTED_URL and FLUTTER_STORAGE_BASE_URL
> 
> Thanks for your reply, I have resolved the problem. As your description.

老铁  这几个命令 应该在哪写啊？

**Comment by LulukFadiyah246** [comment]
i am beginner and i got same problem. I try to fix it by your instruction but still error. Can you help me?
Here is my powershell :
![image](https://user-images.githubusercontent.com/33032645/100806272-bc912400-3462-11eb-85fb-fd94927959e4.png)
My flutter 👍 
![image](https://user-images.githubusercontent.com/33032645/100806373-eba79580-3462-11eb-80bd-1f581a537286.png)

**Comment by adnanjpg** [comment]
apparently my computer's time was not synced with my timezone, and that was the obstacle to connect to  [https://pub.dartlang.org](https://pub.dartlang.org). try syncing your computer's time to your timezone.

**Comment by erperejildo** [comment]
should I do this if I'm based in Spain but getting this error?
`pub get failed (server unavailable) -- attempting retry 1 in 1 second...`

**Comment by RubenBenBen** [comment]
It literally just works 1 time in 4 hours, running from Poland.
