### ISSUE TITLE
On Android Device，Change  AppBar brightness cause widget rebuild

### ISSUE THREAD

**Issue by loumzy** [flutter/flutter#46651]
I have page whick change the AppBar brightness (Brightness.dark | Brightness.light) with page scrolling. but I face a problem, when changing the  brightness, widget will be rebuilt.

**Comment by iapicca** [comment]
Hi @loumzy 
If you are changing the state of your widget,
in some measure there need to be a rebuilding<
without seeing a sample code it's hard to tell if it's a bug.

Could  you please provide your `flutter doctor -v`
and a minimal code sample?
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
