### ISSUE TITLE
pub upgrade failed (255)

### ISSUE THREAD

**Issue by thetwobear** [flutter/flutter#46654]
D:\flutter\bin\flutter.bat --no-color packages upgrade
[0x7FFE295861E0] ANOMALY: meaningless REX prefix used
Running "flutter pub upgrade" in flutterlearn...                
******  B A T C H   R E C U R S I O N  exceeds STACK limits ******

Recursion Count=317, Stack Usage=90 percent

******       B A T C H   PROCESSING IS   A B O R T E D      ******
pub upgrade failed (255)
[0x7FFE295861E0] ANOMALY: meaningless REX prefix used
Process finished with exit code 255

**Comment by iapicca** [comment]
Hi @phoelapyae69 
can you please provide your `flutter doctor -v`?
Thank you

**Comment by thetwobear** [comment]
When I reinstall the computer system, there is no 255 error in my development environment

**Comment by iapicca** [comment]
Hi @thetwobear 
I'm glad that you solved the issue
thank you for letting me know
