### ISSUE TITLE
path_provider e2e test flakes on firebase test lab

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#46656]
First run failed:
https://cirrus-ci.com/task/5293677936640000?command=main#L2259

Re-run passed:
https://cirrus-ci.com/task/5445221805981696

@collinjackson

**Comment by collinjackson** [comment]
[Plugins post-submits](https://cirrus-ci.com/build/6272587911135232) and [FlutterFire post-submits](https://cirrus-ci.com/build/5204802468577280) both appear to be green after the following change.

https://github.com/flutter/plugin_tools/pull/91
https://github.com/flutter/plugin_tools/pull/89
https://github.com/flutter/plugin_tools/pull/85
https://github.com/flutter/plugin_tools/pull/86

I'm closing this issue out for now, but feel free to reopen or file new issues if additional flakes are encountered.
