### ISSUE TITLE
UikitView use large memory, and may cause jank. 

### ISSUE THREAD

**Issue by luoyibu** [flutter/flutter#46666]
##  flutter --version 
Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (3 个月前) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

### I found that the Uikitview has big performance at memory use. 
the simple test demo is here: [platform_view_profile](https://github.com/luoyibu/platform_view_profile). The platform view is just a single UIView with red background color. And I try the instrument for allocation. The result is like this:

![](https://tva1.sinaimg.cn/large/006tNbRwgy1g9rrajphopj30xc0k8q3z.jpg)

The one instance of UikitView will result in 45M use of memory, what ever the UikitView size is. The huge memory use is unacceptable when I want to place the Uikitview in Listview item.
I dig into the flutter engine, and found that the screen size overlay view was add for every UikitView. And the overlay view has 10M gl buffer，10M offscreen buffer，20M while copy from offscreen to onscreen.

![](https://tva1.sinaimg.cn/large/006tNbRwgy1g9rrb6uoqtj30xc03pjrl.jpg)

### not only the memory, when the count of Uikitview increase, the frame drops happen.
The instrument of time profile show that, the offscreen draw and the copy from offscreen to onscreen surface is the bottleneck.

![](https://tva1.sinaimg.cn/large/006tNbRwgy1g9rrbwkm71j30xc0emtad.jpg)

Wish a good solution to the performance issues of platform view

**Comment by iapicca** [comment]
Hi @luoyibu 
are you still experiencing the issue with the latest stable version of flutter?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
