### ISSUE TITLE
[web] [gallery] Support video playback

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#46669]
I just blindly assumed that adding the `video_player_web` dependency in https://github.com/flutter/samples/pull/170 would be enough but some more stuff is needed and it would make sense to fix it in this repo instead of in the web samples:

- The connectivity plugin used in [video_demo.dart](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/video_demo.dart ) is not available on the web.

- We can not use `dart:io` on the web.

- Adding `video_player_web` will not be needed once https://github.com/flutter/plugins/pull/2370 is merged.

@ditman I offered to fix this but you mentioned in https://github.com/flutter/plugins/pull/2384 that you were also playing with this. Do you want to take this? I wouldn't mind as I am not sure what the nicest solution to the `dart:io` problem would be.

**Comment by ditman** [comment]
Yes, I mostly have this working, let me update everything and try again. BTW I did this in flutter/flutter, not flutter/samples (I can backport the fix to flutter/samples as well)

**Comment by ditman** [comment]
I have published a PR, but it probably won't get reviewed in a couple of days. I'll remove myself from this issue so it gets seen on triage, though!

**Comment by ditman** [comment]
The PR above has been merged; I'm closing this ticket. @hterkelsen is looking into an issue with clicks not being detected in the video on web.
