### ISSUE TITLE
Flutter connectivity package issue with ios and cellular data

### ISSUE THREAD

**Issue by guyzk** [flutter/flutter#46678]
I have an issue when running my app on an iPhone 8 Plus using ios v13.1.3.
When wifi is on the connectivity package correctly returns that the connection is currently "wifi", but when I turn off the wifi connection and move to my 4G cellular connection the package reports that the current connectivity is "none" even though I can access the internet on any other app.
This issue happened on all flutter versions from 1.0 up till 1.12.3 and up to connectivity package version 0.4.6+1

**Comment by iapicca** [comment]
Hi @guyzk 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Thank you

**Comment by guyzk** [comment]
[✓] Flutter (Channel beta, v1.12.13+hotfix.4, on Mac OS X 10.15.1 19B88, locale en-IL)
    • Flutter version 1.12.13+hotfix.4 at /Users/guyzion/flutter
    • Framework revision fb60324e6f (13 hours ago), 2019-12-09 15:58:15 -0800
    • Engine revision ac9391978e
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/guyzion/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/guyzion/Library/Android/sdk
    • Java binary at: /Users/guyzion/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/guyzion/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 10 (API 29) (emulator)
    • Avi's phone               • 5706fa97fab8bcb377ea0f26a974230813758f71 • ios         • iOS 13.1.3

• No issues found!

**Comment by shashikantshaale** [comment]
I'm facing same issue here, It's only detecting WiFi, ignoring cellular data.
Please fix this soon.

**Comment by iapicca** [comment]
Hi @guyzk 
are you still experiencing the issue with the latest stable version of flutter
and [connectivity 0.4.8+2](pub.dev/packages/connectivity)?
thank you

**Comment by pureimpro** [comment]
Hi @iapicca , it's not clear wether or not "Access Wifi Information" should be enabled in Xcode for IOS >= 13.
In my case "Access Wifi Information" is **NOT** enabled and both `NSLocationAlwaysAndWhenInUseUsageDescription ` and `NSLocationWhenInUseUsageDescription ` keys are aded to my Info.plist, but ConnectivityStatus returns `null` (working on ios simulator).
Is this normal ?

**Comment by sjghose** [comment]
My code using connectivity: ^0.4.8+2 and provider: ^4.0.0 with StreamProvider works flawlessly on Android and is able to instantly provide any changes. On IOS it returns Null for Wifi with the exact same code. I did also try with adding the two location keys (doesn't appear they are needed). My guess is the issue is probably related to the Provider package or stream since the Connectivity example in he documentation works with SetState on Ios just not with a Provider stream. I did also try adding updateShouldNotify: (_,__) => true to my StreamProvider with no success. Using Flutter 1.16.2.

**Comment by pureimpro** [comment]
> My code using connectivity: ^0.4.8+2 and provider: ^4.0.0 with StreamProvider works flawlessly on Android and is able to instantly provide any changes. On IOS it returns Null for Wifi with the exact same code. I did also try with adding the two location keys (doesn't appear they are needed). My guess is the issue is probably related to the Provider package or stream since the Connectivity example in he documentation works with SetState on Ios just not with a Provider stream. I did also try adding updateShouldNotify: (_,__) => true to my StreamProvider with no success. Using Flutter 1.16.2.

I also use connectivity package with stream provider, with the same null output...

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions
what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference
related issues
Thank you
