### ISSUE TITLE
updateEditingValue of TextInputClient called twice on Android

### ISSUE THREAD

**Issue by miguelpruivo** [flutter/flutter#46680]
When implementing `TextInputClient` on a class it has the `updateEditingValue` method which handles text editing for that input connection.

I've found that when typing on iOS, the method will trigger only _once_ per key tap, which is correct. However, on Android, it triggers twice for the exactly same key and value. This can result in some inefficient calls of `onChange` (when available) callbacks for example.

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale pt-PT)
    • Flutter version 1.9.1+hotfix.6 at /Users/miguelruivo/devtools/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
```

**Comment by iapicca** [comment]
Hi @miguelpruivo 
can you please provide you `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by miguelpruivo** [comment]
@iapicca the information that I've provided should be enough to reproduce this use case.

**Comment by goderbauer** [comment]
We will need need some code that reproduces this to debug this further.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by nikitadol** [comment]
@iapicca Hi
```dart
class Test extends StatefulWidget {
  @override
  _TestState createState() => _TestState();
}

class _TestState extends State<Test> {
  final c = TextEditingController();

  @override
  void initState() {
    super.initState();

    c.addListener(_l);
  }

  void _l() {
    print(c.text);
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: TextField(
          controller: c,
        ),
      ),
    );
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  return runApp(MaterialApp(
    home: Test(),
  ));
}
```
InputConnection behaves strangely. It does not save the input value. You can see it on GIF
![ezgif-3-cc5631ee08d4](https://user-images.githubusercontent.com/16593680/75791222-4fd6e500-5d7d-11ea-899b-457f23f93275.gif)

**Comment by iapicca** [comment]
Hi @nikitadol 
I'm not sure that the situation you are describing match this issue,
could you please open a new issue
providing your `flutter doctor -v` ,
your `flutter run --verbose` 
and the sample above.
Thank you

**Comment by nikitadol** [comment]
@iapicca 
#51947

**Comment by keepfocusontechnology** [comment]
I think maybe I have the same problem。When I click  the textField content.the TextEditingController listener sometimes call twice. And when my language is The Arab. The  TextEditingController`s selection may give me different value.
- this my log:
![image](https://user-images.githubusercontent.com/8263580/99671024-67d9ca80-2aac-11eb-9034-5f141157899a.png)

- this my Phone Screen capture,I just click the content once:

![image](https://user-images.githubusercontent.com/8263580/99671172-a1123a80-2aac-11eb-832e-056e0e2447a3.png)

- My code :

```
import 'package:flutter/material.dart';

import 'custom_rich_text.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'BugTest',
      home: ExampleWidget(),
    );
  }
}


class ExampleWidget extends StatefulWidget {
  ExampleWidget({Key key}) : super(key: key);

  @override
  _ExampleWidgetState createState() => new _ExampleWidgetState();
}





/// State for [ExampleWidget] widgets.
class _ExampleWidgetState extends State<ExampleWidget> {
  final TextEditingController _controller = new TextEditingController();
  
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _controller.addListener((_printLatestValue));
  }


  _printLatestValue() {
    print("_controller.value: ${_controller.selection}");
  }
  
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Padding(
            padding: EdgeInsets.only(left: 100,right: 100),
              child: new TextField(
                autofocus: true,
                onChanged: (String value) {
                  print("onChanged run ... $value");
                },
                maxLines: 10,
                minLines: 5,
                controller: _controller,
                decoration: new InputDecoration(
                  contentPadding: EdgeInsets.symmetric(horizontal: 10,vertical: 5),
                  hintText: 'Type something',
                  border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(5),
                      borderSide: BorderSide.none),
                  filled: true,
                  fillColor: Color(0xffaaaaaa),
                ),
              ),
            ),
          new RaisedButton(
            onPressed: () {
              showDialog(
                context: context,
                child: new AlertDialog(
                  title: new Text('What you typed'),
                  content: new Text(_controller.text),
                ),
              );
            },
            child: new Text('DONE'),
          ),
        ],
      ),
    );
  }
}


```


- flutter verson:
![image](https://user-images.githubusercontent.com/8263580/99671806-87252780-2aad-11eb-84bc-a1fd8dd11fd3.png)
