### ISSUE TITLE
Dependency of Image package on flutter_test must be updated to the latest version

### ISSUE THREAD

**Issue by fgadea** [flutter/flutter#46682]
## Steps to Reproduce

1. Create a new flutter project

2. import Image package dependency on pubspec.yaml `image: ^2.1.9`

3. Run Packages get: `flutter pub get`

**Target Platform: All**
**Target OS version/browser: All**
**Devices: All**

## Logs
It won't compile, log of flutter pub get:
```bash
Because every version of flutter_test from sdk depends on image 2.1.4 and optic_v2 depends on image ^2.1.9, flutter_test from sdk is forbidden.
So, because optic_v2 depends on flutter_test any from sdk, version solving failed.
Running "flutter pub get" in optic_v2...                                
pub get failed (1; So, because optic_v2 depends on flutter_test any from
sdk, version solving failed.)
```

## Flutter analize
```bash
Because every version of flutter_test from sdk depends on image 2.1.4 and optic_v2 depends on image ^2.1.9, flutter_test from sdk is forbidden.
So, because optic_v2 depends on flutter_test any from sdk, version solving failed.
Running "flutter pub get" in optic_v2...                                
pub get failed (1; So, because optic_v2 depends on flutter_test any from
sdk, version solving failed.)
```

## Flutter doctor
```bash 
[✓] Flutter (Channel master, v1.13.1-pre.80, on Mac OS X 10.15.1 19B88,
    locale en-ES)
    • Flutter version 1.13.1-pre.80 at
      /Users/felipegadeallopis/development/flutter
    • Framework revision 2fe9623c36 (4 hours ago), 2019-12-10 04:22:32
      -0500
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
    • Android SDK at /Users/felipegadeallopis/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 41.1.5
    • Dart plugin version 193.5233.116

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome
      78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by iapicca** [comment]
Hi @fgadea 
if we are talking about the 3rd party plugin [image](https://pub.dev/packages/image)
on `master ` I've run  `flutter pub get`

I initially got this error 
```bash 
[eleventh_december] flutter packages get
Running "flutter pub get" in eleventh_december...               
Because every version of flutter_test from sdk depends on image 2.1.4 and eleventh_december depends on image ^2.1.9, flutter_test from sdk is forbidden.
```

just for science, I'm not recommending it,  I've removed `flutter_test`
```yaml
dependencies:
  image: ^2.1.9
  flutter:
    sdk: flutter

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
```
and run it again successfully
```bash
[eleventh_december] flutter packages get
Running "flutter pub get" in eleventh_december...                   1.0s
exit code 0
```

moreover since it's a 3rd party you might want to open an issue in the dedicated [github](https://github.com/brendan-duncan/image/issues)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by fgadea** [comment]
Thank you @iapicca 
Removing `flutter_test` from `dev_dependencies` it could be a temporal solution. I hope flutter team updates that dependency on flutter_test as soon as possible.
Than you 😉

**Comment by alvinthen** [comment]
Any plan to upgrade the image package? It seems like the image package is only used for golden image comparison. An upgrade from 2.1.4 to ^2.1.11 doesn't break, at least on the flutter_test package.

Would love to send in a PR, but I couldn't find a proper way to upgrade the image across all packages.

**Comment by vinicioslc** [comment]
i will fall in love if someone do this

> Any plan to upgrade the image package? It seems like the image package is only used for golden image comparison. An upgrade from 2.1.4 to ^2.1.11 doesn't break, at least on the flutter_test package.
> 
> Would love to send in a PR, but I couldn't find a proper way to upgrade the image across all packages.

**Comment by erperejildo** [comment]
what is `flutter_test` used for? Didn't notice any change after removing it

**Comment by fgadea** [comment]
> what is `flutter_test` used for?

It is for testing purposes like unit testing

**Comment by vinicioslc** [comment]
In my case i had moved the image processing to serverside api giving me more flexibility and removed the image dependency.

**Comment by jonahwilliams** [comment]
Pull requests welcome!

**Comment by willvlad** [comment]
Same issue

**Comment by jonahwilliams** [comment]
Fixed by https://github.com/flutter/flutter/pull/54144
