### ISSUE TITLE
Round slider dial background intermittently inverted.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#46691]
https://buganizer.corp.google.com/issues/142280381. 

cc @cbracken

**Comment by cbracken** [comment]
Reassigned to @chinmaygarde to mirror internal assignment. Underlying issue is being resolved by a Skia patch.

**Comment by chinmaygarde** [comment]
I am removing the TODAY tag as the suggested workarounds have been applied to unblock the internal user and the fix in Skia [has landed](https://skia-review.googlesource.com/c/skia/+/259174) and is being rolled in. Will close this bug once the test to verify this in the engine has landed.
