### ISSUE TITLE
Race-like conditions exist in status bar updates

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#4669]
Right now, the system status bar is updated during `AppBar.build()`.  During a transition from one route to another, you have one `AppBar` in the route that's going away and another one in the incoming route -- both of which may be called to build.

In this scenario, the last widget to `build()` will control the status bar, which isn't right (as it may be the widget in the outgoing route).

@abarth @Hixie

**Comment by Hixie** [comment]
This will be fixed by https://github.com/flutter/flutter/issues/4630.
