### ISSUE TITLE
Add support for  the remaining Material two-finger gestures

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#467]
http://www.google.com/design/spec/patterns/gestures.html

Two-finger tap, drag
Two-finger long-press ("Example: None; this gesture is uncommon")
Two-finger long-press drag
Two-finger double tap
Two-finger rotate - simultaneously orbit both fingers around the center point

**Comment by Hixie** [comment]
We're going to close this because we've had no demand for these and it is just a grab bag of features. If you want a specific gesture, please file a new bug.
