### ISSUE TITLE
Bitcode generation issue for iOS builds

### ISSUE THREAD

**Issue by peroksid90** [flutter/flutter#46707]
Bitcode support has been added recently:
[#15288](https://github.com/flutter/flutter/issues/15288)

However, I have checked bitcode which gets generated for the test project 
Runner.app/Frameworks/App.framework/ 
and it looks like that is not "real" bitcode, but a Mach-O binary file instead.

There should be files like 1, 2, 3, 4,... of LLVM bitcode type and wrapper. And you should be able to process those using llvm-dis. However, we get a Mach-O binary there. 

I have used bitcode_retriever tool to extract xar files from Runner.app/Frameworks/App.framework/App:

```
shell $ bitcode_retriever App
arm.xar
arm64.xar

shell $ xar -xf arm64.xar
shell $ file 1
1: Mach-O 64-bit object arm64
```

If you did the same for Runner.app/Runner binary, you would get correct bitcode of LLVM bitcode type: 

```
shell $ bitcode_retriever Runner
arm.xar
arm64.xar

shell $ xar -xf arm64.xar
shell $ file 1
file 1
1: LLVM bitcode, wrapper
```

The root cause of that issue is that an assembly file got put as input for clang:
https://github.com/flutter/flutter/blob/fb69a393b886aa91d30b81f79a590653fb677a4b/packages/flutter_tools/lib/src/base/build.dart#L257

Clang produces correct xars that carry LLVM bitcode if you pass unmanaged code or llvm-bitcode, and set -fembed-bitcode flag (it is possible to re-create a binary containing bitcode from bitcode).

If it was possible to get Dart compiled into llvm-bitcode, it would be proper bitcode-enabled archives generated. 

Thus, even it is now possible to build projects with BITCODE_ENABLE=YES, the community I believe is still facing the following issues:

1. Compatibility with analysis tools such as Veracode
2. Use of app-hardening solutions (rely on bitcode)

I will deeply appreciate if you can look into that @dnfield. Cheers!

**Comment by dnfield** [comment]
We use assembly in several places.  Right now, at the least:

- The output of gen_snapshot is assembly for iOS builds. 
- In the engine binary, we have assembly coming in from libpng and from the Dart VM as well.

We don't really have a good way to avoid this.  There's been some experiments around having Dart generate LLVM, but I believe that was blocked on something and AFAIK it's not actively being worked on (/cc @a-siva or @mraleph who may know more).

Right now we basically tell LLVM to embed the assembly along side of bitcode, which I assume is resulting in what you're seeing.  In my understanding, this means the parts of the binary that can be bitcode (all of the C++ and Objective C/C++ for example) are allowed to be bitcode, and the rest is shoved into the binary.

It's not clear to me what impact this actually has.  Are you seeing failures when trying to use app hardening tools that rely on bitcode or Veracode?

**Comment by mraleph** [comment]
Yes, @dnfield is correct. We are not currently working (or having plans to work) on having Dart-to-bitcode compiler.

**Comment by peroksid90** [comment]
@dnfield , @mraleph, 

	Thanks for your help and time.

Embedding binary blobs in xar files instead of LLVM bitcode is a little bit contradictive with the idea around bitcode-enabled builds to the best of my understanding.

According to Apple (https://help.apple.com/xcode/mac/current/#/devbbdc5ce4f), including bitcode allows Apple to re-optimize your app binary in the future without any need for submitting a new version of your app to the App Store.

And when it comes to binary blobs, they are barely optimizable. 

I would also like to reference that article: https://www.highcaffeinecontent.com/blog/20190518-Translating-an-ARM-iOS-App-to-Intel-macOS-Using-Bitcode

In practice, you (or Apple) can easily take the bitcode blobs from your app and recompile them into a fully-functioning copy of your app, going from armv7 to armv7s, or arm64 to arm64e smoothly. As well as that, it saves up developers' efforts in having to recompile an ever-fatter binary of their own every time Apple tweaks their ARM chips.

That is not often obviously, but it is worth getting things in compliance with Apple's vision in my humble opinion. 

> It's not clear to me what impact this actually has. Are you seeing failures when trying to use app hardening tools that rely on bitcode or Veracode?

All the bitcode hardening tools work in the pretty same way: the bitcode gets extracted from the app binary; then it is being read and harden via LLVM API. After that an application being protected gets re-compiled from bitcode. 

And so, I have been looking into that deeply recently, and realized that there is a binary container that does not carry bitcode (as I provided details earlier). It gets re-compiled perfectly though thanks to the special logic in bitcode-rebuilder that handles such a special case with an embedded container not carrying bitcode. So technically, it is all good and it works, but again, ideally there were no binary blobs in the containers.

**Comment by jmagman** [comment]
https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes
> Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.
> 
> Xcode no longer builds bitcode by default and generates a warning message if a project explicitly enables bitcode: “Building with bitcode is deprecated. Please update your project and/or target settings to disable bitcode.” The capability to build with bitcode will be removed in a future Xcode release. IPAs that contain bitcode will have the bitcode stripped before being submitted to the App Store. Debug symbols for past bitcode submissions remain available for download. (86118779)

**Comment by jmagman** [comment]
Closing this, the only bitcode work we're going to do at this point is remove it.
