### ISSUE TITLE
iOS mDNS lookup fails until a dialog box is clicked

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#46704]
Splitting off from #41085.

With Catalina and iOS 13, iOS mDNS lookup is reported to fail until a prompt from macOS is approved to allow dart to accept incoming network connections.

This issue is to investigate and recommend a fix, or an error message from the `flutter` tool as appropriate.

@dnfield @christopherfujino @jmagman @tvolkert

**Comment by dnfield** [comment]
@christopherfujino and I were looking into this at one point. As I recall, our discussion was something like having the tool/doctor check if the current Dart binary had an exception allowed in the firewall or not. I don't think we had come up wiht a way to bypass the allow/deny box altogether though.

**Comment by dnfield** [comment]
I don't believe this is a regression though, or an engine issue..  Removing those labels.

**Comment by zanderso** [comment]
Adding back the regression label since vmservice connections used to work without doing this.

**Comment by dnfield** [comment]
Fair enough - although that was only because of log-scanning.  We always had this dialog pop up the first time you tried to run `flutter attach` using mDNS.

**Comment by christopherfujino** [comment]
And the doctor check wasn't a perfect solution either, because it is still dependent on the user recognizing the dialog and accepting.

**Comment by jmagman** [comment]
In https://storage.googleapis.com/flutter_infra/flutter/ac9391978e7c0693b75a82c219e059b6ffee35c4/dart-sdk-darwin-x64.zip (v1.12.13+hotfix.4) the dart binary isn't codesigned at all and doesn't have any networking entitlements like https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_network_client

**Comment by christopherfujino** [comment]
Good catch @jmagman, working on this!

**Comment by christopherfujino** [comment]
The next hotfix to beta will be codesigned, and have the additional networking entitlements which will resolve the dialog box popping up. The next dev release should also pick up the entitlements. I will close this issue when both the beta and dev releases are published.

**Comment by christopherfujino** [comment]
This is fixed on beta and the new stable release. Dev release should be very soon...

**Comment by christopherfujino** [comment]
This should now be fixed on dev, beta, and stable, due to the dart binary now being signed with network entitlements. The dialog will still pop up on master, however, due to https://github.com/flutter/flutter/issues/44372.

**Comment by christopherfujino** [comment]
It looks like due to a bug in the codesigning script, the appropriate entitlements were not added. Re-opening pending a fix to the codesigning process.

**Comment by zanderso** [comment]
@christopherfujino If it's still needed, let's track the codesigning script bug in a separate issue.

**Comment by christopherfujino** [comment]
Thanks @zanderso. This was indeed fixed and I forgot to double back and close this issue.
