### ISSUE TITLE
iOS mDNS lookup fails when mac firewall is enabled

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#46703]
Splitting off from #41085.

With Catalina and iOS 13, iOS mDNS lookup is reported to fail when the macOS firewall is enabled.

This issue is to investigate and recommend a fix, or an error message from the `flutter` tool as appropriate.

@dnfield @christopherfujino @jmagman @tvolkert

**Comment by christopherfujino** [comment]
This appears to be the same as https://github.com/flutter/flutter/issues/46704, and will thus also soon be fixed on the next releases to dev, beta, and stable (fixed by adding 2 networking entitlements to the dart binary). I will close both issues when the dev & beta releases are out.

**Comment by christopherfujino** [comment]
The fix for this (codesigning the dart binary with network entitlements) is now on dev, beta, and stable. Codesigning on master is still blocked by https://github.com/flutter/flutter/issues/44372.
