### ISSUE TITLE
ButtonTextTheme should have onPrimary option

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#46715]
`ButtonTextTheme` should have a `onPrimary` (and etc.) option, just like `colorScheme` has, this way the text inside a `RaisedButton` with a primary color and the background, would automatically get the right color for it's text, which is usually white or black, depending on the luminescence of the color, even if the `ThemeData.brighness` doesn't match the primary color.

Also, adding the option to set the actual color for text inside a button and thus be able to override any other options would be very much welcome.

**Comment by HansMuller** [comment]
@feinstein We're proposing a rather different approach for customizing the appearance of buttons in #54776. If you have time, we'd appreciate feedback on the proposal.

I'm going to close this issue in favor of #54776 .

**Comment by feinstein** [comment]
Ok Hans, I will take a look at it next week.
