### ISSUE TITLE
Flag emojis don't render properly on old android API

### ISSUE THREAD

**Issue by NicolasCaous** [flutter/flutter#46712]
I'm having a problem rendering flag emojis on old android versions. This a side by side image showing a comparison between an emulator with API 29 and an emulator with API 21 running the same code:

![Screenshot from 2019-12-10 16-27-07](https://user-images.githubusercontent.com/24411365/70563084-5d107900-1b6c-11ea-9644-5104ee52d28f.png)

Some flags are rendered: 
![Screenshot from 2019-12-10 16-46-40](https://user-images.githubusercontent.com/24411365/70563281-baa4c580-1b6c-11ea-8a66-8a4fe6d69abf.png)

Similar to #16960

## Steps to Reproduce

1. Create an android emulator using API 21 (5.0.2)
2. Render any emoji flag that is not supported (Ex: 🇧🇷)

**Target Platform:** Android
**Target OS version/browser:** 5.0.2 (API 21)
**Devices:** I don't have a physical device with API 21 to test with

## Logs

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.6 at /home/nicolas/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/nicolas/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /snap/android-studio/81/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/81/android-studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • SM J810M                  • 324d965c      • android-arm • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 5.0.2 (API 21) (emulator)

• No issues found!
```

**Comment by gaaclarke** [comment]
cc @jason-simmons @GaryQian

**Comment by GaryQian** [comment]
The flag emojis were added in 2015 as part of Emoji 1.0. API 21 dates to 2014, which means that those devices simply do not include fonts to render a lot of the flag emojis. There is not much we can do about this unfortunately!
