### ISSUE TITLE
Unable to run tests when pubspec uses Path packages on Dart 2.7 or greater

### ISSUE THREAD

**Issue by atreeon** [flutter/flutter#46723]
I have a dart only project that I am running in IntelliJ.  IntelliJ is using the version of dart made for Flutter.

Using v1.12.13 (current dev or v1.13.1-pre.89, master), when I run a test I get the following error message

> The ".dart_tool/package_config.json" file is not recognized by "pub" version, please run "pub get".

I run `pub get`, or `flutter pub get` again but I get the same error when I try to run the file again in IntelliJ.  

I'm really stumped so if anyone could help that would be great.

**Comment by atreeon** [comment]
I think it is if you have any path reference dependency in the pubspec.yaml file.
Anything like this fails with the above message if you try to run a dart test.
```
dependencies:
  test_dependency:
    path: ../test_dependency

```

**Comment by atreeon** [comment]
Dropping down to v1.9.1+hotfix.6 (stable) does work but being unable to run tests in the beta or dev channels is pretty debilitating.

**Comment by FaFre** [comment]
Got the same problem today most probably after running `flutter update-packages` on 1.12.13+hotfix.7

**Comment by goderbauer** [comment]
Does this still reproduce with the latest flutter version?

**Comment by jonahwilliams** [comment]
Without a response we're unable to make any progress. I'm closing the issue, but don't hesitate to file a new one if you have the time.

**Comment by mit-mit** [comment]
This looks related to https://github.com/dart-lang/pub/issues/2806#issuecomment-757910693 ?
