### ISSUE TITLE
Every time I run "flutter run" it uninstalls and reships the APK

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4672]
Right now my edit/refresh cycle on Android is really slow.

My workflow is as follows:
1. Run a bash script that does the following:
2. Dump the results of the most recent run of `flutter analyze --watch --write`, which is running in the background.
3. Run `flutter run -t lib/main.dart --route=/`
4. Watch the logs, interact with the app, fix a bug.
5. Kill the bash script and return to step 1.

Step 3, `flutter run`, is taking forever each time. The output includes the line "Uninstalling old version...", and it shows that for several seconds, so that's what I'm blaming.

The verbose logs show the following steps as being expensive:
```
  900 ms • adb -s ZX1G22KJ3C shell pm list packages io.flutter.gallery
 1062 ms • adb -s ZX1G22KJ3C uninstall io.flutter.gallery
11791 ms • adb -s ZX1G22KJ3C install -r build/app.apk
  848 ms • zip -q .../app.flx snapshot_blob.bin assets/flutter_logo.png ...
 4822 ms • adb -s ZX1G22KJ3C push build/app.flx /data/local/tmp/dev.flx
 1000 ms • adb -s ZX1G22KJ3C shell am start -a android.intent.action.RUN ...
```

These steps happen every time even if I skip step 4 (i.e. even if I make no changes to anything).

**Comment by devoncarew** [comment]
@tvolkert, the uninstall/reinstall change happened here: https://github.com/flutter/flutter/commit/51d4ab33243c7329d816dce2466a906739bcb902 - can you give a bit of context for that? I'm working if there's some way to solve the issue you were facing w/o a full uninstall.

@Hixie, can you try hitting `r` / `F5` in the console w/ `flutter run` running instead of stopping and starting the app? That'll effectively issue a `flutter refresh` against android devices.

**Comment by tvolkert** [comment]
Yeah, `flutter install` fails for iOS if you try to install over an existing app without uninstalling the old one first.  We could add a -[no]uninstall flag... if we did, could we make --uninstall the default on iOS but --nouninstall the default on Android?

**Comment by devoncarew** [comment]
Perhaps we can special case for iOS, and/or push the uninstalling-when-installing logic down into the iOS specific device code.

**Comment by eseidelGoogle** [comment]
Uninstall actually appears to be destructive on Android, as my Application
directory is deleted.  I ran into this with:
https://github.com/eseidelGoogle/flutter/commit/2cea20512ccfc1843eb29f2ee47e27791da5ee35

**Comment by Hixie** [comment]
Hitting "r" doesn't work because the steps I'm running above are being run inside an Emacs compilation buffer, which is non-interactive. Also, I want the analysis results in there, so I have to first exit the 'flutter' tool to print the analysis options.

Is there any way to tell flutter to refresh a running instance without having the flutter tool be the same instance that started it?

**Comment by devoncarew** [comment]
Not currently, but that's something we could add.

**Comment by devoncarew** [comment]
@tvolkert, can you look into making the uninstall-on-install logic iOS specific?

**Comment by tvolkert** [comment]
Sure

**Comment by tvolkert** [comment]
Actually, the code path for `flutter run` that calls `installApp()` is only run for Android devices, so the fix is gonna be pretty simple...
