### ISSUE TITLE
Add api.flutter.dev analytics for javadocs and objcdocs

### ISSUE THREAD

**Issue by xster** [flutter/flutter#46731]

**Comment by xster** [comment]
The dartdocs have usage data but the platform APIs docs don't

**Comment by digiter** [comment]
Triage: what is needed from infra team?

**Comment by xster** [comment]
I meant this to be a website infra feature request. Don't know if this is in a Flutter infra team queue. There are currently no google analytics reporting from the non-dart docs on our website.

**Comment by godofredoc** [comment]
Are these metrics still useful?
