### ISSUE TITLE
Build status should take into account re-running a failed test

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#46732]
Currently, when we re-run a devicelab test, the build dashboard goes green because the test is no longer red -- it's orange (re-running).  However, in such cases, we should treat the test as the status of whatever the first run was.  In other words, re-running a failed test should not make the tree go green until that test passes.

**Comment by CaseyHillers** [comment]
I am closing this in favor of https://github.com/flutter/flutter/issues/45735.
