### ISSUE TITLE
[connectivity] Add web support

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#46735]
We should support the `connectivity` plugin on web. We can use [this](https://api.dart.dev/stable/2.7.0/dart-html/Navigator/onLine.html) API from `dart:html` to check connection status.

**Comment by ditman** [comment]
@franciscojma86 is working on the federation part of this plugin currently.

**Comment by ditman** [comment]
I published a somewhat limited version of the plugin here:

https://pub.dev/packages/experimental_connectivity_web

Contributions to expand to other browsers are welcome! (Desktop browsers other than chrome might need a polyfill or similar)

**Comment by ditman** [comment]
`connectivity: 0.4.9` now has an endorsed implementation for web.
