### ISSUE TITLE
flutter gallery macos not git clean

### ISSUE THREAD

**Issue by xster** [flutter/flutter#46743]
On 1.12.13, check that flutter config doesn't have enable-macos-desktop. Run `flutter packages get`.

<img width="659" alt="Screen Shot 2019-12-10 at 6 38 42 PM" src="https://user-images.githubusercontent.com/156888/70586568-4eca5900-1b7c-11ea-87fc-29a8ba2335dc.png">

I would expect the new feature to not have side-effects until it's turned on.

**Comment by stuartmorgan** [comment]
Did you already have a `macos` folder in the directory you ran that command in? IIRC all of the file generation logic (for all platforms, not just macOS) is based on the presence of the platform folder.

**Comment by xster** [comment]
right, this may be a flutter_gallery specific problem (the macOS folder is source controlled in on beta). This may be a non-issue once the flag defaults to on. 

Otherwise, you may also want to just source control macOS/podfile in directly if macOS is already source controlled.

**Comment by stuartmorgan** [comment]
If flutter_gallery was checked in with a `macos` folder but without checking in the corresponding generated-but-not-ignored files, that is indeed a mistake in the gallery setup itself, rather than the tool.

**Comment by xster** [comment]
Indeed, this is a more marginal issue.

**Comment by timsneath** [comment]
Can repro on `stable` channel.
