### ISSUE TITLE
Memory leaks in `fml/platform/darwin`

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#46750]
Some objc objects are not released in this file. We need to fix those to avoid leaks.

One example would be `CAShapeLayer* clip = [[CAShapeLayer alloc] init];` is never released.

We should use `fml::CFRef` for all CoreFoundation objects.

**Comment by zhongwuzw** [comment]
https://github.com/flutter/engine/pull/14326
https://github.com/flutter/engine/pull/14275

**Comment by cyanglaz** [comment]
This seems to be fixed, closing the issue.
