### ISSUE TITLE
Add `HostDevice` and ability to `flutter run/drive` on it

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#4676]
A `HostDevice` is similar to `AndroidDevice` and `IOSDevice` but runs Flutter shell on the host machine instead of a real device or an emulator. We already do this for `flutter test`. This feature request is to extend this capability to other commands, especially `run` and `drive`.

Flutter tools should have an option to use a host device as a deployment target. Strawman:

```
flutter run -d host
flutter drive -d host
```

## Why?

**tl;dr** so we can run more tests on Travis as a pre-submit step

* smoke-test `flutter` sub-commands, such as `run` and `drive`
* sanity check our integration tests prior to sending them over to the device lab, such as:
  * performance tests
  * hot-reload dev cycle tests

/cc @devoncarew

**Comment by Hixie** [comment]
The document above isn't publicly visible.

**Comment by yjbanov** [comment]
@Hixie that document has a lot of stale info. I replaced the link with information that's still relevant.

**Comment by yjbanov** [comment]
Closing on the basis that we won't get to it any time soon.
