### ISSUE TITLE
Update Flutter Documentation for InputDecoration

### ISSUE THREAD

**Issue by Hinal1108** [flutter/flutter#46768]
Please update the flutter.dev documentation,
some of the classes are not supported in applications like:

InputDecoration(border:InputBorder()) // it is not found
InputDecoration(border:OutlineInputBorder()) // it is working instead of the above

So please update the documentation so we can easily find the classes, methods,etc..

**Comment by iapicca** [comment]
Thank you for reporting this @Hinal1108

**Comment by avk29** [comment]
Hi @iapicca , I would like to help out with this issue. Would appreciate if you could give me instructions for the same

**Comment by iapicca** [comment]
@TahaTesser can you follow up please

**Comment by iapicca** [comment]
@avk29
Anyone is welcome to submit a PR to improve the docs, you may want to refer to @TahaTesser for more info.
Thank you

**Comment by JaiAravindh-git** [comment]
I would like to be assigned to this issue.

**Comment by Roshan13046** [comment]
> I would like to be assigned to this issue.

Hi @JaiAravindh-git
what's the status of fixing this issue? 
Are you working on it?

**Comment by TahaTesser** [comment]
@Roshan13046
Feel free to file PR for this, it's been more than 2 months so I unassigned 
You don't need to be assigned to file PR, go ahead

**Comment by Abhishek01039** [comment]
@TahaTesser 
is this still valid issue?
Thanks

**Comment by TahaTesser** [comment]
@Abhishek01039 
Yes

**Comment by Abhishek01039** [comment]
Hello @TahaTesser 
can you please give me some hints?
Thanks

**Comment by talamaska** [comment]
I'm not sure where the problem with the docs is. InputBorder is just an Abstract class, it doesn't have any functionality. It just defines the interface for the Border that could be used in InputDecoration - OutlineInputBorder and UnderlineInputBorde. The error you should be able to see is that abstract classes cannot be instantiated.

**Comment by arafaysaleem** [comment]
I don't think this issue in docs exists as of today or either I am not looking in the right place. I went through the docs of `InputDecoration` and it does not contain incorrect references to `InputBorder()`. I think we close this @TahaTesser

**Comment by TahaTesser** [comment]
@arafaysaleem 
Thanks for looking into it.

For anyone, If the issue persists, please file a new issue.
