### ISSUE TITLE
Animated WebP with alpha displays incorrectly

### ISSUE THREAD

**Issue by leowang566** [flutter/flutter#46760]
## Steps to Reproduce

Use 

Image.asset('images/xx.webp')

to show an animated webp with alpha, then it displays with shadow or multi images --- incorrect effect.

Once alpha is removed, it displays well.

**Target Platform:**Android/iOS
**Target OS version/browser:**any
**Devices:**any

## Logs

```
```

```
```

```[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.2 18C54, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/tool/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

```

**Comment by leowang566** [comment]
Add: 

Animated WebP on Native displays well.

**Comment by iapicca** [comment]
Hi @leowang566 
can you please provide a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
