### ISSUE TITLE
Error while build app

### ISSUE THREAD

**Issue by androiddaniel** [flutter/flutter#46783]
hi.
i have a error in build flutter APK  

error:

C:\src\flutter\bin\flutter.bat --no-color build apk

**Comment by jmagman** [comment]
What error are you seeing?  Can we get the logs?

What's the output of `flutter doctor -v`?

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
