### ISSUE TITLE
Navigator push that doesn't redraw underlying screens in Tab Bar

### ISSUE THREAD

**Issue by danielgchap** [flutter/flutter#46780]
Hi all,

I have an application that has a bottom tab bar, with a center docked FAB. 
Here is that screen (Home.dart) with the screens. 

 
      bottomNavigationBar: FABBottomAppBar(
        centerItemText: '',
        color: Colors.grey,
        selectedColor: Colors.blueAccent,
        notchedShape: CircularNotchedRectangle(),
        onTabSelected: _selectedTab,
        items: [
          FABBottomAppBarItem(iconData: CustomAppIcons.pray_icon, text: 'First Screen'),
          FABBottomAppBarItem(
              iconData: CustomAppIcons.praise_icon, text: 'Second Screen'),
          FABBottomAppBarItem(iconData: CustomAppIcons.user, text: 'Third Screen'),
          FABBottomAppBarItem(
              iconData: Icons.format_list_bulleted, text: 'Fourth Screen'),
        ],
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      floatingActionButton: Visibility(
        visible: _fabVisible,
        child: _buildFab(context, key: _fabKey),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  
When the user tabs on the FAB it calls the following:

`String result = await Navigator.of(context).push(

      PageRouteBuilder(
        fullscreenDialog: true,
        // maintainState: true,
        transitionDuration: _fabDuration,
        pageBuilder: (context, animation, secondaryAnimation) => CreateScreen(),
        transitionsBuilder: (context, animation, secondaryAnimation, child) =>
            _buildTransition(child, animation, fabSize, fabOffset),
      ),`

The problem is, when the FAB is tapped, it redraws the First Screen, Second Screen, Third Screen and Fourth Screen. I obviously don't like this for memory performance issues. 

Is there a different navigator flow I can use to avoid this? I DO have the AutomaticKeepAliveClientMixin implemented already with the wantKeepAlive => true. 

Would love any input.

Thanks

**Comment by danielgchap** [comment]
This is kind of a 'good enough' work around for what I personally intended lol..

`showDialog(
      context: context,
      child: CreateScreen()
    );

**Comment by VladyslavBondarenko** [comment]
Hi @danielgchap 
is it still an issue? could you provide a **complete** minimal reproducible code sample?

**Comment by darshankawar** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
