### ISSUE TITLE
Brightness.light doesn't work in flutter channel master

### ISSUE THREAD

**Issue by qiuguian** [flutter/flutter#46781]
Brightness.light doesn't work in flutter channel master, why?  no matter what Brightness type  I set, the app status bar color is white. device: iphone 8 plus, ios 13.2.3.
![image](https://user-images.githubusercontent.com/7962840/70637393-1d33b980-1c72-11ea-93c8-f2fbc20f6103.png)

**Comment by TheJulianJES** [comment]
I think I already saw an issues about this, but this basically happens because you have system-wide dark mode enabled in iOS.
Since the app seems to be compiled with XCode 11, iOS forces the status bar to white by default (when dark mode is on).

**Comment by qiuguian** [comment]
@TheJulianJES  Thank you!  you are right!
