### ISSUE TITLE
[web] LUCI recipe for MacOS for Flutter Web Engine

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#46782]
We would like to run flutter for web tests in MacOS. Since we will be moving our tests to LUCI, we we should also prepare the LUCI recipe.

Have the first LUCI recipe:
- running on macOS container (Mojave or Catalina)
- running [felt tool](https://github.com/flutter/engine/tree/master/lib/web_ui/dev)
- with the 'licences' parameter under $ENGINE_PATH/src/flutter/lib/web_ui directory

example from cirrus CI: https://github.com/flutter/engine/blob/master/.cirrus.yml#L40

**Comment by godofredoc** [comment]
CC: @digiter is this something you can help with? I'll write docs for all the steps

**Comment by nturgut** [comment]
@digiter let me know if there is anything I can help with felt tool and web engine part in general

**Comment by godofredoc** [comment]
@nturgut can you please share the command for windows and linux and the version of the engine we need to build?

**Comment by godofredoc** [comment]
Recipe is complete,  windows and linux tests are running on presubmit.
