### ISSUE TITLE
version_checker is running on too many CI tasks

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#46799]
A version update failure fails the following presubmit tasks:

 - analyze
 - build-apks+java-test+firebase-test-lab
 - build-apps+drive-examples
 - build-ipas+drive-examples 
 - format 
 - test

It should only fail a single presubmit task

**Comment by godofredoc** [comment]
\cc @stuartmorgan is this something we would like to keep open?

**Comment by stuartmorgan** [comment]
I'm not sure what the current state is; I think it's worth keeping open to re-test and see if we're doing the same check in too many places.

**Comment by stuartmorgan** [comment]
As f as I know this is only running on one task now.
