### ISSUE TITLE
Your Xcode version may be too old for your iOS version, The service is invalid. AMDeviceSecureStartService

### ISSUE THREAD

**Issue by azamsharp** [flutter/flutter#46806]
I am getting the following error: 

I am using Xcode 11.1 and my device is running 13.2.3. 

```bash
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (19 hours ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

```

Error launching app. Try launching from within Xcode via:
    open ios/Runner.xcworkspace

```bash
Your Xcode version may be too old for your iOS version.
═══════════════════════════════════════════════════════════════════════════════════
2019-12-11 14:56:34.809 ios-deploy[66432:2876376] [ !! ] Error 0xe8000022: The service is invalid. AMDeviceSecureStartService(device, CFSTR("com.apple.debugserver"), NULL, &con)
Could not install build/ios/iphoneos/Runner.app on 584319f35bff0e6b9127fa572389aee5a3a4c615.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace
```

**Comment by RayZhuAU** [comment]
Have you tried checking that your app is verified on your physical device. On iPhone go to settings -> general -> device management

**Comment by azamsharp** [comment]
Yes it is verified

**Comment by agarny** [comment]
I am having the same problem. @azamsharp, have you managed to solve it?

**Comment by Arkangel12** [comment]
Does some one have a solution, i am having the same issue

**Comment by jmagman** [comment]
`AMDeviceSecureStartService` is a MobileDevice error.  Please update Xcode and try again.

**Comment by sinano1107** [comment]
i am having the same issue.
My xcode is latest 11.3.1
How do I solve this problem?

**Comment by agarny** [comment]
> i am having the same issue.
> My xcode is latest 11.3.1
> How do I solve this problem?

I also had that problem and the only solution that worked for me was to revert to iOS 13.3 from 13.3.1. A pain, but at least now it's working fine once again.

**Comment by jmagman** [comment]
This error means the version of Xcode you are using doesn't have the version of the SDK that your iOS device has installed.  If you are running a beta version of iOS, you may need the beta version of Xcode.

**Comment by agarny** [comment]
> This error means the version of Xcode you are using doesn't have the version of the SDK that your iOS device has installed. If you are running a beta version of iOS, you may need the beta version of Xcode.

When I had upgraded my iOS to 13.3.1, I had also upgraded my SDK to the corresponding version, but still no luck. FWIW, my iOS version is now 13.3 (i.e. not the latest version of iOS) and my SDK is 11.3.1 (i.e. the latest version), and it's all working fine.
