### ISSUE TITLE
Linking to other apps on Android can sometimes cause Flutter to leave leftover content over native content

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#46809]
https://b.corp.google.com/issues/146070562.

cc @chinmaygarde

**Comment by xster** [comment]
ummm sounds like buffers from a different process is being mixed up. @jason-simmons any ideas? The repros don't seem very straight forward unfortunately.

**Comment by jtmcdole** [comment]
Has there been any triage for this?

**Comment by zanderso** [comment]
Also https://b.corp.google.com/issues/154530076. @xster was there any follow-up? I am removing the priority so that we take a look at this together at our next triage meeting.

**Comment by xster** [comment]
@zanderso no, we haven't reproduced it yet.

**Comment by chinmaygarde** [comment]
The instructions in the last comment on the bug are fairly involved and require setting up the application in a test environment. @kf6gpe is going to followup on priorities and a reduced test case.

**Comment by GaryQian** [comment]
Since the internal bug was verified as resolved, I will go ahead and close this bug.
