### ISSUE TITLE
ReorderableListView: Allow using a simple drag on a drag handle

### ISSUE THREAD

**Issue by 12people** [flutter/flutter#46805]
## Use case
Both iOS and the [Material design guidelines](https://material.io/components/lists/#behavior) use a drag gesture on a drag handle as a way to reorder lists. Unfortunately, the ReorderableListView does not allow such behavior.

There is [a package](https://pub.dev/packages/flutter_reorderable_list) that allows this. However, as this is a part of the Material design guidelines as well as important for iOS support, it should be a behavior allowed by ReorderableListView.

## Proposal
A simple "dragUsingTrailing" parameter on ReorderableListView would suffice, allowing the user to drag items by dragging the trailing widget.

**Comment by phenax** [comment]
+1

**Comment by wdavies973** [comment]
+1

**Comment by darrenaustin** [comment]
Hey folks, we are ramping up a design to try to address this and other issues with `ReorderableListView`. We are tracking it with #66080 and in a [design doc](https://docs.google.com/document/d/1JzNtMQ-jnPnSHEBoi6IO0x2qMMylwhvRslEDcmqiwSs/edit#heading=h.pub7jnop54q0). Feedback welcome.

**Comment by darrenaustin** [comment]
With the recent refactoring of the `ReorderableListView` (PRs: #74299 and #74697), we have added automatic drag handles when running on the desktop (with a `buildDefaultDragHandles` property to turn it off). If this isn't what you want, you can add your own drag handle as a widget to each of your items with something like:

```dart
ReorderableDragStartListener(
  index: index,
  child: const Icon(Icons.drag_handle),
),
```
 
somewhere in the child's subtree.

**Comment by saurik** [comment]
@darrenaustin While I'm of course ostensibly satisfied by this feature being something I can manually opt into, I'm curious why this is only the default on desktop, given that Material Design clearly shows drag handles on reorderable lists in a mobile UI and this is also the convention on iOS... shouldn't this be something that, if users want to disable, they should have to manually turn off?

From https://material.io/components/lists#types:

![reorderable-material](https://user-images.githubusercontent.com/36743/112961974-bd795000-90fa-11eb-8f1d-33542baa3c07.png)

https://user-images.githubusercontent.com/36743/112962314-19dc6f80-90fb-11eb-9104-b4a840fded32.mp4
