### ISSUE TITLE
Feature Request: DatePickerFormField Widget

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#46826]
A normal use case for the [DatePicker](https://api.flutter.dev/flutter/material/showDatePicker.html) is to use it with a TextField and a Form to take date inputs. 

We could create a convenience widget that composes TextField or TextFormField with a DatePicker, since I would imagine that it is a common use case that can be simplified for developers.

cc/ @hillelcoren

**Comment by rahulraj64** [comment]
Totally agree. Currently, it's difficult to coordinate a TextField and the date picker like disable the editing, setting the date back to the Textfield, etc.  It would be great if you add TimePicker support too.

**Comment by Hixie** [comment]
This seems like something that should be relatively straight-forward to build; if a precanned version would be useful, it could be created as a package. Unless the material spec has such a widget, though, it's probably best not to have it in the core given the maintenance cost.
