### ISSUE TITLE
[Web] ClipRect works differently on Web

### ISSUE THREAD

**Issue by chingjun** [flutter/flutter#46829]
Discrepancy found in newly enabled screenshot tests for web in PR #46820

Got different results for multiple tests, see the attached zip file for all the screenshots.

Here's one of the screenshots:
Web:
![z_clip ClipPath](https://user-images.githubusercontent.com/1267593/70673753-88f93080-1c38-11ea-93e1-e81670d570d1.png)

Flutter tester:
![z_clip ClipPath png o](https://user-images.githubusercontent.com/1267593/70673754-88f93080-1c38-11ea-892a-29b1bd081325.png)

Test: test/widgets/clip_test.dart
List of screenshots: [clips.zip](https://github.com/flutter/flutter/files/3953319/clips.zip)

**Comment by ferhatb** [comment]
clip_test no longer has skips.

**Comment by monsieurtanuki** [comment]
I experienced something crazy on the web version of my app: some `Path`s were not correctly drawn, it looked like in some cases I could only see the bottomRight quarter of it (like a bottomRight clip rect on each path).
If I draw the `Path` on an empty canvas, no problem, but if before that I used `canvas.drawImageRect`, then I get the "last-quarter-only" bug for my `Path`s. Of course I have no problem for the same app on Android or iOS.

One thing seemed to solve that: draw a circle before drawing the path. Even a transparent circle.

It looks like there's some kind of operation like `drawImageRect` that sets an implicit clip rect on path for later, or something like that. And the `drawCircle` operation seems to clear this implicit clip rect.

Well, the point of my comment is that if you get the same crazy bug, try to draw something transparent, that may clear some flags that prevent the display to be OK.

And for people that develop flutter web: maybe there's something to investigate.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Mac OS X 10.15.5 19F101 darwin-x64, locale
    fr-FR)
    • Flutter version 1.25.0-8.3.pre at /Users/fabricefontaine/development/flutter
    • Framework revision 5d36f2e7f5 (8 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/fabricefontaine/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```
</details>
