### ISSUE TITLE
Crash after updating to Flutter 1.12

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#46825]
I just upgraded to:

Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (23 hours ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

And my app was running just fine before, this is my `main`:

```
void main() async {
  Crashlytics.instance.enableInDevMode = true;
  FlutterError.onError = Crashlytics.instance.recordFlutterError;

// THIS THROWS THE EXCEPTION
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

  bool isDebug = false;
  assert(isDebug = true);

  runZoned(
    () => runApp(MyApp()),
    onError: Crashlytics.instance.recordError,
    zoneSpecification: ZoneSpecification(
      print: (self, parent, zone, message) {
        if (isDebug) { // we only print in a debug build.
          parent.print(zone, message);
        }
      },
    ),
  );
}
```

The `await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);` throws an exception (`FlutterError`): 

>ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.

Stacktrace:
>0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
4      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:429:36)
5      SystemChrome.setPreferredOrientations (package:flutter/src/services/system_chrome.dart:236:35)
6      main (package:itineraty/main.dart:30:22)
7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
8      _rootRun (dart:async/zone.dart:1126:13)
9      _CustomZone.run (dart:async/zone.dart:1023:19)
10     _runZoned (dart:async/zone.dart:1518:10)
11     runZoned (dart:async/zone.dart:1502:12)
12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Before the upgrade this line of code didn't throw anything and my code executed just fine, is this a breaking change?

I fixed it by calling `WidgetsFlutterBinding.ensureInitialized()` before the offending line, as the exception message suggests.

**Comment by stuartmorgan** [comment]
Yes, this was [a breaking change](https://groups.google.com/forum/m/#!msg/flutter-announce/sHAL2fBtJ1Y/mGjrKH3dEwAJ)

Closing as this was a deliberate and announced change, rather than a bug.

**Comment by feinstein** [comment]
Perfect, thanks @stuartmorgan

**Comment by feinstein** [comment]
I tried to find the breaking change here: https://flutter.dev/docs/development/tools/sdk/release-notes/release-notes-1.12.13 but I can't, should it be updated?

**Comment by alod2019** [comment]
> should it be updated?
for sure it should. Many links there give me HTTP 404

**Comment by feinstein** [comment]
I got 404 too, but if I clicked to a new tab... But clicking to open on the same tab worked, go figure.
