### ISSUE TITLE
An app that runs IOS and Android does not work on web or macOS.

### ISSUE THREAD

**Issue by donaldww** [flutter/flutter#46821]
I built a flutter app that connects to a server (built in Go) using a socket connection via dart:io. The app works perfectly under IOS and Android, and has for the past year.

However, so far, it won't work as a web app. It compiles and looks perfect running in the browser, but does absolutely nothing when a user clicks on the connect button.

I built the same app for macOS after watching the flutter livestream. The macOS app also compiles and appears to runs perfectly, but it reports (OS Error: Operation not permitted, errorno = 1) when clicking on the connect button.

I would be very thankful if someone could point me in the right direction, to get this app to run — especially on macOS.

Thanks,
DW

**Comment by jmagman** [comment]
I don't know about web, but the macOS app is sandboxed.  So you would need to add any security entitlements required to open a socket, like [com.apple.security.network.server](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_network_server) or 
[com.apple.security.network.client](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_network_client)
See https://github.com/google/flutter-desktop-embedding/issues/546#issuecomment-529286551

**Comment by jmagman** [comment]
I suggest closing this issue and splitting issues for each respective platform so it can be triaged separately to different teams.

**Comment by stuartmorgan** [comment]
For the web, see https://flutter.dev/docs/development/platform-integration/web#can-i-use-dartio-with-a-web-app

Closing, since on macOS this is a local configuration error, and on web is a documented limitation.

**Comment by donaldww** [comment]
Thanks jmagman and stuartmorgan!

<key>com.apple.security.network.client</key>
<true/>

I added the above line to the Runner…entitlements files and the macOS program now works.

Cheers, DW
