### ISSUE TITLE
Update latest stable flutter version: App show white Screen in Android

### ISSUE THREAD

**Issue by KuPinsIT** [flutter/flutter#46839]
I use azure devops(Window machine) to build flutter app Android, I always use flutter channel stable and latest version, but when I update version v1.12.13+hotfix.5, my app is show full white screen and not working. I try to downgrade to version v1.9.1+hotfix.6 and it work successful. I'm still using latest version and not hardcode it. Please help me resolve this issue.

**Comment by tirth-aubergine** [comment]
Add `WidgetsFlutterBinding.ensureInitialized();` in `void main` before the `runApp` call.

**Comment by iapicca** [comment]
Hi @KuPinsIT 
did the solution proposed by @tirth-aubergine  solved the issue?
thank you

**Comment by KuPinsIT** [comment]
> Add `WidgetsFlutterBinding.ensureInitialized();` in `void main` before the `runApp` call.
@tirth-aubergine thank you, your solution work with me. Many thanks for that

**Comment by KuPinsIT** [comment]
> Hi @KuPinsIT
> did the solution proposed by @tirth-aubergine solved the issue?
> thank you

Yes, it work well with me.

**Comment by tirth-aubergine** [comment]
I'm glad I could help @KuPinsIT :smile:
