### ISSUE TITLE
DropdownButtonFormField has additional padding on top and bottom after upgrade to v1.12.13+hotfix.5

### ISSUE THREAD

**Issue by tirth-aubergine** [flutter/flutter#46844]
`DropdownButtonFormField` looks different after building my app against latest stable flutter. 

**After Upgrading to Flutter v1.12.13+hotfix.5**

<img src="https://imgur.com/NFf75Qy.png" />

**Before Upgrading to v1.12.13+hotfix.5 (I was using latest stable version prior to v1.12.13+hotfix.5)**

<img src="https://imgur.com/YyMp7BA.png" />

**Target Platform:** Ubuntu Mate
**Target OS version/browser:** Android Pie
**Devices:** Mi A1

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_IN)
    • Flutter version 1.12.13+hotfix.5 at /home/tirth/flutter
    • Framework revision 27321ebbad (28 hours ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/tirth/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/tirth/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/tirth/android-studio
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by HansMuller** [comment]
It would help if you could provide a  small self-contained app that demonstrates the problem. Note also: https://gist.github.com/ is a useful way to share the code.

**Comment by gabrielginter** [comment]
same issue here, I had to set the contentPadding in the decoration to improve its look, but still have some extra padding that I can't remove.

**Comment by tirth-aubergine** [comment]
@HansMuller Here is the example. If the below example is built against the latest flutter stable version then you'll get this issue. If it is built against the stable version prior to the latest stable then you won't see this issue.

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String _value = '1';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Container(
            margin: EdgeInsets.all(16),
            child: DropdownButtonFormField(
              decoration: InputDecoration(labelText: 'Input'),
              onChanged: (newValue) => setState(() {
                _value = newValue;
              }),
              value: _value,
              items: [
                DropdownMenuItem(
                  child: Text('1'),
                  value: '1',
                ),
                DropdownMenuItem(
                  child: Text('2'),
                  value: '2',
                ),
                DropdownMenuItem(
                  child: Text('3'),
                  value: '3',
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

<img src="https://imgur.com/yhQ80H2.png" width=300 />

## Other example I posted

`DropdownButtonFormField` looks different after building my app against latest stable flutter. 

**After Upgrading to Flutter v1.12.13+hotfix.5**

<img src="https://imgur.com/NFf75Qy.png" />

**Before Upgrading to v1.12.13+hotfix.5 (I was using latest stable version prior to v1.12.13+hotfix.5)**

<img src="https://imgur.com/YyMp7BA.png" />

**Comment by shihaohong** [comment]
There was recently a change to increase the minimum height of TextFields from 40px to 48px, and that resulted in some changes to `InputDecorator`, which is used by `DropdownButtonFormField`. [Here is the PR](https://github.com/flutter/flutter/pull/42449). 

If that's the case, if you set InputDecorator's `isDense` property to true, you should be able to get the original size. 

@justinmc would that change have caused this? That was the only thing I could find or think of.

**Comment by justinmc** [comment]
I just tried comparing the size of the dropdown on master vs. after reverting my PR (924e48e), and it was the same size.  TextFields did change size, though.  That PR seems suspicious, but I don't think it's affecting this.

isDense still might help, but it looks like a real regression.

**Comment by shihaohong** [comment]
Thanks for taking the look. After doing some more digging, I think that https://github.com/flutter/flutter/pull/36998 might be the culprit. After reverting that PR, the spacing seems to have fixed itself. 

I'll take a look a little later when I have the time. @sarbagyastha if you have the time, could you perhaps investigate this? My guess is that some added parameter's default value was not correctly translated.

**Comment by shihaohong** [comment]
Edit: Somehow I deleted my original comment, but here it is again:

Thanks for the help. I think I've narrowed it down to https://github.com/flutter/flutter/pull/36998. when I revert it, the spacing seems to fix itself. @sarbagyastha, if you have some time, could you take a look at what might be causing this issue? I plan on looking at it as well, but my first guess would be that some default parameter value was not properly translated

**Comment by shihaohong** [comment]
I figured it out -- `isDense` used to be true by default for DropdownButtonFormField, but is now false by default.

**Comment by tirth-aubergine** [comment]
Thank you @shihaohong, now I understand. :+1: I've observed this change in the master channel a few months back but when I saw it stable I was surprised.

**Comment by tirth-aubergine** [comment]
Thank you @justinmc :+1:

**Comment by cassioseffrin** [comment]
@shihaohong  take a look: ![Screen Shot 2020-06-30 at 10 58 17](https://user-images.githubusercontent.com/13109831/86135113-c59b5500-bac0-11ea-9f08-a745c586a112.png)

the 1st field (price) is a common TextField with OutlineInputBorder border;
the 2nd field (unit) is a Dropdown DropdownButtonFormField  with OutlineInputBorder border;

Even with isDense=true there is an extra padding  (8 pixes in total: 4 on top, 4 on bottom) between the labelText and the  widget that wraps the labelText and the Icon

in dropdown.dart line 1284 there is a method that calculates the height, the result is 24 if I set it to 16 the  DropdownButtonFormField render the same height of the TextField, however I think it's not correct to set it as a constant. I can't figure out where exactly this 8 pixels of extra padding is created.  

Line 1284 of dropdown.dart.
```
  double get _denseButtonHeight {
    final double fontSize =
        _textStyle.fontSize ?? Theme.of(context).textTheme.subtitle1.fontSize;
    return math.max(fontSize, math.max(widget.iconSize, _kDenseButtonHeight));
  }
```
I am in last stable release of Flutter (Channel stable, v1.17.4)

**Comment by HansMuller** [comment]
It seems unlikely that this is due to https://github.com/flutter/flutter/pull/59196, but it would be worth ruling out.

@cassioseffrin - please open up a new issue and include a small complete test app that demos the problem. Let us know if the problem exists in the latest version of Flutter. Thanks for the report!

**Comment by cassioseffrin** [comment]
@HansMuller, I don't think it's related to  #59196, int hist case the Text height is exactly the same. I actually have correct the widget dropdown.dart, just 1 line of code. May I could make make a PR?

The problem is the icon size calculation: see the result, both components are now with the exactly the same height.

![Screen Shot 2020-06-30 at 14 44 21](https://user-images.githubusercontent.com/13109831/86159400-ab716f00-bae0-11ea-9092-b31dd6f2b28c.png)

**Comment by HansMuller** [comment]
@cassioseffrin - I have opened a new issue for the bug you've reported: https://github.com/flutter/flutter/issues/60624. Please add new comments there, since this issue is closed.

**Comment by cassioseffrin** [comment]
Thks for opening the issue @HansMuller, I will continue there!

**Comment by meiraxx** [comment]
Any news on this issue? Currently, this issue no longer happens in the labelText, however, the errorText positioning does not join the label.

[
<img width="335" alt="errorTextDropdown" src="https://user-images.githubusercontent.com/25626434/122829664-31348e80-d2df-11eb-9706-8f63244ca8fd.png">
](url)

In the abve screenshot, the "Gender" DropDownButtonFormField errorText is positioned too far away, while the TextFormField is ok.
