### ISSUE TITLE
The large and long picture of 33080 pixels is displayed blank on the real machine and cannot be displayed. I also put the long picture like this on h5. Why does h5 come out without problems, and flutter can't?

### ISSUE THREAD

**Issue by lhgNB** [flutter/flutter#46847]
![0cd6870b4a8f66c055d4031e01dd7fb](https://user-images.githubusercontent.com/41946105/70689041-25313f00-1cee-11ea-9ac8-cfe82728fb79.png)

> 我在真机上显示空白，在模拟机上可以出来。

I display the blank on the real machine, and it can come out on the simulator.

**Comment by iapicca** [comment]
Hi @lhgNB 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
