### ISSUE TITLE
 flutter web start take a long time！

### ISSUE THREAD

**Issue by qiuguian** [flutter/flutter#46853]
flutter web project start take a long time！is there any way to make it better?

**Comment by iapicca** [comment]
Hi @qiuguian 
does the issue occur in `debug` or `release`?  
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
