### ISSUE TITLE
Document platform channel migration steps for the new embedding

### ISSUE THREAD

**Issue by MichaelSowah** [flutter/flutter#46855]
How do I migrate my method channels from my pre 1.12 flutter app to 1.12...my Main activity.java file looks quite different from the old one so please how do I migrate... where do I place what? Thanks

**Comment by axilesoft** [comment]
You can check the platform_channel example in the SDK.

**Comment by MichaelSowah** [comment]
Which SDK please

**Comment by axilesoft** [comment]
> Which SDK please

https://github.com/flutter/flutter/blob/master/examples/platform_channel/lib/main.dart

**Comment by xster** [comment]
We should update https://flutter.dev/docs/development/platform-integration/platform-channels to use the new embedding, and add some details for how to move existing method channel registrations in flutter.dev/go/android-project-migration

**Comment by MichaelSowah** [comment]
> > Which SDK please
> 
> https://github.com/flutter/flutter/blob/master/examples/platform_channel/lib/main.dart

@axilesoft Thanks

**Comment by xster** [comment]
The work remaining is to add some info for how to migrate the platform channel code to the new embedding in https://flutter.dev/go/android-project-migration

**Comment by jmagman** [comment]
@matthew-carroll @mklim You guys have more context, is this done?  I see https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects#changes-specific-to-add-to-app.

**Comment by matthew-carroll** [comment]
@jmagman I think this ticket still applies. First, the docs should be part of the website guide rather than the wiki. Second, those existing wiki docs don't cover platform channel communication.

**Comment by shinriyo** [comment]
how to update platform channels?

**Comment by xster** [comment]
Thanks for the tip @axilesoft and sorry all for the wait in the doc. https://flutter.dev/go/android-project-migration has been updated with an example for a custom platform channel usage migration.
