### ISSUE TITLE
tooltip_test.dart fails on iOS (and Mac host)

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#4685]
## Steps to Reproduce

`cd packages/flutter && flutter test test/material/tooltip_test.dart`

## Logs and Crash Reports

https://gist.github.com/tvolkert/7ec937a89ed5434eafad89495218e723

**Comment by tvolkert** [comment]
@HansMuller

**Comment by tvolkert** [comment]
I verified that running a live test on the iOS simulator produces the same failure, so this appears to be a difference in rendering between Android and iOS and thus a test catching a real issue.

**Comment by Hixie** [comment]
Do you have a pair of screenshots showing the difference? That's really weird. I don't understand how that could happen.
