### ISSUE TITLE
After IOS mobile phone takes a picture, clicking the picture will throw out "picker image error". Please check the comment for the picture

### ISSUE THREAD

**Issue by CNzhou97** [flutter/flutter#46851]
Look at the picture:
http://chuantu.xyz/t6/703/1576136740x1031866013.jpg

**Comment by iapicca** [comment]
Hi @CNzhou97 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
