### ISSUE TITLE
Error when trying to run demo app with Atom: cannot open $HOME/.packages

### ISSUE THREAD

**Issue by smanilov** [flutter/flutter#4686]
## Steps to Reproduce

1. Follow the setup here https://flutter.io/setup/
2. flutter create myapp
3. Start Atom
4. File > Open Folder...
5. Select myapp
6. Click on the run button

## Flutter Doctor

[✓] Flutter (on Linux, channel alpha)
    • Flutter at /usr/local/google/home/stanm/f/d/flutter
    • Framework revision 6d2d495369 (2 weeks ago), engine revision a943c732d5

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0)
    • Android SDK at /usr/local/google/home/stanm/Android/Sdk
    • Platform android-24, build-tools 24.0.0
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-123992248-123972143)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27

## Logs and Crash Reports

Atom displays an error message:

"
Title: Error running 'lib/main.dart'.
Message: FileSystemException: Cannot open file, path = '/usr/local/google/home/stanm/.packages' (OS Error: No such file or directory, errno = 2)
"

## Additional info

`flutter run` from the myapp directory successfully installs and runs the program on the target device.

**Comment by devoncarew** [comment]
@smanilov, nothing jumps out at me as an obvious issue. It's strange that it's looking in your home dir for the .packages file. You may try closing atom, changing to the project directory, and running:
- `flutter upgrade`
- `atom .`

That will ensure that the project has a .packages file and open atom on the current directory.

**Comment by smanilov** [comment]
@devoncarew, I actually got this error while I was trying to reproduce another one. Now when I test again, I get the initial one, which quotes:

"
Title: Error running 'lib/main.dart'.
Message: The null object does not have a getter 'buildMode'.

NoSuchMethodError: method not found: 'buildMode' Receiver: null Arguments: []
"

**Comment by smanilov** [comment]
After a `flutter update` I cannot reproduce this any more.

Here's my current `flutter doctor` output:

[✓] Flutter (on Linux, channel alpha)
    • Flutter at /usr/local/google/home/stanm/f/d/flutter
    • Framework revision 7a9fe01cb9 (20 hours ago), engine revision dedab3e6e7

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0)
    • Android SDK at /usr/local/google/home/stanm/Android/Sdk
    • Platform android-24, build-tools 24.0.0
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-128173541-128170350)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.32

Should I close the issue?

**Comment by devoncarew** [comment]
Thanks for re-checking the issue; I'll close.
