### ISSUE TITLE
Flutter web app is blank when deployed through firebase hosting with url_launcher_web

### ISSUE THREAD

**Issue by happyharis** [flutter/flutter#46861]
Created the boiler plate counter app and deployed through firebase hosting. It works.

However, when I add url_launcher and url_launcher_web package and re-deploy, the web app shows a blank screen.

**Comment by hqwlkj** [comment]
I also encountered this problem
```

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :url_launcher_macos.
     Required by:
         project :app > project :url_launcher
      > Unable to find a matching configuration of project :url_launcher_macos: None of the consumable configurations have attributes.
   > Could not resolve project :shared_preferences_macos.
     Required by:
         project :app > project :shared_preferences
      > Unable to find a matching configuration of project :shared_preferences_macos: None of the consumable configurations have attributes.
   > Could not resolve project :shared_preferences_web.
     Required by:
         project :app > project :shared_preferences
      > Unable to find a matching configuration of project :shared_preferences_web: None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Finished with error: Gradle task assembleDebug failed with exit code 1

```


Is there a good way to deal with it?

**Comment by iapicca** [comment]
Hi @happyharis and @hqwlkj 
can you please provide your `flutter doctor -v`?
Thank you

possibly related to https://github.com/flutter/flutter/issues/46767

**Comment by happyharis** [comment]
Hi @iapicca , here is `flutter doctor -v`

[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-SG)
    • Flutter version 1.12.13+hotfix.6 at /Users/haris/Development/flutter
    • Framework revision 18cd7a3601 (35 hours ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/haris/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.7.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • iPhone 11 Pro Max • ED8CD3DA-200E-4A27-AD8E-29C3F6494798 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
    • Chrome            • chrome                               • web-javascript • Google Chrome 79.0.3945.79
    • Web Server        • web-server                           • web-javascript • Flutter Tools

• No issues found!

**Comment by hqwlkj** [comment]
Hi @iapicca 

```

MacBook-Pro app % flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /usr/local/flutter
    • Framework revision 27321ebbad (2 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/yanghc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 42.0.4
    • Dart plugin version 193.5731

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 297F1EBD-45F0-42E7-845B-2BD64E4A74BC • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!

```

Did not find any abnormal prompt messages

**Comment by happyharis** [comment]
I try running `flutter run -d chrome --release`:

The web app is still blank. I went to inspect and there is 2 errors:

`Uncaught Assertion failed
    at Object.f (http://localhost:54379/main.dart.js:1635:3)
    at Object.P (http://localhost:54379/main.dart.js:1641:23)
    at http://localhost:54379/main.dart.js:9552:3
    at Jc.a (http://localhost:54379/main.dart.js:2408:71)
    at Jc.$2 (http://localhost:54379/main.dart.js:15896:23)
    at Object.a0 (http://localhost:54379/main.dart.js:2395:20)
    at Object.rk (http://localhost:54379/main.dart.js:9570:10)
    at http://localhost:54379/main.dart.js:35040:8
    at http://localhost:54379/main.dart.js:35035:55
    at dartProgram (http://localhost:54379/main.dart.js:35038:84)`

**Comment by buntagonalprism** [comment]
Hi @happyharis I seem to be having the same issue. The cause seems to be the `plugin_platform_interface` package used by URL launcher. I've got a workaround fix I'm currently using which you can apply by putting this at the bottom of your pubspec.yaml file
```
dependency_overrides:
  plugin_platform_interface:
    git:
      url: https://github.com/buntagonalprism/plugins.git
      ref: fix-platform-interface-token
      path: packages/plugin_platform_interface
```

Also you don't need to `url_launcher_web` in your pubspec any more - it's included by default with the base `url_launcher` since version `5.3.0`.

**Comment by happyharis** [comment]
@buntagonalprism It works! How did you figure it out? The errors was pretty obscure. Thank you for the tip on the `url_launcher_web`.

**Comment by happyharis** [comment]
Will close this as related to #46941

**Comment by buntagonalprism** [comment]
Hi @happyharis flutter team has release a fix - you can remove the `dependency_overrides` now and run `flutter pub get` and it should update `plugin_platform_interface` to version 1.0.1 ( you can check you've got that version in your `pubspec.lock` file)

**Comment by happyharis** [comment]
Thanks @buntagonalprism !

**Comment by kevan-mtl** [comment]
@buntagonalprism hi Alex,

I ran into the exact same problem as @happyharis:

My web app runs smoothly with flutter run, but shows a blank page when I try to host it on Firebase. Here are the errors I get:

```
Uncaught FormatException: SyntaxError: Unexpected token < in JSON at position 0
    at Object.c (http://localhost:5000/main.dart.js:2119:3)
    at Object.aI5 (http://localhost:5000/main.dart.js:4447:9)
    at a19.e2 (http://localhost:5000/main.dart.js:30325:26)
    at http://localhost:5000/main.dart.js:63530:12
    at an3.a (http://localhost:5000/main.dart.js:3493:71)
    at an3.$2 (http://localhost:5000/main.dart.js:27999:23)
    at amg.$1 (http://localhost:5000/main.dart.js:27991:30)
    at Rz.Br (http://localhost:5000/main.dart.js:29233:40)
    at Rz.kr (http://localhost:5000/main.dart.js:29235:30)
    at ahs.$0 (http://localhost:5000/main.dart.js:28429:13)
```

with more specifically:
`Could not load content for org-dartlang-sdk:///sdk/lib/_internal/js_runtime/lib/async_patch.dart (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)`

I don't understand since it seems this issue is closed and my `plugin_platform_interface` points to version 1.0.2 in my pubspec.lock. 

Any help would be greatly appreciated :))

**Comment by buntagonalprism** [comment]
Hi @kevan-mtl it doesn't sound like your issue is related - it looks like you have a JSON parsing problem somewhere. Try using `flutter run --release` to see if it's an issue specific to release builds for starters, and use Chrome developer tools and break on exceptions and explore the stack trace to see if there's some unexpected data. If you still can't pinpoint the problem please raise a new issue with a minimal sample app that reproduces the issue

**Comment by kevan-mtl** [comment]
hi @buntagonalprism , I think you are right. I was able to track the issue (or at least one of them) to the time_machine package that I'm using. Thanks for your help :)

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by michael-timi** [comment]
I ran into the same blank screen after hosting on firebase @happyharis  and @buntagonalprism 
on chrome inspect, I found this...
TypeError: Instance of 'minified:ef': type 'minified:ef' is not a subtype of type 'minified:dN'
js_primitives.dart:47     at Object.b (http://localhost:12568/main.dart.js:4095:3)
js_primitives.dart:47     at Object.aFH (http://localhost:12568/main.dart.js:4714:27)
js_primitives.dart:47     at js.aRX [as a] (http://localhost:12568/main.dart.js:4713:3)
js_primitives.dart:47     at yU.rq (http://localhost:12568/main.dart.js:65151:6)
js_primitives.dart:47     at uN.wA (http://localhost:12568/main.dart.js:68084:58)
js_primitives.dart:47     at uN.fb (http://localhost:12568/main.dart.js:68011:3)
js_primitives.dart:47     at uN.fb (http://localhost:12568/main.dart.js:68112:3)
js_primitives.dart:47     at Cv.xN (http://localhost:12568/main.dart.js:67800:3)
js_primitives.dart:47     at Cv.du (http://localhost:12568/main.dart.js:67759:16)
js_primitives.dart:47     at Cv.jw (http://localhost:12568/main.dart.js:67903:32)
5js_primitives.dart:47 Another exception was thrown: Instance of 'minified:fA<void>'


But I don't understand how I can go about fixing this
