### ISSUE TITLE
Web, Flickering black effect

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#46876]
I'm having weird black rectangle on my UI: 
<img width="1680" alt="Capture d’écran 2019-12-12 à 13 08 25" src="https://user-images.githubusercontent.com/2970449/70711502-fc0ab180-1ce1-11ea-8ffe-e4202f235016.png">

When moving around the textfield is flicker to the correct state and the black rectangle, here is the video:
[Enregistrement de l’écran 2019-12-12 à 13.13.45.mov.zip](https://github.com/flutter/flutter/files/3955665/Enregistrement.de.l.ecran.2019-12-12.a.13.13.45.mov.zip)

No problem on iOS, Android, MacOS. Just on web

## Steps to Reproduce

```
git clone https://github.com/mylisabox/lisa_flutter
cd lisa_flutter
flutter pub get
flutter pub run build_runner build --delete-conflicting-outputs
flutter build web
```
Open index.html (I have tested it in Chrome on Mac OS X Version 78.0.3904.108 (Build officiel) (64 bits))

My env: 
```
[✓] Flutter (Channel master, v1.13.1-pre.99, on Mac OS X 10.15.1 19B88, locale fr-FR)
    • Flutter version 1.13.1-pre.99 at /Users/jaumard/flutter_master
    • Framework revision 354f80b84a (12 hours ago), 2019-12-11 16:36:03 -0800
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jaumard/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 42.0.3
    • Dart plugin version 192.7761

[✓] Connected device (4 available)
    • iPhone 5s  • 7FBEACF7-A82B-4663-A9C7-A40FE7835A12 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac OS X 10.15.1 19B88
    • Chrome     • chrome                               • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server                           • web-javascript • Flutter Tools

• No issues found!

```

**Comment by yjbanov** [comment]
Can you please provide a screenshot from a non-web build of the app? What is it supposed to look like?

**Comment by jaumard** [comment]
Sure here is the Mac OS X version: 
<img width="1679" alt="Capture d’écran 2019-12-13 à 08 30 28" src="https://user-images.githubusercontent.com/2970449/70778564-ded9ef80-1d82-11ea-873e-a1c5fa707b4e.png">

**Comment by TahaTesser** [comment]
Hi @kf6gpe 
Can you please provide your `flutter doctor -v`  and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by kf6gpe** [comment]
Hi, @TahaTesser! I think the reporter to add the doctor output and the repro would be @jaumard. Thanks!

**Comment by TahaTesser** [comment]
Oops, sorry, mentions are broken from the last few months, whenever I type @, I get anyone but the author of the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
