### ISSUE TITLE
androidx-migration

### ISSUE THREAD

**Issue by salem-matloob** [flutter/flutter#46872]
I tried to migrate my flutter app to AndroidX however, I am getting the "No Usage Found" message and the migration did not work.

Still, when I run the app, it says that I should migrate.

How to resolve this,

Thanks

**Comment by aaronmyatt** [comment]
I am facing the same issue, this is a real blocker for my project 😿

**Comment by gawdevishal** [comment]
> I tried to migrate my flutter app to AndroidX however, I am getting the "No Usage Found" message and the migration did not work.
> 
> Still, when I run the app, it says that I should migrate.
> 
> How to resolve this,
> 
> Thanks

Did you open the Flutter Project Directory or the android directory within your Project?

In official docs it's mentioned to open the android directory which is inside your flutter project and then migrate

**Comment by kf6gpe** [comment]
Thanks for using Flutter! This is a support request, and it's better to engage the community with these --- please reach out to one of the forums at https://flutter.dev/support. I'm closing this issue as it appears not to be an issue with Flutter itself.
