### ISSUE TITLE
dart:ffi - expose dart_api.h to FFI modules

### ISSUE THREAD

**Issue by derolf** [flutter/flutter#46887]
Would it be possible to

```
#include "third_party/dart/runtime/include/dart_api.h"
```

from a c-file that is called by ffi?

**Comment by jonahwilliams** [comment]
cc @sjindel-google

**Comment by sjindel-google** [comment]
This should be possible, provided the `Dart_*` symbols are publicly exported from `libflutter.so`.

/cc @dcharkes

**Comment by derolf** [comment]
I tried the code from https://github.com/dart-lang/sdk/blob/c52acadd15f95e1367f03200206c549a52f81b94/tests/ffi/vmspecific_send_port_id_test.dart on iOS.

It failed. So, I guess the symbols are stripped.

**Comment by dcharkes** [comment]
@jonahwilliams this is a Flutter embedder thing, not a Dart thing if the symbols are not exposed.

**Comment by jonahwilliams** [comment]
Not sure, cc @cbracken

**Comment by hanabi1224** [comment]
Flutter FFI on IOS with statically linked prebuilt library does not work either, is it related? Please see https://github.com/flutter/flutter/issues/33227#issuecomment-566239011

**Comment by dcharkes** [comment]
We will solve this on the Dart side https://github.com/dart-lang/sdk/issues/40607.
