### ISSUE TITLE
Cocoon Stackdriver logs do not properly handle UTF16 characters

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#46899]
GCP Stackdriver only currently supports UTF8. Devicelab logs lose the fancy formatting from the Flutter logs.

There is currently no timeline for UTF16 support on Stackdriver.

**Comment by digiter** [comment]
Triage: stackdriver shows logs from other tasks, which is confusing. We might consider removing stackdriver.

**Comment by CaseyHillers** [comment]
@digiter can you close this when devicelab tasks are moved to LUCI?
