### ISSUE TITLE
mojoms (in sky_services) aren't getting dartdocs

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4689]
For example:
http://docs.flutter.io/flutter/activity_mojom/activity_mojom-library.html

**Comment by chinmaygarde** [comment]
Those are the generated files. Don't we provided documented wrappers for these anyway?

**Comment by Hixie** [comment]
They're generated files but presumably they can propagate the documentation from the originals.

We don't wrap all of them. For example, "activity" is a static global that exposes the class linked to above.

**Comment by abarth** [comment]
No longer a thing
