### ISSUE TITLE
Flutter Web and native code

### ISSUE THREAD

**Issue by ggolda** [flutter/flutter#46893]
Is it possible to call native functions (in C++) from Flutter Web? As I understand, plugins are currently not supported in Web applications and I haven't found any examples about how to call WASM modules. May be it is possible but documentation is outdated? Thanks!

**Comment by iapicca** [comment]
Hi @ggolda,
yours is a familiar question 
https://github.com/flutter/flutter/issues/41062
I'd say a good one ;)

I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

https://github.com/dart-lang/sdk/issues/32894
https://github.com/dart-lang/sdk/issues/37355
