### ISSUE TITLE
Support for BIDI: mirrored layouts

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#469]
http://www.google.com/design/spec/usability/bidirectionality.html

![Material Design spec BIDI Layout Example](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsb3NQTFZZVUI4WHM/usability_bidirectionality_mirror2.png)

**Comment by Hixie** [comment]
For the record, this isn't just trivial mirroring. For example, notice how even in that picture, some of the icons are mirrored (e.g. speaker icon) but not all (e.g. check mark).

**Comment by HansMuller** [comment]
That's right. The Material Design spec covers the details.

http://www.google.com/design/spec/usability/bidirectionality.html

**Comment by Hixie** [comment]
This bug is too general. I'll file individual bugs for specific features then track them at https://github.com/flutter/flutter/projects/17.
