### ISSUE TITLE
How to round corners/edges for the Material tab "line" indicator as seen in Google's updated apps

### ISSUE THREAD

**Issue by corylui** [flutter/flutter#46906]
Trying to round the corners/edges for the line indicator, but am not able to. Does anyone know how to do this? Most of Google's updated apps use this new look for their tab indicators.

![tabIndicator_short_1](https://user-images.githubusercontent.com/58793884/70738091-e3da6880-1cc8-11ea-83dc-816909bb5b97.gif)

**Comment by HansMuller** [comment]
You can make the selected tab indicator look however you like. Take a look at the TabBar indicator, indicatorColor, indicatorPadding, indicatorSize, and indicatorWeight properties.

**Comment by corylui** [comment]
Nevermind! I found it! Here's the link in case anyone is trying to use the same style tab indicators
https://pub.dev/packages/md2_tab_indicator

**Comment by HansMuller** [comment]
I'm going to close this issue per https://github.com/flutter/flutter/issues/46906#issuecomment-567141331
