### ISSUE TITLE
Disable Origin Policy CORS in Flutter web

### ISSUE THREAD

**Issue by amorenew** [flutter/flutter#46904]
## Use case

While calling a web service on Flutter web it will not work because of CORS Policy

## Proposal
I saw a chrome window when I start debugging a Flutter web application
I wonder if we could add a flag to disable the CORS policy
like `Flutter run -d web --no-cors`

`chromium-browser --disable-web-security --user-data-dir="[some directory here]"
`
https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

**Comment by jonahwilliams** [comment]
Disabling the CORS checks locally would lead to drastically different behavior between a debug and deployed application - you can't very well ask all users of your website to disable CORS locally. Adding this flag would be a mistake

**Comment by amorenew** [comment]
@jonahwilliams I wonder why web services work in Android debugging mode while there is no Internet permission in the Manifest file?
<uses-permission android:name="android.permission.INTERNET"/>

For sure the simple answer is easy debugging until adding the permission for the release version

**Comment by amorenew** [comment]
`This is not an "injection" at build time, but rather a separate manifest for debug builds
`
https://github.com/flutter/flutter/pull/22139

**Comment by jonahwilliams** [comment]
> Internet Permission for Android is the same as CORS in Chrome

It is absolutely not the same thing

**Comment by krunaldarji** [comment]
@amreniouinnovent flutter web working locally and remotely ? I am also facing this issue with flutter web but it works fine on Mobile

**Comment by amorenew** [comment]
@krunaldarji it is not a bug. it is security permission like when you call twitter from facebook then facebook is not allowed to call twitter.
So backend developer should allow you to call his web service from your localhost.
this security feature is for browsers only but not on mobile or postman.

**Comment by amreniouinnovent** [comment]
@jonahwilliams developers suggested using an extension or opening chrome with CORS disabled
So I have 2 questions:

1- Why the app is not launching as a new tab in the same browser? and is there any possibility I can change the default behavior? because the chrome instance which got launched doesn't have extensions like my default chrome.

2-How could I configure the app to run on Firefox instead of chrome?

**Comment by amreniouinnovent** [comment]
For the future, if we can launch in Firefox by default
open in the address bar `about:config`
then search for  `security.fileuri.strict_origin_policy` and make it `false`

**Comment by krunaldarji** [comment]
@amorenew But i hosted my website on Firebase also but still same problem any idea ? Or how to allow this api call from my localhost because i am using few microsoft sharepoint api's which i can't request Microsoft for modification.

Pls help.

**Comment by MOlechowski** [comment]
You can start flutter web server on random port using command flutter run -d web-server, and then go to localhost:port in your browser or you could use release app using following guide https://flutter.dev/docs/deployment/web

**Comment by krunaldarji** [comment]
@MOlechowski Thanks for your response but its giving below error:

**Comment by amreniouinnovent** [comment]
@krunaldarji In AWS you could whitelist a specific port
So I am sure Sharepoint has the same feature
By the way, you can Add the whitelisted port for every run in the launch.json file
```
"configurations": 
[{"name": "Flutter",
"request": "launch",
"type": "dart",
"args": ["--web-port","8080"]
}]

```

Sharepoint CORS https://techcommunity.microsoft.com/t5/SharePoint-Developer/SharePoint-Office-365-CORS-issue-REST-API-call-to-other/m-p/777557

**Comment by MohsinKhanSerpro** [comment]
Hi team
I am facing this CORS policy issue from last 2 month, still not able to figure it out how to fix

`Access to XMLHttpRequest at 'http://obuat-env.zuriwydraq.ap-south-1.elasticbeanstalk.com/api/v1/RegisterDevice' from origin 'http://35.154.115.156' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`

- I have hosted my flutter web app on AWS - Apache environment

please if you any solution please help me.

**Comment by deakjahn** [comment]
The solution: create a batch file (or whatever your platform calls the shell scripts) that calls Chrome with the appropriate command line:

    "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-web-security --user-data-dir="a-temp-location" %*

Set up an environment variable named CHROME_EXECUTABLE to point to this file. Flutter will then use this file to start Chrome.

**Comment by amorenew** [comment]
@deakjahn 
How flutter will use it? is it automatically?
> Flutter will then use this file to start Chrome.

**Comment by deakjahn** [comment]
Yes. Flutter checks this env variable before it launches Chrome. You can actually check this is you happen to try to start `flutter run -d chrome` on a system that doesn't have Chrome installed. Flutter will specifically ask you to either put it into the default location or to tell it where it is using CHROME_EXECUTABLE.

**Comment by BesartLaci** [comment]
@deakjahn your [script solution](https://github.com/flutter/flutter/issues/46904#issuecomment-629363145) workes like a charm 👍

**Comment by vyvee** [comment]
@deakjahn Thanks! I have adapted your [script solution](https://github.com/flutter/flutter/issues/46904#issuecomment-629363145) in Linux as described below and it works perfectly!

Create a `google-chrome-unsafe.sh` with the following content:

    #!/bin/sh
    /usr/bin/google-chrome-stable --disable-web-security --user-data-dir="A-TEMP-LOCATION" $*

It's better to create and use a dedicated folder in the home directory instead of `/tmp` for the temporary location, as Chrome will create some folders there to work properly.

Then, make it executable with `chmod a+x google-chrome-unsafe.sh`

The environment variable can be set in `~/.bashrc` or `~/.bash_aliases` (if included from `.bashrc`):
`export CHROME_EXECUTABLE=/path/to/google-chrome-unsafe.sh`

**Comment by JaiMistry** [comment]
> Yes. Flutter checks this env variable before it launches Chrome. If you try to start `flutter run -d chrome` on a system that doesn't have Chrome installed, Flutter will specifically ask you to either put it into the default location or to tell it where it is using `CHROME_EXECUTABLE` (this is actually how I learned of its existence :-) ).

Do I set the `User` or `System` environment variable to `CHROME_EXECUTABLE`? I tried both and running my web application with `flutter run -d chrome` still resulted in a CORS error.

**Comment by deakjahn** [comment]
I have it in System but it shouldn't actually matter. The Flutter doctor display shows the value when it sees it, try that first.

**Comment by devDeejay** [comment]
So disabling CORS in Chrome on my development machine will fix it, but once deployed release mode in production the user's wont face any CORS issue?

**Comment by deakjahn** [comment]
They will, unless you setup your servers properly. This is something you can't skip.

**Comment by jaggzh** [comment]
Would it help if we had "flutter -d web-server" accept additional headers, like:
  ````--web-header "Access-Control-Allow-Origin: my-ip-here"````

**Comment by jaggzh** [comment]
Why is this closed anyway?  Is there some solution I'm missing?
I ended up setting up a reverse proxy script to modify traffic headers (the flutter host/port are hard-coded near the top of the script).
(The script is from somewhere else on the web, but I modified it for py3.x and had to make some other changes to get it working.)
```
#!/usr/bin/env python

from http.server import BaseHTTPRequestHandler, HTTPServer
import argparse
import os
import random
import sys
import requests

hostname = "0.0.0.0";
hostport = "8989";

def merge_two_dicts(x, y):
    z = x.copy()   # start with x's keys and values
    z.update(y)    # modifies z with y's keys and values & returns None
    return z

def set_header():
    headers = {
        'Meow': hostname
    }
    return headers

class ProxyHTTPRequestHandler(BaseHTTPRequestHandler):
    protocol_version = 'HTTP/1.0'
    def do_HEAD(self):
        self.do_GET(body=False)

    def do_GET(self, body=True):
        sent = False
        try:

            url = 'http://{}:{}{}'.format(hostname, hostport, self.path)
            req_header = self.parse_headers()

            print(req_header)
            print(url)
            resp = requests.get(url, headers=merge_two_dicts(req_header, set_header()), verify=False)
            sent = True

            self.send_response(resp.status_code)
            self.send_resp_headers(resp)
            if body:
                self.wfile.write(resp.content)
            return
        finally:
            self.finish()
            if not sent:
                self.send_error(404, 'error trying to proxy')

    def do_POST(self, body=True):
        sent = False
        try:
            url = 'http://{}:{}{}'.format(hostname, hostport, self.path)
            content_len = int(self.headers.getheader('content-length', 0))
            post_body = self.rfile.read(content_len)
            req_header = self.parse_headers()

            resp = requests.post(url, data=post_body, headers=merge_two_dicts(req_header, set_header()), verify=False)
            sent = True

            self.send_response(resp.status_code)
            self.send_resp_headers(resp)
            if body:
                self.wfile.write(resp.content)
            return
        finally:
            self.finish()
            if not sent:
                self.send_error(404, 'error trying to proxy')

    def parse_headers(self):
        req_header = {}
        for line in self.headers:
            line_parts = [o.strip() for o in line.split(':', 1)]
            if len(line_parts) == 2:
                req_header[line_parts[0]] = line_parts[1]
        return req_header

    def send_resp_headers(self, resp):
        respheaders = resp.headers
        print('Response Header')
        for key in respheaders:
            if key not in [
                           'Content-Encoding',
                           'Transfer-Encoding',
                           'content-encoding',
                           'transfer-encoding',
                           'content-length',
                           'Content-Length',
                           'x-frame-options',
                           'x-xss-protection',
                           'x-content-type-options',
                           ]:
                print(key, respheaders[key])
                self.send_header(key, respheaders[key])
                # Response Header
                # date Fri, 29 May 2020 18:35:40 GMT
                # x-frame-options SAMEORIGIN
                # content-type text/html
                # x-xss-protection 1; mode=block
                # x-content-type-options nosniff
                # server dart:io with Shelf
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Content-Length', len(resp.content))
        self.end_headers()


def parse_args(argv=sys.argv[1:]):
    parser = argparse.ArgumentParser(description='Proxy HTTP requests')
    parser.add_argument('--port', dest='port', type=int, default=9000,
                        help='serve HTTP requests on specified port (default: 9000)')
    args = parser.parse_args(argv)
    return args

def main(argv=sys.argv[1:]):
    args = parse_args(argv)
    print('http server is starting on port {}...'.format(args.port))
    server_address = ('0.0.0.0', args.port)
    httpd = HTTPServer(server_address, ProxyHTTPRequestHandler)
    print('http server is running as reverse proxy')
    httpd.serve_forever()

if __name__ == '__main__':
    main()
```

**Comment by JaiMistry** [comment]
The solution I ended up following was to simply use a [CORS proxy url](https://github.com/Rob--W/cors-anywhere/) and append it to the beginning of my API endpoint URL. You can do something like this:
```dart
Future<Album> fetchAlbum() async {
  String proxy = 'https://cors-anywhere.herokuapp.com/';
  final response = await http.get(`${proxy}https://jsonplaceholder.typicode.com/albums/1`);
  if (response.statusCode == 200) {
    return Album.fromJson(jsonDecode(response.body));
  } else {
    throw Exception('Failed to load album');
  }
}
```

**Comment by BrendonW** [comment]
I really wish there was a simple solution to this. It makes developing my Flutter app that interacts with a legacy web-server very difficult. The simplest option would be to give a way of enabling other domains for the debug webserver that AndroidStudio starts, or give me away to enable source-maps in the standalone flutter webserver. 

I can proxy through a server, but then data errors result in incomprehensible errors because source maps never load.
OR
I can run directly out of Android Studio which gives me good errors, but then I can't test any network interactions. 

The arguments about fooling people into having problems in production is about as valid as saying that debuggers shouldn't be supported because it is not how production works. Making development difficult WILL NOT increase Flutter Web usage.

**Comment by jeansebastienZ** [comment]
So basically no viable solution for this?

**Comment by deakjahn** [comment]
A very simply batch file and it works. https://github.com/flutter/flutter/issues/46904#issuecomment-629363145 I've been using it since my first Flutter Web day and it's still perfect. :-)

**Comment by jeansebastienZ** [comment]
Hello @deakjahn  , This batch will be used on release version ?  If i did understand well no ? Because my problem is calling some webservice from my release version .

**Comment by deakjahn** [comment]
No, I thought you meant debugging, this is what the OP talked about. :-)

In release mode, you need correct CORS settings. I don't think Flutter can do anything about this, this is a browser security limitation. No webapp can override the security features of the browser; iof it could, that would make them completely useless.

So there is actually a web service not under your control that doesn't have correct CORS settings? If it is so, how is anybody supposed to use it, quite independent from Flutter?

**Comment by mateusfccp** [comment]
> @deakjahn Thanks! I have adapted your [script solution](https://github.com/flutter/flutter/issues/46904#issuecomment-629363145) in Linux as described below and it works perfectly!
> 
> Create a `google-chrome-unsafe.sh` with the following content:
> 
> ```
> #!/bin/sh
> /usr/bin/google-chrome-stable --disable-web-security --user-data-dir="A-TEMP-LOCATION" $*
> ```
> 
> It's better to create and use a dedicated folder in the home directory instead of `/tmp` for the temporary location, as Chrome will create some folders there to work properly.
> 
> Then, make it executable with `chmod a+x google-chrome-unsafe.sh`
> 
> The environment variable can be set in `~/.bashrc` or `~/.bash_aliases` (if included from `.bashrc`):
> `export CHROME_EXECUTABLE=/path/to/google-chrome-unsafe.sh`

This solution didn't work for me on macOS.

I made the following script:
```sh
#!/bin/sh
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-web-security --user-data-dir="a-temp-location" %*
```

And set the `CHROME_EXECUTABLE` variable correctly in my `.profile`.

When I start my Flutter Web app in debug mode it will correctly open the specified browser (as it will even show a warning about the usafe argument), however, Dart won't find it to attach the app and it won't ever start. The debugger will hang indefinitely as it is still building the app.

**Comment by deakjahn** [comment]
Did you leave `a-temp-location` verbatim? :-)

**Comment by mateusfccp** [comment]
> Did you leave `a-temp-location` verbatim? :-)

YES

**Comment by deakjahn** [comment]
A quick Googling seems to suggest that in sh, the variable to include all passed parameters is `$@`. I used `$*` on Windows but neither that nor your `%*` might be accepted in sh.

**Comment by pedromassango** [comment]
Hi guys, can you help me? I'm on Mac and this bash_profile is not working:
```
export PATH="$PATH:$HOME/dev/flutter/bin"
export CHROME_EXECUTABLE="~/google-chrome-unsafe"
```

What is wrong with it and how should I do that? When I run my IDE with this bash profile chrome is not being listed as device, but if I remove the last line it and restart the IDE it is being listed.

Cc: @mateusfccp, @deakjahn

**Comment by mateusfccp** [comment]
> A quick Googling seems to suggest that in sh, the variable to include all passed parameters is `$@`. I used `$*` on Windows but neither that nor your `%*` might be accepted in sh.

I tried with all three, but no results. Finally, I simply gave up doing this. This is the reason this issue exists, after all. :)

**Comment by pedromassango** [comment]
@mateusfccp can you show me how did you do with the bash_profile?

**Comment by pedromassango** [comment]
Thanks everyone I finally got it working on Mac.

**Comment by deakjahn** [comment]
Tell Mateus how. :-)

**Comment by pedromassango** [comment]
Here it is:

Device: Macbook Pro 
OS: macOS Catalina

1. Add this to `.bash_profile`:
`export CHROME_EXECUTABLE="/Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe"`

2. Create a shell-script file with this one single line:
`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-web-security --user-data-dir="tmp-dir" $*`

OBS: the `$*` is basically to allow Flutter to provide more flags so don't remove it.

**Comment by pedromassango** [comment]
@deakjahn I've updated my comment above.

**Comment by LSambo02** [comment]
I have followed the presented steps by @pedromassango using ```.bash``` executable
In which I had to add the extension to the ```.bash_profile``` like this
```export CHROME_EXECUTABLE="/Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe.bash"```

After that you should source the path of the ```.bash_profile``` and ```google-chrome-unsafe.bash```
it will open the unsafe chrome version, so it means you're good to go, if not restart your machine so the changes are applied

In my case when I ran the debug it didn't start, and running ```flutter doctor -v``` gives ```Permission denied```
You should run ```chmod +x  /Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe.bash```
In the app directory so it's able to execute the executable

Another scenario that might occur is to have a ```Permission denied errno = 13``` which states you can resolve by running ```flutter clean```, with more detailed view ```flutter clean -v``` but might not work as expected so you must delete the shown file manually on the correspondent paths, in my case were ```.dart_tool``` and ```build```. 
After that you just need to run it and should work, it will rebuild the project and run.

**Comment by amreniouinnovent** [comment]
@jonahwilliams Could you reconsider opening the issue as it got a lot of attention?
Thanks

**Comment by jonahwilliams** [comment]
no

**Comment by SRnandanan** [comment]
how to create the batch file like @deakjahn had mentioned??

**Comment by deakjahn** [comment]
Well, how do you normally create files? That way. :-)

**Comment by SRnandanan** [comment]
@deakjahn So what I did is, I opened Notepad, wrote those lines and saved it as a .bat file. And then in environment variables, I created a new variable called CHROME_EXECUTABLE and set its value as the path to my .bat file. And the request method, when I inspect the network tab has changed to POST instead of OPTION. Am I doing this right? Sorry I'm a complete noob :/

**Comment by deakjahn** [comment]
Unless you allow Notepad to save it as a .txt file. Use a proper programmer's text editor, preferably, but until then, rename the file after editing, if necessary.

Unfortunately, I have no idea at all what you mean by the request method and options. This should have nothing to do with something like that. Using this batch file simply means that Chrome is started with an extra option in the command line that makes it not observe the CORS requirement during debug runs. Which is basically a temporary solution because, in the long run, you have to make sure the server is set up to provide the required CORS settings, there's no way out of this requirement. This isn't a Flutter limitation at all, Flutter has nothing to do with it, it's a browser limitation and cannot be circumvented because that would make it dangerous and no browser vendor would ever do that.

**Comment by Rahulshahare** [comment]
### SOLUTION IS LISTED FOR WIKIPEDIA CORS ERROR
A api request to wikipedia from flutter web and the error was very simple the "**CORS error**".
as it happens i did what we all do "Search The Google" and to many result specially associate with flutter, but most important is so many issues are still not closed.

This person tries to understand what these errors are and why it happen. f**irebase, google storage CORS error** better check this out [on stackoverflow](https://stackoverflow.com/a/62900737) 

**wikipedia api CORS error** [check this out](https://stackoverflow.com/a/38921370).

**at my side** what i was missing was  a `&origin=*` url parametere with value

previous url  with error : `https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=$search&format=json`

new updated working url : `https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=$search&origin=*&format=json`

**Comment by deakjahn** [comment]
Now that Flutter Web has gone mainstream, this seems to resurface again. So, let's put it straight, with the largest, boldest letters: **THIS IS NOT A FLUTTER ISSUE, there is no Flutter solution or workaround and never will be.**

If you use a web service, you have to abide by CORS rules. Check out the web service to see how they want you to do it. If it's your own server, set it up properly. **Flutter has nothing to do with it.** While you might be able to disable CORS as described above for yourself in **debug**, there's absolutely no way to do it in **release** for your users. Simply impossible and would be so dangerous no browser vendor would ever allow it.

**Comment by hansly1985** [comment]
To keep it simple, it's not Flutter issue.

You can setup a server and enable cors headers or write a **Chrome extension** that receive a **message** from your app, and get data from external api resource using **XMLHttpRequest**.

**Comment by nmtitov** [comment]
@jonahwilliams don't be stupid, it's a bug
