### ISSUE TITLE
Remove Xcode build settings from verbose logs if not building for iOS/macOS

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#46910]
Currently these just make it harder for ourselves and contributors from reading verbose logs

**Comment by jmagman** [comment]
I wonder what build setting it's looking for and why `-showBuildSettings` is being called at all in that case.

**Comment by jmagman** [comment]
`flutter run -d <android-emulator> -v`
```
XcodeProjectInterpreter.getBuildSettings (xcodeproj.dart:288)
IosProject.buildSettings (project.dart:435)
IosProject.isSwift (project.dart:426)
RunCommand.usageValues (run.dart:252)
<asynchronous gap>
FlutterCommand.verifyThenRunCommand (flutter_command.dart:620)
```

**Comment by jmagman** [comment]
So it's being called to populate `CustomDimensions.commandRunProjectHostLanguage`

**Comment by jmagman** [comment]
@blasten Ideally isSwift wouldn't be expensive, but even if it wasn't, do we want `CustomDimensions.commandRunProjectHostLanguage` to be populated with the iOS language if it's being run on a non-iOS device?

https://github.com/flutter/flutter/pull/33297

**Comment by jmagman** [comment]
> @blasten Ideally isSwift wouldn't be expensive, but even if it wasn't, do we want `CustomDimensions.commandRunProjectHostLanguage` to be populated with the iOS language if `flutter run` is on a non-iOS device?
> 
> #33297

Question for @xster, too re: analytics this is populating.

**Comment by xster** [comment]
Oh we should totally not be grabbing xcode build settings if we're not building for iOS. 

Also worth auditing if we're repeatedly getting the build settings in case we are building for iOS/mac too.

**Comment by jmagman** [comment]
> Also worth auditing if we're repeatedly getting the build settings in case we are building for iOS/mac too. We had some issues there before shipping 1.0 and manually cleaned up but I don't think we had a test to prevent wasteful calls.

It should just be called once, then cached.  But in this case, it didn't need to be called at all.
