### ISSUE TITLE
flutter assets doesnt work

### ISSUE THREAD

**Issue by fatih255** [flutter/flutter#46915]
pubspec.yaml 
flutter:
  uses-material-design: true
  assets:
     - assets/images/logo.png
     - assets/images/1.png
  #  - images/a_dot_burr.jpeg

main.dart

import 'package:flutter/material.dart';
import './UI/CustomInputField.dart';

void main(){
  runApp(MaterialApp(
    title: "Login App",
    home: HomeScreen(),
        ));
    }
    
    class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
      body: Container(
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.height,
        color:Colors.blue,
        child: Center(
          child: Container( 
            width: 400,
            height: 300,
           child: Column( 
             mainAxisAlignment: MainAxisAlignment.spaceEvenly,
             children: <Widget>[
              Material(
                elevation: 10.0,
                borderRadius: BorderRadius.all(Radius.circular(50.0)),
                child: Padding( 
                  padding: const EdgeInsets.all(8.0),
                   child:Image.asset("assets/images/1.png",width: 200, height: 200)), ),
              
CustomInputField(Icon(Icons.person,color: Colors.white),"Kullanıcı Adı"),
CustomInputField(Icon(Icons.lock,color: Colors.white),"Şifre"),
Container( 
  width: 150,
  child: RaisedButton(onPressed: (){},color:Colors.deepOrange,textColor: Colors.white,
  shape: RoundedRectangleBorder(borderRadius: BorderRadius.all(Radius.circular(10.0))),
  child: Text("Giriş",style: TextStyle( 
    fontSize: 20.0
   ),
  ),
  
 ))
             ],
            ),
            
      
          ),

        ),

      )
      
      );

}

**Comment by jonahwilliams** [comment]
It looks like you've mis-formatted the asset section:

```
assets:
- assets/images/logo.png
- assets/images/1.png
```

Should instead be:

```
assets:
  - assets/images/logo.png
  - assets/images/1.png
```

**Comment by pranjal-joshi** [comment]
I am also having a similar issue while loading image assets.

**My code**
```
Image.asset(
              "assets/images/bg.jpg",
              fit:  BoxFit.cover,
              height: MediaQuery.of(context).size.height * 0.4,
),
```

My yaml file is as below **(Also notice the warning given by VS Code!)**
![yaml](https://user-images.githubusercontent.com/6128978/71001153-ab8cbd00-2102-11ea-8e3a-50966099a7f0.png)

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
