### ISSUE TITLE
Flutter bots should (separately?) upload symbolicated versions of libskyshell.so

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4692]
If we had symbolicated versions of the engine binary stored in cloud storage we could easily write a command in `flutter` tool to symbolicate crash logs.  Even if we didn't expose that to users it would be useful for use in handling user crashes.

Example crash: https://github.com/flutter/flutter/issues/4611

**Comment by eseidelGoogle** [comment]
Attempt: https://codereview.chromium.org/1884703002 FYI @abarth @chinmaygarde

**Comment by eseidelGoogle** [comment]
Sorry, I mean https://codereview.chromium.org/2085133004

**Comment by chinmaygarde** [comment]
For iOS: Will generate DSYM files in the engine and upload them to the bucket.

**Comment by Hixie** [comment]
Normally I would mark this "no milestone necessary" since it's just about improving our world but this would be so useful to fixing crashers and crashers are so important that I'm going to put this in milestone 2.

**Comment by eseidelGoogle** [comment]
We actually already do this. :)  At least for Android, e.g. https://storage.googleapis.com/flutter_infra/flutter/9de4d1530b4d24fc219c0e38997e4bf5391f86e0/android-arm-release/symbols.zip

**Comment by eseidelGoogle** [comment]
Instructions on how to use them here:
https://github.com/flutter/engine/wiki/Symbolicating-production-crash-stacks

@yjbanov is currently working on improving (parts of) our crash reporting (not directly related to this), but eventually we will need to wire up these symbols in a nice way so that our customers can use them to understand the crash reports they get back from crashlytics, firebase crash reporting, etc.
