### ISSUE TITLE
After push a native viewController from flutter, is this possible display more content above native viewController with flutter again?

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#46920]
I have a native viewController which implement from a framework, I can't directly change it into flutter view.

So I think I can:

- Display the UI in native ViewController(a 3rd party native video player) from flutter main app.
- Then I need display some extra content(for example user avatar, some text message and so on) above(or in) native ViewController
- But I would prefer implement this extra content with flutter, if it's possible?

Is this good approach ? If not, then I think have to do the things bellow:

- Display the UI in native ViewController(a video player) from flutter main app.
- Then display some extra content with native code.

PS: why I can't change the native VideController into flutter ? it's because it integration with a native video player which integration cache logic and I can't change the source code in that.

**Comment by xster** [comment]
Seems like a candidate to use https://api.flutter.dev/flutter/widgets/UiKitView-class.html

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
