### ISSUE TITLE
When I use "flutter pub get",the build.gradle was rebuild

### ISSUE THREAD

**Issue by cn-Meepo** [flutter/flutter#46929]
I edit something in  build.gradle.but,When I use "flutter pub get", it was rebuild

**Comment by ghozay19** [comment]
if u edit something in build.gradle it will re-sync the gradle.

**Comment by iapicca** [comment]
Hi @cn-Meepo 
does @ghozay19 answer satisfy your question?
thank you

**Comment by cn-Meepo** [comment]
@ghozay19 Hi, I have edit something in build.grade and AndroidManifest.xml,but it was not re-sync the gradle.when i use flutter pub get,it will back default build.grade and default AndroidManifest.xml,the something i edit will be lost

**Comment by cn-Meepo** [comment]
@iapicca  It happened after updating androidx

**Comment by iapicca** [comment]
Hi @cn-Meepo 
could you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter clean`
`flutter pub cache repair`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by cn-Meepo** [comment]
Hi @iapicca 
this happened after updating my project to androidx,  when i edit something in .android file,example: edit minSdkVersion 16  to   minSdkVersion 21. then i use flutter pub get, the  minSdkVersion 21 back to  minSdkVersion 16.
I don't know it is a bug or it is normal.
flutter doctor -v

D:\code\flutter\scan>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.14393], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at D:\java\flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\java\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\java\android-sdk
    • Java binary at: C:\Users\meepo\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\meepo\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Users\meepo\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\193.5662.53
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7221

[√] Connected device (1 available)
    • MI 6 • bc840644 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by jonahwilliams** [comment]
Is this an app or a module project? In the later case the .android folder is ephemeral and is not meant to be modified

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
