### ISSUE TITLE
library source does not match the bytecode for class FlutterActivity

### ISSUE THREAD

**Issue by tongyangsheng** [flutter/flutter#46939]
when i check my FlutterActivity class in Android studio it show error like that,but i can still run my application, can i fix this promblem?thanks very much
![image](https://user-images.githubusercontent.com/32046282/70766845-1acc7f00-1d9a-11ea-9af5-5684927115dc.png)
![image](https://user-images.githubusercontent.com/32046282/70766857-2455e700-1d9a-11ea-917b-913f7433d94d.png)

**Comment by iapicca** [comment]
Hi @tongyangsheng 
it seems more a problem w/ android studio;
can you please provide your updated  `flutter doctor -v`?
Thank you

**Comment by tongyangsheng** [comment]
@iapicca Hi It's seems like everything is OK 
![image](https://user-images.githubusercontent.com/32046282/70875103-cde1e600-1fef-11ea-93af-9f888ab8fe71.png)

**Comment by xster** [comment]
I'm not sure if there are pre-configured source resolutions for the engine jars. 

/move flutter/flutter-intellij
