### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by lishuliang28** [flutter/flutter#46946]
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

The relevant error-causing widget was: 
  ClassicalHeaderWidget file:///C:/Users/Robust/AppData/Roaming/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.0.6/lib/src/header/header.dart:384:12
When the exception was thrown, this was the stack: 
#0      ClassicalHeaderWidgetState._refreshText (package:flutter_easyrefresh/src/header/header.dart:456:47)
#1      ClassicalHeaderWidgetState._showText (package:flutter_easyrefresh/src/header/header.dart:564:18)
#2      ClassicalHeaderWidgetState._buildContent (package:flutter_easyrefresh/src/header/header.dart:798:21)
#3      ClassicalHeaderWidgetState.build (package:flutter_easyrefresh/src/header/header.dart:734:33)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
type 'String' is not a subtype of type 'bool'
The relevant error-causing widget was: 
  ClassicalFooterWidget file:///C:/Users/Robust/AppData/Roaming/Pub/Cache/hosted/pub.flutter-io.cn/flutter_easyrefresh-2.0.6/lib/src/footer/footer.dart:321:12
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 5781): dispose

```
```

```
```

```
```

**Comment by iapicca** [comment]
Hi @lishuliang28 
```bash
════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
type 'String' is not a subtype of type 'bool'
```
the error might depend from the code<
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
