### ISSUE TITLE
New flutter broke google_sign_in

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4694]
Not sure if I should file this here, or in google_sign_in. No google_sign_in calls do anything, although no errors are displayed. This breakage occurred at some commit past c823acc345f97cd0baacd1bc970c43ced7b88066 .

It is broken at `Framework revision 0f2c3dc07f (59 minutes ago), engine revision 161496dff3`

Potentially of note: new mojo dependencies are used when I break
```
> mojo 0.4.25 (was 0.4.23)
> mojo_sdk 0.2.29 (was 0.2.27)
> mojo_services 0.4.32 (was 0.4.30)
```

**Comment by abarth** [comment]
I believe collin is working on a fix for this issue.

**Comment by abarth** [comment]
I think it's currently in this branch https://github.com/flutter/google_sign_in/tree/v2

**Comment by collinjackson** [comment]
assigning this to myself -- will try to get a new Google Sign-In release out ASAP. we're removing the mojo dependency so breakages of this kind won't happen in the future. thanks!

**Comment by collinjackson** [comment]
(This mojo change probably broke Firebase as well, but the codelab tells people to use the "codelab" branch so it's not going to codelab users until I finish porting that over and update the codelab branch.)

**Comment by collinjackson** [comment]
I regenerated the mojo files for now to get you going, tested locally in a simulator and it seems to work.

**Comment by drewwarren** [comment]
Great!

For some reason I had to change my pub git reference to get it to pull the
version.

I was using :
`git: git://github.com/flutter/google_sign_in.git`

to get it to pull the new code I changed it to:
```
git:
  url: git://github.com/flutter/google_sign_in.git
  ref: master
```

**Comment by collinjackson** [comment]
I think you'd need to run "pub upgrade" on the command line to get it to fetch the remote and see if the ref has changed. These seems like an issue that is likely to come up often since we are managing users' pub dependencies for them, but I'm not sure how to solve it. I'll file an issue anyway just to track it.

**Comment by collinjackson** [comment]
Apparently "flutter upgrade" is the way to get flutter to run pub upgrade for you. (See #3964.) So I guess this is working as intended, although I'll make sure to suggest that people run flutter upgrade when new versions come out.
