### ISSUE TITLE
QR generator in Flutter

### ISSUE THREAD

**Issue by Jayani12345** [flutter/flutter#46949]
Hi All,
Can I make a qr generator with multiple text fields attach to with it. 
For an Example :Name:,
                         Age,
                        Address:,
                         Email:,
as text fields user will input data then QR code will be generate according to user inputs.
please help with a code.

**Comment by stuartmorgan** [comment]
The issue tracker is for bugs in Flutter, or feature requests for the Flutter framework. For help building a feature or application, try one of the general discussion forums listed at flutter.dev/community.
