### ISSUE TITLE
Is Expandable notification supported in firebase messaging(notification) in flutter?

### ISSUE THREAD

**Issue by sharansingh00002** [flutter/flutter#46953]
If the text content is more than 1 or 2 lines it gets cropped out and the notification can not be expanded. It can be done easily in android but I don't know how to do it in flutter.
I've attatched a image about what i want.
![Screenshot 2019-12-13 at 12 26 00 PM](https://user-images.githubusercontent.com/40237701/70776700-d219c380-1da3-11ea-95d4-9e94112c60dd.png)

**Comment by edumolins** [comment]
Hi. You find and answer? 
I can't find anything about it is supported. Thanks
