### ISSUE TITLE
 Because myapp depends on image_picker >=0.6.2+3 which requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed.

### ISSUE THREAD

**Issue by chao9267** [flutter/flutter#46955]
The current Flutter SDK version is 1.9.1+hotfix.6.

Because myapp depends on image_picker >=0.6.2+3 which requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed.

pub get failed (1)

my  version :environment:   sdk: ">=2.1.0 <3.0.0"

**Comment by cedricgrothues** [comment]
Your version of Flutter is too old to support image_picker. Upgrade Flutter to the latest version (`v1.12.13+hotfix.5`) using `flutter upgrade`. The environment SDK has nothing to do with your Flutter version.

**Comment by darren-f5s** [comment]
OR (If you're supporting older devices), do not upgrade, and simply use the version of `image_picker` that doesn't rely on Flutter >10

**Comment by iapicca** [comment]
Hi @chao9267 
let me know if one of the proposed solutions works for you;
if you decide to upgrade please also run
`flutter clean`
`flutter pub cache repair`
just in case.
thank you

**Comment by chao9267** [comment]
because i use stable version ,so   i   changed the old version of image_picker ,thanks

**Comment by iapicca** [comment]
Hi @chao9267 
I'm glad that you fixed the problem, 
thank you for letting me know

please note that the current `stable` is `v1.12.13+hotfix.5`
`Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.19013.1122], locale en-US)`
