### ISSUE TITLE
Upgrade Flutter 1.12.13, How I use FlutterView in old project

### ISSUE THREAD

**Issue by venshine** [flutter/flutter#46958]
Old Code（use Flutter 1.9.1 stable channel）：
```
val flutterView = Flutter.createView(this, lifecycle, "main_page")
```
Now upgrade 1.12.13 master channel, I don't use io.flutter.facade.Flutter class, How can I replace this code?

**Comment by xster** [comment]
Does https://flutter.dev/go/android-project-migration help?

**Comment by venshine** [comment]
> Does https://flutter.dev/go/android-project-migration help?

Yeah, It's well for me.
