### ISSUE TITLE
Problem in shared_preferences 0.5.6

### ISSUE THREAD

**Issue by Arcturus5404** [flutter/flutter#46957]
The following went wrong in my CI tool:

> FAILURE: Build failed with an exception.

* What went wrong:

> Execution failed for task ':app:preReleaseBuild'.

> Android dependency 'androidx.core:core' has different version for the compile (1.0.0-rc01) and runtime (1.0.2) classpath. You should manually set the same version via DependencyResolution`

More specific:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+2/android/build.gradle' line: 22

```

Versions:

+ shared_preferences 0.5.6
+ shared_preferences_macos 0.0.1+2
+ shared_preferences_platform_interface 1.0.1

**Comment by Arcturus5404** [comment]
The previous build was successful with these versions:

+ shared_preferences 0.5.4+8 (0.5.6 available)
+ shared_preferences_platform_interface 1.0.1

**Comment by BaranMichal25** [comment]
Take a look at https://github.com/flutter/flutter/issues/46807

**Comment by Arcturus5404** [comment]
Thanks Baran.. seems that all suggested solutions did not work. I will contact the guys @ codemagic to see if they can clear caches on their mac minis

**Comment by Arcturus5404** [comment]
Downgrading to 0.5.4+8 works for codemagic, but I do get warnings for the camera plugin:

Android dependency 'androidx.lifecycle:lifecycle-runtime' has different version for the compile (2.0.0-rc01) and runtime (2.0.0) classpath. You should manually set the same version via DependencyResolution

Anyone an idea?

**Comment by iapicca** [comment]
Hi @Arcturus5404 
as @BaranMichal25 pointed out 
there's an issue open addressing this problem.

Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by Arcturus5404** [comment]
Hi @iapicca 

I will follow up on that issue 

Thanks
