### ISSUE TITLE
Error about  flutter engine compile on windows.

### ISSUE THREAD

**Issue by luori-mvp77** [flutter/flutter#46962]
Commands:
```bash
python .\flutter\tools\gn --unoptimized --runtime-mode=release --android
ninja -C .\out\android_release_unopt gen_snapshot
```

I want to compile flutter engine on windows10 env,but occurd exception below:
```bash
[911/911] LINK ./gen_snapshot.exe
FAILED: gen_snapshot.exe gen_snapshot.lib
E:/workspace/depot_tools/bootstrap-3_8_0_chromium_8_bin/python/bin/python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:./gen_snapshot.exe /PDB:./gen_snapshot.exe.pdb @./gen_snapshot.exe.rsp
libdart_vm_nosnapshot_with_precompiler.dart.obj : error LNK2019: 无法解析的外部符号 "public: static void __cdecl dart::Service::SetGetServiceAssetsCallback(struct _Dart_Handle * (__cdecl*)(void))" (?SetGetServiceAssetsCallback@Service@dart@@SAXP6APAU_Dart_Handle@@XZ@Z)，该符号在函数 "public: static char * __cdecl dart::Dart::Init(unsigned char const *,unsigned char const *,struct _Dart_Isolate * (__cdecl*)(char const *,char const *,char const *,char const *,struct Dart_IsolateFlags *,void *,char * *),bool (__cdecl*)(void * *,char * *),void (__cdecl*)(void *,void *),void (__cdecl*)(void *,void *),void (__cdecl*)(void *),void (__cdecl*)(void),void * (__cdecl*)(char const *,bool),void (__cdecl*)(unsigned char * *,int *,void *),void (__cdecl*)(void const *,int,void *),void (__cdecl*)(void *),bool (__cdecl*)(unsigned char *,int),struct _Dart_Handle * (__cdecl*)(void),bool,struct Dart_CodeObserver *)" (?Init@Dart@dart@@SAPADPBE0P6APAU_Dart_Isolate@@PBD111PAUDart_IsolateFlags@@PAXPAPAD@ZP6A_NPAPAX4@ZP6AX33@Z8P6AX3@ZP6AXXZP6APAX1_N@ZP6AXPAPAEPAH3@ZP6AXPBXH3@Z9P6A_NPAEH@ZP6APAU_Dart_Handle@@XZ_NPAUDart_CodeObserver@@@Z) 中被引用
libdart_vm_nosnapshot_with_precompiler.isolate.obj : error LNK2019: 无法解析的外部符号 "public: static class dart::RawError * __cdecl dart::Service::HandleIsolateMessage(class dart::Isolate *,class dart::Array const &)" (?HandleIsolateMessage@Service@dart@@SAPAVRawError@2@PAVIsolate@2@ABVArray@2@@Z)，该符号在函数 "public: virtual enum dart::MessageHandler::MessageStatus __thiscall dart::IsolateMessageHandler::HandleMessage(class std::unique_ptr<class dart::Message,struct std::default_delete<class dart::Message> >)" (?HandleMessage@IsolateMessageHandler@dart@@UAE?AW4MessageStatus@MessageHandler@2@V?$unique_ptr@VMessage@dart@@U?$default_delete@VMessage@dart@@@std@@@std@@@Z) 中 被引用
libdart_vm_nosnapshot_with_precompiler.os_thread.obj : error LNK2019: 无法解析的外部符号 "public: static void __cdecl dart::ThreadInterrupter::WakeUp(void)" (?WakeUp@ThreadInterrupter@dart@@SAXXZ)，该符号在函数 "public: void __thiscall dart::OSThread::EnableThreadInterrupts(void)" (?EnableThreadInterrupts@OSThread@dart@@QAEXXZ) 中被引用
libdart_vm_nosnapshot_with_precompiler.inliner.obj : error LNK2019: 无法解析的外部符号 "public: void __thiscall dart::FlowGraphPrinter::PrintBlocks(void)" (?PrintBlocks@FlowGraphPrinter@dart@@QAEXXZ)，该符号在函数 "public: int __thiscall dart::FlowGraphInliner::Inline(void)" (?Inline@FlowGraphInliner@dart@@QAEHXZ) 中被引用
libdart_vm_nosnapshot_with_precompiler.range_analysis.obj : error LNK2001: 无法解析的外部符号 "public: void __thiscall dart::FlowGraphPrinter::PrintBlocks(void)" (?PrintBlocks@FlowGraphPrinter@dart@@QAEXXZ)
libdart_vm_nosnapshot_with_precompiler.graph_intrinsifier.obj : error LNK2001: 无法解析的外部符号 "public: void __thiscall dart::FlowGraphPrinter::PrintBlocks(void)" (?PrintBlocks@FlowGraphPrinter@dart@@QAEXXZ)
./gen_snapshot.exe : fatal error LNK1120: 4 个无法解析的外部命令
ninja: build stopped: subcommand failed.
```

PS: I also refer to [32746](https://github.com/flutter/flutter/issues/32746), but i think that no the same issue, i also update engine version to v1.12.13 and check flutter/runtime/BUILD.gn confirm that add win_10 adaption, so i want know how to fix it, or actually current flutter/engine no support compile on Win10?

@stuartmorgan @shoryukenn

**Comment by stuartmorgan** [comment]
32746 is about building the engine *for* Windows. You're building for Android, so this is completely unrelated.

**Comment by luori-mvp77** [comment]
> 32746 is about building the engine _for_ Windows. You're building for Android, so this is completely unrelated.

I check what you said, but also got the same exception:
1. git checkout branch to v1.12.13-hotfixes
2.send command for building window like you said, but also got the c :
  python .\flutter\tools\gn --unoptimized --runtime-mode=release
  ninja -C .\out\host_release_unopt gen_snapshot
[exception]:
注意: 包含文件:     e:\engine\src\third_party\icu\source\common\unicode/uset.h
注意: 包含文件:  e:\engine\src\third_party\icu\source\common\util.h
[916/916] LINK ./gen_snapshot.exe
FAILED: gen_snapshot.exe gen_snapshot.lib
E:/workspace/depot_tools/bootstrap-3_8_0_chromium_8_bin/python/bin/python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /OUT:./gen_snapshot.exe /PDB:./gen_snapshot.exe.pdb @./gen_snapshot.exe.rsp
libdart_vm_nosnapshot_with_precompiler.dart.obj : error LNK2019: 无法解析的外部符号 "public: static void __cdecl dart::Service::SetGetServiceAssetsCallback(struct _Dart_Handle * (__cdecl*)(void))" (?SetGetServiceAssetsCallback@Service@dart@@SAXP6APEAU_Dart_Handle@@XZ@Z)，该符号在函数 "public: static char * __cdecl dart::Dart::Init(unsigned char const *,unsigned char const *,struct _Dart_Isolate * (__cdecl*)(char const *,char const *,char const *,char const *,struct Dart_IsolateFlags *,void *,char * *),bool (__cdecl*)(void * *,char * *),void (__cdecl*)(void *,void *),void (__cdecl*)(void *,void *),void (__cdecl*)(void *),void (__cdecl*)(void),void * (__cdecl*)(char const *,bool),void (__cdecl*)(unsigned char * *,__int64 *,void *),void (__cdecl*)(void const *,__int64,void *),void (__cdecl*)(void *),bool (__cdecl*)(unsigned char *,__int64),struct _Dart_Handle * (__cdecl*)(void),bool,struct Dart_CodeObserver *)" (?Init@Dart@dart@@SAPEADPEBE0P6APEAU_Dart_Isolate@@PEBD111PEAUDart_IsolateFlags@@PEAXPEAPEAD@ZP6A_NPEAPEAX4@ZP6AX33@Z8P6AX3@ZP6AXXZP6APEAX1_N@ZP6AXPEAPEAEPEA_J3@ZP6AXPEBX_J3@Z9P6A_NPEAE_J@ZP6APEAU_Dart_Handle@@XZ_NPEAUDart_CodeObserver@@@Z) 中被引用
libdart_vm_nosnapshot_with_precompiler.isolate.obj : error LNK2019: 无法解析的外部符号 "public: static class dart::RawError * __cdecl dart::Service::HandleIsolateMessage(class dart::Isolate *,class dart::Array const &)" (?HandleIsolateMessage@Service@dart@@SAPEAVRawError@2@PEAVIsolate@2@AEBVArray@2@@Z)，该符号在函数 "public: virtual enum dart::MessageHandler::MessageStatus __cdecl dart::IsolateMessageHandler::HandleMessage(class std::unique_ptr<class dart::Message,struct std::default_delete<class dart::Message> >)" (?HandleMessage@IsolateMessageHandler@dart@@UEAA?AW4MessageStatus@MessageHandler@2@V?$unique_ptr@VMessage@dart@@U?$default_delete@VMessage@dart@@@std@@@std@@@Z) 中被引用
libdart_vm_nosnapshot_with_precompiler.os_thread.obj : error LNK2019: 无法解析的外部符号 "public: static void __cdecl dart::ThreadInterrupter::WakeUp(void)" (?WakeUp@ThreadInterrupter@dart@@SAXXZ)，该符 号在函数 "public: void __cdecl dart::OSThread::EnableThreadInterrupts(void)" (?EnableThreadInterrupts@OSThread@dart@@QEAAXXZ) 中被引用
libdart_vm_nosnapshot_with_precompiler.inliner.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl dart::FlowGraphPrinter::PrintBlocks(void)" (?PrintBlocks@FlowGraphPrinter@dart@@QEAAXXZ)，该符号在函数 "public: int __cdecl dart::FlowGraphInliner::Inline(void)" (?Inline@FlowGraphInliner@dart@@QEAAHXZ) 中被引用
libdart_vm_nosnapshot_with_precompiler.range_analysis.obj : error LNK2001: 无法解析的外部符号 "public: void __cdecl dart::FlowGraphPrinter::PrintBlocks(void)" (?PrintBlocks@FlowGraphPrinter@dart@@QEAAXXZ)
libdart_vm_nosnapshot_with_precompiler.graph_intrinsifier.obj : error LNK2001: 无法解析的外部符号 "public: void __cdecl dart::FlowGraphPrinter::PrintBlocks(void)" (?PrintBlocks@FlowGraphPrinter@dart@@QEAAXXZ)
./gen_snapshot.exe : fatal error LNK1120: 4 个无法解析的外部命令
ninja: build stopped: subcommand failed.

3. If i modify model to debug, it's ok:
  python .\flutter\tools\gn --unoptimized --android
  ninja -C .\out\android_debug_unopt gen_snapshot

[success]:
注意: 包含文件:    e:\engine\src\third_party\icu\source\i18n\decContext.h
注意: 包含文件:     C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\signal.h
注意: 包含文件:  e:\engine\src\third_party\icu\source\i18n\number_utypes.h
注意: 包含文件:   e:\engine\src\third_party\icu\source\i18n\unicode/numberformatter.h
注意: 包含文件:   e:\engine\src\third_party\icu\source\i18n\number_types.h
注意: 包含文件:   e:\engine\src\third_party\icu\source\i18n\number_decimalquantity.h
注意: 包含文件:   e:\engine\src\third_party\icu\source\i18n\number_stringbuilder.h
注意: 包含文件:   e:\engine\src\third_party\icu\source\i18n\formattedval_impl.h
注意: 包含文件:    e:\engine\src\third_party\icu\source\common\capi_helper.h
注意: 包含文件:    e:\engine\src\third_party\icu\source\common\util.h
注意: 包含文件:    e:\engine\src\third_party\icu\source\common\uvectr32.h
注意: 包含文件:    e:\engine\src\third_party\icu\source\i18n\number_stringbuilder.h
[916/916] LINK ./gen_snapshot.exe

**Comment by luori-mvp77** [comment]
Please check again and let me know if i am wrong on some places. I also check the related .cc and .h files, i think definitions is ok. 
thanks.

**Comment by chinmaygarde** [comment]
Compiling the Flutter Engine on Windows is not a supported workflow as the engine can only be built on Mac and Linux. Developers on Windows can use prebuilt Android engines just fine though. Closing since this is unsupported and adding support for this is a larger effort than one we can realistically invest in ATM.

**Comment by deakjahn** [comment]
It might not be officially supported, still it works. I have two step-by-step procedures for both Windows directly and for Linux running in Windows Subsystem in Linux (just a creature comfort for those of us normally running on Windows) at https://github.com/flutter/flutter/issues/28720. I use both approaches actively, the first to compile my own engine so that I can use it on Windows for debug testing and the Linux one to send PRs to the engine itself. They both work and I hope they will keep working in the future, too. :-)

**Comment by Sunbreak** [comment]
> I use both approaches actively, the first to compile my own engine so that I can use it on Windows for debug testing and the Linux one to send PRs to the engine itself. They both work and I hope they will keep working in the future, too. :-)

#28720 is about build `Web` engine on Windows, while the OP is about build `Android` engine on Windows. Not quite the same
