### ISSUE TITLE
flutter run takes long to run

### ISSUE THREAD

**Issue by kutigbolahan** [flutter/flutter#46961]
i tried running a flutter app i cloned from Github but it tells me it takes unexpectedly long time and the app just crashes and send crash report to google.Crash report sent (report ID: f339b573f89aae57)

**Comment by iapicca** [comment]
Hi @kutigbolahan 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by kutigbolahan** [comment]
Thanks @iapicca  i solved the issue already

**Comment by iapicca** [comment]
Hi @kutigbolahan 
I'm glad that you fixed the problem, 
thank you for letting me know
