### ISSUE TITLE
A helper class to extract prominent colors from an image,Like Android Palette class .

### ISSUE THREAD

**Issue by liaobushi520** [flutter/flutter#46967]
In some situation ,we need  change widget color ,background color ,according to image primary color .

 
We need a  helper class to extract prominent colors from an image ,Like Android Palette class .

we need ,we need ,we need .

**Comment by goderbauer** [comment]
There is https://github.com/flutter/packages/tree/master/packages/palette_generator and https://pub.dev/packages/image that could probably be used for this. If not, this would be a good community supported package, I don't think we will support this natively in the framework.
