### ISSUE TITLE
Error: Getter not found: 'macOS'

### ISSUE THREAD

**Issue by rohanabraham** [flutter/flutter#46969]
Just installed flutter and trying to get flutter_gallery app to work

1. Download flutter_gallery from github
2. Go to /examples/flutter_gallery
3. Run >flutter pub get
4. Run >open -a Simulator
5. Run >flutter run

Running into this error.
![image](https://user-images.githubusercontent.com/4366633/70796998-72b7b580-1d9b-11ea-92f5-09373455326c.png)

Same error on MacOS & Windows.

**Comment by stuartmorgan** [comment]
`flutter_gallery` is part of the Flutter tree, and is only intended to work when run with the version of Flutter that it is checked out with; you shouldn't be downloading a separate copy.

Given the error, you are trying to run the latest master of the gallery using an older version of Flutter (presumably stable). You should instead run the copy that is in your Flutter tree.

**Comment by lzhuor** [comment]
Hi @rohanabraham, as @stuartmorgan  said, you should run the flutter version that is in your checked out `flutter` repo. 

The checked out code doesn't have a flutter SDK but you can trigger an auto download by running:
```
 git clone -b master https://github.com/flutter/flutter.git
 ./flutter/bin/flutter --version
``` 

Please see details here: https://flutter.dev/docs/development/tools/sdk/releases?tab=macos
