### ISSUE TITLE
Future-rolling bot

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4696]
We should have a bot that tries to rev all our dependencies (engine and framework) to the future, and then builds and runs the tests, and if they pass, it should automatically commit us to the future (and if it fails, that bot should go red).

**Comment by Hixie** [comment]
See also #6767.

**Comment by matanlurey** [comment]
We have needs for this on the Dart SDK + Angular + Pub-land. Would love to collaborate.

**Comment by dnfield** [comment]
I think the only part of this left to do is a bot to automatically run the update packages script.

**Comment by godofredoc** [comment]
Closing as completed. Please reopen if there is any remaining work.
