### ISSUE TITLE
Compilation error in example app of "flutter create --template=plugin": androidx.annotation.NonNull; can't be imported

### ISSUE THREAD

**Issue by arnaudelub** [flutter/flutter#46971]
If you do flutter create --template=plugin myplugin
and then try to run the example with flutter run, the compilation fails as import androidx.annotation.NonNull; can't be imported.

So i think that --androidx should be added by default with flutter create

**Comment by iapicca** [comment]
Hi @BadTasTe- 
can you please provide your `flutter doctor -v`?
Thank you

**Comment by BadTasTe-** [comment]
hi @iapicca,
thank you for the answer, here is my flutter doctor:
```terminal
`flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale ca-ES)
    • Flutter version 1.12.13+hotfix.5 at /Users/arnaud/dev/flutter
    • Framework revision 27321ebbad (5 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/arnaud/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/arnaud/Library/Android/sdk
    • Java binary at: /Users/arnaud/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/arnaud/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.`

**Comment by jmagman** [comment]
`androidx` is used by default as of 1.10.6 with https://github.com/flutter/flutter/pull/40925, and you're past that on v1.12.13+hotfix.5.
I just successfully `flutter create --template=plugin myplugin` and `flutter run` the example and didn't see the import issue.

Am I missing steps to reproduce?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
