### ISSUE TITLE
Flutter prints lots of errors during compilation after 1.12 upgrade

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#46985]
I don't know if this is related  to the `flutter` tool, or the `firebase_crashlytics` package, but after I upgraded to the latest version of Flutter:

>Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.476], locale pt-BR)

>[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[√] VS Code (version 1.40.0)
[√] Connected device (1 available)

>• No issues found!

And I click the Debug button to launch my app in and Android AVD I get hundreds of lines of errors in my console while the app is compiling, then later it installs just fine.

They look like old messages printed on the past days, exceptions I got while designing my UI, I uninstalled my app and reinstalled in the AVD but its the same, I also tried `flutter clean`.

These are the messages, they are huge, so I am just showing a printscreen:

![image](https://user-images.githubusercontent.com/8120472/70816674-c384d980-1dae-11ea-8bc9-0d211e57a093.png)

Take a look at the scroll handle so you can have an idea on all of the messages being printed just after I clicked the Debug button.

As you can see, they start once the compilation starts, and later when the APK is built they end, so they are being dumped during the compilation phase, as this can be shown here:

![image](https://user-images.githubusercontent.com/8120472/70817253-f4b1d980-1daf-11ea-97dc-523c29b3272d.png)

I don't know if this is related to #46898.

Using a separate device I don't get this messages.

**Comment by feinstein** [comment]
I don't that I can provide any code that will trigger this, as I don't know what's triggering this and my code is huge, and the only that made it appear was the upgrade itself.

Maybe in order to reproduce, try to downgrade Flutter to 1.9.7 again and call crashlytics `recordError` and then upgrade flutter and then run the same code and see if it's printed while the compiles.

**Comment by iapicca** [comment]
Hi @feinstein 
as you pointed, even though the issue seems related to a `flutterfire` plugin
it might caused by a broader problem with the current stable.

I'm leaving this open regarding the "flutter-side" part of the problem
you may want to consider opening an e issue in the [flutterfire's github]
(https://github.com/FirebaseExtended/flutterfire/issues) about the specific plugin.
thank you

**Comment by feinstein** [comment]
I will, thanks @iapicca

**Comment by feinstein** [comment]
done: https://github.com/FirebaseExtended/flutterfire/issues/1662
