### ISSUE TITLE
linux_chrome_dev_mode SecondStartupTime may have regressed.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#46981]
Looks like it occurs around https://github.com/flutter/flutter/pull/46913, although there's a clearer jump at https://github.com/flutter/flutter/pull/46801, which I don't believe.

**Comment by jonahwilliams** [comment]
From looking at all of the benchmarks run in that suite (searching for *chrome), the behavior seems bimodal, implying that it is probably much slower on one of the devicelab machines

**Comment by GaryQian** [comment]
Looks like the perf is back to old numbers after https://github.com/flutter/flutter/commit/6a5ef29a75c7fe8c2f8af393e7daed09a34c4027 or is this a symptom of the bimodal behavior you mentioned?

**Comment by GaryQian** [comment]
cc @digiter

**Comment by GaryQian** [comment]
I'm removing the TODAY tag, it looks like benches are back down to normal, although the bimodal spikes still seem to exist.

**Comment by kf6gpe** [comment]
Thanks, Gary!

Spikiness is probably OK --- we've got a few benchmarks like that. When
triaging for regressions, I generally take three or four persistent red
measurements before I start to file issues. Maybe we can close this?
Ray Rischpater, KF6GPE | kf6gpe.org | @kf6gpe
<http://www.twitter.com/kf6gpe>

**Comment by godofredoc** [comment]
I'd like to dig further into this problem. We can discard hardware differences as the root cause, all the machines have the same specs and the same type of phones.

I'll check from the running processes point of view to see if I can find something, temperature might be another problem the AC in the lab has been broken for a few days already.

**Comment by godofredoc** [comment]
We can add a postflight check for chrome processes just as we do for adb

**Comment by liyuqian** [comment]
I'm curious if there's any update. From the comments above, I can't clearly tell if this is a regression caused by a commit, or just a bimodal benchmark. If it's a regression, we can try a revert. If it's bimodal, maybe we can remove the "regression" label?

**Comment by kf6gpe** [comment]
What are next steps here? @godofredoc did we get a chance to add the post-flight check? Looking at the benchmark, it seems much smoother now. Shall we close this?

**Comment by kf6gpe** [comment]
Closing this as obsolete at this point; this benchmark has definitely settled.
