### ISSUE TITLE
exceptions from flutter dashboard

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#4698]
These are visible in the devtools console:

![screenshot from 2016-06-22 14 45 34](https://cloud.githubusercontent.com/assets/1269969/16284850/1a8ca7d6-3888-11e6-9d30-2d4ef9c2f6fc.png)

/cc @yjbanov

**Comment by yjbanov** [comment]
These are benign. We should probably reduce the severity to INFO.

**Comment by sethladd** [comment]
+1 for INFO

**Comment by yjbanov** [comment]
Currently the assumption is that every task has a corresponding card on the dashboard. That's not the case.

**Comment by yjbanov** [comment]
...anymore.
