### ISSUE TITLE
Don't hardcode out/* directories.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#46980]
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=42945.

**Comment by chinmaygarde** [comment]
Is there any guidance on how the engine can resolve these directories at runtime?

**Comment by kf6gpe** [comment]
cc @iskakaushik

**Comment by arbreng** [comment]
Closing out old obsolete issues

**Comment by miguelfrde** [comment]
Hey David, could you help me understand why this is obsolete?
Looking at the source code, the directories exposed under `out/` are still hardcoded: https://github.com/flutter/engine/blob/master/shell/platform/fuchsia/flutter/component.cc#L322

Please take a look at https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=42945 for a post mortem of an old issue that could have been prevented by not having these directories hardcoded.

**Comment by arbreng** [comment]
Ah, I was mass-triaging old issues and this one got swept up in the purge

Will re-open the fuchsia.dev bug and continue to track there (although the priority is low due to a loooot of other work to be done)
