### ISSUE TITLE
Could not find com.google.android:annotations:17.0

### ISSUE THREAD

**Issue by julianmarangoni** [flutter/flutter#46987]
Just updated android studios and flutter today, now every time I try to build, I get the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.google.android:annotations:17.0.
     Required by:
         project :app > io.grpc:grpc-core:1.21.0
```

Running a Clean Project in android studio gives a more descriptive error message:
```
Could not find com.google.android:annotations:17.0.
Searched in the following locations:
  - file:/C:/../../../sdk/extras/m2repository/com/google/android/annotations/17.0/annotations-17.0.pom
  - file:/C:/../../../sdk/extras/m2repository/com/google/android/annotations/17.0/annotations-17.0.jar
  - file:/C:/../../../sdk/extras/google/m2repository/com/google/android/annotations/17.0/annotations-17.0.pom
  - file:/C:/../../../sdk/extras/google/m2repository/com/google/android/annotations/17.0/annotations-17.0.jar
  - file:/C:/../../../sdk/extras/android/m2repository/com/google/android/annotations/17.0/annotations-17.0.pom
  - file:/C:/../../../sdk/extras/android/m2repository/com/google/android/annotations/17.0/annotations-17.0.jar
  - https://dl.google.com/dl/android/maven2/com/google/android/annotations/17.0/annotations-17.0.pom
  - https://dl.google.com/dl/android/maven2/com/google/android/annotations/17.0/annotations-17.0.jar
  - https://jcenter.bintray.com/com/google/android/annotations/17.0/annotations-17.0.pom
  - https://jcenter.bintray.com/com/google/android/annotations/17.0/annotations-17.0.jar
  - https://maven.fabric.io/public/com/google/android/annotations/17.0/annotations-17.0.pom
  - https://maven.fabric.io/public/com/google/android/annotations/17.0/annotations-17.0.jar
  - http://download.flutter.io/com/google/android/annotations/17.0/annotations-17.0.pom
  - http://download.flutter.io/com/google/android/annotations/17.0/annotations-17.0.jar
  - https://maven.google.com/com/google/android/annotations/17.0/annotations-17.0.pom
  - https://maven.google.com/com/google/android/annotations/17.0/annotations-17.0.jar
  - https://google.bintray.com/exoplayer/com/google/android/annotations/17.0/annotations-17.0.pom
  - https://google.bintray.com/exoplayer/com/google/android/annotations/17.0/annotations-17.0.jar
Required by:
    project :app > project :cloud_firestore > com.google.firebase:firebase-firestore:21.3.0 > io.grpc:grpc-android:1.21.0 > io.grpc:grpc-core:1.21.0
```

It looks like the cloud_firestore plugin is requesting com.google.android:annotations:17.0, but can't seem to find it. Currently have ^0.12.9+5 of cloud_firestore, tried updating it to ^0.13.0+1, same issue.

Not sure if I have the wrong dependencies set, here is my build.gradle:
```
buildscript {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath 'com.google.gms:google-services:4.3.2'  // Google Services plugin
        classpath 'io.fabric.tools:gradle:1.26.1'

    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->

            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "26.1.0"
            }

            if (details.requested.group == 'com.google.android'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "17.0"
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

Here is my flutter doctor:
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.16299.1182], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\..\..\..\flutter\flutter
    • Framework revision 27321ebbad (3 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\..\..\..\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\..\..\..\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[!] Android Studio (version 3.5)
    • Android Studio at C:\..\..\..\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\..\..\..\JetBrains\Toolbox\apps\IDEA-C\ch-0\192.7142.36
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6262.13

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\..\..\..\JetBrains\Toolbox\apps\IDEA-C\ch-0\193.5233.102
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
```

**Comment by iapicca** [comment]
Hi @julianmarangoni 
from your doctor seems like android studio couldn't locate flutter and dart plugins,
could you double check please?
thank you

**Comment by julianmarangoni** [comment]
Hi @iapicca ,
I am using IntelliJ IDEA Community Edition for flutter development.

When gradle runs, it indicates in the task background that its trying to download com.google.android:annotations:17, but can't find it.

Not sure if this is a cloud_firestore plugin issue or maybe my repositories are set wrong?

**Comment by iapicca** [comment]
Hi @julianmarangoni  
could you please run 
`flutter pub cache repair`
`cd <YOUR APP FOLDER>`
`flutter clean`
If the issue persist please provide `flutter run --verbose`
thank you

**Comment by julianmarangoni** [comment]
> Hi @julianmarangoni
> could you please run
> `flutter pub cache repair`
> `cd <YOUR APP FOLDER>`
> `flutter clean`
> If the issue persist please provide _flutter run --verbose_
> thank you

Hi @iapicca, thanks for getting back to me.

The issue still persists, I ran _flutter pub cache repair_. Android studio is still saying that the gradle project sync failed, and the error is showing: 

_ERROR: Failed to resolve: com.google.android:annotations:17.0
Affected Modules: app, cloud_firestore_

Here is the flutter run --verbose output:

[  +38 ms] executing: [C:\Users\PRIVATE_USER\Desktop\flutter\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +118 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 27321ebbad34b0a3fafe99fac037102196d655ff
[   +1 ms] executing: [C:\Users\PRIVATE_USER\Desktop\flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +165 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.5-0-g27321ebba
[ +178 ms] executing: [C:\Users\PRIVATE_USER\Desktop\flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +82 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\PRIVATE_USER\Desktop\flutter\flutter\] git ls-remote --get-url origin
[  +67 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +143 ms] executing: [C:\Users\PRIVATE_USER\Desktop\flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +67 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +130 ms] executing: C:\Users\PRIVATE_USER\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +34 ms] Exit code 0 from: C:\Users\PRIVATE_USER\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[  +17 ms] C:\Users\PRIVATE_USER\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +84 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +47 ms] Found plugin cloud_firestore at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.13.0+1\
[   +8 ms] Found plugin connectivity at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\connectivity-0.4.6+2\
[   +8 ms] Found plugin file_picker at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\file_picker-1.4.3+2\
[   +4 ms] Found plugin firebase_analytics at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-5.0.9\
[   +2 ms] Found plugin firebase_auth at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-0.14.0+9\
[   +3 ms] Found plugin firebase_core at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.3+2\
[   +4 ms] Found plugin firebase_core_web at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +4 ms] Found plugin firebase_crashlytics at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_crashlytics-0.1.2+4\
[   +3 ms] Found plugin firebase_storage at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_storage-3.1.1\
[   +9 ms] Found plugin flutter_full_pdf_viewer at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_full_pdf_viewer-1.0.6\
[  +15 ms] Found plugin flutter_mailer at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_mailer-0.4.2\
[   +3 ms] Found plugin flutter_plugin_android_lifecycle at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.4\
[  +18 ms] Found plugin flutter_webview_plugin at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.3.10+1\
[  +10 ms] Found plugin geocoder at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\geocoder-0.2.1\
[   +5 ms] Found plugin google_maps_flutter at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.21+15\
[  +11 ms] Found plugin image_picker at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\image_picker-0.6.3+1\
[   +3 ms] Found plugin in_app_purchase at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\in_app_purchase-0.2.2+6\
[   +7 ms] Found plugin location at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\location-2.3.5\
[  +11 ms] Found plugin path_provider at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\path_provider-1.5.1\
[   +5 ms] Found plugin permission_handler at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\permission_handler-3.3.0\
[  +10 ms] Found plugin printing at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\printing-2.1.9\
[   +4 ms] Found plugin shared_preferences at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-0.5.6\
[   +3 ms] Found plugin shared_preferences_macos at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+3\
[   +4 ms] Found plugin shared_preferences_web at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+2\
[   +5 ms] Found plugin sqflite at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\sqflite-1.2.0\
[  +12 ms] Found plugin url_launcher at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher-5.4.1\
[   +2 ms] Found plugin url_launcher_macos at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+2\
[   +3 ms] Found plugin url_launcher_web at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-0.1.0+2\
[ +504 ms] Found plugin cloud_firestore at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.13.0+1\
[   +4 ms] Found plugin connectivity at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\connectivity-0.4.6+2\
[   +4 ms] Found plugin file_picker at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\file_picker-1.4.3+2\
[   +2 ms] Found plugin firebase_analytics at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-5.0.9\
[   +1 ms] Found plugin firebase_auth at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-0.14.0+9\
[   +2 ms] Found plugin firebase_core at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.3+2\
[   +4 ms] Found plugin firebase_core_web at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +11 ms] Found plugin firebase_crashlytics at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_crashlytics-0.1.2+4\
[   +1 ms] Found plugin firebase_storage at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_storage-3.1.1\
[   +4 ms] Found plugin flutter_full_pdf_viewer at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_full_pdf_viewer-1.0.6\
[   +5 ms] Found plugin flutter_mailer at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_mailer-0.4.2\
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.4\
[  +10 ms] Found plugin flutter_webview_plugin at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.3.10+1\
[   +2 ms] Found plugin geocoder at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\geocoder-0.2.1\
[   +1 ms] Found plugin google_maps_flutter at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.21+15\
[   +4 ms] Found plugin image_picker at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\image_picker-0.6.3+1\
[   +3 ms] Found plugin in_app_purchase at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\in_app_purchase-0.2.2+6\
[  +18 ms] Found plugin location at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\location-2.3.5\
[   +9 ms] Found plugin path_provider at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\path_provider-1.5.1\
[   +5 ms] Found plugin permission_handler at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\permission_handler-3.3.0\
[   +4 ms] Found plugin printing at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\printing-2.1.9\
[   +4 ms] Found plugin shared_preferences at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-0.5.6\
[   +2 ms] Found plugin shared_preferences_macos at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+3\
[   +4 ms] Found plugin shared_preferences_web at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+2\
[   +4 ms] Found plugin sqflite at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\sqflite-1.2.0\
[   +7 ms] Found plugin url_launcher at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher-5.4.1\
[   +2 ms] Found plugin url_launcher_macos at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+2\
[   +2 ms] Found plugin url_launcher_web at C:\Users\PRIVATE_USER\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-0.1.0+2\
[  +94 ms] Generating C:\Users\PRIVATE_USER\Desktop\PRIVATE_PROJECT\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +48 ms] ro.hardware = ranchu
[  +54 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +27 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[  +19 ms] executing: C:\Users\PRIVATE_USER\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -s flutter
[  +13 ms] executing: C:\Users\PRIVATE_USER\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +86 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as C:\Users\PRIVATE_USER\AppData\Local\Android\sdk\platform-tools\adb.exe
[  +12 ms] executing: C:\Users\PRIVATE_USER\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +122 ms] Building APK
[  +35 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] gradle.properties already sets `android.enableR8`
[   +7 ms] Using gradle from C:\Users\PRIVATE_USER\Desktop\PRIVATE_PROJECT\android\gradlew.bat.
[  +16 ms] executing: C:\Users\PRIVATE_USER\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548\jre\bin\java -version
[ +163 ms] Exit code 0 from: C:\Users\PRIVATE_USER\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +7 ms] executing: [C:\Users\PRIVATE_USER\Desktop\PRIVATE_PROJECT\android\] C:\Users\PRIVATE_USER\Desktop\PRIVATE_PROJECT\android\gradlew.bat -Pverbose=true -Ptarget=C:\Users\PRIVATE_USER\Desktop\PRIVATE_PROJECT\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-x86 assembleDebug
[+1835 ms] > Configure project :app
[   +4 ms] WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
[   +1 ms] It will be removed at the end of 2019.
[        ] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[   +1 ms] To determine what is calling variant.getAssemble(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
[   +1 ms] WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
[   +1 ms] It will be removed at the end of 2019.
[   +2 ms] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[   +5 ms] To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
[   +1 ms] WARNING: API 'variantOutput.getProcessManifest()' is obsolete and has been replaced with 'variantOutput.getProcessManifestProvider()'.
[   +1 ms] It will be removed at the end of 2019.
[   +3 ms] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[  +12 ms] To determine what is calling variantOutput.getProcessManifest(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
[   +1 ms] WARNING: API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'.
[   +4 ms] It will be removed at the end of 2019.
[   +3 ms] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[   +1 ms] To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
[  +53 ms] WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
[   +1 ms] It will be removed at the end of 2019.
[        ] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[        ] To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
[   +1 ms] WARNING: API 'variant.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
[  +80 ms] It will be removed at the end of 2019.
[   +1 ms] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[        ] To determine what is calling variant.getPackageApplication(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
[   +8 ms] WARNING: API 'variant.getExternalNativeBuildTasks()' is obsolete and has been replaced with 'variant.getExternalNativeBuildProviders()'.
[   +2 ms] It will be removed at the end of 2019.
[   +1 ms] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[        ] To determine what is calling variant.getExternalNativeBuildTasks(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
[+31657 ms] FAILURE: Build failed with an exception.
[  +11 ms] * What went wrong:
[   +1 ms] Could not determine the dependencies of task ':app:preDebugBuild'.
[   +1 ms] > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
[   +1 ms]    > Could not find com.google.android:annotations:17.0.
[        ]      Searched in the following locations:
[        ]        - file:/C:/Users/PRIVATE_USER/AppData/Local/Android/sdk/extras/m2repository/com/google/android/annotations/17.0/annotations-17.0.pom
[   +1 ms]        - file:/C:/Users/PRIVATE_USER/AppData/Local/Android/sdk/extras/m2repository/com/google/android/annotations/17.0/annotations-17.0.jar
[   +3 ms]        - file:/C:/Users/PRIVATE_USER/AppData/Local/Android/sdk/extras/google/m2repository/com/google/android/annotations/17.0/annotations-17.0.pom
[        ]        - file:/C:/Users/PRIVATE_USER/AppData/Local/Android/sdk/extras/google/m2repository/com/google/android/annotations/17.0/annotations-17.0.jar
[        ]        - file:/C:/Users/PRIVATE_USER/AppData/Local/Android/sdk/extras/android/m2repository/com/google/android/annotations/17.0/annotations-17.0.pom
[        ]        - file:/C:/Users/PRIVATE_USER/AppData/Local/Android/sdk/extras/android/m2repository/com/google/android/annotations/17.0/annotations-17.0.jar
[        ]        - https://dl.google.com/dl/android/maven2/com/google/android/annotations/17.0/annotations-17.0.pom
[        ]        - https://dl.google.com/dl/android/maven2/com/google/android/annotations/17.0/annotations-17.0.jar
[        ]        - https://jcenter.bintray.com/com/google/android/annotations/17.0/annotations-17.0.pom
[        ]        - https://jcenter.bintray.com/com/google/android/annotations/17.0/annotations-17.0.jar
[        ]        - https://maven.fabric.io/public/com/google/android/annotations/17.0/annotations-17.0.pom
[        ]        - https://maven.fabric.io/public/com/google/android/annotations/17.0/annotations-17.0.jar
[   +2 ms]        - http://download.flutter.io/com/google/android/annotations/17.0/annotations-17.0.pom
[   +1 ms]        - http://download.flutter.io/com/google/android/annotations/17.0/annotations-17.0.jar
[        ]        - https://maven.google.com/com/google/android/annotations/17.0/annotations-17.0.pom
[   +5 ms]        - https://maven.google.com/com/google/android/annotations/17.0/annotations-17.0.jar
[   +3 ms]        - https://google.bintray.com/exoplayer/com/google/android/annotations/17.0/annotations-17.0.pom
[   +1 ms]        - https://google.bintray.com/exoplayer/com/google/android/annotations/17.0/annotations-17.0.jar
[        ]      Required by:
[        ]          project :app > project :cloud_firestore > com.google.firebase:firebase-firestore:21.3.0 > io.grpc:grpc-android:1.21.0 > io.grpc:grpc-core:1.21.0
[   +5 ms] * Try:
[  +11 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 33s
[   +5 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
[   +1 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[   +1 ms] See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings
[ +396 ms] Running Gradle task 'assembleDebug'... (completed in 34.4s)
[   +7 ms] "flutter run" took 36,124ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by darshankawar** [comment]
Hi @julianmarangoni,
Is this still an issue ?
If so, can you create a new Flutter project and build to see if you get the same error ?
If your app uses Firebase, there have been latest updates to their plugin which you will need to upgrade to (`firebase_core`, `cloud_firestore`) and then try to run and see if it works.
Also, if the error is causing due to firebase plugins, there's a separate repo for tracking bugs and you may want to open the issue here : https://github.com/FirebaseExtended/flutterfire/issues
Thanks.

**Comment by julianmarangoni** [comment]
Hi @darshankawar,

I managed to fix it by creating a new project and moving my files over. I suspect the issue was something to do with one of the build scripts.
