### ISSUE TITLE
Add support for dumping the layer tree from flutter_driver

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#46992]
Right now we have an API to get a string representation of the render tree programmatically (https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/getRenderTree.html). For debugging it'd be nice to have a sister API that gets the layer tree as well.

**Comment by gw280** [comment]
This was landed in #47014

**Comment by ajschwieterman** [comment]
When getting the render tree with a profile build of a Flutter app, the FlutterDriver returns an empty string, but a debug build returns the render tree.  Is this expected/intended?

**Comment by ajschwieterman** [comment]
The same holds true for `getRenderObjectDiagnostics`
