### ISSUE TITLE
Problem With Flutter Webview

### ISSUE THREAD

**Issue by yaseen-abugamess** [flutter/flutter#46996]
when i upgrade to v1.12 the webview dose't work and give this error
Initializing hot reload...
Syncing files to device iPhone 11 Pro Max...
Reloaded 0 of 483 libraries in 152ms.
[VERBOSE-2:platform_view_layer.cc(22)] Trying to embed a platform view but the PrerollContext does not support embedding
[VERBOSE-2:platform_view_layer.cc(39)] Trying to embed a platform view but the PaintContext does not support embedding

**Comment by amirh** [comment]
Do you have the `io.flutter.embedded_views_preview` set in your Info.plist?
Can you try running the webview example app and see if it works?

**Comment by yaseen-abugamess** [comment]
Hi Amir Thank you for replying , I think there is an update in
packages ecosystem and today is working fine.
but i wanna ask you about apple pay integration and payment company dose't
have payment SDK for flutter can I use SDK like in_app_payment ,so this
plugin for specific payment company? or common?
lastly I wanna thank you again

‫في السبت، 14 ديسمبر 2019 في 1:17 ص تمت كتابة ما يلي بواسطة ‪Amir Hardon‬‏
<‪notifications@github.com‬‏>:‬

**Comment by amirh** [comment]
Thanks @yaseen-abugamess , I'd suggest asking support questions on StackOverflow where more people will benefit from the question and the answers.
