### ISSUE TITLE
Attempting `flutter build ios-framework`, getting "Directory listing failed" error in log

### ISSUE THREAD

**Issue by gogisha** [flutter/flutter#46993]
I wasn't quite sure which topic to choose for this question, so I'm hoping "I have a problem with my Flutter application." is the correct one.

I'm trying to integrate a Flutter app within an existing iOS application and working off of [the following](https://flutter.dev/docs/development/add-to-app/ios/project-setup) documentation.

Unfortunately I cannot use the CocoaPods method as my team uses buddybuild for our CI and it seems to not be able to get at the Flutter project, even if I place it wholly within our existing iOS app's repo folder.

Thus I'm trying the second option "Option B - Embed frameworks in Xcode".

However, when I try to invoke the following command (I know the path is just a placeholder but it didn't seem to matter which one I chose):

`flutter build ios-framework --output=some/path/MyApp/Flutter/`

I get the following error:

```
Building framework for com.nytimes.games.expansion in debug mode...
 ├─Populating Flutter.framework...                               1,115ms
 ├─Add placeholder App.framework for debug...                    1,188ms
 ├─Assembling Flutter resources for App.framework...                7.5s
 
 ├─Building plugins...                                                 ⣷
Sending crash report to Google.                                 
Crash report sent (report ID: 0265d06642fcdce0)                         
 ├─Building plugins...                                                 ⣻Oops; flutter has exited unexpectedly.
       Crash report written to [MY LOCAL PATH]/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
       ⣾%                                                                                                                                                   
```

And when I look at that file I see the following error about the directory not existing, which I found weird as I think the Flutter command I invoked is supposed to create said directory:

```
FileSystemException: FileSystemException: Directory listing failed, path = 'some/path/MyApp/Flutter/Debug/iphoneos/Debug-iphoneos/' (OS Error: No such file or directory, errno = 2)

#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:39:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:251:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:45:12)
#3      BuildIOSFrameworkCommand._producePlugins (package:flutter_tools/src/commands/build_ios_framework.dart:390:61)
<asynchronous suspension>
#4      BuildIOSFrameworkCommand.runCommand (package:flutter_tools/src/commands/build_ios_framework.dart:175:15)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

Any help would be appreciated, thanks!

**Comment by xster** [comment]
cc @jmagman

**Comment by jmagman** [comment]
`some/path/MyApp/Flutter/` is a placeholder.  You need to replace it with absolute path to the directory where you want to output the frameworks.

The tool shouldn't crash here, though, it should give a better error message.

**Comment by jmagman** [comment]
Also, the status indicator is malformed.

**Comment by gogisha** [comment]
Yup yup, figured it was just a placeholder, but since it seemed like it would generate the folders for the path provided in case they weren't there I figured while testing it couldn't hurt to keep them as placeholder values.

**Comment by jmagman** [comment]
It does create the directories, but unfortunately output is expecting an absolute path.  Can you try with an absolute path that doesn't exist, @gogisha?
Working on a pull request to handle relative paths.

**Comment by gogisha** [comment]
Gotcha gotcha, just tried that and it seems to have worked! One follow up though, if I wanted my import to vary based on build configuration a la the tip at the end of this page: https://flutter.dev/docs/development/add-to-app/ios/project-setup , is the proposal that I edit the "path" in the actual XML of the project itself (ie. manually changing the text instead of checking a box somewhere in the IDE)? Thanks so much for all the help!

**Comment by jmagman** [comment]
> is the proposal that I edit the "path" in the actual XML of the project itself (ie. manually changing the text instead of checking a box somewhere in the IDE)?

Sadly, yes.  There's no way AFAIK to add a build configuration variable in a path through the UI.  Products > Location > only provides a file picker, not a free-form text box.
Don't corrupt your project file, use source control, stay safe out there.

**Comment by gogisha** [comment]
Gotcha, well will try that for now. Thanks for all the help!

**Comment by Quanhua-Guan** [comment]
flutter 1.12.13-hotfix5
SOLUTION:
use absolute path, like follow: 
flutter build ios-framework --debug --output=/Users/yuyuan/Desktop/MeiyaTime/Gaoding-iOS/modules/GaodingFlutter/fc_flutter/frameworks

Flutter版本: flutter 1.12.13-hotfix5
解决方法: --output的参数必须要使用全路径, 否则会失败.

**Comment by xster** [comment]
@Quanhua-Guan that's specifically the fix @jmagman made in https://github.com/flutter/flutter/pull/47369. 

Absolute paths should be no longer necessary if you're on v1.13.3+
