### ISSUE TITLE
don't back to upper line in text field

### ISSUE THREAD

**Issue by mohamadalipour** [flutter/flutter#47001]
i'm using Samsung default keyboard ,
when I'm  using text field or text form field and set keyboard type in multiline and write in  Arabic characters then press new line(enter) button in keyboard after that if i want to press back space button  to back previous line in don't work  and hangs in current line
when I use gboard instead of Samsung default keyboard it will works correctly
Flutter version 1.9.1+hotfix.4 
Dart version 2.5.0

**Comment by iapicca** [comment]
Hi @mohamadalipour 
can you please provide your `flutter doctor -v`
and your `flutter run --verbose` relative to the "hanging" event?
Thank you

**Comment by mohamadalipour** [comment]
• Flutter version 1.12.13+hotfix.5 at C:\Users\m.alipour\Desktop\android-sdk-windows\flutter
    • Framework revision 27321ebbad (6 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

![WhatsAppVideo2019-12-13at105713P](https://user-images.githubusercontent.com/32418402/70994719-0f53bd80-20e4-11ea-9dbc-d625e6641b8b.gif)


this is my exact problem

**Comment by iapicca** [comment]
Hi @mohamadalipour 
thank you for your `flutter doctor -v`
can you please provide also  your `flutter run --verbose`?
Thank you

**Comment by mohamadalipour** [comment]
[   +5 ms] <- compile package:test/main.dart
[  +41 ms] Result: {type: Isolate, id: isolates/2932188082996647, name: main, number: 2932188082996647, _originNumber: 2932188082996647, startTime: 1576927848689, _heaps: {new: {type:
HeapSpace, name: new, vmName: Scavenger, collections: 1, avgCollectionPeriodMillis...
[+9013 ms] Updating files
[+1523 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device SM A320F... (completed in 10,612ms, longer than expected)
[        ] Synced 5.9MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +7 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0xe1921290, isolate: {type: @Isolate, fixedId: true, id: isolates/2932188082996647, name:
main.dart$main-2932188082996647, number: 2932188082996647}}]}
[   +1 ms] <- accept
[        ] Connected to _flutterView/0xe1921290.
[   +2 ms] �  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on SM A320F is available at: http://127.0.0.1:62481/JjUSyE8AduY=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+40180 ms] �  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +2 ms] An Observatory debugger and profiler on SM A320F is available at: http://127.0.0.1:62481/JjUSyE8AduY=/
[   +1 ms] You can dump the widget hierarchy of the app (debugDumpApp) by pressing "w".
[        ] To dump the rendering tree of the app (debugDumpRenderTree), press "t".
[   +1 ms] For layers (debugDumpLayerTree), use "L"; for accessibility (debugDumpSemantics), use "S" (for traversal order) or "U" (for inverse hit test order).
[   +1 ms] To toggle the widget inspector (WidgetsApp.showWidgetInspectorOverride), press "i".
[        ] To toggle the display of construction lines (debugPaintSizeEnabled), press "p".
[        ] To simulate different operating systems, (defaultTargetPlatform), press "o".
[        ] To toggle the elevation checker, press "z".
[        ] To display the performance overlay (WidgetsApp.showPerformanceOverlay), press "P".
[        ] To enable timeline events for all widget build methods, (debugProfileWidgetBuilds), press "a"
[   +1 ms] To save a screenshot to flutter.png, press "s".
[        ] To repeat this help message, press "h". To detach, press "d"; to quit, press "q".

**Comment by mohamadalipour** [comment]
@iapicca 
I'm waiting for your response that when would to fix this issue

**Comment by GaryQian** [comment]
@mohamadalipour We have recently made changes that greatly improve Samsung keyboard behavior (https://github.com/flutter/engine/pull/17426) can you please verify whether or not you are still seeing this?

**Comment by mohamadalipour** [comment]
thank you so much for your follow up
but i still have this bug in my flutter app
my flutter version is  1.17.0 on channel stable and dart is 2.8.1

**Comment by mohamadalipour** [comment]
@iapicca 
@GaryQian 
I'm waiting for your response that when would to fix this issue

**Comment by GaryQian** [comment]
Have you tried on the latest master channel? We have recently landed some changes to rtl handling and backspace, so there is a chance this is fixed. Please let me know if you still see it!

**Comment by mohamadalipour** [comment]
@GaryQian 
thank you it was fixed on master channel after almost 1 year
I'm waiting for this bug fix on stable channel
