### ISSUE TITLE
Handling DateTime, Currency and Numbers in gen_l10n tool

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#47008]
It would be great to provide some support/convenience for handling DateTime, numbers and currencies in the gen_l10n tool. I've been working with @HansMuller on some of ideas:

### Pull requests:
Simple, non-plural messages - https://github.com/flutter/flutter/pull/47006 
Plural messages - https://github.com/flutter/flutter/pull/47483

### Description
Essentially handles DateTime through reading the "type" and "format" resource attributes for each placeholder. By defining the "type" as "DateTime" and providing a "format" string that corresponds to an existing DateFormat constructor, the tool will automatically generate code that formats the date or time for the developer.

It generates the following result:
**Message in .arb file:** 
```
{
  "springBegins": "Spring begins on {springStartDate}",
  "@springBegins": {
    "description": "The first day of spring",
    "placeholders": {
      "springStartDate": {
        "type": "DateTime",
        "format": "yMMMMEEEEd"
      }
    }
  }
}
```

**Resulting method:**
```
  String springBegins(Object springStartDate) {
    final DateFormat springStartDateDateFormat = DateFormat.yMMMMEEEEd(_localeName);
    final String springStartDateString = springStartDateDateFormat.format(springStartDate);
    return Intl.message(
      r'Spring begins on \$springStartDateString',
      locale: _localeName,
      name: 'springBegins',
      desc: r'The first day of spring',
      args: <Object>[springStartDateString]
    );
  }
```

This takes away complexity from the app developer from having to format dates for each locale themselves. 

### Pull requests
Fix positional vs named params, introduce Currency formatting - https://github.com/flutter/flutter/pull/48445

### Description
Essentially handles currencies through intl.NumberFormat through reading the "type, "format", and optional attributes such as "decimalDigits" for resource attributes for each placeholder. The tool will automatically generate code that formats the date or time for the developer.

**Message in .arb file:** 
```
{
  "itemCostMessage": "Your item is {cost} dollars.",
  "@itemCostMessage": {
    "description": "The monetary cost of a single item.",
    "placeholders": {
      "cost": {
        "type": "Number",
        "format": "simpleCurrency",
        "decimalDigits": 2
      }
    }
  }
}
```

**Resulting method:**
```
  String itemCostMessage(Object cost) {
    final NumberFormat costNumberFormat = NumberFormat.simpleCurrency({
      locale: _locale,
      decimalDigits: 2,
    });
    final String costString = costNumberFormat.format(cost);

    return Intl.message(
      r'Your item is \$costString dollars.',
      locale: _localeName,
      name: 'itemCostMessage',
      desc: r'The monetary cost of a single item.',
      args: <Object>[cost]
    );
  }
```

### Pull requests
Handles number formats for simple and plural messages - https://github.com/flutter/flutter/pull/47706

### Description
Essentially handles numbers through intl.NumberFormat through reading the "type, "format", and optional attributes such as "decimalDigits" for resource attributes for each placeholder. The tool will automatically generate code that formats the date or time for the developer.

**Message in .arb file:** 
```
{
  "courseCompletion": "You have completed {progress} of the course.",
  "@courseCompletion": {
    "description": "The amount of progress the student has made in their class.",
    "placeholders": {
      "progress": {
        "type": "Number",
        "format": "percentPattern",
      }
    }
  }
}
```

**Resulting method:**
```
  String courseCompletion(Object progress) {
    final NumberFormat progressNumberFormat = NumberFormat.percentPattern({
      locale: _locale,
    });
    final String progressString = progressNumberFormat.format(progress);

    return Intl.message(
      r'You have completed \$progress of the course.',
      locale: _localeName,
      name: 'courseCompletion',
      desc: r'The amount of progress the student has made in their class.',
      args: <Object>[progress]
    );
  }
```

**Comment by shihaohong** [comment]
I updated the original proposal to have currencies be specified with the type "Number", since currencies are also formatted using the `NumberFormat` class. I don't see a benefit of separating "Number" and "Currency" types, but if there are any objections, please comment on the thread!

**Comment by shihaohong** [comment]
I believe that this issue can be closed, since all functionality in this proposal has been merged.

**Comment by garry-jeromson** [comment]
Sanity check: is this most excellent functionality ready for use? With the current version of master, the mapping functions (`m1`, `m2`, etc.) present in the generated `messages_xx.dart` files are those for placeholders with type `string` - for `DateTime` types, there are no mapping functions, which means the fallback message (see #48822) is always shown.

**Comment by HansMuller** [comment]
@garry-jeromson - could you open a new issue and include a test case that demonstrates how the generated localizations class fails?

**Comment by garry-jeromson** [comment]
@HansMuller Will do. :-)
