### ISSUE TITLE
all files contains my dart code in android studio change to this code if i leave the project for some days

### ISSUE THREAD

**Issue by MahmoudElbokl** [flutter/flutter#47009]
**<?xml version="1.0" encoding="utf-8"?>

<selector xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:app="http://schemas.android.com/apk/res-auto">
    <item android:state_enabled="false"
          app:alpha="?android:attr/disabledAlpha"
          android:color="?android:attr/textColorPrimary" />
    <item android:color="?android:attr/textColorPrimaryInverse" />
</selector>**

**Comment by MahmoudElbokl** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/55541781/70835832-01155100-1e07-11ea-8aba-9c64b55d08a2.png)

**Comment by iapicca** [comment]
Hi @MahmoudElbokl 
I'm not sure how this issue is related to flutter;
can you please provide your `flutter doctor -v`
and describe the issue in details?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by MahmoudElbokl** [comment]
Flutter Doctor 
C:\src\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\M\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\M\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by MahmoudElbokl** [comment]
the issue is the project when i use it work with me no problems in it when i stop and return to it after some days i found it the code change to this code like the picture and i found some files code change like this 

/// Builds indication marks for PageView from any Widget and/or Animation.
library page_view_indicator;

import 'dart:math';

import 'package:flutter/material.dart';
import 'package:page_view_indicator/src/indicator.dart';

export 'src/circle.dart';

typedef Widget IndicatorBuilder(AnimationController controller, int index);

/// The Indicator Widget, you would likely put it next to your PageView.
class PageViewIndicator extends StatefulWidget {
  /// [pageIndexNotifier] is how we can properly handle page changes.
  /// [length] is how much pages there is in the [PageView].
  /// [normalBuilder] is how we should build the Indicator at its normal state.
  /// [highlightedBuilder] is how we should build the Indicator at its highlighted state.
  /// [currentPage] gives you the ability to star the Indicator at a given index.
  /// [indicatorPadding] space around each Indicator.
  PageViewIndicator

  (

  {

  Key

  key

  ,

  @required

  this

      .

  pageIndexNotifier

  ,

  @required

  this

      .

  length

  ,

  @required

  this

      .

  normalBuilder

  ,

  @required

  this

      .

  highlightedBuilder

  ,

  this

      .

  currentPage

  =

  0

  ,

**Comment by iapicca** [comment]
Hi @MahmoudElbokl 
could it be that you updated flutter in the meantime?

Could you please run
`flutter clean`
`flutter pub cache repair`
let me know if the issue persists
thank you

**Comment by MahmoudElbokl** [comment]
thank you for your answer
