### ISSUE TITLE
Error: The getter 'fullObstruction' isn't defined for the class 'ObstructingPreferredSizeWidget'.

### ISSUE THREAD

**Issue by cheekuji** [flutter/flutter#47012]
Upgraded to latest flutter and now have this issue:Compiler message:                                                       
../../Devlopment/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-0.20.2/lib/src/platform_scaffold.dart:229:38: Error: The getter 'fullObstruction' isn't defined for the class 'ObstructingPreferredSizeWidget'.
 - 'ObstructingPreferredSizeWidget' is from 'package:flutter/src/cupertino/page_scaffold.dart' ('../../Devlopment/flutter/packages/flutter/lib/src/cupertino/page_scaffold.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'fullObstruction'.
      final obstruct = navigationBar.fullObstruction == null ||         
                                     ^^^^^^^^^^^^^^^                    
../../Devlopment/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-0.20.2/lib/src/platform_scaffold.dart:230:25: Error: The getter 'fullObstruction' isn't defined for the class 'ObstructingPreferredSizeWidget'.
 - 'ObstructingPreferredSizeWidget' is from 'package:flutter/src/cupertino/page_scaffold.dart' ('../../Devlopment/flutter/packages/flutter/lib/src/cupertino/page_scaffold.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'fullObstruction'.
          navigationBar.fullObstruction;                                
                        ^^^^^^^^^^^^^^^                                 
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.                                                           
                                                                        
FAILURE: Build failed with an exception.

**Comment by LongCatIsLooong** [comment]
See the [changelog](https://github.com/flutter/flutter/wiki/Changelog):

> #40690 ObstructingPreferredSizeWidget.fullObstruction is replaced by ObstructingPreferredSizeWidget.shouldFullyObstruct(BuildContext context).

You might want to upgrade the `flutter_platform_widgets` plugin to a new version.

**Comment by cheekuji** [comment]
I did the upgrade and now got this error: 

FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:preDebugBuild'.                         
> Android dependency 'com.google.firebase:firebase-measurement-connector' has different version for the compile (17.0.1) and runtime (18.0.0) classpath. You should manually set the same version via DependencyResolution
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org

**Comment by LongCatIsLooong** [comment]
@cheekuji does https://github.com/flutter/flutter/issues/27254 help? If not, could you please file a new issue?
