### ISSUE TITLE
[cocoon] Update Task entity to store information for individual attempts

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#47018]
Extension to https://github.com/flutter/flutter/issues/43104

It would be nice in the Build Dashboard summary for tasks to give more information on each individual run. Right now we throw away information from previous attempts.

Such as individual statuses, individual start and end timestamps, etc.

**Comment by csells** [comment]
@CaseyHillers what use cases would having this add'l data enable?

**Comment by CaseyHillers** [comment]
This is to enable the infra team to have better overall task metrics and help better identify flakiness.

An example use case is that a task is rerun because of an infra issue. The first attempt of the task is run on Agent A and fails. The second attempt is on Agent B and succeeds. This is a strong signal that there is either flakiness in the task or the agent, and should be investigated. If it's consistent that its just Agent A that is unable to run tasks successfully, we can better quarantine it so tasks are not assigned for it until we can fix it.

Storing the other metrics for each run will also help the infra team have a better view of queue and run times for tasks as we only know about the latest attempt on a task.

**Comment by Hixie** [comment]
We've lived without this for a while and I'm not sure having this on file is helping us much (we haven't even triaged this in several years), so I'm going to close it. If we ever want to do this, we should just do it.
