### ISSUE TITLE
WidgetsApp should track what the current route name is and tell observatory

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4701]
Navigator should expose a callback which it invokes whenever the current route name changes.

WidgetsApp should hook into this and keep the debugger/IDE up to date about what the current route name is.

cc @devoncarew, @eseidel

**Comment by Hixie** [comment]
cc @jacob314 Is this something you would want to expose in your inspector?

**Comment by jacob314** [comment]
Could be handy although I need to know when anything at all changes in the widget tree so getting updates at the granularity of the route changes probably isn't that useful on its own.

**Comment by Hixie** [comment]
Ok. In that case I will close this for now and we can reconsider when we have some more immediate need.
