### ISSUE TITLE
compilesdk least 28 in androidx

### ISSUE THREAD

**Issue by androiddaniel** [flutter/flutter#47016]
I had a difficulty when i try to migrate my flutter project to AndroidX. It gives me the error
you need to have compileSdk set to at least 28 in your module build.grandle to migrate to Androidx

I tried by changing the compilesdk 28 but it not work.

please help me

**Comment by androiddaniel** [comment]
flutter terminal in while run: 

Launching lib\main.dart on Android SDK built for x86 in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Running Gradle task 'assembleDebug'...

Compiler message:
/C:/src/flutter/packages/flutter/lib/foundation.dart:12:1: Error: Error when reading '/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/meta-1.1.7/lib/meta.dart': The system cannot find the path specified.

**Comment by zaralockheart** [comment]
@androiddaniel did you tried to follow the step using android studio?

**Comment by cedricgrothues** [comment]
Did you try to migrate using AndroidStudio?

**Comment by iapicca** [comment]
Hi @androiddaniel 
did you follow the [link](https://goo.gl/CP92wY) provided in the logs?
Please note that from the latest stable version of flutter 
the generated apps are `androidx` by default.
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by adilwahla** [comment]
Launching lib\main.dart on CPH1809 in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
C:\Users\adil rehman\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0.aar\22c4dc47832d27a81011f405acb1cbf6\res\values\values.xml:133:5-70: AAPT: error: resource android:attr/fontVariationSettings not found.

C:\Users\adil rehman\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0.aar\22c4dc47832d27a81011f405acb1cbf6\res\values\values.xml:133:5-70: AAPT: error: resource android:attr/ttcIndex not found.

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
BUILD FAILED in 52s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
