### ISSUE TITLE
Flutter + CanvasKit crashes when loading webp images

### ISSUE THREAD

**Issue by jtmcdole** [flutter/flutter#47023]
1. Experimenting with WASM compiled CanvasKit.
1. Have images in assets/ + pubspec.yaml
1. Have a full screen app with background and carousel of images.

```
flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true
```

Expected: Flutter renders
Outcome: White screen when using webp. Fully rendered when switched to png or jpg.

**Comment by iapicca** [comment]
Hi @jtmcdole 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by jtmcdole** [comment]
I'll try to repro here at home; this was at work on a freshly updated, external flutter-dev checkout.

**Comment by hterkelsen** [comment]
It seems like Skia already supports decoding webp, it's just not exposed in CanvasKit.

@kjlubick how difficult do you think this would be to add to CanvasKit's image decoding support?

**Comment by hterkelsen** [comment]
This was fixed in CanvasKit upstream: https://skia-review.googlesource.com/c/skia/+/262928

Once CanvasKit 0.11 is released I'll update the flutter engine and this should be fixed

**Comment by darran-kelinske-fivestars** [comment]
0.11 was released, correct?

https://skia.googlesource.com/skia.git/+/032aa7217845348966e7b670bbab53d6b2401722/modules/canvaskit/CHANGELOG.md

**Comment by kjlubick** [comment]
Yep
