### ISSUE TITLE
[ver1.12] image_picker does not work in Flutter Module 

### ISSUE THREAD

**Issue by axilesoft** [flutter/flutter#47021]
After upgrading to Flutter 1.12 , image_picker does not work in Flutter Module (FlutterView).

And pub get , it says
> The plugin `image_picker` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.

**Comment by iapicca** [comment]
Hi @axilesoft 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by axilesoft** [comment]
It may be not a bug, just need to be upgraded to v2 API.

I'm now using 1.13.  "flutter run“ has no problem. 
But when it's a flutter module (FlutterView) in a  FullscreenActivity java application, it does not work.

**Comment by iapicca** [comment]
that's a good insight, thank you for your feedback @axilesoft

**Comment by iapicca** [comment]
Hi @axilesoft 
I see there's an open [issue](https://github.com/flutter/flutter/issues/46079) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
