### ISSUE TITLE
Navigator should support starting with an initial history

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4702]
Instead of just pushing the initialRoute, we should split it on / and push every step of the route. So if the initialRoute is "/foo/bar/baz", we should first push "/", then "/foo", then "/foo/bar", then "/foo/bar/baz".

cc @devoncarew

**Comment by abarth** [comment]
Hum...  I'm not sure we want to force that sort of structure on route names.  You should be able to load an initial history with more than one route pushed, but we should probably do that by taking a list of route names rather than but splitting a single route name on `/`.

**Comment by abarth** [comment]
I think we'll be able to add this feature in a way that doesn't break the API.

**Comment by kelegorm** [comment]
I don't think setting bunch of routes instead one `/foo/bar/baz` is a good idea. For example, consider Google Inbox application. I has "Add Reminder" widget which run application in route of adding reminder, and back action leads to close application. And it is a good behaviour.

**Comment by Hixie** [comment]
We support this today actually, both ways. If your routes use `/`, we push the whole stack, if they use `:` or some other separator, we only push the one route.

**Comment by kelegorm** [comment]
Can we add it (":route" usage) to docs?

**Comment by Hixie** [comment]
Yeah, see https://github.com/flutter/flutter/issues/11607 for the bug tracking the documentation efforts around routes.
