### ISSUE TITLE
shared_preferences fatal error: 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by emadd** [flutter/flutter#47036]
I've run flutter clean

Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    In file included from /Users/erikmadsen/development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/ios/Classes/FLTSharedPreferencesPlugin.m:5:
    /Users/erikmadsen/development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/ios/Classes/FLTSharedPreferencesPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    /Users/erikmadsen/development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/ios/Classes/FLTSharedPreferencesPlugin.h:5:9: note: did not find header 'Flutter.h' in framework
    'Flutter' (loaded from '/Users/erikmadsen/Documents/Projects/project/ios/Flutter')
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target
    'image_picker' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target
    'image_picker' from project 'Pods')

[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.12.13+hotfix.6 at /Users/erikmadsen/development/flutter
    • Framework revision 18cd7a3601 (3 days ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/erikmadsen/development/Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/erikmadsen/development/Android
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • E3602791-9AE9-41DD-9909-069ECF089BCB • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

**Comment by emadd** [comment]
Fixed with "flutter create --org com.mydomain ." and then restoring previous manual changes made within android and ios folders

**Comment by rahmanfasalu** [comment]
can you explain the steps you did, am having the same issue now.
![Screenshot 2019-12-18 at 15 20 21](https://user-images.githubusercontent.com/3534052/71093700-ff061600-21a9-11ea-8ca7-e874502e7ba8.png)
