### ISSUE TITLE
CupertinoDatePicker not taking changes (onDateTimeChanged not working)

### ISSUE THREAD

**Issue by kimjaehu** [flutter/flutter#47035]
Hi, 

I was wondering if anybody is having the same issue that I am having with CupertinoDatePicker which suddenly started not taking changes after today's update.

When I drag the dates, it moves back to initial date without printing anything.
No errors in the code or other codes in debug console.

below is the code for the date picker:
        CupertinoDatePicker(
                  initialDateTime: _date,
                  minimumDate: dob,
                  minimumYear: dob.year,
                  maximumDate: _date,
                  maximumYear: _date.year,
                  mode: CupertinoDatePickerMode.date,
                  onDateTimeChanged: (pickedDate) {
                    print(pickedDate); //no print
                   }

Your help is greatly appreciated.

Thank you.

**Comment by LongCatIsLooong** [comment]
Check your `minimumDate` and `maximumDate`. The callback won't report the new date selected if it's invalid (out of range), and once let go the picker will automatically scroll to the closest valid date.

**Comment by kimjaehu** [comment]
Oh wow...it works.

Thank you very much.
