### ISSUE TITLE
flutter doctor --android licenses crashes on java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by JerryMatera** [flutter/flutter#47042]
![Screenshot from 2019-12-14 15-58-42](https://user-images.githubusercontent.com/50982093/70849075-bfc68500-1e8a-11ea-929c-06c9b17dc75e.png)

**Comment by rahuldange09** [comment]
To resolve, try running flutter doctor --android-licenses. This should prompt you to accept licenses (it may ask you first, in case just type y and press enter - although it should tell you that).

**Comment by JerryMatera** [comment]
![Screenshot from 2019-12-14 16-37-59](https://user-images.githubusercontent.com/50982093/70849495-35811f80-1e90-11ea-9a51-dc937d27aaf2.png)

**Comment by rahuldange09** [comment]
The solution is already there in screenshot
run ******

**Comment by JerryMatera** [comment]
Can't figure out the solution just yet,  sdkmanager doesn't update.

**Comment by iapicca** [comment]
Hi @JerryMatera 
does running the command suggested in the error 
and consequently `flutter doctor --android-licenses`
fix the issue?

Please refrain from posting pictures if not necessary.

Thank you

**Comment by JerryMatera** [comment]
@iapicca it doesn't solve the problem. i already posted the output of that command above

**Comment by iapicca** [comment]
Hi @JerryMatera 
 `--licence` should be run after `--update`,
did you manage to get your SDK recognized?
thank you

**Comment by JerryMatera** [comment]
it did't work

**Comment by jonahwilliams** [comment]
See https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-a

This can be an issue if your Java version is not in sync with Android studio

**Comment by michaelmairegger** [comment]
For me installing `Android SDK Command-line Tools` fixed this issue

**Comment by exerror14** [comment]
[[Solved] flutter doctor –android-licenses gives a java error](https://fluttercorner.com/flutter-doctor-android-licenses-gives-a-java-error/)
