### ISSUE TITLE
[BLOCKING] Dart obfuscation mapping json file is not created

### ISSUE THREAD

**Issue by talent-apps** [flutter/flutter#47049]
Dart obfuscation mapping *.json file is not created when building an android app bundle.

The `gradle.properties` file under the root/android/ folder is set as follows:

```
org.gradle.jvmargs=-Xmx4G

android.useAndroidX=true
android.enableJetifier=true

extra-gen-snapshot-options=--obfuscate,--save-obfuscation-map=build/symbols.json
android.enableR8=false
```
But when running `flutter build appbundle`, the `symbols.json` file is **NOT** created.

Notes:
- **This is a blocker for issuing new android releases** since the json file is needed in order to deobfuscate crashlytics reports that originate from dart code.

- This feature used to work previously.

- A warning related to dart obfuscation that used to appear in the build output, does **NO** longer appear there:
> This VM has been configured to obfuscate symbol information which violates the Dart standard.

- When downgrading to `v1.9.1+hotfix.6 ` the above warning appears in the build output and the `symbols.json` file is created as usual.

Output of `flutter doctor -v`:

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (4 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\XXX\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\XXX\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\XXX\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1
```

**Comment by talent-apps** [comment]
After manually integration the above PR into the local flutter repo, the json file is still **NOT** generated.
Is something missing?

**Comment by jonahwilliams** [comment]
@talent-apps if you patched the source code in locally, you need to follow the instructions at https://github.com/flutter/flutter/tree/master/packages/flutter_tools#forcing-snapshot-regeneration

**Comment by jonahwilliams** [comment]
Ahh you're right, this isn't quite ready yet. I have a new commit that I've verified locally though. thanks for the patience on this one
